### PR TITLE
v1.16 Backports 2024-07-08

### PR DESCRIPTION
**Pull request by jibi**
* [x] #33447 (@jrajahalme)
 * [x] #33448 (@jrajahalme)
 * [x] #33442 (@aditighag)
 * [x] #33153 (@giorio94)
 * [x] #33403 (@sayboras)
 * [x] #33444 (@brb)
 * [x] #33445 (@bimmlerd)
 * [x] #33514 (@aanm)
 * [x] #33509 (@julianwiedmann)
 * [x] #33516 (@cdtzabra)
 * [x] #33498 (@ysksuzuki)
 * [x] #33420 (@gandro)
 * [x] #33472 (@jasonaliyetti)
 * [x] #33526 (@rastislavs)
 * [x] #33505 (@saintdle)
 * [x] #33512 (@jasonaliyetti)
 * [x] #33504 (@pchaigno)
 * [x] #33564 (@pchaigno)
 * [x] #33486 (@sayboras) :warning: resolved conflicts
   * please double check this commit is needed as the previous digest was different than the one in main
 * [x] #33567 (@yushoyamaguchi)
 * [x] #33389 (@nathanjsweet)
 * [x] #33524 (@julianwiedmann)
 * [x] #33551 (@julianwiedmann)
 * [x] #33569 (@chaunceyjiang)
 * [x] #33485 (@mhofstetter)
 * [x] #33446 (@balous)
 * [x] #33511 (@skmatti)
 * [x] #33449 (@jrajahalme)
 * [x] #33278 (@bimmlerd)
 * [x] #33537 (@rastislavs)
 * [x] #33624 (@julianwiedmann)
 * [x] #33599 (@rgo3)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33447 33448 33442 33153 33403 33444 33445 33514 33509 33516 33498 33420 33472 33526 33505 33512 33504 33564 33486 33567 33389 33524 33551 33569 33485 33446 33511 33449 33278 33537 33624 33599
```

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commits :+1:

**Review by rastislavs — APPROVED** [review]

**Review by mhofstetter — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
My commits look good, thanks!

**Comment by jibi** [comment]
/test-backport-1.16

**Review by gandro — APPROVED** [review]

**Review by rgo3 — APPROVED** [review]

**Review by bimmlerd — APPROVED** [review]
thanks!

**Review by nathanjsweet — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
My two PRs look good. Thanks!

**Review by aanm — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
Also looks good for https://github.com/cilium/cilium/pull/33569https://github.com/cilium/cilium/pull/33569

**Review by ghost — APPROVED** [review]
#33505 good

**Review by pchaigno — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
Looks good for https://github.com/cilium/cilium/pull/33446 as well.

**Comment by jibi** [comment]
(rebased and fixed the backport note on all commit messages)

**Review by aditighag — APPROVED** [review]

**Review by brb — APPROVED** [review]
Thanks!

**Review by jrajahalme — APPROVED** [review]
Thanks for the backports!

**Pull request merged**
