### PR TITLE
v1.10 backports 2021-09-29

### PR DESCRIPTION
**Pull request by jibi**
* ~#14254 -- operator: add identity GC metrics (@ArthurChiao)~
   * skipped due to some non trivial conflicts
 * #17382 -- docs: Fix up broken minikube link (@joestringer)
 * #17288 -- docs: Fix version sorting for CRD schema docs (@joestringer)
 * #17329 -- Remove CiliumNode deletion logic from CiliumNode watcher and guarantee CiliumNode's OwnerReference is always set (@christarazi)
 * #17359 -- operator: Improve identity GC efficiency (@christarazi)
 * #17378 -- bugtool: Include listing of egress gateway map (@pchaigno)
 * #16264 -- docs: Fix command for overwriting iptables on kube-proxy replacement install (@Stijn98s)
 * #17230 -- daemon: Add --derive-masquerade-ip-addr-from-device opt (@brb)
   * Minor conflict, moved the `c.DeriveMasqIPAddrFromDevice` assignment inside `populateMasqueradingSettings()`
 * #17424 -- contrib/backporting: add environment variables to set ORG and REPO (@aanm)
 * #17411 -- hubble: Display proxy redirects in policy verdict events (@pchaigno)
   * Minor conflict: rebuilt the hubble API protobufs with `make generate-hubble-api`
 * #17417 -- pkg/k8s: fix User-Agent for kubernetes client (@aanm)
 * #17439 -- helm: upgrade envoy to v1.18.4 for hubble-ui (@geakstr)
   * minor conflict: in `values.yaml` I kept the `pullPolicy` to `IfNotPresent` (as opposed to what we have in master, i.e. `Always`) and running `make -C install/kubernetes` updated also `certgen` to `v0.1.5`
 * #17432 -- Fix FQDN memory leak (@aanm)
 * #16585 -- pkg/identity: Add missing labels to well-known identities (@mauriciovasquezbernal)
 * #17477 -- helm: set correct versions of docker images in Makefile (@aanm)
 * #17418 -- Fix bug where IP addresses of devices in unknown state are resolved as remote-node (@jibi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 17382 17288 17329 17359 17378 16264 17230 17424 17411 17417 17439 17432 16585 17477 17418; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by jibi** [comment]
test-backport-1.10

**Review by pchaigno — APPROVED** [review]
My PRs look good :+1:

**Comment by jibi** [comment]
test-backport-1.10

**Comment by jibi** [comment]
test-backport-1.10

**Review by joestringer — APPROVED** [review]
For docs & GH workflows changes:

**Review by aanm — APPROVED** [review]
LGTM for my commits. Thanks!

**Review by nebril — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Pull request merged**
