### PR TITLE
cilium: sockops #define AF_INET{6} if not already defined

### PR DESCRIPTION
**Pull request by jrfastab**
Cilium fails to compile bpf_sockops.o because /usr/include/asm doesn't
exist on the docker image

error:
level=error msg="Failed to compile bpf_sockops.o: exit status 1" compiler-pid=228 linker-pid=229 subsys=datapath-loader
level=warning msg="In file included from /var/lib/cilium/bpf/sockops/bpf_sockops.c:29:" subsys=datapath-loader
level=warning msg="In file included from /usr/include/sys/socket.h:33:" subsys=datapath-loader
level=warning msg="/usr/include/bits/socket.h:390:10: fatal error: 'asm/socket.h' file not found" subsys=datapath-loader
level=warning msg="#include <asm/socket.h>" subsys=datapath-loader
level=warning msg=" ^" subsys=datapath-loader
level=warning msg="1 error generated." subsys=datapath-loader
level=error msg="failed compile sockops/bpf_sockops.c: Failed to compile bpf_sockops.o: exit status 1" subsys=sockops
level=error msg="Failed to compile bpf_redir.o: exit status 1" compiler-pid=231 linker-pid=232 subsys=datapath-loader
level=warning msg="In file included from /var/lib/cilium/bpf/sockops/bpf_redir.c:29:" subsys=datapath-loader
level=warning msg="In file included from /usr/include/sys/socket.h:33:" subsys=datapath-loader
level=warning msg="/usr/include/bits/socket.h:390:10: fatal error: 'asm/socket.h' file not found" subsys=datapath-loader
level=warning msg="#include <asm/socket.h>" subsys=datapath-loader
level=warning msg=" ^" subsys=datapath-loader
level=warning msg="1 error generated." subsys=datapath-loader
level=error msg="failed compile sockops/bpf_redir.c: Failed to compile bpf_redir.o: exit status 1" subsys=sockops

Reported-by: Nirmoy Das ndas@suse.de
Signed-off-by: John Fastabend <john.fastabend@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6216)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Review by joestringer — COMMENTED** [review]
Do we need another piece here, like removal of the `sys/socket.h` include? It's not obvious to me that the failure report in the commit message could be resolved by just #defining these symbols.

**Comment by vadorovsky** [comment]
If `sys/socket.h` include would be removed, then `ifndef AF_INET{6}` statements would be always true, I guess. After removing `sys/socket.h` include we could just define everything we need without `ifndef`. Am I right? But I probably like @jrfastab's solution more.

**Comment by joestringer** [comment]
I'm fine with this if it solves the issue, I'm just saying that this message:

```
level=warning msg="In file included from /usr/include/sys/socket.h:33:" subsys=datapath-loader
level=warning msg="/usr/include/bits/socket.h:390:10: fatal error: 'asm/socket.h' file not found" 
```

Seems to indicate that if you include `sys/socket.h` then it will attempt to include `asm/socket.h` and if it gets that far, the compile will fail. If defining AF_INET{6} is enough to stop that happening, then no further changes are necessary, LGTM.

**Comment by ianvernon** [comment]
@jrfastab please rebase.

**Comment by jrfastab** [comment]
@nirmoy I'm trying to recall, do we still need this? If so I'm happy to rebase it otherwise I'll close it.

**Comment by nirmoy** [comment]
@joestringer I guess no, I don't see the warning any more.

**Comment by jrfastab** [comment]
Closing this if the warning appears we can rebase and apply. I've never been able to repro myself.

**Pull request closed without merging**
