### PR TITLE
Backport/v1.1 20180625

### PR DESCRIPTION
**Pull request by raybejjani**
* PR: 4626 -- Fix nested indentation for Upgrade notes for 1.1 (@iamShantanu101) -- https://github.com/cilium/cilium/pull/4626
* PR: 4620 -- Fix golang 1.10 build on Ubuntu with snap packages (@joestringer) -- https://github.com/cilium/cilium/pull/4620
* PR: 4587 -- Allocate ipcache mappings for service backends (@joestringer) -- https://github.com/cilium/cilium/pull/4587
* PR: 4303 -- Improve contributor guide (@tgraf) -- https://github.com/cilium/cilium/pull/4303

@joestringer I saw conflicts (and perhaps a previous backport) for https://github.com/cilium/cilium/pull/4587 so you should review this

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4632)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-docs-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
@joestringer oh, nevermind. Your PR was already backported, and I apparently managed to resolve it like the previous merge. All those commits were no-ops.

**Comment by joestringer** [comment]
@raybejjani Ah, okay. It musn't have been referenced properly in the GH issues/PR during its backport, then.

It seems like they're all no-op commits, so they could be dropped entirely before merge.

**Pull request merged**
