### PR TITLE
Upgrade ginkgo

### LINKED ISSUE #19687: test: Upgarde gingko to v2
Related to the comment https://github.com/cilium/cilium/pull/19248#issuecomment-1081561295

As gingko v1 is EOL, we should consider to upgrade it to v2.

### PR DESCRIPTION
**Pull request by pigletfly**
Signed-off-by: pigletfly <wangbing.adam@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: https://github.com/cilium/cilium/issues/19687

### CODE REVIEW

**Comment by rolinh** [comment]
Thanks for your contribution! It looks like some of the failures are legit, e.g.:
```
 #27 10.69 ../test/ginkgo-ext/scopes.go:78:58: cannot use ginkgo.Context (variable of type func(text string, args ...interface{}) bool) as type func(string, func()) bool in argument to wrapContextFunc
```

**Comment by pigletfly** [comment]
> Thanks for your contribution! It looks like some of the failures are legit, e.g.:
> 
> ```
>  #27 10.69 ../test/ginkgo-ext/scopes.go:78:58: cannot use ginkgo.Context (variable of type func(text string, args ...interface{}) bool) as type func(string, func()) bool in argument to wrapContextFunc
> ```

yes, I am working on this. It seems there are some incompatible changes.

**Comment by tklauser** [comment]
@pigletfly Are you still working on this? It looks like the branch picked up a merge conflict and needs a rebase. I'll mark the PR as draft until this is resolved. Please feel free to mark the PR ready to review once the merge conflicts and the build failures are resolved.

**Comment by pigletfly** [comment]
> @pigletfly Are you still working on this? It looks like the branch picked up a merge conflict and needs a rebase. I'll mark the PR as draft until this is resolved. Please feel free to mark the PR ready to review once the merge conflicts and the build failures are resolved.

rebased, and I will finish the ginkgo upgrade ASAP.

**Pull request closed without merging**
