### PR TITLE
pkg/sockops: replace filepath related string concatenation with filepath.Join

### PR DESCRIPTION
**Pull request by nirmoy**
cleaup code that replaces string concatenation with Go's filepath.Join()

Signed-off-by: Nirmoy Das <ndas@suse.de>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6716)

### CODE REVIEW

**Comment by nirmoy** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by nirmoy** [comment]
test-me-please

**Comment by nirmoy** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Review by vadorovsky — APPROVED** [review]

**Comment by vadorovsky** [comment]
test-me-please

**Comment by nirmoy** [comment]
Something is broken but I don't understand how this change is responsible for that.

Cluster health:      1/2 reachable   (2019-01-23T11:34:27Z)
  Name               IP              Reachable   Endpoints reachable
  k8s2 (localhost)   192.168.36.12   true        false

**Comment by nirmoy** [comment]
test-me-please

**Comment by vadorovsky** [comment]
@nirmoy I don't think that your change breaks anything. Just rebase and write `test-me-please` again. Maybe you are hitting some CI flake which was fixed in meantime. This has nothing to do with your changes:

```13:38:43 • Failure [48.510 seconds]
13:38:43 K8sHealthTest
13:38:43 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
13:38:43   checks cilium-health status between nodes [It]
13:38:43   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:408
13:38:43 
13:38:43   Expected
13:38:43       <string>: Connection timed out
13:38:43   to be empty
13:38:43 
13:38:43   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Health.go:110
```

**Comment by nirmoy** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
