### PR TITLE
auth: streamline logging

### PR DESCRIPTION
**Pull request by mhofstetter**
This PR streamlines logging within the auth package.

* replacing package global logger with injected one (by hive)
* use structured logging with fields
* remove prefix `auth:` from the message itself (which is a duplicate of the field `subsys`)
* Start log messages in uppercase

For more detail - have a look at the individual commits.

### CODE REVIEW

**Comment by mhofstetter** [comment]
rebased to `main` to fetch fix for https://github.com/cilium/cilium/issues/25968

**Comment by mhofstetter** [comment]
rebased to `main` without any changes to get and check against the latest auth changes

**Review by youngnick — APPROVED** [review]
LGTM, nice work.

**Comment by mhofstetter** [comment]
[ci-ginkgo testrun](https://github.com/cilium/cilium/actions/runs/5210344520/jobs/9401345460#step:69:741) failed with https://github.com/cilium/cilium/issues/25964 -> won't retry because it's not required

**Pull request merged**
