### PR TITLE
Envoy: Update to 1.13.1

### PR DESCRIPTION
**Pull request by jrajahalme**
Update Envoy to the latest release to be ready for Istio 1.5 update.

```release-note
Cilium host proxy has has been updated to Envoy release 1.13.1.
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10222)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Looks like an unrelated failure in Kafka test teardown:
```
14:35:41  • Failure in Spec Teardown (AfterEach) [16.932 seconds]
14:35:41  RuntimeKafka
14:35:41  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
14:35:41    Kafka Policy Role Ingress [AfterEach]
14:35:41    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
14:35:41  
14:35:41    Expected command: sudo cilium config ConntrackLocal=false 
[2020-02-19T22:35:41.081Z]   To succeed, but it failed:
[2020-02-19T22:35:41.081Z]   Exitcode: 1 
[2020-02-19T22:35:41.081Z]   Stdout:
[2020-02-19T22:35:41.081Z]    	 
[2020-02-19T22:35:41.081Z]   Stderr:
[2020-02-19T22:35:41.081Z]    	 Error: Error while retrieving configuration: Get http:///var/run/cilium/cilium.sock/v1/config: dial unix /var/run/cilium/cilium.sock: connect: connection refused
[2020-02-19T22:35:41.081Z]   	 Is the agent running?
[2020-02-19T22:35:41.081Z]   	 
[2020-02-19T22:35:41.081Z]   
```
Looks like Cilium may have crashed, causing `sudo cilium config` to fail.

**Comment by jrajahalme** [comment]
Letting the failing test run finish to get the artifacts.

**Comment by jrajahalme** [comment]
Unfortunately no meaningful artifacts were collected, likely due to test failing in AfterEach. Opened a new issue to track the collection of artifacts in this case: #10266

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Marked this `dont-merge` as we may want to update the 1.12 based images before moving to 1.13.

**Review by raybejjani — APPROVED** [review]

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Pull request merged**
