### PR TITLE
 Move connector package from endpoint to datapath

### PR DESCRIPTION
**Pull request by nathanjsweet**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Moved the sub package, "connector", from the "endpoint" package to the "datapath" package in order to continue to decouple common code from being Linux specific.
```release-note
Moved the sub package, "connector", from the "endpoint" package to the "datapath" package in order to continue to decouple common code from being linux specific.
```

### CODE REVIEW

**Review by gandro — COMMENTED** [review]
Thanks! The commit itself looks good! 

Your commits are missing the `Signed-Off-By` bit however (use `git commit -s` to add it) and please add the appropriate release-notes label (in this case probably `misc`), see the [guide](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request) for more details.

**Review by aanm — CHANGES_REQUESTED** [review]
Can you add answer to "why?" in the commit message? Thanks

**Review by errordeveloper — DISMISSED** [review]
LGTM

**Comment by errordeveloper** [comment]
@nathanjsweet please do either fill out the template or delete the text, some justification would be useful actually, also do have a look at git log, there is a simple commit message style that we tend to follow in Cilium project :)

**Review by joestringer — APPROVED** [review]
Great start, I look forward to `pkg/endpoint` becoming less and less dependent on the datapath :smile: 

The entire contents of the quote in your PR description will be the release note, so please replace the `<!---` line. As Ilya mentioned, please also review what's in the PR message and either confirm the boxes or delete the entire template message so that reviewers can easier understand the intent of the changes in this PR.

The changes themselves look good, so assuming you sign off and get the CI to pass this should be good to go.

**Review by aanm — APPROVED** [review]

**Comment by joestringer** [comment]
test-me-please

**Comment by nathanjsweet** [comment]
test-with-kernel

**Comment by joestringer** [comment]
I dug into the `Cilium-Tests-With-Kernel` link:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/231/

The failure includes `JoinEp`; when I opened it up and found the `kube-system-cilium-.....log` file with `JoinEp` in it, there's also the `Unable to allocate memory` error, which is known flake #10821 .

We can ignore this failure as irrelevant to this PR.

**Pull request merged**
