### PR TITLE
cli: Add support to exclude certain nodes on EKS clusters from the OS check

### LINKED ISSUE #36320: Encounter cluster has nodes with different OS images issue when using 1.17.0-pre.3
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

environment: 1.17.0-pre.3
cilium-cli: built locally with 1.17.0-pre.3 source

When trying out new 1.17.0-pre.3, I noticed that the old cli is not compatible with new cilium version, so a new cli is built and used. In our EKS cluster, we do have two different OSes: 
* AL2 which is used in fargate node hosting Karpenter
* Bottlerocket is configured on nodes provisioned by Karpenter 

we do have nodeSelector in cilium values file for cilium agents/ operators/ envoys workloads. And in earlier version, our approach works well. This behavior breaks in 1.17.0-pre.3 (not in .2) with below error
```
cilium upgrade cilium cilium/cilium --namespace kube-system --version "$cilium_version" --values cilium-values.yaml       --set cluster.id=1       --set "cluster.name=${cluster_name}"       --set "eni.iamRole=${cilium_role_arn}"       --set "serviceAccounts.operator.annotations.eks\.amazonaws\.com/role-arn=${cilium_role_arn}" --set "k8sServiceHost=${cluster_api_endpoint}"
🔮 Auto-detected Kubernetes kind: EKS
ℹ️  Using Cilium version 1.17.0-pre.3
ℹ️  Using cluster name "truong-test-cluster"
🔮 Auto-detected kube-proxy has been installed
❌ Could not detect AWS node image family, defaulted to fallback value: Custom

Error: Unable to upgrade Cilium: cluster has nodes with different OS images: 'AmazonLinux2' and 'Bottlerocket'
```

 I guess it might be related to [this feature](https://github.com/cilium/cilium/pull/36076/files#diff-0b6dc304261e14febe58bbc9f05a9358eb47cfb9e85673ab0c7aec413dfd6ed7).

### How can we reproduce the issue?

environment: 1.17.0-pre.3
cilium-cli: built locally with 1.17.0-pre.3 source

When trying out new 1.17.0-pre.3, I noticed that the old cli is not compatible with new cilium version, so a new cli is built and used. In our EKS cluster, we do have two different OSes: 
* AL2 which is used in fargate node hosting Karpenter
* Bottlerocket is configured on nodes provisioned by Karpenter 

we do have nodeSelector in cilium values file for cilium agents/ operators/ envoys workloads. And in earlier version, our approach works well. This behavior breaks in 1.17.0-pre.3 (not in .2) with below error
```
cilium upgrade cilium cilium/cilium --namespace kube-system --version "$cilium_version" --values cilium-values.yaml       --set cluster.id=1       --set "cluster.name=${cluster_name}"       --set "eni.iamRole=${cilium_role_arn}"       --set "serviceAccounts.operator.annotations.eks\.amazonaws\.com/role-arn=${cilium_role_arn}" --set "k8sServiceHost=${cluster_api_endpoint}"
🔮 Auto-detected Kubernetes kind: EKS
ℹ️  Using Cilium version 1.17.0-pre.3
ℹ️  Using cluster name "truong-test-cluster"
🔮 Auto-detected kube-proxy has been installed
❌ Could not detect AWS node image family, defaulted to fallback value: Custom

Error: Unable to upgrade Cilium: cluster has nodes with different OS images: 'AmazonLinux2' and 'Bottlerocket'
```

 I guess it might be related to [this feature](https://github.com/cilium/cilium/pull/36076/files#diff-0b6dc304261e14febe58bbc9f05a9358eb47cfb9e85673ab0c7aec413dfd6ed7).

### Cilium Version

1.17.0-pre.3

### Kernel Version

NA

### Kubernetes Version

1.31

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by marcofranssen**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #36320

```release-note
Excludes Fargate nodes from EKS cluster node checks. Overridable from the cli.
```

### CODE REVIEW

**Comment by gandro** [comment]
Thanks for the PR! To make sure I understand this correctly, this PR is obsolete once https://github.com/cilium/cilium/pull/36336 is merged, correct?

**Comment by viktor-kurchenko** [comment]
> Thanks for the PR! To make sure I understand this correctly, this PR is obsolete once #36336 is merged, correct?

Yes, you are right.

**Comment by marcofranssen** [comment]
@gandro indeed. This won't be required if the other PR is merged. Just offering it as an alternative in case you guys want to keep that logic (not sure on the long term goal with that existing logic there).

If you decide to go with @viktor-kurchenko his PR, feel free to close this one.

**Comment by gandro** [comment]
Other PR has been merged. Thanks! Closing.

**Pull request closed without merging**
