### PR TITLE
statedb: Rename statedb2 to statedb

### PR DESCRIPTION
**Pull request by joamaki**
Now that old pkg/statedb has been removed, rename
pkg/statedb2 to pkg/statedb.

### CODE REVIEW

**Review by bimmlerd — APPROVED** [review]

**Comment by joestringer** [comment]
Will this cause backporting issues for statedb features in v1.14?

**Review by christarazi — APPROVED** [review]

**Comment by joamaki** [comment]
> Will this cause backporting issues for statedb features in v1.14?

Would only cause it for L2 announcements, so that should be manageable.

**Review by joestringer — APPROVED** [review]
Looks like tophat got pulled in because of pkg/statedb2. I didn't review in detail but it looks like a straightforward rename. I assume others have looked more closely at the details.

**Pull request merged**
