### PR TITLE
v1.12 Backports 2023-12-05

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #29182 (@viktor-kurchenko)
 * [x] #29566 (@christarazi)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 29182 29566
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
@viktor-kurchenko @christarazi Some minor conflicts were hit, please check commit notes for details.

**Comment by nbusseneau** [comment]
/test-backport-1.12

**Review by christarazi — APPROVED** [review]

**Comment by nbusseneau** [comment]
/test-backport-1.12

**Review by chancez — APPROVED** [review]
Metrics changes LGTM.

**Review by viktor-kurchenko — APPROVED** [review]
My commit looks good. Thanks!

**Review by ti-mo — APPROVED** [review]

**Comment by nbusseneau** [comment]
/test-1.17-4.9

**Pull request merged**
