### PR TITLE
k8s: Use slim Node in LocalNode Resource and K8s watchers

### PR DESCRIPTION
**Pull request by joamaki**
We were performing unnecessary conversions from corev1.Node to slim_corev1.Node.
Only blocker for using slim_corev1.Node was the missing ProviderID.

### CODE REVIEW

**Review by nebril — APPROVED** [review]
LGTM!

**Review by dylandreimerink — APPROVED** [review]

**Review by tommyp1ckles — APPROVED** [review]

**Comment by aditighag** [comment]
@joamaki None of the e2e tests were triggered for your last `test` command. Is that expected? Would we need to close and reopen the PR so that all the tests are forcefully triggered?

**Comment by joamaki** [comment]
> @joamaki None of the e2e tests were triggered for your last `test` command. Is that expected? Would we need to close and reopen the PR so that all the tests are forcefully triggered?

Huh, that's odd. I'll rebase and try again and if that doesn't do it, I'll close and reopen.

**Pull request merged**
