### PR TITLE
v1.9 backports 2021-02-24

### PR DESCRIPTION
**Pull request by twpayne**
* #14993 -- Move Azure IPAM out of beta (@tgraf)
 * #14951 -- kpr: Make it possible to run bpf_sock on Kind (@brb)
 * #14943 -- helm: Fix and add missing podLabels (@Subreptivus)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14993 14951 14943; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by aditighag** [comment]
test-backport-1.9

**Comment by aditighag** [comment]
@twpayne Let me know if you want me to update the commit description - 

```
 * #14993 -- Move Azure IPAM out of beta (@tgraf)
 * #14951 -- kpr: Make it possible to run bpf_sock on Kind (@brb)
 * #14943 -- helm: Fix and add missing podLabels (@Subreptivus)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14993 14951 14943; do contrib/backporting/set-labels.py $pr done 1.9; done
```
```

**Comment by aditighag** [comment]
@twpayne Can you also backport the missed commit from 3rd change? Here is the relevant comment - https://github.com/cilium/cilium/pull/15101#issuecomment-785405658

**Comment by twpayne** [comment]
> Can you also backport the missed commit from 3rd change?

Done. I cherry picked it onto this branch.

**Comment by twpayne** [comment]
Closing this as we didn't get it merged in time.

**Comment by aditighag** [comment]
test-*-4.9

**Comment by aditighag** [comment]
test-backport-1.9

**Comment by twpayne** [comment]
test-missed-k8s

**Comment by twpayne** [comment]
test-gke

**Comment by twpayne** [comment]
test-1.13-4.9

**Comment by nebril** [comment]
test-1.19-4.9

**Comment by twpayne** [comment]
CI failures are being investigated in https://github.com/cilium/cilium/issues/15169.

**Comment by twpayne** [comment]
test-backport-1.9

**Comment by twpayne** [comment]
The failing test (test-1.17-4.9) is the [same as this](https://github.com/cilium/cilium/pull/15006#issuecomment-783490056).

**Pull request merged**
