### PR TITLE
v1.8 backports 2020-07-23

### PR DESCRIPTION
**Pull request by pchaigno**
* #12589 -- docs: Clarify that identity transfer is an optimization (@pchaigno)
 * #12568 -- daemon: Add "datapath" opt to --debug-verbose flag (@brb)
 * #12607 -- Makefile: process packages in subshells for bench targets (@tklauser)
 * #12556 -- hubble/relay: improve peer connections handling (@Rolinh)
 * #12615 -- docs: move removal of access-log option to correct section (@tklauser)
 * #12618 -- install/kubernetes: remove deprecated tofqdns-enable-poller option (@tklauser)
 * #12623 -- Fixes for EKS NodePort XDP getting started guide (@tklauser)
 * #12605 -- etcd: Fix several etcd related issues (@tgraf)
 * #12606 -- fqdn/dnsproxy/proxy_test: increase again timeout for DNS TCP exchanges (@qmonnet)
* k8s: Fix CRD schema version to 1.21.1

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12589 12568 12607 12556 12615 12618 12623 12605 12606; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]
> * #12606 -- fqdn/dnsproxy/proxy_test: increase again timeout for DNS TCP exchanges (@qmonnet)

Looks good :+1:

**Review by tklauser — APPROVED** [review]
:+1: for my changes

**Review by rolinh — APPROVED** [review]
Looks good for my changes as well :+1:

**Review by brb — APPROVED** [review]
LGTM for my changes.

**Comment by pchaigno** [comment]
test-backport-1.8

**Comment by aanm** [comment]
test-upstream-k8s

**Pull request merged**
