### PR TITLE
install: don't render role / rolebinding when agent disabled

### LINKED ISSUE #23819: Unable to run pre-flight in Cilium 1.13.90 on an upgrade from 1.13.0
```
minikube start --network-plugin=cni --kubernetes-version=v1.24.7
```

```
git checkout origin/v1.13
```
```
helm install cilium ./install/kubernetes/cilium --version=1.13 --namespace=kube-system  --set clustermesh.apiserver.image.repository=quay.io/cilium/clustermesh-apiserver-ci  --set operator.image.suffix=-ci  --set hubble.relay.image.useDigest=false  --set logSystemLoad=true  --set hubble.eventBufferCapacity=65535  --set bpf.preallocateMaps=false  --set debug.enabled=true  --set hubble.relay.image.repository=quay.io/cilium/hubble-relay-ci  --set bandwidthManager.enabled=false   --set image.useDigest=false  --set debug.verbose=flow  --set kubeProxyReplacement=disabled  --set ipv4NativeRoutingCIDR=10.0.0.0/8  --set ipv4.enabled=true  --set hubble.relay.image.tag=v1.13  --set hubble.listenAddress=:4244  --set pprof.enabled=true  --set preflight.image.tag=ea67e91f6ebe25656b9305402e6a24e29138dabe  --set operator.image.useDigest=false  --set operator.image.tag=v1.13  --set preflight.image.useDigest=false  --set etcd.leaseTTL=30s  --set preflight.image.repository=quay.io/cilium/cilium-ci  --set ipv6NativeRoutingCIDR=fd02::/112  --set ipam.operator.clusterPoolIPv6PodCIDR=fd02::/112  --set operator.image.repository=quay.io/cilium/operator  --set k8s.requireIPv4PodCIDR=true  --set enableCnpStatusUpdates=true  --set hubble.enabled=true  --set ipv6.enabled=true  --set image.repository=quay.io/cilium/cilium-ci  --set image.tag=v1.13  --set clustermesh.apiserver.image.tag=v1.13  --set bpf.masquerade=false  --set sessionAffinity=false
```
wait for it to be installed...
```
git checkout origin/master
```
```
helm install cilium-preflight ./install/kubernetes/cilium --version=1.13.90 --namespace=kube-system  --set operator.image.repository=quay.io/cilium/operator  --set pprof.enabled=true  --set ipv4NativeRoutingCIDR=10.0.0.0/8  --set ipv4.enabled=true  --set config.enabled=false   --set preflight.image.useDigest=false  --set logSystemLoad=true  --set hubble.eventBufferCapacity=65535  --set ipv6.enabled=true  --set nodeinit.enabled=false  --set preflight.image.tag=ea67e91f6ebe25656b9305402e6a24e29138dabe  --set hubble.relay.image.tag=ea67e91f6ebe25656b9305402e6a24e29138dabe  --set image.tag=ea67e91f6ebe25656b9305402e6a24e29138dabe  --set operator.enabled=false   --set enableCnpStatusUpdates=true  --set ipam.operator.clusterPoolIPv6PodCIDR=fd02::/112  --set bpf.preallocateMaps=false  --set sessionAffinity=false  --set debug.enabled=true  --set image.repository=quay.io/cilium/cilium-ci  --set operator.image.useDigest=false  --set bandwidthManager.enabled=false  --set operator.image.tag=ea67e91f6ebe25656b9305402e6a24e29138dabe  --set preflight.enabled=true   --set hubble.relay.image.repository=quay.io/cilium/hubble-relay-ci  --set k8s.requireIPv4PodCIDR=true  --set operator.image.suffix=-ci  --set hubble.relay.image.useDigest=false  --set debug.verbose=flow  --set ipv6NativeRoutingCIDR=fd02::/112  --set preflight.image.repository=quay.io/cilium/cilium-ci  --set agent=false   --set image.useDigest=false  --set hubble.listenAddress=:4244  --set etcd.leaseTTL=30s  --set hubble.enabled=true  --set kubeProxyReplacement=disabled  --set bpf.masquerade=false  
```

See the error:

> Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: Role "cilium-config-agent" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "cilium-preflight": current value is "cilium"

### PR DESCRIPTION
**Pull request by squeed**
I missed excluding these roles when the agent is disabled.

Fixes: 0dbde96d
Fixes: #23819

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by squeed** [comment]
[Test failure](https://github.com/cilium/cilium/actions/runs/4221456229/jobs/7329728460) looks like a flake; the apiserver went away during a test run; Given that Cilium was successfully installed, this can't have broken it.

**Comment by squeed** [comment]
The only missing tests aren't relevant (ci-verifier, ci-l4lb). Marking as ready to merge.

**Comment by squeed** [comment]
My mistake, missing @tommyp1ckles review :-)

**Review by tommyp1ckles — APPROVED** [review]

**Comment by squeed** [comment]
marking ready-to-merge, no need to run ci-l4lb or ci-verifier. Those don't even use the helm chart.

**Pull request merged**
