### PR TITLE
v1.10: Update Go to 1.16.4

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
test-1.20-4.19

**Comment by aanm** [comment]
@tklauser needs rebase

**Comment by tklauser** [comment]
test-backport-1.10

**Comment by tklauser** [comment]
test-1.20-4.19

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.19/400/

**Comment by tklauser** [comment]
test-1.20-4.19

**Comment by tklauser** [comment]
test-1.19-5.4

**Comment by tklauser** [comment]
test-1.20-4.19

**Pull request merged**
