### PR TITLE
Update Go to 1.18.2

### PR DESCRIPTION
**Pull request by tklauser**
Also bump `go.mod` to 1.18 which was previously omitted. See commit messages for details.

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]
Let's go.

**Comment by tklauser** [comment]
AKS and external workloads are currently failing consistently (on `master` as well). The AKS failure is due to #19788 and the external workloads failure will be fixed by a cilium-cli release containing https://github.com/cilium/cilium-cli/pull/837

All other tests passed and several reviewers approved. Marking as ready to merge.

**Comment by tklauser** [comment]
Rebased (and rebuilt images), reviews are in and all tests except for AKS (which is currently failing consistently and thus marked as not required) passed. Marked as ready to merge.

**Comment by christarazi** [comment]
Needs rebase

**Comment by tklauser** [comment]
> Needs rebase

😭 again? I just rebased and rebuilt today.

**Comment by tklauser** [comment]
> > Needs rebase
> 
> 😭 again? I just rebased and rebuilt today.

Luckly just a simple conflict in `go.sum` which didn't require an image rebuild.

**Pull request merged**
