### PR TITLE
[RFC] build: run kernel checkpatch.pl on diff for bpf/ in precheck

### PR DESCRIPTION
**Pull request by qmonnet**
Although there is no explicit coding style for the BPF code, several developers tend to follow the kernel coding style [conventions][0]. To try and maintain a consistent style all over the code, this commit adds kernel checkpatch.pl to the list of checks performed on the source as part as `make precheck`.

Some details on the check:

- We only run checkpatch.pl on the bpf/ directory.

- We make it part of `make precheck`, so it runs for all builds.

- However we only run it on the latest changes, meaning the changes   returned by `git diff HEAD`. This means that checkpatch.pl will not receive any input if the user (or CI system) has made no change since last commit, in particular there will be no check if a user commit their changes before building. And there is no check enforced on the pull requests.

- Hooking checkpatch.pl for all PRs could be done in the future, if there is sufficient interest in it.

The checkpatch.pl and spelling.txt files (both under GPLv2) are directly copied from the kernel repository, as per commit 4efc61c798cd ("scripts/spelling.txt: add "issus" typo"). File const_structs.checkpatch is not used in our case, but is created blank to avoid a warning message from checkpatch.pl. The script checkpatch.sh (bash script) launches checkpatch.pl with the relevant arguments and options.

[0]: https://www.kernel.org/doc/html/v5.6/process/coding-style.html

### CODE REVIEW

**Comment by qmonnet** [comment]
test-me-please

**Comment by qmonnet** [comment]
test-me-please

**Comment by pchaigno** [comment]
> The checkpatch.pl and spelling.txt files (both under GPLv2) are directly copied from the kernel repository, as per commit 4efc61c798cd ("scripts/spelling.txt: add "issus" typo").

Don't we also need to have a `COPYING` file to explicitly state the license (as in the `bpf/` directory)? I don't think SPDX comments are enough.

> Hooking checkpatch.pl for all PRs could be done in the future

Did you try that? How bad is it? :worried:

**Comment by qmonnet** [comment]
> > The checkpatch.pl and spelling.txt files (both under GPLv2) are directly copied from the kernel repository, as per commit 4efc61c798cd ("scripts/spelling.txt: add "issus" typo").
> 
> Don't we also need to have a `COPYING` file to explicitly state the license (as in the `bpf/` directory)? I don't think SPDX comments are enough.

I don't know, but no harm in adding the file. Will do.

> 
> > Hooking checkpatch.pl for all PRs could be done in the future
> 
> Did you try that? How bad is it? worried

For all new PRs I meant. For current code base:

``` shell
find bpf -regex ".*.\(c\|h\)" -print0 | xargs -0 checkpatch.pl --no-tree --strict -f
```
* `ERROR`: 315
* `WARNING`: 4484
* `CHECK`: 687

**Comment by borkmann** [comment]
Have you also tried sparse and cppcheck and the like to integrate as precheck? Would be nice to have. :-)

**Comment by qmonnet** [comment]
> Have you also tried sparse and cppcheck and the like to integrate as precheck? Would be nice to have. :-)

I have not (I didn't know how checkpatch would be received), but could do as a follow-up.

Which one do you have in mind for “the like”?

- sparse
- cppcheck
- xmastree.py
- ... [feel free to edit]

**Comment by qmonnet** [comment]
test-me-please

**Comment by borkmann** [comment]
> > Have you also tried sparse and cppcheck and the like to integrate as precheck? Would be nice to have. :-)
> 
> I have not (I didn't know how checkpatch would be received), but could do as a follow-up.
> 
> Which one do you have in mind for “the like”?
> 
> * sparse
> * cppcheck
> * xmastree.py
> * ... [feel free to edit]

I personally don't care too much about xmastree, but we once had discussed coccinelle tool which could then also run against all scripts in https://github.com/cilium/cilium/tree/master/contrib/coccinelle . Latter we can then extend over time with more useful things to catch for BPF code base. So I'd be happy for everything that would help us find potential bugs.

**Review by pchaigno — APPROVED** [review]

**Comment by joestringer** [comment]
> However we only run it on the latest changes, meaning the changes returned by git diff HEAD. This means that checkpatch.pl will not receive any input if the user (or CI system) has made no change since last commit, in particular there will be no check if a user commit their changes before building. And there is no check enforced on the pull requests.

I wonder if we could figure out a way to run these on commits in PRs as well. A bit trickier but the weakness of the current approach is it forces developers to perform these `make check`s before making their commits. If developers don't do this because their workflow doesn't involve such a step,  or because they hack up several intermediate commits before rebasing & cleaning up, then these checks would be missed entirely.

One potential way would be to define an env variable for the git object in the `git diff HEAD` command, with `HEAD` as the default. That way, I could export `BPF_CHECK_GITREF=upstream/master` and the checks would be run against the diff between my current tree and the remote branch `master` on the remote `upstream`. Maybe in CI we set this to `origin/master` and make sure the remote `origin` is in sync with the latest git branch so that this command is effective.

**Comment by qmonnet** [comment]
I had missed the `make check` in `Makefile.bpf`.
``` make
check:
	@$(ECHO_CHECK)/*.c
	$(QUIET) spatch --sp-file $(ROOT_DIR)/contrib/coccinelle/null.cocci --dir . --include-headers
	$(QUIET) sparse -Wsparse-all ${FLAGS} $(ROOT_DIR)/$(RELATIVE_DIR)/*.c
	$(QUIET) $(CLANG) ${CLANG_FLAGS} --analyze $(ROOT_DIR)/$(RELATIVE_DIR)/*.c
	$(QUIET) $(foreach SUBDIR,$(SUBDIRS), \
```
So we already have the “infra” to call sparse and cocci patches. I tried `make check` and it works well indeed. Sparse complains a lot, spatch does nearly nothing at the moment. We could either try to fix the sparse warnings, or count them and make sure we don't add new ones.

@joestringer because I had not seen the `make check` in bpf, I run checkpatch from `make precheck` in main Makefile. So developers might still miss it if they commit first, but it is called from the `all` target and should be run each time we call `make`. A majority of developers should compile their code before committing [citation needed].

But it's true, it would be nice to have checkpatch _and_ `make check` run for each PR. I've seen checkpatch called from “pre-receive” git hooks before, but I think only Enterprise GitHub have these. We could indeed check against a configurable variable that would default to `origin/master`, and find something that works for the CI. I can change my PR to run against the remote branch, at least locally.

Questions:

- Should we call `make check` from Makefile.bpf as a dependency to `make precheck` from main Makefile, or find a similar way to run the checks each time we build? Or do we prefer to run them explicitly?

- If we call it for each PR and especially in the CI, what do we consider as blocking? Is a checkpatch error a reason to fail the tests? What about a sparse warning? Etc. We would likely need a way to bypass checks for false positives. Also one consideration is that sparce / spatch / cppcheck all require additional software to be installed on the system. Not a problem for us, but this might make it harder for new/occasional contributors if we make those tests blocking for a merge.

**Comment by joestringer** [comment]
> . So developers might still miss it if they commit first, but it is called from the all target and should be run each time we call make. A majority of developers should compile their code before committing [citation needed]

I frequently make a series of commits, then find issues and write fixup patches to amend the earlier commits in the series. My workflow tends to involve something like:
```
<edit>
$ make -C daemon
$ make reload
<test/validate>
$ git commit --fixup $old_commit_sha
$ git rebase -i upstream/master
```

or
```
<edit>
$ make microk8s
$ kubectl -n kube-system delete po -l k8s-app=cilium
<test>
$ git commit ...
```

This kind of workflow necessitates a separate later step to `make` to actually run the various checks regardless of what's currently uncommited. Indeed I'll often fix these up and commit in the same manner. The `make` at the end is also something super easy to miss, which I would hope is picked up early by CI so that it doesn't waste a bunch of time validating the changes when I'll have to fix up some minor things and resubmit anyway. (This is largely the case already today with the `jenkins-precheck` target).

> Should we call make check from Makefile.bpf as a dependency to make precheck from main Makefile, or find a similar way to run the checks each time we build? Or do we prefer to run them explicitly?

I don't mind them being part of the main check as long as they're clean. I rarely run the checks under `bpf/` and part of that is because the (eg sparse) targets have so many complaints; I don't know where to start and I don't know that my changes are related.

> If we call it for each PR and especially in the CI, what do we consider as blocking? Is a checkpatch error a reason to fail the tests? What about a sparse warning? Etc. We would likely need a way to bypass checks for false positives. Also one consideration is that sparce / spatch / cppcheck all require additional software to be installed on the system. Not a problem for us, but this might make it harder for new/occasional contributors if we make those tests blocking for a merge.

All good points. My general stance is that if we don't make something blocking, then developers will ignore it. Exhibit A: `sparse` :-) That's why I tend to advocate all of the go vet, etc. stuff in the main make (check) target. These things do make setting up the dev env more complicated though. One way to mitigate this is to set up docker containers with all of the dev dependencies and using those containers to perform the build. Might be an option if we're worried about that. For docs we're already assuming docker (or another container runtime engine) is already available.

**Pull request closed without merging**
