### PR TITLE
vagrant: Bump all Vagrant box versions

### LINKED ISSUE #11255: "'stddef.h' file not found" in dev. VM
## Issue
Trying to run the unit tests from inside the dev. VM results in the following error:
```
In file included from unit-test.c:8:
/usr/include/stdlib.h:31:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
```
That error is happening because [we recently switched the compiler for the BPF unit tests to Clang](https://github.com/cilium/cilium/commit/1f0c4a995bf526fe82d5feb2347a61c40a467ac7). The dev. VM images (4.9 and net-next) don't include a full Clang, but only the strict minimum required to compile BPF programs.

## Workaround
The following steps, proposed by André for a similar issue on v1.7, work as a quick fix:
```
sudo mv /usr/bin/clang{,.bak}
sudo mv /usr/bin/llc{,.bak}
sudo apt-get install -y clang-7 llvm-7
sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-7/bin/clang 1000
sudo update-alternatives --install /usr/bin/llc llc /usr/lib/llvm-7/bin/llc 1000
```
To revert:
```
sudo mv /usr/bin/clang{.bak,}
sudo mv /usr/bin/llc{.bak,}
``` 

## Proper Fix
The proper fix requires to revert part of cilium/packer-ci-build#200, to be able to compile on x86 with Clang.

----
Reported-by: Nate Sweet <nathanjsweet@pm.me>

### PR DESCRIPTION
**Pull request by pchaigno**
Fixes: #11255

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
retest-net-next

**Comment by pchaigno** [comment]
retest-runtime

**Comment by pchaigno** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
I assume the failure fixed by the `maps: Use fmt.Sprint() instead of string()` commit only showed up now due to the Go version bump in the new Vagrant box?

**Comment by pchaigno** [comment]
> I assume the failure fixed by the `maps: Use fmt.Sprint() instead of string()` commit only showed up now due to the Go version bump in the new Vagrant box?

Yeah, that's my assumption since the VM image update includes a Go update, it didn't occur on previous VM images, and I was able to easily reproduce locally with the new VM image.

**Comment by pchaigno** [comment]
Net-next CI build hit known flake #13062. Other builds are passing. Marking as ready-to-merge.

**Pull request merged**
