### PR TITLE
v1.14 Backports 2024-06-12

### PR DESCRIPTION
**Pull request by giorio94**
* [x] #32866 (@YutaroHayakawa) :warning: resolved conflicts
    * ℹ️ Resolved trivial conflict in values.yaml.tmpl, and dropped the values.schema.json hunk, which is not relevant in v1.14.
 * [x] #33062 (@julianwiedmann)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 32866 33062
```

### CODE REVIEW

**Comment by giorio94** [comment]
/test-backport-1.14

**Review by julianwiedmann — APPROVED** [review]

**Review by YutaroHayakawa — APPROVED** [review]

**Comment by giorio94** [comment]
CI failures to be addressed rebasing on top of #33111

**Comment by giorio94** [comment]
Rebased to pick the fix introduced in https://github.com/cilium/cilium/pull/33111

**Comment by giorio94** [comment]
/test-backport-1.14

**Review by michi-covalent — APPROVED** [review]
`:rubber-stamp:`

**Pull request merged**
