### PR TITLE
Update containerd libraries

### PR DESCRIPTION
**Pull request by aanm**
Read per commit message

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6991)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
Seems fine from janitor perspective. It'd be nice if we didn't have to carry manual configuration of systemd services in our tree but I suppose there's not a lot we can do about it right now.

**Comment by aanm** [comment]
>Seems fine from janitor perspective. It'd be nice if we didn't have to carry manual configuration of systemd services in our tree but I suppose there's not a lot we can do about it right now.

@joestringer why?

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
@aanm needs rebase.

**Comment by aanm** [comment]
test-me-please

**Comment by joestringer** [comment]
> > Seems fine from janitor perspective. It'd be nice if we didn't have to carry manual configuration of systemd services in our tree but I suppose there's not a lot we can do about it right now.

> @joestringer why?

Traditionally distros provide a way to install and configure packages. `apt-get install foo` or distro equivalent. Presumably because the distro we're using here doesn't have a new enough version of containerd or doesn't package it, we're explicitly removing any existing versions of the package and writing our own custom package install stuff here. It's just more stuff we need to maintain. Even if it's copied from somewhere, when upstream changes something, we won't pick up the changes/fixes.

**Comment by aanm** [comment]
@joestringer ah! you mean the containerd.service? I copy it from the containerd repo because it's not shipped in the tar.gz and yeah AFAIK there are no packages for it in ubuntu.

**Pull request merged**
