### PR TITLE
Revert patch to exclusively use bugtool to collect failure results in bash tests on CI

### PR DESCRIPTION
**Pull request by joestringer**

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
@scanf I noticed that the bash-based jenkins CI builds such as the following no longer provide useful tarballs for debugging when they fail:

https://jenkins.cilium.io/job/Cilium-Bash-Tests/85/

It seems like the culprit is the following commit, so I reverted it in this PR and now it looks like archives are generated correctly:
https://github.com/cilium/cilium/commit/2d713e2227d5a31c8b3549564812193e7d6fcaa2

https://jenkins.cilium.io/job/Cilium-Bash-Tests/89/

Do you have any thoughts on the best way to fix this? We could just apply the revert in this PR, or come up with a better fix, or just ignore it since the bash tests will be deprecated soon in favour of ginkgo tests.

**Comment by ianvernon** [comment]
I'd prefer if we revert and come up with a fix as we don't know how long we will be maintaining the bash framework, and if we hit an odd failure case, we need to have logs.

**Comment by aalemayhu** [comment]
Revert is fine. Debugging it might take a while and I don't think I can trigger Jenkins builds on anymore via the phrase.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
This PR only touches `tests/`, issue https://github.com/cilium/cilium/issues/2562 is causing a red herring on the Ginkgo CI here.

**Comment by ianvernon** [comment]
I don't see a point in triggering the Ginkgo CI again since this is relegated only to the `tests/` directory as you said. Merging. Thanks for identifying and taking care of this!

**Pull request merged**
