### PR TITLE
eni: update limits list

### PR DESCRIPTION
**Pull request by bpineau**
Re-sync the AWS ENI limits list with
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html?shortFooter=true#AvailableIpPerENI

For those not using `--update-ec2-apdater-limit-via-api` CLI option.

```release-note
Update ENI limits list
```

### CODE REVIEW

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Review by ungureanuvladvictor — APPROVED** [review]

**Comment by christarazi** [comment]
retest-runtime

**Comment by christarazi** [comment]
retest-4.9

**Comment by bpineau** [comment]
Thanks for the reviews.
Would it be possible to cherry-pick this to the upcoming 1.8?

**Comment by christarazi** [comment]
retest-runtime

**Comment by christarazi** [comment]
retest-runtime

> Thanks for the reviews.
> Would it be possible to cherry-pick this to the upcoming 1.8?

If you mean that you'd like this in 1.8, we can backport.

**Review by aanm — APPROVED** [review]

**Pull request merged**
