### PR TITLE
v1.13 Backports 2023-08-28

### PR DESCRIPTION
**Pull request by pippolo84**
* [ ] #27597 (@sayboras)
   * :warning: merge conflicts due to different signature for function `policy.NewPolicyRepository` in v1.13
 * [ ] #27644 (@brb)
 * [x] #27391 (@brlbil)
   * :warning: merge conflicts due to missing workflow files in v1.13 branch:
     - .github/workflows/build-images-docs-builder.yaml
     - .github/workflows/ci-images-cache-cleaner.yaml
     - .github/workflows/ci-images-garbage-collect.yaml
     - .github/workflows/close-stale-issues.yaml
     - .github/workflows/conformance-ginkgo.yaml
     - .github/workflows/conformance-ipsec-e2e.yaml
     - .github/workflows/conformance-k8s-kind-network-policies.yaml
     - .github/workflows/conformance-k8s-kind.yaml
     - .github/workflows/conformance-k8s-network-policies.yaml
     - .github/workflows/conformance-kind-proxy-daemonset.yaml
     - .github/workflows/conformance-multi-pool.yaml
     - .github/workflows/conformance-runtime.yaml
     - .github/workflows/container-scan.yaml
     - .github/workflows/integration-test.yaml
     - .github/workflows/lint-codeowners.yaml
     - .github/workflows/lint-workflows.yaml
     - .github/workflows/push-chart-ci.yaml
     - .github/workflows/tests-datapath-verifier.yaml

PRs skipped due to conflicts:

 * #27646 (@giorio94)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 27597 27644 27391; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=27597,27644,27391
```

### CODE REVIEW

**Comment by giorio94** [comment]
> PRs skipped due to conflicts:
> 
> https://github.com/cilium/cilium/pull/27646 (@giorio94)

I mistakenly assumed that the Chart CI Push existed in v1.13, but it appears to not be present. I've dropped the associated needs-backport label from https://github.com/cilium/cilium/pull/27646. Sorry for the noise.

**Comment by pippolo84** [comment]
> > PRs skipped due to conflicts:
> > #27646 (@giorio94)
> 
> I mistakenly assumed that the Chart CI Push existed in v1.13, but it appears to not be present. I've dropped the associated needs-backport label from #27646. Sorry for the noise.

No problem at all, thanks!

**Review by brlbil — APPROVED** [review]
I have made small changes to my commit.

Since some of the workflow names changed, Required Workflows need to be adjusted after this is merged.

The list of changes is below.
```
-name: ConformanceAKS (ci-aks)
+name: Conformance AKS (ci-aks)
--
-name: ClusterMesh (ci-multicluster)
+name: Conformance Cluster Mesh (ci-clustermesh)
--
-name: Cilium Conformance E2E (ci-e2e)
+name: Conformance E2E (ci-e2e)
--
-name: ConformanceEKS (ci-eks)
+name: Conformance EKS (ci-eks)
--
-name: External workloads (ci-external-workloads)
+name: Conformance External Workloads (ci-external-workloads)
--
-name: ConformanceGatewayAPI
+name: Conformance Gateway API
--
-name: ConformanceGKE (ci-gke)
+name: Conformance GKE (ci-gke)
--
-name: ConformanceIngress
+name: Conformance Ingress
--
-name: ConformanceKind
+name: Conformance Kind
--
-name: BPF checks
+name: BPF Checks
--
-name: build-commits
+name: Build Commits
--
-name: codeql
+name: CodeQL
--
-name: Go-related checks
+name: Go Related Checks
--
-name: Smoke test
+name: Smoke Test
```

Also, Branch protection rules need to be adjusted.
To Remove
```
build datapath
coccicheck
conformance-test
conformance-test-ipv6
generate-api
generate-k8s-api
go-mod
helm-charts
installation-and-connectivity
```

To Add
```
BPF Checks / Build Datapath
BPF Checks / Run coccicheck
Smoke Test / Installation and Conformance Test
Smoke Test with IPv6 / Installation and Conformance Test
Go Related Checks / Generate API
Go Related Checks / Generate k8s API
Go Related Checks / Check Go Modules
Smoke Test / Helm Charts Check
Conformance Kind / Installation and Connectivity Test
```

**Comment by pippolo84** [comment]
Rebased to fix conflicts with target branch.

**Comment by pippolo84** [comment]
/test-backport-1.13

**Comment by pippolo84** [comment]
Pinging @brb and @sayboras for the missing reviews :pray:

**Review by brb — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
