### PR TITLE
all: preallocate slices with known size

### PR DESCRIPTION
**Pull request by tklauser**
This avoids reallocations in loops, cf. #10056

Found using github.com/alexkohler/prealloc

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by aanm — APPROVED** [review]
Can we add this as a checker?

**Comment by tklauser** [comment]
> Can we add this as a checker?

Will look into it, yes. But there are some cases in which preallocation doesn't make sense, i.e. the slice is rather small and/or the capacity cannot be estimated reliably. Thus the `prealloc` results need manual inspection, e.g. I left out these:

```
pkg/datapath/linux/node_addressing.go:39 Consider preallocating addresses
pkg/endpoint/bpf.go:258 Consider preallocating updatedStats
pkg/envoy/server.go:1031 Consider preallocating policies
```

Not sure how to tell the checker to ignore these cases.

**Comment by aanm** [comment]
> > Can we add this as a checker?
> 
> Will look into it, yes. But there are some cases in which preallocation doesn't make sense, i.e. the slice is rather small and/or the capacity cannot be estimated reliably. Thus the `prealloc` results need manual inspection, e.g. I left out these:
> 
> ```
> pkg/datapath/linux/node_addressing.go:39 Consider preallocating addresses
> pkg/endpoint/bpf.go:258 Consider preallocating updatedStats
> pkg/envoy/server.go:1031 Consider preallocating policies
> ```
> 
> Not sure how to tell the checker to ignore these cases.

I guess there isn't a tag to ignore false positives.

**Comment by tklauser** [comment]
> I guess there isn't a tag to ignore false positives.

Doesn't look like it :disappointed:

**Comment by tklauser** [comment]
Found some other cases using the `-forloops` flag, please have another look.

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Pull request merged**
