### PR TITLE
Add BPF verification checker test to ginkgo suite

### PR DESCRIPTION
**Pull request by joestringer**
Add the verifier test script to the regular ginkgo testsuite. If a datapath change is likely to cause verifier complexity issues, then this specific test should catch it.

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by eloycoto — COMMENTED** [review]
I'm not sure why you changed the ReportFailed function. It's only one change in one test, and you changed the helper, I don't think that it's necessary at all. 

What about the following: 

```
	AfterFailed(func() {
		commands := []string{"clang -a"}
		for _,cmd := range comamnds{
			GinkgoPrint(vm.Exec(cmd).GetDebugMessage())
		}
	})
```

I think that the helper will be simpler, and the specific use case should be covered no?

What do you think?

**Comment by joestringer** [comment]
@eloycoto because the default fail report helper expects Cilium to be running. This test explicitly requires Cilium to be *not* running. If the default one runs, it will screw up on any Cilium command gathering.

**Comment by eloycoto** [comment]
Joe, that is what I said, instead of having all of this in cilium helper, you can use a custom report writted into `AfterFailed` function, so no change in the helper at all.

**Comment by joestringer** [comment]
@eloycoto ah, so that skips the default helper? I didn't realise this. Let me dig around a bit.

**Comment by joestringer** [comment]
@eloycoto to be consistent with other test failure output, here's what the `AfterFailed()` would end up looking like (git diff):

```
$ git diff
diff --git a/test/runtime/verifier.go b/test/runtime/verifier.go
index 336166411440..53f193ec81b9 100644
--- a/test/runtime/verifier.go
+++ b/test/runtime/verifier.go
@@ -17,6 +17,7 @@ package RuntimeTest
 import (
        "fmt"
 
+       "github.com/cilium/cilium/test/config"
        . "github.com/cilium/cilium/test/ginkgo-ext"
        "github.com/cilium/cilium/test/helpers"
 
@@ -46,7 +47,16 @@ var _ = Describe(verifierTest, func() {
        })
 
        AfterFailed(func() {
-               vm.ReportFailedWithoutCilium("clang --version", "uname -a")
+               if config.CiliumTestConfig.HoldEnvironment {
+                       GinkgoPrint("Skipped gathering logs (-cilium.holdEnvironment=true)\n")
+                       return
+               }
+               GinkgoPrint("===================== TEST FAILED =====================")
+               commands := []string{"clang --version", "uname -a"}
+               for _,cmd := range commands{
+                       GinkgoPrint(vm.Exec(cmd).GetDebugMessage())
+               }
+               GinkgoPrint("===================== EXITING REPORT GENERATION =====================")
        })
 
        AfterAll(func() {
```

Are you happy with this? Otherwise I think that my current approach is fine.

**Review by ianvernon — APPROVED** [review]

**Review by jrfastab — APPROVED** [review]
LGTM

**Comment by eloycoto** [comment]
@joestringer as soon you apply that change I think that it'll be simpler. Thanks

**Comment by joestringer** [comment]
@eloycoto the helper will be simpler in favour of the test boilerplate being more complicated, but there's just one user right now so it doesn't need to be a helper. I'll fix this up.

**Comment by joestringer** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]
Test side LGTM

**Pull request merged**
