### PR TITLE
feat(helm): Move requirements.yaml to Chart.yaml

### LINKED ISSUE #10478: Move helm's old requirements.yaml into Chart.yaml
This is new with Helm 3, we should update our charts.

### PR DESCRIPTION
**Pull request by sayboras**
To move requirements.yaml to Chart.yaml as a recommended way in helm 3.
    
Bump chart apiVersion to v2, and clean old attributes e.g. gotpl and
tillerVersion.
    
BREAKING CHANGE: This is breaking change as helm 3 must be used.

I have scanned the code base (docs, ci, etc), seems like helm 3 is recommended.
If it's the case, this PR is not really breaking change.
    
Closes #10478
    
Signed-off-by: Tam Mach <sayboras@yahoo.com>

```release-note
Removed helm 2 support. Move requirements.yaml to Chart.yaml and set min. helm version to helm 3
```

### CODE REVIEW

**Review by aanm — APPROVED** [review]
Since we recommend `helm3` in all of our docs this makes sense to me.

**Comment by aanm** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]
It looks good to me; I think it'd be good to have at least one member from @cilium/helm to OK this.

**Review by nebril — APPROVED** [review]
Thanks!

**Comment by seanmwinn** [comment]
We do presently state that Helm 2 can be supported in the install guides. This change would require modifying those guides to exclude Helm 2 support.

Here's one example: https://docs.cilium.io/en/v1.8/gettingstarted/k8s-install-etcd-operator/#deploy-cilium-cilium-etcd-operator

**Pull request merged**
