### PR TITLE
backport/v1.4 2019 02 24

### PR DESCRIPTION
**Pull request by jrfastab**
PR #7191 
PR #7189  
PR #7186 
PR #7184 
PR #7167 
PR #7155

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7202)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by ianvernon** [comment]
Looks like the alignchecker backport broke the ability to compile v1.4:

```
17:34:21     runtime: probe
17:34:21     runtime: ' is not a recognized processor for this target
17:34:21     runtime:  (ignoring processor)
17:34:21     runtime: error
17:34:21     runtime: : 
17:34:21     runtime: couldn't allocate input reg for constraint '
17:34:21     runtime: r
17:34:21     runtime: '
17:34:21     runtime:  at line 
17:34:21     runtime: 2148004599
17:34:21     runtime: Makefile:19: recipe for target 'bpf_alignchecker.o' failed
17:34:21     runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/bpf'
17:34:21     runtime: Makefile:42: recipe for target 'bpf' failed
17:34:21     runtime: make[1]: *** [bpf_alignchecker.o] Error 1
17:34:21     runtime: make: *** [bpf] Error 2
17:34:21 The SSH command responded with a non-zero e
```

**Comment by ianvernon** [comment]
I think #7162 should be removed from this PR as it isn't a user-facing bug / a security issue.

**Comment by joestringer** [comment]
While we need to ensure that structures are aligned on older versions, we would hopefully pick up on any such breakage first when a patch is written against master, so I'm inclined to agree with @ianvernon .

IIRC someone was saying that this alignchecker doesn't work on clang 3.8.1, which we would be using with all older trees.

**Comment by jrfastab** [comment]
@brb If we drop the alignment checker series will we have any problems backporting patches going forward. Something like patch A works upstream but needs an additional patch A' to get it working on 1.4.x? Just want to check.

**Review by vadorovsky — APPROVED** [review]
I agree with @jrfastab and I think that align checker should be backported. Otherwise, Cilium 1.4 will be locked to a specific **patch** version of Go (concretely 1.11.3). Imagine situation when some future Go version 1.11.x fixes bugs or security vulnerabilities and we will be unable to use it, because we are locked to 1.11.3.

**Comment by vadorovsky** [comment]
And I would rather adjust the new align checker to work with Cilium 1.4 and clang 3.8, if possible.

**Comment by vadorovsky** [comment]
I guess that the only thing which is needed to fix this PR is backporting #7210 here when it's merged.

**Comment by jrfastab** [comment]
@mrostecki OK so what I'm doing here is popping the alignment check series and when we have a complete working series it can be backported (if we decide to) with the fix.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
