### PR TITLE
daemon: Define CILIUM_ACCESS-LOG and CILIUM_ACCESS-LABELS env vars

### PR DESCRIPTION
**Pull request by rlenglet**
Fixes: https://github.com/cilium/cilium/issues/3751
Fixes: 5b03fb8635551b1ae3c3012beecebe0e16e606b1
Signed-off-by: Romain Lenglet <romain@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/3753)

### CODE REVIEW

**Comment by rlenglet** [comment]
test-me-please

**Review by manalibhutiyani — APPROVED** [review]

**Comment by manalibhutiyani** [comment]
@rlenglet I think this will need back porting. Adding the necessary label.

**Comment by manalibhutiyani** [comment]
You should also add a `Fixes : 5b03fb8635551b1ae3c3012beecebe0e16e606b1` in the commit summary to make the back porting easy  and also backport related commit `5b03fb8635551b1ae3c3012beecebe0e16e606b1` if not done already.

**Review by aanm — DISMISSED** [review]
This should still work, did you try `CILIUM_ACCESS-LOG`?

**Comment by rlenglet** [comment]
@manalibhutiyani no it doesn't need backporting because the commit that broke this wasn't backported.

**Review by ianvernon — APPROVED** [review]

**Comment by manalibhutiyani** [comment]
Sure. I guess the real question is do you think the other commit and this one needs to be back ported. If not then we are good

**Comment by rlenglet** [comment]
@aanm Good point about `-` vs `_`. I'll fix the names of environment variables.

But unfortunately the special logic in viper to lookup the environment variables is only called from `viper.Get`, and it doesn't set flag variables automatically from env variables. So if we replace `viper.Get*` calls with flag variables like I did, the env variable is ignored unless we explicitly call `viper.BindEnv`.

**Comment by rlenglet** [comment]
I think calling `viper.BindEnv` is better anyway, since it documents explicitly which env variables are supported.

**Comment by rlenglet** [comment]
@manalibhutiyani neither commit needs backporting. Thanks!

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by aanm** [comment]
@rlenglet We have [0] which should pick all of the flags, doesn't that work?

[0]
```
	viper.AutomaticEnv()           // read in environment variables that match
```

**Comment by rlenglet** [comment]
@aanm The problem is that this works only when we call `viper.Get*` directly to get the values. Calling `viper.AutomaticEnv()` doesn't set the variables of declared flags. Makes me doubt the usefulness of `viper.AutomaticEnv()` altogether.

**Comment by aanm** [comment]
@rlenglet yep, you are right, accordingly with the docs:

>AutomaticEnv is a powerful helper especially when combined with SetEnvPrefix. When called, Viper will check for an environment variable any time a **viper.Get** request is made. It will apply the following rules. It will check for a environment variable with a name matching the key uppercased and prefixed with the EnvPrefix if set.

**Comment by tgraf** [comment]
@rlenglet The requirement of the Fixes tag is unrelated to our current decision to backport or not. If the faulty commit ever gets subject to be backported it needs to be clear what dependencies it has. Please add a fixes tag to the commit message.

**Comment by rlenglet** [comment]
Green build: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/2438/

**Comment by rlenglet** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
Sorry, didn't see that the CI is still ongoing, removing read-to-merge label again

**Comment by rlenglet** [comment]
I just wanted to have a 2nd green build...

**Comment by jrajahalme** [comment]
@rlenglet Are you sure using '-' in env variable names is a good idea? Typically it is avoided, IMO.

**Comment by rlenglet** [comment]
@jrajahalme That's how viper matches flag names to env variable names. Apparently we've been relying on those names, so we can't change them anymore.

**Comment by aanm** [comment]
>Sorry, didn't see that the CI is still ongoing, removing read-to-merge label again

@tgraf I thought we could add the `ready-to-merge` label regardless of the PR state and the Janitor's would only merge ready-to-merge PRs with all tests all green

**Comment by jrajahalme** [comment]
> On Apr 16, 2018, at 2:10 PM, Romain Lenglet <notifications@github.com> wrote:
> 
> @jrajahalme <https://github.com/jrajahalme> That's how viper matches flag names to env variable names. Apparently we've been relying on those names, so we can't change them anymore.
> 
> 
IMO it would be better to double-check the need to keep using those names. Viper examples do not use underscores and the docs refer to the ability to set up a formatter/filter to translate underscores to dashes. If we absolutely must keep them, we should deprecate them now and somehow support both spellings and hopefully get rid of the env variables with dashes in some future.

The problem with dashes is that I have not yet been able to figure out how to set an environment variable with a dash in it’s name. Indeed, according to https://unix.stackexchange.com/questions/23659/can-shell-variable-include-character/23714#23714 <https://unix.stackexchange.com/questions/23659/can-shell-variable-include-character/23714#23714> it is not even possible. So I wonder how can we be depending on those old names?

  Jarno

**Comment by tgraf** [comment]
> The problem with dashes is that I have not yet been able to figure out how to set an environment variable with a dash in it’s name. Indeed, according to https://unix.stackexchange.com/questions/23659/can-shell-variable-include-character/23714#23714 <https://unix.stackexchange.com/questions/23659/can-shell-variable-include-character/23714#23714> it is not even possible. So I wonder how can we be depending on those old names?

Wow, so viper is literally broken for the majority of flags using AutomaticEnv(). I agree with Jarno. No point in guaranteeing this compatibility.

**Comment by rlenglet** [comment]
2nd green build: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/2448/
Will remove the call to `viper.AutomaticEnv()`.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
3rd green build: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/2458/

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
