### PR TITLE
v1.7 backports 2020-07-30

### PR DESCRIPTION
**Pull request by christarazi**
* #12719 -- Parallelise CRD registration to improve bootstrap time (@tgraf)
   * Note: conflict resolution:
       * First commit: vendored in `errgroup`
        * Second commit: kept the `k8sCachesSynced` channel which was moved to another location in the latest tree.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12719; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
retest-ginkgo

**Comment by christarazi** [comment]
test-backport-1.7

**Review by gandro — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Pull request merged**
