### PR TITLE
npds: Don't wait for ACKs from sidecar proxy when no HTTP filter should be configured

### PR DESCRIPTION
**Pull request by rlenglet**
Signed-off-by: Romain Lenglet <romain@covalent.io>

### CODE REVIEW

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
This PR fixes an issue we've seen recently with Istio with sidecar proxies, where we try to push a NetworkPolicy to the sidecar proxy for the endpoint and wait for an ACK, before the network policy has been even calculated and Envoy has had the ability to connect to Pilot to get configured.

**Comment by rlenglet** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by jrajahalme** [comment]
Backport #3856

**Pull request merged**
