### PR TITLE
bpf: Retry opening map after initial error

### PR DESCRIPTION
**Pull request by tgraf**
Current code used sync.Once and only attempted opening the map once using
sync.Once. Subsequent tried to open the map would always fail without
ever retrying, i.e. the initial failure always became a permanent failure.

Fixes: #2965 
Fixed: #2924

Reported-by: @mrdima
Signed-off-by: Thomas Graf <thomas@cilium.io>

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by dimitri** [comment]
I'm not the reporter here, maybe you mean another GitHub account that happens to share my first name?

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
> I'm not the reporter here, maybe you mean another GitHub account that happens to share my first name?

@dimitri My mistake, I was referring to a slack user name. Fixed. Will also fix the commit. Sorry about the noise for you.

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
