### PR TITLE
[v1.11] Author Backport of WG node handler and dependent PR

### PR DESCRIPTION
**Pull request by bimmlerd**
* [x] #25450 (@bimmlerd)
 * [x] #25419 (@bimmlerd)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 25450 25419; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
make add-labels BRANCH=v1.11 ISSUES=25450,25419
```

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Nice work, thanks again for the backporter notes, that was helpful in understanding the interface change!

**Comment by bimmlerd** [comment]
/test-backport-1.11

**Review by michi-covalent — APPROVED** [review]

**Comment by gandro** [comment]
- https://github.com/cilium/cilium/actions/runs/5188573844/jobs/9352416199 seems to have hit a potential new infrastructure flake `failed to fetch cilium runtime config: error dialing backend: remote error: tls: internal error`. #26112 

Both [smoke test](https://github.com/cilium/cilium/actions/runs/5188379289/jobs/9351956464?pr=25935) and [ConformanceKind1.19 ](https://github.com/cilium/cilium/actions/runs/5188379281/jobs/9351946495?pr=25935) failed with a very similar error. This looks potentially related, looking into it.

**Comment by bimmlerd** [comment]
Marking as release blocker, as this is a regression (see https://github.com/cilium/cilium/pull/25419#issuecomment-1568056801)

**Comment by gandro** [comment]
Checked the ConformanceKind workflow. Endpoint regeneration is indeed failing with `2023-06-12T12:14:43.202117738Z level=warning msg="BPF program is too large. Processed 1000001 insn" subsys=datapath-loader`, which indicates that this is due to https://github.com/cilium/cilium/pull/25993

I don't think it makes sense to block this PR on the other PR, since the changes are unrelated and this code here does not change any BPF code at all.

**Comment by gandro** [comment]
/ci-eks-1.11

**Comment by gandro** [comment]
/ci-multicluster-1.11

**Comment by aspsk** [comment]
The conformance-kind and SmokeTest CI failures could be "resolved" by rebasing on top of the current v1.11

**Comment by aspsk** [comment]
> * [CI multicluster](https://github.com/cilium/cilium/actions/runs/5245026884/jobs/9471887734) failed due to google.com rejecting our CI request

@gandro note that ci-multicluster may also fail due to complexity issue (fix in progress in https://github.com/cilium/cilium/pull/25993)

**Comment by gandro** [comment]
- https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-5.4/34/testReport/junit/Suite-k8s-1/21/K8sDatapathConfig_Host_firewall_With_native_routing/ hit a variant of https://github.com/cilium/cilium/issues/24697
- One of the ci-multicluster jobs indeed failed due to the complexity issue as expected (c.f. sysdump). The others are green: https://github.com/cilium/cilium/actions/runs/5245026910/jobs/9471893688

**Comment by gandro** [comment]
/test-1.21-5.4

**Pull request merged**
