### PR TITLE
k8s: Update grafana dashboard with latest metrics

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7226)

### CODE REVIEW

**Comment by brb** [comment]
Reading the diff of the Grafana dashboard is not feasible due to its size. Maybe we should use https://github.com/weaveworks/grafanalib to generate the dashboard?

**Comment by ianvernon** [comment]
Agreed with @brb  , it's hard to review such large diffs. Is there anything in particular to look at / note in this PR which would make it easier to review?

**Comment by tgraf** [comment]
Not opposed to grafanalib but it's another steep learning curve for all engineers. Who would be able to review that diff right now? It's auto-generated JSON, the review should really happen in the rendered dashboard with actual data. So maybe screenshots?

**Comment by brb** [comment]
> So maybe screenshots?

Yes, it would work.

**Comment by eloycoto** [comment]
> Reading the diff of the Grafana dashboard is not feasible due to its size. Maybe we should use https://github.com/weaveworks/grafanalib to generate the dashboard?

Grafana also uses jsonnet to create the dashboards, we can use that also.

**Pull request merged**
