### PR TITLE
docs: add Veepee as cilium USERS

### PR DESCRIPTION
**Pull request by nerzhul**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

### CODE REVIEW

**Review by xmulligan — APPROVED** [review]

**Comment by xmulligan** [comment]
Thank for the addition! Would you be interested in doing a case study about your use of Cilium? We would just need 30 minutes to interview you. Some past examples can be found [here](https://www.cncf.io/case-studies/?_sft_lf-project=cilium)

**Comment by nerzhul** [comment]
thanks for the proposal but we are a tiny player for now on cilium, maybe next year :D , we are migrating to it this year

**Comment by xmulligan** [comment]
Fair enough, maybe later then. Come and say hi to us at KubeCon if you are coming though!

**Comment by nerzhul** [comment]
@xmulligan without doubt :) 
i rebased branch

**Review by aanm — APPROVED** [review]

**Pull request merged**
