### PR TITLE
gh: workflows: clarify reference to issue #23283

### PR DESCRIPTION
**Pull request by julianwiedmann**
Clarify that while the issue was closed as resolved, this actually only
applies to scenarios where the kind.sh script is used.

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@julianwiedmann FYI that since this is being opened from a fork I'm not sure if this is being tested with your changes or not.

**Comment by gandro** [comment]
> Issue #23283 has been resolved, clean up the workarounds.

Could you like to the PR which has resolved this? Because last time I checked, the underlying issue wasn't actually fixed in Cilium, it was only "resolved" by adjusting the `kind.sh` script. But the workflows here use `helm/kind-action`, not `kind.sh`, thus they failed (that's at least why the multi-pool workflow has the mention, we discovered it "the hard way").

See also my comment here: https://github.com/cilium/cilium/issues/23283#issuecomment-1597282247

**Review by gandro — CHANGES_REQUESTED** [review]
(as per comment above)

**Comment by julianwiedmann** [comment]
> > Issue #23283 has been resolved, clean up the workarounds.
> 
> Could you like to the PR which has resolved this? Because last time I checked, the underlying issue wasn't actually fixed in Cilium, it was only "resolved" by adjusting the `kind.sh` script. But the workflows here use `helm/kind-action`, not `kind.sh`, thus they failed (that's at least why the multi-pool workflow has the mention, we discovered it "the hard way").
> 
> See also my comment here: [#23283 (comment)](https://github.com/cilium/cilium/issues/23283#issuecomment-1597282247)

Thanks! Marco pointed out the same to me earlier, we came to the conclusion that it's probably best to point right at your :amaze: comment and not the high-level issue. Updated the PR.

**Review by christarazi — APPROVED** [review]

**Review by gandro — APPROVED** [review]
Thanks!

**Review by YutaroHayakawa — APPROVED** [review]

**Pull request merged**
