### PR TITLE
statedb:  Reconciler utility

### PR DESCRIPTION
**Pull request by joamaki**
This adds the statedb reconciler, a utility for reconciling a StateDB table with a target system defined by the operations Update/Delete/Prune.

The reconciler performs incremental reconciliation as objects change as well periodic full reconciliation to catch cases where the target may have diverged. Metrics are gathered for errors and the durations of the operations. Module health is reported and marked degraded if operations fail.

### CODE REVIEW

**Review by tommyp1ckles — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]
I can't find anything wrong with this, very nice. Getting a little fancy in places, but nothing that can't pass in my opinion.

**Pull request merged**
