### PR TITLE
[ignore] testing

### PR DESCRIPTION
**Pull request by raybejjani**
wip

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8181)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-docs-please

**Comment by raybejjani** [comment]
test-docs-please

**Comment by raybejjani** [comment]
test-nightly

**Comment by raybejjani** [comment]
test-docs-please

**Comment by joestringer** [comment]
@raybejjani are we seeing complexity issues in BPF compilation somewhere? I was was worried it might introduce something like that, but we really should figure out which combination of defines causes this and use that combination by default in the CI test for BPF datapath complexity so that we can pick up on such issues before they land in the tree (or in someone's cluster!).

**Comment by raybejjani** [comment]
@joestringer I haven't seen any errors from BPF compilation. In the case of this PR it was because docker needed to be explicitly brought up. It previously didn't need this, apparently. All our tests were failing if they ran on newly provisioned machines.

**Pull request closed without merging**
