### PR TITLE
Add `dep check` to travis build

### PR DESCRIPTION
**Pull request by nebril**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7700)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by raybejjani** [comment]
womp womp :/ no dep in the travis environment, it seems.

**Review by raybejjani — CHANGES_REQUESTED** [review]
Could you provide a trivial amount of context in the commit message? I'm guessing `dep check` verifies that the dependencies are consistent in some way (but how could they not be?)
Separately, could this just be a make target that can also be run as part of local dev vm tests?

**Comment by nebril** [comment]
@raybejjani this change is just to make sure that Gopkg files are not committed to repo malformed. Added this info to commit message.

I wonder if dep install script will work on travis.

**Review by ianvernon — APPROVED** [review]

**Review by vadorovsky — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Comment by jrfastab** [comment]
Files being patched don't exist in 1.3 dropping needs backport 1.3 tag.

**Pull request merged**
