### PR TITLE
1.2 backports 14-12.18

### PR DESCRIPTION
**Pull request by nebril**
#6435 
#6427 

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6455)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-docs-please

**Review by raybejjani — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Pull request merged**
