### PR TITLE
Fix minikube gsg with CNI flag

### PR DESCRIPTION
**Pull request by aanm**
**Summary of changes**:

Fix minikube gsg with CNI flag

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4201)

### CODE REVIEW

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-docs-please

**Review by ackerman80 — APPROVED** [review]
Changes look good.

**Comment by techcet** [comment]
Works with minikube 0.22.3 (defaults to k8s v1.7.5).

**Comment by techcet** [comment]
Some of the kubectl tiefighter output has an extra space in front of the name "tiefighter".

Also, please fix the indentation in front of point#2 in the "minikube_intro.rst".

**Comment by aanm** [comment]
test-docs-please

**Review by techcet — APPROVED** [review]
Looks great!

**Pull request merged**
