### PR TITLE
v1.11: Update Go to 1.17.12

### PR DESCRIPTION
**Pull request by tklauser**
This includes various security fixes, see
https://go.dev/doc/devel/release#go1.17.12 for details.

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Review by ldelossa — APPROVED** [review]

**Comment by joestringer** [comment]
/test-backport-1.11

**Comment by aanm** [comment]
/test-1.17-4.9

**Comment by aanm** [comment]
/test-1.23-4.9

**Comment by joestringer** [comment]
AKS failed during workflow cleanup: https://github.com/cilium/cilium/runs/7358900183?check_suite_focus=true
GKE looks like it failed due to a Hubble relay timeout: https://github.com/cilium/cilium/runs/7350813942?check_suite_focus=true
GKE-stable hit #17628, https://github.com/cilium/cilium/issues/20542.

**Pull request merged**
