### PR TITLE
v1.13 Backports 2023-03-15

### PR DESCRIPTION
**Pull request by nebril**
* [ ] #24085 (@tommyp1ckles)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 24085; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=24085
```

### CODE REVIEW

**Comment by nebril** [comment]
/test-backport-1.13

**Review by jrajahalme — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Comment by nebril** [comment]
Looks like we hit https://github.com/cilium/cilium/issues/24379 on almost all jenkins jobs :thinking:

**Comment by nebril** [comment]
That's ok, the branch doesn't include https://github.com/cilium/cilium/pull/24336 (it was backported to 1.13 in parallel), which fixes this behaviour. We should be good to merge.

**Comment by nebril** [comment]
`k8s-1.17-kernel-4.9` had additional etcd timeout, not relevant to PR

**Pull request merged**
