### PR TITLE
v1.11 backports 2022-05-02

### PR DESCRIPTION
**Pull request by aditighag**
* #19570 -- pkg/policy/api: Optimize FQDNSelector String() (@christarazi)
 * #19593 -- docs: Update max MTU value for Nodeport XDP on AWS (@qmonnet)
 * #19610 -- docs: set the right url for API version check (@aanm)
 * #19423 -- pkg/labels: Optimize SortedList() and FormatForKVStore() (@christarazi)
 * #19587 -- datapath: Allow egress GW with XDP (@brb)
 * #19638 -- docs: set right path for robots.txt (@aanm)
 * #19383 -- daemon, fqdn: Add flag to control FQDN regex LRU size (@christarazi) --
                      **Resolved conflicts (please check)**
 * #19649 -- operator: fix identity GC collection (@aanm)
 * #19188 -- logging: do not swallow subsystem logs (@ldelossa) --
                     **Resolved conflicts (please check)**

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 19570 19593 19610 19423 19587 19638 19383 19649 19188; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Comment by aditighag** [comment]
/test-backport-1.11

**Comment by aditighag** [comment]
gke, external-workloads and multicluster failed with the same error - 

```
WARNING: Could not open the configuration file: [/home/runner/.config/gcloud/configurations/config_default].
ERROR: (gcloud.container.clusters.delete) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
```

**Review by aanm — APPROVED** [review]
My commits are looking good, thanks!

**Review by brb — APPROVED** [review]
My changes LGTM, thanks.

**Review by qmonnet — APPROVED** [review]
> https://github.com/cilium/cilium/pull/19593 -- docs: Update max MTU value for Nodeport XDP on AWS (@qmonnet)

is good, thank you!

**Comment by aditighag** [comment]
/ci-external-workloads-v1.11

**Comment by aditighag** [comment]
/ci-multicluster-1.11

**Comment by aditighag** [comment]
/test-1.23-4.9

**Comment by aditighag** [comment]
/test-1.21-5.4

**Comment by aditighag** [comment]
/ci-external-workloads-v1.11

**Review by christarazi — APPROVED** [review]
:+1:

**Comment by aditighag** [comment]
All tests have passed, except the runtime. Missed an import (change in the latest push) /cc @christarazi  - 

```
$ git diff 
diff --git a/pkg/fqdn/dnsproxy/proxy_test.go b/pkg/fqdn/dnsproxy/proxy_test.go
index 1aecc02d2b..866f1d3fe0 100644
--- a/pkg/fqdn/dnsproxy/proxy_test.go
+++ b/pkg/fqdn/dnsproxy/proxy_test.go
@@ -42,6 +42,7 @@ import (
        "github.com/golang/groupcache/lru"
        "github.com/miekg/dns"
        . "gopkg.in/check.v1"
+       "sigs.k8s.io/yaml"
 )
 
 // Hook up gocheck into the "go test" runner.
```

https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/2109/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/


Screen Shot 2022-05-03 at 2 20 40 PM


Runtime test has passed with the small change.

**Pull request merged**
