### PR TITLE
egressgw: tidy up Config handling

### PR DESCRIPTION
**Pull request by lmb**
egressgw: move Config sanity checks into the manager

    Move all the scattered config validation into the egress gateway manager. 
    This serves as self documentation and makes it less likely that the warnings
    will get out of date.

    Signed-off-by: Lorenz Bauer <lmb@isovalent.com>

egressgw: gate common checks using method on Config

    Call a method on Config instead of gating common checks required for egress
    gateway on EnableIPv4EgressGateway. This allows introducing additional
    implementations without changing code everywhere.

    Signed-off-by: Lorenz Bauer <lmb@isovalent.com>

### CODE REVIEW

**Comment by lmb** [comment]
ci-ipsec-e2e is a flake https://github.com/cilium/cilium/issues/26591

**Review by rgo3 — APPROVED** [review]

**Review by jschwinger233 — APPROVED** [review]

**Review by jibi — APPROVED** [review]
:ok_hand: :ok_hand:

**Pull request merged**
