### PR TITLE
Update CLOMonitor badge url

### PR DESCRIPTION
**Pull request by cynthia-sg**
Signed-off-by: Cintia Sanchez Garcia <cynthiasg@icloud.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

This PR updates the CLOMonitor’s badge url, which has changed recently

```release-note
Update CLOMonitor badge url 
```

### CODE REVIEW

**Comment by xmulligan** [comment]
Thanks for noticing @cynthia-sg.

I think the link you are looking for is actually [CLOMonitor](https://clomonitor.io/projects/cncf/cilium) from https://clomonitor.io/projects/cncf/cilium

**Comment by cynthia-sg** [comment]
Sorry, my bad, will fix it right away 😇

**Comment by xmulligan** [comment]
Thanks! Can you just resolve the conflicts?

**Review by qmonnet — CHANGES_REQUESTED** [review]
Thank you, can you please get rid of the merge commit (the second one in the PR)?

**Comment by cynthia-sg** [comment]
I think I created this PR from a fork that wasn’t up to date, hence the conflicts. I will close it and create a new one.

**Pull request closed without merging**
