### PR TITLE
golang: update to 1.13.6

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9872)

### CODE REVIEW

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Review by brb — APPROVED** [review]

**Comment by aanm** [comment]
all tests have previously passed. Fixed a documentation conflict. merging the PR

**Pull request merged**
