### PR TITLE
Fix typos in FQDN semaphore metric enablement.

### PR DESCRIPTION
**Pull request by rahulkjoshi**
Signed-off-by: Rahul Joshi <rkjoshi@google.com>

```release-note
Fixes typos in enabling fqdn_semaphore_rejected_total metric
```

### CODE REVIEW

**Review by nathanjsweet — APPROVED** [review]
Thanks!

**Review by sayboras — APPROVED** [review]
🚢

**Review by tklauser — APPROVED** [review]

**Comment by rahulkjoshi** [comment]
Do we need to do anything else to get this merged?

**Comment by sayboras** [comment]
> Do we need to do anything else to get this merged?

Nothing is pending from your side, this will be merged soon. Thanks a lot for your contribution :medal_sports:

**Pull request merged**
