### PR TITLE
v1.14 Backports 2023-07-18

### PR DESCRIPTION
**Pull request by gandro**
* [x] #26815 (@sayboras) :warning: Minor conflicts in auto-generated Helm chart values and docs (:heavy_check_mark: [approved in previous PR](https://github.com/cilium/cilium/pull/26885#pullrequestreview-1534469199))
 * [x] #26653 (@joestringer)
 * [x] #26655 (@joestringer)
 * [x] #26840 (@tklauser)
 * [x] #26874 (@michi-covalent)
 * [x] #25509 (@nvibert)
 * [x] #26869 (@gandro)
 * [x] #26812 (@chancez)
 * [x] #26883 (@michi-covalent)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 26815 26653 26655 26840 26874 25509 26869 26812 26883; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=26815,26653,26655,26840,26874,25509,26869,26812,26883
```

### CODE REVIEW

**Comment by gandro** [comment]
/test-backport-1.14

**Review by joestringer — APPROVED** [review]
Approving on behalf of my codeowners and for the backports of PRs I wrote.

**Comment by gandro** [comment]
Apparently we missed https://github.com/cilium/cilium/pull/26869 for ConformanceGKE :disappointed: It also needs `useDigest=false`.

**Review by michi-covalent — APPROVED** [review]
🥰

**Review by nvibert — APPROVED** [review]
My Mutual Auth docs have been merged so I am happy!

**Review by chancez — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by gandro** [comment]
All reviews are in and CI is as green as it's going to get. Marking as ready to merge.

**Pull request merged**
