### PR TITLE
31-10-2019 backports 1.6

### PR DESCRIPTION
**Pull request by borkmann**
v1.6 backports 2019-10-31

 * #9430 -- bpf: fix recirculation and remove range check (@borkmann)
 * #9443 -- bpf: fully merge dst port ranges for nodeport (@borkmann)
 * #9507 -- couple of misc nodeport improvements (@borkmann)
 * #9510 -- k8s: Provision NodePort services for LoadBalancer (@brb)
 * #9514 -- install: fix label used in ServiceMonitor to select cilium-agent (@pmahoney)
 * #9517 -- misc bpf nodeport fixes (@borkmann)

Once this PR is merged, you can update the PR labels via:
$ for pr in 9430 9443 9507 9510 9514 9517; do contrib/backporting/set-labels.py $pr done 1.6; done

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9532)

### CODE REVIEW

**Comment by borkmann** [comment]
never-tell-me-the-odds

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
net-next vm provision fail:
```08:14:37      k8s2-1.10: d83811f270d5: Pull complete
08:14:37      k8s2-1.10: ee671aafb583: Pull complete
08:14:38      k8s2-1.10: 7fc152dfb3a6: Pull complete
08:14:39  Cancelling nested steps due to timeout
08:14:39  Sending interrupt signal to process
08:14:44  script returned exit code 255
[Pipeline] }
[Pipeline] // retry```

**Comment by borkmann** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Pull request merged**
