### PR TITLE
makefile: fix unstripped docker images build

### LINKED ISSUE #18315: Cannot build unstripped container images
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm now learning Cilium and trying to attach `delve` to `cilium-agent` process. So, I'm building the Cilium unstripped images.

There are two potentially related issues.

1. In the latest `master`, `make docker-images-all-unstripped` fails with following error.

```
make: *** No rule to make target 'docker-operator-image-unstripped', needed by 'docker-operator-images-all-unstripped'.  Stop.
```

2. Above seems like only `operator` images are failing to build. But actually unstriped images are not built at all (unstripped images should have `-unstripped` suffix).

```
$ docker images
REPOSITORY                             TAG       IMAGE ID       CREATED              SIZE
quay.io/cilium/clustermesh-apiserver   latest    03a550907894   About a minute ago   53.9MB
quay.io/cilium/hubble-relay            latest    155c8d88a440   3 minutes ago        32.2MB
quay.io/cilium/docker-plugin           latest    904a25e22672   3 minutes ago        15.3MB
quay.io/cilium/cilium                  latest    8bace7fe76c4   3 minutes ago        437MB
```

Seems like `NOSTRIP` flags are not set. For example, `clustermesh-apiserver` image is built like this.

```
docker buildx build -f images/clustermesh-apiserver/Dockerfile  --load --build-arg BASE_IMAGE=scratch --build-arg NOSTRIP= --build-arg NOOPT= --build-arg LOCKDEBUG= --build-arg RACE= --build-arg V= --build-arg LIBNETWORK_PLUGIN= --build-arg CILIUM_SHA=99c034f398 --build-arg OPERATOR_VARIANT=clustermesh-apiserver -t quay.io/cilium/clustermesh-apiserver:latest .
```

I'm trying to solve this problem, but I haven't found the cause yet. Since there's no one reporting this issue, I'll leave here a report.

### Cilium Version

I'm not running Cilium.

### Kernel Version

```
$ uname -a
Linux yutaro-XPS-13-9310 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

I'm not running k8s.

### Sysdump

_No response_

### Relevant log output

```shell
GNU Make version


$ make --version
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by zhanghe9702**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #18315

### CODE REVIEW

**Review by jibi — CHANGES_REQUESTED** [review]
Thanks for your contribution! Could you please:

* go through the checklist and mark items accordingly
* amend the commit message to something like `makefile: fix unstripped docker images build`
* add some context on the commit message about what this fix is about (it's not clear to me how this is fixing the issue you referenced)

**Review by jibi — APPROVED** [review]

**Review by pchaigno — CHANGES_REQUESTED** [review]
Thanks for the fix!

Checkpatch is failing because you're missing an empty line between the commit title and its description. Could you fix that small nit? :pray:

**Comment by YutaroHayakawa** [comment]
Thanks for the fix! I'll test the change in my local.

**Comment by YutaroHayakawa** [comment]
Hrm, actually the fix doesn't work in my local.

What I did:

```
$ make docker-cilium-image-unstripped
Using Docker Buildx builder "default" with build flags " --load".
docker buildx build -f images/cilium/Dockerfile  --load --build-arg BASE_IMAGE=scratch --build-arg NOSTRIP= --build-arg NOOPT= --build-arg LOCKDEBUG= --build-arg RACE= --build-arg V= --build-arg LIBNETWORK_PLUGIN= --build-arg CILIUM_SHA=067ad136f2 --build-arg OPERATOR_VARIANT=cilium -t quay.io/cilium/cilium:latest .
```

It is still making the stripped image (which is not suffixed with `-unstripped`).

**Comment by zhanghe9702** [comment]
> Hrm, actually the fix doesn't work in my local.
> 
> What I did:
> 
> ```
> $ make docker-cilium-image-unstripped
> Using Docker Buildx builder "default" with build flags " --load".
> docker buildx build -f images/cilium/Dockerfile  --load --build-arg BASE_IMAGE=scratch --build-arg NOSTRIP= --build-arg NOOPT= --build-arg LOCKDEBUG= --build-arg RACE= --build-arg V= --build-arg LIBNETWORK_PLUGIN= --build-arg CILIUM_SHA=067ad136f2 --build-arg OPERATOR_VARIANT=cilium -t quay.io/cilium/cilium:latest .
> ```
> 
> It is still making the stripped image (which is not suffixed with `-unstripped`) and `NOSTRIP` option is not set.

yes, very strange behavior, i have modified the recipe and test in local machine.
zhanghe@node2:~/cilium/cilium$ docker images | grep unstripped
quay.io/cilium/operator-generic-unstripped            latest                                           8af67ebb4044   9 seconds ago        77.3MB
quay.io/cilium/operator-alibabacloud-unstripped       latest                                           0af8ba26fd4b   20 seconds ago       118MB
quay.io/cilium/operator-azure-unstripped              latest                                           a464604118bd   33 seconds ago       81MB
quay.io/cilium/operator-aws-unstripped                latest                                           ab71d6379a08   53 seconds ago       101MB
quay.io/cilium/operator-unstripped                    latest                                           5317e00811a1   About a minute ago   146MB
quay.io/cilium/clustermesh-apiserver-unstripped       latest                                           6a8eb05cbdcb   About a minute ago   73.8MB
quay.io/cilium/hubble-relay-unstripped                latest                                           7474c8133722   About a minute ago   43.6MB
quay.io/cilium/docker-plugin-unstripped               latest                                           8392d68bfea2   About a minute ago   21.7MB
quay.io/cilium/cilium-unstripped                      latest                                           507a01b51395   About a minute ago   509MB

**Comment by YutaroHayakawa** [comment]
Now I am pretty sure what were causing this issue. Above suggested changes describe them. If you think it makes sense for you, please commit suggested changes.

**Comment by YutaroHayakawa** [comment]
Ah, no sorry. My changes still doesn't work for the `docker-operator-image-unstripped`. Please forget above suggestions.

I still don't understand why @zhanghe9702's changes work, but I'll approve this PR since it works so better than doesn't work at all.

**Review by YutaroHayakawa — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
Smoke tests are passing and reviews are in. Marking ready to merge.

**Pull request merged**
