### PR TITLE
backport v1.14: gh/workflows: Reusable workflow for ci-e2e and misc changes

### PR DESCRIPTION
**Pull request by brb**
Manual backport of https://github.com/cilium/cilium/pull/27355.

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]

**Review by viktor-kurchenko — APPROVED** [review]

**Comment by ldelossa** [comment]
@brb is only the /ci-e2e tests necessary here to merge? If so please make a note here.

**Comment by brb** [comment]
@ldelossa Yep, only ci-e2e.

**Pull request merged**
