### PR TITLE
v1.15 Backports 2024-07-08

### PR DESCRIPTION
**Pull request by jibi**
* [x] #30580 (@Pionerd)
 * [x] #33514 (@aanm)
 * [x] #33509 (@julianwiedmann)
 * [x] #33420 (@gandro) :warning: resolved conflicts
 * [x] #33472 (@jasonaliyetti) :warning: resolved conflicts
 * [x] #33512 (@jasonaliyetti) :warning: resolved conflicts
 * [x] #33551 (@julianwiedmann)
 * [x] #33569 (@chaunceyjiang)
 * [x] #33624 (@julianwiedmann) :warning: resolved conflicts
 * [x] #33599 (@rgo3)

PRs skipped due to conflicts:

 * #33449 (@jrajahalme)
 * #33511 (@skmatti)
    * dropped the PR due to some build failures

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30580 33514 33509 33420 33472 33512 33551 33569 33624 33599
```

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Comment by jibi** [comment]
/test-backport-1.15

**Review by rgo3 — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by skmatti** [comment]
@jibi If possible, can you merge https://github.com/cilium/cilium/pull/33663 into this?

**Review by sayboras — APPROVED** [review]
Looks good for https://github.com/cilium/cilium/pull/33569

**Comment by jibi** [comment]
> @jibi If possible, can you merge #33663 into this?

@skmatti I think it should be fine to merge your PR separately :+1:

**Review by pchaigno — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by jibi** [comment]
(rebased and fixed the backport note on all commit messages)

**Comment by jibi** [comment]
/test-backport-1.15

**Review by aditighag — APPROVED** [review]

**Comment by krokofant** [comment]
Great contribution! I've been manually editing the dashboards to make them work before. 🏆

**Pull request merged**
