### PR TITLE
Nightly: Update CPU and RAM in Nightly test

### PR DESCRIPTION
**Pull request by eloycoto**
Updated the CPU and Memory in Nightly test and update kubernetes version
to 1.8

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

### CODE REVIEW

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
Hi @ianvernon 

If you can review and merge if it's possible it'll be great. With this changes we can retrieve the Jenkins artifacts, and I can debug the Nightly issues on Monday.

**Comment by ianvernon** [comment]
@eloycoto please examine the test failure associated with the most recent build, as there is a panic which looks to be caused due to bugs in the test framework. However, such bugs are not caused by the changes to this PR, so I'm merging it anyway.

**Pull request merged**
