### PR TITLE
v1.13 Backports 2024-04-30

### PR DESCRIPTION
**Pull request by gandro**
* [ ] #32008 (@darox)
 * [x] #32118 (@marseel)
 * [x] #31999 (@gandro) :warning: resolved conflicts
 * [ ] #32099 (@jasonaliyetti)
 * [x] #32085 (@pchaigno)
 * [ ] #32030 (@JBodkin-Amphora)
 * [ ] #32132 (@jrajahalme)
 * [x] #32176 (@dependabot[bot]) :warning: resolved conflicts
 * [x] #32181 (@tklauser) :warning: resolved conflicts
 * [x] #32201 (@marseel)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 32008 32118 31999 32099 32085 32030 32132 32176 32181 32201
```

### CODE REVIEW

**Review by tklauser — APPROVED** [review]
My change looks good, thanks Sebastian!

**Comment by gandro** [comment]
/test-backport-1.13

**Review by marseel — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Comment by gandro** [comment]
/test-1.23-4.19

**Comment by gandro** [comment]
/test-1.21-4.19

**Comment by gandro** [comment]
/test-1.21-4.19

**Comment by gandro** [comment]
Required CI is green, non-trivial reviews are in. Merging.

**Pull request merged**
