### PR TITLE
v1.4 backports 2019-06-27

### PR DESCRIPTION
**Pull request by jrajahalme**
Decided against backporting  #8014 (envoy: Do not use deprecated configuration options. (@jrajahalme)) due to vendor changes it would have required. This PR removed a deprecation warning from the logs, but does not affect functionality.

* #8352 -- CI: Cleanup VMs and reclaim disk on job completion (@raybejjani)
* #8351 -- Workaround for systemd 242 assigning MAC addr for virtual devices (@brb)
  - updated the vendor tree with `dep` rather than trying to manually fix the merge conflicts
* #8358 -- CI: Clean VMs and reclaim disk in nightly test (@raybejjani)

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8411)

### CODE REVIEW

**Comment by jrajahalme** [comment]
never-tell-me-the-odds

**Comment by jrajahalme** [comment]
never-tell-me-the-odds

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Comment by jrajahalme** [comment]
never-tell-me-the-odds

**Comment by jrajahalme** [comment]
test-docs-please

**Comment by jrajahalme** [comment]
test-missed-k8s

**Comment by jrajahalme** [comment]
Looks like a test flake (a docker problem) in the upstream k8s test, firing it again:
```
10:06:13      k8s1-1.12: Step 5/19 : COPY . ./
10:20:40      k8s1-1.12: failed to export image: failed to set parent sha256:6dd482e438cec506b0359965060b1311bbecf1a78237d96eedd4bc3b5b04f450: unknown parent image ID sha256:6dd482e438cec506b0359965060b1311bbecf1a78237d96eedd4bc3b5b04f450
10:20:40      k8s1-1.12: Makefile:144: recipe for target 'docker-image-no-clean' failed
10:20:40      k8s1-1.12: make: *** [docker-image-no-clean] Error 1
```

**Comment by jrajahalme** [comment]
test-upstream-k8s

**Comment by jrajahalme** [comment]
Similar docker failure, testing once more

**Comment by jrajahalme** [comment]
test-upstream-k8s

**Comment by joestringer** [comment]
I added a card to the v1.4 CI for the policy trace output ordering issue in the main CI tests:
https://github.com/cilium/cilium/projects/47#card-23364143

**Comment by joestringer** [comment]
test-upstream-k8s

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Regular tests provision issue:

```
20:57:55  ==> k8s1-1.8: Checking if box 'cilium/ubuntu' version '126' is up to date...
20:57:55  ==> k8s1-1.8: Setting the name of the VM: test_k8s1-18_1561755466317_68436
20:57:55  ==> k8s1-1.8: Fixed port collision for 22 => 2222. Now on port 2201.
20:57:55  ==> k8s1-1.8: Clearing any previously set network interfaces...
20:57:55  There was an error while executing `VBoxManage`, a CLI used by Vagrant
20:57:55  for controlling VirtualBox. The command and stderr is shown below.
20:57:55  
20:57:55  Command: ["dhcpserver", "add", "--ifname", "vboxnet0", "--ip", "172.28.128.2", "--netmask", "255.255.255.0", "--lowerip", "172.28.128.3", "--upperip", "172.28.128.254", "--enable"]
20:57:55  
20:57:55  Stderr: VBoxManage: error: DHCP server already exists
```

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Pull request merged**
