### PR TITLE
Install fib rules and routes with proto kernel to avoid systemd messing with them

### LINKED ISSUE #18706: Host network broken after one of the underlying interfaces of a bond goes down
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On Equinix Metal the network setup is a bond of two NICs using LACP.
When Cilium is used as CNI for Kubernetes on Flatcar Container Linux, and one of the two NIC interfaces goes down, the host network is broken and remains broken even if the underlying interface goes up again.

The network looks normal but `ping 1.1` leads to no outgoing packets visible in `tcpdump -i bond0` (ping reports 100% packet loss) and `ping 127.0.0.1` leads to `ping: sendmsg: Operation not permitted`.

We could not restore the network even after terminating the Pods and kubelet on the node, flushing nft and deleting the Cilium interfaces (maybe BPF programs are still loaded and not cleaned up?)

IPv6 is not affected, `ping6 2606:4700:4700::1111` works.

### Cilium Version

1.9, 1.10, 1.11 

### Kernel Version

from 5.10.52 to 5.10.84

### Kubernetes Version

1.22

### Sysdump

```
🔍 Collecting Kubernetes nodes
failed to create sysdump collector: failed to collect Kubernetes nodes: Get "https://136.144.49.47:6443/api/v1/nodes": dial tcp 136.144.49.47:6443: i/o timeout
```

### Relevant log output

Kernel
```
Feb 04 15:50:06 kernel: bond0: (slave enp2s0f0np0): link status down for interface, disabling it in 200 ms
Feb 04 15:50:06 kernel: bond0: (slave enp2s0f0np0): link status down for interface, disabling it in 200 ms
Feb 04 15:50:06 kernel: bond0: (slave enp2s0f0np0): link status down for interface, disabling it in 200 ms
Feb 04 15:50:06 kernel: bond0: (slave enp2s0f0np0): link status down for interface, disabling it in 200 ms
Feb 04 15:50:06 kernel: bond0: (slave enp2s0f0np0): invalid new link 1 on slave
Feb 04 15:50:06 kernel: mlx5_core 0000:02:00.0: modify lag map port 1:2 port 2:2
Feb 04 15:50:06 kernel: bond0: (slave enp2s0f0np0): link status definitely down, disabling slave
Feb 04 15:51:09 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): lxc_health: link becomes ready
Feb 04 15:51:10 kernel: lxc_health: Caught tx_queue_len zero misconfig
Feb 04 15:51:33 kernel: mlx5_core 0000:02:00.0 enp2s0f0np0: Link down
Feb 04 15:51:33 kernel: mlx5_core 0000:02:00.0 enp2s0f0np0: Link up
Feb 04 15:51:33 kernel: bond0: (slave enp2s0f0np0): link status up again after 200 ms
Feb 04 15:51:33 kernel: bond0: (slave enp2s0f0np0): link status definitely up, 10000 Mbps full duplex
Feb 04 15:51:35 kernel: mlx5_core 0000:02:00.0: modify lag map port 1:1 port 2:2
```

### Anything else?

Flatcar releases 2905.x.y to 3033.x.y are affected, running systemd from 247 to 249 (maybe relevant because systemd-networkd is used)

Flatcar releases 2764.x.y are not affected (kernel 5.10.43, systemd 247)

Reproduce it by provisioning an Equinix Metal machine with Flatcar Stable (used `c3.small.x86`).
Ensure it is on the latest version:

```
update_engine_client -update
sudo rm -f /etc/systemd/system/containerd.service.d/10-use-cgroupfs.conf
sudo sed -i 's/systemd.unified_cgroup_hierarchy=0 systemd.legacy_systemd_cgroup_controller//' /usr/share/oem/grub.cfg
sudo systemctl reboot
```

Set up a one-node Cilium cluster, using the script contents at the end:

```
sudo ./install.sh
```

Then, this action is valid and should not any harm, but now does:
```
sudo ip link set enp2s0f0np0 down
```
(and `sudo ip link set enp2s0f0np0 up` does not help)

The `install.sh` script used above:
```
#!/bin/bash

set -xe

systemctl enable --now docker
modprobe br_netfilter

cat <<EOF | tee /etc/modules-load.d/k8s.conf
br_netfilter
EOF

cat <<EOF | tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sysctl --system

CNI_VERSION="v0.8.2"
CRICTL_VERSION="v1.17.0"
RELEASE_VERSION="v0.4.0"
DOWNLOAD_DIR=/opt/bin
RELEASE="$(curl -sSL https://dl.k8s.io/release/stable.txt)"

mkdir -p /opt/cni/bin
mkdir -p /etc/systemd/system/kubelet.service.d

curl() {
	command curl -sSfL "$@"
}

curl "https://github.com/containernetworking/plugins/releases/download/${CNI_VERSION}/cni-plugins-linux-amd64-${CNI_VERSION}.tgz" | tar -C /opt/cni/bin -xz
curl "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz" | tar -C $DOWNLOAD_DIR -xz
curl "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service" | sed "s:/usr/bin:${DOWNLOAD_DIR}:g" | tee /etc/systemd/system/kubelet.service
curl "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/kubepkg/templates/latest/deb/kubeadm/10-kubeadm.conf" | sed "s:/usr/bin:${DOWNLOAD_DIR}:g" | tee /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
curl --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/{kubeadm,kubelet,kubectl}

curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz{,.sha256sum}
sha256sum --check cilium-linux-amd64.tar.gz.sha256sum
sudo tar xzvfC cilium-linux-amd64.tar.gz /opt/bin
rm cilium-linux-amd64.tar.gz{,.sha256sum}

chmod +x {kubeadm,kubelet,kubectl}
mv {kubeadm,kubelet,kubectl} $DOWNLOAD_DIR/

systemctl enable --now kubelet
#systemctl status kubelet

cat <<EOF | tee kubeadm-config.yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
controllerManager:
  extraArgs:
    flex-volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
networking:
  podSubnet: "192.168.254.0/24"
EOF

# For explicit cgroupdriver selection
# ---
# kind: KubeletConfiguration
# apiVersion: kubelet.config.k8s.io/v1beta1
# cgroupDriver: systemd

# For containerd
# apiVersion: kubeadm.k8s.io/v1beta2
# kind: InitConfiguration
# nodeRegistration:
#  criSocket: "unix:///run/containerd/containerd.sock

export PATH=$PATH:$DOWNLOAD_DIR

kubeadm config images pull
kubeadm init --config kubeadm-config.yaml

mkdir -p $HOME/.kube
cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.9.4/install/kubernetes/quick-install.yaml

kubectl taint nodes --all node-role.kubernetes.io/master-
kubectl get pods -A
kubectl get nodes -o wide

kubectl apply -f https://k8s.io/examples/application/deployment.yaml
kubectl expose deployment.apps/nginx-deployment

curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz{,.sha256sum}
tar xzvfC cilium-linux-amd64.tar.gz /opt/bin
rm cilium-linux-amd64.tar.gz{,.sha256sum}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by NikAleksandrov**
In order to workaround systemd's bad recent changes where they decided to manage "foreign" rules and to flush them on certain events (e.g. device flap), we should add our rules as "proto kernel" so systemd will just skip them and leave them in place in such events instead of wiping them from underneath us if a networkd policy like below is not installed (https://docs.cilium.io/en/stable/operations/system_requirements/#systemd-based-distributions):
```
ManageForeignRoutes=no
ManageForeignRoutingPolicyRules=no
```
Normal rules with Cilium deployed look like:
 $ ip ru
 9:	from all fwmark 0x200/0xf00 lookup 2004
 10:	from all fwmark 0xa00/0xf00 lookup 2005
 100:	from all lookup local
 32766:	from all lookup main
 32767:	from all lookup default

After a network event we see systemd flushing all unspec rules (9, 10 and 100, the last one being critical):
 $ ip rule list
 32766:  from all lookup main
 32767:  from all lookup default

With this change the rules remain in place and everything continues working as expected.

The change also affects routes installed by Cilium, they are now with proto kernel.
For example:
```
$ ip -d r sh
unicast 10.0.0.0/24 via 10.0.2.245 dev cilium_host proto kernel scope global src 10.0.2.245 mtu 1373 
unicast 10.0.1.0/24 via 10.0.2.245 dev cilium_host proto kernel scope global src 10.0.2.245 mtu 1373 
unicast 10.0.2.0/24 via 10.0.2.245 dev cilium_host proto kernel scope global src 10.0.2.245 
unicast 10.0.2.245 dev cilium_host proto kernel scope link

$ ip -d rule sh
1:      from all fwmark 0xd00/0xf00 lookup 200 proto kernel
1:      from all fwmark 0xe00/0xf00 lookup 200 proto kernel
9:      from all fwmark 0x200/0xf00 lookup 2004 proto kernel
10:     from all fwmark 0xa00/0xf00 lookup 2005 proto kernel
100:    from all lookup local proto kernel
32766:  from all lookup main proto kernel
32767:  from all lookup default proto kernel

$ ip -d rou sh table 200
unicast 10.0.0.0/24 dev cilium_host proto kernel scope global mtu 1450 
unicast 10.0.1.0/24 dev cilium_host proto kernel scope global mtu 1450 
local 10.0.2.0/24 dev cilium_vxlan proto kernel scope host 

$ ip -d rou sh table 2004
local default dev lo proto kernel scope host 

$ ip -d rou sh table 2005
unicast default via 10.0.2.245 dev cilium_host proto kernel scope global 
unicast 10.0.2.245 dev cilium_host proto kernel scope link 
```

Note that we rely on the fact that route deletes with proto == 0 cause the kernel to not check if
the route protocol matches (it is ignored). Note also that there is one exception for the conversion done
which is about node-to-node encryption routes because those overload the route protocol and use it
to recognize routes installed by Cilium for node-to-node encryption. That can be revisited additionally.

Patches overview:
 Patch 01 - adds a new RTProto constant in linux_defaults to be used for fib rules and routes
 Patch 02 - adds a new RulePriorityLocalLookup constant in linux_defaults to be used for fib rules and routes
 Patch 03 - changes rules and routes in bpf/init.sh (also default rt proto is taken as an argument)
 Patch 04 - changes init.sh to take the local lookup rule priority as an argument
 Patch 05 - updates the netlink library to get RTA_PROTOCOL support for fib rules
 Patch 06 - adds support for rule protocol to datapath/linux/route
 Patch 07 - updates datapath/linux/route
 Patch 08 - updates egress gateway
 Patch 09 - updates datapath/loader
 Patch 10 - updates datapath/linux/routing (skips migration code, more in commit msg)
 Patch 11 - updates datapath/linux/node (the patch doesn't modify node-to-node encryption routes)
 Patch 12 - removes RouteProtocolIPSec and uses proto kernel instead
 Patch 13 - adds "-d" to bugtool when dumping fib rules so we can log their protocol
 Patch 14 - ensures that local lookup IP rules are installed on agent init and also cleans up old local lookup rules with a 
                   different rt proto only if they're before the new ones with proto kernel
                   
I have tested locally IPv4, IPv6 with and without tunnels, with and without ipsec. Routes and rules are installed
and cleaned up properly. This set also fixes another bug when we restore ip rules on init.sh failure, we'd
install rule #0 with proto unspec instead of kernel as the original rule.

Closes: #18706

Thanks,
 Nik

### CODE REVIEW

**Comment by brandshaide** [comment]
@NikAleksandrov any update on this PR since it's still in status `Draft` but seems to be ready to be shipped according to @borkmann We've stumbled upon this issue on our AKS cluster and this fix would've saved us a lot of time ;-)

**Comment by NikAleksandrov** [comment]
> @NikAleksandrov any update on this PR since it's still in status `Draft` but seems to be ready to be shipped according to @borkmann ?We've stumbled upon this issue on our AKS cluster and this fix would've saved us a lot of time ;-)

@brandshaide it is incomplete, to fix the issue fully we need to change all routes and rules to use proto kernel
but we're currently blocked by merging support for the proto attribute in the netlink library ([PR](https://github.com/vishvananda/netlink/pull/855)).
Once that is merged I can push the additional changes that will complete the fix.

**Comment by brandshaide** [comment]
> > @NikAleksandrov any update on this PR since it's still in status `Draft` but seems to be ready to be shipped according to @borkmann ?We've stumbled upon this issue on our AKS cluster and this fix would've saved us a lot of time ;-)
> 
> @brandshaide it is incomplete, to fix the issue fully we need to change all routes and rules to use proto kernel but we're currently blocked by merging support for the proto attribute in the netlink library ([PR](https://github.com/vishvananda/netlink/pull/855)). Once that is merged I can push the additional changes that will complete the fix.

@NikAleksandrov aweseome! and thanks a lot for your efforts 👍

**Review by YutaroHayakawa — APPROVED** [review]
Overall, looks nice to me. A non-blocking suggestion. I think it's better to define Go constant like `DefaultRTProto` (and the equivalent shell-script variable) and use that instead of hard-coding kernel protocol. So that when this kernel protocol comes at a problem, we can easily change that instead of finding all the places we set protocol.

**Comment by NikAleksandrov** [comment]
> Overall, looks nice to me. A non-blocking suggestion. I think it's better to define Go constant like `DefaultRTProto` (and the equivalent shell-script variable) and use that instead of hard-coding kernel protocol. So that when this kernel protocol comes at a problem, we can easily change that instead of finding all the places we set protocol.

Yep, good point. Coming right up.

**Comment by NikAleksandrov** [comment]
@YutaroHayakawa I've requested a new review, the code is basically the same just using a constant as you suggested.

**Review by borkmann — APPROVED** [review]
LGTM, great work!

**Comment by borkmann** [comment]
> LGTM, great work!

Small follow-up q: would upgrading all the rules/routes work seamlessly from one Cilium minor release to the next once we have this backported to say 1.13?

**Comment by NikAleksandrov** [comment]
> > LGTM, great work!
> 
> Small follow-up q: would upgrading all the rules/routes work seamlessly from one Cilium minor release to the next once we have this backported to say 1.13?

Hmm.. good question, so on upgrade the routes and rules are not replaced. In order to do that either the node needs to be rebooted or some options changed that cause a replace. We should at the very minimum catch the upgrade path for
the local lookup rule which causes full host outage when removed. I'll add new code on agent startup to detect the old
rule with proto unspec and add a new one with proto kernel for local lookups.

**Review by borkmann — APPROVED** [review]
new changes LGTM, thanks!

**Review by YutaroHayakawa — APPROVED** [review]
LGTM! Thanks!

**Comment by pchaigno** [comment]
This PR introduced a CI-only regression that was fixed by https://github.com/cilium/cilium/pull/24577. We'll thus need to backport that second PR wherever we backport this one.

**Comment by gandro** [comment]
> This PR introduced a CI-only regression that was fixed by #24577. We'll thus need to backport that second PR wherever we backport this one.

Why did CI not catch the regression in this PR?

**Comment by jibi** [comment]
Dropped the needs-backport labels as this PR is likely to be reverted

**Comment by vethastanley** [comment]
I see the fix is reverted. Do we know whether this issue will be fixed anytime recently?

**Pull request merged**
