### PR TITLE
mtu: autodetect MTU for IPv6 only network

### PR DESCRIPTION
**Pull request by nirmoy**
autoDetect() fails On IPv6 only deployement.
This PR adds a fails safe if IPv4 check fails

Signed-off-by: Nirmoy Das <ndas@suse.de>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7392)

### CODE REVIEW

**Comment by nirmoy** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Hit known flake #7126 .

**Comment by nirmoy** [comment]
test-me-please

**Comment by nirmoy** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Pull request merged**
