### PR TITLE
Remove CiliumOperatorName constant

### PR DESCRIPTION
**Pull request by miono**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ]  All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

### CODE REVIEW

**Review by thorn3r — COMMENTED** [review]
Thanks for the submission! It looks like there are no longer any references to this constant. I think we can just remove it rather than correcting the typo.

**Comment by miono** [comment]
I've amended my commit to do that instead!

**Review by thorn3r — APPROVED** [review]
Thanks!

**Comment by miono** [comment]
Do you need me to rebase maybe, or why are the tests failing?

**Comment by thorn3r** [comment]
Hey @miono yes please rebase and I'll retrigger the tests. The clustermesh related failures are caused by the changes in [this PR](https://github.com/cilium/cilium/pull/31677). The workflow runs on main and this branch is missing the needed changes.

**Comment by miono** [comment]
@thorn3r Rebased on main!

**Pull request merged**
