### PR TITLE
docs: Fix gRPC API generation for online docs

### PR DESCRIPTION
**Pull request by qmonnet**
This is an attempt to fix [the gRPC API](https://docs.cilium.io/en/latest/grpcapi/), which is missing from the hosted version of the documentation. Let's try to symlink the `api` directory instead of having an additional step to copy it.

I'll mark this PR for backports if it gets merged and if it indeed fixes the API reference on the hosted documentation.

### CODE REVIEW

**Comment by qmonnet** [comment]
Netlify preview still works :tada:

**Comment by qmonnet** [comment]
... But this will of course require an update of the docs-builder image, that we still haven't automated (https://github.com/cilium/cilium/pull/24121)

**Review by viktor-kurchenko — APPROVED** [review]
LGTM.

**Review by christarazi — APPROVED** [review]

**Review by zacharysarah — APPROVED** [review]
This looks like a reasonable approach to me.

**Comment by qmonnet** [comment]
I confirm the issue is fixed [on the online doc](https://docs.cilium.io/en/latest/grpcapi/) :tada:

Let's mark this for backports.

**Pull request merged**
