### PR TITLE
v1.10 backports 2022-07-13

### PR DESCRIPTION
**Pull request by ti-mo**
* ~~#20072 -- datapath: Create sysctl `rp_filter` overwrite config on agent init (@dylandreimerink)~~
 Please manually backport, was not able to quickly figure out where this fit into the old DaemonSet layout.
 * #19379 -- add support for AKS BYOCNI (@nbusseneau)
   **Extra attention needed, not sure if I got it right.**
 * #20388 -- ctmap: Do not use nil locks (@jrajahalme)
 * #20399 -- docs: Improve policy troubleshooting guide (@joestringer)
 * #16499 -- docs: Document clustermesh datapath configuration for non-tunneled modes (@jrajahalme)
 * #19533 -- Use '.Values.enableIPv4Masquerade' in 'node-init' (@bmcustodio)
 * #20389 -- daemon: Fix issue where stale router IPs were not cleaned up (@gandro)
 * ~~#20305 -- dnsproxy: update dnsproxy benchmark memory calculation (@odinuge)~~
   The benchmark structure changed somewhat since and the changes didn't fit in, please take a look if it can be manually backported.
 * #20296 -- Add Peer Service to Cilium DS Port List (@nathanjsweet)
 * #20486 -- docs: Bump up Netlify Python version to 3.8 (@michi-covalent)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 19379 20388 20399 16499 19533 20389 20296 20486; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Review by gandro — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Review by kaworu — APPROVED** [review]
"Add Peer Service to Cilium DS Port List" commit LGTM

**Comment by aanm** [comment]
/test-backport-1.10

**Review by michi-covalent — APPROVED** [review]
lgtm: `docs: Bump up Netlify Python version to 3.8`

**Review by nbusseneau — APPROVED** [review]

**Comment by ldelossa** [comment]
Same flakes as seen in v1.12 backports. Merging.

**Pull request merged**
