### PR TITLE
bpffs: Fix panic when root directory does not exist

### PR DESCRIPTION
**Pull request by eloycoto**
Backport #4474

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4553)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by eloycoto** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4232/testReport/junit/(root)/runtime/RuntimeValidatedPolicies_Tests_Egress_To_World/

**Comment by eloycoto** [comment]
test-me-please

**Comment by aanm** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4240/testReport/junit/(root)/runtime/RuntimeValidatedConntrackTest_Conntrack_related_configuration_options_for_endpoints/

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
