### PR TITLE
v1.15 Backports 2024-04-29

### PR DESCRIPTION
**Pull request by gandro**
* [x] #29916 (@mhofstetter)
 * [x] #31866 (@squeed)
 * [x] #32066 (@chancez)
 * [ ] #32025 (@lou-lan)
 * [ ] #32008 (@darox)
 * [x] #32118 (@marseel)
 * [x] #31999 (@gandro) :warning: resolved conflicts by rerunning go get
 * [ ] #32099 (@jasonaliyetti)
 * [x] #32116 (@julianwiedmann)
 * [x] #32085 (@pchaigno)
 * [ ] #32030 (@JBodkin-Amphora)
 * [ ] #32132 (@jrajahalme)
 * [x] #32176 (@dependabot[bot]) :warning: resolved conflicts by using newer version of docs image
 * [x] #32181 (@tklauser) :warning: resolved conflicts by regenerating Helm README.md
 * [x] #32168 (@squeed)
 * [x] #32069 (@aanm)
 * [x] #32203 (@mhofstetter)
 * [x] #32201 (@marseel)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 29916 31866 32066 32025 32008 32118 31999 32099 32116 32085 32030 32132 32176 32181 32168 32069 32203 32201
```

### CODE REVIEW

**Review by mhofstetter — APPROVED** [review]
My commits look good - thanks Sebastian!

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by marseel — APPROVED** [review]

**Comment by gandro** [comment]
/test-backport-1.15

**Review by aanm — APPROVED** [review]

**Review by youngnick — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Review by squeed — APPROVED** [review]

**Review by chancez — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Comment by gandro** [comment]
Non-trivial reviews are in, CI is green. Merging.

**Pull request merged**
