### PR TITLE
v1.13 Backports 2023-12-14 [Author Submitted]

### PR DESCRIPTION
**Pull request by jrfastab**
* [ ] #29801 

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
29801
```

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Comment by jrfastab** [comment]
/test-backport-1.13

**Review by ldelossa — APPROVED** [review]

**Comment by michi-covalent** [comment]
/test-backport-1.13

**Comment by michi-covalent** [comment]
/test-1.23-4.19

**Comment by michi-covalent** [comment]
/test-1.23-4.19

**Pull request merged**
