### PR TITLE
[v1.12] Author backport of WG Node handler and dependent PR

### PR DESCRIPTION
**Pull request by bimmlerd**
* [x] #25450 (@bimmlerd)
 * [x] #25419 (@bimmlerd)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 25450 25419; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=25450,25419
```

### CODE REVIEW

**Comment by bimmlerd** [comment]
/test-backport-1.12

**Review by gandro — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Comment by gandro** [comment]
test-1.16-4.9 looks like it hit a variant of https://github.com/cilium/cilium/issues/24839

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/16/testReport/junit/Suite-k8s-1/16/K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies/

**Comment by gandro** [comment]
/test-1.16-4.9

**Comment by bimmlerd** [comment]
Marked as a release blocker, since this is a regression fix (see https://github.com/cilium/cilium/pull/25419#issuecomment-1568056801).

**Pull request merged**
