### PR TITLE
v1.11: Update Go to 1.17.8

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Review by gandro — APPROVED** [review]

**Comment by tklauser** [comment]
/test-backport-1.11

**Review by aanm — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by tklauser** [comment]
/test-1.23-4.9

**Comment by tklauser** [comment]
runtime failed on #18919: https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1498/
k8s-1.21-kernel-5.4 failed on #18873 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-5.4/666/

These are known issues/flakes, all other tests passed. Marking as ready to merge given that all reviewers approved.

**Pull request merged**
