### PR TITLE
api/v1: Include string representations of data path types

### LINKED ISSUE #277: TraceToLxc is not handled properly
Definitely encountered this in `-o json`, not sure if this is also affecting other printer formats

cilium uses iota for `TraceToLxc` segment, which during decoding gets assumed as default empty value and thus ommitted.

iota:
https://github.com/cilium/cilium/blob/450c79ce5e2fbdeb32833df45c04bd529ff6ff4b/pkg/monitor/api/types.go#L135

parser decode:
https://github.com/cilium/cilium/blob/3d57190d73e0407865452bed93f1d4126e3235fd/pkg/hubble/parser/threefour/parser.go#L430

omitempty:
https://github.com/cilium/cilium/blob/18e5c632fb5013763eedde3aaea9ea9995da7a05/api/v1/flow/flow.pb.go#L1191

### PR DESCRIPTION
**Pull request by glibsm**
Fixes https://github.com/cilium/hubble/issues/277

### CODE REVIEW

**Comment by glibsm** [comment]
Rel https://github.com/cilium/hubble/issues/277

**Review by michi-covalent — APPROVED** [review]

**Comment by michi-covalent** [comment]
i'm a bit torn about this, whether the field should be a string or an enum. i understand that maintaining an enum might become too much work, but i think it would make the api easier to use. what do you all think?

**Comment by glibsm** [comment]
> i'm a bit torn about this, whether the field should be a string or an enum. i understand that maintaining an enum might become too much work, but i think it would make the api easier to use. what do you all think?

That's a good point, enum is probably better here since it's a finite set

**Comment by gandro** [comment]
Marked for backport (and consequently removed the `wait-until-release` label), since this ideally should land in 1.8 if possible, as best-effort. Not a release blocker though. (/cc @aanm)

**Comment by aanm** [comment]
test-me-please

**Comment by gandro** [comment]
@glibsm Are you planning to change this PR to use enums? If so, please change the PR status to draft. If no action is taken, the current version will likely get merged eventually. This would be fine by me, but your last comment suggests you wanted to reiterate on the approach.

**Comment by glibsm** [comment]
@gandro the train to declare this DRAFT has long gone since you can only open the PR as draft :)

I can tag this as do-not-merge until the decision is made.

**Comment by gandro** [comment]
> @gandro the train to declare this DRAFT has long gone since you can only open the PR as draft :)
> 
> I can tag this as do-not-merge until the decision is made.

https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft/ ;)

**Comment by glibsm** [comment]
How could I have possibly missed it? 
image

**Comment by glibsm** [comment]
Superseeded by #12085

**Pull request closed without merging**
