### PR TITLE
install/kubernetes: Helm option for fragment tracking

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request adds a Helm option to allow users to disable IPv4 fragment tracking.

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]

**Review by aanm — CHANGES_REQUESTED** [review]
I think this conflicts with the work being done in https://github.com/cilium/cilium/pull/12097. @tgraf will #12097 introduce some kind of compatibility checker that avoids changes like this PR is doing?

**Review by qmonnet — APPROVED** [review]
I don't know about the possible conflict mentioned by André, but pending this is solved the patch looks good to me. Thanks!

**Review by nebril — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by pchaigno** [comment]
retest-4.19

**Review by aanm — APPROVED** [review]

**Pull request merged**
