### PR TITLE
v1.8: Update Go to 1.14.8

### PR DESCRIPTION
**Pull request by tklauser**
```release-note
update Go to 1.14.8
```

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
retest-gke

**Comment by tklauser** [comment]
retest-4.9

**Comment by tklauser** [comment]
retest-4.9

**Comment by tklauser** [comment]
test-backport-1.8

**Comment by tklauser** [comment]
test-upstream-k8s

**Comment by tklauser** [comment]
test-upstream-k8s

**Comment by tklauser** [comment]
I think GKE and k8s-1.19-kernel-4.9 failures can be ignored, they were run by mistake because I used `test-me-please` instead of `test-backport-1.8` initially, this should be good to merge once @cilium/janitors approve.

**Pull request merged**
