### PR TITLE
Bump k8s 1.11 test version and dependencies to 1.11.3

### PR DESCRIPTION
**Pull request by aanm**
depends on https://github.com/cilium/cilium/pull/5520

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5521)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
depends on https://github.com/kubernetes/release/issues/624

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-upstream-k8s

**Review by joestringer — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Pull request merged**
