### PR TITLE
[v1.16] Add missing test coverage in v1.16 branch

### PR DESCRIPTION
**Pull request by aanm**
This is a follow up of https://github.com/cilium/cilium/pull/35157 which should not have been merged without these changes. Once this PR is merged we will make the upgrade tests required to be merged.

### CODE REVIEW

**Comment by aanm** [comment]
'15' - Failed once related with the health
'8' - Cilium wasn't able to start right from the beginning.

**Comment by aanm** [comment]
/test-backport-1.16

**Review by julianwiedmann — APPROVED** [review]

**Review by brlbil — APPROVED** [review]

**Comment by giorio94** [comment]
@aanm Where do matrix entries 23 to 26 come from? They caused a hidden conflict (in the matrix name/maximum parallelism) when backporting a new entry, because they don't appear to be present on main (and they don't seem to have been present in the conformance-e2e workflow either --- https://github.com/cilium/cilium/pull/35157/commits/6b7ae3c3108a8e4380439cd185e906e4fa653aeb)

**Pull request merged**
