### PR TITLE
Fix operator shutdown hanging when kvstore is enabled

### PR DESCRIPTION
**Pull request by giorio94**
Reporting here the message of the last commit, which addresses the core issue, for convenience:

> https://github.com/cilium/cilium/commit/f487647f4b5da61bd047a36d561cc61effe4943c ("operator: Wait for informers to shut down when stopping") introduced a WaitGroup to wait for the shutdown of all goroutines started by `legacy.onStart`. When running in kvstore mode, the operator spawns one goroutine to synchronize global services to the kvstore, continuously reading from a channel. Since that channel is never closed, the goroutine does not terminate, preventing the correct shutdown of the operator. This commit fixes it propagating the context, and stopping the goroutine when it is canceled.

The first two commits instead, perform the following modifications to the controller implementation:
1. Access the controller context while holding the mutex, to avoid reading it while being overwritten on restart.
2. Do not rerun the DoFunc once the context has been canceled. This caused spurious errors during operator shutdown, since the controllers handling the renew of etcd leases started failing repeatedly due to the context being closed.

```release-note
Fix operator shutdown hanging when kvstore is enabled
```

### CODE REVIEW

**Comment by giorio94** [comment]
ci-multicluster hit known failure https://github.com/cilium/cilium/issues/24990

**Comment by giorio94** [comment]
test-1.27-net-next egressgw tests failed due to https://github.com/cilium/cilium/pull/24835 having been merged, as this one is not rebased.

**Review by joamaki — APPROVED** [review]

**Review by thorn3r — APPROVED** [review]
looks great! appreciate the detailed commit messages :heavy_plus_sign:

**Pull request merged**
