### PR TITLE
golang: update to 1.14

### PR DESCRIPTION
**Pull request by aanm**
```release-note
golang: update to 1.14
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10340)

### CODE REVIEW

**Comment by Rolinh** [comment]
@aanm I think that the go version in the `go.mod` file should be updated to 1.14 as well, no? It currently [still points to 1.13](https://github.com/cilium/cilium/blob/pr/update-golang-to-1.14/go.mod#L3).

**Review by tklauser — APPROVED** [review]

**Comment by aanm** [comment]
never-tell-me-the-odds

**Review by raybejjani — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
the test that failed didn't failed previously. I've opened a GH issue to track this new flake

**Pull request merged**
