### PR TITLE
test-l4lb: Use QUAY_ORGANIZATION_DEV as the Quay org name

### PR DESCRIPTION
**Pull request by michi-covalent**
Use QUAY_ORGANIZATION_DEV environment variable as Quay organization name to be consistent with other workflow files.

### CODE REVIEW

**Comment by michi-covalent** [comment]
✅✅✅ `ci-l4lb` passed: https://github.com/cilium/cilium/actions/runs/4767610134

i'll remove the temporary commit

**Review by viktor-kurchenko — APPROVED** [review]
LGTM.

**Pull request merged**
