### PR TITLE
[Packaging] Fix deb packages build

### PR DESCRIPTION
**Pull request by eloycoto**
Hello!

This PR is going to be an annoying task, sorry for that! Let me explain a few problems to get the package into Ubuntu/Debian official repositories. 

The way to submit packages to Ubuntu/Debian is to upload the source to the [Launchpad](https://launchpadlibrarian.net/329508570/buildlog_ubuntu-xenial-amd64.cilium_0.9.90_BUILDING.txt.gz), and it will compile on Launchpad servers.   All the dependencies (to compile) need to be in the official repos,  and Cilium has the following problems: 

- Go-Bindata: a recent version needs to be used. The package version is too old, and it's not working. 
- Golang: The official version is 1.7.4 and Cilium needs 1.8 to compile. 

My plan was to submit the package on Ubuntu or Debian, but ATM we must wait until these dependencies get fixed in the future releases. I tried to upload in a personal repository (PPA), but send binary packages are not allowed. 

My proposal is: 

- Keep the changelog up to date using `make release` command each time that a new change is added. So in the future, we don't need to work on that.  
- Create a cilium deb repo, that provides deb packages to the people that want to use it. I can build it and provide support for it. 

`make build-deb` creates the deb file in the correct format, but using Docker for the dependencies. 

Feel free to request changes, I think that having nightly builds in deb packages is valuable for the project, so I'm happy to suit to your workflow. 

Regards.

### CODE REVIEW

**Comment by aanm** [comment]
@eloycoto Is it normal to have such a large changelog? I thought we could use something like this https://github.com/cilium/cilium/pull/1146

**Comment by eloycoto** [comment]
I tried to build the deb with the less trouble as possible when a new release is created. So the changelog is created with the git-buildpackage options, this means that it gets all the info from the git log from tag to tag. 

Happy to parse the NEWS file and create a Debian changelog format. Not a real problem ;-)

**Comment by tgraf** [comment]
> I tried to build the deb with the less trouble as possible when a new release is created. So the changelog is created with the git-buildpackage options, this means that it gets all the info from the git log from tag to tag.
> 
> Happy to parse the NEWS file and create a Debian changelog format. Not a real problem ;-)

I think using git-buildpackage is fine. The majority if not all users will prefer the release notes online which provide links to the pull requests with additional information and discussions. Do you agree @aanm?

**Review by tgraf — APPROVED** [review]

**Comment by aanm** [comment]
>> I tried to build the deb with the less trouble as possible when a new release is created. So the changelog is created with the git-buildpackage options, this means that it gets all the info from the git log from tag to tag.
>> 
>> Happy to parse the NEWS file and create a Debian changelog format. Not a real problem ;-)
>
>I think using git-buildpackage is fine. The majority if not all users will prefer the release notes online which provide links to the pull requests with additional information and discussions. Do you agree @aanm?

I'm fine with it, I was just wondering what was the normal behavior for deb packaging.

**Review by aanm — APPROVED** [review]

**Review by aalemayhu — CHANGES_REQUESTED** [review]
I would have a shorter changelog. I don't think people reading the debian changelog are interested in all upstream development. A few lines should suffice IMO.
For example see

- https://anonscm.debian.org/cgit/pkg-chromium/pkg-chromium.git/tree/debian/changelog
- https://anonscm.debian.org/cgit/collab-maint/ocrad.git/tree/debian/changelog
- https://anonscm.debian.org/cgit/pkg-mutt/mutt.git/tree/debian/changelog

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
This is awesome!

**Pull request merged**
