### PR TITLE
ci: pick up cilium-cli v0.11.11 for master, v1.11 and v1.12 workflows

### LINKED ISSUE #20397: upgrade Cilium CLI to `v0.11.11`
We need to release `v0.11.11` of the Cilium CLI before v1.12 proper release for AKS BYOCNI to work as intended with v1.12 charts (full details at https://github.com/cilium/cilium-cli/pull/953), and then bump the version in CI workflows so we can re-enable the AKS workflow for `master`.

This issue is just there to have a visible issue with the `release-blocker` label on the main repo.

### PR DESCRIPTION
**Pull request by tklauser**
Release notes:
https://github.com/cilium/cilium-cli/releases/tag/v0.11.11

Fixes #20397

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
:shipit:

**Review by nbusseneau — APPROVED** [review]

**Comment by tklauser** [comment]
All affected workflows passed on `master` and reviews are in. Removing `DO NOT MERGE` commit and marking as ready to merge.

**Review by michi-covalent — APPROVED** [review]

**Comment by ldelossa** [comment]
@tklauser I'm running into an issue while cherry picking this into v1.12. 

```
Unmerged paths:
  (use "git restore --staged <file>..." to unstage)
  (use "git add/rm <file>..." as appropriate to mark resolution)
	deleted by us:   .github/workflows/conformance-aks-v1.11.yaml
	deleted by us:   .github/workflows/conformance-aks-v1.12.yaml
	deleted by us:   .github/workflows/conformance-aks.yaml
	deleted by us:   .github/workflows/conformance-aws-cni-v1.11.yaml
	deleted by us:   .github/workflows/conformance-aws-cni-v1.12.yaml
	deleted by us:   .github/workflows/conformance-aws-cni.yaml
	deleted by us:   .github/workflows/conformance-eks-v1.11.yaml
	deleted by us:   .github/workflows/conformance-eks-v1.12.yaml
	deleted by us:   .github/workflows/conformance-eks.yaml
	deleted by us:   .github/workflows/conformance-externalworkloads-v1.11.yaml
	deleted by us:   .github/workflows/conformance-externalworkloads-v1.12.yaml
	deleted by us:   .github/workflows/conformance-externalworkloads.yaml
	deleted by us:   .github/workflows/conformance-gke-v1.11.yaml
	deleted by us:   .github/workflows/conformance-gke-v1.12.yaml
	deleted by us:   .github/workflows/conformance-gke.yaml
	deleted by us:   .github/workflows/conformance-k8s-network-policies.yaml
	deleted by us:   .github/workflows/conformance-multicluster-v1.11.yaml
	deleted by us:   .github/workflows/conformance-multicluster-v1.12.yaml
	deleted by us:   .github/workflows/conformance-multicluster.yaml
```
it appears the cherry pick assumes deletion of all files. 

does this PR need to be back ported?

**Comment by tklauser** [comment]
@ldelossa only the changes to `conformance-ingress.yaml`, `conformance-kind.yaml`, `tests-smoke.yaml` and `tests-smoke-ipv6.yaml` need to be backported. Sorry, I forgot to mention this in the PR description.

All other workflows only exist in `master` and are used from the stable branches. These can be skipped.

**Comment by ldelossa** [comment]
Got it.

**Pull request merged**
