### PR TITLE
pkg/datapath/link: Use pure go implementation

### PR DESCRIPTION
**Pull request by florianl**
Signed-off-by: Lehner Florian <dev@der-flo.net>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](http://docs.cilium.io/en/stable/contributing/#submitting-a-pull-request)
- [-] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue. 
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](http://docs.cilium.io/en/stable/contributing/#dev-coo).
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

This PR replaces the dependency vishvananda/netlink with a pure go rtnetlink implementation.

```release-note
release-note/minor
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7821)

### CODE REVIEW

**Comment by brb** [comment]
@florianl Thanks for your contribution!

What is an advantage of replacing the mature `vishvananda/netlink` with `jsimonetti/rtnetlink`?

**Comment by florianl** [comment]
`jsimonetti/rtnetlink` exposes the socket for the rtnetlink communication via the API, while `vishvananda/netlink` uses a package wide used `pkgHandle`.

**Comment by florianl** [comment]
At the moment, I'm confused, where the `github.com/cilium/cilium: missing from vendor`comes from and how this dependency got introduced.

**Comment by brb** [comment]
> jsimonetti/rtnetlink exposes the socket for the rtnetlink communication via the API <..>

But why should it matter to us? Under the hood, both libraries use `AF_NETLINK` sockets to communicate with the kernel.

In addition, `vishvananda/netlink` has a better coverage, as it has been more widely adopted (e.g. Kubernetes and Docker use it).

**Comment by florianl** [comment]
I think, it could matter if multiple netlink commands are send at the same time. With `jsimonetti/rtnetlink` you can have multiple sockets, while `vishvananda/netlink` uses only one socket per netlink family in its `pkgHandle`.

But I agree with you, `vishvananda/netlink` is more widely used than `jsimonetti/rtnetlink`.

**Pull request closed without merging**
