### PR TITLE
Add missing generated Deepcopy functions

### PR DESCRIPTION
**Pull request by raybejjani**
These seem to be missing, although it's unclear where they are coming from. I think it's a recursive descent in the deepcopy of a higher level type, but I'm not sure.

I'm not sure this is a real "fix"!

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6747)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@raybejjani does it need backport to 1.4?

**Comment by ianvernon** [comment]
@raybejjani these types are coming from the new CEP code introduced here: https://github.com/cilium/cilium/pull/6697

**Comment by ianvernon** [comment]
@aanm @raybejjani I think this should be backported to v1.4 since #6697 is also going to be backported.

**Review by tgraf — CHANGES_REQUESTED** [review]
Their use is limited to:

```
// +k8s:deepcopy-gen=false
type EndpointStatus struct {
```

So it seems that `+k8s:deepcopy-gen=false` tags are missing for the sub types. It doesn't hurt to have it but it's not really needed.

**Pull request closed without merging**
