### PR TITLE
Revert "pkg/k8s: add k8s external IPs support"

### PR DESCRIPTION
**Pull request by aanm**
This reverts commit 46ae5ef2be6b72a80769c7931b48fed7339113c3.

```release-note
Revert k8s external IPs support due wrong implementation
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9125)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
I think this is ready to merge - the BPF nodeport failure is a known flaky test.

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
