### PR TITLE
hubble: add printer for lost events

### PR DESCRIPTION
**Pull request by aanm**
Currently hubble can't handle lost events which results on a large output on CI runs [1]. This commit implements this missing functionality while trying to maintain the same format for other types of messages.

[1]
```
2024-10-01T05:27:10.3601309Z unknown response type: &{LostEvents:source:HUBBLE_RING_BUFFER  num_events_lost:1}
2024-10-01T05:27:10.3601823Z unknown response type: &{LostEvents:source:HUBBLE_RING_BUFFER  num_events_lost:1}
2024-10-01T05:27:10.3602406Z unknown response type: &{LostEvents:source:HUBBLE_RING_BUFFER  num_events_lost:1}
```

Related to https://github.com/cilium/cilium/issues/34981

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]
🖨️

**Comment by bimmlerd** [comment]
I don't think "Fixes:" is correct. Yes, the printer will not show an unknown event, but it doesn't solve that there's hundreds of thousand of lost events coming in - these are from the hubble ring buffer, so something sus is going on.

**Pull request merged**
