### PR TITLE
[v1.14] CI: fix broken BPF complexity tests

### PR DESCRIPTION
**Pull request by lmb**
test/verifier: fix complexity tests not being recompiled

    [ upstream commit 735807fb16806abf13c71c936efbf887b8ee00a5 ]

    TestVerifier is accidentally reusing the result of previous subtest 
    compilations. This means that only the first set of configurations was
    tested.

    Invoke clean for every new compilation. The generated object files are moved
    to the test directory to make them accessible as artifacts from CI.

    Fixes: d3ef5b2ac8 ("test/verifier: Avoid pruning object files before testing
    the next file") Signed-off-by: Lorenz Bauer <lmb@isovalent.com>

test/verifier: improve log output

    [ upstream commit 1e71a19a5db1f411b4e804d3f798e7b454168e13 ]

    Include the command invoked to compile the BPF and the output of the command
    in the test output by default.

    Signed-off-by: Lorenz Bauer <lmb@isovalent.com>

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]
LGTM

**Review by youngnick — APPROVED** [review]

**Comment by lmb** [comment]
@brlbil PTAL!

**Review by viktor-kurchenko — APPROVED** [review]
LGTM.

**Review by ti-mo — APPROVED** [review]

**Pull request merged**
