### PR TITLE
Remove hubble-cli sub-chart 

### LINKED ISSUE #11805: Helm: Deprecate hubble-cli sub-chart
Hubble-cli daemonset will not be released since the hubble binary is built into the cilium-agent container. Nuke the helm sub-chart for hubble-cli and references to it.

### PR DESCRIPTION
**Pull request by seanmwinn**
Remove the hubble-cli sub-chart since the binary was packaged with the cilium-agent container and will not be released

Fixes: #11805

Signed-off-by: Sean Winn <sean@isovalent.com>

### CODE REVIEW

**Comment by michi-covalent** [comment]
this is blocked on https://github.com/cilium/cilium/pull/11784. once it's merged, test/k8sT/hubble.go needs to be updated a bit more. for example, https://github.com/cilium/cilium/blob/7a113cbb5d2fe446ccfae392ddc68d6247623465/test/k8sT/hubble.go#L179 needs to exec into the cilium pod to run the hubble command.

**Review by aanm — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]
love it

**Comment by michi-covalent** [comment]
test-me-please

**Comment by gandro** [comment]
retest-runtime

**Pull request merged**
