### PR TITLE
[WIP] dockerfile: update workdir in cilium dockerfile

### LINKED ISSUE #8456: Change WORKDIR away from /root
The current `Dockerfile` uses `WORKDIR=/root` which prevents running Cilium as non-root.

- [ ] Change the WORKDIR
- [ ] Build a container image with the change `DOCKER_IMAGE_TAG=test make dev-docker-image`
- [ ] Make any additional required changes which may depend on WORKDIR=/root

### PR DESCRIPTION
**Pull request by fristonio**
Fixes #8456

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8746)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by fristonio** [comment]
I think the error is due to a timeout, can someone trigger the CI again?

**Comment by ianvernon** [comment]
The failure appears to be unrelated: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14025/testReport/junit/Suite-k8s-1/10/K8sDatapathConfig_Encapsulation_Check_connectivity_with_transparent_encryption_and_VXLAN_encapsulation/

Will run the CI.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Failure is unrelated (a known test flake); is this ready for review @fristonio ?

**Comment by fristonio** [comment]
Yeah, I think so. I was supposed to see if this break things in the CI testing.

**Comment by jrajahalme** [comment]
@fristonio Could you post the output of `DOCKER_IMAGE_TAG=test make dev-docker-image` (instructed to be run after the change in #8456) in the description?

**Comment by fristonio** [comment]
Here are the complete logs for the docker build
https://pastebin.com/7jfhP2kB

**Pull request closed without merging**
