### PR TITLE
1.2 backports 18 09 17

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:
* #5552
* #5556 - required a few conflicts to be resolved. Required pulling in of 7b542736ab79964e89263705deb31f451f071953 . @tgraf please confirm validity of changes.
* #5579
* #5551
* #5575

Not-backported PRs:

* #5550 - already being taken care of by #5583 
* #5445 - requires pulling in a lot of changes into CI. Discussion is ongoing. 

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5584)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Unit tests got broken in this PR: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/6527

Will triage and fix.

**Comment by ianvernon** [comment]
Got unit tests passing locally, trying tests again.

**Comment by ianvernon** [comment]
test-me-please

**Comment by tgraf** [comment]
Please also pull in https://github.com/cilium/cilium/pull/5551

**Comment by ianvernon** [comment]
@tgraf done

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by ianvernon** [comment]
Had some `bpf.sha` fun, trying again...

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Kafka tests failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/6535/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
When triaging 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/6535 , I noticed that we are still testing with K8s 1.7 in this branch?

```
2018-09-17T21:40:04.523793614Z [2018-09-17 21:40:04,520] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
2018-09-17T21:40:04.523814678Z java.net.UnknownHostException: zook: Name does not resolve
2018-09-17T21:40:04.523817169Z 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
2018-09-17T21:40:04.523819359Z 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
2018-09-17T21:40:04.523821292Z 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
2018-09-17T21:40:04.523823204Z 	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
2018-09-17T21:40:04.523825069Z 	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
2018-09-17T21:40:04.523837131Z 	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
2018-09-17T21:40:04.523839187Z 	at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61)
2018-09-17T21:40:04.523841087Z 	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445)
2018-09-17T21:40:04.52384294Z 	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:380)
2018-09-17T21:40:04.523844884Z 	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:86)
2018-09-17T21:40:04.523846776Z 	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1539)
2018-09-17T21:40:04.523848603Z 	at kafka.server.KafkaServer.createZkClient$1(KafkaServer.scala:345)
2018-09-17T21:40:04.523850383Z 	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:369)
2018-09-17T21:40:04.523852133Z 	at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
2018-09-17T21:40:04.523854534Z 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
2018-09-17T21:40:04.523857585Z 	at kafka.Kafka$.main(Kafka.scala:92)
2018-09-17T21:40:04.523860189Z 	at kafka.Kafka.main(Kafka.scala)
2018-09-17T21:40:04.529448586Z [2018-09-17 21:40:04,529] INFO shutting down (kafka.server.KafkaServer)
2018-09-17T21:40:04.535952531Z [2018-09-17 21:40:04,535] WARN  (kafka.utils.CoreUtils$)
2018-09-17T21:40:04.53597933Z java.lang.NullPointerException
2018-09-17T21:40:04.535983894Z 	at kafka.server.KafkaServer.$anonfun$shutdown$6(KafkaServer.scala:569)
2018-09-17T21:40:04.535987824Z 	at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:85)
2018-09-17T21:40:04.53599061Z 	at kafka.server.KafkaServer.shutdown(KafkaServer.scala:569)
2018-09-17T21:40:04.535992469Z 	at kafka.server.KafkaServer.startup(KafkaServer.scala:326)
2018-09-17T21:40:04.535994208Z 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
2018-09-17T21:40:04.535995944Z 	at kafka.Kafka$.main(Kafka.scala:92)
2018-09-17T21:40:04.535997628Z 	at kafka.Kafka.main(Kafka.scala)
2018-09-17T21:40:04.542221165Z [2018-09-17 21:40:04,542] INFO shut down completed (kafka.server.KafkaServer)
2018-09-17T21:40:04.542957274Z [2018-09-17 21:40:04,542] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
2018-09-17T21:40:04.550162389Z [2018-09-17 21:40:04,550] INFO shutting down (kafka.server.KafkaServer)

```

IMO if this is the only test that fails (this was known to have problems with K8s 1.7) we can merge this.

**Comment by ianvernon** [comment]
Merging, will cut release tomorrow morning PST.

**Pull request merged**
