### PR TITLE
v1.6 backports 2019-07-30

### PR DESCRIPTION
**Pull request by ianvernon**
* #8665 -- init-container: Look for a concrete BPFFS mount in /sys/fs/bpf (@mrostecki)
 * #8687 -- endpoint: fix deadlock when endpoint EventQueue is full (@ianvernon)
 * #8691 -- identity: Reduce churn, fix manager refcounts (@jrajahalme)
 * #8675 -- documentation: clean up upgrade guide and remove references to older versions of Cilium (@ianvernon)
 * #8669 -- documentation: split up contributing guide (@ianvernon)
 * #8664 -- docs: Explain how to enable metrics (@gandro)
 * #8705 -- bpf: fix nodeport over tunnel when vxlan/geneve have lco (@borkmann)
 * #8708 -- few nodeport and hostlb gsg improvements (@borkmann)
 * #8688 -- [bugfix] - mtu for interfaces in host-network (@nyodas)
 * #8717 -- monitor: Add human-readable reason for NO_FIB_LOOKUP drops (@brb)
 * #8693 -- policy: Reject unsupported L7 rules (@joestringer)
 * #8711 -- cilium: encryption, use default route interface if encrypt-interface is not specified. (@jrfastab)
 * #8714 -- cilium: encryption, push tunnel_endpoint IP with encrypt ipcache entries (@jrfastab)
 * #8718 -- lbmap: Do not fail to upsert if ARP neigh add fails (@brb)
 * #8703 -- daemon: Remove old proxymaps on startup, use proxy with legacy fix (@jrajahalme)
 * #8709 -- metrics: fixes constant registering and unregistering of metrics map (@fristonio)
 * #8728 -- pkg/monitor: add endpoint create and delete monitor notifications (@aanm)
 * #8726 -- encryption documentation updates (@jrfastab)

Edit 2019-0-31 (raybejjani)
added
 * PR: 8729 -- IPsec related fixes (@tgraf) -- https://github.com/cilium/cilium/pull/8729
 * PR: 8736 -- agent: Fix wait for ipcache synchroniation when kvstore is disabled (@tgraf) -- https://github.com/cilium/cilium/pull/8736
 * PR: 8730 -- Pr/ray/revert waitfor (@raybejjani) -- https://github.com/cilium/cilium/pull/8730

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 8665 8687 8691 8675 8669 8664 8705 8708 8688 8717 8693 8711 8714 8718 8703 8709 8728 8726; do contrib/backporting/set-labels.py $pr done 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8735)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
Upstream test failure appears legitimate: https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/1418/execution/node/58/log/

**Comment by raybejjani** [comment]
test-missed-k8s

**Comment by raybejjani** [comment]
test-upstream-k8s

**Comment by raybejjani** [comment]
@ianvernon I added the waitfor revert. I included 2 other backports that came in since to keep the apply order.
Added:
 * PR: 8729 -- IPsec related fixes (@tgraf) -- https://github.com/cilium/cilium/pull/8729
 * PR: 8736 -- agent: Fix wait for ipcache synchroniation when kvstore is disabled (@tgraf) -- https://github.com/cilium/cilium/pull/8736
 * PR: 8730 -- Pr/ray/revert waitfor (@raybejjani) -- https://github.com/cilium/cilium/pull/8730

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-missed-k8s

**Comment by raybejjani** [comment]
test-upstream-k8s

**Comment by raybejjani** [comment]
test-docs-please

**Pull request merged**
