### PR TITLE
Add k8s label source in GetPolicyLabels

### PR DESCRIPTION
**Pull request by ashwinp**
Fixes: https://github.com/cilium/cilium/issues/4339
Signed-off-by: ashwinp <ashwin@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4340)

### CODE REVIEW

**Comment by ashwinp** [comment]
test-me-please

**Comment by ashwinp** [comment]
test-me-please

**Comment by ashwinp** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]

**Comment by ashwinp** [comment]
test-me-please

**Comment by ashwinp** [comment]
test-me-please

**Comment by ashwinp** [comment]
test-me-please

**Pull request merged**
