### PR TITLE
Update envoy for Istio 1.0.2

### PR DESCRIPTION
**Pull request by rlenglet**
Upgrade Envoy to Istio 1.0.2's fork of Envoy:
https://github.com/istio/proxy/blob/1.0.2/WORKSPACE#L33-L39
This fork is based on Envoy commit c1cc68dda009452e90d485da22ee9c74c08b328d and fixes a bug with mTLS support.

This PR also cherry-picks commits from https://github.com/cilium/cilium/pull/5499:

- Update BUILD_DEPS
- Increase Memory available to Bazel to 4GB, limit jobs to 4
- Update Bazel to 0.16.1
- Remove deprecated Bazel option '--batch'

Signed-off-by: Romain Lenglet <romain@covalent.io>
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5530)

### CODE REVIEW

**Comment by rlenglet** [comment]
I still need to update the Vagrant box to pick up the updated Bazel cache.
https://jenkins.cilium.io/job/Vagrant-Master-Boxes-Packer-Build/114/

**Comment by rlenglet** [comment]
The packer build succeeded: https://jenkins.cilium.io/job/Vagrant-Master-Boxes-Packer-Build/114/

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Successful CI build: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/6383/

**Review by tgraf — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
