### PR TITLE
fqdn: Delay ipcache upserts until policies have been updated

### PR DESCRIPTION
**Pull request by jrajahalme**
Add a map for newly allocated identities to ipcache.AllocateCIDR
functions that the caller can use to insert the IPs to the IP cache later,
after affected endpoint policy maps have been updated.

Use this new functionality on the DNS proxy and policy update code
paths, that makes sure that new policy map entries are in place before
an IP received from a DNS server or a CIDR included in a policy is placed
in IP cache. This is really straightforward as the logic for waiting was
already in place.

This fix was first developed in the v1.7 branch (#14084), so no 1.7 backport is needed.

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Could not repro the privileged unit test fail on datapath/linux locally, testing again.

**Comment by jrajahalme** [comment]
retest-runtime

**Review by joestringer — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
The entire CI was green, I've just closed and re-open so that Travis could be triggered. If Travis is green we can merge this PR.

**Pull request merged**
