### PR TITLE
WIP test v1.5.0 + svc fix v2

### PR DESCRIPTION
**Pull request by brb**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8058)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by brb** [comment]
No longer relevant, closing.

**Pull request closed without merging**
