### PR TITLE
v1.7 backport 2020 02 11

### PR DESCRIPTION
**Pull request by raybejjani**
v1.7 backports 2020-02-11

 * #10083 -- daemon,cli: Improve kube-proxy-replacement status (@brb)
 * #10086 -- docs: add setup validation howto to kube-proxy-free guide (@borkmann)
 * #10082 -- Add more detailed proxy redirects status to `cilium status` (@joestringer)
 * #10098 -- ipcache: Fix ipcache pod IP update (@joestringer)
 * #10088 -- ServiceMonitor should default to release namespace (@dsexton)
 * #10039 -- test: Remove cilium DS before installing a new one (@brb)
 * #10112 -- [CI] Fix path to print-node-ip script in jenkinsfile (@nebril)
 * #10111 -- improve kernel probe for host reachable services and fix compile warns (@borkmann)
 * #10126 -- Documentation: Switch EKS documentation to default to ENI (@tgraf)
 * #10101 -- install/kubernetes: add option to hold cilium agent after init container (@aanm)
 * #10124 -- bpf, sock: fix post-bind-sock{4,6} not found in ELF file (@borkmann)
 * #10087 -- bpf: Remove bpf_netdev.o from previously used devices (@brb)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10083 10086 10082 10098 10088 10039 10112 10111 10126 10101 10124 10087; do contrib/backporting/set-labels.py $pr done 1.7; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10132)

### CODE REVIEW

**Review by borkmann — APPROVED** [review]

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-missed-k8s

**Comment by raybejjani** [comment]
never-tell-me-the-odds

**Comment by raybejjani** [comment]
test-missed-k8s

**Comment by raybejjani** [comment]
test-me-please

**Pull request merged**
