### PR TITLE
ipcache: Fix metadata access from CIDR allocation

### PR DESCRIPTION
**Pull request by joestringer**
The locking order for metadata -> IPCache should be first grabbing the
metadata lock then the IPCache lock, according to the documentation in
the metadata structure. Correct this lock ordering to conform to the
documented pattern.

This sort of improper lock ordering could theoretically cause a deadlock
if for instance the label injector ran at the same time as this function
is called.

Found by inspection.

Fixes: 40e13ea2a5a9 ("ipcache: Fix race in identity/ipcache release")
Fixes: #20721

### CODE REVIEW

**Review by christarazi — APPROVED** [review]

**Comment by christarazi** [comment]
Marking for v1.11 backport so that we can include it in https://github.com/cilium/cilium/pull/21564.

**Review by aditighag — COMMENTED** [review]
Looking at the commit description, I think the changes seem straight forward. Any chance a unit test can be added/extended in order to prevent such regressions in future? I'm looking at `ipcache/metadata_test.go: TestRemoveLabelsFromIPs`.

**Comment by joestringer** [comment]
Hit https://github.com/cilium/cilium/issues/21120, otherwise CI is passing. Reviews are in, merging.

**Comment by gandro** [comment]
Is there any scenario where `ipc.metadata.get` is actually ever safe?  It returns a reference type (map), but does not hold into the lock. But the returned reference may still be mutated concurrently (e.g. by UpsertLabels).

**Comment by joestringer** [comment]
@gandro you're right, it's not safe.

**Comment by codablock** [comment]
@joestringer shouldn't the same fix be applied to `releaseCIDRIdentities` as well? I came across this fix by analysing https://github.com/cilium/cilium/issues/21596 (I encountered the same deadlock). I'm not sure if applying the metadata lock to releaseCIDRIdentities will also fix #21596, but it looks connected. I'll post a more detailed analysis of the stack traces in the issue later.

**Comment by joestringer** [comment]
@codablock are you looking for https://github.com/cilium/cilium/pull/20721 or something more than that?

The change here relates to the conflict between the ipcache overall lock and the ipcache metadata lock. The ipcache metadata lock is not used during release.

**Comment by codablock** [comment]
@joestringer What I wrote was just a wild guess before I did the detailed analysis of the stack traces, so you can ignore my comment in this PR.

**Comment by joestringer** [comment]
Given this doesn't backport cleanly, I've removed the labels and assigned myself. When the other subsequent fixes are ready I can prepare the backports (or collaborate with Chris on the 1.11 variation)

**Pull request merged**
