### PR TITLE
daemon: fix cilium-agent helper message for disable-cnp-status-updates

### PR DESCRIPTION
**Pull request by aanm**
The helper message seems to print a string in front of it that should
not have been printed.

Fixes: 3aacf41d784e ("add capability to disable CNP NodeStatus updates")
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10414)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
test-docs-please

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-docs-please

**Pull request merged**
