### PR TITLE
v1.13 Backports 2023-12-05

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #29098 (@julianwiedmann)
 * [x] #29182 (@viktor-kurchenko)
 * [x] #29497 (@danehans)
 * [x] #29566 (@christarazi)
 * [x] #29603 (@mhofstetter)

PRs skipped due to conflicts:

 * #29495 (@learnitall)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 29098 29182 29497 29566 29603
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
@viktor-kurchenko @christarazi Some minor conflicts were hit, please check commit notes for details.

**Review by christarazi — APPROVED** [review]
Thanks!

**Review by mhofstetter — APPROVED** [review]

**Comment by nbusseneau** [comment]
/test-backport-1.13

**Review by julianwiedmann — APPROVED** [review]

**Review by chancez — APPROVED** [review]
Metrics changes LGTM.

**Review by viktor-kurchenko — APPROVED** [review]
My commit looks good. Thanks!

**Review by ti-mo — APPROVED** [review]

**Comment by nbusseneau** [comment]
/test-1.19-4.19

**Comment by nbusseneau** [comment]
@julianwiedmann A likely legitimate failure that I suspect was introduced by the backport of #29098 was hit in runtime tests => https://jenkins.cilium.io/job/Cilium-PR-Runtime-kernel-net-next/1315/testReport/junit/(root)/Suite-runtime/RuntimeDatapathPrivilegedUnitTests_Run_Tests/

```
	 [18:32:10] PANIC: ctmap_privileged_test.go:499: CTMapPrivilegedTestSuite.TestOrphanNatGC
	 [18:32:10] 
	 [18:32:10] ... Panic: interface conversion: bpf.MapValue is *tuple.TupleValStub, not *ctmap.CtEntry (PC=0x439EF1)
```

Can you investigate?

**Comment by nbusseneau** [comment]
Thanks @julianwiedmann, I amended the commit, if you'd like to do a quick double peek :)

**Comment by nbusseneau** [comment]
/test-backport-1.13

**Review by julianwiedmann — APPROVED** [review]
:pray:

**Review by danehans — APPROVED** [review]

**Pull request merged**
