### PR TITLE
Update controller tools v0.6.2

### PR DESCRIPTION
**Pull request by jrajahalme**
Update controller-tools to v0.6.2 to gain support for opaque json in k8s custom resources. This is needed for including Envoy resources in the upcoming Cilium Envoy Config CRD.

This update pulled in a Ginkgo update which required some CI updates. These are separated out into a commit of their own to make reviewing easier.

### CODE REVIEW

**Review by christarazi — APPROVED** [review]
Thanks for separating this out and taking care of the controller-tools update. LGTM.

**Comment by aanm** [comment]
@jrajahalme needs rebase

**Review by aanm — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
The new cmdrefs for completion seem a bit unnecessary but I'm assuming that it's all just part of the tool-based autogeneration so sure :+1: LGTM from docs-structure perspective.

The ginkgo changes looked pretty confusing at first glance so I'm assuming the other reviewers took a closer look.

**Review by nbusseneau — APPROVED** [review]
Code changes LGTM.

**Pull request merged**
