### PR TITLE
test: update k8s test versions to 1.16.15, 1.17.12, 1.18.9 and 1.19.2

### PR DESCRIPTION
**Pull request by aanm**
Also update Kubernetes libraries to 1.19.2

Signed-off-by: André Martins <andre@cilium.io>

```release-note
Update Kubernetes libraries to 1.19.2
```

### CODE REVIEW

**Comment by aanm** [comment]
test-missed-k8s

**Review by nebril — APPROVED** [review]

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
