### PR TITLE
Pr/v1.9 backport 2020 10 27

### PR DESCRIPTION
**Pull request by aditighag**
#13747 -- bpf: redirect_neigh signature fix (@borkmann) -- https://github.com/cilium/cilium/pull/13747
 #13724 -- loader: Use netlink lib instead of tc binary to delete filters (@pchaigno) -- https://github.com/cilium/cilium/pull/13724
 #13734 -- Remove high cardinality port-distribution metric from default install (@jedsalazar) -- https://github.com/cilium/cilium/pull/13734
 #13741 -- redirectpolicy: Check lrp type before restoring lrp service (@aditighag) -- https://github.com/cilium/cilium/pull/13741
 #13666 -- VM Support Refinement (@jrajahalme) -- https://github.com/cilium/cilium/pull/13666
 #13671 -- redirectpolicy: Move the feature behind feature flag and remove CCLRP related code (@aditighag) -- https://github.com/cilium/cilium/pull/13671
 #13764 -- docs: update CODEOWNERS review process (@aanm) -- https://github.com/cilium/cilium/pull/13764
 #13755 -- ci: skip tests involving L7 proxy if race detector is enabled (@tklauser) -- https://github.com/cilium/cilium/pull/13755
 #13770 -- .github: Add action to build all BPF permutations (@joestringer) -- https://github.com/cilium/cilium/pull/13770
 #12268 -- docs: document test-only ci command (@nebril) -- https://github.com/cilium/cilium/pull/12268
 #13750 -- hubble: Fix reply state unknown being interpreted as false (@gandro) -- https://github.com/cilium/cilium/pull/13750
 #13779 -- ci: Avoid null pointer exception in non-pr builds (@nebril) -- https://github.com/cilium/cilium/pull/13779
 #13781 -- docs: Clarify bumping the runtime images step (@christarazi) -- https://github.com/cilium/cilium/pull/13781
 #13549 -- helm: Add check for prometheus service monitoring CRDs (@sayboras) -- https://github.com/cilium/cilium/pull/13549
 #13776 -- hubble/relay: flush old flows when the buffer drain timeout is reached (@Rolinh) -- https://github.com/cilium/cilium/pull/13776

When you have backported the above commits, you can update the PR labels via this command:

```upstream-prs
$ for pr in 13747 13724 13734 13741 13666 13671 13764 13755 13770 12268 13750 13779 13781 13549 13776; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by aditighag** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]
My PR looks good :+1:

**Review by joestringer — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
looks good for my commit :100:

**Review by christarazi — APPROVED** [review]
LGTM for my commits

**Review by tklauser — APPROVED** [review]
My changes look good, thanks!

**Review by gandro — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Review by ti-mo — APPROVED** [review]

**Comment by jrajahalme** [comment]
checkpatch seems unhappy with our backport commit style:
```
ERROR:GIT_COMMIT_ID: Please use git commit description style 'commit <12+ chars of sha1> ("<title line>")' - ie: 'commit aa4031c0c08c ("bpf: fix up redirect_neigh helper signature wrt nexthop")'
#6: 
[ upstream commit aa4031c0c08cd0f7b3a8faba315712b541d930e2 ]
```
No other errors in there so merging as-is.

**Pull request merged**
