### PR TITLE
v1.7 backports 2020-04-02

### PR DESCRIPTION
**Pull request by pchaigno**
* #10717 -- test: Fix kubectl log retrieval for badLogMessages (@pchaigno)
 * #10727 -- pkg/k8s: fix all structural issues with CNP validation (@aanm)
   * Had to change call to `k8s.CiliumClient().[...].Do()` to not take argument for k8s <1.18.
   * Dropped the `CODEOWNERS` change from ff863a8f2.
 * #10782 -- Drop ephemeral port range check for NodePort from datapath (@brb)
   * Had to run and commit `make -C daemon apply-bindata`.
   * Fixed minor conflict in `Documentation/gettingstarted/kubeproxy-free.rst` (9b8f7fcbc).
   * Fixed two minor conflicts in `install/kubernetes/cilium/values.yaml` and `install/kubernetes/quick-install.yaml` (a064bf56b).

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10717 10727 10782; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by aanm** [comment]
never-tell-me-the-odds

**Review by aanm — APPROVED** [review]
My commits LGTM

**Review by brb — APPROVED** [review]
My changes LGTM, thanks

**Comment by joestringer** [comment]
Legitimate failure by the looks:
```
daemon/cmd/nodeport_linux_test.go:83:9: undefined: checkNodePortAndEphemeralPortRanges
	 make: *** [tests-privileged] Error 1
```

**Comment by brb** [comment]
Re `undefined: checkNodePortAndEphemeralPortRanges`: the problem is that the failing test is in the `daemon/cmd` dir, while the function is in the `daemon/`. Perhaps we should move the tests from `daemon/cmd` to `daemon/`, or maybe the function public. I'd vote for the former.

**Comment by pchaigno** [comment]
Thanks @brb! I went with the former and moved `nodeport_linux_test.go` to `daemon/`.

**Comment by pchaigno** [comment]
never-tell-me-the-odds

**Comment by joestringer** [comment]
@pchaigno I don't think that github registered the new version.

**Comment by pchaigno** [comment]
@joestringer Uh, you're right. Nonetheless:
```
$ git push -f origin pr/v1.7-backport-2020-04-02 
Everything up-to-date
```
:thinking:

**Comment by pchaigno** [comment]
never-tell-me-the-odds

**Comment by pchaigno** [comment]
test-upstream-k8s

**Comment by pchaigno** [comment]
test-missed-k8s

**Comment by pchaigno** [comment]
restart-ginkgo

**Comment by joestringer** [comment]
test-with-kernel

**Comment by joestringer** [comment]
(test-with-kernel shows no pipeline steps, not sure if that's just because the target is unsupported on v1.7 branch.. https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/140/flowGraphTable/)

**Comment by joestringer** [comment]
OK, 1.7 just doesn't support that target. I'll merge this now.

**Pull request merged**
