### PR TITLE
Remove bpf_lb.c and friends

### PR DESCRIPTION
**Pull request by brb**
This PR removes the `--lb` feature support which was deprecated in `v1.6`.

In addition, we have removed the `networking.k8s.io/v1beta1.Ingress` support, as it depended on the `--lb` and was broken. The support might come back after we have fixed the ExternalIP service implementation.

Reviewable per commit.

```release-notes
Support for the `--lb` feature was removed
Support for Kubernetes Single Service Ingress was removed
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9199)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-docs-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failed due to the NodePort BPF flake.

**Comment by brb** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Pull request merged**
