### PR TITLE
Adds flag to clean up cilium state before startup

### PR DESCRIPTION
**Pull request by abhide15**
Signed-off-by: Amey Bhide <amey@covalent.io>

### CODE REVIEW

**Comment by abhide15** [comment]
@eloycoto @joestringer New PR for https://github.com/cilium/cilium/pull/3680; since ginkgo test gate wasn't getting triggered

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
@eloycoto this PR still isn't getting picked up by Jenkins.

**Comment by abhide15** [comment]
@eloycoto any idea why CI isn't picking this up?

**Comment by joestringer** [comment]
@abhide15 it seems to have eventually run, but I suspect that this is a CI flake. I'll attempt to retrigger.

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/2692/

**Comment by joestringer** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by ianvernon** [comment]
@abhide15 @joestringer can this be merged?

**Comment by joestringer** [comment]
@ianvernon yes, it was signed off by several people in the previous PR #3680, we were just trying to get the CI to run.

**Comment by raybejjani** [comment]
backport in https://github.com/cilium/cilium/pull/3953

**Pull request merged**
