### PR TITLE
Refactored, renamed and small misc changes in GH workflows

### PR DESCRIPTION
**Pull request by aanm**
See per commit basis

@pchaigno @nbusseneau I see a lot of changes from v1.10 to master branch `git diff origin/v1.10 origin/master -- .github/workflows` I assume all of the current changes in the master branch are currently in the process of being backported to v1.10 and so it is safe to backport this PR as well?

### CODE REVIEW

**Comment by pchaigno** [comment]
> I assume all of the current changes in the master branch are currently in the process of being backported to v1.10 and so it is safe to backport this PR as well?

All of my PRs for `.github` should be marked for backport (some are currently being backported).

**Review by pchaigno — COMMENTED** [review]
What's the logic for naming `conformance-` vs. `tests-`?

**Comment by aanm** [comment]
> What's the logic for naming `conformance-` vs. `tests-`?

I think I tried to name `tests-` for tests that were created in this repository and `conformance-` for tests created outside this repository.

**Comment by pchaigno** [comment]
> `conformance-` for tests created outside this repository.

I'm not sure I understand. By outside this repository, do you mean tests whose infra. logic is maintained in cilium-cli?

**Comment by aanm** [comment]
> > `conformance-` for tests created outside this repository.
> 
> I'm not sure I understand. By outside this repository, do you mean tests whose infra. logic is maintained in cilium-cli?

correct

**Comment by pchaigno** [comment]
I'm fine with those names, but `conformance-k8s-network-policies.yaml` and `conformance-kind.yaml ` are not related to cilium-cli AFAIK.

**Comment by aanm** [comment]
> I'm fine with those names, but `conformance-k8s-network-policies.yaml` and `conformance-kind.yaml ` are not related to cilium-cli AFAIK.

Correct but they maintained "externally" to cilium/cilium repository.

**Comment by pchaigno** [comment]
Ok. What about `external-`?

**Comment by aanm** [comment]
> Ok. What about `external-`?

But the are named as `Conformance` inside :cry:

**Comment by pchaigno** [comment]
Not all of them, and we can always rename that if we don't like it.

**Comment by nbusseneau** [comment]
Re: renaming of `conformance` workflows: I'm all for it, see my comment on the initial PR: https://github.com/cilium/cilium/pull/15144#discussion_r589566374

**Review by nbusseneau — COMMENTED** [review]
LGTM, just need to agree on the names I guess :D

**Review by pchaigno — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Pull request merged**
