### PR TITLE
Fix ipvlan helm template and gsg

### PR DESCRIPTION
**Pull request by brb**
This PR fixes the helm template for ipvlan and updates the ipvlan getting start guide accordingly.

Please review per commit.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8905)

### CODE REVIEW

**Comment by brb** [comment]
test-docs-please

**Comment by brb** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Comment by tgraf** [comment]
In general, we are trying to no longer use terms like "master" or "slave" but use more neutral terminology. I agree though that it can cause confusion as many people are used to the term master in the context of IPVLAN.

**Comment by ianvernon** [comment]
@brb needs rebase

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Pull request merged**
