### PR TITLE
k8s: Optimize CRD controller to avoid using Table

### PR DESCRIPTION
**Pull request by christarazi**
This commit further optimizes the CRD controller by avoiding the
unnecessary use of metav1.Table type.

Previously, it was thought that we needed to use the Table type as
that's what `kubectl get crds` returns them as. However, K8s supports
retrieving the PartialObjectMetadataList directly, which is what we were
converting to by hand already under-the-hood from the Table contents.

Fixes: 3a803bfcc4 ("pks/k8s: use slimmer objects when waiting for CRDs")
Fixes: https://github.com/cilium/cilium/pull/13418

### CODE REVIEW

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
retest-runtime

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
retest-net-next

**Comment by aanm** [comment]
@christarazi it doesn't seem to work for k8s 1.12:
```
020-11-02T20:51:45.608149109Z level=warning msg="Ignoring invalid k8s v1beta1 CustomResourceDefinition" obj="&PartialObjectMetadata{ObjectMeta:ObjectMeta{Name:ciliumlocalredirectpolicies.cilium.io,Namespace:,UID:8792653f-1d4c-11eb-85f4-080027bc8edc,ResourceVersion:1284,Labels:map[string]string{io.cilium.k8s.crd.schema.version: 1.22.3,},Annotations:map[string]string{},},}" subsys=k8s
2020-11-02T20:51:45.608169675Z level=warning msg="Ignoring invalid k8s v1beta1 CustomResourceDefinition" obj="&PartialObjectMetadata{ObjectMeta:ObjectMeta{Name:ciliumnodes.cilium.io,Namespace:,UID:879280e5-1d4c-11eb-85f4-080027bc8edc,ResourceVersion:1285,Labels:map[string]string{io.cilium.k8s.crd.schema.version: 1.22.3,},Annotations:map[string]string{},},}" subsys=k8s
2020-11-02T20:51:45.608173582Z level=warning msg="Ignoring invalid k8s v1beta1 CustomResourceDefinition" obj="&PartialObjectMetadata{ObjectMeta:ObjectMeta{Name:ciliumexternalworkloads.cilium.io,Namespace:,UID:87c9daed-1d4c-11eb-85f4-080027bc8edc,ResourceVersion:1288,Labels:map[string]string{io.cilium.k8s.crd.schema.version: 1.22.3,},Annotations:map[string]string{},},}" subsys=k8s
```

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
retest-gke

**Comment by christarazi** [comment]
retest-4.9

**Review by aanm — APPROVED** [review]
Changes LGTM. The GKE failures seem suspicious.

**Comment by aanm** [comment]
retest-gke

**Comment by christarazi** [comment]
Looks like the GKE failures are expected on master and https://github.com/cilium/cilium/pull/13899 fixes it by quarantining it. Rebased on top of that PR and only rerunning the GKE test because all the CI tests have passed.

**Comment by christarazi** [comment]
retest-gke

**Review by fristonio — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
