### PR TITLE
update golang to 1.11.1

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

```release-note
Update Golang version to 1.11.1
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6088)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-k8s-upstream

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
k8s upstream tests failed but it's already being fixed here https://github.com/cilium/cilium/pull/6114

**Review by eloycoto — APPROVED** [review]

**Pull request merged**
