### PR TITLE
images/runtime: update ubuntu base image

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]
i guess it's ok `@sha256` part is missing?

**Comment by aanm** [comment]
@michi-covalent I was just following the steps here https://docs.cilium.io/en/latest/contributing/development/images/#update-cilium-builder-and-cilium-runtime-images

**Comment by aanm** [comment]
test-me-please

**Review by michi-covalent — APPROVED** [review]

**Comment by aanm** [comment]
test-gke

**Comment by aanm** [comment]
test-1.20-4.18

**Comment by aanm** [comment]
test-1.20-4.19

**Review by joestringer — APPROVED** [review]

**Comment by tklauser** [comment]
test-1.20-4.19

**Review by tklauser — APPROVED** [review]

**Comment by tklauser** [comment]
test-1.20-4.19

**Pull request merged**
