### PR TITLE
V0.12 backports

### PR DESCRIPTION
**Pull request by tgraf**

### CODE REVIEW

**Comment by joestringer** [comment]
FYI there's another test flake in l4 test, #1902 which causes failures in about 10% of unit test runs. I've almost got a fix for that prepared, and will update this PR with the link to the PR for the fix to that.

**Comment by tgraf** [comment]
> FYI there's another test flake in l4 test, #1902 which causes failures in about 10% of unit test runs. I've almost got a fix for that prepared, and will update this PR with the link to the PR for the fix to that.

@joestringer 
Was this introduced by one of the backports fixes?

```
21:46:26 ==> cilium-master-build-PR-1904-1: ... Unified diff:
21:46:26 ==> cilium-master-build-PR-1904-1: --- expected
21:46:26 ==> cilium-master-build-PR-1904-1: +++ obtained
21:46:26 ==> cilium-master-build-PR-1904-1: @@ -1,4 +1,8 @@
21:46:26 ==> cilium-master-build-PR-1904-1:  [{
21:46:26 ==> cilium-master-build-PR-1904-1: -  "port": 8080,
21:46:26 ==> cilium-master-build-PR-1904-1: -  "protocol": "TCP"
21:46:26 ==> cilium-master-build-PR-1904-1: +  "Port": 8080,
21:46:26 ==> cilium-master-build-PR-1904-1: +  "Protocol": "TCP",
21:46:26 ==> cilium-master-build-PR-1904-1: +  "L7Parser": "",
21:46:26 ==> cilium-master-build-PR-1904-1: +  "L7RedirectPort": 0,
21:46:26 ==> cilium-master-build-PR-1904-1: +  "L7RulesPerEp": {},
21:46:26 ==> cilium-master-build-PR-1904-1: +  "Ingress": false
21:46:26 ==> cilium-master-build-PR-1904-1:  }]
21:46:26 ==> cilium-master-build-PR-1904-1: 
```

**Comment by joestringer** [comment]
@tgraf weird, I think that failure is introduced by `l4: Fix JSON marshalling of models.L4Policy`, but should be fixed by  `l4: Fix unit test flake`.

I've sent out the PR for the other fix: #1906

**Comment by joestringer** [comment]
Looks like it's commit 060efbd9643f ("l4: Fix JSON marshalling of models.L4Policy") introducing the failure.

**Comment by joestringer** [comment]
@tgraf If you backport commit 0e06543cb077 ("l4: Improve L4Filter json formatting."), that issue should go away.

**Review by aalemayhu — APPROVED** [review]

**Pull request merged**
