### PR TITLE
Refactor /endpoint/{id}/config for API 1.0 stability

### PR DESCRIPTION
**Pull request by raybejjani**
*Note: This PR is a diff to https://github.com/cilium/cilium/pull/3388. Please don't merge.
See https://github.com/cilium/cilium/issues/3280 for background

**Summary of changes**:
- Refactor the endpoint config to be declarative.
- Mark PATCH /endpoint deprecated to discourage use

**How to test (optional)**:
all tests should pass.

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-pleae

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request closed without merging**
