### PR TITLE
bpf: l3: clean up check for BPF Host Routing

### PR DESCRIPTION
**Pull request by julianwiedmann**
Re-defining the FORCE_LOCAL_POLICY_EVAL_AT_SOURCE macro is unnecessarily complicated. Instead just add the actual check + comment at the relevant code section.

### CODE REVIEW

**Review by YutaroHayakawa — APPROVED** [review]

**Comment by julianwiedmann** [comment]
(there's a whole bunch of BPF tests that are misbehaving - they are enabling BPF Host Routing, but were expecting us to still take the `bpf_redirect()` path. Looking into it atm)

**Pull request merged**
