### PR TITLE
daemon: always re-add CNP when receiving an update from Kubernetes

### PR DESCRIPTION
**Pull request by aanm**
Fixes: 1fd4f57c1ab3 ("adding CRD cilium network policy policy status")
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5024)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
@aanm what is the need for this fix?

**Comment by ianvernon** [comment]
Upstream tests failed due to not being able to get a required package:
```
16:05:55     k8s1-1.10: Failed to fetch http://apt.kubernetes.io/pool/kubernetes-cni_0.6.0-00_amd64_43460dd3c97073851f84b32f5e8eebdc84fadedb5d5a00d1fc6872f30a4dd42c.deb  Could not connect to apt.kubernetes.io:80 (23.236.58.218), connection timed out
16:05:55     k8s1-1.10: E
16:05:55     k8s1-1.10: : 
16:05:55     k8s1-1.10: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by ianvernon** [comment]
test-upstream-k8s

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
