### PR TITLE
test: Fix docker compose in precheck

### PR DESCRIPTION
**Pull request by nebril**
fixes: #15169

### CODE REVIEW

**Comment by nebril** [comment]
test-1.19-4.9

**Comment by nebril** [comment]
test-1.19-4.9

**Comment by nebril** [comment]
test-backport-1.9

**Comment by nebril** [comment]
test-backport-1.9

**Comment by nebril** [comment]
test-backport-1.9

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
1.17 fail is expected, will be fixed in next 1.9 backport round.

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
travis failure seems to be caused by docker rate limiting, not connected to the PR

**Comment by nebril** [comment]
test-gke

**Comment by pchaigno** [comment]
test-gke

**Review by pchaigno — APPROVED** [review]

**Pull request merged**
