### PR TITLE
envoy: Include Cilium NetworkPolicies in Envoy Config Dump

### PR DESCRIPTION
**Pull request by mhofstetter**
This commit updates the Cilium Proxy docker image to the latest version (`797bea843de17da8f8a096747c4691405b540aa8`).

This provides the enhancement that Cilium NetworkPolicies are now part of Envoys Config Dump and therefore part of Ciliums SysDump (cilium/proxy#184)

```release-note
Cilium L7 Proxy: Envoy config dump contains Cilium network policies
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
LGTM :heavy_check_mark:.

For other reviewer, the digest is coming from https://github.com/cilium/proxy/actions/runs/4757816249/jobs/8455099808

**Comment by mhofstetter** [comment]
marking this as `ready-to-merge` - with the main intention to bring this into `v1.14.0-snapshot.2`

@sayboras already covered all SIGS (vendor & build)

**Comment by sayboras** [comment]
Merged and thanks :heavy_check_mark:

**Pull request merged**
