### PR TITLE
controller: Skip StopFunc when stopping controller for update

### PR DESCRIPTION
**Pull request by rlenglet**
Controllers can specify a `StopFunc`, i.e. a function that is called when the controller is stopped.
Currently, only a few controllers specify a `StopFunc`. Especially, that's the case of the `sync-IPv4-identity-mapping (<id>)` and `sync-IPv6-identity-mapping (<id>)` controllers. Those controllers sync the IP addresses of an endpoint with its identity in the ipcache when that identity changes. In those controllers, the `StopFunc` deletes the association between the IP address and the identity.

In the current controller implementation, the `StopFunc` is erroneously called on controller update, not only when stopping a controller. This has undesirable side-effects.

In the case of the `sync-*-identity-mapping (*)` controllers, this can lead to the `StopFunc` being executed after the new controller has executed, which results in the deletion of the IP-to-identity mappings for an endpoint in the ipcache. This results in all the traffic to that endpoint being dropped at egress.

This PR skips executing the `StopFunc` for a controller when it's updated. The `StopFunc` is now only called when the controller is removed.

Signed-off-by: Romain Lenglet <romain@covalent.io>

### CODE REVIEW

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Successful CI build: https://jenkins.cilium.io/view/PR/job/Cilium-PR-Ginkgo-Tests-Validated/3169/

**Review by joestringer — APPROVED** [review]
Would you mind outlining the motivation / impact in the patch commit message (and probably PR)? It might be useful to know retrospectively which cases this could affect, when referring to commits later on.

**Comment by rlenglet** [comment]
@joestringer Updated the PR's description.

**Comment by joestringer** [comment]
Based on your updated description, I wonder if this might improve #3992.

**Comment by rlenglet** [comment]
Maybe. The symptoms were very similar. In my case, I had the full logs, and I saw an explicit deletion of mapping from a controller just after identity udpate, so it was pretty clear.

**Comment by rlenglet** [comment]
However, the particular bug with the sync controllers only manifests itself only on endpoint identity update. And I don't think we exercise that in the CI in master right now.

**Pull request merged**
