### PR TITLE
v1.7 backports 2020-08-27

### PR DESCRIPTION
**Pull request by jrfastab**
* #12901 -- docs/metrics: Correct label typos in metrics.rst (@sayboras)
 * #12917 -- datapath: Pull skb data in to-netdev path (@brb)
 * #12947 -- pkg/kvstore: add gRPC keep alives for etcd connectivity (@aanm)
 * #12894 -- fix: node-init restartPods should use docker if /etc/crictl.yaml not found (@UnwashedMeme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12901 12917 12947 12894; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by jrfastab** [comment]
@tgraf can you check this I had to do it by hand, https://github.com/cilium/cilium/pull/12992/commits/e4a652dda9d1bd4a72ff69648bce215f2a439ca2

**Comment by christarazi** [comment]
> @tgraf can you check this I had to do it by hand, [e4a652d](https://github.com/cilium/cilium/commit/e4a652dda9d1bd4a72ff69648bce215f2a439ca2)
> 
> A bit more specific I kept this chunk above where the new config option parsing is handeld,
> 
> ```
>        if v, ok := e.opts[optionEnabledHeartbeat]; ok {
>                 if opts == nil {
>                         opts = &ExtraOptions{}
>                 }
>                 opts.HeartbeatHealthCheck = strings.ToLower(v.value) == "true"
> ```
> 
> That part doesn't exist in 1.8 But looks like removing as the patch wanted might not be too smart?

@jrfastab We do want to keep the hunk around enabling the heartbeat. You're correct in that it doesn't exist in 1.8; that's intentional as the heartbeat is only in 1.7.

**Comment by jrfastab** [comment]
@christarazi that is how I read the code as well. Does the patch look good to you? Extra set of eyes familiar with this bit of code would be appreciated.

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
test-backport-1.7

**Review by christarazi — APPROVED** [review]
LGTM. Ginkgo test failed around some error re: `revalidate_data_pull`

**Comment by jrfastab** [comment]
test-backport-1.7

**Comment by jrfastab** [comment]
test-backport-1.7

**Review by sayboras — APPROVED** [review]
LGTM for my change

**Comment by joestringer** [comment]
Regular Cilium-Ginkgo-Tests failed `GuestBook Examples checks policy example` test which suddenly today sprung up almost 40 separate failures across all versions, which seems like some kind of timebomb we stumbled on. I have filed https://github.com/cilium/cilium/issues/12994 and will disregard for the purposes of evaluating this PR for inclusion into the v1.7 tree.

**Comment by joestringer** [comment]
Of the three tests that failed in the k8s run:

1.    Suite-k8s-1.12.K8sPolicyTest Basic Test Redirects traffic to proxy when no policy is applied with proxy-visibility annotation Tests proxy visibility interactions with policy lifecycle operations
1.    Suite-k8s-1.13.K8sFQDNTest Restart Cilium validate that FQDN is still working
1.    Suite-k8s-1.13.K8sFQDNTest Validate that multiple specs are working correctly

(1) Only occurred in k8s 1.13 run (not any other run) which implies flake, does not appear to have been observed before but seems unrelated to the changes in this PR. Filed https://github.com/cilium/cilium/issues/12995 .
(2) Suggests infrastructure issue
(3) Failure in before-all is likely caused by (2) failing

**Comment by joestringer** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
This time, k8s only failed on `K8sFQDNTest Restart Cilium validate that FQDN is still working` which failed with `Expected connectivity to work consistently`, a string I can't find in the Cilium issues. But apparently we are quarantining this test on master, so I don't see how v1.7 could be any more stable for this test.

I also note that it didn't fail the previous time so it's clearly a flake.
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3457/testReport/junit/Suite-k8s-1/14/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/

**Comment by joestringer** [comment]
Ignoring failures to merge.

**Pull request merged**
