### PR TITLE
[v1.10] images: Bump Hubble CLI to v0.11.1

### PR DESCRIPTION
**Pull request by gandro**
This bumps the Hubble CLI to the latest release, v0.11.1. By upgrading the Hubble CLI to the latest release, we ensure that the binary is built using the most recent version of Golang while preserving compatibility to the previous version using the new `HUBBLE_COMPAT` environment variable.

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]

**Review by ldelossa — APPROVED** [review]

**Comment by michi-covalent** [comment]
will rebase after https://github.com/cilium/cilium/pull/23220 gets backported cc @ldelossa

**Comment by joestringer** [comment]
@michi-covalent @ldelossa I've backported it here: https://github.com/cilium/cilium/pull/23316

**Comment by michi-covalent** [comment]
/test-backport-1.10

**Comment by joestringer** [comment]
Second failure was also #22019. It's a bit odd to see that fail in two jobs, but many of the other jobs passed and this PR is clearly unrelated. Merging.

**Pull request merged**
