### PR TITLE
envoy: Use patched image

### PR DESCRIPTION
**Pull request by jrajahalme**
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

```release-note
Envoy is updated to version 1.11.1
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8889)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
never-tell-me-the-odds

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
never-tell-me-the-odds

**Comment by jrajahalme** [comment]
"upgrade and downgrade" test failed due to health check failing on v1.5, so not related to this PR, retesting.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-missed-k8s

**Comment by jrajahalme** [comment]
test-upstream-k8s

**Comment by tgraf** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
test-upstream-k8s

**Review by nebril — APPROVED** [review]

**Comment by ianvernon** [comment]
Upstream K8s tests failed: https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/1454/

GitHub checkout problem.

**Comment by ianvernon** [comment]
test-upstream-k8s

**Pull request merged**
