### PR TITLE
v1.8 backports 2021-01-19

### PR DESCRIPTION
**Pull request by vadorovsky**
* #14565 -- clustermesh: Ignore symlink files on fsnotify events (@tgraf)
 * #14516 -- Fix CIDR coalescing issue in ExceptCIDR rule expressions (@jrajahalme)
 * #14591 -- pkg/node: fix concurrent access of entry node (@aanm)
 * #14524 -- jenkinsfile: Allow enabling host firewall in k8s-all CI (@pchaigno)
 * #14623 -- pkg/kvstore: fix panic when closing etcd connections on error (@aanm)
 * #14645 -- cilium-cni: Fix error handling for bad netns (@joestringer)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14565 14516 14591 14524 14623 14645; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by mrostecki** [comment]
never-tell-me-the-odds

**Review by pchaigno — APPROVED** [review]
My changes LGTM!

**Comment by pchaigno** [comment]
test-backport-1.8

**Review by aanm — APPROVED** [review]
My changes look good to me. Thanks!

**Comment by aanm** [comment]
test-upstream-k8s

**Review by joestringer — APPROVED** [review]

**Comment by mrostecki** [comment]
test-missed-k8s

**Review by rolinh — APPROVED** [review]

**Comment by joestringer** [comment]
@Rolinh this is a reminder to run the "labels update" command from backports PRs when you merge them. I've done it this time (hopefully one day we'll just automate this step...).

**Pull request merged**
