### PR TITLE
Update Go to 1.16.5

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-runtime

**Comment by tklauser** [comment]
test-1.19-5.4

**Comment by tklauser** [comment]
test-1.20-4.19

**Review by christarazi — APPROVED** [review]
LGTM. A rebase is needed

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-1.21-4.9

**Comment by tklauser** [comment]
test-1.21-4.9

**Review by pchaigno — APPROVED** [review]

**Comment by tklauser** [comment]
test-1.21-4.9

**Review by michi-covalent — APPROVED** [review]

**Comment by tklauser** [comment]
Received enough reviews and all required tests passed. Marking as ready to merge.

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
`k8s-1.21-kernel-4.9` CI job was for some reason triggered by mistake by my previous comment and failed due to the comment not matching the trigger phrase: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/676/.

That job previously passed on this PR, see https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/657/ so this PR is still ready to be merged.

**Pull request merged**
