### PR TITLE
vendor: update github.com/google/gops to v0.3.10

### PR DESCRIPTION
**Pull request by tklauser**
This pulls in additional fixes for working around #11455
and will also get rid of two transitive dependencies:
github.com/kardianos/osext and github.com/shirou/w32

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by rolinh — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
retest-runtime

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
The runtime test failed to be provisioned but going to merge this since https://github.com/cilium/cilium/pull/12287 will retest everything again

**Comment by jdef** [comment]
any chance of the gops bump being backported to 1.7.x or 1.8.x?

https://github.com/google/gops/pull/97 is missing from gops 0.3.6 and is generating TONS of "use of a closed connection" noise in our logs.

**Comment by tklauser** [comment]
> any chance of the gops bump being backported to 1.7.x or 1.8.x?
> 
> [google/gops#97](https://github.com/google/gops/pull/97) is missing from gops 0.3.6 and is generating TONS of "use of a closed connection" noise in our logs.

@jdef this PR was backported to `v1.8` in #13128 and will be included in the next 1.8.x release.

**Pull request merged**
