### PR TITLE
bpf: Remove fib_redirect's BPF_FIB_LOOKUP_DIRECT

### LINKED ISSUE #24252: Cilium not respecting routes in different routing tables
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Pod-to-pod communication is not working in case when routes are located in different routing tables

working case:
```
ip route add 10.10.10.1/32 via 192.168.100.1 dev enp1s0
```

non-working case:
```
ip rule add to 10.10.10.0/24 lookup 1490
ip route add 10.10.10.1/32 via 192.168.100.1 dev enp1s0 table 1490
```

### Cilium Version

1.11.14

### Kernel Version

5.15.0-25-generic

### Kubernetes Version

v1.23.15

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by borkmann**
See commit desc.

Fixes: #24252

### CODE REVIEW

**Comment by kvaps** [comment]
I tesed this on `v1.11.14`, it works fine:

```patch
diff --git a/bpf/lib/fib.h b/bpf/lib/fib.h
index f24d6c7a47..24f78beb34 100644
--- a/bpf/lib/fib.h
+++ b/bpf/lib/fib.h
@@ -31,8 +31,7 @@ redirect_direct_v6(struct __ctx_buff *ctx __maybe_unused,
 	ipv6_addr_copy((union v6addr *)&fib_params.ipv6_dst,
 		       (union v6addr *)&ip6->daddr);

-	ret = fib_lookup(ctx, &fib_params, sizeof(fib_params),
-			 BPF_FIB_LOOKUP_DIRECT);
+	ret = fib_lookup(ctx, &fib_params, sizeof(fib_params), 0);
 	switch (ret) {
 	case BPF_FIB_LKUP_RET_SUCCESS:
 		break;
```

@borkmann thank you a lot 🙏

**Comment by borkmann** [comment]
> @borkmann thank you a lot 🙏

Thanks a lot for testing! Then yeah we should do the 0 flag by default and revisit at a later point in time to make an optional opt-in for optimizing via BPF_FIB_LOOKUP_DIRECT. But to keep default most compatible as possible.

**Comment by borkmann** [comment]
Looks like quay.io was ratelimiting?
```
level=fatal msg="generating doc: creating SPDX document: generating SPDX package from image ref quay.io/cilium/hubble-relay-ci:bbe60c2d176b31afca18aeceb48932580349901a-unstripped: while downloading images to archive: downloading archive of image: writing image to disk: unable to calculate manifest: GET https://cdn03.quay.io/sha256/16/165053af1eb6099b8e6f8f779c2e22785da63d093adbbf18a76a7e0e2af7a11d?X-Amz-Algorithm=REDACTED&X-Amz-Credential=REDACTED&X-Amz-Date=REDACTED&X-Amz-Expires=REDACTED&X-Amz-Signature=REDACTED&X-Amz-SignedHeaders=REDACTED&cf_expiry=REDACTED&cf_sign=REDACTED&region=REDACTED: unexpected status code 503 Service Unavailable"
```
Retrigger tests..

**Review by julianwiedmann — APPROVED** [review]

**Pull request merged**
