### PR TITLE
Add Powered by eBPF Logo.

### PR DESCRIPTION
**Pull request by sknrao**
This patch adds Powered-By-eBPF Logo to the Readme.rst.

This is based on the feedback received on PR #33982. Thanks to Quentin Monnet for the suggestions and logos. This patch is to support eBPF Logo trademark application by eBPF Foundation.

```release-note
README.rst: Add "Powered-by-eBPF" and CNCF logos to README, link to ebpf.io and cncf.io
```

### CODE REVIEW

**Comment by bimmlerd** [comment]
I think a cc @qmonnet is warranted, given he has looked into this in detail.

**Review by qmonnet — APPROVED** [review]
Thanks David!

The change looks good to me, thanks a lot Sridhar for this PR :+1: 

image

image

**Comment by qmonnet** [comment]
BPF checks (checkpatch) complains because the author email is different than the one used in the `sign-off-by` tag, this is fine to ignore.

**Comment by bimmlerd** [comment]
Unfortunately `ci-ginkgo` will not pass until you rebase onto latest `main`, due to https://github.com/cilium/cilium/pull/35193.

**Review by bimmlerd — APPROVED** [review]

**Comment by sknrao** [comment]
@bimmlerd should I do "update branch" (update with merge commit?)

**Comment by joestringer** [comment]
@sknrao Better to do "Update with rebase" instead.

**Pull request merged**
