### PR TITLE
bpf: fast veth redirect for per-endpoint routes

### PR DESCRIPTION
**Pull request by borkmann**
See commit desc.

- Next up also tunneling support.
- wireguard: https://docs.cilium.io/en/stable/gettingstarted/encryption-wireguard/#limitations

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by m-yosefpor** [comment]
@borkmann any updates on this?

**Comment by borkmann** [comment]
Closing as superseded by PR: https://github.com/cilium/cilium/pull/22006

**Pull request closed without merging**
