### PR TITLE
jenkins: switch to ad-hoc GKE cluster creation/deletion

### PR DESCRIPTION
**Pull request by nbusseneau**
The general idea is to remove the need for our permanent pool of GKE clusters + management cluster (that manages the pool via Config Connector).

Instead, we switch to ad-hoc clusters as we do on CI 3.0. This should:

- Remove the upper limit on the number of concurrent Jenkins GKE jobs.
- Remove the need for permanent clusters (reduce CI costs).
- Have no effect on the setup time required before the tests actually start running on GKE clusters.
- Improve control over GKE features (e.g. `DenyServiceExternalIPs` admission controller) that cannot be controlled via CNRM / Config Connector.

### CODE REVIEW

**Comment by nbusseneau** [comment]
Note to reviewers: since the GKE pipeline is currently disabled so as not to be triggered on `/test`, changes here were tested in an exact copy of the pipeline at: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE-nicolas/

See https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE-nicolas/3/ for a valid run.

**Review by gandro — APPROVED** [review]
Not part of the CI team, but looks good to me nonetheless.

**Review by sayboras — APPROVED** [review]
:ship:

**Review by joestringer — APPROVED** [review]
I glanced through the bash, `set -e` is present in the new script and it seems like if it fails, the outer code will call into the `release-cluster.sh`. :+1:

**Comment by nbusseneau** [comment]
> How is that possible if we are going from a pool of pre-created clusters to creating the clusters as part of the CI job?

The clusters in the pool are already created but were actually scaled down to 0 nodes when not in use, then scaled back up to 2 nodes when in use. In practice this operation takes about the same amount of time as creating a new cluster.

**Pull request merged**
