### PR TITLE
v1.13 backports 2023-10-24

### PR DESCRIPTION
**Pull request by tklauser**
- [x] #28391 -- bpf: lxc: remove stale ENABLE_IDENTITY_MARK ifdefs (@julianwiedmann)
   - :warning: Minor conflict, kept `SECLABEL` instead of `SECLABEL_IPV4` and `SECLABEL_IPV6` as used on `main`
 - [x] #28141 -- docs: Update IPsec key rotation command (@jschwinger233)
 - [x] #28682 -- docs: Clarify BPF Map Pressure Metric (@nathanjsweet)
 - [x] #28400 -- ipsec: New Prometheus metrics for XFRM configs (@pchaigno)
   - :warning: Conflicts in the first two commits on moved/removed files. Please check whether I've resolved them correctly.
 - [x] #28703 -- policy: Fix Unspecified Protocol Type (@nathanjsweet)
 - [x] #28640 -- cmd: Display decryption interfaces in encrypt status (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 28391 28141 28682 28400 28703 28640; do contrib/backporting/set-labels.py $pr done 1.13; done
```

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.13

**Review by pchaigno — APPROVED** [review]
My PRs look good. Thanks Tobias!

**Review by nathanjsweet — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Review by jschwinger233 — APPROVED** [review]

**Review by tommyp1ckles — APPROVED** [review]

**Comment by tommyp1ckles** [comment]
@sayboras looks like some test failures related to envoy?

**Comment by sayboras** [comment]
> looks like some test failures related to envoy (in runtime)?

As the flaky unit test was introduced by the below backport, I am working on the fix now. 

Considered that it's only unit test, we probably don't need to revert.

https://github.com/cilium/cilium/pull/28331

**Review by dylandreimerink — APPROVED** [review]

**Pull request merged**
