### PR TITLE
Miscellaneous fixes

### PR DESCRIPTION
**Pull request by tgraf**

### CODE REVIEW

**Comment by borkmann** [comment]
While looking through the perf reader, I noticed that we're doing one pkt at a time and need to two __sync_synchronize() for head/tail. Why not moving the loop into this, so that tail is flushed only once after reading all packets? Should be much faster.

**Comment by borkmann** [comment]
We should also change __sync_synchronize() into a more lightweight barrier if possible, as otherwise it's always a full memory barrier (https://gcc.gnu.org/onlinedocs/gcc-6.2.0/gcc/_005f_005fsync-Builtins.html).

**Comment by tgraf** [comment]
@borkmann Agreed. I had the tail write protection for a batch of packets before but it required to store some state which upset cgo because eventually by coincidence a pointer value would match a go pointer value and cgo would complain.

In order to achieve better performance. We have to do a full C implementation of the entire reading loop and the initial parsing and then pass it into go or something alike. The current cgo back and forth is adding so much overhead, the type of memory barrier doesn't even matter right now.

**Comment by borkmann** [comment]
@tgraf Ahh, okay, so this means that the state we had before was problematic due to this false pointer matching from go garbage collector side, but also more generally the fact that we need to do gc for the state. Agree with C rewrite. Under this circumstance, patch 3 (pkg/bpf: Optimize perf reader) in this series looks fine then.

**Review by aanm — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Pull request merged**
