### PR TITLE
add support for k8s 1.17

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9661)

### CODE REVIEW

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Review by brb — APPROVED** [review]

**Pull request merged**
