### PR TITLE
Stable backports 18-04-14

### PR DESCRIPTION
**Pull request by manalibhutiyani**
Backports

### CODE REVIEW

**Comment by manalibhutiyani** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
test-docs-please

**Comment by manalibhutiyani** [comment]
test-missed-k8s

**Comment by manalibhutiyani** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]

**Comment by rlenglet** [comment]
Build failed because of wrong bindata checksum:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/2414/execution/node/58/log/
```
02:46:35     runtime: ../contrib/scripts/bindata.sh d2974bc88d31aba7d3d1cac4d1af4a2073dbd98d
02:46:35     runtime: bindata.go: FAILED
02:46:35     runtime: sha1sum: 
02:46:35     runtime: WARNING: 1 computed checksum did NOT match
02:46:35     runtime: ########################################################################
02:46:35     runtime:                   ERROR: bindata.go is out of date.
02:46:35     runtime: 
02:46:35     runtime:  This can happen for two reasons:
02:46:35     runtime:  1. You are using a go-bindata binary compiled with a different version
02:46:35     runtime:     of golang (not 1.9). If so, please up/downgrade.
02:46:35     runtime: 
02:46:35     runtime:  2. You have made changes to the bpf/ directory. Please run the
02:46:35     runtime:     following command to update the SHA in daemon/bpf.sha:
02:46:35     runtime: 
02:46:35     runtime:     $ make -C daemon apply-bindata
02:46:35     runtime: 
02:46:35     runtime: ########################################################################
02:46:35     runtime: Makefile:46: recipe for target 'check-bindata' failed
02:46:35     runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/daemon'
02:46:35     runtime: Makefile:22: recipe for target 'daemon' failed
02:46:35     runtime: make[1]: *** [check-bindata] Error 1
02:46:35     runtime: make: *** [daemon] Error 2
```

Every backported commit that modifies BPF (e.g. https://github.com/cilium/cilium/pull/3740/commits/d81c10b9a637ffd6d967e682f0e781ccd0b6efec) should be edited to update bindata (just `make -C daemon apply-bindata` and amend the commit with the modified files).

**Comment by manalibhutiyani** [comment]
Closing this one as @tgraf already has another PR open for these backports
https://github.com/cilium/cilium/pull/3741

**Pull request closed without merging**
