### PR TITLE
v1.15 Backports 2024-01-02

### PR DESCRIPTION
**Pull request by pippolo84**
* [x] #29720 (@mhofstetter)
 * [x] #29957 (@gandro)
 * [x] #29880 (@julianwiedmann)
 * [x] #29954 (@rastislavs)
 * [x] #29934 (@pchaigno)
 * [x] #29813 (@jrajahalme)
 * [x] #29246 (@pippolo84)
 * [x] #29896 (@giorio94)
 * [x] #29616 (@learnitall)
 * [x] #29815 (@jrajahalme)
 * [x] #29826 (@giorio94)
 * [x] #29674 (@giorio94)
 * [x] #30000 (@brb)
 * [x] #29865 (@squeed)
 * [x] #29343 (@tommyp1ckles)
 * [x] #29848 (@joamaki)
 * [x] #30013 (@harsimran-pabla)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 29720 29957 29880 29954 29934 29813 29246 29896 29616 29815 29826 29674 30000 29865 29343 29848 30013
```

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]

**Review by mhofstetter — APPROVED** [review]

**Comment by pippolo84** [comment]
/test-backport-1.15

**Review by pchaigno — APPROVED** [review]

**Review by rastislavs — APPROVED** [review]

**Review by harsimran-pabla — APPROVED** [review]

**Comment by pippolo84** [comment]
Conformance Ginkgo flake tracked [here](https://github.com/cilium/cilium/issues/30018#issuecomment-1875499109) and Conformance IPsec E2E [here](https://github.com/cilium/cilium/issues/29846#issuecomment-1875506660), rerunning.

**Review by squeed — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
My commits look good, thanks!

**Review by joamaki — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Review by learnitall — APPROVED** [review]
Thanks!

**Review by jrajahalme — APPROVED** [review]

**Review by tommyp1ckles — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]

**Pull request merged**
