### PR TITLE
fix(docs): bandwidth-manager install error

### PR DESCRIPTION
**Pull request by withlin**
fix(docs): bandwidth-manager install error

Signed-off-by: JinLin Fu <withlin@apache.org>

### CODE REVIEW

**Review by borkmann — APPROVED** [review]
Thanks for spotting!

**Review by bmcustodio — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Thanks for the submission! To satisfy the bot, can you add the Signoff line from your PR into the commit message itself using `git commit --amend` and repush?

**Comment by withlin** [comment]
Done

**Review by joestringer — APPROVED** [review]
Thanks!

FYI in future if you need it, you can use `git commit -s` for --signoff and it will inject the signoff into the commit message based on your git.user configuration, then you can just configure it once and don't need to type it out each time.

**Pull request merged**
