### PR TITLE
v1.9 backports 2021-07-26

### PR DESCRIPTION
**Pull request by jibi**
* ~#16589 -- vagrant: Bump all Vagrant box versions (@pchaigno)~
   * dropped until https://github.com/cilium/cilium/issues/16964 is addressed
 * #16958 -- hubble/relay: Fix close of closed channel in unit test (@gandro)
 * #16937 -- install/kubernetes: restrict k8s access for relay (@jonkerj)
 * #16936 -- contrib: Improve release script guard rails (@joestringer)
 * #16783 -- docs: improve the bandwidth manager page (@bmcustodio)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16958 16937 16936 16783; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by jibi** [comment]
test-backport-1.9

**Comment by jibi** [comment]
test-backport-1.9

**Comment by pchaigno** [comment]
> vagrant: Bump all Vagrant box versions #16589 -- vagrant: Bump all Vagrant box versions (@pchaigno)

You will likely hit https://github.com/cilium/cilium/issues/16964 with that backport.

**Review by bmcustodio — APPROVED** [review]
My commit LGTM!

**Comment by jibi** [comment]
> > vagrant: Bump all Vagrant box versions #16589 -- vagrant: Bump all Vagrant box versions (@pchaigno)
> 
> You will likely hit #16964 with that backport.

Ack, I'll drop it from this backport PR for now and try to address it in a different one

**Comment by jibi** [comment]
test-backport-1.9

**Review by michi-covalent — APPROVED** [review]

**Pull request merged**
