### PR TITLE
feat(helm): allow setting resources for spire agent and server workloads

### PR DESCRIPTION
**Pull request by sjoukedv**
Added resources to the helm values for `authentication.mutual.spire.install.agent` and `authentication.mutual.spire.install.server`.

Replaces https://github.com/cilium/cilium/pull/34798

### CODE REVIEW

**Review by squeed — APPROVED** [review]

**Review by youngnick — APPROVED** [review]

**Comment by ldelossa** [comment]
@sjoukedv looks like we are seeing some legitimate failures here: https://github.com/cilium/cilium/actions/runs/10809781806/job/30324202551?pr=34822

**Comment by sjoukedv** [comment]
> @sjoukedv looks like we are seeing some legitimate failures here: https://github.com/cilium/cilium/actions/runs/10809781806/job/30324202551?pr=34822

```
.  ❌ Found 4 logs in kind-chart-testing/kube-system/cilium-b8jfq (cilium-agent) matching list of errors that must be investigated:
time=2024-09-18T15:03:13Z level=error msg="Timer job errored" module=agent.controlplane.envoy-proxy name=version-check func="envoy.registerEnvoyVersionCheck.func2 (pkg/envoy/cell.go:262)" error="envoy version ae435a5bef3856f4de98fa360ecfa6a0f5b0f7a1/1.30.4/Distribution/RELEASE/BoringSSL does not match with required version 0cb6b7d34a032ee945a80495681ecf2ea109a54c" (1 occurrences)
time="2024-09-18T14:58:13.913853573Z" level=error msg="Envoy: Version check failed" error="envoy version ae435a5bef3856f4de98fa360ecfa6a0f5b0f7a1/1.30.4/Distribution/RELEASE/BoringSSL does not match with required version 0cb6b7d34a032ee945a80495681ecf2ea109a54c" subsys=envoy-proxy (1 occurrences)
time=2024-09-18T14:58:13Z level=error msg="Timer job errored" module=agent.controlplane.envoy-proxy name=version-check func="envoy.registerEnvoyVersionCheck.func2 (pkg/envoy/cell.go:262)" error="envoy version ae435a5bef3856f4de98fa360ecfa6a0f5b0f7a1/1.30.4/Distribution/RELEASE/BoringSSL does not match with required version 0cb6b7d34a032ee945a80495681ecf2ea109a54c" (1 occurrences)
time="2024-09-18T15:03:13.914486416Z" level=error msg="Envoy: Version check failed" error="envoy version ae435a5bef3856f4de98fa360ecfa6a0f5b0f7a1/1.30.4/Distribution/RELEASE/BoringSSL does not match with required version 0cb6b7d34a032ee945a80495681ecf2ea109a54c" subsys=envoy-proxy (1 occurrences)
```

@ldelossa this PR doesn't touch envoy settings. Could it be that the tests are a bit flaky? I can update the branch from main if that helps.

**Review by joamaki — APPROVED** [review]

**Comment by sayboras** [comment]
> Could it be that the tests are a bit flaky? I can update the branch from main if that helps.

This is due to the outdated based branch (vs upstream main branch), and should be resolved after rebase with cilium main.

**Pull request merged**
