### PR TITLE
DO NOT MERGE: Bisecting 1.1 branch

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4842)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please (green)

**Comment by ianvernon** [comment]
test-me-please (green)

**Comment by ianvernon** [comment]
Launching another build to see how stable the branch is (ideally 3-5 concurrent green runs should give us an indicator of stability)

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by tgraf** [comment]
GOOD 7e0975c (-20)

**Comment by tgraf** [comment]
test-me-please (red, -10)

**Comment by tgraf** [comment]
test-me-please (green, -15)

**Comment by tgraf** [comment]
test-me-please (red, -15)

**Comment by tgraf** [comment]
test-me-please (red, -15)

**Comment by tgraf** [comment]
test-me-please (green, -17)

**Comment by tgraf** [comment]
test-me-please (red, -17)

**Comment by tgraf** [comment]
test-me-please (red, -17)

**Comment by tgraf** [comment]
test-me-please (green, -20)

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build link: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4975/

Tests failed due to NACK found in logs (which is a known issue, and is being tracked; it is not exclusive to v1.1)

**Comment by ianvernon** [comment]
test-me-please (green, -20)

**Comment by tgraf** [comment]
test-me-please

**Pull request closed without merging**
