### PR TITLE
cilium-health: accept only positive interval

### PR DESCRIPTION
**Pull request by nirmoy**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4593)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by nirmoy** [comment]
missed make -C Documentation cmdref

**Comment by joestringer** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by joestringer** [comment]
Hit #4579. Retrying.

**Comment by joestringer** [comment]
test-me-please

**Review by manalibhutiyani — APPROVED** [review]

**Pull request merged**
