### PR TITLE
[CI] retry vm provisioning, increase timeout

### PR DESCRIPTION
**Pull request by nebril**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8477)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-upstream-k8s

**Review by raybejjani — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
