### PR TITLE
Istio: Update to 1.2.4

### PR DESCRIPTION
**Pull request by jrajahalme**
Istio release 1.2.4 includes the sidecar proxy with Envoy security fixes released on 8/13/2019.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

```release-note
Istio integration is updated to Istio version 1.2.4
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8917)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by ianvernon** [comment]
never-tell-me-the-odds

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
NodePort test failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2366/testReport/junit/Suite-k8s-1/13/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort/

**Comment by ianvernon** [comment]
test-missed-k8s

**Pull request merged**
