### PR TITLE
Deprecate providing Hubble TLS secrets in helm values

### PR DESCRIPTION
**Pull request by chancez**
This is the first step in a few changes to improve our documentation around configuring and using Hubble with TLS. The next PR https://github.com/cilium/cilium/pull/34115 will build upon this to make some improvements on the Hubble TLS documentation.

The primary goal with this PR is to add support for using existing secrets for Hubble TLS certificates and private keys to discourage storing private keys in helm values, and to better support users who wish to manage TLS certificates using other methods. While introducing support for using existing secrets, we should deprecate the previous method of directly providing certificates via helm values.

In the same vein, we want to encourage users to use one of the automated TLS methods rather than provide their own certificates in most cases, so let's move the documentation for user provided certificates to the end of the section. 

I've got a number of other TLS related improvements coming, mostly in the form of documentation updates, and would like to get all of those improvements in to the stable/v1.16 documentation, so I'm setting the `needs-backport/1.16` label on this PR. If the deprecation, and/or helm changes are an issue to backport, then we could skip the backport on this PR, and I'll just have to deal with conflicts when back porting the rest of my upcoming PRs to v1.16. Let me know what you think.

### CODE REVIEW

**Review by nebril — APPROVED** [review]

**Review by ghost — CHANGES_REQUESTED** [review]
Ideally deprecations should also be documented in upgrade notes (`Documentation/operations/upgrade.rst`), can you add a note there?

**Review by joamaki — APPROVED** [review]

**Review by ghost — APPROVED** [review]
lgtm

**Review by rolinh — APPROVED** [review]
This is a great doc improvement, thanks!

**Pull request merged**
