### PR TITLE
v1.9 backports 2021-07-01

### PR DESCRIPTION
**Pull request by jrajahalme**
* #16391 -- iptables: Keep old rules while adding new ones (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16391; do contrib/backporting/set-labels.py $pr done 1.9; done
```

```release-note
DNS proxy is now more available during Cilium restarts, including upgrades. 
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-backport-1.9

**Review by pchaigno — CHANGES_REQUESTED** [review]
LGTM apart from the sign off issue:
```
Signed-off-by: vagrant <vagrant@runtime>
```

**Comment by pchaigno** [comment]
k8s-1.17-kernel-5.4 is hitting the usual complexity issue on v1.9. k8s-1.18-kernel-4.19 crashed with a Jenkins stack trace (reason isn't clear).

More interestingly, runtime hit https://github.com/cilium/cilium/issues/16713, it seems for the first time on v1.9. Could https://github.com/cilium/cilium/issues/16713 be caused by these changes?

**Comment by pchaigno** [comment]
test-1.18-4.19

**Comment by jrajahalme** [comment]
test-backport-1.9

**Comment by jrajahalme** [comment]
vm provisioning fails

**Comment by jrajahalme** [comment]
test-backport-1.9

**Comment by jrajahalme** [comment]
test-backport-1.9

**Comment by jrajahalme** [comment]
> We should probably update the commit description to point to the upstream commits now that #16391 is merged. The PR needs a rebase anyway.

Done :-)

**Review by pchaigno — APPROVED** [review]

**Comment by jrajahalme** [comment]
Unrelated unit test fail for arm64 build (#9604)

**Comment by jrajahalme** [comment]
Jenkins fail:
```
java.io.IOException: Cannot read more than 2Gib at a time
```
on test-1.17-5.4, no other indication of failure in https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-5.4/68/

retesting

**Comment by jrajahalme** [comment]
test-1.17-5.4

**Comment by jrajahalme** [comment]
a consistent fail in test-1.17-5.4 due to #16050

**Comment by jrajahalme** [comment]
> a consistent fail in test-1.17-5.4 due to #16050

This test has failed on v1.9 since May 9th. Assuming we are ignoring this for now & marking this ready-to-merge.

**Pull request merged**
