### PR TITLE
Update weekly community meeting timeslot

### PR DESCRIPTION
**Pull request by joestringer**
As discussed during community meeting 2021-05-03.

The next meeting will be 2021-05-12.

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]

**Comment by glibsm** [comment]
To backport into 1.8 we need https://github.com/cilium/cilium/commit/63996d674e844da369e6408db4b90c836952d5ba first

**Comment by pchaigno** [comment]
@joestringer I see you removed the v1.9 backport. Users can land on any version of this page via search engines, so I'd rather backport everywhere. It should cause much conflicts as we can just overwrite the older versions with the new. WDYT?

**Comment by joestringer** [comment]
@pchaigno I agree, but I expected it's going to conflict. Glib and I had a brief discussion on the topic here: https://github.com/cilium/cilium/pull/16015#discussion_r626746512 but basically we need to either do some extra work to line it up correctly and backported on the v1.8 / v1.9 branches (and make sure we always update these on older branches), or put out a PR so that the v1.8/v1.9/v1.10 branches avoid stating this information directly and just link to the dev docs for the latest version of this information.

**Comment by pchaigno** [comment]
> I agree, but I expected it's going to conflict.

Isn't it just a matter of overwriting whatever is on the v1.X page with the content of the master page?

**Comment by joestringer** [comment]
Yeah, the conflict is easy enough to resolve. Needs additions to the spelling list too. Basically just backporting https://github.com/cilium/cilium/commit/63996d674e844da369e6408db4b90c836952d5ba should make it a clean backport I think.

**Comment by joestringer** [comment]
Now that #14968 is marked for backport, we can re-mark this and it should be smooth next time.

**Pull request merged**
