### PR TITLE
iptables: Read CNI chaining mode from CNI config manager

### PR DESCRIPTION
**Pull request by pippolo84**
CNI chaining mode option has been moved to the CNI cell in commit 1254bf403f.

Since it is not a global config option anymore, iptables manager will not see any change to that value, and its field `CNIChainingMode` will always be an empty string.
Thus, with the following config option values:

- "enable-endpoint-routes": true
- "cni-chaining-mode": "aws-cni"

the delivery interface referenced in the rules installed by the manager is "lxc+" instead of "eni+".

This commit fixes this adding a CNI config manager reference to the iptables manager parameters, in order to read the current setting for the chaining mode during rules installation.

Fixes: 1254bf403f ("daemon / cni: move to Cell, watch for changes")

```release-note
Fix the referenced interface in iptables rules (`eni+` instead of `lxc+`) when `--enable-endpoint-routes=true` and `--cni-chaining-mode="aws-cni"`
```

### CODE REVIEW

**Comment by pippolo84** [comment]
Added @squeed as reviewer as original author of https://github.com/cilium/cilium/pull/24389

**Comment by pippolo84** [comment]
Force pushed after rebase

**Review by ldelossa — APPROVED** [review]
LGTM

**Review by squeed — APPROVED** [review]
Nice catch!

**Comment by pippolo84** [comment]
ci-clustermesh hit https://github.com/cilium/cilium/issues/30964, rerunning

**Comment by pippolo84** [comment]
ci-ipsec-upgrade hit https://github.com/cilium/cilium/issues/29856, rerunning

**Comment by pippolo84** [comment]
Force pushed to rebase on main and solve some flakes.

**Comment by julianwiedmann** [comment]
:wave: is this worth a `release-note/bug` label, and corresponding release-note text?

**Comment by julianwiedmann** [comment]
The v1.14 backport landed via https://github.com/cilium/cilium/pull/31265.

**Pull request merged**
