### PR TITLE
operator: remove lastPodRestart in unmanaged pod controller

### PR DESCRIPTION
**Pull request by wedaly**
operator: remove lastPodRestart in unmanaged pod controller

The restart-unmanaged-pod controller logic was:

1. Find unmanaged pod to delete.
2. Lookup the last restart time by the pod's ID (namespace + name).
3. If last restart time is less than 5 minutes ago, skip.
4. Otherwise, delete the pod.
5. If the deletion was successful, set lastPodRestart[podID] = time.Now()

However, step 2 would never find pod ID in the lastRestartTime map, because podIDs are only added to the map after a successful deletion (step 5). Any new pods created after the deletion would be assigned a unique, different, pod ID. Therefore, step 3 would never be executed.

Since the controller behaves the same without checking lastPodRestart, and I don't believe there is a way to reliably identify which pod replaced the deleted pod, remove the lastPodRestart map.

### CODE REVIEW

**Comment by joamaki** [comment]
Why would the `podID` be different after restart? It's the `namespace/name` after all and not e.g. the `types.ID`?

**Comment by squeed** [comment]
There is one case in which pod names are constant, even across deletion: StatefulSets. I agree, though, the logic is convoluted to say the least.

**Comment by joamaki** [comment]
Ok that makes sense. Has the naming behavior changed at some point in Kubernetes? Looking at the original issue (https://github.com/cilium/cilium/issues/6839) it shows that it was added to fix multiple restarts of kube-dns pods and there the name didn't change. I would be hesitant to removing this code until we're sure we don't just reintroduce #6839 back again.

**Comment by wedaly** [comment]
> Ok that makes sense. Has the naming behavior changed at some point in Kubernetes? Looking at the original issue (#6839) it shows that it was added to fix multiple restarts of kube-dns pods and there the name didn't change. I would be hesitant to removing this code until we're sure we don't just reintroduce #6839 back again.

hmm, looking at that issue I'm now less confident in this change

Reading through https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination I suspect cilium-operator might end up sending multiple delete requests between when apiserver sets `DeletionTimestamp` on the pod and when kubelet finishes cleaning it up.

Given that the current code isn't causing any problems and I'm not 100% sure removing it is safe, I'll close this PR. Thanks for the review and comments!

**Pull request closed without merging**
