### PR TITLE
test: Enable third node in K8sKubeProxyFreeMatrix suite

### PR DESCRIPTION
**Pull request by brb**
Just blindly uncommenting @aanm's code (no-kube-proxy + third node w/o cilium has been already merged).

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by brb** [comment]
Some `K8sKubeProxyFreeMatrix` tests failed, marking this PR as WIP.

**Comment by brb** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
this PR has been marked as a draft PR since it had a WIP label. Please click in "Ready for review" [below vvv ] once the PR is ready to be reviewed. CI will still run for draft PRs.

**Pull request closed without merging**
