### PR TITLE
hubble: add file name and line number info to dropped flows

### PR DESCRIPTION
**Pull request by kaworu**
When running `cilium monitor` the file name and line number are displayed for dropped flows, but before this patch the file information were not exposed in Hubble flows. This commit adds file name and line number to Hubble flows, and populate them for dropped flows (i.e. Verdict = DROPPED).

Some comments cleanup on the way.

### CODE REVIEW

**Review by brb — APPROVED** [review]
Thanks!

**Review by rolinh — APPROVED** [review]
lgtm

**Review by learnitall — APPROVED** [review]
LGTM!

**Comment by kaworu** [comment]
[Conformance IPsec E2E (ci-ipsec-e2e)](https://github.com/cilium/cilium/actions/runs/11036070609/job/30653664230) hit https://github.com/cilium/cilium/issues/34981

**Comment by julianwiedmann** [comment]
Thank you! This will also address https://github.com/cilium/hubble/issues/1216.

**Pull request merged**
