### PR TITLE
v1.3 backports 2019-05-14

### PR DESCRIPTION
**Pull request by nebril**
* #7955 -- test: replace guestbook test docker image (@aanm)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 7955; do contrib/backporting/set-labels.py $pr done 1.3; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8012)

### CODE REVIEW

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Review by raybejjani — APPROVED** [review]

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Review by raybejjani — APPROVED** [review]

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-me-please

**Comment by aanm** [comment]
Closing in favor of #8157

**Pull request closed without merging**
