### PR TITLE
[v1.13-hf] ipsec: cache xfrm state list

### PR DESCRIPTION
**Pull request by marseel**
Backport of https://github.com/cilium/cilium/pull/32588

Changes compared to original PR:
- Use `time` instead of `pkg/time`
- Some minor changes with replacing correctly `netlink.XfrmState*` in `ipsec_linux.go`
- switching `t *testing.T` -> `check.v1`

I've manually verified turning off caching with following helm values:
```
extraArgs:
  - --enable-ipsec-xfrm-state-caching=false
```

### CODE REVIEW

**Comment by marseel** [comment]
/test-backport-1.13

**Comment by marseel** [comment]
/test-backport-1.13

**Review by lmb — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]

**Comment by marseel** [comment]
Rebased to pick up https://github.com/cilium/cilium/pull/32668

**Comment by marseel** [comment]
/test-backport-1.13

**Comment by marseel** [comment]
Fixed typo when in tests when migrating from testing to check: `NotNil` -> `IsNil`

**Comment by marseel** [comment]
/test-backport-1.13

**Comment by marseel** [comment]
Runtime test https://jenkins.cilium.io/job/Cilium-PR-Runtime-kernel-net-next/1634/ failed with:
```
12:33:49  	 [10:30:00]     // Create new xfrm state and check that cache is utomatically updated
12:33:49  	 [10:30:00]     c.Assert(xfrmStateCache.isExpired(), Equals, false)
12:33:49  	 [10:30:00] ... obtained bool = true
12:33:49  	 [10:30:00] ... expected bool = false
```

Which makes sense after looking at netlink.XfrmStateList implementation, it returns nil pointer if there are no XfrmState results: https://github.com/cilium/cilium/blob/0a8f3f91f1090230b73324169ddb84385007ff24/vendor/github.com/vishvananda/netlink/xfrm_state_linux.go#L392-L411
so cache considers it expired - which is fine from a correctness point of view, just unit test fails. 

While it's not a bug in the implementation itself, it means that my suspicion that privileged tests were probably not being run on the main branch is correct: https://github.com/cilium/cilium/pull/32588#issuecomment-2117559246
I've validated that with this PR: https://github.com/cilium/cilium/pull/32686


So I:
- Fixed test here by pushing a new commit that only changes unit tests.
- @sayboras is looking into fixing that on main

**Comment by marseel** [comment]
/test-backport-1.13

**Comment by marseel** [comment]
/test-backport-1.13

**Comment by marseel** [comment]
/test-backport-1.13

**Comment by marseel** [comment]
Ok, all tests passed, and everything seems to be working, merging PR.

**Pull request merged**
