### PR TITLE
v1.11 backports 2022-08-09

### PR DESCRIPTION
**Pull request by nbusseneau**
* #20404 -- Add metric to track terminating endpoint events (@aditighag)
 * #18384 -- istio: Update to release 1.10.6 (@jrajahalme)
 * #20305 -- dnsproxy: update dnsproxy benchmark memory calculation (@odinuge)
 * #20296 -- Add Peer Service to Cilium DS Port List (@nathanjsweet)
 * #20251 -- Fix the bugs when empty CiliumEndpointSlices were created and leaked. (@alan-kut)
 * #20433 -- pkg/metrics: Remove source node label (@aditighag)
 * #20440 -- Disable Envoy version check if L7 proxy is disabled (@bmcustodio)
 * #20486 -- docs: Bump up Netlify Python version to 3.8 (@michi-covalent)
 * #20460 -- docs: fix a Links documentation style guide error (@Kikiodazie)
 * #20491 -- Add metric on number of requests rejected by DNS Proxy semaphore (@rahulkjoshi)
 * #20517 -- add an option to wait for kube-proxy (@michi-covalent)
 * #20383 -- pkg/k8s/version: Also set EndpointSlice when forcing version (@joamaki)
 * #20537 -- fqdn/dnsproxy: fix test build (@tklauser)
 * #20538 -- docs(masquerading): add missing "address" (@raphink)
 * #20552 -- Fix mtu setting for tunnel interface in init.sh (@ChengyuanLiCY)
 * #20569 -- pkg/k8s: do not wait for endpointslice cache sync in k8s >= 1.17 (@aanm)
 * #20624 -- docs: update etcd kvstore migration instructions (@hhoover)
 * #20564 -- contrib: Add CRD generation to release process (@joestringer)
 * #20649 -- daemon: Improve dnsproxy error when EP not found (@joestringer)
 * #20203 -- ci: use pinned Cilium CLI version for post-test information gathering (@tklauser)
 * #20617 -- ci: pick up cilium-cli v0.12.0 for master, v1.11 and v1.12 workflows (@tklauser)
 * #20609 -- ENI: Trigger NodeManager.Resync immediately after new ENI successfully created (@wu0407)
 * #20643 -- helm: Guard apply sysctl init container (@sayboras)
 * #20673 -- command: fix parsing of string map strings with multiple separators (@tklauser)
 * #20697 -- clustermesh: Add EndpointSlice support for API server (@YutaroHayakawa)
 * #20685 -- ci: fix code changes detection on `push` events (@nbusseneau)
 * #20680 -- iptables: handle case where kernel IPv6 support is disabled (@jibi)
 * #20449 -- fix subnet_id label value is empty (@wu0407)
 * #20572 -- ui: release v0.9.1 (@geakstr)
 * #20716 -- docs: Update Helm values (@qmonnet)
 * #20744 -- Revert "Revert "doc: update the api spec for fqdn egress policies cod… (@aanm)
 * #20741 -- Fix ineffective post-start hook in ENI mode (@bmcustodio)
 * #20757 -- pkg/k8s: set the right IP addresses in log messages (@aanm)
 * #20750 -- Consider `$GO` environment variable `make precheck` checks (@tklauser)
 * #20234 -- ci: pick up cilium-cli v0.11.9 for master/v1.11 workflows (@tklauser)
 * #20082 -- helm: Make DNS policy for agent and operator configurable (@michi-covalent)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20404 18384 20305 20296 20251 20433 20440 20486 20460 20491 20517 20383 20537 20538 20552 20569 20624 20564 20649 20203 20617 20609 20643 20673 20697 20685 20680 20449 20572 20716 20744 20741 20757 20750 20234 20082; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
@aditighag FYI, 0e1d03fe66b840240157ff50f0d6af4dc9aefc94 was skipped due to #18814 not having been backported to `v1.11`.

**Review by sayboras — APPROVED** [review]
Looks good for my changes :100:

**Review by jibi — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
Backports of my PRs look good. I also scanned through the github workflow changes. :+1:

**Review by aanm — APPROVED** [review]
All my commits look good. Thanks

**Review by tklauser — APPROVED** [review]
My changes look good. Thanks Nicolas.

**Review by qmonnet — APPROVED** [review]
> - https://github.com/cilium/cilium/pull/20716 -- docs: Update Helm values (@qmonnet)

Looks good, thanks!

**Comment by tklauser** [comment]
Kind conformance test looks related to the cilium-cli update which dropped the `base-version` flag: https://github.com/cilium/cilium/runs/7747502208?check_suite_focus=true

I think we'd also need to backport the relevant bits of #20234 135f522644f0953385df2c5b0a24c4cb9ebe3c5e for the workflows that don't live on `master`.

**Review by geakstr — APPROVED** [review]
Looks good, thanks!

**Review by nathanjsweet — APPROVED** [review]
My changes look good.

**Comment by nbusseneau** [comment]
> I think we'd also need to backport the relevant bits of #20234 (commit [135f522](https://github.com/cilium/cilium/commit/135f522644f0953385df2c5b0a24c4cb9ebe3c5e)) for the workflows that don't live on `master`.

Done!

**Comment by nbusseneau** [comment]
/test-backport-1.11

**Review by YutaroHayakawa — APPROVED** [review]
My change looks good to me. Thanks!

**Review by michi-covalent — APPROVED** [review]

**Comment by nbusseneau** [comment]
/test-backport-1.11

**Review by tklauser — APPROVED** [review]
https://github.com/cilium/cilium/pull/20234 backport also LGTM, thank you.

**Comment by dylandreimerink** [comment]
The backport of #20413 breaks Travis, which is fixed by #20521. Since #20521 can't be automatically backported, I suggest removing #20413 from this PR, I will make a custom backport with both #20413 and #20521 to keep everything happy

**Comment by nbusseneau** [comment]
@dylandreimerink OK.

**Comment by nbusseneau** [comment]
/test-backport-1.11

**Review by aditighag — APPROVED** [review]
Backports of my PRs look good. Thank you!

**Comment by nbusseneau** [comment]
GKE https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/9022/ hit an issue very similar to #16852:

```
/home/jenkins/workspace/Cilium-PR-K8s-GKE/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:527
Expected
    <*fmt.wrapError | 0xc0015ab420>: {
        msg: "could not parse JSON from command \"kubectl -n kube-system get pod cilium-5lphm -o json\"\nunexpected end of JSON input\n",
        err: <*json.SyntaxError | 0xc0012e9950>{
            msg: "unexpected end of JSON input",
            Offset: 0,
        },
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-GKE/src/github.com/cilium/cilium/test/k8sT/Health.go:55
```

Re-trying to check if consistent, will file an issue for flake if not.

**Comment by nbusseneau** [comment]
L4LB tests https://github.com/cilium/cilium/actions/runs/2832079407 failed with a known issue that's addressed by #20682 and #20834.

**Comment by tklauser** [comment]
Approvals are in (namely for backports that needed special attention) and all remaining test failures are known flakes (AKS, GKE) or will be followed up on (L4LB). Merging this PR.

**Pull request merged**
