### PR TITLE
.travis: update travis golang to 1.12.5

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8294)

### CODE REVIEW

**Comment by aanm** [comment]
@joestringer I've noticed we are unit testing against this clang version. Shouldn't we update it?

https://github.com/cilium/cilium/blob/61960adfba101bec0c231575c7c4b77c585d02f3/.travis/prepare.sh#L3

**Comment by joestringer** [comment]
@aanm I thought you didn't want to change it because we would lose testing of compiling with LLVM 3.8 :-)

I'd be OK with bumping it, ideally we'd just use whatever comes with the distro from Travis but apparently that's *ancient*.. any chance we can also bump to a distro released in the last five years?

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
> @aanm I thought you didn't want to change it because we would lose testing of compiling with LLVM 3.8 :-)
> 
> I'd be OK with bumping it, ideally we'd just use whatever comes with the distro from Travis but apparently that's _ancient_.. any chance we can also bump to a distro released in the last five years?

@joestringer are we using clang in the unit tests?

**Comment by joestringer** [comment]
@aanm I believe that the unit tests rely on compilation of a BPF ELF file (so that `pkg/elf` can do it's unprivileged testing)

**Pull request merged**
