### PR TITLE
Create main.yml as a renovate bot for github actions

### LINKED ISSUE #25457: Add renovate bot as a GitHub action
Once we are able to run renovate as a GitHub action we should be able to specify any [postupgradecommands](https://docs.renovatebot.com/self-hosted-configuration/#allowedpostupgradecommands) that we wish. This will be helpful so that we can generate certain files after updates. For example `install/kubernetes/cilium/values.yaml` which is generated from the `install/kubernetes/cilium/values.yaml.tmpl` could make use of this. Another example is the `make -C images/ update-runtime-image` and `make -C images/ update-builder-image` scripts that are executed after upgrading.

Instructions are in https://github.com/renovatebot/github-action

### PR DESCRIPTION
**Pull request by swastik959**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #25457

```release-note
NONE
```

### CODE REVIEW

**Review by nbusseneau — COMMENTED** [review]
Hello! I am a bit confused, can you clarify what the PR is trying to achieve? 🤔 For information we already have Renovate watching over our GitHub Actions (see https://github.com/cilium/cilium/blob/main/.github/renovate.json5).

**Comment by swastik959** [comment]
@nbusseneau oh it is there so that means in this issue I only have have add a script to the renovate.json5

**Comment by nbusseneau** [comment]
Sorry, I'm still not sure what you're trying to achieve 😅 Perhaps you can give some more details? Would be helpful so that you don't waste time implementing something that might already be there.

**Review by aanm — CHANGES_REQUESTED** [review]
Thank you for the changes but I believe we need a PR similar to https://github.com/cilium/tetragon/pull/1036 made into Cilium

**Pull request closed without merging**
