### PR TITLE
test: Skip Istio test if Ginkgo runs on unsupported runtime.

### PR DESCRIPTION
**Pull request by jrajahalme**
Skip Istio test if running cilium-istioctl is not supported for the
current Go runtime.

Support running Istio test from OSX by downloading the osx version of
cilium-istioctl if the test suite is running in OSX. This allows
running the Istio test on a remote cluster (e.g., GKE) when Ginkgo is
running on OSX.

On Windows the test is skipped, even though the cilium-istioctl binary
is released also for Windows, but this has not been tested yet.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Review by michi-covalent — APPROVED** [review]

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Fixed formatting errors, re-testing.

**Comment by jrajahalme** [comment]
Unrelated runtime flake due to external connectivity:
```
Expected to be able to connect to cloudflare ("1.1.1.1"); external connectivity not available
```

**Pull request merged**
