### PR TITLE
1.8 backport for envoy: Update to release 1.18.4

### PR DESCRIPTION
**Pull request by jrajahalme**
```release-note
Cilium Envoy integration is updated to release 1.18.4. 
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-backport-1.8

**Comment by jrajahalme** [comment]
test-backport-1.8

**Comment by jrajahalme** [comment]
test-backport-1.8

**Review by joestringer — APPROVED** [review]

**Comment by jrajahalme** [comment]
1.17 hit by #14598

**Comment by jrajahalme** [comment]
k8s 1.16 hit by #16873. This might be fixed by #16381, but that is not backported to v1.8.

**Comment by jrajahalme** [comment]
Smoke test failed to install Ginkgo.

**Comment by jrajahalme** [comment]
@joestringer all CI fails look non-Envoy related.

**Comment by joestringer** [comment]
Filed #17263 for smoke test failure.

**Pull request merged**
