### PR TITLE
[1.15] bpf: lxc: limit nodeport RevDNAT support to IPsec configurations

### PR DESCRIPTION
**Pull request by jschwinger233**
- [ ] https://github.com/cilium/cilium/pull/33960

### CODE REVIEW

**Comment by jschwinger233** [comment]
/test-backport-1.15

**Comment by jschwinger233** [comment]
/test-backport-1.15

**Comment by julianwiedmann** [comment]
Curious, I would have expected some CI fallout as https://github.com/cilium/cilium/pull/33426 is not available on v1.15.

**Comment by jschwinger233** [comment]
@julianwiedmann I think this is because echo-ingress-l7-via-hostport-with-encryption skips 1.15 https://github.com/cilium/cilium/blob/dc6d99ffe02a50023f25b52804a2e8280fbd3110/cilium-cli/connectivity/builder/echo_ingress_l7.go#L48

**Comment by julianwiedmann** [comment]
> @julianwiedmann I think this is because echo-ingress-l7-via-hostport-with-encryption skips 1.15
> 
> https://github.com/cilium/cilium/blob/dc6d99ffe02a50023f25b52804a2e8280fbd3110/cilium-cli/connectivity/builder/echo_ingress_l7.go#L48

Yep, and *that* scenario **is** broken on v1.15 (since we redirect to L7 proxy before hitting the RevNAT in bpf_lxc).

But with this PR we would now skip RevNAT for **all** reply traffic that returns to the client via WG. And I'm pretty sure we had previously seen CI breakage on `main` when attempting to switch the RevNAT to the native-device level ... which made us realize that WG needs a RevNAT stage.

**Pull request closed without merging**
