### PR TITLE
daemon: adding support for egress policy tracing

### PR DESCRIPTION
**Pull request by wofanli**
Previously, only ingress policy tracing is supported.

Related: #9790

Signed-off-by: Wenxian Li <wofanli@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10020)

### CODE REVIEW

**Review by joestringer — COMMENTED** [review]
Wow, this looks like an easy fix, awesome!

Do you have commandline examples of how you tested this and what the output looks like with egress policy enabled? Also with ingress + egress policy enabled?

Next I'm wondering how we could validate that the policy trace output matches the behaviour in the regular tests... should be possible at least in the `test/runtime/Policies.go` tests with a straightforward CLI invocation.

**Comment by wofanli** [comment]
@joestringer Sure. Let me add several test-cases.

**Comment by joestringer** [comment]
I tested this and for basic cases it works great, thanks!

```
$ cilium policy trace -s id=app2 -d reserved:world --dport 53
----------------------------------------------------------------
Tracing From: [any:id=app2] => To: [reserved:world] Ports: [53/ANY]

Resolving egress policy for [any:id=app2]
* Rule {"matchLabels":{"any:id":"app2"}}: selected
    Allows to labels {"matchLabels":{"reserved:world":""}}
      Found all required labels
      Allows port [{53 ANY}]
    Allows to labels {"matchLabels":{"reserved:none":""}}
      No label match for [reserved:world]
1/1 rules selected
Found allow rule
Egress verdict: allowed


Final verdict: ALLOWED
```

This was using the following diff against master + app2 from the docker examples.

```
diff --git a/examples/policies/l7/dns/dns.json b/examples/policies/l7/dns/dns.json
index a397d9fc9752..1a0a673aea49 100644
--- a/examples/policies/l7/dns/dns.json
+++ b/examples/policies/l7/dns/dns.json
@@ -2,17 +2,13 @@
   {
     "endpointSelector": {
       "matchLabels": {
-        "app": "test-app"
+        "id": "app2"
       }
     },
     "egress": [
       {
-        "toEndpoints": [
-          {
-            "matchLabels": {
-              "app-type": "dns"
-            }
-          }
+        "toEntities": [
+           "world"
         ],
         "toPorts": [
           {
```

**Comment by joestringer** [comment]
I note that this still doesn't work for CIDR or DNS destinations, examples:

### CIDR
```
$ cilium identity list | grep cidr
16777217   cidr:104.198.14.52/32
16777218   cidr:20.1.1.1/32
16777219   cidr:10.128.0.0/9
16777220   cidr:10.0.0.0/10
16777221   cidr:10.64.0.0/11
16777222   cidr:10.112.0.0/12
$ cilium policy trace -s id=app2 --dst-identity 16777217
----------------------------------------------------------------
Tracing From: [any:id=app2] => To: [cidr:0.0.0.0/0, cidr:0.0.0.0/1, cidr:104.0.0.0/5, cidr:104.0.0.0/6, cidr:104.0.0.0/7, cidr:104.0.0.0/8, cidr:104.128.0.0/9, cidr:104.192.0.0/10, cidr:104.192.0.0/11, cidr:104.192.0.0/12, cidr:104.192.0.0/13, cidr:104.196.0.0/14, cidr:104.198.0.0/15, cidr:104.198.0.0/16, cidr:104.198.0.0/17, cidr:104.198.0.0/18, cidr:104.198.0.0/19, cidr:104.198.0.0/20, cidr:104.198.12.0/22, cidr:104.198.14.0/23, cidr:104.198.14.0/24, cidr:104.198.14.0/25, cidr:104.198.14.0/26, cidr:104.198.14.32/27, cidr:104.198.14.48/28, cidr:104.198.14.48/29, cidr:104.198.14.52/30, cidr:104.198.14.52/31, cidr:104.198.14.52/32, cidr:104.198.8.0/21, cidr:64.0.0.0/2, cidr:96.0.0.0/3, cidr:96.0.0.0/4, reserved:world] Ports: [0/ANY]

Resolving egress policy for [any:id=app2]
* Rule {"matchLabels":{"any:id":"app2"}}: selected
    Allows to labels {"matchLabels":{"reserved:world":""}}
      Found all required labels
      Allows port [{53 ANY}]
    Allows to labels {"matchLabels":{"reserved:none":""}}
      No label match for [cidr:0.0.0.0/0 cidr:0.0.0.0/1 cidr:104.0.0.0/5 cidr:104.0.0.0/6 cidr:104.0.0.0/7 cidr:104.0.0.0/8 cidr:104.128.0.0/9 cidr:104.192.0.0/10 cidr:104.192.0.0/11 cidr:104.192.0.0/12 cidr:104.192.0.0/13 cidr:104.196.0.0/14 cidr:104.198.0.0/15 cidr:104.198.0.0/16 cidr:104.198.0.0/17 cidr:104.198.0.0/18 cidr:104.198.0.0/19 cidr:104.198.0.0/20 cidr:104.198.12.0/22 cidr:104.198.14.0/23 cidr:104.198.14.0/24 cidr:104.198.14.0/25 cidr:104.198.14.0/26 cidr:104.198.14.32/27 cidr:104.198.14.48/28 cidr:104.198.14.48/29 cidr:104.198.14.52/30 cidr:104.198.14.52/31 cidr:104.198.14.52/32 cidr:104.198.8.0/21 cidr:64.0.0.0/2 cidr:96.0.0.0/3 cidr:96.0.0.0/4 reserved:world]
* Rule {"matchLabels":{"any:id":"app2"}}: selected
    Allows to labels {"matchLabels":{"cidr:20.1.1.1/32":""}}
      No label match for [cidr:0.0.0.0/0 cidr:0.0.0.0/1 cidr:104.0.0.0/5 cidr:104.0.0.0/6 cidr:104.0.0.0/7 cidr:104.0.0.0/8 cidr:104.128.0.0/9 cidr:104.192.0.0/10 cidr:104.192.0.0/11 cidr:104.192.0.0/12 cidr:104.192.0.0/13 cidr:104.196.0.0/14 cidr:104.198.0.0/15 cidr:104.198.0.0/16 cidr:104.198.0.0/17 cidr:104.198.0.0/18 cidr:104.198.0.0/19 cidr:104.198.0.0/20 cidr:104.198.12.0/22 cidr:104.198.14.0/23 cidr:104.198.14.0/24 cidr:104.198.14.0/25 cidr:104.198.14.0/26 cidr:104.198.14.32/27 cidr:104.198.14.48/28 cidr:104.198.14.48/29 cidr:104.198.14.52/30 cidr:104.198.14.52/31 cidr:104.198.14.52/32 cidr:104.198.8.0/21 cidr:64.0.0.0/2 cidr:96.0.0.0/3 cidr:96.0.0.0/4 reserved:world]
    Allows to labels {"matchLabels":{"cidr:10.128.0.0/9":""}}
    Allows to labels {"matchLabels":{"cidr:10.0.0.0/10":""}}
    Allows to labels {"matchLabels":{"cidr:10.64.0.0/11":""}}
    Allows to labels {"matchLabels":{"cidr:10.112.0.0/12":""}}
      No label match for [cidr:0.0.0.0/0 cidr:0.0.0.0/1 cidr:104.0.0.0/5 cidr:104.0.0.0/6 cidr:104.0.0.0/7 cidr:104.0.0.0/8 cidr:104.128.0.0/9 cidr:104.192.0.0/10 cidr:104.192.0.0/11 cidr:104.192.0.0/12 cidr:104.192.0.0/13 cidr:104.196.0.0/14 cidr:104.198.0.0/15 cidr:104.198.0.0/16 cidr:104.198.0.0/17 cidr:104.198.0.0/18 cidr:104.198.0.0/19 cidr:104.198.0.0/20 cidr:104.198.12.0/22 cidr:104.198.14.0/23 cidr:104.198.14.0/24 cidr:104.198.14.0/25 cidr:104.198.14.0/26 cidr:104.198.14.32/27 cidr:104.198.14.48/28 cidr:104.198.14.48/29 cidr:104.198.14.52/30 cidr:104.198.14.52/31 cidr:104.198.14.52/32 cidr:104.198.8.0/21 cidr:64.0.0.0/2 cidr:96.0.0.0/3 cidr:96.0.0.0/4 reserved:world]
2/2 rules selected
Found allow rule
Egress verdict: denied


Final verdict: DENIED
```

### FQDN

```
$ cilium policy trace --src-endpoint 2426 --dst-iden                                                                                             
tity 16777217                                                                                                                                                                                  
----------------------------------------------------------------                                                                                                                               
Tracing From: [container:id=app2, container:maintainer=tgraf@tgraf.ch] => To: [cidr:0.0.0.0/0, cidr:0.0.0.0/1, cidr:104.0.0.0/5, cidr:104.0.0.0/6, cidr:104.0.0.0/7, cidr:104.0.0.0/8, cidr:104
.128.0.0/9, cidr:104.192.0.0/10, cidr:104.192.0.0/11, cidr:104.192.0.0/12, cidr:104.192.0.0/13, cidr:104.196.0.0/14, cidr:104.198.0.0/15, cidr:104.198.0.0/16, cidr:104.198.0.0/17, cidr:104.19
8.0.0/18, cidr:104.198.0.0/19, cidr:104.198.0.0/20, cidr:104.198.12.0/22, cidr:104.198.14.0/23, cidr:104.198.14.0/24, cidr:104.198.14.0/25, cidr:104.198.14.0/26, cidr:104.198.14.32/27, cidr:1
04.198.14.48/28, cidr:104.198.14.48/29, cidr:104.198.14.52/30, cidr:104.198.14.52/31, cidr:104.198.14.52/32, cidr:104.198.8.0/21, cidr:64.0.0.0/2, cidr:96.0.0.0/3, cidr:96.0.0.0/4, reserved:w
orld] Ports: [0/ANY]                                                                                                                                                                           
                                                                                               
Resolving egress policy for [container:id=app2 container:maintainer=tgraf@tgraf.ch]                                                                                                            
* Rule {"matchLabels":{"any:id":"app2"}}: selected                                                                                                                                             
    Allows to labels {"matchLabels":{"reserved:world":""}}                                                                                                                                     
      Found all required labels                                                                                                                                                                
      Allows port [{53 ANY}]                                                                                                                                                                   
    Allows to labels {"matchLabels":{"reserved:none":""}}                                                                                                                                      
      No label match for [cidr:0.0.0.0/0 cidr:0.0.0.0/1 cidr:104.0.0.0/5 cidr:104.0.0.0/6 cidr:104.0.0.0/7 cidr:104.0.0.0/8 cidr:104.128.0.0/9 cidr:104.192.0.0/10 cidr:104.192.0.0/11 cidr:104
.192.0.0/12 cidr:104.192.0.0/13 cidr:104.196.0.0/14 cidr:104.198.0.0/15 cidr:104.198.0.0/16 cidr:104.198.0.0/17 cidr:104.198.0.0/18 cidr:104.198.0.0/19 cidr:104.198.0.0/20 cidr:104.198.12.0/2
2 cidr:104.198.14.0/23 cidr:104.198.14.0/24 cidr:104.198.14.0/25 cidr:104.198.14.0/26 cidr:104.198.14.32/27 cidr:104.198.14.48/28 cidr:104.198.14.48/29 cidr:104.198.14.52/30 cidr:104.198.14.5
2/31 cidr:104.198.14.52/32 cidr:104.198.8.0/21 cidr:64.0.0.0/2 cidr:96.0.0.0/3 cidr:96.0.0.0/4 reserved:world]                                                                                 
1/1 rules selected                                                                                                                                                                             
Found allow rule                                                                                                                                                                               
Egress verdict: denied                                                                                                                                                                         
                                                                                                                                                                                               
                                                                                                                                                                                               
Final verdict: DENIED
```

That said, this PR moves us closer to where we want to get to so I'm happy to merge as-is. I updated the PR description to state "Related-to" #9790 as it does not appear to fully resolve the CIDR case yet.

@wofanli Any status on the tests? Please do open a fresh PR for those changes if you are still working on them.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by aanm** [comment]
the jenkins build expired. re-triggering

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
