### PR TITLE
v1.7 backport 2020-07-21

### PR DESCRIPTION
**Pull request by jrfastab**
v1.7 backports 2020-07-21

 * #11620 -- Rework netns handling in LinuxRoutingSuite privileged tests (@christarazi)
 * #12440 -- Fix small CRD issue with toGroups (@lbernail)
 * #12457 -- refactor stringSlice type CLI arguments (@JieJhih)
 * #12470 -- pkg/k8s: use copy of objectmeta when fetching from local stores (@aanm)
 * #12461 -- datapath/linux: protect against concurrent access in NodeValidateImplementation (@tklauser)
 * #12515 -- .travis:fix up TestShuffle failure on Arm64 (@Jianlin-lv)
 * #12517 -- Adds documentation for limiting identity-relevant labels used when evaluating Cilium Identities (@seanmwinn)
 * #12529 -- bpf: explicitly set ttl in tunnel key (@borkmann)
 * #12532 -- docs(troubleshooting):  Remove bugtool related step with --serve flag (@sayboras)
 * #12524 -- endpoint: Write headerfile under full regeneration (@christarazi)
 * #12525 -- Clarify egress policy rule documentation (@joestringer)
 * #12559 -- bpf: Fix monitor aggregation for 'from-network' (@joestringer)
 * #12553 -- etcd: Fix session renewal controllers (@tgraf)
 * #12587 -- Fix etcd failure behavior when user or client context ends (@tgraf)

Notes:

 PR#12470: small conflict but looks fine to me. Please double-check
 PR#12461: small conflict on function signature.

 I've pulled two PRs for next round
      #12440 (how do we do version schemas on backports?)
      #12517 (to proof read doc changes if they still make sense in 1.7 context) 

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 11620 12457 12470 12461 12515 12529 12532 12524 12525 12559 12553 12587; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by jrfastab** [comment]
test-backport-1.7

**Review by christarazi — APPROVED** [review]
LGTM for my changes

**Comment by christarazi** [comment]
Looks like a go-bindata related failure.

**Comment by jrfastab** [comment]
test-backport-1.7

**Review by tklauser — APPROVED** [review]
👍 for my change

**Review by aanm — APPROVED** [review]
LGTM for my commits

**Comment by christarazi** [comment]
test-missed-k8s

**Pull request merged**
