### PR TITLE
envoy: Use patched image

### PR DESCRIPTION
**Pull request by jrajahalme**
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

```release-note
Envoy is updated to version 1.11.1
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8890)

### CODE REVIEW

**Comment by jrajahalme** [comment]
never-tell-me-the-odds

**Comment by jrajahalme** [comment]
never-tell-me-the-odds

**Comment by jrajahalme** [comment]
"kube-dns not ready"

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Kube-dns service not found: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2353/

The pod isn't even there. Perhaps this is a test ordering problem?

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
