### PR TITLE
hf: v1.12.0-rc0 + EgressGW & XDP fix

### PR DESCRIPTION
**Pull request by brb**

### CODE REVIEW

**Comment by borkmann** [comment]
Fixes: https://github.com/cilium/cilium/issues/17770

**Comment by brb** [comment]
> Fixes: https://github.com/cilium/cilium/issues/17770

@borkmann It doesn't fix for all cases. I.e., it doesn't fix for a case when iptables FORWARD chain's default policy is DROP.

**Comment by brb** [comment]
Closing, as https://github.com/cilium/cilium/pull/19587 should resolve it.

**Pull request closed without merging**
