### PR TITLE
bugtool: dump all active configs and encryption status

### PR DESCRIPTION
**Pull request by h3llix**
To be merged after #17303.

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]

**Review by ldelossa — COMMENTED** [review]
LGTM. Any initial ideal on how much larger this will make a sysdump size? Ok if not, but just curious.

**Comment by aanm** [comment]
ping @h3llix

**Comment by h3llix** [comment]
Hi @aanm @ldelossa. Sorry, for being inactive as I was busy with CSAW. I'll just have a look and inform.

**Comment by h3llix** [comment]
Earlier 5.1821MB, Now 5.1914MB. @ldelossa

**Pull request merged**
