### PR TITLE
v1.13: ariane: Run ci-ipsec-upgrade when testing backports

### PR DESCRIPTION
**Pull request by brb**

### CODE REVIEW

**Comment by brb** [comment]
/test-backport-1.13

**Review by qmonnet — APPROVED** [review]
First commit looks good. Second commit looks correct assuming we're OK with disabling IPv6 in CI for these tests.

**Review by nbusseneau — APPROVED** [review]

**Review by lmb — APPROVED** [review]

**Comment by lmb** [comment]
/test-backport-1.13

**Review by jschwinger233 — APPROVED** [review]

**Comment by lmb** [comment]
/test-1.21-4.19

**Pull request merged**
