### PR TITLE
bpf: fix sock6_xlate when not all host service protocols are enabled

### PR DESCRIPTION
**Pull request by borkmann**
See commit msg.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9847)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
amazing technology

**Comment by borkmann** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Comment by borkmann** [comment]
test-me-please

**Pull request merged**
