### PR TITLE
bpf: edt support for traffic egressing l7 proxy

### PR DESCRIPTION
**Pull request by borkmann**
WIP (not tested yet), setting release blocker to pick this up later but in scope for 1.9

TODO:
 - [ ] Waiting to rebase on top of https://github.com/cilium/cilium/pull/12976
 - [ ] CI tests for proxy
 - [ ] UDP specific drop horizon (SO_TXTIME)
 - [ ] Adjust readme graphic

### CODE REVIEW

**Review by jrajahalme — APPROVED** [review]
Looks good :-)

**Comment by joestringer** [comment]
From community meeting: We should release note this for v1.9.

**Comment by joestringer** [comment]
@borkmann are you still intending to follow up on this? Otherwise we can close this out.

**Comment by joestringer** [comment]
@borkmann how would you like to track this? This is the oldest draft PR in the tree, and it doesn't seem to be making progress. As long as we document the limitation and track this PR via an issue, I think it should be possible for someone interested in implementing this to pick up the PR and drive it over the finish line.

**Pull request closed without merging**
