### PR TITLE
cilium: enable bpf host routing with per endpoint routes for IPv6 as well

### PR DESCRIPTION
**Pull request by borkmann**
See commit descriptions.

### CODE REVIEW

**Comment by julianwiedmann** [comment]
For the ep-routes change, the original patch said

> In case of endpoint routes & host routing the IPv6 breaks, so enable host
> routing only for IPv4 case.  **One reason** is that the host can't populate
> neighbour entries for endpoints.  This happens because in case of endpoint
> routes ICMPv6 messages originate on [host] lxc veth devices. Those devices are
> only configured with IPv6 link-local addresses, so the ICMPv6 answer from the
> endpoint is sent to a link-local address which is recognized "world" by cilium,
> but fib_redirect can't redirect it (as it should be delivered to stack, not
> forwarded).

Given this lists just **one** reason - have all the other reasons been resolved by now? :)

**Comment by borkmann** [comment]
> For the ep-routes change, the original patch said
> 
> > In case of endpoint routes & host routing the IPv6 breaks, so enable host
> > routing only for IPv4 case.  **One reason** is that the host can't populate
> > neighbour entries for endpoints.  This happens because in case of endpoint
> > routes ICMPv6 messages originate on [host] lxc veth devices. Those devices are
> > only configured with IPv6 link-local addresses, so the ICMPv6 answer from the
> > endpoint is sent to a link-local address which is recognized "world" by cilium,
> > but fib_redirect can't redirect it (as it should be delivered to stack, not
> > forwarded).
> 
> Given this lists just **one** reason - have all the other reasons been resolved by now? :)

Good reminder, I'll check this out if its still the case and brainstorm what we could do about it.

**Review by zacharysarah — APPROVED** [review]
LGTM

**Review by qmonnet — APPROVED** [review]
Looks good, thank you!

**Review by aspsk — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Pull request merged**
