### PR TITLE
Microscope improvements on testing

### PR DESCRIPTION
**Pull request by eloycoto**
- Added WriteOrAppend helper function. 
- If Microscope is restarted in the middle of the test, the data will be saved. 
- Added Microscope in the update test before and after the image is updated. 
- Delete monitor.log if the test is successful

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4686)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4535/testReport/junit/k8s-1/7/K8sValidatedUpdates_Updating_Cilium_stable_to_master/

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4538/testReport/junit/k8s-1/7/K8sValidatedUpdates_Updating_Cilium_stable_to_master/

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Pull request merged**
