### PR TITLE
gha: Move to helm mode for aws-cni, eks, gke

### PR DESCRIPTION
**Pull request by sayboras**
### Description

Please refer to individual commits for more details.

Relates: https://github.com/cilium/cilium/issues/25156

### Testing

Testing was done with the temp commit, please find below the successful runs for each job:

- GKE: https://github.com/cilium/cilium/actions/runs/5143703162/jobs/9259050575?pr=25820
- AWS-CNI: https://github.com/cilium/cilium/actions/runs/5143703158/jobs/9259047353?pr=25820
- EKS: https://github.com/cilium/cilium/actions/runs/5143703175/jobs/9259139727?pr=25820

### CODE REVIEW

**Review by brb — APPROVED** [review]
ACK

**Review by nbusseneau — APPROVED** [review]
tl;dr

**Comment by sayboras** [comment]
Required reviews are in, changes are limited to GHA, full CI is not required. Marking this ready to merge.

**Pull request merged**
