### PR TITLE
[v1.11] vagrant: Bump 4.9 Vagrant box (Linux 4.9.326, to fix a kernel bug)

### PR DESCRIPTION
**Pull request by qmonnet**
- Manual backport of #21106,
  in the attempt of fixing #24394.

Fixes: #24394

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 21106; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
make add-labels BRANCH=v1.11 ISSUES=21106
```

### CODE REVIEW

**Comment by qmonnet** [comment]
/test-1.17-4.9

**Comment by qmonnet** [comment]
/test-1.17-4.9

**Comment by qmonnet** [comment]
/test-1.19-4.9

**Comment by qmonnet** [comment]
/test-1.20-4.9

**Comment by qmonnet** [comment]
/test-1.21-4.9

**Comment by qmonnet** [comment]
/test-1.23-4.9

**Comment by qmonnet** [comment]
/test-backport-1.11

**Comment by jrajahalme** [comment]
/test-backport-1.11

**Comment by jrajahalme** [comment]
/test-backport-1.11

**Comment by jrajahalme** [comment]
/test-1.17-4.9

**Comment by jrajahalme** [comment]
/test-1.20-4.9

**Comment by jrajahalme** [comment]
/test-1.21-4.9

**Comment by jrajahalme** [comment]
/test-1.21-5.4

**Comment by jrajahalme** [comment]
/test-1.23-4.9

**Comment by jrajahalme** [comment]
/test-1.18-4.9

**Comment by jrajahalme** [comment]
/test-1.23-4.9

**Comment by qmonnet** [comment]
/test-backport-1.11

**Comment by jrajahalme** [comment]
@qmonnet Added commit trying to avoid trying to re-mount the bpf file system.

**Comment by jrajahalme** [comment]
/test-backport-1.11

**Comment by qmonnet** [comment]
/test-1.19-4.9

**Comment by qmonnet** [comment]
Not sure why `Cilium L4LB XDP` didn't trigger, but it's not affected by the version of the Vagrant boxes anyway.

**Review by jrajahalme — APPROVED** [review]
LGTM

**Pull request merged**
