### PR TITLE
test: fix nightly upgrade test

### PR DESCRIPTION
**Pull request by aanm**
The order of the arguments are switched which makes the upgrade tests
from failing in the nightly tests.

Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10306)

### CODE REVIEW

**Comment by aanm** [comment]
test-focus NightlyExamples

**Comment by nebril** [comment]
test-focus NightlyExamples.*

**Comment by aanm** [comment]
@nebril it seems the upgrade tests failed with the following error:

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
cannot apply dempo application
Expected command: kubectl apply --force=false -f  
To succeed, but it failed:
Exitcode: 1 
Stdout:
 	 
Stderr:
 	 Error: flag needs an argument: 'f' in -f
	 See 'kubectl apply --help' for usage.
	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/Nightly.go:398
```

Is this because the nightly upgrade tests are not setting the demoPath string similar to the way it's done in https://github.com/cilium/cilium/blob/40657fa1ed98f10f90453b02cd69c67b6fce192b/test/k8sT/Updates.go#L62

**Comment by nebril** [comment]
test-nightly NightlyExamples.*

**Comment by nebril** [comment]
test-nightly NightlyExamples.*

**Comment by aanm** [comment]
test-nightly NightlyExamples.*

**Comment by nebril** [comment]
test-nightly NightlyExamples.*

**Comment by nebril** [comment]
test-nightly NightlyExamples.*

**Comment by nebril** [comment]
test-nightly NightlyExamples

**Comment by nebril** [comment]
test-nightly NightlyExamples

**Comment by nebril** [comment]
test-nightly NightlyExamples

**Comment by nebril** [comment]
test-nightly NightlyExamples

**Comment by nebril** [comment]
test-nightly NightlyExamples

**Comment by nebril** [comment]
test-nightly NightlyExamples

**Comment by nebril** [comment]
test-nightly NightlyExamples

**Comment by nebril** [comment]
test-nightly NightlyExamples

**Comment by nebril** [comment]
test-nightly NightlyExamples

**Comment by nebril** [comment]
test-nightly NightlyExamples

**Comment by nebril** [comment]
test-nightly NightlyExamples

**Comment by nebril** [comment]
test-nightly NightlyExamples

**Comment by nebril** [comment]
test-nightly NightlyExamples

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
hit a flake, rerunning regular tests

**Review by raybejjani — APPROVED** [review]

**Pull request merged**
