### PR TITLE
v1.4 backports 2019-02-27

### PR DESCRIPTION
**Pull request by joestringer**
## Backported

From #7212:
* #7207 -- endpoint: Fix and quieten endpoint revert logs (@joestringer)
* #7203 -- Get rid of JoinEP flakes (@brb)
* #7200 -- ctmap: Print source addresses in ctmap cli (@joestringer)

Newly backported here:

* #7213 -- endpoint: Fix ENABLE_NAT46 endpoint config validation (@brb)
   * Required minor fixups
* #7161 -- policy: Add missing import error metric calls (@mrostecki)
* #7214 -- pkg/kvstore: add 15 min TTL for the first session lease (@aanm)
* #7148 -- Fix policy drops on restart due to lack of kvstore sync (@tgraf)
* #7160 -- daemon: Track policy implementation delay by source (@raybejjani)
   * @raybejjani please review this closely, I had to rebase the function
     signature changes in daemon/policy.go and could easily have missed a
     patch dependency or broken something.
* #7217 -- workloads: Synchronous handling of container events (@tgraf)
* #7235 -- Improve backport workflow (sort PRs by merge date!) (@joestringer)

## Skipped

* #7163 -- Bump Go version to 1.11.5 (@brb)
* #7162 -- Add new C and Go struct alignment checker (@brb)
* #7210 -- bpf: Replace inline asm with call to BPF helper function (@brb)
   * I suspect that there may still be problems here with clang-3.8 not generating the symbols correctly.

## Post-merge

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 7207 7203 7200 7213  7161 7214 7148 7160 7217 7235; do contrib/backporting/set-labels.py $pr done 1.4; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7232)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

EDIT: bpf.sha breakage, fixing...

**Comment by joestringer** [comment]
test-docs-please

**Comment by joestringer** [comment]
test-me-please

EDIT: And this is why we need go modules (#5367)  - to make it easier to locally build/test before pushing backports!
```
00:44:52     runtime: ../pkg/metrics/metrics.go:151:14: undefined: Agent
00:45:25     runtime: Makefile:14: recipe for target 'cilium-agent' failed
00:45:25     runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/daemon'
00:45:25     runtime: make[1]: *** [cilium-agent] Error 2
00:45:25     runtime: Makefile:42: recipe for target 'daemon' failed
00:45:25     runtime: make: *** [daemon] Error 2
```

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Is this normal?

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10293/execution/node/79/log/

```
01:24:30     runtime: service 
01:24:30     runtime: Too few arguments.
01:24:30     runtime: service  failed
01:24:30     runtime: Too few arguments.
01:24:30     runtime: service  failed to restart
01:24:30     runtime: service sys-fs-bpf.mount
```

EDIT: Yes, this appears on successful build. Not related to current failure.

**Comment by nebril** [comment]
Seems like Cilium agent is not running in runtime tests in CI https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10293 , I will rerun tests to check if it's a flake.

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
Wow, that was not obvious:

If Cilium `Fatal()`s out at runtime, then the CI does not discover this and represent it in any way, it just results in all tests failing with no output in jenkins at all. Here's the log I found digging through the artifacts:
```
Feb 28 12:46:36 runtime cilium-agent[28595]: level=fatal msg="C and Go structs alignment check failed" error="C struct remote_endpoint_info not found" subsys=daemon
```

I opened #7244 to make this easier to debug in future.

**Comment by joestringer** [comment]
I dropped the alignchecker backport, not sure why it's not detecting the `remote_endpoint_info` struct in the alignchecker blob---maybe there's still some clang-3.8 issue we need to work through. Fixable, but we don't need to block 1.4 backports on fixing this up.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
test-docs-please

**Review by tgraf — APPROVED** [review]

**Review by aanm — APPROVED** [review]
LGTM for my backported commit

**Pull request merged**
