### PR TITLE
node: don't exclude IPs which is already included

### LINKED ISSUE #19926: Host address detect problem
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

host ip is resolved as world

1. use ipvs mode, and create a default deny netwokrpolicy
2. expose LB service, external ip is one of the node ip. ( will add the node ip to kube-ipvs0 device)
3. restart cilium , and cilium will not regard the node ip as host
4. this will break health chek for pods

this problem is lead to this code below

https://github.com/cilium/cilium/blob/82c742f2e9fb65fb3fc392c7dcb3b4e22b69c650/pkg/node/ip_linux.go#L16-L52

one solution is not add ip to excludedIPs ip which is already included.

### Cilium Version

v1.10.11

### Kernel Version

5.10.84-10.4.al8.x86_64

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:18Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by l1b0k**
This PR will not exclude ip which is already included. 

Signed-off-by: l1b0k <libokang.dev@gmail.com>

Fixes: #19926

```release-note
Fix node ip can't be recognized as host
```

### CODE REVIEW

**Comment by tommyp1ckles** [comment]
@l1b0k my apologies, this one slipped past me. I'm travelling currently but I'll try to take a look, I've also added more reviewers.

**Review by jibi — COMMENTED** [review]
Hey @l1b0k :wave: 

I'm wondering if we actually want to change the logic of `initExcludedIPs` to the one you proposed or if we are trying to solve the wrong issue :thinking: 

With these changes we won't add an IP to the excluded list if it's assigned to at least one "good" (i.e. UP and different than the docker one) interface, contrary to the current behavior where at least one "bad" interface is enough to add it to this list.

Could you share the IP addresses configuration of your setup?

**Comment by l1b0k** [comment]
> Hey @l1b0k 👋
> 
> I'm wondering if we actually want to change the logic of `initExcludedIPs` to the one you proposed or if we are trying to solve the wrong issue 🤔
> 
> With these changes we won't add an IP to the excluded list if it's assigned to at least one "good" (i.e. UP and different than the docker one) interface, contrary to the current behavior where at least one "bad" interface is enough to add it to this list.
> 
> Could you share the IP addresses configuration of your setup?

Hi @jibi 

```log
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:16:3e:0c:2b:07 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.188/24 brd 192.168.0.255 scope global dynamic noprefixroute eth0
       valid_lft 315055436sec preferred_lft 315055436sec
    inet6 fe80::216:3eff:fe0c:2b07/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:a5:da:5a:7b brd ff:ff:ff:ff:ff:ff
    inet 169.254.123.1/24 brd 169.254.123.255 scope global docker0
       valid_lft forever preferred_lft forever
4: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default
    link/ether 7e:51:ca:bc:21:19 brd ff:ff:ff:ff:ff:ff
    inet 172.16.24.177/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.22.162/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.152.215/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.0.1/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.244.12/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.0.10/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.39.31/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
5: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:16:3e:15:a1:0e brd ff:ff:ff:ff:ff:ff
    inet6 fe80::216:3eff:fe15:a10e/64 scope link
       valid_lft forever preferred_lft forever
6: cilium_net@cilium_host: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether c2:13:92:2f:ef:4e brd ff:ff:ff:ff:ff:ff
    inet6 fe80::c013:92ff:fe2f:ef4e/64 scope link
       valid_lft forever preferred_lft forever
7: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether da:24:57:02:e1:46 brd ff:ff:ff:ff:ff:ff
    inet 169.254.10.2/32 scope link cilium_host
       valid_lft forever preferred_lft forever
    inet6 fc00::10ca:1/128 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::d824:57ff:fe02:e146/64 scope link
       valid_lft forever preferred_lft forever
8: ipvl_5@eth1: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq state UNKNOWN group default qlen 1000
    link/ether 00:16:3e:15:a1:0e brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.188/32 scope host ipvl_5
       valid_lft forever preferred_lft forever
    inet6 fe80::16:3e00:215:a10e/64 scope link
       valid_lft forever preferred_lft forever


<- stack flow 0x69b65bf6 identity world->unknown state new ifindex eth0 orig-ip 0.0.0.0: 192.168.0.188:35028 -> 192.168.0.193:80 tcp SYN
Policy verdict log: flow 0x69b65bf6 local EP ID 547, remote ID world, proto 6, ingress, action deny, match none, 192.168.0.188:35028 -> 192.168.0.193:80 tcp SYN
xx drop (Policy denied) flow 0x69b65bf6 to endpoint 547, identity world->19780: 192.168.0.188:35028 -> 192.168.0.193:80 tcp SYN
<- stack flow 0x7fe19cf7 identity world->unknown state new ifindex eth0 orig-ip 0.0.0.0: 192.168.0.188:35028 -> 192.168.0.193:80 tcp SYN
Policy verdict log: flow 0x7fe19cf7 local EP ID 547, remote ID world, proto 6, ingress, action deny, match none, 192.168.0.188:35028 -> 192.168.0.193:80 tcp SYN
xx drop (Policy denied) flow 0x7fe19cf7 to endpoint 547, identity world->19780: 192.168.0.188:35028 -> 192.168.0.193:80 tcp SYN

```

```
# before change

127.0.0.1
::1
169.254.123.1
172.16.24.177
172.16.22.162
172.16.152.215
172.16.0.1
172.16.244.12
172.16.0.10
172.16.39.31
192.168.0.188  # <----
fe80::16:3e00:215:a10e


# after change

127.0.0.1
::1
169.254.123.1
172.16.24.177
172.16.22.162
172.16.152.215
172.16.0.1
172.16.244.12
172.16.0.10
172.16.39.31
fe80::16:3e00:215:a10e
```

for the single case, the problem is the way to determine link up status, 
but for expose node ip as externalIP  case, the node ip will set on kube-ipvs0 , and will always be excluded.

**Comment by jibi** [comment]
Looking at the logs it seems like `192.168.0.188` is assigned to 2 interfaces in either `UP` or `UNKNOWN` state:

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
```

```
8: ipvl_5@eth1: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq state UNKNOWN group default qlen 1000
```

So according to the `if l.Attrs().OperState == netlink.OperUp || l.Attrs().OperState == netlink.OperUnknown` logic that IP should not get added in any case to the list of excluded IPs :thinking: 

Could you please add an extra logline right after we loop over the slice of links to print the interface name and its operstate (something like `fmt.Printf("iface: %s, operstate: %d\n", l.Attrs().Name, l.Attrs().OperState)`) to understand why that check is failing?

**Comment by jibi** [comment]
> kube-ipvs0 have DOWN status

Make sense :+1: for context, I'm not necessarily opposed to this solution, I'm just trying to understand if it's something we should handle in the agent or if it's a sign of misconfiguration and so we should let the user sort their environment.

Is there a specific reason for having also `kube-ipvs0` with the node IP `192.168.0.188` assigned to while keeping that interface down?

**Comment by jibi** [comment]
@l1b0k as a first step could you please you rebase your branch on top of master so that I can rerun the CI?

**Pull request closed without merging**
