### PR TITLE
test/runtime: remove unused runtimeConnectivityTest

### PR DESCRIPTION
**Pull request by tklauser**
It's unused since commit 7fe5304748d7 ("test: Remove runtime ipvlan
tests") via PR #10145.

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Comment by tklauser** [comment]
test-with-kernel

**Comment by tklauser** [comment]
test-with-kernel

**Comment by errordeveloper** [comment]
@tklauser is this one ready to merge yet?

**Comment by tklauser** [comment]
@errordeveloper Yes, sorry forgot to check the build status and mark as `ready-to-merge`.

**Pull request merged**
