### PR TITLE
1.2 backports

### PR DESCRIPTION
**Pull request by tgraf**
* https://github.com/cilium/cilium/pull/5171
* https://github.com/cilium/cilium/pull/5170
* https://github.com/cilium/cilium/pull/5165
* https://github.com/cilium/cilium/pull/5159
* https://github.com/cilium/cilium/pull/5157
* https://github.com/cilium/cilium/pull/5146
* https://github.com/cilium/cilium/pull/5144
* https://github.com/cilium/cilium/pull/5125
* https://github.com/cilium/cilium/pull/5118
* https://github.com/cilium/cilium/pull/5115
* https://github.com/cilium/cilium/pull/5052
* https://github.com/cilium/cilium/pull/4928

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5175)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-upstream-k8s

**Comment by tgraf** [comment]
test-nightly

**Review by rlenglet — APPROVED** [review]

**Pull request merged**
