### PR TITLE
enabled initalDelaySeconds on StartupProbe to avoid needless spamming…

### LINKED ISSUE #28574: CFP: enable initalDelaySeconds on StartupProbe
Currently the helm release doesn't supply `initialDelaySeconds` which defaults to `0` but it would be useful to avoid spamming unnecessary `Warning` events to the api:

```
Started | Normal | Oct 12, 2023, 5:08:37 PM | Started container cilium-agent
Unhealthy | Warning | Oct 12, 2023, 5:08:37 PM | Startup probe failed: Get "http://127.0.0.1:9879/healthz": dial tcp 127.0.0.1:9879: connect: connection refused
Pulled | Normal | Oct 12, 2023, 5:08:36 PM | Container image "quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35" already present on machine
Created | Normal | Oct 12, 2023, 5:08:36 PM | Created container cilium-agent
Pulled | Normal | Oct 12, 2023, 5:08:35 PM | Container image "quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35" already present on machine
Created | Normal | Oct 12, 2023, 5:08:35 PM | Created container install-cni-binaries
Started | Normal | Oct 12, 2023, 5:08:35 PM | Started container install-cni-binaries
Pulled | Normal | Oct 12, 2023, 5:08:33 PM | Container image "quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35" already present on machine
Created | Normal | Oct 12, 2023, 5:08:33 PM | Created container clean-cilium-state
Started | Normal | Oct 12, 2023, 5:08:33 PM | Started container clean-cilium-state
Pulled | Normal | Oct 12, 2023, 5:08:31 PM | Container image "quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35" already present on machine
Created | Normal | Oct 12, 2023, 5:08:31 PM | Created container mount-bpf-fs
Started | Normal | Oct 12, 2023, 5:08:31 PM | Started container mount-bpf-fs
Started | Normal | Oct 12, 2023, 5:08:28 PM | Started container apply-sysctl-overwrites
Pulled | Normal | Oct 12, 2023, 5:08:27 PM | Container image "quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35" already present on machine
Created | Normal | Oct 12, 2023, 5:08:27 PM | Created container apply-sysctl-overwrites
Pulled | Normal | Oct 12, 2023, 5:08:26 PM | Container image "quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35" already present on machine
Created | Normal | Oct 12, 2023, 5:08:26 PM | Created container mount-cgroup
Started | Normal | Oct 12, 2023, 5:08:26 PM | Started container mount-cgroup
Created | Normal | Oct 12, 2023, 5:08:24 PM | Created container config
Started | Normal | Oct 12, 2023, 5:08:24 PM | Started container config
Pulled | Normal | Oct 12, 2023, 5:08:20 PM | Successfully pulled image "quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35" in 8.677826618s (8.677841669s including waiting)
Pulling | Normal | Oct 12, 2023, 5:08:12 PM | Pulling image "quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35"
Scheduled | Normal | Oct 12, 2023, 5:08:11 PM | Successfully assigned kube-system/cilium-45h7x to ip-10-208-83-146.ec2.internal
Started	Normal	Oct 12, 2023, 5:08:37 PM	Started container cilium-agent
Unhealthy	Warning	Oct 12, 2023, 5:08:37 PM	Startup probe failed: Get "[http://127.0.0.1:9879/healthz":](http://127.0.0.1:9879/healthz) dial tcp 127.0.0.1:9879: connect: connection refused
Pulled	Normal	Oct 12, 2023, 5:08:36 PM	Container image "quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35" already present on machine
Created	Normal	Oct 12, 2023, 5:08:36 PM	Created container cilium-agent
Pulled	Normal	Oct 12, 2023, 5:08:35 PM	Container image "quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35" already present on machine
Created	Normal	Oct 12, 2023, 5:08:35 PM	Created container install-cni-binaries
Started	Normal	Oct 12, 2023, 5:08:35 PM	Started container install-cni-binaries
Pulled	Normal	Oct 12, 2023, 5:08:33 PM	Container image "quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35" already present on machine
Created	Normal	Oct 12, 2023, 5:08:33 PM	Created container clean-cilium-state
Started	Normal	Oct 12, 2023, 5:08:33 PM	Started container clean-cilium-state
Pulled	Normal	Oct 12, 2023, 5:08:31 PM	Container image "quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35" already present on machine
Created	Normal	Oct 12, 2023, 5:08:31 PM	Created container mount-bpf-fs
Started	Normal	Oct 12, 2023, 5:08:31 PM	Started container mount-bpf-fs
Started	Normal	Oct 12, 2023, 5:08:28 PM	Started container apply-sysctl-overwrites
Pulled	Normal	Oct 12, 2023, 5:08:27 PM	Container image "quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35" already present on machine
Created	Normal	Oct 12, 2023, 5:08:27 PM	Created container apply-sysctl-overwrites
Pulled	Normal	Oct 12, 2023, 5:08:26 PM	Container image "quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35" already present on machine
Created	Normal	Oct 12, 2023, 5:08:26 PM	Created container mount-cgroup
Started	Normal	Oct 12, 2023, 5:08:26 PM	Started container mount-cgroup
Created	Normal	Oct 12, 2023, 5:08:24 PM	Created container config
Started	Normal	Oct 12, 2023, 5:08:24 PM	Started container config
Pulled	Normal	Oct 12, 2023, 5:08:20 PM	Successfully pulled image "quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35" in 8.677826618s (8.677841669s including waiting)
Pulling	Normal	Oct 12, 2023, 5:08:12 PM	Pulling image "quay.io/cilium/cilium:v1.14.2@sha256:6263f3a3d5d63b267b538298dbeb5ae87da3efacf09a2c620446c873ba807d35"
Scheduled	Normal	Oct 12, 2023, 5:08:11 PM	Successfully assigned kube-system/cilium-45h7x to ip-10-208-83-146.ec2.internal
```

It literally needed 1 more second to pass, so maybe a 5s delay being default wouldn't be so bad?

### PR DESCRIPTION
**Pull request by jignyasamishra**
Enabled initalDelaySeconds on StartupProbe to avoid needless spamming of warnings by adding initialDelaySeconds of '5' seconds inside StartupProbe which is present in https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml and https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/cilium-envoy/daemonset.y

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #28574 

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Review by gandro — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution to Cilium!

Three points of feedback:
- Would it make sense to make the initial delay configurable, i.e. use the same mechanism as `periodSeconds`?
- Please do not use merge commits in your branch, we cannot merge this as is. Please squash all your changes into a single commit using `git rebase`. 
- Please do not use overly long subject lines in git commit descriptions, it should ideally not be longer than 72 chars for the subject line

Thanks!

**Comment by jignyasamishra** [comment]
> * Would it make sense to make the initial delay configurable, i.e. use the same mechanism as `periodSeconds`?

@gandro Thank you so much for your feedback!! On the above point you mentioned i don't think it is necessasy to make initialDelaySeconds configurable because we just need few seconds of delay to avoid needless spamming of  warnings , making it configurable does not give any edge. As it is also mentiond in the isssue that bringing a delay of 1 sec is also good enough , 5 sec is to make sure that warnings passby.

**Comment by jignyasamishra** [comment]
@gandro I am extremely sorry for the inconvenience , there wa some issue in this branch while i was doing `git rebase` can i open another PR for this issue while closing this one ?

**Comment by gandro** [comment]
> @gandro I am extremely sorry for the inconvenience , there wa some issue in this branch while i was doing `git rebase` can i open another PR for this issue while closing this one ?

Sure!

**Pull request closed without merging**
