### PR TITLE
v1.13 Backports 2023-03-06

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
v1.13 backports 2023-03-06

 - [x] #24057 -- bugtool: Add ingress/egress tc filter dump (@joestringer)
 - [x] #24055 -- docs: Document CONFIG_PERF_EVENTS requirement (@joestringer)
 - [x] #23877 -- install: don't render role / rolebinding when agent disabled (@squeed)
 - [x] #23984 -- ingress: Bypass service count check (@sayboras)
 - [x] #24081 -- Hide `--install-iptables-rules` agent flag and remove `installIptablesRules` Helm flag (@pchaigno)
 - [x] #24106 -- bpf/Makefile: Cover VTEP in compile tests (@pchaigno)
 - [x] #24101 -- docs: Document kernel requirement for L3 devices support (@pchaigno)
 - [ ] #24116 -- cilium: Add TunnelDevice config helper to retrieve tunnel device name (@borkmann)
 - [x] #24127 -- bpf,test: Define BPF_TEST macro for map-in-map/prog-map initialization (@YutaroHayakawa)
 - [x] #24009 -- cni: add option to keep CNI configuration file on agent shutdown (@squeed)
 - [x] #24156 -- pkg/k8s: set the ciliumNodeStore as nil when connecting to KVStore (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 24057 24055 23877 23984 24081 24106 24101 24116 24127 24009 24156; do contrib/backporting/set-labels.py $pr done 1.13; done
```

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
/test-backport-1.13

**Review by pchaigno — APPROVED** [review]
My backports look good. Thanks!

**Review by aanm — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
LGTM and thanks :medal_military:

**Review by christarazi — APPROVED** [review]

**Review by brlbil — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
k8s-1.22-kernel-4.9: Known flake https://github.com/cilium/cilium/issues/20763
TravisCI: Known flake https://github.com/cilium/cilium/issues/23509

**Comment by YutaroHayakawa** [comment]
/test-1.22-4.9

**Comment by YutaroHayakawa** [comment]
/ci-datapath-1.13

**Review by squeed — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
/test-1.22-4.9

**Pull request merged**
