### PR TITLE
Disable the images digest when pushing the development helm chart

### PR DESCRIPTION
**Pull request by giorio94**
While the digests are unset and disabled in the main branch, they are set to the values corresponding to the latest patch release for stable branches. Hence, let's explicitly disable them when pushing the development helm chart.

Tested on top of the v1.14 branch (non-relevant images are omitted, the kvstoremesh image is configured in https://github.com/cilium/cilium/pull/27645, due to the different backport policy):

```
$ helm show values -n kube-system oci://quay.io/cilium-charts-dev/cilium \
        --version 1.15.0-dev-dev.748-pr-giorio94-main-gha-push-chart-digests-0a51d4c5b8| grep 'image:' -A7 -B1

# -- Agent container image.
image:
  override: ~
  repository: "quay.io/cilium/cilium-ci"
  tag: "0a51d4c5b82108ad6c3cb883c5b87b913a796fdb"
  pullPolicy: "Always"
  # cilium-digest
  digest: ""
  useDigest: false
--
    # -- Hubble-relay container image.
    image:
      override: ~
      repository: "quay.io/cilium/hubble-relay-ci"
      tag: "0a51d4c5b82108ad6c3cb883c5b87b913a796fdb"
      # hubble-relay-digest
      digest: ""
      useDigest: false
      pullPolicy: "Always"
--
  # -- Cilium pre-flight image.
  image:
    override: ~
    repository: "quay.io/cilium/cilium-ci"
    tag: "0a51d4c5b82108ad6c3cb883c5b87b913a796fdb"
    # cilium-digest
    digest: ""
    useDigest: false
    pullPolicy: "Always"
--
    # -- Clustermesh API server image.
    image:
      override: ~
      repository: "quay.io/cilium/clustermesh-apiserver-ci"
      tag: "0a51d4c5b82108ad6c3cb883c5b87b913a796fdb"
      # clustermesh-apiserver-digest
      digest: ""
      useDigest: false
      pullPolicy: "Always"


$ helm show values -n kube-system oci://quay.io/cilium-charts-dev/cilium \
        --version 1.15.0-dev-dev.748-pr-giorio94-main-gha-push-chart-digests-0a51d4c5b8| grep 'cilium-operator image' -A14

  # -- cilium-operator image.
  image:
    override: ~
    repository: "quay.io/cilium/operator"
    tag: "0a51d4c5b82108ad6c3cb883c5b87b913a796fdb"
    # operator-generic-digest
    genericDigest: ""
    # operator-azure-digest
    azureDigest: ""
    # operator-aws-digest
    awsDigest: ""
    # operator-alibabacloud-digest
    alibabacloudDigest: ""
    useDigest: false
    pullPolicy: "Always"
```

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
This one also triggered https://github.com/cilium/cilium/issues/27675, I don't really understand why. Is it because the base commit is earlier in the tree and somehow the test is only running a diff vs. `main`?

**Review by christarazi — APPROVED** [review]

**Comment by giorio94** [comment]
> This one also triggered #27675, I don't really understand why. Is it because the base commit is earlier in the tree and somehow the test is only running a diff vs. `main`?

Thanks for opening the issue! To be honest it is unclear to me why this didn't also happen on the original PR introducing the metric.

**Comment by giorio94** [comment]
Rebased onto main to fix a context, and re-tested

**Review by aanm — APPROVED** [review]

**Comment by giorio94** [comment]
Everything seems green. It's unclear to me why MLH didn't mark this as ready to merge. Doing that manually.

**Comment by giorio94** [comment]
I incorrectly though that this workflow had been backported to v1.12 and v1.13, but it appears not to exist in these branches. Hence, dropping the associated `needs-backport` labels.

**Pull request merged**
