### PR TITLE
test: Wait for POD readiness before test steps

### PR DESCRIPTION
**Pull request by jrajahalme**
Applying an L7 policy may make 'httpGet' readiness probes fail for the
duration the policy is in effect. Reduce test flakiness by waiting for
POD readiness before applying any policies in the individual test
steps.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-gke

**Comment by jrajahalme** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by errordeveloper** [comment]
I was looking into these flakes last week also, will see how it behaves now.

**Pull request merged**
