### PR TITLE
[v1.10] Backport 19153

### PR DESCRIPTION
**Pull request by christarazi**
[ upstream commit 6c5e2d66f3e3efcf9723c4cbb19d92ae80bcb1d7 ]

[ Backporter's notes: Needed to bump the Prometheus module in order to
                      make the upstream commit pass Go's mod checks. ]

Prometheus provides metrics collectors that expose go runtime and go build
information, which can be useful to server administrators, lets expose
them.

Signed-off-by: Chance Zibolski <chance.zibolski@gmail.com>
Signed-off-by: Chris Tarazi <chris@isovalent.com>

Backport of https://github.com/cilium/cilium/pull/19153

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 19153; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by christarazi** [comment]
/test-backport-1.10

**Review by aanm — APPROVED** [review]

**Comment by christarazi** [comment]
/test-1.20-4.19

**Comment by christarazi** [comment]
Marking ready to merge as we have approvals and CI has passed except for ci-awscni-1.10 which is broken for v1.10.x runs with the CLI due to the Helm-based install incompatibility.

**Comment by aanm** [comment]
/ci-awscni-1.10

**Comment by christarazi** [comment]
@aanm It passed. Ready to merge now?

**Comment by aditighag** [comment]
@christarazi The PR needs to be rebased.

**Comment by aanm** [comment]
@aditighag it's not required at this moment as we have a couple backport PRs open. We can merge all of them, if the CI is green, and them run a CI on a draft PR for the stable branch to double check if everything passes before doing a release.

**Pull request merged**
