### PR TITLE
Allow setting timeout on status command

### PR DESCRIPTION
**Pull request by ashrayjain**
```release-note
Allow setting timeout on cilium status command
```

We use `cilium status` as a liveness check and sometimes (due to other issues), the daemon can fail to respond to the health endpoint within a reasonable amount of time. If this is larger then the [liveness timeout of 5 seconds](https://github.com/cilium/cilium/blob/master/install/kubernetes/quick-install.yaml#L382) then this can cause the liveness check to timeout. 

In these scenarios, for exec liveness probes, the kubelet does not treat timeouts as failure. (It does do that for http/tcp liveness probes)

https://github.com/kubernetes/kubernetes/issues/82987 has more context on the k8s side.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9625)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by vadorovsky — CHANGES_REQUESTED** [review]
Hi @ashrayjain, thanks for your contribution! CI shows that there is an issue with `go format`:

```
14:58:34  contrib/scripts/check-fmt.sh
14:58:36  Unformatted Go source code:
14:58:36  ./cilium/cmd/status.go
14:58:36  diff -u ./cilium/cmd/status.go.orig ./cilium/cmd/status.go
14:58:36  --- ./cilium/cmd/status.go.orig	2019-11-18 13:58:35.965060181 +0000
14:58:36  +++ ./cilium/cmd/status.go	2019-11-18 13:58:35.965060181 +0000
14:58:36  @@ -57,7 +57,7 @@
14:58:36   	statusCmd.Flags().BoolVar(&allRedirects, "all-redirects", false, "Show all redirects")
14:58:36   	statusCmd.Flags().BoolVar(&brief, "brief", false, "Only print a one-line status message")
14:58:36   	statusCmd.Flags().BoolVar(&verbose, "verbose", false, "Equivalent to --all-addresses --all-controllers --all-nodes --all-health")
14:58:36  -	statusCmd.Flags().DurationVar(&timeout, "timeout", 30 * time.Second, "Sets the timeout to use when querying for health")
14:58:36  +	statusCmd.Flags().DurationVar(&timeout, "timeout", 30*time.Second, "Sets the timeout to use when querying for health")
14:58:36   	command.AddJSONOutput(statusCmd)
14:58:36   }14:58:34  contrib/scripts/check-fmt.sh
14:58:36  Unformatted Go source code:
14:58:36  ./cilium/cmd/status.go
14:58:36  diff -u ./cilium/cmd/status.go.orig ./cilium/cmd/status.go
14:58:36  --- ./cilium/cmd/status.go.orig	2019-11-18 13:58:35.965060181 +0000
14:58:36  +++ ./cilium/cmd/status.go	2019-11-18 13:58:35.965060181 +0000
14:58:36  @@ -57,7 +57,7 @@
14:58:36   	statusCmd.Flags().BoolVar(&allRedirects, "all-redirects", false, "Show all redirects")
14:58:36   	statusCmd.Flags().BoolVar(&brief, "brief", false, "Only print a one-line status message")
14:58:36   	statusCmd.Flags().BoolVar(&verbose, "verbose", false, "Equivalent to --all-addresses --all-controllers --all-nodes --all-health")
14:58:36  -	statusCmd.Flags().DurationVar(&timeout, "timeout", 30 * time.Second, "Sets the timeout to use when querying for health")
14:58:36  +	statusCmd.Flags().DurationVar(&timeout, "timeout", 30*time.Second, "Sets the timeout to use when querying for health")
14:58:36   	command.AddJSONOutput(statusCmd)
14:58:36   }
```

Please fix it and then most probably we will be able to accept your PR. `go format` checks should run locally every time you do `make` or `make precheck`.

**Comment by ashrayjain** [comment]
Fixed!

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Comment by ashrayjain** [comment]
@mrostecki could you please take a look here?

**Comment by ungureanuvladvictor** [comment]
previous run failed with a VM provisioning err at https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/15912/ 

test-me-please

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Review by soumynathan — COMMENTED** [review]
Looks good to me.

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Review by ungureanuvladvictor — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Review by gandro — APPROVED** [review]

**Review by jrfastab — APPROVED** [review]

**Pull request merged**
