### PR TITLE
Fix access from local host to node port via loopback IP

### PR DESCRIPTION
**Pull request by joestringer**
If a local application attempts to access a nodeport on the local node
via localhost/127.0.0.1, then both the source and destination of the
packet will be 127.0.0.1. The destination will be NATed to the
underlying pod's address, however if the source address is not NATed
then the traffic will arrive into the pod with the 127.0.0.1 source
address, which inside the pod will be considered the local network
namespace's loopback IP. As such, the responses to such requests will be
looped within the pod rather than being routed back out to the host.

Fix this by not clearing the k8s masquerade mark if the source address
is 127.0.0.1.

Fixes: #6381

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6482)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

EDIT: Testing that the test properly fails when localhost attempts to reach the nodeport on localhost (validate the bug exists on master).

Successful failure:
```
23:58:04 • Failure [184.934 seconds]
23:58:04 K8sServicesTest
23:58:04 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
23:58:04   K8sFoo Checks ClusterIP Connectivity
23:58:04   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
23:58:04     Checks service on same node [It]
23:58:04     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
23:58:04 
23:58:04     cannot curl to localhost nodeport from host
```

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Unless I'm missing something (eg the test is flawed), the approach here with the iptables rule doesn't achieve what we want it to.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Original solution of excluding traffic sourced from 127.0.0.1 in the masquerade clear bit rule in CILIUM_POST_mangle appears to work in local testing. The test addition here is not pinging the correct port, and it's not a nodeport either.

**Comment by joestringer** [comment]
test-me-please

EDIT: Green build.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
Great work

**Pull request merged**
