### PR TITLE
ci: Set PR build name

### PR DESCRIPTION
**Pull request by nebril**

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-focus K8sDemos.*

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-focus K8sDemos.*

**Review by raybejjani — APPROVED** [review]

**Comment by nebril** [comment]
test-focus K8sDemos.*

**Comment by nebril** [comment]
test-focus K8sDemos.*

**Pull request merged**
