### PR TITLE
v1.16 Backports 2024-12-16

### PR DESCRIPTION
**Pull request by pippolo84**
* [x] #36176 (@tamilmani1989)
 * [x] #36463 (@julianwiedmann) :warning: resolved conflicts
  - fixed minor conflict accepting incoming changes
 * [x] #36410 (@liyihuang)
 * [x] #36417 (@EricMountain) :warning: resolved conflicts
  - Fixed minor conflict due to a different handling of the `MODIFIERS` var in main, kept v1.16 approach.
 * [x] #36517 (@borkmann)
 * [x] #36549 (@verysonglaa)
 * [x] #36394 (@joamaki) :warning: resolved conflicts
  - Fixed minor conflicts due to `TrafficPolicy` field in `ServiceUpsertNotification` removed in main.
 * [x] #36558 (@liyihuang)
 * [x] #36466 (@joamaki) :warning: resolved conflicts
  - Minor conflicts due to different package for logging
  - Decreased number of expected deletes in `TestServiceEventDebounce`, as https://github.com/cilium/cilium/pull/33434 has not been backported and `ANY` protocol is not expected.

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 36176 36463 36410 36417 36517 36549 36394 36558 36466
```

### CODE REVIEW

**Comment by pippolo84** [comment]
/test-backport-1.16

**Review by julianwiedmann — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by borkmann — APPROVED** [review]

**Comment by pippolo84** [comment]
/test-backport-1.16

**Review by liyihuang — APPROVED** [review]

**Comment by pippolo84** [comment]
CI is green and enough reviews are in. I'll mark this as ready to merge.

**Pull request merged**
