### PR TITLE
feat(helm): allow setting resources for spire agent and server workloads

### PR DESCRIPTION
**Pull request by sjoukedv**
Added resources to the helm values for `authentication.mutual.spire.install.agent` and `authentication.mutual.spire.install.server`.

Replaces https://github.com/cilium/cilium/pull/34744

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Thank you!

**Review by mhofstetter — APPROVED** [review]
Thanks! :tada: 

Can you please squash the two commits into one (the second one seems to be the update of the generated docs)

**Comment by sjoukedv** [comment]
> Thanks! 🎉
> 
> Can you please squash the two commits into one (the second one seems to be the update of the generated docs)

I did with https://github.com/cilium/cilium/pull/34822

**Pull request closed without merging**
