### PR TITLE
CODEOWNERS: assign egressgw control plane/datapath logic to egress-gateway team

### PR DESCRIPTION
**Pull request by jibi**

### CODE REVIEW

**Comment by julianwiedmann** [comment]
Grep'ing around idly, some other candidates:

> /Documentation/network/egress-gateway.rst
> /pkg/k8s/watchers/cilium_egress_gateway_policy.go
> /pkg/k8s/apis/cilium.io/client/crds/v2/ciliumegressgatewaypolicies.yaml

**Review by julianwiedmann — APPROVED** [review]

**Review by ldelossa — APPROVED** [review]

**Review by zacharysarah — APPROVED** [review]
LGTM

**Comment by lmb** [comment]
You have a "real" failure: https://github.com/cilium/cilium/actions/runs/5610963082/job/15201538514?pr=26952#step:3:47

**Comment by lmb** [comment]
Can someone from @cilium/contributing take a look please.

**Review by pchaigno — APPROVED** [review]

**Pull request merged**
