### PR TITLE
test: disable policy enforcement in k8s tests

### PR DESCRIPTION
**Pull request by aanm**
As we are testing the policy enforcement in runtime tests there's no
point on testing this test in kubernetes as it causes network
disruption in the DNS pod. This network disruption might be causing test
failures in the following tests.

Signed-off-by: André Martins <andre@cilium.io>

Fixes: https://github.com/cilium/cilium/issues/3878
Fixes: https://github.com/cilium/cilium/issues/3803
Fixes: https://github.com/cilium/cilium/issues/4029
Fixes: https://github.com/cilium/cilium/issues/4720

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4708)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by eloycoto** [comment]
Please delete the code instead of comment it.

**Comment by aanm** [comment]
@eloycoto it is just a test, I'll delete it if we see it fixes the flake.

**Comment by aanm** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/453/
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4608/

not the dns issues at a first sight

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4623/
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/458/
green checks

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
Kafka pods not ready
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4633/testReport/junit/k8s-1/7/K8sValidatedKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

known bug #4715 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/459/

**Comment by aanm** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]

**Pull request merged**
