### PR TITLE
Don't modify route MTU but set MSS instead

### PR DESCRIPTION
**Pull request by lbernail**
Addresses https://github.com/cilium/cilium/issues/9112

Long term goal:
- detect kernel support for xfrm output mark
- use it for have a different mtu post encryption (in table 200)
- fallback to advmss for kernels that don't support it

cc @jrfastab

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9164)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by tgraf** [comment]
@lbernail Is this still needed? (cc @jrfastab)

**Comment by lbernail** [comment]
@tgraf Now that we have output-mark support we can close this one

**Pull request closed without merging**
