### PR TITLE
v1.14 Backports 2023-10-06

### PR DESCRIPTION
**Pull request by sayboras**
* [ ] ~#27323 (@michaelasp)~
    * :warning: conflict with test files 
    * dropped this one as we might need https://github.com/cilium/cilium/pull/24677 (cc @joamaki, who is PR author and next week backporter)
 * [x] #28358 (@gandro)
 * [x] #28258 (@pchaigno)
 * [x] #28357 (@sayboras)
 * [x] #28380 (@aanm)
 * [x] #28392 (@giorio94)
 * [x] #28294 (@nxy7)
 * [ ] ~#28388 (@haiyuewa)~
 * [ ] #28403 (@raphink)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 28358 28258 28357 28380 28392 28294 28403; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=28358,28258,28357,28380,28392,28294,28403
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.14

**Review by aanm — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
My commit looks good, thanks!

**Comment by haiyuewa** [comment]
Hi @sayboras  , My commit depends on: https://github.com/cilium/cilium/commit/d4d7ff4282a274b8e60ea2c41c1834703961375a

It is not in 1.14 branch:

https://github.com/cilium/cilium/blob/v1.14/Documentation/network/servicemesh/gateway-api/installation.rst

vs

https://github.com/cilium/cilium/blob/main/Documentation/network/servicemesh/gateway-api/installation.rst

**Comment by sayboras** [comment]
ah thanks a lot, I will remove backport label from your PR.

**Comment by sayboras** [comment]
/test-backport-1.14

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by gandro — APPROVED** [review]

**Comment by sayboras** [comment]
Most of the reviews are in, CI is green, let's merge it in.

**Pull request merged**
