### PR TITLE
policy: Simplify generation of L4 BPF keys

### PR DESCRIPTION
**Pull request by joestringer**
An L4 policy, with or without L7 policy, can be represented as a single
BPF key which wildcards the identity (by specifying it as 0), and
specifying the port/protocol/direction for the key. Previously this code
synthesised L3-dependent L4 keys for every identity in the system, which
could cause an explosion of BPF map keys when L4-only or L4+L7 policies
are in use, and would inject delays for allowing traffic on the L4 port
when new identities appear on remote nodes.

Improve this by only generating the single L4-only BPF key when L4
policy is in use. This will reduce the number of keys generated (saving
policymap key space and CPU for iteration), and also make the policy
more resilient during creation and deletion of identities, as the policy
will apply regardless of whether identities have propagated across the
cluster.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7439)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Want to ensure that #7437 goes in first so that we can actually run the unit tests.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Sorry for re-triggering tests - I thought travis would run if I triggered the CI, but it appears that it isn't triggered for draft PRs. #7437 is merged, so you should be good to go!

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Hit also #7443. Otherwise green, please review.

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
