### PR TITLE
k8s: Fix envoyConfig description on CNP/CCNP CRDs

### PR DESCRIPTION
**Pull request by hmonsalv**
Fixes a typo on the `envoyConfig` description of `CiliumNetworkPolicy` and `CiliumClusterwideNetworkPolicy` K8s CRDs definitions.

### CODE REVIEW

**Review by aanm — CHANGES_REQUESTED** [review]
Thank you for the changes, however these two files are automatically generated. The right place to change should be [here](https://github.com/cilium/cilium/blob/58b67dc281544ff463d4c92c0fe5444feebf731b/pkg/policy/api/l4.go#L142-L143) and then you need to generate the yamls with `make manifests`

**Review by aanm — APPROVED** [review]

**Comment by nathanjsweet** [comment]
@hmonsalv Can you squash these commits. Thanks.

**Review by nathanjsweet — APPROVED** [review]

**Comment by nathanjsweet** [comment]
LGTM, pending git changes.

**Comment by ldelossa** [comment]
@hmonsalv this PR is good to go, final request is to squash the two commits into one.

**Comment by hmonsalv** [comment]
Commits squashed ;)

**Review by youngnick — APPROVED** [review]

**Comment by hmonsalv** [comment]
@nathanjsweet anything else pending here from my side?

**Comment by youngnick** [comment]
Since this is effectively only a docs change, I think this is ready to merge?

**Comment by dylandreimerink** [comment]
On the one hand its only doc changes, on the other we have 4 CI checks that have massive failures which don't go a away on a retry. Can we rebase this branch on main in case that solves it?

**Pull request merged**
