### PR TITLE
Re-enable k8s 1.11 and disable k8s 1.12 tests

### PR DESCRIPTION
**Pull request by aanm**
Check commits for more context.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4757)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by tgraf** [comment]
What changed since we had to revert? Almost every k8s test failed with 1.11 before.

**Comment by aanm** [comment]
@tgraf was the failures related with 1.11 or with our flakes? I'll defer to @eloycoto if we are missing anything. But if the tests have a green pass in this PR I don't see any reason why we shouldn't merge it.

**Comment by tgraf** [comment]
@aanm I'm happy to merge this if we can verify this PR with 5 consecutive green builds.

**Comment by eloycoto** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4702/testReport/junit/k8s-1/11/K8sValidatedTunnelTest_Geneve_Check_Geneve_mode/

Endpoints are not ready after timeout, let me trigger again.

**Comment by eloycoto** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4723/ seems to have been a problem from k8s that didn't retry to create the pod after finding out `cilium-cni` didn't exist

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by eloycoto** [comment]
LGTM, I'll approve when test pass.

**Comment by aanm** [comment]
ginkgo tests were hit by https://github.com/cilium/cilium/issues/4843

k8s tests passed except the k8s 1.8.15 which was requiring a new CNI version. Already change the provisioning to have a newest version of CNI for k8s 1.8.15.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
ginkgo tests were hit again by https://github.com/cilium/cilium/issues/4843

Reverted the k8s upgrade to 1.8.15 as the packaging is broken. Will update to k8s 1.8.15 once the packaging is fixed upstream.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
missed-k8s-tests had 2 green builds.

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/533/
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/537/

ginkgo test had a failure being tracked here https://github.com/cilium/cilium/issues/4847

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
unable to provision k8s 1.8 https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/546/flowGraphTable/

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
@eloycoto can you look at this failure? https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4998/ it seems `kubectl apply` was not perform correctly for Cilium DS with the geneve option. Better yet, it seems the previous Cilium DS was not removed.

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
@aanm please ping me for review once the tests have stabilized; I am in agreement with @tgraf that we need consecutive stable builds for this to be validated.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/4850

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/4879

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
green https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5056/

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test missed k8s got a "NACK" test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
previous missed k8s got a NACK again

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/4879

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/4879 again

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
@eloycoto @ianvernon ping for review

**Review by eloycoto — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by joestringer** [comment]
@ianvernon was this backported to 1.1? I don't see any reference from a backport PR and the label still says pending.

**Pull request merged**
