### PR TITLE
1.3 backports 19 01 14

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:

*  https://github.com/cilium/cilium/pull/6624
*  https://github.com/cilium/cilium/pull/6636
* https://github.com/cilium/cilium/pull/6611
*  https://github.com/cilium/cilium/pull/6586
*  https://github.com/cilium/cilium/pull/6575
*  https://github.com/cilium/cilium/pull/6570
*  https://github.com/cilium/cilium/pull/6568

Signed-off by: Ian Vernon <ian@cilium.io>

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6641)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Unrelated issue with build infrastructure occurred:

Link: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9032/

Relevant output:
```
02:09:53 ==> k8s1-1.12: Booting VM...
02:09:55 ==> k8s1-1.12: Waiting for machine to boot. This may take a few minutes...
02:09:55     k8s1-1.12: SSH address: 127.0.0.1:2203
02:09:55     k8s1-1.12: SSH username: vagrant
02:09:55     k8s1-1.12: SSH auth method: private key
02:10:18     k8s1-1.12: Warning: Connection reset. Retrying...
02:10:18     k8s1-1.12: Warning: Remote connection disconnect. Retrying...
02:10:18     k8s1-1.12: Warning: Connection reset. Retrying...
02:10:18     k8s1-1.12: Warning: Remote connection disconnect. Retrying...
02:10:18     k8s1-1.12: Warning: Connection reset. Retrying...
02:10:20     k8s1-1.12: 
02:10:20     k8s1-1.12: Vagrant insecure key detected. Vagrant will automatically replace
02:10:20     k8s1-1.12: this with a newly generated keypair for better security.
02:10:20     k8s1-1.12: 
02:10:20     k8s1-1.12: Inserting generated public key within guest...
02:10:20     k8s1-1.12: Removing insecure key from the guest if it's present...
02:10:20     k8s1-1.12: Key inserted! Disconnecting and reconnecting using new SSH key...
02:10:22 ==> k8s1-1.12: Machine booted and ready!
02:10:22 ==> k8s1-1.12: Checking for guest additions in VM...
02:10:22 ==> k8s1-1.12: Setting hostname...
02:10:22 ==> k8s1-1.12: Configuring and enabling network interfaces...
02:15:10 Sending interrupt signal to process
02:15:20 After 10s process did not stop
```

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Hit the same issue again: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9052/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Green build: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9053/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by aanm — APPROVED** [review]
LGTM for my changes

**Comment by ianvernon** [comment]
Cilium-Ginkgo-Tests failed:

Endpoint build failed in runtime tests:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9057/testReport/junit/(root)/runtime/RuntimeChaos_Endpoint_recovery_on_restart/

```
Jan 15 20:44:24 runtime cilium-agent[25162]: level=warning msg="JoinEP: Failed to load program" containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=44773 error="Failed to load tc filter: exit status 2" file-path=44773_next/bpf_lxc.o ipv4=10.15.58.189 ipv6="f00d::a0f:0:0:aee5" k8sPodName=/ subsys=datapath-loader veth=cilium_health
```

Looks like the health endpoint and its network namespace is removed while it is being regenerated? : 

```
Jan 15 20:44:24 runtime cilium-agent[25162]: level=info msg="Killing old process" pid=25703 pidfile=/var/run/cilium/state/health-endpoint.pid subsys=pidfile
Jan 15 20:44:24 runtime cilium-agent[25162]: level=debug msg="Didn't find existing cilium-health endpoint to delete" endpointID=44773 subsys=daemon
Jan 15 20:44:24 runtime cilium-agent[25162]: level=info msg=Killed netns=cilium-health subsys=cilium-health-launcher
Jan 15 20:44:24 runtime cilium-agent[25162]: level=debug msg="Created veth pair" subsys=endpoint-connector vethPair="[cilium cilium_health]"
Jan 15 20:44:24 runtime cilium-agent[25162]: level=error msg="Command execution failed" cmd="[tc filter replace dev cilium_health ingress prio 1 handle 1 bpf da obj 44773_next/bpf_lxc.o sec from-container]" error="exit status 2" subsys=datapath-loader
Jan 15 20:44:24 runtime cilium-agent[25162]: level=warning msg="RTNETLINK answers: Invalid argument" subsys=datapath-loader
Jan 15 20:44:24 runtime cilium-agent[25162]: level=warning msg="We have an error talking to the kernel" subsys=datapath-loader
Jan 15 20:44:24 runtime cilium-agent[25162]: level=debug msg="Endpoint creation" code=OK containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=44773 endpointState=waiting-for-identity ipv4= ipv6= k8sPodName=/ policyRevision=0 subsys=endpoint type=0
```

Long-lived TCP connections test failed as well due to JoinEP found in logs, and failing controllers for the health endpoint:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9057/testReport/junit/k8s-1/8/K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts/

```
⚠️  Found a 'JoinEP: ' in logs
Number of 'context deadline exceeded' in logs: 0
Number of 'level=error' in logs: 3
Number of 'level=warning' in logs: 5
Number of 'Cilium API handler panicked' in logs: 0
⚠️  Number of 'Goroutine took lock for more than' in logs: 25
Cilium pods: [cilium-7z7tz cilium-qgvp5]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
     kube-dns-6f4c8dbcd4-nscsn          =>   none
     prometheus-core-5c9fbf5cc6-5pfrs   =>   none
     netperf-client                     =>   none
     netperf-server                     =>   none
     cilium-etcd-2qlgw5rzzg             =>   none
     cilium-etcd-nhjlfb9g22             =>   none
     cilium-etcd-zdbvrdv4lr             =>   none
     etcd-operator-8b5cbb6d6-zxkk7      =>   none
⚠️  Cilium agent 'cilium-7z7tz': Status: Ok  Health: Ok Nodes "k8s2 k8s1" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 41 Failed 1
Failed controllers:
 controller cilium-health-ep failure 'unable to transition health endpoint to WaitingToRegenerate state'
Cilium agent 'cilium-qgvp5': Status: Ok  Health: Warning Nodes "k8s1 k8s2" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 36 Failed 0
Failed controllers:
 controller cilium-health-ep failure 'unable to transition health endpoint to WaitingToRegenerate state'
```

Similar error as with the runtime tests:
```
2019-01-15T21:17:54.308236257Z level=error msg="Command execution failed" cmd="[tc filter replace dev cilium_health ingress prio 1 handle 1 bpf da obj 8395_next/bpf_lxc.o sec from-container]" error="exit status 2" subsys=datapath-loader
2019-01-15T21:17:54.308263354Z level=warning msg="RTNETLINK answers: No such device" subsys=datapath-loader
2019-01-15T21:17:54.308266677Z level=warning msg="We have an error talking to the kernel, -1" subsys=datapath-loader
2019-01-15T21:17:54.312725249Z level=warning msg="JoinEP: Failed to load program" containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=8395 error="Failed to load tc filter: exit status 2" file-path=8395_next/bpf_lxc.o ipv4=10.10.0.204 ipv6="f00d::a0a:0:0:20cb" k8sPodName=/ subsys=datapath-loader veth=cilium_health
```

The health endpoint regeneration logs are related to one of the backports around setting health state, so I will investigate.

**Comment by ianvernon** [comment]
K8s tests failed too :/ 

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1502/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
The cilium-health failures occur because the health endpoint is added into the endpoint manager, but the state transition to `waiting-to-regenerate` fails. The controller returns with an error, which then causes the health endpoint cleanup code to be invoked. But, while we are compiling BPF for the endpoint, it is deleted, including its network namespace, which causes `tc` to fail:

Health endpoint first regeneration occurs due to identity being changed, which is explicitly performed in `LaunchAsEndpoint`:

```
2019-01-15T23:13:13.555241286Z level=debug msg="Dequeued endpoint from build queue" containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:13.55536746Z level=info msg="Regenerating endpoint" containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ reason="updated security labels" startTime="2019-01-15 23:13:13.555189898 +0000 UTC m=+7.039896703" subsys=endpoint
2019-01-15T23:13:13.555631867Z level=debug msg="Regenerating endpoint: updated security labels" code=OK containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3109 endpointState=regenerating ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ policyRevision=0 subsys=endpoint type=0
```

Health endpoint added, but state transition fails:
```
2019-01-15T23:13:13.655831458Z level=info msg="New endpoint" containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:13.655842294Z level=debug msg="Skipped invalid state transition to waiting-to-regenerate due to: initial build of health endpoint" code=Warning containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3109 endpointState=waiting-to-regenerate ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ policyRevision=0 subsys=endpoint type=0
2019-01-15T23:13:13.655897191Z level=debug msg="Controller func execution time: 1.075233568s" name=cilium-health-ep subsys=controller uuid=2014787e-191b-11e9-92c3-080027b66966
2019-01-15T23:13:13.655901802Z level=debug msg="Controller run failed" consecutiveErrors=2 error="unable to transition health endpoint to WaitingToRegenerate state" name=cilium-health-ep subsys=controller uuid=2014787e-191b-11e9-92c3-080027b66966
```

Compilation occurring:
```
2019-01-15T23:13:14.595783447Z level=debug msg="Preparing to compile BPF" bpfHeaderfilesChanged=true containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
```

Cleanup logic is invoked:
```
2019-01-15T23:13:15.656502213Z level=debug msg="Didn't find existing cilium-health endpoint to delete" endpointID=3109 subsys=daemon
2019-01-15T23:13:15.668277462Z level=info msg=Killed netns=cilium-health subsys=cilium-health-launcher
```

Regeneration failure occurs:
```
019-01-15T23:13:15.852749593Z level=warning msg="JoinEP: Failed to load program" containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=3109 error="Failed to load tc filter: exit status 2" file-path=3109_next/bpf_lxc.o ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=datapath-loader veth=cilium_health
2019-01-15T23:13:15.852860626Z level=info msg="Recompiled endpoint BPF program" BPFCompilationTime=1.257049604s containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=3109 error="Failed to load tc filter: exit status 2" ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:15.852944422Z level=error msg="Restoring endpoint state after BPF regeneration failed" containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:15.853022881Z level=debug msg="Reverting proxy redirect removals" containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:15.853085551Z level=debug msg="Finished reverting proxy redirect removals" containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:15.853157167Z level=debug msg="Reverting proxy redirect additions" containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:15.853248594Z level=debug msg="Finished reverting proxy redirect additions" containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:15.853892885Z level=error msg="Finished restoring endpoint state after BPF regeneration failed" containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:15.854141421Z level=warning msg="generating BPF for endpoint failed, keeping stale directory." containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=3109 file-path=3109_next_fail ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:15.854298951Z level=debug msg="removing directory" containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=3 directory=3109_next_fail endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:15.854410747Z level=debug msg="removing directory" containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=3 directory=3109_next endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:15.855940844Z level=debug msg="Completed endpoint regeneration with no pending regeneration requests" code=OK containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=3109 endpointState=ready ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ policyRevision=0 subsys=endpoint type=0
2019-01-15T23:13:15.856258442Z level=warning msg="Regeneration of endpoint failed" bpfCompilation=1.257049604s buildDuration=2.30090898s containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=3109 error="Failed to load tc filter: exit status 2" ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ mapSync="102.875µs" policyCalculation="309.91µs" prepareBuild=19.471848ms proxyConfiguration="6.037µs" proxyPolicyCalculation=1.367805ms proxyWaitForAck=0s reason="updated security labels" subsys=endpoint waitingForCTClean=19.011691ms waitingForLock=1.017748471s
2019-01-15T23:13:15.856452404Z level=debug msg="Error regenerating endpoint: Failed to load tc filter: exit status 2" code=Failure containerID=cilium-loc datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=3109 endpointState=ready ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ policyRevision=0 subsys=endpoint type=200
2
```


The reason the regeneration is already occurring is because we are changing its identity upon bootstrap, which triggers a regeneration before the health endpoint is inserted into the endpointmanager. When we try to regenerate the endpoint again in `LaunchAsEndpoint`, the health endpoint is in an invalid state to transition to `waiting-to-regenerate`, and we fail, causing the endpoint to be deleted. I think this issue may occur in v1.4 and master as well, but we are insulated from it due to subtle timing differences (possibly because regeneration is faster in those branches).

Now to figure out what the fix for this is...

**Comment by tgraf** [comment]
@ianvernon Does the health endpoint controller not recover and compile it successfully afterwards?

**Comment by ianvernon** [comment]
@tgraf yes, the endpoint controller recovers correctly and it is compiled successfully after this initial failure:

```
2019-01-15T23:13:18.135110078Z level=debug msg="BPF header file hashed (was: \"928041ad94ff35a918806db7b4bbc18b\")" bpfHeaderfileHash=928041ad94ff35a918806db7b4bbc18b containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:18.135112417Z level=debug msg="Preparing to compile BPF" bpfHeaderfilesChanged=false containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:18.135114534Z level=debug msg="BPF header file unchanged, skipping BPF compilation and installation" bpfHeaderfileHash=928041ad94ff35a918806db7b4bbc18b containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:18.135116725Z level=debug msg="Waiting for proxy updates to complete..." containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:18.13511881Z level=debug msg="Wait time for proxy updates: 10.724µs" containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:18.135121034Z level=debug msg="Finalizing successful endpoint regeneration" containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:18.135124772Z level=debug msg="synchronizing directories" containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:18.13512702Z level=debug msg="endpoint directory exists; backing it up" containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:18.135129101Z level=debug msg="removing directory" containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 directory=3109_stale endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:18.135131178Z level=debug msg="moving current directory to backup location" backupDirectory=3109_stale containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ originalDirectory=/var/run/cilium/state/3109 subsys=endpoint
2019-01-15T23:13:18.135133363Z level=debug msg="compilation was skipped; moving old BPF objects into new directory" containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:18.135135455Z level=debug msg="removing directory" containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 directory=3109_next_fail endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:18.135137471Z level=debug msg="removing directory" containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 directory=3109_stale endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:18.135143286Z level=debug msg="removing directory" containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 directory=3109_next endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ subsys=endpoint
2019-01-15T23:13:18.135145666Z level=debug msg="Completed endpoint regeneration with no pending regeneration requests" code=OK containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=3109 endpointState=ready ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ policyRevision=3 subsys=endpoint type=0
2019-01-15T23:13:18.135147902Z level=info msg="Completed endpoint regeneration" bpfCompilation=0s buildDuration=1.098469143s containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=3109 ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ mapSync="120.937µs" policyCalculation="541.475µs" prepareBuild="398.279µs" proxyConfiguration="4.879µs" proxyPolicyCalculation="686.667µs" proxyWaitForAck="16.077µs" reason="health daemon bootstrap" subsys=endpoint waitingForCTClean=322ns waitingForLock="204.678µs"
2019-01-15T23:13:18.13515092Z level=debug msg="Successfully regenerated endpoint program (Reason: health daemon bootstrap)" code=OK containerID=cilium-loc datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=3109 endpointState=ready ipv4=10.10.1.158 ipv6="f00d::a0a:100:0:c25" k8sPodName=/ policyRevision=3 subsys=endpoint type=200
```

**Comment by ianvernon** [comment]
I think that we should have logic where we do not regenerate the endpoint when we are first setting its identity if it is the health endpoint, and instead exit from the function which sets the identity. This would ensure that we are not concurrently regenerating the health endpoint while we are adding it into the endpointmanager.

**Comment by ianvernon** [comment]
@tgraf trying out my above suggestion here: https://github.com/cilium/cilium/pull/6659/commits/247c099731b855ae17573cfbe0c26c1becfe2604

**Comment by tgraf** [comment]
@ianvernon make sense

**Comment by ianvernon** [comment]
@tgraf 
https://github.com/cilium/cilium/pull/6659 passed with the proposed change. This affects v1.3 of Cilium and not v1.4 or master because we defer regeneration of endpoints until they are added into the endpointmanager in those versions of cilium, but not in v1.3, which is why this bug occurred here and not in master. I've added it as another commit to this branch. This may need backporting to v1.2 as well, although the CI did not fail in the PR with the createEndpoint changes.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Review by tgraf — APPROVED** [review]

**Comment by ianvernon** [comment]
K8s 1.10 tests failed due to microscope being in a bad state:
```
Events:
  Type     Reason                 Age                 From               Message
  ----     ------                 ----                ----               -------
  Normal   Scheduled              23m                 default-scheduler  Successfully assigned microscope to k8s2
  Normal   SuccessfulMountVolume  23m                 kubelet, k8s2      MountVolume.SetUp succeeded for volume "microscope-token-j9c6k"
  Normal   Pulled                 23m                 kubelet, k8s2      Container image "docker.io/cilium/microscope:1.1.2-ci" already present on machine
  Normal   Created                23m                 kubelet, k8s2      Created container
  Normal   Started                23m                 kubelet, k8s2      Started container
  Warning  Unhealthy              3m (x240 over 23m)  kubelet, k8s2      Readiness probe failed: Exception encountered: KeyError('identity') stack trace below

closing
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/bin/microscope/__main__.py", line 156, in <module>
  File "/bin/microscope/__main__.py", line 150, in main
  File "/bin/microscope/__main__.py", line 138, in main
  File "/bin/microscope/microscope/monitor/runner.py", line 99, in run
  File "/bin/microscope/microscope/monitor/epresolver.py", line 43, in __init__
  File "/bin/microscope/microscope/monitor/epresolver.py", line 43, in <listcomp>
KeyError: 'identity'
```

I think we should disable microscope in the v1.3 CI. The change is non-invasive, and will reduce build times in the branch. Running the tests again to see if the issue reproduces for K8s 1.10.

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Build failure due to VM boot timeout: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1522/

**Comment by ianvernon** [comment]
test-missed-k8s

**Pull request merged**
