### PR TITLE
v1.4 backports 2019-04-24

### PR DESCRIPTION
**Pull request by joestringer**
* #7835 -- operator: add ca-certificates to operator (@aanm)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 7835; do contrib/backporting/set-labels.py $pr done 1.4; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7842)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Comment by joestringer** [comment]
Hit what looks like a variation on #6347, and #5645.

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11860/testReport/junit/(root)/Suite-runtime/RuntimePolicyImportTests_checks_policy_trace_output/

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:408
Expected allowed identities [26235 46688], but instead got [46688 26235]
Expected
    <[]int64 | len:2, cap:2>: [26235, 46688]
to equal
    <[]int64 | len:2, cap:4>: [46688, 26235]
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/runtime/Policies.go:2011
```

[73a61006_RuntimePolicyImportTests_checks_policy_trace_output.zip](https://github.com/cilium/cilium/files/3114703/73a61006_RuntimePolicyImportTests_checks_policy_trace_output.zip)

These seem like flakes, I'll just kick the CI again.

**Comment by joestringer** [comment]
test-me-please

**Comment by brb** [comment]
test-docs-please

**Pull request merged**
