### PR TITLE
v1.14 Backports 2023-07-26

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #26721 (@julianwiedmann)
 * [x] #26736 (@julianwiedmann)
 * [x] #26857 (@julianwiedmann)
 * [x] #27002 (@michi-covalent)
 * [x] #27014 (@qmonnet)
 * [x] #27066 (@michi-covalent)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 26721 26736 26857 27002 27014 27066; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=26721,26736,26857,27002,27014,27066
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
Note for maintainers:

After merge, the following checks will need to be unmarked as required on `v1.14`:

- Runtime Test (agent)
- Runtime Test (datapath)
- Runtime Test (privileged)
- gateway-api-conformance-test (experimental)
- gateway-api-conformance-test (standard)
- ingress-conformance-test (With Default Ingress Controller, disabled, dedicated, true)
- ingress-conformance-test (With Shared LB, disabled, shared, false)
- ingress-conformance-test (With XDP, native, dedicated, false)
- ingress-conformance-test (Without XDP, disabled, dedicated, false)
- integration-test

And the following checks will need to be marked as required instead:

- Cilium Runtime
- ConformanceGatewayAPI
- ConformanceIngress
- IntegrationTests

**Review by qmonnet — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]
i guess we need to update branch protection rules for v1.14 once this PR gets merged? cc @joestringer

**Comment by michi-covalent** [comment]
are i missed your comment. you are way ahead of me 🥰

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Merged and applied the new branch protection settings. Thanks!

**Pull request merged**
