### PR TITLE
helm: Correct spire labels indentation

### LINKED ISSUE #28599: Helm chart: broken spire setup
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```
authentication:
  enabled: true
  mutual:
    spire:
      enabled: true
      install:
        enabled: true
        agent:
          labels:
            k8s-app: cilium-spire-agent
        server:
          labels:
            k8s-app: cilium-spire-server
```

Setting `labels` as above will break the helm install with:

```
Error: YAML parse error on cilium/templates/spire/agent/daemonset.yaml: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context
```

### Cilium Version

1.14.2

### Kernel Version

-

### Kubernetes Version

-

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

Not setting labels will allow helm install to happen.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sayboras**
Fixes: #28599

```release-note
fix: Correct spire labels identation in helm chart
```

### CODE REVIEW

**Review by meyskens — APPROVED** [review]
Good catch! LGTM

**Review by squeed — APPROVED** [review]

**Comment by joestringer** [comment]
@sayboras Could you add a release note to the PR description? Glancing over the changes it looks like it's fixing the labels for SPIRE deployments, so it may be helpful to better highlight that in the release note.

**Comment by sayboras** [comment]
> Could you add a release note to the PR description? Glancing over the changes it looks like it's fixing the labels for SPIRE deployments, so it may be helpful to better highlight that in the release note.

Thanks and done :+1:

**Comment by joestringer** [comment]
@sayboras ah, what I meant is that for a user "fixing the indentation" doesn't declare what the side effects are. If this is a cosmetic change then there's no need to backport and it's not a bugfix. If this ensures that when the user configures the feature with setting X or Y, it actually works, then we should document the user impact that way so that users can understand exactly which configurations are affected and decide if the bug is related to their problem or not. And in that case yeah it makes sense to backport this to 1.14.

**Pull request merged**
