### PR TITLE
hubble: Add kafka metrics

### PR DESCRIPTION
**Pull request by chancez**
Adds Kafka metrics to hubble. 

```release-note
hubble: Add kafka metrics
```

### CODE REVIEW

**Review by michi-covalent — COMMENTED** [review]
maybe we can include api key (e.g. `Produce`, `Fetch`, etc.) as a label. there are only ~20 api calls so it shouldn't be too bad:

https://kafka.apache.org/0101/protocol.html#protocol_api_keys

**Comment by chancez** [comment]
@michi-covalent Good idea. I also removed the error codes from the histogram because it's probably not needed (can be overlayed with the requests metric) and will increase cardinality potentially too much. I did add Apikey to the histogram though.

**Review by michi-covalent — APPROVED** [review]
🚀

**Review by michi-covalent — APPROVED** [review]
approving it again because i like it so much

**Review by nebril — APPROVED** [review]

**Comment by rolinh** [comment]
test-runtime

**Review by qmonnet — APPROVED** [review]

**Comment by rolinh** [comment]
test-runtime

**Pull request merged**
