### PR TITLE
policy: avoid marshalling L4Filter with indent

### PR DESCRIPTION
**Pull request by odinuge**
This code path is very hot since hubble fetch the
/v1/endpoint and /v1/endpoint/{ID} endpoints very often. When having a
lot of policy rules, the output of those, and all the cascading buffers
used to marshal and generate the result grow very big, and cause a lot
of memory pressure.

Since this is encoded down to a string in a struct, later marshalled
without indentation, there isn't really any need to add the extra
white spaces and newlines.

The outout of the json deep into the L4Filter struct looks like this;
````
'      {\n        \"dns\": [\n          {\n            \"matchName\": \"domain.tld\"\n          }\n        ]\n      }'
````
And with this change, it will look like this;
````
'{\"dns\":[{\"matchName\":\"domain.tld\"}]}'
````
That is a reduction from 110 characters to only 42, a more than 60%
decrease. Since this data flows through multiple buffers, the actual
saving will be even longer. We saw the output of the /v1/endpoint
be reduced by almost 50% from ~20MiB to ~10MiB with this change.

Signed-off-by: Odin Ugedal <ougedal@palantir.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Fixes: #issue-number

```release-note
Improve memory usage for encoding endpoint objects into JSON
```

^ Do you want me to add a release note to this change?

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]
Nice find! LGTM.

**Comment by joestringer** [comment]
> ^ Do you want me to add a release note to this change?

This is fine. Maybe for a more user-focused release-note it would say something like "improve memory usage for encoding endpoint objects into JSON".

**Comment by aanm** [comment]
@odinuge it looks the unit tests are failing because of these changes https://app.travis-ci.com/github/cilium/cilium/builds/253195570

**Comment by odinuge** [comment]
Oooh, yee, you are right @aanm, thanks! It looks legit as well. Will fix!

**Review by jrajahalme — APPROVED** [review]
Assuming the unit test(s) get fixed :-)

**Comment by odinuge** [comment]
Thanks all! Sorry for missing that obvious test.. Made the test compare with the compacted json, and it passes locally when running `(cd pkg/policy; go test -check.v -check.vv)`.

**Review by joestringer — APPROVED** [review]
LGTM. Running the full CI just in case something happens to be concerned with the indentation vs. not, but I don't expect anything to pop out from that.

**Comment by odinuge** [comment]
Its not clear to me that the test failures are due to this change.. Can we rerun them to check @joestringer?

Thanks

**Comment by joestringer** [comment]
@odinuge scanning through the first link on all of those failures, one test consistently fails across all jobs. That suggests this is not a flake.

**Comment by odinuge** [comment]
Hmm, I see. Thanks!

The errors seems similar to these; https://github.com/cilium/cilium/issues/16122

With erros like these;
```
/home/jenkins/workspace/Cilium-PR-K8s-1.23-kernel-4.19/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:527
Failed to reach 192.168.56.12:80 from testclient-27jkk
Expected command: kubectl exec -n 202208042322k8sdatapathconfighostfirewallwithnativeroutinganden testclient-27jkk -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 [http://192.168.56.12:80/](http://192.168.56.12/) -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Err: exit status 28
Stdout:
 	 time-> DNS: '0.000018()', Connect: '0.000000',Transfer '0.000000', total '5.001379'
Stderr:
 	 command terminated with exit code 28
	 

/usr/local/go/src/runtime/asm_amd64.s:1571
```

I'll keep digging and see if I find any reason for it..

**Comment by odinuge** [comment]
Been digging a bit today as well, but can't really see how this change can cause those tbh. Under the hood `json.MarshalIndent` will call `json.Marshal`, then add some spaces and newlines, so functionally, it should be 1:1...  Rebased now, so let's see how that works. I don't have perms to start all the test suites tho.

**Comment by joestringer** [comment]
Logically I agree, the only gap would be if somehow the way that the test verifies something relies on the formatting of this output somehow (eg grep across lines rather than processing the json correctly). I've re-kicked CI to gather feedback again.

**Comment by odinuge** [comment]
Thanks!

They all look better now, and most of them are passing, except;
- Some timeout in `runtime (test-runtime)`, and I think that one passed in the previous run
- Some new fails in `k8s-1.16-kernel-4.9`. The tests that failed last time are now succeeding, and now some other tests are failing. Since the other suites pass, I assume this is a flake. (https://github.com/cilium/cilium/issues/20793)

I'm out a few weeks, but will check back when I'm back

Thanks
Odin

**Comment by joestringer** [comment]
/test-1.16-4.9

**Comment by joestringer** [comment]
/test-1.16-4.9

**Comment by odinuge** [comment]
> EDIT: It looks like it has been too long since the images were generated from this PR, so the images were cleaned up & the latest CI run could not pull the images.

Ack. Rebased and pushed a new version now

**Comment by odinuge** [comment]
Thanks @aanm! All boxes are green now, so it looks like all the previous errors were flakes

**Comment by odinuge** [comment]
Thanks @joestringer!

Will this be cherry-picked to previous releases, or will we have to do that on our internal fork instead?

**Comment by joestringer** [comment]
Typically the Cilium community would not automatically backport a change like this, as it's not considered a bugfix - see [here](https://docs.cilium.io/en/stable/contributing/release/backports/#backport-criteria) for the backport criteria. That said, depending on the risk/benefit of the specific change, we could be open to accepting a backport on older releases.

**Pull request merged**
