### PR TITLE
1.2 Backports 2018-08-17

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5244)

### CODE REVIEW

**Review by joestringer — APPROVED** [review]
Looks good, though I note that you've signed off as:

`Signed-off-by: vagrant <thomas@cilium.io>`

**Comment by tgraf** [comment]
Thanks, will fix

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Green build, pulled in #5243, running CI again

**Comment by tgraf** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]

**Pull request merged**
