### PR TITLE
WIP add bpftool output for LB maps to bugtool

### PR DESCRIPTION
**Pull request by brb**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8082)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
No longer relevant.

**Pull request closed without merging**
