### PR TITLE
docs: Fix multiple broken links

### PR DESCRIPTION
**Pull request by errordeveloper**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10576)

### CODE REVIEW

**Comment by errordeveloper** [comment]
test-docs-please

**Review by joestringer — APPROVED** [review]

**Comment by errordeveloper** [comment]
Some links are not passing the link checker tests right now and I'm not sure how to fix these, perhaps we could instruct the checker to ignore these somehow?

Anchors work fine in the browser, but not in the link checker:

```
(line   35) broken    https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-quick-configuration - Anchor 'cli-quick-configuration' not found
(line   19) broken    https://github.com/kubernetes-sigs/kubespray#requirements - Anchor 'requirements' not found
```

Commands that contain URL substrings:

```
(line   32) broken    https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname - 404 Client Error: Not Found for url: https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname
(line   39) broken    https://github.com/kubernetes/kops/releases/download/$(curl - 404 Client Error: Not Found for url: https://github.com/kubernetes/kops/releases/download/$(curl
```


This one needs auth:
```(line   41) broken    https://github.com/cilium/cilium/projects/new - 404 Client Error: Not Found for url: https://github.com/cilium/cilium/projects/new
```

We also have a few localhost links like this:
```
(line   42) broken    http://localhost:9080 - HTTPConnectionPool(host='localhost', port=9080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31cddb0d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
(line  238) broken    http://127.0.0.1:15000/logging?level=debug - HTTPConnectionPool(host='127.0.0.1', port=15000): Max retries exceeded with url: /logging?level=debug (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31ce248bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by errordeveloper** [comment]
test-docs-please

**Comment by errordeveloper** [comment]
@joestringer I think it would be good to merge as-is, happy to open follow-up issue to look into other broken links and long-term CI strategy for this :)

**Pull request merged**
