### PR TITLE
hubble: Remove pod-short metrics context option

### PR DESCRIPTION
**Pull request by ghost**
This option was deprecated in 1.13 release and should be removed in 1.14.

```release-note
The deprecated pod-short context option in Hubble metrics is now removed
```

### CODE REVIEW

**Review by zacharysarah — APPROVED** [review]
LGTM from a docs perspective

**Review by chancez — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
This seems pretty low-risk and was something we intend to take care of for 1.14 anyway. I expect sig-hubble-api should not take long, happy to grant an exception to feature freeze for this change. Marked accordingly.

**Review by rolinh — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
