### PR TITLE
v1.12 Backports 2023-07-24

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #25038 (@pchaigno)
 * [x] #26808 (@pchaigno)
 * [x] #26933 (@nbusseneau)
 * [x] #26934 (@michi-covalent)
 * [x] #26979 (@pchaigno)

PRs skipped due to conflicts:

 * #26455 (@alan-kut)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 25038 26808 26933 26934 26979; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=25038,26808,26933,26934,26979
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
@michi-covalent @pchaigno Please see backporter's notes for each commit, conflicts arised due to file renames.

**Comment by nbusseneau** [comment]
/test-backport-1.12

**Review by michi-covalent — APPROVED** [review]
🥰

**Review by pchaigno — APPROVED** [review]
My changes look good. Thanks!

**Comment by nbusseneau** [comment]
- 1.16 / 4.9 hit both #25721 and #24840.
- 1.19 / 4.9 hit #25721 as well.

The backport only targets docs and tests themselves, and the unquarantined test passed, the 2 failures above cannot be introduced by this PR. Marking `ready-to-merge`.

**Review by youngnick — APPROVED** [review]

**Comment by youngnick** [comment]
Looks like there are some conflicts @nbusseneau.

**Comment by nbusseneau** [comment]
Indeed, #27059 got merged first so I lost the race here (unlike on v1.13, where I won and now Quentin has to deal with it, hehe). It's only very a minor Documentation conflict though (spelling wordlist...), so no need to re-run the full CI for this. Documentation checks have passed, marking `ready-to-merge`.

**Pull request merged**
