### PR TITLE
k8s: update k8s to 1.19.0-rc.4

### PR DESCRIPTION
**Pull request by aanm**
Skip tests that are currently failing in the upstream k8s tests and add
the reason for why they are being skipped.

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Review by michi-covalent — APPROVED** [review]

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Comment by tklauser** [comment]
All tests except GKE passed (Scaling cluster failed: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/2121/), merging.

**Pull request merged**
