### PR TITLE
docs: Mark host-policies as tech preview

### PR DESCRIPTION
**Pull request by joestringer**
The Cilium v1.8 blog describes this feature as tech preview, make sure
the docs are consistent with this.

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
What's the difference between beta and tech preview? We have header for both now.

**Comment by joestringer** [comment]
I was wondering about that myself, we should come up with criteria and define what these mean :-)

**Comment by Rolinh** [comment]
Should we also apply this change to doc that refer to Hubble Relay? It's also "tech preview". I think the doc currently mentions it's "beta" but this generic warning seems better.

**Review by michi-covalent — APPROVED** [review]

**Comment by joestringer** [comment]
@Rolinh filed https://github.com/cilium/cilium/issues/12280 to follow up on this. I think it'd be good to have a discussion on what we mean when we use these terms and how we decide to apply them.

**Review by qmonnet — APPROVED** [review]

**Pull request merged**
