### PR TITLE
Backports for 1.5.2 - 2019-05-17

### PR DESCRIPTION
**Pull request by tgraf**
* PR: 8010 -- daemon/Makefile: rm -f on make clean for links (@aanm) -- https://github.com/cilium/cilium/pull/8010
 * PR: 8037 -- datapath: Redo backend selection if stale CT_SERVICE entry is found (@brb) -- https://github.com/cilium/cilium/pull/8037
 * PR: 8013 -- test/provision: bump k8s testing to v1.13.6 (@aanm) -- https://github.com/cilium/cilium/pull/8013
 * PR: 8057 -- pkg/ipcache: initialize globalmap at import time (@aanm) -- https://github.com/cilium/cilium/pull/8057
 * PR: 8066 -- pkg/endpoint: fix assignment in nil map on restore (@aanm) -- https://github.com/cilium/cilium/pull/8066
 * PR: 8059 -- bpf: redo regular ct entry upon service collision (@borkmann) -- https://github.com/cilium/cilium/pull/8059

```
$ for pr in 8010 8037 8013 8057 8066 8059; do contrib/backporting/set-labels.py $pr pending 1.5; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8070)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
Failure showed up in vxlan+IPsec data path config test:

```
Failed controllers:
 controller cilium-health-ep failure 'unable to build health endpoint'
```

**Comment by brb** [comment]
> Failure showed up in vxlan+IPsec data path config test:

Failed due to:

```
2019-05-17T01:06:55.060442817Z level=warning msg="Prog section '2/10' rejected: Invalid argument (22)!" subsys=datapath-loader
2019-05-17T01:06:55.060491972Z level=warning msg=" - Type:         3" subsys=datapath-loader
2019-05-17T01:06:55.060558632Z level=warning msg=" - Attach Type:  0" subsys=datapath-loader
2019-05-17T01:06:55.060610112Z level=warning msg=" - Instructions: 4139 (43 over limit)" subsys=datapath-loader
2019-05-17T01:06:55.060678785Z level=warning msg=" - License:      GPL" subsys=datapath-loader
2019-05-17T01:06:55.060727046Z level=warning subsys=datapath-loader
2019-05-17T01:06:55.060802258Z level=warning msg="Verifier analysis:" subsys=datapath-loader
2019-05-17T01:06:55.060857606Z level=warning subsys=datapath-loader
2019-05-17T01:06:55.06095174Z level=warning msg="Error filling program arrays!" subsys=datapath-loader
2019-05-17T01:06:55.0610088Z level=warning msg="Unable to load program" subsys=datapath-loader
2019-05-17T01:06:55.062221184Z level=warning msg="JoinEP: Failed to load program" containerID=f6bb431fad datapathPolicyRevision=0 desiredPolicyRevision=30 endpointID=2514 error="Failed to load tc filter: exit status 1" file-path=2514_next/bpf_lxc.o identity=101 ipv4=10.10.0.141 ipv6="f00d::a0a:0:0:9406" k8sPodName=kube-system/cilium-etcd-lq2p6v7r49 subsys=datapath-loader veth=lxcb387726937e5
```

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
Hit #7721

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.14-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
DNS connectivity of www.google.com from pod "app2-55cdf7cd56-ww77m"
Expected command: kubectl exec -n default app2-55cdf7cd56-ww77m -- host www.google.com 
To succeed, but it failed:
Exitcode: 1 
Stdout:
 	 ;; connection timed out; no servers could be reached
	 
Stderr:
 	 command terminated with exit code 1
```

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Backported 61ad2c6b1fc to decrease # instruction

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
61ad2c6  actually increase the number of instructions again, dropped backport

**Comment by tgraf** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Pull request merged**
