### PR TITLE
images: update cilium-{runtime,builder}

### PR DESCRIPTION
**Pull request by joestringer**
Fix master after the merge of https://github.com/cilium/cilium/pull/22565.

Fixes: https://github.com/cilium/cilium/pull/22565

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by joestringer** [comment]
Awaiting our :robot: overlords to complete the PR: https://github.com/cilium/cilium/actions/runs/3944818161/jobs/6751121941

**Comment by joestringer** [comment]
Our overlord's overlords got impatient and cancelled the automated action: https://github.com/cilium/cilium/actions/runs/3944818161

> https://github.com/cilium/cilium/actions/runs/3944818161

**Comment by joestringer** [comment]
Given that the runtime and builder images were pushed, I've just manually updated the commit.

**Comment by joestringer** [comment]
Already got Andre's review, and this fixes master. Merging.

**Pull request merged**
