### PR TITLE
v1.4 Backports 2019-01-29

### PR DESCRIPTION
**Pull request by joestringer**
* #6772
* #6818
* #6829
* #6834
* #6837

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6851)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
Previous [Cilium-Ginkgo-Test-k8s](https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1578/) has failed due to https://github.com/cilium/cilium/issues/6059#issuecomment-458967926.

**Review by tgraf — APPROVED** [review]

**Pull request merged**
