### PR TITLE
v1.12 backports 2022-07-13

### PR DESCRIPTION
**Pull request by ldelossa**
v1.12 backports 2022-07-13

 * #20378 -- images, contrib/coccinelle: update alpine image to 3.16.0 (@tklauser)
 * #16499 -- docs: Document clustermesh datapath configuration for non-tunneled modes (@jrajahalme)
 * #20408 -- docs: fix flags for 1.12 branch (@aanm)
 * #19533 -- Use '.Values.enableIPv4Masquerade' in 'node-init' (@bmcustodio)
 * #20389 -- daemon: Fix issue where stale router IPs were not cleaned up (@gandro)
 * #20404 -- Add metric to track terminating endpoint events (@aditighag)
 * #18384 -- istio: Update to release 1.10.6 (@jrajahalme)
 * #20209 -- bpf: switch egress gateway logic to identity_is_cluster() (@jibi)
 * #20420 -- ci: pick up cilium-cli v0.11.11 for master, v1.11 and v1.12 workflows (@tklauser)
 * #16179 -- daemon: Don't auto disable session affinity (@brb)
 * #20417 -- Documentation: Restart cilium-operator and cilium after enabling Service Mesh (@chancez)
 * #20353 -- operator: start the event queue in a dedicated go routine (@aanm)
 * #20082 -- helm: Make DNS policy for agent and operator configurable (@michi-covalent)
 * #20403 -- docs: Update docs with minimum helm version (@aditighag)
 * #20363 -- endpointmanager: Add extra check for out-of-range endpoint IDs (@twpayne)
 * #20332 -- test/helpers: Fix variadic expansion related panic (@christarazi)
 * #20305 -- dnsproxy: update dnsproxy benchmark memory calculation (@odinuge)
 * #20296 -- Add Peer Service to Cilium DS Port List (@nathanjsweet)
 * #20251 -- Fix the bugs when empty CiliumEndpointSlices were created and leaked. (@alan-kut)
 * #20239 -- docs: Add example how to config ipmasq via ConfigMap (@brb)
 * #20416 -- Documentation: Only install 1 replica of operator on k3s (@chancez)
 * #20430 -- install/kubernetes: do not initialize variable twice (@aanm)
 * #20433 -- pkg/metrics: Remove source node label (@aditighag)
 * #20440 -- Disable Envoy version check if L7 proxy is disabled (@bmcustodio)
 * #20442 -- docs: Fixed service list command in clustermesh affinity guide (@dylandreimerink)
 * #20421 -- docs: L7 traffic management getting started guide (@sayboras)
 * #20406 -- docs: Add CLI installation for ServiceMesh (@sayboras)
 * #20461 -- test/k8s/manifests: bump test-verifier image to latest version (@tklauser)
 * #20473 -- config: Fix unit tests for native routing CIDR (@pchaigno)
 * #20376 -- Add Prometheus gRPC metrics for hubble and hubble-relay (@chancez)
 * #20387 -- Aspsk/pr/better error reporting for cilium monitor (@aspsk)
 * #20428 -- docs: Add troubleshooting docs for Ingress (@sayboras)
 * #20407 -- bpf: Handle tuple collisions for inactive backends (@borkmann)
 * #20446 -- hubble/parser/threefour: check (*Parser).linkGetter before accessing it (@tklauser)
 * #20486 -- docs: Bump up Netlify Python version to 3.8 (@michi-covalent)
 * #20413 -- bgp: fixed PodCIDR announcement being overwritten by SVC announcement (@dylandreimerink)
 * #20481 -- docs: Fix update-spelling_wordlist.sh to run command on spelling errors (@qmonnet)
 * #20471 -- Improve Egress Gateway Getting Started Guide (@pippolo84)
 * #20507 -- update k8s versions to the latest releases (@aanm)
 * #20521 -- bgp: Fixed broken bgp speaker unit tests (@dylandreimerink)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20378 16499 20408 19533 20389 20404 18384 20422 20209 16179 20417 20353 20082 20403 20363 20332 20305 20296 20251 20239 20416 20430 20433 20440 20442 20421 20406 20461 20473 20376 20387 20428 20407 20446 20486 20413 20481 20471 20507 20420 20521; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by christarazi — APPROVED** [review]

**Review by aditighag — APPROVED** [review]
My changes look good! Thanks!

**Review by chancez — APPROVED** [review]
My changes look good

**Review by aanm — APPROVED** [review]
My changes LGTM thank you!

**Comment by ldelossa** [comment]
/test-backport-1.12

**Comment by ldelossa** [comment]
@dylandreimerink travis CI failure on this backport PR seems to revolve around BGP changes.

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                                         

┃   PANIC  package: github.com/cilium/cilium/pkg/bgp/speaker • TestSpeakerOnUpdateNode   ┃                                                         

┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                                                         

panic: runtime error: invalid memory address or nil pointer dereference                                                                            

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x185dbd6]                                                                            

                                                                                                                                                   

goroutine 54 [running]:                                                                                                                            

github.com/cilium/cilium/pkg/bgp/mock.(*MockMetalLBSpeaker).GetBGPController(0xc00014f490?)                                                        

	/home/travis/gopath/src/github.com/cilium/cilium/pkg/bgp/mock/mock.go:38 +0x16                                                                     

github.com/cilium/cilium/pkg/bgp/speaker.(*MetalLBSpeaker).announcePodCIDRs(0xc0003c5620, {0xc0004028d0, 0x1, 0x1})                                

	/home/travis/gopath/src/github.com/cilium/cilium/pkg/bgp/speaker/pod_cidr.go:84 +0x131                                                             

github.com/cilium/cilium/pkg/bgp/speaker.(*MetalLBSpeaker).handleNodeEvent(0xc0003c5620, {{{0x0, 0x0}, 0x1}, 0x2, 0xc000010a40, 0xc0001287b0, 0x0})

	/home/travis/gopath/src/github.com/cilium/cilium/pkg/bgp/speaker/events.go:231 +0x445                                                              

github.com/cilium/cilium/pkg/bgp/speaker.(*MetalLBSpeaker).do(0xc0003c5620, {0x1b423c0?, 0xc0005f1b40?})                                           

	/home/travis/gopath/src/github.com/cilium/cilium/pkg/bgp/speaker/events.go:187 +0x496                                                              

github.com/cilium/cilium/pkg/bgp/speaker.(*MetalLBSpeaker).run(0xc0003c5620, {0x1f5a938, 0xc0003c5560})                                            

	/home/travis/gopath/src/github.com/cilium/cilium/pkg/bgp/speaker/events.go:114 +0x1e9                                                              

created by github.com/cilium/cilium/pkg/bgp/speaker.TestSpeakerOnUpdateNode                                                                        

	/home/travis/gopath/src/github.com/cilium/cilium/pkg/bgp/speaker/speaker_test.go:368 +0x470                                                        

FAIL	github.com/cilium/cilium/pkg/bgp/speaker	0.035s             `
```
https://app.travis-ci.com/github/cilium/cilium/jobs/576612745

Did this slip through that initial PR?

**Review by gandro — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]

**Review by tklauser — COMMENTED** [review]
> * [ci: pick up cilium-cli v0.11.11 for master, v1.11 and v1.12 workflows #20420](https://github.com/cilium/cilium/pull/20420) -- ci: pick up cilium-cli v0.11.11 for master, v1.11 and v1.12 workflows (@tklauser)

I didn't find this change on the backport branch. The backport will need some adjustment because some workflow files are only present on `master`. See https://github.com/cilium/cilium/pull/20420#issuecomment-1184190101

My other changes look good. Thank you.

**Review by sayboras — APPROVED** [review]
Looks good for my changes, thanks :100:

**Comment by dylandreimerink** [comment]
Travis CI has been fixed in #20521, adding it to this PR should fix the CI

**Comment by ldelossa** [comment]
@tklauser just pulled in your CI changes, lmk if it looks good.

**Review by tklauser — APPROVED** [review]
Looks good, thanks Louis!

**Comment by ldelossa** [comment]
/test-backport-1.12

**Review by twpayne — APPROVED** [review]

**Review by pippolo84 — APPROVED** [review]

**Review by jibi — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
github-sec LGTM.

**Review by nathanjsweet — APPROVED** [review]

**Comment by ldelossa** [comment]
rerunning `ci-aks-1.12` - looks like cloud infra flake.

**Review by odinuge — APPROVED** [review]
My change looks good!

**Comment by ldelossa** [comment]
/test-1.21-4.9

**Comment by ldelossa** [comment]
/test-1.17-4.9

**Comment by ldelossa** [comment]
test gke-stable (test-gke) is currently failing for most branches and builds. Considering this a flaky test and we won't block merge on this.

**Comment by nbusseneau** [comment]
The AKS workflow for 1.12 is incorrect: https://github.com/cilium/cilium/runs/7345075686?check_suite_focus=true
It should be using BYOCNI, not Azure IPAM => for some reason when we branched out in 51961dd2599393b12744594101b247de1ebf6a5a 23 days ago we used the wrong workflow file as basis, and it's missing the following changes from the same day: 6d5512303c5dc1dd2f99587c17dbd85b6e88c146

**Pull request merged**
