### PR TITLE
Dockerfile: bug fix, Go upgrade and replaced MAINTAINER field

### PR DESCRIPTION
**Pull request by aanm**
- Renamed cilium to cilium-agent in cni script
- Upgraded Golang from 1.7.4 to 1.7.5
- Replaced MAINTAINER deprecated field with a LABEL
- Update iproute2 to 4.10.0

Signed-off-by: André Martins <andre@cilium.io>
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/cilium/cilium/pull/308%23issuecomment-286148498%22%2C%20%22https%3A//github.com/cilium/cilium/pull/308%23issuecomment-286169928%22%2C%20%22https%3A//github.com/cilium/cilium/pull/308%23issuecomment-286249635%22%2C%20%22https%3A//github.com/cilium/cilium/pull/308%23issuecomment-286626177%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/cilium/cilium/pull/308%23issuecomment-286148498%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Should%20I%20upgrade%20%60iproute2%60%20to%20%60v4.10.0%60%20as%20well%3F%22%2C%20%22created_at%22%3A%20%222017-03-13T15%3A47%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/5714066%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/aanm%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3E%20Should%20I%20upgrade%20iproute2%20to%20v4.10.0%20as%20well%3F%5Cr%5Cn%5Cr%5CnI%20defer%20to%20%40borkmann%20%22%2C%20%22created_at%22%3A%20%222017-03-13T16%3A53%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1417913%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tgraf%22%7D%7D%2C%20%7B%22body%22%3A%20%22You%20can%20upgrade%2C%20that%27s%20fine.%20There%27s%20one%20bug%20fix%20%28https%3A//git.kernel.org/pub/scm/linux/kernel/git/shemminger/iproute2.git/commit/%3Fid%3D51361a9f1cfca81259c68515cb24fbaace03136a%29%20which%20is%20not%20part%20of%20a%20release%20yet%2C%20but%20we%27re%20not%20affected%20by%20it.%22%2C%20%22created_at%22%3A%20%222017-03-13T21%3A28%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/677393%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/borkmann%22%7D%7D%2C%20%7B%22body%22%3A%20%22add%20a%20new%20commit%22%2C%20%22created_at%22%3A%20%222017-03-15T02%3A54%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/5714066%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/aanm%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/cilium/cilium/pull/308#issuecomment-286148498'>General Comment</a></b>
- <a href='https://github.com/aanm'></a> Should I upgrade `iproute2` to `v4.10.0` as well?
- <a href='https://github.com/tgraf'></a> > Should I upgrade iproute2 to v4.10.0 as well?
I defer to @borkmann
- <a href='https://github.com/borkmann'></a> You can upgrade, that's fine. There's one bug fix (https://git.kernel.org/pub/scm/linux/kernel/git/shemminger/iproute2.git/commit/?id=51361a9f1cfca81259c68515cb24fbaace03136a) which is not part of a release yet, but we're not affected by it.
- <a href='https://github.com/aanm'></a> add a new commit

<a href='https://www.codereviewhub.com/cilium/cilium/pull/308?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/cilium/cilium/pull/308?approve=1'></a>&nbsp;<a href='https://github.com/cilium/cilium/pull/308'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by aanm** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/cilium/cilium/pull/308'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by aanm** [comment]
Should I upgrade `iproute2` to `v4.10.0` as well?

**Comment by tgraf** [comment]
> Should I upgrade iproute2 to v4.10.0 as well?

I defer to @borkmann

**Review by tgraf — APPROVED** [review]

**Comment by borkmann** [comment]
You can upgrade, that's fine. There's one bug fix (https://git.kernel.org/pub/scm/linux/kernel/git/shemminger/iproute2.git/commit/?id=51361a9f1cfca81259c68515cb24fbaace03136a) which is not part of a release yet, but we're not affected by it.

**Comment by aanm** [comment]
add a new commit

**Review by tgraf — APPROVED** [review]

**Pull request merged**
