### PR TITLE
docs: Correct spelling in ServiceAccount documentation

### PR DESCRIPTION
**Pull request by manalibhutiyani**
Signed-Off-By: Manali Bhutiyani <manali@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4517)

### CODE REVIEW

**Comment by manalibhutiyani** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
test-docs-please

**Comment by manalibhutiyani** [comment]
test-docs-please

**Comment by aanm** [comment]
FYI @manalibhutiyani by adding the labels first and then writing the `test-me-please`, jenkins will be smart enough  to be pick necessary tests (docs/k8s/ginkgo) to run.

**Comment by manalibhutiyani** [comment]
test-me-please

**Pull request merged**
