### PR TITLE
docs: Improve formatting of upgrade notes

### PR DESCRIPTION
**Pull request by joestringer**
Improve the formatting of the upgrade notes to provide critical
information: affected versions, mitigations, solution and upgrade steps.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4361)

### CODE REVIEW

**Comment by joestringer** [comment]
test-docs-please

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
Build failed due to "misspelling" in docs:
```
22:09:33 Please fix the following spelling mistakes:
22:09:33 * Documentation/install/upgrade.rst:140: (remediate) 
22:09:33 If the words are not misspelled, add them to Documentation/spelling_wordlist.txt.
```

I'm surprised that it doesn't know what this word is, but, alas.

**Comment by joestringer** [comment]
Yeah, I built this on top of https://github.com/cilium/cilium/pull/4360 at first and thought I might be able to sneak it in without conflicts on the side. No strong pressure, I'll just rebase/rerun when that's merged to avoid conflicts.

**Comment by joestringer** [comment]
Test-docs-please

**Comment by joestringer** [comment]
test-docs-please

**Pull request merged**
