### PR TITLE
service: Improve memory usage when handling update of a big service.

### PR DESCRIPTION
**Pull request by alan-kut**
Change slices of Backends into slices of pointers to Backends.
That way the slice can be garbage collected even if some parts of
Backends are still in use.

Signed-off-by: Alan Kutniewski <kutniewski@google.com>

### CODE REVIEW

**Comment by sayboras** [comment]
There is CI failure for code generation, can you perform the below ? 

https://github.com/cilium/cilium/runs/7214499228?check_suite_focus=true
```
Please run make generate-k8s-api and submit your changes
```

**Comment by alan-kut** [comment]
Sorry, I wasn't sure how to run deepcopy generation.
The commit is updated with the ```make generate-k8s-api```

**Review by tklauser — APPROVED** [review]
Thanks

**Review by joamaki — APPROVED** [review]
Looks reasonable to me. Backend struct seems to be roughtly some 100+ bytes so we'll save some cycles and we anyway kept deep copying it (though since it had no pointers the deep copy was unnecessary).

I didn't quite understand how this improves the situation with garbage collection. Could you elaborate on that in the commit message? Even better if you happen to have some before and after numbers.

**Review by sayboras — APPROVED** [review]
Looks reasonable to me, thanks :100:

**Comment by sayboras** [comment]
jenkins test failures are all due to `K8sVerifier Runs the kernel verifier against Cilium's BPF datapath` test, which could be related to comment https://github.com/cilium/cilium/pull/20303#issuecomment-1179728499

```
[Suite-k8s-1.16.K8sVerifier Runs the kernel verifier against Cilium's BPF datapath](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/2071/testReport/junit/Suite-k8s-1/16/K8sVerifier_Runs_the_kernel_verifier_against_Cilium_s_BPF_datapath/)
```

**Comment by alan-kut** [comment]
**ConformanceAKS (ci-aks) — Connectivity test failed**
```
Test [to-fqdns]: 1/11 tests failed
  ❌ to-fqdns/pod-to-world/https-to-one-one-one-one-index-0: cilium-test/client-6488dcf5d4-hbp2v (10.0.1.20) -> one-one-one-one-https-index (one.one.one.one:443)
  ❌ to-fqdns/pod-to-world/http-to-one-one-one-one-1: cilium-test/client2-5998d566b4-k5qvg (10.0.1.209) -> one-one-one-one-http (one.one.one.one:80)
  command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null [https://one.one.one.one:443/index.html](https://one.one.one.one/index.html)" succeeded while it should have failed
```
I don't think it is related to the change - I didn't make changes in network policies.

**Cilium L4LB XDP (ci-l4lb) — L4LB test failed**
```
ERROR: failed to create cluster: node(s) already exist for a cluster with the name "kind"
```
Seems like a flake?

**CIFuzz / Fuzzing (pull_request) Failing after 10m**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x24bf58d]
goroutine 17 [running, locked to thread]:
github.com/cilium/cilium/pkg/monitor.(*DebugMsg).Message(0x10c00011da58, {0x0, 0x0})
	github.com/cilium/cilium/pkg/monitor/datapath_debug.go:257 +0x3cd
github.com/cilium/cilium/pkg/hubble/parser/debug.(*Parser).Decode(0x10c000461c50, {0x10c000739e00, 0x23, 0x23}, 0x0)
	github.com/cilium/cilium/pkg/hubble/parser/debug/parser.go:62 +0x2ff
github.com/cilium/cilium/pkg/hubble/parser.(*Parser).Decode(0x10c001994d20, 0x10c00132ddc0)
	github.com/cilium/cilium/pkg/hubble/parser/parser.go:101 +0x84a
github.com/cilium/cilium/pkg/hubble/parser.FuzzParserDecode({0x6040000200d0, 0x25, 0x25})
	github.com/cilium/cilium/pkg/hubble/parser/hubble_parser_fuzzer.go:68 +0x609
main.LLVMFuzzerTestOneInput(...)
	./main.2293162584.go:28
AddressSanitizer:DEADLYSIGNAL
```
I'll look into this

**Comment by sayboras** [comment]
ci-aks and ci-l4lb are known flake AFAIK.

**Comment by alan-kut** [comment]
For the CIFuzz / Fuzzing (pull_request) Failing after 10m AFAIU it ran pkg/hubble/parser with different args. I didn't change any code in neither pkg/hubble nor pkg/monitor and I analyzed the execution path of this failure and I didn't find any dependency on the code I changed.

**Comment by alan-kut** [comment]
I don't see any other action item on me for this PR now.
Is there anything else that I should do?

**Pull request merged**
