### PR TITLE
Update Go to 1.18.1

### PR DESCRIPTION
**Pull request by tklauser**
Also remove `ineffassign` from the `cilium-builder` image and update `golangci-lint` config to Go 1.18 which was missed in the update to Go 1.18.

See commits for details.

### CODE REVIEW

**Review by christarazi — APPROVED** [review]

**Comment by tklauser** [comment]
Had to revert the `//go:build go1.18` update for `plugins/cilium-docker` as it's still built natively in the runtime VM which is still using Go 1.17 at the moment. Will send a follow-up to bump the VM images.

Other than that no changes in the latest push.

**Review by aanm — APPROVED** [review]

**Pull request merged**
