### PR TITLE
bpf, cilium/cmd: remove unused hidden `cilium bpf migrate-map` sub-command

### PR DESCRIPTION
**Pull request by tklauser**
The `cilium bpf migrate-map sub-command` was introduced in 4305f92e7b66
("cilium-migrate-map: port from from C to Go") as a temporary CLI
wrapper around the logic to migrate bpf maps from `bpf/init.sh`. Since
commit d38dda49ef83 ("init.sh,loader: load overlay programs in Go") that
task is performed from within the agent using the same Go code and thus
making the migrate-map sub-command obsolete. The sub-command is hidden
and was only used in `bpf/init.sh`, so remove it directly without
deprecating it first.

### CODE REVIEW

**Review by ti-mo — APPROVED** [review]
Thanks! :grin: :rocket: How did you notice?

**Comment by tklauser** [comment]
Merge conflicts when rebasing one of my WIP branches where I had hacks in `bpf/init.sh`, got curious, checked d38dda49ef835309a4760d1577467973d2496d41 and noticed that `cilium bpf migrate-maps` isn't used anywhere else anymore :grin:

**Review by dylandreimerink — APPROVED** [review]
LGTM!

**Review by squeed — APPROVED** [review]

**Pull request merged**
