### PR TITLE
Update kube-router.rst

### PR DESCRIPTION
**Pull request by carsonoid**
typo fix

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6054)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
Thanks for the fix @carsonoid ! Can you please sign-off your commit per the [Developer's Certificate of Origin](http://docs.cilium.io/en/v1.3/contributing/#developer-s-certificate-of-origin) ?

**Comment by carsonoid** [comment]
Sign off added

**Review by joestringer — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by tgraf** [comment]
test-docs-please

**Comment by aanm** [comment]
@cilium/janitors this a PR being merged to `v1.2`. Should we merge it to `v1.2` or merge it to master and backport it to `v1.3` and `v1.2`?

**Comment by tgraf** [comment]
> this a PR being merged to `v1.2`. Should we merge it to `v1.2` or merge it to master and backport it to `v1.3` and `v1.2`?

It's fine to merge it into 1.2 and cherry-pick it into master and 1.3

**Pull request merged**
