### PR TITLE
doc: Document API guarantees and provide API usage examples

### PR DESCRIPTION
**Pull request by tgraf**
Fixes: #1225

Signed-off-by: Thomas Graf <thomas@cilium.io>

### CODE REVIEW

**Review by aalemayhu — APPROVED** [review]
LGTM, but not sure about the fixes tag. Would instead reference #1225

**Comment by tgraf** [comment]
> LGTM, but not sure about the fixes tag. Would instead reference #1225 

I think there is no point in marking the API stable prematurely before users ask for it, hence closing the issue.

**Comment by aalemayhu** [comment]
Maybe I am missing something here but the issue you are marking as fixed looks unrelated.
`docs: removing cilium-consul ds reference in k8s #1255` is not `Declare API stable #1225`

**Comment by tgraf** [comment]
> Maybe I am missing something here but the issue you are marking as fixed looks unrelated.
> docs: removing cilium-consul ds reference in k8s #1255 is not Declare API stable #1225

Sorry, I misunderstood the comment. Fixed.

**Pull request merged**
