### PR TITLE
Test: Bump stable image to 1.3

### PR DESCRIPTION
**Pull request by eloycoto**
- Bump the stable image to 1.3
- Bump updates from 1.2. Removed 1.0 and 1.1 due EOL

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6016)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]
LGTM - waiting for tests to pass before merging.

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
Hi,

Weird issue here:

ETCD operator is ok, and only **one** etcd container:
```
cmd: "kubectl get pods -o wide --all-namespaces" exitCode: 0 duration: 443.818759ms stdout:
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE   IP              NODE   NOMINATED NODE
kube-system   cilium-4qwsf                       1/1     Running   1          15m   192.168.36.11   k8s1   <none>
kube-system   cilium-cbvfq                       1/1     Running   1          15m   192.168.36.12   k8s2   <none>
kube-system   cilium-etcd-5q5np2ffg7             1/1     Running   0          11m   10.10.1.176     k8s2   <none>
kube-system   coredns-779ffd89bd-5qtql           1/1     Running   0          41m   10.10.0.238     k8s1   <none>
kube-system   etcd-k8s1                          1/1     Running   0          41m   192.168.36.11   k8s1   <none>
kube-system   etcd-operator-547c5c7f84-4bls6     1/1     Running   0          15m   10.10.0.251     k8s1   <none>
kube-system   kube-apiserver-k8s1                1/1     Running   0          41m   192.168.36.11   k8s1   <none>
kube-system   kube-controller-manager-k8s1       1/1     Running   0          41m   192.168.36.11   k8s1   <none>
kube-system   kube-proxy-7dckk                   1/1     Running   0          16m   192.168.36.12   k8s2   <none>
kube-system   kube-proxy-8wzfx                   1/1     Running   0          41m   192.168.36.11   k8s1   <none>
kube-system   kube-scheduler-k8s1                1/1     Running   1          41m   192.168.36.11   k8s1   <none>
monitoring    prometheus-core-5888d94764-qc4jg   1/1     Running   0          15m   10.10.0.203     k8s1   <none>
```

If you see the etcd operator logs all looks good:
```
2018-10-25T08:45:11.211666419Z time="2018-10-25T08:45:11Z" level=info msg="etcd-operator Version: 0.9.2"
2018-10-25T08:45:11.211802635Z time="2018-10-25T08:45:11Z" level=info msg="Git SHA: a0032c1f"
2018-10-25T08:45:11.211935634Z time="2018-10-25T08:45:11Z" level=info msg="Go Version: go1.10"
2018-10-25T08:45:11.213819392Z time="2018-10-25T08:45:11Z" level=info msg="Go OS/Arch: linux/amd64"
2018-10-25T08:45:11.441562763Z time="2018-10-25T08:45:11Z" level=info msg="Event(v1.ObjectReference{Kind:\"Endpoints\", Namespace:\"kube-system\", Name:\"etcd-operator\", UID:\"48a8b283-d832-11e8-b3d0-080027915ef7\", APIVersion:\"v1\", ResourceVersion:\"2682\", FieldPath:\"\"}): type: 'Normal' reason: 'LeaderElection' etcd-operator-547c5c7f84-4bls6 became leader"
2018-10-25T08:45:11.850834168Z time="2018-10-25T08:45:11Z" level=info msg="creating cluster with Spec:" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.850894064Z time="2018-10-25T08:45:11Z" level=info msg="{" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.850912056Z time="2018-10-25T08:45:11Z" level=info msg="    \"size\": 3," cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.850928542Z time="2018-10-25T08:45:11Z" level=info msg="    \"repository\": \"quay.io/coreos/etcd\"," cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851493236Z time="2018-10-25T08:45:11Z" level=info msg="    \"version\": \"3.3.9\"," cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851654378Z time="2018-10-25T08:45:11Z" level=info msg="    \"pod\": {" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851675417Z time="2018-10-25T08:45:11Z" level=info msg="        \"labels\": {" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851692347Z time="2018-10-25T08:45:11Z" level=info msg="            \"io.cilium/app\": \"etcd-operator\"" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851708216Z time="2018-10-25T08:45:11Z" level=info msg="        }," cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851721876Z time="2018-10-25T08:45:11Z" level=info msg="        \"resources\": {}" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851736049Z time="2018-10-25T08:45:11Z" level=info msg="    }," cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851748985Z time="2018-10-25T08:45:11Z" level=info msg="    \"TLS\": {" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851762429Z time="2018-10-25T08:45:11Z" level=info msg="        \"static\": {" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851777029Z time="2018-10-25T08:45:11Z" level=info msg="            \"member\": {" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851791193Z time="2018-10-25T08:45:11Z" level=info msg="                \"peerSecret\": \"cilium-etcd-peer-tls\"," cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851806585Z time="2018-10-25T08:45:11Z" level=info msg="                \"serverSecret\": \"cilium-etcd-server-tls\"" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851821099Z time="2018-10-25T08:45:11Z" level=info msg="            }," cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851878486Z time="2018-10-25T08:45:11Z" level=info msg="            \"operatorSecret\": \"cilium-etcd-client-tls\"" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851896179Z time="2018-10-25T08:45:11Z" level=info msg="        }" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851910369Z time="2018-10-25T08:45:11Z" level=info msg="    }" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.851924181Z time="2018-10-25T08:45:11Z" level=info msg="}" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:11.940493519Z time="2018-10-25T08:45:11Z" level=info msg="cluster created with seed member (cilium-etcd-5q5np2ffg7)" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:12.323009888Z time="2018-10-25T08:45:12Z" level=info msg="start running..." cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:20.372931394Z time="2018-10-25T08:45:20Z" level=info msg="skip reconciliation: running ([]), pending ([cilium-etcd-5q5np2ffg7])" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:28.388661277Z time="2018-10-25T08:45:28Z" level=info msg="skip reconciliation: running ([]), pending ([cilium-etcd-5q5np2ffg7])" cluster-name=cilium-etcd pkg=cluster
2019-10-25T08:45:36.410469891Z time="2018-10-25T08:45:36Z" level=info msg="skip reconciliation: running ([]), pending ([cilium-etcd-5q5np2ffg7])" cluster-name=cilium-etcd pkg=cluster
2018-10-25T08:45:44.459732326Z time="2018-10-25T08:45:44Z" level=info msg="skip reconciliation: running ([]), pending ([cilium-etcd-5q5np2ffg7])" cluster-name=cilium-etcd pkg=cluster
```

ETCD pod is healthy, but I do not know why the other two pods are not deploying. Any idea @aanm?

Build link: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7544/execution/node/94/log/?consoleFull
Logs: 
[5190e287_K8sHealthTest_checks_cilium-health_status_between_nodes.zip](https://github.com/cilium/cilium/files/2514432/5190e287_K8sHealthTest_checks_cilium-health_status_between_nodes.zip)

**Comment by eloycoto** [comment]
test-me-please

**Comment by aanm** [comment]
@eloycoto I believe we discuss this over slack

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Pull request merged**
