### PR TITLE
workflows: Use docker manifest inspect for waiting images

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
Please see the commit message for more details.

All workflows were passing with the test commit: 
image

```release-note
Use docker manifest inspect to wait for images instead of using quay API
```

### CODE REVIEW

**Comment by YutaroHayakawa** [comment]
Somehow, this became ready-for-review automatically. Actually, I need to revert the PR for debugging and merge it to the first commit.

**Comment by YutaroHayakawa** [comment]
Now, it's ready for review.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
Workflows were passing earlier with the test commit and all Jenkins tests have passed the Wait for images step. Merging.

**Comment by nbusseneau** [comment]
Thanks for fixing it :)

**Pull request merged**
