### PR TITLE
bpf: constify pointer function arguments

### PR DESCRIPTION
**Pull request by tklauser**
Constify pointer function arguments where possible.

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Comment by raybejjani** [comment]
@tklauser The tests for this ended up on a machine with no free disk. It will probably fail. Sorry!

**Comment by tklauser** [comment]
> @tklauser The tests for this ended up on a machine with no free disk. It will probably fail. Sorry!

@raybejjani no worries, this isn't something urgent, so I can retrigger the failed tests once the issue is sorted out.

**Review by pchaigno — APPROVED** [review]
I wonder if we could write a Coccinelle script for this :thinking:

**Comment by borkmann** [comment]
test-with-kernel

**Comment by borkmann** [comment]
> I wonder if we could write a Coccinelle script for this

We do have a coccinelle script in our repo:

https://github.com/cilium/cilium/blob/master/contrib/coccinelle/null.cocci

I think we can invoke them via `make check`, but probably makes more sense to extend them and integrate into our CI, same with the sparse in there so we can bail out early and catch such bugs?

**Comment by borkmann** [comment]
> > I wonder if we could write a Coccinelle script for this
> 
> We do have a coccinelle script in our repo:
> 
> https://github.com/cilium/cilium/blob/master/contrib/coccinelle/null.cocci
> 
> I think we can invoke them via `make check`, but probably makes more sense to extend them and integrate into our CI, same with the sparse in there so we can bail out early and catch such bugs?

Opened #10842.

**Pull request merged**
