### PR TITLE
v1.10 backports 2022-03-03

### PR DESCRIPTION
**Pull request by pchaigno**
* #18506 -- Fix EncryptStatusSuite.TestCountUniqueIPsecKeys (@tklauser)
     - Skipped the first commit as the unit test doesn't exist in v1.10.
     - Re-updated the github.com/vishvananda/netlink dep from scratch using the same commit as on master.
 * #18827 -- pkg/datapath/linux: Fix asymmetric IPsec logic on delete (@christarazi)
 * #18893 -- docs: Remove trailing step in AWS helm install (@joestringer)
     - Fixed trivial conflict.
 * #18886 -- jenkinsfiles: bump runtime tests VM boot timeout (@nbusseneau)
 * #18891 -- docs: update Azure Service Principal / IPAM documentation (@nbusseneau)
 * #18877 -- hubble: Added nil check in filterByTCPFlags() to avoid segfault (@wazir-ahmed)
 * #18911 -- Fix IPsec in Azure's IPAM mode (@pchaigno)
 * #18952 -- pkg/maps: Fix data races around accessing nat maps (@aditighag)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18506 18827 18893 18886 18891 18877 18911 18952; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by pchaigno** [comment]
/test-backport-1.10

**Review by tklauser — APPROVED** [review]
> * #18506 (@tklauser)
>   * Skipped the first commit as the unit test doesn't exist in v1.10.
>   * Re-updated the github.com/vishvananda/netlink dep from scratch using the same commit as on master.

That one LGTM, thanks Paul!

**Review by nbusseneau — APPROVED** [review]
My commits LGTM.

**Review by tklauser — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by pchaigno** [comment]
- The CodeQL errors are clearly unrelated (it's unclear why they even show up).
- runtime failed with the known issue https://github.com/cilium/cilium/issues/18919.

We're only missing the review from Aditi but there weren't any conflicts on her changes, so probably fine to skip. Marking ready to merge.

**Review by aditighag — APPROVED** [review]
Changes for my PR look good. Thanks!

**Review by gandro — APPROVED** [review]

**Comment by seanmwinn** [comment]
https://github.com/isovalent/customer-support/issues/280

**Comment by joestringer** [comment]
@seanmwinn It doesn't makes sense to add "needs-backport/1.9" to a backport PR like this. If you intended to raise a specific PR for backport, please go to the original PR and add the label there. I'll remove the label since it's unclear which PR from this set of already-backported PRs that you intended to be backported.

**Pull request merged**
