### PR TITLE
Bump aws/aws-sdk-go-v2 to 0.23.0

### PR DESCRIPTION
**Pull request by ungureanuvladvictor**
Signed-off-by: Vlad Ungureanu <vladu@palantir.com>

Bump aws/aws-sdk-go-v2 to 0.23.0 from 0.18.0.

Changelogs are below:
- 0.19.0: https://github.com/aws/aws-sdk-go-v2/blob/master/CHANGELOG.md#release-v0190-2020-01-30
- 0.20.0: https://github.com/aws/aws-sdk-go-v2/blob/master/CHANGELOG.md#release-v0200-2020-03-17
- 0.21.0: https://github.com/aws/aws-sdk-go-v2/blob/master/CHANGELOG.md#release-v0210-2020-04-21
- 0.22.0: https://github.com/aws/aws-sdk-go-v2/blob/master/CHANGELOG.md#release-v0220-2020-04-27
- 0.23.0: https://github.com/aws/aws-sdk-go-v2/blob/master/CHANGELOG.md#release-v0230-2020-05-28

From scanning the changelog list there are no bugfixes/features added to the `ec2` part of the SDK (just the usual syncing with API definitions).

The only breaking change is in 0.19.0 from https://github.com/aws/aws-sdk-go-v2/pull/461 which add context param to the `GetInstanceIdentityDocument ` call.

Given we do not have e2e tests with a real k8s cluster + ENI IPAM I gave this a spin on my EKS stack and scaled up/down a couple of times which worked as expected.

```release-note
Bump aws/aws-sdk-go-v2 to 0.23.0 from 0.18.0
```

### CODE REVIEW

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Comment by ungureanuvladvictor** [comment]
netnext failed because of (https://jenkins.cilium.io/job/Cilium-PR-K8s-oldest-net-next/1080/console):
```
19:42:09  Progress state: VBOX_E_INVALID_OBJECT_STATE
19:42:09  VBoxManage: error: Machine delete failed
19:42:09  VBoxManage: error: Medium '/root/VirtualBox VMs/ubuntu-18.04.4-amd64-60_1593741403324_42802/ubuntu-18.04.4-amd64-60-disk001.vmdk' is locked for reading by another task
19:42:09  VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MediumWrap, interface IMedium
19:42:09  VBoxManage: error: Context: "RTEXITCODE handleUnregisterVM(HandlerArg*)" at line 162 of file VBoxManageMisc.cpp
```

**Comment by ungureanuvladvictor** [comment]
retest-net-next

**Review by tgraf — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Comment by tgraf** [comment]
retest-net-next

**Comment by nebril** [comment]
Previous build failed due to faulty CI node which was taken down.

**Pull request merged**
