### PR TITLE
ci: delete gke cluster after test run

### PR DESCRIPTION
**Pull request by nebril**
We are hitting a lot of issues caused by state left over from test run.

This change deletes the cluster after the test run and relies on our
infra recreating the cluster for subsequent builds.

From my testing it takes our infra around10 minutes to get the cluster back up after deletion.

### CODE REVIEW

**Comment by nebril** [comment]
test-gke K8sDemos

**Review by jrajahalme — APPROVED** [review]

**Comment by errordeveloper** [comment]
@nebril how quickly do they get re-created?

**Comment by nebril** [comment]
@errordeveloper from my testing - it takes around 10 minutes for cluster to get back up

**Comment by nebril** [comment]
test-gke K8sDemos

**Comment by nebril** [comment]
swapped the order of commands, we delete the cluster first so we don't rely on config connector deleting the cluster (there were issues related to that before), then we delete the k8s object which will be recreated.

**Comment by nebril** [comment]
test-gke K8sDemos

**Review by errordeveloper — APPROVED** [review]

**Comment by nebril** [comment]
This change is only GKE-related, merging.

**Comment by mrostecki** [comment]
I think it might need a backport to 1.8 - we already want to backport GKE changes which depend on this PR.

**Pull request merged**
