### PR TITLE
v1.15 Backports 2024-02-29

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
* [x] #30909 (@aanm)
 * [x] #30742 (@qmonnet)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30909 30742
```

### CODE REVIEW

**Comment by YutaroHayakawa** [comment]
/test-backport-1.15

**Comment by YutaroHayakawa** [comment]
[Conformance AKS](https://github.com/cilium/cilium/actions/runs/8090978367): https://github.com/cilium/cilium/issues/30745
[Conformance Ginkgo](https://github.com/cilium/cilium/actions/runs/8090978586): https://github.com/cilium/cilium/issues/30802
[Conformance Runtime](https://github.com/cilium/cilium/actions/runs/8090978723): https://github.com/cilium/cilium/issues/31006

**Review by aanm — APPROVED** [review]
Thank you!

**Review by qmonnet — APPROVED** [review]
My commit looks good, thanks! I checked that the script is identical to its version on the `main` branch.

However, it seems that the commits are missing your own sign-off tags? :open_mouth:

**Comment by YutaroHayakawa** [comment]
Added my signed-off-by

**Comment by YutaroHayakawa** [comment]
/test-backport-1.15

**Review by ldelossa — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
[Cilium Cluster Mesh upgrade](https://github.com/cilium/cilium/actions/runs/8097624485): https://github.com/cilium/cilium/issues/30964
[Conformance E2E](https://github.com/cilium/cilium/actions/runs/8097623894): LVH timeout while waiting for SSH daemon startup.
[Conformance Ginkgo](https://github.com/cilium/cilium/actions/runs/8097624109): https://github.com/isovalent/cilium/issues/2724
[Conformance IPsec E2E](https://github.com/cilium/cilium/actions/runs/8097623933): https://github.com/cilium/cilium/issues/30745

**Comment by YutaroHayakawa** [comment]
[Conformance Ginkgo](https://github.com/cilium/cilium/actions/runs/8097624109/job/22157609378): https://github.com/cilium/cilium/issues/31080

**Pull request merged**
