### PR TITLE
v1.10 backports 2021-05-12

### PR DESCRIPTION
**Pull request by glibsm**
* #15975 -- docs: improve and fix minor issues (@qmonnet)
 * #15942 -- Follow ups for host firewall support of endpoint routes (@pchaigno)
 * #16006 -- docs: update OpenShift getting started guide (@twpayne)
 * #16020 -- wireguard: Set wireguard and route MTU to detected MTU (@joamaki)
 * #16066 -- vendor: update wireguard library (@aanm)
 * #16017 -- daemon: store Cilium's configuration in a file (@aanm)
 * #16027 -- docs: Update SIG-Datapath meeting time. (@joestringer)
 * #16070 -- vendor: bump github.com/vishvananda/netlink to latest master (@tklauser)
 * #16068 -- test: Fix flake in ValidateEndpointsAreCorrect (@pchaigno)
 * #16056 -- jenkinsfiles: fix race detector pipelines (@nbusseneau)
 * #16045 -- docs: add 'endpointRoutes.enabled=true' to aws-cni (@bmcustodio)
 * #15979 -- docs: improve the aws-cni chaining page (@bmcustodio)
 * #15978 -- docs/ipsec: misc improvements (@kaworu)
 * #16057 -- Add XFRM In policy for traffic destined to the L7 proxy (@christarazi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 15975 15942 16006 16020 16066 16017 16027 16070 16068 16056 16045 15979 15978 16057; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by glibsm** [comment]
Two PRs didn't get their commits correctly picked up by the scripts. I manually found them in the log and grabbed the shas. I'm not sure what confused the scripts. Is this common?

```
 * PR: 16006 -- docs: update OpenShift getting started guide (@twpayne) -- https://github.com/cilium/cilium/pull/16006
   Merge with 1 commit(s) merged at: Mon, 10 May 2021 13:56:34 +0000!
     Branch:     master (!)                          refs/pull/16006/head
                 ----------                          -------------------
     v (start)
     |  Warning: No commit correlation found!    via a4b7645a9b90303e54eee9e9edfc609402ac7cca ("docs: update OpenShift getting started guide")
     v (end)

     GS: Manually pulled up `421314d9b` from the git log

 * PR: 15979 -- docs: improve the aws-cni chaining page (@bmcustodio) -- https://github.com/cilium/cilium/pull/15979
   Merge with 1 commit(s) merged at: Tue, 11 May 2021 21:56:30 +0000!
     Branch:     master (!)                          refs/pull/15979/head
                 ----------                          -------------------
     v (start)
     |  Warning: No commit correlation found!    via 216ddbb299fc4bcfa42b0cc6539a2b6bc8fdeec3 ("docs: improve the aws-cni chaining page")
     v (end)

     GS: Manually found 3b350ce81
```

**Review by christarazi — CHANGES_REQUESTED** [review]
My commits look good, but it seems like all the commits in the PR are not signed off by you, but rather the author references vagrant.

**Review by qmonnet — APPROVED** [review]
> #15975 -- docs: improve and fix minor issues (@qmonnet)

Looks good (apart from the SOB issue reported by Chris already).

As far as I'm concerned, I don't remember seeing the commit correlation issue before :/.

**Comment by bmcustodio** [comment]
> #15979 -- docs: improve the aws-cni chaining page (@bmcustodio)

@glibsm my commit (216ddbb) seems to have been picked up correctly as 4c2874b.

**Review by pchaigno — APPROVED** [review]
My commits look good :+1:

**Review by tklauser — APPROVED** [review]
👍 for my commit (apart from `Signed-off-by` already pointed out by Chris)

**Review by nbusseneau — APPROVED** [review]
OK for me.

**Review by twpayne — APPROVED** [review]
OpenShift GSG changes LGTM.

**Review by joamaki — APPROVED** [review]
My commit is OK.

**Review by aanm — APPROVED** [review]
LGTM except the sign-off as pointed out by others

**Comment by glibsm** [comment]
> My commits look good, but it seems like all the commits in the PR are not signed off by you, but rather the author references vagrant.

Thanks for pointing it out, that's really bizarre since I didn't even shut down this vagrant since last backport. Strange. I'll force push a fix

**Review by christarazi — APPROVED** [review]

**Comment by christarazi** [comment]
test-backport-1.10

**Comment by pchaigno** [comment]
test-1.19-5.4

**Pull request merged**
