### PR TITLE
add toEntities/fromEntities CRD description missing options

### LINKED ISSUE #22235: toEntities/fromEntities CRD description missing some options
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

CRDs are missing all the possible options listed in the docs: https://docs.cilium.io/en/stable/policy/language/#entities-based
```
(⎈|kind-kind:default) ~/p/w/hubble-timescape ❯❯❯ k explain ciliumnetworkpolicy.spec.egress.toEntities                                                                               pr/chancez/network_policies ✭ ✚ ✱
KIND:     CiliumNetworkPolicy
VERSION:  cilium.io/v2

FIELD:    toEntities <[]string>

DESCRIPTION:
     ToEntities is a list of special entities to which the endpoint subject to
     the rule is allowed to initiate connections. Supported entities are
     `world`, `cluster` and `host`

     Entity specifies the class of receiver/sender endpoints that do not have
     individual identities. Entities are used to describe "outside of cluster",
     "host", etc.

(⎈|kind-kind:default) ~/p/w/hubble-timescape ❯❯❯ k explain ciliumnetworkpolicy.spec.ingress.fromEntities                                                                      ✘ 130 pr/chancez/network_policies ✭ ✚ ✱
KIND:     CiliumNetworkPolicy
VERSION:  cilium.io/v2

FIELD:    fromEntities <[]string>

DESCRIPTION:
     FromEntities is a list of special entities which the endpoint subject to
     the rule is allowed to receive connections from. Supported entities are
     `world`, `cluster` and `host`

     Entity specifies the class of receiver/sender endpoints that do not have
     individual identities. Entities are used to describe "outside of cluster",
     "host", etc.
```

### Cilium Version

v1.12.2

### Kernel Version

Linux lima-docker 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 12:56:31 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:38:29Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by slayer321**
Signed-off-by: Sachin Maurya <sachin.maurya7666@gmail.com>

add all the Entities options from [docs](https://docs.cilium.io/en/stable/policy/language/#entities-based) 

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: https://github.com/cilium/cilium/issues/22235

### CODE REVIEW

**Review by pchaigno — DISMISSED** [review]

**Comment by pchaigno** [comment]
@slayer321 Thanks for the pull request! Please have a look at the failing CI checks. Some of them are failing because of missing changes (e.g., files that need to be regenerated).

I've switched the PR to draft mode until this is addressed.

**Comment by slayer321** [comment]
@pchaigno  When I'm running this command `make generate-k8s-api`in cilium root dir I'm getting below error
```
Set $GOPATH to a directory containing the Cilium repository at $GOPATH/src/github.com/cilium/cilium.
The current working directory must be the repository root for code generation to work correctly.
make: *** [Makefile:329: generate-k8s-api] Error 1
```
This is where my cilium project resides `/home/sachinmaurya/go/src/github.com/cilium`
my GOPATH is `/home/sachinmaurya/go`  ... as I can see that my cilium project is already in the dir it is mention .. I'm not getting why it is failing

**Comment by pchaigno** [comment]
@slayer321 Could you ask in Slack? I'm not seeing the issue but others may spot it.

**Comment by chancez** [comment]
> This is where my cilium project resides `/home/sachinmaurya/go/src/github.com/cilium` my GOPATH is `/home/sachinmaurya/go` ... as I can see that my cilium project is already in the dir it is mention .. I'm not getting why it is failing

It should be at `/home/sachinmaurya/go/src/github.com/cilium/cilium`, note the extra `cilium` directory.

**Comment by slayer321** [comment]
@chancez Yeah, I also thought that but as I can see that the `generate-k8s-api` is available is root directory [Makefile](https://github.com/cilium/cilium/blob/master/Makefile#L328) of Cilium repo so that's the reason I tried running it from this directory `/home/sachinmaurya/go/src/github.com/cilium` .. am I missing something here :thinking:

@pchaigno yes, I first asked it on [slack](https://cilium.slack.com/archives/C1MATJ5U5/p1669040639050629) .. but as there was no reply so thought of asking it here

**Comment by slayer321** [comment]
Hey, I tried running the `make generate-k8s-api` command and it runs successfully without any errors  and there was not changes in any of the files.. But now I can see that the `generate-k8s-api` CI is still failing and says I need to run the make commands ..
I don't understand what can be the reason for that :thinking:

**Comment by aanm** [comment]
hey @slayer321, the changes in this PR are modifying a auto-generated file. The changes should be done [here](https://github.com/cilium/cilium/blob/e4d68f84a7c957bc9c6b6fea3bfda3151f830629/pkg/policy/api/egress.go#L70-L74) and then you should run the `make generate-k8s-api`. Let me know if this helps. Once you have submitted your changes don't forget to mark your PR as "Ready for review" Thank you.

**Comment by aanm** [comment]
@slayer321 Also run `make manifests`

**Review by aanm — APPROVED** [review]

**Pull request merged**
