### PR TITLE
gha: Remove ci-aks workflow

### PR DESCRIPTION
**Pull request by sayboras**
Cilium v1.14 supports only up to aks v1.27, however, this version is no
longer available in standard support, hence any new cluster creation
will fail with below error.

This commit is to remove ci-aks related configuration and files.

https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli

```
ERROR: (BadRequest) Managed cluster cilium-cilium-10606103899-2-2 is on version 1.27.16 which is not supported in this region. Please use [az aks get-versions] command to get the supported version list in this region. For more information, please check https://aka.ms/supported-version-list
```

Signed-off-by: Tam Mach <tam.mach@cilium.io>

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.14

**Comment by sayboras** [comment]
/test-backport-1.14

**Review by nbusseneau — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Pull request merged**
