### PR TITLE
v1.14 Backports 2024-06-18

### PR DESCRIPTION
**Pull request by jschwinger233**
* [ ] #32852 (@geakstr) :warning: resolved conflicts

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 32852
```
* [ ] #33050 (@sayboras) :warning: I dropped your patch because there is no `operator/pkg/controller-runtime` in 1.14, I don't know how to proceed with backport.

### CODE REVIEW

**Comment by jschwinger233** [comment]
/test-backport-1.14

**Comment by jschwinger233** [comment]
/test-backport-1.14

**Comment by sayboras** [comment]
> I dropped your patch because there is no operator/pkg/controller-runtime in 1.14, I don't know how to proceed with backport.

Noted and thanks, I will add backport/author label for mentioned PR.

**Comment by jschwinger233** [comment]
The only unsuccessful CI check is "Image CI Build / Display Digests", not an issue caused by this PR, I think it's ready for review.

**Comment by sayboras** [comment]
> The only unsuccessful CI check is "Image CI Build / Display Digests", not an issue caused by this PR, I think it's ready for review.

Just a note that this PR should fix the display digest failure, so probably for the next backport.

https://github.com/cilium/cilium/pull/33216

**Review by ti-mo — APPROVED** [review]

**Pull request merged**
