### PR TITLE
v1.3 backports 2018-10-19

### PR DESCRIPTION
**Pull request by borkmann**
PRs backported:

- #5877 
- #5878 
- #5915 
- #5922 
- #5937 
- #5940 
- #5947

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5952)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by tgraf** [comment]
test-docs

**Comment by tgraf** [comment]
test-missed-k8s

**Review by tgraf — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]
Proxy commits look good, thanks!

**Comment by tgraf** [comment]
test-docs-please

**Review by ianvernon — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Pull request merged**
