### PR TITLE
bpf: skip in-cluster xlation for non-local ips

### PR DESCRIPTION
**Pull request by borkmann**
See commit msg.
```release-note
Skip in-cluster xlation for non-local ips in socket lb for case of external ips
```

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
(All green except `Tests externalIPs` on net-next, https://jenkins.cilium.io/job/Cilium-PR-K8s-oldest-net-next/929/)

**Comment by borkmann** [comment]
retest-net-next

**Comment by borkmann** [comment]
test-focus K8sService*

**Review by vadorovsky — APPROVED** [review]

**Comment by borkmann** [comment]
retest-4.19

**Comment by borkmann** [comment]
retest-4.9

**Comment by borkmann** [comment]
retest-runtime

**Comment by borkmann** [comment]
retest-4.9

**Review by pchaigno — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Pull request merged**
