### PR TITLE
v1.6 backports 2020-03-19

### PR DESCRIPTION
**Pull request by jrfastab**
* #9649    cilium: encryption fixes for ipv6 and tear down
* #10218  cilium: encryption + tunnel improvements and fixes
* #10268  cilium: encryption, segfaults if existing non-Cilium xfrm policy without mark set exists
* #10551  cilium: encryption, additional mtu fix for non-default 1500B MTU 

Note: Only IPv4 support added from #9649 IPv6 is not included here, we can debate if we want fib IPv6 support backported somewhere else but its strictly speaking not a fix. This was really an error on my side in original PR to mix a fix with a feature.

Note: Scripts broke on this set of backports so did this by hand comparing manual and v1.6

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 9649 10218 10268 10551; do contrib/backporting/set-labels.py $pr done 1.6; done
```

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Review by jrajahalme — APPROVED** [review]

**Comment by joestringer** [comment]
test-me-please

**Comment by aanm** [comment]
seems to be a real failure https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18059/testReport/junit/Suite-k8s-1/10/K8sDatapathConfig_Transparent_encryption_DirectRouting_Check_connectivity_with_transparent_encryption_and_direct_routing/

**Comment by jrfastab** [comment]
I'll look into it. Agree, looks like a real failure.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
provisioning error. I'll try again.

**Comment by jrfastab** [comment]
test-me-please

**Comment by aanm** [comment]
Failed again @jrfastab 

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.10-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:420
Connectivity test between nodes failed
Expected
    <bool>: false
to be true
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.10-gopath/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:193
```
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18268/testReport/junit/Suite-k8s-1/10/K8sDatapathConfig_Transparent_encryption_DirectRouting_Check_connectivity_with_transparent_encryption_and_direct_routing/

**Comment by jrfastab** [comment]
closing, tracking this in new PR https://github.com/cilium/cilium/pull/10638

**Comment by qmonnet** [comment]
> closing, tracking this in new PR #10638

This is the current PR. New PR seems to be #11044.

**Pull request closed without merging**
