### PR TITLE
helm: remove duplicate metrics for Envoy pod

### LINKED ISSUE #32747: Duplicate metrics with `envoy.prometheus.enabled=true` in Helm chart
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When you set `envoy.prometheus.enabled=true` both Pods (from `cilium-envoy` DaemonSet) and Service (`cilium-envoy`) have prometheus annotations which leads to double scraping:

* https://github.com/cilium/cilium/blob/v1.16.0-pre.2/install/kubernetes/cilium/templates/cilium-envoy/daemonset.yaml#L30-L31
* https://github.com/cilium/cilium/blob/v1.16.0-pre.2/install/kubernetes/cilium/templates/cilium-envoy/service.yaml#L10-L11

May be the Service should not be created at all for standalone Envoy DaemonSet (`envoy.enabled=true`)?

### Cilium Version

v1.15.5, v1.16.0-pre.2

### Kernel Version

5.15.0-97-generic

### Kubernetes Version

v1.28.8

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mhofstetter**
Currently, having Prometheus enabled `envoy.prometheus.enabled=true` results in duplicated metrics for the Envoy daemonset Pods if scraping via a dedicated `ServiceMonitor` isn't enabled. The reason is that prometheus are added to the `Pod` (in the `DaemonSet`) and to the `Service`.

Therefore, this commit removes the Envoy K8s `Service` completely, as this is only used for prometheus scraping.

Fixes: #32747

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@mhofstetter I've added the needs-backport labels for 1.15 and 1.16

**Comment by joamaki** [comment]
v1.15 does not have this file, removed the backport label for it.

**Comment by mhofstetter** [comment]
> v1.15 does not have this file, removed the backport label for it.

@joamaki what about https://github.com/cilium/cilium/blob/v1.15/install/kubernetes/cilium/templates/cilium-envoy/service.yaml? :thinking:

**Pull request merged**
