### PR TITLE
daemon: Remove --help flags grouping

### PR DESCRIPTION
**Pull request by brb**
This commit reverts the --help flags grouping introduced by [1].

The motivation for removing the grouping is the following:

- Some flags should be in multiple groups to help users to navigate
  through the flags (e.g. "IPMasqAgentConfigPath").
- Some grouping doesn't make much sense (e.g. "IP flags" - each flag
  should belong to a different group instead).
- We tend to forget to add new flags.

Therefore considering above, the alphabetical order yields better UX.

\[1\]: https://github.com/cilium/cilium/pull/10795

### CODE REVIEW

**Review by borkmann — APPROVED** [review]
Thanks for cleaning up this mess! :+1:

**Comment by brb** [comment]
test-me-please

**Review by twpayne — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
k8s-1.20-kernel-4.19 failed with known flake https://github.com/cilium/cilium/issues/15575. Other CI jobs are passing (even though GitHub doesn't report the updated status).

**Pull request merged**
