### PR TITLE
vendor: bump github.com/vishvananda/netlink to latest master

### LINKED ISSUE #15438: [Race Detector] Race between netlink.parseBpfData() and netlink.LinkDeserialize()
```
2021-03-22T00:42:18.428617949Z WARNING: DATA RACE
2021-03-22T00:42:18.428762956Z Write at 0x0000050ade90 by goroutine 237:
2021-03-22T00:42:18.428985880Z   github.com/vishvananda/netlink.parseBpfData()
2021-03-22T00:42:18.429003997Z       /go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:704 +0x9d
2021-03-22T00:42:18.429078845Z   github.com/vishvananda/netlink.(*Handle).FilterList()
2021-03-22T00:42:18.429092127Z       /go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:374 +0x9d5
2021-03-22T00:42:18.429182743Z   github.com/vishvananda/netlink.FilterList()
2021-03-22T00:42:18.429202709Z       /go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:297 +0xf6
2021-03-22T00:42:18.429291823Z   github.com/cilium/cilium/pkg/datapath/loader.RemoveTCFilters()
2021-03-22T00:42:18.429305236Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/netlink.go:153 +0xb3
2021-03-22T00:42:18.429378025Z   github.com/cilium/cilium/pkg/datapath/loader.(*Loader).reloadDatapath()
2021-03-22T00:42:18.429391035Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:346 +0x166d
2021-03-22T00:42:18.429461117Z   github.com/cilium/cilium/pkg/datapath/loader.(*Loader).ReloadDatapath()
2021-03-22T00:42:18.429473827Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:478 +0x1f5
2021-03-22T00:42:18.429545613Z   github.com/cilium/cilium/pkg/datapath/loader.(*Loader).CompileOrLoad()
2021-03-22T00:42:18.429559439Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:466 +0x704
2021-03-22T00:42:18.429642354Z   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).realizeBPFState()
2021-03-22T00:42:18.429655634Z       /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:720 +0x842
2021-03-22T00:42:18.429748051Z   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF()
2021-03-22T00:42:18.429762227Z       /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:635 +0x3f5
2021-03-22T00:42:18.429873286Z   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate()
2021-03-22T00:42:18.429888838Z       /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:416 +0xd7b
2021-03-22T00:42:18.429984539Z   github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle()
2021-03-22T00:42:18.429999809Z       /go/src/github.com/cilium/cilium/pkg/endpoint/events.go:65 +0x3e5
2021-03-22T00:42:18.430102412Z   github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run.func1()
2021-03-22T00:42:18.430117614Z       /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:256 +0x26a
2021-03-22T00:42:18.430224127Z   sync.(*Once).doSlow()
2021-03-22T00:42:18.430248892Z       /usr/local/go/src/sync/once.go:68 +0x109
2021-03-22T00:42:18.430347394Z   sync.(*Once).Do()
2021-03-22T00:42:18.430362171Z       /usr/local/go/src/sync/once.go:59 +0x68
2021-03-22T00:42:18.430462224Z   github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run()
2021-03-22T00:42:18.430477157Z       /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:244 +0x64
2021-03-22T00:42:18.430576982Z 
2021-03-22T00:42:18.430742266Z Previous read at 0x0000050ade90 by goroutine 25:
2021-03-22T00:42:18.430912173Z   github.com/vishvananda/netlink.LinkDeserialize()
2021-03-22T00:42:18.430930359Z       /go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/link_linux.go:1792 +0x108d
2021-03-22T00:42:18.431031683Z   github.com/vishvananda/netlink.(*Handle).LinkList()
2021-03-22T00:42:18.431059243Z       /go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/link_linux.go:1937 +0x42a
2021-03-22T00:42:18.431160437Z   github.com/vishvananda/netlink.LinkList()
2021-03-22T00:42:18.431175219Z       /go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/link_linux.go:1915 +0x65
2021-03-22T00:42:18.431285563Z   github.com/cilium/cilium/pkg/datapath/link.(*ifNameCache).syncCache()
2021-03-22T00:42:18.431299802Z       /go/src/github.com/cilium/cilium/pkg/datapath/link/link.go:90 +0x45
2021-03-22T00:42:18.431395920Z   github.com/cilium/cilium/pkg/datapath/link.init.0.func1()
2021-03-22T00:42:18.431410983Z       /go/src/github.com/cilium/cilium/pkg/datapath/link/link.go:35 +0xc4
```
This stack trace from https://jenkins.cilium.io/view/Race%20Detection/job/Ginkgo-CI-Tests-Pipeline-GKE-Race-Detection/107/

Also observed in
- https://jenkins.cilium.io/view/Race%20Detection/job/Ginkgo-CI-Tests-k8s1.13-Pipeline-Race-Detection/101/
- https://jenkins.cilium.io/view/Race%20Detection/job/Ginkgo-CI-Tests-k8s1.13-Pipeline-Race-Detection/102/
- https://jenkins.cilium.io/view/Race%20Detection/job/Ginkgo-CI-Tests-k8s1.19-Pipeline-Race-Detection/78/
- https://jenkins.cilium.io/view/Race%20Detection/job/Ginkgo-CI-Tests-Pipeline-GKE-Race-Detection/106/
- https://jenkins.cilium.io/view/Race%20Detection/job/Ginkgo-CI-Tests-Pipeline-GKE-Race-Detection/108/

/Cc @christarazi @aanm

### PR DESCRIPTION
**Pull request by tklauser**
This pulls in https://github.com/vishvananda/netlink/pull/637 and
https://github.com/vishvananda/netlink/pull/648 with data race fixes.

Fixes #15438

Marked for `needs-backport/1.10` given that this fixes a data race and `go.mod` in the `v1.10` branch is currently at the same version of `github.com/vishvananda/netlink` as `master`.

### CODE REVIEW

**Comment by tklauser** [comment]
test-race-gke

**Review by qmonnet — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-runtime

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-runtime

**Comment by tklauser** [comment]
test-1.20-4.19

**Comment by tklauser** [comment]
test-1.19-5.4

**Comment by tklauser** [comment]
test-race-gke

**Comment by tklauser** [comment]
All required tests passed, the GKE-Race job failed on an unrelated flake (#16004 https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE-Race-Detection/19/). Marking as ready to merge.

**Pull request merged**
