### PR TITLE
ipsec: Change XFRM FWD policy to simplest wildcard

### PR DESCRIPTION
**Pull request by pchaigno**
This fixes the XFRM FWD policies and the IPv6 catch-all default-drop policy. See commits.

Fixes: https://github.com/cilium/cilium/pull/24030.
```release-note
Fix leak of IPsec XFRM FWD policies in IPAM modes `cluster-pool`, `kubernetes`, and `crd` when nodes are deleted.
Fix incorrect catch-all default-drop XFRM OUT policy for IPsec IPv6 traffic that could lead to leaking plain-text IPv6 traffic if combined with some other bug.
```

### CODE REVIEW

**Review by jschwinger233 — APPROVED** [review]

**Comment by pchaigno** [comment]
I needed to repush to address two issues. One in the first commit (see :point_down:) and another one fixed in the second commit.

> There's a small implementation hurdle here. Because we used to install FWD policies of the form "src 0.0.0.0/0 dst 10.0.1.0/24", the kernel was able to deduce which IP family we are matching against and would adapt the 0.0.0.0/0 source CIDR to ::/0 as needed. Now that we are matching on 0/0 for both CIDRs, it cannot deduce this anymore. So instead, we must detect the IP family ourself and use the proper CIDRs.

@jschwinger233 I've therefore re-requested a review from you just to be on the safe side :slightly_smiling_face:

**Review by jschwinger233 — APPROVED** [review]
Looks good! I actually noticed that mask for wildcard CIDR before, but I was thinking "yeah since it's been working as expected for long time, no reason there is an obvious bug unknown..." :sob:

**Pull request merged**
