### PR TITLE
bpf: fix build error when ipsec is enabled and tunneling disabled

### PR DESCRIPTION
**Pull request by borkmann**
If we don't have encap index defined (ENCAP_IFINDEX), then we also cannot
redirect to it. This compilation error is thrown instead:

  2019-03-16T08:38:33.30268603Z level=warning msg="/var/lib/cilium/bpf/bpf_netdev.c:548:11: warning: implicit declaration of function '__encap_and_redirect_with_nodeid' is invalid in C99 [-Wimplicit-function-declaration]" subsys=daemon
  2019-03-16T08:38:33.302694714Z level=warning msg="                        return __encap_and_redirect_with_nodeid(skb, tunnel_endpoint, seclabel, TRACE_PAYLOAD_LEN);" subsys=daemon
  2019-03-16T08:38:33.302702926Z level=warning msg="                               ^" subsys=daemon
  2019-03-16T08:38:33.302708262Z level=warning msg="1 warning generated." subsys=daemon

Fixes: 3b6245843aef ("cilium: ipsec, add BPF datapath encryption direction")
Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7425)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Review by jrfastab — COMMENTED** [review]
Will solve the build error but ipsec wont work at this point. I think it might be better to fix on the golang side and disable ipsec if its not in tunnel mode.  Better still would be to get the direct routing PR completed.

**Comment by borkmann** [comment]
> Will solve the build error but ipsec wont work at this point. I think it might be better to fix on the golang side and disable ipsec if its not in tunnel mode. Better still would be to get the direct routing PR completed.

Yeah as discussed offline, I'll follow-up disabling via daemon and also fix the doc.

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-docs-please

**Comment by borkmann** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by jrfastab** [comment]
LGTM we can fix direct routing soon but lets get this in now.

**Pull request merged**
