### PR TITLE
Cleanup cilium/proxy golang dependencies and golang dependencies

### PR DESCRIPTION
**Pull request by aanm**
This PR cleans up a couple of dependencies that are not really needed by cilium/proxy

After discussing with @jrajahalme we came into the conclusion that we were downloading golang dependencies to the developer VM that aren't necessary to build Cilium.

`cilium/proxy` will have its own Gopkg.toml file which contains the list of dependencies that envoy uses to generate the golang protobufs. 

Also pinned the gops that is installed in the cilium docker image as well as pinned down the version of innefassign installed in the cilium-builder image.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8064)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Testing cilium/proxy#13 to make sure cilium-envoy-builder still builds: https://quay.io/repository/cilium/cilium-envoy-builder/build/55c118c6-d14c-4d51-a158-b44f702683dc

**Comment by jrajahalme** [comment]
envoy-builder build passed, cilium/proxy#13 merged. Updated proxy APIs, new cilium/proxy master SHA is c8aa9b116d3244623292255863cadd314fb88c0e.

**Comment by aanm** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by jrajahalme** [comment]
@aanm How did you get `dep ensure -v` to pass with this? I get:
```
Solving failure: No versions of github.com/lyft/protoc-gen-validate met constraints:
	v0.0.13: Could not introduce github.com/lyft/protoc-gen-validate@v0.0.13, as it has a dependency on github.com/golang/protobuf with constraint ^1.2.0, which has no overlap with existing constraint v1.3.1 from (root)
	d75a15c1da0f853ca31399f30c49088ca5716b04: Could not introduce github.com/lyft/protoc-gen-validate@d75a15c1da0f853ca31399f30c49088ca5716b04, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	v0.0.14: Could not introduce github.com/lyft/protoc-gen-validate@v0.0.14, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	v0.0.13: Could not introduce github.com/lyft/protoc-gen-validate@v0.0.13, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	v0.0.12: Could not introduce github.com/lyft/protoc-gen-validate@v0.0.12, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	v0.0.11: Could not introduce github.com/lyft/protoc-gen-validate@v0.0.11, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	v0.0.10: Could not introduce github.com/lyft/protoc-gen-validate@v0.0.10, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	v0.0.9: Could not introduce github.com/lyft/protoc-gen-validate@v0.0.9, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	v0.0.8: Could not introduce github.com/lyft/protoc-gen-validate@v0.0.8, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	v0.0.7: Could not introduce github.com/lyft/protoc-gen-validate@v0.0.7, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	v0.0.6: Could not introduce github.com/lyft/protoc-gen-validate@v0.0.6, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	v0.0.5: Could not introduce github.com/lyft/protoc-gen-validate@v0.0.5, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	v0.0.4: Could not introduce github.com/lyft/protoc-gen-validate@v0.0.4, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	v0.0.3: Could not introduce github.com/lyft/protoc-gen-validate@v0.0.3, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	v0.0.2: Could not introduce github.com/lyft/protoc-gen-validate@v0.0.2, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	v0.0.1: Could not introduce github.com/lyft/protoc-gen-validate@v0.0.1, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	master: Could not introduce github.com/lyft/protoc-gen-validate@master, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	apr30-protobuf-changes: Could not introduce github.com/lyft/protoc-gen-validate@apr30-protobuf-changes, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	fix-nested-rules: Could not introduce github.com/lyft/protoc-gen-validate@fix-nested-rules, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
	fix-readme: Could not introduce github.com/lyft/protoc-gen-validate@fix-readme, as it is not allowed by constraint v0.0.13 from project github.com/cilium/proxy.
```

**Comment by aanm** [comment]
test-me-please

**Review by nebril — APPROVED** [review]
LGTM!

**Comment by ianvernon** [comment]
The following commit(s) from this PR were backported to v1.5:

* https://github.com/cilium/cilium/commit/f27130849a88ec74f1397705c659481de63c0509

**Pull request merged**
