### PR TITLE
Rename tunnel endpoint map to be more consistent

### PR DESCRIPTION
**Pull request by joestringer**
Rename the tunnel endpoint map so it has the same prefix as all of the
other cilium maps.

Would be nice to make this consistent before 1.0 just so we can reliably ensure that cilium stuff is under `/sys/fs/bpf/tc/globals/cilium_*`.

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by joestringer** [comment]
Adding upgrade-impact because it renames a map. This should 'just work' (TM), though the previously pinned copy of the previous named map may remain on the filesystem.

**Comment by joestringer** [comment]
Suspicious stacktrace in CI failure, retrying.

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:269
Pod did not finish as expected.
Expected error:
    <*errors.errorString | 0xc42037a480>: {
        s: "pod \"client-can-connect-80\" failed with status: {Phase:Failed Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-04-12 06:03:24 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-04-12 06:03:34 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [client-can-connect-80-container]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-04-12 06:03:24 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:192.168.36.12 PodIP:10.10.1.204 StartTime:2018-04-12 06:03:24 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:client-can-connect-80-container State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:1,Signal:0,Reason:Error,Message:,StartedAt:2018-04-12 06:03:28 +0000 UTC,FinishedAt:2018-04-12 06:03:33 +0000 UTC,ContainerID:docker://ebb4a13f28e1af7feae1d0ba35ab1b772a6aeb947a5b61f9b43516e9b952644b,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:busybox:latest ImageID:docker-pullable://busybox@sha256:58ac43b2cc92c687a32c8be6278e50a063579655fe3090125dcb2af0ff9e1a64 ContainerID:docker://ebb4a13f28e1af7feae1d0ba35ab1b772a6aeb947a5b61f9b43516e9b952644b}] QOSClass:BestEffort}",
    }
    pod "client-can-connect-80" failed with status: {Phase:Failed Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-04-12 06:03:24 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-04-12 06:03:34 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [client-can-connect-80-container]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-04-12 06:03:24 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:192.168.36.12 PodIP:10.10.1.204 StartTime:2018-04-12 06:03:24 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:client-can-connect-80-container State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:1,Signal:0,Reason:Error,Message:,StartedAt:2018-04-12 06:03:28 +0000 UTC,FinishedAt:2018-04-12 06:03:33 +0000 UTC,ContainerID:docker://ebb4a13f28e1af7feae1d0ba35ab1b772a6aeb947a5b61f9b43516e9b952644b,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:busybox:latest ImageID:docker-pullable://busybox@sha256:58ac43b2cc92c687a32c8be6278e50a063579655fe3090125dcb2af0ff9e1a64 ContainerID:docker://ebb4a13f28e1af7feae1d0ba35ab1b772a6aeb947a5b61f9b43516e9b952644b}] QOSClass:BestEffort}
not to have occurred
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Policies.go:644
```

**Comment by joestringer** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Comment by borkmann** [comment]
@joestringer Should we mark this to be backported then?

**Comment by joestringer** [comment]
I'll add something else to delete the old map name, then this can be backported along with that PR. I'll update here with the relevant details.

**Pull request merged**
