### PR TITLE
v1.7 backports 2020-04-01

### PR DESCRIPTION
**Pull request by joestringer**
* #10518 -- bpf: significantly improve capacity of TCP CT tables (@borkmann)
   * Had to rebase against CTX refactors in master, PTAL @borkmann
 * #10729 -- Fix incorrect name in sysctl_linux_test.go (@christarazi)
 * #10767 -- k8s: Defer marking node as ready to just API is served (@tgraf)
   * Had to import the `context` package which was not previously imported
 * #10785 -- pkg/allocator: do not fail to allocate identity in CRD mode (@aanm)
 * #10641 -- Add helm NOTES file (@soumynathan)
 * #10801 -- Kubernetes connectivity check fixes (@tgraf)
 * #10805 -- cilium, contrib: tighten permissions on systemd bpffs mount unit file (@borkmann)
 * #10790 -- pkg/k8s: fix heartbeat unit test (@aanm)

Not backported due to conflicts:
 * #10717 -- test: Fix kubectl log retrieval for badLogMessages (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10518 10729 10767 10785 10641 10801 10805 10790; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Comment by borkmann** [comment]
test-upstream-k8s

**Comment by borkmann** [comment]
test-upstream-k8s

**Comment by pchaigno** [comment]
test-upstream-k8s

**Comment by pchaigno** [comment]
test-upstream-k8s

**Review by aanm — APPROVED** [review]
LGTM for my commits

**Review by borkmann — APPROVED** [review]

**Comment by pchaigno** [comment]
test-upstream-k8s

**Pull request merged**
