### PR TITLE
cleanup: Remove vagrant related files

### PR DESCRIPTION
**Pull request by sayboras**
The Vagrant VM is no longer maintained in favor of kind cluster (local dev) and little vm helpers (CI), hence it's better to remove all vagrant related files.

### CODE REVIEW

**Review by nebril — APPROVED** [review]
amazing

**Comment by sayboras** [comment]
oops, I forgot that sometimes github didn't enforce for _all_ reviewers before merge. Please let me know if you have any comment on docs change, I will address in separate PR.

**Pull request merged**
