### PR TITLE
v1.1 backports 18-10-15

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:

#5882 

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5891)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
Build failed: 
```
20:06:41 pkg/endpoint/endpoint.go:2620:3: e.UnconditionalLock undefined (type *Endpoint has no field or method UnconditionalLock)
```

Will fix.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
K8s 1.11 tests timed out, and have no logs: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7267/execution/node/75/

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
