### PR TITLE
[1.14-backport] ipsec: Fix unencrypted traffic when IPsec is used with L7 egress proxy

### PR DESCRIPTION
**Pull request by jschwinger233**
- [x] https://github.com/cilium/cilium/pull/32683 @jschwinger233

### CODE REVIEW

**Comment by jschwinger233** [comment]
/test-backport-1.14

**Comment by jschwinger233** [comment]
/test-backport-1.14

**Comment by jschwinger233** [comment]
CI is almost green except ci-ipsec-e2e https://github.com/cilium/cilium/actions/runs/9400458006

image

ci-ipsec-e2e's failure is a known racing issue of leak detection that will be fixed by https://github.com/cilium/cilium/pull/32930.

I'll drop the last three leak detection patches and mark ready for review.

**Comment by jschwinger233** [comment]
/test-backport-1.14

**Review by qmonnet — APPROVED** [review]
Looks good thanks, bash script looks OK

**Pull request merged**
