### PR TITLE
v1.8 backports 2020-09-21

### PR DESCRIPTION
**Pull request by jrajahalme**
* #12964 -- daemon: Start DNS proxy before k8s with restored rules (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12964; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-backport-1.8

**Comment by aanm** [comment]
```
# github.com/cilium/cilium/pkg/proxy
vet: pkg/proxy/kafka_test.go:112:45: cannot use &(proxyUpdaterMock literal) (value of type *proxyUpdaterMock) as logger.EndpointUpdater value in variable declaration: missing method OnDNSPolicyUpdateLocked
Makefile:393: recipe for target 'govet' failed
make[1]: *** [govet] Error 2
make[1]: Leaving directory '/home/travis/gopath/src/github.com/cilium/cilium'
Makefile:209: recipe for target 'unit-tests' failed
make: *** [unit-tests] Error 2
```

**Comment by jrajahalme** [comment]
test-backport-1.8

**Comment by jrajahalme** [comment]
Fixed `pkg/proxy/kafka_test.go` (which does not exist in master)

**Comment by jrajahalme** [comment]
Fixed white space errors.

**Comment by jrajahalme** [comment]
test-backport-1.8

**Comment by jrajahalme** [comment]
`k8s-1.11-kernel-netnext` test fails to pull cilium operator for the old version in the upgrade/downgrade test, seems not releated to this PR:
```
Failed to pull image "docker.io/cilium/operator:v1.7": rpc error: code = Unknown desc = error pulling image configuration: unknown blob
```

**Review by rolinh — APPROVED** [review]

**Pull request merged**
