### PR TITLE
Split BPF ingress program into IPv4 and IPv6 handlers

### PR DESCRIPTION
**Pull request by joestringer**
This saves about 4.5K instructions complexity (~9%) on a Linux 4.9.17 kernel with GCC 7.2.0 and default datapath options from the config files under `bpf/`.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4867)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Green build. Will await another round of BPF datapath changes to go into master and rebase. This can still be reviewed in the mean time however.

**Review by tgraf — APPROVED** [review]

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Found a NACK in the logs (#4850?).

**Comment by joestringer** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]
lgtm

**Pull request merged**
