### PR TITLE
Support host firewall with IPv6 BPF masquerading

### PR DESCRIPTION
**Pull request by qmonnet**
[In progress]

### CODE REVIEW

**Comment by glennpratt** [comment]
@qmonnet is it time to merge this?

**Comment by qmonnet** [comment]
The PR needs a rebase, plus some validation from people more familiar with the host firewall than I am. Maybe some CI coverage as well. I do intend to come back to this at some point, but no ETA.

**Comment by qmonnet** [comment]
Completed in https://github.com/cilium/cilium/pull/28813 - Although we could merge the test updates from the current PR, too.

**Comment by qmonnet** [comment]
Now superseded by #31511

**Pull request closed without merging**
