### PR TITLE
helm: Fix typo in dashboard path

### PR DESCRIPTION
**Pull request by jcpunk**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/master/USERS.md)
- [ ] Thanks for contributing!

Resolve typo in path for cillium dashboards

Fixes: bdbb1294f251f ("helm: Add example dashboards as chart options ")

### CODE REVIEW

**Comment by sathieu** [comment]
Thanks @jcpunk!

**Review by gandro — COMMENTED** [review]
Thanks! Would you mind adding a `Fixes: bdbb1294f251f ("helm: Add example dashboards as chart options ")` to the commit description? 

c.f. https://docs.cilium.io/en/v1.13/contributing/development/contributing_guide/#submit-pr

Thanks

**Review by gandro — APPROVED** [review]
Looks good, thanks!

**Review by tommyp1ckles — APPROVED** [review]

**Comment by gandro** [comment]
- Jenkins CI all failed with ` controller write-cni-file failure 'failed to render CNI configuration file: invalid CNI chaining mode: '` - this unrelated to this PR (it's also happening on other PRs) and caused by a desync issue due to [changes to the Helm charts](https://github.com/cilium/cilium/pull/24389) present on master which are pulled in by Jenkins, but not present on this branch. 
- ci-verifier failed with unrelated new flake: https://github.com/cilium/cilium/issues/24808

Since none of the code here is tested by Jenkins CI or related to BPF, I am marking this PR as ready to merge.

**Pull request merged**
