### PR TITLE
ci: check if gke cluster has a nodepool before reserving it

### PR DESCRIPTION
**Pull request by nebril**

### CODE REVIEW

**Comment by nebril** [comment]
test-gke

**Review by pchaigno — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
marking as ready to merge, as gke passed.

**Pull request merged**
