### PR TITLE
Remove unused functions in pkg/comparator

### PR DESCRIPTION
**Pull request by pippolo84**
Remove unused functions in pkg/comparator and replace all usages of `comparator.MapStringEquals` with `maps.Equal` from the Go standard library (as suggested in this [review comment](https://github.com/cilium/cilium/pull/29222#discussion_r1425327301) by @giorio94).
Since we are at it, migrate the comparator pkg tests from [checkmate](https://github.com/cilium/cilium/pull/25484) to the standard Go testing library.

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
Thanks!

**Review by squeed — APPROVED** [review]

**Comment by pippolo84** [comment]
Force-pushed to fix a conflict in `pkg/k8s/watchers/cilium_node.go`

**Review by ldelossa — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]

**Pull request merged**
