### PR TITLE
docs: Update docs with minimum helm version

### PR DESCRIPTION
**Pull request by aditighag**
Helm install may fail with following error on older versions - 

`Error: parse error at (cilium/templates/validate.yaml:38): unclosed action`

Suggested-by: Chris Tarazi <chris@isovalent.com>

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
💯

**Review by christarazi — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Review by qmonnet — COMMENTED** [review]
I'm not opposed to the upgrade, but I'm wondering if there would be an easy fix for the YAML file instead of forcing users to install a more recent version of Helm.

Your error message mentions line 38 of the YAML file. Could it be something as simple as the different parts of the `if` not being in the same line in commit https://github.com/cilium/cilium/commit/1d62cadccaeacac94a65bf7ec4e3ca41606529df? Just in case, did you try something like this:

```diff
diff --git a/install/kubernetes/cilium/templates/validate.yaml b/install/kubernetes/cilium/templates/validate.yaml
index 6c0ffed94563..3757aacab26f 100644
--- a/install/kubernetes/cilium/templates/validate.yaml
+++ b/install/kubernetes/cilium/templates/validate.yaml
@@ -35,9 +35,7 @@
 {{- end }}
 
 {{/* validate hubble-ui specific config */}}
-{{- if and .Values.hubble.ui.enabled
-  (ne .Values.hubble.ui.backend.image.tag "latest")
-  (ne .Values.hubble.ui.frontend.image.tag "latest") }}
+{{- if and .Values.hubble.ui.enabled (ne .Values.hubble.ui.backend.image.tag "latest") (ne .Values.hubble.ui.frontend.image.tag "latest") }}
   {{- if regexReplaceAll "@.*$" .Values.hubble.ui.backend.image.tag "" | trimPrefix "v" | semverCompare "<0.9.0" }}
     {{ fail "Hubble UI requires hubble.ui.backend.image.tag to be '>=v0.9.0'" }}
   {{- end }}
```

**Comment by aditighag** [comment]
> I'm not opposed to the upgrade, but I'm wondering if there would be an easy fix for the YAML file instead of forcing users to install a more recent version of Helm.
> 
> Your error message mentions line 38 of the YAML file. Could it be something as simple as the different parts of the `if` not being in the same line in commit [1d62cad](https://github.com/cilium/cilium/commit/1d62cadccaeacac94a65bf7ec4e3ca41606529df)? Just in case, did you try something like this:
> 
> ```diff
> diff --git a/install/kubernetes/cilium/templates/validate.yaml b/install/kubernetes/cilium/templates/validate.yaml
> index 6c0ffed94563..3757aacab26f 100644
> --- a/install/kubernetes/cilium/templates/validate.yaml
> +++ b/install/kubernetes/cilium/templates/validate.yaml
> @@ -35,9 +35,7 @@
>  {{- end }}
>  
>  {{/* validate hubble-ui specific config */}}
> -{{- if and .Values.hubble.ui.enabled
> -  (ne .Values.hubble.ui.backend.image.tag "latest")
> -  (ne .Values.hubble.ui.frontend.image.tag "latest") }}
> +{{- if and .Values.hubble.ui.enabled (ne .Values.hubble.ui.backend.image.tag "latest") (ne .Values.hubble.ui.frontend.image.tag "latest") }}
>    {{- if regexReplaceAll "@.*$" .Values.hubble.ui.backend.image.tag "" | trimPrefix "v" | semverCompare "<0.9.0" }}
>      {{ fail "Hubble UI requires hubble.ui.backend.image.tag to be '>=v0.9.0'" }}
>    {{- end }}
> ```

Not sure. I already upgraded helm, and that resolved the issue.

**Review by joestringer — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]
I still believe it would be nice to check, but if everybody else agrees on this it's probably not worth spending more time on it. Ack

**Pull request merged**
