### PR TITLE
Factor nodediscovery out of daemon

### PR DESCRIPTION
**Pull request by nebril**
This is done so https://github.com/cilium/node-discovery-perf works.

Also, it's always nice to have less stuff in `daemon`

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7141)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
