### PR TITLE
test: update k8s test versions to 1.16.15 and 1.17.12

### PR DESCRIPTION
**Pull request by aanm**
Also update Kubernetes libraries to 1.17.12

Signed-off-by: André Martins <andre@cilium.io>

```release-note
Update Kubernetes libraries to 1.17.12
```

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.7

**Comment by aanm** [comment]
retest-ginkgo

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-ginkgo

**Comment by pchaigno** [comment]
restart-ginkgo

**Comment by aanm** [comment]
restart-ginkgo

**Comment by aanm** [comment]
restart-ginkgo

**Review by christarazi — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
Failure looks actually related to changes I had made previously, I'll send a fix:

```
07:37:55      runtime: ../cilium-health/cilium-health --cmdref /tmp/tmp.MJOfxxzUEo
07:37:55      runtime: ../operator/cilium-operator --cmdref /tmp/tmp.MJOfxxzUEo
07:37:55      runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/Documentation'
07:37:55      runtime: diff -x '*.rst' -r ./Documentation/cmdref/cilium-operator.md /tmp/tmp.MJOfxxzUEo/cilium-operator.md
07:37:55      runtime: 34a35
07:37:55      runtime: >       --enable-k8s-event-handover                 Enable k8s event handover to kvstore for improved scalability
07:37:55      runtime: Detected a difference in the cmdref directory
07:37:55      runtime: diff -r: diff -r ./Documentation/cmdref/cilium-operator.md /tmp/tmp.MJOfxxzUEo/cilium-operator.md
07:37:55      runtime: 34a35
07:37:55      runtime: >       --enable-k8s-event-handover                 Enable k8s event handover to kvstore for improved scalability
07:37:55      runtime: Only in ./Documentation/cmdref: cli_index.rst
07:37:55      runtime: Only in ./Documentation/cmdref: index.rst
07:37:55      runtime: Only in ./Documentation/cmdref: kvstore.rst
07:37:55      runtime: Please rerun 'make -C Documentation cmdref' and commit your changes
07:37:55      runtime: Makefile:443: recipe for target 'postcheck' failed
07:37:55      runtime: make: *** [postcheck] Error 1
```

**Comment by aanm** [comment]
merging since Joe will fix the failure in another backport PR

**Pull request merged**
