### PR TITLE
v1.13 Backports 2023-10-06

### PR DESCRIPTION
**Pull request by sayboras**
* [x] #26956 (@julianwiedmann)
    * :warning: small conflict for bpf/bpf_lxc.c as high ipcache block is not avaialble 
 * [ ] #28358 (@gandro)
 * [x] #28258 (@pchaigno)
 * [x] #28392 (@giorio94)
 * [ ] #28403 (@raphink)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 26956 28358 28258 28392 28403
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.13

**Review by julianwiedmann — APPROVED** [review]
> * small conflict for bpf/bpf_lxc.c as high ipcache block is not avaialble

ack, see https://github.com/cilium/cilium/pull/26956#issuecomment-1744683350. Thanks :pray: .

**Review by giorio94 — APPROVED** [review]
My commit looks good, thanks!

**Review by ti-mo — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Comment by sayboras** [comment]
Most of the reviews are in, CI is green, so let's merge it in.

**Pull request merged**
