### PR TITLE
Use watcher to track unmanaged kube-dns pods in Cilium Operator

### LINKED ISSUE #11466: Do not list kube-dns pods in cilium-operator
https://github.com/cilium/cilium/blob/588f8352adac37a33a58ea7db602d03be2d96720/operator/k8s_pod_controller.go#L50-L57

This list is filtered in kube-apiserver so it does not help for large clusters fetching an entire list of pods which can cause load in etcd.

depends on #11376

### PR DESCRIPTION
**Pull request by aanm**
Listing all pods, even if with a filter will load the etcd kvstore as
the filtering is done in kube-apiserver. To avoid doing this operation
every 10 seconds we can have a single watcher that keeps track of all
unmanaged kube-dns pods locally.

Fixes https://github.com/cilium/cilium/issues/11466

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
will need rebase once https://github.com/cilium/cilium/pull/11435 is merged

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by qmonnet — APPROVED** [review]
Looks good to me

**Comment by aanm** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]

**Comment by aanm** [comment]
retest-net-next

**Comment by aanm** [comment]
K8s1.17 hit https://github.com/cilium/cilium/issues/11314

**Pull request merged**
