### PR TITLE
bpf: fix session affinity timeout test flake

### LINKED ISSUE #13641: CI: k8s upstream tests failing in session affinity test cases
Example failures:
https://jenkins.cilium.io/job/cilium-master-K8s-Upstream/485/execution/node/67/log/
https://jenkins.cilium.io/job/cilium-master-K8s-Upstream/484
https://jenkins.cilium.io/job/cilium-master-K8s-Upstream/483

https://github.com/cilium/cilium/pull/13480 was supposed to help here, but the test still failed: https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/2601/

### PR DESCRIPTION
**Pull request by fristonio**
See commit message for more details.
Fixes #13641

### CODE REVIEW

**Comment by fristonio** [comment]
test-upstream-k8s

**Review by borkmann — APPROVED** [review]

**Comment by fristonio** [comment]
test-me-please

**Review by jibi — APPROVED** [review]

**Comment by aanm** [comment]
Do we need to backport it to earlier branches?

**Comment by borkmann** [comment]
> Do we need to backport it to earlier branches?

Yeah we should for 1.8 at least.

**Review by brb — APPROVED** [review]
Thanks!

**Comment by brb** [comment]
> Yeah we should for 1.8 at least.

Yeah, only to 1.{8,9}, as the feature was introduced in v1.8.

**Pull request merged**
