### PR TITLE
backports 1.6 2019 11 05

### PR DESCRIPTION
**Pull request by raybejjani**
* PR: 9395 -- xds: Allow endpoints to wait for the current policy version to be acked (@jrajahalme) -- https://github.com/cilium/cilium/pull/9395
   * @jrajahalme For "xds: Allow endpoints to wait for the current policy version to be acked" (ccbd64f84a2fc1d53736fd746914c22533386b68) I had to 
pkg/proxy/proxy.go: Remove new useCurrentNetworkPolicy because Endpoint.updateNetworkPolicy does that
pkg/endpoint/proxy.go: Skip the comment change because the function already exists in daemon
pkg/endpoint/redirect_test.go: Not fixup the dummy 

 * PR: 9534 -- docs: clarify usage of bpf fs mount (@aanm) -- https://github.com/cilium/cilium/pull/9534

 * PR: 9481 -- endpoint: Do not fail to regenerate endpoint when running w/o L7 proxy (@brb) -- https://github.com/cilium/cilium/pull/9481
@brb I skipped "endpoint: Do not fail to regenerate w/o L7 proxy (44753289d7839e966491612181a9b256e41ff282)
skipped because daemon already has this logic in 1.6

 * PR: 9541 -- Clean up endpoint labels resolver on endpoint removal (@joestringer) -- https://github.com/cilium/cilium/pull/9541
   * @joestringer  For "endpoint: Run labels controller under ep manager" (a31ab29f57b2ea915fa82b8598593252cf638533)
I excluded ep.UpdateVisibilityPolicy(annotations[annotation.ProxyVisibility]) because the commit adding the annotations handling isn't backported ("endpoint: add `VisibilityPolicy` field and plumbing logic "45f6426695f081a14aba7d4b670d8a5e2e935205)
I also excluded controller.Context = e.aliveCtx because 1.6 controllers don't have this parameter

 * PR: 9542 -- Envoy 1.12 update (@jrajahalme) -- https://github.com/cilium/cilium/pull/9542
@jrajahalme I manually applied "envoy: Update to release 1.12 with Cilium TLS support" (95487c9578da401559b6ad0cc449b47edeb96885)

 * PR: 9491 -- Fix cilium-health node updates (@joestringer) -- https://github.com/cilium/cilium/pull/9491

 * PR: 9535 -- pkg/k8s: fix toServices policy update when service endpoints are modified (@aanm) -- https://github.com/cilium/cilium/pull/9535
@aanm For "pkg/k8s: fix toServices policy update when service endpoints are modified" (0c6cb2663b7cdef3716dbdd78ead4339c0177966) I didn't port the tests because I didn't want to figure out how to initialise the daemon for it.

 * PR: 9537 -- KVStore and k8s bug fixes (@aanm) -- https://github.com/cilium/cilium/pull/9537

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9553)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Review by aanm — CHANGES_REQUESTED** [review]
@raybejjani do not backport https://github.com/cilium/cilium/pull/9553/commits/e31e2bfa6584f87b4144b87656b43edadee648a8 I'll do this manually

**Comment by raybejjani** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
The backports for PRs I authored LGTM.

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
@jrajahalme I think my backport of the envoy changes it the culprit with test failures. I see a lot of:
```
[[external/envoy/source/server/server.cc:93] error initializing configuration '/var/run/cilium/bootstrap.pb': cluster: cluster type 'original_dst' may only be used with LB type 'original_dst_lb'
[[external/envoy/source/common/runtime/runtime_impl.cc:497] Skipping unsupported runtime layer: name: \
static_layer {
}
Envoy: Proxy crashed
```

Does this mean the backport was bad, and I should try again? or that there is a deeper mismatch here and that I should pull #9395 and/or #9542 out?

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
omfg github

**Comment by raybejjani** [comment]
test-me-please

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by raybejjani** [comment]
@aanm I'm guessing you're ok with the remaining changes.
@jrajahalme Let me know if something seems wrong to you. I will time-out and merge otherwise

**Review by aanm — APPROVED** [review]

**Pull request merged**
