### PR TITLE
Test/K8s: Added debug logs in cilium DS

### PR DESCRIPTION
**Pull request by eloycoto**
Added ciliumDS in cilium daemonsets. 

@cilium/janitors I think that should be backported. 

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
@eloycoto agreed, adding needs-backport label.

**Comment by joestringer** [comment]
@ianvernon Is there anything the backporter needs to know about this commit? Are we safe to backport it now?

**Pull request merged**
