### PR TITLE
jenkinsfiles: use quay.io images in Jenkins

### PR DESCRIPTION
**Pull request by nbusseneau**
1.9 pipelines were still building images on the spot and storing them in a local Docker instance on the nodes. This was working fine up until the GKE node decided not to cooperate with certificate issues resulting in all 1.9 GKE tests failing due to `ImagePullBackOff` errors.

Trying to fix the certificate issues eventually turned out to be a mess, with issues such as `x509: cannot validate certificate for 147.75.55.179 because it doesn't contain any IP SANs` and `x509: certificate signed by unknown authority`, even though manual testing was confirming the certificate to be valid and contain the proper SANs.

To work around the issue, we change 1.9 Jenkins pipelines to use quay.io images as we do since 1.10, removing the need for local image builds and as a bonus should speed up the pipelines a little bit.

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
test-backport-1.9

**Comment by nbusseneau** [comment]
/test-1.19-4.9

**Comment by nbusseneau** [comment]
/test-backport-1.9

**Review by pchaigno — APPROVED** [review]

**Comment by aanm** [comment]
@nbusseneau I assume the tests shouldn't have failed that much? :thinking:

**Comment by nbusseneau** [comment]
@aanm I don't know why they failed here specifically on the upgrade/downgrade tests, and of course now the jobs are gone. I will retrigger the CI.

**Comment by nbusseneau** [comment]
/test-backport-1.9

**Comment by nbusseneau** [comment]
/test-backport-1.9

**Comment by nbusseneau** [comment]
So there is definitely an issue with `K8sUpdates Tests upgrade and downgrade from a Cilium stable image to master`, and we also hit `K8sChaosTest Restart with long lived connections TCP connection is not dropped when cilium restarts` on both GKE retries.

For GKE / K8sChaosTest, it seems the `netperf-server` loses connectivity:
```
Warning  Unhealthy  26s (x21 over 3m46s)  kubelet            Readiness probe errored: command "netperf -H 127.0.0.1 -l 1" timed out
```
However I fail to see how this is related to the PR.

For upgrade/downgrade tests, I think we are hitting something similar to #15059. Investigating.

**Comment by nbusseneau** [comment]
I have issues reproducing this locally, but while debugging I'm not quite sure the images used are the same. I think this comes from the way Ginkgo arguments are passed down in our CI. Will continue tomorrow.

**Pull request closed without merging**
