### PR TITLE
Backport/v1.0 2018 04 30

### PR DESCRIPTION
**Pull request by raybejjani**
- endpoint: Improve logging of endpoint lifecycle events 
[ upstream commit 12b6876da414a50308ecafa1932c0b9c2fbd7843 ]
https://github.com/cilium/cilium/pull/3936

- policy: Do not enable DROP_ALL mode if not needed.
[ upstream commit fb333388579c20a4ca9a6e286520b81f7701647c ]
https://github.com/cilium/cilium/pull/3938

- Adds flag to clean up cilium state before startup
[ upstream commit 38ba456dff36f041d586c0dc9f03f7a1362f84f8 ]
https://github.com/cilium/cilium/pull/3852

### CODE REVIEW

**Comment by raybejjani** [comment]
@abhide15 I had a merge conflict when backporting https://github.com/cilium/cilium/pull/3852 but it was in the kubernetes examples. I regenerated them and committed them but could you review to ensure I didn't pull in something incorrect?

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
@abhide15 As a janitor I'm hesitating the approval as I'm not fully versed in things k8s.

**Comment by raybejjani** [comment]
@abhide15 @jrajahalme I forgot to mention. I compared the commit here to the one in the original PR. Most of the changes are the same. The exception is the combined example file (the */cilium.yaml files). We changed the order in which files are catted into that one, and I think the diff just reflects that.

**Comment by abhide15** [comment]
@raybejjani thanks! Will take a look.

**Review by tgraf — APPROVED** [review]

**Pull request merged**
