### PR TITLE
v1.13 Backports 2023-06-22

### PR DESCRIPTION
**Pull request by nbusseneau**
* [ ] #22918 (@vipul-21)
 * [x] #25259 (@giorio94)
 * [ ] #25908 (@jrajahalme)
 * [x] #26047 (@julianwiedmann)
 * [x] #26115 (@julianwiedmann)
 * [x] #25956 (@jcpunk)
 * [x] #26189 (@jibi)
 * [x] #26037 (@jrajahalme)
 * [x] #26108 (@ti-mo)
 * [x] #26005 (@jrajahalme)
 * [x] #26211 (@qmonnet)
 * [ ] #26016 (@amitmavgupta)
 * [ ] #26092 (@peterj)
 * [ ] #26180 (@wedaly)
 * [x] #26130 (@brb)
 * [x] #26113 (@jschwinger233)
 * [ ] #26015 (@amitmavgupta)
 * [x] #26278 (@joestringer)
 * [ ] #25851 (@cyclinder)

PRs skipped due to conflicts:

 * #26118 (@julianwiedmann)
 * #26136 (@ldelossa)
 * #26290 (@julianwiedmann)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 22918 25259 25908 26047 26115 25956 26189 26037 26108 26005 26211 26016 26092 26180 26130 26113 26015 26278 25851; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=22918,25259,25908,26047,26020,26115,25956,26189,26037,26108,26005,26211,26016,26092,26180,26130,26113,26015,26278,25851
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.13

**Review by jschwinger233 — APPROVED** [review]

**Review by brb — APPROVED** [review]
Thanks!

**Review by giorio94 — APPROVED** [review]
My commit looks good. Thanks!

**Review by jibi — APPROVED** [review]

**Review by ti-mo — APPROVED** [review]

**Comment by qmonnet** [comment]
- https://github.com/cilium/cilium/pull/26211

Looks all in order, thanks!

**Review by qmonnet — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Comment by nbusseneau** [comment]
1.22 / 4.19 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/80/ has hit our old friend #25467.

**Comment by nbusseneau** [comment]
/test-1.22-4.19

**Review by jrajahalme — APPROVED** [review]
Looks good for my PRs :)

**Comment by nbusseneau** [comment]
CI passed and most reviews are in (most importantly those for commits with conflicts), marking ready to merge.

**Review by jcpunk — APPROVED** [review]

**Pull request merged**
