### PR TITLE
Prepare for 1.3.0 release

### PR DESCRIPTION
**Pull request by tgraf**
1. Backports of:
- #5950
- #5956
- #5957
- #5958
- #5964

2. Prepare for 1.3.0 release

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5965)

### CODE REVIEW

**Review by ianvernon — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
I believe tests will not pass because the tag does not exist yet on docker hub?

**Comment by tgraf** [comment]
runtime passed
k8s 1.8 passed
k8s 1.12 failed (etcd cluster scale down)

**Pull request merged**
