### PR TITLE
jenkinsfile: Allow enabling host firewall in k8s-all CI

### PR DESCRIPTION
**Pull request by pchaigno**

### CODE REVIEW

**Review by christarazi — APPROVED** [review]

**Comment by pchaigno** [comment]
test-missed-k8s

**Comment by pchaigno** [comment]
test-missed-k8s

**Comment by pchaigno** [comment]
test-missed-k8s

**Comment by pchaigno** [comment]
test-missed-k8s

**Comment by pchaigno** [comment]
test-missed-k8s

**Comment by pchaigno** [comment]
test-missed-k8s

**Comment by pchaigno** [comment]
I think this is ready to merge given Cilium-PR-Ginkgo-Tests-K8s failed with what looks like an unrelated flake (unrelated test & different test failed before). Marking as ready-to-merge.

**Review by gandro — APPROVED** [review]

**Pull request merged**
