### PR TITLE
v1.11 backports 2022-11-09

### PR DESCRIPTION
**Pull request by pchaigno**
* #21831 -- docs: Remove `autoDirectNodeRoutes` where not needed (@pchaigno)
 * #21064 -- Add a section with distro-specific considerations (@bmcustodio)
     - Minor conflict on `Documentation/operations/system_requirements.rst`.
 * #21526 -- ipam: Fix overlapping/duplicate PodCIDR allocation when nodes are added while operator is down (@dylandreimerink)
     - Non-trivial conflicts. Please review carefully :warning:
 * #21897 -- docs: Reword note in Azure CNI chaining documentation (@wedaly)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 21831 21064 21526 21897; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Comment by pchaigno** [comment]
/test-backport-1.11

**Review by michi-covalent — APPROVED** [review]

**Comment by dylandreimerink** [comment]
The unit test included in #21526 somehow triggers a nil pointer deference in `operator.startSynchronizingCiliumNodes`. I will need to do some investigation on why(original stack trace is gone, panic is caught and re-thrown by error handling in the test). So I will have to make a dedicated backport PR with a bugfix for v1.11.

**Comment by pchaigno** [comment]
/test-backport-1.11

**Comment by michi-covalent** [comment]
- test-gke: failed with a known flake: https://github.com/cilium/cilium/issues/21175

**Review by michi-covalent — APPROVED** [review]

**Pull request merged**
