### PR TITLE
Initialize default flag configurations (datapath)

### PR DESCRIPTION
**Pull request by joestringer**
Explicitly initialize the default flags for configuring datapath components.

Towards: #34134

### CODE REVIEW

**Comment by joestringer** [comment]
Hi @jschwinger233 could you take a look? This should hopefully make no logical changes, it's primarily just explicitly outlining the default configurations so we can later do some better linting as part of the CI smoke tests.

**Review by jschwinger233 — APPROVED** [review]
Thank you! This review request didn't show up in my https://github.com/notifications?query=reason%3Areview-requested, and my email was full of CI notifications so I also missed your ping yesterday :persevere:

**Comment by joestringer** [comment]
@jschwinger233 oh I see! Personally I find that this link is a lot more helpful: https://github.com/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+user-review-requested%3A%40me+sort%3Aupdated-asc+user%3Acilium+user%3Aisovalent+ .

Thanks for the review.

**Pull request merged**
