### PR TITLE
V1.0 backports 2018-04-06

### PR DESCRIPTION
**Pull request by jrajahalme**

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Due missing labels bpf backports have been applied out of order and some individual commits may fail to build due to manual conflict resolution. The end result is the same as current master, as the daemon/bpf.sha is the same.

**Comment by jrajahalme** [comment]
Turns out the earlier bpf commits that were now applied later, if squashed together mostly disappear, I'll squash them together.

**Comment by jrajahalme** [comment]
Added this text to the commit message of "bpf: Apply egress CIDR policy to reserved identities":
```    
    Merge squashed in these upstream commits as well:
    
    [ upstream commit bdbb62252020df34119c9b294cc293dc0f007b5e ]
    [ upstream commit f48021c33893302d0cdb4e077cc081aaaa047c4d ]
    [ upstream commit f34524168b82657b2f17d324bf4537852f92caaf ]
    [ upstream commit 97836ccb76fdf3d88503f37cdb1b1eff1357d335 ]
    [ upstream commit 2d7f8af971d546a8504f112a925b31d5d71a29c7 ]
```

**Comment by jrajahalme** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
