### PR TITLE
k8s: update k8s libraries to 1.19.4

### PR DESCRIPTION
**Pull request by aanm**
Also update k8s test versions to 1.17.14 and 1.18.12

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Review by brb — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Review by christarazi — APPROVED** [review]

**Pull request merged**
