### PR TITLE
Make k8s-cilium-exec.sh friendlier to read

### PR DESCRIPTION
**Pull request by weizhoublue**
the debug script k8s-cilium-exec.sh is used to execute command on all cilium-agent pods 
but its output is not friendly to figure out which node each output section belongs to
for example , below output is for 2-nodes cluster , if an issue is happening , we could not tell which node the issue is happening on
```
# ./k8s-cilium-exec.sh  cilium status
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.22 (v1.22.1) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEgressNATPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumLocalRedirectPolicy", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Probe   [ens192 172.110.185.60 fd00:110::172:110:185:60 (Direct Routing), ens224 10.6.185.60 fd00:6::10:6:185:60]
Cilium:                 Ok   1.10.4 (v1.10.4-2a46fd6)
NodeMonitor:            Listening for events on 8 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok
IPAM:                   IPv4: 9/254 allocated from 172.60.0.0/24, IPv6: 9/18446744073709551614 allocated from fc06:1::/64
ClusterMesh:            1/1 clusters ready, 8 global-services
BandwidthManager:       EDT with BPF   [ens192, ens224]
Host Routing:           Legacy
Masquerading:           BPF   [ens192, ens224]   172.61.0.0/16 [IPv4: Enabled, IPv6: Enabled]
Controller Status:      54/54 healthy
Proxy Status:           OK, ip 172.60.0.27, 0 redirects active on ports 10000-20000
Hubble:                 Ok   Current/Max Flows: 65535/65535 (100.00%), Flows/s: 16.49   Metrics: Ok
Encryption:             Disabled
Cluster health:         4/4 reachable   (2021-11-24T08:47:15Z)
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.22 (v1.22.1) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEgressNATPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumLocalRedirectPolicy", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Probe   [ens192 172.110.185.65 fd00:110::172:110:185:65 (Direct Routing), ens224 10.6.185.65 fd00:6::10:6:185:65]
Cilium:                 Ok   1.10.4 (v1.10.4-2a46fd6)
NodeMonitor:            Listening for events on 8 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok
IPAM:                   IPv4: 14/254 allocated from 172.60.1.0/24, IPv6: 14/18446744073709551614 allocated from fc06:1:0:1::/64
ClusterMesh:            1/1 clusters ready, 8 global-services
BandwidthManager:       EDT with BPF   [ens192, ens224]
Host Routing:           Legacy
Masquerading:           BPF   [ens192, ens224]   172.61.0.0/16 [IPv4: Enabled, IPv6: Enabled]
Controller Status:      75/75 healthy
Proxy Status:           OK, ip 172.60.1.174, 0 redirects active on ports 10000-20000
Hubble:                 Ok   Current/Max Flows: 65535/65535 (100.00%), Flows/s: 23.58   Metrics: Ok
Encryption:             Disabled
Cluster health:         4/4 reachable   (2021-11-24T08:46:55Z)
``` 

I add the the pod and node information for each output section , so it is easy to find where an error is happening
```
# ./k8s-cilium-exec.sh  cilium status
==== detail from pod cilium-8fv96 , on node 172-110-185-65
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.22 (v1.22.1) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEgressNATPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumLocalRedirectPolicy", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Probe   [ens192 172.110.185.65 fd00:110::172:110:185:65 (Direct Routing), ens224 10.6.185.65 fd00:6::10:6:185:65]
Cilium:                 Ok   1.10.4 (v1.10.4-2a46fd6)
NodeMonitor:            Listening for events on 8 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok
IPAM:                   IPv4: 14/254 allocated from 172.60.1.0/24, IPv6: 14/18446744073709551614 allocated from fc06:1:0:1::/64
ClusterMesh:            1/1 clusters ready, 8 global-services
BandwidthManager:       EDT with BPF   [ens192, ens224]
Host Routing:           Legacy
Masquerading:           BPF   [ens192, ens224]   172.61.0.0/16 [IPv4: Enabled, IPv6: Enabled]
Controller Status:      75/75 healthy
Proxy Status:           OK, ip 172.60.1.174, 0 redirects active on ports 10000-20000
Hubble:                 Ok   Current/Max Flows: 65535/65535 (100.00%), Flows/s: 23.58   Metrics: Ok
Encryption:             Disabled
Cluster health:         4/4 reachable   (2021-11-24T08:46:55Z)

==== detail from pod cilium-297wj , on node 172-110-185-60
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.22 (v1.22.1) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEgressNATPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumLocalRedirectPolicy", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Probe   [ens192 172.110.185.60 fd00:110::172:110:185:60 (Direct Routing), ens224 10.6.185.60 fd00:6::10:6:185:60]
Cilium:                 Ok   1.10.4 (v1.10.4-2a46fd6)
NodeMonitor:            Listening for events on 8 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok
IPAM:                   IPv4: 9/254 allocated from 172.60.0.0/24, IPv6: 9/18446744073709551614 allocated from fc06:1::/64
ClusterMesh:            1/1 clusters ready, 8 global-services
BandwidthManager:       EDT with BPF   [ens192, ens224]
Host Routing:           Legacy
Masquerading:           BPF   [ens192, ens224]   172.61.0.0/16 [IPv4: Enabled, IPv6: Enabled]
Controller Status:      54/54 healthy
Proxy Status:           OK, ip 172.60.0.27, 0 redirects active on ports 10000-20000
Hubble:                 Ok   Current/Max Flows: 65535/65535 (100.00%), Flows/s: 16.49   Metrics: Ok
Encryption:             Disabled
Cluster health:         4/4 reachable   (2021-11-24T08:46:15Z)
```

Signed-off-by: weizhou Lan <weizhou.lan@daocloud.io>

### CODE REVIEW

**Comment by weizhouBlue** [comment]
Signed-off-by: weizhou Lan weizhou.lan@daocloud.io

**Review by joestringer — CHANGES_REQUESTED** [review]
Thanks, this is easier to read.

Please fix up the author and signoff using the following commands, and then force push to update the PR:

```
git config --global user.name "weizhou Lan"
git commit --amend --reset-author --signoff
```

**Review by aditighag — APPROVED** [review]
Nice improvement! Approved, pending comment from Joe.

**Comment by nbusseneau** [comment]
@weizhouBlue Thanks for your contribution! As noted above by Joe, we require the commit description to include sign-offs. Can you please amend your commit so that we can merge your PR?

**Comment by weizhouBlue** [comment]
@joestringer @nbusseneau 
apologize for the late response , many thanks for reminding

**Review by nbusseneau — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
