### PR TITLE
v1.6 backports 2020-02-20

### PR DESCRIPTION
**Pull request by nebril**
* #10168 -- pkg/bpf: Protect each uintptr with runtime.KeepAlive (@brb)
* #10187  -- bpf: remove unused GetProgNextID, GetProgFDByID and GetProgInfoByFD (@tklauser)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10168 10187 ; do contrib/backporting/set-labels.py $pr done 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10267)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
never-tell-me-the-odds

**Comment by brb** [comment]
@nebril Can you please pull https://github.com/cilium/cilium/pull/10187 as well into this backport?

**Comment by nebril** [comment]
never-tell-me-the-odds

**Review by brb — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
LGTM for my change.

**Pull request merged**
