### PR TITLE
bpf: nat: fix L4 csum case in ingress path for ICMP-embedded SCTP

### PR DESCRIPTION
**Pull request by julianwiedmann**
We can't adjust the L4 csum for a SCTP packet yet.

### CODE REVIEW

**Review by gentoo-root — APPROVED** [review]

**Comment by julianwiedmann** [comment]
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-4.19/2036/testReport/junit/Suite-k8s-1/25/K8sDatapathConfig_Host_firewall_With_VXLAN/ is https://github.com/cilium/cilium/issues/15455

**Comment by julianwiedmann** [comment]
/test-1.25-4.19

**Comment by julianwiedmann** [comment]
Moar HostFW flakes (thanks mlh!) in https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-4.19/2051/

**Comment by julianwiedmann** [comment]
/test-1.25-4.19

**Pull request merged**
