### PR TITLE
endpoint: create endpoint without labels

### LINKED ISSUE #29776: Endpoint transition from waiting-to-identity state to waiting-to-regenerate not supported
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

For the the context, I have cilium agent running on a node independent from Kubernetes, connected to a dedicated etcd server.

While trying to create some custom endpoint using the API, with initial state as _models.EndpointStateWaitingDashForDashIdentity_, I get a state transition skipped error, causing the endpoint to be created:
 - in status _**waiting-for-identity**_ 
 - and the identity to stay forever as _no label id_

```
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY        LABELS (source:key[=value])                IPv6                 IPv4         STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                    
3236       Unknown            Unknown           <no label id>   k8s:app=incubator-mynetns3                                      10.247.1.1   waiting-for-identity   
                                                                k8s:io.cilium.k8s.policy.cluster=default                                                            
                                                                k8s:io.kubernetes.pod.namespace=default 
```

From what I could see is that an endpoint could transition from waiting-to-identity state to waiting-to-regenerate, but it appears that [this case is not handled](https://github.com/cilium/cilium/blob/v1.4/pkg/endpoint/endpoint.go#L1688).

When I recompile cilium with the support of this transition as follow

```
diff --git a/pkg/endpoint/endpoint.go b/pkg/endpoint/endpoint.go
index ab689e8d54..674e68e82c 100644
--- a/pkg/endpoint/endpoint.go
+++ b/pkg/endpoint/endpoint.go
@@ -1364,7 +1364,7 @@ func (e *Endpoint) setState(toState State, reason string) bool {
                }
        case StateWaitingForIdentity:
                switch toState {
-               case StateReady, StateDisconnecting, StateInvalid:
+               case StateReady, StateDisconnecting, StateInvalid, StateWaitingToRegenerate:
                        goto OKState
                }
        case StateReady:
```
the endpoint creation gives following warning

`Endpoint lacks identity, skipping policy calculation`

and the endpoint becomes in
 - in status _**ready**_ 
 - and the identity stays forever as _no label id_

```
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY        LABELS (source:key[=value])                IPv6                 IPv4         STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                    
331        Unknown            Unknown           <no label id>   k8s:app=incubator-mynetns3                                      10.247.1.1   ready   
                                                                k8s:io.cilium.k8s.policy.cluster=default                                             
                                                                k8s:io.kubernetes.pod.namespace=default                                              

```

```
2023-12-11T08:32:16.354860000Z level=info msg="Successful endpoint creation" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=331 ipv4= ipv6= k8sPodName=/ subsys=daemon
2023-12-11T08:32:16.354917000Z level=warning msg="Endpoint lacks identity, skipping policy calculation" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=331 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2023-12-11T08:32:16.360608000Z level=warning msg="Endpoint lacks identity, skipping policy calculation" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=331 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2023-12-11T08:32:18.372274000Z level=info msg="Compiled new BPF template" BPFCompilationTime=2.004872253s file-path=/var/run/cilium/state/templates/364daf715b9c11c5d1ed671f9aefd56af5815691eb91baae26c525514a8fe5b5/bpf_lxc.o subsys=datapath-loader
2023-12-11T08:32:18.452824000Z level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=331 ipv4= ipv6= k8sPodName=/ subsys=endpoint
```
Indeed, I could see the bpf program in the run directory

```
$ sudo tree /var/run/cilium/state/331
/var/run/cilium/state/331
├── bpf_lxc.o
├── ep_config.h
└── template.o -> /var/run/cilium/state/templates/364daf715b9c11c5d1ed671f9aefd56af5815691eb91baae26c525514a8fe5b5/bpf_lxc.o

0 directories, 3 files
```

After a restart of cilium-agent, the endpoint moves in restore state, and the endpoint is ready to be used, with identity created

```
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                IPv6                 IPv4         STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                               
331        Disabled           Disabled          21864      k8s:app=incubator-mynetns3                                      10.247.1.1   ready   
                                                           k8s:io.cilium.k8s.policy.cluster=default                                             
                                                           k8s:io.kubernetes.pod.namespace=default                                              

```

```
2023-12-11T08:41:54.231384000Z level=info msg="New endpoint" containerID=mynetns3 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=331 ipv4=10.247.1.1 ipv6= k8sPodName=default/netsvc-incubator01-da1 subsys=endpoint
2023-12-11T08:41:54.231657000Z level=info msg="Successfully restored endpoint. Scheduling regeneration" endpointID=331 subsys=daemon
2023-12-11T08:41:54.233104000Z level=info msg="Reusing existing global key" key="k8s:app=netsvc-incubator01-da1-mynetns;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.kubernetes.pod.namespace=default;" subsys=allocator
2023-12-11T08:41:54.245346000Z level=info msg="Security identity for endpoint is different from the security identity restored for the endpoint" endpointID=331 identityLabels.new=21864 identityLabels.old=init subsys=endpoint
2023-12-11T08:41:59.243368000Z level=info msg="Identity of endpoint changed" containerID=mynetns3 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=331 identity=21864 identityLabels="k8s:app=incubator-mynetns3,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.kubernetes.pod.namespace=default" ipv4=10.247.1.1 ipv6= k8sPodName=default/netsvc-incubator01-da1 oldIdentity=5 subsys=endpoint
2023-12-11T08:41:59.332702000Z level=info msg="Rewrote endpoint BPF program" containerID=mynetns3 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=331 identity=21864 ipv4=10.247.1.1 ipv6= k8sPodName=default/netsvc-incubator01-da1 subsys=endpoint
2023-12-11T08:41:59.333142000Z level=info msg="Restored endpoint" endpointID=331 ipAddr="[10.247.1.1 ]" subsys=endpoint
2023-12-11T08:41:59.333318000Z level=info msg="Finished regenerating restored endpoints" regenerated=4 subsys=daemon total=4
```

Once created, modulo the addition of the routes, the traffic is fully routable via cilium in the namespace, and policy are also enabled.

### Cilium Version

1.14

### Kernel Version

5.4.249

### Kubernetes Version

NA

### Sysdump

_No response_

### Relevant log output

```shell
Logs:
=====
	Invalid state transition skipped" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1473 endpointState.from=waiting-for-identity endpointState.to=waiting-to-regenerate


$ sudo cilium endpoint list
...
3236       Unknown            Unknown           <no label id>   k8s:app=incubator-mynetns3                                      10.247.1.1   waiting-for-identity   
                                                                k8s:io.cilium.k8s.policy.cluster=default                                                            
                                                                k8s:io.kubernetes.pod.namespace=default
```

### Anything else?

Initially raised in cilium slack https://cilium.slack.com/archives/C1MATJ5U5/p1702055222749189

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by oblazek**
When endpoint API is used to create an endpoint and `EndpointChangeRequest` contains labels, it will not allocate an identity to the endpoint.

During `NewEndpointFromChangeModel()` labels are stored in the endpoint model, causing the followup call `ep.UpdateLabels()` to not bump revision during this single `createEndpoint()` call. This means the folloup call to `e.runIdentityResolver()` never happens and the endpoint ends up without identity and with state waiting-for-identity.

```
ENDPOINT   IDENTITY        LABELS (source:key[=value])               IPv4         STATUS

3236       <no label id>   k8s:app=incubator-mynetns3                10.247.1.1   waiting-for-identity
                           k8s:io.cilium.k8s.policy.cluster=default
                           k8s:io.kubernetes.pod.namespace=default
```

This should not happen, otherwise user can only not set the labels during `createEndpoint()` call and do a followup call `patchEndpoint()` where labels will be set which then triggers regeneration to be triggered and identity allocated.

Instead epTemplate.Labels don't need to be set which means the above issue never happens as `updateLabels()` will now bump revision -> i.e. the regeneration is triggered.

With these changes one can `createEndpoint()` with labels in a single call:
```
ENDPOINT   IDENTITY   LABELS (source:key[=value])                IPv4         STATUS

331        21864      k8s:app=incubator-mynetns3                 10.247.1.1   ready
                      k8s:io.cilium.k8s.policy.cluster=default
                      k8s:io.kubernetes.pod.namespace=default
```

Fixes: https://github.com/cilium/cilium/issues/29776

```release-note
endpoint: fix inability to create endpoint with labels in a single API call
```

Signed-off-by: Ondrej Blazek <ondrej.blazek@firma.seznam.cz>

### CODE REVIEW

**Comment by aditighag** [comment]
I'm not familiar with this API as I was only aware of the custom health endpoint being created within the agent, so I'm removing my review assignment. /cc @cilium/sig-agent and @christarazi from the linked issue for review.

**Comment by squeed** [comment]
I'm not sure this is the right solution. Wouldn't it just make more sense to unconditionally start the identity resolver? I don't know why we skip it when `rev = 0`.

**Comment by oblazek** [comment]
> I'm not sure this is the right solution. Wouldn't it just make more sense to unconditionally start the identity resolver? I don't know why we skip it when `rev = 0`.

tbh I have no idea, very good point

**Comment by oblazek** [comment]
when I am looking closely at the `runIdentityResolver()`.. seems to me it can be safely run unconditionaly as https://github.com/cilium/cilium/blob/main/pkg/endpoint/endpoint.go#L2067 will make sure to run the ID allocation only when really needed

**Comment by oblazek** [comment]
```
diff --git a/pkg/endpoint/endpoint.go b/pkg/endpoint/endpoint.go
index 616c2020e6..a6e2764abe 100644
--- a/pkg/endpoint/endpoint.go
+++ b/pkg/endpoint/endpoint.go
@@ -1743,11 +1743,7 @@ func (e *Endpoint) UpdateLabels(ctx context.Context, identityLabels, infoLabels
        // replace identity labels and update the identity if labels have changed
        rev := e.replaceIdentityLabels(identityLabels)
        e.unlock()
-       if rev != 0 {
-               return e.runIdentityResolver(ctx, rev, blocking)
-       }
-
-       return false
+       return e.runIdentityResolver(ctx, rev, blocking)
 }
 ```

**Review by aanm — CHANGES_REQUESTED** [review]
Thanks for the PR. Sorry for taking so much time to review this but now I understood the full picture. I think this patch would be more appropriate. We should prevent executing `runIdentityResolver` unnecessarily.
```patch
diff --git a/daemon/cmd/endpoint.go b/daemon/cmd/endpoint.go
index d995eda77f..ed064bec20 100644
--- a/daemon/cmd/endpoint.go
+++ b/daemon/cmd/endpoint.go
@@ -376,6 +376,16 @@ func (d *Daemon) createEndpoint(ctx context.Context, owner regeneration.Owner, e
                "sync-build":                 epTemplate.SyncBuildEndpoint,
        }).Info("Create endpoint request")
 
+       // We don't need to create the endpoint with the labels. This might cause
+       // the endpoint regeneration to not be triggered further down, with the
+       // ep.UpdateLabels or the ep.RunMetadataResolver, because the regeneration
+       // is only triggered in case the labels are changed, which they might not
+       // change because NewEndpointFromChangeModel would contain the
+       // epTemplate.Labels, the same labels we would be calling ep.UpdateLabels or
+       // the ep.RunMetadataResolver.
+       apiLabels := labels.NewLabelsFromModel(epTemplate.Labels)
+       epTemplate.Labels = nil
+
        ep, err := endpoint.NewEndpointFromChangeModel(d.ctx, owner, d, d.ipcache, d.l7Proxy, d.identityAllocator, epTemplate)
        if err != nil {
                return invalidDataError(ep, fmt.Errorf("unable to parse endpoint parameters: %s", err))
@@ -414,7 +424,6 @@ func (d *Daemon) createEndpoint(ctx context.Context, owner regeneration.Owner, e
                return invalidDataError(ep, err)
        }
 
-       apiLabels := labels.NewLabelsFromModel(epTemplate.Labels)
        infoLabels := labels.NewLabelsFromModel([]string{})
 
        if len(apiLabels) > 0 {
```

**Comment by oblazek** [comment]
updated title, PR desc, commit.. triggering tests

**Review by aanm — APPROVED** [review]

**Pull request merged**
