### PR TITLE
v1.15 Backports 2024-08-03

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #31940 (@sayboras) :warning: resolved conflicts
 * [x] #33803 (@mhofstetter) :warning: resolved conflicts
 * [x] #33666 (@bimmlerd) :warning: resolved conflicts
 * [x] #33894 (@chancez)
 * [ ] #33908 (@giorio94) :warning: resolved conflicts
 * [ ] #34004 (@tommyp1ckles) :warning: resolved conflicts
 * [ ] #33905 (@chaunceyjiang)
 * [x] #34032 (@sayboras)
 * [x] #34044 (@Huweicai) :warning: resolved conflicts
 * [x] #34106 (@dylandreimerink) :warning: resolved conflicts
 * [x] #34109 (@sayboras)
 * [x] #34121 (@michi-covalent) :warning: resolved conflicts
 * [x] #34110 (@mhofstetter)

PRs skipped due to conflicts:

 * #34091 (@giorio94)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31940 33803 33666 33894 33908 34004 33905 34032 34044 34106 34109 34121 34110
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.15

**Review by michi-covalent — APPROVED** [review]
https://github.com/cilium/cilium/pull/34157/commits/7e94a3ba2095b46f0210b19497711de845397043 lgtm ❤️

**Review by mhofstetter — APPROVED** [review]
My commits look good, thanks Nicolas!

**Review by bimmlerd — APPROVED** [review]

**Review by viktor-kurchenko — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
Looks good for my commits, thanks.

**Review by chancez — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Pull request merged**
