### PR TITLE
v1.4 backports 2019-03-19

### PR DESCRIPTION
**Pull request by borkmann**
PRs:
- #7280 *
- #7391 
- #7394 *
- #7402 
- #7409 *
- #7392 
- #7398 
- #7428 
- #7425 
- #7426 

Not yet:
- #7414 *

(*) conflicts

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7442)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-docs-please

**Comment by borkmann** [comment]
test-missed-k8s

**Review by tgraf — APPROVED** [review]

**Pull request merged**
