### PR TITLE
vagrant: Bump all Vagrant box versions

### PR DESCRIPTION
**Pull request by pchaigno**

### CODE REVIEW

**Comment by pchaigno** [comment]
test-1.21-4.9

**Comment by pchaigno** [comment]
test-1.20-4.19

**Comment by pchaigno** [comment]
test-runtime

**Comment by pchaigno** [comment]
test-1.16-netnext

**Comment by brb** [comment]
Too late to the party, but can we get https://github.com/cilium/packer-ci-build/pull/267 into this bump? The image is 123MB, so we could save on time by a bit.

**Comment by pchaigno** [comment]
@brb Changes to packer-ci-build are frequent these days and it takes a long time to build all the images (before they can be used in this PR). I don't really see the point of waiting if we can merge this now and do another one later.

**Review by tklauser — APPROVED** [review]

**Pull request merged**
