### PR TITLE
v1.12 Backports 2023-04-20

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #24786 (@hemanthmalla)
 * [x] #24869 (@tklauser)
 * [x] #24825 (@christarazi)
 * [x] #25067 (@christarazi)
 * [x] #24939 (@jrajahalme)
 * [x] #24850 (@pchaigno)
 * [x] #24785 (@giorio94)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 24786 24869 24825 25067 24939 24850 24785; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=24786,24869,24825,25067,24939,24850,24785
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.12

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by giorio94 — APPROVED** [review]
Mine too. Thanks!

**Review by christarazi — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Review by hemanthmalla — APPROVED** [review]

**Comment by nbusseneau** [comment]
@christarazi There was a failure in a single pipeline at https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.9/1820/testReport/junit/Suite-k8s-1/20/K8sDatapathConfig_AutoDirectNodeRoutes_Check_direct_connectivity_with_per_endpoint_routes/ which might be related to the change in 29776a4a5e4aaa6dbd1c51c018f0512a61bfe283. Can investigate further, but before I do, does that ring any obvious bell to you or not?

**Comment by christarazi** [comment]
@nbusseneau Thanks for digging in. I think my commit introduced a bug, so https://github.com/cilium/cilium/pull/25067 will be needed.

cc @pchaigno for review from the original PR

**Comment by nbusseneau** [comment]
/test-backport-1.12

**Review by christarazi — APPROVED** [review]
Thanks for backporting! 

I think `build-commits` is failing because the "node/manager: Only remove old IPs if they weren't already added" commit is before the go.mod update commit. Probably will want to reorder them or even squash it into the "node/manager" commit. I think the latter is preferable so that the context for why we do it is all in the same commit.

**Comment by sayboras** [comment]
> I think the latter is preferable so that the context for why we do it is all in the same commit.

Thanks for your note, I have performed the above.

**Comment by sayboras** [comment]
/test-backport-1.12

**Comment by sayboras** [comment]
test-1.16-4.9 hits https://github.com/cilium/cilium/issues/15455

**Comment by sayboras** [comment]
Most of the reviews are in, CI jobs are good except for the above flake.

Marking this ready to merge.

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
