### PR TITLE
Document that clustermesh cluster-id range is 1-255

### PR DESCRIPTION
**Pull request by stonith**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

The documented clustermesh cluster-id range is 0-255 but actually seems to be 1-255 as per https://github.com/cilium/cilium/blob/master/daemon/cmd/daemon.go#L1188-L1190

### CODE REVIEW

**Comment by stonith** [comment]
Signed-off-by: Darren Foo <stonith@users.noreply.github.com>

**Review by joestringer — APPROVED** [review]
Looks good, thanks. The Signed-off line needs to be inside the commit message, which you can do using `git commit --amend` and by force-pushing the updated commit into your branch here.

**Review by sayboras — APPROVED** [review]
Thanks

**Review by kaworu — APPROVED** [review]
Thanks!

**Comment by sayboras** [comment]
can you help to sign off the commit as per Joe's comment to make CI happy ? Thanks

https://github.com/cilium/cilium/runs/6321874286?check_suite_focus=true

**Comment by joestringer** [comment]
It looks like the script is not picking up the signed-off-by line because the formatting is unusual. Note that you can use `git commit --amend --signoff to get the appropriate format (assuming you already configured your git settings). In particular, the email is expected to be within angle brackets, ie `John Doe <john@doe.com>`.

**Review by jrajahalme — APPROVED** [review]
I'm not exactly sure where the non-zero limitation comes from, but as `cilium-cli` warns for it we might as well document it like proposed here. Btw. `cilium-cli` also warns if a cluster name is `default`, but clustermesh might still work as cluster name should not really mattar that much.

**Comment by kaworu** [comment]
This is a pure documentation change, no need for CI to run. All reviews are in, marking as `ready-to-merge`.

**Pull request merged**
