### PR TITLE
bpf: Use different drop code for DROP_ALL

### PR DESCRIPTION
**Pull request by joestringer**
The reasons for a policy drop in DROP_ALL mode are different from the
typical policy drop, so it's useful to be able to distinguish this
reason in monitor output. Create a new drop code for this case.

We may want to consider backporting this at least to 1.2 for improved debuggability.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5040)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]
approved for monitor

**Review by tgraf — APPROVED** [review]

**Comment by joestringer** [comment]
Hit #5025.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Hit #5025 again.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
A thought was raised out-of-band by @rlenglet , these days it is far more likely that the container gets the init identity (5) and that this code would never be triggered. It's perhaps then more likely that we would get more use out of fixing https://github.com/cilium/cilium/issues/5007 instead.

**Comment by joestringer** [comment]
Given the discussion during yesterday's Cilium developer meeting, it's not clear that this will be particularly useful. I'll drop it for now, if it turns out that it could be useful then we can reopen and merge it.

**Pull request closed without merging**
