### PR TITLE
bpf: fix cilium-map-migrate compiler warnings

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

Fixed a couple of warnings
```
cilium-map-migrate.c: In function ‘bpf_handle_finalize’:
cilium-map-migrate.c:373:37: warning: ‘:’ directive output may be truncated writing 1 byte into a region of size between 0 and 4096 [-Wformat-truncation=]
  snprintf(file, sizeof(file), "%s/%s:%s", fs_base, name,
                                     ^
cilium-map-migrate.c:373:2: note: ‘snprintf’ output 10 or more bytes (assuming 4106) into a destination of size 4097
  snprintf(file, sizeof(file), "%s/%s:%s", fs_base, name,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    STATE_PENDING);
    ~~~~~~~~~~~~~~
cilium-map-migrate.c:384:38: warning: ‘snprintf’ output may be truncated before the last format character [-Wformat-truncation=]
   snprintf(dest, sizeof(dest), "%s/%s", fs_base, name);
                                      ^
cilium-map-migrate.c:384:3: note: ‘snprintf’ output 2 or more bytes (assuming 4098) into a destination of size 4097
   snprintf(dest, sizeof(dest), "%s/%s", fs_base, name);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cilium-map-migrate.c: In function ‘bpf_handle_pending’:
cilium-map-migrate.c:332:37: warning: ‘snprintf’ output may be truncated before the last format character [-Wformat-truncation=]
  snprintf(file, sizeof(file), "%s/%s", fs_base, name);
                                     ^
cilium-map-migrate.c:332:2: note: ‘snprintf’ output 2 or more bytes (assuming 4098) into a destination of size 4097
  snprintf(file, sizeof(file), "%s/%s", fs_base, name);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cilium-map-migrate.c:358:35: warning: ‘%s’ directive output may be truncated writing 7 bytes into a region of size between 0 and 4096 [-Wformat-truncation=]
  snprintf(dest, sizeof(dest), "%s:%s", file, STATE_PENDING);
                                   ^~
cilium-map-migrate.c:358:2: note: ‘snprintf’ output between 9 and 4105 bytes into a destination of size 4097
  snprintf(dest, sizeof(dest), "%s:%s", file, STATE_PENDING);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I can't fix this one :disappointed: 
```
cilium-map-migrate.c: In function ‘main’:
cilium-map-migrate.c:489:9: warning: ‘fn’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   ret = cb(ctx, map, name, exit);
         ^~~~~~~~~~~~~~~~~~~~~~~~
cilium-map-migrate.c:555:21: note: ‘fn’ was declared here
  bpf_handle_state_t fn;
                     ^~
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4742)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
flake https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4675/

**Comment by aanm** [comment]
test-me-please

**Comment by eloycoto** [comment]
@aanm Reviewed https://github.com/cilium/cilium/issues/4746 and it is not a flake, Cilium can't even start and test can't run. 

Regards.

**Comment by aanm** [comment]
Fixed on https://github.com/cilium/cilium/pull/4785

**Pull request closed without merging**
