### PR TITLE
.github: Remove Loki action

### PR DESCRIPTION
**Pull request by joestringer**
Depends on #26516

This loki action has been disabled for a while, and it refers to a bunch
of outdated workflow names (since Ariane moved many to individual
branches). Furthermore, I believe that at least the ginkgo workflows on
github actions now emit metrics that we can use to assess CI stability,
so Loki should no longer be necessary at least for those workflows. We
can continue to re-evaluate the metric export for Cilium CI in order to
facilitate maintenance of stable trees over time, but this Loki workflow
is not currently critical to that goal.

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]
😇

**Review by aanm — APPROVED** [review]

**Review by ghost — APPROVED** [review]
docs ok

**Review by nebril — APPROVED** [review]

**Comment by squeed** [comment]
@joestringer needs rebase.

**Comment by joestringer** [comment]
Hmm, I thought that GitHub automatically did the rebase when the parent commit is merged into the default branch, but apparently not. Rebased now :+1:

**Review by julianwiedmann — APPROVED** [review]

**Pull request merged**
