### PR TITLE
v1.8 backports 2020-08-25

### PR DESCRIPTION
**Pull request by brb**
v1.8 backports 2020-08-25

 * #12809 -- service, loadbalancer: Misc refactoring (@brb)
 * #12852 -- test: Replace MetalLB with dummyLB and re-enable LoadBalancer test (@brb)
 * #12841 -- datapath,daemon: Add check for loadBalancerSourceRanges (@brb)
 * #12940 -- helm,docs: Add section about (LB) source range check (@brb)
 * #12947 -- pkg/kvstore: add gRPC keep alives for etcd connectivity (@aanm)

**NOT INCLUDED DUE TO MERGE CONFLICTS**:

 * #12948 -- connectivity-check: Use unprivileged ports (@tgraf)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12809 12852 12841 12940 12947; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by brb** [comment]
Tests are failing because https://github.com/cilium/cilium/pull/12852 has to be backported too.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-backport-1.8

**Comment by brb** [comment]
4.19 CI failed due to:
```
k8s1-1.19: sudo: kubeadm: command not found
[2020-08-25T16:48:41.713Z] The SSH command responded with a non-zero exit status. Vagrant
```

**Comment by brb** [comment]
retest-4.19

**Comment by brb** [comment]
retest-4.9

**Comment by brb** [comment]
test-upstream-k8s

**Comment by brb** [comment]
retest-gke

**Comment by joestringer** [comment]
k8s-1.19-kernel-4.9 target failed provisioning. Will retry.

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.9/296/flowGraphTable/

**Comment by joestringer** [comment]
test-1.19-4.9

**Comment by joestringer** [comment]
Hmm, it did nothing, but I also realised that there's already `k8s-1.18-kernel-4.9` which tested a similar set of options and that one passed:

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.18-kernel-4.9/1335/

Furthermore, AFAIK GKE is not yet fully fixed & enabled on the latest code let alone v1.8 branch so I'm assuming that the GKE failure here is a CI issue:

https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/2305/

**Review by joestringer — APPROVED** [review]
I looked over the commits not authored by you since I figure you have the best view into the LB ones to properly resolve any conflicts. :+1:

**Pull request merged**
