### PR TITLE
v1.14 Backports 2023-08-28

### PR DESCRIPTION
**Pull request by pippolo84**
* [ ] #27362 (@ayuspin)
 * [ ] #27658 (@weizhoublue)
 * [x] #27678 (@borkmann)
 * [x] #27694 (@jschwinger233)
 * [x] #27241 (@meyskens)
   * :warning: merge conflicts due to different parameter type in `newAuthManager` (`ipCache` -> `nodeIDHandler`) and unexported `AuthManager` type)
 * [x] #27391 (@brlbil)
   * :warning: merge conflicts due to missing workflow files in v1.14 branch (`build-images-docs-builder.yaml`, `close-stale-issues.yaml`, `ci-images-cache-cleaner.yaml`, `ci-images-garbage-collect.yaml`, `conformance-ipsec-e2e.yaml` and `lint-codeowners.yaml`)
 * [ ] #27702 (@RichardoC)
 * [x] #27646 (@giorio94)
 * [ ] #27690 (@shawnh2)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 27362 27658 27678 27694 27241 27391 27702 27646 27690; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=27362,27658,27678,27694,27241,27391,27702,27646,27690
```

### CODE REVIEW

**Review by jschwinger233 — APPROVED** [review]
My PR looks good, thanks!

**Review by giorio94 — APPROVED** [review]
My commit looks good. Thanks!

**Comment by pippolo84** [comment]
/test-backport-1.14

**Review by meyskens — APPROVED** [review]
LGTM for my PR

**Comment by brlbil** [comment]
/test-backport-1.14

**Review by brlbil — APPROVED** [review]
I have made small changes to my commit.

Since some of the workflow names changed, Required Worflows needs to be changed after this is merged. The list of changes is below.
```
-name: ConformanceAKS (ci-aks)
+name: Conformance AKS (ci-aks)
--
-name: ClusterMesh (ci-multicluster)
+name: Conformance Cluster Mesh (ci-clustermesh)
--
-name: Cilium Conformance E2E (ci-e2e)
+name: Conformance E2E (ci-e2e)
--
-name: ConformanceEKS (ci-eks)
+name: Conformance EKS (ci-eks)
--
-name: External workloads (ci-external-workloads)
+name: Conformance External Workloads (ci-external-workloads)
--
-name: ConformanceGatewayAPI
+name: Conformance Gateway API
--
-name: Conformance ginkgo (ci-ginkgo)
+name: Conformance Ginkgo (ci-ginkgo)
--
-name: ConformanceGKE (ci-gke)
+name: Conformance GKE (ci-gke)
--
-name: ConformanceIngress
+name: Conformance Ingress
--
-name: K8sUpstreamNetConformance
+name: Conformance K8s Upstream Network
--
-name: ConformanceK8sKind
+name: Conformance K8s Kind
--
-name: Cyclonus network policy test
+name: Cyclonus Network Policy Test
--
-name: ConformanceKindEnvoyDaemonSet
+name: Conformance Kind Envoy DaemonSet
--
-name: ConformanceMultiPoolIPAM
+name: Conformance Multi Pool IPAM
--
-name: Cilium Runtime
+name: Conformance Runtime
--
-name: Container vulnerability scan
+name: Container Vulnerability Scan
--
-name: IntegrationTests
+name: Integration Tests
--
-name: BPF checks
+name: BPF Checks
--
-name: build-commits
+name: Build Commits
--
-name: codeql
+name: CodeQL
--
-name: Go-related checks
+name: Go Related Checks
--
-name: GitHub Workflow-related checks
+name: GitHub Workflow Related Checks
--
-name: Smoke test
+name: Smoke Test
```

Also, Branch protection rules need to be adjusted.

To Remove
```
build datapath
coccicheck
conformance-test
conformance-test-ipv6
generate-api
generate-k8s-api
go-mod
lint
precheck
preflight-clusterrole
```

To Add
```
BPF Checks / Build Datapath
BPF Checks / Run coccicheck
Smoke Test / Installation and Conformance Test
Smoke Test with IPv6 / Installation and Conformance Test
Go Related Checks / Generate API
Go Related Checks / Generate k8s API
Go Related Checks / Check Go Modules
Go Related Checks / Lint Source Code
Go Related Checks / Precheck
Smoke Test / Preflight Clusterrole Check
```

**Comment by RichardoC** [comment]
LGTM for my PR

**Comment by pippolo84** [comment]
/test-backport-1.14

**Review by borkmann — APPROVED** [review]

**Pull request merged**
