### PR TITLE
clustermesh: drop legacy README file and associated scripts

### PR DESCRIPTION
**Pull request by giorio94**
The official clustermesh documentation is already included as part of the Cilium docs \[1\]. There's very little value in maintaining a separate README file with duplicated at best, likely outdated information. Indeed, besides a trivial update one year ago, this README file has seen only a single significant change in 2021.

Hence, let's just sunset it to prevent confusion to users. Similarly, let's drop the scripts therein mentioned, as users shall either leverage the Cilium CLI tool or helm to configure the set of clusters to connect to, rather than manually creating the clustermesh secret.

Finally, let's also remove the `tls.rst` file in favor of the external workloads official documentation \[2\].

\[1\]: https://docs.cilium.io/en/stable/network/clustermesh/
\[2\]: https://docs.cilium.io/en/stable/network/external-toc/

### CODE REVIEW

**Review by nebril — APPROVED** [review]

**Review by thorn3r — APPROVED** [review]
:headstone: :pray:

**Comment by giorio94** [comment]
Rebased onto main to hopefully make CI happier :crossed_fingers:

**Pull request merged**
