### PR TITLE
Revert https://github.com/cilium/cilium/pull/24288

### LINKED ISSUE #24573: CI: K8sUpdates Tests upgrade and downgrade from a Cilium stable image to master
### Test Name

```shell
K8sUpdates Tests upgrade and downgrade from a Cilium stable image to master
```

### Failure Output

```shell
Cilium "1.13.90" did not become ready in time
("unable to retrieve daemonset kube-system/cilium")
```

### Stack Trace

```shell
/home/jenkins/workspace/Cilium-PR-K8s-1.26-kernel-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:515
Timed out after 247.361s.
Cilium "1.13.90" did not become ready in time
Expected
    <*errors.errorString | 0xc002e1c1f0>: {
        s: "unable to retrieve daemonset kube-system/cilium: Exitcode: -1 \nErr: signal: killed\nStdout:\n \t \nStderr:\n \t \n",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.26-kernel-net-next/src/github.com/cilium/cilium/test/k8s/updates.go:230
```

### Standard Output

```shell
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Cilium pods: []
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod   Ingress   Egress
```

### Standard Error

```shell
17:11:56 STEP: Running BeforeAll block for EntireTestsuite K8sUpdates
17:11:56 STEP: Ensuring the namespace kube-system exists
17:11:57 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs")
17:11:57 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs") => <nil>
17:11:57 STEP: Waiting for pods to be terminated
17:12:04 STEP: Deleting Cilium and CoreDNS
17:12:04 STEP: Waiting for pods to be terminated
17:12:04 STEP: Cleaning Cilium state (5f59a61f4422381b3db45d45158d130de3c7130b)
17:12:04 STEP: Cleaning up Cilium components
17:12:06 STEP: Waiting for Cilium to become ready
FAIL: Timed out after 247.361s.
Cilium "1.13.90" did not become ready in time
Expected
    <*errors.errorString | 0xc002e1c1f0>: {
        s: "unable to retrieve daemonset kube-system/cilium: Exitcode: -1 \nErr: signal: killed\nStdout:\n \t \nStderr:\n \t \n",
    }
to be nil
=== Test Finished at 2023-03-22T17:16:13Z====
17:16:13 STEP: Running JustAfterEach block for EntireTestsuite K8sUpdates
===================== TEST FAILED =====================
17:16:33 STEP: Running AfterFailed block for EntireTestsuite K8sUpdates
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: -1 
Err: signal: killed
```

### Resources

- Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/1430/testReport/junit/Suite-k8s-1/26/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/
- ZIP file(s): 
[43f56c88_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip](https://github.com/cilium/cilium/files/11076004/43f56c88_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by aanm**
The PR https://github.com/cilium/cilium/pull/24288 and https://github.com/cilium/cilium/pull/24577 introduced a regression on the upgrade from 1.13 to latest. Thus, we will revert all commits from this PR so that we can have the CI in a healthy state.

cc @NikAleksandrov 

Fixes https://github.com/cilium/cilium/issues/24573

Verified locally that upgrade test doesn't fail after this.

### CODE REVIEW

**Review by sayboras — APPROVED** [review]

**Review by pchaigno — CHANGES_REQUESTED** [review]
You will also need to revert https://github.com/cilium/cilium/pull/24577/commits.

**Review by pchaigno — APPROVED** [review]

**Review by YutaroHayakawa — APPROVED** [review]

**Comment by julianwiedmann** [comment]
I hate to spoil the party, but still seeing this fail with the revert applied:
https://github.com/cilium/cilium/issues/24687

**Pull request merged**
