### PR TITLE
clustermesh: fix config watcher missed events with fsnotify 1.8.0

### PR DESCRIPTION
**Pull request by giorio94**
The clustermesh configuration watcher needs to explicitly watch the config files to receive a notification when the underlying file gets updated, if the path points to a symbolic link (e.g., when the folder is mounted from a Kubernetes ConfigMap/Secret). However, the fsnotify library slightly changed its behavior in the latest release [1], and no longer propagates a remove event in case the parent directory is watched as well. The reason being to prevent duplicate events, as it would be generated both by the specific watcher and the parent directory watcher. Still, the parent watcher doesn't emit the remove event in this context, given that the symbolic link is not actually removed. In turn, opening the possibility for race conditions in the current event processing logic, which depends on always correctly re-establishing the watcher.

Let's address this by using two separate watchers, one for the config directory itself and one for the individual config files, to ensure that the remove event is correctly emitted when the symbolic link starts pointing to a different file (hence breaking the existing watcher), so that we can re-establish it.

\[1]: fsnotify/fsnotify#620

### CODE REVIEW

**Comment by giorio94** [comment]
Ci is reasonably green (failures are unrelated flakes). Dropping the extra commit.

**Review by aanm — APPROVED** [review]

**Pull request merged**
