### PR TITLE
images: don't assume Dockerfile directory in builder/runtime update scripts

### PR DESCRIPTION
**Pull request by tklauser**
Just check for the strings `CILIUM_BUILDER_IMAGE=` and `CILIUM_RUNTIME_IMAGE=`, respectively in all found Dockerfiles. This allows to update Dockerfiles not stored in the images/ hierarchy.

### CODE REVIEW

**Review by viktor-kurchenko — APPROVED** [review]
LGTM.

**Review by nebril — APPROVED** [review]
amazing

**Review by kaworu — APPROVED** [review]

**Pull request merged**
