### PR TITLE
[v1.4] Fix dep and add missing generated code

### PR DESCRIPTION
**Pull request by aanm**
kind of backport of https://github.com/cilium/cilium/pull/7081

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7116)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-docs-please

**Review by nebril — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Pull request merged**
