### PR TITLE
gateway-api: Sync up with the latest upstream v1.2.0-rc1

### PR DESCRIPTION
**Pull request by sayboras**
Support for https://github.com/kubernetes-sigs/gateway-api/releases/tag/v1.2.0-rc1

### CODE REVIEW

**Comment by sayboras** [comment]
ci-gateway

**Comment by sayboras** [comment]
ci-gateway-api

**Review by marseel — APPROVED** [review]

**Review by ysksuzuki — APPROVED** [review]

**Comment by sayboras** [comment]
Seems like something is broken after rebase with main branch, marking this as draft.

**Review by joamaki — APPROVED** [review]

**Pull request merged**
