### PR TITLE
v1.11 Backports 2023-01-30

### PR DESCRIPTION
**Pull request by qmonnet**
* [ ] #23159 -- docs: Disable exclusive lock when chaining with aws-cni (@jaygridley)
 * [x] #23339 -- cilium: Fix missing error log dump from compilation (@borkmann)
    * Minor conflict
 * [X] #23338 -- test: print log messages that need to be investigated (@aanm)
 * [X] #23334 -- tests: add exception for etcd error (@aanm)
    * Minor conflict
 * [x] #23377 -- proxy: Fix deadlock in error path of CreateOrUpdateRedirect (@gandro)
    * Minor conflict 
 * [X] #23406 -- .github/workflows: fix external contribution detection (@aanm)
    * Minor conflict
 * [X] #23424 -- .github/workflows: fix typo in organization parameter (@aanm)
 * [X] #23431 -- .github: set do not use provenance from docker buildx (@aanm)
    * Minor conflict
 * [X] #23437 -- .github/workflows: set right secret name (@aanm)
    * Minor conflict

PRs skipped due conflicts:

 * #23202 -- Introduce node IDs (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 23159 23339 23338 23334 23377 23406 23424 23431 23437; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
$ make add-label BRANCH=v1.11 ISSUES=23159,23339,23338,23334,23377,23406,23424,23431,23437
```

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Thanks for resolving the conflict. The commit looks good to me!

**Review by nbusseneau — APPROVED** [review]

**Comment by qmonnet** [comment]
/test-backport-1.11

**Review by aanm — APPROVED** [review]
LGTM. Thank you!

**Comment by qmonnet** [comment]
Rebased to address conflicts

**Comment by qmonnet** [comment]
/test-backport-1.11

**Comment by qmonnet** [comment]
Travis failure on arm64 looks like a hiccup, doesn't seem related to the current changes. I filed https://github.com/cilium/cilium/issues/23495 for it.

**Review by borkmann — APPROVED** [review]

**Pull request merged**
