### PR TITLE
v1.6 backports 2020-05-07

### PR DESCRIPTION
**Pull request by aanm**
* #10727 -- pkg/k8s: fix all structural issues with CNP validation (@aanm)
* #11040 -- CRD: fix allocation logic of identities with the same set of labels (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10727 11040; do contrib/backporting/set-labels.py $pr done 1.6; done
```

### CODE REVIEW

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Review by joestringer — APPROVED** [review]

**Pull request merged**
