### PR TITLE
[v1.14] gh/workflows: IPsec key rotation improvements

### PR DESCRIPTION
**Pull request by julianwiedmann**
Manual backport of
* [ ] #29592 (@brb)
* [ ] #29704 (@brb)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 29592 29704
```

### CODE REVIEW

**Comment by julianwiedmann** [comment]
/test-backport-1.14

**Comment by julianwiedmann** [comment]
/test-backport-1.14

**Comment by julianwiedmann** [comment]
/test-backport-1.14

**Comment by julianwiedmann** [comment]
/test-backport-1.14

**Comment by julianwiedmann** [comment]
/test-backport-1.14

**Review by brb — APPROVED** [review]
Thanks!

**Comment by julianwiedmann** [comment]
I believe there's some conflicting work in the pipeline, so let's see how we get this in the easiest. `preview-only` for now, but good for review.

**Review by viktor-kurchenko — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]

**Comment by julianwiedmann** [comment]
/test-backport-1.14

**Comment by julianwiedmann** [comment]
/test-backport-1.14

**Comment by julianwiedmann** [comment]
/test-backport-1.14

**Comment by pchaigno** [comment]
@julianwiedmann Is there something in particular I should review? This is just a backport for two PRs I already reviewed, no?

**Comment by julianwiedmann** [comment]
> @julianwiedmann Is there something in particular I should review? This is just a backport for two PRs I already reviewed, no?

Right, sorry - I should have noted that. The interesting part is the adjustments for the new key system in https://github.com/cilium/cilium/pull/31429/commits/5e1e120ba08f135e539519d850353a22c54aa3b6. This *should* be very much in line with the changes in https://github.com/cilium/cilium/pull/31428.

**Review by pchaigno — APPROVED** [review]

**Comment by julianwiedmann** [comment]
/test-backport-1.14

**Review by lmb — APPROVED** [review]

**Pull request merged**
