### PR TITLE
endpoint: refactor regeneration to be in a controller

### PR DESCRIPTION
**Pull request by ianvernon**
Related-to #8817 

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9194)

### CODE REVIEW

**Review by joestringer — COMMENTED** [review]
I'm wondering about how the new controller gets stopped upon endpoint deletion?

**Comment by ianvernon** [comment]
> I'm wondering about how the new controller gets stopped upon endpoint deletion?

@joestringer we stop all controllers when an Endpoint is deleted. See the following:

https://github.com/cilium/cilium/blob/b820c709bba12e78629d6e7a35c376ecb0bffb9a/pkg/endpoint/endpoint.go#L926

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Pull request closed without merging**
