### PR TITLE
Disable container runtime integration in default ConfigMap

### PR DESCRIPTION
**Pull request by tgraf**
---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6495)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
This cannot be done yet due to backward compatibility, see #6526 for details.

**Comment by ianvernon** [comment]
Removed needs-backport/1.4 label since the PR was closed and not merged.

**Pull request closed without merging**
