### PR TITLE
vendor: Bump go.universe.tf/metallb

### LINKED ISSUE #16181: [Race Detector] Race between `go.universe.tf/metallb/pkg/controller.(*Controller).MarkSynced()` and `go.universe.tf/metallb/pkg/controller.(*Controller).convergeBalancer()`
```
2021-05-07T22:01:52.914351586Z WARNING: DATA RACE                                                                                                                                
2021-05-07T22:01:52.914417876Z Write at 0x00c000c04b58 by goroutine 138:
2021-05-07T22:01:52.914456394Z   go.universe.tf/metallb/pkg/controller.(*Controller).MarkSynced()
2021-05-07T22:01:52.914463360Z       /go/src/github.com/cilium/cilium/vendor/go.universe.tf/metallb/pkg/controller/controller.go:105 +0xbd
2021-05-07T22:01:52.914499821Z   github.com/cilium/cilium/operator/watchers.StartLBIPAllocator.func1()
2021-05-07T22:01:52.914507780Z       /go/src/github.com/cilium/cilium/operator/watchers/bgp.go:41 +0x96
2021-05-07T22:01:52.914543495Z 
2021-05-07T22:01:52.914612365Z Previous read at 0x00c000c04b58 by goroutine 137:
2021-05-07T22:01:52.914655135Z   go.universe.tf/metallb/pkg/controller.(*Controller).convergeBalancer()
2021-05-07T22:01:52.914663250Z       /go/src/github.com/cilium/cilium/vendor/go.universe.tf/metallb/pkg/controller/service.go:100 +0xd95
2021-05-07T22:01:52.914703328Z   go.universe.tf/metallb/pkg/controller.(*Controller).SetBalancer()
2021-05-07T22:01:52.914711504Z       /go/src/github.com/cilium/cilium/vendor/go.universe.tf/metallb/pkg/controller/controller.go:59 +0x398
2021-05-07T22:01:52.914751715Z   github.com/cilium/cilium/pkg/bgp/manager.(*Manager).reconcile()
2021-05-07T22:01:52.914759783Z       /go/src/github.com/cilium/cilium/pkg/bgp/manager/subscriber.go:134 +0xca
2021-05-07T22:01:52.914800358Z   github.com/cilium/cilium/pkg/bgp/manager.(*Manager).process()
2021-05-07T22:01:52.914808031Z       /go/src/github.com/cilium/cilium/pkg/bgp/manager/subscriber.go:124 +0x2a8
2021-05-07T22:01:52.914846977Z   github.com/cilium/cilium/pkg/bgp/manager.(*Manager).run()
2021-05-07T22:01:52.914855101Z       /go/src/github.com/cilium/cilium/pkg/bgp/manager/subscriber.go:80 +0x87
2021-05-07T22:01:52.914895144Z 
2021-05-07T22:01:52.914936012Z Goroutine 138 (running) created at:
2021-05-07T22:01:52.914979076Z   github.com/cilium/cilium/operator/watchers.StartLBIPAllocator()
2021-05-07T22:01:52.914996799Z       /go/src/github.com/cilium/cilium/operator/watchers/bgp.go:39 +0x186
2021-05-07T22:01:52.915039049Z   main.onOperatorStartLeading()
2021-05-07T22:01:52.915046753Z       /go/src/github.com/cilium/cilium/operator/main.go:415 +0x30f0
2021-05-07T22:01:52.915084261Z 
2021-05-07T22:01:52.915121567Z Goroutine 137 (running) created at:
2021-05-07T22:01:52.915164290Z   github.com/cilium/cilium/pkg/bgp/manager.New()
2021-05-07T22:01:52.915171299Z       /go/src/github.com/cilium/cilium/pkg/bgp/manager/manager.go:64 +0x69c
2021-05-07T22:01:52.915212379Z   github.com/cilium/cilium/operator/watchers.StartLBIPAllocator()
2021-05-07T22:01:52.915219942Z       /go/src/github.com/cilium/cilium/operator/watchers/bgp.go:36 +0x124
2021-05-07T22:01:52.915255446Z   main.onOperatorStartLeading()
2021-05-07T22:01:52.915262342Z       /go/src/github.com/cilium/cilium/operator/main.go:415 +0x30f0
```

Hit in https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next-Race-Detection/4/

Observed by @nbusseneau in https://github.com/cilium/cilium/pull/16056#issuecomment-834909274

Looks like an issue in MetalLB itself, which was vendored in by dede69f2b7f4a5bb2d7a02b4037569478ec559f5 /cc @christarazi

### PR DESCRIPTION
**Pull request by christarazi**
This bump fixes a data race reported in
https://github.com/cilium/cilium/issues/16181.

Signed-off-by: Chris Tarazi <chris@isovalent.com>

### CODE REVIEW

**Comment by christarazi** [comment]
test-race-net-next

**Comment by christarazi** [comment]
test-net-next

**Review by tklauser — APPROVED** [review]
Nice, thanks!

**Comment by christarazi** [comment]
test-net-next

**Pull request merged**
