### PR TITLE
Fixup FQDN tests to run on GKE & EKS

### PR DESCRIPTION
**Pull request by raybejjani**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9990)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-gke K8sFQDNTest*

**Comment by raybejjani** [comment]
test-eks K8sFQDNTest*

**Comment by raybejjani** [comment]
test-gke K8sFQDNTest*

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-eks K8sFQDNTest*

**Comment by raybejjani** [comment]
test-gke K8sFQDNTest*

**Comment by nebril** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-focus K8sFQDNTest*

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-eks K8sFQDNTest*

**Comment by raybejjani** [comment]
test-gke K8sFQDNTest*

**Review by nebril — APPROVED** [review]
Let's ship it!

**Pull request merged**
