### PR TITLE
test: disable fqdn restart test

### PR DESCRIPTION
**Pull request by nebril**
Test is flaky, let's disable it

Updates #11213
Updates #10538

### CODE REVIEW

**Comment by nebril** [comment]
test-gke K8sFQDNTest

**Review by tklauser — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]

**Comment by nebril** [comment]
test-focus K8sFQDNTest

**Comment by nebril** [comment]
test-focus K8sFQDNTest

**Comment by nebril** [comment]
Rebased

**Comment by nebril** [comment]
test-focus K8sFQDNTest

**Comment by nebril** [comment]
test-4.9

**Pull request merged**
