### PR TITLE
bpf: Do not redirect replies from a pod to a proxyport.

### PR DESCRIPTION
**Pull request by jrajahalme**
Replies going into a pod are already not redirected to a proxy. Do the
same for replies going out of a pod. Only original direction packets
should be redirected to a proxy.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5835)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
CI tests to be added in a separate PR.

**Review by tgraf — APPROVED** [review]
Isn't this very hard to hit? It would only be hit if the ephemeral source port matches the L4 policy port. Correct?

**Review by joestringer — APPROVED** [review]

**Comment by jrajahalme** [comment]
@tgraf Thats what I don't fully understand either, as this is very easy to hit (see https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7066/). Apparently we flip the reply tuple for policy matching, which causes this to be hit on any return traffic from a service port.

**Pull request merged**
