### PR TITLE
images: bump cni plugins to v1.6.0

### PR DESCRIPTION
**Pull request by ferozsalam**

### CODE REVIEW

**Review by squeed — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Given the runtime/builder image changes, I think we're going to need to manually prepare the backports for each branch. Probably it's quicker to cherry-pick only the first commit to each branch and let the auto-committer help with the rest on each PR for each branch.

**Review by brlbil — APPROVED** [review]

**Comment by ferozsalam** [comment]
@joestringer I've added the necessary labels, will create backports shortly.

**Review by aanm — APPROVED** [review]

**Pull request merged**
