### PR TITLE
k8s-example: allowing IPv4 mode to run with k8s

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins andre@cilium.io

### CODE REVIEW

**Comment by aanm** [comment]
k8s tests fails if cilium is running with `ipv4` flag and the k8s service IPs range set with an ipv6 range. where should I write a warning/message about this since it can affect not only us but the users in the future?

**Comment by tgraf** [comment]
@aanm What and why is it failing exactly?

**Comment by aanm** [comment]
@tgraf I add a small note in the docs regarding the limitation. Looks good?

**Review by tgraf — APPROVED** [review]
:+1:

**Pull request merged**
