### PR TITLE
bpf: Fix drop notifications for local identities

### PR DESCRIPTION
**Pull request by tgraf**
The tail call was using 16 bit for identities which was insufficient for local
identities. Reoder use of the cb[] buffer to grant enough bits to transfer
the identity into the drop handling tail call

Tested manually:
```
xx drop (Policy denied (L3)) flow 0x125d2640 to endpoint 0, identity 21940->2: [f00d::a10:0:0:ba4b]:32944 -> [2a00:1450:400a:801::2004]:443 tcp SYN
xx drop (Policy denied (L3)) flow 0xfb7b6af2 to endpoint 0, identity 21940->13003: 10.16.46.200:33510 -> 10.16.86.179:80 tcp SYN
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7026)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by aanm** [comment]
seems a legit failure:
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:408
Default drop on ingress failed
Expected
    <*errors.errorString | 0xc420544010>: {
        s: "Timeout reached: xx drop (Policy denied is not in the output after timeout",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/runtime/Policies.go:1537
```

**Comment by tgraf** [comment]
Drop reason is corrupted:
```
xx drop (123) flow 0xf229a352 to endpoint 65535, identity 44824->2: [f00d::a10:0:0:ba4b]:39120 -> [2a00:1450:400a:802::2004]:443 tcp SYN
xx drop (123) flow 0x6e29fd42 to endpoint 65535, identity 44824->2: 10.16.218.67:40516 -> 172.217.168.4:443 tcp SYN
```

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Hit known flake ` k8s-1.13.K8sFQDNTest Restart Cilium validate that FQDN is still working`. All other tests passed.

**Pull request merged**
