### PR TITLE
v1.14 Backports 2024-01-22

### PR DESCRIPTION
**Pull request by giorio94**
* [x] #27331 (@christarazi)
 * [x] #29983 (@giorio94)
    - :information_source: Slightly adapted the kvstore action -- Skipped renovate and codeowners changes, as only relevant in the main branch. Additionally included the clustermesh CA cert as part of the clustermesh settings, as Cilium v1.13 and earlier do not allow to override the CA on a per-cluster basis.
    - :information_source: Slightly adapted the clustermesh workflows -- In Cilium v1.14 and earlier, the clustermesh
      configuration secret is created only when the clustermesh-apiserver is enabled. For this reason, we need to enable it also when actually connecting to a remote kvstore cluster, although with zero replicas.
   - :x: Skipped 5e8f85d55689 as not applicable to v1.14.
 * [x] #29926 (@giorio94)
   - :x: Skipped b48a281bf2, df3ab28daf7, ab2a1492cfe0, 00ed827d9c6f as not applicable to v1.14.
 * [x] #30207 (@giorio94)
    - :information_source: Hit multiple conflicts due to the absence of the helm-default action in the v1.14 branch, resolved updating the chart-dir path as appropriate. Additionally, skipped the e2e-upgrade hunks, as not present.
 * [x] #29460 (@tommyp1ckles)
    - :information_source: Hit a few conflicts as the v1.14 branch does not include f2587d97a337. Applied the changes to the `local_node_init{_test}.go` files, and adapted as appropriate
 * [ ] #28286 (@tamilmani1989)
 * [ ] #30131 (@ayuspin)
 * [x] #30335 (@giorio94)
 * [x] #30126 (@youngnick)
 * [x] #30343 (@julianwiedmann)
 * [x] #30340 (@dylandreimerink)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 27331 29983 29926 30207 29460 28286 30131 30335 30126 30343 30340
```

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]

**Comment by giorio94** [comment]
/test-backport-1.14

**Review by christarazi — APPROVED** [review]

**Comment by giorio94** [comment]
/test-backport-1.14

**Review by dylandreimerink — APPROVED** [review]

**Comment by giorio94** [comment]
Marking as blocked, as it depends on https://github.com/cilium/cilium/pull/30371

**Review by youngnick — APPROVED** [review]

**Review by brlbil — APPROVED** [review]

**Review by tommyp1ckles — APPROVED** [review]

**Comment by giorio94** [comment]
Rebased onto the tip of v1.14 to pick the Datapath BPF Complexity workflow fixes.

**Comment by giorio94** [comment]
/test-backport-1.14

**Review by squeed — APPROVED** [review]

**Comment by giorio94** [comment]
CI is green and most of the reviews are in (the remaining PRs didn't incur in any conflict, and I performed an additional sanity check). Marking as ready to merge.

**Pull request merged**
