### PR TITLE
Retrieve additional information for SCTP flake

### PR DESCRIPTION
**Pull request by pchaigno**
Should help debug https://github.com/cilium/cilium/issues/16838. See commits for details.

### CODE REVIEW

**Review by jibi — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by pchaigno** [comment]
test-1.16-netnext

**Comment by pchaigno** [comment]
test-1.20-4.19

**Comment by brb** [comment]
OT: the test provides very small value. Maybe we should just remove it and write a BPF unit test instead?

**Comment by pchaigno** [comment]
> Maybe we should just remove it and write a BPF unit test instead?

Sure, who has cycles to write that?

**Comment by brb** [comment]
> who has cycles to write that?

I think it's OK to do it later once we have merged https://github.com/cilium/cilium/pull/16862. For now we could just create an issue.

**Pull request closed without merging**
