### PR TITLE
Enable cilium-health in ipvlan mode

### PR DESCRIPTION
**Pull request by brb**
This PR:

- Enables `cilium-health` when running in the ipvlan datapath mode.
- Makes `cilium-health` to use ipvlan slave device when running in the ipvlan mode.
- Refactors the ipvlan connector.
- Introduces the `pkg/netns` package (sorry, no tests at the moment - I will add them later).

It's best to review each commit separately.

---

We could avoid a lot of cilium-health related code, if we would call CNI ADD instead of trying to replicate all container netdev initialization steps. Happy to refactor if the suggestion make sense to you.

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6845)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Pull request merged**
