### PR TITLE
docs: Ignore Helm values, update spelling list

### PR DESCRIPTION
**Pull request by qmonnet**
It's a pain for developers to have to update the spelling list each time they add a new Helm value. Let's ignore these when running the spell-checker. Then we can also update (trim down) the list of exceptions.

- docs: Ignore Helm value names for spellcheck
- docs: Trim down spelling list

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Nice, looks good to me.

**Comment by gandro** [comment]
I'm struggling to backport this to v1.13. It seems our tooling on that branch does not understand this new directive. Running `make -C Documentation` on the first commit yields the following error: `helm-values.rst:8: ERROR: Unknown interpreted text role "spelling:ignore"`

**Comment by qmonnet** [comment]
> Running `make -C Documentation` on the first commit yields the following error: `helm-values.rst:8: ERROR: Unknown interpreted text role "spelling:ignore"`

This should be addressed by the change in this PR on Documentation/check-build.sh. Unless the rstcheck version in 1.13 is too old? I'll look into it and backport.

**Comment by qmonnet** [comment]
Turns out this was more complex than I thought; but backports to 1.12, 1.13, 1.14 are now all done.

**Pull request merged**
