### PR TITLE
datapath: Fix NodePort reply mark

### PR DESCRIPTION
**Pull request by brb**
This PR fixes the following issues:

- 867fc862 did not set the mark mask in the iptables rule, so all packets were excluded due to the exact match.
- 867fc862 did not mark skb in the case of IPv4.
- In the case of `request -> host A -> host B -> endpoint B`, endpoint `B` does not know that the request came via NodePort, so the mark cannot be set based on the CT `node_port` bit. Due to this, we mark all reply packets to bypass the cilium masquerade non-cluster iptables rule when BPF NodePort is enabled.

Fixes: 867fc862 ("datapath: Avoid MASQing NodePort replies")

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8481)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failed due to provisioning errors.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by brb** [comment]
CI provisioning failure.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failed due to:
```
[2019-07-07T15:06:31.596Z]     k8s2-1.10: [discovery] Failed to request cluster info, will try again: [Get https://192.168.36.11:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 192.168.36.11:6443: getsockopt: no route to host]
```

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI is failing due to provisioning errors.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
Just tested locally, fixing the rule brings back the problem which https://github.com/cilium/cilium/commit/867fc862c71cb174d0f196214b179bafc4d0b6b4 supposed to fix. Adding `wip` label.

**Comment by brb** [comment]
Resolved. PTAL.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
privilege runtime tests failed due to a very rare kernel race condition when installing nexthop routes

**Comment by tgraf** [comment]
test-me-please

**Comment by joestringer** [comment]
privileged runtime tests failed again:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13485/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/

```
	 node_linux_test.go:668:
	     c.Assert(err, check.IsNil)
	 ... value *errors.errorString = &errors.errorString{s:"route to destination 4.4.4.4 contains gateway 4.4.4.4, must be directly reachable"} ("route to destination 4.4.4.4 contains gateway 4.4.4.4, must be directly reachable")
	 
	 START: node_linux_test.go:123: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:123: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest	0.029s
	 
	 FAIL: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestNodeUpdateDirectRouting
```
...
```
	 level=warning msg="Unable to install direct node route {Ifindex: 0 Dst: 5.5.5.0/24 Src: <nil> Gw: 4.4.4.4 Flags: [] Table: 0}" error="route to destination 4.4.4.4 contains gateway 4.4.4.4, must be directly reachable" subsys=linux-datapath
	 node_linux_test.go:668:
	     c.Assert(err, check.IsNil)
	 ... value *errors.errorString = &errors.errorString{s:"route to destination 4.4.4.4 contains gateway 4.4.4.4, must be directly reachable"} ("route to destination 4.4.4.4 contains gateway 4.4.4.4, must be directly reachable")
	 
	 START: node_linux_test.go:127: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:127: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.035s
	 
	 FAIL: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestNodeUpdateDirectRouting
```
...
```
	 level=warning msg="Unable to install direct node route {Ifindex: 0 Dst: 5.5.5.0/24 Src: <nil> Gw: 4.4.4.4 Flags: [] Table: 0}" error="route to destination 4.4.4.4 contains gateway 4.4.4.4, must be directly reachable" subsys=linux-datapath
	 node_linux_test.go:668:
	     c.Assert(err, check.IsNil)
	 ... value *errors.errorString = &errors.errorString{s:"route to destination 4.4.4.4 contains gateway 4.4.4.4, must be directly reachable"} ("route to destination 4.4.4.4 contains gateway 4.4.4.4, must be directly reachable")
	 
	 START: node_linux_test.go:131: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest
	 PASS: node_linux_test.go:131: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest	0.031s
	 
	 FAIL: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestNodeUpdateDirectRouting
```

**Comment by tgraf** [comment]
I've run the privileged tests manually on this branch several times without issues.

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by brb** [comment]
> I've run the privileged tests manually on this branch several times without issues.

@tgraf The CI is using the ubuntu-next due to the `ci/net-next` label. Are you using the same VM image?

**Comment by tgraf** [comment]
> The CI is using the ubuntu-next due to the `ci/net-next` label. Are you using the same VM image?

Aha! No, I'm not. This is a potential kernel regression then.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by tgraf** [comment]
I think this is a change in kernel behavior:

```
        routes, err = netlink.RouteGet(nodeIP)
        if err != nil {
                err = fmt.Errorf("unable to lookup route for node %s: %s", nodeIP, err)
                return
        }

        if routes[0].Gw != nil && !routes[0].Gw.IsUnspecified() {
                err = fmt.Errorf("route to destination %s contains gateway %s, must be directly reachable",
                        nodeIP, routes[0].Gw.String())
                return
        }
```

**Comment by brb** [comment]
> I think this is a change in kernel behavior

@tgraf You are right. https://github.com/cilium/cilium/pull/8513

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]

**Comment by brb** [comment]
test-me-pease

**Comment by brb** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Comment by brb** [comment]
CI failed due to `Suite-k8s-1.15.K8sHealthTest checks cilium-health status between nodes` - seems to be a new flake.
[a26e4d6a_K8sHealthTest_checks_cilium-health_status_between_nodes.zip](https://github.com/cilium/cilium/files/3382297/a26e4d6a_K8sHealthTest_checks_cilium-health_status_between_nodes.zip) /cc @gandro

**Comment by brb** [comment]
test-me-please

**Pull request merged**
