### PR TITLE
policy: Track policy entries with no owners to avoid BPF state leaks

### LINKED ISSUE #18581: eBPF map "policy" fills up (resource leak)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Using Cilium version 1.11.0 (and 1.11.1) we run into problems with exceeding the eBPF map size for the *policy* map of the clusters CoreDNS Pods. We already increased bpf-map-dynamic-size-ratio from 0.0025 (the default setting) to 0.01 to increase all map sizes. However, after some hours (and several hundred very short-lived CronJob Pods later) we again hit the policy map size limit.

Once the eBPB map is full, traffic to CoreDNS will be dropped and (affected) workloads on the cluster start to fail as they no longer can resolve DNS names.

It looks like there is some garbage collection issues (bug) with Cilium not removing old (stale) map entries, kind-of-a resource leak. 

Below the `CiliumNetworkPolicy` which causes this problem. Removing that policy from our clusters resolves the problem.

```yaml
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: coredns
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      k8s-app: coredns
  ingress:
    # Allow DNS access from any namespace and pod inside this Kubernetes cluster.
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
        - ports:
            - port: "53"
              protocol: TCP 
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: grafana-agent
            app.kubernetes.io/instance: grafana-agent-metrics
            io.kubernetes.pod.namespace: grafana-agent-system
        - matchLabels:
            app.kubernetes.io/name: datadog
            app.kubernetes.io/component: cluster-agent
            io.kubernetes.pod.namespace: kube-system
        - matchLabels:
            app.kubernetes.io/name: datadog
            app.kubernetes.io/component: agent
            io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "9153"
  egress:
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
        - ports:
            - port: "53"
              protocol: TCP
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
```

### Cilium Version

We observe that behavior with the following Cilium version:
- 1.11.1
- 1.11.0

### Kernel Version

We observe this behavior with the following kernel version:
- 5.4.156
- 5.10.75

### Kubernetes Version

1.21 (EKS)

### Sysdump

_No response_

### Relevant log output

```shell
msg="Failed to add PolicyMap key" bpfMapKey="{31163 53 6 0}" containerID=94cb79724b datapathPolicyRevision=12 desiredPolicyRevision=12 endpointID=2200 error="Unable to update element for cilium_policy_02200 map with file descriptor 88: the map is full, please consider resizing it. argument list too long" identity=7935 ipv4=10.176.27.102 ipv6= k8sPodName=kube-system/coredns-6df967c45d-fcfnk port=0 subsys=endpoint
```

### Anything else?

Related [Slack thread](https://cilium.slack.com/archives/C01JALNQAR1/p1640211424433400)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aditighag**
When an identity is deleted, the agent processes the incremental policy
map changes against previously saved policy state with owners
and dependents of the identity key to decide if an identity can be marked for
deletion in the `deletes` map. In some cases, the `owners` field for the identity
entry was nil, and the deleteKeyWithChanges would return early without tracking
the identity for deletion. As a result, when this information is consumed
later to delete the identity from the BPF maps, the identity was being leaked
in those cases.

Fix : While removing contributions of an owner passed via incremental map
changes to an identity entry, check if the store policy map state for the
entry had any previously populated owners.
If no owners found, the key entry will be removed from the map as expected
so that the deleted identity is correctly tracked in the `deletes` map.

See this issue for more details about how the design
can be improved - https://github.com/cilium/cilium/issues/19003.

Snippet of leaked identity entries in an affected cluster -

```
$ kubectl get ciliumidentity 2025
NAME   NAMESPACE   AGE
2025   default     99s

$ kubectl -n kube-system exec cilium-ktdhh -c cilium-agent -- cilium bpf policy get -n 2382 | grep 2025

$ kubectl get ciliumidentity 2025
Error from server (NotFound): ciliumidentities.cilium.io "2025" not found

$ kubectl -n kube-system exec cilium-ktdhh -c cilium-agent -- cilium bpf policy get -n 2382 | grep 2025
Allow    Ingress     2025       ANY          NONE         0          0

```

Fixes: #18581
Fixes: https://github.com/cilium/cilium/commit/0d585f110846237eb3611e88d0992ba26a162f72

**Release note**
```release-note
Fix issue with deleted identities not getting cleaned up from BPF maps leading to policy sync-up issues because of map being full.
```

### CODE REVIEW

**Review by joestringer — APPROVED** [review]
OK, basically if the entry has no owners, we pick up on that case and delete the entry itself.

Ideally we would find out that this is occurring when removing the last owner originally, but I guess we can't yet track down where that is?

The proposed patch seems OK to me, the only dangers are:
* Whatever the root cause of ending up with an entry with no owner, that path could still occur and apparently it's not exactly the same as this code path. If there's any way for that condition to persist for a while, we could theoretically still have the same class of problem.
* Alternatively, if there's some path that injects these entries without an owner in the first place, but that entry corresponds to a legitimate entry that should exist, then this patch could cause such entries to get randomly deleted after the first insertion, even if it should correspond to a legitimate key in the map. Then maybe we deny traffic that should be allowed because we prematurely clean up the entry.

Absent more thorough testing, I don't see a clear way to identify either of these conditions.

**Comment by aditighag** [comment]
Oops, we had a race - I was adding more comments and unit tests, that's why the PR was in the draft state. Please check the updated commits and unit test that I just pushed. :)

**Comment by aditighag** [comment]
>Ideally we would find out that this is occurring when removing the last owner originally, but I guess we can't yet track down where that is?

Exactly, https://github.com/cilium/cilium/issues/19003 has more details.

>Alternatively, if there's some path that injects these entries without an owner in the first place, but that entry corresponds to a legitimate entry that should exist

Looking at the callers of `addKeyWithChanges`, I'm not sure if we could have such a path. @jrajahalme might have more context. #19003 calls out this limitation that we can't easily track/validate consumer sites that  mutate owners/dependents fields.

**Comment by aditighag** [comment]
Superseded by https://github.com/cilium/cilium/pull/19005.

**Pull request closed without merging**
