### PR TITLE
bpf: Derive proxy_port from policy rather than CT

### PR DESCRIPTION
**Pull request by tgraf**
Trust the policy's determination of proxy_port rather than using the
conntrack entry for determining whether to send to the proxy in the
forward direction. This should allow traffic to fail over to via proxy
or not via proxy quickly when the policy is changed, rather than waiting
for an out-of-band userspace thread to iterate through the conntrack
entries and update the conntrack entry with the correct proxy_port.

Fixes: #3552

Signed-off-by: Joe Stringer <joe@covalent.io>

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Seems to have gotten stuck.

**Comment by joestringer** [comment]
test-me-please

**Comment by tgraf** [comment]
@joestringer Successful build, fix manually tested and confirmed as well. Feel free to update the commit message and rebase. Will merge afterwards.

**Comment by joestringer** [comment]
@tgraf done.

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
