### PR TITLE
Change kafka docker image to point to a more stable tag 1.1.0

### PR DESCRIPTION
**Pull request by manalibhutiyani**
Fixes: #4481
Related-to: #4431
Signed-Off-By: Manali Bhutiyani <manali@covalent.io>

```release-note
Change kafka docker image to point to a more stable tag 1.1.0
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4464)

### CODE REVIEW

**Comment by manalibhutiyani** [comment]
test-me-please

**Comment by tgraf** [comment]
Last run succeeded, running again

**Comment by tgraf** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
Hit another existing CI issue #4357 Trying again

**Comment by manalibhutiyani** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
Not sure why CI is not being triggered. trying again

**Comment by manalibhutiyani** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
test-me-please

**Comment by eloycoto** [comment]
Hit kafka issue: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4072/testReport/junit/k8s-1/7/K8sValidatedKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

**Comment by manalibhutiyani** [comment]
Yup, the fix is not going to work unfortunately :(

**Comment by manalibhutiyani** [comment]
@tgraf : I still feel this change is a good to have, even if it does not fix the issue. Should I put it out for review. This way we will not depend on latest kafka docker image and stick to a more stable version, avoiding any failures if something changes in the latest kafka image.

**Comment by tgraf** [comment]
> I still feel this change is a good to have, even if it does not fix the issue. Should I put it out for review. This way we will not depend on latest kafka docker image and stick to a more stable version, avoiding any failures if something changes in the latest kafka image.

Agreed

**Comment by manalibhutiyani** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]

**Comment by manalibhutiyani** [comment]
test-docs-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
