### PR TITLE
v1.15 Backports 2024-07-01

### PR DESCRIPTION
**Pull request by pippolo84**
* [x] #33260 (@sgargan) :warning: resolved conflicts
 * [x] #33382 (@gandro)
 * [x] #33421 (@brb)
 * [x] #33311 (@pippolo84)
 * [x] #33427 (@marseel) :warning: resolved conflicts
 * [x] #33448 (@jrajahalme) :warning: resolved conflicts
 * [x] #33442 (@aditighag) :warning: resolved conflicts
 * [x] #33444 (@brb) :warning: resolved conflicts

PRs skipped due to conflicts:

 * #33403 (@sayboras) :x: Dropped because there is no `pkg/ciliumenvoyconfig/envoy_l7lb_backend_syncer.go` in v1.15

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33260 33382 33421 33311 33427 33448 33442 33444
```

### CODE REVIEW

**Review by marseel — APPROVED** [review]
Thank you!

**Review by aanm — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]

**Comment by pippolo84** [comment]
/test-backport-1.15

**Review by gandro — APPROVED** [review]

**Review by brb — APPROVED** [review]
Both my PRs :+1: Thanks!

**Comment by pippolo84** [comment]
Force-pushed to solve conflict in `install/kubernetes/Makefile.values` with v1.15 target branch

**Comment by pippolo84** [comment]
/test-backport-1.15

**Review by jrajahalme — APPROVED** [review]

**Review by ysksuzuki — APPROVED** [review]
LGTM for the LRP changes

**Pull request merged**
