### PR TITLE
v1.14 Backports 2023-07-24

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #26773 (@squeed)
 * [x] #26455 (@alan-kut)
 * [x] #26864 (@meyskens)
 * [x] #26808 (@pchaigno)
 * [x] #26658 (@tommyp1ckles)
 * [x] #26901 (@jibi)
 * [x] #26933 (@nbusseneau)
 * [x] #26868 (@giorio94)
 * [x] #26884 (@julianwiedmann)
 * [x] #26956 (@julianwiedmann)
 * [x] #26951 (@ldelossa)
 * [x] #26719 (@christarazi)
 * [x] #26911 (@meyskens)
 * [x] #26867 (@rauanmayemir)
 * [x] #26934 (@michi-covalent)
 * [x] #26979 (@pchaigno)
 * [x] #26986 (@sayboras)
 * [x] #26912 (@giorio94)
 * [x] #26999 (@aanm)
 * [x] #27011 (@geakstr)
 * [x] #26984 (@sayboras)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 26773 26455 26864 26808 26658 26901 26933 26868 26884 26956 26951 26719 26911 26867 26934 26979 26986 26912 26999 27011 26984; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=26773,26455,26864,26808,26658,26901,26933,26868,26884,26956,26951,26719,26911,26867,26934,26979,26986,26912,26999,27011,26984
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
@julianwiedmann Please see backporter's notes for your commits, had conflicts to resolve.

**Review by michi-covalent — APPROVED** [review]
💞

**Comment by nbusseneau** [comment]
/test-backport-1.14

**Review by tommyp1ckles — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
My changes look good. Thanks!

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commits 👍

**Review by giorio94 — APPROVED** [review]
My commits look good. Thanks!

**Review by geakstr — APPROVED** [review]

**Review by jibi — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by squeed — APPROVED** [review]

**Review by meyskens — APPROVED** [review]
LGTM for my changes

**Comment by nbusseneau** [comment]
All testing has passed, almost all reviews are in and the remaining ones are for backports that did not hit any conflicts and are not complex, I will mark this `ready-to-merge`.

**Pull request merged**
