### PR TITLE
[v1.13] service: Update for L7 LB while locked

### PR DESCRIPTION
**Pull request by jrajahalme**
* [ ] #31744(@jrajahalme)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
31744
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.13

**Comment by lmb** [comment]
/test-1.21-4.19

**Comment by lmb** [comment]
/test-1.22-4.19

**Comment by lmb** [comment]
/test-1.24-4.19

**Comment by lmb** [comment]
/test-1.24-5.4

**Review by lmb — APPROVED** [review]
tophat

**Pull request merged**
