### PR TITLE
vagrant: bump server VM image for net-next updates

### PR DESCRIPTION
**Pull request by borkmann**
See commit msg.

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Comment by borkmann** [comment]
Hit #10770 on arm64.

**Comment by borkmann** [comment]
Hit #10760.

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Pull request merged**
