### PR TITLE
v1.11 backports 2022-04-08

### PR DESCRIPTION
**Pull request by jrajahalme**
* #18618 -- pull in the latest changes from github.com/vishvananda/netlink (@aditighag)
 * #19310 -- Test runtime cilium in container (take two) (@jrajahalme)
 * #19358 -- test: Fix whitespace in docker-run-cilium (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18618 19310 19358; do contrib/backporting/set-labels.py $pr done 1.11; done

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.11

**Review by nbusseneau — APPROVED** [review]

**Comment by jrajahalme** [comment]
/test-backport-1.11

**Comment by jrajahalme** [comment]
/test-backport-1.11

**Comment by jrajahalme** [comment]
/test-backport-1.11

**Comment by jrajahalme** [comment]
runtime VM provisioning fail, but apparently not due to these changes. Restarting.

**Comment by jrajahalme** [comment]
k8s VM provisioning timing out in the middle of pulling all the test images, in test-1.23-4.9 and test-1.16-netnext. As the VM box image does not have the images we should either update the box image, or allow more time for pulling them. Now each test spent 45 minutes (3 retries, max 15 minutes each), and I'd think it would have been done in maybe 20 minutes.. Maybe 2 x 25 minutes would be better than 3 x 15?

**Comment by jrajahalme** [comment]
/test-1.16-netnext

**Comment by jrajahalme** [comment]
/test-1.23-4.9

**Comment by jrajahalme** [comment]
test-1.16-netnext cut short downloading test images, restarting

**Comment by jrajahalme** [comment]
/test-1.16-netnext

**Comment by jrajahalme** [comment]
Superceded by #19403

**Comment by jrajahalme** [comment]
Re-opening for testing this:
```
>  2022-04-12T09:06:38.940189722Z level=fatal msg="Unable to mount BPF filesystem" error="multiple mount points detected at /sys/fs/bpf" subsys=bpf
```

**Comment by tklauser** [comment]
Can this be closed now that #19403 was merged containing these backports?

**Comment by tklauser** [comment]
Can this be closed now that #19403 was merged containing these backports?

**Pull request closed without merging**
