### PR TITLE
v1.7 backport for #11333

### PR DESCRIPTION
**Pull request by joestringer**
* #11333 -- Fix fromCIDR policy on kernels 4.10 or older and extend test coverage (@willdeuschle)
  * Had to rebase against `resolve_srcid_ipv[46]()` refactoring in master (not present in v1.7).

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 11333; do contrib/backporting/set-labels.py $pr done 1.7; done
```

Currently I backported this including all test changes, but if we hit issues because the required test code is not available I'll just drop them and rework this to only include the functional fix.

### CODE REVIEW

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Comment by joestringer** [comment]
Hit known flake #10442.

**Comment by joestringer** [comment]
I'll hold off on rebasing this until #11233 goes in to minimize the conflicts there.

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Review by gandro — APPROVED** [review]

**Comment by gandro** [comment]
restart-ginkgo

**Comment by gandro** [comment]
restart-ginkgo

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Pull request merged**
