### PR TITLE
[v1.12] Author backport of "Address ipcache startup perfomance regression"

### PR DESCRIPTION
**Pull request by bimmlerd**
* [ ] #25007 (@bimmlerd)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 25007; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=25007
```

### CODE REVIEW

**Comment by pchaigno** [comment]
(FYI, having the PR title in the backport PR title helps quickly triaging GitHub notifications.)

**Comment by bimmlerd** [comment]
Left backporter's notes in the commits, but here's a summary of the conflicts:
- portmap{,_test}.go lives in `pkg/policy` instead of `pkg/types`
- no generics, hence needed to copy `counter.Counter` implementations into the redeclared methods on `PortProtoSet`
- ipcache/types.go is not a thing, moved the `namedPortMultiMapUpdater` interface into `ipcache.go` at the very bottom.

**Comment by bimmlerd** [comment]
> (FYI, having the PR title in the backport PR title helps quickly triaging GitHub notifications.)

yeah the original title is created by tooling, but I agree it isn't very helpful, I'll think on improving it and add the title instead of the number here

**Comment by bimmlerd** [comment]
/test-backport-1.12

**Comment by bimmlerd** [comment]
/test-1.19-4.9

**Review by joestringer — APPROVED** [review]

**Pull request merged**
