### PR TITLE
v1.3: disable microscope in CI

### PR DESCRIPTION
**Pull request by ianvernon**
Microscope is disabled in v1.4 and master CI due to concerns around performance / stability in the Cilium CI. Disable it in v1.3 as well.

This is a partial backport of #6110.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6669)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
K8s tests failed:

`JoinEP` found in logs:

```
$ grep -r "JoinEP" * 
cilium-test.log:2019-01-17T01:22:56.790102984Z level=warning msg="JoinEP: Failed to load program" containerID=ad77701dd4 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=22060 error="Failed to replace Qdisc for lxccd6e15799b4a: Link not found" file-path=22060_next/bpf_lxc.o ipv4=10.10.1.122 ipv6="f00d::a0a:100:0:562c" k8sPodName=monitoring/prometheus-core-846d65749f-rvlq2 subsys=datapath-loader veth=lxccd6e15799b4a
cilium-test.log:2019-01-17T01:22:58.961733531Z level=warning msg="JoinEP: Failed to load program" containerID=16afe38c99 datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=13922 error="Failed to replace Qdisc for lxc65d16625199b: Link not found" file-path=13922_next/bpf_lxc.o ipv4=10.10.1.160 ipv6="f00d::a0a:100:0:3662" k8sPodName=default/testds-6k492 subsys=datapath-loader veth=lxc65d16625199b
cilium-test.log:2019-01-17T01:22:59.920595089Z level=warning msg="JoinEP: Failed to load program" containerID=696a463606 datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=21649 error="Failed to replace Qdisc for lxc3714a3ab929d: Link not found" file-path=21649_next/bpf_lxc.o ipv4=10.10.1.68 ipv6="f00d::a0a:100:0:5491" k8sPodName=default/testclient-lzkfm subsys=datapath-loader veth=lxc3714a3ab929d
cilium-test.log:2019-01-17T01:22:56.278082608Z level=warning msg="JoinEP: Failed to load program" containerID=7c9ac116d6 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=14316 error="Failed to replace Qdisc for lxc238f000cf20f: Link not found" file-path=14316_next/bpf_lxc.o ipv4=10.10.0.241 ipv6="f00d::a0a:0:0:37ec" k8sPodName=default/testclient-jlgbw subsys=datapath-loader veth=lxc238f000cf20f
cilium-test.log:2019-01-17T01:22:57.468883052Z level=warning msg="JoinEP: Failed to load program" containerID=6974d4b036 datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=65389 error="Failed to replace Qdisc for lxc3f72bbde623a: Link not found" file-path=65389_next/bpf_lxc.o ipv4=10.10.0.246 ipv6="f00d::a0a:0:0:ff6d" k8sPodName=default/testds-td8zp subsys=datapath-loader veth=lxc3f72bbde623a
pod-kube-system-cilium-f5r9z-cilium-agent.log:2019-01-17T01:22:56.790102984Z level=warning msg="JoinEP: Failed to load program" containerID=ad77701dd4 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=22060 error="Failed to replace Qdisc for lxccd6e15799b4a: Link not found" file-path=22060_next/bpf_lxc.o ipv4=10.10.1.122 ipv6="f00d::a0a:100:0:562c" k8sPodName=monitoring/prometheus-core-846d65749f-rvlq2 subsys=datapath-loader veth=lxccd6e15799b4a
pod-kube-system-cilium-f5r9z-cilium-agent.log:2019-01-17T01:22:58.961733531Z level=warning msg="JoinEP: Failed to load program" containerID=16afe38c99 datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=13922 error="Failed to replace Qdisc for lxc65d16625199b: Link not found" file-path=13922_next/bpf_lxc.o ipv4=10.10.1.160 ipv6="f00d::a0a:100:0:3662" k8sPodName=default/testds-6k492 subsys=datapath-loader veth=lxc65d16625199b
pod-kube-system-cilium-f5r9z-cilium-agent.log:2019-01-17T01:22:59.920595089Z level=warning msg="JoinEP: Failed to load program" containerID=696a463606 datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=21649 error="Failed to replace Qdisc for lxc3714a3ab929d: Link not found" file-path=21649_next/bpf_lxc.o ipv4=10.10.1.68 ipv6="f00d::a0a:100:0:5491" k8sPodName=default/testclient-lzkfm subsys=datapath-loader veth=lxc3714a3ab929d
pod-kube-system-cilium-q6q8t-cilium-agent.log:2019-01-17T01:22:56.278082608Z level=warning msg="JoinEP: Failed to load program" containerID=7c9ac116d6 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=14316 error="Failed to replace Qdisc for lxc238f000cf20f: Link not found" file-path=14316_next/bpf_lxc.o ipv4=10.10.0.241 ipv6="f00d::a0a:0:0:37ec" k8sPodName=default/testclient-jlgbw subsys=datapath-loader veth=lxc238f000cf20f
pod-kube-system-cilium-q6q8t-cilium-agent.log:2019-01-17T01:22:57.468883052Z level=warning msg="JoinEP: Failed to load program" containerID=6974d4b036 datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=65389 error="Failed to replace Qdisc for lxc3f72bbde623a: Link not found" file-path=65389_next/bpf_lxc.o ipv4=10.10.0.246 ipv6="f00d::a0a:0:0:ff6d" k8sPodName=default/testds-td8zp subsys=datapath-loader veth=lxc3f72bbde623a
```

This was tracked by https://github.com/cilium/cilium/issues/6059 , the purported fix for which was backported ( 
https://github.com/cilium/cilium/pull/6551 ). This is unrelated to the changes in this PR.

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
K8s tests failed: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1526

/Cilium-etcd-operator failed to start.

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
K8s tests failed again: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1530/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
PR time reduces by almost 30 minutes with this change, which will greatly enhance the velocity of backports to v1.3.

**Review by tgraf — APPROVED** [review]

**Pull request merged**
