### PR TITLE
v1.12 Backports 2023-06-06

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
* [x] #25079 (@pchaigno)
 * [x] #25774 (@michi-covalent)
   * [x] ⚠️ Observed minor conflicts

Skipped due to major conflicts

* cilium/cilium#25450
  * Same reason as v1.13 backport (https://github.com/cilium/cilium/pull/25855)
* cilium/cilium#25419
  * Same reason as v1.13 backport (https://github.com/cilium/cilium/pull/25855)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 25079 25774; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=25079,25774
```

### CODE REVIEW

**Comment by YutaroHayakawa** [comment]
/test-backport-1.12

**Review by pchaigno — APPROVED** [review]
My PR looks good to me.

**Review by michi-covalent — APPROVED** [review]
https://github.com/cilium/cilium/pull/25774 lgtm

**Comment by YutaroHayakawa** [comment]
/test-1.20-4.9

**Comment by YutaroHayakawa** [comment]
Cilium L4LB XDP is not triggered. Manually triggering.

**Comment by YutaroHayakawa** [comment]
/ci-l4lb-1.12

**Comment by YutaroHayakawa** [comment]
All green and reviews are in. Ready to merge.

**Pull request merged**
