### PR TITLE
multicast: modify list operations from iterator to batch lookup.

### PR DESCRIPTION
**Pull request by harsimran-pabla**
This change modifying how groups and subsribers are listed. Current approach takes very long time to list bpf map data.

Also, fixing typo in multicast group map name in ELF ignore prefixes.

### Performance test
Added 255 groups and compare time to list them.

```
root@clab-multicast-devel-worker2:/home/cilium# for i in {1..255} ; do cilium bpf multicast group add 229.0.0.$i; done
```

With iterator, output is returned in ~6-7 seconds.
```
root@clab-multicast-devel-worker2:/home/cilium# time cilium-dbg bpf multicast group ls > /dev/null

real    0m6.646s
user    0m0.043s
sys     0m0.036s
root@clab-multicast-devel-worker2:/home/cilium#
```

With BatchLookup, output is returned in sub second range.
```
root@clab-multicast-devel-worker3:/home/cilium# time cilium-dbg bpf multicast group ls > /dev/null

real    0m0.039s
user    0m0.028s
sys     0m0.016s
root@clab-multicast-devel-worker3:/home/cilium#
```

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]
LGTM

**Comment by harsimran-pabla** [comment]
[EKS test failure](https://github.com/cilium/cilium/actions/runs/8421818221/job/23059632509) : https://github.com/cilium/cilium/issues/30990

**Comment by harsimran-pabla** [comment]
[IPSec ci failure](https://github.com/cilium/cilium/actions/runs/8421818866/job/23059623836#step:18:777) : https://github.com/cilium/cilium/issues/29846

**Review by rgo3 — APPROVED** [review]

**Comment by harsimran-pabla** [comment]
@markpash please have a look at this change whenever you get a chance 🙏

**Review by markpash — APPROVED** [review]

**Pull request merged**
