### PR TITLE
Bugtool commands list generation improvements

### PR DESCRIPTION
**Pull request by pippolo84**
Miscellaneous improvements to increase modularity and reusability of the bugtool helpers to generate the list of commands to be run.

This should ease the extensibility of bugtool itself in case we want to add some environment-specific command on top of the default ones.

Notes to the reviewers: better reviewed commit by commit.

### CODE REVIEW

**Review by derailed — APPROVED** [review]
@pippolo84 Nice work Fabio!

**Comment by pippolo84** [comment]
I realized I missed some minor changes, so I'll temporarily mark this as not ready to be merged.

**Comment by pippolo84** [comment]
Hey @derailed I added a couple of commits to make bugtool easily extendable for specific environments. Do you mind taking another look? Compare to the previous version you already reviewed, the changes are all in the last two commits. Thanks! :pray:

**Review by derailed — APPROVED** [review]
@pippolo84 Thanks for the updates!

**Comment by pippolo84** [comment]
- https://github.com/cilium/cilium/actions/runs/8967430105/job/24624952244?pr=32253 hit https://github.com/cilium/cilium/issues/13071

**Pull request merged**
