### PR TITLE
1.4 backports 19-02-26

### PR DESCRIPTION
**Pull request by nebril**
#7207
#7203
#7200
#7163

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7212)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
rerunning k8s tests, vagrant provisioning failed on CI

**Comment by jrfastab** [comment]
fyi @nebril I'm going to push https://github.com/cilium/cilium/pull/7202 before I merge this series to keep backports in order.

**Comment by joestringer** [comment]
Failure: 
```
11:43:03     k8s1-1.9: different structure types for CGO and GO: alignchecker._Ctype_struct_metrics_key != metricsmap.Key
11:43:03     k8s1-1.9: 
11:43:03     k8s1-1.9: panic: C struct field "reason" (2) has different size than GoStruct field "Reason" (1)
11:43:03     k8s1-1.9: 
11:43:03     k8s1-1.9: goroutine 1 [running]:
11:43:03     k8s1-1.9: github.com/cilium/cilium/pkg/alignchecker.init.0()
11:43:03     k8s1-1.9: 	/go/src/github.com/cilium/cilium/pkg/alignchecker/alignchecker.go:162 +0x1e1
11:43:03     k8s1-1.9: 
```

**Comment by ianvernon** [comment]
The alignchecker failure is intriguing. I checked out `v1.4` and this is the declaration of the `metricsmap.Key`: in `pkg/maps/metricsmap/metricsmap.go`:

```
// Key must be in sync with struct metrics_key in <bpf/lib/common.h>
type Key struct {
	Reason uint8
	Dir    uint8
	Pad1   uint16
	Pad2   uint32
}
```

and the corresponding C type:
```
struct metrics_key {
    __u8      reason;     //0: forwarded, >0 dropped
    __u8      dir:2,      //1: ingress 2: egress
              pad:6;
    __u16     reserved[3]; // reserved for future extension
};
```

The error: 
```
C struct field "reason" (2) has different size than GoStruct field "Reason" (1)
```

Is strange as both are `uint8`? The structs appear the same since reserved is 3 `uint16` which is equivalent in size to `Pad1` + `Pad2` in the C representation of the key. cc: @be right back  , any thoughts on this?

**Comment by brb** [comment]
This is because https://github.com/cilium/cilium/pull/7212/commits/f695dc7c66a221ef1096353e022b31071bd0296b got backported which cannot be backported without https://github.com/cilium/cilium/pull/7162. Please see https://github.com/cilium/cilium/issues/6559. Sorry for not explicitly mentioning in the PR description https://github.com/cilium/cilium/pull/7163.

**Comment by joestringer** [comment]
Superseded by #7232.

**Pull request closed without merging**
