### PR TITLE
Fix CIDR coalescing issue in ExceptCIDR rule expressions

### PR DESCRIPTION
**Pull request by jrajahalme**
Fix CIDR rule exception handling cases where
- `ExceptCIDRs` contains the CIDR itself. In this case nothing should be allowed.
- exception handling errors out and drops the whole CIDR while part of if should be allowed.

The same bug could have allowed excluded CIDRs in deny rules (beta feature).

**Note to backporters**: Only the first commit needs to be backported.

```release-note
Fix CIDR rule bug potentially dropping allowed traffic or allowing denied traffic for deny policies (beta feature) when using ExceptCIDRs expressions.
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Known runtime flake #14463

**Comment by jrajahalme** [comment]
retest-runtime

**Review by aanm — APPROVED** [review]
the changes look fine overall to me. However, it would be nice to split this PR to avoid backporting refactoring changes to older branches.

**Comment by jrajahalme** [comment]
@aanm I'd rather instruct the backporter to only backport the first commit, would that work for you?

**Comment by aanm** [comment]
> @aanm I'd rather instruct the backporter to only backport the first commit, would that work for you?

yeah, that sounds sane.

**Review by gandro — APPROVED** [review]

**Pull request merged**
