### PR TITLE
chore(deps): update docker.io/library/golang docker tag to v1.19.11

### PR DESCRIPTION
**Pull request by ferozsalam**
A very lightly edited cherry-pick of commit 93e613e to try and ensure that renovate doesn't attempt to autoclose it.

### CODE REVIEW

**Comment by ferozsalam** [comment]
/test-backport-1.11

**Comment by ferozsalam** [comment]
/test-1.19-4.9

**Comment by ferozsalam** [comment]
/test-1.21-4.9

**Review by aanm — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by ferozsalam** [comment]
/test-1.19-4.9

**Review by ldelossa — APPROVED** [review]

**Pull request merged**
