### PR TITLE
metrics: add cilium_datapath_nat_gc_entries

### PR DESCRIPTION
**Pull request by ArthurChiao**
This patch adds NAT GC metrics to current metrics list. ~~As NAT entries are
GC'd alongside CT entries and NAT module has no dedicated GC jobs, we
calculate the NAT metrics in CT module's GC job.~~

Signed-off-by: ArthurChiao <arthurchiao@hotmail.com>

### CODE REVIEW

**Review by brb — CHANGES_REQUESTED** [review]
Thanks for your PR!

Unfortunately, iterating over all NAT entries just to update metrics counters each time we do GC of CT entries is too expensive operation. We might introduce such iteration in #12686. So, I suggest to wait until the latter has been done.

**Comment by ArthurChiao** [comment]
Thanks @brb , then should close this PR right now?

**Comment by brb** [comment]
> Thanks @brb , then should I close this PR right now?

Let's keep it open. I've just changed its state to draft.

**Comment by brb** [comment]
@ArthurChiao https://github.com/cilium/cilium/pull/13912 got merged. Mind rebasing your PR and adding metrics?

**Comment by ArthurChiao** [comment]
Thanks for reminding me @brb.

> Yeah, we definitely need the metric for it. I will add it as a follow up.

I closed this PR as i saw the above message in #13912. So not sure if my PR is still needed?

**Comment by brb** [comment]
@ArthurChiao Yeah, the metrics part is still needed (I've only added the logging).

**Comment by ArthurChiao** [comment]
I'll have a look, thanks! @brb

**Comment by ArthurChiao** [comment]
Hi @brb, rebased to master, please have a review, thanks!

Note: currently this metric could only be enabled/disabled along with `cilium_datapath_conntrack_gc_entries`,
seems there is no need to add a dedicated flag to control NAT gc metric on/off?

Test output:

```
# HELP cilium_datapath_nat_gc_entries The number of alive and deleted nat entries at the end of a garbage collector run labeled by datapath family.
# TYPE cilium_datapath_nat_gc_entries gauge
cilium_datapath_nat_gc_entries{direction="egress",family="ipv4",status="deleted"} 0
cilium_datapath_nat_gc_entries{direction="ingress",family="ipv4",status="alive"} 11800
cilium_datapath_nat_gc_entries{direction="ingress",family="ipv4",status="deleted"} 0
```

**Review by brb — APPROVED** [review]
LGTM, thanks!

> Note: currently this metric could only be enabled/disabled along with cilium_datapath_conntrack_gc_entries,
seems there is no need to add a dedicated flag to control NAT gc metric on/off?

Yep, no need for a dedicated flag.

**Comment by brb** [comment]
test-me-please

**Pull request merged**
