### PR TITLE
Fix: Affinity in `cilium-pre-flight-check` daemonset

### LINKED ISSUE #26604: Missing affinity in the preflight daemonset template
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We need to deploy different preflight daemonsets across different node types. To do this we would like to set affinity on the preflight daemonset. 

https://github.com/cilium/cilium/blob/d102dbc5f1056493f01efea9c9059771b9c63823/install/kubernetes/cilium/values.yaml#L2546 - provides a way to set affinity for cilium-preflight. 

But because: 
https://github.com/cilium/cilium/blob/d102dbc5f1056493f01efea9c9059771b9c63823/install/kubernetes/cilium/templates/cilium-preflight/daemonset.yaml is missing: 
```
{{- with .Values.preflight.affinity }}
affinity:
  {{- toYaml . | trim | nindent 8 }}
{{- end }}
```
The affinity is not respected. 

### Cilium Version

Copied the template using 1.12.10 and 1.12.7 as the versions, but I assume this is across versions. 

### Kernel Version

n/a

### Kubernetes Version

n/a

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ishuar**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

- Fixes: https://github.com/cilium/cilium/issues/26604

```release-note
Fix: Affinity in cilium-pre-flight-check daemonset.
```

### CODE REVIEW

**Review by kaworu — APPROVED** [review]
Thanks!

**Comment by ishuar** [comment]
@kaworu  Is there anything needed from my side to get it merged?

**Review by joamaki — APPROVED** [review]

**Comment by joestringer** [comment]
The [runtime failure](https://github.com/cilium/cilium/actions/runs/5892738140/job/15982733154) is a known failure on the main branch https://github.com/cilium/cilium/issues/27080, unrelated to this PR. I'll re-run it to confirm.

**Pull request merged**
