### PR TITLE
[v1.12 backport] test: Switch target FQDN

### PR DESCRIPTION
**Pull request by nbusseneau**
Manual backport of https://github.com/cilium/cilium/pull/25571 to v1.12.

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.12

**Comment by nbusseneau** [comment]
/test-1.17-4.9

**Comment by nbusseneau** [comment]
/test-1.18-4.9

**Comment by nbusseneau** [comment]
/test-1.21-4.9

**Review by pchaigno — APPROVED** [review]

**Comment by nbusseneau** [comment]
1.21 / 4.9 hit #22554.

Marking ready to merge.

**Pull request merged**
