### PR TITLE
Fix CGO import warning

### PR DESCRIPTION
**Pull request by joestringer**
The golang compilation would previously print this warning while
compiling the daemon, because "bpf_htons" would not be declared when
importing the conntrack header file from CGO:

```
$ make -C daemon
  CHECK contrib/scripts/bindata.sh
  GO    daemon/cilium-agent
In file included from /home/joe/work/src/github.com/cilium/cilium/bpf/lib/conntrack.h:24:0,
                 from ../pkg/alignchecker/alignchecker.go:30:
/home/joe/work/src/github.com/cilium/cilium/bpf/lib/common.h: In function ‘conn_is_dns’:
/home/joe/work/src/github.com/cilium/cilium/bpf/lib/common.h:532:15: warning: implicit declaration of function ‘bpf_htons’ [-Wimplicit-function-declaration]
```

Fix this by shifting the function into a file which includes utils.h.

Developers may need to run the following command to clear out their CGO
caches to pick up these changes and silence the warning:

```
    $ go clean -cache
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5592)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by aanm** [comment]
@joestringer I've made https://github.com/cilium/cilium/pull/5601 without knowing about this PR. Which one do you want to merge? I'm fine either way.

**Comment by joestringer** [comment]
@aanm either way, strictly speaking the warning is right and the function kinda depends on the connections state to determine whether it's DNS.

**Review by aanm — APPROVED** [review]

**Comment by joestringer** [comment]
Marked for backport to 1.2 since the patch which introduced this warning was also backported. Might help people to avoid following the wrong error. Backporter, feel free to disregard if you feel this is extraneous.

**Pull request merged**
