### PR TITLE
vtep: VTEP redirection in bpf_host to-netdev to support L7 proxy

### PR DESCRIPTION
**Pull request by vincentmli**
L7 policies redirect packets on egress of bpf_lxc to userspace
proxy. When packets leave the proxy, they don't go back through
bpf_lxc again, so the VTEP redirectons won't be enforced. Add
the VTEP redirection in bpf_host to-netdev. This also requires
host having default route and the default route network device
has "to-netdev" attached.

Keep the VTEP redirection in bpf_lxc when L7 proxy is disabled
VTEP redirection would happen earlier to avoid packets passing to
host stack to be handled in bpf_host.

Reported-by: Paul Chaignon <paul@cilium.io>
Signed-off-by: Vincent Li <v.li@f5.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
resolve VTEP redirection and L7 proxy compitibility
```

### CODE REVIEW

**Comment by vincentmli** [comment]
Hi @pchaigno @joestringer Paul and I discussed the VTEP redirection to support L7 proxy, our conclusion is to have VTEP redirection in `to-netdev` similar to host firewall, bandwith...and require host having default route and default route device has `to-netdev` attached,  could  you review the PR, thank you!

**Comment by pchaigno** [comment]
> Keep the VTEP redirection in bpf_lxc when L7 proxy is disabled VTEP redirection would happen earlier to avoid packets passing to host stack to be handled in bpf_host.

As far as I understand, with the PR as it stands, the code in bpf_lxc will always match first, regardless of whether the L7 proxy is disabled or not.

**Comment by vincentmli** [comment]
> > Keep the VTEP redirection in bpf_lxc when L7 proxy is disabled VTEP redirection would happen earlier to avoid packets passing to host stack to be handled in bpf_host.
> 
> As far as I understand, with the PR as it stands, the code in bpf_lxc will always match first, regardless of whether the L7 proxy is disabled or not. I also wonder if this is worth the additional complexity to compile one piece and not the other.

when L7 is enabled, packet redirects to proxy and host stack, VTEP is skipped bpf_lxc, why it would still match in VTEP in bpf_lxc? because compiler could arrange the VTEP code before L7 proxy process?

**Comment by pchaigno** [comment]
> when L7 is enabled, packet redirects to proxy and host stack, VTEP is skipped bpf_lxc, why it would still match in VTEP in bpf_lxc? because compiler could arrange the VTEP code before L7 proxy process?

Oh, I think you're right. If the L7 proxy is enabled AND the packet matches an L7 policy, then we will hit the VTEP logic in bpf_host. Otherwise, we will the VTEP logic in bpf_lxc.

Then, how exactly did you test the first case? Did you load an L7 policy to make sure it works?

**Comment by vincentmli** [comment]
> > when L7 is enabled, packet redirects to proxy and host stack, VTEP is skipped bpf_lxc, why it would still match in VTEP in bpf_lxc? because compiler could arrange the VTEP code before L7 proxy process?
> 
> Oh, I think you're right. If the L7 proxy is enabled AND the packet matches an L7 policy, then we will hit the VTEP logic in bpf_host. Otherwise, we will the VTEP logic in bpf_lxc.
> 
> Then, how exactly did you test the first case? Did you load an L7 policy to make sure it works?

I tested with `enable-l7-proxy: "true"` and `enable-l7-proxy: "false"`, I did not test actual L7 policy, but from datapath debug log, I could tell if the VTEP is handled in `to-netdev` or `from-container`, I can double check

**Comment by pchaigno** [comment]
> I tested with `enable-l7-proxy: "true"` and `enable-l7-proxy: "false"`, I did not test actual L7 policy, but from datapath debug log, I could tell if the VTEP is handled in `to-netdev` or `from-container`, I can double check

Please double check, because as far as I can tell, unless you actually use L7 policies, it should always be handled in `from-container` with the current changes.

**Comment by vincentmli** [comment]
> > I tested with `enable-l7-proxy: "true"` and `enable-l7-proxy: "false"`, I did not test actual L7 policy, but from datapath debug log, I could tell if the VTEP is handled in `to-netdev` or `from-container`, I can double check
> 
> Please double check, because as far as I can tell, unless you actually use L7 policies, it should always be handled in `from-container` with the current changes.

I tested, it does confirm your observation, now I remembered when I was testing it, I actually removed the VTEP in bpf_lxc to test the correctness of VTEP in to-netdev, I also added `if defined(ENABLE_VTEP) && !defined(ENABLE_L7_PROXY)` to guard the VTEP in bpf_lxc from another closed draft PR https://github.com/cilium/cilium/pull/19473, I will add the if condition check back in bpf_lxc.

**Comment by vincentmli** [comment]
> > > I tested with `enable-l7-proxy: "true"` and `enable-l7-proxy: "false"`, I did not test actual L7 policy, but from datapath debug log, I could tell if the VTEP is handled in `to-netdev` or `from-container`, I can double check
> > 
> > 
> > Please double check, because as far as I can tell, unless you actually use L7 policies, it should always be handled in `from-container` with the current changes.
> 
> I tested, it does confirm your observation, now I remembered when I was testing it, I actually removed the VTEP in bpf_lxc to test the correctness of VTEP in to-netdev, I also added `if defined(ENABLE_VTEP) && !defined(ENABLE_L7_PROXY)` to guard the VTEP in bpf_lxc from another closed draft PR #19473, I will add the if condition check back in bpf_lxc.

I prefer to keep the VTEP in bpf_lxc because it can be assured to work for users and have good users experience, the VTEP in to-netdev  rely on default route conditions and to-netdev attachment, I understand your BPF complexity concern, I am more user oriented as my whole past career is to support customer :)

**Comment by vincentmli** [comment]
also here is datapath debug  log signature to tell if VTEP redirection happened in `from-container` in bpf_lxc or in `to-netdev` in bpf_host

In `to-netdev`, we can see `to-stack` right after `from-endpoint`, meaning packet passed to stack

```
CPU 02: MARK 0x0 FROM 1849 from-endpoint: 98 bytes (98 captured), state unknown, , identity 4352->unknown, orig-ip 0.0.0.0
CPU 02: MARK 0x0 FROM 1849 DEBUG: Successfully mapped addr=10.1.1.6 to identity=2
CPU 02: MARK 0x0 FROM 1849 DEBUG: Conntrack lookup 1/2: src=10.0.1.209:11860 dst=10.1.1.6:0
CPU 02: MARK 0x0 FROM 1849 DEBUG: Conntrack lookup 2/2: nexthdr=1 flags=1
CPU 02: MARK 0x0 FROM 1849 DEBUG: CT verdict: New, revnat=0
------------------------------------------------------------------------------
Ethernet        {Contents=[..14..] Payload=[..86..] SrcMAC=72:f2:09:b2:f0:b9 DstMAC=7e:a2:d5:c1:4f:03 EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..64..] Version=4 IHL=5 TOS=0 Length=84 Id=57038 Flags=DF FragOffset=0 TTL=63 Protocol=ICMPv4 Checksum=17923 SrcIP=10.0.1.209 DstIP=10.1.1.6 Options=[] Padding=[]}
ICMPv4  {Contents=[..8..] Payload=[..56..] TypeCode=EchoRequest Checksum=48830 Id=11860 Seq=1}
  Failed to decode layer: No decoder for layer type Payload
CPU 02: MARK 0x0 FROM 1849 to-stack: 98 bytes (98 captured), state new, , identity 4352->world, orig-ip 0.0.0.0
```

in `from-container`, we can see `to-overlay` right after `from-endpoint`

```
CPU 01: MARK 0x0 FROM 1849 from-endpoint: 98 bytes (98 captured), state unknown, , identity 4352->unknown, orig-ip 0.0.0.0
CPU 01: MARK 0x0 FROM 1849 DEBUG: Successfully mapped addr=10.1.1.6 to identity=2
CPU 01: MARK 0x0 FROM 1849 DEBUG: Conntrack lookup 1/2: src=10.0.1.209:20190 dst=10.1.1.6:0
CPU 01: MARK 0x0 FROM 1849 DEBUG: Conntrack lookup 2/2: nexthdr=1 flags=1
CPU 01: MARK 0x0 FROM 1849 DEBUG: CT verdict: New, revnat=0
CPU 01: MARK 0x0 FROM 1849 DEBUG: Conntrack create: proxy-port=0 revnat=0 src-identity=4352 lb=0.0.0.0
CPU 01: MARK 0x0 FROM 1849 DEBUG: Encapsulating to node 178866412 (0xaa948ec) from seclabel 2
------------------------------------------------------------------------------
Ethernet        {Contents=[..14..] Payload=[..86..] SrcMAC=72:f2:09:b2:f0:b9 DstMAC=82:36:4c:98:2e:56 EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..64..] Version=4 IHL=5 TOS=0 Length=84 Id=37298 Flags=DF FragOffset=0 TTL=64 Protocol=ICMPv4 Checksum=37407 SrcIP=10.0.1.209 DstIP=10.1.1.6 Options=[] Padding=[]}
ICMPv4  {Contents=[..8..] Payload=[..56..] TypeCode=EchoRequest Checksum=25370 Id=20190 Seq=1}
  Failed to decode layer: No decoder for layer type Payload
CPU 01: MARK 0x0 FROM 1849 to-overlay: 98 bytes (98 captured), state new, interface cilium_vxlan, , identity world->unknown, orig-ip 0.0.0.0
```

I would like to keep VTEP in bpf_lxc because it saves packet path when L7 proxy is disabled

**Comment by vincentmli** [comment]
Add VTEP redirection to `to-netdev` also requires `enable-bpf-masquerade: "true"`, otherwise, the inner packet source ip will be SNATed to ip on network device `ens224` that has default route and has `to-netdev` attached, 
for example:

route:

```
# ip r s
default via 10.3.254.254 dev ens224 proto static metric 101  <===default route
10.0.0.0/24 via 10.0.1.171 dev cilium_host src 10.0.1.171 mtu 1450 
10.0.1.0/24 via 10.0.1.171 dev cilium_host src 10.0.1.171 
10.0.1.171 dev cilium_host scope link 
10.3.72.0/24 dev ens224 proto kernel scope link src 10.3.72.233 metric 101 
10.3.254.254 dev ens224 proto static scope link metric 101 
10.169.72.0/24 dev ens192 proto kernel scope link src 10.169.72.233 metric 100 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
```
network device and ip, note `ens192` is k8s node interface, `ens224` is management network interface, both are configured in cilium `devices: ens224 ens192` which allow `to-netdev` attached

```
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:86:3d:0c brd ff:ff:ff:ff:ff:ff
    inet 10.169.72.233/24 brd 10.169.72.255 scope global noprefixroute ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::9c57:ea27:44ab:b238/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: ens224: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:86:08:b4 brd ff:ff:ff:ff:ff:ff
    inet 10.3.72.233/24 brd 10.3.72.255 scope global noprefixroute ens224
       valid_lft forever preferred_lft forever
    inet6 fe80::a9fb:af21:c91e:3a4c/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```
when `enable-bpf-masquerade: "false"`, ping vtep ip `10.1.1.6`, inner packet source ip snatted to `10.3.72.233`, thus the network breaks
tcpdump

```
15:43:30.717505 IP 10.3.72.233 > 10.1.1.6: ICMP echo request, id 16284, seq 6, length 64
15:43:31.741606 IP 10.3.72.233 > 10.1.1.6: ICMP echo request, id 16284, seq 7, length 64
```
when `enable-bpf-masquerade: "true"`, the pod source ip is preserved:

```
15:47:31.747053 IP 10.0.1.53 > 10.1.1.6: ICMP echo request, id 4441, seq 1, length 64
15:47:31.747081 IP 10.1.1.6 > 10.0.1.53: ICMP echo reply, id 4441, seq 1, length 64
```
Adding VTEP redirection in  `from-host` may not have this issue.

**Comment by vincentmli** [comment]
tested egress L7 proxy according to https://github.com/cilium/cilium-service-mesh-beta/tree/main/l7-traffic-management, it seems put VTEP redirection in `from-host` would support L7 proxy better than `to-netdev` according to the code path. I noticed when L7 proxy policy is deployed, test client pod curl request to remote pod, the client pod source ip `10.0.1.225` will be SNATed to cilium_host ip `10.0.1.171` before the tunnel encap, wonder why not preserve the client pod src ip even after L7 policy


from-endpoint -> to-proxy

```
1530798 Ethernet        {Contents=[..14..] Payload=[..62..] SrcMAC=f2:14:05:40:10:52 DstMAC=ea:4c:b9:66:0b:2c EthernetType=IPv4 Length=0}
1530799 IPv4    {Contents=[..20..] Payload=[..40..] Version=4 IHL=5 TOS=0 Length=60 Id=4917 Flags=DF FragOffset=0 TTL=64 Protocol=TCP Checksum=4342 SrcIP=10.0.1.225         DstIP=10.0.0.177 Options=[] Padding=[]}
1530800 TCP     {Contents=[..40..] Payload=[] SrcPort=35274 DstPort=8080(http-alt) Seq=2675677650 Ack=0 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=fal        se URG=false ECE=false CWR=false NS=false Window=64860 Checksum=5824 Urgent=0 Options=[..5..] Padding=[]}
1530801 CPU 05: MARK 0xf8b66a31 FROM 166 from-endpoint: 74 bytes (74 captured), state unknown, , identity 45118->unknown, orig-ip 0.0.0.0
1530802 CPU 05: MARK 0xf8b66a31 FROM 166 DEBUG: Successfully mapped addr=10.0.0.177 to identity=28188
1530803 CPU 05: MARK 0xf8b66a31 FROM 166 DEBUG: Conntrack lookup 1/2: src=10.0.1.225:35274 dst=10.0.0.177:8080
1530804 CPU 05: MARK 0xf8b66a31 FROM 166 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
1530805 CPU 05: MARK 0xf8b66a31 FROM 166 DEBUG: CT verdict: New, revnat=0
1530806 CPU 05: MARK 0xf8b66a31 FROM 166 DEBUG: Matched L4 policy; creating conntrack src=28188 dst=45118 dport=8080 proto=6
1530807 Policy verdict log: flow 0xf8b66a31 local EP ID 166, remote ID 28188, proto 6, egress, action redirect, match L3-L4, 10.0.1.225:35274 -> 10.0.0.177:8080 tcp         SYN
1530808 CPU 05: MARK 0xf8b66a31 FROM 166 DEBUG: Conntrack create: proxy-port=0 revnat=0 src-identity=45118 lb=0.0.0.0
1530809 ------------------------------------------------------------------------------
1530810 Ethernet        {Contents=[..14..] Payload=[..62..] SrcMAC=f2:14:05:40:10:52 DstMAC=ea:4c:b9:66:0b:2c EthernetType=IPv4 Length=0}
1530811 IPv4    {Contents=[..20..] Payload=[..40..] Version=4 IHL=5 TOS=0 Length=60 Id=4917 Flags=DF FragOffset=0 TTL=64 Protocol=TCP Checksum=4342 SrcIP=10.0.1.225         DstIP=10.0.0.177 Options=[] Padding=[]}
1530812 TCP     {Contents=[..40..] Payload=[] SrcPort=35274 DstPort=8080(http-alt) Seq=2675677650 Ack=0 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=fal        se URG=false ECE=false CWR=false NS=false Window=64860 Checksum=5824 Urgent=0 Options=[..5..] Padding=[]}
1530813 CPU 05: MARK 0xf8b66a31 FROM 166 to-proxy: 74 bytes (74 captured), state new, , identity 45118->unknown, orig-ip 0.0.0.0, to proxy-port 13663
1530814 CPU 05: MARK 0xf8b66a31 FROM 166 DEBUG: CT entry found lifetime=24373, revnat=0

```
from-proxy(from-host) -> to-overlay ->to-stack

```
1530909 CPU 02: MARK 0x94bed542 FROM 1825 DEBUG: Inheriting identity=45118 from stack
1530910 ------------------------------------------------------------------------------
1530911 Ethernet        {Contents=[..14..] Payload=[..62..] SrcMAC=de:d8:da:30:e0:3e DstMAC=de:d8:da:30:e0:3e EthernetType=IPv4 Length=0}
1530912 IPv4    {Contents=[..20..] Payload=[..40..] Version=4 IHL=5 TOS=0 Length=60 Id=19487 Flags=DF FragOffset=0 TTL=64 Protocol=TCP Checksum=55361 SrcIP=10.0.1.1        71 DstIP=10.0.0.177 Options=[] Padding=[]}
1530913 TCP     {Contents=[..40..] Payload=[] SrcPort=55650 DstPort=8080(http-alt) Seq=3821768027 Ack=0 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=fal        se URG=false ECE=false CWR=false NS=false Window=64860 Checksum=5770 Urgent=0 Options=[..5..] Padding=[]}
1530914 CPU 02: MARK 0x94bed542 FROM 1825 from-proxy: 74 bytes (74 captured), state unknown, , identity 45118->unknown, orig-ip 0.0.0.0
1530915 CPU 02: MARK 0x94bed542 FROM 1825 DEBUG: Encapsulating to node 178866415 (0xaa948ef) from seclabel 45118
1530916 ------------------------------------------------------------------------------
1530917 Ethernet        {Contents=[..14..] Payload=[..62..] SrcMAC=de:d8:da:30:e0:3e DstMAC=1e:06:de:db:e5:e1 EthernetType=IPv4 Length=0}
1530918 IPv4    {Contents=[..20..] Payload=[..40..] Version=4 IHL=5 TOS=0 Length=60 Id=19487 Flags=DF FragOffset=0 TTL=64 Protocol=TCP Checksum=55361 SrcIP=10.0.1.1        71 DstIP=10.0.0.177 Options=[] Padding=[]}
1530919 TCP     {Contents=[..40..] Payload=[] SrcPort=55650 DstPort=8080(http-alt) Seq=3821768027 Ack=0 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=fal        se URG=false ECE=false CWR=false NS=false Window=64860 Checksum=5770 Urgent=0 Options=[..5..] Padding=[]}
1530920 CPU 02: MARK 0x94bed542 FROM 1825 to-overlay: 74 bytes (74 captured), state unknown, interface cilium_vxlan, , identity 45118->unknown, orig-ip 0.0.0.0
1530921 CPU 02: MARK 0x94bed542 FROM 0 DEBUG: Conntrack lookup 1/2: src=10.0.1.171:55650 dst=10.0.0.177:8080
1530922 CPU 02: MARK 0x94bed542 FROM 0 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
1530923 CPU 02: MARK 0x94bed542 FROM 0 DEBUG: CT verdict: New, revnat=0
1530924 CPU 02: MARK 0x94bed542 FROM 0 DEBUG: Conntrack create: proxy-port=0 revnat=0 src-identity=0 lb=0.0.0.0
1530925 CPU 02: MARK 0x94bed542 FROM 1825 DEBUG: Conntrack lookup 1/2: src=10.169.72.233:40044 dst=10.169.72.239:8472
1530926 CPU 02: MARK 0x94bed542 FROM 1825 DEBUG: Conntrack lookup 2/2: nexthdr=17 flags=1
1530927 CPU 02: MARK 0x94bed542 FROM 1825 DEBUG: CT verdict: New, revnat=0
1530928 CPU 02: MARK 0x94bed542 FROM 1825 DEBUG: Conntrack create: proxy-port=0 revnat=0 src-identity=0 lb=0.0.0.0
1530929 ------------------------------------------------------------------------------
1530930 Ethernet        {Contents=[..14..] Payload=[..110..] SrcMAC=00:50:56:86:3d:0c DstMAC=00:50:56:86:92:e7 EthernetType=IPv4 Length=0}
1530931 IPv4    {Contents=[..20..] Payload=[..90..] Version=4 IHL=5 TOS=0 Length=110 Id=56088 Flags= FragOffset=0 TTL=64 Protocol=UDP Checksum=63548 SrcIP=10.169.72        .233 DstIP=10.169.72.239 Options=[] Padding=[]}
1530932 UDP     {Contents=[..8..] Payload=[..82..] SrcPort=40044 DstPort=8472(otv) Length=90 Checksum=0}
1530933   Failed to decode layer: No decoder for layer type Payload
1530934 CPU 02: MARK 0x94bed542 FROM 1825 to-network: 124 bytes (124 captured), state unknown, orig-ip 0.0.0.0
```

**Comment by vincentmli** [comment]
> tested egress L7 proxy according to https://github.com/cilium/cilium-service-mesh-beta/tree/main/l7-traffic-management, it seems put VTEP redirection in `from-host` would support L7 proxy better than `to-netdev` according to the code path. I noticed when L7 proxy policy is deployed, test client pod curl request to remote pod, the client pod source ip `10.0.1.225` will be SNATed to cilium_host ip `10.0.1.171` before the tunnel encap, wonder why not preserve the client pod src ip even after L7 policy

In the case of sending traffic to VTEP device from the client pod, after L7 policy enforcement, before tunnel encap, the pod IP will be changed to IP on the network device has default route and has `to-netdev` attached, for example, tcpdump on VTEP device VXLAN interface:

```
# tcpdump -nn -i vxlan2

18:20:26.036260 IP 10.3.72.233.55664 > 10.1.1.6.8080: Flags [S], seq 132567225, win 64240, options [mss 1460,sackOK,TS val 1332488937 ecr 0,nop,wscale 7], length 0
```
`10.3.72.233` is IP on `ens224` that has default route, the source ip should have been either client pod IP or cilium_host interface IP, seems putting VTEP redirection in `from-host` in bpf_host makes more sense, but that requires route management in Cilium agent.

**Comment by vincentmli** [comment]
> > tested egress L7 proxy according to https://github.com/cilium/cilium-service-mesh-beta/tree/main/l7-traffic-management, it seems put VTEP redirection in `from-host` would support L7 proxy better than `to-netdev` according to the code path. I noticed when L7 proxy policy is deployed, test client pod curl request to remote pod, the client pod source ip `10.0.1.225` will be SNATed to cilium_host ip `10.0.1.171` before the tunnel encap, wonder why not preserve the client pod src ip even after L7 policy
> 
> In the case of sending traffic to VTEP device from the client pod, after L7 policy enforcement, before tunnel encap, the pod IP will be changed to IP on the network device has default route and has `to-netdev` attached, for example, tcpdump on VTEP device VXLAN interface:
> 
> ```
> # tcpdump -nn -i vxlan2
> 
> 18:20:26.036260 IP 10.3.72.233.55664 > 10.1.1.6.8080: Flags [S], seq 132567225, win 64240, options [mss 1460,sackOK,TS val 1332488937 ecr 0,nop,wscale 7], length 0
> ```
> 
> `10.3.72.233` is IP on `ens224` that has default route, the source ip should have been either client pod IP or cilium_host interface IP, seems putting VTEP redirection in `from-host` in bpf_host makes more sense, but that requires route management in Cilium agent.

I did a test by putting VTEP redirection in `from-host`,  it works exact like traffic to remote pod with L7 policy, pod IP changed to cilium_host interface IP, but curl to VTEP IP works

**Comment by vincentmli** [comment]
In summary

attach VTEP redirection in `to-netdev` 

Pros: 

1. no cilium agent route management required, users setup route

Cons:

1.  require `enable-bpf-masquerade: "true"`, only supported by kernel > `5.10` ?
2.  does not support endpoint with egress L7 policy when endpoint send request to VTEP, reason is endpoint IP is using IP on network device with default route and has `to-netdev` attached, not cilium_host IP or endpoint IP.

attach VTEP redirection in `from-host`

Pros:

1. does not require `enable-bpf-masquerade: "true"`
2. support endpoint with egress L7 policy when endpoint send request to VTEP

Cons:

1.  require Cilium agent to setup route to VTEP, easy to add VTEP route, tricky part is to remove old VTEP route at runtime ( can fall back to user manually remove old VTEP route with `kubectl exec -it <agent pod> -- ip route del <old vtep route>`)

**Comment by vincentmli** [comment]
> Cons:
> 
> 1. require Cilium agent to setup route to VTEP, easy to add VTEP route, tricky part is to remove old VTEP route at runtime ( can fall back to user manually remove old VTEP route with `kubectl exec -it <agent pod> -- ip route del <old vtep route>`)

this is also addressed now in https://github.com/cilium/cilium/pull/19473, so I  prefer the "from-host" PR than this one :)

**Comment by vincentmli** [comment]
based on my test above, VTEP redirection L7 policy in `to-netdev` is not supported  properly, close the PR

**Pull request closed without merging**
