### PR TITLE
Bump github.com/aws/aws-sdk-go-v2/service/ec2 to v1.13.0

### PR DESCRIPTION
**Pull request by ungureanuvladvictor**
Signed-off-by: Vlad Ungureanu <vladu@palantir.com>

```release-note
Bump github.com/aws/aws-sdk-go-v2/service/ec2 to v1.13.0
```

### CODE REVIEW

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Comment by ungureanuvladvictor** [comment]
test-1.19-5.4

**Comment by ungureanuvladvictor** [comment]
test-1.20-4.19

**Review by rolinh — APPROVED** [review]

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Pull request merged**
