### PR TITLE
v1.7 backports 2020-10-15

### PR DESCRIPTION
**Pull request by christarazi**
* #13532 -- bpf: only clean up XDP from devices with XDP attached (@jaffcheng)
   * Note: Needed to add 1afb536cd61b5a817c472f761979fd08e0611ae9 from https://github.com/cilium/cilium/pull/10910 as this PR depends on the aforementioned commit.
 * #13576 -- service: Use initNextID in acquireLocalID() (@hzhou8)
 * #13514 -- identity: Fix nil pointer panic in LookupIdentityByID (@gandro)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13532 13576 13514; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by tklauser** [comment]
Looks like bindata needs to be updated for `bpf/`:

```
[2020-10-16T07:30:14.342Z]     k8s1-1.17:   CHECK contrib/scripts/bindata.sh
[2020-10-16T07:30:14.342Z]     k8s1-1.17: ../contrib/scripts/bindata.sh 7908e40e990be4a6a2b99755863abd58630958ac
[2020-10-16T07:30:14.342Z]     k8s1-1.17: [91msha1sum: WARNING: 1 computed checksum did NOT match
[2020-10-16T07:30:14.342Z]     k8s1-1.17: [0mbindata.go: FAILED
[2020-10-16T07:30:14.342Z]     k8s1-1.17: ########################################################################
[2020-10-16T07:30:14.342Z]     k8s1-1.17: 
[2020-10-16T07:30:14.342Z]     k8s1-1.17:                   ERROR: bindata.go is out of date.
[2020-10-16T07:30:14.342Z]     k8s1-1.17: 
[2020-10-16T07:30:14.342Z]     k8s1-1.17:  This can happen for two reasons:
[2020-10-16T07:30:14.342Z]     k8s1-1.17:  1. You are using a go-bindata binary compiled with a different version
[2020-10-16T07:30:14.342Z]     k8s1-1.17:     of golang (not 1.13.15). If so, please up/downgrade.
[2020-10-16T07:30:14.342Z]     k8s1-1.17: 
[2020-10-16T07:30:14.342Z]     k8s1-1.17:  2. You have made changes to the bpf/ directory. Please run the
[2020-10-16T07:30:14.342Z]     k8s1-1.17:     following command to update the SHA in daemon/bpf.sha:
[2020-10-16T07:30:14.342Z]     k8s1-1.17: 
[2020-10-16T07:30:14.342Z]     k8s1-1.17:     $ make -C daemon apply-bindata
[2020-10-16T07:30:14.342Z]     k8s1-1.17: 
[2020-10-16T07:30:14.342Z]     k8s1-1.17: ########################################################################
[2020-10-16T07:30:14.342Z]     k8s1-1.17: Makefile:53: recipe for target 'check-bindata' failed
```

**Comment by christarazi** [comment]
test-backport-1.7

**Review by gandro — APPROVED** [review]
LGTM for my commit!

**Comment by christarazi** [comment]
test-backport-1.7

**Review by pchaigno — APPROVED** [review]
I reviewed the first two commits (concerning the datapath) and they look good to me!

**Review by aanm — APPROVED** [review]

**Pull request merged**
