### PR TITLE
Fix http gsg app yaml and delete old app yaml files

### LINKED ISSUE #3928: Minikube getting started guide app yaml doesn't work with K8s 1.8.0
### General Information

Issue is unrelated to Cilium. 
### How to reproduce the issue

1. minikube start --network-plugin=cni --memory=4096 --kubernetes-version v1.8.0
2. kubectl create -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/minikube/http-sw-app.yaml
```
Error from server (AlreadyExists): error when creating "https://raw.githubusercontent.com/cilium/cilium/doc-1.0/examples/minikube/http-sw-app.yaml": services "deathstar" already exists
Error from server (BadRequest): error when creating "https://raw.githubusercontent.com/cilium/cilium/doc-1.0/examples/minikube/http-sw-app.yaml": Deployment in version "v1" cannot be handled as a Deployment: no kind "Deployment" is registered for version "apps/v1"
Error from server (BadRequest): error when creating "https://raw.githubusercontent.com/cilium/cilium/doc-1.0/examples/minikube/http-sw-app.yaml": Deployment in version "v1" cannot be handled as a Deployment: no kind "Deployment" is registered for version "apps/v1"
Error from server (BadRequest): error when creating "https://raw.githubusercontent.com/cilium/cilium/doc-1.0/examples/minikube/http-sw-app.yaml": Deployment in version "v1" cannot be handled as a Deployment: no kind "Deployment" is registered for version "apps/v1"
```

### PR DESCRIPTION
**Pull request by ackerman80**
**Summary of changes**:
- fixed the api version spec for Deployment object in the app yaml. This is for backward compatibility with K8s version before 1.9
- removed the old demo app files (demo.yaml and policy files)

Fixes: [3928](https://github.com/cilium/cilium/issues/3928)

**How to test (optional)**:
create minikube with version 1.8 
create the app using the yaml. all pods and svcs should get created without errors

create minikube with version 1.9
create the app using the yaml. all pods and svcs should get created without errors

Signed-off-by: Arvind Soni <arvindsoni@gmail.com>

### CODE REVIEW

**Comment by ackerman80** [comment]
test-me-please

**Comment by ackerman80** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
Can you please rebase and remove commit `c0d7351ecf90e409c4b9d284bbe25a87a168a0ee` ? We do not want merge commits in our Git history.

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Review by aanm — APPROVED** [review]

**Comment by eloycoto** [comment]
test-me-please

**Review by raybejjani — DISMISSED** [review]
I second Ian’s request to rebase the merge out (although our rebase merge button might do that for us, it’s good practice to not rely on it). I also would prefer if we squashed this PR to two commits:
- Update minikube demo spec to use Kind: extensions/v1beta
- Remove unused minikube demo spec files

Both should have some more content in the body of the commit message, in particular the Kind: extensions/v1beta commit. The reasoning behind it isn’t clear and won’t be to someone reading this later (specifically, when would we switch back to apps/v1?)

**Comment by ianvernon** [comment]
@ackerman80 we do not want merge commits in the Cilium commit history; please rebase from latest master to remove the merge commit: https://github.com/cilium/cilium/pull/3929/commits/c309d1703d8d3b4d647b5712901cc64f9a81b5a7 

Clicking on the 'update branch' button when GitHub notifies you saying 'this branch is out-of-date with the base branch' causes this merge commit to appear. If you want to get your branch up-to-date with latest master, please rebase locally.

**Comment by ackerman80** [comment]
ok now it only has two commit messages. @ianvernon let me know if this is all set to merge

**Comment by eloycoto** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
SIgh, looks like the Jenkins trigger isn't working... I'm going to merge because these files aren't tested in the CI currently.

**Pull request merged**
