### PR TITLE
Add "cilium identity list" output to bugtool

### PR DESCRIPTION
**Pull request by stevenceuppens**
Fixes: #4236
Signed-Off-By: Steven Ceuppens <steven.ceuppens@icloud.com>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by stevenceuppens** [comment]
@joestringer is this the change you expected?

When running cilium-bugtool, a new file "cilium-identity-list.md" will be created in the dump

$ cat cilium-bugtool-20180524-140632.584+0000-UTC-899593867/cmd/cilium-identity-list.md 

# cilium identity list

```
ID   LABELS
1    reserved:host
2    reserved:world
4    reserved:health
3    reserved:cluster
5    reserved:init

```

**Review by ianvernon — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
Looks good, thanks Steven!

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
