### PR TITLE
v1.10 Backports 2023-01-27

### PR DESCRIPTION
**Pull request by qmonnet**
* [x] #22620 (@NikAleksandrov)
   * Minor conflict due to docs reorganisation
 * [x] #22654 (@bimmlerd)
 * [x] #22619 (@aspsk)
 * [x] #23095 (@joestringer)
 * [x] #23134 (@xmulligan)
   * Minor conflict due to docs reorganisation
 * [x] #23158 (@pchaigno)
 * [x] #23406 (@aanm)
   * Minor conflict due to Dependabot having updated an image digest on v1.10.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 22620 22654 22619 23095 23134 23158 23406; do contrib/backporting/set-labels.py $pr done 1.10; done
```
or with
```
$ make add-label BRANCH=v1.10 ISSUES=22620,22726,22654,22619,23095,23134,23158,23406
```

Left aside:

* #20350 - Conflicts due to source file missing. I think this is because https://github.com/cilium/cilium/pull/20350 has not been marked for backports to v1.10 (see for example https://github.com/cilium/cilium/pull/23097). Cc @tommyp1ckles

### CODE REVIEW

**Review by aanm — APPROVED** [review]
Thanks. The digest is fine since dependanbot will update to the right one anyways.

**Review by aanm — APPROVED** [review]

**Comment by qmonnet** [comment]
/test-backport-1.10

**Comment by joestringer** [comment]
> https://github.com/cilium/cilium/pull/23095 -- docs: Improve wording for deny policies limitation (@joestringer)

I don't see the commits for this in the PR.

**Review by christarazi — APPROVED** [review]
:+1: for my commits, thanks for the backporter's notes on the commits. Make it very easy to understand the subtle changes!

**Review by bimmlerd — APPROVED** [review]
https://github.com/cilium/cilium/pull/22654 LGTM

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Comment by qmonnet** [comment]
> > #23095 -- docs: Improve wording for deny policies limitation (@joestringer)
> 
> I don't see the commits for this in the PR.

Yikes! Not sure what happened to that commit. It's now fixed, and I double-checked that all other commits from advertised PRs are present :/.

**Comment by qmonnet** [comment]
/test-backport-1.10

**Comment by qmonnet** [comment]
- k8s-1.16-kernel-netnext timed out, for no obvious reason (to me).
- k8s-1.21-kernel-4.9 hit https://github.com/cilium/cilium/issues/15455

**Comment by qmonnet** [comment]
/test-1.16-netnext

**Comment by qmonnet** [comment]
/test-1.21-4.9

**Comment by tommyp1ckles** [comment]
@qmonnet I discussed this with @aanm - we're not backporting these to v1.10.

**Review by tommyp1ckles — APPROVED** [review]

**Comment by qmonnet** [comment]
/test-1.16-netnext

**Review by aspsk — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.16-netnext

**Review by joestringer — APPROVED** [review]

**Review by NikAleksandrov — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.16-netnext

**Comment by pchaigno** [comment]
/test-1.16-netnext

**Comment by pchaigno** [comment]
@christarazi The k8s-1.16-kernel-netnext CI job failed at least 3 times on the 170 minutes timeout for ginkgo. It's not failing on the v1.10 branch or on the master branch, where we have the same timeout. Looking at the PRs being backported here, the only susceptible to increase the runtime is https://github.com/cilium/cilium/pull/22726. I can bump the timeout but I'm wondering (1) if you have any idea why it might increase runtime and (2) if it's really worth backporting to v1.10.

**Comment by christarazi** [comment]
@pchaigno Ok, let's remove it then.

**Comment by pchaigno** [comment]
/test-backport-1.10

**Comment by pchaigno** [comment]
/test-1.21-4.9

**Pull request merged**
