### PR TITLE
v1.14 Backports 2024-02-27

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
* [ ] #30677 (@tklauser)
 * [ ] #30859 (@tklauser)
 * [ ] #30170 (@oblazek)
 * [x] #30868 (@YutaroHayakawa)
 * [ ] #30970 (@iandrewt)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30677 30859 30170 30868 30970
```

### CODE REVIEW

**Comment by YutaroHayakawa** [comment]
/test-backport-1.14

**Review by oblazek — APPROVED** [review]
LGTM. Thanks.

**Comment by YutaroHayakawa** [comment]
[Cilium IPsec upgrade](https://github.com/cilium/cilium/actions/runs/8091442384): https://github.com/cilium/cilium/issues/29846
[Conformance Cluster Mesh](https://github.com/cilium/cilium/actions/runs/8091441778): https://github.com/cilium/cilium/issues/30139
[Conformance E2E](https://github.com/cilium/cilium/actions/runs/8091441820): https://github.com/cilium/cilium/issues/30901

Might be a regression. Checking...
[Conformance Runtime](https://github.com/cilium/cilium/actions/runs/8091442119): https://github.com/cilium/cilium/issues/31057
[Integration Tests](https://github.com/cilium/cilium/actions/runs/8091442154): https://github.com/cilium/cilium/issues/31057
[Travis CI](https://app.travis-ci.com/github/cilium/cilium/builds/269138575)

**Comment by YutaroHayakawa** [comment]
/test-backport-1.14

**Review by ldelossa — APPROVED** [review]

**Pull request merged**
