### PR TITLE
go.mod, vendor: update cloud provider SDK Go modules

### PR DESCRIPTION
**Pull request by tklauser**
Monthly update of the cloud provider SDK Go modules using
`contrib/scripts/go-mod-update-cloud-providers.sh`

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by christarazi** [comment]
Nice, didn't know we had this script. :rocket:

**Comment by tklauser** [comment]
AKS workflow is currently broken on `master`, all other workflows passed. Marking as ready to merge.

**Pull request merged**
