### PR TITLE
update images 1.12

### PR DESCRIPTION
**Pull request by nebril**

### CODE REVIEW

**Comment by nebril** [comment]
/test-backport-1.12

**Review by jrajahalme — APPROVED** [review]

**Comment by nebril** [comment]
/test-1.19-4.9

**Comment by nebril** [comment]
test-1.19-4.9

**Comment by nebril** [comment]
1.19-4.9 tests failed due to GH api rate limiting

**Comment by nebril** [comment]
1.21 and 1.16 tests failed because of etcd server timeouts, marking as ready to merge

**Pull request merged**
