### PR TITLE
Backport v1.5 2019 05 08

### PR DESCRIPTION
**Pull request by raybejjani**
* PR: 7625 -- ipcache: print tunnel endpoint for RemoteEndpointInfo (@aanm) -- https://github.com/cilium/cilium/pull/7625
 * PR: 7929 -- Fix bug where Cilium would refuse to start if ipv6 netfilter modules are unavailable (@joestringer) -- https://github.com/cilium/cilium/pull/7929
 * PR: 7932 -- daemon: Use all labels to restore endpoint identity (@joestringer) -- https://github.com/cilium/cilium/pull/7932
 * PR: 7935 -- test/provision: update k8s testing versions to v1.11.10 and v1.12.8 (@aanm) -- https://github.com/cilium/cilium/pull/7935
 * PR: 7952 -- cilium/cmd: dump bpf lb list if map exists (@aanm) -- https://github.com/cilium/cilium/pull/7952
 * PR: 7950 -- Improve configmap documentation (@joestringer) -- https://github.com/cilium/cilium/pull/7950

 * PR: 7951 -- Typo in encryption algorithm: GMC -> GCM (@jimmyjones2) -- https://github.com/cilium/cilium/pull/7951
This was merged directly into 1.5 so I did nothing with it.

 * PR: 7708 -- don't allocate any memory when iterating over BPF maps (@aanm) -- https://github.com/cilium/cilium/pull/7708
@aanm This was non-trivial to merge, and I made things up, so you probably should look at it (or do the backport yourself in this branch, if that's simpler).

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7960)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-docs-please

**Comment by raybejjani** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-missed-k8s

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-docs-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by ianvernon** [comment]
K8s tests failed due to VXLAN encapsulation + encryption test failing: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2001/execution/node/60/log/?consoleFull this is a known issue that occurs intermittently, and is unrelated to the backports in this PR.

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by raybejjani** [comment]
Well, these finally passed normal tests. Only 1 commit here is directly relevant to k8s, but it changes the patch versions used in testing. It would be nice if those tests passed but I expect no problems, so it might be fine to merge if they fail again.

I'll merge this EU morning unless someone else does it sooner (cc @jrajahalme @ianvernon @tgraf  since you might be around/interested)

**Pull request merged**
