### PR TITLE
v1.4 backports 2019-03-05

### PR DESCRIPTION
**Pull request by brb**
v1.4 backports 2019-03-05

## Included

 * #7246 -- Protect remaining local keys from kvstore delete events (@tgraf)
 * #7265 -- api: Return 500 "Internal Error" when API handlers panic (@joestringer)
 * #7249 -- daemon: Remove old health EP state dirs in restore (@joestringer)
 * #7181 -- cilium: populate wildcard src->dst policy for transparent encryption (@jrfastab)

## Dropped

 * #7258 -- contrib: `$a` corrupted patch in cherry-pick (@nebril)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 7246 7265 7249 7181; do contrib/backporting/set-labels.py $pr done 1.4; done
```

---

@joestringer There was a merge conflict for #7249. Please check whether I haven't missed anything.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7285)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
`runtime.RuntimeFQDNPolicies CNAME follow`

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Hit `runtime.RuntimeFQDNPolicies Implements matchPattern: "*"`:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10458/testReport/junit/(root)/runtime/RuntimeFQDNPolicies_Implements_matchPattern_____/

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-docs-please

**Comment by joestringer** [comment]
test-missed-k8s

**Pull request merged**
