### PR TITLE
[v1.14] ci-ipsec-upgrade: Disable Linux 5.10-based configs

### PR DESCRIPTION
**Pull request by brb**
As reported in \[1\], the node-to-node-encryption tests are failing. It expects ICMP packets to be not encrypted.

Disable the config until we have resolved the issue.

\[1\]: https://github.com/cilium/cilium/issues/29351

Reported-by: Marcel Zieba <marcel.zieba@isovalent.com>

### CODE REVIEW

**Review by marseel — APPROVED** [review]

**Comment by marseel** [comment]
Thanks!

**Review by nbusseneau — APPROVED** [review]

**Comment by marseel** [comment]
LGTM

But looking at recent runs after matrix updates:
https://github.com/cilium/cilium/actions/runs/7014845611
https://github.com/cilium/cilium/actions/runs/7018446333
seems like `(bpf-next, patch)` is also failing :thinking:

**Review by nbusseneau — APPROVED** [review]

**Comment by qmonnet** [comment]
I fixed the PR (the workflow was still running on 5.10 because I had forgotten to remove it from `matrix.config`.

I'll look into bpf-next too, we can disable it as well if necessary (follow-up?).

**Review by marseel — APPROVED** [review]

**Pull request merged**
