### PR TITLE
vagrant: Update 4.9 and 5.4 VM images

### PR DESCRIPTION
**Pull request by pchaigno**
Yutaro reported an agent startup failure in the 4.9 dev. VM image, due to a regression in bpftool feature probes. The regression was introduced upstream in commit [1] and later fixed in [2]. The new images should have the latest bpftool, with the fix.

1 - https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e32660ac6fd6
2 - https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=878d8def0603
Reported-by: Yutaro Hayakawa <yhayakawa3720@gmail.com>

### CODE REVIEW

**Comment by pchaigno** [comment]
test-1.21-5.4

**Comment by pchaigno** [comment]
test-1.22-4.19

**Comment by pchaigno** [comment]
test-1.16-4.9

**Review by kkourt — APPROVED** [review]

**Comment by pchaigno** [comment]
test-1.16-4.9

**Comment by pchaigno** [comment]
test-1.21-5.4

**Review by ldelossa — APPROVED** [review]

**Review by YutaroHayakawa — APPROVED** [review]

**Review by sayboras — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by pchaigno** [comment]
Only the 4.9 and 5.4 CI jobs are affected and they are passing. Marking ready to merge.

**Comment by nbusseneau** [comment]
I want to check if this the CI issue we're currently dealing this (see [here](https://cilium.slack.com/archives/C7PE7V806/p1642088325020900)), please merge :shipit:

**Pull request merged**
