### PR TITLE
v1.14 Backports 2024-03-06

### PR DESCRIPTION
**Pull request by giorio94**
* [x] #30928 (@giorio94)
 * [x] #30916 (@giorio94)
    - :information_source: Skipped the renovate-related commit, as not relevant in stable branches.
 * [x]  #31198 (@giorio94)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30928 30916 31198
```

### CODE REVIEW

**Comment by giorio94** [comment]
/test-backport-1.14

**Comment by giorio94** [comment]
Need to backport https://github.com/cilium/cilium/pull/31198 as well to make sure that we use the variables from the target branch also in `pull_request/push` workflows.

**Comment by giorio94** [comment]
/test-backport-1.14

**Comment by giorio94** [comment]
Conformance K8s Kind and Conformance K8s Upstream Network failures are expected, because they use the set-env-variables checked out from the target branch, which doesn't contain the additional variables. This will be fixed after merging this PR.

**Review by jrajahalme — APPROVED** [review]

**Comment by jrajahalme** [comment]
@giorio94 Looks like the version number is missing from this (executed) line in conformance k8s kind:
```
  curl -L https://dl.k8s.io//kubernetes-test-linux-amd64.tar.gz -o ${TMP_DIR}/kubernetes-test-linux-amd64.tar.gz
```

Hence tar is complaining that its stdin is not gzip.

**Review by aanm — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Review by markpash — APPROVED** [review]

**Review by marseel — APPROVED** [review]

**Comment by giorio94** [comment]
Releases are out, unblocking.

**Pull request merged**
