### PR TITLE
Vagrantfiles: update developer, CI VM version to 128

### LINKED ISSUE #6638: cache latest Istio images in Ginkgo VMs

### PR DESCRIPTION
**Pull request by ianvernon**
Changes from the prior VM version include:

* Include kTLS support in packer builds
* Pull Spotify Kafka proxy image
* Fix golang envtpl installation
* install python3-sphinx and add ~/.local/bin to PATH
* Pull FQDN images
* Pull Istio images
* Allow to specify packer binary name
* fix permissions for packages installed via pip3

Fixes: #6638

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7004)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9729/execution/node/7/log/

Connectivity from Jenkins to GitHub appears to have gone wonky :)

**Comment by ianvernon** [comment]
test-me-please

**Comment by eloycoto** [comment]
Ohh, I though that we already made this one. Thanks!

**Review by eloycoto — APPROVED** [review]

**Comment by ianvernon** [comment]
Build failed: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9730

Looks like we may have removed `yamllint` from the VM?
```
bash: yamllint: command not found
```

**Comment by ianvernon** [comment]
Appears that this commit broke the yamllint / policy validator test: https://github.com/cilium/packer-ci-build/pull/106/files#diff-311d278f7a5b45efe4ddf8ed67e10081R75

**Comment by ianvernon** [comment]
Fix out for `yamllint` not being accessible as vagrant user: https://github.com/cilium/packer-ci-build/pull/111

We will have to build a newer version of the VM so that the Cilium CI can consume it.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
A bunch of Vagrant errors in most recent build: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9894/

No idea regarding these... trying again to see if this is a persistent problem.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Superseded by 
https://github.com/cilium/cilium/pull/7096

**Pull request closed without merging**
