### PR TITLE
Final 1.5.2 backports

### PR DESCRIPTION
**Pull request by tgraf**
* PR: 8151 -- bugtool: improve lb dump support and add monitor helper for k8s tests (@borkmann) -- https://github.com/cilium/cilium/pull/8151
 * PR: 8152 -- pkg/labels: ignore all labels that match the regex "annotation.*" (@aanm) -- https://github.com/cilium/cilium/pull/8152
 * PR: 8158 -- docs: Update upgrade instructions for v1.5 -> v1.4 -> v1.5 case (@brb) -- https://github.com/cilium/cilium/pull/8158
 * PR: 8171 -- operator: Fix health check API (@tgraf) -- https://github.com/cilium/cilium/pull/8171
 * PR: 8173 -- doc: Add EKS node-init DaemonSet to mount BPF filesystem (@tgraf) -- https://github.com/cilium/cilium/pull/8173
 * PR: 8190 -- pkg/kvstore: perform update if value or lease are different (@aanm) -- https://github.com/cilium/cilium/pull/8190
 * PR: 8192 -- ipcache: Fix automatic recovery of deleted ipcache entries (@tgraf) -- https://github.com/cilium/cilium/pull/8192
 * PR: 7938 -- kvstore: Wait for kvstore to reach quorum (@tgraf) -- https://github.com/cilium/cilium/pull/7938
 * PR: 8085 -- pkg/kvstore: acquire a random initlock (@aanm) -- https://github.com/cilium/cilium/pull/8085
 * PR: 8114 -- Add kvstore quorum check to Cilium precheck (@nebril) -- https://github.com/cilium/cilium/pull/8114

When you have backported the above commits, you can update the PR labels via this command:
```
$ for pr in 7710 8151 8152 8158 8171 8173 8190; do contrib/backporting/set-labels.py $pr pending 1.5; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8193)

### CODE REVIEW

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Review by borkmann — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by brb — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
K8s tests failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2111

Direct Routing tests failed for both K8s versions:

```
15:02:24  K8sDatapathConfig DirectRouting 
15:02:24    Check connectivity with automatic direct nodes routes
15:02:24    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
15:03:08  STEP: Performing Cilium preflight check
15:03:08  STEP: Waiting for all etcd-operator pods are ready
15:03:08  STEP: Making sure all endpoints are in ready state
15:03:09  STEP: Checking pod connectivity between nodes
15:03:14  === Test Finished at 2019-06-03T15:03:14Z====
```

```
16:29:23  • [SLOW TEST:4974.097 seconds]
16:29:23  K8sDatapathConfig
16:29:23  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:378
16:29:23    DirectRouting
16:29:23    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:378
16:29:23      Check connectivity with automatic direct nodes routes
16:29:23      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
16:29:23  ------------------------------
16:29:23  K8sDatapathConfig Transparent encryption DirectRouting 
16:29:23    Check connectivity with automatic direct nodes routes
16:29:23    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
16:29:23  ===================== TEST FAILED =====================
16:29:23  cmd: kubectl get pods -o wide --all-namespaces
16:29:23  Exitcode: 1 
16:29:23  Stdout:
16:29:23   	 
16:29:23  Stderr:
16:29:23   	 
16:29:23  
16:29:23  ===================== Exiting AfterFailed =====================
16:29:30  After 20s process did not stop
```

**Comment by ianvernon** [comment]
Normal Ginkgo tests failed due to VXLAN + Encryption test which is likely due to kernel bugs: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12759/execution/node/136/log/

I will file a PR to ensure that we don't run this test when not running with newer kernels in v1.5, as it's just adding useless noise to our CI runs for v1.5.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Preflight check got stuck again: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12763/

**Comment by ianvernon** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
Failure : https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12773/

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2123/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-docs-please

**Pull request merged**
