### PR TITLE
Test: Add Kuberentes 1.14-beta.1 to the build system.

### PR DESCRIPTION
**Pull request by eloycoto**
According to CI meeting: 

- Drop support to 1.8 and 1.9 releases. 
- Test with 1.14 version in all. 
- Default 1.10 as minimal version. 

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6984)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-missed-k8s

**Review by aanm — APPROVED** [review]
Thanks for doing this, don't waste much time on it, usually alpha versions are painful to setup.

**Comment by ianvernon** [comment]
I don't think this should be part of the K8s test setup jut yet because alpha still means there could still be issues that we are not in control of that affect the stability of the job and will introduce noise into the CI.

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Review by aanm — CHANGES_REQUESTED** [review]
Couple things:

1) add this file https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.14/cluster/addons/dns/coredns/coredns.yaml.base to `test/provision/manifest/1.14`

2) Remove from the documentation 1.8 and 1.9 as we no longer support it.

3) on `test/helpers/utils.go` line 376

```
	case CiliumV1_5.Check(cst):
		return versioncheck.MustCompile(">= 1.10, <1.15"), nil
```

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Review by aanm — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
Build failure in regular Cilium-Ginkgo-Tests job: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10580/testReport/junit/k8s-1/10/K8sDatapathConfig_IPv4Only_Check_connectivity_with_IPv6_disabled/

Build failure in Cilium-Ginkgo-Test-k8s job: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1771/testReport/junit/k8s-1/14/BDD_Test_k8s_1_14___K8sServicesTest_Bookinfo_Demo_Tests_bookinfo_demo/

This appears legitimate - looks like DNS was not able to resolve for one of the services. May be related to core-dns configuration for K8s 1.14.

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
Mark as wip due is a error in core-dns with 1.14

**Comment by eloycoto** [comment]
Issue:

```
STEP: Checking that "productpage-v1-5966d4b955-dpgk6" can connect to "ratings.default.svc.cluster.local:9080/health"
time="2019-03-08T09:39:46Z" level=debug msg="running command: kubectl exec -n default productpage-v1-5966d4b955-dpgk6 -- wget --tries=2 --connect-timeout 5 ratings.default.svc.cluster.local:9080/health"
cmd: "kubectl exec -n default productpage-v1-5966d4b955-dpgk6 -- wget --tries=2 --connect-timeout 5 ratings.default.svc.cluster.local:9080/health" exitCode: 4 duration: 176.345325ms stdout:

stderr:
--2019-03-08 09:39:46--  http://ratings.default.svc.cluster.local:9080/health
Resolving ratings.default.svc.cluster.local (ratings.default.svc.cluster.local)... failed: Name or service not known.
wget: unable to resolve host address ‘ratings.default.svc.cluster.local’
command terminated with exit code 4
```

The issue does not look related to coredns, due it works before without issues:

```
time="2019-03-08T09:39:45Z" level=debug msg="running command: dig +short ratings.default.svc.cluster.local @10.96.0.10 | grep -v -e '^;'"
cmd: "dig +short ratings.default.svc.cluster.local @10.96.0.10 | grep -v -e '^;'" exitCode: 0 duration: 10.470353ms stdout:
10.111.217.56
```


And from other pods:

```
STEP: Checking that "reviews-v1-94dff74b6-9l4v2" can connect to "ratings.default.svc.cluster.local:9080/health"
time="2019-03-08T09:39:45Z" level=debug msg="running command: kubectl exec -n default reviews-v1-94dff74b6-9l4v2 -- wget --tries=2 --connect-timeout 5 ratings.default.svc.cluster.local:9080/health"
cmd: "kubectl exec -n default reviews-v1-94dff74b6-9l4v2 -- wget --tries=2 --connect-timeout 5 ratings.default.svc.cluster.local:9080/health" exitCode: 0 duration: 240.837696ms stdout:

stderr:
--2019-03-08 09:39:45--  http://ratings.default.svc.cluster.local:9080/health
Resolving ratings.default.svc.cluster.local (ratings.default.svc.cluster.local)... 10.111.217.56
Connecting to ratings.default.svc.cluster.local (ratings.default.svc.cluster.local)|10.111.217.56|:9080... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: 'health'

     0K                                                         621K=0s

2019-03-08 09:39:45 (621 KB/s) - 'health' saved [31]


STEP: Checking that "reviews-v1-94dff74b6-9l4v2" can connect to "ratings.default.svc.cluster.local:9080/ratings/0"
time="2019-03-08T09:39:46Z" level=debug msg="running command: kubectl exec -n default reviews-v1-94dff74b6-9l4v2 -- wget --tries=2 --connect-timeout 5 ratings.default.svc.cluster.local:9080/ratings/0"
cmd: "kubectl exec -n default reviews-v1-94dff74b6-9l4v2 -- wget --tries=2 --connect-timeout 5 ratings.default.svc.cluster.local:9080/ratings/0" exitCode: 0 duration: 207.191712ms stdout:

stderr:
--2019-03-08 09:39:46--  http://ratings.default.svc.cluster.local:9080/ratings/0
Resolving ratings.default.svc.cluster.local (ratings.default.svc.cluster.local)... 10.111.217.56
Connecting to ratings.default.svc.cluster.local (ratings.default.svc.cluster.local)|10.111.217.56|:9080... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: '0'

     0K                                                        7.44M=0s

2019-03-08 09:39:46 (7.44 MB/s) - '0' saved [48]
```


The produdctPage does not have any policy, so the connection should happens without issues:

```
	 800        Disabled           Disabled          11846      k8s:app=productpage                               f00d::a0a:100:0:f5ad   10.10.1.166   ready
	                                                            k8s:io.cilium.k8s.policy.cluster=default
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default
	                                                            k8s:io.kubernetes.pod.namespace=default
	                                                            k8s:track=stable
	                                                            k8s:version=v1
	                                                            k8s:zgroup=bookinfo
```


Also, the log record in coredns is in place, so all should work without issues:

```
2019-03-08T09:39:46.796981651Z 2019-03-08T09:39:46.796Z [INFO] 10.10.1.166:55510 - 14609 "AAAA IN ratings.default.svc.cluster.local.default.svc.cluster.local. udp 77 false 512" NXDOMAIN qr,rd 170 0.000106876s
2019-03-08T09:39:46.797332185Z 2019-03-08T09:39:46.797Z [INFO] 10.10.1.166:55510 - 24572 "A IN ratings.default.svc.cluster.local.default.svc.cluster.local. udp 77 false 512" NXDOMAIN qr,rd 170 0.000364786s
2019-03-08T09:39:46.799847572Z 2019-03-08T09:39:46.799Z [INFO] 10.10.1.166:40928 - 44960 "AAAA IN ratings.default.svc.cluster.local.svc.cluster.local. udp 69 false 512" NXDOMAIN qr,rd 162 0.000118789s
2019-03-08T09:39:46.799910483Z 2019-03-08T09:39:46.799Z [INFO] 10.10.1.166:40928 - 24403 "A IN ratings.default.svc.cluster.local.svc.cluster.local. udp 69 false 512" NXDOMAIN qr,rd 162 0.00022912s
2019-03-08T09:39:46.801957007Z 2019-03-08T09:39:46.801Z [INFO] 10.10.1.166:55272 - 34180 "AAAA IN ratings.default.svc.cluster.local.cluster.local. udp 65 false 512" NXDOMAIN qr,rd 158 0.000102181s
2019-03-08T09:39:46.802041302Z 2019-03-08T09:39:46.802Z [INFO] 10.10.1.166:55272 - 8973 "A IN ratings.default.svc.cluster.local.cluster.local. udp 65 false 512" NXDOMAIN qr,rd 158 0.000223266s
2019-03-08T09:39:46.808292173Z 2019-03-08T09:39:46.808Z [INFO] 10.10.1.166:46494 - 43297 "AAAA IN ratings.default.svc.cluster.local. udp 51 false 512" NOERROR qr,rd 144 0.000112908s
2019-03-08T09:39:46.808396992Z 2019-03-08T09:39:46.808Z [INFO] 10.10.1.166:46494 - 37198 "A IN ratings.default.svc.cluster.local. udp 51 false 512" NOERROR qr,rd 100 0.000209785s
```

Checking more on dep this issue.

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please (FQDN issues) https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1799/#showFailuresLink

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s (FQDN restart)
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1802/testReport/k8s-1/11/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/

**Comment by eloycoto** [comment]
test-missed-k8s (https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1803/)

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-missed-k8s (https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1805/)

**Comment by eloycoto** [comment]
mi

**Comment by eloycoto** [comment]
test-missed-k8s

**Review by aanm — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
K8s tests failed again for 1.14: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1806/

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Review by aanm — APPROVED** [review]

**Pull request merged**
