### PR TITLE
daemon: Do not remove orphan svc-v2 during restore

### PR DESCRIPTION
**Pull request by brb**
Previously, the service restoration procedure could remove an orphan service v2 if no corresponding legacy service could have been found. This was to handle a case when a user downgraded from v1.5 to <v1.5, changed services and then upgraded back to >= 1.5.

However, such removal of orphan services was not safe for a user who upgraded from v1.5 to >= v1.5 and forgot to disable legacy services. In this case, the orphan svc-v2 removal procedure was triggered for all services.

---

In addition, I've included all commits from https://github.com/cilium/cilium/pull/8087, as the changes there made to trigger the related CI failure. Once we merge this commit, we can close #8087.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8135)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
Ci failed due to the git fetch timeout.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
CI failed due to:
```
[2019-05-28T19:48:32.713Z]     k8s1-1.10: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
@brb The upgrade/downgrade test failed. I assume this is related to bumping the stable image to 1.5. Given that the main motivation of this PR is to unblock 1.5.2, do you want to remove that commit and test 1.4 -> master instead of 1.5 -> master?

**Comment by brb** [comment]
@tgraf The test case failed because we did the upgrade from v1.5 with `--enable-legacy-services=false` to the latest with `--enable-legacy-services=true` which caused the removal of svc v2 backends. I've fixed the flag in the test manifests.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
I had a second thought on this PR.

The problem I was trying to solve with this PR is that if a user ran v1.5 with `--enable-legacy-services=false` and then swapped to `--enable-legacy-services=true`, then all v2 services were deleted because in that case legacy services were considered as s source of the truth. The swap could have happened because of one of the following reasons:
1. The user accidentally forgot to set the flag (default is `true`).
2. The user decided to downgrade to < v1.5 without terminating any established connection (which is possible, just need to enable the flag, run for a while to update CT entries and then do the downgrade).

However, we probably have quite a few users who downgraded to <1.5 due to the regressions. Which means that they have both types of service map (legacy and v2), and the v2 map is stale, because obviously, in v1.4 we do not manage the v2. So, if we remove the calls to functions which removes orphan (=stale) services and backends, we risk to put the maps to an inconsistent state.

**Comment by tgraf** [comment]
Discussed over lunch: We should document that legacy services need to stay enabled until a user decided that downgrade will not happen anymore. Otherwise, connection resets must be expected.

**Comment by brb** [comment]
Closing in favor of #8158.

**Pull request closed without merging**
