### PR TITLE
logging: fixed log-options/level interpretation

### LINKED ISSUE #16002: logging: level being passed as log-options is not interpreted
## Bug report

I spotted that we do not properly interpret the `level` of the `--log-options`, therefore we cannot really update the logging level. At first sight, I believe the culprit resides in here: https://github.com/cilium/cilium/blob/f740f55f313216f6cee35b5c69896811445a21a6/pkg/logging/logging.go#L296

This variable does not seem to be updated at any point.

I will work on a PR to sort this issue out and make the logging level interface easier to use.

**General Information**

- Cilium version: `v1.9.4` - though it probably impacts much lower versions too

**How to reproduce the issue**

- Attempt to start the agent with `--log-options='{"level":"error"}'`

### PR DESCRIPTION
**Pull request by mvisonneau**
Ensure that most components correctly interpret the
`--log-options={"level"="[level]"}` flag. Looking at where
**logging.SetupLogging()** is being called from, I would say:

- agent
- operator
- health
- cni

Fixes: #16002

```release-note
Fix an issue preventing the interpretation of the `--log-options={"level"="[level]"}` flag
```

### CODE REVIEW

**Comment by anfernee** [comment]
I would say only fix the bug without enhancing the interface if we want to backport it. This PR has some behavior change in terms of how level is parsed.

**Comment by ti-mo** [comment]
Hi @mvisonneau, I don't think we can backport this in its current state. Could you extract the refactor into a separate commit (and PR) and only leave the bugfix in this PR? Thank you!

**Comment by mvisonneau** [comment]
@anfernee, @ti-mo, sounds good, I have replaced this PR with a change which I believe will be easily "backportable" into former versions.

**Review by twpayne — APPROVED** [review]

**Review by borkmann — APPROVED** [review]

**Review by twpayne — APPROVED** [review]

**Comment by twpayne** [comment]
test-me-please

**Comment by twpayne** [comment]
ci-gke

**Comment by twpayne** [comment]
test-1.16-netnext

Flake is #16127

**Comment by twpayne** [comment]
test-1.19-5.4

**Comment by twpayne** [comment]
test-1.20-4.19

**Comment by twpayne** [comment]
test-1.21-4.9

**Comment by kaworu** [comment]
test-1.16-netnext

**Comment by aditighag** [comment]
@mvisonneau Could you rebase the PR against the master branch?

**Comment by mvisonneau** [comment]
I haven't looked into details but at first sight, I believe it has been superseded by https://github.com/cilium/cilium/pull/16021. I will test it and let you know if we can eventually close this PR.

**Comment by aditighag** [comment]
> I haven't looked into details but at first sight, I believe it has been superseded by #16021. I will test it and let you know if we can eventually close this PR.

Marking the PR as a draft in the meantime.

**Pull request closed without merging**
