### PR TITLE
Refactor /endpoint/{id}/labels for API 1.0 stability

### PR DESCRIPTION
**Pull request by raybejjani**
See https://github.com/cilium/cilium/issues/3280 for background

**Summary of changes**:
- Refactor the endpoint label config to be declarative.
- Refactor client to retain the CLI add/remove behaviour

**How to test (optional)**:
all tests should pass.

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
This has failed runtime tests consistently. I'll assume that I broke something with how labels are assigned. I'll debug.

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
