### PR TITLE
vagrant: Remove reference of libvirt to avoid confusion

### PR DESCRIPTION
**Pull request by sayboras**
As confirmed, dev vagrant box doesn't work with libvirt, hence it's
better to remove related reference to avoid confusion

Signed-off-by: Tam Mach <sayboras@yahoo.com>

## Testing

By default, vagrant will use virtualbox as mentioned [here](https://www.vagrantup.com/docs/providers/default)

> By default, VirtualBox is the default provider for Vagrant.

<details>
<summary>runtime</summary>

```shell script
vagrant@runtime1:~/go/src/github.com/cilium/cilium$ cilium status
KVStore:                 Ok         Consul: 172.17.0.3:8300
Kubernetes:              Disabled   
Cilium:                  Ok         OK
NodeMonitor:             Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok   
IPAM:                    IPv4: 2/65535 allocated from 10.11.0.0/16, IPv6: 2/4294967295 allocated from f00d::a0f:0:0:0/96
BandwidthManager:        Disabled
Host Routing:            Legacy
Masquerading:            IPTables
Controller Status:       18/18 healthy
Proxy Status:            OK, ip 10.11.72.4, 0 redirects active on ports 10000-20000
Hubble:                  Ok              Current/Max Flows: 547/4096 (13.35%), Flows/s: 36.67   Metrics: Disabled
Cluster health:          0/1 reachable   (2020-10-27T23:57:15Z)
  Name                   IP              Node        Endpoints
  runtime1 (localhost)   10.0.2.15       reachable   unreachable
```

```release-note
docs/vagrant: Remove reference of libvirt to avoid confusion
```

</details>

<details>
<summary>vagrant cluster</summary>

```shell script
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ cilium status
KVStore:                Ok   etcd: 1/1 connected, lease-ID=29c6756c811d5b52, lock lease-ID=29c6756c811d5b54, has-quorum=true: https://192.168.33.11:2379 - 3.4.13 (Leader)
Kubernetes:             Ok   1.19 (v1.19.2) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumLocalRedirectPolicy", "cilium/v2::CiliumNetworkPolicy", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Partial   
Cilium:                 Ok        OK
NodeMonitor:            Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 11/255 allocated from 10.11.0.0/24, IPv6: 11/65535 allocated from fd00::/112
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           IPTables
Controller Status:      82/82 healthy
Proxy Status:           OK, ip 10.11.0.253, 3 redirects active on ports 10000-20000
Hubble:                 Ok              Current/Max Flows: 4096/4096 (100.00%), Flows/s: 52.97   Metrics: Disabled
Cluster health:         2/2 reachable   (2020-10-28T00:11:32Z)
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ 
```

</details>

### CODE REVIEW

**Review by pchaigno — COMMENTED** [review]
Should we remove the [other references to `VAGRANT_DEFAULT_PROVIDER`](https://github.com/cilium/cilium/search?q=VAGRANT_DEFAULT_PROVIDER) from the source code?

**Comment by sayboras** [comment]
> Should we remove the [other references to `VAGRANT_DEFAULT_PROVIDER`](https://github.com/cilium/cilium/search?q=VAGRANT_DEFAULT_PROVIDER) from the source code?

Good point, thanks for highlighting this. I should keep in mind that easy change normally leads to easy miss :sweat:

**Comment by sayboras** [comment]
test-me-please

**Comment by sayboras** [comment]
1.12 failed due to below reason, I think it's unrelated to changes as similar failur for other run as well.

```
Expected command: kubectl exec -n kube-system log-gatherer-c5vrp -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 tftp://192.168.36.12:32613/hello -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 error: unable to upgrade connection: Authorization error (user=kube-apiserver-kubelet-client, verb=create, resource=nodes, subresource=proxy)
```

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
retest-net-next

**Review by christarazi — APPROVED** [review]

**Comment by aanm** [comment]
There's no need to backport this to older branches since it only affects developers.

**Pull request merged**
