### PR TITLE
helm: Added support for existing Cilium SPIRE NS

### PR DESCRIPTION
**Pull request by PhilipSchmid**
Added additional `existingNamespace` bool flag to configure if the SPIRE `namespace` already exists or not. If it's an existing one, we should not include our Cilium SPIRE namespace template as this causes the Helm installation to fail. Helm then complains about `Namespace "xxx" in namespace "" exists and cannot be imported into the current release`.

Please also backport this PR to 1.14.

Please ensure your pull request adheres to the following guidelines:

- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [X] Thanks for contributing!

```release-note
helm: Added support for existing Cilium SPIRE NS
```

### CODE REVIEW

**Review by nebril — APPROVED** [review]

**Review by meyskens — APPROVED** [review]
LGTM

**Review by tommyp1ckles — APPROVED** [review]

**Comment by meyskens** [comment]
You need to run `make -C Documentation update-helm-values` still :wink:

**Comment by PhilipSchmid** [comment]
@meyskens Thanks for the input! I just run it and amended the `Documentation/helm-values.rst` changes.

**Comment by meyskens** [comment]
@PhilipSchmid CI is failing on the Helm chart: https://github.com/cilium/cilium/actions/runs/7045839909/job/19176386249?pr=29032#step:3:79

**Comment by PhilipSchmid** [comment]
@meyskens Right, thanks, it failed because I forgot to re-run `make -C install/kubernetes` after I rebased it the last time 🤦‍♂️. 
🤞 that it now runs through.

**Comment by joestringer** [comment]
This one just missed the cutoff but all reviews are in + CI passed. It looks trivially correct so makes sense to get in before the first v1.15 RC.

**Comment by joestringer** [comment]
We typically wouldn't backport something like this since it's adding support for a new mode. IIRC external SPIRE was out of scope for v1.14, and it's also a beta feature. Dropping backport labels. This should be part of the next v1.15 release candidate.

**Pull request merged**
