### PR TITLE
Add missing kvstore-max-consecutive-quorum-errors option to clustermesh-apiserver/kvstoremesh binaries

### PR DESCRIPTION
**Pull request by giorio94**
Extend the clustermesh-apiserver/kvstoremesh configurations by adding the previously missed kvstore-max-consecutive-quorum-errors option to match the one already provided by the Cilium agents, as well as configure the same default value. While being there, let's also convert the flag to be of Uint type, to reflect the fact that negative values are not expected to be provided.

Fixes: 2911b44ace7b ("kvstore: add a cell for the kvstore client")

```release-note
Add missing kvstore-max-consecutive-quorum-errors option to clustermesh-apiserver/kvstoremesh binaries
```

### CODE REVIEW

**Review by marseel — CHANGES_REQUESTED** [review]
Can we switch it to uint here too?
https://github.com/cilium/cilium/blob/aa02b7457356fbccbeb09de7886e23a86e70db24/daemon/cmd/daemon_main.go#L475

I think it's reasonable to have the same type everywhere. Then we can have `KVstoreMaxConsecutiveQuorumErrors` in config as uint too.

**Comment by giorio94** [comment]
> Can we switch it to uint here too?
> 
> https://github.com/cilium/cilium/blob/aa02b7457356fbccbeb09de7886e23a86e70db24/daemon/cmd/daemon_main.go#L475
> 
> I think it's reasonable to have the same type everywhere. Then we can have `KVstoreMaxConsecutiveQuorumErrors` in config as uint too.

Yeah, makes sense. Updated. PTAL

**Review by marseel — APPROVED** [review]
looks good, thanks

**Review by nebril — APPROVED** [review]

**Comment by giorio94** [comment]
Fixed missing cmd-ref update, and rebased onto main.

**Comment by giorio94** [comment]
@asauber Gentle ping :pray:

**Comment by giorio94** [comment]
@asauber Gentle ping 🙏

**Review by michi-covalent — APPROVED** [review]
😇

**Review by asauber — APPROVED** [review]

**Pull request merged**
