### PR TITLE
Move common/colors.go into pkg/color

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4707)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]
Since we use this in so few places, would it be simpler to remove it outright?

**Review by ianvernon — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by aanm** [comment]
>Since we use this in so few places, would it be simpler to remove it outright?

Remove the colors from the CLI?!  :scream:

**Review by aanm — APPROVED** [review]

**Comment by raybejjani** [comment]
> Remove the colors from the CLI?! 😱

The alternative is to go all out, and use it everywhere!!!! (you could have green for the ready state, yellow for regenerating, orange for waiting-for-identity)... We can even stick the output into the CEPs so when you dump to console the yaml has colour :P

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
> The alternative is to go all out, and use it everywhere!!!!

I'm waiting for `pkg/emoji` to appear

**Pull request merged**
