### PR TITLE
fix warning log for list IPV6 address: move IPV4 to IPv6

### PR DESCRIPTION
**Pull request by lic17**
Signed-off-by: Li Cheng 1076366950@qq.com

### CODE REVIEW

**Comment by lic17** [comment]
Signed-off-by: Li Cheng <1076366950@qq.com>

**Review by lic17 — COMMENTED** [review]
Signed-off-by: Li Cheng 1076366950@qq.com

**Comment by jrfastab** [comment]
The commit list has a bit of noise. Can you please rebase on top of latest code branch so it just shows up as a single commit. Otherwise the patch itself is good.

**Comment by jrfastab** [comment]
The commit list has a bit of noise. Can you please rebase on top of latest code branch so it just shows up as a single commit. Otherwise the patch itself is good.

**Comment by lic17** [comment]
> The commit list has a bit of noise. Can you please rebase on top of latest code branch so it just shows up as a single commit. Otherwise the patch itself is good.

thank,I create a new PR with the single commit to fix [16475](this.https://github.com/cilium/cilium/pull/16475)

**Comment by jrfastab** [comment]
merged here thanks!

https://github.com/cilium/cilium/pull/16475

**Pull request closed without merging**
