### PR TITLE
vendor: Upgrade github.com/cilium/ebpf to v0.5.0

### PR DESCRIPTION
**Pull request by aditighag**
Release notes : https://github.com/cilium/ebpf/releases/tag/v0.5.0 supersedes  
Release notes: https://github.com/cilium/ebpf/releases/tag/v0.4.0 

Signed-off-by: Aditi Ghag <aditi@cilium.io>

### CODE REVIEW

**Comment by rolinh** [comment]
@aditighag The failure looks legit. Please run the following:
```
go mod tidy && go mod vendor && go mod verify
```

**Comment by aditighag** [comment]
> @aditighag The failure looks legit. Please run the following:
> 
> ```
> go mod tidy && go mod vendor && go mod verify
> ```

I had already run the first two. Let me see what the 3rd command does. Thanks!

**Comment by rolinh** [comment]
> I had already run the first two. Let me see what the 3rd command does. Thanks!

Make sure you use Go 1.16 as well.

**Comment by aditighag** [comment]
I missed committing some unversioned files after running `go mod tidy && go mod vendor`.

**Comment by aditighag** [comment]
There is a bug in the released version so I'll hold off on this PR for now. I'll follow up to see what the plan is for the bug fix.

**Comment by aditighag** [comment]
test-me-please

**Comment by aditighag** [comment]
I don't understand why go-mod check is failing - 

```
please run 'go mod tidy && go mod vendor', and submit your changes
Error: Process completed with exit code 1.
```

I've already run `go mod tidy && go mod vendor` locally before pushing the changes. There are no other changes in the README file that it is flagging.

**Comment by aditighag** [comment]
test-me-please

**Review by rolinh — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]

**Comment by aditighag** [comment]
test-1.16-netnext

**Comment by aditighag** [comment]
test-1.20-4.19

**Comment by pchaigno** [comment]
@aditighag What failed? Are there already issues for those flakes?

**Comment by aditighag** [comment]
I saw that these tests failed on other PRs, and they were flakes. My changes shouldn't cause any failures considering all but 2 tests have passed. Looks like both the tests passed on the retry.

**Comment by pchaigno** [comment]
> I saw that these tests failed on other PRs, and they were flakes.

If there weren't issues for those, would be good to create them.

**Pull request merged**
