### PR TITLE
v1.15: WG L7

### PR DESCRIPTION
**Pull request by brb**
Advanced test case passed - https://github.com/cilium/cilium/actions/runs/8248436777/job/22558759219

### CODE REVIEW

**Comment by brb** [comment]
/test-backport-1.15

**Comment by brb** [comment]
/test-backport-1.15

**Comment by ferozsalam** [comment]
/test-backport-1.15

**Comment by brb** [comment]
/test-backport-1.15

**Comment by brb** [comment]
/test-backport-1.15

**Comment by brb** [comment]
/test-backport-1.15

**Comment by brb** [comment]
/test-backport-1.15

**Review by gandro — APPROVED** [review]

**Review by gentoo-root — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
