### PR TITLE
Test: Do not log cilium logs in test-output.log

### LINKED ISSUE #4189: Split cilium log out from test-output.log
In local testing, I found that spinning up a simple test that runs Cilium, then `Expect(true).To(BeFalse())`, the `test-output.log` contained 4500 lines of cilium logs, and 200 lines of actual test output.

It would be great to split the cilium logs out and put them in a separate file so that the `test-output.log` can reflect exactly what's going on in the test. This can be cross-referenced against the logs separately.

### PR DESCRIPTION
**Pull request by eloycoto**
Fix #4189

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Review by joestringer — COMMENTED** [review]
Thanks for the PR, looks good to me. Will the logs still be available in a separate file somewhere, particularly in cases where the test fails in places like a `BeforeEach()`/`AfterEach()`? I wouldn't to introduce a regression in our ability to debug such situations.

**Comment by eloycoto** [comment]
@joestringer All the cilium logs are in `cilium.logs` file

**Comment by eloycoto** [comment]
Flake: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3534/

**Comment by eloycoto** [comment]
test-me-please

**Pull request merged**
