### PR TITLE
Removed unnecessary 'revert' parameter from Newk8sTranslator

### LINKED ISSUE #26094: Remove unnecessary `revert` parameter from `NewK8sTranslator()`
See https://github.com/cilium/cilium/pull/25687#discussion_r1223941380.

### PR DESCRIPTION
**Pull request by akstron**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

---

- Removed the revert parameter from Newk8sTranslator definition
- Updated api calls and comments accordingly.
- Updated unit tests.

Fixes: #26094 

```release-note
removed unnecessary 'revert' parameter from Newk8sTranslator and updated api calls accordingly.
```

### CODE REVIEW

**Review by youngnick — APPROVED** [review]
Thanks for this @akstron.

**Comment by akstron** [comment]
I tried to amend this commit https://github.com/cilium/cilium/pull/26217/commits/42a439009c0693ea8a7af1f217281093a954fcaf to sign it but wasn't able to. Is there any other way?

**Comment by youngnick** [comment]
I think the way to sort this out is to rebase from main, squash all your commits into one, and add the "Signed-off-by" manually into the commit message.

**Comment by akstron** [comment]
Let me know if there is anything else which needs to be done? Thanks

**Comment by ldelossa** [comment]
@akstron looks like checkpatch is complaining due to your commit subject being too long:

  Error: ERROR:CUSTOM: Please avoid long commit subjects (max: 75, found: 94)

Also, looks like the TravisCI test got a bit stuck. 

Can you 1. Fix the commit message length and 2. rebase this PR on latest `main` ? After that push the changes back up here and I'll re-run tests.

**Comment by akstron** [comment]
@ldelossa made the necessary changes.

**Comment by christarazi** [comment]
Travis hit https://github.com/cilium/cilium/issues/25635

**Pull request merged**
