### PR TITLE
v1.3: Stop annotating Cilium security identity in kubernetes pods

### PR DESCRIPTION
**Pull request by aanm**
Backport of https://github.com/cilium/cilium/pull/6888

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6993)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by joestringer** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
test-docs-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
