### PR TITLE
ipsec: Deprecate global IPsec keys

### PR DESCRIPTION
**Pull request by pchaigno**
Using a single IPsec key for all IPsec tunnels is insecure. It was only preserved to allow for a smooth switch to per-tunnel keys. Per-tunnel keys have been released in v1.13, v1.14, and v1.15, so we can now deprecate the insecure alternative for v1.16.

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]
Thank you!

I think this would benefit from a mention in the upgrade notes. And maybe a few lines in the IPsec docs to describe the new key system, so that users understand what the deprecation actually means?

**Comment by pchaigno** [comment]
> I think this would benefit from a mention in the upgrade notes. And maybe a few lines in the IPsec docs to describe the new key system, so that users understand what the deprecation actually means?

Done at https://github.com/cilium/cilium/pull/33564.

**Pull request merged**
