### PR TITLE
v1.12: ci: use Ariane to trigger workflows

### PR DESCRIPTION
**Pull request by nbusseneau**
Please see the main PR at #26237 for full context and discussions.

### CODE REVIEW

**Comment by nbusseneau** [comment]
/ariane-test-backport-1.12

**Comment by nbusseneau** [comment]
/ariane-test-backport-1.12

**Comment by nbusseneau** [comment]
/ariane-test-backport-1.12

**Comment by nbusseneau** [comment]
/ariane-test-backport-1.11

**Comment by nbusseneau** [comment]
/ariane-test-backport-1.12

**Comment by nbusseneau** [comment]
image
Removing temporary test commit.

**Review by aanm — APPROVED** [review]

**Pull request merged**
