### PR TITLE
bgp-cp: fix taking address of of loop variable

### PR DESCRIPTION
**Pull request by ldelossa**
this commit fixes a bug in computing a work diff when reconciliating BGP
virtual routers.

this bug would take an address of the the loop variable and store this
which is not the correct reference when utilized later.

to fix this, just take the address of the slice's index.

Signed-off-by: Louis DeLosSantos <louis.delos@isovalent.com>

```release-note
Fixes a bug in the BGP control plane which causes the wrong BGP virtual servers to be selected for reconciliation or removal
```

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
> Fixes a bug in the BGP control plane which causes the wrong BGP virtual servers to be selected for reconciliation or remove.

"or remove" what? :thinking:

**Comment by ldelossa** [comment]
> > Fixes a bug in the BGP control plane which causes the wrong BGP virtual servers to be selected for reconciliation or remove.
> 
> "or remove" what? thinking

Thanks, fixed typo, should have been "removal"

**Review by YutaroHayakawa — APPROVED** [review]

**Review by kaworu — APPROVED** [review]

**Comment by ldelossa** [comment]
@pchaigno Seems like we are hitting flakes, you think we are OK to merge?

**Comment by pchaigno** [comment]
> @pchaigno Seems like we are hitting flakes, you think we are OK to merge?

I didn't triage the flakes. We need to triage them before we can merge I think. It's just a matter of checking opened issues and the CI dashboard.

**Comment by ldelossa** [comment]
Whoops, thought we had. Okay will do.

**Comment by ldelossa** [comment]
two failed test are unrelated to this PR. Setting ready to merge.

**Comment by christarazi** [comment]
Was this PR marked with needs backport to v1.11 by mistake? I don't think this code exists in v1.11. Removing label.

**Pull request merged**
