### PR TITLE
pkg/k8s: update auto-generated code

### PR DESCRIPTION
**Pull request by aanm**
Update autogenerated code and the dependency to generate the code to
tag 1.9.2.

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-nightly

**Comment by tgraf** [comment]
test-me-please

**Comment by aanm** [comment]
test-nightly

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
only 1 nightly test has failed and they don't seem related with my changes

depends on #2690

**Comment by aanm** [comment]
test-nightly

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Pull request merged**
