### PR TITLE
Improve cilium monitor context

### PR DESCRIPTION
**Pull request by joestringer**
This PR puts more context information into monitor messages. Specifically whenever there is a drop, more effort is made to retain the source identity for the traffic. This will help when users attempt to understand monitor messages relating to drops, particularly cases like `Not a local target address`/`Stale or unroutable IP`. Additionally, it updates the monitor drop code comments to highlight some of the now-unused codes.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8174)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]
API side LGTM !

**Comment by ianvernon** [comment]
Not sure what happened to the build - https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12705/flowGraphTable/

**Comment by ianvernon** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
