### PR TITLE
test: Improve host firewall tests

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request improves the ginkgo host firewall tests. The first commit removes an unnecessary test that is already covered in complexity tests. The second commit moves the host firewall tests to their own file. Finally, the third commit fixes an issue that prevents proper artifact collection.

Fixes: https://github.com/cilium/cilium/pull/24484.
Updates: https://github.com/cilium/cilium/issues/16122.

### CODE REVIEW

**Comment by pchaigno** [comment]
/test-1.26-4.19

**Review by viktor-kurchenko — APPROVED** [review]
LGTM.

**Pull request closed without merging**
