### PR TITLE
Fixes:  #23541 

### LINKED ISSUE #23541: hubble: deprecation cleanup
- [x] [Helm's `.Values.hubble.metrics.tls.ca` section](https://github.com/cilium/cilium/blob/4095784e172094e21fcff8cfe6cf69b9a7938c63/install/kubernetes/cilium/values.yaml#L972-L981) was deprecated by https://github.com/cilium/cilium/pull/18607 and planned to be removed in v1.13
- [x] [Helm's `.Values.hubble.peerService.enabled` flag](https://github.com/cilium/cilium/blob/4095784e172094e21fcff8cfe6cf69b9a7938c63/install/kubernetes/cilium/values.yaml#L916-L920) was deprecated by https://github.com/cilium/cilium/pull/23407 and planned to be removed in v1.14, related code (i.e. local UNIX domain socket for the Peer Service in Hubble Relay) should be removed on the way. https://github.com/cilium/cilium/pull/24214

### PR DESCRIPTION
**Pull request by azepecki**
# Summary 

Remove `.Values.hubble.tls.ca` which is deprecated in favor of `tls.ca`. 

Remove `.Values.hubble.peerService.enabled` which is set to true by default.

Fixes: #23541

### CODE REVIEW

**Review by mohit-marathe — CHANGES_REQUESTED** [review]
Lines 944 to 948 needs to be removed as well

**Review by mohit-marathe — CHANGES_REQUESTED** [review]
Remove lines 944 to 948

**Comment by mohit-marathe** [comment]
According to the description of issue: #23541, this block of code seems relevant:
```
{{- if and .Values.hubble.enabled .Values.hubble.peerService.enabled }}
peer-service: "hubble-peer.{{ .Release.Namespace }}.svc.{{ .Values.hubble.peerService.clusterDomain }}:{{ $peerSvcPort }}"
{{- else }}
peer-service: unix://{{ .Values.hubble.socketPath }}
{{- end }}
```
from `install/kubernetes/cilium/templates/hubble-relay/configmap.yaml`

**Comment by mohit-marathe** [comment]
Also this line can be removed as well:
```| hubble.peerService.enabled | bool | `true` | Enable a K8s Service for the Peer service, so that it can be accessed by a non-local client. This configuration option is deprecated, the peer service will be non-optional starting Cilium v1.14. |``` 

from `install/kubernetes/cilium/README.md`

**Comment by sayboras** [comment]
Seems like there is some overlapping with https://github.com/cilium/cilium/pull/24214

**Comment by sayboras** [comment]
Marking this as draft. If you think there is anything else missing, please feel free to shout out. 

Thanks for your interest contributing to Cilium.

**Pull request closed without merging**
