### PR TITLE
v1.16 Backports 2024-10-22

### PR DESCRIPTION
**Pull request by tklauser**
* [ ] #35179 (@wedaly)
 * [x] #35337 (@julianwiedmann)
 * [x] #35165 (@julianwiedmann)
 * [ ] #35400 (@sayboras)
 * [x] #35399 (@aanm)
 * [x] #35408 (@aanm)
 * [ ] #35381 (@jrajahalme)
 * [x] #35333 (@rastislavs)
 * [x] #35422 (@marseel) :warning: resolved conflicts
   * added `any:` prefix as with other labels because commit 1918908a174d ("Improve identity-relevant-labels.rst page") which removed these prefixes across all docs wasn't backported to `v1.16`.
 * [x] #35457 (@aanm)

PRs skipped due to conflicts:

 * #33972 (@darox)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 35179 35337 35165 35400 35399 35408 35381 35333 35422 35457
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commit.

**Comment by tklauser** [comment]
/test-backport-1.16

**Review by julianwiedmann — APPROVED** [review]

**Review by rastislavs — APPROVED** [review]
Thanks!

**Review by marseel — APPROVED** [review]
lgtm, nonblocking: if you happen to update commits for whatever reason, now my commit points to incorrect commit, while PR description points to correct one: https://github.com/cilium/cilium/commit/1918908a174d229aa97af7fa77a88961d72714ba

**Comment by tklauser** [comment]
> lgtm, nonblocking: if you happen to update commits for whatever reason, now my commit points to incorrect commit, while PR description points to correct one: [1918908](https://github.com/cilium/cilium/commit/1918908a174d229aa97af7fa77a88961d72714ba)

Oops, sorry. I updated it locally but forgot to force-push apparently.

**Comment by tklauser** [comment]
/test-backport-1.16

**Review by aanm — APPROVED** [review]

**Pull request merged**
