### PR TITLE
v1.13 Backports 2024-04-22

### PR DESCRIPTION
**Pull request by jschwinger233**
* [ ] #32042 (@giorio94)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 32042
```

### CODE REVIEW

**Comment by jschwinger233** [comment]
/test-backport-1.13

**Comment by giorio94** [comment]
https://github.com/cilium/cilium/pull/29704 has not yet been backported to v1.13. I think we should wait backporting this PR until that one is backported as well (assuming it is still part of the plan, otherwise we can just drop the labels from both). /cc @brb

**Comment by jschwinger233** [comment]
@giorio94 Thanks for letting me know. Does it mean I should backport that PR (https://github.com/cilium/cilium/pull/29704) now (in a separate PR I guess), or I just keep waiting until someone else does me a favor? I

**Comment by giorio94** [comment]
> @giorio94 Thanks for letting me know. Does it mean I should backport that PR (#29704) now (in a separate PR I guess), or I just keep waiting until someone else does me a favor? I

#29704 is marked as backport/author, so I'd personally just mark this one as blocked, and then coordinate with Martynas once it gets backported.

(I'm requesting changes so that it disappears from my review queue until then.)

**Review by giorio94 — CHANGES_REQUESTED** [review]
(I'm requesting changes so that it disappears from my review queue until then.)

**Pull request closed without merging**
