### PR TITLE
Helm: add nodeport-addresses value

### LINKED ISSUE #12508: Add support for --nodeport-addresses
https://kubernetes.io/docs/concepts/services-networking/service/#nodeport:

> If you want to specify particular IP(s) to proxy the port, you can set the --nodeport-addresses flag in kube-proxy to particular IP block(s); this is supported since Kubernetes v1.10. This flag takes a comma-delimited list of IP blocks (e.g. 10.0.0.0/8, 192.0.2.0/25) to specify IP address ranges that kube-proxy should consider as local to this node.
>
> For example, if you start kube-proxy with the --nodeport-addresses=127.0.0.0/8 flag, kube-proxy only selects the loopback interface for NodePort Services. The default for --nodeport-addresses is an empty list. This means that kube-proxy should consider all available network interfaces for NodePort. (That's also compatible with earlier Kubernetes releases).

Also, the flag could be used to extend the kube-proxy replacement device detection.

### PR DESCRIPTION
**Pull request by eyenx**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #12508

I struggled to create the rst with Makefile, got into 

```
docker container run --rm --workdir /src/install/kubernetes --volume /home/usergit/cilium/install/kubernetes/../..:/src --volume /home/user/git/cilium/install/kubernetes:/home/user/git/cilium/install/kubernetes --user "1001:1000" "quay.io/cilium/helm-toolbox:"v1.1.0"@sha256:"961693f182b9b456ed90e5274ac5df81e4af4343104e252666959cdf9570ce9e"" helm-schema -c cilium --skip-auto-generation title,description,required,default,additionalProperties
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan send]:
main.exec(0xc0000d4500?, {0x76d94d?, 0x7?, 0x76cf9f?})
        /go/src/helm-schema/cmd/helm-schema/main.go:337 +0xfbf
github.com/spf13/cobra.(*Command).execute(0xc000004300, {0xc0000140b0, 0x4, 0x4})
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004300)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /go/src/helm-schema/cmd/helm-schema/main.go:355 +0x7f
make: *** [Makefile:68: cilium/values.schema.json] Error 2
```

Any help to fix this appreciated.

```release-note
Feat add nodePort.addresses value to set nodeport-addresses in the cilium configmap
```

### CODE REVIEW

**Comment by joamaki** [comment]
Thanks for this contribution. I had postponed adding the helm value for this until we have tests around it, but I'm OK adding it in already!

**Comment by joamaki** [comment]
Hey, hope you don't mind, but I fixed up few things and also tested this locally.
Changes I made:
- Added schema to the option
- Added the missing join operation
- Added the default value (`~` which is "null") so that the helm docs get generated
- Generated the helm docs

I also tested this in a local kind cluster and added a more descriptive commit message.

If you have a specific need and an environment to test this, could you also independently test that everything works?

Thanks!

**Comment by eyenx** [comment]
> Hey, hope you don't mind, but I fixed up few things and also tested this locally. Changes I made:
> 
>     * Added schema to the option
> 
>     * Added the missing join operation
> 
>     * Added the default value (`~` which is "null") so that the helm docs get generated
> 
>     * Generated the helm docs
> 
> 
> I also tested this in a local kind cluster and added a more descriptive commit message.
> 
> If you have a specific need and an environment to test this, could you also independently test that everything works?
> 
> Thanks!

I don't mind at all 

I really struggled to add make helm-docs work with the `Makefile` Thanks for that. Also I did not add the adresses into the schema as I was not seeing `nodePort.range` there. 

I will test this change on my local cluster and give you feedback! Thanks @joamaki

**Comment by eyenx** [comment]
@joamaki I can confirm my test are successful! Either with an array or sigle string!


Thanks very much for helping me out!

**Review by joamaki — APPROVED** [review]

**Pull request merged**
