### PR TITLE
Various cleanups around pkg/datapath

### PR DESCRIPTION
**Pull request by tklauser**
Best reviewed by commit.

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
LGTM :100:

**Review by gandro — APPROVED** [review]

**Comment by tklauser** [comment]
/test-1.23-net-next

**Review by ldelossa — APPROVED** [review]
LGTM, nice refactors

**Comment by tklauser** [comment]
Kind conformance test was failing due to #20034 which was fixed by #20039 in the meantime. Reviews are in and all other required tests passed. Marking as ready to merge.

**Review by joamaki — APPROVED** [review]

**Pull request merged**
