### PR TITLE
hubble, policy: shuffle types to reduce imports

### PR DESCRIPTION
**Pull request by squeed**
The "leaf" type `pkg/hubble/api/v1` inadvertently imported `pkg/policy`, which has a large set of imports. This causes a few problems, most notably the hubble CLI binary to have a huge number of unnecessary imports. This also means a large set of the codebase must build on all architectures, unnecessarily to boot.

So, this commit has two changes:

1. Lift the policy Key type in to its own package. Since this is referenced **everywhere**, use a type alias to keep our sanity.

2. Move the hubble EndpointInfo interface out of the API type, since it's not really relevant to the API package.

This reduces the number of local imports in the hubble binary from 196 to 57. A nice cleanup.

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Nice cleanup! Note that due to the package move, there are some lint failures now:
image

Otherwise, this looks good to me!

**Comment by squeed** [comment]
> Note that due to the package move, there are some lint failures now:

Hah. I had to actually force-disable that check in `.golangci.yaml`, which is a bummer but better than making hundreds of invocations harder to read.

**Review by michi-covalent — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by squeed** [comment]
I gave up and just fixed the struct literals; we use bot `govet` linter as well as `go vet`, so configuring them is not possible :-/

**Review by ghost — APPROVED** [review]

**Pull request merged**
