### PR TITLE
v1.11 Backports 2023-04-03

### PR DESCRIPTION
**Pull request by jibi**
* [x] #24484 (@jschwinger233)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 24484; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
make add-labels BRANCH=v1.11 ISSUES=24484
```

### CODE REVIEW

**Comment by jibi** [comment]
/test-backport-1.11

**Review by jschwinger233 — APPROVED** [review]

**Comment by jibi** [comment]
/test-backport-1.11

**Comment by jibi** [comment]
/test-1.18-4.9

**Comment by jibi** [comment]
/test-1.20-4.9

**Review by squeed — APPROVED** [review]

**Pull request merged**
