### PR TITLE
docs: fixed various typos in the readme

### LINKED ISSUE #29757: Fix typos all around the project
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've found 200+ misspellings.
From https://github.com/cilium/cilium/pull/29753#issuecomment-1847954160

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

What is the the next step?

### PR DESCRIPTION
**Pull request by payneInTheBrian**
Fixes: #29757 

In an effort to help fix the typos referenced in #29757, I have started with a few in this pr. Sorry about the new pr, I will work on rebase for similar instances in the future. The original is here fyi #30924

Signed-off-by: Brian Payne payne.in.the.brian@gmail.com

```release-note
docs: Fix various typos in README.rst
```

### CODE REVIEW

**Review by qmonnet — CHANGES_REQUESTED** [review]
The fixes look all good, thank you!

Can you please amend your commit to add your `Signed-off-by:` tag to the commit description (and then force-push on your branch)?

**Comment by payneInTheBrian** [comment]
@qmonnet I thought I did just that, but the bot is still saying something is wrong.

**Comment by qmonnet** [comment]
GitHub would display it across two lines if it's too long.

The issue is that you appended the sign-off to your commit title, with no line break, instead of using the commit description. Please change this:

```
docs: fixed various typos in the readme. Signed-off-by: Brian Payne <your email>
```

into this (note the empty line separator between title and description):

```
docs: fixed various typos in the readme

Signed-off-by: Brian Payne <your email>
```

**Comment by payneInTheBrian** [comment]
I think I got it this time. Thanks for being patient with me.

**Review by qmonnet — APPROVED** [review]
Looks all in order this time!

> I think I got it this time. Thanks for being patient with me.

You're welcome, thank _you_ for the PR and for addressing all the quirks!

**Comment by qmonnet** [comment]
In fact we were still missing the blank separator line in the commit description:

```
docs: fixed various typos in the readme.
Signed-off-by: Brian Payne <payne.in.the.brian@gmail.com>
```

should have been:

```
docs: fixed various typos in the readme.

Signed-off-by: Brian Payne <payne.in.the.brian@gmail.com>
```

GitHub interface can do without, but some tools break (including our checkpatch workflow) if the separator is missing. I fixed it for you and force-pushed on your branch.

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
