### PR TITLE
daemon: Fix issue where stale router IPs were not cleaned up

### PR DESCRIPTION
**Pull request by gandro**
Previously, `removeOldRouterState` would only try to clean up stale router
IPs if the `cilium_host` device had more than one address assigned to
it. The implementation however is incorrect if router IP restoration
failed, because if restoration failed, then `restoredIP` would be nil
and the function would assume the IPv6 address family, thus only trying
to remove IPv6 addresses.

But even with the proper address family, the existing logic seems to
have a bug if there is only one single stale IP on the `cilium_host`
device: If restoration failed and there is only one IP on the host
device, then the IP assigned to the device cannot be the restored one,
thus it needs to be removed.

If the single stale IP is not removed and remains on the device, once a
new router IP is allocated by `allocateRouterIPv{4,6}`, and after a new
router IP is added to the interface in `init.sh` (via `Daemon.init`),
then `cilium_host` device will wrongly end up with two router IPs (one
of which is stale).

Fixes: fcd00390c30c6eeffbe2fefa81d5b22e59397297 ("daemon, node: Remove old, discarded router IPs from `cilium_host`")

### CODE REVIEW

**Review by christarazi — APPROVED** [review]
Nice! 

FWIW, It would be great to have tests (https://github.com/cilium/cilium/issues/17771), but I don't expect you to do that now, especially given that I didn't add them when I introduced this logic :sweat_smile:

**Comment by gandro** [comment]
> FWIW, It would be great to have tests (#17771), but I don't expect you to do that now, especially given that I didn't add them when I introduced this logic sweat_smile

Yeah, I found that issue too. If I find the cycles, I might add some. Thanks for the review!

**Comment by gandro** [comment]
I just noticed that both those workflows have been disabled in the meantime, because they are known broken. Thus marking this ready to merge, so it can get backported.

**Pull request merged**
