### PR TITLE
Replace ADD with COPY instruction in Dockerfile

### PR DESCRIPTION
**Pull request by ghost**
ADD VS COPY (https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
Thanks for the PR @juliengk. Could you add some explanation on the rationale behind the switch to the  commit message? (something as simple as "COPY only copies but ADD will unpack archives and fetch URLS" is fine). The change out of context is confusing.

**Comment by jrajahalme** [comment]
test-me-please

**Review by jrajahalme — COMMENTED** [review]
Looking good, thanks!

Would you mind summarizing the rationale in the commit message so that it gets into the git history as well?

Also, we have another Dockerfile in envoy directory, would you mind doing the same fix there as well?

**Comment by joestringer** [comment]
Test failure seems unrelated, to do with failing to download the vagrant image. Will retrigger test run.

**Comment by joestringer** [comment]
test-me-please

**Comment by ghost** [comment]
I have updated the Dockerfile in envoy directory. Let me know if that's good.

Do you want me to do the same for those dockerfiles as well?
* Documentation/Dockerfile
* contrib/packaging/deb/Dockerfile
* contrib/packaging/rpm/Dockerfile

**Comment by rlenglet** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
Awesome, thanks @juliengk!

**Comment by tgraf** [comment]
> Do you want me to do the same for those dockerfiles as well?
> 
> Documentation/Dockerfile
> contrib/packaging/deb/Dockerfile
> contrib/packaging/rpm/Dockerfile

Same cleanup would be much appreciated! I'll merge this as-is as we want to keep PRs small.

**Pull request merged**
