### PR TITLE
cilium: support aead state keys

### PR DESCRIPTION
**Pull request by jrfastab**
Add support aead keys.

Signed-off-by: John Fastabend <john.fastabend@gmail.com

```release-note
Transparent Encryption support for Authenticated Encryption with Associated Data algorithms
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7635)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by tgraf** [comment]
@jrfastab Can we update the main documentation to use this as well?

**Comment by jrfastab** [comment]
@tgraf sure lets update docs. I'll push an update here.

**Comment by jrfastab** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by tgraf — CHANGES_REQUESTED** [review]
```
	 START: ipsec_linux_test.go:116: IPSecSuitePrivileged.TestUpsertIPSecEndpoint
	 level=warning msg="unable to delete IPSec (stateIn) context\n" error="no such process" ipAddr=1.2.0.0 subsys=ipsec
	 level=warning msg="unable to delete IPSec (stateOut) context\n" error="no such process" ipAddr=1.2.0.0 subsys=ipsec
	 ipsec_linux_test.go:152:
	     c.Assert(err, IsNil)
	 ... value *errors.errorString = &errors.errorString{s:"unable to replace local state: invalid argument"} ("unable to replace local state: invalid argument")
	 
	 FAIL: ipsec_linux_test.go:116: IPSecSuitePrivileged.TestUpsertIPSecEndpoint
```

**Comment by jrfastab** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Review by joestringer — CHANGES_REQUESTED** [review]
Still hitting this:

```
	 START: ipsec_linux_test.go:116: IPSecSuitePrivileged.TestUpsertIPSecEndpoint
	 level=warning msg="unable to delete IPSec (stateIn) context\n" error="no such process" ipAddr=1.2.0.0 subsys=ipsec
	 level=warning msg="unable to delete IPSec (stateOut) context\n" error="no such process" ipAddr=1.2.0.0 subsys=ipsec
	 ipsec_linux_test.go:152:
	     c.Assert(err, IsNil)
	 ... value *errors.errorString = &errors.errorString{s:"unable to replace local state: invalid argument"} ("unable to replace local state: invalid argument")
	 
	 FAIL: ipsec_linux_test.go:116: IPSecSuitePrivileged.TestUpsertIPSecEndpoint
```

**Comment by jrfastab** [comment]
Perhaps its worth documenting what is failing above. When we add policies we add using a mark/mask value like this (mark=0x1d00 mask=0x0f00) where 1 is the Key index referencing the associated keys. ~The SPI serves the same purpose. The '1' is masked out so its really there just to aid in reading xfrm output and I *thought* it was harmless.~

However the kernel compares policy entries to find a matching policy to delete like so,

```
		if (pol->type == type &&
		    (mark & pol->mark.m) == pol->mark.v &&
		    !selector_cmp(sel, &pol->selector) &&
		    xfrm_sec_ctx_match(ctx, pol->security)) {
```

Where `mark` is the value passed in by user, `pol->mark.m` is the installed policies mask value and `pol->mark.v` is the installed policies mark value. So what is happening is those entries get stuck in the policy database and can never be deleted. This also explains why the key rollover logic gets stuck sometimes because old policies are not being removed :(.

Feels like a kernel bug to me but easy enough to work-around. If you only ever flush the policy database then this is never noticed. This bug was introduced when we added (re)keying support.

Unit tests worked previously because if we don't try to add any conflicting entries nothing "bad" happens but this PR deletes policy/state to add a new policy/state with the same src/dst mark/mask but with new keys. And the failure above is seen.

EDIT: Including the SPI in the mark _is_ needed because we use it on egress to select the key to use when multiple keys are in the datapath during key transition. The BPF datapath sets the mark to indicate which key to use. Modifying the example above for encrypt 0x1e00 indicates to use the keys associated with '1' to do encryption. However on decrypt side the mark is not needed/used because we can extract the key association directly from the SPI in the header. Fix is a bit subtle but should be straight-forward.

**Comment by jrfastab** [comment]
Also this needs one more fixup otherwise the policies can now be deleted but the key rollover breaks because the SPI is not part of the new/old policy comparison so new policies, with new keys but same nodes, are rejected as duplicates without mark.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Pull request merged**
