### PR TITLE
daemon: Fix Envoy version check and add hidden option to skip it

### PR DESCRIPTION
**Pull request by jrajahalme**
Cilium agent should abort on mismatching Envoy version. The log level
was inadvertently changed from Fatal to Warn in commit 5f18a28b0e
("ct: enforce CT clean up from L3 to L7 policy changes on ingress").

Envoy has not updated its Bazel configuration to correctly set the
linkstamp for the version. Workaround by manually deleteting the
version_linkstamp.o file before build.

Add a new hidden boolean command line option
"--disable-envoy-version-check" that bypasses the version check on
startup. This option is bound to the environment variable
"CILIUM_DISABLE_ENVOY_BUILD" so that if that is defined as "true" or
non-zero the version check will also be skipped. If this environment
variable is defined (at all) when invoking "make" all make actions
within the envoy directory are skipped.

Fixes: 5f18a28b0e ("ct: enforce CT clean up from L3 to L7 policy changes on ingress")
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/3527)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
For the linkstamp workaround, ref. https://github.com/envoyproxy/envoy/issues/2551

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]

**Review by rlenglet — APPROVED** [review]

**Comment by rlenglet** [comment]
Note that I adapted the `envoy/Makefile` changes in https://github.com/cilium/cilium/pull/3035, since it significantly modifies that Makefile.

**Review by aanm — COMMENTED** [review]
As a developer I've mix feelings about this. I remember that I initially ask this to be a `Fatal` so the users wouldn't accidentally run a unsynced `cilium-envoy` binary.

As a developer this will require me to re-build envoy whenever I want to try out cilium (without any HTTP policies) on my development environment, otherwise cilium will not run. But unfortunately envoy takes a lot of time to build and I'm constantly changing the Makefile to not build envoy and use any random cilium-envoy binary that I have installed.

**Comment by rlenglet** [comment]
@aanm We’re only making it re-link here, not rebuild completely. This takes only a few seconds.

**Comment by tgraf** [comment]
> As a developer this will require me to re-build envoy whenever I want to try out cilium (without any HTTP policies) on my development environment, otherwise cilium will not run. But unfortunately envoy takes a lot of time to build and I'm constantly changing the Makefile to not build envoy and use any random cilium-envoy binary that I have installed.

I understand and agree with @aanm. Envoy build times have a huge impact on productivity. Similar to CI issues. We can introduce a hidden flag and Makefile env variable to skip the Envoy build and to not require it to be up or not even attempt for it to be started.

**Comment by tgraf** [comment]
> We’re only making it re-link here, not rebuild completely. This takes only a few seconds.

This has definitely not been my experience, the build and linking often takes 2-3 minutes without any changes.

**Comment by raybejjani** [comment]
I don't particularly have an opinion on this but we have decided previously to indicate unhealthy critical dependencies by exiting (as opposed to reporting a bad health but not exiting). We do this for k8s version or no connection, and maybe etcd. Do we consider Envoy the same type of thing?

**Comment by rlenglet** [comment]
The dependency is actually even tighter to Envoy, more precisely to our filters that are linked into it.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
@aanm @tgraf Added a hidden command line option to skip the test and a bound environment variable that will skip build/install.

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
@aanm Are you OK with this?

**Comment by rlenglet** [comment]
FYI I ported the Makefile changes from this PR into https://github.com/cilium/cilium/pull/3530. I haven’t ported the CILIUM_DISABLE_ENVOY_BUILD trick yet, so that will need to be fixed.

**Review by aanm — APPROVED** [review]
@jrajahalme awesome! thanks a lot!

**Pull request merged**
