### PR TITLE
treewide: Tidy up more imports

### PR DESCRIPTION
**Pull request by twpayne**
This is a follow-up PR to #18357 that tidies a up a few more imports.

### CODE REVIEW

**Review by christarazi — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
That has to be our fastest-ever follow up PR! I've just merged the previous PR :rocket:

**Review by aanm — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
LGTM :100: 

I am using the below settings in goland, just run organize import for entire codebase, only small diff found as per below, feel free to ignore it :dancing_men: 

<details>

```diff
diff --git a/daemon/cmd/daemon_test.go b/daemon/cmd/daemon_test.go
index 3e9516eebe..e7691a5c63 100644
--- a/daemon/cmd/daemon_test.go
+++ b/daemon/cmd/daemon_test.go
@@ -14,11 +14,12 @@ import (
        "testing"
        "time"
 
-       fqdnproxy "github.com/cilium/cilium/pkg/fqdn/proxy"
-       "github.com/cilium/cilium/pkg/proxy"
        "github.com/prometheus/client_golang/prometheus"
        . "gopkg.in/check.v1"
 
+       fqdnproxy "github.com/cilium/cilium/pkg/fqdn/proxy"
+       "github.com/cilium/cilium/pkg/proxy"
+
        "github.com/cilium/cilium/api/v1/models"
        "github.com/cilium/cilium/pkg/controller"
        "github.com/cilium/cilium/pkg/datapath"
diff --git a/pkg/monitor/datapath_debug.go b/pkg/monitor/datapath_debug.go
index 04d8536d33..9a0af21413 100644
--- a/pkg/monitor/datapath_debug.go
+++ b/pkg/monitor/datapath_debug.go
@@ -7,7 +7,6 @@ import (
        "encoding/json"
        "fmt"
        "net"
-
        // NOTE: syscall is deprecated, but it is replaced by golang.org/x/sys
        //       which reuses syscall.Errno similarly to how we do below.
        "syscall"
```

</details>

image

**Comment by twpayne** [comment]
> I am using the below settings in goland, just run organize import for entire codebase, only small diff found as per below, feel free to ignore it 👯‍♂️

Thanks! PR updated and welcome @sayboras! Really happy to have you on the team :)

**Review by tklauser — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Comment by twpayne** [comment]
This has multiple reviews and no functional changes so marking as `ready-to-merge`.

**Review by joestringer — APPROVED** [review]

**Pull request merged**
