### PR TITLE
fix typo in bpf/lib/lb.h

### PR DESCRIPTION
**Pull request by BSWANG**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](http://docs.cilium.io/en/stable/contributing/contributing/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue. 
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](http://docs.cilium.io/en/stable/contributing/contributing/#dev-coo).
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Fix typo in `bpf/lib/lb.h`.

```release-note
<!-- Enter the release note text here if needed -->
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9378)

### CODE REVIEW

**Review by brb — CHANGES_REQUESTED** [review]
Thanks for your contribution.

Please run `make -C daemon apply-bindata` to update `daemon/bpf.sha`. Otherwise, cilium-agent won't compile.

Also, please sign off your commit.

**Comment by BSWANG** [comment]
@brb Thanks for your review. I have updated the commits.

**Comment by BSWANG** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failed due to a git fetch error.

**Comment by brb** [comment]
@BSWANG Can you please rebase and `make -C daemon apply-bindata` again, as `daemon/bpf.sha` got updated in the master?

**Comment by BSWANG** [comment]
@brb done!

**Review by brb — APPROVED** [review]

**Pull request merged**
