### PR TITLE
Add test support for Arm64

### PR DESCRIPTION
**Pull request by odidev**
This PR adds ARM64 job to `nightly.yaml` file.
Modified files `.github/workflows/tests-nightly.yaml` for running the test for arm64 platform.

Signed-off-by: odidev odidev@puresoftware.com

### CODE REVIEW

**Comment by nbusseneau** [comment]
Hi, the nightly tests have been disabled for a while as they are superseded by our other test workflows, and we are going to remove this file entirely in the near future.

I'm not quite clear on what the need is here, mind to clarify? Depending on the answer I may be able to help redirect to the right place where to add the changes.

**Comment by odidev** [comment]
As we have added arm64 job in the GHA, we are trying to check if nightly tests are supported on arm64.

**Comment by nbusseneau** [comment]
I'm still not quite clear on what we're testing here, the code seems to only run `helm template`. Am I missing something? How is it related to the nightly tests above, which used to run on GKE clusters and run stress/performance tests from the repository?

**Comment by odidev** [comment]
I tried to add GKE-test-clusters for arm64 in nightly.yml but the image of `gke-test-cluster` is available for x86 only. While trying to build the image for arm64 I found that it's an archived repo. 

Repo link: https://github.com/isovalent/gke-test-cluster-operator 

Could you please share your feedback regarding this.

**Comment by nbusseneau** [comment]
Yes, this is part of a larger operator-based GKE infrastructure that we stopped supporting, hence why the nightly tests are disabled and will be dropped in the future.

If the goal was only to enhance the nightly tests with arm64 support, I think we can close the PR and not worry anymore about this, as we don't plan on adding it back.

**Comment by odidev** [comment]
@nbusseneau, thank you for the information, it was really helpful.

**Pull request closed without merging**
