### PR TITLE
v1.12 Backports 2022-12-01

### PR DESCRIPTION
**Pull request by bimmlerd**
* [ ] #20472 -- Include DeleteNetworkInterface in ENI Required Privileges Docs (@espringsteen)
 * [ ] #22002 -- docs: fix deployment resource type output (@cleverhu)
 * [x] #22321 -- docs: Update Cilium Sphinx RTD Theme reference (@kimstacy)
 * [x] #22296 -- daemon/cmd: Fix error handling for getting proxy port (@christarazi)
 * [x] #22304 -- docs: add instructions to build the base images from external forks (@aanm)
 * [x] #20366 -- Clear stale CNP status nodes if updates have been disabled (@pippolo84)
 * [ ] #21990 -- fix: Fail CCNP preflight check if using empty endpoint selectors (@thorn3r)
 * [ ] #22346 -- fix: some tofqdn flags not being parsed (@carloscastrojumo)
 * [ ] #22351 -- docs: clarifications about CNCF maintainer status (@lizrice)
 * [ ] #22422 -- docs: update roadmap for graduation application (@xmulligan)
 * [ ] #22303 -- fix 'egressIP' field indentation (@yulng)
 * [x] #22393 -- k8s: don't consider 4xx a successful interaction (@bimmlerd)
 * [ ] #22442 -- docs: Remove Google Season of Docs (@xmulligan)
 * [ ] #22443 -- docs: describe Cilium Feature Proposals (@lizrice)

Most of these had conflicts due to various moves and refactors, but specifically #20366 should be reviewed carefully, I've had to make some changes to it.

PRs skipped due conflicts:

 * #20350 -- daemon: add cleanup for stale local ciliumendpoints that aren't being managed. (@tommyp1ckles)
 * #22297 -- helm: Add relabelings config to ServiceMonitors (@chancez)

PRs "skipped" because the backport is empty:

 * #22426 -- option: Fix Populate entries using "viper" package. (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20472 22002 22321 22296 22304 20366 21990 22346 22351 22422 22303 22393 22442 22443; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
$ make add-label BRANCH=v1.12 ISSUES=20472,22002,22321,22296,22304,20366,21990,22346,22351,22422,22303,22393,22442,22443
```

### CODE REVIEW

**Comment by bimmlerd** [comment]
/test-backport-1.12

**Review by aanm — APPROVED** [review]

**Comment by chancez** [comment]
I opened https://github.com/cilium/cilium/pull/22506 to handle my PR which had conflicts when backporting to 1.12.

**Review by christarazi — APPROVED** [review]

**Comment by julianwiedmann** [comment]
>  Fix behavior where packets leave node if there are no backends (v2) #22388 -- Fix behavior where packets leave node if there are no backends (v2) (@julianwiedmann)

Please back this one out, it needs a custom backport to avoid BPF complexity issues on `v1.12`.
[note that it was tagged with `backport/author` for that reason]

**Review by pippolo84 — APPROVED** [review]
LGTM for PR #20366. Thanks! :+1:

**Comment by bimmlerd** [comment]
> > Fix behavior where packets leave node if there are no backends (v2) #22388 -- Fix behavior where packets leave node if there are no backends (v2) (@julianwiedmann)
> 
> Please back this one out, it needs a custom backport to avoid BPF complexity issues on `v1.12`. [note that it was tagged with `backport/author` for that reason]

Ooof. Good catch, thanks! Bug in my tooling 🙃

**Comment by bimmlerd** [comment]
/test-backport-1.12

**Review by thorn3r — APPROVED** [review]

**Comment by bimmlerd** [comment]
/test-1.24-net-next

**Comment by bimmlerd** [comment]
/ci-external-workloads-v1.12

**Comment by bimmlerd** [comment]
/test-1.18-4.9

**Comment by bimmlerd** [comment]
Marking as ready-to-merge:

- gke-stable is not marked as required, I did not look into what caused the failure.
- ConformanceGKE passed, but then [timed out during cleanup](https://github.com/cilium/cilium/actions/runs/3601903016/jobs/6068254100#step:24:25).

**Review by kimstacy — APPROVED** [review]
Looks great. Thank you, @bimmlerd!

**Pull request merged**
