### PR TITLE
1.6 backports 2019 08 02

### PR DESCRIPTION
**Pull request by raybejjani**
* PR: 8734 -- test: use kvstore-based allocator for upgrade tests (@ianvernon) -- https://github.com/cilium/cilium/pull/8734
 * PR: 8710 -- cilium: encryption, ensure 0x*d00 and 0x*e00 marks dont cause conflicts (@jrfastab) -- https://github.com/cilium/cilium/pull/8710
 * PR: 8578 -- Fix flannel datapath (@joestringer) -- https://github.com/cilium/cilium/pull/8578

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8752)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-nightly

**Comment by raybejjani** [comment]
test-docs-please

**Comment by raybejjani** [comment]
test-upstream-k8s

**Comment by raybejjani** [comment]
test-missed-k8s

**Comment by raybejjani** [comment]
test-me-please

**Comment by ianvernon** [comment]
Normal CI tests failed due to failure to connect to etcd endpoints: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14041/

This has been intermittently occurring in master as well.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Connectivity lost to kvstore: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14076/execution/node/152/log/?consoleFull

**Comment by ianvernon** [comment]
test-me-please

**Review by jrajahalme — COMMENTED** [review]
Did we conclude that none of these PRs caused the master CI regression over the weekend?

**Comment by ianvernon** [comment]
@jrajahalme the kvstore connectivity problems have been observed in the CI for some time since around 1-1.5 weeks

**Comment by raybejjani** [comment]
thanks for retesting/merging this folks! most appreciated

**Pull request merged**
