### PR TITLE
envoy: update cilium/proxy to latest version

### PR DESCRIPTION
**Pull request by mhofstetter**
This commit bumps `cilium/proxy` to the latest version in Helm and Go deps. In addition the following filters are enabled.

* network - set_filter_state
* http - set_filter_state
* http - basic_auth

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Thanks  and LGTM :heavy_check_mark:

**Review by sayboras — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Pull request merged**
