### PR TITLE
[Do not merge] Egress LDL4 plus CIDR-L4 fixes

### PR DESCRIPTION
**Pull request by joestringer**
This is a WIP branch for testing #3324 with an extra datapath fix on top.

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
@joestringer I've rebased my branch (`egress-l3-l4-2`)  to be compatible with master.

**Comment by joestringer** [comment]
@ianvernon I just rebased against your branch.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
PR #3372 supersedes this.

**Pull request closed without merging**
