### PR TITLE
v1.11 backports 2022-04-21

### PR DESCRIPTION
**Pull request by tklauser**
* #19459 -- jenkinsfiles: add `IMAGE_REGISTRY` env parameter (@nbusseneau)
 * #19491 -- pkg/bpf: add map name in error message for OpenParallel (@aanm)
 * #19478 -- docs: improve description for session affinity with KPR (@julianwiedmann)
 * #19489 -- LRP minor improvements (@aditighag)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 19459 19491 19478 19489; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.11

**Review by nbusseneau — APPROVED** [review]
My changes LGTM.

**Review by aanm — APPROVED** [review]

**Review by aditighag — APPROVED** [review]
LGTM for my changes. Thanks!

**Comment by tklauser** [comment]
/test-1.22-4.19

**Comment by tklauser** [comment]
/test-1.18-4.9

**Comment by tklauser** [comment]
/test-1.16-netnext

**Pull request merged**
