### PR TITLE
Documentation: remove bash-test framework references

### LINKED ISSUE #2546: Ginkgo Migration: update documentation to remove old bash script test infra references
Parent: #1839 

After the Ginkgo migration is complete, remove references to the old bash-script based framework from the CI.

### PR DESCRIPTION
**Pull request by ianvernon**
Also do some minor fixups of grammatical errors, and some rewording to make sentences more clear.

Signed-off by: Ian Vernon <ian@cilium.io>

Fixes: #2546

### CODE REVIEW

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
@cilium/contributing Doc build succeeded, indicating that this is good for review.

**Review by aanm — APPROVED** [review]

**Comment by ianvernon** [comment]
@cilium/contributing please review.

**Comment by ianvernon** [comment]
Merging, as no feedback has been received as requested, but have received approval, and because we need the doc fixes for 1.0.

**Pull request merged**
