### PR TITLE
lbmap: Use silent delete in deleteServiceLocked and deleteRevNatLocked

### LINKED ISSUE #30342: "Unable to remove service" after upgrade
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After an upgrade (1.11 -> 1.14.6), the following errors showed up in cilium status. I tried reinstalling cilium, but the issue persisted. The service mentioned does not exist on the cluster.

### Cilium Version

1.14.6

### Kernel Version

5.15

### Kubernetes Version

v1.25.16

### Sysdump

[cilium-sysdump-20240121-113704.zip](https://github.com/cilium/cilium/files/14002334/cilium-sysdump-20240121-113704.zip)

### Relevant log output

```shell
Errors:                cilium             cilium-9kbhm    controller sync-lb-maps-with-k8s-services is failing since 6s (7x): Unable to remove service &{hash:��

d�bP frontend:{L3n4Addr:{AddrCluster:{addr:{addr:{hi:0 lo:281470856125538} z:0xc00019c018} clusterID:0} L4Addr:{Protocol:NONE Port:80} Scope:0} ID:80} backends:[0xc0003cbd50] backendByHash:map[��

♣]$�:0xc0003cbd50] svcType:ClusterIP svcExtTrafficPolicy:Cluster svcIntTrafficPolicy:Cluster svcNatPolicy:NONE sessionAffinity:false sessionAffinityTimeoutSec:0 svcHealthCheckNodePort:0 svcName:{Namespace: Name: Cluster:} loadBalancerSourceRanges:[] l7LBProxyPort:0 l7LBFrontendPorts:[] LoopbackHostport:false restoredFromDatapath:true restoredBackendHashes:map[��

♣]$�:{}]}: Unable to delete service entry 10.100.220.98:20480: unable to delete element 10.100.220.98:80 from map cilium_lb4_services_v2: delete: key does not exist

    cilium    cilium-6pr9h    controller sync-lb-maps-with-k8s-services is failing since 6s (7x): Unable to remove service &{hash:��

d�bP frontend:{L3n4Addr:{AddrCluster:{addr:{addr:{hi:0 lo:281470856125538} z:0xc000010030} clusterID:0} L4Addr:{Protocol:NONE Port:80} Scope:0} ID:80} backends:[0xc000372ee0] backendByHash:map[��

♣d▼�:0xc000372ee0] svcType:ClusterIP svcExtTrafficPolicy:Cluster svcIntTrafficPolicy:Cluster svcNatPolicy:NONE sessionAffinity:false sessionAffinityTimeoutSec:0 svcHealthCheckNodePort:0 svcName:{Namespace: Name: Cluster:} loadBalancerSourceRanges:[] l7LBProxyPort:0 l7LBFrontendPorts:[] LoopbackHostport:false restoredFromDatapath:true restoredBackendHashes:map[��

♣d▼�:{}]}: Unable to delete service entry 10.100.220.98:20480: unable to delete element 10.100.220.98:80 from map cilium_lb4_services_v2: delete: key does not exist

    cilium    cilium-kb72d    controller sync-lb-maps-with-k8s-services is failing since 6s (7x): Unable to remove service &{hash:��

l&MP frontend:{L3n4Addr:{AddrCluster:{addr:{addr:{hi:0 lo:281470856603213} z:0xc000010030} clusterID:0} L4Addr:{Protocol:NONE Port:80} Scope:0} ID:79} backends:[0xc0003de770] backendByHash:map[��

♠Y↑�:0xc0003de770] svcType:ClusterIP svcExtTrafficPolicy:Cluster svcIntTrafficPolicy:Cluster svcNatPolicy:NONE sessionAffinity:false sessionAffinityTimeoutSec:0 svcHealthCheckNodePort:0 svcName:{Namespace: Name: Cluster:} loadBalancerSourceRanges:[] l7LBProxyPort:0 l7LBFrontendPorts:[] LoopbackHostport:false restoredFromDatapath:true restoredBackendHashes:map[��

♠Y↑�:{}]}: Unable to delete service entry 10.108.38.77:20480: unable to delete element 10.108.38.77:80 from map cilium_lb4_services_v2: delete: key does not exist

    cilium    cilium-m59wd    controller sync-lb-maps-with-k8s-services is failing since 5s (7x): Unable to remove service &{hash:��

l&MP frontend:{L3n4Addr:{AddrCluster:{addr:{addr:{hi:0 lo:281470856603213} z:0xc00019c018} clusterID:0} L4Addr:{Protocol:NONE Port:80} Scope:0} ID:79} backends:[0xc000254070] backendByHash:map[��

♠7▼�:0xc000254070] svcType:ClusterIP svcExtTrafficPolicy:Cluster svcIntTrafficPolicy:Cluster svcNatPolicy:NONE sessionAffinity:false sessionAffinityTimeoutSec:0 svcHealthCheckNodePort:0 svcName:{Namespace: Name: Cluster:} loadBalancerSourceRanges:[] l7LBProxyPort:0 l7LBFrontendPorts:[] LoopbackHostport:false restoredFromDatapath:true restoredBackendHashes:map[��

♠7▼�:{}]}: Unable to delete service entry 10.108.38.77:20480: unable to delete element 10.108.38.77:80 from map cilium_lb4_services_v2: delete: key does not exist

    cilium    cilium-xl5qb    controller sync-lb-maps-with-k8s-services is failing since 5s (7x): Unable to remove service &{hash:��

d�bP frontend:{L3n4Addr:{AddrCluster:{addr:{addr:{hi:0 lo:281470856125538} z:0xc0001ae018} clusterID:0} L4Addr:{Protocol:NONE Port:80} Scope:0} ID:80} backends:[0xc000232e70] backendByHash:map[��

♥d=8:0xc000232e70] svcType:ClusterIP svcExtTrafficPolicy:Cluster svcIntTrafficPolicy:Cluster svcNatPolicy:NONE sessionAffinity:false sessionAffinityTimeoutSec:0 svcHealthCheckNodePort:0 svcName:{Namespace: Name: Cluster:} loadBalancerSourceRanges:[] l7LBProxyPort:0 l7LBFrontendPorts:[] LoopbackHostport:false restoredFromDatapath:true restoredBackendHashes:map[��

♥d=8:{}]}: Unable to delete service entry 10.100.220.98:20480: unable to delete element 10.100.220.98:80 from map cilium_lb4_services_v2: delete: key does not exist

    cilium    cilium-zzfd7    controller sync-lb-maps-with-k8s-services is failing since 7s (7x): Unable to remove service &{hash:��

l&MP frontend:{L3n4Addr:{AddrCluster:{addr:{addr:{hi:0 lo:281470856603213} z:0xc000010030} clusterID:0} L4Addr:{Protocol:NONE Port:80} Scope:0} ID:79} backends:[0xc0002e64d0] backendByHash:map[��

♠a↑�:0xc0002e64d0] svcType:ClusterIP svcExtTrafficPolicy:Cluster svcIntTrafficPolicy:Cluster svcNatPolicy:NONE sessionAffinity:false sessionAffinityTimeoutSec:0 svcHealthCheckNodePort:0 svcName:{Namespace: Name: Cluster:} loadBalancerSourceRanges:[] l7LBProxyPort:0 l7LBFrontendPorts:[] LoopbackHostport:false restoredFromDatapath:true restoredBackendHashes:map[��

♠a↑�:{}]}: Unable to delete service entry 10.108.38.77:20480: unable to delete element 10.108.38.77:80 from map cilium_lb4_services_v2: delete: key does not exist
```

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by haozhangami**
The controller failed to delete elements when deleting no longer present services from bpf map.
```
sync-lb-maps-with-k8s-services: unable to delete element <serviceKey>
from map cilium_lb4_services_v2: no such file or directory
sync-lb-maps-with-k8s-services: unable to delete element <revNATKey>
from map cilium_lb4_reverse_nat: no such file or directory
```

In addition, log warning instead of returning error if the service key with a backend slot fails to be deleted, the next backend slot can be deleted.

Fixes: #30342

```release-note
Fix services could not be removed in sync-lb-maps-with-k8s-services controller
```

### CODE REVIEW

**Comment by haozhangami** [comment]
Hi @joestringer @gentoo-root，Please review.

**Comment by msune** [comment]
> Hi @joestringer @gentoo-root，Please review.

@haozhangami @gentoo-root will be OOO until Fri/next. Can we assign another reviewer?

**Comment by joestringer** [comment]
We can cc @cilium/sig-datapath for volunteers. I'm not sure there's a way to retrigger GitHub review load-balancing for the group.

**Comment by youngnick** [comment]
Looks like @gentoo-root should be back online, bump this one back up in his notifications. 😄

**Comment by haozhangami** [comment]
Hi @gentoo-root Please take a look, thanks.

**Comment by haozhangami** [comment]
@gentoo-root seems busy, @msune Can you assign another reviewer?

**Review by joamaki — APPROVED** [review]
Makes sense to me to do these silently!

**Comment by pchaigno** [comment]
@haozhangami I think the CI is failing in part because the pull request hasn't been rebased in a long time. Could you please rebase on latest `main` and I'll retrigger CI?

**Comment by haozhangami** [comment]
@pchaigno I have rebased. Please rerun tests, thanks.

**Comment by haozhangami** [comment]
Integration Tests and Conformance Runtime failures due to a invalid job name.

https://github.com/cilium/cilium/actions/runs/10981304442/job/30490228773
https://github.com/cilium/cilium/actions/runs/10981304424/job/30490245391

This PR #35009 should fix it.

**Comment by haozhangami** [comment]
#35009 has been merged, I rebase on latest main branch. Could you rerun tests? thanks! @pchaigno

**Comment by pchaigno** [comment]
Congrats @haozhangami! Sorry this took a while!

**Pull request merged**
