### PR TITLE
v1.11 backports 2022-09-28

### PR DESCRIPTION
**Pull request by gandro**
* #20979 -- helm: Fix post-start and pre-stop hooks for cilium-nodeinit on Ubuntu EKS images (@dctrwatson)
 * #21239 -- Remove Slack notifications (@michi-covalent) :warning: Conflicts due to differences and missing files
 * #21365 -- daemon: Fix a nil dereference on cleanup when DNS proxy is not enabled (@joamaki) :warning: Conflicts due the cleanup call being slightly different
 * #21348 -- bugtool: Dump envoy config for troubleshooting (@sayboras)
 * #21254 -- makefile: use versioned go container when formatting after api generate. (@tommyp1ckles) :warning: Minor conflicts in flags section
 * #21402 -- Fix a typo in the comment example (@farcaller)
 * #21429 -- cmd/bpf: Log if no policy maps found (@aditighag)
 * #21370 -- ipsec: Simplify XFRM IN policies (@pchaigno) :warning: Minor conflicts in import section
 * #21449 -- daemon: avoid nil pointer dereference on invalid endpoint state (@tklauser)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20979 21239 21365 21348 21254 21402 21429 21370 21449; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Looks good for my commit, thanks :100:

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by tklauser — APPROVED** [review]
Thanks, my change looks good.

**Comment by gandro** [comment]
/test-backport-1.11

**Review by michi-covalent — APPROVED** [review]
🚢 https://github.com/cilium/cilium/pull/21468/commits/7b5f941e49b1525be67e78b3f5fd43a8bfe0119f

**Review by joamaki — APPROVED** [review]
Mine is good, thanks!

**Review by aditighag — APPROVED** [review]
Backport of my changes looks good. Thanks!

**Review by nebril — APPROVED** [review]

**Comment by gandro** [comment]
All failed workflows are disabled on master due to flakiness. Marking ready to merge.

**Pull request merged**
