### PR TITLE
envoy: Optimize lookup in allowed remote policies ordered list

### PR DESCRIPTION
**Pull request by rlenglet**
Signed-off-by: Romain Lenglet <romain@covalent.io>

### CODE REVIEW

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
We store the allowed remotes in an `std::unordered_set<uint64_t>` in the Envoy filter. I'll just use `allowed_remotes_.find(remote_id)`.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]

**Comment by jrajahalme** [comment]
Good find :-)

**Pull request merged**
