### PR TITLE
clustermesh, kvstore: consistently pass controller context to kvstore operations

### PR DESCRIPTION
**Pull request by tklauser**
See commits for details.

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Review by YutaroHayakawa — APPROVED** [review]

**Comment by tklauser** [comment]
/test-1.16-4.9

**Comment by tklauser** [comment]
Cilium-PR-K8s-1.16-kernel-4.9 failed on #23374, all other tests passed and approvals are in. Marking as ready to merge.

**Pull request merged**
