### PR TITLE
Quarantine K8sDatapathVerifier test

### PR DESCRIPTION
**Pull request by michi-covalent**
Due to this flake: https://github.com/cilium/cilium/issues/25255

### CODE REVIEW

**Comment by pchaigno** [comment]
This is happening often now because the tests run in the same order all the time and, I'm guessing, K8sDatapathServicesTest doesn't properly clean pods after itself (most likely removes Cilium without checking that all pods have been removed).

**Comment by michi-covalent** [comment]
sounds good, then i'll wait for @tommyp1ckles to open a pull request to fix this flake before closing this pull request 🚀 i just noticed people are setting `ready-to-merge` label manually just to ignore this flake. if it's a one line fix, totally makes sense to fix it instead 🙏

**Review by tommyp1ckles — APPROVED** [review]

**Comment by michi-covalent** [comment]
/test-backport-1.13

**Comment by michi-covalent** [comment]
/test-backport-1.13

**Comment by michi-covalent** [comment]
got fixed in https://github.com/cilium/cilium/issues/25255. closing.

**Comment by pchaigno** [comment]
> got fixed in #25255. closing.

@michi-covalent Did you mean to link to something else?

**Comment by michi-covalent** [comment]
oh yes i did 😅 the fix is in https://github.com/cilium/cilium/pull/25341, and it got backported to v1.13 in https://github.com/cilium/cilium/pull/25503

**Pull request closed without merging**
