### PR TITLE
docker: Install protoc-gen-validate in cilium-builder image

### PR DESCRIPTION
**Pull request by rlenglet**
Signed-off-by: Romain Lenglet <romain@covalent.io>

### CODE REVIEW

**Comment by rlenglet** [comment]
I'm testing and building an image right now.

**Review by aanm — APPROVED** [review]
the real question is how is docker hub running without any errors?

**Review by jrajahalme — APPROVED** [review]
Looks good to me :-)

**Comment by rlenglet** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
> the real question is how is docker hub running without any errors?

Very good question. It is still on builder:
`FROM cilium/cilium-builder:2018-02-16 as builder`

**Comment by tgraf** [comment]
@rlenglet @jrajahalme When is protoc-gen-validate executed exactly?

**Comment by rlenglet** [comment]
@tgraf It's executed when building Envoy.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Pushed image `cilium/cilium-builder:2018-03-09` with the change in this PR to install `protoc-gen-validate`.

**Comment by rlenglet** [comment]
test-me-please

**Comment by aanm** [comment]
>@tgraf It's executed when building Envoy.

So we are not building envoy on every docker build?

**Pull request merged**
