### PR TITLE
[v1.13] nodediscovery: Split fill local node and fill some fields early

### PR DESCRIPTION
**Pull request by dylandreimerink**
When in cluster pool IPAM mode we update the Cilium node before we initialize the local node via `StartDiscovery` -> `fillLocalNode`. When this happens during a restart the bootID is not set yet and the other nodes will see us go from a known boot ID to no bootID and back which triggers IPSec logic to replace xfrm states.

The `fillLocalNode` function can only be called at a certain point in the startup sequence, but this doesn't apply to all fields it sets including the boot ID. So this change splits the function into two and moves all fields that can be initialized early to a new function which is called in the node discovery constructor. This ensures the boot ID is always set when doing an early Cilium node update.

Fixes: #33881

```release-note
Fix IPSec XfrmInStateProtoError errors on agent restart in cluster pool IPAM mode
```

### CODE REVIEW

**Comment by dylandreimerink** [comment]
/test-backport-1.13

**Review by squeed — APPROVED** [review]

**Comment by dylandreimerink** [comment]
/test-1.17-4.19

**Comment by dylandreimerink** [comment]
/test-1.25-4.19

**Pull request merged**
