### PR TITLE
docs: cleanup SPIRE & Envoy values in helm reference

### PR DESCRIPTION
**Pull request by mhofstetter**
This PR cleans up the helm reference documentation of the SPIRE & Envoy related values, by removing the comments of "objects" from the documentation and replacing them with comments on the object properties if not already present.

This removes objects like the following from the docu
screenshot-2023-06-08-16-29-54

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
LGTM :heavy_check_mark:

**Review by kaworu — APPROVED** [review]

**Review by youngnick — APPROVED** [review]

**Comment by mhofstetter** [comment]
removed review-request for @tommyp1ckles as sig-k8s is already covered by @youngnick & @sayboras

**Review by zacharysarah — APPROVED** [review]
LGTM

**Comment by mhofstetter** [comment]
documentation changes only. marking as ready-to-merge

**Pull request merged**
