### PR TITLE
Fix L7 ingress proxy in endpoint routes mode

### PR DESCRIPTION
**Pull request by joestringer**
Fix per-endpoint route mode with the cilium-health endpoint, and configure
it such that the daemon prefers to connect over IPv4 rather than IPv6 when
both protocols are enabled in the daemon. Otherwise we hit CI issues in
the endpoint routes mode datapath configuration test (See #8956).

Fix up the per-endpoint route mode tests so they actually test per-endpoint
routes in the supported direct routing mode rather than in tunnel mode.

Fix routing from a host proxy towards local pods in endpoint routes mode:

    When endpoint routes are enabled, we don't need to install the ip rules
    or routes to ensure that the traffic from the ingress proxy goes into
    cilium_host; Instead, we configure BPF programs attached to the TC
    egress filter of the endpoint device to ensure that it implements the
    policy logic.
    
    Treat this case as datapath mode "routed", where we will now skip those
    rules. All other datapath configuration should be equivalent to direct
    mode.
    
    If we don't do this, then when applying L7 ingress policy, the traffic
    from the ingress proxy towards the pod is first directed towards the
    cilium_host device, then subsequently passed to the stack and re-routed
    towards the endpoint device, which causes the BPF to lose the context
    that this traffic comes from the proxy and hence the BPF program treats
    it as newly inbound traffic from the world. As a result, inbound HTTP
    requests see a message like:

    ```
    $ kubectl exec tiefighter -- curl -s -XPOST 192.168.73.130/v1/request-landing                                                                                                                                                                  
    upstream connect error or disconnect/reset before headers. reset reason: connection failure
    ```

This fixes the following policy cases:
* Ingress L7 policy in direct routing mode for traffic from the same node
* Ingress L7 policy in direct routing mode for traffic from a remote node

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8930)

### CODE REVIEW

**Comment by joestringer** [comment]
This currently causes some havoc with `cilium-health` IPv6 connectivity which I'm still figuring out. It's easy to reproduce with `enable-ipv6: true` and `enable-endpoint-routes: true`, and may be something to do with the new `routed` mode in `bpf/init.sh`.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
