### PR TITLE
v1.14 Backports 2024-04-22

### PR DESCRIPTION
**Pull request by jschwinger233**
* [x] #31510 (@giorio94)
 * [x] #31959 (@marseel)
 * [x] #32004 (@jrajahalme)
 * [x] #31958 (@giorio94)
 * [x] #32042 (@giorio94)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31510 31959 32004 31958 32042
```

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
My PRs look good, thanks!

**Comment by jschwinger233** [comment]
/test-backport-1.14

**Review by marseel — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]
My commits LGTM

**Comment by jschwinger233** [comment]
/test-backport-1.14

**Review by aanm — APPROVED** [review]

**Review by ti-mo — APPROVED** [review]

**Pull request merged**
