### PR TITLE
test: update k8s to 1.21.0

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
The CI was green except the runtime tests and go-mod GH action. Fix go mod and re-running runtime tests only...

**Comment by aanm** [comment]
test-runti,e

**Comment by aanm** [comment]
test-runtime

**Review by kkourt — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Pull request merged**
