### PR TITLE
Run cloud provider conformance tests every 6 hours

### PR DESCRIPTION
**Pull request by michi-covalent**
Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
What about the cluster-mesh one? https://github.com/cilium/cilium/blob/09c465e232072b5da13c88c8a11460981efbb575/.github/workflows/multicluster.yaml

**Review by tgraf — APPROVED** [review]

**Comment by michi-covalent** [comment]
> What about the cluster-mesh one? https://github.com/cilium/cilium/blob/09c465e232072b5da13c88c8a11460981efbb575/.github/workflows/multicluster.yaml

ah yes i missed that one. updating...

**Review by aanm — APPROVED** [review]
:rocket: :rocket: :rocket: :rocket: :rocket:

**Comment by michi-covalent** [comment]
test-me-please

**Comment by pchaigno** [comment]
All team reviews are covered and CI is green. Marking as ready to merge.

**Review by nbusseneau — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by joestringer** [comment]
@michi-covalent  thanks again for the PR, as a quick reminder for future PRs, please ensure that you either update the release note in the description or remove this section as these end up in the final release notes for the upcoming release:

```
<!-- Enter the release note text here if needed or remove this section! -->
```

**Pull request merged**
