### PR TITLE
vendor: update github.com/go-openapi/loads

### PR DESCRIPTION
**Pull request by tklauser**
This will pull in memory usage improvements from go-openapi/analysis#54

Updates #10056

Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10364)

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
Shouldn't we pin this version somewhere by importing the dependency directly?

**Comment by tklauser** [comment]
> Shouldn't we pin this version somewhere by importing the dependency directly?

I tried that, but since the version pinned in github.com/go-openapi/loads is currently the latest version github.com/go-openapi/analysis (due to go-openapi/loads#26) it didn't make any difference.

**Comment by aanm** [comment]
> > Shouldn't we pin this version somewhere by importing the dependency directly?
> 
> I tried that, but since the version pinned in github.com/go-openapi/loads is currently the latest version github.com/go-openapi/analysis (due to [go-openapi/loads#26](https://github.com/go-openapi/loads/pull/26)) it didn't make any difference.

great, perfect!

**Pull request merged**
