### PR TITLE
v1.9 backports 2021-04-29

### PR DESCRIPTION
**Pull request by aanm**
* #15803 -- handle IP addresses modification in running nodes and CEPs (@aanm)
* #15077 -- pkg/k8s: add DeepEqual code generation for Service (@aanm)

PR #15803 depends on #15077, so both had to be backported

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 15077 15803; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.9

**Comment by aanm** [comment]
test-1.12-netnext

**Comment by pchaigno** [comment]
test-1.12-netnext

**Comment by aanm** [comment]
@pchaigno I think it's a real failure since it happened here as well https://github.com/cilium/cilium/pull/15927

**Comment by aanm** [comment]
test-backport-1.9

**Review by rolinh — APPROVED** [review]

**Pull request merged**
