### PR TITLE
k8s: fix ciliumpodippools CRD controller-gen version

### LINKED ISSUE #25974: CI: generate-k8s-api (check)
## CI failure

Output from `Check k8s generated files`

```
Ungenerated source code:
diff --git a/pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliumpodippools.yaml b/pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliumpodippools.yaml
index 1521cb28..d3ec7776 100644
--- a/pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliumpodippools.yaml
+++ b/pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliumpodippools.yaml
@@ -4,7 +4,7 @@ apiVersion: apiextensions.k8s.io/v1
 kind: CustomResourceDefinition
 metadata:
   annotations:
-    controller-gen.kubebuilder.io/version: v0.7.0
+    controller-gen.kubebuilder.io/version: v0.11.4
   creationTimestamp: null
   name: ciliumpodippools.cilium.io
```

Example: https://github.com/cilium/cilium/actions/runs/5198526498/jobs/9374763790?pr=25973

Introduced with https://github.com/cilium/cilium/pull/25824 and having https://github.com/cilium/cilium/pull/25711 (which updated the generator version) in the meantime

### PR DESCRIPTION
**Pull request by mhofstetter**
This commit fixes the outdated version in the annotation `controller-gen.kubebuilder.io/version` of the CRD ciliumpodippools by updating it to `v0.11.4`.

Fixes: https://github.com/cilium/cilium/issues/25974

### CODE REVIEW

**Review by gandro — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
Thanks

**Review by sayboras — APPROVED** [review]
Thanks :rocket:

**Comment by mhofstetter** [comment]
removed review-request from @youngnick - as sig-k8s is already covered by @sayboras

**Comment by gandro** [comment]
`Go-related checks / generate-k8s-api (pull_request)` is green :green_circle: 

Let's not wait on CI to finish, since this prevents other PRs from becoming green.

**Pull request merged**
