### PR TITLE
test: De-flake xds server_e2e_test

### LINKED ISSUE #31855: CI: Runtime Test (privileged): `panic: Fail in goroutine after Test/ServerSuite/TestRequestStaleNonce has completed`
From: https://github.com/cilium/cilium/actions/runs/8566213622/job/23475661233
[logs_22453019086.zip](https://github.com/cilium/cilium/files/14917321/logs_22453019086.zip)
```
time="2024-04-05T07:14:03Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-05T07:14:04Z" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-05T07:14:04Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-05T07:14:04Z" level=warning msg="NACK received for versions after 1 and up to 2; waiting for a version update before sending again" subsys=xds xdsAckedVersion=1 xdsClientNode="node0~10.0.0.0~node0~bar" xdsDetail=FAILFAIL xdsNonce=2 xdsStreamID=1 xdsTypeURL=type.googleapis.com/envoy.config.v3.DummyConfiguration
time="2024-04-05T07:14:05Z" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-05T07:14:05Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-05T07:14:05Z" level=warning msg="NACK received for versions after  and up to 1; waiting for a version update before sending again" subsys=xds xdsAckedVersion= xdsClientNode="node0~10.0.0.0~node0~bar" xdsDetail= xdsNonce=1 xdsStreamID=1 xdsTypeURL=type.googleapis.com/envoy.config.v3.DummyConfiguration
time="2024-04-05T07:14:05Z" level=warning msg="NACK received for versions after  and up to 2; waiting for a version update before sending again" subsys=xds xdsAckedVersion= xdsClientNode="node0~10.0.0.0~node0~bar" xdsDetail= xdsNonce=2 xdsStreamID=1 xdsTypeURL=type.googleapis.com/envoy.config.v3.DummyConfiguration
time="2024-04-05T07:14:05Z" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-05T07:14:05Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-05T07:14:06Z" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-05T07:14:06Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-05T07:14:06Z" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-05T07:14:06Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-05T07:14:07Z" level=info msg="xDS stream closed" subsys=xds xdsClientNode="node0~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-05T07:14:07Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
panic: Fail in goroutine after Test/ServerSuite/TestRequestStaleNonce has completed

goroutine 15 [running]:
testing.(*common).Fail(0xc00032b860)
	/root/sdk/go1.22.2/src/testing/testing.go:952 +0xd4
github.com/cilium/checkmate.(*C).Fail(0xc000337880)
	/host/vendor/github.com/cilium/checkmate/helpers.go:29 +0x34
github.com/cilium/checkmate.(*C).internalCheck(0xc000337880, {0xc35f0d, 0x5}, {0xb11d00, 0x128dd00}, {0xd3cc80, 0x128d260}, {0x0, 0x0, 0x0})
	/host/vendor/github.com/cilium/checkmate/helpers.go:217 +0x9da
github.com/cilium/checkmate.(*C).Check(...)
	/host/vendor/github.com/cilium/checkmate/helpers.go:152
github.com/cilium/cilium/pkg/envoy/xds.(*ServerSuite).TestRequestStaleNonce.func1()
	/host/pkg/envoy/xds/server_e2e_test.go:681 +0xa8
created by github.com/cilium/cilium/pkg/envoy/xds.(*ServerSuite).TestRequestStaleNonce in goroutine 14
	/host/pkg/envoy/xds/server_e2e_test.go:678 +0x4f6
FAIL	github.com/cilium/cilium/pkg/envoy/xds	4.029s
```

### PR DESCRIPTION
**Pull request by jrajahalme**
De-flake xds server_e2e_test by:
- return `nil` error from xDS server after context cancel
- wait for stream server error check to be done before completing test
- return io.EOF upon channel close from stream_test mock
- eliminate xDS CacheUpdateDelay
- eliminate duplicate SendRequest in TestRequestStaleNonce
- increase xDS test stream timeout

See commit messages for rationale for each step.

Fixes: #31855

### CODE REVIEW

**Review by sayboras — COMMENTED** [review]
Nice, the tests are running much faster than previous iteration :heavy_check_mark: 

```
$ go test -count 1000 ./pkg/envoy/xds/...           
ok      github.com/cilium/cilium/pkg/envoy/xds  4.371s
```

**Review by sayboras — APPROVED** [review]

**Comment by jrajahalme** [comment]
@sayboras How far you think we should backport this? The code touched here has barely changed, so it should be easy to backport, and recuding flakes in release builds may be valuable as well.

**Comment by sayboras** [comment]
> How far you think we should backport this? The code touched here has barely changed, so it should be easy to backport, and recuding flakes in release builds may be valuable as well.

Yes, xds code is not changed much for a long time, we can backport this till 1.13 imo.

**Pull request merged**
