### PR TITLE
Adds ipv6 support for local-router-ip

### PR DESCRIPTION
**Pull request by Weil0ng**
- breaks local-router-ip into local-router-ipv4 and local-router-ipv6
- removes a problematic ipam condition check when either of the above is
specified

original option added in PR #14800

Signed-off-by: Weilong Cui <cuiwl@google.com>

### CODE REVIEW

**Review by twpayne — APPROVED** [review]
LGTM. As the original `--local-router-ip` flag was introduced after 1.9 was released and therefore hasn't been part of a stable release, I think it's OK to remove the old flag completely.

**Comment by Weil0ng** [comment]
test-me-please

**Comment by Weil0ng** [comment]
failure seems unrelated, retesting 4.9

**Comment by Weil0ng** [comment]
retest-4.9

**Comment by Weil0ng** [comment]
friendly ping :)

**Review by nathanjsweet — APPROVED** [review]

**Pull request merged**
