### PR TITLE
Nightly: Fix issues with Kubectl exec

### LINKED ISSUE #3106: Nightly: Test flake cannot exec command in container.
```
15:34:32 [Nightly] • Failure [150.970 seconds]
15:34:32 [Nightly] NightlyPolicies
15:34:32 [Nightly] /root/jenkins/workspace/Cilium-PR-Nightly-Tests-All/src/github.com/cilium/cilium/test/k8sT/PoliciesNightly.go:29
15:34:32 [Nightly]   PolicyEnforcement default
15:34:32 [Nightly]   /root/jenkins/workspace/Cilium-PR-Nightly-Tests-All/src/github.com/cilium/cilium/test/k8sT/PoliciesNightly.go:65
15:34:32 [Nightly]     L3:Ingress Label L4:Egress Port 80 TCP L7:No Policy Destination:NodePort [It]
15:34:32 [Nightly]     /root/jenkins/workspace/Cilium-PR-Nightly-Tests-All/src/github.com/cilium/cilium/test/k8sT/PoliciesNightly.go:70
15:34:32 [Nightly] 
15:34:32 [Nightly]     cannot apply network policy for 19e67f5e
15:34:32 [Nightly]     Expected
15:34:32 [Nightly]         <*errors.errorString | 0xc420082ad0>: {
15:34:32 [Nightly]             s: "Network policy cannot be imported prefix=19e67f5e: cannot get the revision OCI runtime exec failed: exec failed: container_linux.go:296: starting container process caused \"process_linux.go:90: adding pid 27342 to cgroups caused \\\"failed to write 27342 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/kubepods/besteffort/pod4162b40b-2399-11e8-9b7d-08002795cd5f/2cc45c507b40fd742fed0c4202dfe08c496e03b8d3f4114b6a90ce2c7de1a8aa/cgroup.procs: invalid argument\\\"\": unknown\r\ncommand terminated with exit code 126\n",
15:34:32 [Nightly]         }
15:34:32 [Nightly]     to be nil
```

**Issue related:**
https://github.com/moby/moby/pull/36097 --> Docker CE 17.12.0-ce version.
https://github.com/openshift/origin/issues/16246 
https://github.com/opencontainers/runc/pull/1683

Docker should be updated in the VM.

### PR DESCRIPTION
**Pull request by eloycoto**
This is a workaround to the CGroups issues that we have seen in Nightly
in the last months. Tested with Kubernetes 1.10 and it fails too, so
make this workaround to avoid Kubectl Exec issue.

Fix #3106

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-nightly

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
