### PR TITLE
envoy: remove unnecessary wait and log message after starting envoy

### PR DESCRIPTION
**Pull request by mhofstetter**
When the envoy proxy gets started by the Cilium Agent, the message `Envoy: Sleeping for 100ms before restarting proxy` gets logged.

With the introduction of supervising the Envoy Proxy in a dedicated go-routine (https://github.com/cilium/cilium/pull/2680), this message and the corresponding wait is somewhat unnecessary and gets deleted with this commit.

### CODE REVIEW

**Review by jrajahalme — CHANGES_REQUESTED** [review]
Agree that since the introduction of the `stopCh` the restart loop will be exited after Envoy is intentionally stopped, so this wait is not necessary in that case. However, if there is a crash in Envoy startup this wait is necessary to limit the speed at which Envoy is started again, as in some cases Envoy would just crash again and then be perpetually restarted in a busy loop, hogging CPU resources.

How about moving the wait to be right after the "Envoy: Proxy crashed" log message, where a non-nil error was received, so that there would be some time before restart is tried in the outer goroutine?

**Comment by mhofstetter** [comment]
> Agree that since the introduction of the `stopCh` the restart loop will be exited after Envoy is intentionally stopped, so this wait is not necessary in that case. However, if there is a crash in Envoy startup this wait is necessary to limit the speed at which Envoy is started again, as in some cases Envoy would just crash again and then be perpetually restarted in a busy loop, hogging CPU resources.
> 
> How about moving the wait to be right after the "Envoy: Proxy crashed" log message, where a non-nil error was received, so that there would be some time before restart is tried in the outer goroutine?

thanks for pointing that out! might be really worth to only delete the "irritating" log message and move the actual wait to the point where we should wait after a crash of envoy.

**Review by jrajahalme — APPROVED** [review]

**Comment by mhofstetter** [comment]
/test-1.25-4.19

**Pull request merged**
