### PR TITLE
v1.13 Backports 2023-12-20

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
* [x] #29809 (@marseel)
 * [x] #29957 (@gandro)
 * [x] #29880 (@julianwiedmann)

⚠️ Conflict observed, see backporter's note for more details

 * [x] #27894 (@leblowl)
 * [x] #29616 (@learnitall)

⚠️ Skipped

 * #29849 (@brb)
   * There's no workflow using `CILIUM_CLI_VERSION`

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 27894 29809 29957 29880 29616
```

### CODE REVIEW

**Comment by YutaroHayakawa** [comment]
/test-backport-1.13

**Review by julianwiedmann — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
k8s-1.26-kernel-net-next: https://github.com/cilium/cilium/issues/30021

**Comment by YutaroHayakawa** [comment]
/test-1.26-net-next

**Review by marseel — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Review by learnitall — CHANGES_REQUESTED** [review]
Changes LGTM, but I'm not sure I understand the backporter note that you left. It says:

```
[ backporter's note: backporter's note: Conflict due to the
  do_netdev_encrypt_encap doesn't exist on v1.13 branch. Removed it. ]
```

But the commit applied here is 1:1 with the upstream commit. The change on line 733 in `bpf/bpf_host.c` is inside the function `do_netdev_encrypt_encap`. Maybe I'm missing something?

**Comment by YutaroHayakawa** [comment]
@learnitall Same for https://github.com/cilium/cilium/pull/30004#issuecomment-1884181251. Sorry for the confusion. Fixed the message in the latest push.

**Comment by YutaroHayakawa** [comment]
/test-backport-1.13

**Review by learnitall — APPROVED** [review]
Thank you!

**Comment by julianwiedmann** [comment]
@gandro did your review cover https://github.com/cilium/cilium/pull/27894 ? If not, who else could cover the review for that PR?

**Comment by gandro** [comment]
> @gandro did your review cover #27894 ? If not, who else could cover the review for that PR?

Ah, yes it did. Sorry, forgot to check that too.

**Review by dylandreimerink — APPROVED** [review]

**Pull request merged**
