### PR TITLE
bpf: Avoid additional cgo call per perf read

### PR DESCRIPTION
**Pull request by tgraf**
Every cgo call is expensive. Avoid the call to Cast() as it can be folded into
the read.

Related: #5650

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5652)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — COMMENTED** [review]
@tgraf do we need to add these structures to the `pkg/alignchecker`?

**Comment by tgraf** [comment]
> @tgraf do we need to add these structures to the `pkg/alignchecker`?

Doesn't hurt.

**Comment by tgraf** [comment]
CI failure is relevant. Will investigate.

**Comment by tgraf** [comment]
test-me-please

**Comment by aanm** [comment]
> > @tgraf do we need to add these structures to the `pkg/alignchecker`?
> 
> Doesn't hurt.

Here or in a different PR?

**Review by joestringer — APPROVED** [review]

**Comment by tgraf** [comment]
> Here or in a different PR?

Different PR

**Pull request merged**
