### PR TITLE
Periodically sync ENI limits using EC2 API to update newly launched AWS instance info.

### LINKED ISSUE #28424: Cilium operator cannot allocate IP addresses when AWS launch new instance types
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- The cilium operator relies on the ec2 instance limit in the process of IP allocation. This information fetched from AWS API on the Cilium operator startup here: https://github.com/cilium/cilium/blob/main/pkg/ipam/allocator/aws/aws.go#L102
- On 4 Oct 2023 AWS launched new instance types c7a ([blog post](https://aws.amazon.com/blogs/aws/new-amazon-ec2-c7a-instances-powered-by-4th-gen-amd-epyc-processors-for-compute-optimized-workloads/))
- The Cilium operator that was already running before that launch has no information about limits for c7a types
- We are using Karpenter for node provisioning. It periodically fetches information about new instance types and started provisioning c7a instances because it’s cheap  (because a low amount of AWS customers use new instance types right after launch)
- Karpenter provisions new nodes and Cilium cannot allocate IP addresses on it

Some cilium operator logs in the process of the incident

--update-ec2-adapter-limit-via-api already set to true and the issue was fixed after the ilium-operator reboot

I guess that cilium-operator should periodically fetch this API for new instance types to prevent such issues

### Cilium Version

Client: 1.14.2 a6748946 2023-09-09T20:59:33+00:00 go version go1.20.8 linux/amd64
Daemon: 1.14.2 a6748946 2023-09-09T20:59:33+00:00 go version go1.20.8 linux/amd64

### Kernel Version

Linux <NodeName> 5.15.128 #1 SMP Thu Sep 14 21:42:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.4-eks-2d98532", GitCommit:"3d90c097c72493c2f1a9dd641e4a22d24d15be68", GitTreeState:"clean", BuildDate:"2023-07-28T16:51:44Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

n/a

### Relevant log output

```shell
2023-10-04 17:57:17.292 
level=warning msg="Unable to find limits for instance type, consider setting --update-ec2-adapter-limit-via-api=true on the Operator" instance-type=c7a.large subsys=eni

2023-10-05 10:39:24.478 
level=warning msg="Instance not found! Please delete corresponding ciliumnode if instance has already been deleted." instanceID=i-0b7fc3f275d818c7f name=ip-10-7-128-51.ec2.internal subsys=ipam
```

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AnishShah**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

I'm periodically calling `GetInstanceTypes` EC2 API call to keep updating ENI limits. I think this is overkill (since AWS might be launched only a few new instances per year). But I think it is ok as there are only hundreds of AWS instances and shouldn't impact memory/network perf.

Another alternative is to lazy fetch new instance type only when we don't find the instance type. I tried implementing this approach but it required a lot of refactoring. 

Fixes: #28424 

```release-note
Fix an issue where cilium is unable to allocate IP addresses when it is running on newly launched AWS instances
```

### CODE REVIEW

**Review by christarazi — APPROVED** [review]

**Comment by AnishShah** [comment]
@christarazi , do you think this change is safe enough to be backported?

**Comment by christarazi** [comment]
Backports are subject to the [backporting criteria](https://docs.cilium.io/en/stable/contributing/release/backports/#backport-criteria-for-x-y-1-z-and-x-y-2-z). From what I can tell, this PR could be considered for v1.15 backport, but any further seems to be a stretch according to the criteria.

**Comment by AnishShah** [comment]
Thanks, @christarazi. Can you help with triggering the remaining tests?

**Comment by AnishShah** [comment]
any idea if some tests are flaky? The test failure doesn't seem to be related to my change. How can I retrigger tests?

**Comment by christarazi** [comment]
I've retriggered the tests as they were flakes.

**Pull request merged**
