### PR TITLE
v1.11 backports 2022-05-26

### PR DESCRIPTION
**Pull request by jibi**
* #19885 -- docs: Add docs-builder build as dependency to live preview (@qmonnet)
 * #19888 -- docs: Remove '\r' chars from grep result to parse Alpine image name (@qmonnet)
   * small conflict as the `builder-image` command was slightly different
 * #19832 -- datapath: Fix implicit-int-conversion err in common.h (@brb)
 * #19886 -- Do not disable peer service when hubble.listenAddress is empty (@chancez)
   * some minor conflicts for docs, had to run `make -C install/kubernetes && make -C Documentation update-helm-values`
 * #19856 -- Bugtool: Add additional tc commands. (@tommyp1ckles)
 * #19927 -- api: change "group not found" log to debug (@tklauser)
 * #19893 -- docs: Fix max SPI value for IPsec key rotations (@pchaigno)
 * #19930 -- docs: Fix incorrect FQDN flag (@pchaigno)
 * #19918 -- jenkins: switch to ad-hoc GKE cluster creation/deletion (@nbusseneau)
   * some conflicts: `resize_cluster.sh` does not exist in 1.11 and the cli test is under `k8sT/Cli.go`
 * #19887 -- ipcache: Error out from InjectLabels if Checker is nil (@jrajahalme)
   * some conflicts: `ipc` -> `IPIdentityCache`

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 19885 19888 19832 19886 19856 19927 19893 19930 19918 19887; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
$ make add-label BRANCH=v1.11 ISSUES=19885,19888,19832,19886,19856,19927,19893,19930,19918,19887
```

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]
> * https://github.com/cilium/cilium/pull/19885 -- docs: Add docs-builder build as dependency to live preview (@qmonnet)
> * https://github.com/cilium/cilium/pull/19888 -- docs: Remove '\r' chars from grep result to parse Alpine image name (@qmonnet)
>    * small conflict as the builder-image command was slightly different

Look good, thank you!

**Review by pchaigno — CHANGES_REQUESTED** [review]
> https://github.com/cilium/cilium/pull/16647 -- ipsec: Fix off-by-one error on max keyID (@pchaigno)

This PR is so old that it's actually already part of v1.11. Sorry about that, I didn't notice when adding the labels. The commit can be removed.

> https://github.com/cilium/cilium/pull/19893 -- docs: Fix max SPI value for IPsec key rotations (@pchaigno)
https://github.com/cilium/cilium/pull/19930 -- docs: Fix incorrect FQDN flag (@pchaigno)

Those look good to me.

**Comment by jibi** [comment]
/test-backport-1.11

**Review by pchaigno — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]
My commits LGTM.

> some conflicts: resize_cluster.sh does not exist in 1.11 

What do you mean by this? I'm confused because the file is there and properly removed by the backported commit 🤔

**Comment by jibi** [comment]
> My commits LGTM.
> 
> > some conflicts: resize_cluster.sh does not exist in 1.11
> 
> What do you mean by this? I'm confused because the file is there and properly removed by the backported commit thinking

Sorry, I probably just misread the conflict (so file was there but was different than the one in master, and so git complained about deleting it)

**Review by tommyp1ckles — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Review by brb — APPROVED** [review]
My changes LGTM, thanks.

**Review by chancez — APPROVED** [review]
peerService chart updates LGTM

**Review by tklauser — APPROVED** [review]
My change looks good, thanks Gilberto!

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
