### PR TITLE
bpf: verifier rejection fix and sock cookie cleanup

### PR DESCRIPTION
**Pull request by borkmann**
/cc @brb

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8840)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
(Setting to release blocker due to nodeport verifier error fix.)

**Review by brb — APPROVED** [review]
LGTM! Just one thing - in the case of `get_sock_cookie()` being absent, we will chose the same backend for UDP which is probably fine, as in this case we have more problems to care about.

**Comment by borkmann** [comment]
> LGTM! Just one thing - in the case of `get_sock_cookie()` being absent, we will chose the same backend for UDP which is probably fine, as in this case we have more problems to care about.

`get_sock_cookie()` is always present for the case where UDP is enabled in there.

**Comment by borkmann** [comment]
test-me-please

**Comment by joestringer** [comment]
Need to cherry pick the first change here for v1.5.

**Pull request merged**
