### PR TITLE
iptables: Fix wrong use of podCIDR in cluster node NAT exclusion

### PR DESCRIPTION
**Pull request by gandro**
By default, in the iptables-based masquerading mode, Cilium will only masquerade traffic coming from the local pod CIDR (`allocRange` in `installMasqueradeRules`). However, many IPAM modes such as ENI or multi-pool IPAM do not have a single pod CIDR. Instead, those modes rely on the `egress-masquerade-interfaces` setting, which only masquerades traffic if it leaves one of the `egress-masquerade-interfaces` devices.

Therefore, the "exclude traffic to cluster nodes from masquerade" `CILIUM_POST_nat` rule should also respect the
`egress-masquerade-interfaces` setting and not masquerade traffic regardless of the value of `allocRange` (which will not be valid in settings such as ENI mode).

This likely has not manifested in ENI mode as an issue, because in ENI mode we derive the native routing CIDR (`snatDstExclusionCIDR` in `installMasqueradeRules`) from the EC2 VPC CIDR, which usually contains the node IPs too. However, we should not rely on that, since we are adding additional non-podCIDR based IPAM modes such as multi-pool where this will not be true.

Related: #22273

**Open question:** Should this be backported to v1.13? I'm not aware of any actual bugs this has caused so far in ENI mode (see above), but we should fix it nonetheless. I'd particularly would like to have this in v1.14, since it will fix iptables-based masquerading for the newly added Multi-Pool IPAM mode in v1.14.

### CODE REVIEW

**Comment by gandro** [comment]
ci-ginko failed with LVH provisioning errors https://github.com/cilium/cilium/actions/runs/5334904372/jobs/9667395901 https://github.com/cilium/cilium/actions/runs/5334904372/jobs/9667397270

**Comment by gandro** [comment]
Louis says he does not have time to review

**Review by jibi — APPROVED** [review]

**Comment by gandro** [comment]
Marking ready to merge. `gateway-api-conformance-test` are pending since the test was renamed since I ran CI, but the previous version of it has passed: https://github.com/cilium/cilium/actions/runs/5334861019/jobs/9667235765?pr=26397

**Pull request merged**
