### PR TITLE
v1.14 Backports 2024-03-24

### PR DESCRIPTION
**Pull request by sayboras**
* [x] #31211 (@kaworu)
 * [x] #31504 (@bimmlerd)
     * :warning: minor conflict 
 * [x] #31503 (@mhofstetter)
 * [x] #31469 (@YutaroHayakawa)
    * :warning: minor conflict and require extra changes
    * 660f2c43d9ed2e02fbcd0594899826f6fd67d2cc for pkg/time packaeg
    * 04f654592897fe3d2ce0fb327376199dae507b9c for providing registry dependency

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31211 31504 31503 31469
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.14

**Comment by sayboras** [comment]
/test-backport-1.14

**Comment by sayboras** [comment]
/test-backport-1.14

**Review by YutaroHayakawa — APPROVED** [review]
Mine looks good. Thanks!

**Review by mhofstetter — APPROVED** [review]
Thanks Tam!

**Review by kaworu — APPROVED** [review]
hubble patch LGTM

**Review by viktor-kurchenko — APPROVED** [review]

**Review by bimmlerd — APPROVED** [review]

**Comment by sayboras** [comment]
Required reviews are in, CI is also green, marking this ready to merge.

**Review by squeed — APPROVED** [review]

**Pull request merged**
