### PR TITLE
test/provision: bump k8s 1.12 to 1.12.9

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8130)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Pull request merged**
