### PR TITLE
docs: Update link to be specific to Janitors

### PR DESCRIPTION
**Pull request by pchaigno**
The link for PRs waiting for Janitor reviews including all PRs waiting for a review from the person clicking the link. This pull request fixes it.

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]
Nice fix, thanks

**Comment by pchaigno** [comment]
Documentation-only change so fine to merge despite merge freeze.

**Comment by joestringer** [comment]
How do regular contributors find the old link? The idea of the old one is to make sure that you are following up on everything that your review is requested for.

**Comment by pchaigno** [comment]
But that's a different issue, no? When I perform a round of Janitoring, I only want to see the PRs that require me as a Janitor. I'll typically review the rest at a different time.

For general reviews requested from me, there's a link in https://docs.cilium.io/en/latest/contributing/development/contributing_guide/#pull-requests-review-process-for-committers.

**Comment by joestringer** [comment]
OK thanks, I had to read it a few times to find the link even once you pointed it out above. I think we could probably improve the wording to make this clearer but it's not such a big deal. I'll take a note so if it bothers me again I'll improve the docs.

**Pull request merged**
