### PR TITLE
bpf: Allow to override HOST_CC and HOST_STRIP

### PR DESCRIPTION
**Pull request by brb**
Otherwise, "make build" fails on hosts which don't have the predefined
symlink (e.g., "x86_64-linux-gnu-gcc") to "gcc".

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]
Looks reasonable to me. The surrounding cross comp env will have those ENV vars set on the call to `make`?

**Comment by jrajahalme** [comment]
> Looks reasonable to me. The surrounding cross comp env will have those ENV vars set on the call to make?

No.

This is already fixed so that cross-compilations also work in master via #19218.

**Review by jrajahalme — COMMENTED** [review]
Closed this as this was already properly fixed in master via #19218

**Pull request closed without merging**
