### PR TITLE
bpf: Provision HostPort also for case of Maglev

### LINKED ISSUE #19260: Hostport doesn’t work when using Cilium with enabling maglev
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hostport doesn’t work when using Cilium with `loadBalancer.algorithm=maglev `.
https://docs.cilium.io/en/v1.9/gettingstarted/kubeproxy-free/#maglev-consistent-hashing-beta
I reproduced this issue with kind.
```
$ kind create cluster --name=hands-on --config kind-config.yaml --image kindest/node:v1.23.0
$ kubectl -n kube-system delete ds kube-proxy
$ kubectl -n kube-system delete cm kube-proxy
$ sudo iptables-save | grep -v KUBE | sudo iptables-restore
$ helm install cilium cilium/cilium --version 1.9.13 --namespace kube-system
     --set kubeProxyReplacement=strict
     --set loadBalancer.algorithm=maglev
     --set k8sServiceHost=172.18.0.3
     --set k8sServicePort=6443
$ kubectl apply -f my-nginx.yaml 
$ curl 172.18.0.5:8080 
curl: (28) Failed to connect to 172.18.0.5 port 8080: Connection timed out
```

kind-config.yaml
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
networking:
  disableDefaultCNI: true
```
my-nginx.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
          hostPort: 8080
```

### Cilium Version

```
$ kubectl -n kube-system exec cilium-p57c6  -- cilium version
Client: 1.9.13 f2160fc 2022-02-23T13:03:31-08:00 go version go1.15.15 linux/amd64
Daemon: 1.9.13 f2160fc 2022-02-23T13:03:31-08:00 go version go1.15.15 linux/amd64
```

### Kernel Version

```
$ uname -a
Linux ubuntu-focal 5.4.0-71-generic #79-Ubuntu SMP Wed Mar 24 10:56:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-08T00:29:07Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

No response

### Relevant log output

```shell
No response
```

### Anything else?

No response

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by borkmann**
Previosly, added HostPort service will not create a map in Maglev LUT, so
access to HostPort from outside of the host will cause service backend not
found error and thus drop the request.

PR #19882 has added a quirk into the fast-path to skip Maglev LUT lookup,
but better approach would be to extend useMaglev() agent code and if needed
we could optimize the size of such maps. Expectation here anyway is that
there may not be too many HostPort services provisioned in general.

Fixes: #19260
Reported-by: Rel Zhong <relzhong@outlook.com>
Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
Link: https://github.com/cilium/cilium/pull/19882

### CODE REVIEW

**Review by brb — APPROVED** [review]
Thanks!

**Review by aspsk — APPROVED** [review]

**Comment by ysksuzuki** [comment]
@borkmann Thanks for the PR to fix #19260. One quick question. Does this PR also fix the case in which a Pod sends a request to the host port with bpf-lb-sock-hostns-only=true?

**Comment by borkmann** [comment]
> @borkmann Thanks for the PR to fix #19260. One quick question. Does this PR also fix the case in which a Pod sends a request to the host port with bpf-lb-sock-hostns-only=true?

Hasn't this been fixed via below?
```
commit fc99c0cdfa37b7da7b27405deef68dbef2185c5d
Author: Yusuke Suzuki <yusuke-suzuki@cybozu.co.jp>
Date:   Thu Dec 23 15:59:40 2021 +0900

    bpf: Fix maglev hash with hostServices.hostNamespaceOnly
    
    This fixes the bug that Cilium drops packets destined to ClusterIP.
    Cilium tries to resolve ClusterIP to Pod IP using Maglev hash when
    hostServices.hostNamespaceOnly is enabled. However, it doesn't provision
    the Maglev LUT for ClusterIP. So it drops the packet.
    This commit fixes this problem by forcing bpf_lxc to use the random
    backend selection for ClusterIP. Also, Cilium will populate the Maglev
    LUT for ClusterIP if bpf.lbExternalClusterIP is set to true so that
    the external ingress traffic connecting ClusterIP will be properly
    handled.
    
    Fixes: #17474
    
    Signed-off-by: Yusuke Suzuki <yusuke-suzuki@cybozu.co.jp>
```

**Comment by ysksuzuki** [comment]
Ah, yes, that's right. bpf-lb-sock-hostns-only is irrelevant here. With this PR, I could confirm that hostPort with Maglev works in our environment. Thanks.

**Pull request merged**
