### PR TITLE
datapath: Support enable-endpoint-routes with encapsulation

### PR DESCRIPTION
**Pull request by tgraf**
It is reasonable to support encapsulation with enable-endpoint-routes.
The existing code derived a new datapath mode when
enable-endpoint-routes was enabled, which automatically disabled
encapsulation.

### CODE REVIEW

**Review by errordeveloper — APPROVED** [review]
LGTM, but a code-owner should definitely review this as well :)

**Comment by tgraf** [comment]
test-me-please

**Review by fristonio — APPROVED** [review]
LGTM.
I saw this [draft PR](https://github.com/cilium/cilium/pull/13207/files). Tagging @mrostecki here so this doesn't get missed.

**Review by tklauser — APPROVED** [review]

**Review by vadorovsky — APPROVED** [review]
LGTM. Thanks for cc-ing me @fristonio! :rocket:

**Review by joestringer — APPROVED** [review]

**Pull request merged**
