### PR TITLE
test: Cleanup default namespace before each Context()

### PR DESCRIPTION
**Pull request by tgraf**
Many tests still deploy into the default namespace and sometimes leak
resources. This makes it difficult to reliably re-use clusters for
testing. Clean the default namespace from various deployment resources.

This is specifically not using `delete all --all` so it can be used with
the default namespace. It also doesn't touch services, serviceaccounts,
secrets, clusterroles, ... with the assumption that these can always be
safely overwritten.

### CODE REVIEW

**Comment by tgraf** [comment]
test-gke

**Review by nebril — APPROVED** [review]

**Review by errordeveloper — APPROVED** [review]

**Comment by errordeveloper** [comment]
Thanks!

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
retest-4.9

**Comment by tgraf** [comment]
This needs another fix:
```
00:18:41.540  FAIL: Unable to unmarshal string slice '"Exitcode: 0 \nStdout:\n \t \nStderr:\n \t error: the server doesn't have a resource type \"cnp\"\n\t \n"': unexpected end of JSON input
```

CiliumNetworkPolicy may be unregistered initially.

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
