### PR TITLE
all: convert package level vars to consts where possible

### PR DESCRIPTION
**Pull request by tklauser**
Also unexport them if they're not used outside the package.

Also remove unused global var RetryInterval, it's unused since commit
7ccf87701fc9 ("kvstore: New kvstore abstraction API").

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10329)

### CODE REVIEW

**Review by aanm — APPROVED** [review]
LGTM, there are at least 1 var that is changed when we are linking which is [0] so we can't move that one to `const` 
[0] https://github.com/cilium/cilium/blob/5accb0097df063d64d0cfd3be8ae0af3f91e355c/pkg/version/version.go#L38

Also, is there any lint to check for this or are you doing it sort of manually?

**Comment by tklauser** [comment]
> LGTM, there are at least 1 var that is changed when we are linking which is [0] so we can't move that one to `const`
> [0]
> 
> https://github.com/cilium/cilium/blob/5accb0097df063d64d0cfd3be8ae0af3f91e355c/pkg/version/version.go#L38

Yes, I noticed that one and intentionally didn't change it. There are also others like `pkg/envoy.RequiredEnvoyVersionSHA` and `pkg/datapath/loader.DatapathSHA` which have corresponding comments. There are also some instances where a default value needs to be tunable for tests.

> Also, is there any lint to check for this or are you doing it sort of manually?

I've done this manually (mainly looking through `git grep -A 10 "^var ("`)

**Comment by aanm** [comment]
test-me-please

**Comment by pchaigno** [comment]
> I've done this manually (mainly looking through `git grep -A 10 "^var ("`)

Maybe this would help?
```
for f in $(find . -path ./vendor -prune -o -name *.go); do \
  c=$(grep -vP "^\s*var\s*\(\s*\)" $f | awk '/^\s*var\s*\(/{flag=1}/^\s*\)/{flag=0}flag' | grep "="); \
  if [ -n "$c" ]; then echo $f; echo "$c"; fi; \
done
```
That's still 1203 lines to go through though :disappointed_relieved:

**Comment by tklauser** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
