### PR TITLE
gateway-api: Add service observable event handler

### LINKED ISSUE #33279: CI: Conformance Gateway API: TestConformance/HTTPRouteServiceTypes
## CI failure

Sample failure can be found here https://github.com/cilium/cilium/actions/runs/9597945715/job/26468107591

Sysdump: [cilium-sysdump-out-false-standard.zip](https://github.com/user-attachments/files/15914649/cilium-sysdump-out-false-standard.zip)

```
--- FAIL: TestConformance/HTTPRouteServiceTypes (0.22s)

    conformance.go:64: 2024-06-20T13:06:53.078533807Z: Applying tests/httproute-service-types.yaml
    apply.go:273: 2024-06-20T13:06:53.081184685Z: Creating service-types HTTPRoute
    apply.go:273: 2024-06-20T13:06:53.089058603Z: Creating manual-endpointslices Service
    apply.go:273: 2024-06-20T13:06:53.10111978Z: Creating manual-endpointslices-ip4 EndpointSlice
    apply.go:273: 2024-06-20T13:06:53.120610512Z: Creating manual-endpointslices-ip6 EndpointSlice
    apply.go:273: 2024-06-20T13:06:53.132755546Z: Creating headless Service
    apply.go:273: 2024-06-20T13:06:53.142643629Z: Creating headless-manual-endpointslices Service
    apply.go:273: 2024-06-20T13:06:53.15435219Z: Creating headless-manual-endpointslices-ip4 EndpointSlice
    apply.go:273: 2024-06-20T13:06:53.16147056Z: Creating headless-manual-endpointslices-ip6 EndpointSlice
    helpers.go:611: 2024-06-20T13:06:53.176343149Z: Conditions matched expectations
    helpers.go:611: 2024-06-20T13:06:53.176399614Z: Route gateway-conformance-infra/service-types Parents matched expectations
    apply.go:281: 2024-06-20T13:07:23.250019968Z: Deleting headless-manual-endpointslices-ip6 EndpointSlice
    apply.go:281: 2024-06-20T13:07:23.253846345Z: Deleting headless-manual-endpointslices-ip4 EndpointSlice
    apply.go:281: 2024-06-20T13:07:23.257820386Z: Deleting headless-manual-endpointslices Service
    apply.go:281: 2024-06-20T13:07:23.265422036Z: Deleting headless Service
    apply.go:281: 2024-06-20T13:07:23.273158986Z: Deleting manual-endpointslices-ip6 EndpointSlice
    apply.go:281: 2024-06-20T13:07:23.27741143Z: Deleting manual-endpointslices-ip4 EndpointSlice
    apply.go:281: 2024-06-20T13:07:23.284735067Z: Deleting manual-endpointslices Service
    apply.go:281: 2024-06-20T13:07:23.300149767Z: Deleting service-types HTTPRoute

    --- FAIL: TestConformance/HTTPRouteServiceTypes/1_request_to_'/headless-manual-endpointslices'_should_go_to_infra-backend-v1 (30.00s)

    httproute-service-types.go:102: 2024-06-20T13:06:53.24931143Z: Making GET request to http://172.18.255.192/headless-manual-endpointslices
    http.go:240: 2024-06-20T13:06:53.266587743Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 500 (after 1.232µs)
    http.go:240: 2024-06-20T13:06:54.272235323Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 1.018284922s)
    http.go:240: 2024-06-20T13:06:55.275170805Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 2.023703386s)
    http.go:240: 2024-06-20T13:06:56.277613233Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 3.025949513s)
    http.go:240: 2024-06-20T13:06:57.280808664Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 4.029279772s)
    http.go:240: 2024-06-20T13:06:58.283124697Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 5.031563393s)
    http.go:240: 2024-06-20T13:06:59.285531474Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 6.033946912s)
    http.go:240: 2024-06-20T13:07:00.288664715Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 7.036933041s)
    http.go:240: 2024-06-20T13:07:01.291506941Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 8.040052133s)
    http.go:240: 2024-06-20T13:07:02.29434106Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 9.042985864s)
    http.go:240: 2024-06-20T13:07:03.29677718Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 10.045217812s)
    http.go:240: 2024-06-20T13:07:04.299756431Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 11.048210776s)
    http.go:240: 2024-06-20T13:07:05.302632303Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 12.051000797s)
    http.go:240: 2024-06-20T13:07:06.305468831Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 13.053577134s)
    http.go:240: 2024-06-20T13:07:07.308530866Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 14.056896621s)
    http.go:240: 2024-06-20T13:07:08.31120104Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 15.0598282s)
    http.go:240: 2024-06-20T13:07:09.313777006Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 16.062531179s)
    http.go:240: 2024-06-20T13:07:10.316018097Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 17.064626673s)
    http.go:240: 2024-06-20T13:07:11.318585757Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 18.066884242s)
    http.go:240: 2024-06-20T13:07:12.320741974Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 19.069356235s)
    http.go:240: 2024-06-20T13:07:13.323675178Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 20.072284474s)
    http.go:240: 2024-06-20T13:07:14.326048821Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 21.074601496s)
    http.go:240: 2024-06-20T13:07:15.328204291Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 22.076837889s)
    http.go:240: 2024-06-20T13:07:16.330781475Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 23.078986183s)
    http.go:240: 2024-06-20T13:07:17.333475581Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 24.081944246s)
    http.go:240: 2024-06-20T13:07:18.336216647Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 25.085008696s)
    http.go:240: 2024-06-20T13:07:19.3383551Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 26.086994651s)
    http.go:240: 2024-06-20T13:07:20.34084504Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 27.08939512s)
    http.go:240: 2024-06-20T13:07:21.343480115Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 28.091863153s)
    http.go:240: 2024-06-20T13:07:22.346182356Z: Response expectation failed for request: {URL: {Scheme:http Opaque: User: Host:172.18.255.192 Path:/headless-manual-endpointslices RawPath: OmitHost:false ForceQuery:false RawQuery: Fragment: RawFragment:}, Host: , Protocol: HTTP, Method: GET, Headers: map[X-Echo-Set-Header:[]], UnfollowRedirect: false, Server: , CertPem: <truncated>, KeyPem: <truncated>}  not ready yet: expected status code to be 200, got 503 (after 29.09485791s)
    http.go:221: 2024-06-20T13:07:23.249937424Z: timeout while waiting after 30 attempts, 0/3 successes

┌─────────────────────────────────────────────────────────────────────────────────────────────────────┐
│  STATUS │ ELAPSED │                      PACKAGE                      │ COVER │ PASS │ FAIL │ SKIP  │
│─────────┼─────────┼───────────────────────────────────────────────────┼───────┼──────┼──────┼───────│
│  FAIL   │ 129.07s │ github.com/cilium/cilium/operator/pkg/gateway-api │  --   │ 355  │  3   │  9    │
└─────────────────────────────────────────────────────────────────────────────────────────────────────┘
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by sayboras**
This is to react based on events instead of relying on periodic sync.

Fixes: c3fcea21b6575148fe1ebb64fb9d65356607382a
Fixes: #33279

### Testing

Testing was done as per below:

- https://github.com/cilium/cilium/actions/runs/11430727353 -> 11 consecutive runs i.e. total 3x11 tests
- https://github.com/cilium/cilium/actions/runs/11431773470 -> 15 consecutive runs i.e. total 3x15 tests

### CODE REVIEW

**Review by youngnick — COMMENTED** [review]
This makes sense to me, seems like it could definitely solve that Gateway API flakiness.

**Review by pchaigno — APPROVED** [review]
Approving for CI pieces.

**Review by youngnick — APPROVED** [review]

**Pull request merged**
