### PR TITLE
Revert "node-neigh: Query once netlink for neigh discovery device"

### PR DESCRIPTION
**Pull request by joestringer**
This reverts commit 44e138c444af9988259c1f5faf2b948edbc9372a.

v1.8 branch is in a poor state in terms of CI. Try to evaluate whether this commit may be related.

### CODE REVIEW

**Comment by joestringer** [comment]
test-backport-1.8

**Comment by joestringer** [comment]
1.11-net-next hit infra issue:

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.11-net-next/1596/execution/node/125/log/

**Comment by joestringer** [comment]
test-1.11-netnext

**Comment by joestringer** [comment]
Given the failures here from CI, it's not obvious whether this PR made any change to which tests pass. At least we have a few more jobs to triage and correlate with the other CI runs.

**Comment by aanm** [comment]
Closing as the CI failures were fixed by https://github.com/cilium/cilium/pull/15750

**Pull request closed without merging**
