### PR TITLE
WIP : use correct image for k8s-gsg test

### PR DESCRIPTION
**Pull request by ianvernon**

### CODE REVIEW

**Review by aanm — APPROVED** [review]
LGTM, I've a couple commits to push regarding the kubeadm tests.

**Comment by ianvernon** [comment]
While my code changes have fixed the issue of not using the image built during the tests for the GSG, this means that for the past week ever since the multi-node tests went in, we were not actually testing the latest Cilium code in the k8s-GSG test. I am now seeing errors in the tests like the following which my patch may be revealing as it is now testing code which was previously untested:
```
time="2017-07-24T23:06:40Z" level=error msg="github.com/cilium/cilium/daemon/k8s_watcher.go:138: Failed to list *v1.NetworkPolicy: User \"system:node:k8s-2\" cannot list networkpolicies.networking.k8s.io at the cluster scope. (get networkpolicies.networking.k8s.io)" 
```

**Comment by tgraf** [comment]
> time="2017-07-24T23:06:40Z" level=error msg="github.com/cilium/cilium/daemon/k8s_watcher.go:138: Failed to list *v1.NetworkPolicy: User \"system:node:k8s-2\" cannot list networkpolicies.networking.k8s.io at the cluster scope. (get networkpolicies.networking.k8s.io)"

The verbose error messages are tracked in issue #1169

Are you running on top of the @aanm's 1.7 k8s rebase?

BTW `examples/minikube/l3_l4_policy.yaml` is still using apiVersion `extensions/v1beta1` instead of `networking.k8s.io/v1`. Needs to be fixed but we need to be careful as binaries are out there that still need v1beta1

**Comment by ianvernon** [comment]
@tgraf  yes I rebased on top of @aanm 's 1.7 k8s changes.

Should we version our RBAC files in the repo? I.e., k8s version 1.6 vs. k8s version 1.7?

Which binaries still need v1beta1? Can you clarify?

**Comment by ianvernon** [comment]
I'm closing this PR in favor of #1188 which is more efficient / cleaner.

**Pull request closed without merging**
