### PR TITLE
host based lb follow-up improvements

### LINKED ISSUE #8068: host based lb prog removal
remove stale prog from cgroupv2 if setting is on false.

### LINKED ISSUE #8396: cilium: probing for cgroup hooks
Add feature probes to bail out with a meaningful error message

### PR DESCRIPTION
**Pull request by borkmann**
- allow selecting {tcp,udp} only as an option for handling services
- clear progs if cgroup bpf hook not used
- probe kernel for support

Fixes: #8396 
Fixes: #8068 

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8475)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
CI provisioning failed.

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Provision issue:
```14:22:28      k8s2-1.10: Setting up kubectl (1.10.13-00) ...
14:22:28      k8s2-1.10: Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
14:22:30      k8s2-1.10: Setting up kubeadm (1.10.13-00) ...
14:22:32  Cancelling nested steps due to timeout
14:22:32  Sending interrupt signal to process
14:22:33  Sending interrupt signal to process
14:22:34      k8s2-1.10: Created symlink /etc/systemd/system/multi-user.target.wants/sys-fs-bpf.mount -> /etc/systemd/system/sys-fs-bpf.mount.
14:22:34  script returned exit code 255
[Pipeline] }
[Pipeline] // retry```

**Comment by borkmann** [comment]
test-me-please

**Review by brb — APPROVED** [review]
LGTM!

**Comment by borkmann** [comment]
CI provisioning issue:
```
14:59:18      k8s2-1.15: removed directory '/var/lib/kubelet/device-plugins'
14:59:18      k8s2-1.15: removed directory '/var/lib/kubelet/plugin-containers'
14:59:18      k8s2-1.15: removed directory '/var/lib/kubelet/pods'
14:59:18      k8s2-1.15: removed '/var/lib/kubelet/cpu_manager_state'
14:59:18      k8s2-1.15: removed directory '/var/lib/kubelet'
14:59:18      k8s2-1.15: [preflight] Running pre-flight checks
14:59:18      k8s2-1.15: 	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
14:59:20      k8s2-1.10: [discovery] Failed to request cluster info, will try again: [Get https://192.168.36.11:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 192.168.36.11:6443: getsockopt: no route to host]
14:59:23      k8s2-1.10: [discovery] Failed to request cluster info, will try again: [Get https://192.168.36.11:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 192.168.36.11:6443: getsockopt: no route to host]
14:59:30      k8s2-1.10: [discovery] Failed to request cluster info, will try again: [Get https://192.168.36.11:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 192.168.36.11:6443: getsockopt: no route to host]
```

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Build K8s 1.15 vm provisioning fail #13441

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Same provisioning error.

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Rebase since #8480 was merged first and bpf.sha had a conflict.

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
`k8s 1.10 net-next vm provisioning fail`, needs https://github.com/cilium/cilium/pull/8478/commits/13136206b144333d2aee0c07fdc7275686f971a0 first.

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
CI green, merging.

**Pull request merged**
