### PR TITLE
bpf: Reenable features disabled because of complexity issues

### PR DESCRIPTION
**Pull request by pchaigno**
Since we have just reduce complexity in bpf_lxc by splitting the CT lookup, we can now reenable complexity coverage of some features. First commit is for ICMP policies; second for custom calls.

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]
Looks straight-forward, thanks!

AFAIU this should only cause CI fallout in `K8sVerifier`, and those tests are green.

**Comment by pchaigno** [comment]
@nebril Runtime doesn't run any complexity tests (there's only K8sVerifier doing that).

**Pull request merged**
