### PR TITLE
v1.11 backports 2022-06-30

### PR DESCRIPTION
**Pull request by qmonnet**
* [x] #19341 -- Consider VPC's secondary CIDRs during cilium_host IP restoration (@hemanthmalla)
     * :warning: Conflict due to https://github.com/cilium/cilium/commit/16f3262b94e7 missing on v1.11
 * [ ] #19697 -- Unset `ImageReference` when updating Azure VMSS (@andrew-bulford-form3)
 * [ ] #20123 -- cilium: fix conflicting iptables-legacy and iptables-nft rules (@jrfastab)
     * First commit: minor conflict due to https://github.com/cilium/cilium/commit/17a78a2325a1 missing on v1.11
     * :warning: Second commit:
         * Regenerated all images for v1.11
         * Applied image changes for test/k8s/manifests/demo-customcalls.yaml to test/k8sT/...
 * [x] #20072 -- datapath: Create sysctl `rp_filter` overwrite config on agent init (@dylandreimerink)
     * :warning: First commit: Conflict due to https://github.com/cilium/cilium/commit/28bffa6d4b11 missing on v1.11. Addressed by removing the case where the security context is unprivileged from daemonset.yaml.
     * :warning: Second commit: Conflicts on go.mod and go.sum. One line added from running "go mod tidy".
 * [x] #20104 -- Don't unnecessarily calculate SHA256 over identity labels (@tklauser)
     * Minor conflicts: applied changes for test/k8s/cli.go to test/k8sT/cli.go instead.
 * [x] #19936 -- bug: Prevent CiliumIdentities from Being Deleted Improperly (@nathanjsweet)
     * :warning: Conflicts on install/kubernetes/cilium/templates/*/clusterrole.yaml, addressed by ignoring the changes to these files, as per https://github.com/cilium/cilium/pull/19936/files#r908819662.
 * [x] #20289 -- docs(policy): add notes on DNS/L7 policies & Cilium agent availability (@raphink)
     * Minor conflict on spelling_wordlist.txt
 * [x] #20325 -- jenkinsfiles: fix docker manifest inspect commands in GKE pipeline (@tklauser)
 * [x] #20314 -- Add ESP to firewall requirements in documentation for IPSec enabled C… (@Kikiodazie)
 * [x] #20312 -- helm: Fix cluster-id arguments in clustermesh deployment (@sayboras)
 * [ ] #20194 -- [docs] Add training and support information to Getting Help (@lizrice)
 * [x] #19379 -- add support for AKS BYOCNI (@nbusseneau)
     * Only 3 commits backported with minor conflict on README.md to regenerate, as per https://github.com/cilium/cilium/pull/19379#issuecomment-1171432668

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 19341 19697 20123 20072 20104 19936 20289 20325 20314 20312 20194 19379; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
$ make add-label BRANCH=v1.11 ISSUES=19341,19697,20123,20072,20104,19936,20289,20325,20314,20312,20194,19379
```

### CODE REVIEW

**Review by tklauser — APPROVED** [review]
My changes look good. Thanks for adjusting the test changes in 993700aa95cd8bf3e745ad030f2a314bac77072f!

**Review by sayboras — APPROVED** [review]
Looks good for my commit 💯

**Review by raphink — APPROVED** [review]
LGTM

**Review by nbusseneau — APPROVED** [review]
My commits LGTM. Thanks!

**Comment by qmonnet** [comment]
@nathanjsweet @hemanthmalla @dylandreimerink Hi! I would appreciate if you could have a look at your commits, given that there were conflicts to address.

**Comment by dylandreimerink** [comment]
My commits look good!

**Review by nathanjsweet — APPROVED** [review]
My changes look good.

**Review by joestringer — APPROVED** [review]
I just glanced over my codeowners (TIL `policy` can be requested for backport PRs..). I acknowledge the removal of `Labels.SHA256Sum()` to reduce runtime CPU usage.

**Review by hemanthmalla — APPROVED** [review]
@qmonnet Thanks for resolving the conflicts. Commit LGTM.

**Comment by qmonnet** [comment]
Thanks all! Most reviews are in, and most tests passed.

- I checked the remaining commits. They look good, backport was straightforward or (for #20123) there was trivial conflicts or images to regenerate, which does not call for additional reviews.
- I understand the ConformanceAKS test is currently broken, the failure is not related to Nicolas' changes.

So we are good to merge!

**Pull request merged**
