### PR TITLE
Use Go 1.19 atomic types and their default value

### PR DESCRIPTION
**Pull request by tklauser**
Follow-up for https://github.com/cilium/cilium/pull/27563 fixing a few missed cases.

See commits for details.

### CODE REVIEW

**Review by ti-mo — APPROVED** [review]
Thanks!

**Comment by tklauser** [comment]
@jrajahalme @nathanjsweet ping for review

**Review by jrajahalme — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Pull request merged**
