### PR TITLE
test/nat46x64: Fix out-of-bounds index error

### LINKED ISSUE #19464: CI: Cilium L4LB NAT-46x64: array index out of bounds
https://github.com/cilium/cilium/runs/6038764931?check_suite_focus=true

```
+ kubectl -n kube-system delete pod -l k8s-app=cilium
pod "cilium-84b8f" deleted
++ kubectl -n kube-system get pod -l k8s-app=cilium '-o=jsonpath={.items[0].metadata.name}'
error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].metadata.name}
	object given to jsonpath engine was:
		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}


+ CILIUM_POD_NAME=
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by pchaigno**
In the NAT46x64 workflow, on several occasions, we delete the Cilium pods and wait for them to be ready again. We do this by first retrieving the Cilium pod name then waiting for it with `kubectl wait`.

However, if we attempt to retrieve the pod name just between the deletion of the previous pod and the scheduling of the new one, it fails with the following error because no Cilium pod is present:

    ++ kubectl -n kube-system get pod -l k8s-app=cilium '-o=jsonpath={.items[0].metadata.name}'
    error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
        template was:
    	    {.items[0].metadata.name}
        object given to jsonpath engine was:
    	    map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}

We can avoid this by waiting for the daemonset rollout to be finished instead.

This pull request was tested [with the test commit 6 times](https://github.com/cilium/cilium/actions/runs/2174329586) and passed each time.

Fixes: https://github.com/cilium/cilium/issues/19464.

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]
Can't think of any reason why using the rollout feature is not better then deleting the pods directly. :+1:

**Comment by borkmann** [comment]
Thanks for fixing, like this it's fine! The `kubectl [...] delete [...]` is still present and needed there as it turned out that otherwise the changed helm options don't apply.

**Comment by pchaigno** [comment]
> Thanks for fixing, like this it's fine! The `kubectl [...] delete [...]` is still present and needed there as it turned out that otherwise the changed helm options don't apply.

Yep. We could replace it with `kubectl rollout restart`, but I think it's exactly the same in this case.

**Comment by pchaigno** [comment]
> /ci-nat46x64

Note that will trigger the master version, but I did test this change with the usual test commit:

> This pull request was tested [with the test commit 6 times](https://github.com/cilium/cilium/actions/runs/2174329586) and passed each time.

**Pull request merged**
