### PR TITLE
pkg/alignchecker: include header to avoid cgo warning

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5601)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
This was the first change I did, although I think that the approach in the other PR reduces the dependencies of the lib/common.h header which is slightly tidier from a C perspective. Either way works.

**Comment by aanm** [comment]
@joestringer let's go with yours then :+1:

**Pull request closed without merging**
