### PR TITLE
cilium, ipvlan: derive secctx from ipcache in bpf_netdev

### PR DESCRIPTION
**Pull request by borkmann**
In order to enforce policies from Cilium managed containers on remote
host allow to derive secctx from ipcache data if the packet info does
not contain any useful information.

Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6703)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Comment by borkmann** [comment]
Needs another rebase due to bpf.sha.

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
got timeout, retesting

**Comment by borkmann** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by borkmann** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by borkmann** [comment]
test-me-please

**Comment by brb** [comment]
Tested manually with ipvlan - fixes the problem when invalid identity is derived for a remote ingress traffic.

**Pull request merged**
