### PR TITLE
v1.5 backports 2019-06-21 v2

### PR DESCRIPTION
**Pull request by brb**
Supersedes #8369. Thanks @joestringer and @aanm for crafting this backport.

* #8328 -- fqdn: correctly populate Source IP and Port in `notifyOnDNSMsg` (@ianvernon)
   * Had to make minor fixups because the function was refactored out
 * #8350 -- CI: Report last seen error in CiliumPreFlightCheck (@raybejjani)
 * #8352 -- CI: Cleanup VMs and reclaim disk on job completion (@raybejjani)
 * #8361 -- pkg/metrics: re-register newStatusCollector function (@aanm)
 * #8366 -- docs: Clarify about legacy services enabled by default (@brb)
 * #8280 -- Add support for k8s 1.15 (@aanm)
 * #8351 -- Workaround for systemd 242 assigning MAC addr for virtual devices (@brb)

[ Round 2, added CI fixes]
 * #7911 
    * This was partially backported before in f7a1bd149a40f237850c91baa9b6987de6c67061, so I went back and backported the other half.
 * #8148
 * #8341 
 * #8355 

We also disabled the automatic direct node routes test:
https://github.com/cilium/cilium/commit/0c94cfd3786e3092aa68284f3e3d5576f250625a

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 7911 8148 8328 8341 8350 8352 8355 8361 8366 8280 8351; do contrib/backporting/set-labels.py $pr done 1.5; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8381)

### CODE REVIEW

**Comment by brb** [comment]
never-tell-me-the-odds

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Comment by joestringer** [comment]
From k8s upstream tests:
https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/1355/execution/node/42/log/

```
18:53:33      k8s1-1.15: docker build \
18:53:33      k8s1-1.15: 	--build-arg LOCKDEBUG=1 \
18:53:33      k8s1-1.15: 	--build-arg V= \
18:53:33      k8s1-1.15: 	--build-arg LIBNETWORK_PLUGIN= \
18:53:33      k8s1-1.15: 	-t "cilium/cilium:"latest"" .
18:59:49      k8s1-1.15: Sending build context to Docker daemon  9.247GB
18:59:49      k8s1-1.15: Step 1/19 : FROM quay.io/cilium/cilium-envoy:68c49eeb8241867829c5eab4dff13a316c71c355 as cilium-envoy
18:59:49      k8s1-1.15: 68c49eeb8241867829c5eab4dff13a316c71c355: Pulling from cilium/cilium-envoy
18:59:49      k8s1-1.15: 59fc10cbb750: Pulling fs layer
18:59:49      k8s1-1.15: 59fc10cbb750: Verifying Checksum
18:59:49      k8s1-1.15: 59fc10cbb750: Download complete
18:59:49      k8s1-1.15: 59fc10cbb750: Pull complete
18:59:49      k8s1-1.15: Digest: sha256:6579ea6d0c6ab19e07e6c07f52f1633846eadd0842db06ffe335f0cfd846c9a4
18:59:49      k8s1-1.15: Status: Downloaded newer image for quay.io/cilium/cilium-envoy:68c49eeb8241867829c5eab4dff13a316c71c355
18:59:49      k8s1-1.15:  ---> d6de2e5e111c
18:59:49      k8s1-1.15: Step 2/19 : FROM quay.io/cilium/cilium-builder:2019-05-08 as builder
18:59:49      k8s1-1.15:  ---> 9e0b4d2d855c
18:59:49      k8s1-1.15: Step 3/19 : LABEL maintainer="maintainer@cilium.io"
18:59:49      k8s1-1.15:  ---> Running in 19c94a3aac23
18:59:49      k8s1-1.15: Removing intermediate container 19c94a3aac23
18:59:49      k8s1-1.15:  ---> fbd37d6ac480
18:59:49      k8s1-1.15: Step 4/19 : WORKDIR /go/src/github.com/cilium/cilium
18:59:49      k8s1-1.15:  ---> Running in a845fcf7e887
18:59:49      k8s1-1.15: Removing intermediate container a845fcf7e887
18:59:49      k8s1-1.15:  ---> 844ef5a62190
18:59:49      k8s1-1.15: Step 5/19 : COPY . ./
19:11:57      k8s1-1.15: failed to export image: failed to set parent sha256:844ef5a62190361566480fcf029251e4eedb451737eb3238d8b51bda6e8d4859: unknown parent image ID sha256:844ef5a62190361566480fcf029251e4eedb451737eb3238d8b51bda6e8d4859
19:11:57      k8s1-1.15: Makefile:169: recipe for target 'docker-image-no-clean' failed
19:11:57      k8s1-1.15: make: *** [docker-image-no-clean] Error 1
```

**Comment by joestringer** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
test-upstream-k8s

**Review by jrajahalme — APPROVED** [review]
Reviewed all commits for sanity.

**Pull request merged**
