### PR TITLE
vagrant: Bump all Vagrant box versions except net-next

### PR DESCRIPTION
**Pull request by pchaigno**
We can't bump net-next yet because there's an issue with the vboxsf kernel module.

Other VM images are bumped mostly to include the new Go version for Cilium.

### CODE REVIEW

**Comment by pchaigno** [comment]
/test-1.16-4.9

**Comment by pchaigno** [comment]
/test-1.21-5.4

**Comment by pchaigno** [comment]
/test-1.22-4.19

**Comment by pchaigno** [comment]
/test-1.22-4.19

**Comment by pchaigno** [comment]
/test-1.16-4.9

**Comment by pchaigno** [comment]
/test-1.22-4.19

**Comment by pchaigno** [comment]
/test-1.22-4.19

**Review by sayboras — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.22-4.19

**Comment by pchaigno** [comment]
/test-1.22-4.19

**Review by christarazi — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.22-4.19

**Pull request merged**
