### PR TITLE
envoy: Move LDS/RDS server to new XDS server backend

### PR DESCRIPTION
**Pull request by rlenglet**
Use the same Envoy Node ID structure as in Istio sidecar proxy.

Define new ResourceVersionAckObserver to receive notifications of ACKs from proxies. Callback observers in Server. Implement AckingResourceMutatorWrapper to wrap a Cache and complete a Completion when a Cache update is ACKed by proxies.

Integrate the LDS/RDS server with the new XDS server backend in package pkg.envoy.xds.

Fixes: #2596

### CODE REVIEW

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Note that this branch is based off https://github.com/cilium/cilium/pull/2734, so it is blocked by that PR.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Rebased on https://github.com/cilium/cilium/pull/2734.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Rebased on #2734.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
@jrajahalme tests are passing! ⭐️
https://jenkins.cilium.io/job/Cilium-Bash-Tests/490/
https://jenkins.cilium.io/job/Cilium-Ginkgo-Tests/493/

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Pull request merged**
