### PR TITLE
docs: updating roadmap

### PR DESCRIPTION
**Pull request by aanm**
I think I might have missed some things. Lets complete this

Ping @tgraf

### CODE REVIEW

**Comment by tgraf** [comment]
@aanm I've updated the roadmap a bit. Would be great if you could add your thoughts around k8s integration and what is missing for a ready to use experience.

**Comment by tsenart** [comment]
Could these be translated into Github issues with the appropriate context?

**Comment by tgraf** [comment]
Makes sense, reference each roadmap item with github issue id. I'll take care of it after Andre has filled out the k8s related items.

**Comment by tgraf** [comment]
ping @aanm: Do you want to fill out some k8s roadmap items. Otherwise I'll push this as-is and do the github issues.

**Comment by aanm** [comment]
Haven't forgot this. Let me close #179 and #177 first so I can have a better look at what's missing.

**Comment by aanm** [comment]
@tgraf I've added a couple items, you can merge it.

**Comment by aanm** [comment]
LGTM

**Review by tgraf — APPROVED** [review]

**Pull request merged**
