### PR TITLE
v1 5 backports 19-05-14

### PR DESCRIPTION
**Pull request by jrfastab**
PRs:

#7982
#8014
#8017
#7996
#7999
#8000

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8028)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-docs-please

**Review by tgraf — APPROVED** [review]

**Comment by ianvernon** [comment]
VXLAN encryption test failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2029/

this is a known issue with the 4.9 kernel, which is used in the 1.5 CI.

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-missed-k8s

**Pull request merged**
