### PR TITLE
v1.11 backports 2023-02-12

### PR DESCRIPTION
**Pull request by pchaigno**
- [x] #23578 -- Node ID restoration (@pchaigno)
     - Trivial conflicts in first commit: needed to define ebpf.Hash.
     - Minor conflicts in the last commit: some helper functions changed name.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 23578; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Comment by pchaigno** [comment]
/test-backport-1.11

**Comment by pchaigno** [comment]
/test-backport-1.11

**Comment by pchaigno** [comment]
@tklauser @NikAleksandrov Could one of you perform a sanity check on the backported commits? (You were picked given you reviewed the upstream PR.)

**Review by NikAleksandrov — APPROVED** [review]
Backported commits look good to me

**Comment by pchaigno** [comment]
/test-1.22-4.19

**Comment by pchaigno** [comment]
"BPF checks / build datapath" failed with known CI job issue https://github.com/cilium/cilium/issues/23682. Other CI jobs are passing and the backports were reviewed. Merging.

**Pull request merged**
