### PR TITLE
backport/v1.4 2019 02 21

### PR DESCRIPTION
**Pull request by raybejjani**
* PR: 7170 -- loader: Fix nil dereference in logging statement (@joestringer) -- https://github.com/cilium/cilium/pull/7170
 * PR: 7168 -- release: fix uploadrev script to work with changes made after 1.3 (@ianvernon) -- https://github.com/cilium/cilium/pull/7168
 * PR: 7159 -- ctmap: Fix order of CtKey{4,6} struct fields (@brb) -- https://github.com/cilium/cilium/pull/7159
 * PR: 7157 -- fqdn-poller: Ensure monitor events contain all data (@raybejjani) -- https://github.com/cilium/cilium/pull/7157
 * PR: 7145 -- cilium.io/v2: set DerivativePolicies json to derivativePolicies (@aanm) -- https://github.com/cilium/cilium/pull/7145
 * PR: 7119 -- bpf: Do not account tx for CT_SERVICE (@brb) -- https://github.com/cilium/cilium/pull/7119

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7174)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-docs-please

**Comment by raybejjani** [comment]
test-missed-k8s (I can't figure this failure out https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1697/ so I'll try again)

**Comment by raybejjani** [comment]
test-missed-k8s

**Review by tgraf — APPROVED** [review]

**Pull request merged**
