### PR TITLE
v1.12 backports 2022-10-06

### PR DESCRIPTION
**Pull request by ldelossa**
* PR: 20520 -- Reference datapath metrics in feature and troubleshooting guides (@aditighag) -- https://github.com/cilium/cilium/pull/20520
   Merge with 2 commit(s) merged at: Wed, 28 Sep 2022 13:53:28 +0000!
     Branch:     master (!)                          refs/pull/20520/head
                 ----------                          -------------------
     -- Clean Merge
     v (start)
     |  22cf89a475af725a27a5b3688c2fce9dc90cf2cb via 78f9615c9040b92bcba513e60e598dfa7243c02a ("docs: Reference terminating endpoints metric in kube-proxy free guide")
     |  18ef60772318c707a72a44e32eee6ac99485c131 via 167c7680a84aae53e2b9d5445bcfe444c8642b92 ("docs: Reference conntrack metrics in troubleshooting guide")
     v (end)

 * PR: 21495 -- alibabacloud: fix incorrect instance-type reported by cilium-agent (@ArthurChiao) -- https://github.com/cilium/cilium/pull/21495
   Merge with 1 commit(s) merged at: Thu, 29 Sep 2022 21:23:18 +0000!
     Branch:     master (!)                          refs/pull/21495/head
                 ----------                          -------------------

     -- Clean Merge
     v (start)
     |  5b411027eed3c06fafc6c74f61263af630cd23f6 via 50ea506016c0372a653599ad55b8bf6dee7c96d4 ("alibabacloud: fix incorrect instance-type reported by cilium-agent")
     v (end)

 * PR: 21463 -- helm: Quote operator and etcd-operator image fields (@michi-covalent) -- https://github.com/cilium/cilium/pull/21463
   Merge with 1 commit(s) merged at: Fri, 30 Sep 2022 08:10:28 +0000!
     Branch:     master (!)                          refs/pull/21463/head
                 ----------                          -------------------
     -- Clean Merge
     v (start)
     |  5b40396716893b50616026f41f3f7d5836de61d4 via 5be1df7d7e5e357c714ccbb06baecafe6e11b23d ("helm: Quote operator and etcd-operator image fields")
     v (end)

 * PR: 21461 -- ipsec: Refactoring around `UpsertIPsecEndpoint` (@pchaigno) -- https://github.com/cilium/cilium/pull/21461
   Merge with 4 commit(s) merged at: Tue, 04 Oct 2022 10:19:54 +0000!
     Branch:     master (!)                          refs/pull/21461/head
                 ----------                          -------------------

     -- Clean Merge
     v (start)
     |  8ae15622379b2b2614eee0864c714f46b3cf66cd via c15aee58ec5d71a7eafbc6b8f8e62487501c948a ("ipsec: Simplify DeleteIPsecEndpoint parameter")
     |  3fe791905a098ca5f729933d0a5593c812dc218f via 8613c669fce11ae1847758b2d27a59485b44f0f1 ("ipsec: Rename variables in enableIPsec")
     |  91fdc20faa8496fc57b157db87aad760418329df via 07c03cbebe2249d09d231e501932c529341de8d5 ("ipsec: New arguments for UpsertIPsecEndpoint")
     |  645da8065170baf7933c18b1b565e02757416e3a via 23051acd0a85d503216aea43bb1649794552ec9f ("ipsec: Simplify UpsertIPsecEndpoint CIDR arguments")
     v (end)

 * PR: 21497 -- bugtool: Fix pprof default ports (@pippolo84) -- https://github.com/cilium/cilium/pull/21497
   Merge with 1 commit(s) merged at: Tue, 04 Oct 2022 10:25:59 +0000!
     Branch:     master (!)                          refs/pull/21497/head
                 ----------                          -------------------

    -- Merge Conflict - daemon/cmd/daemon_main.go, operator/flags.go
    -- @pippolo84 - Please confirm changes look good.
     v (start)
     |  b33adeb6f88701979d98095149d6ecb359dc8812 via 9e1917d470cfbc670dcd0f05bc3824c9ef983079 ("bugtool: Fix pprof default ports")
     v (end)

 * PR: 21565 -- ipcache: Fix metadata access from CIDR allocation (@joestringer) -- https://github.com/cilium/cilium/pull/21565
   Merge with 1 commit(s) merged at: Tue, 04 Oct 2022 22:40:54 +0000!
     Branch:     master (!)                          refs/pull/21565/head
                 ----------                          -------------------

    -- Merge Conflict - skipped due to complexity
    -- @joestringer - does not merge cleanly and not sure context for change.
     v (start)
     |  021ea42e6f8cfbb139286db88c4d5e2f84dac93f via 3f27143b048479157c24d2e8a07791ea77f5e8d1 ("ipcache: Fix metadata access from CIDR allocation")
     v (end)

 * PR: 21577 -- contrib: avoid reviews from non-collaborators (@bimmlerd) -- https://github.com/cilium/cilium/pull/21577
   Merge with 1 commit(s) merged at: Wed, 05 Oct 2022 09:31:54 +0000!
     Branch:     master (!)                          refs/pull/21577/head
                 ----------                          -------------------

    -- Clean Merge
     v (start)
     |  5520be196693d7fce495a91fbf21e3838d5e7343 via 7a7137c5e27d6d6e5a87311205d3a00fd059c67b ("contrib: avoid reviews from non-collaborators")
     v (end)

 * PR: 21588 -- test: fix up the number of pods in DemoDaemonSet (@julianwiedmann) -- https://github.com/cilium/cilium/pull/21588
   Merge with 1 commit(s) merged at: Wed, 05 Oct 2022 17:19:48 +0000!
     Branch:     master (!)                          refs/pull/21588/head
                 ----------                          -------------------
    -- Clean Merge
     v (start)
     |  1019e700a3eba4f8372c7449a7b231a0e3c7c606 via ab5d9640f3b99754f5cb9b91dfb5c4379f86e94f ("test: fix up the number of pods in DemoDaemonSet")
     v (end)

 * PR: 21444 -- plugins/cni: wait for AWS to drop its CNI configuration file (@squeed) -- https://github.com/cilium/cilium/pull/21444
   Merge with 1 commit(s) merged at: Thu, 06 Oct 2022 00:16:55 +0000!
     Branch:     master (!)                          refs/pull/21444/head
                 ----------                          -------------------
    -- Clean Merge
     v (start)
     |  d45999d5bded78590c19a670601f9c486dc0cba0 via 8b55f3fba8f9a682d0cfe749bc40213140e55ad2 ("plugins/cni: wait for AWS to drop its CNI configuration file")
     v (end)

```upstream-prs
$ for pr in 21444 21588 21577 21497 21461 21463 21495 20520; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Comment by michi-covalent** [comment]
✅ ack on https://github.com/cilium/cilium/pull/21610/commits/a2534e4092f644819eaf64486478794223f167c8 thanks @ldelossa ! ❤️

**Review by michi-covalent — APPROVED** [review]

**Comment by ldelossa** [comment]
@jibi looks like I left a git diff marker in the commit, will fix momentarily.

**Comment by ldelossa** [comment]
> [force-pushed](https://github.com/cilium/cilium/compare/945019a1f6fe4c242c0e958ec6f2864d07361a44..80a76e5938a95e72932200b5ee6e5185d016ccda) the pr/v1.12-backport-2022-10-06 branch from[ 945019a ](https://github.com/cilium/cilium/commit/945019a1f6fe4c242c0e958ec6f2864d07361a44)to[ 80a76e5 ](https://github.com/cilium/cilium/commit/80a76e5938a95e72932200b5ee6e5185d016ccda)40 seconds ago 

@jibi ^ force push removed git diff markr.

**Comment by ldelossa** [comment]
@joestringer ah, i think i may have deleted the original generated file the script generates. I kept my own copy and used that as input to the branch creation script.

**Comment by joestringer** [comment]
@ldelossa I see. The general format of the description doesn't matter to me, but either way please ensure that the PR description has that `upstream-prs` snippet :pray:

**Comment by ldelossa** [comment]
Yup will do.

**Review by bimmlerd — APPROVED** [review]
4c1a0e2d4dab240acda6ac02dda4257fb19bf9df LGTM, thanks!

**Review by julianwiedmann — APPROVED** [review]

**Review by pippolo84 — APPROVED** [review]
https://github.com/cilium/cilium/pull/21610/commits/788f7e848294bce55a5f056e2c081c12ce0059ab looks fine, thanks! :100:

**Review by squeed — APPROVED** [review]

**Comment by squeed** [comment]
/ci-awscni-1.12

**Comment by squeed** [comment]
/ci-aks-1.12

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Comment by squeed** [comment]
ci-awscni and ci-aks passed all good for my commit!

**Comment by squeed** [comment]
/ci-eks-1.12

**Comment by pchaigno** [comment]
@squeed These will all get tested as part of CI once Louis triggers it.

**Comment by ldelossa** [comment]
@joestringer fixed `upstream` code block. :heavy_check_mark:

**Comment by sayboras** [comment]
dropped https://github.com/cilium/cilium/pull/21499 as per offline discussion.

**Comment by sayboras** [comment]
Due to permission to forked repo, replace this by https://github.com/cilium/cilium/pull/21631

**Pull request closed without merging**
