### PR TITLE
ci-e2e: Use kernel 6.1 instead of 6.0

### PR DESCRIPTION
**Pull request by brb**
The former is the long term stable - https://kernel.org

### CODE REVIEW

**Comment by brb** [comment]
Unfortunately legit failure after changing kernel from 6.0 to 6.1 on the '6' config:
```
2023-11-23T08:51:43.413001842Z level=fatal msg="Failed to compile XDP program" error="attaching XDP program to interface eth0: loading eBPF collection into the kernel: program tail_nodeport_nat_ingress_ipv6: load program: argument list too long: BPF program is too large. Processed 1000001 insn (863 line(s) omitted)" subsys=datapath-loader
```

```
         - name: '6'
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: '6.1-20231026.065108'
            kube-proxy: 'none'
            kpr: 'true'
            tunnel: 'vxlan'
            lb-mode: 'snat'
            egress-gateway: 'true'
            host-fw: 'true'
            lb-acceleration: 'testing-only'
            ingress-controller: 'true'
```

**Comment by julianwiedmann** [comment]
@brb want to give this another try, now that https://github.com/cilium/cilium/pull/29377 is in?

Stable backports, all the way back? ugh ...

**Comment by brb** [comment]
@julianwiedmann Cool, resolved!

> Stable backports, all the way back? ugh ...

Any concerns about it?

**Comment by julianwiedmann** [comment]
> > Stable backports, all the way back? ugh ...
> 
> Any concerns about it?

Let's see which ones will need https://github.com/cilium/cilium/pull/29377, no point in worrying about it in advance :crossed_fingers: .

**Review by nbusseneau — APPROVED** [review]

**Comment by julianwiedmann** [comment]
updating the labels, as

* The workflows in `v1.12` have no reference to 6.0 kernels.
* The parts in `v1.13` have been addressed by https://github.com/cilium/cilium/pull/30812.
* The parts in `v1.14` were updated by https://github.com/cilium/cilium/pull/30653. But looks like we applied a `s/6.0/6.6` instead of `s/6.0/6.1`. @lmb got a moment to restore harmony across the different branches? :pray:

**Pull request merged**
