### PR TITLE
v1.9 backports 2020-11-05

### PR DESCRIPTION
**Pull request by tklauser**
* #13857 -- Remove the beta status note for Hubble Relay/UI (@michi-covalent)
 * #13847 -- test: extend XDP coverage for Maglev (@borkmann)
 * #13862 -- vagrant: bump bpf-next vagrant box version (@borkmann)
 * #13860 -- examples: Fix grafana and prometheus (@nathanjsweet)
 * #13855 -- docs: Update for clustermesh-apiserver (@joestringer)
 * #13844 -- option: avoid error on dynamic NAT table size if CT map sizes are static (@tklauser)
 * #13837 -- helm: Fix format issue for logOptions in ConfigMap (@sayboras)
 * #13825 -- Improve and expand on documentation for the API rate limiter (@christarazi)
 * #13820 -- k8s: Only wait for the needed CRDs (@jrajahalme)
 * #13859 -- bpf: fix session affinity timeout test flake (@fristonio)
 * #13806 -- docs: GKE setup example with encryption and direct routing (@ti-mo)
 * #13874 -- 1.9 Upgrade guide misc updates (@kkourt)
 * #13885 -- docs: Mark Flannel (beta) integration as non-preferred/deprecated (@andreek)
 * #13895 -- build: don't disable compiler optimizations and inlining on unstripped builds (@tklauser)
 * #13897 -- helm: Generate docs in default target (@joestringer)
 * #13892 -- release: add script to check presence of docker images (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13857 13847 13862 13860 13855 13844 13837 13825 13820 13859 13806 13874 13885 13895 13897 13892; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by tklauser** [comment]
test-backport-1.9

**Review by sayboras — APPROVED** [review]
Looks good for my commit :100:

**Comment by tklauser** [comment]
The checkpatch GH action consistently fails on backport PRs due to the formatting of the upstream commit in the commit message. Sent #13904 to disable the check on `v1.9`.

**Review by aanm — APPROVED** [review]
looks good for my changes.

**Review by fristonio — APPROVED** [review]
LGTM for my changes

**Comment by tklauser** [comment]
retest-4.19

**Review by joestringer — APPROVED** [review]
My commits LGTM

**Comment by joestringer** [comment]
@tklauser when identifying a flaky CI run, please also look for a corresponding flake issue and link it or file a new one. If we do not track flaky CI failures, then in future we will not be able to understand whether the failure has happened before or whether it's new, which is one of the pieces of data we use to gauge whether the CI failure should block the PR merge (and subsequently, release). Furthermore, with issues tracking the flakes, we can track / prioritize / investigate and make progress to make CI more stable over time.

For the one linked above (https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/3678/), I found the corresponding issue https://github.com/cilium/cilium/issues/13552 with the same failure style. Seems like it's new in 1.9 cycle, but not new in this backport PR.

**Review by christarazi — APPROVED** [review]
LGTM for my commits

**Review by kkourt — APPROVED** [review]

**Review by ti-mo — APPROVED** [review]
Thanks, LGTM!

**Pull request merged**
