### PR TITLE
iptables: Simplify proxy rules removing ingress/egress flag

### PR DESCRIPTION
**Pull request by pippolo84**
The proxy rules installed by the iptables manager are the same regardless of the traffic direction (ingress or egress). So, there is no point in having separate functions to install them, nor passing a boolean flag indicating the traffic direction of the proxy.

The relevant interfaces and mock implementations are updated accordingly.

### CODE REVIEW

**Review by dylandreimerink — APPROVED** [review]

**Comment by pippolo84** [comment]
Gentle ping to @tommyp1ckles for the review :pray:

**Review by tommyp1ckles — APPROVED** [review]

**Pull request merged**
