### PR TITLE
Fix scalability of CNP status updates

### PR DESCRIPTION
**Pull request by tgraf**
The existing CNP status update controller is applying an aggressive retry behavior with no exponential backoff.

CNP updates are processed in parallel by all agents in the cluster. Typically at the same time. Introduce an exponential backoff with jitter that also depends on the size of the cluster to avoid overloading the apiserver

```
    Distribution:
    nodes      4        16       128       512      1024      2048
    1:      2.6s      5.5s      8.1s        9s      9.9s     12.9s
    2:      1.9s      4.2s      6.3s     11.9s     17.6s     26.2s
    3:        4s     10.4s     15.7s     26.7s     20.7s     23.3s
    4:       18s     12.1s     19.7s       40s    1m6.3s   1m46.3s
    5:     16.2s     28.9s   1m58.2s     46.2s      2m0s      2m0s
    6:     54.7s      7.9s     53.3s      2m0s      2m0s     45.8s
    7:   1m55.5s     22.8s      2m0s      2m0s      2m0s      2m0s
    8:   1m45.8s   1m36.7s      2m0s      2m0s      2m0s      2m0s
```

This also improves the error reporting via controller errors. Only non-temporary errors are pushed down and exposed via controller errors. This means that if the Update() call to the apiserver returns, we will retry without exposing this to the controller. This should provide better visibility in permanent vs temporary errors and allow to treat controller failures seriously.

Finally, a metric is introduced to track the latency of CNP status update as well as the number of required attempts.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7349)

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

[etcd-operator did not come up, debugging...]

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
CI failure is most likely related to a bug which prevented the wait for the endpoint readiness to be retried. This eventually resulted in https://github.com/cilium/cilium/issues/7363

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
buildqueue unit test failure

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Pull request merged**
