### PR TITLE
v1.8 backports 2020-11-30

### PR DESCRIPTION
**Pull request by aanm**
* #13923 -- doc: Link hubble metrics to L7 visibility (@mandarjog)
 * #14112 -- endpoint: Add DebugPolicy option (@jrajahalme)
 * #14145 -- bugtool: Add lsmod (@joestringer)
 * #14182 -- cilium: disable bind-protection in kube-proxy free probe mode (@borkmann)
 * #14090 -- hubble/parser: Always preserve datapath numeric identity (@gandro)
 * #14171 -- daemon: Fix netns usage in kpr privileged unit tests (@brb)
 * #14110 -- fqdn: Delay ipcache upserts until policies have been updated (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13923 14112 14145 14182 14090 14171 14110; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Review by gandro — APPROVED** [review]
LGTM for Hubble-related changes.

**Comment by aanm** [comment]
test-backport-1.8

**Comment by brb** [comment]
@aanm You probably want to exclude #14044 (see https://github.com/cilium/cilium/pull/14059#issuecomment-734247320).

**Comment by aanm** [comment]
> @aanm You probably want to exclude #14044 (see [#14059 (comment)](https://github.com/cilium/cilium/pull/14059#issuecomment-734247320)).

Thanks, I forgot about it

**Comment by aanm** [comment]
test-backport-1.8

**Comment by aanm** [comment]
test-backport-1.8

**Review by joestringer — APPROVED** [review]
Backport of my commit is trivially correct :+1:

**Comment by joestringer** [comment]
Several RuntimeFQDNPolicies test failures, suggests something is off with the backport of PR #14110. I looked around and it seems like the v1.7 and master versions hit no such issue so it's presumably either some missing commit or some unintended change specific to this backport:

https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/2802/

```
Cannot access to allowed DNS name "http://world1.cilium.test"
Expected command: docker exec -i  app1 curl --path-as-is -s  -D /dev/stderr --output /dev/stderr -w '%{http_code}' --connect-timeout 5 http://world1.cilium.test 
To succeed, but it failed:
Exitcode: 28 
Err: Process exited with status 28
Stdout:
 	 000
Stderr:
```

**Comment by jrajahalme** [comment]
Looks like the failure is releted to DNS poller which was removed in 1.9 (and master), so the upstream commit misses code that is needed. It is in v1.7 commits, found this via visual comparison of the commits:

This PR:
```
	_, _, err := poller.ruleManager.UpdateGenerateDNS(ctx, lookupTime, updatedDNSIPs)
	return err
```
v1.7:
```
	_, newlyAllocatedIdentities, err := poller.ruleManager.UpdateGenerateDNS(ctx, lookupTime, updatedDNSIPs)
	if err == nil {
		ipcache.UpsertGeneratedIdentities(newlyAllocatedIdentities)
	}
```

Looks like this happened during manual fixing of compile failures after backports were cherry-picked. I'll push a fix ASAP.

**Comment by jrajahalme** [comment]
test-backport-1.8

**Comment by joestringer** [comment]
Fixed trivial build conflict, re-running CI.

**Comment by joestringer** [comment]
test-backport-1.8

**Review by jrajahalme — APPROVED** [review]

**Comment by aanm** [comment]
retest-runtime

**Comment by jrajahalme** [comment]
retest-runtime

**Comment by jrajahalme** [comment]
Restarted runtime tests due to provisioning fail.

**Pull request merged**
