### PR TITLE
v1.12 backports 2023-01-13 (replacement)

### PR DESCRIPTION
**Pull request by ldelossa**
* #20619 -- test/k8s: remove l7_demos test (@tklauser)
 * #21267 -- Adding/fixing DNSProxy metrics (@rahulkjoshi)
 * #22620 -- Update Cilium install guide about EKS aws-node DaemonSet potential connectivity problem on uninstall (@NikAleksandrov)
 * #22821 -- Add sphinxcontrib-googleanalytics to doc requirements (@chalin)
 * #22794 -- bpf: nodeport: wire up trace aggregation for rev_nodeport_lb6() (@julianwiedmann)
  -> please double-check if this makes sense, rev_nodeport_lb6 changed quite a bit
 * #22807 -- Update Layer 7 Protocol Visibility Document. (@obaranov1)
 * #22745 -- Improve fqdn events logging management (@pippolo84)
 * #22678 -- bpf: nodeport: fix tracing for handle_nat_fwd() (@julianwiedmann)
 * #22930 -- Fix missing node neigh metric for counting arping requests (@christarazi)
 * #22985 -- datapath: Fix L7 ingress with XDP (@brb)
 * #22884 -- Fix crash of CES queue delay metric when CESTracker is nil (@dlapcevic)
 * #22977 -- iptables: skip reverse IP lookup (@jibi)
 * #22972 -- bpf: Fix LB loopback path with ingress policy (@aditighag)
 * #23018 -- bpf: test: fix xdp_lb4_forward_to_other_node test (@julianwiedmann)
 * #23037 -- ctmap: fix-up host_local flag in the DSR NAT entry for GC test (@julianwiedmann)
 * #22962 -- clustermesh: Add missing brackets of etcd option (@YutaroHayakawa)
 * #21857 -- test: net_policies: delete custom IP routes after test completion (@julianwiedmann)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20619 21267 22620 22821 22794 22807 22745 22678 22930 22985 22884 22977 22972 23018 23037 22962 21857; do contrib/backporting/set-labels.py $pr done 1.12; done
```

---

PRs dropped from this round:
 * #22928 -- CODEOWNERS: Cover test/bpf_tests by sig-datapath (@christarazi)
  -> dropped, maintenance branches have different CODEOWNERS
 * #21768 -- Endpoint/CEP Ownership Fix (@tommyp1ckles)
  -> relies on missing node.GetCiliumEndpointNodeIP()
 * #22810 -- nodeport: fix CT accounting in revDNAT path (@julianwiedmann)
  -> generated quite a large diff I wasn't sure what to do with
 * #22768 -- Make cilium pprof listen address configurable (@chancez)
  -> can probably be made to fit with some work from the author; do we really want/need to backport this?
 * #22220 -- Enable Google Analytics 4 (@chalin)
 * #21980 -- datapath: Fix L7 reply to outside when endpoint routes disabled (@brb)

Manual fix added to skip `check-missing-tags-in-tests.sh` in v1.12 branch due to 7435adb50f.
Manual modified cherry-pick of https://github.com/cilium/cilium/pull/22980 to avoid eBPF unit test failures
Manual fix added to to avoid eBPF unit test failures: https://github.com/cilium/cilium/pull/23092#issuecomment-1396191886

### CODE REVIEW

**Comment by joestringer** [comment]
Where did the extra couple of commits come from? I might be missing it but I don't see the PR reference in the PR summary, and the commits don't have the `upstream commit xxxx` bit in them which is usually added if cherrypicks are performed using the `contrib/backporting/cherry-pick` script. I was going to just quickly eyeball those changes vs. the original for a quick sanity check.

Assuming that's fine and CI is passing, this should be OK to merge - the original PR already received reviews from most of the authors of the original PRs.

**Comment by ldelossa** [comment]
@joestringer there should be two additional commits. One is a modified cherry-pick from upstream, which I can create a link too (tho this upstream commit has no 'needs backport' label, so thought this wasn't necessary). 

the second commit is manually done for this PR, which bumps cilium/ebpf to v0.10.0 to avoid a breaking kernel change.

**Comment by joestringer** [comment]
I see. For the first one, it would help to see the original too, to make review easier. If that PR wasn't marked for backport, maybe it should have been in order to help fix CI stability(?), though I recognize also that sometimes a PR may have some commits that need backport + some that don't.

Typically we'll try to avoid custom changes in backports, mainly because the backports were already reviewed so it's more just an opportunity for the author to do a sanity check + make sure there weren't known incompatibilities in the older version. For that case, typically I would suggest something like nominating https://github.com/cilium/cilium/pull/21521 for backport and then backporting that, rather than manually bumping the library version in the branch. In general changes flow into master first where we have a higher bar of scrutiny + review, then we nominate backports and at that point the core idea of the change should be OK.

That said, the ebpf library bump seems innocent enough. I don't know if that's bumped to v0.10.0 on master yet but I presume that will be taken care of at some point since it seems like we have bots to arrange those activities now.

**Comment by ldelossa** [comment]
@joestringer I did talk to @ti-mo out of bounds about this issue, and the bump to v0.10.0 was suggested. However, it probably does make sense to make that change flow from `master` down. 

I could open a PR against master to bump cilium/ebpf as well.

**Comment by joestringer** [comment]
Yeah I think from a release perspective, if we introduce a change like bumping the cilium/ebpf library in this PR, then it won't show up in the release notes. This is because release note generation work by going through backport PRs like this, looking for the `upstream-prs` section in the description, then iterating the PRs listed there and pulling the `release-note` section in the description of those original PRs. Without the original PR, there's no release note to pull.

Functionally it's not a big deal to bump the library here and in master separately, since we'll probably want the newer version in both places, it can just make it harder to search & propagate information about the changes in each branch / release. We simply assume that everything flows into master first and then into branches.

**Comment by ti-mo** [comment]
@joestringer I manually added 0367f47 to the PR since it doesn't have an upstream equivalent. iirc this is a common thing to do (like CODEOWNERS being recently changed on the maintenance branches only) for fixes that can/should not exist on master.

Small update on the lib bump: we'll be putting that change through master first because it also requires a patch to coverbee, which also needs its dependency bumped. @dylandreimerink is polishing and will cut a new coverbee version. When it lands on master, I'll backport lib+coverbee to 1.12 in a separate PR as to not grow this one any further. After a rebase, this PR should pass.

**Review by michi-covalent — APPROVED** [review]

**Comment by ldelossa** [comment]
We needed to cherry-pick: https://github.com/cilium/cilium/pull/23220/commits/39cbafc3f3ecbca862ae7e5b82022ad1967e63c0 to unblock these tests. 

Further more, I added a commit on top of this cherry pick which flips the github workflow targets to run the workflow files within this PR. 

We'll perform the rest of the tests like this, and it all pass, I'll make a note of this, chop off the top most commit, and merge this. 

Exciting stuff.

**Comment by michi-covalent** [comment]
looks like https://github.com/cilium/cilium/actions/runs/3971493764 is a legitimate failure:
```
unknown flag: --backend-weights
```
https://github.com/cilium/cilium/actions/runs/3971493764/jobs/6808454023#step:10:882

**Comment by joestringer** [comment]
/test-backport-1.13

**Comment by joestringer** [comment]
/test-backport-1.12

**Comment by joestringer** [comment]
Sorry, I triggered v1.13 jobs accidentally so there will be many empty failures. It may be worth closing + reopening and then specifically triggering the right job once more, just to clear out all of the irrelevant test jobs from the `/test` and `/test-backport-1.13` commands run earlier.

**Comment by ldelossa** [comment]
@joestringer no problem. Closing this only to open it right back up.

**Pull request closed without merging**
