### PR TITLE
Use k8s node's IP address to determine MTU, when k8s node is available

### LINKED ISSUE #14339: Cilium is using wrong interface for MTU detection
## Bug report

We've deployed Cilium 1.9.1 via Helm in a bare metal Kubernetes 1.19.4 cluster running MetalLB as a load balancer. It's a 4-node cluster (one control + 3 worker nodes); each node runs Ubuntu 20.04.1 and has two primary interfaces, one for external connectivity and one to talk to our storage backend. These instances are provisioned using Ubuntu MaaS and the interfaces are aliased using netplan for consistency, named `external` and `storage` respectively.

What we're noticing is that Cilium appears to default to the storage interface rather than the external interface. The tell is that the storage interface has an MTU size of 9000 vs the default 1500 for the external interface; after the cluster is stood up and Cilium and MetalLB are running, any new pods created have an MTU size of 9000 on their primary interface:

```
~ > kubectl exec -it alpine-deployment-5dbfb45ff5-jpbtn -- sh
/ # ifconfig
eth0      Link encap:Ethernet  HWaddr FE:DA:85:63:64:91
          inet addr:10.0.3.87  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:9000  Metric:1
          RX packets:13 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1006 (1006.0 B)  TX bytes:0 (0.0 B)
```

This suggests that Cilium is not respecting the Helm setting `devices: "external"`.

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.9.1 975b66772 2020-12-04T18:16:09+01:00 go version go1.15.5 linux/amd64
Daemon: 1.9.1 975b66772 2020-12-04T18:16:09+01:00 go version go1.15.5 linux/amd64
```

- Kernel version (run `uname -a`)
`Linux k8s01 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
ubuntu@k8s01:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Link to relevant artifacts (policies, deployments scripts, ...)

`values.yaml`:
```
containerRuntime:
  integration: "auto"
policyEnforcementMode: "never"
devices: "external"
etcd:
  enabled: true
  ssl: true
  endpoints:
  - "https://172.18.73.31:2379"
hubble:
  enabled: true
  listenAddress: ":4244"
  metrics:
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - http
  relay:
    enabled: true
  ui:
    enabled: true
```
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```
https://novacoast-my.sharepoint.com/:u:/p/sboynton/Ea_SbyQeXKBKrLlb-JKOknEBtPHScZxG54JTEhO229wAlw?e=oCHRbG

**How to reproduce the issue**

1. Build cluster nodes with two interfaces, one configured for jumbo frames (e.g. MTU size of 9000)
2. Standardize interface names using e.g. netplan
3. Provision nodes as kubernetes nodes
4. Install Cilium via Helm with `devices: "external"`
5. Check MTU size of any new pods to see if they have inherited settings from the external or storage interface

### PR DESCRIPTION
**Pull request by nnbu**
cilium may not pick the MTU of expected interface, when there are multiple interfaces present

Today, cilium does not pick the MTU based on k8s node IPs. When there are multiple interfaces present, there is always chance cilium picks the wrong MTU. The fix addresses this issue by calling k8s.WaitForNodeInformation() well before the MTU is chosen. k8s.WaitForNodeInformation() picks up the k8s node's IP address and set it using node.GetExternalIPv4(). So, now mtu.NewConfiguration() gets this ip addresses as it its argument. So, MTU of the interface whose IP addresses is passed is picked up. This makes sure that the right MTU is deterministically picked up.

Fixes: #14339

```release-note
Fixes a bug where cilium may not pick the MTU of expected interface, when there are multiple interfaces present
```
Signed-off-by:  Nishant Burte <nishantburte@gmail.com>

### CODE REVIEW

**Review by joestringer — CHANGES_REQUESTED** [review]
This looks like it could potentially block the daemon startup process for an extended period of time depending on apiserver availability, and in particular, block the `bootstrapFQDN()` which is critical to get up and running ASAP on Cilium restart (see https://github.com/cilium/cilium/pull/12964)

**Comment by joestringer** [comment]
One more comment on the release note, it is currently:

> cilium may not pick the MTU of expected interface, when there are multiple interfaces present

This sounds like a statement of current behaviour. When someone reads the release note and reads this comment, it sounds like this is a "feature" to not pick the MTU of expected interface. This is confusing.

Please consider instead starting with a verb and stating how this change modifies the behaviour of Cilium, for example:

> Fix bug where cilium may not pick the MTU of expected interface, when there are multiple interfaces present

**Comment by nishantburte** [comment]
@joestringer Did you mean to say the current fix will cause the delay in calling bootstrapFQDN() ? I see that bootstrapFQDN() is called at the end of NewDaemon(). The proposed fix moved the block of code which is already before bootstrapFQDN() upwards. So, it is effectively not affecting the dependency graph from bootstrapFQDN()'s point of view.
Could you please help me understand your point better?

**Review by christarazi — CHANGES_REQUESTED** [review]
The code as-is will break cluster-pool IPAM mode. Taking a look inside `k8s.WaitForNodeInformation()`, there's specific logic for cluster-pool IPAM mode where we need to wait for the creation / existence of the CiliumNode CR. In new installs, the creation will take place during the node discovery phase (immediately before where `k8s.WaitForNodeInformation()` was). Another wrinkle to that is the CiliumNode CRD will need to be created and waited on which also happens immediately before the node discovery phase. Note that the CRDs are created by cilium-operator.

Essentially, to make this work, all of the K8s initialization phase will need to be moved up as well. This is assuming that this doesn't disrupt any other dependency chains.

**Comment by liuyuan10** [comment]
@nishantburte you probably are looking at older code. bootstrapFQDN is required to be run before k8s initialization.

@joestringer Thanks for the pointer. I don't fully understand the context for that change. But it does claim this bootstrapFQDN must be done before k8s. So a walkaround can be instead of moving k8s node init upwards, we can also move MTU detection downwards. Just need to make sure MTU is not used before hand.

**Pull request closed without merging**
