### PR TITLE
envoy: Update generated protobufs.

### PR DESCRIPTION
**Pull request by jrajahalme**
Update changed API protobuf generated files.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5543)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]

**Comment by rlenglet** [comment]
CI failure is unrelated:
```
00:18:33.004 VBoxManage: error: Appliance import failed
00:18:33.004 VBoxManage: error: Could not create the imported medium '/root/VirtualBox VMs/ubuntu-18.04.1-amd64-114_1536805217642_50414/ubuntu-18.04.1-amd64-114-disk001.vmdk'.
00:18:33.004 VBoxManage: error: VMDK: cannot write allocated data block in '/root/VirtualBox VMs/ubuntu-18.04.1-amd64-114_1536805217642_50414/ubuntu-18.04.1-amd64-114-disk001.vmdk' (VERR_DISK_FULL)
00:18:33.004 VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
00:18:33.004 VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 886 of file VBoxManageAppliance.cpp
```

**Comment by rlenglet** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Same CI issue with a full disk again...

**Comment by jrajahalme** [comment]
test-me-please

**Pull request merged**
