### PR TITLE
ci-datapath: Use QUAY_ORGANIZATION_DEV for Quay org name

### PR DESCRIPTION
**Pull request by michi-covalent**
Use QUAY_ORGANIZATION_DEV environment variable as Quay organization name to be consistent with other workflow files.

### CODE REVIEW

**Comment by michi-covalent** [comment]
✅ `ci-datapath` passed: https://github.com/cilium/cilium/actions/runs/4768548180/jobs/8477988744?pr=25052

removing the temporary commit and marking it ready for review.

**Review by julianwiedmann — APPROVED** [review]
copy & paste from similar workflows checks out :100:

**Review by sayboras — APPROVED** [review]

**Review by viktor-kurchenko — APPROVED** [review]
LGTM.

**Pull request merged**
