### PR TITLE
v1.15 backports 2024-05-08

### PR DESCRIPTION
**Pull request by christarazi**
- [x] #31605 -- Fix various bugs related to restart of StatefulSet pods that may result in connectivity issues (@christarazi)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
31605
```

### CODE REVIEW

**Comment by christarazi** [comment]
/test-backport-1.15

**Comment by nebril** [comment]
/test-backport-1.15

**Comment by nebril** [comment]
/test-backport-1.15

**Review by nebril — APPROVED** [review]

**Review by ldelossa — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]
LGTM for API

**Pull request merged**
