### PR TITLE
images: Bump Hubble CLI to v0.9.0

### PR DESCRIPTION
**Pull request by gandro**
This bumps the Hubble CLI to the recently released version 0.9.0. Hubble
CLI v0.9.0 has been released to include the Hubble protobuf API changes
present in Cilium v1.11-rc3 and thus is intended to be bundled with the
final Cilium v1.11 release.

Due to the cyclic dependency between Hubble CLI and Cilium, this PR can
only be done after the feature freeze and thus needs to be backported to v1.11.

### CODE REVIEW

**Comment by gandro** [comment]
Test triage (will edit this post as more tests finish)

- ConformanceAKS seems to have an issue with tunnelfront, i.e. `kubectl exec` times out for all nodes https://github.com/cilium/cilium/runs/4379812393?check_suite_focus=true - looks like an infrastructure issue, but I have not found an issue for this yet.

**Review by qmonnet — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Comment by gandro** [comment]
/test-1.16-netnext

**Comment by gandro** [comment]
/test-1.22-4.19

**Comment by gandro** [comment]
/test-1.23-4.9

**Comment by gandro** [comment]
/test-1.23-4.9

**Review by glibsm — APPROVED** [review]

**Comment by gandro** [comment]
/test-1.16-netnext

**Comment by gandro** [comment]
/test-1.16-netnext

**Comment by gandro** [comment]
Previous flakes all are https://github.com/cilium/cilium/issues/18060

**Pull request merged**
