### PR TITLE
chore: generating eni limits for missing aws instances

### LINKED ISSUE #27562: Add m7a AWS instance family to ENI
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

AWS released m7a instance family. In order for ENI to work pkg/aws/eni/limits/limits.go needs to be updated. 

### Cilium Version

1.14.1

### Kernel Version

5.15

### Kubernetes Version

EKS 1.26

### Sysdump

_No response_

### Relevant log output

`level=warning msg="Instance not found! Please delete corresponding ciliumnode if instance has already been deleted." instanceID=i-074938c93fb3eebec name=ip-10-1-27-6.ec2.internal subsys=ipam`

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by svyatoslavmo**
AWS released m7a instances

Fixes: #27562

### CODE REVIEW

**Review by christarazi — APPROVED** [review]

**Comment by borkmann** [comment]
Hi @svyatoslavmo, CI failed due to a build issue, e.g. see https://app.travis-ci.com/github/cilium/cilium/builds/265341749 . Could you fix this up and then repush your commit? Otherwise looks ready to go.
```
Unformatted Go source code:
./pkg/aws/eni/limits/limits.go
diff ./pkg/aws/eni/limits/limits.go.orig ./pkg/aws/eni/limits/limits.go
--- ./pkg/aws/eni/limits/limits.go.orig
+++ ./pkg/aws/eni/limits/limits.go
@@ -423,7 +423,7 @@
 		"m7a.large":         {Adapters: 3, IPv4: 10, IPv6: 10, HypervisorType: "nitro"},
 		"m7a.medium":        {Adapters: 2, IPv4: 4, IPv6: 4, HypervisorType: "nitro"},
 		"m7a.metal-48xl":    {Adapters: 15, IPv4: 50, IPv6: 50, HypervisorType: ""},
-		"m7a.xlarge": 	     {Adapters: 4, IPv4: 15, IPv6: 15, HypervisorType: "nitro"},
+		"m7a.xlarge":        {Adapters: 4, IPv4: 15, IPv6: 15, HypervisorType: "nitro"},
 		"m7g.12xlarge":      {Adapters: 8, IPv4: 30, IPv6: 30, HypervisorType: "nitro"},
 		"m7g.16xlarge":      {Adapters: 15, IPv4: 50, IPv6: 50, HypervisorType: "nitro"},
 		"m7g.2xlarge":       {Adapters: 4, IPv4: 15, IPv6: 15, HypervisorType: "nitro"},
make: *** [Makefile:641: precheck] Error 1
make: *** Waiting for unfinished jobs....
  GEN    Documentation/ api-flags
```

**Comment by julianwiedmann** [comment]
hi @svyatoslavmo ! I've flipped the PR to draft for now, please adjust once you've addressed the build issue & rebased to latest `main` branch. Thank you!

**Comment by jeremych1000** [comment]
Heya - mind regenerating again please? There's also m7a, m7i, and r7a, and r7iz for example/
https://aws.amazon.com/ec2/instance-types/

**Pull request closed without merging**
