### PR TITLE
v1.14 Backports 2024-05-24

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
* [x] #32084 (@pchaigno) :warning: resolved conflicts
 * [x] #32328 (@joestringer)
 * [ ] #32017 (@mikemykhaylov)
 * [x] #32513 (@giorio94)
 * [ ] #32464 (@darox) :warning: resolved conflicts
 * [x] #32553 (@michi-covalent) :warning: resolved conflicts
 * [x] #32564 (@jibi) :warning: resolved conflicts
 * [x] #32548 (@squeed)
 * [x] #32570 (@mhofstetter)
 * [x] #32600 (@mhofstetter) :warning: resolved conflicts
 * [x] #32302 (@marseel) :warning: resolved conflicts
 * [ ] #32629 (@antonipp) :warning: resolved conflicts

PRs skipped due to conflicts:

 * #32307 (@ferozsalam)
 * #32450 (@jschwinger233)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 32084 32328 32017 32513 32464 32553 32564 32548 32570 32600 32302 32629
```

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
/test-backport-1.14

**Review by mhofstetter — APPROVED** [review]

**Review by jibi — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
My commit looks good, thanks!

**Review by lmb — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by joestringer — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
Rebased on top of the latest v1.14 to pull-in https://github.com/cilium/cilium/pull/32708.

**Comment by YutaroHayakawa** [comment]
/test-backport-1.14

**Comment by YutaroHayakawa** [comment]
/test-backport-1.14

**Review by marseel — APPROVED** [review]

**Review by darox — APPROVED** [review]
my change looks good

**Review by squeed — APPROVED** [review]

**Review by kaworu — APPROVED** [review]

**Pull request merged**
