### PR TITLE
docs: Improve disk based policy documentation

### PR DESCRIPTION
**Pull request by tamilmani1989**
update instructions on configuring via helm

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

### CODE REVIEW

**Review by gandro — APPROVED** [review]
As far as documentation goes, this looks good to me, thank you!

 I do wonder if we maybe want to add the static directory as a real Helm value such that our template adds the host path mount?

**Review by qmonnet — APPROVED** [review]
Thanks!

**Review by learnitall — APPROVED** [review]
Thanks!

**Comment by gandro** [comment]
Image build failed due to quay outage. Let's retrigger CI by closing and re-opening

**Pull request merged**
