### PR TITLE
nodeinit: Update image tag

### PR DESCRIPTION
**Pull request by errordeveloper**
This tag has no functional changes over previous one, however
it includes a fix to the manifest format issue that was seen
due to a bug in BuildKit (see #13429).

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by errordeveloper** [comment]
test-me-please

**Review by sayboras — APPROVED** [review]
LGTM :1st_place_medal: 

Just curious on how to backport this PR and helm-related changes going forward to 1.8 branch :thinking:

**Comment by errordeveloper** [comment]
@sayboras good point! I'll just make a separate PR for 1.8.

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Might be interesting to think about whether we can collapse the four places in the tree that we're tracking this version to a single source of truth, but LGTM.

**Pull request merged**
