### PR TITLE
agent: Don't masquerade ingress traffic to local endpoints

### PR DESCRIPTION
**Pull request by tgraf**
The existing behavior masqueraded all external traffic being routed into the
cilium_host interface to ensure that, in the event that the packet is routed
across the overlay to another node, reply traffic is routed in a symmetric
fashion. The side effect of this is that traffic terminated at the local node
was also masqueraded. Exclude traffic that is destined for a local endpoint
from masqueraded to preserve the real source IP whenever possible.

Fixes: #5609

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5608)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
The CI failure is legitimate. It is because we test NodePort from a pod on the same node. In that case, the reply to the source IP would not be routed back through cilium_host if we don't SNAT.

**Comment by tgraf** [comment]
test-me-please

NodePort tests passed now

Failure is infra problem:
```
	 fatal: unable to access 'https://github.com/containernetworking/cni/': Operation timed out after 300047 milliseconds with 0 out of 0 bytes received
```

**Comment by tgraf** [comment]
Updated commit description to explain the reason for the newly added rule. No code changes.

**Comment by tgraf** [comment]
test-me-please

**Review by jrfastab — APPROVED** [review]
LGTM

**Review by aanm — APPROVED** [review]

**Pull request merged**
