### PR TITLE
Add deepcopy plugin

### PR DESCRIPTION
**Pull request by AwesomePatrol**
It is required by https://github.com/cilium/cilium/pull/26646, so I could include the `FlowFilter` proto in the generated CRD.

After this change is merged I will use the updated builder image for code generation.

### CODE REVIEW

**Comment by AwesomePatrol** [comment]
I guess I don't have sufficient permissions to run `images/scripts/update-cilium-builder-image.sh` or am I doing something wrong?

**Review by christarazi — APPROVED** [review]

**Review by gandro — APPROVED** [review]
LGTM, thanks!

**Review by sayboras — APPROVED** [review]
Thanks and LGTM ✅

**Review by bimmlerd — APPROVED** [review]
contrib LGTM

**Pull request merged**
