### PR TITLE
backport v1.9: Fix possible deadlock when querying netdevs

### PR DESCRIPTION
**Pull request by brb**
See commit msgs.

```release-note
Fix possible deadlock when querying network interfaces for arping
```

### CODE REVIEW

**Comment by brb** [comment]
test-backport-1.9

**Comment by christarazi** [comment]
test-upstream-k8s

**Comment by christarazi** [comment]
retest-1.17-4.9

**Comment by christarazi** [comment]
test-backport-1.9

**Comment by christarazi** [comment]
retest-gke

**Review by aanm — APPROVED** [review]

**Pull request merged**
