### PR TITLE
helm: Improve spire template 

### LINKED ISSUE #24552: Ensure mutual auth and Policy interact in safe ways
Spun out from https://github.com/cilium/design-cfps/pull/5#discussion_r1142674630

This issue covers ensuring that we ensure that Cilium can't be used to block its own mutual auth, or that mutual auth policy can't be used to block things that are required for mutual auth to work.

From @joestringer:
> For instance (different options):
> 
> * We have some structure internally that tracks "exceptions to auth", and those peers are _always_ excluded from the auth requirement, transparently
>   
>   * Given the requirement for `toEndpoints`, kube-apiserver might be transparently protected since it's _probably_ not running as a Pod in the cluster so can't be targeted with such policy statements. Does the same apply to SPIRE?
> * We expose some CLI config flag that excludes certain labels, IPs or tuples from auth, then set some sort of default there, and the user can configure it to exclude other things from auth if they have specific constraints in their environment.
> * We provide documentation to protect against footgunnery
> 
> A couple of other corner cases come to mind:
> 
> * Can these statements be used for host firewall?
> * Etcd configuration also comes to mind here for Cilium<->etcd in etcd configuration mode
> * Cilium <-> Cilium auth connections must be exempt

An issue for exceptions to host firewall for mutual auth authentication traffic: #24542.

### PR DESCRIPTION
**Pull request by sayboras**
Please refer to individual commit for more details.

Fixes: https://github.com/cilium/cilium/issues/24552

### CODE REVIEW

**Review by zacharysarah — APPROVED** [review]
LGTM from a docs perspective

**Review by kaworu — APPROVED** [review]

**Comment by sayboras** [comment]
/test-1.26-net-next

**Comment by sayboras** [comment]
/test-1.26-net-next

**Review by joamaki — APPROVED** [review]

**Pull request merged**
