### PR TITLE
k8s: Remove node annotations on startup

### PR DESCRIPTION
**Pull request by tgraf**
Node annotations have been fully replaced by the CiliumNode custom resource.
Remove the logic to annotate the node on startup. This avoids a patch operation
on the node when the agent starts up and simplifies understanding where values
such as health IPs, encryption keys and PodCIDRs are being derived from.

The remaining functionality in the controller which was annotating the node is
to patch the status of the node. Keep this but rename the controller and move
it to the end of the bootstrap phase to only mark the node as ready once the
bootstrapping has been complete. Change the k8s client tests around node
patching to use SetNetworkUnavailableFalse() instead.

The remaining functionality in annotate.go is related to secrets retrieval so
rename the file to secrets.go.

TODO:
- [ ] Investigate CI failure

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10395)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
LGTM, and I assume that Cilium already propagates all of this same state from CiliumNode down to the appropriate modules.

**Comment by tgraf** [comment]
Rebased after CI fix has been merged

**Comment by tgraf** [comment]
test-em-please

**Comment by mrostecki** [comment]
test-me-please

**Comment by tgraf** [comment]
The kube-proxy-free CI tests are failing consistently. Will need further investigation first.

**Pull request closed without merging**
