### PR TITLE
Rename "Policy denied (L3)" to "Policy denied"

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9951)

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@tgraf needs rebase

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
