### PR TITLE
v1.8 backports 2021-01-29

### PR DESCRIPTION
**Pull request by pchaigno**
* #13527 -- test/vagrant: Fix NFS setup for test VMs (@pchaigno)
    - Fixed a minor conflict.
 * #13983 -- test: Use NFS by default in test VMs (@pchaigno)
 * #13953 -- test: Enable K8sVerifier on 4.19 and net-next CI (@pchaigno)
    - Fixed a minor conflict.
 * #13934 -- bpf: Replace CALLS_MAP symbol in compile-tested binaries (@pchaigno)
 * #13958 -- docker: Pull llvm-objcopy in cilium-builder (@pchaigno)
    - Rebuilt the chain of Docker images from https://github.com/cilium/image-tools/tree/v1.8.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13527 13983 13953 13934 13958; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by pchaigno** [comment]
test-backport-1.8

**Review by christarazi — APPROVED** [review]

**Comment by christarazi** [comment]
CI failures seem to be legitimate--pointing to verifier issues

**Comment by pchaigno** [comment]
test-backport-1.8

**Comment by pchaigno** [comment]
test-1.17-4.19

**Comment by pchaigno** [comment]
test-missed-k8s

**Review by tklauser — APPROVED** [review]

**Comment by pchaigno** [comment]
Cilium-Ginkgo-Test-k8s has the usual timeout issues on k8s-all. Other builds are green. I think this is ready to merge.

**Pull request merged**
