### PR TITLE
Pin gcloud CLI version

### PR DESCRIPTION
**Pull request by michi-covalent**
Ref: https://cloud.google.com/sdk/docs/release-notes#40500_2022-10-04
Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Comment by michi-covalent** [comment]
gke cluster creation is failing with the latest cli. for example: https://github.com/cilium/cilium/actions/runs/3324609489/jobs/5496387060#step:13:36

**Review by sayboras — APPROVED** [review]
Pin(in)terest 🧷

**Comment by michi-covalent** [comment]
pin to win

**Review by christarazi — APPROVED** [review]
Pin to win indeed. If the GKE workflows have passed then this seems good to go. Do we need to backport to older branches?

**Comment by michi-covalent** [comment]
no need to backport. all the gke workflows are in the master branch. i updated them all.

**Review by aanm — APPROVED** [review]

**Pull request merged**
