### PR TITLE
v1.10 backports 2022-04-08

### PR DESCRIPTION
**Pull request by jrajahalme**
* #18618 -- pull in the latest changes from github.com/vishvananda/netlink (@aditighag)
 * #19310 -- Test runtime cilium in container (take two) (@jrajahalme)
 * #19358 -- test: Fix whitespace in docker-run-cilium (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18618 19310 19358; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.10

**Review by nbusseneau — APPROVED** [review]

**Comment by jrajahalme** [comment]
/test-1.20-4.19

**Comment by jrajahalme** [comment]
/test-1.19-5.4

**Comment by jrajahalme** [comment]
/test-1.19-4.9

**Comment by jrajahalme** [comment]
/test-1.18-4.9

**Comment by jrajahalme** [comment]
/test-1.17-4.9

**Comment by jrajahalme** [comment]
/test-1.16-netnext

**Comment by jrajahalme** [comment]
/test-backport-1.10

**Comment by jrajahalme** [comment]
/test-backport-1.10

**Comment by jrajahalme** [comment]
/test-1.21-4.9

**Comment by jrajahalme** [comment]
/test-1.20-4.19

**Comment by jrajahalme** [comment]
The failing code scanning job is not required, so labeling as ready-to-merge.

**Comment by jrajahalme** [comment]
Superseded by #19404, closing.

**Pull request closed without merging**
