### PR TITLE
job: Prepare job names for hive bump

### PR DESCRIPTION
**Pull request by ovidiutirla**
The new version of hive have a new format for the job names to ensure the names are compliant with the prometheus metrics. This PR ensures that all jobs are compliant with the new naming convention.

Manually checked the non-static ones
* https://github.com/cilium/cilium/blob/68e145cfd361201300878217e67e2302b3aadfa3/pkg/bpf/metrics.go#L47
* https://github.com/cilium/cilium/blob/4313a4e76890e1938f58a385a7fa3bc8a7ed9c58/pkg/l2announcer/l2announcer.go#L743
* https://github.com/cilium/cilium/blob/2bf8ae746efe113d36811ae36c14e96e527592cb/pkg/envoy/cell.go#L348
* https://github.com/cilium/cilium/blob/df79ac9f0fd493cd14ce6e65e89df52df8c6459d/pkg/datapath/linux/bandwidth/cell.go#L56

Script use to catch the static ones:
<details>

```
import glob
import re


def is_valid_name(name):
  pattern = r"^[a-z][a-z0-9_\-]{0,100}$"
  return bool(re.match(pattern, name))


def extract_names_from_file(filename):
  names = []
  with open(filename, 'r') as file:
    for line_number, line in enumerate(file, start=1):
      match = re.search(r'job\.(?:OneShot|Observer|Timer)\("([^"]+)', line)
      if match:
        name = match.group(1)
        names.append(name)
  return names

count=0
names =[]
for filename in glob.iglob("./" + '**/*.go', recursive=True):
  names = names + extract_names_from_file(filename)

print(names)
for name in names:
  if not is_valid_name(name):
    print(name)
```
</details>

Script used to catch non-static:
<details>

```
grep -rnP 'statedb\.Derive\(' .
grep -rnP 'job\.OneShot\(' .
grep -rnP 'job\.Timer\(' .
grep -rnP 'job\.Observer\(' .
```

</details>

See https://github.com/cilium/hive/pull/10.

### CODE REVIEW

**Review by joamaki — APPROVED** [review]
LGTM, thanks!

**Review by mhofstetter — APPROVED** [review]
Thanks!

**Review by ysksuzuki — APPROVED** [review]

**Pull request merged**
