### PR TITLE
v1.13 Backports 2023-11-27

### PR DESCRIPTION
**Pull request by gandro**
* [ ] #29335 (@gandro)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 29335
```

### CODE REVIEW

**Comment by gandro** [comment]
/test-backport-1.13

**Comment by gandro** [comment]
/test-1.19-4.19

**Comment by gandro** [comment]
/test-1.21-4.19

**Review by youngnick — APPROVED** [review]

**Comment by youngnick** [comment]
I just merged #29003, which updates the test that's failing. I suggest a rebase @gandro.

**Comment by gandro** [comment]
/test-backport-1.13

**Comment by gandro** [comment]
> I just merged #29003, which updates the test that's failing. I suggest a rebase @gandro.

Looks like it's still failing, which, taking a closer look, seems expected as it's not fixing anything, just adding more tests https://github.com/cilium/cilium/actions/runs/7016632415 :disappointed:

**Comment by gandro** [comment]
- https://jenkins.cilium.io/job/Cilium-PR-K8s-1.24-kernel-4.19/276/testReport/junit/Suite-k8s-1/24/K8sAgentPolicyTest_Multi_node_policy_test_with_L7_policy_using_connectivity_check_to_check_datapath/ hit "The Service "echo-b" is invalid: spec.ports[0].nodePort: Invalid value: 31414: provided port is already allocated"
- https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/335/ hit https://github.com/cilium/cilium/issues/27118

**Comment by gandro** [comment]
/test-1.22-4.19

**Comment by gandro** [comment]
/test-1.24-4.19

**Pull request merged**
