### PR TITLE
v1.7 backports 2020-11-03

### PR DESCRIPTION
**Pull request by tklauser**
* #13707 -- backporting: Clean tmp files after backport with conflicts (@pchaigno)
 * #13756 -- backporting: Properly escape commit message when used as regex (@gandro)
 * #13811 -- k8s: clarify CRD schema versioning and its update process (@aanm)
   - Minor merge conflicts in docs because previous release docs didn't get backported.
 * #13825 -- Improve and expand on documentation for the API rate limiter (@christarazi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13707 13756 13811 13825; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by tklauser** [comment]
test-backport-1.7

**Comment by tklauser** [comment]
test-backport-1.7

**Review by pchaigno — APPROVED** [review]
:+1: for my PR.

**Comment by tklauser** [comment]
test-backport-1.7

**Comment by tklauser** [comment]
test-backport-1.7

**Comment by tklauser** [comment]
test-missed-k8s

**Review by christarazi — APPROVED** [review]
:+1: for my commits

**Review by aanm — APPROVED** [review]
LGTM for my changes

**Comment by joestringer** [comment]
@tklauser I saw four re-triggers of CI in this PR, but only one report of which flake was being hit. Was that the only flake being hit?

In future, please post a comment on the PR pointing to which flake is being hit each time so that we can better perceive patterns in the CI behaviour and interpret whether the CI flakes are likely to be related to the changes being made.

Looking at the PRs backported here however, it seems highly unlikely that the flakes are related to the backports. Merging.

**Comment by tklauser** [comment]
@joestringer FWIW, the re-triggers were due to docs build errors in the backport PR itself, i.e. moved files which lead to wrong input paths as well as missing entries in the spelling word list. Thus also the force pushes between the re-triggers.

There were no flakes as such, other than the one reported in https://github.com/cilium/cilium/pull/13871#issuecomment-721207479.

**Pull request merged**
