### PR TITLE
v1.11 backports 2022-04-26

### PR DESCRIPTION
**Pull request by joestringer**
* #19153 -- metrics: Add go_* metrics (@chancez)
 * #19528 -- make: check that Go major/minor version matches required version (@tklauser)
 * #19452 -- Limit the number of active FQDNs beyond the TTL to `--tofqdns-endpoint-max-ip-per-hostname` (@joestringer)
   * Minor conflicts in `pkg/endpoint/endpoint.go`, `pkg/fqdn/cache.go`
 * #19563 -- docs: fix version warning URL to point to docs.cilium.io (@aanm)
 * #19578 -- add robots.txt to Cilium documentation (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 19153 19528 19452 19563 19578; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Comment by joestringer** [comment]
/test-backport-1.11

**Comment by joestringer** [comment]
* [Conformance AWS-CNI](https://github.com/cilium/cilium/actions/runs/2230149287)
  * Failed due to agents not getting ready, agents crashing with `level=fatal msg="Error when enabling sysctl parameters" error="could not open the sysctl file /proc/sys/net/ipv4/ip_forward: open /proc/sys/net/ipv4/ip_forward: read-only file system" subsys=daemon`. Looks similar to https://github.com/cilium/cilium/issues/19526, which is reported as fixed in https://github.com/cilium/cilium/pull/18898. This is likely a regression introduced by that logic, potentially fixed by #19555.
* [External workloads](https://github.com/cilium/cilium/actions/runs/2230149292)
  * DNS verification failed(?) Filed new issue #19603 to follow up, will retry
* [k8s-1.17-kernel-4.9](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-4.9/609/)
  *  VM provisioning failed, will retry
* [k8s-1.22-kernel-4.19](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/1171/)
  *  Hit what looks like known flake https://github.com/cilium/cilium/issues/18318
* ConformanceAKS (ci-aks-1.11)
  * Job failed to run, ignoring

**Comment by joestringer** [comment]
/ci-external-workloads-v1.11

**Comment by joestringer** [comment]
/test-1.17-4.9

**Comment by aanm** [comment]
The fix for the conformance aws-cni test is [here](https://github.com/cilium/cilium/pull/19609)

**Comment by aanm** [comment]
/ci-awscni-1.11

**Comment by joestringer** [comment]
Latest aws-cni breakage during `Update AWS VPC CNI plugin` step still seems related to GH workflow breakages, not this PR:
```
Run kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.7.10/config/v1.7/aws-k8s-cni.yaml
  kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.7.10/config/v1.7/aws-k8s-cni.yaml
  shell: /usr/bin/bash -e {0}
  env:
    clusterName: cilium-cilium-[2](https://github.com/cilium/cilium/runs/6210086880?check_suite_focus=true#step:8:2)238999029
    region: us-east-2
    cilium_cli_version: v0.10.4
    check_url: https://github.com/cilium/cilium/actions/runs/2238999029
    AWS_DEFAULT_REGION: us-east-2
    AWS_REGION: us-east-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
clusterrolebinding.rbac.authorization.k8s.io/aws-node unchanged
clusterrole.rbac.authorization.k8s.io/aws-node unchanged
Warning: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: beta.kubernetes.io/os is deprecated since v1.14; use "kubernetes.io/os" instead
Warning: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[1].key: beta.kubernetes.io/arch is deprecated since v1.14; use "kubernetes.io/arch" instead
daemonset.apps/aws-node configured
error: unable to recognize "https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.7.10/config/v1.7/aws-k8s-cni.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k[8](https://github.com/cilium/cilium/runs/6210086880?check_suite_focus=true#step:8:8)s.io/v1beta1"
serviceaccount/aws-node unchanged
Error: Process completed with exit code 1.
```

**Comment by joestringer** [comment]
External workloads hit https://github.com/cilium/cilium/issues/19603 again.

**Comment by joestringer** [comment]
Only AWS-CNI (described above), External workloads (known flake) and k8s-1.22-kernel-4.19 (known flake) are currently broken. This PR should be good from a CI perspective.

**Review by aanm — APPROVED** [review]

**Pull request merged**
