### PR TITLE
Backports V1.4 27-03-2019

### PR DESCRIPTION
**Pull request by eloycoto**
PR #7520
PR #7506
PR #7514

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7529)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
