### PR TITLE
iptables: Fix 127.0.0.1:NodePort to remote pods

### LINKED ISSUE #5384: CI: NodePort test failed due to curl failing with exit code 28
Build link: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1499/testReport/junit/k8s-1/8/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort/

Output: 
```
/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
Pod "testclient-p4hxc" can not connect to service "http://10.103.229.24:10080"
Expected command: kubectl exec -n default testclient-p4hxc -- curl -s -D /dev/stderr --fail --connect-timeout 3 --max-time 3 http://10.103.229.24:10080 -w "time-> DNS: '%{time_namelookup}', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.000033', Connect: '0.000000',Transfer '0.000000', total '3.001085'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/k8sT/Services.go:187
```

Logs:

```
NAMESPACE     NAME                               READY     STATUS        RESTARTS   AGE       IP              NODE
default       testclient-p4hxc                   1/1       Running       0          1m        10.10.0.36      k8s1
default       testclient-ptmnr                   1/1       Running       0          1m        10.10.1.197     k8s2
default       testds-9qsgq                       1/1       Running       0          1m        10.10.0.134     k8s1
default       testds-pshlv                       1/1       Running       0          1m        10.10.1.201     k8s2
kube-system   cilium-mjrll                       1/1       Running       0          4m        192.168.36.11   k8s1
kube-system   cilium-sc7gn                       1/1       Running       1          4m        192.168.36.12   k8s2
kube-system   etcd-k8s1                          1/1       Running       0          22m       192.168.36.11   k8s1
kube-system   kube-apiserver-k8s1                1/1       Running       0          21m       192.168.36.11   k8s1
kube-system   kube-controller-manager-k8s1       1/1       Running       3          22m       192.168.36.11   k8s1
kube-system   kube-dns-6f4c8dbcd4-9mtht          3/3       Running       0          22m       10.10.1.202     k8s2
kube-system   kube-proxy-t8jjc                   1/1       Running       0          22m       192.168.36.11   k8s1
kube-system   kube-proxy-z78m8                   1/1       Running       0          9m        192.168.36.12   k8s2
kube-system   kube-scheduler-k8s1                1/1       Running       4          22m       192.168.36.11   k8s1
kube-system   microscope                         1/1       Terminating   0          20s       10.10.0.211     k8s1
monitoring    prometheus-core-5c9fbf5cc6-9xl7k   1/1       Running       0          8m        10.10.1.60      k8s2

cmd: kubectl exec -n kube-system cilium-mjrll -- cilium service list
ID   Frontend              Backend                   
1    10.96.0.1:443         1 => 192.168.36.11:6443   
2    10.96.0.10:53         1 => 10.10.1.202:53       
3    10.106.92.174:9090    1 => 10.10.1.60:9090      
7    10.99.98.243:80       1 => 10.10.0.134:80       
                           2 => 10.10.1.201:80       
8    10.103.229.24:10080   1 => 10.10.0.134:80       
                           2 => 10.10.1.201:80       

cmd: kubectl exec -n kube-system cilium-mjrll -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                          IPv6                 IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                          
12217      Disabled           Disabled          39281      k8s:io.cilium.k8s.policy.serviceaccount=default      f00d::a0a:0:0:2fb9   10.10.0.134   ready   
                                                           k8s:io.kubernetes.pod.namespace=default                                                         
                                                           k8s:zgroup=testDS                                                                               
16076      Disabled           Disabled          47736      k8s:io.cilium.k8s.policy.serviceaccount=microscope   f00d::a0a:0:0:3ecc   10.10.0.211   ready   
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                     
                                                           k8s:k8s-app=microscope                                                                          
34588      Disabled           Disabled          56420      k8s:io.cilium.k8s.policy.serviceaccount=default      f00d::a0a:0:0:871c   10.10.0.36    ready   
                                                           k8s:io.kubernetes.pod.namespace=default                                                         
                                                           k8s:zgroup=testDSClient                                                                         
34886      Disabled           Disabled          4          reserved:health                                      f00d::a0a:0:0:8846   10.10.0.119   ready   

cmd: kubectl exec -n kube-system cilium-sc7gn -- cilium service list
ID   Frontend              Backend                   
1    10.96.0.10:53         1 => 10.10.1.202:53       
2    10.106.92.174:9090    1 => 10.10.1.60:9090      
5    10.96.0.1:443         1 => 192.168.36.11:6443   
7    10.99.98.243:80       1 => 10.10.0.134:80       
                           2 => 10.10.1.201:80       
8    10.103.229.24:10080   1 => 10.10.0.134:80       
                           2 => 10.10.1.201:80       

cmd: kubectl exec -n kube-system cilium-sc7gn -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                              IPv6                   IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                                
10533      Disabled           Disabled          27130      k8s:io.cilium.k8s.policy.serviceaccount=kube-dns         f00d::a0a:100:0:2925   10.10.1.202   ready   
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                           
                                                           k8s:k8s-app=kube-dns                                                                                  
18321      Disabled           Disabled          7608       k8s:app=prometheus                                       f00d::a0a:100:0:4791   10.10.1.60    ready   
                                                           k8s:component=core                                                                                    
                                                           k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                                
                                                           k8s:io.kubernetes.pod.namespace=monitoring                                                            
26513      Disabled           Disabled          4          reserved:health                                          f00d::a0a:100:0:6791   10.10.1.45    ready   
39142      Disabled           Disabled          39281      k8s:io.cilium.k8s.policy.serviceaccount=default          f00d::a0a:100:0:98e6   10.10.1.201   ready   
                                                           k8s:io.kubernetes.pod.namespace=default                                                               
                                                           k8s:zgroup=testDS                                                                                     
43922      Disabled           Disabled          56420      k8s:io.cilium.k8s.policy.serviceaccount=default          f00d::a0a:100:0:ab92   10.10.1.197   ready   
                                                           k8s:io.kubernetes.pod.namespace=default                                                               
                                                           k8s:zgroup=testDSClient             
```

[ab2fda27_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort.zip](https://github.com/cilium/cilium/files/2325743/ab2fda27_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort.zip)

### LINKED ISSUE #6341: CI: K8sServicesTest Checks service across nodes Tests NodePort
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
Pod "testclient-4q99h" can not connect to service "http://10.97.156.73:10080"
Expected command: kubectl exec -n default testclient-4q99h -- curl -s -D /dev/stderr --fail --connect-timeout 3 --max-time 8 http://10.97.156.73:10080 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.000018()', Connect: '0.000000',Transfer '0.000000', total '3.001106'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Services.go:183
```

[585281bc_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort.zip](https://github.com/cilium/cilium/files/2633827/585281bc_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort.zip)

### PR DESCRIPTION
**Pull request by tgraf**
Commit c6888d48780 fixed 127.0.0.1:NodePort redirection by adding an additional
clause to the kube-proxy masquerade bit clearing rule to ensure that kube-proxy
masquerades all traffic with a source IP of 127.0.0.1. This fixes NodePort
redirection to local pods but it can cause problem when running in
encapsulation mode depending on the rp_filter settings of nodes because the
source IP of the traffic will have a source IP equal to any of the node IPs
which are not routable on the overlay. This causes reply traffic to be routed
back via the underlay which the reverse path filter can potentially drop.

Fixes: c6888d48780 ("iptables: Ensure NAT for locally-sourced packets")

Fixes: #6341
Fixes: #5384

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6869)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Weird, when setting this up with ginkgo manually, it *always* succeeds no matter how much I hammer it.

**Comment by tgraf** [comment]
test-me-please

green build, testing again

**Comment by tgraf** [comment]
test-me-please

green again, another run

**Comment by tgraf** [comment]
test-me-please

3rd green run

**Review by joestringer — APPROVED** [review]
It passes the recent "testing connectivity via localhost IP" tests, so at minimum doesn't break anything. Would be good to get some real regression tests of cross-node examples of this, but seems OK to me.

I suspect we ended up backporting the prior solution to v1.3 but not v1.2, up to you whether it's worth doing that for this iteration as well.

**Comment by tgraf** [comment]
> It passes the recent "testing connectivity via localhost IP" tests, so at minimum doesn't break anything. Would be good to get some real regression tests of cross-node examples of this, but seems OK to me.

I've done that manually with several million requests and couldn't find a way to break it.

**Pull request merged**
