### PR TITLE
k8s: Update libraries to v1.23.5

### PR DESCRIPTION
**Pull request by nathanjsweet**
Signed-off-by: Nate Sweet <nathanjsweet@pm.me>

### CODE REVIEW

**Review by YutaroHayakawa — APPROVED** [review]

**Comment by nathanjsweet** [comment]
/test-backport-1.11

**Comment by nathanjsweet** [comment]
@nbusseneau yes it is.

**Comment by nathanjsweet** [comment]
/test-backport-1.11

**Comment by nathanjsweet** [comment]
Looks like #19766 is the only issue. Marking as ready.

**Pull request merged**
