### PR TITLE
go.mod: update kevinburke/ssh_config dependency

### PR DESCRIPTION
**Pull request by kevinburke**
Previously if you tried to read a HostName in a SSH config file that
looked like this:

```
Host github
    HostName github.com        # This is the host for code review
```

DefaultUserSettings.Get("HostName") would return "github.com        ",
which I think is unintuitive and unexpected.

This behavior is fixed in v1.2 which would return "github.com" in the
above example.

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [X] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Thanks for contributing!

### CODE REVIEW

**Comment by kevinburke** [comment]
I expect Dependabot will submit the same change in a few hours, just wanted to flag the additional context. 

I didn't think you would want to put this in release notes since you only use this package in test/helpers and the public facing behavior is not changing at all.

**Comment by aanm** [comment]
Thanks for the PR

**Review by tklauser — APPROVED** [review]
Thank you

**Comment by tklauser** [comment]
/test-1.23-net-next

**Comment by tklauser** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
@tklauser Were the tests failing with known flakes?

**Comment by tklauser** [comment]
> @tklauser Were the tests failing with known flakes?

@pchaigno the GKE tests failed because images were not built yet. net-next tests failed due to an issue with sync errors in the bpf-map-sync-cilium_lb{4,6}_backends_v2 controllers, see #19264.

**Pull request merged**
