### PR TITLE
Remove hostPort dependency on BPF NodePort

### LINKED ISSUE #31532: Remove `hostPort` dependency on BPF `NodePort`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently, enabling `hostPort` requires that `nodePort` is also enabled, this requirement is listed for the `--enable-host-port` flag in the Cilium agent command reference:
 

- [Command Reference - cilium-agent](https://docs.cilium.io/en/stable/cmdref/cilium-agent/)

 
Additionally, if `NodePort` is disabled, then its dependents, including `hostPort`, are also disabled:
 
```go
// https://github.com/cilium/cilium/blob/c80018ec287dcbd2f4dfd7571e24514afcc39703/daemon/cmd/kube_proxy_replacement.go#L498

// disableNodePort disables BPF NodePort and friends who are dependent from
// the latter.
func disableNodePort() {
	option.Config.EnableNodePort = false
	option.Config.EnableHostPort = false
	option.Config.EnableExternalIPs = false
	option.Config.EnableSVCSourceRangeCheck = false
	option.Config.EnableHostLegacyRouting = true
}
```

However, despite `NodePort` seemingly being a dependency of `hostPort`, having Wireguard enabled would result in the `disableNodePort()` function not being called, which would keep `hostPort` enabled, and it is functional. 

Is `NodePort` actually a necessary requirement for `hostPort` or can we remove this limitation?

Relevant comments from @brb:

> hostPort can be accessed from outside cluster, thus it depends on nodeport. for in-cluster access it should not depend on nodeport, as it's implemented in bpf_sock/bpf_lxc (vs bpf_host for nodeport).

### Cilium Version

v1.15, v1.14, v1.13

### Kernel Version

`Linux xxx 5.15.0-1057-azure #65-Ubuntu SMP Fri Feb 9 18:39:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.5", GitCommit:"506050d61cf291218dfbd41ac93913945c9aa0da", GitTreeState:"clean", BuildDate:"2023-12-23T00:10:25Z", GoVersion:"go1.20.12", Compiler:"gc", Platform:"linux/amd64"}`

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Remove hostPort dependency on BPF NodePort

Fixes: #31532

```release-note
Remove hostPort dependency on BPF NodePort
```

### CODE REVIEW

**Review by markpash — APPROVED** [review]

**Comment by chaunceyjiang** [comment]
@markpash Can you please add this PR to the merge queue?

**Comment by markpash** [comment]
> @markpash Can you please add this PR to the merge queue?

I'm not sure that's something I need to do. Currently the helper bot is complaining about the PR not having the correct release note label. Perhaps if that's fixed it will get the green-light.

**Comment by borkmann** [comment]
@chaunceyjiang Please add a proper commit description which explain the concrete problem you are solving and why this patch is needed.

**Comment by borkmann** [comment]
@squeed can we pls revert this? It's not even clear what this fixes in the first place.

**Comment by chaunceyjiang** [comment]
> @chaunceyjiang Please add a proper commit description which explain the concrete problem you are solving and why this patch is needed.

My understanding is that disable `NodePort` will also disable `hostPort`. From the description, this dependency does not seem to be necessary.

**Pull request merged**
