### PR TITLE
envoy: Bump envoy minor version to v1.28.0

### PR DESCRIPTION
**Pull request by sayboras**
The goal is to upgrade envoy version in main branch for new development cycle.

@cilium/sig-servicemesh for awareness

Relates: https://github.com/cilium/proxy/pull/510

### CODE REVIEW

**Review by mhofstetter — APPROVED** [review]
:tada: Thanks Tam!

**Review by christarazi — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Pull request merged**
