### PR TITLE
v1.6 backports 2019-08-14

### PR DESCRIPTION
**Pull request by brb**
v1.6 backports 2019-08-14

 * #8881 -- docs: Fine tune external etcd guide. (@jrajahalme)
 * #8862 -- Emit AvailableIPsPerSubnet metric (@ungureanuvladvictor)
 * #8867 -- cilium: encryption, use default route interface if encrypt-interface is not specified (@lbernail)
 * #8886 -- Update AUTHORS (@tgraf)
 * #8874 -- Document CNI chaining modes (@tgraf)
 * #8854 -- Bump vagrant box versions (@nebril)
 * #8882 -- Revert "[daemon] - Change MTU source for cilium_host (Use the Route o…ne)" (@aanm)
 * #8900 -- Fix documentation warnings and fail out when new ones are introduced (@joestringer)
 * #8898 -- Document flannel limitations (@joestringer)
 * #8784 -- Re-enable flannel CI with helm (@joestringer) -- There was a merge conflict, @joestringer please check whether the resolution is OK.
 * #8893 -- Enable insertNeighbor when tunneling is disabled (@lbernail)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 8881 8862 8867 8886 8874 8854 8882 8900 8898 8784 8893; do contrib/backporting/set-labels.py $pr done 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8907)

### CODE REVIEW

**Comment by brb** [comment]
never-tell-me-the-odds

**Comment by ianvernon** [comment]
We had some issues with Jenkins and had to restart it. Triggering failed builds again.

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by tgraf** [comment]
test-docs-please

**Comment by ianvernon** [comment]
@tgraf the docs build is queued, but for some reason for some builds we have multiple 'checks' for the same build (Cilium-PR-Docs-Test and Cilium-Doc-Test), not sure why.

**Comment by ianvernon** [comment]
Apt problems: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2358/


```
    k8s1-1.14: Reading package lists...
    k8s1-1.14: E: Failed to stat /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_bionic-security_main_binary-i386_Packages - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
    k8s1-1.14: E: Failed to stat /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_bionic-security_main_binary-amd64_Packages - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
    k8s1-1.14: E: Failed to stat /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_bionic-security_main_i18n_Translation-en - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
    k8s1-1.14: E: Failed to stat /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_bionic-security_restricted_binary-amd64_Packages - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
    k8s1-1.14: E: Failed to stat /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_bionic-security_restricted_i18n_Translation-en - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
    k8s1-1.14: E: Failed to stat /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_bionic-security_universe_binary-amd64_Packages - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
    k8s1-1.14: E: Failed to stat /var/lib/apt/lists/partial/ppa.launchpad.net_projectatomic_ppa_ubuntu_dists_bionic_InRelease - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
    k8s1-1.14: E: Failed to stat /var/lib/apt/lists/partial/ppa.launchpad.net_projectatomic_ppa_ubuntu_dists_bionic_main_binary-amd64_Packages - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
    k8s1-1.14: E: Failed to stat /var/lib/apt/lists/partial/ppa.launchpad.net_projectatomic_ppa_ubuntu_dists_bionic_main_i18n_Translation-en - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by joestringer — APPROVED** [review]
helm flannel changes look good.

**Comment by ianvernon** [comment]
```
10:17:24  STEP: "app1" attempting to "ping" "httpd1"
10:18:45  Cannot contact jenkins-node-2: java.lang.InterruptedException
```

**Comment by ianvernon** [comment]
test-me-please

**Review by nebril — CHANGES_REQUESTED** [review]
please remove #8854 from this backport, I am reverting it in https://github.com/cilium/cilium/pull/8912 as I believe it might cause CI failures.

**Review by nebril — APPROVED** [review]
Disregard my previous comment

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Checkout from Git failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14377/flowGraphTable/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14382/execution/node/3/log/

Checkout failed, node was `jenkins-node-0`. I took this node offline because other builds were having the same problem.

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
