### PR TITLE
Make FirstInterfaceIndex a pointer on ENI spec

### LINKED ISSUE #9738: ENI: Cannot set spec.eni.first-interface-index to 0 through CNI configuration
## Bug report

Cannot configure in ENI mode the `spec.eni.first-interface-index` to 0 with CNI configuration file. Cilium will continue to create the ciliumnodes with first-interface-index set to 1 with the below configuration.

CNI configuration file
```
{
    "cniVersion": "0.3.1",
    "name": "cilium",
    "plugins": [
        {
            "type": "cilium-cni",
            "eni": {
                "first-interface-index": 0
            }
        }
    ]
}
```

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.6.4 8048d320a 2019-11-27T17:00:12+01:00 go version go1.12.13 linux/amd64
```

### PR DESCRIPTION
**Pull request by ungureanuvladvictor**
Currently `FirstInterfaceIndex` field in the ENI spec is an `int` and the default value in golang is 0.

If a user supplies `FirstInterfaceIndex` to be 0 the code will intepret that as being unset and will default it to 1 via https://github.com/cilium/cilium/blob/master/pkg/nodediscovery/nodediscovery.go#L273 + https://github.com/cilium/cilium/blob/master/pkg/nodediscovery/nodediscovery.go#L285-L287.

Happy to discuss other approaches here to handle this edge case. We also have `MinAllocate`, `PreAllocate` and `MaxAboveWatermark` that suffer from the same behavior.

Fixes: https://github.com/cilium/cilium/issues/9738

Signed-off-by: Vlad Ungureanu <vladu@palantir.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9745)

### CODE REVIEW

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Seems reasonable to me.

I don't know much of the nuance of pointer with nil default (this PR) vs. using `-1` as the "not configured option", other than the latter would require all CNI clients to specify the `FirstInterfaceIndex` when they only intend to ignore the value. This current proposal seems like a better option than using `-1` for this reason, as ignorant clients can just omit the option entirely.

**Comment by joestringer** [comment]
Are there any upgrade considerations here, given that the k8s resources will change on some nodes but not others during rollout?

**Comment by ungureanuvladvictor** [comment]
@joestringer I was thinking about -1 as unset but then this won't work out of the box and we will need operators to fill in this value when the CN gets created which is not great UX if we want Cilium to work out of the box.

As for during the upgrade I don't see why this won't work since all the current CN resources will have the field already set and new CN will have the filed as `nil` when the codepath gets executed and it will be defaulted. If an operator will override the `FirstInterfaceIndex` field we will just use that value.

**Review by aanm — APPROVED** [review]

**Pull request merged**
