### PR TITLE
[WIP] Add OpenStack ipam operator

### PR DESCRIPTION
**Pull request by chestack**
Add OpenStack ipam operator as a new allocator provider that likes:

- https://github.com/cilium/cilium/pull/8347
- https://github.com/cilium/cilium/pull/15160

It's for running cilium on OpenStack cloud and allocates IP from OpenStack neutron.

### CODE REVIEW

**Comment by nathanjsweet** [comment]
@chestack Thanks for the PR! Please add a release note to the PR description.

**Comment by chestack** [comment]
WeChatWorkScreenshot_2ecce8f5-a8b8-4334-bbc4-82578ad3c160

For cloud vpc ipam mode, I run into a problem that **the node nic didn't do ARP reply for pods on it**

pod2(172.16.0.24) running on node-1  ping  node-2(172.16.0.15)
```
ip netns exec cni-2d7326cd-d067-ad4c-4ab8-4310aeccb851 ping 172.16.0.15
```


tcpdump node-2 ens3(172.16.0.15), found that it received icmp request and send ARP request for pod2(172.16.0.24)

```
ethertype IPv4 (0x0800), length 98: 172.16.0.24 > 172.16.0.15: ICMP echo request, id 32438, seq 20, length 64
ethertype IPv4 (0x0800), length 98: 172.16.0.24 > 172.16.0.15: ICMP echo request, id 32438, seq 21, length 64
ethertype ARP (0x0806), length 42: Request who-has 172.16.0.24 tell 172.16.0.15, length 28
```

tcpdump node-1 ens3 where pod1 running, found that it received ARP request for pod2(172.16.0.24) but didn't reply
```
ethertype IPv4 (0x0800), length 98: 172.16.0.24 > 172.16.0.15: ICMP echo request, id 32438, seq 18, length 64
ethertype ARP (0x0806), length 60: Request who-has 172.16.0.24 tell 172.16.0.15, length 46
```

**Comment by BSWANG** [comment]
> For cloud vpc ipam mode(aws eni, alibaba), is it node nic(node-2 ens3 in my case) with attached ebpf code(cil_to_netdev) responsible to do ARP reply for pods running on it? if not, how client get the mac address of the pods running on different nodes?

On alibaba cloud, vpc agent which running on host will reply ARP request with fixed hwaddr(ee:ff:ff:ff:ff:ff).  The ARP request will not passthrough to another guest k8s node.

**Comment by joestringer** [comment]
Hi, thanks for the submission. I have a general design question: Are you aware of the [Delegated IPAM](https://www.cni.dev/docs/spec/#section-4-plugin-delegation) section of the CNI spec, and have you considered whether it fits well for your use case? Cilium supports delegated IPAM, and this potentially provides a way to more easily maintain platform-specific IPAM plugins. Cilium already supports delegated IPAM since Cilium 1.12 (via https://github.com/cilium/cilium/pull/19219).

We had a brief discussion on the topic of delegated IPAM and the future of the Azure IPAM module in Cilium during today's 2023-05-31 community meeting, and there were some interesting points raised about the technical approaches and architectural models. For today, we will continue to have Azure IPAM in the tree, but I think it's worth considering whether alternative approaches like this may be a better fit for newly proposed IPAM modules. You can find the notes we took during the discussion [here](https://docs.google.com/document/d/1Y_4chDk4rznD6UgXPlPvn3Dc7l-ZutGajUv1eF0VDwQ/edit#bookmark=id.cl7yorzc9by3).

**Comment by chestack** [comment]
> Hi, thanks for the submission. I have a general design question: Are you aware of the [Delegated IPAM](https://www.cni.dev/docs/spec/#section-4-plugin-delegation) section of the CNI spec, and have you considered whether it fits well for your use case? This potentially provides a way to more easily maintain platform-specific IPAM plugins. Cilium already supports delegated IPAM since Cilium 1.12 (via #19219).
> 
> We had a brief discussion on the topic of delegated IPAM and the future of the Azure IPAM module in Cilium during today's 2023-05-31 community meeting, and there were some interesting points raised about the technical approaches and architectural models. Although we did not discuss OpenStack IPAM, the discussion may be relevant. For today, we will continue to have Azure IPAM in the tree, but I think it's worth considering whether alternative approaches like this may be a better fit for newly proposed IPAM modules. You can find the notes we took during the discussion [here](https://docs.google.com/document/d/1Y_4chDk4rznD6UgXPlPvn3Dc7l-ZutGajUv1eF0VDwQ/edit#bookmark=id.cl7yorzc9by3).


@joestringer thanks for your comments.

In my understanding, _Delegated IPAM CNI plugin_ fits for an independent plugin with complete IPAM functions. Currently, 
cloud provider IPAM modules(aws、alibaba、openstack) in cilium strongly depend on CRD ciliumnodes.cilium.io, operator reconcile, and existing IPAM skeleton codes(pkg/ipam/node.go node_manager.go).  

So _Delegated IPAM CNI plugin_ is absolutely good for cilium code maintenance,  but for now, it's not easy to move cloud provider IPAM modules out of the tree to keep them as independent IPAM plugins.

**Pull request closed without merging**
