### PR TITLE
bpf: allow llvm to probe the kernel for optimized insns set

### PR DESCRIPTION
**Pull request by borkmann**
Now that also LLVM supports [1] the new insns from [2], enable its use
for cilium programs, so we can benefit from reducing register pressure
which also reduces length & complexity of programs. Also improve doc a
bit wrt new instructions and JIT support.

  [1] https://github.com/llvm-mirror/llvm/commit/d7276a40d87b89aed89978dec6457a5b8b3a0db5
  [2] https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/commit/?id=078295fb9af507abce4976c6e9ff56a67da4e9a0

Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

### CODE REVIEW

**Review by tgraf — APPROVED** [review]

**Comment by jrfastab** [comment]
I need to dig through the code a bit but I thought there was an issue with doing a two step clang+llc compile wrt to switch statements generating jump tables.

**Comment by jrfastab** [comment]
On the other hand the `-target bpf` should be enough to stop the jump table from being generated so I think this is OK.

**Comment by borkmann** [comment]
I think this was only that when you don't set `-target bpf` such that clang assumes x86. I think we do this thing in `samples/bpf/Makefile`.

**Comment by jrfastab** [comment]
Yep `target bpf` is in the patch and necessary.

**Pull request merged**
