### PR TITLE
v1.6 backport 2020-04-17

### PR DESCRIPTION
**Pull request by jrfastab**
* #9649 cilium: encryption fixes for ipv6 and tear down
* #10218 cilium: encryption + tunnel improvements and fixes
* #10268 cilium: encryption, segfaults if existing non-Cilium xfrm policy without mark set exists
* #10551 cilium: encryption, additional mtu fix for non-default 1500B MTU

Note: Only IPv4 support added from #9649 IPv6 is not included here, we can debate if we want fib IPv6 support backported somewhere else but its strictly speaking not a fix. This was really an error on my side in original PR to mix a fix with a feature.

Note: Scripts broke on this set of backports so did this by hand comparing manual and v1.6

Once this PR is merged, you can update the PR labels via:

$ for pr in 9649 10218 10268 10551; do contrib/backporting/set-labels.py $pr done 1.6;

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by joestringer** [comment]
FYI gke/ with kernel runs are not supported on v1.6 branch so those should be fine to ignore.

**Comment by jrfastab** [comment]
bisecting...

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by aanm** [comment]
this PR has been marked as a draft PR since it had a WIP label. Please click in "Ready for review" [below vvv ] once the PR is ready to be reviewed. CI will still run for draft PRs.

**Comment by gandro** [comment]
I don't think we should close this PR as stale, since the backports are still marked as pending

**Comment by joestringer** [comment]
@gandro keeping it open doesn't necessarily solve the problem at hand ;-)

@jrfastab have you heard any reports/concerns on this recently? Is v1.7 better on this front? Given that v1.8 is right around the corner I wonder whether we should simply drop these backports assuming that users will get better encryption behaviour by upgrading to a newer release.

**Comment by jrfastab** [comment]
The only user I originally started this for was able to move to v1.7. I don't see any reason to keep them open at this time and its probably not worth it to pull in more patches.

**Comment by joestringer** [comment]
In the off chance anyone wants to track this, https://github.com/cilium/cilium/pull/10741 might be another fix to pull in as well.

**Pull request closed without merging**
