### PR TITLE
cli: Remove NodePort programs from native netdev upon cleanup

### LINKED ISSUE #8873: Remove BPF NodePort programs from native device upon "cilium cleanup"
Currently, we do not remove the attached BPF NodePort programs from ingress/egress of a native device when running `cilium cleanup --all-state`.

We could store the name of the native device in the generated `node_config.h` which would be read by `cilium cleanup --all-state` to determine the name and whether the programs were attached.

### PR DESCRIPTION
**Pull request by brb**
This PR makes `cilium cleanup` to remove NodePort BPF (`bpf_netdev.o`) programs from a native netdev. The native dev iface is read from `/var/run/cilium/state/globals/node_config.h`.

A follow-up: we should document that if a user was previously running with `--enable-node-port`, and afterwards decided to change `--device` or to switch from the direct mode to the tunnel mode, then they have to do `cilium cleanup` before changing the setting.

```release-note
cilium cleanup removes previously installed NodePort BPF programs
```

Fixes #8873.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10063)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by borkmann** [comment]
I think we'd also need to remove the cgroup progs via bpftool.

**Comment by brb** [comment]
> I think we'd also need to remove the cgroup progs via bpftool.

Created an issue for a follow-up: https://github.com/cilium/cilium/issues/10067.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by raybejjani** [comment]
@brb some jenkins happened and the GKE tests triggered for this PR. You should ignore them (as they will fail). Sorry!

**Review by aanm — APPROVED** [review]
>A follow-up: we should document that if a user was previously running with --enable-node-port, and >afterwards decided to change --device or to switch from the direct mode to the tunnel mode, then they >have to do cilium cleanup before changing the setting.

Telling the user to run a `cilium cleanup` might give unexpected behavior in the system as it removes a lot of stuff, it's basically an uninstall. As an alternative we should cleanup that netdev program from all interfaces automatically. However this won't really matter in the future as we plan to attach the netdev program on all interfaces available in the system.

**Comment by brb** [comment]
@aanm I will create another PR in which cilium-agent during bootstrap checks all devices whether bpf_netdev.o is loaded, and then removes the prog from not used devices.

**Pull request merged**
