### PR TITLE
v1.3 backports 2018-11-23

### PR DESCRIPTION
**Pull request by borkmann**
PRs backported:

* #6208
* #6062 

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6287)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
(On the last one Jenkins killed the test due to vm image download taking too long.)

**Comment by borkmann** [comment]
Same again, https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8161/execution/node/70/log/

**Comment by borkmann** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: all timed out 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8190/

**Comment by ianvernon** [comment]
test-me-please

**Comment by borkmann** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8203/

Same issue, getting killed during test run:
```
22:50:46   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
22:50:47 STEP: Restarting Cilium
22:51:18 Sending interrupt signal to process
22:51:20 cleaning up VMs started for runtime tests
22:51:20 
22:51:20 ---------------------------------------------------------
22:51:20 Received interrupt.  Running AfterSuite...
22:51:20 ^C again to terminate immediately
```

**Comment by ianvernon** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]
LGTM, but may lack context, so take this with a grain of salt ;-)

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
All tests passed, the ginkgo test didn't pass for k8s 1.12, the failure will be fixed by https://github.com/cilium/cilium/pull/6309

**Pull request merged**
