### PR TITLE
v1.15 Backports 2024-03-24

### PR DESCRIPTION
**Pull request by sayboras**
* [x] #31211 (@kaworu)
 * [x] #31504 (@bimmlerd)
 * [x] #31376 (@glrf)
    * :warning:  The test  TestGRPCClientConnBuilder_CertificateChange is failing consistently, do we need to bump google.golang.org/grpc to v1.62.1 to fix it ?
    * Thanks to Alex for pushing the fix
 * [x] #31503 (@mhofstetter)
 * [ ] #31373 (@loomkoom)
 * [x] #31469 (@YutaroHayakawa)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31211 31504 31376 31503 31373 31469
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.15

**Review by YutaroHayakawa — APPROVED** [review]
Thanks!

**Review by mhofstetter — APPROVED** [review]
Thanks Tam!

**Review by kaworu — APPROVED** [review]
My patch LGTM, thanks @sayboras!

**Review by bimmlerd — APPROVED** [review]
Thanks!

**Comment by bimmlerd** [comment]
AFAIK @glrf is on PTO for the week - might want to drop his PR for now if there's issues

**Comment by sayboras** [comment]
/test-backport-1.15

**Comment by sayboras** [comment]
Most of the reviews are in, CI is all green, marking this ready to merge.

**Review by aanm — APPROVED** [review]

**Pull request merged**
