### PR TITLE
Use the iptables 1.8.8 image on v1.12

### PR DESCRIPTION
**Pull request by margamanterola**
Use the new iptables image so that we run iptables 1.8.8 in v1.12

This addresses #22482, but for v1.12

- [x] #23163 -- images/runtime: bump iptables package to 1.8.8 (@jibi)
- [x] #21096 -- iptables: add support for iptables >= 1.8.7 (@jibi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 23163 21096; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Comment by margamanterola** [comment]
Please run the full conformance suite before merging :)

**Comment by jibi** [comment]
/test-backport-1.12

**Review by jibi — APPROVED** [review]

**Comment by jibi** [comment]
CI failures can be ignored as they are from the wrong testsuite (I run `/test` instead of `/test-backport-1.12` the first time)

**Comment by jibi** [comment]
No need to rerun CI, marking as ready

**Pull request merged**
