### PR TITLE
Fix k8s 1.12 generated daemonset files

### PR DESCRIPTION
**Pull request by aanm**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4754)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
previous flake https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4696/ apparently it didn't have the https://github.com/cilium/cilium/commit/667304499ed46c7afc6c3e68a2fd77bcfaa91e45

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
