### PR TITLE
vagrant: add workaround for kube-proxy in iptables

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by tgraf** [comment]
Why are we not running `kube-proxy`?

**Comment by aanm** [comment]
> Why are we not running kube-proxy?

We are running kube-proxy

**Comment by tgraf** [comment]
> We are running kube-proxy

Why is the kube-proxy MASQUERADE rule not working?

**Comment by tgraf** [comment]
I'm happy to merge this to unblock everyone but I'm curious to why this is needed in the longer run.

**Review by tgraf — APPROVED** [review]

**Pull request merged**
