### PR TITLE
Backport v1.14: CI: Add IPsec key rotation test

### PR DESCRIPTION
**Pull request by jschwinger233**
Manual backport of
- https://github.com/cilium/cilium/pull/26730 
- https://github.com/cilium/cilium/pull/27203 
- https://github.com/cilium/cilium/pull/27883 

```upstream-prs
for pr in 26730 27203 27883; do contrib/backporting/set-labels.py $pr done 1.14; done
```

Signed-off-by: Zhichuan Liang <gray.liang@isovalent.com>

### CODE REVIEW

**Comment by jschwinger233** [comment]
/test-backport-1.14

**Review by nbusseneau — APPROVED** [review]

**Comment by jschwinger233** [comment]
I suppose it's ready to merge? Let me know if anything requires change.

**Comment by brb** [comment]
> I suppose it's ready to merge? Let me know if anything requires change.

Yep!

**Pull request merged**
