### PR TITLE
ci: collect sysdump as a separate workflow in L4LB tests

### LINKED ISSUE #18221: CI:  Cilium L4LB XDP: Collect sysdump as part of workflow
The L4LB workflow uses [a Bash script](https://github.com/cilium/cilium/blob/701967f31b7121dc811b3de6ca0fbbb284009749/test/l4lb/test.sh) to run tests (step `Run tests` of the workflow). That Bash script also [collects the sysdump in case of error](https://github.com/cilium/cilium/blob/701967f31b7121dc811b3de6ca0fbbb284009749/test/l4lb/test.sh#L93). We should instead collect the sysdump as a separate step in the workflow, for consistency with other workflows and to get the proper information [when it fails](https://github.com/cilium/cilium/runs/4477255000?check_suite_focus=true).

cc @brb

### PR DESCRIPTION
**Pull request by oblazek**
Fixes: #18221

Signed-off-by: Ondrej Blazek <ondrej.blazek@firma.seznam.cz>

### CODE REVIEW

**Review by christarazi — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by jibi — APPROVED** [review]
Filled a draft PR to test this (as we can't run the PR workflow here since the branch is not in the base repository) https://github.com/cilium/cilium/pull/18399/commits/0b1f60fb0aca104a674e97351d662e711578ee42

**Comment by jibi** [comment]
sysdump collected successfully on failure :heavy_check_mark:  https://github.com/cilium/cilium/actions/runs/1666872689

**Comment by pchaigno** [comment]
Thanks @jibi! :pray:

**Comment by brb** [comment]
@oblazek @pchaigno @jibi Too late to the party, but shouldn't we have updated `tests-l4lb-v1.1{0,1}.yaml` too?

**Comment by pchaigno** [comment]
Oh, right! Completely forgot about those :facepalm:

@oblazek Could you make the same change to those two other files? They are used to run the workflow on stable branches v1.11 and v1.10.

**Comment by oblazek** [comment]
yes will do ;) sorry, wasn't sure

**Comment by oblazek** [comment]
fix here https://github.com/cilium/cilium/pull/18428

**Pull request merged**
