### PR TITLE
[v1.15] bpf: ifindex trace fixes

### PR DESCRIPTION
**Pull request by julianwiedmann**
Minor adjustments in the templating patch + resolving trivial conflicts, here is a manual backport of 

* [ ] #33083
* [ ] #33085

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33083 33085
```

### CODE REVIEW

**Comment by julianwiedmann** [comment]
/test-backport-1.15

**Comment by julianwiedmann** [comment]
/test-backport-1.15

**Comment by julianwiedmann** [comment]
/test-backport-1.15

**Comment by julianwiedmann** [comment]
/test-backport-1.15

**Review by ysksuzuki — APPROVED** [review]
LGTM

**Review by aditighag — APPROVED** [review]

**Pull request merged**
