### PR TITLE
Prepare for release v1.0.7

### PR DESCRIPTION
**Pull request by ianvernon**
Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5893)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
Star Wars Demo tests failed for the K8s tests: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1075/testReport/junit/k8s-1/8/K8sDemosTest_Tests_Star_Wars_Demo/

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by ianvernon** [comment]
The Star Wars test failed because in the v1.0 branch, we never actually deploy the file https://github.com/cilium/star-wars-demo/blob/master/02-xwing.yaml , which contains the 'xwing' pods with label 'alliance', which the test expects to be deployed, but are not. 

Applying the following patch makes the test pass locally for me. Some of the commented out / changed lines are to make the test run on my local setup, because `go vet` fails if I don't perform said modifications:

```
$ git diff
diff --git a/test/k8sT/Nightly.go b/test/k8sT/Nightly.go
index 7b2bf335c..1504a333a 100644
--- a/test/k8sT/Nightly.go
+++ b/test/k8sT/Nightly.go
@@ -49,7 +49,7 @@ var _ = Describe("NightlyEpsMeasurement", func() {
        endpointsTimeout := endpointTimeout * time.Duration(endpointCount)
        manifestPath := "tmp.yaml"
        vagrantManifestPath := path.Join(helpers.BasePath, manifestPath)
-       var lastServer int
+       //var lastServer int
        var err error
 
        initialize := func() {
@@ -99,7 +99,7 @@ var _ = Describe("NightlyEpsMeasurement", func() {
        })
 
        deployEndpoints := func() {
-               _, lastServer, err = helpers.GenerateManifestForEndpoints(endpointCount, manifestPath)
+               _, _, err = helpers.GenerateManifestForEndpoints(endpointCount, manifestPath)
                ExpectWithOffset(1, err).Should(BeNil(), "Manifest cannot be created correctly")
                res := kubectl.Apply(vagrantManifestPath)
                res.ExpectSuccess("cannot apply eps manifest :%s", res.GetDebugMessage())
diff --git a/test/k8sT/demos.go b/test/k8sT/demos.go
index cfa479049..9af501866 100644
--- a/test/k8sT/demos.go
+++ b/test/k8sT/demos.go
@@ -40,7 +40,7 @@ func getStarWarsResourceLink(file string) string {
 var _ = Describe(demoTestName, func() {
 
        var (
-               demoPath   string
+               //demoPath   string
                once       sync.Once
                kubectl    *helpers.Kubectl
                logger     *logrus.Entry
@@ -57,7 +57,7 @@ var _ = Describe(demoTestName, func() {
                kubectl = helpers.CreateKubectl(helpers.K8s1VMName(), logger)
 
                //Manifest paths
-               demoPath = kubectl.ManifestGet("demo.yaml")
+               //demoPath = kubectl.ManifestGet("demo.yaml")
 
                // TODO (ianvernon) - factor this code out into separate functions as it's
                // boilerplate for most K8s test setup.
@@ -125,6 +125,10 @@ var _ = Describe(demoTestName, func() {
                _, err = kubectl.WaitforPods(helpers.DefaultNamespace, fmt.Sprintf("-l %s", empireLabel), 300)
                Expect(err).Should(BeNil(), "Empire pods are not ready after timeout")
 
+               By("Applying xwing deployment")
+               res = kubectl.Apply(xwingYAMLLink)
+               res.ExpectSuccess("unable to apply %s: %s", xwingYAMLLink, res.CombineOutput())
+
                By("Getting xwing pod names")
                xwingPods, err := kubectl.GetPodNames(helpers.DefaultNamespace, allianceLabel)
                Expect(err).Should(BeNil())
```

I can post that patch as a PR into the v1.0 branch to stabilize it after this is merged. I'm going to merge this since the test failure does not affect the quality of the code that will actually be used in user environments.

**Pull request merged**
