### PR TITLE
endpoint: Endpoint state directories can be left behind after build failure

### PR DESCRIPTION
**Pull request by manalibhutiyani**
Failed regeneration files `XXXXX_next_fail` may stick around after regeneration.
We are correctly deleting these files on regeneration, but not on deletion of endpoint.
This commit deletes the endpoint XXX_next_fail files on endpoint deletion.

Fixes: #3494
Fixes: #3175

Signed-Off-By: Manali Bhutiyani <manali@covalent.io>

```release-note
Remove endpoint  state directories left behind after build failure
```

### CODE REVIEW

**Comment by manalibhutiyani** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Looks good. We could probably reuse the `failedDirectoryPath()` in `pkg/endpoint/policy.go` too, to ensure that the directory path is consistently determined.

One more comment, for commit messages it is useful for it to describe what the commit does in imperative form, rather than a declaration about the state. When I read through git logs and see a commit title that says `Endpoint state directories can be left behind after build failure`, it's not immediately clear to me that the commit is introducing this behaviour intentionally, or trying to remove the behaviour. If instead it's in the form `endpoint: Remove state directories left behind after build failure`, then it's clearer that the commit is removing that behaviour.

Thanks!

**Review by ianvernon — APPROVED** [review]

**Comment by manalibhutiyani** [comment]
Sure. I can change the commit message to something more meaningful. Regarding `pkg/endpoint/policy.go` changes, I cannot reuse `failedDirectoryPath` as is, since `failDir` points to previous endpoint and not the current one. Not sure if sending `failedDir` as an argument simply to do a fileJoin makes a lot of sense.

**Comment by manalibhutiyani** [comment]
test-me-please

**Comment by joestringer** [comment]
@manalibhutiyani Looking through `(e *Endpoint) regenerate()`, the logic basically creates the `failDir` path  based on `tmpDir`, which is based on the `origDir` (which, finally, is from the base path + endpoint ID). AFAIK we don't change the endpoint ID after it is first created, so it should still be valid there, shouldn't it?

**Comment by manalibhutiyani** [comment]
@joestringer Yup that's right.
```
+++ b/pkg/endpoint/policy.go
@@ -760,9 +760,9 @@ func (e *Endpoint) regenerate(owner Owner, reason string) (retErr error) {
        revision, err := e.regenerateBPF(owner, tmpDir, reason)
 
        // If generation fails, keep the directory around. If it ever succeeds
-       // again, clean up this copy.
-       failDir := tmpDir + "_fail"
-       os.RemoveAll(failDir) // Most likely will not exist; ignore failure.
+       // again, clean up the XXX_next_fail copy.
+       failDir := e.failedDirectoryPath()
+       e.removeFailedDirectory()
        if err != nil {
                e.getLogger().WithFields(logrus.Fields{
                        logfields.Path: failDir,
Manalis-MBP:cilium manalibhutiyani$ 

```

**Comment by manalibhutiyani** [comment]
I think the `e.removeFailedDirectory()` is not needed, so can keep the logic as is.

**Comment by manalibhutiyani** [comment]
test-me-please

**Comment by raybejjani** [comment]
backport https://github.com/cilium/cilium/pull/3982

**Pull request merged**
