### PR TITLE
CI: WaitForPodsRunning respects filter and checks containers

### PR DESCRIPTION
**Pull request by raybejjani**
https://github.com/cilium/cilium/pull/7946 might be a more comprehensive change, but I'm looking for some feedback on it.

WaitForPodsRunning, used by ExpectCiliumRunning, accidentally ignored
the namespace and filter passed in, hardcoding them to "kube-system" and
"-l k8s-app=cilium". This is now fixed.
It also used pod scheduling status as a proxy for readiness, instead of
the per-container Ready flag. The per-container flag requires the
container to pass its readiness check, a stricter test.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7943)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-nightly

**Comment by raybejjani** [comment]
test-missed-k8s

**Review by eloycoto — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Comment by raybejjani** [comment]
I went with https://github.com/cilium/cilium/pull/7946

**Pull request closed without merging**
