### PR TITLE
Replace the string with constants from the http package

### PR DESCRIPTION
**Pull request by Fish-pro**
Signed-off-by: Fish-pro [zechun.chen@daocloud.io](mailto:zechun.chen@daocloud.io)

### CODE REVIEW

**Comment by Fish-pro** [comment]
The main branch merges frequently, resulting in need update branch?

**Comment by Fish-pro** [comment]
image
Why is the document checked without modification? Why

**Comment by mhofstetter** [comment]
thanks for your contribution @Fish-pro 

> The main branch merges frequently, resulting in need update branch?

no need to update the branch on every merge in main - except you would face some conflicts or issues with CI.

> Why is the document checked without modification? Why

`custom-vet` checks the whole project within the check `Go-related checks / precheck`. looks like you picked up an issue which landed in main when rebasing. https://github.com/cilium/cilium/pull/25615 fixes this. this PR needs another rebase once the fix has been merged.

**Review by mhofstetter — APPROVED** [review]

**Review by jschwinger233 — APPROVED** [review]

**Pull request merged**
