### PR TITLE
ipvlan: use github.com/cilium/ebpf to create map and load program

### PR DESCRIPTION
**Pull request by tklauser**
Reviewable by commit, see individual commit messages for details.

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
Rebased after #14056 was merged.

**Comment by tklauser** [comment]
test-me-please

**Review by jibi — APPROVED** [review]
great to see we are starting to move towards using `cilium/ebpf` :fire::fire:

**Review by nathanjsweet — APPROVED** [review]
Ditto on moving to cilium/ebpf

**Comment by joestringer** [comment]
QQ, what kind of validation have we done on this? When I grep for `ipvlan` under `test/`, I see no entries so I'm not sure the CI would point out any potential impact from these changes.

**Comment by tklauser** [comment]
> QQ, what kind of validation have we done on this? When I grep for `ipvlan` under `test/`, I see no entries so I'm not sure the CI would point out any potential impact from these changes.

I was wrongly assuming that this is covered by the docker-based runtime tests, sorry about that. I'll run the [IPVLAN-based Networking GSG](https://docs.cilium.io/en/latest/gettingstarted/ipvlan/) to verify this.

**Pull request merged**
