### PR TITLE
install: Update image digests for v1.13.16

### PR DESCRIPTION
**Pull request by nebril**
Generated from https://github.com/cilium/cilium/actions/runs/9093775032.

`docker.io/cilium/cilium:v1.13.16@sha256:f1f26a973419ba449a47a08e8c4c8e280d8941bb4fd77d1e992e2721425c0629`
`quay.io/cilium/cilium:v1.13.16@sha256:f1f26a973419ba449a47a08e8c4c8e280d8941bb4fd77d1e992e2721425c0629`

`docker.io/cilium/clustermesh-apiserver:v1.13.16@sha256:5fe762a36b260b400458bb1381e3e8b9453969bb9f4225926645baf4f8abf5ec`
`quay.io/cilium/clustermesh-apiserver:v1.13.16@sha256:5fe762a36b260b400458bb1381e3e8b9453969bb9f4225926645baf4f8abf5ec`

`docker.io/cilium/docker-plugin:v1.13.16@sha256:e4263bf37acccb2256d164cc443afd4fdd43d41c247a0c634abdd51f8df4d917`
`quay.io/cilium/docker-plugin:v1.13.16@sha256:e4263bf37acccb2256d164cc443afd4fdd43d41c247a0c634abdd51f8df4d917`

`docker.io/cilium/hubble-relay:v1.13.16@sha256:bd54f5ebd81e2b911f3453fda344280510d1695abbe24d097ed2f784e5a82840`
`quay.io/cilium/hubble-relay:v1.13.16@sha256:bd54f5ebd81e2b911f3453fda344280510d1695abbe24d097ed2f784e5a82840`

`docker.io/cilium/operator-alibabacloud:v1.13.16@sha256:cd3cf713a9f6658ae62ebf073134f7286228aae36e5946d543a0c8c00eb7fa60`
`quay.io/cilium/operator-alibabacloud:v1.13.16@sha256:cd3cf713a9f6658ae62ebf073134f7286228aae36e5946d543a0c8c00eb7fa60`

`docker.io/cilium/operator-aws:v1.13.16@sha256:e068622352cd2929f98367cd59203b403ab5cc766957f12ac0663c0f4c0b6cdf`
`quay.io/cilium/operator-aws:v1.13.16@sha256:e068622352cd2929f98367cd59203b403ab5cc766957f12ac0663c0f4c0b6cdf`

`docker.io/cilium/operator-azure:v1.13.16@sha256:60d814726d9b9b27e7b2bbbf27d8e44dfdef6271c2d69bd69b1194b11202ea29`
`quay.io/cilium/operator-azure:v1.13.16@sha256:60d814726d9b9b27e7b2bbbf27d8e44dfdef6271c2d69bd69b1194b11202ea29`

`docker.io/cilium/operator-generic:v1.13.16@sha256:a2711d5b891da9fd66c2116b77782b58a1a428eb4abdab2dd3ac1221937d846b`
`quay.io/cilium/operator-generic:v1.13.16@sha256:a2711d5b891da9fd66c2116b77782b58a1a428eb4abdab2dd3ac1221937d846b`

`docker.io/cilium/operator:v1.13.16@sha256:e161e6f883f17b136799abb3e5b910cf1a98da8828f05f1a42f3b6ecf109e45d`
`quay.io/cilium/operator:v1.13.16@sha256:e161e6f883f17b136799abb3e5b910cf1a98da8828f05f1a42f3b6ecf109e45d`

### CODE REVIEW

**Review by gentoo-root — APPROVED** [review]

**Review by squeed — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Comment by nebril** [comment]
/test-backport-1.13

**Comment by nebril** [comment]
/test-1.19-4.19

**Comment by nebril** [comment]
/test-1.22-4.19

**Comment by qmonnet** [comment]
/test-1.17-4.19

**Review by julianwiedmann — APPROVED** [review]

**Pull request merged**
