### PR TITLE
test: bump latest helm chart version

### PR DESCRIPTION
**Pull request by aanm**
Fixes: 138d556b95d4 ("preparing v1.9 dev cycle")
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
retest-4.9

**Comment by aanm** [comment]
retest-netnext

**Comment by aanm** [comment]
retest-net-next

**Review by nebril — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Pull request merged**
