### PR TITLE
datapath: Pass proxy port in to-proxy traces

### PR DESCRIPTION
**Pull request by jrajahalme**
Include proxy port in the to-proxy trace messages.

Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>

### CODE REVIEW

**Comment by jrajahalme** [comment]
The CEP in question (`default/k8s2-client`) is not part of this test, it must be a remnant from a prior test. It would be misleading to track this as a flake on the Istio test.

**Comment by joestringer** [comment]
> This happens during endpoint regeneration, after which the endpoint is deleted. Is it possible that this error log from the endpoint synchronizer should not be considered an error at all? K8s has deleted the pod, but Cilium agent has not yet processed the deletion as it is in the middle of regeneration?

:thinking: I think this makes sense. This controller is running because the endpoint was previously provisioned. Presumably by the time this controller first runs, there is guaranteed to be a k8s pod available so there's no way for this error to be returned. When the pod is deleted, if regeneration is under way then we probably haven't yet cancelled the `ctx` that is passed into this controller, so we don't yet know that the resource is gone. That said, if we attempt to update it and get a 'not found' error (specifically this one) then the only case I can think where this would occur.. is if the pod is being deleted. So yeah we shouldn't need to care in that case since this is probably the one last spurious error that this controller would see before it gets shut down.

Either we can move the 'Context' cancellation earlier for the `ctx` passed into this controller, or we can just detect the 'not found' error type and ignore that specific one without logging. :+1:

**Review by qmonnet — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Pull request merged**
