### PR TITLE
k8s: Remove deprecated identity status field

### PR DESCRIPTION
**Pull request by christarazi**
Following the deprecation notice from
https://github.com/cilium/cilium/pull/11275, remove the field.

### CODE REVIEW

**Comment by christarazi** [comment]
test-me-please

**Review by sayboras — APPROVED** [review]
LGTM :1st_place_medal:  

Just want to check if any docs (e.g. spec, upgrade note, etc) is required, or this change will be just transparent to users.

**Comment by christarazi** [comment]
> LGTM 1st_place_medal
> 
> Just want to check if any docs (e.g. spec, upgrade note, etc) is required, or this change will be just transparent to users.

The change should be transparent as the aforementioned PR migrates its usage to be under the purview of CiliumEndpoint. I did a quick scan over the docs and don't see any mention of this field. Thanks for the tip.

**Review by rolinh — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by christarazi** [comment]
retest-net-next

**Comment by christarazi** [comment]
Code owner approval and full CI have passed. Marking ready to merge. (Not sure why maintainer's little helper didn't detect this PR as ready.)

**Pull request merged**
