### PR TITLE
bump k8s dependencies and test to v1.18.1

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by tklauser — CHANGES_REQUESTED** [review]
Maybe run `go mod tidy` to get rid of stale entries in `go.sum`?

**Comment by aanm** [comment]
@tklauser good finding. Done.

**Comment by aanm** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Comment by aanm** [comment]
restart-ginkgo

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/10882 and travis CI for arm64 was also disabled upstream by #10978

**Comment by joestringer** [comment]
@aanm I haven't seen exit code 6 before, this is a different failure than #10882 :

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18766/testReport/junit/Suite-k8s-1/18/K8sDemosTest_Tests_Star_Wars_Demo/

**Comment by joestringer** [comment]
I filed #11002 in case we see this again. I haven't seen this particular failure before so it's plausible that it's related to this PR, particularly since this PR changes the v1.18 k8s version.

**Pull request merged**
