### PR TITLE
USERS.md: Add Florian Heubeck to the list of users

### PR DESCRIPTION
**Pull request by heubeck**
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### CODE REVIEW

**Review by xmulligan — APPROVED** [review]

**Comment by ti-mo** [comment]
@heubeck Sorry, but I think there's a small misunderstanding here. When we refer to 'users' of Cilium, we generally mean organizations that run it, not individual users that have experience with it.

Instead, please add the organization(s) you deploy Cilium at! I'll convert this to a draft for now, click `Ready for review` at the bottom if you've made changes and want another review. Thank you!

**Comment by heubeck** [comment]
> @heubeck Sorry, but I think there's a small misunderstanding here. When we refer to 'users' of Cilium, we generally mean organizations that run it, not individual users that have experience with it.
> 
> Instead, please add the organization(s) you deploy Cilium at! I'll convert this to a draft for now, click `Ready for review` at the bottom if you've made changes and want another review. Thank you!

thought so as well, but:
https://www.linkedin.com/feed/update/urn:li:activity:7164279305705914368?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7164279305705914368%2C7165246083751632897%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287165246083751632897%2Curn%3Ali%3Aactivity%3A7164279305705914368%29
and
https://github.com/cilium/cilium/blob/main/USERS.md?plain=1#L23 ("or individual")

;)

**Comment by xmulligan** [comment]
Can you be a bit more specific about how you use Cilium? The goal of the users doc is to help other people understand how Cilium can be used in production and what exactly other people are using it for

**Comment by heubeck** [comment]
> Can you be a bit more specific about how you use Cilium? The goal of the users doc is to help other people understand how Cilium can be used in production and what exactly other people are using it for

First of all: Fine with not getting added, just reacted on that comment on linkedin ;)

I'm doing demos and soon workshops about progressive delivery, using cilium as gateway api implementation: https://github.com/heubeck/flux-kind-flagger-cilium

**Comment by xmulligan** [comment]
Sorry that was my mistake for not making it more clear. I really mean to ask if you are using it in production at MediaMarktSaturn

**Comment by heubeck** [comment]
> Sorry that was my mistake for not making it more clear. I really mean to ask if you are using it in production at MediaMarktSaturn

Ok 🫣
Unfortunately not (yet) 😞

maybe you should adjust the statement `Name of user (company or individual)` in the user-to-be-added template.

Will come back here, once we have our first production use in place @ MMS 🫠

**Comment by xmulligan** [comment]
I've updated the description here to make it more hopefully more clear https://github.com/cilium/cilium/pull/31316

Looking forward to having the story about production deployments at MMS

**Pull request closed without merging**
