### PR TITLE
test: enable PodSecurityPolicy in CI

### LINKED ISSUE #10659: Enable K8s PSP in the CI
We had to disable Pod Security Policies feature flag since the CI was not running with them. More info https://github.com/cilium/cilium/pull/10658

cc @maxbischoff

### PR DESCRIPTION
**Pull request by tklauser**
Enable for k8s 1.18 only for CI testing.

Fixes #10659

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-missed-k8s

**Comment by tklauser** [comment]
test-upstream-k8s

**Comment by tklauser** [comment]
test-missed-k8s

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
restart-ginkgo

**Comment by tklauser** [comment]
test-me-please

**Comment by joestringer** [comment]
@tklauser are you actively working on this? In PR #10681 this PR was identified as a blocker before applying those changes.

**Comment by tklauser** [comment]
@joestringer Sorry, this somehow fell between the cracks. I haven't worked on it for the last few days. Currently, the PR is not in a working state as the `log-gatherer` won't come up due to the PSP being active. The last commit in the PR (currently 45d5de89ab4aadfad967137daa5ffc94477c73c7) adds a `PodSecurityPolicy` for `log-gatherer` but it seems to be missing something. If anyone more familiar with k8s, PSPs and our CI setup wants to pick this up and get it working, please feel free to do so. I could also invest some cycles into this in the next few days.

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Comment by aanm** [comment]
retest-4.19

**Comment by aanm** [comment]
retest-4.19

**Comment by aanm** [comment]
retest-4.19

**Comment by tklauser** [comment]
retest-4.19

**Comment by aanm** [comment]
retest-4.19

**Comment by aanm** [comment]
retest-4.19

**Comment by aanm** [comment]
retest-4.19

**Comment by aanm** [comment]
retest-4.19

**Comment by aanm** [comment]
test-me-please

**Comment by sayboras** [comment]
@aanm @tklauser Seems like PSP will unlikely go to GA, and probably get deprecated as per https://github.com/kubernetes/enhancements/issues/5

I am curious what cilium roadmap on this matter will look like on this matter.

**Comment by aanm** [comment]
@sayboras interesting, I've been actually working on this PR lately. Thank you for let me know!

**Comment by aanm** [comment]
Closing this PR. PodSecurityPolicy will be removed from Kubernetes https://github.com/kubernetes/kubernetes/pull/90603

**Pull request closed without merging**
