### PR TITLE
datapath: Avoid MASQing NodePort replies

### LINKED ISSUE #8292: Cilium: masquerade rule broken in direct routing (host to remote EP)
Master affected; I've used direct routing. Setup is two nodes with docker (likely not limited to it). The traffic flow looks as follows. curl from *host* 192.168.1.125 talking to remote endpoint (10.12.111.220:80 is nginx container) on 192.168.1.120:
```
root@tank:~# tcpdump -i any port 80 -n
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
12:13:58.390539 IP 192.168.1.125.43670 > 10.12.111.220.80: Flags [S], seq 394292427, win 64240, options [mss 1460,sackOK,TS val 779704966 ecr 0,nop,wscale 7], length 0
12:13:58.390548 IP 192.168.1.125.43670 > 10.12.111.220.80: Flags [S], seq 394292427, win 64240, options [mss 1460,sackOK,TS val 779704966 ecr 0,nop,wscale 7], length 0
12:13:58.390575 IP 10.12.111.220.80 > 192.168.1.125.43670: Flags [S.], seq 174649252, ack 394292428, win 65160, options [mss 1460,sackOK,TS val 875640306 ecr 779704966,nop,wscale 7], length 0
12:13:58.390590 IP 10.12.111.220.80 > 192.168.1.125.43670: Flags [S.], seq 174649252, ack 394292428, win 65160, options [mss 1460,sackOK,TS val 875640306 ecr 779704966,nop,wscale 7], length 0
12:13:58.390784 IP 192.168.1.125.43670 > 10.12.111.220.80: Flags [.], ack 1, win 502, options [nop,nop,TS val 779704967 ecr 875640306], length 0
12:13:58.390788 IP 192.168.1.125.43670 > 10.12.111.220.80: Flags [.], ack 1, win 502, options [nop,nop,TS val 779704967 ecr 875640306], length 0
12:13:58.390790 IP 192.168.1.125.43670 > 10.12.111.220.80: Flags [P.], seq 1:78, ack 1, win 502, options [nop,nop,TS val 779704967 ecr 875640306], length 77: HTTP: GET / HTTP/1.1
12:13:58.390791 IP 192.168.1.125.43670 > 10.12.111.220.80: Flags [P.], seq 1:78, ack 1, win 502, options [nop,nop,TS val 779704967 ecr 875640306], length 77: HTTP: GET / HTTP/1.1
12:13:58.390819 IP 10.12.111.220.80 > 192.168.1.125.43670: Flags [.], ack 78, win 509, options [nop,nop,TS val 875640306 ecr 779704967], length 0
12:13:58.390835 IP 192.168.1.120.80 > 192.168.1.125.43670: Flags [.], ack 394292505, win 509, options [nop,nop,TS val 875640306 ecr 779704967], length 0
12:13:58.390903 IP 10.12.111.220.80 > 192.168.1.125.43670: Flags [P.], seq 1:239, ack 78, win 509, options [nop,nop,TS val 875640306 ecr 779704967], length 238: HTTP: HTTP/1.1 200 OK
12:13:58.390917 IP 192.168.1.120.80 > 192.168.1.125.43670: Flags [P.], seq 0:238, ack 1, win 509, options [nop,nop,TS val 875640306 ecr 779704967], length 238: HTTP: HTTP/1.1 200 OK
12:13:58.390947 IP 10.12.111.220.80 > 192.168.1.125.43670: Flags [P.], seq 239:851, ack 78, win 509, options [nop,nop,TS val 875640306 ecr 779704967], length 612: HTTP
12:13:58.390953 IP 192.168.1.125.43670 > 192.168.1.120.80: Flags [R], seq 394292505, win 0, length 0
12:13:58.390954 IP 192.168.1.120.80 > 192.168.1.125.43670: Flags [P.], seq 238:850, ack 1, win 509, options [nop,nop,TS val 875640306 ecr 779704967], length 612: HTTP
12:13:58.390962 IP 192.168.1.125.43670 > 10.12.111.220.80: Flags [R], seq 394292505, win 0, length 0
12:13:58.390993 IP 192.168.1.125.43670 > 192.168.1.120.80: Flags [R], seq 394292505, win 0, length 0
12:13:58.391050 IP 192.168.1.125.43670 > 192.168.1.120.80: Flags [R], seq 394292505, win 0, length 0
12:13:58.597599 IP 192.168.1.125.43670 > 10.12.111.220.80: Flags [P.], seq 1:78, ack 1, win 502, options [nop,nop,TS val 779705173 ecr 875640306], length 77: HTTP: GET / HTTP/1.1
12:13:58.597604 IP 192.168.1.125.43670 > 10.12.111.220.80: Flags [P.], seq 1:78, ack 1, win 502, options [nop,nop,TS val 779705173 ecr 875640306], length 77: HTTP: GET / HTTP/1.1
12:13:58.597619 IP 10.12.111.220.80 > 192.168.1.125.43670: Flags [R], seq 174649253, win 0, length 0
12:13:58.597628 IP 10.12.111.220.80 > 192.168.1.125.43670: Flags [R], seq 174649253, win 0, length 0
```
Notice the NAT in the middle of the connection:
```
12:13:58.390819 IP 10.12.111.220.80 > 192.168.1.125.43670: Flags [.], ack 78, win 509, options [nop,nop,TS val 875640306 ecr 779704967], length 0
12:13:58.390835 IP 192.168.1.120.80 > 192.168.1.125.43670: Flags [.], ack 394292505, win 509, options [nop,nop,TS val 875640306 ecr 779704967], length 0
```
This issue does *not* occur when endpoint talks to endpoint over wire. Also, it's fixed when `--masquerade=false` is set.

This rule is the affected one which causes the bug; counter before/after:
```
-[16:832] -A CILIUM_POST -s 10.12.0.0/16 ! -d 10.0.0.0/8 ! -o cilium_+ -m comment --comment "cilium masquerade non-cluster" -j MASQUERADE
+[17:884] -A CILIUM_POST -s 10.12.0.0/16 ! -d 10.0.0.0/8 ! -o cilium_+ -m comment --comment "cilium masquerade non-cluster" -j MASQUERADE
```

### PR DESCRIPTION
**Pull request by brb**
This PR introduces a new skb mark which denotes that a packet is a reply to a NodePort request.

This is needed, as all NodePort requests (but not replies) bypass the netfilter conntrack table and due to some weird `nf_conntrack` logic, starting with a second reply, replies get MASQUERADed. The mark makes such replies to be excluded from the Cilium MASQ rule in the `nat/POSTROUTING` chain.

The mark will go away once we introduce a BPF MASQ support for the veth datapath mode.

Partly (as it covers only NodePort case) fixes https://github.com/cilium/cilium/issues/8292.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8480)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failed due to many weird errors, e.g.:
```
[2019-07-05T15:43:07.837Z]     [91mcannot install Demo application
[2019-07-05T15:43:07.837Z]     Expected command: kubectl apply -f  /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/demo_ds.yaml 
[2019-07-05T15:43:07.837Z]     To succeed, but it failed:
[2019-07-05T15:43:07.837Z]     Exitcode: 1 
[2019-07-05T15:43:07.837Z]     Stdout:
[2019-07-05T15:43:07.837Z]      	 
[2019-07-05T15:43:07.837Z]     Stderr:
```

**Comment by brb** [comment]
test-me-please

**Pull request merged**
