### PR TITLE
helm: ensure defaultMode=0400 for projected volumes containing secrets

### PR DESCRIPTION
**Pull request by rolinh**
It seems that these volumes were wrongly given permission `420` (`420` decimal == `0644` octal) instead of `0400`, meaning that they were world readable and user writable. Secrets should only be readable by the actual user, thus with permission `0400`.

### CODE REVIEW

**Review by joestringer — APPROVED** [review]
Looks right to me, I assume that CI should complain if there's any real problem with these permission changes?

**Comment by rolinh** [comment]
> Looks right to me, I assume that CI should complain if there's any real problem with these permission changes?

That's my assumption, yes.

**Comment by rolinh** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]
Nice catch. I think we have the same issue in cilium-cli:

https://github.com/cilium/cilium-cli/blob/master/install/install.go#L40

https://github.com/cilium/cilium-cli/blob/master/clustermesh/clustermesh.go#L49

**Review by kaworu — APPROVED** [review]
Thanks for the patch!

**Comment by kaworu** [comment]
> It seems that these volumes were wrongly given permission 420 instead of 0400, giving write permission to the group

Actually, `420` is in decimal so before this patch the `defaultMode` expressed in octal would be `0644`.

**Review by sayboras — APPROVED** [review]

**Comment by tklauser** [comment]
> Nice catch. I think we have the same issue in cilium-cli:
> 
> https://github.com/cilium/cilium-cli/blob/master/install/install.go#L40
> 
> https://github.com/cilium/cilium-cli/blob/master/clustermesh/clustermesh.go#L49

https://github.com/cilium/cilium-cli/pull/539

**Review by joestringer — CHANGES_REQUESTED** [review]
Given Alex's report that these YAML values do not support Octal and the previous values were decimal (and correct), it sounds like we shouldn't push forward with this.

**Comment by rolinh** [comment]
> Given Alex's report that these YAML values do not support Octal and the previous values were decimal (and correct), it sounds like we shouldn't push forward with this.

I'm not sure I follow. Alex's point is that these permissions were probably inadvertently decimal instead of octal because of the missing leading 0. The decimal value 420 happens to be 0644 octal which is [the default value if not specified](https://kubernetes.io/docs/concepts/configuration/secret/#secret-files-permissions). However, I think that what we probably want is actually 0400, as per this PR change, as YAML supports octal notation.

> Note that the _JSON spec doesn't support octal notation_, so use the value 256 for 0400 permissions. **If you use YAML** instead of JSON for the Pod, **you can use octal notation to specify permissions in a more natural way**.

I will however update the PR to add a note that the leading 0 is actually important.

**Review by joestringer — APPROVED** [review]
OK yeah my misunderstanding then. :+1:

**Comment by kaworu** [comment]
@joestringer Sorry, my comment was unclear. My guess is that the decimal `420` was meant to be `0420`, as (1) `420=0644` is the default (thanks @rolinh for pointing it out) and (2) we have an actual `0420` in `install/kubernetes/cilium/templates/clustermesh-apiserver/deployment.yaml`.

In any case, I still think the PR is correct and improving the situation. However, it's a "bigger change" than we originally thought it was.

---

@rolinh From the commit message (emphasis mine):

> […] It seems that these volumes were wrongly given permission 420 (420 decimal == 0644 octal) _instead of 0400_

Did you meant _instead of 0420_ instead? I'm

**Comment by rolinh** [comment]
test-me-please

**Review by nathanjsweet — APPROVED** [review]

**Comment by rolinh** [comment]
ci-aks

**Pull request merged**
