### PR TITLE
[v1.13] vagrant: Bump Vagrant box versions

### PR DESCRIPTION
**Pull request by tklauser**
These include Go 1.21 which is needed to update the Go toolchain to a supported version in #29817.

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.13

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
/test-1.21-4.19

**Comment by tklauser** [comment]
/test-1.26-net-next

**Review by squeed — APPROVED** [review]

**Pull request closed without merging**
