### PR TITLE
v1.13 backports 2023-01-09

### PR DESCRIPTION
**Pull request by aditighag**
* #22684 -- test: Quarantine TLS test for now (@jrajahalme)
 * #22774 -- ci, github: Fix IPv6 conformance test (@borkmann)
 * #22763 -- workflows: fix skip condition for encryption tests in datapath conformance (@tklauser) (⚠️ Resolved conflicts)
 * #22029 -- add documentation to explain how to deploy cilium on k0s (@xinity)
 * #22745 -- Improve fqdn events logging management (@pippolo84)
 * #22678 -- bpf: nodeport: fix tracing for handle_nat_fwd() (@julianwiedmann)
 * #22824 -- operator: Add RBAC permission for CiliumNodeConfigs resource (@sayboras)
 * #21871 -- Internal traffic policy (@gentoo-root)
 * #22893 -- helm: Add  `node-role.kubernetes.io/control-plane` key  (@my-git9)
 * #22891 -- k8s: Update dependencies to v0.26.0 (@sayboras)
 * #22744 -- Add Cilium configuration documentation (@squeed)
 * #22930 -- Fix missing node neigh metric for counting arping requests (@christarazi)
 * #22773 -- Extend cgroup path detection to fix socket-lb tracing in certain environments (@aditighag)
 * #22927 -- docs: Document internalTrafficPolicy-related changes in the upgrade guide (@gentoo-root)
 * #22746 -- pkg/maps,pkg/defaults: allow configuring map events on missing maps. (@tommyp1ckles)
 * #22953 -- bpf: lb: fix check for L3 pseudo-hdr csum update in lb6_xlate() (@julianwiedmann)
 * #22976 -- Docs: Fix kubernetes version which isn't emphasized (@Shunpoco)
 * #22503 -- Change start time for policy_implementation_delay to when a CNP is first received by the Agent (@learnitall)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 22684 22774 22763 22029 22745 22678 22824 21871 22893 22891 22744 22930 22773 22927 22746 22953 22976 22503; do contrib/backporting/set-labels.py $pr done 1.13; done
```

### CODE REVIEW

**Comment by aditighag** [comment]
/test-backport-1.13

**Review by sayboras — APPROVED** [review]
Looks good for my commits, thanks 💯

**Review by christarazi — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Review by pippolo84 — APPROVED** [review]
Looks good for #22745, thanks :rocket:

**Review by squeed — APPROVED** [review]

**Review by gentoo-root — APPROVED** [review]
Approved for #22927.

**Review by Shunpoco — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Comment by aditighag** [comment]
/test-1.24-4.9

**Pull request merged**
