### PR TITLE
Encryption fixes for route/rule management

### PR DESCRIPTION
**Pull request by jrfastab**
Include table in route specifier so deleting IPsec routes in the encryption routing table will work.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8000)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
hit timeout after 'Test Suite Passed` going to retry.
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12283/console

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Comment by jrfastab** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
