### PR TITLE
kvstore: prevent deletion delay for node-unrelated events  

### PR DESCRIPTION
**Pull request by giorio94**
Please, refer to the commit messages for more information.

```release-note
kvstore: prevent deletion delay for node-unrelated events  
```

### CODE REVIEW

**Comment by giorio94** [comment]
/test-1.16-4.19

**Comment by giorio94** [comment]
k8s-1.16-kernel-4.19 hit https://github.com/cilium/cilium/issues/23845

**Comment by giorio94** [comment]
/test-1.16-4.19

**Comment by giorio94** [comment]
k8s-1.16-kernel-4.19 hit https://github.com/cilium/cilium/issues/23845
/test-1.16-4.19

**Comment by giorio94** [comment]
/test-1.16-4.19

**Comment by giorio94** [comment]
/test-1.16-4.19

**Comment by giorio94** [comment]
/test-1.16-4.19

**Comment by giorio94** [comment]
Rebasing to pick the fix for https://github.com/cilium/cilium/issues/23845

**Review by aanm — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
