### PR TITLE
test: change archive type to zip

### PR DESCRIPTION
**Pull request by aanm**
Since Github only supports .zip files to be uploaded, this commit
changes the compression file type so it can easily be updated as an
attachment when creating a github issue.

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by eloycoto** [comment]
All my love to this one :-)

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-nightly

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
Looks like there's an issue with the change. The `archive the artifacts` step failed in https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/2425/execution/node/68/log/ 

```
12:28:04 Archiving artifacts
12:28:04 WARN: No artifacts found that match the file pattern "test_results_Cilium-PR-Ginkgo-Tests-Validated_2425.zip". Configuration error?
12:28:05 WARN: ‘test_results_Cilium-PR-Ginkgo-Tests-Validated_2425.zip’ doesn’t match anything
```

**Review by ianvernon — CHANGES_REQUESTED** [review]
Reverting review approval as Jenkins is not picking up the artifacts with this change.

**Comment by eloycoto** [comment]
Installed `zip` on the Jenkins nodes.

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-me-please

**Comment by aanm** [comment]
@ianvernon all good

**Review by eloycoto — APPROVED** [review]

**Comment by ianvernon** [comment]
> Installed zip on the Jenkins nodes.

@eloycoto can you be sure to document that the Jenkins nodes need `zip` installed with the Jenkins master node provisioning recipe?

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
