### PR TITLE
Update CNI to 1.2.0

### PR DESCRIPTION
**Pull request by michi-covalent**
[ upstream commit a1046bcc10b75c7130f0579d40d0529c85e1fe56 ]

Run `images/scripts/update-cni-version.sh 1.2.0` to update the CNI version.

Ref: https://github.com/containernetworking/plugins/releases/tag/v1.2.0
Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Comment by michi-covalent** [comment]
/test-backport-1.12

**Comment by michi-covalent** [comment]
/test-backport-1.12

**Review by joestringer — APPROVED** [review]

**Comment by michi-covalent** [comment]
test-1.17-4.9: a known flake: https://github.com/cilium/cilium/pull/22474

**Comment by michi-covalent** [comment]
/test-1.17-4.9

**Comment by joestringer** [comment]
k8s-1.20-kernel-4.9 hit several failures: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.9/1554/

All of these failures seem to point to a sudden loss of DNS. Given that none of the other workflows exhibited this issue, I presume it must either be a problem with the connectivity in the VM when it ran, or otherwise some sort of transient test issue.

**Comment by joestringer** [comment]
/test-1.20-4.9

**Comment by michi-covalent** [comment]
/test-1.20-4.9

**Pull request merged**
