### PR TITLE
install/kubernetes: remove quick-install from master branches

### PR DESCRIPTION
**Pull request by aanm**
Since `:latest` tags are no longer available in the docker image
repositories, we will remove the quick-install.yaml from the master
branch. However, this will still be valid for stable branches so we will
keep the GH action to still run on those branches.

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-1.20-4.9

**Review by sayboras — APPROVED** [review]
LGTM 💯

**Review by joestringer — APPROVED** [review]

**Comment by dghubble** [comment]
These were useful as a reference :cry:

**Comment by joestringer** [comment]
@aanm btw, this PR broke the quick-install link on this docs page:
https://docs.cilium.io/en/latest/gettingstarted/k8s-install-default/#install-cilium

**Comment by dghubble** [comment]
@joestringer It was sometimes nice to see exactly the PR where something changed in those files, but per release seems pretty reasonable to reference or link to. Thanks

**Comment by joestringer** [comment]
@dghubble another similar approach would be to look at the Helm charts readme, you can track the PRs for specific changes there in a similar way: https://github.com/cilium/cilium/blame/master/install/kubernetes/cilium/README.md

**Pull request merged**
