### PR TITLE
Consolidate per-endpoint routes macros in the datapath

### LINKED ISSUE #15449: Consolidate per-endpoint routes macros in the datapath
In the datapath, we currently have several macros that all indicate whether per-endpoint routes are enabled or not:
```
ENABLE_ENDPOINT_ROUTES
!ENABLE_ROUTING
USE_BPF_PROG_FOR_INGRESS_POLICY
```
We should consolidate at least the first two, probably by keeping the first.

Related: https://github.com/cilium/cilium/pull/15217#discussion_r599707550

### PR DESCRIPTION
**Pull request by CBVenkataReddy**
In the datapath,we currently have several macros that
all indicate whether per-endpoint routes are enabled or not
ENABLE_ENDPOINT_ROUTES
!ENABLE_ROUTING
USE_BPF_PROG_FOR_INGRESS_POLICY
Now consolidated the first two, by keeping the first one ENABLE_ENDPOINT_ROUTES.

Fixes: #15449

Signed-off-by: Venkata Reddy <venkata.reddy@accuknox.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Review by joestringer — CHANGES_REQUESTED** [review]
Thanks for the submission, at a high level it makes sense to me.

I would expect that some userspace changes would be necessary as well. I would suggest grepping for `ENABLE_ROUTING` to find all of the locations in the codebase that contain this symbol and check how to remove them.

Additionally, everything in the PR description below `Please ensure your pull request adheres to the following guidelines:` is for you to fill out, including the release note. When you get a chance, please look them over and confirm whether you have taken those steps, and either add a release note or remove it (in that case the release note will use the title of the PR, which I think is OK).

**Comment by CBVenkataReddy** [comment]
@joestringer Thank you for review,  
ENABLE_ROUTING 
 - when this macro enabled it enables endpoint BPF routing.
 - when this macro disabled, the routing is delegated to Linux routing.
Which means when endpoint BPF routing disabled all routing is performed by the Linux stack.

ENABLE_ENDPOINT_ROUTES
 - when this macro is enabled,
   the endpoint wishes to have a per endpoint route installed in the host's routing table to point to the endpoint's interface.
 
As per my understanding both "ENABLE_ENDPOINT_ROUTES" and "!ENABLE_ROUTING" macro's boiled down to the same meaning, so instead of using both macros now consolidated to ENABLE_ENDPOINT_ROUTES.

I think it is not required to remove the "ENABLE_ROUTING" in user space, kindly suggest.

**Comment by pchaigno** [comment]
> I think it is not required to remove the "ENABLE_ROUTING" in user space, kindly suggest.

If we're not using `ENABLE_ROUTING` in the datapath anymore, then we should remove all references from userspace.

**Comment by CBVenkataReddy** [comment]
We are using ENABLE_ROUTING in datapath,

vagrant@vagrant:~/cilium$ grep -rn "ENABLE_ROUTING" ./
./bpf/lib/encrypt.h:74:#endif /* ENABLE_ROUTING */
./bpf/bpf_lxc.c:89:#ifdef ENABLE_ROUTING
./bpf/bpf_lxc.c:317:    if (is_defined(ENABLE_ROUTING) || hairpin_flow) {
./bpf/bpf_lxc.c:328:#ifdef ENABLE_ROUTING
./bpf/bpf_lxc.c:336:#endif /* ENABLE_ROUTING */
./bpf/bpf_lxc.c:395:#ifdef ENABLE_ROUTING
./bpf/bpf_lxc.c:415:#ifdef ENABLE_ROUTING
./bpf/bpf_lxc.c:518:#ifdef ENABLE_ROUTING
./bpf/bpf_lxc.c:745:    /* Allow a hairpin packet to be redirected even if ENABLE_ROUTING is
./bpf/bpf_lxc.c:750:    if (is_defined(ENABLE_ROUTING) || hairpin_flow) {
./bpf/bpf_lxc.c:762:#ifdef ENABLE_ROUTING
./bpf/bpf_lxc.c:770:#endif /* ENABLE_ROUTING */
./bpf/bpf_lxc.c:840:#ifdef ENABLE_ROUTING
./bpf/bpf_lxc.c:860:#ifdef ENABLE_ROUTING
./bpf/Makefile:83:      -DENABLE_HOST_REDIRECT=1 -DENABLE_ROUTING=1 -DNO_REDIRECT=1 \
./bpf/Makefile:227:      -DENABLE_IPV6:-DENCAP_IFINDEX:-DPOLICY_VERDICT_NOTIFY:-DENABLE_IPV4:-DENABLE_ROUTING: \
./bpf/Makefile:264:     -DENABLE_ROUTING -DENABLE_IPSEC -DPOLICY_VERDICT_NOTIFY
vagrant@vagrant:~/cilium$

**Comment by CBVenkataReddy** [comment]
We are using "ENABLE_ROUTING"  in the datapath

[ENABLE_ROUTING.txt](https://github.com/cilium/cilium/files/6278108/ENABLE_ROUTING.txt)

**Comment by pchaigno** [comment]
I thought the goal of this pull request was to consolidate `ENABLE_ROUTING` and `ENABLE_ENDPOINT_ROUTES`. Why are we still using `ENABLE_ROUTING` in bpf_lxc?

**Comment by CBVenkataReddy** [comment]
From my understanding 
When ENABLE_ROUTING defined (enabled) then endpoints use BPF routing and does not use the routing performed by the Linux stack,
When ENABLE_ENDPOINT_ROUTES defined (enabled) then per endpoint route installed in the host's routing table and endpoints does not use BPF routing.

Pls clarify 
defined(ENABLE_ENDPOINT_ROUTES), 
!defined(ENABLE_ROUTING) 
both of these mean to the "endpoints BPF routing is disabled"  
and use per endpoint route installed in the host's routing table (all routing is performed by the Linux stack) ?

OR

defined(ENABLE_ENDPOINT_ROUTES), 
defined(ENABLE_ROUTING)
both of these mean to the "endpoints use BPF routing" ?

Kindly suggest accordingly I shall make changes.

**Comment by CBVenkataReddy** [comment]
Raised new PR
https://github.com/cilium/cilium/pull/15656

**Pull request closed without merging**
