### PR TITLE
test: increase delete timeout

### PR DESCRIPTION
**Pull request by nebril**

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-backport-1.7

**Comment by aanm** [comment]
test-backport-1.7-k8s)

**Comment by aanm** [comment]
test-backport-1.7-k8s

**Comment by aanm** [comment]
@nebril I've re-trigerred the tests to see if this PR is introducing a regression or not.

**Comment by nebril** [comment]
test-backport-1.7-k8s

**Comment by nebril** [comment]
test-backport-1.7-k8s

**Comment by nebril** [comment]
test-backport-1.7-k8s

**Comment by nebril** [comment]
test-backport-1.7-k8s

**Review by gandro — APPROVED** [review]

**Pull request merged**
