### PR TITLE
bgpv1: fix reconciliation of services with shared VIPs

### LINKED ISSUE #35018: Cilium BGP stops announcing shared IP
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.15.7 and lower than v1.16.0

### What happened?

There is a bug when a service with a sharing key gets deleted. Cilium stops announcing the IP even if there are other LoadBalancer services that are still using it.

### How can we reproduce the issue?

1. Create 2 services that share an IP by using the `lbipam.cilium.io/sharing-key` annotation.
2. Announce those services via bgp.
3. Delete one of the services.
4. See that the announcement of the ip was removed.

### Cilium Version

1.15.8

### Kernel Version

6.10.7

### Kubernetes Version

1.28.13

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rastislavs**
As multiple services can share the same VIP (e.g. using `lbipam.cilium.io/sharing-key`), the service reconciliation logic needs to be adapted to not withdraw a route to VIP that is still in use by some other service.

To address that, this change introduces resource reference counting by reconciling service advertisements.

This fix is specific to BGPv1 service reconciliation, BGPv2 was fixed in https://github.com/cilium/cilium/pull/35166.

Fixes: #35018

### CODE REVIEW

**Review by harsimran-pabla — APPROVED** [review]

**Review by YutaroHayakawa — APPROVED** [review]

**Comment by tklauser** [comment]
Backport to v1.15 in #35469 lead to non-trivial merge conflicts, this will need a manual backport. Marking as `backport/author`.

**Comment by joestringer** [comment]
I'm curious whether the [backport criteria](https://docs.cilium.io/en/v1.15/contributing/release/backports/#backport-criteria-for-x-y-1-z-and-x-y-2-z) for older releases was considered for this fix, was this considered a major bugfix? The reason I ask is that it seems like we have BGPv2 which is where the primary focus for future BGP effort is.. the more effort we spend in backporting fixes for old code to older branches, the less time we have to make the new version better. I see that the automatic backporting failed and was rejected by the backporter, which suggests that there's significant changes going on in this area of the codebase. We have the option to only backport fixes to the latest release and avoid the extra maintenance effort of backporting to older releases, since users still have the option to upgrade to the latest stable release to address this issue.

I think that we may as well take the backport into v1.15 since we already did the work for that backport, no point to revisit for this specific change. But I think it's healthy for us to have discussions about the bar for how significant a bug is before we spend the additional effort in fixing it in the older releases. If there's a common mitigation, especially if [BGP control plane is beta in v1.15](https://docs.cilium.io/en/v1.15/network/bgp-control-plane/) then maybe we don't need to be putting the extra effort into making the v1.15 version of this more stable.

**Comment by rastislavs** [comment]
The reason why I marked this for backport to 1.15 is that there is no workaround for the issue in v1.15 (BGP CP misbehaves if `lbipam.cilium.io/sharing-key` is used and this feature therefore can not be used with BGP in 1.15). 

But I agree that upgrading to 1.16 is always an option, and we should rather invest the time to the new codebase (BGPv2). Will reconsider this in similar cases next time.

**Comment by joestringer** [comment]
> (BGP CP misbehaves if lbipam.cilium.io/sharing-key is used and this feature therefore can not be used with BGP in 1.15).

FWIW this sounds like a feature request to me, not a major bugfix. If it never worked due to this issue then we haven't introduced a regression on v1.15 for users. Given there is the option to upgrade, I think we'd generally prefer users to upgrade to help us make the newer versions better.

**Comment by rastislavs** [comment]
> FWIW this sounds like a feature request to me, not a major bugfix

Makes sense, thanks for the guidance. I closed the backport PR to 1.15, as based on this discussion it does not meet the backport criteria.

**Pull request merged**
