### PR TITLE
datapath: Decouple IPV4_MASQUERADE from IPV4_NODEPORT

### LINKED ISSUE #13326: datapath: Decouple NodePort IP addr from BPF-masq IP addr
Currently, the same IP addr (`IPV4_NODEPORT`) is used by the BPF-based masquerading. Recently, https://github.com/cilium/cilium/pull/13223 changed the preference order for NodePort IP addr selection - instead of a public IP, a k8s Node IP addr is preferred regardless of the scope. This breaks BPF-masq for deployments with a single iface having both public and private IP addrs AND k8s Node IP being set to a private one.

Fix this by independently selecting a public IP addr for BPF-masq.

### PR DESCRIPTION
**Pull request by brb**
See commit msg.

Tested manually.

Fix: #13326

### CODE REVIEW

**Comment by brb** [comment]
retest-net-next

**Comment by brb** [comment]
The checkpatch fails due to a false positive:
```
WARNING:COMMIT_LOG_LONG_LINE: Possible unwrapped commit description (prefer a maximum 75 chars per line)
#41: 
[1]: 870c02c3 ("Makes k8sNodeIP the preferred IP when initializing NodePort addresses".)
```

**Comment by brb** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]
LGTM!

(I think this PR is a good example of a case when having @cilium/bpf/loader vs. @cilium/bpf/lb would be useful. I'm a lot more confident to review the loader bits than the service-handling bits. Therefore, requesting a second review on @cilium/bpf.)

> One downside of the fix is that it introduces a redundant check on the
"to-netdev" fastpath when IPV4_NODEPORT==IPV4_MASQUERADE which the BPF
verifier is not able to optimize away (both IPV4_{NODEPORT,MASQUERADE}
are defined via static data):

That doesn't sound too terrible, but if it is, it should be possible to optimize that case with an additional `#ifdef` for `IPV4_NODEPORT==IPV4_MASQUERADE`, right?

**Review by kkourt — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by borkmann — APPROVED** [review]

**Comment by brb** [comment]
> That doesn't sound too terrible, but if it is, it should be possible to optimize that case with an additional #ifdef for IPV4_NODEPORT==IPV4_MASQUERADE, right?

@pchaigno Both `IPV4_{NODEPORT,MASQUERADE}` are declared as a static data. I didn't find a way how to compare them in a preprocessor. Also not sure whether the BPF verifier would be able to optimize away statements inside the #ifdef block.

**Comment by pchaigno** [comment]
> > That doesn't sound too terrible, but if it is, it should be possible to optimize that case with an additional #ifdef for IPV4_NODEPORT==IPV4_MASQUERADE, right?
> 
> @pchaigno Both `IPV4_{NODEPORT,MASQUERADE}` are declared as a static data. I didn't find a way how to compare them in a preprocessor. Also not sure whether the BPF verifier would be able to optimize away statements inside the #ifdef block.

Ah, right. So we would have to compare in userspace and introduce a new macro. Probably not worth it.

**Comment by kkourt** [comment]
>  didn't find a way how to compare them in a preprocessor. 

@brb, I was also wondering about that but I thought that we didn't had access to the preprocessor when instantiating these.

Would something like the following work?
```
$ cat main.c                                   
#include <stdio.h>

#if XXX == YYY
#define V 0
#else
#define V 1
#endif

int main(int argc, char **argv) {
        printf("=>%d\n", V);
}
$ gcc -Wall -DXXX=1 -DYYY=2 -E main.c | tail -3
int main(int argc, char **argv) {
 printf("=>%d\n", 1);
}
$ gcc -Wall -DXXX=1 -DYYY=1 -E main.c | tail -3
int main(int argc, char **argv) {
 printf("=>%d\n", 0);
}
```

**Comment by brb** [comment]
@kkourt Hmm, not sure whether I'm following. The problem with `#if IPV4_MASQUERADE != IPV4_NODEPORT` is that both macros should resolve to `fetch_u32(x) => __fetch(x) => (__u32)(__u64)(&(x))` which gets "patched" during load time. Regardless of whether the `#if` can be compiled (it can't), the compiler would not be able to optimize away the inside of the `#if` as both values are not know do the compiler during compile time. So, technically only the BPF verifier could remove the inside. But trying `if (IPV4_MASQUERADE != IPV4_NODEPORT) { if (ip4->saddr == IPV4_MASQUERADE ) { .... } }` revealed that the verifier is unable to optimize :-(

**Pull request merged**
