### PR TITLE
Add IPAM modes comparison table

### PR DESCRIPTION
**Pull request by raphink**
Signed-off-by: Raphaël Pinson <raphael@isovalent.com>

```release-note
docs: Add a comparison table for IPAM modes
```

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]
Looks good. Too bad we have to scroll quite a lot horizontally to display the full table, but I don't have a better suggestion. We could have the table displayed “vertically” instead (feature names at the top), but then the feature names would be hard to read if we made the columns narrow enough for it to fit.

**Comment by raphink** [comment]
@qmonnet we have too many IPAM options? 😁

**Review by gandro — APPROVED** [review]
Awesome, thanks!

**Comment by qmonnet** [comment]
Documentation change only, no need for the full CI suite.

**Pull request merged**
