### PR TITLE
Fix Makefile coverpkg when using TESTPKGS=...

### PR DESCRIPTION
**Pull request by joestringer**
The coverpkg parameter was not passing the correct value to go test when
the user specified TESTPKGS, which meant that if developers wanted to
figure out the coverage of a particular package, they'd either have to
run the full set of unit tests or figure out the correct COVERPKG
argument and pass that into "make unit-tests".

Fix it so that COVERPKG inherits the correct package names from TESTPKGS.

While we're at it, fix up the privileged tests options so that you can use TESTPKGS (just like with the regular unit tests), instead of needing to specify PRIV_TEST_PKGS.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8308)

### CODE REVIEW

**Review by ianvernon — APPROVED** [review]
I observed this yesterday while using `TESTPKGS` and it annoyed me, so thank you for fixing this!

**Comment by joestringer** [comment]
Bah, broke the "normal" case apparently, given coveralls' summary there. Back to the drawing board I guess.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Only tests that failed are Istio tests, doesn't make any sense why this PR would cause those to fail:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13089/

(#8346)

**Pull request merged**
