### PR TITLE
backport v1.7: node-neigh: Bump arping vsn to accept netlink.Link

### PR DESCRIPTION
**Pull request by brb**
See commit msg.

```release-note
Fix possible deadlock when querying network interfaces for arping
```

### CODE REVIEW

**Comment by brb** [comment]
test-backport-v1.7

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-backport-1.7

**Comment by joestringer** [comment]
Hit known flake #10678 on travis run, can be ignored.

**Review by joestringer — COMMENTED** [review]
Is this a backport of another existing PR in the main branches? How do we feel those fixes have gone so far?

I understand that the core change here is switching from the `net` package interface dumping over to the `netlink` package, which is known to address issues with the execution blocking. I'm fine with that.

The changes directly in Cilium LGTM here. I don't have context on the arping vendor changes so if we want closer review there then I suggest we figure out who's going to take that closer look.

**Comment by brb** [comment]
> Is this a backport of another existing PR in the main branches? How do we feel those fixes have gone so far?

Noup, there was no fix for the main branch, as we switched the arping library and the new library consumes `netlink.Link` instead of `net.Interface`. However, we had to backport almost the same fix to the 1.8 (https://github.com/cilium/cilium/pull/15225) and to the 1.9 (https://github.com/cilium/cilium/pull/15227).

> The changes directly in Cilium LGTM here. I don't have context on the arping vendor changes so if we want closer review there then I suggest we figure out who's going to take that closer look.

We could pull @jrfastab to do the review. He should know the code very well.

**Comment by tgraf** [comment]
test-backport-1.7

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by joestringer** [comment]
> test-me-please

^ This is why all the failed builds show up in the checks section at the bottom, we need to use `test-backport-1.7` to run CI here

**Pull request merged**
