### PR TITLE
v1.6 backports 2019-11-14

### PR DESCRIPTION
**Pull request by aanm**
* #9509 -- eni: Allow releasing excess IP addresses via option (@jaffcheng)
 * #9545 -- fqdn: DNSCache LookupByRegex functions don't return empty matches (@raybejjani)
 * #9549 -- bpf: Don't perform L3 operation when ENABLE_ROUTING is disabled (@tgraf)
 * #9107 -- Docs: tofqdns-pre-cache is optional in preflight templates (@raybejjani)
 * #9551 -- pkg/endpoint: start RegenerationFailureHandler after assign epID (@aanm)
 * #9526 -- Added chart value for etcd-operator cluster domain (@dsexton)
 * #9577 -- Delete service ports from datapath if they are removed with a k8s update (@aanm)
 * #9581 -- operator: do not rm kube-dns pods if unmanaged-pod-watcher-interval == 0 (@aanm)
 * #9583 -- unmanaged kube-dns: Delete one pod per iteration (@jraby)
 * #9597 -- cni: fix cni plugin error formatting when agent is not running (@fristonio)
 * #9606 -- vendor: point vishvananda/netlink back to upstream (@borkmann)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 9509 9545 9549 9107 9551 9526 9577 9581 9583 9597 9606; do contrib/backporting/set-labels.py $pr done 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9610)

### CODE REVIEW

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
all tests passed but keep in mind that #9613 is still open

**Review by joestringer — APPROVED** [review]

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
