### PR TITLE
v1.7 backports 2020-02-17

### PR DESCRIPTION
**Pull request by nebril**
* #10169 -- clustermesh: Add cilium status section (@tgraf)
 * #10186 -- vagrant: Install temporary forked bpftool (@pchaigno)
 * #10178 -- docs: fix link for Cilium-PR-Kubernetes-Upstream job (@tklauser)
 * #10179 -- golang: update to 1.13.8 (@aanm)
 * #10192 -- maps/nat: return NatEntry6 for NatKey6 NewValue() instead of NatEntry4 (@aanm)
 * #10190 -- bugtool: Dump NAT BPF maps entries with bpftool (@brb)
 * #10185 -- Correct clustermesh identity sync kvstore backend usage (to actually use the remote) (@raybejjani)
 * #10168 -- pkg/bpf: Protect each uintptr with runtime.KeepAlive (@brb)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10169 10186 10178 10179 10192 10190 10185 10168; do contrib/backporting/set-labels.py $pr done 1.7; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10212)

### CODE REVIEW

**Comment by nebril** [comment]
never-tell-me-the-odds

**Comment by nebril** [comment]
never-tell-me-the-odds

**Review by aanm — APPROVED** [review]
LGTM for my changes

**Comment by nebril** [comment]
test-missed-k8s

**Pull request merged**
