### PR TITLE
Clean up and add debug logs to CT map cleanup code

### PR DESCRIPTION
**Pull request by rlenglet**
Add debug logs.
Simplify the implementation of doFiltering().
Define GCFilter.Type as an enum instead of a bit set, since it was used as an enum.

Signed-off-by: Romain Lenglet <romain@covalent.io>

### CODE REVIEW

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Test failure:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/1509/
```
02:00:19 K8sValidatedPolicyTestAcrossNamespaces
02:00:19 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Policies.go:676
02:00:19   Policies Across Namespaces [It]
02:00:19   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Policies.go:744
02:00:19 
02:00:19   Unable to connect between frontend-rzb4d and 10.106.219.234:80/
02:00:19   Expected
02:00:19       <bool>: false
02:00:19   to be true
02:00:19 
02:00:19   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Policies.go:820
```

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Saw conntrack test failures, with my debug logs:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/1518/
```
05:10:51 [Fail] RuntimeValidatedConntrackTable [It] Testing proxy redirect after installing L3-L4-L7 policy over an existing L3-L4 policy 
05:10:51 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/runtime/ct.go:608
05:10:51 
05:10:51 [Fail] RuntimeValidatedConntrackTable [It] Testing L3-L4-L7 policy while the L3-L4 connection was previously made to confirm L3-L4-L7 policy enforcement over the proxy with the same source port 
05:10:51 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/runtime/ct.go:715
```
Will look into details.

**Comment by rlenglet** [comment]
Also got a local conntrack test failure:
```
RuntimeValidatedConntrackTable
/Users/romainlenglet/Documents/gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:170
  Testing proxy redirect after installing L3-L4-L7 policy over an existing L3-L4 policy [It]
  /Users/romainlenglet/Documents/gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:202

  Failed to httpRequest 'docker exec -i  client bash -c "python ./nc.py 11111 5 f00d::a0f:0:0:6f19 80 \"/private\" | head -n 1 | grep \"HTTP/1.*200 OK\""' from client to f00d::a0f:0:0:6f19: 
  Expected
      <bool>: false
  to be true

  /Users/romainlenglet/Documents/gopath/src/github.com/cilium/cilium/test/runtime/ct.go:596
```

The L7 policy is imported around `22:03:47-07:00`, i.e. `05:03:47` UTC:
```
time="2018-03-21T22:03:47-07:00" level=debug msg="running command: sudo cilium policy import /home/vagrant/go/src/github.com/cilium/cilium/test/policy_10cd9672.json"
cmd: "sudo cilium policy import /home/vagrant/go/src/github.com/cilium/cilium/test/policy_10cd9672.json" exitCode: 0
 Revision: 147
```

The failure happens around `22:03:59-07:00`, i.e. `05:03:59` UTC:
```
time="2018-03-21T22:03:59-07:00" level=debug msg="running command: docker exec -i  client bash -c \"python ./nc.py 11111 5 f00d::a0f:0:0:353c 80 \\\"/private\\\" | head -n 1 | grep \\\"HTTP/1.*200 OK\\\"\""
cmd: "docker exec -i  client bash -c \"python ./nc.py 11111 5 f00d::a0f:0:0:353c 80 \\\"/private\\\" | head -n 1 | grep \\\"HTTP/1.*200 OK\\\"\"" exitCode: 0
 HTTP/1.1 200 OK
```

The "server-3" container where the L7 policy is enforced and the client have the following IDs:
```
$ cat endpoint_list.txt | jq '[.[] | {name: ."container-name", endpointID: .id, secID: .identity.id}]'
[
...
  {
    "name": "server-3",
    "endpointID": 13628,
    "secID": 22488
  },
...
  {
    "name": "client",
    "endpointID": 50640,
    "secID": 46560
  }
]
```

As expected, there are 4 matching CT map entries from the previous connections between client and server-3:
```
$ cat cilium.log | grep 'security ID to keep' | grep 'filterEndpointID=13628' | grep 'entrySrcSecID=46560' | grep entryProto=6 | grep 'entryFlags=[13]' | grep Filtering | grep 05:03:4
Mar 22 05:03:48 runtime cilium-agent[3710]: level=debug msg="Filtering CT map entry" entryDstIP=10.15.65.87 entryDstPort=20480 entryFlags=1 entryProto=6 entrySrcIP=10.15.166.9 entrySrcSecID=46560 filterEndpointID=13628 filterEndpointIP=10.15.65.87 filterType="security ID to keep"
Mar 22 05:03:48 runtime cilium-agent[3710]: level=debug msg="Filtering CT map entry" entryDstIP=10.15.65.87 entryDstPort=20480 entryFlags=1 entryProto=6 entrySrcIP=10.15.28.238 entrySrcSecID=46560 filterEndpointID=13628 filterEndpointIP=10.15.65.87 filterType="security ID to keep"
Mar 22 05:03:48 runtime cilium-agent[3710]: level=debug msg="Filtering CT map entry" entryDstIP="f00d::a0f:0:0:353c" entryDstPort=20480 entryFlags=1 entryProto=6 entrySrcIP="f00d::a0f:0:0:c5d0" entrySrcSecID=46560 filterEndpointID=13628 filterEndpointIP="f00d::a0f:0:0:353c" filterType="security ID to keep"
Mar 22 05:03:48 runtime cilium-agent[3710]: level=debug msg="Filtering CT map entry" entryDstIP="f00d::a0f:0:0:353c" entryDstPort=20480 entryFlags=1 entryProto=6 entrySrcIP="fc00::10ca:1" entrySrcSecID=46560 filterEndpointID=13628 filterEndpointIP="f00d::a0f:0:0:353c" filterType="security ID to keep"
```

As expected, all entries match the endpoint and are correctly identified as ingress:
```
$ cat cilium.log | grep 'security ID to keep' | grep 'filterEndpointID=13628' | grep 'entrySrcSecID=46560' | grep entryProto=6 | grep 'entryFlags=[13]' | grep 'Ingress CT map entry matches endpoint IP' | grep 05:03:4 | wc -l
       4
```

Symptom of the problem: no entries are modified to set the proxy port to a non-zero port:
```
$ cat cilium.log | grep 'security ID to keep' | grep 'filterEndpointID=13628' | grep 'entrySrcSecID=46560' | grep Modifying | wc -l
       0
```

No actions are performed on any of those 4 CT map entries:
```
$ cat cilium.log | grep 'security ID to keep' | grep 'filterEndpointID=13628' | grep 'entrySrcSecID=46560' | grep entryProto=6 | grep 'entryFlags=[13]' | grep Ignoring | grep 05:03:4
Mar 22 05:03:48 runtime cilium-agent[3710]: level=debug msg="Ignoring CT map entry: no action required" entryDstIP=10.15.65.87 entryDstPort=20480 entryFlags=1 entryProto=6 entrySrcIP=10.15.166.9 entrySrcSecID=46560 filterEndpointID=13628 filterEndpointIP=10.15.65.87 filterType="security ID to keep"
Mar 22 05:03:48 runtime cilium-agent[3710]: level=debug msg="Ignoring CT map entry: no action required" entryDstIP=10.15.65.87 entryDstPort=20480 entryFlags=1 entryProto=6 entrySrcIP=10.15.28.238 entrySrcSecID=46560 filterEndpointID=13628 filterEndpointIP=10.15.65.87 filterType="security ID to keep"
Mar 22 05:03:48 runtime cilium-agent[3710]: level=debug msg="Ignoring CT map entry: no action required" entryDstIP="f00d::a0f:0:0:353c" entryDstPort=20480 entryFlags=1 entryProto=6 entrySrcIP="f00d::a0f:0:0:c5d0" entrySrcSecID=46560 filterEndpointID=13628 filterEndpointIP="f00d::a0f:0:0:353c" filterType="security ID to keep"
Mar 22 05:03:48 runtime cilium-agent[3710]: level=debug msg="Ignoring CT map entry: no action required" entryDstIP="f00d::a0f:0:0:353c" entryDstPort=20480 entryFlags=1 entryProto=6 entrySrcIP="fc00::10ca:1" entrySrcSecID=46560 filterEndpointID=13628 filterEndpointIP="f00d::a0f:0:0:353c" filterType="security ID to keep"
```

This demonstrates that this predicate is false for every one of those entries:
```
l7RuleCtx.L4Installed && entry.proxy_port != l7RuleCtx.RedirectPort
```

And we can check that all entries in the CT map have a 0 proxy_port:
```
$ cat bpf_ct_list.txt 
ICMP OUT [f00d::a0f:0:0:353c]:0 -> [f00d::a0f:0:0:c5d0]:0 related  expires=143900 rx_packets=0 rx_bytes=0 tx_packets=1 tx_bytes=94 flags=0 revnat=0 proxyport=0 src_sec_id=46560
TCP IN [f00d::a0f:0:0:353c]:80 -> [f00d::a0f:0:0:c5d0]:11111  expires=143900 rx_packets=15 rx_bytes=1643 tx_packets=15 tx_bytes=2057 flags=0 revnat=0 proxyport=0 src_sec_id=46560
TCP IN [f00d::a0f:0:0:353c]:80 -> [fc00::10ca:1]:44270  expires=143885 rx_packets=2 rx_bytes=172 tx_packets=2 tx_bytes=184 flags=0 revnat=0 proxyport=0 src_sec_id=46560
TCP OUT [f00d::a0f:0:0:353c]:80 -> [f00d::a0f:0:0:c5d0]:11111  expires=143900 rx_packets=5 rx_bytes=686 tx_packets=5 tx_bytes=548 flags=0 revnat=0 proxyport=0 src_sec_id=46560
TCP IN [f00d::a0f:0:0:353c]:80 -> [fc00::10ca:1]:44250  expires=143890 rx_packets=2 rx_bytes=172 tx_packets=2 tx_bytes=184 flags=0 revnat=0 proxyport=0 src_sec_id=46560

TCP IN 10.15.65.87:80 -> 10.15.166.9:11111  expires=143888 rx_packets=10 rx_bytes=877 tx_packets=10 tx_bytes=1171 flags=0 revnat=0 proxyport=0 src_sec_id=46560
TCP IN 10.15.65.87:80 -> 10.15.28.238:41738  expires=143885 rx_packets=2 rx_bytes=132 tx_packets=2 tx_bytes=144 flags=0 revnat=0 proxyport=0 src_sec_id=46560
```
```
$ grep proxyport= bpf_ct_list.txt | grep -v proxyport=0 | wc -l
       0
```

Assuming that `l7RuleCtx.RedirectPort` is not 0, we can conclude that the reason the entries are not modified to use the new proxy port is that `l7RuleCtx.L4Installed` is false.

Adding debug logs to confirm this hypothesis.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Had another local failure with the better logs.

```
$ cat endpoint_list.txt | jq '[.[] | {name: ."container-name", endpointID: .id, secID: .identity.id}]'
[
...
  {
    "name": "client",
    "endpointID": 4314,
    "secID": 51859
  },
...
  {
    "name": "server-3",
    "endpointID": 25729,
    "secID": 47438
  },
...
]
```

Policy revision 46 imported around `07:47:42` UTC:
```
time="2018-03-22T00:47:42-07:00" level=debug msg="running command: sudo cilium policy import /home/vagrant/go/src/github.com/cilium/cilium/test/policy_10cd9672.json"
cmd: "sudo cilium policy import /home/vagrant/go/src/github.com/cilium/cilium/test/policy_10cd9672.json" exitCode: 0
 Revision: 46
```

Failure around `07:47:51` UTC:
```
time="2018-03-22T00:47:51-07:00" level=debug msg="running command: docker exec -i  client bash -c \"python ./nc.py 11111 5 f00d::a0f:0:0:6481 80 \\\"/private\\\" | head -n 1 | grep \\\"HTTP/1.*200 OK\\\"\""
cmd: "docker exec -i  client bash -c \"python ./nc.py 11111 5 f00d::a0f:0:0:6481 80 \\\"/private\\\" | head -n 1 | grep \\\"HTTP/1.*200 OK\\\"\"" exitCode: 0
 HTTP/1.1 200 OK
```

In this failure, `updateCT` wasn't even called after the policy was imported. The last scan of the CT map was at `07:47:22`, for revision 43:
```
$ grep 'Updating CT map entries to reflect policy changes' cilium.log  | grep endpointID=25729 | tail -n 1

Mar 22 07:47:22 runtime cilium-agent[7468]: level=debug msg="Updating CT map entries to reflect policy changes" containerID=26a656e692 endpointID=25729 policyRevision=43
```
```
$ cat cilium.log | grep 'security ID to keep' | grep 'filterEndpointID=25729' | grep 'entrySrcSecID=51859' | grep entryProto=6 | grep 'entryFlags=[13]' | grep Filtering | tail -n 1

Mar 22 07:47:22 runtime cilium-agent[7468]: level=debug msg="Filtering CT map entry" entryDstIP="f00d::a0f:0:0:6481" entryDstPort=80 entryFlags=1 entryProto=6 entryProxyPort=17871 entrySrcIP="f00d::a0f:0:0:10da" entrySrcSecID=51859 filterEndpointID=25729 filterEndpointIP="f00d::a0f:0:0:6481" filterType="security ID to keep"
```

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Please review.
This doesn't yet fix fix https://github.com/cilium/cilium/issues/3208, but it adds debug logs that will help debugging that.

**Comment by rlenglet** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]
Great cleanup + addition of logs.

**Review by tgraf — APPROVED** [review]

**Pull request merged**
