### PR TITLE
helm: Set dnsPolicy for Cilium pod to ClusterFirstWithHostNet

### PR DESCRIPTION
**Pull request by michi-covalent**
Ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods-dns-policy

Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Comment by michi-covalent** [comment]
i can lookup dns names of k8s services in minikube with this change, but i don't know what other implications this change might have.

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Review by rolinh — APPROVED** [review]

**Review by tgraf — CHANGES_REQUESTED** [review]
Can you explain why this is needed? This is specifically protected by the managed etcd guards right now because it creates a dependency on CoreDNS. We should remove this entirely as we deprecated managed etcd.

**Comment by michi-covalent** [comment]
@tgraf the original issue was that with `ClusterFirst` policy, cilium cannot resolve dns names of kubernetes dns services. i was trying to run `hubble observe --server hubble-relay:80` from a cilium pod, but it didn't work because the cilium pod couldn't resolve `hubble-relay`. it's not the end of the world if this doesn't work, but maybe we can document this limitation somewhere, if it's not documented already.

**Comment by michi-covalent** [comment]
closing this to avoid adding coredns dependency.

**Pull request closed without merging**
