### PR TITLE
1.2.2 backports 2018-09-05

### PR DESCRIPTION
**Pull request by tgraf**
Backported PRs:
* https://github.com/cilium/cilium/pull/5422
* https://github.com/cilium/cilium/pull/5428
* https://github.com/cilium/cilium/pull/5453
* https://github.com/cilium/cilium/pull/5455
* https://github.com/cilium/cilium/pull/5456
* https://github.com/cilium/cilium/pull/5458
* https://github.com/cilium/cilium/pull/5459
* https://github.com/cilium/cilium/pull/5469
* https://github.com/cilium/cilium/pull/5475
* https://github.com/cilium/cilium/pull/5482
* https://github.com/cilium/cilium/pull/5483
* https://github.com/cilium/cilium/pull/5486
* https://github.com/cilium/cilium/pull/5495
* https://github.com/cilium/cilium/pull/5502

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5490)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

[green build]

**Comment by tgraf** [comment]
test-missed-k8s

[1.12 tests failed, 1.10 tests passed]

**Comment by tgraf** [comment]
test-missed-k8s

[test was interrupted for unknown reasons]

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by raybejjani** [comment]
test-missed-k8s

[15:57:14 VBoxManage: error: Appliance import failed]

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-me-please

[Kafka test failed]

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
