### PR TITLE
Revert #24288

### PR DESCRIPTION
**Pull request by jibi**
This PR undoes a revert PR, #24288, which was reverting https://github.com/cilium/cilium/pull/24288 and https://github.com/cilium/cilium/pull/24577.

We believed the 2 aforementioned PRs introduced a regression on the upgrade from 1.13 to latest, but after the revert the CI is still failing.

### CODE REVIEW

**Review by borkmann — APPROVED** [review]
LGTM (approving on behalf on Nik who is currently out)!

**Comment by borkmann** [comment]
Adding flag to hold merge given @aanm noticed an issue locally that we need to investigate before merging.

**Comment by pchaigno** [comment]
> I got this diff in the before and after an upgrade. I wonder if this could be the reason why connectivity gets broken after upgrade.
> 
> [before.txt](https://github.com/cilium/cilium/files/11160303/before.txt) [after.txt](https://github.com/cilium/cilium/files/11160304/after.txt)

That's just how the reverted patch works. Nothing that looks out of the ordinary. Is that the "issue" you noticed locally?

**Comment by jibi** [comment]
not sure if just a red herring, but after the upgrade, beside the `proto kernel` changes, one other difference is that we are missing a bunch of IPv6 routes for cilium_host

```diff
diff <(cat before.txt | grep cilium_host) <(cat after.txt | grep cilium_host)
1,5c1,5
< default via 10.0.1.62 dev cilium_host table 2005
< 10.0.1.62 dev cilium_host table 2005 scope link
< 10.0.0.0/24 via 10.0.1.62 dev cilium_host src 10.0.1.62 mtu 1450
< 10.0.1.0/24 via 10.0.1.62 dev cilium_host src 10.0.1.62
< 10.0.1.62 dev cilium_host scope link
---
> default via 10.0.1.62 dev cilium_host table 2005 proto kernel
> 10.0.1.62 dev cilium_host table 2005 proto kernel scope link
> 10.0.0.0/24 via 10.0.1.62 dev cilium_host proto kernel src 10.0.1.62 mtu 1450
> 10.0.1.0/24 via 10.0.1.62 dev cilium_host proto kernel src 10.0.1.62
> 10.0.1.62 dev cilium_host proto kernel scope link
7,8c7,8
< fe80::8f9:c6ff:fe3d:3775 dev cilium_host table 2005 metric 1024 pref medium
< default via fe80::8f9:c6ff:fe3d:3775 dev cilium_host table 2005 metric 1024 pref medium
---
> fe80::8f9:c6ff:fe3d:3775 dev cilium_host table 2005 proto kernel metric 1024 pref medium
> default via fe80::8f9:c6ff:fe3d:3775 dev cilium_host table 2005 proto kernel metric 1024 pref medium
10,13c10,12
< fd02::/120 via fd02::1cf dev cilium_host src fc00:c111::4 metric 1024 mtu 1450 pref medium
< fd02::1cf dev cilium_host metric 1024 pref medium
< fd02::100/120 via fd02::1cf dev cilium_host src fc00:c111::4 metric 1024 pref medium
< fe80::/64 dev cilium_host proto kernel metric 256 pref medium
---
> fd02::/120 via fd02::1cf dev cilium_host proto kernel src fc00:c111::4 metric 1024 mtu 1450 pref medium
> fd02::1cf dev cilium_host proto kernel metric 1024 pref medium
> fd02::100/120 via fd02::1cf dev cilium_host proto kernel src fc00:c111::4 metric 1024 pref medium
15,16d13
< anycast fe80:: dev cilium_host table local proto kernel metric 0 pref medium
< local fe80::241d:fff:fe71:c0db dev cilium_host table local proto kernel metric 0 pref medium
```

**Comment by aanm** [comment]
> > I got this diff in the before and after an upgrade. I wonder if this could be the reason why connectivity gets broken after upgrade.
> > [before.txt](https://github.com/cilium/cilium/files/11160303/before.txt) [after.txt](https://github.com/cilium/cilium/files/11160304/after.txt)
> 
> That's just how the reverted patch works. AFAICS, nothing that looks out of the ordinary. Is that the "issue" you noticed locally?

No, the issue is that after an upgrade from 1.13, all the connectivity of all pods break, including hostNetwork pods, and they never recover. I just tried to understand if any of the route diff would explain this issue.

**Comment by pchaigno** [comment]
If it's IPv6 that breaks, then maybe Jibi has the explanation above. If IPv4 breaks as well, then I don't think the route changes are related. We probably need someone from datapath to dig into this.

**Review by asauber — APPROVED** [review]
Approving as a "revert revert" which doesn't appear to break anything. Reaching out to the original reviewers might help for additional approvals here.

**Comment by jibi** [comment]
@nickolaev do you think https://github.com/cilium/cilium/pull/24756#issuecomment-1498604739 is related to the changes introduced in #24288? Should we reintroduce back that PR?

**Pull request closed without merging**
