### PR TITLE
Move all 'common' code to 'pkg'

### LINKED ISSUE #11293: Move all `common/` code into `pkg/`
We've moved to the code organization of having all common libraries under `pkg/` for quite some time now. We should move the remaining bits of `common/` under `pkg/` and retire this directory.

### PR DESCRIPTION
**Pull request by soumynathan**
This PR moves the common packages to the pkg folder.

Fixes: #11293
Signed-off-by: Swaminathan Vasudevan <svasudevan@suse.com>

### CODE REVIEW

**Review by tklauser — CHANGES_REQUESTED** [review]
The `maptool` build failure on Travis CI looks related to this PR: https://travis-ci.com/github/cilium/cilium/jobs/327849061

**Comment by tklauser** [comment]
test-me-please

**Comment by joestringer** [comment]
Precheck failed,

```
15:13:25  + cd /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/
15:13:25  + make jenkins-precheck
15:13:25  docker-compose -f test/docker-compose.yml -p Cilium-PR-Ginkgo-Tests-Validated-$BUILD_NUMBER run --rm precheck
15:13:26  Creating network "cilium-pr-ginkgo-tests-validated-19489_default" with the default driver
15:13:29  ineffassign .
15:13:29  contrib/scripts/check-logging-subsys-field.sh
15:13:29  contrib/scripts/check-fmt.sh
15:13:30  Unformatted Go source code:
...
```

**Comment by pchaigno** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by tklauser — COMMENTED** [review]
Please also drop the `./common/...` entry from the `govet` target in `Makefile` (can be done as a follow-up PR):

https://github.com/cilium/cilium/blob/5aeea785e0395f5687e5f1b532b5ff47d9e58dc1/Makefile#L403

**Review by tklauser — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
Thanks for picking this up! Looks like a good first cut. 

I think a follow-up could revise what's left in `pkg/common` and determine whether they would be more appropriate in a combined package with other bits, because `common` is so generic that it can easily magnet anything that doesn't fit somewhere. Also I saw the `pkg/common/build.sh` which can be removed.

I also wonder about `pkg/addressing` vs. `pkg/types`, seems like there's some commonality here which we could review to see if it makes sense to combine these (potentially also related, `pkg/cidr`.. For the L2 stuff we have `pkg/mac`.

None of this is blocking, we can further iterate on top of this PR as a base.

**Comment by joestringer** [comment]
There's been 3 reviews and the changes are trivial for remaining codeowners; it's also passing CI. Merging.

**Comment by soumynathan** [comment]
> Thanks for picking this up! Looks like a good first cut.
> 
> I think a follow-up could revise what's left in `pkg/common` and determine whether they would be more appropriate in a combined package with other bits, because `common` is so generic that it can easily magnet anything that doesn't fit somewhere. Also I saw the `pkg/common/build.sh` which can be removed.
> 
> I also wonder about `pkg/addressing` vs. `pkg/types`, seems like there's some commonality here which we could review to see if it makes sense to combine these (potentially also related, `pkg/cidr`.. For the L2 stuff we have `pkg/mac`.
> 
> None of this is blocking, we can further iterate on top of this PR as a base.

Makes sense.

**Pull request merged**
