### PR TITLE
Add NodePort BPF CI tests

### PR DESCRIPTION
**Pull request by brb**
This PR adds integration tests for NodePort BPF.

Please review per commit.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8875)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by borkmann** [comment]
For the log, we have the following combinations:

- [ ] Backend is local on the serving node
  - [ ] Direct routing mode
    - [ ] Request via phys dev
    - [ ] Request from own host ns (localhost IP, cilium_host IP)
    - [ ] Request out of podns (same IPs)
  - [ ] Tunnel mode
    - [ ] Request via phys dev
    - [ ] Request via tunnel dev
    - [ ] Request from own host ns (localhost IP, cilium_host IP)
    - [ ] Request out of podns (same IPs)
- [ ] Backend is remote from the serving node (SNAT)
  - Same matrix as above, in tunnel mode we have:
    - [ ] Request via phys dev (pkt path: phys -[node]> tunnel -[backend]> tunnel -[node]>phys)
    - [ ] Request via tunnel dev (pkt path: tunnel -[node]> tunnel -[backend]> tunnel -[node]> tunnel)

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
```
22:31:51      k8s1-1.15: Step 1/20 : FROM quay.io/cilium/cilium-envoy:d68c2561fae4c83960969a7aaa2a186c3b30e17a as cilium-envoy
22:32:09      k8s1-1.15: Get https://quay.io/v2/cilium/cilium-envoy/manifests/d68c2561fae4c83960969a7aaa2a186c3b30e17a: Get https://quay.io/v2/auth?scope=repository%3Acilium%2Fcilium-envoy%3Apull&service=quay.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
22:32:09      k8s1-1.15: Makefile:189: recipe for target 'docker-image-no-clean' failed
22:32:09      k8s1-1.15: make: *** [docker-image-no-clean] Error 1
```

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Pull request merged**
