### PR TITLE
v1.11 backports 2023-02-07

### PR DESCRIPTION
**Pull request by pchaigno**
- [x] #23202 -- Introduce node IDs (@pchaigno)
    - Lots of conflicts because ipcache was refactored to avoid global variables, because cluster IDs were introduced into tunnel map, because helper functions for CLI commands where introduced, etc.
 - [x] #23482 -- .github/workflows: PR labeler fix GH workflow if expression (@aanm)
 - [ ] #23429 -- fqdn/dnsproxy: move init LRU cache call out of StartDNSProxy. (@tommyp1ckles)
    - Trivial conflict due to formatting change.
 - [x] #22797 -- bugtool: Dump envoy metrics for troubleshooting (@sayboras)
    - Trivial conflict.
 - [x] #23502 -- envoy: Bump envoy version to 1.22.7 (@sayboras)

Skipped due to non-trivial conflicts:

 - #23463 -- Pick up etcd v3.5.7 (@michi-covalent)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 23202 23482 23429 22797 23502; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Comment by pchaigno** [comment]
/test-backport-1.11

**Comment by michi-covalent** [comment]
> Skipped due to non-trivial conflicts:
> https://github.com/cilium/cilium/pull/23463 -- Pick up etcd v3.5.7 (@michi-covalent)

i'll take care of backporting this 👍 🚢

**Review by aanm — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-backport-1.11

**Review by sayboras — APPROVED** [review]
Thanks for your help resolving conflict. LGTM 💯

**Comment by sayboras** [comment]
/test-backport-1.11

**Comment by pchaigno** [comment]
I manually ran a bunch of tests (checking node IDs are as expected, with different number of remote nodes, and different types of IP addresses; checking the logs for any issue) on the first commit and everything looks in order.

**Comment by pchaigno** [comment]
/test-backport-1.11

**Comment by sayboras** [comment]
/test-backport-1.11

**Comment by jrajahalme** [comment]
Both Travis CI test runs failed with:
```
----------------------------------------------------------------------
PANIC: ipcache_test.go:34: IPCacheTestSuite.TestIPCache
... Panic: runtime error: invalid memory address or nil pointer dereference (PC=0x438814)
/home/travis/.gimme/versions/go1.17.13.linux.amd64/src/runtime/panic.go:1038
  in gopanic
/home/travis/.gimme/versions/go1.17.13.linux.amd64/src/runtime/panic.go:221
  in panicmem
/home/travis/.gimme/versions/go1.17.13.linux.amd64/src/runtime/signal_unix.go:735
  in sigpanic
ipcache.go:407
  in IPCache.upsertLocked
ipcache.go:238
  in IPCache.Upsert
ipcache_test.go:93
  in IPCacheTestSuite.TestIPCache
/home/travis/.gimme/versions/go1.17.13.linux.amd64/src/reflect/value.go:339
  in Value.Call
/home/travis/.gimme/versions/go1.17.13.linux.amd64/src/runtime/asm_amd64.s:1581
  in goexit
----------------------------------------------------------------------
FAIL: ipcache_test.go:280: IPCacheTestSuite.TestIPCacheNamedPorts
ipcache_test.go:285:
    // Assure sane state at start.
    c.Assert(len(IPIdentityCache.ipToIdentityCache), Equals, 0)
... obtained int = 1
... expected int = 0
OOPS: 2 passed, 1 FAILED, 1 PANICKED
--- FAIL: Test (0.00s)
=== RUN   TestInjectLabels
--- PASS: TestInjectLabels (0.00s)
=== RUN   TestFilterMetadataByLabels
--- PASS: TestFilterMetadataByLabels (0.00s)
=== RUN   TestRemoveLabelsFromIPs
--- PASS: TestRemoveLabelsFromIPs (0.00s)
FAIL
coverage: 3.1% of statements in ./...
FAIL	github.com/cilium/cilium/pkg/ipcache	0.073s
FAIL
make: *** [Makefile:206: integration-tests] Error 1
The command "./.travis/build.sh" exited with 2.
Done. Your build exited with 1.
```

**Comment by pchaigno** [comment]
/test-backport-1.11

**Comment by pchaigno** [comment]
/test-backport-1.11

**Comment by pchaigno** [comment]
/test-backport-1.11

**Comment by pchaigno** [comment]
Tests are passing except for the BPF datapath one. That one is however already failing on the v1.11 branch since v1.11.0. I'll open an issue for that. Reviews are in. Merging.

**Pull request merged**
