### PR TITLE
1.4.0-rc3 backports

### PR DESCRIPTION
**Pull request by tgraf**
* PR: 6592 -- bpf: add check for CONFIG_MAP defines (@ianvernon) -- https://github.com/cilium/cilium/pull/6592
 * PR: 6589 -- examples: remove blank line at end of dns.yaml (@ianvernon) -- https://github.com/cilium/cilium/pull/6589
 * PR: 6585 -- docs: Update spelling list for toFQDNs rules (@raybejjani) -- https://github.com/cilium/cilium/pull/6585
 * PR: 6584 -- example: Fix DNS example policy (@tgraf) -- https://github.com/cilium/cilium/pull/6584
 * PR: 6563 -- Store/Restore DNS Cache state on restart (@raybejjani) -- https://github.com/cilium/cilium/pull/6563
 * PR: 6539 -- Reorganize cilium agent CLI flags (@aanm) -- https://github.com/cilium/cilium/pull/6539
 * PR: 6248 -- pid: handle os interrupts in daemon_main (@aanm) -- https://github.com/cilium/cilium/pull/6248
 * PR: 5077 -- policy: Introduce rate limiting for TriggerPolicyUpdates() (@tgraf) -- https://github.com/cilium/cilium/pull/5077
 * PR: 6547 -- docs: L3/7 toFQDNs documentation w/ matchPattern (@raybejjani) -- https://github.com/cilium/cilium/pull/6547

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6597)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Anything particular you'd like closer review of?

**Comment by tgraf** [comment]
> Anything particular you'd like closer review of?

The only merge conflicts were unused imports. Otherwise this was incredibly straight forward.

**Pull request merged**
