### PR TITLE
v1.9 backports 2021-08-17

### PR DESCRIPTION
**Pull request by pchaigno**
* #16216 -- pkg/redirectpolicy: Make code robust against incorrect policy configu… (@aditighag)
 * #17169 -- routing: Fix incorrect interface selection for egress pod routes (@pchaigno)
 * #17189 --  Fix Linux slave interface detection (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16216 17169 17189; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by pchaigno** [comment]
test-backport-1.9

**Review by ti-mo — APPROVED** [review]

**Review by aditighag — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by pchaigno** [comment]
test-1.12-netnext

**Comment by pchaigno** [comment]
test-1.13-4.9

**Comment by pchaigno** [comment]
test-1.15-4.9

**Comment by pchaigno** [comment]
test-1.16-4.9

**Comment by pchaigno** [comment]
test-backport-1.9

**Comment by pchaigno** [comment]
test-backport-1.9

**Comment by pchaigno** [comment]
test-1.12-netnext

**Comment by pchaigno** [comment]
test-gke

**Comment by pchaigno** [comment]
test-1.12-netnext

**Comment by pchaigno** [comment]
test-1.19-4.9

**Comment by twpayne** [comment]
@pchaigno Could you rebase this PR on the latest `v1.9` so we can re-run the backport tests and merge?

**Comment by pchaigno** [comment]
@twpayne It won't make a difference, the GKE CI is still broken on v1.9: https://jenkins.cilium.io/view/Cilium-v1.9/job/cilium-v1.9-k8s-gke/. I'm waiting for that to be fixed to update the PR.

**Comment by twpayne** [comment]
Ah, thank you for the info.

**Comment by joestringer** [comment]
The changes being backported here are unrelated to GKE, and GKE job is failing due to an env issue (#17282) so there's no evidence of any actual failure here. Zero flakes policy exempts backports from blocking due to test issues. Paul and I also discussed this briefly out-of-band and we see the risk as low for merging & including these changes in the upcoming releases.

Merging.

**Pull request merged**
