### PR TITLE
backport 1.3 2019 05 29

### PR DESCRIPTION
**Pull request by aanm**
* PR: #8066 -- pkg/endpoint: fix assignment in nil map on restore (@aanm) 
 * PR: #8105 -- Recover from ginkgo fail in WithTimeout helper (@nebril) 
 * PR: #8097 -- proxylib: Fix egress enforcement (@jrajahalme) 
 * PR: #8149 -- envoy: Prevent resending NACKed resources also when there are no ACK observers (@jrajahalme)
 * #7955 -- test: replace guestbook test docker image (@aanm)
 * #8235 -- .Jenkinsfile: remove leftover failFast (@aanm)
 * #8160 -- test: Enable IPv6 forwarding in test VMs (@iffyio)
 * #7869 -- pkg/health: Fix IPv6 URL format in HTTP probe (@iffyio)
 * #8290 -- Preload vagrant boxes in k8s upstream jenkinsfile (@nebril)
 * #8318 -- Don't set debug to true in monitor test (@nebril)
 * #8320 -- pkg/lock: RUnlock in RUnlockIgnoreTime (@aanm)
 * #8319 -- daemon: fix endpoint restore when endpoints are not available (@aanm)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 8066 8105 8097 8149 7955 8235 8160 7869 8290 8318 8320 8319; do contrib/backporting/set-labels.py $pr done 1.3; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8157)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
@raybejjani please take a look at the last commit

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
k8s tests failed with 
```
15:14:15      Guestbook deployment cannot be deleted
[2019-06-04T13:14:15.141Z]     Expected command: kubectl delete -f  /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/guestbook_deployment.json 
[2019-06-04T13:14:15.141Z]     To succeed, but it failed:
[2019-06-04T13:14:15.141Z]     Exitcode: 1 
[2019-06-04T13:14:15.141Z]     Stdout:
[2019-06-04T13:14:15.141Z]      	 replicationcontroller "redis-master" deleted
[2019-06-04T13:14:15.141Z]     	 service "redis-master" deleted
[2019-06-04T13:14:15.141Z]     	 replicationcontroller "redis-slave" deleted
[2019-06-04T13:14:15.141Z]     	 service "redis-slave" deleted
[2019-06-04T13:14:15.141Z]     	 
[2019-06-04T13:14:15.141Z]     Stderr:
[2019-06-04T13:14:15.141Z]      	 Error from server (NotFound): error when stopping "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/guestbook_deployment.json": deployments.extensions "frontend" not found
[2019-06-04T13:14:15.141Z] 
```

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
@tgraf The CI fails for the monitor tests, did we change anything in 1.3 that could affect this? https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12806/

```
runtime.RuntimeMonitorTest With Sample Containers Cilium monitor verbose mode
runtime.RuntimeMonitorTest With Sample Containers Cilium monitor event types
runtime.RuntimeMonitorTest With Sample Containers cilium monitor check --from
runtime.RuntimeMonitorTest With Sample Containers cilium monitor check --related-to
```

for example:
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
"FROM 12090 DEBUG:" is not in the output after timeout
Expected
    <*errors.errorString | 0xc420424130>: {
        s: "Timeout reached: FROM 12090 DEBUG: is not in the output after timeout",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/runtime-gopath/src/github.com/cilium/cilium/test/runtime/monitor.go:109
```

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
never-tell-me-the-odds

**Comment by nebril** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
test-upstream-k8s

**Comment by joestringer** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
test-upstream-k8s

**Comment by joestringer** [comment]
Latest failure during provision:
https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/1364/execution/node/42/log/

```
07:06:52      k8s1-1.12: docker build --build-arg LOCKDEBUG=1 --build-arg V= -t "cilium/cilium:"latest"" .
07:13:54      k8s1-1.12: Sending build context to Docker daemon  11.54GB
07:13:54      k8s1-1.12: Step 1/18 : FROM quay.io/cilium/cilium-envoy:68c49eeb8241867829c5eab4dff13a316c71c355 as cilium-envoy
07:13:54      k8s1-1.12: 68c49eeb8241867829c5eab4dff13a316c71c355: Pulling from cilium/cilium-envoy
07:13:54      k8s1-1.12: 59fc10cbb750: Pulling fs layer
07:13:54      k8s1-1.12: 59fc10cbb750: Verifying Checksum
07:13:54      k8s1-1.12: 59fc10cbb750: Download complete
07:13:54      k8s1-1.12: 59fc10cbb750: Pull complete
07:13:54      k8s1-1.12: Digest: sha256:6579ea6d0c6ab19e07e6c07f52f1633846eadd0842db06ffe335f0cfd846c9a4
07:13:54      k8s1-1.12: Status: Downloaded newer image for quay.io/cilium/cilium-envoy:68c49eeb8241867829c5eab4dff13a316c71c355
07:13:54      k8s1-1.12:  ---> d6de2e5e111c
07:13:54      k8s1-1.12: Step 2/18 : FROM quay.io/cilium/cilium-builder:2018-09-17 as builder
07:13:54      k8s1-1.12: 2018-09-17: Pulling from cilium/cilium-builder
07:13:54      k8s1-1.12: 124c757242f8: Already exists
07:13:54      k8s1-1.12: 9d866f8bde2a: Already exists
07:13:54      k8s1-1.12: fa3f2f277e67: Already exists
07:13:54      k8s1-1.12: 398d32b153e8: Already exists
07:13:54      k8s1-1.12: afde35469481: Already exists
07:13:54      k8s1-1.12: 60471827b3c4: Pulling fs layer
07:13:54      k8s1-1.12: 23a51e7fc0e4: Pulling fs layer
07:13:54      k8s1-1.12: 28620e3a1fc0: Pulling fs layer
07:13:54      k8s1-1.12: 4a698fabeb6e: Pulling fs layer
07:13:54      k8s1-1.12: b99f97de70a7: Pulling fs layer
07:13:54      k8s1-1.12: 71624f54493a: Pulling fs layer
07:13:54      k8s1-1.12: 41521fe803c6: Pulling fs layer
07:13:54      k8s1-1.12: dbe60f07d7a8: Pulling fs layer
07:13:54      k8s1-1.12: 4a698fabeb6e: Waiting
07:13:54      k8s1-1.12: b99f97de70a7: Waiting
07:13:54      k8s1-1.12: 71624f54493a: Waiting
07:13:54      k8s1-1.12: 41521fe803c6: Waiting
07:13:54      k8s1-1.12: dbe60f07d7a8: Waiting
07:13:54      k8s1-1.12: 60471827b3c4: Verifying Checksum
07:13:54      k8s1-1.12: 60471827b3c4: Download complete
07:13:54      k8s1-1.12: 4a698fabeb6e: Verifying Checksum
07:13:54      k8s1-1.12: 4a698fabeb6e: Download complete
07:13:56      k8s1-1.12: 23a51e7fc0e4: 
07:13:56      k8s1-1.12: Verifying Checksum
07:13:56      k8s1-1.12: 23a51e7fc0e4: 
07:13:56      k8s1-1.12: Download complete
07:13:56      k8s1-1.12: 28620e3a1fc0: 
07:13:56      k8s1-1.12: Verifying Checksum
07:13:56      k8s1-1.12: 28620e3a1fc0: 
07:13:56      k8s1-1.12: Download complete
07:13:56      k8s1-1.12: 71624f54493a: 
07:13:56      k8s1-1.12: Verifying Checksum
07:13:56      k8s1-1.12: 71624f54493a: 
07:13:56      k8s1-1.12: Download complete
07:13:56      k8s1-1.12: 41521fe803c6: 
07:13:56      k8s1-1.12: Verifying Checksum
07:13:56      k8s1-1.12: 41521fe803c6: 
07:13:56      k8s1-1.12: Download complete
07:13:56      k8s1-1.12: b99f97de70a7: 
07:13:56      k8s1-1.12: Verifying Checksum
07:13:56      k8s1-1.12: b99f97de70a7: 
07:13:56      k8s1-1.12: Download complete
07:14:23      k8s1-1.12: dbe60f07d7a8: 
07:14:23      k8s1-1.12: Verifying Checksum
07:14:23      k8s1-1.12: dbe60f07d7a8: 
07:14:23      k8s1-1.12: Download complete
07:14:49      k8s1-1.12: 60471827b3c4: 
07:14:49      k8s1-1.12: Pull complete
07:14:55      k8s1-1.12: 23a51e7fc0e4: 
07:14:55      k8s1-1.12: Pull complete
07:15:13      k8s1-1.12: 28620e3a1fc0: Pull complete
07:15:32      k8s1-1.12: 4a698fabeb6e: 
07:15:32      k8s1-1.12: Pull complete
07:15:32      k8s1-1.12: b99f97de70a7: Pull complete
07:15:32      k8s1-1.12: 71624f54493a: Pull complete
07:15:32      k8s1-1.12: 41521fe803c6: Pull complete
07:17:29      k8s1-1.12: dbe60f07d7a8: Pull complete
07:17:29      k8s1-1.12: Digest: sha256:6c6db0e6d9cf6e444be7d45d89d375de5fe04733a55bade9756f456a0ec59a27
07:17:29      k8s1-1.12: Status: Downloaded newer image for quay.io/cilium/cilium-builder:2018-09-17
07:17:29      k8s1-1.12:  ---> fb7f8d18b938
07:17:29      k8s1-1.12: Step 3/18 : LABEL maintainer="maintainer@cilium.io"
07:17:29      k8s1-1.12:  ---> Running in 89a9e9c18e5b
07:17:29      k8s1-1.12: Removing intermediate container 89a9e9c18e5b
07:17:29      k8s1-1.12:  ---> 9fbb04b8af32
07:17:29      k8s1-1.12: Step 4/18 : WORKDIR /go/src/github.com/cilium/cilium
07:17:29      k8s1-1.12:  ---> Running in 4e7a8959f44a
07:17:29      k8s1-1.12: Removing intermediate container 4e7a8959f44a
07:17:29      k8s1-1.12:  ---> cad678be6f7b
07:17:29      k8s1-1.12: Step 5/18 : COPY . ./
07:24:01      k8s1-1.12: Error processing tar file(exit status 1): unexpected EOF
07:24:01      k8s1-1.12: Makefile:136: recipe for target 'docker-image-no-clean' failed
07:24:01      k8s1-1.12: make: *** [docker-image-no-clean] Error 1
```

**Comment by joestringer** [comment]
test-upstream-k8s

**Comment by joestringer** [comment]
I looked at the last several (five or so) 1.3 backports, and we never ran the upstream-k8s tests for those. I'm not sure if it ever worked.

**Comment by joestringer** [comment]
Filed known issues here:
https://github.com/cilium/cilium/projects/46

There's no `.travis` directory so I'm assuming that travis was never intended to run against v1.3. That means we should be good to merge.

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Comment by joestringer** [comment]
test-me-please

**Pull request merged**
