### PR TITLE
l4lb: add health-probe support for DSR-Geneve configs

### LINKED ISSUE #27024: Stand-alone L4LB: support health-checks for DSR-Geneve mode
The L4LB offers health-checking for backends (`ENABLE_HEALTH_CHECK`). But currently this feature is limited to DSR with IPIP encapsulation. We should also enable it for DSR-Geneve (at least when in high-scale ipcache mode).

### PR DESCRIPTION
**Pull request by julianwiedmann**
This extends the health-probe feature in the L4LB to also support DSR with Geneve-dispatch (currently it's limited to IPIP dispatch). The main use-case is for high-scale ipcache, so I didn't bother with adding IPv6 support at this point.

The Geneve path is a bit more involved than the IPIP one, to DNAT the packet & insert the DSR option. There's a good amount of overlap with `encap_geneve_dsr_opt4()` here, so I'll see if it's worth extracting a shared helper (in a follow-on PR).

### CODE REVIEW

**Review by brlbil — APPROVED** [review]

**Review by lmb — APPROVED** [review]
Loader changes LGTM.

**Review by asauber — APPROVED** [review]
CLI-related changes LGTM

**Review by thorn3r — APPROVED** [review]
agent changes look good :+1:

**Pull request closed without merging**
