### PR TITLE
hubble: improve policy verdict status (use ALLOWED/DENIED instead of REDIRECTED/FORWARDED/DROPPED)

### PR DESCRIPTION
**Pull request by rolinh**
From a user perspective, it is much easier to understand the flow type when policy verdict events verdicts use the term ALLOWED instead of REDIRECTED/FORWARDED and DENIED instead of DROPPED.

See also: https://github.com/cilium/hubble/issues/570, https://github.com/cilium/hubble/pull/745 and https://github.com/cilium/hubble/issues/740

### CODE REVIEW

**Comment by rolinh** [comment]
I'm also a bit worried about breaking backwards compatibility, which is why I opened this PR as draft for discussion. I didn't think of adding a new field but I agree this might add too much noise for little benefits.

My main concern about the changes proposed in https://github.com/cilium/hubble/pull/745 is that users might think that `ALLOWED` and `DENIED` are valid verdict values, which is why I opened this PR. Maybe another way to address this issue would be at the CLI level where we'd auto convert `ALLOWED` to `FORWARDED || REDIRECTED` and `DENIED` to `DROPPED`?

**Comment by gandro** [comment]
> Maybe another way to address this issue would be at the CLI level where we'd auto convert `ALLOWED` to `FORWARDED || REDIRECTED` and `DENIED` to `DROPPED`?

I think we should do that, yes. I'm very nervous about changing the verdict. I have found code in the wild which checks the verdict for policy verdict events, which would broken by this PR:

```go
	if f.GetEventType().GetType() != int32(monitorAPI.MessageTypePolicyVerdict) ||
		f.GetVerdict() != pb.Verdict_FORWARDED {
		// we are only interested in policy verdict notifications for forwarded flows
		return nil
	}
```

**Comment by gandro** [comment]
> Maybe another way to address this issue would be at the CLI level where we'd auto convert `ALLOWED` to `FORWARDED || REDIRECTED` and `DENIED` to `DROPPED`?

I think we should do that, yes. I'm very nervous about changing the verdict. I have found code in the wild which checks the verdict for policy verdict events, which would broken by this PR:

```go
	if f.GetEventType().GetType() != int32(monitorAPI.MessageTypePolicyVerdict) ||
		f.GetVerdict() != pb.Verdict_FORWARDED {
		// we are only interested in policy verdict notifications for forwarded flows
		return nil
	}
```

**Comment by rolinh** [comment]
It looks like the potential downsides that this PR would bring outweigh the upsides. We shouldn't break the API unless we have a very compelling argument.

**Pull request closed without merging**
