### PR TITLE
helm: Bump Hubble-UI images to v0.10.0

### PR DESCRIPTION
**Pull request by pjbgf**
Bump Hubble images used on Helm chart to `v0.10.0`.

```release-note
Update Helm Chart to use Hubble-UI v0.10.0 images by default.
```

### CODE REVIEW

**Comment by tommyp1ckles** [comment]
lgtm, but I'm not so familiar with hubble versions @michi-covalent does this make sense?

**Comment by sayboras** [comment]
same point as above, just add Dima (who is hubble UI maintainer) as reviewer.

**Comment by michi-covalent** [comment]
the change looks good to me ✅ , you need to run `make -C Documentation update-helm-values` to update `Documentation/helm-values.rst`

**Comment by pjbgf** [comment]
@michi-covalent thank you for the review, I updated the PR accordingly. PTAL

**Review by michi-covalent — APPROVED** [review]

**Review by geakstr — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Comment by pjbgf** [comment]
The arm64 failed test seems to be orthogonal:

```
docker: 'buildx' is not a docker command.
See 'docker --help'
  CHECK   vetting all packages...
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   FAIL  package: github.com/cilium/cilium/pkg/k8s/identitybackend   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

--- FAIL: TestGetIdentity (0.61s)
                                 
    --- FAIL: TestGetIdentity/Duplicated_identity (0.03s)
                                                         
    identity_test.go:218: Expected key 10, got 11
```

Rebasing now to trigger another run.

**Comment by sayboras** [comment]
> ┃   FAIL  package: github.com/cilium/cilium/pkg/k8s/identitybackend   ┃

the above failure is not related to this PR, but more about the flake. I initiated one convo in Cilium development channel 

https://cilium.slack.com/archives/C2B917YHE/p1674537258592139

**Review by tommyp1ckles — APPROVED** [review]

**Comment by pjbgf** [comment]
Please let me know when this would be OK for merge so I can do another rebase.

**Comment by rolinh** [comment]
> Please let me know when this would be OK for merge so I can do another rebase.

I think we can label the PR as ready to merge. Hubble UI is not covered in CI tests and Helm lint tests are :heavy_check_mark:

**Pull request merged**
