### PR TITLE
v1.1 backports 2018-08-09

### PR DESCRIPTION
**Pull request by borkmann**
PRs backported:

- #5109 
- #5096 
- #5090 (with dependencies)

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5143)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Ah, previously I had avoided backporting 036982fa8ce403edf90ae98c6a494085b441e46d by just importing the old package as `api`. However this backport looks fine to me, we'll just have two backports of 66e36c4160e3671372de5fe79a8678a5d60b2f96 in the 1.1 tree.

**Comment by borkmann** [comment]
@joestringer Yeah it's twice now, though closer to upstream. I'm fine either way, could also drop the two dependencies.

**Comment by joestringer** [comment]
I'm happy with it as-is.

**Pull request merged**
