### PR TITLE
test: add cilium-etcd-operator to k8s upstream tests

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6388)

### CODE REVIEW

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
@aanm should this be backported to 1.3 since we run cilium-etd-operator in that branch as well?

**Comment by aanm** [comment]
@ianvernon good point, I guess it makes sense

**Pull request merged**
