### PR TITLE
v1.0 backports 2018-07-09

### PR DESCRIPTION
**Pull request by borkmann**
PRs included:

* #4265 (partial backport, second commit not included since 1.12 deployment examples in tree already)
* #4690 
* #4709 
* #4744 
* #4708 

PRs not included:

* #4675
* #4635 (comment in #4752)

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4783)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by eloycoto** [comment]
Hi @borkmann are you taking care of this PR?

**Comment by borkmann** [comment]
Yep, will get back on this today, sorry was swamped with fixing kernel bugs yesterday.

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
Thanks for taking care of the backports @borkmann

**Comment by ianvernon** [comment]
@borkmann in the future please be sure to update the labels accordingly on the backported PRs to have 'backport-done'

**Pull request merged**
