### PR TITLE
[v1.12] bpf, maps: Don't set nodeid to 0 when nodeid allocation fails.

### PR DESCRIPTION
**Pull request by tommyp1ckles**

### CODE REVIEW

**Comment by tommyp1ckles** [comment]
/test-backport-1.12

**Comment by marseel** [comment]
lgtm

It was a bit unobvious, because now allocation doesn't return an error, instead it just returns an empty nodeID which is not used in case of lack of IPSec:
https://github.com/cilium/cilium/blob/bbb03106d55e4c124b2538e0326f8bb38e9000da/pkg/datapath/linux/node.go#L866C3-L866C15

**Review by dylandreimerink — APPROVED** [review]

**Comment by dylandreimerink** [comment]
/test-1.18-4.9

**Pull request closed without merging**
