### PR TITLE
update cilium to golang 1.10.3

### PR DESCRIPTION
**Pull request by aanm**
(adding `area/k8s` to run more tests)

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4635)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by jrajahalme** [comment]
I don't see changes to Vagrantfiles; does the current packer-ci-build box version already contain the new Go version?

**Comment by aanm** [comment]
@jrajahalme version 90 will have go 1.10 which will be a PR created by @eloycoto

**Comment by eloycoto** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by eloycoto** [comment]
quick one, `test/docker-compose.yaml` should be updated too, no?

**Comment by aanm** [comment]
@eloycoto yes. I was not aware of that file when I've made this PR. I'll create a new PR with that change

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
@aanm does this still need backport for 1.0? @manalibhutiyani noted that it was skipped due to issues with compiling Envoy:

> Also PR: #4635 -- update cilium to golang 1.10.3 (@aanm)
Because it was leading to envoy compilation errors
Please check development channel on slack for reference as well as #4737

**Pull request merged**
