### PR TITLE
Nightly fixes

### PR DESCRIPTION
**Pull request by eloycoto**
Multiple Nightly fixes

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6840)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
@cilium/ci can we get a review on this, also merge it? This fix a lot of CI failures, due the changes in CiliumPolicyAction, there are still two issues that I would like to track down in a new PR, this is a great change overall. 


Thanks

**Review by aanm — APPROVED** [review]

**Pull request merged**
