### PR TITLE
update k8s dependencies to 1.16.7

### PR DESCRIPTION
**Pull request by aanm**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10216)

### CODE REVIEW

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Pull request merged**
