### PR TITLE
Aspsk/pr/add new info to drop notify messages

### PR DESCRIPTION
**Pull request by aspsk**
Two main changes:
  * Add `ifindex` to drop notificagtions (taken from `ctx->ifindex`/`ctx->ingress_ifindex`)
  * Replace source file name by id to reduce noise in `cilium monitor -t drop` (as was requested by some guys)

```release-note
Improve verbosity of drop notification messages.
```

### CODE REVIEW

**Review by dylandreimerink — APPROVED** [review]
LGTM

**Review by NikAleksandrov — APPROVED** [review]

**Comment by aspsk** [comment]
/test-1.23-4.19

**Pull request merged**
