### PR TITLE
[v1.13] envoy: Update envoy version to 1.25.x

### PR DESCRIPTION
**Pull request by sayboras**
## Description

Envoy 1.24 will be EOL in Oct 2023, this commit is to proactively bump envoy version to 1.25.

Related build: https://github.com/cilium/proxy/actions/runs/6160387030/job/16717229803

## Note

This PR contains the backport of https://github.com/cilium/cilium/pull/24684 to pickup the fix 466ab24e261c6093ba9fbacbe24b6160ca6326b9 for below issue.

```
2023-09-29T15:02:01.513660624Z level=warning msg="NACK received for versions after  and up to 3; waiting for a version update before sending again" subsys=xds xdsAckedVersion= xdsClientNode="host~127.0.0.1~no-id~localdomain" xdsDetail="Only unique values for domains are permitted. Duplicate entry of domain foo.bar.com in route default/cilium-ingress-default-host-rules/listener-insecure" xdsNonce=3 xdsStreamID=6 xdsTypeURL=type.googleapis.com/envoy.config.route.v3.RouteConfiguration
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.13

**Comment by sayboras** [comment]
/test-backport-1.13

**Comment by sayboras** [comment]
/test-backport-1.13

**Comment by sayboras** [comment]
/test-backport-1.13

**Comment by sayboras** [comment]
/test-backport-1.13

**Comment by sayboras** [comment]
/test-backport-1.13

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
