### PR TITLE
v1.9 backports 2021-04-30

### PR DESCRIPTION
**Pull request by pchaigno**
* #15765 -- test: 5.4 CI job (@pchaigno)
    - I added a commit (first one) to define the Vagrant box version.
    - Many minor conflicts.

Skipped in this PR:

 * #15934 -- Drop a `@` in clustermesh-apiserver helm chart (@anthr76)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 15765; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by pchaigno** [comment]
test-1.17-5.4

**Comment by pchaigno** [comment]
test-1.17-5.4

**Comment by pchaigno** [comment]
test-1.18-5.4

**Comment by pchaigno** [comment]
test-only --focus="K8sDatapathConfig .* routes" --kernel_version=54 --k8s_version=1.17

**Comment by pchaigno** [comment]
test-1.17-5.4

**Comment by pchaigno** [comment]
test-backport-1.9

**Comment by pchaigno** [comment]
test-1.17-5.4

**Comment by pchaigno** [comment]
test-1.17-5.4

**Comment by pchaigno** [comment]
test-backport-1.9

**Comment by pchaigno** [comment]
test-backport-1.9

**Review by ti-mo — APPROVED** [review]
This looks good, does it need more review?

**Pull request merged**
