### PR TITLE
v1.14 Backports 2023-09-26

### PR DESCRIPTION
**Pull request by giorio94**
* [x] #27567 (@jschwinger233)
 * [x] #27996 (@jschwinger233)
 * [x] #28065 (@julianwiedmann) (verified by @giorio94)
 * [x] #27953 (@asauber)
         :information_source: Re-applied hunk to the v1.14 version of the upgrade notes.
 * [x] #27870 (@joamaki)
         :information_source: Dropped changes in install/kubernetes/Makefile as the given line was not present in v1.14, and re-generated the cilium/values.yaml and cmdref/cilium-agent.md files from scratch.
 * [x] #28131 (@carnerito) (verified by @giorio94)
 * [x] #28122 (@qmonnet)
 * [x] #28133 (@julianwiedmann) (verified by @giorio94)
 * [x] #27841 (@macmiranda) (verified by @giorio94)
 * [x] #27959 (@chaunceyjiang) (Verified by @sayboras)
 * [x] #28018 (@chaunceyjiang)  (verified by @giorio94)
 * [x] #28161 (@qmonnet)
 * [x] #28145 (@margamanterola)
 * [x] #28173 (@aanm)
 * [x] #28172 (@qmonnet)
         :information_source: Picked Documentation/requirements.txt verbatim from the main branch to keep it consistent across versions, as we nonetheless use the same image in CI.
 * [x] #28163 (@mhofstetter)
 * [x] #27873 (@giorio94)
 * [x] #27691 (@weizhoublue) (verified by @giorio94)
         :information_source:  Dropped the CODEOWNERS changes, as not propagated to stable branches.
 * [x] #28221 (@giorio94)
 * [x] #28249 (@nbusseneau)
 * [x] #28219 (@mhofstetter)
         :information_source: Switched cilium/dns import to miekg/dns, as v1.14 was relying on a replace directive instead of pointing to the fork.
 * [x] #28225 (@nbusseneau)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 27567 27996 28065 27953 27870 28131 28122 28133 27841 27959 28018 28161 28145 28173 28172 28163 27873 27691 28221 28249 28219 28225; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=27567,27996,28065,27953,27870,28131,28122,28133,27841,27959,28018,28161,28145,28173,28172,28163,27873,27691,28221,28249,28219,28225
```

### CODE REVIEW

**Review by aanm — APPROVED** [review]
My changes look good. Thank you!

**Comment by giorio94** [comment]
/test-backport-1.14

**Review by qmonnet — APPROVED** [review]
Backports for my doc PRs look good, thank you!

**Review by nbusseneau — APPROVED** [review]
My changes LGTM.

**Review by margamanterola — APPROVED** [review]
My changes look good

**Comment by giorio94** [comment]
The build commits check failed due to timeout. Manually run `git rebase --exec "make -C test build -j $(nproc) && make -C test build-darwin" upstream/v1.14` locally, which correctly succeeded (this was the only step not run by the CI).

**Review by asauber — APPROVED** [review]
Config changes LGTM.

Thanks for the backports

**Review by jschwinger233 — APPROVED** [review]
Mine are good, thanks.

**Review by pippolo84 — APPROVED** [review]
PR 28163 and 28219 LGTM :+1:

**Review by sayboras — APPROVED** [review]
LGTM for HTTPRoute commit ✅

**Review by joamaki — APPROVED** [review]

**Pull request merged**
