### PR TITLE
v1.14 Backports 2023-09-04

### PR DESCRIPTION
**Pull request by jibi**
* [x] #27656 (@pchaigno)
 * [x] #27698 (@mhofstetter)
   * minor conflict, see first commit
 * [x] #27713 (@tommyp1ckles)
 * [x] #27695 (@Managarmrr)
 * [x] #27572 (@bimmlerd)
 * [x] #27822 (@tklauser)
   * minor conflict, see third commit
 * [x] #27171 (@joestringer)
 * [x] #27818 (@mhofstetter)
 * [x] #27416 (@brb)
 * [x] #27831 (@tklauser)
 * [x] #27814 (@haiyuewa)
 * [x] #27359 (@brb)
   * not sure I applied all changes correctly as the 2 workflows were a bit different, please double check
 * [x] #27738 (@brb)
 * [x] #27706 (@tklauser)
   * minor conflict, see first commit
 * [x] #27170 (@joestringer)
 * [x] #27872 (@pchaigno)
   * minor conflict, see first commit

PRs skipped due to conflicts:

 * #27602 (@julianwiedmann)
   * non obvious conflict due to the `#ifndef DISABLE_LOOPBACK_LB` block in lib/conntrack.h missing in v1.14
 * #26663 (@gandro)
   * non obvious conflicts as `enableIPSecIPv{4,6}` don't return an error in v1.14

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 27656 27698 27713 27695 27572 27822 27171 27818 27416 27831 27814 27359 27738 27706 27170 27872; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=27656,27698,27713,27695,27572,27822,27171,27818,27416,27831,27814,27359,27738,27706,27170,27872
```

### CODE REVIEW

**Comment by jibi** [comment]
/test-backport-1.14

**Comment by jibi** [comment]
/test-backport-1.14

**Review by mhofstetter — APPROVED** [review]

**Comment by brb** [comment]
ci-e2e fails due to:
> unknown flag: --secondary-network-iface

To fix that we need to bump the CLI version to v0.15.7

**Comment by brb** [comment]
> To fix that we need to bump the CLI version to v0.15.7

I wonder why it didn't get updated by renovate. cc @aanm

**Comment by jibi** [comment]
waiting on https://github.com/cilium/cilium/pull/27919 then will rebase

**Comment by jibi** [comment]
/test-backport-1.14

**Review by brb — APPROVED** [review]
Thanks!

**Comment by jibi** [comment]
/test-backport-1.14

**Review by haiyuewa — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
My changes look good. Thanks for fixing up the conflicts and documenting the resolution in the commit messages!

**Review by bimmlerd — APPROVED** [review]
#27572 LGTM, thanks!

**Review by pchaigno — APPROVED** [review]
My PRs look good. Thanks!

**Review by tommyp1ckles — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Review by youngnick — APPROVED** [review]
LGTM, I checked the Gateway API PR as well.

**Pull request merged**
