### PR TITLE
examples/kubernetes: remove unmaintained k8s deployment files

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5155)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by eloycoto** [comment]
`examples/prometheus.yaml` is used in `test/test_suite.go`

**Review by eloycoto — CHANGES_REQUESTED** [review]
Nothing.

**Review by eloycoto — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]
Good catch!

**Comment by ianvernon** [comment]
GitHub issue with K8s tests: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/657/execution/node/7/log/

GitHub issue with upstream tests: https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/441/execution/node/7/log/

Trying again.

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
Upstream k8s tests failed due to the stage timing out after 30 mins: 
https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/443/

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Pull request merged**
