### PR TITLE
[v1.14] fqdn: Add Protocol to DNS Proxy Cache

### PR DESCRIPTION
**Pull request by nathanjsweet**
DNS Proxy indexes domain selectors by port
only. In cases where protocols collide on port
the DNS proxy may have a more restrictive selector than it should because it does not merge port
protocols for L7 policies (only ports).

Refactor all users of the DNS Proxy are updated
to add protocol to any DNS Proxy entries, and all
tests are updated to test for port-protocol
merge errors.

```release-note
fqdn: Fixed bug that caused DNS Proxy to be overly restrictive on allowed DNS selectors.
```

### CODE REVIEW

**Comment by nathanjsweet** [comment]
This is a backport of https://github.com/cilium/cilium/pull/31328

**Comment by nathanjsweet** [comment]
/test-backport-1.14

**Comment by julianwiedmann** [comment]
@nathanjsweet looks like the integration tests caught a persistent fail: https://github.com/cilium/cilium/actions/runs/8574930543/job/23517128951. I'll switch to draft for now, could you please have a look?

**Comment by nathanjsweet** [comment]
/test-backport-1.14

**Review by joestringer — APPROVED** [review]

**Pull request merged**
