### PR TITLE
Re-enable microscope

### PR DESCRIPTION
**Pull request by eloycoto**
Still WIP, waiting for DNS/service flake

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4407)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
It works: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3916/

**Comment by ianvernon** [comment]
@eloycoto the reason it was reverted was due to the microscope processes not actually being killed on the nodes, which caused the kernel to have to forcibly terminate processes, which caused test failures. Work will have to be done to forcibly terminate the microscope processes launched in each test, as well as testing to ensure that the processes are actually killed, as this was not done when microscope was re-enabled last time.

**Comment by eloycoto** [comment]
@ianvernon I wanted to have a fail with the Kube-dns, that it's not a PR to merge.

**Comment by ianvernon** [comment]
@eloycoto makes sense. However, the issue I outlined above may impact your desire to get a build with the microscope output.

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
@ianvernon if you can review this, it'll be great. 

Regards

**Comment by eloycoto** [comment]
Close due https://github.com/cilium/cilium/pull/4452

**Pull request closed without merging**
