### PR TITLE
updated eni limits for AWS instances

### PR DESCRIPTION
**Pull request by tsolodov**
Cilium does not have ENI limits defined for some AWS instance types. 
Used aws cli command from limits.go file:
`AWS_REGION=us-east-1 aws ec2 describe-instance-types | jq -r '.InstanceTypes[] | "\"\(.InstanceType)\": {Adapters: \(.NetworkInfo.MaximumNetworkInterfaces), IPv4: \(.NetworkInfo.Ipv4AddressesPerInterface), IPv6: \(.NetworkInfo.Ipv6AddressesPerInterface), HypervisorType: \"\(.Hypervisor)\"},"'  | sort | sed "s/null//"`

Fixes: #issue-number

```release-note
Updated AWS ENI limits
```

## Updated
- "g5.48xlarge"

## Added
- "c6id.12xlarge"
- "c6id.16xlarge"
- "c6id.24xlarge"
- "c6id.2xlarge"
- "c6id.32xlarge"
- "c6id.4xlarge"
- "c6id.8xlarge"
- "c6id.large"
- "c6id.metal"
- "c6id.xlarge"
- "c6in.12xlarge"
- "c6in.16xlarge"
- "c6in.24xlarge"
- "c6in.2xlarge"
- "c6in.32xlarge"
- "c6in.4xlarge"
- "c6in.8xlarge"
- "c6in.large"
- "c6in.xlarge"
- "c7g.12xlarge"
- "c7g.16xlarge"
- "c7g.2xlarge"
- "c7g.4xlarge"
- "c7g.8xlarge"
- "c7g.large"
- "c7g.medium"
- "c7g.xlarge"
- "i4i.metal"
- "m6id.12xlarge"
- "m6id.16xlarge"
- "m6id.24xlarge"
- "m6id.2xlarge"
- "m6id.32xlarge"
- "m6id.4xlarge"
- "m6id.8xlarge"
- "m6id.large"
- "m6id.metal"
- "m6id.xlarge"
- "mac2.metal"
- "r6a.12xlarge"
- "r6a.16xlarge"
- "r6a.24xlarge"
- "r6a.2xlarge"
- "r6a.32xlarge"
- "r6a.48xlarge"
- "r6a.4xlarge"
- "r6a.8xlarge"
- "r6a.large"
- "r6a.metal"
- "r6a.xlarge"
- "r6id.12xlarge"
- "r6id.16xlarge"
- "r6id.24xlarge"
- "r6id.2xlarge"
- "r6id.32xlarge"
- "r6id.4xlarge"
- "r6id.8xlarge"
- "r6id.large"
- "r6id.metal"
- "r6id.xlarge"
- "trn1.2xlarge"
- "trn1.32xlarge"
- "u-18tb1.112xlarge"
- "u-24tb1.112xlarge"
- "x2idn.metal"
- "x2iedn.metal"

### CODE REVIEW

**Review by sichenzhao — APPROVED** [review]

**Review by christarazi — APPROVED** [review]
Thanks for the PR. LGTM.

**Comment by tsolodov** [comment]
> Thanks for the PR. LGTM.

Thank you for quick response. Question: will it automatically be pushed to 1.12.x or I need to create another PR for 1.12 ?

**Comment by christarazi** [comment]
> Thank you for quick response. Question: will it automatically be pushed to 1.12.x or I need to create another PR for 1.12 ?

It will not be automatically pushed to v1.12.x because we follow a backport process to do that. We label PRs that need backport with `needs-backport/1.12` if the PR meets the [backport criteria](https://docs.cilium.io/en/v1.12/contributing/release/backports/#id1). The criteria for this PR would be

> * All bugfixes
> * Debug tool improvements

It's not clear to me that this is a bugfix, given that there are workarounds for this [documented](https://docs.cilium.io/en/v1.12/concepts/networking/ipam/eni/#ec2-instance-types-eni-limits). Although, I'm happy to have a discussion if you do think so.

**Pull request merged**
