### PR TITLE
bpf: add missing drop notifications

### PR DESCRIPTION
**Pull request by julianwiedmann**
End goal was to get rid of the stray drop notification that's currently buried in `__encap_and_redirect_with_nodeid()`. Getting there took quite a few additional drive-by fixes :).

The last two patches can be dropped from the backport (`encap_and_redirect_with_nodeid_opt()` didn't exist in v1.13).

```release-note
Add drop notifications for various error paths in the datapath.
```

### CODE REVIEW

**Comment by julianwiedmann** [comment]
BPF checkpatch complains about

>   CHECK:PARENTHESIS_ALIGNMENT: Alignment should match open parenthesis
>   #21: FILE: bpf/bpf_host.c:1278:
>   +				ret = encap_and_redirect_with_nodeid_opt(ctx,
>    								  ctx_get_xfer(ctx,

which was already bad before. And fixing it means triggering checkpatch again, because we're then exceeding max line width :shrug:. Think I'm good leaving it as is, we're planning to remove this code during the current release cycle anyway.

**Comment by julianwiedmann** [comment]
@ldelossa :wave: how can I help with making your review easier?

**Review by ldelossa — APPROVED** [review]
LGTM

**Comment by julianwiedmann** [comment]
One static checker complaint (https://github.com/cilium/cilium/pull/25183#issuecomment-1527379993) that is ok to ignore imo. The `e2e` workflow is marked as still expected, but that's just because when the PR was opened this was still called `ci-datapath` (which is green).

So `Ready-to-merge` (cc @youngnick :pray:)

**Pull request merged**
