### PR TITLE
bpf: Remove unconditional context pull on revalidate_data()

### PR DESCRIPTION
**Pull request by qmonnet**
We used to require pulling the context (skb) unconditionally when revalidating data, as a workaround for some of the verifier's limitations. With commit 847014aa62f9 ("bpf: Avoid 32bit assignment of packet pointer"), we changed the way we access to the context, and we should now be able to discard this workaround.

To some extent, this reverts commit fdca23e2b23f ("bpf: fix verifier error due to repulling of skb->data/end"), although the code has changed quite a lot since then so the revert is not straightforwards.

### CODE REVIEW

**Comment by julianwiedmann** [comment]
:wave: please wait for https://github.com/cilium/cilium/pull/25159 to land

**Comment by qmonnet** [comment]
> wave please wait for #25159 to land

No problem. My PR doesn't look correct anyway, unit tests are not passing.

**Comment by qmonnet** [comment]
Not stale, just lower prio.

**Pull request closed without merging**
