### PR TITLE
Update k8s test versions

### PR DESCRIPTION
**Pull request by aanm**
v1.10.0-beta.0 -> v1.10.0-beta.1

Signed-off-by: André Martins <andre@cilium.io>

Copy of #https://github.com/cilium/cilium/pull/2978 due jenkins misbehavior

### CODE REVIEW

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-missed-k8s

**Pull request closed without merging**
