### PR TITLE
v1.7 backport 2020-04-29 bpf

### PR DESCRIPTION
**Pull request by jrfastab**
* #10926 -- bpf: Preserve source identity for hairpin via stack (@tgraf)
* #10928 -- datapath/iptables: Masquerade hairpin traffic that traversed the stack

PR #10926 is completely reworked and converted to asm to enable old clang-7 compiler. From #10928 we only apply last remaining test commit. Without the backport of 10926 we were failing previous backports PR #11109 so it was moved here.

```upstream-prs
$ for pr in 10926 10928; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by joestringer** [comment]
```

**Comment by jrfastab** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]
lgtm

**Comment by jrfastab** [comment]
never-tell-me-the-odds

**Comment by jrfastab** [comment]
never-tell-me-the-odds

**Review by tgraf — APPROVED** [review]

**Comment by jrfastab** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
it seems the tests failures are related with changes:
```
	 2097       Enabled            Enabled           5          reserved:init                                     f00d::a0a:0:0:33de   10.10.0.169   ready   
	 3004       Disabled           Disabled          4          reserved:health                                   f00d::a0a:0:0:4dd7   10.10.0.14    ready   
	 3296       Enabled            Enabled           5          reserved:init                                     f00d::a0a:0:0:b37d   10.10.0.237   ready   
```

**Comment by jrfastab** [comment]
@tgraf any guesses on what we might be missing here. Did a quick scan of the git log and didn't see much that was promising in the ./bpf side.

**Review by joestringer — APPROVED** [review]

**Comment by jrfastab** [comment]
never-tell-me-the-odds

**Comment by joestringer** [comment]
Upstream k8s build timed out fetching box:
https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/2091/execution/node/33/log/

**Comment by joestringer** [comment]
test-upstream-k8s

**Comment by jrfastab** [comment]
test-upstream-k8s

**Comment by jrfastab** [comment]
`[KAn error occurred while downloading the remote file. The error`

**Comment by jrfastab** [comment]
test-upstream-k8s

**Pull request merged**
