### PR TITLE
v1.12 Backports 2023-03-06

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
v1.12 backports 2023-03-06

 - [ ] #23605 -- Fix operator crash race condition for CES identity map concurrent read/write (@dlapcevic)
 - [x] #24057 -- bugtool: Add ingress/egress tc filter dump (@joestringer)
 - [x] #24055 -- docs: Document CONFIG_PERF_EVENTS requirement (@joestringer)
 - [x] #24106 -- bpf/Makefile: Cover VTEP in compile tests (@pchaigno)
 - [ ] #24009 -- cni: add option to keep CNI configuration file on agent shutdown (@squeed)
 - [x] #24156 -- pkg/k8s: set the ciliumNodeStore as nil when connecting to KVStore (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 23605 24057 24055 24106 24009 24156; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
/test-backport-1.12

**Review by pchaigno — APPROVED** [review]
My PR looks good to me. Thanks!

**Review by aanm — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
/test-1.20-4.9

**Comment by YutaroHayakawa** [comment]
/test-backport-1.12

**Comment by YutaroHayakawa** [comment]
Multicluster: https://github.com/cilium/cilium/issues/21655
k8s-1.16-kernel-4.9: https://github.com/cilium/cilium/issues/22739
k8s-1.22-kernel-4.9: https://github.com/cilium/cilium/issues/22749

**Comment by YutaroHayakawa** [comment]
/ci-multicluster-1.12

**Comment by YutaroHayakawa** [comment]
/test-1.16-4.9

**Comment by YutaroHayakawa** [comment]
/test-1.22-4.9

**Pull request merged**
