### PR TITLE
test: Update Istio integration to release 1.5.0

### PR DESCRIPTION
**Pull request by jrajahalme**
```release-note
Istio integration has been updated to release 1.5.0.
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10564)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
LGTM, will you change the docker image tag from `1.5.0-test` to `1.5.0` once this is passing CI?

**Comment by jrajahalme** [comment]
@joe image tags changed :-)

**Comment by jrajahalme** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Pull request merged**
