### PR TITLE
daemon: call NodeCleanNeighbors before apiserver connection

### PR DESCRIPTION
**Pull request by waynr**

### CODE REVIEW

**Comment by jibi** [comment]
Hi @waynr :wave: could you add some context on the commit message on why this is needed/what you are trying to solve? (Also the commit needs the `Signed-off-by` tag)

**Review by brb — CHANGES_REQUESTED** [review]
We cannot just clean up the entries (otherwise, some connections will fail due to FIB lookup failures until the entries have been restored). What we need to do is to arping existing PERM entries from the stored device.

**Comment by waynr** [comment]
> Hi @waynr wave could you add some context on the commit message on why this is needed/what you are trying to solve? (Also the commit needs the Signed-off-by tag)

Yeah, for sure -- I actually meant to abort opening the PR (was using `hub pull-request` to create it) but seem to have accidentally proceeded anyway. I'm still working through fallout from this bug in the product I work on but once that's wrapped up I'll focus on getting this PR into an acceptable state.

> We cannot just clean up the entries (otherwise, some connections will fail due to FIB lookup failures until the entries have been restored).

Just to be clear -- is the problem you are pointing to with this feedback temporary and will be addressed by either normal dynamic ARP requests or by Cilium's arping behaviors? Or could this lead to more permanent connection problems? I'm asking because I am preparing to use the patch in the state shown in a patch version of the product I work on so that we can stop breaking customer clusters where we are using Cilium 1.10. I have tested the patch using various ways I have of reproducing the problem (eg. by running master node replacements several times in a row or by explicitly poisoning the arp cache and killing the cilium container so that it goes through its init sequence again) and it seems to work fine for me.

Which isn't to say that don't think you are right about the change that needs to be made to this PR, only that I'm looking for clarity about what other kinds of problems I should expect that I haven't been testing for.

> What we need to do is to arping existing PERM entries from the stored device.

Happy to work that into this PR. If you have any pointers for where to start I would appreciate them, otherwise I'll just dig around a bit more to figure it out.

**Comment by brb** [comment]
Superseded by https://github.com/cilium/cilium/pull/17713

**Pull request closed without merging**
