### PR TITLE
v1.10 backports 2021-06-22: test: Spring cleaning of K8sServicesTest

### PR DESCRIPTION
**Pull request by brb**
v1.10 backports 2021-06-22

 * #16470 -- test: Spring cleaning of K8sServicesTest (@brb)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16470; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by brb** [comment]
test-backport-1.10

**Comment by brb** [comment]
test-1.21-4.9

**Comment by pchaigno** [comment]
This PR needs a rebase given all backports PRs should be up-to-date with their branch before being merged.

**Comment by brb** [comment]
test-backport-1.10

**Comment by joestringer** [comment]
If this is painful to backport to 1.10, then maybe the cost outweighs the potential benefits for spending the effort on this.

If it's low effort and improves test reliability then I'd love to make 1.10 tree more stable with this. But there's also risks associated with the changes (eg unexpected impact on overall CI runs on the older branch + potentially introducing instability due to the churn), and also time investment to get the backports into a good shape.

**Comment by brb** [comment]
@joestringer I just need to figure out which merge conflict caused compilation problems. As the suite doesn't differ a lot in v1.10, I should be relatively straightforward to backport.

**Comment by brb** [comment]
test-backport-1.10

**Review by jibi — APPROVED** [review]

**Pull request merged**
