### PR TITLE
Prepare for 1.0.0-rc7 release

### PR DESCRIPTION
**Pull request by tgraf**

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
I think we need #3054 too as well in this.

**Comment by tgraf** [comment]
> I think we need #3054 too as well in this.

The PR didn't have the release note label set. I'll add it manually after the tests have passed

**Comment by ianvernon** [comment]
@tgraf OK, sorry for missing it :(

**Pull request merged**
