### PR TITLE
prog_test: Fix build breakage

### PR DESCRIPTION
**Pull request by joestringer**
Commit 845a062c0fdf ("monitor: Remove package-level link monitor") broke
this test by refactoring the monitor function signature. Fix it by
overhauling this code to match the new usage model.

Reported-by: Timo Beckers <timo@isovalent.com>

### CODE REVIEW

**Review by aditighag — APPROVED** [review]
How did this sneak through in the original PR? 🤔

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
> How did this sneak through in the original PR? thinking

Because the check did not run I believe: https://github.com/cilium/cilium/actions/runs/1747568015. We should fix that in the BPF check workflow.

**Comment by joestringer** [comment]
BPF checks now passed: https://github.com/cilium/cilium/runs/4986956392?check_suite_focus=true

I don't believe that this code is executed by the ginkgo CI runs, so should not need to trigger the rest of that. The only failure is a non-required false positive from CodeQL which is a known consistent failure in the tree at this time.

Relevant codeowners have provided feedback and this is should not be at all controversial, just getting the master branch back into a good state. Good to merge.

**Comment by joestringer** [comment]
Thanks for the quick reviews @aditighag , @pchaigno !

**Pull request merged**
