### PR TITLE
CI: remove bash tests 

### PR DESCRIPTION
**Pull request by ianvernon**
Since #1841 is closed and all blocking issues in #1839 are done, we can now remove the `tests` directory and the associated bash-script-based Jenkinsfile. 

Signed-off by: Ian Vernon <ian@cilium.io>

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by tgraf** [comment]
So much pain forever stored in git history

**Comment by aanm** [comment]
I thought we plan on running the bash tests nightly

**Comment by ianvernon** [comment]
> I thought we plan on running the bash tests nightly

@aanm  I was thinking about this, and I don't really see the utility in doing so. A lot of the tests haven't been ran in a while, and we already have trust established in the Ginkgo framework. IMO we should focus on stabilizing the nightly tests we have, as they have been unstable, as opposed to adding something which might not work due to lack of maintenance and take up more cycles on Jenkins. The second the bash tests are broken due to a PR which doesn't fix them due to them being not maintained, they lose all utility.

**Comment by ianvernon** [comment]
test-me-please

**Comment by aanm** [comment]
@ianvernon sorry but I disagree, we have decided that we should try running them once and keep the ones that are essential to the core functionality while let them running in the nightly for a couple weeks. The ginkgo tests lost my trust when they didn't fail in this PR https://github.com/cilium/cilium/pull/2804#issuecomment-365780915 where they should have failed

**Comment by ianvernon** [comment]
@aanm which tests are essential to core functionality that you want to keep running?

Edit: furthermore, what are the requirements that we are able to remove the bash tests from nightly tests? I think it's better if out of the tests you specify, that we do some final audit to ensure that they are properly ported to Ginkgo. My concern of what happens when the tests are out-of-date was not addressed either - I think we have to take the leap of faith some time or another, and better now than never.

**Comment by aanm** [comment]
We will not keep the bash test forever. Let's just keep the ones that don't fail now for a couple weeks in the nightly. And checking if they fail because they were not maintained or it's an actual bug

**Review by eloycoto — APPROVED** [review]

**Comment by ianvernon** [comment]
@aanm I've created https://github.com/cilium/cilium/issues/2967 to track the moving of running the tests to nightly builds

**Comment by ianvernon** [comment]
Closing this; it has become stale. Due to lack of response to needed information in #2967 , I closed #2967 . Will reopen another PR with removal of all bash tests soon.

**Pull request closed without merging**
