### PR TITLE
v1.8 backports 2020-07-21

### PR DESCRIPTION
**Pull request by pchaigno**
* #12478 -- Fix RuntimeKVStoreTest flake (@pchaigno)
 * #12515 -- .travis:fix up TestShuffle failure on Arm64 (@Jianlin-lv)
 * #12206 -- lb: Use more neutral terminology (@brb)
 * #12482 -- policy: Enable ingress CIDR-dependent L3 policy (FromCIDR + ToPorts) (@christarazi)
 * #12510 -- Enable modification of config. for endpoints with reserved labels (@pchaigno)
 * #12525 -- Clarify egress policy rule documentation (@joestringer)
 * #12345 -- Host firewall fixes (@pchaigno)
 * #12504 -- .travis:fix up PodCIDRSuite failure on Arm64 (@Jianlin-lv)
 * #12553 -- etcd: Fix session renewal controllers (@tgraf)
 * #12572 -- hubble/relay: expose options to configure flows sorting (@Rolinh)
 * #12573 -- k8s,node: Fix init of labels with Operator IPAM (@pchaigno)
 * #12537 -- Getting started guide for the host firewall (@pchaigno)
 * #12587 -- Fix etcd failure behavior when user or client context ends (@tgraf)
 * #12595 -- k8s/watchers: stop init of local endpoint in success case (@aanm)
 * #12597 -- doc: Remove reference to (KNP) policy limitations (@christarazi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12478 12515 12206 12482 12510 12525 12345 12504 12553 12572 12573 12537 12587 12595 12597; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by pchaigno** [comment]
test-backport-1.8

**Review by rolinh — APPROVED** [review]

**Review by brb — APPROVED** [review]
LGTM for my changes.

**Review by aanm — APPROVED** [review]
LGTM for my commit

**Comment by pchaigno** [comment]
Runtime-4.9 test hit known flake #12042 on privileged unit tests. I've successfully run the privileged unit tests locally, so I think this is ready to merge given it already has several reviews.

**Pull request merged**
