### PR TITLE
v1.12 Backports 2023-01-30

### PR DESCRIPTION
**Pull request by qmonnet**
* [x] #23286 -- egressgw: ensure stale IP routes/rules are deleted (@jibi)
 * [x] #23241 -- bpf: Remove link scope of `cilium_host`'s IPv4 address (@pchaigno)
 * [ ] #23159 -- docs: Disable exclusive lock when chaining with aws-cni (@jaygridley)
   * Minor conflict
 * [x] #22995 -- certloader flake fixes (@kaworu)
 * [x] #23339 -- cilium: Fix missing error log dump from compilation (@borkmann)
   * Minor conflict
 * [x] #23338 -- test: print log messages that need to be investigated (@aanm)
 * [x] #23334 -- tests: add exception for etcd error (@aanm)
   * Minor conflict
 * [x] #23377 -- proxy: Fix deadlock in error path of CreateOrUpdateRedirect (@gandro)
   * Minor conflict
 * [x] #23406 -- .github/workflows: fix external contribution detection (@aanm)
   * Minor conflict
 * [x] #23424 -- .github/workflows: fix typo in organization parameter (@aanm)
 * [x] #23431 -- .github: set do not use provenance from docker buildx (@aanm)
   * Minor conflict
 * [x] #23437 -- .github/workflows: set right secret name (@aanm)
   * Minor conflict

PRs skipped due conflicts:

 * #23202 -- Introduce node IDs (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 23286 23241 23159 22995 23339 23338 23334 23377 23406 23424 23431 23437; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
$ make add-label BRANCH=v1.12 ISSUES=23286,23241,23159,22995,23339,23338,23334,23377,23406,23424,23431,23437
```

### CODE REVIEW

**Review by nbusseneau — APPROVED** [review]

**Comment by qmonnet** [comment]
Bad conflict resolution on https://github.com/cilium/cilium/pull/23339 -- should now be addressed.

**Review by jibi — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Comment by qmonnet** [comment]
/test-1.17-4.9

**Review by aanm — APPROVED** [review]
My changes look good. Thank you for taking care of the conflicts!

**Review by kaworu — APPROVED** [review]
Thanks @qmonnet LGTM for my commits

**Review by gandro — APPROVED** [review]
Thanks for resolving the conflicts, my commit looks good!

**Review by borkmann — APPROVED** [review]

**Pull request merged**
