### PR TITLE
envoy: Make policy direction configurable for Istio

### PR DESCRIPTION
**Pull request by jrajahalme**
Add an optional boolean "is_ingress" configuration parameter to the
cilium.l7policy filter. If set the ingress/egress direction will be
determined using this, otherwise the direction is derived from the
metadata passed from the listener filter.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]

**Comment by rlenglet** [comment]
FYI, I'm cherry-picking this into https://github.com/cilium/cilium/pull/3035 as well.

**Review by tgraf — CHANGES_REQUESTED** [review]
Placeholder as Romain is testing. Don't merge yet.

**Comment by tgraf** [comment]
Obsoleted by #3035

**Pull request closed without merging**
