### PR TITLE
daemon: split up bootstrapping code into smaller functions, logically group specific code into smaller files

### PR DESCRIPTION
**Pull request by ianvernon**
Having smaller files + functions makes it easier to figure out how parts of the daemon are logically grouped together. This will make the code easier to change and read as time goes on.

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8255)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Hit the `not-ready` endpoints issue ( #8234 ): https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12902/testReport/junit/Suite-k8s-1/10/K8sChaosTest_Restart_with_long_lived_connections_L3_L4_policies_still_work_while_Cilium_is_restarted/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Review by jrfastab — APPROVED** [review]
LGTM its going to hurt backporting but reduces size so go for it IMO.

**Comment by ianvernon** [comment]
CI failure is a known issue: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12928/testReport/junit/Suite-k8s-1/14/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/ ( #8234 )

**Review by aanm — APPROVED** [review]

**Review by brb — APPROVED** [review]

**Comment by ianvernon** [comment]
Merging, the CI failure is a known quantity and is unrelated to this PR.

**Pull request merged**
