### PR TITLE
Update Go to 1.16.6

### PR DESCRIPTION
**Pull request by tklauser**
First commit remove an unnecessary step from the `update-golang-image.sh` script, second commit updates Go to 1.16.6 and updates to new Cilium images built with that version.

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
* k8s-1.16-kernel-netnext failed with #16399: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/1080/
* k8s-1.21-kernel-4.9 failed with #16879: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/1059/

**Review by nbusseneau — APPROVED** [review]
Code changes LGTM.

**Review by kkourt — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
Depending on whether this PR or #16915 gets merged first, the respective other PR needs to update its `cilium-builder` image again.

**Comment by tklauser** [comment]
test-1.16-netnext

**Review by brb — APPROVED** [review]

**Comment by tklauser** [comment]
Go 1.16.7 was released while I was on PTO. I'll open a new PR updating to that version.

**Pull request closed without merging**
