### PR TITLE
Add documentation about kvstoremesh

### PR DESCRIPTION
**Pull request by giorio94**
This PR extends the clustermesh documentation with information about the new Cilium CLI helm mode, and kvstoremesh. The PR is ready for review, but marked as blocked because the Cilium CLI has not yet been extended with the new `--enable-kvstoremesh` flag.

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]
Looks good, thank you!

**Review by YutaroHayakawa — APPROVED** [review]
LGTM 👍

**Review by asauber — APPROVED** [review]
Looks great

**Comment by giorio94** [comment]
Last force push just added an additional note that kvstoremesh is a beta feature close to the instructions to enable it:

```diff
-  You can additionally opt in to :ref:`kvstoremesh` when enabling Cluster Mesh.
-  Make sure to configure the Cilium CLI in *helm* mode and run:
+  You can additionally opt in to :ref:`kvstoremesh` (beta feature) when enabling
+  Cluster Mesh. Make sure to configure the Cilium CLI in *helm* mode and run:
```

**Review by marseel — APPROVED** [review]
Thanks for adding it. lgtm

**Comment by giorio94** [comment]
I've bumped the CLI version mentioned in the clustermesh docs to v0.14.8, as it will be the one supporting all clustermesh operations using helm, as well as including the `--enable-kvstoremesh` flag. I'm going to remove the `blocked` label from this PR once that gets released.

**Comment by giorio94** [comment]
Cilium CLI v0.14.8 got released. Marking as ready to merge

**Pull request merged**
