### PR TITLE
docs: Updated contributing_guide documentation files

### PR DESCRIPTION
**Pull request by AdityaK60**
Grammatically updated the contributing_guide document.

Signed-off-by: Aditya Kumar [aditya.kumar60@infosys.com](mailto:aditya.kumar60@infosys.com)

### CODE REVIEW

**Review by xmulligan — APPROVED** [review]

**Comment by bimmlerd** [comment]
Could you squash the two commits and, while at it, change the commit msg title to something a bit more descriptive? Thank you.

**Comment by AdityaK60** [comment]
> Could you squash the two commits and, while at it, change the commit msg title to something a bit more descriptive? Thank you.

I changed the commit message and squashed the commits as one.

**Review by ghost — APPROVED** [review]

**Comment by AdityaK60** [comment]
Hi,
How to get this branch merged

**Review by aanm — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Pull request merged**
