### PR TITLE
Improve dev-doctor version detection and error reporting

### PR DESCRIPTION
**Pull request by joestringer**
Improve some dev-doctor debugging output and standardize the version check to use the same regex to match versions for various different commands.

Tested locally using `make dev-doctor`, works well for my environment.

### CODE REVIEW

**Comment by rolinh** [comment]
> This PR is mainly about adding details for `protoc`, which is a requirement to run `make generate-k8s-api`.

Sorry, my comment is a bit unrelated to the PR but based on the above I wanted to ask: why do we require protoc to be installed locally? In my experience, different protoc versions may generate different code. To address this issue when generating the Hubble API, we use a the cilium-builder image that includes protoc (and a set of protoc plugins). Couldn't such approach be used for `make generate-k8s-api`?

**Comment by joestringer** [comment]
Alright, I spun up https://github.com/cilium/cilium/pull/32063 as a replacement for that part. The other cleanups in this PR could be independently useful though, so I'll re-mark this for review just as a cleanup PR.

**Review by rolinh — APPROVED** [review]

**Review by aditighag — APPROVED** [review]

**Pull request merged**
