### PR TITLE
Testing #10477 with newer Clang

### PR DESCRIPTION
**Pull request by pchaigno**

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-focus K8sKafkaPolicyTest.*

**Comment by borkmann** [comment]
> test-me-please
> 
> Failures:
> `Suite-k8s-1.11.K8sKafkaPolicyTest Kafka Policy Tests KafkaPolicies`
> `Suite-k8s-1.18.K8sKafkaPolicyTest Kafka Policy Tests KafkaPolicies`

Seems to be unrelated, I've seen this in a different PR as well.

**Comment by pchaigno** [comment]
Okay, thanks. Looks like we got rid of complexity issues for now then. I'll respin the tests once `badLogMessages` is fixed, but it's probably okay to start rebasing blocked PRs.

**Comment by borkmann** [comment]
> Okay, thanks. Looks like we got rid of complexity issues for now then. I'll respin the tests once `badLogMessages` is fixed, but it's probably okay to start rebasing blocked PRs.

Yes, other than that this passed the k8s-1.{11,18} test cases now, so good to push rebased PRs that were blocked.

**Comment by borkmann** [comment]
Closing since original PR merged. Thanks for your help @pchaigno!

**Pull request closed without merging**
