### PR TITLE
v1.11 Backports 2023-05-19

### PR DESCRIPTION
**Pull request by jibi**
* [x] #25323 (@tommyp1ckles)
 * [x] #25352 (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 25323 25352; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
make add-labels BRANCH=v1.11 ISSUES=25323,25352
```

### CODE REVIEW

**Comment by jibi** [comment]
/test-backport-1.11

**Review by pchaigno — APPROVED** [review]
First PR looks good.

**Comment by pchaigno** [comment]
/test-backport-1.11

**Comment by pchaigno** [comment]
/test-backport-1.11

**Comment by pchaigno** [comment]
/test-backport-1.11

**Comment by jibi** [comment]
/test-backport-1.11

**Review by jrajahalme — APPROVED** [review]

**Comment by jrajahalme** [comment]
/test-backport-1.11

**Comment by jrajahalme** [comment]
/test-1.20-4.9

**Comment by jibi** [comment]
/test-backport-1.11

**Comment by jibi** [comment]
/test-1.16-netnext

**Comment by jibi** [comment]
/test-1.17-4.9

**Comment by jibi** [comment]
`installation-and-connectivity` is stuck as `Expected` (probably because of the recent CI changes?) so marking as ready

**Pull request merged**
