### PR TITLE
Update external docker images

### PR DESCRIPTION
**Pull request by aanm**
This commit updates hubble-ui envoy proxy to v1.20.2 and clustermesh's etcd to v3.5.2

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
:shipit:

**Comment by aanm** [comment]
All tests were successful. Unit test failed because of documentation. This is the diff that was applied:
```diff
diff --git a/Documentation/helm-values.rst b/Documentation/helm-values.rst
index 9bae795111..a18048766f 100644
--- a/Documentation/helm-values.rst
+++ b/Documentation/helm-values.rst
@@ -152,7 +152,7 @@
    * - clustermesh.apiserver.etcd.image
      - Clustermesh API server etcd image.
      - object
-     - ``{"override":null,"pullPolicy":"Always","repository":"quay.io/coreos/etcd","tag":"v3.4.13"}``
+     - ``{"override":null,"pullPolicy":"Always","repository":"quay.io/coreos/etcd","tag":"v3.5.2@sha256:70fe70b6cdaea99fa9e99d3a16483954eb084c3b32a2475abea4e709a793636c"}``
    * - clustermesh.apiserver.extraEnv
      - Additional clustermesh-apiserver environment variables.
      - list
@@ -932,7 +932,7 @@
    * - hubble.ui.proxy.image
      - Hubble-ui ingress proxy image.
      - object
-     - ``{"override":null,"pullPolicy":"Always","repository":"docker.io/envoyproxy/envoy","tag":"v1.18.4@sha256:e5c2bb2870d0e59ce917a5100311813b4ede96ce4eb0c6bfa879e3fbe3e83935"}``
+     - ``{"override":null,"pullPolicy":"Always","repository":"docker.io/envoyproxy/envoy","tag":"v1.20.2@sha256:eb7d88d5186648049f0a80062120bd45e7557bdff3f6a30e1fc92cbb50916868"}``
    * - hubble.ui.proxy.resources
      - Resource requests and limits for the 'proxy' container of the 'hubble-ui' deployment.
      - object
```

**Review by cure53 — COMMENTED** [review]
:heavy_check_mark: LGTM

**Pull request merged**
