### PR TITLE
v1.14 Backports 2024-03-05

### PR DESCRIPTION
**Pull request by pippolo84**
* [x] #31061 (@sayboras)
 * [x] #31026 (@jrajahalme)
 * [x] #31025 (@julianwiedmann)
 * [x] #30462 (@saintdle)
 * [x] #31037 (@nathanjsweet)
 * [x] #30966 (@pchaigno)

Skipped:

 * [ ] #30766 (@pippolo84)
   - iptables manager has not been modularized in v1.14, the CNI config manager cannot be injected through hive

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31061 31026 31025 30462 31037 30966
```

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks Fabio!

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commit.

**Comment by pippolo84** [comment]
/test-backport-1.14

**Review by nathanjsweet — APPROVED** [review]
My changes LGTM.

**Review by joestringer — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
