### PR TITLE
Disable failing encryption connectivity tests on GKE 

### PR DESCRIPTION
**Pull request by brlbil**
Encryption connectivity tests are failing on the new version of GKE clusters.
Disable encryption tests until issue #22808 is fixed.

### CODE REVIEW

**Comment by brlbil** [comment]
I have tried to only disable a minimum amount of tests to make encrypted compliance tests pass.
But it did not work so I disabled the steps altogether. 

Passed tests:
https://github.com/cilium/cilium/actions/runs/3997396611/jobs/6858680131
https://github.com/cilium/cilium/actions/runs/3997396594/jobs/6858680297

**Review by aanm — APPROVED** [review]

**Review by pchaigno — CHANGES_REQUESTED** [review]
I'm not strictly against this but wondering a bit about the tradeoff here: couldn't we have pinned the GKE version instead of removing IPsec+GKE coverage?

**Comment by brlbil** [comment]
@pchaigno The version pinned before but the pinned GKE version no longer exists so this results in all workflow failing.
This way at least we run the first part of the conformance test. Please see the issue here #23153

**Review by pchaigno — APPROVED** [review]
Got it. Thanks for the context!

**Review by nebril — APPROVED** [review]

**Pull request merged**
