### PR TITLE
bgpv1: ExternalIP  advertisement with BGP Control Plane

### LINKED ISSUE #29990: CFP: BGP Control Plane - add ExternalIPs support
## Cilium Feature Proposal

We are evaluating running Cilium with BGP Control Plane in baremetal environment. In current setup, a BGP controller (runs on every node per Daemonset) advertises all services that have `.spec.externalIPs` configured.

In case of cilium, PodCIDR announcement works out of the box but no services are announced with following policy:

```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: bgp-peering-policy-foo
spec:
 virtualRouters:
 - localASN: 65000
   exportPodCIDR: true
   serviceSelector:
      matchExpressions:
         - key: somekey
           operator: NotIn
           values: ["never-used-value"]
   neighbors:
    - peerAddress: "10.1.1.1/32"
      peerASN: 65001
      eBGPMultihopTTL: 10
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
```

As far as I understand, currently Cilium would only advertise services of type `LoadBalancer` AND [if the IP is set](https://github.com/cilium/cilium/blob/main/pkg/bgpv1/manager/reconciler/lb_service.go#L315-L318) in `.Status.LoadBalancer.Ingress.IP`.

In our environment Service ExternalIPs are part of application charts, there is no controller to set the status:
```
apiVersion: v1
kind: Service
metadata:
  name: foo-nginx-controller
  namespace: kube-system
spec:
  clusterIP: 100.127.1.2
  clusterIPs:
  - 100.127.1.2
  externalIPs:
  - 10.2.2.2
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    nodePort: 32111
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 31112
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

Include any specific requirements you need

Would you consider advertising `.spec.ExternalIPs` in services of type `LoadBalancer` and `NodePort`?

Since there already is an option [enable-external-ips](https://github.com/cilium/cilium/blob/main/pkg/option/config.go#L139-L140), maybe this feature would be a good addition to it?

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Fixes: #29990

```release-note
Add support for ExternalIP service advertisement with BGP Control Plane
```

### CODE REVIEW

**Review by rastislavs — APPROVED** [review]
LGTM, thank you!

**Review by YutaroHayakawa — CHANGES_REQUESTED** [review]
Very nice work, thanks! I forgot to mention this in ClusterIP PR, but you need to bump the patch version here when you change the CRD schema.

https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/register.go#L18

**Comment by chaunceyjiang** [comment]
> Very nice work, thanks! I forgot to mention this in ClusterIP PR, but you need to bump the patch version here when you change the CRD schema.

So should I change it to `1.29.3`? @YutaroHayakawa

**Review by YutaroHayakawa — APPROVED** [review]
Now looks good! Thanks! Please don't forget to write a document together with ClusterIP's one.

https://github.com/cilium/cilium/pull/30963#issuecomment-1985203259

Same caveats applied for ExternalIP + KPR.

**Comment by chaunceyjiang** [comment]
> Please don't forget to write a document together with ClusterIP's one.
> Same caveats applied for ExternalIP + KPR.

Ok. I'm currently writing documentation for these two features.

**Comment by chaunceyjiang** [comment]
CC @youngnick PTAL.

**Review by youngnick — APPROVED** [review]

**Pull request merged**
