### PR TITLE
Move k8s_watcher.go to pkg/k8s/watchers

### PR DESCRIPTION
**Pull request by aanm**
~**NOTE**: :warning:  This PR depends on https://github.com/cilium/cilium/pull/9400 :warning:~

Sorry but I couldn't split the first commit in smaller commits.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9434)

### CODE REVIEW

**Review by ianvernon — APPROVED** [review]
😍😍😍😍

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
unit tests were executed here https://github.com/cilium/cilium/pull/9468/checks?check_run_id=268448218

**Review by brb — APPROVED** [review]
LGTM, just one nit - I would use singular nouns for the watcher file names.

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
