### PR TITLE
gateway-api: Un-set externalTrafficPolicy on LB service for host network

### PR DESCRIPTION
**Pull request by otaconix**
As explained in the commit message, support was recently added for setting an `externalTrafficPolicy` on the load balancer `Service`s generated for `Gateway`s.

This broke those setups where `hostNetworkEnabled==true`, as `externalTrafficPolicy` is only allowed on _externally-facing_ services, which services of type `ClusterIP` are _not_.

This commit addresses that.

### CODE REVIEW

**Comment by otaconix** [comment]
In addition to what's already here, I'm wondering if it'd make sense to log a warning somewhere when `hostNetworkEnabled == true && externalTrafficPolicy != ""`, and document the issue?

**Comment by ti-mo** [comment]
@sayboras Ping, this is passing CI. Also see @otaconix's question in https://github.com/cilium/cilium/pull/33101#issuecomment-2163707385.

**Review by sayboras — APPROVED** [review]
Thanks

**Review by youngnick — CHANGES_REQUESTED** [review]
@otaconix, sorry to take a while to get to this, but I agree that we should make a couple of changes:
* log an warning when we will be ignoring the value of ExternalTrafficPolicy - we can do this in `operator/pkg/gateway-api/cell.go`, in the `initGatewayAPIController()` function, when we validate the values. We could probably skip the validation in the case that `hostNetworkEnabled` is `true`, and just log a warning then to say "Ignoring ExternalTrafficPolicy because hostNetwork is enabled" or something.
* We should also update the docs for Gateway API `externalTraffficPolicy` setting in Helm ( in `install/kubernetes/cilium/values.yaml.tmpl` about line 851) to indicate that this value will be ignored if `hostNetworkEnabled == true`.

**Comment by youngnick** [comment]
@otaconix, if you won't have time to make these changes this week, let us know and we'll look at merging as-is and having someone else do the followup.

**Comment by otaconix** [comment]
@youngnick I added that warning message, skip validation when host networking is enabled, and added a note for the `apiGateway.externalTrafficPolicy` Helm value. Maybe the wording could be better. If so, feel free to change it!

**Review by squeed — APPROVED** [review]
Helm changes look good.

**Review by youngnick — APPROVED** [review]
Changes look great, thanks @otaconix !

**Comment by otaconix** [comment]
I see some conformance tests failing. Is there anything I can do about that? I don't expect my changes to have caused those, but I could be wrong. 

Is there anything else I could/should do to get this merged?

**Comment by tommyp1ckles** [comment]
@otaconix Looking at the test failures, they appear likely unrelated to your changes, going to rerun to see if they're failing consistently.

**Pull request merged**
