### PR TITLE
daemon: remove host-allows-world option

### PR DESCRIPTION
**Pull request by ianvernon**
This is scheduled to be removed in v1.5, so remove it.

Fixes: #6319

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7614)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
It's beautiful :sob:

**Review by aanm — CHANGES_REQUESTED** [review]
Can you add a warning in the upgrade section?

**Review by nebril — APPROVED** [review]

**Review by tgraf — APPROVED** [review]
LGTM assuming that the removal is mentioned in the upgrade docs with the other removed options.

**Comment by ianvernon** [comment]
@aanm it's already there: https://github.com/cilium/cilium/commit/d8ba3c80f20f0249b9f9c0faf5f009ea9083eddc

**Comment by ianvernon** [comment]
test-me-please

**Comment by tgraf** [comment]
@ianvernon Looks good to go, only needs a rebase

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
@aanm PTAL

**Review by aanm — APPROVED** [review]

**Pull request merged**
