### PR TITLE
test: Update Istio integration to release 1.5.1

### PR DESCRIPTION
**Pull request by jrajahalme**
Fix for GKE/COS is included in the cilium/istio_proxy:1.5.1 image, so re-enable istio test in GKE/COS.

```release-note
Istio integration is updated to release 1.5.1, with backported fix for GKE/COS.
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Docs side LGTM.

**Comment by raybejjani** [comment]
test-gke K8sIstio.*

**Comment by raybejjani** [comment]
test-gke K8sIstio.*

**Comment by jrajahalme** [comment]
test-gke K8sIstio.*

**Comment by jrajahalme** [comment]
test-gke K8sIstio.*

**Comment by jrajahalme** [comment]
test-gke K8sIstio.*

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-gke K8sIstio.*

**Comment by jrajahalme** [comment]
Tests passed, replaced tags "1.5.1-test" with "1.5.1" for merging.

**Comment by jrajahalme** [comment]
test-gke K8sIstio.*

**Comment by jrajahalme** [comment]
test-gke K8sIstio.*

**Review by aanm — APPROVED** [review]
LGTM but waiting for @cilium/ci to take a look as well

**Review by nebril — APPROVED** [review]

**Pull request merged**
