### PR TITLE
vendor: update wireguard library

### PR DESCRIPTION
**Pull request by aanm**
go.mod is currently using a revoked wireguard version. To fix this we
will update to the latest wireguard commit.
More info: https://github.com/WireGuard/wgctrl-go/issues/102

Reported-by: Vlad Ungureanu <vladu@palantir.com>
Suggested-by: Nicolas Busseneau <nicolas@isovalent.com>
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Review by ungureanuvladvictor — APPROVED** [review]

**Comment by aanm** [comment]
test-1.16-netnext

**Comment by aanm** [comment]
test-gke

**Pull request merged**
