### PR TITLE
ubuntu-dev: bump to v164

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9466)

### CODE REVIEW

**Comment by aanm** [comment]
cc @ianvernon

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
Only failure was BPF nodeport with VXLAN: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/15503/

**Comment by ianvernon** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
