### PR TITLE
ci: fix gke cluster lock

### PR DESCRIPTION
**Pull request by nebril**

### CODE REVIEW

**Comment by nebril** [comment]
test-gke K8sDemos.*

**Review by qmonnet — APPROVED** [review]

**Comment by errordeveloper** [comment]
Ah, looks like my fault - I find `set -e`/ `set +e` toggling very hard to keep track of (surely I'm not alone), I hope we will eradicate this anti-pattern soon enough!

**Review by errordeveloper — APPROVED** [review]
Thanks a lot!

**Comment by nebril** [comment]
GKE build passed, merging this, will let people know on Slack to rebase

**Pull request merged**
