### PR TITLE
Add periodic aggregation of datapath notifications

### PR DESCRIPTION
**Pull request by joestringer**
Requires ~~#4867~~, ~~#4874~~ to reduce complexity enough to support this new functionality on Linux 4.9.17. Only the top four commits are new in this PR.

This is the next step after ~~#4828~~. It adds a new `MonitorAggregationLevel`, `Medium`. This will reduce notifications further, such that notifications will only be sent if there is new information (such as TCP flags that were not previously seen), or a packet is received and a notification has not been sent in the past five seconds. Future work may make this period more configurable.

Questions (@borkmann):
* Is the update of the ct_entry for timestamps/flags safe?

I suspect that it's just racy, so it's plausible that multiple packets received in quick succession could result in multiple notifications, and perhaps in the case of tcp flags end up un-setting a flag seen in one of the racing executions. However, I'd expect this to be fairly unlikely as the flags used during different portions of a connection should be fairly consistent, ie we won't un-set the SYN flag part way through; SYN and ACK packets are unlikely to conflict and end up unsetting the ACK flag, etc.

Update: I've added a new commit to explain the above and why it should not cause significant issues for monitor notifications.

---

Example monitor output for a standard TCP curl for a basic service (from the docker guide on docs.cilium.io) with both endpoints in Medium aggregation mode:

```
-> endpoint 28601 flow 0x41d01aa identity 54742->54742 state new ifindex lxc33fa9: 10.11.66.250:40210 -> 10.11.176.4:80 tcp SYN       
-> endpoint 44008 flow 0xbd455b43 identity 54742->54742 state reply ifindex lxc8736a: 10.11.176.4:80 -> 10.11.66.250:40210 tcp SYN, ACK
-> endpoint 28601 flow 0x41d01aa identity 54742->54742 state established ifindex lxc33fa9: 10.11.66.250:40210 -> 10.11.176.4:80 tcp ACK
-> endpoint 28601 flow 0x41d01aa identity 54742->54742 state established ifindex lxc33fa9: 10.11.66.250:40210 -> 10.11.176.4:80 tcp ACK
-> endpoint 44008 flow 0xbd455b43 identity 54742->54742 state reply ifindex lxc8736a: 10.11.176.4:80 -> 10.11.66.250:40210 tcp ACK
-> endpoint 28601 flow 0x41d01aa identity 54742->54742 state established ifindex lxc33fa9: 10.11.66.250:40210 -> 10.11.176.4:80 tcp ACK, FIN
-> endpoint 44008 flow 0xbd455b43 identity 54742->54742 state reply ifindex lxc8736a: 10.11.176.4:80 -> 10.11.66.250:40210 tcp ACK, FIN
```

Compare with aggregation mode none:

```
<- endpoint 44008 flow 0xac35ebce identity 54742->0 state new ifindex 0: 10.11.66.250:40710 -> 10.11.176.4:80 tcp SYN
-> endpoint 28601 flow 0xac35ebce identity 54742->54742 state new ifindex lxc33fa9: 10.11.66.250:40710 -> 10.11.176.4:80 tcp SYN
<- endpoint 28601 flow 0xef0d08df identity 54742->0 state new ifindex 0: 10.11.176.4:80 -> 10.11.66.250:40710 tcp SYN, ACK
-> endpoint 44008 flow 0xef0d08df identity 54742->54742 state reply ifindex lxc8736a: 10.11.176.4:80 -> 10.11.66.250:40710 tcp SYN, ACK
<- endpoint 44008 flow 0xac35ebce identity 54742->0 state new ifindex 0: 10.11.66.250:40710 -> 10.11.176.4:80 tcp ACK
-> endpoint 28601 flow 0xac35ebce identity 54742->54742 state established ifindex lxc33fa9: 10.11.66.250:40710 -> 10.11.176.4:80 tcp ACK
<- endpoint 44008 flow 0xac35ebce identity 54742->0 state new ifindex 0: 10.11.66.250:40710 -> 10.11.176.4:80 tcp ACK
-> endpoint 28601 flow 0xac35ebce identity 54742->54742 state established ifindex lxc33fa9: 10.11.66.250:40710 -> 10.11.176.4:80 tcp ACK
<- endpoint 28601 flow 0xef0d08df identity 54742->0 state new ifindex 0: 10.11.176.4:80 -> 10.11.66.250:40710 tcp ACK
-> endpoint 44008 flow 0xef0d08df identity 54742->54742 state reply ifindex lxc8736a: 10.11.176.4:80 -> 10.11.66.250:40710 tcp ACK
<- endpoint 28601 flow 0xef0d08df identity 54742->0 state new ifindex 0: 10.11.176.4:80 -> 10.11.66.250:40710 tcp ACK
-> endpoint 44008 flow 0xef0d08df identity 54742->54742 state reply ifindex lxc8736a: 10.11.176.4:80 -> 10.11.66.250:40710 tcp ACK
<- endpoint 44008 flow 0xac35ebce identity 54742->0 state new ifindex 0: 10.11.66.250:40710 -> 10.11.176.4:80 tcp ACK
-> endpoint 28601 flow 0xac35ebce identity 54742->54742 state established ifindex lxc33fa9: 10.11.66.250:40710 -> 10.11.176.4:80 tcp ACK
<- endpoint 44008 flow 0xac35ebce identity 54742->0 state new ifindex 0: 10.11.66.250:40710 -> 10.11.176.4:80 tcp ACK, FIN
-> endpoint 28601 flow 0xac35ebce identity 54742->54742 state established ifindex lxc33fa9: 10.11.66.250:40710 -> 10.11.176.4:80 tcp ACK, FIN
<- endpoint 28601 flow 0xef0d08df identity 54742->0 state new ifindex 0: 10.11.176.4:80 -> 10.11.66.250:40710 tcp ACK, FIN
-> endpoint 44008 flow 0xef0d08df identity 54742->54742 state reply ifindex lxc8736a: 10.11.176.4:80 -> 10.11.66.250:40710 tcp ACK, FIN
<- endpoint 44008 flow 0xac35ebce identity 54742->0 state new ifindex 0: 10.11.66.250:40710 -> 10.11.176.4:80 tcp ACK
-> endpoint 28601 flow 0xac35ebce identity 54742->54742 state established ifindex lxc33fa9: 10.11.66.250:40710 -> 10.11.176.4:80 tcp ACK
```

Related: #4080 

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4875)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Caveat for testing: It seems that the `MonitorAggregationLevel` can only be set from None -> any value or any value -> None. If for example you attempt to set from Low -> Medium, the API request appears to succeed but in fact it does not change the value. Just set to None first then set to the desired option value.

Will need to follow up on this separately with a fix for this in `pkg/option`.

**Comment by borkmann** [comment]
> Is the update of the ct_entry for timestamps/flags safe?

If they arrive on multiple CPUs at the same time it's not and can be racy since the update is non-atomic - the htab element has a global scope so multiple CPUs in parallel could do the lookup and write into it. It would be avoided altogether by per-cpu map or by using map-update (latter with significant cost though), or perhaps with some tricks in combination with lock_xadd() (latter being __sync_fetch_and_add()). Another option I'm wondering whether RPS/XPS might help here.

**Comment by joestringer** [comment]
If the integrity of the values themselves are kept intact (ie, set one value or the other), I am not too worried about two racing sets; Two CPUs racing this short critical section at the same time could plausibly interfere with one another, but:

* For updating the timestamp, the new timestamp will be almost the same between the two. It could result in a small number of notifications in quick succession, but this will still prevent unnecessary notifications for the next 5 seconds.

* For TCP flags, it is possible for flags to be unset by a racing CPU, however normal TCP sessions will not interleave differently flagged packets. So long as the update sets one of the racing values correctly, it should be eventually correct. Again, we could end up triggering multiple notifications but that's not the worst outcome.

Of course, if it's not too bad to come up with a proper fix for this that synchronizes more strictly, that is probably a better solution.

**Review by ianvernon — APPROVED** [review]
Approving `pkg/option` changes.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Failed due to NACK issue.

**Comment by joestringer** [comment]
test-me-please

EDIT: Saw NACK issue again. Also needs a rebase.

**Comment by joestringer** [comment]
test-me-please

EDIT: NACK issue again, also bpf.sha clash.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

Hit #4886

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Issue:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5148/testReport/k8s-1/10/K8sValidatedChaosTest_Endpoint_can_still_connect_while_Cilium_is_not_running/

Logs:
```

2018-07-20T22:45:54.549731048Z level=debug msg="Reading directory" endpointID=17748 file-path=/var/run/cilium/state/17748/lxc_config.h
2018-07-20T22:45:54.549756343Z level=debug msg="Found endpoint C header file" endpointID=17748 file-path=/var/run/cilium/state/17748/lxc_config.h
2018-07-20T22:45:54.549872004Z level=warning msg="Unable to parse the C header file" endpointID=17748 error="invalid format \"\". Should contain a single ':'" file-path=/var/run/cilium/state/17748/lxc_config.h
```

Entire endpoint file:

[lxc_config.h](https://github.com/cilium/cilium/files/2215782/lxc_config.h.txt)

It's missing the entire stored endpoint structure.

[516c42b0_K8sValidatedChaosTest_Endpoint_can_still_connect_while_Cilium_is_not_running.zip](https://github.com/cilium/cilium/files/2215781/516c42b0_K8sValidatedChaosTest_Endpoint_can_still_connect_while_Cilium_is_not_running.zip)

**Comment by joestringer** [comment]
Attempting to open a fresh PR to see if it impacts CI flakes: #4936

**Pull request closed without merging**
