### PR TITLE
Fix missed deletion events when reconnecting to/disconnecting from remote clusters (ipcache entries) 

### PR DESCRIPTION
**Pull request by giorio94**
Follow up of https://github.com/cilium/cilium/pull/25499 targeting ipcache entries synchronization. Please refer to the above PR and the commit descriptions for additional information.

Related: https://github.com/cilium/cilium/issues/24740
Related: https://github.com/cilium/cilium/pull/25499 

```release-note
Fix missed deletion events when reconnecting to/disconnecting from remote clusters (ipcache entries) 
```

### CODE REVIEW

**Comment by giorio94** [comment]
One of the Cilium Conformance E2E tests failed with https://github.com/cilium/cilium/issues/25823. Manually restarting

**Review by jrajahalme — APPROVED** [review]
I'm quite rusty on this code, but LGTM

**Pull request merged**
