### PR TITLE
doc: correct lock down network policy

### PR DESCRIPTION
**Pull request by Wouter0100**
Before it was 2 separate rules, where it was fromEntities have access OR all toPorts have access. Now it is an fromEntities AND toPorts.

Signed-off-by: Wouter van Os <wouter0100@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Comment by Wouter0100** [comment]
I will be adding the release notes.

**Review by qmonnet — CHANGES_REQUESTED** [review]
Thank you, but I think the disjunction for the rules was intentional, see the relevant commit description in https://github.com/cilium/cilium/commit/e931b3cd8a2c818332e7eb653e9f71f370f98cb3. Cc @pchaigno

**Comment by qmonnet** [comment]
> a colleague spent some hours on this

What was the issue that you faced, exactly? If you were surprised by the traffic being allowed from remote nodes and health, maybe it's the accompanying docs that we should update?

**Review by pchaigno — CHANGES_REQUESTED** [review]
Quentin is correct. That was done on purpose. We could definitely make the policy more fine-grained but that isn't the purpose here.

If you're looking for a very fine-grained example, you may want to check https://github.com/cilium/cilium/blob/master/examples/policies/host/lock-down-gke.yaml.

**Comment by Wouter0100** [comment]
Thanks for clearing things up. We expected it to allow only a minimal set of ports from `remote-node` and `health` (as described in the description: `minimum set of required ports`), but it did allow everything from `remote-node` and `health`. 

After investigation we saw that port SSH was still reachable by `world`, which we did not expect after applying this rule.

**Comment by pchaigno** [comment]
> (as described in the description: `minimum set of required ports`)

Fair enough :smile_cat: We should update the description to clarify that it also allows remote nodes and health endpoints.
This example is really meant to be a simple example you can run in any cluster without breaking stuff, hence not very fine grained.

**Comment by pchaigno** [comment]
> After investigation we saw that port SSH was still reachable by `world`, which we did not expect after applying this rule.

That seems unexpected to me as well. Do you have the corresponding policy verdict?

**Comment by Wouter0100** [comment]
> > After investigation we saw that port SSH was still reachable by `world`, which we did not expect after applying this rule.
> 
> That seems unexpected to me as well. Do you have the corresponding policy verdict?

```
Policy verdict log: flow 0x409e3fd9 local EP ID 398, remote ID world, proto 6, ingress, action allow, match L4-Only, 172.16.8.1:37102 -> 172.24.129.4:22 tcp SYN
Policy verdict log: flow 0x409e3fd9 local EP ID 398, remote ID world, proto 6, ingress, action allow, match L4-Only, 172.16.8.1:37102 -> 172.24.129.4:22 tcp SYN
```

While this rule was present on the cluster, that is because it is `allow ports X from everywhere` and `allow all traffic from the entities`. But we expected this rule to prevent traffic to SSH (for example) from world.

**Comment by pchaigno** [comment]
> > > After investigation we saw that port SSH was still reachable by `world`, which we did not expect after applying this rule.
> > 
> > 
> > That seems unexpected to me as well. Do you have the corresponding policy verdict?
> 
> ```
> Policy verdict log: flow 0x409e3fd9 local EP ID 398, remote ID world, proto 6, ingress, action allow, match L4-Only, 172.16.8.1:37102 -> 172.24.129.4:22 tcp SYN
> Policy verdict log: flow 0x409e3fd9 local EP ID 398, remote ID world, proto 6, ingress, action allow, match L4-Only, 172.16.8.1:37102 -> 172.24.129.4:22 tcp SYN
> ```
> 
> While this rule was present on the cluster, that is because it is `allow ports X from everywhere` and `allow all traffic from the entities`. But we expected this rule to prevent traffic to SSH (for example) from world.

Oh, right :facepalm: Sorry, this is expected. The policy allows traffic from the list of ports, regardless of where it comes from.

**Pull request closed without merging**
