### PR TITLE
1.5 backports 10.04.2019

### PR DESCRIPTION
**Pull request by nebril**
#7648 
#7654 

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7659)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-docs-please

**Review by tgraf — APPROVED** [review]

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-docs-please

**Comment by tgraf** [comment]
Failing CI test failed because of provision error. Many other redundant tests passed so comfortable to merge this.

**Pull request merged**
