### PR TITLE
test: update k8s versions to the latest patched releases

### PR DESCRIPTION
**Pull request by aanm**
Also update k8s libraries to v0.24.4

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
/test-backport-1.12

**Comment by aanm** [comment]
/test-backport-1.12

**Comment by aanm** [comment]
/test-backport-1.12

**Comment by aanm** [comment]
/test-backport-1.12

**Review by glibsm — APPROVED** [review]

**Comment by aanm** [comment]
/test-backport-1.12

**Comment by aanm** [comment]
/ci-gke-1.12

**Comment by aanm** [comment]
/test-1.21-4.9)

**Comment by aanm** [comment]
/test-1.21-4.9

**Comment by aanm** [comment]
The tests have been failing with random flakes, likely unrelated with the PR. Merging.

**Pull request merged**
