### PR TITLE
v1.6 backports 2020-02-10

### PR DESCRIPTION
**Pull request by aanm**
* #10010 -- Fix cilium-operator regressions (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10010; do contrib/backporting/set-labels.py $pr done 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10127)

### CODE REVIEW

**Comment by aanm** [comment]
cc @johngmyers

**Comment by aanm** [comment]
never-tell-me-odds

**Review by joestringer — APPROVED** [review]
Did you want particular review focus on any areas or it was a fairly clean backport?

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
> Did you want particular review focus on any areas or it was a fairly clean backport?

@joestringer the backport was straightforward. You can still review it to double check if I'm introducing a regression.

**Pull request merged**
