### PR TITLE
Helm: add PrometheusRule  in operator, agent and hubble

### PR DESCRIPTION
**Pull request by wirwolf**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Comment by sayboras** [comment]
I am not 100% sure why this change is required. Can you give some more details or reference to github issue or slack discussion ?

**Comment by nathanjsweet** [comment]
I'm looping @aanm to have the last word, but my instinct is to say that we won't merge this. 

Cluster operators can easily create these types of rules outside of the installation of the Cilium. We won't merge this unless you can give us a compelling reason why these rules ought to be a part of the Cilium installation process. There are lots of other components (Grafana, etc) that we could potentially add as additional initialization parameters to the helm chart, but keeping the helm chart minimal helps us to maintain Cilium better (it's already unwieldy as it is :sweat_smile:).

If you're interested in making helm contributions take a look at the [good-first-issue area/helm issues](https://github.com/cilium/cilium/issues?q=is%3Aissue+is%3Aopen+label%3Agood-first-issue+label%3Aarea%2Fhelm).

**Comment by wirwolf** [comment]
@nathanjsweet So many projects have this feature.
https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx
https://github.com/fluent/helm-charts
All bitnami charts have PrometheusRule yaml

Alerting is part of the monitoring system. Today cilium has part integration in monitoring. 
I add optional params, default disabled. Backward Compatibility is not broken

**Comment by sayboras** [comment]
While cilium is not supporting this in main chart, we do have a bunch of examples/addons in examples directory. Below is the sample chart with prometheus and grafana.

https://github.com/cilium/cilium/tree/master/examples/kubernetes/addons/prometheus

**Comment by chancez** [comment]
@gandro @aanm I think we should reconsider this, and considering writing some of our own as well, and including them in our main helm chart.

**Pull request closed without merging**
