### PR TITLE
bpf: Implement downgrading path from v3 to v2 backend map

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
This PR implements the downgrading path for v3 backend maps introduced in #21797 

```release-note
bpf: Implement downgrading path from v3 to v2 backend map
```

### CODE REVIEW

**Review by brb — APPROVED** [review]
LGTM, thanks.

**Comment by YutaroHayakawa** [comment]
/test-backport-1.12

**Comment by YutaroHayakawa** [comment]
/test-1.21-4.9

**Comment by YutaroHayakawa** [comment]
/test-1.22-4.9

**Comment by YutaroHayakawa** [comment]
/test-1.22-4.9

**Comment by YutaroHayakawa** [comment]
/test-1.22-4.9

**Comment by YutaroHayakawa** [comment]
/ci-aks-1.12

**Comment by YutaroHayakawa** [comment]
Looks like ci-aks-1.12 is failing with https://github.com/cilium/cilium/issues/22162

**Comment by YutaroHayakawa** [comment]
ci-gke is failing, but while waiting for connectivity test cleanup. Since the initial connectivity tests are passing, I think it should be safe to ignore the rest since this change won't be affected by those configuration differences.

**Comment by YutaroHayakawa** [comment]
For test-1.25-4.19 and test-1.26-net-next, I just mistakenly invoked them with the wrong trigger phrase (test).

**Review by gandro — APPROVED** [review]

**Pull request merged**
