### PR TITLE
ci-e2e: Add DSR Geneve dispatch test cases

### PR DESCRIPTION
**Pull request by ysksuzuki**
This commit adds two test cases for DSR Geneve dispatch (lb-mode: 'dsr', lb-dsr-dispatch: 'geneve')

- kernel: bpf-next, kpr: strict, tunnel: disable, lb-acceleration: testing-only, egress-gateway: true
- kernel: bpf-next, kpr: strict, tunnel: geneve,  lb-acceleration: disabled, encryption: wireguard, egress-gateway: true

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

### CODE REVIEW

**Comment by brb** [comment]
> /ci-e2e

:wave: In order to test it, you need to uncomment https://github.com/cilium/cilium/pull/25813/files#diff-d273fd1f22aaf669822ba621a80ac486e51e1559316ebcc2169a9502cc0cfcf7L23.

**Comment by brb** [comment]
> Actually, I'm currently stuck. I don't have the permission
> > It will not work with a branch from a fork (missing secrets).

@ysksuzuki As you are a member of the Cilium org https://github.com/cilium/community/pull/20 (btw, congrats, well deserved!), you can push your branch to cilium/cilium instead of the fork. Just prefix the branch name with `pr/ysksuzuki/`, so that it's easier to remove it in the future when no longer needed.

**Comment by ysksuzuki** [comment]
@brb I couldn't push my branch to cilium/cilium

```
git push origin pr/ysksuzuki/add-secondary-if-kind
ERROR: Permission to cilium/cilium.git denied to ysksuzuki.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Pull request closed without merging**
