### PR TITLE
v1.5 backport 2020 02 11

### PR DESCRIPTION
**Pull request by raybejjani**
v1.5 backports 2020-02-11

 * #9034 -- cilium: only enable IPv6 forwarding if IPv6 is enabled (@jrfastab)
 * #10035 -- Update release process steps (@aanm)
 * ~~#10062 -- [CI] add release name to helm template calls (@nebril)~~
 * #10066 -- ipam: Protect release from releasing alive IP (@tgraf)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 9034 10035 10066; do contrib/backporting/set-labels.py $pr done 1.5; done
```

@aanm I had to apply #10035 by hand and I skipped "contributing/release: fix typo in stable release process" and "contributing/release: remove Update versions step".
@nebril I skipped #10062

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10136)

### CODE REVIEW

**Comment by raybejjani** [comment]
never-tell-me-the-odds

**Comment by raybejjani** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Review by aanm — APPROVED** [review]

**Pull request merged**
