### PR TITLE
v1.12 backports 2023-07-31

### PR DESCRIPTION
**Pull request by sayboras**
- [x] #26880 -- Documentation: fix the broken links/dead links (@vipul-21)
- [x] #25324 -- operator: Adjust CiliumEndpoint GC to only run once in kvstore mode (@learnitall)
  - :warning: conflict due to hive and cell refactoring

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 26880 25324; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.12

**Comment by sayboras** [comment]
/test-1.18-4.9

**Review by learnitall — APPROVED** [review]
My commit looks great, thank you!

**Comment by sayboras** [comment]
/test-backport-1.12

**Comment by sayboras** [comment]
/test-1.17-4.9

**Pull request merged**
