### PR TITLE
Revert "dnsproxy: Use original source address in connections to dns servers"

### PR DESCRIPTION
**Pull request by thorn3r**
Revert "dnsproxy: Use original source address in connections to dns servers"

This reverts commit 79b6f134e9f6578ac5edcb933ef285007a99c1b0.

This change was reverted in main at 4dc8ca2.

Since this was an author backport and required special care, I'm reverting the commit in the branch rather than backporting.

[upstream commit 4dc8ca2 ]

Fixes: #29175

```release-note
Revert "dnsproxy: Use original source address in connections to dns servers" to fix performance regression.
```

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by thorn3r** [comment]
/test-backport-1.13

**Review by julianwiedmann — APPROVED** [review]

**Comment by gandro** [comment]
- https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.19/244/ hit docker rate limit Failed to pull image "docker.io/tgraf/netperf:v1.0"
- https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.19/243/ hit a potential new flake, but looks similar to older flakes https://github.com/cilium/cilium/issues/12491

Restarting

**Comment by gandro** [comment]
/test-1.17-4.19

**Comment by gandro** [comment]
/test-1.20-4.19

**Comment by gandro** [comment]
/test-1.19-4.19

**Comment by gandro** [comment]
/test-1.20-4.19

**Pull request merged**
