### PR TITLE
test: ignored service type not to skip validation between k8s and cilium

### LINKED ISSUE #15382: Address several TODOs inside CI test helpers regarding LoadBalancer & NodePort services
See:
- [ ] https://github.com/cilium/cilium/blob/9020c65f7446bf6b277d33720be50685290904ab/test/helpers/kubectl.go#L4060
- [ ] https://github.com/cilium/cilium/blob/9020c65f7446bf6b277d33720be50685290904ab/test/helpers/kubectl.go#L4229

/cc @brb What is needed here? Could you provide more context?

### PR DESCRIPTION
**Pull request by Shikugawa**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Address TODO. Not to skip NodePort/Loadbalancer to be validated.

Fixes: #15382

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Comment by christarazi** [comment]
testme-please

**Comment by christarazi** [comment]
test-me-please

**Comment by Shikugawa** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

**Comment by pchaigno** [comment]
The CI failures seem legit.
```
08:48:53  08:48:53 STEP: Cilium is not ready yet: cilium services are not set up correctly: Error validating Cilium service on pod {cilium-nl8dp [{0xc0008fcab0 0xc003836500} {0xc0008fcb10 0xc003836508} {0xc0008fcb70 0xc003836510} {0xc0008fcbd0 0xc003836518} {0xc0008fcc30 0xc003836520} {0xc0008fcc90 0xc003836528} {0xc0008fccf0 0xc003836530} {0xc0008fcd50 0xc003836538} {0xc0008fcdb0 0xc003836540} {0xc0008fce10 0xc003836548} {0xc0008fce70 0xc003836550} {0xc0008fcf00 0xc003836558} {0xc0008fcf60 0xc003836560} {0xc0008fcff0 0xc003836568} {0xc0008fd050 0xc003836570} {0xc0008fd0b0 0xc003836578} {0xc0008fd110 0xc003836580} {0xc0008fd170 0xc003836588} {0xc0008fd1d0 0xc003836590} {0xc0008fd260 0xc003836598} {0xc0008fd2c0 0xc0038365a0} {0xc0008fd320 0xc0038365a8} {0xc0008fd380 0xc0038365b0} {0xc0008fd410 0xc0038365b8} {0xc0008fd470 0xc0038365c0} {0xc0008fd4d0 0xc0038365c8} {0xc0008fd530 0xc0038365d0} {0xc0008fd590 0xc0038365d8} {0xc0008fd5f0 0xc0038365e0} {0xc0008fd650 0xc0038365e8} {0xc0008fd6b0 0xc0038365f0} {0xc0008fd710 0xc0038365f8} {0xc0008fd770 0xc003836600} {0xc0008fd7d0 0xc003836608} {0xc0008fd830 0xc003836610} {0xc0008fd890 0xc003836618} {0xc0008fd8f0 0xc003836620} {0xc0008fd980 0xc003836628} {0xc0008fd9e0 0xc003836630} {0xc0008fda40 0xc003836638} {0xc0008fdaa0 0xc003836640} {0xc0008fdb00 0xc003836648} {0xc0008fdb60 0xc003836650} {0xc0008fdbc0 0xc003836658} {0xc0008fdc20 0xc003836660} {0xc0008fdc80 0xc003836668} {0xc0008fdce0 0xc003836670} {0xc0008fdd40 0xc003836678} {0xc0008fdda0 0xc003836680} {0xc0008fde00 0xc003836688} {0xc0008fde60 0xc003836690} {0xc0008fdec0 0xc003836698} {0xc0008fdf20 0xc0038366a0} {0xc0008fdf80 0xc0038366a8} {0xc000b26000 0xc0038366b0} {0xc000b26060 0xc0038366b8} {0xc000b260c0 0xc0038366c0} {0xc000b26120 0xc0038366c8} {0xc000b26180 0xc0038366d0} {0xc000b261e0 0xc0038366d8} {0xc000b262a0 0xc0038366e0} {0xc000b26300 0xc0038366e8} {0xc000b26360 0xc0038366f0} {0xc000b263c0 0xc0038366f8} {0xc000b26420 0xc003836700} {0xc000b26480 0xc003836708}] map[0.0.0.0:30026:[10.0.1.49:80 (53) 0.0.0.0:0 (53) [NodePort, non-routable]] 0.0.0.0:30336:[0.0.0.0:0 (62) [NodePort, non-routable] 10.0.0.250:80 (62) 10.0.1.21:80 (62)] 0.0.0.0:30525:[10.0.1.49:69 (58) 0.0.0.0:0 (58) [NodePort, non-routable]] 0.0.0.0:30713:[0.0.0.0:0 (49) [NodePort, Local, non-routable] 10.0.1.49:69 (49)] 0.0.0.0:30713/i:[0.0.0.0:0 (50) [NodePort, Local, non-routable] 10.0.1.49:69 (50)] 0.0.0.0:30981:[0.0.0.0:0 (68) [NodePort, Local, non-routable] 10.0.1.49:80 (68)] 0.0.0.0:30981/i:[10.0.1.49:80 (69) 0.0.0.0:0 (69) [NodePort, Local, non-routable]] 0.0.0.0:31046:[0.0.0.0:0 (29) [NodePort, Local, non-routable] 10.0.1.21:80 (29)] 0.0.0.0:31046/i:[10.0.1.21:80 (30) 10.0.0.250:80 (30) 0.0.0.0:0 (30) [NodePort, Local, non-routable]] 0.0.0.0:31054:[0.0.0.0:0 (11) [NodePort, non-routable] 10.0.1.21:80 (11) 10.0.0.250:80 (11)] 0.0.0.0:31133:[0.0.0.0:0 (76) [NodePort, non-routable] 10.0.0.250:80 (76) 10.0.1.21:80 (76)] 0.0.0.0:31405:[10.0.1.21:69 (79) 10.0.0.250:69 (79) 0.0.0.0:0 (79) [NodePort, non-routable]] 0.0.0.0:31644:[0.0.0.0:0 (17) [NodePort, sessionAffinity, non-routable] 10.0.1.21:69 (17) 10.0.0.250:69 (17)] 0.0.0.0:31793:[10.0.0.250:80 (21) 10.0.1.21:80 (21) 0.0.0.0:0 (21) [NodePort, sessionAffinity, non-routable]] 0.0.0.0:32133:[10.0.1.21:69 (14) 10.0.0.250:69 (14) 0.0.0.0:0 (14) [NodePort, non-routable]] 0.0.0.0:32185:[0.0.0.0:0 (43) [NodePort, Local, non-routable] 10.0.1.49:80 (43)] 0.0.0.0:32185/i:[10.0.1.49:80 (44) 0.0.0.0:0 (44) [NodePort, Local, non-routable]] 0.0.0.0:32286:[0.0.0.0:0 (35) [NodePort, Local, non-routable] 10.0.1.21:69 (35)] 0.0.0.0:32286/i:[0.0.0.0:0 (36) [NodePort, Local, non-routable] 10.0.1.21:69 (36) 10.0.0.250:69 (36)] 0.0.0.0:6969:[0.0.0.0:0 (85) [HostPort, non-routable] 10.0.1.49:69 (85)] 0.0.0.0:8080:[10.0.1.49:80 (82) 0.0.0.0:0 (82) [HostPort, non-routable]] 10.101.52.35:80:[10.0.1.49:80 (63) 0.0.0.0:0 (63) [ClusterIP]] 10.102.185.235:10069:[0.0.0.0:0 (38) [ClusterIP] 10.0.1.49:69 (38)] 10.102.185.235:10080:[10.0.1.49:80 (37) 0.0.0.0:0 (37) [ClusterIP]] 10.103.251.20:10069:[10.0.1.21:69 (24) 0.0.0.0:0 (24) [ClusterIP] 10.0.0.250:69 (24)] 10.103.251.20:10080:[10.0.1.21:80 (23) 10.0.0.250:80 (23) 0.0.0.0:0 (23) [ClusterIP]] 10.104.251.253:20069:[10.0.1.21:69 (70) 10.0.0.250:69 (70) 0.0.0.0:0 (70) [ClusterIP]] 10.104.251.253:20080:[0.0.0.0:0 (71) [ClusterIP] 10.0.0.250:80 (71) 10.0.1.21:80 (71)] 10.104.42.114:80:[10.0.1.21:80 (59) 10.0.0.250:80 (59) 0.0.0.0:0 (59) [ClusterIP]] 10.106.3.142:9090:[0.0.0.0:0 (4) [ClusterIP] 10.0.0.35:9090 (4)] 10.109.154.241:3000:[0.0.0.0:0 (3) [ClusterIP]] 10.111.86.102:10069:[10.0.1.49:69 (52) 0.0.0.0:0 (52) [ClusterIP]] 10.111.86.102:10080:[10.0.1.49:80 (51) 0.0.0.0:0 (51) [ClusterIP]] 10.96.0.10:53:[0.0.0.0:0 (2) [ClusterIP] 10.0.1.211:53 (2)] 10.96.0.1:443:[192.168.36.11:6443 (1) 0.0.0.0:0 (1) [ClusterIP]] 10.96.140.121:10069:[10.0.0.250:69 (8) 10.0.1.21:69 (8) 0.0.0.0:0 (8) [ClusterIP]] 10.96.140.121:10080:[10.0.1.21:80 (7) 10.0.0.250:80 (7) 0.0.0.0:0 (7) [ClusterIP]] 10.98.27.17:10069:[10.0.0.250:69 (15) 10.0.1.21:69 (15) 0.0.0.0:0 (15) [ClusterIP, sessionAffinity]] 10.98.27.17:10080:[0.0.0.0:0 (16) [ClusterIP, sessionAffinity] 10.0.1.21:80 (16) 10.0.0.250:80 (16)] 10.98.94.156:69:[10.0.0.250:69 (6) 10.0.1.21:69 (6) 0.0.0.0:0 (6) [ClusterIP]] 10.98.94.156:80:[10.0.0.250:80 (5) 10.0.1.21:80 (5) 0.0.0.0:0 (5) [ClusterIP]] 192.0.2.233:20069:[10.0.0.250:69 (73) 0.0.0.0:0 (73) [ExternalIPs] 10.0.1.21:69 (73)] 192.0.2.233:20080:[10.0.0.250:80 (72) 10.0.1.21:80 (72) 0.0.0.0:0 (72) [ExternalIPs]] 192.168.36.11:20069:[0.0.0.0:0 (87) [ExternalIPs] 10.0.0.250:69 (87) 10.0.1.21:69 (87)] 192.168.36.11:20080:[10.0.0.250:80 (86) 0.0.0.0:0 (86) [ExternalIPs] 10.0.1.21:80 (86)] 192.168.36.12:30026:[0.0.0.0:0 (54) [NodePort] 10.0.1.49:80 (54)] 192.168.36.12:30336:[10.0.1.21:80 (60) 10.0.0.250:80 (60) 0.0.0.0:0 (60) [NodePort]] 192.168.36.12:30525:[0.0.0.0:0 (56) [NodePort] 10.0.1.49:69 (56)] 192.168.36.12:30713:[10.0.1.49:69 (45) 0.0.0.0:0 (45) [NodePort, Local]] 192.168.36.12:30713/i:[10.0.1.49:69 (46) 0.0.0.0:0 (46) [NodePort, Local]] 192.168.36.12:30981:[0.0.0.0:0 (66) [NodePort, Local] 10.0.1.49:80 (66)] 192.168.36.12:30981/i:[0.0.0.0:0 (67) [NodePort, Local] 10.0.1.49:80 (67)] 192.168.36.12:31046:[10.0.1.21:80 (25) 0.0.0.0:0 (25) [NodePort, Local]] 192.168.36.12:31046/i:[10.0.0.250:80 (26) 0.0.0.0:0 (26) [NodePort, Local] 10.0.1.21:80 (26)] 192.168.36.12:31054:[10.0.0.250:80 (9) 10.0.1.21:80 (9) 0.0.0.0:0 (9) [NodePort]] 192.168.36.12:31133:[10.0.1.21:80 (74) 0.0.0.0:0 (74) [NodePort] 10.0.0.250:80 (74)] 192.168.36.12:31405:[10.0.1.21:69 (77) 0.0.0.0:0 (77) [NodePort] 10.0.0.250:69 (77)] 192.168.36.12:31644:[10.0.0.250:69 (18) 0.0.0.0:0 (18) [NodePort, sessionAffinity] 10.0.1.21:69 (18)] 192.168.36.12:31793:[0.0.0.0:0 (22) [NodePort, sessionAffinity] 10.0.1.21:80 (22) 10.0.0.250:80 (22)] 192.168.36.12:32133:[10.0.1.21:69 (12) 10.0.0.250:69 (12) 0.0.0.0:0 (12) [NodePort]] 192.168.36.12:32185:[0.0.0.0:0 (39) [NodePort, Local] 10.0.1.49:80 (39)] 192.168.36.12:32185/i:[10.0.1.49:80 (40) 0.0.0.0:0 (40) [NodePort, Local]] 192.168.36.12:32286:[10.0.1.21:69 (31) 0.0.0.0:0 (31) [NodePort, Local]] 192.168.36.12:32286/i:[0.0.0.0:0 (32) [NodePort, Local] 10.0.1.21:69 (32) 10.0.0.250:69 (32)] 192.168.36.12:6969:[0.0.0.0:0 (83) [HostPort] 10.0.1.49:69 (83)] 192.168.36.12:8080:[10.0.1.49:80 (80) 0.0.0.0:0 (80) [HostPort]]]}: Could not find Cilium service with ip 192.168.36.12 in k8s
```

**Comment by Shikugawa** [comment]
Test failure isn't reproduced on my local (with Vagrant) environment. Do I have any failure points? 
```
K8S_VERSION=1.19 CNI_INTEGRATION=minikube ginkgo --focus="K8sPolicyTest.*" -v
```
Just following with [here](https://docs.cilium.io/en/v1.9/contributing/testing/e2e/)

**Comment by pchaigno** [comment]
> Test failure isn't reproduced on my local (with Vagrant) environment. Do I have any failure points?
> 
> ```
> K8S_VERSION=1.19 CNI_INTEGRATION=minikube ginkgo --focus="K8sPolicyTest.*" -v
> ```
> 
> Just following with [here](https://docs.cilium.io/en/v1.9/contributing/testing/e2e/)

I think you need to pass `KUBEPROXY=0` to disable kube-proxy and use our kube-proxy replacement instead.

It seems that variable is missing from the docs: https://github.com/cilium/cilium/issues/15522.

**Pull request closed without merging**
