### PR TITLE
v1.12 backports 2022-08-17

### PR DESCRIPTION
**Pull request by tklauser**
* #20516 -- Document existing FQDN metrics (@christarazi)
 * #20548 -- kubectl get cep returns empty columns of policies statuses (@romanspb80)
 * #20255 -- docs: Added `Default` column in metrics details (@kanurag94)
 * #20875 -- Improve CRD schema update automation during release process (@joestringer)
   * Skipped the last commit d9a14a007a1c ("contrib: Fix CRD schema gen when it needs updating")
     because it would require additional backports (see
     https://github.com/cilium/cilium/pull/20700#issuecomment-1217721443) and maintainers seem to be
     using these scripts from `master` branch only anyway.
 * #20916 -- docs(bandwidth-manager): add note on per-pod limits (@raphink)
 * #20868 -- docs: Switch to our own fork of sphinxcontrib-openapi (@qmonnet)
 * #20900 -- ipsec: Fix incorrect parsing of SPI from mark (@pchaigno)
 * #20893 -- Fix typos in FQDN semaphore metric enablement. (@rahulkjoshi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20516 20548 20255 20875 20916 20868 20900 20893; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.12

**Review by qmonnet — APPROVED** [review]
> https://github.com/cilium/cilium/pull/20868 -- docs: Switch to our own fork of sphinxcontrib-openapi (@qmonnet)

Looks good, thank you

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by joestringer — APPROVED** [review]
Approving for my changes

**Comment by joestringer** [comment]
Triage:
- This backport was run before https://github.com/cilium/cilium/pull/20917 , so l4lb was likely broken. I'll rerun it.
- AKS didn't fetch images, seems like they were not ready in time. I'll re-run it.
- test-1.18-4.9 hit https://github.com/cilium/cilium/issues/15791
- test-1.19-4.9 hit https://github.com/cilium/cilium/issues/20998

**Comment by joestringer** [comment]
/ci-l4lb-1.12

**Comment by joestringer** [comment]
/ci-aks-1.12

**Comment by aditighag** [comment]
> Triage:
> 
> * This backport was run before [gh/workflows: Update L4LB 1.1{0,1,2} jobs #20917](https://github.com/cilium/cilium/pull/20917) , so l4lb was likely broken. I'll rerun it.
> * AKS didn't fetch images, seems like they were not ready in time. I'll re-run it.
> * test-1.18-4.9 hit [CI: K8sConformance Portmap Chaining: connectivity-check pods are not ready after timeout #15791](https://github.com/cilium/cilium/issues/15791)
> * test-1.19-4.9 hit [CI: K8sFQDNTest Restart Cilium validate that FQDN is still working #20998](https://github.com/cilium/cilium/issues/20998)

Re-runs were successful.

**Comment by aditighag** [comment]
@tklauser None of the PRs that were backported had the `backport/pending` label set. How was this backports PR created?

**Pull request merged**
