### PR TITLE
encryption: fix encryption when using ip pools

### PR DESCRIPTION
**Pull request by lbernail**
The refactoring in https://github.com/cilium/cilium/pull/8757/files removed code which causes bpf compilation to fail when using ip pools (`tunnel_endpoint` not declared)

I added what I believe to be the missing code back (tested successfully on our test cluster)

cc @jrfastab

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8868)

### CODE REVIEW

**Comment by jrfastab** [comment]
code is fine but needs another patch to update daemon/sha, just run below.

# make -C ./daemon apply-bindata

**Comment by lbernail** [comment]
I did and added the file in my commit
It also compiles fine locally on my latptop
Could it be because I ran it from mac os?

**Comment by jrfastab** [comment]
strange, maybe try manual rebase and run the command again see if anything changes. Not sure why Mac would make any difference.

**Comment by lbernail** [comment]
Executing the same command inside the build container generated a different sha
The check seems to be ok now

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
@lbernail Looks good. The commit needs a sign-off. We can wait until the CI has run before we rebase.

**Comment by lbernail** [comment]
Sorry I forgot the sign-off. I just added it

**Comment by tgraf** [comment]
test-me-please

**Review by jrfastab — APPROVED** [review]
thanks. LGTM.

**Pull request merged**
