### PR TITLE
nit: fix spelling mistakes in source files.

### PR DESCRIPTION
**Pull request by fristonio**
Fixes spellings mistakes in the codebase comments and code.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8326)

### CODE REVIEW

**Comment by joestringer** [comment]
@fristonio How did you pick up on these, using some tool or something? Maybe we should consider making that available as part of the makefile, and maybe even in the travis build or something so that we pick up on these /before/ they go in.

**Review by joestringer — APPROVED** [review]
:shipit:

**Comment by joestringer** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by fristonio** [comment]
Yeah I used misspell for this. I also created an [issue](https://github.com/cilium/cilium/issues/8112) sometime back related to this, will send a PR with a patch including this in Makefile and in CI maybe.

**Pull request merged**
