### PR TITLE
v1.7 backports 2020-02-21

### PR DESCRIPTION
**Pull request by nebril**
* #10187 -- bpf: remove unused GetProgNextID, GetProgFDByID and GetProgInfoByFD (@tklauser)
 * #10230 -- datapath/loader: always set all args to bpf/init.sh (@tklauser)
 * #10255 -- daemon: remove deprecated --enable-legacy-services option (@tklauser)
 * #10260 -- daemon: Check nodePortMax < ephemeralPortMin in agent (@brb)
 * #10268 -- cilium: encryption, segfaults if existing non-Cilium xfrm policy without mark set exists (@jrfastab)
 * #10243 -- Fixups for Correct clustermesh identity sync kvstore backend usage (@raybejjani)
 * #10283 -- Use -F flag in git log in check-stable script (@nebril)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10187 10230 10255 10260 10268 10243 10283; do contrib/backporting/set-labels.py $pr done 1.7; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10286)

### CODE REVIEW

**Comment by nebril** [comment]
never-tell-me-the-odds

**Comment by nebril** [comment]
never-tell-me-the-odds

**Review by tklauser — APPROVED** [review]
LGTM for my changes.

**Comment by aanm** [comment]
@raybejjani @jrfastab PTAL at your commits to see if they were successfully backported.

**Review by joestringer — COMMENTED** [review]
I checked the backports of #10268 (@jrfastab) and #10243 (@raybejjani ), and they appear to be identical to master. :+1:

**Pull request merged**
