### PR TITLE
ci: Fix NightlyEpsMeasurement

### PR DESCRIPTION
**Pull request by nebril**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10514)

### CODE REVIEW

**Comment by nebril** [comment]
test-nightly NightlyEpsMeasurement Test long live connections

**Review by aanm — APPROVED** [review]

**Comment by nebril** [comment]
test-nightly NightlyEpsMeasurement Test long live connections

**Comment by nebril** [comment]
test-nightly NightlyEpsMeasurement Test long live connections

**Comment by nebril** [comment]
I fixed the test, but it seems that it found a real issue. Creating a GH issue to track this, in the meantime I think this should be merged.

**Comment by nebril** [comment]
test-nightly NightlyEpsMeasurement Test long live connections

**Comment by nebril** [comment]
test-nightly NightlyEpsMeasurement Test long live connections

**Pull request merged**
