### PR TITLE
GKE jenkinsfile

### PR DESCRIPTION
**Pull request by nebril**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9876)

### CODE REVIEW

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by nebril** [comment]
This is an infra change that doesn't affect current CI and is base for further GKE work. We should merge it and continue work on https://github.com/cilium/cilium/pull/9853

**Comment by nebril** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Pull request merged**
