### PR TITLE
Dockerfile: Use Envoy image with access logging fixes

### PR DESCRIPTION
**Pull request by jrajahalme**
Use Envoy image with access logging fixes:
- Use fresh timestamp for the response messages instead of repeating the request timestamp
- Correctly parse status codes from HTTP headers into access log messages

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9133)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
CI infra problems:
```
16:53:18      k8s1-1.11: Reading package lists...
16:53:19      k8s1-1.11: E: Failed to stat /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_bionic-updates_InRelease - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
16:53:19      k8s1-1.11: E: Failed to stat /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_bionic-updates_main_binary-amd64_Packages - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
16:53:19      k8s1-1.11: E: Failed to stat /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_bionic-updates_main_binary-i386_Packages - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
```

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
