### PR TITLE
Modify operator metric CES errors sync to count all CES sync events

### PR DESCRIPTION
**Pull request by dlapcevic**
Change operator metric `ces_sync_errors_total` to be more useful, by counting all CES sync events for success and failure. The metric will be more suitable to be an SLI for Cilium Endpoint Batching feature, because it will be able to show the percentage of successful CES syncs.

Signed-off-by: Dorde Lapcevic <[dordel@google.com](mailto:dordel@google.com)>

```release-note
Modify operator metric CES errors sync to count all CES sync events
```

### CODE REVIEW

**Review by nebril — APPROVED** [review]

**Comment by dlapcevic** [comment]
The `k8s-x-kernel-y` tests are failing for different things that are completely unrelated to this change:
Hubble observe, Connectivity with transparent encryption, WireGuard encryption Pod2pod

**Review by aanm — CHANGES_REQUESTED** [review]
@dlapcevic Thank you for the changes but we will need a deprecation notice since this metric has been released.

**Comment by dlapcevic** [comment]
Hi @aanm, I see. Could you point me to what is needed from my side to complete it?
Besides documenting it, is there anything else I should do?

Also, would it then make more sense for me to just add my new metric without removing the old one, and the old one will be removed at a later time that is specified in the deprecation notice?

**Comment by aanm** [comment]
> Hi @aanm, I see. Could you point me to what is needed from my side to complete it? Besides documenting it, is there anything else I should do?

That would be under `Documentation/operations/upgrade.rst`, similar to what is being done in https://github.com/cilium/cilium/pull/23349

> Also, would it then make more sense for me to just add my new metric without removing the old one, and the old one will be removed at a later time that is specified in the deprecation notice?

Yes, that would be even better. We usually deprecate one by adding a new one and then remove it in the next release. For example: `ces_sync_errors_total` is deprecated in 1.14 and `ces_sync_total` is added now. Then `ces_sync_errors_total` is removed in 1.15.

**Comment by dlapcevic** [comment]
Thanks @aanm!
Done. I only added a new metric in code, and added documentation and comments for deprecation of the old metric.

**Comment by dlapcevic** [comment]
Rebase done.

**Review by aanm — APPROVED** [review]
Thank you!

**Comment by dlapcevic** [comment]
The failed tests are not related to the change, and some required tests didn't complete.

@aanm, can you please help me move it forward?

**Pull request merged**
