### PR TITLE
k8s: only watch for ingress changes if LB is enabled

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

```release-note
Only watch for kuberntes Ingress changes if LB mode is set 
```

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Comment by ianvernon** [comment]
Looks like the K8s tests failed due to a hard timeout being hit. In `ginkgo-kubernetes-all.Jenkinsfile` there is a hard timeout of 60 minutes for these stages. I'll file a PR fixing this.

```
options {
                timeout(time: 60, unit: 'MINUTES')
            }
```

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Timeout was hit again for the missed-k8s tests. I'm going to merge this because the timeout issue is being fixed by another PR.

**Comment by jrajahalme** [comment]
Backport #3856

**Pull request merged**
