### PR TITLE
[WIP] NodePort

### PR DESCRIPTION
**Pull request by brb**
Needs #8314 merged first to get NAT fixed.

TODOs:
- [x] IPv6 data path bits (@borkmann)
- [x] Policy bits in data path still needed (check non-BPF node port and replicate, @brb)
- [x] Proper monitor error handling everywhere (@borkmann)
- [x] K8s node port event handling to plumb services into Cilium maps (@brb)
- [ ] Make it work with vxlan/geneve tunneling (@borkmann)
- [x] Rebase to latest master branch (@borkmann)
- [ ] Documentation of options / limitations (@borkmann)
- [ ] ~~Make it work with encryption~~ (separate PR)

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8256)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
With clang 8.0 the kernel verifier complains, while with clang 6.0 it doesn't:

```
level=warning msg="334: (b7) r1 = 48" subsys=daemon
level=warning msg="335: (7b) *(u64 *)(r10 -280) = r1" subsys=daemon
level=warning msg="336: (85) call bpf_ktime_get_ns#5" subsys=daemon
level=warning msg="337: (37) r0 /= 1000000000" subsys=daemon
level=warning msg="338: (0f) r8 += r0" subsys=daemon
level=warning msg="339: (63) *(u32 *)(r9 +32) = r8" subsys=daemon
level=warning msg=" R0_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0) R8_w=inv(id=0) R9=map_value(id=0,off=0,ks=14,vs=56,imm=0) R10=fp0,call_-1 fp-8=??mmmmmm fp-16=mmmmmmmm fp-24=m??????? fp-64=????mmmm fp-72=mmmmmmmm fp-80=mmmmmmmm fp-120=????0000 fp-128=??mmmmmm fp-136=mmmmmmmm fp-144=????mmmm fp-152=00000000 fp-160=00000000 fp-168=00000000 fp-176=00000000 fp-184=00000000 fp-192=00000000 fp-200=00000000 fp-208=00000000 fp-216=mmmmmmmm fp-224=map_value fp-232=mmmmmmmm fp-240=map_value fp-248=00000000 fp-256=mmmmmmmm fp-264=mmmmmmmm fp-272=mmmmmmmm fp-280=mmmmmmmm" subsys=daemon
level=warning msg="340: (bf) r1 = r9" subsys=daemon
level=warning msg="341: (79) r2 = *(u64 *)(r10 -280)" subsys=daemon
level=warning msg="342: (0f) r1 += r2" subsys=daemon
level=warning msg="math between map_value pointer and register with unbounded min value is not allowed" subsys=daemon
```

Offending code is the `__ct_update_timeout` function.

The `r1` register stores the offset 48 to the `ct_entry.last_tx_report` field, while `r9` stores the reference to `ct_entry`.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
### NodePort and NetworkPolicy

The current behavior of Cilium with NodePort services backed by kube-proxy is ruled by the fact that a source IP address seen by a NodePort endpoint is an IP addr of `cilium_host` from the same host, regardless who made a request (incl. the endpoint A -> NodePort -> endpoint B case). Therefore, we can apply a network policy for a Nodeport service which only either allows or denies all.

With host-lb and NodePort backed by BPF, the source IP address can be different:

- `endpoint A -> NodePort -> endpoint B`: IP addr of `endpoint A`.
- `world -> host A:NodePort -> host B -> endpoint B`: IP addr of `host A` public device.
- `world -> host B:NodePort -> host B -> endpoint B`: the original IP addr of the sender is preserved.

Thus, we can have more a fine-grained policy control than with NodePort by kube-proxy.

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
Closing in favor of #8384.

**Pull request closed without merging**
