### PR TITLE
datapath: fix egress to world entity traffic, add e2e test 

### PR DESCRIPTION
**Pull request by ianvernon**
Add a simple datapath test to ensure that adding egress policy allowing traffic
to entity 'world' is plumbed appropriately and is enforced in the datapath.

Fixes egress to world by changing logic for getting prefix.

Signed-off by: Ian Vernon <ian@cilium.io>

Related-to: #3359

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by ianvernon** [comment]
CI failure is unrelated:
```
21:50:58     k8s1-1.7: E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
21:50:58     k8s1-1.7: E: Unable to lock directory /var/lib/apt/lists/
21:50:58 The SSH command responded with a non-zero exit status. Vagrant
21:50:58 assumes that this means the command failed. The output for this command
21:50:58 should be in the log above. Please read the output to determine what
21:50:58 went wrong.
21:50:58 
```

Retriggering CI.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by joestringer** [comment]
successful CI run, I will rebase now.

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
Please file GH issues to add L4 + L7 egress to world tests

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
Test failed due to issue provisioning the VM. These Vagrant provisioning issues are killer... trying again.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
@tgraf issue tracking end-to-end entity tests: https://github.com/cilium/cilium/issues/3359

**Comment by joestringer** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]
test LGTM

**Pull request merged**
