### PR TITLE
Revert "cilium, recorder: rebuild upon wildcard mask change"

### PR DESCRIPTION
**Pull request by nbusseneau**
This reverts PR #15633 as we believe it to be causing #15737.

### CODE REVIEW

**Comment by nbusseneau** [comment]
test-1.16-netnext

**Comment by gandro** [comment]
@nbusseneau Let's test it for sure, but I would find it highly surprising if this really was the root-cause. The recorder logic is only used when `--enable-recorder=true` is passed to the cilium agent, which (to my knowledge) we are not enabling in CI right now.

**Comment by nbusseneau** [comment]
Yea I used the wrong SHA while doing `git revert`, oops. Fixing.

**Comment by nbusseneau** [comment]
test-1.16-netnext

**Comment by gandro** [comment]
> Yea I used the wrong SHA while doing `git revert`, oops. Fixing.

Ah! In that case, I believe you might also have to revert #15680 because it uses the packages introduced by reverted commits.

**Comment by borkmann** [comment]
If this is just a draft for testing, ok. Otherwise NAK.

**Comment by nbusseneau** [comment]
test-1.16-netnext

**Comment by nbusseneau** [comment]
test-1.16-netnext

**Comment by nbusseneau** [comment]
Not culprit.

**Pull request closed without merging**
