### PR TITLE
test: move K8sFQDNTest restart test out of quarantine

### PR DESCRIPTION
**Pull request by tklauser**
FOR TESTING ONLY, DO NOT MERGE.

### CODE REVIEW

**Comment by tklauser** [comment]
test-only --focus="K8sFQDNTest.*Restart Cilium validate that FQDN is still working"

**Comment by tklauser** [comment]
test-only --focus="K8sFQDNTest.*Restart Cilium validate that FQDN is still working" --k8s-version=1.17 --kernel-version=4.9

**Comment by tklauser** [comment]
test-only --focus="K8sFQDNTest.*Restart Cilium validate that FQDN is still working" --k8s_version=1.17 --kernel_version=4.9

**Comment by tklauser** [comment]
test-only --focus="K8sFQDNTest.*Restart Cilium validate that FQDN is still working" --k8s_version=1.17 --kernel_version=49

**Comment by aanm** [comment]
```
	 kube-system         cilium-d2z7q                       0/1     CrashLoopBackOff   1          106s    192.168.36.11   k8s1   <none>           <none>
	 kube-system         cilium-nqcxv                       0/1     Completed          1          106s    192.168.36.12   k8s2   <none>           <none>
```
it seems Cilium is in `CrashLoopBackOff` but there isn't too much information in the logs.

**Comment by tklauser** [comment]
test-only --focus="K8sFQDNTest.*Restart Cilium validate that FQDN is still working" --k8s_version=1.17 --kernel_version=net-next

**Comment by tklauser** [comment]
test-only --focus="K8sFQDNTest.*Restart Cilium validate that FQDN is still working"  --k8s_version=1.18 --kernel_version 419

**Comment by tklauser** [comment]
test-only --focus="K8sFQDNTest.*Restart Cilium validate that FQDN is still working" --k8s_version=1.18 --kernel_version 49

**Comment by tklauser** [comment]
test-only --focus="K8sFQDNTest.*Restart Cilium validate that FQDN is still working" --k8s_version=1.18 --kernel_version net-next

**Comment by tklauser** [comment]
test-only --focus="K8sFQDNTest.*Restart Cilium validate that FQDN is still working" --k8s_version=1.19 --kernel_version 419

**Comment by tklauser** [comment]
test-only --focus="K8sFQDNTest.*Restart Cilium validate that FQDN is still working" --k8s_version=1.19 --kernel_version 49

**Pull request closed without merging**
