### PR TITLE
bpf: Fix native dev cleanup

### PR DESCRIPTION
**Pull request by brb**
:man_facepalming: ~Adding to my TODO to write tests for it~ (it's already there).

Fixes: 1239278985 ("bpf: Remove bpf_netdev.o from previously used devices")

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10352)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
It's there? Then how did it pass CI before?

EDIT: Oh, I guess you mean it's in your TODOs. OK. :+1:

**Comment by brb** [comment]
Tests failed due CI instability, e.g.:
```
time="2020-02-26T21:01:12Z" level=error msg="Error executing command 'kubectl -n kube-system logs --timestamps=true -l k8s-app=cilium --since=0.000297063s --previous'" error="signal: killed"
time="2020-02-26T21:01:12Z" level=error msg="Error executing command 'kubectl -n kube-system logs --timestamps=true -l k8s-app=cilium --since=0.000297063s --previous'" error="signal: killed"
```

Re-running.

**Comment by brb** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by brb** [comment]
```
 > git fetch --tags --progress https://github.com/cilium/cilium +refs/pull/*:refs/remotes/origin/pr/* --depth=1 # timeout=20
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/cilium/cilium
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:894)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1161)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
```
Re-running.

**Comment by brb** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Pull request merged**
