### PR TITLE
Helm: add LoadBalancer option as comment for Hubble relay service type

### PR DESCRIPTION
**Pull request by darox**
This PR adds `LoadBalancer` as option in the coment section for the service type of Hubble relay.

### CODE REVIEW

**Review by tommyp1ckles — APPROVED** [review]

**Review by brlbil — APPROVED** [review]

**Comment by darox** [comment]
can we get it merged? @brlbil

**Comment by brlbil** [comment]
@darox The PR was missing the release label. I have added one and it is not ready to merge.

**Comment by darox** [comment]
> @darox The PR was missing the release label. I have added one and it is now ready to merge.

thank you for the swift response.

**Pull request merged**
