### PR TITLE
 option: add LoadBalancerUsesDSR() helper

### LINKED ISSUE #25769: Consolidate checks for ad-hoc TUNNEL_PROTOCOL setting
We currently have multiple copies of the "special handling for ad-hoc tunnel" to create parameters for init.sh or set config options: https://github.com/cilium/cilium/blob/6b84bef94ba46ed3c09bf7a242a711449f3003bd/pkg/datapath/loader/base.go#L397 https://github.com/cilium/cilium/blob/6b84bef94ba46ed3c09bf7a242a711449f3003bd/pkg/option/config.go#L3141 and will add another one after completion of #24422 to write a correct value to node_config.h.

As a follow-up we should find a way to consolidate these checks in one place as explained by @julianwiedmann in this https://github.com/cilium/cilium/pull/24422#discussion_r1210202828_

### PR DESCRIPTION
**Pull request by julianwiedmann**
Spelling out the different modes that imply DSR is more robust than saying
"if it's not SNAT, it must be DSR".

As discussed in https://github.com/cilium/cilium/pull/25553#pullrequestreview-1454817088.

### CODE REVIEW

**Review by YutaroHayakawa — APPROVED** [review]
LGTM 👍

**Review by thorn3r — APPROVED** [review]
code clarity++ :+1:

**Review by ti-mo — APPROVED** [review]

**Review by squeed — APPROVED** [review]

**Pull request merged**
