### PR TITLE
cleanup/metrics: Remove deprecated metrics in 1.9

### PR DESCRIPTION
**Pull request by sayboras**
This commit is to clean up all deprecated metrics and labels in 1.9.
    
Signed-off-by: Tam Mach <sayboras@yahoo.com>

TODO:
- [x] Update docs (release note)

```release-note
cleanup/metrics: Cleanup deprecated metrics
```

### CODE REVIEW

**Comment by sayboras** [comment]
test-me-please

**Comment by sayboras** [comment]
test-me-please

**Comment by sayboras** [comment]
test failed due to docker limit, I will re-run later (maybe morning my time)

```
21:58:58   > [builder 1/4] FROM docker.io/library/golang:1.15.4:
21:58:58  ------
21:58:58  failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to build LLB: failed to load cache key: failed to copy: httpReaderSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/golang/manifests/sha256:ef9a25dc0bf0a4b5e28c27cf0e8f0cd2d29fb12b4cc9cc5089471328dd0d808c: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
21:58:58  Makefile.docker:98: recipe for target 'docker-plugin-image' failed
21:58:58  make: *** [docker-plugin-image] Error 1
```

**Comment by sayboras** [comment]
test-me-please

**Comment by sayboras** [comment]
retest-4.9

**Review by christarazi — APPROVED** [review]
:broom: :tada:

**Comment by christarazi** [comment]
test-me-please

**Comment by sayboras** [comment]
retest-runtime

**Review by aanm — APPROVED** [review]

**Review by nebril — APPROVED** [review]
Nice. Should we also update grafana dashboards, or have they already been updated to not use deprecated metrics?

**Comment by sayboras** [comment]
> Nice. Should we also update grafana dashboards, or have they already been updated to not use deprecated metrics?

Yes, it's already done as part of https://github.com/cilium/cilium/pull/12826, so grafana dashboards in 1.9 stopped using deprecated metrics/label.

**Review by ti-mo — APPROVED** [review]
Great! Since 1.9 is now released, shouldn't this target 1.10 instead? I see multiple 1.10 references in removed TODOs :eyes:

**Comment by sayboras** [comment]
> Great! Since 1.9 is now released, shouldn't this target 1.10 instead? I see multiple 1.10 references in removed TODOs

Not sure if I understand correctly. As 1.9 is released, master branch will be for 1.10 only, this change will not be backported to earlier version. Feel free to let me know otherwise.

**Comment by christarazi** [comment]
> Great! Since 1.9 is now released, shouldn't this target 1.10 instead? I see multiple 1.10 references in removed TODOs eyes

I think you might be confused by the PR title slightly. It should read `Remove deprecated metrics _from_ 1.9`. 

Merging.

**Comment by ti-mo** [comment]
> It should read `Remove deprecated metrics _from_ 1.9`.

Gotcha, thanks!

**Pull request merged**
