### PR TITLE
helm: Templatize preflight and clustermesh-apiserver repos

### PR DESCRIPTION
**Pull request by michi-covalent**
Following up on #20066, templatize preflight and clustermesh-apiserver
repos.

Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Review by joestringer — APPROVED** [review]
LGTM thanks!

**Review by sayboras — APPROVED** [review]
LGTM :100:

**Review by gandro — APPROVED** [review]

**Pull request merged**
