### PR TITLE
images: bump cni plugins to v1.5.0

### PR DESCRIPTION
**Pull request by antonipp**
The `cilium-runtime` image can no longer be built on `main` because the CNI plugin binaries for v1.4.1 were updated in-place: https://github.com/containernetworking/plugins/issues/1038

The SHAs on `main` are:
https://github.com/cilium/cilium/blob/db5fcdc567a4b2689a5b5f9e3873d7912d0916f7/images/runtime/cni-version.sh#L4-L5

and the new SHAs upstream are now:
```
$ curl -L "https://github.com/containernetworking/plugins/releases/download/v1.4.1/cni-plugins-linux-amd64-v1.4.1.tgz.sha512"
3679530ee3379afda5f77213de072c298f3d6dc9a70085e7175303b238ab481bc1438cc3bb784d304e85fe34b2dacc418b705fba48be38bd77c23717f0e7a9c0  cni-plugins-linux-amd64-v1.4.1.tgz

$ curl -L "https://github.com/containernetworking/plugins/releases/download/v1.4.1/cni-plugins-linux-arm64-v1.4.1.tgz.sha512"
c96b3cbdee78ef002bdb6eeee23cfd0b5212afae9f983f23330c294eae28551b4227bb6153d53b360415d08e61b1a23c3fdf34a617f2a9439bf520367f55181b  cni-plugins-linux-arm64-v1.4.1.tgz
```

I suggest that we no longer use 1.4.1 and we move towards 1.5.0 which was released properly yesterday. The changelog is very minimal so the bump should be relatively safe: https://github.com/containernetworking/plugins/releases/tag/v1.5.0

```release-note
bump cni plugins to v1.5.0
```

### CODE REVIEW

**Comment by antonipp** [comment]
I think I also need to update the actual images like it was done here: https://github.com/cilium/cilium/pull/31347 
But I am not sure what's the exact release process for this.

**Comment by tklauser** [comment]
@antonipp it looks like the second commit `images: update cilium-{runtime,builder}` is empty. Could you please re-run `make -C image update-runtime-image update-builder-image` and amend the result?

**Comment by antonipp** [comment]
Yes, sorry, just fixed it!

**Review by tklauser — APPROVED** [review]
Thanks @antonipp!

**Comment by tklauser** [comment]
@antonipp it looks like there's still something off with the image hashes and `.devcontainer/devcontainer.json` needs an update too: https://github.com/cilium/cilium/actions/runs/9176783977/job/25232879571?pr=32629

**Comment by antonipp** [comment]
Ok, I re-ran
```
make -C images update-runtime-image update-builder-image
```
and pushed the changes. (I believe that's what the [docs](https://docs.cilium.io/en/latest/contributing/development/images/#update-cilium-builder-and-cilium-runtime-images) instruct to do when the "PR was opened from an external fork")

**Review by bimmlerd — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Review by viktor-kurchenko — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
