### PR TITLE
ci: fix runtime kernel version typo

### PR DESCRIPTION
**Pull request by nebril**

### CODE REVIEW

**Comment by nebril** [comment]
test-runtime

**Comment by nebril** [comment]
Looks like the change fixes the bug: https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/1873/execution/node/81/log/?consoleFull (look at first line, there used to be following error:
```
19:03:47  Traceback (most recent call last):
19:03:47    File "get-gh-comment-info.py", line 12, in <module>
19:03:47      print(args.__dict__[args.retrieve])
19:03:47  KeyError: 'version'
```

**Comment by nebril** [comment]
test-runtime

**Review by christarazi — APPROVED** [review]

**Comment by nebril** [comment]
Since this only affects runtime tests which passed, merging.

**Pull request merged**
