### PR TITLE
[WIP] No mtu changes

### PR DESCRIPTION
**Pull request by raybejjani**
this is a testing thing. Do not merge please

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4406)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by joestringer** [comment]
@raybejjani Are you still investigating this path or can we close this PR?

**Comment by raybejjani** [comment]
since we're still seeing the DNS failures sometimes, yeah... I should run this a few more times. I can close it if you prefer, though (I suspect the hooks may still work even then)

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by tgraf** [comment]
@raybejjani Do we have indication that these changes introduced the DNS flakes?

**Comment by raybejjani** [comment]
@tgraf Not definitively, no. I saw an indication that only UDP (and perhaps only in one direction) was getting through in https://github.com/cilium/cilium/issues/3878#issuecomment-395414304 These were the only recent changes that could explain it, and this was a simple test to run until we have monitor logs to check the policy enforcement.

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
yay, it isn't MTU! https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4100/

see https://github.com/cilium/cilium/issues/3878#issuecomment-396723068

**Pull request closed without merging**
