### PR TITLE
images: Regenerate api/v1 when updating builder

### PR DESCRIPTION
**Pull request by joestringer**
The builder image contains the 'protoc' binary which can generate
different API files when it's updated, notably because protoc decides to
encode its own version into the files it outputs.

Add a step in the builder image workflow to update the api/v1 files.

Related: https://github.com/cilium/cilium/pull/32767#issuecomment-2138859419

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Comment by joestringer** [comment]
New step works in the workflow when testing with `pull_request` rather than `pull_request_target` for the workflow: https://github.com/cilium/cilium/actions/runs/9412074812/job/25926379540?pr=32804#step:33:1 . Dropping temporary test commit https://github.com/cilium/cilium/pull/32804/commits/bcc66f1634780f19d53e8176db55642b98ec54c2 .

**Review by rolinh — APPROVED** [review]

**Review by brlbil — APPROVED** [review]

**Review by aditighag — APPROVED** [review]

**Pull request merged**
