### PR TITLE
Test: Add debug verbose in CoreDNS 1.12

### PR DESCRIPTION
**Pull request by eloycoto**
Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5805)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by ianvernon** [comment]
@eloycoto what added information does this give us? Are there any potential performance impacts of this change? I'm all for more logs for debugging, so I will approve.

**Comment by ianvernon** [comment]
Fat-fingered the close button, sorry about that.

**Review by ianvernon — APPROVED** [review]

**Comment by eloycoto** [comment]
@ianvernon the same verbose as the current core-dns, be able to debug what request pods are doing.

**Pull request merged**
