### PR TITLE
v1.15 Backports 2024-08-12

### PR DESCRIPTION
**Pull request by jschwinger233**
* [x] #33945 (@viktor-kurchenko)
 * [x] #34190 (@joestringer)
 * [x] #34137 (@youngnick) :warning:  dropped due to https://github.com/cilium/cilium/pull/34299#issuecomment-2285986416
 * [x] #34247 (@sayboras)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33945 34190 34137 34247
```

### CODE REVIEW

**Review by viktor-kurchenko — APPROVED** [review]
Thanks!

**Review by sayboras — APPROVED** [review]
Thanks :heavy_check_mark:

**Review by joestringer — APPROVED** [review]

**Comment by jschwinger233** [comment]
I'll drop https://github.com/cilium/cilium/pull/34137 from this backport because it depends on https://github.com/cilium/cilium/pull/33698

```
Please fix the following documentation warnings:
/github/workspace/Documentation/network/servicemesh/ingress-reference.rst:: WARNING: image file not readable: images/ingress-policy.png
/github/workspace/Documentation/network/servicemesh/ingress-reference.rst:: WARNING: image file not readable: images/ingress-policy.png
/github/workspace/Documentation/network/servicemesh/ingress-reference.rst:: WARNING: image file not readable: images/ingress-policy.png
/github/workspace/Documentation/network/servicemesh/ingress-reference.rst:57: WARNING: undefined label: 'gs_ingress_and_network_policy'
/github/workspace/Documentation/network/servicemesh/ingress-reference.rst:57: WARNING: undefined label: 'gs_ingress_and_network_policy'
/github/workspace/Documentation/network/servicemesh/ingress-reference.rst:57: WARNING: undefined label: 'gs_ingress_and_network_policy'
```
errors from https://github.com/cilium/cilium/actions/runs/10347961263/job/28639242829?pr=34299

I'll open another PR to include the dependent PR. cc @youngnick

**Comment by jschwinger233** [comment]
/test-backport-1.15

**Review by tklauser — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by youngnick — APPROVED** [review]

**Pull request merged**
