### PR TITLE
Use Eventually instead of custom loop in pkg/node/manager

### PR DESCRIPTION
**Pull request by AwesomePatrol**
It was flaky on my machine.

```release-note
Use EventuallyWithT in TestNodesStartupPruning 
```

### CODE REVIEW

**Comment by ldelossa** [comment]
@AwesomePatrol do you have any insight on why this may have been flaky and the change you're introducing fixes the flake?

**Comment by AwesomePatrol** [comment]
> @AwesomePatrol do you have any insight on why this may have been flaky and the change you're introducing fixes the flake?

Previously, it checked if file exists 10 times every 1ms. On my machine `/tmp` is not backed by `tmpfs` meaning it is orders of magnitude slower than may be expected.

With this change, stat is called on a path every 10ms until 1s timeout is reached what completely resolves the issue for me.

**Comment by AwesomePatrol** [comment]
Hey, @ldelossa, do you need any more information or changes before approving this PR?

**Review by ldelossa — APPROVED** [review]
LGTM.

**Pull request merged**
