### PR TITLE
test: Disable host firewall in incompatible tests

### PR DESCRIPTION
**Pull request by pchaigno**
Related: #12205
Related: #14552

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
retest-gke

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
retest-gke

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-me-please

**Review by kkourt — APPROVED** [review]

**Pull request merged**
