### PR TITLE
XDP multidev with bpf multihoming and egress gw fixes

### PR DESCRIPTION
**Pull request by jibi**

### CODE REVIEW

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by brb** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-5.4

**Pull request closed without merging**
