### PR TITLE
update bpftool image

### PR DESCRIPTION
**Pull request by kkourt**
Update bpftool image.

### CODE REVIEW

**Review by borkmann — APPROVED** [review]

**Review by twpayne — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Comment by kkourt** [comment]
\test-1.23-net-next

**Comment by kkourt** [comment]
/test-1.23-net-next

**Comment by kkourt** [comment]
/test-1.22-kernel-4.19

**Comment by kkourt** [comment]
/test-1.22-4.19

**Comment by borkmann** [comment]
/test-1.22-4.19

**Review by nebril — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.22-4.19

**Comment by kkourt** [comment]
/test-1.22-4.19

**Comment by kkourt** [comment]
The failures on `1.22-4.19` seem to be consistent. @pchaigno retried the while thing from scratch and got the same diff. It is not clear how bpftool could impact connectivity to basic k8s services. @pchaigno also reported that:
>  I tried to delete BPF programs attached to host interfaces but it didn't change anything. The error is also not 100% reproducible (same test sometimes passes). I've compared the bpftool feature probe outputs and they look the same. We also use bpftool to load some programs so that's next to check on my list.

Moving this PR to draft for now.

**Comment by kkourt** [comment]
Closing this, since there is a new PR out: #19046

**Pull request closed without merging**
