### PR TITLE
endpoint: Remove netns cookie getter

### PR DESCRIPTION
**Pull request by aditighag**

### CODE REVIEW

**Comment by aditighag** [comment]
>2024-07-17T18:35:16.187920510Z time="2024-07-17T18:35:16Z" level=fatal msg="failed to start: daemon creation failed: unable to initialize BPF masquerade support: BPF masquerade requires socket-LB (--bpf-lb-sock=\"false\")\nfailed to stop: unable to find controller ipcache-inject-labels" subsys=daemon

Sole failure is unrelated.

**Review by nathanjsweet — APPROVED** [review]

**Pull request merged**
