### PR TITLE
Pr/backport 1.6 2019 09 20

### PR DESCRIPTION
**Pull request by raybejjani**
* PR: 9159 -- daemon: fix container runtime disabled state status (@fristonio) -- https://github.com/cilium/cilium/pull/9159
 * PR: 9161 -- Refactor probing to reuse client (@borancar) -- https://github.com/cilium/cilium/pull/9161
 * PR: 9186 -- loader: remove hash from compileQueue if build fails (@ianvernon) -- https://github.com/cilium/cilium/pull/9186
 * PR: 9195 -- docs: Update kubeproxy-free guide (@brb) -- https://github.com/cilium/cilium/pull/9195
 * PR: 9193 -- fix connectivity issue in cilium-operator v1.6.1 that prevents connecting to cilium-etcd-client.kube-system.svc (@aanm) -- https://github.com/cilium/cilium/pull/9193
 * PR: 9187 -- bpf: Don't delete conntrack entries on policy deny (@tgraf) -- https://github.com/cilium/cilium/pull/9187
 * PR: 9182 -- daemon: check error from `d.init()` (@ianvernon) -- https://github.com/cilium/cilium/pull/9182
 * PR: 9183 -- daemon: move directory setup into `SetUpTest` (@ianvernon) -- https://github.com/cilium/cilium/pull/9183
 * PR: 9203 -- endpoint: start a controller to retry regeneration if regeneration fails (@ianvernon) -- https://github.com/cilium/cilium/pull/9203
 * PR: 9223 -- test: bump k8s testing versions to 1.13.11, 1.14.7 and 1.15.4 (@aanm) -- https://github.com/cilium/cilium/pull/9223
 * PR: 9217 -- charts/managed-etcd: bump cilium-etcd-operator to v2.0.7 (@aanm) -- https://github.com/cilium/cilium/pull/9217
 * PR: 9222 -- Add support for k8s 1.16.0 (@aanm) -- https://github.com/cilium/cilium/pull/9222
 * PR: 9208 -- FQDN IP updates wait on endpoint regenerations (@raybejjani) -- https://github.com/cilium/cilium/pull/9208

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9235)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-missed-k8s

**Comment by aanm** [comment]
@raybejjani it seems somethings are missing :scream: 

```
daemon/fqdn.go:128:10: d.endpointManager undefined (type *Daemon has no field or method endpointManager)
```

**Review by aanm — APPROVED** [review]
All good for my PRs

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-missed-k8s

**Pull request merged**
