### PR TITLE
Envoy update 2018 09 06

### PR DESCRIPTION
**Pull request by jrajahalme**
Update Envoy to a newer SHA to get fixes needed for, e.g., testing infrastructure.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5499)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
rebased to master

**Comment by jrajahalme** [comment]
test-me-please

**Comment by ianvernon** [comment]
@jrajahalme can this be closed?

**Comment by rlenglet** [comment]
Yes it should be closed.

**Pull request closed without merging**
