### PR TITLE
v1.9 backports 2020-10-29

### PR DESCRIPTION
**Pull request by aditighag**
* #13769 -- bpf: Fix --force-local-policy-eval-at-source=false (@joestringer)
 * #13778 -- Pre-allocate slices with known size (@tklauser)
 * #13762 -- cilium/cmd: Cosmetic code clean-ups (@twpayne)
 * #13784 -- install/kubernetes: Allow update of "remote" secret (@jrajahalme)
 * #13771 -- docs: Add gsg cross-link for cluster-pool IPAM (@joestringer)
 * #13782 -- install/kubernetes: Fix experimental-install.yaml for Hubble (@gandro)
 * #13791 -- Fix focus in jenkinsfile (@nebril)
 * #13756 -- backporting: Properly escape commit message when used as regex (@gandro)
 * #13783 -- docs: disable k3s network policy enforcement (@aanm)
 * #13780 -- pkg/kvstore: fix race in etcd initialization (@aanm)
 * #13796 -- hubble: Fix dropped flows not showing up in Hubble UI (@gandro)
 * #13794 -- daemon: Don't check XDPDevice in DevicePreFilter case (@brb)
 * #13792 -- helm: Remove `type: kubernetes.io/tls` from hubble-ca-secret (@gandro)
 * #13758 -- test: skip new tests in upstream k8s (@aanm)
 * #13709 -- build: bpf: Fix cross-compilation of gcc targets (@mrostecki)

Skipped as it may cause regression in CI:
 * #13793 -- test: Unquarantine K8sUpdates under GKE (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13769 13778 13762 13784 13771 13782 13791 13756 13783 13780 13796 13794 13792 13758 13709; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
:+1: for my PR.

**Comment by pchaigno** [comment]
test-backport-1.9

**Review by aanm — APPROVED** [review]
LGT for my changes

**Comment by aanm** [comment]
test-backport-1.9

**Review by tklauser — APPROVED** [review]
👍 for my change

**Review by brb — APPROVED** [review]
LGTM for my changes, thanks.

**Review by vadorovsky — APPROVED** [review]
LGTM for my change, thanks!

But it seems like checkpatch complains about some BPF change.

**Comment by pchaigno** [comment]
> But it seems like checkpatch complains about some BPF change.

It's the usual false positive for backport PRs. We can ignore.

**Comment by aditighag** [comment]
retest-gke

**Comment by aditighag** [comment]
retest-gke

**Review by jrajahalme — APPROVED** [review]
For my PR.

**Comment by aditighag** [comment]
GKE test failures seem concerning. I went over the agent logs, and I didn't see any red flags.

**Comment by aditighag** [comment]
How do you re-trigger just the GKE test? I'm not sure if test-gke will be effective here since the CI test run was originally triggered by running test-backport1.9.

**Comment by aditighag** [comment]
The GKE-booktinfo [failure](https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/3004/testReport/junit/Suite-k8s-1/16/K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter_service_connectivity/) seems similar to - https://github.com/cilium/cilium/pull/13720#issuecomment-715297964

**Comment by aditighag** [comment]
retest-gke

**Comment by joestringer** [comment]
Hit https://github.com/cilium/cilium/issues/13832, https://github.com/cilium/cilium/issues/13833 . First one at a glance seems maybe test infrastructure issue where (1) we don't know where the kill comes from, but (2) the background process run kill causes the entire test to fail, there doesn't appear to be a retry. For the second one, somehow the propagation of DNS names in this environment was slow or unsuccessful. Unclear what role either the agent code or the testing code plays in triggering this failure, we should investigate further.

I'll retry just to see if we're consistently hitting GKE failures.

**Comment by joestringer** [comment]
retest-gke

**Comment by joestringer** [comment]
Still lots of failures on the latest GKE run:
https://github.com/cilium/cilium/pull/13812/checks?check_run_id=1329336861

The GKE pipeline also recently started failing more often than not:
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline-GKE/

It's a bit hard to determine whether there were changes merged into master which caused GKE to become unstable (and then they're backported here for instance) or whether the GKE CI environment in general became more flaky because of some infrastructure or provisioning isse, or something else.

I've kicked off a fresh backport for a single PR in https://github.com/cilium/cilium/pull/13836 , we can see whether that GKE run also fails in a similar way or if it passes. Maybe we can use that as a comparison point for whether GKE CI on v1.9 is in a reasonable shape.

**Comment by joestringer** [comment]
We've had three green GKE runs in a row on https://github.com/cilium/cilium/pull/13836. If I read above correctly, it appears we have had 5 failed GKE runs in a row above in this PR. That seems like reasonable grounds to investigate whether one of the changes being backported in this PR is causing the CI instability.

**Comment by pchaigno** [comment]
retest-gke

**Comment by pchaigno** [comment]
retest-gke

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-backport-1.9

**Comment by aditighag** [comment]
retest-runtime

**Comment by aditighag** [comment]
NetNext failure - https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/1036/
K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing Tests NodePort with Maglev Tests NodePort

**Comment by aditighag** [comment]
retest-netnext

**Comment by aditighag** [comment]
retest-net-next

**Comment by joestringer** [comment]
Hit https://github.com/cilium/cilium/issues/13071, https://github.com/cilium/cilium/issues/13853 on net-next run. Second one appears to be new, but both are clearly flakes since the previous run didn't hit either of these issues. They also did not appear in the equivalent test runs for k8s-1.18 or k8s-1.19 runs.

**Comment by joestringer** [comment]
I also looked into the runtime failure earlier, it appears to be known flake #12862 . https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/2370/execution/node/100/log/?consoleFull

**Comment by joestringer** [comment]
GKE reports a failure but it's an infrastructure issue:

https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/3030/flowGraphTable/

```
Archiving artifacts
java.lang.InterruptedException: no matches found within 10000
        at hudson.FilePath$ValidateAntFileMask.hasMatch(FilePath.java:2803)
        at hudson.FilePath$ValidateAntFileMask.invoke(FilePath.java:2682)
        at hudson.FilePath$ValidateAntFileMask.invoke(FilePath.java:2663)
        at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3050)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to jenkins-node-gke-fixed-1
                at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
                at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
                at hudson.remoting.Channel.call(Channel.java:957)
                at hudson.FilePath.act(FilePath.java:1070)
                at hudson.FilePath.act(FilePath.java:1059)
                at hudson.FilePath.validateAntFileMask(FilePath.java:2661)
                at hudson.tasks.ArtifactArchiver.perform(ArtifactArchiver.java:243)
                at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
                at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
                at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Caused: hudson.FilePath$TunneledInterruptedException
        at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3052)
        at hudson.remoting.UserRequest.perform(UserRequest.java:212)
        at hudson.remoting.UserRequest.perform(UserRequest.java:54)
        at hudson.remoting.Request$2.run(Request.java:369)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
Caused: java.lang.InterruptedException: java.lang.InterruptedException: no matches found within 10000
        at hudson.FilePath.act(FilePath.java:1072)
        at hudson.FilePath.act(FilePath.java:1059)
        at hudson.FilePath.validateAntFileMask(FilePath.java:2661)
        at hudson.tasks.ArtifactArchiver.perform(ArtifactArchiver.java:243)
        at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
        at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
        at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by joestringer** [comment]
Merging as known flakes as reported recently in this PR are not related to the code changes made here.

**Pull request merged**
