### PR TITLE
ci: Remove test-gke

### PR DESCRIPTION
**Pull request by brb**

### CODE REVIEW

**Comment by brb** [comment]
/test-1.24-net-next

**Review by gandro — APPROVED** [review]
Health and Hubble test related changes look good to me!

**Comment by brb** [comment]
/test-1.24-net-next

**Comment by brb** [comment]
/test-1.24-net-next

**Comment by brb** [comment]
CI net-next failure seems to be legit. Converting back to draft.

**Review by ldelossa — APPROVED** [review]

**Comment by brb** [comment]
/test-1.24-net-next

**Comment by brb** [comment]
/test-1.24-net-next

**Comment by brb** [comment]
/test-1.24-net-next

**Comment by brb** [comment]
/test-1.23-4.19

**Pull request closed without merging**
