### PR TITLE
istio: Update to release 1.4.6

### PR DESCRIPTION
**Pull request by jrajahalme**
Update Istio GSG and CI test to release 1.4.6.

```release-note
Istio integration has been updated to Istio release 1.4.6.
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10466)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Docs changes LGTM. I presume that you went through and manually validated these steps?

**Comment by jrajahalme** [comment]
@joestringer Yes, manually validated the doc changes.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Pull request merged**
