### PR TITLE
Change endpoint policy status map to regular map

### PR DESCRIPTION
**Pull request by nebril**
Fixes: #7080

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7103)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Review by aanm — CHANGES_REQUESTED** [review]
How does this change fixes the issue #7080?

**Comment by ianvernon** [comment]
> How does this change fixes the issue #7080?

@aanm - @nebril described his hypothesis on the issue here - 
https://github.com/cilium/cilium/issues/7080#issuecomment-464099949

**Comment by tgraf** [comment]
The suspense is killing me why this fixes #7080

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
Details on why this happenned are in #7080

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by tgraf — APPROVED** [review]
Thanks for adding details to the commit message

**Pull request merged**
