### PR TITLE
CI: Upgrade test on GKE

### PR DESCRIPTION
**Pull request by raybejjani**
The commits are somewhat independent.
- Prefer helm options passed into RunHelm. This allows overriding the global overrides (e.g. force node-init to off when running preflight).
  - Ensure node-init is off when running preflight in the Update/Upgrade tests
- Parse the agent.image tag and set registry and tag, if they are not otherwise set and .image is a full image URL.
- Ensure preflight.image always matches agent.image. This accounts for overrides of the image.
- Cleanup left-over preflight pods in the Update/Upgrade tests.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10422)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-gke K8sUpdates*

**Comment by raybejjani** [comment]
test-gke K8sDemosTest*

**Comment by raybejjani** [comment]
test-gke K8s*

**Comment by raybejjani** [comment]
test-gke K8s*

**Comment by raybejjani** [comment]
test-gke K8s*

**Comment by raybejjani** [comment]
test-gke K8s*

**Comment by raybejjani** [comment]
test-gke K8s*

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-gke K8s*

**Comment by raybejjani** [comment]
test-gke K8sUpdates*

**Comment by raybejjani** [comment]
test-focus K8sUpdates*

**Comment by raybejjani** [comment]
test-gke K8sUpdates*

**Comment by raybejjani** [comment]
test-focus K8sUpdates*

**Comment by raybejjani** [comment]
test-gke K8sUpdates*

**Comment by raybejjani** [comment]
test-focus K8sUpdates*

**Comment by raybejjani** [comment]
test-gke K8sUpdates*

**Comment by raybejjani** [comment]
test-focus K8sUpdates*

**Comment by raybejjani** [comment]
test-gke K8sUpdates*

**Comment by raybejjani** [comment]
test-focus K8sUpdates*

**Comment by raybejjani** [comment]
test-gke K8s*

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-gke K8s*

**Comment by raybejjani** [comment]
test-gke K8s*

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-gke K8s*

**Comment by raybejjani** [comment]
test-gke K8s*

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-nightly

**Comment by raybejjani** [comment]
test-focus (K8sDemosTest)|(K8sUpdates).*

**Comment by raybejjani** [comment]
test-gke (K8sDemosTest)|(K8sUpdates).*

**Comment by raybejjani** [comment]
test-gke K8s(DemosTest)|(Updates).*

**Comment by raybejjani** [comment]
test-gke K8s(DemosTest)|(Updates).*

**Comment by raybejjani** [comment]
test-gke K8s(DemosTest)|(Updates).*

**Comment by raybejjani** [comment]
test-gke K8s(DemosTest)|(Updates).*

**Comment by raybejjani** [comment]
test-nightly

**Comment by raybejjani** [comment]
test-gke K8s.*

**Comment by raybejjani** [comment]
test-gke K8s(DemosTest)|(Updates).*

**Comment by raybejjani** [comment]
test-focus NightlyExamples Upgrade.*

**Comment by raybejjani** [comment]
test-focus K8s(DemosTest)|(Updates).*

**Comment by raybejjani** [comment]
test-gke K8s(DemosTest)|(Updates).*

**Comment by raybejjani** [comment]
test-focus K8s(DemosTest)|(Updates).*

**Comment by raybejjani** [comment]
test-gke K8s.*

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-gke K8s.*

**Comment by raybejjani** [comment]
test-nightly

**Comment by raybejjani** [comment]
test-gke K8s(DemosTest)|(Updates).*

**Comment by raybejjani** [comment]
test-focus K8s(DemosTest)|(Updates).*

**Comment by raybejjani** [comment]
test-gke K8s(DemosTest)|(Updates).*

**Comment by raybejjani** [comment]
test-focus K8s(DemosTest)|(Updates).*

**Comment by raybejjani** [comment]
test-gke K8s(DemosTest)|(Updates).*

**Comment by raybejjani** [comment]
test-focus K8s(DemosTest)|(Updates).*

**Comment by raybejjani** [comment]
test-gke K8s(DemosTest)|(Updates).*

**Comment by raybejjani** [comment]
test-focus K8s(DemosTest)|(Updates).*

**Comment by raybejjani** [comment]
never tell me the odds

**Review by nebril — APPROVED** [review]
LGTM!

**Comment by nebril** [comment]
never-tell-me-the-odds

**Comment by nebril** [comment]
test-gke

**Comment by raybejjani** [comment]
never-tell-me-the-odds

**Comment by raybejjani** [comment]
test-gke

**Comment by raybejjani** [comment]
test-focus K8s(Demos|FQDN).*

**Comment by raybejjani** [comment]
test-focus K8s(Demos|FQDN).*

**Comment by raybejjani** [comment]
test-gke K8s(Demos|FQDN).*

**Comment by raybejjani** [comment]
test-focus K8s(Demos|FQDN).*

**Comment by raybejjani** [comment]
test-gke K8s(Demos|FQDN).*

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-focus K8s(Demos|FQDN).*

**Comment by raybejjani** [comment]
test-gke K8s(Demos|FQDN).*

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-k8s

**Comment by raybejjani** [comment]
test-gke

**Comment by raybejjani** [comment]
test-focus K8sDatapathConfig.*

**Comment by raybejjani** [comment]
test-gke

**Comment by raybejjani** [comment]
test-gke K8sBasic Test Policy.*

**Comment by raybejjani** [comment]
test-gke K8sPolicyTest Basic Test

**Comment by raybejjani** [comment]
test-gke K8sPolicyTest Basic Test.*

**Comment by raybejjani** [comment]
test-gke K8sPolicyTest Basic Test.*

**Comment by raybejjani** [comment]
test-gke

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-gke

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-gke

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-gke

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-gke

**Comment by raybejjani** [comment]
test-focuse K8s(Updates)|(FQDNTest)|(ServicesTest).*

**Comment by raybejjani** [comment]
test-gke K8s(Updates)|(FQDNTest)|(ServicesTest).*

**Comment by raybejjani** [comment]
test-focus K8s(Updates)|(FQDNTest)|(ServicesTest).*

**Comment by raybejjani** [comment]
test-gke K8s(Updates)|(FQDNTest)|(ServicesTest).*

**Comment by raybejjani** [comment]
test-focus K8s(Updates)|(FQDNTest)|(ServicesTest).*

**Comment by raybejjani** [comment]
test-gke K8s(Updates)|(FQDNTest)|(ServicesTest).*

**Comment by raybejjani** [comment]
test-focus K8s(Updates)|(FQDNTest)|(ServicesTest).*

**Comment by raybejjani** [comment]
test-gke K8s(Updates)|(FQDNTest)|(ServicesTest).*

**Comment by raybejjani** [comment]
test-focus K8s(Updates)|(FQDNTest)|(ServicesTest).*

**Comment by raybejjani** [comment]
test-gke K8s(Updates)|(FQDNTest)|(ServicesTest).*

**Comment by raybejjani** [comment]
test-gke K8s(Updates)|(FQDNTest)|(ServicesTest).*

**Comment by raybejjani** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Comment by raybejjani** [comment]
test-gke

**Comment by nebril** [comment]
Let's ship it.

**Pull request merged**
