### PR TITLE
ci: 100 node scale - alert on bootstrap/cpu/memory regressions

### PR DESCRIPTION
**Pull request by marseel**
As we want capture performance of Cilium Agent during bootstraping phase let's deploy first prometheus before creating 100 nodes.
Additionally, add bunch of metrics with cpu/memory usage + bootstrap time and let's start alerting on thresholds.

Removing the exec service speeds up the test slightly and it's not required to bootstrap prom stack.

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
Thanks!

**Review by brlbil — APPROVED** [review]

**Comment by marseel** [comment]
I've manually added ready-to-merge, I have no idea why it wasn't added automatically :shrug:

**Pull request merged**
