### PR TITLE
v1.10 backports 2022-09-28

### PR DESCRIPTION
**Pull request by gandro**
* #20979 -- helm: Fix post-start and pre-stop hooks for cilium-nodeinit on Ubuntu EKS images (@dctrwatson) :warning: Conflicts due to file restructuring 
 * #21239 -- Remove Slack notifications (@michi-covalent) :warning: Conflicts due to missing or changed files
 * #21365 -- daemon: Fix a nil dereference on cleanup when DNS proxy is not enabled (@joamaki) :warning: Conflicts due the cleanup call being different in v1.10
 * #21348 -- bugtool: Dump envoy config for troubleshooting (@sayboras) :warning: Conflicts due to pprof flag being different on v1.10 
 * #21254 -- makefile: use versioned go container when formatting after api generate. (@tommyp1ckles) :warning: Conflicts due to flags definition being different in v1.10 
 * #21402 -- Fix a typo in the comment example (@farcaller) :warning: Minor conflicts due to different helm values in v1.10
 * #21429 -- cmd/bpf: Log if no policy maps found (@aditighag)
 * #21370 -- ipsec: Simplify XFRM IN policies (@pchaigno) :warning: Minor conflicts in import section
 * #21449 -- daemon: avoid nil pointer dereference on invalid endpoint state (@tklauser)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20979 21239 21365 21348 21254 21402 21429 21370 21449; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
still looks good on my commit, thanks :100:

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by tklauser — APPROVED** [review]
Thanks, my change looks good.

**Review by michi-covalent — APPROVED** [review]
❤️ https://github.com/cilium/cilium/pull/21469/commits/a8ecc2e311cd6334656d4d069174321abdf9830d

**Review by aditighag — APPROVED** [review]
Backport of my changes look good. Thanks!
(unrelated: Liked how some of the commits with conflicts are highlighted with ⚠️).

**Review by joamaki — APPROVED** [review]
Thanks, my commit is good

**Review by joestringer — APPROVED** [review]
Approving on behalf of @cilium/github-sec

**Comment by gandro** [comment]
/test-backport-1.10

**Review by nebril — APPROVED** [review]

**Comment by gandro** [comment]
Marking this ready-to-merge. The failing GKE workflows are infrastructure related and both pipelines have been disabled on master for that reason.

**Pull request merged**
