### PR TITLE
docs: Explain test-focus CI trigger

### PR DESCRIPTION
**Pull request by raybejjani**
We've had test-focus for some time but haven't documented it.

One issue to consider: test-focus updates the PR such that if it passes, the PR can be merged without passing the full test suite. It might be best to create a new status field on the PR for focussed tests.

### CODE REVIEW

**Comment by raybejjani** [comment]
test-docs-please

**Review by pchaigno — APPROVED** [review]

**Comment by raybejjani** [comment]
test-docs-please

**Comment by raybejjani** [comment]
@pchaigno I updated the job link in the table, if you wanted to take another look. test-focus now has it's own jenkins job to avoid confusion. I'll probably merge anyway at some point since any mistake I made can be fixed.

**Comment by raybejjani** [comment]
test-focus K8sDemosTest.*

**Comment by pchaigno** [comment]
Thanks for the ping! I wanted to re-review after the Slack message but forgot.

LGTM!

**Pull request merged**
