### PR TITLE
v1.11: Update Go to 1.17.7

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.11

**Review by jibi — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by tklauser** [comment]
/test-1.17-4.9

**Comment by tklauser** [comment]
/test-1.23-4.9

**Pull request merged**
