### PR TITLE
ipam: deepcopy interface resource correctly.

### PR DESCRIPTION
**Pull request by tommyp1ckles**
ipam: deepcopy interface resource correctly.

Currently only used by azure ipam test mocks, was resulting in race
condition prone code where underlying interface addresses where being
shared across resources.

This ensures that the revision interface is correctly deepcopied such
that the underlying resource is also safely copied.

This seems at least partially related to flake https://github.com/cilium/cilium/issues/26617.

Addresses: https://github.com/cilium/cilium/issues/26617

Signed-off-by: Tom Hadlaw <tom.hadlaw@isovalent.com>

### CODE REVIEW

**Review by christarazi — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Comment by tommyp1ckles** [comment]
failures are flake this is partially trying to address

**Comment by tommyp1ckles** [comment]
Think this is still desired, if tests pass following the last fix for the referenced test.

**Comment by tommyp1ckles** [comment]
GKE test hit: https://github.com/cilium/cilium/issues/31385

**Comment by christarazi** [comment]
@hemanthmalla Could you take a look on behalf of cilium/azure?

**Review by hemanthmalla — APPROVED** [review]
LGTM for Azure

**Pull request merged**
