### PR TITLE
v1.5 backports 2019-11-16

### PR DESCRIPTION
**Pull request by aanm**
* #9606 -- vendor: point vishvananda/netlink back to upstream (@borkmann)
 * #9614 -- Update k8s to v1.16.3, 1.14.9 and 1.15.6 (@aanm)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 9606 9614; do contrib/backporting/set-labels.py $pr done 1.5; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9626)

### CODE REVIEW

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Review by borkmann — APPROVED** [review]

**Pull request merged**
