### PR TITLE
v1.13 backport 2023-01-05

### PR DESCRIPTION
**Pull request by borkmann**
Manual 1.13 backport of:

- https://github.com/cilium/cilium/pull/22421 (myself)
- https://github.com/cilium/cilium/pull/22814 (myself)
- https://github.com/cilium/cilium/pull/22915 (@julianwiedmann)
- https://github.com/cilium/cilium/pull/23012 (myself)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 22421 22814 22915 23012; do contrib/backporting/set-labels.py $pr done 1.13; done
```

### CODE REVIEW

**Comment by borkmann** [comment]
/test-backport-1.13

**Comment by borkmann** [comment]
`k8s-1.19-kernel-4.9` pipeline is related to known issue https://github.com/cilium/cilium/issues/22849

**Review by julianwiedmann — APPROVED** [review]
bpf parts look good, thanks!

**Comment by borkmann** [comment]
(Currently investigating the l4lb issue, can repro locally on tc BPF. XDP works.)

**Comment by borkmann** [comment]
/ci-l4lb-1.13

**Comment by borkmann** [comment]
/ci-l4lb-1.13

**Comment by borkmann** [comment]
/ci-l4lb-1.13

**Comment by borkmann** [comment]
/ci-l4lb-1.13

**Comment by borkmann** [comment]
/ci-l4lb-1.13

**Comment by borkmann** [comment]
/test-backport-1.13

**Comment by borkmann** [comment]
gke:
```
Run gcloud container clusters create cilium-cilium-3895055065 \
Default change: During creation of nodepools or autoscaling configuration changes for cluster versions greater than 1.24.1-gke.800 a default location policy is applied. For Spot and PVM it defaults to ANY, and for all other VM kinds a BALANCED policy is used. To change the default values use the `--location-policy` flag.
Note: The Pod address range limits the maximum size of the cluster. Please refer to https://cloud.google.com/kubernetes-engine/docs/how-to/flexible-pod-cidr to learn how to optimize IP address allocation.
ERROR: (gcloud.container.clusters.create) ResponseError: code=409, message=Already exists: projects/***/zones/us-west2-a/clusters/cilium-cilium-3895055065.
Error: Process completed with exit code 1.
```

**Comment by borkmann** [comment]
(L4LB suite requires a full backport/sync with master. [Related GH](https://github.com/cilium/cilium/issues/22833), discussing with Martynas about needed PRs.)

**Pull request merged**
