### PR TITLE
helm: Divide operator image settings in subsections

### PR DESCRIPTION
**Pull request by vadorovsky**
Before this change, operator images were using the common values section
and appending a sufffix ("-generic", "-aws", "-alibabacloud", "-azure")
to the "repository" value.

That approach might be confusing for people who use `helm inspect
values` as a source of truth about container images used for the
operator. The visible `quay.io/cilium/cilium-operator` name is
misleading and does not exist (without prefix).

This change aim to minimize the confusion by having separate image
settings for each particular operator image.

Ref: rancher/rke2#1224

Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

### CODE REVIEW

**Comment by vadorovsky** [comment]
test-me-please

**Review by joestringer — CHANGES_REQUESTED** [review]
I suspect you'll face some issues with the upgrade in ginkgo tests, since the v1.10 or earlier helm charts won't recognize the new option. You'll likely need to add some special extra helm argument handling code for this case. We did something similar in the past but recently removed it in commit ad1e0c4876d4e48539abfccb18807b9d0d010239, so it'll likely help to look there.

We'll also need to consider the implications on upgrade here - if someone already deployed with a values file with specific values today, can we inherit those values into a helm upgrade somehow? If not, the minimum we can do is document what you need to change in `Documentation/operations/upgrade.rst` to have a successful cloud upgrade.

**Comment by joestringer** [comment]
Ginkgo CI looks pretty red too, looks like in the default non-cloud case the image string is not being generated correctly.

**Comment by joestringer** [comment]
If we decide that this PR is the right path forward, this is definitely something I want to raise as a "minor" release note since it could impact users. I agree with the premise in the description that if people expect to be able to introspect the image in a particular way and our charts don't follow that, we're kinda breaking their expectations. This is not ideal.

At the same time, changing something like this can also be a bit painful and it could have severe impacts on users if not implemented or communicated well, sometimes it's simpler to just leave something suboptimal in place to minimize the upgrade pain.

**Comment by errordeveloper** [comment]
I think what would be the most helpful for this is versioned configuration. If we had the machinery to handle multiple configuration versions, it'd be much easier to implement meaningful user-experience that can iterated on easily.

**Comment by vadorovsky** [comment]
@errordeveloper Do you know any good example of such "versioned values" machinery?

**Comment by errordeveloper** [comment]
@vadorovsky like a operator+CRD, or an equivalent with client-side-only implementation :)

**Comment by vadorovsky** [comment]
Alright, I will close this PR then. I agree that without configuration versioning, it's going to be painful and hard to migrate.

**Pull request closed without merging**
