### PR TITLE
helm: Add missing SA automount configuration

### PR DESCRIPTION
**Pull request by ayuspin**
Follow-up to https://github.com/cilium/cilium/pull/23441 to add missing automountServiceAccountToken, extraVolumes and extraVolumeMounts

### CODE REVIEW

**Comment by gandro** [comment]
Thanks for the PR. Please note that the helm README.md also needs to be re-generated: `make -C install/kubernetes`

**Comment by ayuspin** [comment]
@gandro thank you for looking into this, I regenerated helm README.md as suggested

**Review by sayboras — APPROVED** [review]
LGTM :heavy_check_mark:

**Review by gandro — APPROVED** [review]

**Pull request merged**
