### PR TITLE
Update codeowners for recent lb-ipam / ipalloc changes

### PR DESCRIPTION
**Pull request by joestringer**
- CODEOWNERS: Add ipalloc codeowners
- CODEOWNERS: Add lb-ipam docs review groups

Related: https://github.com/cilium/cilium/pull/26488

### CODE REVIEW

**Comment by joestringer** [comment]
These files shouldn't be left to tophat/docs-structure for review. CC @dylandreimerink if you have alternative proposals. Please also consider adding such entries for any newly introduced files in future.

**Review by tklauser — APPROVED** [review]
LGTM for @cilium/contributing

**Review by dylandreimerink — APPROVED** [review]
Ah, yes codeowners, should not forget those :sweat_smile:. This looks good to me!

**Review by tommyp1ckles — APPROVED** [review]

**Comment by dylandreimerink** [comment]
Code owners checks are passing, so going ahead and merging this one

**Pull request merged**
