### PR TITLE
bpf: Check if device exists when compiling progs

### PR DESCRIPTION
**Pull request by joestringer**
Check whether the relevant device exists at the start of the join_ep
script, and fail out early if it doesn't. There's no point compiling the
program for the endpoint if the corresponding device isn't there. While
it's still plausible that the device disappears during compilation, the
more likely case is that the endpoint has been deleted and Cilium is
starting back up and attempting to restore the endpoint, but the device
no longer exists so the BPF program attachment will fail anyway.

Fixes: #3935

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
I created a new PR for this change in an attempt to work around CI issues, it is here: #3959 .

Closing this PR.

**Pull request closed without merging**
