### PR TITLE
v1.9 backports 2020-11-30

### PR DESCRIPTION
**Pull request by aanm**
* #13923 -- doc: Link hubble metrics to L7 visibility (@mandarjog)
 * #14134 -- helm: fix usage of `hostPath` and add `hostPathType` in `extraHostPathMounts` (@errordeveloper)
 * #14135 -- checkpatch: update image tag to latest (@qmonnet)
 * #14112 -- endpoint: Add DebugPolicy option (@jrajahalme)
 * #14145 -- bugtool: Add lsmod (@joestringer)
 * #14104 -- helm: Correct nodeSelector values (@sayboras)
 * #14163 -- helm: Fix description for clustermesh (@joestringer)
 * #14182 -- cilium: disable bind-protection in kube-proxy free probe mode (@borkmann)
 * #13983 -- test: Use NFS by default in test VMs (@pchaigno)
 * #14090 -- hubble/parser: Always preserve datapath numeric identity (@gandro)
 * #14185 -- test: Avoid installing Cilium for K8sBandwidth if tests are skipped (@pchaigno)
 * #14171 -- daemon: Fix netns usage in kpr privileged unit tests (@brb)
 * #14110 -- fqdn: Delay ipcache upserts until policies have been updated (@jrajahalme)
 * #14165 -- test: use kubectl helper for cilium cleanup in upgrade tests (@fristonio)
 * #14141 -- bpf: Don't compile unused BPF sections (@pchaigno)
 * #14191 -- test: Avoid use of install with NFS (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13923 14134 14135 14112 14145 14104 14163 14182 13983 14090 14185 14171 14110 14165 14141 14191; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by aanm** [comment]
@jrajahalme @brb there were some minor conflicts in https://github.com/cilium/cilium/pull/14212/commits/d60dbd845868360aec11ca1a3be25adeb8658579 please take a 2nd look.

**Review by sayboras — APPROVED** [review]
LGTM for my commit 💯

**Review by gandro — APPROVED** [review]

**Comment by aanm** [comment]
test-backport-1.9

**Review by pchaigno — APPROVED** [review]
:+1: for my PRs.

**Review by brb — APPROVED** [review]
My changes LGTM, thanks.

**Review by fristonio — APPROVED** [review]
LGTM for my changes. :rocket:

**Review by qmonnet — APPROVED** [review]
> * #14135 -- checkpatch: update image tag to latest (@qmonnet)

Good, thank you.

**Review by joestringer — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]
Lookin' good on my part.

**Pull request merged**
