### PR TITLE
.github: bump version of cilium-cli to v0.16.0

### LINKED ISSUE #30990: CI: Conformance EKS: Installation and Connectivity Test (1.24, ca-west-1): [check-log-errors]: failed to obtain eni link list: interrupted system call
Happening fairly commonly in CI EKS pipeline. 

```
 [=] Test [check-log-errors] [65/65]
.........
  [-] Scenario [check-log-errors/no-errors-in-logs]
  [.] Action [check-log-errors/no-errors-in-logs/cilium-cilium-8049278400-1.ca-west-1.eksctl.io/kube-system/cilium-5x8dh (cilium-agent)]
  [.] Action [check-log-errors/no-errors-in-logs/cilium-cilium-8049278400-1.ca-west-1.eksctl.io/kube-system/cilium-5x8dh (config)]
  [.] Action [check-log-errors/no-errors-in-logs/cilium-cilium-8049278400-1.ca-west-1.eksctl.io/kube-system/cilium-5x8dh (mount-cgroup)]
  [.] Action [check-log-errors/no-errors-in-logs/cilium-cilium-8049278400-1.ca-west-1.eksctl.io/kube-system/cilium-5x8dh (apply-sysctl-overwrites)]
  [.] Action [check-log-errors/no-errors-in-logs/cilium-cilium-8049278400-1.ca-west-1.eksctl.io/kube-system/cilium-5x8dh (mount-bpf-fs)]
  [.] Action [check-log-errors/no-errors-in-logs/cilium-cilium-8049278400-1.ca-west-1.eksctl.io/kube-system/cilium-5x8dh (clean-cilium-state)]
  [.] Action [check-log-errors/no-errors-in-logs/cilium-cilium-8049278400-1.ca-west-1.eksctl.io/kube-system/cilium-5x8dh (install-cni-binaries)]
  [.] Action [check-log-errors/no-errors-in-logs/cilium-cilium-8049278400-1.ca-west-1.eksctl.io/kube-system/cilium-operator-844886dbf6-pxkpv (cilium-operator)]
  [.] Action [check-log-errors/no-errors-in-logs/cilium-cilium-8049278400-1.ca-west-1.eksctl.io/kube-system/cilium-pctck (cilium-agent)]
  ❌ Found 2 logs in cilium-cilium-8049278400-1.ca-west-1.eksctl.io/kube-system/cilium-pctck (cilium-agent) matching list of errors that must be investigated:
level=error msg="Timed out waiting for ENIs to be attached" attachedENIs="map[]" error="failed to obtain eni link list: interrupted system call" expectedENIs="map[]" subsys=ipam (1 occurrences)
level=error msg="Timed out waiting for ENIs to be attached" attachedENIs="map[]" error="failed to obtain eni link list: interrupted system call" expectedENIs="map[0e:b8:fe:46:45:dc:eni-0a4378a48ca6f8443]" subsys=ipam (1 occurrences)
```

Example(s):
* https://github.com/cilium/cilium/actions/runs/8049278400/job/21982337763
* https://github.com/cilium/cilium/actions/runs/8044897788/job/21969262001

Sysdump:
[cilium-sysdumps(40).zip](https://github.com/cilium/cilium/files/14412249/cilium-sysdumps.40.zip)

### PR DESCRIPTION
**Pull request by tommyp1ckles**
This release includes improved uninstall/cleanup command which should aleviate various issues when re-using clusters while re-running e2e tests.

Fixes: #30990 #30991 #30993

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]
lgtm btw renovate automatically updates this field https://github.com/cilium/cilium/pull/31171 🤖

**Comment by tommyp1ckles** [comment]
@michi-covalent Ah thought I would beat the robot 😄

**Pull request closed without merging**
