### PR TITLE
Set correct cluster name and id during upgrade test

### LINKED ISSUE #29108: CI: Conformance Ginkgo (f19-update) - found error endpoint regeneration failed
## CI failure

Hit on https://github.com/cilium/cilium/pull/29051
Link: https://github.com/cilium/cilium/actions/runs/6825486460/job/18563485231
Sysdump: [test_results-E2E Test (1.19, f19-update).tar.gz](https://github.com/cilium/cilium/files/13320815/test_results-E2E.Test.1.19.f19-update.tar.gz)

Seen on scheduled runs as well: 
* https://github.com/cilium/cilium/actions/runs/6808498669/job/18513085412
* https://github.com/cilium/cilium/actions/runs/6806188619/job/18507111511
* https://github.com/cilium/cilium/actions/runs/6802855511/job/18496939129

```
• Failure in Spec Teardown (AfterEach) [573.044 seconds]
K8sUpdates
/home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:461
  Tests upgrade and downgrade from a Cilium stable image to master [AfterEach]
  /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:515

  Found 1 k8s-app=cilium logs matching list of errors that must be investigated:
  2023-11-10T13:45:10.487646184Z level=error msg="endpoint regeneration failed" containerID=dc7fd23665 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1183 error="endpoint 1183 SecurityIdentity changed during policy regeneration" identity=6117 ipv4=10.0.1.80 ipv6= k8sPodName=default/app1-94b79fb5b-b27qq subsys=endpoint

  /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:413
------------------------------

Summarizing 1 Failure:

[Fail] K8sUpdates [AfterEach] Tests upgrade and downgrade from a Cilium stable image to master 
/home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:413
```

### PR DESCRIPTION
**Pull request by marseel**
Fixes #29108
more details in issue.

### CODE REVIEW

**Review by thorn3r — APPROVED** [review]
nice find!

**Review by aanm — APPROVED** [review]

**Comment by marseel** [comment]
I will mark it as ready-to-merge as both Maciej and Nicolas are out of office and this change only affects tests (also got two approvals)

**Comment by bimmlerd** [comment]
I've hit this on stable branches, any reason we couldn't backport this?

**Comment by marseel** [comment]
@bimmlerd I don't mind backporting. It was a long time ago, but I am assuming I haven't seen this error on other stable branches at that time :thinking:

**Comment by bimmlerd** [comment]
@marseel I guess there's not really a backporting criteria for CI fixes, but as a release manager I'd definitely enjoy seeing CI fixes trickle down

**Pull request merged**
