### PR TITLE
images: update gops using renovate bot

### PR DESCRIPTION
**Pull request by tklauser**
Example PR: https://github.com/tklauser/cilium/pull/490

### CODE REVIEW

**Review by nebril — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by sayboras** [comment]
Can you help to rebase? Thanks

**Comment by tklauser** [comment]
> Can you help to rebase? Thanks

Done, thanks.

**Comment by tklauser** [comment]
Image lint and smoke tests passed after rebase and approvals are in. No need to run full CI, marking as ready to merge.

**Pull request merged**
