### PR TITLE
v1.3 backports 2018-11-28

### PR DESCRIPTION
**Pull request by borkmann**
PR backported as follow-up recommendation to #6287:

- #6309

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6311)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Review by jrajahalme — APPROVED** [review]

**Comment by ianvernon** [comment]
Build timed out: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8255/flowGraphTable/

**Comment by ianvernon** [comment]
test-me-please

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-upstream-k8s

**Pull request merged**
