### PR TITLE
v1.13 backports 2023-02-16

### PR DESCRIPTION
**Pull request by pchaigno**
- [x] #23480 -- test: Update policy for hairpin flow validation (@aditighag)
 - [x] #23706 -- Fix RKE doc link (@raphink)
 - [x] #23501 -- gateway-api: Combine metrics registry with operator (@sayboras)
 - [ ] #23669 -- docs: replace usage of api.twitter.com (@kaworu)
 - [x] #23728 -- Remove / in RKE doc link as it causes redirect bug (@raphink)
 - [x] #23713 -- ipam/crd: Fix panic due to concurrent map read and map write (@gandro)
 - [ ] #23709 -- helm: Add support of annotations in hubble ui service (@brnck)
 - [x] #23740 -- workflow: fixes LLVM, Clang cache and install path (@brlbil)
 - [x] #23733 -- CI: Fixes flake in kubectl wait in CI (@meyskens)
     - Minor conflict because `.github/workflows/conformance-k8s-network-policies.yaml` doesn't exist in v1.13.
 - [x] #23620 -- Document exemplars option for hubble httpV2 metrics (@chancez)
 - [x] #23532 -- clustermesh: correctly remove remoteCache on connection disruption (@squeed)
     - Last commit wasn't backported given `.github/workflows/conformance-multicluster.yaml` doesn't exist in v1.13.
 - [x] #23743 -- daemon: ignore CILIUM_CUSTOM_CNI_CONF when writing cni configuration (@squeed)
 - [ ] #23343 -- test: Get rid of 4.9 pipeline (@brb)
 - [ ] #23641 -- Add CLI command to dump cgroups metadata (@alexkats)
 - [x] #23825 -- bpf,srv6: decouple bpf host routing from srv6 decap (@ldelossa)
 - [ ] #23446 -- Fix restoreServicesLocked() potential nil pointer panic (@dlapcevic)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 23480 23706 23501 23669 23728 23713 23709 23740 23733 23620 23532 23743 23343 23641 23825 23446; do contrib/backporting/set-labels.py $pr done 1.13; done
```

### CODE REVIEW

**Review by chancez — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-backport-1.13

**Review by nathanjsweet — APPROVED** [review]
lgtm for API

**Review by brlbil — APPROVED** [review]
Thanks, LGTM for CI

**Review by gandro — APPROVED** [review]

**Review by kaworu — APPROVED** [review]
My patches LGTM thanks @pchaigno

**Review by sayboras — APPROVED** [review]

**Comment by raphink** [comment]
RKE doc LGTM

**Review by aanm — APPROVED** [review]
LGTM for @cilium/github-sec

**Review by squeed — APPROVED** [review]

**Review by ldelossa — APPROVED** [review]
My changes look good

**Comment by pchaigno** [comment]
/test-1.19-4.9

**Comment by pchaigno** [comment]
I've created https://github.com/cilium/cilium/issues/23892 for the flake mentioned above, on k8s-1.19-kernel-4.9. Merging given the previous comment.

**Pull request merged**
