### PR TITLE
Make it easier to depend on clustermesh types outside of its package

### PR DESCRIPTION
**Pull request by giorio94**
Please refer to the respective commit descriptions for additional details.

### CODE REVIEW

**Comment by giorio94** [comment]
Rebased onto main to pick the fix for the CI test.

**Comment by giorio94** [comment]
Rebased onto main to resolve conflicts

**Review by marseel — APPROVED** [review]

**Comment by giorio94** [comment]
Hopefully this is the last time that this PR conflicts...

**Review by YutaroHayakawa — APPROVED** [review]

**Pull request merged**
