### PR TITLE
v1.15 Author Backports 2024-04-04 for Gateway API

### PR DESCRIPTION
**Pull request by sayboras**
* [x] #30686 (@cjvirtucio87)
 * [ ] #31292 (@chaunceyjiang)
 * [ ] #31361 (@chaunceyjiang)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30686 31292 31361
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.15

**Review by julianwiedmann — APPROVED** [review]
lgtm :rocket:. Do we want to wait for more review, or merge?

**Pull request merged**
