### PR TITLE
helm: loadBalancerClass for Cluster Mesh APIserver

### PR DESCRIPTION
**Pull request by PhilipSchmid**
* Added `loadBalancerClass` Helm value for the Cluster Mesh APIserver Kubernetes Service.
* Refactored the existing `loadBalancerIP` Helm value so it's clearer that it exists (instead of having it commented out in the values.yaml file).

```release-note
helm: loadBalancerClass for Cluster Mesh APIserver
```

### CODE REVIEW

**Comment by PhilipSchmid** [comment]
Let's please backport this to 1.15 :).

**Review by sayboras — APPROVED** [review]
Looks good for helm changes.

**Comment by PhilipSchmid** [comment]
Fixing https://github.com/cilium/cilium/actions/runs/9453106239/job/26037749772?pr=33033#step:5:602 in the next force-commit in a couple of minutes.

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
This looks more a feature than a bug fix but I'll leave it to @giorio94 to decide if we should backport it or not.

**Review by giorio94 — APPROVED** [review]
Thanks!

**Comment by giorio94** [comment]
> This looks more a feature than a bug fix but I'll leave it to @giorio94 to decide if we should backport it or not.

Hmm, I'm a bit on the fence honestly. I agree that the PR looks more as a feature than a bug fix, but on the other hand one may argue that the lack of this setting may prevent users from successfully deploying the clustermesh-apiserver in environments including multiple LB classes. Given that the change is straightforward, and has a very low risk of introducing regressions, I'd probably lean towards backporting it to v1.15 to be on the safe side (it is instead definitely not a serious enough issue to justify backporting to older stable versions).

**Comment by giorio94** [comment]
Sorry for retriggering the tests :crying_cat_face:, I missed that they had already been triggered.

**Comment by giorio94** [comment]
Rebased using the GH UI, hopefully that should fix the failing tests.

**Pull request merged**
