### PR TITLE
v1.16 Backports 2024-08-12

### PR DESCRIPTION
**Pull request by jschwinger233**
* [x] #33945 (@viktor-kurchenko)
 * [x] #34038 (@tommyp1ckles)
 * [x] #34071 (@tommyp1ckles)
 * [x] #34190 (@joestringer)
 * [x] #34137 (@youngnick)
 * [x] #33974 (@xtineskim)
 * [x] #34114 (@chancez) :warning: resolved conflicts
 * [x] #34105 (@jrajahalme)
 * [x] #34115 (@chancez)
 * [x] #34132 (@joestringer)
 * [x] #34151 (@joestringer)
 * [x] #34177 (@rastislavs) :warning: resolved conflicts
 * [x] #34100 (@sathieu)
 * [x] #34247 (@sayboras)
 * [x] #34233 (@chancez)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33945 34038 34071 34190 34137 33974 34114 34105 34115 34132 34151 34177 34100 34247 34233
```

### CODE REVIEW

**Review by viktor-kurchenko — APPROVED** [review]
Thanks!

**Comment by jschwinger233** [comment]
/test-backport-1.16

**Review by rastislavs — APPROVED** [review]
Thanks!

**Review by jrajahalme — APPROVED** [review]
OK for my PR :-)

**Review by chancez — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
Thanks :heavy_check_mark:

**Review by youngnick — APPROVED** [review]
✅ for both my change and wearing the tophat.

**Review by jrajahalme — APPROVED** [review]
Reviewed Tom's changes

**Comment by aanm** [comment]
/test-backport-1.16

**Pull request merged**
