### PR TITLE
operator/bgpv2: Fix CiliumBGPNodeConfig OwnerReference & job health reporting

### PR DESCRIPTION
**Pull request by rastislavs**
Fixes incorrect `APIVersion` in `CiliumBGPNodeConfig`'s `OwnerReference`, which makes k8s garbage collection work, and we can get rid of explicit cleanup code handling deletion of stale `CiliumBGPNodeConfigs`.

Also removes unnecessary health report from `initializeStores` This is not necessary as the jobs are automatically hooked into
health reporter ([here](https://github.com/cilium/cilium/blob/main/pkg/hive/job/job.go#L311-L312)).

Example of working k8s garbage collection with this change:
```
$ k get cbgpnode -o yaml  
apiVersion: v1
items:
- apiVersion: cilium.io/v2alpha1
  kind: CiliumBGPNodeConfig
  metadata:
    creationTimestamp: "2024-04-16T11:49:51Z"
    generation: 1
    name: clab-bgp-cplane-devel-control-plane
    ownerReferences:
    - apiVersion: cilium.io/v2alpha1
      kind: CiliumBGPClusterConfig
      name: tor
      uid: 80bdb609-f0ed-4050-9795-8beb68a4e91a
    resourceVersion: "2021"
    uid: e785877b-3c1e-4e89-bdd3-ef61404305af
  spec:
    bgpInstances:
    - localASN: 65001
      name: test-instance
      peers:
      - name: test-peer
        peerASN: 65000
        peerAddress: 172.0.0.1
  status: {}
kind: List
metadata:
  resourceVersion: ""
```

```
$ k delete CiliumBGPClusterConfig tor 
ciliumbgpclusterconfig.cilium.io "tor" deleted
```

```
$ k get cbgpnode -o yaml     
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""

```

### CODE REVIEW

**Review by harsimran-pabla — APPROVED** [review]
Thanks for the cleanup 🙏

**Review by YutaroHayakawa — APPROVED** [review]

**Pull request merged**
