### PR TITLE
cilium: per service algorithm follow-ups

### LINKED ISSUE #36112: cilium svc handling followups before 1.17
- [x] move algorithm field into affinity timeout (https://github.com/cilium/cilium/pull/35735#discussion_r1853845710)
- [x] helm support
- [x] kpr documentation update on use of algorithm
- [x] also mention the behavior of hostPort that it will use the global default given it's not a svc obj
- [x] small refactorings

### PR DESCRIPTION
**Pull request by borkmann**
(See commit desc)

Fixes: #36112

### CODE REVIEW

**Review by tklauser — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]
Changes look good to me :rocket:

**Review by ghost — APPROVED** [review]
docs good

**Review by aspsk — APPROVED** [review]
👍

**Review by nbusseneau — APPROVED** [review]
Trivial ack for Helm changes.

**Pull request merged**
