### PR TITLE
workflows: fix EKS encryption testing not using aws operator image

### PR DESCRIPTION
**Pull request by nbusseneau**
We missed this when merging #15669. Woops :D

### CODE REVIEW

**Review by aanm — APPROVED** [review]
nice catch

**Review by jrfastab — APPROVED** [review]
Thanks!

**Comment by jrfastab** [comment]
likely no reason to run test-me-* here because we only changed .workflows.

**Comment by nbusseneau** [comment]
> likely no reason to run test-me-* here because we only changed .workflows.

None at all. Just waiting for a `ci-structure` confirmation to mark as ready to merge...

**Pull request merged**
