### PR TITLE
[wip]daemon: prevent daemon init getting called by other binaries

### PR DESCRIPTION
**Pull request by nirmoy**
anything which is imported into the daemon package will  call init function from
daemon_main.go which is not disarable.

$ cilium debuginfo
level=info msg="Detected MTU 1500" subsys=mtu

Fixes:#6197
Signed-off-by: Nirmoy Das <ndas@suse.de>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6286)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
@nirmoy unit tests have failed:
```
daemon_test.go:168:
    e.DaemonSuite.SetUpTest(c)
daemon_test.go:105:
    c.Assert(err, IsNil)
... value *errors.errorString = &errors.errorString{s:"invalid daemon configuration: MTU '0' cannot be 0 or negative"} ("invalid daemon configuration: MTU '0' cannot be 0 or negative")
```

**Review by vadorovsky — CHANGES_REQUESTED** [review]
This fix (probably) works, but in my opinion it's not a good long-term solution.

The main problem is that we use `init` functions for (sub)command flags. And that we have the single Cilium binary defined in `daemon` package, which is not good, because we import modules related to CLI and monitor to the `daemon` package. In my opinion, the unified binary should be in completely separate module.

My proposition is to:
- create separate packages: `cmd/cilium-cli`, `cmd/cilium-agent`, `cmd/cilium-monitor`
- each of those packages implement Cobra commands
- Cobra/viper flags are initialized in functions like `NewCiliumCLICommand`, `NewCiliumAgentCommand` or whatever, but never in `init`
- create a separate package `cmd/cilium` for unified binary and keep it as the only place which can import the other `cmd/*` modules

**Comment by vadorovsky** [comment]
@nirmoy I talked with @nebril offline and he agrees with my proposition. Would you like to try to implement the unified binary that way?

**Comment by nirmoy** [comment]
@mrostecki  @nebril Thanks for suggesting that, seems better solution. I will work on it

**Comment by nirmoy** [comment]
closing! @mrostecki  will over take this

**Pull request closed without merging**
