### PR TITLE
images/builder: update protoc-gen-go-json from v1.0.0 to v1.1.0

### PR DESCRIPTION
**Pull request by rolinh**
This PR updates the `protoc-gen-go-json` dependency from v1.0.0 to v1.1.0.  This new version uses protojson instead of the deprecated jsonpb module. This means that code generated by this plugin does not depend on the deprecated github.com/golang/protobuf module anymore.

### CODE REVIEW

**Comment by rolinh** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Comment by rolinh** [comment]
test-me-please

**Comment by rolinh** [comment]
test-me-please

**Comment by rolinh** [comment]
test-runtime

**Pull request merged**
