### PR TITLE
gateway-api: Fix flaky conformance tests

### PR DESCRIPTION
**Pull request by sayboras**
### Description

The goal is to have unit tests for Conformance test cases for faster feedback and stability. As part of this PR, two flaky tests are fixed :crossed_fingers:.

### Testing

Testing was done in https://github.com/cilium/cilium/actions/runs/4402111837, which are having 20+ consecutive successful runs.

```release-note
gateway-api: Fix flaky conformance tests
```

### CODE REVIEW

**Comment by sayboras** [comment]
Full CI is not required, as the code changes are related to Gateway API/Ingress/Unit tests, which are verified as part of GHA.

**Review by brlbil — APPROVED** [review]
👍 for workflow changes

**Review by jrajahalme — APPROVED** [review]
LGTM

**Review by nbusseneau — APPROVED** [review]

**Comment by sayboras** [comment]
/test-1.16-4.19

**Comment by sayboras** [comment]
Above failure is fixed in https://github.com/cilium/cilium/pull/24336, which is just merged. Re-run is not required.

**Review by youngnick — APPROVED** [review]
LGTM, nice work @sayboras

**Pull request merged**
