### PR TITLE
hubble: distinguish AUDIT policy verdict from FORWARDED

### LINKED ISSUE #14692: Hubble verdict doesn't distinguish AUDIT from FORWARDED
## Bug report

**General Information**

- Cilium version v1.8.4
- Kernel version 4.19.118
- Orchestration system version in use K8S v1.17.3

**How to reproduce the issue**

1. Create a test server `pod1`, create a deny all ciliumnetworkpolicy that enforces on `pod1` ingress
2. Set `PolicyAuditMode` of the endpoint corresponding to the pod to `enabled`
```
cilium endpoint config $EP_ID PolicyAuditMode=enabled
```
3. start hubble observe
```
hubble observe --to-ip $POD1_IP
```
4. Access `pod1`, the `VERDICT` of hubble output is `FORWARDED`

IMHO, in this case, the `VERDICT` field (at least for `policy-verdict` event_type) should be `AUDIT` instead of `FORWARDED` so that we can adjust network policy base on audit verdict before actually dropping packets

### PR DESCRIPTION
**Pull request by jaffcheng**
This patch allows hubble to distinguish whether a packet is allowed
due to the audit mode or because it complies with the security policy.
Only affect events of type `policy-verdict` in L3/L4.

Fixes: #14692

~~#### Note: This PR is ready to be reviewed but requires the following to pass CI runtime tests:~~
~~1. The API changes in https://github.com/cilium/cilium/pull/14785 are bumped in cilium/hubble vendor~~
~~2. A new hubble CLI is released and shipped into test VM image~~

### CODE REVIEW

**Comment by rolinh** [comment]
Thanks @jaffcheng ! I've created https://github.com/cilium/hubble/pull/482 to pick up the API changes introduced with #14785.
Once merged, we can bump the Hubble CLI version in the test VM image.

**Comment by jaffcheng** [comment]
Rebased to pick up the vagrant box changes from https://github.com/cilium/cilium/pull/14982, this should be ready to be reviewed and tested.
Besides, looks like `Smoke Test with IPv6` is hitting this: https://github.com/cilium/cilium/issues/12279

**Comment by gandro** [comment]
test-me-please

**Review by gandro — APPROVED** [review]

**Comment by gandro** [comment]
All tests have passed. The reason why it's not marked as mergable is because the required tests have been renamed in the meantime.

**Comment by jaffcheng** [comment]
I think it's safe to remove `dont-merge/blocked` now.

**Review by nbusseneau — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
