### PR TITLE
docs: Update spelling list for toFQDNs rules

### PR DESCRIPTION
**Pull request by raybejjani**
These were missed, and have broken the docs build.

Fixes: https://github.com/cilium/cilium/commit/92224cece0f5f5b1677756c9bc9c529e8666e0ed ("docs: L3/7 toFQDNs documentation w/ matchPattern")

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6585)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-docs-please

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
Why did the doc CI not fail? Is it even testing the docs build?

**Comment by raybejjani** [comment]
The aanm test seems more stringent ;)

Oddly, I was running `make test-docs` and it had found other spelling mistakes. I'm not sure if I'm doing something wrong. aanm mentioned the docs build being disabled in dev vms, so maybe it does something different.

**Comment by raybejjani** [comment]
I'm going to merge this since I can't make it any worse

**Pull request merged**
