### PR TITLE
v1.5 backports 2019-09-06

### PR DESCRIPTION
**Pull request by aanm**
NOT BACKPORTED !!! @jrajahalme PTAL

 * #9049 -- test: Wait for at least one Istio POD to get ready (@jrajahalme)

BACKPORTED:
 * #9094 -- tofqdns: Allow "_" in DNS names to support service discovery schemes (@raybejjani)
 * #9097 -- bump k8s support to 1.15.3 (@aanm)
 * #9133 -- Dockerfile: Use Envoy image with access logging fixes (@jrajahalme)
 * #9101 -- test: fix k8s upstream test (@aanm)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 9094 9097 9133 9101; do contrib/backporting/set-labels.py $pr done 1.5; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9149)

### CODE REVIEW

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by ianvernon** [comment]
apt issues: https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/1556/execution/node/56/log/

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
