### PR TITLE
[v1.6] k8s: update k8s libraries to v1.16.11

### PR DESCRIPTION
**Pull request by aanm**
Also update k8s test versions to v1.16.11

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.6

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
Something went really wrong while provisioning.

**Comment by nebril** [comment]
```
17:04:20      k8s1-1.16: Reading state information...
17:04:20      k8s1-1.16: Some packages could not be installed. This may mean that you have
17:04:20      k8s1-1.16: requested an impossible situation or if you are using the unstable
17:04:20      k8s1-1.16: distribution that some required packages have not yet been created
17:04:20      k8s1-1.16: or been moved out of Incoming.
17:04:20      k8s1-1.16: The following information may help to resolve the situation:
17:04:20      k8s1-1.16: 
17:04:20      k8s1-1.16: The following packages have unmet dependencies:
17:04:21      k8s1-1.16:  kubelet : Conflicts: kubernetes-cni
```

**Comment by nebril** [comment]
restart-ginkgo

**Comment by aanm** [comment]
restart-ginkgo

**Comment by aanm** [comment]
restart-ginkgo

**Comment by aanm** [comment]
restart-ginkgo

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-missed-k8s

**Review by vadorovsky — APPROVED** [review]

**Pull request merged**
