### PR TITLE
v1.2 backports: 18-10-16

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:

* #5908
* #5909
* #5911
* #5912

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5916)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by tgraf** [comment]
k8s tests failed due to cilium not being deployed

**Comment by tgraf** [comment]
test-missed-k8s

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
Same failure as before. This was broken before this PR so I'm merging this PR to unblock further testing.

**Pull request merged**
