### PR TITLE
proxy: Create access log file and setup notifier at startup

### PR DESCRIPTION
**Pull request by rlenglet**
Move the access log file and notifier and metadata configuration
at daemon startup instead of when creating the first redirect, so
access logging is usable with sidecar proxies, for which Cilium
doesn't create redirects.

Signed-off-by: Romain Lenglet <romain@covalent.io>

### CODE REVIEW

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Checked manually that access logging and `cilium monitor -t l7` are still working as intended.

**Comment by tgraf** [comment]
Changes look good overall but there are a good bunch of cleanups and refactoring which are not needed for the stable branch. Please split this up into the change which fixes the actual issue and a follow-up for the cosmetic stuff which is unrelated and not needed to backport.

**Comment by rlenglet** [comment]
@tgraf OK, I've reduced this PR to the minimum.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
CI build passed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/2171/
Rebasing.

**Comment by rlenglet** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by eloycoto** [comment]
Backport: https://github.com/cilium/cilium/pull/3638

**Pull request merged**
