### PR TITLE
ci: update cilium-cli to v0.9.3

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
ci-aks

**Comment by tklauser** [comment]
ci-awscni

**Comment by tklauser** [comment]
ci-eks

**Comment by tklauser** [comment]
ci-gke

**Comment by tklauser** [comment]
ci-external-workloads

**Comment by tklauser** [comment]
All CI 3.0 tests passed, removing `DO NOT MERGE` commit and marking as ready for review.

AKS: https://github.com/cilium/cilium/actions/runs/1440654469
AWS-CNI: https://github.com/cilium/cilium/actions/runs/1440654466
EKS: https://github.com/cilium/cilium/actions/runs/1440655615
GKE: https://github.com/cilium/cilium/actions/runs/1440655943
External workloads: https://github.com/cilium/cilium/actions/runs/1440656694

**Review by nbusseneau — APPROVED** [review]

**Comment by nbusseneau** [comment]
PR changes were tested (see above) and this PR does not need to run any additional CI, marking as ready to merge.

**Pull request merged**
