### PR TITLE
[wip] Rename CEP.status field to .details

### PR DESCRIPTION
**Pull request by raybejjani**
We crashed kubeapiserver (https://github.com/cilium/cilium/issues/5085) so apparently something is wrong. This is a first attempt at renaming the field. I need to test:
- upgrade and downgrade for all supported k8s version
- GC of older/newer style CEP objects

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5100)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Review by eloycoto — APPROVED** [review]

**Pull request closed without merging**
