### PR TITLE
node: Remove the IPv6 prefix /96 constraint

### PR DESCRIPTION
**Pull request by brb**
This PR removes the IPv6 `/96` prefix constraint which allows cilium to be used with k8s in the dual-stack mode.

Previously, the DSR for IPv6 (aka the `--lb` feature) required the `--ipv6-range` to be /96. This was because the 113-128 bits of an IPv6 addr were used to store a global reverse NAT ID, and the rest was a unique Pod IPv6 addr.

As the `--lb` feature was removed, the constraint is no longer needed (the new DSR implementation leverages IPv6 extension field to store a SVC IP addr and port).

Tested manually with kubeadm (`kubeadm init --skip-phases=addon/kube-proxy --pod-network-cidr=10.217.0.0/16,fc22::/48 --service-cidr=10.96.0.0/16,fc44::/112 --feature-gates IPv6DualStack=true --apiserver-advertise-address=192.168.34.11`).

```release-note
Remove /96 IPv6 CIDR constraint which makes cilium to work in k8s dual-stack mode
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9777)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by joestringer — CHANGES_REQUESTED** [review]
If we still have (and use) `IPv6NodePrefixLen` then I'm assuming that the prefix must still be `/96` or shorter?

https://github.com/cilium/cilium/blob/131fb89d6092cc016d344277f1a8e0540a2658b5/pkg/node/node_address.go#L125-L129

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by brb** [comment]
> If we still have (and use) IPv6NodePrefixLen then I'm assuming that the prefix must still be /96 or shorter?

@joestringer Good question. This is for a different case when an IPv6 alloc range is derived from `--ipv4-range` and`--ipv6-cluster-alloc-cidr` (/64). The case is not used in the dual-stack mode.

I'm going to remove `defaults.IPv6NodePrefixLen` and hard-code the `96` prefix instead to make it less confusing.

**Comment by brb** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
