### PR TITLE
k8s: update k8s dependencies to 1.16.15

### PR DESCRIPTION
**Pull request by aanm**
Also update k8s testing versions to 1.16.15

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.6

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
test-backport-1.6

**Comment by aanm** [comment]
restart-ginkgo

**Comment by joestringer** [comment]
test-backport-1.6

**Comment by joestringer** [comment]
```
11:55:43      k8s1-1.12: Reading state information...
11:55:43      k8s1-1.12: E: Version '1.16.14*' for 'kubectl' was not found
```

**Comment by aanm** [comment]
test-backport-1.6

**Comment by aanm** [comment]
test-backport-1.6

**Comment by tklauser** [comment]
test-backport-1.6

**Comment by aanm** [comment]
test-backport-1.6

**Review by nebril — APPROVED** [review]

**Pull request merged**
