### PR TITLE
cilium: v1.11 backport for ipsec key rotation

### PR DESCRIPTION
**Pull request by jrfastab**
Backport of PR #27319

```upstream-prs
for pr in 27319; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Comment by ti-mo** [comment]
@jrfastab the title of the first commit is `[backport commit ]`, is that intended? We should always include upstream commit SHAs in backport commits as well, which doesn't seem to be the case here.

**Comment by joestringer** [comment]
We expect that for any fix on older branches, the following steps also take place:
- Propose and get the fix merged into `main`
- Update the commit messages in the backport to mention the backported commit sha from the official version in the `main` branch, unless the implementation needs to be completely different. `git log v1.11` should give a good sense for what the usual format for this in commit messages looks like.
- Update the PR description here to include the following stanza so that we can correlate PRs and generate release notes. Note the PRs section and the Cilium branch version at the end:
  ````
  ```upstream-prs
  for pr in xxxxx; do contrib/backporting/set-labels.py $pr done 1.11; done
  ```
  ````
  It's also helpful to directly mention the upstream PR so that reviewers can contrast/compare with the original proposed fix, and also to ensure that github breadcrumbs are placed on the original PR. If we ever trace down the main PR it can be helpful to understand which branches that PR got backported to, so we can see whether subsequent fixes also need to be backported further.
- Use `/test-backport-X.Y` to run CI

**Comment by jrfastab** [comment]
@ti-mo I did the backport before the main PR was merged so I didn't have a commit to add yet.  But yes will have one.

**Comment by jrfastab** [comment]
/test-backport-1.11

**Comment by jrfastab** [comment]
@joestringer That 1.18-kernel-4.9 test failure looks unrelated to the patches. Also added upstream commits now that we have upstream PR merged.

**Comment by jrfastab** [comment]
/test-1.18-4.9

**Review by joestringer — APPROVED** [review]
Ack on behalf of tophat

**Pull request merged**
