### PR TITLE
v1.14 backports 2023-07-31

### PR DESCRIPTION
**Pull request by sayboras**
- [x] #27091 -- docs: kpr: remove caveat about XDP + tunnel performance (@julianwiedmann)
 - [ ] #26880 -- Documentation: fix the broken links/dead links (@vipul-21)
 - [x] #27015 -- bpf: l4lb: fix IPIP health-check path (@julianwiedmann)
 - [x] #26809 -- docs/ipsec: Extend troubleshooting for long key rotations (@pchaigno)
 - [ ] #25324 -- operator: Adjust CiliumEndpoint GC to only run once in kvstore mode (@learnitall)
 - [x] #27158 -- .github: rebuild ginkgo tests in case of cache miss (@sayboras)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 27091 26880 27015 26809 25324 27158; do contrib/backporting/set-labels.py $pr done 1.14; done
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.14

**Review by julianwiedmann — APPROVED** [review]

**Review by brlbil — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by learnitall — APPROVED** [review]
Looks good thank you!

**Comment by sayboras** [comment]
/test-backport-1.14

**Comment by sayboras** [comment]
Closed in favour of https://github.com/cilium/cilium/pull/27190, which is the same but without forked repo, so that the fix for conformance-runtime can be picked up.

**Pull request closed without merging**
