### PR TITLE
[v1.12] vagrant: Bump 4.9 Vagrant box (Linux 4.9.326, to fix a kernel bug)

### PR DESCRIPTION
**Pull request by tklauser**
Manual backport of #21106 to `v1.12` because #20288 is hit on tests using kernel 4.9 on that branch as well.

[ upstream commit 07e7fb0073ab387108ac6b4c126df1a34e36d5d2 ]

(Backporters note: only update the v4.9 image, not the cilium-dev image
 because version 232 also contains an updated Go version, i.e. 1.19
 instead of 1.18 still used on the v1.12 branch. This is fine for VM
 images used in tests because they use CI images built by GH actions
 using the proper Go version for the branch.)

We have been hitting a kernel bug on 4.9 for the verifier tests. An underflow on the memlock rlimit counter, caused by the reallocation of BPF programs not updating the charged values, makes the counter go under zero and convert into a huge value, blocking all further loads of BPF objects [0].

This has been fixed in kernel 4.10 [1], and was backported at last in 4.9.326. We generated a new Ubuntu image based on that, let's update.

[0] #20288
[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=5ccb071e97fbd9ffe623a0d3977cc6d013bee93c

### CODE REVIEW

**Comment by tklauser** [comment]
/test-1.16-4.9

**Comment by tklauser** [comment]
/test-1.17-4.9

**Comment by tklauser** [comment]
/test-1.18-4.9

**Comment by tklauser** [comment]
/test-1.19-4.9

**Comment by tklauser** [comment]
/test-1.20-4.9

**Comment by tklauser** [comment]
/test-1.21-4.9

**Comment by tklauser** [comment]
/test-1.22-4.9

**Review by qmonnet — APPROVED** [review]
Ack, thank you!

**Review by pchaigno — APPROVED** [review]

**Comment by tklauser** [comment]
/test-1.17-4.9

**Comment by tklauser** [comment]
/test-1.19-4.9

**Comment by tklauser** [comment]
All 4.9 tests passed. Marking as ready to merge.

**Pull request merged**
