### PR TITLE
[WIP] bpf: Support multiple xdp progs per interface

### PR DESCRIPTION
**Pull request by wenlxie**
This is used to support multiple xdp programs to be attached to one interface. User can use this feature to integrate with other xdp programs.

CFP: https://github.com/cilium/cilium/issues/28509

### CODE REVIEW

**Comment by wenlxie** [comment]
Kernel patches needed: 
https://github.com/torvalds/linux/commit/4a9c7bbe2ed4d2b240674b1fb606c41d3940c412
https://github.com/torvalds/linux/commit/f858c2b2ca04fc7ead291821a793638ae120c11d
https://github.com/torvalds/linux/commit/1c123c567fb138ebd187480b7fc0610fcb0851f5

**Comment by wenlxie** [comment]
@ti-mo @borkmann  I did a rough implementation for support of multiple programs per interface according to suggestions https://github.com/cilium/ebpf/discussions/940. 

Thanks for the details that provided https://github.com/cilium/cilium/issues/28509 

Before kernel supports for multiple programs (This could take long time), could we use this as an alternative way to support this?

**Review by borkmann — CHANGES_REQUESTED** [review]
Hello 👋 , I don't think this is the right approach. We need to work on bpf_mprog support for XDP instead, then we will have a uniform attach API for all of tcx, XDP, netkit in Cilium. See also my talk at netconf :

https://netdev.bots.linux.dev/netconf/2023/index.html

We need to wait until the upstream kernel has support for it, so that we have the right architectural foundation for multi-prog XDP. Thank you.

**Comment by wenlxie** [comment]
> Hello 👋 , I don't think this is the right approach. We need to work on bpf_mprog support for XDP instead, then we will have a uniform attach API for all of tcx, XDP, netkit in Cilium. See also my talk at netconf :
> 
> https://netdev.bots.linux.dev/netconf/2023/index.html
> 
> We need to wait until the upstream kernel has support for it, so that we have the right architectural foundation for multi-prog XDP. Thank you.

@borkmann thanks for check.
Looks like the multi program api had already supported in kernel 6.6
What is the gap for it to works for XDP? 
I know that code  need to be  changed in nic drivers, but any other gap?

**Comment by wenlxie** [comment]
> https://netdev.bots.linux.dev/netconf/2023/index.html

@borkmann  One scenario for this feature that I want to mention is:

Currently I want to run multiple xdp programs with:

xdpcap to get the packets before cilium xdp program ---> cilium xdp program ----> xdpcap to get the packets after cilium xdp program

The xdp action should be the action from cilium xdp program, but not the action  from the last xdpcap xdp programs. 

Does current multiple programs API supports this requirement?

**Comment by borkmann** [comment]
> > https://netdev.bots.linux.dev/netconf/2023/index.html
> 
> @borkmann One scenario for this feature that I want to mention is:
> 
> Currently I want to run multiple xdp programs with:
> 
> xdpcap to get the packets before cilium xdp program ---> cilium xdp program ----> xdpcap to get the packets after cilium xdp program
> 
> The xdp action should be the action from cilium xdp program, but not the action from the last xdpcap xdp programs.
> 
> Does current multiple programs API supports this scenario?

Cilium does have a pcap recorder feature for XDP that is built into the agent + hubble, and shows packets when the come in before Cilium's L4LB is executed and when they get out after Cilium's L4LB mangled them. Did you try that feature?

**Comment by wenlxie** [comment]
> > > https://netdev.bots.linux.dev/netconf/2023/index.html
> > 
> > 
> > @borkmann One scenario for this feature that I want to mention is:
> > Currently I want to run multiple xdp programs with:
> > xdpcap to get the packets before cilium xdp program ---> cilium xdp program ----> xdpcap to get the packets after cilium xdp program
> > The xdp action should be the action from cilium xdp program, but not the action from the last xdpcap xdp programs.
> > Does current multiple programs API supports this scenario?
> 
> Cilium does have a pcap recorder feature for XDP that is built into the agent + hubble, and shows packets when the come in before Cilium's L4LB is executed and when they get out after Cilium's L4LB mangled them. Did you try that feature?
> 
> Slide 53 onwards, incl. demo: https://lpc.events/event/11/contributions/953/attachments/867/1658/LPC_2021_BPF_Datapath_Extensions.pdf



> > > https://netdev.bots.linux.dev/netconf/2023/index.html
> > 
> > 
> > @borkmann One scenario for this feature that I want to mention is:
> > Currently I want to run multiple xdp programs with:
> > xdpcap to get the packets before cilium xdp program ---> cilium xdp program ----> xdpcap to get the packets after cilium xdp program
> > The xdp action should be the action from cilium xdp program, but not the action from the last xdpcap xdp programs.
> > Does current multiple programs API supports this scenario?
> 
> Cilium does have a pcap recorder feature for XDP that is built into the agent + hubble, and shows packets when the come in before Cilium's L4LB is executed and when they get out after Cilium's L4LB mangled them. Did you try that feature?
> 
> Slide 53 onwards, incl. demo: https://lpc.events/event/11/contributions/953/attachments/867/1658/LPC_2021_BPF_Datapath_Extensions.pdf

@borkmann  Thanks for that

I had tried it.
 
The reason why I am trying to use xdpcap is:
1) Cilium pcap recorder is not early enough. I am afraid that it may miss some packets
2) tcpdump syntax support
3) Our cilium xdp runs with Geneve or IPIP tunnel enabled, it is better to support to capture packets based on Geneve VNI, IPIP inner ip etc.

**Comment by dylandreimerink** [comment]
> The reason why I am trying to use xdpcap is:
>
> * Cilium pcap recorder is not early enough. I am afraid that it may miss some packets
> * tcpdump syntax support
> * Our cilium xdp runs with Geneve or IPIP tunnel enabled, it is better to support to capture packets based on Geneve VNI, Geneve options, IPIP inner ip etc.

I think these are valid reasons, similar uses cases were the reason for introducing TCX into the kernel. However, I think most Cilium maintainers/committers don't see a future in this libxdp like multi program approach.

> We need to wait until the upstream kernel has support for it, so that we have the right architectural foundation for multi-prog XDP. Thank you.

Given this, I think we can close out this PR and move any further discussion / coordination for future steps to an issue.

**Pull request closed without merging**
