### PR TITLE
1.2 backports 19-01-02

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:

* #6502 

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6529)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
@joestringer the local node NodePort test failed: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8709/
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1436/

**Comment by ianvernon** [comment]
test-me-please

**Comment by joestringer** [comment]
High level guess, there has been another change in 1.3 or later that improved nodeport access support which this fix was relying upon, and we're missing that commit in the 1.2 branch.

**Comment by joestringer** [comment]
Looks like it's an issue with the path from k8s1 node into the nodeport on k8s1, when the connection is loadbalanced to the service on k8s2:

(Monitoring from k8s2)
```
-> endpoint 23554 flow 0x1102ade5 identity 1->19586 state new ifindex lxc18fb8: 10.0.2.15:56052 -> 10.10.1.112:80 tcp SYN
<- endpoint 23554 flow 0x241f3af5 identity 19586->0 state new ifindex 0: 10.10.1.112:80 -> 10.0.2.15:56052 tcp SYN, ACK
-> stack flow 0x241f3af5 identity 19586->3 state reply ifindex 0: 10.10.1.112:80 -> 10.0.2.15:56052 tcp SYN, ACK
-> 0: 10.10.1.112:80 -> 10.0.2.15:56052 tcp SYN, ACK
-> endpoint 23554 flow 0x1102ade5 identity 1->19586 state established ifindex lxc18fb8: 10.0.2.15:56052 -> 10.10.1.112:80 tcp RST
```

Compare with Cilium v1.3.2, which works (it already includes this backport):

```
# cilium monitor --related-to 23554
Press Ctrl-C to quit
-> endpoint 23554 flow 0x4f6e7c54 identity 1->19586 state new ifindex lxc18fb8: 10.10.0.1:33066 -> 10.10.1.112:80 tcp SYN
<- endpoint 23554 flow 0x4a6dd68a identity 19586->0 state new ifindex 0: 10.10.1.112:80 -> 10.10.0.1:33066 tcp SYN, ACK
-> overlay flow 0x4a6dd68a identity 19586->0 state new ifindex cilium_vxlan: 10.10.1.112:80 -> 10.10.0.1:33066 tcp SYN, ACK
-> endpoint 23554 flow 0x4f6e7c54 identity 1->19586 state established ifindex lxc18fb8: 10.10.0.1:33066 -> 10.10.1.112:80 tcp ACK
-> endpoint 23554 flow 0x4f6e7c54 identity 1->19586 state established ifindex lxc18fb8: 10.10.0.1:33066 -> 10.10.1.112:80 tcp ACK
<- endpoint 23554 flow 0x4a6dd68a identity 19586->0 state new ifindex 0: 10.10.1.112:80 -> 10.10.0.1:33066 tcp ACK
-> overlay flow 0x4a6dd68a identity 19586->0 state new ifindex cilium_vxlan: 10.10.1.112:80 -> 10.10.0.1:33066 tcp ACK
<- endpoint 23554 flow 0x4a6dd68a identity 19586->0 state new ifindex 0: 10.10.1.112:80 -> 10.10.0.1:33066 tcp ACK
-> overlay flow 0x4a6dd68a identity 19586->0 state new ifindex cilium_vxlan: 10.10.1.112:80 -> 10.10.0.1:33066 tcp ACK
-> endpoint 23554 flow 0x4f6e7c54 identity 1->19586 state established ifindex lxc18fb8: 10.10.0.1:33066 -> 10.10.1.112:80 tcp ACK
-> endpoint 23554 flow 0x4f6e7c54 identity 1->19586 state established ifindex lxc18fb8: 10.10.0.1:33066 -> 10.10.1.112:80 tcp ACK, FIN
<- endpoint 23554 flow 0x4a6dd68a identity 19586->0 state new ifindex 0: 10.10.1.112:80 -> 10.10.0.1:33066 tcp ACK, FIN
-> overlay flow 0x4a6dd68a identity 19586->0 state new ifindex cilium_vxlan: 10.10.1.112:80 -> 10.10.0.1:33066 tcp ACK, FIN
-> endpoint 23554 flow 0x4f6e7c54 identity 1->19586 state established ifindex lxc18fb8: 10.10.0.1:33066 -> 10.10.1.112:80 tcp ACK
```

**Comment by joestringer** [comment]
I haven't managed to narrow down why it is that the k8s1 node decides to SNAT the traffic to `10.0.2.15`. The only commit that I found so far that seems related and is not already backported to v1.2 is e2bb2b7cbbc56b666a2fffd26bf97044b75f5bd4, but as far as I can tell it doesn't fix the issue.

Verbose `cilium monitor` appears to be this from k8s1 viewpoint, so the packet already has this source IP when it arrives into Cilium. This is a problem because the same IP is configured on k8s2, which is why the response never gets routed back to k8s1:

```
CPU 01: MARK 0xb5bf9ed1 FROM 0 from-host: 74 bytes, state new, identity 1->0
Ethernet        {Contents=[..14..] Payload=[..62..] SrcMAC=7e:f9:57:85:93:ac DstMAC=7e:f9:57:85:93:ac EthernetType=IPv4 Length=0}                                                                                                                             
IPv4    {Contents=[..20..] Payload=[..40..] Version=4 IHL=5 TOS=0 Length=60 Id=47844 Flags=DF FragOffset=0 TTL=64 Protocol=TCP Checksum=26703 SrcIP=10.0.2.15 DstIP=10.10.1.112 Options=[] Padding=[]}                                                        
TCP     {Contents=[..40..] Payload=[] SrcPort=53504 DstPort=80(http) Seq=3001842597 Ack=0 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=43690 Checksum=6071 Urgent=0 Options=[..5..] Padding=[]}
CPU 01: MARK 0xb5bf9ed1 FROM 0 DEBUG: Failed to map daddr=10.0.2.15 to identity                                                                                                                                                                               
CPU 01: MARK 0xb5bf9ed1 FROM 0 DEBUG: Reverse proxy lookup sport=80 dport=53504 saddr=10.10.1.112 nexthdr=6                                                                                                                                                   
CPU 01: MARK 0xb5bf9ed1 FROM 0 DEBUG: Encapsulating to node 3232244748 (0xc0a8240c) from seclabel 1                                                                                                                                                           
------------------------------------------------------------------------------                                                                                                                                                                                
CPU 01: MARK 0xb5bf9ed1 FROM 0 to-overlay: 74 bytes, state new, interface cilium_vxlan, identity 1->0
Ethernet        {Contents=[..14..] Payload=[..62..] SrcMAC=7e:f9:57:85:93:ac DstMAC=1a:c3:2a:54:71:f1 EthernetType=IPv4 Length=0}                                                                                                                             
IPv4    {Contents=[..20..] Payload=[..40..] Version=4 IHL=5 TOS=0 Length=60 Id=47844 Flags=DF FragOffset=0 TTL=64 Protocol=TCP Checksum=26703 SrcIP=10.0.2.15 DstIP=10.10.1.112 Options=[] Padding=[]}                                                        
TCP     {Contents=[..40..] Payload=[] SrcPort=53504 DstPort=80(http) Seq=3001842597 Ack=0 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=43690 Checksum=6071 Urgent=0 Options=[..5..] Padding=[]}
```

**Comment by joestringer** [comment]
This feature in #6482 never worked in 1.2 series, so it's more like missing functionality than a regression. We agreed in this morning's Cilium meeting that unless there is someone asking for this, it's not worth backporting. Users can upgrade to the latest v1.3 series release or later to support that use case.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Pull request merged**
