### PR TITLE
Fix v1.7.7 upgrade, add flags to help hitless upgrade from v1.6.x to v1.7.x

### PR DESCRIPTION
**Pull request by joestringer**
Two changes:
* Remove the interaction between `--enable-remote-node-identity` and `--allow-host-src`
* Split `--allow-host-src` into one flag for the receive side (allow from host) and a new flag for transmit side (`--transmit-host-src`) to determine which identity to transmit towards other nodes.

This PR reworks the handling of remote-node identity to be controlled via three separate flags:

* `--allow-host-src`: Allows traffic from nodes that report the traffic as from the host identity, such as v1.6.x or earlier.
* `--transmit-host-src`: Sends traffic towards other nodes with the source identity host, to ensure that 1.6.x nodes will accept traffic from this node during transition.
* `--enable-remote-node-identity`: Treat network policy that allows from host identity to also allow from remote-node identity (ie remote hosts). This provides network policy compatibility with v1.6.x behaviour.

By default to facilitate smooth upgrade from v1.7.x to v1.7.y with `--enable-remote-node-identity=false`, v1.7.9 or later will transmit traffic from the local node towards other nodes with the "remote-node" identity, as v1.7.7 or earlier did.

Furthermore, when performing an upgrade from v1.6.x to v1.7.x, the following steps should be taken to prevent datapath outage:

1. Upgrade to Cilium v1.7.x with `--transmit-host-src=true`, `--allow-host-src=true` and `--enable-remote-node-identity=false`. This ensures that traffic from v1.6.x with source identity host will be accepted by v1.7.x nodes; v1.7.x nodes will transmit with source identity host so that v1.6.x nodes will accept the traffic; and that no network policy change is required to support this transition.
1. Reconfigure Cilium v1.7.x to disable `--transmit-host-src`. Traffic will still be accepted from other v1.7.x nodes if sent from the host identity, but after this configuration step all nodes will transmit the remote-node identity.
1. Reconfigure Cilium v1.7.x to disable `--allow-host-src`. After step 2, no node should be transmitting the source identity so there is no need to accept traffic from remote nodes with this src.
1. Adapt network policy to ensure that traffic from remote nodes is explicitly allowed in the policy, eg via "fromEntities" policy that matches on the remote-node identity.
1. Finally, configure --enable-remote-node-identity=true. This will mean that traffic from remote nodes is not automatically allowed unless explicitly declared in the policy from step 4.

Users who are not concerned about temporary datapath outage during upgrade from v1.6.x to v1.7.x may compress steps 1-3 by simply configuring `--enable-remote-node-identity=false` per the [v1.7.x upgrade guide](https://docs.cilium.io/en/v1.8/install/upgrade/#configmap-remote-node-identity).

Steps (1) and (2) are intended to be required during v1.7.x upgrade cycle. Step (3) is recommended but would be automatically adopted during v1.8.x upgrade. Steps (4) and (5) are also recommended but require user input to take effect.

### CODE REVIEW

**Review by christarazi — APPROVED** [review]
LGTM! Great explanation in the commit msgs.

**Review by aanm — APPROVED** [review]
Doesn't this require changes in the upgrade notes?

**Review by tgraf — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
> Reconfigure Cilium v1.7.x to disable --allow-host-src. After step 2, no node should be transmitting the source identity so there is no need to accept traffic from remote nodes with this src.

I think we either need to make this step mandatory or we need to recognize (and null) `--allow-host-src` in v1.8. Otherwise, Cilium agent may fail to start for users who skipped this step and still have `--allow-host-src` when upgrading to v1.8.

**Comment by pchaigno** [comment]
Downgrade from v1.7.9+ to v1.6.x would require the reverse of steps stated above:
1. Reconfigure Cilium v1.7.9+ to enable `--allow-host-src`.
1. Reconfigure Cilium v1.7.9+ to enable `--transmit-host-src`.
1. Downgrade to Cilium v1.6.x.

Probably doesn't need to be documented, but upgrade from v1.7.8 to v1.7.9+ with `enable-remote-node-identity=false` will also require two steps:
1. Upgrade to Cilium v1.7.9+ with `--allow-host-src=true`.
1. Reconfigure Cilium v1.7.9+ to disable `--allow-host-src`.

All other upgrade/downgrade paths to/from 1.7.9+ I could think of are already covered or don't require anything special.

**Comment by joestringer** [comment]
test-backport-1.7

**Comment by joestringer** [comment]
Lucky us, regular gingko run hit three flakes: #12994 , #12777, #12776 :
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19899/#showFailuresLink

Will ignore the known flakes here.

**Pull request merged**
