### PR TITLE
v1.1 Backports 18-10-05

### PR DESCRIPTION
**Pull request by jrfastab**
PR#:
https://github.com/cilium/cilium/pull/5732 [backport note: dropped tests due to conflicts with missing pkgs and wanted to avoid pulling in multiple patches]

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5810)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by tgraf** [comment]
Need to pull in https://github.com/cilium/cilium/pull/5816 to not cause regression

EDIT: After discussion with @aanm. Backport is not critical

**Review by tgraf — APPROVED** [review]

**Pull request merged**
