### PR TITLE
removed depreacted calls and added nolint for strings.Title

### PR DESCRIPTION
**Pull request by ygxio**
1) Removed deprecated calls.
2) Added nolint for strings.Title

Related: #32274
@nathanjsweet @joestringer

### CODE REVIEW

**Review by chancez — APPROVED** [review]
LGTM on the Hubble related changes (switching to `assert.EqualExportedValues`)

**Comment by yogesh1801** [comment]
@derailed can you please merge this PR?

**Review by ldelossa — APPROVED** [review]

**Review by derailed — APPROVED** [review]
@yogesh1801 Thank you for this update!

**Comment by yogesh1801** [comment]
@derailed @chancez @ldelossa can this PR be merged?

**Review by sayboras — APPROVED** [review]
Looks  good to me for operator related files.

**Comment by ldelossa** [comment]
@yogesh1801 you have a failing lint: https://github.com/cilium/cilium/actions/runs/9399440819/job/25920415439?pr=32936

**Comment by yogesh1801** [comment]
@ldelossa I have fixed the typo in title of the PR and checked it locally also rebased it with main, can you please check and run the required tests again for approvals

Thank you!!

**Comment by yogesh1801** [comment]
@ldelossa some checks still failed, can't figure out the reason, can you help me out?

**Review by doniacld — APPROVED** [review]
lgtm!

**Comment by ldelossa** [comment]
The remaining e2e test failure is unrelated to the PR. Marking ready to merge.

**Pull request merged**
