### PR TITLE
cilium-dbg: remove section with unknown health status.

### PR DESCRIPTION
**Pull request by tommyp1ckles**
The "unknown" status simply refers to components that accept a health reporter scope, but have not declared their state as being either "ok" or degraded.

This is a bit confusing, as this does not necessarily mean any problems with Cilium.

In the future we may want to rework this state to distinguish between unreported states and components that are "timing-out" reconciling a desired state.

This PR simply removes displaying this information in `cilium-dbg status`

```release-note
Remove confusing "unknown" health status for cilium-dbg status output
```

### CODE REVIEW

**Review by thorn3r — APPROVED** [review]
This makes sense to me if the modules are expected to report either 'ok' or 'degraded' soon after

**Comment by tommyp1ckles** [comment]
Hit known flake [here](https://github.com/cilium/cilium/actions/runs/8059399223/job/22013754461)... rebasing/rerunning.

**Pull request closed without merging**
