### PR TITLE
Ginkgo: Updated vagrant box to 0.0.4

### PR DESCRIPTION
**Pull request by eloycoto**
- Updated vagrant box to Ubuntu 17.10

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

Related to https://github.com/cilium/packer-ci-build/pull/7

### CODE REVIEW

**Comment by eloycoto** [comment]
test-all-ginkgo

**Comment by eloycoto** [comment]
test-all-ginkgo

**Comment by eloycoto** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by eloycoto** [comment]
@ianvernon  This includes the PR:  https://github.com/cilium/packer-ci-build/pull/7 and it's using the new image.

**Review by tgraf — APPROVED** [review]

**Pull request merged**
