### PR TITLE
deps: update etcd to v3.4.0

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9104)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Review by vadorovsky — APPROVED** [review]

**Comment by ianvernon** [comment]
@aanm can you clarify on why this needs backporting?

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
> @aanm can you clarify on why this needs backporting?

@ianvernon v3.4 fixes the issue where etcd client stops working if the connectivity with first endpoint fails.

**Pull request merged**
