### PR TITLE
v1.10 backports 2022-01-30

### PR DESCRIPTION
**Pull request by glibsm**
* #17988 -- contrib: Fix backport submission for own PRs (@joestringer)
NOTE: I had to skip two commits, as it seemed they touched code not part of the 1.10 branch.
```
SKIPPED
     |  cd7df97b26cdf5450be4ca9bc83a35ba51faeb66 via d4739ad757d8d84dd65302e0e85e985b51198d69 ("test: Clean up after each graceful termination test")
     |  589c215fd962e7ac2fbd445e9372354c8ccf5181 via 30a6d9091d3c224a34bdea2a27e263a6f029020d ("test: Clean up pods after deleting them")
```
 * #18024 -- doc: getting started minor fixes (@kaworu)
 * #18553 -- metrics: Expose xfrm stats in prometheus (@sayboras)
 * #18627 -- test/runtime: fix flake on non-ready endpoints (@tklauser)
 * #18448 -- test: Fix pod cleanup after various tests (@joestringer)
 * #18636 -- datapath: Only unload obsolete XDP when attached (@jaffcheng)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 17988 18024 18553 18627 18448 18636; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
seems like we didn't maintain CODEOWNER granularly in v1.10 branch. Looks good for my commits, and thanks 💯.

**Comment by glibsm** [comment]
> seems like we didn't maintain CODEOWNER granularly in v1.10 branch. Looks good for my commits, and thanks 💯.

@sayboras that stumped me at first as well, but it turns out it's part of the release process. For example see the following: https://github.com/cilium/cilium/commit/97daf5622197d0cdda003a3f693e6e5a61038884#diff-fcf14c4b7b34fe7a11916195871ae66a59be87a395f28db73e345ebdc828085b

I noticed that your commit was backported to 1.11 but I think it should have been dropped, actually 🤔

**Review by tklauser — APPROVED** [review]
My change looks good, thanks.

**Review by kaworu — APPROVED** [review]
Thanks! LGTM for my commits.

**Comment by glibsm** [comment]
/test-backport-1.10

**Review by joestringer — APPROVED** [review]
Thanks, backports of my PRs look good.

Commit  cd7df97b26cdf5450be4ca9bc83a35ba51faeb66 ("test: Clean up after each graceful termination test") is expected to be skipped, new test.
Commit 589c215fd962e7ac2fbd445e9372354c8ccf5181  ("test: Clean up pods after deleting them") could potentially help some CI stability but probably needs to be reworked for v1.10 if we are worried about it. Though I'm not sure whether it's mitigating long-term issues that have been in the tree in v1.10, or if it's mitigating issues introduced in the v1.11 dev cycle. Either way, I think that it is an independent change from the others that have been backported, so safe to skip for now.

If you see problems in the CI reports around pods still in terminating state, or pods failed to come up, that sort of thing, then feel free to ping me and I can look at whether it seems familiar given that PR, and come up with suggestions.

**Comment by glibsm** [comment]
/test-backport-1.10

**Comment by glibsm** [comment]
/test-backport-1.10

**Comment by joamaki** [comment]
/test-backport-1.10

**Comment by joamaki** [comment]
/ci-eks-1.10

**Comment by joamaki** [comment]
timeout on the EKS test which was successful on previous round prior to rebase. historically looks like that test has not been very flaky.

**Review by joamaki — APPROVED** [review]

**Pull request merged**
