### PR TITLE
bpf, nodeport: add nodeport flag to nodeport services

### PR DESCRIPTION
**Pull request by borkmann**
See commit msg. /cc @brb

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9857)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Review by brb — APPROVED** [review]
LGTM!
/cc @gandro -- the LB BPF maps now will store a flag which indicates whether a SVC is of the NodePort type.

**Pull request merged**
