### PR TITLE
envoy: Bump envoy version to v1.23.7

### PR DESCRIPTION
**Pull request by sayboras**
Upstream release https://github.com/envoyproxy/envoy/releases/tag/v1.23.7

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.13

**Comment by sayboras** [comment]
/test-backport-1.13

**Comment by sayboras** [comment]
/test-backport-1.13

**Comment by sayboras** [comment]
/test-backport-1.13

**Comment by sayboras** [comment]
/test-1.17-4.9

**Comment by sayboras** [comment]
test-1.19-4.9

**Comment by sayboras** [comment]
/test-1.20-4.9

**Comment by sayboras** [comment]
/test-1.23-4.9

**Comment by sayboras** [comment]
/test-1.18-4.9

**Comment by sayboras** [comment]
/test-1.19-4.9

**Review by squeed — APPROVED** [review]

**Comment by sayboras** [comment]
/test-1.24-4.9

**Comment by sayboras** [comment]
There is an issue with MLH, so Mergeability job is stuck. ingress-conformance-test is renamed and split to below jobs

 https://github.com/cilium/cilium/actions/runs/4615996093/jobs/8160467146?pr=24746
 https://github.com/cilium/cilium/actions/runs/4615996093/jobs/8160467008?pr=24746
 
 All other jobs are successfully run, marking this ready to merge.

**Pull request merged**
