### PR TITLE
test: use `cilium identity list` for policy trace test

### PR DESCRIPTION
**Pull request by ianvernon**
`cilium identity get` only returns the identities which fully match the set of labels
provided to its `--labels` parameter. So, if an identity contains labels 'id=app1', and
'app=test', and `cilium identity get --labels=id=app1` is made, then no identities will
be returned because the label 'app=test' was not provided to the command. This means that
if an identity in the policy tracing test overlaps with the labels being used in the trace,
is still in the key-value store, then the test will fail if any other prior test used
the same labels being used in the trace if `cilium identity get` is used to obtain all
identities with a single label, but there are other identities which contain that given
label and other labels. 

Instead, to get all identities which contain the label used in the trace, use
\`cilium identity list\` and filter using \`jq\`.

Fixes: #6347.

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6459)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Test failed: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8572

This is because the second policy trace check wasn't updated in my initial commit. I'll fix this and re-run the tests again.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
