### PR TITLE
Preload vagrant boxes in k8s upstream jenkinsfile

### PR DESCRIPTION
**Pull request by nebril**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8290)

### CODE REVIEW

**Comment by nebril** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Pull request merged**
