### PR TITLE
Remove conformance-e2e tests

### LINKED ISSUE #31776: CI: Conformance E2E: no-unexpected-packet-drops/no-unexpected-packet-drops: No mapping for NAT masquerade
## CI failure

Hit on https://github.com/cilium/cilium/pull/31539
Link: https://github.com/cilium/cilium/actions/runs/8553075421/job/23435496468
Entry: (6, 6.1-20240305.092417, none, true, {eth0,eth1}, vxlan, snat, true, true, testing-o...
Sysdump: [cilium-sysdump-6-20240404-102953.zip](https://github.com/cilium/cilium/files/14868674/cilium-sysdump-6-20240404-102953.zip)

```
[=] Test [no-unexpected-packet-drops] [1/75]
...
  [-] Scenario [no-unexpected-packet-drops/no-unexpected-packet-drops]
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/kind-kind/kind-worker]
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/kind-kind/kind-worker2]
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/kind-kind/kind-control-plane]
  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "EGRESS",
    "reason": "No mapping for NAT masquerade"
  },
  "name": "cilium_drop_count_total",
  "value": 1
}
```

Related: https://github.com/cilium/cilium/issues/30139

### LINKED ISSUE #31918: CI: Socket lookup failed in ci-upgrade-e2e
```
[.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/kind-kind/kind-worker2]
  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "INGRESS",
    "reason": "Socket lookup failed"
  },
  "name": "cilium_drop_count_total",
  "value": 1
}
```
From https://github.com/cilium/cilium/actions/runs/8656794922 (sysdump - https://file.io/PnO9qbJ1qo9i)

Caught multiple times in the ci-upgrade-e2e's 15th configuration after downgrade to v1.15 from `main`:
```
          - name: '15'
            # renovate: datasource=docker depName=quay.io/lvh-images/kind
            kernel: 'bpf-next-20240307.011705'
            kube-proxy: 'none'
            kpr: 'true'
            devices: '{eth0,eth1}'
            secondary-network: 'true'
            tunnel: 'disabled'
            # Disable until https://github.com/cilium/cilium/issues/30717
            # has been resolved.
            # ingress-controller: 'true'
            misc: 'bpfClockProbe=false,cni.uninstall=false,bpf.tproxy=true'
```

According to https://github.com/cilium/cilium/pull/30404#issuecomment-1908656077, it should have been resolved by https://github.com/cilium/cilium/pull/30397 (cc @mhofstetter).

### LINKED ISSUE #33674: CI: Conformance E2E - host-firewall-egress/host-to-pod
## CI failure

Link: https://github.com/cilium/cilium/actions/runs/9854101564/job/27206135510
Sysdump: [cilium-sysdump-6-20240709-094211.zip](https://github.com/user-attachments/files/16142750/cilium-sysdump-6-20240709-094211.zip)

```
ℹ️  📜 Applying CiliumClusterwideNetworkPolicy 'host-firewall-egress'..
  [-] Scenario [host-firewall-egress/host-to-pod]
  [.] Action [host-firewall-egress/host-to-pod/curl-ipv4-0: cilium-test/host-netns-4dggz (172.18.0.3) -> cilium-test/echo-other-node-65965cdd64-2gtfd (10.244.3.67:8080)]
  [.] Action [host-firewall-egress/host-to-pod/curl-ipv6-0: cilium-test/host-netns-4dggz (fc00:c111::3) -> cilium-test/echo-other-node-65965cdd64-2gtfd (fd00:10:244:3::6529:8080)]
  [.] Action [host-firewall-egress/host-to-pod/curl-ipv4-1: cilium-test/host-netns-4dggz (172.18.0.3) -> cilium-test/echo-same-node-9975f89cd-hp7ls (10.244.1.96:8080)]
  [.] Action [host-firewall-egress/host-to-pod/curl-ipv6-1: cilium-test/host-netns-4dggz (fc00:c111::3) -> cilium-test/echo-same-node-9975f89cd-hp7ls (fd00:10:244:1::7372:8080)]
  [.] Action [host-firewall-egress/host-to-pod/curl-ipv4-2: cilium-test/host-netns-djq78 (172.18.0.2) -> cilium-test/echo-other-node-65965cdd64-2gtfd (10.244.3.67:8080)]
  [.] Action [host-firewall-egress/host-to-pod/curl-ipv6-2: cilium-test/host-netns-djq78 (fc00:c111::2) -> cilium-test/echo-other-node-65965cdd64-2gtfd (fd00:10:244:3::6529:8080)]
  ❌ command "curl -w %!!(MISSING){(MISSING)local_ip}:%!!(MISSING){(MISSING)local_port} -> %!!(MISSING){(MISSING)remote_ip}:%!!(MISSING){(MISSING)remote_port} = %!!(MISSING){(MISSING)response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 30 http://[fd00:10:244:3::6529]:8080" succeeded while it should have failed: fd00:10:244:3::62e5:39918 -> fd00:10:244:3::6529:8080 = 200

Test [host-firewall-egress]:
  ❌ host-firewall-egress/host-to-pod/curl-ipv6-2: cilium-test/host-netns-djq78 (fc00:c111::2) -> cilium-test/echo-other-node-65965cdd64-2gtfd (fd00:10:244:3::6529:8080)
```

### LINKED ISSUE #34558: CI: Conformance E2E: Error: Unable to install Cilium: context deadline exceeded - spire busybox imagePullBackOff
## CI failure

- PR https://github.com/cilium/cilium/pull/34325 Introduces a Hubble metrics test and does some gentle refactoring of the metrics server startup logic, without changing its substance - CI failure seems unrelated to the PR
```
🔮 Auto-detected Kubernetes kind: kind
✨ Running "kind" validation checks
⏭️  Skipping disabled validation test "minimum-version"
ℹ️  Using Cilium version 1.17.0
ℹ️  Using cluster name "default"
ℹ️  Detecting real Kubernetes API server addr and port on Kind
🔮 Auto-detected kube-proxy has not been installed
ℹ️  Cilium will fully replace all functionalities of kube-proxy

Error: Unable to install Cilium: context deadline exceeded
Error: Process completed with exit code 1.
```

- Artifact URL: https://github.com/cilium/cilium/actions/runs/10531057346/artifacts/1848578874
- CI run: https://github.com/cilium/cilium/actions/runs/10531057346/job/29182330999

### PR DESCRIPTION
**Pull request by aanm**
The conformance-e2e test has the same coverage as tests-e2e-upgrade.
Although connectivity tests will not run on a "clean state" it does not
really matter given that if the tests fail on the upgrade tests then the
PR should not be merged anyway.

Fixes https://github.com/cilium/cilium/issues/31918
Fixes https://github.com/cilium/cilium/issues/34558
Fixes https://github.com/cilium/cilium/issues/33674
Fixes https://github.com/cilium/cilium/issues/31776

### CODE REVIEW

**Review by joestringer — CHANGES_REQUESTED** [review]
High level seems ok, but doing a diff of the current `.github/workflows/conformance-e2e.yaml` to the `.github/workflows/tests-e2e-upgrade.yaml` version in this PR reveals some subtle changes in coverage, for instance where the conformance-e2e has extra configuration parameters. I think that those extra parameters should probably be added into the e2e-upgrade test. For instance:

```
$ diff -u ../cilium-main/.github/workflows/conformance-e2e.yaml ../cilium-review/.github/workflows/tests-e2e-upgrade.yaml
...
@@ -193,7 +192,6 @@                                                                                                                                                                                                             
             kpr: 'false'                                                                                                                                                                                                       
             tunnel: 'geneve'                                                                                                                                                                                                   
             endpoint-routes: 'true'                                                                                                                                                                                            
-            misc: 'socketLB.enabled=false,nodePort.enabled=true,bpf.masquerade=true'                                                                                                                                           
                                                                                                                                                                                                                                
           - name: '9'                                                                                                                                                                                                          
             # renovate: datasource=docker depName=quay.io/lvh-images/kind 
...
```

nit, can be a separate follow-up: I also noticed that e2e-upgrade disables the ingress-controller due to https://github.com/cilium/cilium/issues/30717 , but the existing test keeps it enabled. Given that the existing test is passing, that suggests to me that we can re-enable on e2e and close out #30717.

**Review by joestringer — APPROVED** [review]
On second thought it's not obvious to me whether it's critical to resolve the above comments before or after, there's just subtle differences in coverage that should be looked over and we make a call about which coverage to keep. I'll change to approve and defer to you on whether to keep the current versions, fix them up in this PR, or follow up separately to fix up the coverage.

**Review by tklauser — APPROVED** [review]

**Review by brb — APPROVED** [review]

**Comment by julianwiedmann** [comment]
>Although connectivity tests will not run on a "clean state" it does not
really matter given that if the tests fail on the upgrade tests then the
PR should not be merged anyway.

So what we no longer cover is that a test succeeds after upgrade, but would actually fail on a clean install? That seems ok.

Also note https://github.com/cilium/cilium/issues/34219. I have no opinion *which* matrix we should keep :).

**Pull request merged**
