### PR TITLE
Add XFRM In policy for traffic destined to the L7 proxy

### LINKED ISSUE #15826: L7 ingress policies are broken with IPsec encryption + tunneling
## Bug report

**General Information**

- Cilium version: Cilium master 42c49fcb433201faa9665700a48cc76d68a59a57
- Kernel version: 5.11.14-arch1-1

**How to reproduce the issue**

1. Create kind cluster:
```console
$ curl -LO https://raw.githubusercontent.com/cilium/cilium/HEAD/Documentation/gettingstarted/kind-config.yaml                                                                          
$ kind create cluster --config=kind-config.yaml
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.20.2) 🖼
...
```

2. Install Cilium with IPsec enabled (cilium-cli master a28d5b11b50f)

```console
$ cilium install --encryption --agent-image=quay.io/cilium/cilium-ci --operator-image=quay.io/cilium/operator-generic-ci --version 42c49fcb433201faa9665700a48cc76d68a59a57 
🔮 Auto-detected Kubernetes kind: kind
✨ Running "kind" validation checks
✅ Detected kind version "0.10.0"
🔮 Auto-detected cluster name: kind-kind
🔮 Auto-detected IPAM mode: kubernetes
🔮 Auto-detected datapath mode: tunnel
🔑 Generating CA...
2021/04/22 12:01:22 [INFO] generate received request
2021/04/22 12:01:22 [INFO] received CSR
2021/04/22 12:01:22 [INFO] generating key: ecdsa-256
2021/04/22 12:01:22 [INFO] encoded CSR
2021/04/22 12:01:22 [INFO] signed certificate with serial number 405881941771138095642683701420529109648776683092
🔑 Generating certificates for Hubble...
2021/04/22 12:01:22 [INFO] generate received request
2021/04/22 12:01:22 [INFO] received CSR
2021/04/22 12:01:22 [INFO] generating key: ecdsa-256
2021/04/22 12:01:22 [INFO] encoded CSR
2021/04/22 12:01:22 [INFO] signed certificate with serial number 52527080873766150852062989974675977903675700005
🚀 Creating Service accounts...
🚀 Creating Cluster roles...
🔑 Generated encryption secret cilium-ipsec-keys
🚀 Creating ConfigMap...
🚀 Creating Agent DaemonSet...
🚀 Creating Operator Deployment...
⌛ Waiting for Cilium to be installed...
```

3. Run the L7 policy example: https://docs.cilium.io/en/latest/gettingstarted/http/
```console
$ kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/minikube/http-sw-app.yaml
$ k get pods -o wide
NAME                        READY   STATUS    RESTARTS   AGE   IP             NODE           NOMINATED NODE   READINESS GATES
deathstar-c74d84667-vcgqv   1/1     Running   0          39s   10.244.3.210   kind-worker2   <none>           <none>
deathstar-c74d84667-vp4fd   1/1     Running   0          39s   10.244.3.68    kind-worker2   <none>           <none>
tiefighter                  1/1     Running   0          3s    10.244.1.49    kind-worker3   <none>           <none>
xwing                       1/1     Running   0          3s    10.244.2.50    kind-worker    <none>           <none>
$ # Before applying policy:
$ kubectl exec tiefighter -- curl -s -XPOST deathstar.default.svc.cluster.local/v1/request-landing
Ship landed
$ kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/minikube/sw_l3_l4_l7_policy.yaml
ciliumnetworkpolicy.cilium.io/rule1 created
$ # This policy should allow the following flow, but instead it times out:
$ kubectl exec tiefighter -- curl -s -XPOST deathstar.default.svc.cluster.local/v1/request-landing
command terminated with exit code 7 (failed to connect())
```

The flow is received and decrypted on the destination node (kind-worker2) and then redirected to the proxy, but after that it seems to be dropped somewhere, i.e. there are no further events in the monitor related to this flow or the proxy, I also don't see any flow arrive on the interface of the endpoint via tcpdump.

```console
$ cilium monitor
Policy verdict log: flow 0xcd3ed225 local EP ID 3721, remote ID 22472, proto 6, ingress, action redirect, match L3-L4, 10.244.1.49:51956 -> 10.244.3.210:80 tcp SYN
-> proxy flow 0xcd3ed225 identity 22472->8675 state new ifindex lxc1d1645030786 orig-ip 10.244.1.49: 10.244.1.49:51956 -> 10.244.3.210:80 tcp SYN
```

### PR DESCRIPTION
**Pull request by christarazi**
- datapath/linux/ipsec: Delete all XFRM state after each test 
- datapath/linux: Add RouteMarkToProxy constant
- datapath/linux/ipsec: Insert additional In rule when tunneling

Fixes: https://github.com/cilium/cilium/issues/15826

```release-note
Fix bug where L7 ingress policies with IPsec dropped traffic in tunneling mode
```

### CODE REVIEW

**Comment by christarazi** [comment]
test-me-please

**Review by jrfastab — APPROVED** [review]

**Comment by brb** [comment]
:rocket: Maybe let's add a CI test for it?

**Comment by christarazi** [comment]
test-runtime

**Comment by christarazi** [comment]
@brb I've filed https://github.com/cilium/cilium-cli/issues/217 for that. Currently, https://github.com/cilium/cilium-cli/pull/215 is still WIP, so after that, I can pick this up.

**Review by joestringer — APPROVED** [review]
Just one nit of the TODO in the commit message, but the change looks good to me.

**Review by joestringer — APPROVED** [review]
Fantastic work tracking this down and also describing how we get here and why this affects tunneling and not DR mode.

**Comment by christarazi** [comment]
All of CI has passed (most recent push was to amend the commit msg; no code change) and the focused run of the previous net-next failure passed as well (https://github.com/cilium/cilium/pull/16057#issuecomment-839320930). We have approving reviews, so marking as ready to merge.

**Pull request merged**
