### PR TITLE
bpf,test: Define BPF_TEST macro for map-in-map/prog-map initialization

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
Please see the commit message for more details.

```release-note
bpf,test: Define BPF_TEST macro for map-in-map/prog-map initialization
```

### CODE REVIEW

**Review by aspsk — COMMENTED** [review]
If you define
```
#define BPF_TEST(...)
```
(somewhere globally) and
```
#undef BPF_TEST
#define BPF_TEST(...) __VA_ARGS__
```
in `bpf/tests/common.h`, then syntax will be a bit more readable, like:
```
struct inner {
        __uint(type, BPF_MAP_TYPE_ARRAY);
        __uint(key_size, sizeof(__u32));
        __uint(val_size, sizeof(__u32));
        __uint(max_entries, 256);
} BPF_TEST(
        inner_0 __section_maps_btf, 
        inner_1 __section_maps_btf
);
```

Wdyt?

**Review by dylandreimerink — APPROVED** [review]
LGTM!

**Comment by YutaroHayakawa** [comment]
@aspsk That syntax looks nice to me, but it only works for map-in-map initialization, right? If so, I'd keep the BPF_TEST macro as is for other purposes and define another macro like `BPF_TEST_MAP_INIT(...)`.

**Comment by aspsk** [comment]
> @aspsk That syntax looks nice to me, but it only works for map-in-map initialization, right? If so, I'd keep the BPF_TEST macro as is for other purposes and define another macro like `BPF_TEST_MAP_INIT(...)`

So, the macro should work for any code block, but, yes, for long code blocks `ifdef`s look better. (Just didn't want to have more ifdefs around :-) )

> Also, another concern is "somewhere globally" is not so trivial

This could be just a build flag: `-DBPF_TEST(...)=` or `-DBPF_TEST(...)=__VA_ARGS__`.

But ok, if this is simpler to just have a testable `BPF_TEST`, then use it. And cleanup code with `BPF_TEST_MAP_INIT` and friends when possible.

**Review by aspsk — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
We don't need to run tests since this just defines the macro, and no one uses it.

**Pull request merged**
