### PR TITLE
v1.15 Backports 2024-10-07

### PR DESCRIPTION
**Pull request by giorio94**
* [ ] #34611 (@dboslee) :warning: resolved conflicts
    * :information_source: Resolved a few conflicts to adapt the patch to the v1.15 tree.
 * [ ] #35033 (@WeeNews) :warning: resolved conflicts
   * :information_source: Hit minor conflict due to different surrounding
      context in `service/id_test.go`. Accepted combination.
 * [x] #34808 (@cfsnyder) :warning: resolved conflicts
    * :information_source: Hit multiple conflicts due to the usage of a different gateway API version (v1alpha2 vs v1); adapted accordingly. Additionally added missing "ptr" package import in `gateway_test.go`.
 * [ ] #35068 (@ayuspin)
 * [ ] #35109 (@jrajahalme) :warning: resolved conflicts
    * :information_source: Hit minor conflict due to different surrounding context, accepted combination. Additionally updated the TestMapState_AccumulateMapChangesOnVisibilityKeys test, which has been removed in the meanwhile on main, applying the changes originally part of https://github.com/cilium/cilium/commit/137abf7b4b6a (from https://github.com/cilium/cilium/pull/35109).
 * [x] #35177 (@marseel)
 * [x] #35262 (@aanm) :warning: resolved conflicts
    * :information_source: Hit minor conflict due to different surrounding context (i.e., missing Update Protobuf APIs step); adapted accordingly.
 * [x] #35264 (@aanm)
 * [x] #31538 (@ti-mo, @aanm)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 34611 35033 34808 35068 35109 35177 35262 35264 31538
```

### CODE REVIEW

**Comment by giorio94** [comment]
/test-backport-1.15

**Review by marseel — APPROVED** [review]

**Comment by giorio94** [comment]
Rebased onto v1.15, fixed a unit test error caused by the backport of #35109, and additionally backported #31538 (first commit only).

**Comment by giorio94** [comment]
/test-backport-1.15

**Review by aanm — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
Looks good for #34808, thanks.

**Review by nebril — APPROVED** [review]

**Comment by giorio94** [comment]
I've double-checked the remaining commits, marking ready to merge.

**Pull request merged**
