### PR TITLE
test: fix cilium policy action for clusterwide policies

### LINKED ISSUE #13378: CI: Checks service across nodes Tests NodePort BPF Tests with direct routing With host policy Tests NodePort
```
/home/jenkins/workspace/Cilium-PR-K8s-1.12-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Request from testclient-9qwnz pod to service http://192.168.36.12:30849 failed
Expected command: kubectl exec -n default testclient-9qwnz -- /bin/bash -c 'fails=""; id=$RANDOM; for i in $(seq 1 10); do if curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://192.168.36.12:30849 -H "User-Agent: cilium-test-$id/$i"; then echo "Test round $id/$i exit code: $?"; else fails=$fails:$id/$i=$?; fi; done; if [ -n "$fails" ]; then echo "failed: $fails"; fi; cnt="${fails//[^:]}"; if [ ${#cnt} -gt 0 ]; then exit 42; fi' 
To succeed, but it failed:
Exitcode: 42 
Err: exit status 42
Stdout:
```

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/593/testReport/junit/Suite-k8s-1/12/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_With_host_policy_Tests_NodePort/

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/593/testReport/junit/Suite-k8s-1/12/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_With_host_policy_Tests_NodePort/attachments/d5337293_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_With_host_policy_Tests_NodePort.zip

### PR DESCRIPTION
**Pull request by fristonio**
Fixes #13378

### CODE REVIEW

**Comment by fristonio** [comment]
test-focus K8sServicesTest

**Comment by fristonio** [comment]
test-focus K8sServicesTest

**Comment by fristonio** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]
Thanks @fristonio!

I wonder why this doesn't affect the other host firewall test (for fromCIDR+toPorts) :thinking: 
Did you check if we have other tests using CCNPs that may be affected?

**Comment by fristonio** [comment]
> I wonder why this doesn't affect the other host firewall test (for fromCIDR+toPorts) thinking

Yeah, I wonder about this too, but honestly, I don't have a really good answer for this. My guess would be that something changed in the test env for `Services.go` that lead to some request failing when applying policies as we started seeing this fail only recently.
Do you have ideas around how a policy addition/removal dictates traffic, as in are there any unnecessary/expected drops when the policy is recalculated and updated(with and without host policies)?

> Did you check if we have other tests using CCNPs that may be affected?

No, I didn't check any other tests related to CCNP. :sweat_smile: 
Maybe `test-me-please` run can give us some info around them. But we haven't seen any tests related to CCNP failing apart from this in recent times.

**Review by nebril — APPROVED** [review]
LGTM!

**Pull request merged**
