### PR TITLE
v1.16 Backports 2024-09-11

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #34609 (@sayboras)
 * [x] #34647 (@chaunceyjiang) :warning: resolved conflicts
 * [x] #34636 (@julianwiedmann)
 * [x] #34527 (@dylandreimerink) :warning: resolved conflicts
 * [x] #34095 (@giorio94)
 * [x] #34650 (@Artyop) :warning: resolved conflicts
 * [x] #34699 (@tklauser)
 * [x] #34707 (@marseel) :warning: resolved conflicts
 * [x] #34711 (@marseel) :warning: resolved conflicts
 * [x] #34727 (@marseel) :warning: resolved conflicts
 * [x] #34721 (@giorio94)
 * [x] #34775 (@julianwiedmann)
 * [x] #34611 (@dboslee)

PRs removed due to issues:
 * #34668 (@marseel)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 34609 34647 34636 34527 34095 34650 34699 34707 34711 34727 34721 34775 34611
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.16

**Review by tklauser — APPROVED** [review]
Thanks, looks good for my change.

**Review by marseel — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
Thanks, my commits look good.

**Review by qmonnet — APPROVED** [review]
image


Are so many owners expected to be pulled in for a backport PR? I thought not, but maybe I got confused :thinking:.

Anyway, doc change's OK

**Comment by nbusseneau** [comment]
> Are so many owners expected to be pulled in for a backport PR? I thought not, but maybe I got confused 🤔.

No indeed, owners are stripped down as part of the release process but seems like they got added back by mistake while resolving conflicts in #34452. I will add a commit fixing this to the PR.

**Review by julianwiedmann — APPROVED** [review]

**Comment by qmonnet** [comment]
> I will add a commit fixing this to the PR.

Thank you! :pray:

**Review by dylandreimerink — APPROVED** [review]

**Review by Artyop — APPROVED** [review]
lgtm for #34650

**Review by aanm — APPROVED** [review]

**Comment by nbusseneau** [comment]
/test-backport-1.16

**Comment by nbusseneau** [comment]
- Fixed the images wait check for stable branches since `cilium-cli` is not build off the tree in stable branches, re-running CI.
- Fixed `CODEOWNERS` via manual commit.

**Comment by nbusseneau** [comment]
Removed #34668 due to issues with IPsec upgrade/downgrade tests.

**Comment by nbusseneau** [comment]
/test-backport-1.16

**Pull request merged**
