### PR TITLE
gh/workflows: Pin lvh to v0.0.1

### PR DESCRIPTION
**Pull request by brb**
gh/workflows: Pin lvh to v0.0.1

    As the latest moved the "lvh" binary path and the "lvh" is close to
    being stable.

    The switch is needed to fix the following failure:

        Status: Downloaded newer image for quay.io/lvh-images/lvh:latest
        Error: No such container:path:
        16b9166a07097cd9f301d48d6767644139edb54aea07e8ecf4429a9efd8bf2ac:/usr/bin/lvh

    Reported-by: Tam Mach <tam.mach@cilium.io>
    Signed-off-by: Martynas Pumputis <m@lambda.lt>

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
:heavy_check_mark:

**Review by NikAleksandrov — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Comment by michi-covalent** [comment]
looks like it's failing consistently with this error 😢 
```
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
```

**Comment by brb** [comment]
The `ci-datapath` passed - https://github.com/cilium/cilium/actions/runs/3173611355/jobs/5169416993. PTAL.

**Review by pchaigno — APPROVED** [review]
> Use 1.1.1.1 until the issue has been resolved.

Do we need to track this issue somewhere?

**Comment by brb** [comment]
> Do we need to track this issue somewhere?

:+1: https://github.com/cilium/little-vm-helper/issues/13

**Review by michi-covalent — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Pull request merged**
