### PR TITLE
v1.13 backports 2022-12-21

### PR DESCRIPTION
**Pull request by joestringer**
v1.13 backports 2022-12-21

 * #22627 -- test/l4lb, nat64x46: pass k8s api server to the standalone proxy (@squeed)
 * #21797 -- Introduce v3 backend maps (@YutaroHayakawa)
 * #22477 -- ipam/crd: Fix agent fatal on router initialization (@jaffcheng)
 * #22676 -- daemon: Do not remove PERM L2 entries in L4LB (@brb)
 * #22553 -- clustermesh: Add an infrastructure for connect time parameter exchange and capability negotiation (@YutaroHayakawa)
 * #22673 -- gha: Add retry mechanism for conformance ingress (shared) (@sayboras)
 * #22252 -- daemon, fqdn: Fix race between parallel DNS requests for the same name (@christarazi)
 * #21600 -- Add policy listener support (@jrajahalme)
 * #22726 -- test/helpers: Fix retry condition for CiliumExecContext (@christarazi)
 * #22333 -- datapath: Don't enforce ingress policies at overlay if endpoint routes are enabled (@pchaigno)
 * #22418 -- gh/workflows: Add DP CI for encryption (@brb)
 * #22656 -- Per-node configuration overrides (v2) (@squeed)
   * @squeed The last commit here changes the workflow files for master, which are deleted on the v1.13 branch. I think we need to also update the master branch's CI workflow definitions for the v1.13 tree to match.
 * #22721 -- install/kubernetes: make securityContext SELinux options configurable (@tklauser)
 * #22679 -- bpf: add drop notification for missed L7 LB tailcall in to-netdev (@julianwiedmann)
 * #22654 -- backporting: leave `backport/author` PRs alone (@bimmlerd)
 * #22700 -- cilium: Add deprecation warning for service ids (@joamaki)
 * #22619 -- fqdn: dnsproxy: fix data race in dns proxy implementation (@aspsk)
 * #22518 -- Add tests for hubble metrics handlers (@marqc)
 * #22772 -- test: service: fix formatting of error msg in doFragmentedRequest() (@julianwiedmann)
 * #22796 -- ci: Replace deprecated `hubble observe -o json` with `-o jsonpb` (@gandro)
 * #22821 -- Add sphinxcontrib-googleanalytics to doc requirements (@chalin)
 * #22600 -- daemon/cmd: improve stale cilium endpoint error handling. (@tommyp1ckles)
 * #21822 -- Datapath support for Cilium mTLS (@jrajahalme)

Skipped due to conflicts, seems some datapath testing PRs are not tagged for backport:
 * #22653 -- test/l4lb,nat46x64: Replace Kind/Helm with DinD (@brb)
 * #22421 -- cilium: completion of nat46/64 gateway (@borkmann)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 22627 21797 22477 22676 22553 22673 22252 21600 22726 22333 22418 22656 22721 22679 22654 22700 22619 22518 22772 22796 22821 22600 21822; do contrib/backporting/set-labels.py $pr done 1.13; done
```

### CODE REVIEW

**Comment by joestringer** [comment]
I'm not sure how https://github.com/cilium/cilium/pull/22656 is going to interact with the v1.13 CI, but just in case I've also posted https://github.com/cilium/cilium/pull/22823. cc @squeed

**Comment by joestringer** [comment]
/test-backport-1.13

**Review by christarazi — APPROVED** [review]

**Review by brb — APPROVED** [review]
My changes LGTM, thanks!

> test/l4lb,nat46x64: Replace Kind/Helm with DinD #22653 -- test/l4lb,nat46x64: Replace Kind/Helm with DinD (@brb)

I will do a manual backport of these.

**Review by julianwiedmann — APPROVED** [review]

**Review by aspsk — APPROVED** [review]

**Review by gandro — APPROVED** [review]
My commit (and the Hubble changes) looks good, thanks!

**Review by sayboras — APPROVED** [review]
Looks good for my commit, thanks :100:

**Review by nbusseneau — APPROVED** [review]

**Comment by joestringer** [comment]
CI triage:
- [Cilium L4LB XDP](https://github.com/cilium/cilium/actions/runs/3746344131):
    - Failing due to https://github.com/cilium/cilium/pull/22656 . It looks like some combination of (a) Backporting https://github.com/cilium/cilium/pull/22653 across (to be done by @brb) and/or porting the L4LB testing changes across to the v1.13 version of the github workflow should resolve this. Filed #22833 to follow up.
- [ConformanceAKS](https://github.com/cilium/cilium/actions/runs/3746344117), [ConformanceEKS](https://github.com/cilium/cilium/actions/runs/3746344139), [ConformanceGKE](https://github.com/cilium/cilium/actions/runs/3746344116):
    -  During install, hits `Error: Unable to install Cilium: roles.rbac.authorization.k8s.io "cilium-config-agent" already exists`. Fail sdue to the changes in https://github.com/cilium/cilium/pull/22656 . These will be resolved by https://github.com/cilium/cilium/pull/22823.
- [k8s-1.16-kernel-4.9](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/3518/)
    - Hit known flake #20998
- [k8s-1.21-kernel-4.9](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/2267/)
    -  Hit known flake https://github.com/cilium/cilium/issues/21279
- [runtime](https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/4374/)
    - Hit known flake #22470. I've marked https://github.com/cilium/cilium/pull/22570 and https://github.com/cilium/cilium/pull/22761 as needing backport in an attempt to make this test more reliable.

**Review by tommyp1ckles — APPROVED** [review]

**Pull request merged**
