### PR TITLE
improve ut for ip.go 

### PR DESCRIPTION
**Pull request by my-git9**
improve ut for ip.go

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Comment by ti-mo** [comment]
@my-git9 Could you elaborate on why these tests are needed? `MustAddrFromIP()` should just be a panic wrapper around `AddrFromIP()`, which is already covered by tests.

@christarazi Why does `MustAddrFromIP()` directly call `netip.AddrFromSlice()` instead of wrapping `AddrFromIP()` with `panic()`?

**Comment by christarazi** [comment]
@ti-mo Good point, filed https://github.com/cilium/cilium/pull/21598.

**Review by christarazi — COMMENTED** [review]
Thanks for the PR. I also don't see how this provides any extra coverage.

**Comment by my-git9** [comment]
OK, I will close this

**Pull request closed without merging**
