### PR TITLE
Update policy docs to reflect ToServices changes

### PR DESCRIPTION
**Pull request by nebril**
Documents changes introduced by #2332

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Review by raybejjani — APPROVED** [review]

**Review by tgraf — DISMISSED** [review]
```
14:55:08 ==> cilium-master-build-Cilium-Bash-Tests-281: Error: Validation of policy has failed: service-labels.json:1: unable to assign value 'object' to type 'api.Rules':
14:55:08 ==> cilium-master-build-Cilium-Bash-Tests-281: {
14:55:08 ==> cilium-master-build-Cilium-Bash-Tests-281: ^
14:55:08 ==> cilium-master-build-Cilium-Bash-Tests-281: ----- 00-check-examples.sh: main: /home/vagrant/go/src/github.com/cilium/cilium/tests/../examples/policies/l3/service/service-labels.json is not valid
```

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Pull request merged**
