### PR TITLE
v1.13 Backports - ipsec: cache xfrm state list

### PR DESCRIPTION
**Pull request by marseel**
* [x] #32588 (@marseel)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 32588
```

### CODE REVIEW

**Comment by marseel** [comment]
/test-backport-1.13

**Comment by marseel** [comment]
/test-backport-1.13

**Review by pchaigno — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]

**Comment by qmonnet** [comment]
So apparently Jenkins doesn't report its results. Here we are:

- https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.16-kernel-4.19/1236/
- https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.17-kernel-4.19/528/ FAIL
- https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.18-kernel-4.19/532/
- https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.19-kernel-4.19/532/
- https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.20-kernel-4.19/530/
- https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.21-kernel-4.19/567/
- https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.22-kernel-4.19/605/
- https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.23-kernel-4.19/843/
- https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.24-kernel-4.19/538/
- https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.24-kernel-5.4/1230/
- https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.25-kernel-4.19/1239/
- https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.26-kernel-net-next/1356/ FAIL
- https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-Upstream/871/
- https://jenkins.cilium.io/view/PR/job/Cilium-PR-Runtime-kernel-net-next/1656/

**Comment by qmonnet** [comment]
/test-1.17-4.19

**Comment by qmonnet** [comment]
/test-1.26-net-next

**Comment by marseel** [comment]
I was wrong Quentin, I triggered tests twice in this PR, only the first one was run in Jenkins :cry:

**Comment by qmonnet** [comment]
> I was wrong Quentin, I triggered tests twice in this PR, only the first one was run in Jenkins 😢

That explains why I can't find the results for the other two v1.13 backport PRs :confused:. Not sure how to fix this.

**Comment by marseel** [comment]
/test-backport-1.13

**Comment by qmonnet** [comment]
/test-1.24-5.4

**Pull request merged**
