### PR TITLE
vendor: Bump StateDB to version v0.2.1

### PR DESCRIPTION
**Pull request by joamaki**
Update StateDB and fix up the API usage. The new version splits the full reconciliation into separate pruning and refreshing. Refreshing of objects is performed gradually rather than as one big operation. This makes refreshing less disruptive to normal operations as it can be spread over a longer period of time.

StateDB API is now more consistent (List/ListWatch, All/AllWatch) and the construction of reconcilers have been revamped to allow for defaults.

https://github.com/cilium/statedb/pull/36
https://github.com/cilium/statedb/pull/34
https://github.com/cilium/statedb/pull/33
https://github.com/cilium/statedb/pull/32

### CODE REVIEW

**Review by lmb — APPROVED** [review]

**Review by learnitall — APPROVED** [review]
Vendor changes LGTM, thanks!

**Review by derailed — APPROVED** [review]
@joamaki Nice work!

**Review by sayboras — APPROVED** [review]
Probably we need to update the docs on metrics renaming.

**Comment by joamaki** [comment]
> Probably we need to update the docs on metrics renaming.

What docs? None of these metrics were yet documented and they're disabled by default.

**Comment by sayboras** [comment]
> What docs?

The below docs for example. https://docs.cilium.io/en/stable/operations/upgrade/#changed-metrics.

> None of these metrics were yet documented and they're disabled by default (luckily!)

Cool

**Review by thorn3r — APPROVED** [review]

**Comment by joamaki** [comment]
> > What docs?
> 
> The below docs for example. https://docs.cilium.io/en/stable/operations/upgrade/#changed-metrics.
> 
> > None of these metrics were yet documented and they're disabled by default (luckily!)
> 
> Cool

Thanks! I would propose skipping this as the metrics have still been in flux and don't have any dashboards and so on yet, so no known users. Documenting the change is just confusing at this point. Though this is likely the last change to these metrics where we can do this.

**Review by aspsk — APPROVED** [review]

**Pull request merged**
