### PR TITLE
[v1.9] vagrant: Bump runtime box image

### PR DESCRIPTION
**Pull request by joestringer**
Related: #18919

### CODE REVIEW

**Comment by joestringer** [comment]
/test-runtime-4.9

**Comment by pchaigno** [comment]
We usually need to use a special branch name to bump the VM image versions because the logic to update the cache relies on that special branch name. I'm not sure how that will work for v1.9 :thinking:  /cc @nbusseneau @nebril

**Comment by nbusseneau** [comment]
Yep, use the same branch name as usual: https://docs.cilium.io/en/v1.11/contributing/testing/ci/#packer-ci-build

**Comment by pchaigno** [comment]
At the same time, if it's the same VM image versions as used on master, then do we even need to update anything in the cache?

**Comment by joestringer** [comment]
I did just pull the image version from master. CI failed but I initially assumed it's because of the process mentioned above. I will do a bit of digging.

**Comment by joestringer** [comment]
The actual failure was the same as what this PR hoped to fix: https://jenkins.cilium.io/view/PR/job/Cilium-PR-Runtime-4.9/5695/execution/node/116/log/

**Comment by joestringer** [comment]
Looking a bit deeper, it seems that I was bumping the wrong image here anyhow: https://jenkins.cilium.io/view/PR/job/Cilium-PR-Runtime-4.9/5695/execution/node/63/log/

**Comment by joestringer** [comment]
OK, I think the PR just updated the wrong variable since the command is `KERNEL=49 vagrant up runtime --provision`, probably I need to bump the final image version in the PR. I'll open a fresh PR with the standard branch name for this.

**Pull request closed without merging**
