### PR TITLE
Makefile: remove -test.v from GOTEST_BASE

### PR DESCRIPTION
**Pull request by ti-mo**
This makes `go test` rather verbose in CI, since it will echo all stdio generated during all tests. The default behaviour of 'go test' (without -v) is to buffer all stdio and only display it when a test fails. This should be sufficient for privileged and integration tests.

### CODE REVIEW

**Comment by ti-mo** [comment]
Turns out -v is ignored when combined with -json, so it doesn't really change anything. Created a https://github.com/mfridman/tparse/pull/93 PR to finetune the verbosity a little. What actually needs changing is setting tparse's `-follow` flag when V=1. V=0 is too quiet for CI.

Moving this into draft until tparse has been updated.

**Comment by ti-mo** [comment]
tparse gained the `-progress` flag in https://github.com/mfridman/tparse/pull/95. Updated this PR to use it and pull in tparse at the latest commit from main.

**Review by borkmann — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Pull request merged**
