### PR TITLE
[v1.13] backport Go version check fixes in preparation for Go 1.21 update

### PR DESCRIPTION
**Pull request by tklauser**
Manually backport a few commits from `main` that let us update to Go 1.21 for `v1.13` in #29817.

See commits for details.

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.13

**Comment by tklauser** [comment]
/test-1.21-4.19

**Comment by tklauser** [comment]
/test-1.18-4.19

**Review by squeed — APPROVED** [review]

**Comment by tklauser** [comment]
/test-1.18-4.19

**Pull request merged**
