### PR TITLE
v1.4 backport 19-01-24

### PR DESCRIPTION
**Pull request by jrfastab**
PR:
#6706 
#6732 
#6746 
#6710 
#6750 
#6693 
#6709 
#6752 
#6704 
#6743 
#6697 
#6738 
#6742 
#6731 
#6736 
#6734 
#6715 

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6762)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by jrfastab** [comment]
test-me-please

**Comment by ianvernon** [comment]
I can triage the Istio test failure in https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1563/

This is occurring intermittently in master as well, so I think it's OK to merge this.

**Pull request merged**
