### PR TITLE
Increase capacity of BPF maps

### PR DESCRIPTION
**Pull request by tgraf**

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by joestringer** [comment]
While we're at it, we can perhaps update the `PROG_ARRAY` for policy to use `ENDPOINTS_MAP_SIZE` rather than `POLICY_MAP_SIZE`: 

https://github.com/cilium/cilium/blob/3135a2f7259f36c83d8107203847c3735b34d179/bpf/lib/maps.h#L37-L44

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Review by raybejjani — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]
LGTM, CI failure looks like a CI issue (@joestringer 's other PR has the same failure at least)?

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
