### PR TITLE
bpf: fix complexity issues around recent CT changes on 4.9 kernels

### PR DESCRIPTION
**Pull request by borkmann**
The single heavy hitter in complexity in our BPF progs right now is
the slave selection based on weights in the LB. Reason is that in the
verifier pruning, a couple of assumptions cannot be made once the
kernel sees that there's one or multiple usages with dynamic map
access and thus we bump from ~30k to ~90k closely hitting limits and
for older 4.9 kernels that don't have the 98k complexity limit we
easily overrun the 68k. Now with this change the heavy hitter in
section '2/10' (IPv6 handling) reduces down to ~30k and loads fine
on my side. It also allows us to remove the relax_verifier() pseudo
helper again. Thus for the LB fall back to just use hash-based which
afaik is the default anyway in our case. We can enable this for more
recent kernels that have a smarter verifier if we want to.

Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
This is a great immediate fix. Given the LB action is always performed first in the execution path, we can move it into a tail call and bypass the LB lookup on the 2nd iteration.

**Comment by borkmann** [comment]
Agree, given we already have the v6 handling in a tail call, this should work. I can look into it as follow-up. Thanks!

**Pull request merged**
