### PR TITLE
[1.3] Fix route lookup and add workaround for kernel race condition

### PR DESCRIPTION
**Pull request by tgraf**
* https://github.com/cilium/cilium/pull/6671

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6836)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9447/

First test to fail was Star Wars demo test.

From the logs in `cilium-test.log`, I searched for `level=fatal`:

```
2019-01-29T05:18:25.936143475Z level=fatal msg="Unable to connect to kvstore" error="timed out while waiting for etcd session. Ensure that etcd is running on [https://cilium-etcd-client.kube-system.svc:2379]" subsys=kvstore
2019-01-29T05:18:25.943975889Z level=fatal msg="Agent pipe unexpectedly closed, shutting down" subsys=cilium-node-monitor
2019-01-29T05:17:58.895305522Z level=fatal msg="Unable to connect to kvstore" error="timed out while waiting for etcd session. Ensure that etcd is running on [https://cilium-etcd-client.kube-system.svc:2379]" subsys=kvstore
2019-01-29T05:17:58.897701878Z level=fatal msg="Agent pipe unexpectedly closed, shutting down" subsys=cilium-node-monitor
2019-01-29T05:18:25.936143475Z level=fatal msg="Unable to connect to kvstore" error="timed out while waiting for etcd session. Ensure that etcd is running on [https://cilium-etcd-client.kube-system.svc:2379]" subsys=kvstore
2019-01-29T05:18:25.943975889Z level=fatal msg="Agent pipe unexpectedly closed, shutting down" subsys=cilium-node-monitor
2019-01-29T05:17:58.895305522Z level=fatal msg="Unable to connect to kvstore" error="timed out while waiting for etcd session. Ensure that etcd is running on [https://cilium-etcd-client.kube-system.svc:2379]" subsys=kvstore
2019-01-29T05:17:58.897701878Z level=fatal msg="Agent pipe unexpectedly closed, shutting down" subsys=cilium-node-monitor
```

Unfortunately the logs for the test failures are paltry because no bugtool output was gathered. This may be a bug in the CI for v1.3 in terms of log gathering.

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
