### PR TITLE
pkg/k8s: remove manual generated DeepCopyInto function

### PR DESCRIPTION
**Pull request by aanm**
Replace the manual creation of the DeepCopyInto function with an
autogenerated one.

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by nathanjsweet** [comment]
retest-ginkgo-gke

**Comment by nathanjsweet** [comment]
retest-gke

**Review by rolinh — APPROVED** [review]

**Pull request merged**
