### PR TITLE
v1.7 backports 2020-03-03

### PR DESCRIPTION
**Pull request by vadorovsky**
* #10353 -- datapath: Switch to upstream bpftool, remove additional arguments  (@mrostecki)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10353; do contrib/backporting/set-labels.py $pr done 1.7; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10429)

### CODE REVIEW

**Comment by mrostecki** [comment]
never-tell-me-the-odds

**Comment by mrostecki** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-docs-please

**Review by joestringer — APPROVED** [review]
LGTM!

Docs target failure is known issue, I will work on getting the relevant PR backported to address that. This PR should not be dependent on that.

**Pull request merged**
