### PR TITLE
Add a test for CNP update of same policy

### PR DESCRIPTION
**Pull request by joestringer**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5729)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
@joestringer needs rebase. Also has WIP in the title still - is this actually ready for review?

**Comment by joestringer** [comment]
@ianvernon a ha! I accidentally changed these labels on the wrong PR some time last week and couldn't find the relevant PR again. 

This needs tidy up and there were an additional couple of similar tests that were suggested by @aanm - updating to completely empty policies (no specs at all), and adding policies with different user-specified labels (then seeing that the appropriate policies are updated).

**Comment by aanm** [comment]
@joestringer there are some unit tests already done in `daemon/k8s_watcher_test.go` but we still need e2e

**Comment by joestringer** [comment]
test-me-please

EDIT: Failed due to weird FS write issue:

```
17:25:29     k8s1-1.12: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/rpm'
17:25:29     k8s1-1.12: rm -f GIT_VERSION
17:25:29     k8s1-1.12: echo "f04235260 2018-10-30T17:13:38+00:00" >GIT_VERSION
17:25:29     k8s1-1.12: /bin/sh: 1: cannot create GIT_VERSION: Operation not permitted
17:25:29     k8s1-1.12: Makefile:128: recipe for target 'GIT_VERSION' failed
17:25:29     k8s1-1.12: make: *** [GIT_VERSION] Error 2
17:25:29 The SSH command responded with a non-zero exit status. Vagrant
17:25:29 assumes that this means the command failed. The output for this command
17:25:29 should be in the log above. Please read the output to determine what
17:25:29 went wrong.
17:25:29 
17:25:29         ===================== ERROR - VM PROVISION FAILED =====================
17:25:29 
17:25:29         Unable to provision and start VM "k8s1-1.12": exit status 1", vm, err
17:25:29 
17:25:29         =======================================================================
```

**Comment by joestringer** [comment]
test-me-please

EDIT: Infra issue:

```
Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
```

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Green run with the new test: 

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7733/execution/node/94/log/

I will remove the Focus commit and push again with no other changes.

**Comment by eloycoto** [comment]
Hi, 

Quick one, could these lines move to this test? I think that the context is too similar, and the current place I don't really liked too:

https://github.com/cilium/cilium/blob/17291bbabbbe0dcc9a9a2de356e26dd1b9aa167e/test/k8sT/Policies.go#L261-L284

From PR https://github.com/cilium/cilium/pull/5210

**Comment by joestringer** [comment]
@eloycoto seems reasonable but the intent of your suggestion is different from this PR and when I look at the code you linked I don't fully understand the context and specific implementation of the test. I've filed #6131 to follow up on that separately.

**Comment by joestringer** [comment]
Looks like some of the helper functions I was using got changed. Need to update for that.

**Comment by joestringer** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]

**Pull request merged**
