### PR TITLE
v1.13 Backports 2024-05-13

### PR DESCRIPTION
**Pull request by jibi**
* [ ] #31424 (@learnitall)
 * [x] #32402 (@michi-covalent)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31424 32402
```

### CODE REVIEW

**Comment by jibi** [comment]
/test-backport-1.13

**Review by michi-covalent — APPROVED** [review]
extra power!

**Comment by jibi** [comment]
test-1.22-4.19

**Review by viktor-kurchenko — APPROVED** [review]

**Review by learnitall — APPROVED** [review]
Thanks!

**Pull request merged**
