### PR TITLE
[v1.9] Backport of #17492

### PR DESCRIPTION
**Pull request by christarazi**
* #17492 -- daemon, ipam, option: Introduce ability to bypass IP availability error (@christarazi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 17492; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by christarazi** [comment]
/test-backport-1.9

**Comment by christarazi** [comment]
/test-backport-1.9

**Comment by christarazi** [comment]
/test-backport-1.9

**Review by joestringer — APPROVED** [review]

**Pull request merged**
