### PR TITLE
clustermesh-apiserver: add missing metrics and documentation

### PR DESCRIPTION
**Pull request by giorio94**
This PR extends the documentation with information about clustermesh-apiserver metrics that have been overlooked in previous commits. It also corrects the selection of the rate limiter metrics exposed by the clustermesh-apiserver and adds a couple of missing metrics.

### CODE REVIEW

**Comment by giorio94** [comment]
Integration tests hit unrelated flake: https://github.com/cilium/cilium/issues/24904. Rerunning manually.

**Review by qmonnet — APPROVED** [review]
Looks good to me

**Review by nathanjsweet — APPROVED** [review]

**Comment by giorio94** [comment]
The last commit exposes the `cilium_clustermesh_apiserver_version`, as suggested in https://github.com/cilium/cilium/pull/26083#discussion_r1227378688.

**Comment by giorio94** [comment]
Rebased onto main to fix conflicts

**Review by YutaroHayakawa — APPROVED** [review]

**Pull request merged**
