### PR TITLE
[DO NOT MERGE] Change default IPv6 CIDR to a real private IPv6 address

### PR DESCRIPTION
**Pull request by tgraf**
Related: #4261 

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4298)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
We can't change the default IPv6 cluster prefix without breaking upgrade compatibility as endpoints can't be restored as the IP of old endpoints would not fall into the new CIDR range.

**Pull request closed without merging**
