### PR TITLE
envoy: Make timeouts user configurable, default to 1 hour request timeout.

### PR DESCRIPTION
**Pull request by jrajahalme**
Allow users to configure the timeouts Cilium configures for
Envoy and change the default value of request timeout to one hour
to allow for longer downloads. Idle timeout is kept as unlimited, as is
the maximum GRPC timeout. This means that GRPC requests may (still) take
longer than one hour to complete without being interrupted.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6295)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by jrajahalme** [comment]
Zero `idle_timeout` failed Envoy runtime validation, changed to only send `idle_timeout` if the value is non-zero.

**Comment by jrajahalme** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by jrajahalme** [comment]
@ianvernon this needs backports to 1.2.x before it goes out.

**Pull request merged**
