### PR TITLE
Remove old proto dependencies

### PR DESCRIPTION
**Pull request by glibsm**
These protoc plugin imports are no longer requires since the
v1 proto generation is accomplished through the use a docker
image. That image controls the versions, this is just a
cleanup commit.

Ref #12931

Signed-off-by: Glib Smaga <code@gsmaga.com>

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]

**Review by vadorovsky — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
The "go-mod" GitHub action failure looks real (https://github.com/cilium/cilium/runs/1087913955). Seems like something stripped whitespaces in `vendor/github.com/envoyproxy/protoc-gen-validate/validate/validator.py`). Otherwise LGTM.

**Comment by glibsm** [comment]
> The "go-mod" GitHub action failure looks real (https://github.com/cilium/cilium/runs/1087913955). Seems like something stripped whitespaces in `vendor/github.com/envoyproxy/protoc-gen-validate/validate/validator.py`). Otherwise LGTM.

```
❯ go mod tidy && go mod vendor
❯ gs
On branch pr/glibsm/old-proto-deps
Your branch is up to date with 'origin/pr/glibsm/old-proto-deps'.

nothing to commit, working tree clean
```

**Comment by aanm** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Comment by aanm** [comment]
retest-4.9

**Comment by aanm** [comment]
retest-runtime

**Pull request merged**
