### PR TITLE
docs: fix link for Cilium-PR-Kubernetes-Upstream job

### PR DESCRIPTION
**Pull request by tklauser**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10178)

### CODE REVIEW

**Comment by tklauser** [comment]
test-docs-please

**Review by pchaigno — APPROVED** [review]
Nice catch!

**Comment by tklauser** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Comment by brb** [comment]
@tklauser To test only the docs, you can run `test-docs-please`.

**Pull request merged**
