### PR TITLE
ci: skip post-test info gathering in case of skipped cilium installation

### PR DESCRIPTION
**Pull request by mhofstetter**
Currently, getting the Cilium status (in steps like "Post-test information gathering" (or similar ones)) always fail if the Cilium installation is skipped due to missing images. As a consequence, these steps are confusingly listed in CI analysis.

IMO we should try to avoid having "post-processing" steps fail due to some missing pre-requisites (like Cilium being installed).

Therefore, this commit skips these steps if Cilium installation has been skipped.

### CODE REVIEW

**Comment by mhofstetter** [comment]
Current state of this PR illustrates the failing tests (due to cancelled image builds) which results in skipped post-processing steps.

will properly run the tests if we decide that we want to go this way.

**Review by aanm — APPROVED** [review]

**Review by viktor-kurchenko — APPROVED** [review]
LGTM.

**Comment by mhofstetter** [comment]
MLH still seems to be asleep - adding `ready-to-merge`manually

**Pull request merged**
