### PR TITLE
Fix rawgit links in README.rst

### LINKED ISSUE #14082: Fix rawgit links in README.rst
Rawgit has been sunsetted:

https://rawgit.com/

However we still appear to have references in the repo which we should remove:

```
 $ git grep rawgit
README.rst:.. image:: https://cdn.rawgit.com/cilium/cilium/master/Documentation/images/cilium_overview.png
README.rst:.. image:: https://cdn.rawgit.com/cilium/cilium/master/Documentation/images/bpf-overview.png
README.rst:.. |logo| image:: https://cdn.rawgit.com/cilium/cilium/master/Documentation/images/logo.svg
```

### PR DESCRIPTION
**Pull request by vignesh-codes**
Signed-off-by: Vigneshwaren Sunder <vickymailed@gmail.com>

Fixes: #14082

Updated readme images as Rawgit is getting shutdown. Updated the cdn.rawgit.com to cdn.jsdelivr.net

### CODE REVIEW

**Comment by vignesh-codes** [comment]
test-me-please

**Review by joestringer — CHANGES_REQUESTED** [review]
Thanks for picking this up!

You just need to update the commits to include your signoff per the docs page:

https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#developer-s-certificate-of-origin

You can achieve this by using `git rebase --interactive origin/master`, then using "fixup"  to squash the second patch into the first, then "git commit --amend -s" to add your sign-off line to the commit message. Then `git push --force origin` to update the branch on Github.

**Comment by vignesh-codes** [comment]
@joestringer I have added the signed-off acknowledgement in the above comment itself. Sorry, I'm extremely new to open source PR. Just wanted to do this documentation before looking into more issues in the cilium. 

 I ran into an error when I tried the above commands you mentioned after fetching the repo. 

' fatal: Needed a single revision '

**Comment by joestringer** [comment]
I fixed it up using your sign-off from the description, thanks!

Feel free to drop by the [Cilium Slack](https://docs.cilium.io/en/latest/community/#slack) if you need help with developing Cilium in future :-)

**Review by joestringer — APPROVED** [review]

**Pull request merged**
