### PR TITLE
v1.11 Backports 2023-03-20

### PR DESCRIPTION
**Pull request by NikAleksandrov**
* [ ] #24171 (@romanspb80)
 * [ ] #24164 (@jspaleta)
 * [x] #24373 (@christarazi)
 * [ ] #24400 (@pchaigno)
 * [ ] #24413 (@hemanthmalla)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 24171 24164 24373 24400 24413; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
make add-labels BRANCH=v1.11 ISSUES=24171,24164,24373,24400,24413
```

### CODE REVIEW

**Comment by NikAleksandrov** [comment]
I had to fix up vp -> viper in the last commit 0557a2f6e940 ("Fix for disabled cloud provider rate limiting")

**Comment by NikAleksandrov** [comment]
Also noticed a typo in commit 93ebeb3bae11 ("docs: Update the documentation for the conntrack-gc-interval flag")
I'll be sending a pr to fix it up (contrack -> conntrack)

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

(How come you're doing backports?)

**Comment by NikAleksandrov** [comment]
> My PR looks good. Thanks!
> 
> (How come you're doing backports?)

I'm first time tophat specifically for backports this week. :)

**Review by hemanthmalla — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Pull request merged**
