### PR TITLE
datapath: Redo backend selection if stale CT_SERVICE entry is found

### PR DESCRIPTION
**Pull request by brb**
Previously, the LB datapath in `lb{4,6}_local` functions was doing the CT lookup for a `CT_SERVICE` entry. If the entry was found, it was extracting backend ID and using it as the connection destination without checking whether the backend actually belonged to the service.

The absence of the check caused interesting problems when the CT entry of no longer existing endpoint was selected (this can happen due to the bug in bpf map walking with `DumpReliablyWithCallback` which can prevent the CT GC from removing CT entries of the removed endpoint; and judging from a user BPF conntrack dump it seems that a source port selection in the kernel is quite deterministic per netns, but I haven't checked why). This led to the request being sent to an endpoint of a totally unrelated service. And because `rev_nat_index` was correct, the reverse NAT translation was xlating the src IP address of a reply to the one of the expected service, so the packet was not dropped.

Another (less harmful) thing was that `lb{4,6}_lookup_slave{,_v2}` functions were modifying the given `key->slave` field without restoring upon a return, so the `lb{4,6}_lookup_service` calls for the legacy service were picking invalid backends for backward-compatibility.

--

It's worth noting that we didn't hit this issue in < `v1.5.0`, as in the case of a stale CT entry being selected, the second lookup slave lookup in `lb4_local` was using the service `key` which prevented from a wrong slave selection. 

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8037)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
@borkmann The verifier issue was hit again: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12367/testReport/junit/(root)/Suite-runtime/RuntimeVerifier_runs_the_kernel_verifier_against_the_tree_copy_of_the_BPF_datapath/

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by borkmann** [comment]
With the latest, I currently cannot reproduce in my env:
```
# git log
commit 154b4a7def2fd5f85751fd6fa42c3aab60cd07bf

In bpf/ dir:

# make clean
make -C sockops clean
[...]
# make
[...]

# clang --version
clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /root/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04/bin

# uname -a
Linux test 4.9.176 #1 SMP Wed May 15 21:28:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

In test/bpf/ dir:

# ./verifier-test.sh
=> Loading ./../../bpf/bpf_lb.c:from-netdev...
=> Loading ./../../bpf/bpf_lxc.c:from-container...
=> Loading ./../../bpf/bpf_lxc.c:to-container...
=> Loading ./../../bpf/bpf_netdev.c:from-netdev...
=> Loading ./../../bpf/bpf_netdev.c:masq...
=> Loading ./../../bpf/bpf_netdev.c:masq-pre...
=> Loading ./../../bpf/bpf_netdev.c:masq-post...
=> Loading ./../../bpf/bpf_overlay.c:from-overlay...
=> Skipping ./../../bpf/bpf_xdp.c.
Ensure you have linux >= 4.12 and recent iproute2 to test XDP.

```

**Comment by borkmann** [comment]
Reverting commit 154b4a7def2fd5f85751fd6fa42c3aab60cd07bf gets me back to the verifier error. So the fix also fixed the verifier error it seems.

**Comment by borkmann** [comment]
test-me-please

**Comment by tgraf** [comment]
Great work everyone. Any work left to do before we review and merge?

**Comment by borkmann** [comment]
Should be good for review.

**Review by tgraf — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Pull request merged**
