### PR TITLE
v1.9 backports 2021-11-09

### PR DESCRIPTION
**Pull request by pchaigno**
* #14129 -- test: Collect object file artifacts for K8sVerifier (@pchaigno)
 * #17470 -- test/K8sVerifier: Cover several datapath configurations (@pchaigno)
 * #17667 -- bug/pkg/health: Fix Nil Address Issue in Node Update Mechanism (@nathanjsweet)
 * #17756 -- docs: Use git+https in requirements.txt (@michi-covalent)
 * #17769 -- test: Do not require netpols in 'waitNextPolicyRevisions()' (@jrajahalme)
 * #17812 -- .github: Increase reporting threshold for new flakes (@pchaigno)
 * #17344 -- .github: Rename `project/ci-force` to `ci/flake` (@pchaigno)
 * #17546 -- Reduce bugtool memory usage (@tklauser)
 * #17573 -- bpf: Additional tail calls for IPvX-only setups (@pchaigno)
 * #17836 -- nodediscovery: Fix local host identity propagation (@joestringer)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14129 17470 17667 17756 17769 17812 17344 17546 17573 17836; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by pchaigno** [comment]
test-backport-1.9

**Review by nathanjsweet — APPROVED** [review]
My changes look good.

**Comment by pchaigno** [comment]
test-backport-1.9

**Review by jrajahalme — APPROVED** [review]
Backport of my PR look right :-)

**Review by tklauser — APPROVED** [review]
LGTM for my changes

**Review by joestringer — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]
:heavy_check_mark: https://github.com/cilium/cilium/pull/17835/commits/8c5a7bc94839e4d5e51f44638dbc1a5d0e741792

**Comment by pchaigno** [comment]
test-bacport-1.9

**Comment by pchaigno** [comment]
test-backport-1.9

**Comment by ti-mo** [comment]
GKE tests failing with:
`21:30:52   	 Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: ConfigMap, namespace: kube-system, name: cilium-config`

Also not sure if the 4.9 and 5.4 test failures need to be considered flakes, since they both fail for the same reason: https://github.com/cilium/cilium/issues/17617#issuecomment-971416845
`networkPlugin cni failed to set up pod "coredns-7dcc479575-mftvg_kube-system" network: unable to allocate IP via local cilium agent: [POST /ipam][502] postIpamFailure  range is full`

**Comment by gandro** [comment]
The failure in the upgrade test worries me a bit, as it indicates some incompatibilities

- https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-5.4/128/
- https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-4.9/395/

**Comment by gandro** [comment]
/test-1.17-4.9

**Comment by gandro** [comment]
/test-1.17-5.4

**Comment by gandro** [comment]
/test-1.17-5.4

**Comment by gandro** [comment]
/test-1.17-4.9

**Comment by pchaigno** [comment]
> Edit: It keeps failing without any error https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-4.9/400/

It seems the VM startup hit the 15m timeout. The tests themselves then ended after exactly 1h30, which looks suspiciously like a timeout but timeout value should be 3h. Maybe worth comparing all the timeouts in the Jenkinsfile with v1.10 and master to see if we're not just missing a fix on timeouts?

**Comment by gandro** [comment]
> It seems the VM startup hit the 15m timeout. The tests themselves then ended after exactly 1h30, which looks suspiciously like a timeout but timeout value should be 3h. Maybe worth comparing all the timeouts in the Jenkinsfile with v1.10 and master to see if we're not just missing a fix on timeouts?

There is a 98 minute timeout here that I don't see on master:
https://github.com/cilium/cilium/blob/bb44128bbd43eb8451673a8892851994a1d40662/jenkinsfiles/ginkgo-kubernetes-all.Jenkinsfile#L43

The Jenkinsfile setup on v1.9 is completely different than on master. I'm not familiar with the setup, would need to spend some time understanding it first.

---

I'm going ahead and merging this PR. As I said, GKE has been broken on v1.9 for a while and the flake on the upgrade test (`ipam: range is full`) needs to be investigated, but it seems unrelated, as I don't see any changes at all to the endpoint control plane in this PR. 

For future reference: https://github.com/cilium/cilium/issues/17617

**Review by gandro — APPROVED** [review]

**Pull request merged**
