### PR TITLE
v1.12 Backports 2024-01-24

### PR DESCRIPTION
**Pull request by giorio94**
* [x] #30207 (@giorio94)
    - ℹ️ Hit multiple conflicts due to the absence of the helm-default action in the v1.12 branch, resolved updating the chart-dir path as appropriate. Additionally, skipped the hunks for workflows which did not exist in v1.12.
 * [ ] #28286 (@tamilmani1989)
   - :warning: Hit multiple conflicts due to the documentation structure refactoring. Adapted the index pages and moved the main content to `Documentation/{gettingstarted,concepts/networking/ipam}` for consistency. Please double check.
 * [x] #30335 (@giorio94)
 * [x] #30167 (@viktor-kurchenko)
   - ⚠️ Hit conflicts due to `cilium` to `cilium-dbg` renaming, resolved running `git cherry-pick -Xrename-threshold=20% $SHA`. Please double check.

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30207 28286 30335 30167
```

### CODE REVIEW

**Review by viktor-kurchenko — APPROVED** [review]
IPsec encrypt changes LGTM. Thank you!

**Comment by giorio94** [comment]
/test-backport-1.12

**Comment by giorio94** [comment]
/test-1.24-net-next

**Review by aanm — APPROVED** [review]

**Review by squeed — APPROVED** [review]

**Comment by squeed** [comment]
Somehow a reviewer from ci-structure wasn't selected. Picked @brlbil at random.

**Review by brlbil — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Docs structure looks good

**Comment by giorio94** [comment]
CI is green, are reviews are in. Marking as ready to merge.

**Pull request merged**
