### PR TITLE
cilium, netkit: Add CI e2e coverage

### LINKED ISSUE #32939: CI: e2e integration for netkit
See https://github.com/cilium/cilium/pull/32429

Blocked on a few kernel patches, then we can add e2e tests to main CI for netkit. Plan is to add the coverage before the release hence self-assign and adding as 1.16.0 blocker.

### PR DESCRIPTION
**Pull request by borkmann**
Add various netkit and netkit-l2 test coverage to CI:

 - netkit/netkit-l2 with recommended performance profile (https://docs.cilium.io/en/latest/operations/performance/tuning/)
 - netkit/netkit-l2 with vxlan/geneve

Closes: https://github.com/cilium/cilium/issues/32939

Related LVH changes:
- bpf tree support: https://github.com/cilium/little-vm-helper-images/pull/525
- build for CI: https://github.com/cilium/little-vm-helper-images/pull/527

### CODE REVIEW

**Review by brlbil — APPROVED** [review]

**Comment by borkmann** [comment]
(all newly added e2e tests passed)

**Pull request merged**
