### PR TITLE
test: Fix pkg/kvstore/store unit tests taking more than 5 minutes

### LINKED ISSUE #10560: Find out reason why pkg/kvstore/store unit tests take > 5 minutes to complete
steps to run unit tests:
`make start-kvstores && cd pkg/kvstore/store && go test ./...`

### PR DESCRIPTION
**Pull request by sayboras**
Fixes: https://github.com/cilium/cilium/issues/10560

## Testing

Now the unit tests are taking around 40+ seconds

<details>
<summary><b>Unit test output</b></summary>

```shell script
$ make start-kvstores && cd pkg/kvstore/store && go test ./...
Starting key-value store containers...
docker rm -f "cilium-etcd-test-container" 2> /dev/null
cilium-etcd-test-container
docker run -d \
        -e ETCD_UNSUPPORTED_ARCH=amd64 \
        --name "cilium-etcd-test-container" \
        -p 4002:4001 \
        quay.io/coreos/etcd:v3.3.20 \
        etcd -name etcd0 \
        -advertise-client-urls http://0.0.0.0:4001 \
        -listen-client-urls http://0.0.0.0:4001 \
        -listen-peer-urls http://0.0.0.0:2380 \
        -initial-cluster-token etcd-cluster-1 \
        -initial-cluster-state new
849376269c8f95fc6465888199b0100f73ff6858783b3e71c373b185d59239ce
docker rm -f "cilium-consul-test-container" 2> /dev/null
cilium-consul-test-container
rm -rf /tmp/cilium-consul-certs
mkdir /tmp/cilium-consul-certs
cp /home/tammach/go/src/github.com/cilium/cilium/test/consul/* /tmp/cilium-consul-certs
chmod -R a+rX /tmp/cilium-consul-certs
docker run -d \
        --name "cilium-consul-test-container" \
        -p 8501:8443 \
        -e 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true, "disable_update_check": true}' \
        -v /tmp/cilium-consul-certs:/cilium-consul/ \
        consul:1.7.2 \
        agent -client=0.0.0.0 -server -bootstrap-expect 1 -config-file=/cilium-consul/consul-config.json
f856ef82bf792fc91eae67ac8a1314f9ebf460431ab03cbf16beb7175f887fa0
ok      github.com/cilium/cilium/pkg/kvstore/store      42.963s

```

</details>

```release-note
Improve unit test for kvstore
```

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]
Awesome contribution :tada:  Thanks a lot!

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by sayboras** [comment]
One of the build failed, I tried to check the console log in jenkins, but unable to find out anything meaningful. Might need your help for some pointer

```
20:13:14  VirtualBox is complaining that the kernel module is not loaded. Please
20:13:14  run `VBoxManage --version` or open the VirtualBox GUI to see the error
20:13:14  message which should contain instructions on how to fix this error.
```

**Review by ianvernon — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
Nice work 🚀 thank you!

**Comment by tklauser** [comment]
test-with-kernel

**Comment by qmonnet** [comment]
test-me-please

**Review by qmonnet — APPROVED** [review]

**Pull request merged**
