### PR TITLE
Remove yaml parser from cilium policy trace

### LINKED ISSUE #22243: Sanitize or remove YAML support from cilium policy trace
The feature triggered by the following code does not properly sanitize the incoming YAML:

https://github.com/cilium/cilium/blob/b1aa5374acf77a598e8f5a6d69cbc53122812d62/cilium/cmd/policy_trace.go#L181-L182

This feature is unlikely to be used by anyone so we could just remove it.

### PR DESCRIPTION
**Pull request by rushi47**
Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Fixes: #22243

### CODE REVIEW

**Review by joestringer — APPROVED** [review]
Thanks, the code looks good to me.

Could you change one thing - amend the PR title and git commit (`git commit --amend`) so that the name is something like `Remove yaml parser from cilium policy trace`? Otherwise the release note sounds like we might be removing YAML parsing the whole of cilium, which is not the case.

**Review by aanm — APPROVED** [review]

**Comment by joestringer** [comment]
Actually, looking a little deeper, it seems that some additional code can be removed, could you remove this function too?

```
$ git grep GetLabelsFromYaml
cilium/cmd/policy_trace.go:                     srcYamlSlices, err := trace.GetLabelsFromYaml(srcK8sYaml)
cilium/cmd/policy_trace.go:                     dstYamlSlices, err := trace.GetLabelsFromYaml(dstK8sYaml)
pkg/policy/trace/yaml.go:// GetLabelsFromYaml iterates through the provided YAML file and for each
pkg/policy/trace/yaml.go:func GetLabelsFromYaml(file string) ([][]string, error) {
```

**Review by joestringer — CHANGES_REQUESTED** [review]
Just updating my review to make it clear that there's a couple of requested changes above - title and remove one extra piece of code.

**Comment by rushi47** [comment]
@joestringer  done ! 👌  I looked for references of function before removing and looks to be good

**Comment by joestringer** [comment]
@rushi47 rebase shouldn't be necessary (though it wouldn't hurt). The main thing would be to make sure that all commits are signed off. Otherwise it looks good.

**Comment by rushi47** [comment]
> @rushi47 rebase shouldn't be necessary (though it wouldn't hurt). The main thing would be to make sure that all commits are signed off. Otherwise it looks good.

Ahh yeah I forgot to add sign off done.

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
I've triggered CI. Assuming it passes this should be good to merge. I'll keep an eye out. Thanks for the contribution!

**Comment by joestringer** [comment]
golang-ci-lint complains:

```
run golangci-lint
  Running [/home/runner/golangci-lint-1.48.0-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  Error: func `generateLabels` is unused (unused)
```

You should be able to test this also locally using `make golangci-lint`.

BPF checks also complain that the signoff is not the same as the author. If you look at `git log --pretty=fuller -2`, you should be able to see what the author is set to and what the signoff lines report. You could either amend the commits to refresh the author to align with the signoff lines or update the signoff lines to match the author formatting. If you have git configured beforehand, then `git commit --signoff` should already align these two to be the same.

**Review by joestringer — CHANGES_REQUESTED** [review]
See above for some pointers how to get CI to pass.

**Comment by rushi47** [comment]
@joestringer  then yaml.go file becomes empty and then making trace folder as well empty so have removed trace folder all together ?
```
├── trace
   └── yaml.go
```

And after doing that in general ci throws this error :
```
docker run --rm -v `pwd`:/app -w /app docker.io/golangci/golangci-lint:v1.48.0@sha256:5e4256fd5001c1c6ec3de3d31fdae2fa2af6dd21ebbb86b3ddfe1925376af326 golangci-lint run
pkg/alibabacloud/api/api.go:16:2: could not import github.com/aliyun/alibaba-cloud-sdk-go/services/vpc (-: could not load export data: no export data for "github.com/aliyun/alibaba-cloud-sdk-go/services/vpc") (typecheck)
	"github.com/aliyun/alibaba-cloud-sdk-go/services/vpc"
	^
pkg/ipam/allocator/alibabacloud/alibabacloud.go:11:2: could not import github.com/aliyun/alibaba-cloud-sdk-go/services/vpc (-: could not load export data: no export data for "github.com/aliyun/alibaba-cloud-sdk-go/services/vpc") (typecheck)
	"github.com/aliyun/alibaba-cloud-sdk-go/services/vpc"
	^
make: *** [golangci-lint] Error 1
```
Not sure if it's because of my changes or this is normal ?

**Review by joestringer — APPROVED** [review]
LGTM thanks. CI looks good except for one thing: The linter for commit messages expects the commits to be in the following form:

```
area: Change foo

<optional description>

Signed-off-by: Foo bar <foo@bar.com>
```

In particular there should typically be an empty line above the sign-off line. I can fix it up in this case but it's something to keep in mind if you make subsequent submissions.

**Pull request merged**
