### PR TITLE
Revert: pkg/bpf: Use the other directory when /sys/fs/bpf is not BPFFS

### PR DESCRIPTION
**Pull request by aanm**
**Summary of changes**:

Revert PR #3786
Reopens: #3717

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4280)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by joestringer** [comment]
I've seen complete breakage of `cilium monitor` with the PR #3786 that is being reverted here:

```
# cilium monitor
Press Ctrl-C to quit
Error: unable to connect to monitor dial unix /var/run/cilium/monitor.sock: connect: connection refused
command terminated with exit code 1
```

Also, policy behaviour seems to have been impacted, I observed an application using k8s nodeport which previously worked fine, as soon as I upgraded to recent master with PR #3786 my application immediately begin serving 403s (seemingly from the proxy?).

I tested with an image generated from this PR here and it resolved all of my issues: http://quay.io/cilium/cilium:e72f3787b

**Review by joestringer — APPROVED** [review]
This resolves multiple known issues on master:

* `cilium monitor` breakage (`connect: connection refused`)
* 403s from proxy on valid policy
* Cilium dev VM cilium cannot start (multiple BPF FS mounts exist under /sys/fs/bpf/ -> agent refuses to start)

**Review by tgraf — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
