### PR TITLE
chore(lint): To enable linter for test files

### PR DESCRIPTION
**Pull request by sayboras**
To enable the same linting rules for *_test files as well

Signed-off-by: Tam Mach <sayboras@yahoo.com>

Some ground work for https://github.com/cilium/cilium/pull/11554#issuecomment-631347734

/cc @mrostecki 

```release-note
chore(lint): To enable linter for test files
```

### CODE REVIEW

**Comment by mrostecki** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]
Looks good. Thanks! I will wait for this PR to be merged before rebasing my PR.

**Review by aanm — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by sayboras** [comment]
All the jenkins job were completed successfully.

I just realize that I used the wrong name in commit log. So will need to force push to correct it.

**Review by gandro — APPROVED** [review]
Hubble changes LGTM!

**Pull request merged**
