### PR TITLE
v1.4 backports 2019-09-06

### PR DESCRIPTION
**Pull request by aanm**
* #9057 -- istio: Update to 1.2.5 (@jrajahalme)
 * #9133 -- Dockerfile: Use Envoy image with access logging fixes (@jrajahalme)
 * #9101 -- test: fix k8s upstream test (@aanm)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 9057 9133 9101; do contrib/backporting/set-labels.py $pr done 1.4; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9150)

### CODE REVIEW

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by ianvernon** [comment]
apt download problems: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2456/execution/node/182/log/

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-missed-k8s

**Pull request merged**
