### PR TITLE
Cilium Endpoint Slices refactor and test improvements

### PR DESCRIPTION
**Pull request by sypakine**
This change has a small refactor to CiliumEndpointSlice (CES) subscriber update and delete methods.

It also includes many more test cases for all public subscriber methods, including test cases/transitions that did not have coverage.

```release-note
Refactor the CiliumEndpointSlice subscriber public methods and increase test coverage
```

### CODE REVIEW

**Review by nebril — APPROVED** [review]
LGTM, thanks!

**Comment by sypakine** [comment]
Added release-note block, `release-note/misc` label is most appropriate.

**Pull request merged**
