### PR TITLE
[1.3] policy: Fix ipcache synchronization on startup

### PR DESCRIPTION
**Pull request by tgraf**
* policy: Fix ipcache synchronization on startup [#7139]

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7228)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by jrfastab — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
```
12:31:31 # github.com/cilium/cilium/daemon
12:31:31 daemon/daemon.go:1158: undefined: err
12:31:31 daemon/daemon.go:1159: undefined: err
12:31:31 daemon/daemon.go:1160: undefined: err
12:31:31 daemon/daemon.go:1161: undefined: err
12:31:31 FAIL	github.com/cilium/cilium/daemon [build failed]
```

**Comment by tgraf** [comment]
Closing in favor of #7234

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-missed-k8s

**Pull request merged**
