### PR TITLE
ci: update cilium-cli to 0.9.1

### PR DESCRIPTION
**Pull request by nebril**
Let's merge this after cli 0.9.1 is released

### CODE REVIEW

**Review by tklauser — APPROVED** [review]

**Comment by tklauser** [comment]
FYI, now that the release is actually there I've re-triggered the kind workflow which was previously failing due to the release not existing yet.

**Review by ldelossa — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
We need a test commit to run the workflows with this version, right?

**Review by joestringer — APPROVED** [review]

**Comment by nbusseneau** [comment]
In test PR we did get a DNS failure still in https://github.com/cilium/cilium/actions/runs/1277574393 during the second connectivity test (with encryption enabled) :/

**Comment by pchaigno** [comment]
DNS is always the first thing to fail when there are connectivity issues, so that's not really a distinguishing feature ;-)

I don't see any `to-proxy` traces in tests without proxy redirects, so I don't think those failures are the same issue.

Note the `to-proxy` failure may still happen in connectivity checks after IPsec (though it doesn't appear to be the case here) because, even though we reordered tests in the checks, the first few tests after enabling IPsec may still conflict with the last few tests before enabling IPsec. A fix for that could be to flush the conntrack map in between the two connectivity check runs in our workflows. Nevertheless, I'd rather wait to see how prevalent that issue is before sending such a fix.

**Review by nbusseneau — APPROVED** [review]
:shipit:

**Comment by nebril** [comment]
repushed a commit with proper formatting, bpf job was complaining about lack of commit description

**Comment by kaworu** [comment]
Should this PR be marked with `needs-backport/v1.10`? See [this PR](https://github.com/cilium/cilium/pull/17143) that is going to be backported ([backport PR](https://github.com/cilium/cilium/pull/17392)).

**Comment by nbusseneau** [comment]
> Should this PR be marked with `needs-backport/v1.10`? See [this PR](https://github.com/cilium/cilium/pull/17143) that is going to be backported ([backport PR](https://github.com/cilium/cilium/pull/17392)).

Yes, it should be backported so that the Kind workflow uses the right CLI version.

**Pull request merged**
