### PR TITLE
Merge clustermesh-apiserver and kvstoremesh into a single image

### PR DESCRIPTION
**Pull request by giorio94**
Reporting here the message from the main commit for convenience:

```
Merge the kvstoremesh logic into the clustermesh-apiserver as a separate
subcommand, so that we can get rid of one image and reduce the overall
time to bootstrap the clustermesh-apiserver deployment. The additional
boilerplate to build the kvstoremesh images is dropped.

Size of the images before this change:
$ make docker-clustermesh-apiserver-image
$ docker inspect -f '{{ .Size }}' quay.io/cilium/clustermesh-apiserver:latest | \
         numfmt --to=si --suffix=B --format="%.2f"
---> 72.09MB
$ make docker-kvstoremesh-image
$ docker inspect -f '{{ .Size }}' quay.io/cilium/kvstoremesh:latest | \
         numfmt --to=si --suffix=B --format="%.2f"
---> 64.62MB

Size of the image after this change:
$ make docker-clustermesh-apiserver-image
$ docker inspect -f '{{ .Size }}' quay.io/cilium/clustermesh-apiserver:latest | \
         numfmt --to=si --suffix=B --format="%.2f"
---> 72.26MB
```

~~Depends on https://github.com/cilium/cilium/pull/27823, https://github.com/cilium/cilium/pull/27817, https://github.com/cilium/cilium/pull/27873~~

To be discussed in the next community meeting: should we rename the clustermesh-apiserver pod/image to something more expressive which better highlights the new structure (the container is planned to be extended to include the etcd binary, as well as the current init-container logic)? This would require a fairly large amount of CI changes (some of which will likely only pop-up during the next release), as well as make backporting of CI changes more tricky in the future.  

```release-note
Merge clustermesh-apiserver and kvstoremesh into a single image
```

### CODE REVIEW

**Comment by giorio94** [comment]
Conformance Cluster Mesh hit https://github.com/cilium/cilium/issues/27672

**Comment by giorio94** [comment]
Converting back to draft. I'm going to split this PR into multiple ones to reduce the size.

**Comment by giorio94** [comment]
A couple of preliminary commits have been extracted into their own PRs to reduce the size of this one, and have been merged. I've rebased this PR onto main, before marking it ready for review again. Now, it only shuffles things around, and performs the necessary adaptations.

In the end, I've preserved the clustermesh-apiserver image name. The reason being that changing it would be a quite significant effort to adapt the CI, renovate configs and alike, but bringing little value, as the clustermesh-apiserver name would still used in all user-facing resources. And changing it also for the user-facing ones would be complex in terms of backward compatibility (especially concerning helm settings), and could end up bringing more confusion than clarity (as users currently recognize the clustermesh-apiserver as the control plane for clustermesh). Happy to reconsider if anyone has strong opinions against the current approach though.

**Review by asauber — APPROVED** [review]
CLI-related changes look good

**Review by viktor-kurchenko — APPROVED** [review]
LGTM.

**Review by aditighag — APPROVED** [review]
Approving for the CODEOWNERS file changes.

**Review by sayboras — APPROVED** [review]

**Pull request merged**
