### PR TITLE
vagrant: update net-next to 141

### PR DESCRIPTION
**Pull request by aanm**
This VM contains the containerd container rumtime that is going to be
used with Kubernetes 1.24 as Kubernetes dropped support for docker.

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
/test-1.23-net-next

**Review by tklauser — APPROVED** [review]

**Comment by aanm** [comment]
/test-1.23-net-next

**Comment by aanm** [comment]
/test-1.23-net-next

**Review by aditighag — CHANGES_REQUESTED** [review]
There are some changes missing for the dev VM where the default runtime is set to `docker` - 

http://github.com/cilium/cilium/tree/master/contrib/vagrant/scripts/helpers.bash#L53-L53


https://docs.cilium.io/en/latest/contributing/development/dev_setup/

>RUNTIME=x: Sets up the container runtime to be used inside a kubernetes cluster. Valid options are: docker, containerd and crio. If not set, it defaults to docker.

**Comment by aanm** [comment]
> There are some changes missing for the dev VM where the default runtime is set to `docker` -
> 
> [http://github.com/cilium/cilium/tree/master/contrib/vagrant/scripts/helpers.bash#L53-L53](https://github.com/cilium/cilium/tree/master/contrib/vagrant/scripts/helpers.bash#L53-L53)
> 
> https://docs.cilium.io/en/latest/contributing/development/dev_setup/
> 
> > RUNTIME=x: Sets up the container runtime to be used inside a kubernetes cluster. Valid options are: docker, containerd and crio. If not set, it defaults to docker.

@aditighag the default runtime can still be docker, the default runtime should be changed by https://github.com/cilium/cilium/pull/19545 because that's when K8s 1.24 is being introduced.

**Comment by aanm** [comment]
depends on https://github.com/cilium/cilium/pull/19690

**Comment by aanm** [comment]
/test-1.23-net-next

**Comment by aanm** [comment]
/test-1.23-net-next

**Comment by aanm** [comment]
previous test failure https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-net-next

**Comment by aanm** [comment]
/test-only --focus="K8sChaosTest.*TCP connection is not dropped when cilium restarts" --k8s_version=1.23 --kernel_version=net-next

**Comment by aanm** [comment]
/test-only --focus="K8sChaosTest.*TCP connection is not dropped when cilium restarts" --k8s_version=1.23 --kernel_version=net-next

**Comment by aanm** [comment]
/test-only --focus="K8sChaosTest.*TCP connection is not dropped when cilium restarts" --k8s_version=1.23 --kernel_version=net-next

**Comment by aanm** [comment]
The https://jenkins.cilium.io/job/Cilium-PR-Tests-Kernel-Focus/435/ failed and I can only assume it's a regression in the net-next kernel since the only change on that commit was the VM version bump. It looks that the machine is rebooted (see the kubelet logs) because of running netperf. Thus, I'll skip these tests in net-next for now /cc @pchaigno

**Comment by aanm** [comment]
/test-1.23-net-nex

**Comment by aanm** [comment]
/test-1.23-net-next

**Comment by aanm** [comment]
/test-1.23-net-next

**Comment by aanm** [comment]
/test-1.23-net-next

**Comment by aanm** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
Sorry, I need that branch :stuck_out_tongue_closed_eyes:

**Pull request closed without merging**
