### PR TITLE
Remove sockops from eBPF datapath diagrams

### LINKED ISSUE #24735: docs: Update diagram to remove mention of sockops
Sockops and friends have been removed in https://github.com/cilium/cilium/pull/23606. Anton reported that they're still referenced in a picture in the docs. We want to update that picture to remove these outdated references.

    Pictures (`cilium/Documentation/network/ebpf/_static/cilium_bpf_*.svg`) will still refer to sockmap et al.

_Originally posted by @aspsk in https://github.com/cilium/cilium/pull/23606#discussion_r1155745372_

### PR DESCRIPTION
**Pull request by zacharysarah**
Fixes: #24735 

```release-note
docs: Remove sockops, sockmaps from eBPF datapath diagrams
```

### CODE REVIEW

**Review by qmonnet — CHANGES_REQUESTED** [review]
Thanks a lot! I have three comments:

- Sockmaps are gone as well, along with sockops. File `bpf_redir.c` was entirely removed in 87c8746e254d2b3ccdf8a42bb48367b6ecf2890f. Could you please remove the corresponding boxes as well?

- The title of some diagrams refers to sockmaps and should also be updated. The version numbers as well, I suppose.

- Could we maybe adjust the size of the frames that contained the removed boxes on the diagrams (maybe narrow down the entire diagram by also moving the keys when relevant)? The resulting diagrams currently have frames with some empty spaces, just as if something in it was missing. This might be easier with an SVG editor rather than a text editor.

**Comment by zacharysarah** [comment]
@qmonnet 👋🏻 

> Sockmaps are gone as well, along with sockops. File bpf_redir.c was entirely removed in https://github.com/cilium/cilium/commit/87c8746e254d2b3ccdf8a42bb48367b6ecf2890f. Could you please remove the corresponding boxes as well?

👍🏻 

> The title of some diagrams refers to sockmaps and should also be updated. The version numbers as well, I suppose.

👍🏻 

> Could we maybe adjust the size of the frames that contained the removed boxes on the diagrams

Exactly the point of my reviewer note in the OP. 🎯 

> This might be easier with an SVG editor rather than a text editor.

I've never actually edited an SVG with an SVG editor before. I welcome your recommendation about which editor you think would work best.

**Comment by zacharysarah** [comment]
@velp

**Comment by zacharysarah** [comment]
@qmonnet 👋🏻 PTAL

**Review by qmonnet — COMMENTED** [review]
Thanks! The diagrams look better now.

I've got a few comments on the second one (cilium_bpf_endpoint.svg):

- Should it be renamed `v1.13` Datapath instead of `v1.x`? It's not clear to me why one is `1.x` and the others have a fixed version number. Maybe I'm missing some context.

- Should we remove the bottom part of the diagram? Now that sockops/sockmaps have been removed from it, I'm not sure there's much interest in keeping that part.

Other than these, looks good to me.

I'll add a request review from Joe who has a good vision of the datapath and should be able to tell if we missed something that is outdated?

**Comment by zacharysarah** [comment]
@qmonnet 👋🏻 
> Should it be renamed v1.13 Datapath instead of v1.x?

I kept 1.x because it's unique in current version (the others were 1.8). I'm happy to change it.

> Should we remove the bottom part of the diagram?

That's my thought as well, but didn't want to presume. @joestringer WDYT? 🙏🏻

**Review by joestringer — APPROVED** [review]
LGTM. I think we could follow up to add the bpf_sock logic for socket-level L4 LoadBalancing, but that can be a separate submission on top IMO.

**Review by qmonnet — APPROVED** [review]
Looks all good to me as well, thanks a lot for working on this!

**Comment by qmonnet** [comment]
Doc change only, with Documentation workflow passing. We have reviews from all code-owner teams (Anton was pulled for cilium/sig-datapath, but Joe and I are part of that team as well). I'm just changing the release-note label to `misc` as there's no functionality change, and marking as ready-to-merge.

**Pull request merged**
