### PR TITLE
v1.13 Backports 2023-01-23

### PR DESCRIPTION
**Pull request by aanm**
* [ ] #23009 -- daemon: Fix BPF host routing can't be enabled if the devices are wildcard (@ysksuzuki)
 * [ ] #22975 -- Bpf: Add missing policy match cases (@jrajahalme)
 * [x] #22671 -- ingress/model: Support multiple certs based on SNI (@sayboras)
 * [ ] #23095 -- docs: Improve wording for deny policies limitation (@joestringer)
 * [x] #23135 -- docs: Improve IPsec guide (@pchaigno)
 * [ ] #22408 -- hubble: Update the reason label for hubble_drop_total metric (@michi-covalent)
 * [ ] #23124 -- Bump Linux minimum version to 4.19.57 (or equivalent) (@joestringer)
 * [x] #23141 -- Document socket LB tracing (@aditighag)
 * [ ] #23140 -- build(deps): update package dependencies (@fengshunli)
 * [ ] #23134 -- docs: update committer security requirements (@xmulligan)
 * [x] #23099 -- gha: Pin minikube version used in CI (@sayboras)
 * [ ] #23025 -- docs: Mark pod-short option in Hubble metrics as deprecated (@lambdanis)
 * [ ] #22756 -- bpf: nodeport: handle revDNAT for local backends at to-netdev/to-overlay (@julianwiedmann)
 * [x] #23158 -- IPsec: Refactor `ipSecReplaceState{In,Out}` functions (@pchaigno)
 * [x] #23195 -- gh: fix indentation bug in ingress workflows (@julianwiedmann)
 * [ ] #22695 -- refactoring of fetching cilium manifests in OKD installation (@zisisli)
 * [ ] #22913 -- docs: Update Minikube ver. requirement and manual BPFFS mount instructions   (@kimstacy)
 * [x] #23225 -- docs: Fix inconsistent node label in egress gateway guide (@pchaigno)
 * [ ] #23163 -- images/runtime: bump iptables package to 1.8.8 (@jibi)

PRs skipped due conflicts:

 * #22425 -- gh/workflows: tune LVH VM params (@brb)
 * #22928 -- CODEOWNERS: Cover test/bpf_tests by sig-datapath (@christarazi)
 * #23020 -- ci: extend nat46x64 l4lb test suite (@borkmann)
 * #23145 -- Use workflow configuration variables for quay organization names (@michi-covalent)
 * #23137 -- clustermesh/types: don't panic on invalid IP in PrefixClusterFromCIDR (@tklauser)
 * #23170 -- k8s/watchers: Fix race condition in init functions (@christarazi)
 * #21980 -- datapath: Fix L7 reply to outside when endpoint routes disabled (@brb)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 23009 22975 22671 23095 23135 22408 23124 23141 23140 23134 23099 23025 22756 23158 23195 22695 22913 23225 23163; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
$ make add-label BRANCH=v1.13 ISSUES=23009,22975,22671,23095,23135,22408,23124,23141,23140,23134,23099,23025,22756,23158,23195,22695,22913,23225,23163
```

### CODE REVIEW

**Comment by aanm** [comment]
/test-backport-1.13

**Review by sayboras — APPROVED** [review]
Looks good on my commits :100:

**Review by pchaigno — APPROVED** [review]
My 3 PRs look good to me. Thanks!

**Review by jibi — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Comment by aanm** [comment]
/test-backport-1.13

**Review by ghost — APPROVED** [review]

**Comment by aanm** [comment]
previous runtime https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/4634

**Review by aditighag — APPROVED** [review]

**Comment by aanm** [comment]
k8s-1.21-kernel-4.9 hit https://github.com/cilium/cilium/issues/23047
k8s-1.26-kernel-net-next hit https://github.com/cilium/cilium/issues/21519

**Review by nathanjsweet — APPROVED** [review]

**Review by chancez — APPROVED** [review]
I don't have any PR changes in this backport, so marking approved? (Is this right? I don't think I can review the entire PR diff. I got assigned via sig-hubble).

**Comment by aanm** [comment]
Merging this one since the failure in Cilium-PR-K8s-1.18-kernel-4.9 was not seen in other tests runs with the same kernel version and different k8s version. We will re-run a full CI in https://github.com/cilium/cilium/pull/23243 as well to have more data.

**Pull request merged**
