### PR TITLE
Aspsk/backports to v1.12

### PR DESCRIPTION
**Pull request by aspsk**
Backport of the following PRs:

* https://github.com/cilium/cilium/pull/20711 (@aspsk)
* https://github.com/cilium/cilium/pull/20859 (@aspsk)

### CODE REVIEW

**Review by gandro — APPROVED** [review]

**Comment by gandro** [comment]
/test-backport-1.12

**Comment by sayboras** [comment]
All failed workflows are disabled on master due to flakiness. Marking ready to merge.

**Pull request merged**
