### PR TITLE
Add k8s 1.16 support

### PR DESCRIPTION
**Pull request by aanm**
```release-note
Add support for k8s 1.16
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9139)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
never-tell-me-the-odds

**Review by nebril — APPROVED** [review]

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
