### PR TITLE
test: Fix some k8s helpers

### PR DESCRIPTION
**Pull request by aanm**
Small fixes made to some helpers. Check per commit for their reason.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5445)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by eloycoto** [comment]
LGTM, let's wait until test pass to approve.

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
@aanm @eloycoto This change relies on several other changes in master that are not in `v1.2`. How critical is the backport of this PR?

**Comment by aanm** [comment]
@tgraf It's critical if we want to backport the etcd-operator CI tests

**Comment by eloycoto** [comment]
I don't think that CI test can be backported at all, the `kubectl patch` is introduced and it'll be hard to backport.

**Comment by ianvernon** [comment]
@aanm what makes it critical for us backporting the etcd-operator tests? Please provide a justification. We have no service pre-flight checks in the v1.2 branch at all: https://github.com/cilium/cilium/blob/cd2f0c4d8fd64ff3b94ff4ceadb927aab5d0a7fd/test/helpers/kubectl.go#L1313-L1336

This makes me question the need for this backport. I cannot cherry-pick this cleanly without backporting all service preflight checks.

**Comment by aanm** [comment]
@ianvernon if precheck is not in 1.2 then only `f1bf1a0fcdcda24252c17aa1f3f936fb6bde1b19` is need to be backported.

**Comment by ianvernon** [comment]
@aanm there are no service preflight checks in v1.2, so why does f1bf1a0fcdcda24252c17aa1f3f936fb6bde1b19 need to be backported?

**Comment by aanm** [comment]
@ianvernon  @borkmann I meant aabb91a8148a892b2d9d52735db178bd5cbc3cdb not f1bf1a0fcdcda24252c17aa1f3f936fb6bde1b19 sorry.

**Comment by ianvernon** [comment]
@aanm those commits still require service preflight checks to be in v1.2. To backport this, we'd have to require backporting the `ServicePreflightCheck` framework. Please specify why this is necessary for v1.2;  if the `ServicePreflightCheck` is not in v1.2 now, why do we need to backport it?

**Comment by eloycoto** [comment]
@aanm I do not think that this PR need to backported, the services is not in there and no reason to merge at all, if you can address @ianvernon comment will be great.

**Pull request merged**
