### PR TITLE
istio: Use cilium-istioctl instead of helm directly

### PR DESCRIPTION
**Pull request by jrajahalme**
Istio GSG and Istio CI test are modified to downloading the current
version of the cilium-istioctl and use it for Istio deployment.

Istioctl bundles the helm charts and uses a helm library to configure
Kubernetes. Cilium version (cilium-istioctl) adds support for
Cilium-specific configuration of the sidecar proxies and defaults to
Cilium builds of pilot and sidecar proxy so that the user does not
need to set the images explicitly.

'bookinfo-gateway.yaml' is added to examples so that it can be used in
the GSG without requiring downloading Istio yamls.

Both Istio GSG and the CI test now use a namespace label for automatic
sidecar injection. This simplifies application deployment and allows
easier future CI updates as pre-formed application/Istio yamls can now
be removed.

```release-note
Istio integration is simplified with Cilium build of istioctl.
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-gke K8sIstio.*

**Comment by jrajahalme** [comment]
test-gke K8sIstio.*

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-gke K8sIstio.*

**Comment by jrajahalme** [comment]
test-gke K8sIstio.*

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-gke K8sIstio.*

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-gke K8sIstio.*

**Comment by jrajahalme** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
`+94 −11,358`

:tada: 

LGTM

**Review by aanm — APPROVED** [review]
:tada:

**Pull request merged**
