### PR TITLE
bpf: bpf based masq for nodeport to avoid tuple clashes

### PR DESCRIPTION
**Pull request by borkmann**
See commit msg /cc @brb.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8649)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Hit #7615

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Pull request merged**
