### PR TITLE
Manual backport of "datapath: Do not log if svc is not found" to v1.7

### PR DESCRIPTION
**Pull request by brb**
[ upstream commit f3c40a729d7c6c88c21093e63ebfa61d3e0cc3d8 ]

We used to log (via cilium_dbg) when a packet dst IP + port did not
match any service, e.g:

    CPU 20: MARK 0xbc243a3b FROM 0 DEBUG: Master service lookup failed, addr.p2=0 addr.p3=0

This added a lot of noise to `cilium monitor -D` output, especially when
bpf_netdev.o was attached to a native device (e.g when BPF NodePort was
enabled), as any inbound packet does a service lookup.

This commit removes the logging when a svc is not found. The fact that
a svc is not found can be deduced from a missing lookup svc endpoint log
message.

/cc @tklauser

### CODE REVIEW

**Comment by brb** [comment]
never-tell-me-the-odds

**Review by tklauser — APPROVED** [review]
Thanks for doing the manual backport!

**Comment by brb** [comment]
never-tell-me-the-odds

**Comment by brb** [comment]
Hit the Kafka CI flake.

**Comment by brb** [comment]
never-tell-me-the-odds

**Comment by tklauser** [comment]
Seems to have hit the kafka flake again. @brb if you want I can pull this commit into the #10756 backports PR which has cherry-picked the fixes for the kafka tests.

**Comment by brb** [comment]
@tklauser Yes, please.

**Comment by tklauser** [comment]
Picked it up into #10756, thus closing this PR. Thanks.

**Pull request closed without merging**
