### PR TITLE
Fix cilium prefilter delete

### PR DESCRIPTION
**Pull request by borkmann**
See commit msg.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9385)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
:shipit:

**Comment by borkmann** [comment]
test-me-please

**Review by brb — APPROVED** [review]
LGTM! Would be nice to have some tests, but it could be done in a separate PR.

Considering that's a fix, do we want to backport it?

**Comment by borkmann** [comment]
> LGTM! Would be nice to have some tests, but it could be done in a separate PR.
> 
> Considering that's a fix, do we want to backport it?

We probably could, but then we'd need both PRs. I'll mark it for 1.6, and open a ticket for test cases.

**Pull request merged**
