### PR TITLE
docker, runtime: Update iproute2 and bpftool images

### LINKED ISSUE #18281: Fix the `verbose` flag of `tc` to dump the verifier logs
The `verbose` flag of the `tc filter` command is documented as:
>    verbose
       if set, it will dump the eBPF verifier output, even if loading the eBPF program was successful. By default, only on error, the verifier log is being emitted to the user.

This behavior is however not respected anymore when compiling `tc` with libbpf support as in Cilium's case. In that case, only miscellaneous information from the loader is dumped, without any verifier logs. The verifier logs are still dumped in case of loading error.

The following two patches provide a quick fix for the issue in iproute2 and libbpf. It may also be possible to rework iproute2 to use `bpf_object__load_xattr` instead of `bpf_object__load`. A patch to libbpf might still be required, to update the log buffer.

<details><summary>iproute2 patch</summary>
diff --git a/lib/bpf_libbpf.c b/lib/bpf_libbpf.c
index cc1931c9..a5e18d68 100644
--- a/lib/bpf_libbpf.c
+++ b/lib/bpf_libbpf.c
@@ -281,6 +281,8 @@ static int load_bpf_object(struct bpf_cfg_in *cfg)
 
 		bpf_program__set_type(p, cfg->type);
 		bpf_program__set_ifindex(p, cfg->ifindex);
+		if (cfg->verbose)
+			bpf_program__set_log_level(p, 2);
 
 		if (prog_to_attach)
 			prog = p;
</details>

<details><summary>libbpf patch</summary>
diff --git a/src/libbpf.c b/src/libbpf.c
index 355285c..dd35e20 100644
--- a/src/libbpf.c
+++ b/src/libbpf.c
@@ -6132,7 +6132,9 @@ load_program(struct bpf_program *prog, struct bpf_insn *insns, int insns_cnt,
 		return 0;
 	}
 retry_load:
-	if (log_buf_size) {
+	if (log_buf_size || load_attr.log_level) {
+		if (!log_buf_size)
+			log_buf_size = BPF_LOG_BUF_SIZE;
 		log_buf = malloc(log_buf_size);
 		if (!log_buf)
 			return -ENOMEM;
@@ -7833,6 +7835,11 @@ void bpf_program__set_type(struct bpf_program *prog, enum bpf_prog_type type)
 	prog->type = type;
 }
 
+void bpf_program__set_log_level(struct bpf_program *prog, int log_level)
+{
+	prog->log_level = log_level;
+}
+
 static bool bpf_program__is_type(const struct bpf_program *prog,
 				 enum bpf_prog_type type)
 {
diff --git a/src/libbpf.h b/src/libbpf.h
index 490bc98..dd9a369 100644
--- a/src/libbpf.h
+++ b/src/libbpf.h
@@ -390,6 +390,8 @@ LIBBPF_API int bpf_program__set_sk_lookup(struct bpf_program *prog);
 LIBBPF_API enum bpf_prog_type bpf_program__get_type(const struct bpf_program *prog);
 LIBBPF_API void bpf_program__set_type(struct bpf_program *prog,
 				      enum bpf_prog_type type);
+LIBBPF_API void bpf_program__set_log_level(struct bpf_program *prog,
+					   int log_level);
 
 LIBBPF_API enum bpf_attach_type
 bpf_program__get_expected_attach_type(const struct bpf_program *prog);
diff --git a/src/libbpf.map b/src/libbpf.map
index 18432d7..9a2f160 100644
--- a/src/libbpf.map
+++ b/src/libbpf.map
@@ -94,6 +94,7 @@ LIBBPF_0.0.1 {
 		bpf_program__set_socket_filter;
 		bpf_program__set_tracepoint;
 		bpf_program__set_type;
+		bpf_program__set_log_level;
 		bpf_program__set_xdp;
 		bpf_program__title;
 		bpf_program__unload;
</details>

### PR DESCRIPTION
**Pull request by kkourt**
Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>

https://github.com/cilium/image-tools/pull/162
https://github.com/cilium/image-tools/pull/161
https://github.com/cilium/image-tools/pull/163

Fixes: #18281

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by pchaigno** [comment]
test-1.22-4.19

**Comment by pchaigno** [comment]
test-1.16-4.9

**Comment by kkourt** [comment]
> Failed with `Kubernetes DNS did not become ready in time`: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/223/consoleFull Seems unrelated, but we need to double check. We'll need to create an issue for it if it doesn't happen again.
> 
> test-1.22-4.19

Now it failed with:
> 20:17:25  FAIL: terminating containers are not deleted after timeout
> 20:17:25  Expected
> 20:17:25      <*errors.errorString | 0xc001059de0>: {
> 20:17:25          s: "Pods are still not deleted after a timeout: 4m0s timeout expired",
> 20:17:25      }

**Comment by kkourt** [comment]
> k8s-1.16-kernel-4.9 failed with `Monitor log did not contain 2 ingress and 3 egress TCP notifications` after a timeout: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/530/testReport/junit/Suite-k8s-1/16/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications/ I can't find a single previous occurence of this in issues or in DataStudio, so could be related even if it doesn't seem.
> 
> If it doesn't happen again, we'll need a create an issue for this as well :-(
> 
> test-1.16-4.9

made: https://github.com/cilium/cilium/issues/18437 (sorry, made it before I saw your /mlh command).

**Comment by pchaigno** [comment]
> Now it failed with:
>    20:17:25 FAIL: terminating containers are not deleted after timeout

Yep, I saw that error, but the first test failure is still `Kubernetes DNS did not become ready in time` (`K8sDatapathConfig AutoDirectNodeRoutes Check connectivity with sockops and direct routing`). At this point, I'd say it's worth digging.

**Comment by kkourt** [comment]
> > Now it failed with:
> > 20:17:25 FAIL: terminating containers are not deleted after timeout
> 
> Yep, I saw that error, but the first test failure is still `Kubernetes DNS did not become ready in time` (`K8sDatapathConfig AutoDirectNodeRoutes Check connectivity with sockops and direct routing`). At this point, I'd say it's worth digging.

Ah sorry, somehow missed that. Thanks!

**Comment by kkourt** [comment]
This also looks very suspect:
> [2022-01-10T17:07:44.616Z] FAIL: Cilium cannot be installed
> [2022-01-10T17:07:44.616Z] Expected
> [2022-01-10T17:07:44.616Z]     <*errors.errorString | 0xc000608730>: {
> [2022-01-10T17:07:44.617Z]         s: "Failed to retrieve ip a output: Failed to exec \"ip -j a s\" cmd on \"k8s1\" node:  (exit status 1) output: cmd: kubectl exec -n kube-system log-gatherer-gkhmh -- ip -j a s\nExitcode: 1 \nErr: exit status 1\nStdout:\n \t \nStderr:\n \t Error from server: unexpected EOF\n\t \n",
> [2022-01-10T17:07:44.617Z]     }
> [2022-01-10T17:07:44.617Z] to be nil

**Review by aanm — APPROVED** [review]

**Comment by kkourt** [comment]
Closing this and starting fresh.

**Pull request closed without merging**
