### PR TITLE
v1.7 backports 2020-03-02

### PR DESCRIPTION
**Pull request by brb**
v1.7 backports 2020-03-02

 * #10322 -- doc: Fix links to contributing guide  (@CybrPunk)
 * #10355 -- install: Support generating vX.Y-dev charts (@joestringer)
 * #10352 -- bpf: Fix native dev cleanup (@brb)
 * #10326 -- add getting started guide for BIRD (@ArthurChiao)
 * #10381 -- etcd: Fix gRPC load balancer issue (@tgraf)
 * #10376 -- metrics: add missing metrics for cilium agent api handler (@fristonio)
 * #10382 -- cilium: fix node-port range parsing from helm and update docs (@borkmann)
 * #10383 -- AKS: Fix dynamic reconfiguration of bridge mode (@tgraf)
 * #10386 -- bpf: Fix typo in max options for bpf_lb (@pchaigno)
 * #10388 -- test: Avoid using global map for Cilium configuration (@brb)

**NOTE**:
- @mrostecki re #10353: I haven't backported it yet. Have you built `cilium-runtime:2020-02-27-v1.7`?
- @tgraf re #10381: There were some conflicts in `go.mod`, `go.sum` and `vendor/modules.txt`. I fixed the one in `go.mod`, and then ran `go mod tidy` (with go 1.13) to fix the latter files. Please check whether everything is OK.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10322 10355 10352 10326 10381 10376 10382 10383 10386 10388; do contrib/backporting/set-labels.py $pr done 1.7; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10401)

### CODE REVIEW

**Comment by brb** [comment]
never-tell-me-the-odds

**Review by pchaigno — APPROVED** [review]
:+1: for my change.

**Comment by brb** [comment]
never-tell-me-the-odds

**Review by aanm — CHANGES_REQUESTED** [review]
@brb please apply the following diff and squash it with the commit "etcd: Fix gRPC load balancer issue"

```diff
diff --git a/go.mod b/go.mod
index b71792be0..242740809 100644
--- a/go.mod
+++ b/go.mod
@@ -71,7 +71,7 @@ require (
        github.com/spf13/pflag v1.0.5
        github.com/spf13/viper v1.6.1
        github.com/vishvananda/netlink v1.0.1-0.20191113183427-d71301a47b60
-       go.etcd.io/etcd v0.0.0-20191023171146-3cf2f69b5738
+       go.etcd.io/etcd v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738
        golang.org/x/crypto v0.0.0-20190820162420-60c769a6c586
        golang.org/x/net v0.0.0-20191004110552-13f9640d40b9
        golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e
@@ -549,7 +549,7 @@ replace (
        github.com/xlab/treeprint => github.com/xlab/treeprint v0.0.0-20180616005107-d6fb6747feb6
        github.com/xordataexchange/crypt => github.com/xordataexchange/crypt v0.0.3-0.20170626215501-b2862e3d0a77
        go.etcd.io/bbolt => go.etcd.io/bbolt v1.3.3
-       go.etcd.io/etcd => go.etcd.io/etcd v0.5.0-alpha.5.0.20190911215424-9ed5f76dc03b
+       go.etcd.io/etcd => go.etcd.io/etcd v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738
        go.mongodb.org/mongo-driver => go.mongodb.org/mongo-driver v1.1.2
        go.opencensus.io => go.opencensus.io v0.21.0
        go.uber.org/atomic => go.uber.org/atomic v1.3.2
diff --git a/go.sum b/go.sum
index 361fe95f5..2ebf99536 100644
--- a/go.sum
+++ b/go.sum
@@ -550,8 +550,8 @@ github.com/xlab/treeprint v0.0.0-20180616005107-d6fb6747feb6/go.mod h1:ce1O1j6Ut
 github.com/xordataexchange/crypt v0.0.3-0.20170626215501-b2862e3d0a77/go.mod h1:aYKd//L2LvnjZzWKhF00oedf4jCCReLcmhLdhm1A27Q=
 go.etcd.io/bbolt v1.3.3 h1:MUGmc65QhB3pIlaQ5bB4LwqSj6GIonVJXpZiaKNyaKk=
 go.etcd.io/bbolt v1.3.3/go.mod h1:IbVyRI1SCnLcuJnV2u8VeU0CEYM7e686BmAb1XKL+uU=
-go.etcd.io/etcd v0.5.0-alpha.5.0.20190911215424-9ed5f76dc03b h1:zzmfsfPYodEcRFxxFVHWBVMkgYj94ZmfhPNORD6eoiU=
-go.etcd.io/etcd v0.5.0-alpha.5.0.20190911215424-9ed5f76dc03b/go.mod h1:dnLIgRNXwCJa5e+c6mIZCrds/GIG4ncV9HhK5PX7jPg=
+go.etcd.io/etcd v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738 h1:lWF4f9Nypl1ZqSb4gLeh/DGvBYVaUYHuiB93teOmwgc=
+go.etcd.io/etcd v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738/go.mod h1:dnLIgRNXwCJa5e+c6mIZCrds/GIG4ncV9HhK5PX7jPg=
 go.mongodb.org/mongo-driver v1.1.2 h1:jxcFYjlkl8xaERsgLo+RNquI0epW6zuy/ZRQs6jnrFA=
 go.mongodb.org/mongo-driver v1.1.2/go.mod h1:u7ryQJ+DOzQmeO7zB6MHyr8jkEQvC8vH7qLUO4lqsUM=
 go.opencensus.io v0.21.0 h1:mU6zScU4U1YAFPHEHYk+3JC4SY7JxgkqS10ZOSyksNg=
diff --git a/vendor/modules.txt b/vendor/modules.txt
index 65f190267..28f885652 100644
--- a/vendor/modules.txt
+++ b/vendor/modules.txt
@@ -395,7 +395,7 @@ github.com/vishvananda/netlink
 github.com/vishvananda/netlink/nl
 # github.com/vishvananda/netns v0.0.0-20191106174202-0a2b9b5464df => github.com/vishvananda/netns v0.0.0-20190625233234-7109fa855b0f
 github.com/vishvananda/netns
-# go.etcd.io/etcd v0.0.0-20191023171146-3cf2f69b5738
+# go.etcd.io/etcd v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738 => go.etcd.io/etcd v0.5.0-alpha.5.0.20191023171146-3cf2f69b5738
 go.etcd.io/etcd/auth/authpb
 go.etcd.io/etcd/clientv3
 go.etcd.io/etcd/clientv3/balancer
```

**Comment by mrostecki** [comment]
@brb 
>     * re #10353: I haven't backported it yet. Have you built `cilium-runtime:2020-02-27-v1.7`?

I didn't and I'm not sure if I'm even able to push container images to dockerhub. I will check.

**Comment by brb** [comment]
never-tell-me-the-odds

**Review by fristonio — APPROVED** [review]
Looks good for my change as well.

**Comment by brb** [comment]
Building docs have failed due to https://github.com/cilium/cilium/pull/10419.

**Comment by joestringer** [comment]
Filed #10442 to follow up on potential CI flake.

**Comment by joestringer** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
test-docs-please

**Comment by joestringer** [comment]
Documented flake in https://github.com/cilium/cilium/issues/10447 .

**Comment by joestringer** [comment]
test-missed-k8s

**Review by tgraf — APPROVED** [review]

**Review by vadorovsky — APPROVED** [review]
Looks good. My change got backported in an another PR.

**Comment by joestringer** [comment]
Hit known flake #9330 on one of the missed k8s builds. That's fine to ignore for now.

I've double-checked @tgraf's commits as well and the functional change looks right.

Merging.

**Pull request merged**
