### PR TITLE
v1.0 backports 2018 05 11

### PR DESCRIPTION
**Pull request by borkmann**
Backports:

* #4004 
* #3998 
* #3831 (dependency to avoid merge conflict with the latter)
* #3985

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by aanm** [comment]
test-docs

**Comment by aanm** [comment]
test-docs-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by borkmann** [comment]
Looks like the doc test seems failing due to missing support in 1.0's Jenkinsfile `ERROR: /var/jenkins_home/workspace/Cilium-PR-Doc-Tests@script/docs.Jenkinsfile not found`.

**Pull request merged**
