### PR TITLE
v1.15 backports 2024-02-14

### PR DESCRIPTION
**Pull request by michi-covalent**
- [ ] #30151 -- docs: Document XfrmInStateInvalid errors (@pchaigno)
 - [ ] #30561 -- bgpv1: remove BGP Controller from daemon cell (@harsimran-pabla)
 - [ ] #30759 -- workflows: Clean IPsec test output (@pchaigno)
 - [ ] #30757 -- node_addressing: fix edge case where `getDirectRouting` returns nil (@dylandreimerink)
 - [ ] #30762 -- Fix indexing of routes (@dylandreimerink)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
30151 30561 30759 30757 30762
```

### CODE REVIEW

**Comment by michi-covalent** [comment]
/test-backport1.15

**Comment by michi-covalent** [comment]
/test-backport-1.15

**Review by joestringer — APPROVED** [review]

**Review by brlbil — APPROVED** [review]
CI changes LGTM

**Comment by michi-covalent** [comment]
running ci-e2e in https://github.com/cilium/cilium/pull/30771

**Comment by michi-covalent** [comment]
✅  ran ci-e2e from a non-fork PR to test the workflow file change: https://github.com/cilium/cilium/actions/runs/7907721456. time to 🎸

**Pull request merged**
