### PR TITLE
v1.11 Backports 2023-04-20

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #20031 (@joestringer)
 * [x] #24786 (@hemanthmalla)
 * [x] #24850 (@pchaigno)
 * [x] #24785 (@giorio94)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 20031 24786 24850 24785; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
make add-labels BRANCH=v1.11 ISSUES=20031,24786,24850,24785
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.11

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by giorio94 — APPROVED** [review]
Mine too. Thanks!

**Review by joestringer — APPROVED** [review]
LGTM for #20031

**Review by hemanthmalla — APPROVED** [review]

**Comment by hemanthmalla** [comment]
LGTM for my commit. Thanks.

**Comment by nbusseneau** [comment]
- Jenkins pipelines failed with #24394, documenting the failures in the issue.
- AKS pipeline failed because K8s 1.23 is not supported on AKS anymore => we are entering one of the scenarios discussed when initially introducing K8s version pinning on stable branches. Since Cilium 1.11 only officially supports up to K8s 1.23, we now have a choice to make:
  - Disable AKS testing on 1.11.
  - Bump AKS testing to use K8s 1.24 even though it's not officially supported.

I would personally advocate for the first solution.
cc @joestringer @aanm

**Comment by joestringer** [comment]
:+1: I think it's fair to say that Cilium branch CI should test the intersection of {k8s releases that were out at the time of cilium release} and {k8s releases supported by the cloud now}. The logical consequence is that if those groups become disjoint then we no longer need to run such tests, as you propose.

We _could_ of course opt to add additional support, but I think it's in everyone's best interest to encourage newer software in cases like this rather than provide more reasons for folks to stick on the older releases.

**Comment by nbusseneau** [comment]
Cool, I will disable AKS testing on 1.11 then!

**Comment by nbusseneau** [comment]
/test-1.16-netnext

**Comment by sayboras** [comment]
/test-1.17-4.9

**Comment by sayboras** [comment]
/test-1.19-4.9

**Comment by sayboras** [comment]
/test-1.20-4.9

**Comment by sayboras** [comment]
/test-1.21-4.9

**Comment by sayboras** [comment]
> /test-1.21-4.9
> 
> Re-run this test suite to confirm if there is any issue or just flake.

Re-run was good :heavy_check_mark:

Required reviews are in, flakes are tracked as part of the below issues. Marking this ready to merge.

https://github.com/cilium/cilium/issues/25098
https://github.com/cilium/cilium/issues/25099
https://github.com/cilium/cilium/issues/25100
https://github.com/cilium/cilium/issues/25101

**Pull request merged**
