### PR TITLE
[v1.9] Backport Operator improvements

### PR DESCRIPTION
**Pull request by christarazi**
* #14380 -- refactor: Remove time.After from any Loops (@nathanjsweet)
 * #16955 -- inctimer: Fix bug where timer fired immediately #16955  (@gandro)
 * #17359 -- operator: Improve identity GC efficiency (@christarazi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14380 16955 17359; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by christarazi** [comment]
test-backport-1.9

**Comment by christarazi** [comment]
test-backport-1.9

**Comment by christarazi** [comment]
No need to re-run all of CI except for GKE as the latest push was a force push to update https://github.com/cilium/cilium/pull/17359 commits with the upstream commit SHAs.

**Comment by christarazi** [comment]
test-gke

**Review by gandro — APPROVED** [review]
Focused on my commit, but rest looks good to me too!

**Comment by christarazi** [comment]
Rebased PR on latest v1.9

**Comment by christarazi** [comment]
test-backport-1.9

**Pull request merged**
