### PR TITLE
1.2 Backport 2018 08 15

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5208)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Backport on hold until #5211 is resolved

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Review by rlenglet — APPROVED** [review]

**Pull request merged**
