### PR TITLE
k8s/watchers: Fix calling Done() with proper error

### PR DESCRIPTION
**Pull request by christarazi**
Previously, the error was not passed down to the Done() which would
never attempt a retry if there was an error in the node handler.

Fixes: b4335eede37 ("k8s: Introduce shared resources")
Fixes: https://github.com/cilium/cilium/pull/21744
Signed-off-by: Chris Tarazi <chris@isovalent.com>

### CODE REVIEW

**Comment by christarazi** [comment]
cc @joamaki

**Review by youngnick — APPROVED** [review]

**Comment by christarazi** [comment]
Marking ready to merge given we have CI passing besides known flakes and approving reviews.

**Pull request merged**
