### PR TITLE
Update Go to 1.17.4

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]
:ship:

**Comment by tklauser** [comment]
k8s-1.23-kernel-4.9 failed on #18060, though in a slightly different form, see https://github.com/cilium/cilium/issues/18060#issuecomment-986787639

**Review by nbusseneau — APPROVED** [review]

**Comment by tklauser** [comment]
All reviewers except for janitors approved and the only failure will be fixed by #18133. Marking as ready to merge, kindly asking the janitor/top hat (@nathanjsweet) to also approve before merging.

**Review by nathanjsweet — APPROVED** [review]

**Pull request merged**
