### PR TITLE
Fix panic in metricsmap Prometheus collector

### PR DESCRIPTION
**Pull request by carnerito**
The datapath metrics exposed in the 'cilium_metrics' eBPF map cannot be collected directly by the Prometheus Collector. This is because the datapath groups forward metrics based on "reason" and "direction," while the Prometheus metric exposed by the agent only includes a "direction" label.

To address this issue, a 'promMetrics' map was introduced in commit f8e94721fceb. This map aggregates datapath metrics, summing them based on the labels expected by the Prometheus Collector. However, a challenge arose when the 'Collect' method of the metricsmap Collector was called concurrently, leading to a 'fatal error: concurrent map writes.'

This commit resolves the issue by converting the 'promMetrics' map into a struct with 'sync.RWMutex' to synchronize concurrent access to the metrics map. Now, the map is updated and read with proper synchronization, preventing concurrent write errors.

Fixes: f8e94721fceb ("Replace metricsmap-bpf-prom-sync with Prometheus Collector pattern")

### CODE REVIEW

**Review by aditighag — COMMENTED** [review]
Thanks for the detailed commit description. Please add a proper `Fixes` tag to the PR/commit description pointing to the commit that introduced the regression. See - https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request.

**Comment by carnerito** [comment]
@aditighag Thanks for review. I've updated PR/commit messages as suggested.

**Comment by carnerito** [comment]
@aditighag @sayboras Can you rerun tests, please? I'm unsure why Ginkgo tests failed, so I pulled the latest changes from the main branch. Let's see if that solves the issue, if not, I'll dig deeper into it.

**Comment by buroa** [comment]
@carnerito I got this merged in https://github.com/cilium/cilium/pull/30104

**Comment by carnerito** [comment]
@buroa I'm glad its been solved. Closing this one.

**Comment by carnerito** [comment]
@buroa I'm glad its been solved. Closing this one.

**Pull request closed without merging**
