### PR TITLE
1.0 backports 18-11-06

### PR DESCRIPTION
**Pull request by nebril**
#6136 
#6109 
#5760 

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6190)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-missed-k8s

**Review by jrfastab — APPROVED** [review]
LGTM

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-missed-k8s

**Pull request merged**
