### PR TITLE
bpf: Avoid redirect in bpf_netdev for NodePort

### PR DESCRIPTION
**Pull request by brb**
This commit makes bpf_netdev to return a packet to the stack if it is destined to a local endpoint instead of redirecting it to the endpoint's iface in the host netns.

We cannot redirect the packet, as then the packet bypasses `nf_conntrack` table which makes a second reply from the endpoint to be MASQUERADEd by the `CILIUM_POST` masquerade non-cluster rule or to be dropped by the k8s `--ctstate INVALID -j DROP` rule, depending on an input interface of the reply (`lxc_$ENDPOINT_ID`, `cilium_net`).

So, instead of adding more complexity to the rules, just `TC_ACT_OK` a request.

Also, get rid of `MARK_MAGIC_REPLY` as the problem it solves is no longer present when a `nf_conntrack` entry is created.

We will be able to do the redirect again once the `veth` mode gets a support for BPF NAT.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8639)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Comment by tgraf** [comment]
```
Suite-k8s-1.10.K8sUpdates Tests upgrade and downgrade from a Cilium stable image to master
```

failed. Retrying to get more data.

**Comment by tgraf** [comment]
test-me-please

**Comment by brb** [comment]
This time CI failed due to the following:
```
    Suite-k8s-1.10.K8sChaosTest Connectivity demo application Endpoint can still connect while Cilium is not running
    Suite-k8s-1.10.K8sKafkaPolicyTest Kafka Policy Tests KafkaPolicies
    Suite-k8s-1.10.K8sFQDNTest Restart Cilium validate that FQDN is still working
    Suite-k8s-1.10.K8sFQDNTest Validate that multiple specs are working correctly
    Suite-k8s-1.10.K8sHealthTest checks cilium-health status between nodes
```

Re-trying.

**Comment by brb** [comment]
test-me-please

**Review by jrfastab — APPROVED** [review]
LGTM,  always nice to remove magic.

**Comment by borkmann** [comment]
(As discussed today with Martynas, tunnel mode does not need changes here since it's flying under the radar with netfilter conntrack due to the way we redirect, so conntrack never sees tunnel traffic for masquerading.)

**Pull request merged**
