### PR TITLE
v1.10 backports 2023-02-07

### PR DESCRIPTION
**Pull request by sayboras**
- [x] #23502 -- envoy: Bump envoy version to 1.22.7 (@sayboras)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 23502; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.10

**Review by pchaigno — APPROVED** [review]

**Comment by sayboras** [comment]
test-1.21-4.9 hits https://github.com/cilium/cilium/issues/18285

**Comment by sayboras** [comment]
/test-1.16-netnext

**Comment by sayboras** [comment]
> /test-1.16-netnext
> 
> Previous run failed for below tests, re-run once to confirm if they are flake.
> 
> [Suite-k8s-1.16.K8sPolicyTest Multi-node policy test with L7 policy using connectivity-check to check datapath](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/2590/testReport/junit/Suite-k8s-1/16/K8sPolicyTest_Multi_node_policy_test_with_L7_policy_using_connectivity_check_to_check_datapath/) [Suite-k8s-1.16.K8sPolicyTest Namespaces policies Cilium Network policy using namespace label and L7](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/2590/testReport/junit/Suite-k8s-1/16/K8sPolicyTest_Namespaces_policies_Cilium_Network_policy_using_namespace_label_and_L7/)

The second run failed for a different test, so it's most likely all three are flake

[Suite-k8s-1.21.K8sChaosTest Connectivity demo application Endpoint can still connect while Cilium is not running](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/2382/testReport/junit/Suite-k8s-1/21/K8sChaosTest_Connectivity_demo_application_Endpoint_can_still_connect_while_Cilium_is_not_running/) --> same as https://github.com/cilium/cilium/issues/18285

**Comment by sayboras** [comment]
Reviews are in, all tests are passed (except the above), marking this ready to merge.

**Review by michi-covalent — APPROVED** [review]

**Comment by joestringer** [comment]
It's interesting to me that it's specifically the k8s 1.16 / net-next build that fails. I doubt that k8s version plays a role here, as various other k8s versions are running the same test and passing. However, I believe that this target is the only one running these jobs on a "net-next" kernel. There's a small chance that something is breaking on newer kernels.

**Comment by joestringer** [comment]
One more datapoint would be that the corresponding 1.11 backport doesn't seem to exhibit any failures with net-next kernel, so that suggests that the Envoy bump by itself should not be introducing any such regression: https://github.com/cilium/cilium/pull/23627

**Comment by sayboras** [comment]
/test-1.16-netnext

**Comment by jrajahalme** [comment]
fail on test-1.16-netnext has a DROP due to "socket assign failed":
```
{"time":"2023-02-09T12:55:20.664254005Z","verdict":"DROPPED","drop_reason":179,"ethernet":{"source":"72:b4:9c:b1:6d:ef","destination":"2e:9c:94:bb:d5:ec"},"IP":{"source":"10.0.0.139","destination":"10.0.0.39","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":34320,"destination_port":80,"flags":{"SYN":true}}},"source":{"ID":1233,"identity":4197,"namespace":"2023020912542k8spolicytestnamespacespoliciesteststhesamepolicyi","labels":["k8s:appSecond=true","k8s:id=app2","k8s:io.cilium.k8s.namespace.labels.nslabel=second","k8s:io.cilium.k8s.policy.cluster=default","k8s:io.cilium.k8s.policy.serviceaccount=app2-account","k8s:io.kubernetes.pod.namespace=2023020912542k8spolicytestnamespacespoliciesteststhesamepolicyi","k8s:zgroup=testapp"],"pod_name":"app2-5cc5d58844-djj4s"},"destination":{"ID":110,"identity":20450,"namespace":"default","labels":["k8s:id=app1","k8s:io.cilium.k8s.policy.cluster=default","k8s:io.cilium.k8s.policy.serviceaccount=app1-account","k8s:io.kubernetes.pod.namespace=default","k8s:zgroup=testapp"],"pod_name":"app1-7b6ddb776f-wdzdc"},"Type":"L3_L4","node_name":"k8s1","event_type":{"type":1,"sub_type":179},"traffic_direction":"INGRESS","drop_reason_desc":"SOCKET_ASSIGN_FAILED","Summary":"TCP Flags: SYN"}
```
This shows that bpf TPROXY does not work with (new) Envoy, most likely due to use of SO_REUSEPORT option.

**Comment by jrajahalme** [comment]
Indeed: https://github.com/cilium/cilium/blob/v1.10/test/k8sT/Policies.go#L1806

**Comment by jrajahalme** [comment]
IMO we need to remove/comment out the `"bpf.tproxy": "true",` in the tests as this feature is not compatible with `SO_REUSEPORT` sockets, and Envoy nowadays has that option on listening sockets, so something like:
```
diff --git a/test/k8sT/Policies.go b/test/k8sT/Policies.go
index bb67b4543e..f3655239ee 100644
--- a/test/k8sT/Policies.go
+++ b/test/k8sT/Policies.go
@@ -1803,7 +1803,10 @@ var _ = SkipDescribeIf(func() bool {
                                        By("Reconfiguring Cilium to enable BPF TProxy")
                                        RedeployCiliumWithMerge(kubectl, ciliumFilename, daemonCfg,
                                                map[string]string{
-                                                       "bpf.tproxy": "true",
+                                                       // bpf tproxy socket lookup fails on sockets
+                                                       // that have SO_REUSEPORT on, so disable for
+                                                       // now.
+                                                       // "bpf.tproxy": "true",
                                                })
                                }
                        })
```

**Comment by jrajahalme** [comment]
Pushed the above into this PR.

**Comment by jrajahalme** [comment]
/test-backport-1.10

**Comment by jrajahalme** [comment]
test-1.16-netnext still running, but it already passed the "namespace label and L7" test that failed with `bpf.tproxy=true`.

**Comment by jrajahalme** [comment]
test-1.19-5.4 fail is a duplicate of a known flake #17069

**Comment by jrajahalme** [comment]
test-1.18-4.9 hit a known flake https://github.com/cilium/cilium/issues/16776

**Comment by pchaigno** [comment]
/test-1.18-4.9

**Comment by pchaigno** [comment]
All tests are passing except for the known flake mentioned above. Merging.

**Pull request merged**
