### PR TITLE
docs: fixed search for every page

### LINKED ISSUE #26866: Search bar only works on homepage / landing page of docs.cilium.io
For example it doesn't work for https://docs.cilium.io/en/v1.14/gettingstarted/hubble/
It works for  https://docs.cilium.io/en/v1.14

### PR DESCRIPTION
**Pull request by geakstr**
Previously search input didn't work on some pages, updated docs theme should fix this.

Closes #26866

Theme fix PR: https://github.com/cilium/sphinx_rtd_theme/pull/22

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by qmonnet** [comment]
Regarding backports, this changes may fail on older branch where we don't run the same version of docutils to generate the docs (I don't remember for sure).

I'm updating Sphinx and add-ons to match the version we use on `main`, for separate reasons, on older branches; this PR could be backported at the same time (I've a PR open for 1.13 at the moment).

**Comment by nbusseneau** [comment]
@qmonnet Thanks for the heads up, I indeed just hit a conflict so will be skipping this PR in my current batch and have marked the PR with `backport/author`, to let you handle it if that is OK.

**Comment by qmonnet** [comment]
Sounds good to me

**Comment by qmonnet** [comment]
Backport to 1.12 was merged, 1.13 still in progress.

Heads up that I don't plan to backport the other changes (or this PR, either) to 1.11, given that [we're dropping support very soon](https://github.com/cilium/cilium/pull/27077).

**Pull request merged**
