### PR TITLE
Fix hubble metrics label ordering with contextOptions

### PR DESCRIPTION
**Pull request by chancez**
This fixes an issue introduced by https://github.com/cilium/cilium/pull/21079/commits/d4d73681026bdf0335699d6ad262397613d143e4 in #21079  where metrics labels for drop, dns, and tcp metrics are incorrect when using any contextOptions. This is because the order labels are registered in, was different from the order the labels are used when incrementing the counters.

I had to refactor DNS a little bit because the logic was so complicated, and I tried to make it less "stateful" with the labels, which is part of the reason that one got done incorrectly in the first place. drop/tcp were simpler.

I'm not sure this actually needs a release note because I don't think the contextLabels PR has made it into a release yet, but I added one anyways.

```release-note
Fix hubble metrics label ordering with contextOptions
```

### CODE REVIEW

**Comment by rolinh** [comment]
The commit messages are empty. Would you mind adding the context around these changes from your PR description to the commits as well?

> I'm not sure this actually needs a release note because I don't think the contextLabels PR has made it into a release yet, but I added one anyways.

If the PR fixes something that isn't yet in any release, then you should use the `release-note/misc` label and not the `release-note/bug` one but a release note is required in any case.

**Review by michi-covalent — APPROVED** [review]

**Comment by chancez** [comment]
/test-1.24-4.19

**Review by rolinh — APPROVED** [review]
Thanks!

**Comment by michi-covalent** [comment]
marking ready to merge, 2 approvals from sig-hubble members.

**Pull request merged**
