### PR TITLE
v1.13 Backports 2023-06-13 (IPsec)

### PR DESCRIPTION
**Pull request by qmonnet**
* [x] #26093 (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 26093; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=26093
```

### CODE REVIEW

**Comment by qmonnet** [comment]
/test-backport-1.13

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks Quentin!

**Comment by qmonnet** [comment]
/test-1.26-net-next

**Review by michi-covalent — APPROVED** [review]

**Comment by gandro** [comment]
- ci-e2e-1.13 is failing due to 1.1.1.1 currently rejecting our traffic (this is happening on other PRs too at the moment). Since this PR only changes the behavior of IPSec with Pod CIDR based IPAM modes, those failures are not relevant. All other IPSec related scenarios have passed (i.e. the following jobs only complain about 1.1.1.1, not other targets):
  - :heavy_check_mark: https://github.com/cilium/cilium/actions/runs/5253555114/jobs/9499306768#step:10:826
  - :heavy_check_mark: https://github.com/cilium/cilium/actions/runs/5253555114/jobs/9499306945#step:10:838
  - :heavy_check_mark: https://github.com/cilium/cilium/actions/runs/5253555114/jobs/9499307077#step:10:838
  - :heavy_check_mark: https://github.com/cilium/cilium/actions/runs/5253555114/jobs/9499307659#step:10:830

Let's wait on net-next as well and then this should be ready to merge, as there is nothing we can do about the current 1.1.1.1 issue in this PR.

**Comment by gandro** [comment]
net-next is green. This is ready-to-merge.

**Pull request merged**
