### PR TITLE
Add fuzzer with OSS-fuzz build script

### PR DESCRIPTION
**Pull request by AdamKorcz**
This PR adds a fuzzer implemented with the go-fuzz fuzzing engine. Furthermore a build script is added to set up continuous fuzzing by way of OSS-fuzz.

Fuzzing is a way of testing programs wherby pseudo-random data is passed to a target application with the goal of finding bugs and vulnerabilities. In this fuzzer, the entrypoint to Cilium is the `UnmarshalJSON` implementatin in the `labels` package.

Integrating Cilium into OSS-fuzz allows Google to run all fuzzers in the Cilium project continuously free of charge. If bugs are found, maintainers get notified with detailed bug reports that include stack trace and reproducible test case. The service is offered free of charge to open source project with an implied expectation that bugs are fixed, and it has contributed to finding vulnerabilities in major open source projects like Kubernetes.

If there is interest in integrating Cilium, I will be happy to complete the integration on the OSS-fuzz side. For this at least one maintainer email address is needed.

Signed-off-by: AdamKorcz <adam@adalogics.com>

### CODE REVIEW

**Comment by twpayne** [comment]
Thanks for this @AdamKorcz :)

Yes, it would be great to get Cilium fuzzed regularly by OSS-Fuzz. Looking at [OSS-Fuzz's guidelines for new projects](https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/) it looks like Cilium is well qualified.

I've opened https://github.com/google/oss-fuzz/pull/4784 to get Cilium added to OSS-Fuzz as having a PR from a Cilium maintainer skips a manual email verification step.

There are obviously several entry points for fuzzing and Cilium and this is great start, thank you. Let's wait to see if Cilium gets accepted and then merge this and add more.

**Comment by twpayne** [comment]
@AdamKorcz note that for this PR to be merged, all commits will need the `Signed-off-by` line as described in the [contributing guide](https://docs.cilium.io/en/v1.9/contributing/development/contributing_guide/#submitting-a-pull-request). You'll need to squash your commits.

**Comment by AdamKorcz** [comment]
@twpayne Thanks for the heads up!

**Comment by AdamKorcz** [comment]
@twpayne Let me know if anything else is missing from my side.

**Review by twpayne — APPROVED** [review]

**Comment by nebril** [comment]
@AdamKorcz can this script be moved out of the `tests` directory? Currently `tests` holds our older bash based test scripts and I think it would be better to put any new features in either `test` dir, or a completely new one.

**Comment by AdamKorcz** [comment]
@nebril that is not an issue. The build file has hereby been moved.

**Review by aanm — COMMENTED** [review]
@AdamKorcz thanks, I think @nebril was referring to both files, `oss-fuzz-build.sh` and `fuzz/fuzz.go` to be moved into `test/` directory.

**Comment by AdamKorcz** [comment]
@aanm Oh sorry about that. Both files have now been moved to `/test/fuzzing`

**Comment by aanm** [comment]
test-me-please

**Comment by AdamKorcz** [comment]
Let me know if there is anything missing from my side.

**Comment by twpayne** [comment]
retest-runtime

**Pull request merged**
