### PR TITLE
v1.13 Backports 2024-02-08

### PR DESCRIPTION
**Pull request by nbusseneau**
* [ ] #30247 (@marseel)
 * [x] #30536 (@hemanthmalla)
 * [x] #30525 (@tklauser)
 * [x] #30496 (@giorio94)
 * [x] #30378 (@brlbil)
 * [x] #30612 (@gailsuccess)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30247 30536 30525 30496 30378 30612
```

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
My commit looks good, thanks!

**Comment by nbusseneau** [comment]
/test-backport-1.13

**Comment by nbusseneau** [comment]
The expected `Conformance Gateway API` check is missing because it has been renamed in this PR to `Conformance Gateway API (ci-gateway-api)`.

All testing has passed, awaiting for reviews now.

**Review by tklauser — APPROVED** [review]
My change looks good, thanks Nicolas.

As you already noted, the required workflows will need to be updated to account for the renamed _Conformance Gateway API (ci-gateway-api)_ workflow.

**Review by julianwiedmann — APPROVED** [review]

**Review by brlbil — APPROVED** [review]
My commit looks good, Thanks

**Comment by nbusseneau** [comment]
This should be ready to merge as soon as reviews are in.

**Review by hemanthmalla — APPROVED** [review]

**Pull request merged**
