### PR TITLE
daemon: move datapath-related code into new file, datapath.go

### PR DESCRIPTION
**Pull request by ianvernon**
This is part of my long quest to split up the size of our files, especially in the daemon directory. This makes the code more logically organized, which allows for easier potential refactoring in the future. It also makes it easier to make changes across multiple files, but only commit one at a time. 

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8274)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Review by brb — CHANGES_REQUESTED** [review]
LGTM! Just one nit: you probably wanted to move `compileBase` in https://github.com/cilium/cilium/pull/8274/commits/605a8717739840f8a46ac2b76a7ed80c6d3756f3 instead of https://github.com/cilium/cilium/pull/8274/commits/a63b40c59dd3048742a3a49d4f95e77f477855d6.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
@be right back  fixed!

**Comment by ianvernon** [comment]
test-me-please

**Comment by brb** [comment]
Hit `Suite-k8s-1.14.K8sFQDNTest Restart Cilium validate that FQDN is still working` which seems to be unrelated to your changes (saw the same failure in other PR builds as well).

**Comment by brb** [comment]
test-me-please

**Review by brb — APPROVED** [review]
Nice!

**Pull request merged**
