### PR TITLE
[v1.10] .github: add conformance AWS test

### PR DESCRIPTION
**Pull request by aanm**
This conformance test is available in the master branch but hasn't been
backported for v1.10 branch. This commit is simply copying it into this
branch.

Signed-off-by: André Martins <andre@cilium.io>

Depends on https://github.com/cilium/cilium/pull/16908

### CODE REVIEW

**Comment by aanm** [comment]
ci-awscni

**Comment by aanm** [comment]
The aws-cni tests have passed as seen in https://github.com/cilium/cilium/pull/16913/checks?check_run_id=3106710500

**Review by christarazi — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]
Sure, we can add it, even though right now it will have no effect whatsoever since neither `issue_comment` nor `schedule` run outside of the context of `master` 😄

Nit: in the comment linking to a successful temporary run, I recommend you use permanent GitHub Actions links (e.g. https://github.com/cilium/cilium/actions/runs/1046098880 or https://github.com/cilium/cilium/runs/3106710500?check_suite_focus=true) as the PR check links are lost when the PR checks get overwritten ;)

**Comment by aanm** [comment]
Closing in favor of #16950

**Pull request closed without merging**
