### PR TITLE
iptables: Do not remove & re-create all iptables on startup

### PR DESCRIPTION
**Pull request by tgraf**
The current brute-force approach can cause disruption on startup. Instead of removing and re-creating all rules, calculate the difference between the old and new ruleset and only flush and re-create the chain if changes were detected.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6735)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
I seem to have broken something. Putting it back into WIP.

**Comment by tgraf** [comment]
test-me-please

green build

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Hit #6730 so this will not be a fix for the netperf failure during restart

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Reducing priority as it does not fix #6730

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Will continue this work after 1.4. Closing for now

**Pull request closed without merging**
