### PR TITLE
v1.9: Update Go to 1.15.7

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
retest-4.9

**Comment by tklauser** [comment]
test-backport-1.9

**Comment by tklauser** [comment]
test-missed-k8s

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
test-missed-k8s

**Comment by tklauser** [comment]
test-backport-1.9

**Comment by tklauser** [comment]
test-backport-1.9

**Comment by tklauser** [comment]
Not sure why `Cilium-Ginkgo-Test-k8s ` is in state _Waiting for status to be reported _ after https://github.com/cilium/cilium/pull/14665#issuecomment-766734280. Likely because I initially triggered CI using `test-me-please`? Given the reviews and the passing individual test I'll mark this as `ready-to-merge`.

**Comment by pchaigno** [comment]
test-missed-k8s

**Comment by pchaigno** [comment]
> Not sure why `Cilium-Ginkgo-Test-k8s ` is in state _Waiting for status to be reported _ after [#14665 (comment)](https://github.com/cilium/cilium/pull/14665#issuecomment-766734280). Likely because I initially triggered CI using `test-me-please`? Given the reviews and the passing individual test I'll mark this as `ready-to-merge`.

@tklauser We had forgotten to update the regular expression to trigger `Cilium-Ginkgo-Test-k8s` from `test-backport-1.9`. I updated the regex in Jenkins, so it should work as expected now.

**Comment by pchaigno** [comment]
test-missed-k8s

**Comment by tklauser** [comment]
test-missed-k8s

**Comment by pchaigno** [comment]
test-missed-k8s

**Pull request merged**
