### PR TITLE
[bugfix] - mtu for interfaces in host-network

### PR DESCRIPTION
**Pull request by nyodas**
We've had some issue with hostNetwork pods not being able to reach other pods.
The investigation lead us to a MTU issue (because for once it wasn't DNS)

This PR change the MTU set by the `init.sh` script.
Instead of using `getDeviceMTU` which provide the mtu of the host interface.
We're using the `getRouteMTU` which provide the mtu minus the bytes used by the various protocols.

While doing that we noticed that the MTU generated by [mtu.NewConfiguration](https://github.com/cilium/cilium/blob/2bc1fdeb97331761241f2e4b3fb88ad524a0681b/pkg/mtu/mtu.go#L106) was not the correct one. We were expecting `8924` and got `8940`
Which lead us to the patch in daemon.go

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8688)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by roboll** [comment]
See #8680

**Review by jrfastab — APPROVED** [review]
LGTM thanks.

**Comment by jrfastab** [comment]
Can we get some Fixes tags on those commits? The error was introduced here,

Fixes:  1ce278f12ec4 ("daemon: move IPSec bootstrap into separate function")

**Comment by nyodas** [comment]
Just added the tags 👍

**Comment by joestringer** [comment]
test-me-please

**Comment by jrfastab** [comment]
Failed here,  

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13908/execution/node/152/log/?consoleFull

With,
```
11:26:43      Endpoint can still connect while Cilium is not running
11:26:43      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.10-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:420
11:26:43      cilium pre-flight checks failed
[2019-07-26T18:26:43.748Z]     Expected
[2019-07-26T18:26:43.748Z]         <*errors.errorString | 0xc0001bb4c0>: {
[2019-07-26T18:26:43.748Z]             s: "CiliumPreFlightCheck error: Timeout reached: PreflightCheck failed: Last polled error: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-5zkn7': Exitcode: 255 \nStdout:\n \t \nStderr:\n \t Error: Cannot get status/probe: Put http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe: context deadline exceeded\n\t \n\t command terminated with exit code 255\n\t \n",
[2019-07-26T18:26:43.748Z]         }
[2019-07-26T18:26:43.748Z]     to be nil
```

I'm not seeing how this PR can cause the above. I'm retrying test but looking into it as well.

**Comment by jrfastab** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by jrfastab** [comment]
The backport to v1.5 is not going to apply cleanly most likely so I'll go ahead and do it once this is merged.

**Comment by ianvernon** [comment]
@raybejjani while I merged your partial backport of this (which seemed self-contained / not risky), I am not marking this backport as "done". @jrfastab can you please review the backport / Ray's comments on https://github.com/cilium/cilium/pull/8738 ?

**Pull request merged**
