### PR TITLE
Test: Disable rolling status in Update

### PR DESCRIPTION
**Pull request by eloycoto**
- Enable Cilium Update test
- Disable rolling status and use the custom WithTimeout helper.
- Update Nigthly to use BeforeAll/AfterAll helpers function

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
