### PR TITLE
bump cilium-etcd-operator to v2.0.6

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.dev>

```release-note
bump cilium-etcd-operator to v2.0.6
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7422)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please previous failure was related with istio https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1815/flowGraphTable/

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please (FQDN-https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1820/testReport/junit/k8s-1/9/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/)

**Comment by eloycoto** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]

**Comment by ianvernon** [comment]
Marking with `priority/high`, as getting this merged would greatly increase CI stability.

**Review by jrfastab — APPROVED** [review]
LGTM, I've been running this locally for awhile now.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
timeout exceeded... I'm going to retest.

**Comment by jrfastab** [comment]
test-me-please

**Comment by joestringer** [comment]
runtime VM took too long to download:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11037/flowGraphTable/

**Comment by joestringer** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
all tests have passed for v2.0.6-rc4.

re-running for v2.0.6

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
