### PR TITLE
vendor: switch github.com/shirou/gopsutil to v3

### PR DESCRIPTION
**Pull request by tklauser**
Use the v3 API of `github.com/shirou/gopsutil` which is implemented as a
properly versioned Go module. This will allow dependabot to bump the
module automatically for future versions.

Additionally, this version of the module fixes an issue with inefficient
use of memory buffers leading to reallocations in
`github.com/shirou/gopsutil/v3/process`. Cilium uses this functionality in
`pkg/loadinfo` in a background goroutine, so it potentially benefits as
well from these fixes.

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-1.20-4.9

**Comment by tklauser** [comment]
test-gke

**Review by twpayne — APPROVED** [review]
Change looks good, 🤞 for CI...

**Review by aanm — APPROVED** [review]

**Pull request merged**
