### PR TITLE
Re-enable flannel CI with helm

### PR DESCRIPTION
**Pull request by joestringer**
The flannel CI testing when run recently did not configure Cilium in
such a way as to chain Cilium on top of flannel, meaning that while
flannel was technically running in the cluster, it was not controlling
the overlay. Fix this by adding a special set of override options in the
CiliumInstall() function that ensure that when the CI is run with the
flannel integration environment variable, it will ensure that Cilium's
configuration includes the set of options necessary for flannel
chaining.

We don't configure flannel-master-device (`globals.flannel.masterDevice`)
here as this should be inherited from the default values specified in
`install/kubernetes/cilium/values.yaml`.

The regular CI should not break on this PR. The flannel Ci should break on this PR. If the flannel CI passes on this PR, it is likely broken; if the flannel CI appears broken then it is likely that flannel is being properly re-enabled and it is revealing known issues with flannel chaining mode.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8784)

### CODE REVIEW

**Comment by joestringer** [comment]
test-flannel

**Comment by joestringer** [comment]
test-flannel

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by joestringer** [comment]
This doesn't yet fix flannel CI, looks like Cilium is being unconditionally waited upon to be ready before flannel deployment.

**Review by jrajahalme — APPROVED** [review]

**Comment by joestringer** [comment]
test-flannel

**Comment by joestringer** [comment]
test-flannel

**Comment by joestringer** [comment]
Some tests actually passed, and it's actually running in Flannel mode. I think this is good to merge as-is, at least to allow further testing of the flannel integration.

https://jenkins.cilium.io/job/Cilium-PR-Flannel-hook/54/execution/node/73/log/?consoleFull

**Comment by joestringer** [comment]
test-me-please

**Pull request merged**
