### PR TITLE
v1.6 backports 2019-09-30

### PR DESCRIPTION
**Pull request by joestringer**
* #9201 -- Solve MTU issues by using table 200 post-encryption using output-mark (@lbernail)
   * I needed to pull in a custom change here to bump the `x/sys/unix` dependency to the tip of the v1.13 tree here.
 * #9299 -- bpf: fix cilium_host unroutable check (@borkmann)
 * #9296 -- policy: Fix selectorcache locking issue (@joestringer)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 9201 9299 9296; do contrib/backporting/set-labels.py $pr done 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9302)

### CODE REVIEW

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Comment by joestringer** [comment]
Hmm, looks like there was a change in the golang `x/sys/unix` library which breaks this backport:

```
# github.com/cilium/cilium/vendor/github.com/vishvananda/netlink
685../../vendor/github.com/vishvananda/netlink/route_linux.go:522:42: undefined: unix.RTA_NEWDST
686../../vendor/github.com/vishvananda/netlink/route_linux.go:528:42: undefined: unix.RTA_ENCAP_TYPE
687../../vendor/github.com/vishvananda/netlink/route_linux.go:533:42: undefined: unix.RTA_ENCAP
688../../vendor/github.com/vishvananda/netlink/route_linux.go:597:46: undefined: unix.RTA_NEWDST
689../../vendor/github.com/vishvananda/netlink/route_linux.go:602:44: undefined: unix.RTA_ENCAP_TYPE
690../../vendor/github.com/vishvananda/netlink/route_linux.go:607:46: undefined: unix.RTA_ENCAP
691../../vendor/github.com/vishvananda/netlink/route_linux.go:842:11: undefined: unix.RTA_NEWDST
692../../vendor/github.com/vishvananda/netlink/route_linux.go:852:11: undefined: unix.RTA_ENCAP_TYPE
693../../vendor/github.com/vishvananda/netlink/route_linux.go:854:11: undefined: unix.RTA_ENCAP
694../../vendor/github.com/vishvananda/netlink/route_linux.go:883:8: undefined: unix.RTA_NEWDST
695../../vendor/github.com/vishvananda/netlink/route_linux.go:883:8: too many errors
696make[1]: *** [perf-event-test] Error 2
```

**Comment by lbernail** [comment]
@joestringer is the new code in `x/sys/unix` only in 1.13?
It would be great for us to get the MTU patch to the 1.6 branch

**Comment by joestringer** [comment]
@lbernail No, it looks like it was already there in 1.11 or earlier but our vendor directory got out of sync somehow. I'm working through the issue with @aanm .

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Review by ianvernon — APPROVED** [review]

**Comment by lbernail** [comment]
Thanks a lot!

**Pull request merged**
