### PR TITLE
v1.11: Update Go to 1.17.5

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]
:ship:

**Comment by tklauser** [comment]
/test-backport-1.11

**Review by nbusseneau — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by tklauser** [comment]
/test-1.20-4.9

**Comment by tklauser** [comment]
/test-1.21-5.4

**Comment by tklauser** [comment]
test-1.20-4.9 failed on #17010 which will be fixed on `v1.11` once #18232 with a backport of #18133 is merged. All other tests passed and requested reviewers approved, marking as ready to merge.

**Pull request merged**
