### PR TITLE
Backports for v1.0.0-rc12

### PR DESCRIPTION
**Pull request by tgraf**

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]

**Comment by tgraf** [comment]
Added backport of
```
proxy: Create access log file and setup notifier at startup

[ upstream commit 1024913 ]
```

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Pull request closed without merging**
