### PR TITLE
[1.14] Author backport of #28928 (Dns proxy use original source address and port) #29239

### PR DESCRIPTION
**Pull request by jrajahalme**
* [ ] #29239 (@jrajahalme)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
29239
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.14

**Comment by jrajahalme** [comment]
/test-backport-1.14

**Comment by jrajahalme** [comment]
/test-backport-1.14

**Comment by lmb** [comment]
@jrajahalme can you find additional reviewers outside of tophat for this please?

**Comment by jrajahalme** [comment]
/test-backport-1.14

**Comment by jrajahalme** [comment]
/test-backport-1.14

**Comment by jrajahalme** [comment]
/test-backport-1.14

**Comment by jrajahalme** [comment]
/test-backport-1.14

**Comment by ti-mo** [comment]
Upstream PR hasn't been merged, converting this to a draft.

**Comment by jrajahalme** [comment]
Superceded by #30213

**Pull request closed without merging**
