### PR TITLE
v1.5 backports 2019-08-19

### PR DESCRIPTION
**Pull request by vadorovsky**
* #8882 -- Revert "[daemon] - Change MTU source for cilium_host (Use the Route o…ne)" (@aanm)
 * #8903 -- cilium: route mtu not set unless route.Spec set MTU (@jrfastab)
 * #8919 -- bpf: try to atomically replace filters when possible (@borkmann)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 8882 8903 8919; do contrib/backporting/set-labels.py $pr done 1.5; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8949)

### CODE REVIEW

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
test-me-please

**Comment by ianvernon** [comment]
Issues downloading dependencies: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14478/

```
08:50:21      k8s1-1.10: 2019-08-19 15:50:21 (97.9 MB/s) - 'apt-key.gpg' saved [659/659]
08:50:21      k8s1-1.10: running of "wget https://packages.cloud.google.com/apt/doc/apt-key.gpg" successful
08:50:21      k8s1-1.10: Warning: apt-key output should not be parsed (stdout is not a terminal)
08:50:21      k8s1-1.10: OK
08:50:21      k8s1-1.10: Disabling crio CNI bridge
08:50:21      k8s1-1.10: removed '/etc/cni/net.d/100-crio-bridge.conf'
08:50:21      k8s1-1.10: removed '/etc/cni/net.d/200-loopback.conf'
08:50:22      k8s1-1.10: Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
08:50:22      k8s1-1.10: Hit:3 http://ppa.launchpad.net/projectatomic/ppa/ubuntu xenial InRelease
08:50:22      k8s1-1.10: Hit:2 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
08:50:22      k8s1-1.10: Hit:4 https://download.docker.com/linux/ubuntu bionic InRelease
08:50:23      k8s1-1.10: Hit:5 http://archive.ubuntu.com/ubuntu bionic InRelease
08:50:27      k8s1-1.10: Hit:6 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
08:50:27      k8s1-1.10: Hit:7 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
08:50:28      k8s1-1.10: Reading package lists...
08:50:29      k8s1-1.10: E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
08:50:29      k8s1-1.10: E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```

**Comment by ianvernon** [comment]
test-me-please

**Comment by mrostecki** [comment]
Seems like the real error is:

```
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: level=warning msg="+ clang -O2 -g -target bpf -emit-llvm -Wno-address-of-packed-member -Wno-unknown-warning-option -I. -I/run/cilium/state/globals -I/var/lib/cilium/bpf -I/var/lib/cilium/bpf/include -D__NR_CPUS__=2 -DENABLE_ARP_RESPONDER -DHANDLE_NS -DBPF_PKT_DIR=1 '-DNODE_MAC={.addr={0x36,0x3d,0x99,0x99,0xd2,0xff}}' -DCALLS_MAP=cilium_calls_netdev_ns_1 -c /var/lib/cilium/bpf/bpf_hostdev_ingress.c -o -" subsys=daemon
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: level=warning msg="clang: error: no such file or directory: '/var/lib/cilium/bpf/bpf_hostdev_ingress.c'" subsys=daemon
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: level=warning msg="clang: error: no input files" subsys=daemon
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1 [running]:
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1 runtime/debug.Stack(0xbf4edb551440f4f0, 0x36048496, 0x4f9fea0)
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1         /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1 github.com/cilium/cilium/pkg/lock.(*internalRWMutex).Unlock(0xc0008bf3e0)
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:68 +0xc4
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1 main.(*Daemon).compileBase(0xc000525180, 0x35ecb60, 0xc00042b880)
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon.go:540 +0x1910
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1 main.(*Daemon).init(0xc000525180, 0x3600ad59, 0x4f9fea0)
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon.go:739 +0x654
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1 main.NewDaemon(0x3673ec0, 0xc0004d0740, 0x365a180, 0xc00042aaa0, 0x1, 0x0, 0x0, 0x0)
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon.go:1310 +0x2b2a
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1 main.runDaemon()
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon_main.go:1170 +0x2ea
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1 main.glob..func1(0x4ee8160, 0xc0004d0040, 0x0, 0x4)
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon_main.go:117 +0x7b
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1 github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).execute(0x4ee8160, 0xc00004e060, 0x4, 0x4, 0x4ee8160, 0xc00004e060)
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801
21:17:43      runtime: ]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1 github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x4ee8160, 0x0, 0x0, 0x0)
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1 github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).Execute(...)
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:800
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1 main.daemonMain()
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/daemon/daemon_main.go:134 +0x17d
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1 main.main()
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: goroutine 1         /home/vagrant/go/src/github.com/cilium/cilium/daemon/main.go:31 +0xda
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: level=error msg="Error while initializing daemon" error="exit status 1" subsys=daemon
21:17:43      runtime: Aug 19 19:17:41 runtime cilium-agent[23801]: level=fatal msg="Error while creating daemon" error="exit status 1" subsys=daemon
21:17:43      runtime: Aug 19 19:17:41 runtime systemd[1]: cilium.service: Service hold-off time over, scheduling restart.
21:17:43      runtime: Aug 19 19:17:41 runtime systemd[1]: cilium.service: Scheduled restart job, restart counter is at 45.
21:17:43      runtime: Aug 19 19:17:41 runtime systemd[1]: Stopped cilium.
21:17:43      runtime: Aug 19 19:17:41 runtime systemd[1]: Started cilium
```

Let me fix it...

**Comment by borkmann** [comment]
@mrostecki I mentioned in #8919 that I did a backport here: https://github.com/cilium/cilium/commit/b9e6d6cfb0ff0f3ad3a8a37624785f73c82b5cdd . Please compare to your version.

**Comment by mrostecki** [comment]
@borkmann Thank you and sorry that I missed your comment! I've applied your version.

**Comment by mrostecki** [comment]
test-me-please

**Comment by brb** [comment]
never-tell-me-the-odds

**Comment by brb** [comment]
I'm confused by the `[ upstream commit cc01f52 ]` in the backported https://github.com/cilium/cilium/pull/8949/commits/a97e9390dcb2c35a3ee6ca0e3351451703727a75. Shouldn't it be b9e6d6c?

**Comment by borkmann** [comment]
No, b9e6d6cfb0ff0f3ad3a8a37624785f73c82b5cdd was a private branch which I gave one of our users for testing, so all good as is.

**Comment by mrostecki** [comment]
k8s tests failed on installing packages...

**Comment by mrostecki** [comment]
test-upstream-k8s

**Comment by mrostecki** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
@mrostecki upstream k8s tests have issues provisioning for the v1.5 branch (we aren't sure why), so it's okay to let them fail for now.

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
