### PR TITLE
doc: update slack channel reference

### LINKED ISSUE #34043: The herokuapp slack channel link is broken
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

The herokuapp slack channel link is broken as below picture shows:
pic

The heroku instance is down as described in https://github.com/cilium/cilium.io/pull/524, we have to update the link.

### How can we reproduce the issue?

`curl https://cilium.herokuapp.com/`

### Cilium Version

*

### Kernel Version

*

### Kubernetes Version

*

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Huweicai**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #34043

Update the dead links `https://cilium.herokuapp.com/` `https://cilium.io/slack` to  `https://slack.cilium.io`

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
Thanks! I guess we'll need to backport these changes to all stable branches, to fix the links there as well (especially for the documentation).

**Comment by giorio94** [comment]
@Huweicai Please don't rebase the PR (even if GH says that it is out of date) unless it hits a real conflict. Otherwise the CI checks are invalidated, and need to be executed again from scratch.

**Review by ghost — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Review by xmulligan — APPROVED** [review]

**Review by joamaki — APPROVED** [review]

**Pull request merged**
