### PR TITLE
v1.8 backports 2020-06-08

### PR DESCRIPTION
**Pull request by tklauser**
* #11927 -- daemon/cli: Add SessionAffinity to cilium status (@brb)
 * #11925 -- cilium: rename --node-port-acceleration=none to =disabled (@borkmann)
 * #11917 -- vagrant: bump net-next vagrant box version (@borkmann)
 * #11920 -- Properly cancel endpoint creations as they become obsolete (@tgraf)
 * #11940 -- docs: Rework live-preview to use docker container (@joestringer)
 * #11942 -- test: Fix NodePort acceleration param (@brb)
 * #11965 -- test/K8sServices: Skip checks for externalTrafficPolicy=Local with kube-proxy <1.15 (@gandro)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 11927 11925 11917 11920 11940 11942 11965; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by tklauser** [comment]
test-backport-1.8

**Review by borkmann — APPROVED** [review]

**Comment by tklauser** [comment]
test-missed-k8s

**Review by brb — APPROVED** [review]
LGTM for my changes.

**Comment by tklauser** [comment]
test-missed-k8s

**Comment by gandro** [comment]
Note on the test-missed-k8s failures:

Suite-k8s-1.12.K8sServicesTest Checks service across nodes Tests NodePort (kube-proxy) with externalTrafficPolicy=Local
Suite-k8s-1.13.K8sServicesTest Checks service across nodes Tests NodePort (kube-proxy) with externalTrafficPolicy=Local

Will never succeed on 1.8 without #11965. Not sure about the other failures though.

**Comment by joestringer** [comment]
The other failures likely stem from this one:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3180/testReport/junit/Suite-k8s-1/13/K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies/

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:459
failed to ensure the namespace kube-system exists: Process exited with status 1
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:632
```

Which comes from here:

https://github.com/cilium/cilium/blob/55fccf68d17b96752ce8c18a7425137610184ed2/test/helpers/kubectl.go#L340-L343

However it doesn't make sense to me that the `kube-system` namespace wouldn't exist; I believe in these clusters it's *always* there so it suggests some other issue, like connectivity from kubectl to the apiserver in the vagrant VM?

I note that it comes after the Upgrades test, if that helps at all:

```
09:53:37  16:53:36 STEP: Running AfterAll block for EntireTestsuite K8sUpdates
09:53:37  
09:53:37  • [SLOW TEST:314.812 seconds]
09:53:37  K8sUpdates
09:53:37  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:476
09:53:37    Tests upgrade and downgrade from a Cilium stable image to master
09:53:37    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:512
09:53:37  ------------------------------
09:53:37  SSSSSSSSSSS
09:53:37  ------------------------------
09:53:37  K8sPolicyTest Basic Test 
09:53:37    checks all kind of Kubernetes policies
09:53:37    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:512
09:53:37  16:53:36 STEP: Running BeforeAll block for EntireTestsuite K8sPolicyTest
09:53:38  16:53:38 STEP: Ensuring the namespace kube-system exists
09:53:38  FAIL: failed to ensure the namespace kube-system exists: Process exited with status 1
09:53:38  16:53:38 STEP: Running JustAfterEach block for EntireTestsuite K8sPolicyTest
09:53:38  16:53:38 STEP: Running AfterEach for block EntireTestsuite
09:53:38  <Checks>
09:53:38  
09:53:38  </Checks>
09:53:38  
09:53:38  [[ATTACHMENT|b768e2c1_K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies.zip]]
09:53:38  
09:53:38  • Failure in Spec Setup (BeforeEach) [1.829 seconds]
09:53:38  K8sPolicyTest
09:53:38  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:476
09:53:38    Basic Test [BeforeEach]
09:53:38    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:476
09:53:38      checks all kind of Kubernetes policies
09:53:38      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:512
09:53:38  
09:53:38      failed to ensure the namespace kube-system exists: Process exited with status 1
09:53:38  
09:53:38      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:632
```

**Comment by tklauser** [comment]
Given that this passed on all but "K8sServicesTest Checks service across nodes" on the second run (https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3179) and this test cannot pass without #11965 (see https://github.com/cilium/cilium/pull/11951#issuecomment-640881089), I'll mark this as ready for merge. As for the "missing `kube-system`" failure in the third run, I've opened #11975 to track it.

**Comment by tklauser** [comment]
test-backport-1.8

**Comment by tklauser** [comment]
Pulled in #11965 in order to fix "K8sServicesTest Checks service across nodes" (as per https://github.com/cilium/cilium/pull/11951#issuecomment-640881089).

**Pull request merged**
