### PR TITLE
v1.6 backports 2019-10-08

### PR DESCRIPTION
**Pull request by vadorovsky**
* PR: 9342 -- Extend NodePort BPF tests (@brb) -- https://github.com/cilium/cilium/pull/9342

When you have backported the above commits, you can update the PR labels via this command:
```
$ for pr in 9342; do contrib/backporting/set-labels.py $pr pending 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9364)

### CODE REVIEW

**Comment by mrostecki** [comment]
never-tell-me-the-odds

**Comment by mrostecki** [comment]
never-tell-me-the-odds

**Comment by mrostecki** [comment]
never-tell-me-the-odds

**Review by brb — CHANGES_REQUESTED** [review]
You probably have run `git add .`, as the PR contains many unrelated files.

**Comment by mrostecki** [comment]
@brb Sorry for that! It should be fixed now.

**Comment by mrostecki** [comment]
never-tell-me-the-odds

**Comment by ianvernon** [comment]
I do not think we should backport substantial CI framework changes to a release branch. The original code should be changed or edited to avoid conflicts instead.

**Comment by mrostecki** [comment]
@ianvernon OK, I will try that approach and push it if it works.

**Comment by mrostecki** [comment]
never-tell-me-the-odds

**Review by brb — APPROVED** [review]
Thanks!

**Pull request merged**
