### PR TITLE
bpf: Fix stale map removal in agent logs

### LINKED ISSUE #17935: cilium: Removed stale bpf map info messages on L4LB-only maps
### What happened?

These should not be created in the first place when running in CNI mode given they belong to L4LB:

```
 k8sPodName=/ subsys=endpoint
level=info msg="Restored endpoint" endpointID=3747 ipAddr="[ ]" subsys=endpoint
level=info msg="Finished regenerating restored endpoints" regenerated=1 subsys=daemon total=1
level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_capture_cache subsys=daemon
level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_ktime_cache subsys=daemon
```

### PR DESCRIPTION
**Pull request by borkmann**
See commit msg.

Fixes: #17935

### CODE REVIEW

**Comment by borkmann** [comment]
test-1.22-4.9

**Review by pchaigno — APPROVED** [review]

**Comment by borkmann** [comment]
test-1.22-4.9

**Pull request merged**
