### PR TITLE
Use generic Set instead of specified Set

### PR DESCRIPTION
**Pull request by bzsuni**
Use generic Set instead of specified Set
sets.String has been deprecated and the generic Set should be used instead

### CODE REVIEW

**Review by ti-mo — APPROVED** [review]

**Comment by giorio94** [comment]
Thanks @bzsuni for your contribution! The file which is modified by this PR appears to be part of a slim copy of the structures used in k8s ([readme](https://github.com/cilium/cilium/blob/e6748209b27ed24b319265ac45b517b9af9b516f/pkg/k8s/slim/README.md)). It is unclear to me whether we want to perform modifications which would cause it to diverge from the upstream version. Though, I'd defer it to other reviewers with more experience about this package.

**Review by jrajahalme — APPROVED** [review]
Given that `sets.String` says it's deprecated and the generic `Set` should be used instead, this is the right thing to do.

**Comment by bzsuni** [comment]
it seems running e2e failed 
https://github.com/cilium/cilium/actions/runs/5329285324/jobs/9659206177?pr=26378#step:14:248

**Comment by ldelossa** [comment]
@bzsuni looks like some tests are stuck. Can you rebase `main` and push this back up?

**Review by aditighag — APPROVED** [review]

**Comment by bzsuni** [comment]
@ldelossa Thank you, I have ebased the `main`

**Review by rolinh — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Review by tommyp1ckles — APPROVED** [review]
thanks for the cleanup!

**Review by qmonnet — CHANGES_REQUESTED** [review]
Thanks! But looking at the commit, I can't find the reason for the change. Please add the motivation in the commit description.

**Comment by bzsuni** [comment]
> Thanks! But looking at the commit, I can't find the reason for the change. Please add the motivation in the commit description.

yes, thanks! sets.String says it's deprecated and the generic Set should be used instead. I wonder if we should also make this change

**Comment by qmonnet** [comment]
> > Thanks! But looking at the commit, I can't find the reason for the change. Please add the motivation in the commit description.
> 
> yes, thanks! sets.String says it's deprecated and the generic Set should be used instead.

Yes I got that from the discussion. Deprecated since v0.26.0, it seems.

> I wonder if we should also make this change

What other change do you mean?

What I'm saying is that your commit description is empty, and does not mention the deprecation. So when we look at the Git history in the future, to understand why this update happened, we'll have none of the context or motivation. Admittedly, it's possible to open the Pull Request discussion to get more info, but doing so shouldn't be necessary. Please state in the commit description the motivation for the change.

**Comment by bzsuni** [comment]
> What I'm saying is that your commit description is empty (save for the sign-off), and does not mention the deprecation. So when we look at the Git history in the future, to understand why this update happened, we'll have none of the context or motivation. Admittedly, it's possible to open the Pull Request discussion to get more info, but doing so shouldn't be necessary. Please state in the commit description the motivation for the change.

Yes, you are right, I have stated it in the commit, thanks

**Review by qmonnet — APPROVED** [review]
Thank you

**Review by learnitall — APPROVED** [review]

**Comment by julianwiedmann** [comment]
Overriding checkpatch's complaint about a typo in the patch description.

**Pull request merged**
