### PR TITLE
v1.11 backports 2021-11-30

### PR DESCRIPTION
**Pull request by qmonnet**
* [x] #18033 (@geakstr)
   (Note: I ran `make -C install/kubernetes` and `make -C Documentation update-helm-values` and committed the resulting changes)
 * [x] #17909 (@Weil0ng)
 * [x] #17958 (@austince)
 * [x] #18017 (@adamzhoul)
 * [x] #18031 (@brb)
 * [x] #18026 (@kaworu)
 * [x] ~#18018 (@brb)~
   Removed because of https://github.com/cilium/cilium/issues/18086
 * [x] #17789 (@krishgobinath)
 * [x] #18057 (@borkmann)
 * [x] #18059 (@tklauser)
 * [x] #18048 (@pchaigno)
 * [x] #18068 (@kkourt)
 * [x] #18006 (@christarazi)
 * [x] #18051 (@joestringer)
 * [x] #17762 (@christarazi)
 * [x] #18052 (@aanm)
 * [x] #18061 (@gandro)
 * [x] #18050 (@aditighag)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18033 17909 17958 18017 18031 18026 17789 18057 18059 18048 18068 18006 18051 17762 18052 18061 18050; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by qmonnet** [comment]
/test-backport-1.11

**Review by borkmann — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
👍 for my change.

**Review by pchaigno — APPROVED** [review]
My PR looks good.

**Review by gandro — APPROVED** [review]
Looks good for my commit!

**Review by brb — APPROVED** [review]
LGTM for my changes, thanks.

**Comment by qmonnet** [comment]
/test-backport-1.11

**Review by christarazi — APPROVED** [review]

**Review by Weil0ng — APPROVED** [review]
My change LGTM.

**Comment by joestringer** [comment]
I didn't triage all the failures, but FYI the 1.19 or lower failures are likely https://github.com/cilium/cilium/issues/18086 .

**Review by kaworu — APPROVED** [review]
my changes LGTM, thanks @qmonnet!

**Comment by qmonnet** [comment]
I removed #18018 (because of #18086) and added #18050 to this PR.

**Comment by qmonnet** [comment]
/test-backport-1.11

**Review by kkourt — APPROVED** [review]

**Review by aditighag — APPROVED** [review]
Thank you!

**Comment by aditighag** [comment]
```
docs: correct ec2 modify net iface action #17958 (@austince)
docs: add registry (quay.io/) for pre-loading images for kind #18017 (@adamzhoul)
Prometheus lint errors in operator metrics #17789
```

LGTM

**Comment by qmonnet** [comment]
[`k8s-1.22-kernel-4.19`](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/51/consoleFull) is similar to https://github.com/cilium/cilium/issues/17895. Most issues of this kind should be fixed by #18051 (by quarantining tests) that we backport in the current PR, but this one hits `Tests with secondary NodePort device`, which is not quarantined.

All other Jenkins issues are https://github.com/cilium/cilium/pull/18060, fixed in https://github.com/cilium/cilium/pull/18087, not backported to v1.11 yet.

I haven't looked into the details of the Conformance issues yet.

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
[ConformanceAKS](https://github.com/cilium/cilium/actions/runs/1530220000) is hitting #18107. Unfortunately part of the issue there is also that the AKS workflow is tearing down the cluster before gathering state from the cluster, so it's difficult to ascertain what went wrong. It's also hitting an error I haven't seen before: `failed to inject labels into ipcache: local identity allocator uninitialized` . This seems to be clearly trying to warn that the agent is not yet initialized, possibly because of an issue in the workflows? Manual validation of v1.11.0-rc3 via #17926 seemed to indicate that AKS is working fine.
[ConformanceEKS](https://github.com/cilium/cilium/actions/runs/1530219993) hit #16938 which I've just submitted a PR to disable to avoid hitting that flake.

**Comment by joestringer** [comment]
I double-checked the Jenkins builds and agree with @qmonnet 's assessment above. This is good to merge, the next batch of v1.11 backports should return stability to the tree.

**Pull request merged**
