### PR TITLE
v1.4 backports 2019-06-18

### PR DESCRIPTION
**Pull request by nebril**
* #8159 -- KVStore bug fixes and small improvements (@aanm)
 * #8192 -- ipcache: Fix automatic recovery of deleted ipcache entries (@tgraf)
 * #8235 -- .Jenkinsfile: remove leftover failFast (@aanm)
 * #8160 -- test: Enable IPv6 forwarding in test VMs (@iffyio)
 * #8249 -- test: bump k8s 1.13 to 1.13.7 (@aanm)
 * #8271 -- k8s: Fix policies with multiple From/To selectors (@gandro)
 * #7869 -- pkg/health: Fix IPv6 URL format in HTTP probe (@iffyio)
 * #8318 -- Don't set debug to true in monitor test (@nebril)
 * #8320 -- pkg/lock: RUnlock in RUnlockIgnoreTime (@aanm)
 * #8319 -- daemon: fix endpoint restore when endpoints are not available (@aanm)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 8159 8192 8235 8160 8249 8271 7869 8318 8320 8319; do contrib/backporting/set-labels.py $pr done 1.4; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8332)

### CODE REVIEW

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by nebril** [comment]
test-me-please

**Pull request merged**
