### PR TITLE
vendor: replace 2 unmaintained dependencies with their blessed forks

### PR DESCRIPTION
**Pull request by rolinh**
Mitchell Hashimoto has [announced](https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc) that he'll be archiving his Go repositories in early 2024.
This PR updates 2 of these dependencies with their blessed forks.

### CODE REVIEW

**Review by sayboras — COMMENTED** [review]
The changes are looking innocent enough, however integration test failure is due to the recent upstream patch

https://github.com/go-viper/mapstructure/pull/6

```
 level=error msg="Invoke failed" ="tables_test.fixture.func1 (pkg/datapath/tables/node_address_test.go:460)" error="could not build arguments for function \"github.com/cilium/cilium/pkg/datapath/tables_test\".fixture.func1 (/home/runner/work/cilium/cilium/pkg/datapath/tables/node_address_test.go:460): failed to build statedb.Table[github.com/cilium/cilium/pkg/datapath/tables.NodeAddress]: could not build arguments for function \"github.com/cilium/cilium/pkg/datapath/tables\".newNodeAddressController (/home/runner/work/cilium/cilium/pkg/datapath/tables/node_address.go:195): failed to build tables.NodeAddressConfig: received non-nil error from function \"github.com/cilium/cilium/pkg/hive/cell\".(*config[...]).Apply.func2 (/home/runner/work/cilium/cilium/pkg/hive/cell/config.go:154): failed to unmarshal config struct tables.NodeAddressConfig: 1 error(s) decoding:\n\n* error decoding 'nodeport-addresses[0]': invalid CIDR address: 2001::/16,10.0.0.0/8.\nHint: field 'FooBar' matches flag 'foo-bar', or use tag `mapstructure:\"flag-name\"` to match field with flag" subsys=hive
 ```

**Review by pippolo84 — APPROVED** [review]

**Review by pippolo84 — COMMENTED** [review]
Changes LGTM, but failures seem related as Tam already said.

**Review by chancez — APPROVED** [review]

**Review by bimmlerd — APPROVED** [review]

**Comment by rolinh** [comment]
Replaced by #32739

**Pull request closed without merging**
