### PR TITLE
bump k8s dependencies to v1.15.12, v1.16.10 and v1.17.6

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Review by gandro — APPROVED** [review]

**Comment by aanm** [comment]
test-missed-k8s

**Pull request merged**
