### PR TITLE
[Doc] - Update link to the contribution guide

### PR DESCRIPTION
**Pull request by manuelbuil**
The link was outdated and pointing nowhere

Signed-off-by: Manuel Buil <mbuil@suse.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10307)

### CODE REVIEW

**Comment by pchaigno** [comment]
This is not the first such pull request. Maybe we should reintroduce `contributing/contributing/` and set up a redirect?

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
> This is not the first such pull request. Maybe we should reintroduce `contributing/contributing/` and set up a redirect?

Do you see a common scenario where users will run into the old link once it is fixed? Some cached version?

**Comment by pchaigno** [comment]
> Do you see a common scenario where users will run into the old link once it is fixed? Some cached version?

Any user that's on an older version of the documentation (e.g., because they landed there from a Google search) and switches to `latest` will get a 404.

**Comment by tgraf** [comment]
> Any user that's on an older version of the documentation (e.g., because they landed there from a Google search) and switches to `latest` will get a 404.

Are you referring to the Cilium documentation? The broken link was in the CONTRIBUTING.md` of the git tree. I would assume that developers will typically look at the version in `master` when looking at this file and not in older branches.

**Comment by pchaigno** [comment]
I'm referring to the Read the docs documentation, not files in the repository. Even once we've found all broken links to `contributing/contributing/` in the sources, we'll still have a broken redirect on Read the docs when switching between versions of the documentation.

**Pull request merged**
