### PR TITLE
k8s: Update libraries to v1.23.5

### PR DESCRIPTION
**Pull request by christarazi**
Signed-off-by: Chris Tarazi <chris@isovalent.com>

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by ldelossa** [comment]
@christarazi does it make sense to hold this until v1.12 release? My thoughts are that there's a few feature branches out there which (especially bgp) which were using the currently vendored versions of k8s tools. 

I think if we merge this and feature branches need to rebase, those feature branche will then get vendor diffs. 

Thoughts?

**Comment by ldelossa** [comment]
@christarazi 

spoke with @aanm and he informed me its not really an issue. Disregard that above comment :)

**Review by ldelossa — APPROVED** [review]

**Pull request closed without merging**
