### PR TITLE
daemon: debuginfo: Read file directly instead of using cat

### PR DESCRIPTION
**Pull request by vadorovsky**
Signed-off-by: Michal Rostecki <mrostecki@suse.de>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6199)

### CODE REVIEW

**Comment by vadorovsky** [comment]
test-me-please

**Comment by vadorovsky** [comment]
test-me-please

**Comment by vadorovsky** [comment]
Unrelated error

**Comment by vadorovsky** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Pull request merged**
