### PR TITLE
bump vagrant box version to 159

### PR DESCRIPTION
**Pull request by ianvernon**
This contains updated image versions used during tests.

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9204)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
This looks fine, though I believe the images in the packer-ci-build are out-of date again (and I'm bumping `cilium-runtime` in another PR at the moment...) so do we want to spin another VM image and bumip it again?

**Comment by aanm** [comment]
> This looks fine, though I believe the images in the packer-ci-build are out-of date again (and I'm bumping `cilium-runtime` in another PR at the moment...) so do we want to spin another VM image and bumip it again?

@joestringer Yes, since we haven't merge this PR.

**Comment by ianvernon** [comment]
Makes sense, closing.

**Pull request closed without merging**
