### PR TITLE
V1.1 10072018

### PR DESCRIPTION
**Pull request by eloycoto**
Backported PRS:

#4648
#4654
#4663
#4670
#4675
#4676
#4678
#4682
#4690
#4708
#4709
#4723
#4739
#4744
#4747
#4753
#4773
#4774
#4780
#4788

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4801)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
Update flake: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4841/console

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
Approving my commits

**Comment by eloycoto** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4850/

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Pull request merged**
