### PR TITLE
test: Unquarantine host firewall + nodeport test

### LINKED ISSUE #23356: CI: K8sDatapathServicesTest Checks N/S loadbalancing With host policy Tests NodePort
This test was quarantined in https://github.com/cilium/cilium/pull/18696, but it seems no issue was created for the flake at the time. The test is consistently failing in CI: https://datastudio.google.com/s/jxRncsyegh4

### Stacktrace
```
/home/jenkins/workspace/cilium-master-k8s-1.26-kernel-net-next-quarantine/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:515
Can not connect to service "tftp://[fd04::12]:30079/hello" from outside cluster (1/10)
Expected command: kubectl exec -n kube-system log-gatherer-wqv64 -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 tftp://[fd04::12]:30079/hello -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Err: exit status 28
Stdout:
 	 time-> DNS: '0.000023()', Connect: '0.000036',Transfer '0.000000', total '5.001194'
Stderr:
 	 command terminated with exit code 28
```

Jenkins: https://jenkins.cilium.io/job/cilium-master-k8s-1.26-kernel-net-next-quarantine/454/testReport/Suite-k8s-1/26/K8sDatapathServicesTest_Checks_N_S_loadbalancing_With_host_policy_Tests_NodePort/
Sysdump: 
[cilium-sysdump.7z.zip](https://github.com/cilium/cilium/files/10502512/cilium-sysdump.7z.zip)

### PR DESCRIPTION
**Pull request by pchaigno**
First commit is the fix from https://github.com/cilium/cilium/pull/25024. Second and third commits fix some general issues in the that test case. Fourth commit unquarantines it.

Fixes: https://github.com/cilium/cilium/issues/23356.

### CODE REVIEW

**Review by nbusseneau — APPROVED** [review]
Acking for `ci-structure` due to trivial changes.

**Review by aspsk — APPROVED** [review]

**Review by viktor-kurchenko — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.27-net-next

**Comment by pchaigno** [comment]
/k8s-1.27-kernel-net-next

**Comment by pchaigno** [comment]
/test-1.27-net-next

**Pull request merged**
