### PR TITLE
pkg/k8s: ignore overwrite source "custom-resource" with "k8s" errors

### PR DESCRIPTION
**Pull request by aanm**
As pointed out in the code changes, it is expected to receive k8s
events after custom-resource events as the propagation delay is often
higher than CRs.

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]
Typo in commit msg. It also says "as pointed out", but no reference to anything

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
ci-gke

**Pull request merged**
