### PR TITLE
v1.8 backports 2020-06-11-2

### PR DESCRIPTION
**Pull request by joestringer**
* #11986 -- contrib/backporting: remove requires-janitor-review label (@aanm)
 * #12025 -- ginkgo-ext: Fix data-race in Writer (@gandro)
 * #12029 -- Implement per-provider operator deployments in Helm (@joestringer)
   * Minor conflict in quick-install yamls, easily resolved
 * #11991 -- install/kubernetes: remove all BPF specific flags from default helm (@aanm)
 * #12026 -- daemon: Allow to fallback to iptables-based masquerading and friends (@brb)
 * #12028 -- docs: Consolidate bpf-map-dynamic-size-ratio documentation (@tklauser)
 * #12004 -- grafana: Add Hubble dashboard (@gandro)
 * #12015 -- cilium: fix encryption flow labels in ip6 case (@jrfastab)
 * #11597 -- helm: added global.cni.readCniConf parameter (@mvisonneau)
 * #11861 -- helm: added global.logOptions parameter (@mvisonneau)
 * #12024 -- hubble/peer: handle burst of change notifications (@Rolinh)
 * #12041 -- test/K8sServices: disable fragment tracking test for kernel 4.19 (@qmonnet)
 * #11939 -- release: Improve documentation around release process (@joestringer)
 * #12043 -- .travis: disable Documentation building on ARM64 (@Jianlin-lv)
 * #11977 -- bpf: split off debug options and do not run it in ci (@borkmann)
 * #12014 -- Fix setting monitorAggregationLevel to max reflects via CLI (@soumynathan)
 * #12055 -- Fix missing operator-generic in upstream k8s tests (@aanm)
 * #12051 -- test/k8s: keep configmap across upgrade test (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 11991 12026 12028 12004 12015 11597 11861 12024 12041 11939 11986 12025 12029 12043 11977 12014 12055 12051; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by joestringer** [comment]
test-backport-1.8

**Comment by aanm** [comment]
test-backport-1.8

**Review by tklauser — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]
> * #12041 -- test/K8sServices: disable fragment tracking test for kernel 4.19 (@qmonnet)

Looks good to me. Thanks!

**Comment by aanm** [comment]
the upgrade tests should be fixed once we backport #12051

**Comment by aanm** [comment]
the upstream k8s will probably be fixed once we backport https://github.com/cilium/cilium/pull/12055

**Comment by joestringer** [comment]
test-backport-1.8

**Comment by aanm** [comment]
test-backport-1.8

**Pull request merged**
