### PR TITLE
Envoy update for service mesh

### PR DESCRIPTION
**Pull request by jrajahalme**
Update Envoy image and API use to be ready for Cilium Envoy Config CRD and Cilium service mesh.

This is a prerequisite for #18894

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Comment by jrajahalme** [comment]
Rebased to pick up CI fixes from master.

**Comment by jrajahalme** [comment]
runtime provision fail, retesting...

**Review by sayboras — APPROVED** [review]

**Review by sayboras — APPROVED** [review]

**Comment by michi-covalent** [comment]
hey @jrajahalme looks like this PR is good to go, could you resolve the conflict? 🙏

**Comment by jrajahalme** [comment]
> hey @jrajahalme looks like this PR is good to go, could you resolve the conflict? 🙏

Done :-)

**Review by ldelossa — APPROVED** [review]

**Pull request merged**
