### PR TITLE
Use Docker buildkit in the CI

### PR DESCRIPTION
**Pull request by jrajahalme**
Use DOCKER_BUILDKIT in the CI.

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-gke

**Review by aanm — APPROVED** [review]

**Comment by jrajahalme** [comment]
Unrelated provision error in net-next, retesting

**Comment by jrajahalme** [comment]
retest-net-next

**Comment by jrajahalme** [comment]
GKE needs these to be added to .gitignore:
```
  	test/gke/cluster-name
  	test/gke/cluster-uri
  	test/gke/cluster-version
  	test/gke/gke-kubeconfig
  	test/gke/resize-kubeconfig
```

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-gke

**Comment by jrajahalme** [comment]
retest-gke

**Comment by jrajahalme** [comment]
test-gke

**Comment by jrajahalme** [comment]
retest-net-next

**Comment by jrajahalme** [comment]
Unrelated GKE upgrade/downgrade fail

**Review by aanm — APPROVED** [review]

**Pull request merged**
