### PR TITLE
node: introduce prefix cluster mutator

### PR DESCRIPTION
**Pull request by giorio94**
Please refer to the respective commit descriptions for additional details.

### CODE REVIEW

**Review by dylandreimerink — APPROVED** [review]

**Review by thorn3r — APPROVED** [review]
elegant :man_dancing:

**Comment by giorio94** [comment]
Rebased onto main to resolve a conflict.

**Comment by giorio94** [comment]
Could someone from @cilium/ipsec please have a final look? 🙏

**Comment by giorio94** [comment]
Rebased onto main to pick a CI fix.

**Review by pchaigno — APPROVED** [review]
Ack for IPsec. I don't see any IPsec-logic being touched :)

**Pull request merged**
