### PR TITLE
Update Go to 1.19.3

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by tbalthazar** [comment]
@tklauser minor: it looks like the branch for this PR was opened after https://github.com/cilium/cilium/pull/22030 got merged. We might want to rebase this PR on `main` and `make update-go-version` again to also update the Go version in `contrib/backporting/Dockerfile`.

**Comment by tklauser** [comment]
> @tklauser minor: it looks like the branch for this PR was opened after #22030 got merged. We might want to rebase this PR on `main` and `make update-go-version` again to also update the Go version in `contrib/backporting/Dockerfile`.

Thanks @tbalthazar, good point. I've rebased this branch and updated the Go version in `contrib/backporting/Dockerfile`.

**Comment by tklauser** [comment]
/test-1.23-5.4

**Comment by tklauser** [comment]
Runtime tests failed on #22078 (https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/3895/) all other required tests passed and reviews are in. Marking as ready to merge.

**Pull request merged**
