### PR TITLE
[CI] use helm template for fqdn tests bind deployment

### PR DESCRIPTION
**Pull request by nebril**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9703)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-eks K8sFQDNTest*

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-eks K8sFQDNTest*

**Comment by nebril** [comment]
test-eks K8sFQDNTest*

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-eks K8sFQDNTest*

**Comment by nebril** [comment]
test-eks K8sFQDNTest*

**Comment by nebril** [comment]
test-eks K8sFQDNTest*

**Comment by nebril** [comment]
test-eks K8sFQDNTest*

**Comment by nebril** [comment]
test-eks K8sFQDNTest*

**Comment by nebril** [comment]
test-eks K8sFQDNTest*

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-eks K8sFQDNTest*

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-eks K8sFQDNTest*

**Comment by nebril** [comment]
test-eks K8sFQDNTest*

**Comment by nebril** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by nebril** [comment]
test-eks K8sFQDNTest*

**Comment by nebril** [comment]
test-eks K8sFQDNTest*

**Comment by nebril** [comment]
test-eks K8sFQDNTest*

**Comment by nebril** [comment]
test-eks K8sFQDNTest*

**Comment by raybejjani** [comment]
test-me-please

**Pull request closed without merging**
