### PR TITLE
v1.3 backports 18-11-21

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:

* #6269 
* #6258 

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6278)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Downloading VM timed out: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8132/execution/node/70/log/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Similar timeout for the K8s tests:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1280/

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by aanm — APPROVED** [review]

**Comment by ianvernon** [comment]
Keep hitting really low VM download speeds...

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8137/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Long-lived connection test failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1282/

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
VM download failed again...

**Comment by ianvernon** [comment]
test-missed-k8s

**Pull request merged**
