### PR TITLE
V1.0 backports 18 04 26

### PR DESCRIPTION
**Pull request by nebril**

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by raybejjani** [comment]
test-docs-please

**Comment by nebril** [comment]
@raybejjani seems like `docs.Jenkinsfile` is missing in 1.0, should it also be backported?

**Comment by raybejjani** [comment]
Good question. My guess is yes, but maybe the scaffolding isn't in place on the 1.0 branch.

@eloycoto Can we backport docs.Jenkinsfile to v1.0?

**Comment by eloycoto** [comment]
+1 to backport it ;-)

**Comment by eloycoto** [comment]
PRs to backport: 
https://github.com/cilium/cilium/pull/3686
https://github.com/cilium/cilium/pull/3787

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
Oops, just saw the above comment thread, didn't realize that docs tests won't work.

**Comment by ianvernon** [comment]
We have not backported any doc changes to 1.0 due to severe merge conflicts. We have the `doc-1.0` branch for doc changes for 1.0.

**Comment by ianvernon** [comment]
Given the above, I think this can be merged.

**Comment by raybejjani** [comment]
Oh, I just realised you are also the backporter this week, @ianvernon (I thought a week had already passed!). I had hoped to merge this before the other backporter came online to avoid confusion.
I'll merge this but my hope was to test the docs, which was why I was trying to run them. While the test itself is difficult to backport, I imagine the jenkinsfile is not, right?

**Pull request merged**
