### PR TITLE
test: Delete DNS pods in AfterAll for datapath tests

### LINKED ISSUE #16717: CI: K8sFQDNTest Restart Cilium validate that FQDN is still working: Error reaching kube-dns before test
https://jenkins.cilium.io/job/cilium-master-k8s-1.17-kernel-4.9/132/testReport/Suite-k8s-1/17/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/
[3205f837_K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working.zip](https://github.com/cilium/cilium/files/6743789/3205f837_K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working.zip)

### Stacktrace
```
/home/jenkins/workspace/cilium-master-k8s-1.17-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:465
Error reaching kube-dns before test: error looking up kube-dns.kube-system.svc.cluster.local from default/app2-5cc5d58844-nv6wr: ;; connection timed out; no servers could be reached

command terminated with exit code 1

Expected
    <*errors.errorString | 0xc0024981b0>: {
        s: "error looking up kube-dns.kube-system.svc.cluster.local from default/app2-5cc5d58844-nv6wr: ;; connection timed out; no servers could be reached\n\ncommand terminated with exit code 1\n",
    }
to be nil
/home/jenkins/workspace/cilium-master-k8s-1.17-kernel-4.9/src/github.com/cilium/cilium/test/k8sT/fqdn.go:89
```
### Standard Output
```
Cilium pods: [cilium-mxkd7 cilium-zggcq]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                          Ingress   Egress
grafana-7fd557d749-qs865               
prometheus-d87f8f984-7rqc2             
app1-7b6ddb776f-9q5nl                  
app1-7b6ddb776f-n4vvx                  
app2-5cc5d58844-nv6wr                  
app3-6c7856c5b5-fs6n9                  
coredns-767d4c6dd7-jsfcl               
Cilium agent 'cilium-mxkd7': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 36 Failed 0
Cilium agent 'cilium-zggcq': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 35 Failed 0
```
### Standard Error
<details><summary>Click to show</summary>

```
15:21:47 STEP: Running BeforeAll block for EntireTestsuite K8sFQDNTest
15:21:47 STEP: Ensuring the namespace kube-system exists
15:21:47 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs")
15:21:47 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs") => <nil>
15:21:47 STEP: Installing Cilium
15:21:48 STEP: Waiting for Cilium to become ready
15:22:18 STEP: Validating if Kubernetes DNS is deployed
15:22:18 STEP: Checking if deployment is ready
15:22:18 STEP: Checking if kube-dns service is plumbed correctly
15:22:18 STEP: Checking if DNS can resolve
15:22:18 STEP: Checking if pods have identity
15:22:20 STEP: Kubernetes DNS is up and operational
15:22:20 STEP: Validating Cilium Installation
15:22:20 STEP: Performing Cilium controllers preflight check
15:22:20 STEP: Performing Cilium health check
15:22:20 STEP: Performing Cilium status preflight check
15:22:26 STEP: Performing Cilium service preflight check
15:22:26 STEP: Performing K8s service preflight check
15:22:26 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-mxkd7': Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 1
	 

15:22:26 STEP: Performing Cilium controllers preflight check
15:22:26 STEP: Performing Cilium status preflight check
15:22:26 STEP: Performing Cilium health check
15:22:28 STEP: Performing Cilium service preflight check
15:22:28 STEP: Performing K8s service preflight check
15:22:28 STEP: Performing Cilium controllers preflight check
15:22:28 STEP: Performing Cilium health check
15:22:28 STEP: Performing Cilium status preflight check
15:22:30 STEP: Performing Cilium service preflight check
15:22:30 STEP: Performing K8s service preflight check
15:22:30 STEP: Performing Cilium controllers preflight check
15:22:30 STEP: Performing Cilium status preflight check
15:22:30 STEP: Performing Cilium health check
15:22:31 STEP: Performing Cilium service preflight check
15:22:31 STEP: Performing K8s service preflight check
15:22:31 STEP: Performing Cilium status preflight check
15:22:31 STEP: Performing Cilium controllers preflight check
15:22:31 STEP: Performing Cilium health check
15:22:34 STEP: Performing Cilium service preflight check
15:22:34 STEP: Performing K8s service preflight check
15:22:34 STEP: Performing Cilium controllers preflight check
15:22:34 STEP: Performing Cilium status preflight check
15:22:34 STEP: Performing Cilium health check
15:22:35 STEP: Performing Cilium service preflight check
15:22:35 STEP: Performing K8s service preflight check
15:22:35 STEP: Performing Cilium controllers preflight check
15:22:35 STEP: Performing Cilium health check
15:22:35 STEP: Performing Cilium status preflight check
15:22:38 STEP: Performing Cilium service preflight check
15:22:38 STEP: Performing K8s service preflight check
15:22:38 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-mxkd7': Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 1
	 

15:22:38 STEP: Performing Cilium controllers preflight check
15:22:38 STEP: Performing Cilium status preflight check
15:22:38 STEP: Performing Cilium health check
15:22:40 STEP: Performing Cilium service preflight check
15:22:40 STEP: Performing K8s service preflight check
15:22:40 STEP: Performing Cilium controllers preflight check
15:22:40 STEP: Performing Cilium status preflight check
15:22:40 STEP: Performing Cilium health check
15:22:41 STEP: Performing Cilium service preflight check
15:22:41 STEP: Performing K8s service preflight check
15:22:41 STEP: Performing Cilium status preflight check
15:22:41 STEP: Performing Cilium controllers preflight check
15:22:41 STEP: Performing Cilium health check
15:22:43 STEP: Performing Cilium service preflight check
15:22:43 STEP: Performing K8s service preflight check
15:22:43 STEP: Performing Cilium controllers preflight check
15:22:43 STEP: Performing Cilium status preflight check
15:22:43 STEP: Performing Cilium health check
15:22:45 STEP: Performing Cilium service preflight check
15:22:45 STEP: Performing K8s service preflight check
15:22:45 STEP: Performing Cilium controllers preflight check
15:22:45 STEP: Performing Cilium health check
15:22:45 STEP: Performing Cilium status preflight check
15:22:47 STEP: Performing Cilium service preflight check
15:22:47 STEP: Performing K8s service preflight check
15:22:47 STEP: Performing Cilium controllers preflight check
15:22:47 STEP: Performing Cilium status preflight check
15:22:47 STEP: Performing Cilium health check
15:22:48 STEP: Performing Cilium service preflight check
15:22:48 STEP: Performing K8s service preflight check
15:22:48 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-mxkd7': Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 1
	 

15:22:48 STEP: Performing Cilium controllers preflight check
15:22:48 STEP: Performing Cilium health check
15:22:48 STEP: Performing Cilium status preflight check
15:22:50 STEP: Performing Cilium service preflight check
15:22:50 STEP: Performing K8s service preflight check
15:22:50 STEP: Performing Cilium controllers preflight check
15:22:50 STEP: Performing Cilium status preflight check
15:22:50 STEP: Performing Cilium health check
15:22:51 STEP: Performing Cilium service preflight check
15:22:51 STEP: Performing K8s service preflight check
15:22:51 STEP: Performing Cilium controllers preflight check
15:22:51 STEP: Performing Cilium health check
15:22:51 STEP: Performing Cilium status preflight check
15:22:54 STEP: Performing Cilium service preflight check
15:22:54 STEP: Performing K8s service preflight check
15:22:54 STEP: Performing Cilium status preflight check
15:22:54 STEP: Performing Cilium controllers preflight check
15:22:54 STEP: Performing Cilium health check
15:22:57 STEP: Performing Cilium service preflight check
15:22:57 STEP: Performing K8s service preflight check
15:22:57 STEP: Performing Cilium controllers preflight check
15:22:57 STEP: Performing Cilium status preflight check
15:22:57 STEP: Performing Cilium health check
15:23:00 STEP: Performing Cilium service preflight check
15:23:00 STEP: Performing K8s service preflight check
15:23:00 STEP: Performing Cilium controllers preflight check
15:23:00 STEP: Performing Cilium health check
15:23:00 STEP: Performing Cilium status preflight check
15:23:01 STEP: Performing Cilium service preflight check
15:23:01 STEP: Performing K8s service preflight check
15:23:01 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-mxkd7': Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 1
	 

15:23:01 STEP: Performing Cilium controllers preflight check
15:23:01 STEP: Performing Cilium health check
15:23:01 STEP: Performing Cilium status preflight check
15:23:02 STEP: Performing Cilium service preflight check
15:23:02 STEP: Performing K8s service preflight check
15:23:02 STEP: Performing Cilium controllers preflight check
15:23:02 STEP: Performing Cilium health check
15:23:02 STEP: Performing Cilium status preflight check
15:23:03 STEP: Performing Cilium service preflight check
15:23:03 STEP: Performing K8s service preflight check
15:23:03 STEP: Performing Cilium controllers preflight check
15:23:03 STEP: Performing Cilium status preflight check
15:23:03 STEP: Performing Cilium health check
15:23:05 STEP: Performing Cilium service preflight check
15:23:05 STEP: Performing K8s service preflight check
15:23:05 STEP: Performing Cilium controllers preflight check
15:23:05 STEP: Performing Cilium health check
15:23:05 STEP: Performing Cilium status preflight check
15:23:08 STEP: Performing Cilium service preflight check
15:23:08 STEP: Performing K8s service preflight check
15:23:08 STEP: Performing Cilium controllers preflight check
15:23:08 STEP: Performing Cilium status preflight check
15:23:08 STEP: Performing Cilium health check
15:23:10 STEP: Performing Cilium service preflight check
15:23:10 STEP: Performing K8s service preflight check
15:23:10 STEP: Performing Cilium controllers preflight check
15:23:10 STEP: Performing Cilium status preflight check
15:23:10 STEP: Performing Cilium health check
15:23:11 STEP: Performing Cilium service preflight check
15:23:11 STEP: Performing K8s service preflight check
15:23:11 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-mxkd7': Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 1
	 

15:23:11 STEP: Performing Cilium controllers preflight check
15:23:11 STEP: Performing Cilium health check
15:23:11 STEP: Performing Cilium status preflight check
15:23:13 STEP: Performing Cilium service preflight check
15:23:13 STEP: Performing K8s service preflight check
15:23:13 STEP: Performing Cilium controllers preflight check
15:23:13 STEP: Performing Cilium health check
15:23:13 STEP: Performing Cilium status preflight check
15:23:16 STEP: Performing Cilium service preflight check
15:23:16 STEP: Performing K8s service preflight check
15:23:16 STEP: Performing Cilium status preflight check
15:23:16 STEP: Performing Cilium controllers preflight check
15:23:16 STEP: Performing Cilium health check
15:23:18 STEP: Performing Cilium service preflight check
15:23:18 STEP: Performing K8s service preflight check
15:23:19 STEP: Waiting for cilium-operator to be ready
15:23:19 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator")
15:23:19 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator") => <nil>
15:23:19 STEP: Applying demo manifest
15:23:19 STEP: WaitforPods(namespace="default", filter="-l zgroup=testapp")
15:23:29 STEP: WaitforPods(namespace="default", filter="-l zgroup=testapp") => <nil>
FAIL: Error reaching kube-dns before test: error looking up kube-dns.kube-system.svc.cluster.local from default/app2-5cc5d58844-nv6wr: ;; connection timed out; no servers could be reached

command terminated with exit code 1

Expected
    <*errors.errorString | 0xc0024981b0>: {
        s: "error looking up kube-dns.kube-system.svc.cluster.local from default/app2-5cc5d58844-nv6wr: ;; connection timed out; no servers could be reached\n\ncommand terminated with exit code 1\n",
    }
to be nil
===================== TEST FAILED =====================
15:27:29 STEP: Running AfterFailed block for EntireTestsuite K8sFQDNTest
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                               READY   STATUS    RESTARTS   AGE     IP              NODE   NOMINATED NODE   READINESS GATES
	 cilium-monitoring   grafana-7fd557d749-qs865           1/1     Running   0          72m     10.0.0.90       k8s2   <none>           <none>
	 cilium-monitoring   prometheus-d87f8f984-7rqc2         1/1     Running   0          72m     10.0.0.2        k8s2   <none>           <none>
	 default             app1-7b6ddb776f-9q5nl              2/2     Running   0          4m13s   10.0.1.84       k8s1   <none>           <none>
	 default             app1-7b6ddb776f-n4vvx              2/2     Running   0          4m13s   10.0.1.52       k8s1   <none>           <none>
	 default             app2-5cc5d58844-nv6wr              1/1     Running   0          4m13s   10.0.1.234      k8s1   <none>           <none>
	 default             app3-6c7856c5b5-fs6n9              1/1     Running   0          4m13s   10.0.1.159      k8s1   <none>           <none>
	 kube-system         cilium-mxkd7                       1/1     Running   0          5m45s   192.168.36.11   k8s1   <none>           <none>
	 kube-system         cilium-operator-5f99fccbd8-2dbr9   1/1     Running   0          5m44s   192.168.36.11   k8s1   <none>           <none>
	 kube-system         cilium-operator-5f99fccbd8-dvpg7   1/1     Running   0          5m44s   192.168.36.12   k8s2   <none>           <none>
	 kube-system         cilium-zggcq                       1/1     Running   0          5m44s   192.168.36.12   k8s2   <none>           <none>
	 kube-system         coredns-767d4c6dd7-jsfcl           1/1     Running   0          7m6s    10.0.0.251      k8s2   <none>           <none>
	 kube-system         etcd-k8s1                          1/1     Running   0          75m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-apiserver-k8s1                1/1     Running   0          75m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-controller-manager-k8s1       1/1     Running   0          75m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-2tcqm                   1/1     Running   0          75m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-dx6pr                   1/1     Running   0          73m     192.168.36.12   k8s2   <none>           <none>
	 kube-system         kube-scheduler-k8s1                1/1     Running   0          75m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-kcfvr                 1/1     Running   0          72m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-qcb6s                 1/1     Running   0          72m     192.168.36.12   k8s2   <none>           <none>
	 kube-system         registry-adder-26hfp               1/1     Running   0          72m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         registry-adder-ldqph               1/1     Running   0          72m     192.168.36.12   k8s2   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-mxkd7 cilium-zggcq]
cmd: kubectl exec -n kube-system cilium-mxkd7 -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend             Service Type   Backend                   
	 1    10.111.116.89:9090   ClusterIP      1 => 10.0.0.2:9090        
	 2    10.96.66.132:80      ClusterIP      1 => 10.0.1.84:80         
	                                          2 => 10.0.1.52:80         
	 3    10.96.0.1:443        ClusterIP      1 => 192.168.36.11:6443   
	 4    10.96.0.10:53        ClusterIP      1 => 10.0.0.251:53        
	 5    10.96.0.10:9153      ClusterIP      1 => 10.0.0.251:9153      
	 6    10.106.214.25:3000   ClusterIP      1 => 10.0.0.90:3000       
	 7    10.96.66.132:69      ClusterIP      1 => 10.0.1.84:69         
	                                          2 => 10.0.1.52:69         
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-mxkd7 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                            IPv6        IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                  
	 880        Disabled           Disabled          13212      k8s:appSecond=true                                     fd02::1af   10.0.1.234   ready   
	                                                            k8s:id=app2                                                                             
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app2-account                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                                 
	                                                            k8s:zgroup=testapp                                                                      
	 1129       Disabled           Disabled          2894       k8s:id=app1                                            fd02::1d3   10.0.1.52    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                                 
	                                                            k8s:zgroup=testapp                                                                      
	 1749       Disabled           Disabled          4          reserved:health                                        fd02::157   10.0.1.221   ready   
	 1868       Disabled           Disabled          2894       k8s:id=app1                                            fd02::16a   10.0.1.84    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                                 
	                                                            k8s:zgroup=testapp                                                                      
	 2876       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s1                                                      ready   
	                                                            k8s:node-role.kubernetes.io/master                                                      
	                                                            reserved:host                                                                           
	 3081       Disabled           Disabled          48485      k8s:id=app3                                            fd02::19a   10.0.1.159   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                         
	                                                            k8s:io.kubernetes.pod.namespace=default                                                 
	                                                            k8s:zgroup=testapp                                                                      
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-zggcq -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend             Service Type   Backend                   
	 1    10.96.0.10:53        ClusterIP      1 => 10.0.0.251:53        
	 2    10.96.0.10:9153      ClusterIP      1 => 10.0.0.251:9153      
	 3    10.106.214.25:3000   ClusterIP      1 => 10.0.0.90:3000       
	 4    10.111.116.89:9090   ClusterIP      1 => 10.0.0.2:9090        
	 5    10.96.66.132:69      ClusterIP      1 => 10.0.1.84:69         
	                                          2 => 10.0.1.52:69         
	 6    10.96.0.1:443        ClusterIP      1 => 192.168.36.11:6443   
	 7    10.96.66.132:80      ClusterIP      1 => 10.0.1.84:80         
	                                          2 => 10.0.1.52:80         
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-zggcq -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                              IPv6       IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                   
	 27         Disabled           Disabled          2560       k8s:app=grafana                                          fd02::1    10.0.0.90    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                          
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                        
	 112        Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s2                                                       ready   
	                                                            reserved:host                                                                            
	 2245       Disabled           Disabled          4          reserved:health                                          fd02::81   10.0.0.201   ready   
	 2411       Disabled           Disabled          471        k8s:app=prometheus                                       fd02::7a   10.0.0.2     ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                   
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                        
	 3246       Disabled           Disabled          28075      k8s:io.cilium.k8s.policy.cluster=default                 fd02::51   10.0.0.251   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                          
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                              
	                                                            k8s:k8s-app=kube-dns                                                                     
	 
Stderr:
 	 

===================== Exiting AfterFailed =====================
15:27:50 STEP: Running AfterEach for block EntireTestsuite K8sFQDNTest
15:27:50 STEP: Running AfterEach for block EntireTestsuite
```
</details

### PR DESCRIPTION
**Pull request by joestringer**
Commit a0e77127dcd7 ("test: Redeploy DNS after changing endpointRoutes")
didn't go quite far enough: It ensured that between individual tests in
a given file, the DNS pods would be redeployed during the next run if
there were significant enough datapath changes. However, the way it did
this was by storing state within the 'kubectl' variable, which is
recreated in each test file. So if the last test in one CI run enabled
endpoint routes mode, then the DNS pods would not be redeployed to
disable endpoint routes mode as part of the next test.

Fix it by just deleting the overall kube-dns deployment at the end of
any test files which reconfigure this datapath option. I assume that the
next test will set up DNS again if it's not available.

Reported-by: Chris Tarazi <chris@isovalent.com>
Fixes: 0e77127dcd7 ("test: Redeploy DNS after changing endpointRoutes")
Fixes: #16717

### CODE REVIEW

**Review by christarazi — APPROVED** [review]
LGTM, simple enough. This is a prime example of something that could easily reoccur again because someone isn't aware that this must be done if they configure endpoint-routes mode. However, it seems this would be unlikely to happen in the near future so we don't have to solve this problem now.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
I manually tried this out by just running:

```
CNI_INTEGRATION=minikube K8S_VERSION=1.20 ginkgo --focus="K8sCustom*" -- -cilium.provision=false -cilium.kubeconfig=`echo ~/.kube/config` -cilium.image="quay.io/cilium/cilium-ci" -cilium.operator-image="quay.io/cilium/operator" -cilium.operator-suffix="-ci" -cilium.passCLIEnvironment=true
```

And sure enough, kube-dns was gone at the end along with Cilium.

I'm not the biggest fan of how the testsuite leaves your cluster in a broken state after it completes (rather than returning to where it started), but I think that's already the case so if we want to fix that we can follow up separately.

**Comment by joestringer** [comment]
Cilium init pods went into crashloopbackoff, many of the jobs seem to have the same issue:

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/1018/testReport/junit/Suite-k8s-1/21/K8sHubbleTest_Hubble_Observe_Test_L3_L4_Flow/
```
	 kube-system         cilium-5jwhk                       0/1     Init:CrashLoopBackOff   5          4m2s    192.168.36.11   k8s1     <none>           <none>
	 kube-system         cilium-fz9m9                       0/1     Init:CrashLoopBackOff   5          4m2s    192.168.36.12   k8s2     <none>           <none>
```

**Comment by joestringer** [comment]
`cilium-combined-logs-previous.txt` shows that it's a problem with the mount init container:
```
2021-07-09T00:25:29.978691280Z cp: cannot stat '/usr/bin/cilium-mount': No such file or directory
2021-07-09T00:25:29.979226735Z rm: cannot remove '/hostbin/cilium-mount': No such file or directory
Error from server (BadRequest): previous terminated container "clean-cilium-state" in pod "cilium-5jwhk" not found
```

I'll try rebasing to see whether I just need to pull in https://github.com/cilium/cilium/pull/16815 to resolve the issue.

**Comment by joestringer** [comment]
test-me-please

**Comment by aditighag** [comment]
> `cilium-combined-logs-previous.txt` shows that it's a problem with the mount init container:
> 
> ```
> 
> 2021-07-09T00:25:29.978691280Z cp: cannot stat '/usr/bin/cilium-mount': No such file or directory
> 
> 2021-07-09T00:25:29.979226735Z rm: cannot remove '/hostbin/cilium-mount': No such file or directory
> 
> Error from server (BadRequest): previous terminated container "clean-cilium-state" in pod "cilium-5jwhk" not found
> 
> ```
> 
> 
> 
> I'll try rebasing to see whether I just need to pull in https://github.com/cilium/cilium/pull/16815 to resolve the issue.

This init container change was introduced in #16815. Looks like there is a mismatch between cilium daemonset (up-to-date with master) used and image built on your PR (not up-to-date). Yeah, please rebase your PR.

**Comment by joestringer** [comment]
Also hit https://github.com/cilium/cilium/issues/16846 .

**Comment by joestringer** [comment]
Evidently not all of the tests ensure that DNS is deployed before running, so the current version of the fix breaks those tests because they're relying on DNS from previous runs.

Maybe I'll just do a complete Cilium + DNS forced redeploy in the AfterAll of the relevant test suites (K8sCustomCalls, K8sDatapathConfig). It may take a few minutes longer but should do the trick.

**Comment by joestringer** [comment]
OK, turns out Cilium was already getting removed at the end of the tests, we just weren't cleaning up the DNS pods. My previous iteration removed the DNS _deployment_, and apparently subsequent tests wouldn't ensure this was available. But if Cilium has been removed, it should be sufficient to simply delete the DNS _pods_ and let them get rescheduled into the cluster (then hopefully the next iteration of Cilium will provision the networking for them).

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Triage:
* CI 3.0 did not run because only `test/ ` code changes were made here.
* Travis failed with known flake #12756 
* Cilium-PR-K8s-1.16-net-next failed with what looks like https://github.com/cilium/cilium/issues/16399
* All other Ginkgo runs were successful.

This is addressing a known flake in the tree and is now only hitting other known flakes. Good to merge.

**Comment by nbusseneau** [comment]
Marking for backport to 1.9 following discussion here: https://github.com/cilium/cilium/pull/18031#issuecomment-991084995

**Pull request merged**
