### PR TITLE
CI: Multi-monitor test is resilient to  misalignments

### PR DESCRIPTION
**Pull request by raybejjani**
This fixes a flake I noticed(https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/3025/testReport/junit/(root)/Suite-runtime/RuntimeMonitorTest_With_Sample_Containers_multiple_monitors/). I'm not sure that the code is clear, however, so I'm open to not doing this or doing something different.

<details><summary>The flake error</summary>

```
/home/jenkins/workspace/cilium-ginkgo_cilium_master/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
Expected
    <string>: Press Ctrl-C to quit
    >> Policy updated: {"revision":50,"rule_count":0}
    level=info msg="Initializing dissection cache..." subsys=monitor
    <- endpoint 1491 flow 0xb1f59987 identity 62740->0 state new ifindex 0: 10.15.40.251 -> 10.15.150.31 EchoRequest
    -> endpoint 3824 flow 0xb1f59987 identity 62740->25875 state established ifindex lxcfa6bc2a8888c: 10.15.40.251 -> 10.15.150.31 EchoRequest
    <- endpoint 3824 flow 0xb1f59987 identity 25875->0 state new ifindex 0: 10.15.150.31 -> 10.15.40.251 EchoReply
    -> endpoint 1491 flow 0xb1f59987 identity 25875->62740 state reply ifindex lxced14b1725bb6: 10.15.150.31 -> 10.15.40.251 EchoReply
    <- endpoint 1491 flow 0xb1f59987 identity 62740->0 state new ifindex 0: 10.15.40.251 -> 10.15.150.31 EchoRequest
    -> endpoint 3824 flow 0xb1f59987 identity 62740->25875 state established ifindex lxcfa6bc2a8888c: 10.15.40.251 -> 10.15.150.31 EchoRequest
    <- endpoint 3824 flow 0xb1f59987 identity 25875->0 state new ifindex 0: 10.15.150.31 -> 10.15.40.251 EchoReply
    -> endpoint 1491 flow 0xb1f59987 identity 25875->62740 state reply ifindex lxced14b1725bb6: 10.15.150.31 -> 10.15.40.251 EchoReply
    <- endpoint 1491 flow 0xb1f59987 identity 62740->0 state new ifindex 0: 10.15.40.251 -> 10.15.150.31 EchoRequest
    -> endpoint 3824 flow 0xb1f59987 identity 62740->25875 state established ifindex lxcfa6bc2a8888c: 10.15.40.251 -> 10.15.150.31 EchoRequest
    <- endpoint 3824 flow 0xb1f59987 identity 25875->0 state new ifindex 0: 10.15.150.31 -> 10.15.40.251 EchoReply
    -> endpoint 1491 flow 0xb1f59987 identity 25875->62740 state reply ifindex lxced14b1725bb6: 10.15.150.31 -> 10.15.40.251 EchoReply
    <- endpoint 1491 flow 0xb1f59987 identity 62740->0 state new ifindex 0: 10.15.40.251 -> 10.15.150.31 EchoRequest
    -> endpoint 3824 flow 0xb1f59987 identity 62740->25875 state established ifindex lxcfa6bc2a8888c: 10.15.40.251 -> 10.15.150.31 EchoRequest
    <- endpoint 3824 flow 0xb1f59987 identity 25875->0 state new ifindex 0: 10.15.150.31 -> 10.15.40.251 EchoReply
    -> endpoint 1491 flow 0xb1f59987 identity 25875->62740 state reply ifindex lxced14b1725bb6: 10.15.150.31 -> 10.15.40.251 EchoReply
    ^C
    Received an interrupt, disconnecting from monitor...
    
    
to contain substring
    <string>: -> lxcc169528a9c84: 52:a4:9a:c4:b7:74 -> 92:64:cf:da:6f:e1 ARP
/home/jenkins/workspace/cilium-ginkgo_cilium_master/runtime-gopath/src/github.com/cilium/cilium/test/runtime/monitor.go:281
```

</details>

We previously randomly sampled lines from the first monitor's output
and compared them to the others. Due to scheduling differences for each
invocation of monitor, we also skipped some lines to account for one
instance seeing traffic earlier than another. This was susceptible to
instances where 5 skipped lines was not enough.
This change switches the code to look for the presence of the shortest
monitor output in all the others, without ordering differences or
additions/removals.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8348)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]

**Pull request merged**
