### PR TITLE
github/workflows: Enable DSR with WireGuard in ci-dp

### PR DESCRIPTION
**Pull request by brb**
Successful run https://github.com/cilium/cilium/actions/runs/4795620155/jobs/8530423625.

### CODE REVIEW

**Review by viktor-kurchenko — APPROVED** [review]

**Review by gentoo-root — APPROVED** [review]
Seems that https://github.com/cilium/cilium/issues/23461 from test 9 was also closed recently.

**Comment by brb** [comment]
> Seems that https://github.com/cilium/cilium/issues/23461 from test 9 was also closed recently.

Sweet, let me try to open a separate PR.

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
I'm confused - the successful run wasn't successful (see config 14):
https://github.com/cilium/cilium/actions/runs/4795620155/jobs/8530423625

**Comment by julianwiedmann** [comment]
> @julianwiedmann That run tried to change both 13 and 14, but in the final commit I ended up changing only 13, as we cannot change 14 due to:
> 
> > We didn't enable for the second TODO as DSR is not supported with the VXLAN.

duh - thanks, that didn't parse. We could enable DSR-GENEVE of course :100:

**Review by julianwiedmann — APPROVED** [review]

**Comment by brb** [comment]
> We could enable DSR-GENEVE of course 100

My brain is lagging, but in the non-standalone LB mode, right?

**Comment by julianwiedmann** [comment]
> > We could enable DSR-GENEVE of course 100
> 
> My brain is lagging, but in the non-standalone LB mode, right?

yep, https://docs.cilium.io/en/latest/network/kubernetes/kubeproxy-free/#direct-server-return-dsr-with-geneve

**Comment by brb** [comment]
@julianwiedmann Let's do that in a separate PR. We could dedicate one configuration slot to enable GENEVE with DSR.

**Pull request merged**
