### PR TITLE
cilium: various xdp related follow-ups

### PR DESCRIPTION
**Pull request by borkmann**
- cilium status output
- CI tests
- Hide generic XDP for testing only

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
unrelated vagrant issue:
```
 97 9861M   97 9609M    0     0   100M      0  0:01:38  0:01:35  0:00:03  112M
 98 9861M   98 9721M    0     0   100M      0  0:01:37  0:01:36  0:00:01  112M
 99 9861M   99 9833M    0     0   100M      0  0:01:37  0:01:37 --:--:--  112M
100 9861M  100 9861M    0     0   100M      0  0:01:37  0:01:37 --:--:--  112M
11:27:23  The machine index which stores all required information about
11:27:23  running Vagrant environments has become corrupt. This is usually
11:27:23  caused by external tampering of the Vagrant data folder.
11:27:23  
11:27:23  Vagrant cannot manage any Vagrant environments if the index is
11:27:23  corrupt. Please attempt to manually correct it. If you are unable
11:27:23  to manually correct it, then remove the data file at the path below.
11:27:23  This will leave all existing Vagrant environments "orphaned" and
11:27:23  they'll have to be destroyed manually.
11:27:23  
11:27:23  Path: /root/.vagrant.d/data/machine-index/index
11:27:24  box locked or unavailable, adding box from vagrant cloud
11:27:25  The machine index which stores all required information about
11:27:25  running Vagrant environments has become corrupt. This is usually
11:27:25  caused by external tampering of the Vagrant data folder.
11:27:25  
11:27:25  Vagrant cannot manage any Vagrant environments if the index is
11:27:25  corrupt. Please attempt to manually correct it. If you are unable
11:27:25  to manually correct it, then remove the data file at the path below.
11:27:25  This will leave all existing Vagrant environments "orphaned" and
11:27:25  they'll have to be destroyed manually.
11:27:25  
11:27:25  Path: /root/.vagrant.d/data/machine-index/index
Post stage
```

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
provisioning issue again:
```
[Pipeline] sh
12:37:23  + /usr/local/bin/add_vagrant_box /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/vagrant_box_defaults.rb
12:37:23  The machine index which stores all required information about
12:37:23  running Vagrant environments has become corrupt. This is usually
12:37:23  caused by external tampering of the Vagrant data folder.
12:37:23  [...]
```

**Comment by borkmann** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Comment by borkmann** [comment]
Hit flake #10821

**Comment by borkmann** [comment]
test-focus K8sService.*

**Comment by borkmann** [comment]
test-focus K8sService.*

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Hit flake #10821

**Comment by borkmann** [comment]
test-focus K8sService.*

**Comment by borkmann** [comment]
Cilium-Tests-With-Kernel provision issue
```
20:45:04  Checking for older boxes...
20:45:04  No old versions of boxes to remove...
20:45:04  VBoxManage: error: Machine '9c85c1b7-53ab-4012-837a-749c5acf0af8' is not currently running
20:45:04  0%...10%...20%...30%...40%...
20:45:04  Progress state: VBOX_E_OBJECT_IN_USE
20:45:04  VBoxManage: error: Machine delete failed
20:45:04  VBoxManage: error: Cannot close medium '/root/VirtualBox VMs/ubuntu-18.04.4-amd64-11_1586464889876_63179/ubuntu-18.04.4-amd64-11-disk001.vmdk' because it has 1 child media
20:45:04  VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component MediumWrap, interface IMedium
20:45:04  VBoxManage: error: Context: "RTEXITCODE handleUnregisterVM(HandlerArg*)" at line 162 of file VBoxManageMisc.cpp
20:45:04  VBoxManage: error: Machine 'ab8f39a8-4e2d-4dc1-bb3e-da306b749f17' is not currently running
20:45:06  0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
20:45:06  Clean docker images from registry
```

**Comment by borkmann** [comment]
test-with-kernel

**Comment by borkmann** [comment]
test-focus K8sService.*

**Comment by borkmann** [comment]
vagrant issue again in CI...

**Comment by borkmann** [comment]
test-focus K8sService.*

**Comment by borkmann** [comment]
test-focus K8sService.*

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
vbox error in CI:
```
00:31:39  Stderr: VBoxManage: error: Failed to create the VirtualBox object!
00:31:39  VBoxManage: error: Document is empty.
00:31:39  VBoxManage: error: Location: '/root/.config/VirtualBox/VirtualBox.xml', line 1 (0), column 1.
00:31:39  VBoxManage: error: /home/vbox/vbox-6.0.18/src/VBox/Main/src-server/VirtualBoxImpl.cpp[624] (nsresult VirtualBox::init())
00:31:39  VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component VirtualBoxWrap, interface IVirtualBox
00:31:39  script returned exit code 143
```

**Comment by borkmann** [comment]
test-me-please

**Comment by joestringer** [comment]
Hit #10929 and #10930, will restart ginkgo.

**Comment by joestringer** [comment]
restart-ginkgo

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-focus K8sService.*

**Comment by christarazi** [comment]
Backported only 7d1a16f08c253add72ca3f4a13f86de9869c64ca to v1.7 (PR: https://github.com/cilium/cilium/pull/13595) as https://github.com/cilium/cilium/pull/13532 depended on this commit.

**Pull request merged**
