### PR TITLE
Endpoint populate new policymap early if empty

### PR DESCRIPTION
**Pull request by jrajahalme**
Sync endpoint bpf policy map before bpf compilation, if the bpf policy
map is empty.

The bpf policy map is empty if it was (re)created for the endpoint. This
can happen in the following situations:

- endpoint is new, so no policy map existed yet
- policy map was upgraded to a new spec or name

In the first case it does not really matter when the policy map is
synced, but in the latter case the new endpoint programs would start with
an empty policy map, which could disrupt existing connections. In this
case it is better to populate the policy map before the bpf program
creation so that when the endpoint starts using the new program if can
use an up-to-date policy map rather than an empty one.

Normally we'd want to sync the policy map only after it is known that the
bpf compilation did not fail.

Rename the 1.17 endpoint policy map to make use of the above.

### CODE REVIEW

**Review by joestringer — APPROVED** [review]
LGTM.

**Review by nathanjsweet — APPROVED** [review]

**Review by bimmlerd — APPROVED** [review]
LGTM (only for `contributing`)

**Review by rgo3 — APPROVED** [review]

**Pull request merged**
