### PR TITLE
identity: Eliminate unit test raciness

### LINKED ISSUE #8049: Unit test failure in allocator test
```
FAIL: <autogenerated>:1: IdentityAllocatorEtcdSuite.TestLocalAllocationr
allocation_test.go:349:
    // KV-store still holds on to the key, so it is not deleted yet via KV-store events
    // This may be racy, as timing here depends on scheduling.
    c.Assert(owner.GetIdentity(id.ID), checker.DeepEquals, lbls1.LabelArray())
... obtained labels.LabelArray = labels.LabelArray(nil) ("[]")
... expected labels.LabelArray = labels.LabelArray{labels.Label{Key:"192.0.2.3/32", Value:"", Source:"cidr"}} ("[cidr:192.0.2.3/32]")
... Unified diff:
--- obtained
+++ expected
@@ -1 +1,3 @@
-labels.LabelArray(nil)
+labels.LabelArray{
+    {Key:"192.0.2.3/32", Value:"", Source:"cidr"},
+}
```

Observed in https://github.com/cilium/cilium/pull/8047

### PR DESCRIPTION
**Pull request by jrajahalme**
Make the unit test not depend on scheduling/timing by explicitly
waiting for identity update events to occur.

Fixes: #8049
Fixes: 21f462c5ebf ("policy: Add selector cache")
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8055)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
CI issue #8056

**Comment by jrajahalme** [comment]
This PR only touches a go unit test file, and Travis CI passed with it. Not sure if running Ginkgo tests makes sense - I'd be happy to merge as is.

**Comment by jrajahalme** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Pull request merged**
