### PR TITLE
v1.13 Backports 2023-04-03

### PR DESCRIPTION
**Pull request by jibi**
* [x] #24034 (@jibi)
 * [x] #23935 (@jschwinger233)
  * only backporting c08189cfb1ec as a dependency of #24309
 * [x] #24575 (@mhofstetter)
 * [x] #24484 (@jschwinger233)
 * [x] #24619 (@giorio94)
 * [x] #24506 (@ti-mo)
 * [x] #24309 (@chenyuezhou)
 * [x] #24645 (@tklauser)
  * skipping as the commit it fixes has been reverted in master
 * [x] #24497 (@ferozsalam)
 * [x] #24646 (@MrFreezeex)
 * [x] #24538 (@ti-mo)
  * only backporting 072968feb415 on author's request

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 24034 23935 24575 24484 24619 24506 24309 24497 24646 24538; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=24034,23935,24575,24484,24619,24506,24309,24497,24646,24538
```

see individual commits for list of conflicts

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
My PR looks good. Thanks!

**Review by mhofstetter — APPROVED** [review]

**Comment by jibi** [comment]
/test-backport-1.13

**Review by MrFreezeex — APPROVED** [review]

**Review by jschwinger233 — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
> https://github.com/cilium/cilium/pull/24309 (@chenyuezhou)

I reviewed the backport for that PR and it looks good to me. Thanks!

**Review by ferozsalam — APPROVED** [review]

**Comment by jibi** [comment]
* reviewed @ti-mo commits as they are small and without conflicts
* `test-1.24-4.9` is failing due to a known flake, https://github.com/cilium/cilium/pull/24723 should help with that once merged
* `ingress-conformance-test` is [passing](https://github.com/cilium/cilium/actions/runs/4598123223/jobs/8121747084?pr=24706) although for some reason it failed to report the state

Marking as ready

**Pull request merged**
