### PR TITLE
policy: clean a duplicated code

### PR DESCRIPTION
**Pull request by zhiyuan0x**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10016)

### CODE REVIEW

**Review by aanm — APPROVED** [review]
Thanks for the changes!

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
