### PR TITLE
v1.16 Backports 2024-11-21

### PR DESCRIPTION
**Pull request by pippolo84**
* [x] #35144 (@pippolo84)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 35144
```

### CODE REVIEW

**Comment by pippolo84** [comment]
/test-backport-1.16

**Review by christarazi — APPROVED** [review]

**Comment by asauber** [comment]
This is hitting https://github.com/cilium/cilium/issues/36086 in CI

**Comment by pippolo84** [comment]
The only (required) test failing (ci-ipsec-upgrade) is hitting https://github.com/cilium/cilium/issues/36086, so marking this ready to merge.

**Comment by julianwiedmann** [comment]
I think the right call here is rebasing to pick up the fix, and re-run CI.

**Comment by julianwiedmann** [comment]
/test-backport-1.16

**Comment by julianwiedmann** [comment]
/test-backport-1.16

**Pull request merged**
