### PR TITLE
Change k8s test versions

### PR DESCRIPTION
**Pull request by aanm**
**Summary of changes**:

Change kubernetes test versions.

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-all-ginkgo

**Comment by eloycoto** [comment]
test-all-ginkgo

**Comment by ianvernon** [comment]
Similar issue to https://github.com/cilium/cilium/pull/3303#issuecomment-376217120 .

**Review by eloycoto — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
@eloycoto it looks like kubernetes 1.10 was not released as a pkg yet. Let's wait a couple hours until it happens

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
@aanm kubernetes 1.10 is already in the repo, I've just trigger the build ;-)

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
