### PR TITLE
Update k8s dependencies to 1.10.beta.3

### PR DESCRIPTION
**Pull request by aanm**
**Summary of changes**:

- Update kuberentes dependencies to 1.10.beta.3
- Bump k8s 1.10 tests to 1.10.beta.3
- regenerated code of kubernetes/code-generator with 1.10.beta.3
- update development requirement docs to kubernetes/code-generator 1.10.beta.3

### CODE REVIEW

**Comment by aanm** [comment]
test-m-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Should we be updating to beta versions of dependencies in master?

**Comment by aanm** [comment]
>Should we be updating to beta versions of dependencies in master?

What you mean?

**Comment by ianvernon** [comment]
> What you mean?

The dependencies are marked with the 'beta' tag - shouldn't we wait until v1.10 of the dependencies is officially released before consuming it ourselves.

**Comment by aanm** [comment]
>The dependencies are marked with the 'beta' tag - shouldn't we wait until v1.10 of the dependencies is officially released before consuming it ourselves.

We are going to code freeze this week so it's better to test it first before jumping to `v1.10` ourselfs

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
all tests have passed including k8s

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
