### PR TITLE
loader: do not invoke llc separately

### PR DESCRIPTION
**Pull request by lmb**
loader: do not invoke llc separately

    Historically it wasn't possible to pass -mcpu and -mattr flags to clang so
    compilation proceeded in two steps: first invoking clang to emit llvm
    bytecode and feeding that into llc. This has the downside of having to
    manage two processes and incurs overhead to marshal and unmarshal llvm
    bytecode.

    Crucially, the compile path does not always invoke llc. Outputting 
    preprocessed source code for debugging purposes has a special short circuit.

    Replace this logic with a single invocation of clang for all supported 
    output types. This makes the compilation logic easier to understand and 
    opens it up for further refactoring.

    Signed-off-by: Lorenz Bauer <lmb@isovalent.com>

### CODE REVIEW

**Comment by lmb** [comment]
ci-external-workloads hit https://github.com/cilium/cilium/issues/29312

**Review by rgo3 — CHANGES_REQUESTED** [review]
A couple general questions:
1. The [test/bpf/Makefile](https://github.com/cilium/cilium/blob/a83864769e81fbe2e7dd00dc2782a8c50c001fb2/test/bpf/Makefile) and [bpf/Makefile](https://github.com/cilium/cilium/blob/a83864769e81fbe2e7dd00dc2782a8c50c001fb2/bpf/Makefile) still invoke `llc` separately, should we make the same changes there as proposed here to keep those Makefiles in sync with how we compile at runtime?
2.  https://github.com/cilium/cilium/blob/a83864769e81fbe2e7dd00dc2782a8c50c001fb2/pkg/datapath/linux/requirements.go#L108 and https://github.com/cilium/cilium/blob/a83864769e81fbe2e7dd00dc2782a8c50c001fb2/tools/dev-doctor/rootcmd.go#L159 still check for `llc` being available, is that still necessary if we remove its direct usage?

**Comment by lmb** [comment]
Good point re the Go code. I'll split the Makefile changes into a separate PR to keep reviews easier.

**Pull request closed without merging**
