### PR TITLE
replace jteeuwen/go-bindata with cilium/go-bindata

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

```release-note
Replace jteeuwen/go-bindata with cilium/go-bindata hard fork
```

### CODE REVIEW

**Review by raybejjani — APPROVED** [review]

**Comment by eloycoto** [comment]
test-me-plesae

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-plesae

**Comment by aanm** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
