### PR TITLE
bug: upgraded Azure API version 

### LINKED ISSUE #23083: Migrate Azure APIs prior to Sep 30 2023
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[Azure announced](https://azure.microsoft.com/en-us/updates/api-versions-being-retired-for-azure-api-management/) API versions older than 2021-08-01 will fail after 2023-09-30.

Cilium is currently using [Network API 2020-11-01](https://github.com/cilium/cilium/blob/13cdd07a70ffd21df3cc043a7c24334985c11286/pkg/azure/api/api.go#L14) and [Compute API 2021-03-01](https://github.com/cilium/cilium/blob/13cdd07a70ffd21df3cc043a7c24334985c11286/pkg/azure/api/api.go#LL13C59-L13C69), both of which will be affected. These will need to be upgraded prior to Sep 30.

### Cilium Version

n/a

### Kernel Version

n/a

### Kubernetes Version

n/a

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by goverdhan07**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Fixes: #23083

- Upgraded Azure API version to 1st august 2021 in order to save it from retiring.
- details [here](https://azure.microsoft.com/en-us/updates/api-versions-being-retired-for-azure-api-management/)

Signed-off-by: Goverdhan Biradar [goverdhanbiradar@gmail.com](mailto:goverdhanbiradar@gmail.com)

### CODE REVIEW

**Comment by tommyp1ckles** [comment]
thanks, change makes sense. Can you squash the two commits together?

**Comment by joestringer** [comment]
@goverdhan07 The bot doesn't recognize the current format for your sign-off line. I would suggest either using `git commit -s` and/or make sure that the email address is wrapped in angle brackets (eg `<foo@bar.com>`). Additionally, please rebase + squash the commits together. Cilium doesn't take merge commits into the tree.

**Review by tommyp1ckles — APPROVED** [review]

**Comment by pchaigno** [comment]
Switching to draft given missing sign off from last week.

**Comment by joestringer** [comment]
@goverdhan07 I would suggest using a [rebase + squash approach](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) and update the commit message to address the DCO requirement as the maintainer's little helper is suggesting above.

**Comment by christarazi** [comment]
Closing in favor of https://github.com/cilium/cilium/pull/28311

**Pull request closed without merging**
