### PR TITLE
v1.12 Backports 2023-06-12

### PR DESCRIPTION
**Pull request by gandro**
* [x] #25953 (@pchaigno)
 * [x] #26072 (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 25953 26072; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=25953,26072
```

### CODE REVIEW

**Comment by gandro** [comment]
/test-backport-1.12

**Review by qmonnet — APPROVED** [review]

**Comment by qmonnet** [comment]
[Cilium L4LB XDP failed](https://github.com/cilium/cilium/actions/runs/5244140295/jobs/9469745041) with an error that I couldn't associate to any known flake, but I don't believe the failing test involved IPsec in any way so I think it's unrelated. I'll file an issue and re-trigger the test.

**Comment by qmonnet** [comment]
/ci-l4lb-1.12

**Review by pchaigno — APPROVED** [review]
My PRs look good. Thanks Sebastian!

**Pull request merged**
