### PR TITLE
v1.5 backports 2019-06-21

### PR DESCRIPTION
**Pull request by joestringer**
* #8328 -- fqdn: correctly populate Source IP and Port in `notifyOnDNSMsg` (@ianvernon)
   * Had to make minor fixups because the function was refactored out
 * #8350 -- CI: Report last seen error in CiliumPreFlightCheck (@raybejjani)
 * #8352 -- CI: Cleanup VMs and reclaim disk on job completion (@raybejjani)
 * #8361 -- pkg/metrics: re-register newStatusCollector function (@aanm)
 * #8366 -- docs: Clarify about legacy services enabled by default (@brb)

[ Round 2, added CI fixes]
 * #7911 
    * This was partially backported before in f7a1bd149a40f237850c91baa9b6987de6c67061, so I went back and backported the other half.
 * #8148
 * #8341 
 * #8355 

Skipped:
* Changes that require vendor updates
   * @aanm how do you update vendor dependencies during backport ? I get errors[1]
   * https://github.com/cilium/cilium/pull/8280 -- Add support for k8s 1.15 (@aanm)
   * https://github.com/cilium/cilium/pull/8351 -- Workaround for systemd 242 assigning MAC addr for virtual devices (@brb)

[1]
```
$ dep ensure
Solving failure: No versions of github.com/go-openapi/spec met constraints:
        v0.18.0: Could not introduce github.com/go-openapi/spec@v0.18.0, as it requires github.com/go-openapi/jsonpointer at revision v0.18.0, but that revision does not exist         
        v0.19.2: Could not introduce github.com/go-openapi/spec@v0.19.2, as it is not allowed by constraint v0.18.0 from project github.com/cilium/cilium.                              
        v0.19.0: Could not introduce github.com/go-openapi/spec@v0.19.0, as it is not allowed by constraint v0.18.0 from project github.com/cilium/cilium.                              
        v0.18.0: Could not introduce github.com/go-openapi/spec@v0.18.0, as it is not allowed by constraint v0.18.0 from project github.com/cilium/cilium.                              
        v0.17.2: Could not introduce github.com/go-openapi/spec@v0.17.2, as it is not allowed by constraint v0.18.0 from project github.com/cilium/cilium.                              
        v0.17.1: Could not introduce github.com/go-openapi/spec@v0.17.1, as it is not allowed by constraint v0.18.0 from project github.com/cilium/cilium.                              
        v0.17.0: Could not introduce github.com/go-openapi/spec@v0.17.0, as it is not allowed by constraint v0.18.0 from project github.com/cilium/cilium.                              
        0.16.0: Could not introduce github.com/go-openapi/spec@0.16.0, as it is not allowed by constraint v0.18.0 from project github.com/cilium/cilium.                                
        0.15.0: Could not introduce github.com/go-openapi/spec@0.15.0, as it is not allowed by constraint v0.18.0 from project github.com/cilium/cilium.                                
        master: Could not introduce github.com/go-openapi/spec@master, as it is not allowed by constraint v0.18.0 from project github.com/cilium/cilium.                                
        fix-definitions-omitempty: Could not introduce github.com/go-openapi/spec@fix-definitions-omitempty, as it is not allowed by constraint v0.18.0 from project github.com/cilium/cilium.
        fixSpelling: Could not introduce github.com/go-openapi/spec@fixSpelling, as it is not allowed by constraint v0.18.0 from project github.com/cilium/cilium.                      
        revert-79-fix-circular: Could not introduce github.com/go-openapi/spec@revert-79-fix-circular, as it is not allowed by constraint v0.18.0 from project github.com/cilium/cilium.
        transitiveResolverLocalRefCheck: Could not introduce github.com/go-openapi/spec@transitiveResolverLocalRefCheck, as it is not allowed by constraint v0.18.0 from project github.com/cilium/cilium.
```

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 7911 8148 8328 8341 8350 8352 8355 8361 8366; do contrib/backporting/set-labels.py $pr done 1.5; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8369)

### CODE REVIEW

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
@joestringer I've pushed pr/v1.5-backport-2019-06-21-2 that contains PRs #8280 and #8351 backported.

I had to backported only the file `Gopkg.toml` for the kubernetes changes and then ran `dep ensure -v`

**Comment by brb** [comment]
>  I've pushed pr/v1.5-backport-2019-06-21-2 that contains PRs #8280 and #8351 backported.

Are we OK to close this PR and open for `pr/v1.5-backport-2019-06-21-2`?

**Comment by joestringer** [comment]
test-me-please

**Comment by brb** [comment]
Superseded by #8381.

**Comment by brb** [comment]
Reopening to get the CI run results.

**Pull request closed without merging**
