### PR TITLE
[v1.15] Replaced declare_tailcall_if with logic in the loader 

### PR DESCRIPTION
**Pull request by ti-mo**
* [x] #30467 (@dylandreimerink)
 * [x] #31419 (@mhofstetter)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30467 31419
```

### CODE REVIEW

**Comment by ti-mo** [comment]
/test-backport-1.15

**Comment by dylandreimerink** [comment]
We might also want to include https://github.com/cilium/cilium/pull/31419 where the CI contrib script got fixed which included an issue in my initial PR

**Review by dylandreimerink — APPROVED** [review]

**Comment by ti-mo** [comment]
/test-backport-1.15

**Review by mhofstetter — APPROVED** [review]

**Comment by ti-mo** [comment]
/test-backport-1.15

**Review by squeed — APPROVED** [review]

**Pull request merged**
