### PR TITLE
Backport 1.3/fqdn fixl3 wildcard

### PR DESCRIPTION
**Pull request by raybejjani**
Backport for https://github.com/cilium/cilium/pull/6326

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6378)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-docs-please

**Comment by raybejjani** [comment]
test-missed-k8s

**Comment by raybejjani** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
