### PR TITLE
[v1.13] docs: Ignore Helm values, update spelling list

### PR DESCRIPTION
**Pull request by qmonnet**
- [x] #26759 (@qmonnet)
- [x] https://github.com/cilium/cilium/pull/24099 (@qmonnet)
- [x] https://github.com/cilium/cilium/pull/23752 (@squeed)
- [x] https://github.com/cilium/cilium/pull/24014 (@qmonnet)
- [x] https://github.com/cilium/cilium/pull/26892 (@geakstr)

\+ Partial backport for the following PRs (not labelled as backported, since we backport only a minor portion of the changes):

- [ ] https://github.com/cilium/cilium/pull/24895 (@tklauser)
- [ ] https://github.com/cilium/cilium/pull/24717 (@joestringer)

Cc @gandro 

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 26759 24099 23752 24014 26892; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=26759,24099,23752,24014,26892
```

### CODE REVIEW

**Comment by qmonnet** [comment]
Hmmm. I'm also getting the errors Sebastian reported:

```
ERROR: Unknown interpreted text role "spelling:ignore".
```

These are _not_ because we omitted to ignore the `spelling:ignore` role for rstcheck, as I previously believed. This is because we use `sphinxcontrib-spelling` v7.6.0, as per `Documentation/requirements.txt` (and _not_ v7.7.0 as specified in `Documentation/requirements-min/requirements.txt`, [because of Dependabot](https://github.com/cilium/cilium/pull/22159)). But the role we're trying to use was only [added in v7.7.0](https://github.com/sphinx-contrib/spelling/blob/main/docs/source/history.rst#770), so in our case the CI legitimately complains that it doesn't know it.

I see two ways forward:

- Drop backports for <= 1.13 for this PR, the easiest thing to do, even though we'll have to manually re-generate the Helm reference each time we backport something touching Helm values for 1.11, 1.12, 1.13.
- Backport anyway, meaning we also have to update the version of the Sphinx plug-in. But re-building the `docs-builder` image locally fails for me on 1.13, so I guess we'd also have to backport a bunch of other commits (0b93dcc0290fafbe61ebe3cab6654ea933ebe4c7, and likely everything related to it); then generate a new `docs-builder` image for CI for 1.13; then update 1.13 to use that.

I've not much appetite for the second solution - I don't mind spending time on improving the docs framework on `main`, but collecting all required commits and dependencies to make sure that this works on 1.11--1.13 will likely be painful, so my preference would be to just drop these backports.

**Comment by gandro** [comment]
I've found that it's already often necessary to regenerate the Helm values and README on stable branches, even before this commit. So I'm fine with not backporting it. 

But I think it would be helpful to have a guide somewhere that explains to backporters what conflicts they have to expect due to this change, and an short guide on what and how to regenerate.

**Comment by qmonnet** [comment]
/test-backport-1.13

**Review by geakstr — APPROVED** [review]

**Review by squeed — APPROVED** [review]

**Review by viktor-kurchenko — APPROVED** [review]

**Comment by qmonnet** [comment]
/test-1.21-4.19

**Review by nbusseneau — APPROVED** [review]

**Comment by youngnick** [comment]
Hey @qmonnet seems like there's now a conflict on `helm-values.rst`?

**Comment by qmonnet** [comment]
There was, I fixed it.

**Review by nbusseneau — APPROVED** [review]

**Comment by nbusseneau** [comment]
This PR only makes changes to the documentation and Helm values, both checks have passed, no need to run full CI for the rebase. Marking `ready-to-merge`.

**Review by youngnick — APPROVED** [review]

**Comment by youngnick** [comment]
Looks like the release activity is really messing with this one @qmonnet, another conflict in helm-values. Feels like timezones may make this tricky, please feel free to ping me on Slack when you are ready to push the conflict fix and if I'm up, I'll merge asap after that.

**Comment by qmonnet** [comment]
> Looks like the release activity is really messing with this one @qmonnet, another conflict in helm-values.

Yeah, there's one commit here that changes _all_ entries in the Helm reference, so as soon as we backport some other change touching that file there's a conflict.

This is also why we want to backport this change, in fact: otherwise, all backports from `main` to 1.13 touching Helm values will need to regenerate the Helm reference. Anyway... at least it's trivial to rebase, easier than the conflict on the spelling exceptions from yesterday.

> please feel free to ping me on Slack when you are ready to push the conflict fix

Sure, will do. We should be good if the Documentation workflow and integration tests pass.

**Comment by qmonnet** [comment]
Looks all in order :rocket:

**Pull request merged**
