### PR TITLE
Correctly change Kafka policy filenames to lower case

### PR DESCRIPTION
**Pull request by manalibhutiyani**
Fixes: #3241
Signed-Off-by: Manali Bhutiyani <manali@covalent.io>

```release-note
Correctly change Kafka policy filenames to lower case
```

### CODE REVIEW

**Comment by manalibhutiyani** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Thanks, looks like this should fix the issue I reported.

I'm not sure whether this needs to be labelled as a fixed bug, the related documentation has only briefly been merged anyway so it's unlikely anyone will notice documentation path changes.

**Review by rlenglet — APPROVED** [review]

**Comment by rlenglet** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
not sure what this error is :                                                                                                              ```19:54:05 make[1]: go-bindata: Command not found
19:54:05 Makefile:54: recipe for target 'go-bindata' failed
19:54:05 make[1]: *** [go-bindata] Error 127
19:54:05 make[1]: Leaving directory '/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/daemon'
19:54:05 Makefile:26: recipe for target 'tests-ginkgo' failed
19:54:05 make: *** [tests-ginkgo] Error 2```

**Comment by manalibhutiyani** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
test-me-please

**Pull request merged**
