### PR TITLE
v1.5: backports 19-07-03

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:

 * PR: 8402 -- pkg/kvstore: fix nil pointer in error while doing a transaction in etcd  (@aanm) -- https://github.com/cilium/cilium/pull/8402
 * PR: 8408 -- operator: add warning message if status returns an error (@aanm) -- https://github.com/cilium/cilium/pull/8408
 * PR: 8416 -- maps/lbmap: protect service cache refcount with concurrent access (@aanm) -- https://github.com/cilium/cilium/pull/8416
 * PR: 8417 -- pkg/k8s: do not parse empty annotations (@aanm) -- https://github.com/cilium/cilium/pull/8417
 * PR: 8427 -- pkg/kvstore: add etcd lease information into cilium status (@aanm) -- https://github.com/cilium/cilium/pull/8427
 * PR: 8388 -- daemon: Change loglevel of "ipcache entry owned by kvstore or agent" (@brb) -- https://github.com/cilium/cilium/pull/8388
 * PR: 8444 -- test: set 1.15 by default in CI Vagrantfile (@aanm) -- https://github.com/cilium/cilium/pull/8444
 * PR: 8443 -- Change nightly CI job label from fixed to baremetal (@nebril) -- https://github.com/cilium/cilium/pull/8443
 * PR: 8453 -- pkg/k8s: hold mutex while adding events to the queue (@aanm) -- https://github.com/cilium/cilium/pull/8453
 * PR: 8462 -- Retry provisioning vagrant vms in CI (@nebril) -- https://github.com/cilium/cilium/pull/8462
 * PR: 8449 -- cli: fix panic in cilium bpf sha get command (@fristonio) -- https://github.com/cilium/cilium/pull/8449

When you have backported the above commits, you can update the PR labels via this command:
```
$ for pr in 8402 8408 8416 8417 8427 8388 8444 8443 8453 8462 8449; do contrib/backporting/set-labels.py $pr pending 1.5; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8465)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by brb** [comment]
Will re-run the failed tests once the CI provisioning errors have been fixed.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Normal Gingko tests failed in a variety of ways: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13466/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Upstream K8s tests failed due to provisioning error: https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/1385/execution/node/42/log/

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
Runtime egress policy tests are failing? https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13479/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
I reverted the Envoy log reduction commits and the L3-dependent L7 egress tests started passing. Given that this is not a critical bugfix for v1.5, I removed it from this PR.

**Comment by ianvernon** [comment]
Cilium-Ginkgo-Tests failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13489/testReport/junit/Suite-k8s-1/15/K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter_service_connectivity/

Istio pods couldn't get ready. Investigating while triggering build again.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Cilium-Ginkgo-Tests-K8s failed as well: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2268/

* FQDN restart test failed (this is a known issue - https://github.com/cilium/cilium/issues/8234 .
* Istio test failed too - it looks like kube-apiserver and kube-scheduler restarted, which is cause for concern (and hopefully unrelated to Cilium!). 

Will triage, and yet again, I am trying again!

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
K8s tests failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2270/

Pod got stuck in `ContainerCreating` state:

```
2019-07-09T17:40:49.196188634Z level=warning msg="Error changing endpoint identity" containerID=9f429b53af datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3767 error="unable to resolve identity: key allocation cancelled: context canceled" identityLabels="k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=default,k8s:zgroup=testDSClient" ipv4=10.10.1.57 ipv6= k8sPodName=default/testclient-sm9jn subsys=endpoint
```

Identity could not be resolved for the endpoint. This might be due to etcd-operator connectivity being disrupted :(

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
I've given up on the upstream K8s tests, they appear to be broken in the provisioning stages.

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
