### PR TITLE
Vagrant: making a more modular vagrant file

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins andre@cilium.io

### CODE REVIEW

**Comment by aanm** [comment]
@tgraf I've test out provider virtualbox with nfs. Can you try things with libvirt with 1 node? I'm going to test out the k8s + virtualbox.

**Comment by aanm** [comment]
@tgraf Also I'm seeing this:

```
11: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether e2:48:0c:89:cb:cb brd ff:ff:ff:ff:ff:ff
    inet 10.11.0.1/32 scope global cilium_host
       valid_lft forever preferred_lft forever
    inet 10.1.0.1/32 scope global cilium_host
       valid_lft forever preferred_lft forever
    inet6 f00d::c0a8:210b:ffff/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::e048:cff:fe89:cbcb/64 scope link 
       valid_lft forever preferred_lft forever
```

do you know where the `10.11.0.1/32` comes from?

**Comment by tgraf** [comment]
@aanm:

```
$ ./contrib/vagrant/start.sh 2
[...]
==> cilium-master: Running provisioner: shell...
    cilium-master: Running: /tmp/vagrant-shell20160810-1315-ytp9pc.sh
==> cilium-master: stdin: is not a tty
==> cilium-master: cilium-net-daemon stop/waiting
==> cilium-master: cilium-net-daemon start/running, process 19220
==> cilium-master: Running provisioner: load-policy (shell)...
    cilium-master: Running: inline script
There are errors in the configuration of this machine. Please fix
the following errors and try again:

shell provisioner:
* `path` for shell provisioner does not exist on the host system: /home/tgraf/dev/go/src/github.com/noironetworks/cilium-net/contrib/vagrant/node-start-0.sh
```

**Comment by tgraf** [comment]
Only thing that's left is to adapt `tests/manual-multi-node.bash`

**Comment by aanm** [comment]
Okay, I'll take a look at that ;-)

**Comment by aanm** [comment]
@tgraf I've adjusted the `manual-multi-node.bash` while I was running that file I got this error:

```
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 0.575/0.814/1.094 ms
Connection to 127.0.0.1 closed.
MIGRATED TCP STREAM TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 10.1.28.238 (10.1.28) port 0 AF_INET
recv_response_timed_n: no response received. errno 28 counter 0
Connection to 127.0.0.1 closed.
server
Connection to 127.0.0.1 closed.
client
Connection to 127.0.0.1 closed.
```

**Comment by tgraf** [comment]
@aanm Do you get the error sporadically or for every run?

**Comment by aanm** [comment]
@tgraf I try that once and saw that error, should I test it again?

**Comment by tgraf** [comment]
I saw that error a couple of times and it always boiled down to the vagrant boxes not being able to talk to each other over IPv4. I haven't tracked down to exactly why that is the case.

I assume you are seeing the error in the VXLAN test case. The native test case _will_ fail of course because we can't transmit the security context across nodes.

**Pull request merged**
