### PR TITLE
Remove unnecessary imports of pkg/policy

### PR DESCRIPTION
**Pull request by jrajahalme**
Remove imports of `pkg/policy` from `pkg/ipcache` and `pkg/hubble/parser/getters` to allow `pkg/policy` to do more imports in future.

### CODE REVIEW

**Review by kaworu — APPROVED** [review]
Hubble related changes LGTM, thanks for the cleanup @jrajahalme!

**Review by tklauser — APPROVED** [review]

**Comment by tklauser** [comment]
@jrajahalme it looks like this branch picked up a merge conflict and needs a rebase.

**Review by nathanjsweet — APPROVED** [review]

**Review by aditighag — APPROVED** [review]

**Review by tommyp1ckles — APPROVED** [review]

**Comment by jrajahalme** [comment]
Rebased to address merge conflicts in unit test imports (x2).

**Comment by jrajahalme** [comment]
Added missing 2nd commit removing unused interface that caused unnecessary imports.

**Review by nebril — APPROVED** [review]

**Pull request merged**
