### PR TITLE
v1.7 backports 2020-04-14

### PR DESCRIPTION
**Pull request by nebril**
* #10634 -- Run tests on 4.19 kernel (@nebril)
 * #10722 -- ci: bump 4.19 image version (@nebril)
 * #10916 -- ci: increase vm memory in kernel specific build (@nebril)
 * #10920 -- Clarify CRI-O installation (@aanm)
 * #10851 -- istio: Use cilium-istioctl instead of helm directly (@jrajahalme)
 * #10932 -- ci: fix argument retrieval script for kernel specific builds on master (@nebril)
 * #10853 -- expand 1.7.x upgrade guide on enable-remote-node-identity (@danwent)
 * #10923 -- k8s/identitybackend: log error if AcquireReference fails (@aanm)
 * #10685 -- Fix node ip script path 

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10634 10722 10916 10920 10851 10932 10853 10923 10685; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
LGTM for my changes

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
twst-with-kernel

**Comment by nebril** [comment]
test-with-kernel

**Comment by joestringer** [comment]
test-with-kernel

**Comment by joestringer** [comment]
Thanks @nebril for investigating the potential upgrade impact via #11035. Looks like that issue was always present on the current v1.7 branch so this PR doesn't change anything. I'll run the docs target and merge.

**Comment by joestringer** [comment]
test-docs-please

**Pull request merged**
