### PR TITLE
init.sh: Use 'ip route replace' instead of 'ip route add'

### PR DESCRIPTION
**Pull request by jrajahalme**
Since we no longer delete the old cilium_host/cilium_net veth pair if
they already exist, 'ip route add' will complain of existing
routes. Fix this by using 'ip route replace' instead.

Fixes: #4214 
Fixes: #4254 
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4247)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
LGTM. AFAICT there's no other such reference that might cause similar issues.

**Comment by joestringer** [comment]
Failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3554/testReport/junit/k8s-1/10/K8sValidatedHealthTest_checks_cilium_health_status_between_nodes/

Test output log places time of failure at 22:16:25:

```
 $ grep -B 5 "timestamps=true" test-output.log 
STEP: checking API response for '.nodes[0].host."primary-address".icmp.status'
time="2018-05-24T22:16:25Z" level=debug msg="running command: kubectl exec -n kube-system cilium-6sr85 -- cilium-health status -o json | jq '.nodes[0].host.\"primary-address\".icmp.status'"
cmd: "kubectl exec -n kube-system cilium-6sr85 -- cilium-health status -o json | jq '.nodes[0].host.\"primary-address\".icmp.status'" exitCode: 0 
 "Connection timed out"

time="2018-05-24T22:16:25Z" level=debug msg="running command: kubectl -n kube-system logs --timestamps=true -l k8s-app=cilium --since=30.302624641s --previous"
cmd: "kubectl -n kube-system logs --timestamps=true -l k8s-app=cilium --since=30.302624641s --previous" exitCode: 1 
 Error from server (BadRequest): previous terminated container "cilium-agent" in pod "cilium-6sr85" not found

time="2018-05-24T22:16:25Z" level=debug msg="running command: kubectl -n kube-system logs --timestamps=true -l k8s-app=cilium --since=30.302624641s"
cmd: "kubectl -n kube-system logs --timestamps=true -l k8s-app=cilium --since=30.302624641s" exitCode: 0
```

Cilium-health status seems to show inability to contact anything via ICMP:

(extracted all of the zips/tars)
```
$ cat $(find . -name *health-status*)
```

# cilium-health status

```
Probe time:   2018-05-24T22:16:25Z
Nodes:
  k8s2 (localhost):
    Host connectivity to 192.168.36.12:
      ICMP:          Connection timed out
      HTTP via L3:   OK, RTT=921.295µs
    Endpoint connectivity to 10.15.242.54:
      ICMP:          Connection timed out
      HTTP via L3:   OK, RTT=1.476719ms
  k8s1:
    Host connectivity to 192.168.36.11:
      ICMP:          Connection timed out
      HTTP via L3:   OK, RTT=2.655647ms
    Endpoint connectivity to 10.10.242.54:
      ICMP:          Connection timed out
      HTTP via L3:   OK, RTT=6.550823ms

```
# cilium-health status

```
Probe time:   2018-05-24T22:16:25Z
Nodes:
  k8s1 (localhost):
    Host connectivity to 192.168.36.11:
      ICMP:          Connection timed out
      HTTP via L3:   OK, RTT=179.779µs
    Endpoint connectivity to 10.10.242.54:
      ICMP:          Connection timed out
      HTTP via L3:   OK, RTT=650.721µs
  k8s2:
    Host connectivity to 192.168.36.12:
      ICMP:          Connection timed out
      HTTP via L3:   OK, RTT=827.552µs
    Endpoint connectivity to 10.15.242.54:
      ICMP:          Connection timed out
      HTTP via L3:   OK, RTT=860.705µs

```

[f0c5341e_K8sValidatedHealthTest_checks_cilium-health_status_between_nodes (1).zip](https://github.com/cilium/cilium/files/2037516/f0c5341e_K8sValidatedHealthTest_checks_cilium-health_status_between_nodes.1.zip)

**Comment by ianvernon** [comment]
test-me-please

**Comment by joestringer** [comment]
Weirdly, the pre- and post- endpoint output in the test has a different number of spaces in the `endpoint status` output. I'm working on making this more reliable. Can re-run in the mean time.

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:373
Expected
    <string>: "...     STATUS..."
to equal               |
    <string>: "...      STATU..."
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:35
```

```
time="2018-05-25T05:23:39Z" level=debug msg="running command: cilium endpoint list | grep -v reserved"
cmd: "cilium endpoint list | grep -v reserved" exitCode: 0 
 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6                 IPv4           STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                    
9455       Disabled           Disabled          50848      container:id.client           f00d::a0f:0:0:24ef   10.15.80.185   ready   
40876      Disabled           Disabled          16778      container:id.server           f00d::a0f:0:0:9fac   10.15.117.56   ready   

STEP: original: ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6                 IPv4            STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                     
9455       Disabled           Disabled          50848      container:id.client           f00d::a0f:0:0:24ef   10.15.80.185    ready   
40876      Disabled           Disabled          16778      container:id.server           f00d::a0f:0:0:9fac   10.15.117.56    ready   

STEP: new: ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6                 IPv4           STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                    
9455       Disabled           Disabled          50848      container:id.client           f00d::a0f:0:0:24ef   10.15.80.185   ready   
40876      Disabled           Disabled          16778      container:id.server           f00d::a0f:0:0:9fac   10.15.117.56   ready  
```

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
@joestringer I hit the same issue in a different PR: https://github.com/cilium/cilium/pull/4239

**Pull request merged**
