### PR TITLE
docs: fix small spelling mistakes in masquerading pages

### PR DESCRIPTION
**Pull request by yanhongchang**
docs: fix typo in masquerading documentation, on CIDR mask separator 

Signed-off-by:  hongchang yan <yanhongchang5@163.com>

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]
Thanks a lot!

Can you please add a `Sign-off-by:` tag to your commit description, as explained in the link above?

**Comment by aanm** [comment]
@yanhongchang can you please sign-off your commits? Thank you!

**Comment by nbusseneau** [comment]
@yanhongchang Thanks for your contribution! As noted above, we require the commit description to include sign-offs for proper credit attribution. Can you please amend your commit? We'll be able to merge your PR afterwards 😄

**Comment by yanhongchang** [comment]
> @yanhongchang Thanks for your contribution! As noted above, we require the commit description to include sign-offs for proper credit attribution. Can you please amend your commit? We'll be able to merge your PR afterwards 😄

thanks for your reminding，I have added sign-offs.

**Comment by nbusseneau** [comment]
I don't see the sign-off in the current commit message -- can you check that you pushed your local changes to the remote branch?

**Comment by yanhongchang** [comment]
> I don't see the sign-off in the current commit message -- can you check that you pushed your local changes to the remote branch?

Maybe somewhere is wrong，i reopen a new pull requests，please see https://github.com/cilium/cilium/pull/18338

**Comment by qmonnet** [comment]
Closing in favour of #18338.

**Pull request closed without merging**
