### PR TITLE
CNI chaining plugin API

### PR DESCRIPTION
**Pull request by tgraf**
This is work to prepare for the addition of AWS CNI chaining support. It makes the CNI layer pluggable for arbitrary chaining sub-plugins.

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7839)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Flannel CI test is known to be broken since https://github.com/cilium/cilium/issues/7523#issuecomment-486678275

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
We should wait for #7331 to be fixed first before adding more code.

**Comment by tgraf** [comment]
> We should wait for #7331 to be fixed first before adding more code.

Who is fixing it?

**Comment by aanm** [comment]
> > We should wait for #7331 to be fixed first before adding more code.
> 
> Who is fixing it?

cc @jrajahalme

**Pull request merged**
