### PR TITLE
sysdump: respect worker count and collect Cilium profiling data as first task

### PR DESCRIPTION
**Pull request by giorio94**
The first two commits modify the sysdump collection logic to actually respect the configured worker count, while the third moves again the collection of Cilium profiling data as first task to prevent it from being impacted by the other sysdump collection tasks. Refer to the individual commit messages for additional details.

### CODE REVIEW

**Comment by giorio94** [comment]
Collection of sysdump on a 100 nodes cluster [took](https://github.com/cilium/cilium/actions/runs/11783142726/job/32819685167) ~9 minutes, which is not significantly different from previous runs of the same workflow (~7 minutes), and can be explained by the lower default number of workers.

**Comment by giorio94** [comment]
Rebased onto main to pick CI fixes.

**Review by nathanjsweet — APPROVED** [review]

**Pull request merged**
