### PR TITLE
install/kubernetes: make securityContext SELinux options configurable

### LINKED ISSUE #22703: Make helm SELinux options configurable
We have a lot of SELinux hardcoded in the helm charts, for example [here](https://github.com/cilium/cilium/blob/6462a4b3b6771494c3772e7d2258592c47ac1ddd/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L263-L268). We should make them configurable in all places to allow users to set their own SELinux profiles without requiring them to change the helm chart.

### PR DESCRIPTION
**Pull request by tklauser**
Make the hardcoded SELinux options in the helm charts configurable.

Fixes #22703

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Neat, thanks!

**Review by squeed — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by tklauser** [comment]
* k8s-1.16-kernel-4.9 failed on #22749: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/3451/
* runtime failed on #22750: https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/4296/

Both failures look unrelated to this change. All other tests passed and all code owners approved, marking as ready to merge.

**Pull request merged**
