### PR TITLE
[v1.12] Test upgrade/downgrade to patch release for IPsec

### PR DESCRIPTION
**Pull request by qmonnet**
- [x] #27977 (@michi-covalent)
- [x] #28016 (@jschwinger233)
- [x] #29072 (@brb)
- [x] #28815 (@qmonnet)

Related to
- #14882

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 27977 28016 29072 28815; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=27977,28016,29072,28815
```

### CODE REVIEW

**Comment by qmonnet** [comment]
/test-backport-1.12

**Comment by qmonnet** [comment]
/test-backport-1.12

**Comment by qmonnet** [comment]
/test-1.16-4.9

**Comment by qmonnet** [comment]
/test-1.16-4.9

**Review by michi-covalent — APPROVED** [review]
🥰

**Comment by qmonnet** [comment]
/test-backport-1.12

**Comment by qmonnet** [comment]
/test-1.16-4.9

**Review by brlbil — APPROVED** [review]

**Comment by qmonnet** [comment]
/test-backport-1.12

**Review by brb — APPROVED** [review]
My changes LGTM, thanks.

**Comment by qmonnet** [comment]
/test-backport-1.12

**Comment by qmonnet** [comment]
/test-1.19-4.9

**Review by lmb — APPROVED** [review]
🎩

**Review by pchaigno — APPROVED** [review]
Same as v1.14: it's conflicting so might be worth adding the references to upstream commits while rebasing.

**Comment by aanm** [comment]
@qmonnet needs rebase

**Comment by qmonnet** [comment]
/test-1.18-4.9

**Comment by qmonnet** [comment]
/test-1.19-4.9

**Comment by qmonnet** [comment]
/test-1.22-4.9

**Review by youngnick — APPROVED** [review]

**Pull request merged**
