### PR TITLE
test: Revert "Re-enable microscsope in CI"

### PR DESCRIPTION
**Pull request by ianvernon**
This reverts commit ac4b37c9f450e67c89708a41df77fd4ce727a781.

Signed-off by: Ian Vernon <ian@cilium.io>

Fixes: #4163

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by tgraf** [comment]
What is the problem?

**Comment by ianvernon** [comment]
https://github.com/cilium/cilium/issues/4163 contains the relevant context. Basically, the launched microscope processes are not killed in the Cilium pod: https://github.com/cilium/cilium/issues/4163#issuecomment-390016109

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
cc @nebril

**Pull request merged**
