### PR TITLE
1.4 Backports

### PR DESCRIPTION
**Pull request by tgraf**
* PR: 7021 -- FQDN: Fix on force expired. (@eloycoto) -- https://github.com/cilium/cilium/pull/7021
 * PR: 7019 -- fqdn: Correctly set request/response in DNS monitor events (@raybejjani) -- https://github.com/cilium/cilium/pull/7019
 * PR: 7018 -- docs: Update contributing docs (@brb) -- https://github.com/cilium/cilium/pull/7018

```
$ for pr in 7021 7019 7018; do contrib/backporting/set-labels.py $pr done 1.4; done
```

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7024)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Build failure in both K8s 1.9 and K8s 1.10 tests.

K8s 1.9: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1647/execution/node/55/log/

K8s 1.10: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1647/execution/node/56/log/

Will trigger again. Builds need triage.

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
