### PR TITLE
v1.8 backports 2021-01-06

### PR DESCRIPTION
**Pull request by christarazi**
* #14299 -- Fix rare crash on startup when kubernetes initialization occurs before IP address configuration (@joestringer)
 * #14388 -- test: Add missing gomega Eventually intervals (@jrajahalme)
 * #14447 -- bpf: Fix misaligned access in bpf_xdp with prefilter and IPv6 (@pchaigno)
 * #14513 -- vendor: Update vishvananda/netlink (@pchaigno)
 * #14517 -- docs: Add cgroups kernel config requirements (@joestringer)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14299 14388 14447 14513 14517; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by christarazi** [comment]
test-backport.18

**Comment by christarazi** [comment]
test-backpor-1.8

**Comment by christarazi** [comment]
test-backport-1.8

**Review by pchaigno — APPROVED** [review]
My PRs looks good :+1:

**Comment by christarazi** [comment]
test-backport-1.8

**Comment by christarazi** [comment]
test-backport-1.8

**Comment by christarazi** [comment]
Looks like I get failures with #14299 @joestringer. If I revert it, then the tests go back to passing. Any tips?

**Comment by christarazi** [comment]
test-backport-1.8

**Comment by christarazi** [comment]
Added commit fa09f789b880a0e9eaa66109c75093b2ef514858 to fix the issue seen with @joestringer's PR.

**Review by joestringer — APPROVED** [review]
I'd CC also @jrajahalme in case he had any thoughts/insights on the commit fa09f789b880a0e9eaa66109c75093b2ef514858 . LGTM though.

**Pull request merged**
