### PR TITLE
Improve k8s specific bootstrap behavior

### PR DESCRIPTION
**Pull request by tgraf**
While stress testing while the Kubernetes apiservers becomes unreachable, it was noticed that the initial k8s connectivity can succeed and the subsequent retrieval of the node resource can fail. Emission of a warning is insufficient here as Cilium may continue with a configuration that is different (due to the fallback to defaults) than used in a previous run.

@aanm @raybejjani Please review. I remember that we initially wanted to keep this as a warning to not depend on node resources being available but given the above experience. I can't see a way to be reliable without failing hard in this case.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/3906)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — CHANGES_REQUESTED** [review]
The will require users to use kubernetes with `pod-cidr` set. which can potentially break current clusters deployed with cilium(?)

My suggestion would be to store the pod-cidr locally, or in the kvstore, if cilium is restarted *and* it can't connect to kube-apiserver then it would fall back to the values locally stored.

You may wonder, what if this is a new node and kubernetes hasn't assigned the pod-cidr to this node? Unfortunately, I don't have a solution for that

**Comment by raybejjani** [comment]
> The will require users to use kubernetes with pod-cidr set. which can potentially break current clusters deployed with cilium(?)

@aanm could you explain that a little more? In the case were `--pod-cidr` is used it means kubelet is in standalone mode, right? In that case there is no apiserver to talk to, I think.

I agree that we should store the node info locally. From what I can tell the IP range allocated to the node doesn't change in the normal case. This means that we can treat the presence of an on-disk copy of this data similarly to how we treat endpoint data to be restored. We restore to our last known state but can then update as needed. In the node-cidr case it just won't change.
The order of operations would be:
- check the server
  - use the data if present. Write a local copy.
  - if the server fails, or no data present, fallthrough
- check disk for an old copy
  - use the data if present
  - if no local copy, or no data preset, fallthrough
- Return an error, triggering an agent exit

("data present" includes checking for critically needed data, like the node's IP range.)

A new node that doesn't have any IP range should exit for the same reasons we chose to exit if we can't talk to the API server. Cilium simply can't do anything in that case and fails fast. We seem to gate this whole section on `K8S_NODE_NAME` being present, so I'm guessing that the env-variable isn't set in a standalone kubelet situation and that would continue to work. I don't fully understand that, though.

CLI options override the k8s node info, when present. This seems reasonable and wouldn't be affected by the above (you may load the data from disk but if the CLI params have changed they would then override). The only difference is that we would have to store the CLI set data to disk as well. This might be a problem, though, since the default behaviour now depends on prior state. Because of this, it might be better to store the k8s node info locally, and not the general cilium-agent ip info. I'm not sure.

**Comment by aanm** [comment]
>* Return an error, triggering an agent exit

The thing is, cilium can assign a pod-cidr to the node based on the node's IP, which covers 90% of the cases. So ideally we shouldn't trigger an agent exit.

**Comment by tgraf** [comment]
> The thing is, cilium can assign a pod-cidr to the node based on the node's IP, which covers 90% of the cases. So ideally we shouldn't trigger an agent exit.

The problem is that we need to know whether we have been using a default before or a CIDR associated by k8s.

**Comment by raybejjani** [comment]
This whole discussion is scoped to k8s, right? We know when k8s is configured, and can do these extra things then. In the non-k8s case we could continue as before. Or is the auto-assign behaviour also used when in kubernetes?

**Comment by tgraf** [comment]
> This whole discussion is scoped to k8s, right? We know when k8s is configured, and can do these extra things then. In the non-k8s case we could continue as before. Or is the auto-assign behaviour also used when in kubernetes?

Yes, we know exactly when we are in k8s mode and this logic should only apply then. The main problem is that we can't blindly fall back to defaults just because the apiserver is not available.

I agree with @aanm though that without having better understanding on how the system was configured before, we can potentially break systems with this.

In what situations is the node resource not available?

**Comment by aanm** [comment]
>In what situations is the node resource not available?

What node resource are you referring too?

**Pull request closed without merging**
