### PR TITLE
Vagrant: Bump base box to version 126.

### PR DESCRIPTION
**Pull request by eloycoto**
This version adds the NTP support in the VM.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6256)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by ianvernon** [comment]
Looks like something in the box update caused the preflight checks for `kubeadm` to fail:

```
15:33:24     k8s2-1.8: [preflight] The system verification failed. Printing the output from the verification:
15:33:24     k8s2-1.8: OS: Linux
15:33:24     k8s2-1.8: KERNEL_VERSION: 4.9.17-040917-generic
15:33:24     k8s2-1.8: CONFIG_NAMESPACES: enabled
15:33:24     k8s2-1.8: CONFIG_NET_NS: enabled
15:33:24     k8s2-1.8: CONFIG_PID_NS: enabled
15:33:24     k8s2-1.8: CONFIG_IPC_NS: enabled
15:33:24     k8s2-1.8: CONFIG_UTS_NS: enabled
15:33:24     k8s2-1.8: CONFIG_CGROUPS: enabled
15:33:24     k8s2-1.8: CONFIG_CGROUP_CPUACCT: enabled
15:33:24     k8s2-1.8: CONFIG_CGROUP_DEVICE: enabled
15:33:24     k8s2-1.8: CONFIG_CGROUP_FREEZER: enabled
15:33:24     k8s2-1.8: CONFIG_CGROUP_SCHED: enabled
15:33:24     k8s2-1.8: CONFIG_CPUSETS: enabled
15:33:24     k8s2-1.8: CONFIG_MEMCG: enabled
15:33:24     k8s2-1.8: CONFIG_INET: enabled
15:33:24     k8s2-1.8: CONFIG_EXT4_FS: enabled
15:33:24     k8s2-1.8: CONFIG_PROC_FS: enabled
15:33:24     k8s2-1.8: CONFIG_NETFILTER_XT_TARGET_REDIRECT: enabled (as module)
15:33:24     k8s2-1.8: CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled (as module)
15:33:24     k8s2-1.8: CONFIG_OVERLAY_FS: enabled (as module)
15:33:24     k8s2-1.8: CONFIG_AUFS_FS: not set - Required for aufs.
15:33:24     k8s2-1.8: CONFIG_BLK_DEV_DM: enabled
15:33:24     k8s2-1.8: CGROUPS_CPU: enabled
15:33:24     k8s2-1.8: CGROUPS_CPUACCT: enabled
15:33:24     k8s2-1.8: CGROUPS_CPUSET: enabled
15:33:24     k8s2-1.8: CGROUPS_DEVICES: enabled
15:33:24     k8s2-1.8: CGROUPS_FREEZER: enabled
15:33:24     k8s2-1.8: CGROUPS_MEMORY: enabled
15:33:24     k8s2-1.8: DOCKER_VERSION: 18.09.0
15:33:24     k8s2-1.8: [preflight] Some fatal errors occurred:
15:33:24     k8s2-1.8: 	unsupported docker version: 18.09.0
15:33:24     k8s2-1.8: [preflight] If you know what you are doing, you can skip pre-flight checks with `--skip-preflight-checks`
```

**Comment by aanm** [comment]
interesting, was docker updated? Aren't we always installing a specific version of docker when we create a new dev VM?

**Comment by eloycoto** [comment]
> interesting, was docker updated? Aren't we always installing a specific version of docker when we create a new dev VM?

No, we are using the latest stable

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Pull request merged**
