### PR TITLE
Split operator-only options into separate package

### PR DESCRIPTION
**Pull request by tklauser**
Split out all options which are specific to cilium-operator into the
separate github.com/cilium/cilium/operator/option package.
    
In the long term, the goal is to separate options which are common to
all Cilium binaries from options applicable to only a specific binary
(or a subset of them). This should also help to reduce unnecessary
dependencies and binary size.

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Review by nathanjsweet — APPROVED** [review]
good on green

**Review by aanm — APPROVED** [review]

**Comment by errordeveloper** [comment]
@tklauser in #10972  I've started building new provider-specific operator binaries, I didn't actually consider making them all use different flags, I am not sure how feasible it would be actually without a lot new code that takes care or registring new flags... if you have some ideas, perhaps we should sync on this topic before I resume working on #10972.

**Comment by tklauser** [comment]
@errordeveloper I haven't looked at #10972 in detail but from a quick look it seems to be using provider-specific build tags to build the different binaries? If so, I think it would be fairly easy to split up the flags further and put the provider-specifc ones into separate files with the proper build tag. So far, there don't seem to be too many provider-specific flags (6 AWS-specific options and 2 Azure-specific options), so it might not be worth the effort ATM. But certainly something to keep in mind...

**Pull request merged**
