### PR TITLE
test: Be verbose about VM provision failures

### PR DESCRIPTION
**Pull request by tgraf**
Related-to: #4300

Signed-off-by: Thomas Graf <thomas@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4301)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by eloycoto** [comment]
@tgraf I would add that here too.

https://github.com/cilium/cilium/blob/bee1ef9aab62a1a8d5d971d865d65ad582ef0d44/test/test_suite_test.go#L189

**Comment by tgraf** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3699/

Funnily enough, this build failure validated that this PR actually works:

```
  k8s1-1.10: 148def6518c3: 
    k8s1-1.10: Pull complete
    k8s1-1.10: d822dd246825: 
    k8s1-1.10: Pull complete
    k8s1-1.10: 08187eb019eb: 
    k8s1-1.10: Pull complete
    k8s1-1.10: a005c0af8719: 
    k8s1-1.10: Verifying Checksum
    k8s1-1.10: a005c0af8719: 
    k8s1-1.10: Download complete
    k8s1-1.10: 445f24ab6b53: 
    k8s1-1.10: Pull complete
    k8s1-1.10: 2a996c023d43: Pull complete
    k8s1-1.10: 9044d6b2a520: Pull complete

        ===================== ERROR - VM PROVISION FAILED =====================

        Unable to provision and start VM "k8s1-1.10": exit status 255", vm, err

        =======================================================================
```

Similar issue occurred on another PR: https://github.com/cilium/cilium/pull/4307 

VM could not be provisioned for the runtime tests as well:
```
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/Documentation'
    runtime: Makefile:275: recipe for target 'postcheck' failed
    runtime: make: *** [postcheck] Error 2
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

        ===================== ERROR - VM PROVISION FAILED =====================

        Unable to provision and start VM "runtime": exit status 1", vm, err

        =======================================================================
```

Is there an infrastructural issue occurring with provisioning VMs on packet.net?

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
