### PR TITLE
cilium: Fix missing error log dump from compilation

### PR DESCRIPTION
**Pull request by borkmann**
(see commit msg)

### CODE REVIEW

**Comment by borkmann** [comment]
Looks like this slipped in via https://github.com/cilium/cilium/commit/6882e98baf7c984e927858422805bb93add162a3 .

**Comment by borkmann** [comment]
(GH actions failing due to images not being ready, there have been cosign issues.)

**Review by jibi — APPROVED** [review]

**Review by ti-mo — APPROVED** [review]
Thank you!

**Pull request merged**
