### PR TITLE
ci: avoid null build names in master builds

### PR DESCRIPTION
**Pull request by nebril**

### CODE REVIEW

**Comment by nebril** [comment]
test-focus K8sDemos

**Comment by nebril** [comment]
test-focus K8sDemos

**Comment by nebril** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by nebril** [comment]
test-with-kernel

**Comment by nebril** [comment]
test-with-kernel

**Comment by nebril** [comment]
test-with-kernel

**Pull request merged**
