### PR TITLE
Re-opened PR: policy: remove `CIDRPolicy` structure

### PR DESCRIPTION
**Pull request by ianvernon**
While resolving policy with a large amount of rules containing CIDRs, a
significant amount of time was taken running `resolveCIDRPolicy`:

```
(pprof) list resolvePolicyLocked
Total: 3.58s
ROUTINE ======================== github.com/cilium/cilium/pkg/policy.(*Repository).resolvePolicyLocked in /Users/ianvernon/go/src/github.com/cilium/cilium/pkg/policy/repository.go
         0      2.72s (flat, cum) 75.98% of Total
         .          .    590:	// First obtain whether policy applies in both traffic directions, as well
         .          .    591:	// as list of rules which actually select this endpoint. This allows us
         .          .    592:	// to not have to iterate through the entire rule list multiple times and
         .          .    593:	// perform the matching decision again when computing policy for each
         .          .    594:	// protocol layer, which is quite costly in terms of performance.
         .       70ms    595:	ingressEnabled, egressEnabled, matchingRules := p.computePolicyEnforcementAndRules(securityIdentity)
         .          .    596:
         .          .    597:	calculatedPolicy := &selectorPolicy{
         .          .    598:		Revision:             p.GetRevision(),
         .          .    599:		SelectorCache:        p.GetSelectorCache(),
         .          .    600:		L4Policy:             NewL4Policy(p.GetRevision()),
         .       10ms    601:		CIDRPolicy:           NewCIDRPolicy(),
         .          .    602:		IngressPolicyEnabled: ingressEnabled,
         .          .    603:		EgressPolicyEnabled:  egressEnabled,
         .          .    604:	}
         .          .    605:	calculatedPolicy.IngressPolicyEnabled = ingressEnabled
         .          .    606:	calculatedPolicy.EgressPolicyEnabled = egressEnabled
         .          .    607:
         .          .    608:	labels := securityIdentity.LabelArray
         .          .    609:	ingressCtx := SearchContext{
         .          .    610:		To:          labels,
         .          .    611:		rulesSelect: true,
         .          .    612:	}
         .          .    613:
         .          .    614:	egressCtx := SearchContext{
         .          .    615:		From:        labels,
         .          .    616:		rulesSelect: true,
         .          .    617:	}
         .          .    618:
         .          .    619:	if option.Config.TracingEnabled() {
         .          .    620:		ingressCtx.Trace = TRACE_ENABLED
         .          .    621:		egressCtx.Trace = TRACE_ENABLED
         .          .    622:	}
         .          .    623:
         .          .    624:	if ingressEnabled {
         .          .    625:		newL4IngressPolicy, err := matchingRules.resolveL4IngressPolicy(&ingressCtx, p.GetRevision(), p.GetSelectorCache())
         .          .    626:		if err != nil {
         .          .    627:			return nil, err
         .          .    628:		}
         .          .    629:
         .          .    630:		newCIDRIngressPolicy := matchingRules.resolveCIDRPolicy(&ingressCtx)
         .          .    631:		if err := newCIDRIngressPolicy.Validate(); err != nil {
         .          .    632:			return nil, err
         .          .    633:		}
         .          .    634:
         .          .    635:		calculatedPolicy.CIDRPolicy.Ingress = newCIDRIngressPolicy.Ingress
         .          .    636:		calculatedPolicy.L4Policy.Ingress = newL4IngressPolicy
         .          .    637:	}
         .          .    638:
         .          .    639:	if egressEnabled {
         .      2.02s    640:		newL4EgressPolicy, err := matchingRules.resolveL4EgressPolicy(&egressCtx, p.GetRevision(), p.GetSelectorCache())
         .          .    641:		if err != nil {
         .          .    642:			return nil, err
         .          .    643:		}
         .          .    644:
         .      620ms    645:		newCIDREgressPolicy := matchingRules.resolveCIDRPolicy(&egressCtx)
         .          .    646:		if err := newCIDREgressPolicy.Validate(); err != nil {
         .          .    647:			return nil, err
         .          .    648:		}
         .          .    649:
         .          .    650:		calculatedPolicy.CIDRPolicy.Egress = newCIDREgressPolicy.Egress
```

Approximately 17% of policy calculation time is taken by `resolveCIDRPolicy` in
this case. Now that we compute all CIDR-based policy in terms of selectors and
identities allocated for CIDRs, this function does not have any purpose from a
policy perspective. Its main purposes were for adding visbility into CIDR-based
policy in the Endpoint API, and for obtaining the set of prefix lengths for
kernels >= 4.9 < 4.11. These prefix lengths are needed for these kernel
versions because said versions do not support LPM map types, and the
implementation of the ipcache in the datapath varies in complexity based off of
the number of prefix lengths of CIDRs used for policy. The prefix lengths of
the resultant CIDR-based policy for each endpoint to determine if the number of
prefix lengths returned were greater than the empirically measured number of
prefix lengths which were determined to break the upper-bound of the complexity
limit in the BPF verifier for these kernels.

Instead, we now use the number of unique prefix lengths in the ipcache itself as
the number of prefixes for IPv6 and IPv4 for which the endpoint's BPF program is
aware, which is global to the entire daemon, instead of per-CIDR policy in the
endpoint. If policy is imported into cilium which does not select an endpoint,
the endpoint will not be aware of these new prefix lengths until it is next
regenerated. The CIDR-based representation in the endpoint API is now empty, but
is still accessible in Kubernetes environments via CEP.

Total policy generation benchmark time before this change:

```
PASS: resolve_test.go:214: PolicyTestSuite.BenchmarkRegenerateCIDRPolicyRules	     500	   4541126 ns/op
```

Total policy generation benchmark time after this change:

```
PASS: resolve_test.go:214: PolicyTestSuite.BenchmarkRegenerateCIDRPolicyRules	     500	   3403568 ns/op
```

The performance improvement is approximately 25 % with this change, which will
help a lot in clusters with policies containing large numbers of CIDRs.

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8577)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
(Propagating my :+1: from prior merge)

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
DNS and multiple specs with FQDN test failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13692/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13722/

**Pull request closed without merging**
