### PR TITLE
Daemon: Do not clean policy maps on startup

### LINKED ISSUE #5142: Policy maps are unnecessarily unpinned from filesystem on startup
Logs observed running roughly master:

```
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="Registered BPF map" path=/sys/fs/bpf/tc/globals/cilium_policy_reserved_2 subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="Unified diff:" subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="--- b" subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="+++ a" subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="@@ -1,15 +1,15 @@" subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg=" &bpf.Map{" subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="     MapInfo:                    bpf.MapInfo{MapType:1, KeySize:0x8, ValueSize:0x18, MaxEntries:0x4000, Flags:0x0, OwnerPr
ogType:0}," subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="-    fd:                         0," subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="+    fd:                         17," subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="     name:                       \"cilium_policy_reserved_2\"," subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="-    path:                       \"\"," subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="+    path:                       \"/sys/fs/bpf/tc/globals/cilium_policy_reserved_2\"," subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="     once:                       sync.Once{}," subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="     lock:                       lock.RWMutex{}," subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="     enableSync:                 false," subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="     openLock:                   lock.Mutex{}," subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="     NonPersistent:              false," subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="     dumpParser:                 bpf.DumpParser {...}," subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="     cache:                      {}," subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="     errorResolverLastScheduled: time.Time{}," subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg="     outstandingErrors:          0," subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=debug msg=" }" subsys=bpf
Aug 09 08:29:09 runtime1 cilium-agent[22737]: level=info msg="Outdated non-persistent BPF map found, removing..." file-path=cilium_policy_reserved_2 subsys=daemon
```

If the filepath is not set in the structure being compared, and the map is not yet open (so it doesn't have an fd), then there will always be a diff in the properties, and the map will always be deleted.

This shouldn't cause any connectivity issue, because even if the map is removed from the filesystem, any BPF programs that reference the map should continue to operate on an existing reference to the map. However, there's no point in checking the fd and path for this comparison operation or deleting the maps because of a mismatch in these attributes.

### PR DESCRIPTION
**Pull request by eloycoto**
On startup the filepath is not set, and the map is not open (it does not
have an fd) there will be a diff and map will always be deleted.

Fix #5142

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5559)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

(Infra issue https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/6472/execution/node/77/log/)

**Comment by eloycoto** [comment]
test-me-please

**Review by joestringer — CHANGES_REQUESTED** [review]
This looks like it's safe because `PolicyMap.OpenMap()` calls `bpf.OpenOrCreate(...)` which already should be validating the attributes of the maps.

I think we can also remove `policymap.Validate()`.

Related: #5168

**Comment by ianvernon** [comment]
Not sure why the build failed - it only took a few seconds, then exited with failure. Will run tests again...

**Comment by ianvernon** [comment]
test-me-please

**Comment by joestringer** [comment]
My only outstanding reservation on this PR is that this keeps some dead code around in `policymap.Validate()`.

**Comment by eloycoto** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
