### PR TITLE
operator: Fix CEP and CES events debug logs

### PR DESCRIPTION
**Pull request by dlapcevic**
Signed-off-by: Dorde Lapcevic <[dordel@google.com](mailto:dordel@google.com)>

### CODE REVIEW

**Review by pippolo84 — APPROVED** [review]
Thanks! :rocket:

**Comment by dlapcevic** [comment]
@pippolo84 could we please merge this?
The failing tests are broken or flakes that cannot be related to a debug logging change.

**Comment by pippolo84** [comment]
It has been marked ready-to-merge now, so it will be merged by a repo owner soon. :+1:

**Pull request merged**
