### PR TITLE
Add mechanism to bootstrap k8s api-server BPF service

### LINKED ISSUE #9018: kube-proxy-free: connect to multiple kube-apiservers
Currently, for Kubernetes deployments w/o kube-proxy, we ask users to specify only one kube-apiserver non-virtual IP addr + port. This overrides the `KUBE_SERVICE_{HOST,PORT}` env vars of the cilium-agent pod, which makes cilium-agent's k8s client to connect to that particular kube-apiserver (see #8995 for this hack reasoning).

In the case of multi-master setup, cilium-agent won't be able to connect to any other than the specified kube-apiserver, as the non-virtual IP addr + port is used. This is not ideal, as a) HA property is lost, b) load is non-evenly distributed among masters.

Instead, we should ask users to provide kube-apiserver non-virtual IP addr + port just for bootstrapping, so that all master could be used after a list of kube-apiserver endpoints has been received.

### PR DESCRIPTION
**Pull request by brb**
This PR introduces a mechanism for bootstrapping k8s api-server BPF service when running Kubernetes without kube-proxy.

The main problem in such setup is that the iptables DNAT rule `(ClusterIP:443 => $MASTER_NODE_IP:6443)` is no longer installed, as kube-proxy is not running. Therefore, cilium-agent is not able to connect to the api-server via the ClusterIP which is passed to the cilium-agent Pod via the env vars by kubelet.

To resolve this chicken-n-egg problem, we ask users to pass `"https://$MASTER_NODE_IP:6443"` via the `--k8s-api-server-url-no-kubeproxy` flag (OT: happy to consider a better name for the flag). This allows cilium-agent to connect to the api-server, and consequently the corresponding BPF LB entry can be created for it which allows the api-server address to be reset to ClusterIP (a connection to the ClusterIP from the host netns is possible thanks to the host reachable services feature).

An alternative solution would have been to pre-populate the BPF LB maps with the required mapping. Unfortunately it cannot be so easily achieved, as bpf_sock.o (the host-reachable services program) gets loaded after cilium-agent has established a connection to the api-server.

Reviewable per commit.

Fixes #9018.

TODO:

- [ ] Add CI test.
- [ ] Atomic updates of pkg/k8s.Client pointers.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9089)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by aanm — CHANGES_REQUESTED** [review]
I don't think this PR is required. To have Cilium connected to a kube-apiserver without kube-proxy the user can specify it like this:

setup the following configmap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: cilium
data:
  kubeconfig-cilium: |-
    apiVersion: v1
    kind: Config
    clusters:
      - name: kube
        cluster:
          server: https://k8s-core-1:6443
          certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    users:
      - name: service-account
        user:
          tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    current-context: kube
    contexts:
      - name: kube
        context:
          cluster: kube
          user: service-account
```

add the following patch to his daemonset
```patch
    spec:
      containers:
      - args:
+        - --k8s-kubeconfig-path=/etc/cilium/kubeconfig.yml
...
          # Needed to be able to load kernel modules
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
+        - mountPath: /etc/cilium/
+          name: kubeconfig-cilium
+          readOnly: true
...
      - configMap:
          name: cilium-config
        name: cilium-config-path
        # To read the configuration from the config map
+      - configMap:
+          name: cilium-config
+          items:
+          - key: kubeconfig-cilium
+            path: kubeconfig.yml
+        name: kubeconfig-cilium
```

**Comment by brb** [comment]
@aanm Your suggestion has been already implemented, see https://github.com/cilium/cilium/pull/8995, https://github.com/cilium/cilium/pull/8981 and the guide https://docs.cilium.io/en/v1.6/gettingstarted/kubeproxy-free/.

The current implementation (and thus, your suggestion) has the following problems:

- kubeconfig has to be distributed to all nodes running Cilium.
- cilium-agents will connect to the same and only one kube-apiserver instance. In the case of multi-master setup, this means that the HA property is lost. Also, non-even load distribution to kube-apiserver.

This PR addresses both problems without requiring a user to have an additional LB for kube-apiserver.

**Comment by aanm** [comment]
> @aanm Your suggestion has been already implemented, see #8995, #8981 and the guide https://docs.cilium.io/en/v1.6/gettingstarted/kubeproxy-free/.
> 
> The current implementation (and thus, your suggestion) has the following problems:
> 
> * kubeconfig has to be distributed to all nodes running Cilium.

Which is being done by the connectivity from kubelet to kube-apiserver automatically.

> * cilium-agents will connect to the same and only one kube-apiserver instance. In the case of multi-master setup, this means that the HA property is lost. Also, non-even load distribution to kube-apiserver.
> 

kubelet already has the same problem.

> This PR addresses both problems without requiring a user to have an additional LB for kube-apiserver.

The HA described in the k8s docs is to have a LB in front of all kube-apiservers https://kubernetes.io/docs/tasks/administer-cluster/highly-available-master/#implementation-notes.

I don't understand why are we adding more complexity into cilium's code base to solve a problem that is not Cilium specific.

**Comment by brb** [comment]
> Which is being done by the connectivity from kubelet to kube-apiserver automatically.

I'm not following this.

> kubelet already has the same problem.

Neither this. Do you mean kube-proxy instead of kubelet? If yes, then it has the same problem.

> The HA described in the k8s docs is to have a LB in front of all kube-apiservers https://kubernetes.io/docs/tasks/administer-cluster/highly-available-master/#implementation-notes.

This is just an example of the k8s HA.

> I don't understand why are we adding more complexity into cilium's code base to solve a problem that is not Cilium specific.

I think requiring a user to install additional LB is more complex and cumbersome than to do the loadbalancing to kube-apiserver from Cilium which already has the LB.

**Comment by aanm** [comment]
> > Which is being done by the connectivity from kubelet to kube-apiserver automatically.
> 
> I'm not following this.
> 

If you have a configmap in kube-apsierver that same configmap is distributed to all nodes that are running kubelet.

> > kubelet already has the same problem.
> 
> Neither this. Do you mean kube-proxy instead of kubelet? If yes, then it has the same problem. But it doesn't mean that we can't do better.
> 

No, I meant kubelet, kubelet also needs to access kube-apiserver via the real api-server address.

> > The HA described in the k8s docs is to have a LB in front of all kube-apiservers https://kubernetes.io/docs/tasks/administer-cluster/highly-available-master/#implementation-notes.
> 
> This is just an example of the k8s HA.
> 
> > I don't understand why are we adding more complexity into cilium's code base to solve a problem that is not Cilium specific.
> 
> I think requiring a user to install additional LB is more complex and cumbersome than to do the loadbalancing to kube-apiserver from Cilium which already has the LB.

The user will have to to this if it wants kube-apiserver HA otherwise kubelet won't be able to access multiple kube-apiservers.

**Comment by brb** [comment]
@aanm Aha, I see what you meant. However, there is one setup in which this PR might make sense - cilium-agent running as a standalone process (i.e. not as part of a DaemonSet). In this case, kubelet and other could connect to apiservers via ClusterIP which is load-balanced by Cilium.

**Comment by brb** [comment]
Closing this for now in favor of #9198.

**Pull request closed without merging**
