### PR TITLE
bgpv1: pass router state to gobgp

### PR DESCRIPTION
**Pull request by harsimran-pabla**
This change passes additional context regarding the control plane state to GoBGP.

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]
These changes look fine to me. 

Just have to remember not to hold onto a ControlPlaneState, as that data is always pushed down on reconcile. 

I say this just because the constructor almost looks like its getting ready to hold onto the state, but the intention is just to use it as flags for construction purposes right? I.e. the ControlPlaneState shouldn't be referenced after initial BGP Speaker initialization, cuz it may contain stale data.

**Comment by harsimran-pabla** [comment]
@ldelossa  Yes, the idea is only to use it in the constructor and not hold on to it.

**Review by rastislavs — APPROVED** [review]

**Comment by harsimran-pabla** [comment]
Not a new feature, should be eligible for merge. 

cc @ldelossa

**Comment by ldelossa** [comment]
@harsimran-pabla theres two stuck tests here, can you rebase and push?

**Comment by brb** [comment]
@harsimran-pabla @ldelossa Please rebase against the latest `main` branch to avoid `ci-e2e` failures.

**Comment by harsimran-pabla** [comment]
Thanks @brb, currently this PR is on top of commit fbbdcabd03 from main, I think it contains KPR related fixes.

**Pull request merged**
