### PR TITLE
Prepare for 1.1.3 release

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5194)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by borkmann — APPROVED** [review]

**Review by joestringer — DISMISSED** [review]
On newer kernels, "daemon: Upgrade CT map properties on startup" will cause recreation of the CT map upon every startup, not just on upgrade.

**Comment by joestringer** [comment]
PR is out for the issue I highlighted: #5197

**Review by rlenglet — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
Noticed that I missed to push the changes to `NEWS.rst`. Will push it after the CI build is done.

**Review by joestringer — APPROVED** [review]

**Pull request merged**
