### PR TITLE
Revert "test: disable fqdn restart test"

### PR DESCRIPTION
**Pull request by jrajahalme**
This reverts commit a4d86b2abc8fa0c77306cc41a3bb2f753b7fe1d2.

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by nebril** [comment]
Was there a change that fixed it?

**Comment by jrajahalme** [comment]
@nebril No, but need to see if/how this is failing. Converted this PR to draft.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
CI failed due to quay error in precheck, retesting.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by nebril** [comment]
@jrajahalme cool, I thought it was out for review and got confused. Good luck!

**Comment by jrajahalme** [comment]
Health status between nodes failing again: #6728

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Opening this for review, have had 4 consecutive without the FQDN test failing on any pipeline. Testing once more, but looks like this flake is rare enough to be merged to master.

**Comment by jrajahalme** [comment]
5 consecutive CI runs without this test flaking, merging this in.

**Pull request merged**
