### PR TITLE
v1.11 backports 2023-03-01

### PR DESCRIPTION
**Pull request by sayboras**
- [ ] #23441 -- helm: Add SA automount configuration (@sayboras)
 - [x] #23590 -- Add leader requirement to watch from Etcd. (@marseel)
 - [x] #23947 -- clustermesh: fix services cache bloat due to incorrect deletion (@giorio94)
 - [ ] #23443 -- helm: Add pod and container security context (@sayboras)
 - [x] #24012 -- docs: Fix the dead link to Mellanox performance tuning guide (@gentoo-root)
 - [x] #23469 -- bpf: Fix usage of tunnel map structs (@pchaigno)
     - Minor conflicts.
 - [x] #24030 -- IPsec: Remove `IP_POOLS` logic (@pchaigno)
     - Conflicts in almost all commits, most major.

Skipped due to conflicts:
  - [ ] #23915 -- agent: dump stack on stale probes (@squeed)
      - skipped due to compilation issue in older golang version. 

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 23469 23441 23590 23947 23443 24012 24030; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
My commit looks good. Thanks!

**Comment by marseel** [comment]
My commit looks good too, thank you!

**Review by marseel — APPROVED** [review]

**Comment by sayboras** [comment]
> #24012 is in the pull request description, but not in the commit list. Why?

My bad, I didn't push and mark this ready for review.

**Comment by sayboras** [comment]
/test-backport-1.11

**Review by gentoo-root — APPROVED** [review]
Approved for my commit.

**Comment by pchaigno** [comment]
/test-backport-1.11

**Comment by pchaigno** [comment]
/test-backport-1.11

**Comment by sayboras** [comment]
All CI jobs are successfully run, except below two failures:

- BPF Checks --> which could be known issue
- Travis CI due to un-used import and diff in helm generated docs. Force push to correct this issue.

**Comment by sayboras** [comment]
/test-backport-1.11

**Comment by sayboras** [comment]
Merging this PR in with below points:

- "BPF checks / build datapath" failed with known CI job issue https://github.com/cilium/cilium/issues/23682. 
- All CI Jobs are passed.
- Force-push is for helm related docs only, no need to perform IPSec manual verification again.
- Reviews are in

**Pull request merged**
