### PR TITLE
CFP: GatewayAPI TCPRoute support

### LINKED ISSUE #29924: API Gateway TCPRoute - Adding TCPRoute for Logstash and Filebeat
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello everyone ! i tried to put a filebeat on a server and send logs to my logstash service from my K8S cluster. 
Here my code for the API GATEWAY for cilium. So it's listening on HTTP and HTTPS but can't find 5044 TCP.
I follow this documentation : https://gateway-api.sigs.k8s.io/guides/tcp/ 
``` yaml
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: cilium
  labels:
    site: ach
spec:
  gatewayClassName: cilium
  listeners:
  - name: https
    port: 443
    protocol: TLS
    tls:
      mode: Passthrough
    allowedRoutes:
      namespaces:
        from: All
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: logstash
    port: 5044
    protocol: TCP
    allowedRoutes:
      kinds:
      - kind: TCPRoute
      namespaces:
        from: All`
```        
 So i don't really know if the TCPRoute are working or not, but when i'm creating a gateway with only listening 5044 TCP, it's said : "level=error msg="Unable to translate resources" controller=gateway error="model source can't be empty" resource=cilium/tcp-gateway subsys=gateway-controller" 
 
 Here are my routes : 
```yaml
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: test-kibana
  namespace: eck
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: cilium
  hostnames:
  - "test-kibana..com"
  rules:
  - backendRefs:
    - name: kibana-service
      port: 5601
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: test-logstash
  namespace: eck
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: cilium
  rules:
  - backendRefs:
    - name: logstash-service
      port: 5044
 ```
 If someone has sucessfully find a way to create TCPRoute correctly, i hope you will help me !
 
Thanks you very much for your help guys !

### Cilium Version

V1.14.5

### Kernel Version

5.15.0-88-generic

### Kubernetes Version

v1.28.2

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Fixes: #29924

Part of #21929

```release-note
TCPRoute that supports GatewayAPI
```

### CODE REVIEW

**Comment by wibed** [comment]
oh boy oh boy its happening 💯

**Comment by madushanTHAMB** [comment]
Is he already availables ?

**Comment by DrMeosch** [comment]
Hi guys, which release would get this feature?

**Comment by wibed** [comment]
@chaunceyjiang any update on this?

**Comment by youngnick** [comment]
I'm sorry about the delay on responding on this PR. I've needed to think about it quite a bit.

Firstly, thanks for the work you've put in to prepare this PR, @chaunceyjiang. I really appreciate it, and thanks for showing how handling TCP proxying can work with Envoy.

One of the reasons this wasn't implemented already by the folks working on Service Mesh is that Envoy's TCP proxying is exactly that, a _proxy_. This means that the TCP connection is terminated on the "outside" of Envoy, and a new TCP connection is created to talk to backends. This means that the connections will effectively have source NAT applied to them - all the connections at the backend will appear to come from the Envoy proxy, and the remote client address will _not_ be preserved. So as far as the backend is concerned, all its traffic will come from Envoy, not from the actual client.

For HTTP, this sort of thing is handled by mechanisms like X-Forwarded-For headers and so on, but for bare TCP, there's nothing we can do. My experience with this is that users almost always want the client address preserved.

So, we've been holding off to try and build something more like how a Loadbalancer Service works (one of the possible ways to implement it is _using_ a Loadbalancer Service, even!), but haven't made much progress.

I can see from folks replies here that there's a lot of interest. Can I ask you all watching, would you really want TCP Proxying support? Or is it TCP _Forwarding_ you really want in TCPRoute support?

(All of this is another reason why Gateway API itself has not had a lot of development on TCPRoute for a while too).

**Comment by wibed** [comment]
forwarding!

**Comment by madushanTHAMB** [comment]
It's more about the TCP Forwarding

**Comment by igor-borisoglebski** [comment]
A very frequent use case is so that it is possible to preserve the source IP address through the proxy protocol as delivered by the cloud load balancers. ie to implement network policies based on client source IP and not LB source IP. This seems to only be achievable through API Gateway supporting the TCPRoute as the proxy protocol is only supported on ingress and API Gateway. Please correct me if I'm wrong

**Comment by youngnick** [comment]
Yes, thanks @ToroNZ. Proxy Protocol support is available from Cilium 1.15.

**Comment by youngnick** [comment]
@zodd3131, sorry, but I don't understand your meaning here.

We already have proxy protocol support for passing through connections as @ToroNZ mentioned above, as of Cilium 1.15.

Additionally, we also have TLS passthrough support using the TLSRoute object in Gateway API.

So, if you want Cilium to pass through a TLS session, and use the SNI to choose what backend to send the traffic to, you can already do that, regardless of what traffic is inside the TLS session. It can be HTTP, but it can also be any other TCP stream.

TCPRoute support in Gateway API is _only_ for unencrypted TCP streams, or TLS streams where Cilium is expected to terminate TLS for the stream, and then forward packets to the backend.

To say this again, more clearly:

TCPRoute is _not_ required to get TLS traffic forwarded to backends, or to make the original IP address visible to a HTTP backend.

**Comment by zodd3131** [comment]
Thank you @youngnick for the reply.
I will try to be as clear as possible this time.

I'm not interested in proxy protocol for my use case.
I want cilium to terminate TLS for the stream and then forward packets to backend.

For now, since cilium  doesn't support TCPRoute, I had to use SNI and make my pods supports TLS so that I can use TLS passthrough. Supporting TLS makes me generates x509 certificate

```mermaid
graph LR
A[client] -- TCP/TLS --> B[Gateway]
B -- TLSRoute --> C[service1]
B -- TLSRoute --> D[service2]
C -- TCP/TLS --> E[POD1]
D -- TCP/TLS --> F[POD2]
```

We handle a lot of legacy tcp streams. Forwarding encrypted flows over the network is something we are looking for. TCPRoute support in GatewayAPI where cilium terminates the TLS stream would be a game changer for us.
 That is what we expect :

```mermaid
graph LR
A[client] -- TCP/TLS --> B[Gateway]
B -- TCPRoute --> C[service1]
B -- TCPRoute --> D[service2]
C -- TCP--> E[POD1]
D --TCP --> F[POD2]
```

**Comment by youngnick** [comment]
Thanks @zodd3131 for the diagrams and use case, any chance you could put that on #21929? That will help that use case be more useful in discussions about TCPRoute.

This PR implements TCPRoute _proxying_, which is not transparent. So your app will see the Envoy proxy as the _source_ of the connection, not the end user. Envoy _can_ do transparent proxying of TCP traffic, but you will run into return-path issues, because the traffic will not be re-translated to come out of the Gateway external IP, because the Pod will send _directly_ back to the external client (so the source address will be the public address for general traffic).

This is why my current approach is to implement TCPRoute and UDPRoute using similar semantics to Loadbalancer Services rather than this proxying method - I think that the tradeoffs here are hard to explain and will affect only a subset of users based on their exact network topology.

**Comment by sbocahu** [comment]
that's sad to see this being closed !
any chance it could be reopened / tcproute landing into cilium ?

**Comment by youngnick** [comment]
@sbocahu, #21929 is the issue that tracks adding support for TCPRoute and UDPRoute to Cilium. That issue is the place to watch for further updates. We do absolutely intend to support Layer 4 forwarding in some way in Cilium when we can.

**Pull request closed without merging**
