### PR TITLE
v1.15 Backports 2024-11-05

### PR DESCRIPTION
**Pull request by joamaki**
* [x] #32598 (@sayboras)
 * [x] #35623 (@mhofstetter) :warning: resolved conflicts
 * [x] #35632 (@chancez)
 * [x] #35738 (@gandro) :warning: resolved conflicts

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 32598 35623 35632 35738
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Looks good for my commit :+1:

**Review by gandro — APPROVED** [review]

**Comment by joamaki** [comment]
/test-backport-1.15

**Review by nebril — APPROVED** [review]

**Review by chancez — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by joamaki** [comment]
Repeatedly hitting https://github.com/cilium/cilium/issues/35594

**Comment by joamaki** [comment]
/test-backport-1.15

**Pull request merged**
