### PR TITLE
examples/kubernetes: add volume types

### PR DESCRIPTION
**Pull request by aanm**
Volume Types allows to fail fast in case the volume type does not exist
on a specific node, for example if a specific path is not a Unix Socket,
or create a directory for a volume path if it does not exist on the node.

Signed-off-by: André Martins <andre@cilium.io>

```release-note
Add volume types for volumes in kubernetes Cilium DaemonSet.
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4755)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by tgraf** [comment]
Does this require docker to be running for the default daemonset? I know that some of our users are using `--container-runtime=disabled` on master nodes. That would break?

I agree that the crio DS should look for the socket as it is specific to cri-o.

**Comment by aanm** [comment]
@tgraf that's a fair concern but, shouldn't the docker socket be available in the node where cilium is running? If there's no docker, i.e. a container runtime, how is cilium going to be running on that node? You might answer that he is probably running rkt or CRI-o. OK, if the user is running with `--container-runtime=disabled` he must have 2 DaemonSets, one for master and the other for the remaining nodes. If the user upgrades its DaemonSet he needs to add `--container-runtime=disabled` by hand, will he remove the volume mount as well? Probably not, so how can we make sure he removes it?

With `type: "Socket"`, he will later see a warning with `kubectl describe` stating "Socket" not available and the cilium pod will not be scheduled to that node. If we remove the type "Socket" **and** the socket does not exist, the container runtime will create a directory with that pathname. That might prevent the user from running docker in the future as I am not 100% sure if that directory will ever be removed and/or if docker will fail to start if there's a path with the same name of the default docker socket that is an existing directory.

**Comment by tgraf** [comment]
> OK, if the user is running with --container-runtime=disabled he must have 2 DaemonSets, one for master and the other for the remaining nodes. If the user upgrades its DaemonSet he needs to add --container-runtime=disabled by hand, will he remove the volume mount as well?

Fair point. I'm convinced.

> With type: "Socket", he will later see a warning with kubectl describe stating "Socket" not available and the cilium pod will not be scheduled to that node. If we remove the type "Socket" and the socket does not exist, the container runtime will create a directory with that pathname. That might prevent the user from running docker in the future as I am not 100% sure if that directory will ever be removed and/or if docker will fail to start if there's a path with the same name of the default docker socket that is an existing directory.

Very good point!

**Review by tgraf — APPROVED** [review]

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
