### PR TITLE
k8s: do not create service if nodeport is 0 in port fields for LB/NodePort services

### LINKED ISSUE #14343: Optionally disable NodePorts for Service Type=LoadBalancer
See [KEP](https://github.com/kubernetes/enhancements/issues/1864).

### PR DESCRIPTION
**Pull request by fristonio**
Fixes #14343 

This field is independent of the CNI. The NodePorts are assigned by `kube-apiserver`. 

With kube-proxy - 4.9 Kernel. As from the `kubectl get svc` output we can see that there is no NodePort assigned to the service. 

image

From Cilium's side, we only need a minor change in the service parsing step. If currently no NodePort is assigned to a `port` field for NodePort service we assume the NodePort to be 0(default value of uint16 in golang) and create a service for that port.

`net-next` kernel with Cilium BPF NodePort enabled -

image

To honor the aforementioned field in Service spec we need to make sure that if the NodePort is `0` then we don't add the corresponding NodePort service to Cilium.

`net-next` with the changes proposed in the Pull Request.

image

To test this `kube-apiserver` must run with `--feature-gates=ServiceLBNodePortControl=true`

```release-note
Honor `allocateLoadBalancerNodePorts` in Kubernetes LoadBalancer service spec.
```

### CODE REVIEW

**Comment by fristonio** [comment]
test-me-please

**Review by aanm — CHANGES_REQUESTED** [review]
Can you add a unit test for this case? Thanks

**Review by brb — APPROVED** [review]
LGTM, thanks!

**Review by christarazi — APPROVED** [review]

**Comment by fristonio** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Pull request merged**
