### PR TITLE
v1.13 Backports 2024-01-30

### PR DESCRIPTION
**Pull request by joamaki**
* [x] #30403 (@f1ko)
 * [x] #30410 (@julianwiedmann)
 * [x] #30399 (@tlcowling)
 * [x] #30219 (@dependabot[bot])
 * [x] #30443 (@brlbil :warning: fair bit of conflicts that I resolved by hand, check carefully!)
 * [x] #30422 (@geakstr)
 * [x] #30503 (@qmonnet)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30403 30410 30399 30219 30443 30422 30503
```

### CODE REVIEW

**Comment by joamaki** [comment]
/test-backport-1.13

**Review by qmonnet — APPROVED** [review]
Thanks!

**Review by brlbil — APPROVED** [review]
Thank you!

**Review by julianwiedmann — APPROVED** [review]

**Review by geakstr — APPROVED** [review]
Thanks!

**Pull request merged**
