### PR TITLE
test: Bump ubuntu-next version to 23

### PR DESCRIPTION
**Pull request by brb**
Notable changes:

- Get rid of custom kernel patches.
- Update vboxsf to work with VirtualBox v6.
- Cache some container images used by Docker (incl. `cilium-runtime` to include iproute2 changes for the host lb).
- Kernel version `linux-5.1.0-rc5`.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7908)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by brb** [comment]
Hit https://github.com/cilium/cilium/issues/7853

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
Building `cilium-agent` timed out:

```
15:10:34      k8s1-1.10: go build -ldflags '-X "github.com/cilium/cilium/pkg/version.Version=1.5.90 59afde6ee 2019-05-03T11:28:54+00:00 go version go1.12.1 linux/amd64" -X "github.com/cilium/cilium/pkg/envoy.RequiredEnvoyVersionSHA=f65bc191a9b99d7bdc6288821d5ee1fe2517f4db" -X "github.com/cilium/cilium/pkg/datapath/loader.DatapathSHA=72b36d7b8971729418098eab9fc2f53efbf7cfa4"'  -tags lockdebug -o cilium-agent
15:48:26  Sending interrupt signal to process
15:48:46  After 20s process did not stop
```

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failed due to VM provisioning timeout on `jenkins-fixed-new-2`.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
Closing in favor of https://github.com/cilium/cilium/pull/7923.

**Pull request closed without merging**
