### PR TITLE
test: update k8s versions

### PR DESCRIPTION
**Pull request by aanm**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7263)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Build timed out: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1744/

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by brb** [comment]
@aanm Why did we commit `Gopkg.{toml.lock}.orig` files?

**Pull request merged**
