### PR TITLE
Documentation framework

### LINKED ISSUE #347: Documentation framework

### PR DESCRIPTION
**Pull request by tgraf**
Fixes: #347
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/cilium/cilium/pull/378%23issuecomment-288792955%22%2C%20%22https%3A//github.com/cilium/cilium/pull/378%23issuecomment-288797107%22%2C%20%22https%3A//github.com/cilium/cilium/pull/378%23issuecomment-289208391%22%2C%20%22https%3A//github.com/cilium/cilium/pull/378%23issuecomment-289230237%22%2C%20%22https%3A//github.com/cilium/cilium/pull/378%23issuecomment-289232846%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/cilium/cilium/pull/378%23issuecomment-288792955%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Looks%20good%20to%20me.%20Had%20to%20make%20some%20minor%20changes%20to%20build%20%60make%20html%60%20%20without%5Cr%5Cnerrors.%20Have%20you%20thought%20about%20using%20a%20different%20theme%3F%20%5BIt%5D%28https%3A//alemayhu.com/download/cilium/%29%20might%20look%20better%20with%20more%20color%2C%20IMO.%5Cr%5Cn%5Cr%5Cn%60%60%60bash%5Cr%5Cn%24%20cd%20Documentation%5Cr%5Cn%24%20mdkir%20_static%5Cr%5Cn%24%20git%20diff%5Cr%5Cn%60%60%60%5Cr%5Cn%60%60%60diff%5Cr%5Cndiff%20--git%20a/Documentation/index.rst%20b/Documentation/index.rst%5Cr%5Cnindex%200ab6c3ed2010..33cc4a3e9a5a%20100644%5Cr%5Cn---%20a/Documentation/index.rst%5Cr%5Cn%2B%2B%2B%20b/Documentation/index.rst%5Cr%5Cn%40%40%20-17%2C6%20%2B17%2C8%20%40%40%20Welcome%20to%20Cilium%27s%20documentation%21%5Cr%5Cn%20%20%20%20installation%5Cr%5Cn%20%20%20%20integrations%5Cr%5Cn%20%20%20%20contributing%5Cr%5Cn%2B%20%20%20commit-access%5Cr%5Cn%2B%20%20%20roadmap%5Cr%5Cn%20%5Cr%5Cn%20Indices%20and%20tables%5Cr%5Cn%20%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cr%5Cndiff%20--git%20a/Documentation/installation.rst%20b/Documentation/installation.rst%5Cr%5Cnindex%2018aca0827c64..f59491945739%20100644%5Cr%5Cn---%20a/Documentation/installation.rst%5Cr%5Cn%2B%2B%2B%20b/Documentation/installation.rst%5Cr%5Cn%40%40%20-17%2C15%20%2B17%2C15%20%40%40%20Prerequisites%5Cr%5Cn%20Cilium%20requires%20a%20recent%20version%20of%20the%20Linux%20kernel%2C%20iproute2%20and%20clang%2BLLVM.%5Cr%5Cn%20All%20required%20changes%20have%20been%20merged%20upstream%20and%20are%20available%20in%20official%5Cr%5Cn%20releases%3A%5Cr%5Cn-%20%2A%20Linux%20%3E%3D%204.8.0%3A%20http%3A//www.kernel.org/%5Cr%5Cn-%20%2A%20iproute2%20%3E%3D%204.8.0%3A%20https%3A//www.kernel.org/pub/linux/utils/net/iproute2/%5Cr%5Cn-%20%2A%20clang%2BLLVM%20%3E%3D3.7.1%3A%20http%3A//llvm.org/releases%5Cr%5Cn%2B%2A%20Linux%20%3E%3D%204.8.0%3A%20http%3A//www.kernel.org/%5Cr%5Cn%2B%2A%20iproute2%20%3E%3D%204.8.0%3A%20https%3A//www.kernel.org/pub/linux/utils/net/iproute2/%5Cr%5Cn%2B%2A%20clang%2BLLVM%20%3E%3D3.7.1%3A%20http%3A//llvm.org/releases%5Cr%5Cn%20%5Cr%5Cn%20Cilium%20can%20make%20use%20of%20additional%20functionality%20available%20in%20%3E%3D%204.9%20kernels.%20It%5Cr%5Cn%20will%20probe%20for%20the%20availability%20upon%20startup%20and%20enable%20it%20automatically.%5Cr%5Cn%20Development%20snapshots%20of%20the%20Linux%20kernel%20and%20iproute2%20tree%20can%20be%20found%20here%3A%5Cr%5Cn-%20%2A%20https%3A//git.kernel.org/cgit/linux/kernel/git/davem/net-next.git%5Cr%5Cn-%20%2A%20https%3A//git.kernel.org/cgit/linux/kernel/git/shemminger/iproute2.git%5Cr%5Cn%2B%2A%20https%3A//git.kernel.org/cgit/linux/kernel/git/davem/net-next.git%5Cr%5Cn%2B%2A%20https%3A//git.kernel.org/cgit/linux/kernel/git/shemminger/iproute2.git%5Cr%5Cn%20%5Cr%5Cn%20Alternatively%2C%20the%20vagrant%20box%20%60noironetworks/net-next%60%20is%20built%20regularly%5Cr%5Cn%20and%20provides%20the%20above%20branches%20compiled%20and%20pre-installed.%20See%20the%5Cr%5Cn%60%60%60%22%2C%20%22created_at%22%3A%20%222017-03-23T17%3A14%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/925044%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/scanf%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3E%20Looks%20good%20to%20me.%20Had%20to%20make%20some%20minor%20changes%20to%20build%20make%20html%20without%5Cr%5Cn%3E%20errors.%20Have%20you%20thought%20about%20using%20a%20different%20theme%3F%20It%20might%20look%20better%20with%20more%20color%2C%20IMO.%5Cr%5Cn%5Cr%5CnThanks%20for%20the%20update.%20I%20haven%27t%20putting%20any%20thought%20into%20the%20theme%20yet.%20Suggestions%20welcome.%22%2C%20%22created_at%22%3A%20%222017-03-23T17%3A26%3A42Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1417913%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tgraf%22%7D%7D%2C%20%7B%22body%22%3A%20%22The%20one%20used%20by%20%5BRead%20the%20Docs%5D%28https%3A//prototype-kernel.readthedocs.io/en/latest/index.html%29%20looks%20good.%22%2C%20%22created_at%22%3A%20%222017-03-25T12%3A20%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/925044%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/scanf%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3E%20The%20one%20used%20by%20Read%20the%20Docs%20looks%20good.%5Cr%5Cn%5Cr%5Cnhttp%3A//cilium.readthedocs.io/en/latest/%5Cr%5Cn%5Cr%5Cnalready%20exists.%20We%20just%20have%20to%20push%20everything%20and%20fix%20up%20the%20styling.%20Dan%20is%20currently%20reworking%20the%20docs.%20I%27ll%20point%20him%20to%20your%20suggested%20changes%20as%20well.%5Cr%5Cn%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222017-03-25T18%3A28%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1417913%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tgraf%22%7D%7D%2C%20%7B%22body%22%3A%20%22On%20Sat%2C%20Mar%2025%2C%202017%20at%2011%3A28%3A23AM%20-0700%2C%20Thomas%20Graf%20wrote%3A%5Cn%3E%20%5Cn%3E%20already%20exists.%20We%20just%20have%20to%20push%20everything%20and%20fix%20up%20the%5Cn%3E%20styling.%20Dan%20is%20currently%20reworking%20the%20docs.%20I%27ll%20point%20him%20to%20your%5Cn%3E%20suggested%20changes%20as%20well.%5Cn%3E%5Cnawesome.%20Fixing%20the%20PDF%20rendering%20would%20be%20very%20nice%20for%20printing.%5Cn%22%2C%20%22created_at%22%3A%20%222017-03-25T19%3A11%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/925044%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/scanf%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/cilium/cilium/pull/378#issuecomment-288792955'>General Comment</a></b>
- <a href='https://github.com/scanf'></a> Looks good to me. Had to make some minor changes to build `make html`  without
errors. Have you thought about using a different theme? [It](https://alemayhu.com/download/cilium/) might look better with more color, IMO.
```bash
$ cd Documentation
$ mdkir _static
$ git diff
```
```diff
diff --git a/Documentation/index.rst b/Documentation/index.rst
index 0ab6c3ed2010..33cc4a3e9a5a 100644
--- a/Documentation/index.rst
+++ b/Documentation/index.rst
@@ -17,6 +17,8 @@ Welcome to Cilium's documentation!
installation
integrations
contributing
+   commit-access
+   roadmap
Indices and tables
==================
diff --git a/Documentation/installation.rst b/Documentation/installation.rst
index 18aca0827c64..f59491945739 100644
--- a/Documentation/installation.rst
+++ b/Documentation/installation.rst
@@ -17,15 +17,15 @@ Prerequisites
Cilium requires a recent version of the Linux kernel, iproute2 and clang+LLVM.
All required changes have been merged upstream and are available in official
releases:
- * Linux >= 4.8.0: http://www.kernel.org/
- * iproute2 >= 4.8.0: https://www.kernel.org/pub/linux/utils/net/iproute2/
- * clang+LLVM >=3.7.1: http://llvm.org/releases
+* Linux >= 4.8.0: http://www.kernel.org/
+* iproute2 >= 4.8.0: https://www.kernel.org/pub/linux/utils/net/iproute2/
+* clang+LLVM >=3.7.1: http://llvm.org/releases
Cilium can make use of additional functionality available in >= 4.9 kernels. It
will probe for the availability upon startup and enable it automatically.
Development snapshots of the Linux kernel and iproute2 tree can be found here:
- * https://git.kernel.org/cgit/linux/kernel/git/davem/net-next.git
- * https://git.kernel.org/cgit/linux/kernel/git/shemminger/iproute2.git
+* https://git.kernel.org/cgit/linux/kernel/git/davem/net-next.git
+* https://git.kernel.org/cgit/linux/kernel/git/shemminger/iproute2.git
Alternatively, the vagrant box `noironetworks/net-next` is built regularly
and provides the above branches compiled and pre-installed. See the
```
- <a href='https://github.com/tgraf'></a> > Looks good to me. Had to make some minor changes to build make html without
> errors. Have you thought about using a different theme? It might look better with more color, IMO.
Thanks for the update. I haven't putting any thought into the theme yet. Suggestions welcome.
- <a href='https://github.com/scanf'></a> The one used by [Read the Docs](https://prototype-kernel.readthedocs.io/en/latest/index.html) looks good.
- <a href='https://github.com/tgraf'></a> > The one used by Read the Docs looks good.
http://cilium.readthedocs.io/en/latest/
already exists. We just have to push everything and fix up the styling. Dan is currently reworking the docs. I'll point him to your suggested changes as well.
- <a href='https://github.com/scanf'></a> On Sat, Mar 25, 2017 at 11:28:23AM -0700, Thomas Graf wrote:
>
> already exists. We just have to push everything and fix up the
> styling. Dan is currently reworking the docs. I'll point him to your
> suggested changes as well.
>
awesome. Fixing the PDF rendering would be very nice for printing.

<a href='https://www.codereviewhub.com/cilium/cilium/pull/378?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/cilium/cilium/pull/378?approve=1'></a>&nbsp;<a href='https://github.com/cilium/cilium/pull/378'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by aanm** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/cilium/cilium/pull/378'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by aalemayhu** [comment]
Looks good to me. Had to make some minor changes to build `make html`  without
errors. Have you thought about using a different theme? [It](https://alemayhu.com/download/cilium/) might look better with more color, IMO.

```bash
$ cd Documentation
$ mdkir _static
$ git diff
```
```diff
diff --git a/Documentation/index.rst b/Documentation/index.rst
index 0ab6c3ed2010..33cc4a3e9a5a 100644
--- a/Documentation/index.rst
+++ b/Documentation/index.rst
@@ -17,6 +17,8 @@ Welcome to Cilium's documentation!
    installation
    integrations
    contributing
+   commit-access
+   roadmap
 
 Indices and tables
 ==================
diff --git a/Documentation/installation.rst b/Documentation/installation.rst
index 18aca0827c64..f59491945739 100644
--- a/Documentation/installation.rst
+++ b/Documentation/installation.rst
@@ -17,15 +17,15 @@ Prerequisites
 Cilium requires a recent version of the Linux kernel, iproute2 and clang+LLVM.
 All required changes have been merged upstream and are available in official
 releases:
- * Linux >= 4.8.0: http://www.kernel.org/
- * iproute2 >= 4.8.0: https://www.kernel.org/pub/linux/utils/net/iproute2/
- * clang+LLVM >=3.7.1: http://llvm.org/releases
+* Linux >= 4.8.0: http://www.kernel.org/
+* iproute2 >= 4.8.0: https://www.kernel.org/pub/linux/utils/net/iproute2/
+* clang+LLVM >=3.7.1: http://llvm.org/releases
 
 Cilium can make use of additional functionality available in >= 4.9 kernels. It
 will probe for the availability upon startup and enable it automatically.
 Development snapshots of the Linux kernel and iproute2 tree can be found here:
- * https://git.kernel.org/cgit/linux/kernel/git/davem/net-next.git
- * https://git.kernel.org/cgit/linux/kernel/git/shemminger/iproute2.git
+* https://git.kernel.org/cgit/linux/kernel/git/davem/net-next.git
+* https://git.kernel.org/cgit/linux/kernel/git/shemminger/iproute2.git
 
 Alternatively, the vagrant box `noironetworks/net-next` is built regularly
 and provides the above branches compiled and pre-installed. See the
```

**Comment by tgraf** [comment]
> Looks good to me. Had to make some minor changes to build make html without
> errors. Have you thought about using a different theme? It might look better with more color, IMO.

Thanks for the update. I haven't putting any thought into the theme yet. Suggestions welcome.

**Comment by aalemayhu** [comment]
The one used by [Read the Docs](https://prototype-kernel.readthedocs.io/en/latest/index.html) looks good.

**Comment by tgraf** [comment]
> The one used by Read the Docs looks good.

http://cilium.readthedocs.io/en/latest/

already exists. We just have to push everything and fix up the styling. Dan is currently reworking the docs. I'll point him to your suggested changes as well.

**Comment by aalemayhu** [comment]
On Sat, Mar 25, 2017 at 11:28:23AM -0700, Thomas Graf wrote:
> 
> already exists. We just have to push everything and fix up the
> styling. Dan is currently reworking the docs. I'll point him to your
> suggested changes as well.
>
awesome. Fixing the PDF rendering would be very nice for printing.

**Pull request merged**
