### PR TITLE
test: Enable IPv6 BPF masquerading for upgrade tests

### PR DESCRIPTION
**Pull request by qmonnet**
Now that Cilium v1.14, with support for IPv6 BPF masquerading, has been released, we can enable IPv6 BPF masquerading in the upgrade tests, and lift the restriction introduced in commit d6f4c53ba443.

To do that, we first need to update the version from which we upgrade: It's time to test upgrades from 1.14 in the CI.

### CODE REVIEW

**Review by aanm — CHANGES_REQUESTED** [review]
Thanks for the PR but I think it's a no-op since the changes were part of https://github.com/cilium/cilium/pull/27114?

**Comment by qmonnet** [comment]
Yes. I missed that other PR when opening mine. Thanks!

**Pull request closed without merging**
