### PR TITLE
bpf: lb: clean up IPv4 loopback handling

### PR DESCRIPTION
**Pull request by julianwiedmann**
`bpf_host`, `bpf_overlay` and `bpf_xdp` are compiled by the agent with `DISABLE_LOOPBACK_LB`, to exclude the IPv4 loopback handling from their nodeport LB code paths.

Apply this fact across
- the BPF complexity tests, so that we test the programs in their actual configuration
- the BPF compile tests, so that we catch issues with/without DISABLE_LOOPBACK_LB
- the LB and CT code, so that we include less code in the nodeport paths

### CODE REVIEW

**Comment by julianwiedmann** [comment]
Some random [before](https://github.com/cilium/cilium/actions/runs/4978435586/jobs/8908751929)/[after](https://github.com/cilium/cilium/actions/runs/4989467129/jobs/8933439706) observations:

```
=== RUN   TestVerifier/bpf_xdp_1
    ...
    verifier_test.go:202: tail_lb_ipv4: processed 23163 insns (limit 131072), stack depth 200
vs
    verifier_test.go:202: tail_lb_ipv4: processed 14288 insns (limit 131072), stack depth 200

=== RUN   TestVerifier/bpf_overlay_1
    ...
    verifier_test.go:202: tail_handle_ipv4: processed 19571 insns (limit 131072), stack depth 240
vs
    verifier_test.go:202: tail_handle_ipv4: processed 12838 insns (limit 131072), stack depth 224

=== RUN   TestVerifier/bpf_host_1
    ...
    verifier_test.go:202: tail_handle_ipv4_from_netdev: processed 40760 insns (limit 131072), stack depth 264
vs
    verifier_test.go:202: tail_handle_ipv4_from_netdev: processed 25143 insns (limit 131072), stack depth 232
```

**Review by ldelossa — APPROVED** [review]
Approved, contingent on a small nit with the conditional changing of structure field layout. 

Discussed out of bound with Julian.

**Comment by julianwiedmann** [comment]
> Approved, contingent on a small nit with the conditional changing of structure field layout.
> 
> Discussed out of bound with Julian.

-> pushed https://github.com/cilium/cilium/compare/980808a212338add90c7c1b34993a761b880930a..9a39a1c1731cc949e89a44946df7181b18701d89
(and rebased afterwards to pick up some CI improvements)

**Comment by julianwiedmann** [comment]
opened https://github.com/cilium/cilium/issues/25522 for the runtime flake

**Comment by julianwiedmann** [comment]
Jumping in for mlh, opened https://github.com/cilium/cilium/issues/25524 for the net-next flake in https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/2383/testReport/Suite-k8s-1/26/K8sDatapathServicesTest_Checks_N_S_loadbalancing_With_host_policy_Tests_NodePort/

**Comment by julianwiedmann** [comment]
/test-1.26-net-next

**Comment by julianwiedmann** [comment]
Same thing on IPv6: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/2386/testReport/Suite-k8s-1/26/K8sDatapathServicesTest_Checks_N_S_loadbalancing_With_host_policy_Tests_NodePort/

**Comment by julianwiedmann** [comment]
/test-1.26-net-next

**Pull request merged**
