### PR TITLE
make: Fix indentation in start-kvstores section

### PR DESCRIPTION
**Pull request by vadorovsky**
Makefiles should indent only with tabs.

Signed-off-by: Michal Rostecki <mrostecki@suse.de>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6344)

### CODE REVIEW

**Comment by vadorovsky** [comment]
test-me-please

**Comment by ianvernon** [comment]
CI failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8331/testReport/junit/k8s-1/8/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/

This is the same issue as found in 
https://github.com/cilium/cilium/issues/6307 , which is unrelated to the changes made in this PR.

**Review by ianvernon — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]

**Comment by jrajahalme** [comment]
test-me-please

**Comment by vadorovsky** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
