### PR TITLE
selectorcache integration testing

### PR DESCRIPTION
**Pull request by ianvernon**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7984)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Upgrade test still failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12245/testReport/junit/Suite-k8s-1/10/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
The L7 request to `app1` failed:

```
time="2019-05-10T23:42:47Z" level=error msg="write ^C error: EOF"
cmd: "kubectl exec -n default app2-5c44ff87c-cdmh7 -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 http://app1-service/public -w \"time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'\"" exitCode: 28 duration: 5.297451692s stdout:
time-> DNS: '0.004090()', Connect: '0.000000',Transfer '0.000000', total '5.001009'
stderr:
command terminated with exit code 28
```

These `write ^C errors` are throughout the log - they appear harmless, though (which is weird). 

The curl command failed. I looked at the logs for the cilium-agent managing that pod (`cilium-fwsn7`). I checked to make sure the map cleanup only occurred after the endpoints were restored, which was the case. The endpoint IDs were 4071, and 813:

```
$ grep "4071\|813" pod-kube-system-cilium-fwsn7-cilium-agent.log | grep -v "subsys=controller\|subsys=endpointsynchronizer\|subsys=loadinfo\|NAME\|subsys=elf\|Load 1-min\|Memory\|List response from etcd\|subsys=kvstore\|subsys=ipam\|GET\|Swap" | grep "Removed stale\|Restored endpoint"
2019-05-10T23:42:25.538436745Z level=info msg="Restored endpoint" endpointID=4071 ipAddr="[10.10.0.16 f00d::a0a:0:0:1312]" subsys=daemon
2019-05-10T23:42:25.941163298Z level=info msg="Restored endpoint" endpointID=813 ipAddr="[10.10.0.137 f00d::a0a:0:0:f4ed]" subsys=daemon
2019-05-10T23:42:25.944251089Z level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_calls_4071 subsys=datapath-maps
2019-05-10T23:42:25.94509399Z level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_calls_813 subsys=datapath-maps
2019-05-10T23:42:25.949807387Z level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_ep_config_4071 subsys=datapath-maps
2019-05-10T23:42:25.950066794Z level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_ep_config_813 subsys=datapath-maps
2019-05-10T23:42:25.954584436Z level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_policy_4071 subsys=datapath-maps
2019-05-10T23:42:25.954591023Z level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_policy_813 subsys=datapath-maps
```

I then checked the logs at the time the request was made to see if anything interesting was happening. At the exact same time, the app1-service definition changed? 

```
2019-05-10T23:42:47.235032798Z level=debug msg="Kubernetes service definition changed" action=service-updated endpoints= k8sNamespace=default k8sSvcName=app1-service service="frontend:10.99.63.200/ports=[]/selector=map[id:app1]" subsys=daemon
2019-05-10T23:42:47.235566525Z level=debug msg="created new L3n4Addr" ipAddr="{10.99.63.200 {TCP 80}}" subsys=loadbalancer
2019-05-10T23:42:47.235655741Z level=debug msg="adding service" obj="[]" serviceID="10.99.63.200:80" subsys=daemon
2019-05-10T23:42:47.235729987Z level=debug msg="converting Cilium load-balancer service (frontend -> backend(s)) into BPF service" lbBackend="[]" lbFrontend="10.99.63.200:80" subsys=map-lb
2019-05-10T23:42:47.235778794Z level=debug msg="converting L3n4Addr to ServiceKey" l3n4AddrID="{{10.99.63.200 {TCP 80}} 4}" subsys=map-lb
2019-05-10T23:42:47.235832113Z level=debug msg="converted LBSVC (frontend -> backend(s)), to Service Key and Value" lbBackend="[]" lbFrontend="10.99.63.200:80" obj="[]" serviceID="10.99.63.200:80" subsys=map-lb
2019-05-10T23:42:47.235965819Z level=debug msg="converting Cilium load-balancer service (frontend -> backend(s)) into BPF service v2" lbBackend="[]" lbFrontend="10.99.63.200:80" subsys=map-lb
2019-05-10T23:42:47.236007623Z level=debug msg="converting L3n4Addr to ServiceKeyV2" l3n4AddrID="{{10.99.63.200 {TCP 80}} 4}" subsys=map-lb
2019-05-10T23:42:47.23650012Z level=debug msg="converted LBSVC (frontend -> backend(s)), to ServiceKeyV2, ServiceValueV2 and Backend" lbBackend="[]" lbFrontend="10.99.63.200:80" obj="[]" serviceID="10.99.63.200:80" subsys=map-lb
2019-05-10T23:42:47.236577094Z level=debug msg="adding service to BPF maps" serviceName="10.99.63.200:80" subsys=daemon
2019-05-10T23:42:47.236761684Z level=debug msg="Updating BPF representation of service" backends="map[]" frontend="10.99.63.200:80" subsys=map-lb
2019-05-10T23:42:47.239284213Z level=debug msg="adding frontend for backend to BPF maps" backend="0.0.0.0:0 (0)" frontend="10.99.63.200:80" subsys=map-lb
2019-05-10T23:42:47.239486276Z level=debug msg="adding revNat to lbmap" bpfMapKey=4 bpfMapValue="10.99.63.200:80" subsys=map-lb
2019-05-10T23:42:47.239829625Z level=debug msg="Upserting service entry" slaveSlot=0 subsys=map-lb svcKey="10.99.63.200:80" svcVal="0 (4)"
2019-05-10T23:42:47.24004048Z level=debug msg="Deleted service entry" slaveSlot=1 subsys=map-lb svcKey="10.99.63.200:80"
2019-05-10T23:42:47.240141536Z level=debug msg="Deleted backend" backendID=10 subsys=map-lb
2019-05-10T23:42:47.240194829Z level=debug msg="adding service to RevNATMap" serviceName="10.99.63.200:80" subsys=daemon
2019-05-10T23:42:47.240253172Z level=debug msg="service is already in lb.SVCMapID; deleting old entry and updating it with new entry" serviceName="10.99.63.200:80" sha=3d72539ce55e7e9c6efe2aaa883270c510c219651963551d66e25d1c831412b6 subsys=loadbalancer
2019-05-10T23:42:47.240302378Z level=debug msg="adding service to loadbalancer" serviceName="10.99.63.200:80" sha=3d72539ce55e7e9c6efe2aaa883270c510c219651963551d66e25d1c831412b6 subsys=loadbalancer
```

This looks highly suspicious - and given that the connection is to the service, I think this warrants investigation.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Follow-up from debugging today. I noticed that on my local setup with K8s-1.10, I was running with the 4.9 Kernel. The CI uses the net-next kernel. I destroyed my local setup, and reprovisioned with the net-next kernel. I was able to reproduce the failure:

```
$ cd test/
$ K8S_VERSION=1.10 NETNEXT=true vagrant up k8s1-1.10 ;  K8S_VERSION=1.10 NETNEXT=true vagrant up k8s2-1.10
...
$ NETNEXT=true K8S_VERSION=1.10 ginkgo --focus=" K8sUpdates*" -v  -- -cilium.provision=false -cilium.holdEnvironment=true  -cilium.skipLogs=true
Running Suite: Suite-k8s-1.10
=============================
Random Seed: 1557783278
Will run 1 of 375 specs

SSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
K8sUpdates 
  Tests upgrade and downgrade from a Cilium stable image to master
  /Users/ianvernon/go/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
STEP: Installing a cleaning state of Cilium
STEP: Installing kube-dns
STEP: Deploying etcd-operator
STEP: Cilium "v1.4" is installed and running
STEP: Performing Cilium preflight check
STEP: Installing Cilium-Operator
STEP: Waiting for all etcd-operator pods are ready
STEP: Installing Microscope
STEP: Creating some endpoints and L7 policy
STEP: Creating service and clients for migration
STEP: Validate that endpoints are ready before making any connection
STEP: Making L7 requests between endpoints
STEP: No interrupts in migrated svc flows
STEP: Install Cilium pre-flight check DaemonSet
STEP: Waiting for all cilium pre-flight pods to be ready
STEP: Removing Cilium pre-flight check DaemonSet
STEP: Deploying compiled version of Cilium
STEP: Installing Cilium-Operator
STEP: Checking that installed image is "k8s1:5000/cilium/cilium-dev:latest"
STEP: Performing Cilium preflight check
STEP: Validate that endpoints are ready before making any connection
STEP: Making L7 requests between endpoints

---
K8sUpdates Tests upgrade and downgrade from a Cilium stable image to master
at /Users/ianvernon/go/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410

[Cannot curl app1-service
Expected command: kubectl exec -n default app2-5c44ff87c-npbwk -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 http://app1-service/public -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.014880()', Connect: '0.000000',Transfer '0.000000', total '5.001982'
Stderr:
 	 command terminated with exit code 28
	 
]

Pausing test for debug, use vagrant to access test setup.
Run "kill -SIGCONT 54819" to continue.
```

App1 pods are Running, but not Ready:

```
$ kubectl describe pod app1-6f5f7bd649-c7fdc
...
Events:
  Type     Reason     Age                From           Message
  ----     ------     ----               ----           -------
  Warning  Unhealthy  2m (x458 over 1h)  kubelet, k8s1  Readiness probe failed: Get http://10.10.0.173:80/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

Running the monitor for the corresponding cilium endpoint shows drops:

```
-> proxy flow 0x3a4ae38a identity 1->17671 state new ifindex lxcaf5fc40205a4: 10.10.0.1:34198 -> 10.10.0.173:80 tcp SYN
-> proxy port 13319: 10.10.0.1:34198 -> 10.10.0.173:80 tcp SYN
-> proxy flow 0x3a4ae38a identity 1->17671 state established ifindex lxcaf5fc40205a4: 10.10.0.1:34198 -> 10.10.0.173:80 tcp ACK
-> proxy port 13319: 10.10.0.1:34198 -> 10.10.0.173:80 tcp ACK
-> proxy flow 0x3a4ae38a identity 1->17671 state established ifindex lxcaf5fc40205a4: 10.10.0.1:34198 -> 10.10.0.173:80 tcp ACK
-> proxy port 13319: 10.10.0.1:34198 -> 10.10.0.173:80 tcp ACK
<- Request http from 0 ([reserved:host]) to 580 ([k8s:id=app1 k8s:io.cilium.k8s.policy.serviceaccount=app1-account k8s:io.kubernetes.pod.namespace=default k8s:zgroup=testapp k8s:io.cilium.k8s.policy.cluster=default]), identity 1->17671, verdict Forwarded GET http://10.10.0.173/ => 0
xx drop (Policy denied (L3)) flow 0x3e3da7c9 to endpoint 580, identity 2->17671: 10.0.2.15:36590 -> 10.10.0.173:80 tcp SYN
xx drop (Policy denied (L3)) flow 0xe90d8edf to endpoint 580, identity 2->17671: 10.0.2.15:36596 -> 10.10.0.173:80 tcp SYN
xx drop (Policy denied (L3)) flow 0xd04b045e to endpoint 580, identity 2->17671: 10.0.2.15:36598 -> 10.10.0.173:80 tcp SYN
```

The ingress to the proxy looks fine - it is forwarded. But, there are drops showing identity as 'world' (identity 2) for the IP 10.0.2.15.

I have some verbose monitor output as well:

```
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: 66 bytes, Packet to proxy port 13319 (Post)
Ethernet	{Contents=[..14..] Payload=[..54..] SrcMAC=ee:08:53:79:39:cb DstMAC=12:b8:63:d7:4a:8c EthernetType=IPv4 Length=0}
IPv4	{Contents=[..20..] Payload=[..32..] Version=4 IHL=5 TOS=0 Length=52 Id=37635 Flags=DF FragOffset=0 TTL=63 Protocol=TCP Checksum=37887 SrcIP=10.10.0.1 DstIP=10.10.0.173 Options=[] Padding=[]}
TCP	{Contents=[..32..] Payload=[] SrcPort=37322 DstPort=80(http) Seq=3527223397 Ack=3778395669 DataOffset=8 FIN=false SYN=false RST=false PSH=false ACK=true URG=false ECE=false CWR=false NS=false Window=502 Checksum=5352 Urgent=0 Options=[TCPOption(NOP:), TCPOption(NOP:), TCPOption(Timestamps:2293221495/718171789 0x88afc8772ace6e8d)] Padding=[]}
CPU 01: MARK 0x8b298fcb FROM 580 DEBUG: Skipping proxy, tc_index is set=1
CPU 01: MARK 0x8b298fcb FROM 580 DEBUG: Conntrack lookup 1/2: src=10.0.2.15:39714 dst=10.10.0.173:80
CPU 01: MARK 0x8b298fcb FROM 580 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 01: MARK 0x8b298fcb FROM 580 DEBUG: CT verdict: New, revnat=0
CPU 01: MARK 0x8b298fcb FROM 580 DEBUG: Policy evaluation would deny packet from 2 to 17671
------------------------------------------------------------------------------
CPU 01: MARK 0x8b298fcb FROM 580 DROP: 74 bytes, reason Policy denied (L3), identity 2->17671, to endpoint 580
Ethernet	{Contents=[..14..] Payload=[..62..] SrcMAC=ee:08:53:79:39:cb DstMAC=12:b8:63:d7:4a:8c EthernetType=IPv4 Length=0}
IPv4	{Contents=[..20..] Payload=[..40..] Version=4 IHL=5 TOS=0 Length=60 Id=9620 Flags=DF FragOffset=0 TTL=63 Protocol=TCP Checksum=65378 SrcIP=10.0.2.15 DstIP=10.10.0.173 Options=[] Padding=[]}
TCP	{Contents=[..40..] Payload=[] SrcPort=39714 DstPort=80(http) Seq=2249629427 Ack=0 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=64240 Checksum=5876 Urgent=0 Options=[..5..] Padding=[]}
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: Conntrack lookup 1/2: src=10.10.0.1:37322 dst=10.10.0.173:80
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: CT entry found lifetime=28645, revnat=0
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: CT verdict: Established, revnat=0
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: Matched L4 policy; creating conntrack src=1 dst=17671 dport=80 proto=6
------------------------------------------------------------------------------
CPU 01: MARK 0xc0695e28 FROM 580 to-proxy: 177 bytes (128 captured), state established, interface lxcaf5fc40205a4, identity 1->17671
Ethernet	{Contents=[..14..] Payload=[..118..] SrcMAC=ee:08:53:79:39:cb DstMAC=12:b8:63:d7:4a:8c EthernetType=IPv4 Length=0}
IPv4	{Contents=[..20..] Payload=[..98..] Version=4 IHL=5 TOS=0 Length=163 Id=37636 Flags=DF FragOffset=0 TTL=63 Protocol=TCP Checksum=37775 SrcIP=10.10.0.1 DstIP=10.10.0.173 Options=[] Padding=[]}
TCP	{Contents=[..32..] Payload=[..66..] SrcPort=37322 DstPort=80(http) Seq=3527223397 Ack=3778395669 DataOffset=8 FIN=false SYN=false RST=false PSH=true ACK=true URG=false ECE=false CWR=false NS=false Window=502 Checksum=5463 Urgent=0 Options=[TCPOption(NOP:), TCPOption(NOP:), TCPOption(Timestamps:2293221495/718171789 0x88afc8772ace6e8d)] Padding=[]}
  Packet has been truncated
------------------------------------------------------------------------------
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: 177 bytes, Packet to proxy port 13319 (Post)
Ethernet	{Contents=[..14..] Payload=[..118..] SrcMAC=ee:08:53:79:39:cb DstMAC=12:b8:63:d7:4a:8c EthernetType=IPv4 Length=0}
IPv4	{Contents=[..20..] Payload=[..98..] Version=4 IHL=5 TOS=0 Length=163 Id=37636 Flags=DF FragOffset=0 TTL=63 Protocol=TCP Checksum=37775 SrcIP=10.10.0.1 DstIP=10.10.0.173 Options=[] Padding=[]}
TCP	{Contents=[..32..] Payload=[..66..] SrcPort=37322 DstPort=80(http) Seq=3527223397 Ack=3778395669 DataOffset=8 FIN=false SYN=false RST=false PSH=true ACK=true URG=false ECE=false CWR=false NS=false Window=502 Checksum=5463 Urgent=0 Options=[TCPOption(NOP:), TCPOption(NOP:), TCPOption(Timestamps:2293221495/718171789 0x88afc8772ace6e8d)] Padding=[]}
  Packet has been truncated
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: Conntrack lookup 1/2: src=10.10.0.1:37322 dst=10.10.0.173:80
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: CT entry found lifetime=28645, revnat=0
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: CT verdict: Established, revnat=0
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: Matched L4 policy; creating conntrack src=1 dst=17671 dport=80 proto=6
------------------------------------------------------------------------------
CPU 01: MARK 0xc0695e28 FROM 580 to-proxy: 66 bytes (66 captured), state established, interface lxcaf5fc40205a4, identity 1->17671
Ethernet	{Contents=[..14..] Payload=[..54..] SrcMAC=ee:08:53:79:39:cb DstMAC=12:b8:63:d7:4a:8c EthernetType=IPv4 Length=0}
IPv4	{Contents=[..20..] Payload=[..32..] Version=4 IHL=5 TOS=0 Length=52 Id=37637 Flags=DF FragOffset=0 TTL=63 Protocol=TCP Checksum=37885 SrcIP=10.10.0.1 DstIP=10.10.0.173 Options=[] Padding=[]}
TCP	{Contents=[..32..] Payload=[] SrcPort=37322 DstPort=80(http) Seq=3527223508 Ack=3778395669 DataOffset=8 FIN=true SYN=false RST=false PSH=false ACK=true URG=false ECE=false CWR=false NS=false Window=502 Checksum=5352 Urgent=0 Options=[TCPOption(NOP:), TCPOption(NOP:), TCPOption(Timestamps:2293222495/718171789 0x88afcc5f2ace6e8d)] Padding=[]}
------------------------------------------------------------------------------
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: 66 bytes, Packet to proxy port 13319 (Post)
Ethernet	{Contents=[..14..] Payload=[..54..] SrcMAC=ee:08:53:79:39:cb DstMAC=12:b8:63:d7:4a:8c EthernetType=IPv4 Length=0}
IPv4	{Contents=[..20..] Payload=[..32..] Version=4 IHL=5 TOS=0 Length=52 Id=37637 Flags=DF FragOffset=0 TTL=63 Protocol=TCP Checksum=37885 SrcIP=10.10.0.1 DstIP=10.10.0.173 Options=[] Padding=[]}
TCP	{Contents=[..32..] Payload=[] SrcPort=37322 DstPort=80(http) Seq=3527223508 Ack=3778395669 DataOffset=8 FIN=true SYN=false RST=false PSH=false ACK=true URG=false ECE=false CWR=false NS=false Window=502 Checksum=5352 Urgent=0 Options=[TCPOption(NOP:), TCPOption(NOP:), TCPOption(Timestamps:2293222495/718171789 0x88afcc5f2ace6e8d)] Padding=[]}
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: Conntrack lookup 1/2: src=10.10.0.1:37322 dst=10.10.0.173:80
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: CT entry found lifetime=28646, revnat=0
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: CT verdict: Established, revnat=0
CPU 01: MARK 0xc0695e28 FROM 580 DEBUG: Matched L4 policy; creating conntrack src=1 dst=17671 dport=80 proto=6
```

So, the packet is getting marked as from 'world' after being processed by the proxy, but it isn't conclusive right now as to why. I checked this by trying to allow ingress to world via the following policy:

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "L7 policy for getting started using Kubernetes guide"
metadata:
  name: "l7-policy-2"
spec:
  endpointSelector:
    matchLabels:
      id: app1
  ingress:
  - fromEntities:
    - world
```

And the health checks started succeeding. I am going to check the monitor output for master on net-next / K8s 1.10, as well as this branch against the 4.9 kernel and K8s 1.10 and compare it against the above cases where it is denied. It isn't clear why the datapath behavior would change with this PR. It is possible that something getting configured on the proxy side is messed up?

**Comment by ianvernon** [comment]
When running the test against master, the PolicyMap state is different; there is no L4 policy at port 80 for the host:

```
root@k8s1:~# cilium bpf policy get 114 --numeric
DIRECTION   IDENTITY   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
Ingress     1          ANY          NONE         14305   165       
Ingress     18577      80/TCP       10197        0       0         
Egress      1          ANY          NONE         17042   128    
```

So, the traffic for the host is not redirected to the proxy for the readiness probe from kubelet. No denies due to policy are in the monitor output.

**Comment by ianvernon** [comment]
When running the branch locally against the 4.9 kernel, the healthcheck passes.

Monitor output:

```
<- endpoint 2501 flow 0x140496f identity 7507->0 state new ifindex 0: 10.10.0.137:80 -> 10.0.2.15:59380 tcp ACK, FIN
-> stack flow 0x140496f identity 7507->2 state reply ifindex 0: 10.10.0.137:80 -> 10.0.2.15:59380 tcp ACK, FIN
-> 0: 10.10.0.137:80 -> 10.0.2.15:59380 tcp ACK, FIN
-> endpoint 2501 flow 0x4738abe identity 1->7507 state established ifindex lxc082e9330f15f: 10.0.2.15:59380 -> 10.10.0.137:80 tcp ACK
<- endpoint 2501 flow 0xb077b41 identity 7507->0 state new ifindex 0: 10.10.0.137:80 -> 10.0.2.15:59368 tcp ACK, FIN
-> stack flow 0xb077b41 identity 7507->2 state reply ifindex 0: 10.10.0.137:80 -> 10.0.2.15:59368 tcp ACK, FIN
-> 0: 10.10.0.137:80 -> 10.0.2.15:59368 tcp ACK, FIN
-> endpoint 2501 flow 0x740799b identity 1->7507 state established ifindex lxc082e9330f15f: 10.0.2.15:59368 -> 10.10.0.137:80 tcp ACK
-> proxy flow 0x3e826fab identity 1->7507 state new ifindex lxc082e9330f15f: 10.10.0.1:36968 -> 10.10.0.137:80 tcp SYN
-> proxy port 19596: 10.10.0.1:36968 -> 10.10.0.137:80 tcp SYN
-> proxy flow 0x3e826fab identity 1->7507 state established ifindex lxc082e9330f15f: 10.10.0.1:36968 -> 10.10.0.137:80 tcp ACK
-> proxy port 19596: 10.10.0.1:36968 -> 10.10.0.137:80 tcp ACK
-> proxy flow 0x3e826fab identity 1->7507 state established ifindex lxc082e9330f15f: 10.10.0.1:36968 -> 10.10.0.137:80 tcp ACK
-> proxy port 19596: 10.10.0.1:36968 -> 10.10.0.137:80 tcp ACK
-> endpoint 2501 flow 0x5930f1b2 identity 1->7507 state new ifindex lxc082e9330f15f: 10.0.2.15:59408 -> 10.10.0.137:80 tcp SYN
<- endpoint 2501 flow 0x442d21f7 identity 7507->0 state new ifindex 0: 10.10.0.137:80 -> 10.0.2.15:59408 tcp SYN, ACK
-> stack flow 0x442d21f7 identity 7507->2 state reply ifindex 0: 10.10.0.137:80 -> 10.0.2.15:59408 tcp SYN, ACK
-> 0: 10.10.0.137:80 -> 10.0.2.15:59408 tcp SYN, ACK
-> endpoint 2501 flow 0x5930f1b2 identity 1->7507 state established ifindex lxc082e9330f15f: 10.0.2.15:59408 -> 10.10.0.137:80 tcp ACK
-> endpoint 2501 flow 0x5930f1b2 identity 1->7507 state established ifindex lxc082e9330f15f: 10.0.2.15:59408 -> 10.10.0.137:80 tcp ACK
<- endpoint 2501 flow 0x442d21f7 identity 7507->0 state new ifindex 0: 10.10.0.137:80 -> 10.0.2.15:59408 tcp ACK
-> stack flow 0x442d21f7 identity 7507->2 state reply ifindex 0: 10.10.0.137:80 -> 10.0.2.15:59408 tcp ACK
-> 0: 10.10.0.137:80 -> 10.0.2.15:59408 tcp ACK
-> endpoint 2501 flow 0x5930f1b2 identity 1->7507 state established ifindex lxc082e9330f15f: 10.0.2.15:59408 -> 10.10.0.137:80 tcp ACK
-> proxy flow 0x3e826fab identity 1->7507 state established ifindex lxc082e9330f15f: 10.10.0.1:36968 -> 10.10.0.137:80 tcp ACK
-> proxy port 19596: 10.10.0.1:36968 -> 10.10.0.137:80 tcp ACK
-> proxy flow 0x3e826fab identity 1->7507 state established ifindex lxc082e9330f15f: 10.10.0.1:36968 -> 10.10.0.137:80 tcp ACK, FIN
-> proxy port 19596: 10.10.0.1:36968 -> 10.10.0.137:80 tcp ACK, FIN
-> proxy flow 0x3e826fab identity 1->7507 state established ifindex lxc082e9330f15f: 10.10.0.1:36968 -> 10.10.0.137:80 tcp ACK
-> proxy port 19596: 10.10.0.1:36968 -> 10.10.0.137:80 tcp ACK
<- endpoint 2501 flow 0x442d21f7 identity 7507->0 state new ifindex 0: 10.10.0.137:80 -> 10.0.2.15:59408 tcp ACK
-> stack flow 0x442d21f7 identity 7507->2 state reply ifindex 0: 10.10.0.137:80 -> 10.0.2.15:59408 tcp ACK
-> 0: 10.10.0.137:80 -> 10.0.2.15:59408 tcp ACK
<- Request http from 0 ([reserved:host]) to 2501 ([k8s:id=app1 k8s:io.cilium.k8s.policy.serviceaccount=app1-account k8s:io.kubernetes.pod.namespace=default k8s:zgroup=testapp k8s:io.cilium.k8s.policy.cluster=default]), identity 1->7507, verdict Forwarded GET http://10.10.0.137:80/ => 0
<- Response http to 0 ([reserved:host]) from 2501 ([k8s:id=app1 k8s:io.cilium.k8s.policy.serviceaccount=app1-account k8s:io.kubernetes.pod.namespace=default k8s:zgroup=testapp k8s:io.cilium.k8s.policy.cluster=default]), identity 1->7507, verdict Forwarded GET http://10.10.0.137:80/ => 200
-> endpoint 2501 flow 0x5930f1b2 identity 1->7507 state established ifindex lxc082e9330f15f: 10.0.2.15:59408 -> 10.10.0.137:80 tcp ACK, FIN
<- endpoint 2501 flow 0x442d21f7 identity 7507->0 state new ifindex 0: 10.10.0.137:80 -> 10.0.2.15:59408 tcp ACK, FIN
-> stack flow 0x442d21f7 identity 7507->2 state reply ifindex 0: 10.10.0.137:80 -> 10.0.2.15:59408 tcp ACK, FIN
-> 0: 10.10.0.137:80 -> 10.0.2.15:59408 tcp ACK, FIN
-> endpoint 2501 flow 0x5930f1b2 identity 1->7507 state established ifindex lxc082e9330f15f: 10.0.2.15:59408 -> 10.10.0.137:80 tcp ACK
<- Request http from 0 ([reserved:host]) to 2501 ([k8s:io.cilium.k8s.policy.cluster=default k8s:id=app1 k8s:io.cilium.k8s.policy.serviceaccount=app1-account k8s:io.kubernetes.pod.namespace=default k8s:zgroup=testapp]), identity 1->7507, verdict Forwarded GET http://10.10.0.137:80/ => 0
<- Response http to 0 ([reserved:host]) from 2501 ([k8s:id=app1 k8s:io.cilium.k8s.policy.serviceaccount=app1-account k8s:io.kubernetes.pod.namespace=default k8s:zgroup=testapp k8s:io.cilium.k8s.policy.cluster=default]), identity 1->7507, verdict Forwarded GET http://10.10.0.137:80/ => 200
-> proxy flow 0xb376702a identity 1->7507 state new ifindex lxc082e9330f15f: 10.10.0.1:37012 -> 10.10.0.137:80 tcp SYN
-> proxy port 19596: 10.10.0.1:37012 -> 10.10.0.137:80 tcp SYN
-> proxy flow 0xb376702a identity 1->7507 state established ifindex lxc082e9330f15f: 10.10.0.1:37012 -> 10.10.0.137:80 tcp ACK
-> proxy port 19596: 10.10.0.1:37012 -> 10.10.0.137:80 tcp ACK
-> endpoint 2501 flow 0x34e4a9d4 identity 1->7507 state new ifindex lxc082e9330f15f: 10.0.2.15:59452 -> 10.10.0.137:80 tcp SYN
<- endpoint 2501 flow 0x5041656b identity 7507->0 state new ifindex 0: 10.10.0.137:80 -> 10.0.2.15:59452 tcp SYN, ACK
-> stack flow 0x5041656b identity 7507->2 state reply ifindex 0: 10.10.0.137:80 -> 10.0.2.15:59452 tcp SYN, ACK
-> 0: 10.10.0.137:80 -> 10.0.2.15:59452 tcp SYN, ACK
```

cc: @jrfastab and @joestringer

**Comment by tgraf** [comment]
> Analyzing this build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12245/testReport/junit/Suite-k8s-1/10/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/

This may be affected by the stale map removal bug which is fixed by #7982. We should rebase and test again.

**Comment by ianvernon** [comment]
@tgraf I cherry-picked the stale-map removal failure commit onto this PR before it was merged, so we are not affected by that here.

**Comment by ianvernon** [comment]
It turns out that if you have L7 policy that applies to the host on ingress, the packets are dropped with newer kernels, even on master; this PR revealed that by synthesizing L7-allow-all on the specific port for the host anyway, which is in line with how we treat other entities as well.

Filed an issue: https://github.com/cilium/cilium/issues/8018

**Comment by ianvernon** [comment]
Closing; this PR has served its purpose :)

**Pull request closed without merging**
