### PR TITLE
[k8s] daemonset scheduling on master node

### PR DESCRIPTION
**Pull request by eloycoto**
Hello! 

This PR added the tolerations needed on Kubernetes 1.7.4. Mainly this adds the option to schedule the cilium DS on the master node. 

On the other hand, I added the tolerations on all uninitialized nodes. These are the same tolerations as Kube-proxy. 

On the tests, this is working due the k8s-1 node is taint to schedule pods. 

Working on my env + tested on a fresh install. 

Regards.

PS: I think that the annotations section can be deleted too, but I was not sure so I keep it.

### CODE REVIEW

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
> PS: I think that the annotations section can be deleted too, but I was not sure so I keep it.

I added them because older Kubernetes versions will not understand the tolerations yet.

**Comment by tgraf** [comment]
@eloycoto Can you rebase and repush so we get a clean CI run?

**Comment by eloycoto** [comment]
@tgraf  shouldn't we have a cilium-ds-1.6.yaml and cilium-1.7.yaml?

**Comment by aanm** [comment]
@eloycoto can you rebase again? @ianvernon fix the CI-bug with PR #1435

**Comment by tgraf** [comment]
> @tgraf shouldn't we have a cilium-ds-1.6.yaml and cilium-1.7.yaml?

Having a single DaemonSet would be ideal and so far that worked OK, but if we can't avoid it then yes.

**Pull request merged**
