### PR TITLE
Cassandra Parser:  Unit tests and fixes for 'batch' requests and 'prepared queries'

### PR DESCRIPTION
**Pull request by danwent**
Adding unit test coverage for some of the more advanced protocol capabilities, including batch requests and prepared queries.   Found and fixed some bugs in those areas.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6167)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]
Not a Cassandra export, though.

**Comment by danwent** [comment]
test-me-please

**Comment by danwent** [comment]
Thanks @jrajahalme  .  I rebased, added two more unit tests, and fixed more more bug (to ensure that "use" queries do not generate a "DROP" response).

**Comment by jrfastab** [comment]
test-me-please

**Pull request merged**
