### PR TITLE
test: fix ClusterIP IPv6 connectivity checks

### LINKED ISSUE #10157: CI: Suite-k8s-1.11.K8sServicesTest Checks ClusterIP Connectivity IPv6 Connectivity Checks service on same node
Potential CI flake in #10153 

### Stacktrace
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
cannot curl to service IP from host
Expected command: kubectl exec -n kube-system log-gatherer-nmsds -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 "tftp://[fd03::100]/hello" -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.000088()', Connect: '0.000137',Transfer '0.000000', total '5.000266'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:277
```
### Standard Output
```
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Cilium pods: [cilium-6kh5z cilium-cf79h]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                        Ingress   Egress
app3-68fb594d47-4v4kd      false     false
app1-78d56bb6bb-kfwvv      false     false
app2-64975875bc-kmg8s      false     false
app3-688574cd6d-7zcm7      false     false
echo-67786d8cc8-gx5bf      false     false
app1-798d4f944d-jcsjg      false     false
app2-dc85b4585-scfwg       false     false
app1-78d56bb6bb-r7pxt      false     false
coredns-687db6485c-b4hp2   false     false
Cilium agent 'cilium-6kh5z': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 33 Failed 0
Cilium agent 'cilium-cf79h': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 21 Failed 0
```
### Standard Error
```
=== Test Finished at 2020-02-12T02:03:49Z====
===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                              READY   STATUS    RESTARTS   AGE   IP              NODE   NOMINATED NODE
	 default             app1-78d56bb6bb-kfwvv             2/2     Running   0          26s   10.10.0.56      k8s1   <none>
	 default             app1-78d56bb6bb-r7pxt             2/2     Running   0          26s   10.10.0.69      k8s1   <none>
	 default             app2-64975875bc-kmg8s             1/1     Running   0          26s   10.10.0.147     k8s1   <none>
	 default             app3-688574cd6d-7zcm7             1/1     Running   0          26s   10.10.0.200     k8s1   <none>
	 default             echo-67786d8cc8-gx5bf             2/2     Running   0          26s   10.10.1.191     k8s2   <none>
	 external-ips-test   app1-798d4f944d-jcsjg             2/2     Running   0          21m   10.10.0.23      k8s1   <none>
	 external-ips-test   app2-dc85b4585-scfwg              2/2     Running   0          21m   10.10.0.8       k8s1   <none>
	 external-ips-test   app3-68fb594d47-4v4kd             2/2     Running   0          21m   10.10.1.222     k8s2   <none>
	 external-ips-test   host-client-mv5zn                 1/1     Running   0          21m   192.168.36.12   k8s2   <none>
	 external-ips-test   host-client-wpdcm                 1/1     Running   0          21m   192.168.36.11   k8s1   <none>
	 external-ips-test   host-server-1-56c9467d4b-cwgqw    2/2     Running   0          21m   192.168.36.11   k8s1   <none>
	 external-ips-test   host-server-2-b8d89c58c-64vcm     2/2     Running   0          21m   192.168.36.11   k8s1   <none>
	 kube-system         cilium-6kh5z                      1/1     Running   0          3m    192.168.36.11   k8s1   <none>
	 kube-system         cilium-cf79h                      1/1     Running   0          3m    192.168.36.12   k8s2   <none>
	 kube-system         cilium-operator-8ff8697cc-hhvqs   1/1     Running   0          32m   192.168.36.12   k8s2   <none>
	 kube-system         coredns-687db6485c-b4hp2          1/1     Running   0          1h    10.10.1.249     k8s2   <none>
	 kube-system         etcd-k8s1                         1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         kube-apiserver-k8s1               1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         kube-controller-manager-k8s1      1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         kube-scheduler-k8s1               1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         log-gatherer-kwx4n                1/1     Running   0          1h    192.168.36.13   k8s3   <none>
	 kube-system         log-gatherer-lqp62                1/1     Running   0          1h    192.168.36.12   k8s2   <none>
	 kube-system         log-gatherer-nmsds                1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         registry-adder-7627x              1/1     Running   0          1h    192.168.36.12   k8s2   <none>
	 kube-system         registry-adder-sqv5h              1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         registry-adder-zwqpw              1/1     Running   0          1h    192.168.36.13   k8s3   <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-6kh5z cilium-cf79h]
cmd: kubectl exec -n kube-system cilium-6kh5z -- cilium service list
Exitcode: 0 
Stdout:
 	 ID      Frontend              Service Type   Backend                        
	 1       10.96.0.10:53         ClusterIP      1 => 10.10.1.249:53            
	 2       10.96.0.1:443         ClusterIP      1 => 192.168.36.11:6443        
	 3       10.100.162.253:82     ClusterIP      1 => 10.10.0.23:80             
	 4       192.0.2.223:82        ExternalIPs    1 => 10.10.0.23:80             
	 5       172.28.128.3:82       ExternalIPs    1 => 10.10.0.23:80             
	 6       192.168.36.11:82      ExternalIPs    1 => 10.10.0.23:80             
	 7       10.110.38.7:30002     ClusterIP      1 => 10.10.0.23:80             
	 8       192.0.2.223:30002     ExternalIPs    1 => 10.10.0.23:80             
	 9       172.28.128.3:30002    ExternalIPs    1 => 10.10.0.23:80             
	 10      192.168.36.11:30002   ExternalIPs    1 => 10.10.0.23:80             
	 11      10.101.162.56:83      ClusterIP      1 => 10.10.0.8:80              
	 12      0.0.0.0:30003         NodePort       1 => 10.10.0.8:80              
	 13      192.168.36.11:30003   NodePort       1 => 10.10.0.8:80              
	 14      10.10.0.181:30003     NodePort       1 => 10.10.0.8:80              
	 15      10.111.190.219:84     ClusterIP      1 => 192.168.36.11:20004       
	 16      0.0.0.0:30004         NodePort       1 => 192.168.36.11:20004       
	 17      192.168.36.11:30004   NodePort       1 => 192.168.36.11:20004       
	 18      10.10.0.181:30004     NodePort       1 => 192.168.36.11:20004       
	 19      10.104.53.50:85       ClusterIP      1 => 192.168.36.11:30006       
	 20      0.0.0.0:30005         NodePort       1 => 192.168.36.11:30006       
	 21      192.168.36.11:30005   NodePort       1 => 192.168.36.11:30006       
	 22      10.10.0.181:30005     NodePort       1 => 192.168.36.11:30006       
	 31      10.110.229.26:69      ClusterIP      1 => 10.10.0.69:69             
	                                              2 => 10.10.0.56:69             
	 32      10.110.229.26:80      ClusterIP      1 => 10.10.0.69:80             
	                                              2 => 10.10.0.56:80             
	 33      10.98.176.253:80      ClusterIP      1 => 10.10.1.191:80            
	 34      10.98.176.253:69      ClusterIP      1 => 10.10.1.191:69            
	 45      10.103.241.125:2379   ClusterIP                                     
	 10069   [fd03::100]:69        ClusterIP      1 => [f00d::a0b:0:0:ef0]:69    
	                                              2 => [f00d::a0b:0:0:38a9]:69   
	                                              3 => [f00d::a0b:0:0:df54]:69   
	 10080   [fd03::100]:80        ClusterIP      1 => [f00d::a0b:0:0:38a9]:80   
	                                              2 => [f00d::a0b:0:0:df54]:80   
	                                              3 => [f00d::a0b:0:0:ef0]:80    
	 20069   [fd03::200]:69        ClusterIP      1 => [f00d::a0c:0:0:e66f]:69   
	 20080   [fd03::200]:80        ClusterIP      1 => [f00d::a0c:0:0:e66f]:80   
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-6kh5z -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                            IPv6                 IPv4          STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                            
	 532        Disabled           Disabled          4          reserved:health                                        f00d::a0b:0:0:7ce0   10.10.0.10    ready   
	 571        Disabled           Disabled          40617      k8s:id=app1                                            f00d::a0b:0:0:ef0    10.10.0.56    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                          
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                              
	                                                            k8s:io.kubernetes.pod.namespace=default                                                           
	                                                            k8s:zgroup=testapp                                                                                
	 896        Disabled           Disabled          40617      k8s:id=app1                                            f00d::a0b:0:0:38a9   10.10.0.69    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                          
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                              
	                                                            k8s:io.kubernetes.pod.namespace=default                                                           
	                                                            k8s:zgroup=testapp                                                                                
	 2137       Disabled           Disabled          6636       k8s:appSecond=true                                     f00d::a0b:0:0:3e5d   10.10.0.147   ready   
	                                                            k8s:id=app2                                                                                       
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                          
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app2-account                                              
	                                                            k8s:io.kubernetes.pod.namespace=default                                                           
	                                                            k8s:zgroup=testapp                                                                                
	 2432       Disabled           Disabled          33173      k8s:id=app1                                            f00d::a0b:0:0:df54   10.10.0.23    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                          
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                   
	                                                            k8s:io.kubernetes.pod.namespace=external-ips-test                                                 
	 2558       Disabled           Disabled          14346      k8s:id=app2                                            f00d::a0b:0:0:d786   10.10.0.8     ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                          
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                   
	                                                            k8s:io.kubernetes.pod.namespace=external-ips-test                                                 
	 3973       Disabled           Disabled          11027      k8s:id=app3                                            f00d::a0b:0:0:b102   10.10.0.200   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                          
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                   
	                                                            k8s:io.kubernetes.pod.namespace=default                                                           
	                                                            k8s:zgroup=testapp                                                                                
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-cf79h -- cilium service list
Exitcode: 0 
Stdout:
 	 ID      Frontend              Service Type   Backend                        
	 1       10.96.0.1:443         ClusterIP      1 => 192.168.36.11:6443        
	 2       10.96.0.10:53         ClusterIP      1 => 10.10.1.249:53            
	 3       10.100.162.253:82     ClusterIP      1 => 10.10.0.23:80             
	 4       192.0.2.223:82        ExternalIPs    1 => 10.10.0.23:80             
	 5       172.28.128.3:82       ExternalIPs    1 => 10.10.0.23:80             
	 6       192.168.36.11:82      ExternalIPs    1 => 10.10.0.23:80             
	 7       10.110.38.7:30002     ClusterIP      1 => 10.10.0.23:80             
	 8       192.168.36.11:30002   ExternalIPs    1 => 10.10.0.23:80             
	 9       192.0.2.223:30002     ExternalIPs    1 => 10.10.0.23:80             
	 10      172.28.128.3:30002    ExternalIPs    1 => 10.10.0.23:80             
	 11      10.101.162.56:83      ClusterIP      1 => 10.10.0.8:80              
	 12      10.10.1.89:30003      NodePort       1 => 10.10.0.8:80              
	 13      0.0.0.0:30003         NodePort       1 => 10.10.0.8:80              
	 14      192.168.36.12:30003   NodePort       1 => 10.10.0.8:80              
	 15      10.111.190.219:84     ClusterIP      1 => 192.168.36.11:20004       
	 16      0.0.0.0:30004         NodePort       1 => 192.168.36.11:20004       
	 17      192.168.36.12:30004   NodePort       1 => 192.168.36.11:20004       
	 18      10.10.1.89:30004      NodePort       1 => 192.168.36.11:20004       
	 19      10.104.53.50:85       ClusterIP      1 => 192.168.36.11:30006       
	 20      192.168.36.12:30005   NodePort       1 => 192.168.36.11:30006       
	 21      10.10.1.89:30005      NodePort       1 => 192.168.36.11:30006       
	 22      0.0.0.0:30005         NodePort       1 => 192.168.36.11:30006       
	 31      10.110.229.26:69      ClusterIP      1 => 10.10.0.69:69             
	                                              2 => 10.10.0.56:69             
	 32      10.110.229.26:80      ClusterIP      1 => 10.10.0.69:80             
	                                              2 => 10.10.0.56:80             
	 33      10.98.176.253:69      ClusterIP      1 => 10.10.1.191:69            
	 34      10.98.176.253:80      ClusterIP      1 => 10.10.1.191:80            
	 45      10.103.241.125:2379   ClusterIP                                     
	 10069   [fd03::100]:69        ClusterIP      1 => [f00d::a0b:0:0:ef0]:69    
	                                              2 => [f00d::a0b:0:0:38a9]:69   
	                                              3 => [f00d::a0b:0:0:df54]:69   
	 10080   [fd03::100]:80        ClusterIP      1 => [f00d::a0b:0:0:38a9]:80   
	                                              2 => [f00d::a0b:0:0:df54]:80   
	                                              3 => [f00d::a0b:0:0:ef0]:80    
	 20069   [fd03::200]:69        ClusterIP      1 => [f00d::a0c:0:0:e66f]:69   
	 20080   [fd03::200]:80        ClusterIP      1 => [f00d::a0c:0:0:e66f]:80   
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-cf79h -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                         IPv6                 IPv4          STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                         
	 1220       Disabled           Disabled          28525      k8s:io.cilium.k8s.policy.cluster=default            f00d::a0c:0:0:3c4e   10.10.1.249   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                    
	                                                            k8s:k8s-app=kube-dns                                                                           
	 1305       Disabled           Disabled          16678      k8s:id=app3                                         f00d::a0c:0:0:ee7f   10.10.1.222   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                       
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=external-ips-test                                              
	 2113       Disabled           Disabled          31382      k8s:io.cilium.k8s.policy.cluster=default            f00d::a0c:0:0:e66f   10.10.1.191   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=default                                                        
	                                                            k8s:name=echo                                                                                  
	 3528       Disabled           Disabled          4          reserved:health                                     f00d::a0c:0:0:7665   10.10.1.74    ready   
	 
Stderr:
```

[b2288a94_K8sServicesTest_Checks_ClusterIP_Connectivity_IPv6_Connectivity_Checks_service_on_same_node.zip](https://github.com/cilium/cilium/files/4190325/b2288a94_K8sServicesTest_Checks_ClusterIP_Connectivity_IPv6_Connectivity_Checks_service_on_same_node.zip)

### PR DESCRIPTION
**Pull request by borkmann**
From time to time in our CI connectivity to {tftp,http}://[fd03::100]/ failed.

Related service map dump looks like:

  [...]
  10069   [fd03::100]:69         ClusterIP      1 => [f00d::a0b:0:0:eb33]:69
                                                2 => [f00d::a0b:0:0:ce1a]:69
                                                3 => [f00d::a0b:0:0:3d75]:69
  10080   [fd03::100]:80         ClusterIP      1 => [f00d::a0b:0:0:3d75]:80
                                                2 => [f00d::a0b:0:0:eb33]:80
                                                3 => [f00d::a0b:0:0:ce1a]:80
  20069   [fd03::200]:69         ClusterIP      1 => [f00d::a0c:0:0:172d]:69
  20080   [fd03::200]:80         ClusterIP      1 => [f00d::a0c:0:0:172d]:80
  [...]

And endpoint list:

  ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                            IPv6                 IPv4          STATUS
             ENFORCEMENT        ENFORCEMENT
  [...]
  45         Disabled           Disabled          27884      k8s:id=app1                                            f00d::a0b:0:0:ce1a   10.10.0.178   ready
                                                             k8s:io.cilium.k8s.policy.cluster=default
                                                             k8s:io.cilium.k8s.policy.serviceaccount=default
                                                             k8s:io.kubernetes.pod.namespace=external-ips-test
  510        Disabled           Disabled          12623      k8s:id=app1                                            f00d::a0b:0:0:3d75   10.10.0.105   ready
                                                             k8s:io.cilium.k8s.policy.cluster=default
                                                             k8s:io.cilium.k8s.policy.serviceaccount=app1-account
                                                             k8s:io.kubernetes.pod.namespace=default
                                                             k8s:zgroup=testapp
  688        Disabled           Disabled          12623      k8s:id=app1                                            f00d::a0b:0:0:eb33   10.10.0.126   ready
                                                             k8s:io.cilium.k8s.policy.cluster=default
                                                             k8s:io.cilium.k8s.policy.serviceaccount=app1-account
                                                             k8s:io.kubernetes.pod.namespace=default
                                                             k8s:zgroup=testapp
  [...]

As can be seen the selection based on `k8s:id=app1` is not sufficient as
Cilium label selector works slightly different than K8s label selector in
that the former needs to specify the K8s namespace. Hence, for the IPv6
tests, add `k8s:io.kubernetes.pod.namespace=default` namespace selector.

Fixes: #10157
Fixes: d1a61479eae3 ("test/k8s: Add tests for same-node IPv6 service connectivity")
Fixes: a6c62bae969c ("test/k8s: Test IPv6 ClusterIP service connectivity across nodes")
Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10214)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Review by gandro — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by borkmann** [comment]
Hit #9869

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
`net-next vm provisioning fail`

**Comment by borkmann** [comment]
test-me-please

**Comment by gandro** [comment]
`net-next vm provisioning fail`

**Comment by gandro** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Pull request merged**
