### PR TITLE
Remove unused functionality in pkg/bpf

### PR DESCRIPTION
**Pull request by tklauser**
See commits for details.

### CODE REVIEW

**Comment by tklauser** [comment]
l4lb test failure will be fixed by #18370

**Review by jibi — APPROVED** [review]
Thanks!

**Comment by tklauser** [comment]
Approved and runtime tests passed. All other tests (except l4lb, see https://github.com/cilium/cilium/pull/18378#issuecomment-1005582857) passed on previous run. Marking as ready to merge.

**Pull request merged**
