### PR TITLE
lbmap: Get rid of bpfService cache lock

### PR DESCRIPTION
**Pull request by brb**
This PR:

- Removes the bpfService cache lock, as any call to the cache happens via lbmap, and lbmap itself is protected by its own lock.
- Makes sure that the lbmap lock is taken in the very beginning of each public method definition of lbmap.

.Added `needs-backport/1.5` as in `lbmap.UpdateService()` the lock used to be taken after calling `acquireNewBackendIDs()` which could have caused subtle race conditions.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8494)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by tgraf** [comment]
@brb Is there a particular reason to backport this to 1.5?

**Review by tgraf — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by brb** [comment]
CI failed due to failing to fetch Cilium repo.

**Comment by brb** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Pull request merged**
