### PR TITLE
k8s: use netip.Prefix for endpoint backed prefixes

### PR DESCRIPTION
**Pull request by tklauser**
Instead of converting from `netip.Addr` to string and then parsing to a
`net.IP` or `net.IPNet`, only to be converted to `net.IPNet` in
`RuleTranslator.generateToCidrFromEndpoint`, let's use `netip` types
consistently to avoid the round trips.

### CODE REVIEW

**Review by nathanjsweet — APPROVED** [review]

**Comment by aanm** [comment]
related to https://github.com/cilium/cilium/issues/24246

**Pull request merged**
