### PR TITLE
v1.13 Backports 2024-05-06

### PR DESCRIPTION
**Pull request by pippolo84**
* [x] #30548 (@squeed)
 * [x] #32240 (@pchaigno)
 * [x] #32303 (@marseel)
 * [x] #32244 (@learnitall)
 * [x] #32333 (@jrajahalme)
 * [x] #32325 (@nathanjsweet)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30548 32240 32303 32244 32333 32325
```

### CODE REVIEW

**Comment by pippolo84** [comment]
/test-backport-1.13

**Review by pchaigno — APPROVED** [review]
Thanks Fabio!

**Review by nathanjsweet — APPROVED** [review]

**Review by squeed — APPROVED** [review]

**Review by marseel — APPROVED** [review]

**Comment by pippolo84** [comment]
/test-1.26-net-next)

**Comment by pippolo84** [comment]
/test-1.26-net-next

**Review by learnitall — APPROVED** [review]
Thanks!

**Review by jrajahalme — APPROVED** [review]

**Review by ldelossa — APPROVED** [review]

**Pull request merged**
