### PR TITLE
v1.4 backport 19-04-15

### PR DESCRIPTION
**Pull request by brb**
v1.4 backports 2019-04-15

**INCLUDED**

 * #7713 -- Doc: Update jinja dependency for documentation building (@tgraf)
 * #7717 -- envoy: Update to enable path normalization (@jrajahalme)
 * #7712 -- Istio update to use proxy image with path normalization (@jrajahalme)
 * #7704 -- Fix backporting scripts for https users (@nebril)

**NOT INCLUDED**

 * #7720 -- CI: Enforce sensible timeouts. (@jrajahalme): There was a merge conflict. @jrajahalme Is it fine to exclude this PR or is it needed to make the 1.4 CI stable?

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 7713 7717 7712 7704; do contrib/backporting/set-labels.py $pr done 1.4; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7729)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-docs-please

**Comment by ianvernon** [comment]
ToServices BeforeAll failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11609/

**Comment by ianvernon** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
