### PR TITLE
v1.13 Backports 2024-01-23

### PR DESCRIPTION
**Pull request by giorio94**
* [x] #30207 (@giorio94)
   - ℹ️ Hit multiple conflicts due to the absence of the helm-default action in the v1.13 branch, resolved updating the chart-dir path as appropriate. Additionally, skipped the e2e-upgrade hunks, as not present.
 * [ ] #28286 (@tamilmani1989)
 * [ ] #30131 (@ayuspin)
 * [x] #30335 (@giorio94)
 * [x] #30167 (@viktor-kurchenko)
   - :warning: Hit conflicts due to `cilium` to `cilium-dbg` renaming, resolved running `git cherry-pick -Xrename-threshold=20% $SHA`. Please double check.
  
PRs skipped due to conflicts:

 * #29460 (@tommyp1ckles)
   - :x: Skipped, because v1.13 did not include the `localNodeInitializer` logic. @tommyp1ckles I've marked the PR as `backport/author` (backports to v1.15 and v1.14 are already in progress). Could you please take care of it?

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30207 28286 30131 30335 30167
```

### CODE REVIEW

**Comment by giorio94** [comment]
/test-backport-1.13

**Comment by giorio94** [comment]
Conformance AKS failure is https://github.com/cilium/cilium/issues/22162, which got fixed in newer versions of the CLI (but the version is pinned to v0.14.8 in the v1.13 branch). Rerunning

**Review by squeed — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Comment by giorio94** [comment]
@viktor-kurchenko Gentle ping

**Review by viktor-kurchenko — APPROVED** [review]

**Comment by viktor-kurchenko** [comment]
> @viktor-kurchenko Gentle ping

Approved! Thank you.

**Comment by giorio94** [comment]
CI is green and most of the reviews are in (the remaining PRs didn't incur in any conflict, and I performed an additional sanity check). Marking as ready to merge.

**Pull request merged**
