### PR TITLE
v1.8 backports 2021-06-10

### PR DESCRIPTION
**Pull request by gandro**
* #14594 -- datapath: Do not use proxy original source address with tunneling (@jrajahalme)
 * #16268 -- pkg/k8s: ignore namespace events that do not change labels (@aanm)
 * #16271 -- endpoint: Skip waiting-to-regenerate -> waiting-for-identity state transitions (@jrajahalme)
 * #16176 -- contrib: simplify check-docker-images script (@aanm) ⚠️ Had to resolve conflicts (`external_dependencies` is empty on 1.8)
 * #16137 -- docs: document the policy for backporting documentation changes (@qmonnet)
 * #16055 -- Add missing bpftool map dumps (@h3llix)
~* #16190 -- pkg/k8s: add pod IP event change (@aanm) ⚠️ Had to resolve various conflicts (e.g. `if newK8sPod.Spec.HostNetwork` was already present on 1.8?)~ removed due to it breaking policy visibility annotations
 * #16118 -- daemon: Improve logging of device auto-detection (@brb)
 * #16016 -- Clarify one-time setup for backporting (@christarazi)
 * #16432 -- node: fix arpping test (@jibi)
 * #16408 -- docs: add a "Copy Commands" button for shell-session snippets (@qmonnet)
 * #16186 -- docs: ENIs should not be managed by the OS (@gandro)

**Skipped**

 * #16238 -- docs: add a reference of helm values (@bmcustodio) ⚠️ Cilium v1.8 has a different Helm setup. This will need a manual backport if we want this on 1.8.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14594 16268 16271 16176 16137 16055 16118 16016 16432 16408 16186; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Review by qmonnet — COMMENTED** [review]
> #16137 -- docs: document the policy for backporting documentation changes (@qmonnet)
#16408 -- docs: add a "Copy Commands" button for shell-session snippets (@qmonnet)

Those are good, thank you!

**Review by qmonnet — APPROVED** [review]

**Comment by gandro** [comment]
test-backport-1.8

**Review by christarazi — APPROVED** [review]

**Review by aanm — APPROVED** [review]
Looks good for my changes

**Review by jibi — APPROVED** [review]

**Comment by gandro** [comment]
All tests with visibility annotation failed. Could this be caused by https://github.com/cilium/cilium/pull/16497/commits/34be426daa442f567a33cf350ebfefe0205bfb37 @jrajahalme ?

**Review by brb — APPROVED** [review]
LGTM for my changes, thanks.

**Comment by gandro** [comment]
Removed 34be426 to see if this fixes the policy visibility annotation issues we saw in almost all suites.

**Comment by gandro** [comment]
test-backport-1.8

**Comment by gandro** [comment]
Looks like  34be426 wasn't the culprit after all - will readd it. The tests are still failing, e.g. https://jenkins.cilium.io/job/Cilium-PR-K8s-1.18-kernel-4.9/1667/ - will investigate which commit might be causing this.

**Comment by gandro** [comment]
Removing 29e6b13 to test if it was the culprit

**Comment by gandro** [comment]
test-backport-1.8

**Comment by gandro** [comment]
> Removing [29e6b13](https://github.com/cilium/cilium/commit/29e6b137ee4a9a7d74890721de2440d4eff115ab) to test if it was the culprit

@aanm I had to drop #16190 as it was breaking all tests which used policy visibility annotations. Please take a look, maybe my conflict resolution was buggy.

**Comment by gandro** [comment]
CI hit various flakes on 1.8:

- k8s-1.12-kernel-4.9 hit #13011 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-kernel-4.9/108/
- k8s-1.14-kernel-4.9 also hit #13011 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.14-kernel-4.9/290/
- k8s-1.18-kernel-4.9 weirdly hit #15418 in K8sVerifier tests https://jenkins.cilium.io/job/Cilium-PR-K8s-1.18-kernel-4.9/1668/ - I assume this is a rare race on the filesystem?
- k8s-upstream timed out fetching a vagrant box https://jenkins.cilium.io/job/Cilium-PR-K8s-Upstream/3138/console
- runtime hit #16075 - looks like a different test than the one fixed by f9bbd6f ? @jibi @brb

**Comment by gandro** [comment]
test-1.12-4.9

**Comment by gandro** [comment]
test-1.14-4.9

**Comment by gandro** [comment]
test-1.18-4.9

**Comment by gandro** [comment]
test-upstream-k8s

**Comment by gandro** [comment]
test-runtime

**Comment by gandro** [comment]
Hit the same flakes again:

https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/4991/ arping #16075 (i.e. not the one addressed in this backport)
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.14-kernel-4.9/291/ ` go: RLock /cilium/go.mod: no locks available`

**Comment by gandro** [comment]
test-1.14-4.9

**Comment by gandro** [comment]
test-runtime

**Review by jrajahalme — APPROVED** [review]

**Review by aditighag — APPROVED** [review]

**Comment by aditighag** [comment]
>Setting labels for PR 16271... backport-pending/1.8 label not found in PR, exiting

Saw this while updating the labels.

**Comment by jibi** [comment]
>     * runtime hit #16075 - looks like a different test than the one fixed by [f9bbd6f](https://github.com/cilium/cilium/commit/f9bbd6fc5e68f57498b497eb348a118ef8a49f7b) ? https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/4978/ @jibi @brb

Looks like the same test (`linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling`) but it's failing in a different way now:
```
	 node_linux_test.go:1198:
	     c.Assert(n.HardwareAddr.String(), check.Equals, mac.String())
	 ... obtained string = "02:48:4e:57:94:3c"
	 ... expected string = "7e:06:77:f1:c6:7d"
	
	 level=info msg="Unable to insert neighbor" error="no such device" hardwareAddr="7e:06:77:f1:c6:7d" interface=veth0 ipAddr=9.9.9.250 subsys=node-neigh-debug
	 level=info msg="Unable to insert neighbor" error="no such device" hardwareAddr="7e:06:77:f1:c6:7d" interface=veth0 ipAddr=9.9.9.250 subsys=node-neigh-debug
	 level=info msg="Unable to insert neighbor" error="no such device" hardwareAddr="7e:06:77:f1:c6:7d" interface=veth0 ipAddr=9.9.9.250 subsys=node-neigh-debug
	 level=info msg="Unable to remove neighbor entry" error="no such device" hardwareAddr="7e:06:77:f1:c6:7d" interface=veth0 ipAddr=9.9.9.250 linkIndex=56 subsys=node-neigh-debug
	 level=info msg="Unable to insert neighbor" error="no such device" hardwareAddr="7e:06:77:f1:c6:7d" interface=veth0 ipAddr=9.9.9.250 subsys=node-neigh-debug
	 level=info msg="Unable to insert neighbor" error="no such device" hardwareAddr="7e:06:77:f1:c6:7d" interface=veth0 ipAddr=9.9.9.250 subsys=node-neigh-debug
	 level=info msg="Unable to insert neighbor" error="no such device" hardwareAddr="7e:06:77:f1:c6:7d" interface=veth0 ipAddr=9.9.9.250 subsys=node-neigh-debug
	 level=info msg="Unable to insert neighbor" error="no such device" hardwareAddr="7e:06:77:f1:c6:7d" interface=veth0 ipAddr=9.9.9.250 subsys=node-neigh-debug
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 level=info msg="Unable to insert neighbor" error="no such device" hardwareAddr="7e:06:77:f1:c6:7d" interface=veth0 ipAddr=9.9.9.250 subsys=node-neigh-debug
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.052s
	
	 FAIL: node_linux_test.go:956: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
```

while the failure that was fixed was reporting:
```
	 node_linux_test.go:1207:
	     wait(nodev1.Identity(), nil, true)
	 node_linux_test.go:1048:
	     c.Assert(err, check.IsNil)
	 ... value *errors.errorString = &errors.errorString{s:"timeout reached while waiting for condition"} ("timeout reached while waiting for condition")
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.052s
	 
	 FAIL: node_linux_test.go:956: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
```

I filled https://github.com/cilium/cilium/issues/16573

**Pull request merged**
