### PR TITLE
1.9 backport for envoy: Update to release 1.18.4

### PR DESCRIPTION
**Pull request by jrajahalme**
```release-note
Cilium Envoy integration is updated to release 1.18.4.
 ```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-backport-1.9

**Comment by jrajahalme** [comment]
net-next hit by #12511

**Comment by jrajahalme** [comment]
gke-stable had run before images where ready, restarting

**Comment by jrajahalme** [comment]
test-gke

**Comment by jrajahalme** [comment]
test-backport-1.9

**Comment by jrajahalme** [comment]
test-backport-1.9

**Review by joestringer — APPROVED** [review]

**Comment by jrajahalme** [comment]
k8s 1.15 hit by #15255

**Comment by jrajahalme** [comment]
conformance test ipv6 fail looks not related to Envoy version.

**Comment by jrajahalme** [comment]
GKE stable failed on ImagePullBackoff on all CI images.

**Comment by jrajahalme** [comment]
@joestringer None of the CI fails seem related to Envoy Version.

**Pull request merged**
