### PR TITLE
Rename `hostFirewall` and mark stable

### PR DESCRIPTION
**Pull request by pchaigno**
See commits for details.

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Review by qmonnet — APPROVED** [review]
Looks good to me :+1:

**Review by tklauser — APPROVED** [review]

**Review by errordeveloper — APPROVED** [review]

**Comment by pchaigno** [comment]
The changes covered by @cilium/policy are minor (related to the Helm value change in the docs & tests), so I think it's okay to not wait for those reviews. All tests are passing so marking this ready to merge.

**Review by christarazi — APPROVED** [review]
:rocket:

**Pull request merged**
