### PR TITLE
test: Delete all unmanaged pods with a single kubectl delete

### PR DESCRIPTION
**Pull request by pchaigno**
In flake #14915, some pods are not found while attempting to restart unmanaged pods on GKE. The assumption is that those pods are for some reason deleted between the time we list unmanaged pods and the time we delete them in `RestartUnmanagedPodsInNamespace()`.

One reason this might happen is because we delete unmanaged pods one by one. We first list all pods, then iterate on them, and every time a pod is found unmanaged we run `kubectl delete`. Since executing `kubectl delete` can take some time, it may take a while between when we take a snapshot of all pods and when we delete the last pods in the list.

To avoid this, we can list all pods and iterate on them to find unmanaged pods. Then, in a single go we can delete all unmanaged pods with a single `kubectl delete` command. This commit implements that approach.

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Comment by aditighag** [comment]
GKE test passed - https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/4319/ 🚀 . I'll trigger one more round to confirm that it fixes the flake #14915.

**Comment by aditighag** [comment]
test-gke

**Comment by pchaigno** [comment]
test-gke

**Comment by pchaigno** [comment]
GKE passed three times in a row :tada: 

The only failing test is known-broken test https://github.com/cilium/cilium/issues/14950. Should be good to merge as soon as we have the @cilium/ci-structure review.

**Review by nebril — APPROVED** [review]

**Comment by nebril** [comment]
conformance tests failed due to known issue being worked on, unrelated to the PR I say we merge

**Pull request merged**
