### PR TITLE
v1.15 Backports 2024-04-10

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #31533 (@chancez)
 * [x] #31227 (@vipul-21) :warning: resolved conflicts
 * [x] #31220 (@brlbil)
 * [x] #31714 (@sayboras)
 * [x] #31686 (@sayboras)
 * [x] #29581 (@xyz-li)
 * [x] #31750 (@tklauser)
 * [x] #31728 (@saintdle)
 * [x] #31781 (@giorio94)
 * [x] #31820 (@julianwiedmann)
 * [ ] #31692 (@katiestruthers)
 * [ ] #31847 (@xmulligan)
 * [x] #31851 (@nathanjsweet)

PRs skipped due to conflicts:

 * #31753 (@qmonnet)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31533 31227 31220 31714 31686 29581 31750 31728 31781 31820 31692 31847 31851
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
LGTM for my commits, thanks a lot 👍

**Comment by qmonnet** [comment]
> - https://github.com/cilium/cilium/pull/31753 (@qmonnet) ⚠️ resolved conflicts

I suppose you resolved the conflicts by regenerating the images? Sorry for the additional work, I should maybe have marked this one as `backport/author` :grimacing:

By the way, this commit misses your own sign-off tag, can you fix it please?

**Comment by nbusseneau** [comment]
@qmonnet Yeah nah I actually intended to drop this one when I realized it was touching the images, but I messed up... will fix and remove from the PR, this is indeed one of the cases where manual backport is needed.

**Comment by nbusseneau** [comment]
> By the way, this commit misses your own sign-off tag, can you fix it please?

Huh, so I'm just noticing now that my automation for adding `Sign-off` is not working for commits I fixed during the backporting process. This is new (the process is new, so...), thanks for spotting it!

**Comment by nbusseneau** [comment]
Backport of #31227 introduces a change to the upgrade guide under `Changed metrics`. Just want to make sure all of this is correct and intended and we're not going to cause troubles for existing v1.15 users. cc @joestringer @vipul-21

**Comment by nbusseneau** [comment]
/test-backport-1.15

**Comment by joestringer** [comment]
@nbusseneau as I understand, it should only be a net addition of a new label for one metric, so should not impact existing usage of the metric. Furthermore I wouldn't expect a significant change in cardinality.

**Comment by vipul-21** [comment]
@nbusseneau the addition of a label to the metric should not impact the existing usage of the metric. The changes of commit looks good. Thanks !

**Review by vipul-21 — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
My commit looks good, thanks!

**Review by julianwiedmann — APPROVED** [review]

**Review by chancez — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Review by lmb — APPROVED** [review]
tophat

**Review by brlbil — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
My changes looks good, thanks Nicolas!

**Pull request merged**
