### PR TITLE
v1.3 backports 2019-02-25

### PR DESCRIPTION
**Pull request by joestringer**
## Backported

Cleanly backported:

 * #7203 -- Get rid of JoinEP flakes (@brb)
 * #7200 -- ctmap: Print source addresses in ctmap cli (@joestringer)
 * #7191 -- pkg/kvstore: do not use default instance to create new instance module (@aanm)
 * #7184 -- bpf: Enable pipefail option in init.sh (@brb)
   * Required bpf.sha update.

## Skipped

These PRs did not cleanly apply to v1.3 branch:

 * @brb, please take a look at whether it makes sense to backport these to v1.3:
   * #7163 -- Bump Go version to 1.11.5 (@brb)
   * #7162 -- Add new C and Go struct alignment checker (@brb)
 * @tgraf, please take a look at backporting these to v1.3:
   * #7139 -- policy: Fix ipcache synchronization on startup (@tgraf)

## Remaining Tasks

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 7203 7200 7191 7184; do contrib/backporting/set-labels.py $pr done 1.3; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7208)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

EDIT: Woops, messed up bindata. Fixing.

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
Boot VMs stage timed out: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10216/execution/node/70/log/

trying again.

**Comment by ianvernon** [comment]
test-me-please

**Comment by joestringer** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
test-docs-please

**Comment by joestringer** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
