### PR TITLE
update cilium-docker-plugin, cilium-operator to golang 1.12.8

### PR DESCRIPTION
**Pull request by ianvernon**
Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8926)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Do we need to update some container image version references somewhere in the tree for these?

**Comment by ianvernon** [comment]
@joestringer no, the builds for Cilium operator and the docket plugin are self contained. I bumped the versions in Cilium’s images (builder and runtime) and for Travis , but missed these. All of our images are up to date now with Golang 1.12.8.

**Pull request merged**
