### PR TITLE
v1.12 Backports 2023-06-08

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
* [x] #25907 (@jrajahalme)
 * [x] #25893 (@pchaigno)
   * ⚠️ Observed conflicts. I dropped the key rotation duration stuff
 * [x] #25936 (@joamaki)
   * ⚠️ Observed minor conflicts

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 25907 25893 25936; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=25907,25893,25936
```

### CODE REVIEW

**Review by joamaki — CHANGES_REQUESTED** [review]
Please merge https://github.com/cilium/cilium/pull/25896 first and then repick https://github.com/cilium/cilium/pull/25936.

**Comment by YutaroHayakawa** [comment]
/test-backport-1.12

**Review by jrajahalme — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
k8s-1.20-kernel-4.9: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.9/35/
- Hitting https://github.com/cilium/cilium/issues/22931

k8s-1.22-kernel-4.9: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.9/21/
- Hitting https://github.com/cilium/cilium/issues/13071

k8s-upstream: https://jenkins.cilium.io/job/Cilium-PR-K8s-Upstream/60/
- `Error: execution error at (cilium/templates/cilium-configmap.yaml:59:5): kubeproxyReplacement must be explicitly set to a valid value (disabled, partial, or strict) to continue.`
- This is concerning. Might be a regression. I'll check.

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Comment by YutaroHayakawa** [comment]
Fixed the backport error in https://github.com/cilium/cilium/pull/26006/commits/bbce1e0af5c7c1cde7359a783fc144d3b00a5aab. TL;DR: kubeProxyReplacement=probe is still valid in this branch.

**Comment by YutaroHayakawa** [comment]
/test-backport-1.12

**Review by joamaki — APPROVED** [review]

**Pull request merged**
