### PR TITLE
[v1.15] bpf: improvements for tailcall error reporting

### PR DESCRIPTION
**Pull request by julianwiedmann**
To improve the error reporting for missed tailcalls in the datapath, backport a bunch of recent upstream improvements. This will make it easier to diagnose drops for such errors, and hopefully also help to eliminate CI flakes in the upgrade/downgrade workflows.

The manual backport is needed due to some trivial contextual conflicts.

* [ ] #30001
* [ ] #30023
* [ ] #30288
* [ ] #31990
* [ ] #32129
* [ ] #32151
* [ ] #32299

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30001 30023 30288 31990 32129 32151 32299
```

### CODE REVIEW

**Comment by julianwiedmann** [comment]
/test-backport-1.15

**Review by ti-mo — APPROVED** [review]
Cool, thank you!

**Review by ldelossa — APPROVED** [review]

**Comment by julianwiedmann** [comment]
@kaworu ping, I think CODEOWNERS wants you to sanity-check the new drop reason.

**Review by kaworu — APPROVED** [review]
Protobuf changes LGTM

**Review by lmb — APPROVED** [review]

**Pull request merged**
