### PR TITLE
envoy: Avoid empty typeURL for all resources

### LINKED ISSUE #108: Avoid empty typeURL for cilium.tls_wrapper
### Description

As per new envoy build, we faced the below error while envoy proxy was starting. The workaround is to add depecating flag `envoy.reloadable_features.no_extension_lookup_by_name`.

This issue is to track the longterm solution which should register typeURL for cilium.tls_wrapper type.

https://github.com/cilium/cilium/commit/81e2491196cea1dd058322e7eae980bc77ca5280

```
level=error msg="[error initializing configuration '/var/run/cilium/bootstrap.pb': Didn't find a registered implementation for 'cilium.tls_wrapper' with type URL: 'envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext'" subsys=envoy-main threadID=1944
level=info msg="[exiting" subsys=envoy-main threadID=1944
level=info msg="Didn't find a registered implementation for 'cilium.tls_wrapper' with type URL: ''" subsys=envoy-main threadID=1944
```

### PR DESCRIPTION
**Pull request by sayboras**
### Description

This commit is to add typeURL for below resources:

- cilium.network
- cilium.tls_wrapper
- envoy.filters.http.router
- envoy.filters.listener.tls_inspector

The main reason is to avoid the workaround (which disables extension
lookup by name), and to pave the way for future envoy minor version
upgrade.

Fixes: https://github.com/cilium/proxy/issues/108

Signed-off-by: Tam Mach <tam.mach@cilium.io>

### Testing

Sanity check was done locally and manually, we probably rely on CI to verify this change.

### CODE REVIEW

**Review by jrajahalme — APPROVED** [review]

**Review by rolinh — APPROVED** [review]
vendor changes lgtm

**Comment by sayboras** [comment]
/test-1.16-4.19

**Pull request merged**
