### PR TITLE
fix dnsproxy data race

### LINKED ISSUE #33897: [DATA RACE]: github.com/cilium/dns.(*Conn).ReadMsgHeader()
```
2024-07-18T14:37:47.357247712Z Read at 0x00c00754eb90 by goroutine 3305340:
2024-07-18T14:37:47.357252450Z   github.com/cilium/dns.(*Conn).ReadMsgHeader()
2024-07-18T14:37:47.357257480Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/client.go:304 +0xc4
2024-07-18T14:37:47.357262319Z   github.com/cilium/dns.(*Conn).ReadMsg()
2024-07-18T14:37:47.357267288Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/client.go:274 +0x3d
2024-07-18T14:37:47.357272528Z   github.com/cilium/dns.handler.func2()
2024-07-18T14:37:47.357277507Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/shared_client.go:173 +0x15a
2024-07-18T14:37:47.357282857Z 
2024-07-18T14:37:47.357288267Z Previous write at 0x00c00754eb90 by goroutine 3305339:
2024-07-18T14:37:47.357293467Z   github.com/cilium/dns.(*Client).SendContext()
2024-07-18T14:37:47.357299017Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/client.go:242 +0xfe
2024-07-18T14:37:47.357304728Z   github.com/cilium/dns.handler()
2024-07-18T14:37:47.357309738Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/shared_client.go:251 +0x773
2024-07-18T14:37:47.357331218Z   github.com/cilium/dns.(*SharedClient).ExchangeSharedContext.gowrap1()
2024-07-18T14:37:47.357336457Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/shared_client.go:298 +0x5d
2024-07-18T14:37:47.357340785Z 
2024-07-18T14:37:47.357345324Z Goroutine 3305340 (running) created at:
2024-07-18T14:37:47.357350383Z   github.com/cilium/dns.handler()
2024-07-18T14:37:47.357355262Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/shared_client.go:161 +0x2ab
2024-07-18T14:37:47.357359330Z   github.com/cilium/dns.(*SharedClient).ExchangeSharedContext.gowrap1()
2024-07-18T14:37:47.357364089Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/shared_client.go:298 +0x5d
2024-07-18T14:37:47.357369478Z 
2024-07-18T14:37:47.357374568Z Goroutine 3305339 (running) created at:
2024-07-18T14:37:47.357379718Z   github.com/cilium/dns.(*SharedClient).ExchangeSharedContext()
2024-07-18T14:37:47.357384506Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/shared_client.go:298 +0x52b
2024-07-18T14:37:47.357389957Z   github.com/cilium/dns.(*SharedClients).ExchangeContext()
2024-07-18T14:37:47.357395206Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/shared_client.go:36 +0xa8
2024-07-18T14:37:47.357400347Z   github.com/cilium/dns.(*SharedClients).Exchange()
2024-07-18T14:37:47.357406027Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/shared_client.go:31 +0x9e
2024-07-18T14:37:47.357410846Z   github.com/cilium/cilium/pkg/fqdn/dnsproxy.(*DNSProxy).ServeDNS()
2024-07-18T14:37:47.357415604Z       /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:1085 +0x279b
2024-07-18T14:37:47.357420224Z   github.com/cilium/dns.(*Server).serveDNS()
2024-07-18T14:37:47.357425222Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/server.go:653 +0x681
2024-07-18T14:37:47.357430022Z   github.com/cilium/dns.(*Server).serveUDPPacket()
2024-07-18T14:37:47.357434741Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/server.go:605 +0x398
2024-07-18T14:37:47.357439500Z   github.com/cilium/dns.(*Server).serveUDP.func2()
2024-07-18T14:37:47.357444228Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/server.go:531 +0xd8
```

seen with 54796b085eb2f8c695db74cef95521e732effacf

### PR DESCRIPTION
**Pull request by bimmlerd**
Please see the commit messages for details.

This pulls in the https://pkg.go.dev/golang.org/x/net/nettest package as a dependency, let me know if I need to separate adding that dependency into a new commit.

Fixes: #33897 

```release-note
The cilium dnsproxy now handles EDNS0 large buffersize advertisements better.
```

### CODE REVIEW

**Review by learnitall — APPROVED** [review]
Vendor changes LGTM, thanks! There's NP IMO keeping it all in the same commit.

**Comment by bimmlerd** [comment]
noticed I forgot a `fmt.Println` and an unused function in a test, removed those and rebased

**Review by pippolo84 — APPROVED** [review]
Nice! And thanks for the thorough explanation! :rocket:

**Pull request merged**
