### PR TITLE
docs: fix spelling of "primarily" in Kubernetes IPAM docs

### PR DESCRIPTION
**Pull request by tklauser**
This was introduced by #10407 and currently makes the spell checker fail.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10458)

### CODE REVIEW

**Comment by tklauser** [comment]
test-docs-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
Maybe we should run the docs check for each PR to not break it accidentally.

**Comment by tklauser** [comment]
> Maybe we should run the docs check for each PR to not break it accidentally.

Sounds like a good idea. Maybe we could directly add a Github action or similar which would trigger the docs check if a PR touches `Documentation/`. I'll have a look...

**Comment by joestringer** [comment]
> Sounds like a good idea. Maybe we could directly add a Github action or similar which would trigger the docs check if a PR touches Documentation/. I'll have a look...

@tklauser I believe that we should do this today, if the `area/documentation` label is set on the PR. However nothing automatically adds that label to the PR right now, so we rely on contributors to configure it.

**Comment by tklauser** [comment]
@joestringer does this mean that the docs test is automatically triggered if the `area/documentation` label is set? If yes, I think it would maybe be possible to extend cilium/github-actions to apply the label automatically on PRs touching `Documentation/`.

**Pull request merged**
