### PR TITLE
Bump vagrant box version for tests to 151

### PR DESCRIPTION
**Pull request by nebril**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7977)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Review by aanm — COMMENTED** [review]
Can you bump it as well in the root's Vagrantfile? Thanks

**Comment by nebril** [comment]
test-docs-please

**Review by raybejjani — APPROVED** [review]

**Comment by nebril** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Pull request merged**
