### PR TITLE
cilium: remove old probe content before restoring assets

### LINKED ISSUE #7971: delete .t probes if they are present

### PR DESCRIPTION
**Pull request by borkmann**
Fixes: #7971
Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8478)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Unrelated CI issue:
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated@3/k8s-1.10-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:374
Cannot connect to vmName  'k8s1-1.10'
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated@3/k8s-1.10-gopath/src/github.com/cilium/cilium/test/k8sT/Health.go:33
```

**Review by brb — APPROVED** [review]
LGTM!

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
timeout provisioning

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
K8s 1.15 vm provisioning fail again

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Now hit `K8s 1.10 net-next vm provisioning fail`

**Comment by borkmann** [comment]
This time we didn't get interrupted during provisioning as last multiple attempts, so the revert got us one step forward, but now it seems the net-next box gets into routing issue:
```
[2019-07-05T20:35:46.233Z]     k8s2-1.10: [0;37mCGROUPS_DEVICES[0m: [0;32menabled[0m
[2019-07-05T20:35:46.233Z]     k8s2-1.10: [0;37mCGROUPS_FREEZER[0m: [0;32menabled[0m
[2019-07-05T20:35:46.233Z]     k8s2-1.10: [0;37mCGROUPS_MEMORY[0m: [0;32menabled[0m
[2019-07-05T20:35:46.233Z]     k8s2-1.10: 	[WARNING SystemVerification]: unsupported kernel release: 5.1.0-rc5+
[2019-07-05T20:35:46.233Z]     k8s2-1.10: 	[WARNING SystemVerification]: unsupported docker version: 18.09.5
[2019-07-05T20:35:46.723Z]     k8s2-1.10: 	[WARNING FileExisting-crictl]: crictl not found in system path
[2019-07-05T20:35:46.723Z]     k8s2-1.10: Suggestion: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
[2019-07-05T20:35:46.723Z]     k8s2-1.10: [discovery] Trying to connect to API Server "192.168.36.11:6443"
[2019-07-05T20:35:46.723Z]     k8s2-1.10: [discovery] Created cluster-info discovery client, requesting info from "https://192.168.36.11:6443"
[2019-07-05T20:35:51.123Z]     k8s2-1.10: [discovery] Failed to request cluster info, will try again: [Get https://192.168.36.11:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 192.168.36.11:6443: getsockopt: no route to host]
[2019-07-05T20:36:00.407Z]     k8s2-1.10: [discovery] Failed to request cluster info, will try again: [Get https://192.168.36.11:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 192.168.36.11:6443: getsockopt: no route to host]
[ stuck in retry loop in here till we hit timeout ]
```

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Pipeline steps all green: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13450/flowGraphTable/

Failed timeout:
```23:35:43  ./archive_test_results.sh: line 3: cd: /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/test: No such file or directory
[Pipeline] sh
23:36:10  Body did not finish within grace period; terminating with extreme prejudice
[Pipeline] // parallel
[Pipeline] }
Error when executing always post condition:
org.jenkinsci.plugins.workflow.steps.FlowInterruptedException
	at org.jenkinsci.plugins.workflow.steps.TimeoutStepExecution.cancel(TimeoutStepExecution.java:160)
	at org.jenkinsci.plugins.workflow.steps.TimeoutStepExecution.access$100(TimeoutStepExecution.java:38)
	at org.jenkinsci.plugins.workflow.steps.TimeoutStepExecution$1.run(TimeoutStepExecution.java:134)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Jenkins issue:
```13:29:10  STEP: Deleting the Istio resources
13:29:11  STEP: Container "client" test connectivity to "server"
13:29:11  STEP: Container "client" test connectivity to "server"
13:29:44  Cannot contact jenkins-node-1: java.lang.InterruptedException
```

**Comment by ianvernon** [comment]
Only commit `fd771ae6193f4ce75398c90ed7229bcdec69ff06` needs to be backported.

**Pull request merged**
