### PR TITLE
v1.10 backports 2021-06-25

### PR DESCRIPTION
**Pull request by tklauser**
* #16577 -- docs: run GitHub action when Charts are touched to check Helm values ref (@qmonnet)
 * #16136 -- bpf: fix iptables masquerading for node -> remote pod traffic (@jibi)
 * #16589 -- vagrant: Bump all Vagrant box versions (@pchaigno)
 * #16621 -- images: Remove trailing newlines before computing SHA256 (@pchaigno)
 * #16572 -- contrib: Identify upstream commits by author and date (@pchaigno)
 * #16650 -- Pick up cilium-cli v0.8.2 (@michi-covalent)
   - Minor conflicts due to bumping from v0.4 rather than v0.8.2. Also had to change `--encryption` to `--encryption=ipsec` in `cilium install` commands in the conformance GH actions.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16577 16136 16589 16621 16572 16650; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by tklauser** [comment]
Forgot to check for other backport PRs in flight before opening. Noticed that #16614 is still open, changing this PR to draft for now.

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
When you do pull this out of draft, looks like the Kind conformance test still needs the encryption fix (or CLI version bump):

https://github.com/cilium/cilium/pull/16654/checks?check_run_id=2913664228
```
Run cilium install --agent-image=quay.io/cilium/cilium-ci --operator-image=quay.io/cilium/operator-generic-ci --version=2c995da3f6a6e72473a9dca648a30e71ea5e8d1a --wait=false --config monitor-aggregation=none \
  cilium install --agent-image=quay.io/cilium/cilium-ci --operator-image=quay.io/cilium/operator-generic-ci --version=2c995da3f6a6e72473a9dca648a30e71ea5e8d1a --wait=false --config monitor-aggregation=none \
    --encryption
  shell: /usr/bin/bash -e {0}
  env:
    kind_version: v0.9.0
    kind_config: .github/kind-config.yaml
    cilium_install_defaults: 
flag needs an argument: --encryption
```

**Comment by tklauser** [comment]
Rebased and fixed the `cillium install --encryption` invocation in all GH actions.

**Comment by tklauser** [comment]
test-backport-1.10

**Review by pchaigno — APPROVED** [review]
My 3 PRs look good.

**Comment by tklauser** [comment]
test-runtime

**Comment by tklauser** [comment]
test-1.17-4.9

**Comment by tklauser** [comment]
test-1.20-4.19

**Comment by tklauser** [comment]
test-runtime

**Pull request merged**
