### PR TITLE
v1.10 backports 2021-05-14

### PR DESCRIPTION
**Pull request by aanm**
* #16063 -- doc: Update diagrams in benchmark report (@tgraf)
 * #16013 -- envoy: Add response headers access logging (@jrajahalme)
 * #16102 -- envoy: Update Envoy to release 1.17.3 (@jrajahalme)
 * #16087 -- doc: Add more generic install section for egress gateway guide (@tgraf)
 * #16083 -- docs: Add note about DNS-related policies on OpenShift  (@twpayne)
 * #16072 -- node-neigh: Fix unit test flake (@brb)
 * #16084 -- Fix 5.10+ complexity issue with `kubeProxyReplacement=disabled` (@pchaigno)
 * #16123 -- docs: add ids to the list of special identities (@bmcustodio)
 * #15422 -- install: Disable kube-proxy-replacement by default (@tgraf)
 * #16162 -- test: set kubeProxyReplacement=probe for upstream k8s tests (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16063 16013 16102 16087 16083 16072 16084 16123 15422 16162; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.10

**Review by pchaigno — APPROVED** [review]
My PR looks good.

**Review by bmcustodio — APPROVED** [review]
> #16123 -- docs: add ids to the list of special identities (@bmcustodio)

My PR looks good too :+1:

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-1.19-5.4

**Comment by pchaigno** [comment]
> test-1.19-5.4, previous: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-5.4/94/

That's a known flake: https://github.com/cilium/cilium/issues/16088.

**Comment by aanm** [comment]
@tgraf PR https://github.com/cilium/cilium/pull/15422 is currently breaking e2e tests for upstream k8s. They have failed twice in a row and this PR https://github.com/cilium/cilium/pull/16156, which doesn't contain https://github.com/cilium/cilium/pull/15422, has passed.

**Comment by aanm** [comment]
test-upstream-k8s

**Review by brb — APPROVED** [review]
My changes LGTM, thanks.

**Pull request merged**
