### PR TITLE
Initial implementation of Kubernetes service spec

### PR DESCRIPTION
**Pull request by aanm**

### CODE REVIEW

**Comment by aanm** [comment]
Waiting for https://github.com/cilium/cilium/pull/109 to be closed

**Comment by aanm** [comment]
Still waiting for #109 but after it's merged the changes on this PR will be minimal.

**Comment by tgraf** [comment]
Can you split out the KVStore abstraction into a separate PR?

**Comment by tgraf** [comment]
@aanm Do you want to merge this before we hook it up to the BPF maps? That's fine but it must be mentioned in the commit message.

**Comment by aanm** [comment]
@tgraf If that's ok from your side then yes. The 2nd version of this code (with performance improvements) could be made on a different PR.

**Comment by tgraf** [comment]
Fine with me, please leave a note in the commit message.

**Pull request merged**
