### PR TITLE
v1.13 Backports 2023-10-30

### PR DESCRIPTION
**Pull request by pippolo84**
* [x] #28465 (@pippolo84)
  - :warning: conflicts due to `cidr.go` moved in main branch
 * [x] #27923 (@mhofstetter)
 * [x] #28767 (@giorio94)
 * [x] #28790 (@pchaigno)
 * [x] #28788 (@pippolo84)
  - :warning: conflicts due to `cidr.go` moved in main branch
 * [x] #28857 (@julianwiedmann)
  - :warning: minor conflicts due to `nat.IPv4` constant missing and different return types for `natMap.OpenOrCreate` used in tests

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 28465 27923 28767 28790 28788 28857
```

### CODE REVIEW

**Comment by pippolo84** [comment]
- @julianwiedmann please review your commits very carefully, I hit some conflicts during the backporting.
- @learnitall I wasn't able to complete the backporting, the main reason is that in v1.13 there isn't a separate file for `ingress_class.go` and I didn't feel comfortable solving all of the conflicts.

**Review by giorio94 — APPROVED** [review]
My commit looks good. Thanks!

**Comment by learnitall** [comment]
Ah @pippolo84, my apologies, my PR shouldn't be backported to 1.13. The [commit introducing IngressClass](https://github.com/cilium/cilium/commit/85671ad30e0ed94a08ad9df43b4079c6c58610b1) support wasn't backported to 1.13 so my PR is inapplicable. Sorry for the trouble!

**Review by mhofstetter — APPROVED** [review]
thanks @pippolo84 !

**Comment by pippolo84** [comment]
Force-pushed to apply the changes suggested for v1.14 [here](https://github.com/cilium/cilium/pull/28870#issuecomment-1786517122).

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks Fabio!

**Review by nathanjsweet — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Review by christarazi — APPROVED** [review]
Typically we document the conflict resolution if the context is important to save in the commit msgs by having a section in the commit body like `[ Backporter's notes: resolved blah blah ]`.

**Comment by pippolo84** [comment]
/test-1.18-4.19

**Comment by pippolo84** [comment]
/test-1.19-4.19

**Comment by pippolo84** [comment]
/test-1.20-4.19

**Review by aditighag — APPROVED** [review]

**Comment by aditighag** [comment]
@pippolo84 Looks like the label updater job failed, so you would have to update the labels manually - https://github.com/cilium/cilium/actions/runs/6734638321/job/18305980125. I checked one of the PRs, and the backport labels are indeed not updated.

**Comment by pippolo84** [comment]
> Looks like the label updater job failed, so you would have to update the labels manually

Updated the labels manually, I'm investigating the workflow failure.

**Pull request merged**
