### PR TITLE
helm: Add support of servicePort in hubble ui service

### PR DESCRIPTION
**Pull request by nishant221**
Signed-off-by: Nishant Shekhar <nishant.ranjanasaxena@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [X] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [X] Thanks for contributing!

The changes in this PR is for adding support to define servicePort of hubble-ui service.

Fixes: #issue-number

```release-note
helm: Add support of servicePort in hubble ui service
```

### CODE REVIEW

**Review by kaworu — CHANGES_REQUESTED** [review]
Thanks for the PR @nishant221! Helm changes LGTM, but the commit title needs to be fixed (the `Signed-off-by:` should be in the commit description, not the commit title).

Also pulling in @cilium/hubble-ui to to review.

**Review by geakstr — APPROVED** [review]

**Comment by kaworu** [comment]
[Travis-CI](https://app.travis-ci.com/github/cilium/cilium/builds/265503033) hit https://github.com/cilium/cilium/issues/27080, re-running.

**Review by kaworu — APPROVED** [review]
Thanks @nishant221, LGTM.

**Review by JonnieDoe — APPROVED** [review]
/lgtm

**Review by rdtiu — APPROVED** [review]
/lgtm

**Review by kaworu — CHANGES_REQUESTED** [review]
[Travis CI workflow](https://app.travis-ci.com/github/cilium/cilium/builds/265503033) hit https://github.com/cilium/cilium/issues/27080, but [Check Patch](https://github.com/cilium/cilium/actions/runs/5979389149/job/16267112112?pr=27703) complain is legit:
```
Warning: WARNING:BAD_SIGN_OFF: Do not use whitespace before Signed-off-by:
#6: 
Signed-off-by: Nishant Shekhar <nishant.ranjanasaxena@gmail.com>
```

@nishant221 can you amend the commit message and remove the leading whitespace from the Signed-off-by trailer please?

**Review by joamaki — APPROVED** [review]

**Comment by julianwiedmann** [comment]
:wave: hi @nishant221 ! I'll take the liberty to flip this PR to draft, until you had time to address the requested change. Please flip it back when ready, thank you!

**Pull request closed without merging**
