### PR TITLE
v1.3 backport 19-04-19

### PR DESCRIPTION
**Pull request by jrfastab**
PR:

#7727 
#7758

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7800)

### CODE REVIEW

**Comment by jrfastab** [comment]
teet-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-docs-please

**Pull request merged**
