### PR TITLE
WIP: test CI L7

### PR DESCRIPTION
**Pull request by brb**

### CODE REVIEW

**Comment by jschwinger233** [comment]
pod-to-pod-with-l7-policy-encryption/ failed due to packet drop between egress proxy and egress proxy, the following pwru log is ack-payload right after syn, from egress proxy (dest node) to ingress proxy (src node):

```
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 a00             0         0x0000 0     2499  10.244.0.239:8080->10.244.3.8:31929(tcp) ip_local_out                 __ip_queue_xmit
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 a00             0         0x0000 0     2499  10.244.0.239:8080->10.244.3.8:31929(tcp) __ip_local_out               ip_local_out
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 a00             0         0x0800 0     2499  10.244.0.239:8080->10.244.3.8:31929(tcp) nf_hook_slow                 __ip_local_out
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 a00             0         0x0800 0     2499  10.244.0.239:8080->10.244.3.8:31929(tcp) ip_output                    ip_local_out
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 a00       cilium_host:3   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) nf_hook_slow                 ip_output
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 a00       cilium_host:3   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) apparmor_ip_postroute        nf_hook_slow
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 a00       cilium_host:3   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) ip_finish_output             ip_output
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 a00       cilium_host:3   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) __ip_finish_output           ip_finish_output
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 a00       cilium_host:3   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) ip_finish_output2            __ip_finish_output
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 a00       cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) __dev_queue_xmit             neigh_hh_output
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 a00       cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) qdisc_pkt_len_init           __dev_queue_xmit
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 a00       cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) tcf_classify                 __dev_queue_xmit
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0         cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) skb_ensure_writable          bpf_skb_pull_data
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0         cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) skb_ensure_writable          bpf_skb_pull_data
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0         cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) skb_ensure_writable          bpf_skb_store_bytes
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0         cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) netdev_core_pick_tx          __dev_queue_xmit
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0         cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) validate_xmit_skb            __dev_queue_xmit
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0         cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) netif_skb_features           validate_xmit_skb
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0         cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) passthru_features_check      netif_skb_features
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0         cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) skb_network_protocol         netif_skb_features
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0         cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) skb_csum_hwoffload_help      validate_xmit_skb
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0         cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) validate_xmit_xfrm           validate_xmit_skb
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0         cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) dev_hard_start_xmit          __dev_queue_xmit
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0         cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) skb_clone_tx_timestamp       veth_xmit[veth]
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0         cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) __dev_forward_skb            veth_xmit[veth]
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0         cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) __dev_forward_skb2           __dev_forward_skb
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0         cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) skb_scrub_packet             __dev_forward_skb2
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0         cilium_host:3   0x0800 1500  2513  10.244.0.239:8080->10.244.3.8:31929(tcp) eth_type_trans               __dev_forward_skb2
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0          cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) __netif_rx                   veth_xmit[veth]
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0          cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) netif_rx_internal            __netif_rx
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0          cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) enqueue_to_backlog           netif_rx_internal
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0          cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) __netif_receive_skb          process_backlog
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0          cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) __netif_receive_skb_one_core __netif_receive_skb
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 0          cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) tcf_classify                 sch_handle_ingress.constprop.0
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) ip_rcv                       __netif_receive_skb_one_core
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) ip_rcv_core                  ip_rcv
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) tcp_wfree                    ip_rcv_core
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) nf_hook_slow                 ip_rcv
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) __inet_lookup_listener       nf_sk_lookup_slow_v4[nf_socket_ipv4]
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) inet_lhash2_lookup           __inet_lookup_listener
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) inet_lhash2_lookup           __inet_lookup_listener
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) ip_route_input_noref         ip_rcv_finish_core.constprop.0
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) ip_route_input_slow          ip_route_input_noref
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) __mkroute_input              ip_route_input_slow
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) fib_validate_source          __mkroute_input
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) ip_forward                   ip_rcv
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) __xfrm_policy_check          ip_forward
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) decode_session4              __xfrm_policy_check
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) security_xfrm_decode_session __xfrm_policy_check
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) __xfrm_route_forward         ip_forward
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) decode_session4              __xfrm_route_forward
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) security_xfrm_decode_session __xfrm_route_forward
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) __icmp_send                  ip_forward
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) __ip_options_echo            __icmp_send
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) security_skb_classify_flow   icmp_route_lookup.constprop.0
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) __xfrm_decode_session        icmp_route_lookup.constprop.0
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) decode_session4              __xfrm_decode_session
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) security_xfrm_decode_session __xfrm_decode_session
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) ip_route_input_noref         icmp_route_lookup.constprop.0
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) ip_route_input_slow          ip_route_input_noref
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) fib_validate_source          ip_route_input_slow
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) __fib_validate_source        fib_validate_source
0xffff979f2a8be2e8 7   ~um-envoy:995322 4026533156 1d003e00   cilium_net:2   0x0800 1500  2499  10.244.0.239:8080->10.244.3.8:31929(tcp) kfree_skb_reason(SKB_DROP_REASON_PKT_TOO_BIG) ip_forward
```

**Comment by jschwinger233** [comment]
```c
// net/ipv4/ip_forward.c
int ip_forward(struct sk_buff *skb)
{
[...]
	mtu = ip_dst_mtu_maybe_forward(&rt->dst, true);
	if (ip_exceeds_mtu(skb, mtu)) {
		IP_INC_STATS(net, IPSTATS_MIB_FRAGFAILS);
		icmp_send(skb, ICMP_DEST_UNREACH, ICMP_FRAG_NEEDED,
			  htonl(mtu));
		SKB_DR_SET(reason, PKT_TOO_BIG);
		goto drop;
	}
[...]
}
```

**Comment by jschwinger233** [comment]
kernel sends an icmp to notify mtu (as showed above), so I captured these icmp packets:

image

It says mtu is 1446, not very sure how kernel gets this number, as all interfaces are set 1500 mtu.

**Comment by jschwinger233** [comment]
```
$ nscontainer kind-control-plane ip r g 10.244.3.8 mark 0xa00
10.244.3.8 via 10.244.0.198 dev cilium_host table 2005 src 10.244.0.198 mark 0xa00 uid 0 
    cache 
```

Due to 2005 routing rules, proxy packets are routed to lo, whose mtu is 65535 :fearful: That could be the reason why proxy sends big packets...

**Comment by brb** [comment]
> however our packet len is 2499

any idea why?

**Comment by jschwinger233** [comment]
Created an issue for this: https://github.com/cilium/cilium/issues/33168

This issue didn't include the reasons for "however our packet len is 2499", I'll explain it here: this is because TCP gso, but the underneath logic is the same, kernel still checks skb's gso_size, which is set by TCP MSS, whose value respects MTU too. So it's still MTU.

**Pull request closed without merging**
