### PR TITLE
[v1.7] Dockerfile: Bump cilium-runtime image

### PR DESCRIPTION
**Pull request by christarazi**

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by joestringer** [comment]
Failed `Cilium-Ginkgo-Tests` with https://github.com/cilium/cilium/issues/12374.

**Comment by joestringer** [comment]
test-backport-1.7

**Comment by joestringer** [comment]
Hit https://github.com/cilium/cilium/issues/12374 again, along with managed etcd flake: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19793/

**Comment by joestringer** [comment]
Running v1.7 branch without this commit to see whether the breakage is already in the tree or possibly introduced by the runtime image bump:

https://github.com/cilium/cilium/pull/12376

**Comment by joestringer** [comment]
Investigation with @jrfastab reveals this appears to be directly relevant to the changes in this PR, because apparently the `cilium-runtime` dockerfile in v1.7 branch will pull latest `bpftool`, which is introducing this regression.

**Review by jrfastab — APPROVED** [review]
Looks reasonable to me. And fixing bpf-next bug now.

**Comment by joestringer** [comment]
I built a new `cilium-runtime` image with `bpftool` generated from the stable Linux 5.4 tree rather than from `bpf-next` latest so this should resolve the issue we were hitting in CI.

**Comment by joestringer** [comment]
test-backport-1.7

**Comment by joestringer** [comment]
I realised that commit d7c30619bbb6cbd76f9a59810a874035e86692e4 specifically tried to bring in a newer version of `bpftool` than would be available in v5.4 so it's probably better to bump to stable release 5.7 since the above commit was in February; 5.6 was in May which means 5.7 would merge in the `bpf-next` from that time to include the change.

**Comment by joestringer** [comment]
test-backport-1.7

**Comment by joestringer** [comment]
Previously-failing test is already showing to be passing: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19797/execution/node/174/log/

**Pull request merged**
