### PR TITLE
pkg/cgroups: Prune excessive debug logging

### PR DESCRIPTION
**Pull request by aditighag**

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
Thanks!

**Comment by pchaigno** [comment]
I see there's a request for review from the tophat. Should we give ownership of this package to the datapath team?

**Comment by aditighag** [comment]
>Should we give ownership of this package to the datapath team?

That should already be the case. I added tophat to the reviewers' list because it's a simple change.

**Review by borkmann — APPROVED** [review]

**Comment by dylandreimerink** [comment]
Integration test is hitting flake #24696. Re-running

**Pull request merged**
