### PR TITLE
v1.8 backports 2020-06-18

### PR DESCRIPTION
**Pull request by jrajahalme**
* #12085 -- api/v1: Add observation proto enum (@glibsm)
 * #12076 -- test: Fix hubble-relay image helm path (@jrajahalme)
 * #12088 -- doc: Misc fixups for Transparent Encryption GSG (@christarazi)
 * #12101 -- daemon: fix panic when starting Cilium (@aanm)
 * #12121 -- bpf: Use `nproc --all` for __NR_CPUS__ (@gandro)
 * #12090 -- test: Fix typo (@jrajahalme)
 * #12114 -- Add Hubble store getter to gain access to k8s data store. (@lzang)
 * #12106 -- Use right CCNP validation (@aanm)
 * #12099 -- test: fix cli flags handling (@nebril)
 * #11905 -- test: Skip Istio test if Ginkgo runs on unsupported runtime. (@jrajahalme)
 * #12109 -- test: Download correct cilium-istioctl for the executing OS. (@jrajahalme)
 * #12089 -- Ginkgo: Simplify all --focus regexes (@jrajahalme)
 * #12110 -- test: Add generated files to .gitignore, avoid pulling stale images. (@jrajahalme)
 * #12126 -- contrib: Misc. fixups for k8s-cilium-exec.sh script (@christarazi)
 * #11979 -- 1.8 documentation updates: Concepts & menu structure (@tgraf)
 * #11969 -- test: Set devices and enable host firewall in kube-proxy CI (@pchaigno)
 * #12143 -- k8s/watchers: fix missing missing CNP/CCNP updates (@aanm)
 * #12150 -- docs: NodePort XDP on Azure (@gandro)
 * #10899 -- operator: Wait for CRDs before running informers (@mrostecki)
 * #12156 -- docs: NodePort XDP on AWS (@borkmann)
 * #12157 -- docs: fix line-break in parsed-literal instance (@borkmann)
 * #12148 -- docs: simplify one of the steps in GKE guide (@errordeveloper)
 * #12139 -- helm: Remove affinity from cilium-etcd-operator (@brb)
 * #12149 -- doc: Specify CILIUM_NAMESPACE for Hubble installation instruction (@michi-covalent)
 * #12097 -- doc: Ensure ConfigMap remains compatible across 1.7 -> 1.8 upgrade (@tgraf)
 * #12146 -- pkg/option: disable K8sEventHandover if Cilium is running without KVStore (@aanm)
 * #12172 -- docs: mention disabling of lro on hv_netvsc (@borkmann)

Added next batch into this branch:

 * #12164 -- Tidy & expand policy docs (@joestringer)
 * #12166 -- daemon: Warn when policy audit mode is enabled (@joestringer)
 * #12108 -- docs: Improve consistency in Azure docs (@errordeveloper)
 * #12033 -- helm: Clean up the hubble-relay DNS name in the UI chart (@michi-covalent)
 * #12174 -- Fix commands in EKS kube-proxy free GSG (@tklauser)
 * #12171 -- pkg/k8s: ignore status field in CNP DeepEqual (@aanm)
 * #12155 -- doc: add Networking and security observability with Hubble guide (@michi-covalent)
 * #12151 -- cilium/charts: set system-{node,cluster}-critical priorityClass for k8s >= 1.17 (@aanm)

Plus:

 * #12134 -- daemon: Fix session affinity map creation (@brb)
 * #12183 -- docs: consolidate BPF map documentation in concepts/ebpf/intro.rst (@tklauser)
 * #12179 -- operator: sync CiliumNodes into etcd instead of k8s nodes (@aanm)
 * #12180 -- Fix native routing cidr missing flag in daemon (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12085 12076 12088 12101 12121 12090 12114 12106 12099 11905 12109 12089 12110 12126 11979 11969 12143 12150 10899 12156 12157 12148 12139 12149 12097 12146 12172 12164 12166 12108 12033 12174 12171 12155 12151 12134 12183 12179 12180; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-backport-1.8

**Comment by jrajahalme** [comment]
test-backport-1.8

**Review by borkmann — APPROVED** [review]

**Comment by borkmann** [comment]
test-backport-1.8

**Review by pchaigno — APPROVED** [review]
:+1: for my changes.

**Comment by borkmann** [comment]
bookinfo flake on 4.19, rerunning

**Comment by borkmann** [comment]
retest-4.19

**Comment by aanm** [comment]
@borkmann there's no point in rerunning the CI without https://github.com/cilium/cilium/pull/12171

**Comment by borkmann** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Review by christarazi — APPROVED** [review]
LGTM for my changes

**Comment by borkmann** [comment]
test-backport-1.8

**Comment by borkmann** [comment]
The 4.19 still has the single bookinfo test fail, as discussed with @aanm and @joestringer it should not block the PR and the fix is coming in the next batch here https://github.com/cilium/cilium/pull/12190 . Once `Cilium-PR-Ginkgo-Tests-K8s` is done & green, we can merge.

**Pull request merged**
