### PR TITLE
bugtool: dump output of routing tables that have rules to prevent proxy looping

### PR DESCRIPTION
**Pull request by ianvernon**
<details>
<summary>Example output from running bugtool</summary>

```
$ cat ip--4-route-show-table-2005.md 
# ip -4 route show table 2005

default via 10.0.0.1 dev cilium_host 
10.0.0.1 dev cilium_host scope link 

$ cat ip--6-route-show-table-2005.md 
# ip -6 route show table 2005

fe80::d829:f8ff:febc:fcdc dev cilium_host metric 1024 pref medium
default via fe80::d829:f8ff:febc:fcdc dev cilium_host metric 1024 pref medium

```
</details>

Fixes: #5828 

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5833)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Tests failed

Build link: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7277/ 

```
22:49:54 K8sServicesTest
22:49:54 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
22:49:54   Checks ClusterIP Connectivity
22:49:54   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
22:49:54     Checks service on same node [AfterEach]
22:49:54     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
22:49:54 
22:49:54     Found a 'JoinEP: ' in Cilium Logs
22:49:54 
22:49:54     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:474
```

Investigating.

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
