### PR TITLE
v1.6 backports 2019-09-06

### LINKED ISSUE #9127: Documentation: typo
In https://cilium.readthedocs.io/en/stable/intro/#simple-networking, under the first bullet point, "Overlay", I believe the phrase is meant to be "Encapsulation-based virtual network spanning all hosts" rather than "Encapsulation based virtual network spawning all hosts".

### PR DESCRIPTION
**Pull request by aanm**
**NOT BACKPORTED DUE CONFLICTS!!!** @borkmann PTAL

 * #9111 -- cilium: prandom based backend selection (@borkmann)
 * #9124 -- cilium: configurable ct timeouts (@borkmann)

**BACKPORTED**:

 * #9081 -- clustermesh: Improve troubleshooting ability (@tgraf)
 * #9090 -- cilium: fix restore v6 router ip to not break pod connectivity on restart (@borkmann)
 * #9094 -- tofqdns: Allow "_" in DNS names to support service discovery schemes (@raybejjani)
 * #9097 -- bump k8s support to 1.15.3 (@aanm)
 * #9102 -- ipam: do not assign v4 addresses for status.IPV6 (@borkmann)
 * #9062 -- bpf: fix asymmetric routing and cilium_host connectivity in v6 tunnel (@borkmann)
 * #9105 -- bump manifests apiVersion to apps/v1 (@aanm)
 * #9053 -- daemon: Improve logging for auto-enabling host-lb (@brb)
 * #9104 -- deps: update etcd to v3.4.0 (@aanm)
 * #9096 -- test: Ensure managed etcd test tears down etcd (@joestringer)
 * #9108 -- docs: Improve sysdump collection guide (@brb)
 * #9126 -- Fix connectivity test example probes (@borancar)
 * #9128 -- Docs: minor spelling corrections (Fixes #9127) (@gkze)
 * #9125 -- Revert "pkg/k8s: add k8s external IPs support" (@aanm)
 * #9133 -- Dockerfile: Use Envoy image with access logging fixes (@jrajahalme)
 * #9101 -- test: fix k8s upstream test (@aanm)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 9081 9090 9094 9097 9102 9062 9111 9105 9053 9104 9096 9108 9124 9126 9128 9125 9133 9101; do contrib/backporting/set-labels.py $pr done 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9148)

### CODE REVIEW

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
never-tell-me-the-odds

**Review by tgraf — APPROVED** [review]

**Comment by ianvernon** [comment]
apt problems: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2455/execution/node/187/log/

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
