### PR TITLE
v1.12 Backports 2023-09-26

### PR DESCRIPTION
**Pull request by giorio94**
* [x] #23093 (@obaranov1)  (verified by @giorio94)
   :information_source: Skipped the hunk modifying the `echo-dpl.yaml` file, as not present in the v1.12 branch.
 * [x] #25426 (@bleggett)
   :warning: Hit a few conflicts due to the different structure of the bpf_lxc.c file, resolved accepting the combination of the
      changes. Please review carefully.
 * [x] #27567 (@jschwinger233)
 * [x] #27996 (@jschwinger233)
 * [x] #28131 (@carnerito)  (verified by @giorio94)
 * [x] #28122 (@qmonnet)
   :information_source: Skipped the hunk related to bpf_tests, as not present in the v1.12 branch.
 * [x] #28133 (@julianwiedmann)
   :information_source: Adapted the hunk to the different variable name.
 * [x] #28161 (@qmonnet)
   :information_source: Skipped a few hunks modifying targets not present in the v1.12 branch.
 * [x] #28145 (@margamanterola)
   :information_source: Reapplied the main hunk to the corresponding file, due to the different docs structure. Additionally backported the paragraph introduced in https://github.com/cilium/cilium/commit/9a01260dedfb4db580d1b841fe53d4f4af9ee359, including the modification from the upstream commit.
 * [x] #28172 (@qmonnet)
   :x: Skipped the backport of c2bf8914a16e71ab5d1e8277fdad02e811a3bb8b as the modified file is not present in the v1.12 branch.
   :information_source: Picked Documentation/requirements.txt verbatim from the main branch to keep it consistent across versions, as we nonetheless use the same image in CI.
 * [x] #28249 (@nbusseneau)
 * [x] #28225 (@nbusseneau)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 23093 25426 27567 27996 28131 28122 28133 28161 28145 28172 28249 28225; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=23093,25426,27567,27996,28131,28122,28133,28161,28145,28172,28249,28225
```

### CODE REVIEW

**Comment by giorio94** [comment]
/test-backport-1.12

**Review by qmonnet — APPROVED** [review]
Backports for my doc PRs look good, thank you!

**Review by nbusseneau — APPROVED** [review]
LGTM for my changes.

**Review by jschwinger233 — APPROVED** [review]

**Comment by giorio94** [comment]
/k8s-1.16-kernel-4.9

**Comment by giorio94** [comment]
/k8s-1.22-kernel-4.9

**Comment by giorio94** [comment]
/k8s-1.23-kernel-4.19

**Comment by giorio94** [comment]
/test-1.16-4.9

**Comment by giorio94** [comment]
/test-1.22-4.9

**Comment by giorio94** [comment]
/test-1.24-net-next

**Comment by giorio94** [comment]
/test-1.23-4.19

**Comment by giorio94** [comment]
All previous failures occurred because Jenkins had been restarted while the tests were in progress.

**Comment by giorio94** [comment]
The build commits check failed due to timeout. Manually run:
* `git rebase --exec "make -C bpf build_all -j $(nproc)" 6bb3bb849ef8^`
* `git rebase --exec "make -C test build -j $(nproc)" 6bb3bb849ef8^`

which both completed successfully locally.

**Comment by margamanterola** [comment]
For my docs commit, in the 1.13 backport, Donia had actually introduced the whole paragraph:
https://github.com/cilium/cilium/pull/28251/commits/b98de6b68f78ff67b2147e740d4729a3b348aab0

Can we do the same here? Thanks!

**Comment by lmb** [comment]
> The build commits check failed due to timeout.

Do we need to bump the timeout then?

**Comment by giorio94** [comment]
> > The build commits check failed due to timeout.
> 
> Do we need to bump the timeout then?

That's what I wonder as well. The most demanding part seems to be building all the datapath configurations, which is skipped if no BPF changes are part of the PR. That's probably the reason why we don't hit this issue consistently in backport PRs (and then the number of commits also plays an important role).

**Comment by giorio94** [comment]
/test-backport-1.12

**Review by margamanterola — APPROVED** [review]
Approved for my commit, thanks

**Comment by giorio94** [comment]
Marking as `dont-merge` until Julian gets the chance to review the backport of https://github.com/cilium/cilium/pull/25426, given that different conflicts were encountered.

**Comment by giorio94** [comment]
/test-1.17-4.9

**Comment by giorio94** [comment]
/test-backport-1.12

**Review by julianwiedmann — APPROVED** [review]
looks good, thank you!

**Comment by giorio94** [comment]
/test-1.18-4.9

**Comment by giorio94** [comment]
Manually run again the build commits steps locally, as timed out in the CI.
All the other tests are green, marking as ready to merge.

**Pull request merged**
