### PR TITLE
[V1.0] backports 2018 06 11

### PR DESCRIPTION
**Pull request by aanm**
Backports

 * PR: #4442 -- allocator: Use DefaultLogger (@tgraf)
 * PR: #4436 -- pkg/bpf: Use the other directory when /sys/fs/bpf is not BPFFS (@tgraf)
 * PR: #4433 -- Test: Demo tests waiting to policies to be applied. (@eloycoto)
 * PR: #4420 -- daemon: return error if createEndpoint fails (@aanm)
 * PR: #4408 -- conntrack: Increase conntrack interval to 1 minute (@tgraf)

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4454)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by mrostecki** [comment]
```
12:00:27 pkg/bpf/bpffs.go:24:2: cannot find package "github.com/cilium/cilium/pkg/defaults" in any of:
12:00:27 	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/cilium/pkg/defaults (vendor tree)
12:00:27 	/usr/local/go/src/github.com/cilium/cilium/pkg/defaults (from $GOROOT)
12:00:27 	/go/src/github.com/cilium/cilium/pkg/defaults (from $GOPATH)
```

It seems that there is no `pkg/defaults` package, so you need to add those constants somewhere in `pkg/bpf/bpffs.go`:

https://github.com/cilium/cilium/blob/master/pkg/defaults/defaults.go#L70-L78

**Review by vadorovsky — CHANGES_REQUESTED** [review]
```
12:00:27 pkg/bpf/bpffs.go:24:2: cannot find package "github.com/cilium/cilium/pkg/defaults" in any of:
12:00:27 	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/cilium/pkg/defaults (vendor tree)
12:00:27 	/usr/local/go/src/github.com/cilium/cilium/pkg/defaults (from $GOROOT)
12:00:27 	/go/src/github.com/cilium/cilium/pkg/defaults (from $GOPATH)
```

It seems that there is no `pkg/defaults` package, so you need to add those constants somewhere in `pkg/bpf/bpffs.go`:

https://github.com/cilium/cilium/blob/master/pkg/defaults/defaults.go#L70-L78

**Review by vadorovsky — CHANGES_REQUESTED** [review]
Maybe let's just drop this commit

https://github.com/cilium/cilium/pull/4454/commits/a9c94f1be4a88f5bef85919812a09eea48987c1a

and put those variables in `pkg/bpf/bpffs.go` in this commit

https://github.com/cilium/cilium/pull/4454/commits/041613d0fc9a6ae1a75b46d67e632f4518e58e5d

**Comment by aanm** [comment]
@mrostecki done!

**Comment by aanm** [comment]
test-me-please

**Comment by tgraf** [comment]
```
15:18:48 ?   	github.com/cilium/cilium/api/v1/server/restapi/prefilter	[no test files]
15:18:50 ?   	github.com/cilium/cilium/api/v1/server/restapi/service	[no test files]
15:19:03 ?   	github.com/cilium/cilium/bugtool	[no test files]
15:19:13 ?   	github.com/cilium/cilium/bugtool/cmd	[no test files]
15:19:13 pkg/maps/tunnel/tunnel.go:24:2: cannot find package "github.com/cilium/cilium/pkg/defaults" in any of:
15:19:13 	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/cilium/pkg/defaults (vendor tree)
15:19:13 	/usr/local/go/src/github.com/cilium/cilium/pkg/defaults (from $GOROOT)
15:19:13 	/go/src/github.com/cilium/cilium/pkg/defaults (from $GOPATH)
15:19:13 Makefile:43: recipe for target 'tests-ginkgo-real' failed
15:19:13 make: *** [tests-ginkgo-real] Error 1
15:19:13 Makefile:29: recipe for target 'tests-ginkgo' failed
15:19:13 make: *** [tests-ginkgo] Error 2
```

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by vadorovsky — APPROVED** [review]

**Pull request merged**
