### PR TITLE
Document new minimum Linux requirements

### PR DESCRIPTION
**Pull request by lmb**
docs: update Linux requirements

    Signed-off-by: Lorenz Bauer <lmb@isovalent.com>

datapath/linux: remove kernel and clang version check

    We check for a minimum kernel and clang version on start up. The kernel
    version check is dubious since the minimum version we need is 4.19. It also
    doesn't handle the fact that RHEL 8 kernels report a version of 4.18 even
    though being functionally close to a 5.4 kernel. The clang version check is
    similarly dubious, since 3.8 hasn't worked in a long time.

    Remove the check outright.

    Signed-off-by: Lorenz Bauer <lmb@isovalent.com>

datapath: move state directory manipulation out of CheckRequirements

    For some reason CheckRequirements creates state directories and also changes
    the working directory of the current process. Move the code into daemon
    setup, which is the only caller.

    Signed-off-by: Lorenz Bauer <lmb@isovalent.com>

Updates: #30456

```release-note
Increase the minimum required kernel version to v5.4 / RHEL 8.6.
```

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]
Looks good to me, thanks!

**Review by markpash — APPROVED** [review]

**Review by sayboras — APPROVED** [review]

**Review by rgo3 — APPROVED** [review]
LGTM. When I grep the codebase I can find more "4.19.57" version strings throughout the codebase in e.g. error logs. Should we eventually clean those up as well? Not saying this should happen in this PR, but maybe we can create a follow-up issue so it doesn't slip? Given you touch '4.8' version strings in this PR as well which should have been removed with the previous minimum Linux bump, it seems that this stuff easily slips the radar.

**Comment by lmb** [comment]
There is https://github.com/cilium/cilium/pull/30872 plus another cleanup PR which I need to make. Probably won't get rid of all of the 4.19, I'll include a list once I make the PR.

**Pull request merged**
