### PR TITLE
Revert "Pick up etcd v3.5.7"

### PR DESCRIPTION
**Pull request by michi-covalent**
[ upstream commit 11773bcb74a7ea4d1b2c40076d7ad6e8b055e35e ]

This reverts commit 83c6201a694c7d74105479e28cc4428c73f74aae.

Let's revert this change until we address #23760.

Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Comment by michi-covalent** [comment]
/test-backport-1.12

**Comment by michi-covalent** [comment]
/test-1.18-4.9

**Comment by michi-covalent** [comment]
/ci-l4lb-1.12

**Comment by michi-covalent** [comment]
[test-1.18-4.9](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.18-kernel-4.9/2486/): https://github.com/cilium/cilium/issues/23892

**Comment by michi-covalent** [comment]
/test-1.18-4.9

**Review by joestringer — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]

**Pull request merged**
