### PR TITLE
helm: Document debug.verbose option

### PR DESCRIPTION
**Pull request by sayboras**
This is just to avoid looking up in the code to find available options.

Signed-off-by: Tam Mach <tam.mach@cilium.io>

### CODE REVIEW

**Review by christarazi — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Review by gandro — APPROVED** [review]
Sweet, thanks!

**Comment by sayboras** [comment]
Reviews are in, CI jobs are all good except one flake, which is tracked in #23236

**Pull request merged**
