### PR TITLE
netkit: Use NETKIT_SCRUB_NONE on primary device

### LINKED ISSUE #33875: Using Cilium V1.16.0 External Access with DNS-Based Policies is not working properly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0-rc.1 and lower than v1.17.0

### What happened?

While following the doc https://docs.cilium.io/en/latest/security/dns/, before running step 'kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes-dns/dns-matchname.yaml', running command 'kubectl exec mediabot -- curl -I -s https://api.github.com | head -1' returns normal response; after applying dns policy, the same command hangs

### How can we reproduce the issue?

Here are the steps:
1. Create Kubernetes cluster using kind:
       kind create cluster --name test --config kind-config.yaml
       and content of kind-config.yaml is:
       
 ```
kind: Cluster
name: test
nodes:
  - role: control-plane
    image: "kindest/node:v1.30.2"
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "bgp=controlplane"
  - role: worker
    image: "kindest/node:v1.30.2"
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "bgp=65001"
  - role: worker
    image: "kindest/node:v1.30.2"
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "bgp=65001"
networking:
  ipFamily: ipv4
  #apiServerAddress: 127.0.0.1
  apiServerPort: 6443
  podSubnet: 10.1.0.0/16
  serviceSubnet: 172.20.0.0/16
  disableDefaultCNI: true
  kubeProxyMode: none
```
  
  2. Install Cilium using command:
      a) git clone Cilium repository
      b) git switch to branch 1.16.0-rc.2
      c) cd to ${patht to cilium}/install/kubernetes
      d)helm upgrade --install --namespace kube-system  cilium ./cilium -f ${path to custom value file}/cilium-values.yaml
      e) content of cilium-values.yaml
      

```
healthChecking: true
endpointHealthChecking:
  # -- Enable connectivity health checking between virtual endpoints.
  enabled: false

cluster:
  name: test
  id: 1

ipv4:
  enabled: true
enableIPv4BIGTCP: true
enableIPv6BIGTCP: false

ipv6:
  enabled: false

kubeProxyReplacement: "true"
# cluster name is test
k8sServiceHost: test-control-plane
k8sServicePort: 6443

routingMode: "native"
# -- Allows to explicitly specify the IPv4 CIDR for native routing.
ipv4NativeRoutingCIDR: "10.1.0.0/16"
enableIPv4Masquerade: true
autoDirectNodeRoutes: true
enableCiliumEndpointSlice: false
endpointRoutes:
  enabled: true

bpf:
  masquerade: true
  datapathMode: netkit

ipam:
  #mode: "cluster-pool"
  mode: "kubernetes"

  operator:
     # -- IPv4 CIDR list range to delegate to individual nodes for IPAM.
    clusterPoolIPv4PodCIDRList: ["10.1.0.0/16"]
    # -- IPv4 CIDR mask size to delegate to individual nodes for IPAM.
    clusterPoolIPv4MaskSize: 26

bgpControlPlane:
  enabled: true
operator:
  replicas: 1

  prometheus:
    enabled: true
```

3. Run command: kubectl create -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes-dns/dns-sw-app.yaml
4. Run command: kubectl exec mediabot -- curl -I -s https://api.github.com | head -1
    Get normal output: HTTP/2 200
5. Run command: kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes-dns/dns-matchname.yaml
6. Run command: kubectl exec mediabot -- curl -I -s https://api.github.com | head -1
    curl request hang here, after timeout, failure with exit code 6
    
 7 doing same above steps with Cilium v1.15.6/v1.15.7, just comment out bpf.datapathMode in cilium-values.yaml, no curl hang, everything is normal

### Cilium Version

Cilium v1.15.6/v1.15.7 --- are normal versions, no issue found with those version
Cilium  V1.16.0-rc.1/ V1.16.0-rc.2 with bpf.datapathMode=netkit, http request to external domain name hang

### Kernel Version

iUbuntu 6.8.0-38-generic x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 24.04)

### Kubernetes Version

Kubernetes v1.30.0
Kind version: kind v0.23.0 go1.21.10 linux/amd64

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #34042: netkit mode with networkpolicy drops k3s kubelet Liveness/Readiness probe packets but veth mode did not
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

Recently I upgrade my homelab k3s cluster from cilium 1.15.7 to 1.16.0 and experiment with the netkit datapath mode, but I found that all the pods in the flux-system namespace fail to start, the remaining pods in the cluster are working as expected. I tried reboot the node but the issue persists.

In the hubble UI, I found that in netkit mode the k3s kubelet healthcheck packets are dropped by cilium. The flux-system namespace uses some k8s networkpolicies to deny all ingress traffic by default, but it is working fine if I switched to veth mode.

### How can we reproduce the issue?

1. install a single node k3s cluster without default cni or networkpolicy addons
    * It's maybe worth mentioning that I have two network interfaces in my setup - eth0 (default route) and wg0, and my k3s node-ip is the wg0 ip, might also reproduced with eth0 and eth1 setup or just single main interface.
2. install cilium 1.16.0, enable netkit datapath mode and use default networkpolicy behavior
3. create a test k8s namespace and some k8s ingress/egress networkpolicies, e.g. [flux-system](https://github.com/fluxcd/flux2/tree/main/manifests/policies)
4. create a demo k8s deployment with Liveness/Readiness probe
5. all the pod in the test namespace are in CrashLoopBackOff state due to failed healthcheck probe
6. check the verdicts in hubble ui showing flow dropped due to Policy denied
    * One of the top source IP of ingress dropped is from the main network interface - eth0.

### Cilium Version

1.16.0

### Kernel Version

6.10.1

### Kubernetes Version

v1.30.2+k3s1

### Regression

_No response_

### Sysdump

[cilium-sysdump-20240727-212749.zip](https://github.com/user-attachments/files/16400293/cilium-sysdump-20240727-212749.zip)

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #35060: Netkit does not work with endpoint routes in some cases
This tracks a group of issues related to netkit that share a similar root cause and discussion around it.

- In #34042 a user reported that liveness/readiness probes stopped working after applying `NetworkPolicy` to a `Pod` when using `netkit` and endpoint routes. The same configuration using `veth` did not have this problem. Some [investigation](https://github.com/cilium/cilium/issues/34042#issuecomment-2350351085) turned up that packets coming from the host namespace get misidentified with the `world` identity instead of `host`. With `NetworkPolicies` applied to the endpoint this leads to packets from liveness/readiness probes getting dropped.
- In #33875 a user [reported](https://github.com/cilium/cilium/issues/33875#issuecomment-2365156011) that running `curl -I -s https://api.github.com/` from a `Pod` hangs when using `netkit` and endpoint routes after applying a `CiliumNetworkPolicy` which specifies `.spec.egress.toFQDNs`. The same configuration using `veth` or with endpoint routes disabled did not have this problem. Some [investigation](https://github.com/cilium/cilium/issues/33875#issuecomment-2375774287) turned up a similar symptoms, with reply DNS traffic returning from the proxy taking on the `world` identity in `cil_to_container`.

In both cases the root cause looks to be that netkit scrubs packets (clearing `skb->mark`) before executing attached BPF programs. This is evident looking at the source for [`netkit_xmit`](https://github.com/torvalds/linux/blob/075dbe9f6e3c21596c5245826a4ee1f1c1676eb8/drivers/net/netkit.c#L66) where `netkit_prep_forward` clears `skb->mark` when crossing network namespaces before `netkit_run()` runs any attached programs.

```c
	netkit_prep_forward(skb, !net_eq(dev_net(dev), dev_net(peer)));
	eth_skb_pkt_type(skb, peer);
	skb->dev = peer;
	entry = rcu_dereference(nk->active);
	if (entry)
		ret = netkit_run(entry, skb, ret);
```

In contrast, when using `veth` TC/TCX hooks are executed *before* the `veth` driver does any packet scrubbing.

#### `netkit` egress processing order
1. [`sch_handle_egress`](https://github.com/torvalds/linux/blob/075dbe9f6e3c21596c5245826a4ee1f1c1676eb8/net/core/dev.c#L4115) is called but does not execute any hooks, since BPF programs are attached directly to the device in `netkit` mode.
2. `netkit_xmit` begins
3. `netkit_xmit` clears `skb->mark`
4. `netkit_xmit` runs `cil_to_container`
5. `netkit_xmit` passes the packet to the peer device

#### `veth` egress processing order
1. [`sch_handle_egress`](https://github.com/torvalds/linux/blob/075dbe9f6e3c21596c5245826a4ee1f1c1676eb8/net/core/dev.c#L4115) is called executing `cil_to_container`.
2. `veth_xmit` begins
3. `veth_xmit` clears `skb->mark`
4. `veth_xmit` passes the packet to the peer device

Since `cil_to_container` uses `ctx->mark` for proxy redirection and policy enforcement this can lead to various issues. For now this only seems to be a problem when using endpoint routes, but if `cilium_host` were to be changed to `netkit` (I'm not sure if this is the case already) it may interfere there as well.

Just to confirm that this is indeed the root cause, patching the netkit driver with this hack locally resolves the reported issues in both cases making behavior consistent between `veth` and `netkit` modes (note: this is not a real fix, just something I used to test my observations).

```
 static void netkit_prep_forward(struct sk_buff *skb, bool xnet)
 {
+       u32 save_mark = skb->mark;
        skb_scrub_packet(skb, xnet);
+       skb->mark = save_mark;
        skb->priority = 0;
        nf_skip_egress(skb, true);
        skb_reset_mac_header(skb);
```

## Tasks
- [ ] Short term, decide whether or not we should allow netkit to be used with endpoint routes enabled. We could add some checks on startup to block this combination. Cons: this might make things stop working for some users who are already using this combination without issue.
- [ ] Document this as a known issue (#35126)
- [ ] Patch netkit. Talking to @borkmann offline, he mentioned maybe adding a new mode to determine if the scrub happens before or after running BPF. If implemented, this needs some follow up work to make sure this mode is configured.
- [ ] Expand test coverage to include some of these scenarios with netkit+endpoint routes.

### PR DESCRIPTION
**Pull request by jrife**
When using endpoint routes with veth, cil_to_container runs before the veth driver scrubs the packet (i.e. clears skb->mark). In netkit mode, cil_to_container is executed after scrubbing the packet. This causes traffic from originating from the host to be miscategorized leading to cases like GH-34042 where enabling netkit causes liveness+readiness probes to fail.

To address this, the `IFLA_NETKIT_SCRUB` and `IFLA_NETKIT_PEER_SCRUB` flags were [recently introduced](https://lore.kernel.org/bpf/20241004101335.117711-1-daniel@iogearbox.net/T/#u) to configure whether or not netkit scrubs the packet when xmiting to the primary or peer devices, respectively. Set `IFLA_NETKIT_SCRUB` to `NETKIT_SCRUB_NONE` to ensure that any mark set in the host namespace is passed to cil_to_container when using netkit with endpoint routes. Set `IFLA_NETKIT_PEER_SCRUB` to `NETKIT_SCRUB_DEFAULT` to ensure that the mark is always cleared before running cil_from_container and passing the packet on to the host namespace.

This PR relies on [this change](https://github.com/vishvananda/netlink/pull/1022) which adds support for these new flags to `github.com/vishvananda/netlink`. 

Fixes: #35060
Fixes: #34042
Fixes: #33875
Fixes: 68953415f03a ("cilium, connector: Add netkit connector")

```release-note
netkit: Fix issue where traffic originating from the host namespace fails to reach the pod when using endpoint routes and network policies.
```

### CODE REVIEW

**Comment by jrife** [comment]
cc @borkmann . Tested this locally with a fresh kernel build and [this change](https://github.com/vishvananda/netlink/pull/1022) to `github.com/vishvananda/netlink`. The issues described in #34042 and #33875 seem to be fixed with this combination. I'm going to wait for that PR to get merged so that we can bump the module version in `go.mod` in this PR.

**Comment by borkmann** [comment]
Looks great to me, thanks! Once the https://github.com/vishvananda/netlink/pull/1022 PR gets merged, we need to pull in the go mod dependencies and then we can get this merged asap.

**Comment by jrife** [comment]
https://github.com/vishvananda/netlink/pull/1022 was merged and I updated this PR. I ended up leaving out the new test case from `.github/workflows/test-e2e-upgrade.yaml`, as I'll need to follow up and make sure there is a test image with the required netkit changes before enabling a test case with netkit+endpoint routes.

**Review by borkmann — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
vendor changes LGTM

**Review by YutaroHayakawa — APPROVED** [review]

**Comment by borkmann** [comment]
> I ended up leaving out the new test case from .github/workflows/test-e2e-upgrade.yaml, as I'll need to follow up and make sure there is a test image with the required netkit changes before enabling a test case with netkit+endpoint routes.

Sounds good, the repo for CI builds is here https://github.com/cilium/little-vm-helper-images/commits/main/ , and I think https://github.com/cilium/little-vm-helper-images/commit/ef9d087877210670ba16451a0ed53cb9c08291af should already have it included (the bpf tree one).

One more thing to follow-up apart from the e2e test addition is that the BPF program attached to the netkit primary device should also at the end clear prio+mark to 0, so that this doesn't go all the way into the Pod. Thanks @YutaroHayakawa for spotting!

**Pull request merged**
