### PR TITLE
test: do not run make clean when running CI tests

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5389)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by eloycoto** [comment]
I already try this, and the results are not satisfied at all, so this PR will not work at all. 

- The clean is made into the Dockerfile too. 
- The container does not have the go-env correct, so each time that the build is in place, there is no cache at all, so need to build it all again. 

The work that I have made: https://github.com/cilium/cilium/pull/4831 the reason to close the RFC will be that no time saved at all without making the container more heavy, and all the people complain about the size of the image. 

For me there is no reason to merge this PR. IMHO. 
Best regards

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by tgraf** [comment]
> The clean is made into the Dockerfile too.

Do we know why?

**Comment by eloycoto** [comment]
No idea, but in the build we call `clean-container` in the before make, I understood that there is a reason for that, due no go build cache in the container, I didn't continue with the work, so I didn't fix that at all. 

https://github.com/cilium/cilium/blob/203803b2d96de29bfed37122dfb905bbd417ab16/Dockerfile#L21

**Comment by tgraf** [comment]
@aanm At least the title of the PR is misleading then. Does this gain anything right now?

**Pull request closed without merging**
