### PR TITLE
update bpf_ct_tests.c to use node_config.h

### PR DESCRIPTION
**Pull request by sahid**
This commit avoids code-duplication.

Signed-off-by: Sahid Orentino Ferdjaoui <sahid.ferdjaoui@industrialdiscipline.com>

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]
Thanks for the cleanup!

>IIRC, this is covered in the privileged unit tests

This is covered by `BPF checks / coccicheck (pull_request)`.

**Review by ldelossa — APPROVED** [review]
Nice.

**Review by NikAleksandrov — APPROVED** [review]

**Comment by pchaigno** [comment]
> > IIRC, this is covered in the privileged unit tests
> 
> This is covered by `BPF checks / coccicheck (pull_request)`.

I don't think so. I introduced the coccichecks and they shouldn't even compile the code.

**Comment by joestringer** [comment]
Looks like it is now running via the bpf linter:

```
$ git grep run_bpf_tests
.github/workflows/lint-bpf-checks.yaml:          make -C test run_bpf_tests || (echo "Run 'make -C test run_bpf_tests' locally to investigate failures"; exit 1)
test/Makefile:.PHONY = all build test run k8s k8s-kind nightly clean run_bpf_tests
test/Makefile:run_bpf_tests:
```

**Comment by pchaigno** [comment]
Uh, that doesn't make a lot of sense either. I'd expect the linter to have one static checks.

Well, at least it's passing so marking ready to merge.

**Pull request merged**
