### PR TITLE
test: Update k8s test versions

### PR DESCRIPTION
**Pull request by aanm**
v1.10.0-beta.0 -> v1.10.0-beta.2

Signed-off-by: André Martins <andre@cilium.io>

Copy of #https://github.com/cilium/cilium/pull/2998 due jenkins misbehavior

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
Although jenkins reports it has failure this PR has passed the last 2 `Cilium-Ginkgo-Test-k8s` builds :tada: (you can check in the details)

This PR is good to merge if the normal tests succeed.

@eloycoto Will check what is wrong why Jenkins for not showing up success in the PR although the builds have passed

**Comment by ianvernon** [comment]
The reason the build failed is because TEST_DIR is not scoped to the `post` stage in `ginkgo-kubernetes-all.Jenkinsfile`.

**Comment by eloycoto** [comment]
@ianvernon working on that, a long PR related with Jenkins is coming today

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
Merging as this has passed CI and I don't think janitor review is really necessary here. We need to add `ginkgo-kubernetes-all.Jenkinsfile` to be owned by cilium/ci .

**Pull request merged**
