### PR TITLE
envoy: Bump golang version

### PR DESCRIPTION
**Pull request by sayboras**
This also includes other go package upgrade as well.

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.16

**Comment by sayboras** [comment]
/test-backport-1.16

**Review by youngnick — APPROVED** [review]

**Comment by aanm** [comment]
added the `dont-merge/wait-until-release` label so that we don't merge this PR because the other stable branches are already prepared for the releases but the 1.16 is still not prepared. Merging this would make the 1.16 to have the patch while other stable branches to not have it. If that's the intention, feel free to remove the label.

**Comment by sayboras** [comment]
Thanks Andre, this can wait :heavy_check_mark:

**Pull request merged**
