### PR TITLE
sockmap fixes for running in example k8s DS

### PR DESCRIPTION
**Pull request by jrfastab**
Fixes hash collision and compile errors when running agent with  --sockops-enable and example k8s DS.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7167)

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Comment by jrfastab** [comment]
Fixes:
https://github.com/cilium/cilium/issues/6967
https://github.com/cilium/cilium/issues/7052

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
Will rebase this on top of https://github.com/cilium/cilium/pull/7153 after its merged because they will conflict and easier to fixup here vs run that PR through the ringer again.

**Review by tgraf — APPROVED** [review]

**Comment by jrfastab** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Comment by ianvernon** [comment]
Build failure for Istio test: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10099

Issue for CI failure appears unrelated, updated GitHub issue tracking it: https://github.com/cilium/cilium/issues/6778

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
