### PR TITLE
test: Allow hostfw tests to run on GKE

### PR DESCRIPTION
**Pull request by pchaigno**
Host firewall tests in tunneling mode can run on GKE. We just need to enable tunneling.

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-me-please

**Comment by nbusseneau** [comment]
test-1.13-netnext

**Comment by nbusseneau** [comment]
test-1.19-4.19

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-1.16-netnext

**Review by borkmann — APPROVED** [review]

**Pull request merged**
