### PR TITLE
Update Go to 1.15.7

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
retest-gke

**Review by rolinh — APPROVED** [review]

**Review by twpayne — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
Received reviews from all assigned teams and CI passed. Marking as "ready to merge".

**Comment by tklauser** [comment]
retest-gke

**Review by kaworu — APPROVED** [review]
@tklauser not completely related but: should we update alpine images to 3.13?

**Comment by tklauser** [comment]
retest-gke

**Comment by tklauser** [comment]
> @tklauser not completely related but: should we update alpine images to 3.13?

@kaworu Good point, thanks. Will send a separate PR doing that (and for `cilium/hubble` as well).

**Comment by tklauser** [comment]
retest-gke

**Comment by tklauser** [comment]
retest-gke

**Pull request merged**
