### PR TITLE
examples/kubernetes-grpc: update grpc image

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5280)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
Where is this image used ? I looked for usages of it in this repository, but couldn't find anything beyond `examples/kubernetes-grpc`. I want to make sure that this fix does not get pushed and break functionality to consumers of it downstream.

**Comment by aanm** [comment]
@ianvernon The image was already created as `v2.0` in https://hub.docker.com/r/cilium/cc-grpc-demo/tags/ the old "latest" is still kept around but TBH if anyone is using `latest` and expect things to not break I've bad news for them. This demo is tested in our CI.

**Comment by ianvernon** [comment]
@aanm Where is it used in the CI? I don't see it used anywhere:

```
$ cd test
$ grep -r "grcp-demo" *
$ echo $?
1
```

**Comment by aanm** [comment]
@ianvernon https://github.com/cilium/cilium/blob/7633db32da2ed7f8290d199c4cb49a5ef6c042ac/test/k8sT/Nightly.go#L448-L518

**Comment by ianvernon** [comment]
@aanm OK, got it.

**Comment by ianvernon** [comment]
test-nightly

**Comment by aanm** [comment]
@ianvernon the image is not build in nightly. The new version was updated to be used in #5297

**Comment by aanm** [comment]
test-docs-please

**Comment by ianvernon** [comment]
@aanm I understand that the image is not built in nightly tests. My main concern was that the new image being built wasn't tested yet in our CI. But, we are using `docker.io/cilium/cc-grpc-demo:v2.0` already in the CI, which was built based off of these changes. So, it has been tested.

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
