### PR TITLE
Revert "Perform reverse NAT at Host Interface"

### PR DESCRIPTION
**Pull request by nbusseneau**
This reverts commit dc4b06ef3b61c342b9fa5adf300898c97661bc25.

Rationale:

- PR #15354 introduced a new test that is frequently failing:
  `K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with vxlan Test NodePort with netfilterCompatMode=true`
- This flake is tracked in issue #17060.
- We are reverting the original PR so as to remove the flake from the CI until we have a fix and are confident the new test is not flaky.

### CODE REVIEW

**Comment by nbusseneau** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]
No conflicts while reverting, right?

**Comment by nbusseneau** [comment]
> No conflicts while reverting, right?

Got one with https://github.com/cilium/cilium/commit/0bb3eed3ff976808328bfe46e019b8c727f063d5#diff-8a383aefc352ba8854dbab293a563fecf7f8916983d013ab36f677293996ca3c because they both added new entries at the end of the `const` section, but that's not a real conflict right? 😁

**Comment by nbusseneau** [comment]
All CI passed, now we're just waiting for approval! /cc @joestringer because we discussed that backport earlier.

**Comment by pchaigno** [comment]
Marking ready to merge considering tests are passing and this is just a revert of a complete feature, so probably no need for all reviews.

**Comment by brb** [comment]
cc @krishgobinath

**Pull request merged**
