### PR TITLE
v1.8 backports 2020-11-17

### PR DESCRIPTION
**Pull request by kaworu**
* #13865 -- ipam: Fix ENI IPAM on smaller instance types (@christarazi)
 * #13996 -- pkg/k8s: trim spaces from loadBalancerSourceRanges (@aanm)
 * #14053 -- ci/github: Replace set-env command by echo (@sayboras)

Ignored by this PR:
 * #14044 -- test: Bump migrate-svc-test image (@brb)
 * #13884 -- cilium: fix redirect limits on multi dev case (@borkmann)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13865 13996 14053; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by kAworu** [comment]
@aanm had to solve a simple conflict on your PR, please take a look (I've updated the commit message accordingly).

**Review by brb — APPROVED** [review]
LGTM for my changes, thanks.

**Review by christarazi — APPROVED** [review]
LGTM for my commits

**Review by aanm — APPROVED** [review]
LGTM for my commits

**Comment by nathanjsweet** [comment]
test-backport-1.8

**Review by sayboras — APPROVED** [review]
LGTM for my commit 👍

**Comment by kAworu** [comment]
test-backport-1.8

**Comment by brb** [comment]
test-backport-1.8

**Review by jibi — APPROVED** [review]

**Comment by jibi** [comment]
test-backport-1.8

**Comment by kAworu** [comment]
test-backport-1.8

**Comment by kAworu** [comment]
Dropping #14044 from this PR in order to pass CI, we can reconsider whether to backport #13032 and #14404 together later on.

**Pull request merged**
