### PR TITLE
workloads/cri-o: Small bug fixes

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4342)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
