### PR TITLE
revert bpf: Warn if another program is using a VXLAN device

### PR DESCRIPTION
**Pull request by nirmoy**
Cilium fails to start with other overlay based cni like multus-cni + flannel

Signed-off-by: Nirmoy Das <ndas@suse.de>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5533)

### CODE REVIEW

**Comment by joestringer** [comment]
@nirmoy Doesn't this just re-introduce the following issue? https://github.com/cilium/cilium/issues/2925

Also, please include the commit reference that is usually included in the revert message (this is usually provided for you when you do `git revert ...`). This helps discussion as we can trace back the original reason for the previous commit and get the context. Here's the commit:

https://github.com/cilium/cilium/commit/2588faee73b0f373d03ac592ff934bb9e056548d

**Comment by tgraf** [comment]
@nirmoy How did you manage to run Cilium + flannel? Are you running Cilium in non-encapsulation mode?

**Comment by nirmoy** [comment]
Sorry its false alarm. I was using "--tunnel=geneve" With Vxlan I get similar issue like  https://github.com/cilium/cilium/issues/2925

**Comment by nirmoy** [comment]
@tgraf So I guess even flannel with vxlan and cilium with geneve should  result in a broken cluster/setup ?

**Comment by joestringer** [comment]
@nirmoy I think there's only a conflict if both are using the same tunnel type.

**Pull request closed without merging**
