### PR TITLE
1.3 backports 19-01-02

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:

* #6475
* #6482 
* #6487 
* #6502 

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6528)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Runtime test failure:

```
Stacktrace

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:340
failed to create container memcache
Expected command: sudo docker run -d --name memcache --net cilium-net -l id.memcache memcached  
To succeed, but it failed:
Exitcode: 125 
Stdout:
 	 
Stderr:
 	 Unable to find image 'memcached:latest' locally
	 docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/memcached/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fmemcached%3Apull&service=registry.docker.io: EOF.
	 See 'docker run --help'.
	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/runtime/memcache.go:55
```

Link: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8708/

Infrastructure related? Trying again.

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
