### PR TITLE
vagrant: Bump box versions to include LLVM patch

### PR DESCRIPTION
**Pull request by gentoo-root**
Ref: https://github.com/cilium/packer-ci-build/pull/362
Ref: https://github.com/cilium/cilium/pull/25338
Ref: https://github.com/cilium/image-tools/pull/215

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.26-net-next

**Comment by joestringer** [comment]
@gentoo-root it looks like this PR stalled. I presume that you found another workaround in the mean time. Do we still need some variation on this PR to solve the underlying issue or should we just close this?

**Pull request closed without merging**
