### PR TITLE
[v1.13] ci/ipsec: Fix downgrade version for release preparation commits

### PR DESCRIPTION
**Pull request by qmonnet**
- [ ] https://github.com/cilium/cilium/pull/30413
- [ ] https://github.com/cilium/cilium/pull/30532

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]

**Comment by qmonnet** [comment]
/test-backport-1.13

**Review by viktor-kurchenko — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Comment by qmonnet** [comment]
/test-1.19-4.19

**Comment by michi-covalent** [comment]
[test-1.19-4.19](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.19/369/): hit https://github.com/cilium/cilium/issues/22749

**Comment by michi-covalent** [comment]
[test-1.26-net-next](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/1183/): vm provisioning failure

**Pull request merged**
