### PR TITLE
[1.15-backport] ipsec: Fix unencrypted traffic when IPsec is used with L7 egress proxy

### PR DESCRIPTION
**Pull request by jschwinger233**
- [x] https://github.com/cilium/cilium/pull/32683 @jschwinger233 

```upstream-prs
 32683
```

### CODE REVIEW

**Comment by jschwinger233** [comment]
/test-backport-1.15

**Comment by jschwinger233** [comment]
/test-backport-1.15

**Comment by jschwinger233** [comment]
CI is almost green except ci-ipsec-e2e https://github.com/cilium/cilium/actions/runs/9411867166/job/25925849574

image

ci-ipsec-e2e's failure is a known racing issue of leak detection that will be fixed by #32930.

I'll drop the last three leak detection patches and mark ready for review.

**Comment by jschwinger233** [comment]
/test-backport-1.15

**Review by julianwiedmann — APPROVED** [review]
looks good, thank you!

**Pull request merged**
