### PR TITLE
ci: Bump ubuntu-next image

### LINKED ISSUE #14956: bpf_sock: Detect when running in host netns on Kind
In bpf_sock we need to detect whether a socket belongs to a host netns (e.g. to allow a 127.0.0.1:NodePort lookup). We do that by comparing self netns cookie against a host nens cookie: https://github.com/cilium/cilium/blob/v1.9.4/bpf/bpf_sock.c#L90.

Unfortunately, this approach doesn't work when running on Kind, as cilium-agent is running in a non-host netns.

As there is no way to query a netns cookie from a userspace, one way to solve it is to write a small dummy program which runs in a separate cgroup, has attached a BPF program attached to the connect hook which pushes current process netns cookie value to a perf ring buffer. Finally, the program reads the value from the buffer, and the value is passed to bpf_sock during compile time via -D.

### PR DESCRIPTION
**Pull request by brb**
The bump is to include \[1\] which is required to properly fix #14956.

\[1\]: https://github.com/torvalds/linux/commit/e8b9eab99232c4e62ada9d7976c80fd5e8118289

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-1.16-netnext

**Comment by brb** [comment]
The EKS conformance suite has nothing to do with the VM image bump. Marking as ready to merge.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI hit - https://github.com/cilium/cilium/issues/11560 (did some investigation)

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-1.16-netnext had a weird failure:
> Test report file /home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/k8s-1.16.xml was length 0

**Comment by brb** [comment]
test-1.16-netnext

**Review by vadorovsky — APPROVED** [review]

**Pull request merged**
