### PR TITLE
Run tooling in module mode by removing `GO111MODULE=off`

### PR DESCRIPTION
**Pull request by ti-mo**
Best reviewed per commit, GH hides diffs to autogenerated files, and they're all one-liners.

Running `make generate-k8s-api` locally mysteriously fails:
```
import "/home/timo/github/cilium/cilium/vendor/k8s.io/code-generator/cmd/go-to-protobuf":
cannot import absolute path
```

Since go modules, using `go run` from within a Go module will automatically select and build the version of the tool based on the contents of go.mod. This makes scripts that call 'go run' on a local package redundant in most cases. This also enables module mode for tools that support it. `./generate-groups.sh` currently does not and is therefore run with Go modules disabled.

Move the GOPATH check into the Makefile to prevent littering GOPATH with generated files if the repo is checked out outside GOPATH and `make generate-k8s-api` is run. Make setting GOPATH and GOBIN explicit and only for the duration of the task.

```release-note
Run tooling in module mode by removing GO111MODULE=off
```

A similar change to `go vet` and `go list` has been proposed here: https://github.com/cilium/cilium/pull/21560.

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Discussed here and there offline, the current changes and approach are making sense to me.

**Review by christarazi — APPROVED** [review]
Nice cleanup!

**Review by tommyp1ckles — APPROVED** [review]
nice work

**Review by rolinh — APPROVED** [review]

**Comment by ti-mo** [comment]
Thanks for the reviews, marking this ready.

**Pull request merged**
