### PR TITLE
examples: Remove obsolete k8s-ingress example

### PR DESCRIPTION
**Pull request by brb**
This PR does the following:

- Removes the `kubernetes-ingress` example which became obsolete once we removed the `--lb` mode support.
- Moves provisioning scripts and deployment files of `contrib/vagrant/start.sh` from the removed example dir to `contrib/vagrant`.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9419)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
OT: we could simplify the `contrib/vagrant/start.sh` and friends by relying on `kubeadm` for provisioning.

**Review by aanm — CHANGES_REQUESTED** [review]
Please leave `examples/kubernetes-ingress/deployments/guestbook/1-redis-master-controller.json ` and friends somewhere else, I usually use that app to test the cluster.

**Comment by aanm** [comment]
> OT: we could simplify the `contrib/vagrant/start.sh` and friends by relying on `kubeadm` for provisioning.

I strongly suggest against it, it's easier to test upcoming k8s versions if we have the ability to change any flag set for any k8s component.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
> Please leave examples/kubernetes-ingress/deployments/guestbook/1-redis-master-controller.json and friends somewhere else, I usually use that app to test the cluster.

@aanm Moved to `examples/misc`.

**Comment by brb** [comment]
test-me-please

**Comment by ianvernon** [comment]
@brb needs rebase.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by aanm — CHANGES_REQUESTED** [review]
```
mv examples/misc examples/misc/guestbook
mv examples/kubernetes-ingress/network-policy/ examples/misc/guestbook/network-policy/
```

**Comment by brb** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Pull request merged**
