### PR TITLE
test: run with NETNEXT=true for K8s-1.10

### PR DESCRIPTION
**Pull request by ianvernon**
Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7752)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Related-to #7751

**Comment by ianvernon** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]
I'm ok with the change, but TBH I do not think that Net-next is the correct one. We should test with the latest LTS kernel, like 4.19. 

Net-next is cool for testing new features, but that boxes can be problematic in some points of time. 

Regards!

**Comment by ianvernon** [comment]
@eloycoto this means we will then have to build an additional box, correct?

**Comment by eloycoto** [comment]
@ianvernon sadly yes, but I think that the testing will be better.

**Comment by ianvernon** [comment]
@eloycoto not a problem, I will create an issue to get a new box built :-)

**Comment by ianvernon** [comment]
@eloycoto created https://github.com/cilium/cilium/issues/7765

**Review by joestringer — COMMENTED** [review]
Very reasonable concept. I think it'd be good to make sure that it's very explicit in the jenkins job UI for a failure that the failure is with particular k8s version and kernel version. I think that the k8s is already pretty well represented, but it'll be important to also include the kernel version so that we don't go chasing up the wrong tree if the k8s-1.10 run fails.

I also agree that a recent stable kernel would be a good choice here. I added a comment to #7765.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11849/

Got stuck:

```
15:59:30  K8sDatapathConfig Transparent encryption DirectRouting 
15:59:30    Check connectivity with automatic direct nodes routes
15:59:30    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
16:52:29  Sending interrupt signal to process
16:52:34  cleaning up VMs started for k8s tests
```

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
@joestringer @eloycoto this was discussed during the monthly CI meeting this morning: https://docs.google.com/document/d/1_ReU7bD4HSwFBrBpHrbclLvZhGUrxdfB-iIiwkVf4Ak/edit# . 

For now, would you be OK with us merging this and testing with the net-next kernel, and problems in the kernel itself cause instability in the CI, we can move to using a specific kernel version? This would allow us to get testing going on newer kernels ASAP. I'm slightly wary about having another VM image to manage with a newer kernel , and @borkmann says that net-next has been fairly stable.

**Comment by joestringer** [comment]
SGTM, my main concern is just making sure it's clear that these are the differences on the two main builds just in case we hit an issue that is specific to either that k8s version or kernel.

**Review by joestringer — APPROVED** [review]

**Review by brb — APPROVED** [review]
I'm in favor of merging this sooner than later to start testing now.

Regarding the visibility, we can change the step name to `K8s-1.10-net-next`, but this can be done in a follow-up PR.
Regarding instability of the net-next, I haven't hit any issues so far.

**Pull request merged**
