### PR TITLE
v1.4 backports 2019-02-10

### PR DESCRIPTION
**Pull request by borkmann**
For after tagging; PRs:

- #7013 
- #7012 
- #7009 
- #7002 
- #6986 
- #6973 
- #6915

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7015)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by borkmann** [comment]
Hit timeout, retesting.

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
Merging so we can install new version into testing cluster

**Review by tgraf — APPROVED** [review]

**Pull request merged**
