### PR TITLE
v1.9 backports 2021-02-17

### PR DESCRIPTION
**Pull request by gandro**
v1.9 backports 2021-02-18

 * #14966 -- Revert kernel-check CLI (@joestringer)
 * #14991 -- Fix ENI compatibility regression between 1.7 <-> 1.8 (@tgraf)
 * ~#14999 -- cilium: encryption fix, ipv4-pod-subnets without encryptnode fails (@jrfastab)~
 * #14994 -- iptables: Skip CILIUM_TRANSIENT_FORWARD for IPv6 (@pchaigno)
 * #14899 -- Install Cilium in kube-system on GKE (@pchaigno)
 * #14938 -- test: Avoid unnecessary restarts of unmanaged pods (@pchaigno)
 * #14942 -- test: Delete all unmanaged pods with a single kubectl delete (@pchaigno)
 * #14995 -- bpf: Enable monitor aggregation in complexity tests (@pchaigno)
 * #15010 -- test: Use Endpoint instead of EndpointSlice in 1.17 (@nebril)
 * #15008 -- backporting: Add support for forked cilium repositories  (@gandro)
 * #14902 -- datapath: Do not log when kernel config not found (@brb)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14966 14991 14994 14899 14938 14942 14995 15010 15008 14902; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
:+1: for my PR.

**Comment by gandro** [comment]
test-backport-1.9

**Review by joestringer — APPROVED** [review]

**Comment by gandro** [comment]
GKE seems to have hit two known flakes and one which I don't recognize, but seems unrelated to the commits here.

Suite-k8s-1.17.K8sDatapathConfig Host firewall Check connectivity with IPv6 disabled **unknown**
Suite-k8s-1.17.K8sServicesTest Checks service across nodes Tests NodePort (kube-proxy) with the host firewall and externalTrafficPolicy=Local #12511
Suite-k8s-1.17.K8sServicesTest External services To Services first endpoint creation #14996

https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/4390/

**Comment by gandro** [comment]
retest-gke

**Comment by pchaigno** [comment]
The two host firewall failures have the error:
```
Cilium DaemonSet not ready yet: desired number of pods is zero
```
We don't have the `kubectl describe ds cilium` unfortunately, but when I saw the same error happen locally it was caused by the fact that we were not running in the `kube-system` namespace. It's not related to the host firewall per se, but to the succession of quick Cilium deployments as far as I could see.

Maybe we should backport https://github.com/cilium/cilium/pull/14899 and related PRs?

**Comment by gandro** [comment]
GKE hit the same known flakes again: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/4394/

@pchaigno To me it makes sense to backport the above CI change. We can do it in the next batch however.

@jrfastab We removed #14999 from the 1.8 backport because there was an issue for it? https://github.com/cilium/cilium/pull/15011#issuecomment-780862805 Should I also remove it from this commit_

**Comment by pchaigno** [comment]
> @pchaigno To me it makes sense to backport the above CI change. We can do it in the next batch however.

I'll mark the PRs for backport then.

> @jrfastab We removed #14999 from the 1.8 backport because there was an issue for it? [#15011 (comment)](https://github.com/cilium/cilium/pull/15011#issuecomment-780862805) Should I also remove it from this PR?

I believe the #14999 fix is incomplete. I removed the needs-backport label and we should probably remove the PR from this set of backports. We can backport everything once we have the complete fix.

**Comment by gandro** [comment]
OK, I dropped #14999  and pulled in the latest backports to ensure GKE can actually get green.

**Comment by gandro** [comment]
The failing BPF check can be ignored, it's a warning due to a overly long commit message.

**Comment by gandro** [comment]
test-backport-1.9

**Review by pchaigno — APPROVED** [review]
My changes look good :+1:

**Comment by gandro** [comment]
@nebril K8s-1.17-kernel-4.9 (not GKE) hit the `K8sServicesTest External services To Services` issue now. Could this be related to https://github.com/cilium/cilium/pull/15010 somehow?

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-4.9/42/

**Comment by gandro** [comment]
retest-gke

**Comment by gandro** [comment]
retest-1.17-4.9

**Comment by gandro** [comment]
retest-1.17-4.9

**Comment by gandro** [comment]
Discussed in the Cilium community meeting: The `K8sServicesTest External services To Services` is also occurring on the master pipeline.

Therefore, this needs to be fixed in master first. Marking this ready to merge.

**Review by christarazi — APPROVED** [review]

**Pull request merged**
