### PR TITLE
Pick up etcd v3.5.7

### PR DESCRIPTION
**Pull request by michi-covalent**
Pick up the latest etcd patch release. This version fixes a bunch of critical security vulnerabilities.

Ref: https://quay.io/repository/coreos/etcd?tab=tags
Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
:ship:

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
@michi-covalent heads up this looks like it broke etcd mode for Cilium 1.12: https://github.com/cilium/cilium/issues/23760

**Comment by michi-covalent** [comment]
struggle

**Pull request merged**
