### PR TITLE
v1.14 Backports 2024-04-10

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #31533 (@chancez)
 * [x] #31714 (@sayboras)
 * [x] #31686 (@sayboras)
 * [x] #29581 (@xyz-li)
 * [x] #31750 (@tklauser)
 * [x] #31728 (@saintdle)
 * [x] #31692 (@katiestruthers)
 * [x] #31847 (@xmulligan)
 * [x] #31851 (@nathanjsweet)

PRs skipped due to conflicts:

 * #31407 (@tommyp1ckles)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31533 31714 31686 29581 31750 31728 31692 31847 31851
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
LGTM for my commits, thanks a lot.

**Comment by sayboras** [comment]
/test-backport-1.14

**Review by chancez — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Review by lmb — COMMENTED** [review]
tophat

**Review by tklauser — APPROVED** [review]
Looks good for my commits, thanks Nicolas!

**Review by xmulligan — APPROVED** [review]

**Pull request merged**
