### PR TITLE
[v1.12] Update CNI to 1.3.0

### PR DESCRIPTION
**Pull request by thorn3r**
v1.12 backports 2023-05-12

 - [ ] #25400 -- Update CNI to 1.3.0 (@anfernee)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 25400; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Comment by thorn3r** [comment]
images in the job have no sha :thinking: they didn't get pushed, so i cant run the script locally either

**Comment by christarazi** [comment]
Drive by comment: was there a reason why this is a manual backport and not just run through the backport tooling in `contrib/backporting/...`? The reason I ask is because the tooling ensure that the process is followed in regards to setting the correct labels, etc., which are important for ensuring that all changes for a release are prepared for the release.

**Comment by thorn3r** [comment]
@christarazi Yee, the PR had 2 commits: the 1st to update CNI and the 2nd to update all the images. Since we don't want to use the images built for main, I didn't want to backport the 2nd commit

**Comment by thorn3r** [comment]
hmm I suppose maybe I could've just not picked the 2nd commit during the backport 🤔

**Comment by thorn3r** [comment]
/ci-l4lb-1.12

**Comment by thorn3r** [comment]
/test-backport-1.12

**Comment by thorn3r** [comment]
/ci-l4lb-1.12

**Comment by thorn3r** [comment]
/ci-multicluster-1.12

**Comment by thorn3r** [comment]
/ci-external-workloads-v1.12

**Comment by joestringer** [comment]
It seems there is something about your user that's not configured right in the Cilium CI systems which makes the jenkins runs not trigger. Worth following up with the testing folks to find out why that's the case. You're an org member (part of the Team team), so I assumed you should be able to trigger those workflows.

**Comment by thorn3r** [comment]
ConformanceGKE (ci-gke-1.12)  is failing for the same reason as the others:
https://github.com/cilium/cilium/pull/25346#issuecomment-1548357619

**Comment by thorn3r** [comment]
/ci-gke-1.12

**Comment by thorn3r** [comment]
/ci-multicluster-1.12

**Comment by thorn3r** [comment]
/test-1.22-4.9

**Comment by asauber** [comment]
/test-1.22-4.9

**Review by nathanjsweet — APPROVED** [review]

**Pull request merged**
