### PR TITLE
v1.9 backports 2021-01-29

### PR DESCRIPTION
**Pull request by pchaigno**
* #13953 -- test: Enable K8sVerifier on 4.19 and net-next CI (@pchaigno)
 * #14451 -- Extend K8sVerifier to maximize program sizes on 4.19 and net-next kernels (@pchaigno)
     - Minor conflicts in several commits.
 * #14607 -- daemon, lbmap: Avoid premature initialization of BPF maps (@christarazi)
     - Minor conflict. Please have a look. 
 * #13934 -- bpf: Replace CALLS_MAP symbol in compile-tested binaries (@pchaigno)
 * #13958 -- docker: Pull llvm-objcopy in cilium-builder (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13953 14451 14607 13934 13958; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by pchaigno** [comment]
test-backport-1.9

**Review by christarazi — APPROVED** [review]
LGTM

**Comment by pchaigno** [comment]
test-gke

**Comment by pchaigno** [comment]
test-missed-k8s

**Comment by christarazi** [comment]
Looks like [net-next](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/1591/testReport/Suite-k8s-1/12/K8sVerifier_Runs_the_kernel_verifier_against_Cilium_s_BPF_datapath/) failed with 

```
/home/jenkins/workspace/Cilium-PR-K8s-1.12-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Expected the kernel verifier to pass for BPF programs
Expected command: kubectl exec -n default test-verifier -- /cilium/test/bpf/verifier-test.sh 
To succeed, but it failed:
Exitcode: 255 
Err: exit status 255
Stdout:
 	 => Loading bpf_lxc.c:from-container...
	 => Loading bpf_lxc.c:to-container...
	 => Loading bpf_host.c:from-netdev...
	 => Loading bpf_host.c:from-host...
	 => Loading bpf_host.c:to-netdev...
	 => Loading bpf_host.c:to-host...
	 => Loading bpf_network.c:from-network...
	 => Loading bpf_overlay.c:from-overlay...
	 => Loading bpf_overlay.c:to-overlay...
	 => Skipping bpf_sock.c:connect4
	 => Skipping bpf_sock.c:post_bind4
	 => Skipping bpf_sock.c:sendmsg4
	 => Skipping bpf_sock.c:recvmsg4
	 => Skipping bpf_sock.c:getpeername4
	 => Skipping bpf_sock.c:post_bind6
	 => Skipping bpf_sock.c:connect6
	 => Skipping bpf_sock.c:sendmsg6
	 => Skipping bpf_sock.c:recvmsg6
	 => Skipping bpf_sock.c:getpeername6
	 => Loading sockops/bpf_sockops.c:sockops...
	 => Loading sockops/bpf_redir.c:sk_msg...
	 => Loading bpf_xdp.c:from-netdev...
	 
Stderr:
 	 skipping kernel config, can't open file: No such file or directory
	 
	 BTF debug data section '.BTF' rejected: Invalid argument (22)!
	  - Length:       3575
	 Verifier analysis:
	 
	 magic: 0xeb9f
	 version: 1
	 flags: 0x0
...
```

and [4.19](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.18-kernel-4.19/37/testReport/Suite-k8s-1/18/K8sVerifier_Runs_the_kernel_verifier_against_Cilium_s_BPF_datapath/) failed with:

```
/home/jenkins/workspace/Cilium-PR-K8s-1.18-kernel-4.19/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Expected deletion of object file sections from bpf/sockops/bpf_sockops.o to succeed.
Expected command: kubectl exec -n default test-verifier -- llvm-objcopy --remove-section=.debug_info --remove-section=.BTF --remove-section=.data /cilium/bpf/sockops/bpf_sockops.o /cilium/bpf/sockops/bpf_sockops.o 
To succeed, but it failed:
Exitcode: 126 
Err: exit status 126
Stdout:
 	 OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"llvm-objcopy\": executable file not found in $PATH": unknown
	 
Stderr:
 	 command terminated with exit code 126
	 

/home/jenkins/workspace/Cilium-PR-K8s-1.18-kernel-4.19/src/github.com/cilium/cilium/test/k8sT/Verifier.go:97
```

**Comment by pchaigno** [comment]
The line that matters for net-next is actually this:

> Tail call map owned by prog type 3, but prog type is 6!

I thought I fixed this issue in https://github.com/cilium/cilium/pull/13927, not sure yet what I'm missing.

For 4.19, I think we need some sort of image update.

I just need to cycles to handle both failures. Same for the v1.8 backport PR.

**Comment by pchaigno** [comment]
test-backport-1.9

**Comment by pchaigno** [comment]
test-missed-k8s

**Review by tklauser — APPROVED** [review]
Image update LGTM.

**Pull request merged**
