### PR TITLE
v1.8 backports 2021-04-29

### PR DESCRIPTION
**Pull request by aanm**
* #15803 -- handle IP addresses modification in running nodes and CEPs (@aanm)
* #15077 -- pkg/k8s: add DeepEqual code generation for Service (@aanm)

PR #15803 depends on #15077, so both had to be backported

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 15077 15803; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.8

**Comment by aanm** [comment]
test-1.11-netnext

**Comment by aanm** [comment]
test-backport-1.8

**Comment by aanm** [comment]
test-1.15-4.9

**Comment by aanm** [comment]
test-1.16-4.9

**Review by rolinh — APPROVED** [review]

**Pull request merged**
