### PR TITLE
workflow: Workaround EKS flake

### PR DESCRIPTION
**Pull request by pchaigno**
See commits for details.

Passing workflow: https://github.com/cilium/cilium/actions/runs/3639862710/jobs/6143833409.

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Wow, nice find. Thanks for the detailed commit description.

**Comment by pchaigno** [comment]
> Wow, nice find. Thanks for the detailed commit description.

Your kudos should go to @NikAleksandrov :slightly_smiling_face:

**Review by NikAleksandrov — APPROVED** [review]
As we discussed, I think this is enough since we already have the option to delete the aws-cni daemonset. We should document the behaviour somewhere to have for future reference.

**Review by nebril — APPROVED** [review]
Can we make AWS operator delete this DS?

**Comment by pchaigno** [comment]
> Can we make AWS operator delete this DS?

@nebril I think we don't want to remove this DaemonSet for users, outside of CI: https://github.com/cilium/cilium-cli/pull/208.

**Comment by pchaigno** [comment]
The workflow passed as shown in the first post. Reviews are in except for the github-sec review but the PR doesn't affect the way the workflow is ran so it shouldn't affect the security impact. I'm merging.

**Pull request merged**
