### PR TITLE
daemon: Add KubeProxyReplacement to cilium status cmd

### PR DESCRIPTION
**Pull request by brb**
This PR adds kube-proxy replacement configuration to the `cilium status` cmd. E.g.:

```
$ cilium status
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.17 (v1.17.2) [linux/amd64]
Kubernetes APIs:        ["CustomResourceDefinition", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [NodePort, ExternalIPs, HostReachableServicesTCP, HostReachableServicesUDP]
Cilium:                 Ok   OK
NodeMonitor:            Disabled
Cilium health daemon:   Ok
IPAM:                   IPv4: 4/65535 allocated from 10.1.0.0/16,
Controller Status:      17/17 healthy
Proxy Status:           OK, ip 10.1.28.236, port-range 10000-20000
Cluster health:       0/1 reachable   (2020-02-05T14:02:54+01:00)
  Name                IP              Reachable   Endpoints reachable
    ceuse (localhost)   10.5.57.1       true        false
```

Reviewable per commit.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10059)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]
Looks good!

**Review by aanm — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by borkmann** [comment]
provisioning error

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Btw, one more thought. We should also dump the used node-port port-range and whether we use snat or dsr for node-port services. Can also be follow-up, but we should do this as well for 1.7.

**Comment by borkmann** [comment]
Perhaps makes sense to slightly adapt the output for above case, for example:
```
$ cilium status
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.17 (v1.17.2) [linux/amd64]
Kubernetes APIs:         ["CustomResourceDefinition", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    Strict
- NodePort:              Enabled [SNAT, 30000-32767]
- ExternalIPs:           Enabled
- HostReachableServices: Enabled [TCP, UDP]
Cilium:                  Ok   OK
NodeMonitor:             Disabled
Cilium health daemon:    Ok
IPAM:                    IPv4: 4/65535 allocated from 10.1.0.0/16,
Controller Status:       17/17 healthy
Proxy Status:            OK, ip 10.1.28.236, port-range 10000-20000
Cluster health:          0/1 reachable   (2020-02-05T14:02:54+01:00)
  Name                IP              Reachable   Endpoints reachable
    ceuse (localhost)   10.5.57.1       true        false
```

**Comment by brb** [comment]
> Perhaps makes sense to slightly adapt the output for above case, for example:

Makes sense, will do it as a follow-up.

**Comment by brb** [comment]
test-me-please

**Pull request merged**
