### PR TITLE
Correctly use cli installer action in ipv4/6 smoke

### PR DESCRIPTION
**Pull request by bleggett**
Fix for regression in smoke test script introduced by https://github.com/cilium/cilium/pull/25493

See https://github.com/cilium/cilium/pull/25493/files#r1362783422

### CODE REVIEW

**Review by joestringer — CHANGES_REQUESTED** [review]
Thanks! Looks like `.github/workflows/tests-smoke.yaml` could do with the same treatment.

**Review by joestringer — COMMENTED** [review]
Changes LGTM, could you rebase to main / drop the merge commit?

**Comment by joestringer** [comment]
^ Context, we try to keep Cilium git log linear for easier bisectability, and keep the commit messages simple and well-written. The original commit message is good from that perspective, but the second one lacks context. Perhaps squash them all together during the rebase and just reword the commit to drop the IPv6 part?

**Review by joestringer — APPROVED** [review]
LGTM

**Review by nbusseneau — APPROVED** [review]

**Comment by nbusseneau** [comment]
Both affected workflows passed, no need to run the rest of the CI on this one, marking ready to merge.

**Pull request merged**
