### PR TITLE
Tests: Update Nightly to kubernetes 1.9

### PR DESCRIPTION
**Pull request by eloycoto**
Updating Nightly test to Kubernetes 1.9 instead of 1.8

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

### CODE REVIEW

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Review by ianvernon — APPROVED** [review]
Approving based on the change alone; if there is a test failure related to K8s 1.9, it should be triaged and fixed accordingly as part of this PR so we can maintain green nightly runs.

**Comment by eloycoto** [comment]
test-me-please

**Pull request merged**
