### PR TITLE
fix：make fsnotify event more readable

### PR DESCRIPTION
**Pull request by yulng**
Signed-off-by: yulng <wei.yang@daocloud.io>

https://github.com/fsnotify/fsnotify/pull/477 and [fsnotify release](https://github.com/fsnotify/fsnotify/releases/tag/v1.6.0) .
so to make fsnotify event more readable

Thanks

### CODE REVIEW

**Review by YutaroHayakawa — APPROVED** [review]
LGTM

**Review by ldelossa — APPROVED** [review]

**Comment by ldelossa** [comment]
@yulng can you rebase this branch on latest master? Thanks.

**Comment by yulng** [comment]
> @yulng can you rebase this branch on latest master? Thanks.

rebase it and push again just now
thanks

**Comment by pchaigno** [comment]
This pull request was reverted in https://github.com/cilium/cilium/pull/27694 because it introduced a regression in IPsec key rotations.

**Pull request merged**
