### PR TITLE
gh/workflows: Rename ci-datapath to ci-e2e

### PR DESCRIPTION
**Pull request by brb**
The GHAs are no longer testing only the datapath features.

The ownership will be addressed by \[1\].

\[1\]: https://github.com/cilium/cilium-cli/issues/1549

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]

**Comment by viktor-kurchenko** [comment]
There are few lines like: `description: Datapath tests in progress...`.
Should they be renamed also?

**Review by viktor-kurchenko — APPROVED** [review]
LGTM.

**Comment by brb** [comment]
> There are few lines like: description: Datapath tests in progress....

@viktor-kurchenko Nice catch! Let me update in a sec.

**Review by viktor-kurchenko — APPROVED** [review]

**Comment by brb** [comment]
cc @nbusseneau : Once this PR has been merged, we need to update the required jobs.

**Comment by joestringer** [comment]
[ConformanceIngress CI failed](https://github.com/cilium/cilium/actions/runs/4851488367/jobs/8645379148?pr=25164) with strange infra-looking issue:

```
Run curl -sSL --remote-name-all [https://github.com/cilium/cilium-cli/releases/download/v0.13.2/cilium-linux-amd64.tar.gz{](https://github.com/cilium/cilium-cli/releases/download/v0.13.2/cilium-linux-amd64.tar.gz%7B),.sha[2](https://github.com/cilium/cilium/actions/runs/4851488367/jobs/8645379148?pr=25164#step:4:2)56sum}
  curl -sSL --remote-name-all [https://github.com/cilium/cilium-cli/releases/download/v0.13.2/cilium-linux-amd64.tar.gz{](https://github.com/cilium/cilium-cli/releases/download/v0.13.2/cilium-linux-amd64.tar.gz%7B),.sha256sum}
  sha256sum --check cilium-linux-amd64.tar.gz.sha256sum
  sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin
  rm cilium-linux-amd64.tar.gz{,.sha256sum}
  cilium version
  shell: /usr/bin/bash -e {0}
  env:
    cilium_cli_version: v0.1[3](https://github.com/cilium/cilium/actions/runs/4851488367/jobs/8645379148?pr=25164#step:4:3).2
    kind_version: v0.17.0
    kind_config: .github/kind-config.yaml
    metallb_version: 0.12.1
    timeout: 5m
    QUAY_ORGANIZATION: cilium
    QUAY_ORGANIZATION_DEV: cilium
sha256sum: WARNING: 1 computed checksum did NOT match
cilium-linux-amd6[4](https://github.com/cilium/cilium/actions/runs/4851488367/jobs/8645379148?pr=25164#step:4:4).tar.gz: FAILED
Error: Process completed with exit code 1.
```

I see that this PR only makes changes to completely unrelated workflows, so the above does not need to block the merging (however, the standard process is to triage, link failures and re-run CI).

**Pull request merged**
