### PR TITLE
pkg/k8s: remove unused ContainerStatuses field

### LINKED ISSUE #13136: Review duplicate processing in pod watcher callbacks that can cause increased resources utilization
I observed that when a pod is deleted, cilium Kubernetes pod watcher triggers `updateK8sPodV1` [1], which in turn calls add `addK8sPodV1`[2]. 

Both these functions do parsing of various pod related data. For example, `updateK8sPodV1` compares annotations and labels for the received old and new pod objects, while `addK8sPodV1` upserts host to port mappings in the service maps, upserts an IP entry in ipcache, parses named ports for updates, etc. These events are then immediately followed by the actual `deleteK8sPodV1` event, which would trigger deletion of all the saved internal state associated with the pod. 

The duplicated and redundant processing can lead to increased CPU utilization. I haven't measured the actual CPU cycles consumed during the processing that happens, but it's good to collect that data in high scale and dynamic clusters. 

I added a `comparator.Compare` [3] (thanks to @joestringer for the pointer) call in the `updateK8sPodV1` to see why the update callback function was being called [4].  

We should review these call chains to see if they are intended to be this way, and if not, can the processing during pod update callbacks be optimized? Additionally, we should check if any of the unused fields in the slim pod object need be trimmed further in order to avoid triggering the update events in such cases?

Here is the diff printed by the compare method during one of the iterations - 

```
Unified diff:
--- a
+++ b
@@ -1,83 +1,62 @@
 &v1.Pod{
     TypeMeta:   v1.TypeMeta{},
     ObjectMeta: v1.ObjectMeta{
         Name:            "lrp-pod",
         Namespace:       "default",
         UID:             "24f7b0bb-1f03-4db6-a3f0-6a9c60a86000",
-        ResourceVersion: "3348474",
+        ResourceVersion: "3348479",
         Labels:          {"app":"proxy"},
         Annotations:     {"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"proxy\"},\"name\":\"lrp-pod\",\"namespace\":\"default\"},\"spec\":{\"containers\":[{\"image\":\"nginx\",\"name\":\"lrp-pod\",\"ports\":[{\"containerPort\":80,\"name\":\"tcp\",\"protocol\":\"TCP\"}]}]}}\n"},
     },
     Spec: v1.PodSpec{
         InitContainers: nil,
         Containers:     {
             {
                 Name:  "lrp-pod",
                 Image: "nginx",
                 Ports: {
                     {Name:"tcp", HostPort:0, ContainerPort:80, Protocol:"TCP", HostIP:""},
                 },
                 VolumeMounts: {
                     {MountPath:"/var/run/secrets/kubernetes.io/serviceaccount"},
                 },
             },
         },
         ServiceAccountName: "default",
         HostNetwork:        false,
     },
     Status: v1.PodStatus{
         HostIP: "192.168.33.11",
         PodIP:  "10.16.242.176",
         PodIPs: {
             {IP:"10.16.242.176"},
         },
         StartTime: &v1.Time{
             Time: time.Time{
                 wall: 0x0,
                 ext:  63735305066,
                 loc:  &time.Location{
                     name: "Local",
                     zone: {
                         {name:"UTC", offset:0, isDST:false},
                     },
                     tx: {
                         {when:-576460752303423488, index:0x0, isstd:false, isutc:false},
                     },
                     cacheStart: -576460752303423488,
                     cacheEnd:   9223372036854775807,
                     cacheZone:  &time.zone{(CYCLIC REFERENCE)},
                 },
             },
         },
         ContainerStatuses: {
             {
-                Name:  "lrp-pod",
-                State: v1.ContainerState{
-                    Running: &v1.ContainerStateRunning{
-                        StartedAt: v1.Time{
-                            Time: time.Time{
-                                wall: 0x0,
-                                ext:  63735305069,
-                                loc:  &time.Location{
-                                    name: "Local",
-                                    zone: {
-                                        {name:"UTC", offset:0, isDST:false},
-                                    },
-                                    tx: {
-                                        {when:-576460752303423488, index:0x0, isstd:false, isutc:false},
-                                    },
-                                    cacheStart: -576460752303423488,
-                                    cacheEnd:   9223372036854775807,
-                                    cacheZone:  &time.zone{(CYCLIC REFERENCE)},
-                                },
-                            },
-                        },
-                    },
-                },
+                Name:        "lrp-pod",
+                State:       v1.ContainerState{},
                 Image:       "nginx:latest",
                 ImageID:     "docker-pullable://nginx@sha256:5dc39e6ea65a5bf52d0cb6cbe687445a03ab7fdf1382cf51d6af7f2e0c2f464b",
                 ContainerID: "docker://240f6735becc0e6eca11de7c9f2f545135d66348d5339c931d789c6c648dbab4",
             },
         },
     },
 }
```

[1] https://github.com/cilium/cilium/blob/d7433cff08bfd29b3aa3b15769bd01fdfcb115ca/pkg/k8s/watchers/pod.go#L215
[2] https://github.com/cilium/cilium/blob/d7433cff08bfd29b3aa3b15769bd01fdfcb115ca/pkg/k8s/watchers/pod.go#L188
[3] https://github.com/cilium/cilium/blob/d7433cff08bfd29b3aa3b15769bd01fdfcb115ca/pkg/comparator/comparator.go#L23
[4] https://github.com/cilium/cilium/blob/d7433cff08bfd29b3aa3b15769bd01fdfcb115ca/pkg/k8s/watchers/pod.go#L86

### PR DESCRIPTION
**Pull request by aanm**
This field is no longer used in the Cilium code base. Having it makes
Cilium to process useless events when a pod is being removed as the
container status will be updated, causing an update event, and only
afterwards Cilium receives a delete pod event.

Signed-off-by: André Martins <andre@cilium.io>

Fixes: https://github.com/cilium/cilium/issues/13136

```release-note
Stop listening for Pod Container Status events, making Cilium's Kubernetes event watcher less resource consuming when a pod is deleted.
```

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by michi-covalent — APPROVED** [review]
🚀

**Review by christarazi — APPROVED** [review]

**Review by aditighag — APPROVED** [review]

**Comment by aanm** [comment]
retest-net-next

**Comment by aanm** [comment]
retest-net-next

**Comment by aanm** [comment]
remove the needs-backport label since this code does not exist in v1.8 branch

**Pull request merged**
