### PR TITLE
add timeouts to init.sh and join_ep.sh

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Review by borkmann — APPROVED** [review]

**Review by aalemayhu — COMMENTED** [review]
Adding a test would have been nice, but otherwise looks good.

**Comment by aanm** [comment]
@scanf To test what? :-)

**Comment by aalemayhu** [comment]
@aanm that the timeout actually occurs :)

**Comment by aanm** [comment]
@scanf I understand your concerns but on this case I would be basically testing go lib.

**Comment by tgraf** [comment]
I think it's fine without a test

**Pull request merged**
