### PR TITLE
v1.13: k8s: Restrict configuring reserved:init policy via CNP

### PR DESCRIPTION
**Pull request by joestringer**
* [ ] #28007 (@joestringer)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 28007; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=28007
```

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]
✨

**Comment by joestringer** [comment]
/test-backport-1.13

**Comment by joestringer** [comment]
k8s-1.19-kernel-4.19 (test-1.19-4.19) -  Provisioning failed: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.19/146/execution/node/90/log/

**Comment by joestringer** [comment]
test-1.19-4.19

**Comment by joestringer** [comment]
/test-1.19-4.19

**Review by aanm — APPROVED** [review]

**Comment by joestringer** [comment]
/test-1.17-4.19

**Pull request merged**
