### PR TITLE
v1.13 Backports 2023-08-09

### PR DESCRIPTION
**Pull request by joamaki**
* [x] #26975 (@mhofstetter)
 * [x] #27193 (@nbusseneau) (:warning: minor conflicts, few missing files)
 * [x] #27184 (@pchaigno)
 * [x] #27250 (@qmonnet)
 * [ ] #27168 (@learnitall)
 * [x] #27312 (@julianwiedmann)
 * [x] #27346 (@qmonnet) (:warning: minor conflicts)
 * [ ] #27230 (@brb)
 * [x] #27365 (@mhofstetter)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 26975 27193 27184 27250 27168 27312 27346 27230 27365; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=26975,27193,27184,27250,27168,27312,27346,27230,27365
```

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]

**Review by mhofstetter — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]
Looks good, thanks for addressing the conflicts on my second commit! :pray:

**Review by nbusseneau — APPROVED** [review]

**Review by brb — APPROVED** [review]
Thanks!

**Review by learnitall — APPROVED** [review]
Thank you!

**Review by ldelossa — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
Resolved conflict.

**Comment by YutaroHayakawa** [comment]
/test-backport-1.13

**Comment by YutaroHayakawa** [comment]
Paul's change is a document only. He's out now and CI is passing. I think it's safe to go forward.

**Comment by YutaroHayakawa** [comment]
@cilium/github-sec @cilium/ci-structure Could someone take a look and approve if it seems ok?

**Review by brlbil — APPROVED** [review]
@nbusseneau has already approved, interesting that it requires reviews from github-sec, and structure

**Comment by YutaroHayakawa** [comment]
@brlbil Thanks! Yeah, I was also wondering that 🤔

**Pull request merged**
