### PR TITLE
Misc endpoint cleanups

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4642)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
Hit #4644

**Comment by tgraf** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
