### PR TITLE
improve kernel probe for host reachable services and fix compile warns

### PR DESCRIPTION
**Pull request by borkmann**
See commit msg. /cc @brb

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10111)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Comment by borkmann** [comment]
provision failure

**Comment by borkmann** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
