### PR TITLE
Update vishvananda/netlink

### LINKED ISSUE #30744: [1.15] DNS proxy doesn't get traffic when ipv6 is disabled in kernel
### Is there an existing issue for this?

- [X] I have looked for the existing issues, and related are:
  - #30563
  - #29238

### What happened?

I run a K3s cluster and recently upgraded to Cilium 1.15 from 1.14.7 (where everything was working flawlessly). I noticed that DNS stopped working, so I went to investigate and found, after a bit of time, that

```yaml
          rules:
            dns:
              - matchPattern: '*'
```

in a CNP like

```yaml
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: coredns
      toPorts:
        - ports:
            - port: '53'
              protocol: ANY
          rules:
            dns:
              - matchPattern: '*'
```

was the issue. When I remove the DNS proxy, everything starts to work again (but I loose the L7 FQDN functionality, of course).

---

K3s setup arguments related to this issue:

```bash
K3S_ARGUMENTS+=('--disable=servicelb,traefik,coredns')
K3S_ARGUMENTS+=('--flannel-backend=none')
K3S_ARGUMENTS+=('--disable-network-policy')
K3S_ARGUMENTS+=('--disable-kube-proxy')

K3S_ARGUMENTS+=('--cluster-domain=cluster')

K3S_ARGUMENTS+=('--cluster-cidr=10.10.0.0/16')
K3S_ARGUMENTS+=('--service-cidr=10.100.0.0/16')
K3S_ARGUMENTS+=('--cluster-dns=10.100.0.10')
```

I am deploying a custom coreDNS (which is not the issue because this exact coreDNS instance works flawlessly without Cilium's DNS proxy).

---

I am applying Cilium with Helm; here is the base configuration of the chart:

```yaml
# upgradeCompatibility: '1.15'

operator:
  replicas: 1
  rollOutPods: true

hubble:
  enabled: false
  # relay:
  #   enabled: true
  # peer-service:
  #   clusterDomain: cluster
  # ui:
  #   enabled: true
  #   frontend:
  #     server:
  #       ipv6:
  #         enabled: false

bpf:
  autoMount:
    enabled: true
  masquerade: true

preflight:
  enabled: false

ipv4:
  enabled: true
ipv6:
  enabled: false

ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList: [ 10.10.0.0/16 ]
    clusterPoolIPv4MaskSize: 24

ipv4NativeRoutingCIDR: 10.10.0.0/16

kubeProxyReplacement: true
k8sServiceHost: <MY PUBLIC IPv4>
k8sServicePort: 6443
```

I played around with the settings, but I was unable to find a working configuration.

---

When I now run a test pod (like Alpine) in a test namespace (say `podinfo`) to check whether DNS works, I can see that when the DNS proxy is enabled, it does not work. I have traced the flow when executing `dig +short google.de A`:

```console
$ # without DNS proxy
$ kubectl -n kube-system exec -ti cilium-9mh6p --container cilium-agent -- cilium-dbg monitor | grep -F -- '10.10.0.67'
Policy verdict log: flow 0x6376f802 local EP ID 120, remote ID 11394, proto 17, egress, action allow, auth: disabled, match L3-L4, 10.10.0.67:46401 -> 10.10.0.198:53 udp
Policy verdict log: flow 0x6376f802 local EP ID 82, remote ID 2844, proto 17, ingress, action allow, auth: disabled, match L3-L4, 10.10.0.67:46401 -> 10.10.0.198:53 udp
-> endpoint 82 flow 0x6376f802 , identity 2844->11394 state new ifindex lxc1380f4aa9917 orig-ip 10.10.0.67: 10.10.0.67:46401 -> 10.10.0.198:53 udp
-> endpoint 120 flow 0x0 , identity 11394->2844 state reply ifindex lxcf3b10c2203a8 orig-ip 10.10.0.198: 10.10.0.198:53 -> 10.10.0.67:46401 udp

$ # with DNS proxy
$ kubectl -n kube-system exec -ti cilium-9mh6p --container cilium-agent -- cilium-dbg monitor | grep -F -- '10.10.0.67'
Policy verdict log: flow 0xa318316f local EP ID 120, remote ID 11394, proto 17, egress, action redirect, auth: disabled, match L3-L4, 10.10.0.67:59365 -> 10.10.0.198:53 udp
-> proxy port 35591 flow 0xa318316f , identity 2844->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.10.0.67:59365 -> 10.10.0.198:53 udp
Policy verdict log: flow 0xdac88a8a local EP ID 120, remote ID 11394, proto 17, egress, action redirect, auth: disabled, match L3-L4, 10.10.0.67:52522 -> 10.10.0.198:53 udp
-> proxy port 35591 flow 0xdac88a8a , identity 2844->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.10.0.67:52522 -> 10.10.0.198:53 udp
Policy verdict log: flow 0x8b249f1a local EP ID 120, remote ID 11394, proto 17, egress, action redirect, auth: disabled, match L3-L4, 10.10.0.67:41475 -> 10.10.0.198:53 udp
-> proxy port 35591 flow 0x8b249f1a , identity 2844->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.10.0.67:41475 -> 10.10.0.198:53 udp
```

In this example, `10.10.0.67` is the IP of the Alpine pod, and `10.10.0.198` is the IP of the coreDNS pod. `dig` shows

```console
$ # without DNS proxy
$ dig A googledaewdawda.de +short
142.250.186.163

$ # with DNS proxy
$ dig A googledaewdawda.de
;; communications error to 10.100.0.10#53: timed out
;; communications error to 10.100.0.10#53: timed out
;; communications error to 10.100.0.10#53: timed out
;; no servers could be reached
```

The CNP looks like this:

```yaml
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy

metadata:
  name: alpine

spec:
  endpointSelector:
    matchLabels:
      app: alpine

  egress:
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: '80'
            - port: '443'

    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: coredns
      toPorts:
        - ports:
            - port: '53'
              protocol: ANY
          rules:
            dns:
              - matchPattern: '*'

```

---

I am not sure where to look next. Here is some more information that might be useful:

```console
$ kubectl -n kube-system exec -ti cilium-9mh6p --container cilium-agent -- cilium-dbg status
KVStore:                 Ok   Disabled
Kubernetes:              Ok   <I TRIED 1.16.1 - 1.29.1> [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    True   [eth0   <MY PUBLIC IPv4> <MY SECOND PUBLIC IPv4> (Direct Routing)]
Host firewall:           Disabled
SRv6:                    Disabled
CNI Chaining:            none
Cilium:                  Ok   1.15.0 (v1.15.0-2db45c46)
NodeMonitor:             Listening for events on 6 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok
IPAM:                    IPv4: 54/254 allocated from 10.10.0.0/24,
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Host Routing:            BPF
Masquerading:            BPF   [eth0]   10.10.0.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       315/315 healthy
Proxy Status:            OK, ip 10.10.0.212, 3 redirects active on ports 10000-20000, Envoy: embedded
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 4095/4095 (100.00%), Flows/s: 121.91   Metrics: Disabled
Encryption:              Disabled
Cluster health:          1/1 reachable   (2024-02-13T18:53:33Z)
Modules Health:          Stopped(0) Degraded(0) OK(11) Unknown(3)

$ # now using the Cilium CLI
$ cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       OK
    \__/       ClusterMesh:        disabled

Deployment             hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
Deployment             cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
DaemonSet              cilium             Desired: 1, Ready: 1/1, Available: 1/1
Deployment             hubble-ui          Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium             Running: 1
                       cilium-operator    Running: 1
                       hubble-ui          Running: 1
                       hubble-relay       Running: 1
Cluster Pods:          52/52 managed by Cilium
Helm chart version:
Image versions         hubble-ui          quay.io/cilium/hubble-ui:v0.12.3@sha256:e6b825302fc1e406b1305363fe0bcd1fdf95730b32c2b99a2b36dfa37bdaeec2: 1
                       hubble-ui          quay.io/cilium/hubble-ui-backend:v0.12.3@sha256:1cd84251cec46e20f9e839ee0afba9b51c8de59d35681234f701d7f42062f138: 1
                       hubble-relay       quay.io/cilium/hubble-relay:v1.15.0@sha256:45b3ea70b73aee01644f800b8f6138c36446bfb130d2b88b0f75775ebe6a9ab6: 1
                       cilium             quay.io/cilium/cilium:v1.15.0@sha256:9cfd6a0a3a964780e73a11159f93cc363e616f7d9783608f62af6cfdf3759619: 1
                       cilium-operator    quay.io/cilium/operator-generic:v1.15.0@sha256:e26ecd316e742e4c8aa1e302ba8b577c2d37d114583d6c4cdd2b638493546a79: 1
```

### Cilium Version

```console
$ kubectl -n kube-system exec -ti cilium-9mh6p --container cilium-agent -- cilium version
Client: 1.15.0 2db45c46 2024-01-31T18:58:02+01:00 go version go1.21.6 linux/amd64
Daemon: 1.15.0 2db45c46 2024-01-31T18:58:02+01:00 go version go1.21.6 linux/amd64
```

### Kernel Version

```console
$ uname -a
Linux node00 6.5.0-17-generic #17~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan 16 14:32:32 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
```

### Kubernetes Version

I tried 1.26.11 up to 1.29.1.

### Sysdump

<details>
  <summary>Log outout</summary>
  <code>
🔍 Collecting sysdump with cilium-cli version: v0.15.21, args: [sysdump]
🔮 Detected Cilium installation in namespace "kube-system"
🔮 Detected Cilium operator in namespace "kube-system"
ℹ️ Failed to detect Cilium SPIRE installation - using Cilium namespace as Cilium SPIRE namespace: kube-system
🔍 Collecting Kubernetes nodes
🔮 Detected Cilium features: map[cidr-match-nodes:Disabled cni-chaining:Disabled:none enable-envoy-config:Disabled enable-gateway-api:Disabled enable-ipv4-egress-gateway:Disabled endpoint-routes:Disabled ingress-controller:Disabled ipv4:Enabled ipv6:Disabled mutual-auth-spiffe:Disabled wireguard-encapsulate:Disabled]
🔍 Collecting tracing data from Cilium pods
🔍 Collect Kubernetes nodes
🔍 Collecting Kubernetes events
🔍 Collect Kubernetes version
🔍 Collecting Kubernetes pods
🔍 Collecting Kubernetes namespaces
🔍 Collecting Kubernetes services
🔍 Collecting Kubernetes endpoints
🔍 Collecting Kubernetes network policies
🔍 Collecting Kubernetes metrics
🔍 Collecting Cilium cluster-wide network policies
🔍 Collecting Cilium network policies
🔍 Collecting Kubernetes leases
🔍 Collecting Kubernetes pods summary
🔍 Collecting Cilium Egress Gateway policies
🔍 Collecting Cilium egress NAT policies
🔍 Collecting Cilium local redirect policies
🔍 Collecting Cilium CIDR Groups
🔍 Collecting Cilium endpoint slices
🔍 Collecting Cilium endpoints
🔍 Collecting Cilium nodes
🔍 Collecting Cilium identities
🔍 Collecting Ingresses
🔍 Collecting Cilium Node Configs
🔍 Collecting Cilium BGP Peering Policies
🔍 Collecting IngressClasses
🔍 Collecting Cilium LoadBalancer IP Pools
🔍 Collecting Cilium Pod IP Pools
🔍 Checking if cilium-etcd-secrets exists in kube-system namespace
🔍 Collecting the Cilium configuration
🔍 Collecting the Cilium daemonset(s)
🔍 Collecting the Cilium Node Init daemonset
🔍 Collecting the Cilium Envoy configuration
🔍 Collecting the Cilium Envoy daemonset
🔍 Collecting the Hubble daemonset
🔍 Collecting the Hubble Relay configuration
🔍 Collecting the Hubble Relay deployment
🔍 Collecting the Hubble UI deployment
🔍 Collecting the Cilium operator deployment
🔍 Collecting the Cilium operator metrics
🔍 Collecting the clustermesh metrics
🔍 Collecting the 'clustermesh-apiserver' deployment
🔍 Collecting the CNI configuration files from Cilium pods
🔍 Collecting the CNI configmap
🔍 Collecting gops stats from Cilium pods
⚠️ Daemonset "cilium-node-init" not found in namespace "kube-system" - this is expected if Node Init DaemonSet is not enabled
🔍 Collecting gops stats from Hubble pods
🔍 Collecting gops stats from Hubble Relay pods
⚠️ Daemonset "cilium-envoy" not found in namespace "kube-system" - this is expected if Envoy DaemonSet is not enabled
🔍 Collecting bugtool output from Cilium pods
⚠️ Deployment "clustermesh-apiserver" not found in namespace "kube-system" - this is expected if 'clustermesh-apiserver' isn't enabled
🔍 Collecting profiling data from Cilium pods
🔍 Collecting logs from Cilium pods
🔍 Collecting logs from Cilium Envoy pods
🔍 Collecting logs from Cilium Node Init pods
🔍 Collecting logs from Cilium operator pods
🔍 Collecting logs from 'clustermesh-apiserver' pods
🔍 Collecting logs from Hubble pods
Secret "cilium-etcd-secrets" not found in namespace "kube-system" - this is expected when using the CRD KVStore
🔍 Collecting logs from Hubble Relay pods
🔍 Collecting logs from Hubble UI pods
🔍 Collecting platform-specific data
🔍 Collecting kvstore data
🔍 Collecting Cilium external workloads
🔍 Collecting Hubble flows from Cilium pods
I0213 19:55:58.352516  208334 request.go:697] Waited for 1.190210543s due to client-side throttling, not priority and fairness, request: GET:https://62.171.177.25:6443/api/v1/namespaces/kube-system/pods?labelSelector=io.cilium%2Fapp%3Doperator
🔍 Collecting bugtool output from Tetragon pods
🔍 Collecting Tetragon PodInfo custom resources
🔍 Collecting Tetragon tracing policies
🔍 Collecting Helm values from the release
⚠️ The following tasks failed, the sysdump may be incomplete:
⚠️ [13] Collecting Cilium egress NAT policies: failed to collect Cilium egress NAT policies: the server could not find the requested resource
⚠️ [14] Collecting Cilium Egress Gateway policies: failed to collect Cilium Egress Gateway policies: the server could not find the requested resource (get ciliumegressgatewaypolicies.cilium.io)
⚠️ [16] Collecting Cilium local redirect policies: failed to collect Cilium local redirect policies: the server could not find the requested resource (get ciliumlocalredirectpolicies.cilium.io)
⚠️ [18] Collecting Cilium endpoint slices: failed to collect Cilium endpoint slices: the server could not find the requested resource (get ciliumendpointslices.cilium.io)
⚠️ [24] Collecting Cilium BGP Peering Policies: failed to collect Cilium BGP Peering policies: the server could not find the requested resource (get ciliumbgppeeringpolicies.cilium.io)
⚠️ [31] Collecting the Cilium Envoy configuration: failed to collect the Cilium Envoy configuration: configmaps "cilium-envoy-config" not found
⚠️ [61] Collecting Tetragon PodInfo custom resources: failed to collect Tetragon PodInfo: the server could not find the requested resource (get podinfo.cilium.io)
⚠️ [62] Collecting Tetragon tracing policies: failed to collect Tetragon tracing policies: the server could not find the requested resource (get tracingpolicies.cilium.io)
⚠️ [63] Collecting Helm values from the release: failed to get the helm values from the release: unable to retrieve helm value from release cilium: release: not found
⚠️ logs-hubble-relay-b8c686c95-pkpr5-hubble-relay: failed to collect previous logs for "hubble-relay-b8c686c95-pkpr5" ("hubble-relay") in namespace "kube-system": previous terminated container "hubble-relay" in pod "hubble-relay-b8c686c95-pkpr5" not found
⚠️ Please note that depending on your Cilium version and installation options, this may be expected
🗳 Compiling sysdump
✅ The sysdump has been saved to cilium-sysdump-20240213-195556.zip
  </code>
</details>

[cilium-sysdump-20240213-195556.zip](https://github.com/cilium/cilium/files/14271036/cilium-sysdump-20240213-195556.zip)

### Relevant log output

```shell
$ # without DNS proxy
$ kubectl -n kube-system exec -ti cilium-9mh6p --container cilium-agent -- cilium-dbg monitor | grep -F -- '10.10.0.67'
Policy verdict log: flow 0x6376f802 local EP ID 120, remote ID 11394, proto 17, egress, action allow, auth: disabled, match L3-L4, 10.10.0.67:46401 -> 10.10.0.198:53 udp
Policy verdict log: flow 0x6376f802 local EP ID 82, remote ID 2844, proto 17, ingress, action allow, auth: disabled, match L3-L4, 10.10.0.67:46401 -> 10.10.0.198:53 udp
-> endpoint 82 flow 0x6376f802 , identity 2844->11394 state new ifindex lxc1380f4aa9917 orig-ip 10.10.0.67: 10.10.0.67:46401 -> 10.10.0.198:53 udp
-> endpoint 120 flow 0x0 , identity 11394->2844 state reply ifindex lxcf3b10c2203a8 orig-ip 10.10.0.198: 10.10.0.198:53 -> 10.10.0.67:46401 udp

$ # with DNS proxy
$ kubectl -n kube-system exec -ti cilium-9mh6p --container cilium-agent -- cilium-dbg monitor | grep -F -- '10.10.0.67'
Policy verdict log: flow 0xa318316f local EP ID 120, remote ID 11394, proto 17, egress, action redirect, auth: disabled, match L3-L4, 10.10.0.67:59365 -> 10.10.0.198:53 udp
-> proxy port 35591 flow 0xa318316f , identity 2844->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.10.0.67:59365 -> 10.10.0.198:53 udp
Policy verdict log: flow 0xdac88a8a local EP ID 120, remote ID 11394, proto 17, egress, action redirect, auth: disabled, match L3-L4, 10.10.0.67:52522 -> 10.10.0.198:53 udp
-> proxy port 35591 flow 0xdac88a8a , identity 2844->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.10.0.67:52522 -> 10.10.0.198:53 udp
Policy verdict log: flow 0x8b249f1a local EP ID 120, remote ID 11394, proto 17, egress, action redirect, auth: disabled, match L3-L4, 10.10.0.67:41475 -> 10.10.0.198:53 udp
-> proxy port 35591 flow 0x8b249f1a , identity 2844->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.10.0.67:41475 -> 10.10.0.198:53 udp
```

### Anything else?

Hubble does not show anything suspicious. Nothing is marked as dropped in the "Verdict" column; I only see "unknown", which I thought was strange. Hence, I am reporting it here. I don't know what to make out of that.

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by foyerunix**
Hello,

Fixes: #30744

When queried for the routes of an unknow IP family the kernel return the routes for all IP families.
This end up returning the IPv4 routes when IPv6 is disabled at boot time. Therefore calling DeleteRouteTable with family = AF_INET6 will delete IPv4 routes too, breaking the DNS proxy.

I didn't include all the new code from the library yet as the contribution guide state that:

> If the PR is considerably large (e.g. with more than 200 lines changed and/or more than 6 commits), consider whether there is a good way to split the PR into smaller PRs that can be merged more incrementally.

Unfortunately I don't see how to split the whole library update into smaller chunks. I also can't guarantee that the updated library code, if included fully, won't cause any regression. Therefore I prefer to run the CI with my changes only first.

```release-note
Fix DNS proxy regression from Cilium 1.15 on IPv4 only nodes
```

Best Regards,

### CODE REVIEW

**Comment by sayboras** [comment]
I misclicked the update branch button, which adds one merge commit for main branch. I did a force push to your remote branch to rectify it, additionally, we can merge 2 commits into one.

**Comment by sayboras** [comment]
This change in vendor looks good to me, but no harm to have another check from others who involve in triaging the mentioned issue.

**Review by rgo3 — APPROVED** [review]

**Comment by julianwiedmann** [comment]
@sayboras  you're requested as codeowner :)

**Comment by julianwiedmann** [comment]
agent in CI is [crashing](https://github.com/cilium/cilium/actions/runs/8487402440/job/23338854224?pr=31671) with
> 2024-04-02T10:24:51.703614493Z level=fatal msg="failed to start: daemon creation failed: failed to detect devices: unable to determine direct routing device. Use --direct-routing-device to specify it" subsys=daemon

Let's see if a rebase helps.

**Comment by julianwiedmann** [comment]
> Let's see if a rebase helps.

nope, same error. @foyerunix looks like this will need a bit more digging :/

**Comment by sayboras** [comment]
> you're requested as codeowner :)

Oops. Seems like some work need to do here, I will be just in stand by mode 🧍‍♂️

**Comment by foyerunix** [comment]
Hello,

I had an hard time trying to reproduce this on my test cluster. It happened one time, then it didn't came back, meanwhile the cluster wasn't detecting the direct routing interface but used fallback routes.

Anyway I found an error in my contribution to the `netlink` library. Hopefully this is the cause of the issue and once it is merged the tests will pass:

https://github.com/vishvananda/netlink/pull/964

Thanks @rgo3 to suggest me to look at the behavior of `iproute2`.

Best Regards.

**Comment by foyerunix** [comment]
Hello @julianwiedmann,

My new PR was merged yesterday and I just updated the lib again. Please can we run CI ?

Best Regards.

**Comment by julianwiedmann** [comment]
:rocket:, looks much better already. Could you have a look at the linter complaint in https://github.com/cilium/cilium/actions/runs/8550570031/job/23428640769?pr=31671 ? It might be a result of your git `user.name` not being set up as expected.

**Comment by foyerunix** [comment]
Should be fixed @julianwiedmann

**Comment by foyerunix** [comment]
Hello,

Does I still need to do something or can I let you handle the rest of the process ?

Best Regards.

**Comment by sayboras** [comment]
> Does I still need to do something or can I let you handle the rest of the process ?

I think we just need to confirm if CI is happy.

**Review by sayboras — APPROVED** [review]
LGTM for vendor changes.

**Comment by julianwiedmann** [comment]
> Hello,
> 
> Does I still need to do something or can I let you handle the rest of the process ?
> 
> Best Regards.

fyi, CI is still unhappy about the change. Even after rebase to latest `main`.

**Comment by foyerunix** [comment]
Hello,

Please can we CI only this ? The whole library update bring many changes and I want to be sure that it is my own that is breaking the CI.

Best Regards.

**Comment by julianwiedmann** [comment]
> Please can we CI only this ? The whole library update bring many changes and I want to be sure that it is my own that is breaking the CI.
> 

now CI is green. So yep, looks like it's some previous netlink library change that's breaking us :/

**Comment by foyerunix** [comment]
Hello @julianwiedmann,

Considering that my small change fix the issue but a whole library update break the CI, what is your plan to go forward and restore IPv4 only compatibility ?

I understand that you would be unhappy to merge the PR as is as the library code wouldn't match any upstream version.

Unfortunately I can't commit to debug it myself. My understanding of the Cilium codebase is limited and the changes between the two library versions are numerous. Moreover my own environment will probably not match all the tests you are doing in the CI.

Are you planning to debug the issue on your side ?

Best Regards.

**Comment by georglauterbach** [comment]
@julianwiedmann what's the state on this? https://github.com/cilium/cilium/issues/30744 is a serious blocker - as of now, you cannot use the DNS proxy on an IPv4-only cluster. Running the proxy on an IPv4-only cluster is, I guess, rather common (for those that do not want nor need IPv6).

**Comment by foyerunix** [comment]
Hello,

I just built Cilium 1.15 branch with the netlink update and I don't see any issue on my test cluster. If someone have a reproducer that could help me debug the CI issue I can try to help find the regression in the library. As I understand we fail at a task upgrading then downgrading Cilium, but I'm not sure to understand what fail exactly from the CI logs.

Best Regards.

**Comment by rgo3** [comment]
I've been triggering CI [here](https://github.com/cilium/cilium/pull/32250) from time to time over the last two weeks but also can't really pinpoint a clear area that's breaking or deduce a simple reproducer. But its definitely multiple tests that keep failing, not just upgrade/downgrade tests. Potentially you could try to bisect the commits between current commit that cilium pulls from the netlink library and your latest fix. Happy to keep running CI with the revisions we need to test. Once we have a commit in the library that breaks cilium, it hopefully will be easier to locate why that change breaks so many tests.

**Comment by rgo3** [comment]
I think https://github.com/vishvananda/netlink/commit/916f9685fa42fc711f76a7f48d058e2656f7edf6 is the commit in the netlink lib that is causing the troubles for this PR. At least bisecting lead me to that commit. Can't really say what exactly the problematic part is that causes the issues in CI, but the code added to catch `EAGAIN` and retry seems problematic regardless for cilium as that creates a busy loop. Will update this PR if I make any further progress with debugging.

**Comment by julianwiedmann** [comment]
Note that if we want to unblock this sooner, one option is to switch over to our https://github.com/cilium/netlink fork again and revert the offending patch there.

**Comment by julianwiedmann** [comment]
> @julianwiedmann what's the state on this? #30744 is a serious blocker - as of now, you cannot use the DNS proxy on an IPv4-only cluster. Running the proxy on an IPv4-only cluster is, I guess, rather common (for those that do not want nor need IPv6).

If IPv4-only is a common environment that folks care about, then I think it would be great to reflect this via contributions towards https://github.com/cilium/cilium/issues/30327. Otherwise we'll most likely continue to break it once in a while :shrug:.

**Comment by georglauterbach** [comment]
> If IPv4-only is a common environment that folks care about, then I think it would be great to reflect this via contributions towards #30327. Otherwise we'll most likely continue to break it once in a while 🤷.

I understand, fair point. Sadly, I have neither the time nor the Go experience to do that :( Hopefully someone can tackle this :)

**Comment by foyerunix** [comment]
Hello,

Someone reverted the offending commit in the netlink library: https://github.com/vishvananda/netlink/pull/976

I just rebased the branch and updated the library to the latest version.

@julianwiedmann let's CI this please !

Best Regards.

**Review by sayboras — APPROVED** [review]
Thanks for your contribution and endless effort to drive this one through.

**Comment by sayboras** [comment]
Can you help to re-run `go mod tidy` and `go mod vendor` to sync up vendor dir?

```bash
$ git status            
On branch update-vishvananda-netlink
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    vendor/github.com/vishvananda/netlink/cmd/ipset-test/main.go
```

**Comment by foyerunix** [comment]
Hello,

I think the issue should be solved. Not being a Go developer myself, I didn't know the existence of `go mod vendor`, therefore I tried to do the process manually.

Best Regards.

**Pull request merged**
