### PR TITLE
Contrib: Fix systemd services for consul/etcd

### PR DESCRIPTION
**Pull request by eloycoto**
Fix issues reported on slack that consul didn't start correctly when
servers are rebooted

Reported-by: @iamShantanu101 
Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

### CODE REVIEW

**Review by tgraf — APPROVED** [review]
Awesome, great work.
cc @iamShantanu101

**Comment by tgraf** [comment]
test-me-please

**Comment by ishantanu** [comment]
Thanks, @tgraf.

**Comment by joestringer** [comment]
I'm still seeing consul fail to start on running `RELOAD=1 NFS=1 IPV4=1 ./contrib/vagrant/start.sh` after rebase here, do I need to do anything more?
```
Mar 21 22:41:38 runtime1 cilium-agent[6148]: level=info msg="     _ _ _"
Mar 21 22:41:38 runtime1 cilium-agent[6148]: level=info msg=" ___|_| |_|_ _ _____"
Mar 21 22:41:38 runtime1 cilium-agent[6148]: level=info msg="|  _| | | | | |     |"
Mar 21 22:41:38 runtime1 cilium-agent[6148]: level=info msg="|___|_|_|_|___|_|_|_|"
Mar 21 22:41:38 runtime1 cilium-agent[6148]: level=info msg="Cilium 1.0.0-rc8 39aa7cb8909e 2018-03-21T15:07:44-07:00 go version go1.9.3 linux/amd64"
Mar 21 22:41:38 runtime1 cilium-agent[6148]: level=info msg="cilium-envoy  version: 39aa7cb8909e52048512eb56bcf8954fda8bf3e8/1.6.0-dev/Clean/DEBUG"
Mar 21 22:41:38 runtime1 cilium-agent[6148]: level=info msg="clang (3.8.1) and kernel (4.13.0) versions: OK!"
Mar 21 22:41:38 runtime1 cilium-agent[6148]: level=info msg="linking environment: OK!"
Mar 21 22:41:38 runtime1 cilium-agent[6148]: level=info msg="bpf_requirements check: OK!"
Mar 21 22:41:38 runtime1 cilium-agent[6148]: level=info msg="bpf_features check: OK!"
Mar 21 22:41:38 runtime1 cilium-agent[6148]: level=info msg="Mounted BPF filesystem /sys/fs/bpf"
Mar 21 22:41:38 runtime1 cilium-agent[6148]: level=info msg="Waiting for consul to elect a leader"
Mar 21 22:41:38 runtime1 cilium-agent[6148]: level=debug msg="Sleeping with exponential backoff" attempt=1 name=04bd75f7-2d59-11e8-92bb-08002795cd5f time=200ms
Mar 21 22:41:39 runtime1 cilium-agent[6148]: level=debug msg="Sleeping with exponential backoff" attempt=2 name=04bd75f7-2d59-11e8-92bb-08002795cd5f time=400ms
Mar 21 22:41:39 runtime1 cilium-agent[6148]: level=debug msg="Sleeping with exponential backoff" attempt=3 name=04bd75f7-2d59-11e8-92bb-08002795cd5f time=800ms
Mar 21 22:41:40 runtime1 cilium-agent[6148]: level=debug msg="Sleeping with exponential backoff" attempt=4 name=04bd75f7-2d59-11e8-92bb-08002795cd5f time=1.6s
Mar 21 22:41:41 runtime1 cilium-agent[6148]: level=debug msg="Sleeping with exponential backoff" attempt=5 name=04bd75f7-2d59-11e8-92bb-08002795cd5f time=3.2s
Mar 21 22:41:45 runtime1 cilium-agent[6148]: level=debug msg="Sleeping with exponential backoff" attempt=6 name=04bd75f7-2d59-11e8-92bb-08002795cd5f time=6.4s
Mar 21 22:41:51 runtime1 cilium-agent[6148]: level=debug msg="Sleeping with exponential backoff" attempt=7 name=04bd75f7-2d59-11e8-92bb-08002795cd5f time=12.8s
Mar 21 22:42:04 runtime1 cilium-agent[6148]: level=debug msg="Sleeping with exponential backoff" attempt=8 name=04bd75f7-2d59-11e8-92bb-08002795cd5f time=25.6s
Mar 21 22:42:29 runtime1 cilium-agent[6148]: level=debug msg="Sleeping with exponential backoff" attempt=9 name=04bd75f7-2d59-11e8-92bb-08002795cd5f time=51.2s
Mar 21 22:43:21 runtime1 cilium-agent[6148]: level=debug msg="Sleeping with exponential backoff" attempt=10 name=04bd75f7-2d59-11e8-92bb-08002795cd5f time=1m42.4s
Mar 21 22:45:03 runtime1 cilium-agent[6148]: level=debug msg="Sleeping with exponential backoff" attempt=11 name=04bd75f7-2d59-11e8-92bb-08002795cd5f time=3m24.8s
```

Consul logs:
```
$ journalctl -u cilium-consul
-- Logs begin at Wed 2018-03-21 22:28:10 UTC, end at Wed 2018-03-21 22:46:43 UTC. --
Mar 21 22:37:24 runtime1 systemd[1]: Starting cilium-consul...
Mar 21 22:37:25 runtime1 docker[5765]: 0.8.3: Pulling from library/consul
Mar 21 22:37:25 runtime1 docker[5765]: Digest: sha256:008f9751b9e3282c2cd68462847c1eb77c5eae34fc17015ac62adeef3d127038
Mar 21 22:37:25 runtime1 docker[5765]: Status: Image is up to date for consul:0.8.3
Mar 21 22:37:25 runtime1 docker[5939]: Error response from daemon: Conflict. The container name "/cilium-consul" is already in use by container "22c7996d00cf2e67b8923ac2335fa6d834599b82eee5db423cb94c15c0caa584". You have to remove (or rename) that contain
Mar 21 22:37:25 runtime1 systemd[1]: cilium-consul.service: Control process exited, code=exited status=1
Mar 21 22:37:25 runtime1 systemd[1]: Failed to start cilium-consul.
Mar 21 22:37:25 runtime1 systemd[1]: cilium-consul.service: Unit entered failed state.
Mar 21 22:37:25 runtime1 systemd[1]: cilium-consul.service: Failed with result 'exit-code'.
Mar 21 22:41:38 runtime1 systemd[1]: Starting cilium-consul...
Mar 21 22:41:39 runtime1 docker[6141]: 0.8.3: Pulling from library/consul
Mar 21 22:41:39 runtime1 docker[6141]: Digest: sha256:008f9751b9e3282c2cd68462847c1eb77c5eae34fc17015ac62adeef3d127038
Mar 21 22:41:39 runtime1 docker[6141]: Status: Image is up to date for consul:0.8.3
Mar 21 22:41:39 runtime1 docker[6305]: Error response from daemon: Conflict. The container name "/cilium-consul" is already in use by container "22c7996d00cf2e67b8923ac2335fa6d834599b82eee5db423cb94c15c0caa584". You have to remove (or rename) that contain
Mar 21 22:41:39 runtime1 systemd[1]: cilium-consul.service: Control process exited, code=exited status=1
Mar 21 22:41:39 runtime1 systemd[1]: Failed to start cilium-consul.
Mar 21 22:41:39 runtime1 systemd[1]: cilium-consul.service: Unit entered failed state.
Mar 21 22:41:39 runtime1 systemd[1]: cilium-consul.service: Failed with result 'exit-code'.
Mar 21 22:45:51 runtime1 systemd[1]: Starting cilium-consul...
Mar 21 22:45:52 runtime1 docker[6461]: 0.8.3: Pulling from library/consul
Mar 21 22:45:52 runtime1 docker[6461]: Digest: sha256:008f9751b9e3282c2cd68462847c1eb77c5eae34fc17015ac62adeef3d127038
Mar 21 22:45:52 runtime1 docker[6461]: Status: Image is up to date for consul:0.8.3
Mar 21 22:45:52 runtime1 docker[6629]: Error response from daemon: Conflict. The container name "/cilium-consul" is already in use by container "22c7996d00cf2e67b8923ac2335fa6d834599b82eee5db423cb94c15c0caa584". You have to remove (or rename) that contain
Mar 21 22:45:52 runtime1 systemd[1]: cilium-consul.service: Control process exited, code=exited status=1
Mar 21 22:45:52 runtime1 systemd[1]: Failed to start cilium-consul.
Mar 21 22:45:52 runtime1 systemd[1]: cilium-consul.service: Unit entered failed state.
Mar 21 22:45:52 runtime1 systemd[1]: cilium-consul.service: Failed with result 'exit-code'.
```

**Comment by raybejjani** [comment]
This might need `docker rm --force $(docker ps -aq --filter name=cilium-consul)` in `ExecStartPre` to stop any still running containers and to clean up the container's image.

@joestringer I don't suppose you could try that out? If it works, we can make a PR.

**Comment by joestringer** [comment]
@raybejjani I can try this out.

**Comment by ishantanu** [comment]
Adding further to @raybejjani's comment, can we also do one more thing:
1. Use `docker container` instead of `docker` for container specific command like `run,start,rm`,etc.
    Ex.
    ```
    docker container create
    ```

**Pull request merged**
