### PR TITLE
CI: enable load balancer acceleration for some datapath conformance cases

### PR DESCRIPTION
**Pull request by lmb**
gh/workflows: enable loadBalancer acceleration for some suites
    
    Set loadBalancer.acceleration=testing-only in two datapath
    conformance tests. I had originally planned to modify 12-15 but
    those have encryption enabled. Instead, enable it on 6-7. Compared
    to Jenkins we drop  testing for (EP routes=true,
    acceleration=testing-only) from the matrix.
    
    Updates #24151
    
    Signed-off-by: Lorenz Bauer <lmb@isovalent.com>

gh/workflows: fix initialization of EGRESS_GATEWAY
    
    Use the same logic for EGRESS_GATEWAY as for other features.
    
    Signed-off-by: Lorenz Bauer <lmb@isovalent.com>

```release-note
Enable loadBalancer.acceleration=testing-only in some datapath conformance cases
```

### CODE REVIEW

**Comment by lmb** [comment]
Seems to work! https://github.com/cilium/cilium/actions/runs/4609865570/jobs/8147619976?pr=24738#step:8:35

**Comment by lmb** [comment]
cc @jibi @brb

**Review by gentoo-root — APPROVED** [review]

**Comment by lmb** [comment]
ConformanceK8sKind flaked: https://github.com/cilium/cilium/issues/24622

**Review by brlbil — APPROVED** [review]
I have re-run the flaky test, and it passed. 
LGTM from the workflow perspective.

**Review by jibi — APPROVED** [review]
Looks good! Can you maybe add some quick context to the second commit on how we ended up with 6-7? (iirc the initial idea was 4-7 and 12-15, which are the ones with egressgw enabled but  12-15 have encryption enabled?)

**Comment by lmb** [comment]
Updated the commit description. If I understand correctly the setup I'm proposing would drop coverage of EP routes on, acceleration testing-only compared to Jenkins.

**Pull request merged**
