### PR TITLE
cleanup: remove unused code

### PR DESCRIPTION
**Pull request by florianl**
Signed-off-by: Lehner Florian <dev@der-flo.net>

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

This PR just removes dead code that is not used.

### CODE REVIEW

**Review by christarazi — APPROVED** [review]
:rocket:

**Review by tklauser — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
Nice cleanup!

How did you detect these? Seems like there's some potential to put another tool into the regular CI checks.

**Comment by joestringer** [comment]
Compile + unit testing would pick up if there were any problemes with these changes, so CI is good :+1: 

Merging.

**Comment by florianl** [comment]
Thanks for the review and merge :+1: 

I did apply the [staticcheck](https://staticcheck.io/) with the default configuration.

**Pull request merged**
