### PR TITLE
Workaround for systemd 242 assigning MAC addr for virtual devices

### LINKED ISSUE #8304: No connectivity to endpoints with systemd 242
@gandro mentioned to me that `cilium-health` with a standalone `cilium-agent` from v1.5.3 does not work on his laptop running the latest archlinux. After I upgraded my archlinux machine to the latest which upgraded Linux kernel to v5.1.6, Docker to 18.09.6-ce, systemd to 242 (242.29-1-arch). I noticed that neither `cilium-health` nor any cilium endpoint can't be reached from the host.

I've tried to curl the nginx endpoint from the host netns, and `cilium monitor` showed that a TCP SYN packet is being redirected to the peer end of the veth device in the endpoint's netns after https://github.com/cilium/cilium/blob/v1.5.3/bpf/bpf_lxc.c#L999 has been called.

The kernel stack trace showed that the packet is being dropped in `ip_rcv_core`:
```
# bpftrace -e 'kprobe:kfree_skb { @[kstack] = count(); }'
Attaching 1 probe...
^C

@[
    kfree_skb+1
    ip_rcv_core.isra.2+1025
    ip_rcv+58
    __netif_receive_skb_one_core+82
    process_backlog+155
    net_rx_action+324
    __softirqentry_text_start+274
    do_softirq_own_stack+42
    do_softirq+93
    __local_bh_enable_ip+105
    ip_finish_output2+419
    ip_output+112
    __ip_queue_xmit+354
    __tcp_transmit_skb+1398
    tcp_connect+1651
    tcp_v4_connect+1119
    __inet_stream_connect+209
    inet_stream_connect+54
    __sys_connect+135
    __x64_sys_connect+22
    do_syscall_64+91
    entry_SYSCALL_64_after_hwframe+68
]: 1
```

`perf probe` revealed that the drop happened due to `skb->pkt_type == PACKET_OTHERHOST`: https://github.com/torvalds/linux/blob/v5.1/net/ipv4/ip_input.c#L428-L429.

The `skb->pkt_type = PACKET_OTHERHOST` is set by the kernel after the redirect in bpf_lxc.c is executed. In particular, `eth_trans_type` set it for us: https://github.com/torvalds/linux/blob/v5.1/net/ethernet/eth.c#L177. The relevant ktrace:

```
@[
    eth_type_trans+1
    __dev_forward_skb+184
    veth_xmit+110
    dev_hard_start_xmit+156
    __dev_queue_xmit+2185
    __bpf_redirect+428
    __dev_queue_xmit+1864
    ip_finish_output2+661
    ip_output+112
    __ip_queue_xmit+354
    __tcp_transmit_skb+1398
    tcp_connect+1651
    tcp_v4_connect+1119
    __inet_stream_connect+209
    inet_stream_connect+54
    __sys_connect+135
    __x64_sys_connect+22
    do_syscall_64+91
    entry_SYSCALL_64_after_hwframe+68
]: 1
```

The change of the packet type was due to different dmac addrs: `skb->dev->dev_addr` was set to the veth peer in the endpoint's netns (correct), while `((struct ethhdr *)skb->data)->h_dest` was set to some mac addr which didn't exist on the system in any netns.

Next steps:

- [x] Downgrade the kernel to check whether it's a kernel regression.
- [x] Check where the non-existing mac addr comes from.

### PR DESCRIPTION
**Pull request by brb**
This PR introduces a workaround for preventing the systemd 242+ from assigning MAC addrs for virtual devices after they have been created. The trick is to set a MAC addr when creating such device. This sets `addr_assign_type` to `NET_ADDR_SET` which makes the systemd to skip re-assigning of the MAC addr: https://github.com/systemd/systemd/blob/v242/src/udev/net/link-config.c#L292.

Note that we don't apply the same trick to ipvlan slave devices, as they inherit a MAC addr from their master, so they bypass the issue.

See https://github.com/cilium/cilium/issues/8304 for more details about the systemd feature and what it causes to Cilium.

Fix #8304.

```release-note
Work around systemd 242+ trying to re-assign MAC addresses for Cilium interfaces which breaks endpoint connectivity.
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8351)

### CODE REVIEW

**Comment by brb** [comment]
Added the needs backport labels as all Cilium versions are affected.

**Comment by brb** [comment]
test-me-please

**Review by nirmoy — APPROVED** [review]
LGTM

**Comment by nirmoy** [comment]
test-me-please

**Comment by jrfastab** [comment]
Bit surprised the veth pair isn't given a MAC already by whoever created it but OK. Patches LGTM.

**Review by joestringer — APPROVED** [review]
LGTM. Please also add a release note to the PR description to explain that this fixes compatibility with systemd 242.

(http://docs.cilium.io/en/latest/contributing/#submitting-a-pull-request step 9 if you need the formatting)

Also, do we need to do this for IPVLAN devices?

**Review by aanm — APPROVED** [review]

**Comment by brb** [comment]
CI failed due to:
```
[Pipeline] echo
[2019-06-19T15:03:45.899Z] Label 'area/k8s' is not part of the PR '[area/datapath, kind/bug, needs-backport/1.3, needs-backport/1.4, needs-backport/1.5, pending-review]'
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Precheck)
Stage "Precheck" skipped due to earlier failure(s)
[Pipeline] }
```

Retrying.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
> Also, do we need to do this for IPVLAN devices?

> Note that we don't apply the same trick to ipvlan slave devices, as they inherit a MAC addr from their master, so they bypass the issue.

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
@brb needs rebase.

**Comment by brb** [comment]
test-me-please

**Pull request merged**
