### PR TITLE
v1.16 Backports 2024-08-03

### PR DESCRIPTION
**Pull request by nbusseneau**
* [ ] #33934 (@giorio94) :warning: resolved conflicts
 * [ ] #33904 (@chaunceyjiang)
 * [ ] #33908 (@giorio94) :warning: resolved conflicts
 * [x] #33952 (@chancez)
 * [ ] #33517 (@jrajahalme)
 * [ ] #33847 (@tommyp1ckles)
 * [ ] #34004 (@tommyp1ckles)
 * [x] #33971 (@rastislavs)
 * [x] #33947 (@harsimran-pabla)
 * [ ] #33905 (@chaunceyjiang)
 * [x] #34032 (@sayboras)
 * [ ] #34017 (@ysksuzuki) :warning: resolved conflicts
 * [x] #34031 (@rastislavs)
 * [x] #34059 (@joamaki)
 * [ ] #34062 (@giorio94)
 * [x] #34044 (@Huweicai) :warning: resolved conflicts
 * [x] #34097 (@chancez)
 * [ ] #33518 (@jrajahalme)
 * [x] #34106 (@dylandreimerink)
 * [x] #34109 (@sayboras)
 * [x] #34121 (@michi-covalent)
 * [x] #34110 (@mhofstetter)
 * [ ] #34104 (@jrajahalme)

PRs removed due to issues:
 * #33989 (@bimmlerd)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33934 33904 33908 33952 33517 33847 34004 33971 33947 33905 34032 34017 34031 34059 34062 34044 34097 33518 34106 34109 34121 34110 34104
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.16

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commits ✅

**Review by michi-covalent — APPROVED** [review]
tyty~

**Review by mhofstetter — APPROVED** [review]
LGTM, thanks!

**Review by rastislavs — APPROVED** [review]

**Review by bimmlerd — APPROVED** [review]

**Review by viktor-kurchenko — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]

**Comment by bimmlerd** [comment]
@nbusseneau Unfortunately I've managed to introduce two bugs with #33989 - I'm fixing them in #34175 but let's drop #33989 for now until the fixes are merged and can be backported too. Apologies for the overhead.

**Comment by nbusseneau** [comment]
/test-backport-1.16

**Review by joamaki — APPROVED** [review]

**Review by chancez — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Review by harsimran-pabla — APPROVED** [review]

**Comment by gandro** [comment]
e2e upgrade tests are hitting https://github.com/cilium/cilium/issues/33979 - won't become green.

**Pull request merged**
