### PR TITLE
v1.1 backports 2018-08-02

### PR DESCRIPTION
**Pull request by joestringer**
* #4492 
  * Minor conflicts, please review @ianvernon
  * Relies upon #2972 in master, which looks potentially large to backport (k8s dependency?)
* #5074
* #5076

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5081)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
@joestringer can you post the diff showing the conflicts?

**Comment by joestringer** [comment]
@ianvernon 

```
$ ~/git/cilium/contrib/backporting/cherry-pick ab76b79b4c384cab48beb4954d3cd213f64b5ba3
Applying: daemon: refactor updating of CNP Node Status
Using index info to reconstruct a base tree...
M       daemon/k8s_watcher.go
M       pkg/k8s/apis/cilium.io/v2/types.go
Falling back to patching base and 3-way merge...
Auto-merging pkg/k8s/apis/cilium.io/v2/types.go
Auto-merging daemon/k8s_watcher.go
CONFLICT (content): Merge conflict in daemon/k8s_watcher.go
error: Failed to merge in the changes.
Patch failed at 0001 daemon: refactor updating of CNP Node Status
Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```
```
$ git diff
diff --cc daemon/k8s_watcher.go
index f8441803ba40,941f2d4b6ee5..000000000000
--- a/daemon/k8s_watcher.go
+++ b/daemon/k8s_watcher.go
@@@ -1356,41 -1477,39 +1375,48 @@@ func (d *Daemon) addCiliumNetworkPolicy
                                                Warn("Error parsing new CiliumNetworkPolicy rule")
                                }
  
-                               cnpns := cilium_v2.CiliumNetworkPolicyNodeStatus{
-                                       OK: true,
-                                       // If the deadline was reached then not all endpoints are enforcing
-                                       // the given policy.
-                                       Enforcing:   waitForEPsErr == nil,
-                                       Revision:    rev,
-                                       LastUpdated: cilium_v2.NewTimestamp(),
-                                       Annotations: cnp.Annotations,
-                               }
- 
-                               // Most important is the error while adding the CNP
-                               if err != nil {
-                                       cnpns = cilium_v2.CiliumNetworkPolicyNodeStatus{
-                                               Error:       err.Error(),
-                                               OK:          false,
-                                               LastUpdated: cilium_v2.NewTimestamp(),
-                                       }
-                               } else if err2 != nil {
-                                       cnpns = cilium_v2.CiliumNetworkPolicyNodeStatus{
-                                               Error:       err2.Error(),
-                                               OK:          false,
-                                               LastUpdated: cilium_v2.NewTimestamp(),
-                                       }
+                               var err3 error
+ 
+                               // Update the status of whether the rule is enforced on this node.
+                               // If we are unable to parse the CNP retrieved from the store,
+                               // or if endpoints did not reach the desired policy revision
+                               // after 30 seconds, then mark the rule as not being enforced.
+                               if policyImportErr != nil {
+                                       // OK is false here because the policy wasn't imported into
+                                       // cilium on this node; since it wasn't imported, it also
+                                       // isn't enforced.
+                                       err3 = updateCNPNodeStatus(serverRuleCpy, false, false, policyImportErr, rev, cnp.Annotations)
+                               } else if ruleCopyParseErr != nil {
+                                       // This handles the case where the initial instance of this
+                                       // rule was imported into the policy repository successfully
+                                       // (policyImportErr == nil), but, the rule has been updated
+                                       // in the store soon after, and is now invalid. As such,
+                                       // the rule is not OK because it cannot be imported due
+                                       // to parsing errors, and cannot be enforced because it is
+                                       // not OK.
+                                       err3 = updateCNPNodeStatus(serverRuleCpy, false, false, ruleCopyParseErr, rev, cnp.Annotations)
+                               } else {
+                                       // If the deadline by the above context, then not all
+                                       // endpoints are enforcing the given policy, and
+                                       // waitForEpsErr will be non-nil.
+                                       err3 = updateCNPNodeStatus(serverRuleCpy, waitForEPsErr == nil, true, waitForEPsErr, rev, cnp.Annotations)
                                }
  
++<<<<<<< HEAD
 +                              nodeName := node.GetName()
 +                              serverRuleCpy.SetPolicyStatus(nodeName, cnpns)
 +                              ns := k8sUtils.ExtractNamespace(&serverRuleCpy.ObjectMeta)
 +
 +                              _, err2 = ciliumNPClient.CiliumV2().CiliumNetworkPolicies(ns).Update(serverRuleCpy)
 +                              if err2 == nil {
++=======
+                               if err3 == nil {
++>>>>>>> daemon: refactor updating of CNP Node Status
                                        scopedLog.WithField("status", serverRuleCpy.Status).Debug("successfully updated with status")
                                } else {
-                                       return err2
+                                       return err3
                                }
+ 
                                return waitForEPsErr
                        },
                },
@@@ -1457,8 -1677,11 +1584,10 @@@ func (d *Daemon) updateCiliumNetworkPol
                logfields.K8sNamespace + ".old":            oldRuleCpy.ObjectMeta.Namespace,
                logfields.CiliumNetworkPolicyName:          newRuleCpy.ObjectMeta.Name,
                logfields.K8sNamespace:                     newRuleCpy.ObjectMeta.Namespace,
+               "annotations.old":                          oldRuleCpy.ObjectMeta.Annotations,
+               "annotations":                              newRuleCpy.ObjectMeta.Annotations,
        }).Debug("Modified CiliumNetworkPolicy")
  
 -      d.deleteCiliumNetworkPolicyV2(oldRuleCpy)
        d.addCiliumNetworkPolicyV2(ciliumV2Store, newRuleCpy)
  }
  
```

**Comment by joestringer** [comment]
Legitimate failure:

```
19:45:20 # github.com/cilium/cilium/daemon
19:45:20 daemon/k8s_watcher.go:1446: undefined: ciliumUpdateStatusVerConstr in ciliumUpdateStatusVerConstr.Check
19:45:20 daemon/k8s_watcher.go:1446: undefined: k8sServerVer
19:45:20 daemon/k8s_watcher.go:1447: ciliumNPClient.CiliumV2().CiliumNetworkPolicies(ns).UpdateStatus undefined (type "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/cilium.io/v2".CiliumNetworkPolicyInterface has no field or method UpdateStatus)
```

**Comment by joestringer** [comment]
Applied this diff to fix the backport, derived from reverting part of #2972:
```
diff --git a/daemon/k8s_watcher.go b/daemon/k8s_watcher.go
index c8715f14287c..5583fb40f57a 100644
--- a/daemon/k8s_watcher.go
+++ b/daemon/k8s_watcher.go
@@ -1442,12 +1442,7 @@ func updateCNPNodeStatus(cnp *cilium_v2.CiliumNetworkPolicy, enforcing, ok bool,
        cnp.SetPolicyStatus(nodeName, cnpns)
        ns := k8sUtils.ExtractNamespace(&cnp.ObjectMeta)

-       switch {
-       case ciliumUpdateStatusVerConstr.Check(k8sServerVer):
-               _, err2 = ciliumNPClient.CiliumV2().CiliumNetworkPolicies(ns).UpdateStatus(cnp)
-       default:
-               _, err2 = ciliumNPClient.CiliumV2().CiliumNetworkPolicies(ns).Update(cnp)
-       }
+       _, err2 = ciliumNPClient.CiliumV2().CiliumNetworkPolicies(ns).Update(cnp)
        return err2
 }

```

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
@joestringer thanks for taking care of all of the merge conflict resolving!

**Comment by ianvernon** [comment]
Build failed: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5436

Build failed because some pods went into `ImagePullBackOff` - appears to be infrastructure-related vs. a problem with Cilium or a bug within the CI:

```
default       spaceship-8595b78f8c-f7qc8         0/1       ImagePullBackOff   0          5m        10.10.1.54      k8s2
```

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Review by jrfastab — APPROVED** [review]
LGTM

**Pull request merged**
