### PR TITLE
Istio: Update to 1.2.4

### PR DESCRIPTION
**Pull request by jrajahalme**
Istio release 1.2.4 includes the sidecar proxy with Envoy security fixes released on 8/13/2019.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

```release-note
Istio integration is updated to Istio version 1.2.4
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8915)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
VMs couldn't boot: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2365/flowGraphTable/

**Comment by ianvernon** [comment]
Checkout failed again:  https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2368/

This was on `jenkins-node-0`.

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
And again: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2369/execution/node/7/ on `jenkins-node-0` - I took the node offline

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
K8s upstream tests failed during VM booting: https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/1461/execution/node/47/log/

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
K8s upstream tests keep failing in provisioning stage:

```
21:29:34      k8s1-1.15: failed to export image: failed to set parent sha256:153f310db166db8f2a52a73768490683b37d981df1094a0c3417dfc8b46c9909: unknown parent image ID sha256:153f310db166db8f2a52a73768490683b37d981df1094a0c3417dfc8b46c9909
21:29:34      k8s1-1.15: Makefile:181: recipe for target 'docker-image-no-clean' failed
```

Will test one more time.

**Comment by ianvernon** [comment]
test-upstream-k8s

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
