### PR TITLE
v1.13 Backports 2024-07-23

### PR DESCRIPTION
**Pull request by joamaki**
* [x] #33848 (@giorio94)
 * [x] #33845 (@giorio94)
 * [x] #33887 (@gandro)
 * [x] #33934 (@giorio94) :warning: resolved conflicts

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33848 33845 33887 33934
```

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
My commits look good, thanks!

**Review by viktor-kurchenko — APPROVED** [review]

**Review by squeed — APPROVED** [review]

**Comment by joamaki** [comment]
/test-1.26-net-next

**Comment by joamaki** [comment]
/test-1.26-net-next

**Comment by squeed** [comment]
Reviewed for an on-vacation gandro.

**Pull request merged**
