### PR TITLE
Update client-go to 1.26.5 and switch to fork

### PR DESCRIPTION
**Pull request by marseel**
Followup to https://github.com/cilium/cilium/pull/26250

### CODE REVIEW

**Comment by aanm** [comment]
/test-backport-1.13

**Comment by joestringer** [comment]
I can give this a rubber stamp from tophat perspective but there's clearly more background that presumably goes into why it's appropriate to make this change in Cilium v1.13. I can't assess that based on the PR description. I've pinged @aanm since he triggered the CI, so I guess maybe you have some background here?

**Review by aanm — APPROVED** [review]
LGTM but it would be nice to add more information as requested by Joe

**Comment by jibi** [comment]
turning into draft while it gets rebased

**Pull request closed without merging**
