### PR TITLE
Adding support for TrafficDistribution

### PR DESCRIPTION
**Pull request by robscott**
This PR adds support for Service Traffic Distribution, a Kubernetes feature that should go beta/available-by-default in v1.31. For more information, refer to the following resources:

* The [latest update for this KEP](https://github.com/kubernetes/enhancements/pull/4655)
* [Kubernetes documentation](https://kubernetes.io/docs/concepts/services-networking/service/#traffic-distribution)
* [Comparable Kube-Proxy implementation](https://github.com/kubernetes/kubernetes/blob/ff829fe036663acbeaf2c9ef51588f6abb289ad5/pkg/proxy/topology.go#L148)

TrafficDistribution represents the latest and hopefully final iteration in Kubernetes topology aware routing. The default logic is quite simple - route traffic within the same zone if there are any healthy endpoints in that zone. The kube-proxy implementation of that is still based on the EndpointSlice hints field, but does not strictly need to be,

This KEP also comes with a more fundamental change to the implementation logic. As part of a broader goal of separating concerns, we've removed the check from Kube-Proxy that verified that a topology annotation was set before honoring hints on EndpointSlices. Now we simply check that all endpoints for an EndpointSlice have hints, and honor them if so.

In this PR I've left some logic to determine if a Service is likely to have hints set, but that is now only used to determine if a Service should be reconciled again if the local node labels change.

```release-note
Cilium now supports Kubernetes Service TrafficDistribution. To access this feature, use `--enable-service-topology` when running Cilium.
```

### CODE REVIEW

**Comment by robscott** [comment]
cc @gauravkghildiyal

**Comment by tommyp1ckles** [comment]
Hi @robscott , could you provide more context in the Git commit message as described [here](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request).

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@robscott the changes LGTM but there are some files that need to be regenerated accordingly the CI.

**Review by borkmann — APPROVED** [review]
Could you also add a small doc update to the topology awareness section to document support for TrafficDistribution? https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#topology-aware-hints

**Comment by robscott** [comment]
>Hi @robscott , thanks for the PR, could you provide more context in the Git commit message as described [here](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request).

Updated, let me know if I missed anything @tommyp1ckles.

>@robscott the changes LGTM but there are some files that need to be regenerated accordingly the CI.

Ran `make generate-k8s-api`, hopefully that's all I was missing.

>Could you also add a small doc update to the topology awareness section to document support for TrafficDistribution? https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#topology-aware-hints

Added, thanks for the idea @borkmann!

**Review by qmonnet — APPROVED** [review]
Looks good to me, thank you

**Review by aanm — APPROVED** [review]

**Comment by joestringer** [comment]
@robscott unfortunately, the bot that responds to comments cannot accept multiple commands in the same message. Additionally, you will need to [become an organization member](https://github.com/cilium/community/blob/main/CONTRIBUTOR-LADDER.md#organization-member) in order to be able to run tests.

**Comment by joestringer** [comment]
Test `Scenario: An Ingress with a trailing slashes in a prefix path rule should ignore the trailing slash and send traffic to the matching backend service # features/path_rules.feature:188` failed on a couple of runs. Is there any chance this could be impacted by the content of this PR?

**Comment by robscott** [comment]
Thanks for the info @joestringer! I've filed https://github.com/cilium/community/pull/127 to become an organization member.


>Test Scenario: An Ingress with a trailing slashes in a prefix path rule should ignore the trailing slash and send traffic to the matching backend service # features/path_rules.feature:188 failed on a couple of runs in the ci-ingress workflow. Is there any chance this could be impacted by the content of this PR?

I can't think of anything in this PR that should affect the results of Ingress conformance tests. As far as I can tell, this is a common flake per https://github.com/cilium/cilium/issues/31857.

**Comment by joestringer** [comment]
I wonder if we should actually bump this to `release-note/major`, given that it's a feature in k8s that we're now supporting and it could allow users to better manage the load in their clusters?

**Comment by qmonnet** [comment]
Fine by me, I hesitated between the two options when setting the label.

**Pull request merged**
