### PR TITLE
v1.12: Update k8s versions in tests and vendored libraries

### PR DESCRIPTION
**Pull request by tklauser**
See commit messages.

### CODE REVIEW

**Review by gandro — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
/test-backport-1.12

**Comment by tklauser** [comment]
- k8s-1.21-kernel-4.9 failed with #21970: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/2247/
- k8s-1.22-kernel-4.9 failed with #22688: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.9/355/ (I wonder whether we should backport https://github.com/cilium/cilium/pull/20619 to `v1.12`, given the same functionality is already tested by cilium-cli since v0.12.0 with `v1.12` currently using cilium-cli v0.12.11)

All other required tests passed and reviews are in. Marking as ready to merge.

**Comment by pchaigno** [comment]
> I wonder whether we should backport https://github.com/cilium/cilium/pull/20619 to `v1.12`, given the same functionality is already tested by cilium-cli since v0.12.0 with `v1.12` currently using cilium-cli v0.12.11

Makes sense to me.

**Pull request merged**
