### PR TITLE
Add Cilium debugger images and default debugging configuration for kind, vscode

### PR DESCRIPTION
**Pull request by joestringer**
This target wraps the Cilium image with a dlv debugger wrapper,
allowing live debug of the container image after you deploy it.

Usage:
* Start a kind cluster with `make kind`
* Install Cilium
* `make kind-image-debug` & update the Cilium pods' image
* restart target Cilium pods
* attach the debugger to the target node on port 2345 and proceed
  * If you are using vscode then the .vscode/launch.json will automatically provide attach targets in your vscode debugger UI. Just pick your node target:
    image

Note that the Cilium pods will pause immediately on startup until you
have connected the debugger.

This PR exposes the debugger port on each kind node as well, which is enabled by loading an image using `make kind-image-debug`.

Port allocations:
- 23401: First control plane node
- 2340*: Subsequent kind-control-plane nodes (if defined)
- 23411: First kind-worker node
- 2341*: Subsequent kind-worker nodes (if defined)

### CODE REVIEW

**Comment by joestringer** [comment]
I realized I'll need to open this fresh from the cilium/cilium repo in order to bump the base image dependencies.

**Comment by aditighag** [comment]
Welcome to the world of IDEs! 🚀 ;)

**Comment by joestringer** [comment]
I feel like I'm in the future haha. @aditighag is this similar to how you use dlv? Do you have any thoughts on how this is prepared vs. your workflow?

**Comment by aditighag** [comment]
> I feel like I'm in the future haha. @aditighag is this similar to how you use dlv? Do you have any thoughts on how this is prepared vs. your workflow?

I compile cilium using the debug make target. I then install and start delve inside cilium pods (or the dev VM), and then forward the `2345` port on my laptop. I've created a debug profile in GoLand, so it's just a keyboard stroke to connect to the remote delve process. But I noticed that VS code has a dropdown menu to select a kind node to connect to (seems like an added bonus!). There might be something similar on GoLand, but I haven't explored it.

**Comment by joestringer** [comment]
I'll fix up the PR description but I think it's effectively the same trick as you're using, here I just configured the kind nodes to port forward the debugger to the host on some specific ports like 23401. The vscode settings just define those ports to connect to and map them to some friendly names. The other thing is that the debugger is automatically wrapping the binary inside the new image, so no need to manually install / set up the debugger inside the pod.

**Comment by joestringer** [comment]
Superseded by https://github.com/cilium/cilium/pull/21108.

**Pull request closed without merging**
