### PR TITLE
Pr/v1.12 backports

### PR DESCRIPTION
**Pull request by ldelossa**
* #20619 -- test/k8s: remove l7_demos test (@tklauser)
 * #21267 -- Adding/fixing DNSProxy metrics (@rahulkjoshi)
 * #22620 -- Update Cilium install guide about EKS aws-node DaemonSet potential connectivity problem on uninstall (@NikAleksandrov)
 * #22821 -- Add sphinxcontrib-googleanalytics to doc requirements (@chalin)
 * #22794 -- bpf: nodeport: wire up trace aggregation for rev_nodeport_lb6() (@julianwiedmann)
  -> please double-check if this makes sense, rev_nodeport_lb6 changed quite a bit
 * #22807 -- Update Layer 7 Protocol Visibility Document. (@obaranov1)
 * #22745 -- Improve fqdn events logging management (@pippolo84)
 * #22678 -- bpf: nodeport: fix tracing for handle_nat_fwd() (@julianwiedmann)
 * #22930 -- Fix missing node neigh metric for counting arping requests (@christarazi)
 * #22985 -- datapath: Fix L7 ingress with XDP (@brb)
 * #22884 -- Fix crash of CES queue delay metric when CESTracker is nil (@dlapcevic)
 * #22977 -- iptables: skip reverse IP lookup (@jibi)
 * #22972 -- bpf: Fix LB loopback path with ingress policy (@aditighag)
 * #23018 -- bpf: test: fix xdp_lb4_forward_to_other_node test (@julianwiedmann)
 * #23037 -- ctmap: fix-up host_local flag in the DSR NAT entry for GC test (@julianwiedmann)
 * #22962 -- clustermesh: Add missing brackets of etcd option (@YutaroHayakawa)
 * #21857 -- test: net_policies: delete custom IP routes after test completion (@julianwiedmann)
 * #23220 -- .github: Pin docker buildx version to v0.9.1 (v2) (@joestringer)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20619 21267 22620 22821 22794 22807 22745 22678 22930 22985 22884 22977 22972 23018 23037 22962 21857 23220; do contrib/backporting/set-labels.py $pr done 1.12; done
```

---
PRs dropped from this round:
 * #22928 -- CODEOWNERS: Cover test/bpf_tests by sig-datapath (@christarazi)
  -> dropped, maintenance branches have different CODEOWNERS
 * #21768 -- Endpoint/CEP Ownership Fix (@tommyp1ckles)
  -> relies on missing node.GetCiliumEndpointNodeIP()
 * #22810 -- nodeport: fix CT accounting in revDNAT path (@julianwiedmann)
  -> generated quite a large diff I wasn't sure what to do with
 * #22768 -- Make cilium pprof listen address configurable (@chancez)
  -> can probably be made to fit with some work from the author; do we really want/need to backport this?
 * #22220 -- Enable Google Analytics 4 (@chalin)
 * #21980 -- datapath: Fix L7 reply to outside when endpoint routes disabled (@brb)

Manual fix added to skip `check-missing-tags-in-tests.sh` in v1.12 branch due to 7435adb50f.
Manual modified cherry-pick of https://github.com/cilium/cilium/pull/22980 to avoid eBPF unit test failures
Manual fix added to to avoid eBPF unit test failures: https://github.com/cilium/cilium/pull/23092#issuecomment-1396191886

### CODE REVIEW

**Comment by ldelossa** [comment]
re-opened per: https://github.com/cilium/cilium/pull/23190#issuecomment-1399640818

**Review by chancez — APPROVED** [review]
My changed are dropped, and in a separate PR so LGTM.

**Review by nbusseneau — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Comment by ldelossa** [comment]
`Cilium L4LB XDP` tests have a legit failure:

```
 +[21:46:03] docker exec -t lb-node docker exec -t cilium-lb cilium service update --id 1 --frontend 10.0.0.2:80 --backends 172.18.0.3:80 --backend-weights 0 --k8s-node-port
Error: unknown flag: --backend-weights

Usage:

  cilium service update [flags]



Flags:

      --backends strings            Backend address or addresses (<IP:Port>)

      --frontend string             Frontend address

  -h, --help                        help for update

      --id uint                     Identifier

      --k8s-cluster-internal        Set service as cluster-internal for externalTrafficPolicy=Local

      --k8s-external                Set service as a k8s ExternalIPs

      --k8s-host-port               Set service as a k8s HostPort

      --k8s-load-balancer           Set service as a k8s LoadBalancer

      --k8s-node-port               Set service as a k8s NodePort

      --k8s-traffic-policy string   Set service with k8s externalTrafficPolicy as {Local,Cluster} (default "Cluster")

      --local-redirect              Set service as Local Redirect

      --states strings              Backend state(s) as {active(default),terminating,quarantined,maintenance}



Global Flags:

      --config string   config file (default is $HOME/.cilium.yaml)

  -D, --debug           Enable debug messages

  -H, --host string     URI to server-side API



unknown flag: --backend-weights
```

**Comment by ldelossa** [comment]
/test-backport-1.12

**Comment by michi-covalent** [comment]
> Cilium L4LB XDP tests have a legit failure:

i guess we need to backport https://github.com/cilium/cilium/pull/18306 ?

**Comment by michi-covalent** [comment]
> i guess we need to backport https://github.com/cilium/cilium/pull/18306 ?

oh wait the failure is from `ci-l4lb` and `ci-l4lb-1.13`. not sure why these workflows are getting triggered, but `ci-l4lb-1.12` is passing so i think we are ok here ✅

**Comment by ldelossa** [comment]
Okay yeah, a whole slew of v1.13 tests tried to run, and have failed, so we'll ignore those.

**Review by jibi — COMMENTED** [review]
edit: ignore me, wrong PR

**Review by christarazi — APPROVED** [review]

**Review by jibi — APPROVED** [review]

**Comment by michi-covalent** [comment]
`test-1.17-4.9` failed because of this error message:
```
pod-kube-system-cilium-5sh9s-cilium-agent.log:2023-01-23T19:29:44.656595403Z level=error msg="Could not delete stale CEP" ciliumEndpointName=echo-a-6954f488f5-m92mr error="ciliumendpoints.cilium.io \"echo-a-6954f488f5-m92mr\" not found" k8sNamespace=default subsys=daemon
```

**Comment by michi-covalent** [comment]
/test-1.17-4.9

**Comment by ldelossa** [comment]
All tests have passed. This PR has a commit ontop to allow us to use the GHA workflow during this pr. I'm going to remove this commit now, and then immediately merge this PR, since we know tests are OK.

**Comment by joestringer** [comment]
@ldelossa awesome thanks! Please be sure to follow up on running the command under `Once this PR is merged, you can update the PR labels via:`, we haven't automated that step for backports yet.

**Comment by joestringer** [comment]
One more hint: For each PR that was *not* backported, I would suggest adding the `backport/author` label and dropping a note for them that the PR will not be backported by tophat, so they will need to propose the backport to ensure it lands in an older release.

**Pull request merged**
