### PR TITLE
v1.10 backports 2021-05-07

### PR DESCRIPTION
**Pull request by brb**
v1.10 backports 2021-05-07

 * #15906 -- test: Run WG with per-endpoint routes (@brb)
 * #15765 -- test: 5.4 CI job (@pchaigno)
 * #15938 -- ui envoy: fix config to keep grpc conn (@geakstr)
 * #15934 -- Drop a `@` in clustermesh-apiserver helm chart (@anthr76)
 * #15943 -- doc: New performance benchmarks and tuning guide (@tgraf)
 * #15955 -- doc: Reword some results (@tgraf)
 * #15928 -- test: Extend the clusterIP tests with policy (@aditighag)
 * #15964 -- bwm: queue mapping & cong fixes (@borkmann)
 * #15965 -- doc/encryption: improve consistency between ipsec and wireguard guides (@rolinh)
 * #15959 -- test: Fix fragment tracking test on GKE (@pchaigno)
 * #15961 -- Fix encryption getting started guides for v1.10 (@jibi)
 * #15963 -- docs: gsg/operations - use parsed-literal for all blocks referring SCM_WEB (@ti-mo)
 * #15971 -- docs: remove misplaced sentence from Quick Installation guide (@lfundaro)
 * #15973 -- docs: tell how to deploy demo app in Hubble CLI guide (@lfundaro)
 * #15832 -- ebpf: delete existing pinned map if incompatible with the spec (@jibi)
 * #15911 -- eni: Fix Cilium overallocating network interfaces (@gandro)
 * #15968 -- test: Fix the search for VIPs in `cilium service list` (@pchaigno)
 * #15981 -- doc: update Hubble/Hubble Relay guides for recent CLI changes (@rolinh)
 * #15982 -- docs: clustermesh: fix output of "cilium clustermesh status" command (@jibi)
 * #15988 -- connectivity-check: Reduce chances of port conflict with proxy (@pchaigno)
 * #15985 -- Update weekly community meeting timeslot (@joestringer)
 * #15983 -- images: Bump Hubble CLI to v0.8.0 (@gandro)
 * #15915 -- plugins/cilium-cni: fix aws-cni cni chaining (@aanm)
 * #15990 -- test/runtime: Wait for endpoints to be ready before querying by labels (@pchaigno)
 * #15984 -- docs: Fix egress gateway getting started guide (@gandro)
 * #15783 -- node-neigh: Locking, logging, misc improvements (@brb)
 * #16024 -- docs: minor improvements to tuning guide (@borkmann)
 * #15867 -- cilium: Encryption EKS 4.14 kernel (default) fixes (@jrfastab)
 * #16023 -- docs: Some Wireguard improvements (@brb)
 * #15950 -- Dockerfile: use alpine 3.12 (@aanm)
 * #16001 -- wireguard: Fix timeout in unit test (@gandro)
 * #16000 -- Minor fixes for OKD GSG (@errordeveloper)
 * #15994 -- ci-gke: Add -v=6 for `kubectl get pods` (@michi-covalent)
 * #16011 -- ci/wireguard: Ensure allowedIPs are set as expected (@gandro)
 * #15882 -- node-neigh: Avoid flooding the same next hop (@brb)
 * #14940 -- Encryption docs update (@aditighag)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 15906 15765 15938 15934 15943 15955 15928 15964 15965 15959 15961 15963 15971 15973 15832 15911 15968 15981 15982 15988 15985 15983 15915 15990 15984 15783 16024 15867 16023 15950 16001 16000 15994 16011 15882 14940; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
My changes look good :+1:

**Comment by pchaigno** [comment]
test-1.19-5.4

**Comment by pchaigno** [comment]
test-backport-1.10

**Review by aanm — APPROVED** [review]
Looks good for my commits

**Comment by brb** [comment]
test-4.9

**Comment by brb** [comment]
CI runtime hit #16040, CI 1.18-4.9 #15455.

**Comment by brb** [comment]
test-4.9

**Comment by errordeveloper** [comment]
Just double-checked my changes and all looks good :)

**Pull request merged**
