### PR TITLE
v1.12 Backports 2023-07-11

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
* [ ] #26590 (@YutaroHayakawa)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 26590; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=26590
```

### CODE REVIEW

**Comment by YutaroHayakawa** [comment]
/test-backport-v1.12

**Comment by YutaroHayakawa** [comment]
/test-backport-1.12

**Review by ldelossa — APPROVED** [review]
LGTM.

**Review by rastislavs — APPROVED** [review]
LGTM

**Comment by YutaroHayakawa** [comment]
k8s-1.19-kernel-4.9: https://github.com/cilium/cilium/issues/21969

**Comment by YutaroHayakawa** [comment]
/test-1.19-4.9

**Review by julianwiedmann — APPROVED** [review]

**Pull request merged**
