### PR TITLE
Always remove `AWS-SNAT-CHAIN` rules when running in ENI mode.

### PR DESCRIPTION
**Pull request by bmcustodio**
Please see each individual commit for details.

```release-note
Fixes an issue which can cause traffic to be dropped when running Cilium in ENI mode due to the presence of iptables rules left over by the AWS VPC CNI plugin. Notable features that could be impacted include the egress gateway functionality.
```

### CODE REVIEW

**Comment by bmcustodio** [comment]
@brb @jibi ☝️

**Review by brb — APPROVED** [review]

**Review by jibi — APPROVED** [review]
Thanks! :rocket:

**Review by kaworu — APPROVED** [review]

**Review by pchaigno — CHANGES_REQUESTED** [review]
The code looks good to me!

Given this is fixing a bug with egress gateway on EKS, shouldn't it be `release-note/bug` with a release note clarifying the bug impact for users and backport to v1.10?

**Review by pchaigno — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by jibi** [comment]
GKE failure is unrelated, marking as ready

**Pull request merged**
