### PR TITLE
chore: fix some function names

### PR DESCRIPTION
**Pull request by jinjiadu**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

fix some function names

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Review by learnitall — APPROVED** [review]
LGTM, thanks!

**Review by doniacld — APPROVED** [review]
LGTM! Thank you

**Review by youngnick — APPROVED** [review]

**Comment by aanm** [comment]
@jinjiadu thank you. Unfortunately the CI is failing [here](https://github.com/cilium/cilium/actions/runs/10642934497/job/29929785871?pr=34626). Can you take a look?

**Comment by dylandreimerink** [comment]
@jinjiadu It seems you need to rerun some of our generation tooling to fix the CI issue: `make generate-api generate-health-api generate-hubble-api generate-operator-api generate-kvstoremesh-api`

**Comment by jinjiadu** [comment]
> @jinjiadu It seems you need to rerun some of our generation tooling to fix the CI issue: `make generate-api generate-health-api generate-hubble-api generate-operator-api generate-kvstoremesh-api`

Thanks!  The cmd has been Executed.

**Pull request merged**
