### PR TITLE
v1.7 backports 2020-04-28

### PR DESCRIPTION
**Pull request by jrajahalme**
* #11056 -- daemon: Fix the "close of closed channel" panic (@Sen666666)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 11056; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by joestringer** [comment]
FYI I filed https://github.com/cilium/cilium/issues/11204 for the GKE failure. Framework issue.

**Comment by joestringer** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
test-upstream-k8s

**Comment by joestringer** [comment]
`Cilium-Ginkgo-Tests` flaked on one run with #11209 which overlapped with github outage, so seems safe to ignore. It didn't fail on the other k8s run.

`K8s-1.17-Kernel-4.19` failure is known (#11126) so can be safely ignored.

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Out of the 5 checks that are marked failing in the PR:

1. GKE is broken due to #11204 
1. `Cilium-Ginkgo-Test-k8s` failed because we need a backport for #11072 which is part of the other backport PR #11109 
1. Cilium-Ginkgo-Tests failed due to aforementioned #11204 likely github outage
1. Cilium-PR-Ginkgo-Tests-K8s is a duplicate link for (2)
1. K8s-1.17-Kernel-4.19 failed due to known flake #11126 

So from that perspective I think we're actually good to merge this trivial change despite the very red status :/

**Review by aanm — APPROVED** [review]

**Pull request merged**
