### PR TITLE
v1.13 Backports 2023-01-31

### PR DESCRIPTION
**Pull request by qmonnet**
* [x] #23123 (@squeed)
   * Minor conflict
 * [x] #23274 (@jibi)
 * [x] #23254 (@pchaigno)
   * Minor conflict
 * [x] #23235 (@julianwiedmann)
 * [x] #23193 (@julianwiedmann)
 * [x] #23336 (@dylandreimerink)
 * [x] #23286 (@jibi)
 * [x] #23241 (@pchaigno)
 * [ ] #23159 (@jaygridley)
 * [ ] #22995 (@kaworu)
 * [ ] #23339 (@borkmann)
 * [X] #23338 (@aanm)
 * [X] #23334 (@aanm)
 * [x] #23377 (@gandro)
 * [x] #23333 (@tklauser)
 * [X] #23406 (@aanm)
   * Minor conflict
 * [ ] #22629 (@nikhiljha)
 * [X] #23424 (@aanm)
 * [x] #23184 (@pjbgf)
   * Minor conflict
 * [X] #23431 (@aanm)
   * Minor conflict
 * [X] #23437 (@aanm)
   * Minor conflict
 * [ ] #22830 (@brb)
   * Minor conflict
 * [x] #23298 (@giorio94)
 * [x] #23463 (@michi-covalent)
   * Minor conflict
 * [x] #23470 (@michi-covalent)
 * [ ] #23120 (@brb)
   * Minor conflict
 * [X] #23482 (@aanm)

PRs skipped due conflicts:

 * #23202 (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 23123 23274 23254 23235 23193 23336 23286 23241 23159 22995 23339 23338 23334 23377 23333 23406 22629 23424 23184 23431 23437 22830 23298 23463 23470 23120 23482; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
$ make add-label BRANCH=v1.13 ISSUES=23123,23274,23254,23235,23193,23336,23286,23241,23159,22995,23339,23338,23334,23377,23333,23406,22629,23424,23184,23431,23437,22830,23298,23463,23470,23120,23482
```

### CODE REVIEW

**Review by squeed — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by qmonnet** [comment]
/test-backport-1.13

**Review by michi-covalent — APPROVED** [review]
ack!

✅ #23463 -- Pick up etcd v3.5.7 (@michi-covalent)
✅ #23470 -- hubble: Fix the condition to apply for syn-only flag (@michi-covalent)

**Review by pchaigno — APPROVED** [review]
My 2 PRs look good. Thanks!

**Review by julianwiedmann — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
My PR looks good. Thanks!

**Review by pjbgf — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
> [ ] [clustermesh, kvstore: consistently pass controller context to kvstore operations #23333](https://github.com/cilium/cilium/pull/23333) -- clustermesh, kvstore: consistently pass controller context to kvstore operations (@tklauser)

Thanks, looks good for my change.

**Review by gandro — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]

**Review by jibi — APPROVED** [review]

**Pull request merged**
