### PR TITLE
Cilium Envoy Config CRD

### PR DESCRIPTION
**Pull request by jrajahalme**
This is superseded by #18894, which is the same as this, but without the ingress controller code.

### CODE REVIEW

**Comment by jrajahalme** [comment]
Upgrade/downgrade tests will keep on failing until 1.11 is released with recently merged backport (https://github.com/cilium/cilium/pull/18800)

**Comment by michi-covalent** [comment]
superseded by https://github.com/cilium/cilium/pull/18894. closing.

**Pull request closed without merging**
