### PR TITLE
GKE CI: Fix K8sDatapathConfig* tests

### LINKED ISSUE #10026: CI: Fixup encapsulation tests on GKE
cilium runs on GKE, but these tests don't pass. It likely as simple as correctly parsing the output in the failing check, as it differs on GKE.

```
[Fail] K8sDatapathConfig Encapsulation [It] Check connectivity with VXLAN encapsulation
/Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:215



• Failure [158.822 seconds]
K8sDatapathConfig
/Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
  Encapsulation
  /Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
    Check connectivity with VXLAN encapsulation [It]
    /Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430

    Did not find expected number of entries in BPF tunnel map
    Expected
        <int>: 2
    to equal
        <int>: 3

    /Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:215
```

```
[Fail] K8sDatapathConfig Encapsulation [It] Check connectivity with sockops and VXLAN encapsulation
/Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:215

[Fail] K8sDatapathConfig Encapsulation [It] Check connectivity with Geneve encapsulation
/Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/k8sT/assertionHelpers.go:136
```

### LINKED ISSUE #10030: CI: Triage/Fixup DirectRouting tests on GKE
I'm not actually sure that these can pass on GKE, but some other direct routing tests did pass. They both fail at a similar stage in the test, and probably have the same problem. It may be as simple as the testds deploy not coming up clean (perhaps it has some taints).

```
[Fail] K8sDatapathConfig DirectRouting [It] Check connectivity with automatic direct nodes routes
/Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:279

• Failure [154.233 seconds]
K8sDatapathConfig
/Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
  DirectRouting
  /Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
    Check connectivity with automatic direct nodes routes [It]
    /Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430

    Connectivity test between nodes failed
    Expected
        <bool>: false
    to be true

    /Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:279
```
```
[Fail] K8sDatapathConfig DirectRouting [It] Check direct connectivity with per endpoint routes
/Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:288

• Failure [158.002 seconds]
K8sDatapathConfig
/Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
  DirectRouting
  /Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
    Check direct connectivity with per endpoint routes [It]
    /Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430

    Connectivity test between nodes failed
    Expected
        <bool>: false
    to be true

    /Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:288
```

### PR DESCRIPTION
**Pull request by tgraf**
* IPv6 is not enabled on GKE for now so some test expectations need to be adjusted
* autoDirectNodeRoutes is not compatible so tests must be disabled

Fixes: #10030
Fixes: #10026

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10259)

### CODE REVIEW

**Comment by tgraf** [comment]
test-gke K8sDatapathConfig*

**Comment by tgraf** [comment]
test-gke K8sDatapathConfig*

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-gke K8sDatapathConfig*

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-gke K8sDatapathConfig*

**Comment by nebril** [comment]
test-gke K8sDatapathConfig*

**Comment by tgraf** [comment]
test-gke K8sDatapathConfig*

**Comment by tgraf** [comment]
test-gke K8sDatapathConfig*

**Review by aanm — APPROVED** [review]

**Pull request merged**
