### PR TITLE
ci: use host kubectl in k8s-all

### PR DESCRIPTION
**Pull request by nebril**

### CODE REVIEW

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-missed-k8s

**Review by aanm — CHANGES_REQUESTED** [review]
Please add an answer to "Why?" in the commit message.

**Comment by nebril** [comment]
We got hit by a known k8s-all flake, otherwise looks really good! Let's merge.

**Comment by nebril** [comment]
Added missing commit message

**Comment by nebril** [comment]
test-missed-k8s

**Comment by aanm** [comment]
previous failure https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3782/

**Comment by aanm** [comment]
test-missed-k8s

**Comment by nebril** [comment]
same test failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3783/

I think it's out of scope of this PR, will merge this one and we can continue fixing `K8sVerifier Runs the kernel verifier against Cilium's BPF datapath` in another one

**Pull request merged**
