### PR TITLE
Document existing FQDN metrics

### PR DESCRIPTION
**Pull request by christarazi**
- docs: Fix typo in FQDN metric name
- docs: Add enabled by default column to FQDN metrics
- docs: Document existing FQDN metrics

Related: https://github.com/cilium/cilium/issues/20235

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]
Looks good, but I note that FQDN metrics will be the only ones to have a column for the default value. Do you plan to follow-up and add the column for the other metrics too? (If not, maybe open a `good-first-issue` for it?)

**Review by aditighag — CHANGES_REQUESTED** [review]
Per the community discussion yesterday, can you document this in the relevant feature/troubleshooting guides? For example, here - https://docs.cilium.io/en/stable/policy/language/#dns-based? Let's add a new troubleshooting section if needed.

**Comment by christarazi** [comment]
@qmonnet See https://github.com/cilium/cilium/issues/20235.

@aditighag I agree with also having a mention of useful metrics per feature. Could we have both an updated metrics reference and a troubleshooting section with metrics mentioned as well? I think https://github.com/cilium/cilium/pull/20255 is useful too and I don't think we should block improving the metrics reference on a troubleshooting guide. WDYT?

**Comment by aditighag** [comment]
> 
> @aditighag I agree with also having a mention of useful metrics per feature. Could we have both an updated metrics reference (this PR + #20255) and a troubleshooting section with metrics mentioned as well? I think #20255 is useful too and I don't think we should block improving the metrics reference on a troubleshooting guide. WDYT?

Might be good to create a tracking issue.

**Review by aditighag — APPROVED** [review]

**Comment by tklauser** [comment]
The changes in #20255 (which is marked for v1.12 backport) depend on this PR. Thus I've also marked it to be backported.

**Pull request merged**
