### PR TITLE
v1.13 Backports 2023-03-14

### PR DESCRIPTION
**Pull request by nebril**
* [ ] #24132 (@ysksuzuki)
 * [ ] #24336 (@ti-mo)
 * [ ] #24343 (@alan-kut)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 24132 24336 24343; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=24132,24336,24343
```

### CODE REVIEW

**Comment by nebril** [comment]
/test-backport-1.13

**Review by michi-covalent — APPROVED** [review]

**Comment by jrajahalme** [comment]
/test-1.26-net-next

**Review by ti-mo — APPROVED** [review]
Thanks, @nebril!

**Comment by nebril** [comment]
`k8s-1.26-kernel-net-next ` failed due to vm provisioning issue :thinking:

**Comment by nebril** [comment]
/test-1.26-net-next

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
