### PR TITLE
v1.8 backports 2021-02-02

### PR DESCRIPTION
**Pull request by christarazi**
* #14269 -- routing: Fix route collisions in AWS ENI (@christarazi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14269; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by christarazi** [comment]
test-backport-1.8

**Review by joestringer — APPROVED** [review]
I didn't look closely at the PR, I assume that any potential conflicts that may have come up would have been straightforward for you as the original author to resolve.

**Comment by joestringer** [comment]
Do you know why the [lint test](https://github.com/cilium/cilium/pull/14845/checks?check_run_id=1820960018) failed? That's my main reservation against merging right now.

**Comment by christarazi** [comment]
> Do you know why the [lint test](https://github.com/cilium/cilium/pull/14845/checks?check_run_id=1820960018) failed? That's my main reservation against merging right now.

Not sure why it failed; it might have been transient. Rebasing onto latest

**Comment by christarazi** [comment]
Seems to have passed now after rebasing

**Pull request merged**
