### PR TITLE
Reduce size of bugtool binary

### PR DESCRIPTION
**Pull request by tgraf**
``` release-note
Deprecate bugtool HTTP server option (--serve)
```

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6237)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failed due to `cmdref` not being updated: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8044/

**Review by aanm — APPROVED** [review]

**Comment by joestringer** [comment]
Should probably minor release note this as something like "Deprecate bugtool HTTP server option".

**Comment by tgraf** [comment]
> Should probably minor release note this as something like "Deprecate bugtool HTTP server option".

I've added an item to the upgrade notes.

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
