### PR TITLE
Test runtime cilium in container (take two)

### LINKED ISSUE #18919: CI: v1.9/v1.10/v1.11: runtime job is broken
PR #18892 broke the runtime job:

```
11:35:16      runtime: Feb 23 19:35:14 runtime cilium-agent[21324]: level=info msg="Cilium 1.9.12 cc7220091f 2022-02-23T02:21:27+00:00 go version go1.16.5 linux/amd64" subsys=daemon
11:35:16      runtime: Feb 23 19:35:14 runtime cilium-agent[21324]: level=fatal msg="Envoy: Binary \"cilium-envoy\" cannot be executed" error="exit status 1" subsys=envoy-manager
```

### PR DESCRIPTION
**Pull request by jrajahalme**
Run Cilium in docker container for the Runtime tests. This is needed so that cilium-envoy built on Ubuntu 20.04 runs also on earlier versions when the correct version of libc is in the container image.

This version keeps the systemd cilium.service, but uses a new script to run Cilium from a docker container from there within Runtime tests. This design has a high degree of compatibility to the prior running cilium-agent directly from cilium.docker.

Test scripts are organised so that there is no change when running CIlium in a development VM. There cilium-agent is still run in the host as before.

While working with this I noticed that CIlium operator fails to run in Runtime tests as it now assumes to be able to reach k8s api-server. Because of this it is pointless to deploy `cilium-operator` for runtime tests. CIlium agent fails after a while due to this if it is using etcd kvstore as the heartbeats are missing. That's why the kvstore needs to return to the default (consul) configuration after the etcd test. Previously this was done after each test, but now this is done after all (two) of the kvstore tests, speeding up the tests a bit.

Fixes: #18919

### CODE REVIEW

**Comment by jrajahalme** [comment]
Fixed image references to start with "quay.io"

**Comment by jrajahalme** [comment]
Noticed that `test/provision/install.sh` sets `DOCKER_REGISTRY=docker.io` so had to revert adding `quay.io`...

**Review by tklauser — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
The changes are much cleaner than what I have in mind :100:

**Pull request merged**
