### PR TITLE
v1.11 backport: Avoid unpinning in-use prog arrays in init.sh (`K8sUpdates` fix attempt)

### PR DESCRIPTION
**Pull request by ti-mo**
* #18985 -- Avoid unpinning in-use prog arrays in init.sh (@ti-mo)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18985; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Thanks!

**Review by sayboras — APPROVED** [review]
Thanks a lot :100:

**Comment by gandro** [comment]
/test-backport-1.11

**Comment by ti-mo** [comment]
/test-ci-eks-1.11

**Comment by ti-mo** [comment]
/ci-eks-1.11

**Comment by jrajahalme** [comment]
@ti-mo EKS test passed :-)

**Pull request merged**
