### PR TITLE
v1.7 backports 2020-04-22

### PR DESCRIPTION
**Pull request by jrfastab**
* #10902 -- Add helm NOTES to the root folder (@soumynathan)
* #10961 -- pkg/logging: redirect klog output to logrus (@aanm)
* #10918 -- helm: add option to enable automatic etcd name resolution (@aanm)
* #11008 -- bpf: remap MARK_MAGIC_SNAT_DONE marker to avoid conflicts (@borkmann)
* #11021 -- pkg/k8s: detect k8s mode if env variable K8S_NODE_NAME is set
* #11040 -- CRD: fix allocation logic of identities with the same set of labels
* #10984 -- datapath: Fix wrong rev-NAT xlation due to stale conntrack entry
* #11015 --  daemon: Fatal on startup when Identity CRD is enabled without k8s
* #11057 -- Restore node IP behavior of Cilium < 1.7
* #11072 -- test: Run kubectl in test VM for older K8s releases (@jrajahalme)
* #10378 -- test: Install Helm 3 (@jrajahalme)

Backport notes: numerous conflicts mostly in docs, testing and bpf (skb->ctx) datapath.

Pushed bpf.sha changes into commits to allow for bisecting.

Popped, * #10926 -- bpf: Preserve source identity for hairpin via stack (@tgraf) while we debug.
 
PR 10928 split into follow up series do not close until #11239 is also merged. 
   #10928 -- datapath/iptables: Masquerade hairpin traffic that traversed the stack

```upstream-prs
$ for pr in 10902 10961 10918 11008 11021 11040 10984 11015 11057 11072 10378; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by joestringer** [comment]
Seems like one of the patches is relying on a code refactor:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19066/execution/node/55/log/

```
09:02:00  build github.com/cilium/cilium/daemon: cannot load github.com/cilium/cilium/pkg/node/types: open /go/src/github.com/cilium/cilium/pkg/node/types: no such file or directory
[2020-04-22T16:02:00.010Z] make[1]: *** [clean] Error 1
[2020-04-22T16:02:00.010Z] Makefile:29: recipe for target 'clean' failed
09:02:00  make[1]: Leaving directory '/go/src/github.com/cilium/cilium/daemon'
09:02:00  make: [clean-container] Error 2 (ignored)
```

If it helps, we can try to trim down the backports to just the release-blocker PRs right now as we would like to get a release out with the minimal set of changes that are immediately affecting users.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
@joestringer fixed up that specific error lets see if we get anymore.

**Comment by christarazi** [comment]
Looks like unit tests failed: https://travis-ci.com/github/cilium/cilium/builds/161515964

```
# github.com/cilium/cilium/test/k8sT
test/k8sT/Conformance.go:56:16: undefined: helpers.GetBadLogMessages
test/k8sT/Conformance.go:57:10: kubectl.ValidateListOfErrorsInLogs undefined (type *helpers.Kubectl has no field or method ValidateListOfErrorsInLogs)
make[1]: *** [govet] Error 2
make[1]: Leaving directory `/home/travis/gopath/src/github.com/cilium/cilium'
make: *** [unit-tests] Error 2
```

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by joestringer** [comment]
```
ok  	github.com/cilium/cilium/daemon	22.438s	coverage: 14.0% of statements in ./...
/tmp/go-build039424075/b001/operator.test flag redefined: log_dir
panic: /tmp/go-build039424075/b001/operator.test flag redefined: log_dir
goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0000d8120, 0x2758ec0, 0x3bdddd0, 0x233f717, 0x7, 0x2398cda, 0x2f)
	/home/travis/.gimme/versions/go1.13.10.linux.amd64/src/flag/flag.go:848 +0x4ae
flag.(*FlagSet).StringVar(...)
	/home/travis/.gimme/versions/go1.13.10.linux.amd64/src/flag/flag.go:751
k8s.io/klog.InitFlags(0x0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/k8s.io/klog/klog.go:420 +0x7f
github.com/cilium/cilium/operator.init.1()
	/home/travis/gopath/src/github.com/cilium/cilium/operator/main.go:179 +0x110d
FAIL	github.com/cilium/cilium/operator	0.044s
FAIL
make: *** [unit-tests] Error 1
```

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
direct routing + encryption failed. Lets retry and see if its repeatable.

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19080/

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by brb** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19083/testReport/junit/Suite-k8s-1/17/K8sDatapathConfig_Transparent_encryption_DirectRouting_Check_connectivity_with_transparent_encryption_and_direct_routing/ failed due to:
```
2020-04-23T06:40:22.151465604Z level=debug msg="netlink: Replacing qdisc for lxc0380ecf59385 succeeded" subsys=datapath-loader
2020-04-23T06:40:22.234825065Z level=error msg="Command execution failed" cmd="[tc filter replace dev lxc0380ecf59385 ingress prio 1 handle 1 bpf da obj 2178_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader
2020-04-23T06:40:22.234911101Z level=warning subsys=datapath-loader
2020-04-23T06:40:22.234957764Z level=warning msg="Prog section '2/10' rejected: Permission denied (13)!" subsys=datapath-loader
2020-04-23T06:40:22.23500002Z level=warning msg=" - Type:         3" subsys=datapath-loader
2020-04-23T06:40:22.235043152Z level=warning msg=" - Attach Type:  0" subsys=datapath-loader
2020-04-23T06:40:22.235118941Z level=warning msg=" - Instructions: 3371 (0 over limit)" subsys=datapath-loader
2020-04-23T06:40:22.235189366Z level=warning msg=" - License:      GPL" subsys=datapath-loader
2020-04-23T06:40:22.235246313Z level=warning subsys=datapath-loader
2020-04-23T06:40:22.235288395Z level=warning msg="Verifier analysis:" subsys=datapath-loader
2020-04-23T06:40:22.235341353Z level=warning subsys=datapath-loader
2020-04-23T06:40:22.23538375Z level=warning msg="Skipped 65272 bytes, use 'verb' option for the full verbose log." subsys=datapath-loader
2020-04-23T06:40:22.235424796Z level=warning msg="[...]" subsys=datapath-loader
2020-04-23T06:40:22.235465153Z level=warning msg="= 0" subsys=datapath-loader
2020-04-23T06:40:22.235506598Z level=warning msg="3157: (7b) *(u64 *)(r10 -64) = r1" subsys=datapath-loader
2020-04-23T06:40:22.23554827Z level=warning msg="3158: (7b) *(u64 *)(r10 -72) = r1" subsys=datapath-loader
2020-04-23T06:40:22.235589231Z level=warning msg="3159: (b7) r1 = 512" subsys=datapath-loader
2020-04-23T06:40:22.235630323Z level=warning msg="3160: (7b) *(u64 *)(r10 -112) = r1" subsys=datapath-loader
2020-04-23T06:40:22.235672137Z level=warning msg="3161: (bf) r2 = r10" subsys=datapath-loader
2020-04-23T06:40:22.235713215Z level=warning msg="3162: (07) r2 += -112" subsys=datapath-loader
2020-04-23T06:40:22.235754759Z level=warning msg="3163: (18) r1 = 0xffff8f84c3215e40" subsys=datapath-loader
2020-04-23T06:40:22.235796003Z level=warning msg="3165: (85) call 1" subsys=datapath-loader
2020-04-23T06:40:22.23583743Z level=warning msg="3166: (15) if r0 == 0x0 goto pc+10" subsys=datapath-loader
2020-04-23T06:40:22.235881571Z level=warning msg=" R0=map_value(ks=8,vs=16,id=0),min_value=0,max_value=0 R6=inv R7=inv R8=map_value(ks=20,vs=48,id=0),min_value=0,max_value=0 R9=inv R10=fp fp-200=map_ptr fp-192=ctx" subsys=datapath-loader
2020-04-23T06:40:22.235935118Z level=warning msg="3167: (79) r1 = *(u64 *)(r0 +0)" subsys=datapath-loader
2020-04-23T06:40:22.235977239Z level=warning msg="3168: (07) r1 += 1" subsys=datapath-loader
2020-04-23T06:40:22.236018797Z level=warning msg="3169: (7b) *(u64 *)(r0 +0) = r1" subsys=datapath-loader
2020-04-23T06:40:22.236076677Z level=warning msg="3170: (79) r1 = *(u64 *)(r0 +8)" subsys=datapath-loader
2020-04-23T06:40:22.236118219Z level=warning msg="3171: (0f) r1 += r6" subsys=datapath-loader
2020-04-23T06:40:22.23615961Z level=warning msg="3172: (7b) *(u64 *)(r0 +8) = r1" subsys=datapath-loader
2020-04-23T06:40:22.236200756Z level=warning msg="3173: (79) r6 = *(u64 *)(r10 -192)" subsys=datapath-loader
2020-04-23T06:40:22.236242146Z level=warning msg="3174: (79) r1 = *(u64 *)(r10 -280)" subsys=datapath-loader
2020-04-23T06:40:22.236283922Z level=warning msg="3175: (15) if r1 == 0x0 goto pc+63" subsys=datapath-loader
2020-04-23T06:40:22.236327573Z level=warning msg=" R0=map_value(ks=8,vs=16,id=0),min_value=0,max_value=0 R1=inv R6=ctx R7=inv R8=map_value(ks=20,vs=48,id=0),min_value=0,max_value=0 R9=inv R10=fp fp-200=map_ptr fp-192=ctx" subsys=datapath-loader
2020-04-23T06:40:22.236374383Z level=warning msg="3176: (05) goto pc+14" subsys=datapath-loader
2020-04-23T06:40:22.236416332Z level=warning msg="3191: (61) r7 = *(u32 *)(r6 +0)" subsys=datapath-loader
2020-04-23T06:40:22.236457503Z level=warning msg="3192: (bf) r1 = r6" subsys=datapath-loader
2020-04-23T06:40:22.23649823Z level=warning msg="3193: (85) call 34" subsys=datapath-loader
2020-04-23T06:40:22.236539271Z level=warning msg="3194: (18) r1 = 0x882" subsys=datapath-loader
2020-04-23T06:40:22.23658057Z level=warning msg="3196: (6b) *(u16 *)(r10 -70) = r1" subsys=datapath-loader
2020-04-23T06:40:22.236621403Z level=warning msg="3197: (b7) r1 = 772" subsys=datapath-loader
2020-04-23T06:40:22.236664355Z level=warning msg="3198: (6b) *(u16 *)(r10 -72) = r1" subsys=datapath-loader
2020-04-23T06:40:22.236711823Z level=warning msg="3199: (63) *(u32 *)(r10 -68) = r0" subsys=datapath-loader
2020-04-23T06:40:22.23675501Z level=warning msg="3200: (b7) r1 = 1" subsys=datapath-loader
2020-04-23T06:40:22.23679827Z level=warning msg="3201: (6b) *(u16 *)(r10 -58) = r1" subsys=datapath-loader
2020-04-23T06:40:22.236841826Z level=warning msg="3202: (18) r1 = 0x7db2" subsys=datapath-loader
2020-04-23T06:40:22.236885523Z level=warning msg="3204: (63) *(u32 *)(r10 -56) = r1" subsys=datapath-loader
2020-04-23T06:40:22.23692916Z level=warning msg="3205: (63) *(u32 *)(r10 -52) = r9" subsys=datapath-loader
2020-04-23T06:40:22.236973554Z level=warning msg="3206: (79) r1 = *(u64 *)(r10 -248)" subsys=datapath-loader
2020-04-23T06:40:22.237017245Z level=warning msg="3207: (73) *(u8 *)(r10 -46) = r1" subsys=datapath-loader
2020-04-23T06:40:22.237060164Z level=warning msg="3208: (b7) r1 = 0" subsys=datapath-loader
2020-04-23T06:40:22.237103613Z level=warning msg="3209: (73) *(u8 *)(r10 -38) = r1" subsys=datapath-loader
2020-04-23T06:40:22.23714792Z level=warning msg="3210: (73) *(u8 *)(r10 -39) = r1" subsys=datapath-loader
2020-04-23T06:40:22.237191678Z level=warning msg="3211: (73) *(u8 *)(r10 -40) = r1" subsys=datapath-loader
2020-04-23T06:40:22.237235592Z level=warning msg="3212: (73) *(u8 *)(r10 -41) = r1" subsys=datapath-loader
2020-04-23T06:40:22.237293338Z level=warning msg="3213: (73) *(u8 *)(r10 -42) = r1" subsys=datapath-loader
2020-04-23T06:40:22.237338143Z level=warning msg="3214: (73) *(u8 *)(r10 -43) = r1" subsys=datapath-loader
2020-04-23T06:40:22.23739621Z level=warning msg="3215: (73) *(u8 *)(r10 -44) = r1" subsys=datapath-loader
2020-04-23T06:40:22.237441021Z level=warning msg="3216: (73) *(u8 *)(r10 -45) = r1" subsys=datapath-loader
2020-04-23T06:40:22.237485784Z level=warning msg="3217: (6b) *(u16 *)(r10 -48) = r1" subsys=datapath-loader
2020-04-23T06:40:22.237556689Z level=warning msg="3218: (73) *(u8 *)(r10 -37) = r1" subsys=datapath-loader
2020-04-23T06:40:22.237600408Z level=warning msg="3219: (63) *(u32 *)(r10 -36) = r1" subsys=datapath-loader
2020-04-23T06:40:22.237654446Z level=warning msg="3220: (7b) *(u64 *)(r10 -32) = r1" subsys=datapath-loader
2020-04-23T06:40:22.237736995Z level=warning msg="3221: (63) *(u32 *)(r10 -64) = r7" subsys=datapath-loader
2020-04-23T06:40:22.237833855Z level=warning msg="3222: (79) r1 = *(u64 *)(r10 -280)" subsys=datapath-loader
2020-04-23T06:40:22.237921484Z level=warning msg="3223: (2d) if r7 > r1 goto pc+1" subsys=datapath-loader
2020-04-23T06:40:22.238121135Z level=warning msg=" R0=inv,min_value=0,max_value=0 R1=inv R6=ctx R7=inv R8=map_value(ks=20,vs=48,id=0),min_value=0,max_value=0 R9=inv R10=fp fp-200=map_ptr fp-192=ctx" subsys=datapath-loader
2020-04-23T06:40:22.238374629Z level=warning msg="3224: (7b) *(u64 *)(r10 -280) = r7" subsys=datapath-loader
2020-04-23T06:40:22.238517824Z level=warning msg="3225: (79) r3 = *(u64 *)(r10 -280)" subsys=datapath-loader
2020-04-23T06:40:22.238702314Z level=warning msg="3226: (6b) *(u16 *)(r10 -60) = r3" subsys=datapath-loader
2020-04-23T06:40:22.238807587Z level=warning msg="3227: (67) r3 <<= 32" subsys=datapath-loader
2020-04-23T06:40:22.238908913Z level=warning msg="3228: (18) r1 = 0xffffffff" subsys=datapath-loader
2020-04-23T06:40:22.238990166Z level=warning msg="3230: (4f) r3 |= r1" subsys=datapath-loader
2020-04-23T06:40:22.23906371Z level=warning msg="3231: (bf) r4 = r10" subsys=datapath-loader
2020-04-23T06:40:22.239149763Z level=warning msg="3232: (07) r4 += -72" subsys=datapath-loader
2020-04-23T06:40:22.239236197Z level=warning msg="3233: (79) r6 = *(u64 *)(r10 -192)" subsys=datapath-loader
2020-04-23T06:40:22.239325867Z level=warning msg="3234: (bf) r1 = r6" subsys=datapath-loader
2020-04-23T06:40:22.239412366Z level=warning msg="3235: (18) r2 = 0xffff8f85d70bfe00" subsys=datapath-loader
2020-04-23T06:40:22.239497099Z level=warning msg="3237: (b7) r5 = 48" subsys=datapath-loader
2020-04-23T06:40:22.239582585Z level=warning msg="3238: (85) call 25" subsys=datapath-loader
2020-04-23T06:40:22.239668458Z level=warning msg="3239: (61) r7 = *(u32 *)(r6 +0)" subsys=datapath-loader
2020-04-23T06:40:22.239754175Z level=warning msg="3240: (bf) r1 = r6" subsys=datapath-loader
2020-04-23T06:40:22.239839594Z level=warning msg="3241: (85) call 34" subsys=datapath-loader
2020-04-23T06:40:22.239925529Z level=warning msg="3242: (18) r1 = 0x882" subsys=datapath-loader
2020-04-23T06:40:22.240011886Z level=warning msg="3244: (6b) *(u16 *)(r10 -70) = r1" subsys=datapath-loader
2020-04-23T06:40:22.240131023Z level=warning msg="3245: (b7) r1 = 1027" subsys=datapath-loader
2020-04-23T06:40:22.24024138Z level=warning msg="3246: (6b) *(u16 *)(r10 -72) = r1" subsys=datapath-loader
2020-04-23T06:40:22.240337633Z level=error msg="Command execution failed" cmd="[tc filter replace dev lxc_health ingress prio 1 handle 1 bpf da obj 345_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader
2020-04-23T06:40:22.240475779Z level=warning msg="3247: (63) *(u32 *)(r10 -68) = r0" subsys=datapath-loader
2020-04-23T06:40:22.240597838Z level=warning msg="3248: (b7) r1 = 1" subsys=datapath-loader
2020-04-23T06:40:22.24077987Z level=warning msg="3249: (6b) *(u16 *)(r10 -58) = r1" subsys=datapath-loader
2020-04-23T06:40:22.240841315Z level=warning msg="3250: (b7) r1 = 0" subsys=datapath-loader
2020-04-23T06:40:22.24089831Z level=warning msg="3251: (7b) *(u64 *)(r10 -56) = r1" subsys=datapath-loader
2020-04-23T06:40:22.240954745Z level=warning msg="3252: (63) *(u32 *)(r10 -64) = r7" subsys=datapath-loader
2020-04-23T06:40:22.241010354Z level=warning msg="3253: (b7) r1 = 128" subsys=datapath-loader
2020-04-23T06:40:22.241066722Z level=warning msg="3254: (2d) if r1 > r7 goto pc+1" subsys=datapath-loader
2020-04-23T06:40:22.241126675Z level=warning msg=" R0=inv,min_value=0,max_value=0 R1=imm128,min_value=128,max_value=128 R6=ctx R7=inv,min_value=128 R8=map_value(ks=20,vs=48,id=0),min_value=0,max_value=0 R9=inv R10=fp fp-200=map_ptr fp-192=ctx" subsys=datapath-loader
2020-04-23T06:40:22.241182792Z level=warning msg="3255: (b7) r7 = 128" subsys=datapath-loader
2020-04-23T06:40:22.241287056Z level=warning msg="3256: (6b) *(u16 *)(r10 -60) = r7" subsys=datapath-loader
2020-04-23T06:40:22.241345109Z level=warning msg="3257: (67) r7 <<= 32" subsys=datapath-loader
2020-04-23T06:40:22.24140153Z level=warning msg="3258: (18) r1 = 0xffffffff" subsys=datapath-loader
2020-04-23T06:40:22.241472223Z level=warning msg="3260: (4f) r7 |= r1" subsys=datapath-loader
2020-04-23T06:40:22.241527686Z level=warning msg="3261: (bf) r4 = r10" subsys=datapath-loader
2020-04-23T06:40:22.241591316Z level=warning msg="3262: (07) r4 += -72" subsys=datapath-loader
2020-04-23T06:40:22.24164932Z level=warning msg="3263: (79) r1 = *(u64 *)(r10 -192)" subsys=datapath-loader
2020-04-23T06:40:22.241778929Z level=warning msg="3264: (18) r2 = 0xffff8f85d70bfe00" subsys=datapath-loader
2020-04-23T06:40:22.241881244Z level=warning msg="3266: (bf) r3 = r7" subsys=datapath-loader
2020-04-23T06:40:22.24200166Z level=warning msg="3267: (b7) r5 = 24" subsys=datapath-loader
2020-04-23T06:40:22.242163094Z level=warning msg="3268: (85) call 25" subsys=datapath-loader
2020-04-23T06:40:22.242313543Z level=warning msg="3269: (79) r1 = *(u64 *)(r10 -304)" subsys=datapath-loader
2020-04-23T06:40:22.242403087Z level=warning msg="3270: (67) r1 <<= 32" subsys=datapath-loader
2020-04-23T06:40:22.242504461Z level=warning msg="3271: (77) r1 >>= 32" subsys=datapath-loader
2020-04-23T06:40:22.242585265Z level=warning subsys=datapath-loader
2020-04-23T06:40:22.242666355Z level=warning msg="3272: (15) if r1 == 0x0 goto pc+3" subsys=datapath-loader
2020-04-23T06:40:22.242801Z level=warning msg=" R0=inv,min_value=0,max_value=0 R1=inv32 R6=ctx R7=inv R8=map_value(ks=20,vs=48,id=0),min_value=0,max_value=0 R9=inv R10=fp fp-200=map_ptr fp-192=ctx" subsys=datapath-loader
2020-04-23T06:40:22.242920438Z level=warning msg="3273: (79) r1 = *(u64 *)(r10 -296)" subsys=datapath-loader
2020-04-23T06:40:22.24308475Z level=warning msg="3274: (57) r1 &= 255" subsys=datapath-loader
2020-04-23T06:40:22.243211174Z level=warning msg="3275: (55) if r1 != 0x0 goto pc+3" subsys=datapath-loader
2020-04-23T06:40:22.243339107Z level=warning msg=" R0=inv,min_value=0,max_value=0 R1=inv56,min_value=0,max_value=0 R6=ctx R7=inv R8=map_value(ks=20,vs=48,id=0),min_value=0,max_value=0 R9=inv R10=fp fp-200=map_ptr fp-192=ctx" subsys=datapath-loader
2020-04-23T06:40:22.24344087Z level=warning msg="3276: (79) r1 = *(u64 *)(r10 -192)" subsys=datapath-loader
2020-04-23T06:40:22.243559833Z level=warning msg="3277: (61) r4 = *(u32 *)(r1 +8)" subsys=datapath-loader
2020-04-23T06:40:22.243659822Z level=warning msg="3278: (05) goto pc+7" subsys=datapath-loader
2020-04-23T06:40:22.24376578Z level=warning msg="3286: (07) r1 += 8" subsys=datapath-loader
2020-04-23T06:40:22.24386031Z level=warning msg="3287: (18) r2 = 0x7db2" subsys=datapath-loader
2020-04-23T06:40:22.243945202Z level=warning msg="3289: (18) r3 = 0x7db2" subsys=datapath-loader
2020-04-23T06:40:22.244028073Z level=warning msg="3291: (67) r3 <<= 16" subsys=datapath-loader
2020-04-23T06:40:22.244113602Z level=warning msg="3292: (57) r2 &= 16711680" subsys=datapath-loader
2020-04-23T06:40:22.244196477Z level=warning msg="3293: (77) r2 >>= 16" subsys=datapath-loader
2020-04-23T06:40:22.244279618Z level=warning msg="3294: (4f) r3 |= r2" subsys=datapath-loader
2020-04-23T06:40:22.244383835Z level=warning msg="3295: (57) r4 &= 61440" subsys=datapath-loader
2020-04-23T06:40:22.244554524Z level=warning msg="3296: (4f) r4 |= r3" subsys=datapath-loader
2020-04-23T06:40:22.244625413Z level=warning msg="3297: (47) r4 |= 3840" subsys=datapath-loader
2020-04-23T06:40:22.244860075Z level=warning msg="3298: (63) *(u32 *)(r1 +0) = r4" subsys=datapath-loader
2020-04-23T06:40:22.244949579Z level=warning msg="Prog section '2/10' rejected: Permission denied (13)!" subsys=datapath-loader
2020-04-23T06:40:22.245029472Z level=warning msg="R1 invalid mem access 'inv'" subsys=datapath-loader
2020-04-23T06:40:22.245113955Z level=warning subsys=datapath-loader
2020-04-23T06:40:22.245202522Z level=warning msg="Error filling program arrays!" subsys=datapath-loader
2020-04-23T06:40:22.245273317Z level=warning msg="Unable to load program" subsys=datapath-loader
2020-04-23T06:40:22.245522555Z level=warning msg=" - Type:         3" subsys=datapath-loader
2020-04-23T06:40:22.245595935Z level=warning msg=" - Attach Type:  0" subsys=datapath-loader
2020-04-23T06:40:22.245660958Z level=warning msg=" - Instructions: 3371 (0 over limit)" subsys=datapath-loader
2020-04-23T06:40:22.245723867Z level=warning msg=" - License:      GPL" subsys=datapath-loader
2020-04-23T06:40:22.245819697Z level=warning subsys=datapath-loader
```

**Comment by brb** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
LGTM for my commits. One of the commit introduces `nodeTypes.Node` references which are fixed in a later commit again. It will break bisecting but the overall change is correct.

**Review by christarazi — APPROVED** [review]

**Review by aanm — APPROVED** [review]
My commits LGTM

**Comment by jrfastab** [comment]
dropped, ' bpf: Preserve source identity for hairpin via stack ' as we debug verifier issue.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-gke

**Comment by joestringer** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
test-docs-please

**Comment by joestringer** [comment]
test-upstream-k8s

**Comment by joestringer** [comment]
(FYI I fired off all the other bits that would comprise `never-tell-me-the-odds` without re-triggering the existing test runs, so hopefully we'll get at least those results in sooner rather than later)

**Comment by joestringer** [comment]
Initial look is positive, just the newly added test `Check connectivity-check compliance with portmap chaining` failing so far, which presumably validates the commit which has been reverted.

**Comment by joestringer** [comment]
Hit https://github.com/cilium/cilium/issues/11204 , #11126.

**Comment by jrajahalme** [comment]
One GInko CI test for k8s 1.17 failed timing out waiting all pods being ready before the actual test started. One container, but can't figure out why: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19247/testReport/junit/Suite-k8s-1/17/K8sConformance_Portmap_Chaining_Check_connectivity_check_compliance_with_portmap_chaining/

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by joestringer** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
test-upstream-k8s

**Comment by joestringer** [comment]
test-upstream-k8s

**Comment by joestringer** [comment]
test-docs-please

**Comment by jrajahalme** [comment]
Known CI flake #9902

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-missed-k8s

**Comment by jrajahalme** [comment]
Issued #11213 for a likely test flake

**Comment by jrajahalme** [comment]
Hit #10256

**Comment by jrajahalme** [comment]
Istio tests fail on older k8s releases until #11072 is also backported.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-missed-k8s

**Comment by jrajahalme** [comment]
test-upstream-k8s

**Comment by jrajahalme** [comment]
Added backport of #11072

**Comment by joestringer** [comment]
Upstream test stalled downloading vagrant box:
https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/2065/execution/node/33/log/

**Comment by joestringer** [comment]
test-upstream-k8s

**Comment by joestringer** [comment]
Out of the four checks that are marked failing:

1. Cilium-Ginkgo-GKE is known to fail due to https://github.com/cilium/cilium/issues/11204
1. Cilium-Ginkgo-Test-k8s failed due to two new issues listed below.
1. Cilium-PR-Ginkgo-Tests-K8s is the same as (2)
1. K8s-1.17-Kernel-4.19 actually just timed out while downloading the VM images.

## k8s issues hit:
### K8sUpdates Tests upgrade and downgrade from a Cilium stable image to master:
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
Unable to install helm repository
Expected command: helm repo add cilium https://helm.cilium.io 
To succeed, but it failed:
Exitcode: 1 
Stdout:
 	 
Stderr:
 	 Error: Couldn't load repositories file (/home/vagrant/.helm/repository/repositories.yaml).
	 You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/k8sT/Updates.go:121
```

Potentially related to the recently backported changes? This failed for both k8s runs.

### K8sFQDNTest Restart Cilium validate that FQDN is still working

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.12-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:384
Test suite timed out after 1h38m0s
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.12-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:539
```

Did the latest changes modify the timeouts?

**Comment by jrajahalme** [comment]
@joestringer Need to backport #10378 as well to install Helm 3 instead of 2.x.y. I'll do it.

**Comment by jrajahalme** [comment]
Timeout for `test-missed-k8s` is the same as in master:
```
        GINKGO_TIMEOUT="98m"
```

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-missed-k8s

**Comment by jrajahalme** [comment]
test-upstream-k8s

**Comment by joestringer** [comment]
test-docs-please

**Comment by joestringer** [comment]
Only failures are known flakes #11204 , #11126. Neither are required to merge backports.

Merging. :tada:

Thanks @jrfastab @jrajahalme !

**Pull request merged**
