### PR TITLE
[v1.8] Delete Cilium Endpoints for no longer running Pods

### PR DESCRIPTION
**Pull request by aanm**
Since the backport https://github.com/cilium/cilium/pull/13263 was not enough, we need to backport a couple more commits from the original PR https://github.com/cilium/cilium/pull/13220

These commits are also required since a leftover Pod might no longer have a local cilium endpoint available. This means, on restore, the leftover Cilium endpoint will never be removed by the Cilium agent. Thus, the job of garbage collecting these Cilium Endpoints needs to be done by the Cilium Operator.

```release-note
Delete Cilium Endpoints for no longer running Pods
```

Fixes https://github.com/cilium/cilium/issues/13240

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.8

**Review by christarazi — APPROVED** [review]

**Comment by aanm** [comment]
retest-net-next

**Comment by aanm** [comment]
test-backport-1.8

**Comment by nebril** [comment]
test-missed-k8s

**Pull request merged**
