### PR TITLE
test: change accees of go dir in test vm

### PR DESCRIPTION
**Pull request by nebril**
This directory had some subdirs that belonged to root, which caused upstream tests to fail

### CODE REVIEW

**Comment by nebril** [comment]
test-k8s-upstream

**Comment by nebril** [comment]
test-k8s-upstream

**Comment by nebril** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
test-k8s-upstream

**Comment by nebril** [comment]
test-k8s-upstream

**Comment by nebril** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-1.19-4.19

**Review by nbusseneau — APPROVED** [review]
It's weird it was working before, but w/e.

**Pull request merged**
