### PR TITLE
Python yamllint friendly

### PR DESCRIPTION
**Pull request by Kami-no**
Non-functional refactoring:

- python yamllint friendly (whitespaces and "---" in the beginning)
- "apiVersion" before "kind"

Signed-off-by: Dmitriy Zinin <admin@kami-no.ru>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4849)

### CODE REVIEW

**Review by joestringer — COMMENTED** [review]
Thanks for the proposal! Could you also run `make -C examples/kubernetes` to generate each of the kubernetes versioned YAMLs from these templates?

This will also try to change the image, but the image should not be changed from `- image: docker.io/cilium/cilium:latest`.

Also, can you please rebase against latest master and remove the merge commit?

**Comment by Kami-no** [comment]
Ok, I'll make it tomorrow both.

**Comment by Kami-no** [comment]
Done

**Comment by Kami-no** [comment]
In some cases script generates '---' twice. I've not removed them. Perhaps fix for script required.

**Comment by tgraf** [comment]
test-me-please

**Comment by Kami-no** [comment]
```
00:51:41 fatal: destination path 'kubernetes' already exists and is not an empty directory.`
```
Why this test failed?

**Review by aanm — CHANGES_REQUESTED** [review]
The sed command didn't  do the proper replacement for k8s 1.11 files. Please apply the following diff and run `make clean && make CILIUM_VERSION=latest` to see if it works in your OS.
```
diff --git a/examples/kubernetes/Makefile b/examples/kubernetes/Makefile
index 115956db2..0753cadd5 100644
--- a/examples/kubernetes/Makefile
+++ b/examples/kubernetes/Makefile
@@ -12,7 +12,7 @@ define make_concat
 all: $(1)/$(2)
 $(1)/$(2):
        @$(ECHO_GEN)$$@
-       -$(QUIET)for f in $$^ ; do cat "$$$${f}"; echo "---" ; done >$$@
+       -$(QUIET)for f in $$^ ; do cat "$$$${f}"; done >$$@
 endef
 
 # make_yaml creates a YAML specific for a K8s version.
@@ -22,7 +22,7 @@ $(1)/$(patsubst templates/v1/%,%,$(patsubst %.yaml.sed,%.yaml,$(2))):
        @$(ECHO_GEN)$$@
        @echo "$(CILIUM_VERSION)" | egrep -Eq '(v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+(-.+)?)|(latest)' || \
        (echo "\"$(CILIUM_VERSION)\" is not a valid version. Must match regexp '(v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+(-.+)?)|(latest)'. Please fix VERSION file" && false)
-       -$(QUIET)sed -f $(1)/transforms2sed.sed -e s+__CILIUM_VERSION__+$$(CILIUM_VERSION)+ <$$< >$$@
+       -$(QUIET)sed --posix -f $(1)/transforms2sed.sed -e s+__CILIUM_VERSION__+$$(CILIUM_VERSION)+ <$$< >$$@
 endef
 
 SOURCES = $(wildcard templates/v1/*.yaml*)
diff --git a/examples/kubernetes/templates/v1/cilium-rbac.yaml.sed b/examples/kubernetes/templates/v1/cilium-rbac.yaml.sed
index 96af5e724..c4b49a0ca 100644
--- a/examples/kubernetes/templates/v1/cilium-rbac.yaml.sed
+++ b/examples/kubernetes/templates/v1/cilium-rbac.yaml.sed
@@ -13,7 +13,6 @@ subjects:
     namespace: kube-system
   - kind: Group
     name: system:nodes
-
 ---
 apiVersion: __RBAC_API_VERSION__
 kind: ClusterRole
```

**Comment by Kami-no** [comment]
I've OS X - `--posix` is invalid for sed. I'll try later with Ubuntu.

BTW: also in `examples/kubernetes/Makefile` you have problems with indent...

**Comment by Kami-no** [comment]
Better than ever.

**Comment by tgraf** [comment]
test-me-please

**Comment by Kami-no** [comment]
Kafka policy this time?

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
> Kafka policy this time?

Yes, it's a known CI flake

**Comment by ianvernon** [comment]
Prior build failure was due to microscope being flaky; this test has been disabled and a fix is actively been worked on

Failure link: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5210/testReport/junit/k8s-1/11/K8sValidatedMicroscope_Runs_microscope/ 

Trying again.

**Comment by ianvernon** [comment]
test-me-please

**Comment by aanm** [comment]
@Kami-no Can you rebase this against master? Please ping me on slack and I'll take a look ASAP to merge this before getting more conflicts.

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by Kami-no** [comment]
Code for validation script:
```
#!/bin/bash

pip3 install yamllint
yamllint examples/kubernetes/1*

if [ $? -eq 0 ]; then
    echo 'Passed'
else
    echo 'Failed'
fi
```

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Great work, thanks @Kami-no

**Comment by Kami-no** [comment]
Great product!

**Pull request merged**
