### PR TITLE
ci: IPSec E2E tests concurrent run

### PR DESCRIPTION
**Pull request by viktor-kurchenko**
IPSec E2E workflow improved with connectivity tests concurrent run.

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
This is great if it can help reduce runtime!

I'm just curious how many times was it tested? Concurrent executions like this are more likely to lead to flakes due to race conditions so I'm a bit worried about that.

**Comment by viktor-kurchenko** [comment]
> I'm just curious how many times was it tested? Concurrent executions like this are more likely to lead to flakes due to race conditions so I'm a bit worried about that.

Do you mean how many times we used `test-concurrency` > 1 or the question is more about IPSec E2E workflow?

**Comment by viktor-kurchenko** [comment]
I've run [IPSec E2E workflow](https://github.com/cilium/cilium/actions/runs/10411173939) 10 times:
1. No failures
2. 1 job failed
3. No failures
4. 1 job failed
5. No failures
6. No failures
7. No failures
8. No failures
9. No failures
10. 1 job failed

@pchaigno WDYT?

**Comment by pchaigno** [comment]
Did any of the failures happen in the newly-concurrent section? If they did, are they known flakes or new ones?

**Comment by viktor-kurchenko** [comment]
> Did any of the failures happen in the newly-concurrent section? If they did, are they known flakes or new ones?

2 failures unrelated to connectivity tests: `Error: Unable to install Cilium: context deadline exceeded`.
Another one failed with the following error:
```
[=] [cilium-test-1] Test [echo-ingress-mutual-auth-spiffe] [15/19]
.  ℹ️  📜 Applying CiliumNetworkPolicy 'echo-ingress-mutual-authentication' to namespace 'cilium-test-1'..
  [-] Scenario [echo-ingress-mutual-auth-spiffe/pod-to-pod]
  [.] Action [echo-ingress-mutual-auth-spiffe/pod-to-pod/curl-ipv4-0: cilium-test-1/client-974f6c69d-rjrtm (10.244.2.55) -> cilium-test-1/echo-other-node-b7bc474bc-bsj8c (10.244.3.197:8080)]
  ❌ command "curl -w %!!(MISSING){(MISSING)local_ip}:%!!(MISSING){(MISSING)local_port} -> %!!(MISSING){(MISSING)remote_ip}:%!!(MISSING){(MISSING)remote_port} = %!!(MISSING){(MISSING)response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 http://10.244.3.197:8080/" failed: error with exec request (pod=cilium-test-1/client-974f6c69d-rjrtm, container=client): command terminated with exit code 28
```

Maybe it's related to the issue: https://github.com/cilium/cilium-cli/issues/673 but I don't think it's due to concurrent run.

**Comment by pchaigno** [comment]
> Maybe it's related to the issue: https://github.com/cilium/cilium-cli/issues/673 but I don't think it's due to concurrent run.

What makes you think it's related to that issue or that it's not caused by the concurrent run? It doesn't seem to match the description of the issue and I'm personally unable to say it's not the result of a race condition (though maybe I'm just missing context).

**Comment by ldelossa** [comment]
Lets remove the ready-to-merge label, if this is not ready to go.

**Comment by viktor-kurchenko** [comment]
> > Maybe it's related to the issue: [cilium/cilium-cli#673](https://github.com/cilium/cilium-cli/issues/673) but I don't think it's due to concurrent run.
> 
> What makes you think it's related to that issue or that it's not caused by the concurrent run? It doesn't seem to match the description of the issue and I'm personally unable to say it's not the result of a race condition (though maybe I'm just missing context).

Do you mean race condition in Cilium CLI after using `test-concurrency` input param?

**Pull request closed without merging**
