### PR TITLE
bpf: static data: use inline asm to access static data

### PR DESCRIPTION
**Pull request by ti-mo**
The new static data approach is fully documented in the code. Using a volatile inline asm block makes for a more predictable outcome in the bytecode, meaning we can simplify the substitution logic on the Go side and start using runtime-provided constants for user space dead code elimination.

Part of: https://github.com/cilium/cilium/issues/27320

```release-note
bpf: static data: use inline asm to access static data
```

### CODE REVIEW

**Review by dylandreimerink — APPROVED** [review]

**Comment by aojea** [comment]
@yasz24  can you PTAL and see the areas where you can help in follow ups?

**Comment by ti-mo** [comment]
This will conflict with https://github.com/cilium/cilium/pull/28417, will wait for that to land first.

**Pull request merged**
