### PR TITLE
Update k8s-install-etcd-operator.rst

### PR DESCRIPTION
**Pull request by johnzheng1975**
The docs may not up-to-date "Add cilium-operator; Change etcd-xxx to cilium-etcd-xxx"

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@johnzheng1975 Commit 245dd3263ba2c3b0ee0d94b5b865f05d738f0db4 does not contain "Signed-off-by".

Please follow instructions provided in https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#developer-s-certificate-of-origin

**Review by johnzheng1975 — COMMENTED** [review]
Signed-off-by: John Zheng <john.zheng@hp.com>

**Comment by johnzheng1975** [comment]
@aanm 
I changed a space in a new commit, which added Signed-off-by.
Is that fulfill the process. Thanks.

**Comment by joestringer** [comment]
@johnzheng1975 you can use `git commit --amend -s` to sign off your commit. Now that you have two commits you may need to squash them together, for instance by using "git rebase --interactive".

**Comment by johnzheng1975** [comment]
Thanks Joe. I have chance to practice git command. 
After merge, I have three commit now ~_~
```
commit fe9cae80db1411682116e28190485d71d55c6134
Author: John Zheng <johnzhengaz@gmail.com>
Date:   Tue Mar 24 17:40:12 2020 +0800

    Update k8s-install-etcd-operator.rst
    
    The docs may not up-to-date "Add cilium-operator; Change etcd-xxx to cilium-etcd-xxx".
    
    Signed-off-by: John Zheng john.zheng@hp.com

commit b4bedba4252f020e983b0cc6d26aca062513dcb0
Author: John Zheng <johnzhengaz@gmail.com>
Date:   Wed Mar 25 11:02:16 2020 +0800

    Update k8s-install-etcd-operator.rst
    
    Signed-off-by: John Zheng<john.zheng@hp.com>

commit 245dd3263ba2c3b0ee0d94b5b865f05d738f0db4
Author: John Zheng <johnzhengaz@gmail.com>
Date:   Tue Mar 24 17:40:12 2020 +0800

    Update k8s-install-etcd-operator.rst
    
    The docs may not up-to-date "Add cilium-operator; Change etcd-xxx to cilium-etcd-xxx"

```
To make it simple, let me close this and get another PR.

**Comment by joestringer** [comment]
@johnzheng1975 Just so you know, you don't need to close the PR and reopen, you can just force push the branch that you originally pushed and github will update the PR to see the new code.

**Pull request closed without merging**
