### PR TITLE
examples/getting-started: Fix failure to install docker

### PR DESCRIPTION
**Pull request by tgraf**
It was no longer possible to install the docker runtime. Bump to Ubuntu 17.10
as the default image and remove the multi node complexity

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Pull request merged**
