### PR TITLE
Modularize ipcache BPF listener

### PR DESCRIPTION
**Pull request by giorio94**
Convert the ipcache BPF listener module into a cell. Additionally drop the existing ipcache map garbage collection logic, which turned out to be buggy and not really effective, as well as not necessary. Please review commit by commit, and refer to the individual commit messages for additional details.

Related: https://github.com/cilium/cilium/issues/28004

### CODE REVIEW

**Comment by giorio94** [comment]
Rebased onto main, let's see if that makes CI happier.

**Comment by giorio94** [comment]
@brb @jrajahalme Ping

**Review by brb — APPROVED** [review]
The WG changes LGTM, thanks.

**Review by jrajahalme — APPROVED** [review]
Nice to review PRs that mostly remove dead code :-)

**Pull request merged**
