### PR TITLE
[v1.10] backport 22179

### PR DESCRIPTION
**Pull request by aanm**
* #22179 -- Add automatic creation of Cilium base images (@aanm)
 * #22268 -- .github/workflows: split the image tag update in two steps (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 22179 22268; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by aanm** [comment]
/test-backport-1.10

**Comment by aanm** [comment]
/test-backport-1.10

**Review by michi-covalent — APPROVED** [review]
💥

**Review by joestringer — APPROVED** [review]
:tada:

**Pull request merged**
