### PR TITLE
.github: Add workflow telemetry

### PR DESCRIPTION
**Pull request by joestringer**
This can help debugging by exposing CPU,Memory,I/O stats and step timing across these workflows. Click through to the "Summary" page for a workflow to see example telemetry output.

See:
- Marketplace listing: https://github.com/marketplace/actions/workflow-telemetry
- Upstream repo: https://github.com/catchpoint/workflow-telemetry-action

Suggested-by: Antonio Ojea <aojea@google.com>

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]
looks wonderful

**Review by viktor-kurchenko — APPROVED** [review]
Thanks!

**Review by aanm — APPROVED** [review]

**Pull request merged**
