### PR TITLE
Remove release scripts

### PR DESCRIPTION
**Pull request by aanm**
Merge at the same time as https://github.com/cilium/release/pull/206

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]
Looks good, thank you!

**Review by michi-covalent — APPROVED** [review]
🧹

**Comment by joestringer** [comment]
This might not backport cleanly, for the same reason we're moving the scripts to github.com/cilium/release - I'm not sure we've kept all branch versions of these scripts in sync with the latest version on `main`.

**Pull request merged**
