### PR TITLE
pkg/probe: probe kernel support for policy routing

### LINKED ISSUE #9834: Lost default route when deployment cilium on MACCHIATObin
## Bug report

**General Information**

- Cilium version v1.6.4
- Kernel version  4.14.22-armada-18.09.3

**How to reproduce the issue**
Disable CONFIG_IP_MULTIPLE_TABLES kernel module

We have ported Cilium v1.6.4 on Arm server. 
Under this premise, try to deploying cilium on MACCHIATObin, which is an Arm-based development board.
Most of the problems encountered in this process are related to the kernel configuration. 
One of the most serious problems is that when the policy routing kernel module is not enabled,following command
	'ip route replace table 2005 default via 192.168.0.XX'
will cause the default route to be overwritten and
the external network cannot be accessed.
so it is necessary to check the kernel configuration about policy routing.

### PR DESCRIPTION
**Pull request by Jianlin-lv**
When without policy routing enabled, following command
'ip route replace table 2005 default via 192.168.0.XX'
will cause the default route to be overwritten and the external network cannot be accessed.

Signed-off-by: Jianlin Lv Jianlin.Lv@arm.com

Fixes: #9834

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9842)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Looks like there's some formatting issue. You can check by running make from the repo:

```
09:22:57  contrib/scripts/check-logging-subsys-field.sh
09:22:57  contrib/scripts/check-fmt.sh
09:22:58  Unformatted Go source code:
09:22:58  ./pkg/datapath/linux/probes/probes_test.go
09:22:58  diff -u ./pkg/datapath/linux/probes/probes_test.go.orig ./pkg/datapath/linux/probes/probes_test.go
09:22:58  --- ./pkg/datapath/linux/probes/probes_test.go.orig	2020-01-14 09:22:58.354864380 +0000
09:22:58  +++ ./pkg/datapath/linux/probes/probes_test.go	2020-01-14 09:22:58.354864380 +0000
09:22:58  @@ -38,65 +38,65 @@
09:22:58   	}{
09:22:58   		{
09:22:58   			systemConfig: SystemConfig{
09:22:58  -				ConfigBpf:               "y",
09:22:58  -				ConfigBpfSyscall:        "y",
09:22:58  -				ConfigNetSchIngress:     "y",
09:22:58  -				ConfigNetClsBpf:         "y",
09:22:58  -				ConfigNetClsAct:         "y",
09:22:58  -				ConfigBpfJit:            "y",
09:22:58  -				ConfigHaveEbpfJit:       "y",
09:22:58  -				ConfigIPMultipleTables:  "y",
09:22:58  -				ConfigCgroupBpf:         "y",
09:22:58  -				ConfigLwtunnelBpf:       "y",
09:22:58  -				ConfigBpfEvents:         "y",
09:22:58  +				ConfigBpf:              "y",
09:22:58  +				ConfigBpfSyscall:       "y",
09:22:58  +				ConfigNetSchIngress:    "y",
09:22:58  +				ConfigNetClsBpf:        "y",
09:22:58  +				ConfigNetClsAct:        "y",
09:22:58  +				ConfigBpfJit:           "y",
09:22:58  +				ConfigHaveEbpfJit:      "y",
09:22:58  +				ConfigIPMultipleTables: "y",
09:22:58  +				ConfigCgroupBpf:        "y",
09:22:58  +				ConfigLwtunnelBpf:      "y",
09:22:58  +				ConfigBpfEvents:        "y",
09:22:58   			},
09:22:58   			expectErr: false,
09:22:58   		},
09:22:58   		{
09:22:58   			systemConfig: SystemConfig{
09:22:58  -				ConfigBpf:               "y",
09:22:58  -				ConfigBpfSyscall:        "y",
09:22:58  -				ConfigNetSchIngress:     "m",
09:22:58  -				ConfigNetClsBpf:         "m",
09:22:58  -				ConfigNetClsAct:         "y",
09:22:58  -				ConfigBpfJit:            "y",
09:22:58  -				ConfigHaveEbpfJit:       "y",
09:22:58  -				ConfigIPMultipleTables:  "y",
09:22:58  -				ConfigCgroupBpf:         "y",
09:22:58  -				ConfigLwtunnelBpf:       "y",
09:22:58  -				ConfigBpfEvents:         "y",
09:22:58  +				ConfigBpf:              "y",
09:22:58  +				ConfigBpfSyscall:       "y",
09:22:58  +				ConfigNetSchIngress:    "m",
09:22:58  +				ConfigNetClsBpf:        "m",
09:22:58  +				ConfigNetClsAct:        "y",
09:22:58  +				ConfigBpfJit:           "y",
09:22:58  +				ConfigHaveEbpfJit:      "y",
09:22:58  +				ConfigIPMultipleTables: "y",
09:22:58  +				ConfigCgroupBpf:        "y",
09:22:58  +				ConfigLwtunnelBpf:      "y",
09:22:58  +				ConfigBpfEvents:        "y",
09:22:58   			},
09:22:58   			expectErr: false,
09:22:58   		},
09:22:58   		{
09:22:58   			systemConfig: SystemConfig{
09:22:58  -				ConfigBpf:               "y",
09:22:58  -				ConfigBpfSyscall:        "y",
09:22:58  -				ConfigNetSchIngress:     "n",
09:22:58  -				ConfigNetClsBpf:         "n",
09:22:58  -				ConfigNetClsAct:         "y",
09:22:58  -				ConfigBpfJit:            "y",
09:22:58  -				ConfigHaveEbpfJit:       "y",
09:22:58  -				ConfigIPMultipleTables:  "y",
09:22:58  -				ConfigCgroupBpf:         "y",
09:22:58  -				ConfigLwtunnelBpf:       "y",
09:22:58  -				ConfigBpfEvents:         "y",
09:22:58  +				ConfigBpf:              "y",
09:22:58  +				ConfigBpfSyscall:       "y",
09:22:58  +				ConfigNetSchIngress:    "n",
09:22:58  +				ConfigNetClsBpf:        "n",
09:22:58  +				ConfigNetClsAct:        "y",
09:22:58  +				ConfigBpfJit:           "y",
09:22:58  +				ConfigHaveEbpfJit:      "y",
09:22:58  +				ConfigIPMultipleTables: "y",
09:22:58  +				ConfigCgroupBpf:        "y",
09:22:58  +				ConfigLwtunnelBpf:      "y",
09:22:58  +				ConfigBpfEvents:        "y",
09:22:58   			},
09:22:58   			expectErr: true,
09:22:58   		},
09:22:58   		{
09:22:58   			systemConfig: SystemConfig{
09:22:58  -				ConfigBpf:               "n",
09:22:58  -				ConfigBpfSyscall:        "n",
09:22:58  -				ConfigNetSchIngress:     "n",
09:22:58  -				ConfigNetClsBpf:         "n",
09:22:58  -				ConfigNetClsAct:         "n",
09:22:58  -				ConfigBpfJit:            "n",
09:22:58  -				ConfigHaveEbpfJit:       "n",
09:22:58  -				ConfigIPMultipleTables:  "n",
09:22:58  -				ConfigCgroupBpf:         "n",
09:22:58  -				ConfigLwtunnelBpf:       "n",
09:22:58  -				ConfigBpfEvents:         "n",
09:22:58  +				ConfigBpf:              "n",
09:22:58  +				ConfigBpfSyscall:       "n",
09:22:58  +				ConfigNetSchIngress:    "n",
09:22:58  +				ConfigNetClsBpf:        "n",
09:22:58  +				ConfigNetClsAct:        "n",
09:22:58  +				ConfigBpfJit:           "n",
09:22:58  +				ConfigHaveEbpfJit:      "n",
09:22:58  +				ConfigIPMultipleTables: "n",
09:22:58  +				ConfigCgroupBpf:        "n",
09:22:58  +				ConfigLwtunnelBpf:      "n",
09:22:58  +				ConfigBpfEvents:        "n",
09:22:58   			},
09:22:58   			expectErr: true,
09:22:58   		},
09:22:58  Makefile:371: recipe for target 'precheck' failed
09:22:58  make: *** [precheck] Error 1
09:23:00  Makefile:87: recipe for target 'jenkins-precheck' failed
09:23:00  make: *** [jenkins-precheck] Error 1
```

**Review by vadorovsky — CHANGES_REQUESTED** [review]
This change will not work. There is no check for `CONFIG_IP_MULTIPLE_TABLES` in bpftool - Cilium is not checking the kernel config on its own, but rather using output of `bpftool feature -j`.

**Comment by Jianlin-lv** [comment]
@mrostecki Yes, You are right, is it possible to add a new function to check kernel configuration other than BPF or to add some documentation?

**Comment by mrostecki** [comment]
@Jianlin-lv 
> @mrostecki Yes, You are right, is it possible to add a new function to check kernel configuration other than BPF or to add some documentation?

I think the only option is to **not** use bpftool for kernel checks and just read `/proc/config.gz` by Cilium, and then use bpftool only for checking map types and generating feature headers.

The problem is that... for now Cilium uses bpftool **only** for kernel checks and my patches to use it for the other things are still not ready to be merged. And they definitely will not make it to Cilium 1.7.0 release.

So, removing bpftool kernel checks now, on master, would pretty much remove bpftool usage in general. To make any sense in using bpftool, we would need to wait until the other ways of using it get in.

That said, would you mind to wait with this PR until we are done with releasing 1.7 and my other PRs about bpftool get merged? Sorry for the trouble!

**Review by joestringer — CHANGES_REQUESTED** [review]
What kind of environment is this typically disabled in? Are there common linux distributions that disable this?

Given the issues outlined above with using bpftool, I wonder if a different approach might work. What happens if you just query the table or attempt to create it to test if policy routing is available?

This is what happens on my system that supports multiple tables, if I query one that doesn't exist:

```
$ ip route list table 8
Error: ipv4: FIB table does not exist.
Dump terminated
$ echo $?
2
```

Perhaps we can do some variation on this to perform feature detection instead?

We can perform queries similar to the `ip route` command above using the vishvananda/netlink library.

**Comment by Jianlin-lv** [comment]
> What kind of environment is this typically disabled in? Are there common linux distributions that disable this?
> 
> Given the issues outlined above with using bpftool, I wonder if a different approach might work. What happens if you just query the table or attempt to create it to test if policy routing is available?
> 
> This is what happens on my system that supports multiple tables, if I query one that doesn't exist:
> 
> ```
> $ ip route list table 8
> Error: ipv4: FIB table does not exist.
> Dump terminated
> $ echo $?
> 2
> ```
> 
> Perhaps we can do some variation on this to perform feature detection instead?
> 
> We can perform queries similar to the `ip route` command above using the vishvananda/netlink library.

This issue was discovered when deploying cilium to MACCHIATObin,which is an Arm-based development board.
Its kernel is trimmed by the manufacturer, not the Linux distribution kernel;
Your suggestion is very helpful, I will try to update this patch using Netlink.

**Comment by iecedge** [comment]
> > What kind of environment is this typically disabled in? Are there common linux distributions that disable this?
> > Given the issues outlined above with using bpftool, I wonder if a different approach might work. What happens if you just query the table or attempt to create it to test if policy routing is available?
> > This is what happens on my system that supports multiple tables, if I query one that doesn't exist:
> > ```
> > $ ip route list table 8
> > Error: ipv4: FIB table does not exist.
> > Dump terminated
> > $ echo $?
> > 2
> > ```
> > 
> > 
> > Perhaps we can do some variation on this to perform feature detection instead?
> > We can perform queries similar to the `ip route` command above using the vishvananda/netlink library.
> 
> This issue was discovered when deploying cilium to MACCHIATObin,which is an Arm-based development board.
> Its kernel is trimmed by the manufacturer, not the Linux distribution kernel;
> Your suggestion is very helpful, I will try to update this patch using Netlink.

@joestringer  @mrostecki  https://github.com/cilium/cilium/pull/10068  using netlink to check kernel configuration of policy routing

**Pull request closed without merging**
