### PR TITLE
Istio: Update to 1.4.3

### PR DESCRIPTION
**Pull request by jrajahalme**
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

```release-note
Istio support is updated to version 1.4.3
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9968)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
turns out Istio 1.4.3 is no longer compatible with K8s 1.11, applying CRDs fails (`The CustomResourceDefinition "sidecars.networking.istio.io" is invalid`). According to [Istio documentation](https://istio.io/docs/setup/getting-started/), Istio 1.4.3 has been tested with Kubernetes releases 1.13, 1.14, 1.15. Hence extended skipping the Istio test for k8s 1.10, 1.11, and 1.12.

Added tabs for helm 2 and 3 into the Istio GSG.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-missed-k8s

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-missed-k8s

**Comment by jrajahalme** [comment]
VM provisioning gets interrupted after 20 minutes. Trying again.

**Comment by jrajahalme** [comment]
test-missed-k8s

**Comment by jrajahalme** [comment]
Istio integration does not work on k8s 1.13 due to a service connectivity problem, the sidecar can't establish a TCP connection to the istio-pilot via the serviceIP/port (ECONNREFUSED). Same test works on k8s 1.14, 1.15, 1.16, and 1.18. The same test used to work with k8s 1.11, 1.12, and 1.13 with the previous version of Istio integration (Istio 1.2.5). Now the minimum supported k8s version for Istio (1.4) is k8s 1.13, but as stated above, the way Cilium/Istio integration is done does not seem to be working with 1.13.

I'm inclined to just document that Cilium/Istio integration has been tested to work with k8s 1.14-1.17.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by aanm** [comment]
@jrajahalme if that's the minimal requirement for istio then we shouldn't test istio with k8s < 1.14.

**Pull request merged**
