### PR TITLE
v1.10 backports 2021-06-14

### PR DESCRIPTION
**Pull request by gandro**
* #16432 -- node: fix arpping test (@jibi)
 * #16328 -- datapath: Use TUNNEL_MODE as indicator for tunnel mode (@anfernee)
 * #16437 -- test/helpers: Fix incorrect count of endpoints (@pchaigno)
 * #16200 -- docs: mark node-to-node IPSec encryption as beta (@qmonnet)
 * #15655 -- Add Helm option to disable registering CRD from Cilium Operator (@Fedosin)
 * #16238 -- docs: add a reference of helm values (@bmcustodio)
 * #16341 -- watchers: Fix BGP subscriber potentially getting skipped (@christarazi)
 * #16338 -- helm,test: Add standalone L4LB XDP tests in a form of Github Action (@brb)
 * #16408 -- docs: add a "Copy Commands" button for shell-session snippets (@qmonnet)
 * #16186 -- docs: ENIs should not be managed by the OS (@gandro)
 * #16459 -- examples: add an example of a hubble-cli Deployment (@kaworu)
 * #16445 -- test: Instrument LB IP via BGP test with debug-events (@christarazi)
 * #16474 -- docs: use `.. code-block:: shell-session` wherever relevant (@qmonnet)
 * #16359 -- remove ARP entries left from previous Cilium run (@aanm)
 * #16407 -- docs: fix warnings for documentation build, use a linter (@qmonnet)
 * #16493 -- ipam: fix crd mode (@joamaki)
 * #16412 -- test: Specify node-selectors in BGP configmap (@christarazi)
 * #16506 -- ci: restart portmap service on CI nodes (@nebril)
 * #16454 -- docs: Fix build failure (@pchaigno)

:warning: Minor resolved merge conflicts for the follwoing commits

- de62fa37c9ac679fd45bb617e8759dd7a4918ccb Had to regenerate docs for 1.10 release and update wordlist @bmcustodio 
- 673ccd7858ac09f799db5d76cc44a71c2e2754c5 Removed change to CODEOWNERS @brb 
- e9166c42485eba02112c3b96ff79a98e766ce4db One of the dev-doctor codeblocks not present on 1.10 @qmonnet 

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16432 16328 16437 16200 15655 16238 16341 16338 16408 16186 16459 16445 16474 16359 16407 16493 16412 16506 16454; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by gandro** [comment]
test-backport-1.10

**Review by qmonnet — APPROVED** [review]
> #16200 -- docs: mark node-to-node IPSec encryption as beta (@qmonnet)
#16408 -- docs: add a "Copy Commands" button for shell-session snippets (@qmonnet)
#16474 -- docs: use .. code-block:: shell-session wherever relevant (@qmonnet)
#16407 -- docs: fix warnings for documentation build, use a linter (@qmonnet)

Look good to me, thank you!

**Review by pchaigno — APPROVED** [review]
Thanks!

> #16328 -- datapath: Use TUNNEL_MODE as indicator for tunnel mode (@anfernee)
#16437 -- test/helpers: Fix incorrect count of endpoints (@pchaigno)

I reviewed these two :point_up: and they look good to me :ship:

**Review by nebril — APPROVED** [review]

**Review by joamaki — APPROVED** [review]
> * #16493 -- ipam: fix crd mode (@joamaki)

LGTM!

**Comment by gandro** [comment]
Travis is due to differences in the `Documentation` folder. Will try to fix them by running `git rebase --interactive --exec "make -C Documentation" upstream/v1.10` - partially seems to be caused by the new rstlinter which discovered issues on the 1.10 branch that don't exist on master.

**Comment by pchaigno** [comment]
@gandro You will need to backport https://github.com/cilium/cilium/pull/16454 to fix the failing docs build. Sorry, I missed the backport label before.

**Review by christarazi — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by brb — APPROVED** [review]
LGTM for my changes, thanks.

**Comment by gandro** [comment]
> @gandro You will need to backport #16454 to fix the failing docs build. Sorry, I missed the backport label before.

Thanks! I was about to fix it manually (because my previous approach of running `make -C Documentation` somehow didn't fix it), but that works too. Applied and updated the PR description.

**Comment by gandro** [comment]
test-backport-1.10

**Comment by gandro** [comment]
Travis hit #15442

**Comment by gandro** [comment]
test-1.19-5.4

**Comment by gandro** [comment]
test-runtime

**Review by kaworu — APPROVED** [review]
LGTM for my patch, thank you!

**Review by bmcustodio — APPROVED** [review]
It's a bit hard to tell about the spelling wordlist, but otherwise LGTM! Thank you @gandro!

**Comment by gandro** [comment]
test-1.21-4.9

**Comment by gandro** [comment]
Unassigned Joe (already got `maintainers` approval) and Gilberto (on PTO). This has passed CI is just waiting on reviews now.

**Comment by gandro** [comment]
test-1.21-4.9

**Comment by aanm** [comment]
test-only --focus="K8sVerifier.*Runs the kernel verifier against Cilium's BPF datapath" --k8s_version=1.21 --kernel_version=4.9

**Comment by aanm** [comment]
test-only --focus="K8sVerifier.*Runs the kernel verifier against Cilium.*" --k8s_version=1.21 --kernel_version=4.9

**Comment by aanm** [comment]
The focus test have passed which previously failed, merging PR.

**Pull request merged**
