### PR TITLE
Use GO_VERSION as single source for the used Go version

### PR DESCRIPTION
**Pull request by tklauser**
Read the Go version from the `GO_VERSION` file and use it to replace the hard-coded versions across the Cilium repo, i.e. in the test scripts, Dockerfiles, packaging and documentation.
    
This allows to bump the Go version in a single place: the `GO_VERSION` file.
    
With this PR, updating to a new Go version (1.13.8 in this example) is now as easy as:
    
    echo 1.13.8 > GO_VERSION && make update-golang

Verified by running the command above and checking that `git grep 1\.13\.7` doesn't return any matches.

Follow up for #10139, as suggested by @florianl

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10163)

### CODE REVIEW

**Comment by tklauser** [comment]
test-docs-please

**Review by aanm — COMMENTED** [review]
awesome improvement, unfortunately we will still miss these:
```
.travis.yml
cilium-docker-plugin.Dockerfile
cilium-operator.Dockerfile
Dockerfile.builder
contrib/packaging/builder/Dockerfile.runtime
```

**Comment by tklauser** [comment]
> awesome improvement, unfortunately we will still miss these:
> 
> ```
> .travis.yml
> cilium-docker-plugin.Dockerfile
> cilium-operator.Dockerfile
> Dockerfile.builder
> contrib/packaging/builder/Dockerfile.runtime
> ```

As far as I understand the `Makefile` these should already be covered by the `update-golang-dockerfiles` and `update-travis-go-version` targets (which get called by `update-golang`):

https://github.com/cilium/cilium/blob/b4cd2bceb95af789a8cea24e9241d3799875e752/Makefile#L454-L461

**Review by aanm — APPROVED** [review]
wow, nice @tklauser ! thanks

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by tklauser** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Pull request merged**
