### PR TITLE
ci-e2e: add job testing node cidr feature

### PR DESCRIPTION
**Pull request by squeed**
Add a job that sets policy-cidr-match-mode=nodes

### CODE REVIEW

**Comment by squeed** [comment]
Hmm, the new job seems to be consistently failing. Investigating.

**Comment by squeed** [comment]
Aha, I accidentally made a broken cluster with a bad job config. That's better.

Confirmed that the test I'm interested in actually ran:

```
 [=] Test [pod-to-node-cidrpolicy]
............
```

**Comment by squeed** [comment]
(note: no sense in running other CI jobs; they're irrelevant. This PR can be considered "all green")

**Review by nathanjsweet — APPROVED** [review]

**Comment by nathanjsweet** [comment]
@squeed Make sure to edit [the configuration table](https://github.com/cilium/cilium/issues/20606#issue-1311768018)

**Review by viktor-kurchenko — APPROVED** [review]
LGTM.

**Review by aanm — APPROVED** [review]
Sorry, I was checking if the removal of `join` would break the junit2md. After a quick look, I don't think it does.

**Pull request merged**
