### PR TITLE
docs, dependabot: Ignore dependencies udpates

### PR DESCRIPTION
**Pull request by qmonnet**
Since we added support for pip in Dependabot's configuration in commit bd36a19e0bf7 ("dependabot: add configuration for Python module updates") the bot has been eager to propose updates for all the packages used for building the documentation.

While updates are good in general, updates for the documentation are not always desirable, or should be accompanied with more testing that we currently have in the CI.

Why not update the dependencies?

- There may be conflicts arising between different packages versions. This has been observed in the past, and dependabot is not always available to detect them correctly.
- The CI should detect major breakages in the builds, but it does not necessarily test all aspects of doc building. For example, the latest Sphinx update has broken the live preview feature, see details in commit 71afdb9895a0 ("docs: Fix live preview (install sphinx-autobuild in the image)").
- The list of requirements should ideally be regenerated from the shortlist (make -C Documentation update-requirements) anyway, to let Pip pull the latest dependencies while sorting out the version
  requirements.
- There are too many active packages. Given the above, investing time to test and validate the updates for each of them is not worth it.

Can we afford to skip the updates?

- They're for dependencies and don't usually bring new features that we use, or don't usually improve the rendering of the documentation.
- Apart from the Algolia search, which does not depend on the Pip packages we use, the documentation website is static and is unlikely to suffer from vulnerabilities that might be reported to these packages.

If a particular vulnerability is reported, we can always update manually as we did in the past for mistune in commit 4f893e8d3e0f ("docs: Switch to our own fork of sphinxcontrib-openapi").

So, what do we do here? We tell dependabot to ignore requirements.txt, but instead to focus only on the shortlist, requirements-min.txt. As it turns out, we have no way to tell it to ignore a specific file (see GitHub issue https://github.com/dependabot/dependabot-core/issues/1657), so instead we move the shortlist to a dedicated subdirectory and tell dependabot that this is the root for our requirement lists.

### CODE REVIEW

**Review by tklauser — APPROVED** [review]
Thanks for taking care of this.

**Review by joestringer — APPROVED** [review]
So what's the process from here? Dependabot rebases the `requirements_min/` and then we manually update the dependabot PR when they report a dependency bump?

**Comment by qmonnet** [comment]
> So what's the process from here? Dependabot rebases the `requirements_min/` and then we manually update the dependabot PR when they report a dependency bump?

Yes, I hope that dependabot will still be able to detect requirements-min.txt and offer updates for the components we really want. Then we'll need a manual step indeed to align requirements.txt to the new versions.

It's not ideal but I don't have a better solution in mind, receiving the updates for all the dependencies as dependabot currently does is just too much time spent verifying for not enough benefits in my opinion.

Alternatively we could also disable dependabot entirely for the Pip packages, but I thought running it on requirements-min.txt should be less noise while still bringing notifications when the “most important” packages get updates.

**Comment by joestringer** [comment]
:+1: yep that sounds reasonable. I'm not sure how much there is to those steps and whether we should perhaps create documentation about how to properly respond to dependabot PRs in that area. But maybe it's pretty obvious when dependabot suggests a PR and it fails CI. Then we know we need to take manual action to resolve the rest.

**Pull request merged**
