### PR TITLE
hubble: remove unused code

### PR DESCRIPTION
**Pull request by rolinh**
Please, see individual commits for details.

### CODE REVIEW

**Review by glibsm — CHANGES_REQUESTED** [review]
The first two commits are fine, the third one however is not just "removing unused code", it completely removes the versioning from the hubble API.

Monitor is not a great example to use because it's unversioned and was never intended to be long-lived.

I don't think we can't remove the version from the hubble package entirely.

In other words, `hubble/api/v1` should be tracking the v1 of `cilium/api/v1`

**Comment by michi-covalent** [comment]
same feedback as glib. first 2 commits look good. maybe push them first, and then we can figure out what we want to do about api versioning in a separate PR?

**Comment by Rolinh** [comment]
@glibsm @michi-covalent I reworked the last commit to just remove unused code from `pkg/hubble/api/v1` instead.

**Review by michi-covalent — APPROVED** [review]
let's roll

**Review by glibsm — APPROVED** [review]
minor nit: commit message doesn't match the body. 95% of that commit is refactoring the import alias rather than removing the unused code

**Comment by Rolinh** [comment]
test-me-please

**Comment by Rolinh** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Pull request merged**
