### PR TITLE
node: Remove permanent ARP entry when remote node is deleted

### LINKED ISSUE #10197: Remove permanent ARP entry when node is deleted
When IPsec or NodePort is enabled, we add a permanent ARP entry (`remote node IP => remote node mac addr`) upon receiving a node update event: https://github.com/cilium/cilium/blob/v1.7.0-rc4/pkg/datapath/linux/node.go#L571. The entry is needed to facilitate calls to `fib_lookup()` from the datapath.

However, we don't remove entries upon receiving `NodeDelete` events (https://github.com/cilium/cilium/blob/v1.7.0-rc4/pkg/datapath/linux/node.go#L755) which might lead to situations when a packet destined to a new node with the same IP addr as the removed node will have a wrong dst mac addr, and thus will be dropped.

### PR DESCRIPTION
**Pull request by brb**
When IPsec or NodePort is enabled, we add a permanent ARP entry (remote node IP => remote node MAC addr) upon receiving a NodeUpdate event. The entry is needed to facilitate calls to `fib_lookup()` from the datapath.

Up until now, the permanent entry was not removed when the remote node was deleted. This could lead to a problem, when a packet destined to a new node which reused the IP addr of the deleted node was dropped due to the wrong MAC addr until NodeUpdate event for the new node had been received.

This PR fixes the problem by removing obsolete ARP entries.

Tested manually.

Reviewable per commit.

Fixes #10197.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10227)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Review by aanm — CHANGES_REQUESTED** [review]
Can't this be unit tested since we have a `pkg/datapath/linux/node_test.go` file for this?

**Review by jrfastab — APPROVED** [review]
LGTM thanks for doing this.

**Comment by brb** [comment]
@aanm Can we merge this? I'm going to add the tests after I've finished my work on a major feature.

**Comment by aanm** [comment]
> @aanm Can we merge this? I'm going to add the tests after I've finished my work on a major feature.

I'll defer that decision to @joestringer.

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
@brb please file an issue to follow up on the tests just to make sure it doesn't get dropped. Manual testing of something like this is as good as no testing, it could regress at any time.

The change itself looks pretty straightforward and has relevant signoffs so LGTM.

**Comment by joestringer** [comment]
Also, I marked this as a bugfix as this seems like it could cause neighbour cache to grow unchecked if there is much node churn.

**Comment by brb** [comment]
@joestringer @aanm Created an issue for testing: https://github.com/cilium/cilium/issues/10341.

**Pull request merged**
