### PR TITLE
Return version to ldflags in Makefile.defs

### PR DESCRIPTION
**Pull request by nebril**
`-ldflags` with Cilium version was overwritten by envoy
version `-ldflags`, this commit
combines these two into one `-ldflags` argument.

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6202)

### CODE REVIEW

**Comment by nebril** [comment]
fixes #6201

**Comment by nebril** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by nebril** [comment]
test-me-please

**Review by raybejjani — CHANGES_REQUESTED** [review]
Could you make the commit message a little more descriptive? It took me a while to figure out what was different, and I'm not sure why it was a problem before (I'm guessing the second `-ldflags` overrode the first one and we lost some version information). Otherwise, looks fine to me.
Since the `GOLDFLAGS` (I keep reading it as G Old Flags :/) is set in the same set of lines, perhaps we can make that allocation once only? That might make later changes more difficult (and you might be trying to keep the order from before).

**Review by raybejjani — APPROVED** [review]

**Pull request merged**
