### PR TITLE
pkg: move types.Loadbalancer to pkg/loadbalancer

### PR DESCRIPTION
**Pull request by ianvernon**
This introduces no functional changes. Add this new package to be owned by @cilium/loadbalancer .

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5141)

### CODE REVIEW

**Review by rlenglet — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by ianvernon** [comment]
Rebased; now that #5137 is fixed, will try tests.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Forgot to rename `types` --> `loadbalancer` for some unit tests. Fixed and retesting.

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
