### PR TITLE
Update Istio GSG to istio 0.8 release

### PR DESCRIPTION
**Pull request by rlenglet**
Upgrade Envoy and Istio filters to the commits in
https://github.com/istio/proxy/tree/release-0.8
Update the generated Protobuf files.
    
Update the Vagrant box and cilium-builder Docker image to update
the Bazel cache.
    
Update the version of proxy Docker images.
Update the Envoy bootstrap file in proxy Docker images to match
the upstream API v2 bootstrap version.
    
Update the Istio version installed in the Istio GSG.

In all GSGs, create the etcd-cilium deployment in kube-system.

Add Istio injection annotations into all Istio examples.

Remove the unnecessary init policy to Kafka in Istio example.

Refactor the Istio setup to use Helm, which is the recommended
way to setup Istio.
    
Disable mTLS, since it makes the connectivity between pods
unstable in 0.8.0.
    
Fix a formatting nit in the Istio GSG.

Signed-off-by: Romain Lenglet <romain@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4415)

### CODE REVIEW

**Comment by rlenglet** [comment]
test-docs-please

**Comment by rlenglet** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
Awesome. I didn't review the protobuf updates. I assume that's just a sync.

**Comment by rlenglet** [comment]
Yes, the protobuf files were regenerated due to the updated protobuf dependency in Envoy.

**Comment by ianvernon** [comment]
Is there a specific reason this was merged without tests passing?

**Comment by tgraf** [comment]
It was marked green when I merged it

**Comment by rlenglet** [comment]
The build that was started before this PR got merged failed:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3944/execution/node/64/log/?consoleFull
```
03:34:00 K8sValidatedServicesTest
03:34:00 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:341
03:34:00   Bookinfo Demo
03:34:00   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:341
03:34:00     Tests bookinfo demo [It]
03:34:00     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:373
03:34:00 
03:34:00     Unable to connect from "reviews-v1-1217721402-6d1dz" to "ratings.default.svc.cluster.local:9080/health": --2018-06-08 03:32:41--  http://ratings.default.svc.cluster.local:9080/health
03:34:00     Resolving ratings.default.svc.cluster.local (ratings.default.svc.cluster.local)... failed: Temporary failure in name resolution.
03:34:00     wget: unable to resolve host address 'ratings.default.svc.cluster.local'
03:34:00     
03:34:00     Expected command: kubectl exec -n default reviews-v1-1217721402-6d1dz -- wget --tries=2 --connect-timeout 5 ratings.default.svc.cluster.local:9080/health 
03:34:00     To succeed, but it failed:
03:34:00     Exitcode: 4 
03:34:00     Stdout:
03:34:00      	 
03:34:00     Stderr:
03:34:00      	 --2018-06-08 03:32:41--  http://ratings.default.svc.cluster.local:9080/health
03:34:00     	 Resolving ratings.default.svc.cluster.local (ratings.default.svc.cluster.local)... failed: Temporary failure in name resolution.
03:34:00     	 wget: unable to resolve host address 'ratings.default.svc.cluster.local'
03:34:00     	 
03:34:00     
03:34:00 
03:34:00     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Services.go:381
```
[9acb0442_K8sValidatedServicesTest_Bookinfo_Demo_Tests_bookinfo_demo.zip](https://github.com/cilium/cilium/files/2086416/9acb0442_K8sValidatedServicesTest_Bookinfo_Demo_Tests_bookinfo_demo.zip)

**Comment by ianvernon** [comment]
The DNS issue is something that has consistently been hitting the CI, so it is probably not related to this PR.

**Comment by rlenglet** [comment]
That's what I thought too.

**Pull request merged**
