### PR TITLE
Add k8s test for nodeport with proxy

### PR DESCRIPTION
**Pull request by joestringer**
Add a test for nodeport that also configures traffic to flow through the proxy.

Related: #6264

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6266)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Hit https://github.com/cilium/cilium/issues/6268 , will retry..

**Comment by joestringer** [comment]
test-me-please

EDIT: Test failed as expected, when attempting to hit the nodeport:

```
STEP: Installing DNS Deployment
STEP: Deploying etcd-operator
STEP: Installing Cilium
STEP: Performing Cilium preflight check
STEP: Checking that no controllers in Cilium have failed
STEP: Checking that cilium-health status is healthy
STEP: Checking that Kubernetes services are correctly plumbed by Cilium
STEP: Checking that no controllers in Cilium have failed
STEP: Checking that cilium-health status is healthy
STEP: Checking that Kubernetes services are correctly plumbed by Cilium
STEP: Checking that the kubernetes service is correctly plumbed by Cilium
STEP: Waiting for all etcd-operator pods are ready
STEP: Checking that the kubernetes service is correctly plumbed by Cilium
STEP: Applying policy /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/l7-policy-demo.yaml
STEP: Making ten HTTP requests from "testclient-6zhvh" to "http://10.110.215.222:10080"
STEP: Making ten HTTP requests from "testclient-jm6zf" to "http://10.110.215.222:10080"
STEP: Making ten HTTP requests from "testclient-6zhvh" to "http://192.168.36.11:31458"
=== Test Finished at 2018-11-20T21:44:41Z====
===================== TEST FAILED =====================
```

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8111/testReport/junit/k8s-1/12/K8sServicesTest_Checks_service_across_nodes_with_L7_policy_K8sFoo_Tests_NodePort_with_L7_Policy/

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Test passed with PR #6269:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8113/execution/node/82/log/

```
22:32:25 • [SLOW TEST:191.513 seconds]
22:32:25 K8sServicesTest
22:32:25 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
22:32:25   Checks service across nodes
22:32:25   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
22:32:25     with L7 policy
22:32:25     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
22:32:25       K8sFoo Tests NodePort with L7 Policy
22:32:25       /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
22:32:25 ------------------------------
22:32:25 SSSSSSSScleaning up VMs started for k8s tests
22:32:25 
22:32:25 Ran 1 of 312 Specs in 196.838 seconds
22:32:25 SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 311 Skipped PASS
```

**Comment by joestringer** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
