### PR TITLE
Update kubernetes to 1.19.1 and etcd to 3.4.13

### PR DESCRIPTION
**Pull request by aanm**
```release-note
Update Kubernetes dependencies to v1.19.1 and etcd to 3.4.13
```

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Review by nebril — APPROVED** [review]

**Comment by aanm** [comment]
test-missed-k8s

**Review by christarazi — APPROVED** [review]

**Comment by aanm** [comment]
test-missed-k8s

**Pull request merged**
