### PR TITLE
test: Wait until host EP is ready (=regenerated)

### LINKED ISSUE #12511: CI: K8sServicesTest Checks fails with "Can not connect to service X from outside cluster"
```
/home/jenkins/workspace/Ginkgo-CI-Tests-k8s1.11-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Can not connect to service "http://192.168.37.11:30146" from outside cluster
Expected command: kubectl exec -n kube-system log-gatherer-rlhxl -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://192.168.37.11:30146 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Err: exit status 28
Stdout:
 	 time-> DNS: '0.000023()', Connect: '0.000000',Transfer '0.000000', total '5.001665'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Ginkgo-CI-Tests-k8s1.11-Pipeline/src/github.com/cilium/cilium/test/k8sT/Services.go:514
```

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-k8s1.11-Pipeline/727/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device/

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-k8s1.11-Pipeline/724/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device/

### PR DESCRIPTION
**Pull request by brb**
Previously (hopefully), we saw many CI flakes which were due to the
first request from outside to k8s Service failing. E.g.,

> Can not connect to service "http://192.168.37.11:30146" from outside
cluster

After some investigation it became obvious why it happened. Cilium-agent
becomes ready before the host endpoints get regenerated (e.g.,
bpf_netdev_eth0.o). This leads to old programs to handling requests
which might fail in different ways. For example the following request
failed in the K8sServicesTest Checks_N_S_loadbalancing
Tests_with_direct_routing_and_DSR suite:

 > {..., "IP":{"source":"192.168.56.13","destination":"10.0.1.105", ...,
"trace_observation_point":"TO_OVERLAY","interface":{"index":40}, ...}

The previous suite was running in the tunnel mode, so the old program
was still trying to send the packet over the tunnel which no longer
existed. This resulted in the silent drop.

Fix this by making the CI to wait after deploying Cilium until the host
EP is in the "ready" state. This should ensure that the host EP programs
have been regenerated.

Fix #12511.

### CODE REVIEW

**Comment by brb** [comment]
@joestringer Requested you to review mainly to validate the state "ready" == the endpoint has been regenerated after the startup assumption.

**Comment by brb** [comment]
/test-1.23-net-next

**Comment by brb** [comment]
/test-1.23-net-next

**Review by joestringer — APPROVED** [review]
Yep, endpoints first start in restoring state when they're restored from the filesystem, then they should transition through regenerating and become ready:

https://github.com/cilium/cilium/blob/ab7ff52820490ec4639954c82c8c031c886fc34f/pkg/endpoint/endpoint.go#L852
https://github.com/cilium/cilium/blob/ab7ff52820490ec4639954c82c8c031c886fc34f/pkg/endpoint/endpoint.go#L1273

**Comment by pchaigno** [comment]
@brb Would it be feasible to backport this to v1.10?

**Comment by brb** [comment]
@pchaigno Sure. Do you want me to do that or a tophat?

**Comment by pchaigno** [comment]
I'll take care of it and ping you if I need help.

**Pull request merged**
