### PR TITLE
[v1.7] test: Replace managed etcd test with generic etcd test

### LINKED ISSUE #13282: CI: v1.7: "K8sDatapathConfig ManagedEtcd Check connectivity with managed etcd" backport needed
[This](https://github.com/cilium/cilium/pull/11544) needs to be backported to v1.7.
The problem is also reported [here](https://github.com/cilium/cilium/issues/12777)
Failures:
https://jenkins.cilium.io/view/Cilium-v1.7/job/cilium-v1.7-standard/1887/
https://jenkins.cilium.io/view/Cilium-v1.7/job/cilium-v1.7-standard/1886/
https://jenkins.cilium.io/view/Cilium-v1.7/job/cilium-v1.7-standard/1885/

### PR DESCRIPTION
**Pull request by christarazi**
Direct backport of https://github.com/cilium/cilium/pull/11544. The first 2 commits are a backport, and other commits are direct commits (considering applying them to v1.8 & master).

Fixes: https://github.com/cilium/cilium/issues/13282

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 11544; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
test-focus K8sDatapathConfig.*Etcd

**Review by pchaigno — APPROVED** [review]

**Comment by christarazi** [comment]
test-focus K8sDatapathConfig.*Etcd

**Comment by nebril** [comment]
Looks like Cilium pods are failing because of 
```
2020-10-15T08:13:30.501124813Z level=fatal msg="Timeout while waiting for initial allocator state" subsys=allocator
```

**Comment by aanm** [comment]
@gandro do you think that failure will be fixed by https://github.com/cilium/cilium/pull/13514? or it's not even related?

**Comment by christarazi** [comment]
I am not able to reproduce this locally.

**Comment by christarazi** [comment]
test-focus K8sDatapathConfig.*Etcd

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by gandro** [comment]
> @gandro do you think that failure will be fixed by #13514? or it's not even related?

Sorry for the late response. I don't think it's related (the above timeout happens in `NewAllocator`, I don't see how that would be impacted by the checks in lookup).

**Comment by nebril** [comment]
test-missed-k8s

**Review by nebril — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Pull request merged**
