### PR TITLE
v1.14 Backports 2024-09-30

### PR DESCRIPTION
**Pull request by jibi**
* [x] #35107 (@aanm) :warning: resolved conflicts

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
35107
```

### CODE REVIEW

**Comment by jibi** [comment]
/test-backport-1.14

**Review by aanm — APPROVED** [review]
LGTM but the other PR from the PR description

**Review by christarazi — APPROVED** [review]

**Comment by sayboras** [comment]
/test-backport-1.14

**Comment by sayboras** [comment]
Push one commit to address the merge race issue between PRs (related to cilium-envoy auto upgrade)

**Review by sayboras — APPROVED** [review]

**Pull request merged**
