### PR TITLE
Cli output misc retry

### PR DESCRIPTION
**Pull request by aalemayhu**
This is the same as #2465, but opening a new pull request to trigger the tests.

### CODE REVIEW

**Comment by aanm** [comment]
test-all-ginkgo

**Comment by aanm** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by ianvernon** [comment]
Logs on Jenkins show a StackTrace like the following:

```
Unable to handle PR# 2587 for repo: cilium/cilium
java.lang.NullPointerException
	at org.kohsuke.github.GHPerson.populate(GHPerson.java:44)
	at org.kohsuke.github.GHPerson.getEmail(GHPerson.java:231)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.getAuthorEmail(GhprbPullRequest.java:791)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.<init>(GhprbPullRequest.java:139)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getPullRequest(GhprbRepository.java:361)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.onPullRequestHook(GhprbRepository.java:381)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.handlePR(GhprbTrigger.java:676)
	at org.jenkinsci.plugins.ghprb.GhprbRootAction$2.run(GhprbRootAction.java:252)
```

Same as: https://github.com/kohsuke/github-api/issues/395 .

We can try upgrading Jenkins plugins and seeing if this works, as there are a variety of updates needed for Jenkins. In the mean time, so as to not upgrade in the middle of the US workday, I can check out a copy of this branch myself and try to open a PR, as unfortunately, this seems to affect arbitrary users.

**Comment by ianvernon** [comment]
@scanf fetched your branch and opened a new PR with it here - https://github.com/cilium/cilium/pull/2589 . Sorry for the inconvenience with this :(

**Comment by aalemayhu** [comment]
@ianvernon Do you want to close this then, since #2589 is open? It looks like the builds finished. I am not following along, let me know if there is anything I can do to help.

**Comment by aalemayhu** [comment]
@tgraf This has already been reviewed in #2465, please merge when the tests pass. Thanks.

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by raybejjani — APPROVED** [review]

**Pull request merged**
