### PR TITLE
vendor: update k8s dependencies and tests to 1.21.1

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by rolinh — APPROVED** [review]

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/15097

**Review by tklauser — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-1.19-5.4

**Comment by aanm** [comment]
test-1.21-4.9

**Review by christarazi — APPROVED** [review]

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/16237

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/16237

**Pull request merged**
