### PR TITLE
pkg/kvstore: fix high-cpu usage when Cilium loses Consul connectivity

### PR DESCRIPTION
**Pull request by aanm**
Fixes: 85469b099dac ("kvstore: New kvstore abstraction API")
Signed-off-by: André Martins <andre@cilium.io>

Fixes https://github.com/cilium/cilium/issues/3466

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4888)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
got hit by "NACK"

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
@aanm is there any empirical evidence you can provide that demonstrates that this fixes the issue (i.e., CPU usage before / after fix is applied)?

**Review by tgraf — APPROVED** [review]

**Pull request merged**
