### PR TITLE
v1.14 Backports 2023-07-18

### PR DESCRIPTION
**Pull request by gandro**
* [x] #26815 (@sayboras) :warning: Minor conflicts in auto-generated Helm chart values and docs
 * [ ] #26653 (@joestringer)
 * [ ] #26655 (@joestringer)
 * [x] #26840 (@tklauser)
 * [ ] #26874 (@michi-covalent)
 * [ ] #25509 (@nvibert)
 * [x] #26869 (@gandro)
 * [ ] #26812 (@chancez)
 * [ ] #26883 (@michi-covalent)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 26815 26653 26655 26840 26874 25509 26869 26812 26883; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=26815,26653,26655,26840,26874,25509,26869,26812,26883
```

### CODE REVIEW

**Comment by gandro** [comment]
/test-backport-1.14

**Review by sayboras — APPROVED** [review]
Thanks and LGTM ✅

**Comment by gandro** [comment]
CI is failing waiting for Hubble Relay even though https://github.com/cilium/cilium/pull/26869 is part of this branch. Investigating.

**Comment by gandro** [comment]
> CI is failing waiting for Hubble Relay even though #26869 is part of this branch. Investigating.

This is due to the PR branch coming from a fork, so changes to the CI are not applied. I'll reopen this PR from `cilium/cilium`.

**Pull request closed without merging**
