### PR TITLE
Store/Restore DNS Cache state on restart

### PR DESCRIPTION
**Pull request by raybejjani**
When cilium restarts, the collection of DNS responses that were used to
generate toCIDR rules from toFQDNs need to restored. Previously, this
information was lost but is now part of each endpoint's state
information.

I ended up storing the information on each endpoint mainly because we already store/restore that information. This also allows for future per-EP handling. On the other hand, the data is only stored if the policy is regenerated. I'm not sure how to fix this, since we're trying to avoid regenerating needlessly :( The failure mode would be when a lookup repeats the same IPs, but the expiration time is further in the future. The endpoint's policy doesn't change, but the DNS data in the cache does. This might force me to try something else completely (like a globally shared BPF map that stores the DNS cache data).
*Update*: I've opted to store this data here, and I'll look into syncing the endpoint data more often in a separate PR.

The runtime test for this behaviour is in https://github.com/cilium/cilium/pull/6521 but I've tested that this makes that test pass.

#### Benchmarks
```
$ go test github.com/cilium/cilium/pkg/fqdn -check.b -check.f 'Benchmark.*JSON' -v
=== RUN   Test
PASS: cache_test.go:338: DNSCacheTestSuite.BenchmarkMarshalJSON10          50000             62956 ns/op
PASS: cache_test.go:339: DNSCacheTestSuite.BenchmarkMarshalJSON100          5000            572678 ns/op
PASS: cache_test.go:340: DNSCacheTestSuite.BenchmarkMarshalJSON1000          500           6302145 ns/op
PASS: cache_test.go:341: DNSCacheTestSuite.BenchmarkMarshalJSON10000          50          74597825 ns/op
PASS: cache_test.go:355: DNSCacheTestSuite.BenchmarkMarshalJSON1000Repeat2           500           6199934 ns/op
PASS: cache_test.go:350: DNSCacheTestSuite.BenchmarkMarshalJSON100Repeat2           5000            578313 ns/op
PASS: cache_test.go:343: DNSCacheTestSuite.BenchmarkUnmarshalJSON10        10000            172864 ns/op
PASS: cache_test.go:344: DNSCacheTestSuite.BenchmarkUnmarshalJSON100        1000           1468690 ns/op
PASS: cache_test.go:345: DNSCacheTestSuite.BenchmarkUnmarshalJSON1000        100          15734228 ns/op
PASS: cache_test.go:346: DNSCacheTestSuite.BenchmarkUnmarshalJSON10000        10         181890159 ns/op
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6563)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
Righto, this now has a test, and it passes when tested with https://github.com/cilium/cilium/pull/6521

I also added benchmarks, which aren't terribly encouraging :(
```
$ go test github.com/cilium/cilium/pkg/fqdn -check.b -check.f 'Benchmark.*JSON' -v
=== RUN   Test
PASS: cache_test.go:338: DNSCacheTestSuite.BenchmarkMarshalJSON10          50000             62956 ns/op
PASS: cache_test.go:339: DNSCacheTestSuite.BenchmarkMarshalJSON100          5000            572678 ns/op
PASS: cache_test.go:340: DNSCacheTestSuite.BenchmarkMarshalJSON1000          500           6302145 ns/op
PASS: cache_test.go:341: DNSCacheTestSuite.BenchmarkMarshalJSON10000          50          74597825 ns/op
PASS: cache_test.go:355: DNSCacheTestSuite.BenchmarkMarshalJSON1000Repeat2           500           6199934 ns/op
PASS: cache_test.go:350: DNSCacheTestSuite.BenchmarkMarshalJSON100Repeat2           5000            578313 ns/op
PASS: cache_test.go:343: DNSCacheTestSuite.BenchmarkUnmarshalJSON10        10000            172864 ns/op
PASS: cache_test.go:344: DNSCacheTestSuite.BenchmarkUnmarshalJSON100        1000           1468690 ns/op
PASS: cache_test.go:345: DNSCacheTestSuite.BenchmarkUnmarshalJSON1000        100          15734228 ns/op
PASS: cache_test.go:346: DNSCacheTestSuite.BenchmarkUnmarshalJSON10000        10         181890159 ns/op
```

**Review by eloycoto — APPROVED** [review]

**Comment by raybejjani** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
