### PR TITLE
docs: add 'endpointRoutes.enabled=true' to aws-cni

### PR DESCRIPTION
**Pull request by bmcustodio**
This is meant as a temporary workaround for #16007.

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
Do we also want to backport to v1.8?

**Review by qmonnet — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
I'm a little bit nervous that maybe we used to always automatically configure this for chaining mode and somehow we accidentally changed something so that it's not automatic any more (and also implicitly this could mean that for other chaining plugins it's still a problem), but at the same time this seems like an easy workaround for now.

:+1:

**Comment by joestringer** [comment]
If we think this is also a problem on v1.8.x, we should backport it there too so we can point to the docs and make sure folks are configuring this option.

**Comment by pchaigno** [comment]
I spoke too soon. The PR that introduced this regression for chaining mode (i.e., https://github.com/cilium/cilium/pull/15228) wasn't backported to v1.8 so we don't need to backport there either.

**Review by jrajahalme — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Pull request merged**
