### PR TITLE
lrp: Skip clusterIP service restore in service delete callback

### PR DESCRIPTION
**Pull request by aditighag**
See commit message.

### CODE REVIEW

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.* LRP" --kernel_version="net-next"

**Comment by aditighag** [comment]
Focused LRP tests, including the restore test, have passed.

**Review by Weil0ng — APPROVED** [review]

**Comment by Weil0ng** [comment]
I think this change makes the logic much more clearer, but I'm curious is the old behavior causing a bug though? I mean we restore from the svc cache, so if the svc is deleted, there should not be any entry for us to restore to even if we try?

**Comment by aditighag** [comment]
> I think this change makes the logic much more clearer, but I'm curious is the old behavior causing a bug though? I mean we restore from the svc cache, so if the svc is deleted, there should not be any entry for us to restore to even if we try?

I found this unnecessary logic being executed while reading through the code. This could potentially lead to problems if there is a race between service cache deletion and LRP manager service look up. I think the current service event callbacks handlers are synchronous, but that's likely to change in future. Regardless, it's logically incorrect?

**Comment by aditighag** [comment]
> Focused LRP tests, including the restore test, have passed.

Review is in. Marking as ready for merge.

**Comment by Weil0ng** [comment]
> I think this change makes the logic much more clearer, but I'm curious is the old behavior causing a bug though? I mean 
> I found this unnecessary logic being executed while reading through the code. This could potentially lead to problems if there is a race between service cache deletion and LRP manager service look up. I think the current service event callbacks handlers are synchronous, but that's likely to change in future. Regardless, it's logically incorrect?

Yea, totally, I'm with you there, was just curious what problem this could cause :)

**Comment by pchaigno** [comment]
@aditighag I switched this PR from `release-note/misc` to `release-note/bug`, please speak up if the original label was correct :-)

**Pull request merged**
