### PR TITLE
Jenkins: Flannel job fixes

### PR DESCRIPTION
**Pull request by eloycoto**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6841)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-flannel

**Comment by eloycoto** [comment]
test-flannel

**Comment by eloycoto** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Review by brb — APPROVED** [review]

**Comment by brb** [comment]
test-flannel

**Review by ianvernon — APPROVED** [review]

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Pull request merged**
