### PR TITLE
ingress: Set max stream duration as 0

### PR DESCRIPTION
**Pull request by sayboras**
### Description

This commit is to set maxStreamOption for both http and http2 in route
level, mainly for gRPC API.

Signed-off-by: Tam Mach <tam.mach@isovalent.com>

### Testing

Testing was done locally with hubble-ui ingress, connection drop was no longer
happening.

- [x] Conformance test was also done locally.

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]
🚢

**Comment by joestringer** [comment]
Just for those curious, what does it mean for this value to be 0 and why is it useful to configure this? Does Envoy otherwise terminate connections that live longer than some period?

**Comment by sayboras** [comment]
> Just for those curious, what does it mean for this value to be 0 and why is it useful to configure this? Does Envoy otherwise terminate connections that live longer than some period?

The max stream duration is the maximum time that a stream’s lifetime will span. If the value is 0, the stream duration managed by http connection manager can last indefinitely, kindly note that it's still bound by stream idle timeout (i.e. the idle stream will get closed eventually). Without this value configured, the stream connection will get closed every 15~ based on default value from envoy. 

This was identified during internal testing, however similar symptom can be found in this screen shot https://cilium.slack.com/archives/C02QKQDTVDX/p1650469843731669.

**Review by jrajahalme — APPROVED** [review]
Cilium uses the same setting for policy enforcement listeners by default, so LGTM :-)

**Comment by sayboras** [comment]
hit flake for test-1.23-net-next, marking ready for review

**Pull request merged**
