### PR TITLE
bpf: metrics for sock addr programs

### PR DESCRIPTION
**Pull request by borkmann**
Following up on #8375. /cc @brb 

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8382)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Are these new codes considered drop reasons, given that they return `CONNECT_PROCEED`? Might be good to update the comments in `bpf/lib/common.h` to highlight if not.

Specifically:
```
 * If reason > REASON_DECRYPT then this is a drop reason and value corresponds
￼  * to -(DROP_*)		￼  * to -(DROP_*)
```

**Comment by borkmann** [comment]
> Are these new codes considered drop reasons, given that they return `CONNECT_PROCEED`? Might be good to update the comments in `bpf/lib/common.h` to highlight if not.
> 
> Specifically:
> 
> ```
>  * If reason > REASON_DECRYPT then this is a drop reason and value corresponds
> ￼  * to -(DROP_*)		￼  * to -(DROP_*)
> ```

Thanks, will do that. They are no reason for drop at least not at this layer for the load balancer, plus e.g. recvmsg hooks don't support drop.

**Comment by borkmann** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Pull request merged**
