### PR TITLE
v1.12 Backports 2023-04-05

### PR DESCRIPTION
**Pull request by jibi**
* [x] #24715 (@aanm)
 * [x] #24570 (@romanspb80)
 * [ ] #24711 (@joestringer)
 * [x] #24723 (@jibi)
 * [x] #24681(@aditighag)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 24715 24570 24711 24723 24681; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=24715,24570,24711,24723,24681
```

see individual commits for conflicts description

### CODE REVIEW

**Comment by jibi** [comment]
@aditighag I added you here as you originally reviewed #24570. There were some minor conflicts (I described them in the commit itself), please double check I did not screw up anything with that backport :pray:

**Comment by jibi** [comment]
/test-backport-1.12

**Review by aanm — APPROVED** [review]

**Comment by jibi** [comment]
/test-backport-1.12

**Comment by aditighag** [comment]
>https://github.com/cilium/cilium/pull/24570 (@romanspb80)

Looks good, I verified the changes line-by-line. Skipped the automated changes that GH didn't load.
>https://github.com/cilium/cilium/pull/24681(@aditighag)

Looks good!

Thanks!

**Review by nathanjsweet — APPROVED** [review]

**Comment by jibi** [comment]
/test-1.20-4.9

**Pull request merged**
