### PR TITLE
v1.13 Backports 2024-03-05

### PR DESCRIPTION
**Pull request by pippolo84**
* [ ] #30462 (@saintdle)
 * [x] #30966 (@pchaigno)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30462 30966
```

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Comment by pippolo84** [comment]
/test-backport-1.13

**Review by joestringer — APPROVED** [review]

**Comment by pippolo84** [comment]
k8s-1.23-kernel-4.19 hit https://github.com/cilium/cilium/issues/30018

**Comment by pippolo84** [comment]
/test-backport-1.13

**Comment by pippolo84** [comment]
/test-1.17-4.19

**Pull request merged**
