### PR TITLE
v1.5 backport 19-04-17

### PR DESCRIPTION
**Pull request by brb**
v1.5 backports 2019-04-17

 * #7747 -- update Vagrantfiles to version 145 (@ianvernon)
 * #7734 -- cilium: Encryption overhead MTU accounting (@jrfastab)
 * #7741 -- examples: Add --enable-legacy-service=false to ConfigMap (@brb)
 * #7758 -- [k8s-upstream-test] Replace deprecated provider (@nebril)
 * #7749 -- Various masquerading fixes (@borkmann)
 * #7742 -- cli: Add flag to list legacy service BPF maps (@brb)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 7747 7734 7741 7758 7749 7742; do contrib/backporting/set-labels.py $pr done 1.5; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7762)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

Failed due to:

```
17:54:04  Bringing machine 'k8s2-1.10' up with 'virtualbox' provider...
17:54:04  ==> runtime: Box 'cilium/ubuntu' could not be found. Attempting to find and install...
17:54:04      runtime: Box Provider: virtualbox
17:54:04      runtime: Box Version: 145
17:54:04  ==> runtime: Loading metadata for box 'cilium/ubuntu'
17:54:04      runtime: URL: https://vagrantcloud.com/cilium/ubuntu
17:54:04  ==> runtime: Adding box 'cilium/ubuntu' (v145) for provider: virtualbox
17:54:04      runtime: Downloading: https://vagrantcloud.com/cilium/boxes/ubuntu/versions/145/providers/virtualbox.box
17:54:04  ==> runtime: Box download is resuming from prior download progress
17:54:04  
[K    runtime: Progress: 0% (Rate: 0*/s, Estimated time remaining: --:--:--)
[K    runtime: Progress: 0% (Rate: 0*/s, Estimated time remaining: --:--:--)
[K    runtime: Download redirected to host: s3-us-west-2.amazonaws.com
17:54:04  
[K    runtime: Progress: 100% (Rate: 1117/s, Estimated time remaining: --:--:--)
[KAn error occurred while downloading the remote file. The error
17:54:04  message, if any, is reproduced below. Please fix this error and try
17:54:04  again.
```

**Comment by brb** [comment]
test-docs-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
Build failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11678/

Unclear what happened. The build appears to have frozen?

```
17:13:06  
18:04:11  Sending interrupt signal to process
```

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Infra problem: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11689/

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by borkmann — APPROVED** [review]

**Comment by ianvernon** [comment]
NodePort test failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11691/execution/node/83/

Could be related to the SNAT changes?

**Comment by borkmann** [comment]
> NodePort test failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11691/execution/node/83/
> 
> Could be related to the SNAT changes?

For SNAT itself one would need to opt-in, which is not the case from the dump. If anything from SNAT side, it could be this fix 841153e235042b3f2fe0 as a potential candidate. From the bugtool dump, I can see that as primary addresses daemon selected both v4 and v6 from enp0s8. I presume that is correct?

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
