### PR TITLE
pkg/fqdn: Track emitted IPs in cache only

### PR DESCRIPTION
**Pull request by raybejjani**
We tracked the exact IPs we inserted into rules previously, in addition
to those in the DNS cache. This is unnecessary and, ironically, caused
more regenerations than intended. This was because the bookeeping on
previousEmittedIPs would delete the entry as part of a rule update,
which we did on each rule generation. The code is now less implicitly
circular in this regard.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6466)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
I'll make a backport of this, since it makes 1.3 a little crappy to use. The code will be very similar, but the files have been moved around.

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Review by vadorovsky — APPROVED** [review]

**Comment by tgraf** [comment]
@raybejjani @ianvernon I did not find this code in the 1.3 branch. Removing the backport label.

**Comment by raybejjani** [comment]
I have a branch with a backport, but the changes were getting bigger and bigger :/
Is the label only for backporter-hat backports? In any case, I'll mark it backport-done once I finish it.

**Pull request merged**
