### PR TITLE
docs: move star wars demo to getting started

### PR DESCRIPTION
**Pull request by yoyo-go**
Hi @lizrice and @qmonnet, I have moved the Star Wars demo to the Getting Started section per discussion in the sync meeting. Please have a look and let me know if you have any comments.

### CODE REVIEW

**Comment by lizrice** [comment]
Looking at the preview I think there's something slightly wrong with the referenced to Introduction to Cilium & Hubble 
Screenshot 2022-11-29 at 15 34 10

**Comment by joestringer** [comment]
I've converted this to draft. When you've addressed the comment above from Liz, please press the "Ready for review" button at the bottom of the page and we'll take another look.

**Comment by yoyo-go** [comment]
Hi @lizrice and @joestringer , the bug is fixed and squashed into the first commit, please let me know if you have any other comment.

**Comment by joestringer** [comment]
The CI failures do not appear to be related to these changes. I have filed https://github.com/cilium/cilium/issues/22556 to follow up why CI is failing on this PR. For now we can ignore it, since the "Documentation checks" pass and that is the main check for this section of the codebase.

**Comment by xmulligan** [comment]
@joestringer is this ready to merge then?

**Review by joestringer — APPROVED** [review]

**Pull request merged**
