### PR TITLE
.github: Bump CLI version to v0.6

### PR DESCRIPTION
**Pull request by joestringer**
Pull in the latest cilium-cli version to unblock some testing (eg ipsec).

### CODE REVIEW

**Comment by joestringer** [comment]
CI 3.0 runs were mostly successful:
https://github.com/cilium/cilium/actions/runs/800538765
https://github.com/cilium/cilium/actions/runs/800538771
https://github.com/cilium/cilium/actions/runs/800538754

Just one GKE case where I didn't update the --encryption flag correctly:
https://github.com/cilium/cilium/runs/2478719459?check_suite_focus=true

Applying this diff, will re-push & validate the GKE run: 
```
diff --git a/.github/workflows/gke.yaml b/.github/workflows/gke.yaml
index a64cf88ec9c2..3803ef895274 100644
--- a/.github/workflows/gke.yaml
+++ b/.github/workflows/gke.yaml
@@ -199,7 +199,7 @@ jobs:
       - name: Install Cilium with encryption and tunnel datapath
         run: |
           cilium install ${{ steps.vars.outputs.cilium_install_defaults }} \
-            --encryption \
+            --encryption=ipsec \
             --datapath-mode=tunnel
 
       - name: Enable Relay
```

**Comment by joestringer** [comment]
GKE run was ultimately successful but spend a long time in artifact gathering and so exceeded the 30m timeout @ https://github.com/cilium/cilium/commit/728d3a339ed6bb2dc2671e908c2db3ae5a8e0536 : https://github.com/cilium/cilium/pull/15948/checks?check_run_id=2479041189

Dropping the top commit used for testing and marking ready for review.

**Comment by joestringer** [comment]
I suggest we bump v1.10 branch to use this version too, just so it doesn't get hopelessly out of date wrt the CLI version.

**Review by aanm — APPROVED** [review]

**Comment by nbusseneau** [comment]
> I suggest we bump v1.10 branch to use this version too, just so it doesn't get hopelessly out of date wrt the CLI version.

Copy/pasting from #15944: unneeded as long as we stick with `issue_comment` and `schedule` triggers, since these always run from the default `master` branch anyway. The CI 3.0 workflows currently on 1.10 are functionally non-existent.

**Review by nbusseneau — APPROVED** [review]
Thanks, that's one thing crossed off my list ;)

**Comment by joestringer** [comment]
Seems like the test runs are hitting random flakes in the test PR: https://github.com/cilium/cilium/pull/15969, I've reached out in #testing channel to try to get some more understanding of what's going on there.

**Review by nebril — APPROVED** [review]

**Comment by joestringer** [comment]
I think this is technically good to merge, but may increase the likelihood for some of the CI 3.0 jobs to time out. Not really sure if we want to handle this in any special way or just merge it and address any flakes that might show up post-merge? @nbusseneau

**Comment by nbusseneau** [comment]
> I think this is technically good to merge, but may increase the likelihood for some of the CI 3.0 jobs to time out. Not really sure if we want to handle this in any special way or just merge it and address any flakes that might show up post-merge? @nbusseneau

Considering we are still experimenting fast, I think we should merge and see if stuff breaks.

**Pull request merged**
