### PR TITLE
v1.8 backports 2020-06-05 (2)

### PR DESCRIPTION
**Pull request by christarazi**
* #11884 -- endpoint: Implement new Invalid endpoint state (@christarazi)
 * #11923 -- doc: uniformize name when referring to Hubble Relay (@Rolinh)
 * #11919 -- doc: add "observing flows with Hubble Relay" to troubleshooting section (@Rolinh)
 * #11897 -- test/helpers: allow passing custom number of requests to helpers.Ping() (@qmonnet)
 * #11307 -- CI: fix bash complaining about "unexpected tokens" (parenthesis) (@qmonnet)
 * #11899 -- datapath: Only NOTRACK proxy return traffic going to Cilium datapath (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 11884 11923 11919 11897 11307 11899; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by christarazi** [comment]
test-backport-1.8

**Review by qmonnet — APPROVED** [review]
> #11897 -- test/helpers: allow passing custom number of requests to helpers.Ping() (@qmonnet)
#11307 -- CI: fix bash complaining about "unexpected tokens" (parenthesis) (@qmonnet)

Both look good to me :+1:

**Comment by christarazi** [comment]
retest-runtime

**Comment by christarazi** [comment]
test-focus K8sServicesTest Checks service across nodes Tests NodePort (kube-proxy) with externalTrafficPolicy=Local

**Comment by christarazi** [comment]
test-focus K8sServicesTest.*Checks service across nodes Tests NodePort (kube-proxy) with externalTrafficPolicy=Local

**Comment by christarazi** [comment]
test-focus K8sServicesTest.*Checks service across nodes Tests NodePort

**Comment by christarazi** [comment]
Focused test run successful. CI has been all green.

**Pull request merged**
