### PR TITLE
chore: Add constants for cloud APIs

### PR DESCRIPTION
**Pull request by jaffcheng**
Replace string literals for limiters and metrics
in pkg/alibabacloud, pkg/aws and pkg/azure.
This is a follow-up to #33428

### CODE REVIEW

**Comment by jaffcheng** [comment]
@doniacld

**Review by gandro — APPROVED** [review]

**Review by tommyp1ckles — APPROVED** [review]
Thanks, @cilium/azure changes look good!

**Review by christarazi — APPROVED** [review]

**Comment by jaffcheng** [comment]
Kindly ping

**Comment by tommyp1ckles** [comment]
@jaffcheng branch might be a bit stale wrt the tests passing - can you try rebasing?

**Pull request merged**
