### PR TITLE
v1.11 backports 2021-12-10

### PR DESCRIPTION
**Pull request by nbusseneau**
* #17982 -- workflows: Run CodeQL workflow is the workflow is edited (@pchaigno)
 * #17990 -- Makefile: Add kind-image target (@joestringer)
 * #18133 -- test/helpers: fix kubectl version detection for RCs (@tklauser)
 * #18123 -- docs: fix link to signoff / certificate of origin section (@timoreimann)
 * #18148 -- identity: fix incorrect maximum identity when ClusterID > 0 (@ArthurChiao)
 * #18155 -- docs: Update the minimum required Minikube version (@pchaigno)
 * #18170 -- Revert "test/Services: Quarantine 'Checks service on same node'" (@borkmann)
 * #18166 -- policy: Fix selector identity release for FQDN (@joestringer)
 * #17939 -- Fix for excess IP release race condition | handshake between agent and operator (@hemanthmalla)
 * #18117 -- test: Add Error Log Exceptions (@nathanjsweet)
 * #18167 -- Makefile: Push image in 'kind-image' target (@joestringer)
 * #18186 -- test: use stable zookeeper image (@tklauser)
 * #18200 -- .github: add parameter to allow for image suffix (@aanm)
 * #18203 -- ui: v0.8.5 (@geakstr)
 * #18209 -- install: Fix hubble-ui image references (@joestringer)
 * #18208 -- test: Use stable image tag for Graceful termination test (@aditighag)
 * #18137 -- release: Generate helm values docs (@joestringer)
 * #18217 -- Fix for data race in IP release features (@hemanthmalla)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 17982 17990 18133 18123 18148 18155 18170 18166 17939 18117 18167 18186 18200 18203 18209 18208 18137 18217; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.11

**Review by joestringer — APPROVED** [review]
LGTM for commits authored by me.

**Review by aditighag — APPROVED** [review]
Looks good for my commits. Thanks!

**Comment by aditighag** [comment]
Could you remove this backport for now - 

`pkg/endpoint: Pass endpoint alive context to regeneration tasks #18216 -- pkg/endpoint: Pass endpoint alive context to regeneration tasks (@aditighag)`

Thanks!

**Review by aditighag — CHANGES_REQUESTED** [review]
Based on previous comment, skip a backport.

**Review by aanm — APPROVED** [review]
Looks good for my commit. Thanks

**Review by tklauser — APPROVED** [review]
My changes look good, thanks.

**Review by pchaigno — APPROVED** [review]
My changes look good :pray:

**Comment by nbusseneau** [comment]
@aditighag Removed #18216 as asked, and reverted backport labels on the PR so that it gets picked up later.

**Comment by nbusseneau** [comment]
Removed assignees assigned due to wrong `CODEOWNERS` on `v1.11`: https://github.com/cilium/cilium/blob/704a6db70b02b9ed21837ee7bf2edfb85f8a602d/CODEOWNERS
Fixing in another PR.

**Review by jrajahalme — APPROVED** [review]

**Comment by nbusseneau** [comment]
/test-backport-1.11

**Comment by hemanthmalla** [comment]
@nbusseneau Can https://github.com/cilium/cilium/pull/18217 also be added in this PR ? This fixes a data race from https://github.com/cilium/cilium/pull/17939

**Comment by nbusseneau** [comment]
@hemanthmalla Since #18217 was merged after the start of this round of backports, it will be included in the next round of backports after this one is merged (hopefully tomorrow or on Wednesday 😄).

**Comment by nbusseneau** [comment]
/test-backport-1.11

**Review by nathanjsweet — APPROVED** [review]
LGTM

**Review by borkmann — APPROVED** [review]

**Review by aditighag — APPROVED** [review]
Thanks!

**Comment by aditighag** [comment]
runtime failure is legitimate - 

```
07:49:31      runtime: HINT: to fix this, run 'make -C Documentation update-helm-values'
07:49:31      runtime: Makefile:43: recipe for target 'check' failed
07:49:31      runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/Documentation'
07:49:31      runtime: make[1]: *** [check] Error 1
07:49:31      runtime: Makefile:575: recipe for target 'postcheck' failed
07:49:31      runtime: make: *** [postcheck] Error 2
```

**Comment by nbusseneau** [comment]
Both Travis CI and runtime tests hit issues due to `make -C Documentation update-helm-values` needing to be run, adding this to the PR.

**Comment by nbusseneau** [comment]
1.22 / 4.19 hit #16664.

**Comment by nbusseneau** [comment]
Runtime test passed, Travis CI hit Docker pull limits. I've retriggered Travis CI out of habit, but can be merged afterwards.

**Comment by nbusseneau** [comment]
Travis CI passed, marking as ready to merge.

**Pull request merged**
