### PR TITLE
bugtool: remove k8s-mode

### PR DESCRIPTION
**Pull request by mhofstetter**
This PR removes the k8s-mode from the bugtool.

Please take a look at the individual commits (as the command functions have also been cleaned up)

Related deprecation PR: https://github.com/cilium/cilium/pull/35689

### CODE REVIEW

**Review by derailed — APPROVED** [review]
@mhofstetter Nice work!

**Comment by mhofstetter** [comment]
rebased to `main` to pull in [a fix](https://github.com/cilium/cilium/pull/36628) for the failing ci-integration test

**Pull request merged**
