### PR TITLE
v1.14 Backports 2024-09-11

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #34609 (@sayboras)
 * [x] #34650 (@Artyop) :warning: resolved conflicts
 * [x] #34707 (@marseel) :warning: resolved conflicts
 * [x] #34711 (@marseel) :warning: resolved conflicts
 * [x] #34727 (@marseel) :warning: resolved conflicts

PRs removed due to issues:
 * #34668 (@marseel)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 34609 34650 34707 34711 34727
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
Only trivial YAML conflicts due to some other PRs not having been backported.

**Review by marseel — APPROVED** [review]

**Comment by nbusseneau** [comment]
/test-backport-1.14

**Review by Artyop — APPROVED** [review]
lgtm for #34650

**Review by aanm — APPROVED** [review]

**Comment by nbusseneau** [comment]
/test-backport-1.14

**Comment by nbusseneau** [comment]
Fixed the images wait check for stable branches since `cilium-cli` is not build off the tree in stable branches, re-running CI.

**Comment by nbusseneau** [comment]
Removed #34668 due to issues with IPsec upgrade/downgrade tests.

**Comment by nbusseneau** [comment]
/test-backport-1.14

**Review by dylandreimerink — APPROVED** [review]

**Pull request merged**
