### PR TITLE
pkg/endpoint: ignore negative time durations in metrics

### LINKED ISSUE #6183: Deadlock cause by "hidden" panics in metrics
Unfortunately is not possible to retrieve the exact cilium commit has this was tested of a branch.

```
goroutine 175044 [semacquire, 484 minutes]:
sync.runtime_SemacquireMutex(0xc42020b208, 0xfda300)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc42020b204)
	/usr/local/go/src/sync/mutex.go:134 +0x108
sync.(*RWMutex).Lock(0xc42020b204)
	/usr/local/go/src/sync/rwmutex.go:93 +0x2d
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).UnconditionalLock(0xc42020b200)
	/go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:55 +0x31
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF.func2(0xc42556daf8, 0xc42020b200, 0xc42556d920, 0xc42556d908)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:569 +0x234
panic(0x26c8cc0, 0xc425fe6ed0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cilium/cilium/vendor/github.com/prometheus/client_golang/prometheus.(*counter).Add(0xc4202da540, 0xbef4a2cf4d5aa6c0)
	/go/src/github.com/cilium/cilium/vendor/github.com/prometheus/client_golang/prometheus/counter.go:63 +0xb2
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regeneratePolicy(0xc42020b200, 0x2c0a8a0, 0xc4222f7400, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:582 +0x609
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc42020b200, 0x2c0a8a0, 0xc4222f7400, 0xc4214b7600, 0x1b, 0xc4239f9760, 0xa, 0xc425df16c0, 0x0, 0xf87200, ...)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:591 +0x19c2
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc42020b200, 0x2c0a8a0, 0xc4222f7400, 0xc425df16c0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:763 +0x7a6
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1(0xc425df16c0, 0x2c0a8a0, 0xc4222f7400, 0xc421881780, 0xc42020b200)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:842 +0x1fc
created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:820 +0x123
```

The panic above was inside the "Add" of this line: https://github.com/cilium/cilium/blob/ccd371c9acc761f0d37c045ff344f71341c91dcc/pkg/endpoint/policy.go#L584

Which was called inside this function
https://github.com/cilium/cilium/blob/ccd371c9acc761f0d37c045ff344f71341c91dcc/pkg/endpoint/policy.go#L483-L484

As we can see, the function can only be called with the endpoint mutex held, as the function panicked, the mutex was still held. Although we have a "defer" function, that defer function also wanted to Lock the endpoint. Unfortunately, the endpoint mutex was not Unlocked because of the panic, the defer is never executed and the mutex is never unlocked.

>When the function F calls panic, execution of F stops, any deferred functions in F are executed normally, and then F returns to its caller.

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

This will avoid at least panic whenever the time is negative but we will still log it.

Fixes #6183

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6214)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by ianvernon — COMMENTED** [review]
Can you add a check for this log in the CI so that we are aware of it in CI runs?

**Review by eloycoto — APPROVED** [review]

**Comment by ianvernon** [comment]
Running the tests again. The CI addition can be done as a follow-up. If the tests pass I will merge so we can avoid having this panic occur.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build hit etcd-operator scale-up issue: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7994/

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
