### PR TITLE
bpf,metrics: add line/file information to drop metrics

### LINKED ISSUE #27748: datapath: Extend METRICS_MAP to store prog ID / ifindex / LOC upon DROP_MISSED_TAIL_CALL
Currently, we get very little information when `DROP_MISSED_TAIL_CALL` happens - only the counter value is incremented (e.g., https://github.com/cilium/cilium/issues/26739).

To fix that, we could extend the `METRICS_MAP` to store prog ID, ifindex, LOC in the metrics counter which could drastically help with troubleshooting. The meta info could be rendered into prometheus metric label. `DROP_MISSED_TAIL_CALL` should be rare events, so the high cardinality of such a metric shouldn't be an issue.

### PR DESCRIPTION
**Pull request by ti-mo**
Quick summary of the changes here:

- fix shellcheck warnings in check-sources.sh
- add `__MAGIC_LINE__` macro
- move around the file->id lookup machinery and surrounding scripts
- use reserved space in metricsmap.Key to store line/file numbers of all bpf metrics
- (backport commit) prepare the metrics infrastructure for the resulting cardinality bump by summing metrics with a common prefix
- various cleanups to remove type conversions and improve legibility
- no changes to `/metrics` or `cilium-dbg metrics list` to avoid breaking users' Prometheus setups

Fixes: #27748

Example output:
```
~ cilium bpf metrics list
REASON                    DIRECTION   PACKETS   BYTES    LINE   FILE
Interface                 INGRESS     151       9368     1092   bpf_host.c
Interface                 INGRESS     731       139248   659    bpf_overlay.c
Success                   EGRESS      137       8212     1531   bpf_host.c
Success                   EGRESS      9         744      1286   bpf_lxc.c
Success                   INGRESS     11        926      86     l3.h
Success                   INGRESS     1403      299078   231    trace.h
Unsupported L3 protocol   EGRESS      6         460      1466   bpf_lxc.c
```

```
~ cilium bpf metrics list -o json
  {
    "reason": "Success",
    "direction": "egress",
    "packets": 406587,
    "bytes": 78023315,
    "line": 40,
    "file": "encap.h"
  },
  {
    "reason": "Unsupported L3 protocol",
    "direction": "egress",
    "packets": 167,
    "bytes": 12050,
    "line": 1466,
    "file": "bpf_lxc.c"
  }
```

```release-note
Add line numbers and file names to all metrics in 'cilium-dbg bpf metrics list'
```

### CODE REVIEW

**Review by learnitall — APPROVED** [review]
Looks good for API, thanks!

**Review by derailed — APPROVED** [review]
@ti-mo Nice improvement!

**Review by dylandreimerink — APPROVED** [review]

**Review by christarazi — APPROVED** [review]
ci-structure changes LGTM, do we need to consider any impact on downgrading/upgrading given that the metrics map key is structurally changing?

**Comment by ti-mo** [comment]
> ci-structure changes LGTM, do we need to consider any impact on downgrading/upgrading given that the metrics map key is structurally changing?

See individual commits, up/downgrade compat is what the majority of changes aims to deal with.

**Review by bimmlerd — APPROVED** [review]

**Review by markpash — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Pull request merged**
