### PR TITLE
egressGW: test improvements

### PR DESCRIPTION
**Pull request by julianwiedmann**
Make some robustness improvements to the EgressGW tests, so that it's easier to track down CI failures.

### CODE REVIEW

**Comment by julianwiedmann** [comment]
/test-1.25-net-next

**Comment by julianwiedmann** [comment]
/test-1.25-net-next

**Comment by julianwiedmann** [comment]
/test-1.25-net-next

**Comment by julianwiedmann** [comment]
/test-1.25-net-next

**Comment by julianwiedmann** [comment]
/test-1.25-net-next

**Comment by julianwiedmann** [comment]
/test-only --focus="K8sDatapathEgressGatewayTest.*" --k8s_version=1.25 --kernel_version=net-next

**Comment by julianwiedmann** [comment]
/test-only --focus="K8sDatapathEgressGatewayTest.*" --k8s_version=1.25 --kernel_version=net-next

**Comment by julianwiedmann** [comment]
/test-only --focus="K8sDatapathEgressGatewayTest.*" --k8s_version=1.25 --kernel_version=net-next

**Comment by julianwiedmann** [comment]
/test-only --focus="K8sDatapathEgressGatewayTest.*" --k8s_version=1.25 --kernel_version=net-next

**Review by jibi — APPROVED** [review]
Looks good, thanks for the cleanup :pray:

**Pull request merged**
