### PR TITLE
Don't emit an error message on namespace termination due to Ingress reconciliation

### PR DESCRIPTION
**Pull request by giorio94**
When a namespace containing an Ingress configured in dedicated mode gets deleted, the controller may first receive the event corresponding to the deletion of one of the dependent resources, and only afterwards of the ingress itself. Hence, it will attempt to recreate these resources (e.g., the CiliumEnvoyConfig), but fail as rejected by the k8s APIServer with an error along the lines of:

```
failed to create or update CiliumEnvoyConfig: ciliumenvoyconfigs.cilium.io \"cilium-ingress-cilium-test-ingress-service\" is  forbidden: unable to create new content in namespace cilium-test because it is being terminated
```

Let's replace this error with an informative message at lower severity, given that the situation resolves itself, and there's no actionable item for a user reading the error. This also prevents the error from being flagged by the Cilium CLI no-errors-in-logs check.

Since we don't return error to controller-runtime, the reconciliation will not be retried automatically. However, we will be woken up again once the ingress deletion event is received, so that we can proceed with the cleanup.

```release-note
Don't emit an error message on namespace termination due to Ingress reconciliation
```

### CODE REVIEW

**Comment by giorio94** [comment]
@youngnick Gentle ping :pray:

**Review by mhofstetter — APPROVED** [review]
Thanks Marco! I assume many other reconcilers behave the same way - but it's nice to handle it properly for Ingress and can reduce flakes.

I hope you don't mind that i added a unit test.

**Comment by giorio94** [comment]
> Thanks Marco! I assume many other reconcilers behave the same way - but it's nice to handle it properly for Ingress and can reduce flakes.

Yeah, I don't think this is something specific to the Ingress reconciler, others are also likely affected. Just being the one which caused flakes on a workflow I'm currently working on (when deleting the cilium-test namespace), so it seemed reasonable to address it rather than ignoring it in the check.

> 
> I hope you don't mind that i added a unit test.

Thanks!

**Comment by giorio94** [comment]
It seems that the linter is unhappy due to the test.

**Comment by mhofstetter** [comment]
> It seems that the linter is unhappy due to the test.

yep, probably due to recent changes merged into main that are pulled in by the GH checks. At least linting doesn't complain locally :/ i'll try a rebase.

> It seems that the linter is unhappy due to the test.

yep, looks like due to changes that have been merged in the [meantime](https://github.com/cilium/cilium/pull/30616) and now being pulled in by the GH checks.

I will rebase.

**Pull request merged**
