### PR TITLE
cilium: minor follow-ups on stateless nat

### PR DESCRIPTION
**Pull request by borkmann**
(see commit msgs)

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]
Looks good, thanks Daniel!

**Comment by borkmann** [comment]
/test-1.25-net-next

**Comment by borkmann** [comment]
/test-1.24-4.19

**Comment by borkmann** [comment]
/test-1.16-4.9

**Comment by borkmann** [comment]
/test-1.23-5.4

**Comment by borkmann** [comment]
/test-1.16-4.9

**Comment by borkmann** [comment]
/test-1.16-4.9

**Comment by borkmann** [comment]
/test-1.25-net-next

**Comment by borkmann** [comment]
All tests pass except unrelated TLS issue which is being investigated (happening on other PRs too).
```
 	 *   Trying 18.154.242.15...
	 * TCP_NODELAY set
	 * Connected to www.lyft.com (18.154.242.15) port 443 (#0)
	 * ALPN, offering http/1.1
	 * successfully set certificate verify locations:
	 *   CAfile: /cacert.pem
	   CApath: none
	 * TLSv1.2 (OUT), TLS handshake, Client hello (1):
	 } [512 bytes data]
	 * TLSv1.2 (IN), TLS handshake, Server hello (2):
	 { [106 bytes data]
	 * TLSv1.2 (IN), TLS handshake, Certificate (11):
	 { [4957 bytes data]
	 * TLSv1.2 (OUT), TLS alert, unknown CA (560):
	 } [2 bytes data]
	 * SSL certificate problem: unable to get local issuer certificate
	 * Closing connection 0
	 command terminated with exit code 60
```

**Pull request merged**
