### PR TITLE
Spell out the full term of the CRD acronym

### PR DESCRIPTION
**Pull request by Kikiodazie**
My change spells out the full term of the Kubernetes CRD acronym. 

I am not 100% sure if this will be helpful for readers of this "Quick Start Guide," considering their level of experience, but it is a good practice to spell out the full term of an acronym on initial use.

Signed-off-by: Divine Odazie <dodazie@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

### CODE REVIEW

**Comment by joestringer** [comment]
Hi @Kikiodazie, thanks for the PR! It looks like you added the sign-off into the PR description, but the bot needs this to be in git metadata. You can fix this up using `git commit --amend` to update the commit message in the patch, and then do a force push back to this same branch to update the PR.

**Review by qmonnet — APPROVED** [review]
Looks good, thank you! We don't often expand acronym in the doc, probably not often enough. I'm pretty sure `CRD` is used all over the place, which is mostly fine because most users should know what it is, but agreed, it's nice to have it expanded in at the beginning of the Getting Started guide.

Please add your `Signed-off-by:` to the commit description as Joe explained, and we'll be good :).

**Comment by Kikiodazie** [comment]
> Hi @Kikiodazie, thanks for the PR! It looks like you added the sign-off into the PR description, but the bot needs this to be in git metadata. You can fix this up using `git commit --amend` to update the commit message in the patch, and then do a force push back to this same branch to update the PR.

Thanks @joestringer will do that right away.

**Comment by Kikiodazie** [comment]
> Looks good, thank you! We don't often expand acronym in the doc, probably not often enough. I'm pretty sure `CRD` is used all over the place, which is mostly fine because most users should know what it is, but agreed, it's nice to have it expanded in at the beginning of the Getting Started guide.
> 
> Please add your `Signed-off-by:` to the commit description as Joe explained, and we'll be good :).

Thank you @qmonnet.

**Comment by Kikiodazie** [comment]
Done with the `Signed-off-by:` addition @joestringer @qmonnet. Thank you for the help.

**Comment by joestringer** [comment]
merged, thanks @Kikiodazie !

**Comment by Kikiodazie** [comment]
Thanks, @joestringer. Looking forward to more contributions :smile:

**Pull request merged**
