### PR TITLE
Various documentation / comments fixes and improvements

### PR DESCRIPTION
**Pull request by kaworu**
Some documentation / comments fixes I found going through the getting started guides.

### CODE REVIEW

**Comment by kAworu** [comment]
@joe responding to [your comment](https://github.com/cilium/cilium/pull/14413#discussion_r543613503) about `--tofqdns-dns-reject-response-code`:

> --tofqdns-dns-reject-response-code=nameError is a legitimate configuration so changing this line provides strictly less information to users trying to work around this issue.

I'm confused by your comment, because I feel like the patch is adding the information rather than removing it.

**Review by aanm — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by joestringer** [comment]
> I'm confused, I feel like the patch is adding the information rather than removing it.

Maybe I was missing my :coffee: yesterday, looking at the change you're completely right, I must have got the diff mixed up the wrong way around somehow. Sorry for the noise :sweat_smile:

**Review by joestringer — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
Reviews from Janitors were requested because of changes to `.gitignore` and `pkg/crypto/`. I'm tempted to assign `.gitignore` to @cilium/contributing, but I'm unsure there's a good team to which we could assign `pkg/crypto/` :thinking:  Any ideas?

**Comment by joestringer** [comment]
> Reviews from Janitors were requested because of changes to .gitignore and pkg/crypto/. I'm tempted to assign .gitignore to @cilium/contributing, but I'm unsure there's a good team to which we could assign pkg/crypto/ thinking Any ideas?

If we're constantly making changes to these areas then it may make sense to devolve ownership for that to a (new?) group but if it's rare one-off occurrences then I don't think we *have* to remove janitor from all codeowners.

**Comment by kAworu** [comment]
@pchaigno about `pkg/crypto/`, I don't think it warrant a new "crypto" team for now. Looking at the history, there is very little activity and I don't expect the certloader stuff (~80% of the code under `pkg/crypto`) to change in the near future.

In the meantime, @cilium/security could be a good fit (see for example https://github.com/cilium/cilium/pull/14279). @twpayne thoughts on this?

**Pull request merged**
