### PR TITLE
node: Encapsulate all traffic to remote nodes

### PR DESCRIPTION
**Pull request by pchaigno**
Let's see if that breaks connectivity in some configurations.

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
retest-net-next

**Comment by pchaigno** [comment]
retest-4.9

**Comment by pchaigno** [comment]
test-only --focus="K8sConformance Portmap Chaining Check connectivity-check compliance with portmap chaining" --kernel_version=49 --k8s_version=1.18

**Comment by pchaigno** [comment]
test-only --focus="K8sConformance Portmap Chaining Check connectivity-check compliance with portmap chaining" --k8s_version=1.18 --kernel_version=49

**Comment by pchaigno** [comment]
test-only --k8s_version=1.18 --focus="K8sConformance Portmap Chaining Check connectivity-check compliance with portmap chaining"  --kernel_version=49

**Comment by pchaigno** [comment]
test-only --k8s_version=1.18 --focus="K8sConformance Portmap Chaining Check connectivity-check compliance with portmap chaining" --kernel_version=4.9

**Comment by pchaigno** [comment]
retest-4.9

**Comment by brb** [comment]
Is this PR about making `host A -> pod @ host B` to communicate over a tunnel instead of being a subject to masquerading? Asking, as I have this in my TODO.

**Comment by pchaigno** [comment]
@brb Nop, this PR was just to test `pod @ host A -> host B` over a tunnel when host firewall is enabled. It's now part of #12345.

**Pull request closed without merging**
