### PR TITLE
test/l4lb, nat64x46: pass k8s api server to the standalone proxy

### PR DESCRIPTION
**Pull request by squeed**
This test deploys the standalone agent in a funny way; using the existing helm chart, but not configuring it fully. This breaks the config-resolver, which expects to be able to reach a functioning in-cluster apiserver.

So, just pass the correct apiserver to the config resolver.

Signed-off-by: Casey Callendrello <cdc@isovalent.com>

### CODE REVIEW

**Comment by squeed** [comment]
cc @pchaigno @dylandreimerink who discovered this issue.

**Comment by borkmann** [comment]
> This test deploys the standalone agent in a funny way; using the existing helm chart, but not configuring it fully. This breaks the config-resolver, which expects to be able to reach a functioning in-cluster apiserver.
> 
> So, just pass the correct apiserver to the config resolver.
> 
> Signed-off-by: Casey Callendrello [c1@caseyc.net](mailto:c1@caseyc.net)

Can't we ignore the config-resolver and just rely on what was passed via cmdline as before in this case? This should not need to communicate to an apiserver at all. (Cc @brb)

**Comment by brb** [comment]
Please hold my beer - trying to get rid of Kind/Helm in this test suite.

**Comment by squeed** [comment]
You can see a passing run with these tests here: https://github.com/cilium/cilium/actions/runs/3657902069/jobs/6182017546

(Note that this PR also includes the breakage).

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
This is a temporary workaround for the L4LB test to work with the per-node config PR so I'm merging to unblock that second PR and we can revert this change once the L4LB test is fixed.

**Pull request merged**
