### PR TITLE
cilium: encryption cleanup encryption and fix table assignment of nexthop route

### PR DESCRIPTION
**Pull request by jrfastab**
Series of cleanup to encryption code and removes nexthop specifier from out encryption route. Its not needed and will break encryption after PR #8312 by forcing ingress esp traffic to cilium_host when we expect to decrypt it first.

@tgraf says, "The nexthop route was injected into the default table instead of the table
specified. This code path was not used so far, this is a fix for a potential
future usage."

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8322)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
