### PR TITLE
k8s: update k8s to 1.19.0-rc.3

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

Provisioning of k8s upstream tests is still broken, will likely be fixed with the next rc.

### CODE REVIEW

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]
:rocket:

**Review by christarazi — APPROVED** [review]

**Comment by aanm** [comment]
All CI was green, I had to push a small change in `./contrib/vagrant/start.sh` that doesn't require to re-run the CI again.

**Pull request merged**
