### PR TITLE
Retry provisioning vagrant vms in CI

### PR DESCRIPTION
**Pull request by nebril**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8462)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Review by aanm — APPROVED** [review]
noice

**Review by aanm — CHANGES_REQUESTED** [review]
what about all other jenkinsfiles? (k8s upstream and all k8s jobs)

**Comment by nebril** [comment]
@aanm wanted to do this in follow up PR after this one is merged and tested for a day.

**Review by tgraf — APPROVED** [review]

**Pull request merged**
