### PR TITLE
Fix incompatibility issue between Egress Gateway and L7 Policy

### LINKED ISSUE #19642: Egress gateway partially incompatible with L7 policies
The egress gateway feature is partially incompatible with L7 policies: traffic will not be forwarded to a gateway if there's an L7 policy selecting the same endpoint selected by an egress gateway policy.

The specific problem is that the egress gateway logic to forward traffic to a gateway lives currently in `bpf_lxc`, right after the L7 proxy redirection, so if a packet is redirected to the L7 proxy (and then reinjected back into the stack), egress gateway will be completely skipped.

One way to fix this would be to move the egress gateway logic from `bpf_lxc` to `bpf_host`, but this is currently not a viable option as the agent is not yet able to dynamically load `bpf_host` on new network devices. This in turn would be a problem in environments such as EKS, where new ENIs are dynamically allocated to accommodate additional pod IPs.

### PR DESCRIPTION
**Pull request by ysksuzuki**
Currently packets from Pods selected by an egress gateway policy will not be forwarded to a gateway if there's an L7 policy applied to those packets. That's because we apply the egress gateway policy at bpf_lxc right after the L7 policy redirection. Therefore the Egress Gateway logic will be skipped if packets are redirected to the L7 proxy.

This PR adds the egress gateway handling code at to-netdev@bpf_host so that packets from the L7 proxy can be properly redirected to an egress gw.

Fixes: #19642

```release-note
Support Egress Gateway for endpoints that are also selected by a L7 Network Policy.
```

### CODE REVIEW

**Review by jschwinger233 — COMMENTED** [review]
My understanding is, skbs are still redirected to L7 proxy from lxc, then we will handle egress gw business at to_netdev@eth0 for proxy traffic. But this relies on routing mode doesn't it?

(I suppose egress gw is compatible with tunnel.) When tunnel is enabled with egw, L7 proxy's packets are routed to cilium_host, where the skbs are bpf_redirected to cilium_vxlan for encap. In this case, to_netdev bpf doesn't have chance to process egress gateway logic for the proxy traffic, is this the correct assumption?

**Comment by ysksuzuki** [comment]
> When tunnel is enabled with egw, L7 proxy's packets are routed to cilium_host, where the skbs are bpf_redirected to cilium_vxlan for encap. In this case, to_netdev bpf doesn't have chance to process egress gateway logic for the proxy traffic, is this the correct assumption?

Actually, that's not quite right. Since traffic leaving the cluster is not redirected to cilium_vxlan there, it should be handled at to-netdev. Regarding EgressGW, we only care traffic leaving the cluster.

**Review by julianwiedmann — APPROVED** [review]
looks great, thank you!

I polished the release note a tiny bit, and updated the release-note label. This feels more like an enhancement, and not a bugfix that we would attempt to backport.

**Review by jschwinger233 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by cdtzabra** [comment]
@julianwiedmann Since you remove the imcompatibility notice in EgressGateway documentation https://github.com/cilium/cilium/pull/32828/files/e169996613bc2cd9b6ce48df991e792401b4f3be#diff-254749e3152a2d97fdff438b3b2a1611eb7e575f1f0f665ebb534f977d5b661cL72

I guess that `--set l7Proxy=false` is not needed anymore when enabling the egressgatway and should be removed also ?

**Comment by cdtzabra** [comment]
> > @julianwiedmann Since you have removed the imcompatibility notice in EgressGateway documentation https://github.com/cilium/cilium/pull/32828/files/e169996613bc2cd9b6ce48df991e792401b4f3be#diff-254749e3152a2d97fdff438b3b2a1611eb7e575f1f0f665ebb534f977d5b661cL72
> > I guess that `--set l7Proxy=false` is not needed anymore when enabling the egressgatway and should be removed also ?
> 
> Yep! Can you please open a PR?

Here is the PR https://github.com/cilium/cilium/pull/33516

**Pull request merged**
