### PR TITLE
Endpoint build deadlock fix

### LINKED ISSUE #1772: syncWithRuntime waits forever to finish
```
goroutine 57 [semacquire, 4937 minutes]:
sync.runtime_Semacquire(0xc420b4969c)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc420b49690)
	/usr/local/go/src/sync/waitgroup.go:131 +0x72
github.com/cilium/cilium/pkg/workloads/containerd.syncWithRuntime()
	/tmp/cilium-net-build/src/github.com/cilium/cilium/pkg/workloads/containerd/watcher.go:152 +0x272
github.com/cilium/cilium/pkg/workloads/containerd.EnableEventListener.func1(0xc42032b260)
	/tmp/cilium-net-build/src/github.com/cilium/cilium/pkg/workloads/containerd/watcher.go:112 +0x39
created by github.com/cilium/cilium/pkg/workloads/containerd.EnableEventListener
	/tmp/cilium-net-build/src/github.com/cilium/cilium/pkg/workloads/containerd/watcher.go:109 +0x291
```

this stack trace was based from commit e8b46ee470b3f96657fcaf7d446b6e57cbddade0

### PR DESCRIPTION
**Pull request by aanm**
When an endpoint needed to regenerate itself, it would create a
buildRequest and send it to the owner. The owner would receive that
request, and check if there was a request for that same endpoint. If
there was a request for the same endpoint, it would deny any request for
builds for that same endpoint (daemon/daemon.go#L153)

To deny that build, the owner would send the boolean value "false"
through an unbuffered channel in the request structure. This operation
will be done while holding the d.uniqueIDMU mutex in a lock state.

If, at the same time the mutex lock is held, in the deleteEndpoint
function, it will cause a deadlock since the endpoint mutex is held in
lock state and it will need to do a RLock in the RemoveFromEndpointQueue
(daemon/daemon.go#L165).

The unbuffered channel in the request structure is never read since the
endpoint is trying to grab the lock on line pkg/endpoint/policy.go#L514.

This commit moves the request for an endpoint build to the owner only
after the endpoint lock on line pkg/endpoint/policy.go#L514 is lock and
unlocked.

Fixes #1772, #1780

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
@raybejjani can you confirm the description? Does it make sense to what we have talked offline?

**Review by raybejjani — APPROVED** [review]
Yes, I think it does overall. Looking over this again, I have a few questions, though:
- Since `QueueEndpointBuild` is called in a goroutine now, could it work without spawning another goroutine? (so, it would just do the logic directly, in the goroutine of the caller, which is the goroutine spawned in `Regenerate`). This would simplify some of the locking sequencing between various goroutines, and is close the the `RemoveFromEndpointQueue` counterpart.
- I remember agreeing with you that `RemoveFromEndpointQueue` should have a RLock but looking at it now, it feels like it should have a normal Lock. We always lock it when checking membership in the `daemon.uniqueID` map, and that requires no one else modifying the map (because we rely n the value in the map but also the existence of an ID in the map). I could be thinking of another lock, though, but your description above said RLock

**Comment by aanm** [comment]
>Yes, I think it does overall. Looking over this again, I have a few questions, though:
>
>Since QueueEndpointBuild is called in a goroutine now, could it work without spawning another goroutine? (so, it would just do the logic directly, in the goroutine of the caller, which is the goroutine spawned in Regenerate). This would simplify some of the locking sequencing between various goroutines, and is close the the RemoveFromEndpointQueue counterpart.

Good call, I've remove it
>I remember agreeing with you that RemoveFromEndpointQueue should have a RLock but looking at it now, it feels like it should have a normal Lock. We always lock it when checking membership in the daemon.uniqueID map, and that requires no one else modifying the map (because we rely n the value in the map but also the existence of an ID in the map). I could be thinking of another lock, though, but your description above said RLock

Fixed.

**Review by manalibhutiyani — APPROVED** [review]
Looks good to me!

**Pull request merged**
