### PR TITLE
Pr/v1.1 backport use separate clusters

### PR DESCRIPTION
**Pull request by jrajahalme**
v1.1 backports

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5797)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]

**Review by rlenglet — APPROVED** [review]

**Comment by jrajahalme** [comment]
Unrelated Kafka CI failure (https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/6966/).
Testing again in case this is a flake.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
`kafka-broker` pod was in crash loop backoff

**Pull request merged**
