### PR TITLE
Do not merge: Test runs for cilium-cli v0.6

### PR DESCRIPTION
**Pull request by joestringer**
This PR has the temporary GH action changes necessary to test the workflow changes in #15948.

### CODE REVIEW

**Comment by jrfastab** [comment]
@joestringer first patch looks good can we merge it? This increases the coverage on tests significantly.

**Comment by joestringer** [comment]
One random failure on GKE this time:

```
🔌 [pod-to-pod] Testing cilium-test/client2-75c9979459-mm6rq -> cilium-test/echo-other-node-86774f89b9-7mcr8:8080...
---------------------------------------------------------------------------------------------------------------------
✅ curl command "curl -w %***local_ip***:%***local_port*** -> %***remote_ip***:%***remote_port*** = %***response_code***\n --show-error --silent --fail --show-error --connect-timeout 5 --output /dev/null 10.0.0.126:8080" succeeded
❌ Unable to retrieve flows of pod "cilium-test/client2-75c9979459-mm6rq": timeout while waiting for condition, last error: no flows returned
✅ Flow validation successful for pod cilium-test/echo-other-node-86774f89b9-7mcr8 (first: 0, last: 14, matched: 3, nlog: 0)
📄 Flow logs of pod cilium-test/echo-other-node-86774f89b9-7mcr8:
✅Apr 30 22:20:29.034: cilium-test/client2-75c9979459-mm6rq:51460 -> cilium-test/echo-other-node-86774f89b9-7mcr8:8080 from-endpoint FORWARDED (TCP Flags: SYN)
❓Apr 30 22:20:29.034: cilium-test/client2-75c9979459-mm6rq:51460 -> cilium-test/echo-other-node-86774f89b9-7mcr8:8080 to-endpoint FORWARDED (TCP Flags: SYN)
✅Apr 30 22:20:29.034: cilium-test/echo-other-node-86774f89b9-7mcr8:8080 -> cilium-test/client2-75c9979459-mm6rq:51460 from-endpoint FORWARDED (TCP Flags: SYN, ACK)
❓Apr 30 22:20:29.034: cilium-test/echo-other-node-86774f89b9-7mcr8:8080 -> cilium-test/client2-75c9979459-mm6rq:51460 to-endpoint FORWARDED (TCP Flags: SYN, ACK)
❓Apr 30 22:20:29.034: cilium-test/client2-75c9979459-mm6rq:51460 -> cilium-test/echo-other-node-86774f89b9-7mcr8:8080 from-endpoint FORWARDED (TCP Flags: ACK)
❓Apr 30 22:20:29.034: cilium-test/client2-75c9979459-mm6rq:51460 -> cilium-test/echo-other-node-86774f89b9-7mcr8:8080 to-endpoint FORWARDED (TCP Flags: ACK)
❓Apr 30 22:20:29.034: cilium-test/client2-75c9979459-mm6rq:51460 -> cilium-test/echo-other-node-86774f89b9-7mcr8:8080 from-endpoint FORWARDED (TCP Flags: ACK, PSH)
❓Apr 30 22:20:29.034: cilium-test/client2-75c9979459-mm6rq:51460 -> cilium-test/echo-other-node-86774f89b9-7mcr8:8080 to-endpoint FORWARDED (TCP Flags: ACK, PSH)
❓Apr 30 22:20:29.034: cilium-test/echo-other-node-86774f89b9-7mcr8:8080 -> cilium-test/client2-75c9979459-mm6rq:51460 from-endpoint FORWARDED (TCP Flags: ACK)
❓Apr 30 22:20:29.034: cilium-test/echo-other-node-86774f89b9-7mcr8:8080 -> cilium-test/client2-75c9979459-mm6rq:51460 to-endpoint FORWARDED (TCP Flags: ACK)
❓Apr 30 22:20:29.038: cilium-test/echo-other-node-86774f89b9-7mcr8:8080 -> cilium-test/client2-75c9979459-mm6rq:51460 from-endpoint FORWARDED (TCP Flags: ACK, PSH)
❓Apr 30 22:20:29.038: cilium-test/echo-other-node-86774f89b9-7mcr8:8080 -> cilium-test/client2-75c9979459-mm6rq:51460 to-endpoint FORWARDED (TCP Flags: ACK, PSH)
❓Apr 30 22:20:29.038: cilium-test/client2-75c9979459-mm6rq:51460 -> cilium-test/echo-other-node-86774f89b9-7mcr8:8080 from-endpoint FORWARDED (TCP Flags: ACK)
❓Apr 30 22:20:29.038: cilium-test/client2-75c9979459-mm6rq:51460 -> cilium-test/echo-other-node-86774f89b9-7mcr8:8080 to-endpoint FORWARDED (TCP Flags: ACK)
✅Apr 30 22:20:29.038: cilium-test/client2-75c9979459-mm6rq:51460 -> cilium-test/echo-other-node-86774f89b9-7mcr8:8080 from-endpoint FORWARDED (TCP Flags: ACK, FIN)
❌ [pod-to-pod] cilium-test/client2-75c9979459-mm6rq (10.0.0.253) -> cilium-test/echo-other-node-86774f89b9-7mcr8 (10.0.0.126)
```

**Comment by joestringer** [comment]
@jrfastab yeah #15948 (which is the first patch only) should be good to go, the only thing I'm confused about is whether the above GKE failure is a known flake or whether it could reliably break CI runs in the tree if we merge it.

**Comment by jrfastab** [comment]
That looks like a flake to me but not one I'm aware of. I guess we could spin up a GKE cluster and run the test a few times to see if it reproduces.

**Pull request closed without merging**
