### PR TITLE
update cilium runtime image with ubuntu 18.04

### PR DESCRIPTION
**Pull request by aanm**
**Summary of changes**:

update cilium runtime image. See commits for more details

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4359)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
The previous build was the VXLAN flake, already being looked at https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3840/

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
The previous build wast the GENEVE flake https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3847/

**Comment by aanm** [comment]
policy across namespaces https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3854/ [NOT A FLAKE] the k8s setup failed

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
