### PR TITLE
ci: multi pool run tests concurrently

### PR DESCRIPTION
**Pull request by viktor-kurchenko**
Conformance multi pool IPAM workflow improved with connectivity test concurrent run to make it faster.

Connectivity tests runtime:
- without concurrent run: ~11m
- with `--test-concurrency=5`: ~4m

Workflow [run example](https://github.com/cilium/cilium/actions/runs/10046592874/job/27766376162).

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Review by christarazi — APPROVED** [review]

**Comment by gandro** [comment]
This needs to be backported as the workflow in stable branches is otherwise not compatible with the new version of the CLI. c.f. 

https://github.com/cilium/cilium/actions/runs/10188966975/job/28192481335

**Comment by viktor-kurchenko** [comment]
> This needs to be backported as the workflow in stable branches is otherwise not compatible with the new version of the CLI. c.f.

Oh, sorry my bad.
Thank you @gandro !

**Pull request merged**
