### PR TITLE
experimental: BPF reconciler for load-balancing tables

### PR DESCRIPTION
**Pull request by joamaki**
This implements the proper reconciler for the experimental load-balancing control-plane.

It's of course still work-in-progress, but is functional enough to pass connectivity tests (without L7), which
makes this a good checkpoint to upstream the implementation so more people can contribute to it.

The changes outside `pkg/loadbalancer/experimental` (that need non sig-lb review) are:
- helm option `loadBalancer.experimental`. To allow easily enabling this and for use in upcoming e2e tests.
- L3n4Addr.Bytes: method for creating the statedb/part.Map key for L3n4Addr. Basically same as L3n4Addr.Hash() but adds protocol support. I ended up not reusing Hash() as it didn't have protocol and I do not want to affect existing implementation at this point.
- datapath: Use a fake LBMap if the experimental load-balancing is enabled. This allows the code to exist side-by-side and we can flip from one implementation to another without them fighting over the BPF maps.
- testutils: Added "IsPrivileged()" method to check if we're running in a privileged test. This is used to either run tests against fake BPF maps or against real, but unpinned ones.

This can be tested locally in kind as follows:
```
# Create a kind cluster without kube-proxy.
KUBEPROXY_MODE=none make kind

#  Create custom config to enable the experimental implementation
cat > contrib/testing/kind-custom.yaml <<EOF
loadBalancer:
  experimental: true
EOF

# Build and install
make kind-image-fast kind-install-cilium-fast 

# Check table contents
kubectl exec -it -n kube-system ds/cilium -- cilium-dbg statedb experimental {frontends,backends,services}

# Reconciler health/activity
kubectl exec -it -n kube-system ds/cilium -- cilium-dbg statedb health | grep experimental
```

### CODE REVIEW

**Review by brb — APPROVED** [review]

**Comment by joamaki** [comment]
hey @tklauser and @youngnick. Lots of changes here, but I'm expecting you'd just review the `pkg/testutils` and the `Documentation` and `install/kubernetes` changes. Of course feel free to review `pkg/loadbalancer/experimental` if you're up for it :D

**Review by youngnick — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
Looks good for @cilium/ci-structure

**Pull request merged**
