### PR TITLE
Bump cilium/ubuntu-next version to 42

### PR DESCRIPTION
**Pull request by gandro**
This includes an updated version of cilium/iproute2 ([50a9b6da](https://github.com/cilium/iproute2/commit/50a9b6da3509e4caa90d27839dea707030b34347)) and bumps the net-next tree to version 5.4.

Blocks #9880.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9926)

### CODE REVIEW

**Comment by gandro** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by gandro** [comment]
Removing the `ci/net-next` label, just to see if it can pass otherwise. I have a suspicion that regular CI on `net-next` has been broken before this change.

**Comment by gandro** [comment]
test-me-please

**Comment by gandro** [comment]
So it looks like the new vagrant box passes regular CI without any problems. It just can not run the normal CI tests on net-next. Since the current ubuntu-next vagrant also fails master (see #9929), this PR will not introduce any new regressions as is.

**Pull request merged**
