### PR TITLE
test: Collect sysdump as part of artifacts

### PR DESCRIPTION
**Pull request by pchaigno**
Once we have a sysdump in the test artifacts a lot of files we collect will become duplicates. This commit however doesn't remove all those duplicate files from the test artifacts. Let's wait a bit and confirm the sysdump collection always work before cleaning things up.

The sysdump collection was tested by making a test fail on purpose. Test run: https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.16-kernel-4.19/1461/.

### CODE REVIEW

**Review by christarazi — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.16-4.19

**Comment by pchaigno** [comment]
k8s-1.26-kernel-net-next failed with known flake https://github.com/cilium/cilium/issues/25411. Other CI jobs are passing. Marking ready to merge.

**Comment by pchaigno** [comment]
Marking for backports to help debug CI flakes. We've confirmed for the past two weeks that it works in main and pull requests.

**Pull request merged**
