### PR TITLE
add missing kustomization.yaml

### PR DESCRIPTION
**Pull request by wibed**
kustomization.yaml: access custom resource definitions from within kustomization and related files via a simple url.
the simplicity makes the repository more approachable.
    
add missing kustomization.yaml at keypoints in the repository.

### CODE REVIEW

**Comment by joamaki** [comment]
What is this for and how would these files be validated in CI and thus kept up-to-date as new CRDs get added?

**Comment by wibed** [comment]
> What is this for and how would these files be validated in CI and thus kept up-to-date as new CRDs get added?
yes! 
resolves the following issue: https://github.com/cilium/cilium/issues/27000

its a first draft on adding support for kustomize cli tool, to support independent inclusion of cilium crd's

example:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cilium/cilium/pkg/k8s/apis/cilium.io/client/crds/v2 
```

would result in an error.

**Comment by wibed** [comment]
@joamaki anything new?

**Comment by joamaki** [comment]
Hey, sorry for the delay (was on vacation). Could you please write a proper commit message that explains what this is and what are and its use-cases so we have some background on why these files were added in the commit history. Could you also look into whether this file could be auto-generated and it's up-to-dateness checked in CI? Maintaining it manually will likely cause it to go out-of-sync at some point.

**Comment by wibed** [comment]
@joamaki sure thing. included a bit more explanatory message. aswell as rebased with upstream.

id love to autogenerate, yet missing any knowledge on how cilium would like to approach this.

**Comment by joamaki** [comment]
Please fix these issues:

https://github.com/cilium/cilium/actions/runs/7476628501/job/20485466814?pr=29862
```
kustomization not found in /home/runner/work/cilium/cilium/install/kubernetes/cilium/Chart.yaml.
Please update the chart to include kustomization.
make: *** [Makefile:66: lint] Error 1
make: Leaving directory '/home/runner/work/cilium/cilium/install/kubernetes'
```

https://github.com/cilium/cilium/actions/runs/7476628477/job/20485465335?pr=29862
```
  Error: ERROR:CUSTOM: Please avoid long commit subjects (max: 75, found: 116)
All done
make: *** [Makefile.bpf:69: checkpatch] Error 1
```

**Comment by ti-mo** [comment]
Pulled in an extra reviewer (for Helm) to get some more eyes on this.

@wibed Please address the issues flagged by Jussi.

**Comment by wibed** [comment]
sorry for the late reply.

wdym, there is no intention on extending the chart itself.
only to make the crd's accessible via kustomization

if you could elaborate what exactly you would expect, i certainly did not expect the runner to fail for 
there should be no infliction on the installation nor any other automated process within the repo itself.
```
kustomization not found in /home/runner/work/cilium/cilium/install/kubernetes/cilium/Chart.yaml.
Please update the chart to include kustomization.
make: *** [Makefile:66: lint] Error 1
make: Leaving directory '/home/runner/work/cilium/cilium/install/kubernetes'
```

**Comment by wibed** [comment]
dont know why travis fails on me here.

**Comment by gandro** [comment]
I believe the Travis failure is due to a flaky test. Let me restart it.

**Comment by gandro** [comment]
Travis is fine, but the Helm lint still fails with:

```
 kustomization not found in /home/runner/work/cilium/cilium/install/kubernetes/cilium/Chart.yaml.
Please update the chart to include kustomization.
```

**Comment by gandro** [comment]
I've put this back into draft while feedback is getting addressed. Feel free to mark it "ready for review" once done.

**Comment by wibed** [comment]
could you elaborate how the reference to artifact hub impacts the relevance of a kustomization yaml?

its appendage only, no files or processes where harmed during the process. the only upside is to facilitate access via githublink and not to have to resort to artifacthub references or the like

**Comment by gandro** [comment]
So it seems to me that our scripts are believing the new `kustomization.yaml` is a CRD definition and is getting confused as to why it is incomplete.

Unfortunately I do not know how artifact generation works in detail to give you actionable advice on what to do. Let's ping @cilium/sig-k8s

**Review by aanm — CHANGES_REQUESTED** [review]
Hello @wibed,

the CI is currently failing because script that performs the generation of the CRDs deletes the files and regenerates them from scratch. This is done here https://github.com/cilium/cilium/blob/d4c2b9e702afd45ddd2f0a4297d44f066453f170/Makefile#L263-L273 and the files are deleted more specifically on line 269.

Because your files are under that directory they end up being deleted as well and since they are not generated by the scripts the CI doesn't consider them as valid.

**Comment by wibed** [comment]
oof i didnt expect you to bootstrap it dynamically

**Pull request closed without merging**
