### PR TITLE
Remove deprecated tunnel option, and corresponding helm values setting

### PR DESCRIPTION
**Pull request by giorio94**
The --tunnel option was deprecated in v1.14 \[1\], and is superseded by the --routing-mode and --tunnel-protocol options.

\[1\]: https://github.com/cilium/cilium/pull/24561

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]
ty!

**Review by tklauser — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Review by ysksuzuki — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]
Looks good, thank you!

**Review by tommyp1ckles — APPROVED** [review]

**Review by viktor-kurchenko — APPROVED** [review]

**Comment by giorio94** [comment]
Reviews from all code owners are in, tests are green (except for one of the Cilium IPsec upgrade matrix entries, which is unrelated from this PR, and known to be flaky). Marking as ready to merge

**Pull request merged**
