### PR TITLE
[v1.11 backport] test: Switch target FQDN

### PR DESCRIPTION
**Pull request by nbusseneau**
Manual backport of https://github.com/cilium/cilium/pull/25571 to v1.11.

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.11

**Comment by nbusseneau** [comment]
/test-1.21-5.4

**Comment by nbusseneau** [comment]
/test-1.23-4.9

**Review by pchaigno — APPROVED** [review]

**Comment by nbusseneau** [comment]
/test-1.18-4.9

**Pull request merged**
