### PR TITLE
operator: add ccnp event watcher to cilium operator

### PR DESCRIPTION
**Pull request by fristonio**
* Add kvstore status watcher for CiliumClusterwideNetworkPolicies
similar to that of CiliumNetworkPolicies.

Signed-off-by: Deepesh Pathak <deepshpathak@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9669)

### CODE REVIEW

**Review by aanm — COMMENTED** [review]
All good, only one comment so far. Oh also I think you'll need to add RBAC for the cilium-operator

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
test-focus K8sPolicyTest K8sHealthTest

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
test-me-please - VM provisioning failed in the last test.

**Comment by fristonio** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Docs/Makefile changes LGTM.

**Comment by joestringer** [comment]
test-docs-please

**Review by gandro — APPROVED** [review]

**Pull request merged**
