### PR TITLE
v1.8: Update Go to 1.14.14

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by rolinh — APPROVED** [review]

**Comment by tklauser** [comment]
retest-gke

**Comment by tklauser** [comment]
retest-gke

**Comment by tklauser** [comment]
test-backport-1.8

**Comment by tklauser** [comment]
retest-runtime

**Comment by tklauser** [comment]
test-missed-k8s

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
Note for janitors: failed non-required tests (Cilium-Ginkgo-GKE, K8s-1.19-Kernel-4.19 , K8s-1.20-kernel-4.9) are due to the fact that the CI was initially triggered with `test-me-please` rather than `test-backport-1.8`. All 1.8 required tests passed.

**Pull request merged**
