### PR TITLE
bpf: handle VLAN before XDP meta-data in from-netdev

### PR DESCRIPTION
**Pull request by julianwiedmann**
VLAN traffic entering from-netdev@eth0 either gets dropped, or immediately handed back to the stack with CTX_ACT_OK. We then expect to process the packet a second time in from-netdev@eth0.vlanXXX.

Move this logic back to the front of from-netdev, before handling any potential meta_data that was passed up by the XDP program.

In practice this doesn't fix anything - our XDP program currently doesn't handle VLAN traffic at all, and just passes it up without setting any meta_data. So we merely clarify the intent, and restore old behaviour.

### CODE REVIEW

**Review by aspsk — APPROVED** [review]
Looks ok. But I wonder, is there a reason for this change?

**Comment by julianwiedmann** [comment]
> Looks ok. But I wonder, is there a reason for this change?

Sanity mostly - I needed to walk down that code path recently, and was worried whether we could end up accidentally taking the redirect-to-tunnel case while the VLAN header is still on. So let's clean it up, before it ends up causing us trouble later on.

**Comment by aspsk** [comment]
> So let's clean it up, before it ends up causing us trouble later on

Yes, makes sense

**Pull request merged**
