### PR TITLE
Expand Hubble-exporter with filters and field mask

### PR DESCRIPTION
**Pull request by AwesomePatrol**
Add support for filters and field mask to Hubble-exporter

This is prerequisite for implementation of #25508

```release-note
Add an option to specify a filters and field mask for hubble-exporter
```

### CODE REVIEW

**Comment by AwesomePatrol** [comment]
Do you think that I should also add new fields to config-map/command-line to configure new options of the exporter?

If yes, how should they be specified? Is JSON for raw filters ok?

**Comment by chancez** [comment]
@AwesomePatrol yes, we should add some flags for this. JSON is fine. 

And for adding to the configmap, that's also probably a good idea as well.

**Review by thorn3r — APPROVED** [review]
agent changes lgtm :+1:

**Review by asauber — APPROVED** [review]
CLI-related changes LGTM. Appreciate the clear variable names and parsing logic.

**Review by chancez — COMMENTED** [review]
Overall the approach LGTM. What do you think about adding some documentation to go with the export feature?

**Comment by AwesomePatrol** [comment]
> What do you think about adding some documentation to go with the export feature?

Sure, I can do that, but as there is a different PR relying on this can we have it done separately? Feel free to create an issue and assign it to me so that I won't forget.

**Comment by chancez** [comment]
Created https://github.com/cilium/cilium/issues/26970 since we have existing flags + the new options that all need documenting.

**Review by chancez — APPROVED** [review]

**Comment by AwesomePatrol** [comment]
I think the same tests failed again, but it is hard to tell if it may be the fault of this change or tests. Could you please take a look?

**Pull request merged**
