### PR TITLE
test: Fetch DNS proxy port from `ss -uap`

### PR DESCRIPTION
**Pull request by joestringer**
Rather than depending on the underlying iptables implementation, pull
the DNS proxy port from `ss`. This will help when the underlying
implementation changes in future.

I considered whether to instead fetch this information via `cilium status` but it's only present today if an endpoint is configured with DNS policy first, which isn't the case in the related test (it doesn't use L7 policy at all). I figure it's reasonably robust to assume there's one UDP port in use by Cilium and that one corresponds to the DNS proxy.

### CODE REVIEW

**Comment by joestringer** [comment]
test-focus "TFTP with DNS Proxy port collision"

**Review by michi-covalent — APPROVED** [review]

**Comment by joestringer** [comment]
test-focus "K8s.*TFTP with DNS Proxy port collision"

**Comment by joestringer** [comment]
test-focus K8s.*TFTP with DNS Proxy port collision

**Comment by joestringer** [comment]
Only the "TFTP with DNS Proxy port collision" test depends on this function, so if it passes, we're good. If not, it needs iteration.

**Comment by joestringer** [comment]
test-focus K8s.*TFTP with DNS Proxy port collision

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
