### PR TITLE
v1.6 backports 2019-10-15

### PR DESCRIPTION
**Pull request by gandro**
* #9129 -- Don't add route/xfrm state for internal IPs in subnet mode (@lbernail)
 * #9294 -- nat: increase retries on collisions for newer kernels (@borkmann)
 * #9386 -- small bpf nat collision walk improvements (@borkmann)
 * #9390 -- improve ct gc heuristic for nodeport (@borkmann)
 * #9392 -- manager: Wait for policy map changes to be done before waiting for the ACK (@jrajahalme)
 * #9398 -- cilium signal package cleanups and metrics (@borkmann)
 * #9408 -- docs: Fix typo in AWS ENI guide (@brb)
 * #9404 -- ENI IPAM: Fix pre-allocate in the documentation (@lbernail)
 * #9399 -- Fix hairpin flows in CNI-chaining mode (@brb)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 9129 9294 9386 9390 9392 9398 9408 9404 9399; do contrib/backporting/set-labels.py $pr done 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9416)

### CODE REVIEW

**Comment by gandro** [comment]
never-tell-me-the-odds

**Comment by gandro** [comment]
never-tell-me-the-odds

**Comment by gandro** [comment]
test-docs-please

**Comment by gandro** [comment]
never-tell-me-the-odds

**Comment by gandro** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Pull request merged**
