### PR TITLE
health-ep: use launcher to prevent defunct spawn_netns

### PR DESCRIPTION
**Pull request by nirmoy**
lots spawn_netns remains as defunct process because
child process isn't being reaped

nirmoy@c176:~> ps aux|grep spawn_netns|grep defunct|wc -l
3083

Related: #5103
Signed-off-by: Nirmoy Das <ndas@suse.de>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6219)

### CODE REVIEW

**Comment by vadorovsky** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Thanks for the fix!

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
Great fix, thanks @nirmoy

**Comment by joestringer** [comment]
@nirmoy by the way, are you able to give any more details how this ended up occurring? Is the cilium-health endpoint restarting often? Perhaps there's another bug that is triggering this behaviour.

**Comment by nirmoy** [comment]
@joestringer  I couldn't reproduce it at my will :/ It occurred on a node with 10k k8s networking policy left overnight. I tried with 10k networking policy on new k8s node, waited for an hour but didn't see that issue. I will try again with longer wait duration and update you.

**Pull request merged**
