### PR TITLE
LRP: Use hive cell infra

### PR DESCRIPTION
**Pull request by aditighag**
Use the hive cell infra for wiring up the LRP manager.

### CODE REVIEW

**Review by dylandreimerink — APPROVED** [review]
LGTM

**Comment by aditighag** [comment]
Temporarily cherry-picking this fix to run LRP tests - https://github.com/cilium/cilium/pull/30939.

**Review by ldelossa — APPROVED** [review]
LGTM

**Comment by aditighag** [comment]
Relevant tests (LRP) passed - https://github.com/cilium/cilium/actions/runs/8052355690/job/21992517240.

**Pull request merged**
