### PR TITLE
1.2 backports 2018-08-28

### PR DESCRIPTION
**Pull request by nebril**
#5388
 #5386
 #5385
 #5376
 #5375
 #5374
 #5370
 #5369
 #5357
 #5347
 #5340
 #5337
 #5328
 #5300
 #5270
 #5210

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5407)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

`21:34:50 make[1]: go-bindata: Command not found`

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
@nebril 
```
Cilium image didn't update correctly
Expected
    <string>: cilium/cilium:v1.1.4
to equal
    <string>: docker.io/cilium/cilium:v1.1.4
```

**Comment by jrfastab** [comment]
AFAIK there is no easy way to updates someone elses PR. Here is new PR https://github.com/cilium/cilium/pull/5432.

The failing issue is due to string compare in above PR I fixed with updated backport patch,

```
commit d7dc45c8ea443bdc19956c7cf3535ca53c220043
Author: Thomas Graf <thomas@cilium.io>
Date:   Mon Aug 27 11:43:20 2018 +0200

    test: 1.1.4 is required to up- and downgrade from 1.2.0
    
    [ upstream commit ec610ee45934a6d0382424aad5759ebff1c22f7f ]
    
    This avoids testing an unsupported up and downgrade path from 1.1 to 1.2.
    
    Signed-off-by: Thomas Graf <thomas@cilium.io>
    Signed-off-by: Maciej Kwiek <maciej.iai@gmail.com>
    Signed-off-by: John Fastabend <john.fastabend@gmail.com>

diff --git a/test/helpers/cons.go b/test/helpers/cons.go
index feb1c75..3bf7134 100644
--- a/test/helpers/cons.go
+++ b/test/helpers/cons.go
@@ -161,7 +161,7 @@ const (
        KubectlPolicyNameLabel      = k8sConst.PolicyLabelName
        KubectlPolicyNameSpaceLabel = k8sConst.PolicyLabelNamespace
 
-       StableImage = "cilium/cilium:v1.1.1"
+       StableImage = "cilium/cilium:v1.1.4"
 
        configMap = "ConfigMap"
        daemonSet = "DaemonSet"
```
per @aanm we can also backport https://github.com/cilium/cilium/pull/5282/commits/1dbceb75f46e681a9bc22634c3272881fe3ecf64 which would also fix the issue. I have a  slight preference to not break it in the first place and just fix up the original back ported patch. Backporting #5282 might be a good idea in general though seeing it applies easily.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
```
16:47:36 [K8s-1.11]   kube-dns was not able to get into ready state
16:47:36 [K8s-1.11]   Expected
16:47:36 [K8s-1.11]       <*errors.errorString | 0xc420441980>: {
16:47:36 [K8s-1.11]           s: "Timeout reached: timed out waiting for pods with filter -l k8s-app=kube-dns to be ready",
16:47:36 [K8s-1.11]       }
16:47:36 [K8s-1.11]   to be nil
```

**Comment by jrfastab** [comment]
PR replaced by https://github.com/cilium/cilium/pull/5432

**Pull request closed without merging**
