### PR TITLE
Final flannel adjustments and enhacements

### PR DESCRIPTION
**Pull request by aanm**
Some final adjustments and enhancements to flannel integration.

Fixes https://github.com/cilium/cilium/issues/5566

Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6883)

### CODE REVIEW

**Comment by aanm** [comment]
test-flannel

**Comment by aanm** [comment]
test-flannel

**Comment by aanm** [comment]
test-flannel

**Comment by aanm** [comment]
test-flannel

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
Some minor typos in the README that you could fix up but overall looks good. Great to see this come together.

**Pull request merged**
