### PR TITLE
Relax CT creation restriction

### PR DESCRIPTION
**Pull request by tgraf**
In latest versions, the commits reverted in this PR have been causing unwanted drops for fragmented traffic. Revert the changes until a fix has been developed.

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
This is the safest fix for this, though I suspect that only the patch for the DROP_CT_CANT_CREATE logic needs to be (un-)reverted. That said we can always go back and investigate further later on if this is blocking someone.

Note that these patches were never backport so only master should be affected.

**Comment by tgraf** [comment]
> This is the safest fix for this, though I suspect that only the patch for the DROP_CT_CANT_CREATE logic needs to be (un-)reverted. That said we can always go back and investigate further later on if this is blocking someone.
> 
> Note that these patches were never backport so only master should be affected.

Agreed, I chose the safest option for now. I'd rather test all required changes at once.

**Pull request merged**
