### PR TITLE
v1.12 Backports 2023-05-15

### PR DESCRIPTION
**Pull request by jibi**
* [x] #20236 (@joestringer)
   * had to rerun `make -C Documentation update-helm-values`
 * [ ] #25215 (@youngnick)
   * ⚠️ Dropped since it has a bug
 * [x] #25352 (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 20236 25352; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=20236,25352
```

### CODE REVIEW

**Comment by jibi** [comment]
/test-backport-1.12

**Comment by jibi** [comment]
/test-backport-1.12

**Comment by jibi** [comment]
/test-1.22-4.9

**Comment by jibi** [comment]
/test-backport-1.12

**Comment by jibi** [comment]
/test-backport-1.12

**Comment by jibi** [comment]
/test-backport-1.12

**Comment by jibi** [comment]
/test-backport-1.12

**Comment by jibi** [comment]
/test-1.24-net-next

**Review by tklauser — APPROVED** [review]
Checked both commits that they correspond to their respective upstream commit. Re-generated helm values look sound as well.

**Review by jrajahalme — APPROVED** [review]

**Comment by jrajahalme** [comment]
/ci-l4lb-1.12

**Review by joestringer — APPROVED** [review]

**Pull request merged**
