### PR TITLE
Dockerfiles: update to golang 1.12.8

### PR DESCRIPTION
**Pull request by ianvernon**
Update the following images:

* cilium-builder
* cilium-runtime

Update versions for:
* `.travis.yml`

TODO:

- [ ] Update developer VM / Ginkgo VM golang versions

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8901)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by aanm — CHANGES_REQUESTED** [review]
Please squash all commits into 1 as it should be all in for the upgrade of golang 1.12.8

**Comment by tgraf** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
@aanm done

**Review by aanm — APPROVED** [review]

**Comment by ianvernon** [comment]
Tests timed out due to waiting for `cilium-operator` to be ready: 

Example: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14342/

```
10:56:09  STEP: Waiting for cilium-operator to be ready
11:00:31  STEP: Waiting for kube-dns to be ready
```

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure checking out GitHub repo: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14378/

Ran on `jenkins-fixed-new-0` https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14378/execution/node/3/log/

**Comment by ianvernon** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Review by tgraf — APPROVED** [review]

**Pull request merged**
