### PR TITLE
v1.8 backports 2020-10-07

### PR DESCRIPTION
**Pull request by qmonnet**
* #13419 -- docs: Fix minor issues in getting started guide (@twpayne)
 * #13340 -- Add the return code CT_REOPENED for conntrack table lookup. (@lzang)
 * #13414 -- bpf: properly handle IPv4 fragmented packets in host firewall (@jibi)
 * #13408 -- contexthelpers: Fix deadlock when nobody recvs on success channel (@brb)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13419 13340 13414 13408; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Review by jibi — APPROVED** [review]
LGTM for my changes :+1:

**Comment by qmonnet** [comment]
test-backport-1.8

**Review by brb — APPROVED** [review]
LGTM for my changes, thanks.

**Review by pchaigno — APPROVED** [review]
I reviewed my code owners only (datapath and documentation).

**Review by gandro — APPROVED** [review]

**Review by twpayne — APPROVED** [review]
LGTM, thanks :)

**Comment by lzang** [comment]
LGTM for my changes, thanks!

**Review by lzang — APPROVED** [review]

**Comment by nebril** [comment]
test-1.18-4.9

**Pull request merged**
