### PR TITLE
cilium-docker: fix gatewayIPv4 assignment

### PR DESCRIPTION
**Pull request by nirmoy**
Signed-off-by: Nirmoy Das <ndas@suse.de>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4709)

### CODE REVIEW

**Review by aanm — APPROVED** [review]
@nirmoy This is a really old code. Did it fail for you to find this bug? Probably needs to be backport down to 1.0 :thinking:

**Comment by nirmoy** [comment]
@aanm no, it did not fail. I found it while reading some code around.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
