### PR TITLE
nodediscovery: add backoff to CiliumNode update retry

### LINKED ISSUE #33293: Cilium agent is unable to update CiliumNode resource at startup
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Cilium agent exits soon after being started (logs below). I located the relevant function [here](https://github.com/cilium/cilium/blob/3fc57b38abe6179ac4c8fc21dd515c038ab45226/pkg/nodediscovery/nodediscovery.go#L258). Is it possible that the loop is retrying too quickly?

If I modify the `cilium-config` ConfigMap and set `auto-create-cilium-node-resource: false`, it starts up just fine.

### Cilium Version

```
cilium-cli: v0.16.10 compiled with go1.22.4 on darwin/arm64
cilium image (default): v1.15.5
cilium image (stable): v1.15.6
cilium image (running): 1.15.5
```

### Kernel Version

```
Linux master-1 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: v1.31.0-alpha.1.43+6ac60160c5729a
Kustomize Version: v5.4.2
Server Version: v1.30.1
```

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell
time="2024-06-20T20:00:25Z" level=info msg="Creating or updating CiliumNode resource" node=master-1 subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=fatal msg="Could not create or update CiliumNode resource, despite 10 retries" subsys=nodediscovery
```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by harsimran-pabla**
Existing nodeResource is taken from either directly from APIServer or from local Cilium node store. In cases of getting nodeResource from Cilium node store, we can run into issues where API server has more upto date version of CiliumNode resource and local store is lagging behind, this will result in failure of update request.

This change adds sleep duration before retrying again to update the CiliumNode object. It will give local node store time to get in sync with APIServer.

Fixes: #33293

```release-note
Fixes startup fatal error when updating CiliumNode resource.
```

### CODE REVIEW

**Review by marseel — APPROVED** [review]
Lgtm, thanks.

**Comment by harsimran-pabla** [comment]
Removing @ldelossa review request, @marseel  reviewed on behalf of sig-agent.

**Comment by julianwiedmann** [comment]
(drive-by: this would benefit from a `release-note` that spells out the user impact of the bug. Right now the backport labels feel quite ambitious - is this fix really needed for v1.14?)

**Comment by harsimran-pabla** [comment]
Thanks @julianwiedmann, I added the release note - hopefully it is more clear description of the impact of this bug.

> is this fix really needed for v1.14?

There are users reporting this issue on 1.14, this issue can be quite impactful when users run into it. ( [ranging from just a single crash to continuous crashloop.](https://github.com/cilium/cilium/issues/33293#issuecomment-2334349797) )

I'd leave it upto the backport to make this decision. I would nominate it for backport, given the impact of this bug . And fix is not intrusive and likely will have no side-effects.

**Pull request merged**
