### PR TITLE
GH-4248: Return Annotations in CNP NodeStatus

### PR DESCRIPTION
**Pull request by ashwinp**
- sending PR on behalf of ian@cilium.io

Signed-off-by: ashwinp <ashwin@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4412)

### CODE REVIEW

**Comment by ashwinp** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3935/

Hit #3878 :(. Trying again.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
