### PR TITLE
update k8s dependencies to 1.24.13

### PR DESCRIPTION
**Pull request by aanm**
The last client-go version contains an important bug fix. See https://github.com/kubernetes/kubernetes/pull/115901 for more info.

```release-note
Fix missing delete events on informer re-lists to ensure all delete events are correctly emitted and using the latest known object state, so that all event handlers and stores always reflect the actual apiserver state as best as possible
```

### CODE REVIEW

**Comment by aanm** [comment]
/test-backport-1.12

**Review by michi-covalent — APPROVED** [review]

**Comment by aanm** [comment]
In the previous test run the only test that failed was "[K8sPolicyTest Multi-node policy test with L7 policy using connectivity-check to check datapath](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.24-kernel-net-next/759/testReport/junit/Suite-k8s-1/24/K8sPolicyTest_Multi_node_policy_test_with_L7_policy_using_connectivity_check_to_check_datapath/)"

This test has passed in the current test run [here](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.24-kernel-net-next/760/execution/node/126/log/):
```
00:31:51  • [SLOW TEST:112.098 seconds]
00:31:51  K8sPolicyTest
00:31:51  /home/jenkins/workspace/Cilium-PR-K8s-1.24-kernel-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:473
00:31:51    Multi-node policy test
00:31:51    /home/jenkins/workspace/Cilium-PR-K8s-1.24-kernel-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:473
00:31:51      with L7 policy
00:31:51      /home/jenkins/workspace/Cilium-PR-K8s-1.24-kernel-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:473
00:31:51        using connectivity-check to check datapath
00:31:51        /home/jenkins/workspace/Cilium-PR-K8s-1.24-kernel-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:527
```

We don't need to wait for the CI run to complete to merge the PR.

**Comment by michi-covalent** [comment]
i would merge this if i could 😿

**Comment by joestringer** [comment]
/ci-l4lb-1.12

**Comment by joestringer** [comment]
L4LB job is weirdly apparently marked required, but github isn't triggering it:
image

**Pull request merged**
