### PR TITLE
cilium-docker-plugin: set default CMD to /usr/bin/cilium-docker

### PR DESCRIPTION
**Pull request by aanm**
Fixes: 18eb98aaac16 ("add cilium-docker-plugin Dockerfile")
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7043)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by vadorovsky — APPROVED** [review]

**Comment by vadorovsky** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
