### PR TITLE
vendor: update netlink library

### PR DESCRIPTION
**Pull request by aanm**
This update contains the serializing empty TCA_OPTIONS that we need.

Signed-off-by: André Martins <andre@cilium.io>

Fixes https://github.com/cilium/cilium/issues/5423

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5948)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by joestringer** [comment]
Up to you whether to include in this PR or another one, but the primary intent behind https://github.com/cilium/cilium/issues/5423 is to allow us to get properly fail out when there are errors in this case, instead of logging & ignoring:

https://github.com/cilium/cilium/blob/7bd249800ad305bed17985447f55af7e05c4b32d/pkg/datapath/loader/netlink.go#L47-L56

**Review by joestringer — APPROVED** [review]
LGTM at a glance, just see my comment above in the PR.

**Comment by aanm** [comment]
@joestringer Updating the library would have been too much easy :) I'll make the change in this PR.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Pull request merged**
