### PR TITLE
test: Install Helm 3

### LINKED ISSUE #10374: CI: Tests upgrade and downgrade from a Cilium stable image to master
When running k8s CI tests locally with ginkgo, first having started the the k8s VMs with `test/vagrant-local-start.sh`:

```
K8sUpdates 
  Tests upgrade and downgrade from a Cilium stable image to master
  /Users/jarno/go/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
STEP: Deleting Cilium, CoreDNS, and etcd-operator...
STEP: Waiting for pods to be terminated..
=== Test Finished at 2020-02-27T12:22:57-08:00====
===================== TEST FAILED =====================
...
• Failure [281.629 seconds]
K8sUpdates
/Users/jarno/go/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
  Tests upgrade and downgrade from a Cilium stable image to master [It]
  /Users/jarno/go/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430

  Unable to install helm repository
  Expected command: helm repo add cilium https://helm.cilium.io 
  To succeed, but it failed:
  Exitcode: 1 
  Stdout:
   	 
  Stderr:
   	 Error: Couldn't load repositories file (/home/vagrant/.helm/repository/repositories.yaml).
  	 You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
```

Also:
```
$ git grep HELM_VERSION
test/provision/k8s_install.sh:export HELM_VERSION="2.14.2"
```

This is confusing as Documentation now expects helm 3:
```
Documentation/gettingstarted/k8s-install-download-release.rst:`Install Helm`_ version 3.0.0 or higher to prepare generating the deployment
```

This was from a local CI, so no packaged artifacts.

### PR DESCRIPTION
**Pull request by jrajahalme**
Install Helm 3 instead of Helm 2. Use the "cilium-dev" image also for preflight as "cilium" image is not available for the local build.

Fixes: #10374

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10378)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Review by aanm — CHANGES_REQUESTED** [review]
@jrajahalme the upgrade guide should reflect the steps executed in the upgrade guide here: https://docs.cilium.io/en/v1.7/install/upgrade/ we require helm 3 to installed in order for the upgrade guide to be successful.

**Comment by jrajahalme** [comment]
@aanm If Helm 3 is required, then why we insist on installing Helm 2 in `test/provision/k8s_install.sh`:
```
export HELM_VERSION="2.14.2"
```

**Comment by jrajahalme** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Pull request merged**
