### PR TITLE
v1.9 backports 2020-11-06

### PR DESCRIPTION
**Pull request by joestringer**
* #13840 -- test: Additional info to debug fromCIDR+toPorts flake (@pchaigno)
 * #13927 -- test/bpf: Fix XDP loading in verifier-test.sh (@pchaigno)
 * #13907 -- operator: increase GC Rate limit of identities to 2500 per minute (@aanm)
 * #13911 -- add missing '| quote' for disableEnvoyVersionCheck (@rkage)
 * #13854 -- k8s: Optimize CRD controller to avoid using Table (@christarazi)
 * #13886 -- fqdn: Add a nil check for security id lookup (@aditighag)
 * #13921 -- bpf: fix disable PolicyVerdictNotification broken (@ArthurChiao)
 * #13914 -- fqdn: keep IPs alive if their name is alive (@kkourt)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13840 13927 13907 13911 13854 13886 13921 13914; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by joestringer** [comment]
test-backport-1.9

**Review by aditighag — APPROVED** [review]
:+1: for my change

**Review by aanm — APPROVED** [review]
looks good for my commit

**Review by kkourt — APPROVED** [review]
My commit looks good.

**Review by pchaigno — APPROVED** [review]
:+1: for my PRs.

**Comment by aanm** [comment]
retest-runtime

**Comment by aanm** [comment]
K8s-1.19-kernel-4.9 is an obvious flake, re-triggered runtime to see if it is a flake or a failure.

**Pull request merged**
