### PR TITLE
chore(misspell): To enable misspell linter for go codes

### PR DESCRIPTION
**Pull request by sayboras**
Inspired by recent PRs:
- https://github.com/cilium/cilium/pull/12394
- https://github.com/cilium/cilium/pull/12488

Signed-off-by: Tam Mach <sayboras@yahoo.com>

```release-note
chore(misspell): To enable misspell linter for go codes
```

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Review by christarazi — APPROVED** [review]
:tada:

**Comment by sayboras** [comment]
Runtime 4.9 failed due to below reason, I can't replicate in local vagrant box though :(

```
[2020-07-10T15:39:53.147Z]   	 START: proxy_test.go:370: DNSProxyTestSuite.TestRespondMixedCaseInRequestResponse
[2020-07-10T15:39:53.147Z]   	 proxy_test.go:393:
[2020-07-10T15:39:53.147Z]   	     c.Assert(err, IsNil, Commentf("DNS request from test client failed when it should succeed"))
[2020-07-10T15:39:53.147Z]   	 ... value *net.OpError = &net.OpError{Op:"read", Net:"tcp", Source:(*net.TCPAddr)(0xc00041d710), Addr:(*net.TCPAddr)(0xc00041d740), Err:(*poll.TimeoutError)(0x2f2eae0)} ("read tcp [::1]:59548->[::1]:46443: i/o timeout")
[2020-07-10T15:39:53.147Z]   	 ... DNS request from test client failed when it should succeed
[2020-07-10T15:39:53.147Z]   	 
[2020-07-10T15:39:53.147Z]   	 START: proxy_test.go:219: DNSProxyTestSuite.TearDownTest
[2020-07-10T15:39:53.147Z]   	 PASS: proxy_test.go:219: DNSProxyTestSuite.TearDownTest	0.000s
```

**Comment by pchaigno** [comment]
retest-runtime

**Comment by sayboras** [comment]
> Previous Runtime build flaked. I filed #12507 for it.

Thanks a lot for your help @pchaigno. Re-run seems ok now :tada:

**Review by vadorovsky — APPROVED** [review]

**Review by nebril — APPROVED** [review]
Good stuff!

**Review by qmonnet — APPROVED** [review]

**Pull request merged**
