### PR TITLE
go.mod, vendor: update vishvananda/netlink to latest

### PR DESCRIPTION
**Pull request by tklauser**
This pulls in a few fixes (namely https://github.com/vishvananda/netlink/pull/917) which avoids building the netlink package on non-linux platforms, simplifying its use for cross-platform builds e.g. in cilium-cli which transitively (through cilium/cilium) vendors the netlink package.

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Ah nice, I abandoned one pr in this upstream repo :heavy_check_mark:

**Comment by tklauser** [comment]
> Ah nice, I abandoned one pr in this upstream repo ✔️

Oh, I forgot about that one. I guess this followed more or less the same approach my upstream PR did.

**Review by michi-covalent — APPROVED** [review]
🥰

**Pull request merged**
