### PR TITLE
Documentation: Add `--set cni.exclusive=false` for Azure Chain Mode

### PR DESCRIPTION
**Pull request by Mais316**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #issue-number

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Hi @Mais316 thanks for the PR.

I don't have context here, why is `cni.exclusive=false` required in Azure chain mode?

If you could write a little explanation in the commit message, that would be great. Also, please squash the two commits together and force push, so that the git history is clean (you can use `git rebase -i HEAD~2` for this).

**Comment by Mais316** [comment]
@lambdanis my ref is https://github.com/cilium/cilium/pull/23159 so azure needs to follow same logic and in chain mode azure cni should be the main owner of /etc/cni/net.d not cilium.

**Comment by joestringer** [comment]
@Mais316 thanks for the PR! Can you please rebase and squash all the commits together into one, with just your patch + signoff, then force push the branch? The bots are getting confused with the merge commits.

Also useful to know that Cilium is a very fast-moving project, so your branch will be marked as "out-of-date with the base branch" by GitHub almost all the time. You don't need to keep this updated all the time. In future if you have a longer-lived PR, rebasing about once a week is the best policy. 

Once you have squashed the PR, we can trigger the tests and further review.

I would also suggest integrating your response to @lambdanis into the git commit message and PR description, so that others can better understand the motivation for the change.

**Comment by Mais316** [comment]
@joestringer will close this one and open a new one then.

**Comment by Mais316** [comment]
new PR https://github.com/cilium/cilium/pull/33708

**Comment by joestringer** [comment]
There's no need to close the PR, force-pushing the branch will replace the implementation. But sure let's move to #33708.

**Pull request closed without merging**
