### PR TITLE
Removes CEP subresource.

### LINKED ISSUE #15153: Removing CEP status subresource
## Proposal / RFE

**Is your feature request related to a problem?**
Ciliumendpoints object update seems to put some scalability limitations. Each CEP today requires at least 1 CREATE and 1 UPDATE request to k8s api-server. Given that all CEPs are watched by all Cilium-agents, this translates to `2*#Nodes` watch event per CEP even if they are completely static (no updates after creation). In an environment with lots of nodes and some amount of pod churn, this alone can overload api-server.

With our test on GKE, for 1k node with a pod churn rate of 30, we observe for each CEP, 1 CREATE and 2 UPDATE requests (one that updates the status to `wait-for-identity`, the other to `ready`). The watch event is estimated to be roughly 90k/s in this case, which would overwhelm a `n1-standard-96` master.

**Describe the solution you'd like**
We'd like to trim down the CEP updates by removing the status subresource completely and only create CEP when all required info is gathered (IP, identity, etc.). This should allow us to scale better in short-term.

### PR DESCRIPTION
**Pull request by Weil0ng**
This is part 2/2 of trimmming CEP subresource to improve scalability.
Part 1/2 is PR #15230.

This will bump cilium CRD schema version and is only backward-compatible
with agent that has part 1/2.

Signed-off-by: Weilong Cui <cuiwl@google.com>

Fixes: #15153

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by Weil0ng** [comment]
@aanm, as we discussed this should NOT go into 1.10, we need users to upgrade to part 1 first with 1.10, is there a way to do that except for manual monitoring?

**Review by christarazi — APPROVED** [review]
LGTM. In terms of signaling that this PR should only be merged after the release, we have a label for that. Applying.

**Comment by Weil0ng** [comment]
CI should be fixed by PR #15731, will rebase once that is merged.

**Comment by Weil0ng** [comment]
test-me-please

**Comment by Weil0ng** [comment]
retest-net-next

**Comment by Weil0ng** [comment]
test-only --focus="K8sServicesTest.*Checks service across nodes Tests NodePort BPF Tests with direct routing Tests LoadBalancer" --kernel_version=net-next

**Comment by Weil0ng** [comment]
Rebased with current master

**Comment by aanm** [comment]
test-me-please

**Comment by Weil0ng** [comment]
Shall we remove `dont-merge/wait-until-release` since 1.10 is released now :)

**Comment by aanm** [comment]
@Weil0ng can you rebase against master so that we can run a full CI in this PR?

**Comment by Weil0ng** [comment]
test-me-please

**Comment by aanm** [comment]
test-1.21-4.9

**Comment by aanm** [comment]
test-1.21-4.9

**Comment by aanm** [comment]
The failure hit a flake that was fixed by https://github.com/cilium/cilium/pull/16381 so merging.

**Pull request merged**
