### PR TITLE
v1.12 Backports 2023-05-22

### PR DESCRIPTION
**Pull request by tklauser**
* [x] #25323 (@tommyp1ckles)
 * [ ] #25278 (@akhilles)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 25323 25278; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=25323,25278
```

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
The hostfw PR looks good to me. Thanks!

**Comment by tklauser** [comment]
/test-backport-1.12

**Comment by tklauser** [comment]
/ci-multicluster-1.12

**Comment by tklauser** [comment]
/ci-l4lb-1.12

**Comment by tklauser** [comment]
/ci-awscni-1.12

**Comment by tklauser** [comment]
/ci-aks-1.12

**Comment by tklauser** [comment]
/ci-eks-1.12

**Comment by tklauser** [comment]
/ci-gke-1.12

**Pull request merged**
