### PR TITLE
v1.8 backports 2021-02-17

### PR DESCRIPTION
**Pull request by gandro**
* #14991 -- Fix ENI compatibility regression between 1.7 <-> 1.8 (@tgraf)
 * ~#14999 -- cilium: encryption fix, ipv4-pod-subnets without encryptnode fails (@jrfastab)~
 * #14994 -- iptables: Skip CILIUM_TRANSIENT_FORWARD for IPv6 (@pchaigno)
 * #14995 -- bpf: Enable monitor aggregation in complexity tests (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14991 14994 14995; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by gandro** [comment]
@pchaigno I had to resolve some conflicts for https://github.com/cilium/cilium/pull/14995/commits/d9df6d4766a463a3c3a36c76626cc432e302a532 

Notably, this section here seems absent in 1.8, so I did skipped it in the backport as well:
https://github.com/cilium/cilium/blob/40e6cebd251616e19df4fd0ee3430caf14b637c5/bpf/Makefile#L91-L95

**Comment by pchaigno** [comment]
> Notably, this section here seems absent in 1.8, so I did skipped it in the backport as well:

That was the right call :+1: These features were introduced in Cilium v1.9.

**Review by pchaigno — APPROVED** [review]
My changes look good :+1:

**Comment by gandro** [comment]
test-backport-1.8

**Comment by gandro** [comment]
retest-1.12-4.9

**Comment by joestringer** [comment]
I discussed #14999 with @jrfastab out of band, there's an issue with it so we should remove the backport. I'll do so shortly.

**Comment by joestringer** [comment]
The CI was otherwise green before removing the commits from #14999, so good to merge.

**Pull request merged**
