### PR TITLE
cilium, bpf: replace join endpoint script with loader package

### PR DESCRIPTION
**Pull request by aalemayhu**
This is a skeleton package, which will be extended or rewritten later.
We are moving away from invoking scripts to a more programmatic
approach.  This patch still invokes the commands but wraps it all in Go.
This will make it easier to fully replace the init / setup script.

From discussions with Daniel, the next thing is to get the iproute2 code
accessible via cgo or swig. If something like that works we can call tc,
bpf and related functions directly from Go. Then the needed calls are
compiled in and the iproute2 version dependency can be dropped.

Maybe too much work, but it would be nice if we also had a option to use
LLVM apis instead of clang and llc execs for the container case where we
can decide which version is being shipped.

Related: #1711 (evaluate vishvananda/netlink for replacing iproute2 usage)
Related: #1600 (Go native interaction with the kernel)

Signed-off-by: Alexander Alemayhu <alexander@alemayhu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/2411)

### CODE REVIEW

**Comment by aalemayhu** [comment]
Build 1 failure looks legitimate, https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-2411/1/execution/node/35/log/
```
18:10:11 ==> cilium-master-build-PR-2411-1-envoy: Starting test 999-deadlock-check.sh
18:10:11 ==> cilium-master-build-PR-2411-1-envoy: ----- 999-deadlock-check.sh: main: Checking for deadlocks in cilium service log
18:10:11 ==> cilium-master-build-PR-2411-1-envoy: ------------------------------------------------------------------------
18:10:11 ==> cilium-master-build-PR-2411-1-envoy:                             Test Failed
18:10:11 ==> cilium-master-build-PR-2411-1-envoy: Deadlock during test run detected, check the log above for context
18:10:11 ==> cilium-master-build-PR-2411-1-envoy: 
18:10:11 ==> cilium-master-build-PR-2411-1-envoy: ------------------------------------------------------------------------
```

Build 2 looks like a flake with the git checkout, https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-2411/2/execution/node/14/log/
```
Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
```

Build 3 also seems to be a git flake, https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-2411/3/console
```
hudson.plugins.git.GitException: Command "git checkout -f 6b610235bdd858f85666d361bce053f653259dcc" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: 6b610235bdd858f85666d361bce053f653259dcc

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1970)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$800(CliGitAPIImpl.java:71)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2269)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:208)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:360)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
[...]
```
Build 4 looks like a timeout in 10-proxy, https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-2411/4/execution/node/34/log/
```
19:22:24 ==> cilium-master-build-PR-2411-4: ----- 10-proxy.sh: main/policy_single_ingress/policy_import_and_wait: importing policy - and waiting up to 120 seconds to complete
19:22:24 ==> cilium-master-build-PR-2411-4: Error: cannot list endpoints: Get http:///var/run/cilium/cilium.sock/v1beta/endpoint: dial unix /var/run/cilium/cilium.sock: connect: connection refused
19:22:24 ==> cilium-master-build-PR-2411-4: Is the agent running?
19:22:25 ==> cilium-master-build-PR-2411-4: ----- 10-proxy.sh: main/policy_single_ingress/finish_test/gather_files: gathering files for test 10-proxy in test suite runtime-tests
19:22:25 ==> cilium-master-build-PR-2411-4: Error: cannot get endpoint list: Get http:///var/run/cilium/cilium.sock/v1beta/endpoint: dial unix /var/run/cilium/cilium.sock: connect: connection refused
19:22:25 ==> cilium-master-build-PR-2411-4: Is the agent running?
19:22:25 ==> cilium-master-build-PR-2411-4: Error: cannot get endpoint list: Get http:///var/run/cilium/cilium.sock/v1beta/endpoint: dial unix /var/run/cilium/cilium.sock: connect: connection refused
```

**Comment by aalemayhu** [comment]
The queue is empty on Jenkins, will trigger 5 more builds to catch test flakes.

**Comment by aalemayhu** [comment]
Build 7 failed in 16-cidr-ingress-policy.sh, https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-2411/7/execution/node/34/log/?consoleFull
```
10:30:49 ==> cilium-master-build-PR-2411-7: ----- 16-cidr-ingress-policy.sh: main/monitor_clear: clearing monitor
10:30:49 ==> cilium-master-build-PR-2411-7: ----- 16-cidr-ingress-policy.sh: main: pinging service1 from service2 (should work)
10:30:50 ==> cilium-master-build-PR-2411-7: PING service1-instance1 (10.11.193.100) 56(84) bytes of data.
10:31:13 ==> cilium-master-build-PR-2411-7: 
10:31:13 ==> cilium-master-build-PR-2411-7: --- service1-instance1 ping statistics ---
10:31:13 ==> cilium-master-build-PR-2411-7: 14 packets transmitted, 0 received, 100% packet loss, time 13317ms
10:31:14 ==> cilium-master-build-PR-2411-7: ------------------------------------------------------------------------
10:31:14 ==> cilium-master-build-PR-2411-7:                             Test Failed
10:31:14 ==> cilium-master-build-PR-2411-7: Error: Could not ping service1-instance1 from service2
10:31:14 ==> cilium-master-build-PR-2411-7: 
10:31:14 ==> cilium-master-build-PR-2411-7: ------------------------------------------------------------------------

```

**Comment by aalemayhu** [comment]
Removed the review tags. Suspect there are multiple issues, 1) the endpoint regeneration might be slower now and causes some timeout. 2) there is a hidden crash occurring in some of the runs. Will look into both.

**Review by aalemayhu — COMMENTED** [review]
Hmm, I thought that there was something wrong with the pull request after seeing the flakes, but to be honest. Have no idea why the tests are sporadic failing. Out of 34 local runs, 6 fail and it's mostly in `10-proxy.sh` but also seen in ` 11-getting-started.sh`, `999-deadlock-check.sh` and `07-kafka`.

**Review by vadorovsky — COMMENTED** [review]
Looks very promising. I hope that the test flakes will be not very hard to fix.

What are your feelings about keeping the programmatic approach even more and considering using https://github.com/iovisor/gobpf for loading BPF programs? Of course it's just an idea, which may be considered in the late future.

**Comment by joestringer** [comment]
Archiving as there is no active work on this PR.

**Pull request closed without merging**
