### PR TITLE
pkg/rate: Make parsing of positive values more strict

### PR DESCRIPTION
**Pull request by twpayne**
This fixes issues identified by CodeQL where strings were parsed as
unsigned integers and then converted to integers without a bounds check.

Refs #14514 

Signed-off-by: Tom Payne <tom@isovalent.com>

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]

**Comment by twpayne** [comment]
test-me-please

**Comment by twpayne** [comment]
retest-net-next

**Comment by twpayne** [comment]
test-gke

**Comment by twpayne** [comment]
The Cilium-Ginkgo-GKE check is currently failing with messages like:

```
15:00:27  ERROR: (gcloud.container.clusters.delete) Some requests did not succeed:
15:00:27   - ResponseError: code=400, message=Operation operation-1610373623343-d02f397d is currently operating on cluster cilium-ci-21. Please wait and try again once it is done.
```

This seems unrelated to the changes in this PR.

**Comment by twpayne** [comment]
retest-gke

**Comment by twpayne** [comment]
retest-gke

**Pull request merged**
