### PR TITLE
Backport/1.1/2018 08 12

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5176)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
Failure in BPF compilation:

```
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="Command execution failed" cmd="/var/lib/cilium/bpf/join_ep.sh /var/lib/cilium/bpf /var/run/cilium/state /var/run/cilium/state/61535_next lxc8b7c8 true 61535" containerID=692be4be69 endpointID=61535 error="exit status 1" ipv4=10.15.175.61 ipv6="f00d::a0f:0:0:f05f" k8sPodName=":" policyRevision=12
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="Join EP id=/var/run/cilium/state/61535_next ifname=lxc8b7c8"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="kernel version:  Linux runtime 4.9.17-040917-generic #201703220831 SMP Wed Mar 22 12:33:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="clang version:  clang version 3.8.1 (tags/RELEASE_381/final) Target: x86_64-unknown-linux-gnu Thread model: posix InstalledDir: /usr/local/bin"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="'probe' is not a recognized processor for this target (ignoring processor)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="'probe' is not a recognized processor for this target (ignoring processor)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="'probe' is not a recognized processor for this target (ignoring processor)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="'probe' is not a recognized processor for this target (ignoring processor)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="Prog section '2/10' rejected: Permission denied (13)!"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg=" - Type:         3"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg=" - Instructions: 1935 (0 over limit)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg=" - License:      GPL"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="Verifier analysis:"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="Skipped 15589 bytes, use 'verb' option for the full verbose log."
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="[...]"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg=" *(u64 *)(r0 +8)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="1032: (0f) r1 += r6"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="1033: (7b) *(u64 *)(r0 +8) = r1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="1034: (05) goto pc+11"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="1046: safe"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="from 1027 to 1035: safe"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="from 1004 to 1052: safe"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="from 343 to 523: R0=inv R1=inv32 R2=inv R3=imm54,min_value=54,max_value=54 R6=imm2,min_value=2,max_value=2 R7=inv R8=imm40,min_value=40,max_value=40 R9=ctx R10=fp fp-208=ctx"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="523: (18) r7 = 0xffffff7a"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="525: (61) r2 = *(u32 *)(r9 +80)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="526: (61) r1 = *(u32 *)(r9 +76)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="527: (bf) r3 = r1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="528: (07) r3 += 54"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="529: (2d) if r3 > r2 goto pc+465"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg=" R0=inv R1=pkt(id=0,off=0,r=54) R2=pkt_end R3=pkt(id=0,off=54,r=54) R6=imm2,min_value=2,max_value=2 R7=inv R8=imm40,min_value=40,max_value=40 R9=ctx R10=fp fp-208=ctx"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="530: (79) r2 = *(u64 *)(r10 -192)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="531: (7b) *(u64 *)(r10 -272) = r2"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="532: (79) r2 = *(u64 *)(r10 -200)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="533: (7b) *(u64 *)(r10 -280) = r2"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="534: (61) r2 = *(u32 *)(r1 +38)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="535: (bf) r3 = r2"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="536: (07) r3 += -3568"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="537: (55) if r2 != 0xdf0 goto pc+1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg=" R0=inv R1=pkt(id=0,off=0,r=54) R2=inv,min_value=3568,max_value=3568 R3=inv R6=imm2,min_value=2,max_value=2 R7=inv R8=imm40,min_value=40,max_value=40 R9=ctx R10=fp fp-208=ctx"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="538: (61) r3 = *(u32 *)(r1 +42)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="539: (7b) *(u64 *)(r10 -296) = r3"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="540: (7b) *(u64 *)(r10 -224) = r8"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="541: (7b) *(u64 *)(r10 -208) = r9"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="542: (b7) r1 = 160"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="543: (63) *(u32 *)(r10 -32) = r1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="544: (67) r3 <<= 32"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="545: (77) r3 >>= 32"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="546: (b7) r1 = 2"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="547: (b7) r4 = 3"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="548: (b7) r2 = 0"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="549: (1d) if r3 == r2 goto pc+1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg=" R0=inv R1=imm2,min_value=2,max_value=2 R2=imm0,min_value=0,max_value=0 R3=inv32 R4=imm3,min_value=3,max_value=3 R6=imm2,min_value=2,max_value=2 R7=inv R8=imm40,min_value=40,max_value=40 R9=ctx R10=fp fp-208=ctx"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="550: (b7) r4 = 2"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="551: (7b) *(u64 *)(r10 -288) = r4"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="552: (73) *(u8 *)(r10 -26) = r2"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="553: (6b) *(u16 *)(r10 -28) = r2"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="554: (73) *(u8 *)(r10 -25) = r1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="555: (79) r1 = *(u64 *)(r10 -192)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="556: (7b) *(u64 *)(r10 -16) = r1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="557: (79) r1 = *(u64 *)(r10 -200)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="558: (7b) *(u64 *)(r10 -24) = r1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="559: (bf) r2 = r10"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="560: (07) r2 += -32"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="561: (18) r1 = 0x77e8c180"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="563: (85) call 1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="564: (55) if r0 != 0x0 goto pc+37"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg=" R0=inv,min_value=0,max_value=0 R6=imm2,min_value=2,max_value=2 R7=inv R8=imm40,min_value=40,max_value=40 R9=ctx R10=fp fp-208=ctx"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="565: (bf) r8 = r10"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="566: (07) r8 += -28"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="567: (b7) r1 = 96"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="568: (63) *(u32 *)(r10 -32) = r1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="569: (b7) r6 = 0"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="570: (73) *(u8 *)(r8 +2) = r6"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="571: (6b) *(u16 *)(r8 +0) = r6"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="572: (b7) r9 = 2"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="573: (73) *(u8 *)(r10 -25) = r9"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="574: (79) r1 = *(u64 *)(r10 -200)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="575: (7b) *(u64 *)(r10 -24) = r1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="576: (7b) *(u64 *)(r10 -16) = r6"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="577: (bf) r2 = r10"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="578: (07) r2 += -32"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="579: (18) r1 = 0x77e8c180"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="581: (85) call 1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="582: (55) if r0 != 0x0 goto pc+19"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg=" R0=inv,min_value=0,max_value=0 R6=imm0,min_value=0,max_value=0 R7=inv R8=fp-28 R9=imm2,min_value=2,max_value=2 R10=fp fp-208=ctx"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="583: (bf) r1 = r10"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="584: (07) r1 += -24"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="585: (b7) r2 = 32"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="586: (63) *(u32 *)(r10 -32) = r2"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="587: (73) *(u8 *)(r8 +2) = r6"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="588: (6b) *(u16 *)(r8 +0) = r6"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="589: (73) *(u8 *)(r10 -25) = r9"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="590: (63) *(u32 *)(r1 +12) = r6"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="591: (63) *(u32 *)(r1 +8) = r6"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="592: (63) *(u32 *)(r1 +4) = r6"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="593: (63) *(u32 *)(r1 +0) = r6"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="594: (bf) r2 = r10"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="595: (07) r2 += -32"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="596: (18) r1 = 0x77e8c180"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="598: (85) call 1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="599: (b7) r9 = 53"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="600: (79) r8 = *(u64 *)(r10 -288)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="601: (15) if r0 == 0x0 goto pc+2"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg=" R0=map_value(ks=24,vs=8,id=0),min_value=0,max_value=0 R6=imm0,min_value=0,max_value=0 R7=inv R8=inv R9=imm53,min_value=53,max_value=53 R10=fp fp-208=ctx"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="602: (b7) r9 = 55"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="603: (69) r8 = *(u16 *)(r0 +0)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="604: (61) r3 = *(u32 *)(r10 -188)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="605: (7b) *(u64 *)(r10 -248) = r3"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="606: (79) r6 = *(u64 *)(r10 -208)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="607: (bf) r1 = r6"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="608: (85) call 34"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="609: (b7) r1 = 2"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="610: (73) *(u8 *)(r10 -32) = r1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="611: (73) *(u8 *)(r10 -31) = r9"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="612: (b7) r1 = 61535"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="613: (6b) *(u16 *)(r10 -30) = r1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="614: (63) *(u32 *)(r10 -28) = r0"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="615: (79) r1 = *(u64 *)(r10 -248)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="616: (63) *(u32 *)(r10 -24) = r1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="617: (57) r8 &= 65535"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="618: (7b) *(u64 *)(r10 -248) = r8"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="619: (63) *(u32 *)(r10 -20) = r8"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="620: (b7) r1 = 0"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="621: (63) *(u32 *)(r10 -16) = r1"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="622: (bf) r4 = r10"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="623: (07) r4 += -32"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="624: (bf) r1 = r6"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="625: (18) r2 = 0x747fc880"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="627: (18) r3 = 0xffffffff"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="629: (b7) r5 = 20"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="630: (85) call 25"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="631: (79) r9 = *(u64 *)(r10 -168)"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="invalid read from stack off -168+6 size 8"
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning
Aug 12 15:13:26 runtime cilium-agent[6208]: level=warning msg="Error filling program arrays!"
```

**Comment by joestringer** [comment]
(Copied assessment from slack):

IPv6 egress is failing due to `"invalid read from stack off -168+6 size 8"` during bpf compilation, likely stemming from the change in packed attribute of the ipv6 ct tuple. I haven't seen this before on master, but I'm not yet sure why. We could mitigate this (at least for the backport versions) by replacing the datapath code that packs the ipv6 structure  to instead round the ipv6 result for `getMapPathsToKeySize()` up to the nearest 8B boundary

Here's an example diff to achieve this:

```
diff --git a/bpf/lib/common.h b/bpf/lib/common.h
index e679524cea10..d42da9ba7934 100644
--- a/bpf/lib/common.h
+++ b/bpf/lib/common.h
@@ -343,7 +343,7 @@ struct ipv6_ct_tuple {
        __be16          sport;
        __u8            nexthdr;
        __u8            flags;
-} __attribute__((packed));
+};
 
 static inline union v6addr *
 ipv6_ct_tuple_get_daddr(struct ipv6_ct_tuple *tuple)
diff --git a/daemon/bpf.sha b/daemon/bpf.sha
index 545dd8ca482b..691ed8818abe 100644
--- a/daemon/bpf.sha
+++ b/daemon/bpf.sha
@@ -1,2 +1,2 @@
-GO_BINDATA_SHA1SUM=d64f01444413a7d6108c95a2bfb05816c8fab7d8
+GO_BINDATA_SHA1SUM=1bfa75dcfac80c330545e963c5bb3d1689b91e8c
 BPF_FILES=../bpf/.gitignore ../bpf/COPYING ../bpf/Makefile ../bpf/bpf_features.h ../bpf/bpf_lb.c ../bpf/bpf_lxc.c ../bpf/bpf_netdev.c ../bpf/bpf_overlay.c ../bpf/bpf_xdp.c ../bpf/cilium-map-migrate.c ../bpf/filter_config.h ../bpf/include/bpf/api.h ../bpf/include/elf/elf.h ../bpf/include/elf/gelf.h ../bpf/include/elf/libelf.h ../bpf/include/iproute2/bpf_elf.h ../bpf/include/linux/bpf.h ../bpf/include/linux/bpf_common.h ../bpf/include/linux/byteorder.h ../bpf/include/linux/byteorder/big_endian.h ../bpf/include/linux/byteorder/little_endian.h ../bpf/include/linux/icmp.h ../bpf/include/linux/icmpv6.h ../bpf/include/linux/if_arp.h ../bpf/include/linux/if_ether.h ../bpf/include/linux/in.h ../bpf/include/linux/in6.h ../bpf/include/linux/ioctl.h ../bpf/include/linux/ip.h ../bpf/include/linux/ipv6.h ../bpf/include/linux/perf_event.h ../bpf/include/linux/swab.h ../bpf/include/linux/tcp.h ../bpf/include/linux/type_mapper.h ../bpf/include/linux/udp.h ../bpf/init.sh ../bpf/join_ep.sh ../bpf/lib/arp.h ../bpf/lib/common.h ../bpf/lib/conntrack.h ../bpf/lib/csum.h ../bpf/lib/dbg.h ../bpf/lib/drop.h ../bpf/lib/encap.h ../bpf/lib/eps.h ../bpf/lib/eth.h ../bpf/lib/events.h ../bpf/lib/icmp6.h ../bpf/lib/ipv4.h ../bpf/lib/ipv6.h ../bpf/lib/l3.h ../bpf/lib/l4.h ../bpf/lib/lb.h ../bpf/lib/lxc.h ../bpf/lib/maps.h ../bpf/lib/metrics.h ../bpf/lib/nat46.h ../bpf/lib/policy.h ../bpf/lib/trace.h ../bpf/lib/utils.h ../bpf/lib/xdp.h ../bpf/lxc_config.h ../bpf/netdev_config.h ../bpf/node_config.h ../bpf/probes/raw_change_tail.t ../bpf/probes/raw_insn.h ../bpf/probes/raw_invalidate_hash.t ../bpf/probes/raw_lpm_map.t ../bpf/probes/raw_lru_map.t ../bpf/probes/raw_main.c ../bpf/probes/raw_map_val_adj.t ../bpf/probes/raw_mark_map_val.t ../bpf/run_probes.sh ../bpf/spawn_netns.sh 
diff --git a/pkg/maps/ctmap/ctmap.go b/pkg/maps/ctmap/ctmap.go
index df93b01ff4f9..26bcd9b29965 100644
--- a/pkg/maps/ctmap/ctmap.go
+++ b/pkg/maps/ctmap/ctmap.go
@@ -100,12 +100,18 @@ func GetMapPath(e CtEndpoint, isIPv6 bool) string {
        return file
 }
 
+// roundToWordBoundary rounds the specified value up to the nearest 64-bit word
+// boundary.
+func roundToWordBoundary(size uintptr) uint32 {
+       return uint32(size + (8 - size%8))
+}
+
 // getMaps fetches all paths for conntrack maps associated with the specified
 // endpoint, and returns a map from these paths to the keySize used for that
 // map.
 func getMapPathsToKeySize(e CtEndpoint) map[string]uint32 {
        return map[string]uint32{
-               GetMapPath(e, true):  uint32(unsafe.Sizeof(CtKey6{})),
+               GetMapPath(e, true):  roundToWordBoundary(unsafe.Sizeof(CtKey6{})),
                GetMapPath(e, false): uint32(unsafe.Sizeof(CtKey4{})),
        }
 }
```

This would also serve to avoid changing map attributes in the micro-release, which further reduces the upgrade impact.

**Comment by tgraf** [comment]
@joestringer Added

**Comment by tgraf** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-docs-please

**Comment by joestringer** [comment]
k8s tests timed out:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/677/flowGraphTable/

**Comment by tgraf** [comment]
test-missed-k8s

**Pull request merged**
