### PR TITLE
backport: 1.4 backports 18-12-19

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:

* #6082 
* #6375 
* #6404 
* #6432 
* #6436 
* #6443 
* #6446 
* #6459 
* #6461 
* #6464 
* #6466 
* #6472 
* #6474 

Signed-off by: Ian Vernon <ian@cilium.io.

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6479)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Hit loader unit test failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8613/execution/node/56/log/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Normal CI job got stuck building container image: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8615/

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
