### PR TITLE
test: bump upgrade tests to test 1.13

### PR DESCRIPTION
**Pull request by aanm**
We have released 1.13.0 so it's time for us to start testing 1.13.0 upgrade.

### CODE REVIEW

**Comment by aanm** [comment]
blocked by https://github.com/cilium/cilium/issues/23819

**Comment by aanm** [comment]
Blocked by #24191

**Comment by aanm** [comment]
/test-1.24-5.4

**Comment by aanm** [comment]
/test-1.26-net-next

**Comment by aanm** [comment]
/test-1.26-net-next

**Comment by aanm** [comment]
/test-only --focus="K8sUpdates" --k8s_version=1.26 --kernel_version=net-next

**Comment by aanm** [comment]
/test-1.26-net-next

**Comment by aanm** [comment]
/test-1.24-5.4

**Review by christarazi — APPROVED** [review]

**Comment by joestringer** [comment]
Did we ever get to the bottom of why this test wasn't picking up #24191 during the v1.13 development process?

**Pull request merged**
