### PR TITLE
v1.13 Backports 2023-06-30

### PR DESCRIPTION
**Pull request by tklauser**
* [ ] #26560 (@ferozsalam)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 26560; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=26560
```

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.13

**Review by ferozsalam — APPROVED** [review]
thanks!

**Comment by tklauser** [comment]
/ci-l4lb-1.13

**Comment by joamaki** [comment]
/ci-aks-1.13

**Review by squeed — APPROVED** [review]

**Pull request merged**
