### PR TITLE
Adding an AWS architecture diagram for AWS FTR review

### PR DESCRIPTION
**Pull request by amitmavgupta**

### CODE REVIEW

**Review by zacharysarah — APPROVED** [review]
LGTM

@amitmavgupta 👋🏻 Please be sure to add a release note.

**Review by christarazi — COMMENTED** [review]
Please signoff your commit by doing `git commit --amend --signoff`.

**Comment by amitmavgupta** [comment]
@christarazi could you kindly approve and merge? I have signed off the commit.

**Review by christarazi — APPROVED** [review]

**Comment by joestringer** [comment]
Hi @amitmavgupta , I know this feedback is late, but I'm wondering why this was needed if there was already an architecture diagram just a few lines down in the same document? Maybe this was a refresh and we should delete the second one?

https://docs.cilium.io/en/stable/installation/cni-chaining-aws-cni/

**Comment by amitmavgupta** [comment]
@joestringer the architecture diagram was required to complete the AWS FTR which required us to have a reference architecture distinctly called out.

**Comment by joestringer** [comment]
I just realized the diagram looks incorrect. The page is about chaining with AWS VPC CNI chaining, but that plugin is not present in the diagram.

**Pull request merged**
