### PR TITLE
[v1.13] envoy: Update to use source port in connection pool hash

### PR DESCRIPTION
**Pull request by jrajahalme**
Author backport of 

* [ ] #32270

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
32270
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.13

**Comment by jrajahalme** [comment]
/test-1.26-net-next

**Comment by jrajahalme** [comment]
/test-1.18-4.19

**Comment by jrajahalme** [comment]
/test-1.20-4.19

**Review by youngnick — APPROVED** [review]

**Review by ldelossa — APPROVED** [review]

**Pull request merged**
