### PR TITLE
update cilium/certgen to v0.1.11

### PR DESCRIPTION
**Pull request by rolinh**
v0.1.10 and v0.1.11 are patch releases which update the Go version and dependencies. See releases for details:

v0.1.10: https://github.com/cilium/certgen/releases/tag/v0.1.10
v0.1.11: https://github.com/cilium/certgen/releases/tag/v0.1.11

I marked the PR for backport to all maintained branches as the new release is built with Go v1.22.2 and updated dependencies which address security issues.

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Thanks! Is there any reason we can't have Renovate update this in the future?

**Comment by rolinh** [comment]
> Thanks! Is there any reason we can't have Renovate update this in the future?

I don't think so, we probably want to setup renovate for that indeed.

**Comment by rolinh** [comment]
@gandro I pushed another commit for Renovate. I think that's all that is needed based on my understanding of the current renovate config. Well, we'll see soon enough I guess :slightly_smiling_face:

**Review by tommyp1ckles — APPROVED** [review]

**Pull request merged**
