### PR TITLE
v1.6 backports 2019-12-12

### PR DESCRIPTION
**Pull request by jrajahalme**
* #9643 -- Add missing words to spelling_wordlist (@ungureanuvladvictor)
 * #9743 -- fqdn: Support setting tofqdns-min-ttl to 0 (@raybejjani)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 9643 9743; do contrib/backporting/set-labels.py $pr done 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9753)

### CODE REVIEW

**Comment by jrajahalme** [comment]
never-tell-me-the-odds

**Review by aanm — APPROVED** [review]

**Review by aanm — CHANGES_REQUESTED** [review]
Can you drop the FQDN commit so we can fix the documentation parts?

**Comment by raybejjani** [comment]
@jrajahalme I finally managed to understand what's going on. The version of viper we have on master and 1.6 happen to have a bug were IsSet always returns true. This seems to cause IPs to not show up in the checks for the failing tests. Given that the original motivation for backporting this was to supports the `--tofqdns-min-ttl 0` usecase, but it turned out to not be in-use, I'd say let's skip the backport for now. It isn't critical for any known user (and otherwise unlikely to occur).
See https://github.com/cilium/cilium/pull/9796 for the fix on master.

**Comment by jrajahalme** [comment]
Dropped #9743

**Comment by jrajahalme** [comment]
never-tell-me-the-odds

**Pull request merged**
