### PR TITLE
Use original Cilium K8s descriptors in tests

### PR DESCRIPTION
**Pull request by aanm**
With this PR we will always test against the original cilium kubernetes descriptors in `examples/kubernetes` the CI will still have specific patches applied to the original files but it will no longer require us to maintain copies of the original descriptor files in the test directory.

Fixes: https://github.com/cilium/cilium/issues/5281

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5297)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-docs-please

**Comment by eloycoto** [comment]
I'm happy with the change, but I would not change kubecfg here, let me explain the reason: 

- @tgraf want to add more labels on cilium-agent, BuildNumber and Jenkins job name, if we use kubecfg we can use jsonnet `std.extVar(x)`, we should create on-fly yamls if we use `kubectl patch`
- These changes do not update the livenessProbe and the readinessProbe, if we have as big as in the examples, CI will take a bit longer. 
- Devs lost the availability to run one single command to install cilium for testing. 
- We lost the availability to have dsManifest option, and that has a idea behind of that. (To run all the test using custom options, like all the test in geneve for example)

I know that `kubectl patch`  works, but I still do not know a user that use it in the daily job, `kubecfg` or `helm` are the tools that people use, and I think that we should use that too, but as I said, this works and I'm happy to merge, I would change the livenessProbe, waiting 2 minutes each time that cilium is installed means that we increase the test about 8 minutes (we installed 4 times) 

Regards.

**Comment by aanm** [comment]
@eloycoto 

>These changes do not update the livenessProbe and the readinessProbe, if we have as big as in the examples, CI will take a bit longer.

That can be made in a following up PR as I kept the same liveness and readiness probe from the old template.

> We lost the availability to have dsManifest option, and that has a idea behind of that. (To run all the test using custom options, like all the test in geneve for example)

If it helps we can have a new option called "patchDescriptor" that points to other `cilium-ds-patch.yaml` instead of the default one. but TBH the developer can also change the `cilium-ds-patch.yaml` directly.

>@tgraf want to add more labels on cilium-agent, BuildNumber and Jenkins job name, if we use kubecfg we can use jsonnet std.extVar(x), we should create on-fly yamls if we use kubectl patch

We can always add a new patch line with the labels that we want.
```
if os.Exists("generated-file-with-labels.yaml") {
      kubectl patch --filename='%s' --patch \"$(cat generated-file-with-labels.yaml)\"
}
```

**Comment by aanm** [comment]
test-me-please

**Comment by eloycoto** [comment]
> That can be made in a following up PR as I kept the same liveness and readiness probe from the old template.

I don't see a reason why it should be addressed in  another PR, this build will take another 8 minutes, and I think that there is no reason why this PR need to rush to be merged. 

> If it helps we can have a new option called "patchDescriptor" that points to other cilium-ds-patch.yaml instead of the default one. but TBH the developer can also change the cilium-ds-patch.yaml directly.

The idea is not as a dev to run that, the idea is to have a `test-me-please --cilium.dsManifest` and all can be run in Jenkins, the new jobs are defered until sept, but will be in there and we're going to need this one. 

> We can always add a new patch line with the labels that we want.
```
if os.Exists("generated-file-with-labels.yaml") {
      kubectl patch --filename='%s' --patch \"$(cat generated-file-with-labels.yaml)\"
}
```

The problem is not using another pach file, the problem is to create the file, that need to be yaml, autogenerated, etc.. and always we finish with the following phrase, `if we do logic in the test, who is testing the test?` With jsonnet/kubecfg is to use something that is develop by other people, and we are only consumers. 

I'll wait for @ianvernon input here.

**Comment by aanm** [comment]
>> That can be made in a following up PR as I kept the same liveness and readiness probe from the old template.
>
>I don't see a reason why it should be addressed in  another PR, this build will take another 8 minutes, and I think that there is no reason why this PR need to rush to be merged. 

Where did you see it takes another 8 minutes? As I said before, I kept the same liveness and readiness probe from the previous template. https://github.com/cilium/cilium/pull/5297/commits/38b12b5e00f1a886daf907bcdd25ac16ccf23b0c#diff-d142da8ce8fb7d2c0f803dd6cc776df2L187

>> If it helps we can have a new option called "patchDescriptor" that points to other cilium-ds-patch.yaml instead of the default one. but TBH the developer can also change the cilium-ds-patch.yaml directly.
>
>The idea is not as a dev to run that, the idea is to have a `test-me-please --cilium.dsManifest` and all can be run in Jenkins, the new jobs are defered until sept, but will be in there and we're going to need this one. 

I can add the `patchDescriptor` option that points to a `cilium-ds-patch.yaml`

>> We can always add a new patch line with the labels that we want.
>>```
>>if os.Exists("generated-file-with-labels.yaml") {
>>      kubectl patch --filename='%s' --patch \"$(cat generated-file-with-labels.yaml)\"
>>}
>>```
>>
>The problem is not using another pach file, the problem is to create the file, that need to be yaml, autogenerated, etc.. and always we finish with the following phrase, `if we do logic in the test, who is testing the test?` With jsonnet/kubecfg is to use something that is develop by other people, and we are only consumers. 

We can always write unit tests for the helpers. I don't see what difference is the `generated-file-with-labels.yaml` compared to the `cilium-ds-patch.yaml`. Also, the generated file is only one option, the `patch` parameter also accept inline parameter and no files are generated.

```
kubectl patch deployment patch-demo --patch '{"spec": {"template": {"spec": {"containers": [{"name": "patch-demo-ctr-2","image": "redis"}]}}}}'
```

I just find it easier to have it in files.

> I'll wait for @ianvernon input here.

**Comment by eloycoto** [comment]
> Where did you see it takes another 8 minutes? As I said before, I kept the same liveness and readiness probe from the previous template. 38b12b5#diff-d142da8ce8fb7d2c0f803dd6cc776df2L187

Sorry, I remember to set to 30 seconds, it's ok then.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]
LGTM. Regarding whether we use `kubecfg` or `kubectl` does not make much of a difference to me, as long as we are guaranteed to be using the generated YAMLs which we provide to end-users, which this achieves.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
@eloycoto anything else needed here? Wanted to confirm with you before merging.

**Comment by eloycoto** [comment]
There is the ciliumDSManifest option that got deleted, but can be done in another PR.

**Comment by tgraf** [comment]
@eloycoto Do you want to merge this as-is?

**Pull request merged**
