### PR TITLE
Dockerfile: point envoy image to an existent repository

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6148)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]

**Comment by aanm** [comment]
@jrajahalme can you take a look at the failure?
```
Nov 02 08:43:09 runtime systemd[1]: Started cilium.
Nov 02 08:43:09 runtime cilium-agent[8866]: level=info msg="Detected MTU 1500" subsys=mtu
Nov 02 08:43:09 runtime cilium-agent[8866]: level=info msg="     _ _ _" subsys=daemon
Nov 02 08:43:09 runtime cilium-agent[8866]: level=info msg=" ___|_| |_|_ _ _____" subsys=daemon
Nov 02 08:43:09 runtime cilium-agent[8866]: level=info msg="|  _| | | | | |     |" subsys=daemon
Nov 02 08:43:09 runtime cilium-agent[8866]: level=info msg="|___|_|_|_|___|_|_|_|" subsys=daemon
Nov 02 08:43:09 runtime cilium-agent[8866]: level=info msg="Cilium 1.2.90 de0b0a2e7 2018-11-02T08:32:04+00:00 go version go1.11.1 linux/amd64" subsys=daemon
Nov 02 08:43:09 runtime cilium-agent[8866]: level=info msg="cilium-envoy  version: 971e018d05c0fce542d315e320b7b5d9e7480d24/1.8.0-dev/Modified/RELEASE" subsys=daemon
Nov 02 08:43:09 runtime cilium-agent[8866]: level=fatal msg="Envoy version 971e018d05c0fce542d315e320b7b5d9e7480d24/1.8.0-dev/Modified/RELEASE does not match with required version fd3866831d8f85e27120f34d98133343fc9c4e0e ,aborting." subsys=daemon
```

**Comment by aanm** [comment]
test-me-please

**Comment by jrajahalme** [comment]
This is superseded by #6158, except for the part of using quay.io instead of Docker Hub.

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
