### PR TITLE
v1.10 backports 2021-05-21

### PR DESCRIPTION
**Pull request by nbusseneau**
* #16051 -- test: Quarantine fragment tracking test on GKE (@pchaigno)
 * #15899 -- Improve author attribution scripts (@joestringer)
 * #16142 -- helm: add back 'wellKnownIdentities' (@bmcustodio)
 * #15872 -- Improve ipsec compile-time testing in CI (@joestringer)
 * #16199 -- .github: Cancel outdated GitHub workflows (@pchaigno)
 * #16214 -- Specify scrape interval for Hubble metrics (@christian-2)
 * #16175 -- alibabacloud: fix race (@l1b0k)
 * #16104 -- daemon: Ignore cilium_* interfaces when deriving NodePort device (@eyanulis)
 * #16218 -- ci: add slack notification to GH actions (@nebril)
 * #16158 -- examples, connectivity-check, test: Use even-numbered nodePort (@christarazi)
 * #16157 -- .github: Skip unnecessary workflow steps (@pchaigno)
 * #15989 -- docs: Clarify coordination for backporting process (@christarazi)
 * #16149 -- docs: Revert host firewall to beta for kube-proxy setups (@pchaigno)
 * #16187 -- vendor: Bump go.universe.tf/metallb (@christarazi)
 * #16207 -- .github: Speed up cluster cleanups in end-to-end tests (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16051 15899 16142 15872 16199 16214 16175 16104 16218 16158 16157 15989 16149 16187 16207; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
My commits look good :+1:

**Comment by nbusseneau** [comment]
Sorry, I made a mistake with my fork and accidentally closed all my PRs. Reopening.

**Review by christarazi — COMMENTED** [review]
:+1: for my commits

**Review by christarazi — APPROVED** [review]

**Review by bmcustodio — APPROVED** [review]
> #16142 -- helm: add back 'wellKnownIdentities' (@bmcustodio)

LGTM :+1:

**Comment by pchaigno** [comment]
test-backport-1.10

**Comment by nbusseneau** [comment]
1.21 / 4.9 hit #16237 : https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/545/testReport/junit/Suite-k8s-1/21/K8sServicesTest_Checks_service_across_nodes_Checks_ClusterIP_Connectivity/

All good otherwise.

**Review by aanm — APPROVED** [review]

**Comment by pchaigno** [comment]
I think we can merge this. I reviewed the code from Maciej and tests are passing except for the known flake mentioned by Nicolas.

**Comment by nbusseneau** [comment]
@aanm @pchaigno Can one of you review also [this commit](https://github.com/cilium/cilium/pull/16269/commits/01a3fc424084565d93fd2da9edd769e5709a2213) originally from Joe and for which there were conflitcs? See commit log for details on how I resolved.

**Comment by pchaigno** [comment]
> @aanm @pchaigno Can one of you review also [this commit](https://github.com/cilium/cilium/pull/16269/commits/01a3fc424084565d93fd2da9edd769e5709a2213) originally from Joe and for which there were conflitcs? See commit log for details on how I resolved.

I looks good :+1: 
The only nit is that we would usually keep all `Signed-off-by` and similar tags at the end of the commit description to ease parsing in tools, etc. (though I understand the intent of clarifying what text belongs where :slightly_smiling_face:)

**Comment by nbusseneau** [comment]
> The only nit is that we would usually keep all `Signed-off-by` and similar tags at the end of the commit description to ease parsing in tools, etc. (though I understand the intent of clarifying what text belongs where slightly_smiling_face)

🙈
(though in this case I think my solution is the right way to go, and tools should be smarter)

**Comment by christarazi** [comment]
@nbusseneau Usually the format for something like this is

```
commit title

[ Backporter's notes: blah blah

Body of commit

Sign off: original author
Sign off: you
```

**Pull request merged**
