### PR TITLE
[v1.13] Test upgrade/downgrade to patch release for IPsec

### PR DESCRIPTION
**Pull request by qmonnet**
- [x] #27977 (@michi-covalent)
- [x] #28016 (@jschwinger233)
- [x] #29072 (@brb)
- [x] #28815 (@qmonnet)

Related to
- #14882

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 27977 28016 29072 28815; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=27977,28016,29072,28815
```

### CODE REVIEW

**Comment by qmonnet** [comment]
/test-backport-1.13

**Comment by qmonnet** [comment]
/test-1.21-4.19

**Comment by qmonnet** [comment]
/test-1.24-4.19

**Comment by qmonnet** [comment]
/test-1.25-4.19

**Comment by qmonnet** [comment]
/test-backport-1.13

**Comment by qmonnet** [comment]
/test-1.20-4.19

**Comment by qmonnet** [comment]
[Tests fail when upgrading from either minor or patch version on bpf-next](https://github.com/cilium/cilium/actions/runs/6895070419/job/18760311812), but I understand this has been the case before this PR. Other tests passed.

I need to rebase this one now that 751b7c4713f293d3d2ae2d168ffd0ad754321767 was merged.

**Comment by qmonnet** [comment]
/test-backport-1.13

**Review by michi-covalent — APPROVED** [review]

**Comment by qmonnet** [comment]
/test-1.24-4.19

**Comment by qmonnet** [comment]
/test-backport-1.13

**Review by brb — APPROVED** [review]
My changes LGTM, thanks.

**Comment by qmonnet** [comment]
/test-backport-1.13

**Comment by qmonnet** [comment]
/test-1.26-net-next

**Review by lmb — APPROVED** [review]
:tophat:

**Review by pchaigno — APPROVED** [review]
net-next should now be fixed, so probably worth rebasing to ensure CI passes. Might also be worth updating the commits here with references to the now-merged upstream commits.

**Comment by qmonnet** [comment]
/test-backport-1.13

**Comment by qmonnet** [comment]
/test-backport-1.13

**Comment by qmonnet** [comment]
/test-1.23-4.19

**Review by youngnick — APPROVED** [review]

**Pull request merged**
