### PR TITLE
istio: Add nslookup timeout during container injection

### LINKED ISSUE #6230: Add timeout to nslookup init container in istio injection
When performing Istio injection, an init container is added to wait for the DNS name to become available:

```
command: ['sh', '-c', 'until nslookup kube-dns.kube-system.svc.cluster.local; do sleep 1; done']"
```

There is no timeout associated with this so far so a pod will stay in `Init` phase forever. Introducing a timeout can potentially help as the pod can be re-scheduled onto a different node.

### PR DESCRIPTION
**Pull request by iffyio**
Aborts the DNS lookup if still unsuccessful when timeout elapses

Fixes #6230

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7424)

### CODE REVIEW

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
runtime FQDN tests failed

**Comment by tgraf** [comment]
test-me-please

**Comment by iffyio** [comment]
Hey @tgraf It looks like this time around, most of the tests fail in `BeforeAll` (assuming due to `runtime.RuntimeConntrackTest Conntrack-related configuration options for endpoints` failing?) Is this a result of the changes made in this PR?

**Comment by aanm** [comment]
> Hey @tgraf It looks like this time around, most of the tests fail in `BeforeAll` (assuming due to `runtime.RuntimeConntrackTest Conntrack-related configuration options for endpoints` failing?) Is this a result of the changes made in this PR?

@iffyio no :)

**Comment by aanm** [comment]
test-docs-please

**Pull request merged**
