### PR TITLE
vagrant: Bump net-next Vagrant box version

### PR DESCRIPTION
**Pull request by pchaigno**
This new version includes updates for the kernel, Ubuntu, and Docker images.

### CODE REVIEW

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Review by sayboras — APPROVED** [review]

**Comment by pchaigno** [comment]
Some issue with vboxsf...

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
Net-next is still blocked on the vboxsf issue. I will close this so I can update the other VM images.

**Pull request closed without merging**
