### PR TITLE
bpf/init.sh: move node config generation to Go

### LINKED ISSUE #25378: init.sh: move node_config.h header generation to Go
init.sh writes and `sed`s a bunch of values in node_config.h, and this should be done from Go going forward.

Some things to pay attention to:

- Taking the same approach of appending values to an existing header is a bad idea in general. node_config.h should include an autogenerated file that is generated from Go using a template or equivalent logic if a template is overkill. That way, compilation will fail if the header is not generated yet, making bugs in the startup sequence more obvious.
- grep for `node_config.h` in the codebase to form an idea of which components explicitly depend on it. There are comments in Go files mentioning the file, so those spots may be of particular interest.
- `ip link show` info may be available in DeviceManager.
- sysctls can be obtained through package `pkg/sysctl`.

### PR DESCRIPTION
**Pull request by rgo3**
This PR refactors node_config.h generation code in init.sh to Go. In order for this to work properly the function that initially creates node_config.h had to move to Reinitialize().

Fixes: #25378

### CODE REVIEW

**Review by dylandreimerink — APPROVED** [review]

**Review by pippolo84 — APPROVED** [review]
LGTM for agent related changes :rocket:

**Pull request merged**
