### PR TITLE
test/provision: bump k8s testing to v1.13.6

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8013)

### CODE REVIEW

**Comment by aanm** [comment]
test-missed-k8s

**Review by nebril — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Pull request merged**
