### PR TITLE
Improve CEP representation of l4-only allow

### PR DESCRIPTION
**Pull request by joestringer**
BPF map state which allows all peers to access traffic on an L4 port
encodes the identity as "0", which in this case means "allow all", not
the "reserved:unknown" identity. To properly reflect this in the API,
don't serialize the labels in this case. API users should interpret the
lack of `Identity` and `IdentityLabels` as allowing all peers on the L4 port.

Fixes: #7511

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7535)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

EDIT: All green, will rebase to kick travis.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Hit #7495 . Also fixing unit-test issue, rebasing.

**Comment by joestringer** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
