### PR TITLE
v1.13 Backports 2024-05-16

### PR DESCRIPTION
**Pull request by giorio94**
* [x] #32336 (@giorio94) :warning: resolved conflicts
    :information_source: Resolved minor conflicts detailed in the individual commit messages. Dropped https://github.com/cilium/cilium/commit/8c951b2785b001841dcc88f03bac98f9f5a538f1 and https://github.com/cilium/cilium/commit/041321b7a70d8370fae571f0524cbf8b538d4780, as not relevant in Cilium v1.13.
 * [x] #32552 (@giorio94) :warning: resolved conflicts
    ℹ️ Resolved minor conflicts detailed in the individual commit messages. Dropped https://github.com/cilium/cilium/commit/952df8f98dfab6436f08cf611a37e1681b4d2f4b as not relevant in Cilium v1.13.

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 32336 32552
```

### CODE REVIEW

**Comment by giorio94** [comment]
/test-backport-1.13

**Comment by giorio94** [comment]
/test-backport-1.13

**Comment by giorio94** [comment]
/test-backport-1.13

**Comment by giorio94** [comment]
/test-1.18-4.19

**Review by lmb — APPROVED** [review]

**Pull request merged**
