### PR TITLE
Pr/ray/revert waitfor

### PR DESCRIPTION
**Pull request by raybejjani**
We've been seeing unstable CI since last week. It might be this PR (and its updates). So, maybe this is better?

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8730)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-nightly

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-nightly

**Review by eloycoto — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by nebril** [comment]
This PR seems to fix much flakiness, I think we should merge it.

**Comment by raybejjani** [comment]
Well, this passed 6/8 times (https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/revert-waitfor/) so it seems better. The failures that did happen were cilium-health related but I'm not clear why. I will merge this.


One possible reason we see more failures  is that k8s 1.10 doesn't populate `DaemonSetStatus.NumberUnavailable` correctly/the same way/ever.

**Pull request merged**
