### PR TITLE
Update k8s test versions of 1.8, 1.9, 1.10 and 1.11

### PR DESCRIPTION
**Pull request by aanm**
Update k8s test versions and kubedns

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
Thanks, that DNS changes will fix the guestbook issues?

**Review by eloycoto — APPROVED** [review]

**Comment by aanm** [comment]
@eloycoto Not sure, let's see :crossed_fingers:

**Comment by aanm** [comment]
waiting on https://github.com/kubernetes/kubernetes/issues/62403

**Review by tgraf — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
Given that we are updating K8s versions, I do not think this is ready to be merged. Test failures need to be analyzed.

**Comment by aanm** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/2609/
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/136/
storing to know if those are flakes

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Pull request merged**
