### PR TITLE
operator: generate cmdref

### PR DESCRIPTION
**Pull request by ianvernon**
Other cilium binaries have a `cmdref` option, which, when provided, generates
the cmdref for the given binary. Provide the same for cilium-operator.

To generate the cmdref output for cilium-operator, run the following command:

```
make -C Documentation/ cmdref
```

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8918)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Travis timed out:

```
Unable to find image 'quay.io/coreos/etcd:v3.2.17' locally
v3.2.17: Pulling from coreos/etcd
ff3a5c916c92: Pulling fs layer
284f89722fb0: Pulling fs layer
4a3171e40b10: Pulling fs layer
71d778e32a40: Pulling fs layer
e5fe97300337: Pulling fs layer
a47915215f95: Pulling fs layer
71d778e32a40: Waiting
e5fe97300337: Waiting
a47915215f95: Waiting
ff3a5c916c92: Verifying Checksum
ff3a5c916c92: Download complete
4a3171e40b10: Verifying Checksum
4a3171e40b10: Download complete
284f89722fb0: Verifying Checksum
284f89722fb0: Download complete
ff3a5c916c92: Pull complete
71d778e32a40: Verifying Checksum
71d778e32a40: Download complete
e5fe97300337: Verifying Checksum
e5fe97300337: Download complete
284f89722fb0: Pull complete
4a3171e40b10: Pull complete
71d778e32a40: Pull complete
e5fe97300337: Pull complete


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

```

**Review by joestringer — APPROVED** [review]

**Comment by ianvernon** [comment]
Merging since @joestringer is now part of the @cilium/docs team as well.

**Pull request merged**
