### PR TITLE
Adding support for tracking instance hypervisor type in ENI limits pkg

### PR DESCRIPTION
**Pull request by tommyp1ckles**
[ upstream commit 2cd83ee6db83d51980f637176becab7fd51dbd0e ]

Signed-off-by: Hemanth Malla <hemanth.malla@datadoghq.com>
Signed-off-by: Tom Hadlaw <tom.hadlaw@isovalent.com>

Backporting recent update to the eni limits map so that v1.10 has up to date list, as well as recent changes to the limit structure so that we can easily backport these updates in the future.

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@tommyp1ckles the CI failure is legitimate.

**Comment by tommyp1ckles** [comment]
@aanm I see what happened, the API generate changes where part of a different [commit](https://github.com/cilium/cilium/pull/18463/commits/67b0fb922772867a3ab2103bdb5995657b12a14f#diff-f698b5ac30e65c4c5902fdc615748187978cca1987796dcb4360e8dafabce8aaR184)

There's more changes there than I want to add to this backport. We can create a new commit with the zz_deepcopy generate changes.

**Comment by aanm** [comment]
@tommyp1ckles make sure the files are generated with the same Golang version pointed out in go.mod. I believe 1.10 is with golang 1.17 or go 1.16

**Comment by tommyp1ckles** [comment]
/test-backport-v1.10

**Comment by tommyp1ckles** [comment]
/test-backport-v1.10

**Comment by tommyp1ckles** [comment]
/test-1.24-net-next

**Comment by tommyp1ckles** [comment]
/test-1.23-4.19

**Comment by tommyp1ckles** [comment]
/test-1.22-5.4

**Comment by tommyp1ckles** [comment]
/test-backport-v1.10

**Comment by tommyp1ckles** [comment]
CodeQL CI failures on this don't seem to have anything to do with this branch.

**Comment by tommyp1ckles** [comment]
/test-1.22-5.4

**Comment by tommyp1ckles** [comment]
/test-1.23-4.19

**Comment by tommyp1ckles** [comment]
/test-1.23-5.4

**Comment by tommyp1ckles** [comment]
/test-1.24-net-next

**Comment by tommyp1ckles** [comment]
/test-backport-1.10

**Comment by tommyp1ckles** [comment]
/test-backport-v1.10

**Comment by tommyp1ckles** [comment]
/test-backport-v1.10

**Comment by tommyp1ckles** [comment]
I don't think all the correct CI jobs are being run here. Going to try to invoke them manually.

**Comment by tommyp1ckles** [comment]
/test-1.21-4.9

**Comment by tommyp1ckles** [comment]
/test-1.20-4.19

**Comment by tommyp1ckles** [comment]
/test-1.20-4.19

**Comment by tommyp1ckles** [comment]
/test-1.19-5.4

**Comment by tommyp1ckles** [comment]
/test-1.19-4.9

**Comment by tommyp1ckles** [comment]
/test-backport-1.10

**Comment by tommyp1ckles** [comment]
/ci-multicluster-1.10

**Comment by tommyp1ckles** [comment]
/test-1.19-4.9

**Comment by aanm** [comment]
Merging since this PR only affects eks code and that test has passed.

**Pull request merged**
