### PR TITLE
[v1.15] Bump GoBGP to v3.27.0

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
To pull-in the recent fix (https://github.com/osrg/gobgp/pull/2803) for the [issue](https://github.com/osrg/gobgp/issues/2596).

Fixes: https://github.com/cilium/cilium/issues/32886

```release-note
Bump GoBGP to v3.27.0
```

### CODE REVIEW

**Comment by YutaroHayakawa** [comment]
/test-backport-1.15

**Review by marseel — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
Putting this back to draft. Sorry, seems like upgrading GoBGP doesn't solve the original issue.

**Comment by YutaroHayakawa** [comment]
Modified the GoBGP version to v3.27.0 which actually solves the problem.

**Comment by YutaroHayakawa** [comment]
Rebased on the latest v1.15

**Comment by YutaroHayakawa** [comment]
/test-backport-1.15

**Review by dylandreimerink — APPROVED** [review]

**Pull request merged**
