### PR TITLE
agent: Stop serving DNS before shutdown

### PR DESCRIPTION
**Pull request by nebril**
This PR affects DNS proxy startup, as we have started proxy without populating proxy DNS clients which might have caused some DNS messages to get to proxy before it had DNS clients set.

 It also adds a cleanup step that causes the proxy to unbind from the socket so that it doesn't get served DNS traffic while it's shutting down. This should decrease amount of in-flight DNS messages that are lost because proxy is being shut down.

```release-note
dnsproxy: stop serving DNS traffic before agent shutdown
```

### CODE REVIEW

**Comment by nebril** [comment]
There were some issues with operator image in quay, reran the image build job, now it seems to be working, rerunning tests.

**Comment by nebril** [comment]
I hit some panics in cleanup code, changing to draft.

**Comment by nebril** [comment]
/test-1.16-4.9

**Review by jrajahalme — APPROVED** [review]
LGTM

**Comment by nebril** [comment]
/test-1.23-5.4

**Comment by nebril** [comment]
/test-1.24-4.19

**Comment by nebril** [comment]
/test-1.25-net-next

**Review by pippolo84 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
