### PR TITLE
daemon/cmd: fix a couple of func doc string

### PR DESCRIPTION
**Pull request by cuishuang**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Review by kaworu — APPROVED** [review]
@cuishuang thanks for the PR and good catch.

Could you please rephrase the commit message and PR title to something a tad more descriptive? e.g. "daemon/cmd: fix a couple of func doc string"

**Comment by cuishuang** [comment]
> @cuishuang thanks for the PR and good catch.
> 
> Could you please rephrase the commit message and PR title to something a tad more descriptive? e.g. "daemon/cmd: fix a couple of func doc string"

Of course！Done

**Comment by kaworu** [comment]
@cuishuang Thanks for the update, please change the commit message as well, you can do it with

```console
% git commit --amend
% git push --force-with-lease
```

**Comment by cuishuang** [comment]
> @cuishuang Thanks for the update, please change the commit message as well, you can do it with
> 
> ```
> % git commit --amend
> % git push --force-with-lease
> ```

Thanks!  Done

**Review by thorn3r — APPROVED** [review]

**Comment by kaworu** [comment]
[**generate-k8s-api** CI failure](https://github.com/cilium/cilium/actions/runs/4771018567/jobs/8604522276?pr=25030) is unrelated to the patch (opened https://github.com/cilium/cilium/pull/25192 to workaround the issue), all other checks are green and reviews in (no need for a full CI run) so marking as `ready-to-merge`.

**Pull request merged**
