### PR TITLE
v1.4 backports 19 01 25

### PR DESCRIPTION
**Pull request by jrfastab**
PR:
#6692 
#6758 
#6774 
#6771 
#6768 
#6767 
#6713 
#6763 
#6725 
#6766 
#6764  

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6784)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
K8s 1.8 tests failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9377/execution/node/80/log/ 

```
23:05:32     k8s1-1.8:   Cannot initiate the connection to download.docker.com:443 (2600:9000:2001:4e00:3:db06:4200:93a1). - connect (101: Network is unreachable) Cannot initiate the connection to download.docker.com:443 (2600:9000:2001:7000:3:db06:4200:93a1). - connect (101: Network is unreachable) Cannot initiate the connection to download.docker.com:443 (2600:9000:2001:3600:3:db06:4200:93a1). - connect (101: Network is unreachable) Cannot initiate the connection to download.docker.com:443 (2600:9000:2001:1000:3:db06:4200:93a1). - connect (101: Network is unreachable) Cannot initiate the connection to download.docker.com:443 (2600:9000:2001:fc00:3:db06:4200:93a1). - connect (101: Network is unreachable) Cannot initiate the connection to download.docker.com:443 (2600:9000:2001:a200:3:db06:4200:93a1). - connect (101: Network is unreachable) Cannot initiate the connection to download.docker.com:443 (2600:9000:2001:2c00:3:db06:4200:93a1). - connect (101: Network is unreachable) Cannot initiate the connection to download.docker.com:443 (2600:9000:2001:5200:3:db06:4200:93a1). - connect (101: Network is unreachable)
23:05:32     k8s1-1.8: Hit:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
23:05:32     k8s1-1.8: Hit:6 http://security.ubuntu.com/ubuntu bionic-security InRelease
23:05:32     k8s1-1.8: Hit:7 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
23:05:32     k8s1-1.8: Hit:8 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
23:05:35     k8s1-1.8: Reading package lists...
23:05:36     k8s1-1.8: E
23:05:36     k8s1-1.8: : 
23:05:36     k8s1-1.8: The repository 'https://download.docker.com/linux/ubuntu bionic Release' no longer has a Release file.
```

Not a Cilium issue.

I tried provisioning the K8s VMs locally with this very branch and it worked OK, indicating that the issue was due to network connectivity on the packet.net infrastructure we are using.

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
