### PR TITLE
Remove logstash and fluentd integration

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6516)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]
I haven't seen anyone use this integration at all, but how should we approach removing functionality like this in the future that end-users may be consuming? Now that fluentd integration is removed, the log-driver instantiation will fail, which will cause agent bootstrap to fail.

**Comment by tgraf** [comment]
> I haven't seen anyone use this integration at all, but how should we approach removing functionality like this in the future that end-users may be consuming? Now that fluentd integration is removed, the log-driver instantiation will fail, which will cause agent bootstrap to fail.

I think we should differ between well-documented and known to be used functionality and functionality that we are not aware of to have users. We can always revert something worst case but removing will only get harder and I'd rather remove it now than later.

**Comment by ianvernon** [comment]
@tgraf makes sense, I agree.

**Pull request merged**
