### PR TITLE
examples/kubernetes: bump cilium-etcd-operator to v2.0.3

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6436)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by raybejjani** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Comment by ianvernon** [comment]
@aanm maybe this is failing because of https://github.com/cilium/cilium-etcd-operator/commit/c15b9b2c1276674325d8104cc09143c49682aea3 ? This is the only notable change between 2.0.2 and 2.0.3. I'm not able to discern much from the CI logs, as the failed tests don't collect all the status of all of the pods (including etcd-operator).

**Comment by aanm** [comment]
@ianvernon it was failing because I didn't build the image tag on docker hub :man_facepalming:

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
@aanm better that than a code issue!

**Pull request merged**
