### PR TITLE
v1.1 backports: 09-05-18

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:

* #5388
* #5400 (required fixing several merge conflicts - @tgraf please review carefully)
* #5458
* #5482
* #5483 (required fixing merge conflicts - @rlenglet @tgraf please review)
* #5403
* #5502 
* #5495 
* #5469 (required fixing merge conflicts - was fairly trivial, though)

*NOT* backported:

* #5291 - I didn't do this because @jrfastab said it was causing flakiness. I can try this separately as its own PR to try to isolate the issue and fix it in the v1.1 branch after this PR is merged.

Signed-off by: Ian Vernon <ian@cilium.io.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5487)

### CODE REVIEW

**Comment by aanm** [comment]
I thought me and @joestringer were backporters this week? :thinking:

**Comment by ianvernon** [comment]
Did things get shuffled around? I read the page a few days ago and could have sworn I was backporter for this week, but you're right, looks like things got changed up (or I just misread the page). Sorry about that.

**Review by rlenglet — APPROVED** [review]

**Review by tgraf — CHANGES_REQUESTED** [review]
The backport is not incorrect but it contains the following now dead code which can be removed in the last commit.

```
 	createdPolicyMap := false

```

and

```
	 			if createdPolicyMap {
 				epLogger.Debug("removing endpoint PolicyMap")	 				epLogger.Debug("removing endpoint PolicyMap")
 				os.RemoveAll(e.PolicyMapPathLocked())	 				os.RemoveAll(e.PolicyMapPathLocked())
 				e.PolicyMap = nil	 				e.PolicyMap = nil
 			}	 			}
```

can be removed

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by tgraf** [comment]
Do we know which of the tests above are reliable in the 1.1 branch?

**Comment by ianvernon** [comment]
@tgraf I'd probably only go with the 'Cilium-Ginkgo-Tests'. I can investigate the failures of the other branches if you like.

**Comment by ianvernon** [comment]
The tests failed due to infrastructural problems (e.g. connecting to GitHub) which are not related to the changes here. I think we are good to merge.

**Comment by tgraf** [comment]
Thanks for looking into the failures

**Pull request merged**
