### PR TITLE
bpf: Send packet drop notify for ipv6 lb nat mode failures.

### PR DESCRIPTION
**Pull request by hzhou8**
Same change for ipv4 was added in commit 8d575af1b8. This patch ensures
the consistent behavior for ipv6.

Signed-off-by: Han Zhou <hzhou8@ebay.com>

### CODE REVIEW

**Review by borkmann — APPROVED** [review]
LGTM, thanks for the follow-up!

**Comment by borkmann** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]

**Comment by borkmann** [comment]
retest-4.9

**Comment by borkmann** [comment]
retest-net-next

**Comment by borkmann** [comment]
retest-gke

**Comment by pchaigno** [comment]
We backported the previous PR to v1.8 and v1.9; I think we should do the same here. I added labels.

**Pull request merged**
