### PR TITLE
Add externalTrafficPolicy=Local CI tests

### LINKED ISSUE #9284: kube-proxy NodePort externalTrafficPolicy=Local is broken
@olemarkus has reported that the kube-proxy NodePort's `externalTrafficPolicy=Local` is broken on `v1.6`. By broken, we mean that the source IP addr gets SNAT'ed by the `cilium_host` IP addr instead of the original source IP addr being preserved.

The fix for `v1.5.7` - https://github.com/cilium/cilium/pull/8944 (not backported to `v1.6`).

### PR DESCRIPTION
**Pull request by brb**
This PR:

* Creates the `outside-no-masq` network and attaches the `client-from-outside` container to the network. The former is the Docker network with masquerading being disabled. The network (and the container) is created only on the "k8s1" host, as we want to avoid MASQ in the `externalTrafficPolicy=Local` test which checks for a real source IP addr of the client.
* Adds a test for `externalTrafficPolicy=Local` (for kube-proxy) which checks whether a source IP address of a client is preserved (not MASQ'd).
* Changes the `cilium-demo-httpd` image to the `echoserver`, as the latter returns a client IP addr which is used by the test ^^.

/cc @gandro

```release-note
Add tests for a service annotated with externalTrafficPolicy=Local
```

Fix #9284.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9728)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
The CI tests are failing because of the `80 -> 8080` port change of the `zgroup=testDS` pods.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by nebril** [comment]
This test will be hard to run on eks, but it's good to have it.

**Comment by Antiarchitect** [comment]
Waiting for 1.7.0

**Comment by brb** [comment]
@Antiarchitect with or without kube-proxy?

**Comment by Antiarchitect** [comment]
> @Antiarchitect with or without kube-proxy?

@brb Currently with kube-proxy. (K8s provisioning is via Puppet module, so I can't easily turn off kube-proxy)

**Pull request merged**
