### PR TITLE
Test: Alleviate the WaitForPods constrains about terminated pods.

### PR DESCRIPTION
**Pull request by eloycoto**
This commits will allow pods that are in terminated state to clean
meanwhile some pods are installed. The main reason to allow this
behaviour is that nowadays we use ExpectAllPodsTerminated in the
AfterAll functions and this behaviour is not longer normal.

This change will return false for WaitForPods, but will not block the
test at all.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7537)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11134/

**Comment by ianvernon** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by ianvernon** [comment]
test-me-please (Istio Join EP issue https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11209/)

**Comment by eloycoto** [comment]
test-me-please

**Pull request merged**
