### PR TITLE
v1.13 backports 2023-03-01

### PR DESCRIPTION
**Pull request by sayboras**
- [ ] #23091 -- bpf: Fix broken remote-node identity classification (@ysksuzuki)
 - [x] #23469 -- bpf: Fix usage of tunnel map structs (@pchaigno)
 - [x] #23441 -- helm: Add SA automount configuration (@sayboras)
 - [x] #23915 -- agent: dump stack on stale probes (@squeed)
 - [x] #23499 -- watchers: endpointsync can manage already owned CiliumEndpoints. (@tommyp1ckles)
 - [x] #23443 -- helm: Add pod and container security context (@sayboras)
 - [ ] #24029 -- Update signature verification docs for Sigstore 2.0 (@jedsalazar)
 - [x] #23745 -- kvstore: prevent deletion delay for node-unrelated events   (@giorio94)
 - [x] #24012 -- docs: Fix the dead link to Mellanox performance tuning guide (@gentoo-root)
 - [ ] #23785 -- clustermesh: correctly release allocator references for GC (@oblazek)
 - [ ] #23928 -- kvstore: add clusterName suffix to session controllers (@oblazek)
 - [ ] #23605 -- Fix operator crash race condition for CES identity map concurrent read/write (@dlapcevic)
 - [x] #24030 -- IPsec: Remove `IP_POOLS` logic (@pchaigno)
     - Minor conflicts on almost all commits, some major.

Skipped due to conflicts:

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 23469 23441 23915 23499 23443 24029 23745 24012 24030 23785 23928 23605; do contrib/backporting/set-labels.py $pr done 1.13; done
```

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
My commits look good. Thanks!

**Review by gentoo-root — APPROVED** [review]
Approved for my commit.

**Comment by ysksuzuki** [comment]
It seems that #23091 is not included

**Comment by pchaigno** [comment]
> It seems that #23091 is not included

@ysksuzuki Should we fixed now. Thanks for reporting!

**Comment by pchaigno** [comment]
/test-backport-1.13

**Comment by sayboras** [comment]
> It seems that #23091 is not included

Sorry about this, the concern we had before was resolved, so it will be part of the next round.

**Review by squeed — APPROVED** [review]

**Comment by oblazek** [comment]
my commits lgtm

**Comment by pchaigno** [comment]
/test-backport-1.13

**Comment by pchaigno** [comment]
I've tested the IPsec backports on 3-nodes GKE and EKS clusters with the connectivity tests.

**Review by pchaigno — APPROVED** [review]

**Comment by sayboras** [comment]
/test-1.21-4.9

**Pull request merged**
