### PR TITLE
Envoy: Use an image with injection fix.

### PR DESCRIPTION
**Pull request by jrajahalme**
Cilium network filter failed to call back to proxylib when the OnData
call returned with a full inject buffer. Use a newer Envoy image that
fixes this.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8047)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Hit CI flakes, testing again.

**Comment by tgraf** [comment]
Unit test failure is unrelated:
```
FAIL: <autogenerated>:1: IdentityAllocatorEtcdSuite.TestLocalAllocationr
allocation_test.go:349:
    // KV-store still holds on to the key, so it is not deleted yet via KV-store events
    // This may be racy, as timing here depends on scheduling.
    c.Assert(owner.GetIdentity(id.ID), checker.DeepEquals, lbls1.LabelArray())
... obtained labels.LabelArray = labels.LabelArray(nil) ("[]")
... expected labels.LabelArray = labels.LabelArray{labels.Label{Key:"192.0.2.3/32", Value:"", Source:"cidr"}} ("[cidr:192.0.2.3/32]")
... Unified diff:
--- obtained
+++ expected
@@ -1 +1,3 @@
-labels.LabelArray(nil)
+labels.LabelArray{
+    {Key:"192.0.2.3/32", Value:"", Source:"cidr"},
+}
```

Filed https://github.com/cilium/cilium/issues/8049

**Comment by tgraf** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
