### PR TITLE
v1.13 backports 2023-03-28

### PR DESCRIPTION
**Pull request by tklauser**
- [x] #22980 -- bpf,test: Fixed bugs when running BPF tests on older kernels (@dylandreimerink)                                                                                                                                                   
- [x] #23281 -- bpf_test: use bpf.LoadCollection, print full verifier error logs (@ti-mo)
- [x] #23351 -- bpf/tests: fix mac addresses definitions in egressgw test (@jibi)
- [ ] #24469 -- bpf/test: Add unit test to check whether netpol drops result in metric counter increament (@brb)
 - [x] #24339 -- Correctly configure extra SANs for the clustermesh API server certificate when generated through certgen (@giorio94)
 - [x] #24546 -- bgp: extract exportPodCIDRReconciler logic into a generic function (@jibi)
 - [x] #23631 -- hubble-ui: allow ingress from non root `/` urls (@geakstr)
 - [x] #24557 -- pkg: add missing xfrm-no-track rules from ipv6 (@jschwinger233)
 - [x] #24569 -- test: Update 1.26 k8s version (@sayboras)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 22980 23281 23351 24469 24339 24546 23631 24577 24569; do contrib/backporting/set-labels.py $pr done 1.13; done
```

Skipped:

 - #24288 -- Install fib rules and routes with proto kernel to avoid systemd messing with them (@NikAleksandrov)
   - Caused build failures on 4.9 kernel: https://github.com/cilium/cilium/pull/24607#issuecomment-1490522379 needs manual backport
 - #24577 -- datapath/linux/route: fix CI expectations for rule string format (@NikAleksandrov)
    - Fix for #24288 which was dropped.
  - #24645 -- daemon: ignore EEXIST on NodeEnsureLocalIPRule (@tklauser)
    - Fix for #24288 which was dropped.

### CODE REVIEW

**Review by NikAleksandrov — APPROVED** [review]

**Comment by tklauser** [comment]
/test-backport-1.13

**Review by sayboras — APPROVED** [review]
Looks good for my changes, thanks a lot 🎖️

**Review by geakstr — APPROVED** [review]

**Comment by geakstr** [comment]
Thanks Tobias!

**Review by giorio94 — APPROVED** [review]
Thanks!

**Review by jschwinger233 — APPROVED** [review]

**Comment by tklauser** [comment]
Blocked on #24611

**Comment by tklauser** [comment]
Looks like the 4.9 Jenkins jobs failed with cilium pods crash looping and the following message in the logs:

```
2023-03-28T18:18:37.228913131Z level=error msg=\"Start hook failed\" error=\"daemon creation failed: error while initializing daemon: failed to ensure local IP rules: could not replace IPv4 local rule: file exists\" function=\"cmd.newDaemonPromise.func1 (daemon_main.go:1677)\" subsys=hive
```

Looks like https://github.com/cilium/cilium/pull/24288 is the culprit here. Not sure what to do about this. Is there anything different in the 4.9 VM images than in the other ones wrt. ip rules? @NikAleksandrov could you have a look?

**Comment by NikAleksandrov** [comment]
> Looks like the 4.9 Jenkins jobs failed with cilium pods crash looping and the following message in the logs:
> 
> ```
> 2023-03-28T18:18:37.228913131Z level=error msg=\"Start hook failed\" error=\"daemon creation failed: error while initializing daemon: failed to ensure local IP rules: could not replace IPv4 local rule: file exists\" function=\"cmd.newDaemonPromise.func1 (daemon_main.go:1677)\" subsys=hive
> ```
> 
> See e.g. https://jenkins.cilium.io/job/Cilium-PR-K8s-1.18-kernel-4.9/2580/
> 
> Presumably https://github.com/cilium/cilium/pull/24288 is the culprit here. Not sure what to do about this. Is there anything different in the 4.9 VM images than in the other ones wrt. ip rules? @NikAleksandrov could you have a look?

@tklauser will do and see how we can fix it

**Review by dylandreimerink — APPROVED** [review]

**Comment by tklauser** [comment]
> > Looks like the 4.9 Jenkins jobs failed with cilium pods crash looping and the following message in the logs:
> > ```
> > 2023-03-28T18:18:37.228913131Z level=error msg=\"Start hook failed\" error=\"daemon creation failed: error while initializing daemon: failed to ensure local IP rules: could not replace IPv4 local rule: file exists\" function=\"cmd.newDaemonPromise.func1 (daemon_main.go:1677)\" subsys=hive
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > See e.g. https://jenkins.cilium.io/job/Cilium-PR-K8s-1.18-kernel-4.9/2580/
> > Presumably #24288 is the culprit here. Not sure what to do about this. Is there anything different in the 4.9 VM images than in the other ones wrt. ip rules? @NikAleksandrov could you have a look?
> 
> @tklauser will do and see how we can fix it

As discussed on Slack, I've added an additional commit https://github.com/cilium/cilium/pull/24607/commits/bb0642723774d31d2af366344c0ec03a976a6642 ignoring `EEXIST` on `linuxdatapath.NodeEnsureLocalIPRule` in order to fix CI on 4.9 (that kernel doesn't support fib rule protocol attribute).

**Review by ti-mo — APPROVED** [review]
My commits look good, thanks. :+1:

**Review by julianwiedmann — APPROVED** [review]

**Comment by tklauser** [comment]
/test-backport-1.13

**Comment by jibi** [comment]
I don't think #23351 should be backported to v1.13, as the commit that it's fixing is not in v1.13 as well (why was it marked for backport?)

**Comment by tklauser** [comment]
> I don't think #23351 should be backported to v1.13, as the commit that it's fixing is not in v1.13 as well (why was it marked for backport?)

I picked it up because I had to pick up https://github.com/cilium/cilium/pull/23281 for 0e3b0bbd3fdfec427f509d735185884401093773 to fix another issue in a unit test introduced by https://github.com/cilium/cilium/pull/24469. Picking #23281 lead to a failure in the egressgw tests which I figured were fixed by #23351.

I guess the alternative would be to drop #24469 (and thus also #23281 and #23351).

**Review by jibi — APPROVED** [review]

**Comment by tklauser** [comment]
It looks like there's another issue with https://github.com/cilium/cilium/pull/24288 on kernel 4.9 even with https://github.com/cilium/cilium/pull/24645 in place: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.24-kernel-4.9/100/testReport/junit/Suite-k8s-1/24/K8sDatapathConfig_Transparent_encryption_DirectRouting_Check_connectivity_with_transparent_encryption_and_direct_routing_with_bpf_host/

This seems to be failing in [`(*linuxNodeHandler).replaceHostRules()`](https://github.com/cilium/cilium/blob/8bbe9247f02c40c61cc52e7473a0b6d50e732fe1/pkg/datapath/linux/node.go#L1236). I think I'm going to drop https://github.com/cilium/cilium/pull/24288 and https://github.com/cilium/cilium/pull/24645 from this backport PR in order to get it into a mergeable state by the end of the week.

@NikAleksandrov could you please look into what else is needed to successfully backport https://github.com/cilium/cilium/pull/24288?

**Comment by tklauser** [comment]
/test-backport-1.13

**Comment by NikAleksandrov** [comment]
@tklauser thank you for giving it a try, I'll take care of the backport

**Comment by tklauser** [comment]
/test-1.19-4.9

**Pull request merged**
