### PR TITLE
k8s: update k8s libraries to 1.19.8

### PR DESCRIPTION
**Pull request by aanm**
also update tested versions to 1.17.17 and 1.18.16

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.9

**Review by christarazi — APPROVED** [review]

**Comment by aanm** [comment]
test-gke

**Comment by aanm** [comment]
test-net-next

**Review by jibi — APPROVED** [review]

**Comment by aanm** [comment]
test-gke

**Comment by aanm** [comment]
test-1.12-net-next

**Comment by aanm** [comment]
test-gke

**Comment by nebril** [comment]
test-gke

**Comment by aanm** [comment]
test-1.12-net-next

**Comment by aanm** [comment]
previous GKE failures https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/4424

**Comment by aanm** [comment]
test-gke

**Comment by aanm** [comment]
the GKE tests are failing in the v1.9 branch https://jenkins.cilium.io/view/Cilium-v1.9/job/cilium-v1.9-k8s-gke

**Pull request merged**
