### PR TITLE
[v1.14] docs: egress masquerade selector

### PR DESCRIPTION
**Pull request by nbusseneau**
This is a custom backport of #36076.

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Comment by gandro** [comment]
/test-backport-1.14

**Comment by gandro** [comment]
/test-backport-1.14

**Comment by jrajahalme** [comment]
/test-backport-1.14

**Comment by gandro** [comment]
CI is stuck on waiting for the skipped conformance test. Force merging, as everything else is green.

**Pull request merged**
