### PR TITLE
v1.6 backport for docs: re-design cilium docs theme

### PR DESCRIPTION
**Pull request by joestringer**
Backport the new docs theme.
* #11803
* #12002 
* #12010 

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 11803 12002 12010; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by joestringer** [comment]
test-docs-please

**Comment by joestringer** [comment]
Failure needs fixing:

```
21:58:13  Successfully tagged cilium/docs-builder:latest
21:58:13  docker container rm -f docs-cilium >/dev/null 2>&1 || true
21:58:13  docker container run --rm -v $(pwd):/srv/ cilium/docs-builder /bin/bash -c 'make html'
21:58:13  /bin/sh: syntax error: unexpected word (expecting "do")
21:58:13  make: *** [Makefile:27: check-requirements] Error 2
21:58:14  Makefile:407: recipe for target 'test-docs' failed
21:58:14  make: *** [test-docs] Error 2
21:58:16  Terminated
```

**Comment by aanm** [comment]
same failure seen in https://github.com/cilium/cilium/pull/11992#issuecomment-643184331

**Comment by joestringer** [comment]
test-docs-please

**Pull request merged**
