### PR TITLE
k8s: fix clean state InitContainer permissions

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>
This PR is needed for https://github.com/cilium/cilium/pull/5330

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5344)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
failed because of the kafka test

**Comment by aanm** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
