### PR TITLE
Fix operator startup delay caused by leader election lease not being released correctly

### PR DESCRIPTION
**Pull request by giorio94**
The leader election logic of the operator is currently executed in a separate goroutine started by an OnStart hook, and relies on a context (canceled by the respective OnStop hook) for shutting down. Once this occurs, it will automatically release the lease, to allow the immediate election of a new leader. Yet, we do not explicitly wait for this operation to complete, and the operator might stop before the lease is actually released, introducing a ~15 seconds delay for the next election.

This PR fixes this by introducing a WaitGroup to explicitly wait for the leader election loop to terminate before continuing with the shutdown process.

```release-note
Fix operator startup delay caused by leader election lease not being released correctly
```

### CODE REVIEW

**Comment by giorio94** [comment]
kubernetes-e2e hit https://github.com/cilium/cilium/issues/24622

**Comment by giorio94** [comment]
Travis CI hit unrelated flake https://github.com/cilium/cilium/issues/24491

**Comment by giorio94** [comment]
Rebased onto master since egressgw tests were failing due to https://github.com/cilium/cilium/pull/24835 having been merged.

**Comment by joamaki** [comment]
> The leader election logic of the operator is currently executed in a separate goroutine started by an OnStart hook, and relies on a context (canceled by the respective OnStop hook) for shutting down.

This is not true. The start context is only valid during the start and is cancelled either due to timeout or when the start is finished. It must not be used outside the lifetime of the Start hook.

**Review by joamaki — APPROVED** [review]
Thanks!

**Comment by michi-covalent** [comment]
thank you mlh

**Pull request merged**
