### PR TITLE
v1.14 Backports 2023-10-30

### PR DESCRIPTION
**Pull request by pippolo84**
* [x] #28465 (@pippolo84)
  - :warning: conflicts due to `cidr.go` moved in main branch
 * [x] #27923 (@mhofstetter)
 * [x] #28663 (@learnitall)
  - :warning: conflicts due to `resource_ctors.go` moved in main branch
 * [x] #28767 (@giorio94)
 * [x] #28789 (@aanm)
 * [x] #28790 (@pchaigno)
 * [x] #28697 (@nebril)
 * [x] #28788 (@pippolo84)
  - :warning: conflicts due to `cidr.go` moved in main branch
 * [x] #28857 (@julianwiedmann)
  - :warning: minor conflicts due to `nat.IPv4` constant missing

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 28465 27923 28663 28767 28789 28790 28697 28788 28857
```

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
My commit looks good. Thanks!

**Review by mhofstetter — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by pippolo84** [comment]
@learnitall @julianwiedmann please review your commits very carefully, I hit quite a number of conflicts during the backporting.

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Comment by pippolo84** [comment]
/test-backport-1.14

**Review by nebril — APPROVED** [review]
My changes LGTM

**Comment by julianwiedmann** [comment]
Peeked at the related [ci-conformance fail](https://github.com/cilium/cilium/actions/runs/6694344171/job/18187528883)


```
--- FAIL: Test (0.00s)
    --- FAIL: Test/CTMapPrivilegedTestSuite (0.00s)
        --- FAIL: Test/CTMapPrivilegedTestSuite/TestCtGcDsr (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xc783f3]
```



Looks like we need below change for 1.14. Let me know if this is getting too involved and you would prefer a separate backport :).

```
diff --git a/pkg/maps/ctmap/ctmap_privileged_test.go b/pkg/maps/ctmap/ctmap_privileged_test.go
index f5c3fec337..d8b206b005 100644
--- a/pkg/maps/ctmap/ctmap_privileged_test.go
+++ b/pkg/maps/ctmap/ctmap_privileged_test.go
@@ -213,9 +213,9 @@ func (k *CTMapPrivilegedTestSuite) TestCtGcTcp(c *C) {
        defer natMap.Map.Unpin()
 
        ctMapName := MapNameTCP4Global + "_test"
-       mapInfo[mapTypeIPv4TCPGlobal] = mapAttributes{
-               natMap: natMap, natMapLock: mapInfo[mapTypeIPv4TCPGlobal].natMapLock,
-       }
+       setupMapInfo(mapTypeIPv4TCPGlobal, ctMapName,
+               &CtKey4Global{}, int(unsafe.Sizeof(CtKey4Global{})),
+               100, natMap)
 
        ctMap := newMap(ctMapName, mapTypeIPv4TCPGlobal)
        err = ctMap.OpenOrCreate()
@@ -323,9 +323,9 @@ func (k *CTMapPrivilegedTestSuite) TestCtGcDsr(c *C) {
        defer natMap.Map.Unpin()
 
        ctMapName := MapNameTCP4Global + "_test"
-       mapInfo[mapTypeIPv4TCPGlobal] = mapAttributes{
-               natMap: natMap, natMapLock: mapInfo[mapTypeIPv4TCPGlobal].natMapLock,
-       }
+       setupMapInfo(mapTypeIPv4TCPGlobal, ctMapName,
+               &CtKey4Global{}, int(unsafe.Sizeof(CtKey4Global{})),
+               100, natMap)
 
        ctMap := newMap(ctMapName, mapTypeIPv4TCPGlobal)
        err = ctMap.OpenOrCreate()
@@ -413,9 +413,9 @@ func (k *CTMapPrivilegedTestSuite) TestCtGcLegacyDsr(c *C) {
        defer natMap.Map.Unpin()
 
        ctMapName := MapNameTCP4Global + "_test"
-       mapInfo[mapTypeIPv4TCPGlobal] = mapAttributes{
-               natMap: natMap, natMapLock: mapInfo[mapTypeIPv4TCPGlobal].natMapLock,
-       }
+       setupMapInfo(mapTypeIPv4TCPGlobal, ctMapName,
+               &CtKey4Global{}, int(unsafe.Sizeof(CtKey4Global{})),
+               100, natMap)
```

**Comment by pippolo84** [comment]
> Looks like we need below change for 1.14. Let me know if this is getting too involved and you would prefer a separate backport :).

Thanks @julianwiedmann . I've applied the changes, let's see how it goes.

**Comment by pippolo84** [comment]
/test-backport-1.14

**Review by julianwiedmann — APPROVED** [review]
lgtm, and the current CI fails look unrelated :crossed_fingers:. Thank you!

**Review by learnitall — APPROVED** [review]
Looks good for my PR, thank you!

**Comment by pippolo84** [comment]
Should wait for https://github.com/cilium/cilium/pull/28940 to be merged first, in order to fix CI.

**Comment by pippolo84** [comment]
Force-pushed to remove commit already backported [here](https://github.com/cilium/cilium/pull/28940). Description has been updated as well.

**Comment by pippolo84** [comment]
/test-backport-1.14

**Review by squeed — APPROVED** [review]

**Review by squeed — APPROVED** [review]

**Review by squeed — APPROVED** [review]

**Pull request merged**
