### PR TITLE
v1.7 backports 2020-11-25

### PR DESCRIPTION
**Pull request by aanm**
* #11133 -- Added support for JSON based logging (@mvisonneau)
 * #12395 -- Register logging flags with operator main cmd (@ungureanuvladvictor)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 11133 12395; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.7

**Comment by aanm** [comment]
retest-ginkgo

**Comment by aanm** [comment]
restart-ginkgo

**Comment by aanm** [comment]
restart-ginkgo

**Review by errordeveloper — APPROVED** [review]

**Pull request merged**
