### PR TITLE
k8s: Update libraries to 1.23.3

### PR DESCRIPTION
**Pull request by christarazi**
Signed-off-by: Chris Tarazi <chris@isovalent.com>

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Review by aanm — CHANGES_REQUESTED** [review]
the `test` directory, i.e. the `provision_k8s.sh` also needs an update.

**Review by aanm — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by christarazi** [comment]
/test-1.23-net-next

**Comment by christarazi** [comment]
CI passed overall (over 2 runs) and approving reviews. Ready to merge.

**Pull request merged**
