### PR TITLE
v1.8 backports 2020-06-03

### PR DESCRIPTION
**Pull request by tklauser**
* #11661 -- proxy: Keep DNS port allocated (@jrajahalme)
 * #11771 -- test: Wait for IPCache entries in testSessionAffinity (@brb)
 * #11758 -- ci: outer vm boot timeout was smaller than inner (@nebril)
 * #11775 -- test: retry fqdn requests, increase curl timeout (@nebril)
 * #11779 -- nodeinit: Fix for restarting kubenet managed pods (@dctrwatson)
 * #11773 -- eni: Fix node manager test (@errordeveloper)
 * #11714 -- Ensure endpoint validation occurs before initial regeneration (@tgraf)
 * #11786 -- azure/ipam: Fix nil dereference with logger (@christarazi)
 * #11694 -- bpf: more scalability improvements (@borkmann)
 * #11760 -- docs: add scalability report (@aanm)
 * #11804 -- fix(datarace): Fix possible nil pointer dereference (@sayboras)
 * #11759 -- policy: Fix enforcement status for host endpoint (@pchaigno)
 * #11598 -- loader: Attach bpf_host to cilium_net from Golang (@pchaigno)
 * #11776 -- test: disable fqdn restart test (@nebril)
 * #11798 -- ci: fix timeout vagrant up timeout (@nebril)
 * #11715 -- connectivity-check: Do not perform hostport in standard check (@tgraf)
 * #11762 -- test: Add simple retries for flaky Helm operations (@christarazi)
 * #11812 -- bpf: Fix race when accessing m.fd (@tgraf)
 * #11822 -- docs: add word to misspelled list (@aanm)
 * #11816 -- cilium: downgrade kernel_hz clock probe warning to info message (@borkmann)
 * #11815 -- datapath: Silent iptables removal on first init (@tgraf)
 * #11818 -- test: Fix and re-enable test reliant on managed etcd (@errordeveloper)
 * #11784 -- docker: add hubble CLI binary to the base cilium image (@Rolinh)
 * #11817 -- test: use local copy of Cilium Star Wars Demo (@tklauser)
 * #11796 -- ci: retry docker build in jenkins (@nebril)
 * #11839 -- Misc docs index & development section improvements (@joestringer)
 * #11835 -- hubble/observer: increment 'numObservedFlows' atomically (@aanm)
 * #11823 -- agent: Fix data race when accessing d.monitorAgent (@tgraf)
 * #11806 -- Remove hubble-cli sub-chart  (@seanmwinn)
 * #11831 -- eni: Fix potential deadlock (@christarazi)
 * #11643 -- Adding connectivity test to troubleshooting doc (@jedsalazar)
 * #11814 -- ci: run lscpu at end of build (@nebril)
 * #11840 -- docs: Parameterize READTHEDOCS_VERSION (@joestringer)
 * #11615 -- test(datarace): Fix datarace issue in spanstat.go (@sayboras)
 * #11811 -- Update Go to 1.14.4 (@tklauser)
 * #11819 -- datapath: Accept proxy traffic if enable-endpoint-routes are enabled (@tgraf)
 * #11833 -- pkg/ipcache: create a GetK8sMetadata for public access (@aanm)
 * #11834 -- pkg/k8s: use node name from pkg/node instead of env variable (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 11661 11771 11758 11775 11779 11773 11714 11786 11694 11760 11804 11759 11598 11776 11798 11715 11762 11812 11822 11816 11815 11818 11784 11817 11796 11839 11835 11823 11806 11831 11643 11814 11840 11615 11811 11819 11833 11834; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by tklauser** [comment]
never-tell-me-the-odds

**Review by borkmann — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
:+1: for my changes. Thanks @tklauser!

**Comment by tklauser** [comment]
test-backport-1.8

**Comment by errordeveloper** [comment]
My commit looks good!

**Comment by tklauser** [comment]
test-backport-1.8

**Review by christarazi — APPROVED** [review]
LGTM for my changes

**Review by brb — CHANGES_REQUESTED** [review]
I don't see my commits for #11678 and #11739. Were their changes overwritten by other commits, so they were dropped?

**Comment by tklauser** [comment]
> I don't see my commits for #11678 and #11739. Were their changes overwritten by other commits, so they were dropped?

They were already backported before (see commits 4fa26a4105eb2166f05cf198f494273e338575df and 1b95d351eb76ac2f21a26c29765d86fb7ecda9f6) but weren't marked as `backport-done/1.8` thus the script picked them up for the PR description.

**Review by brb — APPROVED** [review]

**Comment by tklauser** [comment]
Not sure why `Cilium-Ginkgo-Tests ` is timing out, see slack thread here: https://cilium.slack.com/archives/C7PE7V806/p1591198945064700

Otherwise this should be good to merge.

**Comment by nebril** [comment]
https://github.com/cilium/cilium/pull/11858 wasn't marked for backport, this is what caused `Cilium-Ginkgo-Test` to fail. These tests are run in separated pipelines too and they passed, marking this as ready-to-merge

**Pull request merged**
