### PR TITLE
Readme: Updates for release 1.15.4, 1.14.10, 1.13.15

### PR DESCRIPTION
**Pull request by asauber**
Readme: Updates for release 1.15.4, 1.14.10, 1.13.15

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]
Thanks!

**Review by ti-mo — APPROVED** [review]
Looks like `stable.txt` isn't in CODEOWNERS, should it be? cc @aanm

**Comment by aanm** [comment]
> Looks like `stable.txt` isn't in CODEOWNERS, should it be? cc @aanm

@ti-mo it is in https://github.com/cilium/cilium/blob/5aec7f58af0e57f93d5fa65f6e84a5e45609aac0/CODEOWNERS#L543

**Comment by ti-mo** [comment]
> > Looks like `stable.txt` isn't in CODEOWNERS, should it be? cc @aanm
> 
> @ti-mo it is in https://github.com/cilium/cilium/blob/5aec7f58af0e57f93d5fa65f6e84a5e45609aac0/CODEOWNERS#L543

Hmm, why assign things to tophat? Shouldn't it get assigned to people working on releases? TH is a revolving door, their reviews go stale after a week (and already have enough stuff to rubber-stamp).

**Pull request merged**
