### PR TITLE
helm: Use variable for spire config container image

### LINKED ISSUE #27282: Spire helm chart - static busy box image
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Helm chart issue:
The busybox image in both the statefulset and daemonset templates in the spire-agent and spire-server are static (docker.io)
They should be represented in the values file so you can override them with (for instance) a private repository.

### Cilium Version

1.14

### Kernel Version

n/a

### Kubernetes Version

n/a

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by eegseth**
Previously, the busybox image used for configuring spire server and agent was hardcoded into the manifests.

This patch moves this image reference to the variable authentication.mutual.spire.install.init.image

Fixes: #27282

Signed-off-by: E Egseth endre@egseth.no

### CODE REVIEW

**Comment by eegseth** [comment]
Recreation of pr https://github.com/cilium/cilium/pull/27377 due to fubar branch.

Please add label needs-backport/1.14

**Review by kaworu — APPROVED** [review]
Patch LGTM. @meyskens how is this busybox image kept up-to-date? Should it be watched by Renovate bot?

**Comment by meyskens** [comment]
@kaworu we should, and same with spire images, the busybox was used before but also untracked. Will create an issue for us to look into fixing that for all dependency images we ship

**Review by meyskens — APPROVED** [review]
LGTM

**Review by sayboras — APPROVED** [review]
LGTM ✅

**Review by youngnick — APPROVED** [review]

**Comment by joestringer** [comment]
@eegseth The format for signoff is incorrect, see https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#developer-s-certificate-of-origin. Once you've configured git with your name + email, it should be enough to use `-s` to sign off the commits for DCO correctly.

Can you also please rebase against the upstream main branch and squash the commits all together? There is no need to include merge commits in the PR. Thanks!

**Comment by joestringer** [comment]
One of the test failures also says:

```
please run 'make -C install/kubernetes' and submit your changes
```

**Review by nbusseneau — APPROVED** [review]

**Comment by joestringer** [comment]
I see that you have created an additional squashed commit, referring various other unrelated changes. Could you please rebase the entire PR against the tip of main and squash all of the commits together so that there's just one commit with your intended changes? You should then be able to force-push that commit into this branch to override the changes here, and GitHub will present the PR as just requesting one new commit on top.

**Comment by joestringer** [comment]
I'm not entirely sure why, but the smoke tests are still requesting you to do `please run 'make -C install/kubernetes' and submit your changes`.

**Pull request closed without merging**
