### PR TITLE
pkg/bpf: update BPF_* constants as of Linux kernel 4.17-rc3

### PR DESCRIPTION
**Pull request by tklauser**
Add newly added constants from linux/bpf.h (as of Linux kernel
4.17-rc43) to pkg/bpf.

Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
CI is reporting:
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:312
Expected
    <*errors.errorString | 0xc420ab2550>: {
        s: "could not parse JSON from command \"kubectl exec -n kube-system cilium-fvlzb -- cilium endpoint get 3978 -o json\"",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Services.go:282
```

This seems unrelated to the contents of the PR, so I'll re-run the CI now.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
Is this ready to merge?

**Pull request merged**
