### PR TITLE
datapath: Store NodePort client MAC addr in LRU map

### PR DESCRIPTION
**Pull request by brb**
Previously, the NodePort datapath was doing a `fib_lookup` before sending a reply back to a client to determine a MAC addr of a nexthop to the client and a MAC addr of an egress iface (a native device).

Meanwhile, the kernel networking stack creates an ARP entry only when a packet is sent, but not received.

So, in the NodePort case, when a never seen before client sends a request, a receiving node does not create the ARP entry for the `CLIENT_IP => REQUEST_SMAC` mapping. This makes the `fib_lookup` to fail.

As a workaround, we create `NODEPORT_NEIGH{4,6} LRU` maps to store the mapping.

OT: happy to discuss the LRU map size.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8670)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failed: `Suite-k8s-1.10.K8sHealthTest checks cilium-health status between nodes`

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failed: `fatal: write error: No space left on device`

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failed:
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.10-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:420
Failure while waiting for all cilium endpoints to reach ready state
Expected
    <*helpers.SSHMetaError | 0xc003bfe360>: Error: context deadline exceeded
Extended info: 	Cilium Pod: cilium-j5kbd 	Endpoint: 292 	Identity: 12034	 State: ready
	Cilium Pod: cilium-j5kbd 	Endpoint: 415 	Identity: 4	 State: ready
	Cilium Pod: cilium-j5kbd 	Endpoint: 781 	Identity: 21948	 State: ready
	Cilium Pod: cilium-j5kbd 	Endpoint: 1005 	Identity: 101	 State: not-ready
	Cilium Pod: cilium-j5kbd 	Endpoint: 2294 	Identity: 101	 State: ready
	Cilium Pod: cilium-j5kbd 	Endpoint: 2750 	Identity: 100	 State: ready
	Cilium Pod: cilium-j5kbd 	Endpoint: 3473 	Identity: 102	 State: ready
	Cilium Pod: cilium-pmqvh 	Endpoint: 372 	Identity: 4	 State: ready
	Cilium Pod: cilium-pmqvh 	Endpoint: 653 	Identity: 101	 State: ready
	Cilium Pod: cilium-pmqvh 	Endpoint: 845 	Identity: 21948	 State: ready
	Cilium Pod: cilium-pmqvh 	Endpoint: 1428 	Identity: 12034	 State: ready


to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.10-gopath/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:170
```

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Pull request merged**
