### PR TITLE
bpf: Add VTEP redirection to complexity  tests

### PR DESCRIPTION
**Pull request by vincentmli**
ENABLE_VTEP was missing from the complexity tests in
bpf/complexity-tests.

Reported-by: Paul Chaignon <paul@cilium.io>
Signed-off-by: Vincent Li <v.li@f5.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
Add missing VTEP complexity tests
```

### CODE REVIEW

**Review by YutaroHayakawa — APPROVED** [review]

**Comment by vincentmli** [comment]
@YutaroHayakawa this PR is getting stale notification, time to merge? :)

**Comment by YutaroHayakawa** [comment]
Oh, I noticed I am the only reviewer for this PR, sorry. Let me mention @pchaigno just in case, but this is a trivial change and doesn't have any problem for merge I think.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
We need to run the Vagrant/Jenkins tests because test K8sVerifier uses those files.

**Comment by pchaigno** [comment]
Lots of end-to-end tests are failing because this branch is pretty old, but the changes here only affect K8sVerifier anyway and that test is not failing anywhere. So I think we're safe to merge.

**Pull request merged**
