### PR TITLE
Cleanup leftovers from node statuses in CNP/CCNP

### LINKED ISSUE #29590: Remove `skip-cnp-status-startup-clean` and CNP status
Follow-ups from https://github.com/cilium/cilium/issues/24503 :
- Remove `skip-cnp-status-startup-clean`: https://github.com/cilium/cilium/blob/2835b063800f7e98696c38e451016e5e9a0ab47b/operator/option/config.go#L72
- Remove CNP Status: https://github.com/cilium/cilium/blob/e6a55a021627d41c0779631e8e01faed4e5f31a3/pkg/k8s/apis/cilium.io/v2/cnp_types.go#L77
- Remove hidden option `legacy-turn-off-k8s-event-handover` https://github.com/cilium/cilium/blob/5ef0f107d64e64a422a65741d804b01cd3995545/pkg/option/config.go#L828

### LINKED ISSUE #32903: CI: TestControlPlane/CNPStatusNodesGC timed out
## CI failure

Hit on https://github.com/cilium/cilium/pull/32900
Link: https://github.com/cilium/cilium/actions/runs/9379774662/job/25825392709

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                                                                                          
┃   PANIC  package: github.com/cilium/cilium/test/controlplane • TestControlPlane/CNPStatusNodesGC   ┃                                                                                                          
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                                                                                                          
panic: test timed out after 10m0s                                                                                                                                                                               
running tests:                                                                                                                                                                                                  
	TestControlPlane (10m0s)                                                                                                                                                                                        
	TestControlPlane/CNPStatusNodesGC (10m0s) 
```

Attaching the stack trace, as too large to be pasted here: [stacktrace.txt](https://github.com/user-attachments/files/15580048/stacktrace.txt)

### PR DESCRIPTION
**Pull request by marseel**
Fixes: #29590
Fixes: #32903

```release-note
Removed Cilium Operator options `cnp-status-cleanup-burst` and `cnp-status-cleanup-qps`
```

### CODE REVIEW

**Review by christarazi — APPROVED** [review]
:broom:

**Review by nathanjsweet — APPROVED** [review]
Not a single line added. Noice!

**Pull request merged**
