### PR TITLE
Replace `integration_tests` build tag with `INTEGRATION_TESTS` env

### PR DESCRIPTION
**Pull request by ti-mo**
Similar to cilium/cilium#20769, remove the integration_tests build tag and gate integration tests using the INTEGRATION_TESTS env instead.

This makes sure all code can be built with a single `go build` or `go test`, without being aware of the existence of the build tag. Editor tooling will resume to function without additional configuration, and linters will see the code once again.

Omitted enabling integration tests in some examples if it wasn't relevant to what the example was trying to showcase.

```release-note
Replace integration_tests build tag with INTEGRATION_TESTS env
```

cc @oblazek

### CODE REVIEW

**Review by dylandreimerink — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Review by YutaroHayakawa — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Review by zacharysarah — APPROVED** [review]
LGTM from a docs perspective.

**Review by aanm — APPROVED** [review]

**Pull request merged**
