### PR TITLE
build(deps): Bump aws-sdk-v2 to official releases

### PR DESCRIPTION
**Pull request by sayboras**
### Description

This commit is to bump aws-sdk-v2 to official release v1.0.0.
Please refer to [1] for migration path, there is required change
in current codebase.

[1]: https://github.com/aws/aws-sdk-go-v2/releases

Signed-off-by: Tam Mach <sayboras@yahoo.com>

### Testing

Testing was done locally with `make docker-images-all`, will do a quick
round of testing in AWS if required next week. 

Note: Understand that we have dependabot, but I don't know if if it supports
for multiple modules together in the same PR :thinking: 

```release-note
build(deps): Bump aws-sdk-v2 to official releases
```

### CODE REVIEW

**Comment by tklauser** [comment]
@sayboras could you please rebase the PR on top of latest `master` to get the helm fixes for the failing GH action tests? I also think that a quick smoke on AWS would be good to verify nothing broke.

**Comment by sayboras** [comment]
test-me-please

**Comment by tklauser** [comment]
retest-net-next

**Comment by tklauser** [comment]
retest-gke

**Review by tklauser — APPROVED** [review]
Did a quick connectivity-check smoke-test on an EKS cluster, looks good :heavy_check_mark:

**Comment by sayboras** [comment]
> Did a quick connectivity-check smoke-test on an EKS cluster, looks good heavy_check_mark

Thanks for your help, I did once with eksctl as well, seems ok from my side.

**Comment by sayboras** [comment]
CI was successful for all, except https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/4188/. I will re-run only gke after rebase.

**Comment by sayboras** [comment]
retest-gke

**Review by ungureanuvladvictor — APPROVED** [review]

**Comment by tklauser** [comment]
All CI tests were green on the previous run. GH actions, Travis & GKE tests passed on this run and the PR was manually smoke-tested on EKS. Merging, thanks.

**Pull request merged**
