### PR TITLE
Move Cilium CRDs to special Helm directory for auto installation upon `helm install`

### PR DESCRIPTION
**Pull request by christarazi**
This PR doesn't add the CRDs to the `quick-install.yaml` and `experimental-install.yaml` because it would make them too big to be practical. The reason is because the CRDs contain validation which can be quite verbose.

Manually tested by deploying the following and ensuring that `kubectl get crds` shows Cilium CRDs as soon as the Helm install begins:

```diff
diff --git a/install/kubernetes/cilium/charts/agent/templates/daemonset.yaml b/install/kubernetes/cilium/charts/agent/templates/daemonset.yaml
index 8bd0374a2..f757b779a 100644
--- a/install/kubernetes/cilium/charts/agent/templates/daemonset.yaml
+++ b/install/kubernetes/cilium/charts/agent/templates/daemonset.yaml
@@ -53,6 +53,7 @@ spec:
 {{- else }}
       - args:
         - --config-dir=/tmp/cilium/config-map
+        - --skip-crd-creation
         command:
         - cilium-agent
         livenessProbe:
```

See commit msgs.

Updates: https://github.com/cilium/cilium/issues/12737

```release-note
Allow Helm to install Cilium CRDs instead of Operator, with Operator acting as a fallback in case Helm was unable to install CRDs
```

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
retest-net-next

**Review by sayboras — APPROVED** [review]
Just one note on below flag in helm 3, I feel like we need to document somewhere saying that this flag must not be set. Keen to hear your input.

The rest is LGTM :+1: 

```
      --skip-crds                    if set, no CRDs will be installed. By default, CRDs are installed if not already present
```

**Comment by aanm** [comment]
@sayboras that's a good point, how come when we are generating the template the CRDs are not created in the `quick-install.yaml`?

**Comment by sayboras** [comment]
> @sayboras that's a good point, how come when we are generating the template the CRDs are not created in the `quick-install.yaml`?

yes, I normally used the below flag to include crds in template. As far as I understand from PR description, we don't want to bundle crds in either `quick-install` or `experimential-install`.

```
      --include-crds                 include CRDs in the templated output
```

**Comment by aanm** [comment]
@sayboras oh ok, I think it's fine to leave it as is because we just don't want to have a huge `quick-install.yaml` but if the user runs `helm install` we want the CRDs to be installed (if they aren't already)

@christarazi did you test installing with helm on k8s 1.12?

**Comment by christarazi** [comment]
Update: This PR is failing on versions below 1.15, because Helm does not know how to install v1beta1 CRDs on versions of K8s that do not understand v1. See [this comment](https://github.com/cilium/cilium/issues/12737#issuecomment-701007713) for more info. Pinning and converting to draft mode to be picked up in the future.

**Comment by christarazi** [comment]
Obsoleted by https://github.com/cilium/cilium/issues/12737#issuecomment-856713156

**Pull request closed without merging**
