### PR TITLE
vagrant: bump box versions, again

### PR DESCRIPTION
**Pull request by tklauser**
The previous box version bump in commit bc9998f13343 ("vagrant: bump box
versions") did not include the Go 1.16 update, despite mentioning it in
the commit message.

This time update it to a box containing Go 1.16 for real.

Note that this also bumps the patch version for kernel 4.9 and 4.19 in
the VM images to 4.9.212 (see
https://github.com/cilium/packer-ci-build/pull/257) and 4.19.177,
respectively (see https://github.com/cilium/packer-ci-build/pull/256/).
The reason for this is that the old versions are no longer available
from https://kernel.ubuntu.com/~kernel-ppa/mainline

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by kkourt — APPROVED** [review]

**Comment by tklauser** [comment]
test-1.19-4.19

**Comment by tklauser** [comment]
test-1.20-4.9

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
4.19 tests are broken with the current image because it does contain a 4.15 kernel rather than a 4.19 kernel: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.19/4827

This is due to the micro version in use no longer being available from Ubuntu Kernel PPA. I've sent cilium/packer-ci-build#256 which should hopefully fix this. Once the new VM image is build, I'll bump the version in this PR.

The 4.19 tests seem broken because of  #15141

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
Same issue as https://github.com/cilium/cilium/pull/15129#issuecomment-787970496 for the 4.9 tests: the image was built without a 4.9 kernel being installed. I've sent cilium/packet-ci-build#257 with a fix.

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-1.19-4.19

**Pull request merged**
