### PR TITLE
1.2 backports 18-10-15

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:

* #5882 
* #5875

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5892)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
Upstream k8s tests failed due to timeout.

Build link: 
https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/778

```
20:43:56 Sending interrupt signal to process
20:43:56 Terminated
```

The tests themselves were running still.

**Comment by ianvernon** [comment]
NodePort test failure: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7265/

Looks related to: 
https://github.com/cilium/cilium/issues/5384

**Comment by ianvernon** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by ianvernon** [comment]
Needs rebase, will address shortly.

**Comment by ianvernon** [comment]
Prior build failed due to Kafka tests misbehaving: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7275/testReport/junit/k8s-1/7/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

This test has not been stable in v1.2 for some time :/

**Comment by ianvernon** [comment]
Rebased against v1.2 and running tests again.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
Hit the ring buffer problem:
```
$ grep -r "BUG" *cilium*.log
pod-kube-system-cilium-kgxw1-cilium-agent.log:2018-10-16T18:14:22.97571423Z level=error msg="BUG: Timeout while reading perf ring buffer: cpu: 1, Fd: 12, pagesize: 4096, npages: 64, lost: 1003, unknown: 0, state: [0 224 230 247 255 127 0 0 0 0 4 0 0 0 0 0 32 0 0 0 0 0 0 0]" subsys=cilium-node-monitor
pod-kube-system-cilium-kgxw1-cilium-agent.log:2018-10-16T18:15:17.496004783Z level=error msg="BUG: Timeout while reading perf ring buffer: cpu: 0, Fd: 11, pagesize: 4096, npages: 64, lost: 2691, unknown: 0, state: [0 240 234 247 255 127 0 0 0 0 4 0 0 0 0 0 32 0 0 0 0 0 0 0]" subsys=cilium-node-monitor
```

**Comment by tgraf** [comment]
test-missed-k8s

**Review by tgraf — APPROVED** [review]

**Comment by ianvernon** [comment]
I'm merging this; will work on test stabilization outside of this PR - the failures are unrelated to the changes in this PR:

* K8s Upstream tests need bump in timeout
* Need to backport Kafka test CI fixes from master (the test has been unstable for some time)
* The missed K8s tests appear to have failed installing Cilium - the pod wasn't even scheduled:

```
time="2018-10-16T19:07:57Z" level=debug msg="running command: kubecfg validate /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cilium_ds.jsonnet"
cmd: "kubecfg validate /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cilium_ds.jsonnet" exitCode: 0 stdout:

stderr:
Validating configmaps kube-system.cilium-config
validate object "/v1, Kind=ConfigMap"
Validating secrets kube-system.cilium-etcd-secrets
validate object "/v1, Kind=Secret"
Validating daemonsets kube-system.cilium
validate object "extensions/v1beta1, Kind=DaemonSet"
Validating clusterrolebindings cilium
validate object "rbac.authorization.k8s.io/v1beta1, Kind=ClusterRoleBinding"
Validating clusterroles cilium
validate object "rbac.authorization.k8s.io/v1beta1, Kind=ClusterRole"
Validating serviceaccounts kube-system.cilium
validate object "/v1, Kind=ServiceAccount"

time="2018-10-16T19:07:58Z" level=debug msg="running command: kubecfg update /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cilium_ds.jsonnet"
cmd: "kubecfg update /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cilium_ds.jsonnet" exitCode: 0 stdout:

stderr:
Validating configmaps kube-system.cilium-config
validate object "/v1, Kind=ConfigMap"
Validating secrets kube-system.cilium-etcd-secrets
validate object "/v1, Kind=Secret"
Validating daemonsets kube-system.cilium
validate object "extensions/v1beta1, Kind=DaemonSet"
Validating clusterrolebindings cilium
validate object "rbac.authorization.k8s.io/v1beta1, Kind=ClusterRoleBinding"
Validating clusterroles cilium
validate object "rbac.authorization.k8s.io/v1beta1, Kind=ClusterRole"
Validating serviceaccounts kube-system.cilium
validate object "/v1, Kind=ServiceAccount"
Fetching schemas for 6 resources
Updating clusterroles cilium
Creating non-existent clusterroles cilium
Updating clusterrolebindings cilium
Creating non-existent clusterrolebindings cilium
Updating serviceaccounts kube-system.cilium
Creating non-existent serviceaccounts kube-system.cilium
Updating configmaps kube-system.cilium-config
Creating non-existent configmaps kube-system.cilium-config
Updating secrets kube-system.cilium-etcd-secrets
Creating non-existent secrets kube-system.cilium-etcd-secrets
Updating daemonsets kube-system.cilium
Creating non-existent daemonsets kube-system.cilium

time="2018-10-16T19:07:58Z" level=debug msg="running command: kubectl -n kube-system get pods -l k8s-app=cilium -o json"
cmd: "kubectl -n kube-system get pods -l k8s-app=cilium -o json" exitCode: 0 stdout:
{
    "apiVersion": "v1",
    "items": [],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}

```

Will work on fixing this.

**Pull request merged**
