### PR TITLE
e2e: Make ginkgo default to verbose mode

### PR DESCRIPTION
**Pull request by qmonnet**
It is usually helpful to get the verbose information provided by ginkgo. For example, it lets the user know when provisioning is stuck on downloading an image, instead of providing no feedback for non-verbose mode.

This PR forces ginkgo to run in verbose mode by default (`-v` flag). But it skips enforcement in a few cases:

- If `-succinct` is provided.
- <s>If the new option `-cilium.noVerbose=true` is provided.</s> [removed]

The second commit updates the documentation accordingly.

### CODE REVIEW

**Comment by qmonnet** [comment]
test-me-please

**Comment by qmonnet** [comment]
test-runtime

**Comment by pchaigno** [comment]
> This PR forces ginkgo to run in verbose mode by default (`-v` flag). But it skips enforcement in a few cases:
>     * If `-succinct` is provided.
>     * If the new option `-cilium.noVerbose=true` is provided.

Do we need `cilium.noVerbose` if we have `-succinct`? Is there a difference between the two?

**Comment by qmonnet** [comment]
> Do we need `cilium.noVerbose` if we have `-succinct`? Is there a difference between the two?

There are three modes: verbose, “default”, and succinct. Succinct is more quiet than the default mode: `If set, default reporter prints out a very succinct report`. The `cilium.noVerbose` is for using the default mode.

I don't know how strong we need it, but I didn't feel comfortable disabling this default mode entirely.

**Comment by qmonnet** [comment]
test-1.20-4.9

**Comment by joestringer** [comment]
This is always a balancing act between verbosity and noise :-)

> There are three modes: verbose, “default”, and succinct. Succinct is more quiet than the default mode: If set, default reporter prints out a very succinct report. The cilium.noVerbose is for using the default mode.
> 
> I don't know how strong we need it, but I didn't feel comfortable disabling this default mode entirely.

For some context, a long time ago (in a galaxy yada yada..), I had added the "succinct" mode because for my personal usage I found that the default was too noisy. For example if I really just wanted to see whether various tests passed/failed when running locally. But a lot has changed since then, including changes to the default verbosity and even the way we do testing as a project. I don't have any local shell shortcuts that use succinct, my guess is that noone still uses it. 

I interpret the PR in its current state to be saying two things:
* The default options are not providing you with enough information to debug an issue with the individual test run
* The three existing options for debug output are not enough, let's add a fourth.

Overall though I think there's only really two use cases:
* Running all of the tests where you expect everything to pass and you just want a short summary of each test that you run
  * In the past it was far more common for developers to run all tests locally. Printing all --verbose output would be counterproductive here because there's just so much irrelevant information if you don't expect many tests to fail.
  * These days we are far more reliant on the CI to provide these checks so maybe this use case is not as common. Between Github and Jenkins, if there are any failures, the red failure icons will be pretty obvious and you know where to focus.
* Running in a way that gathers as much information as possible about the build
  * Behind the scenes in CI (eg in the full jenkins log), we actually want this by defualt so that we don't have to run the test twice just to start getting debug information.
  * When running locally, if you know the test is likely to fail then you probably just want to set this flag and get as much info as possible.

Going based off the above, I think at this point it's quite reasonable to switch the default to verbose, then allow developers to specify either `--succinct` or `--quiet` or however we want the flag to be called if they really want less output. :+1:  Then if we implement this and developers start complaining, let's discuss more about what info is useful and what is too much info to again rebalance the verbosity/noise equation.

**Comment by qmonnet** [comment]
The `-succinct` is a ginkgo option, not something we can remove cleanly (we could probably disable it the way we enforce verbose, but there's probably no need). Talking with Joe on Slack - It transpires that you share Paul's concern about too-many-options. So after all, I removed the `-cilium.noVerbose` option. In this new revision we have verbose by default, or `-succinct` to get a very quiet output.

**Comment by qmonnet** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
I'm fine with this, would be good to make sure folks in #development channel on Slack have a chance to see the PR in case there's any concerns but we can always iterate on top and gauge the best balance of providing the information we need to debug vs. hiding the extra output if it's not useful for what people need to know.

There's some potential for the extra output to cause issues given the size of the logs (like I don't know if this is too noisy for jenkins or it's OK)

**Comment by qmonnet** [comment]
A quick grep for `ginkgo` in the jenkinsfiles seems to indicate that all invocations already use the `-v` (verbose) flag, so I don't believe there will be an issue. But you're correct on announcing on #development, I'll do that. Thanks!

**Review by christarazi — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by qmonnet** [comment]
test-1.20-4.9

**Review by pchaigno — APPROVED** [review]
I ran a few tests with `-succinct` and without `-v`. The output is fairly close, with `-succinct` hiding almost everything but failures. I think it's fine to remove the current default :+1: 

Thanks!

**Comment by qmonnet** [comment]
@glibsm I don't see any conflict, and the files touched by this PR do not appear to have been modified in the master branch since the creation of the PR. I believe you set the label by mistake? Did you intend to add it to another PR instead?

I'm swapping back to `ready-to-merge`, let me know if I missed something.

**Pull request merged**
