### PR TITLE
ui deployment: upgrade envoy to 1.18.2, fix config

### PR DESCRIPTION
**Pull request by geakstr**
Signed-off-by: Dmitry Kharitonov <dmitry@isovalent.com>

Related to https://github.com/cilium/cilium/issues/15842

### CODE REVIEW

**Review by aanm — APPROVED** [review]
:rocket:

**Comment by aanm** [comment]
@geakstr you need to run `make -C install/kubernetes docs` and submit changes

**Comment by geakstr** [comment]
Thanks @aanm !

**Review by kaworu — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-1.16-netnext

**Comment by aanm** [comment]
test-gke

**Comment by kaworu** [comment]
test-1.16-netnext

**Comment by kaworu** [comment]
test-gke

**Comment by aanm** [comment]
merging since all other tests should have provided enough coverage for envoy integration.

**Pull request merged**
