### PR TITLE
helm: Bump cilium/startup-script image tag

### PR DESCRIPTION
**Pull request by gandro**
This bumps the `cilium/startup-script` image tag to a more recent
tag, which bumps the underlying Alpine base image too.

This PR does not contain any functional changes.

Signed-off-by: Sebastian Wicki <sebastian@isovalent.com>

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
:shipit:

Seems like only alpine version changes as you mentioned, based on history of this https://github.com/cilium/image-tools/tree/master/images/startup-script

**Comment by gandro** [comment]
AKS failed, but it's not using Helm so unrelated to the PR. I'll restart in any case

https://github.com/cilium/cilium/runs/5751599803?check_suite_focus=true

**Review by aanm — APPROVED** [review]

**Comment by gandro** [comment]
net-next hit a known verifier flake (https://github.com/cilium/cilium/issues/18895) and a potentially new flake in K8sKafkaPolicyTest 

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-net-next/847/testReport/junit/Suite-k8s-1/23/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

**Comment by gandro** [comment]
/test-1.23-net-next

**Comment by gandro** [comment]
/test-1.23-net-next

**Comment by gandro** [comment]
/test-1.23-net-next

**Comment by gandro** [comment]
All CI has passed. Marking ready to merge.

**Pull request merged**
