### PR TITLE
IPAM: fix node's pod cidr duplicate

### LINKED ISSUE #22770: cilium endpoint cidr conflict
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Two node's cilium endpoint cidr same.

image

cilium config:
ipam: cluster-pool

### Cilium Version

cilium version
Client: 1.12.0 9447cd1 2022-07-19T12:22:00+02:00 go version go1.18.4 linux/amd64
Daemon: 1.12.0 9447cd1 2022-07-19T12:22:00+02:00 go version go1.18.4 linux/amd64

### Kernel Version

uname -a
Linux 10-10-66-25 4.19.113-300.el7.x86_64 #1 SMP Mon Mar 30 21:50:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T00:54:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

Error: unknown command "sysdump" for "cilium"

### Relevant log output

```shell
None
```

### Anything else?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by llhhbc**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #22770

### CODE REVIEW

**Review by gandro — CHANGES_REQUESTED** [review]
Thanks for the PR. Could you explain why this PR fixes the issue you linked?

Since I noticed you reported the original issue on Cilium v1.12.0, please note that we have fixed a similar (the same?) bug in v1.12.4: https://github.com/cilium/cilium/pull/21526

**Comment by llhhbc** [comment]
From the code level, the code does not completely solve this problem. Because it only handles ciliumnode synchronization, and does not consider the order of processing

**Comment by gandro** [comment]
> From the code level, the code does not completely solve this problem. Because it only handles ciliumnode synchronization, and does not consider the order of processing

Thanks for the reply. I don't understand why the order matters. The set of "marked" pod CIDRs will be the same, regardless of the order we mark them. 

Could you give an example of a list of events that shows the buggy behavior you are trying to fix sorting the events?

**Comment by llhhbc** [comment]
ok.

here is test data:

node1 with cidr 1.1.1.0/24
node2 without cidr
node3 with cidr 1.1.2.0/24

because canAllocatePodCIDRs=false, so they record in map.
map range is out of order.
when node1 resync, 1.1.1.0 will load in cache,  
when node2 resync, will allocate 1.1.2.0 to node2, and is dumplicate with node3

**Comment by gandro** [comment]
> because canAllocatePodCIDRs=false, so they record in map.
Yes, node1 and node3 will be in the `nodesToAllocate` map, _and_ they will also called into `reuseIPNets` here: https://github.com/cilium/cilium/blob/8d61ec9e9dcb0a996a9f129a1af30b6ed193341d/pkg/ipam/allocator/podcidr/podcidr.go#L504

node2 will be in `nodesToAllocate`, but it will not have allocated before canAllocatePodCIDRs is set to true.

> map range is out of order.

Yes.

>when node1 resync, 1.1.1.0 will load in cache,
> when node2 resync, will allocate 1.1.2.0 to node2, and is dumplicate with node3

Here is where I disagree. This will not happen: node2 will _not_ allocate 1.1.2.0, because 1.1.2.0 was passed to `reuseIPNets` in `NodesPodCIDRManager.allocateNode` (right before node2 was added to `nodesToAllocate`) and therefore is not available for allocation.

**Comment by llhhbc** [comment]
Ok, I understand that there is a deviation, and this logic has indeed been fixed.

**Pull request closed without merging**
