### PR TITLE
Envoy 1.17.1 backport v1.8

### PR DESCRIPTION
**Pull request by jrajahalme**
* #14754 -- envoy: Update to release 1.17.1 (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14754; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-backport-1.8

**Comment by jrajahalme** [comment]
test-backport-1.8

**Comment by jrajahalme** [comment]
test-backport-1.8

**Comment by jrajahalme** [comment]
Added a commit discarding Envoy API v2 deprecation warnings unless flowdebug is enabled. We are intentionally using Envoy API v2 on v1.8 and v1.7 releases.

**Comment by jrajahalme** [comment]
test-backport-1.8

**Review by joestringer — APPROVED** [review]

**Comment by jrajahalme** [comment]
retest-upstream-k8s

**Comment by jrajahalme** [comment]
test-1.15-4.9 hit by #6728

**Comment by jrajahalme** [comment]
retest-1.15-4.9

**Comment by joestringer** [comment]
The `test-upstream-k8s` job failed at provisioning: https://jenkins.cilium.io/job/Cilium-PR-K8s-Upstream/2890/flowGraphTable/

**Comment by joestringer** [comment]
test-upstream-k8s

**Pull request merged**
