### PR TITLE
helm: fix poststart-eni.bash execution in agent DS

### PR DESCRIPTION
**Pull request by nebril**
This change fixes malformed yaml that caused poststart-eni to not be executed. The original change was made in https://github.com/cilium/cilium/pull/24134 and backported in https://github.com/cilium/cilium/pull/24547. Master branch is already fixed by https://github.com/cilium/cilium/pull/24389 , which was not marked for backporting.

### CODE REVIEW

**Comment by nebril** [comment]
/test-backport-1.13

**Comment by nebril** [comment]
/test-backport-1.13

**Comment by nebril** [comment]
Cilium-PR-K8s-1.23-kernel-4.9 hit https://github.com/cilium/cilium/issues/16122

**Review by joestringer — APPROVED** [review]

**Comment by nebril** [comment]
Sorry Joe, I saw your comment after I merged the PR.

As far as I understand, new CI health rotation will be responsible for figuring out flakes? What else aside from identifying which flakes were hit in this PR should be done?

**Comment by joestringer** [comment]
Good question. If we trust that this CI health rotation is going to detect all of these issues, prioritize well and drive a solution then sure that may work. I'm mildly concerned that this incentivizes subverting CI rather than making CI simple and trustable.

I think it wouldn't hurt to at least raise such discussions with them to see about the options to deal with issues like this. I wonder if we should get to even more drastic measures like just submitting a PR to quarantine/disable the specific tests that are failing, since we're getting unreliable feedback from that PR anyway. At least then the CI health rotation person will have a clear signal about how the quarantined tests are unreliable enough that we are missing coverage due to the test instability, so those tests could be prioritized for development+fixing.

**Pull request merged**
