### PR TITLE
[1.5] daemon: Make policymap size configurable

### PR DESCRIPTION
**Pull request by tgraf**
[ upstream commit ec07900a49bf96b2f47b6ecbc0b4c22c7ca4de46 ]

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8121)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
Hit known toEntities flake

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by brb** [comment]
Hit #7615

**Comment by brb** [comment]
test-missed-k8s

**Review by brb — APPROVED** [review]

**Pull request merged**
