### PR TITLE
daemon: in k8s mode always allow localhost traffic

### PR DESCRIPTION
**Pull request by aanm**
Fixes: 0da4df30f4b9 ("daemon: move daemon's config to option/config")
Signed-off-by: André Martins <andre@cilium.io>

Fixes https://github.com/cilium/cilium/issues/4245

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4263)

### CODE REVIEW

**Comment by aanm** [comment]
@tgraf do we still need #4249 ?

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
> @tgraf do we still need #4249 ?

Yes, both fixes are independent.

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by tgraf** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
@tgraf feel free to merge this, I've test it locally, all tests passed, except the named-ports (as expected):
```
SSSSSSSSSSSSSSSSSSSSSSSSSSMay 28 14:01:13.215: INFO: Running AfterSuite actions on all node
May 28 14:01:13.215: INFO: Running AfterSuite actions on node 1


Summarizing 2 Failures:

[Fail] [sig-network] NetworkPolicy NetworkPolicy between server and client [It] should allow egress access on one named port [Feature:NetworkPolicy] 
/home/aanm/git-repos/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:444

[Fail] [sig-network] NetworkPolicy NetworkPolicy between server and client [It] should allow ingress access on one named port [Feature:NetworkPolicy] 
/home/aanm/git-repos/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:444

Ran 8 of 876 Specs in 617.095 seconds
FAIL! -- 6 Passed | 2 Failed | 0 Pending | 868 Skipped --- FAIL: TestE2E (617.12s)
```

**Pull request merged**
