### PR TITLE
[WIP] bpf: Remove tunnel map support

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9953)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by joestringer** [comment]
For upgrade we'll need to unpin the map from the filesystem to clean it up.

**Comment by tgraf** [comment]
The following tests have failed:
```

Suite-k8s-1.11.K8sDatapathConfig DirectRouting Check connectivity with sockops and direct routing 
Suite-runtime.RuntimeMemcache Testing text memcache Tests policy disallowing set action
Suite-runtime.RuntimeMemcache Testing text memcache Tests policy allowing actions only for allowed key
Suite-runtime.RuntimeCassandra Tests policy allowing all actions
Suite-runtime.RuntimeCassandra Tests policy disallowing Insert action
```

Running another test run to get more data

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
> For upgrade we'll need to unpin the map from the filesystem to clean it up.

I was considering to just keep the map for a full release but no longer update it and then remove it with 1.8.

**Comment by tgraf** [comment]
Different tests failed this time:
```

Suite-k8s-1.11.K8sHealthTest checks cilium-health status between nodes
Suite-k8s-1.17.K8sPolicyTest Basic Test Redirects traffic to proxy when no policy is applied with proxy-visibility annotation Tests DNS proxy visibility without policy

```

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Pull request closed without merging**
