### PR TITLE
agent: Require go 1.10 for safe namespace operations

### PR DESCRIPTION
**Pull request by tgraf**
We already use Go 1.10 to build the cilium container image. Document this
properly as a requirement in the vagrant box and remove the FIXME in the CNI
plugin which is no longer an issue.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4599)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
Out of curiosity, how come the FIXME in the CNI plugin is no longer an issue?

**Review by ianvernon — APPROVED** [review]

**Review by rlenglet — APPROVED** [review]

**Comment by tgraf** [comment]
@eloycoto correctly pointed out that `envoy/Dockerfile` defines the golang version of the container image build. Bumped the golang version there as well.

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
