### PR TITLE
development: add cache to k8s components

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

When creating a development environment with 2 nodes we don't need to download those components twice as they will be stored under `./hack/cache/k8s`

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]
LGTM! I always like me some handy-dandy bash scripts :)

**Comment by ianvernon** [comment]
@cilium/janitors please review.

**Comment by ianvernon** [comment]
@cilium/janitors this still needs review.

**Review by manalibhutiyani — APPROVED** [review]

**Pull request merged**
