### PR TITLE
Envoy 1.17.1 backport v1.7

### PR DESCRIPTION
**Pull request by jrajahalme**
* #14754 -- envoy: Update to release 1.17.1 (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14754; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-backport-1.7

**Comment by jrajahalme** [comment]
test-backport-1.7

**Comment by jrajahalme** [comment]
test-backport-1.7

**Comment by jrajahalme** [comment]
test-1.12-4.9

**Comment by joestringer** [comment]
FYI @jrajahalme I don't think the "test-1.12-4.9" makes sense, we can probably ignore it. See my comment here: https://github.com/cilium/cilium/pull/15183#issuecomment-791612872

**Comment by jrajahalme** [comment]
> FYI @jrajahalme I don't think the "test-1.12-4.9" makes sense, we can probably ignore it. See my comment here: [#15183 (comment)](https://github.com/cilium/cilium/pull/15183#issuecomment-791612872)

Good to know, it shows up as "required" :-)

**Comment by jrajahalme** [comment]
Added a commit discarding Envoy API v2 deprecation warnings unless flowdebug is enabled. We are intentionally using Envoy API v2 on v1.8 and v1.7 releases.

**Review by joestringer — APPROVED** [review]

**Pull request merged**
