### PR TITLE
deps: update k8s deps to 1.11.0

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4693)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
flake https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/467/

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
different flake https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/470

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
probably flake : https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/494/testReport/junit/k8s-1/9/K8sValidatedDemosTest_Tests_Star_Wars_Demo/

probably flke: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4748/

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
quay.io was down https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/496/

**Comment by aanm** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
I don't see the need for janitor review here, as this is a vendoring / K8s change and I cover both of those groups.

**Pull request merged**
