### PR TITLE
cilium/cmd: Add pretty print to bpf metrics list

### LINKED ISSUE #4223: Pretty print for cilium bpf metrics list
Currently the `sudo cilium bpf metrics list` output looks like this:
```
vagrant@runtime1:~/go/src/github.com/cilium/cilium$ sudo cilium bpf metrics list
KEY                COUNT                 
reason:0 dir:1     count:22 bytes:2102   
reason:131 dir:2   count:22 bytes:1700   
reason:133 dir:2   count:5 bytes:370     
reason:0 dir:2     count:25 bytes:2324   
reason:133 dir:1   count:3 bytes:222  
```

We need to make this better to something like:
```
REASON          DIRECTION    PACKETS    BYTES
PolicyDropped   Ingress      1          64
```  

Related to PR: #4211

### PR DESCRIPTION
**Pull request by iffyio**
This commit adds pretty print to the cilium bpf metrics list
cli command output.

Fixes #4223

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5631)

### CODE REVIEW

**Comment by aanm** [comment]
@iffyio Can you attach an example of what the output looks like in the commit message?

**Comment by iffyio** [comment]
Example added :)

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
@iffyio great work! your commits have been stellar.

**Comment by iffyio** [comment]
Thanks :)

**Pull request merged**
