### PR TITLE
v1.13 Backports 2023-11-07

### PR DESCRIPTION
**Pull request by jibi**
* [x] #28808 (@brb)
 * [x] #28884 (@julianwiedmann)
 * [x] #28898 (@pchaigno)
 * [x] #28941 (@pchaigno)
 * [x] #28927 (@sayboras)
 * [x] #28642 (@pchaigno)
 * [x] #28795 (@pchaigno)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 28808 28884 28898 28941 28927 28642 28795
```

### CODE REVIEW

**Comment by jibi** [comment]
/test-backport-1.13

**Comment by jibi** [comment]
/test-backport-1.13

**Review by julianwiedmann — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-backport-1.13

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commit

**Comment by jibi** [comment]
/test-1.23-4.19

**Review by squeed — APPROVED** [review]

**Review by brb — APPROVED** [review]
Thanks!

**Review by pchaigno — APPROVED** [review]
The two PRs from me you backported look good. Thanks!

**Pull request merged**
