### PR TITLE
Update Go to 1.16.2

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-gke

**Review by twpayne — APPROVED** [review]
LGTM

**Review by jrajahalme — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Comment by Skymirrh** [comment]
I was 100% sure I had approved this, my bad.

**Pull request merged**
