### PR TITLE
images: Update cilium-iproute2

### PR DESCRIPTION
**Pull request by pchaigno**

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by pchaigno** [comment]
All tests are passing and reviews are in. Marking ready to merge.

**Comment by anfernee** [comment]
@pchaigno should we backport this to 1.11 (and 1.10)?

**Comment by pchaigno** [comment]
@anfernee Why? Is this fixing a bug that is present on v1.11?

**Comment by anfernee** [comment]
I believe it includes some CVE fixes.

**Comment by joestringer** [comment]
@anfernee are you able to provide details to the security@cilium.io mailinglist?

Maybe @pchaigno can chime in with more detail here, but I believe that the build process for the iproute2 binary we ship in Cilium has changed significantly in v1.11/master so my main concern would be mitigating any potential adverse effects of such an update, particularly on older branches. However, perhaps there's a simpler cherrypick process we can go through to bump the older releases to address this issue.

**Pull request merged**
