### PR TITLE
test(notify): add tests to compare flow proto parsed from notify events

### PR DESCRIPTION
**Pull request by sypakine**
Related: #35057

Diffing the flow proto provides more clarity how a change to the notification or parsing has affected the output.

Note: no release note

### CODE REVIEW

**Review by rolinh — APPROVED** [review]
Sorry for the delay in reviewing your PR. Changes lgtm.

**Comment by jrajahalme** [comment]
This broke `main`:
```
~/go/src/github.com/cilium/cilium$ cd pkg/hubble/parser/threefour/
~/go/src/github.com/cilium/cilium/pkg/hubble/parser/threefour$ go test ./...
--- FAIL: TestDecode_DropNotify (0.00s)
    --- FAIL: TestDecode_DropNotify/drop_unknown (0.00s)
        parser_test.go:1497: Unexpected diff (-want +got):
              (*flow.Flow)(Inverse(protocmp.Transform, protocmp.Message{
              	... // 5 identical entries
              	"ethernet":   protocmp.Message{"@type": s"flow.Ethernet", "destination": string("07:08:09:00:01:02"), "source": string("01:02:03:04:05:06")},
              	"event_type": protocmp.Message{"@type": s"flow.CiliumEventType", "type": int32(1)},
            + 	"file":       s`{name:"unknown(0)"}`,
              	"source":     protocmp.Message{"@type": s"flow.Endpoint", "ID": uint32(1234)},
              	"verdict":    s"DROPPED",
              }))
    --- FAIL: TestDecode_DropNotify/drop_egress (0.00s)
        parser_test.go:1497: Unexpected diff (-want +got):
              (*flow.Flow)(Inverse(protocmp.Transform, protocmp.Message{
              	... // 5 identical entries
              	"ethernet":          protocmp.Message{"@type": s"flow.Ethernet", "destination": string("07:08:09:00:01:02"), "source": string("01:02:03:04:05:06")},
              	"event_type":        protocmp.Message{"@type": s"flow.CiliumEventType", "type": int32(1)},
            + 	"file":              s`{name:"unknown(0)"}`,
              	"source":            protocmp.Message{"@type": s"flow.Endpoint", "ID": uint32(1234)},
              	"traffic_direction": s"EGRESS",
              	"verdict":           s"DROPPED",
              }))
    --- FAIL: TestDecode_DropNotify/drop_ingress (0.00s)
        parser_test.go:1497: Unexpected diff (-want +got):
              (*flow.Flow)(Inverse(protocmp.Transform, protocmp.Message{
              	... // 5 identical entries
              	"ethernet":          protocmp.Message{"@type": s"flow.Ethernet", "destination": string("07:08:09:00:01:02"), "source": string("01:02:03:04:05:06")},
              	"event_type":        protocmp.Message{"@type": s"flow.CiliumEventType", "type": int32(1)},
            + 	"file":              s`{name:"unknown(0)"}`,
              	"source":            protocmp.Message{"@type": s"flow.Endpoint"},
              	"traffic_direction": s"INGRESS",
              	"verdict":           s"DROPPED",
              }))
FAIL
FAIL	github.com/cilium/cilium/pkg/hubble/parser/threefour	0.030s
FAIL
```

**Comment by rolinh** [comment]
Thanks for reporting @jrajahalme, looks like there was a merge race. See #35196 for a fix.

**Pull request merged**
