### PR TITLE
vagrant: bump all vagrant box versions

### PR DESCRIPTION
**Pull request by tklauser**
These include new tags for the pre-pulled images and Go is updated to
1.14.3.

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by tklauser** [comment]
retest-4.19

**Comment by tklauser** [comment]
retest-net-next

**Comment by tklauser** [comment]
retest-4.9

**Comment by tklauser** [comment]
retest-4.19

**Comment by tklauser** [comment]
retest-4.9

**Comment by tklauser** [comment]
retest-4.9

**Comment by aanm** [comment]
hitting flakes, merging

**Pull request merged**
