### PR TITLE
Fixes:Added the declaration of license

### PR DESCRIPTION
**Pull request by yulng**
Need to declare the license at the beginning of the file

Signed-off-by: yulng wei.yang@daocloud.io

Signed-off-by: yulng <31728060+yulng@users.noreply.github.com>

### CODE REVIEW

**Comment by joestringer** [comment]
@yulng thanks for the submission, the DCO needs to be signed off in the following syntax, note the `<>` angle brackets:

```
Signed-off-by: Your Name <your@name.com>
```

You should be able to do a `git commit --amend` to edit the message, then `git push --force-with-lease` to update the PR branch.

**Comment by yulng** [comment]
> @yulng thanks for the submission, the DCO needs to be signed off in the following syntax, note the `<>` angle brackets:
> 
> ```
> Signed-off-by: Your Name <your@name.com>
> ```
> 
> You should be able to do a `git commit --amend` to edit the message, then `git push --force-with-lease` to update the PR branch.

ok, done, just now

**Comment by joestringer** [comment]
@yulng you need to push the latest changes to this same branch on github to update the PR.

**Comment by yulng** [comment]
> @yulng you need to push the latest changes to this same branch on github to update the PR.

Updated

Thanks

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Thanks, merged.

**Pull request merged**
