### PR TITLE
v1.11: Update Go to 1.17.10

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Review by christarazi — APPROVED** [review]

**Comment by tklauser** [comment]
/test-backport-1.11

**Review by joestringer — APPROVED** [review]

**Comment by tklauser** [comment]
/test-backport-1.11

**Comment by tklauser** [comment]
/test-backport-1.11

**Comment by tklauser** [comment]
/test-1.23-4.9

**Comment by tklauser** [comment]
Only AKS workflow is failing, which is a known issue (#19788). Both Chris and Joe approved, so marking as ready to merge.

**Pull request merged**
