### PR TITLE
daemon: Delete old ID mapping when updating the IP for a reserved ID

### PR DESCRIPTION
**Pull request by rlenglet**
Fix logging.
Homogenize the code calling OnIPIdentityCacheChange to make it
easier to maintain.

Fixes: https://github.com/cilium/cilium/issues/4277
Fixes: https://github.com/cilium/cilium/pull/4172
Fixes: https://github.com/cilium/cilium/commit/8b64ca827b78a9787015f29cd075d04906068f0c
Signed-off-by: Romain Lenglet <romain@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4365)

### CODE REVIEW

**Comment by rlenglet** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
I see, in effect this means that if we end up handing out an existing address to one of the reserved identities then the reserved identity will take precedence. This seems like exactly the case we're hitting in #4277. Nice find!

**Comment by rlenglet** [comment]
CI build failure:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3818/execution/node/65/log/
```
06:46:48 K8sValidatedPolicyTest
06:46:48 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:341
06:46:48   Basic Test
06:46:48   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:341
06:46:48     tests PolicyEnforcement updates [It]
06:46:48     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:373
06:46:48 
06:46:48     Expected
06:46:48         <int>: 3
06:46:48     to equal
06:46:48         <int>: 4
06:46:48 
06:46:48     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Policies.go:153
```
Seems likely to be https://github.com/cilium/cilium/issues/3803

**Comment by rlenglet** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by jrfastab** [comment]
@rlenglet not applying for v1.0 backports this should be pushed into v1.1. Please drop the backport tag assuming you agree.

**Comment by rlenglet** [comment]
Done. Thanks!

**Pull request merged**
