### PR TITLE
endpoint: Fix detection of L4 policy changes

### PR DESCRIPTION
**Pull request by joestringer**
When adding an L7 rule to an L4 policy, the recent endpoint logic
changes did not properly propagate the need to recompile the BPF
program, so entirely skipped it, leading to #4181.

Fix it by tracking whether the L4 policy changes in regeneratePolicy()
and including this in the final "needToRegenerateBPF" result.

Fixes: #4181

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4185)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by joestringer** [comment]
Filed issue for bug that was hit in CI, appears to be unrelated: https://github.com/cilium/cilium/issues/4187

Re-running CI to see if we hit it again.

**Comment by joestringer** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]
Looks correct. However wonder if the original intention was to somehow notice that now the desired policy is different from the realized policy? Either way we need to return true for the `policyChanged` here.

**Comment by joestringer** [comment]
@jrajahalme I suspect that if we were to spin this L4 part out into a controller, then we'd need to revert this and do something like that. In the absence of L4 policy being handled in a controller, we need to do this somewhere and I think this PR puts the check in the right place.

**Pull request merged**
