### PR TITLE
datapath, netkit: Allow ARP passthrough on host when using netkit

### LINKED ISSUE #34230: Enabling host firewall blocks arp
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

After enabling host firewall arp stops working. After a while cluster loses external connectivity as it can't resolve mac address of default gateway. 

### How can we reproduce the issue?

Install cilium and enable host firewall

### Cilium Version

cilium-cli: v0.16.15 compiled with go1.22.5 on linux/amd64
cilium image (default): v1.16.0
cilium image (stable): unknown
cilium image (running): 1.16.0

### Kernel Version

Linux service-cluster-server-03 6.8.0-39-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.3+rke2r1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3+rke2r1

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jrife**
When using the `netkit` datapath mode neither `ENABLE_ARP_PASSTHROUGH` nor `ENABLE_ARP_RESPONDER` is set for any endpoint. When host firewall is enabled all ARP messages are blocked to and from the netdev. Make an exception for host endpoints to ensure connectivity is maintained between the host and the outside world. Additionally, add test coverage for netkit combined with host firewall.

Fixes: #34230
Fixes: 68953415f03a ("cilium, connector: Add netkit connector")

```release-note
netkit: Allow ARP packets through when using host firewall.
```

### CODE REVIEW

**Comment by jrife** [comment]
cc @borkmann

**Review by pchaigno — APPROVED** [review]

**Review by borkmann — APPROVED** [review]
awesome, thanks @jrife !

**Review by brlbil — APPROVED** [review]
CI changes 👍

**Review by rgo3 — APPROVED** [review]

**Comment by jrife** [comment]
thanks @borkmann

**Pull request merged**
