### PR TITLE
iptables: Fix incorrect SNAT for externalTrafficPolicy=local

### PR DESCRIPTION
**Pull request by tgraf**
So far, Cilium has installed a rule to clear the masquerade bit set by
kube-proxy in an attempt to still expose the correct source IP for kube-proxy
traffic regardless of the externalTrafficPolicy setting.

This works relatively well unless hostPort is getting involved. By clear the
bit, it is no longer possible to distinguish hostPort traffic and traffic for
which externalTrafficPolicy=local has been set.

Revert this strategy and stop clearing the masquerade bit. This allows to
remove several SNAT/MASQUERADE rules installed by Cilium which attempted to
replicate the kube-proxy SNAT behavior. Instead, leave it up to the user to
properly set externalTrafficPolicy=local.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9561)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]
Should we also update the docs to reflect the change in behavior wrt `instead, leave it up to the user to properly set externalTrafficPolicy=local.`?

**Comment by tgraf** [comment]
> Should we also update the docs to reflect the change in behavior wrt `instead, leave it up to the user to properly set externalTrafficPolicy=local.`?

Yes, I'll update the docs as well and also update the iptables diagram.

**Comment by joestringer** [comment]
@tgraf is this intended for backport? It looks like this PR should fix https://github.com/cilium/cilium/issues/9284

**Pull request merged**
