### PR TITLE
test: Remove e2e graceful termination test cases

### PR DESCRIPTION
**Pull request by brb**
The commit 108c4595d ("test/control-plane: Add graceful termination
test") implemented the graceful termination tests in a form of the
control plane integration tests. Therefore, we can remove the e2e ginkgo
tests.

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
:shipit:

**Review by jibi — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by joestringer** [comment]
Should we backport this to v1.12? We are hitting the flake from this test on that branch as well.

**Comment by aditighag** [comment]
> Should we backport this to v1.12? We are hitting the flake from this test on that branch as well.

Control plane tests are not backported to 1.12, are they?

**Comment by brb** [comment]
Noup, they are not backported. I think it's safe to backport them. cc @aanm and @joamaki for opinions.

**Pull request merged**
