### PR TITLE
test: update k8s test versions to 1.16.14, 1.17.11 and 1.18.8

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
hitting https://github.com/cilium/cilium/issues/12867

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]

**Pull request merged**
