### PR TITLE
Makefile: fix grep command for getting directories to run unit tests

### PR DESCRIPTION
**Pull request by ianvernon**
This fixes an issue where no unit tests are ran when \`make unit tests\`
is invoked, as the parameters provided to grep to acquire the list of
directories for which tests should be ran was broken. When ran, it would
produce the following error:

```
grep: the -P option only supports a single pattern
```

A consequence of the above is that no unit tests were ran since 4dbb8fdfc5
was merged. This only affected the master branch.

Fixes: `4dbb8fdfc5`: Create testable logutils package in test helpers

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7437)

### CODE REVIEW

**Comment by ianvernon** [comment]
Unit test failure because BPF map root could not be found: 
```
level=fatal msg="Could not find BPF map root" subsys=bpf
```

**Review by joestringer — APPROVED** [review]
Looks fine to me, coveralls is now reporting coverage again so presumably the unit tests are running. Would be nice to get to the bottom of why these CLI tests require privileges and remove that necessity, but that can be addressed after-the-fact.

**Comment by joestringer** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by joestringer** [comment]
CI I was successful, it just couldn't record the results.

**Comment by ianvernon** [comment]
I ran the old (correct) command for getting the directories for which unit tests had to be ran:

```
$ go list ./... | grep -v -e /api/v1 -e /vendor/ -e /contrib/ -e test > old.out
```

and the new one:

```
$ go list ./... | grep -v '/api/v1\|/vendor\|/contrib' | grep -v -P 'test(?!/helpers/logutils)' > new.out
```

And diff'd the output:

```
$ diff -Naurd old.out new.out 
--- old.out	2019-03-19 16:18:46.335663303 +0000
+++ new.out	2019-03-19 16:21:37.962048666 +0000
@@ -165,6 +165,7 @@
 github.com/cilium/cilium/proxylib/npds
 github.com/cilium/cilium/proxylib/proxylib
 github.com/cilium/cilium/proxylib/r2d2
+github.com/cilium/cilium/test/helpers/logutils
 github.com/cilium/cilium/tools/alignchecker
 github.com/cilium/cilium/tools/ring-dump
 github.com/cilium/cilium/tools/ring-dump/cmd
```

Which is correct, so this means that we are not skipping any directories for which unit tests need to be ran.

Merging.

**Pull request merged**
