### PR TITLE
helm: Bump default spire image version

### PR DESCRIPTION
**Pull request by sayboras**
### Description

Testing was done locally to make sure there is no breaking change.

```
$ cilium connectivity test --test auth
...

[=] Test [echo-ingress-auth-always-fail]
........
[=] Test [echo-ingress-auth-mtls-spiffe]
........
✅ All 2 tests (16 actions) successful, 45 tests skipped, 0 scenarios skipped.
```

Signed-off-by: Tam Mach <tam.mach@cilium.io>

### CODE REVIEW

**Review by gandro — APPROVED** [review]

**Review by qmonnet — CHANGES_REQUESTED** [review]
Looks good, but please rework the description of the second commit. The motivation is not clear to me (Do you mean that you add this line to the config file to have the bot update the SPIRE images using the info from `values.yaml.tmpl`, and that unless we add more config this is the only image it should update? If so, please mention explicitly that the intent is to handle updates for the SPIRE images. Or do you mean something else?)

\+ Typo in commit title, `configu`.

**Review by tommyp1ckles — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]
Reads much better, thank you!

**Comment by qmonnet** [comment]
Travis simply had a hiccup: `apt-get install failed`, temporary failure to reach `ports.ubuntu.com`.

**Comment by sayboras** [comment]
run-time failed for below issue 

https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/6719/testReport/(root)/Suite-runtime/RuntimeDatapathPrivilegedUnitTests_Run_Tests/
```
	 [10:48:59] --- FAIL: TestGetIdentity (0.86s)
	 [10:48:59]   --- FAIL: TestGetIdentity/Duplicated_key (0.26s)
	 [10:48:59] 
	 [10:48:59]     identity_test.go:226: Identity not found in the store
```

**Pull request merged**
