### PR TITLE
Add IPv6 services tests for DualStack environment

### PR DESCRIPTION
**Pull request by fristonio**
* Adds IPv6 services tests for DualStack environment
* Refactor k8sT/Services.go to have a more defined structure
* Fix looped back IPv6 services reachability issue(#13420)
* Add ipv6 masquerading for Cilium running with kube-proxy

### CODE REVIEW

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
retest-runtime

**Review by aanm — APPROVED** [review]
LGTM overall

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
retest-4.9

**Pull request closed without merging**
