### PR TITLE
v1.6 backport 2020 02 11

### PR DESCRIPTION
**Pull request by raybejjani**
v1.6 backports 2020-02-11

 * #9034 -- cilium: only enable IPv6 forwarding if IPv6 is enabled (@jrfastab)
 * #10035 -- Update release process steps (@aanm)
 * ~~#10062 -- [CI] add release name to helm template calls (@nebril)~~
 * #10088 -- ServiceMonitor should default to release namespace (@dsexton)
 * #10101 -- install/kubernetes: add option to hold cilium agent after init container (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 9034 10035 10088 10101; do contrib/backporting/set-labels.py $pr done 1.6; done
```

@aanm I applied https://github.com/cilium/cilium/pull/10035 by hand so double check those commits. I skipped "contributing/release: remove Update versions step".
@nebril I skipped https://github.com/cilium/cilium/pull/10062 since I couldn't find anything it changed that exists on v1.6

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10135)

### CODE REVIEW

**Comment by raybejjani** [comment]
never-tell-me-the-odds

**Comment by raybejjani** [comment]
never-tell-me-the-odds

**Comment by raybejjani** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
