### PR TITLE
helm: Lower default hubble.tls.auto.certValidityDuration to 365 days

### PR DESCRIPTION
**Pull request by chancez**
Hubble CLI will fail to validate certificates with an expiration that's too large on recent MacOS versions with the following error:
```
rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: “*.hubble-relay.cilium.io” certificate is not standards compliant"
```

This is due to https://support.apple.com/en-us/103769 which specifies:

> All TLS server certificates must comply with these new security requirements in iOS 13 and macOS 10.15:
> ...
> Additionally, all TLS server certificates issued after July 1, 2019 (as indicated in the NotBefore field of the certificate) must follow these guidelines:
> ...
> TLS server certificates must have a validity period of 825 days or fewer (as expressed in the NotBefore and NotAfter fields of the certificate).

Since we have many users using MacOS and are likely using the default values with Hubble when starting with TLS, we should adjust the default value to work with recent MacOS versions. Users who wish to preserve the existing expiration validity can set `hubble.tls.auto.certValidityDuration` to the previous default value.

```release-note
helm: Lower default `hubble.tls.auto.certValidityDuration` to 365 days
```

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]
seems reasonable

**Review by gandro — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]
Thanks for the context in the PR's description; I'd recommend keeping it in the commit description as well (for next time).

Looks good to me

**Comment by qmonnet** [comment]
It seems the spell-checker does not recognise “expirations” :facepalm:

**Comment by chancez** [comment]
I just realized too: we should probably backport to 1.16 at least?

**Pull request merged**
