### PR TITLE
start.sh: set RELOAD=1 if VM already exists

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

Fixes https://github.com/cilium/cilium/issues/4628

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4631)

### CODE REVIEW

**Review by vadorovsky — APPROVED** [review]
WFM, LGTM

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
