### PR TITLE
v1.14 Backports 2023-09-12

### PR DESCRIPTION
**Pull request by gandro**
* [x] #27911 (@brb)
   - :warning: Minor conflicts in `main-focus.yaml`
 * [x] #27908 (@julianwiedmann)
 * [x] #27913 (@sofat1989)
 * [ ] #27693 (@joamaki)
   - :warning: Minor conflicts due to controller group not existing in v1.14
    - :warning: Minor conflicts in `daemon_main.go` due to differently named `vp` variable
 * [x] #27889 (@chancez)
 * [x] #27220 (@brb)
 * [x] #27931 (@aanm)
   - :warning: Minor conflicts due to dev container section not existing in v1.14
 * [ ] #27855 (@danehans)
 * [x] #27918 (@julianwiedmann)
 * [x] #27968 (@tklauser)
 * [x] #27963 (@gandro)
   - :warning: Minor conflicts due to controller group not existing in v1.14
 * [x] #27805 (@learnitall)
 * [x] #27792 (@marqc)
 * [x] #27712 (@vipul-21)
 * [ ] #27985 (@joamaki)

PRs skipped due to conflicts:

 * #27670 (@jrajahalme)
 * #27798 (@ti-mo)
 * #27634 (@christarazi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 27911 27908 27913 27693 27889 27220 27931 27855 27918 27968 27963 27805 27792 27712 27985; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=27911,27908,27913,27693,27889,27220,27931,27855,27918,27968,27963,27805,27792,27712,27985
```

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]

**Review by aanm — APPROVED** [review]
LGTM for my commit.  Thank you

**Review by tklauser — APPROVED** [review]
Looks good for my change, thanks!

**Comment by gandro** [comment]
/test-backport-1.14

**Review by brb — APPROVED** [review]
Thanks!

**Comment by joamaki** [comment]
@gandro hey, I had a small mistake in #27693., would it be possible to include https://github.com/cilium/cilium/pull/27985 as well in this? Alternatively could drop #27693 from this and do it in the next round.

**Review by kaworu — APPROVED** [review]
Hubble metrics changes LGTM

**Comment by gandro** [comment]
> @gandro hey, I had a small mistake in #27693., would it be possible to include #27985 as well in this? Alternatively could drop #27693 from this and mark it `backport/author` and I'll do it.

Seems simple enough, I'll add it to this PR, no worries. For 1.12 and 1.13 I'll assume you'll do it as part of the backport of #27693 though, so I'm adding the `backport/author` label for v1.12 and v1.13 (since the two are dependent it seems)

**Comment by gandro** [comment]
Added https://github.com/cilium/cilium/pull/27985

**Comment by gandro** [comment]
/test-backport-1.14

**Review by learnitall — APPROVED** [review]
Thanks!

**Review by marqc — APPROVED** [review]

**Review by chancez — APPROVED** [review]
LGTM for backport of https://github.com/cilium/cilium/pull/27889

**Comment by gandro** [comment]
Commits for remaining reviewers only had minor or no conflicts at all. Merging this, to unblock the v1.14 branch.

**Pull request merged**
