### PR TITLE
Add support for image digests in helm charts

### PR DESCRIPTION
**Pull request by aanm**
Read per commit

### CODE REVIEW

**Review by joestringer — APPROVED** [review]
Same comments as the [v1.9 review](https://github.com/cilium/cilium/pull/15186), all non-blocking nits.

**Comment by aanm** [comment]
test-backport-1.7

**Comment by aanm** [comment]
test-backport-1.7

**Comment by aanm** [comment]
test-backport-1.7

**Comment by aanm** [comment]
test-backport-1.7-k8s

**Pull request merged**
