### PR TITLE
test: Determine private / public iface dynamically

### LINKED ISSUE #10023: CI: K8sDatapathConfig tests should infer the device to use at runtime
When running on the older VM-based CI, the interfaces have set names and can be hardcoded. As we switch to managed k8s tests these interfaces will have arbitrary names. If the tests can derive the interface name to use in the tests then they will be more portable.
There are 3 places this is obviously true:
- K8sDatpathConfig tests: https://github.com/cilium/cilium/blob/master/test/k8sT/DatapathConfiguration.go#L393
```
[Fail] K8sDatapathConfig Transparent encryption DirectRouting [It] Check connectivity with transparent encryption and direct routing
/Users/ray/covalent/gopath/src/github.com/cilium/cilium/test/k8sT/assertionHelpers.go:136
```

- K8sServices tests: https://github.com/cilium/cilium/blob/master/test/k8sT/Services.go#L412
- external_ips https://github.com/cilium/cilium/blob/master/test/k8sT/manifests/externalIPs/external_ips.go#L18

### PR DESCRIPTION
**Pull request by brb**
This PR:

- Determines private / public ifaces (used by NodePort or IPSec) dynamically.
- Removes unnecessary `nodePort.enabled=true` from `k8sT/Services.go`.
- Moves the MetalLB test case into the direct routing context to avoid accidentally changing the datapath configuration of the test case.
- Use log-gatherer from https://github.com/cilium/log-gatherer. Also, add `ServiceAccount=cilium` for it.

Reviewable per commit.

TODO:

- [x] Rebase #10087 once it's been merged.
- [x] Add iproute2 to log-gatherer Docker image.
- [ ] ~Use dynamic iface retriever in the kube-proxy matrix tests.~ Will do it in a separate PR, as it requires provisioning k8s nodes with ExternalIP.

```release-note
Dynamically determine native dev iface for NodePort/externalIPs
```

Fix #10023.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10119)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-gke

**Comment by brb** [comment]
test-gke K8sServices*

**Comment by brb** [comment]
test-gke K8sDatapathConfig*

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-gke K8sDatapathConfig*

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-gke K8sDatapathConfig*

**Comment by brb** [comment]
Provisioning failure. Re-running.

**Comment by brb** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@brb I didn't merge the PR because the build failed for GKE.

**Comment by brb** [comment]
> I didn't merge the PR because the build failed for GKE.

@aanm The test which failed on GKE, they were failing before my PR. I've run them to check whether my PR has fixed some.

**Pull request merged**
