### PR TITLE
Add detailed panic messages for slim ObjectMeta and ListMeta

### PR DESCRIPTION
**Pull request by hemanthmalla**
Currently its hard to track down which method panics are coming from when we do hit them during upgrades. Stack-traces don't seem to have enough information to pinpoint the origin either.

image

### CODE REVIEW

**Review by youngnick — APPROVED** [review]
LGTM, thanks for this!

Will need tests to pass though.

**Comment by hemanthmalla** [comment]
@youngnick all tests are passing now.

**Comment by youngnick** [comment]
yes, the k8s-1.25-kernel-4.19 test appears to have hit #25344, which is being worked on in #25374, so that's a flake. Looks like both of the failing jobs have expired artifacts now though.

I'll run the runtime one again, since I can't check the results now.

/test-runtime

**Pull request merged**
