### PR TITLE
Switch to cilium/statedb

### PR DESCRIPTION
**Pull request by joamaki**
This PR removes pkg/statedb, pulls in cilium/statedb and fixes up StateDB usage in few places as cilium/statedb had evolved a bit.

Here's a summary of changes:

* Remove pkg/statedb
* Vendor cilium/statedb
* Remove the StateDB Swagger API endpoints in favor of StateDB's built-in HTTP handler
* Add the StateDB handler under `/statedb/` in the UNIX socket HTTP API
* Fix up uses of StateDB reconciler (StatusPendingDelete is gone, WithStatus is now SetStatus+Clone)
* statedb.NewDB is now statedb.New
* DeleteTracker() is now Changes()
* Get() is List(), and First() is Get()
* Add metrics implementations for StateDB and the reconciler. Minor change to metrics, "package" label is now "handle" (extracting the package name with runtime.Callers was way too expensive). The metrics have been disabled by default and there should be no users yet depending on stability of the metrics.
* Add module provider for `statedb.Handle`. Using `statedb.Handle` instead of `*statedb.DB` will account metrics to the module id instead of the generic "DB" handle.
* Fix health status JSON marshalling by using string instead of error type for Status field

Additionally small boy scout cleanups that I encounted when testing:
* Increase sysctl full reconciliation to 10 mins from 10 secs (leftover from copy-pasting example code)
* Change sysctl table name from "sysctl-settings" to just "sysctl"
* Added status to sysctl table output
* Add missing ipsets statedb command.

The major functional change in `cilium/statedb` is the switch to our own [adaptive radix tree](https://github.com/cilium/statedb/tree/main/part) implementation from go-immutable-radix which doubles the insert throughput of StateDB and almost halves memory usage as the tree nodes are now more compact.

Benchmarks (insert of 1000 objects in various txn sizes):
```
# Before:
BenchmarkDB_WriteTxn_1-32      220941	     5345 ns/op	   187094 objects/sec
BenchmarkDB_WriteTxn_10-32     779038	     1513 ns/op	   660740 objects/sec
BenchmarkDB_WriteTxn_100-32    845493	     1224 ns/op	   816714 objects/sec
BenchmarkDB_WriteTxn_1000-32  1000000	     1276 ns/op	   783520 objects/sec

## reconciler/benchmark:
1000000 objects reconciled in 2.72 seconds (batch size 1000)
Throughput 367442.46 objects per second
Allocated 11020638 objects, 774545kB bytes, 947656kB bytes still in use

# After 
BenchmarkDB_WriteTxn_1-32        599227	      1986 ns/op	   503406 objects/sec
BenchmarkDB_WriteTxn_10-32      1719872	      711.2 ns/op	  1406167 objects/sec
BenchmarkDB_WriteTxn_100-32     2134458	      564.6 ns/op	  1771128 objects/sec
BenchmarkDB_WriteTxn_1000-32    2393395	      523.6 ns/op	  1909838 objects/sec

## reconciler/benchmark:
1000000 objects reconciled in 1.33 seconds (batch size 1000)
Throughput 751258.11 objects per second
Allocated 6011578 objects, 393555kB bytes, 533768kB bytes still in use
```

Thank you for reviewing :smiling_face_with_three_hearts: . It's a lot! 

```release-note
The StateDB in-memory database library was switched to github.com/cilium/statedb with a new much faster radix tree implementation. This is used internally in the cilium-agent for storing and accessing, among others, the network devices and local node IP addresses. This state can be inspected with the "cilium-dbg statedb" commands.
cilium-dbg: Added "statedb ipsets" command
cilium-dbg: "statedb sysctl-settings" is now "statedb sysctl"
```

### CODE REVIEW

**Review by marseel — APPROVED** [review]
approving vendor changes.

**Review by lmb — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]
Thanks!

**Review by pippolo84 — APPROVED** [review]
LGTM, thanks! :rocket:

**Review by christarazi — APPROVED** [review]
LGTM for ci-structure

**Review by nathanjsweet — APPROVED** [review]

**Pull request merged**
