### PR TITLE
users.md: sphere doesn't exist anymore, 👋 datadog

### PR DESCRIPTION
**Pull request by mvisonneau**
- Sphere has been [acquired by formerly known Twitter](https://blog.sphere.me/sphere-has-joined-twitter-e7127cfe0467) 🐦 in October 2021!
- I've now moved to Datadog 👋 
- Added some more features we are using

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
LGTM and congratz :1st_place_medal:

**Comment by xmulligan** [comment]
@mvisonneau thanks for the update. Does that mean that Twitter is currently using Cilium then?

**Comment by mvisonneau** [comment]
Unfortunately I believe our infra has now been sunsetted :(

**Review by xmulligan — APPROVED** [review]

**Comment by sayboras** [comment]
Full CI is not required, mark this as ready to merge.

**Pull request merged**
