### PR TITLE
v1.5 backports 2019-05-15

### PR DESCRIPTION
**Pull request by nebril**
* #8000 -- Encryption fixes for route/rule management (@jrfastab)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 8000; do contrib/backporting/set-labels.py $pr done 1.5; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8034)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
We should merge it after https://github.com/cilium/cilium/pull/8028

**Review by raybejjani — APPROVED** [review]

**Comment by nebril** [comment]
added this backport to  #8028

**Pull request closed without merging**
