### PR TITLE
v1.4: backports 19-02-05

### PR DESCRIPTION
**Pull request by ianvernon**
* #6936 -- docs: bump copyright headers to 2017-2019 (@aanm)
 * #6935 -- operator: set right environment variable for 'cluster-name' in operator (@aanm)
 * #6931 -- doc: Provide a fully functional GKE create cluster example (@tgraf)
 * #6930 -- Fix clustermesh links, improve syntax highlighting (@joestringer)
 * #6929 -- doc: Document kube-dns requirement in 1.4 (@tgraf)
 * #6928 -- clustermesh: Fix panic in clustermesh initialization (@tgraf)
 * #6925 -- Docs: Trivial fixes on k8s-install-etcd-operator.rst (@jrajahalme)
 * #6914 -- docs: Improve EKS guide (@brb)
 * #6861 -- Encrypt init ns and proxy support (@jrfastab)
 * #6740 -- DNSCache: TTL cleanup implementation. (@eloycoto)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 6936 6935 6931 6930 6929 6928 6925 6914 6861 6740; do contrib/backporting/set-labels.py $pr done 1.4; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6938)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
