### PR TITLE
v1.12 backports 2022-09-28

### PR DESCRIPTION
**Pull request by gandro**
* #20979 -- helm: Fix post-start and pre-stop hooks for cilium-nodeinit on Ubuntu EKS images (@dctrwatson)
 * #21239 -- Remove Slack notifications (@michi-covalent) :warning: Major conflicts (some files missing or are different), please review carefully
 * #21311 -- Remove no more available dockershim flags in kubelet wrapper (@pippolo84)
 * #21333 -- Remove references to node encryption (@pchaigno) :warning: Minor conflicts (viper usage is different in v1.12), please review carefully
 * #21365 -- daemon: Fix a nil dereference on cleanup when DNS proxy is not enabled (@joamaki) :warning: Minor conflicts (testcase unavailable), please review carefully
 * #21348 -- bugtool: Dump envoy config for troubleshooting (@sayboras)
 * #20749 -- docs: Clarify KPR requirements for Kind (@brb) :warning: Conflicts in docs, please review carefully
 * #21254 -- makefile: use versioned go container when formatting after api generate. (@tommyp1ckles)
 * #21402 -- Fix a typo in the comment example (@farcaller)
 * #21403 -- bpf: Add missing identity to `TRACE_TO_STACK` packet traces (@pchaigno)
 * #21429 -- cmd/bpf: Log if no policy maps found (@aditighag)
 * #21370 -- ipsec: Simplify XFRM IN policies (@pchaigno)
 * #21449 -- daemon: avoid nil pointer dereference on invalid endpoint state (@tklauser)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20979 21239 21311 21333 21365 21348 20749 21254 21402 21403 21429 21370 21449; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Looks good for my changes, thanks :100:

**Review by pchaigno — APPROVED** [review]
My 3 PRs look good. Thanks!

**Review by tklauser — APPROVED** [review]
Thanks, looks good for my change.

**Comment by gandro** [comment]
/test-backport-1.12

**Review by pippolo84 — APPROVED** [review]
My PR looks good, thanks! :+1:

**Review by michi-covalent — APPROVED** [review]
✅ https://github.com/cilium/cilium/pull/21466/commits/df17f9c7b6a8c90bfda64de82b1e96e310ecd670

thanks sebastian!

**Review by joamaki — APPROVED** [review]
Mine is good, thanks!

**Review by aditighag — APPROVED** [review]
Backport of my changes looks good! Thanks

**Comment by gandro** [comment]
/test-1.23-4.9

**Review by nebril — APPROVED** [review]

**Comment by gandro** [comment]
All failed workflows are disabled on master due to flakiness. Marking ready to merge.

**Pull request merged**
