### PR TITLE
CI: Determine and set K8s version in GKE pipeline

### PR DESCRIPTION
**Pull request by raybejjani**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10025)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-gke K8sDemosTest*

**Comment by raybejjani** [comment]
test-gke K8sDemosTest*

**Comment by raybejjani** [comment]
test-gke K8sDemosTest*

**Comment by raybejjani** [comment]
test-gke K8sDemosTest*

**Comment by raybejjani** [comment]
test-gke K8sDemosTest*

**Comment by raybejjani** [comment]
test-gke K8sDemosTest*

**Comment by raybejjani** [comment]
test-gke K8sDemosTest*

**Comment by raybejjani** [comment]
test-gke K8sDemosTest*

**Comment by raybejjani** [comment]
test-gke K8sDemosTest*

**Comment by raybejjani** [comment]
test-gke K8sDemosTest*

**Comment by raybejjani** [comment]
test-gke K8sDemosTest*

**Comment by raybejjani** [comment]
test-gke K8sDemosTest*

**Comment by raybejjani** [comment]
test-gke K8sDemosTest*

**Comment by raybejjani** [comment]
test-gke K8sServicesTest External services To Services first endpoint creation match service by labels*

**Review by nebril — APPROVED** [review]

**Pull request merged**
