### PR TITLE
Add some missing alignchecker structs and new cilium-align-checker tool

### PR DESCRIPTION
**Pull request by joestringer**
Review commit-by-commit.

* Avoid stack limits in the BPF program with too many map key/values.
* Refactor alignchecker so that a separate tool can run the same logic as the daemon (against the datapath maps).
* Support multiple golang structures referring to the same C structure.
* Add checks for policymap, eppolicymap, tunnelmap.
* Add tool to do standalone alignment checking.

To use the new tool:
```
$ make -C tools/alignchecker
$ make -C bpf/
$ tools/alignchecker/cilium-align-checker bpf/bpf_alignchecker.o
OK
```

Fixes: #7245

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7247)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

EDIT: Didn't remove some now-unnecessary imports. Fixed.

**Comment by joestringer** [comment]
test-me-please

Forgot to update the unit tests. Done.

**Comment by joestringer** [comment]
test-me-please

EDIT: Hit #7105. All the other tests appear green.

**Comment by joestringer** [comment]
I guess now that we nest the structure declarations inside their own nested code block, the unique names for the structs are not necessary and we can get rid of the iterator in `bpf_alignchecker.c`, but that's a totally cosmetic nit.

**Review by aanm — APPROVED** [review]

**Review by brb — APPROVED** [review]
Very nice, thanks!

**Comment by brb** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]
Great work!!

**Comment by joestringer** [comment]
Hit what looks (at a glance) like a recurrance of #6727. Not at all related to the code changed in this PR.

**Comment by tgraf** [comment]
`runtime.RuntimeFQDNPolicies CNAME follow` hit

**Pull request merged**
