### PR TITLE
[1.14] operator: propagate CiliumClusterConfig when in kvstore mode

### PR DESCRIPTION
**Pull request by hemanthmalla**
1.14 backport of https://github.com/cilium/cilium/pull/27109 to support running `kvstoremesh` in `kvstore` identity allocation mode. Currently cluster-config in local kvstore is only set by apiserver component of clustermesh-apiserver. In this config, we don't need to run apiserver component. So, without this commit remote clusters cannot discover cluster-id and will default to using 0 as cluster ID.

### CODE REVIEW

**Review by giorio94 — CHANGES_REQUESTED** [review]
The backport looks reasonable to me, being straightforward and extremely unlikely to introduce regressions.

Could you please just edit the commit message to link the upstream commit for consistency?

```
[ upstream commit 45174b3c97779a4288b59f6650d4d4b7d6380418 ]
```

You can also use `./contrib/backporting/cherry-pick 45174b3c9777` to automatically add it while cherry-picking the patch. And also fix the link in the PR description? The correct one is https://github.com/cilium/cilium/pull/27109.

**Review by youngnick — APPROVED** [review]
LGTM once @giorio94's changes are done.

**Comment by giorio94** [comment]
(i forgot to mention earlier, FYI the trigger phrase on the v1.14 branch is test-backport-1.14)

**Comment by hemanthmalla** [comment]
/test-backport-1.14

**Comment by hemanthmalla** [comment]
@giorio94 Thanks for catching that. Updated the commit and PR description.

**Review by giorio94 — APPROVED** [review]
Thanks!

**Comment by hemanthmalla** [comment]
Rebased to pull in https://github.com/cilium/cilium/commit/c5ab76b94292e4cc8000698f66928969de2ec3e5

**Comment by hemanthmalla** [comment]
/test-backport-1.14

**Review by ldelossa — APPROVED** [review]

**Pull request merged**
