### PR TITLE
v1.12: Update Go to 1.18.7

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.12

**Review by sayboras — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Review by ti-mo — APPROVED** [review]

**Comment by sayboras** [comment]
/test-1.18-4.9

**Comment by sayboras** [comment]
/test-1.20-4.9

**Comment by sayboras** [comment]
/ci-l4lb-1.12

**Comment by sayboras** [comment]
/test-backport-1.12

**Comment by sayboras** [comment]
/test-1.20-4.9

**Comment by aanm** [comment]
/test-backport-1.12

**Comment by pippolo84** [comment]
/test-1.17-4.9

**Comment by pippolo84** [comment]
/test-1.17-4.9

**Comment by pippolo84** [comment]
/test-1.18-4.9

**Comment by pippolo84** [comment]
/test-1.19-4.9

**Comment by pippolo84** [comment]
/test-1.21-4.9

**Comment by pippolo84** [comment]
/test-1.22-4.9

**Comment by pippolo84** [comment]
/test-1.22-5.4

**Comment by pippolo84** [comment]
/test-1.19-4.9

**Comment by pippolo84** [comment]
All required checks are passing (failed tests are unrelated and they were incorrectly requested with the `/test` comment), reviews are in, marking ready to merge.

**Pull request merged**
