### PR TITLE
ServicesAPI: update backendByHash of all relevant svcs after updateBackendsState

### PR DESCRIPTION
**Pull request by strudelPi**
Previously on backends update only the Service's (handler) backendByHash would be updated, but not the ones inside the svcInfo for each service.

This is important since the service svcInfo's backendByHash value is used to determine the state of the backend for that particular service (e.g. in upsertService).

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

We have experienced issue after changing a state of a backend through the [service API](https://docs.cilium.io/en/stable/api/#put--service-id) with the `updateServices` flag. This goes through fine but some subsequent service updates seem to ignore the backend state change.

[Here](https://github.com/cilium/cilium/blob/b53db76dfc2dbb8e3e8582de73d7fb9569a0dede/pkg/service/service.go#L822) the `backends` structure seems to be correctly updated when the backend state occurs, but the  `backendByHash` seems to be forgotten. As per commit message, the `backendByHash` is used by [upsertService](https://github.com/cilium/cilium/blob/b53db76dfc2dbb8e3e8582de73d7fb9569a0dede/pkg/service/service.go#L644) (later in the upsert used [here](https://github.com/cilium/cilium/blob/b53db76dfc2dbb8e3e8582de73d7fb9569a0dede/pkg/service/service.go#L1557).

### CODE REVIEW

**Comment by strudelPi** [comment]
Converting to draft. Some test should probably be added so that this bug cannot occur again.

**Review by aditighag — COMMENTED** [review]
Good catch! Thanks for the fix. Do you mind adding a new test case to validate updates to backend states instead of extending an existing one?

**Comment by strudelPi** [comment]
> Good catch! Thanks for the fix. Do you mind adding a new test case to validate updates to backend states instead of extending an existing one?

hey @aditighag, I suppose I can move it to a new test, I was also comtemplating on what are all the structures that should be checked. 

I have one blocker right now though. I feel like I extended the test correctly, but as I checked to make sure if it breaks before my fix .... it doesn't. So far I realised that we are not initialising the backends correctly in that test module, since if you try to call the `Hash()` on the existing backends in this test, they return an empty string, which surely is wrong. Let me know if you have any thoughts on this.

**Comment by strudelPi** [comment]
Closing in favor of this PR https://github.com/cilium/cilium/pull/24474

**Pull request closed without merging**
