### PR TITLE
Add support for k8s 1.28

### PR DESCRIPTION
**Pull request by aanm**
Update libraries for k8s 1.28 by updating all the libraries.

### CODE REVIEW

**Review by tklauser — APPROVED** [review]
Looks good for my codeowners.

**Review by nathanjsweet — APPROVED** [review]
Why did you move kindest to quay.io?

**Comment by aanm** [comment]
> Why did you move kindest to quay.io?

@nathanjsweet that's a good question. There aren't any builds for RCs in kindest so we had to build one and push it to quay.io. I'll write a rewrite a guide on the process to update k8s versions which will include this step.

**Comment by aanm** [comment]
> > Why did you move kindest to quay.io?
> 
> @nathanjsweet that's a good question. There aren't any builds for RCs in kindest so we had to build one and push it to quay.io. I'll write a rewrite a guide on the process to update k8s versions which will include this step.

@nathanjsweet as promised https://github.com/cilium/cilium/pull/29079 :angel:

**Pull request merged**
