### PR TITLE
v1.8 backports 2021-01-26

### PR DESCRIPTION
**Pull request by pchaigno**
* #14626 -- helm: set dnsPolicy based on etcd.k8sService (@aanm)
    - Some minor conflicts due to the Helm refactoring in v1.9.
 * #14684 -- contrib/release: clarify project number for release process (@aanm)
 * #14679 -- pkg/node: Skip setting MTU on local node routes (@aditighag)
 * #14649 -- bpf: Send packet drop notify for LB DSR mode failures. (@hzhou8)
    - Some minor conflicts.
 * #14677 -- hubble: parser: Set Encrypted bit correctly (@tgraf)
 * #14451 -- Extend K8sVerifier to maximize program sizes on 4.19 and net-next kernels (@pchaigno)
    - Many conflicts in bpf/Makefile
    - Removed options added in v1.9 (BPF host routing, BPF TProxy, Maglev, and bandwidth manager).
    - I did not backport the last commit, as it's only needed to workaround https://github.com/cilium/cilium/issues/14234 on master.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14626 14684 14679 14649 14677 14451; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Review by aditighag — APPROVED** [review]
My changes look good. Thanks!

**Comment by pchaigno** [comment]
test-backport-1.8

**Comment by pchaigno** [comment]
test-backport-1.8

**Review by aanm — APPROVED** [review]
Looks good for my commits. Thank you!

**Review by joestringer — APPROVED** [review]

**Pull request merged**
