### PR TITLE
examples/kubernetes: change Cilium init image to Cilium image

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

Follow up of https://github.com/cilium/cilium/pull/8489

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8522)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
The K8s-1.10 tests got into a weird state (including NodeLost?): https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13558/

**Comment by ianvernon** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
