### PR TITLE
1.2 backports 19-01-18

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:

* PR: 5869 -- endpoint: signal when BPF program is compiled for the first time (@ianvernon) -- https://github.com/cilium/cilium/pull/5869

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6690)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
Build failed due to VM boot stage timing out: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9142/

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
