### PR TITLE
istio: Update to release 1.10.3

### PR DESCRIPTION
**Pull request by jrajahalme**
Update Cilium Istio integration to Istio release 1.10.3.

```release-note
Cilium Istio integration is updated to Istio release 1.10.3.
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-only --focus="K8sIstioTest"

**Comment by jrajahalme** [comment]
test-only --focus="K8sIstioTest"

**Comment by jrajahalme** [comment]
test-only --focus="K8sIstioTest"

**Comment by jrajahalme** [comment]
test-only --focus="K8sIstioTest"

**Comment by jrajahalme** [comment]
test-only --focus="K8sIstioTest"

**Comment by jrajahalme** [comment]
test-only --focus="K8sIstioTest"

**Comment by jrajahalme** [comment]
test-only --focus="K8sIstioTest"

**Comment by jrajahalme** [comment]
test-me-please

**Review by qmonnet — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by jrajahalme** [comment]
ci-awscni

**Comment by jrajahalme** [comment]
ci-aks

**Comment by jrajahalme** [comment]
ci-eks

**Comment by jrajahalme** [comment]
ci-gke

**Comment by jrajahalme** [comment]
started some required CI tests, but those will not exercise Istio images, so marking this ready-to-merge.

**Pull request merged**
