### PR TITLE
[1.13] Address selectorcache concurrent read/write

### PR DESCRIPTION
**Pull request by tklauser**
See commit message for details.

v1.13 version of #29167

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.13

**Comment by tklauser** [comment]
/test-backport-1.13

**Comment by tklauser** [comment]
/test-1.16-4.19

**Comment by tklauser** [comment]
/test-1.16-4.19

**Comment by tklauser** [comment]
/test-1.17-4.19

**Comment by tklauser** [comment]
test-1.20-4.19

**Comment by tklauser** [comment]
/test-1.20-4.19

**Comment by tklauser** [comment]
/test-1.20-4.19

**Review by bimmlerd — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Pull request merged**
