### PR TITLE
Fix gke zone in release cluster script

### PR DESCRIPTION
**Pull request by nebril**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10109)

### CODE REVIEW

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by nebril** [comment]
test-gke K8sDemos*

**Review by raybejjani — APPROVED** [review]

**Comment by nebril** [comment]
test-gke K8sDemos*

**Comment by joestringer** [comment]
@nebril @raybejjani is there a reason we're not backporting this to v1.7?

**Pull request merged**
