### PR TITLE
Vagrant: Update base box version

### PR DESCRIPTION
**Pull request by eloycoto**
Update envoy deps cache based on commit https://github.com/cilium/cilium/commit/20b44e8c2923865a87dc81b90e4296abafcf5b34

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-nightly

**Review by ianvernon — APPROVED** [review]
LGTM, will wait until builds have succeeded to merge.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
The missed-K8s build failed due to timeout; looks like timeout in `ginkgo-kubernetes-all.Jenkinsfile` needs to be increased.

**Comment by ianvernon** [comment]
I think we can merge this since the issue with test-missed-k8s is due to timeout (Jenkinsfile configuration) and the VMs booted / Cilium compiled just fine. @eloycoto what do you think?

**Comment by eloycoto** [comment]
+1

**Pull request merged**
