### PR TITLE
Remove unused jenkinsfiles

### PR DESCRIPTION
**Pull request by aanm**

### CODE REVIEW

**Review by nbusseneau — APPROVED** [review]
https://i.kym-cdn.com/entries/icons/original/000/006/077/so_good.png

**Review by pchaigno — APPROVED** [review]
Do we need to trigger k8s-all & k8s-upstream just to double check this PR doesn't break anything?

**Review by nebril — APPROVED** [review]

**Comment by nebril** [comment]
test-upstream-k8s

**Comment by nebril** [comment]
confirmed that upstream k8s job is able to load jenkinsfile, marking as ready to merge

**Pull request merged**
