### PR TITLE
Test: Enable Cilium Update test

### PR DESCRIPTION
**Pull request by eloycoto**
- Use cilium/cilum:v1.0 to update
- Delete scale command. It'll fail with 5 or 8 containers.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by ianvernon** [comment]
> Delete scale command. It'll fail with 5 or 8 containers.

Can you elaborate on this please?

**Comment by eloycoto** [comment]
@ianvernon time to time, the scale option fails on Kubernetes: https://github.com/cilium/cilium/issues/3383

If the update from `cilium:stable` to master fails, it'll fail with 5 containers or 8. The number does not matter in this case.

**Comment by ianvernon** [comment]
@eloycoto OK, thanks. Can you rebase this and run the tests one more time? I want to make sure that this test works against latest master as we made a significant change w.r.t. conntrack this morning.

**Comment by eloycoto** [comment]
test-me-please

**Pull request merged**
