### PR TITLE
[v1.14] Test upgrade/downgrade to patch release for IPsec

### PR DESCRIPTION
**Pull request by qmonnet**
- [x] #27977 (@michi-covalent)
- [x] #28016 (@jschwinger233)
- [x] #29072 (@brb)
- [x] #28815 (@qmonnet)

Related to
- #14882

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 27977 28016 29072 28815; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=27977,28016,29072,28815
```

### CODE REVIEW

**Comment by qmonnet** [comment]
/test-backport-1.14

**Comment by qmonnet** [comment]
/test-backport-1.14

**Review by michi-covalent — APPROVED** [review]
🚀🙏

**Review by christarazi — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by qmonnet** [comment]
/test-backport-1.14

**Comment by qmonnet** [comment]
/test-backport-1.14

**Review by brb — APPROVED** [review]
My changes LGTM, thanks.

**Comment by qmonnet** [comment]
/test-backport-1.14

**Comment by qmonnet** [comment]
/test-backport-1.14

**Review by lmb — APPROVED** [review]
🎩

**Review by pchaigno — APPROVED** [review]
Given your upstream PR is now merged and this has a conflict anyway, it might make sense to refer to the upstream commits in the "backported" commits here.

**Comment by aanm** [comment]
@qmonnet needs rebase

**Comment by qmonnet** [comment]
/test-backport-1.14

**Review by youngnick — APPROVED** [review]

**Pull request merged**
