### PR TITLE
helm: Remove chart fields planned for removal in 1.12

### PR DESCRIPTION
**Pull request by my-git9**
Remove chart fields planned for removal in 1.12

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]

**Comment by my-git9** [comment]
The error report of ci seems to have nothing to do with the modification of this pr.

**Comment by my-git9** [comment]
Could you give some help for the failed test, thanks? @sayboras

**Comment by sayboras** [comment]
Can you rebase with master ?

**Comment by my-git9** [comment]
> Can you rebase with master ?

OK

**Comment by my-git9** [comment]
> Can you rebase with master ?

Thanks, all test has been pass

**Pull request merged**
