### PR TITLE
Test: add top and ps aux on report failed.

### PR DESCRIPTION
**Pull request by eloycoto**
Added both commands to be able to debug when a test fails.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4666)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failed due to fun with apt:

```
    k8s2-1.7: Reading package lists...
    k8s2-1.7: E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
    k8s2-1.7: E: Unable to lock directory /var/lib/apt/lists/
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

        ===================== ERROR - VM PROVISION FAILED =====================

        Unable to provision and start VM "k8s2-1.7": exit status 1", vm, err

        =======================================================================
```

**Comment by ianvernon** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
