### PR TITLE
v1.10 backports 2022-02-22

### PR DESCRIPTION
**Pull request by jrajahalme**
* #18748 -- envoy: Update to release 1.21.0 (@jrajahalme)
 * #18899 -- envoy: Update to 1.21.1 (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18748 18899; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.10

**Comment by jrajahalme** [comment]
/test-backport-1.10

**Comment by joestringer** [comment]
Some sort of jenkins issues with this build: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.9/2021/console , re-kicking.

**Comment by joestringer** [comment]
/test-1.19-4.9

**Comment by joestringer** [comment]
Eleven failures:                                                                
                                                                                
* Code scanning results / CodeQL Failing after 2s — 19 new alerts including 19 high severity security vulnerabilities
[Details](https://github.com/cilium/cilium/pull/18890/checks?check_run_id=5298075223)[](https://github.com/apps/github-actions)
  * Caused by @codeql arbitrarily changing their alert ruling, not marked required. Ignoring.
* Conformance AWS-CNI (ci-awscni-1.10) — Connectivity test failed               
Required                                                                        
[Details](https://github.com/cilium/cilium/actions/runs/1885081254)[](https://github.com/apps/github-actions)
  * Caused by https://github.com/cilium/cilium-cli/issues/719 , ignoring        
* ConformanceEKS (ci-eks-1.10) — Connectivity test failed                       
Required                                                                        
[Details](https://github.com/cilium/cilium/actions/runs/1885081253)[](https://github.com/apps/github-actions)
  * Caused by https://github.com/cilium/cilium-cli/issues/719 , ignoring        
* ConformanceGKE (ci-gke-1.10) — Connectivity test failed                       
Required                                                                        
[Details](https://github.com/cilium/cilium/actions/runs/1885081242)[](https://github.com/apps/github-actions)
  * Caused by https://github.com/cilium/cilium-cli/issues/719 , ignoring        
* External workloads (ci-external-workloads-v1.10) — Connectivity test failed   
[Details](https://github.com/cilium/cilium/actions/runs/1885081257)[](https://github.com/apps/github-actions)
  * Caused by https://github.com/cilium/cilium-cli/issues/719 , ignoring        
* Multicluster / Cluster mesh (ci-multicluster-1.10) — Connectivity test failed 
Required                                                                        
[Details](https://github.com/cilium/cilium/actions/runs/1885081248)[](https://github.com/ciliumbot)
  * Caused by https://github.com/cilium/cilium-cli/issues/719 , ignoring        
* gke-stable (test-gke) — Build finished.                                       
Required                                                                        
[Details](https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/7703/)[](https://github.com/ciliumbot)
  * Caused by test issue https://github.com/cilium/cilium/issues/18912 , ignoring
* k8s-1.16-kernel-netnext (test-1.16-netnext) — Build finished.                 
Required                                                                        
[Details](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/2243/)[](https://github.com/ciliumbot)
  * Looks a lot like known flake #18520, ignoring                               
* k8s-1.18-kernel-4.9 (test-1.18-4.9) — Build finished.                         
Required                                                                        
[Details](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.18-kernel-4.9/1921/)[](https://github.com/ciliumbot)
  * Hit time limit. Lots of complaints about kube-dns not being ready, cilium-health routing issues. Filed #18913.
* k8s-1.19-kernel-5.4 (test-1.19-5.4) — Build finished.                         
Required                                                                        
[Details](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-5.4/1419/)[](https://github.com/ciliumbot)
  * Looks like known flake #18873.                                              
* runtime (test-runtime) — Build finished.                                      
Required                                                                        
[Details](https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1379/)[](https://github.com/apps/github-actions)                                                                                          
  * Timed out. Will be addressed when we backport #18886.

**Pull request merged**
