### PR TITLE
v1.11 backports 2022-04-11

### PR DESCRIPTION
**Pull request by jrajahalme**
* #18618 -- pull in the latest changes from github.com/vishvananda/netlink (@aditighag)
 * #19310 -- Test runtime cilium in container (take two) (@jrajahalme)
 * #19358 -- test: Fix whitespace in docker-run-cilium (@jrajahalme)
 * #19360 -- daemon: Restore old CIDR identities (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18618 19310 19358 19360; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.11

**Comment by jrajahalme** [comment]
Runtime test failing to start Envoy due to #19369 not having merged yet.

**Comment by jrajahalme** [comment]
Cherry-picked commits from https://github.com/cilium/cilium/pull/19370 here (6 first commits) to be able to run the new test verifying local identity restoration.

**Comment by jrajahalme** [comment]
//test-backport-1.11

**Comment by jrajahalme** [comment]
Format of `cilium bpf ipcache list -o json` is different from master, amended.

**Comment by jrajahalme** [comment]
/test-backport-1.11

**Comment by nbusseneau** [comment]
/test-1.19-4.9

**Comment by nbusseneau** [comment]
https://github.com/cilium/cilium/actions/runs/2153808115

External workloads hit an issue during DNS verification:

```
Run gcloud compute ssh cilium-cilium-2153808115-vm --zone us-west2-a \
Server:		169.254.169.254
Address:	169.254.169.254#53

** server can't find clustermesh-apiserver.kube-system.svc.cluster.local: NXDOMAIN
```

Could this be a legitimate failure?

Quick look at agent logs shows this fatal error message:

```
 2022-04-12T09:06:38.940189722Z level=fatal msg="Unable to mount BPF filesystem" error="multiple mount points detected at /sys/fs/bpf" subsys=bpf
```

**Comment by jrajahalme** [comment]
> https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1864/testReport/junit/(root)/Suite-runtime/RuntimeKafka_Kafka_Policy_Role_Egress/
> 
> Runtime tests hit an issue during Kafka testing:
> 
> ```
> /home/jenkins/workspace/Cilium-PR-Runtime-net-next/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:527
> Traffic in disallowTopic is allowed
> Expected
>     <*errors.errorString | 0xc00030c770>: {
>         s: "{disallowTopic=TOPIC_AUTHORIZATION_FAILED} is not in the output after timeout: 4m0s timeout expired",
>     }
> to be nil
> /home/jenkins/workspace/Cilium-PR-Runtime-net-next/runtime-gopath/src/github.com/cilium/cilium/test/runtime/kafka.go:213
> ```
> 
> Could this be a legitimate failure?

Not related to these backports.

It seems Cilium agent crashed after the policy was set up, and before the disallowTopic was tried out. Monitor logs have bunch of allowTopic logs, but then the monitoring stops on message:
```
[33mWARN[0m[0008] connection closed                             [33merror[0m=EOF
```

Agent logs (`container_cilium.log`): has this happening sometime after the Kafka policy is set up:
```
level=info msg="[cilium.bpf_metadata: setRequestedApplicationProtocols(..., kafka)" subsys=envoy-config threadID=1092
level=info msg="[cilium.bpf_metadata: setRequestedApplicationProtocols(..., kafka)" subsys=envoy-config threadID=1096
level=info msg="[cilium.bpf_metadata: setRequestedApplicationProtocols(..., kafka)" subsys=envoy-config threadID=1096
level=info msg="[cilium.bpf_metadata: setRequestedApplicationProtocols(..., kafka)" subsys=envoy-config threadID=1095
level=info msg="[cilium.bpf_metadata: setRequestedApplicationProtocols(..., kafka)" subsys=envoy-config threadID=1093
level=info msg="[cilium.bpf_metadata: setRequestedApplicationProtocols(..., kafka)" subsys=envoy-config threadID=1096
level=debug msg="Registered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct4_global subsys=bpf
level=debug msg="Registered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct_any4_global subsys=bpf
level=debug msg="Registered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct6_global subsys=bpf
level=debug msg="Registered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct_any6_global subsys=bpf
level=debug msg="Unregistered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct_any6_global subsys=bpf
level=debug msg="Unregistered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct6_global subsys=bpf
level=debug msg="Unregistered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct_any4_global subsys=bpf
level=debug msg="Unregistered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct4_global subsys=bpf
level=debug msg="Registered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct4_00513 subsys=bpf
level=debug msg="Unregistered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ct4_00513 subsys=bpf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cc77db]

goroutine 1173 [running]:
github.com/cilium/cilium/pkg/maps/ctmap.doGC4(0xc000f48480, 0xc0010c3fa8)
	/go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:429 +0xbb
github.com/cilium/cilium/pkg/maps/ctmap.doGC(0x0, 0x26dab40)
	/go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:532 +0xf1
github.com/cilium/cilium/pkg/maps/ctmap.GC(0xc000f48480, 0xc0010c3fa8)
	/go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:552 +0x6c
github.com/cilium/cilium/pkg/maps/ctmap/gc.runGC(0xc000b32e00, 0x1, 0x1, 0x0, 0x1)
	/go/src/github.com/cilium/cilium/pkg/maps/ctmap/gc/gc.go:188 +0x58a
github.com/cilium/cilium/pkg/maps/ctmap/gc.Enable.func1()
	/go/src/github.com/cilium/cilium/pkg/maps/ctmap/gc/gc.go:96 +0x609
created by github.com/cilium/cilium/pkg/maps/ctmap/gc.Enable
	/go/src/github.com/cilium/cilium/pkg/maps/ctmap/gc/gc.go:39 +0x1e5
```

This may be due to the Kafka test setting Cilium to use CT maps per endpoint, while I have the impression we don't support that any more, so it may be buggy?
```

		status := vm.ExecCilium(fmt.Sprintf("config %s=true",
			helpers.OptionConntrackLocal))
		status.ExpectSuccess()
```

**Comment by nbusseneau** [comment]
> Not related to these backports.

OK, restarting runtime tests then.

**Comment by jrajahalme** [comment]
Runtime test setup hang on `Mounting NFS shared folders`, retesting

**Comment by jrajahalme** [comment]
Looks like external workload test fails due to DNS setup in the external workload not being correct. The install script says:
```
Cilium successfully started!
../run/systemd/resolve/stub-resolv.conf
updating systemd resolved with kube-dns IP 10.88.0.10
Removed /etc/systemd/system/multi-user.target.wants/systemd-resolved.service.
Removed /etc/systemd/system/dbus-org.freedesktop.resolve1.service.
Created symlink /etc/systemd/system/dbus-org.freedesktop.resolve1.service → /lib/systemd/system/systemd-resolved.service.
Created symlink /etc/systemd/system/multi-user.target.wants/systemd-resolved.service → /lib/systemd/system/systemd-resolved.service.
```

While the following failing DNS lookup says:
```
 ssh cilium-cilium-2153808115-vm --zone us-west2-a \
    --command "nslookup -norecurse clustermesh-apiserver.kube-system.svc.cluster.local"
  shell: /usr/bin/bash -e {0}
  env:
    clusterName: cilium-cilium-2153808115-vm
    vmName: cilium-cilium-2153808115-vm
    zone: us-west2-a
    vmStartupScript: .github/gcp-vm-startup.sh
    cilium_cli_version: v0.10.4
    check_url: https://github.com/cilium/cilium/actions/runs/2153808115
    CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
    GCLOUD_PROJECT: ***
    GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/cilium/cilium/a7cab0394f65a8904e317305
    GOOGLE_GHA_CREDS_PATH: /home/runner/work/cilium/cilium/a7cab0394f65a8904e317305
Server:		169.254.169.254
Address:	169.254.169.254#53

** server can't find clustermesh-apiserver.kube-system.svc.cluster.local: NXDOMAIN
```

Based on this it seems to me that the DNS request never gets to the kube-dns IP 10.88.0.10, but to 169.254.169.254 instead. If so it is no wonder that `clustermesh-apiserver.kube-system.svc.cluster.local` is not found.


This fail is not related to this backport PR, so we should disregard this fail for now.

**Comment by jrajahalme** [comment]
On Cilium 1.10 backport of these same commits external workload test succeeds to get DNS response:
```
Run gcloud compute ssh cilium-cilium-2153807352-vm --zone us-west2-a \
Server:		10.91.[17](https://github.com/cilium/cilium/runs/5986875667?check_suite_focus=true#step:17:17)6.10
Address:	10.91.176.10#53

Name:	clustermesh-apiserver.kube-system.svc.cluster.local
Address: 10.91.[18](https://github.com/cilium/cilium/runs/5986875667?check_suite_focus=true#step:17:18)5.184
```

**Comment by jrajahalme** [comment]
/ci-external-workloads-v1.11

**Review by tklauser — APPROVED** [review]

**Pull request merged**
