### PR TITLE
1.5 istio backports 26 07 2019

### PR DESCRIPTION
**Pull request by jrajahalme**
```release-note
Istio GSG updated to Istio release 1.2.2.
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8707)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-docs-please

**Comment by jrajahalme** [comment]
test-missed-k8s

**Comment by jrajahalme** [comment]
test-upstream-k8s

**Comment by jrajahalme** [comment]
test-upstream-k8s

**Comment by jrajahalme** [comment]
Re-opened #2588 due to the failure in test-upstream-k8s.

**Comment by jrajahalme** [comment]
The Cilium-kubernetes-upstream-test failure (#2588) is known problem in the v1.5 branch.

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
