### PR TITLE
More obvious how to achieve bpffs mounted by systemd.

### PR DESCRIPTION
**Pull request by Savemech**
Just 5 cents into Docs

### CODE REVIEW

**Review by aanm — CHANGES_REQUESTED** [review]
Thank you for the changes, we use the lteralinclude so we have the installation files always up to date with the documentation. It seems the problem was with the missing `[Install]`. Can you add it directly into that file here https://github.com/cilium/cilium/blob/master/contrib/systemd/sys-fs-bpf.mount?

The documentation won't need to be changed afterwards.

**Comment by tgraf** [comment]
> Thank you for the changes, we use the lteralinclude so we have the installation files always up to date with the documentation. It seems the problem was with the missing [Install]. Can you add it directly into that file here https://github.com/cilium/cilium/blob/master/contrib/systemd/sys-fs-bpf.mount?
> 
> The documentation won't need to be changed afterwards.

It's more than this, the unit file must be named correctly and we need to make this very clear. It's very hard not to dislike systemd.

**Comment by joestringer** [comment]
It looks like this PR is missing commit sign-offs, please provide this. By signing off on commits, it means you agree to the [Developer's certificate of origin](http://docs.cilium.io/en/latest/contributing/#developer-s-certificate-of-origin).

**Comment by Savemech** [comment]
@aanm I would happy to, but @tgraf explicitly explains why I did this in that manner.
@joestringer ugh that's a little confusing, should I commit with proper "sign" string?

**Comment by joestringer** [comment]
@Savemech yeah, on the commandline it's `git commit -s`. If you use another client, the form is like:

```Signed-off-by: My Name <myname@doma.in>```

**Review by tgraf — APPROVED** [review]

**Comment by Savemech** [comment]
Well, i just noticed my PR was merged, and broke wiki, by means urls arent showing correctly.
Could i send few more commits for fix?

**Comment by tgraf** [comment]
> Well, i just noticed my PR was merged, and broke wiki, by means urls arent showing correctly.
> Could i send few more commits for fix?

Yes. The changes are only in latest and are not included in the stable branch which is displayed in the docs by default. Feel free to send follow-up fixes.

**Pull request merged**
