### PR TITLE
v1.14 Backports - background node sync improvements

### PR DESCRIPTION
**Pull request by marseel**
* [x] #32577 (@marseel)
 * [x] #32630 (@marseel)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 32577 32630
```

### CODE REVIEW

**Comment by marseel** [comment]
/test-backport-1.14

**Comment by marseel** [comment]
/test-backport-1.14

**Review by giorio94 — APPROVED** [review]
/lgtm, thanks!

**Review by qmonnet — APPROVED** [review]

**Comment by qmonnet** [comment]
I understand deployments are proposed because the PR was initially opened against `main`, by mistake. Deployments are not necessary for this PR, I'll just go ahead, ignore them and merge.

**Pull request merged**
