### PR TITLE
v1.13 Backports 2024-03-06

### PR DESCRIPTION
**Pull request by giorio94**
* [x] #30928 (@giorio94)
 * [x] #30916 (@giorio94)
 * [x] #31198 (@giorio94)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30928 30916 31198
```

### CODE REVIEW

**Comment by giorio94** [comment]
/test-backport-1.13

**Comment by giorio94** [comment]
Need to backport https://github.com/cilium/cilium/pull/31198 as well to make sure that we use the variables from the target branch also in pull_request/push workflows.

**Comment by giorio94** [comment]
/test-backport-1.13

**Comment by jrajahalme** [comment]
/test-1.24-5.4

**Comment by jrajahalme** [comment]
/test-1.26-net-next

**Review by jrajahalme — APPROVED** [review]

**Comment by giorio94** [comment]
Releases are out, unblocking.

**Comment by giorio94** [comment]
@viktor-kurchenko Gentle ping :pray:

**Review by viktor-kurchenko — APPROVED** [review]

**Comment by viktor-kurchenko** [comment]
> @viktor-kurchenko Gentle ping 🙏

Approved, thanks!

**Pull request merged**
