### PR TITLE
bpf: remove bandwidth manager from 5.4 MAX_BASE_OPTIONS

### PR DESCRIPTION
**Pull request by jibi**
There's a known complexity issue in 5.4 kernels that is causing the
K8sVerifier test to always fail.

Disabling the bandwidth manager on these kernels will allow us to run
this test again while the complexity issue is sorted.

### CODE REVIEW

**Comment by jibi** [comment]
test-backport-1.9

**Comment by jibi** [comment]
k8s-1.16-kernel-4.9 hit https://github.com/cilium/cilium/issues/16813

**Review by brb — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
Are we tracking this issue somewhere specifically? Can you link that from the PR here? I appreciate getting a more reliable gauge on complexity on this kernel by unblocking this testing, but I'd like to check that we don't just sweep the issue under the rug and forget about it.

**Comment by jibi** [comment]
> Are we tracking this issue somewhere specifically? Can you link that from the PR here? I appreciate getting a more reliable gauge on complexity on this kernel by unblocking this testing, but I'd like to check that we don't just sweep the issue under the rug and forget about it.

@joestringer yep, this is tracked on https://github.com/cilium/cilium/issues/16925

**Pull request merged**
