### PR TITLE
Refactor and add bpf test scripts

### PR DESCRIPTION
**Pull request by joestringer**
* Refactor `common/tests` to `test/bpf`
* Fix existing perf event test to clean up after itself
* Add test that runs all of the probes in `bpf/`
* Add test that attempts to load all object files in `bpf/` to test verification

I'm not intending to push for these to be included in the CI at the moment, I've just found them useful for local validation before fleshing out more comprehensive datapath tests via ginkgo.

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]

**Comment by joestringer** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by jrfastab — APPROVED** [review]
Seems like a couple useful scripts. Looks good to me.

**Comment by joestringer** [comment]
`bpf/*.sh` changes are trivial, not concerned about getting rigorous `bpf-loader` team review.

**Review by borkmann — APPROVED** [review]

**Pull request merged**
