### PR TITLE
[Docs] Fix rbac links in upgrade guide

### PR DESCRIPTION
**Pull request by nebril**
Signed-off-by: Maciej Kwiek <maciej@covalent.io>

### CODE REVIEW

**Review by raybejjani — APPROVED** [review]
This probably should be backported too. I will add the tags.

**Comment by raybejjani** [comment]
oh, and it may need to be backported to the doc-1.0 branch as well, since that's what we currently serve

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-me-please

**Comment by raybejjani** [comment]
Oh, this was the PR! I'm really sorry! I thought i was merges and couldn't find it. I should have looked in the open PRs :/

**Pull request closed without merging**
