### PR TITLE
gateway-api: Bump to the latest version from upstream

### PR DESCRIPTION
**Pull request by sayboras**
This is to pick up the new format for conformance profile report, also a couple of new conformance tests.

Related: https://github.com/kubernetes-sigs/gateway-api/pull/2746

### CODE REVIEW

**Review by rolinh — APPROVED** [review]
vendor changes lgtm

**Review by tklauser — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by lmb — APPROVED** [review]

**Pull request merged**
