### PR TITLE
maps/metricsmap: fix cilium bpf metrics list output

### LINKED ISSUE #8072: cilium bpf metrics dump needs fixing
It needs to use the per-CPU dump instead. Issue is only present when the cli queries the map directly (not via daemon).

### PR DESCRIPTION
**Pull request by aanm**
As the metrics bpf map is the type of per CPU hash when performing a
lookup we need to provide the number of CPUs running to get all the
metrics stored in the BPF map.

Signed-off-by: André Martins <andre@cilium.io>

Fixes: https://github.com/cilium/cilium/issues/8072

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8080)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by nirmoy** [comment]
test-me-please

**Comment by tgraf** [comment]
What were the last 3 CI run failures related to?

**Comment by tgraf** [comment]
Digged in, failures were also instances of #7902

**Pull request merged**
