### PR TITLE
Revert and fix ip rules

### PR DESCRIPTION
**Pull request by NikAleksandrov**
This set is a second attempt at reverting the revert PR [#24756](https://github.com/cilium/cilium/pull/24756), which was reverting [#24288](https://github.com/cilium/cilium/pull/24288) and [#24577](https://github.com/cilium/cilium/pull/24577)

The upgrade problem mentioned in PR [#24756](https://github.com/cilium/cilium/pull/24756) was due to wrongfully assuming that DeleteRule()
was handling both IPv4 and IPv6. Turns out there was a specific DeleteRuleIPv6() function
which seems unnecessary, so there is 1 additional patch prior to the last revert which changes DeleteRule() and adds
a new family argument, then removes DeleteRuleIPv6(). The problem manifested only when both IPv4 and IPv6 were 
enabled due to the IPv6 rule deletion which was actually removing the IPv4 rule.

Note I have removed the "Revert revert" in the patch titles to make checkpatch happy.

The upgrade was tested as:
```
$ helm install cilium install/cilium/cilium --version 1.13.2 --namespace kube-system --set ipv6.enabled=true

<make sure ip -d rule show has "proto unspec">

$ helm upgrade cilium install/kubernetes/cilium  --set image.override=192.168.122.1:5000/cilium/cilium-dev:latest --set ipv6.enabled=true --namespace kube-system
# upgrade to a local registry with patched cilium image

<make sure ip -d rule show now has "proto kernel" and there is connectivity>
```

### CODE REVIEW

**Review by asauber — APPROVED** [review]
CLI owned changes LGTM

**Review by aanm — APPROVED** [review]
Thank you for taking a second look at this. I didn't review the code but I tested the changes and the upgrade / downgrade test doesn't fail :tada:

**Review by borkmann — APPROVED** [review]

**Review by brb — APPROVED** [review]

**Comment by kamikaze** [comment]
got the same problem with systemd and recommended networkd options don't help :/

**Comment by borkmann** [comment]
/test-1.16-4.19

**Comment by borkmann** [comment]
/test-1.24-5.4

**Comment by borkmann** [comment]
/test-1.25-4.19

**Comment by borkmann** [comment]
(net-next one hit https://github.com/cilium/cilium/issues/25605)

**Review by YutaroHayakawa — APPROVED** [review]

**Comment by julianwiedmann** [comment]
As note for a backport to v1.13

- we need to check for any additional usage of routing rules in `v1.13`, and fix those up as well. For instance I did stumble over [wireguard](https://github.com/cilium/cilium/blob/a124c1a5b9c8dd41c2b36dc448e6249e5139afe5/pkg/wireguard/agent/agent.go#L248).
- we need to check for upgrade scenarios, so that a v1.14 agent also considers new style of rules/routes. Again see [wireguard](https://github.com/cilium/cilium/blob/d68e6e5aaa6dc27fe324305710b68f9b6ef17657/pkg/wireguard/agent/agent.go#L665).

**Comment by jrajahalme** [comment]
Removing release blocker 1.14 as this is already in v1.14: https://github.com/cilium/cilium/commit/a63aabca29d5bc98f393b415bc5e84f59d1eceaf

**Comment by julianwiedmann** [comment]
I dropped the PR from the 1.13 backport queue for now, let's not set wrong expectations.

**Comment by mfoliveira** [comment]
Hi @nebril 

> nebril added this to Needs backport from main in 1.13.17 last week
> nebril removed this from Needs backport from main in 1.13.16 last week
> nebril removed this from Needs backport from main in 1.13.17 last week

Apparently, this indicates that attempts to queue this for backporting to 1.13.x are over; is that correct?

If at all possible, could you please describe the concerns? (e.g., CI regressions, regression potential, community help with the backport is needed)

Thank you, and have a great weekend!

**Pull request merged**
