### PR TITLE
bpf: fix test/bpf/unit-test segfault due to memcmp looping

### LINKED ISSUE #11255: "'stddef.h' file not found" in dev. VM
## Issue
Trying to run the unit tests from inside the dev. VM results in the following error:
```
In file included from unit-test.c:8:
/usr/include/stdlib.h:31:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
```
That error is happening because [we recently switched the compiler for the BPF unit tests to Clang](https://github.com/cilium/cilium/commit/1f0c4a995bf526fe82d5feb2347a61c40a467ac7). The dev. VM images (4.9 and net-next) don't include a full Clang, but only the strict minimum required to compile BPF programs.

## Workaround
The following steps, proposed by André for a similar issue on v1.7, work as a quick fix:
```
sudo mv /usr/bin/clang{,.bak}
sudo mv /usr/bin/llc{,.bak}
sudo apt-get install -y clang-7 llvm-7
sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-7/bin/clang 1000
sudo update-alternatives --install /usr/bin/llc llc /usr/lib/llvm-7/bin/llc 1000
```
To revert:
```
sudo mv /usr/bin/clang{.bak,}
sudo mv /usr/bin/llc{.bak,}
``` 

## Proper Fix
The proper fix requires to revert part of cilium/packer-ci-build#200, to be able to compile on x86 with Clang.

----
Reported-by: Nate Sweet <nathanjsweet@pm.me>

### PR DESCRIPTION
**Pull request by borkmann**
Jarno and Paul reported a segfault in the memcmp() test case for older clang:

  test/bpf/unit-test
  Makefile:216: recipe for target 'unit-tests' failed
  make[1]: *** [unit-tests] Segmentation fault
  make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium'
  Makefile:201: recipe for target 'tests' failed
  make: *** [tests] Error 2

It appears that we'll end up generating a loop, that is, (*) -> __bpf_memcmp() ->
__bpf_memcmp_builtin() -> __builtin_memcmp() -> memcmp() -> (*), meaning it will
end up selecting our memcmp() implementation from the same header. It seems clang
ends up generating calls between the two and then trashing the stack. Given the
way we implemented and use the optimized memcmp(), we can simply switch to the
__builtin_bcmp() instead, which also fixes the segfault. The man-page says 'The
bcmp() function returns 0 if the byte sequences are equal, otherwise a nonzero
result is returned.' This equals what we do here anyway.

Fixes: #11255
Reported-by: Jarno Rajahalme <jarno@covalent.io>
Reported-by: Paul Chaignon <paul@cilium.io>
Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]
LGTM, but don't we need some equivalent fix for other builtins in case Clang selects our implementation for them as well?

**Comment by pchaigno** [comment]
I doesn't fix #11255 though. We still need to include a full Clang in the dev. VM image.

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
retest-net-next

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
> I doesn't fix #11255 though. We still need to include a full Clang in the dev. VM image.

True, I'll do a PR to packer-ci now.

**Comment by borkmann** [comment]
> LGTM, but don't we need some equivalent fix for other builtins in case Clang selects our implementation for them as well?

So given this only ever happens for clang < 10 where we fall into this ifdef and never run into it from a BPF datapath PoV but potentially only from unit testing under these circumstances, I would say that we fix up the others should we ever run into them. Looks like so far the rest can be handled fine.

**Comment by pchaigno** [comment]
> I'll do a PR to packer-ci now.

Thanks! :bow: 

> So given this only ever happens for clang < 10 where we fall into this ifdef and never run into it from a BPF datapath PoV but potentially only from unit testing under these circumstances, I would say that we fix up the others should we ever run into them. Looks like so far the rest can be handled fine.

Yep, fair enough :smile:

**Comment by borkmann** [comment]
Related: https://github.com/cilium/cilium/issues/11255

**Comment by borkmann** [comment]
retest-runtime

**Comment by borkmann** [comment]
retest-4.19

**Comment by borkmann** [comment]
retest-4.19

**Comment by borkmann** [comment]
retest-4.19

**Comment by borkmann** [comment]
4.19 is currently broken in general, see #11737.

**Comment by borkmann** [comment]
Given rest is all green and it doesn't affect BPF datapath, lets proceed.

**Pull request merged**
