### PR TITLE
docs: update Kind installation documentation page

### LINKED ISSUE #14960: v1.9: Cilium is broken due to a kernel complexity issue when using Kind and a recent kernel
## Bug report

With recent kernels (it's the case with at least kernel 5.10), when using Kind, Cilium is broken on v1.9 due to a kernel complexity issue. The default options as suggested in [the kind installation page](https://docs.cilium.io/en/v1.9/gettingstarted/kind/#install-cilium) instruct to disable host services (`--set hostServices.enabled=false`) as this is not supported with Kind.

As PR #14951, marked for backport to v1.9, removes this limitation,  the installation documentation for Kind should be updated to instruct to instead enable host services which allows to bypass the kernel complexity issue.

### PR DESCRIPTION
**Pull request by Ankurk99**
This commit enable the host services by default which allows to bypass the kernel complexity issue. 

Fixes: #14960

### CODE REVIEW

**Review by qmonnet — CHANGES_REQUESTED** [review]
Thanks for your contribution!
Please make sure to address the other two occurrences in the file.

**Comment by Ankurk99** [comment]
> Thanks for your contribution!
> Please make sure to address the other two occurrences in the file.

Sorry, I just missed that.

**Review by qmonnet — APPROVED** [review]
Thanks!

**Review by brb — CHANGES_REQUESTED** [review]
Please extend the note below saying that the hostServices should be disabled when cgroupv1 enabled.

**Comment by qmonnet** [comment]
Labelling for backports based on the description in the linked issue.

**Review by rolinh — APPROVED** [review]

**Comment by brb** [comment]
I'm having a second thought on this. I _think_ that majority of users would still run with cgroupv1 enabled, and only few with cgroupv2 only. So for majority this would result in cilium-agent panicking. Also, before 1.10 we are going to fix the complexity issue which can be hit when the hostServices feature is disabled.

**Comment by Ankurk99** [comment]
> I'm having a second thought on this. I _think_ that majority of users would still run with cgroupv1 enabled, and only few with cgroupv2 only. So for majority this would result in cilium-agent panicking. Also, before 1.10 we are going to fix the complexity issue which can be hit when the hostServices feature is disabled.

Right. If the complexity issue is fixed then we will not need to enable hostSevices feature. So should we drop this PR for now?

**Comment by brb** [comment]
The complexity issue was fixed (https://github.com/cilium/cilium/pull/16084). We can close this PR (https://github.com/cilium/cilium/pull/15946#issuecomment-832556973).

**Pull request closed without merging**
