### PR TITLE
bpf, xdp: various optimizations for nodeport

### PR DESCRIPTION
**Pull request by borkmann**
See commit msg.

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-gke

**Review by jrfastab — APPROVED** [review]
lgtm

**Comment by borkmann** [comment]
(ci green)

**Review by christarazi — APPROVED** [review]
LGTM

**Review by joestringer — COMMENTED** [review]
:+1:

**Pull request merged**
