### PR TITLE
[v1.13-hf] background-sync: spread node updates over time

### PR DESCRIPTION
**Pull request by marseel**
Based on #32577 and #32630

There were some changes compared to these PRs:
- no context and closeChan instead
- no errors / health module handling
- no comment about a bug with the mutex order / https://github.com/cilium/cilium/pull/32606

### CODE REVIEW

**Comment by marseel** [comment]
@jschwinger233 Seems like your recent push to this branch broke tests:
```
 	 # github.com/cilium/cilium/pkg/datapath/linux/ipsec
	 pkg/datapath/linux/ipsec/ipsec_linux.go:721:19: cannot convert s.Dst.To16() (value of type "net".IP) to type [16]byte
	 pkg/datapath/linux/ipsec/ipsec_linux.go:729:18: cannot convert s.Dst.To16() (value of type "net".IP) to type [16]byte
```

**Review by tklauser — APPROVED** [review]
LGTM, thanks Marcel.

**Review by lmb — APPROVED** [review]

**Comment by marseel** [comment]
/test-1.21-4.19

**Comment by marseel** [comment]
/test-1.24-5.4

**Comment by marseel** [comment]
runtime failure confirmed to be due to vagrant being outdated on this branch: https://github.com/cilium/cilium/pull/32666

so merging this PR.

**Pull request merged**
