### PR TITLE
agent: fix incorrect deletion of veth host interfaces on bootstrap

### PR DESCRIPTION
**Pull request by giorio94**
When the cilium agent starts up, it takes care of removing possible veth interfaces that are considered a leftover from failed attempts to connect a container. This PR fixes an issue that caused the incorrect deletion of unrelated veth interfaces (especially in Kind clusters).

Specifically, this could occur due to ifindex clashes, with the real parent of a given interface residing in a different network namespace, while another interface with the same index was also present in the current namespace. Notably, this may happen within Kind nodes, as eth0 is a veth interface itself, its parent resides in the root namespace, and an lxcxxxxxx interface might be present with the same ifindex inside the Kind node. If so, eth0 was previously detected as leftover and deleted, with the obvious ill-fated consequences. To detect ifindex clashes, the logic is changed to check whether the parent of the parent interface is actually the interface itself (which cannot hold true if the actual parent resides in a different namespace).

@reviewers I've currently marked the PR for backport to all supported versions since this might be the cause for hard to detect flakes in the CI upon agent restart (which is the reason why I discovered this issue in the first place). Feel free to unmark it if you think that not to be appropriate.

```release-note
agent: fix incorrect deletion of veth host interfaces on bootstrap
```

### CODE REVIEW

**Comment by giorio94** [comment]
ci-multicluster hit https://github.com/cilium/cilium/issues/21655
ci-gke hit https://github.com/cilium/cilium/issues/22368

**Comment by giorio94** [comment]
Smoke test with IPv6 hit https://github.com/cilium/cilium/issues/23812

**Review by dylandreimerink — APPROVED** [review]
LGTM

**Comment by giorio94** [comment]
/test-1.16-4.19

**Comment by giorio94** [comment]
k8s-1.16-kernel-4.19 hit https://github.com/cilium/cilium/issues/23845

**Comment by giorio94** [comment]
/test-1.16-4.19

**Review by pchaigno — APPROVED** [review]

**Pull request merged**
