### PR TITLE
*: use rlimit.RemoveMemlock() for setting RLIM_INFINITY

### PR DESCRIPTION
**Pull request by ti-mo**
Clean up the wide variety of ways in which memlock was bumped to infinity.

On newer kernels with memcg accounting, this becomes a no-op as it's no longer necessary to bump the rlimit.

Lowering the limit after e.g. a test suite or map creation is no longer done as there's arguably little point in doing so given the limit only applies to the current process and the getting/setting is inherently racy.

```release-note
Use `cilium/ebpf/rlimit` for bumping memlock rlimits
```

### CODE REVIEW

**Comment by ti-mo** [comment]
This needs a rebase onto https://github.com/cilium/cilium/pull/18578.

**Review by rolinh — APPROVED** [review]

**Review by joamaki — APPROVED** [review]

**Pull request merged**
