### PR TITLE
iptables: fix cilium_forward chain rules to support openshift

### PR DESCRIPTION
**Pull request by borkmann**
See commit msg.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9259)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Review by brb — APPROVED** [review]
LGTM.

Do you think it makes sense to limit the scope of the rules by adding `-m conntrack --ctstate ESTABLISHED,RELATED` just to match replies?

**Comment by borkmann** [comment]
> LGTM.
> 
> Do you think it makes sense to limit the scope of the rules by adding `-m conntrack --ctstate ESTABLISHED,RELATED` just to match replies?

I'd rather keep it simple and have it equivalent to the rules we already install, after all, Cilium's BPF datapath is responsible to perform the policy part, not netfilter. Perhaps with the rule in place, we could have avoided the whole going-through-the-stack-to-not-break-CT in BPF-based nodeport.

**Comment by borkmann** [comment]
Provision failure:
```12:57:01      k8s1-1.11: a2a2197e145e: Waiting
12:57:01      k8s1-1.11: 36ac8c11a11f: Waiting
12:57:01      k8s1-1.11: ea67eaa7dd42: Waiting
12:57:01      k8s1-1.11: ecd7d9a67e26: Waiting
12:57:01      k8s1-1.11: 14408c8d4f9a: Verifying Checksum
12:57:01      k8s1-1.11: 14408c8d4f9a: Download complete
12:57:01      k8s1-1.11: 4b5cacb629f5: Verifying Checksum
12:57:01      k8s1-1.11: 4b5cacb629f5: Download complete
13:37:25  Cancelling nested steps due to timeout
13:37:25  Sending interrupt signal to process
13:37:25  Sending interrupt signal to process
13:37:26  Sending interrupt signal to process
13:37:26  Sending interrupt signal to process
13:37:28  script returned exit code 255
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // retry
Post stage
[Pipeline] script
[Pipeline] {
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
13:37:29  Failed in branch Boot vms K8s-1.11 net-next
13:37:29  script returned exit code 255```

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Same timeout:
```
[...]
13:55:17      k8s1-1.16: make[1]: Leaving directory '/go/src/github.com/cilium/cilium/plugins/cilium-cni'
13:55:17      k8s1-1.16: make[1]: Entering directory '/go/src/github.com/cilium/cilium/bpf'
13:55:17      k8s1-1.16: gcc -Wall -O2 -Wno-format-truncation -I include/ cilium-map-migrate.c -lelf -o cilium-map-migrate
14:42:03  Cancelling nested steps due to timeout
14:42:03  Sending interrupt signal to process
14:42:04  Sending interrupt signal to process
14:42:05  Sending interrupt signal to process
14:42:12  script returned exit code 255
14:42:14  script returned exit code 255
14:42:15  script returned exit code 255
[Pipeline] }
[Pipeline] }
[Pipeline] }
[Pipeline] // retry
[Pipeline] // dir
[Pipeline] // dir
[...]
```

**Comment by borkmann** [comment]
Stuck in `Waiting for next available executor on ‘baremetal’` for ~1hrs, retrying.

**Comment by borkmann** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Review by aanm — APPROVED** [review]

**Pull request merged**
