### PR TITLE
v1.14 Backports 2024-02-29

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
* [x] #30909 (@aanm)
 * [x] #30742 (@qmonnet)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30909 30742
```

### CODE REVIEW

**Comment by YutaroHayakawa** [comment]
/test-backport-1.14

**Review by aanm — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
Conformance Kind Envoy DaemonSet, Conformance Multi Pool IPAM: Timeout while initializing Cilium

**Comment by YutaroHayakawa** [comment]
Cilium IPsec upgrade: https://github.com/cilium/cilium/issues/29987
Conformance EKS: Timeout while fetching Cilium runtime information (i/o timeout).

**Review by qmonnet — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
/test-backport-1.14

**Review by ldelossa — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
[Cilium IPSec upgrade](https://github.com/cilium/cilium/actions/runs/8097631491): https://github.com/cilium/cilium/issues/29856
[Conformance AKS](https://github.com/cilium/cilium/actions/runs/8097630254): https://github.com/cilium/cilium/issues/31009
[Conformance Cluster Mesh](https://github.com/cilium/cilium/actions/runs/8097630418): https://github.com/cilium/cilium/issues/22749
[Conformance Ginkgo](https://github.com/cilium/cilium/actions/runs/8097630719): https://github.com/cilium/cilium/issues/22749

**Pull request merged**
