### PR TITLE
Fixing a few typos in intro.rst

### PR DESCRIPTION
**Pull request by didier-durand**
Hello there,
As per title
Didier
Signed-off-by: Didier Durand <durand.didier@gmail.com>

### CODE REVIEW

**Comment by pchaigno** [comment]
Hello again :smile: 
This pull request could probably be folded with the other you sent at the same time, to reduce notifications, builds, etc.

**Comment by didier-durand** [comment]
@pchaigno : Hi, you want only one ? I can. I just usually do 1 per different page: some projects like distinct PRs for different pages. You decide: just let me know.
Best
Didier

**Comment by pchaigno** [comment]
Only one would be enough. You can push this commit on top of your branch `lifeofpacket_typo_fix`.

For small, related fixes like this, we usually try to group them together to avoid noise (a lot of people receive notifications for every action on this repository).

**Comment by didier-durand** [comment]
Good, I'll remember it for the future and will move both into one. Didier

**Comment by didier-durand** [comment]
Closing : all changes moved to #1496

**Pull request closed without merging**
