### PR TITLE
ci: bump 4.19 image version

### PR DESCRIPTION
**Pull request by nebril**
Bump 4.19 image version

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-with-kernel

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-with-kernel

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-with-kernel

**Comment by nebril** [comment]
test-with-kernel

**Comment by nebril** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by nebril** [comment]
test-with-kernel

**Comment by nebril** [comment]
test-with-kernel

**Comment by nebril** [comment]
test-with-kernel

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
seems like no skipping was needed, 4.19 vagrant image is fixed now, bumping the version

**Pull request merged**
