### PR TITLE
resource: Work around a rare race in initial sync

### LINKED ISSUE #23079: CI: Travis: Unit test panic in TestResource_WithFakeClient
## CI failure

https://app.travis-ci.com/github/cilium/cilium/jobs/593210550

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   PANIC  package: github.com/cilium/cilium/pkg/k8s/resource • TestResource_WithFakeClient   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
panic: runtime error: invalid memory address or nil pointer dereference [recovered]            
	panic: runtime error: invalid memory address or nil pointer dereference                        
[signal SIGSEGV: segmentation violation code=0x1 addr=0x188 pc=0x1a6f9cd]                      
                                                                                               
goroutine 17 [running]:                                                                        
testing.tRunner.func1.2({0x1c8ce40, 0x31c3350})                                                
	/home/travis/.gimme/versions/go1.19.4.linux.amd64/src/testing/testing.go:1396 +0x24e           
testing.tRunner.func1()                                                                        
	/home/travis/.gimme/versions/go1.19.4.linux.amd64/src/testing/testing.go:1399 +0x39f           
panic({0x1c8ce40, 0x31c3350})                                                                  
	/home/travis/.gimme/versions/go1.19.4.linux.amd64/src/runtime/panic.go:884 +0x212              
github.com/cilium/cilium/pkg/k8s/resource_test.TestResource_WithFakeClient(0xc0004504e0)       
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/k8s/resource/resource_test.go:158 +0xbed  
testing.tRunner(0xc0004504e0, 0x20393f0)                                                       
	/home/travis/.gimme/versions/go1.19.4.linux.amd64/src/testing/testing.go:1446 +0x10b           
created by testing.(*T).Run                                                                    
	/home/travis/.gimme/versions/go1.19.4.linux.amd64/src/testing/testing.go:1493 +0x35f           
FAIL	github.com/cilium/cilium/pkg/k8s/resource	0.162s           
```

### PR DESCRIPTION
**Pull request by joamaki**
TestResource_WithFakeClient is sometimes failing due to seeing two Upserts instead of Upsert+Sync. This is due to the fact that we add the initial set of keys from the store to the queue when subscribing in Events() and the fact that adding to the store is happening before our event handler runs. The sequence of events looks like this:

  [informer 1/2] add object A to store
  [resource] subscribe and add object with key A to queue
  [resource] dequeue A and emit Event{Upsert, A}
  [informer 2/2] call AddFunc handler for A and queue A
  [resource] dequeue A and emit Event{Upsert, A}

Work around the issue by allowing the extra Upsert event in the test case.

Proper fix for this would be to either detect a duplicate using ResourceVersion, or implementing a custom (cache.Config) Process function that synchronizes the updating of the store with subscribing (e.g. pkg/k8s/informer/informer.go).

Fixes: #23079
Fixes: 4101e2c768 ("k8s: Add resource package")

### CODE REVIEW

**Comment by joestringer** [comment]
I marked this for backport to 1.13 since it looks like it will mitigate a unit test failure. If this relies on changes only in the master branch, feel free to remove the label.

**Review by tommyp1ckles — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]
LGTM

**Comment by pchaigno** [comment]
@joamaki Why were the end-to-end tests executed here? AFAICS, it's only affecting the non-privileged unit tests which run in Travis CI. Is that was a mistake, I can probably merge.

**Comment by joamaki** [comment]
> @joamaki Why were the end-to-end tests executed here? AFAICS, it's only affecting the non-privileged unit tests which run in Travis CI. Is that was a mistake, I can probably merge.

Yep only Travis CI needed to check that the test passes. Go ahead and merge.

**Comment by julianwiedmann** [comment]
@joamaki is the backport for 1.13 still on your radar, or is it fine to drop that?

**Comment by julianwiedmann** [comment]
Taking that as a no :).

**Comment by joamaki** [comment]
@julianwiedmann oops, sorry about the delay (had half-answered this and then it got buried). Yes no need to backport to 1.13.

**Pull request merged**
