### PR TITLE
images/runtime: update runtime image

### PR DESCRIPTION
**Pull request by aanm**
Update runtime image to fix some potentially security vulnerabilities
detected by image scanners.

Signed-off-by: André Martins <andre@cilium.io>

```release-note
Update base image to fix potential security vulnerabilities detected by image scanners.
```

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.10

**Review by joestringer — APPROVED** [review]

**Comment by aanm** [comment]
test-1.19-5.4

**Comment by aanm** [comment]
test-1.17-4.9

**Comment by aanm** [comment]
test-1.19-5.4

**Pull request merged**
