### PR TITLE
v1.12 backports 2023-02-14

### PR DESCRIPTION
**Pull request by pchaigno**
- [ ] #23333 -- clustermesh, kvstore: consistently pass controller context to kvstore operations (@tklauser)
     - Trivial conflict.
 - [x] #23202 -- Introduce node IDs (@pchaigno)
     - Major conflicts on unit tests.
     - Minor conflicts elsewhere.
 - [ ] #23404 -- docs: correct Prometheus port (@lizrice)
 - [x] #23480 -- test: Update policy for hairpin flow validation (@aditighag)
 - [x] #22797 -- bugtool: Dump envoy metrics for troubleshooting (@sayboras)
     - Trivial conflict.
 - [x] #23118 -- docs: Drop sphinxcontrib-openapi fork, switch back to upstream (@qmonnet)
     - Minor conflict. I had to reapply the changes manually as the requirements.txt file changed a lot.
 - [x] #23506 -- cilium-health status: fix endpoint reachability in succinct view (@giorio94)
 - [x] #23578 -- Node ID restoration (@pchaigno)
     - Trivial conflict on first commit. I had to declare ebpf.Hash.
 - [x] #23706 -- Fix RKE doc link (@raphink)
 - [x] #23669 -- docs: replace usage of api.twitter.com (@kaworu)
 - [x] #23728 -- Remove / in RKE doc link as it causes redirect bug (@raphink)
 - [x] #23713 -- ipam/crd: Fix panic due to concurrent map read and map write (@gandro)
 - [ ] #23709 -- helm: Add support of annotations in hubble ui service (@brnck)
 - [x] #23740 -- workflow: fixes LLVM, Clang cache and install path (@brlbil)
     - Minor conflict in .github/workflows/lint-bpf-checks.yaml.

Skipped due to conflicts:

 - [ ] #23537 -- init.sh: clean up cgroup bpf_links created by newer versions of Cilium (@ti-mo)
     - Some conflicts and didn't seem worth it :/ 

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 23333 23202 23404 23480 22797 23118 23506 23578 23706 23669 23728 23713 23709 23740; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
Thanks. My commit looks good

**Review by qmonnet — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
Looks good for my changes, thanks :100:

**Review by brlbil — APPROVED** [review]

**Review by kaworu — APPROVED** [review]
My patches LGTM, thanks @pchaigno!

**Review by gandro — APPROVED** [review]
My commit looks good, thanks!

**Review by nathanjsweet — APPROVED** [review]
LGTM for API

**Comment by pchaigno** [comment]
/test-1.16-4.9

**Comment by raphink** [comment]
The RKE doc LGTM

**Review by aditighag — APPROVED** [review]
Thanks!

**Pull request merged**
