### PR TITLE
cni: Change default configuration filename to 00-cilium.conf

### PR DESCRIPTION
**Pull request by tgraf**
Various other plugins do not remove the configuration upon uninstallation which
then causes conflicts as kubelet picks the first CNI based on alphabetical
order. Change the default configuration filename to a prefix that should come
first. This is safe as Cilium properly removes the configure when the pod
exits.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4578)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by raybejjani** [comment]
Do we need to clean the old one too? we would begin leaving it behind if cilium is upgraded to this.

**Comment by tgraf** [comment]
> Do we need to clean the old one too? we would begin leaving it behind if cilium is upgraded to this.

`plugins/cilium-cni/cni-uninstall.sh` will automatically take care of this as the existing pod terminates

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
