### PR TITLE
cilium-dbg: Add "statedb node-addresses" command

### PR DESCRIPTION
**Pull request by joamaki**
Add the "cilium-dbg statedb node-addresses" command to dump the node-addresses table.

```
root@kind-control-plane:/home/cilium# cilium statedb node-addresses
Address                     NodePort   Primary   DeviceName
172.19.0.3                  true       true      eth0
fc00:c111::3                true       true      eth0
10.244.0.52                 false      false     cilium_host
fe80::44b9:b6ff:fe7e:4749   false      true      cilium_host
root@kind-control-plane:/home/cilium#
```

EDIT: Uh something is wrong here. The `10.244.0.52` should be marked as primary IPv4 address for cilium_host...
EDIT2: It was the `dev.Selected` check that I added this week that broke it. Will fix that in separate PR.
EDIT3: Fix in https://github.com/cilium/cilium/pull/29483

### CODE REVIEW

**Review by markpash — APPROVED** [review]

**Review by asauber — APPROVED** [review]
The abstraction available for this is very cool

**Pull request merged**
