### PR TITLE
Improve troubleshooting ability of endpoint creation

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7636)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Only `k8s-1.10.K8sIstioTest Istio Bookinfo Demo Tests bookinfo inter-service connectivity` failed. Trying again.

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
Hit known https://github.com/cilium/cilium/issues/7641

**Pull request merged**
