### PR TITLE
logging: expose more syslog options

### PR DESCRIPTION
**Pull request by jaffcheng**
Expose more syslog options via --log-opt to make syslog more configurable.
Before this commit we can only log to the default facility `kern`
of localhost, which may pollute kernel log file.
Also, add a fatal out logic to cilium-agent, cilium-operator and cilium-health,
if an error is returned from SetupLogging.

The following option keys are added:

    syslog.network
    syslog.address
    syslog.facility
    syslog.severity
    syslog.tag

configmap example for syslog driver: {"syslog.level":"info","syslog.facility":"local5","syslog.tag":"cilium-agent"}

Signed-off-by: Jaff Cheng <jaff.cheng.sh@gmail.com>

```release-note
Expose more syslog options
```

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Thanks!

**Review by twpayne — APPROVED** [review]
Nice, thank you!

**Comment by pchaigno** [comment]
test-me-please

**Comment by jaffcheng** [comment]
> test-me-please

Runtime CI failed as I missed the newly added Alibaba operator cmdref, rebased and updated

**Comment by pchaigno** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Comment by aanm** [comment]
For some reason jenkins didn't report the status. I've check and all have passed, only one flake found https://github.com/cilium/cilium/issues/15572. Merging...

**Comment by pchaigno** [comment]
(FYI, that flake is actually https://github.com/cilium/cilium/issues/15455.)

**Pull request merged**
