### PR TITLE
v1.3 backports 19 07 10

### PR DESCRIPTION
**Pull request by ianvernon**
* PR: 8352 -- CI: Cleanup VMs and reclaim disk on job completion (@raybejjani) -- https://github.com/cilium/cilium/pull/8352
 * PR: 8351 -- Workaround for systemd 242 assigning MAC addr for virtual devices (@brb) -- https://github.com/cilium/cilium/pull/8351
 * PR: 8358 -- CI: Clean VMs and reclaim disk in nightly test (@raybejjani) -- https://github.com/cilium/cilium/pull/8358
 * PR: 8443 -- Change nightly CI job label from fixed to baremetal (@nebril) -- https://github.com/cilium/cilium/pull/8443
 * PR: 8462 -- Retry provisioning vagrant vms in CI (@nebril) -- https://github.com/cilium/cilium/pull/8462
 * PR: 8477 -- [CI] retry vm provisioning, increase timeout (@nebril) -- https://github.com/cilium/cilium/pull/8477

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8517)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]

**Comment by jrajahalme** [comment]
VM provisioning failure:
```
09:34:02      k8s1-1.12: Some packages could not be installed. This may mean that you have
09:34:02      k8s1-1.12: requested an impossible situation or if you are using the unstable
09:34:02      k8s1-1.12: distribution that some required packages have not yet been created
09:34:02      k8s1-1.12: or been moved out of Incoming.
09:34:02      k8s1-1.12: The following information may help to resolve the situation:
09:34:02      k8s1-1.12: The following packages have unmet dependencies:
09:34:02      k8s1-1.12:  kubeadm : Depends: kubernetes-cni (>= 0.7.5) but 0.6.0-00 is to be installed
09:34:02      k8s1-1.12:  kubelet : Depends: kubernetes-cni (>= 0.7.5) but 0.6.0-00 is to be installed
09:34:02      k8s1-1.12: E
09:34:02      k8s1-1.12: : 
09:34:02      k8s1-1.12: Unable to correct problems, you have held broken packages.
09:34:02  The SSH command responded with a non-zero exit status. Vagrant
09:34:02  assumes that this means the command failed. The output for this command
09:34:02  should be in the log above. Please read the output to determine what
09:34:02  went wrong.
```

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Same provisioning failure in the new run, not a flake :-(

**Comment by ianvernon** [comment]
@jrajahalme I'm working on fixing the flake in another branch on top of v1.3

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
The failure observed ( https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13538/ ) is likely due to the fact that somewhere, debug was disabled, Cilium was restarted, and then because the option was enabled in the systemd configuration for Cilium, was enabled again. This is not worthy of running tests again IMO.

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Pull request merged**
