### PR TITLE
v1.9 backports 2020-10-31

### PR DESCRIPTION
**Pull request by joestringer**
* #13821 -- cilium: minor lb follow-ups (@borkmann)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13821; do contrib/backporting/set-labels.py \$pr done 1.9; done
```

### CODE REVIEW

**Comment by joestringer** [comment]
test-backport-1.9

**Comment by joestringer** [comment]
Green GKE run, testing again to see if it's reliably passing: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/3011/

**Comment by joestringer** [comment]
test-gke

**Comment by joestringer** [comment]
netnext provisioning failure: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/1033/execution/node/120/log/

**Comment by joestringer** [comment]
retest-net-next

**Comment by joestringer** [comment]
Second green GKE run: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/3012/

**Comment by joestringer** [comment]
test-gke

**Comment by joestringer** [comment]
Third green GKE run in a row: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/3013/

**Review by pchaigno — APPROVED** [review]

**Pull request merged**
