### PR TITLE
Golint fixes, removed dead code

### PR DESCRIPTION
**Pull request by nebril**
Fixed golint fixes that seemed fixable.
Fixed several shadowed occurences.
Fixed comment format
Fixed error formatting (removed punctuation and newlines from the end of
error messages)
Capitalised abbreviations in local variable names (didn't touch exported
types)
Removed dead code occurences
Changed receiver identifiers to be consistent in proxy package

Signed-off-by: Maciej Kwiek <maciej@covalent.io>

related: #153

### CODE REVIEW

**Comment by nebril** [comment]
@scanf please take a look. Should I split this PR into several smaller ones (one per package?). Or is that fine?

**Review by aalemayhu — CHANGES_REQUESTED** [review]
Would have been nice if your commit message was tidier, for example, a prefix
topic without spaces like `golint: ...` instead of `Golint fixes...`.  Also
listing the changes as bullet points make it easier to read IMO. Using
prefixes like `o` or `*` is enough.

For grouping would focus on the specific change vs which package it belongs in.
So one commit per lint change for all files, makes it easier to review. Have seen all of the lint messages before, so current is fine.

Can you fix the remaining issues reported by the bot and force push? Should be fine to merge when the build passes again.

Thanks.

**Comment by nebril** [comment]
@scanf thanks, will do

**Comment by nebril** [comment]
@scanf done, please re-review

**Review by aalemayhu — APPROVED** [review]
LGTM

**Pull request merged**
