### PR TITLE
v1.12 Backports 2023-11-27

### PR DESCRIPTION
**Pull request by gandro**
* [ ] #29335 (@gandro)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 29335
```

### CODE REVIEW

**Comment by gandro** [comment]
/test-backport-1.12

**Comment by gandro** [comment]
/test-1.16-4.9

**Comment by gandro** [comment]
/test-1.19-4.9

**Comment by gandro** [comment]
/test-1.16-4.9

**Review by youngnick — APPROVED** [review]

**Comment by gandro** [comment]
/test-1.16-4.9

**Pull request merged**
