### PR TITLE
[v1.8]: pkg/k8s: add pod IP event change

### PR DESCRIPTION
**Pull request by aanm**
[ upstream commit e92dc6ac6b766e793091410d0cf58c61b01d424d ]

This is a follow up of 6bd98ad7e443 ("handle IP addresses modification in running nodes and CEPs")
for more information read the commit description of that commit.

Signed-off-by: André Martins <andre@cilium.io>

 * #16190 -- pkg/k8s: add pod IP event change (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16190; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.8

**Comment by aanm** [comment]
test-backport-1.8

**Comment by joamaki** [comment]
test-1.15-4.9

**Comment by joamaki** [comment]
Failed earlier with `06:20:01   	 go: RLock /cilium/go.mod: no locks available`, which is a NFS error. Kicked it off again.

**Review by joamaki — APPROVED** [review]

**Pull request merged**
