### PR TITLE
add initial support for k8s 1.18

### PR DESCRIPTION
**Pull request by aanm**
k8s 1.18 had a lot of changes in the client-go library by including a
context.Context argument for the kube-apiserver interactions, for this
reason lots of files in cilium had to be modified to account for this
changes.

Some follow ups are still required since most of those context.Context
are now using context.TODO() which they require a deeper look
case-by-case.

Also, k8s.io/client-go/tools/metrics/metrics.go:L50-L59 has more metrics
that can be exposed which will also be done as a follow up, this commit
was entirely made to have an almost atomic upgrade of the k8s library
from 1.17 to 1.18 so we can start testing the compatibility with k8s
1.18.

The upstream tests were also failing because we have a delay to change
the pod identity when a label changes. This delay is set with the option
'identity-change-grace-period' which has a default of 5 seconds. To make
the tests pass we have set this delay to 0s in the k8s upstream tests 
provisioning.

Signed-off-by: André Martins <andre@cilium.io>

```release-note
add support for k8s 1.18
```

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Review by raybejjani — APPROVED** [review]

**Review by rolinh — APPROVED** [review]
LGTM  :+1: 

Would you mind documenting in the commit message why identity grace period related changes are necessary though?

**Comment by aanm** [comment]
Merging since the tests have passed for all k8s versions. The only change made was the commit message suggested by Robin.

**Pull request merged**
