### PR TITLE
Backport v1.12: CI: Add IPsec key rotation test

### PR DESCRIPTION
**Pull request by jschwinger233**
Manual backport of
- https://github.com/cilium/cilium/pull/26730 
- https://github.com/cilium/cilium/pull/27567
- https://github.com/cilium/cilium/pull/27203 
- https://github.com/cilium/cilium/pull/27883 

```upstream-prs
for pr in 26730 27567 27203 27883; do contrib/backporting/set-labels.py $pr done 1.12; done
```

Signed-off-by: Zhichuan Liang <gray.liang@isovalent.com>

### CODE REVIEW

**Comment by jschwinger233** [comment]
/test-backport-1.12

**Comment by jschwinger233** [comment]
/test-1.16-4.9

**Comment by jschwinger233** [comment]
/test-1.20-4.9

**Comment by ti-mo** [comment]
I got pinged as @cilium/tophat for `.github/actions/conn-disrupt-test/action.yaml` and `.github/ariane-config.yaml`.

Shouldn't these be assigned to @cilium/ci-structure or @cilium/github-sec instead, even on release branches?

I'll approve to get this out of the review queue.

**Review by ti-mo — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]

**Pull request merged**
