### PR TITLE
ipcache: keep upserted prefixes from being deleted by InjectLabels

### PR DESCRIPTION
**Pull request by squeed**
The "new" ipcache API (InjectLabels()) will delete a prefix if there are no metadata entries left. However, this behavior is not desirable when a user of the old APIs has taken control of this prefix. In order to prevent this, the field "createdFromMetadata" is set on all "new-style" prefixes to indicate they are safe to delete.

However, in the case where a prefix is first injected via the metadata layer, then transitions to the old APIs, it should not be deleted. In other words:

1. UpsertMetadata(A)
2. UpsertGeneratedIdentities(A)
3. RemoveMetadata(A)

should *not* delete A from the bpf ipcache, just the metadata layer.

This change prevents that by ensuring the bit is always set.

### CODE REVIEW

**Comment by squeed** [comment]
Split out from #28673 on @christarazi's request.

**Comment by squeed** [comment]
Requesting @gandro's review, as he approved the original commit.

**Review by gandro — APPROVED** [review]
Thanks!

**Pull request merged**
