### PR TITLE
v1.16: Remove leftover backporter state file

### PR DESCRIPTION
**Pull request by gandro**
This file was accidentally committed to the tree. It contains ephemeral state of the `backporter` tool and thus can be deleted.

Fixes: 92c110e58a7b ("gateway-api: Enqueue gateway for Reference Grant changes")

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Thanks

**Comment by gandro** [comment]
/test-backport-1.16

**Review by michi-covalent — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
LGTM. We could add it to .gitignore as well. 

cc also @nbusseneau (for the corresponding backports PR) as ideally we'd catch these things by looking at the commits being added to the tree before proposing them. We missed this during initial commit preparation as well as during the review process.

**Review by julianwiedmann — APPROVED** [review]

**Comment by gandro** [comment]
> LGTM. We could add it to .gitignore as well.

Agreed! That's a change for `main` to be backported to all branches ideally however

**Pull request merged**
