### PR TITLE
v1.9 backports 2020-11-23

### PR DESCRIPTION
**Pull request by joestringer**
* #14083 -- Improve the Helm readme (@joestringer)
  * Minor conflicts, resolved with context as the author of the PR.
 * #14111 -- Update troubleshooting docs for cilium-sysdump (@christarazi)
   * Minor conflict, accepted the new PR version of the docs to resolve.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14083 14111; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by joestringer** [comment]
test-backport-1.9

**Review by errordeveloper — APPROVED** [review]

**Comment by errordeveloper** [comment]
@joestringer would you entertain the possibility of including #14134 also?

**Comment by joestringer** [comment]
@errordeveloper makes sense to backport that, we can roll that PR into the next round of backports.

**Comment by joestringer** [comment]
Hit GKE issue: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/3373/

**Review by christarazi — APPROVED** [review]
LGTM for my commits

**Comment by joestringer** [comment]
retest-gke

**Comment by joestringer** [comment]
retest-gke

**Pull request merged**
