### PR TITLE
test: update k8s testing versions

### PR DESCRIPTION
**Pull request by aanm**
v1.10.0-beta.0 -> v1.10.0-beta.1

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Review by nebril — APPROVED** [review]

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Appears there is an issue with K8s 1.10, as it failed in the past two builds for the same reason.

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Pull request closed without merging**
