### PR TITLE
node: Remove check whether nextHop is in same L2

### LINKED ISSUE #14340: Cilium complains "IP is not L2 reachable" on startup
Cilium 1.9.1
Linux 5.9
GKE

Cilium logged this warning:
```
level=error msg="IP is not L2 reachable" error="iface: 'eth0' can't reach ip: '10.168.0.1'" interface=eth0 ipAddr=10.168.0.1 subsys=linux-datapath
```

As far as I can tell, this has no impact, it's just an extraneous warning.

Configmap:

```
$ kc get cm cilium-config -oyaml
apiVersion: v1
data:
  auto-direct-node-routes: "false"
  bpf-lb-map-max: "65536"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: ""
  cluster-name: default
  custom-cni-conf: "false"
  debug: "false"
  disable-cnp-status-updates: "true"
  enable-auto-protect-node-port-range: "true"
  enable-bandwidth-manager: "false"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "true"
  enable-bpf-tproxy: "true"
  enable-endpoint-health-checking: "true"
  enable-endpoint-routes: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-l7-proxy: "true"
  enable-local-node-route: "false"
  enable-local-redirect-policy: "false"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  hubble-socket-path: /var/run/cilium/hubble.sock
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  ipam: kubernetes
  kube-proxy-replacement: probe
  kube-proxy-replacement-healthz-bind-address: ""
  masquerade: "true"
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  native-routing-cidr: 10.4.0.0/14
  node-port-bind-protection: "true"
  operator-api-serve-addr: 127.0.0.1:9234
  preallocate-bpf-maps: "false"
  sidecar-istio-proxy-image: cilium/istio_proxy
  tunnel: disabled
  wait-bpf-mount: "false"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: cilium
  creationTimestamp: "2020-12-09T22:58:15Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cilium-config
  namespace: cilium
  resourceVersion: "9573"
  selfLink: /api/v1/namespaces/cilium/configmaps/cilium-config
  uid: 7aca0827-c0a6-4260-b2fa-5f243f49af1e
```

### PR DESCRIPTION
**Pull request by brb**
It was reported that on a GKE cluster the neigh handling logged the
following error:

    level=error msg="IP is not L2 reachable" error="iface: 'eth0' can't
    reach ip: '10.164.0.1'" interface=eth0 ipAddr=10.164.0.1
    subsys=linux-datapath

The "ip route" and "ip addr" had the following relevant entries:

    default via 10.164.0.1 dev eth0 proto dhcp metric 1024
    10.164.0.1 dev eth0 proto dhcp scope link metric 1024

    eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc mq state UP
    group default qlen 1000 link/ether 42:01:0a:a4:00:4f brd ff:ff:ff:ff:ff:ff
    inet 10.164.0.79/32 scope global dynamic eth0

As we can see, eth0 had IP addr assigned from /32 subnet which made the
check for nexthop in the same L2 to fail regardless of the "10.164.0.1
dev eth0" route.

This commit removes the check, as nexthop is guaranteed to be L2-reachable
by the Linux kernel routing system.

Reported-by: Joe Stringer <joe@cilium.io>
Reported-by: Paul Chaignon <paul@cilium.io>
Fix #14340

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Review by joestringer — CHANGES_REQUESTED** [review]
Thanks for the fix. Unfortunately it only uncovers another error message:
```
level=error msg="arping failed" error="iface: 'eth0' can't reach ip: '10.168.0.1'" interface=eth0 ipAddr=10.168.0.1 subsys=linux-datapath
```

ip a / r output:
```
root@gke-joe-k-e-default-pool-3a648787-jzsd:/home/cilium# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc mq state UP group default qlen 1000
    link/ether 42:01:0a:a8:0f:d4 brd ff:ff:ff:ff:ff:ff
    inet 10.168.15.212/32 scope global dynamic eth0
       valid_lft 55499sec preferred_lft 55499sec
    inet6 fe80::4001:aff:fea8:fd4/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:09:07:de:ab brd ff:ff:ff:ff:ff:ff
    inet 169.254.123.1/24 brd 169.254.123.255 scope global docker0
       valid_lft forever preferred_lft forever
269: lxc8096abd4fe4f@if268: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP group default qlen 1000
    link/ether a6:c4:40:c0:17:18 brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::a4c4:40ff:fec0:1718/64 scope link
       valid_lft forever preferred_lft forever
14: cilium_net@cilium_host: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP group default qlen 1000
    link/ether fa:af:b3:9d:7b:1d brd ff:ff:ff:ff:ff:ff
    inet6 fe80::f8af:b3ff:fe9d:7b1d/64 scope link
       valid_lft forever preferred_lft forever
15: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP group default qlen 1000
    link/ether da:66:61:ab:dd:1d brd ff:ff:ff:ff:ff:ff
    inet 10.4.0.96/32 scope link cilium_host
       valid_lft forever preferred_lft forever
    inet6 fe80::d866:61ff:feab:dd1d/64 scope link
       valid_lft forever preferred_lft forever
19: lxc1a931baa42f4@if18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP group default qlen 1000
    link/ether 3a:f7:44:a6:0b:7d brd ff:ff:ff:ff:ff:ff link-netnsid 5
    inet6 fe80::38f7:44ff:fea6:b7d/64 scope link
       valid_lft forever preferred_lft forever
21: lxc574d9323f605@if20: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP group default qlen 1000
    link/ether e2:d8:29:aa:7e:3a brd ff:ff:ff:ff:ff:ff link-netnsid 6
    inet6 fe80::e0d8:29ff:feaa:7e3a/64 scope link
       valid_lft forever preferred_lft forever
23: lxc6378cf6e1e51@if22: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP group default qlen 1000
    link/ether 72:dc:44:60:70:24 brd ff:ff:ff:ff:ff:ff link-netnsid 7
    inet6 fe80::70dc:44ff:fe60:7024/64 scope link
       valid_lft forever preferred_lft forever
27: lxcd16ce377228b@if26: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP group default qlen 1000
    link/ether be:dc:ce:eb:f7:7b brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::bcdc:ceff:feeb:f77b/64 scope link
       valid_lft forever preferred_lft forever
411: lxc644293a86df6@if410: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP group default qlen 1000
    link/ether e2:ba:69:54:a0:78 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::e0ba:69ff:fe54:a078/64 scope link
       valid_lft forever preferred_lft forever
413: lxc_health@if412: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP group default qlen 1000
    link/ether 6e:b3:6d:8a:18:fd brd ff:ff:ff:ff:ff:ff link-netns cilium-health
    inet6 fe80::6cb3:6dff:fe8a:18fd/64 scope link
       valid_lft forever preferred_lft forever
root@gke-joe-k-e-default-pool-3a648787-jzsd:/home/cilium# ip route
default via 10.168.0.1 dev eth0 proto dhcp src 10.168.15.212 metric 100
10.4.0.0/24 via 10.4.0.96 dev cilium_host src 10.4.0.96 mtu 1460
10.4.0.11 dev lxc6378cf6e1e51 scope link
10.4.0.25 dev lxc1a931baa42f4 scope link
10.4.0.64 dev lxc574d9323f605 scope link
10.4.0.89 dev lxc8096abd4fe4f scope link
10.4.0.96 dev cilium_host scope link
10.4.0.129 dev lxc644293a86df6 scope link
10.4.0.131 dev lxcd16ce377228b scope link
10.4.0.164 dev lxc_health scope link
10.168.0.1 dev eth0 proto dhcp scope link src 10.168.15.212 metric 100
169.254.123.0/24 dev docker0 proto kernel scope link src 169.254.123.1 linkdown
```

**Review by borkmann — APPROVED** [review]

**Comment by brb** [comment]
Damn, the arping library does the same check/detection internally: https://github.com/cilium/arping/blob/master/netutils.go#L9. I will change the library to accept the source IP param to avoid the check.

**Review by tklauser — APPROVED** [review]
Vendoring LGTM

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
retest-gke

**Review by joestringer — APPROVED** [review]
LGTM. I also manually validated that it removes the warning.

**Comment by joestringer** [comment]
Added the dont-merge label given the nearly-ready replacement of the underlying library for 1.10. This fix is more appropriate for backporting v1.9 however, given the lower risk.

**Comment by brb** [comment]
Closing this, as master (v1.10) got fixed by https://github.com/cilium/cilium/pull/13112. The backport PRs:
- v1.9 - https://github.com/cilium/cilium/pull/14453
- v1.8 - https://github.com/cilium/cilium/pull/14455

**Pull request closed without merging**
