### PR TITLE
Cilium servicemonitor & alertmanager rules

### PR DESCRIPTION
**Pull request by abhide15**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4098)

### CODE REVIEW

**Review by aanm — CHANGES_REQUESTED** [review]
Can you add this in `examples/kubernetes/addons/prometheus` along with a small README with a explanation for what is this useful for?

**Review by raybejjani — CHANGES_REQUESTED** [review]
@abhide15 Could you refresh my memory on why we're adding these? And should the ServiceMonitor replace the current prometheus example outright? It seems simpler, but I'm not sure how complex installing the prometheus-operator is.
I'll be honest and say I don't know how the `.rules` file is used, do we include it or mount it somewhere already? If we have some other scheme to use it (like we're also updating the docs) I would prefer to commit it with those changes.

**Comment by ianvernon** [comment]
@abhide15 is this still needed? Please let me know how I can assist in getting this merged.

**Comment by abhide15** [comment]
This isn't urgent. I will fix the comments on this PR

**Pull request closed without merging**
