### PR TITLE
v1.9 backports 2021-09-14

### PR DESCRIPTION
**Pull request by kaworu**
* #17115 (@jaffcheng) :heavy_check_mark:
 * #14621 (@jrajahalme) :heavy_check_mark:
 * #14704 (@jrajahalme) :heavy_check_mark:
 * #17275 (@jrajahalme) :heavy_check_mark:
 * #17445 (@jrajahalme) :heavy_check_mark:
 * #17351 (@joamaki) :heavy_check_mark:
 * #17153 (@tklauser) :heavy_check_mark:
 * #17258 (@twpayne) :heavy_check_mark:

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 17115 14621 14704 17275 17445 17351 17153 17258; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by kaworu** [comment]
Please take a close look at the patches, there was conflict with almost everyone of them.

@pchaigno @jrajahalme can you also look at the commits from #17115 please? See [this discussion](https://github.com/cilium/cilium/pull/17328#discussion_r703175928) for context.

**Review by tklauser — APPROVED** [review]
> #17153 (@tklauser)

LGTM for the PR above.

**Review by joamaki — APPROVED** [review]
> test/runtime: Look into log errors after test start #17351 

LGTM

**Review by twpayne — APPROVED** [review]
> jenkinsfiles: Don't display nulls in current build display name #17258 (@twpayne)

LGTM

**Comment by christarazi** [comment]
test-backport-1.9

**Comment by pchaigno** [comment]
> @pchaigno @jrajahalme can you also look at the commits from #17115 please? See [this discussion](https://github.com/cilium/cilium/pull/17328#discussion_r703175928) for context.

I'll defer to @jrajahalme as I'm unsure the solution I proposed in that discussion is the right one.

**Comment by kaworu** [comment]
@jrajahalme could you take a look at the PR and the CI `K8sIstioTest` issues please?

**Comment by kaworu** [comment]
@jrajahalme added https://github.com/cilium/cilium/pull/17445 to the backport, but we previously had failures on k8s >=v1.17 that still need a look.

**Comment by kaworu** [comment]
test-backport-1.9

**Review by jaffcheng — APPROVED** [review]
> policy: Fix transient policy deny during agent restart #17115 (@jaffcheng)

LGTM

**Review by jrajahalme — APPROVED** [review]
Istio changes look good :-)

**Comment by jrajahalme** [comment]
test-backport-1.9

**Comment by jrajahalme** [comment]
> Istio changes look good :-)

Maybe spoke too soon, this may still need to be included:

- #14704

**Comment by kaworu** [comment]
> […this may still need to be included:
> 
>     * [istio: Update to 1.8.2 #14704](https://github.com/cilium/cilium/pull/14704)

@jrajahalme added #14704 to the backports, please re-review both #14704 #17275 patches as there were conflicts (although trivials).

**Comment by jrajahalme** [comment]
This is also needed, even though the backport-done label is already on, must be due to a mistake of mine:

- #14621

**Comment by kaworu** [comment]
> This is also needed, even though the backport-done label is already on, must be due to a mistake of mine:
> * istio: Update to 1.7.6 #14621

Done

**Comment by kaworu** [comment]
/test-backport-1.9

**Review by jrajahalme — APPROVED** [review]
Istio backports seem complete now! Hoping the test will pass..

**Comment by kaworu** [comment]
@pchaigno @nbusseneau seems to me that `gke-stable` hit flake #12993 and `k8s-1.17-kernel-5.4` #16088

**Pull request merged**
