### PR TITLE
vagrant: Bump VM images to the latest versions

### PR DESCRIPTION
**Pull request by pchaigno**
The 5.4 and net-next images have new kernels.

### CODE REVIEW

**Comment by pchaigno** [comment]
/test-1.26-net-next

**Comment by pchaigno** [comment]
/test-1.26-net-next

**Comment by pchaigno** [comment]
/test-1.26-net-next

**Comment by pchaigno** [comment]
/test-1.25-4.19

**Comment by pchaigno** [comment]
/test-1.24-5.4

**Review by nebril — APPROVED** [review]

**Comment by pchaigno** [comment]
k8s-1.25-kernel-4.19 is failing with known flake https://github.com/cilium/cilium/issues/16122, but that CI job isn't affected by the VM version change anyway. Marking ready to merge.

**Pull request merged**
