### PR TITLE
v1.8 backports 2020-06-09

### PR DESCRIPTION
**Pull request by aanm**
* #11922 -- docs: quote helm flags with brackets (@nebril)
 * #11945 -- test: Disable flaky RuntimeKVStoreTest tests (@pchaigno)
 * #11941 -- endpoint: Fix data races while accessing GetIdentity() (@tgraf)
 * #11957 -- docs: Add session affinity to kubeproxy-free guide (@brb)
 * #11953 -- fqdn: Fix missing IsNil checks in unit tests (@pchaigno)
 * #11950 -- ipcache: Fix deadlock when ipcache GC results in datapath reload (@tgraf)
 * #11924 -- bpf: various datapath follow-up optimisations and fixes (@borkmann)
 * #11958 -- docs: Improve session affinity section in kube-proxy free guide (@brb)
 * #11952 -- service: Clean up HealthCheckNodePort server when traffic policy changes  (@gandro)
 * #11966 -- daemon: Fix waiting on metrics in endpoint_test.go (@christarazi)
 * #11968 -- runtime: Update LLVM image (@errordeveloper)
 * #11970 -- bpf, docs: add list of XDP supported drivers (@borkmann)
 * #11960 -- doc: fix up GKE install guide (@Rolinh)
 * #11907 -- helm: Generate experimental-install.yaml (@michi-covalent)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 11922 11945 11941 11957 11953 11950 11924 11958 11952 11966 11968 11970 11960 11907; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.8

**Review by pchaigno — APPROVED** [review]
:+1: for my changes.

**Review by borkmann — APPROVED** [review]

**Review by christarazi — APPROVED** [review]
Looks good for my changes

**Comment by aanm** [comment]
test-missed-k8s

**Review by jrfastab — APPROVED** [review]

**Review by errordeveloper — COMMENTED** [review]
My change looks good.

**Comment by errordeveloper** [comment]
@aanm accidentally I made a comment and didn't approve, surely the bot couldn't have guessed what my true intention was... looks like a bug, right?

**Comment by aanm** [comment]
> @aanm accidentally I made a comment and didn't approve as such, surely the bot couldn't have guessed what my true intention was... looks like a bug, right?

@errordeveloper not quite, leaving a comment is the same as approving. Only requested changes blocks the PR from being merged.

**Pull request merged**
