### PR TITLE
README: Update badge for GAPI v1.1.0

### PR DESCRIPTION
**Pull request by joestringer**

### CODE REVIEW

**Comment by joestringer** [comment]
@sayboras oh I see you just posted v1.2.0 support PR at https://github.com/cilium/cilium/pull/35216 :D ... what do you think we should do with the badge, update to 1.1.0 since that's the current supported Cilium release or 1.2.0 in your PR since Cilium will soon support 1.2.0?

**Comment by sayboras** [comment]
> oh I see you just posted v1.2.0 support PR at #35216 :D ... what do you think we should do with the badge, update to 1.1.0 since that's the current supported Cilium release or 1.2.0 in your PR since Cilium will soon support 1.2.0?

Good catch, I have added the changes to update the badge to v1.2.0 in the PR https://github.com/cilium/cilium/pull/35216 as well. Upstream report is pending for review https://github.com/kubernetes-sigs/gateway-api/pull/3372.

**Review by sayboras — APPROVED** [review]
Ship it, just in case we want to backport to 1.16.

**Comment by joestringer** [comment]
README is typically only inspected for the `main` branch so no need to backport.

**Pull request merged**
