### PR TITLE
datapath: Add per-endpoint direct routing support

### LINKED ISSUE #29619: CFP: Multi ENI support
## Cilium Feature Proposal
        
**Is your proposed feature related to a problem?**

Cilium configed as follow
- bpf host routing enabled
- endpoint-routes enabled

Node has multi nics , eth0 , eth1 ...
Pod allocate ip related to eth1.

bpf would redirect traffic to the default interface (eth0).  

**Describe the feature you'd like**

For cloud providers such as Alibaba Cloud , multiple ENIs are used on nodes to provide networking capabilities. We wish to have container traffic directly redirected to the corresponding elastic network interface. This would achieve:

- Faster forwarding
- Correct security group configurations.

**(Optional) Describe your proposed solution**

In CNI , pass the ip related eni id to Endpoint. 
In bpf fib.h , replace the DIRECT_ROUTING_DEV_IFINDEX with the eni id , passed through CNI .

The current fib lookup has two problems
1. `fib_lookup` only work for main table , can not get correct oif when policy route is used.
2. not necessary for the lookup , we can specific the oif here.

### PR DESCRIPTION
**Pull request by l1b0k**
Introduce ENDPOINT_DIRECT_ROUTING_DEV_IFINDEX for container endpoints to enable direct packet redirection using bpf_redirect_neigh(). This optimization eliminates the overhead of BPF FIB lookup operations in the datapath.

Fixes: #29619

### CODE REVIEW

**Review by nebril — APPROVED** [review]

**Review by dylandreimerink — COMMENTED** [review]
If I understand these changes correctly, this will always redirect traffic from a pod to its parent index if it has any. But I do not believe that is correct behavior. Since any traffic that should be masqueraded should exit via the primary interface, not the parent interface.

**Comment by l1b0k** [comment]
> If I understand these changes correctly, this will always redirect traffic from a pod to its parent index if it has any. But I do not believe that is correct behavior. Since any traffic that should be masqueraded should exit via the primary interface, not the parent interface.

Whether MASQ is required varies depending on different datapaths. This modification is suitable for multi-ENI scenarios, and traffic in and out needs to go through its own ENI.This case MASQ is not required. There a flag to allow enable this behavior.

**Review by joestringer — CHANGES_REQUESTED** [review]
Could you add the flag to the daemon as well?

**Comment by joestringer** [comment]
Thanks for adding the flag, that helps to try to reason about the UX / feature this provides vs. other flags. It feels like there is some overlap with `EnableEndpointRoutes` but the functionality is not 1:1 so if we think we need something like this it's likely we need a dedicated flag. On the other hand I'm struggling a bit to reason about how we might recommend users to enable or disable the flag. Worst case we could mark the flag as hidden but I'd also want to be sure we want to carry the datapath pieces of this.

Do I follow correctly that the intent behind this PR is to deliver traffic to the Linux stack as soon as possible so that Linux will choose how to route the traffic to the destination?

Are you able to share your observations around performance? Were you using BPF host routing at the time?

**Comment by joestringer** [comment]
Idly wondering whether we need another flag for this or the behaviour could be contingent on `EnableEndpointRoutes && BPFHostRouting` (maybe also some ENI option, though it looks like the only one we have is the IPAMENI option currently :thinking: ) instead of a new flag. From the parent issue it sounds like BPF host routing is currently routing incorrectly in this condition due to multiple routing tables being in use. In that case it's a correctness issue and not about performance at all.

**Comment by l1b0k** [comment]
> Idly wondering whether we need another flag for this or the behaviour could be contingent on `EnableEndpointRoutes && BPFHostRouting` (maybe also some ENI option, though it looks like the only one we have is the IPAMENI option currently 🤔 ) instead of a new flag. From the parent issue it sounds like BPF host routing is currently routing incorrectly in this condition due to multiple routing tables being in use. In that case it's a correctness issue and not about performance at all.

1. I just figured out the multiple routing tables issue has fixed by  https://github.com/cilium/cilium/commit/10deda489a888793224d0bca53b83c08a770ae58. So it is not a issue now.
2. This flag is intended to more explicitly capture the behavior of direct forwarding in ENI mode. If it's deemed unnecessary, I think we can also remove it and rely solely on the existing configuration.

**Comment by l1b0k** [comment]
> Thanks for adding the flag, that helps to try to reason about the UX / feature this provides vs. other flags. It feels like there is some overlap with `EnableEndpointRoutes` but the functionality is not 1:1 so if we think we need something like this it's likely we need a dedicated flag. On the other hand I'm struggling a bit to reason about how we might recommend users to enable or disable the flag. Worst case we could mark the flag as hidden but I'd also want to be sure we want to carry the datapath pieces of this.
> 
> Do I follow correctly that the intent behind this PR is to deliver traffic to the Linux stack as soon as possible so that Linux will choose how to route the traffic to the destination?
> 
> Are you able to share your observations around performance? ~Were you using BPF host routing at the time?~ (EDIT: I see bpf host routing is specified in the parent issue)

Yes , i intend to avoid the extra lookup in fib.  
BPF host routing is enabled.

```
Test run on aliyun ACK cluster, the base cilium version is Cilium 1.16.4.
5.10.134-17.2.al8.x86_64
ecs.g7nex.xlarge

2 nodes, deploy 40 pods each
node has 85 ip rules

run the netperf 2 times
netperf -H 10.84.156.253 -f M -p 12865 -t TCP_CRR -v 2 -- -o min_latency,mean_latency,max_latency,stddev_latency,transaction_rate
```

This test measure with netperf  and monitor the ebpf prog time cost.
The only difference in this test is w/o enable the flag.

## before

```
MIGRATED TCP Connect/Request/Response TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 10.84.156.253 () port 0 AF_INET
Minimum Latency Microseconds,Mean Latency Microseconds,Maximum Latency Microseconds,Stddev Latency Microseconds,Transaction Rate Tran/s
257,316.67,5759,84.79,3156.595
249,315.09,4329,51.24,3172.356

6683: sched_cls  name cil_from_contai  tag 1b3c66bcb67f7b2e  gpl run_time_ns 385894770 run_cnt 323886
```

## after

```
MIGRATED TCP Connect/Request/Response TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 10.84.156.253 () port 0 AF_INET
Minimum Latency Microseconds,Mean Latency Microseconds,Maximum Latency Microseconds,Stddev Latency Microseconds,Transaction Rate Tran/s
253,314.76,7856,84.77,3175.795
255,317.14,10016,96.82,3151.892

4595: sched_cls  name cil_from_contai  tag 1b3c66bcb67f7b2e  gpl run_time_ns 146819881 run_cnt 323005
```
## result

 | | run_time_ns  | run_cnt |  time per execute   |
| --|------------|-------------|----------|
| before | 385894770  | 323886      | 1,191.452|
| after | 146819881  | 323005      | 454.544  |

cpu cost decrease about 61.87%

**Comment by julianwiedmann** [comment]
I'd suggest to split this into multiple changes / PRs:
1. plumb the parent ifindex into bpf_lxc (suggested naming `THIS_INTERFACE_PARENT_IFINDEX`), and use it for `CT_REPLY` results to short-cut the FIB lookup. Redirect straight to the desired parent interface. This would merely optimize the logic introduced with https://github.com/cilium/cilium/pull/35298.
2. on-top, demonstrate with a separate patch what additional feature you'd like to propose.

**Comment by l1b0k** [comment]
I will split it into two PRs.

**Pull request closed without merging**
