### PR TITLE
v1.9 backports 2021-05-19

### PR DESCRIPTION
**Pull request by vadorovsky**
* #14639 -- test: Mark GKE CI pipeline as running Linux 4.19 (@pchaigno)
 * #14822 -- test: Extend coverage for host policies enforcement (@pchaigno)
 * #15398 -- test: add e2e tests for fromEntities: cluster and all (@chez-shanpu)
 * #15968 -- test: Fix the search for VIPs in `cilium service list` (@pchaigno)
 * #16064 -- test: Misc improvements (@pchaigno)
 * #16072 -- node-neigh: Fix unit test flake (@brb)
 * #16123 -- docs: add ids to the list of special identities (@bmcustodio)
 * #16169 -- docs, gsg: minor edits to kpr guide and note on hybrid use (@borkmann)
 * #16171 -- docs, gsg: add link to plumbers talk on service lb mechanisms (@borkmann)
 * #16141 -- docs: add information about ConfigMap updates (@aanm)
 * #16160 -- contrib: Make upstream commit check more generic (@joestringer)
 * #15899 -- Improve author attribution scripts (@joestringer)
 * #16142 -- helm: add back 'wellKnownIdentities' (@bmcustodio)
 * #15872 -- Improve ipsec compile-time testing in CI (@joestringer)
 * #16214 -- Specify scrape interval for Hubble metrics (@christian-2)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14639 14822 15398 15968 16064 16072 16123 16169 16171 16141 16160 15899 16142 15872 16214; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by mrostecki** [comment]
test-backport-1.9

**Comment by mrostecki** [comment]
@pchaigno I had to manually fix conflicts for #15968, I hope I did it correctly

**Review by pchaigno — APPROVED** [review]
My changes look good.

**Review by bmcustodio — APPROVED** [review]
My changes look good.

**Review by joestringer — APPROVED** [review]
MCLG

**Comment by joestringer** [comment]
Failure is a build issue in the test code:

https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/4751/execution/node/113/log/

```
08:50:46  + cd /home/jenkins/workspace/Cilium-PR-Runtime-4.9/runtime-gopath/src/github.com/cilium/cilium/test
08:50:46  + python get-gh-comment-info.py test-backport-1.9
08:50:46  + sed s/^$/Runtime/
08:50:46  + sed s/K8s.*/NoTests/
08:50:46  + ginkgo --focus=Runtime -v --failFast=false -- -cilium.provision=false -cilium.timeout=150m -cilium.runQuarantined=false
08:51:16  Failed to compile test:
08:51:16  
08:51:16  # github.com/cilium/cilium/test/k8sT
08:51:16  k8sT/Services.go:2276:11: undefined: helpers.DoesNotRunOnNetNextOr419Kernel
08:51:16  
08:51:16  Ginkgo ran 1 suite in 28.823139991s
08:51:16  Test Suite Failed
```

**Comment by mrostecki** [comment]
test-backport-1.9

**Review by brb — APPROVED** [review]
My changes LGTM, thanks.

**Review by twpayne — APPROVED** [review]

**Comment by pchaigno** [comment]
FYI, it looks like this backport PR introduced test failures https://github.com/cilium/cilium/issues/16318 and https://github.com/cilium/cilium/issues/16317.

**Comment by twpayne** [comment]
Whoops, sorry for merging this - I guess I saw four LGTMs and missed the failing tests or assumed that they were flakes.

**Comment by twpayne** [comment]
@pchaigno Since no other 1.9 backports have been merged, we can reset the `v1.9` to before this PR was merged (307663bd3).

**Pull request merged**
