### PR TITLE
Add hubble metrics for Node-local DNS addon

### LINKED ISSUE #34142: CFP: Add hubble metrics for Node-local DNS addon
## Cilium Feature Proposal

**The problem to solve**

Cilium [documentation](https://docs.cilium.io/en/latest/network/kubernetes/local-redirect-policy/#node-local-dns-cache) as well as several cloud providers provide a DNS caching layer running as DaemonSet on every node. Currently it is difficult to verify if DNS traffic is flowing through Node-local DNS cache or does it bypass the cache due to some issue. CiliumLocalRedirectPolicy redirects traffic to a local pod only if it exists, which is a good failsafe mechanism to forward dns traffic via a local cache. Having an insight to how the DNS traffic flows would enable one to say if the cache is functioning or it silently fails, while the traffic is bypassing the cache. Although a similar scheme applies to any optional caching layer, DNS node-local cache is a well documented concept and has a large user base compared to other services.

**Describe the feature you'd like**

A new hubble metric, which measures the DNS traffic.

**Describe your proposed solution**

There are “two” paths, which a DNS request can take while traveling from the workflow.

a1) nld is it’s destination (this is downstream of Node-local DNS)

a2) nld is it’s source (this is upstream of Node-local DNS)

b) nld is not the source nor the destination (this is bypassing the Node-local DNS)

Similarly for DNS response, but for a1) it’s upstream and for b2) it’s downstream. Verification of query/response can be done based on the traffic’s port.

DNS originating from the host are out of scope.

I propose to make 3 data series with an extra label for request/response tag; one series for each path “section”:
1. Traffic bypassing Node-local DNS
2. Traffic upstream of Node-local DNS
3. Traffic downstream of Node-local DNS

### PR DESCRIPTION
**Pull request by pwdtr**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [X] Thanks for contributing!

Introduce hubble metrics for monitoring DNS traffic for Node-local DNS.

The metrics gives an insight if workload’s DNS requests are passing through Node-local DNS cache and not bypassing it. It is useful for monitoring if the cache is performing it’s job.

Fixes: #34142

```release-note
Add hubble metrics for monitoring DNS traffic for Node-local DNS addon
```

### CODE REVIEW

**Review by gandro — CHANGES_REQUESTED** [review]
Thanks for the PR! I think the motivation overall makes sense, but I have a few questions regarding the implementation that I think we need to address first:

- Why does this require a well-known identity to be added? Those typically exist to solve bootstrapping problems and should not be needed do detect NLD traffic. Instead, you should be able to check the identity labels in the metric instead. In particular, the metric won't work if you do don't enable well-known identities - which is the case for the vast majority of users (`wellKnownIdentities.enabled` defaults to `false`). How have you tested this?

- This seems overly specific for NLD. Have you investigated if it would be possible to get the same data by introducing a new `sourceContext/destinationContext` variant? The existing ones are documented here: https://docs.cilium.io/en/stable/observability/metrics/#context-options

**Comment by pwdtr** [comment]
Hi Gandro! Thank You for the feedback.

> Re: well known identity

I have tested this in my cluster but apparently with the identity enabled. I was not sure if this is the right change, so I will be reverting. I will revert the known identity commit.

> Re: Using existing metrics

I have seen the `dns` metrics, which are working on L7 level and were insufficient to determine if the cache is working. `udp` metrics are udp only and I want to look at both TCP and UDP.

**Review by gandro — COMMENTED** [review]
Thanks for the context. I think this will work. Two requests:

- Please add documentation for these metrics in https://docs.cilium.io/en/stable/operations/metrics/#hubble-metrics
- Please squash all your commits into one.

Thanks

**Comment by chancez** [comment]
I'm not sure these are necessary and it this feels too specific to a given use-case. 

You should be able to get the same information by collecting coredns metrics from NLD and kube-dns directly. Additionally, I feel like introducing DNS specific metrics for NLD in Hubble feels a bit too. I'd rather see _Cilium_ (not Hubble) metrics for LocalRedirectPolicy redirects, if there aren't any already. This would probably be a better place for information that deals with LRPs. It wouldn't be DNS specific, but would likely give you roughly the same information that you need, which could be combined with the coredns metrics from NLD and core-dns.

**Comment by dlapcevic** [comment]
Hi. I'm not very familiar with use cases for it, but it seems like metrics for LocalRedirectPolicy redirects would be quite useful. Any pointers on where to look for it or implement it?

I agree that having metrics for LocalRedirectPolicy redirects is a good solution here, as long as it is considered useful for a broader range of cases.

cc @bowei

**Comment by bowei** [comment]
@pwdtr -- can we think about making this proposal more generic? It seems clear that there is a need for better visibility (there always is!) -- but focusing on a specific system even though it is in upstream K8s might be too narrow. It will probably not be a ton more effort to expand the domain of the metrics?

**Comment by pwdtr** [comment]
> It will probably not be a ton more effort to expand the domain of the metrics?

So the natural expansion I can think of is monitoring how LRPs function. As [chancez](https://github.com/chancez) suggested:  "I'd rather see Cilium (not Hubble) metrics for LocalRedirectPolicy redirects".

This is too big scope for my current project and I would have to work around hubble not having this metric here.

**Comment by chancez** [comment]
> > It will probably not be a ton more effort to expand the domain of the metrics?
> 
> So the natural expansion I can think of is monitoring how LRPs function. As [chancez](https://github.com/chancez) suggested: "I'd rather see Cilium (not Hubble) metrics for LocalRedirectPolicy redirects".
> 
> This is too big scope for my current project and I would have to work around hubble not having this metric here.

You should be able to get everything you need that you need from the coredns metrics themselves and comparing the metrics for kube-dns and node-local-dns.

**Comment by joestringer** [comment]
Do we see a path forward for some variation on this PR or does this need more discussion?

**Comment by chancez** [comment]
> Do we see a path forward for some variation on this PR or does this need more discussion?

I think the path forward is "generic" KPR Ciiium metrics for the KPR aspect, and using the coredns metrics directly from kube-dns and NLD for anything specific to the node local DNS use case.

**Comment by bowei** [comment]
I recommend we park this for the time being until we have an idea for generic solution.

**Comment by bowei** [comment]
By park -- it probably means close for now...

**Pull request closed without merging**
