### PR TITLE
updates.go: bump stable version to 1.12

### PR DESCRIPTION
**Pull request by aanm**
Test upgrade and downgrade from the last stable version which is 1.12

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
Why was this missed? Should this be part of the .0 release process?

**Comment by aanm** [comment]
> Why was this missed? Should this be part of the .0 release process?

It is part of the release process and it is marked as checked. https://github.com/cilium/release/issues/46#:~:text=Bump%20the%20master%20testsuite%20to%20upgrade%20from%20v1.12%20branch%20to%20master

I'm pretty sure it was an oversight.

**Pull request merged**
