### PR TITLE
daemon, option: consistently hard-code host device

### PR DESCRIPTION
**Pull request by tklauser**
The host device name is currently stored in option.Config.HostDevice
which is always initialized to defaults.HostDevice and there is no
command line option or other method to change it. Remove the option var
and always consistently hard-code the host device name using
defaults.HostDevice, like already done in several other places in the
code base.

### CODE REVIEW

**Comment by tklauser** [comment]
/test-1.16-4.9

**Comment by tklauser** [comment]
/test-1.22-4.19

**Review by ldelossa — APPROVED** [review]
Seems OK to me, just curious if the initial intent was to eventually allow this to be CLI driven. Tho I think we have other flags which allow defining devices?

**Comment by tklauser** [comment]
> Seems OK to me, just curious if the initial intent was to eventually allow this to be CLI driven. Tho I think we have other flags which allow defining devices?

It looks like this is a leftover from the flannel integration which was removed in 3b64f2372319ec25c112c7c2d008d76b05ea8968 (the commit originally adding it was 1e0a8f70516dd7a3751fd7acf285787867cfaa67).

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
