### PR TITLE
v1.10 backports 2022-06-08

### PR DESCRIPTION
**Pull request by joamaki**
* #19565 -- ui: v0.9.0 images and drop envoy proxy container (@geakstr)
 * #19923 -- ipam: Fix inconsistent update of CiliumNodes (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 19565 19923; do contrib/backporting/set-labels.py $pr done 1.10; done
```
or with
```
$ make add-label BRANCH=v1.10 ISSUES=19565,19923
```

### CODE REVIEW

**Review by geakstr — APPROVED** [review]
LGTM!

**Comment by joamaki** [comment]
/test-backport-1.10

**Review by gandro — APPROVED** [review]
Approving the commit for @pchaigno which was taken over by me.

**Comment by nebril** [comment]
/test-1.19-4.9

**Comment by nebril** [comment]
/test-1.19-5.4

**Comment by joestringer** [comment]
Tests are passing, reviews are in, merging.

**Pull request merged**
