### PR TITLE
v1.8 backports 2020-11-03

### PR DESCRIPTION
**Pull request by tklauser**
* #13704 -- docs: Fix shell session highlighting (@joestringer)
   - Minor merge conflicts due to doc differences between v1.8 and master
 * #13710 -- Update wording for BPFFS requirement and move to main system requirements page (@joestringer)
 * #13674 -- Various fixes for NodePort XDP kube-proxy free guide (@tklauser)
   - Minor merge conflicts due to helm refactoring
 * #13724 -- loader: Use netlink lib instead of tc binary to delete filters (@pchaigno)
 * #13769 -- bpf: Fix --force-local-policy-eval-at-source=false (@joestringer)
   - Minor merge conflict in bpf/lib/l3.h
 * #13783 -- docs: disable k3s network policy enforcement (@aanm)
 * #13780 -- pkg/kvstore: fix race in etcd initialization (@aanm)
 * #13794 -- daemon: Don't check XDPDevice in DevicePreFilter case (@brb)
 * #13810 -- go.mod: update cilium/ipam library with bug fixes (@aanm)
   - Minor merge conflicts in go.mod and go.sum, resolved by running
     `go get github.com/cilium/ipam@latest && go mod tidy`
 * #13714 -- docs: Add Azure troubleshooting tips (@jrajahalme)
 * #13800 -- cilium: Node to node encryption is not supported with vxlan (@jrfastab)
   - Minor merge conflicts due to helm refactoring.
 * #13822 -- Documentation: Fix Loadbalancer Guide for Clustermesh (@nathanjsweet)
 * #13808 -- docs: Add how to remove kube-proxy from existing clusters (@brb)
 * #13842 -- pkg/maps: fix interface implementation for SourceRangeKey{4,6} (@aanm)
 * #13811 -- k8s: clarify CRD schema versioning and its update process (@aanm)
 * #13860 -- examples: Fix grafana and prometheus (@nathanjsweet)
 * #13844 -- option: avoid error on dynamic NAT table size if CT map sizes are static (@tklauser)
 * #13837 -- helm: Fix format issue for logOptions in ConfigMap (@sayboras)
   - Minor merge conflicts due to helm refactoring.
 * #13825 -- Improve and expand on documentation for the API rate limiter (@christarazi)
 * #13859 -- bpf: fix session affinity timeout test flake (@fristonio)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13704 13710 13674 13724 13769 13783 13780 13794 13810 13714 13800 13822 13808 13842 13811 13860 13844 13837 13825 13859; do contrib/backporting/set-labels.py $pr done 1.8; done
```

Dropped from this PR:

 * #13750 -- hubble: Fix reply state unknown being interpreted as false  (@gandro)
   - Too many merge conflicts I didn't know how to resolve
 * #13796 -- hubble: Fix dropped flows not showing up in Hubble UI (@gandro)
   - Too many merge conflicts I didn't know how to resolve
 * #13776 -- hubble/relay: flush old flows when the buffer drain timeout is reached (@Rolinh)
   - Dropped due to build failure: `../pkg/hubble/relay/queue/priority_queue.go:75:29: resp.GetTime().AsTime undefined (type *timestamp.Timestamp has no field or method AsTime)`

### CODE REVIEW

**Comment by tklauser** [comment]
test-backport-1.8

**Review by rolinh — APPROVED** [review]

**Comment by tklauser** [comment]
test-backport-1.8

**Review by fristonio — APPROVED** [review]
Looks good for my changes. :rocket:

**Review by pchaigno — APPROVED** [review]
:+1: for my PR.

**Review by sayboras — APPROVED** [review]
Thanks for resolving conflict in my commit. LGTM

**Review by christarazi — APPROVED** [review]
:+1: for my commits

**Review by aanm — APPROVED** [review]
LGTM for my changes

**Review by joestringer — APPROVED** [review]

**Pull request merged**
