### PR TITLE
datapath, service: Isolate runtime-specific types from widely imported types

### LINKED ISSUE #10609: Operator shouldn't depend on pkg/bpf
Right now the operator has many dependencies (#9920), but amongst all of Kubernetes and could prover dependencies, it has dependencies that are very specific to Cilium runtime.
Namely, it happens to depend on `pkg/bpf` as it uses `pkg/datapath`, which in turns depends on `pkg/datapath/prefilter`. Moreover, `pkg/datapath` appears to be intended as types-only package.
There is also a dependency on `pkg/service`, that pulls in `pkg/bpf` as well as `pkg/maps/lbmap`.

### PR DESCRIPTION
**Pull request by errordeveloper**
Fixes: #10609

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10610)

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Comment by errordeveloper** [comment]
@tklauser @pchaigno I just added another commit that still relates to the original issue #10609, would you mind to review this new commit also? If you prefer separate PRs, just let me know - I don't mind either way :)

**Comment by tklauser** [comment]
> @tklauser @pchaigno I just added another commit that still relates to the original issue #10609, would you mind to review this new commit also? If you prefer separate PRs, just let me know - I don't mind either way :)

I think it's fine as part of this PR since it addresses the same issue. Still LGTM with the new commit, but I'd prefer if someone from @cilium/kubernetes could also take a look.

**Comment by errordeveloper** [comment]
test-me-please

**Comment by errordeveloper** [comment]
test-me-please

**Comment by errordeveloper** [comment]
test-me-please

**Comment by errordeveloper** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Looks good on datapath / docs side. I didn't look closely at the service stuff.

**Comment by jrajahalme** [comment]
Failed DNS/FQDN tests have curl returning 22:
```
CURLE_HTTP_RETURNED_ERROR (22)

This is returned if CURLOPT_FAILONERROR is set TRUE and the HTTP server returns an error code that is >= 400.
```
Since these tests have no HTTP redirection, this means that the http server at `vagrant-cache.ci.cilium.io` has returned an error (would be handy if the test output would show the returned HTTP error code).

**Comment by jrajahalme** [comment]
Checked the logs, security ID for the FQDN is properly plumbed to the bpf policy maps, so this is likely a transient issue with `vagrant-cache.ci.cilium.io`.

**Comment by jrajahalme** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]

**Comment by errordeveloper** [comment]
This [test failure](https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18030/execution/node/178/log/) looks like a flake, right?

```
23:26:01  [Fail] K8sDatapathConfig ManagedEtcd [It] Check connectivity with managed etcd 
23:26:01  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.17-gopath/src/github.com/cilium/cilium/test/k8sT/assertionHelpers.go:120
```

**Comment by errordeveloper** [comment]
test-me-please

**Comment by errordeveloper** [comment]
Another one, seems like the same thing?
```
13:36:30  • Failure [798.823 seconds]
13:36:30  K8sDatapathConfig
13:36:30  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.17-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
13:36:30    ManagedEtcd
13:36:30    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.17-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
13:36:30      Check connectivity with managed etcd [It]
13:36:30      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.17-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
13:36:30  
13:36:30      cilium pre-flight checks failed
[2020-03-19T13:36:30.739Z]     Expected
[2020-03-19T13:36:30.739Z]         <*errors.errorString | 0xc000591720>: {
[2020-03-19T13:36:30.739Z]             s: "CiliumPreFlightCheck error: Timeout reached: PreflightCheck failed: Last polled error: status is unhealthy: cilium-agent 'cilium-skxmf' is unhealthy: Exitcode: 1 \nStdout:\n \t KVStore:                Failure   Err: not able to connect to any etcd endpoints\n\t Kubernetes:             Ok        1.17 (v1.17.3) [linux/amd64]\n\t Kubernetes APIs:        [\"CustomResourceDefinition\", \"cilium/v2::CiliumClusterwideNetworkPolicy\", \"cilium/v2::CiliumNetworkPolicy\", \"core/v1::Endpoint\", \"core/v1::Namespace\", \"core/v1::Pods\", \"core/v1::Service\", \"networking.k8s.io/v1::NetworkPolicy\"]\n\t KubeProxyReplacement:   Probe     []\n\t Cilium:                 Failure   Kvstore service is not ready\n\t NodeMonitor:            Disabled\n\t Cilium health daemon:   Ok   \n\t IPAM:                   IPv4: 8/255 allocated from 10.10.1.0/24, IPv6: 8/4294967295 allocated from f00d::a0a:100:0:0/96\n\t Controller Status:      53/54 healthy\n\t   Name                              Last success   Last error   Count   Message\n\t   kvstore-etcd-lock-session-renew   never          35s ago      2       unable to renew etcd lock session: rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field   \n\t Proxy Status:   OK, ip 10.10.1.111, 0 redirects active on ports 10000-20000\n\t \nStderr:\n \t command terminated with exit code 1\n\t \n",
[2020-03-19T13:36:30.739Z]         }
[2020-03-19T13:36:30.739Z]     to be nil
```

**Comment by errordeveloper** [comment]
test-me-please

**Comment by joestringer** [comment]
@errordeveloper if you go back up to the top summary page for the earlier build:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18030/

Then click on the "Test result" for the specific test:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18030/testReport/junit/Suite-k8s-1/17/K8sDatapathConfig_ManagedEtcd_Check_connectivity_with_managed_etcd/

There are more specific symptoms than "cilium pre-flight checks failed", for instance:

"unable to add endpoint IP mapping"

I'm not finding any filed issues with this string. Either it's a new flake on master that no-one has filed a CI issue for, or it's related to the changes in this PR. If you find that you're consistently hitting issues with this test, I'd suggest digging a bit deeper---I imagine someone on Slack should be able to help you to dig around in the failure. If it's really flaking, I'd suggest filing an issue so that we can track this CI failure and understand how widespread it is, etc.

**Comment by aanm** [comment]
test-me-please

**Comment by errordeveloper** [comment]
Looks like this is one good to go now! 🎉

**Pull request merged**
