### PR TITLE
test: node: use Eventually() to check CiliumNode labels 

### PR DESCRIPTION
**Pull request by jibi**

### CODE REVIEW

**Comment by jibi** [comment]
/test-backport-1.12

**Comment by jibi** [comment]
/test-1.20-4.9

**Comment by pchaigno** [comment]
Is this opened against v1.12 because the code isn't in master anymore?

Also, do you have a link to the flake it fixes? If not, could you explain a bit more what happens and which test is affected?

**Comment by jibi** [comment]
> Is this opened against v1.12 because the code isn't in master anymore?

Yes, we don't have `node.go` in master anymore

> Also, do you have a link to the flake it fixes?

I don't think there's an issue for that flake

> If not, could you explain a bit more what happens and which test is affected?

I put a short explanation in the commit message (there's only one test in that file, `K8sNode Node labels updates are reflected in CiliumNode objects`, so I didn't mentioned it), not sure what else I should add to that :thinking:

**Review by pchaigno — APPROVED** [review]
Ah, I see. The test itself is simply checking that Node label changes are reflected in CiliumNode objects. I thought this was part of a bigger thing :facepalm:

**Comment by jibi** [comment]
`gke-stable` is failing because of unrelated tests, marking as ready to merge

**Pull request merged**
