### PR TITLE
#17813 v1.10 backport

### PR DESCRIPTION
**Pull request by jibi**
* https://github.com/cilium/cilium/pull/17813 -- egressgateway: fix manager logic (@jibi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 17813; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-4.9

**Comment by jibi** [comment]
/test-4.9

**Comment by jibi** [comment]
/test-backport-1.10

**Review by kkourt — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Pull request merged**
