### PR TITLE
bpf: handles nodeport_nat_{*}_fwd errors

### LINKED ISSUE #15890: BPF NAT engine is not dropping ICMP type 13 (timestamp)
Cilium version
```
Client: 1.9.90 44382f928 2021-04-27T09:45:08-03:00 go version go1.16.3 linux/amd64
Daemon: 1.9.90 44382f928 2021-04-27T09:45:08-03:00 go version go1.16.3 linux/amd64
```
Kernel version 
```
Linux k8s1 5.12.0-rc4+ #1 SMP Wed Apr 21 11:28:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux      
```
Cluster health
```
Cluster health:      2/2 reachable   (2021-04-27T21:39:48Z)
  Name               IP              Node        Endpoints
  k8s1 (localhost)   192.168.33.11   reachable   reachable
  k8s2               192.168.33.12   reachable   reachable
```

How to reproduce:

- Run the VM: `NETNEXT=1 VM_CPUS=6 K8S=1 NWORKERS=1 contrib/vagrant/start.sh`
- Create a pod (e.g. ubuntu) in k8s1+
- Run `hping3 <ip-k8s2+> --icmp --icmp-ts` in the pod 

The messages should be dropped, but the reply is received
```
root@ubuntu:/# hping3 192.168.33.12 --icmp --icmp-ts                                                                                                                                          
HPING 192.168.33.12 (eth0 192.168.33.12): icmp mode set, 28 headers + 0 data bytes                                                                                                            
len=40 ip=192.168.33.12 ttl=62 id=61849 icmp_seq=0 rtt=1.8 ms
ICMP timestamp: Originate=70862679 Receive=70862681 Transmit=70862681
ICMP timestamp RTT tsrtt=1

len=40 ip=192.168.33.12 ttl=62 id=61979 icmp_seq=1 rtt=505.2 ms
ICMP timestamp: Originate=70863706 Receive=70863709 Transmit=70863709
ICMP timestamp RTT tsrtt=505

len=40 ip=192.168.33.12 ttl=62 id=62121 icmp_seq=2 rtt=12.1 ms
ICMP timestamp: Originate=70864716 Receive=70864719 Transmit=70864719
ICMP timestamp RTT tsrtt=12

len=40 ip=192.168.33.12 ttl=62 id=62220 icmp_seq=3 rtt=3.9 ms
ICMP timestamp: Originate=70865717 Receive=70865720 Transmit=70865720
ICMP timestamp RTT tsrtt=4

len=40 ip=192.168.33.12 ttl=62 id=62257 icmp_seq=4 rtt=6.9 ms
ICMP timestamp: Originate=70866718 Receive=70866721 Transmit=70866721
ICMP timestamp RTT tsrtt=7

```

### PR DESCRIPTION
**Pull request by navarrothiago**
snat_v{*} process() errors were not translated from DROP_INVALID hooks to TC_ACT_SHOT return code for the Linux stack to enforce the drop. Also we skipped pushing an indication to userspace so Cilium user was not able to see events when drop were expected. The result is snat engine was allowing the all the icmp packets on the egress when the traffic was genereted from a pod (k8s1) to another node (k8s2). This was observed with the configuration `--kube-proxy- replacement probe`.

Fixes: #15890

Signed-off-by: Thiago Navarro <navarro@accuknox.com>

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by navarrothiago** [comment]
@brb, I dont think the failures are related to this change. WDYT?

**Review by pchaigno — CHANGES_REQUESTED** [review]
Could you add context in the commit message (how the issue manifests & why it happens)?

Also, AFAICS, it is not specific to ICMP type 13; several other ICMP types are affected as well. The title should reflect that as it will be used in release notes.

**Comment by brb** [comment]
Thanks for your PR! Could you write about direction and origin of the traffic which is affected by your change (ideally, in the commit msg)? This would help us to understand a user impact.

**Comment by jrfastab** [comment]
Same comment as @brb this is less about a specific icmp type although thats the effect that you probably see and more that we are not catching the error correctly. For example revalidate data and ctx_load_bytes can also fail and we would have ignored that error as well, passing the packet up the stack. Can you just fixup the commit a bit so that when we read logs we can be sure to understand the fix?

Just something as simple as, 
```
snat_v{*} process() errors were not translated from DROP_INVALID hooks to TC_ACT_SHOT return code for the Linux stack to enforce the drop.  Also we skipped pushing an indication to userspace so Cilium user was not able to see events when drop were expected. The result is ... [what you saw]
```

**Comment by navarrothiago** [comment]
Thanks @jrfastab to clarify. Let me know if this is what you are expecting.

**Comment by jrfastab** [comment]
LGTM thanks

**Review by jrfastab — APPROVED** [review]

**Comment by brb** [comment]
@navarrothiago Considering the comment https://github.com/cilium/cilium/issues/15890#issuecomment-900161703, I'm marking this PR as draft. Let's discuss during the next sig-datapath meeting (next week) whether we should drop or just pass such packets (i.e., the ones for which we don't support SNAT).

**Pull request closed without merging**
