### PR TITLE
Various bugfixes & improvements to daemon config handling

### PR DESCRIPTION
**Pull request by The-Loeki**
This PR fixes a few outstanding bugs and improves Cilium's handling of configuration loading.

* `--config` silently ignored
* improved logging
* no more (sometimes silent) continuing when explicitly defined config files/dirs could not be loaded

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7703)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
LGTM, thanks for contributing

**Comment by tgraf** [comment]
@The-Loeki Please add a signed-off-by line to the commit message to acknowledge that you agree to the "Developer’s Certificate of Origin": http://docs.cilium.io/en/v1.4/contributing/?highlight=signed-off-by#dev-coo

**Comment by The-Loeki** [comment]
Done, thanks for picking the PR up so quickly

**Pull request merged**
