### PR TITLE
[1.5] cilium: fix transient rules to use allocation cidr

### PR DESCRIPTION
**Pull request by borkmann**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8934)

### CODE REVIEW

**Comment by borkmann** [comment]
never-tell-me-the-odds

**Comment by borkmann** [comment]
Fyi, not critical for 1.5.6, can go into 1.5.7.

**Comment by borkmann** [comment]
never-tell-me-the-odds

**Comment by borkmann** [comment]
```17:40:05  Deleted: sha256:ed8308579f11f616d6b58e6e456f765f8e3837f69f81f7304f213c4e3aa96856
17:40:05  Deleted: sha256:a757708db54bb9fe5cc7962e8890e008992209d6eca7d6556db03d2891159fef
17:40:05  Deleted: sha256:543791078bdb84740cb5457abbea10d96dac3dea8c07d6dc173f734c20c144fe
17:40:05  /usr/local/bin/cleanup: line 57: [[: cb04a359db13::2018-12-21 03:31:34 +0000 UTC: syntax error in expression (error token is "::2018-12-21 03:31:34 +0000 UTC")
17:40:05  Error response from daemon: conflict: unable to delete cb04a359db13 (cannot be forced) - image has dependent child images
17:40:05  Enough space in the VM. Skipping vagrant prune.
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // ansiColor
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
17:40:06  Terminated
[Pipeline] End of Pipeline
Setting status of c15e2cea66825ba014b713cafc775ff7493b62ae to FAILURE with url https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/1475/ and message: 'Build finished. '
Using context: Cilium-kubernetes-upstream-test
Timeout has been exceeded
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)```

**Comment by borkmann** [comment]
test-upstream-k8s

**Review by joestringer — APPROVED** [review]

**Pull request merged**
