### PR TITLE
cleanup/unused: Remove un-used code in codebase

### PR DESCRIPTION
**Pull request by sayboras**
Remove un-used methods and params in code base

```release-note
cleanup/unused: Remove un-used code in codebase
```

### CODE REVIEW

**Comment by sayboras** [comment]
test-me-please

**Review by aditighag — APPROVED** [review]
:rocket:

**Comment by sayboras** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
I'm sure there is plenty more unused code but the 'unused' linter is not smart enough to detect it.

**Comment by aanm** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]
Agree with André, I think the unused checker only detects unused unexported symbols by default. Last time I checked it also had an option to enable checking off all exported symbols on a binary, but that reported way too many false positives (probably also due to the fact that we build multiple binaries which use the same packages, but not all the symbols defined therein).

**Comment by sayboras** [comment]
@aanm @tklauser I think it will skip all packages in `pkg` as pkg _can be_ imported by other project(s). I assume that only hubble is importing cilium :thinking:, but not 100% sure.

Checking actually binary dependency with different OS/ARCH will be interesting though.

**Comment by ti-mo** [comment]
> I think it will skip all packages in `pkg` as pkg _can be_ imported by other project(s).

It should work on all packages, including ones in `pkg/` it's not a hard convention like `internal/` is. It ignores all exported symbols since those can be directly depended on by any other package in any other repo and are not safe to remove as a result.

**Review by ti-mo — APPROVED** [review]

**Review by jibi — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Review by christarazi — APPROVED** [review]
:rocket: 

Re: ignoring `pkg/` and exported symbols. Ideally, all exported symbols regardless of the package they're in should be used _at least_ once--in a (unit) test. I know we don't have that in place today, but going forward, we should use all exported symbols by writing a test that uses them. That would solve our linting problem and improve our code coverage. Having an untested exported function can be a liability.

**Review by errordeveloper — APPROVED** [review]

**Comment by aanm** [comment]
retest-runtime

**Comment by sayboras** [comment]
thanks all for review and add your comments, TIL 💯 

I didn't check the test until now. 2 failures are related to #14125 and #13839. I am marking this PR `ready to merge` now, feel free to let me know if you think otherwise.

**Pull request merged**
