### PR TITLE
ipam: Support dynamic allocation of pod CIDRs in cluster pool

### PR DESCRIPTION
**Pull request by gandro**
This is a work introduces "Dynamic Cluster Pool", i.e. a mechanism to dynamically allocate (and deallocate) pod CIDRs to nodes based on dynamic requirements to more efficiently use IP address space.

The feature is currently gated behind a new `cluster-pool-v2` IPAM mode. It is mostly backwards compatible with the existing cluster-pool implementation, but to regressions the two modes are kept separate for now. If any detected backwards incompatibilities can be resolved or mitigated, the goal is to eventually deprecate cluster-pool v1 and always default to v2 when `cluster-pool` IPAM is selected.

The overall logic and user configuration is documented in this commit description:
```
The CiliumNode CRD is extended with two spec and one status fields
needed to support dynamic allocation of pod CIDRs to node.

  - CiliumNode.Status.IPAM.UsedPodCIDRs informs the operator about the
    pod CIDR usage of this node.  Each pod CIDR can be in one of three
    states:

    * `in-use`: This pod CIDR is currently being used for allocation of
      pod IPs.
    * `depleted`: Every IP in this pod CIDR is currently used up. If all
      pod CIDRs are depleted, the operator will allocate and assign new
      pod CIDRs to this node.
    * `released`: This pod CIDR is no longer in use by the agent and
      should be deallocated by the operator.

  - CiliumNode.Spec.IPAM.PodCIDRAllocationThreshold defines the minimum
    number of free IPs which must be available to this node via its pod
    CIDR pool. If the total number of IP addresses in the pod CIDR pool
    is less than this value, the pod CIDRs currently in-use by this node
    will be marked as depleted and cilium-operator will allocate a new
    pod CIDR to this node.  This value effectively defines the buffer of
    IP addresses available immediately without requiring cilium-operator
    to get involved.

  - CiliumNode.Spec.IPAM.PodCIDRReleaseThreshold defines the maximum
    number of free IPs which may be available to this node via its pod
    CIDR pool. While the total number of free IP addresses in the pod
    CIDR pool is larger than this value, cilium-agent will attempt to
    release currently unused pod CIDRs.
```

TODO:
- [x] Implement cilium-operator logic. It will need to watch the `CiliumNode.Status.IPAM.UsedPodCIDR` data and allocate/de-allocate pod CIDRs accordingly
- [x] Make the pre-allocation and release thresholds used by the agent configurable
- [x] Make the feature opt-in or opt-out (to be decided, either by adding it as a separate new IPAM mode or as a config flag related to cluster pool). Currently dynamic cluster pool replaces the old cluster pool implementation.
- [x] Unit testing
- [ ] Add support for this IPAM mode to the `cilium_host` route setup. The route setup logic currently only supports one single pod CIDR per node. Support for multiple CIDRs is required such that dynamic cluster pool can be used in tunnel mode.
- [ ] Documentation
- [ ] CI testing and increased unit test coverage (will likely be done as a follow-up after feature freeze)
- [ ] Add support for cluster-pool (v1&v2) in the BGP announcement feature (https://github.com/cilium/cilium/pull/16525)

### CODE REVIEW

**Comment by cndoit18** [comment]
👀

**Comment by cndoit18** [comment]
#13227
Will this feature be supported in `cluster-pools-v2`?

**Comment by gandro** [comment]
> #13227 Will this feature be supported in `cluster-pools-v2`?

Not yet in this version. But the design is such that it could be added in the feature.

**Comment by gandro** [comment]
Closing in favor of https://github.com/cilium/cilium/pull/18887

**Pull request closed without merging**
