### PR TITLE
v1.14 Backports 2023-12-07

### PR DESCRIPTION
**Pull request by sayboras**
* [ ] ~#24836 (@darox)~ already part of 1.14 as highlighted below.
 * [ ] #29511 (@ayuspin)
 * [ ] #29610 (@ayuspin)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
  29511 29610
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.14

**Comment by darox** [comment]
Let's get https://github.com/cilium/cilium-cli/issues/1396#issuecomment-1845023009 answered before merging.

**Comment by darox** [comment]
Why is my commit https://github.com/cilium/cilium/pull/24836 part of this backport? I can see that it's already part of the latest v1.14.4 see https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml#L74 Is it because the commits by @ayuspin where done on top of my commit?

**Comment by sayboras** [comment]
The changes in #24836 are only available in main, but not in 1.14 branch and older branches. 
I

**Comment by sayboras** [comment]
/test-backport-1.14

**Comment by sayboras** [comment]
You are right, the mentioned changes are already part of 1.14, I have dropped the commit accordingly. Thanks for highlighting :+1:

**Review by ti-mo — APPROVED** [review]

**Pull request merged**
