### PR TITLE
Introduce `DebugLB` option in endpoint config

### PR DESCRIPTION
**Pull request by joestringer**
`LB_DEBUG` was entirely disabled in the datapath and that codepath didn't compile. Fix it up and allow it to be configured on a per-endpoint basis so that issues in LB may be debugged.

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]
Endpoint portion LGTM.

**Comment by joestringer** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]
lgtm

**Pull request merged**
