### PR TITLE
daemon/cmd: improve stale cilium endpoint error handling.

### PR DESCRIPTION
**Pull request by tommyp1ckles**
Avoid error logging on no-op cleanup situations to avoid breaking CI.

Previously, if stale CEP cleanup was attempted and the CiliumEndpoint was already gone it would log an error.
This would go on to fail CI, on tests enforcing zero error logs.
In the case where the error is a `k8serrors.NotFound`,  we don't need to consider this an error. This change differentiates between the two cases and logs info if its the no-op case.

Signed-off-by: Tom Hadlaw <tom.hadlaw@isovalent.com>

### CODE REVIEW

**Comment by tommyp1ckles** [comment]
/test-1.16-4.9

**Comment by tommyp1ckles** [comment]
/test-1.16-4.9

**Comment by tommyp1ckles** [comment]
/test-1.16-4.9

**Comment by tommyp1ckles** [comment]
/test-1.16-4.9

**Comment by tommyp1ckles** [comment]
/test-1.16-4.9

**Comment by tommyp1ckles** [comment]
/test-1.24-5.4

**Comment by tommyp1ckles** [comment]
/test-1.26-net-next

**Comment by tommyp1ckles** [comment]
/test-1.16-4.9

**Comment by tommyp1ckles** [comment]
/test-1.16-4.9

**Review by joestringer — APPROVED** [review]

**Comment by aditighag** [comment]
@tommyp1ckles This file doesn't exist in <= v1.12. Removing the needs-backport/* labels for those changes for now.

**Pull request merged**
