### PR TITLE
v1.11: Update Go to 1.17.6

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Comment by tklauser** [comment]
/test-backport-1.11

**Review by pchaigno — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Comment by tklauser** [comment]
/test-backport-1.11

**Comment by tklauser** [comment]
/test-1.16-netnext

**Comment by tklauser** [comment]
Travis CI failed due to dockerhub rate limiting, all other tests passed and reviews are in. Marking as ready to merge.

**Pull request merged**
