### PR TITLE
first pass at consistent logrus usage

### PR DESCRIPTION
**Pull request by raybejjani**
I'm not sure if this is what you had in mind, @tgraf, comments?

### CODE REVIEW

**Comment by tgraf** [comment]
> I'm not sure if this is what you had in mind, @tgraf, comments?

This is exactly what I had in mind

**Comment by raybejjani** [comment]
Perfect. I'll keep switching things over until it's good :)

**Comment by ianvernon** [comment]
Looks great so far - this will be great for having consistency across logs!

**Comment by raybejjani** [comment]
I'm closing this to avoid confusion with PRs intended for review, but the `with-fields-usage` branch will still hold all the pending commits (there are many :/ ) for the log changes. I'll wait until we have https://github.com/cilium/cilium/pull/1801 approved so I can reconcile any changes we decide on there.

**Pull request closed without merging**
