### PR TITLE
vagrant: update box versions

### PR DESCRIPTION
**Pull request by tklauser**
To pull in https://github.com/cilium/packer-ci-build/pull/339 for
https://github.com/cilium/cilium/pull/20033

Ref. https://github.com/cilium/cilium/pull/20033#issuecomment-1189022004

/cc @DolceTriade @joestringer

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Comment by tklauser** [comment]
/test-1.24-net-next

**Comment by tklauser** [comment]
Only GKE failed, but that test is known to be flaky and thus not required. The failure doesn't look specific to the VM update. Marking as ready to merge.

**Pull request merged**
