### PR TITLE
test/k8sT/manifests: re-add l3_l4_policy.yaml

### PR DESCRIPTION
**Pull request by ianvernon**
This file (`test/k8sT/manifests/l3_l4_policy.yaml`) was symlinked to a file which was deleted.

Fixes: dc36592246cc3853574adf587a9f5d6a714f2d56

Signed-off by: Ian Vernon <ian@cilium.io>

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
shipit.gif

**Comment by joestringer** [comment]
As a follow-up, does this mean that the new guides aren't being tested in the testsuite?

**Comment by ianvernon** [comment]
> As a follow-up, does this mean that the new guides aren't being tested in the testsuite?

@joestringer yes, that is correct. https://github.com/cilium/cilium/issues/4137 was filed to track that effort

**Comment by ianvernon** [comment]
Test failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3259/

but, appears that it is for an unrelated reason. Investigating.

**Comment by ianvernon** [comment]
And, there's no bugtool output for the failed test :(

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
