### PR TITLE
v1.8 backports 2021-03-19

### PR DESCRIPTION
**Pull request by jrajahalme**
* #14488 -- Bugtool: route tables dynamically dumped (@youssefazrak)
 * #14568 -- Bugtool: add taskset  (@youssefazrak)
 * #15328 -- contrib: fix remote overriding (@kaworu)
 * #15323 -- docs: adds a rancher kubernetes engine installation guide (@seanmwinn)
 * #15365 -- Documentation: fix key rotation command in encryption guide (@mauriciovasquezbernal)
 * #15363 -- bugtool: dump iptables-legacy and iptables-nft (@h3llix)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14488 14568 15328 15323 15365 15363; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-backport-1.8

**Comment by jrajahalme** [comment]
Fails on kernel 4.9 due to complexity issue:
```
2021-03-19T18:13:41.312406578Z level=warning msg="BPF program is too large. Proccessed 98305 insn" subsys=datapath-loader
```

**Comment by jrajahalme** [comment]
> Fails on kernel 4.9 due to complexity issue:
> 
> ```
> 2021-03-19T18:13:41.312406578Z level=warning msg="BPF program is too large. Proccessed 98305 insn" subsys=datapath-loader
> ```

#15321 seems to be the culprit here, conversation there indicated the same issue on master?

**Comment by aditighag** [comment]
> > Fails on kernel 4.9 due to complexity issue:
> > ```
> > 2021-03-19T18:13:41.312406578Z level=warning msg="BPF program is too large. Proccessed 98305 insn" subsys=datapath-loader
> > ```
> 
> #15321 seems to be the culprit here, conversation there indicated the same issue on master?

Umm... I thought the complexity was resolved with one of my commits. The `4.9` test passed on the master branch. @pchaigno Did you hit this issue on your temporary backport PR?

**Comment by pchaigno** [comment]
> @pchaigno Did you hit this issue on your temporary backport PR?

Yes, even with the `unlikely()`.

**Comment by aditighag** [comment]
@jrajahalme Please skip the PR in question. Paul and I will manage the `1.8` backport.

**Comment by jrajahalme** [comment]
Removed backport of #15321

**Comment by jrajahalme** [comment]
test-backport-1.8

**Comment by jrajahalme** [comment]
retest-upstream-k8s

**Comment by jrajahalme** [comment]
Upstream k8s test had failed to bring vagrant vm up, retesting.

**Review by kaworu — APPROVED** [review]
Look good for my change, thanks!

**Pull request merged**
