### PR TITLE
[v1.5] examples/kubernetes: bump cilium to v1.5.4

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8445)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-upstream-k8s

**Pull request merged**
