### PR TITLE
Prevent incorrect observation of LocalNode changes by always creating deep copies.

### PR DESCRIPTION
**Pull request by giorio94**
Currently, the Update method of the LocalNodeStore directly mutates the cached value, and then emits a shallow copy, to be eventually seen by all observers. Yet, this can create issues in case of slices and maps, as the old object could be directly mutated, preventing observers from correctly seeing all transitions, possibly observing incomplete states, or even causing panics due to concurrent reads and writes.

To prevent these issues, let's always create a deep copy of the object before passing it to the mutator function, so that we are guaranteed to never modify the one readers could be accessing. This relieves all consumers of this function from needing to perform a copy themselves.

I'm personally on the fence whether this should be treated as a bug fix, and backported to at least the latest version. My understanding is that currently we are not mutating map elements (which can cause concurrent read write panics), but we are modifying slices to configure addresses. Which leads to a different behavior depending on whether an existing element is mutated in place or not.

### CODE REVIEW

**Comment by bimmlerd** [comment]
I don't think this is a bug in `LocalNodeStore`. The choice to _not_ copy was a AFAIR deliberate, as these objects aren't exactly tiny. It creates (even more) GC pressure to copy these. In my opinion, we should fix consumers which mutate these slices without copying (or calling update themselves) and state the supposed immutability of the object more clearly.

**Comment by bimmlerd** [comment]
> I see. Do you think it would change that much in terms of GC pressure?

On the one hand, no - it's hard to measure this, and there's so much GC going on in the agent, that this would likely not have massive impact. On the other hand, it's exactly the cause for the somewhat staggering amount of memory used (and memory churn) that the agent exhibits. It's death by a thousand cuts, metaphorically.

> I mean, I agree that the Node object can be pretty large, but on the other hand AFAIU it is not expected to change ony a few times during startup. 

I don't think this will be true in the near future. As far as I'm aware, for multi network IPAM some information will need to live in `node.Node` (as all nodes need to know this about each other), and will change at runtime. If we start copying, this will become expensive quickly.

Furthermore, I think the direction we're trying to take is eventually going to lead to a statedb Table of nodes, where this exact problem will resurface, as statedb also relies on the immutability of it's objects. 

> And relying on consumers to create a copy of the modified fields can lead to subtle bugs, being easy to miss. Especially because most if not all readers currently only retrieve the latest value through the getters, which means that in most cases it just works fine even if the copy is missed. And the more we drop the global setters, the more this will risk to happen.

I agree that it's dangerous to rely on consumers to do the right thing. However, from a design perspective, it's a tradeoff: Without copying, a correct _and_ efficient design is possible, whereas copying prevents an efficient design.

**Comment by giorio94** [comment]
> > I see. Do you think it would change that much in terms of GC pressure?
> 
> On the one hand, no - it's hard to measure this, and there's so much GC going on in the agent, that this would likely not have massive impact. On the other hand, it's exactly the cause for the somewhat staggering amount of memory used (and memory churn) that the agent exhibits. It's death by a thousand cuts, metaphorically.

Yeah, I'm just a bit concerned that we risk introducing difficult to find bugs for relatively little reward.

> 
> > I mean, I agree that the Node object can be pretty large, but on the other hand AFAIU it is not expected to change ony a few times during startup.
> 
> I don't think this will be true in the near future. As far as I'm aware, for multi network IPAM some information will need to live in `node.Node` (as all nodes need to know this about each other), and will change at runtime. If we start copying, this will become expensive quickly.

Fair enough, I didn't know about that.

> 
> Furthermore, I think the direction we're trying to take is eventually going to lead to a statedb Table of nodes, where this exact problem will resurface, as statedb also relies on the immutability of it's objects.
> 
> > And relying on consumers to create a copy of the modified fields can lead to subtle bugs, being easy to miss. Especially because most if not all readers currently only retrieve the latest value through the getters, which means that in most cases it just works fine even if the copy is missed. And the more we drop the global setters, the more this will risk to happen.
> 
> I agree that it's dangerous to rely on consumers to do the right thing. However, from a design perspective, it's a tradeoff: Without copying, a correct _and_ efficient design is possible, whereas copying prevents an efficient design.

That's definitely true. OK, let me move that back to draft until we converge on whether we want the deepcopy change or not.

**Pull request closed without merging**
