### PR TITLE
Improve building of the bpf/ directory

### PR DESCRIPTION
**Pull request by joestringer**
* Add datapath permutations for the overlay programs, now that they have optional macros
* Shift the datapath permutation building into a separate `build_all` target
* Add the `build_all` `bpf/` directory build target to the jenkins precheck
* Don't build all permutations of the datapath by default when running `make`.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8211)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
I guess the jenkins-precheck isn't the right place for this, given the lack of clang in the docker compose environment. Will need to rethink where to run the full BPF permutations build, or maybe add another compose container for this.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
@joestringer what makes this WIP still? It has passed the CI.

**Review by tgraf — APPROVED** [review]

**Pull request merged**
