### PR TITLE
v1.14 Backports 2023-07-19

### PR DESCRIPTION
**Pull request by gandro**
* [x] #26708 (@pchaigno)
 * [x] #26797 (@toVersus)
 * [x] #26891 (@dylandreimerink)
 * [x] #26856 (@brb)
 * [x] #26899 (@aanm)
 * [x] #26890 (@gandro)

PRs skipped due to conflicts:

 * #25440 (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 26708 26797 26891 26856 26899 26890; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=26708,26797,26891,26856,26899,26890
```

### CODE REVIEW

**Comment by gandro** [comment]
/test-backport-1.14

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks Sebastian!

**Review by aanm — APPROVED** [review]

**Comment by gandro** [comment]
- [ci-clustermesh](https://github.com/cilium/cilium/actions/runs/5596737627/jobs/10234158969) hit #26513

**Review by dylandreimerink — APPROVED** [review]

**Review by brb — APPROVED** [review]
Thanks!

**Comment by gandro** [comment]
Reviews are in, CI is green. Merging!

**Pull request merged**
