### PR TITLE
Add CRD validation for ciliumnodes.cilium.io

### LINKED ISSUE #9644: eni: agent failed to restart after patching wrong value in ciliumnode
## Bug report

**General Information**

- Cilium version 1.6.2
- Orchestration system version in use k8s 1.13.2

**How to reproduce the issue**

**1. start cilium-agent in `ipam:eni` mode, ciliumnode resource is created automatically
2. set random subnet-tags for this node**
```
kubectl patch ciliumnodes.cilium.io nodename --type='json' -p='[{"op": "replace", "path": "/spec/eni/subnet-tags", "value":[{"key":"testkey","value":"testvalue"}]}]'
```
The `subnet-tags` shown in describe ciliumnode:
```
Spec:
...
  Eni:
...
    Subnet - Tags:
      Key:     testkey
      Value:   testvalue
...
```
**3. restart cilium-agent, cilium-agent exited with the following logs:**

```
level=info msg="Updating CRD (CustomResourceDefinition)..." name=v2.CiliumIdentity subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=v2.CiliumIdentity subsys=k8s
level=info msg="k8s mode: Allowing localhost to reach local endpoints" subsys=daemon
level=info msg="Initializing node addressing" subsys=daemon
level=info msg="Restored IPv4 internal node IP: xx.xx.xx.xx" subsys=node
level=info msg="Initializing CRD-based IPAM" subsys=ipam
level=info msg="Subscribed to CiliumNode custom resource" name=nodename subsys=ipam
level=fatal msg="Unable to create CiliumNode resource" error="ciliumnodes.cilium.io \"nodename\" already exists" subsys=nodediscovery

```

### PR DESCRIPTION
**Pull request by ungureanuvladvictor**
Signed-off-by: Vlad Ungureanu <vladu@palantir.com>

Fixes: https://github.com/cilium/cilium/issues/9644

```release-note
Added CRD validation for ciliumnodes.cilium.io
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9655)

### CODE REVIEW

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
@ungureanuvladvictor I assume this is ready for review?

**Review by joestringer — APPROVED** [review]

**Comment by ungureanuvladvictor** [comment]
@aanm yep, ready for review. Curious on thought on the PR, first time I'm working with CRD validation and the upstream k8s docs are not super noob friendly on this.

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
Nice work @ungureanuvladvictor

**Pull request merged**
