### PR TITLE
Use "BPF host routing" instead of "fast redirect".

### LINKED ISSUE #18818: Unify the term points to the BPF Host Routing
Historically, BPF Host Routing was called Fast Redirect at some point. However, currently, we decided to go with "BPF Host Routing". We need to fix the code or comments that use the term Fast Redirect (or similar) to "BPF Host Routing".

Example of the place using Fast Redirect term
- https://github.com/cilium/cilium/blob/master/bpf/bpf_lxc.c#L910
- https://github.com/cilium/cilium/blob/master/daemon/cmd/devices.go#L73

### PR DESCRIPTION
**Pull request by chenk008**
This patch fixes the code or comments that use the term Fast Redirect (or similar) to "BPF host routing".

Fixes: #18818

Signed-off-by: chen kang <kongchen28@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: https://github.com/cilium/cilium/issues/18818

```release-note
Unify the term points "Fast Redirect" on host  to the "BPF Host Routing".
```

### CODE REVIEW

**Review by YutaroHayakawa — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution! We still need some work to make this PR merge.

1. There is a "fast redirect" left in the doc
- https://github.com/cilium/cilium/blame/8a5b71a51b3f84f2dd2a43f27bb35c07efccc6dc/Documentation/concepts/ebpf/intro.rst#L109
2. Please use `ENABLE_HOST_ROUTING` instead of `ENABLE_BPF_HOST_ROUTING`. We don't put `BPF` for other features (e.g., NodePort), so the former should be more consistent.

**Comment by chenk008** [comment]
@YutaroHayakawa Thanks for your review. I have rename `ENABLE_BPF_HOST_ROUTING` to `ENABLE_HOST_ROUTING`.

I am new to cilium. Does the `socketmap fast redirect` belongs to `BPF host routing`?

**Comment by YutaroHayakawa** [comment]
Oh, you're right. `socketmap fast redirect` is not related. My bad 🤦

**Review by YutaroHayakawa — APPROVED** [review]
Now it looks good to me. You still need to wait for approval from the maintainer. Meanwhile, I'll kick the tests.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
The changes are trivial and we already have two reviews, so I think we can skip the agent review. Marking ready to merge.

**Pull request merged**
