### PR TITLE
Test: Re-Enable kafka

### LINKED ISSUE #5309: CI: Fix Kafka test
The Kafka test is still unreliable. Problems arise while the Kafka cluster is bootstrapping.

Options:
- [ ] Consider http://strimzi.io/docs/0.6.0/#deploying-kafka-cluster-kubernetes-str

### PR DESCRIPTION
**Pull request by eloycoto**
- Use a `spotify/kafkaproxy` image instead of old one.
- Remove invalid egress rule to zook

Fix #5309

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5467)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

[green]

**Comment by tgraf** [comment]
test-me-please

**Review by ianvernon — COMMENTED** [review]
Changes look fine, but please triage the test failure that occurred in the most recent build.

**Comment by eloycoto** [comment]
test-me-please

[Green: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/6303/]

**Comment by eloycoto** [comment]
Jenkins build already deleted, trigger again to check what happens.

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
@ianvernon 3 times the green light, and one that I can't debug because Jenkins delete it. I think that this one is ready-to-merge.

Regards

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
