### PR TITLE
v1.9 backports 2022-02-22

### PR DESCRIPTION
**Pull request by jrajahalme**
* #18748 -- envoy: Update to release 1.21.0 (@jrajahalme)
 * #18899 -- envoy: Update to 1.21.1 (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18748 18899; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.9

**Comment by jrajahalme** [comment]
/test-backport-1.9

**Comment by joestringer** [comment]
[runtime-kernel-4.9](https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/5692/execution/node/116/log/) timed out while starting up Cilium. Might be a real issue? I'll re-kick it.
[k8s-upstream](https://jenkins.cilium.io/job/Cilium-PR-K8s-Upstream/3505/execution/node/52/log/) timed out while pulling VM images.
[k8s-1.12-kernel-netnext](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/1851/) hit #13853.

**Comment by joestringer** [comment]
/test-runtime-4.9

**Comment by joestringer** [comment]
On second look at the failed runtime run, it failed suspiciously at 20 minutes so I'm suspecting timeouts again. I don't know the underlying cause of the timeouts issue though.

**Comment by joestringer** [comment]
^^ I'm assuming that the above runtime issue is something weird about the runtime test deployment approach, as this doesn't affect any of the other runs which use a more typical k8s deployment model. In order to unblock the security release, I'll merge this as-is but this likely needs followup to fix the runtime job on this v1.9 branch @jrajahalme . Maybe something to do with how Envoy gets run in that environment.

**Comment by jrajahalme** [comment]
/test-runtime-4.9

**Pull request merged**
