### PR TITLE
[RFC] Enable policy-free DNS visibility

### PR DESCRIPTION
**Pull request by christarazi**
This PR is currently serving as an RFC for implementing policy-free DNS
visibility. This is the minimum implementation required to do so. See
https://github.com/cilium/hubble/issues/92.

This PR implements policy-free DNS visibility by allowing the user to set a
flag on Cilium (`--enable-dns-visibility`). This flag informs Cilium that upon
endpoint creation, it should inject a DNS visibility policy. Once the flag is
set, all endpoints will default to having DNS visibility. Other visibility
policies can be [set via pod annotations](https://docs.cilium.io/en/latest/policy/visibility/#proxy-visibility). If another annotation is added, the 
visibility policy will still contain DNS visibility. In other words, DNS visibility will
continue in the cluster, and is **not** overwritten. This can be tweaked in future 
iterations, if we prefer the overwriting behavior.

What's missing in this PR taking a comprehensive look at policy enforcement.
CNPs / CCNPs should be considered the source of truth for what to do with
traffic, regardless of the flag set. The constraint is to never allow the
visibility policy to allow traffic that should be denied. It's worth mentioning
that during my testing, I applied an [FQDN policy](https://docs.cilium.io/en/latest/gettingstarted/dns/#dns-policies-using-patterns) and tweaked it to allow only
resolution of `*.twitter.com` domains, I observed that all other domains were 
denied, which is good. This is expected.

I am open to hearing feedback on this approach and whether this PR has some
blind spots, especially from the policy enforcement perspective.

---

Tested by following:
https://docs.cilium.io/en/latest/gettingstarted/dns/#deploy-the-demo-application

See commit msgs.

### CODE REVIEW

**Comment by citosid** [comment]
Is there any work to pursue this configuration?

**Comment by christarazi** [comment]
@jrajahalme Does https://github.com/cilium/cilium/pull/16258/ supersede this PR and fix https://github.com/cilium/hubble/issues/92?

**Comment by joestringer** [comment]
This seems not far from being able to merge - just need someone to pick it up and take it over the line. If we find someone to work on it, let's push it forward. Otherwise we can drop it.

**Comment by citosid** [comment]
@joestringer #16258 fixes this?

**Comment by joestringer** [comment]
@citosid no, the core idea here is a "set once and forget" setting, but there's not sufficient contributor involvement to drive it over the line.

#30572 could potentially help with this by allowing you to create a new network policy that *only* applies the DNS redirect to learn about DNS names, without enforcing a default deny.

**Pull request closed without merging**
