### PR TITLE
Set VERSION to 1.14.0-dev

### PR DESCRIPTION
**Pull request by michi-covalent**
1.14.0-dev is more accurate version than 1.13.90 for the development branch for the next Cilium minor release, which is 1.14.0.

### CODE REVIEW

**Comment by michi-covalent** [comment]
i have a lingering suspicion this will break some release scripts somewhere. requesting review from andre and joe.

**Comment by joestringer** [comment]
In principle I'm OK with this, I just don't know what breaks or how to detect that (I guess one way is just try and see..). Anything using a proper semver-v2 library will properly match this as <1.14.0, the long tail is random bash scripts with more naive version checks.

For release scripts specifically it's probably not too much of a problem, because we change the version for all releases--both snapshots or regular releases-- so I wouldn't expect this version number to show up in a release at all.

**Comment by joestringer** [comment]
Helm chart failure is caused by the PR, helm charts include this version string in them.

**Review by tommyp1ckles — APPROVED** [review]

**Review by aanm — CHANGES_REQUESTED** [review]
https://github.com/cilium/cilium/blob/v1.13.2/test/helpers/cons.go#L179 is also missing

**Review by gandro — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Pull request merged**
