### PR TITLE
Backport/v1.0 2018 04 20

### PR DESCRIPTION
**Pull request by raybejjani**
Backports for: https://github.com/cilium/cilium/pull/3824 https://github.com/cilium/cilium/pull/3806 https://github.com/cilium/cilium/pull/3829

    bpf: Fix tracing message for egress policy

    [ upstream commit adc46707494ba108aef26d9e85dd56ee8290afee ]

    Previously, this would print the source and destination in the wrong
    order. Fix it up.

    bpf: Fix default build config

    [ upstream commit c7b00124fb1ed598dc2607f950c995075a3beaa5 ]

    The policy prog array is indexed by LXC index, so it needs to be as big
    as the ENDPOINTS_MAP_SIZE. Fix it up in the node_config.

    This only affects developers that build the bpf/ directory then attempt
    to load BPF programs from it directly into the kernel without using the
    rest of Cilium to orchestrate.

    etcd: Clear the etcd status error when connectivity is OK

    [ upstream commit 5fb78adb81052b449834de960704ff017fbb950a ]

    Fixes: 9f9086e5c68aea7556dbec3b98a249ca7520863a

    Test: Fix issues with Updates and Kube-dns

    [ upstream commit c01603b2450536d5f5c8215aebed9d00957b096a ]

    On `k8sT/Update.go` the system install a new cilium v1.0 image, but it
    does not wait for Kubedns to be ready, so time to time the kubedns was
    not ready at all.

    With this commit we make sure that the DNS is ready before applied any
    policy.

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by ianvernon** [comment]
@raybejjani is this needed for 1.0?

**Review by tgraf — APPROVED** [review]

**Comment by raybejjani** [comment]
oops. Yes. I thought it was merged! it was needed.

**Pull request merged**
