### PR TITLE
v1.5: backports 19 07 22

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:

* PR: 8508 -- test: move creation of Istio resources into `It` (@ianvernon) -- https://github.com/cilium/cilium/pull/8508
* **had conflicts** PR: 8547 -- operator: restart non-managed kube-dns pods before connecting to etcd (@aanm) -- https://github.com/cilium/cilium/pull/8547
* **had conflicts** PR: 8544 -- pkg/{kvstore,node}: delay node delete event in kvstore (@aanm) -- https://github.com/cilium/cilium/pull/8544
* PR: 8575 -- docs: Fix up unparsed SCM_WEB literals (@joestringer) -- https://github.com/cilium/cilium/pull/8575
* PR: 8579 -- test: add `ExecMiddle` function (@ianvernon) -- https://github.com/cilium/cilium/pull/8579
* PR: 8548 -- test: misc. runtime policy test fixes (@ianvernon) -- https://github.com/cilium/cilium/pull/8548
* **had conflicts** PR: 8551 -- RFC: endpoint: change transition from restore state (@ianvernon) -- https://github.com/cilium/cilium/pull/8551
* PR: 8612 -- proxy: Perform dnsproxy Close() in the returned finalizeFunc (@jrajahalme) -- https://github.com/cilium/cilium/pull/8612
* **had conflicts** PR: 8618 -- endpoint: Create redirects before bpf map updates. (@jrajahalme) -- https://github.com/cilium/cilium/pull/8618 
* PR: #8611 -- pkg/kvstore: wait for node delete delay in unit tests (@aanm) -- https://github.com/cilium/cilium/pull/8611 

Not backported due to conflicts that were difficult to resolve:

 * **had conflicts** PR: 8583 -- proxy: Do not error out if reading of open ports fails. (@jrajahalme) -- https://github.com/cilium/cilium/pull/8583
* **had conflicts** PR: 8566 -- daemon: Remove svc from cache in syncLBMapsWithK8s (@brb) -- https://github.com/cilium/cilium/pull/8566
* **had conflicts** PR: 8581 -- envoy: Add SO_MARK option to listener config (@jrajahalme) -- https://github.com/cilium/cilium/pull/8581

When you have backported the above commits, you can update the PR labels via this command:
```
$ for pr in 8508 8547 8544 8575 8579 8581 8548 8551 8612 8618; do contrib/backporting/set-labels.py $pr done 1.5; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8640)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]

**Comment by jrajahalme** [comment]
#8581 likely needs a vendor update for the `cilium/proxy`. On master it is done by commit 2777f9b6038. Backporting it before #8581 should resolve the backport problem.

**Review by aanm — APPROVED** [review]
All good from my side, the conflicts were minor and they were addressed properly.

**Comment by aanm** [comment]
@ianvernon https://github.com/cilium/cilium/pull/8611 also needs to be backported.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
K8s-Upstream test failed: https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/1411/flowGraphTable/

This test has had problems for a while, so it's not related to this PR. Merging.

**Pull request merged**
