### PR TITLE
v1.10 backports 2022-05-17

### PR DESCRIPTION
**Pull request by christarazi**
* #19702 -- fqdn/dnsproxy: Improve error wrapping (@christarazi)
 * #19759 -- helm: don't generate the hubble-peer svc during preflight checks (@kaworu)
 * #19592 -- Add concurrency limiting for DNS message processing (@nebril)
 * #19767 -- docs: Fix incorrect command in IPsec GSG (@pchaigno)
 * #19794 -- cli: Update regex for key value validation (@sayboras)
 * #19830 -- Change default agent health check port to avoid conflicts (@tklauser)
 * #19918 -- jenkins: switch to ad-hoc GKE cluster creation/deletion (@nbusseneau)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 19702 19759 19592 19767 19794 19830 19918; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
thanks and looks good for my changes.

**Review by tklauser — APPROVED** [review]
Looks good for my commits. Thanks!

**Comment by christarazi** [comment]
/test-backport-1.10

**Review by pchaigno — COMMENTED** [review]
My change looks good. Thanks!

**Review by nebril — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]

**Review by kaworu — APPROVED** [review]

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-1.19-5.4

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Review by nbusseneau — APPROVED** [review]
My commits LGTM.

**Comment by jibi** [comment]
/test-1.19-5.4

**Comment by jibi** [comment]
CI is green, beside `ci-gke-1.10` failing to clean up the cluster:
```
⌛ Waiting for Cilium to be uninstalled...
⌛ Waiting for cilium-test namespace to be terminated...
Error: The operation was canceled.
```

**Pull request merged**
