### PR TITLE
cilium: add test for lb + proxy

### PR DESCRIPTION
**Pull request by jrfastab**
Add test for running load balancer with proxy. This exercises a
code path that was previously missing in test suite.

Signed-off-by: John Fastabend <john.fastabend@gmail.com>

### CODE REVIEW

**Comment by jrfastab** [comment]
With all features enabled, conntrack, ingress, and services the policy can take some extra time to be compiled and enabled. The latest pull request adds a helper routine to wait for policy to be enabled to ensure we do not run tests before policy is applied.

**Comment by jrfastab** [comment]
Tests hangs after `16-cidr-ingress-policy.sh` with message `Waiting for Cilium to get into 'ready' state in Minikube cluster`

**Comment by jrfastab** [comment]
Kick jenkins again to verify we get the same error because it seems unrelated to these changes that touch ./10-proxy.sh tests.

**Comment by ianvernon** [comment]
The message `Waiting for Cilium to get into 'ready' state in Minikube cluster` indicates an issue in the K8s VM, which runs separately from the runtime tests.

**Review by tgraf — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@ianvernon can we also create a tar.gz for the k8s tests with the logs of all kubernetes components?

**Comment by ianvernon** [comment]
@aanm #1040 created to track this

**Pull request merged**
