### PR TITLE
hubble: Add support for PERF_RECORD_LOST

### PR DESCRIPTION
**Pull request by gandro**
This modifies the Hubble monitor payload parser to understand `PERF_RECOD_LOST` events and expose it via API. Such losses occur when cilium-agent is not reading the BPF `perf_event_array` quick enough. `cilium monitor` already supports reporting such losses, this PR therefore is related to #12416. Previously, these events were dropped in the parser with an `ErrEmptyData` error.

The new API message is called `LostEvent`. It is used to inform Hubble clients about a loss of messages in the pipeline, not just in the BPF ring buffer (but this PR only uses it for `PERF_RECOD_LOST`). The parser and observer RPC `GetFlows` stub to decode and process `LossEvent` as well.

This is a backwards-compatible change, as existing clients will ignore this new message.

The following features are omitted intentionally in this PR:

- [ ] CI tests. This requires the CLI to be updated first (https://github.com/cilium/hubble/pull/315). However I have locally validated that it works.
- [ ] `LostEvent` messages for `OBSERVER_EVENTS_QUEUE`. Such an event will be emitted if this condition is met:
https://github.com/cilium/cilium/blob/9db20dc31942c590469d395be03c547774d50493/pkg/hubble/listener/listener.go#L49-L51
It is part of the API definition, but not yet implemented, as it is not clear how to signal such events via the existing Hubble events queue type. I am planning to rework the plumbing from the monitor agent to Hubble to avoid the unnecessary gob encoding and decoding of agent notifications, which will require changes the signature of Hubble's events queue, therefore I hope to support for `OBSERVER_EVENTS_QUEUE` then.

---

**Reviewable per commit**

### CODE REVIEW

**Comment by gandro** [comment]
test-me-please

**Comment by gandro** [comment]
test-me-please

**Comment by gandro** [comment]
test-me-please

**Review by glibsm — APPROVED** [review]
> I am planning to rework the plumbing

Good luck :)

**Comment by gandro** [comment]
Rebased on master due to conflicts.

**Comment by gandro** [comment]
test-me-please

**Review by rolinh — APPROVED** [review]
LGTM!

**Pull request merged**
