### PR TITLE
Logging: Add klog override matcher to remap certain errors to "info" level

### LINKED ISSUE #31374: CI: Cilium E2E Upgrade - failed to update lock
## CI failure

```
[=] Test [check-log-errors] [77/77]
..
  [-] Scenario [check-log-errors/no-errors-in-logs]
  [.] Action [check-log-errors/no-errors-in-logs/kind-kind/kube-system/cilium-operator-67b967df64-c9zjt (cilium-operator)]
  [.] Action [check-log-errors/no-errors-in-logs/kind-kind/kube-system/cilium-operator-67b967df64-pzzf5 (cilium-operator)]
  ❌ Found 1 logs in kind-kind/kube-system/cilium-operator-67b967df64-pzzf5 (cilium-operator) matching list of errors that must be investigated:
level=error msg="Failed to update lock: Operation cannot be fulfilled on leases.coordination.k8s.io \"cilium-operator-resource-lock\": the object has been modified; please apply your changes to the latest version and try again" subsys=klog (1 occurrences)
```

Should be added to the list of error message exceptions similar to a fix here https://github.com/cilium/cilium/pull/23334

### PR DESCRIPTION
**Pull request by tommyp1ckles**
Fixes: https://github.com/cilium/cilium/issues/31374

### CODE REVIEW

**Comment by tklauser** [comment]
Instead of remapping the errors to info level, have you considered just ignoring the error in the connectivity tests, like we do for other error logs?

**Comment by tklauser** [comment]
Upon closer inspection, it seems like we already ignore it:

https://github.com/cilium/cilium/blob/f460408cc91d976a40e62369c168926261699ecc/cilium-cli/connectivity/tests/errors.go#L258

and

https://github.com/cilium/cilium/blob/f460408cc91d976a40e62369c168926261699ecc/cilium-cli/connectivity/tests/errors.go#L50

Any idea why this is not enough to ignore it?

**Comment by tommyp1ckles** [comment]
> Instead of remapping the errors to info level, have you considered just ignoring the error in the connectivity tests, like we do for other error logs?
@tklauser This fundamentally doesn't feel like a error to me, hence the thinking was that we still want to display it to users, but it would be misleading to emit it as a error since it doesn't inherently imply any degradation.

**Comment by tommyp1ckles** [comment]
> Any idea why this is not enough to ignore it?

The semicolon is breaking the matching, the log currently appears as: `Failed to update lock optimitically` (think I saw you on the upstream client-go commit to fix the spelling 😄 )

**Comment by tklauser** [comment]
> > Instead of remapping the errors to info level, have you considered just ignoring the error in the connectivity tests, like we do for other error logs?
> 
> @tklauser This fundamentally doesn't feel like a error to me, hence the thinking was that we still want to display it to users, but it would be misleading to emit it as a error since it doesn't inherently imply any degradation.

That makes sense, thanks for the explanation.

> This is quite a bit of change for such a small issue, but the intention was to setup the code to future such remappings.

Let's hope we won't need it too often :sweat_smile: 

> Maybe we should just propose changing the log level upstream in k8s client-go however, and ignore it for now.

Yeah, that would IMO be the optimal solution.

**Review by squeed — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
The `misspell` linter is complaining about mispelled being misspelled 😄

image

Otherwise LGTM

**Pull request merged**
