### PR TITLE
v1.16 Backports 2024-11-19

### PR DESCRIPTION
**Pull request by sayboras**
* [ ] #35943 (@sayboras)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 35943
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.16

**Comment by sayboras** [comment]
/test-backport-1.16

**Comment by sayboras** [comment]
/test-backport-1.16

**Comment by sayboras** [comment]
/test-backport-1.16

**Review by tklauser — APPROVED** [review]

**Pull request merged**
