### PR TITLE
cilium: add minor annotation mode follow-ups

### PR DESCRIPTION
**Pull request by borkmann**
(see commit desc)

### CODE REVIEW

**Review by brb — APPROVED** [review]

**Review by gandro — APPROVED** [review]
Helm looks good to me.

I assume we can do this without a breaking change because we haven't shipped the annotation yet, right?

**Comment by borkmann** [comment]
> I assume we can do this without a breaking change because we haven't shipped the annotation yet, right?

Yes, correct

**Review by mhofstetter — APPROVED** [review]
LGTM, thanks for the rename of the annotation!

**Review by brb — APPROVED** [review]

**Pull request merged**
