### PR TITLE
v1.10 backports 2022-02-07

### PR DESCRIPTION
**Pull request by joamaki**
* #18583 -- docs: add Hands-on tutorial (@vannyle)
 * #18563 -- Fix local redirect policies selecting host networked pods (@aditighag)
 * #18277 -- clustermesh-apiserver: fix cmd-line args processing (@abocim)
 * #18478 -- cmd: Fix issue reading string map type via config map (@sayboras)
 * #18671 -- docs: disable k3s network policy enforcement (@tklauser)
 * #18697 -- docs: export KUBECONFIG for cilium-cli with k3s (@tklauser)
 * #18693 -- labelfilter: Refine default label regexps (@twpayne)
 * #18707 -- ci: remove box download timeout in upstream tests (@nbusseneau)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18583 18563 18277 18478 18671 18697 18693 18707; do contrib/backporting/set-labels.py $pr done 1.10; done
```
or with
```
$ make add-label branch=v1.10 issues=18583,18563,18277,18478,18671,18697,18693,18707
```

### CODE REVIEW

**Comment by joamaki** [comment]
Backport of https://github.com/cilium/cilium/pull/18486 skipped as it requires more manual work. @bmcustodio is taking a look.

**Review by aditighag — APPROVED** [review]
Backport of my PR looks good.Thanks!

**Review by nbusseneau — APPROVED** [review]
My changes LGTM.

**Comment by joamaki** [comment]
/test-backport-1.10

**Comment by sayboras** [comment]
> Ok, failed due to use of t.Setenv which was introduced in Go v1.17. Refactored the code to use os.Setenv and clean up just like t.Setenv. @sayboras could you take a look at https://github.com/cilium/cilium/commit/e6d1f747d013a63faf6205932e8ea38f8817a55c and let me know if my changes made sense?

The adapting changes for go 1.16 looks good to me, thanks for taking care of this.

**Review by sayboras — APPROVED** [review]
Looks good for my commit

**Comment by joamaki** [comment]
/test-1.16-netnext

**Comment by joamaki** [comment]
oops, I missed reviews from @tklauser and @twpayne before merging. could you guys check?

**Review by twpayne — COMMENTED** [review]
LGTM

**Pull request merged**
