### PR TITLE
v1.9 backports 2020-10-26

### PR DESCRIPTION
**Pull request by gandro**
* #13710 -- Update wording for BPFFS requirement and move to main system requirements page (@joestringer)
 * #13702 -- pkg/endpoint: calculate Kube API-Server lag from pod events (@aanm)
 * #13713 -- doc: Update OpenShift GSG (@michi-covalent)
 * #13606 -- datapath: Decouple IPV4_MASQUERADE from IPV4_NODEPORT (@brb)
 * #13719 -- docs: remove repeated words (@tklauser)
 * #13669 -- doc: update Hubble doc for 1.9 (@Rolinh)
 * #13718 -- ci: Print hint to fix auto-generated file checks (@sayboras)
 * #13717 -- docs: Add a note about systemd 245 rp_filter issue (@brb)
 * #13733 -- docs: Do not over promise in BPF-masq docs (@brb)
 * #13726 -- nodeinit: Update image tag (@errordeveloper)
 * #13716 -- Fix deadlock on eventqueue when it's being drained when endpoints are being restored (@christarazi)
 * #13737 -- docs: Various LRP gsg fixups (@nebril)
 * #13729 -- pkg/k8s: keep resource version when watching CRDs (@aanm)
 * #13682 -- Helm: Adapt Hubble ingress template to the new Ingress API (@youssefazrak)
 * #13674 -- Various fixes for NodePort XDP kube-proxy free guide (@tklauser)
 * #13707 -- backporting: Clean tmp files after backport with conflicts (@pchaigno)
 * #13636 -- certloader: Fix reload on K8s Secret/ConfigMap update (@gandro)
 * #13730 -- Remove remnants of bindata check script (@tklauser)
 * #13728 -- operator: do not early return on CEP GC (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13710 13702 13713 13606 13719 13669 13718 13717 13733 13726 13716 13737 13729 13682 13674 13707 13636 13730 13728; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Review by aanm — APPROVED** [review]
All good for my PRs

**Review by sayboras — APPROVED** [review]
looks good for my commit

**Comment by gandro** [comment]
test-backport-1.9

**Comment by gandro** [comment]
Putting this back into draft. I noticed that two commits from PR #13674 are missing, because the scripts did not correlate the commits due to escaping errors in the commit message (which is used as a regex). Will move out of draft once I fixed that issue and made sure the script picks up the commits properly.

**Review by rolinh — APPROVED** [review]

**Review by errordeveloper — APPROVED** [review]
My commit looks good, also checked Michi's OpenShift doc update - looks good too!

**Comment by youssefazrak** [comment]
Looks good for my commit

**Review by tklauser — CHANGES_REQUESTED** [review]
~Looks like backports for commits b32876d07fe93504616d3b769d1bd0fa2e93a7ea and c0b8a82366f573470afe62bdce4463bd8a56174d from #13674 are missing (while f8fe7b5fd471a9dfdfb6442f6f1065797c8f0a2f was properly backported). I didn't spot anything in the PR description regarding these. Were they overlooked, were there merge conflicts or did I miss something?~

Sorry, only saw https://github.com/cilium/cilium/pull/13751#issuecomment-716512945 after I submitted this. LGTM once this is resolved.

**Comment by gandro** [comment]
> Looks like backports for commits [b32876d](https://github.com/cilium/cilium/commit/b32876d07fe93504616d3b769d1bd0fa2e93a7ea) and [c0b8a82](https://github.com/cilium/cilium/commit/c0b8a82366f573470afe62bdce4463bd8a56174d) from #13674 are missing (while [f8fe7b5](https://github.com/cilium/cilium/commit/f8fe7b5fd471a9dfdfb6442f6f1065797c8f0a2f) was properly backported). I didn't spot anything in the PR description regarding these. Were they overlooked, were there merge conflicts or did I miss something?

See https://github.com/cilium/cilium/pull/13751#issuecomment-716512945 ;) While I could easily add them manually, I want to fix the scripts first to properly escape the commit messages.

**Review by tklauser — APPROVED** [review]
LGTM given https://github.com/cilium/cilium/pull/13751#issuecomment-716512945 is resolved.

**Comment by gandro** [comment]
Pushed the two missing commits. It's now 33 commits, same as the output of `check-stable`. I'll open a PR with the partial fix for the scripts.

**Comment by gandro** [comment]
test-backport-1.9

**Review by christarazi — APPROVED** [review]
LGTM for my commits

**Pull request merged**
