### PR TITLE
vagrant: Bump all Vagrant box versions

### PR DESCRIPTION
**Pull request by pchaigno**
Mostly to pick up the latest commits on bpf-next, which fix vulnerabilities but may increase complexity.

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-runtime

**Comment by pchaigno** [comment]
test-runtime

**Comment by pchaigno** [comment]
test-1.21-4.9

**Comment by pchaigno** [comment]
test-runtime

**Review by tklauser — APPROVED** [review]

**Comment by pchaigno** [comment]
test-runtime

**Comment by pchaigno** [comment]
Blocked on https://github.com/cilium/packer-ci-build/pull/277.

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-runtime

**Comment by pchaigno** [comment]
test-1.20-4.19

**Comment by pchaigno** [comment]
k8s-1.16-kernel-netnext is hitting know flake https://github.com/cilium/cilium/issues/13853 and https://github.com/cilium/cilium/issues/16402#issuecomment-861544964. Other tests are passing or not covering these changes. The CI team review is covered. Marking as ready to merge.

**Comment by pchaigno** [comment]
I marked for backports as the net-next bump may impact complexity.

**Comment by pchaigno** [comment]
Removing from v1.9 backports until https://github.com/cilium/cilium/issues/16964 is addressed.

**Comment by pchaigno** [comment]
Marked again for v1.9 backports as backporting https://github.com/cilium/cilium/pull/15397 as well should fix https://github.com/cilium/cilium/issues/16964.

**Pull request merged**
