### PR TITLE
docs: Add an install guide to use Kata Containers with Cilium

### PR DESCRIPTION
**Pull request by amshinde**
The guide provides the steps for setting up Kata Containers
with Cilium CNI on GCE.

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7882)

### CODE REVIEW

**Review by aanm — CHANGES_REQUESTED** [review]
@amshinde everything looks great!

can you change all URLs from `https://raw.githubusercontent.com/kata-containers/packaging/master/` to point to a tag instead of master?

Also, what's the minimal Cilium version required?

**Comment by aanm** [comment]
test-docs-please

**Comment by amshinde** [comment]
@aanm Will add the appropriate commit.
I had simply tried this out with Cilium 1.4 at the time to test out some other features.
But for just the CNI to work with Kata, anything that works with docker-runc should work with Kata.

**Comment by amshinde** [comment]
cc @jrfastab

**Review by jrfastab — APPROVED** [review]
Looks like a good start to me. We can refine as needed.

**Comment by jrfastab** [comment]
For minimum Cilium version should we backport this to a 1.5.x release? And master for 1.6.

**Pull request merged**
