### PR TITLE
v1.8: Update Go to 1.14.12

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
test-backport-1.8

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
retest-4.19

**Review by christarazi — APPROVED** [review]

**Comment by christarazi** [comment]
retest-4.19

**Comment by tklauser** [comment]
retest-4.19

**Comment by tklauser** [comment]
retest-4.19

**Comment by tklauser** [comment]
retest-4.19

**Comment by tklauser** [comment]
test-backport-1.8

**Comment by tklauser** [comment]
Will rebase once #14059 (with a backport of #14053) is merged to solve the Go GH action failing.

**Comment by tklauser** [comment]
test-backport-1.8

**Comment by tklauser** [comment]
test-upstream-k8s

**Comment by tklauser** [comment]
retest-runtime

**Pull request merged**
