### PR TITLE
Backports v1.0

### PR DESCRIPTION
**Pull request by eloycoto**
PR: 

https://github.com/cilium/cilium/pull/4067
https://github.com/cilium/cilium/pull/4072
https://github.com/cilium/cilium/pull/4078
https://github.com/cilium/cilium/pull/4079
https://github.com/cilium/cilium/pull/4096
https://github.com/cilium/cilium/pull/4095

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
This build failed on import policy: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3185/testReport/junit/(root)/runtime/RuntimeValidatedMonitorTest_With_Sample_Containers_Cilium_monitor_event_types/

Maybe related with https://github.com/cilium/cilium/pull/4079, but it's in this branch, @joestringer can you confirm? Any other changed needed?

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
