### PR TITLE
doc: Add doc for disk based cilium network policy

### PR DESCRIPTION
**Pull request by tamilmani1989**
Please ensure your pull request adheres to the following guidelines:

- [] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #issue-number

### CODE REVIEW

**Comment by joestringer** [comment]
Hi @tamilmani1989 , please update the release note to capture the user-facing implications of the change, or alternatively remove the entire block including the grave characters.

Currently the content in the PR description is this:
````
```release-note
1.16
```
````

In the release note this will show up as:

- 1.16 (33854, @tamilmani1989)

**Review by qmonnet — APPROVED** [review]
Looks good, thank you. Please make sure to address Joe's comment for the PR description.

**Pull request merged**
