### PR TITLE
v1.1 backports 18 10 17

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:

* #5909

Not-backported PRs:
* #5911 - I did not feel confident trying to resolve conflicts; I've asked @jrajahalme to backport accordingly.

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5917)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by tgraf** [comment]
test-docs-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
