### PR TITLE
Vagrant: Update images to 108.

### PR DESCRIPTION
**Pull request by eloycoto**
Update images to 108 to avoid the issues that we had with 107.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5402)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by ianvernon** [comment]
@eloycoto what is the difference between 107 and 108 exactly? Please elaborate on how this will fix the issues faced with build 107.

**Comment by eloycoto** [comment]
@ianvernon done

**Comment by eloycoto** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
