### PR TITLE
tests: update complexity check script to include new calls

### LINKED ISSUE #10100: Fix `test/bpf/check-complexity.sh`
```
$ sudo -E ./test/bpf/check-complexity.sh 
This script is out of date compared to CILIUM_CALL_SIZE.
```

Need to fix up the script to include the new `CILIUM_CALL_*` options.

(Note: If you hit `ELF contains non-{map,call} related relo data in entry 3 pointing to section 31! Compiler bug?!` then ensure you are specifying `TC=/path/to/tc/with/static/data` using a TC compiled from here: https://github.com/cilium/iproute2/tree/static-data)

### PR DESCRIPTION
**Pull request by fristonio**
Fixes #10100

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10106)

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
test-me-please

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
@joestringer should we put this in 1.7? I don't see why not

**Pull request merged**
