### PR TITLE
daemon: log any error returned by RestoreServices()

### PR DESCRIPTION
**Pull request by jibi**

### CODE REVIEW

**Comment by jibi** [comment]
test-me-please

**Review by joamaki — APPROVED** [review]
LGTM

**Review by brb — APPROVED** [review]
LGTM, thanks. Perhaps the next step is to check whether in `RestoreServices()` we don't return upon a first failure (we should try to restore as much as possible instead).

**Comment by pchaigno** [comment]
This pull request doesn't seem to be among the exceptions for the merge freeze, so removing `ready-to-merge` label.

**Comment by aanm** [comment]
@jibi can you rebase the PR and trigger the tests? Thanks

**Review by ldelossa — APPROVED** [review]

**Pull request merged**
