### PR TITLE
Refactor /config for API 1.0 stability

### PR DESCRIPTION
**Pull request by raybejjani**
*Note: This PR is a diff to https://github.com/cilium/cilium/pull/3389. Please don't merge.
See https://github.com/cilium/cilium/issues/3280 for background

**Summary of changes**:
- Refactor the daemon config to be declarative.

**How to test (optional)**:
all tests should pass.

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
Looks good. We'll need to squash this to not break bisecting

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
Yeah, the autogeneration commits will be squashed, it was just easier to look at the changes locally if I kept them separate. Each PR can me merged separately (and nothing should break) but I can also squash all API changes if you prefer, but that commit will be larger.

**Comment by raybejjani** [comment]
Also, @tgraf, the PRs are chained so you might want to start with https://github.com/cilium/cilium/pull/3388

**Comment by tgraf** [comment]
@raybejjani So you suggest to merge #3388 first?

**Comment by raybejjani** [comment]
@tgraf Yes. I'd then switch this PR to be against `cilium:master`. It's a little tedious. If you prefer, we can approve all the API PRs and I can make a combo PR that holds all the commits and we would merge that in one go.

**Comment by raybejjani** [comment]
In any case, however, #3388 hasn't passed tests yet :/ but I've seen failures with `K8sValidatedPolicyTestAcrossNamespaces Policies Across Namespaces`, `RuntimeValidatedPolicyImportTests [It] Check Endpoint PolicyMap Generation` and `RuntimeValidatedMonitorTest With Sample Containers [It] cilium monitor check --from` which I hope are unrelated

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Pull request closed without merging**
