### PR TITLE
Fix `cilium metrics list`: revert "prometheus/client_golang"

### LINKED ISSUE #19425: CI: ci-external-workload: Cilium API handler panicked
## CI failure

Seen in one of the agent logs attached to the zip in here:
```
2022-04-13T08:05:39.897310085Z level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2022-04-13T08:07:15.761674513Z level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2022-04-13T08:08:21.258858526Z level=warning msg="Cilium API handler panicked" client=@ method=GET panic_message="json: unsupported value: NaN" subsys=api url=/v1/metrics/
2022-04-13T08:08:21.259518780Z 2022/04/13 08:08:21 http: superfluous response.WriteHeader call from github.com/cilium/cilium/pkg/api.(*APIPanicHandler).ServeHTTP.func1 (apipanic.go:36)
```

https://github.com/cilium/cilium/actions/runs/2158036465
[cilium-sysdump-out.zip (23).zip](https://github.com/cilium/cilium/files/8479547/cilium-sysdump-out.zip.23.zip)

### PR DESCRIPTION
**Pull request by ti-mo**
This reverts commit d8e3f28c01f04b4c314b65e090a21c2aaf235207.

Extra Go metrics were added to the Prometheus client, some having NaN values, breaking json marshaling on the server side of `cilium metrics list`:

`msg="Cilium API handler panicked" panic_message="json: unsupported value: NaN" url=/v1/metrics/ ...`

Fixes: #19425

```release-note
Revert Prometheus client to fix 'cilium metrics list'
```

### CODE REVIEW

**Review by tklauser — CHANGES_REQUESTED** [review]
Probably makes sense to ignore `github.com/prometheus/client_golang` in the dependabot config until a new version with a fix is released. So the bot won't attempt to update the dependency again.

https://github.com/cilium/cilium/blob/b79ebcf9f752179ee9fecc26a0b488fa83bb42a2/.github/dependabot.yml#L9-L18

**Review by tklauser — APPROVED** [review]

**Review by rolinh — CHANGES_REQUESTED** [review]
While we're at it and given that dependabot ignores this dep for now, could we bump from v1.11.0 to [v1.11.1](https://github.com/prometheus/client_golang/releases/tag/v1.11.1) to pull in the security fix?

**Review by qmonnet — APPROVED** [review]

**Comment by ti-mo** [comment]
@rolinh Good point, done!

**Review by rolinh — APPROVED** [review]

**Review by borkmann — APPROVED** [review]

**Comment by joestringer** [comment]
This seems like a straightforward revert, approvals are in. The CI runs below are hitting issues, the kafka one looks new to me but I don't understand how the PR could be related:

https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/8303/
https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/2030/

Please do consider filing issues or referencing existing issues if these are flakes we are not yet tracking. However, given this is resolving a known issue due to the dependency bump, and reverting back to the previous version should be safe, I think this is good to merge.

**Pull request merged**
