### PR TITLE
v1.9 backports 2021-03-31

### PR DESCRIPTION
**Pull request by aanm**
* #14752 -- vendor: Update sigs.k8s.io/structured-merge-diff/v4 (@christarazi)
~* #15321 -- bpf: Skip policy enforcements for service loopback case (@aditighag)~
 * #15395 -- test: make RunsOnNetNextKernel() helper work with KERNEL="net-next" (@qmonnet)
 * #15454 -- docs: De-duplicate k8s integration section (@joestringer)
 * #15320 -- docs: Update VM support to use cilium-cli (@jrajahalme)
 * #15463 -- docs: fix the Cilium namespace in GKE (@kaworu)
 * #15481 -- docs: Fix commands for IPSec key rotations (@pchaigno)
 * #15294 -- Improve release scripts (@joestringer)
 * #15495 -- build(deps): bump pygments from 2.4.2 to 2.7.4 in /Documentation (@dependabot[bot])
 * #15380 -- Add Cluster Health metrics (@h3llix)
 * #15458 -- daemon: Add command line option --tofqdns-idle-connection-grace-period (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14752 15395 15454 15320 15463 15481 15294 15495 15380 15458; do contrib/backporting/set-labels.py $pr done 1.9; done
```

@brb the PR 15431 -- node-neigh: Query once netlink for neigh discovery device (@brb) was not backported due conflicts.
@aditighag the PR 15321 -- bpf: Skip policy enforcements for service loopback case (@aditighag) was not backported due test failures in the `Smoke test / conformance-test (pull_request)` GH action:

```
2021-04-01T00:21:35.209344853Z level=error msg="Error while rewriting endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=199 error="Failed to load tc filter: exit status 1" identity=62540 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-04-01T00:21:35.209463859Z level=warning msg="generating BPF for endpoint failed, keeping stale directory." containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=199 file-path=199_next_fail identity=62540 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-04-01T00:21:35.209633169Z level=warning msg="Regeneration of endpoint failed" bpfCompilation=0s bpfLoadProg=55.878847999s bpfWaitForELF="4.801µs" bpfWriteELF="281.115µs" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=199 error="Failed to load tc filter: exit status 1" identity=62540 ipv4= ipv6= k8sPodName=/ mapSync="28.901µs" policyCalculation="64.103µs" prepareBuild="383.421µs" proxyConfiguration="9.501µs" proxyPolicyCalculation="15.401µs" proxyWaitForAck=0s reason="updated security labels" subsys=endpoint total=55.883503347s waitingForCTClean=2.667141ms waitingForLock="33.302µs"
2021-04-01T00:21:35.209809978Z level=error msg="endpoint regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=199 error="Failed to load tc filter: exit status 1" identity=62540 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-04-01T00:22:09.524005490Z level=info msg="Processing API request with rate limiter" name=endpoint-delete parallelRequests=4 subsys=rate uuid=4c1afae8-9280-11eb-a864-0242ac120003
2021-04-01T00:22:09.524044592Z level=info msg="API request released by rate limiter" name=endpoint-delete parallelRequests=4 subsys=rate uuid=4c1afae8-9280-11eb-a864-0242ac120003 waitDurationTotal="65.404µs"
2021-04-01T00:22:09.524051693Z level=info msg="Delete endpoint request" id="container-id:9635ba8096353929bd42a40e5985118c240bbfd115f48c80b25a24c97e666445" subsys=daemon
2021-04-01T00:22:09.524066994Z level=warning msg="Cancelled endpoint create request due to receiving endpoint delete request" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=199 identity=62540 ipv4= ipv6= k8sPodName=/ subsys=daemon
```

[cilium-sysdump-out.zip.zip](https://github.com/cilium/cilium/files/6240270/cilium-sysdump-out.zip.zip)

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.9

**Review by christarazi — APPROVED** [review]
:+1: for my commits

**Review by pchaigno — APPROVED** [review]
:+1: for my PR.

**Review by qmonnet — APPROVED** [review]
> #15395 -- test: make RunsOnNetNextKernel() helper work with KERNEL="net-next" (@qmonnet)

Looks good to me, thanks.

**Comment by aanm** [comment]
test-backport-1.9

**Review by joestringer — APPROVED** [review]

**Review by kaworu — APPROVED** [review]

**Comment by brb** [comment]
@aanm I've created https://github.com/cilium/cilium/pull/15536 to backport #15431.

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/13011

**Comment by aanm** [comment]
test-1.17-4.9

**Comment by aanm** [comment]
As requested by Jarno, I've removed `docs: Update VM support to use the new Cilium CLI tool`. It won't be necessary to run the CI since this commit only had doc changes.

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
