### PR TITLE
vagrant: update net-next to 136

### PR DESCRIPTION
**Pull request by aanm**
This VM contains the overlayfs module required for container runtimes
that are not docker.

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Review by pchaigno — CHANGES_REQUESTED** [review]
You need to use the fixed branch name to update the images otherwise the caching system won't know it needs to update its cache.

**Review by pchaigno — CHANGES_REQUESTED** [review]
You need to use the fixed branch name to update the images otherwise the caching system won't know it needs to update its cache.

**Comment by aanm** [comment]
replaced by https://github.com/cilium/cilium/pull/19645

**Pull request closed without merging**
