### PR TITLE
cilium: Add a few bwm setting tweaks

### PR DESCRIPTION
**Pull request by borkmann**
(see commit desc)

### CODE REVIEW

**Review by aspsk — APPROVED** [review]
LGTM. One small typo: `Slighly` -> `Slightly` in commit 2 message header

**Review by qmonnet — APPROVED** [review]
Looks good, thank you.

**Review by rolinh — APPROVED** [review]
Vendor changes lgtm

**Comment by borkmann** [comment]
(rebase to latest main to bring in ci fixes, rest unchanged)

**Pull request merged**
