### PR TITLE
v1.5 backports 2019-08-12

### PR DESCRIPTION
**Pull request by ianvernon**
* #8478 -- cilium: remove old probe content before restoring assets (@borkmann) (only the first commit - see PR for more info)
 * #8764 -- daemon: get list of frontends from ServiceCache before acquiring BPFMapMu (@ianvernon)
 * #8836 -- eventqueue: use mutex to synchronize access to events channel (@ianvernon)
 * #8809 -- eventqueue: protect against enqueueing same Event twice (@ianvernon)
 * #8701 -- Make use of xtables.lock for parallel iptables usage (@aanm) **had a lot of conflicts** @aanm PTAL. I removed the need to pass the `ruleManager` interface down to the `linuxDatapath` type because the TPROXY iptables rules are not part of this PR.
 * #8793 -- Fix issue where packets would be dropped for reason "Invalid packet" (@joestringer)
  * Required also to backport a03c33a592e3c and the first commit of PR #8840

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 8478 8764 8836 8809 8701 8793 8840; do contrib/backporting/set-labels.py $pr done 1.5; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8879)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
never-tell-me-the-odds

**Review by borkmann — APPROVED** [review]

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
Hit bindata out-of-date issue, rebased.

**Comment by ianvernon** [comment]
never-tell-me-the-odds

**Comment by ianvernon** [comment]
Sigh, I can't rebase well it seems. Let's try this one more time.

**Comment by ianvernon** [comment]
never-tell-me-the-odds

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Review by nebril — APPROVED** [review]

**Review by aanm — CHANGES_REQUESTED** [review]
@ianvernon Needs this patch on top

```patch
--- a/pkg/datapath/iptables/iptables.go
+++ b/pkg/datapath/iptables/iptables.go
@@ -415,24 +415,26 @@ func (m *IptablesManager) InstallRules(ifName string) error {
                // cases. This rule here must come after all Kubernetes post-routing
                // chains, so we can match on our endpoint allocation range.
                if option.Config.EnableIPv4 {
-                       if err := runProg("iptables", []string{
+                       if err := runProg("iptables", append(
+                               m.waitArgs,
                                "-t", "nat",
                                "-A", ciliumPostNatKubeChain,
                                "-d", node.GetIPv4AllocRange().String(),
                                "-o", ifName,
-                               "-m", "comment", "--comment", "cilium: host->service(cluster ip)->local-endpoint on " + ifName + " src address fix",
-                               "-j", "SNAT", "--to-source", node.GetHostMasqueradeIPv4().String()}, false); err != nil {
+                               "-m", "comment", "--comment", "cilium: host->service(cluster ip)->local-endpoint on "+ifName+" src address fix",
+                               "-j", "SNAT", "--to-source", node.GetHostMasqueradeIPv4().String()), false); err != nil {
                                return err
                        }
                }
                if option.Config.EnableIPv6 {
-                       if err := runProg("ip6tables", []string{
+                       if err := runProg("ip6tables", append(
+                               m.waitArgs,
                                "-t", "nat",
                                "-A", ciliumPostNatKubeChain,
                                "-d", node.GetIPv6AllocRange().String(),
                                "-o", ifName,
-                               "-m", "comment", "--comment", "cilium: host->service(cluster ip)->local-endpoint on " + ifName + " src address fix",
-                               "-j", "SNAT", "--to-source", node.GetIPv6().String()}, false); err != nil {
+                               "-m", "comment", "--comment", "cilium: host->service(cluster ip)->local-endpoint on "+ifName+" src address fix",
+                               "-j", "SNAT", "--to-source", node.GetIPv6().String()), false); err != nil {
                                return err
                        }
                }
```

**Comment by ianvernon** [comment]
never-tell-me-the-odds

**Comment by ianvernon** [comment]
Box download failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2342/execution/node/35/log/

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by aanm — APPROVED** [review]

**Pull request merged**
