### PR TITLE
endpoint: fix logic to finalize proxy state in dry mode

### PR DESCRIPTION
**Pull request by ianvernon**
The logic was inverted for checking whether proxy state should be finalized
or not.

Fixes: 4045887122c11827977956abda8c7c28684538f8

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6732)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
(It'd be nice if we could unit test this somehow...)

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
> (It'd be nice if we could unit test this somehow...)

I think DryMode will go away soon with the Datapath interface

**Pull request merged**
