### PR TITLE
bpf: Add test for __ct_lookup return value

### LINKED ISSUE #9303: Improve unit tests for conntrack lookup in BPF
* [x] Merge initial framework PR #9304
* [x] Test the monitor notification behaviour with respect to new, established, closing, closed connection
  * [x] The first lookup should be monitored #9304
  * [x] Subsequent lookups within the timeout should not be monitored #9304
  * [x] After the monitor timeout has passed, a packet should be monitored #9304
  * [x] The first FIN in a direction should be monitored #9304
  * [x] Subsequent packets in the same direction do not need to be monitored #9771
  * [x] The second FIN (closing the other direction) should be monitored #9304
  * [x] Subsequent packets in the FIN direction do not need to be monitored #9304
* [x] Test the timeout behaviour of `__ct_lookup()`
  * [x] When only SYN was seen, there is the SYN timeout #9771
  * [x] When other subsequent packets were seen, there is the standard TCP lifetime timeout #9771
  * [x] Once bidirectional close (fin/rst) was seen, there is the FIN timeout #9771
* [x] When looking up a tuple that was not previously connection-tracked, the function should return CT_NEW. #10064

### PR DESCRIPTION
**Pull request by pchaigno**
Check that `__ct_lookup()` returns `CT_NEW` when given tuple wasn't previously connection-tracked.

Fixes: #9303

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10064)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by brb — APPROVED** [review]
Thanks, LGTM!

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
test-me-please

**Comment by brb** [comment]
@pchaigno Please rebase against the latest master. This will fix the conflict and will resolve the CI provisioning issue your CI build is facing.

**Comment by brb** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Comment by aanm** [comment]
@pchaigno needs rebase

**Comment by pchaigno** [comment]
test-me-please

**Pull request merged**
