### PR TITLE
vagrant: Bump net-next Vagrant box version

### PR DESCRIPTION
**Pull request by pchaigno**

### CODE REVIEW

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Review by christarazi — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Review by sayboras — APPROVED** [review]

**Comment by pchaigno** [comment]
It seems the k8s net-next tests are failing because a bunch of services stops on k8s2. Might be because of the OOM killer. I'm able to reproduce locally if I use the same seed for the test order.

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Pull request merged**
