### PR TITLE
[v1.12] ci/ipsec: Fix downgrade version for release preparation commits

### PR DESCRIPTION
**Pull request by qmonnet**
- [ ] https://github.com/cilium/cilium/pull/30413
- [ ] https://github.com/cilium/cilium/pull/30532

### CODE REVIEW

**Comment by qmonnet** [comment]
/test-backport-1.12

**Review by michi-covalent — APPROVED** [review]

**Comment by qmonnet** [comment]
/test-backport-1.12

**Review by viktor-kurchenko — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Comment by michi-covalent** [comment]
/test-1.22-4.9

**Comment by michi-covalent** [comment]
[test-1.16-4.9](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/337/): hit https://github.com/cilium/cilium/issues/27118 and https://github.com/cilium/cilium/issues/24840

**Comment by michi-covalent** [comment]
/test-1.16-4.9

**Pull request merged**
