### PR TITLE
daemon: delete double-remove of endpoint from endpointmanager

### PR DESCRIPTION
**Pull request by raybejjani**
We were removing the endpoint twice. This seems unnecessary and caused
double counting in some instances, in particular it caused the endpoint count metric to go negative. I'll fix that metric to not be sensitive to things like this but I thought it wasn't ideal to do the double remove (it should be harmless nonetheless).

I'm not sure why we added the upper `Remove` in https://github.com/cilium/cilium/commit/0948bc0b3a6fe96a6bbc5ce56515ebef54f19208 and it seems like the remove call could/should happen before all the bookkeeping we do, or after all of it (where the one I deleted is).

### CODE REVIEW

**Review by manalibhutiyani — CHANGES_REQUESTED** [review]
I think the correct thing to do is delete `endpointmanager.Remove(ep)` at line 397 and keep the one at line 414, so that we delete endpoint at the very end of all the operations/book-keeping on it. @aanm :Thoughts?

**Review by aanm — CHANGES_REQUESTED** [review]
Good catch, but I think it should be only one endpointmanager.Remove around line 357. We can remove the endpoint immediately from the list of endpoints to prevent it from being reschedule for a build or showing up in the endpoint list.

**Comment by raybejjani** [comment]
Fixed up (following aanm's suggestion). I had tested the remove before all the bookkeeping but it deadlocked. I had other changes at the time, though, and that was probably what deadlocked :/
Anyway, this seems to work.

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@raybejjani please rebase and add `ready-to-merge` if your PR is ready to be merged or, if you want, you can merge it as well

**Review by manalibhutiyani — APPROVED** [review]

**Comment by raybejjani** [comment]
I'll try to merge it once CI is done but I've tagged it anyway.

**Pull request merged**
