### PR TITLE
.github: add cilium sysdump to test artifacts

### PR DESCRIPTION
**Pull request by aanm**
With e93fdd87b963, cilium sysdumps were being collected by relying on the cilium-cli to be available on the host where the tests ran. This commit fixes the sysdump capture on conformance-ginkgo by adding cilium-cli to host where the tests are running.

Fixes: ce55298e0bbd ("test: Don't collect bugtool reports in artifacts")

### CODE REVIEW

**Comment by pchaigno** [comment]
The change in behavior is from https://github.com/cilium/cilium/commit/e93fdd87b96328847bfe31ab9343ccfef4843b93, not https://github.com/cilium/cilium/commit/ce55298e0bbd8ddd1d3ab2f1ff5487f8e2886173. https://github.com/cilium/cilium/commit/ce55298e0bbd8ddd1d3ab2f1ff5487f8e2886173 only removed bugtools and other commands, it did not introduce sysdumps in artifacts.

**Comment by pchaigno** [comment]
And I believe this fixes your commit, not mine. The GH ginkgo pipelines didn't exist when I wrote https://github.com/cilium/cilium/commit/e93fdd87b96328847bfe31ab9343ccfef4843b93.

**Comment by aanm** [comment]
The commit https://github.com/cilium/cilium/commit/ce55298e0bbd8ddd1d3ab2f1ff5487f8e2886173 was merged after https://github.com/cilium/cilium/pull/25713

**Comment by pchaigno** [comment]
Yeah, but https://github.com/cilium/cilium/commit/ce55298e0bbd8ddd1d3ab2f1ff5487f8e2886173 didn't change anything for the sysdumps :wink:

**Review by sayboras — APPROVED** [review]
🚢

**Review by viktor-kurchenko — APPROVED** [review]
LGTM.

**Pull request merged**
