### PR TITLE
Support customizing the timeout for listing k8s resources in a large scale cluster

### LINKED ISSUE #34198: CFP:  Support customizing k8s List timeout to accommodate ultra-large scale clusters.
### Problem in large scale cluster
In my k8s cluster running version 1.26.8, there are 200K Pod resources and 160K ciliumendpoints. After restarting a large number of cilium instances, I encountered an issue where cilium failed to start successfully. Upon checking the kube-apiserver logs, I found the following entries:
```
I0806 07:59:44.410877       1 panic.go:884] "HTTP" verb="LIST" URI="/apis/cilium.io/v2/ciliumendpoints?limit=500&resourceVersion=0" latency="1m0.000097438s" userAgent="cilium-agent/1.15.6 72c3b0c414 2024-08-06T15:40:57+08:00 go version go1.21.12 linux/amd64" audit-ID="75a26477-357c-4984-9cf2-80e754f8f84d" srcIP="10.27.130.198:36022" apf_pl="network-low" apf_fs="network-lister" apf_iseats=10 apf_fseats=0 apf_additionalLatency="0s" resp=200
I0806 07:59:45.953911       1 panic.go:884] "HTTP" verb="LIST" URI="/apis/cilium.io/v2/ciliumendpoints?limit=500&resourceVersion=0" latency="1m0.00005637s" userAgent="cilium-agent/1.15.6 72c3b0c414 2024-08-06T15:40:57+08:00 go version go1.21.12 linux/amd64" audit-ID="803a5927-5893-4ddc-af2d-21bf67cabc3d" srcIP="10.27.134.216:57080" apf_pl="network-low" apf_fs="network-lister" apf_iseats=10 apf_fseats=0 apf_additionalLatency="0s" resp=200
I0806 07:59:46.687622       1 panic.go:884] "HTTP" verb="LIST" URI="/apis/cilium.io/v2/ciliumendpoints?limit=500&resourceVersion=0" latency="1m0.000088741s" userAgent="cilium-agent/1.15.6 72c3b0c414 2024-08-06T15:40:57+08:00 go version go1.21.12 linux/amd64" audit-ID="17f01e1d-747a-4ca0-adac-cd3a9990782c" srcIP="10.27.148.18:59360" apf_pl="network-low" apf_fs="network-lister" apf_iseats=10 apf_fseats=0 apf_additionalLatency="0s" resp=200
I0806 07:59:47.312765       1 panic.go:884] "HTTP" verb="LIST" URI="/apis/cilium.io/v2/ciliumendpoints?limit=500&resourceVersion=0" latency="1m0.000091336s" userAgent="cilium-agent/1.15.6 72c3b0c414 2024-08-06T15:40:57+08:00 go version go1.21.12 linux/amd64" audit-ID="bc8ead83-1a88-4ced-be45-2420f469e35b" srcIP="10.27.145.169:29058" apf_pl="network-low" apf_fs="network-lister" apf_iseats=10 apf_fseats=0 apf_additionalLatency="0s" resp=200
I0806 07:59:47.653120       1 httplog.go:131] "HTTP" verb="LIST" URI="/apis/cilium.io/v2/ciliumendpoints?limit=500&resourceVersion=0" latency="59.602034819s" userAgent="cilium-agent/1.15.6 72c3b0c414 2024-08-06T15:40:57+08:00 go version go1.21.12 linux/amd64" audit-ID="a4dcacee-afe6-46f0-be0f-7e6eb583680f" srcIP="10.27.133.141:54896" apf_pl="network-low" apf_fs="network-lister" apf_iseats=10 apf_fseats=0 apf_additionalLatency="0s" apf_execution_time="59.60174364s" resp=200
```

I think that the number of ciliumendpoints resources, which is 160,000, is too large, making it impossible for the apiserver’s watch cache to respond to list requests within 60 seconds. As the cluster size increases, cilium becomes almost unusable on clusters of this scale.

### **Describe the feature you'd like**
cilium-agent add a new flag `k8s-list-timeout-seconds` to define the maximum duration to wait before giving up on a list operation.
default value of `k8s-list-timeout-seconds` is 0, it means not to customize the timeout, which is consistent with the old cilium behavior, using the kube-apiserver’s default timeout of 60 seconds.
When the timeout value is set to 300 seconds, it implies that cilium will wait for a maximum of 5 minutes before giving up on a list request that hasn’t received a response.

### PR DESCRIPTION
**Pull request by weiwei02**
Support customizing the timeout for listing k8s resources in a large cluster through `k8s-list-timeout-seconds`

Fixes:  #34198

In kube-apiserver, the default timeout for listing is 60 seconds. However, in large clusters with hundreds of thousands ofresources(like ciliumendpoints), the listing time increases with the growth of resource quantity, making the default 60-second timeout inadequate. This commit optimizes the issue where cilium fails to list resources due to excessive resource counts during list requests.

### CODE REVIEW

**Comment by marseel** [comment]
Thanks for the PR @weiwei02 

Just to clarify, have you tried that / tested it? 
If I remember correctly, kube-apiserver enforces a 1 minute timeout for all non long running requests. From code https://github.com/kubernetes/kubernetes/blob/60c4c2b2521fb454ce69dee737e3eb91a25e0535/staging/src/k8s.io/apiserver/pkg/server/config.go#L215:
```
	// If specified, all requests except those which match the LongRunningFunc predicate will timeout
	// after this duration.
	RequestTimeout time.Duration
```
`LongRunningFunc` refers to proxy/logs/watch requests, but not to list requests.
 
Also default is `--request-timeout duration     Default: 1m0s`

I'm pretty sure that just increasing timeout here won't make it work and k8s apiserver will still kill requests after 1 minute.

**Comment by marseel** [comment]
Alternatively, Increasing `--request-timeout` on apiserver should work.
You could also explore CES: https://docs.cilium.io/en/latest/network/kubernetes/ciliumendpointslice/
CES have a significantly smaller footprint and k8s apiserver latency mostly comes from gzip compression.

**Review by marseel — CHANGES_REQUESTED** [review]
@weiwei02 do you have an update on this PR?

**Comment by weiwei02** [comment]
> https://github.com/kubernetes/kubernetes/blob/60c4c2b2521fb454ce69dee737e3eb91a25e0535/staging/src/k8s.io/apiserver/pkg/server/config.go#L215

@marseel  You are absolutely right. The --request-timeout duration flag, with a default value of 1 minute, is used to set the default timeout for the API server when no user-specified timeout is provided.

If the client specifies a timeout, it will only take effect if it is less than the --request-timeout set for the kube-apiserver.

Thank you for your review. I will abandon this pull request.
as see:
```
                userSpecifiedTimeout, ok, err := parseTimeout(req)
		...

		timeout := requestTimeoutMaximum
		if ok {
			// we use the default timeout enforced by the apiserver:
			// - if the user has specified a timeout of 0s, this implies no timeout on the user's part.
			// - if the user has specified a timeout that exceeds the maximum deadline allowed by the apiserver.
			if userSpecifiedTimeout > 0 && userSpecifiedTimeout < requestTimeoutMaximum {
				timeout = userSpecifiedTimeout
			}
		}
```
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/filters/request_deadline.go#L49

**Pull request closed without merging**
