### PR TITLE
v1.7 backports 2020-02-13

### PR DESCRIPTION
**Pull request by jrajahalme**
* #10106 -- tests: update complexity check script to include new calls (@fristonio)
 * #10156 -- test: bpf: Fix load for cgroups progs (@joestringer)
 * #10162 -- docs: Use kube-system namespace consistently in Encryption guide (@pchaigno)
 * #10159 -- docs: Update kube-router getting started guide (@brb)
 * #10140 -- pkg/endpoint: access endpoint state safely across go routines (@aanm)
 * #10137 -- pkg/eventqueue: fix concurrent access of waitConsumeOffQueue (@aanm)
 * #10166 -- api: Add missing annotations to generate DeepCopy for new status fields (@tgraf)
 * #10150 -- docs: Minor improvements to GKE guide (@pchaigno)
 * #10164 -- datapath: Filter out bpftool probes emitting dmesg messages (@mrostecki)
 * #10171 -- charts: Generate versions from VERSION file (@joestringer)
 * #10173 -- bpf: Fix space hack in Makefile (@brb)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10106 10156 10162 10159 10140 10137 10166 10150 10164 10171 10173; do contrib/backporting/set-labels.py $pr done 1.7; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10183)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by jrajahalme** [comment]
k8s builds produced no output, trying again

**Comment by jrajahalme** [comment]
test-missed-k8s

**Review by joestringer — APPROVED** [review]

**Pull request merged**
