### PR TITLE
bpf: add tail_call_{static,dynamic} helpers

### PR DESCRIPTION
**Pull request by borkmann**
See commit msg.

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
retest-4.19

**Comment by borkmann** [comment]
retest-4.9

**Comment by borkmann** [comment]
retest-runtime

**Comment by borkmann** [comment]
Travis CI twice in a row blocked by Github:
```
$ ./.travis/prepare.sh
https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz:
2020-05-12 09:08:55 ERROR 429: too many requests. [...]
```

**Review by brb — APPROVED** [review]

**Comment by borkmann** [comment]
retest-4.9

**Comment by borkmann** [comment]
retest-runtime

**Comment by borkmann** [comment]
K8s-1.11-Kernel-netnext + K8s-1.17-Kernel-4.19 green.

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
runtime-4.9 currently broken in master (https://jenkins.cilium.io/job/Ginkgo-CI-Tests-runtime-Pipeline/), same (unrelated) issue.

**Comment by borkmann** [comment]
retest-runtime

**Comment by borkmann** [comment]
retest-4.19

**Pull request merged**
