### PR TITLE
metrics: fix missing k8s rest client metrics

### PR DESCRIPTION
**Pull request by ysksuzuki**
K8s rest client metrics, `cilium_k8s_client_api_latency_time_seconds` and `cilium_k8s_client_api_calls_total`, are missing because of a conflict with controller-runtime on the metrics registration. 
(This issue of missing metrics occurs only in 1.13. See https://github.com/cilium/cilium/pull/25555#issuecomment-1601069680)

controller-runtime(sigs.k8s.io/controller-runtime/pkg/metrics) also registers the client-go rest client metrics on its registry using metrics.Register method in its init function. The metrics.Register can be called only once, and subsequent calls will be ignored.

cilium-agent doesn't use controller-runtime, but there's an indirect dependency from github.com/cilium/cilium/daemon to github.com/cilium/cilium/operator/metrics package. (operator uses controller-runtime in its Gateway API implementation) For example,
github.com/cilium/cilium/daemon/cmd
-> github.com/cilium/cilium/pkg/ipam
-> github.com/cilium/cilium/pkg/ipam/metrics
-> github.com/cilium/cilium/operator/metrics

The init function of sigs.k8s.io/controller-runtime/pkg/metrics will be called because of this indirect dependency.

This commit fixes this conflict by registering the metrics directly as well as calling metrics.Register.

Fixes: #25610

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

### CODE REVIEW

**Comment by ti-mo** [comment]
Thanks! Since we have no codeowners on release branches, I'll tag some reviewers manually.

Adding @aanm as the original author and @dylandreimerink for recent context around metrics. Please correct as necessary.

**Review by dylandreimerink — APPROVED** [review]
Given that this is a v1.13 backport it doesn't conflict with the recent metrics changes on main. LGTM!

**Review by aanm — APPROVED** [review]
Thank you for the PR. @ysksuzuki I understand that this issue doesn't happen in main, but it can happen if the order of imports changes again. Maybe would be worth forward port this change to the main branch?

**Comment by aanm** [comment]
/test-backport-1.13

**Comment by ysksuzuki** [comment]
>  it can happen if the order of imports changes again. Maybe would be worth forward port this change to the main branch?

Right. I will raise a PR to forward port it.

I want to clean up the dependency from ipam to operator package in https://github.com/cilium/cilium/issues/26122. There's no way to override the workqueue metrics if controller-runtime wins.

**Comment by ysksuzuki** [comment]
/test-1.22-4.19

**Comment by ysksuzuki** [comment]
/test-1.24-4.19

**Review by squeed — APPROVED** [review]

**Comment by squeed** [comment]
CI green except for, inexplicably, waiting for some `main`-branch tests. Merging

**Pull request merged**
