### PR TITLE
cli: aws mixed nodes install fix

### LINKED ISSUE #36320: Encounter cluster has nodes with different OS images issue when using 1.17.0-pre.3
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

environment: 1.17.0-pre.3
cilium-cli: built locally with 1.17.0-pre.3 source

When trying out new 1.17.0-pre.3, I noticed that the old cli is not compatible with new cilium version, so a new cli is built and used. In our EKS cluster, we do have two different OSes: 
* AL2 which is used in fargate node hosting Karpenter
* Bottlerocket is configured on nodes provisioned by Karpenter 

we do have nodeSelector in cilium values file for cilium agents/ operators/ envoys workloads. And in earlier version, our approach works well. This behavior breaks in 1.17.0-pre.3 (not in .2) with below error
```
cilium upgrade cilium cilium/cilium --namespace kube-system --version "$cilium_version" --values cilium-values.yaml       --set cluster.id=1       --set "cluster.name=${cluster_name}"       --set "eni.iamRole=${cilium_role_arn}"       --set "serviceAccounts.operator.annotations.eks\.amazonaws\.com/role-arn=${cilium_role_arn}" --set "k8sServiceHost=${cluster_api_endpoint}"
🔮 Auto-detected Kubernetes kind: EKS
ℹ️  Using Cilium version 1.17.0-pre.3
ℹ️  Using cluster name "truong-test-cluster"
🔮 Auto-detected kube-proxy has been installed
❌ Could not detect AWS node image family, defaulted to fallback value: Custom

Error: Unable to upgrade Cilium: cluster has nodes with different OS images: 'AmazonLinux2' and 'Bottlerocket'
```

 I guess it might be related to [this feature](https://github.com/cilium/cilium/pull/36076/files#diff-0b6dc304261e14febe58bbc9f05a9358eb47cfb9e85673ab0c7aec413dfd6ed7).

### How can we reproduce the issue?

environment: 1.17.0-pre.3
cilium-cli: built locally with 1.17.0-pre.3 source

When trying out new 1.17.0-pre.3, I noticed that the old cli is not compatible with new cilium version, so a new cli is built and used. In our EKS cluster, we do have two different OSes: 
* AL2 which is used in fargate node hosting Karpenter
* Bottlerocket is configured on nodes provisioned by Karpenter 

we do have nodeSelector in cilium values file for cilium agents/ operators/ envoys workloads. And in earlier version, our approach works well. This behavior breaks in 1.17.0-pre.3 (not in .2) with below error
```
cilium upgrade cilium cilium/cilium --namespace kube-system --version "$cilium_version" --values cilium-values.yaml       --set cluster.id=1       --set "cluster.name=${cluster_name}"       --set "eni.iamRole=${cilium_role_arn}"       --set "serviceAccounts.operator.annotations.eks\.amazonaws\.com/role-arn=${cilium_role_arn}" --set "k8sServiceHost=${cluster_api_endpoint}"
🔮 Auto-detected Kubernetes kind: EKS
ℹ️  Using Cilium version 1.17.0-pre.3
ℹ️  Using cluster name "truong-test-cluster"
🔮 Auto-detected kube-proxy has been installed
❌ Could not detect AWS node image family, defaulted to fallback value: Custom

Error: Unable to upgrade Cilium: cluster has nodes with different OS images: 'AmazonLinux2' and 'Bottlerocket'
```

 I guess it might be related to [this feature](https://github.com/cilium/cilium/pull/36076/files#diff-0b6dc304261e14febe58bbc9f05a9358eb47cfb9e85673ab0c7aec413dfd6ed7).

### Cilium Version

1.17.0-pre.3

### Kernel Version

NA

### Kubernetes Version

1.31

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by viktor-kurchenko**
The PR fixes AWS installation for mixed node clusters by logging warning instead of breaking it with error.

Fixes: https://github.com/cilium/cilium/issues/36320

### CODE REVIEW

**Review by tommyp1ckles — APPROVED** [review]

**Review by squeed — CHANGES_REQUESTED** [review]
I think we can get rid of this detection entirely. We use it do determine the prefix of the masquerade interfaces, but multiple prefixes are allowed. If we just set `egressMasqueradeInterfaces=eth+,ens+` we can cull this entire code path.

**Comment by viktor-kurchenko** [comment]
> I think we can get rid of this detection entirely. We use it do determine the prefix of the masquerade interfaces, but multiple prefixes are allowed. If we just set `egressMasqueradeInterfaces=eth+,ens+` we can cull this entire code path.

To be honest I really like that idea!
@nbusseneau WDYT?

**Comment by nbusseneau** [comment]
> I think we can get rid of this detection entirely. We use it do determine the prefix of the masquerade interfaces, but multiple prefixes are allowed. If we just set `egressMasqueradeInterfaces=eth+,ens+` we can cull this entire code path.

Are we sure this is working? I had tried it but it didn't seem to work 🤔

**Comment by viktor-kurchenko** [comment]
> Are we sure this is working? I had tried it but it didn't seem to work 🤔

It's working after this fix: https://github.com/cilium/cilium/pull/36103 )))

**Review by squeed — APPROVED** [review]
Nice and clean :)

**Comment by viktor-kurchenko** [comment]
> Nice and clean :)

Thank you!

**Review by nbusseneau — APPROVED** [review]

**Pull request merged**
