### PR TITLE
v1.3 backports 2019-02-10, part 1

### PR DESCRIPTION
**Pull request by borkmann**
PRs:
- #6992 
- #6978 
- #6953 

Both #6970 and #6809 require custom implementations due to complex conflicts, proposal will come in part 2.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7014)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9773/flowGraphTable/

All test suites timed out (indicating either a regression, or some possible load / environment issue on the baremetal machines on which the CI runs).

Per the "Allocate Node" step, the build ran on "jenkins-fixed-5": https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1647/execution/node/3/log/

**Comment by ianvernon** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Pull request merged**
