### PR TITLE
Handle fragmented packet in snat

### PR DESCRIPTION
**Pull request by anfernee**
When processing snat, the current logic assumes the packet always has L4
headers, which is not true for fragmented packets. When looking up
conntrack map, it is searching with the wrong port number. This will
cause the returning fragmented packets from service get dropped due to
the failed conntrack lookup.

BUG: #11180

### CODE REVIEW

**Review by brb — CHANGES_REQUESTED** [review]
Thanks for the PR.

- For which packet flow are you fixing SNAT?
- Have you checked whether `snat_v4_rewrite_{ingress,egress}` invocations below won't rewrite the non-first frag packet non-existing ports?
- This code is changing the core datapath logic. We definitely need the integration tests for it.

**Comment by anfernee** [comment]
> Thanks for the PR.
> 
> * For which packet flow are you fixing SNAT?

It fixed the non-first fragmented return packet. In this method, `snat_v4_handle_mapping(ctx, tuple, ...)`  the tuple contains the wrong port numbers, so it skip the rewrite. 

> * Have you checked whether `snat_v4_rewrite_{ingress,egress}` invocations below won't rewrite the non-first frag packet non-existing ports?

non-existing ports will fail the snat lookup like previously mentioned. It should skip this step. 

> * This code is changing the core datapath logic. We definitely need the integration tests for it.

Agreed. The test should reproduce the issue. This probably involves the third machine to test. Now I am not very sure how to do it..

**Comment by brb** [comment]
> non-existing ports will fail the snat lookup like previously mentioned. It should skip this step.

Let's say that a reply to a NodePort BPF (in SNAT mode) request got fragmented. The intermediate node which is forwarding requests to the destination node, which runs the service backend, does SNAT for requests and rev-SNAT for replies.

The first packet of the fragmented reply will create an entry in the BPF IPv4 frag map, and it will be properly rev-SNAT-ed. Next, the second packet of the same reply will do the lookup in the frag map and the tuple ports will be set accordingly. Afterwards, the tuple will successfully find the related SNAT entry, and finally `snat_v4_rewrite_ingress()` will be called.

The latter function is not aware of the fragmentation. For the second packet it will detect L4 protocol (from the `nexthdr` field), and will try to modify the non-existing ports which should cause the packet corruption.

Do I miss something? If not, then we should make `snat_v4_rewrite_{ingress,egress}()` fragmentation aware.

> Agreed. The test should reproduce the issue. This probably involves the third machine to test. Now I am not very sure how to do it..

You could re-use the existing infrastructure: https://github.com/cilium/cilium/blob/master/test/k8sT/Services.go#L902. Probably you could create an UDP echo service (just check, maybe there is already one), and then send larger than MTU request "from outside" (the k8s3 node which does not run cilium).

Another thing to test is that BPF masq is not broken. For this, you would need to create the same echo UDP pod on k8s3 running in the host netns (so no CNI is needed) and send a large request from a pod managed by Cilium to that UDP pod.

**Comment by anfernee** [comment]
@brb  Sorry for missing this thread for so long. What you said made perfect sense. `snat_v4_rewrite_ingress` should be fixed to make it fragment-aware. I am also going to add e2e test for this patch, probably over this weekend.

**Comment by anfernee** [comment]
> You could re-use the existing infrastructure: https://github.com/cilium/cilium/blob/master/test/k8sT/Services.go#L902. Probably you could create an UDP echo service (just check, maybe there is already one), and then send larger than MTU request "from outside" (the k8s3 node which does not run cilium).

This is exactly what I did manually to test it. I didn't check the reply echo, and probably missed the corruption. Will cover it in the test.
> 
> Another thing to test is that BPF masq is not broken. For this, you would need to create the same echo UDP pod on k8s3 running in the host netns (so no CNI is needed) and send a large request from a pod managed by Cilium to that UDP pod.
Noted..

**Comment by brb** [comment]
Converting this to draft, as the PR is still WIP.

**Comment by brb** [comment]
@anfernee Are you still working on this?

**Comment by anfernee** [comment]
yeah, I'll see how much progress I could make this week.

**Comment by anfernee** [comment]
Working on the e2e test first. I think I need a couple of more days.

**Comment by anfernee** [comment]
Added some e2e tests: https://github.com/cilium/cilium/pull/16616 and https://github.com/cilium/echoserver-udp/pull/1

**Pull request closed without merging**
