### PR TITLE
v1.12 backports 2023-02-23

### PR DESCRIPTION
**Pull request by sayboras**
- [x] #22072 -- workflows: Bump timeout of ConformanceKind workflow (@pchaigno)
 - [x] #23787 -- agent: fix incorrect deletion of veth host interfaces on bootstrap (@giorio94)
 - [x] #23857 -- Fix connectivity issue upon agent restart in case of ipv6 + direct routing + KPR replacement (@giorio94)
 - [x] #23800 -- envoy: Bump envoy to 1.23.4 (@sayboras)
 - [x] #23904 -- fix(deps): update module golang.org/x/net to v0.7.0 [security] (master) (@renovate[bot])
 - [ ] #23836 -- endpoint, proxy: Fix deadlock with ipcache and K8s watcher (@christarazi). _Updated: As Chris is on leave, I have double checked this patch :heavy_check_mark:_

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 22072 23787 23857 23800 23904 23836; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.12

**Review by giorio94 — APPROVED** [review]
My commits look good. Thanks!

**Review by tklauser — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by aanm — APPROVED** [review]

**Comment by sayboras** [comment]
Reviews are in, CI are all good. Merging this in.

**Pull request merged**
