### PR TITLE
cilium, ipvlan: loop back icmp6 requests to router on slave device

### PR DESCRIPTION
**Pull request by borkmann**
Allow container/pods to reach router v6 in case of ipvlan.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6882)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
`Timeout has been exceeded`

**Comment by borkmann** [comment]
test-me-please

**Pull request merged**
