### PR TITLE
v1.14 Backports 2024-02-08

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #30154 (@ldelossa)
 * [x] #30536 (@hemanthmalla)
 * [x] #30525 (@tklauser)
 * [x] #30520 (@julianwiedmann)
 * [x] #30496 (@giorio94)
 * [x] #30378 (@brlbil)
 * [ ] #30543 (@chaunceyjiang)
 * [x] #30321 (@giorio94)
 * [ ] #30612 (@gailsuccess)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30154 30536 30525 30520 30496 30378 30543 30321 30612
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.14

**Comment by nbusseneau** [comment]
/test-backport-1.14

**Comment by nbusseneau** [comment]
The expected `Conformance Gateway API` check is missing because it has been renamed in this PR to `Conformance Gateway API (ci-gateway-api)`.

All testing has passed, awaiting for reviews now.

**Comment by nbusseneau** [comment]
This should be ready to merge as soon as reviews are in.

**Review by hemanthmalla — APPROVED** [review]

**Review by brlbil — APPROVED** [review]
Thanks, looks good.

**Review by julianwiedmann — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
LGTM for https://github.com/cilium/cilium/pull/30525

**Pull request merged**
