### PR TITLE
test/helpers: use ExpectWithOffset in helper functions

### PR DESCRIPTION
**Pull request by ianvernon**
This makes it easier to see where the failure occurred in relation to where said
function is called within a test as opposed to within the helper function itself.

Signed-off by: Ian Vernon <ian@cilium.io>

Fixes: #3658

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
LGTM

**Comment by eloycoto** [comment]
Hi!

I'm not sure if this is a good approach, let me explain why I'm saying this: 

You have this function: 
```
func GetAppPods(apps []string, namespace string, kubectl *Kubectl, appFmt string) map[string]string {
	appPods := make(map[string]string)
	for _, v := range apps {
		res, err := kubectl.GetPodNames(namespace, fmt.Sprintf("%s=%s", appFmt, v))
		ExpectWithOffset(1, err).Should(BeNil())
		ExpectWithOffset(1, res).Should(Not(BeNil()))
		appPods[v] = res[0]
		log.Infof("GetAppPods: pod=%q assigned to %q", res[0], v)
	}
	return appPods
}
```

That is called multiple times from Kubernetes test, with this ExpectWithOffset,
the line of the problem will be inside Kubernetes test, and you don't know in
what assertion fail, so you know that fails, but you don't know where, because
there are two assertions in there. 

In this example, it's kinda ok, but in `InstallExampleCilium` is harder, and I
think that in these cases we should assert in the exact line of the failure, if
not will be super difficult to know where it fails. 

As proposal, I think that the good practice should be using `ExpectWithOffset`
when we only have one assertion in the helper, and use the normal `Expect` when
we have more than one. 

Ideally Ginkgo should have a stacktrace, that would be great, but in this case
is a bit mess. :-(

PS: After writing this, I've started to work on issue https://github.com/cilium/cilium/issues/3657, If the ExpectWithOffset was used, I can not know where is the error mainly :\

**Comment by ianvernon** [comment]
@eloycoto the reason I added this change was because it was hard for me to figure out where in the test that these functions ran, where the failure occurred. What if we add more `By` messages within the helper functions to allow narration of what's going on? This allows the user to see how the helper function progressed via the console output, and shows in which test the function itself failed. I believe this fulfills your requirements. In the end though, this is a difference of opinion, so as the CI owner, I will defer to you on this. Feel free to close if you so desire.

**Comment by eloycoto** [comment]
I'm not sure that `By` will help, if the helper gets called two times you will have two `By` messages and things are going to be much verbose and harder to debug and still don't know where the test fails. IMHO. 

Now that we have BeforeAll, `By` for me does not help at all, at the moment, I think that we should split a lot of test to make it smaller so is the right way to go IMHO.

**Comment by ianvernon** [comment]
> if the helper gets called two times you will have two By messages and things are going to be much verbose

If something gets called twice, it isn't much more verbose; it will add two extra lines of narration of what the tests are doing, which I think has high utility. 

> Now that we have BeforeAll, By for me does not help at all

Why ? I don't understand how `BeforeAll` is part of the picture here. Please explain.

> at the moment, I think that we should split a lot of test to make it smaller so is the right way to go IMHO.

Do you mean like each `Expect` being defined in its own helper function? This seems a bit excessive to me. 

Overall, I think adding `By` and getting more console output isn't overly verbose. Again, as the owner of the CI, feel free to close if you desire, because I will defer to you on what you want to implement as best-practices for it.

**Comment by ianvernon** [comment]
@eloycoto please let me know what you think about my above comments.

**Comment by eloycoto** [comment]
@ianvernon TBH, I prefer to close this one. I'm not confident with this one :\

**Pull request closed without merging**
