### PR TITLE
api/hubble: Explicitly mark unused fields as reserved

### PR DESCRIPTION
**Pull request by gandro**
All of these fields were used in older versions of the Hubble API. To
avoid accidental re-use, this commit explicitly mark these fields as
reserved.

### CODE REVIEW

**Review by rolinh — APPROVED** [review]
:100:

**Review by michi-covalent — APPROVED** [review]
🚀

**Review by glibsm — APPROVED** [review]
very cool. TIL.

**Review by ti-mo — APPROVED** [review]
Not sure about why these are unused, but the change looks sound. :+1:

**Comment by aanm** [comment]
test-me-please

**Review by kaworu — APPROVED** [review]

**Comment by gandro** [comment]
Rebased on master to avoid issues in CI due to the container registry rate limitting.

**Comment by gandro** [comment]
test-me-please

**Pull request merged**
