### PR TITLE
v1.1 backports 2018-09-17

### PR DESCRIPTION
**Pull request by borkmann**
PRs backported:

- #5369 
- #5300 
- #4958 
- #4757

Not backported:

- #5291 (waiting on backport clarification as per comment in the PR)

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5572)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Previous Jenkins error was ...
```
09:59:19  [K8s-1.11]     k8s1-1.11: I0917 09:59:17.545821    3516 feature_gate.go:230] feature gates: &{map[]}
09:59:19  [K8s-1.11]     k8s1-1.11: nodeRegistration.criSocket: Invalid value: "unix:///var/run/docker.sock": path is not absolute
09:59:19  [K8s-1.11] The SSH command responded with a non-zero exit status. Vagrant
09:59:19  [K8s-1.11] assumes that this means the command failed. The output for this command
09:59:19  [K8s-1.11] should be in the log above. Please read the output to determine what
09:59:19  [K8s-1.11] went wrong.
09:59:19  [K8s-1.11] 
09:59:19  [K8s-1.11]         ===================== ERROR - VM PROVISION FAILED =====================
09:59:19  [K8s-1.11] 
09:59:19  [K8s-1.11]         Unable to provision and start VM "k8s1-1.11": exit status 1", vm, err
09:59:19  [K8s-1.11] 
09:59:19  [K8s-1.11]         =======================================================================
```
... so I pulled in 0c4e2a7b9e9417accea6e9955778e0a0b1c7a860 as a dependency.

**Comment by borkmann** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure was due to issues connecting to `quay.io` to get images:
```
k8s1-1.7: Get https://quay.io/v2/: dial tcp: lookup quay.io on 8.8.4.4:53: dial udp 8.8.4.4:53: connect: network is unreachable
    k8s1-1.7: Makefile:132: recipe for target 'docker-image' failed
```

Re-trying.

**Comment by ianvernon** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Hit #5204. Kafka pod in `CrashLoopBackoff ` due to not being able to resolve `zook` hostname.

From logs:
```
2018-09-17T20:41:24.712440746Z [2018-09-17 20:41:24,710] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
2018-09-17T20:41:24.712458681Z java.net.UnknownHostException: zook: Name does not resolve
2018-09-17T20:41:24.71246095Z 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
2018-09-17T20:41:24.712462862Z 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
2018-09-17T20:41:24.712464612Z 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
2018-09-17T20:41:24.712466431Z 	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
2018-09-17T20:41:24.712468149Z 	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
2018-09-17T20:41:24.712477892Z 	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
2018-09-17T20:41:24.712479844Z 	at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61)
2018-09-17T20:41:24.71248356Z 	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445)
2018-09-17T20:41:24.712485365Z 	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:380)
2018-09-17T20:41:24.712487095Z 	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:86)
2018-09-17T20:41:24.712488906Z 	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1539)
2018-09-17T20:41:24.712490619Z 	at kafka.server.KafkaServer.createZkClient$1(KafkaServer.scala:345)
2018-09-17T20:41:24.712492319Z 	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:369)
2018-09-17T20:41:24.712494006Z 	at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
2018-09-17T20:41:24.712495683Z 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
2018-09-17T20:41:24.712497387Z 	at kafka.Kafka$.main(Kafka.scala:92)
2018-09-17T20:41:24.712499001Z 	at kafka.Kafka.main(Kafka.scala)
2018-09-17T20:41:24.713061297Z [2018-09-17 20:41:24,712] INFO shutting down (kafka.server.KafkaServer)
2018-09-17T20:41:24.714574785Z [2018-09-17 20:41:24,714] WARN  (kafka.utils.CoreUtils$)
2018-09-17T20:41:24.714584395Z java.lang.NullPointerException
2018-09-17T20:41:24.714586622Z 	at kafka.server.KafkaServer.$anonfun$shutdown$6(KafkaServer.scala:569)
2018-09-17T20:41:24.714588638Z 	at kafka.utils.CoreUtils$.swallow(CoreUtils.scala:85)
2018-09-17T20:41:24.714590414Z 	at kafka.server.KafkaServer.shutdown(KafkaServer.scala:569)
2018-09-17T20:41:24.714592115Z 	at kafka.server.KafkaServer.startup(KafkaServer.scala:326)
2018-09-17T20:41:24.714593794Z 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
2018-09-17T20:41:24.714595561Z 	at kafka.Kafka$.main(Kafka.scala:92)
2018-09-17T20:41:24.71459729Z 	at kafka.Kafka.main(Kafka.scala)
2018-09-17T20:41:24.721900733Z [2018-09-17 20:41:24,721] INFO shut down completed (kafka.server.KafkaServer)
2018-09-17T20:41:24.722411181Z [2018-09-17 20:41:24,722] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
2018-09-17T20:41:24.723683974Z [2018-09-17 20:41:24,723] INFO shutting down (kafka.server.KafkaServer)

```

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
This run hit:

```
[...]
21:51:33  [Runtime]     runtime: Analyzing: target //:envoy (256 packages loaded)
21:51:33  [K8s-1.11]     k8s1-1.11: [preflight] Some fatal errors occurred:
21:51:33  [K8s-1.11]     k8s1-1.11: 	[ERROR ImagePull]: failed to pull image [k8s.gcr.io/coredns:1.1.3]: exit status 1
21:51:33  [K8s-1.11]     k8s1-1.11: [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
21:51:33  [K8s-1.11] The SSH command responded with a non-zero exit status. Vagrant
21:51:33  [K8s-1.11] assumes that this means the command failed. The output for this command
21:51:33  [K8s-1.11] should be in the log above. Please read the output to determine what
21:51:33  [K8s-1.11] went wrong.
21:51:33  [K8s-1.11] 
21:51:33  [K8s-1.11]         ===================== ERROR - VM PROVISION FAILED =====================
21:51:33  [K8s-1.11] 
21:51:33  [K8s-1.11]         Unable to provision and start VM "k8s1-1.11": exit status 1", vm, err
21:51:33  [K8s-1.11] 
21:51:33  [K8s-1.11]         =======================================================================
```

**Comment by borkmann** [comment]
test-me-please

**Comment by joestringer** [comment]
Seems like nothing specific failed, the k8s 1.11 tests just took too long and timed out:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/6542/execution/node/75/log/

**Comment by joestringer** [comment]
test-me-please

**Pull request merged**
