### PR TITLE
v1.10 backports 2022-04-26

### PR DESCRIPTION
**Pull request by jrajahalme**
* #19501 -- daemon: Dump ipcache without probing for support (@jrajahalme)
 * #19556 -- identity: Initialize local identity allocator early (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 19501 19556; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.10

**Comment by aanm** [comment]
/ci-gke-1.10

**Comment by aanm** [comment]
/ci-gke-1.10

**Comment by jrajahalme** [comment]
Cannot parse JSON error on test-1.19-5.4, restarting

**Comment by jrajahalme** [comment]
/test-1.19-5.4

**Comment by jrajahalme** [comment]
/test-1.20-4.19

**Comment by jrajahalme** [comment]
Runtime test fail is due to this backport not working correctly, I'll have to investigate it, flipping this to draft in the meanwhile.

**Comment by jrajahalme** [comment]
Had to apply this for the v1.10 backport:
```
diff --git a/daemon/cmd/policy.go b/daemon/cmd/policy.go
index b9f1cbe2d1..cff454b087 100644
--- a/daemon/cmd/policy.go
+++ b/daemon/cmd/policy.go
@@ -81,6 +81,11 @@ func (d *Daemon) policyUpdateTrigger(reasons []string) {
 // in agent configuration, changes in endpoint labels, and change of security
 // identities.
 func (d *Daemon) TriggerPolicyUpdates(force bool, reason string) {
+	// CIDR identity restoration may trigger early when endpoints can not yet be regenerated
+	if d.policyTrigger == nil {
+		return
+	}
+
 	if force {
 		log.Debugf("Artificially increasing policy revision to enforce policy recalculation")
 		d.policy.BumpRevision()
```

**Comment by jrajahalme** [comment]
/test-backport-1.10

**Comment by jrajahalme** [comment]
/test-1.19-4.9

**Comment by jrajahalme** [comment]
/test-1.16-netnext

**Comment by joestringer** [comment]
> Had to apply this for the v1.10 backport:
> 
> ```
>diff --git a/daemon/cmd/policy.go b/daemon/cmd/policy.go
>index b9f1cbe2d1..cff454b087 100644
>--- a/daemon/cmd/policy.go
>+++ b/daemon/cmd/policy.go
>@@ -81,6 +81,11 @@ func (d *Daemon) policyUpdateTrigger(reasons []string) {
> // in agent configuration, changes in endpoint labels, and change of security
> // identities.
> func (d *Daemon) TriggerPolicyUpdates(force bool, reason string) {
>+	// CIDR identity restoration may trigger early when endpoints can not yet be regenerated
>+	if d.policyTrigger == nil {
>+		return
>+	}
>+
> 	if force {
> 		log.Debugf("Artificially increasing policy revision to enforce policy recalculation")
> 		d.policy.BumpRevision()
>```
> 
> This was not necessary on v1.11 due to the policyTrigger mechanism being replaced with policy.Updater.

Why is the policy engine not initialized when something calls into `TriggerPolicyUpdates()`? Presumably something that got rearranged is now attempting to trigger policy updates before that code is ready to handle them? If we can guarantee that this logic will be called again soon, then I think we're "OK" here. If it doesn't trigger again then this is potentially avoiding handling the policy update event altogether. Then we'd need another event to come along later to make sure that the trigger eventually happens. On average I guess that's the case, but I just don't know if in some case it could get "stuck" and policy won't get recalculated due to this logic.

If the above concerns you, we'd just want to ensure that after `d.policyTrigger` is initialized, we then trigger policy updates. This could be a static call at the `d.policyTrigger` initialization point, or it could be triggered directly after k8s is fully synced, or we could introduce a `sync.Once` into this `TriggerPolicyUpdates` case iff `d.policyTrigger == nil`, then run a goroutine to wait until `d.policyTrigger` is _not_ nil, and then call the trigger. Alternatively, if you're fairly confident that we'll get & handle another policy update trigger soon anyway then maybe we just don't worry about it.

I agree that replacing the mechanism with policy.Updater in 4881234a857e70759ecb22b50ecf0895c2d7d91a changed the calculation here, because the trigger is now initialized earlier in bootstrap, which is probably what ensures that this nil dereference doesn't occur with this patch on newer releases. And I don't think it makes sense to backport that commit/PR, as it's pretty invasive and risky to backport. On the other hand... if we are now triggering policy updates much earlier on newer versions (successfully), is it at all possible that this early trigger of policy updates could cause the policy to be evaluated before we've fully synced the k8s policy resources? That seems like it could introduce a whole different cause for policy drops during restart.

**Review by joestringer — APPROVED** [review]
@jrajahalme pointed out to me out-of-band that these triggers will not find any endpoints until all k8s resources are synced, so my point above is moot. LGTM.

**Comment by jrajahalme** [comment]
> @jrajahalme pointed out to me out-of-band that these triggers will not find any endpoints until all k8s resources are synced, so my point above is moot. LGTM.

Labeled as `ready-to-merge` based on Joe's approval.

**Comment by aditighag** [comment]
@jrajahalme The PR needs to be rebased; looks like some other v1.10 backport PR was merged in between.

**Pull request merged**
