### PR TITLE
cilium: K8s Delete event indicates agent should gracefully shutdown

### PR DESCRIPTION
**Pull request by jrfastab**
K8s sends a delete event to cilium-agent which is ignored at the
moment because the node is in the kv-store. Using the kv-store as
the source of truth makes sense in most cases but when we get a
Delete event for the running cilium-agent this indicates the node
we are running on is about to be destroyed. Ignoring it means we
do not have a chance to gracefully close the agent manager which
means any keys in the kvstore will persist in the kvstore. This
means no other nodes will get delete events for the node because
the kvstore will continue to contain the node.

This results in a couple issues. First the datapath will not be
cleaned up. For ipsec this means rules will persist and if the
cluster is scaled back up may result in collisions between new
node rules and old rules if IPs are reused. Second cilium-health
will continue to probe for nodes that no longer exist resulting
in the appearance that the cluster is unhealthy.

To fix this in this patch we check if the K8s event is for the
local node and if it is close the manager which cleans up the
kvstore in the process. This will propogate delete events to all
the other nodes. When the nodes (node the one being deleted)
receive the delete event, because the node key is removed from
the kvstore, they will delete the node from the node map and
cleanup the datapath. Cilium health checks rely on the node
map so that solves the cilium-health issue and the datapath
cleanup will remove old ipsec entries and routes solving the
IP collision when scaling back up.

Tested in GKE by spinning up 10 node cluster and dropping it
down to 5 nodes and finally 1 node. Verified that state was
removed at each stepping.

Signed-off-by: John Fastabend <john.fastabend@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7998)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
I'm fine with the changes but why are you hitting this? `cilium-operator` should clean up the nodes in the kvstore as it receives the node events from k8s. Aren't you running `cilium-operator`?

cc @tgraf please double check the patch

**Comment by aanm** [comment]
@jrfastab left some comments ^^^^

**Comment by jrfastab** [comment]
@aanm will have to look into cilium-operator paths, what I was seeing before is nodes remaining in the nodes_map which is used by cilium_health and also route tables remaining. Logically this patch seems like the correct behavior to me, if the nodes being deleted lets close gracefully. But, maybe there is a bug somewhere else?

**Review by tgraf — APPROVED** [review]

**Pull request merged**
