### PR TITLE
v1.5 backports 2020-01-31

### PR DESCRIPTION
**Pull request by aanm**
* #9913 -- cni: Fix IP leak when CNI ADD times out (@tgraf)
 * #9982 -- garbage collect stale distributed locks (@aanm)
 * #10005 -- Fix GC Locks bugs (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 9913 9982 10005; do contrib/backporting/set-labels.py $pr done 1.5; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10004)

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Review by gandro — APPROVED** [review]

**Pull request merged**
