### PR TITLE
Update bpftool to get latest feature probes

### PR DESCRIPTION
**Pull request by borkmann**
See commit msg. Needed for BBR.

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]

**Comment by borkmann** [comment]
For external workloads, created https://github.com/cilium/cilium/issues/19425 as it's unrelated to this PR (if it was kernel/bpftool related in some way then we would see also issues on older 4.9 CI etc).

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
@borkmann I think you're just hitting known flake https://github.com/cilium/cilium/issues/17307 in GKE again and again (grep for `connection refused` in the output). It's very frequent so you'll probably keep hitting it. We can just merge.

**Pull request merged**
