### PR TITLE
[v1.14] ipcache: Yet another refcounting fix with mix of APIs

### PR DESCRIPTION
**Pull request by gandro**
This is a custom backport of https://github.com/cilium/cilium/pull/34715. It contains additional fixes and unit test that only apply to v1.14 only (i.e. the last two commits).
Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
34715
```

### CODE REVIEW

**Comment by gandro** [comment]
/test-backport-1.14

**Comment by gandro** [comment]
/test-backport-1.14

**Comment by gandro** [comment]
/test-backport-1.14

**Review by ldelossa — APPROVED** [review]

**Comment by gandro** [comment]
/test-backport-1.14

**Review by tommyp1ckles — APPROVED** [review]

**Pull request merged**
