### PR TITLE
Move github.com/cilium/ipam packages to main repo

### PR DESCRIPTION
**Pull request by tklauser**
First 3 commits are preparatory to update the vendored package, allow use of Cilium's concurrency-safe PRNG type in the new package and allow k8s authors in file header copyright notices.

The fourth commit moves the packages. Quoting the commit message:

    ipam, vendor: move github.com/cilium/ipam packages to main repo
    
    Instead of keeping a separate repo for these packages move them to the
    main cilium repo which makes this easier to maintain and iterate on.
    
    The code was originally forked from
    k8s.io/kubernetes/pkg/registry/core/service and has since been extended
    and changed to fit Cilium's needs.
    
    This is a copy of the github.com/cilium/ipam repo at commit.
    https://github.com/cilium/ipam/commit/fd66eae7909b3d3962dfc8887805181462a7e384
    This corresponds to the version that is currently vendored.
    Additionally, the test files are copied and unnecessry BUILD files
    (stemming from upstream k8s) were removed. Some modifications to the
    lock and rand types used within the packages needed to be made:
    
     * Use mutex types from pkg/lock for deadlock detection
     * Use pkg/rand for concurrency safe PRNG
     * Change the license/copyright format in file headers to conform to Cilium
       project requirements.
    
    Otherwise linters would complain about the use of the Go stdlib types.

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Thanks for splitting it into multiple commits. Very easy to review!

**Review by squeed — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Review by rolinh — APPROVED** [review]
Vendor changes lgtm :tada:

**Review by tommyp1ckles — APPROVED** [review]

**Pull request merged**
