### PR TITLE
v1.5 backports 19-07-13

### PR DESCRIPTION
**Pull request by jrfastab**
PRs:
#8513
// not included believe this might be causing issue. #8508
#8525
#8524
#8511
#8546

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8556)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-missed-k8s

**Comment by jrfastab** [comment]
test-me-please

**Comment by ianvernon** [comment]
This error is quite strange:

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.15-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:367
unable to create Istio resources
Expected command: kubectl apply -f  /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/istio-cilium.yaml 
To succeed, but it failed:
Exitcode: 1 
Stdout:
 	 poddisruptionbudget.policy/istio-galley created
	 poddisruptionbudget.policy/istio-ingressgateway created
	 poddisruptionbudget.policy/istio-policy created
	 poddisruptionbudget.policy/istio-telemetry created
	 poddisruptionbudget.policy/istio-pilot created
	 configmap/istio-galley-configuration created
	 configmap/prometheus created
	 configmap/istio-security-custom-resources created
	 configmap/istio created
	 configmap/istio-sidecar-injector created
	 serviceaccount/istio-galley-service-account created
	 serviceaccount/istio-ingressgateway-service-account created
	 serviceaccount/istio-mixer-service-account created
	 serviceaccount/istio-pilot-service-account created
	 serviceaccount/prometheus created
	 serviceaccount/istio-cleanup-secrets-service-account created
	 clusterrole.rbac.authorization.k8s.io/istio-cleanup-secrets-istio-system created
	 clusterrolebinding.rbac.authorization.k8s.io/istio-cleanup-secrets-istio-system created
	 job.batch/istio-cleanup-secrets-1.1.3 created
	 serviceaccount/istio-security-post-install-account created
	 clusterrole.rbac.authorization.k8s.io/istio-security-post-install-istio-system created
	 clusterrolebinding.rbac.authorization.k8s.io/istio-security-post-install-role-binding-istio-system created
	 job.batch/istio-security-post-install-1.1.3 created
	 serviceaccount/istio-citadel-service-account created
	 serviceaccount/istio-multi created
	 clusterrole.rbac.authorization.k8s.io/istio-galley-istio-system created
	 clusterrole.rbac.authorization.k8s.io/istio-ingressgateway-istio-system created
	 clusterrole.rbac.authorization.k8s.io/istio-mixer-istio-system created
	 clusterrole.rbac.authorization.k8s.io/istio-pilot-istio-system created
	 clusterrole.rbac.authorization.k8s.io/prometheus-istio-system created
	 clusterrole.rbac.authorization.k8s.io/istio-citadel-istio-system created
	 clusterrole.rbac.authorization.k8s.io/istio-reader created
	 clusterrolebinding.rbac.authorization.k8s.io/istio-galley-admin-role-binding-istio-system created
	 clusterrolebinding.rbac.authorization.k8s.io/istio-ingressgateway-istio-system created
	 clusterrolebinding.rbac.authorization.k8s.io/istio-mixer-admin-role-binding-istio-system created
	 clusterrolebinding.rbac.authorization.k8s.io/istio-pilot-istio-system created
	 clusterrolebinding.rbac.authorization.k8s.io/prometheus-istio-system created
	 clusterrolebinding.rbac.authorization.k8s.io/istio-citadel-istio-system created
	 clusterrolebinding.rbac.authorization.k8s.io/istio-multi created
	 role.rbac.authorization.k8s.io/istio-ingressgateway-sds created
	 rolebinding.rbac.authorization.k8s.io/istio-ingressgateway-sds created
	 service/istio-galley created
	 service/istio-ingressgateway created
	 service/istio-policy created
	 service/istio-telemetry created
	 service/istio-pilot created
	 service/prometheus created
	 service/istio-citadel created
	 deployment.extensions/istio-galley created
	 deployment.extensions/istio-ingressgateway created
	 deployment.extensions/istio-policy created
	 deployment.extensions/istio-telemetry created
	 deployment.extensions/istio-pilot created
	 deployment.extensions/prometheus created
	 deployment.extensions/istio-citadel created
	 horizontalpodautoscaler.autoscaling/istio-ingressgateway created
	 horizontalpodautoscaler.autoscaling/istio-policy created
	 
Stderr:
 	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.15-gopath/src/github.com/cilium/cilium/test/k8sT/istio.go:106
```

The exitCode is 1, yet the resources were created?

**Comment by ianvernon** [comment]
Ah, I see why it failed now from the `test-output.log`:

```
cmd: "kubectl apply -f  /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/istio-cilium.yaml" exitCode: 1 duration: 10.000306692s stdout:
```

I will increase the duration for this command since it appears to be taking some time due to the sheer amount of resources created.

**Comment by ianvernon** [comment]
PR which I have out against master to fix the timeout when applying the YAMLs which create the CRDs: https://github.com/cilium/cilium/pull/8579

We can cherry-pick the commit into this patch once it's merged.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13699/

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Pull request merged**
