### PR TITLE
Pick up etcd v3.4.23

### PR DESCRIPTION
**Pull request by michi-covalent**
Pick up the latest etcd 3.4 patch release. This version fixes a bunch of critical security vulnerabilities.

Ref: https://quay.io/repository/coreos/etcd?tab=tags
Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Comment by michi-covalent** [comment]
/test-backport-1.11

**Comment by michi-covalent** [comment]
`test-1.21-4.9` failure https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/2376/ looks similar to https://github.com/cilium/cilium/issues/15455

**Comment by michi-covalent** [comment]
/test-1.21-4.9

**Comment by michi-covalent** [comment]
/ci-l4lb-1.11

**Review by pchaigno — APPROVED** [review]

**Pull request merged**
