### PR TITLE
[v1.15] gh/workflows: Add IPsec key rotation action and use it in ci-eks / ci-ipsec-e2e

### PR DESCRIPTION
**Pull request by julianwiedmann**
Manual backport of
* [x] #29704 (@brb)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 29704
```

### CODE REVIEW

**Comment by julianwiedmann** [comment]
/test-backport-1.15

**Comment by julianwiedmann** [comment]
/test-backport-1.15

**Review by brb — APPROVED** [review]
Thanks!

**Comment by julianwiedmann** [comment]
I believe there's some conflicting work in the pipeline, so let's see how we get this in the easiest. `preview-only` for now, but good for review.

**Review by viktor-kurchenko — APPROVED** [review]

**Comment by julianwiedmann** [comment]
/test-backport-1.15

**Review by pchaigno — APPROVED** [review]

**Pull request merged**
