### PR TITLE
daemon: adding kernel/clang compatibility tests

### PR DESCRIPTION
**Pull request by aanm**
Cilium will check if the system is running kernel < 4.9 + clang >= 3.9
If true, cilium will error out advising the user to upgrade their kernel
version.

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/cilium/cilium/pull/505'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by tgraf** [comment]
The commit description is mistakenly saying <=4.9 when it should be saying saying >=4.9.

**Comment by aanm** [comment]
I re-write it, better?

**Comment by tgraf** [comment]
> I re-write it, better?

Why 4.9? We are working fine with 4.8 right now unless clang is too recent. Why change this?

**Comment by aanm** [comment]
The conditions where cilium doesn't start are: `kernel < 4.8 || (kernel < 4.9 && clang >= 3.9)` all remaining combinations work.

**Review by tgraf — APPROVED** [review]

**Pull request merged**
