### PR TITLE
Increase complexity in default build case

### PR DESCRIPTION
**Pull request by joestringer**
Depends on: #7153 

In local testing when I configured the header files as in this PR, I was able to get the verifier to reject a datapath that we could potentially generate in v1.4. :fearful: 

Basically I think that the introduction of `is_defined()` usage which bases conditional branches upon macros meant that the `bpf/Makefile` and `bpf/*_config.h` files no longer represent the worst-case complexity, so the verifier tests passed even though we could potentially generate too many instructions in the worst case, at runtime.

Likely to only affect pre-4.14 or so kernels, YMMV

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7092)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
@joestringer is there a way that we can automatically detect if something has changed / if the configuration the verifier is checking against is stale?

**Comment by joestringer** [comment]
test-me-please

EDIT: OK, finally got the error:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9906/testReport/junit/(root)/runtime/XRuntimeVerifier_runs_the_kernel_verifier_against_the_tree_copy_of_the_BPF_datapath/

```
	 Prog section '2/7' rejected: Invalid argument (22)!
	  - Type:         3
	  - Instructions: 4111 (15 over limit)
	  - License:      GPL
	 
	 Verifier analysis:
	 
	 Error filling program arrays!
```

**Comment by joestringer** [comment]
@ianvernon There's a couple of things here:

1. The header files in `bpf/` are out-of-date compared to what the latest daemon code generates. We could rework it so that there's a make target to generate the code from the same library package, and run that regularly somehow.
1. We have many different configuration knobs and at the moment we're basically just figuring out the most complex version by trial and error (plus maybe a little bit of context from developers). It would be neat if we could run a random configuration and watermark which configurations generate the most complexity.

**Comment by joestringer** [comment]
I'll rebase this against #7153 at which point it will pass.

**Comment by joestringer** [comment]
My plan is that for master, we use the llvm rebase to mitigate this issue and merge the headerfiles change. Then I'll prepare a backport with one minor code reorg I found that should push v1.4 under the complexity limit with this headerfile.

**Comment by brb** [comment]
> 2\. It would be neat if we could run a random configuration and watermark which configurations generate the most complexity.

We got 23 "high-level" knobs (`git grep 'if[n]\?def' bpf_lxc.c bpf_lb.c bpf_netdev.c bpf_overlay.c bpf_xdp.c bpf_features.h | awk '{print $2}' | sort | uniq | wc -l`) excluding "low-level" ones (e.g. from `bpf/include/bpf/api.h`). So, in a dummy way we would need to test 2^23 = 8388608 different configurations :scream:

**Pull request closed without merging**
