### PR TITLE
egressgw: Stop CEGP parsing in case of non-empty invalid EgressIP

### PR DESCRIPTION
**Pull request by pippolo84**
EgressIP field of CiliumEgressGatewayPolicy spec is optional, but if specified, it is used to SNAT egress traffic.  Being an optional parameter, no error is logged in case the conversion to netip.Addr fails, and the field is silently ignored.

To inform the user of the failure in setting the requested egress IP, log a warning in case of an invalid non-empty egress IP.

### CODE REVIEW

**Comment by julianwiedmann** [comment]
hmm, how does this match up with https://github.com/pippolo84/cilium/blob/355f2ffef29ad30fbdfcbf3ff20b5356e7bc994e/pkg/egressgateway/policy.go#L224 ?

**Comment by pippolo84** [comment]
> hmm, how does this match up with https://github.com/pippolo84/cilium/blob/355f2ffef29ad30fbdfcbf3ff20b5356e7bc994e/pkg/egressgateway/policy.go#L224 ?

That parsing swallows the error without giving the user any sign about a possible mistake in specifying the address. With this change, `ParseCEGP` still won't break up in case of an error, but then the user will be informed through the warning that the manager will ignore the field, despite being non-empty.

An alternative might be to stop the parsing with an error in case EgressIP is both non empty and invalid. But this would introduce a non backward-compatible change that might be harmful. In the end, a warning should be the best trade off.

**Comment by julianwiedmann** [comment]
> > hmm, how does this match up with https://github.com/pippolo84/cilium/blob/355f2ffef29ad30fbdfcbf3ff20b5356e7bc994e/pkg/egressgateway/policy.go#L224 ?
> 
> That parsing swallows the error without giving the user any sign about a possible mistake in specifying the address. With this change, `ParseCEGP` still won't break up in case of an error, but then the user will be informed through the warning that the manager will ignore the field, despite being non-empty.
> 

Ah and that's ok, because `deriveFromPolicyGatewayConfig()` later does an additional `gc.egressIP.IsValid()` check.

I think we can be more fool-proof, and move that specific `IsValid()` check into `ParseCEGP()` instead - so any potential user of the `gc.egressIP` field understands that it wasn't set with a valid IP.

> An alternative might be to stop the parsing with an error in case EgressIP is both non empty and invalid. But this would introduce a non backward-compatible change that might be harmful. In the end, a warning should be the best trade off.

I think we can definitely expect *some* sanity from the user, as the `egressIP` has a kubebuilder validation pattern attached to it. So rejecting an invalid egressIP in `ParseCEGP()` feels doable?

**Comment by pippolo84** [comment]
> I think we can definitely expect _some_ sanity from the user, as the `egressIP` has a kubebuilder validation pattern attached to it. So rejecting an invalid egressIP in `ParseCEGP()` feels doable?

Yeah, looking at the kubebuilder pattern I can't find any case where an invalid IP can pass the validation, so it is probably enough to reject the address and fail the entire parsing if, for some reason, something that the netip package doesn't like ends up there.

**Comment by julianwiedmann** [comment]
> > I think we can definitely expect _some_ sanity from the user, as the `egressIP` has a kubebuilder validation pattern attached to it. So rejecting an invalid egressIP in `ParseCEGP()` feels doable?
> 
> Yeah, looking at the kubebuilder pattern I can't find any case where an invalid IP can pass the validation, so it is probably enough to reject the address and fail the entire parsing if, for some reason, something that the netip package doesn't like ends up there.

I'll do you one better - could we also update the kubebuilder to use `+kubebuilder:validation:Format=ipv4`, and get rid of that ugly regex? :smile:

**Comment by pippolo84** [comment]
> I'll do you one better - could we also update the kubebuilder to use `+kubebuilder:validation:Format=ipv4`, and get rid of that ugly regex? 😄

Definitely! :+1:

**Review by julianwiedmann — APPROVED** [review]
looks good, thank you!

**Review by squeed — APPROVED** [review]

**Comment by julianwiedmann** [comment]
:bulb: The ipsec-e2e fail needs a rebase to pick up https://github.com/cilium/cilium/pull/31757.

**Comment by pippolo84** [comment]
Conformance Ingress failure tracked [here](https://github.com/cilium/cilium/issues/31857), rerunning

**Pull request merged**
