### PR TITLE
v1.15 Backports 2024-03-05

### PR DESCRIPTION
**Pull request by pippolo84**
* [x] #30778 (@learnitall)
 * [x] #31039 (@joestringer)
 * [x] #31052 (@sayboras)
 * [x] #30766 (@pippolo84)
 * [x] #31061 (@sayboras)
 * [ ] #31026 (@jrajahalme)
 * [x] #31025 (@julianwiedmann)
 * [x] #31083 (@julianwiedmann)
 * [x] #28657 (@gentoo-root)
 * [ ] #30462 (@saintdle)
 * [x] #31037 (@nathanjsweet)
 * [x] #31100 (@kaworu)
 * [x] #30966 (@pchaigno)
   :warning: minor conflict due to `deprecatedEnvoyRuntimeKey` and `noConnLimitEnvoy` log messages not listed in v1.15

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30778 31039 31052 30766 31061 31026 31025 31083 28657 30462 31037 31100 30966
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commits.

**Review by julianwiedmann — APPROVED** [review]

**Review by gentoo-root — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by nathanjsweet — APPROVED** [review]
My changes LGTM.

**Review by joestringer — APPROVED** [review]
:+1: for the VTEP fix

**Review by kaworu — APPROVED** [review]
Hubble commits LGTM :+1:

**Review by learnitall — APPROVED** [review]
Thank you!

**Review by nathanjsweet — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
