### PR TITLE
feat(helm): allow adding extra containers to the cilium daemonset

### PR DESCRIPTION
**Pull request by mhulscher**
This PR allows adding extra containers to the cilium daemonset.

### CODE REVIEW

**Comment by sayboras** [comment]
can you explain why this is required or point to related convo/issue ? I can't find much details from commit message.

**Comment by mhulscher** [comment]
Hi @sayboras , there is no previous conversation or issue. I have a use-case where I would like to add extra containers to the cilium daemonset. For example, I would like to be able to run `hubble observe` in the same pod. There are already other `.Values.extra*` arguments, so I figured this would be a low-impact change.

**Review by gandro — CHANGES_REQUESTED** [review]
Makes sense to me, thanks! Please apply the changes to the `values.yaml.tmpl` as well and run `make -C install/kubernetes` to generate the docs and values file.

**Comment by mhulscher** [comment]
@gandro @sayboras I pushed the requested changes. Please let me know if there's anything else.

**Comment by gandro** [comment]
@mhulscher Thanks! There are still some docs that need to be re-generated, see the Travis output here:

image

Should be fixed automatically by running `make -C Documentation`

**Comment by gandro** [comment]
Contentwise this looks good now. Please squash all your commits into a single one (which contains the `Signed-off-by` line). Thanks!

**Comment by mhulscher** [comment]
@gandro done and rebased

**Review by gandro — APPROVED** [review]
Thank you!

**Review by tommyp1ckles — APPROVED** [review]
lgtm

**Pull request merged**
