### PR TITLE
WG tunneling

### PR DESCRIPTION
**Pull request by brb**
Forward port of https://github.com/cilium/cilium/pull/28917 (minus the optional flag and the strict mode removal).

```release-note
When tunneling is enabled, a packet will be encapsulated by Cilium's tunnel netdev before encrypting with WireGuard.
```

### CODE REVIEW

**Review by brlbil — APPROVED** [review]
CI Changes LGTM

**Review by gandro — APPROVED** [review]

**Comment by julianwiedmann** [comment]
Adding backport-label to account for https://github.com/cilium/cilium/pull/28917.

**Pull request merged**
