### PR TITLE
1.4 istio backports 06 08 2019

### PR DESCRIPTION
**Pull request by jrajahalme**
Backport latest Envoy support to Cilium 1.4. This is mainly based on the corresponding backport to 1.5 (#8707), but I had to cherry-pick additional commits from v1.5 to make this work.

Istio support to updated to release 1.2.2.

This is also needed to be able to backport fortcoming Envoy changes to 1.4. 

```release-note
Istio support is updated to release 1.2.2.
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8812)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
@joestringer @brb due to the need to rebase with upstream Envoy, a lot of changes had to be pulled back into this branch, including the alignchecker changes. Can you PTAL? I don't think we're changing any actual struct alignments here, but would be more comfortable if this got your guys' signoff as well.

**Review by brb — CHANGES_REQUESTED** [review]
I think https://github.com/cilium/cilium/commit/69fd5d6d9c385209cddc6d51680c760e1110b758 needs to be backported as well. As otherwise, cilium-agent won't start with LLVM/clang < 7.0.

**Comment by ianvernon** [comment]
never-tell-me-the-odds

**Comment by ianvernon** [comment]
Builds failed:

* https://jenkins.cilium.io/job/Cilium-PR-Doc-Tests/1347/
* https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2335/
* https://jenkins.cilium.io/job/Cilium-PR-Doc-Tests/1347/
* https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/1433/

A Jenkins slave ran out of disk space ; rebuilding again, as I have taken said offending Jenkins slave offline.

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-upstream-k8s

**Review by nebril — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Review by brb — APPROVED** [review]

**Pull request merged**
