### PR TITLE
chore(deps): update go to v1.22.5

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
This PR replaces https://github.com/cilium/cilium/pull/33858. Due to the breakage introduced by the golang version upgrade, we need to have additional commits, but the branch protection rule doesn't allow us to add commits over Renovate. That's why I introduced this PR.

```release-note
chore(deps): update go to v1.22.5
```

### CODE REVIEW

**Comment by YutaroHayakawa** [comment]
/test-backport-1.14

**Review by viktor-kurchenko — APPROVED** [review]

**Review by markpash — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
Conformance Cluster Mesh: Google rate limit
Conformance IPsec E2E: https://github.com/cilium/cilium/issues/27672

**Review by kaworu — APPROVED** [review]

**Comment by julianwiedmann** [comment]
@YutaroHayakawa fyi, this needs a rebase now

**Review by glibsm — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
/test-backport-1.14

**Comment by YutaroHayakawa** [comment]
@cilium/tophat Please take a look 🙏

**Review by julianwiedmann — APPROVED** [review]

**Pull request merged**
