### PR TITLE
tests: remove unmaintained / unused tests

### PR DESCRIPTION
**Pull request by ianvernon**
Remove old runtime and K8s tests that aren't used anymore now that we have migrated
to Ginkgo. Keep some old tests, including:

* 02-perf.sh (could be useful for future nightly tests)
* 09-perf-gce.sh (could be useful for future nightly tests)
* 10-proxy.sh (devs still use this for local testing)
* 98-documentation-link-check.sh (needs to be ported to new framework)

Also keep old helper files for now, including environment provisioning scripts for K8s
just in case.

Signed-off by: Ian Vernon <ian@cilium.io>

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
CI failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3298/

Note that I have performed no code changes at all that are ran in the CI.

Almost all containers were still in 'ContainerCreating' state:
```
Ians-MBP:Documents ianvernon$ grep -A13 -r "containerStatuses" foo.txt 
foo.txt:                "containerStatuses": [
foo.txt-                    {
foo.txt-                        "image": "cilium/starwars",
foo.txt-                        "imageID": "",
foo.txt-                        "lastState": {},
foo.txt-                        "name": "deathstar",
foo.txt-                        "ready": false,
foo.txt-                        "restartCount": 0,
foo.txt-                        "state": {
foo.txt-                            "waiting": {
foo.txt-                                "reason": "ContainerCreating"
foo.txt-                            }
foo.txt-                        }
foo.txt-                    }
--
foo.txt:                "containerStatuses": [
foo.txt-                    {
foo.txt-                        "image": "cilium/starwars",
foo.txt-                        "imageID": "",
foo.txt-                        "lastState": {},
foo.txt-                        "name": "deathstar",
foo.txt-                        "ready": false,
foo.txt-                        "restartCount": 0,
foo.txt-                        "state": {
foo.txt-                            "waiting": {
foo.txt-                                "reason": "ContainerCreating"
foo.txt-                            }
foo.txt-                        }
foo.txt-                    }
--
foo.txt:                "containerStatuses": [
foo.txt-                    {
foo.txt-                        "containerID": "docker://e41913ea32bbdd19e8060e9d821fa280684a2eabe761bbe42c50dc597d52b245",
foo.txt-                        "image": "cilium/starwars:latest",
foo.txt-                        "imageID": "docker-pullable://cilium/starwars@sha256:b21abf15760e67771572f1d7100475fbda11b0de49447741612b7f5d6364bbb0",
foo.txt-                        "lastState": {},
foo.txt-                        "name": "deathstar",
foo.txt-                        "ready": true,
foo.txt-                        "restartCount": 0,
foo.txt-                        "state": {
foo.txt-                            "running": {
foo.txt-                                "startedAt": "2018-05-17T19:16:08Z"
foo.txt-                            }
foo.txt-                        }
--
foo.txt:                "containerStatuses": [
foo.txt-                    {
foo.txt-                        "image": "tgraf/netperf",
foo.txt-                        "imageID": "",
foo.txt-                        "lastState": {},
foo.txt-                        "name": "spaceship",
foo.txt-                        "ready": false,
foo.txt-                        "restartCount": 0,
foo.txt-                        "state": {
foo.txt-                            "waiting": {
foo.txt-                                "reason": "ContainerCreating"
foo.txt-                            }
foo.txt-                        }
foo.txt-                    }
--
foo.txt:                "containerStatuses": [
foo.txt-                    {
foo.txt-                        "image": "tgraf/netperf",
foo.txt-                        "imageID": "",
foo.txt-                        "lastState": {},
foo.txt-                        "name": "spaceship",
foo.txt-                        "ready": false,
foo.txt-                        "restartCount": 0,
foo.txt-                        "state": {
foo.txt-                            "waiting": {
foo.txt-                                "reason": "ContainerCreating"
foo.txt-                            }
foo.txt-                        }
foo.txt-                    }
--
foo.txt:                "containerStatuses": [
foo.txt-                    {
foo.txt-                        "image": "tgraf/netperf",
foo.txt-                        "imageID": "",
foo.txt-                        "lastState": {},
foo.txt-                        "name": "spaceship",
foo.txt-                        "ready": false,
foo.txt-                        "restartCount": 0,
foo.txt-                        "state": {
foo.txt-                            "waiting": {
foo.txt-                                "reason": "ContainerCreating"
foo.txt-                            }
foo.txt-                        }
foo.txt-                    }
--
foo.txt:                "containerStatuses": [
foo.txt-                    {
foo.txt-                        "image": "tgraf/netperf",
foo.txt-                        "imageID": "",
foo.txt-                        "lastState": {},
foo.txt-                        "name": "spaceship",
foo.txt-                        "ready": false,
foo.txt-                        "restartCount": 0,
foo.txt-                        "state": {
foo.txt-                            "waiting": {
foo.txt-                                "reason": "ContainerCreating"
foo.txt-                            }
foo.txt-                        }
foo.txt-                    }
```

**Comment by ianvernon** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]

**Pull request merged**
