### PR TITLE
v1.10 backports 2022-02-17

### PR DESCRIPTION
**Pull request by nebril**
* #18762 -- Alibabacloud fixes (@jaffcheng)
 * #18486 -- Prevent unmanaged pods in GKE's containerd flavors (@joamaki )

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18762 18486; do contrib/backporting/set-labels.py $pr done 1.10; done
```
or with
```
$ make add-label branch=v1.10 issues=18762
```

### CODE REVIEW

**Comment by nebril** [comment]
/test-backport-1.10

**Comment by nebril** [comment]
/test-backport-1.10

**Review by jaffcheng — APPROVED** [review]

**Review by bmcustodio — APPROVED** [review]

**Comment by nebril** [comment]
/ci-aks-1.10

**Comment by nebril** [comment]
/test-1.17-4.9

**Comment by nebril** [comment]
/test-1.18-4.9

**Comment by joestringer** [comment]
[ConformanceEKS](https://github.com/cilium/cilium/actions/runs/1858416906) run failed during initialization (waiting for services to become ready) after reinstalling with encryption.
[k8s-1.17-kernel-4.9](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-4.9/518/) and [k8s-1.19-kernel-4.9](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.9/2011/) both timed out, it seems like there's frequently issues with kube-dns not being ready.  In the 1.17 run for instance, `K8sDatapathConfig Host firewall With VXLAN and endpoint routes` failed due to kubernetes not becoming ready in time. Other tests demonstrate `cilium status` complaining about one of the controllers for assessing cilium-health endpoint happiness, `cilium-health-ep                              2m23s ago      14s ago      2       Get "http://10.0.0.23:4240/hello": dial tcp 10.0.0.23:4240: connect: no route to host`.

I'll kick each of these, hopefully there isn't breakage introduced into the v1.10 tree.

**Comment by joestringer** [comment]
/ci-eks-1.10

**Comment by joestringer** [comment]
/test-1.17-4.9

**Comment by joestringer** [comment]
/test-1.19-4.9

**Comment by joestringer** [comment]
Seems like there's something that needs investigation here in regards to the ConformanceEKS action. The other flaky tests are also making me nervous. Not planning to merge this before the upcoming release. @cilium/tophat , please investigate.

**Comment by pchaigno** [comment]
Taking over.

**Comment by pchaigno** [comment]
/test-backport-1.10

**Comment by pchaigno** [comment]
/test-1.18-4.9

**Comment by pchaigno** [comment]
- The CodeQL errors are clearly unrelated (it's unclear why they even show up).
- ConformanceEKS failed with the bug fixed by https://github.com/cilium/cilium/pull/18506. I marked for backport to v1.10.
- runtime failed with the known issue https://github.com/cilium/cilium/issues/18919.

Given the changes in this PR affect Alibaba IPAM and GKE, it's unlikely any of these CI jobs would be affected anyway. Reviews are in. Marking ready to merge.

**Pull request merged**
