### PR TITLE
operator, k8s: Prevent CEC watcher goroutine leak

### PR DESCRIPTION
**Pull request by yulng**
fix:prevent goroutine leakage

### CODE REVIEW

**Review by christarazi — CHANGES_REQUESTED** [review]
Can you provide justification as to why this change is needed? It's not clear how there is a goroutine leak. The K8s watchers will always be running forever until Cilium shuts down, so moving to a context here doesn't seem to have any impact.

**Comment by yulng** [comment]
> Can you provide justification as to why this change is needed? It's not clear how there is a goroutine leak. The K8s watchers will always be running forever until Cilium shuts down, so moving to a context here doesn't seem to have any impact.

I refer to this https://github.com/cilium/cilium/pull/21913

**Comment by christarazi** [comment]
Can you check it against [this](https://github.com/cilium/cilium/pull/21913#pullrequestreview-1160216922) comment?

**Comment by yulng** [comment]
> Can you check it against [this](https://github.com/cilium/cilium/pull/21913#pullrequestreview-1160216922) comment?

ok,I thought it was all
i closed it later

**Comment by tommyp1ckles** [comment]
/test-1.25-4.19

**Comment by tommyp1ckles** [comment]
Changes make sense to me.

**Comment by sayboras** [comment]
I have no other comment :)

**Comment by yulng** [comment]
> @yulng Were you going to work on this one some more, or should it be closed?
> 
> If you are still interested in it, it needs:
> 
> * a commit message update to make clear what's happening
> * a response to @christarazi's feedback above
> * a rebase from `master`.



> comment

Christarazi's  comment only talks about test/controlplane ,but i searched all and modified it
if i rebase and push again ,is there any hope to merge ?

**Comment by youngnick** [comment]
@yulng I think if you change your commit message to include some information about how this will affect mainly the tests, as in the comment linked above, then rebase, we should be good to go.

**Review by tommyp1ckles — APPROVED** [review]

**Comment by yulng** [comment]
> @yulng I think if you change your commit message to include some information about how this will affect mainly the tests, as in the comment linked above, then rebase, we should be good to go.

ok,done

**Review by christarazi — CHANGES_REQUESTED** [review]
Can you update the commit msg title to:

```
operator, k8s: Prevent CEC watcher goroutine leak
```

**Review by sayboras — APPROVED** [review]

**Comment by yulng** [comment]
> Can you update the commit msg title to:
> 
> ```
> operator, k8s: Prevent CEC watcher goroutine leak
> ```

It's ok
Thanks

**Review by christarazi — APPROVED** [review]
Thanks for the fix and the PR!

For future submissions, we ask for justification upfront so that we can understand why you are submitting a change. This way, we can review and validate the fix with ease. For bugfixes, this is especially important, along with how you were able to find the issue.

**Comment by julianwiedmann** [comment]
/test-1.26-net-next

**Comment by julianwiedmann** [comment]
happy CI, happy me

**Comment by yulng** [comment]
Thanks everyone

**Pull request merged**
