### PR TITLE
Async containerd sync

### PR DESCRIPTION
**Pull request by raybejjani**
**Summary of changes**:

Fixes: #2627

**How to test (optional)**:
I restarted the daemon a few times and observed no problems. I'm hoping the runtime tests cover this codepath enough.

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-ginkgo-all

**Comment by raybejjani** [comment]
test-all-ginkgo

**Comment by tgraf** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
