### PR TITLE
Istio: Update to 1.2.4

### PR DESCRIPTION
**Pull request by jrajahalme**
Istio release 1.2.4 includes the sidecar proxy with Envoy security fixes released on 8/13/2019.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
```release-note
Istio integration is updated to Istio version 1.2.4
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8914)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
