### PR TITLE
Gopkg.*: bump etcd library to v3.3.11

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6676)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
@aanm shouldn't there be corresponding code changes as well to the dependency if the version changes?

**Comment by ianvernon** [comment]
@aanm shouldn't there be corresponding code changes as well to the dependency if the version changes?

**Comment by aanm** [comment]
@ianvernon in this case no as there were no changes in the imports that we use.

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
