### PR TITLE
Test: K8s Policies did not wait for all endpoints to be ready.

### LINKED ISSUE #3975: TesT: k8s-1.7.K8sValidatedPolicyTest Basic Test checks all kind of kubernetes policies failed
```
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:312
"app3-1089644107-597xc" cannot curl to "10.99.145.185" public
Expected
    <bool>: false
to be true
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/k8sT/Policies.go:313
```
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/2291/console

Looks like that the policy didn't wait correctly: 
```
time="2018-05-01T15:04:19Z" level=debug msg="running command: kubectl exec -n kube-system cilium-bkh2x -- cilium endpoint list -o jsonpath='{range [*]}{@.id}{\"=\"}{@.status.policy.realized.policy-revision}{\"\\n\"}{end}'"
cmd: "kubectl exec -n kube-system cilium-bkh2x -- cilium endpoint list -o jsonpath='{range [*]}{@.id}{\"=\"}{@.status.policy.realized.policy-revision}{\"\\n\"}{end}'" exitCode: 0 
 173=15
13949=15
29381=14
29898=15
48896=15


time="2018-05-01T15:04:20Z" level=info msg="Endpoint 13949 had version 14 now 15 updated : 0"
time="2018-05-01T15:04:20Z" level=info msg="Endpoint 29898 had version 14 now 15 updated : 1"
time="2018-05-01T15:04:20Z" level=info msg="Endpoint 48896 had version 14 now 15 updated : 2"
time="2018-05-01T15:04:20Z" level=info msg="Endpoint 173 had version 14 now 15 updated : 3"
time="2018-05-01T15:04:20Z" level=debug msg="running command: kubectl exec -n default app3-1089644107-597xc -- curl -s --fail --connect-timeout 5 --max-time 5 http://10.99.145.185/public"
cmd: "kubectl exec -n default app3-1089644107-597xc -- curl -s --fail --connect-timeout 5 --max-time 5 http://10.99.145.185/public" exitCode: 28 
```

[test_results_Ginkgo-CI-Tests-Pipeline_2280.zip](https://github.com/cilium/cilium/files/1964354/test_results_Ginkgo-CI-Tests-Pipeline_2280.zip)

### PR DESCRIPTION
**Pull request by eloycoto**
When the test runs, one pod was not ready and the connection fails. With
the use of `kubectl.CiliumPolicyAction` all endpoints need to be ready
and with the latest policy applied to the test continue.

Fix #3975

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
Problems with the update: 
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:312
Expect 403 in the result
Expected
    <string>: 200{ 'val': 'this is private' }
    
to contain substring
    <string>: 403
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Updates.go:189
```
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/2888/testReport/junit/k8s-1/7/K8sValidatedUpdates_Updating_Cilium_stable_to_master/

**Comment by eloycoto** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
LGTM, but this is not labeled; can this be merged @eloycoto ?

**Comment by eloycoto** [comment]
Ohh, sorry, I've just labeled it,sorry!

**Comment by ianvernon** [comment]
@eloycoto no problem :) merged!

**Pull request merged**
