### PR TITLE
policy: Fix selector policy detach when races

### PR DESCRIPTION
**Pull request by jrajahalme**
It is possible for two endpoints race in policy resolution so that
they both end up computing and updating the same revision of the
policy. This was fine when the selector policy did not hold any
references in the selector cache, but now that it does, we must make
sure each generated selector policy will be Detache()ed. With the race
it was possible that two parallel executions got the same
`currentPolicy` pointer, hence detaching the same `currentPolicy` on
both execution paths, leaving the new policy computed first simply
overwritten by setPolicy, but not detached.

Solve this by using atomic.SwapPointer() instead of the simpler
atomic.StorePointer() to swap the pointer values, and then detach the
old pointer value returned by the swap operation. By moving the
Detach() call to the setPolicy() we simplify the call sites.

Fixes: #7958
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8186)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
CI flake (interrupt after test stuck after finishing for more than an hour):
```
18:06:00  STEP: Checking pod connectivity between nodes
18:06:05  === Test Finished at 2019-06-01T15:06:04Z====
19:37:51  Sending interrupt signal to process
19:38:04  <Checks>
19:38:04  Number of "context deadline exceeded" in logs: 0
19:38:04  Number of "level=error" in logs: 0
19:38:04  Number of "level=warning" in logs: 0
19:38:04  Number of "Cilium API handler panicked" in logs: 0
19:38:04  Number of "Goroutine took lock for more than" in logs: 0
19:38:04  No errors/warnings found in logs
19:38:04  
19:38:04  </Checks>
19:38:04  
19:38:04  
19:38:04  • [SLOW TEST:5555.531 seconds]
19:38:04  K8sDatapathConfig
19:38:04  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.14-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:378
19:38:04    DirectRouting
19:38:04    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.14-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:378
19:38:04      Check connectivity with automatic direct nodes routes
19:38:04      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.14-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
19:38:04  ------------------------------
19:38:04  K8sDatapathConfig Transparent encryption DirectRouting 
19:38:04    Check connectivity with automatic direct nodes routes
19:38:04    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.14-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
19:38:04  ===================== TEST FAILED =====================
19:38:04  cmd: kubectl get pods -o wide --all-namespaces
19:38:04  Exitcode: 1 
19:38:04  Stdout:
19:38:04   	 
19:38:04  Stderr:
19:38:04   	 
19:38:04  
19:38:04  ===================== Exiting AfterFailed =====================
19:38:11  After 20s process did not stop
```

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
CI failure due to "Bad Gateway":
```
22:09:55      k8s1-1.14: ***************************************
22:09:55      k8s1-1.14: *
22:09:55      k8s1-1.14: *
22:09:55      k8s1-1.14: * on attempt 9 of function "wget https://packages.cloud.google.com/apt/doc/apt-key.gpg"
22:09:55      k8s1-1.14: *
22:09:55      k8s1-1.14: *
22:09:55      k8s1-1.14: ***************************************
22:09:55      k8s1-1.14: --2019-06-02 19:09:53--  https://packages.cloud.google.com/apt/doc/apt-key.gpg
22:09:55      k8s1-1.14: Resolving packages.cloud.google.com (packages.cloud.google.com)... 
22:09:55      k8s1-1.14: 172.217.11.46
22:09:55      k8s1-1.14: , 
22:09:55      k8s1-1.14: 2607:f8b0:4006:815::200e
22:09:55      k8s1-1.14: Connecting to packages.cloud.google.com (packages.cloud.google.com)|172.217.11.46|:443... 
22:09:55      k8s1-1.14: connected.
22:09:55      k8s1-1.14: HTTP request sent, awaiting response... 
22:10:13      k8s1-1.14: 502 Bad Gateway
22:10:13      k8s1-1.14: 2019-06-02 19:10:13 ERROR 502: Bad Gateway.
22:10:14      k8s1-1.14: ***************************************
22:10:14      k8s1-1.14: *
22:10:14      k8s1-1.14: *
22:10:14      k8s1-1.14: * running function "wget https://packages.cloud.google.com/apt/doc/apt-key.gpg" 10 times did not succeed
22:10:14      k8s1-1.14: *
22:10:14      k8s1-1.14: *
22:10:14      k8s1-1.14: ***************************************
```

**Comment by jrajahalme** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Pull request merged**
