### PR TITLE
maglev: Don't populate v4 inner table upon nat46 service

### PR DESCRIPTION
**Pull request by borkmann**
See commit msg

### CODE REVIEW

**Comment by julianwiedmann** [comment]
Oh, fun. And all the surrounding code looked like this was very much intended :sweat_smile:.

Had a quick look, think we also need the following:

```
diff --git a/pkg/maps/lbmap/lbmap.go b/pkg/maps/lbmap/lbmap.go
index 6b1f68c402..364971ce25 100644
--- a/pkg/maps/lbmap/lbmap.go
+++ b/pkg/maps/lbmap/lbmap.go
@@ -82,12 +82,14 @@ func (lbmap *LBBPFMap) upsertServiceProto(p *datapathTypes.UpsertServiceParams,
        slot := 1
        svcVal := svcKey.NewValue().(ServiceValue)
 
-       backends := p.ActiveBackends
-       if len(p.PreferredBackends) > 0 {
-               backends = p.PreferredBackends
-       }
+       // start off with #backends = 0 for updateMasterService()
+       backends := make(map[string]loadbalancer.BackendID)
 
        if backendsOk {
+               backends = p.ActiveBackends
+               if len(p.PreferredBackends) > 0 {
+                       backends = p.PreferredBackends
+               }
+
                if p.UseMaglev && len(backends) != 0 {
                        if err := lbmap.UpsertMaglevLookupTable(p.ID, backends, ipv6); err != nil {
                                return err
@@ -246,7 +248,7 @@ func (*LBBPFMap) DeleteService(svc loadbalancer.L3n4AddrID, backendCount int, us
                return err
        }
        if natPolicy == loadbalancer.SVCNatPolicyNat46 {
-               if err := deleteServiceProto(svc, 0, useMaglev, false); err != nil {
+               if err := deleteServiceProto(svc, 0, false, false); err != nil {
                        return err
                }
        }
diff --git a/pkg/service/service.go b/pkg/service/service.go
index 8a8dca8044..b125e97f44 100644
--- a/pkg/service/service.go
+++ b/pkg/service/service.go
@@ -1345,11 +1345,8 @@ func (s *Service) restoreServicesLocked() error {
 
                // Recalculate Maglev lookup tables if the maps were removed due to
                // the changed M param.
-               ipv6 := newSVC.frontend.IsIPv6()
+               ipv6 := newSVC.frontend.IsIPv6() || (newSVC.NatPolicy == lb.SVCNatPolicyNat46)
                recreated := s.lbmap.IsMaglevLookupTableRecreated(ipv6)
-               if svc.NatPolicy == lb.SVCNatPolicyNat46 {
-                       recreated = recreated || s.lbmap.IsMaglevLookupTableRecreated(!ipv6)
-               }
                if option.Config.DatapathMode == datapathOpt.DatapathModeLBOnly &&
                        newSVC.useMaglev() && recreated {
 
@@ -1358,17 +1355,10 @@ func (s *Service) restoreServicesLocked() error {
                                backends[b.String()] = b.ID
                        }
                        if err := s.lbmap.UpsertMaglevLookupTable(uint16(newSVC.frontend.ID), backends,
-                               ipv6 || svc.NatPolicy == lb.SVCNatPolicyNat46); err != nil {
+                               ipv6); err != nil {
                                scopedLog.WithError(err).Warning("Unable to upsert into the Maglev BPF map.")
                                continue
                        }
-                       if svc.NatPolicy == lb.SVCNatPolicyNat46 {
-                               if err := s.lbmap.UpsertMaglevLookupTable(uint16(newSVC.frontend.ID), backends,
-                                       false); err != nil {
-                                       scopedLog.WithError(err).Warning("Unable to upsert into the Maglev BPF map.")
-                                       continue
-                               }
-                       }
                }
 
                s.svcByHash[newSVC.hash] = newSVC
```

**Comment by brb** [comment]
Thanks for the fix. Could we also add the pkg/lbmap unit tests to whether the unnecessary Maglev tables are not created?

**Comment by borkmann** [comment]
> Thanks for the fix. Could we also add the pkg/lbmap unit tests to whether the unnecessary Maglev tables are not created?

Yes, I'll add a unit test for it.

**Review by brb — APPROVED** [review]
Thanks! Tested in my PR https://github.com/cilium/cilium/pull/20625, the issue is resolved indeed - https://github.com/cilium/cilium/runs/7746364417?check_suite_focus=true.

**Review by julianwiedmann — APPROVED** [review]
lgtm, thanks Daniel!

**Pull request merged**
