### PR TITLE
ci: update cilium-cli to v0.10.3

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by pchaigno** [comment]
Should we run all workflows a couple times to ensure we're not introducing flakes?

**Comment by tklauser** [comment]
> Should we run all workflows a couple times to ensure we're not introducing flakes?

Good suggestions. The affected CI 3.0 tests ran 5 times (and 3 times for the previous version of this PR with cilium-cli 0.10.2) without any flakes occurring. Removing the test commit.

**Review by pchaigno — APPROVED** [review]
Thanks a lot @tklauser!

**Comment by tklauser** [comment]
Review is in and CI 3.0 tests passed, marked as ready to merge.

**Pull request merged**
