### PR TITLE
bpf: Add BPF map operations for the StateDB reconciler

### PR DESCRIPTION
**Pull request by joamaki**
This allows defining the desired state of a BPF map as a StateDB table and to reconcile it with a BPF map. The table can be inspected with "cilium-dbg statedb dump" (or with a table-specific command), and the reconciliation state of each object can be queried. Failure the reconcile will be reported in module health, metrics and in the individual objects.

See ops_linux_test.go for example usage.

### CODE REVIEW

**Comment by joamaki** [comment]
I left out the batch operations as I'm not sure how we could currently do this efficiently without bunch of copying and the benchmarks didn't show significant improvement in speed.

Here's how it would approximately look like: https://github.com/cilium/cilium/pull/31035/files#diff-d8fb501ccfd280cddcf1eb74a221bcd6de40714f3fbba1176502fbb435ec18c7R165.

**Review by dylandreimerink — APPROVED** [review]
LGTM

**Pull request merged**
