### PR TITLE
bpf: Fix edge cases in new token bucket ratelimiting implementation

### PR DESCRIPTION
**Pull request by dylandreimerink**
This commit makes sure we reuse the same timestamp within the whole function instead of getting time multiple times.

It also adds logic to keep track of the time remainder of the interval when topping up the bucket. Before we discarded the remainder which could cause differences in the rate limit in certain edge cases.

Both changes improve the correctness of the rate limiting implementation in certain edge cases.

```release-note
improve the correctness of the rate limiting implementation in certain edge cases.
```

### CODE REVIEW

**Review by gentoo-root — APPROVED** [review]
Perfect! Thanks for fixing it.

**Review by derailed — APPROVED** [review]
@dylandreimerink Great catch!

**Pull request merged**
