### PR TITLE
Support updating controllers instead of requiring to re-create them

### PR DESCRIPTION
**Pull request by rlenglet**
Don't stop the old goroutine to start a new one on update, to prevent having two goroutines running simultaneously for a single controller.
Instead, atomically change the parameters of the existing controller.
Make sure that all fields (esp. lastError) are updated while locking the controller mutex.

Preserving the old controller when it is updated also preserves the controller's UUID and stats (success and failure counts, success and failure timestamps, etc.).

Signed-off-by: Romain Lenglet <romain@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4683)

### CODE REVIEW

**Comment by rlenglet** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
Very nice!

**Review by ianvernon — APPROVED** [review]

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by joestringer** [comment]
Proposing for backport to fix #5158 on Cilium v1.1.

**Pull request merged**
