### PR TITLE
policy: replace go-logging with std log

### PR DESCRIPTION
**Pull request by tklauser**
This saves ~35 KB on the cilium-agent and cilium-operator binaries and
gets rid of a vendored dependency.

Updates #10056

Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10110)

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
looks good. Needs rebase @tklauser

**Comment by tklauser** [comment]
test-me-please

**Comment by aanm** [comment]
@tklauser it seem it hit a real failure:

```
# github.com/cilium/cilium/pkg/policy
vet: pkg/policy/rule_test.go:226:16: undeclared name: logging
make[1]: *** [govet] Error 2
make[1]: Leaving directory `/home/travis/gopath/src/github.com/cilium/cilium'
make: *** [unit-tests] Error 2
```

**Comment by tklauser** [comment]
Oops, looks like I missed newly added ones. Now fixed, thanks @aam.

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Pull request merged**
