### PR TITLE
backport 1.4 2019 05 29

### PR DESCRIPTION
**Pull request by aanm**
* PR: #7982 -- daemon: Remove stale maps only after restoring all endpoints (@brb) 
 * PR: #8014 -- envoy: Do not use deprecated configuration options. (@jrajahalme) 
 * PR: #8017 -- cilium: IsLocal() needs to compare both Name and Cluster (@jrfastab) 
 * PR: #8010 -- daemon/Makefile: rm -f on make clean for links (@aanm) 
 * PR: #8066 -- pkg/endpoint: fix assignment in nil map on restore (@aanm) 
 * PR: #8105 -- Recover from ginkgo fail in WithTimeout helper (@nebril) 
 * PR: #8097 -- proxylib: Fix egress enforcement (@jrajahalme) 
 * PR: #8149 -- envoy: Prevent resending NACKed resources also when there are no ACK observers (@jrajahalme)

* #7955 -- test: replace guestbook test docker image (@aanm)
 * #8004 -- docs: fix architecture images' URL (@aanm)

https://github.com/cilium/cilium/pull/8002
https://github.com/cilium/cilium/pull/7823
https://github.com/cilium/cilium/pull/8105

~@jrajahalme I had to bump the revision number of `cilium/proxy` in `Gopkg.toml` so I could be able to backport PR #8014.~ check https://github.com/cilium/cilium/pull/8156#issuecomment-496958744

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8156)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
@jrajahalme I might need to drop #8014 as the build is failing, can you take a look at it?

**Comment by aanm** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Bumping cilium/proxy version should be OK, as we have earlier already bumped the actual proxy version due to the CVE fixes.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
@raybejjani please take a look at the last commit

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-docs-please

**Pull request merged**
