### PR TITLE
v1.11 Backports 2023-03-14

### PR DESCRIPTION
**Pull request by nebril**
* [ ] #24132 (@ysksuzuki)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 24132; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
make add-labels BRANCH=v1.11 ISSUES=24132
```

### CODE REVIEW

**Comment by nebril** [comment]
/test-backport-1.11

**Comment by jrajahalme** [comment]
@nebril `init.sh` failed in logs, could it be a verifier fail?

**Comment by nebril** [comment]
Got confirmation from @rgo3 that these `init.sh` failures are not related to these changes

**Comment by nebril** [comment]
`k8s-1.17-kernel-4.9` seems to have failed because of a cleanup issue (port was already allocated for a service), unlikely to have been caused by the changes.

**Comment by jrajahalme** [comment]
test-1.19-4.9 has these in the agent logs:
```
⚠️  Found "2023-03-14T18:45:29.040496972Z level=error msg=\"Command execution failed\" cmd=\"[/var/lib/cilium/bpf/init.sh /var/lib/cilium/bpf /var/run/cilium/state 10.0.1.190 fd04::12 tunnel vxlan 8472 <nil> cilium_host cilium_net 1500 false false false /run/cilium/cgroupv2 /sys/fs/bpf false true v3 3 false true]\" error=\"exit status 1\" subsys=datapath-loader" in logs 1 times
⚠️  Found "2023-03-14T18:45:27.158158954Z level=error msg=\"Command execution failed\" cmd=\"[/var/lib/cilium/bpf/init.sh /var/lib/cilium/bpf /var/run/cilium/state 10.0.0.188 fd04::11 tunnel vxlan 8472 <nil> cilium_host cilium_net 1500 false false false /run/cilium/cgroupv2 /sys/fs/bpf false true v3 3 false true]\" error=\"exit status 1\" subsys=datapath-loader" in logs 1 times
```

**Comment by jrajahalme** [comment]
relevant agent `9vdqs` logs:
```
2023-03-14T18:45:29.046475112Z level=warning msg="+ '[' -z '' ']'" subsys=datapath-loader
2023-03-14T18:45:29.046476918Z level=warning msg="+ cilium bpf migrate-maps -s bpf_overlay.o" subsys=datapath-loader
2023-03-14T18:45:29.046478744Z level=warning msg="+ tc filter replace dev cilium_vxlan ingress prio 1 handle 1 bpf da obj bpf_overlay.o sec from-overlay" subsys=datapath-loader
2023-03-14T18:45:29.046480631Z level=warning msg="libbpf: load bpf program failed: Invalid argument" subsys=datapath-loader
2023-03-14T18:45:29.046482440Z level=warning msg="libbpf: -- BEGIN DUMP LOG ---" subsys=datapath-loader
2023-03-14T18:45:29.046484235Z level=warning msg="libbpf: " subsys=datapath-loader
2023-03-14T18:45:29.046485989Z level=warning msg="0: (bf) r6 = r1" subsys=datapath-loader
2023-03-14T18:45:29.046487770Z level=warning msg="1: (61) r2 = *(u32 *)(r6 +0)" subsys=datapath-loader
2023-03-14T18:45:29.046489551Z level=warning msg="2: (61) r1 = *(u32 *)(r6 +56)" subsys=datapath-loader
2023-03-14T18:45:29.046491375Z level=warning msg="3: (61) r4 = *(u32 *)(r6 +68)" subsys=datapath-loader
2023-03-14T18:45:29.046494403Z level=warning msg="4: (61) r5 = *(u32 *)(r6 +60)" subsys=datapath-loader
2023-03-14T18:45:29.046496215Z level=warning msg="5: (61) r3 = *(u32 *)(r6 +48)" subsys=datapath-loader
2023-03-14T18:45:29.046498013Z level=warning msg="6: (61) r0 = *(u32 *)(r6 +52)" subsys=datapath-loader
2023-03-14T18:45:29.046500006Z level=warning msg="7: (63) *(u32 *)(r10 -12) = r0" subsys=datapath-loader
2023-03-14T18:45:29.046501851Z level=warning msg="8: (63) *(u32 *)(r10 -16) = r3" subsys=datapath-loader
2023-03-14T18:45:29.046503682Z level=warning msg="9: (bf) r3 = r2" subsys=datapath-loader
2023-03-14T18:45:29.046505438Z level=warning msg="10: (a6) BUG" subsys=datapath-loader
2023-03-14T18:45:29.046507269Z level=warning msg="unknown insn class 6" subsys=datapath-loader
2023-03-14T18:45:29.046509051Z level=warning subsys=datapath-loader
2023-03-14T18:45:29.046510815Z level=warning msg="libbpf: -- END LOG --" subsys=datapath-loader
2023-03-14T18:45:29.046512627Z level=warning msg="libbpf: failed to load program '__send_drop_notify'" subsys=datapath-loader
2023-03-14T18:45:29.046514482Z level=warning msg="libbpf: failed to load object 'bpf_overlay.o'" subsys=datapath-loader
2023-03-14T18:45:29.046516322Z level=warning msg="Unable to load program" subsys=datapath-loader
2023-03-14T18:45:29.046518107Z level=warning msg="+ cilium bpf migrate-maps -e bpf_overlay.o -r 1" subsys=datapath-loader
2023-03-14T18:45:29.046519918Z level=warning msg="+ return 1" subsys=datapath-loader
2023-03-14T18:45:29.046521775Z level=fatal msg="Error while creating daemon" error="error while initializing daemon: failed while reinitializing datapath: exit status 1" subsys=daemon
```
Same on the other agent. This is from `bpf_overlay` program, while the backported change is in `bpf_host.c`, so it seems unlikely that this backport would have caused this.

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
