### PR TITLE
Fix daddr lookup

### PR DESCRIPTION
**Pull request by jrfastab**
The checksum is not being correctly calculated when using lb service + proxy. The reason is because we use the original daddr assigned before the service daddr is assigned to calculate the checksum.

This PR fixes this by using the service daddr in this case.

Pushing the fix now, but will push additional test cases to catch this case tomorrow.

### CODE REVIEW

**Comment by borkmann** [comment]
Jenkin says ...
```
==> cilium-master: faf760718c591c4ae63d7300f912d9f02a3d0592015695ddc79d32cb56e4280b
==> cilium-master: 2d96ba3a1c59ae2f57d482ac37aeb0146b26ade2b206514766d9d44b45077c30
==> cilium-master: docker: Error response from daemon: NetworkDriver.Join: Unable to connect endpoint to network: [PATCH /endpoint/{id}][500] patchEndpointIdFailed  error while regenerating endpoint. For more info run: 'cilium endpoint get 63464'
==> cilium-master: {"Err":"","InterfaceName":{"SrcName":"tmpd96d5","DstName":"","DstPrefix":"cilium"},"Gateway":"","GatewayIPv6":"fd02::c0a8:210b:0:0","StaticRoutes":[{"Destination":"fd02::c0a8:210b:0:0/128","RouteType":1,"NextHop":""},{"Destination":"::/0","RouteType":0,"NextHop":"fd02::c0a8:210b:0:0"},{"Destination":"10.11.0.1/32","RouteType":1,"NextHop":""},{"Destination":"0.0.0.0/0","RouteType":0,"NextHop":"10.11.0.1"}],"DisableGatewayService":true}.
==> cilium-master: server
```
... but I cannot reproduce the errorr locally. Do we have any introspection what fails to regenerate exactly on Jenkins side?

**Comment by tgraf** [comment]
> ... but I cannot reproduce the errorr locally. Do we have any introspection what fails to regenerate exactly on Jenkins side?

The Jenkins error seems unrelated to the change. I suggest to trigger another test run.

**Comment by jrfastab** [comment]
I just pushed the series with a revert patch on top that reverted the change so we can see if it fails regardless of changes.

**Comment by jrfastab** [comment]
Moved address assignments below 'goto' label. The older verifiers do not seem to be able to track that proxy_port will only be non-zero in TCP or UDP cases.

**Comment by jrfastab** [comment]
And one more time, with bindata update.

**Review by tgraf — APPROVED** [review]
Thanks for leaving a comment regarding verifier behaviour.

**Review by aanm — APPROVED** [review]

**Pull request merged**
