### PR TITLE
v1.14 Backports 2023-07-10

### PR DESCRIPTION
**Pull request by jibi**
* [x] #26607 (@michi-covalent)
 * [x] #26608 (@michi-covalent)
 * [x] #26577 (@brb)
 * [x] #26615 (@jschwinger233)
 * [x] #26642 (@mhofstetter)
 * [x] #26590 (@YutaroHayakawa)
 * [x] #26668 (@tklauser)
 * [x] #26614 (@giorio94)
 * [x] #26606 (@michi-covalent)
 * [x] #22587 (@yasz24)
 * [x] #26662 (@gandro)
 * [ ] #26671 (@christarazi)
 * [x] #26484 (@pippolo84)
 * [x] #25217 (@brb)
 * [x] #26457 (@jibi)
 * [ ] #26675 (@christarazi)
 * [x] #26692 (@tklauser)
 * [x] #26715 (@tklauser)
 * [ ] #26667 (@dylandreimerink)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 26607 26608 26577 26615 26642 26590 26668 26614 26606 22587 26662 26671 26484 25217 26457 26675 26692 26715 26667; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=26607,26608,26577,26615,26642,26590,26668,26614,26606,22587,26662,26671,26484,25217,26457,26675,26692,26715,26667
```

### CODE REVIEW

**Review by tklauser — APPROVED** [review]
Looks good for my changes, thanks Jibi!

**Comment by jibi** [comment]
/test-backport-1.14

**Review by pippolo84 — APPROVED** [review]
LGTM for my PR, thanks!

**Review by mhofstetter — APPROVED** [review]

**Review by brb — APPROVED** [review]
Thanks!

**Review by gandro — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
My commits look good. Thanks!

**Review by michi-covalent — APPROVED** [review]
🙏

**Review by yasz24 — APPROVED** [review]
LGTM for #22587

**Comment by YutaroHayakawa** [comment]
My change looks good. Thanks!

**Review by YutaroHayakawa — APPROVED** [review]
My change looks good. Thanks!

**Review by jschwinger233 — APPROVED** [review]

**Comment by jibi** [comment]
couple of trivial docs/bugtool PRs left, marking as ready

**Pull request merged**
