### PR TITLE
Allow IPSec and kube-proxy-replacement=strict to be used together

### PR DESCRIPTION
**Pull request by martin31821**
This is a draft PR which allows cilium to be used with kube-proxy-replacement=strict as well as IPSec.
It does so by reducing the IPSec key space to 3 bit (i.e. 8 Keys) and therefore resolving the conflict between MARK_MAGIC_SNAT_DONE and MARK_MAGIC_KEY_ID. 

I tested this on a small test cluster where the cilium connectivity test passes.

xref: #12985

### CODE REVIEW

**Comment by brb** [comment]
retest-net-next

**Comment by jrfastab** [comment]
I think 8 keys is likely OK, but it does create a compat problem on upgrade if user has a working key sytem using >8keys they will potentially break.

**Comment by jrfastab** [comment]
@joestringer maybe we could wrap it in a helm option for users to opt in? So for a release have a `--reduced-ipsec-keys` option? Then drop it later? Do we support multiple version jumps I presume users going from 1.8->1.10 for example need to upgrade through 1.9 to have any expectation the upgrade system will guard them from breaking changes.

**Comment by martin31821** [comment]
@jrfastab It will most likely create an update problem anyway, since the position of the key index in the skb->mark changed, which will connections cause to drop (if I understood the concept correctly, but I'm not sure on that point)
Another point is what @joestringer mentioned in the slack yesterday is that we indeed have a clash with the kubelet IPTables chains using 0x8000 and 0x4000 as marks for DROP and SNAT, which we should also fix.

**Comment by joestringer** [comment]
Just wondering did you try at all to find an alternative value than `0x1500` for the `MARK_MAGIC_SNAT_DONE` feature? Like I'm not sure I follow why we need to check all three bits `0x1500` and why we couldn't for instance use `0x0500` (/cc @borkmann). If we're setting the two bits `0x0500` in the 4-bit range that we're using `0x0F00` it would otherwise plausibly overlap with decrypt (`0x0D00`) but we could tell it's not decrypt by the fact that the `0x0800` is not set.

In logic where there's things like this:

```
#define MARK_MAGIC_SNAT_DONE 0x1500
if ((ctx->mark & MARK_MAGIC_SNAT_DONE) != MARK_MAGIC_SNAT_DONE) {
```

I would anticipate using instead:

```
#define MARK_MAGIC_SNAT_DONE 0x0500
#define MARK_MAGIC_FEATURE_MASK 0x0F00
if ((ctx->mark & MARK_MAGIC_FEATURE_MASK) != MARK_MAGIC_SNAT_DONE) {
```

**Comment by joestringer** [comment]
Agree there's an upgrade concern here and I think @martin31821 is on point given that as-is this would shift from using bits at `0xF000` to using `0xE000` for the value, but today we do things like `keyIndex << 12`. 

> Do we support multiple version jumps I presume users going from 1.8->1.10 for example need to upgrade through 1.9 to have any expectation the upgrade system will guard them from breaking changes.

Yes we instruct users to go v1.8 -> v1.9 -> v1.10, with the latest version in a series before going to the next one (in case we need to do any compatibility fixups for upgrade in an older relaase).

Helm options could be explored but if we can get away with bitshuffling and no flags or actual move of the bits, that's even better.

Not sure how exactly we deal with overlap on 0x8000 vs. k8s today, if it works today then we shouldn't need to take any action. But if using key index 8 or larger today triggers that drop rule then clearly we should avoid that.

**Comment by brb** [comment]
> Just wondering did you try at all to find an alternative value than 0x1500 for the MARK_MAGIC_SNAT_DONE feature

The `MARK_MAGIC_SNAT_DONE` is used to avoid going through the SNAT engine twice when a request was sent to a NodePort service and a remote backend was selected. When the `from-netdev` attached at TC ingress receives such request, it selects the backend, does the SNAT, sets the mark, and then redirects the packet to the `to-netdev` attached at TC egress (potentially to the same device in the case of a single device). The `to-netdev` does the check for the mark.

@borkmann I'm wondering whether we could use any other skb field here (we don't depend on the mark in the case of XDP, as there is no skb and egress hook). E.g. `skb->priority` (we don't change netns, so no skb scrubbing?) or `skb->queue_mapping` (AFAIK EDT uses only 16bits, so 16bits left)?

**Comment by martin31821** [comment]
FWIW, I tried using 0x8500 for SNAT_DONE first, but that ended up with dropped traffic due to the KUBE-MARK-DROP chain, that's why I went with the changed shifts, though.
I'll try to rotate the ipsec keys to match KUBE-MARK-DROP and see if the traffic gets dropped.

**Comment by borkmann** [comment]
> @borkmann I'm wondering whether we could use any other skb field here (we don't depend on the mark in the case of XDP, as there is no skb and egress hook). E.g. `skb->priority` (we don't change netns, so no skb scrubbing?) or `skb->queue_mapping` (AFAIK EDT uses only 16bits, so 16bits left)?

queue_mapping is only 16 bit and all used up for EDT. The priority seems not preserved last time I checked, so we should probably use a per-CPU scratch map slot for transferring the info.

@jrfastab @martin31821 What is the expectation wrt services when ipsec is used? E.g. request arrives on one node, which then does SNAT to its own IP and forwards the request to final remote backend in the cluster.. is the expectation that this traffic is then encrypted, or do we expect to see unencrypted traffic for this case?

**Comment by martin31821** [comment]
> @jrfastab @martin31821 What is the expectation wrt services when ipsec is used? E.g. request arrives on one node, which then does SNAT to its own IP and forwards the request to final remote backend in the cluster.. is the expectation that this traffic is then encrypted, or do we expect to see unencrypted traffic for this case?

@borkmann I think, I'd like to see encrypted traffic in this scenario, i.e. connection from the internet to a NodePort service and a backing pod on another node. At the moment, we have xfrm policies for [Node CIDR -> All other Node CIDRs] in place, which means if the SNAT on such a service would translate to the IP address on cilium_host, then it will get encrypted, but if it gets the public IP address as source then it won't.

**Comment by martin31821** [comment]
@joestringer @brb: I tested the IPSec key rotation to keyID 7 to run into KUBE_MARK_DROP, but that traffic was catched by the CILIUM_* iptables chains and it worked fine, so from my side it's ready now.

Still need to decide how we want to proceed on the update problem, reducing the key space is mandatory, so maybe we should include a check in the preflight deployment which ensures all keys are within [0, 7]?

Also, could one of you take a look at the net-next failure? I don't think it's related to the changes here.

**Comment by joestringer** [comment]
> reducing the key space is mandatory,

I saw above that `0x8500` was attempted, but I didn't see that other values using the 0xF00 bits were tested, for instance `0x0500`. Are we sure that reducing the key space is mandatory at this point? If we don't have to reduce the space, then that will also resolve the update problem.

As for the net-next failure, the job logs have expired so I can re-kick the CI.

**Comment by joestringer** [comment]
retest-net-next

**Comment by martin31821** [comment]
I'll take a look whether 0x500 could work. The net-next seems to hit a timeout after 2h50m, causing the test to be aborted.

**Comment by joestringer** [comment]
Failure looks legitimate:

```
test/helpers/kubectl.go:667:38: too many arguments in call to kub.GetCiliumPods
	have (string)
	want ()
make[1]: *** [Makefile:444: govet] Error 2
```

**Comment by brb** [comment]
> Are we sure that reducing the key space is mandatory at this point?

We could use per-CPU scratch map to indicate `SNAT_DONE` as per @borkmann suggestion (https://github.com/cilium/cilium/pull/12985#issuecomment-683861698). That would allows us to get rid of the `MARK_MAGIC_SNAT_DONE`.

**Comment by martin31821** [comment]
@brb do you have some pointers for me to get started using those scratchmaps in the data path?

**Comment by brb** [comment]
> do you have some pointers for me to get started using those scratchmaps in the data path?

@martin31821 Grep for `cilium_xdp_scratch` in `bpf/include/ctx/xdp.h`.

**Comment by brb** [comment]
@martin31821 Are you still working on this?

**Pull request closed without merging**
