### PR TITLE
Revert "Update k8s tests and libraries to v1.27.0"

### PR DESCRIPTION
**Pull request by pchaigno**
Reverts https://github.com/cilium/cilium/pull/24837.

First two commits are reverts. Last one fixes the test reporting to GitHub.

### CODE REVIEW

**Review by nbusseneau — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.25-5.4

**Comment by pchaigno** [comment]
/test-1.27-net-next

**Review by zacharysarah — APPROVED** [review]
Docs rubberstamping to unblock

**Comment by pchaigno** [comment]
/test-1.26-net-next

**Comment by pchaigno** [comment]
/test-1.24-5.4

**Comment by pchaigno** [comment]
/test-1.25-4.19

**Review by christarazi — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.26-net-next

**Review by viktor-kurchenko — APPROVED** [review]

**Review by bimmlerd — APPROVED** [review]
contrib changes lgtm

**Comment by pchaigno** [comment]
/test-1.26-net-next

**Review by joamaki — APPROVED** [review]

**Review by youngnick — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.24-5.4

**Comment by pchaigno** [comment]
/test-1.26-net-next

**Comment by pchaigno** [comment]
/test-1.26-net-next

**Comment by pchaigno** [comment]
/test-1.25-4.19

**Comment by pchaigno** [comment]
/test-1.24-5.4

**Comment by pchaigno** [comment]
/test-1.26-net-next

**Comment by pchaigno** [comment]
/test-1.25-4.19

**Comment by pchaigno** [comment]
/test-1.24-5.4

**Comment by pchaigno** [comment]
k8s-1.26-kernel-net-next failed with known flake https://github.com/cilium/cilium/issues/24514. Other tests are passing except for the k8s-1.27-kernel-net-next job, but that one is expected: we just removed support for k8s 1.27.

@nbusseneau Ready to go!

**Pull request merged**
