### PR TITLE
[CI backport] Add jenkins stage for loading vagrant boxes

### PR DESCRIPTION
**Pull request by nebril**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8103)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12511/flowGraphTable/

**Comment by ianvernon** [comment]
test-me-please

**Comment by nebril** [comment]
Jenkins stage added succeeded, build failures are flakes, merging this to ease problems with other backports.

**Pull request merged**
