### PR TITLE
[v1.13] bugtool: Avoid sensitive data in envoy config dump

### PR DESCRIPTION
**Pull request by sayboras**

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.13

**Review by michi-covalent — APPROVED** [review]

**Comment by sayboras** [comment]
/test-backport-1.13

**Review by qmonnet — APPROVED** [review]

**Comment by sayboras** [comment]
/test-backport-1.13

**Comment by qmonnet** [comment]
```
20:03:21  FAIL: Failed to run privileged unit tests
20:03:21  Expected command: bash -c 'sudo make -C /home/vagrant/go/src/github.com/cilium/cilium/ tests-privileged NO_COLOR=1 | ts "[%H:%M:%S]"; exit "${PIPESTATUS[0]}"' 
20:03:21  To succeed, but it failed:
20:03:21  Exitcode: 2 
20:03:21  Err: Process exited with status 2
20:03:21  Stdout:
20:03:21   	 [19:03:05] make: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium'
20:03:21  	 [19:03:13] PRIVILEGED_TESTS=true PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/vagrant/go/src/github.com/cilium/cilium/bpf CGO_ENABLED=0 go test  -mod=vendor -vet=all -tags=osusergo -ldflags "-X github.com/cilium/cilium/pkg/kvstore.consulDummyAddress=https://consul:8443/ -X github.com/cilium/cilium/pkg/kvstore.etcdDummyAddress=http://etcd:4002/ -X github.com/cilium/cilium/pkg/datapath.DatapathSHA256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" \
20:03:21  	 [19:03:13] 	./... -test.v -timeout 600s  -json -covermode=count -coverprofile=coverage.out | tparse -follow
20:03:21  	 [19:03:19] make: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium'
20:03:21  	 
20:03:21  Stderr:
20:03:21   	 bugtool/cmd/mask.go:8:2: package slices is not in GOROOT (/usr/local/go/src/slices)
20:03:21  	 no parseable events: Make sure to run go test with -json flag
20:03:21  	 make: *** [Makefile:115: tests-privileged] Error 1
```

**Comment by qmonnet** [comment]
I added the following change to the first commit:

```diff
diff --git a/bugtool/cmd/mask.go b/bugtool/cmd/mask.go
index 4a6a32961d03..77847895d503 100644
--- a/bugtool/cmd/mask.go
+++ b/bugtool/cmd/mask.go
@@ -5,7 +5,6 @@ package cmd
 
 import (
        "encoding/json"
-       "slices"
 )
 
 const (
@@ -34,9 +33,18 @@ func maskFields(b []byte, fieldNames []string) ([]byte, error) {
        return json.MarshalIndent(data, "", ident)
 }
 
+func contains(names []string, name string) bool {
+       for _, n := range names {
+               if n == name {
+                       return true
+               }
+       }
+       return false
+}
+
 func mask(data map[string]interface{}, fieldNames []string) {
        for k, v := range data {
-               if slices.Contains(fieldNames, k) {
+               if contains(fieldNames, k) {
                        data[k] = redacted
                        continue
                }
```

**Comment by qmonnet** [comment]
/test-backport-1.13

**Review by michi-covalent — APPROVED** [review]

**Comment by qmonnet** [comment]
/test-1.21-4.19

**Comment by sayboras** [comment]
/test-1.19-4.19

**Pull request merged**
