### PR TITLE
v1.10: Update Go to 1.16.7

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Comment by tklauser** [comment]
test-backport-1.10

**Review by nebril — APPROVED** [review]

**Comment by tklauser** [comment]
test-1.21-4.9

**Comment by tklauser** [comment]
ConformanceEKS failed due to known issue #17139 which was fixed in #17140. It looks like we need to backport that PR (and #17143 pinning cilium-cli to 0.8.6) into v1.10, though. I'll take care of that as a follow-up.

All other tests passed, merging this PR.

**Pull request merged**
