### PR TITLE
Documentation: Add unit testing documenation to contributing guide

### PR DESCRIPTION
**Pull request by tgraf**

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by joestringer** [comment]
LGTM. Do you think it's worth documenting the `watchtest` function too? Example below.

```
Unit testing in a tight loop
~~~

The script ``contrib/shell/test.sh`` contains some helpful bash functions to improve the feedback cycle between writing tests and seeing their results. If you're writing unit tests in a particular package, the ``watchtest`` function will watch for changes in a directory and run the unit tests for that package any time the files change. For example, if writing unit tests in `pkg/policy`, run this in a terminal next to your editor:

.. code:: bash

    $ . contrib/shell/test.sh
    $ watchtest pkg/policy

This shell script depends on the ``inotify-tools`` package on Linux.

```

https://github.com/cilium/cilium/blob/6ee0e2620469317e18fb1833e94ca933b19b2146/contrib/shell/test.sh#L53-L56

**Comment by joestringer** [comment]
Just realised that `make tests` launches the envoy tests as well... maybe we should have a separate make target to allow unit tests to be run and document it in these docs?

**Comment by tgraf** [comment]
> LGTM. Do you think it's worth documenting the watchtest function too? Example below.

Done.

> Just realised that make tests launches the envoy tests as well... maybe we should have a separate make target to allow unit tests to be run and document it in these docs?

Not opposed to it. Let's do in a separate PR to keep this a doc only change.

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
