### PR TITLE
Ginkgo: Add segmentation fault check on `ValidateErrorsOnLogs`

### PR DESCRIPTION
**Pull request by eloycoto**
Add new assert to validate that Envoy didn't crash.

Related #3233

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
It works: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/1705/testReport/junit/(root)/runtime/RuntimeValidatedMonitorTest_With_Sample_Containers_Cilium_monitor_verbose_mode/

```
  Mar 28 11:14:10 runtime cilium-agent[15563]: level=debug msg="endpoint IP cache Delete" cached-identity=0 endpoint-ip=10.15.201.245 identity=51862
    Mar 28 11:14:10 runtime cilium-agent[15563]: level=debug msg="Queueing container event" containerID=4cd15e905a event=destroy subsys=containerd-watcher
    Mar 28 11:14:10 runtime cilium-agent[15563]: level=debug msg="Processing event for Container" containerID=4cd15e905a event=destroy subsys=containerd-watcher
    Mar 28 11:14:10 runtime cilium-agent[15563]: level=info msg="Envoy: Closing access log connection"
    Mar 28 11:14:10 runtime cilium-agent[15563]: level=error msg="error while receiving request from xDS stream" error="rpc error: code = 1 desc = context canceled" xdsStreamID=2
    Mar 28 11:14:10 runtime cilium-agent[15563]: level=error msg="xDS stream context canceled" error="context canceled" xdsStreamID=1
    Mar 28 11:14:10 runtime cilium-agent[15563]: level=warning msg="Envoy: Proxy crashed" error="signal: segmentation fault (core dumped)"
    Mar 28 11:14:10 runtime cilium-agent[15563]: level=error msg="error while receiving request from xDS stream" error="rpc error: code = 1 desc = context canceled" xdsStreamID=1
    Mar 28 11:14:10 runtime cilium-agent[15563]: level=info msg="xDS stream closed" xdsStreamID=2
    Mar 28 11:14:10 runtime cilium-agent[15563]: level=debug msg="Envoy: Started proxy"
    Mar 28 11:14:10 runtime cilium-agent[15563]: level=info msg="Envoy: Proxy started with pid 15434"
    Mar 28 11:14:10 runtime cilium-agent[15563]: level=info msg="Envoy: Sleeping for 100ms before restarting proxy"
    Mar 28 11:14:10 runtime cilium-agent[15563]: level=info msg="starting xDS stream processing" xdsStreamID=3
    Mar 28 11:14:10 runtime cilium-agent[15563]: level=debug msg="received request from xDS stream" xdsClientNode="id:\"host~127.0.0.1~no-id~localdomain\" cluster:\"cluster1\" build_version:\"a00e54c5397e24f1fdaf37da7a72fe501b8e61f9/1.7.0-dev/Modified/RELEASE\" " xdsNonce= xdsStreamID=3 xdsTypeURL=type.googleapis.com/envoy.api.v2.Listener xdsVersionInfo=
```

**Comment by ianvernon** [comment]
I don't think we should make an assertion about segmentation faults because it might block the CI due to spurious failures that aren't even caused by our Envoy filters (i.e., it could be an issue with Envoy itself). I think printing a huge warning on console is best for now that is visible to users on Jenkins. It'd be nice if we could dump these warnings at the end of each suite (Runtime, K8s, etc.), i.e. 
```
=================================================================
==
==
==
== SEGMENTATION FAULT FOUND IN ENVOY - PLEASE DEBUG IF POSSIBLE
==
==
==
=================================================================
```

This will not fail the tests, but will make it very apparent to users that something happened which shouldn't. Once we *do* find the reason behind the segmentation faults that are currently occurring, we can re-add the assertion as you have done with your initial patch here. What do you think?

cc: @jrajahalme @rlenglet

**Comment by eloycoto** [comment]
@ianvernon I'll hold this until end of the week, I remember that in the past I used something that set the Build as warning, but test continue to mark as green (I do not remember the plugin name) .

**Comment by rlenglet** [comment]
I'd love to make this fail the build. Those warnings will be mostly ignored. But we should do that only after we at least start collecting Envoy logs, or even better after we run a debug build of Envoy so we can get good tracebacks.
I'll work on including the logs in the Cilium logs ASAP.

**Review by rlenglet — APPROVED** [review]

**Comment by eloycoto** [comment]
@rlenglet ok

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@rlenglet can I merge this?

**Comment by rlenglet** [comment]
Yes. We have Envoy debug logs in Cilium debug logs now. That should be enough to give us a clue why it segfaults.

**Comment by jrajahalme** [comment]
@eloycoto We need this, but for the logs to be useful we'd need `--debug-verbose=flow` in addition to `--debug`, but then logs are very verbose.

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
@jrajahalme  is already in there https://github.com/cilium/cilium/blob/master/test/helpers/cilium.go#L752

**Comment by ianvernon** [comment]
Tests failed, but that shows that the logic in this PR is correct, because they discovered a core dump: 

```
11:22:31 
11:22:31     Found a "segmentation fault" in Cilium logs
11:22:31     Expected
...
11:22:31         2018-04-06T11:21:25.030765148Z level=info msg="Imported CiliumNetworkPolicy" ciliumNetworkPolicyName=rule-to-services k8sApiVersion= k8sNamespace=default
11:22:31         2018-04-06T11:21:25.21740674Z level=error msg="error while receiving request from xDS stream" error="rpc error: code = 1 desc = context canceled" xdsStreamID=3
11:22:31         2018-04-06T11:21:25.217773488Z level=warning msg="Envoy: Proxy crashed" error="signal: segmentation fault (core dumped)"
11:22:31         2018-04-06T11:21:25.217834813Z level=error msg="error while receiving request from xDS stream" error="rpc error: code = 1 desc = context canceled" xdsStreamID=1
11:22:31         2018-04-06T11:21:25.217840345Z level=info msg="Envoy: Closing access log connection"
11:22:31         2018-04-06T11:21:25.217854741Z level=error msg="xDS stream context canceled" error="context canceled" xdsStreamID=1
11:22:31         2018-04-06T11:21:25.217869671Z level=error msg="error while receiving request from xDS stream" error="rpc error: code = 1 desc = context canceled" xdsStreamID=2
11:22:31         2018-04-06T11:21:25.217873174Z level=error msg="xDS stream context canceled" error="context canceled" xdsStreamID=2
11:22:31         2018-04-06T11:21:25.21788611Z level=error msg="xDS stream context canceled" error="context canceled" xdsStreamID=3
11:22:31         2018-04-06T11:21:25.227322504Z level=info msg="Envoy: Proxy started with pid 5882"
11:22:31         2018-04-06T11:21:25.227377975Z level=info msg="Envoy: Sleeping for 100ms before restarting proxy"
...
11:22:31         
11:22:31     not to contain substring
11:22:31         <string>: segmentation fault
11:22:31 
```

But, we still don't gather the core. We should not merge this until we gather the core dump; otherwise the build will fail and we'll have nothing to debug.

**Comment by eloycoto** [comment]
@ianvernon Some changes are waiting in the packer-ci-build related with the cores: 
https://github.com/cilium/packer-ci-build/pull/43

**Comment by eloycoto** [comment]
As @ianvernon mention, the PR #3683 was merged into this PR and now is part of this PR to have all in the same PR.

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
Fix #3399
Needs to wait until: PR #3354

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by ianvernon** [comment]
@eloycoto we will need a way to get the core dump from the Cilium pods, as the core dump logic is only available for the runtime tests right now. The tests found a core dump, but there is no core to debug. For this to be merged, we need corresponding logic for gathering logs from Cilium pods as well.

```
13:42:45     Found a "segmentation fault" in Cilium logs
13:42:45     Expected
13:42:45         <string>: 2018-04-16T13:42:44.362530083Z level=error msg="xDS stream context canceled" error="context canceled" xdsStreamID=1
13:42:45         2018-04-16T13:42:44.362627557Z level=info msg="Envoy: Closing access log connection"
13:42:45         2018-04-16T13:42:44.362791762Z level=warning msg="Envoy: Proxy crashed" error="signal: segmentation fault (core dumped)"
13:42:45         2018-04-16T13:42:44.362990557Z level=error msg="error while receiving request from xDS stream" error="rpc error: code = 1 desc = context canceled" xdsStreamID=1
13:42:45         2018-04-16T13:42:44.362996955Z level=error msg="xDS stream context canceled" error="context canceled" xdsStreamID=2
13:42:45         2018-04-16T13:42:44.363048418Z level=error msg="error while receiving request from xDS stream" error="rpc error: code = 1 desc = context canceled" xdsStreamID=2
13:42:45         2018-04-16T13:42:44.363057869Z level=error msg="xDS stream context canceled" error="context canceled" xdsStreamID=3
13:42:45         2018-04-16T13:42:44.367300634Z level=info msg="Envoy: Proxy started with pid 3530"
13:42:45         2018-04-16T13:42:44.36731808Z level=info msg="Envoy: Sleeping for 100ms before restarting proxy"
13:42:45         2018-04-16T13:42:44.374432428Z level=info msg="starting xDS stream processing" xdsStreamID=4
13:42:45         2018-04-16T13:42:25.548416607Z level=info msg="Policy imported via API, recalculating..." policyRevision=39
13:42:45         2018-04-16T13:42:25.548480341Z level=info msg="Imported CiliumNetworkPolicy" ciliumNetworkPolicyName=rule-to-services k8sApiVersion= k8sNamespace=default
13:42:45         2018-04-16T13:42:44.138108875Z level=info msg="Deleted CiliumNetworkPolicy" ciliumNetworkPolicyName=rule-to-services k8sApiVersion= k8sNamespace=default
13:42:45         
13:42:45     not to contain substring
13:42:45         <string>: segmentation fault
13:42:45 
13:42:45     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Services.go:71
```

No dump in logs:
```
Ians-MBP:K8sValidatedServicesTestExternalservicesToServicesfirstpolicy,matchservicebylabels ianvernon$ ls
cmds.log	test-output.log
```

**Review by ianvernon — CHANGES_REQUESTED** [review]
Needs gathering of core dumps from K8s Cilium pods.

**Comment by eloycoto** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]
@eloycoto overall changes look great. I'd like to run this PR a few more times to see if we hit another segmentation fault (since they seem fairly common) and if the logs are gathered accordingly before merging.

**Comment by eloycoto** [comment]
test-me-please

**Comment by jrajahalme** [comment]
@eloycoto  It would be really nice to have this merged as soon as possible so that I would have something to debug the segfaults with.

**Comment by jrajahalme** [comment]
I tried the newer box versions locally and found that the core dump pattern was not set when I logged into the VM started by ginkgo for the runtime tests. I have to apply this:
```
sudo sysctl -w kernel.core_pattern=/tmp/core.%e.%p.%t
```

Maybe this needs to be added to test/provision/compile.sh to make sure it is set correctly?

**Comment by ianvernon** [comment]
@jrajahalme I'm okay with merging this, *but* I do not want the build to fail if a segfault occurs. This will grind our CI to a halt because this failure occurs fairly frequently. So, I'd like to remove the assertion on whether there are segfaults in the logs, and instead add a warning in the mean time. Once the segmentation fault issue is fixed, then we can enable the assertion to ensure we do not regress again. Does this sound reasonable? cc: @eloycoto

**Comment by eloycoto** [comment]
@jrajahalme is already in the newer images: https://github.com/cilium/packer-ci-build/blob/master/provision/ubuntu/install.sh#L160

@ianvernon  ATM we need to merge the monitor first https://github.com/cilium/cilium/pull/3354. Instead of having a invalid log, I'm happy to merge this to another branch, added in the Jenkins job that run every two hours and Jarno can triage when it fails. As soon is it stable can be merged in master. sounds like a plan?

**Comment by jrajahalme** [comment]
@eloycoto @ianvernon Now that we have fixed known segfaults, IMO it would be good time to make CI runs fail on any observed segfaults. We can always temporarily disable flaky tests if such appear in the future.

**Comment by eloycoto** [comment]
@jrajahalme I've just rebase ;-)

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Pull request merged**
