### PR TITLE
mod: bump cilium/ebpf to v0.10.0

### PR DESCRIPTION
**Pull request by ldelossa**
this commit beats dependabot to the punch and updates cilium/ebpf to v0.10.0.

Signed-off-by: Louis DeLosSantos <louis.delos@isovalent.com>

```release-note
Bump cilium/ebpf to v0.10.0
```

### CODE REVIEW

**Review by joestringer — APPROVED** [review]
Thanks!

**Comment by ldelossa** [comment]
Hmm travis is legit:

```
vendor/github.com/cilium/coverbee/instrumentation.go:161:34: coll.Programs[name].BTF undefined (type *ebpf.ProgramSpec has no field or method BTF)

vendor/github.com/cilium/coverbee/instrumentation.go:350:23: coll.Programs[name].BTF undefined (type *ebpf.ProgramSpec has no field or method BTF)

make[1]: *** [Makefile:429: govet] Error 2

make: *** [Makefile:175: integration-tests] Error 2
````

We dont see that in a normal `go build./...` let me seeeeeeee.

**Comment by ldelossa** [comment]
Look like we'll need to bump the ebpf package in coverbee as well.

**Comment by ti-mo** [comment]
@ldelossa Coverbee needs to be updated to work with 0.10, I don't think master is compatible yet. I'll see if I can help out there.

cc @dylandreimerink

**Comment by ti-mo** [comment]
Coverbee fix pending in https://github.com/cilium/coverbee/pull/4, I'll rebase this PR when coverbee has been bumped on master.

**Comment by ldelossa** [comment]
Sounds good @ti-mo.

**Review by rolinh — APPROVED** [review]

**Comment by rolinh** [comment]
It looks like #23212 supersedes this PR by bumping both cilium/ebpf and coverbee. Should we close this one instead?

**Comment by dylandreimerink** [comment]
I think it would be cleaner to merge this PR since we have move context here. I will rebase #23212 after that so it contains only the CoverBee update.

**Comment by ti-mo** [comment]
Fine by me, but master (well, just tests really) will be broken in between merging this one and #23212. Looks like many are already broken due to image builds not working anyway.

**Review by ti-mo — APPROVED** [review]

**Pull request closed without merging**
