### PR TITLE
v1.7 backports 2020-06-12

### PR DESCRIPTION
**Pull request by jrfastab**
* #12015 -- cilium: fix encryption flow labels in ip6 case (@jrfastab)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12015; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.7

**Review by aanm — APPROVED** [review]

**Comment by jrfastab** [comment]
test-backport-1.7

**Comment by jrfastab** [comment]
pushed bindata update.

**Comment by aanm** [comment]
test-missed-k8s

**Review by tgraf — APPROVED** [review]

**Pull request merged**
