### PR TITLE
v1.14: Upgrade GoBGP to v3.23.0 and backport #28293

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
This PR combines GoBGP upgrade and the backport of https://github.com/cilium/cilium/pull/28293 together solves the GR hanging issue https://github.com/cilium/cilium/issues/30367.

```release-note
Upgrade GoBGP to v3.23.0 and backport #28293
```

### CODE REVIEW

**Comment by YutaroHayakawa** [comment]
/test-backport-1.14

**Comment by YutaroHayakawa** [comment]
Conformance E2E: https://github.com/cilium/cilium/issues/30745

**Review by ldelossa — APPROVED** [review]

**Review by youngnick — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
/test-backport-1.14

**Comment by YutaroHayakawa** [comment]
Cilium IPsec upgrade: https://github.com/cilium/cilium/issues/29987
Conformance Cluster Mesh: https://github.com/cilium/cilium/issues/22749

**Pull request merged**
