### PR TITLE
bpf: Remove HAVE_L4_POLICY

### PR DESCRIPTION
**Pull request by joestringer**
Based on #5321.

Remove `HAVE_L4_POLICY` from the datapath to reduce variations in possible compiled datapath programs.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5332)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by joestringer** [comment]
Green build. Rebasing against latest #5321.

**Review by borkmann — APPROVED** [review]

**Comment by ianvernon** [comment]
Needs rebase after #5321 was merged.

**Comment by joestringer** [comment]
test-me-please

**Comment by tgraf** [comment]
CI hit a new bug, unrelated to this change though. When agent is restarted while waiting for policy revision to be reached, the revision is reset and won't be reached.

https://github.com/cilium/cilium/issues/5355

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
@joestringer did you intend to remove 'pending-review'?

**Comment by joestringer** [comment]
@ianvernon yes, it's just pending a green build right?

**Pull request merged**
