### PR TITLE
v1.0 backports 2018-04-18

### PR DESCRIPTION
**Pull request by jrajahalme**
Stable backports as of 2018-04-18.

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by tgraf** [comment]
I assume `ipcache: Shift NPHDS logic to envoy` is a dependency of one of the backports. We should try to aim avoiding backporting non fixes like this in the future. I think it's safe in this case.

**Review by tgraf — APPROVED** [review]

**Comment by joestringer** [comment]
@tgraf agreed, but the alternative in this case would have involved duplicating all of that logic. I don't think there was a better way to achieve this fix without that refactor.

**Review by ianvernon — APPROVED** [review]

**Comment by joestringer** [comment]
Before we merge this, I would suggest holding a bit longer for us to further verify the NPHDS changes on master.

**Comment by joestringer** [comment]
I checked it again, LGTM.

**Pull request merged**
