### PR TITLE
ci/ipsec: Fix downgrade version for release preparation commits

### PR DESCRIPTION
**Pull request by qmonnet**
For the IPsec upgrade/downgrade CI test, for the jobs where we upgrade/downgrade to the closest patch release, the script print-downgrade-version.sh determines the patch release by picking up the value in file VERSION. This works most of the time.

For release preparation commits, however, this approach fails because the reference in VERSION points to a release that has not been tagged or published yet. We need to pick the previous patch release in that case.

However, it's non-trivial to figure out whether we're on a release preparation commit, in particular because the CI workflow does a shallow Git clone and we don't have access to the Git history. I couldn't find an ideal solution, so this commit changes the shallow-clone into a clone with 2 commits (one for the last commit, which is the one we're interested in, and another one squashing all the rest of the history). And we add a hack in the script to account for this last commit and check whether it modifies the VERSION file. If it does, we decrement the version found in VERSION before computing the patch release to downgrade to.

Fixes: 5581963cbf94 ("ci/ipsec: Fix version retrieval for downgrades to closest patch release")

### CODE REVIEW

**Comment by julianwiedmann** [comment]
Just to brain-storm on less-hacky alternatives a bit more. Would a checkout with `fetch-tags: true` help us? And instead of comparing `VERSION`, testing whether the expected tag exists?

**Review by pchaigno — APPROVED** [review]

**Comment by michi-covalent** [comment]
are we still doing v1.12 releases or can we remove `needs-backport/v1.12` label?

**Comment by qmonnet** [comment]
> are we still doing v1.12 releases or can we remove `needs-backport/v1.12` label?

@michi-covalent I've heard they might be a last v1.12 release. It's not necessary to have this change backported there, though.

**Review by michi-covalent — APPROVED** [review]

**Comment by michi-covalent** [comment]
`Conformance Gateway API` got renamed to `Conformance Gateway API (ci-gateway-api)`, and it passed. added `dont-merge/waiting-for-review` label since quentin specifically asked for a review from julian. @julianwiedmann could you take a look? we are trying to include this in this month's patch releases which are supposed to go out on 15th 🚀 🙏

**Comment by qmonnet** [comment]
```console
$ for i in 1.14.3 1.14.1 1.14.0 1.14.1-dev 1.15.0-dev 1.13.90 2.0.1 2.0.2; do \
    printf "%-12s %-12s %-12s\n" \
        "$i" \
        "$(VERSION=$i ./contrib/scripts/print-downgrade-version.sh)" \
        "$(VERSION=$i ./contrib/scripts/print-downgrade-version.sh  patch)"; done 2>/dev/null
1.14.3       v1.13        v1.14.3     
1.14.1       v1.13        v1.14.1     
1.14.0       v1.13                    
1.14.1-dev   v1.13        v1.14.1     
1.15.0-dev   v1.14                    
1.13.90      v1.12        v1.13.89    
2.0.1                     v2.0.0      
2.0.2                     v2.0.1
```

We get the patch release number decremented for 1.13.90, 2.0.1, 2.0.2 for which the tag does not exist in the repo - this is what we want.

**Comment by qmonnet** [comment]
Ha! So as it turns out, `fetch-tags: true` doesn't work with `fetch-depth: 0`, we don't retrieve any tags (presumably because we don't have the commits to associate them with). I'll send a fix to the fix to the fix :upside_down_face:, switch back to the `VERSION`-update based check.

**Pull request merged**
