### PR TITLE
eni node_manager unit test improvements

### PR DESCRIPTION
**Pull request by jaffcheng**
Signed-off-by: Jaff Cheng <jaff.cheng.sh@gmail.com>

I'll send some follow up PRs to add mockup for ipam crdAllocator soon

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9756)

### CODE REVIEW

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Review by aanm — COMMENTED** [review]
@jaffcheng the PR needs to be rebased against master

**Comment by jaffcheng** [comment]
I'll rebase it later today

**Comment by jaffcheng** [comment]
@ungureanuvladvictor @aanm please take another look

**Comment by aanm** [comment]
test-me-please

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
@jaffcheng can you please rebase against master? Thank you!

**Comment by jaffcheng** [comment]
@aanm Rebased, please take a look

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
