### PR TITLE
modules: Load modules with finit_module syscall

### PR DESCRIPTION
**Pull request by vadorovsky**
This PR is a follow up to #7820 and recent discussions about loading kernel modules.

For now we are using `modprobe` and we started shipping it in Cilium images. This pull requests aims to replace `modprobe` with `finit_module` system call which allows to load kernel modules programmatically. The goal is to not depend on the external binary.

Please review per commit.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7838)

### CODE REVIEW

**Comment by vadorovsky** [comment]
test-me-please

**Review by brb — COMMENTED** [review]
> The benefit of this change is lack of need to rely on the external binary or need of shipping it in container images.

Doesn't `iptables` internally call `modprobe`?

**Comment by mrostecki** [comment]
> Doesn't `iptables` internally call `modprobe`?

Yes, true. I will remove that part of description.

**Comment by vadorovsky** [comment]
> > The benefit of this change is lack of need to rely on the external binary or need of shipping it in container images.
> 
> Doesn't `iptables` internally call `modprobe`?

True. I will remove that part of description.

**Pull request closed without merging**
