### PR TITLE
envoy: Bump envoy minor version to 1.30.x

### PR DESCRIPTION
**Pull request by sayboras**
Relates: https://github.com/cilium/proxy/pull/831

### CODE REVIEW

**Review by youngnick — APPROVED** [review]

**Review by marseel — APPROVED** [review]

**Review by viktor-kurchenko — APPROVED** [review]

**Review by squeed — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]
the build team gladly approves this pull request.

**Pull request merged**
