### PR TITLE
LB refactoring leftovers

### PR DESCRIPTION
**Pull request by brb**
This PR resolves some LB refactoring leftovers. Mostly changes in naming (except for the API field change, `loadbalancer.SVC` type cleanup and `lbmap.DumpServiceMaps()` simplification).

Reviewable per commit (highly recommended).

```release-minor
API: "node-port" field was replaced with "type" in "ServiceSpec".
```

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9320)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Review by borkmann — APPROVED** [review]
Still needs a rebase due to bpf.sha, but otherwise lgtm.

**Comment by brb** [comment]
test-me-please

**Pull request merged**
