### PR TITLE
[v1.13] Update CNI to 1.3.0

### PR DESCRIPTION
**Pull request by thorn3r**
v1.13 backports 2023-05-12

 - [ ] #25400 -- Update CNI to 1.3.0 (@anfernee)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 25400; do contrib/backporting/set-labels.py $pr done 1.13; done
```

### CODE REVIEW

**Comment by joestringer** [comment]
When doing manual backports of PRs, please follow https://docs.cilium.io/en/v1.13/contributing/release/backports/#via-github-web-interface - this ensures that the release notes properly pick up the related changes.

**Comment by joestringer** [comment]
@thorn3r The CI trigger doesn't seem like it has taken effect, I don't see the `Details` link beside the various ginkgo jobs :thinking: Maybe try once more?

**Comment by thorn3r** [comment]
@joestringer trying again :crossed_fingers:

**Comment by joestringer** [comment]
That's weird, the GitHub action based workflows seemed to trigger, but the jenkins+ginkgo ones did not.

**Comment by joestringer** [comment]
/test-backport-1.13

**Comment by joestringer** [comment]
They triggered when I ran it, so there must be something about your user that's not configured right in the Cilium CI systems. Worth following up with the testing folks to find out why that's the case. You're an org member (part of the `Team` team), so I assumed you should be able to trigger those workflows.

**Comment by thorn3r** [comment]
/ci-gke-1.13

**Comment by thorn3r** [comment]
/test-1.16-4.19

**Comment by thorn3r** [comment]
/test-1.25-4.19

**Comment by thorn3r** [comment]
k8s-1.25-kernel-4.19 (test-1.25-4.19) looks related to this flake: [K8sVerifier Runs the kernel verifier against Cilium's BPF datapath](https://github.com/cilium/cilium/issues/20763). re-running

**Comment by thorn3r** [comment]
/test-1.25-4.19

**Comment by thorn3r** [comment]
failure for k8s-1.25-kernel-4.19 (test-1.25-4.19) looks like it could be related to https://github.com/cilium/cilium/issues/22749

**Comment by asauber** [comment]
/test-1.20-4.19

**Comment by aditighag** [comment]
/test-1.25-4.19

**Review by aanm — APPROVED** [review]

**Pull request merged**
