### PR TITLE
test: Delete Istio resources if install does not complete

### PR DESCRIPTION
**Pull request by jrajahalme**
If Istio install fails (e.g., times out) during BeforeAll(), the
resource cleanups in AfterAll() are not performed, so have to clean up
explicitly after failure in BeforeAll instead.

Without this some Istio resources may be left behind, causing other
tests to fail due to unexpected pods being present.

Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]

**Comment by jrajahalme** [comment]
test-1.21-4.9 experienced a flake like #11867 and a new test panic tracked in #16480

**Comment by jrajahalme** [comment]
test-1.21-4.9
Previous run failed due to text at the end of the first line not being recognized as valid arguments:
```
13:12:08  get-gh-comment-info.py: error: unrecognized arguments: experienced a flake like
```

**Comment by jrajahalme** [comment]
test-1.21-4.9
cluster provisioning failed

**Comment by jrajahalme** [comment]
test-1.21-4.9
vm provisioning fail

**Comment by jrajahalme** [comment]
test-1.21-4.9
vm provisioning fail

**Comment by jrajahalme** [comment]
@nebril Do I need to rebase to get the CI to provision a VM?

**Comment by nebril** [comment]
@jrajahalme  I don't think so, this provisioning issue seems different then NFS ones that we were hitting.

**Comment by nebril** [comment]
Looks like env vars were not being set properly because of `vm provisioning fail` bit of trigger comments: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/763/execution/node/45/log/

**Comment by nebril** [comment]
test-1.21-4.9

**Comment by jrajahalme** [comment]
This PR only changes a CI 2.0 (Ginkgo) and all Ginkgo CI runs passed. Marking this ready-to-merge.

**Pull request merged**
