### PR TITLE
helm: bump hubble-ui patch version in chart values

### PR DESCRIPTION
**Pull request by genbit**
Use v0.7.2 by default for hubble-ui

### CODE REVIEW

**Comment by joestringer** [comment]
One of the failures is looking for you to run `make -C install/kubernetes` to update the experimental-install.yaml.

**Review by gandro — APPROVED** [review]
As already stated, the experiment install YAML to be re-generated and the sign-off in the commit, but otherwise LGTM!

**Review by sayboras — APPROVED** [review]
💯 for releasing the underlying fix 💯

**Review by christarazi — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@genbit you need to fix the related failures.

**Comment by genbit** [comment]
@aanm done

**Comment by gandro** [comment]
@genbit You still need to add the `Signed-off-By` message to your commit message

**Review by christarazi — APPROVED** [review]

**Comment by genbit** [comment]
@gandro and here I go, using GitHub UI to commit into cilium was not good idea 🤦

**Review by rolinh — APPROVED** [review]

**Pull request merged**
