### PR TITLE
Fix misclassification of traffic SNATed to host device as "cluster" rather than "world"

### PR DESCRIPTION
**Pull request by joestringer**
Update the netdev ipcache lookup to ignore the ipcache identity if it identifies the source as cluster. This avoids breaking ingress identity lookup compared to Cilium 1.1 or earlier.

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4885)

### CODE REVIEW

**Comment by tgraf** [comment]
@joestringer Feel free to merge this over #4881

**Review by tgraf — APPROVED** [review]

**Comment by joestringer** [comment]
@tgraf rebased on yours.

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by joestringer** [comment]
Green build. Rebasing.

**Pull request merged**
