### PR TITLE
Backports for v1.1 18-07-11

### PR DESCRIPTION
**Pull request by ianvernon**
PR's:

#4764  (had conflicts, resolved side-by-side with original PR filer @rlenglet )
#4809 (no conflicts)
#4812 (no conflicts)

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4827)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by ianvernon** [comment]
Don't know how, but the cmdref got out of sync in the v1.1 branch? Will fix soon...

EDIT: this was because the cmdref was regenerated as part of the sidecar-proxy regex changes. I had to regenerate the cmdref for that commit. Should be good now... retriggering tests.

**Review by rlenglet — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure:
```
01:46:21   Cilium DS cannot be deleted
01:46:21   Expected command: kubectl delete ds -n kube-system cilium 
01:46:21   To succeed, but it failed:
01:46:21   Exitcode: 1 
01:46:21   Stdout:
01:46:21    	 
01:46:21   Stderr:
01:46:21    	 error: timed out waiting for the condition
```

Link: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4882/execution/node/75/log/

Trying again...

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure in upgrade test :/  https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4905/

Trying again...

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Another failure :( https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4909/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Recent failure appears to show that Cilium gets into a bad state:

```
stderr:
Error: Cannot get policy: context deadline exceeded
```

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4911/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Next build failed, and logs are littered with errors for endpoint regeneration:
```
2018-07-13T03:26:16.285061323Z level=error msg="destroying BPF maps due toerrors during regeneration" containerID=c83aa8ebd5 endpointID=9882 error="error: \"exit status 1\" command output: \"Join EP id=/var/run/cilium/state/9882_next ifname=lxcc83aa\\nkernel version:  Linux k8s2 4.9.17-040917-generic #201703220831 SMP Wed Mar 22 12:33:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux\\nclang version:  clang version 3.8.1 (tags/RELEASE_381/final) Target: x86_64-unknown-linux-gnu Thread model: posix InstalledDir: /usr/local/clang+llvm/bin\\n'probe' is not a recognized processor for this target (ignoring processor)\\n'probe' is not a recognized processor for this target (ignoring processor)\\n'probe' is not a recognized processor for this target (ignoring processor)\\n'probe' is not a recognized processor for this target (ignoring processor)\\nCannot find device \\\"lxcc83aa\\\"\\nCannot find device \\\"lxcc83aa\\\"\\n\"" ipv4=10.10.1.179 ipv6="f00d::a0a:100:0:269a" k8sPodName="default:deathstar-3567858499-7bglr" policyRevision=0
2018-07-13T03:26:16.285094118Z level=warning msg="Regeneration of endpoint program failed" containerID=c83aa8ebd5 endpointID=9882 error="error: \"exit status 1\" command output: \"Join EP id=/var/run/cilium/state/9882_next ifname=lxcc83aa\\nkernel version:  Linux k8s2 4.9.17-040917-generic #201703220831 SMP Wed Mar 22 12:33:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux\\nclang version:  clang version 3.8.1 (tags/RELEASE_381/final) Target: x86_64-unknown-linux-gnu Thread model: posix InstalledDir: /usr/local/clang+llvm/bin\\n'probe' is not a recognized processor for this target (ignoring processor)\\n'probe' is not a recognized processor for this target (ignoring processor)\\n'probe' is not a recognized processor for this target (ignoring processor)\\n'probe' is not a recognized processor for this target (ignoring processor)\\nCannot find device \\\"lxcc83aa\\\"\\nCannot find device \\\"lxcc83aa\\\"\\n\"" ipv4=10.10.1.179 ipv6="f00d::a0a:100:0:269a" k8sPodName=":" policyRevision=0
2018-07-13T03:26:16.285099351Z level=debug msg="Error regenerating endpoint: error: \"exit status 1\" command output: \"Join EP id=/var/run/cilium/state/9882_next ifname=lxcc83aa\\nkernel version:  Linux k8s2 4.9.17-040917-generic #201703220831 SMP Wed Mar 22 12:33:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux\\nclang version:  clang version 3.8.1 (tags/RELEASE_381/final) Target: x86_64-unknown-linux-gnu Thread model: posix InstalledDir: /usr/local/clang+llvm/bin\\n'probe' is not a recognized processor for this target (ignoring processor)\\n'probe' is not a recognized processor for this target (ignoring processor)\\n'probe' is not a recognized processor for this target (ignoring processor)\\n'probe' is not a recognized processor for this target (ignoring processor)\\nCannot find device \\\"lxcc83aa\\\"\\nCannot find device \\\"lxcc83aa\\\"\\n\"" code=Failure containerID=c83aa8ebd5 endpointID=9882 endpointState=ready ipv4=10.10.1.179 ipv6="f00d::a0a:100:0:269a" k8sPodName="default:deathstar-3567858499-7bglr" policyRevision=0 type=200
2018-07-13T03:26:16.288797268Z level=warning msg="Ignoring error while deleting endpoint" endpointID=9882 error="unable to delete element 9882 from map /sys/fs/bpf/tc/globals/cilium_policy_9882: [Unable to delete key f00d::a0a:100:0:269a in endpoint BPF map: Unable to delete element from map with file descriptor 6: no such file or directory Unable to delete key 10.10.1.179 in endpoint BPF map: Unable to delete element from map with file descriptor 6: no such file or directory]"
2018-07-13T03:26:16.296213459Z level=warning msg="Ignoring error while deleting endpoint" endpointID=9882 error="unable to delete element 9882 from map /sys/fs/bpf/tc/globals/cilium_policy_9882: [Unable to delete key f00d::a0a:100:0:269a in endpoint BPF map: Unable to delete element from map with file descriptor 6: no such file or directory Unable to delete key 10.10.1.179 in endpoint BPF map: Unable to delete element from map with file descriptor 6: no such file or directory]"
2018-07-13T03:26:16.296770461Z level=warning msg="Ignoring error while deleting endpoint" endpointID=9882 error="unable to delete element 9882 from map /sys/fs/bpf/tc/globals/cilium_policy_9882: [Unable to delete key f00d::a0a:100:0:269a in endpoint BPF map: Unable to delete element from map with file descriptor 6: no such file or directory Unable to delete key 10.10.1.179 in endpoint BPF map: Unable to delete element from map with file descriptor 6: no such file or directory]"
```

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
