### PR TITLE
v1.15 Backports 2024-04-02

### PR DESCRIPTION
**Pull request by joamaki**
* [x] #29300 (@learnitall)
 * [x] #31407 (@tommyp1ckles)
 * [x] #31478 (@julianwiedmann)
 * [x] #31494 (@mhofstetter)
 * [x] #31594 (@qmonnet)
 * [x] #31328 (@nathanjsweet)
 * [x] #31635 (@pchaigno)
 * [x] #31622 (@gandro)
 * [x] #31636 (@julianwiedmann)
 * [x] #31627 (@pchaigno)
 * [ ] #31104 (@tamilmani1989)
 * [x] #31641 (@tklauser)
 * [x] #31652 (@qmonnet)

PRs skipped due to conflicts:

 * #31493 (@mhofstetter)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 29300 31407 31478 31494 31594 31328 31635 31622 31636 31627 31104 31641 31652
```

### CODE REVIEW

**Review by mhofstetter — APPROVED** [review]
My commit looks good - thanks Jussi!

Will handle the conflicting PR.

**Review by tklauser — APPROVED** [review]
My changes look good, thanks!

**Review by pchaigno — APPROVED** [review]
My PRs look good. Thanks Jussi!

**Review by qmonnet — APPROVED** [review]
My commits look good on the three branches, thanks Jussi!

**Review by learnitall — APPROVED** [review]
Thanks!

**Review by julianwiedmann — APPROVED** [review]

**Review by tommyp1ckles — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Review by gandro — APPROVED** [review]
My commit looks good, thanks!

**Pull request merged**
