### PR TITLE
v1.9: Update Go to 1.15.13

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
test-backport-1.9

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
test-1.12-netnext

**Comment by tklauser** [comment]
test-1.17-5.4

**Comment by tklauser** [comment]
test-1.19-4.9

**Comment by tklauser** [comment]
test-backport-1.9

**Comment by tklauser** [comment]
test-1.14-4.9

**Comment by tklauser** [comment]
test-1.17-5.4

**Comment by tklauser** [comment]
The `k8s-1.17-kernel-5.4` job hit #16050.

**Comment by tklauser** [comment]
test-1.12-netnext

**Pull request merged**
