### PR TITLE
K8s: Append rule labels while parsing api.Rule

### PR DESCRIPTION
**Pull request by ashwinp**
- Add unit test to check for rule labels

Fixes: #4164

Signed-off-by: ashwinp <ashwin@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4175)

### CODE REVIEW

**Review by rlenglet — APPROVED** [review]

**Comment by rlenglet** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
@ashwinp Could you squash these 3 commits into a single commit. I see one is a merge commit too, so doesn't make sense to have a separate commit for that.

**Review by aanm — CHANGES_REQUESTED** [review]
Needs squash, otherwise everything looks good to me

**Comment by ashwinp** [comment]
@aanm @manalibhutiyani done.

**Comment by aanm** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Pull request merged**
