### PR TITLE
test: Swap k8s vsn between cilium/ubuntu{,-next} CI jobs

### PR DESCRIPTION
**Pull request by brb**
See commit messages.

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
Applying `istio-cilium.yaml` timed out:
```
time="2020-04-06T19:39:52Z" level=error msg="Error executing command 'kubectl apply --force=false -f /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.18-gopath/src/github.com/cilium/cilium/test/k8sT/manifests/istio-cilium.yaml'" error="signal: killed"
cmd: "kubectl apply --force=false -f /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.18-gopath/src/github.com/cilium/cilium/test/k8sT/manifests/istio-cilium.yaml" exitCode: -1 duration: 30.002656564s stdout:
```

Re-running to see whether it's a flake.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
This PR conflicts with https://github.com/cilium/cilium/pull/10880 has one needs to be rebase with the other. In this case will be documentation update.

**Comment by aanm** [comment]
@brb please rebase against master and update the docs added by https://github.com/cilium/cilium/pull/10880

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]

**Comment by brb** [comment]
`Suite-k8s-1.11.K8sConformance Portmap Chaining Check connectivity-check compliance with portmap chaining` failed:
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
connectivity-check pods are not ready after timeout
Expected
    <*errors.errorString | 0xc0002784e0>: {
        s: "Timeout reached: timed out waiting for pods with filter  to be ready",
    }
to be nil
/usr/local/go/src/reflect/value.go:460
```
Rerunning to see whether my PR does not introduced the failure.

**Comment by brb** [comment]
test-me-please

**Comment by pchaigno** [comment]
> Rerunning to see whether my PR does not introduced the failure.

@brb You did not introduce this. That test is broken on K8S 1.11 apparently. It was previously skipped on K8s 1.11 because it requires kube-proxy. See #11118, which enables kube-proxy on K8s 1.11 net-next, for example.

**Comment by brb** [comment]
test-me-please

**Comment by aanm** [comment]
restart-ginkgo

**Comment by pchaigno** [comment]
@aanm It's going to fail again with the same test. [That test is broken on K8s 1.11](https://github.com/cilium/cilium/pull/10864#issuecomment-618899290).

**Comment by brb** [comment]
I haven't run it locally yet, but my gut feeling is that some api definitions might not be valid on k8s 1.11.

**Comment by joestringer** [comment]
@brb is this PR still relevant now that we have an additional test job for kernel 4.19?

**Comment by brb** [comment]
The k8s Service Topology feature is currently being reworked, so we can close this PR.

**Pull request closed without merging**
