### PR TITLE
[v1.5] Dockerfile: Bump cilium-runtime to latest image

### PR DESCRIPTION
**Pull request by joestringer**
Update the cilium-runtime image to bump all OS dependencies.

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Comment by nebril** [comment]
never-tell-me-the-odds

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Review by michi-covalent — APPROVED** [review]

**Comment by joestringer** [comment]
Looks like the initial attempt at resolving the certificate issue was ineffective:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19684/execution/node/96/log/
```
17:53:30      k8s2-1.10: Error response from daemon: Get https://k8s1:5000/v2/: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "cilium.io")
```

**Comment by nebril** [comment]
never-tell-me-the-odds

**Comment by nebril** [comment]
Added one last hack:
```
echo '{"insecure-registries": ["k8s1:5000"]}' > /etc/docker/daemon.json
sudo pkill -SIGHUP docker
```
this should be enough of a band-aid to keep this from failing.

**Review by nebril — APPROVED** [review]

**Pull request merged**
