### PR TITLE
v1.7 backports 2020-03-30

### PR DESCRIPTION
**Pull request by tklauser**
* #10184 -- Add apiserver heartbeat with conntrack (@tom-hadlaw-hs)
   * Resolved some conflicts and manual of wiring-up of
     `option.K8sHeartbeatTimeout` for the operator was needed due to #10184
     moving the operator flags to operator/flags.go in master.
 * #10490 -- k8s: Disable several CiliumEndpoint status sections by default (@tgraf)
   * Resolved some minor conflicts.
 * #10658 -- test: fix k8s provisioning with feature gates (@aanm)
 * #10608 -- daemon/cmd: update visibility policy after endpoint queue is created (@aanm)
 * #10566 -- kubernetes: do not set enable-endpoint-health-checking=false with portmap (@soumynathan)
 * #10537 -- Adds details about required kernel versions above 4.9.17, supported OS update (@seanmwinn)
 * #10666 -- bugtool: add mode to retrieve pprof traces (@aanm)
 * #10673 -- Improve k8s client heartbeat capability (@aanm)
   * Trivial merge conflict in 04309e64d2332e7aa91ef575eabd5bd4ef62f98e
     regarding `pkg/k8s/client.go`. Change needed in `pkg/k8s/init.go` to remove
     `ctx` argument from call to `k8sRestClient.Get().Resource("healthz").Do()`.
 * #9888 -- eni: Fix unexpected IP release when agent restarts (@jaffcheng)
   * Trivial merge conflicts. Had to drop `option.IPAMAzure` from condition in
     `daemon.NewDaemon` since Azure IPAM is not in `v1.7`.
 * #10694 -- helm: re-generate quick-install.yml after PR #10566 (@tklauser)
   * Trivial merge conflicts
 * #10741 -- cilium: set encrypt node route mtu in encryption table (@jrfastab)
 * #10734 -- make: pick up all privileged tests in `make tests-privileged` (@tklauser)
 * #10690 -- pkg/k8s: fix heartbeat unit test flake (@aanm)
 * #10721 -- CI: K8sKafkaPolicyTest kafka-broker starts up without errors (@raybejjani)
 * #10753 -- pre-flight: Correct tofqdns-precache container name (@raybejjani)
 * #10668 -- datapath: Do not log if svc is not found (@brb)
   * Separate commit created by @brb against the `v1.7` branch in #10757. Cherry-picked from there.

*Unresolved Conflicts*
 * #10518 -- bpf: significantly improve capacity of TCP CT tables (@borkmann)
   * Too many conflicts due to `skb` -> `ctx` renaming in #10491. Dropped for now.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10184 10490 10658 10608 10566 10537 10666 10673 9888 10694 10741 10734 10690 10721 10753 10668; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by tklauser** [comment]
never-tell-me-the-odds

**Review by aanm — APPROVED** [review]
@tklauser changes look good for my commits and the first commit. You will need to backport https://github.com/cilium/cilium/pull/10721 as well to fix the kafka failure.

**Comment by tklauser** [comment]
Pulled in #10721 and #10753

**Comment by tklauser** [comment]
never-tell-me-the-odds

**Comment by tklauser** [comment]
never-tell-me-the-odds

**Comment by tklauser** [comment]
test-upstream-k8s

**Comment by tklauser** [comment]
test-upstream-k8s

**Pull request merged**
