### PR TITLE
test: fix kafka policy test

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6399)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
:thinking:

**Comment by ianvernon** [comment]
This looks fine, but I'd like a bit more context. Is it a requirement that kube-dns needs to be running in the kube-system namespace? Are there tests in which pods with the kube-dns label were not running in the kube-system namespace?

**Comment by aanm** [comment]
@ianvernon kube-dns is running in the kube-system namespace so I don't know how the test was working :thinking: I did found out the packets were being dropped when kafka was trying to reach kube-dns

**Comment by ianvernon** [comment]
But why do we have to specify the kube-system namespace? Wouldn't the policy that is generated find that the identity for the kube-dns pod contains the kube-dns label and whitelist the kube-dns identity, even if the kube-system namespace label is not provided in the policy spec?

**Comment by joestringer** [comment]
@ianvernon I think what's happening is that along the way something is implicitly adding the default namespace into the target rule, so rather than allowing connectivity to any pods with the labels `k8s-app=kube-dns`, it only allows it to such pods inside the default namespace. (I don't know the logic of how or why this happens, but the policy reported by `cilium policy get` reflected this)

**Comment by ianvernon** [comment]
@joestringer ahh... I did not realize this. That is intriguing then that this test worked. 🤔

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
