### PR TITLE
1.4 backports: 19-03-05

### PR DESCRIPTION
**Pull request by ianvernon**
* PR: 7302 -- cilium: ipsec, zero cb[0] to avoid incorrectly encrypting (@jrfastab) -- https://github.com/cilium/cilium/pull/7302
* PR: 7288 -- contrib: Update backporting README (@brb) -- https://github.com/cilium/cilium/pull/7288
* PR: 7286 -- contrib: Fix cherry-pick to avoid omitting parts of patch (@brb) -- https://github.com/cilium/cilium/pull/7286

When you have backported the above commits, you can update the PR labels via this command:
```
$ for pr in 7302 7288 7286; do contrib/backporting/set-labels.py $pr pending 1.4; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7313)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Review by joestringer — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Comment by ianvernon** [comment]
K8s tests failed due to infrastructure issue: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1752/


```
[K    k8s1-1.9: Progress: 85% (Rate: 3507k/s, Estimated time remaining: 0:03:18)Cannot contact jenkins-fixed-2: java.lang.InterruptedException
02:14:47  
```

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
Hit #7316:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1753/execution/node/64/log/

**Comment by joestringer** [comment]
test-missed-k8s

**Pull request merged**
