### PR TITLE
all: bump Alpine base image to 3.13.1 and add meta image SHA256 sum

### PR DESCRIPTION
**Pull request by rolinh**

### CODE REVIEW

**Comment by rolinh** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by kaworu — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by rolinh** [comment]
retest net-next

**Comment by rolinh** [comment]
test netnext

**Comment by rolinh** [comment]
retest-net-next

**Pull request merged**
