### PR TITLE
backport 1.9: vendor: Bump github.com/cilium/arping

### PR DESCRIPTION
**Pull request by brb**
The bumped version includes https://github.com/cilium/arping/pull/6.

### CODE REVIEW

**Review by gandro — APPROVED** [review]

**Comment by brb** [comment]
test-backport-1.9

**Comment by gandro** [comment]
GKE scaling failure https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/3999/

**Comment by gandro** [comment]
retest-gke

**Comment by Rolinh** [comment]
test-missed-k8s

**Pull request merged**
