### PR TITLE
Update Go to 1.16.3

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
test-1.16-netnext

**Comment by tklauser** [comment]
test-1.21-4.9

**Review by vadorovsky — APPROVED** [review]

**Comment by tklauser** [comment]
test-1.16-netnext

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-1.21-4.9

**Comment by nebril** [comment]
test-me-please

**Review by michi-covalent — APPROVED** [review]

**Pull request merged**
