### PR TITLE
[v1.9] eni: Fix Cilium overallocating network interfaces 

### PR DESCRIPTION
**Pull request by gandro**
v1.9 backports 2021-05-06

 * #15911 -- eni: Fix Cilium overallocating network interfaces (@gandro)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 15911; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by gandro** [comment]
test-backport-v1.9

**Comment by gandro** [comment]
test-backport-1.9

**Comment by pchaigno** [comment]
test-1.17-5.4

**Comment by gandro** [comment]
test-1.17-5.4

**Comment by gandro** [comment]
test-1.13-4.9

**Comment by pchaigno** [comment]
> test-1.17-5.4 seems to keep hitting Suite-k8s-1.17.K8sVerifier Runs the kernel verifier against Cilium's BPF datapath - I assume this is unrelated to the PR?

Hm, could be another complexity issue :sweat: 

There are no datapath changes in this PR so if it happens here, it also happens in master. It must have slipped through during the rebase of my backport PR. Let's ignore for now.

**Review by joestringer — APPROVED** [review]

**Pull request merged**
