### PR TITLE
controlplane: Refactor the framework

### PR DESCRIPTION
**Pull request by joamaki**
This PR simplifies the controlplane test framework to use a more imperative API that should be easier to use and more transparent.

Additionally this fixes the few blockers with instantiating Daemon multiple times in one process and then moves all test cases into one ~100MB binary (instead of one per test case).

Unmarshalling of the K8s objects is also rewritten to use CodecFactory to allow unmarshalling of Cilium CRDs that contain unexported fields and thus require unmarshalling via their custom UnmarshalJSON methods.

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
The changes in main application make sense to me.

For controlplane test, I didn't check in details, except trying to add a new test suite, which is smooth as expected :100:

**Review by christarazi — APPROVED** [review]

**Review by tommyp1ckles — APPROVED** [review]
metrics changes look good.

**Review by pippolo84 — APPROVED** [review]
LGTM :100:

**Pull request merged**
