### PR TITLE
workflows: hubble cli integration: fix logic to wait for images

### PR DESCRIPTION
**Pull request by jibi**
Fixes: bc294a83d5 ("Add hubble CLI integration tests")

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
Thanks!

**Review by rolinh — APPROVED** [review]

**Review by chancez — APPROVED** [review]

**Comment by chancez** [comment]
We can't test this change until after it's merged, can we?

**Review by michi-covalent — APPROVED** [review]

**Comment by michi-covalent** [comment]
> We can't test this change until after it's merged, can we?

ariane is supposed to check out the right context. let's see.

**Comment by chancez** [comment]
Also, once we get `Hubble CLI integration tests` working fully, we should probably mark them as required.

**Comment by chancez** [comment]
Oops:
```
      - name: Build hubble CLI
        run: make
```

This needs to be `make -C hubble`

**Comment by chancez** [comment]
🎉 https://github.com/cilium/cilium/actions/runs/9981939812/job/27586675700

**Pull request merged**
