### PR TITLE
Backports V1.3 14-02-2019

### PR DESCRIPTION
**Pull request by eloycoto**
Done: 

#7025
#7029

Others PR will be backport one-by-one in separate PR.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7072)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-docs-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
