### PR TITLE
CI: fix broken BPF complexity tests

### PR DESCRIPTION
**Pull request by lmb**
complexity-tests: remove Egress Gateway from IPv6-only tests

    Egress Gateway only supports IPv4 so enabling it on IPv6-only tests doesn't
    make a lot of sense.

    Signed-off-by: Lorenz Bauer <lmb@isovalent.com>

bpf: prevent clang from reordering address calculations before NULL check

    Compiling the BPF complexity tests currently bails out in 
    tail_nodeport_nat_egress_ipv4 and tail_nodeport_nat_egress_ipv6. The error 
    for the v4 case is the following:

        ; return map_lookup_elem(map, tuple);
       169: (18) r1 = 0xffff9dfb4d0f9800     ;
    R1_w=map_ptr(off=0,ks=14,vs=40,imm=0)
       171: (85) call bpf_map_lookup_elem#1
       172: (bf) r5 = r0
       173: (07) r5 += 32
       R5 pointer arithmetic on map_value_or_null prohibited, null-check it
    first

    The problem is easier to spot when looking at the disassembly of the
    function:

        ;       return map_lookup_elem(map, tuple);
       169:       r1 = 0x0 ll
       171:       call 0x1
       172:       r5 = r0
       173:       r5 += 0x20
       174:       r3 = r0
       175:       r3 += 0x24
       ;       if (*state)
       176:       if r0 != 0x0 goto +0x6da <LBB9_167>

    It seems like clang has decided that it can hoist the address calculation
    based on r0 before checking that r0 != 0.

    Work around this issue by inserting a barrier_data() call.

    Signed-off-by: Lorenz Bauer <lmb@isovalent.com>

test/verifier: fix complexity tests not being recompiled

    TestVerifier is accidentally reusing the result of previous subtest 
    compilations. This means that only the first set of configurations was
    tested.

    Invoke clean for every new compilation. The generated object files are moved
    to the test directory to make them accessible as artifacts from CI.

    Fixes: d3ef5b2ac8 ("test/verifier: Avoid pruning object files before testing
    the next file") Signed-off-by: Lorenz Bauer <lmb@isovalent.com>

test/verifier: improve log output

    Include the command invoked to compile the BPF and the output of the command
    in the test output by default.

    Signed-off-by: Lorenz Bauer <lmb@isovalent.com>

### CODE REVIEW

**Comment by lmb** [comment]
This might need a manual backport to v1.14, I think that reverting the offending commit is probably the best option.

**Review by christarazi — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]

**Comment by pchaigno** [comment]
@lmb If it affects v1.14, shouldn't we backport there?

**Comment by lmb** [comment]
Yes, I'll do that once this is in `main`.

**Comment by lmb** [comment]
https://github.com/cilium/cilium/pull/29553

**Pull request merged**
