### PR TITLE
go.mod, vendor: use github.com/cilium/dns fork directly

### PR DESCRIPTION
**Pull request by tklauser**
We have been maintaining and using that fork for a long time and it looks like the custom changes won't make it upstream any time soon.

There are no other vendored dependencies using miekg/dns, so switching to the cilium/dns fork shouldn't have any side effects. The fork's module name was changed to match its import path in https://github.com/cilium/dns/pull/4.

Let's replace the `github.com/miekg/dns` import path by `github.com/cilium/dns` to get rid of another `replace` directive in `go.mod` and thus make life a tiny bit easier for downstream packages importing `github.com/cilium/cilium`.

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]

**Comment by tklauser** [comment]
Rebased to resolve merge conflict.

**Review by borkmann — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Pull request merged**
