### PR TITLE
api-limiter: Make auto adjust test less flaky

### LINKED ISSUE #13508: api-limiter: TestAutoAdjust unit test fails consistently
Running `make unit-tests` in the standard Vagrant VM on my local machine consistently fails with the following test failing:

```
FAIL: api_limiter_test.go:96: ControllerSuite.TestAutoAdjust

api_limiter_test.go:128:
    // burst should not adjust this quickly
    c.Assert(a.limiter.Burst(), check.Equals, initialRateBurst)
... obtained int = 1
... expected int = 2
```

The failing test is at [this line](https://github.com/cilium/cilium/blob/master/pkg/rate/api_limiter_test.go#L128).

The test here looks potentially a little racy (there are a few `time.Sleep`s), and the code being tested looks to be both new and quite subtle.

@tgraf and @aanm it looks like you're currently working on this area of the codebase. Would you like me to investigate further? Do you need any further information?

### PR DESCRIPTION
**Pull request by twpayne**
Fixes: #13508
    
The auto adjust unit test relies on time.Sleep to schedule multiple requests. The existing sleep times were close to the limit for the test to pass. This commit shortens the times so the test is less sensitive to delays and more likely to pass.
    
The use of a fake clock in the tests, e.g. [`github.com/jonboulle/clockwork`](github.com/jonboulle/clockwork), to make the tests both reliable and more accurate was investigated. However, the existing code builds on `golang.org/x/time/rate` which itself does not have support for a fake clock in tests, so `golang.org/x/time/rate` would need to updated first.

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by tklauser** [comment]
These tests run as part of the unprivileged unit tests on Travis CI. These passed, so no need to run Jenkins CI. Merging.

**Comment by christarazi** [comment]
@twpayne Should these be backported given that the api-limiter is on the v1.7 and v1.8 trees as well?

**Comment by twpayne** [comment]
It's optional. It's not a critical fix, but it does reduce flakiness.

**Comment by christarazi** [comment]
I'll pull it in for v1.9 because that'll be an active branch for a while. If we find the CI on other branches become too flaky, we can always backport when the need arises.

**Pull request merged**
