### PR TITLE
bpf: test: add some IPv6 DSR integration tests

### PR DESCRIPTION
**Pull request by julianwiedmann**
Some IPv6 tests I didn't upstream as part of https://github.com/cilium/cilium/pull/22978. This looks a bit prettier now that we have `pktgen` support for IPv6 extension headers.

### CODE REVIEW

**Comment by julianwiedmann** [comment]
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.19/1473/ fail is https://github.com/cilium/cilium/issues/22749#issuecomment-1401682979.

**Comment by julianwiedmann** [comment]
/test-1.16-4.19

**Review by nbusseneau — APPROVED** [review]
Auto-approving for `ci-structure` and `github-sec` as workflow changes are trivial.

**Review by ldelossa — APPROVED** [review]
LGTM

**Pull request merged**
