### PR TITLE
Testing: Add operator in deployments

### PR DESCRIPTION
**Pull request by eloycoto**
Added Cilium operator in CI

Related to commit: 317b6f13b797b7d40d5b3cb2f7fbe8345b28bf3f

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6238)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Review by aanm — CHANGES_REQUESTED** [review]
@eloycoto the operator will likely require a kvstore to be up so it would be better to add a new helper and install it after etcd-operator and kubedns are up and running.

**Comment by eloycoto** [comment]
@aanm I'm not agree with you on this one. Should be deployed and the check is restarting until is ready.

**Pull request closed without merging**
