### PR TITLE
K8s fix for kube-proxy

### PR DESCRIPTION
**Pull request by jrfastab**
Kube proxy was causing issues where `--enable-ipsec` was failing to load properly. There were really two problems fixes here,

 (i) If the kv-store required communication inside Cilium managed node with ipsec enabled then one side would expect encryption and the other would not. This prevented initial node configuration to add all encryption keys and the system got stuck unable to communicate with the kv-store. To reproduce use the etcd-operator DaemonSet. The fix is to add the necessary fields to k8s watcher so we can add the keys earlier.

(ii) Kube-services (installed by kube-proxy) use a set of iptables rules to do NAT rules mapping into cilium_host IP/ports. But because with enable-ipsec we do an extra trip through the xfrm stack where connection tracking rules are applied as well we ended up doing nat multiple times creating invalid sport values. This resulted in the connection being reset on the receiver. To fix add a NOTRACK rule early in the raw table with the mark values.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7146)

### CODE REVIEW

**Comment by jrfastab** [comment]
Resolves blocking issues,
https://github.com/cilium/cilium/issues/7121
https://github.com/cilium/cilium/issues/7122

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
