### PR TITLE
v1.7 backports 2020-06-10

### PR DESCRIPTION
**Pull request by joestringer**
* #11952 -- service: Clean up HealthCheckNodePort server when traffic policy changes  (@gandro)
   * Dropped testsuite changes due to major conflicts
 * #11947 -- Fix EndpointSlice support (@aanm)
   * Minor conflict due to v1.7 not using slim k8s structures
 * #11974 -- cilium: fixes transparent encryption (@jrfastab)
   * @jrfastab helped with the backport here, PTAL. Dropped second commit.
 * #11998 -- cilium, test: Only run sockops tests on 4.19 and bpf-next kernels (@jrfastab)
   * Minor conflicts, dropping 4.19 skip since v1.7 doesn't run v4.19 CI.
 * #11891 -- etcd: propagate Context from higher-level calls (@tklauser)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 11952 11947 11974 11998 11891; do contrib/backporting/set-labels.py $pr done 1.7; done
```

Skipping the following backports:

 * #11995 -- test: Wait for POD policy revision increment in all cases. (@jrajahalme)
   * Significant conflicts; I tried just pulling the version of the changes
     from the PR but that resulted in test compile failures in code that
     apparently doesn't exist in master, so naive conflict resolution is not
     sufficient to provide a good backport. Dropping.
 * Several others where the authors have already been notified recently to
   backport their PRs.

### CODE REVIEW

**Review by jrfastab — APPROVED** [review]
LGTM thanks!

**Comment by joestringer** [comment]
test-backport-1.7

**Comment by joestringer** [comment]
test-backport-1.7

**Review by aanm — APPROVED** [review]
LGTM for my changes

**Review by tklauser — APPROVED** [review]
LGTM for my change.

**Review by gandro — APPROVED** [review]
lgtm for my commit

**Comment by aanm** [comment]
test-missed-k8s

**Pull request merged**
