### PR TITLE
k8s/crds: Allow ingress entity in CNP

### PR DESCRIPTION
**Pull request by sayboras**
Relates: https://github.com/cilium/cilium/pull/19764

Signed-off-by: Tam Mach <tam.mach@cilium.io>

### CODE REVIEW

**Review by jrajahalme — APPROVED** [review]
Would be nice to have some tests validating entity ingress in CNPs as well.

**Comment by sayboras** [comment]
> Would be nice to have some tests validating entity ingress in CNPs as well.

Agreed, there is some effort going on simplifying the tests, so I raise the below issue for tracking purpose.

https://github.com/cilium/cilium/issues/20558

**Comment by sayboras** [comment]
Hitting different flakes during different runs for test-1.24-net-next, all of other required jobs are passed. Marking this ready to merge.

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.24-kernel-net-next/301/
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.24-kernel-net-next/287/

**Review by joestringer — APPROVED** [review]

**Pull request merged**
