### PR TITLE
Ginkgo: Add Measure ginkgo function to the Beforeall/AfterAll group

### PR DESCRIPTION
**Pull request by eloycoto**
Had seen issues with the BeforeAll/AfterAll in Nightly where the
functions are not cleanup correctly and get the test in a bad state.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5012)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-nightly

**Review by aanm — APPROVED** [review]

**Comment by eloycoto** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Nightly-Tests-All/160/console

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-me-please

**Comment by ianvernon** [comment]
> Had seen issues with the BeforeAll/AfterAll in Nightly where the
functions are not cleanup correctly and get the test in a bad state.

Can you provide an example here?

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Pull request closed without merging**
