### PR TITLE
test: Add test cases for lbmap-related restore

### LINKED ISSUE #13867: Add CI tests to check whether lbmap-related restore works
The https://github.com/cilium/cilium/issues/13824 issue revealed one weakness in the `k8sT/Services.go` suite - we don't test restore procedures of the lbmap-related maps. The unit tests in `pkg/service/service_test.go` contain test cases for testing the restore procedures, but they are relying on the lbmap mock implementation, so they cannot catch such issues as #11213 

~Therefore, we should extend the CI suite by adding a case in which cilium-agent gets restarted and is able to function.~ We should add a _privileged_ unit test which uses the actual lbmap implementation.

### PR DESCRIPTION
**Pull request by oneiro-naut**
This modifies test cases to test lbmap-related map restore during three stages which are:
1. When cilium-agent is running(= before restart)
2. When cilium-agent is killed and is restarting(= during restart)
3. When cilium-agent has restarted(= after restart)

Following tests under context Tests NodePort BPF are modified:
- [X] Tests NodePort(for lb_service map restore check)
- [ ] Tests NodePort with sessionAffinity(for lb_affinity map restore check)

Following tests under context Tests LoadBalancer are modified:
- [ ] Connectivity to endpoint via LB(for lb_src_range map restore check)

All these tests need to pass during all the 3 stages.

Fixes: #13867

### CODE REVIEW

**Comment by brb** [comment]
@oneiro-naut We are in the process of migrating the Services suite to GH Actions. Therefore, we are very reluctant to add new tests to the suite. I think the test you are working on could be a privileged unit test which uses a real lbmap instead of the mock.

**Comment by oneiro-naut** [comment]
> @oneiro-naut We are in the process of migrating the Services suite to GH Actions. Therefore, we are very reluctant to add new tests to the suite. I think the test you are working on could be a privileged unit test which uses a real lbmap instead of the mock.

@brb It does use the real lbmap implementation. It doesn't explicitly call the RestoreService function and relies on cilium-agent to call it. https://github.com/cilium/cilium/blob/901afa5131f27406c43a508356469141b6ed1ce0/daemon/cmd/daemon.go#L496

**Comment by brb** [comment]
@oneiro-naut What I meant is that you can write a unit test instead of the ginkgo test. In order to use the actual lbmap implementation, you would need to make the test as privileged.

**Comment by oneiro-naut** [comment]
> @oneiro-naut What I meant is that you can write a unit test instead of the ginkgo test. In order to use the actual lbmap implementation, you would need to make the test as privileged.

@brb Sure thing. I will write a unit test instead of the ginkgo test for the same scenario.

**Pull request closed without merging**
