### PR TITLE
Fixed Cilium CLI fatal error: concurrent map read and map write

### LINKED ISSUE #35222: Cilium CLI, connectivity tests: fatal error: concurrent map read and map write
Hit on https://github.com/cilium/cilium/pull/35172
Link: https://github.com/cilium/cilium/actions/runs/11175025648/job/31065863288

```
fatal error: concurrent map read and map write

goroutine 54 [running]:
k8s.io/apimachinery/pkg/runtime.(*Scheme).ObjectKinds(0xc000460000, {0x5327c00?, 0xc0007463f0?})
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:267 +0x1cb
k8s.io/apimachinery/pkg/runtime.(*parameterCodec).EncodeParameters(0x76d39c0, {0x5327c00, 0xc0007463f0}, {{0x0, 0x0}, {0x3a6dd38, 0x2}})
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/runtime/codec.go:190 +0x62
k8s.io/client-go/rest.(*Request).SpecificallyVersionedParams(0xc000976240, {0x5327c00?, 0xc0007463f0?}, {0x53271a0?, 0x76d39c0?}, {{0x0?, 0x13b6056?}, {0x3a6dd38?, 0xc0005a3b60?}})
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/rest/request.go:380 +0x75
k8s.io/client-go/rest.(*Request).VersionedParams(...)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/rest/request.go:373
k8s.io/client-go/gentype.(*alsoLister[...]).list(0x5375e00, {0x534f368, 0xc00028d480}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x3a9ffc9, 0xe}, {0x0, ...}, ...})
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/gentype/type.go:186 +0x16b
k8s.io/client-go/gentype.(*alsoLister[...]).List(0x5375e00, {0x534f368, 0xc00028d480}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x3a9ffc9, 0xe}, {0x0, ...}, ...})
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/gentype/type.go:170 +0x39a
github.com/cilium/cilium/cilium-cli/k8s.(*Client).ListPods(0x1508599?, {0x534f368, 0xc00028d480}, {0x3a8dd4c, 0xb}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x3a9ffc9, ...}, ...})
	/go/src/github.com/cilium/cilium/cilium-cli/k8s/client.go:307 +0xab
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).initCiliumPods(0xc000b3f808, {0x534f368, 0xc00028d480})
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/context.go:835 +0x157
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).SetupAndValidate(0xc000b3f808, {0x534f368, 0xc00028d480}, {0x7fdf5c530a08, 0x7cd5d80})
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/context.go:294 +0xc6
github.com/cilium/cilium/cilium-cli/connectivity.setupConnectivityTests.func1()
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/suite.go:63 +0x58
github.com/cilium/cilium/cilium-cli/utils/runner.(*MultiError).Go.func1()
	/go/src/github.com/cilium/cilium/cilium-cli/utils/runner/multierror.go:27 +0x6c
created by github.com/cilium/cilium/cilium-cli/utils/runner.(*MultiError).Go in goroutine 1
	/go/src/github.com/cilium/cilium/cilium-cli/utils/runner/multierror.go:25 +0x73

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x2f06cf3?)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*WaitGroup).Wait(0xc0001cc030?)
	/usr/local/go/src/sync/waitgroup.go:118 +0x48
github.com/cilium/cilium/cilium-cli/utils/runner.(*MultiError).Wait(...)
	/go/src/github.com/cilium/cilium/cilium-cli/utils/runner/multierror.go:38
github.com/cilium/cilium/cilium-cli/connectivity.setupConnectivityTests({0x534f368, 0xc00028d480}, {0xc000af10e0, 0x5, 0x5}, {0x7fdf5c5309d8, 0x7cd5d80})
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/suite.go:66 +0x10f
github.com/cilium/cilium/cilium-cli/connectivity.Run({0x534f368, 0xc00028d480}, {0xc000af10e0, 0x5, 0x5}, {0x7fdf5c5309d8, 0x7cd5d80})
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/suite.go:23 +0x65
github.com/cilium/cilium/cilium-cli/cli.newCmdConnectivityTest.RunE.func1(0xc0008fa308, {0x3a6f587?, 0x4?, 0x3a6f443?})
	/go/src/github.com/cilium/cilium/cilium-cli/cli/connectivity.go:97 +0x6b2
github.com/spf13/cobra.(*Command).execute(0xc0008fa308, {0xc0002db860, 0xf, 0xf})
	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:985 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002d6c08)
	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0x535ea90?)
	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1041 +0x13
main.main()
	/go/src/github.com/cilium/cilium/cilium-cli/cmd/cilium/main.go:22 +0xc5

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x7fe05c728e28, 0x72)
	/usr/local/go/src/runtime/netpoll.go:351 +0x85
internal/poll.(*pollDesc).wait(0xc000675100?, 0x0?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000675100)
	/usr/local/go/src/internal/poll/fd_unix.go:620 +0x295
net.(*netFD).accept(0xc000675100)
	/usr/local/go/src/net/fd_unix.go:172 +0x29
net.(*TCPListener).accept(0xc000b3bcc0)
	/usr/local/go/src/net/tcpsock_posix.go:159 +0x1e
net.(*TCPListener).Accept(0xc000b3bcc0)
	/usr/local/go/src/net/tcpsock.go:372 +0x30
github.com/google/gops/agent.listen({0x5339050, 0xc000b3bcc0})
	/go/src/github.com/cilium/cilium/vendor/github.com/google/gops/agent/agent.go:129 +0x51
created by github.com/google/gops/agent.Listen in goroutine 1
	/go/src/github.com/cilium/cilium/vendor/github.com/google/gops/agent/agent.go:122 +0x385

goroutine 49 [syscall]:
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:152 +0x29
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x13
created by os/signal.Notify.func1.1 in goroutine 1
	/usr/local/go/src/os/signal/signal.go:151 +0x1f

goroutine 50 [select]:
os/signal.NotifyContext.func1()
	/usr/local/go/src/os/signal/signal.go:288 +0x66
created by os/signal.NotifyContext in goroutine 1
	/usr/local/go/src/os/signal/signal.go:287 +0x156

goroutine 51 [chan receive]:
github.com/cilium/cilium/cilium-cli/cli.newCmdConnectivityTest.RunE.func1.1()
	/go/src/github.com/cilium/cilium/cilium-cli/cli/connectivity.go:91 +0x46
created by github.com/cilium/cilium/cilium-cli/cli.newCmdConnectivityTest.RunE.func1 in goroutine 1
	/go/src/github.com/cilium/cilium/cilium-cli/cli/connectivity.go:90 +0x5c5

goroutine 52 [select]:
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConcurrentLogger).collector(0xc000a69e00, {0x534f368, 0xc00028d480})
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/logger.go:120 +0x11e
created by github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConcurrentLogger).Start in goroutine 1
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/logger.go:50 +0x85

goroutine 53 [runnable]:
sync.(*Mutex).Unlock(...)
	/usr/local/go/src/sync/mutex.go:221
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConcurrentLogger).collectedTestCount(0x0?)
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/logger.go:163 +0x61
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConcurrentLogger).printer(0xc000a69e00)
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/logger.go:148 +0x29
created by github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConcurrentLogger).Start in goroutine 1
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/logger.go:51 +0xc5

goroutine 55 [select]:
net/http.(*Transport).getConn(0xc000894300, 0xc000d78460, {{}, 0x0, {0xc000d321e0, 0x5}, {0xc0004f3400, 0xb}, 0x0})
	/usr/local/go/src/net/http/transport.go:1468 +0x4bd
net/http.(*Transport).roundTrip(0xc000894300, 0xc0004fedc0)
	/usr/local/go/src/net/http/transport.go:633 +0xb54
net/http.(*Transport).RoundTrip(0x36ac520?, 0xc000d71440?)
	/usr/local/go/src/net/http/roundtrip.go:30 +0x13
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc00096c8a0, 0xc0004feb40)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/transport/round_trippers.go:168 +0x326
net/http.send(0xc0004feb40, {0x5300360, 0xc00096c8a0}, {0x7fdf5c59db01?, 0x30?, 0x0?})
	/usr/local/go/src/net/http/client.go:259 +0x5e4
net/http.(*Client).send(0xc0009fd7d0, 0xc0004feb40, {0x0?, 0x0?, 0x0?})
	/usr/local/go/src/net/http/client.go:180 +0x98
net/http.(*Client).do(0xc0009fd7d0, 0xc0004feb40)
	/usr/local/go/src/net/http/client.go:725 +0x8bc
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:590
k8s.io/client-go/rest.(*Request).request(0xc000d665a0, {0x534f368, 0xc00028d480}, 0xc000ca0de8)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/rest/request.go:1162 +0x385
k8s.io/client-go/rest.(*Request).Do(0xc000d665a0, {0x534f368, 0xc00028d480})
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/rest/request.go:1202 +0xad
k8s.io/client-go/gentype.(*alsoLister[...]).list(0x5375e00, {0x534f368, 0xc00028d480}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x3a9ffc9, 0xe}, {0x0, ...}, ...})
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/gentype/type.go:188 +0x196
k8s.io/client-go/gentype.(*alsoLister[...]).List(0x5375e00, {0x534f368, 0xc00028d480}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x3a9ffc9, 0xe}, {0x0, ...}, ...})
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/gentype/type.go:170 +0x39a
github.com/cilium/cilium/cilium-cli/k8s.(*Client).ListPods(0x1508599?, {0x534f368, 0xc00028d480}, {0x3a8dd4c, 0xb}, {{{0x0, 0x0}, {0x0, 0x0}}, {0x3a9ffc9, ...}, ...})
	/go/src/github.com/cilium/cilium/cilium-cli/k8s/client.go:307 +0xab
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).initCiliumPods(0xc000af4008, {0x534f368, 0xc00028d480})
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/context.go:835 +0x157
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).SetupAndValidate(0xc000af4008, {0x534f368, 0xc00028d480}, {0x7fdf5c530a08, 0x7cd5d80})
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/context.go:294 +0xc6
github.com/cilium/cilium/cilium-cli/connectivity.setupConnectivityTests.func1()
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/suite.go:63 +0x58
github.com/cilium/cilium/cilium-cli/utils/runner.(*MultiError).Go.func1()
	/go/src/github.com/cilium/cilium/cilium-cli/utils/runner/multierror.go:27 +0x6c
created by github.com/cilium/cilium/cilium-cli/utils/runner.(*MultiError).Go in goroutine 1
	/go/src/github.com/cilium/cilium/cilium-cli/utils/runner/multierror.go:25 +0x73

goroutine 56 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0xc00011c080?)
	/usr/local/go/src/runtime/sema.go:95 +0x25
sync.(*Mutex).lockSlow(0x7cd6430)
	/usr/local/go/src/sync/mutex.go:173 +0x15d
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:92
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).initClients(0xc000af4808, {0x534f368, 0xc00028d480})
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/context.go:817 +0xf0
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).SetupAndValidate(0xc000af4808, {0x534f368, 0xc00028d480}, {0x7fdf5c530a08, 0x7cd5d80})
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/context.go:291 +0x9a
github.com/cilium/cilium/cilium-cli/connectivity.setupConnectivityTests.func1()
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/suite.go:63 +0x58
github.com/cilium/cilium/cilium-cli/utils/runner.(*MultiError).Go.func1()
	/go/src/github.com/cilium/cilium/cilium-cli/utils/runner/multierror.go:27 +0x6c
created by github.com/cilium/cilium/cilium-cli/utils/runner.(*MultiError).Go in goroutine 1
	/go/src/github.com/cilium/cilium/cilium-cli/utils/runner/multierror.go:25 +0x73

goroutine 57 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0xc00011c1b0?)
	/usr/local/go/src/runtime/sema.go:95 +0x25
sync.(*Mutex).lockSlow(0x7cd6430)
	/usr/local/go/src/sync/mutex.go:173 +0x15d
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:92
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).initClients(0xc000af5008, {0x534f368, 0xc00028d480})
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/context.go:817 +0xf0
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).SetupAndValidate(0xc000af5008, {0x534f368, 0xc00028d480}, {0x7fdf5c530a08, 0x7cd5d80})
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/context.go:291 +0x9a
github.com/cilium/cilium/cilium-cli/connectivity.setupConnectivityTests.func1()
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/suite.go:63 +0x58
github.com/cilium/cilium/cilium-cli/utils/runner.(*MultiError).Go.func1()
	/go/src/github.com/cilium/cilium/cilium-cli/utils/runner/multierror.go:27 +0x6c
created by github.com/cilium/cilium/cilium-cli/utils/runner.(*MultiError).Go in goroutine 1
	/go/src/github.com/cilium/cilium/cilium-cli/utils/runner/multierror.go:25 +0x73

goroutine 58 [runnable]:
syscall.Syscall6(0x101, 0xffffffffffffff9c, 0xc000078030, 0x80000, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_linux.go:95 +0x39
syscall.openat(0xffffffffffffff9c, {0xc0007540c0?, 0x44869e?}, 0x80000, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:98 +0x90
syscall.Open(...)
	/usr/local/go/src/syscall/syscall_linux.go:284
os.open({0xc0007540c0?, 0x448740?}, 0xc000d1b3af?, 0xd1b440?)
	/usr/local/go/src/os/file_open_unix.go:15 +0x2b
os.openFileNolog.func1()
	/usr/local/go/src/os/file_unix.go:279 +0x92
os.ignoringEINTR(...)
	/usr/local/go/src/os/file_posix.go:251
os.openFileNolog({0xc0007540c0, 0x12}, 0x0, 0x106?)
	/usr/local/go/src/os/file_unix.go:278 +0xae
os.OpenFile({0xc0007540c0, 0x12}, 0x0, 0x0)
	/usr/local/go/src/os/file.go:385 +0x3e
os.Open(...)
	/usr/local/go/src/os/file.go:365
os.ReadFile({0xc0007540c0?, 0x0?})
	/usr/local/go/src/os/file.go:784 +0x56
k8s.io/client-go/tools/clientcmd.LoadFromFile({0xc0007540c0, 0x12})
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/clientcmd/loader.go:387 +0x2f
k8s.io/client-go/tools/clientcmd.(*ClientConfigLoadingRules).Load(0xc000d08960)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/clientcmd/loader.go:226 +0x267
k8s.io/client-go/tools/clientcmd.(*DeferredLoadingClientConfig).createClientConfig(0xc000db89b0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/clientcmd/merged_client_builder.go:69 +0xba
k8s.io/client-go/tools/clientcmd.(*DeferredLoadingClientConfig).ClientConfig(0xc000db89b0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/clientcmd/merged_client_builder.go:97 +0x1f
k8s.io/cli-runtime/pkg/genericclioptions.(*clientConfig).ClientConfig(0xc000460000?)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/cli-runtime/pkg/genericclioptions/client_config.go:53 +0x1b
github.com/cilium/cilium/cilium-cli/k8s.NewClient({0x7fff837a3dae, 0x19}, {0x0, 0x0}, {0x3a8dd4c, 0xb})
	/go/src/github.com/cilium/cilium/cilium-cli/k8s/client.go:79 +0x1a2
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).initClients(0xc000af5808, {0x534f368, 0xc00028d480})
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/context.go:819 +0x145
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).SetupAndValidate(0xc000af5808, {0x534f368, 0xc00028d480}, {0x7fdf5c530a08, 0x7cd5d80})
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/context.go:291 +0x9a
github.com/cilium/cilium/cilium-cli/connectivity.setupConnectivityTests.func1()
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/suite.go:63 +0x58
github.com/cilium/cilium/cilium-cli/utils/runner.(*MultiError).Go.func1()
	/go/src/github.com/cilium/cilium/cilium-cli/utils/runner/multierror.go:27 +0x6c
created by github.com/cilium/cilium/cilium-cli/utils/runner.(*MultiError).Go in goroutine 1
	/go/src/github.com/cilium/cilium/cilium-cli/utils/runner/multierror.go:25 +0x73

goroutine 34 [chan receive]:
net/http.(*persistConn).addTLS(0xc000d666c0, {0x534f218, 0xc000d784b0}, {0xc0004f3401, 0x3}, 0xc000748e00)
	/usr/local/go/src/net/http/transport.go:1657 +0x327
net/http.(*Transport).dialConn(0xc000894300, {0x534f218, 0xc000d784b0}, {{}, 0x0, {0xc000d321e0, 0x5}, {0xc0004f3400, 0xb}, 0x0})
	/usr/local/go/src/net/http/transport.go:1738 +0x99c
net/http.(*Transport).dialConnFor(0xc000894300, 0xc000d84000)
	/usr/local/go/src/net/http/transport.go:1563 +0xb8
net/http.(*Transport).startDialConnForLocked.func1()
	/usr/local/go/src/net/http/transport.go:1545 +0x35
created by net/http.(*Transport).startDialConnForLocked in goroutine 55
	/usr/local/go/src/net/http/transport.go:1544 +0x117

goroutine 22 [runnable]:
internal/poll.runtime_pollWait(0x7fe05c728d20, 0x72)
	/usr/local/go/src/runtime/netpoll.go:351 +0x85
internal/poll.(*pollDesc).wait(0xc000748f00?, 0xc00075e240?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000748f00, {0xc00075e240, 0x240, 0x240})
	/usr/local/go/src/internal/poll/fd_unix.go:165 +0x27a
net.(*netFD).Read(0xc000748f00, {0xc00075e240?, 0x240?, 0x0?})
	/usr/local/go/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc00009e000, {0xc00075e240?, 0xc0000a0708?, 0x0?})
	/usr/local/go/src/net/net.go:189 +0x45
crypto/tls.(*atLeastReader).Read(0xc00075a0c0, {0xc00075e240?, 0x0?, 0xc00075a0c0?})
	/usr/local/go/src/crypto/tls/conn.go:809 +0x3b
bytes.(*Buffer).ReadFrom(0xc000e042b8, {0x52feb80, 0xc00075a0c0})
	/usr/local/go/src/bytes/buffer.go:211 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000e04008, {0x52fa940, 0xc00009e000}, 0xc000748f20?)
	/usr/local/go/src/crypto/tls/conn.go:831 +0xde
crypto/tls.(*Conn).readRecordOrCCS(0xc000e04008, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:629 +0x3cf
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:591
crypto/tls.(*Conn).readHandshakeBytes(0xc000e04008, 0x4)
	/usr/local/go/src/crypto/tls/conn.go:1078 +0x51
crypto/tls.(*Conn).readHandshake(0xc000e04008, {0x0, 0x0})
	/usr/local/go/src/crypto/tls/conn.go:1089 +0x39
crypto/tls.(*Conn).clientHandshake(0xc000e04008, {0x534f218, 0xc000e12000})
	/usr/local/go/src/crypto/tls/handshake_client.go:327 +0x512
crypto/tls.(*Conn).handshakeContext(0xc000e04008, {0x534f218, 0xc000d784b0})
	/usr/local/go/src/crypto/tls/conn.go:1568 +0x3a6
crypto/tls.(*Conn).HandshakeContext(...)
	/usr/local/go/src/crypto/tls/conn.go:1508
net/http.(*persistConn).addTLS.func2()
	/usr/local/go/src/net/http/transport.go:1651 +0x6e
created by net/http.(*persistConn).addTLS in goroutine 34
	/usr/local/go/src/net/http/transport.go:1647 +0x309

goroutine 23 [select]:
crypto/tls.(*Conn).handshakeContext.func2()
	/usr/local/go/src/crypto/tls/conn.go:1544 +0x86
created by crypto/tls.(*Conn).handshakeContext in goroutine 22
	/usr/local/go/src/crypto/tls/conn.go:1543 +0x285
```

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Fixes #35222

```release-note
Fixed Cilium CLI fatal error: concurrent map read and map write
```

### CODE REVIEW

**Comment by michi-covalent** [comment]
@tommyp1ckles ping! 🏓 

i asked @chaunceyjiang to add a bit more description in the commit message about how this fixes the issue 🚀🙏

**Review by aanm — APPROVED** [review]

**Comment by pchaigno** [comment]
@chaunceyjiang We had to revert this pull request in https://github.com/cilium/cilium/pull/35391 as the end-to-end upgrade test was failing in several configurations (cf. https://github.com/cilium/cilium/actions/runs/11328217910).

**Comment by chaunceyjiang** [comment]
>  as the end-to-end upgrade test was failing in several configurations (cf.

@pchaigno 🙀，let me take a look at this issue. The end-to-end upgrade test passed successfully when I merged this PR.

**Pull request merged**
