### PR TITLE
test: Wait for at least one Istio POD to get ready

### PR DESCRIPTION
**Pull request by jrajahalme**
BACKPORTED:

 * #9049 -- test: Wait for at least one Istio POD to get ready (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 9049; do contrib/backporting/set-labels.py $pr done 1.4; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9156)

### CODE REVIEW

**Comment by jrajahalme** [comment]
never-tell-me-the-odds

**Comment by ianvernon** [comment]
Apt issues: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14893/execution/node/107/log/

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
never-tell-me-the-odds

**Pull request merged**
