### PR TITLE
datapath: Return early if SVC is not found

### PR DESCRIPTION
**Pull request by brb**
In the case of k8s external-ip svc being enabled, stop executing the `nodeport_lb{4,6}` helper functions if a service for the given skb is not found.

The functions are used to load-balance requests to service endpoints, so it is fine to return early if a svc is not found.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9800)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by mrostecki** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
The return makes the helper functions to bypass NodePort svc traffic. Closing for now.

**Pull request closed without merging**
