### PR TITLE
Update Go to 1.16.7

### PR DESCRIPTION
**Pull request by tklauser**
First commit remove an unnecessary step from the `update-golang-image.sh` script, second commit updates Go to 1.16.7 and updates to new Cilium images built with that version.

Supersedes #16866

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Review by gandro — APPROVED** [review]
Nice catch with the alpine variant!

**Comment by tklauser** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-gke

**Review by borkmann — APPROVED** [review]

**Comment by tklauser** [comment]
test-1.21-4.9

**Pull request merged**
