### PR TITLE
Prepare for release v1.2.5

### PR DESCRIPTION
**Pull request by ianvernon**
Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5969)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
All tests passed except for Kafka on K8s 1.7 - this is a known flake in v1.2 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7468

I think this is OK to merge.

**Review by tgraf — APPROVED** [review]

**Pull request merged**
