### PR TITLE
v1.13 Backports 2023-04-20

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #23880 (@joamaki)
 * [x] #23751 (@squeed)
 * [x] #24760 (@ferozsalam)
 * [x] #24874 (@tklauser)
 * [x] #24786 (@hemanthmalla)
 * [x] #24869 (@tklauser)
 * [x] #24942 (@sayboras)
 * [x] #24825 (@christarazi)
 * [x] #25067 (@christarazi)
 * [x] #24951 (@aanm)
 * [x] #24939 (@jrajahalme)
 * [x] #24850 (@pchaigno)
 * [x] #24993 (@giorio94)
 * [x] #24785 (@giorio94)
 * [x] #24985 (@harsimran-pabla)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 23880 23751 24760 24874 24786 24869 24942 24825 25067 24951 24939 24850 24993 24785 24985; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=23880,23751,24760,24874,24786,24869,24942,24825,25067,24951,24939,24850,24993,24785,24985
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.13

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by christarazi — APPROVED** [review]

**Review by harsimran-pabla — APPROVED** [review]

**Review by ferozsalam — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Review by hemanthmalla — APPROVED** [review]
LGTM for my commit. Thanks.

**Review by sayboras — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
My commits look good. Thanks!

**Review by squeed — APPROVED** [review]

**Comment by nbusseneau** [comment]
All CI passed, awaiting missing reviews before setting `ready-to-merge`.

**Review by aanm — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by sayboras** [comment]
Rebased with latest v1.13 branch to fix egress test failures

**Comment by sayboras** [comment]
/test-backport-1.13

**Comment by sayboras** [comment]
/test-1.21-4.19

**Comment by sayboras** [comment]
/test-1.22-4.19

**Comment by sayboras** [comment]
/test-1.24-4.19

**Comment by sayboras** [comment]
/test-1.26-net-next

**Review by joamaki — APPROVED** [review]

**Comment by sayboras** [comment]
/test-1.26-net-next

**Comment by squeed** [comment]
Filed #25119 for N/S loadbalancing flake.

**Review by jrajahalme — APPROVED** [review]

**Comment by sayboras** [comment]
Considered the all reviews are in, one flake is tracked in https://github.com/cilium/cilium/issues/25119.

Marking this ready to merge.

**Pull request merged**
