### PR TITLE
update k8s library versions

### PR DESCRIPTION
**Pull request by aanm**
k8s 1.19.16, 1.20.15 and 1.21.9

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
/test-backport-1.10

**Comment by aanm** [comment]
/test-1.16-netnext

**Comment by aanm** [comment]
/ci-gke-1.10

**Review by kkourt — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Comment by kkourt** [comment]
@aanm should we ignore CodeQL failures https://github.com/cilium/cilium/pull/18588/checks?check_run_id=4904401458 ?

**Comment by aanm** [comment]
@kkourt yes since they were not introduced on this PR.

**Pull request merged**
