### PR TITLE
v1.10: images/runtime: update CNI plugins to 1.1.1

### PR DESCRIPTION
**Pull request by tklauser**
This allows Cilium to run in environments using containerd which do not
have a `loopback` CNI plugin binary available.

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.10

**Review by nbusseneau — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by tklauser** [comment]
/test-backport-1.10

**Comment by aanm** [comment]
/test-1.19-5.4

**Review by kaworu — APPROVED** [review]

**Pull request merged**
