### PR TITLE
Documentation fixups

### PR DESCRIPTION
**Pull request by joestringer**
- docs: Fix documentation build
- docs: Fix release steps enumeration

Fixes: #16238

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]
Looks good to me, thanks!

Notes:
- First commit will likely conflict with #16469, but your PR should probably go in first.
- Second commit is also addressed in #16474 (in a similar way, so no conflict to expect).

**Comment by qmonnet** [comment]
According to @bmcustodio, the first commit is entirely covered by #16469, so I suppose I was wrong and we should probably focus on his PR instead.

**Review by aditighag — APPROVED** [review]
Thanks!

**Review by bmcustodio — COMMENTED** [review]
I'd propose we stick to https://github.com/cilium/cilium/pull/16469 for the reasons @qmonnet mentioned — plus it avoids adding `dsrDispatch` to the spellchecker as that's not captured by `helm-docs` anymore.

**Comment by joestringer** [comment]
OK perfect, what I'm hearing is that this PR was superseded by the combination of https://github.com/cilium/cilium/pull/16474 and https://github.com/cilium/cilium/pull/16469. I can then close this out.

**Pull request closed without merging**
