### PR TITLE
1.4 backports

### PR DESCRIPTION
**Pull request by tgraf**
* PR: 7031 -- doc: Update grafana dashboard and add to docs (@tgraf) -- https://github.com/cilium/cilium/pull/7031
 * PR: 7026 -- bpf: Fix drop notifications for local identities (@tgraf) -- https://github.com/cilium/cilium/pull/7026
 * PR: 7025 -- docs: fixed copy buttons icon (@geakstr) -- https://github.com/cilium/cilium/pull/7025
 * PR: 6969 -- Installation & upgrade guide improvements for 1.4 (@tgraf) -- https://github.com/cilium/cilium/pull/6969
 * PR: 6995 -- [Docs] Note about apiserver outside of cluster (@nebril) -- https://github.com/cilium/cilium/pull/6995

```
$ for pr in 7031 7026 7025 6969 6995; do contrib/backporting/set-labels.py $pr pending 1.4; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7035)

### CODE REVIEW

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Comment by tgraf** [comment]
The backport script is broken for 4b401fa67359599f4b1c9fba0a70452902b1aa1a for some reason

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Pull request merged**
