### PR TITLE
pkg/ipcache: remove stale identity to IP mappings from XDS cache upon identity update for endpoint

### PR DESCRIPTION
**Pull request by ianvernon**
If the identity is updated for an endpoint, the XDS cache not only needs to have the new
identity to list of IPs mapping updated, it needs to have the old identity to IP mapping
updated as well to account that the IP for which a key-value store Create or Modify event
no longer maps to its old identity. Delete the identity from the XDS cache if it no longer
maps to any IPs in the IPIdentityCache, or update it with the list of IPs that it still
maps to.

Signed-off by: Ian Vernon <ian@cilium.io>

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]
I cherry-picked and tried this out, works as intended!

**Comment by ianvernon** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Now the runtime tests fail to even start properly, seems completely independent of these changes!

**Review by rlenglet — APPROVED** [review]

**Comment by tgraf** [comment]
```
    runtime: Documentation dependency 'snowballstemmer' not found.
    runtime: Run 'pip install -r Documentation/requirements.txt'
    runtime: Makefile:24: recipe for target 'check-requirements' failed
    runtime: make[1]: *** [check-requirements] Error 2
```

Did we upgrade the vagrant box?

**Comment by tgraf** [comment]
test-me-please

**Comment by jrajahalme** [comment]
@tgraf Vagrant box was very recently updated:
```
5c9efe0c00 (Eloy Coto       2018-03-29 16:00:03 +0200 108)         config.vm.box_version = "46"
```

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
test failed:
```
03:53:42   Updating Cilium stable to master [It]
03:53:42   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:270
03:53:42 
03:53:42   Cannot curl app1-service
03:53:42   Expected
03:53:42       <bool>: false
03:53:42   to be true
03:53:42 
03:53:42   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Updates.go:123
03:53:42 ------------------------------
03:53:42 SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
03:53:42 
03:53:42 Summarizing 1 Failure:
03:53:42 
03:53:42 [Fail] K8sValidatedUpdates [It] Updating Cilium stable to master 
03:53:42 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Updates.go:123
03:53:42 
03:53:42 Ran 1 of 272 Specs in 626.282 seconds
03:53:42 FAIL! -- 0 Passed | 1 Failed | 0 Pending | 271 Skipped --- FAIL: TestTest (626.29s)
```

Build link: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/1800/execution/node/59/log/

Will investigate tomorrow; triggering another build for now.

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
