### PR TITLE
v1.8 backports 2020-07-28

### PR DESCRIPTION
**Pull request by christarazi**
* #12640 -- backporting: Report progress in set-labels.py (@pchaigno)
 * #12626 -- .travis:fix up TestSpanStatRaceCondition failure (@Jianlin-lv)
 * #12632 -- hubble/relay: split server code into a relay/observer and relay/server (@Rolinh)
 * #12654 -- hubble/relay: fix report of unavailable nodes (@Rolinh)
 * #12651 -- bpf: change tcp slot selection to prandom instead of cookie (@borkmann)
 * #12652 -- api: add missing audit mode enum values for EndpointPolicyEnabled (@tklauser)
 * #12659 -- doc: Clarify post-release steps (@christarazi)
 * #12521 -- health: Differentiate between unknown and unreachable state (@mrostecki)
 * #12683 -- Use the global Azure key (@gravis)
 * #12655 -- hubble/relay: report nodes connectivity status on ServerStatus (@Rolinh)
 * #12685 -- hubble/relay: fix unavailable nodes count on ServerStatus (@Rolinh)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12640 12626 12632 12654 12651 12652 12659 12521 12683 12655 12685; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Review by tklauser — APPROVED** [review]
:+1: for my change

**Comment by christarazi** [comment]
test-backport-1.8

**Review by rolinh — APPROVED** [review]

**Comment by Rolinh** [comment]
test-backport-1.8

**Comment by Rolinh** [comment]
@christarazi I resolved the conflicts for #12655 and #12685 and updated the PR.

**Review by gandro — APPROVED** [review]

**Pull request merged**
