### PR TITLE
gha: Bump cilum cli version to v0.11.6

### PR DESCRIPTION
**Pull request by sayboras**
Signed-off-by: Tam Mach <tam.mach@cilium.io>

### CODE REVIEW

**Comment by sayboras** [comment]
Testing was done with temp commit

https://github.com/cilium/cilium/runs/6441621811?check_suite_focus=true --> aws cni
https://github.com/cilium/cilium/runs/6441621718?check_suite_focus=true --> ci-eks
https://github.com/cilium/cilium/runs/6441621725?check_suite_focus=true --> ci-gke
https://github.com/cilium/cilium/runs/6441621883?check_suite_focus=true ---> external workload is successful now

**Comment by sayboras** [comment]
Drop the temp commit and mark ready for review.

**Review by pchaigno — APPROVED** [review]

**Comment by jibi** [comment]
Given that this is now marked for backport, all `-v1.11` workflows in the `master` branch should be updated as well

**Comment by jibi** [comment]
Dropping the `needs-backport/1.11` label: we only need to backport the Kind workflow, but in v1.11 it's already bumped to `v.0.11.7`: https://github.com/cilium/cilium/blob/d2db1ad319cda44b3ee8682e816fa38e33d7c8d7/.github/workflows/conformance-kind.yaml#L26

**Pull request merged**
