### PR TITLE
[v1.16] add feature metrics

### PR DESCRIPTION
**Pull request by aanm**
* [x] #35852 (@aanm)
 * [x] #36077 (@aanm)
 * [x] #36078 (@aanm)
 * [x] #36209 (@aanm)
 * [x] #36234 (@aanm)
 * [x] #36236 (@aanm)
 * [x] #36298 (@aanm)
 * [x] #36203 (@aanm)
 * [x] #36397 (@aanm)
 * [x] #36355 (@aanm)
 * [x] #36402 (@aanm)
 * [x] #36461 (@aanm)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 35852 36077 36078 36209 36234 36236 36298 36203 36397 36355 36402 36461
```

**Note for reviewers**: any of the test failures can be explained with the fact that some workflows are not able to pull the github action from the stable branches because they are not available there yet. However, PR https://github.com/cilium/cilium/pull/36584 contains a dummy commit against this branch so we can properly test if the workflows work correct. Thus, the CI should be green on that PR.

### CODE REVIEW

**Comment by aanm** [comment]
/test-backport-1.16

**Comment by aanm** [comment]
/test-backport-1.16

**Comment by aanm** [comment]
/test-backport-1.16

**Comment by aanm** [comment]
/test-backport-1.16

**Review by christarazi — APPROVED** [review]

**Pull request merged**
