### PR TITLE
datapath: Do not return len in find_dsr_v6

### PR DESCRIPTION
**Pull request by brb**
Previously, `find_dsr_v6()` returned a len instead of 0 once no IPv6 extension could have been found. A non-zero len was considered as an error which made any packet sent to endpoint via IPv6 to be dropped (when DSR was enabled).

Fixes: 5fbf127e ("datapath: Support multiple IPv6 extensions with DSR")

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9933)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Comment by joestringer** [comment]
VM provision failed. Retrying.

**Comment by joestringer** [comment]
test-me-please

**Comment by aanm** [comment]
```
Suite-k8s-1.17.K8sIstioTest Istio Bookinfo Demo Tests bookinfo inter-service connectivity
Suite-k8s-1.17.K8sDemosTest Tests Star Wars Demo
Suite-k8s-1.17.K8sPolicyTest Basic Test TLS policy
Suite-k8s-1.17.K8sPolicyTest Basic Test Redirects traffic to proxy when no policy is applied with proxy-visibility annotation Tests HTTP proxy visibility without policy
Suite-k8s-1.17.K8sPolicyTest Basic Test Redirects traffic to proxy when no policy is applied with proxy-visibility annotation Tests proxy visibility interactions with policy lifecycle operations
Suite-k8s-1.17.K8sChaosTest Connectivity demo application Endpoint can still connect while Cilium is not running
Suite-runtime.RuntimePrivilegedUnitTests Run Tests
Suite-runtime.RuntimeLB Services Policies tests with conntrack enabled
```

**Comment by aanm** [comment]
test-me-please

**Comment by brb** [comment]
CI failed due to the Runtime memcache flake

**Comment by brb** [comment]
test-me-please

**Pull request merged**
