### PR TITLE
ci: log in to docker in vagrant boxes

### PR DESCRIPTION
**Pull request by nebril**

### CODE REVIEW

**Comment by nebril** [comment]
test-only --focus="NoTests"

**Comment by nebril** [comment]
test-only --focus="K8sConformance"

**Comment by nebril** [comment]
test-only --focus="K8sConformance"

**Comment by nebril** [comment]
test-only --focus="K8sConformance"

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-upstream-k8s

**Review by christarazi — APPROVED** [review]

**Comment by nebril** [comment]
Cilium-PR-Ginkgo-Tests-K8s  failed because of a known flake

**Pull request merged**
