### PR TITLE
Service load-balancing differentiates between protocols

### LINKED ISSUE #9207: Differentiate between UDP and TCP services
Currently, we do not differentiate between UDP and TCP services both in the BPF datapath and cilium-agent which means that services of different L4 protocols with the same port number cannot co-exist.

Solving the issue should be thoroughly thought, as we don't want to break the ongoing connections.

### PR DESCRIPTION
**Pull request by akhilles**
Builds off the work started by @aojea in https://github.com/cilium/cilium/pull/26399.

TODO:
- [x] Add double lookup in datapath to preserve compat
- [ ] TC eBPF unit tests
- [ ] XDP eBPF unit tests
- [ ] Add agent support for setting protocol in services map
- [ ] Add a feature flag that's disabled by default
- [ ] Update backend address API spec
- [ ] Update docs
- [ ] Integration tests
- [ ] Update `cilium-dbg` CLI

Fixes: #9207

```release-note
Service load-balancing differentiates between protocols
```

### CODE REVIEW

**Comment by i404788** [comment]
@akhilles are you planning to work on this still? If not I would like to continue working from this PR.

**Comment by aojea** [comment]
> @akhilles are you planning to work on this still? If not I would like to continue working from this PR.

please go ahead

**Comment by abhay-krishna** [comment]
@i404788 are you currently working on a fix? We are currently blocked by this issue and were wondering if it's being actively worked on.

**Comment by i404788** [comment]
@abhay-krishna haven't started yet as other tasks got in between, still plan to work on it eventually as it blocks us as well but it's lower priority. Feel free to pick it up if you need it in short order

**Comment by lizrice** [comment]
Reopening because of https://github.com/kubernetes/kubernetes/pull/120069

**Comment by oblazek** [comment]
maybe we can link the final implementation? https://github.com/cilium/cilium/pull/33434

**Pull request closed without merging**
