### PR TITLE
v1.9 backports 2022-05-31

### PR DESCRIPTION
**Pull request by jibi**
* #16647 -- ipsec: Fix off-by-one error on max keyID (@pchaigno)
 * #19885 -- docs: Add docs-builder build as dependency to live preview (@qmonnet)
 * #19927 -- api: change "group not found" log to debug (@tklauser)
 * #19893 -- docs: Fix max SPI value for IPsec key rotations (@pchaigno)
 * #19930 -- docs: Fix incorrect FQDN flag (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16647 19885 19927 19893 19930; do contrib/backporting/set-labels.py $pr done 1.9; done
```
or with
```
$ make add-label BRANCH=v1.9 ISSUES=16647,19885,19927,19893,19930
```

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
My PRs look good. Thanks!

**Review by tklauser — APPROVED** [review]
Backport of my PR looks good, thanks!

**Comment by jibi** [comment]
/test-backport-1.9

**Review by qmonnet — APPROVED** [review]

**Comment by jibi** [comment]
/test-1.14-4.9

**Comment by jibi** [comment]
test-1.15-4.9

**Comment by jibi** [comment]
/test-1.15-4.9

**Pull request merged**
