### PR TITLE
v1.5 backported lb changes

### PR DESCRIPTION
**Pull request by borkmann**
- #9111
- #9124

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9130)

### CODE REVIEW

**Comment by borkmann** [comment]
never-tell-me-the-odds

**Comment by borkmann** [comment]
Unrelated CI failure due to provisioning errors:
```
[...]
21:31:29      k8s2-1.14: Get:40 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [4,000 B]
21:31:29      k8s2-1.14: Get:41 http://archive.ubuntu.com/ubuntu bionic-backports/universe Translation-en [1,856 B]
21:31:29      k8s2-1.14: Get:30 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,003 kB]
21:31:31      k8s2-1.14: Fetched 3,675 kB in 48s (76.5 kB/s)
21:31:31      k8s2-1.14: Reading package lists...
21:31:32      k8s2-1.14: E
21:31:32      k8s2-1.14: : 
21:31:32      k8s2-1.14: Failed to stat /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_bionic-updates_InRelease - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
21:31:32      k8s2-1.14: E
21:31:32      k8s2-1.14: : 
21:31:32      k8s2-1.14: Failed to stat /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_bionic-updates_main_binary-amd64_Packages - pkgAcqTransactionItem::TransactionState-stat (2: No such file or directory)
21:31:32      k8s2-1.14: E
21:31:32      k8s2-1.14: : 
[...]
```

**Comment by borkmann** [comment]
test-missed-k8s

**Comment by borkmann** [comment]
test-upstream-k8s

**Review by brb — APPROVED** [review]

**Comment by borkmann** [comment]
Provisioning timeout in test-upstream-k8s, retrying.

**Comment by borkmann** [comment]
test-upstream-k8s

**Pull request merged**
