### PR TITLE
v1.10 backports 2021-06-04

### PR DESCRIPTION
**Pull request by pchaigno**
* #16360 -- .github: Fix error triggered by large comments (@pchaigno)
 * #16190 -- pkg/k8s: add pod IP event change (@aanm)
 * #16381 -- endpoint: trigger k8s sync controller on identity update (@jibi)
 * #16374 -- operator: remove deprecated options (@twpayne)
 * #16373 -- helm: Fix patch failure when updating `hubble-generate-certs` (@gandro)
 * #16342 -- docs: Clarify LRP loop related note (@aditighag)
 * #16323 -- install: Allow setting enable-health-check-nodeport to 'false' (@dctrwatson)
 * #16273 -- install: fix ordering of operator resource block (@rkage)
 * #16231 -- test: Use new test-verifier image in K8sVerifier (@pchaigno)
     - Minor conflicts.
 * #16118 -- daemon: Improve logging of device auto-detection (@brb)
 * #16016 -- Clarify one-time setup for backporting (@christarazi)
 * #16380 -- helm: Disable the bandwidth manager by default (@pchaigno)
 * #16307 -- k8s, node: Restore router IPs (cilium_host) from K8s resource  (@christarazi)
 * #16423 -- Update test/packet instructions for running CI tests on dedicated instances (@christarazi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16360 16190 16381 16374 16373 16342 16323 16273 16231 16118 16016 16380 16307 16423; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by pchaigno** [comment]
test-backport-1.10

**Comment by pchaigno** [comment]
test-1.18-4.9

**Review by christarazi — APPROVED** [review]
:+1: for my commits

**Review by aanm — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Comment by pchaigno** [comment]
All tests are passing and the missing reviews are only for backports without conflicts, so I think we can merge. Marking.

**Review by jibi — APPROVED** [review]

**Pull request merged**
