### PR TITLE
daemon: preallocate prefilter spec slices with known size

### PR DESCRIPTION
**Pull request by tklauser**
These were missed in #10716

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by qmonnet — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by errordeveloper** [comment]
@tklauser ok to remove `pending-review` and megre?

**Comment by tklauser** [comment]
@errordeveloper yes, though I cannot merge myself.

**Comment by errordeveloper** [comment]
@tklauser me neither...

**Pull request merged**
