### PR TITLE
backport v1.8: Fix possible deadlock when querying netdevs

### PR DESCRIPTION
**Pull request by brb**
See commit msg.

```release-note
Fix possible deadlock when querying network interfaces for arping
```

### CODE REVIEW

**Comment by brb** [comment]
test-backport-1.8

**Comment by joestringer** [comment]
Runtime provisioning failure:
https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/3821/

Upstream also failed to provision, although the Jenkins infrastructure did not identify that as the root cause:
https://jenkins.cilium.io/job/Cilium-PR-K8s-Upstream/2878/

Travis hit a pull ratelimit from Docker:
https://travis-ci.com/github/cilium/cilium/jobs/488513594

**Comment by joestringer** [comment]
test-runtime

**Comment by joestringer** [comment]
test-upstream-k8s

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
@brb #15193 already bumps the netlink library. Is the library bump here necessary?

**Comment by brb** [comment]
test-backport-1.8

**Pull request merged**
