### PR TITLE
datapath: add controller manage to monitor cilium iptabels rules

### LINKED ISSUE #8856: Controller to monitor Cilium iptables rules
Currently, the Cilium iptables chains and rules are inserted by `(*Daemon) compileBase()` method. It first removes all the chains and rules, and then tries to install them. The method is being called from multiple places.

The problem with this approach is that during invocation of the method, the chains and rules gets removed which can cause transient connectivity / policy enforcement issues.

To address the problem, the following can be done:

1. Remove / install only the chains and rules which are missing / are in a wrong position.
2. Start a controller which would monitor rules, and in the case a user removes any of the rules, would re-install that rule without removing the rest.

### PR DESCRIPTION
**Pull request by fristonio**
Fixes #8856

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9803)

### CODE REVIEW

**Comment by brb** [comment]
@fristonio Great work so far! One suggestion - perhaps you could use `iptables-save` output to check for rules. That would allow us to avoid multiple exec's for `iptables -C`, also then you could check that order of the rules is correct.

**Comment by fristonio** [comment]
Hey @brb, yeah that makes sense. I will update the Pull Request.

**Comment by mskrocki** [comment]
Can this PR be re-opened and merged?

**Comment by brb** [comment]
> Can this PR be re-opened and merged?

@mskrocki I suggest to discuss this either in the community meeting or in the #development channel.

**Pull request closed without merging**
