### PR TITLE
v1.9 backports 2020-12-04

### PR DESCRIPTION
**Pull request by pchaigno**
* #14189 -- .travis: Run race detection builds on master commits only (@pchaigno)
 * #14238 -- vendor: update etcd to 3.4.14 (@aanm)
 * #14256 -- node: Fix ineffectual assignment (@brb)
 * #14263 -- Log host routing fallback & document kernel requirement (@pchaigno)
 * #14220 -- metricsmap: fix Prometheus exporter (@jibi)
 * #14077 -- helm: Add extraConfig in configmap template (@michi-covalent)
 * #14255 -- bpf: Fix IS_BPF_HOST macro (@pchaigno)

Skipped for now as it is causing complexity issues:

 * #14193 -- bpf: optimize dsr and add ipip support for lb-only (@borkmann)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14189 14238 14256 14263 14220 14077 14255; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by pchaigno** [comment]
test-backport-1.9

**Review by brb — APPROVED** [review]
My changes LGTM, thanks.

**Review by borkmann — APPROVED** [review]

**Review by jibi — APPROVED** [review]
My changes looks :+1: thanks

**Review by aanm — APPROVED** [review]
Changes look good!

**Comment by pchaigno** [comment]
Runtime-4.9 failed with known flake #14125. K8s-1.12-Kernel-netnext with known flake https://github.com/cilium/cilium/issues/12596. All other required builds are passing.
We have several reviews and are only missing for Michi's. Given there were no conflicts for any of the commits, I'll mark as ready-to-merge now so that we can move on with the 1.9.1 release.

**Pull request merged**
