### PR TITLE
k8s: update k8s libraries to 1.18.12

### PR DESCRIPTION
**Pull request by aanm**
Also update k8s test versions to 1.17.14 and 1.18.12

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.8

**Comment by aanm** [comment]
test-backport-1.8

**Review by fristonio — APPROVED** [review]
LGTM. One question though, I see that for v1.8 we don't have the K8s version updated for dev VM - https://github.com/cilium/cilium/blob/v1.8/contrib/vagrant/scripts/helpers.bash#L79
Is it intended or should we also update this?

**Comment by aanm** [comment]
> LGTM. One question though, I see that for v1.8 we don't have the K8s version updated for dev VM - https://github.com/cilium/cilium/blob/v1.8/contrib/vagrant/scripts/helpers.bash#L79
> Is it intended or should we also update this?

@fristonio It depends, I never use older branches' VMs to run a Kubernetes cluster.

**Pull request merged**
