### PR TITLE
ipsec: Remove dead code for IPsec node encryption

### PR DESCRIPTION
**Pull request by pchaigno**
Node encryption for IPsec hasn't been supported since 1d2674df ("docs: ipsec: remove node-to-node encryption") and subsequent commits. The feature also wasn't working since several releases.

This commit simply removes the code for that feature. This code has no use now and makes changes to IPsec slightly more difficult.

Commit 1d2674df was merged in v1.12 so I marked this code removal for backports to v1.13 and v1.14 to simplify backports there as well.

### CODE REVIEW

**Review by jschwinger233 — COMMENTED** [review]
Should we delete `EncryptNode` field definition at the same time?

**Comment by pchaigno** [comment]
> Should we delete `EncryptNode` field definition at the same time?

Do you mean the flag? It's still used for WireGuard node encryption.

**Review by jschwinger233 — APPROVED** [review]

**Pull request merged**
