### PR TITLE
Endpoint: Log policyRevision on endpoint log.

### PR DESCRIPTION
**Pull request by eloycoto**
To make debugging easier, add the policyRevision in the endpoint log
status message.

Related to #4514

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4516)

### CODE REVIEW

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
@raybejjani PTAL as well

**Comment by eloycoto** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by raybejjani** [comment]
Should we also store the revision number in the in-endpoint log? it's relevant there as well.

Separately, do we also need to record nextPolicyRevision since it is that revision that is causing some of the logged events/actions we see.

**Comment by eloycoto** [comment]
@raybejjani I'm happy to add another field in the endpoint log, that can be the policyVersion. It'll help a lot with the debugging.

**Comment by raybejjani** [comment]
shrug. Maybe the reviewers had a reason not to suggest it?

**Pull request merged**
