### PR TITLE
cleanup: code cleanup to remove unused parameter from repository add api

### PR DESCRIPTION
**Pull request by tamilmani1989**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Removing unused parameter from add api and also from other references in unit tests which uses this api

### CODE REVIEW

**Comment by tamilmani1989** [comment]
@aditighag / @tommyp1ckles  can i get review on this PR?

**Comment by tommyp1ckles** [comment]
@tamilmani1989 nice cleanup thanks 😄 , code changes look good.   Only thing is the commit message "fix: ..." makes it seem like this is fixing a bug or similar.  I think the commit title should make it clear that this is just a code cleanup.

**Comment by tamilmani1989** [comment]
@tommyp1ckles i fixed the title and commit message. Let me know if there any other concerns

**Comment by tamilmani1989** [comment]
these ci failures look unrelated to this PR. Looks like flaky.

1. allow-all-with-metrics-check/pod-to-pod/curl-ipv4-3: cilium-test/client2-f59f448f9-mpv55 (10.244.1.199) -> cilium-test/echo-same-node-77d94449fc-5w7q2 (10.244.1.83:8080)
2. connection reset in `Fetch Artifacts` step 
```
Run cilium/little-vm-helper@908ab1ff8a596a03cd5221a1f8602dc44c3f906d
Run ssh -p 2222 -o "StrictHostKeyChecking=no" root@localhost << EOF
Pseudo-terminal will not be allocated because stdin is not a terminal.
kex_exchange_identification: read: Connection reset by peer
Connection reset by 127.0.0.1 port 2222
Error: Process completed with exit code 255.
```

**Review by aditighag — APPROVED** [review]

**Comment by tamilmani1989** [comment]
@aditighag @tommyp1ckles is this PR good to merge now?

**Comment by aditighag** [comment]
> @aditighag @tommyp1ckles is this PR good to merge now?

It was waiting on a review. But since it's a simple change, and CI is green, I'll go ahead and mark it as ready for merge.

**Pull request merged**
