### PR TITLE
examples: remove blank line at end of dns.yaml

### PR DESCRIPTION
**Pull request by ianvernon**
This caused the policy validation CI test to fail.

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6589)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Validated that this works locally.

**Review by joestringer — APPROVED** [review]
Thanks!

**Comment by ianvernon** [comment]
Merging, the change is self-evident and the build passed.

**Pull request merged**
