### PR TITLE
[WIP]AWS ENI support for IPv6

### LINKED ISSUE #18405: ENI IPv6 support
## Proposal / RFE

AWS released IPv6 on EKS https://aws.amazon.com/blogs/aws/amazon-elastic-kubernetes-service-adds-ipv6-networking/.

Now eager to see this land in cilium :)

### PR DESCRIPTION
**Pull request by zhenggu**
I am trying to add the feature of ENI support on IPv6, but I find many things need to be discussed:
1. Support IPv6 prefix delegation feature is impossible, the feature of IPv4 is [here](https://github.com/cilium/cilium/pull/18463), for IPv4, the prefix is /28, and the count of IPs which assigned once is 16, it is easy to handle, but for IPv6, the prefix is /80, so the count of IPs will be 281474976710656, it will take too much time to use function ip.PrefixToIps to generate the IP list, and also it wastes too much memory and disk.
2. I am not very much [the functions under interface NodeOperations](https://github.com/cilium/cilium/blob/665b4fc32103a296d77074c2b3ff3a13f917c751/pkg/ipam/node_manager.go#L42) are IPv6 supported or not, for the current implement , they are all IPv4 only, such as AllocateIPs/ReleaseIPs. another example is ResyncInterfacesAndIPs, the second return value of it means how many ENIs which still has available IPs in AWS, if IPv4 IP address is not  available, and IPv6 addresses are still available, will we +1 for this value? Should we create new functions for IPv6 requirement or we can just reuse these functions?
3. How will we store the IPv6 addresses in CiliumNode. Currently, we use spec.ipam.pool/status.eni.enis to store the the allocated IPv4 addresses, and use status.ipam.used to store the used ones. Will we reuse it or create new parameters for IPv6? I guess reuse the currently parameter will be better.
4. The [MaxIPsToAllocate](https://github.com/cilium/cilium/blob/665b4fc32103a296d77074c2b3ff3a13f917c751/pkg/ipam/node.go#L625) is for IPv4 only, can it be used for ipv6 or we need another parameter for it?
5. Which type of [AvailableIPv6ForAllocation](https://github.com/zhenggu/cilium/blob/ca277956047ee30b84756337e8a91c451614cae5/pkg/ipam/node.go#L545) will be used, I think maybe int is not enough for it, but the interesting thing is that [AWS use Integer as the type of Ipv6AddressCount](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssignIpv6Addresses.html)

### CODE REVIEW

**Comment by pchaigno** [comment]
Converting to draft given WIP tag. I would encourage to discuss these open questions in Slack and maybe even to create a CFP for it.

**Comment by gandro** [comment]
Thanks a lot for the PR. I agree that all those questions do need a discussion - I don't think a PR is a good venue for that. When we discussed the topic in the [community meeting on March 29](https://docs.google.com/document/d/1Y_4chDk4rznD6UgXPlPvn3Dc7l-ZutGajUv1eF0VDwQ/edit#heading=h.ck2ap1gf1w1i), we concluded that this likely needs a [CFP document](https://github.com/cilium/design-cfps) first, so we have a better venue to discuss all those open questions.

**Comment by zhenggu** [comment]
Thanks @gandro for your information, I am just play the cilium source code for about 2-3 weeks, and I am not very familiar about the architecture. In the CFP document, I think I should provide a proposal solution. If so, it will be very hard for me. Anyway, I will try to create one.

**Comment by gandro** [comment]
> Thanks @gandro for your information, I just play the cilium source code for about 2-3 weeks, and I am not very familiar about the architecture. In the CFP document, I think I should provide a proposal solution. If so, it will be very hard for me. Anyway, I will try to create one.

Thanks! The main goal of a CFP document is to discuss open questions (like the ones you presented in the original post). You don't necessarily need to have a ready-to-go solution proposed, but it does help having rough solution outlined, so we can see how it compares to potential alternatives.

**Comment by ajaykumarmandapati** [comment]
@zhenggu Thanks for your contributions and work so far however I see that the PR is closed due to inactivity, would this be something that can be continued to work on?
Thoughts? 👍🏾

**Pull request closed without merging**
