### PR TITLE
bpf: Shift ingress ipcache source lookup to netdev

### PR DESCRIPTION
**Pull request by joestringer**
Ingress paths may be one of the following:
* From a local endpoint. In this case the source is known.
* From the overlay. In this case the source is taken from the overlay.
* From a local netdev. In this case, we don't know the source and should
  perform a lookup to determine what we can about the source.

This final case was being implemented in the ingress policy lookup
stage, which adds complexity to the ingress BPF program and also makes
monitor output less consistent, as the actual source is not known until
that point and may not be propagated to the correct parts of the program
so that the real identity is reported in monitor output.

Solve these problems by shifting this ipcache lookup all the way back
into the netdev program.

Changes in instruction complexity on Linux 4.9.17 with GCC 7.2.0:

bpf_lxc ingress:        49458 -> 26197 (-47%)
bpf_netdev handle_ipv4: 3471 -> 4682   (+35%)
bpf_netdev handle_ipv6: 8847 -> 13326  (+50%)

Note that the complexity limit in this case is 64K on Linux 4.9, so
although we increase the complexity in each of the netdev programs by
fair margin, the decrease in complexity in the ingress lxc program
provides us significantly more margin for feature development.
Furthermore, depending on where the ipcache is called from, it clearly
has a different impact on complexity limit; In the lxc program from the
ingress policy function, it represents ~23K instructions of complexity
due to the nesting of where it is called from. In the netdev programs,
this is only 1.2K or 4.5K.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4874)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Hit #4850:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5031/testReport/junit/k8s-1/10/K8sValidatedDemosTest_Tests_Star_Wars_Demo/
[f0c5341e_K8sValidatedDemosTest_Tests_Star_Wars_Demo.zip](https://github.com/cilium/cilium/files/2204425/f0c5341e_K8sValidatedDemosTest_Tests_Star_Wars_Demo.zip)

```
Found a "NACK received for version" in Cilium logs
```

```
2018-07-18T02:21:00.340554727Z level=warning msg="[external/envoy/source/common/config/grpc_mux_impl.cc:218] gRPC config for type.googleapis.com/cilium.NetworkPolicyHosts update rejected: NetworkPolicyHosts: Duplicate host entry '10.10.0.137' for policy 11696, already mapped to 3" subsys=envoy-upstream threadID=1104
    2018-07-18T02:21:00.34056298Z level=warning msg="[bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/cilium.NetworkPolicyHosts rejected: NetworkPolicyHosts: Duplicate host entry '10.10.0.137' for policy 11696, already mapped to 3" subsys=envoy-config threadID=1104
```

**Comment by joestringer** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Comment by joestringer** [comment]
Green build. Rebasing to fix up bpf.sha.

**Pull request merged**
