### PR TITLE
Backport #2271

### PR DESCRIPTION
**Pull request by joestringer**
Backport #2271 per request as it wasn't applying cleanly.

### CODE REVIEW

**Review by raybejjani — APPROVED** [review]
approved for docs

**Review by jrfastab — APPROVED** [review]
LGTM thanks.

**Review by jrfastab — APPROVED** [review]

**Review by jrfastab — APPROVED** [review]

**Review by jrfastab — APPROVED** [review]

**Review by jrfastab — APPROVED** [review]

**Review by jrfastab — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Review by jrfastab — APPROVED** [review]
Approving as janitor.

**Comment by joestringer** [comment]
Attempting to get rid of jenkins branch build check via close / reopen.

**Comment by joestringer** [comment]
Reopening for review.

**Pull request merged**
