### PR TITLE
identity: don't regenerate endpoints whenever an identity is allocated

### PR DESCRIPTION
**Pull request by squeed**
When an identity is newly allocated, it is added to the SelectorCache, which generates an incremental policy update as relevant. However, the code as written triggered a full endpoint regeneration, which is wasteful.

Change this to perform an incremental policy map update.

This is safe because regenerating an endpoint is only necessary if the endpoint's identity has changed. However, this is not the codepath that updates endpoint identities. It is only used for propagating "remote" identities in to the policy subsystem. That comes from a different watcher, which will trigger its own regeneration.

```release-note
Reduce resource usage when updating remote identities in the policy engine.
```

### CODE REVIEW

**Comment by oblazek** [comment]
seems to me, it makes sense to backport this.. wdyt?

**Comment by squeed** [comment]
> seems to me, it makes sense to backport this.. wdyt?

That's my plan, yes!

**Review by christarazi — APPROVED** [review]
From my understanding and from digging up some git archeology, it seems that this PR is safe. 

Deducing from c2d63aa2c4e, we can see that each time `UpdateIdentities` is called, it was with `force == false`, meaning that the policy revision does **not** need to be bumped. Any time a policy changes, the policy revision is bumped. A policy change (and therefore a policy revision bump) requires a reevaluation of the policies, i.e. full calculation. Therefore, since the call to `UpdateIdentities` was always with `force == false`, we weren't doing a full recalculation anyway, which means we can move to incremental policy updates instead.

**Comment by christarazi** [comment]
It would be good to get confirmation from @jrajahalme / @joestringer as well.

**Comment by christarazi** [comment]
In regards to backports, it doesn't seem to me that this PR is a candidate for backporting as per our [criteria](https://docs.cilium.io/en/stable/contributing/release/backports/#id1).

**Comment by joestringer** [comment]
I haven't had the time to dig into this to really understand it, but I guess at a high level my question is, is there a possibility this goes too far and have we explored those possibilities? Could we be relying on this trigger at the moment in some particular case, then with this PR we end up inadvertently skipping policy recalculation? The potential impact would then have security impact.

**Comment by squeed** [comment]
> with this PR we end up inadvertently skipping policy recalculation

Very good question! We already skip policy recalculation on regeneration -- policy is only recalculated if the policy revisions do not match. Specifically, we only recalculate policy if `e.nextPolicyRevision < PolicyRepository.GetRevision()`. And, setting `e.nextPolicyRevision` is not done in the context of identity allocation, but policy upserts. So they are totally different code paths, and the regenerations triggered by identity allocation already won't recalculate policy.

I can't think of a case where identity allocation should lead to regenerating all endpoints. It doesn't recalculate policy -- the incremental changes come from the SelectorCache and `UpdatePolicyMaps()`. It doesn't update SelectorPolicy -- this code path cannot change endpoint identities, so it's only for "peer" identities. So what else could it do? We already elide regeneration when the identity is allocated by the IPCache. As far as I can tell, this is just a bunch of lock contention slowing down FQDN updates for no good reason.

**Review by jrajahalme — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
I went through the users of `UpdateIdentities()` afresh, and it seems like the main callers are coming from either local identity allocation or from remote identity allocation paths, each of which only need to inform all existing endpoints that have policies with selectors that select the new identity about how to change their policymaps. Digging into the selectorcache and the way the users are susbscribed to the changes triggered by the call here to `...GetSelectorCache().UpdateIdentities()`, it seems like the per-endpoint policymap caches should be prepared correctly by the existing call, so the extra trigger to regenerate endpoints is extraneous; we could rely just on incremental processing to push the map changes down to the datapath, like this PR proposes.

The other `UpdateIdentities()` call I see is from ipcache, but that one is not using this function, and is effectively doing exactly what the new version of this function is doing. There's even a comment there to try to refactor to reuse this function, which we probably avoided before now since it would have triggered full regeneration too frequently... This change would potentially allow us to do that cleanup too. May be something to consider after this goes through.

I'd say this does make us more dependent on incremental policy processing doing the right thing just because we won't be triggering policy recalculation as frequently. That said, I don't think that keeping the old behaviour here is necessarily the right solution if we wanted to mitigate against the risk that incremental calculation does the wrong thing. I'd rather set up some dedicated resiliency mechanisms like doing periodic extra recalculations or spot checks to validate that the policy is in the correct desired state.

**Comment by squeed** [comment]
Thanks, @joestringer, for your excellent analysis as always.

As part of expanding on this, I discovered the error 

> I'd say this does make us more dependent on incremental policy processing doing the right thing just because we won't be triggering policy recalculation as frequently.

On regeneration, we do (for policy):
1. Recalculate SelectorPolicy and EndpointPolicy **only if the endpoint's identity or PolicyRevision has changed**
2. Compute Envoy redirects
3. Compute DNS redirects
4. Push policy to Envoy
5. Push policy to DNS proxy
6. Consume incremental updates
7. Push PolicyMap to BPF

On incremental update we do:
1. Consume incremental updates
2. Push incremental updates to BPF PolicyMap
3. Push policy to Envoy

So, there are three things that could *theoretically* diverge, if we were relying on regeneration to catch a new identity/
1. proxy redirects
2. BPF PolicyMap

For 1, an incremental update cannot create new redirects. I had to read the code *very carefully* to determine this, since it does have access to the set of selections. In the future, we may wish to restrict this more formally with the type system

For 2, we already have a periodic synchronization job that detects a missed incremental update, so that's OK.

However, there is a bug: we don't update the DNS proxy on incremental updates. I only discovered this after a deep code dive.

I'll be filing an issue on this shortly, once I can characterize it a bit better.

**Comment by squeed** [comment]
> I'll be filing an issue on this shortly, once I can characterize it a bit better. We may have to revert https://github.com/cilium/cilium/pull/29865 which would be very unfortunate.

Fortunately, it's not as dire as immediately realized. This code path is only used for caching selected IPs for use on restoration, until the endpoint's first regeneration pass.

**Conclusion:**

We cannot merge this PR as-is, because it will break one specific thing: the endpoint-info caching of destination IPs to which DNS interception should apply.

Furthermore, we *probably* don't correctly re-write the cached DNS proxy destination IPS in the case where new CoreDNS pods are scheduled without any new identities being allocated. I am currently validating this. This would only cause traffic loss between agent restart and endpoint restoration.

**Comment by joestringer** [comment]
Marking as draft as this is not actively progressing. I'm also a little nervous that the comments above report this PR will break something but all of CI is passing. That'd be another thing to look into.

**Pull request closed without merging**
