### PR TITLE
[v1.15] images: Update bpftool, checkpatch images

### PR DESCRIPTION
**Pull request by qmonnet**
- https://github.com/cilium/cilium/pull/31753

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31753
```

This backport was initially part of #31890, but got tossed out due to the necessity to regenerate the images.

### CODE REVIEW

**Comment by qmonnet** [comment]
/test-backport-1.15

**Comment by tommyp1ckles** [comment]
@qmonnet sorry about the description edit, I needed to copy the backport description format from somewhere and I accidentally hit save 😓 Everything should be as it was.

**Review by brlbil — APPROVED** [review]

**Comment by qmonnet** [comment]
Ready to merge after TopHat review (and when we have the green light from release managers to merge on v1.15 again).

**Comment by aditighag** [comment]
@qmonnet The PR needs to be rebased as there are a bunch of conflicts.

**Comment by qmonnet** [comment]
/test-backport-1.15

**Comment by qmonnet** [comment]
/test-backport-1.15

**Comment by qmonnet** [comment]
@aditighag Thank you, I rebased and had the images re-generated

**Pull request merged**
