### PR TITLE
v1.14 Backports 2023-11-15

### PR DESCRIPTION
**Pull request by gandro**
* [x] #28557 (@dylandreimerink)
    * :warning: Conflicts in the lbipam unit test, as it did not have any leak check before in v1.14
 * [x] #28959 (@julianwiedmann)
 * [x] #28264 (@aspsk)
 * [x] #29007 (@mhofstetter)
    *  :warning: Conflicts in the following files
    *  operator/pkg/gateway-api/tlsroute.go Conflicts due to Gateway resoruce version (v1 vs v1beta1)
    *  operator/pkg/gateway-api/httproute.go Conflicts due to Gateway resoruce version (v1 vs v1beta1)
    *  operator/pkg/gateway-api/grpcroute.go Conflicts because the file does not exist in v1.14
 * [x] #27062 (@gentoo-root)
    * :warning: Conflicts due to "cilium-dbg" and "pkg/time" rename
 * [ ] #29077 (@meyskens)

PRs skipped due to conflicts:

 * #28896 (@mhofstetter)
 * #29115 (@sayboras)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 28557 28959 28264 29007 27062 29077
```

### CODE REVIEW

**Comment by gandro** [comment]
> Seems that the fixup got lost? It's still `probes.Jiffies()` there.

This is v1.14, which does have probes.Jiffies!

**Review by julianwiedmann — APPROVED** [review]

**Review by gentoo-root — APPROVED** [review]

**Comment by gandro** [comment]
/test-backport-1.14

**Review by mhofstetter — APPROVED** [review]
Thanks for resolving the conflicts @gandro  :pray: will take care of backporting my other PR manually to `v1.14`

**Review by aspsk — APPROVED** [review]

**Comment by gandro** [comment]
- [ci-ginkgo](https://github.com/cilium/cilium/actions/runs/6877820117/job/18706208373) hit a vm provisioning error. Restarting.

**Review by dylandreimerink — APPROVED** [review]

**Pull request merged**
