### PR TITLE
v1.12 backports 2022-08-23

### PR DESCRIPTION
**Pull request by aditighag**
* ~#20853 -- ingress: Support clustermesh service affinity (@sayboras)~
 I tried resolving the conflicts, but it seems like there was a change that changed []backends to []*backends, and that wasn't backported. @sayboras I skipped it.
 * #20865 -- k8s/watchers: fix panic in CiliumEndpoint labels update (@jaffcheng)
 * #20911 -- pkg/endpoint: set namedPortsGetter interface on ParseEndpoint (@aanm)
 * #20313 -- Add ArgoCD issues notes in the official documentation (@Kikiodazie)
 * #20623 -- docs: second set of video contents added (@Kikiodazie)
 
 * #20895 -- don't merge stderr into iptable stdout (@liuyuan10)
Resolved minor conflict around imports.

 * #20973 -- docs: Add available options for Ingress Controller annotations (@NikhilSharmaWe)
* ~#20860 -- ingress: Propagate required annotations from Ingress to LB Service (@NikhilSharmaWe)~
I was able to resolve other conflicts, except the ones in cmd/root.go, looks like that file doesn't exist. I wasn't able to find the other variables from the file in v1.12 source code. @aanm/ @sayboras I skipped the backport for this PR. 

 * #21015 -- gh/workflows: stop using ubuntu-18.04 runner (@julianwiedmann)
 * #20977 -- metrics: fix ts_events API timestamp and scope label cardinality (@tommyp1ckles)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20865 20911 20313 20623 20895 20973 21015 20977; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Comment by aditighag** [comment]
/test-backport-1.12

**Comment by sayboras** [comment]
> https://github.com/cilium/cilium/pull/20853 -- ingress: Support clustermesh service affinity

I will take care of this manually, thanks 💯 

> https://github.com/cilium/cilium/pull/20860 -- ingress: Propagate required annotations from Ingress to LB Service 

Will take another look for this 💯

**Comment by aditighag** [comment]
4.9s hit - https://github.com/cilium/cilium/issues/20288.
gke - https://github.com/cilium/cilium/issues/21055

Documentation failure is legit - 

```
Please fix the following spelling mistakes:
* Documentation/further_reading.rst:19: (SRv)  Cloud Native Telco Day, Europe 2022 - Leveraging Cilium and SRv6 for Telco Networking:

If the words are not misspelled, run:
Documentation/update-spelling_wordlist.sh SRv 
```

Screen Shot 2022-08-23 at 5 33 28 PM
.

**Comment by aditighag** [comment]
The last push only updated the documentation commit - 


Documentation Updates / Validate & Build HTML (pull_request) Successful in 1m

**Pull request merged**
