### PR TITLE
bpf: dedicated functions for per-packet lb xlate

### PR DESCRIPTION
**Pull request by ldelossa**
House-keeping task which introduces dedicated inline functions for per-packet-lb service translation on pod egress.

Cleans up the __handle_ip* methods in bpf_lxc.c so they can be dedicated to expressing the packet flow.

Signed-off-by: Louis DeLosSantos <louis.delos@isovalent.com>

```release-note
introduces dedicated inline functions for per-packet-lb service translation on pod egress
```

### CODE REVIEW

**Comment by ldelossa** [comment]
Hold in draft until: https://github.com/cilium/cilium/pull/22936 merged, then rebase.

**Comment by ldelossa** [comment]
/test-1.25-4.19

**Review by NikAleksandrov — APPROVED** [review]

**Comment by ldelossa** [comment]
Some combination of macro defs are causing a preprocessor failure:

```
2023-02-18T16:03:44.512566091Z level=error msg="Failed to compile bpf_lxc.dbg.o: exit status 1" compiler-pid=569 linker-pid=573 subsys=datapath-loader
2023-02-18T16:03:44.512582579Z level=warning msg="/var/lib/cilium/bpf/bpf_lxc.c:721:6: error: expected value in expression" subsys=datapath-loader
2023-02-18T16:03:44.512584803Z level=warning msg="#elif" subsys=datapath-loader
2023-02-18T16:03:44.512586851Z level=warning msg="     ^" subsys=datapath-loader
2023-02-18T16:03:44.512588449Z level=warning msg="/var/lib/cilium/bpf/bpf_lxc.c:1217:6: error: expected value in expression" subsys=datapath-loader
2023-02-18T16:03:44.512589996Z level=warning msg="#elif" subsys=datapath-loader
2023-02-18T16:03:44.512591526Z level=warning msg="     ^" subsys=datapath-loader
2023-02-18T16:03:44.512593196Z level=warning msg="2 errors generated." subsys=datapath-loader
2023-02-18T16:03:44.512676230Z level=debug msg="JoinEP: Failed to compile" debug=true error="Failed to compile bpf_lxc.dbg.o: exit status 1" params="&{Source:bpf_lxc.c Output:bpf_lxc.dbg.o OutputType:obj Options:[]}" subsys=datapath-loader
```

Odd that we don't catch this is `make build` or `make build_all` but must be a combination used for the particular failing ginkgo test: `K8sPolicyTestExtended_Validate_toEntities_KubeAPIServer_Allows_connection_to_KubeAPIServer`

**Comment by ldelossa** [comment]
/test-1.25-4.19

**Comment by ldelossa** [comment]
/test-1.26-net-next

**Comment by ldelossa** [comment]
Spoke with @jibi and the `net-next` errors can be ignored, they are unrelated to this PR.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
I've changed the release-note label given there is no user-visible impact here.

**Pull request merged**
