### PR TITLE
test: remove leftovers of running own registry in GKE tests

### PR DESCRIPTION
**Pull request by tklauser**
As of commit ce72454b3a93 ("ci: use quay.io images in gke builds") the
GKE tests no longer run their own registry. Remove any leftover scripts
and manifests related to running our own registry.

clean-local-registry-tag.sh is already unused since commit 9cbc1512e694
("ci: Start separate registries for gke builds")

### CODE REVIEW

**Comment by tklauser** [comment]
test-gke

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
Tested draft successfully on GKE. Now re-running to confirm this has no side effects on other CI jobs.

**Review by christarazi — APPROVED** [review]
:broom:

**Pull request merged**
