### PR TITLE
Dockerfile: adding envoy Dockerfile

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by jrajahalme** [comment]
How would I test this locally? Other Dockerfiles are referenced from contrib/packaging/docker, but this is not. Should it be?

**Comment by tgraf** [comment]
> How would I test this locally? Other Dockerfiles are referenced from contrib/packaging/docker, but this is not. Should it be?

I think we should actually move over to multi stage builds. I have a local branch that I will push. It works except for the incremental builds. I think we can combine it with your tarball approach.

**Comment by aanm** [comment]
I just wanted to push this as PR in case someone wants to rebuild docker image

**Comment by jrajahalme** [comment]
Being a total docker noob I would appreciate instructions on how to rebuild the docker image using this. Are additional steps/rights needed to make a new build available to others, and how to avoid accidentally destroying a working image others might be using etc.

**Comment by aanm** [comment]
@jrajahalme I can close this PR since #2452 was merged?

**Comment by jrajahalme** [comment]
> On Jan 11, 2018, at 8:36 AM, André Martins <notifications@github.com> wrote:
> 
> @jrajahalme <https://github.com/jrajahalme> I can close this PR since #2452 <https://github.com/cilium/cilium/pull/2452> was merged?
> 

Right.

**Pull request closed without merging**
