### PR TITLE
Added the declaration of license

### PR DESCRIPTION
**Pull request by yulng**
Need to declare the license at the beginning of the file
Signed-off-by: yulng  <wei.yang@daocloud.io>

### CODE REVIEW

**Review by aditighag — CHANGES_REQUESTED** [review]
Thanks! Can you sign-off the commit - https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#developer-s-certificate-of-origin?

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Just waiting on @yulng to add sign-off into the commit per the instructions above. Cilium does not use a CLA.

**Comment by yulng** [comment]
> 

already added signed off 
thanks

**Comment by xmulligan** [comment]
@yulng you've signed off the PR comment, but not the commit yet. Either check out [this article](https://www.secondstate.io/articles/dco/) for how to amend your commit or if you open a new PR in the Github UI, it will automatically add sign off for you.

**Comment by yulng** [comment]
Need to declare the license at the beginning of the file
Signed-off-by: yulng <wei.yang@daocloud.io>

thanks

**Comment by yulng** [comment]
> @yulng you've signed off the PR comment, but not the commit yet. Either check out [this article](https://www.secondstate.io/articles/dco/) for how to amend your commit or if you open a new PR in the Github UI, it will automatically add sign off for you.

**Comment by yulng** [comment]
Need to declare the license at the beginning of the file
Signed-off-by: yulng wei.yang@daocloud.io

**Comment by xmulligan** [comment]
@yulng please open a new PR. I think that will be easier

**Comment by yulng** [comment]
Submit another one

**Pull request closed without merging**
