### PR TITLE
images/runtime: update CNI plugins to 1.1.1

### PR DESCRIPTION
**Pull request by tklauser**
This allows Cilium to run in environments using containerd which do not
have a `loopback` CNI plugin binary available.

### CODE REVIEW

**Review by nbusseneau — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by aanm** [comment]
/test-1.16-4.9

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@tklauser it seems the k8s-1.16-kernel-4.9 is always failing on the same tests

**Comment by aanm** [comment]
merging since the current failures are expected

**Pull request merged**
