### PR TITLE
v1.14 Backports 2024-05-11

### PR DESCRIPTION
**Pull request by sayboras**
* [ ] #32367 (@sayboras)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 32367
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.14

**Review by viktor-kurchenko — APPROVED** [review]

**Review by ti-mo — COMMENTED** [review]
init.sh changes look fine to me :+1:

**Review by jschwinger233 — APPROVED** [review]
bpf/init.sh looks good.

**Review by michi-covalent — APPROVED** [review]
`:rubber-stamp:`

**Pull request merged**
