### PR TITLE
v1.10 backports 2022-03-11

### PR DESCRIPTION
**Pull request by christarazi**
* #18864 -- Prevent CiliumEndpoint removal by non-owning agent (@timoreimann)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18864; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by christarazi** [comment]
/test-backport-1.10

**Comment by ti-mo** [comment]
/test-1.18-4.9

**Comment by ti-mo** [comment]
/test-1.19-4.9

**Review by nathanjsweet — APPROVED** [review]

**Comment by ti-mo** [comment]
/ci-aks-1.10

**Pull request merged**
