### PR TITLE
bump k8s dependencies and test to v1.17.5

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

Changelog includes a regression fix in the client-go library that was created in k8s 1.15.

>client-go: resolves an issue with informers falling back to full list requests when timeouts are encountered, rather than re-establishing a watch.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#changelog-since-v1174

### CODE REVIEW

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
never-tell-me-odds

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
hitting #11063

**Review by christarazi — APPROVED** [review]
LGTM

**Pull request merged**
