### PR TITLE
hubble/metrics: Add protocol labels to `flows_processed_total`

### LINKED ISSUE #12656: hubble/metrics: Add protocol labels to `flows_processed_total`
Unlike the drop metric, this one is not annotated with protocol.

There may be others that we want to include the protocol on as well.

### PR DESCRIPTION
**Pull request by sayboras**
Add protocol labels to `flows_processed_total`

Closes #12656

Signed-off-by: Tam Mach <sayboras@yahoo.com>

```release-note
hubble/metrics: Add protocol labels to `flows_processed_total`
```

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]

**Comment by sayboras** [comment]
test-me-please

**Comment by sayboras** [comment]
test-me-please

**Comment by Rolinh** [comment]
@sayboras I think that the failure is legit. The [Hubble CI tests](https://github.com/cilium/cilium/blob/master/test/k8sT/hubble.go) need to be updated as well.

**Comment by sayboras** [comment]
retest-4.9

**Comment by sayboras** [comment]
test-focus K8sHubbleTest

**Comment by sayboras** [comment]
test-me-please

**Comment by sayboras** [comment]
retest-net-next

**Comment by sayboras** [comment]
test-me-please

**Review by glibsm — APPROVED** [review]
`feat(hubble)` is not a syntax i'm familiar with. I was expecting `hubble/metrics: ...`

**Comment by glibsm** [comment]
I think the PR is ready to be out of draft and `release-note/misc` seems wrong for this. This does have user impact, a positive one.

**Review by rolinh — APPROVED** [review]

**Comment by sayboras** [comment]
> feat(hubble) is not a syntax i'm familiar with. I was expecting hubble/metrics: ...

> I think the PR is ready to be out of draft and `release-note/misc` seems wrong for this. This does have user impact, a positive one.

Thanks for your comments. I have updated for both :+1:

**Pull request merged**
