### PR TITLE
[v1.4] 2019-03-26 backports

### PR DESCRIPTION
**Pull request by aanm**
PR #7414

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7510)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
Hit VM download issue: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11075/execution/node/57/log/

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
Hit VM download issue again: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11077/

**Comment by ianvernon** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-docs-please

**Pull request merged**
