### PR TITLE
test: Disable unreliable K8sDemosTest

### PR DESCRIPTION
**Pull request by twpayne**
Refs #14598 and #17350.

### CODE REVIEW

**Comment by twpayne** [comment]
test-me-please

**Comment by twpayne** [comment]
`gke-stable` and `k8s-1.20-kernel-4.19` both timed out waiting for the images to become available on quay.io, e.g.

```
17:12:35  + curl --silent -f -lSL https://quay.io/api/v1/repository/cilium/cilium-ci/tag/a479f99c53834ce5d9ed0e189d6af50eea5a9753/images
17:12:35  curl: (22) The requested URL returned error: 404 
```

**Review by tklauser — COMMENTED** [review]
Is this still needed now that #17489 is merged, fixing #14598?

**Comment by twpayne** [comment]
We need the first commit, but not the second one. I'll cherry pick it out into a separate PR.

**Pull request closed without merging**
