### PR TITLE
ci: fix archiving artifacts in runtime jenkinsfile

### LINKED ISSUE #11503: CI: Runtime pipeline does not gather artifacts
## Ginkgo-CI-Tests-runtime-Pipeline

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-runtime-Pipeline/
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-runtime-Pipeline/282/

This build (and other recent builds) failed but no artifacts were gathered.

### PR DESCRIPTION
**Pull request by nebril**
Fixes https://github.com/cilium/cilium/issues/11503

### CODE REVIEW

**Comment by nebril** [comment]
test-runtime

**Comment by nebril** [comment]
test-net-next

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-net-next

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
retest-4.9

**Comment by nebril** [comment]
retest-4.19

**Comment by nebril** [comment]
retest-4.9

**Comment by nebril** [comment]
retest-4.19

**Comment by nebril** [comment]
retest-4.9

**Comment by nebril** [comment]
retest-gke

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
Runtime run failed, but the artifacts are there: https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/337/ , merging

**Review by christarazi — APPROVED** [review]
:tada:

**Review by joestringer — APPROVED** [review]
The changes fix the bug, I don't think there's anything subtle we need to review this for is there?  Any chance it could inadvertently break other artifact gathering?

**Comment by nebril** [comment]
Not really, merging this as is.

**Pull request merged**
