### PR TITLE
Quieten spellcheck output with `make V=0`

### PR DESCRIPTION
**Pull request by joestringer**
Example output:

```
   $ make -C Documentation spellcheck V=0 --quiet SPHINXOPTS="-q"
     CHECK documentation dependencies...
     CHECK documentation spelling...
   WARNING: Found 1 misspelled words
   WARNING: Not copying tabs assets! Not compatible with spelling builder
   Please fix the following spelling mistakes:
   * Documentation/concepts.rst:7: (deplyment)
   If the words are not misspelled, add them to Documentation/spelling_wordlist.txt
   Makefile:48: recipe for target 'spellcheck' failed
   make: *** [spellcheck] Error 1
```

### CODE REVIEW

**Comment by joestringer** [comment]
test-docs-please

**Review by raybejjani — APPROVED** [review]
This is probably fine but @aanm implied, at one point, that the printed spelling mistakes were intended. aanm will have to confirm, though. I might have misunderstood.

**Comment by aanm** [comment]
>This is probably fine but @aanm implied, at one point, that the printed spelling mistakes were intended. aanm will have to confirm, though. I might have misunderstood.

@raybejjani That is correct. @joestringer What is the reason behind commit?

**Comment by joestringer** [comment]
@aanm @raybejjani Previously, the output with `make V=0` is very tidy and quiet, only printing a small number of one-liner status messages such as `CC ...` or `CHECK ...`, and errors/warnings. Now, the documentation target floods the terminal with output. The main change I'd like to suggest here is to respect `$SPHINX_OPTS` in the new target, then if the passing down of the `SPHINX_OPTS=-q` is not in the proper place (or not properly gated by `V=0`) then we can shift that around. I can look into that.

If you want to see the misspelled words, we could also cat the spelling output file to the terminal in the error case.

Compare:

```
  GO    cilium/cilium                                                                                                                                                                                                                                          
  CHECK contrib/scripts/bindata.sh                                                                                                                                                                                                                             
  GO    daemon/cilium-agent                                                                                                                                                                                                                                    
  GO    bugtool/cilium-bugtool                                 
  CHECK contrib/scripts/check-cmdref.sh                        
  GEN   Documentation/cmdref/cilium                            
  GEN   Documentation/cmdref/cilium-bugtool                    
  GEN   Documentation/cmdref/cilium-agent                      
  GEN   Documentation/cmdref/cilium-health                     
  CHECK contrib/scripts/lock-check.sh                          
  CHECK documentation dependencies...  
  CHECK documentation spelling...
WARNING: Found 2 misspelled words                                                                                                                                
 See Documentation/_build/spelling/output.txt for misspelled words.                                                                                            
 Please fix the spelling, or if they are not misspelled,                                                                                                     
 add them to Documentation/spelling_wordlist.txt      
```

```
  GO    cilium/cilium                                                                                                                                                                                                                                          
  CHECK contrib/scripts/bindata.sh                                                                                                                                                                                                                             
  GO    daemon/cilium-agent                                                                                                                                                                                                                                    
  GO    bugtool/cilium-bugtool                                 
  CHECK contrib/scripts/check-cmdref.sh                        
  GEN   Documentation/cmdref/cilium                            
  GEN   Documentation/cmdref/cilium-bugtool                    
  GEN   Documentation/cmdref/cilium-agent                      
  GEN   Documentation/cmdref/cilium-health                     
  CHECK contrib/scripts/lock-check.sh                          
  CHECK documentation dependencies...                          
  GEN   Documentation/_build/dummy                             
Running Sphinx v1.6.3                                          
Initializing Spelling Checker                                  
loading pickled environment... done                            
Ignoring wiki words                                            
Ignoring acronyms                                              
Ignoring Python builtins                                       
Ignoring importable module names                               
Looking for custom word list in /home/joe/work/src/github.com/cilium/cilium/Documentation/spelling_wordlist.txt
building [mo]: targets for 0 po files that are out of date     
building [spelling]: all documents                             
updating environment: 0 added, 0 changed, 0 removed            
looking for now-outdated files... none found                   
preparing documents... done                                    
writing output... [  0%] api                                   
writing output... [  1%] bpf                                   
writing output... [  2%] cheatsheet                            
writing output... [  3%] cmdref/cilium                         
writing output... [  4%] cmdref/cilium-agent                   
writing output... [  5%] cmdref/cilium-bugtool                 
writing output... [  6%] cmdref/cilium-health                  
writing output... [  7%] cmdref/cilium-health_get              
writing output... [  8%] cmdref/cilium-health_ping             
writing output... [  8%] cmdref/cilium-health_status           
writing output... [  9%] cmdref/cilium_bpf                     
writing output... [ 10%] cmdref/cilium_bpf_ct                  
writing output... [ 11%] cmdref/cilium_bpf_ct_flush            
writing output... [ 12%] cmdref/cilium_bpf_ct_list             
writing output... [ 13%] cmdref/cilium_bpf_endpoint            
writing output... [ 14%] cmdref/cilium_bpf_endpoint_delete     
writing output... [ 15%] cmdref/cilium_bpf_endpoint_list       
writing output... [ 16%] cmdref/cilium_bpf_ipcache             
writing output... [ 16%] cmdref/cilium_bpf_lb                  
writing output... [ 17%] cmdref/cilium_bpf_lb_list             
writing output... [ 18%] cmdref/cilium_bpf_policy              
writing output... [ 19%] cmdref/cilium_bpf_policy_add          
writing output... [ 20%] cmdref/cilium_bpf_policy_delete       
writing output... [ 21%] cmdref/cilium_bpf_policy_get          
writing output... [ 22%] cmdref/cilium_bpf_proxy               
writing output... [ 23%] cmdref/cilium_bpf_proxy_flush         
writing output... [ 24%] cmdref/cilium_bpf_proxy_list          
writing output... [ 25%] cmdref/cilium_bpf_tunnel              
writing output... [ 25%] cmdref/cilium_bpf_tunnel_list         
writing output... [ 26%] cmdref/cilium_cleanup                 
writing output... [ 27%] cmdref/cilium_completion              
writing output... [ 28%] cmdref/cilium_config                  
writing output... [ 29%] cmdref/cilium_debuginfo               
writing output... [ 30%] cmdref/cilium_endpoint                
writing output... [ 31%] cmdref/cilium_endpoint_config
...
```

**Comment by aanm** [comment]
@joestringer ah, ok I've never seen the CI output. That makes sense. But can you `cat` the contents of the misspelled words? It will be easier to know before trying ourselves in our environments.

**Comment by joestringer** [comment]
test-docs-please

**Comment by joestringer** [comment]
@aanm by the way, the above wasn't CI output, it was the output in my terminal for a regular build.

I've updated with the change to cat the file (well, actually sed and create a list..), let me know what you think. I updated the PR description.

**Review by rlenglet — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Pull request merged**
