### PR TITLE
Documentation: split up contributing guide into smaller, more focused documents

### PR DESCRIPTION
**Pull request by ianvernon**
The split up documentation is grouped as follows under the 'For Developers' section:
    
* Getting Started
    - How To Contribute: contains information around the contribution process
       for Cilium, including pull requests, getting pull requests merged, etc.
    - Development Setup: contains information on how to set up a development
       environment.
    - Building Container Images: contains information about how to build and
      publish container images for use by Cilium.
* Testing
    - CI / Jenkins: information about the Cilium testing / CI infrastructure.
    - Documentation: information about how to locally build / test
      documentation.
    - End-To-End Testing Framework: information about the Ginkgo test suite.
    - Unit Testing: information about how to run unit tests.

This makes the file more manageable and easier to maintain.
    
Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9456)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-docs-please

**Review by joestringer — COMMENTED** [review]
I like the idea here!

Hmm, weird, I get some strange sidebar behaviour when testing this out. For instance when on the main `Developer/Contributor Guide` page, I see the new links... but if I click on `CI/Jenkins` they disappear. Not sure what sphinx is doing here. Shouldn't be a caching issue AFAICT...

At a glance I see that `CI/Jenkins` and `Testing` are both under the `For Developers` as peers but I feel like these should be part of overall testing. Maybe CI/Jenkins should be moved under `Testing`.

`Building Container Images` seems like it should in fact be nested under the `Developer/Contributor Guide` as it's not that useful for most people on the website attempting to find something in the sidebar. I actually wonder if we could split the `Developer/Contributor Guide` into subsections in the same way that the GSGs break down particular GSGs. What do you think?

**Comment by ianvernon** [comment]
@joestringer hm, does it persist if you run `cd Documentation/ ; make clean` and then run `make render-docs` from the root of the cilium repo again?

RE: your comments - all valid. I'll work on doing that, it makes sense to split up the guide entirely right now into separate documents and group them under `Developer / Contributor Guide`.

**Comment by joestringer** [comment]
> hm, does it persist if you run `cd Documentation/ ; make clean` and then run `make render-docs` from the root of the cilium repo again?

Didn't try yet, but I assumed `make render-docs` builds from a clean slate each time. If not that would explain it.

**Comment by ianvernon** [comment]
test-docs-please

**Review by aanm — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
:shipit:

**Pull request merged**
