### PR TITLE
v1.2 backport -  proxy: "Make NACK cancel the WaitGroup and pass NACK detail in ProxyError"

### PR DESCRIPTION
**Pull request by jrajahalme**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5742)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/6860/

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
