### PR TITLE
cilium: bpf: use conntrack for service backend tracking in lxc

### LINKED ISSUE #4510: Request fails in scale out scenario for pod to pod networking
## Bug reports

I have tried to communicate from a pod to pods which are scaling out at a moment using Service's Cluster IP. In Kubernetes, grouped Endpoints as one Service can be scaled out in some cases.(either manually and auto-scaling).
In this case, when pods are scaling out, requests fail must happen.

Request fails should not be happened in scaling out scenario. If connection sync is not correct  in HTTP, web server sends RST-packet.. then request fails. (It doesn't happen in Calico)

---
In my polite opinion, it happens because of hash algorithm.
--> https://github.com/cilium/cilium/blob/master/bpf/lib/lb.h#L184 

### Title

Request fails in scale out scenario for pod to pod networking

### General Information

- Cilium version (run `cilium version`
```
Client: 1.0.90 aef051d 2018-05-23T12:01:01-07:00 go version go1.9 linux/amd64
Daemon: 1.0.90 aef051d 2018-05-23T12:01:01-07:00 go version go1.9 linux/amd64
```
- Kernel version (run `uname -a`)
```
4.12.2-1.20180114.el7.centos.x86_64
```
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Kubernetes v1.9.6
```

### How to reproduce the issue

1. Make 2 sets of Deployment and target Service(ClusterIP) in Kubernetes
2. Generate packets(I used locust - https://github.com/kubernetes/charts/tree/master/stable/locust) from a pod to the ClusterIP.
3. Check correct connectivity 
4. Try to change Replica in a Deployment. The target Deployment is web servers(SimpleNodeJS...just helloworld)
5. Check request fails

---

If you have any discussion, then please contact me anytime. I'm very interested in Cillium.
Thank you.

### PR DESCRIPTION
**Pull request by jrfastab**
**Summary of changes**:

When services are enabled each packet runs lb*_select_slave to
select which backend to target. This code hashes the packet and then
does a simple (hash % count), where count is the number of backends,
to select the backend to use. However, if we change the number of
backends with open TCP connections the backend may change due to the
above calculation. This will break the running TCP sessions.

Ideally, TCP sessions should continue to use the same backend for
the lifetime of the connection even if the number of backends changes.
Additionally, hashing every packet is a bit of a waste. To fix this
we use the conntrack code to track connections before they are
translated (lb4_xlate takes a packet targeted at a service endpoint
and transforms the the daddr, dport to point to the selected
backend.) and use a hole in the ct_entry data structure to track
the slave. This way we only hash the packet on the first packet and
we use the same slave regardless of backend size changes. This
does create one complication however, if the backend is removed. In
this case we rehash the packet and move to a new valid slave. If its
a TCP session this may possibly result in a TCP RST but the backend
has been removed so this should be expected.

Another nice property achieved here is RELATED flows will now
choose the same backend.

Couple design points. First we reuse the CT_MAP{4|6} to stash the
service endpoint id. This means there will be extra entries in this
map, the tuple from the local IP to the service IP. Also replies could
in-theory use the direct IP and not the service IP and the connection
tracker would allow the packet through. However translation is done on
egress anyways so it would not "look" different outside the cilium
egress BPF path. If we don't like this its trivial to create new
map specific for the service handling. Next, because we use the
service backend index to lookup the service if a user shuffles there
backend service table we will continue to use the same index. At which
point this may or may not be the same endpoint, it is up to the user
to ensure that backend indices do not change if they choose to change
the backend table at runtime. Worse case is the user does this
incorrectly and TCP sessions will receive a TCP RST, which is no
worse then the current situation.

With regards to --lb option. The netdev attached lb will continue
to function as it always has we do not try to address this here. A
subsequent patch may add similar logic here if needed.

Fixes:  #4510

```release-note
Service backends may now be added without potentially disturbing existing TCP sessions.
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4667)

### CODE REVIEW

**Comment by jrfastab** [comment]
Also might be worth noting that the slave-id is given by cilium daemon in the order the --backends are listed on the cmd line `cilium service update ... --backends` so be sure to list them in the same order. Future improvement might allow users to assign the slave_id in order to have more control over the mapping.

**Comment by tgraf** [comment]
Will need to schedule the work to guarantee that we keep the index constant. Not sure if this is the case right now as we receive updates from Kubernetes.

**Comment by jrfastab** [comment]
Does Kubernetes hand down an ID with the backends? If so it should be fairly straightforward.

**Comment by tgraf** [comment]
No, we'll have to keep some state. Let's merge this first.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
hung with no details? Looks like Ginkgo-tests never got scheduled/started/whatever? Will retry... Failed again with `k8s1-1.7: E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)` seems possibly unrelated. At the risk of hitting the retry limit do another round of testing.

Update: The LB test in ginkgo is sneaky and uses its own clang command line to compile bpf_lb.c so we must modify that as well as init.sh, I'll create an issue on that though because it means our tests miss the build options being used by daemon.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
Looks good, just needs a bpf.sha rebase

**Comment by jrfastab** [comment]
test me please

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
