### PR TITLE
v1.14 Backports 2023-07-13

### PR DESCRIPTION
**Pull request by jibi**
* [x] #26504 (@sayboras)
 * [x] #26726 (@julianwiedmann)
 * [x] #26711 (@dylandreimerink)
 * [x] #26732 (@squeed)
 * [x] #26613 (@giorio94)
 * [ ] #26547 (@glibsm)
 * [x] #26660 (@squeed)
 * [x] #26639 (@aojea)
 * [x] #26753 (@giorio94)
 * [x] #25351 (@odinuge)
 * [x] #26755 (@rolinh)
 * [x] #26741 (@jibi)
 * [x] #26502 (@sayboras)

PRs skipped due to conflicts:

 * #26331 (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 26504 26726 26711 26732 26613 26547 26660 26639 26753 25351 26755 26741 26502; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=26504,26726,26711,26732,26613,26547,26660,26639,26753,25351,26755,26741,26502
```

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
My commits look good. Thanks!

**Review by aojea — APPROVED** [review]
lgtm on my side

**Review by squeed — APPROVED** [review]

**Comment by jibi** [comment]
/test-backport-1.14

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commits :heavy_check_mark:

**Review by nbusseneau — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Review by odinuge — APPROVED** [review]
My cherry-pick looks fine. Thanks!

**Review by dylandreimerink — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Pull request merged**
