### PR TITLE
envoy: Reduce error logging

### PR DESCRIPTION
**Pull request by jrajahalme**
gRPC stream on the server side gets cancelled if the client side
cancels the stream. This happens when the Envoy listener is being shut
down, which happens when the policy is changed to not contain L7 rules
any more. As this is part of the normal operation, change these logs
to the debug level.

Use a new cilium-envoy image with sanitized logging.

This should remove these from the CI output:

Top 5 errors/warnings:
error while receiving request from xDS stream
xDS stream context canceled
[[cilium/network_policy.cc:129] Bad Network Policy Configuration
[[cilium/host_map.cc:187] Bad NetworkPolicyHosts Configuration
[[cilium/bpf.cc:81] cilium.bpf_metadata: map /sys/fs/bpf/tc/globals/cilium_ipcache mismatch 1!=11 || 24!=24 || 12!=12

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8425)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
I am removing the needs-backport lables for v1.4 and v1.5, since this is mainly a cosmetic change, and cherry-picking the Envoy version change into v1.4 and v1.5 appeared to break Egress policy for those branches.

**Comment by ianvernon** [comment]
The following commit was backported into `v1.5`: https://github.com/cilium/cilium/pull/8425/commits/c39f0a4dc69c3d6a5d2145e941eb691a1525d541

**Pull request merged**
