### PR TITLE
Add support for file based authorizer for Azure

### PR DESCRIPTION
**Pull request by ashrayjain**
This adds support for file based credentials when using Azure. 

This PR prefers file based first and then falls back to environment based if that fails, but we could also reverse that if that's preferable.

Upstream Azure docs for file based auth live here: https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-authorization#use-file-based-authentication

### CODE REVIEW

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Comment by ungureanuvladvictor** [comment]
// failure does not seem related https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18562/testReport/Suite-k8s-1/18/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/

test-me-please

**Comment by ungureanuvladvictor** [comment]
restart-ginkgo

**Review by vadorovsky — APPROVED** [review]
Looks good, thanks!

**Review by tgraf — APPROVED** [review]

**Pull request merged**
