### PR TITLE
node: Check for nil in OnUpdate()

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6906)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by brb — COMMENTED** [review]
LGTM, just a few notes:

- It would be good to add to the git commit message a reason for `*node.Node` being nil.
- Shouldn't we check for the nil in https://github.com/cilium/cilium/blob/master/pkg/clustermesh/services.go#L130 as well?

**Comment by tgraf** [comment]
> * It would be good to add to the git commit message a reason for `*node.Node` being nil.

I don't know yet. A user hit it but I couldn't reproduce it so far. This avoids the panic and unblocks 1.4.0.

**Comment by brb** [comment]
> I don't know yet. A user hit it but I couldn't reproduce it so far.

Maybe it makes sense to add a log statement, so that in the future we could find out the reason?

**Comment by aanm** [comment]
AFAIK the panic was not related with the `node` struct, otherwise it would have panic on line 53 of that file. It's more likely caused by the `o.manager` to be `nil`

**Comment by tgraf** [comment]
> AFAIK the panic was not related with the `node` struct, otherwise it would have panic on line 53 of that file. It's more likely caused by the `o.manager` to be `nil`

You are right, initially I thought you were talking about `node.` here:
```
                nodeCopy.Source = node.FromKVStore
```

but `nodeCopy` would be `nil` as well. I'll check the initialization path of `NodeObserver`

**Pull request closed without merging**
