### PR TITLE
bpf: Avoid routing loops

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6236)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
@tgraf the Ginkgo tests need to be updated to account for the difference in number of nodes in the tunnel map with this change.

**Review by joestringer — APPROVED** [review]

**Comment by ianvernon** [comment]
Superseded by #6251 .

**Pull request closed without merging**
