### PR TITLE
Backports for 0.10.1

### PR DESCRIPTION
**Pull request by tgraf**

### CODE REVIEW

**Review by borkmann — COMMENTED** [review]
Cannot make sense out of the k8s-multi-node-tests yet. Is it perhaps under some circumstances that we're hitting complexity limit? I was testing with 4.9.13 and worst case I've seen was 51,500, close but still within upper limit. Also if it would be the case we would trigger much earlier, hm.

**Review by aalemayhu — APPROVED** [review]
Did not look close at CI failure, but the changes themselves look good.

**Comment by borkmann** [comment]
Ok, in the full log, it says:
```
09:50:54 + abort 'Error: unexpected connection between frontend and backend. wanted HTTP 403, got: HTTP 404'
09:50:54 ------------------------------------------------------------------------
09:50:54                           K8s Test Failed
09:50:54 Error: unexpected connection between frontend and backend. wanted HTTP 403, got: HTTP 404
09:50:54 
09:50:54 ------------------------------------------------------------------------
09:50:54 + set +x
```

**Comment by tgraf** [comment]
> Ok, in the full log, it says:
> 
> 09:50:54 + abort 'Error: unexpected connection between frontend and backend. wanted HTTP 403, got: HTTP 404'
> 09:50:54 ------------------------------------------------------------------------
> 09:50:54                           K8s Test Failed
> 09:50:54 Error: unexpected connection between frontend and backend. wanted HTTP 403, got: HTTP 404
> 09:50:54 
> 09:50:54 ------------------------------------------------------------------------
> 09:50:54 + set +x

I think this is a false negative and `wait_all_k8s_regenerated` is returning early. It assumes that by the time it is called, at least one endpoint is already in state regenerating.

I will fix this to use policy revision. I think we can merge this in the meantime.

**Review by borkmann — APPROVED** [review]

**Comment by borkmann** [comment]
Ok, thanks for clarifying!

**Pull request merged**
