### PR TITLE
ServiceMonitor should default to release namespace

### PR DESCRIPTION
**Pull request by dsexton**
Signed-off-by: Dan Sexton <dan.b.sexton@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10088)

### CODE REVIEW

**Review by aanm — APPROVED** [review]
Changes LGTM. @joestringer should we backport this to 1.7? I don't see why not.

**Comment by aanm** [comment]
test-me-please

**Comment by dsexton** [comment]
@aanm can we backport this to 1.7 & 1.6?

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
I don't see why not, is there any particular inherent risk in the backport? Seems like @dsexton has specifically hit an issue with it and is submitting the fix to address an issue on the older versions too.

**Comment by joestringer** [comment]
test-me-please

**Comment by dsexton** [comment]
@joestringer no risk, this just ensures that the service monitors render to the release namespace if you do not specify an override.

**Pull request merged**
