### PR TITLE
v1.8 backport: connectivity-check: Use unprivileged ports

### PR DESCRIPTION
**Pull request by kaworu**
Several PR were nominated for backport:

 * #12580 -- chore(docker): Bump json-mock version to 1.2 for dual stack (@sayboras)
 * #12599 -- Extend connectivity-check for HTTP policy validation via CUE (@joestringer)
 * #12730 -- connectivity-check: Add DNS query tool for debugging (@joestringer)
 * #12788 -- connectivity-check: re-introduce port-to-b NodePort checks (@qmonnet)
 * #12671 -- test(conformance): Enable smoke test in ipv6 cluster (@sayboras)
 * #12829 -- Refactor/connectivity check cue (@sayboras)

Initial PR requiring backporting:

 * #12948 -- connectivity-check: Use unprivileged ports (@tgraf)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12580 12599 12730 12788 12671 12829 12948; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by kAworu** [comment]
@sayboras I think both `github/kind-config-ipv6.yaml` and `github/workflows/smoke-test-ipv6.yaml` should be omitted from this backport but am not sure. Happy to hear your opinion on this.

**Comment by sayboras** [comment]
> I think both `github/kind-config-ipv6.yaml` and `github/workflows/smoke-test-ipv6.yaml` should be omitted from this backport but am not sure. Happy to hear your opinion on this.

Yes, we can if it's a must. I am just curious about the reason behind for my understanding. The related PR #12671 had single commit only, so I am not sure how we can ignore specific files in backport. As this job is successfully run in 1.8 branch, can we still keep it as optional ? In master branch, it's mandatory GA check currently.

**Review by qmonnet — APPROVED** [review]
> #12788 -- connectivity-check: re-introduce port-to-b NodePort checks (@qmonnet)

Looks good to me, thanks!

**Comment by kAworu** [comment]
> > I think both `github/kind-config-ipv6.yaml` and `github/workflows/smoke-test-ipv6.yaml` should be omitted from this backport but am not sure. Happy to hear your opinion on this.
> 
> Yes, we can if it's a must. I am just curious about the reason behind for my understanding.

I am asking because the goal of this PR is to backport #12948, which as far as I understand is unrelated to smoke tests. I've discarded on the way several diff related to `.github/workflows/smoke-test.yaml` because it has been introduced after 1.8.

> The related PR #12671 had single commit only, so I am not sure how we can ignore specific files in backport.

I think interactive git rebase magic would do the trick.

> As this job is successfully run in 1.8 branch, can we still keep it as optional ? In master branch, it's mandatory GA check currently.

Fine by me, thanks for checking in!

**Comment by sayboras** [comment]
> I am asking because the goal of this PR is to backport #12948, which as far as I understand is unrelated to smoke tests. I've discarded on the way several diff related to `.github/workflows/smoke-test.yaml` because it has been introduced after 1.8.

This is very good point. Not so long ago, Andre told me about some issue related single/multi node cluster discrepancy in smoketest between master and v1.8 (e.g. HA operator requires multiple node clusters). Let me follow up with Andre once he is back.

Now, it's fair to drop smoke-test-ipv* for consistency. Then we can tackle 1.8 smoketest for both ipv4 and ipv6 separately if required. Might need your help to do the magic rebase :1st_place_medal:

**Review by sayboras — APPROVED** [review]
Thanks for your kind help. Looks good for my commits :100:

**Comment by joestringer** [comment]
I'll put this on my review queue since I made the most invasive changes here. Just had one query in the mean time:

> Before this PR is merged, mark the nominated PR as pending backporting via:
> ```
> $ for pr in 12580 12599 12730 12788 12671 12829; do contrib/backporting/set-labels.py $pr pending 1.8; done
> ```

@kAworu Did you have trouble running this command? Usually this (mark `pending`) step is the backporter's responsibility and should be done when preparing the PR. Marking as `done` can only be done once the PR is merged, so it's the responsibility of the person who merges the changes to run that (mark `done`) command. That's why you'll typically only see the `done` variation in backport PR descriptions.

**Comment by kAworu** [comment]
@joestringer I did not run the mark `pending` command because I did not want to make changes to theses PR without some kind of author approval beforehand. Seems like everyone has given it's OK so far so I'll run it and remove the block from the description. Thanks for clarifying this!

**Review by tgraf — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
test-backport-1.8

**Comment by christarazi** [comment]
Rebased to include fix for Guestbook flake from https://github.com/cilium/cilium/pull/13060

**Comment by christarazi** [comment]
test-backport-1.8

**Pull request merged**
