### PR TITLE
[operator] Refactor - export CiliumEndpointSlice test utils

### PR DESCRIPTION
**Pull request by dlapcevic**
Extract test utility functions to a new package that exports them.
It's required for testing features that interact with CiliumEndpointSlices - e.g. https://github.com/cilium/cilium/pull/30356

No user facing changes.

area/operator
kind/cleanup

Signed-off-by: Dorde Lapcevic <[dordel@google.com](mailto:dordel@google.com)>

### CODE REVIEW

**Review by pippolo84 — APPROVED** [review]
Thanks!

**Comment by dlapcevic** [comment]
Done. Thank you @pippolo84

**Comment by dlapcevic** [comment]
Hi @pippolo84, could you please help me merge this?
This is a simple refactor of test code. The unit tests are passing. The failing tests shouldn't be related.

**Comment by dlapcevic** [comment]
Rebased

**Comment by dlapcevic** [comment]
@alan-kut

**Review by alan-kut — APPROVED** [review]

**Pull request merged**
