### PR TITLE
v1.10 backports 2022-06-29

### PR DESCRIPTION
**Pull request by nbusseneau**
* #19379 -- add support for AKS BYOCNI (@nbusseneau)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 19379; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Review by pchaigno — CHANGES_REQUESTED** [review]
What were the conflicts?

**Comment by nbusseneau** [comment]
> What were the conflicts?

Helm values / README to regenerate.

**Comment by pchaigno** [comment]
For something that simple to fix, we should favor letting the tophat do the backports. We want to avoid having multiple backport PRs in flight as the same time.

**Comment by nbusseneau** [comment]
> For something that simple to fix, we should favor letting the tophat do the backports. We want to avoid having multiple backport PRs in flight as the same time.

Agreed, I thought there'd be more conflicts initially because I intended to only backports Azure IPAM changes (and the structure had changed in previous commits in the PR), but in the end I recalled we had discussed backporting everything because older branches would benefit from BYOCNI as well...

We can drop this PR to include it in regular backports if we think it's better.

**Comment by pchaigno** [comment]
> We can drop this PR to include it in regular backports if we think it's better.

Let's do that. In general, it's fine to only backport once the tophat tells you they won't pick it up themselves because of conflicts.

**Comment by nbusseneau** [comment]
Closing as per the discussion above.

**Pull request closed without merging**
