### PR TITLE
vagrant: Bump all Vagrant box versions

### PR DESCRIPTION
**Pull request by pchaigno**
To pick up the fix at https://github.com/cilium/packer-ci-build/pull/266 for the 5.4 box and https://github.com/cilium/packer-ci-build/pull/266.

### CODE REVIEW

**Review by nbusseneau — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-1.19-5.4

**Comment by pchaigno** [comment]
test-only --focus="K8sDatapathConfig MonitorAggregation Checks that monitor aggregation restricts notifications" --kernel_version=netnext --k8s_version=1.16

**Comment by pchaigno** [comment]
The focused test for the flake passed. The team review from CI is covered. Merging.

**Pull request merged**
