### PR TITLE
api/hubble: add AUDIT policy verdict

### PR DESCRIPTION
**Pull request by jaffcheng**
Add a new policy verdict value `AUDIT` to distinguish whether a packet
is allowed due to the audit mode or because it complies with the security
policy.
Need to bump vendor in hubble repo accordingly.

This is a PR for API change, changes for hubble logic and tests will be in a separate PR once this gets merged and bumped in test VM hubble CLI.

### CODE REVIEW

**Comment by jaffcheng** [comment]
Runtime tests check for hubble observe output so this requires a newer hubble binary to pass, shall I split this change into two PRs, with one adding enum to flow API and the next one changes hubble output?

**Review by kkourt — APPROVED** [review]
LGTM, but let's wait to hear from people more familiar with hubble than me :)

Thanks.

**Review by gandro — APPROVED** [review]
Looks straight forward, thanks!

**Comment by gandro** [comment]
> Runtime tests check for hubble observe output so this requires a newer hubble binary to pass, shall I split this change into two PRs, with one adding enum to flow API and the next one changes hubble output?

I missed this comment before. Yes, I think we first need to get the API change in and then update the tests.

**Comment by jaffcheng** [comment]
Removed hubble and test changes from this PR, will send that in a separate PR.

**Review by gandro — APPROVED** [review]

**Comment by gandro** [comment]
test-me-please

**Comment by glibsm** [comment]
So in this case `AUDIT` means `would be dropped otherwise`?

**Comment by jaffcheng** [comment]
> So in this case `AUDIT` means `would be dropped otherwise`?

Hi, yes, I think we already have `audit` action in `cilium monitor -t policy-verdict`
https://docs.cilium.io/en/stable/gettingstarted/policy-creation/#observe-policy-verdicts

**Comment by gandro** [comment]
retest-gke

**Comment by gandro** [comment]
retest-net-next

**Comment by gandro** [comment]
Marking this ready to merge. The API change itself is very small.

**Pull request merged**
