### PR TITLE
examples/kubernetes-ingress: update kubernetes options to 1.11.0

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4692)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4589/testReport/junit/k8s-1/10/K8sValidatedUpdates_Updating_Cilium_stable_to_master/
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
DNS entry is not ready after timeout
Expected
    <*errors.errorString | 0xc4204244d0>: {
        s: "Timeout reached: DNS \"app1-service.default.svc.cluster.local\" is not ready after timeout",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Updates.go:110
```
impossible to debug it without #4686

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
Cannot curl from "testclient-lrrvj" to testds-service
Expected command: kubectl exec -n default testclient-lrrvj -- curl -s -D /dev/stderr --fail --connect-timeout 5 --max-time 5 http://testds-service.default.svc.cluster.local:80/ 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 
Stderr:
 	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Chaos.go:109
```
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4596/

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
