### PR TITLE
test: Increase verifier test make timeout

### PR DESCRIPTION
**Pull request by nebril**
We are hitting timeouts in this test, let's increase the timeout.

This change adds `Timeout` ExecOption that can be used throughtout the
tests to fine-tune timeouts for commands.

### CODE REVIEW

**Comment by nebril** [comment]
test-missed-k8s

**Review by qmonnet — APPROVED** [review]
Looks good to me

**Review by pchaigno — APPROVED** [review]
LGTM!

Would it make sense to also apply the following diff to output the list of compiled packages. It might help us explain why we spend >4min compiling in this pipeline when we spend 15s doing the same in other pipelines.
```diff
diff --git a/tools/maptool/Makefile b/tools/maptool/Makefile
index 8c78180a4..0d80fc7f1 100644
--- a/tools/maptool/Makefile
+++ b/tools/maptool/Makefile
@@ -12,7 +12,7 @@ all: $(TARGET)
 $(TARGET):
        @$(ECHO_GO)
 ifneq ($(RACE),"")
-       $(QUIET)$(GO_BUILD_WITH_CGO) -o $@
+       $(QUIET)$(GO_BUILD_WITH_CGO) -v -o $@
 else
        $(QUIET)$(GO_BUILD) -o $@
 endif
```

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-me-please

**Review by kkourt — APPROVED** [review]
LGTM, but also something definitely seems wrong if we need 10' to build this.

**Comment by nebril** [comment]
test-gke

**Comment by joestringer** [comment]
:heavy_plus_sign: 10 minutes sounds like a long time. I would expect results in the order of maybe 20 seconds. If we're triggering such long time, this would be a great target to investigate and figure out whether we need to propose bugfixes to the kernel/loader or similar. And if some effort in reworking the scripts to provide better visibility then that could be worth scoping out as well.

But yeah, no point blocking this PR on that effort. :+1:

**Comment by pchaigno** [comment]
> If we're triggering such long time, this would be a great target to investigate and figure out whether we need to propose bugfixes to the kernel/loader or similar.

Note the timeout bump is to compile `tools/maptool` only, no BPF compilation or loading. That's why I suspect there's some difference in how many packages we need to (re)compile, which could explain this.

**Comment by nebril** [comment]
Looks like the build timed out on other step... will retrigger and decide what to do with it tomorrow

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-missed-k8s

**Pull request closed without merging**
