### PR TITLE
add clomonitor exception file

### PR DESCRIPTION
**Pull request by xmulligan**
Signed-off-by: Bill Mulligan <bill@isovalent.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

```release-note
added a CLOMonitor exception file for Slack
```

### CODE REVIEW

**Comment by xmulligan** [comment]
would @cilium/tophat be the best code owner for this file?

**Comment by YutaroHayakawa** [comment]
This week's tophat is here. 

> would @cilium/tophat be the best code owner for this file?

I don't have a good answer for this right now. It is assigned to the tophat because it is a new file and doesn't have an owner. I would suggest creating a new owner entry like `cilium/cncf` but let me ping @aanm @lizrice for their opinion.

**Review by YutaroHayakawa — CHANGES_REQUESTED** [review]
Could you elaborate more about why we need this on the commit message?

**Comment by xmulligan** [comment]
> Could you elaborate more about why we need this on the commit message?

Yes, I've just update the commit message

**Review by qmonnet — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by YutaroHayakawa — APPROVED** [review]

**Comment by pchaigno** [comment]
No need to wait for Maciej's review since it was requested for cilium/contributing and that's already covered by André. Merging.

**Pull request merged**
