### PR TITLE
v1.15 Backports 2024-06-25

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
* [x] #32951 (@giorio94) :warning: resolved conflicts
 * [x] #33216 (@aanm)
 * [ ] #33218 (@dependabot[bot]) :warning: resolved conflicts
 * [ ] #33181 (@julianwiedmann)
 * [ ] #33225 (@julianwiedmann) :warning: resolved conflicts
 * [x] #33248 (@giorio94)
 * [x] #33262 (@harsimran-pabla) :warning: resolved conflicts
 * [x] #33222 (@ysksuzuki)
 * [x] #33292 (@joestringer)
 * [x] #33353 (@aanm)
 * [ ] #33304 (@learnitall)
 * [x] #33368 (@aanm)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 32951 33216 33218 33181 33225 33248 33262 33222 33292 33353 33304 33368
```

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
My commits look good, thanks!

**Review by aanm — APPROVED** [review]

**Review by harsimran-pabla — APPROVED** [review]
BGP changes 🚀

**Review by joestringer — APPROVED** [review]
Approving for @cilium/github-sec and my PR.

**Comment by sgargan** [comment]
@YutaroHayakawa any chance that this [PR](https://github.com/cilium/cilium/pull/33260) could be included in this release?

**Review by learnitall — APPROVED** [review]
Thanks!

**Comment by YutaroHayakawa** [comment]
@sgargan Unfortunately, the PR is merged after this PR is opened. That would be included into the next cycle.

**Comment by YutaroHayakawa** [comment]
`Image CI Build / Display Digests` should be fixed with https://github.com/cilium/cilium/pull/33216 included in this PR.

**Review by ysksuzuki — APPROVED** [review]
My commit LGTM. ty!

**Review by viktor-kurchenko — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Review by youngnick — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
The failing Image CI Build / Display Digests should be fixed by https://github.com/cilium/cilium/pull/33216 included in this PR. Merging.

**Pull request merged**
