### PR TITLE
cilium, ipvlan, docs: add note about ipvlan tech preview

### PR DESCRIPTION
**Pull request by borkmann**
... and also required kernel fix to run in L3S mode.

Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6884)

### CODE REVIEW

**Comment by borkmann** [comment]
test-docs-please

**Comment by borkmann** [comment]
test-docs-please

**Comment by borkmann** [comment]
test-docs-please

**Comment by borkmann** [comment]
test-docs-please

**Review by brb — APPROVED** [review]

**Pull request merged**
