### PR TITLE
v1.13 backports 2023-07-31

### PR DESCRIPTION
**Pull request by sayboras**
- [ ] #26880 -- Documentation: fix the broken links/dead links (@vipul-21)
 - [x] #27015 -- bpf: l4lb: fix IPIP health-check path (@julianwiedmann)
    - :warning: small conflict with GHA job 
 - [x] #25324 -- operator: Adjust CiliumEndpoint GC to only run once in kvstore mode (@learnitall)
    -  :warning: small conflict root.go

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 26880 27015 25324; do contrib/backporting/set-labels.py $pr done 1.13; done
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.13

**Review by julianwiedmann — APPROVED** [review]

**Review by learnitall — APPROVED** [review]
Looks good! Thanks!

**Comment by sayboras** [comment]
@julianwiedmann there is bpf unit test failure due to the below error, seems like v1.13 didn't have the new attribute local_ivp4 in bpf.h (added as part of https://github.com/cilium/cilium/pull/25438). Any suggestion on how to move forward ?

https://github.com/cilium/cilium/actions/runs/5714021888/job/15480514433?pr=27154
```
l4lb_ipip_health_check_host.c:70:12: error: no member named 'local_ipv4' in 'struct bpf_tunnel_key'
        if (from->local_ipv4 != 0)
```

**Comment by julianwiedmann** [comment]
> @julianwiedmann there is bpf unit test failure due to the below error, seems like v1.13 didn't have the new attribute local_ivp4 in bpf.h (added as part of #25438). Any suggestion on how to move forward ?

Oh of course :facepalm:.

It's fine to just drop that specific condition check from the test - thanks for digging it up @sayboras ! Should be straight-forward enough, but let me know if you want me to provide a custom backport.

**Comment by sayboras** [comment]
Seems like the below patch helps

```diff
diff --git a/bpf/tests/l4lb_ipip_health_check_host.c b/bpf/tests/l4lb_ipip_health_check_host.c
index ce9bd98fcd..e2f55e9dc7 100644
--- a/bpf/tests/l4lb_ipip_health_check_host.c
+++ b/bpf/tests/l4lb_ipip_health_check_host.c
@@ -67,10 +67,8 @@ int mock_skb_set_tunnel_key(__maybe_unused struct __sk_buff *skb,
 {
 	if (from->tunnel_id != 0)
 		return -1;
-	if (from->local_ipv4 != 0)
-		return -2;
 	if (from->remote_ipv4 != bpf_ntohl(BACKEND_IP))
-		return -3;
+		return -2;
 	return 0;
 }
 ```

**Comment by sayboras** [comment]
/test-backport-1.13

**Comment by sayboras** [comment]
CI hits below flakes:

- test-1.23-4.19 hits https://github.com/cilium/cilium/issues/13071
- test-1.25-4.19 hits https://github.com/cilium/cilium/issues/25785

**Comment by sayboras** [comment]
/test-1.23-4.19

**Comment by sayboras** [comment]
/test-1.25-4.19

**Review by aanm — APPROVED** [review]

**Pull request merged**
