### PR TITLE
v1.13 Backports 2023-11-15

### PR DESCRIPTION
**Pull request by gandro**
* [x] #29178 (@brb)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 29178
```

### CODE REVIEW

**Review by brb — APPROVED** [review]
Thanks!

**Comment by gandro** [comment]
@brb Can you take a look at the failed test? It seems to have timed out https://github.com/cilium/cilium/actions/runs/6878192185/job/18707329446

**Comment by brb** [comment]
The ci-ipsec-upgrade was never a part of "test-backport-1.1{2,3,4}" :-( The test is failing for other reasons than the changes in this PR.

**Comment by brb** [comment]
Let's merge this PR.

**Pull request merged**
