### PR TITLE
v1.11 backports 2022-02-07

### PR DESCRIPTION
**Pull request by joamaki**
* #18583 -- docs: add Hands-on tutorial (@vannyle)
 * #18563 -- Fix local redirect policies selecting host networked pods (@aditighag)
 * #18277 -- clustermesh-apiserver: fix cmd-line args processing (@abocim)
 * #18478 -- cmd: Fix issue reading string map type via config map (@sayboras)
 * #18671 -- docs: disable k3s network policy enforcement (@tklauser)
 * #18643 -- ipsec: Fix incorrect trace in from-network (@YutaroHayakawa)
 * #18682 -- ipsec: Feed src_id to traces in do_netdev_encrypt for native routing (@YutaroHayakawa)
 * #18676 -- docs: Don't rely on `assignee` filter for reviews (@pchaigno)
 * #18655 -- test: cleanup Services test suite (@brb)
 * #18679 -- test: Move service-proxy-name to unit test (@brb)
 * #18697 -- docs: export KUBECONFIG for cilium-cli with k3s (@tklauser)
 * #18693 -- labelfilter: Refine default label regexps (@twpayne)
 * #18684 -- test: Move some Services test cases to separate suites (@brb)
 * #18707 -- ci: remove box download timeout in upstream tests (@nbusseneau)
 * #18486 -- Prevent unmanaged pods in GKE's containerd flavors (@bmcustodio)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18583 18563 18277 18478 18671 18643 18682 18676 18655 18679 18697 18693 18684 18707 18486; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
$ make add-label branch=v1.11 issues=18583,18563,18277,18478,18671,18643,18682,18676,18655,18679,18697,18693,18684,18707
```

### CODE REVIEW

**Review by nbusseneau — APPROVED** [review]
My changes LGTM.

**Comment by joamaki** [comment]
/test-backport-1.11

**Review by pchaigno — APPROVED** [review]
My change looks good. Thanks!

**Review by sayboras — APPROVED** [review]
Looks good for my commits, thanks :1st_place_medal:

**Review by aditighag — APPROVED** [review]
Backport of my PR looks good. Thanks!

**Comment by joamaki** [comment]
/test-backport-1.11

**Review by brb — APPROVED** [review]
My changes LGTM, thanks.

**Pull request merged**
