### PR TITLE
doc: Add an example for HostReachableServices

### LINKED ISSUE #12347: What is difference between Host-Reachable Services and Container HostPort
## Support

What is the difference between Host-Reachable Services and Container HostPort?

While I was going through the documentation i had this question.

If they are different, it would make sense to add an Example for 'Host-Reachable Services'. 
If they are the same, then provide a note or link in the "Host-Reachable Services" to the Container HostPort Example.

### PR DESCRIPTION
**Pull request by soumynathan**
This PR adds an example for HostReachableServices that would
be help to validate.

Fixes: #12347
Signed-off-by: Swaminathan Vasudevan <svasudevan@suse.com>

### CODE REVIEW

**Review by vadorovsky — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Review by brb — CHANGES_REQUESTED** [review]
HostReachableServices are used to access Kubernetes services either from a host netns or from a pod. The given example shows how to access nginx running in a host netns via node IP which does nothing to do with HostReachableServices.

**Comment by soumynathan** [comment]
> HostReachableServices are used to access Kubernetes services either from a host netns or from a pod. The given example shows how to access nginx running in a host netns via node IP which does nothing to do with HostReachableServices.

@brb thanks for your response.

**Comment by soumynathan** [comment]
> > HostReachableServices are used to access Kubernetes services either from a host netns or from a pod. The given example shows how to access nginx running in a host netns via node IP which does nothing to do with HostReachableServices.
> 
> @brb thanks for your response.

@brb could you provide an example.

**Comment by brb** [comment]
@soumynathan https://docs.cilium.io/en/v1.8/gettingstarted/kubeproxy-free/#validate-the-setup

**Comment by brb** [comment]
Considering https://github.com/cilium/cilium/pull/12355#pullrequestreview-444603465, this PR can be closed.

**Pull request closed without merging**
