### PR TITLE
Aspsk/backports to v1.11

### PR DESCRIPTION
**Pull request by aspsk**
Backport of the following PRs:

* https://github.com/cilium/cilium/pull/20711 (@aspsk)
* https://github.com/cilium/cilium/pull/20859 (@aspsk)

### CODE REVIEW

**Comment by gandro** [comment]
"Check if build works for every commit" failure looks legitimate

**Comment by aspsk** [comment]
> "Check if build works for every commit" failure looks legitimate

Yes, I know the reason, will fix shortly

**Comment by aspsk** [comment]
/test-backport-1.11

**Review by gandro — APPROVED** [review]

**Comment by aspsk** [comment]
/test-backport-1.11

**Comment by sayboras** [comment]
/test-1.18-4.9

**Comment by sayboras** [comment]
test-gke failed for below flake

- [Suite-k8s-1.22.K8sDatapathConfig MonitorAggregation Checks that monitor aggregation flags send notifications](https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/9137/testReport/Suite-k8s-1/22/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_flags_send_notifications/)

**Pull request merged**
