### PR TITLE
Add feature tracking in Cilium Operator as prometheus metrics

### PR DESCRIPTION
**Pull request by aanm**
Follow up of https://github.com/cilium/cilium/pull/35852 but this time for Cilium Operator. I've split in multiple commits so it's easier for each sig to review their section.

**Note for reviewers**: Review on a per-commit basis to make sure the feature of your sig is being detected correctly.

### Features Checklist
- [x] Enable Gateway API (@cilium/sig-servicemesh)
- [x] Enable Ingress Controller (@cilium/sig-servicemesh)
- [x] Enable LBIPAM (@cilium/sig-ipam)
- [x] Enable L7AwareTrafficManagement (@cilium/sig-servicemesh)
- [x] Enable NodeIPAM (@cilium/sig-ipam)

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Looks good for Ingress and Gateway related changes

**Review by aspsk — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]
IPAM look good

**Review by dlapcevic — APPROVED** [review]
LGTM for operator

**Review by nathanjsweet — APPROVED** [review]

**Review by learnitall — APPROVED** [review]
:rocket:

**Pull request merged**
