### PR TITLE
v1.9: Update Go to 1.15.14

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
test-backport-1.9

**Comment by tklauser** [comment]
test-1.13-4.9

**Comment by tklauser** [comment]
* k8s-1.12-kernel-netnext failed on #13853 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/1771/
* k8s-1.17-kernel-5.4 failed on #16050 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-5.4/69/

**Comment by tklauser** [comment]
test-runtime

**Review by aanm — APPROVED** [review]

**Pull request merged**
