### PR TITLE
fqdn: Fix repeat UUID insertion

### PR DESCRIPTION
**Pull request by raybejjani**
I need to add a test for this.

This code path is never hit because UUIDs are always randomized.
Nonetheless, fqdn.RuleGen.addRule shouldn't assume that and it should
actually work correctly when the same UUID is used. It did not.
Previously, re-inserting a UUID would skip adding this rule's UUID to
a DNS matchName/Pattern that already had UUIDs associated with it (not
necessarily this one!).
The code now ensures that this UUID is associated with matchName/Pattern
entries in the ToFQDNs rule even on updates that partially modify the
rule.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6856)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]

**Comment by raybejjani** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@raybejjani you still want to add tests for this or merge it as is?

**Comment by raybejjani** [comment]
@aanm It was on my list to add a test, but I can make a separate PR. Nothing important broke because the main tests passed (because, of course, our tests cover all the important things).

**Pull request merged**
