### PR TITLE
policy: Fix concurrent access of SelectorCache

### LINKED ISSUE #24021: concurrent map read and map write panic after importing CiliumNetworkPolicy
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

One cilium agent pod crashed after importing a `CiliumNetworkPolicy` with error `fatal error: concurrent map read and map write`. I've hit this during a connectivity test [here](https://github.com/cilium/cilium/actions/runs/4264336582/jobs/7422286692).

### Cilium Version

Current latest on master: 918b75c5b385ac8ac7152c6b841705ebffd6ebbf

### Kernel Version

Not relevant

### Kubernetes Version

Not relevant

### Sysdump

[cilium-sysdump-20230224-164728.zip](https://github.com/cilium/cilium/files/10827320/cilium-sysdump-20230224-164728.zip)

### Relevant log output

```shell
2023-02-24T16:47:17.128413432Z level=info msg="Imported CiliumNetworkPolicy" ciliumNetworkPolicyName=client-egress-to-cidr-deny k8sApiVersion= k8sNamespace=cilium-test subsys=k8s-watcher
2023-02-24T16:47:17.132382045Z fatal error: concurrent map read and map write
2023-02-24T16:47:17.145717662Z 
2023-02-24T16:47:17.146030778Z goroutine 1620 [running]:
2023-02-24T16:47:17.146541906Z github.com/cilium/cilium/pkg/policy.(*SelectorCache).GetLabels(0xc003fec1f5?, 0xa?)
2023-02-24T16:47:17.146931027Z 	/go/src/github.com/cilium/cilium/pkg/policy/selectorcache.go:1094 +0x3f
2023-02-24T16:47:17.147768072Z github.com/cilium/cilium/pkg/policy.(*MapStateEntry).getNets(0xc003833f98, {0x3769b20?, 0xc0003c25b0?}, 0x0?)
2023-02-24T16:47:17.148152992Z 	/go/src/github.com/cilium/cilium/pkg/policy/mapstate.go:204 +0x75
2023-02-24T16:47:17.153780895Z github.com/cilium/cilium/pkg/policy.entryIdentityIsSupersetOf({0x1?, 0x0?, 0x0?, 0x0?}, {0x0, 0x1, 0x0, {0xc00223a540, 0x1, 0x1}, ...}, ...)
2023-02-24T16:47:17.154156315Z 	/go/src/github.com/cilium/cilium/pkg/policy/mapstate.go:381 +0x87
2023-02-24T16:47:17.154403328Z github.com/cilium/cilium/pkg/policy.MapState.denyPreferredInsertWithChanges(0x8?, {0x100003e, 0x0, 0x0, 0x1}, {0x0, 0x1, 0x0, {0xc00223a540, 0x1, ...}, ...}, ...)
2023-02-24T16:47:17.154410129Z 	/go/src/github.com/cilium/cilium/pkg/policy/mapstate.go:435 +0xb25
2023-02-24T16:47:17.154413529Z github.com/cilium/cilium/pkg/policy.MapState.DenyPreferredInsert(...)
2023-02-24T16:47:17.154417129Z 	/go/src/github.com/cilium/cilium/pkg/policy/mapstate.go:285
2023-02-24T16:47:17.154420529Z github.com/cilium/cilium/pkg/policy.(*EndpointPolicy).computeDirectionL4PolicyMapEntries(0xc0017745c0, 0xc0017745c0?, 0xc003f4f51c?, 0xc0?)
2023-02-24T16:47:17.154423629Z 	/go/src/github.com/cilium/cilium/pkg/policy/resolve.go:191 +0x2c5
2023-02-24T16:47:17.159766616Z github.com/cilium/cilium/pkg/policy.(*EndpointPolicy).computeDesiredL4PolicyMapEntries(0xc0017745c0)
2023-02-24T16:47:17.159780717Z 	/go/src/github.com/cilium/cilium/pkg/policy/resolve.go:164 +0x56
2023-02-24T16:47:17.159793418Z github.com/cilium/cilium/pkg/policy.(*selectorPolicy).DistillPolicy(0xc0003cae60, {0x37a5b00?, 0xc0003df180}, 0x0)
2023-02-24T16:47:17.159796818Z 	/go/src/github.com/cilium/cilium/pkg/policy/resolve.go:141 +0x105
2023-02-24T16:47:17.159799818Z github.com/cilium/cilium/pkg/policy.(*cachedSelectorPolicy).Consume(0xc000602a80?, {0x37a5b00?, 0xc0003df180?})
2023-02-24T16:47:17.159802918Z 	/go/src/github.com/cilium/cilium/pkg/policy/distillery.go:202 +0x32
2023-02-24T16:47:17.159805918Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regeneratePolicy(0xc0003df180)
2023-02-24T16:47:17.159808919Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:237 +0x40e
2023-02-24T16:47:17.159811919Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).runPreCompilationSteps(0xc0003df180, 0xc002df2c00)
2023-02-24T16:47:17.159815719Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:844 +0x2c7
2023-02-24T16:47:17.159819219Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc0003df180, 0xc002df2c00)
2023-02-24T16:47:17.159822319Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:603 +0x189
2023-02-24T16:47:17.159825319Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc0003df180, 0xc002df2c00)
2023-02-24T16:47:17.159828320Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:401 +0x7a5
2023-02-24T16:47:17.159831520Z github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc003768830, 0x2ad97c0?)
2023-02-24T16:47:17.159834620Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/events.go:53 +0x325
2023-02-24T16:47:17.159837720Z github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run.func1()
2023-02-24T16:47:17.159840620Z 	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:245 +0x142
2023-02-24T16:47:17.159844220Z sync.(*Once).doSlow(0xc001c29e01?, 0x4430e5?)
2023-02-24T16:47:17.159847521Z 	/usr/local/go/src/sync/once.go:74 +0xc2
2023-02-24T16:47:17.159851021Z sync.(*Once).Do(...)
2023-02-24T16:47:17.159854021Z 	/usr/local/go/src/sync/once.go:65
2023-02-24T16:47:17.159857121Z github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run(0xc000e45c80?)
2023-02-24T16:47:17.159860521Z 	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:233 +0x45
2023-02-24T16:47:17.159863521Z created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run
2023-02-24T16:47:17.159866422Z 	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:229 +0x76
```

### Anything else?

This function seems to be the culprit based on the stack trace above: https://github.com/cilium/cilium/blob/918b75c5b385ac8ac7152c6b841705ebffd6ebbf/pkg/policy/selectorcache.go#L1093-L1099

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by joestringer**
Marco Iorio reports that with previous code, Cilium could crash at
runtime after importing a network policy, with the following error
printed to the logs:

    fatal error: concurrent map read and map write

The path for this issue is printed also in the logs, with the following
call stack:

    pkg/policy.(*SelectorCache).GetLabels(...)
    pkg/policy.(*MapStateEntry).getNets(...)
    pkg/policy.entryIdentityIsSupersetOf(...)
    pkg/policy.MapState.denyPreferredInsertWithChanges(...)
    pkg/policy.MapState.DenyPreferredInsert(...)
    pkg/policy.(*EndpointPolicy).computeDirectionL4PolicyMapEntries(...)
    pkg/policy.(*EndpointPolicy).computeDesiredL4PolicyMapEntries(...)
    pkg/policy.(*selectorPolicy).DistillPolicy(...)
    pkg/policy.(*cachedSelectorPolicy).Consume(...)
    pkg/endpoint.(*Endpoint).regeneratePolicy(...)
    ...

Upon further inspection, this call path is not grabbing the
SelectorCache lock at any point. If we check all of the incoming calls
to this function, we can see multiple higher level functions calling
into this function. The following tree starts from the deepest level of
the call stack and increasing indentation represents one level higher in
the call stack.

INCOMING CALLS
- f GetLabels github.com/cilium/cilium/pkg/policy • selectorcache.go
  - f getNets github.com/cilium/cilium/pkg/policy • mapstate.go
    - f entryIdentityIsSupersetOf github.com/cilium/cilium/pkg/policy • mapstate.go
      - f denyPreferredInsertWithChanges github.com/cilium/cilium/pkg/policy • mapstate.go
        - f DenyPreferredInsert github.com/cilium/cilium/pkg/policy • mapstate.go
          - f computeDirectionL4PolicyMapEntries github.com/cilium/cilium/pkg/policy • resolve.go
            - f computeDesiredL4PolicyMapEntries github.com/cilium/cilium/pkg/policy • resolve.go
              + f DistillPolicy github.com/cilium/cilium/pkg/policy • resolve.go <--- No SelectorCache lock
          - f DetermineAllowLocalhostIngress github.com/cilium/cilium/pkg/policy • mapstate.go
            + f DistillPolicy github.com/cilium/cilium/pkg/policy • resolve.go <--- No SelectorCache lock
        - f consumeMapChanges github.com/cilium/cilium/pkg/policy • mapstate.go
          + f ConsumeMapChanges github.com/cilium/cilium/pkg/policy • resolve.go <--- Already locks the SelectorCache

Read the above tree as "GetLabels() is called by getNets()",
"getNets() is called by entryIdentityIsSupersetOf()", and so on.
Siblings at the same level of indent represent alternate callers of the
function that is one level of indentation less in the tree, ie
DenyPreferredInsert() and consumeMapChanges() both call
denyPreferredInsertWithChanges().

As annotated above, we see that calls through DistillPolicy() do not
grab the SelectorCache lock. Given that ConsumeMapChanges() grabs the
SelectorCache lock, we cannot introduce a new lock acquisition in any
descendent function, otherwise it would introduce a deadlock in
goroutines that follow that call path. This provides us the option to
lock at some point from the sibling of consumeMapChanges() or higher in
the call stack.

Given that the ancestors of DenyPreferredInsert() are all from
DistillPolicy(), we can amortize the cost of grabbing the SelectorCache
lock by grabbing it once for the policy distillation phase rather than
putting the lock into DenyPreferredInsert() where the SelectorCache
could be locked and unlocked for each map state entry.

Future work could investigate whether these call paths could make use of
the IdentityAllocator's cache of local identities for the GetLabels()
call rather than relying on the SelectorCache, but for now this patch
should address the immediate locking issue that triggers agent crashes.

Fixes: #24021
Supersedes: https://github.com/cilium/cilium/pull/24032
Supersedes: https://github.com/cilium/cilium/pull/24283

```release-note
Fix Cilium crash during network policy computation
```

### CODE REVIEW

**Review by christarazi — COMMENTED** [review]
Fix makes sense to me. 

1. Should we go a step further in this PR as an additional commit to rename `GetLabels` [here](https://github.com/cilium/cilium/blob/18ebb46389157eab6deb5772680660c6b3212e41/pkg/policy/selectorcache.go#L1092) to `GetLabelsLocked` to document the assumption that the SelectorCache is intended to be locked?

2. What do you think of clarifying the locking expectations for the functions in common between the write-locked SelectorCache (`ConsumeMapChanges`) and the read-locked SelectorCache (`DistillPolicy`)? 

Also, as an FYI the call graph in the commit msg omits `ToMapState` as a potential caller; it's a sibling of `DenyPreferredInsert`, btw. Not sure if its omission was intended or not, however I don't think it fundamentally impacts the conclusions drawn from the call graph. It was more that my expectation of the call graph was that it was exhaustive, so when I double-checked locally, I noticed this gap.

**Comment by joestringer** [comment]
Yeah, sounds like (1) and (2) above would be good follow-ups. 

As it turns out, if you start the callgraph from `SelectorCache.GetLabels()`, it does not highlight `ToMapState()` as another caller, because `ToMapState` doesn't use the SelectorCache to grab the labels for an identity. Rather, it calls into the CachingIdentityAllocator which has its own local cache of this information. I took one stab at better-documenting this in https://github.com/cilium/cilium/pull/24321 , and hint at some future explanation in the final paragraph of the commit message.

**Review by giorio94 — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Comment by joestringer** [comment]
This was backported in https://github.com/cilium/cilium/pull/25427, https://github.com/cilium/cilium/pull/25491.

**Comment by lefterisALEX** [comment]
We are running cilium `1.12.15` and are experiencing that issue. This pull request should is backported to our version if i am looking correctly.

We are getting this error mentioned in  #24021 

```
evel=info msg="Policy imported via API, recalculating..." policyAddRequest=e1602b41-ce7e-4404-8465-ed96eaf95513 policyRevision=1646 subsys=daemon
level=info msg="Imported CiliumNetworkPolicy" ciliumNetworkPolicyName=testing k8sApiVersion= k8sNamespace=demo-01 subsys=k8s-watcher
level=info msg="CEP deleted, calling endpointDeleted" CEPName=dc-develop/dc-registration-service-develop-75b6ddd889-mhjz9 CESName=ces-tqnvnq6ks-ppxl2 subsys=k8s-watcher
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
fatal error: concurrent map read and map write

goroutine 13404 [running]:
github.com/cilium/cilium/pkg/policy.(*SelectorCache).GetNetsLocked(0x4fcd9e?, 0x4fd13f?)
	/go/src/github.com/cilium/cilium/pkg/policy/selectorcache.go:1119 +0x68
github.com/cilium/cilium/pkg/policy.getNets({0x358a4a0?, 0xc000119490?}, 0x1e4?)
	/go/src/github.com/cilium/cilium/pkg/policy/mapstate.go:194 +0x58
github.com/cilium/cilium/pkg/policy.identityIsSupersetOf(0x53fa7a8?, 0x7e13, {0x358a4a0, 0xc000119490})
	/go/src/github.com/cilium/cilium/pkg/policy/mapstate.go:399 +0x52
```

**Pull request merged**
