### PR TITLE
mtu: Switch to v/netlink for querying netdevs

### PR DESCRIPTION
**Pull request by brb**
This commit makes the package to use vishvananda/netlink instead of Go's stdlib net for querying netdevs. The latter lib does not set a receive timeout for a netlink socket. As netlink is not a reliable protocol, a recv w/o timeout might block indefinitely.

Partial fix of https://github.com/cilium/cilium/issues/15051.

### CODE REVIEW

**Review by jibi — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]

**Comment by pchaigno** [comment]
This pull request is rather old. Probably worth rebasing before we run the end-to-end tests or lots a new tests will fail.

**Comment by brb** [comment]
test-me-please

**Comment by pchaigno** [comment]
The Travis CI failure looks related.

**Review by joestringer — APPROVED** [review]
:rocket:

**Comment by brb** [comment]
Yeah, the travis CI failure looks legit:
```
FAIL: mtu_test.go:32: MTUSuite.TestNewConfiguration

mtu_test.go:92:

    c.Assert(conf.GetDeviceMTU(), Equals, 65536)

... obtained int = 1500

... expected int = 65536
```

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI runtime hit https://github.com/cilium/cilium/issues/14463.

**Comment by brb** [comment]
test-runtime

**Comment by brb** [comment]
net-next CI hit https://github.com/cilium/cilium/issues/15620 and https://github.com/cilium/cilium/issues/12511.

**Comment by brb** [comment]
test-net-next

**Comment by brb** [comment]
CI 4.19 hit https://github.com/cilium/cilium/issues/15337.

**Comment by brb** [comment]
test-4.19

**Comment by brb** [comment]
net-next hit #15620.

**Pull request merged**
