### PR TITLE
v1.12 backports 2023-02-09

### PR DESCRIPTION
**Pull request by sayboras**
- [x] #23502 -- envoy: Bump envoy version to 1.22.7 (@sayboras)

Once this PR is merged, you can update the PR labels via:

```upstream-prs
$ for pr in 23502; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.12

**Review by pchaigno — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Comment by nbusseneau** [comment]
/test-1.23-4.9

**Comment by sayboras** [comment]
/test-1.18-4.9

**Pull request merged**
