### PR TITLE
test/k8s: Remove replaced service load-balancing tests

### PR DESCRIPTION
**Pull request by joamaki**
Replaced tests:

"Check DualStack services" => test/control-plane/services/dual-stack
"Check in-cluster KPR / Tests NodePort" => test/control-plane/services/nodeport
"Check in-cluster KPR / Tests HostPort" => test/control-plane/services/nodeport
"Check in-cluster KPR / Tests NodePort with sessionAffinity" => bpf/tests/session_affinity_test.c
"Checks connectivity when skipping socket lb in pod ns" => bpf/tests/host_only_socket_lb_test.c

### CODE REVIEW

**Review by brb — APPROVED** [review]
:rocket:

**Review by jibi — APPROVED** [review]

**Review by christarazi — APPROVED** [review]
:rocket:

**Comment by joamaki** [comment]
The failed test is not related to the changes at all, so marking ready to merge.

**Pull request merged**
