### PR TITLE
helm: avoid generating ConfigMapList

### PR DESCRIPTION
**Pull request by kaworu**
According to [the Kubernetes documentation](https://kubernetes.io/docs/reference/using-api/api-concepts/#collections), List objects should not appear in requests.

See also https://github.com/prometheus-operator/kube-prometheus/issues/1735

### CODE REVIEW

**Comment by kaworu** [comment]
This intend to fix a `helm lint` warning, before this patch we have

```
% helm lint --debug --with-subcharts --values ./install/kubernetes/cilium/values.yaml ./install/kubernetes/cilium
==> Linting ./install/kubernetes/cilium
[WARNING] templates/hubble/dashboards-configmap.yaml: object name does not conform to Kubernetes naming requirements: "": metadata.name: Invalid value: "": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

1 chart(s) linted, 0 chart(s) failed
```

After the patch:

```
% helm lint --debug --with-subcharts --values ./install/kubernetes/cilium/values.yaml ./install/kubernetes/cilium
==> Linting ./install/kubernetes/cilium

1 chart(s) linted, 0 chart(s) failed
```

**Review by michi-covalent — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Review by chancez — APPROVED** [review]
Functionally this looks fine. We lost the `if $files` check, but that should be fine since we `range` over `$files` which will produce nothing if `$files` is empty.

**Comment by kaworu** [comment]
> […] We lost the if $files check, but that should be fine since we range over $files which will produce nothing if $files is empty

It wasn't lost, it was removed :wink:

**Review by squeed — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by kaworu** [comment]
/test-1.16-4.9

**Pull request merged**
