### PR TITLE
Add ESP to firewall requirements in documentation for IPSec enabled C…

### LINKED ISSUE #18678: Add ESP to firewall requirements in documentation for IPSec enabled Cilium
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have Cilium deployed on EKS with some workers belonging to a fine grained AWS Security Group.  When I enabled IPSec in Cilium, requests to workloads on these nodes started to fail with timeouts.

At the end of the day, in addition to the rules called out [in the docs](https://docs.cilium.io/en/v1.11/operations/system_requirements/#firewall-rules), I needed to allow ESP traffic from other security groups [as suggested here](https://aws.amazon.com/blogs/security/creating-an-opportunistic-ipsec-mesh-between-ec2-instances/).  This should be added to the required firewall rules (for IPSec enabled Cilium deployments) listed in the docs. 

### Cilium Version

1.11.1

### Kernel Version

5.10

### Kubernetes Version

EKS 1.21

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Kikiodazie**
Adds note on firewall requirement For IPSec enabled Cilium deployments.

Signed-off-by: Divine Odazie <dodazie@gmail.com>

Fixes: #18678 

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

### CODE REVIEW

**Comment by xmulligan** [comment]
@Kikiodazie Thanks for adding! 🎊 Can you squash your commits into one and add sign off to your commit? I use Github desktop to do it, but feel free to do it how you want https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/amending-a-commit

**Comment by Kikiodazie** [comment]
> @Kikiodazie Thanks for adding! 🎊 Can you squash your commits into one and add sign off to your commit? I use Github desktop to do it, but feel free to do it how you want https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/amending-a-commit

Thank you @xmulligan. I have squashed it into one commit and sign off added. I used interactive rebase on the terminal :slightly_smiling_face:

**Review by xmulligan — APPROVED** [review]

**Review by NikAleksandrov — APPROVED** [review]

**Review by qmonnet — CHANGES_REQUESTED** [review]
The comment looks good.

Please massage your commit title and description:

image

Checkpatch complains that your commit title is too long (keep something short, add any additional details in the commit description, separated from the title by a blank line), and you have duplicated `Signed-off-by:` tags.

Thanks a lot for the PR!

**Comment by Kikiodazie** [comment]
@qmonnet I have made the change. What do you think about it now?

**Review by qmonnet — APPROVED** [review]
Looks good, thanks a lot!

**Comment by Kikiodazie** [comment]
> Looks good, thanks a lot!

Yayyy. Thank you.

**Pull request merged**
