### PR TITLE
dnsproxy: Return DNS response before cache update

### PR DESCRIPTION
**Pull request by raybejjani**
We may have slow update behaviour when running the proxy on a loaded
system. In these cases it is more reliable to return the DNS response to
the requesting pod before we block. This assumes that it is better to
absorb a delay in regenerating in a TCP connection setup than to delay
the DNS response beyond its timeout.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7475)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
@raybejjani Should we backport this to 1.4?

**Comment by ianvernon** [comment]
@tgraf I'm fine to backport this. My only question is what testing of this has been performed to validate this is the right fix, and this looks innocuous, but actually is a fairly big behavioral change. @raybejjani can you elaborate on the testing you did for this?

**Comment by raybejjani** [comment]
@ianvernon This isn't the "right" fix for anything specific, unfortunately. I was generally debugging why we saw more DNS timeouts on machines under load. Pinning this down was difficult; the specific code segment that was slow seemed to change. In fact, in one instance I saw a Mutex.Unlock call take ~30ms. I realised that with a queue we potentially increase the time the DNS proxy would wait when updating caches. This would only manifest under load, however, since pre-queue we still waited on locks. My hope is that this makes the behaviour more consistent, but it won't be perfect.

As for testing, some of it was just inspection: this specific part of the code updates caches, and sends the response. These are nominally independent but when we introduced metrics to this part of the code we ran into some sequencing sensitivity. I'll test this further since I didn't really try enough possible combinations. Otherwise, I did run this code for a few hours while tracking the timings under load. The consistency was better and my node didn't deadlock (despite various errors).

**Pull request merged**
