### PR TITLE
kafka, go.mod, vendor: use github.com/cilium/kafka fork

### PR DESCRIPTION
**Pull request by tklauser**
We have been using that fork since 2017. Let's replace the import path in the few instances we use github.com/optiopay/kafka to get rid of another replace in go.mod (and thus make life a tiny bit easier for downstream packages importing github.com/cilium/cilium).

### CODE REVIEW

**Review by rolinh — APPROVED** [review]
Oh man, that's an early Christmas present! :heart:

Only 3 more to go :laughing:

**Review by kaworu — APPROVED** [review]
:pray:

**Comment by tklauser** [comment]
/test-1.16-4.9

**Pull request merged**
