### PR TITLE
v1.10 backport: fix multi option parsing

### PR DESCRIPTION
**Pull request by bimmlerd**
Backport of https://github.com/cilium/cilium/pull/22299

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 22299; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by bimmlerd** [comment]
/test-backport-1.10

**Review by thorn3r — APPROVED** [review]
Looks good, thanks!
CI is failing for the same reason here as the 1.11 backport: GKE is being deploying using K8s v1.25 which cilium:v1.10 doesn't support. Open PR to address this here: https://github.com/cilium/cilium/pull/22724

**Comment by joestringer** [comment]
👍 https://github.com/cilium/cilium/pull/22724 is now backported, we should be able to rebase and see that the CI issues are solved.

**Comment by joestringer** [comment]
I took a fresh look at the backport PR content and it seems highly unlikely that CI will pick up any further issues with the backport. Merging.

**Comment by joestringer** [comment]
@bimmlerd please do not forget to either use the official backport scripts or add the ```` ```upstream-prs ... ``` ```` spiel into the backport PR description. This is how we generate release notes. I have done it in this case.

**Pull request merged**
