### PR TITLE
Test: Kafka wait until all endpoints are ready.

### PR DESCRIPTION
**Pull request by eloycoto**
Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4959)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]
Awesome!

**Comment by ianvernon** [comment]
Actually, I do have one question - how does checking the endpoints to be ready (i.e., policy is regenerated and no other builds are queued) ensure that DNS is ready as well?

**Comment by eloycoto** [comment]
Green build -> https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5225/

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
Another green build: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5230/

**Comment by eloycoto** [comment]
test-me-please

**Comment by tgraf** [comment]
@eloycoto @ianvernon Should we be checking for both? Ability to resolve DNS and endpoints up?

**Comment by ianvernon** [comment]
@tgraf sure, can't hurt.

**Comment by eloycoto** [comment]
The kafka issue is still in there: 

```
cmd: "kubectl -ti -n kube-system exec microscope -- microscope| ts '[%Y-%m-%d %H:%M:%S]'" exitCode: 0STEP: Waiting for DNS to resolve within pods for kafka-service
time="2018-07-24T21:43:25Z" level=debug msg="running command: kubectl exec -n default empire-hq-749db985fb-mr477 -- nslookup kafka-service"
cmd: "kubectl exec -n default empire-hq-749db985fb-mr477 -- nslookup kafka-service" exitCode: 0 stdout:

Name:      kafka-service
Address 1: 10.10.1.57 10-10-1-57.kafka-service.default.svc.cluster.local

stderr:
nslookup: can't resolve '(null)': Name does not resolve

time="2018-07-24T21:43:25Z" level=debug msg="running command: kubectl exec -n default empire-outpost-8888-84469c7b8b-xngdt -- nslookup kafka-service"
cmd: "kubectl exec -n default empire-outpost-8888-84469c7b8b-xngdt -- nslookup kafka-service" exitCode: 1 stdout:


stderr:
nslookup: can't resolve '(null)': Name does not resolve
nslookup: can't resolve 'kafka-service': Name does not resolve
command terminated with exit code 1

time="2018-07-24T21:43:30Z" level=debug msg="running command: kubectl exec -n default empire-outpost-8888-84469c7b8b-xngdt -- nslookup kafka-service"
cmd: "kubectl exec -n default empire-outpost-8888-84469c7b8b-xngdt -- nslookup kafka-service" exitCode: 0 stdout:

Name:      kafka-service
Address 1: 10.10.1.57 10-10-1-57.kafka-service.default.svc.cluster.local

stderr:
nslookup: can't resolve '(null)': Name does not resolve
```
```
/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
Failed to produce to empire-hq on topic empire-announce
Expected
    <*errors.errorString | 0xc4203afdc0>: {
        s: "ExecKafkaPodCmd: command 'kubectl exec -n default empire-hq-749db985fb-mr477 sh -- -c \"echo 'Happy 40th Birthday to General Tagge' | ./kafka-produce.sh --topic empire-announce\"' failed '' || '[2018-07-24 21:43:31,060] WARN Removing server kafka-service:9092 from bootstrap.servers as DNS resolution failed for kafka-service (org.apache.kafka.clients.ClientUtils)\norg.apache.kafka.common.KafkaException: Failed to construct kafka producer\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:416)\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:288)\n\tat kafka.producer.NewShinyProducer.<init>(BaseProducer.scala:40)\n\tat kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:48)\n\tat kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)\nCaused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers\n\tat org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:64)\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:373)\n\t... 4 more\ncommand terminated with exit code 1\n'",
    }
to be nil
/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/k8sT/KafkaPolicies.go:172
```


https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1288/testReport/junit/k8s-1/11/K8sValidatedKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/
[9acb0442_K8sValidatedKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies(2).zip](https://github.com/cilium/cilium/files/2226229/9acb0442_K8sValidatedKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.2.zip)

**Comment by eloycoto** [comment]
test-me-please

**Comment by ianvernon** [comment]
@eloycoto test failure appears related:

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:333
Kafka Pods are not ready after timeout
Expected
    <*errors.errorString | 0xc420e9e220>: {
        s: "Timeout reached: timed out waiting for pods with filter -l zgroup=kafkaTestApp to be ready",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/KafkaPolicies.go:133
```

Link: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5313/

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
