### PR TITLE
v1.9 backports 2021-05-12

### PR DESCRIPTION
**Pull request by jrajahalme**
* #16013 -- envoy: Add response headers access logging (@jrajahalme)
 * #16102 -- envoy: Update Envoy to release 1.17.3 (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16013 16102; do contrib/backporting/set-labels.py $pr done 1.9; done
```

```release-note
Envoy is updated to release 1.17.3
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-backport-1.9

**Comment by jrajahalme** [comment]
test-1.17-5.4

**Review by rolinh — APPROVED** [review]

**Comment by jrajahalme** [comment]
Verifier problem in test-1.17-5.4 seems sticky, but should be unrelated to Envoy version being used.

**Comment by jrajahalme** [comment]
test-1.19-4.9

**Comment by jrajahalme** [comment]
test-1.17-5.4

**Comment by jrajahalme** [comment]
Consistent verifier test fail in test-1.17-5.4: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-5.4/13/testReport/Suite-k8s-1/17/K8sVerifier_Runs_the_kernel_verifier_against_Cilium_s_BPF_datapath/

**Pull request merged**
