### PR TITLE
v1.13 backports 2023-06-02

### PR DESCRIPTION
**Pull request by sayboras**
- [x] #25079 -- test: Collect sysdump as part of artifacts (@pchaigno)
 - [x] #25742 -- bpf: dsr: fix typo in tail_nodeport_dsr_ingress_ipv4() (@julianwiedmann)
 - [ ] #25795 -- bpf,datapath: read jiffies from /proc/schedstat (@ti-mo)
    - :warning: minor conflicts
 - [x] #25774 -- Pick up the latest startup-script image (@michi-covalent)
 - [ ] #25747 -- test: prevent panic on k8s services host fw test on some runs. (@tommyp1ckles)
 - [x] #25803 -- daemon: Reject BPF Host Routing without KPR=strict (@pchaigno)

Skipped due to major conflicts:

 - [ ] ~#25450 -- Slim down Node handler interface (@bimmlerd)~
    - :loudspeaker: major conflicts due to hive and cell changes
 - [ ] ~#25419 -- wireguard, linuxnodehandler: untangle WireGuard agent from the linux node handler (@bimmlerd)~
     - :loudspeaker: skipped as dependent PRs are not backported (e.g. https://github.com/cilium/cilium/pull/24016)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 25450 25419 25742 25795 25774 25747 25803; do contrib/backporting/set-labels.py $pr done 1.13; done
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.13

**Review by pchaigno — APPROVED** [review]
My PRs look good. Thanks Tam!

**Review by michi-covalent — APPROVED** [review]
https://github.com/cilium/cilium/pull/25855/commits/c0e721b27ce7cdfe942d0414930d1e8c99f3f3c5 lgtm

**Review by julianwiedmann — APPROVED** [review]

**Comment by sayboras** [comment]
/test-backport-1.13

**Comment by sayboras** [comment]
The conflict is very minimal https://github.com/cilium/cilium/pull/25795, most of the reviews are in, CIs are green as well :heavy_check_mark:. 

Marking this ready to merge.

**Pull request merged**
