### PR TITLE
workloads: Synchronous handling of container events

### PR DESCRIPTION
**Pull request by tgraf**
The periodic container runtime watcher has been scheduling go routines into the background for each container to allow for parallel handling. However, the existing waitgroup did not wait for the events to be handled completely. This could cause for a pile up of go routines which continue to interact with the container runtime and the apiserver.

Fixes: #7209

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7217)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Good start, how about the other `handleCreateWorkload()` from inside `ws.enqueueByContainerID()`?

**Comment by tgraf** [comment]
> how about the other `handleCreateWorkload()` from inside `ws.enqueueByContainerID()`

I starred at that code for quite a while. It creates a single go routine for each containerID so it will not pile up. The go routine is garbage collected when len() on the channel returns 0.

I'm a bit careful as it affects the main container runtime event handler as well and I don't want to break it for non Kubernetes. Each container has a channel with a queue of 100 elements. This potentially creates a large backlog but parallelization is limited to the number of containers running. It would be better to have a single queue and limit parallelization with a weighted semaphore though.

Open to more thoughts.

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
I did not find a reason for the call to`ws.enqueueByContainerID(id, nil)` in the periodic watcher to I've removed it.

**Review by joestringer — APPROVED** [review]
Hopefully CI catches if this breaks anything on the libnetwork side..

**Comment by tgraf** [comment]
Fixed up commit message

**Pull request merged**
