### PR TITLE
Add leader requirement to watch from Etcd.

### PR DESCRIPTION
**Pull request by marseel**
In the case of network partition of Etcd, the watch may be hanging without any updates, which can lead to hard-to-debug issues. This adds leader requirement. In this case, if a leader is not elected within 3 election cycles, the watch will return an error.

Signed-off-by: Marcel Zięba <marseel@gmail.com>

### CODE REVIEW

**Review by tklauser — APPROVED** [review]

**Comment by sayboras** [comment]
ConformanceGatewayAPI failure is due to PR not rebase with master, however, it's not related to this change, so we can skip it.

Required review is in, all other CI jobs are passed. Marking this ready to merge.

**Pull request merged**
