### PR TITLE
v1.14 Backports 2024-03-19

### PR DESCRIPTION
**Pull request by gandro**
* [x] #26775 (@mhofstetter)
 * [x] #31016 (@hemanthmalla) :warning: Conflicts, see commit description
 * [x] #31119 (@bimmlerd)
 * [x] #31366 (@PhilipSchmid)
 * [x] #31150 (@sayboras) :warning: Conflicts, see commit description
 * [ ] #31387 (@YutaroHayakawa)
 * [ ] #26998 (@tommyp1ckles)
 * [x] #31271 (@sayboras)
 * [x] #31420 (@giorio94)
 * [x] #31437 (@pchaigno)

PRs skipped due to conflicts:

 * #30906 (@bimmlerd)
 * #31030 (@bimmlerd)
 * #31380 (@marseel)
 * #31358 (@christarazi)
 * #31214 (@tommyp1ckles)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 26775 31016 31119 31366 31150 31387 26998 31271 31420 31437
```

### CODE REVIEW

**Review by mhofstetter — APPROVED** [review]
Thanks @gandro

**Review by sayboras — APPROVED** [review]
Thanks for resolving the conflict, the commits look good :heavy_check_mark:

**Review by giorio94 — APPROVED** [review]
My commit looks good, thanks!

**Comment by gandro** [comment]
/test-backport-1.14

**Review by PhilipSchmid — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Comment by christarazi** [comment]
No need for https://github.com/cilium/cilium/pull/31358 on v1.14.

**Review by hemanthmalla — APPROVED** [review]
LGTM. Thanks

**Review by bimmlerd — APPROVED** [review]

**Comment by gandro** [comment]
Non-trivial reviews are in. Marking ready to merge.

**Pull request merged**
