### PR TITLE
Add extraArgsList to helm chart

### LINKED ISSUE #14944: Helm chart doesn't support multiple --api-rate-limit arguments
## Bug report

Hey guys,

Further to our [slack thread](https://cilium.slack.com/archives/C1MATJ5U5/p1613075990014900), I'm creating this issue to associate with the PR I'm about to submit.

The issue is that in order to adjust the default API rate limits, it's necessary to pass multiple `--api-rate-limit` arguments to cilium-agent. However, the helm chart implements `extraArgs` as an object, and so it's not possible to pass duplicate keys with different values. (duplicates are discarded).

**General Information**

- Cilium version (run `cilium version`) : 1.9.4
- Kernel version (run `uname -a`) : N/A
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...) : Kubernetes with helm v3.5.2

**How to reproduce the issue**

```
❯ helm template . --set extraArgs.api-rate-limit=foo --set extraArgs.api-rate-limit=bar | grep rate-limit -C 3
      containers:
      - args:
        - --config-dir=/tmp/cilium/config-map
        - --api-rate-limit=bar
        command:
        - cilium-agent
        livenessProbe:
```

### PR DESCRIPTION
**Pull request by funkypenguin**
(This PR supercedes https://github.com/cilium/cilium/pull/14946, during which I got my local git branches/commits so tangled up that it was quicker to create a new PR!)

This commit introduces an extra helm value, `extraArgsList`,
which permits passing extra arguments to the cilium-agent, and allows
for duplication of arguments.

An new value was chosen to avoid breaking existing configurations/documentation.

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [X] Thanks for contributing!

Fixes: #14944

```release-note
Add extraArgsList to helm chart to permit duplicate arguments to be passed to cilium-agent
```

### CODE REVIEW

**Comment by funkypenguin** [comment]
Gah. I woke the beast by telling GitHub to update the PR against the target branch!

**Comment by qmonnet** [comment]
Thanks a lot! Your first commit looks good. Not sure what the second one is for, did you try the automatic update button proposed by GitHub? It should not be necessary, if you have conflicts on your first patch you may prefer to rebase on top of the current master and force-push on the PR. No need to update otherwise.

CI issue is linked to #14950 and does not come from your changes.

**Review by nebril — APPROVED** [review]

**Comment by Skymirrh** [comment]
I think this PR is related to #14974 in its goal.
I would tend to think we should do first answer the questions raised [here](https://github.com/cilium/cilium/pull/14974#discussion_r576213685).

**Comment by Skymirrh** [comment]
Consensus reached, what we'd like to do re: Helm `extraArgs` has been documented in #15150.

**Comment by Skymirrh** [comment]
Since goal has changed and is now tracked in #15150, I will be closing this PR.

@funkypenguin I would like to thank you again for your contribution! Even if the PR was not merged in the end, it was plenty useful: your #14944 shed light on improvements to be made on Helm charts re: duplication of extra parameters, and thanks to the solution you hinted at in this PR we now have a clear idea of how to fix the situation :) You are of course most welcome to continue contributing, whether for #15150 or anything you wish to.

**Pull request closed without merging**
