### PR TITLE
cilium-docker-plugin: set default CMD to /usr/bin/cilium-docker

### PR DESCRIPTION
**Pull request by jrajahalme**
[ upstream commit 084674e4cd84a7c76f28fba404ee340b8bc74d95 ]

Fixes: 18eb98aaac16 ("add cilium-docker-plugin Dockerfile")
Reported-by: Chanwit Kaewkasi <chanwit@gmail.com>
Signed-off-by: André Martins <andre@cilium.io>
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7049)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by ianvernon** [comment]
Istio test failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9824/testReport/junit/k8s-1/13/K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter_service_connectivity/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
