### PR TITLE
manager: Wait for policy map changes to be done before waiting for the ACK

### PR DESCRIPTION
**Pull request by jrajahalme**
Pending operations that may N/ACK must be placed into a
completion.WaitGroup before waiting for the N/ACK. Otherwise we may
wait for an empty completion.WaitGroup and release the returned
sync.WaitGroup right after endpoints have applied their policy map
changes, but without waiting for the N/ACK.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9392)

### CODE REVIEW

**Comment by jrajahalme** [comment]
@raybejjani This was a tricky one to track down, can you take a look?

**Comment by jrajahalme** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build got into a bad state unrelated to PR changes:

```
Setting status of a74a1e8398e0a69d43ec72ad922ccaf1b3c496ed to FAILURE with url https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/15366/ and message: 'Build finished. '
Using context: Cilium-Ginkgo-Tests
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.kohsuke.github.Requester.parse(Requester.java:615)
```

Link: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/15366/

**Comment by ianvernon** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]
Nice catch!

**Review by aanm — APPROVED** [review]

**Pull request merged**
