### PR TITLE
helm: re-generate quick-install.yml after PR #10566

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
There's probably no point running `test-me-please` unless #10616 and/or #10425 are solved.

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
no need to backport it for 1.6

**Comment by borkmann** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
Hit #10669: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18250/

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Pull request merged**
