### PR TITLE
Remove Slack notifications

### PR DESCRIPTION
**Pull request by michi-covalent**
Let's use Grafana instead to monitor CI stability.

Ref: https://github.com/cilium/cilium/pull/21238

Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
:heavy_check_mark:

**Review by nbusseneau — APPROVED** [review]
Off you go.

**Comment by michi-covalent** [comment]
this PR only removes 'Send slack notification' step from workflows so no need for a full CI run. marking as ready to merge.

**Comment by tklauser** [comment]
Like #21238, should this be backported to the stable branches? We still seem to be using slack notification there (noticed while reviewing https://github.com/cilium/cilium/pull/21443).

**Pull request merged**
