### PR TITLE
WIP 1.5 CI debugging

### PR DESCRIPTION
**Pull request by ianvernon**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8229)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2175/

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by aanm** [comment]
@ianvernon please rebase this branch against v1.5

**Comment by ianvernon** [comment]
test-missed-k8s

**Pull request closed without merging**
