### PR TITLE
recorder: hive cell (recorder & rest api handler)

### PR DESCRIPTION
**Pull request by mhofstetter**
This PR introduces a new Hive Cell for the PCAP recorder that provides the recorder and the corresponding rest api handler.

### CODE REVIEW

**Review by joamaki — APPROVED** [review]

**Review by ldelossa — APPROVED** [review]
LGTM

**Review by ysksuzuki — APPROVED** [review]

**Comment by mhofstetter** [comment]
rebased to `main` to get some fixes for Gateway API checks.

**Review by dylandreimerink — APPROVED** [review]

**Comment by mhofstetter** [comment]
rebased to `main` to resolve conflicts.

**Pull request merged**
