### PR TITLE
v1.10 backports 2021-12-10

### PR DESCRIPTION
**Pull request by nbusseneau**
* #17005 -- github: Misc improvements for the L4LB test suite (@brb)
 * #18117 -- test: Add Error Log Exceptions (@nathanjsweet)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 17005 18117; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
@nathanjsweet Please see conflict notes in commit description for double confirmation.

**Comment by nbusseneau** [comment]
/test-backport-1.10

**Comment by nbusseneau** [comment]
1.19 / 5.4 failed with
```
20:03:38  K8sDatapathConfig IPv4Only 
20:03:38    Check connectivity with IPv6 disabled
20:03:38    /home/jenkins/workspace/Cilium-PR-K8s-1.19-kernel-5.4/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
20:03:38  19:03:37 STEP: Installing Cilium
20:04:07  FAIL: Cilium cannot be installed
20:04:07  Expected
20:04:07      <*helpers.cmdError | 0xc00090a7f0>: Unable to delete existing cilium YAML (signal: killed) output: cmd: kubectl delete -f  cilium-16bf789498a408c2.yaml --wait --ignore-not-found
20:04:07  Exitcode: -1 
20:04:07  Err: signal: killed
20:04:07  Stdout:
20:04:07   	 
20:04:07  Stderr:
20:04:07   	 
20:04:07  
20:04:07  to be nil
20:04:07  === Test Finished at 2021-12-10T19:04:07Z====
20:04:07  19:04:07 STEP: Running JustAfterEach block for EntireTestsuite K8sDatapathConfig
20:04:50  ===================== TEST FAILED =====================
20:04:50  19:04:47 STEP: Running AfterFailed block for EntireTestsuite K8sDatapathConfig
20:05:50  cmd: kubectl get pods -o wide --all-namespaces
20:05:50  Exitcode: -1 
20:05:50  Err: signal: killed
20:05:50  Stdout:
20:05:50   	 
20:05:50  Stderr:
20:05:50   	 
20:05:50  
20:05:50  Fetching command output from pods []
```

Never seen this one 🤔

**Comment by nbusseneau** [comment]
1.16 / net-next hit #12511.

**Comment by nbusseneau** [comment]
GKE Jenkins test hit issues around FQDN tests:

- K8sFQDNTest Validate that multiple specs are working correctly
- K8sFQDNTest Validate that FQDN policy continues to work after being updated
- K8sFQDNTest Restart Cilium validate that FQDN is still working

Issue seems to originate from `K8sFQDNTest Restart Cilium validate that FQDN is still working` where the `kube-dns` pods get stuck in `CrashLoopBackOff` when Cilium tries to restart unmanaged pods after being installed:
```
18:42:42 STEP: Restarting unmanaged pods kube-dns-7f4d6f474d-b8rq8, kube-dns-7f4d6f474d-nb4g4 in namespace kube-system
18:42:43 STEP: Validating if Kubernetes DNS is deployed
18:42:43 STEP: Checking if deployment is ready
18:42:43 STEP: Kubernetes DNS is not ready: unable to retrieve deployment kube-system/coredns: Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Error from server (NotFound): deployments.apps "coredns" not found
	 

18:42:43 STEP: Restarting Kubernetes DNS (-l k8s-app=kube-dns)
```
which then have the `beforeAll` step step in the 2 other tests.

**Comment by nbusseneau** [comment]
L4LB tests are failing with
```
++ kubectl -n kube-system get pod -l k8s-app=cilium '-o=jsonpath={.items[0].metadata.name}'
+ CILIUM_POD_NAME=cilium-5brjm
+ kubectl -n kube-system wait --for=condition=Ready pod cilium-5brjm --timeout=5m
error: timed out waiting for the condition on pods/cilium-5brjm
```
This is #18211.

**Comment by nbusseneau** [comment]
/test-1.19-5.4

**Review by nathanjsweet — APPROVED** [review]
Looks good for my changes.

**Review by brb — APPROVED** [review]
My changes LGTM, thanks.

**Comment by nbusseneau** [comment]
CI failures are known flakes, all reviews are in, merging.

**Pull request merged**
