### PR TITLE
test/K8sUpdates: Bump stable branch for v1.12 development

### PR DESCRIPTION
**Pull request by pchaigno**

### CODE REVIEW

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
test-1.22-4.19

**Comment by pchaigno** [comment]
test-1.23-net-next

**Comment by pchaigno** [comment]
test-1.23-net-next

**Comment by pchaigno** [comment]
test-1.22-4.19

**Comment by pchaigno** [comment]
test-1.23-net-next

**Comment by pchaigno** [comment]
test-1.23-net-next

**Comment by pchaigno** [comment]
test-1.23-net-next

**Review by joestringer — APPROVED** [review]
Thanks!

**Comment by joestringer** [comment]
Oh, one minor nit: The PR says "v1.11 development" but this is for testing v1.12, with upgrade _from_ v1.11.

**Comment by pchaigno** [comment]
test-gke

**Review by tklauser — APPROVED** [review]

**Comment by pchaigno** [comment]
Tests are passing except for k8s-1.21-kernel-5.4 which failed with known flake #16852. Reviews are in. Merging.

**Pull request merged**
