### PR TITLE
Test ci fix

### PR DESCRIPTION
**Pull request by jrfastab**
testing fix for ci tests...

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7293)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
previously 1.8 failed 1.13 passed going to try again and see if we get same result.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
fqdn failure

**Comment by jrfastab** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]

**Comment by jrfastab** [comment]
"real" PRs out closing.

**Comment by jrfastab** [comment]
(Re)testing mark checks on state as well as policy. Perhaps being paranoid but its possible xfrm state could match packets posted to the stack unintentionally without further mark restrictions.

And now we can run CI without hitting tx unit hang at driver layer so retry.

WIP for now I'll roll this into a broader PR of refinements later.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
clearing out stale PRs

**Pull request closed without merging**
