### PR TITLE
install: add TerminationMessagePolicy to cilium pods

### PR DESCRIPTION
**Pull request by squeed**
This "captures" the last few lines of logs and sets them as the TerminationMessage in the Status. This means that errors are preserved even if logs are lost (e.g. because of node restarts).

Signed-off-by: Casey Callendrello <cdc@isovalent.com>

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
LGMT :100:

for other reviewers https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#container-v1-core

> Indicate how the termination message should be populated. File will use the contents of terminationMessagePath to populate the container status message on both success and failure. FallbackToLogsOnError will use the last chunk of container log output if the termination message file is empty and the container exited with an error. The log output is limited to 2048 bytes or 80 lines, whichever is smaller. Defaults to File. Cannot be updated.

**Review by kaworu — APPROVED** [review]
Thanks for the PR @squeed. Generally speaking this seems like a "sane default" setting, does that make sense? If yes, should it also be added to other containers (i.e. Hubble UI, Hubble Relay, preflight etc.)?

**Comment by squeed** [comment]
> Thanks for the PR @squeed. Generally speaking this seems like a "sane default" setting, does that make sense? If yes, should it also be added to other containers (i.e. Hubble UI, Hubble Relay, preflight etc.)?

Yeah, I'll add it to all pods.

**Comment by squeed** [comment]
@kaworu added it to every container I could find :-)

**Review by aanm — APPROVED** [review]

**Review by kaworu — APPROVED** [review]
@squeed thank you!

**Comment by kaworu** [comment]
@squeed IMHO `release-note/minor` is bit of a stretch here, `release-note/misc` might be more appropriate? cc @aanm

**Comment by aanm** [comment]
> @squeed IMHO `release-note/minor` might be a bit of a stretch here, `release-note/misc` is probably more appropriate cc @aanm

@kaworu That's a fair point but actually `release-note/minor` looks good here because this is a user-facing change in the sense that users will now be able to see what happened to a crashing cilium with `kubectl describe pod`. :-)

**Comment by kaworu** [comment]
@aanm make sense thanks for the explanation!

**Review by nathanjsweet — APPROVED** [review]

**Pull request merged**
