### PR TITLE
common/types: remove unused files

### PR DESCRIPTION
**Pull request by ianvernon**
All of the code in the following files is not used anywhere in Cilium:
* common/types/namespace_annotation.go
* common/types/ping.go
* common/types/server.go

Remove it accordingly to keep the code base tidy.

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5140)

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
:tada:

**Comment by ianvernon** [comment]
Build failure: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5546/

Will triage. Trying tests again since this code was not used anywhere in Cilium. But, want to get a green build all the same.

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
