### PR TITLE
cilium: make tcp rebalance grace period configurable

### PR DESCRIPTION
**Pull request by borkmann**
See commit desc.

### CODE REVIEW

**Review by brb — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
nit, this seems like it adds some extra branches which could increase complexity (vs not differentiating TCP). But otherwise LGTM.

**Comment by borkmann** [comment]
> nit, this seems like it adds some extra branches which could increase complexity (vs not differentiating TCP). But otherwise LGTM.

Agree, but I think we cannot just use the UDP specific timeout setting here. :/ Yeah, few more branches.

**Review by jibi — APPROVED** [review]

**Review by twpayne — APPROVED** [review]

**Pull request merged**
