### PR TITLE
1.2 backports 2018-10-11

### PR DESCRIPTION
**Pull request by joestringer**
* #5835
  * Minor conflict, @jrajahalme please take a look.
* #5837
  * Rebased to also add changes to v1.7 YAMLs
* #5840
* #5842
  * Backport #5652 to resolve conflict
* #5855

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5845)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

EDIT: Realised that YAML changes didn't make their way into the v1.7 YAMLs. Fixed that up.

**Comment by joestringer** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]

**Comment by jrajahalme** [comment]
`bindata` is out of date.

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build timed out while building Cilium container image:
```
06:23:53     k8s1-1.11: service/kube-dns created
06:23:53     k8s1-1.11: building cilium/cilium container image...
08:21:05 Sending interrupt signal to process
08:21:05 Sending interrupt signal to process
08:21:15 After 10s process did not stop
```

Seems like an infrastructure issue again. Trying again.

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by joestringer** [comment]
Failure:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7180/testReport/junit/k8s-1/7/K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies/

```
Stacktrace
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
Failed to produce to empire-hq on topic deathstar-plans
Expected
    <*errors.errorString | 0xc42850e820>: {
        s: "ExecKafkaPodCmd: command 'kubectl exec -n default empire-hq-2917507631-2qpsg sh -- -c \"echo 'deathstar reactor design v3' | ./kafka-produce.sh --topic deathstar-plans\"' failed '' || 'The connection to the server 192.168.36.11:6443 was refused - did you specify the right host or port?\n'",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/KafkaPolicies.go:177
Standard Output
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Cilium pods: []
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:

Standard Error
STEP: Wait for Kafka broker to be up
STEP: Creating new kafka topic empire-announce
STEP: Creating new kafka topic deathstar-plans
STEP: Waiting for DNS to resolve within pods for kafka-service
STEP: Testing basic Kafka Produce and Consume
=== Test Finished at 2018-10-11T16:09:08Z====
===================== TEST FAILED =====================
===================== Existing AfterFailed =====================
```

Given that this is not observed on master and the lack of bugtool output (#5866), I plan to push a fresh version of the backports without digging too much. ~~The failure itself looks similar to #5164.~~

Seems like kubectl became unable to run commands, infra issue?

```
Unable to connect to the server: net/http: TLS handshake timeout
```

[bd4d6df5_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies (2).zip](https://github.com/cilium/cilium/files/2469978/bd4d6df5_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.2.zip)

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Interesting, part of the latest failure:
```
2018-10-11T18:13:59.404810134Z level=error msg="BUG: Timeout while reading perf ring buffer: cpu: 1, Fd: 12, pagesize: 4096, npages: 64, lost: 1321, unknown: 0, state: [0 224 230 247 255 127 0 0 0 0 4 0 0 0 0 0 32 0 0 0 0 0 0 0]" subsys=cilium-node-monitor
```

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
I think v1.2 contains the old Kafka tests.

**Pull request merged**
