### PR TITLE
vagrant: bump all Vagrant box versions

### PR DESCRIPTION
**Pull request by tklauser**
Mostly to pick up Go 1.17

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-1.16-netnext

**Comment by tklauser** [comment]
test-1.19-5.4

**Review by pchaigno — APPROVED** [review]

**Comment by twpayne** [comment]
Does the branch name need to be different? The [docs say](https://github.com/cilium/cilium/blob/master/Documentation/contributing/testing/ci.rst#packer-ci-build):

> Once you change the image versions locally, create a branch named `pr/update-packer-ci-build` and open a PR `github.com/cilium/cilium`. It is important that you use that branch name so the VM images are cached into packet.net before the branch is merged.

cc @gandro

**Comment by tklauser** [comment]
> Does the branch name need to be different? The [docs say](https://github.com/cilium/cilium/blob/master/Documentation/contributing/testing/ci.rst#packer-ci-build):
> 
> > Once you change the image versions locally, create a branch named `pr/update-packer-ci-build` and open a PR `github.com/cilium/cilium`. It is important that you use that branch name so the VM images are cached into packet.net before the branch is merged.

Indeed, thanks for reminding me. This also explains why the netnext jenkins jobs failed during VM provisioning. I'll reopen the PR from a branch with the correct name.

**Comment by tklauser** [comment]
Superseded 

> > Does the branch name need to be different? The [docs say](https://github.com/cilium/cilium/blob/master/Documentation/contributing/testing/ci.rst#packer-ci-build):
> > > Once you change the image versions locally, create a branch named `pr/update-packer-ci-build` and open a PR `github.com/cilium/cilium`. It is important that you use that branch name so the VM images are cached into packet.net before the branch is merged.
> 
> Indeed, thanks for reminding me. This also explains why the netnext jenkins jobs failed during VM provisioning. I'll reopen the PR from a branch with the correct name.

Done: #17394 Closing this PR.

**Pull request closed without merging**
