### PR TITLE
daemon: Separate FQDN callbacks into real functions

### PR DESCRIPTION
**Pull request by raybejjani**
This had grown to an absurd degree, and make it very difficult to follow
this code. The code is unchanged, but the inline functions have been
converted into real functions.

It's probably best to view the diff with ignore-whitespace selected.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8038)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
This was just a refactoring, right? I took a look but not a deep look and this seems fine to me.

**Comment by ianvernon** [comment]
@raybejjani I don't think this is necessary for backporting. There are no functional changes, but there have been changes in the FQDN code since v1.5 was released.

**Comment by raybejjani** [comment]
I'm finally getting back to this! It was just refactoring. @ianvernon I was worried that backports would be more difficult since this shuffled code around but we can wait and see.

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
ianvernon was correct, there are enough changes to make this annoying to backport. I've removed the label. It's probably fine.

**Pull request merged**
