### PR TITLE
[v1.12] images: Bump Hubble CLI to v0.11.1

### PR DESCRIPTION
**Pull request by gandro**
This bumps the Hubble CLI to the latest release, v0.11.1. By upgrading the Hubble CLI to the latest release, we ensure that the binary is built using the most recent version of Golang while preserving compatibility to the previous version using the new `HUBBLE_COMPAT` environment variable.

### CODE REVIEW

**Comment by gandro** [comment]
operator build failed with an unrelated temporary issue: https://github.com/cilium/cilium/actions/runs/3998883242/jobs/6862082717

ERROR: failed to solve: failed to do request: Head "https://registry-1.docker.io/v2/docker/dockerfile/manifests/1.2": net/http: TLS handshake timeout 

Closing and re-opening

**Review by michi-covalent — APPROVED** [review]
bump it and ship it

**Review by ldelossa — APPROVED** [review]

**Comment by gandro** [comment]
/test-backport-1.12

**Comment by michi-covalent** [comment]
ci-gke-1.12: a known flake: https://github.com/cilium/cilium/issues/21655

**Comment by michi-covalent** [comment]
[test-1.17-4.9](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-4.9/1027/): a known flake: https://github.com/cilium/cilium/issues/23264

**Comment by michi-covalent** [comment]
/test-1.17-4.9

**Pull request merged**
