### PR TITLE
health: Fix health check to local health agent

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6738)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by joestringer — COMMENTED** [review]
The changes seem fine, but I'm wondering where the `NodeEpAnnotator.AnnotateNode(node.GetName(), nil, nil, ip4, ip6, nil)` call that was deleted in https://github.com/cilium/cilium/commit/be7d5cb4b919e46cb12aa9fbd2ded6b186d17f75 is has moved to? It seems like the node annotation was completely removed without a replacement. See also the `Annotator` interface in `cilium-health/launch/endpoint.go`

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
> The changes seem fine, but I'm wondering where the `NodeEpAnnotator.AnnotateNode(node.GetName(), nil, nil, ip4, ip6, nil)` call that was deleted in [be7d5cb](https://github.com/cilium/cilium/commit/be7d5cb4b919e46cb12aa9fbd2ded6b186d17f75) is has moved to? It seems like the node annotation was completely removed without a replacement. See also the `Annotator` interface in `cilium-health/launch/endpoint.go`

The distribution is happening via the kvstore. Looking at https://github.com/cilium/cilium/blob/master/daemon/daemon.go#L1090, we can simply move that down to after the allocation of the health IPs and also provide it via the node annotations. The removal of the second annotation call was to not require two annotation calls when the node comes up. I'll fix it up.

**Comment by tgraf** [comment]
@joestringer https://github.com/cilium/cilium/pull/6746

**Pull request merged**
