### PR TITLE
v1.6 backports 2019-08-19

### PR DESCRIPTION
**Pull request by vadorovsky**
* #8942 -- docs: Fix versioned archive path (@joestringer)
 * #8919 -- bpf: try to atomically replace filters when possible (@borkmann)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 8942 8919; do contrib/backporting/set-labels.py $pr done 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8950)

### CODE REVIEW

**Comment by mrostecki** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-upstream-k8s

**Pull request merged**
