### PR TITLE
Gather cni logs in bugtool.

### LINKED ISSUE #23912: bugtool: copy CNI logs as well
We should add a command to bugtool that just does a `cat /var/run/cilium/cilium-cni.log`

### PR DESCRIPTION
**Pull request by marseel**
Fixes: #23912

```release-note
sysdump: Added Kubernetes CNI logs to sysdump.
```

### CODE REVIEW

**Review by squeed — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Comment by nathanjsweet** [comment]
I ran the tests to (hopefully) get a CI failure and view the new dump.

**Comment by nathanjsweet** [comment]
There was no sysdump with the failed test.

**Comment by aditighag** [comment]
@marseel Can we tag this PR for backporting to 1.12 and 1.13 so that CNI logs are available as part of sysdump?

**Comment by marseel** [comment]
Added labels as this is a low-risk change.

**Comment by aditighag** [comment]
> Added labels as this is a low-risk change.

@marseel FYI: I updated the correct labels.

**Pull request merged**
