### PR TITLE
vendor: downgrade go-version library due regression

### PR DESCRIPTION
**Pull request by aanm**
There is a regression present in go-version library that prevents to
check the kubernetes version properly. For this reason we will downgrade
the library version up the last commit working. The mitigation for this
regression will be made in a follow up commit as well as upgrading the
library to the most recent version.

Fixes: d1fecef5d46f ("vendor: add go-mod support")
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9459)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
