### PR TITLE
remove export from shell session to avoid the inconsistency

### PR DESCRIPTION
**Pull request by fujitatomoya**
### Description

adding `export` to be environmental variable would be better for user-friendly installation doc, because that user would be likely to copy and paste the command described in this shell session to the terminal to process the installation.

Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

### CODE REVIEW

**Comment by fujitatomoya** [comment]
- Those are just shell variables, user cannot use the following procedure via terminal

```bash
root@edgemaster:~# CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt)
root@edgemaster:~# CLI_ARCH=amd64
root@edgemaster:~# if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
root@edgemaster:~# env | grep CLI
```

- Successfully exported as environmental variable

```bash
root@edgemaster:~# export CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt)
root@edgemaster:~# export CLI_ARCH=amd64
root@edgemaster:~# if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
root@edgemaster:~# env | grep CLI
CLI_ARCH=amd64
CILIUM_CLI_VERSION=v0.12.11
```

**Comment by kaworu** [comment]
Hi @fujitatomoya and thanks for the PR.

Theses variables don't need to be exported for the steps to work, instead of `env | grep CLI` one can use `set | grep CLI` to find shell variables. I would be inclined to remove `export` from `export HUBBLE_VERSION` instead for consistency and avoiding unnecessary export. What do you think?

**Comment by qmonnet** [comment]
Another argument in favour of removing unnecessary `export`s is that the syntax for exporting variables might differ for some less common shells (fish, for example, I think?).

**Comment by fujitatomoya** [comment]
Okay, that also makes sense to me. I wasnt clear that if those are intended to be shell variables or environmental variable using terminal console. probably just remove `export` to keep the consistency, that would be better, fix coming up soon.

**Comment by fujitatomoya** [comment]
@kaworu @qmonnet could you help review again? thanks!

**Review by qmonnet — APPROVED** [review]
Looks good, thank you

**Review by kaworu — APPROVED** [review]
Thanks @fujitatomoya!

**Pull request merged**
