### PR TITLE
1.3 Backports 24-10-2018

### PR DESCRIPTION
**Pull request by eloycoto**
PR that was already in there and labels was not updated: 

PR #5950
PR #5956
PR #5957
PR #5958
PR #5964

Current backports:
PR #6020
PR #6024
PR #6025

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6028)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-docs-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
K8s tests failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1126/testReport/junit/k8s-1/9/K8sChaosTest_Restart_with_long_lived_connections_L3_L4_policies_still_work_while_Cilium_is_restarted/

Looks unrelated to the changes in this PR.

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Pull request merged**
