### PR TITLE
Add runtime policy test with server l7 egress

### PR DESCRIPTION
**Pull request by jrajahalme**
Test http connectivity from host to a pod when the pod has an http egress policy on port 80.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5836)

### CODE REVIEW

**Comment by jrajahalme** [comment]
This is expected to fail before https://github.com/cilium/cilium/pull/5835 is merged.

**Comment by jrajahalme** [comment]
test-me-please

**Review by eloycoto — CHANGES_REQUESTED** [review]
There is a test to validate egress-L7 already, I'm not sure if this is needed at all: lines that are related: 

https://github.com/cilium/cilium/blob/07a0969a2b4badb5e0d3eb874da14e7c2e7d394e/test/runtime/Policies.go#L510-L513

And: 
https://github.com/cilium/cilium/blob/07a0969a2b4badb5e0d3eb874da14e7c2e7d394e/test/runtime/manifests/Policies-l7-simple.json#L44-L60

**Review by aanm — APPROVED** [review]

**Comment by jrajahalme** [comment]
Failed predictably: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7066/
Now that #5835 is merged this should succeed.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
@eloycoto Please see #5835 for context. This PR adds an egress policy to a service pod, not to an app pod like in the policy you linked to. The purpose of the added test is NOT to match the service pod's egress policy. However, we had a bug in the bpf datapath (fixed by #5835) that redirected replies to the proxyport due to an egress L7 policy. The L7 policy added here is a "visibility policy", i.e., causes proxy redirect but does not block any traffic.

**Comment by jrajahalme** [comment]
Now that #5835 is merged the point of this change is to prevent future regressions.

**Review by eloycoto — APPROVED** [review]
@jrajahalme I understood now, thanks :-)

**Review by ianvernon — APPROVED** [review]

**Comment by jrajahalme** [comment]
Unrelated k8s 1.12 test failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7092/execution/node/94/log/

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Docker build failed due to likely transient issue:
```
16:33:43     k8s1-1.12: Step 1/16 : FROM quay.io/cilium/cilium-builder:2018-09-17 as builder
16:34:06     k8s1-1.12: Get https://quay.io/v2/cilium/cilium-builder/manifests/2018-09-17: Get https://quay.io/v2/auth?scope=repository%3Acilium%2Fcilium-builder%3Apull&service=quay.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
16:34:06     k8s1-1.12: Makefile:134: recipe for target 'docker-image' failed
16:34:06     k8s1-1.12: make: *** [docker-image] Error 1
```

**Comment by jrajahalme** [comment]
test-me-please

**Pull request merged**
