### PR TITLE
1.6 Backport 19 08 06

### PR DESCRIPTION
**Pull request by jrfastab**
PRs:
#8792
#8637
#8791 
#8779 
#8755 
#8764 
#8757 
#8773 
#8768 
#8765 
#8747 
#8754 
#8731 
#8749 
#8715

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8802)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
@tgraf please review https://github.com/cilium/cilium/pull/8802/commits/9c4f5034fca71f6e8384d10ee34b31a3d11d9dbf there were some conflicts.

**Comment by jrfastab** [comment]
OK need to rework the helpers patch my conflict resolution is obviously broken.

**Comment by jrfastab** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
