### PR TITLE
Backport v1.5 2019 05 09

### PR DESCRIPTION
**Pull request by raybejjani**
* PR: 7823 -- Separate directories for jenkins parallel builds (@nebril) -- https://github.com/cilium/cilium/pull/7823
 * PR: 7923 -- Bump vagrant box versions for tests (@nebril) -- https://github.com/cilium/cilium/pull/7923
 * PR: 7956 -- metrics: add map_ops_total by default (@aanm) -- https://github.com/cilium/cilium/pull/7956
 * PR: 7937 -- Dockerfile: update golang to 1.12.5 (@aanm) -- https://github.com/cilium/cilium/pull/7937
 * PR: 7946 -- CI: Consolidate WaitforNPods and WaitForPodsRunning and bugfix ready check (@raybejjani) -- https://github.com/cilium/cilium/pull/7946

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7969)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-docs-please

**Comment by raybejjani** [comment]
test-missed-k8s

**Comment by raybejjani** [comment]
wow. This passed first time in 3 test suites... seems bogus to me

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
