### PR TITLE
cni: use right network NS while removing link

### PR DESCRIPTION
**Pull request by nirmoy**
WithNetNSPath(removeIfFromNSIfExists) == removeIfFromNSIfExists(hostNS,
..). removeIfFromNSIfExists runs in expected network namespace but
it gets hostNS as a argument

Signed-off-by: Nirmoy Das <ndas@suse.de>
https://github.com/cilium/cilium/blob/c1f2f3fbe871b3a8b2dbd2b85ff9d1cd4389cfa4/vendor/github.com/containernetworking/cni/pkg/ns/ns.go#L145

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5557)

### CODE REVIEW

**Review by aanm — CHANGES_REQUESTED** [review]
@nirmoy I'm probably missing something but aren't your changes having the same behavior of `ns.WithNSPath`?

https://github.com/cilium/cilium/blob/728c4d44fc8b9d77946d9600d7a7c836abde66cd/vendor/github.com/containernetworking/cni/pkg/ns/ns.go#L169-L178

**Comment by nirmoy** [comment]
@aanm removeIfFromNSIfExists should get netNs of the endpoint. 
in https://github.com/cilium/cilium/blob/c1f2f3fbe871b3a8b2dbd2b85ff9d1cd4389cfa4/plugins/cilium-cni/cilium-cni.go#L481-L483 removeIfFromNSIfExists get hostNS as 1st argument

**Review by aanm — APPROVED** [review]
Great finding!

**Comment by aanm** [comment]
@nirmoy can you add to your commit message 
```

Fixes: dd19c96e33ef ("Ignore non-existing link error in cni del")
```

**Comment by nirmoy** [comment]
@aanm updated

**Review by tgraf — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by joestringer** [comment]
@aanm @tgraf Does this need backporting?

**Comment by aanm** [comment]
@joestringer no, it is unreleased code, I've also removed the release-note/bug.

**Pull request merged**
