### PR TITLE
v1.12 backports 2023-10-02

### PR DESCRIPTION
**Pull request by sayboras**
- [x] #26115 -- bpf: lxc: fix one missing drop notification in CT lookup tail calls (@julianwiedmann)
 - [x] #28272 -- envoy: Sync supported resources in CiliumEnvoyConfig (@sayboras)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 26115 28272; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Comment by julianwiedmann** [comment]
Note that the BPF fix will need https://github.com/cilium/cilium/pull/28295 to land first.

**Comment by sayboras** [comment]
> Note that the BPF fix will need #28295 to land first.

You beat me to this. Yes, I noticed the pending backport PR, so just mark this one as draft.

**Review by julianwiedmann — APPROVED** [review]
The fix itself is good of course, so pre-approving. Thank you!

**Comment by sayboras** [comment]
/test-backport-1.12

**Comment by sayboras** [comment]
Reviews are in, CI is also great, marking this ready to merge.

**Review by ti-mo — APPROVED** [review]

**Pull request merged**
