### PR TITLE
Change default identity change grace period

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7403)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
`k8s-1.13.K8sServicesTest Checks service across nodes with L7 policy Tests NodePort with L7 Policy` failed

**Comment by tgraf** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
