### PR TITLE
Pick up cilium-cli v0.8.2

### PR DESCRIPTION
**Pull request by michi-covalent**

### CODE REVIEW

**Comment by aanm** [comment]
ci-aks

**Comment by aanm** [comment]
ci-gke

**Comment by aanm** [comment]
ci-multicluster

**Comment by aanm** [comment]
ci-gke test is fixed so as ci-awscni. both ci-aks and ci-eks hit https://github.com/cilium/cilium/issues/16542

image

links: https://github.com/cilium/cilium/actions/runs/969774453 https://github.com/cilium/cilium/actions/runs/969774446 https://github.com/cilium/cilium/actions/runs/969774455 https://github.com/cilium/cilium/actions/runs/969774458

**Review by tklauser — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]

**Pull request merged**
