### PR TITLE
[v1.5] ci: update k8s to 1.13.12, 1.14.8 and 1.15.5

### PR DESCRIPTION
**Pull request by aanm**
also update vendor libraries

```release-note
Add support for k8s 1.15.5
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9449)

### CODE REVIEW

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Review by vadorovsky — APPROVED** [review]

**Pull request merged**
