### PR TITLE
Pr/jrajahalme/envoy 1.17.3 backport v1.8

### PR DESCRIPTION
**Pull request by jrajahalme**
* #12331 -- envoy: Move to Envoy API v3 (@jrajahalme)
* #12548 -- proxy: Move Kafka proxy to Envoy Go Extensions (**first commit only**) (@jrajahalme)
* #15232 -- envoy: Do not use deprecated fields (@jrajahalme)
* #14462 -- Update Envoy to release 1.15.3 (@jrajahalme)
* #16102 -- envoy: Update Envoy to release 1.17.3 (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12331 15232 14462 16102; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-backport-1.8

**Comment by jrajahalme** [comment]
Added #14462

**Comment by jrajahalme** [comment]
test-backport-1.8

**Comment by jrajahalme** [comment]
Travis CI for amd64 failed due to docker pull rate limit, arm64 build succeeded:
```
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Comment by jrajahalme** [comment]
Will rerun after rebase once #16105 lands.

**Comment by joestringer** [comment]
Every test other than Travis passed.

**Comment by jrajahalme** [comment]
test-backport-1.8

**Comment by jrajahalme** [comment]
test-backport-1.8

**Review by joestringer — APPROVED** [review]
I recognize that this is quite a bit of churn for v1.8 this late, but given that (1) these are mostly backports for changes that users have been running already in v1.9 for some time and (2) the security background for this (+ benefits for future updates), I think it's a reasonable tradeoff.

**Comment by joestringer** [comment]
Unit tests pass for me locally. Privileged unit tests fail for me locally the same way that the runtime CI does.

**Comment by joestringer** [comment]
Everything else passed, good to merge :+1:

**Pull request merged**
