### PR TITLE
v1.11: Update Go to 1.17.13

### PR DESCRIPTION
**Pull request by tklauser**
This includes various security fixes, see
https://go.dev/doc/devel/release#go1.17.13 for details.

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.11

**Comment by tklauser** [comment]
/test-backport-1.11

**Review by rolinh — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Comment by tklauser** [comment]
/test-1.16-netnext

**Comment by tklauser** [comment]
/test-1.16-netnext

**Comment by tklauser** [comment]
/test-1.20-4.9

**Comment by nathanjsweet** [comment]
/test-1.16-netnext

**Comment by nathanjsweet** [comment]
/test-1.20-4.9

**Comment by nathanjsweet** [comment]
Looks like there was an issue with github, both of the failures from @tklauser 's run were from timing out on checking out cilium for the test.

**Comment by nbusseneau** [comment]
Test failures look like regular flakes. @tklauser Think we can mark as ready to merge?

**Comment by tklauser** [comment]
Ack, GKE and AKS are unstable on master as well. Netlify failure looks like a temporary glitch. Marking as ready to merge.

**Pull request merged**
