### PR TITLE
test: remove microscope test

### PR DESCRIPTION
**Pull request by ianvernon**
The test has been disabled for almost a year, and we don't officially support
microscope anymore. Remove the test accordingly.

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9075)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]

**Comment by eloycoto** [comment]
Maybe is good to remove also from here: 

https://github.com/cilium/packer-ci-build/blob/61cde4e2d8d905e78d116200f5866038b449b45e/provision/pull-images.sh#L31

**Comment by eloycoto** [comment]
And https://github.com/cilium/cilium/blob/master/test/k8sT/manifests/microscope.yaml

**Comment by ianvernon** [comment]
@eloycoto good catch, removed the `microscope.yaml` file too.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
@eloycoto posted PR to remove microscope from cilium/packer-ci-build: https://github.com/cilium/packer-ci-build/pull/168

**Pull request merged**
