### PR TITLE
daemon: bpf: Exclude .gitignore from BPF bindata

### LINKED ISSUE #7058: bpf/.gitignore file is needed to build
Files specific for git (like .git/, .gitignore) are not (and should be not) included in tarballs. But Cilium requires .gitignore files to create bindata files, which prevents builds from tarballs:

```
[    5s] + make -C daemon apply-bindata
[    5s] make: Entering directory '/home/abuild/rpmbuild/BUILD/cilium-1.4.0/daemon'
[    5s] make: *** No rule to make target '../bpf/.gitignore', needed by 'go-bindata'.  Stop.
[    5s] make: Leaving directory '/home/abuild/rpmbuild/BUILD/cilium-1.4.0/daemon'
[    5s] error: Bad exit status from /var/tmp/rpm-tmp.JOiMSK (%build)
```

### PR DESCRIPTION
**Pull request by vadorovsky**
Before this change, .gitignore was needed by go-bindata which made
Cilium builds from tarballs impossible. Tarballs usually do not include
git specific files and directories (i.e. .git/, .gitignore).

Fixes #7058

Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7062)

### CODE REVIEW

**Comment by vadorovsky** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Thanks, I just noticed this too.

**Comment by joestringer** [comment]
Error:

```
15:18:18     runtime: bindata.go: FAILED
15:18:18     runtime: sha1sum: WARNING: 1 computed checksum did NOT match
15:18:18     runtime: ########################################################################
15:18:18     runtime: 
15:18:18     runtime:                   ERROR: bindata.go is out of date.
15:18:18     runtime: 
15:18:18     runtime:  This can happen for two reasons:
15:18:18     runtime:  1. You are using a go-bindata binary compiled with a different version
15:18:18     runtime:     of golang (not 1.9). If so, please up/downgrade.
15:18:18     runtime: 
15:18:18     runtime:  2. You have made changes to the bpf/ directory. Please run the
15:18:18     runtime:     following command to update the SHA in daemon/bpf.sha:
15:18:18     runtime: 
15:18:18     runtime:     $ make -C daemon apply-bindata
15:18:18     runtime: 
15:18:18     runtime: ########################################################################
```

**Comment by ianvernon** [comment]
@mrostecki the bindata SHA is out of date, please rebase and run `make -C daemon/ apply-bindata` again:

```
15:18:18     runtime: bindata.go: FAILED
15:18:18     runtime: sha1sum: WARNING: 1 computed checksum did NOT match
15:18:18     runtime: ########################################################################
15:18:18     runtime: 
15:18:18     runtime:                   ERROR: bindata.go is out of date.
15:18:18     runtime: 
15:18:18     runtime:  This can happen for two reasons:
15:18:18     runtime:  1. You are using a go-bindata binary compiled with a different version
15:18:18     runtime:     of golang (not 1.9). If so, please up/downgrade.
15:18:18     runtime: 
15:18:18     runtime:  2. You have made changes to the bpf/ directory. Please run the
15:18:18     runtime:     following command to update the SHA in daemon/bpf.sha:
15:18:18     runtime: 
15:18:18     runtime:     $ make -C daemon apply-bindata
15:18:18     runtime: 
15:18:18     runtime: ########################################################################
15:18:18     runtime: Makefile:53: recipe for target 'check-bindata' failed
```

EDIT: didn't see Joe's comment above :-) don't mind me...

**Comment by vadorovsky** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
