### PR TITLE
Cleanup leaked GCE kops clusters

### PR DESCRIPTION
**Pull request by marseel**
Add CI job to cleanup leaked clusters.

Example run: https://github.com/cilium/cilium/actions/runs/11796421412/job/32858237616?pr=35915

### CODE REVIEW

**Comment by viktor-kurchenko** [comment]
Hey @marseel, overall the PR LGTM!
But what do you think about delegating the cleanup to already existed Cloud Custodian pipeline?

**Comment by marseel** [comment]
> But what do you think about delegating the cleanup to already existed Cloud Custodian pipeline?

I don't mind that, but Cloud Custodian will still probably not clean up kops state?
I went with this approach as I know it will work :)

**Comment by viktor-kurchenko** [comment]
> > But what do you think about delegating the cleanup to already existed Cloud Custodian pipeline?
> 
> I don't mind that, but Cloud Custodian will still probably not clean up kops state? I went with this approach as I know it will work :)

Absolutely, makes sense!
Do you want to test together if Custodian can do a cleanup?
If yes, can send me an KOPS cluster example and I'll test C7N.

**Review by viktor-kurchenko — APPROVED** [review]
LGTM.

**Review by thorn3r — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Pull request merged**
