### PR TITLE
fix error log when sync EpToPolicy map

### PR DESCRIPTION
**Pull request by arikachen**
Fix error log.

Signed-off-by: arikachen <eaglesora@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7777)

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Review by nirmoy — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
Travis errored out for unrelated reason:
```
level=warning msg="Unable to list keys before starting watcher" config= endpoints="[http://127.0.0.1:4002]" error="context canceled" prefix=test-prefixZLxOuMCZWgdD/id subsys=kvstore watcher=test-prefixZLxOuMCZWgdD/id
level=warning msg="Unable to list keys before starting watcher" config= endpoints="[http://127.0.0.1:4002]" error="rpc error: code = Canceled desc = grpc: the client connection is closing" prefix=test-prefixZLxOuMCZWgdD/id subsys=kvstore watcher=test-prefixZLxOuMCZWgdD/id
level=warning msg="Unable to list keys before starting watcher" config= endpoints="[http://127.0.0.1:4002]" error="rpc error: code = Canceled desc = grpc: the client connection

The job exceeded the maximum log length, and has been terminated.
```

**Comment by ianvernon** [comment]
test-me-please

**Comment by arikachen** [comment]
test-me-please

**Comment by joestringer** [comment]
Hit #7546 . Retrying.

**Comment by joestringer** [comment]
test-me-please

**Pull request merged**
