### PR TITLE
incase expansions be performed

### PR DESCRIPTION
**Pull request by GeorgeGuo2018**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Comment by GeorgeGuo2018** [comment]
cilium

My host's operation system is linux 5.4.119-19.0009.44, tlinux 3.1.
On this host " $(/bin/mount | /bin/grep /sys/fs/bpf -c) -eq 0 " will be peformed before writing to /usr/lib/systemd/system/kubelet.service. 
In the end, inside the /usr/lib/systemd/system/kubelet.service would be like this
[Service]
# Mount BPF fs for cilium
ExecStartPre=/bin/bash -c ' \\
        if [[ 1 -eq 0 ]]; then \\
           /bin/mount bpffs /sys/fs/bpf -t bpf; \\
        fi'

**Review by bimmlerd — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution. Please explain why this is better and add the explanation as a commit message.

**Comment by GeorgeGuo2018** [comment]
> Hi, thanks for your contribution. Please explain why this is better and add the explanation as a commit message.
under certain  kernels like 5.4.119-19.0009.44, this session "$(/bin/mount | /bin/grep /sys/fs/bpf -c)" would be peformed to a certain num before the "sudo tee /etc/systemd/system/kubelet.service <<EOF" command. 
This would lead to a hardcoded if statement, for example" if [[ 1 -eq 0 ]];then"

**Comment by bimmlerd** [comment]
> Under certain  kernels like 5.4.119-19.0009.44, this session "$(/bin/mount | /bin/grep /sys/fs/bpf -c)" would be peformed to a certain num before the "sudo tee /etc/systemd/system/kubelet.service <<EOF" command take effect.
> This would lead to a hardcoded if statement in kubelet.service, for example" if [[ 1 -eq 0 ]];then" .

It seems unlikely to me that the kernel version is what decides whether the substitution occurs earlier or later. How did you determine that this is the reason?

It's difficult for me to understand that the change is equivalent for other systems where this seems to have worked fine so far, could you explain?

**Comment by GeorgeGuo2018** [comment]
> > Under certain  kernels like 5.4.119-19.0009.44, this session "$(/bin/mount | /bin/grep /sys/fs/bpf -c)" would be peformed to a certain num before the "sudo tee /etc/systemd/system/kubelet.service <<EOF" command take effect.
> > This would lead to a hardcoded if statement in kubelet.service, for example" if [[ 1 -eq 0 ]];then" .
> 
> It seems unlikely to me that the kernel version is what decides whether the substitution occurs earlier or later. How did you determine that this is the reason?
> 
> It's difficult for me to understand that the change is equivalent for other systems where this seems to have worked fine so far, could you explain?

You are right. The character '\' before  '$' will prevent the session be peformed.

**Pull request closed without merging**
