### PR TITLE
Remove combine flag from microscope call

### PR DESCRIPTION
**Pull request by nebril**

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by eloycoto** [comment]
Quick question, Why? The combine is the default now?

**Comment by nebril** [comment]
@eloycoto combine flag is removed, new `--rich` flag was added to show the column ui, combined view is default in 1.0.0

**Comment by eloycoto** [comment]
@nebril 

It's working: 
```
['cilium', 'monitor']
2018-04-25 12:03:38,942 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2273)'),)': /api/v1/namespaces/kube-system/pods/cilium-l77lb
2018-04-25 12:03:38,940 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2273)'),)': /api/v1/namespaces/kube-system/pods/cilium-nwf8v

k8s1: Listening for events on 2 CPUs with 64x4096 of shared memory
k8s1: Press Ctrl-C to quit
k8s2: Listening for events on 2 CPUs with 64x4096 of shared memory
k8s2: Press Ctrl-C to quit
k8s2: <- host flow 0xb09c88f9 identity 1->0 state new ifindex enp0s8: 192.168.36.11:6443 -> 10.10.1.142:39060 tcp ACK
k8s2: -> endpoint 48896 flow 0xb09c88f9 identity 1->27475 state reply ifindex lxccd8b4: 10.96.0.1:443 -> 10.10.1.142:39060 tcp ACK
k8s2: <- endpoint 48896 flow 0xc9e98537 identity 27475->0 state new ifindex 0: 10.10.1.142:39060 -> 10.96.0.1:443 tcp ACK
k8s2: -> stack flow 0x4c3a168c identity 27475->2 state established ifindex 0: 10.10.1.142:39060 -> 192.168.36.11:6443 tcp ACK
k8s2: <- endpoint 48896 flow 0x587cd88f identity 27475->0 state new ifindex 0: 10.10.1.142:39392 -> 10.96.0.1:443 tcp ACK
k8s2: -> stack flow 0xc299379c identity 27475->2 state established ifindex 0: 10.10.1.142:39392 -> 192.168.36.11:6443 tcp ACK
k8s2: <- host flow 0x65825fd9 identity 1->0 state new ifindex enp0s8: 192.168.36.11:6443 -> 10.10.1.142:39392 tcp ACK
k8s2: -> endpoint 48896 flow 0x65825fd9 identity 1->27475 state reply ifindex lxccd8b4: 10.96.0.1:443 -> 10.10.1.142:39392 tcp ACK
k8s2: <- endpoint 48896 flow 0x587cd88f identity 27475->0 state new ifindex 0: 10.10.1.142:39392 -> 10.96.0.1:443 tcp ACK
k8s2: -> stack flow 0xc299379c identity 27475->2 state established ifindex 0: 10.10.1.142:39392 -> 192.168.36.11:6443 tcp ACK
k8s2: <- host flow 0x65825fd9 identity 1->0 state new ifindex enp0s8: 192.168.36.11:6443 -> 10.10.1.142:39392 tcp ACK
```

**Review by eloycoto — APPROVED** [review]

**Pull request merged**
