### PR TITLE
ci: update CI Vagrant VM IP addresses

### PR DESCRIPTION
**Pull request by nbusseneau**
VirtualBox 6.1.28 introduced new restrictions on host-only networking: https://www.virtualbox.org/wiki/Changelog-6.1#v28
Manual: https://www.virtualbox.org/manual/ch06.html#network_hostonly

> On Linux, Mac OS X and Solaris Oracle VM VirtualBox will only allow IP addresses in 192.68.56.0/21 range to be assigned to host-only adapters. For IPv6 only link-local addresses are allowed. If other ranges are desired, they can be enabled by creating /etc/vbox/networks.conf and specifying allowed ranges there. For example, to allow 10.0.0.0/8 and 192.168.0.0/16 IPv4 ranges as well as 2001::/64 range put the following lines into /etc/vbox/networks.conf:
>
>      * 10.0.0.0/8 192.168.0.0/16
>      * 2001::/64
>
> Lines starting with the hash # are ignored. Next example allows any addresses, effectively disabling range control:
>
>      * 0.0.0.0/0 ::/0

These new restrictions manifest in the form of the following issue:

```
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp
```

when running `VBoxManage hostonlyif ipconfig` command where the IP address is outside of the allowed range, as is the case in our CI:

```
10:32:07  ==> k8s1-1.21: Clearing any previously set network interfaces...
10:32:09  There was an error while executing `VBoxManage`, a CLI used by Vagrant
10:32:09  for controlling VirtualBox. The command and stderr is shown below.
10:32:09
10:32:09  Command: ["hostonlyif", "ipconfig", "vboxnet0", "--ip", "192.168.38.1", "--netmask", "255.255.255.0"]
10:32:09
10:32:09  Stderr: VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
10:32:09  VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp
```

We update the IP addresses used by Vagrant VMs to be compatible with the new restricted range so that our VMs can still be run when using VirtualBox 6.1.28 and above, without the need for the `/etc/vbox/networks.conf` workaround above.

### CODE REVIEW

**Comment by nbusseneau** [comment]
This is a re-open of #17733, which was merged accidentally and subsequently reverted in #17898.

**Comment by nbusseneau** [comment]
Original PR hit an issue on net-next, tracked in #17897, however the re-run seems to have gotten through just fine: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/1953/

I am retriggering the CI just in case.

**Comment by nbusseneau** [comment]
Reposting comment from previous PR regarding the "IP replace pattern":

> My pattern was:
>
> - Try to do `3X` => `5X` if possible => this perfectly matches the CI Vagrant VMs IPs.
> - Start from `60` if not possible => this perfectly matches the non-CI Vagrant VMs IPs.
>
> But I can re-do it another way if we'd like, I mostly wanted to have a quick thing out to run tests ^^

**Review by pchaigno — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Review by jibi — APPROVED** [review]

**Comment by pchaigno** [comment]
The changes here mostly impact @cilium/ci-structure (test VMs) and @cilium/contributing (dev. VMs); other changes are trivial. So probably not worth waiting for all remaining review requests. Tests are also all passing. Marking ready to merge.

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
