### PR TITLE
datapath: Do not check rev_nat_id in IPv6 addr

### PR DESCRIPTION
**Pull request by brb**
The `rev_nat_id` is no longer stored in an IPv6 addr since the`--lb` feature (`bpf_lb.c`) has been deprecated and removed.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9952)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]
Looks good, but needs rebase

**Comment by brb** [comment]
test-me-please

**Comment by mrostecki** [comment]
It needs rebase again :(

**Comment by brb** [comment]
test-me-please

**Pull request merged**
