### PR TITLE
v1.14: WG L7

### PR DESCRIPTION
**Pull request by brb**
Advanced test case passed - https://github.com/cilium/cilium/actions/runs/8248439782/job/22558768872

### CODE REVIEW

**Comment by brb** [comment]
/test-backport-1.14

**Comment by brb** [comment]
/test-backport-1.14

**Comment by brb** [comment]
/test-backport-1.14

**Comment by ferozsalam** [comment]
/test-backport-1.14

**Comment by brb** [comment]
/test-backport-1.14

**Comment by brb** [comment]
/test-backport-1.14

**Comment by brb** [comment]
/test-backport-1.14

**Comment by brb** [comment]
/test-backport-1.14

**Comment by brb** [comment]
/test-backport-1.14

**Review by gandro — APPROVED** [review]

**Review by gentoo-root — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
