### PR TITLE
Misc: Log messages improvements

### PR DESCRIPTION
**Pull request by eloycoto**
- Bugtool:  running dmesg with iso date format. 
- Endpoint: fix format issue on log message.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4546)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
I had no idea there was such an option for dmesg :-)

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4206/

No logs were gathered.

Looks like the setup maybe got hosed?:

```
time="2018-06-18T19:14:42Z" level=debug msg="running command: kubectl get pods --all-namespaces -o jsonpath='{.items[*].metadata.deletionTimestamp}'"
cmd: "kubectl get pods --all-namespaces -o jsonpath='{.items[*].metadata.deletionTimestamp}'" exitCode: 1 stdout:

stderr:
Unable to connect to the server: net/http: TLS handshake timeout

time="2018-06-18T19:14:53Z" level=debug msg="running command: kubectl get pods --all-namespaces -o jsonpath='{.items[*].metadata.deletionTimestamp}'"
cmd: "kubectl get pods --all-namespaces -o jsonpath='{.items[*].metadata.deletionTimestamp}'" exitCode: 1 stdout:

stderr:
Unable to connect to the server: net/http: TLS handshake timeout

time="2018-06-18T19:15:03Z" level=debug msg="running command: kubectl get pods --all-namespaces -o jsonpath='{.items[*].metadata.deletionTimestamp}'"
cmd: "kubectl get pods --all-namespaces -o jsonpath='{.items[*].metadata.deletionTimestamp}'" exitCode: 1 stdout:

stderr:
Unable to connect to the server: net/http: TLS handshake timeout

time="2018-06-18T19:15:14Z" level=debug msg="running command: kubectl get pods --all-namespaces -o jsonpath='{.items[*].metadata.deletionTimestamp}'"
cmd: "kubectl get pods --all-namespaces -o jsonpath='{.items[*].metadata.deletionTimestamp}'" exitCode: 0 stdout:
```

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
