### PR TITLE
[v1.14] `cilium bgp routes` command backport

### PR DESCRIPTION
**Pull request by rastislavs**
This is a manual backport of the `cilium bgp routes` debug CLI implementation and its integration in the bugtool. The list of backported PRs:

- https://github.com/cilium/cilium/pull/26803
- https://github.com/cilium/cilium/pull/27182
- https://github.com/cilium/cilium/pull/30033

```release-note
bgpv1: Add bgp/routes API endpoint and cilium bgp routes CLI command & integrate it in the bugtool
```

### CODE REVIEW

**Comment by rastislavs** [comment]
/test-backport-1.14

**Review by learnitall — COMMENTED** [review]
Hey! Couple of questions for you that will help with the review:

1. Why did these PRs need to be backported manually?
2. Are there any changes that you made between these commits and their associated upstream commits?

Also just a heads up, when doing backports it is helpful for the commit messages to have a little comment that links to the upstream commit, something like:

```
message

[ upstream commit COMMIT SHA ]

extended desc
```

Thanks!

**Review by learnitall — CHANGES_REQUESTED** [review]
I went through each commit and compared it to its upstream commit.

It looks like the only one that had to be changed was 4ab06b51ce0beed2f976626431e4824d4240168a, with upstream commit 1f5224517c49604d064bfc2236d2073cb0e02a35. Can you modify commit 4ab06b51ce0beed2f976626431e4824d4240168a to contain a backporter's note explaining how you had to adjust the way the API handler was added to the daemon, since 1.14 doesn't have the API handlers cell? The format looks like this:

```
msg

[ Upstream commit COMMIT SHA ]

[ Backporter's note: NOTE ]

extended message
```

After that, and a note in each commit in the backport citing the upstream commit its based on, and we should be good to go.

Everything else looks great. The Swagger version is the same between upstream and 1.14, so nothing to really worry about there.

Thanks!

**Comment by rastislavs** [comment]
@learnitall Thanks for guidance, and sorry that you had to go through the commits without context in the commit messages. 

Commit messages are fixed now. There were actually 3 commits with non-trivial changes due to which this had to be backported manually (although the rest 2 were not easy to spot) - now it's all documented in the backporter's notes:
-  https://github.com/cilium/cilium/pull/30205/commits/018c69d78335a0f979e3daf0a9d5b167ca6f587e - as you noticed already, this is the largest one
- https://github.com/cilium/cilium/pull/30205/commits/5bd7e768a4bf56e0fa57fb9efd53d51e4f3a3b71 - similar reason
- https://github.com/cilium/cilium/pull/30205/commits/2b7bf5f5c72aa6a730e945504c0295ef01c5448a - due to bgp code refactoring in upstream

**Comment by rastislavs** [comment]
/test-backport-1.14

**Comment by learnitall** [comment]
No problem! Thank you for taking care of adding the extra context in the commit messages. My apologies for missing those other two.

**Review by learnitall — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
ConformanceEKS: https://github.com/cilium/cilium/issues/29987

**Pull request merged**
