### PR TITLE
v1.3 Backport 19 03 20

### PR DESCRIPTION
**Pull request by jrfastab**
PR:
 * #7428 
 * #7409 
 * #7394 

Note: PRs 7409 and 7394 had a set of conflicts.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7455)

### CODE REVIEW

**Review by aanm — APPROVED** [review]
All good from my backported commits

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by jrfastab** [comment]
failed Policy Test, https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10971/ will retry

**Comment by jrfastab** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-docs-please

**Pull request merged**
