### PR TITLE
envoy: Rebase to get IP_TRANSPARENT support.

### PR DESCRIPTION
**Pull request by jrajahalme**
integration test still need some work, but it is not run by the CI.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

### CODE REVIEW

**Review by rlenglet — APPROVED** [review]

**Comment by jrajahalme** [comment]
test-me-please

**Comment by rlenglet** [comment]
@jrajahalme C++ compilation error in Envoy / Bazel:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/1835/
```
00:36:11     runtime: ERROR: /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy/source/server/BUILD:192:1: C++ compilation of rule '@envoy//source/server:listener_manager_lib' failed (Exit 1)
00:36:11     runtime: external/envoy/source/server/listener_manager_impl.cc: In constructor 'Envoy::Server::ListenerImpl::ListenerImpl(const envoy::api::v2::Listener&, Envoy::Server::ListenerManagerImpl&, const string&, bool, bool, uint64_t)':
00:36:11     runtime: external/envoy/source/server/listener_manager_impl.cc:117:86: error: '*((void*)& iftmp.771 +1)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
00:36:11     runtime:              PROTOBUF_GET_WRAPPED_OR_DEFAULT(config, freebind, absl::optional<bool>{})) {}
00:36:11     runtime:                                                                                       ^
00:36:11     runtime: external/envoy/source/server/listener_manager_impl.cc:117:86: error: '*((void*)& iftmp.770 +1)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
00:36:11     runtime: external/envoy/source/server/listener_manager_impl.cc:117:86: error: '*((void*)& iftmp.770 +1)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
```

Weird, I've not seen this error until now.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by jrajahalme** [comment]
I don't see the compilation error locally, maybe there are some compiler differences that need to be circumvented. But that seems like a fix that needs to be done on Envoy.

**Comment by rlenglet** [comment]
> I don't see the compilation error locally, maybe there are some compiler differences that need to be circumvented. But that seems like a fix that needs to be done on Envoy.

Hard to fix, since this is the first time I've ever seen this compilation error.

**Comment by rlenglet** [comment]
Same C++ compilation error:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/1839/execution/node/58/log/
```
01:25:13     runtime: ERROR: /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy/source/server/BUILD:192:1: C++ compilation of rule '@envoy//source/server:listener_manager_lib' failed (Exit 1)
01:25:13     runtime: external/envoy/source/server/listener_manager_impl.cc: In constructor 'Envoy::Server::ListenerImpl::ListenerImpl(const envoy::api::v2::Listener&, Envoy::Server::ListenerManagerImpl&, const string&, bool, bool, uint64_t)':
01:25:13     runtime: external/envoy/source/server/listener_manager_impl.cc:117:86: error: '*((void*)& iftmp.771 +1)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
01:25:13     runtime:              PROTOBUF_GET_WRAPPED_OR_DEFAULT(config, freebind, absl::optional<bool>{})) {}
01:25:13     runtime:                                                                                       ^
01:25:13     runtime: external/envoy/source/server/listener_manager_impl.cc:117:86: error: '*((void*)& iftmp.770 +1)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
01:25:13     runtime: external/envoy/source/server/listener_manager_impl.cc:117:86: error: '*((void*)& iftmp.770 +1)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
```

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Same C++ compilation error again:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/1841/execution/node/58/log/
```
02:08:52     runtime: ERROR: /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy/source/server/BUILD:192:1: C++ compilation of rule '@envoy//source/server:listener_manager_lib' failed (Exit 1)
02:08:52     runtime: external/envoy/source/server/listener_manager_impl.cc: In constructor 'Envoy::Server::ListenerImpl::ListenerImpl(const envoy::api::v2::Listener&, Envoy::Server::ListenerManagerImpl&, const string&, bool, bool, uint64_t)':
02:08:52     runtime: external/envoy/source/server/listener_manager_impl.cc:117:86: error: '*((void*)& iftmp.771 +1)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
02:08:52     runtime:              PROTOBUF_GET_WRAPPED_OR_DEFAULT(config, freebind, absl::optional<bool>{})) {}
02:08:52     runtime:                                                                                       ^
02:08:52     runtime: external/envoy/source/server/listener_manager_impl.cc:117:86: error: '*((void*)& iftmp.770 +1)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
02:08:52     runtime: external/envoy/source/server/listener_manager_impl.cc:117:86: error: '*((void*)& iftmp.770 +1)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
```

This is definitely not a fluke.
We need to look into differences in C++ compiler version etc.
This build doesn't fail on a Vagrant dev VM, where both clang++ 3.8.1 and g++ 7.2.0 are installed:
```
$ clang++ --version
clang version 3.8.1 (tags/RELEASE_381/final)

$ g++ --version
g++ (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0
```
(and I'm not sure which compiler is used by Bazel).

It doesn't fail either on a bare metal Ubuntu Xenial box with g++ 5.4.0 installed:
```
# g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
```

This log line containing `cc1plus` suggests that it's a version of g++ that is used by Bazel to compile C++ in the CI:
```
02:08:52     runtime: cc1plus: all warnings being treated as errors
```
It's not clear what version this is.

**Comment by rlenglet** [comment]
Note that Envoy requires either clang 5.0:
https://github.com/envoyproxy/envoy/blob/ed02aaea58e71051eda2a70a1a071bfa4aef1cb6/ci/build_container/build_container_ubuntu.sh#L13
or g++ 5.4.0:
https://github.com/envoyproxy/envoy/blob/ed02aaea58e71051eda2a70a1a071bfa4aef1cb6/ci/build_container/build_container_ubuntu.sh#L25
depending on the target.
The release builds are compiled using g++ 5.4.0.

We install g++ 7.2.0 in our Vagrant VM, and that is probably the root cause of this failure.

**Comment by rlenglet** [comment]
That still doesn't explain why it's failing in CI builds and not in a dev Vagrant VM.

**Review by rlenglet — APPROVED** [review]

**Comment by jrajahalme** [comment]
@rlenglet maybe updating CI box to have this file cached would get around the problem?

**Comment by rlenglet** [comment]
@jrajahalme hmmm I'm not super optimistic. I bet changing the g++ version will lead to the cache getting ignored. I bet we can't use a cache compiled with g++ 5.4.0 and compile and link on top with g++ 7.2.0.

**Comment by jrajahalme** [comment]
I don't think it's GCC 7.2.0 as I'm compiling with that locally all the time. It's possible that packer-ci-build succeeds with GCC 7.2.0 and that the CI could then proceed fine.

**Comment by rlenglet** [comment]
OK, then it's worth trying!

**Comment by jrajahalme** [comment]
I spotted another issue that *might* have an effect. The option is created with `make_unique` while it is consumed as `shared_ptr` as the function parameter type. Not sure how that should really work out, but I'm prepping an Envoy PR to change this `make_unique` to `make_shared` instead.

**Comment by jrajahalme** [comment]
IMO we are being hit by this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80635

Tried to make a new cilium-image-builder and it fails also for `error: '*((void*)& iftmp.773 +1)' may be used uninitialized in this function [-Werror=maybe-uninitialized]`

Seems like we need to surround the affected code by #pragma's that suppress the warning (that is being treated as an error). I did not find instances of such pragma's in Envoy's code so far, so not sure how enthusiastic they are to take such #pragma's in.

**Comment by jrajahalme** [comment]
I'm experimenting with using GCC 5 instead.

**Comment by jrajahalme** [comment]
Ubuntu 17.10 has buggy GCC 5: https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1725848
This causes compile errors in Envoy dependencies, which makes using Ubuntu-provided GCC 5.4 (on 17.10 which we currently use) not work. I'll explore getting around the problem in upstream Envoy instead.

Apparently the upstream bug causing the build break is fixed, but Ubuntu has not re-built gcc-5 package with the fixed libstdc++.

**Comment by rlenglet** [comment]
FYI I upgrade Envoy in https://github.com/cilium/cilium/pull/3035 and I fix the g++ 7.2 compilation issue as well.

**Comment by jrajahalme** [comment]
Fixed via #3853

**Pull request closed without merging**
