### PR TITLE
Update Go to 1.18.5

### PR DESCRIPTION
**Pull request by tklauser**
This includes various security fixes, see
https://go.dev/doc/devel/release#go1.18.5 for details.

### CODE REVIEW

**Review by nbusseneau — APPROVED** [review]

**Review by jibi — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by tklauser** [comment]
/test-1.23-4.19

**Comment by tklauser** [comment]
/test-1.23-4.19

**Pull request merged**
