### PR TITLE
v1.13 Backports 2023-07-24

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #25038 (@pchaigno)
 * [x] #26808 (@pchaigno)
 * [x] #26933 (@nbusseneau)
 * [x] #26884 (@julianwiedmann)
 * [x] #26719 (@christarazi)
 * [x] #26934 (@michi-covalent)
 * [x] #26979 (@pchaigno)
 * [x] #26912 (@giorio94)

PRs skipped due to conflicts:

 * #26455 (@alan-kut)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 25038 26808 26933 26884 26719 26934 26979 26912; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=25038,26808,26933,26884,26719,26934,26979,26912
```

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]
💕

**Comment by nbusseneau** [comment]
@julianwiedmann @giorio94 Please see backporter's notes for your commits, had conflicts to resolve.

**Comment by nbusseneau** [comment]
/test-backport-1.13

**Review by julianwiedmann — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
My changes look good. Thanks Nicolas!

**Review by giorio94 — APPROVED** [review]
My commit looks good. Thanks!

**Review by gandro — APPROVED** [review]

**Comment by nbusseneau** [comment]
- 1.23 / 4.19 hit #25403.
- Runtime hit #26183.

Re-running both out of caution.

**Comment by nbusseneau** [comment]
/test-1.23-4.19

**Review by nathanjsweet — APPROVED** [review]

**Comment by nbusseneau** [comment]
All testing has passed and reviews are in, marking `ready-to-merge`.

**Review by youngnick — APPROVED** [review]

**Pull request merged**
