### PR TITLE
vagrant: bump net-next vagrant image

### PR DESCRIPTION
**Pull request by joestringer**
Each builds contains:

- Bump of cached Istio container images

net-next build also contains latest bpf tree on track for 5.7:

- Fixes for BPF TPROXY

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]

**Comment by borkmann** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Comment by joestringer** [comment]
Provisioning failure.

**Comment by joestringer** [comment]
restart-ginkgo

**Comment by joestringer** [comment]
Hit provisioning issues, in part because it's spending time pulling istio v1.5.1 container images. I've pinged @jrajahalme to add these into the dev VM, will wait on that.

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18647/execution/node/122/log/

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
@nebril I haven't updated the `@v419_SERVER_VERSION` as I didn't see a jenkins target that I could trigger to generate a new image. Is this documented somewhere?

**Comment by joestringer** [comment]
Just one failure, apparently the regular box got rid of `yamllint` and the runtime tests depend on it.

**Comment by joestringer** [comment]
PR https://github.com/cilium/cilium/pull/10952 should allow us to just rebase and merge the existing VMs without having to go and generate the box images again just to pick up yamllint.

**Comment by joestringer** [comment]
test-me-please

**Pull request merged**
