### PR TITLE
Fix node ip script path

### PR DESCRIPTION
**Pull request by nebril**
This change will cause images to not be built during k8s vm provisioning

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-focus K8sDemos.*

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-focus K8sDemos.*

**Pull request merged**
