### PR TITLE
1.2 backports 2018-11-06

### PR DESCRIPTION
**Pull request by nebril**
#6150
#6145
#6136
#6132
#6079
#6074
#5760

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6188)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
LGTM for my commits

**Comment by nebril** [comment]
test-me-please

**Comment by aanm** [comment]
https://covalentio.atlassian.net/browse/COV-2798?oldIssueView=true

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-missed-k8s

**Review by raybejjani — APPROVED** [review]

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-upstream-k8s

**Pull request merged**
