### PR TITLE
Dockerfile: use patched proxy image.

### PR DESCRIPTION
**Pull request by jrajahalme**
```release-note
<!-- Enter the release note text here if needed -->
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9338)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Found "JoinEP: " in logs failed one test (https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/15278/testReport/junit/(root)/Suite-runtime/RuntimePolicies_L3_L4_Checks/), seems unrelated so running again.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
