### PR TITLE
v1.6 backports 2019-08-12

### PR DESCRIPTION
**Pull request by ianvernon**
* #8847 -- doc: Fix some typos in the portmap chaining guide (@tgraf)
 * #8861 -- helm: fix host reachable services template for cilium config map (@borkmann)
 * #8837 -- Fix DNS egress L7 policy in ENI mode (@joestringer)
 * #8868 -- encryption: fix encryption when using ip pools (@lbernail)
 * #8871 -- doc: Fix cosmetic problem of two helm blocks in guides (@tgraf)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 8847 8861 8837 8868 8871; do contrib/backporting/set-labels.py $pr done 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8876)

### CODE REVIEW

**Comment by ianvernon** [comment]
never-tell-me-the-odds

**Review by joestringer — APPROVED** [review]
:shipit:

**Comment by ianvernon** [comment]
K8s upstream tests failed:
```
10:00:00  The guest machine entered an invalid state while waiting for it
10:00:00  to boot. Valid states are 'starting, running'. The machine is in the
10:00:00  'paused' state. Please verify everything is configured
10:00:00  properly and try again.
10:00:00  
10:00:00  If the provider you're using has a GUI that comes with it,
10:00:00  it is often helpful to open that and watch the machine, since the
10:00:00  GUI often has more helpful error messages than Vagrant can retrieve.
10:00:00  For example, if you're using VirtualBox, run `vagrant up` while the
10:00:00  VirtualBox GUI is open.
10:00:00  
10:00:00  The primary issue for this error is that the provider you're using
10:00:00  is not properly configured. This is very rarely a Vagrant issue.
```

re-running.

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
K8s upstream tests failed again: https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/1431/

Failure to fetch from GitHub: 

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/cilium/cilium
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:894)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1161)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14244/

Hit issue which will be fixed by https://github.com/cilium/cilium/pull/8855 .

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14251/

Could not check out from version control:

```
using credential ciliumbot
Cloning the remote Git repository
Using shallow clone
Using shallow clone
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:813)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:605)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to jenkins-fixed-new-0
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:957)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
		at sun.reflect.GeneratedMethodAccessor849.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
		at com.sun.proxy.$Proxy94.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1152)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		... 4 more
```

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
