### PR TITLE
v1.15 Backports 2024-01-16

### PR DESCRIPTION
**Pull request by gandro**
* [x] #30009 (@ti-mo)
 * [ ] #30233 (@jrajahalme)
 * [x] #30211 (@qmonnet)
 * [x] #30107 (@mhofstetter)
 * [ ] #29963 (@joamaki)
 * [ ] #29902 (@joestringer)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30009 30233 30211 30107 29963 29902
```

### CODE REVIEW

**Comment by gandro** [comment]
/test-backport-1.15

**Review by qmonnet — APPROVED** [review]
Backport for my commit looks good, thanks Sebastian!

**Review by tklauser — APPROVED** [review]

**Review by mhofstetter — APPROVED** [review]
My commit looks good. Thanks!

**Review by ti-mo — APPROVED** [review]
Thanks!

**Review by aanm — APPROVED** [review]
I'll merge it since I'm preparing an RC for the v1.15. Thanks for the PR Sebastian!

**Pull request merged**
