### PR TITLE
Revert "dnsproxy: Use original source address in connections to dns servers"

### PR DESCRIPTION
**Pull request by thorn3r**
Revert "dnsproxy: Use original source address in connections to dns servers"

This reverts commit 277037fd1d52a0a8cb6e4346c7840fb4cf1d4cf4.

This change was reverted in main at 4dc8ca2.

Since this was an author backport and required special care, I'm reverting the commit in the branch rather than backporting.

[upstream commit 4dc8ca2 ]

Fixes: #29175

```release-note
Revert "dnsproxy: Use original source address in connections to dns servers" to fix performance regression.
```

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by thorn3r** [comment]
/test-backport-1.14

**Review by julianwiedmann — APPROVED** [review]

**Comment by sergeyshevch** [comment]
@thorn3r Is it possible to edit 1.14.4 release description on github to include this bug. It was really bad experience to get 5 cores cpu consumption on production after upgrade to 1.14.4

**Comment by thorn3r** [comment]
Hey @sergeyshevch, sorry to hear about your troubles with that regression in v1.14.4. We don't typically update previous release notes, but the fix is called out in the [v1.14.5 release notes](https://github.com/cilium/cilium/releases/tag/v1.14.5) under `Other Changes`. This should have been listed under `Bugfixes` instead, but that is a side-effect of this one not following the standard backporting procedure

**Pull request merged**
