### PR TITLE
vagrant: update Vagrantfiles to use vm v97

### PR DESCRIPTION
**Pull request by ianvernon**
This VM image is built with Ubuntu 18.04 LTS as a base.

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4766)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Due to issues with the `cilium/ubuntu-dev` image that got pushed to S3, we need to rebuild the VM. But, CI has passed using 18.04 LTS :)

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Testing the provisioning of the VMs used by developers (with `./contrib/vagrant/start.sh`) manually on my local setup, will confirm that it functions without issue.

**Comment by ianvernon** [comment]
Provisioning the developer VMs locally with this PR's branch with the following commands succeeded:

* `NFS=1 ./contrib/vagrant/start.sh`
* `K8S=1 NFS=1 ./contrib/vagrant/start.sh`

**Comment by ianvernon** [comment]
I'm somewhat wary about the backporting of this change, because we build Envoy based off of latest Cilium master, and I'm unsure how that will impact past branches.

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
I don't think we need to backport

**Comment by joestringer** [comment]
Branches 1.0 and 1.1 will start failing soon if we don't come up with new 18.04-based images for them.

**Comment by ianvernon** [comment]
@joestringer is correct; we will have to create commits specifically for those branches with VM images based off of the head of the each branch for building Envoy.

**Comment by tgraf** [comment]
> because we build Envoy based off of latest Cilium master, and I'm unsure how that will impact past branches

> Branches 1.0 and 1.1 will start failing soon if we don't come up with new 18.04-based images for them.

I'm a bit lost, why does this affect 1.0 and 1.1 branches? They should have a different vagrant box version encoded.

**Comment by ianvernon** [comment]
If we try to do any type of update via apt in those boxes, it’ll fail because 17.10 will be EOL’d. IMO it’s better to be proactive with things like that so we don’t get bitten by it if we need to do an urgent backport.

**Comment by tgraf** [comment]
Thanks for the clarification. Can we avoid requiring apt-get instead then? Backporting the box has serious consequences in how we build Envoy as we will use a build cache that is too new.

**Comment by ianvernon** [comment]
>  Can we avoid requiring apt-get instead then? 

If we want to avoid using apt-get, we'd have to package versions of K8s into the VMs directly. Currently, we install K8s using apt-get:

https://github.com/cilium/cilium/blob/e261cd16b5139ce422cb65a780f32689bd2bbe1d/test/provision/k8s_install.sh#L128-L141

https://github.com/cilium/cilium/blob/e261cd16b5139ce422cb65a780f32689bd2bbe1d/test/provision/helpers.bash#L40-L48

However, in the same `helpers.bash` file, I see that instead of using apt, we can download the binary directly:

https://github.com/cilium/cilium/blob/e261cd16b5139ce422cb65a780f32689bd2bbe1d/test/provision/helpers.bash#L50-L69

TL;DR: currently, installing K8s requires apt per the provisioning scripts, but we could possibly avoid using apt all together to avoid EOL issues by acquiring the binaries directly. This would require some exploration, though. Would you like me to file an issue for this?

> Backporting the box has serious consequences in how we build Envoy as we will use a build cache that is too new.

@tgraf we can build a version of the VM per release branch. It is possible to build a version of the box with the latest changes to the box (i.e., Ubuntu 18.04 LTS as a base), but have the building of that box check out the release branch and build Envoy / populate the Bazel cache against the version of the release branch by providing an argument to the build pipeline for the cilium branch (e.g., v1.0, v1.1, etc.). Instead of backporting the box, we would open up PRs against the branches themselves directly. The likelihood of merge conflicts is next to none because all we'd ideally be doing is changing a single line in the Vagrantfiles (the box version). 

So, we have a variety of options at our disposal.

**Pull request merged**
