### PR TITLE
loader: remove hash from compileQueue if build fails

### PR DESCRIPTION
**Pull request by ianvernon**
Otherwise, the loader erroneously thinks that the template has been built,
while it actually needs to be rebuilt again.

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9186)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
@joestringer PTAL - I think this is only half of the solution. The problem is that multiple things will wait on the same function queue, and then they'll fail because the template wasn't actually compiled. Subsequent regenerations would have to take care of that - we have no way of signaling to other waiters on the queue that the compilation failed.

**Review by joestringer — APPROVED** [review]
Right, if you trace the `ep.Regenerate()` calls up, we basically just don't handle failures at all.

There should probably be some kind of retry logic / controller / something that re-attempts regeneration in that case.

That said, this change is also necessary and looks correct to me.

**Pull request merged**
