### PR TITLE
envoy: Update to Envoy 1.27.0, drop privileges

### PR DESCRIPTION
**Pull request by jrajahalme**
Use `cilium-envoy-starter` image that runs `cilium-envoy` process without any privileges. `cilium-envoy-starter` retains privileges to be able to integrate with Cilium BPF datapath.

Review notes:
- 1st commit is an update of generated Go API files with no functional changes in the features used by Cilium

```release-note
Update to Envoy 1.27.0, run cilium-envoy process without any privileges.
```

### CODE REVIEW

**Review by rolinh — APPROVED** [review]
Vendor changes lgtm

**Review by kaworu — APPROVED** [review]
Helm changes LGTM

**Comment by jrajahalme** [comment]
Unrelated flake in Travis CI, restarted

**Review by mhofstetter — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
