### PR TITLE
[v1.12] Author Backport of 28382 (Metrics associated with a deleted node should not be reported)

### PR DESCRIPTION
**Pull request by derailed**
- [ ] #28382 -- Metrics associated with a deleted node should not be reported (@derailed)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 28382; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Comment by derailed** [comment]
/test-backport-1.12

**Review by christarazi — APPROVED** [review]

**Comment by christarazi** [comment]
/test-backport-1.12

**Comment by derailed** [comment]
/test-backport-1.12

**Comment by derailed** [comment]
/test-backport-1.12

**Comment by christarazi** [comment]
The runtime tests all failed which might either suggest a VM provisioning failure or something in the privileged unit test suite is broken from changes in this PR.

**Review by squeed — APPROVED** [review]

**Comment by christarazi** [comment]
/test-1.16-4.9

**Comment by christarazi** [comment]
test-runtime

**Comment by christarazi** [comment]
//test-1.16-4.9

**Comment by christarazi** [comment]
/test-1.16-4.9

**Pull request merged**
