### PR TITLE
fix: hubble exporter filter test with clashing filters

### PR DESCRIPTION
**Pull request by rectified95**
Fixes bug in test where a flow matching both the white- and blacklist was not getting filtered out.
Fix suggested by @chancez and @glibsm

### CODE REVIEW

**Review by chancez — CHANGES_REQUESTED** [review]
Can you update the other events in the list to also use the source endpoint field?

**Review by chancez — APPROVED** [review]

**Review by chancez — CHANGES_REQUESTED** [review]
Sorry, actually I think the test cases are now a bit confusing as to what is expected to be returned since now only one of the `allow-pods` is being returned. Perhaps we should change the `namespace: "allow-pod"` so that it's not so confusing? It could be more arbitrary just like "namespace-a" and "namespace-b" and then update the filters to pick one of them and edit the results as expected.

**Comment by rectified95** [comment]
> Sorry, actually I think the test cases are now a bit confusing as to what is expected to be returned since now only one of the `allow-pods` is being returned. Perhaps we should change the `namespace: "allow-pod"` so that it's not so confusing? It could be more arbitrary just like "namespace-a" and "namespace-b" and then update the filters to pick one of them and edit the results as expected.

For sure, the namespaces we now filter on are called `namespace-a` and `namespace-b`. I added comments on each test case explaining the filtering behavior for clarity.

**Review by chancez — APPROVED** [review]

**Comment by rectified95** [comment]
@rolinh Mind taking a quick look? :)

**Review by rolinh — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
