### PR TITLE
ci: add gke cluster name to build name

### PR DESCRIPTION
**Pull request by nebril**

### CODE REVIEW

**Comment by nebril** [comment]
test-gke K8sDemos.*

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Review by errordeveloper — APPROVED** [review]

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
retest-net-next

**Comment by nebril** [comment]
retest-runtime

**Comment by nebril** [comment]
retest-4.9

**Comment by nebril** [comment]
restart-ginkgo

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-upstream-k8s

**Pull request merged**
