### PR TITLE
policy: Fix proxy listener and priority with auth rules

### PR DESCRIPTION
**Pull request by jrajahalme**
Properly inherit listener name and priority from the L3-wildcard rule to L3 rule when auth types are different between them.

Fixes: #26331

```release-note
Policy properly propagates proxy listener name and priority from a L3 wildcard rule with policies requiring authentication.
```

### CODE REVIEW

**Review by doniacld — APPROVED** [review]
Lgtm!

**Review by derailed — APPROVED** [review]
@jrajahalme Nice catch!

**Review by squeed — APPROVED** [review]

**Pull request merged**
