### PR TITLE
workflows: add external workload conformance test

### PR DESCRIPTION
**Pull request by nbusseneau**
This was ported and adapted from `cilium-cli`.

### CODE REVIEW

**Comment by nebril** [comment]
looks like clustermesh apiserver pod is in crash loop backoff, but it's a different issue that we had in CLI repo (apiserver is managed by Cilium). investigating.

**Comment by nebril** [comment]
looks like we are using cilium sha tag to download clustermesh image, which is not available due to being in different repo

**Comment by nebril** [comment]
we are currently hitting the same failure as https://github.com/cilium/cilium-cli/pull/358

**Comment by nbusseneau** [comment]
Closing in favor of #16789.

**Pull request closed without merging**
