### PR TITLE
v1.16 Backports 2024-11-05

### PR DESCRIPTION
**Pull request by joamaki**
* [ ] #35351 (@learnitall)
 * [ ] #35143 (@jrajahalme) :warning: resolved conflicts
 * [x] #35561 (@michi-covalent)
 * [ ] #35551 (@borkmann)
 * [x] #35589 (@bimmlerd)
 * [x] #35552 (@harsimran-pabla)
 * [x] #35591 (@julianwiedmann)
 * [ ] #35623 (@mhofstetter)
 * [ ] #35415 (@kaworu)
 * [x] #35632 (@chancez)
 * [x] #35657 (@rastislavs) :warning: resolved conflicts
 * [ ] #35498 (@akaliwod)
 * [x] #35599 (@squeed) :warning: resolved conflicts
 * [ ] #35669 (@borkmann)
 * [x] #35630 (@chancez) :warning: resolved conflicts
 * [x] #35673 (@giorio94)
 * [ ] #35674 (@ayuspin)
 * [ ] #35703 (@solidDoWant)
 * [ ] #35725 (@nvibert)
 * [x] #35738 (@gandro)
 * [x] #35626 (@pchaigno)
 * [ ] #35736 (@jrajahalme)
 * [x] #35747 (@pchaigno)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 35351 35143 35561 35551 35589 35552 35591 35623 35415 35632 35657 35498 35599 35669 35630 35673 35674 35703 35725 35738 35626 35736 35747
```

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
My commits look good, thanks!

**Review by rastislavs — APPROVED** [review]

**Review by squeed — APPROVED** [review]

**Review by harsimran-pabla — APPROVED** [review]

**Comment by joamaki** [comment]
/test-backport-1.16

**Review by pchaigno — APPROVED** [review]

**Review by bimmlerd — APPROVED** [review]
Thanks!

**Review by michi-covalent — APPROVED** [review]
🥰

**Review by chancez — APPROVED** [review]

**Comment by pchaigno** [comment]
The K8SUpdates failure in ginkgo tests seems likely to be related to https://github.com/cilium/cilium/issues/35594.

**Pull request merged**
