### PR TITLE
v1.14 backports 2023-10-24

### PR DESCRIPTION
**Pull request by tklauser**
- [ ] #27229 -- spire: add scheduling configurations to helm-chart (@tvonhacht-apple)
 - [x] #28391 -- bpf: lxc: remove stale ENABLE_IDENTITY_MARK ifdefs (@julianwiedmann)
   - :warning: Minor conflict, kept SECLABEL instead of SECLABEL_IPV4 and SECLABEL_IPV6 as used on `main`
 - [x] #28425 -- Print full labelset for all identities in 'cilium ip list' output (@joestringer)
 - [x] #26798 -- docs: update clustermesh troubleshooting guide (@giorio94)
   - :warning: Minor conflict in context, kept version from the PR.
 - [x] #28141 -- docs: Update IPsec key rotation command (@jschwinger233)
 - [x] #28481 -- helm: don't expose kvstoremesh metrics if not enabled (@giorio94)
 - [x] #28633 -- Fix IPv6 cilium_host address assignment (@CallMeFoxie)
 - [x] #28610 -- helm: Correct spire labels indentation (@sayboras)
 - [x] #28676 -- install: Remove AWS-CONNMARK-CHAIN iptable rules (@nebril)
 - [x] #28682 -- docs: Clarify BPF Map Pressure Metric (@nathanjsweet)
   - :warning: Minor conflict in context, kept version from the PR.
 - [x] #28400 -- ipsec: New Prometheus metrics for XFRM configs (@pchaigno)
 - [ ] #28638 -- fixed cilium-operator delete CEC cilium-ingress when other ingressclass resources are created (@chaunceyjiang)
 - [x] #28703 -- policy: Fix Unspecified Protocol Type (@nathanjsweet)
 - [x] #28640 -- cmd: Display decryption interfaces in encrypt status (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 27229 28391 28425 26798 28141 28481 28633 28610 28676 28682 28400 28638 28703 28640; do contrib/backporting/set-labels.py $pr done 1.14; done
```

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.14

**Review by pchaigno — APPROVED** [review]
My PRs look good. Thanks Tobias!

**Review by sayboras — APPROVED** [review]
My commit looks good, thanks 👍

**Review by giorio94 — APPROVED** [review]
My commits look good. Thanks!

**Review by jschwinger233 — APPROVED** [review]
Mine looks good, thanks!

**Review by nathanjsweet — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by CallMeFoxie** [comment]
My commit looks good as well, thanks :)

**Review by julianwiedmann — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]

**Pull request merged**
