### PR TITLE
ipmasq: Stop and wait until goroutine is finished in unit tests

### LINKED ISSUE #11373: CI: Travis: panic: close of closed channel in (*IPMasqAgent).Start
Seen in PR #11368 posted 3 hours ago:
https://travis-ci.com/github/cilium/cilium/jobs/328758821

```
=== RUN   Test
panic: close of closed channel
goroutine 27 [running]:
github.com/cilium/cilium/pkg/ipmasq.(*IPMasqAgent).Start.func1(0xc000032af0)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipmasq/ipmasq.go:146 +0x368
created by github.com/cilium/cilium/pkg/ipmasq.(*IPMasqAgent).Start
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipmasq/ipmasq.go:124 +0x3cb
FAIL	github.com/cilium/cilium/pkg/ipmasq	0.350s
FAIL
Makefile:151: recipe for target 'unit-tests' failed
make: *** [unit-tests] Error 1
The command "./.travis/build.sh" exited with 2.
```

I'm not sure whether this is with or without PR https://github.com/cilium/cilium/pull/11317

### PR DESCRIPTION
**Pull request by brb**
Otherwise, a previous ipmasq agent goroutine which has been asked to
terminate (via `a.close(stop)`) might close the `handlerFinished`
channel of a new goroutine's (it's read by ref) which will result in
panic once the new ip-masq-agent is issued to stop:

    goroutine 14 [running]:

    github.com/cilium/cilium/pkg/ipmasq.(*IPMasqAgent).Start.func1(0xc000100aa0)

	    /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipmasq/ipmasq.go:146 +0x368

    created by github.com/cilium/cilium/pkg/ipmasq.(*IPMasqAgent).Start

	    /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipmasq/ipmasq.go:124 +0x3cb

    FAIL	github.com/cilium/cilium/pkg/ipmasq	0.340s

Fixes: acaa1d15ee ("ipmasq: Use fsnotify instead of periodic polling")
Fix #11373

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
@brb please add a new CODEOWNERS entry for `pkg/ipmasq`

**Comment by brb** [comment]
CI hit #8945 flake.

**Comment by brb** [comment]
test-me-please

**Pull request merged**
