### PR TITLE
cni: Change default configuration filename to 05-cilium.conf

### PR DESCRIPTION
**Pull request by aanm**
By having "00-cilium.conf" as default users have experienced issues
while trying to overwrite the default configuration file.

To ease those deployments the default configuration name of Cilium
CNI is switched to "05-cilium.conf" this will allow users to
overwrite with their 00-cilium.conf configuration while Cilium can be
deployed on systems that previously ran other CNI plugins.

Signed-off-by: André Martins <andre@cilium.io>

Fixes: https://github.com/cilium/cilium/issues/5190

```release-note
Switch default CNI configuration filename to "05-cilium.conf"
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5191)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Comment by raybejjani** [comment]
Didn't we start using 00- (instead of 01-) to ease deployments? Doesn't this just make that older problem reappear, to fix this one?

**Comment by tgraf** [comment]
> Didn't we start using 00- (instead of 01-) to ease deployments? Doesn't this just make that older problem reappear, to fix this one?

See issue for details, tl;dr: We used to have 10- which causes problems, 00- gives no chance to overwrite to add hostPort mappins, 05- is the middle ground.

**Pull request merged**
