### PR TITLE
[1.14] ci: Add IPsec leak detection for ci-ipsec-e2e

### PR DESCRIPTION
**Pull request by jschwinger233**
- [ ] https://github.com/cilium/cilium/pull/32930 @jschwinger233 

```upstream-prs
 32930
```

### CODE REVIEW

**Comment by jschwinger233** [comment]
/test-backport-1.14

**Review by julianwiedmann — APPROVED** [review]
lgtm, thank you!

**Review by viktor-kurchenko — APPROVED** [review]
LGTM, Thanks!

**Review by dylandreimerink — APPROVED** [review]

**Pull request merged**
