### PR TITLE
Metrics: Add services metrics

### PR DESCRIPTION
**Pull request by eloycoto**
Added a new metric related with the number of services that Cilium
create/update/delete by time.

Related to #5382

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5580)

### CODE REVIEW

**Review by ianvernon — APPROVED** [review]

**Review by tgraf — CHANGES_REQUESTED** [review]
I wonder if we should make this more generic and introduce a k8s_events_received with two axis of labels:
- resource name
- action type { add | update | delete }

**Comment by eloycoto** [comment]
Hi @tgraf 

There is another issue to add kubernetes events on that, but this is a only for services. 

The issue is, a service cannot finish on loadbalancer, (Headless) and it can fail, this is only the service data.

**Comment by eloycoto** [comment]
test-me-please

**Comment by tgraf** [comment]
> There is another issue to add kubernetes events on that, but this is a only for services.
> 
> The issue is, a service cannot finish on loadbalancer, (Headless) and it can fail, this is only the service data.

OK, understood. Please rename the metric to `service_events_total` so it's clear that this is the total number of events received. With the current naming, I would interpret it as the number of currently implemented services.

**Comment by eloycoto** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by vadorovsky — APPROVED** [review]
LGTM, just needs rebase :)

**Comment by eloycoto** [comment]
test-me-please

14:37:49 /bin/sh: 1: docker-compose: not found

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
