### PR TITLE
Update Go to 1.20

### PR DESCRIPTION
**Pull request by tklauser**
Release notes: https://go.dev/doc/go1.20

Note: inline static init is disabled for now (`-gcflags=-d=inlstaticinit=0`) because it breaks the build for some of our tests. See https://go.dev/issue/58293 for details.

Note: the cilium-runtime and cilium-builder images will be update separately by @renovatebot.

### CODE REVIEW

**Comment by tklauser** [comment]
> Note: the cilium-runtime and cilium-builder images will be update separately by @renovatebot.

Converting this PR to draft until the @renovatebot image update PRs get created merged, this will fix the CI image builds in this PR.

**Comment by tklauser** [comment]
Currently also blocked by https://github.com/golang/go/issues/58293, so we probably need to wait for Go 1.20.x to be released with a fix.

**Review by ldelossa — APPROVED** [review]

**Comment by tklauser** [comment]
Closing in favor of #23896

**Pull request closed without merging**
