### PR TITLE
contrib/vagrant: fix reading VM_MEMORY/VM_CPUS from env vars

### PR DESCRIPTION
**Pull request by rolinh**
According to the Vagrantfile, environment variables to set VM memory and CPU count are VM_MEMORY and VM_CPUS respectively. This change fixes picking up VM CPU and memory settings when set via environment variables.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9945)

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Review by vadorovsky — CHANGES_REQUESTED** [review]
Looks good, but an update in documentation is needed:

https://github.com/cilium/cilium/blob/master/Documentation/contributing/testing/e2e.rst#vms-for-testing

**Comment by Rolinh** [comment]
> Looks good, but an update in documentation is needed:

Nice catch! Note that with a quick grep, I also found other references to `MEMORY` and `CPUS`, notably in the various `*.Jenkinsfile`. Shall these be adjusted as well?

**Comment by mrostecki** [comment]
> > Looks good, but an update in documentation is needed:
> 
> Nice catch! Note that with a quick grep, I also found other references to `MEMORY` and `CPUS`, notably in the various `*.Jenkinsfile`. Shall these be adjusted as well?

I think so. Otherwise Vagrant machines may be provisioned incorrectly in CI.

**Comment by Rolinh** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]
Thanks!

**Comment by Rolinh** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Review by aanm — APPROVED** [review]
@mrostecki @Rolinh the CI does not run the `start.sh` script.

**Pull request merged**
