### PR TITLE
Use alpine as base image for Docs container

### PR DESCRIPTION
**Pull request by ishantanu**
1. Modify Docs Dockerfile to use alpine.
2. Modify Makefile to use newer docker cli commands.

Signed-off-by: Shantanu Deshpande <shantanud106@gmail.com>

**Summary of changes**:

Fixes: #3276 

**How to test**:

Run `make render-docs`

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
Please rebase against master with the Kafka CI fixes.

**Comment by ishantanu** [comment]
Done. Rebased the branch from master.

**Comment by manalibhutiyani** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
Thanks!

**Pull request merged**
