### PR TITLE
v1.15 Backports 2024-06-12

### PR DESCRIPTION
**Pull request by giorio94**
* [x] #33000 (@marqc)
 * [x] #33062 (@julianwiedmann)
 * [x] #32660 (@learnitall) :warning: resolved conflicts
    * :warning: Resolved conflicts in cilium and hubble-relay Dockerfiles, please check carefully.
 * [x] #33129 (@giorio94)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33000 33062 32660 33129
```

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]

**Comment by giorio94** [comment]
/test-backport-1.15

**Review by learnitall — APPROVED** [review]
LGTM, thank you!

**Review by marqc — APPROVED** [review]
LGTM, thanks!

**Comment by giorio94** [comment]
CI failures to be addressed rebasing on top of https://github.com/cilium/cilium/pull/33110

**Comment by giorio94** [comment]
Rebased to pick the changes introduced in https://github.com/cilium/cilium/pull/33110

**Comment by giorio94** [comment]
/test-backport-1.15

**Review by viktor-kurchenko — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]
pre-approved

**Comment by giorio94** [comment]
Marked as draft to additionally include https://github.com/cilium/cilium/pull/33129

**Comment by giorio94** [comment]
Rebased to fix conflict, and additionally backported #33129.

**Comment by giorio94** [comment]
/test-backport-1.15

**Review by ti-mo — APPROVED** [review]

**Pull request merged**
