### PR TITLE
Add missing requireIPv6PodCIDR setting

### PR DESCRIPTION
**Pull request by NeilW**
Signed-off-by: Neil Wilson <neil@aldur.co.uk>

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]

**Comment by christarazi** [comment]
net-next hit https://github.com/cilium/cilium/issues/12511.

**Comment by christarazi** [comment]
retest-net-next

**Comment by christarazi** [comment]
retest-runtime

**Comment by christarazi** [comment]
retest-gke

**Review by brb — APPROVED** [review]
Thanks!

**Pull request merged**
