### PR TITLE
images: Update LLVM to 18.1.8

### PR DESCRIPTION
**Pull request by sayboras**
Relates: https://github.com/cilium/image-tools/pull/302
Relates: #32801

### CODE REVIEW

**Review by borkmann — APPROVED** [review]

**Review by gentoo-root — APPROVED** [review]

**Review by brlbil — APPROVED** [review]

**Review by kaworu — APPROVED** [review]
Relay change LGTM

**Comment by julianwiedmann** [comment]
@sayboras can we close https://github.com/cilium/cilium/issues/32801 then, or are there still any outstanding tasks for the update to LVVM 18?

I remember @gentoo-root did an evaluation of BPF program size / complexity changes when we last bumped to LLVM 17, to identify gains / regressions.

**Comment by sayboras** [comment]
yes, it will be the next step :+1:

**Pull request merged**
