### PR TITLE
go.mod, vendor: update cloud provider SDK Go modules

### PR DESCRIPTION
**Pull request by tklauser**
Update the cloud provider SDK Go modules using
`contrib/scripts/go-mod-update-cloud-providers.sh`

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Comment by tklauser** [comment]
Review is in and affected CI jobs passed (Travis CI is currently failing consistently on `master`). Marking as ready to merge.

**Comment by tklauser** [comment]
Rebased to resolve conflicts in `go.sum`. Go vendoring checks passed, no need to re-run other tests, marking as ready to merge.

**Pull request merged**
