### PR TITLE
Documentation: Embed full branch name in all SCM_WEB links

### PR DESCRIPTION
**Pull request by tgraf**
Fixes: #2537

```release-note
Fix link URLs that depend on a branch name
```

### CODE REVIEW

**Comment by aalemayhu** [comment]
Sorry, I don't understand what you are fixing here. The URLs will still be broken for `v1.0.0-rc2`. So basically you are reverting to similar behavior as before. When you release the next release candidate it will be pointing to master because that is the default HEAD on GitHub. What if the release candidate includes configuration changes specific to it? The reason the URL broke was that your purposed version scheme did not cover release candidates. I tried to raise this a couple of times on Slack but was ignored.

**Comment by tgraf** [comment]
> Sorry, I don't understand what you are fixing here. The URLs will still be broken for v1.0.0-rc2. So basically you are reverting to similar behavior as before. When you release the next release candidate it will be pointing to master because that is the default HEAD on GitHub. What if the release candidate includes configuration changes specific to it? The reason the URL broke was that your purposed version scheme did not cover release candidates. I tried to raise this a couple of times on Slack but was ignored.

This changes moves to a very simple schema very every branch that is to be released in the documentation must be backed by a git branch. This works well because on RTD, we select branches to be included so they are automatically always backed by a git branch. When backported to the v1.0.0-rc2 branch, it will work there as well.

Are you saying that when building on RTD, `git rev-parse --abbrev-ref HEAD` will not work and always point to HEAD?

I'm open to other suggestions but we can't stick to the old schema as we require doc branches for versions outside of the vX.Y schema.

**Comment by aalemayhu** [comment]
2018-01-16 7:29 GMT+01:00 Thomas Graf <notifications@github.com>:

> Sorry, I don't understand what you are fixing here. The URLs will still be
> broken for v1.0.0-rc2. So basically you are reverting to similar behavior
> as before. When you release the next release candidate it will be pointing
> to master because that is the default HEAD on GitHub. What if the release
> candidate includes configuration changes specific to it? The reason the URL
> broke was that your purposed version scheme did not cover release
> candidates. I tried to raise this a couple of times on Slack but was
> ignored.
>
> This changes moves to a very simple schema very every branch that is to be
> released in the documentation must be backed by a git branch. This works
> well because on RTD, we select branches to be included so they are
> automatically always backed by a git branch. When backported to the
> v1.0.0-rc2 branch, it will work there as well.
>

If there is a branch it should work yes but will GitHub let you use the
same src for both a tag and a branch?
Would you not just hit a error like
```
error: src refspec X.Y.Z matches more than one.
error: failed to push some refs to 'git@github.com:cilium/cilium'
```


> Are you saying that when building on RTD, git rev-parse --abbrev-ref HEAD
> will not work and always point to HEAD?
>
No. If you are running it from a branch it might work, but I would test
this properly and make no assumtions. I was thinking of
when run from a tag.

> I'm open to other suggestions but we can't stick to the old schema as we
> require doc branches for versions outside of the vX.Y schema.
>
I don't like your fix, and would instead have fixed the conditional
statement to include release candidates.

**Comment by tgraf** [comment]
> If there is a branch it should work yes but will GitHub let you use the
> same src for both a tag and a branch?
> Would you not just hit a error like

Why do we need to use the same name for the tag and branch? We will have branches after 1.0 in the form of `1.0`, `1.1` and then tag `1.0.0`, `1.0.1`. These tags must strictly be compatible to each other so will share the same documentation.

> No. If you are running it from a branch it might work, but I would test
> this properly and make no assumtions. I was thinking of
> when run from a tag.

I'm not objecting to any further work here. I've merged this immediately because all link in the latest Documentation were broken including all getting started guides. An immediate fix was required. We can now discuss the long term fix. The `v1.0.0-rc2` doc branch is still broken so we should get to consensus quickly or just backport this change to fix it in the meantime.

> I don't like your fix, and would instead have fixed the conditional
> statement to include release candidates.

That is not good enough. You need to provide some reasons if you disagree. I have no problem arguing over this and giving in to anything that is better but it needs to be on the basis of technical argumentation factoring in things like: risk of not breaking this again.

My argument for branch based is:
- it is not dependant on anyone updating `VERSION` so even on error, we won't break the documentation
- A branch is used naturally for any past version that will receive backports and thus needs available documentation for that version.
- It is very simple to understand and is completely decoupled from the actual versioning schema in use.

**Pull request merged**
