### PR TITLE
Update to kubernetes tests and library dependencies to 1.12.1

### PR DESCRIPTION
**Pull request by aanm**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5819)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Review by jrajahalme — APPROVED** [review]

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Review by eloycoto — APPROVED** [review]
I saw that the CNI  is still `0.6.0-00`, what is the reason of the change?

```
Package: kubernetes-cni
Version: 0.6.0-00
Installed-Size: 44824
Maintainer: Kubernetes Authors <kubernetes-dev@googlegroups.com>
Architecture: amd64
Description: Kubernetes CNI
 The binaries required to provision container networking
Homepage: https://kubernetes.io
Filename: pool/kubernetes-cni_0.6.0-00_amd64_43460dd3c97073851f84b32f5e8eebdc84fadedb5d5a00d1fc6872f30a4dd42c.deb
Priority: optional
SHA256: 43460dd3c97073851f84b32f5e8eebdc84fadedb5d5a00d1fc6872f30a4dd42c
Section: misc
Size: 5909628
```

**Comment by aanm** [comment]
@eloycoto This weekend the installation of all k8s versions was failing as the packaged depend on `kubernetes-cni 0.6.0-02` but that package didn't exist. This was to help switching between the `00` and `02`

**Comment by eloycoto** [comment]
Ok, thanks

**Review by tgraf — APPROVED** [review]

**Pull request merged**
