### PR TITLE
Update k8s to v1.16.3, 1.14.9 and 1.15.6

### PR DESCRIPTION
**Pull request by aanm**
it's marked as a release blocker for 1.6.4 because of the client-go bug fixed in k8s

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9614)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
:ship:

**Comment by joestringer** [comment]
Upstream test failure seems legitimate:
```
14:29:49  +++ [1114 22:29:48] Building go targets for linux/amd64:
14:29:49      vendor/github.com/onsi/ginkgo/ginkgo
14:29:50  go: downloading github.com/onsi/ginkgo v1.8.0
14:29:50  go: extracting github.com/onsi/ginkgo v1.8.0
14:29:50  go: downloading github.com/hpcloud/tail v1.0.0
14:29:50  go: extracting github.com/hpcloud/tail v1.0.0
14:29:50  go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
14:29:50  go: downloading gopkg.in/fsnotify.v1 v1.4.7
14:29:50  go: extracting gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
14:29:50  go: extracting gopkg.in/fsnotify.v1 v1.4.7
14:29:50  go: downloading golang.org/x/sys v0.0.0-20190209173611-3b5209105503
14:29:50  go: extracting golang.org/x/sys v0.0.0-20190209173611-3b5209105503
14:29:50  go: finding github.com/onsi/ginkgo v1.8.0
14:29:50  go: finding github.com/hpcloud/tail v1.0.0
14:29:50  go: finding gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
14:29:50  go: finding gopkg.in/fsnotify.v1 v1.4.7
14:29:50  go: finding golang.org/x/sys v0.0.0-20190209173611-3b5209105503
14:29:53  go: downloading github.com/spf13/pflag v1.0.3
14:29:53  go: extracting github.com/spf13/pflag v1.0.3
14:29:53  go: finding github.com/spf13/pflag v1.0.3
14:29:54  go/build: importGo k8s.io/kubernetes: exit status 1
14:29:54  can't load package: package k8s.io/kubernetes: cannot find module providing package k8s.io/kubernetes
14:29:54  
14:29:54  
14:29:55  +++ [1114 22:29:55] Building go targets for linux/amd64:
14:29:55      ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
14:30:17  go: finding k8s.io/kubernetes/vendor latest
14:30:17  go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd latest
14:30:17  go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen latest
14:30:17  go: finding k8s.io/kubernetes/vendor/k8s.io latest
14:30:17  go: finding k8s.io/kubernetes/vendor/k8s.io/code-generator latest
14:30:32  can't load package: package k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen: no matching versions for query "latest"
14:30:32  !!! [1114 22:30:31] Call tree:
14:30:32  !!! [1114 22:30:31]  1: /home/vagrant/go/src/k8s.io/kubernetes/hack/lib/golang.sh:714 kube::golang::build_some_binaries(...)
14:30:32  !!! [1114 22:30:31]  2: /home/vagrant/go/src/k8s.io/kubernetes/hack/lib/golang.sh:853 kube::golang::build_binaries_for_platform(...)
14:30:32  !!! [1114 22:30:31]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
14:30:32  !!! [1114 22:30:31] Call tree:
14:30:32  !!! [1114 22:30:31]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
14:30:32  !!! [1114 22:30:31] Call tree:
14:30:32  !!! [1114 22:30:31]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
14:30:32  Makefile.generated_files:200: recipe for target '_output/bin/deepcopy-gen' failed
14:30:32  Makefile:559: recipe for target 'generated_files' failed
14:30:32  make[1]: *** [_output/bin/deepcopy-gen] Error 1
14:30:32  make: *** [generated_files] Error 2
```

https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/1701/execution/node/58/log/

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-upstream-k8s

**Review by jrajahalme — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Pull request merged**
