### PR TITLE
[Monitor] add src and dst data to json output

### PR DESCRIPTION
**Pull request by nebril**
Signed-off-by: Maciej Kwiek <maciej@covalent.io>

### CODE REVIEW

**Review by raybejjani — APPROVED** [review]

**Review by raybejjani — APPROVED** [review]

**Comment by nebril** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
@nebril the previous flake was already informed here https://github.com/cilium/cilium/issues/3850#issuecomment-391437815

**Comment by nebril** [comment]
test-me-please

**Pull request merged**
