### PR TITLE
v1.9 backports 2021-06-16

### PR DESCRIPTION
**Pull request by christarazi**
* #16307 -- k8s, node: Restore router IPs (cilium_host) from K8s resource  (@christarazi)
   * Note: see the commit msg of the last commit for an update on how I
     resolved the conflicts and build failures specifically for the v1.9 tree.
* #16672 -- daemon, node: Fix faulty router IP restoration logic  (@christarazi)
* #16696 -- Plumb Azure interface's VPC / primary CIDR and set it as native routing CIDR in Azure IPAM mode  (@christarazi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16307 16672 16696 ; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by christarazi** [comment]
test-backport-1.9

**Comment by christarazi** [comment]
test-backport-1.9

**Comment by christarazi** [comment]
test-1.17-5.4

**Comment by christarazi** [comment]
test-1.15-4.9

**Comment by christarazi** [comment]
test-1.13-4.9

**Comment by christarazi** [comment]
test-1.12-netnext

**Comment by christarazi** [comment]
test-backport-1.9

**Review by aanm — APPROVED** [review]

**Comment by aditighag** [comment]
@christarazi This might need a rebase after https://github.com/cilium/cilium/pull/16779 was merged.

**Comment by christarazi** [comment]
test-backport-1.9

**Pull request merged**
