### PR TITLE
vendor: update k8s dependencies to 1.11.2

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5147)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-k8s-upstream

**Comment by aanm** [comment]
test-upstream-k8s

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
