### PR TITLE
v1.11 Backports 2023-05-03 Cont

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
This PR is a successor of #25250. I didn't make any changes for those who are already approved in the old PR, so you don't have to review this again.

For those who are notified even if you are not listed as a reviewer now, sorry for the spam. I mistakenly open the PR against `main` at the beginning, and that made a huge diff.
 
 * [x] #25033 (@giorio94)
 * [x] #25109 (@sayboras)
 * [x] #25192 (@kaworu)
 * [ ] #25174 (@joestringer)
 * [x] #25219 (@tommyp1ckles)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 25033 25109 25192 25174 25219; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
make add-labels BRANCH=v1.11 ISSUES=25043,25046,24770,25033,25109,25192,25174,25219
```

### CODE REVIEW

**Comment by YutaroHayakawa** [comment]
@aditighag I resolved this comment, but I still see the test failure. I'll dig into more details, but please let me know if you have any clue.

https://github.com/cilium/cilium/pull/25250#discussion_r1187486629

**Review by giorio94 — APPROVED** [review]

**Comment by pchaigno** [comment]
> For those who are notified even if you are not listed as a reviewer now, sorry for the spam. I mistakenly open the PR against `main` at the beginning, and that made a huge diff.

Don't be sorry. Use the scripts.

**Review by sayboras — APPROVED** [review]
LGTM ✅

**Comment by aditighag** [comment]
@YutaroHayakawa Please skip the PR backport. I'll backport it manually to 1.11. Thanks!

**Review by harsimran-pabla — APPROVED** [review]
There is no bgp change in this, fix is already backported here https://github.com/cilium/cilium/pull/25139.

**Review by kaworu — APPROVED** [review]
Thanks @YutaroHayakawa my patch LGTM

**Comment by YutaroHayakawa** [comment]
Dropped Aditi's PR.

**Comment by YutaroHayakawa** [comment]
/test-backport-1.11

**Review by michi-covalent — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
k8s-1.21-kernel-4.9: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/2621/
k8s-1.22-kernel-4.19: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/1665/
They are known flakes as MLH mentioned.

**Comment by YutaroHayakawa** [comment]
/test-1.21-4.9

**Comment by YutaroHayakawa** [comment]
/test-1.22-4.19

**Comment by YutaroHayakawa** [comment]
Conformance AWS-CNI: https://github.com/cilium/cilium/actions/runs/4942916632

Timeout while connecting to EKS kubernetes service. Probably, the AWS side of the issue. Let me retry.

**Comment by YutaroHayakawa** [comment]
/ci-awscni-1.11

**Comment by YutaroHayakawa** [comment]
All green. Ready to merge.

**Comment by jrajahalme** [comment]
@YutaroHayakawa Run the script to mark backports done. Noticed that you had dropped #24770, marked it back to `needs-backport-1.11`, but should make sure if there was another determination what to do with it?

**Comment by YutaroHayakawa** [comment]
@jrajahalme Thanks for running the script. #24770 will be handled by Aditi.

**Pull request merged**
