### PR TITLE
v1.13 Backports 2023-07-17

### PR DESCRIPTION
**Pull request by gandro**
* [x] #23616 (@deepeshaburse) :information_source: Minor docs conflicts
 * [ ] #26660 (@squeed) :information_source: Minor docs conflicts
 * [x] #26502 (@sayboras) :information_source: Minor docs conflicts
 * [x] #26800 (@tklauser)
 * [x] #26791 (@aanm)
 * [x] #26810 (@pchaigno)

PRs skipped due to conflicts:

 * #26755 (@rolinh)
 * #26759 (@qmonnet)
 * #26846 (@julianwiedmann)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 23616 26660 26502 26800 26791 26810; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=23616,26660,26502,26800,26791,26810
```

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by tklauser — APPROVED** [review]
My change looks good, thanks Sebastian.

**Review by sayboras — APPROVED** [review]
Thanks a lot and lgtm :1st_place_medal:

**Review by aanm — APPROVED** [review]

**Comment by gandro** [comment]
/test-backport-1.13

**Comment by gandro** [comment]
Travis timed out. Restarting. https://app.travis-ci.com/github/cilium/cilium/jobs/606163249

**Comment by gandro** [comment]
Travis hit https://github.com/cilium/cilium/issues/26873

**Comment by gandro** [comment]
/test-1.24-4.19

**Comment by gandro** [comment]
All required tests besides Travis have passed. Travis will not become green on this branch, as it needs follow-up fixes. Only missing review is for a 3 line docs change form Casey who is out today. Marking ready to merge.

**Pull request merged**
