### PR TITLE
Support EndpointSlices with BGP mode by updating MetalLB to v0.10.0 

### PR DESCRIPTION
**Pull request by christarazi**
- bgp, vendor: Update go.universe.tf/metallb to support EndpointSlices
- watchers: Refactor endpoint slice add/update events handling
- bgp, watchers: Add support for EndpointSlice
- docs, daemon: Allow EndpointSlices to be used with BGP

Depends on https://github.com/cilium/cilium/pull/16523

### CODE REVIEW

**Comment by christarazi** [comment]
test-me-please

**Review by rolinh — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]

**Review by jibi — APPROVED** [review]

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

**Review by nathanjsweet — APPROVED** [review]

**Comment by christarazi** [comment]
ci-eks

**Comment by christarazi** [comment]
ci-gke

**Comment by christarazi** [comment]
Rebased to up fix for FQDN related (https://github.com/cilium/cilium/pull/16769) that would resolve these flakes: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/1016/

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
CI has passed, just need to rebase to resolve vendor conflicts:
image

**Comment by christarazi** [comment]
Adding back ready to merge as the vendor Go checks have passed along with Travis, which should be enough to validate the rebase.

**Pull request merged**
