### PR TITLE
DO NOT MERGE: Testing v1.3 before release

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6007)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Build failure: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1119

etcd-operator scaled down again it looks like.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-upstream-k8s

**Comment by tgraf** [comment]
test-docs-please

**Pull request closed without merging**
