### PR TITLE
alibabacloud: use DescribeVSwitches to get vswitch tags

### PR DESCRIPTION
**Pull request by haozhangami**
Obtaining the vswitch tags through ListTagResources is incomplete, which will cause the IP allocation to fail and require additional queries. Therefore, use DescribeVSwitches to get the vswitch tags.

Signed-off-by: Hao Zhang <hao.zhang.am.i@gmail.com>

```release-note
use DescribeVSwitches to get vswitch tags
```

### CODE REVIEW

**Comment by haozhangami** [comment]
Hello @l1b0k  please help to review, thank you

**Review by christarazi — APPROVED** [review]

**Comment by sayboras** [comment]
All CI jobs are passed (except ci-verifier is in waiting for status stage, but this job is not required as part of the changes here), reviews are in, marking this ready to merge.

**Pull request merged**
