### PR TITLE
fix: if ends with return, drop else

### PR DESCRIPTION
**Pull request by yulng**
if block ends with a return statement, so drop this else and outdent its block

Signed-off-by: yulng <wei.yang@daocloud.io>

Thanks

### CODE REVIEW

**Comment by pchaigno** [comment]
@yulng I think we should avoid these cleanup PR now that we have branched. They are not fixing anything and will just increase the likelihood of backporting conflicts for the v1.13 branch.

**Comment by yulng** [comment]
> @yulng I think we should avoid these cleanup PR now that we have branched. They are not fixing anything and will just increase the likelihood of backporting conflicts for the v1.13 branch.



> @yulng I think we should avoid these cleanup PR now that we have branched. They are not fixing anything and will just increase the likelihood of backporting conflicts for the v1.13 branch.

OK. If there is no problem with my PR, could  it be merged before the v1.13 modification?

**Comment by pchaigno** [comment]
No. The v1.13 branching already happened.

**Comment by yulng** [comment]
> No. The v1.13 branching already happened.

ok,i closed it

**Pull request closed without merging**
