### PR TITLE
Cilium Training by Solo.io

### PR DESCRIPTION
**Pull request by distributethe6ix**
This README.md describe the the Cilium training workshop as developed by Solo.io

We would like to add this to the Cilium training program.

Signed-off-by: Marino Wijay <45947861+distributethe6ix@users.noreply.github.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Review by aanm — CHANGES_REQUESTED** [review]
Hi, did you mean to open a PR against https://github.com/cilium/cilium.io?

**Comment by distributethe6ix** [comment]
@aanm Maybe! I want to add Cilium training but, is this supposed to go into the cilium/cilium.io repo?

**Comment by lizrice** [comment]
You might also want to check the requirements for Cilium training listed [here](https://github.com/cilium/cilium.io/blob/main/CONTRIBUTING.md#listing-cilium-training).

**Comment by distributethe6ix** [comment]
@lizrice I have reviewed prior to submitting. I have created a readme that provides details about the training workshop itself.

**Comment by aanm** [comment]
> @aanm Maybe! I want to add Cilium training but, is this supposed to go into the cilium/cilium.io repo?

Yes, that is correct.

**Comment by distributethe6ix** [comment]
> > @aanm Maybe! I want to add Cilium training but, is this supposed to go into the cilium/cilium.io repo?
> 
> Yes, that is correct.

Should I close this PR and resubmit then? Where would be the best place to store this?

**Comment by aanm** [comment]
> > > @aanm Maybe! I want to add Cilium training but, is this supposed to go into the cilium/cilium.io repo?
> > 
> > 
> > Yes, that is correct.
> 
> Should I close this PR and resubmit then? Where would be the best place to store this?

Correct since PRs can't be transferred between github projects

**Comment by distributethe6ix** [comment]
> > > > @aanm Maybe! I want to add Cilium training but, is this supposed to go into the cilium/cilium.io repo?
> > > 
> > > 
> > > Yes, that is correct.
> > 
> > 
> > Should I close this PR and resubmit then? Where would be the best place to store this?
> 
> Correct since PRs can't be transferred between github projects

Sounds good! Will recreate and thanks for your help!

**Pull request closed without merging**
