### PR TITLE
v1.6 backports 2019-08-16

### PR DESCRIPTION
**Pull request by ianvernon**
* #8925 -- Fix proxy port leak on endpoint delete (@joestringer)
 * #8918 -- operator: generate cmdref (@ianvernon)
 * #8929 -- endpoint: check if returned FinalizeFunc is nil before executing it (@ianvernon)
 * #8926 -- update cilium-docker-plugin, cilium-operator to golang 1.12.8 (@ianvernon)
 * #8928 -- daemon: Do not start L7 proxy support if --install-iptables-rules="false" (@jrajahalme)
 * #8875 -- Add NodePort BPF CI tests (@brb)

Once this PR is merged, you can update the PR labels via:

```
$ for pr in 8925 8918 8929 8926 8928 8875; do contrib/backporting/set-labels.py $pr done 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8935)

### CODE REVIEW

**Comment by ianvernon** [comment]
Travis failed due to issues retrieving packages: 

```
E: Package 'kernel-package' has no installation candidate
apt-get.diagnostics
429apt-get install failed
518The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install kernel-package libc6-dev-i386" failed and exited with 100 during .
```

**Comment by ianvernon** [comment]
never-tell-me-the-odds

**Comment by ianvernon** [comment]
BPF NodePort tests (added in this backport) failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14436/testReport/junit/Suite-k8s-1/10/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan/

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by ianvernon** [comment]
Another failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14438/

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
