### PR TITLE
v1.10 backports 2021-11-12

### PR DESCRIPTION
**Pull request by ti-mo**
* #17344 -- .github: Rename `project/ci-force` to `ci/flake` (@pchaigno)
 * #17546 -- Reduce bugtool memory usage (@tklauser)
 * #17651 -- daemon: add K8sCacheIsSynced() method (@jibi)
 * #17663 -- Minor egress gateway fixups (@pchaigno)
 * #17667 -- bug/pkg/health: Fix Nil Address Issue in Node Update Mechanism (@nathanjsweet)
 * #17756 -- docs: Use git+https in requirements.txt (@michi-covalent)
 * #17755 -- Adds a warning in the upgrade doc about split cluster (@Weil0ng)
 * #17772 -- operator: Hidden flags for egress gateway and LRPs (@pchaigno)
 * #17760 -- docs: fix a block directive in OpenShift GSG (@qmonnet)
 * #17699 -- Fix identity leak via FQDN selectors (@joestringer)
 * #17773 -- egressgateway: Allow several CENPs with same egress IP (@pchaigno)
 * #17639 -- egress gw exclude internal traffic (@kkourt)
 * #17769 -- test: Do not require netpols in 'waitNextPolicyRevisions()' (@jrajahalme)
 * #16840 -- node-init: remove aws iptables rules in eni mode (@bmcustodio)
 * #17757 -- install/kubernetes/cilium: reference stable docs for eBPF maps (@tklauser)
 * #17812 -- .github: Increase reporting threshold for new flakes (@pchaigno)
 * #17822 -- docs: Reword sentence on WireGuard limitation (@pchaigno)
 * #17585 -- Adds an `ACCEPT` rule for untracked pkts in `filter:CILIUM_OUTPUT` (@Weil0ng)
 * #17847 -- docs: Mention about KubeVirt in KPR docs (@brb)
 * #17836 -- nodediscovery: Fix local host identity propagation (@joestringer)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 17344 17546 17651 17663 17667 17756 17755 17772 17760 17699 17773 17639 17769 16840 17757 17812 17822 17585 17847 17836; do contrib/backporting/set-labels.py $pr done 1.10; done
```

---

@jibi @kkourt Commit 02b38a0f60745fb57bd364b7b093851e72c4f4d8 from https://github.com/cilium/cilium/pull/17639 depends on 6cad004269eda9350c1ae26a1779fe827e4e9f89, which I was able to pull in here. Unfortunately, it also depends on 5d6a12d3732cce45534e57324a6c10a92a395583, which would introduce a breaking change, so I changed your code to look at the pre-renamed flag `EnableEgressGateway` instead. Please double check to make sure everything here is correct.

@bmcustodio I skipped 35e93c47eae05f4e1212acb015706bfdb8bbd27b and just kept the script inline, we don't do those bash includes in the 1.10 charts yet.

Removed #17642 as the PR was incorrectly marked as a 1.10 backport initially.

### CODE REVIEW

**Comment by ti-mo** [comment]
@kkourt PTAL: https://github.com/cilium/cilium/runs/4190682158?check_suite_focus=true

**Comment by pchaigno** [comment]
> @kkourt PTAL: https://github.com/cilium/cilium/runs/4190682158?check_suite_focus=true

@ti-mo The variable is just called `dstID` instead of `dst_id` in the v1.10 branch. See a few lines above.

**Review by jibi — APPROVED** [review]
:+1: for my changes

**Review by brb — APPROVED** [review]
My change LGTM, thanks.

**Review by jibi — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
LGTM for my changes

**Review by bmcustodio — APPROVED** [review]
> @bmcustodio I skipped 35e93c4 and just kept the script inline, we don't do those bash includes in the 1.10 charts yet.

ACK! :+1: LGTM!

**Comment by ti-mo** [comment]
> > * [Reduce bugtool memory usage #17546](https://github.com/cilium/cilium/pull/17546) -- Reduce bugtool memory usage (@tklauser)
> 
> Looks like commit [f05a344](https://github.com/cilium/cilium/commit/f05a344504c8cea44ae8f90cc67da4c5f99ae432) from that PR is missing though. Is this intentional?

Oh dear, nice catch. Thanks!

**Comment by ti-mo** [comment]
/test-backport-1.10

**Review by qmonnet — APPROVED** [review]
> * #17760 -- docs: fix a block directive in OpenShift GSG (@qmonnet)

Looks good, thanks!

**Review by aanm — APPROVED** [review]

**Review by aanm — CHANGES_REQUESTED** [review]
@ti-mo why is https://github.com/cilium/cilium/pull/17161 being backported? It didn't have the `needs-backport/1.10` label.

**Review by jrajahalme — APPROVED** [review]
Backport of my PR looks good :-)

**Review by kkourt — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
PR #17699 backport looks about right at a glance. Based on the PR description I assume there were no troubles in backporting it.

Travis seems to be legitimately complaining, not sure about the other CI failures.

**Review by michi-covalent — APPROVED** [review]
:heavy_check_mark: https://github.com/cilium/cilium/pull/17861/commits/4df609199ec52d14285c858bc1662714d3138c76

**Comment by Weil0ng** [comment]
My changes LGTM!

**Review by Weil0ng — APPROVED** [review]

**Review by aanm — DISMISSED** [review]
@ti-mo sorry, I meant #17642 should not be backported. I've just left this comment https://github.com/cilium/cilium/pull/17642#issuecomment-970215553

**Comment by ti-mo** [comment]
> @ti-mo sorry, I meant #17642 should not be backported. I've just left this comment [#17642 (comment)](https://github.com/cilium/cilium/pull/17642#issuecomment-970215553)

@aanm Done. Dropped the commit, removed the backporting label(s) from that PR and removed it from the description in this one.

**Review by pchaigno — APPROVED** [review]
> - .github: Rename project/ci-force to ci/flake #17344 -- .github: Rename project/ci-force to ci/flake (@pchaigno)
> - Minor egress gateway fixups #17663 -- Minor egress gateway fixups (@pchaigno)
> - operator: Hidden flags for egress gateway and LRPs #17772 -- operator: Hidden flags for egress gateway and LRPs (@pchaigno)
> - egressgateway: Allow several CENPs with same egress IP #17773 -- egressgateway: Allow several CENPs with same egress IP (@pchaigno)
> - .github: Increase reporting threshold for new flakes #17812 -- .github: Increase reporting threshold for new flakes (@pchaigno)
> - docs: Reword sentence on WireGuard limitation #17822 -- docs: Reword sentence on WireGuard limitation (@pchaigno)

My PRs look good.

**Comment by ti-mo** [comment]
/test-backport-1.10

**Review by aanm — APPROVED** [review]

**Comment by gandro** [comment]
- Conformance AWS-CNI failed probably due to an infrastructure or workflow issue. Will restart, it's not Cilium-related at least: https://github.com/cilium/cilium/runs/4236999713?check_suite_focus=true
- ConformanceAKS is known to be broken on v1.10 https://github.com/cilium/cilium/actions/runs/1471205981 https://github.com/cilium/cilium/issues/17671
- net-next failed with an provisioning error https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/1973/ 
 `11:34:55  Progress state: NS_ERROR_INVALID_ARG
11:34:55  VBoxManage: error: Appliance import failed
11:34:55  VBoxManage: error: Code NS_ERROR_INVALID_ARG (0x80070057) - Invalid argument value (extended info not available)`
- k8s-1.19-kernel-4.9 failed with a yet unidentified error https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.9/1888/testReport/Suite-k8s-1/19/K8sPolicyTest_GuestBook_Examples_checks_policy_example/
- k8s-1.19-kernel-5.4 got sigkilled during `K8sDatapathConfig Host firewall With VXLAN` with `12:16:47  12:16:46 STEP: Installing Cilium
12:17:22  FAIL: Cilium cannot be installed
12:17:22  Expected
12:17:22      <*helpers.cmdError | 0xc002056a00>: Unable to delete existing cilium YAML (signal: killed) output: cmd: kubectl delete -f  cilium-16b852c9efbd02cb.yaml --wait --ignore-not-found
12:17:22  Exitcode: -1 
12:17:22  Err: signal: killed`

**Comment by gandro** [comment]
/ci-awscni-1.10

**Comment by gandro** [comment]
/ci-aks-1.10

**Comment by gandro** [comment]
/test-1.16-netnext

**Comment by gandro** [comment]
/test-1.19-4.9

**Comment by gandro** [comment]
/test-1.19-5.4

**Comment by gandro** [comment]
/test-1.19-5.4

**Comment by gandro** [comment]
/test-1.16-netnext

**Comment by gandro** [comment]
/test-1.16-netnext

**Review by gandro — APPROVED** [review]

**Pull request merged**
