### PR TITLE
bpf: fix misconfigured nat to 0.0.0.0 on !masquerade config

### PR DESCRIPTION
**Pull request by borkmann**
(See commit msg for detailled analysis.)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Review by brb — COMMENTED** [review]
Thanks for fixing this!

I think that the check is still error prone. Could we conditionally enable `EnableBPFMasquerade` in `pkg/option/option.go` by checking whether `EnableIPv4` and `Masquerade` are true?

Also, I think that it fixes 0962c029849168da34d88f57dd7d0b73876d823b instead of other two linked commits in your msg. The problem came to the surface once we had decoupled NP and MASQ IP addrs.

**Comment by borkmann** [comment]
> I think that the check is still error prone. Could we conditionally enable `EnableBPFMasquerade` in `pkg/option/option.go` by checking whether `EnableIPv4` and `Masquerade` are true?

I don't think we could as this would mean that iptables-based masquerading rules won't be installed if we auto-enable the EnableBPFMasquerade config option.

(Fwiw, the check is now in line with the rest of BPF masq tests:

```
root@apoc:~/go/src/github.com/cilium/cilium# git grep -n EnableBPFMasquerade | grep -n EnableIPv4Masquerade
1:daemon/cmd/daemon.go:518:	if option.Config.EnableIPv4Masquerade && option.Config.EnableBPFMasquerade &&
3:daemon/cmd/daemon.go:540:	if option.Config.EnableIPv4Masquerade && option.Config.EnableBPFMasquerade {
10:pkg/datapath/iptables/iptables.go:1185:		if option.Config.EnableIPv4Masquerade && !option.Config.EnableBPFMasquerade {
12:pkg/datapath/linux/config/config.go:425:		if option.Config.EnableIPv4Masquerade && option.Config.EnableBPFMasquerade {
13:pkg/datapath/linux/config/config.go:541:		if option.Config.EnableIPv4Masquerade && option.Config.EnableBPFMasquerade {
14:pkg/datapath/loader/loader.go:175:	if option.Config.EnableIPv4Masquerade && option.Config.EnableBPFMasquerade && bpfMasqIPv4Addrs != nil {
15:pkg/datapath/loader/template.go:232:		if option.Config.EnableIPv4Masquerade && option.Config.EnableBPFMasquerade {
```)

> Also, I think that it fixes [0962c02](https://github.com/cilium/cilium/commit/0962c029849168da34d88f57dd7d0b73876d823b) instead of other two linked commits in your msg. The problem came to the surface once we had decoupled NP and MASQ IP addrs.

Ok, will update the commit msg.

**Comment by borkmann** [comment]
(CI green, changing commit msg only)

**Comment by brb** [comment]
> I don't think we could as this would mean that iptables-based masquerading rules won't be installed if we auto-enable the EnableBPFMasquerade config option.

I meant in `pkg/option/option.go` to do `option.Config.EnableBPFMasquerade = option.Config.EnableBPFMasquerade & option.Config.EnableIPv4 & option.Config.Masquerade`. This would allow in the most places to drop the check for `option.Config.Masquerade`.

**Review by pchaigno — APPROVED** [review]
LGTM, although Martynas's proposed change would make it harder to re-introduce this sort of error later on.

**Comment by pchaigno** [comment]
> (CI green, changing commit msg only)

Not GKE. Failed due to scaling issues.

**Comment by borkmann** [comment]
> > I don't think we could as this would mean that iptables-based masquerading rules won't be installed if we auto-enable the EnableBPFMasquerade config option.
> 
> I meant in `pkg/option/option.go` to do `option.Config.EnableBPFMasquerade = option.Config.EnableBPFMasquerade & option.Config.EnableIPv4 & option.Config.Masquerade`. This would allow us to drop the check for `option.Config.Masquerade` in the most places.

The old config option `option.Config.Masquerade` does not exist anymore, we do have however `option.Config.EnableIPv4Masquerade` and `option.Config.EnableIPv6Masquerade` which implies the v4 + masq setting. I'm a bit hesitant to do something like `option.Config.EnableBPFMasquerade = option.Config.EnableBPFMasquerade && option.Config.EnableIPv4Masquerade` given we might need to for `option.Config.EnableIPv6Masquerade` as well in future to get rid of the iptables masq there.

**Comment by pchaigno** [comment]
retest-gke

**Review by tgraf — APPROVED** [review]

**Comment by borkmann** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Pull request merged**
