### PR TITLE
datapath: Provide IptablesManager instead of *Manager

### PR DESCRIPTION
**Pull request by jrajahalme**
Provide the `datapath/types.IptablesManager` instead of `iptables.*Manager`, so that it can be replaced with the fake for testing.

### CODE REVIEW

**Review by rgo3 — APPROVED** [review]

**Review by aspsk — APPROVED** [review]

**Comment by joestringer** [comment]
Did you consider just adding the fake to `pkg/testutils` so we can avoid linking this logic into the runtime daemon?

**Review by doniacld — APPROVED** [review]

**Comment by jrajahalme** [comment]
> Did you consider just adding the fake to `pkg/testutils` so we can avoid linking this logic into the runtime daemon?

No. AFAIK no-one, including the runtime daemon should depend on the explicit struct pointer type, but on the interface instead so that the iptables manager is mockable for all kinds of tests. The only change in the `daemon/cmd` is this:
```
 	Orchestrator        datapath.Orchestrator
-	IPTablesManager     *iptables.Manager
+	IPTablesManager     datapath.IptablesManager
```

And right there in the context `Orchestrator` was already defined via an interface in `pkg/datapath/types`.

I have to add that I'm not familiar at all with `pkg/testutils` and may be missing something obvious here!

**Review by sayboras — APPROVED** [review]

**Comment by jrajahalme** [comment]
CI images were no longer available, closed and reopened to force a rebuild.

**Comment by jrajahalme** [comment]
Image builds did not find `cilium-cli`, rebased to fix this.

**Comment by ldelossa** [comment]
@jrajahalme needs a rebase befoe this can be merged.

**Comment by jrajahalme** [comment]
Rebased to resolve merge conflict.

**Pull request merged**
