### PR TITLE
endpoint: Remove unnecessary endpoint lock on restore

### PR DESCRIPTION
**Pull request by tgraf**
The endpoint structure has just been restored from state and is not exposed in
any way yet so it is impossible to encounter a parallel writer or reader.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5883)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

* external connectivity failed

**Comment by tgraf** [comment]
test-me-please

* external connectivity failed

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Rebased

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — COMMENTED** [review]
Is the removal of this lock really important? I would prefer to keep it to avoid developer errors in the future. If we always lock / unlock variables, as we are supposed to do, we won't need to be aware where those variables are not required to be locked. I know you added the comment but what happens if in the future, for some other reason, we need to perform parallel operations for the same endpoint doing the restore? I'll defer the decision to @raybejjani

**Review by ianvernon — APPROVED** [review]

**Comment by raybejjani** [comment]
I'm with @aanm on this one. Even if we never end up in the situation where we have parallel access when restoring, the lock is not under contention and locking is nearly 0-time. If we don't lock it we're making an example of bad usage of the endpoint locks.

Was your thinking that we would forget to add the unlock on an error exit path? If so, then solving that is a little more complex because of `ep.SkipStateClean()`.

**Comment by tgraf** [comment]
@raybejjani @aanm I don't understand the logic. Are we starting to lock all variables on the stack going forward? The lock is being held through the IP allocation logic which may be blocking in the future. It will trigger warnings for long lock durations behind held.

Leaving locking code like this in is very confusing, why do we lock if it is not necessary? When I read code like this, I have to assume that the locking is required for something. Either the lock is completely hidden from the user and buried in accessor functions or it must be absolutely clear *why* a lock is being taken. The endpoint is on the stack, there is no chance anyone can use it in parallel.

**Comment by raybejjani** [comment]
ok. I think you feel more strongly than me about this so let's merge this.

**Comment by ianvernon** [comment]
@aanm are you OK with @tgraf 's justification?

**Comment by tgraf** [comment]
@raybejjani @aanm No. I think we should discuss this and the consistently do one pattern. This will be a cornerstone of quality and if we don't all have the same assumptions that will cause a lot of subtle bugs down the road. What are you proposing in terms of how to do the locking. We always lock a structure even if the structure is still on the stack?

**Comment by aanm** [comment]
>We always lock a structure even if the structure is still on the stack?

Yes, the lock serves to protect against concurrent access. If the lock exists we should make use of it. If the lock is not necessary then why is it there? All of the functions called that are wrapped by that lock clearly states:
```
// must be called with endpoint.Mutex held
```

or has the "Locked" suffix.

I don't like to make assumptions today because they will be wrong tomorrow, and I don't want to remember that there is a special place in the code where we don't use locks, it's one more thing that we can't forget when we will have to fix a bug in this section or add a new functionality in this section.

**Comment by tgraf** [comment]
> I don't like to make assumptions today because they will be wrong tomorrow, and I don't want to remember that there is a special place in the code where we don't use locks, it's one more thing that we can't forget when we will have to fix a bug in this section or add a new functionality in this section.

OK. I don't feel that strongly about this change so I'm fine to drop it. I think we all agree that we should avoid requiring knowledge about whether certain locks must be held or not so we should strive for that instead and limit locks to data accesses only.

**Pull request closed without merging**
