### PR TITLE
[v1.9] k8s: Update libraries to v1.19.6

### PR DESCRIPTION
**Pull request by christarazi**
This commit also updates the older K8s versions to their latest
(v1.18.14 and v1.17.16), as well as bumping the CI K8s version to
v1.19.6.

### CODE REVIEW

**Comment by christarazi** [comment]
test-backport-1.9

**Comment by aanm** [comment]
retest-gke

**Review by aanm — APPROVED** [review]

**Comment by christarazi** [comment]
retest-gke

**Comment by christarazi** [comment]
retest-net-next

**Pull request merged**
