### PR TITLE
v1.9 backports 2021-06-16

### PR DESCRIPTION
**Pull request by pchaigno**
* #14594 -- datapath: Do not use proxy original source address with tunneling (@jrajahalme)
 * #16084 -- Fix 5.10+ complexity issue with `kubeProxyReplacement=disabled` (@pchaigno)
     - Minor conflicts in bpf/*.h and bpf/Makefile files.
 * #16342 -- docs: Clarify LRP loop related note (@aditighag)
 * #16323 -- install: Allow setting enable-health-check-nodeport to 'false' (@dctrwatson)
 * #16231 -- test: Use new test-verifier image in K8sVerifier (@pchaigno)
     - Minor conflicts on new image.
 * #16118 -- daemon: Improve logging of device auto-detection (@brb)
 * #16016 -- Clarify one-time setup for backporting (@christarazi)
 * #16432 -- node: fix arpping test (@jibi)
 * #16408 -- docs: add a "Copy Commands" button for shell-session snippets (@qmonnet)
 * #16186 -- docs: ENIs should not be managed by the OS (@gandro)
 * #16506 -- ci: restart portmap service on CI nodes (@nebril)
 * #16535 -- docs: Hubble UI does not show HTTP endpoints anymore (@gandro)

Skipped:

 * #16307 -- k8s, node: Restore router IPs (cilium_host) from K8s resource  (@christarazi)
     - Conflict were minor but build was then failing due to missing `LocalRouterIPv{4,6}`.
 * #16238 -- docs: add a reference of helm values (@bmcustodio)
     - Sent fix to improve commit correlation at https://github.com/cilium/cilium/pull/16572.
 * #16190 -- pkg/k8s: add pod IP event change (@aanm)
     - Minor conflicts, resolved by @nathanjsweet 
     - Skipped because it was causing CI failures: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.15-kernel-4.9/285/.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14594 16084 16342 16323 16231 16118 16016 16432 16408 16186 16506 16535; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by pchaigno** [comment]
test-backport-1.9

**Review by aanm — APPROVED** [review]
Looks good for my commit. Thanks

**Review by jibi — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Review by brb — APPROVED** [review]
LGTM for my changes, thanks.

**Review by nebril — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]
> #16408 -- docs: add a "Copy Commands" button for shell-session snippets (@qmonnet)

Looks good. Kind of. I mean, it's JavaScript, it can't look _that_ good. But backport is OK.

**Comment by pchaigno** [comment]
test-backport-1.9

**Comment by pchaigno** [comment]
Switching to draft while I debug the L7 and Hubble tests consistently failing...

**Comment by pchaigno** [comment]
test-1.15-4.9

**Comment by pchaigno** [comment]
test-1.15-4.9

**Comment by pchaigno** [comment]
test-backport-1.9

**Comment by pchaigno** [comment]
test-1.16-4.9

**Comment by pchaigno** [comment]
test-1.12-netnext

**Comment by pchaigno** [comment]
test-1.12-netnext

**Comment by pchaigno** [comment]
test-1.12-netnext

**Comment by pchaigno** [comment]
k8s-1.17-kernel-5.4 is failing because of https://github.com/cilium/cilium/issues/16050. The two missing reviews are on backports that didn't have any conflicts at all. Marking as ready to merge.

**Pull request merged**
