### PR TITLE
v1.7 backports 2020-05-08

### PR DESCRIPTION
**Pull request by christarazi**
* #10175 -- docs: de-duplicate AWS cluster scale up instructions (@tklauser)
 * #10461 -- doc: Update EKS documentation to delete aws-node (@errordeveloper)
 * #10581 -- set explicit liveness/readiness probe timeout for deny connectivity checks (@danwent)
 * #10854 -- Docs policy title rename (@danwent)
 * #11208 -- Refactor enirouting package to reduce code interdependence and add test coverage (@christarazi)
 * #11068 -- Docs:  Update EKS GSG to clarify deployment in ENI vs. overlay mode (@danwent)
 * #11163 -- Clean up stale ENI rules upon endpoint deletion (@christarazi)
 * #11271 -- doc: Fix the kubectl create option in upgrade.rst (@soumynathan)
 * #11343 -- docs: clarify recommendation around managing multiple policy types (@genbit)
 * #11349 -- envoy: Reduce logging verbosity. (@jrajahalme)
 * #11203 -- Fixes cilium-agent helm chart so the daemonset can be configured with… (@seanmwinn)
 * #11410 -- BPF: fix missing "break" in nat46 switch, and minor cleanup (@qmonnet)
   * Note: Skipping 03a17552b781ce9c1341f830f2a65744f7e06e72 of this PR b/c it doesn't apply cleanly, but it's called out as superfluous in the original PR. 
   * Also, needed to squash bpf.sha update in this
 * #11157 -- docs: Cilium multi-node (and mesh) Kind Guide (@dctrwatson)
   * Note: Depended on #10163 
 * #10163 -- Use GO_VERSION as single source for the used Go version (@tklauser)
   * ~~Note: Dropped 771aa8ac6d27d013948bf77d216957566e940482 as it wasn't needed for backporting; no functionality or behavior is lost~~
   * Re-added dropped commit, and added the changes from `make update-golang` as well
 * #11328 -- Validate when Cilium is in ENI mode that IPv4 is enabled (@soumynathan)

*Skipping due to non-trivial conflicts*:

 * #11240 -- pkg/k8s: add missing support for multi-stack (@aanm)
 * #11282 -- k8s/watchers: do not consider pods with empty podIPs (@aanm)

*Causing build failures*:

 * #11269 -- Improve Helm post-setup NOTES (@soumynathan)

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.12-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:384
Cilium cannot be installed
Expected
    <*helpers.cmdError | 0xc00042b0a0>: Unable to generate YAML (%!s(<nil>)) output: cmd: helm template /home/vagrant/go/src/github.com/cilium/cilium/install/kubernetes/cilium --namespace=kube-system  --set global.debug.enabled=true  --set preflight.image=cilium-dev  --set global.pprof.enabled=true  --set agent.image=cilium-dev  --set operator.image=operator  --set global.ipv6.enabled=true  --set managed-etcd.registry=docker.io/cilium  --set global.logSystemLoad=true  --set global.k8s.requireIPv4PodCIDR=true  --set global.bpf.preallocateMaps=true  --set global.registry=147.75.199.49/cilium  --set global.etcd.leaseTTL=30s  --set global.ipv4.enabled=true  --set global.tag=latest  > cilium-160d36c2f8212ef6.yaml
Exitcode: 1 
Stdout:
 	 
Stderr:
 	 Error: error unpacking hubble-ui in cilium: validation: chart.metadata is required
	 

to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.12-gopath/src/github.com/cilium/cilium/test/k8sT/assertionHelpers.go:98
```

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3083/testReport/junit/Suite-k8s-1/12/K8sChaosTest_Connectivity_demo_application_Endpoint_can_still_connect_while_Cilium_is_not_running/

---

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10175 10461 10581 10854 11208 11068 11163 11271 11343 11349 11203 11410 11157 10163 11328; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by christarazi** [comment]
never-tell-me-the-odds

**Comment by christarazi** [comment]
@aanm Could you please take a look at the PRs of yours that had non-trivial conflicts?

**Comment by christarazi** [comment]
@qmonnet  Could you please take a look at the PR of yours that did not apply cleanly?

**Comment by christarazi** [comment]
never-tell-me-the-odds

**Comment by christarazi** [comment]
test-upstream-k8s

**Review by tklauser — APPROVED** [review]
LGTM for my change (#10175). I assume its backport is needed because other doc changes depend on it?

**Comment by qmonnet** [comment]
> #11410 -- BPF: fix missing "break" in nat46 switch, and minor cleanup (@qmonnet)
> 
>     * Second commit of this PR doesn't apply cleanly

In PR comments I referred to the _second_ commit _in git history_, but GitHub shows it first in the PR (because I wrote it first then reordered the commits before creating the PR). Could you please double check you tried the correct one? Commit to backport is [this one](https://github.com/cilium/cilium/pull/11410/commits/2e3f193bc5a614ce3dc5984af3382e6c5de86d55), and the surrounding code had not been touched in a while so I would expect it to apply cleanly.

**Comment by christarazi** [comment]
> > #11410 -- BPF: fix missing "break" in nat46 switch, and minor cleanup (@qmonnet)
> > ```
> > * Second commit of this PR doesn't apply cleanly
> > ```
> 
> In PR comments I referred to the _second_ commit _in git history_, but GitHub shows it first in the PR (because I wrote it first then reordered the commits before creating the PR). Could you please double check you tried the correct one? Commit to backport is [this one](https://github.com/cilium/cilium/pull/11410/commits/2e3f193bc5a614ce3dc5984af3382e6c5de86d55), and the surrounding code had not been touched in a while so I would expect it to apply cleanly.

The commit that didn't apply was 03a17552b781ce9c1341f830f2a65744f7e06e72. I will try again and let you know if I have trouble.

**Review by qmonnet — APPROVED** [review]
Looks good for the commit I did in #11410 and discussed above, thank you :+1:

**Comment by christarazi** [comment]
never-tell-me-the-odds

**Comment by christarazi** [comment]
@tklauser Please have another look, as I needed to backport another one of your PRs (#10163). Please see the top post for any additional context.

**Comment by christarazi** [comment]
restart-ginkgo

**Review by gandro — APPROVED** [review]
Looks good to me! 

With regard to the failed backport of #11269, I left a comment about it here: https://github.com/cilium/cilium/pull/11269#issuecomment-627187243 

But let's do that in the next batch of backports, this PR is already large enough as is.

**Comment by tklauser** [comment]
> #10163 -- Use GO_VERSION as single source for the used Go version (@tklauser)
> 
>     * Note: Dropped [771aa8a](https://github.com/cilium/cilium/commit/771aa8ac6d27d013948bf77d216957566e940482) as it wasn't needed for backporting; no functionality or behavior is lost

Dropping this commit will lead to inconsistencies when bumping Go version on the `v1.7` branch using `make update-golang`. We need to bump it in `GO_VERSION` and still manually bump it in `test/kubernetes-test.sh` because the curl/tar commands still use the hardcoded version.

I noted that `GO_VERSION` currently has 1.13.10, while `test/kubernetes-test.sh` has 1.3.9 in the curl/tar commands, so it's inconsistent already.

If there is no strong reason against it, I'd propose to pick up 771aa8ac6d27d013948bf77d216957566e940482 in a future backport PR (in order not to delay this backport PR further).

**Review by tklauser — APPROVED** [review]
~Approving despite one minor issue wrt. Go version update due to the dropped commit as pointed out in https://github.com/cilium/cilium/pull/11441#issuecomment-627241611 Hopefully we can address this in a future backport PR.~

**Review by tklauser — CHANGES_REQUESTED** [review]
Reverting my approval after discussion with @gandro. It's likely we forget to backport the single commit 771aa8ac6d27d013948bf77d216957566e940482 out of #10163, so better to include it as well in this PR.

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
Reviewed ENI related backports

**Comment by christarazi** [comment]
@tklauser Thanks for clearing that up! I've re-added the commit and ran the `make update-golang` and added those changes. Let me know if I've missed anything.

**Comment by christarazi** [comment]
never-tell-me-the-odds

**Review by tklauser — APPROVED** [review]
LGTM, thanks.

**Comment by christarazi** [comment]
test-upstream-k8s

**Comment by christarazi** [comment]
test-missed-k8s

**Comment by gandro** [comment]
test-missed-k8s

**Comment by gandro** [comment]
test-missed-k8s

**Pull request merged**
