### PR TITLE
v1.7 backports 2020-07-22

### PR DESCRIPTION
**Pull request by jrfastab**
* #12440 -- Fix small CRD issue with toGroups (@lbernail)
 * #12517 -- Adds documentation for limiting identity-relevant labels used when evaluating Cilium Identities (@seanmwinn)
 * #12605 -- etcd: Fix several etcd related issues (@tgraf)

Backport notes:
 #12440 -- ./pkg/apis/cilium.io/v2/client/register.go is here ./pkg/apis/cilium.io/v2/register.go otherwise applied cleanly
 #12517 -- concepts/scalability/index.rst does not exist so I put the identity-relevant-labels.rst in the getting started index
 #12605 -- added 12605 to get going in the pipeline, it applied cleanly.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12440 12517 12605; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by jrfastab** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
@seanmwinn Since your PR https://github.com/cilium/cilium/pull/12517 has been marked for 1.6 and 1.7 backport, please review the doc change, as the doc structure has changed since 1.6/1.7.

**Review by aanm — APPROVED** [review]

**Comment by pchaigno** [comment]
Labels for the two PRs had not been updated. I just updated them.

**Comment by jrfastab** [comment]
test-backport-1.7

**Comment by jrfastab** [comment]
test-backport-1.7

**Review by pchaigno — APPROVED** [review]

**Pull request merged**
