### PR TITLE
[v1.14] cilium: Fix 16bit ifindex limitation

### PR DESCRIPTION
**Pull request by borkmann**
Backport of:
- https://github.com/cilium/cilium/pull/27622
- https://github.com/cilium/cilium/pull/27528

### CODE REVIEW

**Comment by borkmann** [comment]
/test-backport-1.14

**Comment by julianwiedmann** [comment]
Maybe just grab https://github.com/cilium/cilium/pull/27528 as well, to align things with upstream?

**Comment by borkmann** [comment]
> Maybe just grab #27528 as well, to align things with upstream?

Good point, will include it! Thanks!

**Comment by borkmann** [comment]
/test-backport-1.14

**Review by julianwiedmann — APPROVED** [review]
:ship:

**Pull request merged**
