### PR TITLE
pkg/endpoint: update scopeLog in controller

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5180)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]
ah, I forgot about this from last week

**Comment by aanm** [comment]
@raybejjani I had this on my git stash in case any of us would forgot.

**Comment by raybejjani** [comment]
Ha, usually I don't label my stash entries well, so I get confused, and then clear it all out :/

**Pull request merged**
