### PR TITLE
Remove references for old k8s version from tests

### PR DESCRIPTION
**Pull request by fristonio**

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by fristonio** [comment]
test-me-please

**Review by kaworu — APPROVED** [review]

**Comment by fristonio** [comment]
retest-net-next

**Comment by fristonio** [comment]
retest-gke

**Comment by fristonio** [comment]
retest-4.9

**Comment by fristonio** [comment]
Runtime tests failure is unrelated to the changes in the PR and is tracked in #14125

**Review by christarazi — APPROVED** [review]
:rocket:

**Pull request merged**
