### PR TITLE
Backport 1.5 2019 06 13

### PR DESCRIPTION
**Pull request by raybejjani**
* PR: 8228 -- test: have timeout for `Exec` (@ianvernon) -- https://github.com/cilium/cilium/pull/8228
 * PR: 8147 -- test/provision: upgrade k8s 1.15 to 1.15.0-beta.2 (@aanm) -- https://github.com/cilium/cilium/pull/8147
 * PR: 8248 -- test: bump to k8s 1.14.3 (@aanm) -- https://github.com/cilium/cilium/pull/8248
 * PR: 8264 -- test: create session and run commands asynchronously (@ianvernon) -- https://github.com/cilium/cilium/pull/8264
 * PR: 8271 -- k8s: Fix policies with multiple From/To selectors (@gandro) -- https://github.com/cilium/cilium/pull/8271
 * PR: 8262 -- test: use context with timeout to ensure that Cilium log gathering takes <= 5 minutes (@ianvernon) -- https://github.com/cilium/cilium/pull/8262
 * PR: 7869 -- pkg/health: Fix IPv6 URL format in HTTP probe (@iffyio) -- https://github.com/cilium/cilium/pull/7869
 * PR: 8290 -- Preload vagrant boxes in k8s upstream jenkinsfile (@nebril) -- https://github.com/cilium/cilium/pull/8290

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8291)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-docs-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-missed-k8s

**Comment by raybejjani** [comment]
test-upstream-k8s

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-docs-please

**Comment by raybejjani** [comment]
test-missed-k8s

**Comment by raybejjani** [comment]
test-upstream-k8s

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
