### PR TITLE
v1.11 Backports 2023-06-22

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #25969 (@jrajahalme)
 * [x] #25908 (@jrajahalme)
 * [ ] #26092 (@peterj)
 * [ ] #26180 (@wedaly)
 * [x] #26130 (@brb)
 * [x] #26113 (@jschwinger233)
 * [ ] #26278 (@joestringer)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 25969 25908 26092 26180 26130 26113 26278; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
make add-labels BRANCH=v1.11 ISSUES=25969,25908,26092,26180,26130,26113,26278
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
@jrajahalme @qmonnet @brb Conflicts arised during backport of your commits, please check the notes in commits for context and validate that it looks good to you :)

**Comment by nbusseneau** [comment]
/test-backport-1.11

**Review by brb — APPROVED** [review]
Thanks!

**Comment by nbusseneau** [comment]
/test-1.16-netnext

**Comment by nbusseneau** [comment]
/test-1.17-4.9

**Comment by nbusseneau** [comment]
/test-1.21-4.9

**Review by jschwinger233 — APPROVED** [review]

**Comment by nbusseneau** [comment]
The GKE failures are expected due to 1.11 not supporting K8s 1.24. This is caused by an infrastructure setup conundrum and will be addressed as part of infrastructure rework items this week (not feasible to simply rollback, unfortunately). In the meantime, we should ignore these failures on 1.11.

**Review by jrajahalme — APPROVED** [review]
Looks good to my PRs :)

**Pull request merged**
