### PR TITLE
kubernetes-upstream: update to k8s 1.14

### LINKED ISSUE #6386: Change k8s upstream tests to 1.13
The k8s upstream tests are currently broken upstream. We should bump the version to k8s 1.13 once the tests are fixed.

https://github.com/kubernetes/kubernetes/issues/71728

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

Lets see if the tests are fixed upstream.

Fixes https://github.com/cilium/cilium/issues/6386

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7663)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
