### PR TITLE
Fix bug where traffic from a host to a service IP was classified as from the world, not from the host

### LINKED ISSUE #4715: CI: A connection from the host to a ServiceIP is shown as entity "world"
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4629/testReport/junit/k8s-1/7/K8sValidatedServicesTest_Checks_ClusterIP_Connectivity_Checks_service_on_same_node/

```
time="2018-07-03T01:34:57Z" level=debug msg="running command: curl http://10.96.108.241/"
cmd: "curl http://10.96.108.241/" exitCode: 7 stdout:

stderr:
  %!T(MISSING)otal    %!R(MISSING)eceived %!X(MISSING)ferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
...
  0     0    0     0    0     0      0      0 --:--:--  0:02:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:02:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:02:07 --:--:--     0curl: (7) Failed to connect to 10.96.108.241 port 80: Connection timed out
```

output from microscope
```
k8s1: <- host flow 0x487d092e identity 2->0 state new ifindex 0: 10.10.0.1:33930 -> 10.10.0.47:80 tcp SYN

k8s2: -> endpoint 21004 flow 0x1544162c identity 2->17031 state reply ifindex lxcdcff8: 10.96.0.1:443 -> 10.10.1.70:39020 tcp ACK
k8s1: xx drop (Policy denied (L3)) flow 0x487d092e to endpoint 53544, identity 2->30517: 10.10.0.1:33930 -> 10.10.0.47:80 tcp SYN
```

policy for the `10.10.0.47` endpoint
```
"realized": {
          "allowed-egress-identities": [
            17031,
            39258,
            9739,
            51755,
            51081,
            25658,
            5,
            30517,
            23477,
            3,
            28564,
            1,
            4,
            2
          ],
          "allowed-ingress-identities": [
            1
          ],
```

[9acb0442_K8sValidatedServicesTest_Checks_ClusterIP_Connectivity_Checks_service_on_same_node.zip](https://github.com/cilium/cilium/files/2157761/9acb0442_K8sValidatedServicesTest_Checks_ClusterIP_Connectivity_Checks_service_on_same_node.zip)

### PR DESCRIPTION
**Pull request by joestringer**
Originally we set this mark only for traffic destined to the
cilium_host device, to ensure that any traffic directly reaching
to a Cilium-managed IP could be classified as from the host.

However, there's another case where a local process attempts to
reach a service IP which is backed by a Cilium-managed pod. The
service implementation is outside of Cilium's control, for example,
handled by kube-proxy. We can tag even this traffic with a magic
mark, then when the service implementation proxies it back into
Cilium the BPF will see this mark and understand that the packet
originated from the host.

Fixes: #4715

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4830)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
LGTM

**Comment by joestringer** [comment]
I validated locally that it makes the service traffic appear appropriately as from the host instead of from the world. The k8s tests are passing. Not sure that there's any other more specific test I can make.

**Comment by joestringer** [comment]
There is some loss of operations on Github, which is a likely cause for Hound starting to complain now.

I've also proposed this for 1.1 backport as it would affect that branch.

**Pull request merged**
