### PR TITLE
[v1.13] bpf: lxc: support Pod->Service->Pod hairpinning with endpoint routes

### PR DESCRIPTION
**Pull request by qmonnet**
- [ ] https://github.com/cilium/cilium/pull/27798 (@ti-mo)
- [x] https://github.com/cilium/cilium/pull/27602 (@julianwiedmann)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 27602 27798; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=27602,27798
```

### CODE REVIEW

**Comment by qmonnet** [comment]
/test-backport-1.13

**Comment by qmonnet** [comment]
/test-backport-1.13

**Comment by qmonnet** [comment]
/test-backport-1.13

**Review by julianwiedmann — APPROVED** [review]
:rocket: thank you!

**Review by michi-covalent — APPROVED** [review]
should we wait for @ti-mo to review this as well?

**Comment by qmonnet** [comment]
> should we wait for [@]ti-mo to review this as well?

This is not necessary, he's out of office and I've written most of the code in this commit anyway.

**Pull request merged**
