### PR TITLE
v1.12 backports 2022-08-10

### PR DESCRIPTION
**Pull request by nbusseneau**
* #20617 -- ci: pick up cilium-cli v0.12.0 for master, v1.11 and v1.12 workflows (@tklauser)
 * #20605 -- Doc: Clarify CentOS 7 kernel upgrade and Cilium advance features (@vincentmli)
 * #20609 -- ENI: Trigger NodeManager.Resync immediately after new ENI successfully created (@wu0407)
 * #20643 -- helm: Guard apply sysctl init container (@sayboras)
 * #20610 -- helm: Set KPR default to "disabled" for >= 1.12 (@brb)
 * #20638 -- Remove check on intSlice type from config map validation (@pippolo84)
 * #20260 -- docs: Update clustermesh troubleshooting with more details (@sayboras)
 * #20630 -- cilium-cni: delegated IPAM DEL even when netns does not exist (@wedaly)
 * #20673 -- command: fix parsing of string map strings with multiple separators (@tklauser)
 * #20669 -- docs: update the version specific notes table for v1.12 release (@tklauser)
 * #20697 -- clustermesh: Add EndpointSlice support for API server (@YutaroHayakawa)
 * #20685 -- ci: fix code changes detection on `push` events (@nbusseneau)
 * #20680 -- iptables: handle case where kernel IPv6 support is disabled (@jibi)
 * #20449 -- fix subnet_id label value is empty (@wu0407)
 * #20572 -- ui: release v0.9.1 (@geakstr)
 * #20674 -- cilium-cni: don't set interface link up twice (@tklauser)
 * #20703 -- docs: Add required ec2:DescribeInstances when instance-tags-filter is used (@lht)
 * #20716 -- docs: Update Helm values (@qmonnet)
 * #20744 -- Revert "Revert "doc: update the api spec for fqdn egress policies cod… (@aanm)
 * #20752 -- fqdn/metrics: Fix ProxyUpstreamTime error=timeout (@joestringer)
 * #20741 -- Fix ineffective post-start hook in ENI mode (@bmcustodio)
 * #20757 -- pkg/k8s: set the right IP addresses in log messages (@aanm)
 * #20750 -- Consider `$GO` environment variable `make precheck` checks (@tklauser)
 * #20479 -- bpf: Add send_trace_notify hook for redirect_direct_{v4,v6} (@qmonnet)
 * #20758 -- docs: correct IPAM mode name in BGP control plane installation docs (@tklauser)
 * #20771 -- envoy: Bump envoy version to 1.21.5 (@sayboras)
 * #20721 -- Improve dnsproxy ipcache handling, metrics (@joestringer)
 * #20831 -- fix k8s latency metrics label cardinality (@aanm)
 * #20648 -- maglev: Don't populate v4 inner table upon nat46 service (@borkmann)
 * #20833 -- ipcache: Fix lock leak (@joestringer)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20617 20605 20609 20643 20610 20638 20260 20630 20673 20669 20697 20685 20680 20449 20572 20674 20703 20716 20744 20752 20741 20757 20750 20479 20758 20771 20721 20831 20648 20833; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Looks good for my commit :100:

**Comment by nbusseneau** [comment]
/test-backport-1.12

**Review by aanm — APPROVED** [review]
My commits look good, thanks

**Review by tklauser — APPROVED** [review]
Looks good for my changes, thanks.

**Review by pippolo84 — APPROVED** [review]
LGTM for my changes :+1:

**Comment by nbusseneau** [comment]
1.18 / 4.9 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.18-kernel-4.9/2162/ hit #20288. Restarting just to confirm.

**Comment by nbusseneau** [comment]
/test-1.18-4.9

**Comment by nbusseneau** [comment]
1.16 / 4.9 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/2302/ hit #16847. Restarting just to check.

**Comment by nbusseneau** [comment]
/test-1.16-4.9

**Review by geakstr — APPROVED** [review]

**Comment by geakstr** [comment]
My commit looks good, thanks

**Comment by nbusseneau** [comment]
L4LB tests https://github.com/cilium/cilium/actions/runs/2832287202 failed with a known issue that's addressed by #20682 and #20834.

**Review by michi-covalent — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]
> #20716 -- docs: Update Helm values (@qmonnet)
> #20479 -- bpf: Add send_trace_notify hook for redirect_direct_{v4,v6} (@qmonnet)

Look good, thank you!

**Comment by nbusseneau** [comment]
GKE hit #16122 with exit code 28.

**Comment by nbusseneau** [comment]
@brb @borkmann There were conflicts while handling your backports, please check the commit notes for more details.

**Review by borkmann — APPROVED** [review]

**Review by brb — APPROVED** [review]
My changes LGTM, thanks.

**Comment by tklauser** [comment]
Approvals are in, namely for backports that needed special attention due to conflicts. All remaining test failures have been triaged and are either known flakes (GKE) or will be followed up on (L4LB). Merging this PR.

**Pull request merged**
