### PR TITLE
[v1.15] golangci: Enable errorlint

### PR DESCRIPTION
**Pull request by jrajahalme**
* [ ] #31458 (@jrajahalme)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31458
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.15

**Review by learnitall — APPROVED** [review]
Thanks!

**Review by glibsm — APPROVED** [review]

**Comment by jrajahalme** [comment]
rebased & resolved conflicts

**Comment by jrajahalme** [comment]
/test-backport-1.15

**Review by michi-covalent — APPROVED** [review]

**Review by aditighag — APPROVED** [review]

**Pull request merged**
