### PR TITLE
Bump Go version to 1.11.5

### PR DESCRIPTION
**Pull request by brb**
Golang release notes: https://golang.org/doc/devel/release.html#go1.11.minor.

Depends on #7162 (merged).

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7163)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by aanm** [comment]
@brb please add this patch

```patch
diff --git a/Dockerfile b/Dockerfile
index 4e64fc6f6..017b9674e 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -13,7 +13,7 @@ FROM quay.io/cilium/cilium-envoy:84ee839e1d78ef858a39e390288ad417d35bb1d4 as cil
 # versions to be built while allowing the new versions to make changes
 # that are not backwards compatible.
 #
-FROM quay.io/cilium/cilium-builder:2019-02-19 as builder
+FROM quay.io/cilium/cilium-builder:2019-02-25 as builder
 LABEL maintainer="maintainer@cilium.io"
 WORKDIR /go/src/github.com/cilium/cilium
 COPY . ./
@@ -37,7 +37,7 @@ RUN make LOCKDEBUG=$LOCKDEBUG PKG_BUILD=1 V=$V LIBNETWORK_PLUGIN=$LIBNETWORK_PLU
 # built while allowing the new versions to make changes that are not
 # backwards compatible.
 #
-FROM quay.io/cilium/cilium-runtime:2019-02-20
+FROM quay.io/cilium/cilium-runtime:2019-02-25
 LABEL maintainer="maintainer@cilium.io"
 COPY --from=builder /tmp/install /
 COPY --from=cilium-envoy / /
diff --git a/contrib/packaging/docker/Dockerfile.runtime b/contrib/packaging/docker/Dockerfile.runtime
index 3d6961920..b7616bace 100644
--- a/contrib/packaging/docker/Dockerfile.runtime
+++ b/contrib/packaging/docker/Dockerfile.runtime
@@ -78,7 +78,7 @@ apt-get clean
 #
 # Go-based tools we need at runtime
 #
-FROM golang:1.11.1 as runtime-gobuild
+FROM golang:1.11.5 as runtime-gobuild
 WORKDIR /tmp
 RUN go get -u github.com/cilium/go-bindata/... && \
 go get -u github.com/google/gops && \
diff --git a/test/docker-compose.yml b/test/docker-compose.yml
index 438d38ad0..dd626d82b 100644
--- a/test/docker-compose.yml
+++ b/test/docker-compose.yml
@@ -15,7 +15,7 @@ services:
     command: "etcd -name etcd0 -advertise-client-urls http://0.0.0.0:4002 -listen-client-urls http://0.0.0.0:4002 -initial-cluster-token etcd-cluster-1 -initial-cluster-state new"
     privileged: true
   base_image:
-    image: "quay.io/cilium/cilium-builder:2019-02-19"
+    image: "quay.io/cilium/cilium-builder:2019-02-25"
     volumes:
       - "./../:/go/src/github.com/cilium/cilium/"
     privileged: true
```

**Comment by aanm** [comment]
test-me-please hit https://github.com/cilium/cilium/issues/7126

**Review by aanm — APPROVED** [review]

**Pull request merged**
