### PR TITLE
[v1.15] re-introduce ICMPv6 NS responder on from-netdev

### PR DESCRIPTION
**Pull request by jschwinger233**
- [x] https://github.com/cilium/cilium/pull/30837  @jschwinger233 
- [x] https://github.com/cilium/cilium/pull/31127 @julianwiedmann 

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
30837 31127
```

### CODE REVIEW

**Comment by jschwinger233** [comment]
/test-backport-1.15

**Comment by jschwinger233** [comment]
/test-backport-1.15

**Review by julianwiedmann — APPROVED** [review]
lgtm, ty Gray!

**Review by joestringer — APPROVED** [review]
Deferring to Julian's ack as tophat.

**Pull request merged**
