### PR TITLE
vagrant: update 4.19 and net-next VM images

### PR DESCRIPTION
**Pull request by nbusseneau**
We have been hitting issues in our CI since yesterday on all `master` scheduled pipelines as well as `master`-based PR pipelines, with Cilium Agent seemingly being unable to reach a healthy state due to IPv6-related issues (see [1] and [2] below).

I have a hunch the issue is due to the Vagrant VMs themselves, as we do not seem to hit the issue anymore on 4.9- and 5.4-based pipelines after merging an update to their Vagrant VMs in 35625206ea02aa816cd81f012cc86df052d90694, containing an unrelated fix.

This commit bumps the 4.19 and net-next VM images as well.

[1]

```
2022-01-13T05:42:17.179701398Z level=debug msg="Greeting failed" error="Get \"http://[fd04::12]:4240/hello\": dial tcp [fd04::12]:4240: connect: network is unreachable" host="http://[fd04::12]:4240" ipAddr="fd04::12" nodeName=k8s2 path="Via L3" subsys=health-server
2022-01-13T05:42:17.179730123Z level=debug msg="Failed to probe: Get \"http://[fd04::12]:4240/hello\": dial tcp [fd04::12]:4240: connect: network is unreachable" ipAddr="fd04::12" nodeName=k8s2 port=4240 subsys=health-server
```

[2]

```
2022-01-14T12:12:52.181387748Z level=fatal msg="Error while creating daemon" error="failed to finalise LB initialization: failed to initialize NodePort addrs. : Failed to determine IPv6 of enp0s3 for NodePort" subsys=daemon
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-1.22-4.19

**Comment by nbusseneau** [comment]
/test-1.23-net-next

**Comment by nbusseneau** [comment]
/test-1.23-net-next

**Comment by nbusseneau** [comment]
/test-1.23-net-next

**Comment by nbusseneau** [comment]
/test-1.23-net-next

**Comment by nbusseneau** [comment]
I still have no idea why it works but both 4.19 and net-next tests are passing.

**Review by pchaigno — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
The change itself LGTM, but I think the PR bumping the Vagrant VMs needs to be created from a branch named `pr/update-packer-ci-build` on the `github.com/cilium/cilium` repo (per https://docs.cilium.io/en/v1.11/contributing/testing/ci/#packer-ci-build) so the images get cached properly.

**Comment by nbusseneau** [comment]
@tklauser Thanks, I didn't know about that xD

Will re-open.

**Comment by nbusseneau** [comment]
Closing in favor of #18496.

**Pull request closed without merging**
