### PR TITLE
CI Fixups to target other runtimes

### PR DESCRIPTION
**Pull request by raybejjani**
This PR allows running the CI against non-jenkins clusters. It's still WIP but everyone should try it out and let me know how it doesn't work.

ginkgo now honours environment variables to set the image sources to test with, and has an option to pass the environment to subprocesses.

**Relevant config**
`CILIUM_IMAGE` & `CILIUM_OPERATOR_IMAGE` set the images to use. I recommend using a fully qualified image name with tag here.
Internally, there are also `CILIUM_REGISTRY` and `CILIUM_TAG` variables but our helm templating treats any `CILIUM_IMAGE` with a `/` in it as a fully image path (which is always the case since it would be `cilium/cilium`).

`-cilium.provision=false` stops ginkgo from provisioning the CI VMs.

`-cilium.kubeconfig=/my/kube/config` will use this kubeconfig. It will honour the selected cluster. It also supports authentication schemes such as aws-authenticator that may be needed

`-cilium.passCLIEnvironment=true` Passes along the environment when invoking kubectl. This is needed when kubectl invokes other programs to do things, like authentication. This is the case with eks.

**Example invocation**
ginkgo expects to be run from the cilium/test directory
`CILIUM_IMAGE="docker.io/cilium/cilium:latest" CILIUM_OPERATOR_IMAGE="docker.io/cilium/operator:latest" K8S_VERSION=1.15  ginkgo -v --focus="K8sDemosTest*" -noColor -- -cilium.provision=false -cilium.kubeconfig=/Users/ray/.kube/config -cilium.passCLIEnvironment=true`

**Specific targets**
Minikube
1- Start minikube as in https://cilium.readthedocs.io/en/latest/gettingstarted/minikube/. You can skip installing cilium and the connectivity check.

2- [temp until we find a solution] Edit `test/helpers/kubectl.go` with
```
diff --git a/test/helpers/kubectl.go b/test/helpers/kubectl.go
index e18f56d35..30bcba1af 100644
--- a/test/helpers/kubectl.go
+++ b/test/helpers/kubectl.go
@@ -86,3 +86,3 @@ var (
                "global.debug.enabled":          "true",
-               "global.k8s.requireIPv4PodCIDR": "true",
+               "global.k8s.requireIPv4PodCIDR": "false",
                "global.pprof.enabled":          "true",
```

3- in cilium/test `CILIUM_IMAGE="docker.io/cilium/cilium:latest" CILIUM_OPERATOR_IMAGE="docker.io/cilium/operator:latest" K8S_VERSION=1.15  ginkgo -v --focus="K8sDemosTest*" -noColor -- -cilium.provision=false -cilium.kubeconfig=/my/kubeconfig -cilium.passCLIEnvironment=true`

EKS
1- Follow our getting started guide at https://cilium.readthedocs.io/en/latest/gettingstarted/k8s-install-eks/ to get your tooling working and scale a cluster up. I've successfully scaled the cluster before installing cilium, which the tests will install anyway. Skip the connectivity check.

2- [temp until I figure out something] Change the coredns manifest with the below diff. Adjust the 1.15 to your k8s version.
```
diff --git a/test/provision/manifest/1.15/coredns_deployment.yaml b/test/provision/manifest/1.15/coredns_deployment.yaml
index 4b09572e4..3c69e566a 100644
--- a/test/provision/manifest/1.15/coredns_deployment.yaml
+++ b/test/provision/manifest/1.15/coredns_deployment.yaml
@@ -73,7 +73,7 @@ data:
             upstream
             fallthrough in-addr.arpa ip6.arpa
         }
-        proxy cilium.test 10.96.0.100:53 {
+        proxy cilium.test 10.100.0.100:53 {
             fail_timeout 10s
             max_fails 0
         }
@@ -193,7 +193,7 @@ metadata:
 spec:
   selector:
     k8s-app: kube-dns
-  clusterIP: 10.96.0.10
+  clusterIP: 10.100.0.10
   ports:
   - name: dns
     port: 53
```
The eks clusters come up with a different range and coredns should, ideally just use that.

3- in cilium/test `CNI_INTEGRATION=eks CILIUM_IMAGE="docker.io/cilium/cilium:latest" CILIUM_OPERATOR_IMAGE="docker.io/cilium/operator:latest" K8S_VERSION=1.15  ginkgo -v --focus="K8sDemosTest*" -noColor -- -cilium.provision=false -cilium.kubeconfig=/my/kubeconfig -cilium.passCLIEnvironment=true`

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9189)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-missing-k8s

**Comment by raybejjani** [comment]
test-nightly

**Comment by raybejjani** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Pull request merged**
