### PR TITLE
Fixing go vet related issues

### PR DESCRIPTION
**Pull request by aanm**
@tgraf Is the `common/tests/perf-event-test.go` still needed it?

Signed-off-by: André Martins andre@cilium.io

### CODE REVIEW

**Comment by tgraf** [comment]
`common/tests/perf-event-test.go` can be removed alltogether.

**Comment by tgraf** [comment]
LGTM. Feel free to also consider removing `common/tests/perf-event-test.go` as acked.

**Comment by aanm** [comment]
@tgraf The whole `common/tests` directory?

**Comment by tgraf** [comment]
On second thought. It provides for an isolated test scenario which is useful in itself. I'll fix up the tests.

**Pull request merged**
