### PR TITLE
doc: fixed broken gettingstarted link on helm chart

### PR DESCRIPTION
**Pull request by dotdc**
Signed-off-by: David Calvert <david@0xdc.me>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

This just fix the broken link in the [README.md](https://github.com/cilium/cilium/tree/master/install/kubernetes/cilium#getting-started) of Cilium Helm chart. 
Not creating an issue because this is a minor change.

```release-note
fixed broken gettingstarted link on helm chart README.md
```

### CODE REVIEW

**Comment by dotdc** [comment]
I guess this needs the `release-note/minor` label

**Review by nathanjsweet — APPROVED** [review]

**Review by kaworu — CHANGES_REQUESTED** [review]
Thanks @dotdc for the contribution! Patch LGTM, but [this CI failure](https://github.com/cilium/cilium/actions/runs/3483543776/jobs/5842535196) is legit:

> please run 'make -C install/kubernetes' and submit your changes

**Comment by dotdc** [comment]
Hi @kaworu,

I've just pushed a new commit with the compiled change in README.md, but the ouput from  `make -C install/kubernetes`  and `make -C install/kubernetes cilium/values.yaml` makes me think that this error is not related to this change.

Am I missing something?

**Comment by kaworu** [comment]
@dotdc thanks! The failure I linked previously is gone (Smoke test / helm-charts) as before the update the PR only updated the README template file (.gotmpl) and now it also update the README.md file.

Could you please squash all the commit into the first one please? :pray:

**Comment by dotdc** [comment]
> Could you please squash all the commit into the first one please? :pray:

Done :+1:

**Review by kaworu — APPROVED** [review]
@dotdc thanks!

**Comment by aanm** [comment]
@dotdc can you remove the "Merge" commit? Thank you

**Comment by dotdc** [comment]
Not sure what append there but forced push a new commit.
Labels got removed but otherwise it should be all good now @aanm.

**Pull request merged**
