### PR TITLE
clustermesh: drain all known entries upon cluster ID change

### PR DESCRIPTION
**Pull request by giorio94**
Recent changes (#32749, #32785) introduced improved validation to ensure that the information retrieved from remote clusters matches the advertised cluster ID, and discard it otherwise. Let's additionally fully drain all previously known entries upon cluster ID change. Indeed, although synthetic deletion events would be generated in any case upon initial listing (as the entries with the incorrect cluster ID would not pass validation), that would leave a window of time in which there would still be stale entries for a cluster ID that has already been released, potentially leading to inconsistencies if the same ID is acquired again in the meanwhile by a different cluster.

### CODE REVIEW

**Review by YutaroHayakawa — APPROVED** [review]

**Comment by giorio94** [comment]
Converting back to draft while I figure out the reason of the conformance runtime failure, which looks legitimate.

**Comment by giorio94** [comment]
> Converting back to draft while I figure out the reason of the conformance runtime failure, which looks legitimate.

I had accidentally removed `testutils.IntegrationTest(t)` from one of the tests. Should be good now.

**Pull request merged**
