### PR TITLE
Move from vendr to dep

### PR DESCRIPTION
**Pull request by aanm**
**Summary of changes**:
```
vendor.conf to golang/dep

* Kept all direct dependencies with the same version defined in the old
vendor.conf. For the containerd integration the following dependencies
will be prematurely updated:

- etcd library was updated to 3.2.20

* All transient dependencies were automatically delt by dep.
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4068)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Looks fine at face-value, I would like to see a few green builds in a row given that we are changing underlying dependencies though.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-nightly

**Review by ianvernon — APPROVED** [review]
Awesome!

**Review by joestringer — APPROVED** [review]
Using `git show upstream/master..upstream/pr/move-to-dep -- . ':!vendor'`, the diff looks pretty straightforward and I assume the rest is handled automatically by dep. I did observe several packages being updated to newer versions, so from a bisectability point of view this has higher risk than a pure tool switch. That said, the tests are all passing and assuming that the nightly tests aren't explicitly broken by this PR, this should be fine to go ahead and merge.

**Comment by aanm** [comment]
@joestringer the etcd was prematurely updated. I've kept all direct dependencies to be at the same version that were used with the previous vendor tool. All transient dependencies were taken care by dep.

**Pull request merged**
