### PR TITLE
v1.6 backports 2019-08-08

### PR DESCRIPTION
**Pull request by nebril**
* #8828 -- test: wait for k8s external service in [kube|core]-dns (@aanm)
 * #8825 -- operator: start health check handler after initializing k8s client (@aanm)
 * #8826 -- aws/eni: Fix race condition leading to overaggressive ENI allocation (@tgraf)
 * #8836 -- eventqueue: use mutex to synchronize access to events channel (@ianvernon)
 * #8831 -- doc: Document ENI installation (@tgraf)
 * #8807 -- cilium preflight identity migration (@raybejjani)
 * #8833 -- Added prometheus-operator ServiceMonitor (@dsexton)
 * #8839 -- datapath: Always include IP of cilium_host in list of local IPs (@tgraf)
 * #8845 -- doc: Create cilium namespace in GKE guide (@tgraf)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 8828 8825 8826 8836 8831 8807 8833 8839 8845; do contrib/backporting/set-labels.py $pr done 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8838)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
never-tell-me-the-odds

**Comment by nebril** [comment]
test-missed-k8s

**Review by tgraf — APPROVED** [review]

**Comment by nebril** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2328/

L7 NodePort test - issue is going to be fixed upstream by #8839.

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
I am going to pull in more backports (specifically the one which stabilizes the CI) into this PR.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14194/execution/node/151/log/?consoleFull

Failures are around kvstore not being ready, and kube-dns service not being found. I suspect the second one is a CI bug, and will triage. Running test again.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
It's unclear what the nature of the failure was in parts of this build: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14200/

Will triage, running again...

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
