### PR TITLE
Extend the check-ipsec-leak bpftrace script to capture additional details of leaked packets

### PR DESCRIPTION
**Pull request by giorio94**
We have been recently witnessing a few [conformance ipsec runs reporting leaked packets](https://github.com/cilium/cilium/issues/33084), with some referring to DNS answers from a coredns pod to a CiliumInternalIP. In order to simplify troubleshooting these issues, and figure out whether they are legitimate or flakes, let's additionally print whether the detected packet was encapsulated or not, and whether it matched a "trace_override". Moreover, let's output information about the DNS message itself, so that we can trace down which component performed the request. Similatly, let's also print the TCP flags.
    
The output is along the lines of:

```    
[15:54:36:823373] 10.244.1.188:57010 -> 10.244.2.76:53 (proto: 17, TCP flags: ...., encap: 1, ifindex: 53, netns: f0000000, override: 0)
[15:54:36:823373] Detected DNS message, ID: 4391, flags 0100, QD: 1, AN: 0, NS: 0, AR: 0, query podinfodefaultsvcclusterlocal
[15:54:36:823534] 10.244.2.76:53 -> 10.244.1.188:57010 (proto: 17, TCP flags: ...., encap: 1, ifindex: 49, netns: f0000000, override: 0)
[15:54:36:823536] Detected DNS message, ID: 4391, flags 8500, QD: 1, AN: 1, NS: 0, AR: 0, query podinfodefaultsvcclusterlocal
[15:54:36:823631] 10.244.2.76:53 -> 10.244.1.188:57010 (proto: 17, TCP flags: ...., encap: 1, ifindex: 49, netns: f0000000, override: 0)
[15:54:36:823632] Detected DNS message, ID: 42f7, flags 8500, QD: 1, AN: 1, NS: 0, AR: 0, query podinfodefaultsvcclusterlocal
[15:54:36:823767] fd00:10:244:1::eb5b:35708 -> fd00:10:244:2::b2fb:9898 (proto: 6, TCP flags: S..., encap: 1, ifindex: 53, netns: f0000000, override: 0)
[15:54:36:823811] fd00:10:244:2::b2fb:9898 -> fd00:10:244:1::eb5b:35708 (proto: 6, TCP flags: SA.., encap: 1, ifindex: 49, netns: f0000000, override: 0)
```

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Review by ldelossa — APPROVED** [review]
Thanks, should help.

**Review by ldelossa — COMMENTED** [review]
Should we also log whether `trace_override` is true or false in the ipv4/6 clauses?

**Comment by giorio94** [comment]
The last push adds the support for displaying whether the detected flow matched `trace_override`, as well as the TCP flags in case of TCP packets.

**Comment by ldelossa** [comment]
Looks great.

**Comment by giorio94** [comment]
Updated the last commit to use (sort of) character literals rather than strings, as otherwise hitting the stack limit.

**Review by christarazi — APPROVED** [review]

**Review by ldelossa — APPROVED** [review]

**Comment by giorio94** [comment]
:wave: @youngnick, any specific reason why you removed the ready to merge label?

Reviews are in, and all required tests are green. The two failing tests cannot be possibly related given that this PR only touches the bpftrace script used by ipsec-related workflows only.

Cilium E2E Upgrade: has been pretty flaky recently, and looks related to https://github.com/cilium/cilium/issues/32689
CiliumEndpointSlice migration: https://github.com/cilium/cilium/issues/33417 - Based on the occurrences on main, this would be likely fixed by a rebase on main. Considering that the test is not required, and cannot be possibly affected by this PR, I wouldn't trigger another CI run though.

**Comment by youngnick** [comment]
The current tophat guidance is to just rerun CI for failed tests, rather than bypassing the branch protections, which is why I removed ready-to-merge. I think that we should definitely clarify what the tophat is supposed to be doing here, and do a better job of communicating that to everybody.

Let me check with @aanm and @joestringer about this.

**Comment by giorio94** [comment]
> The current tophat guidance is to just rerun CI for failed tests, rather than bypassing the branch protections, which is why I removed ready-to-merge.

My understanding is that the re-run CI guidance applies to required tests. Yet, in this case, the only failing tests are not marked as required. If we are forced to re-run then, then what is the value of marking tests known to be flaky (or not yet shown to be stable) as non required?

Moreover:
* The `ready-to-merge` label was added by the bot, not by myself. Which means that the bot agrees that tests marked as non required are not required to merge a PR. If that's not the case, then the bot should be updated accordingly.
* AFICT, merging such PR does not require bypassing any protection, and could have been performed by any committer. Hence, this would also leave an inconsistency in terms of what committers could/should do, and external contributors (with the helm of the triager) could/should do. 

> I think that we should definitely clarify what the tophat is supposed to be doing here, and do a better job of communicating that to everybody.

I agree, there's definitely not 100% alignment on this among different folks. I personally think that the removal of the ready-to-merge label should be also clearly communicated by the tophat (e.g., with a comment explaining the reason), as otherwise easy to miss, and possibly misleading for PR authors.

**Comment by sayboras** [comment]
> Marking again for backport to v1.15, as it appears to have been dropped from #36783.

Thanks for pointing it out, it seems like I have triggered the script by mistake. Adding this PR into #36783.

**Pull request merged**
