### PR TITLE
v1.11 backports 2022-02-23

### PR DESCRIPTION
**Pull request by nebril**
* #18725 -- watchers: Support hostPort for init containers (@pchaigno)
 * #18788 -- iptables,option,node: Consistent condition for ipset usage (@pchaigno)
 * #18766 -- clustermesh: Modify shared-service annotation after creation (@sayboras)
 * #18827 -- pkg/datapath/linux: Fix asymmetric IPsec logic on delete (@christarazi)
 * excluded #18857 -- test: Flush CT tables after L7 proxy tests in K8sServices (@brb)
 * #18731 -- ipsec: Add/Fix packet tracing for overlay mode (@YutaroHayakawa)
 * #18859 -- test: Wait until host EP is ready (=regenerated) (@brb)
 * #18893 -- docs: Remove trailing step in AWS helm install (@joestringer)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18725 18788 18766 18827 18731 18859 18893; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
$ make add-label branch=v1.11 issues=18725,18788,18766,18827,18731,18859,18893
```

### CODE REVIEW

**Comment by nebril** [comment]
/test-backport-1.11

**Review by pchaigno — APPROVED** [review]
My changes look good. Thanks Maciej!

**Review by sayboras — APPROVED** [review]
Looks good for my changes, thanks :100:

**Review by christarazi — APPROVED** [review]
:+1: for my commits

**Comment by nebril** [comment]
/test-backport-1.11

**Review by YutaroHayakawa — APPROVED** [review]
My changes looks good. Thanks!

**Comment by gandro** [comment]
- Runtime 404'ed, will restart
- GKE failed due to a transient error in fetching the istio artifacts, will restar https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/7713
- test-1.16-netnext looks like #18318 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-4.9/125
- 1.23-kernel-4.9 also looks like #18318 and a failure in the upgrade test, for which we need to backport #18985 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-4.9/125/

**Comment by gandro** [comment]
/ci-aks-1.11

**Review by brb — APPROVED** [review]
My changes LGTM, thanks.

**Comment by gandro** [comment]
Runtime is failing with `17:51:21      runtime: Mar 07 17:51:20 runtime cilium-agent[24064]: level=fatal msg="Envoy: Binary \"cilium-envoy\" cannot be executed" error="exit status 1" subsys=envoy-manager` - we've observed similar problems on the v1.10 branch.

**Comment by gandro** [comment]
All failures are known issues or flakes on v1.11

- Runtime image needs to be updated before it can pass https://github.com/cilium/cilium/issues/18919
- Upgrade tests will be fixed by https://github.com/cilium/cilium/pull/19066
 -https://github.com/cilium/cilium/issues/18318 is a known flake and seems unrelated to the PR

Given that the other pipelines passed, I'll merge this.

**Pull request merged**
