### PR TITLE
v1.12 Backports 2023-06-22

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #25969 (@jrajahalme)
 * [x] #25908 (@jrajahalme)
 * [x] #26189 (@jibi)
 * [ ] #26016 (@amitmavgupta)
 * [ ] #26092 (@peterj)
 * [ ] #26180 (@wedaly)
 * [x] #26130 (@brb)
 * [x] #26113 (@jschwinger233)
 * [ ] #26015 (@amitmavgupta)
 * [x] #26278 (@joestringer)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 25969 25908 26189 26016 26092 26180 26130 26113 26015 26278; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=25969,25908,26189,26016,26092,26180,26130,26113,26015,26278
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
@jrajahalme @amitmavgupta Conflicts arised during backport of your commits, please check the notes in commits for context and validate that it looks good to you :)

**Comment by nbusseneau** [comment]
/test-backport-1.12

**Review by jschwinger233 — APPROVED** [review]

**Review by brb — APPROVED** [review]
Thanks!

**Review by jibi — APPROVED** [review]

**Comment by nbusseneau** [comment]
/test-1.16-4.9

**Comment by nbusseneau** [comment]
/test-1.19-4.9

**Review by jrajahalme — APPROVED** [review]
Looks good for my PRs :)

**Comment by nbusseneau** [comment]
CI passed and most reviews are in (most importantly those for commits with conflicts), marking ready to merge.

**Pull request merged**
