### PR TITLE
1.10 backport for envoy: Update to release 1.18.4

### PR DESCRIPTION
**Pull request by jrajahalme**
Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>

```release-note
Cilium Envoy integration is updated to release 1.18.4.
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-backport-1.10

**Comment by jrajahalme** [comment]
test-backport-1.10

**Comment by jrajahalme** [comment]
test-backport-1.10

**Review by joestringer — APPROVED** [review]

**Comment by jrajahalme** [comment]
1.21 hit unrelated flake #16879

**Comment by jrajahalme** [comment]
New netnext fail #17261, unrelated to Envoy version (agent logs indicate Envoy not started).

**Comment by jrajahalme** [comment]
Multi-cluster hit https://github.com/cilium/cilium-cli/issues/361

**Comment by jrajahalme** [comment]
AKS failed with #17260

**Comment by jrajahalme** [comment]
@joestringer None of the CI fails are Envoy releated.

**Comment by pchaigno** [comment]
Is the `release-note` label on backport PRs used for anything?

**Pull request merged**
