### PR TITLE
Remove IP filters from initial GC

### LINKED ISSUE #29667: Agent restart causes undue removal of valid conntrack entries, leading to breaking of existing connections for some flows
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

For a long time we've been struggling with some critical connections being cut whenever we need to restart cilium agent. Upon deep diving into this problem, it seems that it's been a problem since cilium 1.3.0 for some specific types of flows, due to incorrect assumptions made on this commit https://github.com/cilium/cilium/commit/eefe58a3a7e8742909b7e630bcb1359c3dfb3ae1

When cilium starts up, it does a proactive removal of CT entries, and it assumes that the only valid flows are the ones for endpoints that live on that node, which isn't true in some cases.

Example: Having a LoadBalancer service with ExternalTrafficPolicy: Cluster, persistent connections will flow through any node in the cluster. For the nodes which don't have a local backend of such service, when the initial GC runs, it drops all CT entries for these valid flows with active connections, since they don't really have an IP for a local endpoint, but rather the IP of some endpoint that lives on another node.

What did I expect to happen?
I expected no flows affected by agent restart as documented.

### Cilium Version

1.14.4

### Kernel Version

5.19.0-1024-aws

### Kubernetes Version

1.24.14

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rsafonseca**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #29667

```release-note
Fixes some valid GC entries being removed at agent restart
```

### CODE REVIEW

**Comment by joestringer** [comment]
@rsafonseca Thanks for the PR! Could you describe in more specific terms the types of entries that were deleted before and how this proposed change addresses that issue?

How do we ensure that entries for Pods that have been descheduled during cilium-agent outage are removed? 

@ti-mo I don't think that we should be backporting this directly to all branches per [backport criteria](https://docs.cilium.io/en/stable/contributing/release/backports/#backport-criteria-for-current-minor-release). For the latest release I think it makes sense, but we should also be super careful here because there is a risk of regression if we fail to correctly garbage collect the entries. In the worst case, IPs for stale conntrack entries may be reused and this could have unexpected policy impacts.

**Comment by rsafonseca** [comment]
Hi @joestringer, thanks for taking a look!

I've noted a short description of some affected flows in the linked issue, the reality is that cleanup is unsafe and has been affecting some of our critical production flows since forever, whenever we need to restart the agent (which could be for various reasons like a config change or simply adjusting cpu/mem requests/limits
 
How do we ensure that entries for Pods that have been descheduled during cilium-agent outage are removed?

**Comment by joestringer** [comment]
@rsafonseca I appreciate that this has been a pain point for you, and I'm glad that you're investigating these issues and proposing fixes. I agree with the motivation of your change.

The difficult part here is that changing anything with conntrack can have various unintended impacts, so we need to make these changes thoughtfully and with a comprehensive understanding on the scope of the changes. If we do not discuss how + why the proposed change targets the undesirable behaviour, then this can cause regressions in other areas. Making such a change without documenting the design clearly can also lead to regressions if someone attempts to bring back some of the behaviour that is being removed here.

>  In the worst case, IPs for stale conntrack entries may be reused and this could have unexpected policy impacts.

I reviewed this possibility and I don't think this is possible, as newly created endpoints set `e.ctCleaned` to false and `runPreCompilationSteps()` will perform `e.scrubIPsInConntrackTable` to scrub any entries for the same IP that may still exist in the conntrack table during endpoint creation.

> > How do we ensure that entries for Pods that have been descheduled during cilium-agent outage are removed?
> 
> Do we really need to ensure that? Any stale entries shouldn't really cause any problems, and will eventually be removed when they expire. It's much worse to actively delete conntrack entries that are in active use, which is what currently happens

The intent behind `createGCFilter()` is to determine which entries correspond to active IPs and only delete entries that are for endpoints that no longer exist. If the logic inside that filter was working correctly, then you should not experience this bug. Evidently, the logic is not accurate. I agree that the current problem of being overzealous about deleting entries is creating a higher impact than keeping the entries, but that doesn't mean that the solution must ignore which IPs are active or not. I think the solution should consider exactly which entries should be kept and which entries should remain, as that keeps the content of the conntrack as small as possible following startup. This can have impacts on bpf map pressure, CPU utilization to iterate conntrack, and potentially even endpoint creation latency.

At a high level, I think that the problem you are facing is that there are active entries being deleted. What exactly do those entries look like? Are they service entries (pod->svc tuple) or in/out entries (pod->pod tuple)? Have you considered whether to identify those entries and skip deletion for them during the initial scan?

**Comment by joestringer** [comment]
> They look like:
> Public IP -> Endpoint IP of a pod in another node

In which case is this conntrack entry created? Why is the traffic bouncing through a node that doesn't host the target endpoint IP? The most common case for this would be NodePort, but those are exposed on host IPs so I'd expect the conntrack entries to reflect Public IP -> host IP, then with the existing function the host IP filtering should handle the case. So presumably there's a different scenario in your environment.

> Host IP -> Endpoint IP of a pod in another node

This case should already be handled by the current logic, unless the host IP detection logic is failing to detect a relevant host IP.

> If you do feel strongly that this mechanism is currently useful, one inexpensive way that we could implement this to keep a similar behavior and avoid GC'ing external flows accidentally would be to simply look at the CIDR used by the node and only collect GCs which contain a src/dest within the node CIDR and only delete the ones that match that and not the list of restored endpoints. That would GC entries from any pod that might have de-scheduled during the short downtime without touching anything else which doesn't pertain to any pods in the node.

This is an interesting idea, but it relies on each node having a dedicated CIDR. Not all IPAM modes provide this guarantee, so for other IPAM modes there could still be an issue.

**Comment by rsafonseca** [comment]
> In which case is this conntrack entry created? Why is the traffic bouncing through a node that doesn't host the target endpoint IP? The most common case for this would be NodePort, but those are exposed on host IPs so I'd expect the conntrack entries to reflect Public IP -> host IP, then with the existing function the host IP filtering should handle the case. So presumably there's a different scenario in your environment.

This happens in services that use a NodePort indeed as noted in the issue, for any service that uses ExternalTrafficPolicy: Cluster with an external LoadBalancer for example.
Two entries are being created in this flow, here's an example (in a host with a pod CIDR of 10.138.186.0/24) where 10.141.118.153:3051 is an endpoint of a service which lives in another node:
```
TCP OUT 58.145.184.245:8149 -> 10.141.118.153:3051 expires=646 RxPackets=241 RxBytes=42535 RxFlagsSeen=0x1a LastRxReport=629 TxPackets=251 TxBytes=23150 TxFlagsSeen=0x1e LastTxReport=636 Flags=0x0033 [ RxClosing TxClosing SeenNonSyn NodePort ] RevNAT=151 SourceSecurityID=2 IfIndex=0 
TCP OUT 172.18.30.107:32762 -> 58.145.184.245:8149 service expires=22236 RxPackets=0 RxBytes=549 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1e LastTxReport=636 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=151 SourceSecurityID=0 IfIndex=0 
```
The bottom one is indeed kept due to the hostIP added to the filter, but the top one is not. Also, in these cases the current GC mechanism is ineffective since it would keep entries for endpoints on the current node that could have been deleted, due to the fact that the entry still contains the hostIP, making this mechanism once again more of a problem than a problem solver.

**Comment by joestringer** [comment]
Thanks for sharing those details. I was unaware that the rev-NAT conntrack entries may contain client world IPs and remote backend IPs. It turns out that the underlying datapath code for managing those local backends in the CT table is exactly the same as how it handles CT for local backends.

> [...] the time for which the pod is down during a restart/crash/update is fairly small, so any stale entries are highly unlikely to have the potential to have any relevant level of impact on the points above

Though I don't want to overstate the initial GC implications, in general I think we should try to avoid assuming that cilium-agent downtime is overly short. Sure, we'd prefer to keep it relatively short, but compared to the scale of the ability for apps to initiate connections, it is quite long. Though that's probably more a general commentary and may not be directly actionable for this bugfix.

> The simplest and safest way to do this would be for the agent to keep a map of its endpoints (which it seems it already does in the cilium_lxc map), and then diff that list with the current endpoints on startup and delete ONLY the entries that are known to match the de-scheduled pods [...]

This would be a bit more accurate, and Cilium should already be tracking enough information to do this. It may be as simple as determining the stale endpoints and then updating the CT GC logic to consider a list of "IPs to match and delete" rather than "IPs to match and keep". The line below seems to be passing the relevant restored endpoints through, so determining the set of stale IPs may be as simple as diffing the `.possible` vs the `.restored` before passing it to the CT init below:

https://github.com/cilium/cilium/blob/7dd9a422e3ae052acc3239a4f360ae65969d6740/daemon/cmd/daemon_main.go#L1729

> [...] instead of trying to assert what should be there and deleting everything else since this is always more expensive and error prone.

I think the underlying tradeoff here is how heavily we rely on the CT entry's expiry timestamp as the only way to garbage collect vs. having a sense of which peers could legitimately be consuming conntrack entries, and clearing out anything that doesn't match. But that said, (a) that's out of scope for a bugfix like this and (b) if we pursued it, it should be implemented across all of the GC cycles, not just whenever Cilium restarts. 

I've prodded a couple of other @cilium/sig-datapath folks to see if anyone else wishes to chime in on the approach here.

**Comment by liuyuan10** [comment]
> I've prodded a couple of other @cilium/sig-datapath folks to see if anyone else wishes to chime in on the approach here.

Any update? do we plan to move forward with this PR?

**Comment by liuyuan10** [comment]
@joestringer any outcome from the community discussion? Are we still debating over the two options?

**Comment by liuyuan10** [comment]
@joestringer is there any update to this topic? I think this is really a severe issue that needs a fix. 

Can I ask what's the issue with the current PR? What's the purpose of such initial GC?

**Comment by borkmann** [comment]
Two entries are being created in this flow, here's an example (in a host with a pod CIDR of 10.138.186.0/24) where 10.141.118.153:3051 is an endpoint of a service which lives in another node:
> 
> ```
> TCP OUT 58.145.184.245:8149 -> 10.141.118.153:3051 expires=646 RxPackets=241 RxBytes=42535 RxFlagsSeen=0x1a LastRxReport=629 TxPackets=251 TxBytes=23150 TxFlagsSeen=0x1e LastTxReport=636 Flags=0x0033 [ RxClosing TxClosing SeenNonSyn NodePort ] RevNAT=151 SourceSecurityID=2 IfIndex=0 
> TCP OUT 172.18.30.107:32762 -> 58.145.184.245:8149 service expires=22236 RxPackets=0 RxBytes=549 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1e LastTxReport=636 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=151 SourceSecurityID=0 IfIndex=0 
> ```
> 
> The bottom one is indeed kept due to the hostIP added to the filter, but the top one is not.

Still catching up on this thread, but could this be resolved by diffing the old local endpoints (data from the BPF map before the sync) with the new local endpoints (data from k8s apiserver after sync), and then removing the IP addresses via createGCFilter()?

**Comment by rsafonseca** [comment]
Hi @borkmann, thanks for chiming in :)

Indeed that would solve the problem, that's the alternate solution I proposed above (different to the one in the MR which was an initial approach of just removing the logic from the GC, which was still preferable to leaving this serious problem as is). It would also actually clean up flows from old endpoints in the overlay network which target the host IP (we should be careful though, to not remove flows from pods which are on hostNetwork, as that would cause an even worse problem 😂 ).

If we can merge as is, great, if we do believe that it's worth keeping this initial filter mechanism instead of just relying on the recurring GC task, we can either merge now to stop the bleeding and defer that for later, or this needs to be reworked before merge.

WDYT?

**Comment by borkmann** [comment]
> Hi @borkmann, thanks for chiming in :)
> 
> Indeed that would solve the problem, that's the alternate solution I proposed above (different to the one in the MR which was an initial approach of just removing the logic from the initial GC, which was still preferable to leaving this serious problem as is). It would also actually clean up flows from old endpoints in the overlay network which target the host IP (we should be careful though, to not remove flows from pods which are on hostNetwork, as that would cause an even worse problem 😂 ).
> 
> If we can merge as is, great, if we do believe that it's worth keeping this initial filter mechanism instead of just relying on the recurring GC task, we can either merge now to stop the bleeding and defer that for later, or this needs to be reworked before merge.
> 
> WDYT?

My preference is that if the plan is to backport for stable, then it would be good to see the full solution with cleaning up the right endpoints. The merge as-is path I think would work for the 1.16-dev cycle without backport to stable and with commitment to a subsequent PR to work on the endpoint cleanup, but ideally we'd have a complete solution in one PR so this is less scattered. I presume that would also be @joestringer 's preference.

**Comment by joestringer** [comment]
I've made a few of observations since the discussions above:
1. By default Cilium already pulls all remote Pod IPs on startup so calculating stale entries should be mostly just some set operations and to make this code aware. Unfortunately there is this one mode `--enable-high-scale-ipcache` which likely violates this. So then it raises the question whether we should try to rely on this and make a special case for the 'high scale ipcache' mode, or simplify so that all modes work the same..
1. Technically you could _probably_ set up a NodePort that has backends in a remote cluster (?) If so then we could get flows like this with stale endpoints corresponding to a very wide set of remote peers. I'm not sure that's necessarily a good assumption to build upon. Not sure whether that suggests we try to exclude remote clusters somehow or otherwise come up with a simpler solution that doesn't rely on state replication so much.
1. The entry with {client, remote backend} tuple presumably has a RevNAT ID which is used to perform the reverse NAT to bring back the local node IP. If we could identify that mapping cheaply then it could greatly simplify the problem so that instead of tracking all remote backend IPs, we could see which local IP it corresponds to and exempt local host flows. Though I guess at that point I wonder if this proposal is much different from just exempting all flows involving only foreign (remote) IPs.

These points suggest the solution should only worry about known stale local node IPs.

> any outcome from the community discussion? Are we still debating over the two options?
> is there any update to this topic? I think this is really a severe issue that needs a fix.

@liuyuan10 I brought it up during the NA/APAC community call on December 20. You can find the notes [here](https://docs.google.com/document/d/1egv4qLydr0geP-GjQexYKm4tz3_tHy-LCBjVQcXcT5M/edit#heading=h.kt6r73jnphq). No real conclusions, just other areas to consider.

One of the points that was raised during the APAC session that if Cilium-agent missed a Pod delete (CNI DEL) while Cilium was down, then other local Linux configuration state such as routes could plausibly also be left stale and remaining configured in the system. That state would also need cleaning. From what I can tell we dug a little and came to the conclusion that those other cases are already handled in other ways so there's no stale devices/routes.

> Can I ask what's the issue with the current PR? What's the purpose of such initial GC?

GC is about removing stale entries, and this GC-on-startup cleans up entries for endpoints in the cluster that are known stale, that is to say that during the time Cilium was stopped, the corresponding Pods were descheduled. We have no way to tell how long cilium-agent has been down, but it's probably fair to say that there is a relatively limited number of such stale Pods. We don't know how many open connections there were for those Pods and hence how many conntrack entries are being consumed for those stale endpoints. The stale endpoints could be in the local node, remote nodes in the current cluster, or remote nodes in remote clusters. The conntrack entries may not have any IP addresses corresponding to the current node. So overall at a high level the question is whether Cilium should try to be accurate about how it's clearing out these potentially stale entries, and then hence what kind of risks or benefits we may get from different proposals on solving the problem. Currently it has a relatively naive heuristic which is overzealous and deletes entries corresponding to live connections, leading to temporary connection disruption in the reply direction (presumably until the client retransmits a forward direction packet).

**Comment by rsafonseca** [comment]
Awesome, it looks like it might sort the issue with processing the missed deletes, and if it does, this MR that just drops the logic entirely is the right way to go to fix the problem of the broken flows on agent startup :)

**Comment by ti-mo** [comment]
What's needed to get this merged? Has the discussion concluded? Changes needed to the code?

**Comment by aditighag** [comment]
@rsafonseca We discussed this internally, and  https://github.com/cilium/cilium/commit/54fef7acd341a4dd95848f9843773ba407c55499 looked promising as that would inform the agent about deleted pod IPs after restart. However, it's not clear whether the commit is enough to trigger the GC for queued deleted pods while the agent was down. 

Trying to understand the implications of your change involving removal of filters altogether in case the GC is missed for deleted pods. FWIW, the agent [scrubs conntrack entries](https://github.com/cilium/cilium/blob/main/pkg/endpoint/bpf.go#L728) when new endpoints are added. So even if there were stale entries with the deleted pod IPs, they would get cleaned up when those IPs are reused. However, one concern I have here is whether some entries could linger in the conntrack map for a longer duration (especially for UDP) depending on when the next GC run is scheduled per the adaptive algorithm. 

Are there proposals for checking whether an IP belongs to a local or remote pod so that we may not have to fully get ride of the current filters? IPcache, for example, has this information.

**Comment by joestringer** [comment]
I dug in a little deeper to confirm. Some info points:

- PR https://github.com/cilium/cilium/pull/23486 refers to some file with a `.delete` suffix, so I'm watching for that as a sign that a deletion is queued during agent outage.
- Need a way to stop the agent to simulate agent outage. Maybe we can just edit a cilium-agent init container to do a long sleep.
- Need to ensure that the deletion eventually triggers CT sweep for that IP. Peruse through functions with names like `Delete` in `pkg/endpoint` in search of relevant codepaths.

Steps:

1. Apply some local logging changes to the local tree per reasoning above[^1]
2. `make kind`, `make kind-image`, `make kind-image-cilium`
3. `kubectl apply -f examples/minikube/http-sw-app.yaml`
4. Force cilium-agent to stop for a while via `kubectl -n kube-system edit ds/cilium`[^2]
5. `kubectl delete pod/tiefighter`
6. `docker exec -ti kind-worker`, browse `/var/run/cilium` to find the `deleteQueue` and `cilium-cni.log` to confirm queued deletion
7. Revert the changes from step (4) to process the deletion `kubectl -n kube-system rollout undo ds/cilium`
8. `kubectl -n kube-system logs ds/cilium | grep -e 'joe' -e 'tiefighter'`
   ```$ kubectl -n kube-system logs ds/cilium | grep joe
   Found 2 pods, using pod/cilium-qlzh5
   ...
   level=debug msg="Endpoint restoring" ciliumEndpointName=default/tiefighter code=OK containerID=59e5a49f05 containerInterface=eth0 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2268 endpointState=restoring identity=30970 ipv4=10.244.1.229 ipv6="fd00:10:244:1::b32e" k8sPodName=default/tiefighter policyRevision=0 subsys=endpoint type=0
   level=warning msg="Unable to restore endpoint, ignoring" ciliumEndpointName=default/tiefighter endpointID=2268 error="Kubernetes pod default/tiefighter does not exist" subsys=daemon
   ...
   level=debug msg="Deleting endpoint" ciliumEndpointName=default/tiefighter code=OK containerID=59e5a49f05 containerInterface=eth0 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2268 endpointState=disconnecting identity=30970 ipv4=10.244.1.229 ipv6="fd00:10:244:1::b32e" k8sPodName=default/tiefighter policyRevision=0 subsys=endpoint type=0
   ...
   level=info msg="Scrubbing conntrack for IPs" ipv4=10.244.1.229 ipv6="fd00:10:244:1::b32e" subsys=endpoint user=joe
   ```

[^1]: Log when pkg/endpoint touches CT map stuff:
      ```
      @@ -1035,6 +1039,12 @@ func (e *Endpoint) garbageCollectConntrack(filter *ctmap.GCFilter) {
       func (e *Endpoint) scrubIPsInConntrackTableLocked() {
      +       log.WithFields(logrus.Fields{
      +               "user":         "joe",
      +               logfields.IPv4: e.IPv4,
      +               logfields.IPv6: e.IPv6,
      +       }).Info("Scrubbing conntrack for IPs")
      +
              e.garbageCollectConntrack(&ctmap.GCFilter{
      ```

[^2]: Force an init container to sleep a while by adding these lines. Can be cross-referenced with init container logs:
      ```
                echo "Sleeping for a while for testing purposes..."
                sleep 9001
      ```

**Comment by joestringer** [comment]
@aditighag:
> Are there proposals for checking whether an IP belongs to a local or remote pod so that we may not have to fully get ride of the current filters? IPcache, for example, has this information.

IPCache _can_ tell you this information, though I think in high scale environments we have users pushing to not explicitly track each such piece of information individually for each Pod across each node's cilium-agent in each connected cluster. I think there's an interesting subsequent question about how we evict CT entries when this node is responsible for NodePort forwarding towards a Pod that is deleted on a remote node. However, I don't think we need to block this PR further on the perfect solution such problems. We can mitigate the couple of existing issues caused by this logic for now, and further improve in subsequent PRs.

I believe this PR should be logically correct if applied on branches v1.14 or newer, assuming it passes CI.

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Requesting @xmulligan to review for Community since this PR touches the `USERS.md` file. Not sure why GitHub didn't autoselect someone to review on behalf of that team.

**Review by borkmann — APPROVED** [review]

**Review by xmulligan — APPROVED** [review]

**Comment by tklauser** [comment]
FYI I've hit major merge conflicts backporting this to `v1.14` in https://github.com/cilium/cilium/pull/30864, thus skipped backporting for now.

**Pull request merged**
