### PR TITLE
fqdn: remove unused test helper funcs

### PR DESCRIPTION
**Pull request by tklauser**
These are unused since commit bb1b093e3a41 ("Remove unused global
variables").

### CODE REVIEW

**Comment by tklauser** [comment]
No need to run Jenkins CI, passing Travis CI unit tests should be enough.

**Review by ianvernon — APPROVED** [review]

**Comment by pchaigno** [comment]
> No need to run Jenkins CI, passing Travis CI unit tests should be enough.

Except if these are used in privileged unit tests, no?

**Review by pchaigno — APPROVED** [review]

**Review by vadorovsky — APPROVED** [review]

**Comment by mrostecki** [comment]
Thanks for spotting that!

**Review by christarazi — APPROVED** [review]

**Comment by pchaigno** [comment]
retest-runtime

**Comment by tklauser** [comment]
> Except if these are used in privileged unit tests, no?

True, yes. Thanks @pchaigno!

Runtime tests failed because of a merge conflict between #13107 and #13036

```
07:37:58  Failed to compile test:
07:37:58  
07:37:58  # github.com/cilium/cilium/test/helpers
07:37:58  helpers/kubectl.go:667:38: too many arguments in call to kub.GetCiliumPods
07:37:58  	have (string)
07:37:58  	want ()
07:37:58  note: module requires Go 1.15
```

https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/1750/

Sent #13124 with a fix.

**Comment by tklauser** [comment]
retest-runtime

**Comment by tklauser** [comment]
Runtime tests and Travis CI passed, marking as ready to merge.

**Pull request merged**
