### PR TITLE
WIP backport 1.5

### PR DESCRIPTION
**Pull request by brb**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8076)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
@brb We found that 8e63c5a actually increases the instruction size. I'd drop it.

**Comment by brb** [comment]
@tgraf Thanks, I dropped it.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
No longer relevant, closing.

**Pull request closed without merging**
