### PR TITLE
cgroup manager: introduce hive cell

### PR DESCRIPTION
**Pull request by mhofstetter**
This PR introduces a Hive Cell for the cgroup manager.

Please review the individual commits.

* introduce hive cell for cgroup manager
* use injected logger in cgroup manager
* remove unused method GetParentPodMetadata
* introduce noop cgroup manager implementation

### CODE REVIEW

**Review by kaworu — APPROVED** [review]
Hubble changes LGTM

**Comment by mhofstetter** [comment]
rebased to `main` to resolve conflicts

**Comment by mhofstetter** [comment]
rebased to `main` to resolve conflicts

**Review by dylandreimerink — APPROVED** [review]
Nice work. Thanks!

**Review by ysksuzuki — APPROVED** [review]

**Review by doniacld — APPROVED** [review]

**Review by joamaki — APPROVED** [review]

**Comment by mhofstetter** [comment]
Removing review-request for Louis as we have everything covered - thanks :pray:

**Pull request merged**
