### PR TITLE
daemon: Fix fallback to iptables-based masquerading

### PR DESCRIPTION
**Pull request by brb**
Previously, when falling back to iptables-based masquerading, if a user
had specified `--egress-masquerade-interface`, the agent considered it
as part of BPF masquerading options. This made it obviously to fail.

Fix: b7b962ba0 ("daemon: Fallback to iptables if BPF masq cannot be enabled")
Reported-by: Tobias Klauser <tklauser@distanz.ch>

Fix #12081

/cc @tklauser

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]
Tested on EKS and verified that this fixes #12078

**Comment by brb** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
LGTM, let's address the remaining connectivity check issue on EKS in a follow-up.

**Pull request merged**
