### PR TITLE
vagrant: Bump Vagrant net-next box version

### PR DESCRIPTION
**Pull request by pchaigno**
This new version of the VM image includes a newer kernel with a fix for the `bpf_skb_set_tunnel_key` helper [1].

1 - https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=b8fff748521c7178b9a7d32b5a34a81cec8396f3

### CODE REVIEW

**Comment by pchaigno** [comment]
/test-1.24-net-next

**Review by sayboras — APPROVED** [review]
:shipit:

**Comment by pchaigno** [comment]
Tested, reviewed, marking ready to merge.

**Pull request merged**
