### PR TITLE
Fix LaTeX doc generation

### PR DESCRIPTION
**Pull request by next-ramses**
"make latex" is currently giving this error, caused by a .gif file not being able to be rendered by Sphynx:

Please fix the documentation warnings below
/src/Documentation/contributing/development/contributing_guide.rst:: WARNING: a suitable image for latex builder not found: ['image/gif'] (https://i1.wp.com/user-images.githubusercontent.com/3477155/52671177-5d0e0100-2ee8-11e9-8645-bdd923b7d93b.gif) make: *** [Makefile:133: latex] Error 1

This commit adds "imgconverter" extension to Sphynx which allows converting the file into a suitable format.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
thank you @next-ramses! looks good and `make latex` worked for me

**Comment by joestringer** [comment]
Thanks for the PR! Could you amend your commit with this diff and force push afresh? This will integrate the changes into the default builder image used for building docs, and should hopefully resolve failures reported by the CI tests.

```
diff --git a/.github/workflows/documentation.yaml b/.github/workflows/documentation.yaml
index aefbf640..55205738 100644
--- a/.github/workflows/documentation.yaml
+++ b/.github/workflows/documentation.yaml
@@ -62,7 +62,7 @@ jobs:
         with:
           persist-credentials: false
       - name: Build HTML
-        uses: docker://quay.io/cilium/docs-builder:ea8511e4d2b39d2ef7a4c71edbe6eddb19e8bb5c@sha256:3a04bb23e017dfb[22](https://github.com/cilium/cilium/actions/runs/10323940229/job/28724112093?pr=34278#step:9:23)9c0139a3ff7208a6d4ec3944bc24b8441c73ed7d70d781f
+        uses: docker://quay.io/cilium/docs-builder:981f885a62540a155c04eb5389fd1995fd7d140f@sha[25](https://github.com/cilium/cilium/actions/runs/10323940229/job/28724112093?pr=34278#step:9:26)6:6ac09bc398694756adc87bee5bb040[27](https://github.com/cilium/cilium/actions/runs/10323940229/job/28724112093?pr=34278#step:9:28)ea3a8e75da6651bc760f4d315eee3a04
         with:
           entrypoint: ./Documentation/check-build.sh
           args: html
```

**Comment by next-ramses** [comment]
> Thanks for the PR! Could you amend your commit with this diff and force push afresh? This will integrate the changes into the default builder image used for building docs, and should hopefully resolve failures reported by the CI tests.
> 
> ```
> diff --git a/.github/workflows/documentation.yaml b/.github/workflows/documentation.yaml
> index aefbf640..55205738 100644
> --- a/.github/workflows/documentation.yaml
> +++ b/.github/workflows/documentation.yaml
> @@ -62,7 +62,7 @@ jobs:
>          with:
>            persist-credentials: false
>        - name: Build HTML
> -        uses: docker://quay.io/cilium/docs-builder:ea8511e4d2b39d2ef7a4c71edbe6eddb19e8bb5c@sha256:3a04bb23e017dfb229c0139a3ff7208a6d4ec3944bc24b8441c73ed7d70d781f
> +        uses: docker://quay.io/cilium/docs-builder:981f885a62540a155c04eb5389fd1995fd7d140f@sha256:6ac09bc398694756adc87bee5bb04027ea3a8e75da6651bc760f4d315eee3a04
>          with:
>            entrypoint: ./Documentation/check-build.sh
>            args: html
> ```
> 
> EDIT: Fixed the copy-paste from the workflow output.

done!

**Comment by aanm** [comment]
@next-ramses please remove the "Merge" commit. Thank you

**Comment by joestringer** [comment]
Looks like there was something else merged in between that broke the sha that I suggested you to change. To simplify this, I just generated the commit separately in #34414, rebased your branch and pulled in the builder update. This should be good to go now.

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Thanks @next-ramses for your contribution!

**Pull request merged**
