### PR TITLE
bpf: minor cleanups

### PR DESCRIPTION
**Pull request by julianwiedmann**
Clean up some areas of confusion in the BPF code. Should cause no functional change.

### CODE REVIEW

**Comment by julianwiedmann** [comment]
/test-1.24-4.19

**Comment by julianwiedmann** [comment]
/test-1.24-4.19

**Comment by julianwiedmann** [comment]
`ci-multicluster` has been failing quite a bit lately, and isn't required.

**Review by NikAleksandrov — APPROVED** [review]

**Pull request merged**
