### PR TITLE
docs: Add instructions to run e2e tests on GKE

### PR DESCRIPTION
**Pull request by raybejjani**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10029)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-docs-please

**Review by joestringer — COMMENTED** [review]
Looks fine to me.

I tried this locally, only change is that I only tried to run `K8sHealth*` rather than the full k8s suite. I got this:

```
Running Suite: Suite-k8s-1.13                                                                                                                                                         
=============================                                                                                                                                                         
Random Seed: 1580775587                                                                                                                                                               
Will run 1 of 377 specs                                                                                                                                                               
                                                                                                                                                                                      
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Spinning up vagrant VMs... ●SSSSSSSSSSSSSSSS                                                                                                                                          
                                                                                                                                                                                      
------------------------------                                                                                                                                                        
• Failure in Spec Setup (BeforeEach) [0.252 seconds]                                                                                                                                  
K8sHealthTest [BeforeEach]                                                                                                                                                            
/home/joe/git/cilium/test/ginkgo-ext/scopes.go:395                                                                                                                                    
  checks cilium-health status between nodes                                                                                                                                           
  /home/joe/git/cilium/test/ginkgo-ext/scopes.go:430                                                                                                                                  
                                                                                                                                                                                      
  Cannot connect to k8s cluster, output:                                                                                                                                              
  bash: kubectl: command not found                                                                                                                                                    
                                                                                                                                                                                      
                                                                                                                                                                                      
  /home/joe/git/cilium/test/test_suite_test.go:276
```

For reference,

```
$ which kubectl
/snap/bin/kubectl
$ ls -lh $(which kubectl)
lrwxrwxrwx 1 root root 13 Jan 22 13:06 /snap/bin/kubectl -> /usr/bin/snap
```

(Kubectl works fine for me in my terminal, but I wonder if snap / microk8s is doing some funny stuff or if there's some other assumption I'm violating....?)

**Comment by raybejjani** [comment]
@joestringer Hmm, could you try with `-cilium.passCLIEnvironment=true` I removed that because tests worked the same way without it. It may be as simple as PATH not being setup right (the env is actively cleared for the execs as I recall, and this option avoids that).

**Comment by raybejjani** [comment]
test-docs-please

**Comment by joestringer** [comment]
@raybejjani Getting better...

```
test $ CNI_INTEGRATION=gke K8S_VERSION=1.13 CILIUM_IMAGE="quay.io/cilium/cilium:latest" CILIUM_OPERATOR_IMAGE="quay.io/cilium/operator:latest" ginkgo --focus="K8sHealth*" -noColor -- -cilium.provision=false -cilium.kub
econfig=~/.kube/config -cilium.image="quay.io/cilium/cilium:latest" -cilium.operator-image="quay.io/cilium/operator:latest" -cilium.passCLIEnvironment=true
Running Suite: Suite-k8s-1.13
=============================
Random Seed: 1580844554
Will run 1 of 377 specs

Spinning up vagrant VMs... ●SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

------------------------------
• Failure in Spec Setup (BeforeEach) [0.504 seconds]
K8sHealthTest [BeforeEach]
/home/joe/work/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
  checks cilium-health status between nodes
  /home/joe/work/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430

  Cannot connect to k8s cluster, output:
  W0204 11:29:28.665237   10845 loader.go:223] Config not found: ~/.kube/config
  The connection to the server localhost:8080 was refused - did you specify the right host or port?
  

  /home/joe/work/src/github.com/cilium/cilium/test/test_suite_test.go:276
------------------------------
<Checks>

</Checks>

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

Summarizing 1 Failure:

[Fail] [BeforeEach] K8sHealthTest checks cilium-health status between nodes 
/home/joe/work/src/github.com/cilium/cilium/test/test_suite_test.go:276

Ran 1 of 377 Specs in 0.514 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 376 Skipped
--- FAIL: TestTest (0.52s)
FAIL

Ginkgo ran 1 suite in 14.730666295s
Test Suite Failed
```

**Comment by raybejjani** [comment]
Hmm, could you manually expand `-cilium.kubeconfig=~/.kube/config`?
I'm not sure why I included the `~/` form in the docs. My CLI history has it fully expanded :/ I'll update this PR to sort that out.

**Comment by aanm** [comment]
@raybejjani I've removed this PR from the needs-bacport to 1.7 as this is not required to block 1.7 release.

**Comment by raybejjani** [comment]
test-docs-please

**Pull request merged**
