### PR TITLE
Test:Guestbook wait for pods to be ready

### PR DESCRIPTION
**Pull request by eloycoto**
Wait until all pods are ready before wait for endpoints to be ready.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4539)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by tgraf** [comment]
Why does this matter? Please provide a description why this change is required.

**Comment by eloycoto** [comment]
It's only for logging to be honest. 

The `WaitForServiceEndpoints` function only return the port and it is hard to know the status of the containers for the pod in that time. If we wait for pods first, we have all `kubectl get pods -l zgroup=guestbook` and we can debug if any container was ready any time. 

Regards.

**Comment by tgraf** [comment]
This is great info. This should have been the commit info. Please adjust accordingly.

**Comment by eloycoto** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Pull request merged**
