### PR TITLE
bpf: Fix ipcache lookup in bpf_netdev

### PR DESCRIPTION
**Pull request by tgraf**
Commit bfdfc3dea6b introduces an incorrect NULL check of the return value of
ipcache_lookup(). Fix this and only derive the security identity if the ipcache
entry if the security identity is in the entry. This allows to work around the
missing delete operations in certain kernels by updating the entry with a
zeroed out value instead of deleting it.

Fixes: bfdfc3dea6b ("bpf: Shift ingress ipcache source lookup to netdev")
Signed-off-by: Thomas Graf <thomas@cilium.io>

This bug was never released, no backport needed.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4881)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Why should info->sec_label ever be 0?

**Comment by joestringer** [comment]
Hit known NACK issue. Re-running tests.

**Comment by joestringer** [comment]
test-me-please

**Comment by tgraf** [comment]
> Why should info->sec_label ever be 0?

I'll add this in a follow up PR to add a workaround for missing delete on LPM tries:
```
diff --git a/pkg/maps/ipcache/ipcache.go b/pkg/maps/ipcache/ipcache.go
index a4406f765..7d29705b8 100644
--- a/pkg/maps/ipcache/ipcache.go
+++ b/pkg/maps/ipcache/ipcache.go
@@ -156,6 +156,17 @@ func NewMap() *Map {
        }
 }

+// Delete removes a key from the ipcache BPF map
+func Delete(k bpf.MapKey) error {
+       // Older kernels do not support deletion of LPM map entries so zero out
+       // the entry instead of attempting a deletion
+       if IPCache.MapType == bpf.BPF_MAP_TYPE_LPM_TRIE {
+               return IPCache.Update(k, &RemoteEndpointInfo{})
+       }
+
+       return IPCache.Delete(k)
+}
+
```

**Comment by tgraf** [comment]
NACK found

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
