### PR TITLE
Test endpoint slice synchronization as part of the Conformance Cluster Mesh workflow

### PR DESCRIPTION
**Pull request by giorio94**
Related: https://github.com/cilium/cilium/pull/28440, https://github.com/cilium/cilium-cli/pull/2267

### CODE REVIEW

**Comment by giorio94** [comment]
Marking ready for review. The actual test has been introduced by @MrFreezeex in https://github.com/cilium/cilium-cli/pull/2267, and will be included in the next release of the Cilium CLI.

**Review by YutaroHayakawa — APPROVED** [review]

**Review by brlbil — APPROVED** [review]

**Pull request merged**
