### PR TITLE
Update stable releases

### PR DESCRIPTION
**Pull request by michi-covalent**

### CODE REVIEW

**Review by zacharysarah — APPROVED** [review]
@michi-covalent Thanks for this! ✨ LGTM

**Comment by michi-covalent** [comment]
[test-1.26-net-next](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/1885/): filed https://github.com/cilium/cilium/issues/24964

**Comment by michi-covalent** [comment]
/test-1.26-net-next

**Comment by michi-covalent** [comment]
[ci-datapath](https://github.com/cilium/cilium/actions/runs/4737889674/jobs/8411173443): filed https://github.com/cilium/cilium/issues/24965

**Comment by michi-covalent** [comment]
ci-datapath: "Provision LVH VMs" step failed. looks like a transient error. a bunch of errors like this:

```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/v/virt-manager/virtinst_4.0.0-1_all.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 52.147.219.192 80]
```

https://github.com/cilium/cilium/actions/runs/4738199801/attempts/1

**Comment by michi-covalent** [comment]
/test-1.26-net-next

**Comment by joestringer** [comment]
I'm not sure why Mergability is stuck, the PR may need closing+reopening, or a rebase against master (probably the latter).

**Review by joestringer — APPROVED** [review]

**Comment by michi-covalent** [comment]
ci-eks: filed https://github.com/cilium/cilium/issues/24988

**Comment by michi-covalent** [comment]
test-1.16-4.19: hit https://github.com/cilium/cilium/issues/24840

**Comment by michi-covalent** [comment]
/test-1.16-4.19

**Review by ldelossa — APPROVED** [review]

**Pull request merged**
