### PR TITLE
bpf, datapath: unconditionally assume support for LRU hash maps

### PR DESCRIPTION
**Pull request by tklauser**
LRU hash maps are available since kernel version 4.10 [1], [2], [3]. For Cilium v1.14, the minimum required kernel version is 4.19.57 [4]. Thus we can now unconditionally assume support for that map type.

[1] https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md#map-types
[2] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=29ba732acbeece1e34c68483d1ec1f3720fa1bb3
[3] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3a08c2fd763450a927d1130de078d6f9e74944fb
[4] https://docs.cilium.io/en/latest/operations/system_requirements/#base-requirements

For #22116

### CODE REVIEW

**Review by jibi — APPROVED** [review]
Nice :rocket:

**Review by jrajahalme — APPROVED** [review]
Runtime test panic seems unrelated.

**Pull request merged**
