### PR TITLE
Update concepts doc page for egress policy

### PR DESCRIPTION
**Pull request by joestringer**
Fixes: #3822

### CODE REVIEW

**Comment by joestringer** [comment]
test-docs-please

**Comment by joestringer** [comment]
test-docs-please

**Review by borkmann — APPROVED** [review]
Thanks!

**Review by ackerman80 — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]
Thanks for taking care of this!

**Comment by ianvernon** [comment]
Merging as docs build succeeded, and we do not need to run the full datapath test suite here.

**Pull request merged**
