### PR TITLE
v1.15 Backports 2024-06-18

### PR DESCRIPTION
**Pull request by jschwinger233**
* [x] #33050 (@sayboras)
 * [ ] #33150 (@jibi) :warning: resolved conflicts
 * [ ] #32852 (@geakstr) :warning: resolved conflicts

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33050 33150  32852
```
 * [ ] #33033 (@PhilipSchmid) :warning: dropped due to conflicts

### CODE REVIEW

**Review by jibi — APPROVED** [review]

**Comment by jschwinger233** [comment]
/test-backport-1.15

**Comment by PhilipSchmid** [comment]
@jschwinger233 What's the plan for 33033? As long as it won't be included here, could you please remove me from the reviewers here? I can't do it on my own. 😢

**Comment by jschwinger233** [comment]
/test-backport-1.15

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commit :heavy_check_mark:

**Comment by jschwinger233** [comment]
The only unsuccessful CI check is "Image CI Build / Display Digests", not an issue caused by this PR, I think it's ready for review.

**Review by viktor-kurchenko — APPROVED** [review]
Thanks!

**Review by ti-mo — APPROVED** [review]

**Pull request merged**
