### PR TITLE
BPF kernel probes based on bpftool

### PR DESCRIPTION
**Pull request by vadorovsky**
This PR implements BPF feature probes for the kernel config with bpftool. Based on #8094, but now I'm trying to submit in smaller pieces with hope that CI is not going to complain. Please review per commit.

```release-note
BPF kernel probes based on bpftool
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9789)

### CODE REVIEW

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
@borkmann @joestringer CI seems to be OK now. Can we possibly include that in 1.7? And should I try the other tests (missing-k8s, upstream-k8s)?

**Review by joestringer — APPROVED** [review]
LGTM, just needs a bpf.sha rebase.

**Comment by mrostecki** [comment]
test-me-please

**Pull request merged**
