### PR TITLE
1.6 Backport 19 08 07

### PR DESCRIPTION
**Pull request by jrfastab**
PR:
#8751 
#8771 
#8783 
#8785 
#8783 
#8787 
#8790 
#8798 
#8800 
#8801 
#8797 
#8796 
#8804 
#8793 
#8799 
#8806 
#8810 
#8811 
#8770

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8827)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Ci failed due to #8781, which is fixed by #8803. Retesting for now.

**Comment by jrajahalme** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]

**Comment by ianvernon** [comment]
Build failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14163/

* Namespace Selector test
* Kafka test
* L7 NodePort test

**Comment by ianvernon** [comment]
test-me-please

**Comment by tgraf** [comment]
Hit known flakes, fix is coming via #8839

**Pull request merged**
