### PR TITLE
pkg: Follow Go convention on capitalization

### PR DESCRIPTION
**Pull request by yulng**
Signed-off-by: yulng <wei.yang@daocloud.io>
According to the golang-lint specification, generic nouns need to be capitalized
Use API instead of Api
Thanks

### CODE REVIEW

**Review by christarazi — CHANGES_REQUESTED** [review]
Thanks for the PR. 

Could you add the justification that you added in the PR description to the commit msg also, and state that this is a cosmetic commit with no functional change?

Could you also re-word the commit title to say "pkg: Follow Go convention on capitalization"?

**Comment by yulng** [comment]
> Thanks for the PR.
> 
> Could you add the justification that you added in the PR description to the commit msg also, and state that this is a cosmetic commit with no functional change?
> 
> Could you also re-word the commit title to say "pkg: Follow Go convention on capitalization"?

ok ,commited it again ,Its changes have no functional change

**Review by tommyp1ckles — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by yulng** [comment]
> Signed-off-by: yulng [wei.yang@daocloud.io](mailto:wei.yang@daocloud.io) According to the golang-lint specification, generic nouns need to be capitalized Use API instead of Api Thanks

@nathanjsweet 😄😄

**Review by nathanjsweet — APPROVED** [review]

**Review by pchaigno — CHANGES_REQUESTED** [review]
Watch out for the commit format. You are missing a newline between the title and description. If you view it using `git log` you will see that it's broken.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
Smoke tests are passing and reviews are in. Given the trivial changes, I don't think we need to run the end-to-end tests.

**Pull request merged**
