### PR TITLE
Add more detailed proxy redirects status to `cilium status`

### PR DESCRIPTION
**Pull request by joestringer**
Add redirect information to the verbose cilium status:

```
$ cilium status --all-redirects
...
Proxy Status:           OK, ip 10.11.15.73, 1 redirects active on ports 10000-20000
  Protocol              Redirect              Proxy Port
  cilium-http-ingress   2886:ingress:TCP:80   11484
...
```

This is not 100% best formatting but it has a bunch of useful information for debugging proxy-related issues: the protocol and direction; endpoint id; L4 proto/port; host port used for redirection.

I avoided printing the number of active proxy ports right now since it seems like one proxy port is always enabled (DNS maybe?) and I figured that printing that prominently for all environments would cause more questions than it resolves.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10082)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Hit #9297 , just on k8s1.11. Otherwise CI is fine.

**Review by aanm — APPROVED** [review]
Changes LGTM, do we want to backport this to 1.7?

**Comment by joestringer** [comment]
I guess there's no harm in backporting it, never know when it could come in handy.

**Pull request merged**
