### PR TITLE
datapath: Use iproute2+libbpf

### LINKED ISSUE #16757: datapath: Loading with iproute2+libbpf
The list of tasks which needed in order to switch to loading BPF programs with libbpf via iproute2 (https://github.com/cilium/cilium/pull/15136):

- [x] Prefix section names of bpf_sock with `cgroup/`.
- [x] Switch to the old approach of handling .bss/.data sections for the static-data (https://github.com/cilium/libbpf/commit/93497fb759b48b087518ce568fb87b64a46157dd). The change requires us to maintain our own libbpf fork until we have changed the static-data implementation (e.g. to the BTF-based one).
- [x] Fix and upstream the wrong `prog_fd` setting in iproute2 resulting in a wrong prog being attached to TC BPF (https://github.com/cilium/iproute2/commit/203ed9b60d0480c86c62983b75921362f663b165, https://lore.kernel.org/netdev/20210705124307.201303-1-m@lambda.lt/T/#u).
- [x] Retry if map pinning fails in libbpf (same as done in iproute2 via https://github.com/cilium/iproute2/blob/pr/brb/static-data-v5.11-with-prog-fd-fix/lib/bpf_legacy.c#L1788, https://lore.kernel.org/bpf/20210705190926.222119-1-m@lambda.lt/).
- [x] Add a probe to libbpf to detect whether `BPF_GET_OBJ_INFO_BY_FD` exists, and if not, switch to `/proc/$PID/fdinfo/$FD` to derive map info when comparing pinned maps.

### PR DESCRIPTION
**Pull request by brb**
See commit msgs.

Fix https://github.com/cilium/cilium/issues/16757

```release-note
Use iproute2 with libbpf for loading datapath BPF programs
```

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-1.16-netnext

**Comment by brb** [comment]
test-1.19-5.4

**Comment by brb** [comment]
test-1.20-4.19

**Comment by brb** [comment]
test-1.21-4.9

**Comment by brb** [comment]
test-runtime

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-1.21-4.9

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-1.21-4.9

**Comment by brb** [comment]
test-1.21-4.9

**Comment by brb** [comment]
test-1.21-4.9

**Comment by brb** [comment]
test-1.21-4.9

**Comment by brb** [comment]
test-1.21-4.9

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failures:
* test-1.16-netnext - https://github.com/cilium/cilium/issues/16399 which we are currently investigating.
* ci-awscni - It should be fixed by https://github.com/cilium/cilium/pull/17122.
* ci-eks - It is currently unstable.

**Review by borkmann — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
FYI, I was surprised `verifier-test.sh` didn't need an update for the cgroup programs, but then discovered we skip those programs in that script by error. I filed https://github.com/cilium/cilium/issues/17125 for it.

**Comment by joestringer** [comment]
`release-note/minor` is to help inform users about changes that impact them. As far as I know this should not have any user-facing impact. Should this be `release-note/misc` instead?

**Review by tklauser — APPROVED** [review]

**Pull request merged**
