### PR TITLE
Update CNI to 1.2.0

### PR DESCRIPTION
**Pull request by michi-covalent**
[ upstream commit a1046bcc10b75c7130f0579d40d0529c85e1fe56 ]

Run `images/scripts/update-cni-version.sh 1.2.0` to update the CNI version.

Ref: https://github.com/containernetworking/plugins/releases/tag/v1.2.0
Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Comment by michi-covalent** [comment]
/test-backport-1.10

**Review by joestringer — APPROVED** [review]

**Comment by michi-covalent** [comment]
/ci-aks-1.10

**Review by joestringer — APPROVED** [review]

**Pull request merged**
