### PR TITLE
pkg/bpf: Include BPF map names during map creation

### PR DESCRIPTION
**Pull request by christarazi**
See previous commit for preparing for the main commit below:

----

This commit passes the name of the map to the bpf() syscall on map
creation. This allows bpftool via `bpftool map show` to show the map
names along side the maps.

Before:
```
8623: lpm_trie  flags 0x1
        key 24B  value 12B  max_entries 512000  memlock 20480000B
```

After:
```
8417: lpm_trie  name cilium_ipcache  flags 0x1
        key 24B  value 12B  max_entries 512000  memlock 20480000B
```

Signed-off-by: Chris Tarazi <chris@isovalent.com>

### CODE REVIEW

**Review by NikAleksandrov — APPROVED** [review]
LGTM, nice improvement.

**Comment by christarazi** [comment]
/test-1.16-4.9

**Comment by christarazi** [comment]
4.9 was failing legitimately because map names are not supported below 4.15, see https://github.com/torvalds/linux/commit/ad5b177bd73f5. I've implemented logic to handle this case. Please re-review.

**Review by NikAleksandrov — APPROVED** [review]

**Pull request merged**
