### PR TITLE
update cilium to golang 1.10.3

### PR DESCRIPTION
**Pull request by aanm**
(adding `area/k8s` to run more tests)

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4602)

### CODE REVIEW

**Review by rlenglet — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
flake #4615

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
Timeout: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/406/

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Pull request closed without merging**
