### PR TITLE
Add ability to use cilium config map in cilium-operator automatically

### PR DESCRIPTION
**Pull request by aanm**
Please read commit by commit. I tried to make gradual changes but it was a little difficult with the flags.

```release-note
Cilium Operator can now use the flags specified `cilium-config` k8s configuration map
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10347)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by ungureanuvladvictor — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 11 of 11 files at r2, 6 of 6 files at r3, 3 of 3 files at r4, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cilium/cilium/10347)* status: :shipit: complete! all files reviewed, 7 unresolved discussions (waiting on @aanm)

___
*[install/kubernetes/quick-install.yaml, line 121 at r5](https://reviewable.io/reviews/cilium/cilium/10347#-M11XF_HA2jsg_-WQP9W:-M11XF_HA2jsg_-WQP9X:b-dxsqq) ([raw file](https://github.com/cilium/cilium/blob/3c2d8fc29c138df191c1ce6ddbb74979ddfc780d/install/kubernetes/quick-install.yaml#L121)):*
> ```YAML
> 
>   masquerade: "true"
>   enable-xt-socket-fallback: "true"
> ```

Was this missing from somewhere? 
___
*[install/kubernetes/quick-install.yaml, line 411 at r5](https://reviewable.io/reviews/cilium/cilium/10347#-M11WnXZ4as-iVIjxgM-:-M11WnXZ4as-iVIjxgM0:b-e1pnx5) ([raw file](https://github.com/cilium/cilium/blob/3c2d8fc29c138df191c1ce6ddbb74979ddfc780d/install/kubernetes/quick-install.yaml#L411)):*
> ```YAML
>               - /cni-uninstall.sh
>         resources:
>           {}
> ```

Do you think it's valuable to leave this here but with empty resources block?
___
*[install/kubernetes/cilium/charts/config/templates/configmap.yaml, line 66 at r5](https://reviewable.io/reviews/cilium/cilium/10347#-M11X2Wy3GRwGVac9iln:-M11X2Wy3GRwGVac9ilo:b-2irkqi) ([raw file](https://github.com/cilium/cilium/blob/3c2d8fc29c138df191c1ce6ddbb74979ddfc780d/install/kubernetes/cilium/charts/config/templates/configmap.yaml#L66)):*
> ```YAML
>   # which the Cilium Operator will have their metrics exposed.
>   # NOTE that this will open the port on the nodes where Cilium operator pods
>   # are scheduled.
> ```

`where Cilium operator pod is scheduled` since we cannot run the operator in HA mode?
___
*[operator/flags.go, line 82 at r2](https://reviewable.io/reviews/cilium/cilium/10347#-M11L48d0MmQIFhO8qzc:-M11L48d0MmQIFhO8qzd:b-n8u3b9) ([raw file](https://github.com/cilium/cilium/blob/47b11aaf3ce3b8f92d459817c746a9d78ce4809f/operator/flags.go#L82)):*
> ```Go
> 	option.BindEnv(option.CNPNodeStatusGCInterval)
> 
> 	flags.Duration(option.CNPStatusUpdateInterval, 1*time.Second, "interval between CNP status updates sent to the k8s-apiserver per-CNP")
> ```

`s/interval/Interval` just to keep it consistent related to capitalization of other description of options.
___
*[operator/flags.go, line 154 at r2](https://reviewable.io/reviews/cilium/cilium/10347#-M11K2UY3lHhnqNvacTB:-M11K2UY3lHhnqNvacTC:b-hcgu0x) ([raw file](https://github.com/cilium/cilium/blob/47b11aaf3ce3b8f92d459817c746a9d78ce4809f/operator/flags.go#L154)):*
> ```Go
> 	option.BindEnv(option.Version)
> 
> 	// TODO: Urgent fix
> ```

Fix related to ?
___
*[operator/main.go, line 136 at r2](https://reviewable.io/reviews/cilium/cilium/10347#-M11UJqZ0SZAPBgfeweW:-M11UJqZ0SZAPBgfeweX:b-17ed5b) ([raw file](https://github.com/cilium/cilium/blob/47b11aaf3ce3b8f92d459817c746a9d78ce4809f/operator/main.go#L136)):*
> ```Go
> 		option.Config.K8sAPIServer,
> 		option.Config.K8sKubeConfigPath,
> 		float32(option.Config.K8sClientQPSLimit),
> ```

`option.Config.K8sClientQPSLimit` is of type `float32` already, don't think you need the cast
___
*[operator/metrics.go, line 43 at r3](https://reviewable.io/reviews/cilium/cilium/10347#-M11Vz5n9eKZE3pIc3vG:-M11Vz5oCrHPclifdPft:b-dmv58x) ([raw file](https://github.com/cilium/cilium/blob/5c2b31b19152cacc4c3f131e01773223a2c0a0fd/operator/metrics.go#L43)):*
> ```Go
> func getPrometheusServerAddr() string {
> 	if option.Config.OperatorPrometheusServeAddr == "" {
> 		return metricsAddress
> ```

given we'll use `metricsAddress` just here is it worth keeping in `operator/main.go`?

**Comment by aanm** [comment]
> > Reviewed 2 of 2 files at r1, 11 of 11 files at r2, 6 of 6 files at r3, 3 of 3 files at r4, 6 of 6 files at r5.
> > _[Reviewable](https://reviewable.io/reviews/cilium/cilium/10347)_ status: :shipit: complete! all files reviewed, 7 unresolved discussions (waiting on @aanm)
> 
> _[install/kubernetes/quick-install.yaml, line 121 at r5](https://reviewable.io/reviews/cilium/cilium/10347#-M11XF_HA2jsg_-WQP9W:-M11XF_HA2jsg_-WQP9X:b-dxsqq) ([raw file](https://github.com/cilium/cilium/blob/3c2d8fc29c138df191c1ce6ddbb74979ddfc780d/install/kubernetes/quick-install.yaml#L121)):_
> 
> > ```yaml
> >   masquerade: "true"
> >   enable-xt-socket-fallback: "true"
> > ```
> 
> Was this missing from somewhere?
> 

This file is auto generated it was probably some older PR that merged changes without generating the file

> _[install/kubernetes/quick-install.yaml, line 411 at r5](https://reviewable.io/reviews/cilium/cilium/10347#-M11WnXZ4as-iVIjxgM-:-M11WnXZ4as-iVIjxgM0:b-e1pnx5) ([raw file](https://github.com/cilium/cilium/blob/3c2d8fc29c138df191c1ce6ddbb74979ddfc780d/install/kubernetes/quick-install.yaml#L411)):_
> 
> > ```yaml
> >               - /cni-uninstall.sh
> >         resources:
> >           {}
> > ```
> 
> Do you think it's valuable to leave this here but with empty resources block?

This file is auto generated it was probably some older PR that merged changes without generating the file. But to answer your question, this does seem suspicious. I've open https://github.com/cilium/cilium/issues/10350 to track this.

> 
> _[install/kubernetes/cilium/charts/config/templates/configmap.yaml, line 66 at r5](https://reviewable.io/reviews/cilium/cilium/10347#-M11X2Wy3GRwGVac9iln:-M11X2Wy3GRwGVac9ilo:b-2irkqi) ([raw file](https://github.com/cilium/cilium/blob/3c2d8fc29c138df191c1ce6ddbb74979ddfc780d/install/kubernetes/cilium/charts/config/templates/configmap.yaml#L66)):_
> 
> > ```yaml
> >   # which the Cilium Operator will have their metrics exposed.
> >   # NOTE that this will open the port on the nodes where Cilium operator pods
> >   # are scheduled.
> > ```
> 
> `where Cilium operator pod is scheduled` since we cannot run the operator in HA mode?

:+1: 

> 
> _[operator/flags.go, line 82 at r2](https://reviewable.io/reviews/cilium/cilium/10347#-M11L48d0MmQIFhO8qzc:-M11L48d0MmQIFhO8qzd:b-n8u3b9) ([raw file](https://github.com/cilium/cilium/blob/47b11aaf3ce3b8f92d459817c746a9d78ce4809f/operator/flags.go#L82)):_
> 
> > ```go
> > 	option.BindEnv(option.CNPNodeStatusGCInterval)
> > 
> > 	flags.Duration(option.CNPStatusUpdateInterval, 1*time.Second, "interval between CNP status updates sent to the k8s-apiserver per-CNP")
> > ```
> 
> `s/interval/Interval` just to keep it consistent related to capitalization of other description of options.
> 
:+1: 

> _[operator/flags.go, line 154 at r2](https://reviewable.io/reviews/cilium/cilium/10347#-M11K2UY3lHhnqNvacTB:-M11K2UY3lHhnqNvacTC:b-hcgu0x) ([raw file](https://github.com/cilium/cilium/blob/47b11aaf3ce3b8f92d459817c746a9d78ce4809f/operator/flags.go#L154)):_
> 
> > ```go
> > 	option.BindEnv(option.Version)
> > 
> > 	// TODO: Urgent fix
> > ```
> 
> Fix related to ?

This was intended for me to not forget about it. I'll fix it once the PR is merged since it requires backport to 1.7. It's basically because the operator is opening that port on host network level to serve `health` requests to kubelet.

> 
> _[operator/main.go, line 136 at r2](https://reviewable.io/reviews/cilium/cilium/10347#-M11UJqZ0SZAPBgfeweW:-M11UJqZ0SZAPBgfeweX:b-17ed5b) ([raw file](https://github.com/cilium/cilium/blob/47b11aaf3ce3b8f92d459817c746a9d78ce4809f/operator/main.go#L136)):_
> 
> > ```go
> > 		option.Config.K8sAPIServer,
> > 		option.Config.K8sKubeConfigPath,
> > 		float32(option.Config.K8sClientQPSLimit),
> > ```
> 
> `option.Config.K8sClientQPSLimit` is of type `float32` already, don't think you need the cast
> 
it's of type `float64`. Unfortunately, viper does not have `viper.GetFloat32`

> _[operator/metrics.go, line 43 at r3](https://reviewable.io/reviews/cilium/cilium/10347#-M11Vz5n9eKZE3pIc3vG:-M11Vz5oCrHPclifdPft:b-dmv58x) ([raw file](https://github.com/cilium/cilium/blob/5c2b31b19152cacc4c3f131e01773223a2c0a0fd/operator/metrics.go#L43)):_
> 
> > ```go
> > func getPrometheusServerAddr() string {
> > 	if option.Config.OperatorPrometheusServeAddr == "" {
> > 		return metricsAddress
> > ```
> 
> given we'll use `metricsAddress` just here is it worth keeping in `operator/main.go`?

good point, will do

**Comment by aanm** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Docs changes LGTM. I didn't look at the other changes in detail.

**Comment by joestringer** [comment]
test-docs-please

**Review by ungureanuvladvictor — APPROVED** [review]
> Reviewed 20 of 20 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cilium/cilium/10347)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
