### PR TITLE
[v1.6] update k8s testing versions

### PR DESCRIPTION
**Pull request by aanm**
```release-note
update k8s tested versions to v1.14.10, v1.15.7 and v1.16.4
```

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9870)

### CODE REVIEW

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
never-tell-me-odds

**Review by nebril — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
