### PR TITLE
v1.14 Backports 2023-12-20

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
* [x] #29809 (@marseel)
 * [x] #29880 (@julianwiedmann)

⚠️ Conflict observed, see backporter's note for more details
 * [x] #28588 (@joamaki)
 * [x] #29957 (@gandro)
 * [x] #29616 (@learnitall)
 * [x] #29815 (@jrajahalme)

⚠️ Skipped
- #27427 (@tklauser)
  - Dependency commit ced01f6 doesn't exist on v1.14 branch
- #29849 (@brb)
  - There's no workflow using `CILIUM_CLI_VERSION`

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 28588 29809 29957 29880 29616 29815
```

### CODE REVIEW

**Comment by YutaroHayakawa** [comment]
/test-backport-1.14

**Comment by YutaroHayakawa** [comment]
/test-backport-1.14

**Review by julianwiedmann — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
Conformance AKS: https://github.com/cilium/cilium/issues/30002

**Review by joamaki — APPROVED** [review]

**Review by marseel — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Review by learnitall — CHANGES_REQUESTED** [review]
Changes LGTM, but I'm not sure I understand the backporter note that you left. It says:

```
[ backporter's note: backporter's note: Conflict due to the
  do_netdev_encrypt_encap doesn't exist on v1.12 branch. Removed it. ]
```

But the change on line 980 in `bpf/bpf_host.c` is inside the function `do_netdev_encrypt_encap`. Maybe I'm misunderstanding something?

**Comment by YutaroHayakawa** [comment]
@learnitall Same for https://github.com/cilium/cilium/pull/30004#issuecomment-1884181251. Sorry for the confusion. Fixed the message in the latest push.

**Comment by YutaroHayakawa** [comment]
/test-backport-1.14

**Review by learnitall — APPROVED** [review]
Thank you!

**Review by jrajahalme — APPROVED** [review]

**Review by tommyp1ckles — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]

**Pull request merged**
