### PR TITLE
1.1 backports 2018-10-11

### PR DESCRIPTION
**Pull request by joestringer**
* #5842
  * Backport #5652 to resolve conflict
* #5855
* #5856

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5864)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Infra issue. Re-running tests.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Suspected flake, filed #5867. Re-trying.

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
https://github.com/cilium/cilium/issues/5867 is a known flake in prior branches due to issues with the Kafka containers we use - this was fixed in latest master. Trying again.

**Comment by ianvernon** [comment]
test-me-please

**Comment by aanm** [comment]
@tgraf @borkmann @nebril @jrajahalme please take a look

**Review by borkmann — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Pull request merged**
