### PR TITLE
envoy: Update generated Cilium protobufs and integration test.

### PR DESCRIPTION
**Pull request by jrajahalme**
We include the go sources generated from the Cilium filter protobufs
in the git repo, but forgot to update them after a recent envoy
rebase. Merge the updated files so that they do not need to be
generated every time Cilium is built.

Cilium integration test for Envoy is not run in the CI, so we've
failed to update it to match the Envoy sources we use as a
dependency. Update the integration test so that it passes in manual
tests.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4235)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Rebased and added fixes for the integration test.

**Review by rlenglet — APPROVED** [review]

**Comment by jrajahalme** [comment]
Rebased.

**Comment by jrajahalme** [comment]
test-me-please

**Pull request merged**
