### PR TITLE
Fix sphinx documentation warnings

### PR DESCRIPTION
**Pull request by joestringer**
This series fixes various sphinx warnings in the docs directory, cleans up the docs container usage and adds a dummy documentation build to the `postcheck` target so that developers can more easily tell when they're potentially breaking the docs in some way.

I'm a bit on the fence about adding the dummy docs target to postcheck. It's nice because it'll show up for everyone when running `make` (and hopefully encourage people to keep the docs working correctly), but it'll also add a few seconds to the build. On the other hand, you can always skip it by running `make build`.

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by raybejjani — DISMISSED** [review]
I'd love to have a docs check in the build, or in the tests, but we don't seem to install the sphinx packages in the dev vm by default. This means you can't just build (we also don't list them in the developer requirements but page seems broken right now. This can all be fixed but I'm not sure how to manage virtualenv setups with this. I suppose one can enter that env before invoking make.

I suppose the ask I have is just add "install the doc dependencies" to the main list of developer ones.

**Comment by raybejjani** [comment]
Oh, this may be a non-issue we we merge the CI and dev images but I'm not sure how close that is to being done

**Comment by joestringer** [comment]
>I'd love to have a docs check in the build, or in the tests, but we don't seem to install the sphinx packages in the dev vm by default. This means you can't just build (we also don't list them in the developer requirements but page seems broken right now. This can all be fixed but I'm not sure how to manage virtualenv setups with this. I suppose one can enter that env before invoking make.

As it turns, out, this PR should fix the broken developer requirements ;)

I thought about this, and realised that if I just add a `-` to the make target, it will relax the requirement but still run if someone has sphinx installed. This seems like a good middle ground.

**Comment by joestringer** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]
api bits LGTM

**Review by ianvernon — APPROVED** [review]

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
