### PR TITLE
bpf: use bounded loops in pcap recorder and nat engine

### PR DESCRIPTION
**Pull request by borkmann**
See commit msgs. Follow-up to https://github.com/cilium/cilium/pull/18592. (dep: https://github.com/cilium/cilium/pull/18597)

### CODE REVIEW

**Review by brb — APPROVED** [review]
:rocket:

**Review by kkourt — APPROVED** [review]
🚀

**Comment by borkmann** [comment]
Closing for now. From debugging turns out that with bounded loops, LLVM will move the rule mask (pcap recorder) into .rodata section as otherwise overhead of having it on-stack becomes too large for >=5 masks. That breaks however with `bpf_xdp.o: load data sections: data section .rodata: can't get BTF: type .rodata: not found" subsys=recorder`, given we have different global data handling. With pragma unroll this situation doesn't happen as the unrolled loop is populating one mask at a time, so even >= 32 masks work just fine.

**Comment by ti-mo** [comment]
Feels like this is related to https://lore.kernel.org/bpf/CAK3+h2wcDceeGyFVDU3n7kPm=zgp7r1q4WK0=abxBsj9pyFN-g@mail.gmail.com.

The BTF-related error is returned by `cilium/ebpf`, but the libbpf version used by iproute2 equally rejects these programs since they contain relo's for a non-global data section (hence why there is no BTF for it). This seems to occur when accessing static data from a loop.

**Comment by ti-mo** [comment]
I've posted a follow-up on this to the list: https://lore.kernel.org/bpf/a141fab8-d848-23bc-87c4-929eba183506@incline.eu.
Thanks to @dylandreimerink for helping find a minimal reproducer!

There's a known issue/corner case in LLVM that trips up the loader(s). If a data section contains only anonymous bytes, e.g. if all static data is provided to the program using `define`s, no debug info is generated for that section, resulting in no BTF emitted.

`.rodata` specifically is special-cased in newer LLVMs since https://reviews.llvm.org/D84002?id=278663, but as mentioned in the mailing list thread, sometimes things end up in different sections like `.rodata.cst32`. Same thing happened with https://github.com/cilium/cilium/pull/17370. @vincentmli 

Since we have a good repro, we can teach `cilium/ebpf` to process `.(ro)data*` sections and return error when trying to replace non-existent constants instead of rejecting the whole data section.

**Pull request closed without merging**
