### PR TITLE
Test: Update cilium stable image to v1.0.4

### PR DESCRIPTION
**Pull request by eloycoto**
Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4747)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by eloycoto** [comment]
Kafka issue: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/471/

**Comment by eloycoto** [comment]
test-missed-k8s

**Comment by eloycoto** [comment]
I think that this one can be merged. The issue with 1.11 and 1.12 will always happens until core-dns support is in there. 

What do you think @aanm ?

**Comment by eloycoto** [comment]
test-missed-k8s

**Pull request merged**
