### PR TITLE
update k8s dependencies to 1.26.4

### PR DESCRIPTION
**Pull request by aanm**
The last client-go version contains an important bug fix. See https://github.com/kubernetes/kubernetes/pull/115901 for more info.

```release-note
Fix missing delete events on informer re-lists to ensure all delete events are correctly emitted and using the latest known object state, so that all event handlers and stores always reflect the actual apiserver state as best as possible
```

### CODE REVIEW

**Comment by aanm** [comment]
/test-backport-1.13

**Comment by aanm** [comment]
/test-1.18-4.9

**Comment by aanm** [comment]
/test-1.23-4.9

**Review by michi-covalent — APPROVED** [review]

**Pull request merged**
