### PR TITLE
daemon: Don't tunnel locally destined traffic

### PR DESCRIPTION
**Pull request by joestringer**
Previously, traffic from the local host that is destined to a local
endpoint was sent via the tunnel device to deliver the traffic locally.
This allowed traffic to pass, but was inefficient and caused the traffic
to be misidentified in monitor output.

When populating IPCache entries, check whether the hostIP points to the
external IP of the local node and if this is the case, don't populate
the host IP. As a result, this traffic should be delivered locally to
the destination endpoint device without sending via the tunnel.

Fixes: #4918

This bug only affects master/1.2, so there is no need to backport this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5032)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by joestringer** [comment]
@ianvernon do we need to release note every bugfix that's only been broken on master between releases?

**Comment by tgraf** [comment]
> do we need to release note every bugfix that's only been broken on master between releases?

We only need to release note bugs for released (non-rc) Cilium releases. Regressions fixed within the dev cycle do not need to be release noted

**Comment by ianvernon** [comment]
Makes sense, sorry for the noise!

**Comment by tgraf** [comment]
test-me-please

**Comment by joestringer** [comment]
Something went wrong in Jenkins, terminated with timeout:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5368/execution/node/93/log/?consoleFull

```
17:03:47     k8s1-1.11: docker build --build-arg LOCKDEBUG=1 -t "cilium/cilium:"latest"" .
19:01:30 Sending interrupt signal to process
19:01:30 Sending interrupt signal to process
19:01:40 After 10s process did not stop
```

Rebased and will re-run CI.

**Comment by joestringer** [comment]
test-me-please

**Pull request merged**
