### PR TITLE
vagrant: Upgrade Vagrant box versions

### PR DESCRIPTION
**Pull request by aditighag**
These include Go 1.16.

### CODE REVIEW

**Review by kkourt — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Review by nbusseneau — APPROVED** [review]

**Comment by aditighag** [comment]
test-runtime

**Comment by pchaigno** [comment]
test-runtime

**Review by pchaigno — APPROVED** [review]

**Comment by tklauser** [comment]
test-runtime

**Comment by pchaigno** [comment]
test-runtime

**Pull request merged**
