### PR TITLE
Update CNI to 1.3.0

### PR DESCRIPTION
**Pull request by jrajahalme**
[ upstream commit 4ebf4e7a81a8f60154d693ecf4c844f6bdcb62e6 ]

Run `images/scripts/update-cni-version.sh 1.3.0` to update the CNI version.

Ref: https://github.com/containernetworking/plugins/releases/tag/v1.3.0

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.11

**Comment by jrajahalme** [comment]
/test-backport-1.11

**Comment by sayboras** [comment]
/test-backport-1.11

**Review by aanm — APPROVED** [review]

**Review by brlbil — APPROVED** [review]

**Comment by jrajahalme** [comment]
test-1.22-4.19 hit flake #15455

**Pull request merged**
