### PR TITLE
k8s: update k8s dependencies to 1.17.9

### PR DESCRIPTION
**Pull request by aanm**
Also update k8s testing versions to 1.17.9

Signed-off-by: André Martins <andre@cilium.io>

Backport of https://github.com/cilium/cilium/pull/12674

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.7

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-backport-1.7

**Comment by aanm** [comment]
restart-ginkgo

**Comment by aanm** [comment]
restart-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Review by rolinh — APPROVED** [review]

**Pull request merged**
