### PR TITLE
v1.13 Backports 2024-04-18

### PR DESCRIPTION
**Pull request by giorio94**
* [x] #31886 (@sharlns) :warning: resolved conflicts
    * :information_source: Manually added the `rm-tetragon` target, and skipped the adopters hunk, as already not present.
 * [x] #31970 (@joestringer)
 * [x] #31959 (@marseel) :warning: resolved conflicts
   * :information_source: Trivial conflicts in `go.{mod,sum}`.
 * [x] #32004 (@jrajahalme) :warning: resolved conflicts
   * :information_source: Applied the same hunk to the `stream.go` file.
 * [x] #31958 (@giorio94) :warning: resolved conflicts
    * :information_source: Trivial conflicts due to different surrounding context, accepted combination.
 * [x] #31061 (@sayboras)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31061 31886 31970 31959 32004 31958
```

### CODE REVIEW

**Comment by giorio94** [comment]
/test-backport-1.13

**Comment by giorio94** [comment]
The test-runtime failure is legitimate, and it appears to have been introduced by https://github.com/cilium/cilium/pull/32053/commits/030d9c15f9ba036931c10e2cb580088bac87491d. 

@jrajahalme Could you please take a look at what could be different wrt the main branch?

```
$ go test ./pkg/envoy/xds -count 1

time="2024-04-18T18:47:52+02:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-18T18:47:52+02:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="sidecar~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-18T18:47:52+02:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-18T18:47:52+02:00" level=warning msg="NACK received for versions after 1 and up to 2; waiting for a version update before sending again" subsys=xds xdsAckedVersion=1 xdsClientNode="sidecar~10.0.0.0~node0~bar" xdsDetail=NACKNACK xdsNonce=2 xdsStreamID=1 xdsTypeURL=type.googleapis.com/envoy.config.v3.DummyConfiguration
time="2024-04-18T18:47:52+02:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="sidecar~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-18T18:47:52+02:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-18T18:47:52+02:00" level=warning msg="NACK received for versions after  and up to 1; waiting for a version update before sending again" subsys=xds xdsAckedVersion= xdsClientNode="sidecar~10.0.0.0~node0~bar" xdsDetail= xdsNonce=1 xdsStreamID=1 xdsTypeURL=type.googleapis.com/envoy.config.v3.DummyConfiguration
time="2024-04-18T18:47:52+02:00" level=warning msg="NACK received for versions after  and up to 2; waiting for a version update before sending again" subsys=xds xdsAckedVersion= xdsClientNode="sidecar~10.0.0.0~node0~bar" xdsDetail= xdsNonce=2 xdsStreamID=1 xdsTypeURL=type.googleapis.com/envoy.config.v3.DummyConfiguration
time="2024-04-18T18:47:52+02:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="sidecar~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-18T18:47:52+02:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-18T18:47:52+02:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="sidecar~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-18T18:47:52+02:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-18T18:47:52+02:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="sidecar~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-18T18:47:52+02:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-18T18:47:52+02:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="sidecar~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-18T18:47:52+02:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-18T18:47:54+02:00" level=error msg="error while receiving request from xDS stream" error="context deadline exceeded" subsys=xds xdsClientNode="sidecar~10.0.0.0~node0~bar" xdsStreamID=1
time="2024-04-18T18:47:54+02:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="sidecar~10.0.0.0~node0~bar" xdsStreamID=1

----------------------------------------------------------------------
FAIL: server_e2e_test.go:644: ServerSuite.TestRequestStaleNonce

server_e2e_test.go:736:
    c.Assert(err, IsNil)
... value context.deadlineExceededError = context.deadlineExceededError{} ("context deadline exceeded")

time="2024-04-18T18:47:54+02:00" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-04-18T18:47:54+02:00" level=info msg="xDS stream closed" subsys=xds xdsClientNode="sidecar~10.0.0.0~node0~bar" xdsStreamID=1
OOPS: 18 passed, 1 FAILED
--- FAIL: Test (2.01s)
FAIL
FAIL    github.com/cilium/cilium/pkg/envoy/xds  2.238s
FAIL
```

**Review by marseel — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
Approving for backport of my PR.

**Review by christarazi — APPROVED** [review]

**Comment by giorio94** [comment]
> The test-runtime failure is legitimate, and it appears to have been introduced by [030d9c1](https://github.com/cilium/cilium/commit/030d9c15f9ba036931c10e2cb580088bac87491d).

Fixed additionally backporting https://github.com/cilium/cilium/pull/31061. Thanks @jrajahalme for looking into it!

**Comment by giorio94** [comment]
/test-backport-1.13

**Review by sayboras — APPROVED** [review]

**Comment by giorio94** [comment]
/test-1.21-4.19

**Review by jrajahalme — APPROVED** [review]

**Comment by giorio94** [comment]
CI is green, reviews are in, marking ready to merge.

**Review by aditighag — APPROVED** [review]

**Pull request merged**
