### PR TITLE
egressgw: drop traffic when gateway node is not configured for policy

### PR DESCRIPTION
**Pull request by julianwiedmann**
> As worker nodes have no insight whether a gateway node is actually able to
> handle forwarded traffic, the gateway node needs to handle traffic where
> the matching EGW policy entry is non-functional.
> 
> One example is policy entries where the agent was unable to derive a valid
> egressIP. Drop traffic that matches such a policy entry, instead of
> SNATing it with 0.0.0.0.

### CODE REVIEW

**Comment by msune** [comment]
Dead?

**Review by nathanjsweet — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by ysksuzuki — APPROVED** [review]

**Comment by julianwiedmann** [comment]
@glibsm shine a light of approval on this innocent PR? :pray:

**Review by glibsm — APPROVED** [review]

**Pull request merged**
