### PR TITLE
bpf: Do not account tx for CT_SERVICE

### PR DESCRIPTION
**Pull request by brb**
It's already accounted for `CT_EGRESS`.

(Same as in https://github.com/cilium/cilium/pull/7060)

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7119)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Comment by joestringer** [comment]
Compile failed.

We also need to validate this against the additional complexity introduced using `bpf/test/verifier-test.sh`. Be aware that we may already be exceeding the maximum complexity limits in specific configurations, see #7092 . For some brief notes on verifier complexity, see #5130 .

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
Thanks for the info on the verifier complexity topic.

I think in the future we can merge `ct_entry.{rx,tx}_packets` and `ct_entry.{rx,tx}_bytes` fields (as part of #7106), so the if-statements could be rewritten to:

```
if (dir != CT_SERVICE) {
    entry.packets = 1;
    entry.bytes = skb->len;
}
```

This would reduce the complexity.

**Review by joestringer — APPROVED** [review]
I manually tested this change against #7092 and surprisingly it reduced complexity (from 15 insns over to 12 insns over the limit).

Not sure what's going on with the CI, but the change LGTM.

**Comment by joestringer** [comment]
> I think in the future we can merge ct_entry.{rx,tx}_packets and ct_entry.{rx,tx}_bytes fields (as part of #7106), so the if-statements could be rewritten to:
> 
>    if (dir != CT_SERVICE) {
>        entry.packets = 1;
>        entry.bytes = skb->len;
>    }
> This would reduce the complexity.

This might not necessarily be the case. If all of the callers are passing the hardcoded dir in, then maybe the compiler is seeing the `if (dir == CT_INGRESS)` and compiling out the if/else and directly compiling in the contents of the conditional statement. I'll believe it when I see the numbers from `test/bpf/check-complexity.sh` :-)

**Comment by brb** [comment]
test-me-please

**Comment by wenlxie** [comment]
The dir=CT_SERVICE are not accounted for the packets/bytes,  so this metrics had been missed,  is there any plan to enhance this?

**Comment by brb** [comment]
@wenlxie There is no plan. Also, the rx stat fields are used to store other info.

**Comment by wenlxie** [comment]
@brb Thanks for reply. 
We are using cilium xdp geneve dsr mode  as L4 load balancer. The metrics for observation like connections/pkts/bytes of  the vip and vip's backends are very important to provide observation for the products.
If cilium can support this, it should a really helpful feature.

**Comment by brb** [comment]
@wenlxie Got it. Can you please create a separate CFP issue?

**Comment by wenlxie** [comment]
@brb  Thanks 
https://github.com/cilium/cilium/issues/27452

**Pull request merged**
