### PR TITLE
v1.11 backport: fix multi option parsing

### PR DESCRIPTION
**Pull request by bimmlerd**
Backport of https://github.com/cilium/cilium/pull/22299

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 22299; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Comment by bimmlerd** [comment]
/test-backport-1.11

**Review by thorn3r — APPROVED** [review]
thanks for backporting this patch :+1: 
CI failures look related to using a newer, unsupported K8s version and should be fixed by this PR: https://github.com/cilium/cilium/pull/22724

**Comment by joestringer** [comment]
👍 https://github.com/cilium/cilium/pull/22724 is now backported, we should be able to rebase and see that the CI issues are solved.

**Comment by joestringer** [comment]
I took a fresh look at the backport PR content and it seems highly unlikely that CI will pick up any further issues with the backport. Merging.

**Pull request merged**
