### PR TITLE
Bump cilium/ubuntu-next version to 31

### PR DESCRIPTION
**Pull request by brb**
* The VM image has kernel 5.2.0-rc5+ with the overlayfs overlap check being disabled which used to prevent Docker from running on it ((see https://github.com/cilium/packer-ci-build/pull/163 for more details).
* Includes the fix in the bpf-next tree to prevent the verifier from pruning the valid code (https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=a3ce685dd01a786fa5bc388e47d0066a4f842591).

The new image is needed for the upcoming host-lb/NodePort CI tests.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8442)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by brb** [comment]
Seems that CI failed due to `cilium-etcd-operator` failing to provision etcd instances. Re-running.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failed due to:
```
2019-07-02T13:48:07.514Z]     k8s1-1.15: error pulling image configuration: received unexpected HTTP status: 502 Bad Gateway
[2019-07-02T13:48:07.514Z]     k8s1-1.15: Makefile:187: recipe for target 'docker-operator-image' failed
[2019-07-02T13:48:07.514Z]     k8s1-1.15: make: *** [docker-operator-image] Error 1
```

**Comment by brb** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by brb** [comment]
Many Runtime test failures: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13378/#showFailuresLink.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
Hit the bug in the verifier, re-building the VM image to include the fix (https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=a3ce685dd01a786fa5bc388e47d0066a4f842591).

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failed due to timeout (waited > 3hr to be scheduled).

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
Hit the RuntimePrivilegedUnitTests flake:

```
node_linux_test.go:668:
	     c.Assert(err, check.IsNil)
	 ... value *errors.errorString = &errors.errorString{s:"route to destination 4.4.4.4 contains gateway 4.4.4.4, must be directly reachable"} ("route to destination 4.4.4.4 contains gateway 4.4.4.4, must be directly reachable")
```

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
Same `RuntimePrivilegedUnitTests` flake.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failed due to provisioning errors.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failed due to provisioning errors.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI provision error:
```
[2019-07-05T21:01:31.037Z]     k8s2-1.10: [discovery] Failed to request cluster info, will try again: [Get https://192.168.36.11:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 192.168.36.11:6443: getsockopt: no route to host]
```

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failed due to the `RuntimePrivilegedUnitTests` flake. Perhaps this can be merged?

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
Same `RuntimePrivilegedUnitTests` failure.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Pull request merged**
