### PR TITLE
v1.9 backports 2020-11-17

### PR DESCRIPTION
**Pull request by kaworu**
* #13969 -- ci: log in to docker in vagrant boxes (@nebril)
 * #13754 -- test: Switch from Cilium test logger to Ginkgo (@manuelbuil)
 * #13976 -- checkpatch: update image tag to latest (@qmonnet)
 * #13992 -- fqdn: Make maximum number of IPs per restored rule configurable (@jrajahalme)
 * #13912 -- ctmap: GC orphan SNAT entries (@brb)
 * #13991 -- dnsproxy: print total number of rules if too many (@kkourt)
 * #13986 -- docs: Replace outdated backporting docs with link (@twpayne)
 * #13994 -- Hubble-Relay: proxy metadata from originating client (@nathanjsweet)
 * #14023 -- helm/hubble-ui: fixed ingress configuration on EKS clusters (@mvisonneau)
 * #13865 -- ipam: Fix ENI IPAM on smaller instance types (@christarazi)
 * #13996 -- pkg/k8s: trim spaces from loadBalancerSourceRanges (@aanm)
 * #14053 -- ci/github: Replace set-env command by echo (@sayboras)
 * #14042 -- doc/hubble-internals: update Hubble Relay section to reflect current state (@Rolinh)
 * #14044 -- test: Bump migrate-svc-test image (@brb)
 * #13884 -- cilium: fix redirect limits on multi dev case (@borkmann)

Ignored by this PR:
 * #13347 -- bpf: add metrics for fragmented ipv4 packets (@jibi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13969 13754 13976 13992 13912 13991 13986 13994 14023 13865 13996 14053 14042 14044 13884; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Review by borkmann — APPROVED** [review]

**Comment by kAworu** [comment]
@jibi please take a careful look at your patch set from https://github.com/cilium/cilium/pull/13347, as I had to resolve conflicts. More specifically theses commits (I've updated the commit message to locate the conflicts):
* 938b4940f92bd3754568cad230916e64fa5b4a7a via 4b95484c89783a4df374720467a903e1b4d0f302 ("bpf: add metrics for fragmented IPv4 packets")
* a78f75e1eb1dd37e107be01eec6ba7db53ad6f4f via 217ebb565aafca50eed2c27fd022e154ec86e3f0 ("bpf: reduce complexity of logic to handle IPv4 fragments")

**Review by kkourt — APPROVED** [review]

**Review by twpayne — APPROVED** [review]
LGTM for my trivial changes.

**Review by qmonnet — APPROVED** [review]
> #13976 -- checkpatch: update image tag to latest (@qmonnet)

Looks good, thank you!

**Review by brb — APPROVED** [review]
LGTM for my changes, thanks.

**Comment by kAworu** [comment]
Removed https://github.com/cilium/cilium/pull/13347 patch set at @jibi's request to be backported later on.

**Review by christarazi — APPROVED** [review]
LGTM for my commits

**Review by aanm — APPROVED** [review]
LGTM for my changes

**Comment by kAworu** [comment]
test-backport-1.9

**Review by nathanjsweet — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
Looks good for my commit

**Pull request merged**
