### PR TITLE
bpf: host: restore HostFW for overlay traffic in to-netdev

### PR DESCRIPTION
**Pull request by julianwiedmann**
https://github.com/cilium/cilium/pull/31082 missed one detail in how the HostFW was relying on the packet mark. Restore the old behaviour.

### CODE REVIEW

**Comment by julianwiedmann** [comment]
Note that I'm not 100% sure whether we *want* this behaviour - there's an argument to be made that the HostFW should disregard pod-originating traffic, even if the traffic is encapsulated. We have that opportunity now. But if we want to make that change, let's do it intentionally and not just slip it in.

**Review by brb — APPROVED** [review]
LGTM

**Pull request merged**
