### PR TITLE
v1.13 Backports 2024-02-16

### PR DESCRIPTION
**Pull request by sayboras**
* [x] #30151 (@pchaigno)
 * [x] #30759 (@pchaigno)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30151 30759
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.13

**Comment by sayboras** [comment]
/test-1.23-4.19

**Review by pchaigno — APPROVED** [review]
Thanks Tam!

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
/test-1.23-4.19

**Comment by aanm** [comment]
/test-1.23-4.19

**Comment by sayboras** [comment]
All the tests are passed now, not sure why the bot removed ready to merge label, manually add it back.

**Pull request merged**
