### PR TITLE
proxy: Use kvstore backed identity cache for label resolution

### PR DESCRIPTION
**Pull request by tgraf**

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
Are we getting rid of `policy.GetConsumableCache`?

**Review by manalibhutiyani — APPROVED** [review]
Looks good. Not sure if there is a plan to cleanup/ get rid of policy.GetConsumableCache, since we are querying the KVstore directly.

**Comment by tgraf** [comment]
> Looks good. Not sure if there is a plan to cleanup/ get rid of policy.GetConsumableCache, since we are querying the KVstore directly.

The only remaining user is a valid one, to lookup the opposite consumer to allow bidirectional policy if conntrack is disabled

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
