### PR TITLE
Extend BPF policymap to include proxy_port

### PR DESCRIPTION
**Pull request by joestringer**
This PR removes the `action` field from the `policy_entry` values that are held in `POLICY_MAP`, as it was not being used (the map is a whitelist and there are no other actions to take other than allow). In its place, it introduces `proxy_port`. This lays the groundwork for userspace to populate this map instead of writing the `BPF_L4_MAP` embedded macro to specify proxy ports to redirect traffic towards.

As part of this, the datapath logic is shifted around a bit to push the L4 policy lookup earlier, to occur alongside the Label-based, and Label-dependent L4, and CIDR policy lookups.

The existing `BPF_L4_MAP` method for fetching the `proxy_port` will still work for now, so this PR can be merged prior to the userspace work. Once userspace switches over to implementing L4-L7 policy via the `POLICY_MAP`, all of the `BPF_L4_MAP` logic can be removed.

Note that this requires the `cilium_policy_*` maps to be flushed upon cilium upgrade, otherwise all existing policies in the BPF map will cause forwarding to the local port 1 (interpreting the previous `action=1` as a `proxy_port` to redirect to), and the kernel will reset those connections. 

This PR also rolls in a few unrelated style / documentation fixes for the datapath.

**If you feel that the `action` field should still exist in this entry, or that this kind of upgrade breakage is unacceptable, please voice your opinions below.**

```release-note
Removed action field from BPF policy map entries
```

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
Awesome cleanup. Does the addition of the L4 policy lookup to the can_access() logic fix a bug or is required for the transition?

**Comment by joestringer** [comment]
@tgraf At this point it's only what's required for the transition.

I realised though that one minor tweak on top may fix #2907: With the current state, l4policy via the embedded maps is only triggered if there's an l4-only entry in the l3/l4 policy map. However, today userspace won't generate such entries. I was thinking that some reworking of the userspace would be necessary to fix the above bug, but we could just unconditionally attempt to use the embedded map if all the other cases fall through. I'll look into that, since it's one of the same core problems blocking #2954.

**Comment by joestringer** [comment]
Confirmed that userspace changes are necessary to fix #2907 without otherwise breaking Label-dependent L4, so I think that we should go ahead with this PR as-is.

**Pull request merged**
