### PR TITLE
datapath/iptables: de-duplicate program argument construction

### PR DESCRIPTION
**Pull request by tklauser**
Merge common code for constructing iptables arguments.

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by qmonnet — COMMENTED** [review]
Nice!
Can't we factorise the `"!", "-d", datapath.RemoteSNATDstAddrExclusionCIDR().String(),` as well? It looks identical in both cases. Unless it _has_ to be after the `-o`, but I don't think this is the case?

**Comment by tklauser** [comment]
> Nice!
> Can't we factorise the `"!", "-d", datapath.RemoteSNATDstAddrExclusionCIDR().String(),` as well? It looks identical in both cases. Unless it _has_ to be after the `-o`, but I don't think this is the case?

Good point. I naïvely assumed that the order of the arguments is important. But it seems for these it's not, so we can factor it out.

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
retest-gke

**Comment by tklauser** [comment]
retest-4.9

**Comment by tklauser** [comment]
retest-4.19

**Comment by tklauser** [comment]
retest-net-next

**Review by qmonnet — APPROVED** [review]

**Review by fristonio — APPROVED** [review]
LGTM :tada:

**Pull request merged**
