### PR TITLE
k8s: CEP GC controller logs errors at debug level

### PR DESCRIPTION
**Pull request by raybejjani**
These errors confused people and have no bearing on cilium's operation.
The error itself will still be surfaced in the controller section of
cilium status.

Fixes https://github.com/cilium/cilium/issues/3724

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by ianvernon** [comment]
This is super nitpick-y, but can you change the phrasing to not say 'silence'? This implies we are removing the logs, no? Would be more accurate to say 'change log level from info to debug for CEP GC errors'.

**Review by ianvernon — CHANGES_REQUESTED** [review]
This is super nitpick-y, but can you change the phrasing to not say 'silence'? This implies we are removing the logs, no? Would be more accurate to say 'change log level from info to debug for CEP GC errors'.

**Comment by raybejjani** [comment]
Sure. It would be far more accurate but it won't fit in git's 50 char shortlog limit so I had to be creative. I'll change it to something like what you have

**Comment by raybejjani** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by raybejjani** [comment]
test-me-please

**Pull request merged**
