### PR TITLE
custom calls: cleanup and improve a few elements

### PR DESCRIPTION
**Pull request by qmonnet**
This PR contains a few fixes and clean-up items related to the tail calls for custom programs. Please refer to the individual commits for details.

(Some of those commits were initially included in #15475, which will be updated to focus only on the new metrics.)

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Comment by qmonnet** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
test-me-please

**Comment by qmonnet** [comment]
Naming the object file after the `.h` file completely breaks test/bpf/verifier-test.sh, where the logics relies on the conversion `.c` -> `.o` reusing the same base name :/.

I will exclude the byte-counter from verifier-test.sh. It's not as if I expected a complexity issue to show up in that program any time soon, and I plan to package it externally anyway.

**Comment by qmonnet** [comment]
test-me-please

**Comment by qmonnet** [comment]
test-1.19-4.19

**Comment by qmonnet** [comment]
test-1.20-4.9

**Comment by qmonnet** [comment]
https://github.com/cilium/cilium/issues/15456 and https://github.com/cilium/cilium/issues/14959 again.

**Pull request merged**
