### PR TITLE
CEC: Move resource parser and envoy l7lb backend syncer to /pkg/ciliumenvoyconfig

### PR DESCRIPTION
**Pull request by mhofstetter**
Follow up of extracting the CiliumEnvoyConfigWatcher into its own package `pkg/ciliumenvoyconfig`. (https://github.com/cilium/cilium/pull/30298)

This PR moves parts of the package `pkg/envoy` into the newly introduced package `pkg/ciliumenvoyconfig`. The goal is to have all `CiliumEnvoyConfig` related logic in one package.

* Split and move CEC resource parsing logic
* Move CEC l7lb backend syncer
* Refactor CEC resource parser to retrieve the Ingress IPs of  the local node from the `LocalNodeStore` instead of the global functions. This is a requirement to make the resource parser selfcontained and the unit-tests working.

Please review the individual commits.

### CODE REVIEW

**Review by jrajahalme — APPROVED** [review]
Great work, one suggestion though: Maybe place the package under `pkg/envoy` instead, i.e, `pkg/envoy/ciliumenvoyconfig`?

**Comment by mhofstetter** [comment]
> Great work, one suggestion though: Maybe place the package under `pkg/envoy` instead, i.e, `pkg/envoy/ciliumenvoyconfig`?

Thanks Jarno!

I thought about this when introducing the new package in the initial PR (https://github.com/cilium/cilium/pull/30298). 

At first i even had it in `pkg/envoy` in the same Hive Cell. But that resulted in cyclic dependencies between  the packages `pkg/envoy` and `pkg/proxy`.

That's why i came to the conclusion that it would be best to move it into its own top-level package - as it's actually more L7LB than Envoy related (even though implemented with Envoy). To separate it from the envoy "foundation" and make it's dependencies to envoy and proxy (port allocation) explicit. IMO this wouldn't be as explicit if we would place it in a subpackage (even though with separate hive cell) below `pkg/envoy` (e.g. `pkg/envoy/ciliumenvoyconfig`).

WDYT? even if we come to the conclusion that we want to have move this package again  - i would recommend to make this in it's own PR afterwards (moving the rest of the files and change the CODEOWNERS file)

**Pull request merged**
