### PR TITLE
images/runtime: bump FORCE_BUILD to force regeneration

### PR DESCRIPTION
**Pull request by aanm**
This will force a regeneration of the image build which will fix some vulnerabilities in the last Cilium image.

### CODE REVIEW

**Comment by aanm** [comment]
/test-backport-1.13

**Comment by aanm** [comment]
/test-backport-1.13

**Comment by aanm** [comment]
/test-1.17-4.9

**Comment by aanm** [comment]
/test-1.26-net-next

**Comment by aanm** [comment]
/test-1.17-4.9

**Review by gandro — APPROVED** [review]

**Pull request merged**
