### PR TITLE
v1.4 backports 19-01-17

### PR DESCRIPTION
**Pull request by ianvernon**
* PR: 6673 -- cilium, ipvlan: fix tail call map fd leakage (@borkmann) -- https://github.com/cilium/cilium/pull/6673
 * PR: 6671 -- Fix route lookup and add workaround for kernel race condition (@tgraf) -- https://github.com/cilium/cilium/pull/6671
 * PR: 6668 -- Documentation: add "behaviour" to spelling wordlist (@ianvernon) -- https://github.com/cilium/cilium/pull/6668
 * PR: 6663 -- maps/tunnel: Retire code for removal of tunnel_endpoint_map (@mrostecki) -- https://github.com/cilium/cilium/pull/6663
 * PR: 6662 -- cilium, ipvlan: add iptables rules switch and set up ipvlan mode accordingly (@borkmann) -- https://github.com/cilium/cilium/pull/6662
 * PR: 6656 -- daemon: Do not mention ipvlan in --device flag usage (@brb) -- https://github.com/cilium/cilium/pull/6656
 * PR: 6655 -- Kubernetes: Deprecate ConfigMap option "legacy-host-allows-world" (@joestringer) -- https://github.com/cilium/cilium/pull/6655
 * PR: 6652 -- daemon: Add /tofqdns/{id} API (@raybejjani) -- https://github.com/cilium/cilium/pull/6652
 * PR: 6650 -- daemon: Use DeepCopy method from StatusResponse (@mrostecki) -- https://github.com/cilium/cilium/pull/6650
 * PR: 6644 -- pkg/option: clean up some environment variables (@aanm) -- https://github.com/cilium/cilium/pull/6644
 * PR: 6634 -- kubernetes: Use 2.0.4 version of cilium-etcd-operator (@tgraf) -- https://github.com/cilium/cilium/pull/6634
 * PR: 6467 -- re-enable Istio test, other misc. code fixes around endpoint (@ianvernon) -- https://github.com/cilium/cilium/pull/6467

I had issues backporting the following PRs:

 * PR: 6601 -- Add troubleshooting section (@briantopping) -- https://github.com/cilium/cilium/pull/6601

```
$ cherry_pick d1c7db04ab74b74bef583abdfa5cc7db84078f74
----- profile: cherry_pick: changing to /home/vagrant/go/src/github.com/cilium/cilium/
----- profile: cherry_pick: cherry-picking commit: d1c7db04ab74b74bef583abdfa5cc7db84078f74
Applying: Add troubleshooting section
error: corrupt binary patch at line 30: 
error: unrecognized input
error: could not build fake ancestor
Patch failed at 0001 Add troubleshooting section
Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

This is documentation only so I will look into it later; wanted to test the code-related stuff in this PR.

 * PR: 6650 -- daemon: Use DeepCopy method from StatusResponse (@mrostecki) -- https://github.com/cilium/cilium/pull/6650

```
$ cherry_pick ba50a3e4f9a2105371184a6010a27fe7ef103007
----- profile: cherry_pick: changing to /home/vagrant/go/src/github.com/cilium/cilium/
----- profile: cherry_pick: cherry-picking commit: ba50a3e4f9a2105371184a6010a27fe7ef103007
Applying: dep: vendor: Update go-openapi/strfmt and remove mohae/deepcopy
error: corrupt patch at line 2837
error: could not build fake ancestor
Patch failed at 0001 dep: vendor: Update go-openapi/strfmt and remove mohae/deepcopy
Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort"
```

This included dependency updates, so I updated via `dep` manually and did a special commit in the branch that did not cherry-pick the commit 

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6679)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
Build failure in K8s tests: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1534/flowGraphTable/

Need to triage.

EDIT: looks like connectivity to etcd had issues:

```
2019-01-17T16:58:26.08197303Z level=fatal msg="Unable to connect to kvstore" error="timed out while waiting for etcd session. Ensure that etcd is running on [https://cilium-etcd-client.kube-system.svc:2379]" subsys=kvstore
2019-01-17T16:58:16.112135106Z level=fatal msg="Unable to connect to kvstore" error="timed out while waiting for etcd session. Ensure that etcd is running on [https://cilium-etcd-client.kube-system.svc:2379]" subsys=kvstore
2019-01-17T16:58:26.08197303Z level=fatal msg="Unable to connect to kvstore" error="timed out while waiting for etcd session. Ensure that etcd is running on [https://cilium-etcd-client.kube-system.svc:2379]" subsys=kvstore
2019-01-17T16:58:16.112135106Z level=fatal msg="Unable to connect to kvstore" error="timed out while waiting for etcd session. Ensure that etcd is running on [https://cilium-etcd-client.kube-system.svc:2379]" subsys=kvstore
```

Logs don't have much in terms of debugging (including state of all pods in the cluster, etc.).

**Comment by ianvernon** [comment]
Ginkgo tests passed: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9121/

Pushed a documentation-only commit which updates the spelling wordlist so the documentation build passes.

Running K8s tests again since those didn't pass before.

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Another failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1535/

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9127/testReport/junit/k8s-1/8/K8sChaosTest_Restart_with_long_lived_connections_L3_L4_policies_still_work_while_Cilium_is_restarted/

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
