### PR TITLE
[v1.10] IPSec key rotation without agent restart

### PR DESCRIPTION
**Pull request by jibi**
* #19814 -- IPSec key rotation without agent restart (@jibi )
 * #19932 -- ipsec: fix stale keys reclaim logic (@jibi)
 * #20392 -- nodediscovery: make LocalNode return a deep copy of localNode (@jibi)

Moreover, as a dependency of the 2 PRs some additional changes/commits have been backported from:
* https://github.com/cilium/cilium/pull/15933:
  * `node: add GetAbsoluteNodeName method`
* https://github.com/cilium/cilium/pull/18887:
  * https://github.com/cilium/cilium/commit/ed934cb958c52515be37998038301229959a0fd2
  * https://github.com/cilium/cilium/commit/9c1cb4856322a80174799dae142ef761e51e2310
  * https://github.com/cilium/cilium/commit/e52fe1d59d1c6f51a76993641ea9412e0f44f749

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 19814 19932 20392 ; do contrib/backporting/set-labels.py $pr done 1.10; done
```
or with
```
$ make add-label BRANCH=v1.10 ISSUES=19814,19932,20392
```

### CODE REVIEW

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by jibi** [comment]
/test-1.21-4.9

**Review by gandro — APPROVED** [review]
Awesome work. Same feedback from me as I gave on the v1.11 branch https://github.com/cilium/cilium/pull/20157#pullrequestreview-1028265750

**Comment by jibi** [comment]
/test-backport-1.10

**Comment by julianwiedmann** [comment]
> Awesome work. Same feedback from me as I gave on the v1.11 branch [#20157 (review)](https://github.com/cilium/cilium/pull/20157#pullrequestreview-1028265750)

Ditto, ipsec looks all good. Thanks for doing these so quickly @jibi !

**Review by julianwiedmann — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]

**Review by NikAleksandrov — APPROVED** [review]

**Pull request merged**
