### PR TITLE
Fix matchPattern: "*" implementation, and actually test it

### PR DESCRIPTION
**Pull request by raybejjani**
Basically, actually test this, and also make it work ☺️ 

Fixes https://github.com/cilium/cilium/pull/6411

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6416)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by raybejjani** [comment]
weird... I ran the unit tests on my end... I'll sort it out

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
my local runtime test finished. I need to fix it, I'll be back

**Comment by raybejjani** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Pull request merged**
