### PR TITLE
Fix race condition in DeepEqual function

### LINKED ISSUE #13436: [RACE Detector]: pkg/k8s/apis/cilium.io/v2.sharedCNPDeepEqual()
```
2020-10-05T00:18:23.305537509Z WARNING: DATA RACE
2020-10-05T00:18:23.305540975Z Write at 0x00c00156c780 by goroutine 89:
2020-10-05T00:18:23.305544277Z   runtime.mapdelete_faststr()
2020-10-05T00:18:23.305548061Z       /usr/local/go/src/runtime/map_faststr.go:297 +0x0
2020-10-05T00:18:23.30555163Z   github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.sharedCNPDeepEqual()
2020-10-05T00:18:23.305555413Z       /go/src/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/cnp_types.go:94 +0x371
2020-10-05T00:18:23.305558986Z   github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*CiliumNetworkPolicy).DeepEqual()
2020-10-05T00:18:23.30556251Z       /go/src/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/cnp_types.go:65 +0x44
2020-10-05T00:18:23.305565883Z   github.com/cilium/cilium/pkg/k8s/types.(*SlimCNP).DeepEqual()
2020-10-05T00:18:23.305569167Z       /go/src/github.com/cilium/cilium/pkg/k8s/types/zz_generated.deepequal.go:82 +0xf4
2020-10-05T00:18:23.305572526Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumNetworkPoliciesInit.func2()
2020-10-05T00:18:23.305576168Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_network_policy.go:141 +0x171
2020-10-05T00:18:23.305579758Z   k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate()
2020-10-05T00:18:23.305583698Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:234 +0xa5
2020-10-05T00:18:23.305587368Z   k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnUpdate()
2020-10-05T00:18:23.305590846Z       <autogenerated>:1 +0x2e
2020-10-05T00:18:23.305594966Z   github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1()
2020-10-05T00:18:23.305598714Z       /go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:114 +0x389
2020-10-05T00:18:23.305602327Z   k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop()
2020-10-05T00:18:23.305609999Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:501 +0x3ab
2020-10-05T00:18:23.305613943Z   k8s.io/client-go/tools/cache.(*controller).processLoop()
2020-10-05T00:18:23.305618005Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:179 +0x83
2020-10-05T00:18:23.305621411Z   k8s.io/client-go/tools/cache.(*controller).processLoop-fm()
2020-10-05T00:18:23.305625731Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:177 +0x44
2020-10-05T00:18:23.305629016Z   k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
2020-10-05T00:18:23.305632056Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x75
2020-10-05T00:18:23.305635247Z   k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
2020-10-05T00:18:23.305638283Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xba
2020-10-05T00:18:23.30564135Z   k8s.io/apimachinery/pkg/util/wait.JitterUntil()
2020-10-05T00:18:23.305644434Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x114
2020-10-05T00:18:23.305647499Z   k8s.io/apimachinery/pkg/util/wait.Until()
2020-10-05T00:18:23.305650422Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4a7
2020-10-05T00:18:23.305653435Z   k8s.io/client-go/tools/cache.(*controller).Run()
2020-10-05T00:18:23.305656423Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x449
2020-10-05T00:18:23.305659521Z 
2020-10-05T00:18:23.30566242Z Previous read at 0x00c00156c780 by goroutine 333:
2020-10-05T00:18:23.305665396Z   k8s.io/apimachinery/pkg/apis/meta/v1.(*ObjectMeta).DeepCopyInto()
2020-10-05T00:18:23.305668448Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/zz_generated.deepcopy.go:685 +0xb39
2020-10-05T00:18:23.305671576Z   github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*CiliumNetworkPolicy).DeepCopyInto()
2020-10-05T00:18:23.3056879Z       /go/src/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:382 +0x18b
2020-10-05T00:18:23.305690995Z   github.com/cilium/cilium/pkg/k8s/types.(*SlimCNP).DeepCopyInto()
2020-10-05T00:18:23.305693998Z       /go/src/github.com/cilium/cilium/pkg/k8s/types/zz_generated.deepcopy.go:85 +0x124
2020-10-05T00:18:23.305697017Z   github.com/cilium/cilium/pkg/k8s/types.(*SlimCNP).DeepCopy()
2020-10-05T00:18:23.305700003Z       /go/src/github.com/cilium/cilium/pkg/k8s/types/zz_generated.deepcopy.go:96 +0xd84
2020-10-05T00:18:23.305703049Z   github.com/cilium/cilium/pkg/k8s.(*CNPStatusUpdateContext).prepareUpdate()
2020-10-05T00:18:23.305706095Z       /go/src/github.com/cilium/cilium/pkg/k8s/cnp.go:130 +0x74b
2020-10-05T00:18:23.305709572Z   github.com/cilium/cilium/pkg/k8s.(*CNPStatusUpdateContext).UpdateStatus()
2020-10-05T00:18:23.305713237Z       /go/src/github.com/cilium/cilium/pkg/k8s/cnp.go:240 +0x578
2020-10-05T00:18:23.305721127Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).addCiliumNetworkPolicyV2.func1()
2020-10-05T00:18:23.305724842Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_network_policy.go:228 +0x7d
2020-10-05T00:18:23.305729819Z   github.com/cilium/cilium/pkg/controller.(*Controller).runController()
2020-10-05T00:18:23.305734163Z       /go/src/github.com/cilium/cilium/pkg/controller/controller.go:205 +0xcb0
2020-10-05T00:18:23.305737695Z 
2020-10-05T00:18:23.305761394Z Goroutine 89 (running) created at:
2020-10-05T00:18:23.305765726Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumNetworkPoliciesInit()
2020-10-05T00:18:23.305769283Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_network_policy.go:177 +0x76e
2020-10-05T00:18:23.305772833Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).EnableK8sWatcher()
2020-10-05T00:18:23.305776139Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:480 +0x3c4
2020-10-05T00:18:23.305779788Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).InitK8sSubsystem()
2020-10-05T00:18:23.305783131Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:376 +0x94
2020-10-05T00:18:23.305786527Z   github.com/cilium/cilium/daemon/cmd.NewDaemon()
2020-10-05T00:18:23.305789751Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:563 +0x28e6
2020-10-05T00:18:23.305793056Z   github.com/cilium/cilium/daemon/cmd.runDaemon()
2020-10-05T00:18:23.305796368Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1335 +0x664
2020-10-05T00:18:23.30579978Z   github.com/cilium/cilium/daemon/cmd.glob..func1()
2020-10-05T00:18:23.305803684Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:124 +0x18f
2020-10-05T00:18:23.305806578Z   github.com/cilium/cilium/daemon/cmd.glob..func1()
2020-10-05T00:18:23.305809592Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:122 +0x175
2020-10-05T00:18:23.305812789Z   github.com/spf13/cobra.(*Command).execute()
2020-10-05T00:18:23.305816057Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:846 +0x906
2020-10-05T00:18:23.305819434Z   github.com/spf13/cobra.(*Command).ExecuteC()
2020-10-05T00:18:23.305823045Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:950 +0x4b2
2020-10-05T00:18:23.305826867Z   github.com/spf13/cobra.(*Command).Execute()
2020-10-05T00:18:23.305829966Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:887 +0x88
2020-10-05T00:18:23.305833535Z   github.com/cilium/cilium/daemon/cmd.Execute()
2020-10-05T00:18:23.305837158Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:149 +0x69
2020-10-05T00:18:23.305840681Z   main.main()
2020-10-05T00:18:23.305843876Z       /go/src/github.com/cilium/cilium/daemon/main.go:22 +0x2f
2020-10-05T00:18:23.305851905Z   runtime.main()
2020-10-05T00:18:23.30585562Z       /usr/local/go/src/runtime/proc.go:204 +0x208
2020-10-05T00:18:23.305858944Z   github.com/cilium/ebpf.init()
2020-10-05T00:18:23.305862371Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/prog.go:362 +0x3f8
2020-10-05T00:18:23.305865966Z   github.com/cilium/ebpf.init()
2020-10-05T00:18:23.305869139Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/syscalls.go:392 +0x38b
2020-10-05T00:18:23.305872633Z   github.com/cilium/ebpf.init()
2020-10-05T00:18:23.305875545Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/syscalls.go:216 +0x31d
2020-10-05T00:18:23.305878553Z   github.com/cilium/ebpf.init()
2020-10-05T00:18:23.305883785Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/syscalls.go:188 +0x2b0
2020-10-05T00:18:23.305886836Z   runtime.doInit()
2020-10-05T00:18:23.30588972Z       /usr/local/go/src/runtime/proc.go:5625 +0x89
2020-10-05T00:18:23.305892563Z   github.com/cilium/ebpf/internal/btf.init()
2020-10-05T00:18:23.305895462Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/internal/btf/btf.go:656 +0x18f
2020-10-05T00:18:23.305898476Z 
2020-10-05T00:18:23.305901272Z Goroutine 333 (running) created at:
2020-10-05T00:18:23.305904143Z   github.com/cilium/cilium/pkg/controller.(*Manager).updateController()
2020-10-05T00:18:23.305907121Z       /go/src/github.com/cilium/cilium/pkg/controller/manager.go:120 +0x1029
2020-10-05T00:18:23.305910093Z   github.com/cilium/cilium/pkg/controller.(*Manager).UpdateController()
2020-10-05T00:18:23.305913032Z       /go/src/github.com/cilium/cilium/pkg/controller/manager.go:59 +0xbe4
2020-10-05T00:18:23.305915974Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).addCiliumNetworkPolicyV2()
2020-10-05T00:18:23.305918996Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_network_policy.go:225 +0x9f0
2020-10-05T00:18:23.305921999Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumNetworkPoliciesInit.func1()
2020-10-05T00:18:23.305924958Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_network_policy.go:131 +0x1c6
2020-10-05T00:18:23.305927928Z   k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd()
2020-10-05T00:18:23.305930857Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:227 +0x8f
2020-10-05T00:18:23.305934111Z   k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd()
2020-10-05T00:18:23.305937704Z       <autogenerated>:1 +0x2a
2020-10-05T00:18:23.30594131Z   github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1()
2020-10-05T00:18:23.305944879Z       /go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:119 +0x2a9
2020-10-05T00:18:23.305948162Z   k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop()
2020-10-05T00:18:23.305962642Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:501 +0x3ab
2020-10-05T00:18:23.305966765Z   k8s.io/client-go/tools/cache.(*controller).processLoop()
2020-10-05T00:18:23.305969924Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:179 +0x83
2020-10-05T00:18:23.305972982Z   k8s.io/client-go/tools/cache.(*controller).processLoop-fm()
2020-10-05T00:18:23.305975923Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:177 +0x44
2020-10-05T00:18:23.305979377Z   k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
2020-10-05T00:18:23.305982265Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x75
2020-10-05T00:18:23.305985299Z   k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
2020-10-05T00:18:23.305988236Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xba
2020-10-05T00:18:23.305991198Z   k8s.io/apimachinery/pkg/util/wait.JitterUntil()
2020-10-05T00:18:23.30599434Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x114
2020-10-05T00:18:23.305997386Z   k8s.io/apimachinery/pkg/util/wait.Until()
2020-10-05T00:18:23.30600024Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4a7
2020-10-05T00:18:23.306003211Z   k8s.io/client-go/tools/cache.(*controller).Run()
2020-10-05T00:18:23.306006086Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x449
```
https://jenkins.cilium.io/view/Race%20Detection/job/Ginkgo-CI-Tests-k8s1.12-Pipeline-Race-Detection/8/testReport/junit/Suite-k8s-1/12/K8sServicesTest_Checks_service_across_nodes_with_L4_policy_Tests_NodePort_with_L4_Policy/

### PR DESCRIPTION
**Pull request by aanm**
Fix https://github.com/cilium/cilium/issues/13436

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
retest-4.9

**Review by christarazi — APPROVED** [review]

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/13430

**Comment by qmonnet** [comment]
As far as I can tell, the function fixed in second commit is introduced with commit 061c66bb3c9a (`add golang markers for deep equal generator`), which does not seem present in v1.7, so I don't believe the backport applies to v1.7?

**Pull request merged**
