### PR TITLE
Update Go to 1.15.4

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
:tada:

**Comment by tklauser** [comment]
test-me-please

**Review by rolinh — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Review by errordeveloper — APPROVED** [review]

**Comment by tklauser** [comment]
Backport PR: #13946

**Pull request merged**
