### PR TITLE
v1.9 backports 2021-03-10

### PR DESCRIPTION
**Pull request by pchaigno**
* #15175 -- nat: Create SNAT maps only if BPF NodePort is enabled (@pchaigno)
 * #15179 -- Docs: adds a getting started guide for Rancher 2.x (@seanmwinn)

Skipped:

 * #15182 -- azure: Add the correct JSON tag to GatewayIP field in CiliumNode CRD (@AnishShah)
     - Small conflict, skipped.
 * #15228 -- endpoint: Fix the initialization of endpoints' datapath configs (@pchaigno)
     - Not trivial and not a release blocker, so let's avoid including in release at the last minute.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 15175 15179; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by pchaigno** [comment]
test-backport-1.9

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
CI is green except for Travis, which failed to trigger. I'll close&reopen to see if that triggers the run.

**Comment by pchaigno** [comment]
I also validated that the unit tests pass locally (for amd64 at least).

**Comment by pchaigno** [comment]
CI was previously green except for Travis CI. Travis CI is now green. I think this is ready to merge.

**Comment by joestringer** [comment]
@pchaigno the command in the PR description updates the statuses of the wrong PRs ;) I manually fixed up the labels to reflect reality.

**Comment by pchaigno** [comment]
> @pchaigno the command in the PR description updates the statuses of the wrong PRs ;) I manually fixed up the labels to reflect reality.

Whoops! All looks good now, thanks!

**Pull request merged**
