### PR TITLE
vagrant: Bump all Vagrant box versions

### PR DESCRIPTION
**Pull request by pchaigno**
Updates: #11255

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Review by rolinh — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by pchaigno** [comment]
retest-runtime

**Comment by pchaigno** [comment]
There appear to be some issue with the Runtime VM:
```
runtime: Jul 23 21:17:46 runtime cilium-agent[12588]: level=fatal msg="could not run bpftool" error="signal: segmentation fault (core dumped)" subsys=probes
```
May be related to cilium/packer-ci-build#226. Switching back to draft.

**Comment by qmonnet** [comment]
Daniel just merged the patches to bpf-next as `9a97c9d2af5c ("tools, bpftool: Add LSM type to array of prog names")` and `70cfab1d871c ("tools, bpftool: Skip type probe if name is not found")`.

**Comment by qmonnet** [comment]
Blocked by https://github.com/cilium/packer-ci-build/issues/230.

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
retest-net-next

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
retest-gke

**Review by aanm — APPROVED** [review]
Does it have go 1.15?

**Comment by pchaigno** [comment]
@aanm I don't think so: https://github.com/cilium/packer-ci-build/blob/master/provision/env.bash

**Comment by aanm** [comment]
> @aanm I don't think so: https://github.com/cilium/packer-ci-build/blob/master/provision/env.bash

Perhaps would it make sense to wait until go is updated in the dev boxes?

**Comment by pchaigno** [comment]
> > @aanm I don't think so: https://github.com/cilium/packer-ci-build/blob/master/provision/env.bash
> 
> Perhaps would it make sense to wait until go is updated in the dev boxes?

Why? We're waiting on this update to partially fix https://github.com/cilium/cilium/issues/11255 and it doesn't cost much to do another update once Go has been updated in packer-ci-build. Plus, the required tests are green!

**Review by tklauser — APPROVED** [review]

**Pull request merged**
