### PR TITLE
envoy: Bump envoy to 1.23.4

### PR DESCRIPTION
**Pull request by sayboras**
### Description

This is as part of BAU activitity to upgrade envoy version, so that we don't rush into any potential EOL. Not to mention that some of useful envoy features (e.g. internal listener) are only available in later versions.

### Testing

Testing was done locally for Gateway API and L7 policies via connectivity test.

### CODE REVIEW

**Comment by sayboras** [comment]
/test-1.16-4.9

**Comment by sayboras** [comment]
/test-1.16-4.19

**Comment by sayboras** [comment]
test-runtime hits https://github.com/cilium/cilium/issues/22373

**Review by rolinh — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]

**Comment by sayboras** [comment]
Reviews from required teams are in, all CI jobs are successfully run. ci-verifier is not required due to the changes here.

Mark this ready to merge.

**Pull request merged**
