### PR TITLE
WIP: separate endpoint code files

### PR DESCRIPTION
**Pull request by ianvernon**
Separate endpoint package into more modular, logically-separated files. I did this because it helps me understand what parts of the endpoint structure are being modified where, which makes it easier to figure out what's going on instead of just having the code in one big `endpoint.go` file.

There should be no logical change to the code here.

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by joestringer** [comment]
Most of this seems OK to me, though the BPF changes suggest that the BPF package isn't picking up enough of the map-related concerns.

**Comment by ianvernon** [comment]
@joestringer I think that the fact that this raises that concern is precisely what this change is meant to do. It will make much more clear what code can be factored out into appropriate packages.

**Comment by ianvernon** [comment]
I'm going to close this in favor of having commits that port functions over one at a time. This will make rebasing a lot easier, as it will just involve copying whatever changes were made in master in the single function to the file that they are moved to. I'll work on this on my own time.

**Pull request closed without merging**
