### PR TITLE
[1.12] Address selectorcache concurrent read/write

### PR DESCRIPTION
**Pull request by bimmlerd**
See commit message.

### CODE REVIEW

**Comment by bimmlerd** [comment]
/test-backport-1.12

**Comment by tklauser** [comment]
/test-1.17-4.9

failed with an unrelated temporary flake:

> 16:56:17  FAIL: failed to ensure kubectl version: failed to download kubectl

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-4.9/274/

**Comment by tklauser** [comment]
CI passed and we've assessed the potential for deadlocks through manual code inspection.

Marking as ready to review.

**Comment by odinuge** [comment]
Hi,

Is it correct that this was introduced by https://github.com/cilium/cilium/commit/d68efba3de11b9526e5191e47dccf1e0d1967623? If so this means this is part of both `v1.12.{15,16}`? We have at least started seeing this cause cilium-agents crashing due to this after upgrading to v1.12.15.

**Comment by tklauser** [comment]
> Is it correct that this was introduced by [d68efba](https://github.com/cilium/cilium/commit/d68efba3de11b9526e5191e47dccf1e0d1967623)? If so this means this is part of both `v1.12.{15,16}`? We have at least started seeing this cause cilium-agents crashing due to this after upgrading to v1.12.15.

Yes, I think that's correct.

**Review by julianwiedmann — APPROVED** [review]

**Comment by bimmlerd** [comment]
/test-backport-1.12

**Review by tklauser — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Comment by gandro** [comment]
@tklauser @bimmlerd Is this still waiting for review?

**Comment by tklauser** [comment]
> @tklauser @bimmlerd Is this still waiting for review?

@odinuge started seeing the issue too (see https://github.com/cilium/cilium/pull/29167#issuecomment-1812399849) and communicated out-of-band that they're testing the patch in their environment. We wanted to wait on whether this PR fixes the issue for them. @odinuge do you already have any news about this?

**Comment by odinuge** [comment]
> We wanted to wait on whether this PR fixes the issue for them. @odinuge do you already have any news about this?

Yes, we have not been able to reproduce the issue with this patch, thanks!

We tested it for a while on a cluster that had a lot of issues without this on v1.12.15; and when applying this patch on top of that build, things worked as expected! We will let this soak for quite a while before hitting larger clusters, but so far it looks very promising.

**Comment by tklauser** [comment]
Thanks a lot @odinuge! Given your feedback I think this PR can be merged.

**Pull request merged**
