### PR TITLE
daemon: split out parts of `NewDaemon` into separate functions

### PR DESCRIPTION
**Pull request by ianvernon**
This makes the code more readable, as the function is quite long. Separating bootstrap into distinct functions will help ordering of initializing certain subsystems easier.

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8107)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Ready for review - only CI failure is the ClusterIP Service connectivity on same node, which is a known flake.

**Comment by nebril** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Pull request merged**
