### PR TITLE
docs: Add deprecation warning for socks-enable.

### PR DESCRIPTION
**Pull request by brb**

### CODE REVIEW

**Review by tklauser — COMMENTED** [review]
Shouldn't this change be made on `master` first and then backported to `v1.13` (e.g. as part of #23555), so that the latest docs version (https://docs.cilium.io/en/latest/) will also show the deprecation notice?

**Review by pchaigno — CHANGES_REQUESTED** [review]
I agree with Tobias here.

**Comment by brb** [comment]
> Shouldn't this change be made on master first and then backported to v1.13

I thought the same, but we recently changed the upgrade guide - https://docs.cilium.io/en/latest/operations/upgrade/ doesn't contain upgrade notes for  < v1.14 anymore.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
Next time we should probably wait for the release to be made before removing release notes.

**Pull request merged**
