### PR TITLE
Updating etcd to 3.2.1

### PR DESCRIPTION
**Pull request by aanm**

### CODE REVIEW

**Comment by tgraf** [comment]
Will we remain compatible with etcd 3.1.x?

**Comment by aanm** [comment]
>Will we remain compatible with etcd 3.1.x?

Let's wait until we have all runtime tests up and running just to be sure.

**Comment by aanm** [comment]
Waiting for #980 to be merged

**Comment by aanm** [comment]
@tgraf the k8s multi node uses etcd and all tests passed

**Review by tgraf — APPROVED** [review]

**Pull request merged**
