### PR TITLE
Add Kryptos Logic to list of users

### PR DESCRIPTION
**Pull request by j-mie**
This PR adds @kryptoslogic to the list of Cilium users

### CODE REVIEW

**Comment by xmulligan** [comment]
@jamie-34254 Thanks for adding! Can you sign off your commit so we can merge it? 

https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/amending-a-commit
or
https://www.secondstate.io/articles/dco/

**Comment by xmulligan** [comment]
@jamie-34254 just a friendly ping :) can you sign off your commit so we can merge it?

**Comment by xmulligan** [comment]
@jamie-34254 would you mind opening this as a new PR? If you do that, Github will automatically add sign off and you won't have to solve the conflicts

**Comment by xmulligan** [comment]
@borkmann is it ok if I resubmit this PR from my account with sign off since it doesn't seem like @jamie-34254 is coming back for this?

**Comment by pchaigno** [comment]
Closing in favor of https://github.com/cilium/cilium/pull/20284.

**Pull request closed without merging**
