### PR TITLE
agent: Remove unused GetTunnelMode()

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4647)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
CI flake:
* dns not ready
* Cannot connect to vmName  'k8s1-1.10'

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
:tada:

**Pull request merged**
