### PR TITLE
v1.12 backports 2023-11-02

### PR DESCRIPTION
**Pull request by derailed**
- [ ] #28649 -- labels: Use slices.Sort instead of sort.Strings (@pippolo84)
 - [ ] #28647 -- labels/cidr: On the fly char replacement for IPv6 (@pippolo84)
 - [ ] #28642 -- ipsec: Improve logging (@pchaigno)
 - [ ] #28808 -- gh/workflows: Dump Cilium LB node logs in case of failure (@brb)
 - [ ] #28884 -- bpf: lb: fix missing drop reason in reverse_map_l4_port() (@julianwiedmann)
 - [ ] #28382 -- Metrics associated with a deleted node should not be reported (@derailed)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 28649 28647 28642 28808 28884; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Review by pchaigno — CHANGES_REQUESTED** [review]
Something went wrong here. There's a single commit in this PR :scream:

**Comment by derailed** [comment]
Thank you for the heads up Paul! 
No idea where I went wrong??

**Comment by derailed** [comment]
@pchaigno I think I've got it in the right shape now?? 
The pb now is golint chokes since errors.Join on one of your bps ;( 
Not sure what the protocol is to upgrade go rev?

**Comment by pippolo84** [comment]
My PRs (#28647 and #28649) have already been backported [here](https://github.com/cilium/cilium/pull/28951), so you can drop them.

**Comment by derailed** [comment]
Looks like I've made a mistake on this backport. Closing

**Pull request closed without merging**
