### PR TITLE
v1.11 backports 2022-03-15

### PR DESCRIPTION
**Pull request by ti-mo**
* #18886 -- jenkinsfiles: bump runtime tests VM boot timeout (@nbusseneau)
 * #17851 -- Add support to connect Clustermesh clusters through Helm Chart (@samueltorres)
 * #18891 -- docs: update Azure Service Principal / IPAM documentation (@nbusseneau)
 * #18849 -- install/helm: Add Image Override Option to All Images (@nathanjsweet)
 * #18708 -- Add Amazon EC2 c7g instance configuration (@otterley)
 * #18877 -- hubble: Added nil check in filterByTCPFlags() to avoid segfault (@wazir-ahmed)
 * #18911 -- Fix IPsec in Azure's IPAM mode (@pchaigno)
 * #18952 -- pkg/maps: Fix data races around accessing nat maps (@aditighag)
 * #18975 -- cilium-cni: Call IPAMAllocate before creating veth (@michi-covalent)
 * #18897 -- helm: check for contents of bootstartFile (@aanm)
 * #19017 -- Fix 'node-init' in GKE's 'cos' images. (@bmcustodio)
 * #19036 -- docs: fix tip about opening the Hubble server port on all nodes (@rolinh)
 * #19053 -- helm: Remove Unnecessary RBAC Permissions for Agent (@nathanjsweet)
 * #19005 -- Policy fix mapstate owners (@jrajahalme)
 * #19031 -- selectorcache: Move identity alloc/release outside of critical section (@joestringer)
 * #19081 -- datapath/config: Fix L2 addr retrieval (@brb)
 * #19088 -- [Docs] Update docs to use enable endpoint route Azure cni (@nitishm)
 * #19100 -- Makefile: Fix TESTPKGS commandline (@joestringer)
 * #19076 -- clustermesh: fix: identities allocation range (@abocim)
 * #19108 -- bpf: Remove DNS quirk for monitor aggregation (@borkmann)
 * #18864 -- Prevent CiliumEndpoint removal by non-owning agent (@timoreimann)
 * #18783 -- accesslog: Pass destination identity from L7 proxies to access logs (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18886 17851 18891 18849 18708 18877 18911 18952 18975 18897 19017 19036 19053 19005 19031 19081 19088 19100 19076 19108 18864 18783; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Review by borkmann — APPROVED** [review]
lgtm for #19108

**Comment by ti-mo** [comment]
/test-backport-1.11

**Review by nbusseneau — APPROVED** [review]
My changes LGTM.

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks Timo!

**Review by brb — APPROVED** [review]
My changes LGTM, thanks.

**Review by michi-covalent — APPROVED** [review]
https://github.com/cilium/cilium/pull/19142/commits/1c89a98d9e10473124b1506e6bb152c75113e340 lgtm. thank you! 🚀

**Review by nathanjsweet — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
Backports for #19031 and #19100 LGTM, thanks!

**Comment by ti-mo** [comment]
/ci-gke-1.11

**Comment by ti-mo** [comment]
/test-backport-1.11

**Review by aditighag — APPROVED** [review]
Looks good for my changes. Thanks!

**Review by rolinh — APPROVED** [review]

**Comment by ldelossa** [comment]
@jrajahalme latest `test-runtime` has failed with:

```
14:50:10      runtime: Mar 17 18:50:08 runtime cilium-agent[24010]: level=info msg="Cilium 1.11.2 b94d77d0d1 2022-03-17T10:08:24-07:00 go version go1.17.2 linux/amd64" subsys=daemon
14:50:10      runtime: Mar 17 18:50:08 runtime cilium-agent[24010]: level=fatal msg="Envoy: Binary \"cilium-envoy\" cannot be executed" error="exit status 1" subsys=envoy-manager
14:50:10      runtime: Cilium failed to start
``` 

Seems legitamate.

**Comment by ldelossa** [comment]
/ci-aks-1.11

**Comment by ldelossa** [comment]
/test-ci-aks-1.11

**Pull request merged**
