### PR TITLE
test: node: use Eventually() to check CiliumNode labels

### PR DESCRIPTION
**Pull request by jibi**
Manual backport of https://github.com/cilium/cilium/pull/21353/ (these 2 PRs were targetting 1.12 and 1.11 as this test does not exist anymore in master)

### CODE REVIEW

**Comment by jibi** [comment]
/test-backport-1.11

**Comment by jibi** [comment]
/test-backport-1.11

**Comment by jibi** [comment]
/test-backport-1.11

**Comment by jibi** [comment]
/test-1.23-4.9

**Comment by jibi** [comment]
/test-1.23-4.9

**Comment by jibi** [comment]
/test-1.23-4.9

**Comment by jibi** [comment]
/test-1.23-4.9

**Comment by jibi** [comment]
/test-backport-1.11

**Review by ti-mo — APPROVED** [review]
Not sure if build-commits is supposed to fail. It's not marked as required, though.

**Comment by jibi** [comment]
Marking it as ready to merge as the failure is unrelated to the changes of this PR

**Pull request merged**
