### PR TITLE
pkg/labels: Optimize SortedList() and FormatForKVStore()

### PR DESCRIPTION
**Pull request by christarazi**
- pkg/labels: Add benchmark for hot labels code
- pkg/labels: Optimize SortedList() and FormatForKVStore()

Related: https://github.com/cilium/cilium/issues/19571

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]
how does the benchmark output look like?

**Review by ldelossa — APPROVED** [review]
code checks out :speedboat:

**Comment by christarazi** [comment]
@michi-covalent It should be in the second commit msg.

**Review by jrajahalme — APPROVED** [review]
Nice improvement!

**Comment by christarazi** [comment]
/test-1.21-5.4

**Comment by christarazi** [comment]
/test-1.21-5.4

**Comment by christarazi** [comment]
Marking ready to merge as we have approving reviews and all CI failure hit known flakes. Ignoring `test-1.21-5.4` because it is not going to provide any more signal than all the other Jenkins run anyway.

**Pull request merged**
