### PR TITLE
install/kubernetes: add extraInitContainers

### PR DESCRIPTION
**Pull request by bewing**
allow additional initContainers to be added to cilium-agent Daemonset via helm values.

### CODE REVIEW

**Comment by bewing** [comment]
fixed missing top-level documentation

**Review by squeed — APPROVED** [review]

**Comment by squeed** [comment]
Looks good, but you will have to add `initContainers` to our spelling dictionary :-/. Sorry for the run-around.

**Comment by bewing** [comment]
New changeset after running `Documentation/update-spelling_wordlist.sh initContainers`

**Review by qmonnet — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
