### PR TITLE
v1.13 Backports 2023-05-10

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
* [x] #23937 (@marseel)
 * [x] #24905 (@gentoo-root)
 * [x] #25219 (@tommyp1ckles)
 * [x] #25230 (@giorio94)
 * [x] #25212 (@michi-covalent)
 * [x] #25222 (@bimmlerd)
 * [ ] #24891 (@JohnJAS)
 * [x] #25147 (@jrajahalme)
 * [ ] #25215 (@youngnick)
   * ⚠️ Dropped since it has a bug
 * [x] #25244 (@sayboras)
 * [ ] #24914 (@margau)
 * [x] #25087 (@joamaki)
 * [x] #25257 (@pchaigno)
 * [x] #25322 (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 23937 24905 25219 25230 25212 25222 24891 25147 25244 24914 25087 25257 25322; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=23937,24905,25219,25230,25212,25222,24891,25147,25244,24914,25087,25257,25322
```

### CODE REVIEW

**Review by nathanjsweet — APPROVED** [review]
API changes lgtm

**Review by sayboras — APPROVED** [review]
Thanks, my commit looks good :heavy_check_mark:

**Comment by YutaroHayakawa** [comment]
/test-backport-1.13

**Review by michi-covalent — APPROVED** [review]

**Review by brlbil — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
My commit looks good. Thanks!

**Review by gentoo-root — APPROVED** [review]
Mine look good to me.

**Review by pchaigno — APPROVED** [review]
I assume there were no conflicts?

My PRs look good. Thanks!

**Review by marseel — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
k8s-1.24-kernel-4.19: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.24-kernel-4.19/37/
k8s-1.25-kernel-4.19: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-4.19/2080/
Hitting known flake as MLH mentioned: https://github.com/cilium/cilium/issues/25255

**Comment by YutaroHayakawa** [comment]
> I assume there were no conflicts?
Yep, except https://github.com/cilium/cilium/pull/25346#issuecomment-1541140166

**Comment by YutaroHayakawa** [comment]
/test-1.24-4.19

**Comment by YutaroHayakawa** [comment]
/test-1.25-4.19

**Comment by YutaroHayakawa** [comment]
Cilium Conformance E2E

Multiple cases are failing: https://github.com/cilium/cilium/actions/runs/4932680771

For case 1, 2, 3, 8, they are failing with `Run encryption test` steps (all IPsec)

```
📋 Test Report
❌ 2/42 tests failed (4/319 actions), 8 tests skipped, 1 scenarios skipped:
connectivity test failed: 2 tests failed
Test [no-policies]:
  ❌ no-policies/from-cidr-to-pod/host-netns-to-pod: cilium-test/host-netns-ntxmv (172.18.0.5) -> cilium-test/echo-other-node-97c9b7c9b-nht2g (10.244.2.240:8080)
  ❌ no-policies/from-cidr-to-pod/host-netns-to-pod: cilium-test/host-netns-ntxmv (172.18.0.5) -> cilium-test/echo-same-node-6c486c6b76-jh7cm (10.244.3.243:8080)
Test [from-cidr-host-netns]:
  ❌ from-cidr-host-netns/from-cidr-to-pod/host-netns-to-pod: cilium-test/host-netns-ntxmv (172.18.0.5) -> cilium-test/echo-other-node-97c9b7c9b-nht2g (10.244.2.240:8080)
  ❌ from-cidr-host-netns/from-cidr-to-pod/host-netns-to-pod: cilium-test/host-netns-ntxmv (172.18.0.5) -> cilium-test/echo-same-node-6c486c6b76-jh7cm (10.244.3.243:8080)
```

For case 6

```
📋 Test Report
❌ 1/2 tests failed (2/24 actions), 3 tests skipped, 0 scenarios skipped:
Test [north-south-loadbalancing-with-l7-policy]:
  ❌ north-south-loadbalancing-with-l7-policy/outside-to-nodeport/curl-2: cilium-test/host-netns-c8x4x (172.18.0.5) -> cilium-test/echo-same-node (echo-same-node:8080)
  ❌ north-south-loadbalancing-with-l7-policy/outside-to-nodeport/curl-4: cilium-test/host-netns-c8x4x (172.18.0.5) -> cilium-test/echo-other-node (echo-other-node:8080)
```

For case 7

```
📋 Test Report
❌ 1/2 tests failed (2/24 actions), 3 tests skipped, 0 scenarios skipped:
Test [north-south-loadbalancing-with-l7-policy]:
  ❌ north-south-loadbalancing-with-l7-policy/outside-to-nodeport/curl-2: cilium-test/host-netns-9k87s (172.18.0.3) -> cilium-test/echo-other-node (echo-other-node:8080)
  ❌ north-south-loadbalancing-with-l7-policy/outside-to-nodeport/curl-5: cilium-test/host-netns-9k87s (172.18.0.3) -> cilium-test/echo-same-node (echo-same-node:8080)
```

**Review by bimmlerd — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
/ci-e2e-1.13

**Comment by YutaroHayakawa** [comment]
k8s-1.25-kernel-4.19: Same error as before.

**Comment by YutaroHayakawa** [comment]
/test-1.25-4.19

**Comment by YutaroHayakawa** [comment]
Cilium Conformance E2E: Same failure. Likely to be a regression. Let me see...

**Review by tommyp1ckles — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
/ci-e2e-1.13

**Comment by YutaroHayakawa** [comment]
/test-1.24-4.19

**Comment by YutaroHayakawa** [comment]
/test-1.25-4.19

**Comment by brb** [comment]
https://github.com/cilium/cilium/pull/25409 needs to be merged first to fix the ci-e2e failures.

**Comment by thorn3r** [comment]
/ci-e2e-1.13

**Comment by thorn3r** [comment]
/ci-e2e-1.13

**Comment by thorn3r** [comment]
ci-e2e-1.13 is failing due to 
```
dial tcp: lookup localhost on 1.1.1.1:53: no such host
```

**Comment by thorn3r** [comment]
/ci-e2e-1.13

**Comment by jibi** [comment]
/ci-e2e-1.13

**Comment by jibi** [comment]
/test-1.25-4.19

**Comment by jibi** [comment]
/test-backport-1.13

**Comment by jibi** [comment]
travis is hitting https://github.com/cilium/cilium/issues/23509

**Review by jrajahalme — APPROVED** [review]
LGTM on my PR

**Review by joamaki — APPROVED** [review]

**Comment by jibi** [comment]
/test-1.25-4.19

**Comment by jibi** [comment]
/test-1.25-4.19

**Comment by thorn3r** [comment]
/ci-external-workloads-v1.13

**Comment by thorn3r** [comment]
/ci-gke-1.13

**Comment by thorn3r** [comment]
/ci-multicluster-1.13

**Comment by thorn3r** [comment]
ci-multicluster-1.13:
```
gcloud compute firewall-rules describe cilium-cilium-4983515101-rule
  shell: /usr/bin/bash -e {0}
  env:
    clusterName1: cilium-cilium-49[8](https://github.com/cilium/cilium/actions/runs/4983515101/jobs/8920641765#step:15:8)3515101-mesh-1
    clusterName2: cilium-cilium-4[9](https://github.com/cilium/cilium/actions/runs/4983515101/jobs/8920641765#step:15:9)83515[10](https://github.com/cilium/cilium/actions/runs/4983515101/jobs/8920641765#step:15:10)1-mesh-2
    clusterNameBase: cilium-cilium-4983515101-mesh
    zone: us-west2-a
    firewallRuleName: cilium-cilium-4983515101-rule
    k8s_version: 1.24
    cilium_cli_version: v0.14.2
    cilium_cli_ci_version: 
    check_url: https://github.com/cilium/cilium/actions/runs/4983515101
    USE_GKE_GCLOUD_AUTH_PLUGIN: true
    QUAY_ORGANIZATION: cilium
    QUAY_ORGANIZATION_DEV: cilium
    QUAY_CHARTS_ORGANIZATION_DEV: cilium-charts-dev
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /home/runner/work/cilium/cilium/gha-creds-85[11](https://github.com/cilium/cilium/actions/runs/4983515101/jobs/8920641765#step:15:11)58df06b30[12](https://github.com/cilium/cilium/actions/runs/4983515101/jobs/8920641765#step:15:12)a.json
    GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/cilium/cilium/gha-creds-851[15](https://github.com/cilium/cilium/actions/runs/4983515101/jobs/8920641765#step:15:15)8df06b3012a.json
    GOOGLE_GHA_CREDS_PATH: /home/runner/work/cilium/cilium/gha-creds-851158df06b3012a.json
    CLOUDSDK_CORE_PROJECT: ***
    CLOUDSDK_PROJECT: ***
    GCLOUD_PROJECT: ***
    GCP_PROJECT: ***
    GOOGLE_CLOUD_PROJECT: ***
    CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
    CLOUDSDK_METRICS_ENVIRONMENT_VERSION: 1.1.1
ERROR: (gcloud.compute.firewall-rules.describe) argument NAME: Must be specified.
Usage: gcloud compute firewall-rules describe NAME [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud compute firewall-rules describe --help
Error: Process completed with exit code 2.
```

**Comment by jibi** [comment]
/test-1.25-4.19

**Comment by thorn3r** [comment]
/ci-gke-1.13

**Comment by thorn3r** [comment]
/ci-multicluster-1.13

**Pull request merged**
