### PR TITLE
Update Go to 1.14.3

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
Waiting for the `golang:1.14.3` image to appear on Docker Hub and then being able to build `cilium-builder` and `cilium-runtime` images.

**Review by rolinh — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Review by gandro — APPROVED** [review]

**Comment by tklauser** [comment]
retest-runtime

**Comment by tklauser** [comment]
retest-4.19

**Review by aanm — APPROVED** [review]

**Pull request merged**
