### PR TITLE
v1.10: Update Go to 1.16.13

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.10

**Review by pchaigno — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Comment by tklauser** [comment]
/test-backport-1.10

**Comment by tklauser** [comment]
/test-backport-1.10

**Comment by tklauser** [comment]
GKE failure is #18285, opened #18466 for the net-next failure. Other tests passed and reviews are in, marking as ready to merge.

**Comment by tklauser** [comment]
/test-backport-1.10

**Comment by tklauser** [comment]
/test-1.17-4.9

**Pull request merged**
