### PR TITLE
v1.15 Backports 2024-01-22

### PR DESCRIPTION
**Pull request by giorio94**
* [x] #29983 (@giorio94)
    - :information_source: Skipped renovate and codeowners changes.
    - :information_source: Slightly adapted the clustermesh upgrade workflow -- in Cilium v1.14 and earlier, the clustermesh configuration secret is created only when the clustermesh-apiserver is enabled. For this reason, we need to enable it also when actually connecting to a remote kvstore cluster, although with zero replicas.
 * [x] #29926 (@giorio94)
 * [x] #30207 (@giorio94)
 * [x] #29460 (@tommyp1ckles)
 * [x] #30128 (@julianwiedmann)
 * [x] #30260 (@sayboras)
 * [ ] #30257 (@danehans)
 * [ ] #28286 (@tamilmani1989)
 * [ ] #30131 (@ayuspin)
 * [x] #30335 (@giorio94)
 * [x] #30126 (@youngnick)
 * [x] #30343 (@julianwiedmann)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 29983 29926 30207 29460 30128 30260 30257 28286 30131 30335 30126 30343
```

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]

**Comment by giorio94** [comment]
/test-backport-1.15

**Comment by giorio94** [comment]
/test-backport-1.15

**Comment by giorio94** [comment]
/test-backport-1.15

**Review by tommyp1ckles — APPROVED** [review]

**Review by brlbil — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my changes 👍

**Review by youngnick — APPROVED** [review]

**Comment by giorio94** [comment]
Rebased onto the tip of v1.15 to fix a conflict

**Comment by giorio94** [comment]
/test-backport-1.15

**Comment by giorio94** [comment]
Conformance E2E hit https://github.com/cilium/cilium/issues/30266
The Conformance Ginkgo and Conformance Runtime failures were GH one-off internal errors

**Comment by giorio94** [comment]
CI is green and most of the reviews are in (the remaining PRs didn't incur in any conflict, and I performed an additional sanity check). Marking as ready to merge (assuming tophat review will be covered before merging).

**Review by squeed — APPROVED** [review]

**Pull request merged**
