### PR TITLE
[CI] allow to specify focus via GH comment

### PR DESCRIPTION
**Pull request by nebril**
Usage: instead of `test-me-please` use `test-focus ginkgo_focus`

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9667)

### CODE REVIEW

**Comment by nebril** [comment]
test-focus K8sDemos*

**Comment by nebril** [comment]
test-focus K8sDemos*

**Comment by nebril** [comment]
test-focus RuntimeFQDNPolicies Enforces ToFQDNs policy

**Comment by nebril** [comment]
test-focus RuntimeFQDNPolicies Enforces ToFQDNs policy

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-focus K8sDemos*

**Comment by nebril** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Pull request merged**
