### PR TITLE
Helm: Add possibility to use affinity on certgen job

### PR DESCRIPTION
**Pull request by seb-lafond**
Add possibility to use affinity on certgen job.

Useful when using nodeAffinity to allow running certgen job on a preferred node.

Related: #28167

```release-note
Helm: Add possibility to use affinity on certgen job
```

### CODE REVIEW

**Review by gandro — COMMENTED** [review]
Thanks for the PR! The change itself looks good to me, but there are a few files that need to be auto-regenerated. In particular:

```
make -C Documentation update-helm-values
make -C install/kubernetes
```

**Comment by gandro** [comment]
Thanks for fixing the docs. Could you please squash your commits into one, so each commit by itself passes "make"? That enables us to use `git bisect`

**Comment by joestringer** [comment]
Hey @youngnick could you take a look on behalf of @cilium/sig-k8s ?

**Review by gandro — APPROVED** [review]

**Comment by gandro** [comment]
@seb-lafond Could you rebase on `main` to pull in the newest changes that are needed for CI to pass?

**Review by aanm — APPROVED** [review]

**Comment by seb-lafond** [comment]
Thanks all !

**Pull request merged**
