### PR TITLE
early spring cleanup helper prep for xdp

### PR DESCRIPTION
**Pull request by borkmann**
Given we've been refactoring the whole BPF code base via #10333, perform some more cleanup including rebase of #10017 while at it, so others only need to rebase once. See commit msg @brb

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10344)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Pull request merged**
