### PR TITLE
daemon: Upgrade spf13/viper

### PR DESCRIPTION
**Pull request by raybejjani**
We began using .IsSet to handle --tofqdns-min-ttl=0 invocations but
older viper versions always returned true from this function. This then
caused the default value to never be used, instead using the 0 default
used when initializing the variable.

fixes 078f19d6b52ebc099edc2ed2a48a25818b6e4a56

I'm not sure that the upgrade went quite correctly, there seem to be a few changes I wouldn't expect in there.
This may also be the worse way to do this, instead of using the workaround in https://github.com/spf13/viper/issues/323#issuecomment-309570752. It passes the cobra object around and handles the flag more directly, and can be backported more simply (but we don't need to backport https://github.com/cilium/cilium/pull/9743 anymore, I'd say).
```golang
diff --git a/daemon/daemon_main.go b/daemon/daemon_main.go
index d227bddd1..303ea10a4 100644
--- a/daemon/daemon_main.go
+++ b/daemon/daemon_main.go
@@ -771,7 +771,7 @@ func initConfig() {
 
 func initEnv(cmd *cobra.Command) {
 	// Prepopulate option.Config with options from CLI.
-	option.Config.Populate()
+	option.Config.Populate(cmd)
 
 	// add hooks after setting up metrics in the option.Confog
 	logging.DefaultLogger.Hooks.Add(metrics.NewLoggingHook(components.CiliumAgentName))
diff --git a/daemon/daemon_test.go b/daemon/daemon_test.go
index b14d7ea08..9562e973b 100644
--- a/daemon/daemon_test.go
+++ b/daemon/daemon_test.go
@@ -81,7 +81,7 @@ func setupTestDirectories() {
 func TestMain(m *testing.M) {
 	// Set up all configuration options which are global to the entire test
 	// run.
-	option.Config.Populate()
+	option.Config.Populate(RootCmd)
 	option.Config.IdentityAllocationMode = option.IdentityAllocationModeKVstore
 	option.Config.DryMode = true
 	option.Config.Opts = option.NewIntOptions(&option.DaemonMutableOptionLibrary)
diff --git a/pkg/envoy/envoy_test.go b/pkg/envoy/envoy_test.go
index 83772aa73..f8e4ae926 100644
--- a/pkg/envoy/envoy_test.go
+++ b/pkg/envoy/envoy_test.go
@@ -65,7 +65,12 @@ func (r *dummyEndpointInfoRegistry) FillEndpointIdentityByIP(ip net.IP, info *ac
 }
 
 func (s *EnvoySuite) TestEnvoy(c *C) {
-	option.Config.Populate()
+	RootCmd = &cobra.Command{
+		Use:   "test",
+		Short: "",
+		Run:   func(cmd *cobra.Command, args []string) {},
+	}
+	option.Config.Populate(&RootCmd)
 	option.Config.ProxyConnectTimeout = 1
 	c.Assert(option.Config.ProxyConnectTimeout, Not(Equals), 0)
 	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
diff --git a/pkg/option/config.go b/pkg/option/config.go
index 009ce0a32..0b995d266 100644
--- a/pkg/option/config.go
+++ b/pkg/option/config.go
@@ -39,6 +39,7 @@ import (
 
 	"github.com/prometheus/client_golang/prometheus"
 	"github.com/sirupsen/logrus"
+	"github.com/spf13/cobra"
 	"github.com/spf13/viper"
 )
 
@@ -1597,7 +1598,7 @@ func (c *DaemonConfig) parseExcludedLocalAddresses(s []string) error {
 }
 
 // Populate sets all options with the values from viper
-func (c *DaemonConfig) Populate() {
+func (c *DaemonConfig) Populate(cmd *cobra.Command) {
 	var err error
 
 	c.AccessLog = viper.GetString(AccessLog)
@@ -1739,14 +1740,16 @@ func (c *DaemonConfig) Populate() {
 	} else {
 		log.Fatal("tofqdns-max-deferred-connection-deletes must be positive, or 0 to disable deferred connection deletion")
 	}
+	flag := cmd.Flags().Lookup(ToFQDNsMinTTL)
 	switch {
-	case viper.IsSet(ToFQDNsMinTTL): // set by user
+	case flag != nil && flag.Changed: // set by user
 		c.ToFQDNsMinTTL = viper.GetInt(ToFQDNsMinTTL)
 	case c.ToFQDNsEnablePoller:
 		c.ToFQDNsMinTTL = defaults.ToFQDNsMinTTLPoller
 	default:
 		c.ToFQDNsMinTTL = defaults.ToFQDNsMinTTL
 	}
+
 	c.ToFQDNsProxyPort = viper.GetInt(ToFQDNsProxyPort)
 	c.ToFQDNsPreCache = viper.GetString(ToFQDNsPreCache)
 

```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9796)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by raybejjani** [comment]
test-me-please

**Comment by brb** [comment]
CI provisioning failed.

**Comment by brb** [comment]
test-me-please

**Pull request merged**
