### PR TITLE
v1.14 Backports 2023-08-22

### PR DESCRIPTION
**Pull request by tklauser**
* [x] #26641 (@ti-mo)
 * [ ] #26964 (@vakalapa)
 * [ ] #27222 (@qmonnet)
 * [x] #27342 (@lambdanis)
 * [ ] #27306 (@darkrift)
 * [ ] #27346 (@qmonnet)
   * :warning: minor merge conflict resolved by omitting changed files that aren't present in `v1.14`
 * [ ] #27230 (@brb)
 * [x] #27365 (@mhofstetter)
 * [x] #27397 (@giorio94)
 * [x] #27353 (@giorio94)
   * :warning: minor merge conflict resolved by adjusting the context of the patch
 * [x] #27453 (@mhofstetter)
   * :warning: minor merge conflict resolved by adjusting the context of the patch
 * [ ] #27495 (@ishuar)
 * [ ] #27409 (@tanjunchen)
 * [x] #27309 (@sayboras)
 * [x] #27457 (@brlbil)
 * [ ] #27251 (@farodin91)
 * [x] #26742 (@giorio94)
 * [ ] #27537 (@qmonnet)
 * [x] #27511 (@rolinh)
   * :warning: minor merge conflicts in files generated from helm values. Resolved by regenerating.
 * [ ] #27496 (@Alex-Waring)
 * [ ] #27475 (@ishuar)
 * [ ] #27561 (@kvaps)

PRs skipped due to conflicts:

 * #26896 (@meyskens)
 * #27622 (@borkmann)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 26641 26964 27222 27342 27306 27346 27230 27365 27397 27353 27453 27495 27409 27309 27457 27251 26742 27537 27511 27496 27475 27561; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=26641,26964,27222,27342,27306,27346,27230,27365,27397,27353,27453,27495,27409,27309,27457,27251,26742,27537,27511,27496,27475,27561
```

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.14

**Review by rolinh — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
My commits look good. Thanks!

**Review by mhofstetter — APPROVED** [review]
LGTM - thank you!

**Review by brlbil — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
Looks good for my commit, thanks 👍

**Review by ghost — APPROVED** [review]

**Review by ti-mo — APPROVED** [review]
Lookin' good, thanks!

**Comment by doniacld** [comment]
* [] https://github.com/cilium/cilium/pull/27532
I am not sure why you got a conflict since this PR is already backported.
cf https://github.com/cilium/cilium/pull/27571

**Comment by tklauser** [comment]
/test-backport-1.14

**Comment by tklauser** [comment]
/test-backport-1.14

**Comment by tklauser** [comment]
/test-backport-1.14

**Comment by tklauser** [comment]
/test-backport-1.14

**Review by joestringer — APPROVED** [review]
I briefly reviewed the remaining backported commits, LGTM.

**Pull request merged**
