### PR TITLE
test: Debug IPsec test

### PR DESCRIPTION
**Pull request by pchaigno**
First commit cleans up some test conditions. The second adds some debug logs in case of failure, to help debug https://github.com/cilium/cilium/issues/16699.

Related: https://github.com/cilium/cilium/issues/16699.

### CODE REVIEW

**Comment by pchaigno** [comment]
test-1.19-5.4

**Comment by pchaigno** [comment]
test-1.19-5.4

**Comment by pchaigno** [comment]
test-only --kernel_version=5.4 --k8s_version=1.19 --focus="K8sDatapathConfig Transparent encryption DirectRouting Check connectivity with transparent encryption and direct routing"

**Comment by pchaigno** [comment]
test-1.19-5.4

**Comment by pchaigno** [comment]
test-only --kernel_version=5.4 --k8s_version=1.19 --focus="K8sDatapathConfig Transparent encryption DirectRouting Check connectivity with transparent encryption and direct routing"

**Comment by pchaigno** [comment]
test-only --kernel_version=5.4 --k8s_version=1.19 --focus="K8sDatapathConfig Transparent encryption DirectRouting Check connectivity with transparent encryption and direct routing"

**Comment by pchaigno** [comment]
test-1.19-5.4

**Comment by pchaigno** [comment]
test-1.19-5.4

**Comment by pchaigno** [comment]
test-only --kernel_version=5.4 --k8s_version=1.19 --focus="K8sDatapathConfig Transparent encryption DirectRouting Check connectivity with transparent encryption and direct routing"

**Comment by pchaigno** [comment]
test-1.19-5.4

**Comment by pchaigno** [comment]
test-only --kernel_version=5.4 --k8s_version=1.19 --focus="K8sDatapathConfig Transparent encryption DirectRouting Check connectivity with transparent encryption and direct routing"

**Comment by nbusseneau** [comment]
test-1.19-5.4

**Comment by nebril** [comment]
test-1.19-5.4

**Review by christarazi — APPROVED** [review]
Why can't the bugtool retrieve this output?

**Comment by pchaigno** [comment]
> Why can't the bugtool retrieve this output?

Because the Cilium agent is fataling, so by the time we get the bugtool reports, the Cilium pods are crashlooping and we can't run anything on them. See https://jenkins.cilium.io/job/cilium-master-k8s-1.19-kernel-5.4/367/testReport/junit/Suite-k8s-1/19/K8sDatapathConfig_Transparent_encryption_DirectRouting_Check_connectivity_with_transparent_encryption_and_direct_routing/ from https://github.com/cilium/cilium/issues/16699.

**Comment by pchaigno** [comment]
test-1.19-5.4

**Comment by pchaigno** [comment]
The changes here are not specific to IPsec or the datapath so skipping that review. Tests are passing. Merging.

**Pull request merged**
