### PR TITLE
Envoy TLS fixes

### PR DESCRIPTION
**Pull request by jrajahalme**
Update `cilium-envoy` image to properly issue an SNI for the upstream TLS connection.

Avoid merging policy rules for `reserved:none`, which errored out for rules containing different TLS certs, even when `toFQDNs` are for different domain names.

Bump the max time dns proxy waits for policy plumbing from 50 to 100ms, as CI tests with TLS contexts would intermittently fail otherwise.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9820)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
TLS test reaching out to swapi.co times out in both k8s tests, trying again to see if this is consistent.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Pull request merged**
