### PR TITLE
v1.9 backports 2021-07-15 (2)

### PR DESCRIPTION
**Pull request by joestringer**
* ~#16589 -- vagrant: Bump all Vagrant box versions (@pchaigno)~
   * Minor conflicts since the box versions were completely different
 * ~#16804 -- contrib: Explicitly set remote for backport branches (@twpayne)~
 * #15999 -- Improve logging when cgroupfs mount fails (johngv2)
   * Had to rebase across file rename pkg/cgroups/cgroups{,_linux}.go

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 15999; do contrib/backporting/set-labels.py $pr done 1.9; done
```

EDIT: Dropped first two PRs to ship the fix with the next release. Will follow up on CI to check whether the vagrant change impacts branch stability.

### CODE REVIEW

**Comment by aditighag** [comment]
>Improve logging when cgroupfs mount fails #15999 -- Improve logging when cgroupfs mount fails (johngv2)

Lgtm, thanks! Let's include this in the upcoming 1.9 release.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-backport-1.9

**Review by pchaigno — APPROVED** [review]
My PR looks good :+1:

**Comment by joestringer** [comment]
CI triage:

* [K8s-Upstream test](https://jenkins.cilium.io/job/Cilium-PR-K8s-Upstream/3243/execution/node/76/log/) looks completely broken:  
  ```
  19:10:44  + cd /home/jenkins/workspace/Cilium-PR-K8s-Upstream/src/github.com/cilium/cilium/test
  19:10:44  + vagrant ssh k8s1-1.19 -c cd /home/vagrant/go/src/github.com/cilium/cilium; ./test/kubernetes-test.sh 
  6ccf6c1132d866f9ac66320f8b5c1cf0efcec4b2
  ...
  19:11:37  result match, continue with kubernetes
  19:11:37  Installing kubetest manually
  19:11:37  mkdir: cannot create directory '/home/vagrant/go/src/k8s.io': Permission denied
  ```

* [Kernel 5.4 job summary generation failed](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-5.4/75/), but it hit the "2GiB logs" issue like we see in https://github.com/cilium/cilium/issues/16050 , known issue with the verifier test on 5.4 jenkins runs.

* [Runtime jobs hit two issues](https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/5363/): #16713 and #14676 (fixed by #15848 but not yet backported).

These do not represent regressions so fine to merge.

**Comment by pchaigno** [comment]
> K8s-Upstream test looks completely broken:

Are you sure this is not a regression? The only other time I saw this was when @twpayne first tried to backport #16589. I'm surprised #16589 would make k8s-upstream fail but not our 4.19 CI job, but maybe @twpayne was right.

**Comment by pchaigno** [comment]
> 19:11:37  mkdir: cannot create directory '/home/vagrant/go/src/k8s.io': Permission denied

Oh, it could be that this directory is only accessed in the k8s-upstream test. We've had some changes in VM image permissions recently...

**Comment by aanm** [comment]
@pchaigno I don't think we need to block 1.9.9 with this PR, what do you think?

**Comment by pchaigno** [comment]
> @pchaigno I don't think we need to block 1.9.9 with this PR, what do you think?

The Union for v1.9.9 political party agrees. There's only CI and misc changes.

**Comment by joestringer** [comment]
test-backport-1.9

**Comment by joestringer** [comment]
CI triage:
* [K8s-1.12-net-next](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/1777/testReport/junit/Suite-k8s-1/12/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device/) hit https://github.com/cilium/cilium/issues/12511 .
* [K8s-1.17-kernel-5.4](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-5.4/76/) hit https://github.com/cilium/cilium/issues/16050 .
* [K8s-1.18-kernel-4.19](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.18-kernel-4.19/213/) hit https://github.com/cilium/cilium/issues/16928 . While this is a new failure, there is no way it's related to the changes being made in this PR. Will follow up separately.

**Pull request merged**
