### PR TITLE
v1.12 backports 2023-01-13

### PR DESCRIPTION
**Pull request by ti-mo**
* #20619 -- test/k8s: remove l7_demos test (@tklauser)
 * #21267 -- Adding/fixing DNSProxy metrics (@rahulkjoshi)
 * #22620 -- Update Cilium install guide about EKS aws-node DaemonSet potential connectivity problem on uninstall (@NikAleksandrov)
 * #22821 -- Add sphinxcontrib-googleanalytics to doc requirements (@chalin)
 * #22794 -- bpf: nodeport: wire up trace aggregation for rev_nodeport_lb6() (@julianwiedmann)
  -> please double-check if this makes sense, rev_nodeport_lb6 changed quite a bit
 * #22807 -- Update Layer 7 Protocol Visibility Document. (@obaranov1)
 * #22745 -- Improve fqdn events logging management (@pippolo84)
 * #22678 -- bpf: nodeport: fix tracing for handle_nat_fwd() (@julianwiedmann)
 * #22930 -- Fix missing node neigh metric for counting arping requests (@christarazi)
 * #22985 -- datapath: Fix L7 ingress with XDP (@brb)
 * #22884 -- Fix crash of CES queue delay metric when CESTracker is nil (@dlapcevic)
 * #22977 -- iptables: skip reverse IP lookup (@jibi)
 * #22972 -- bpf: Fix LB loopback path with ingress policy (@aditighag)
 * #23018 -- bpf: test: fix xdp_lb4_forward_to_other_node test (@julianwiedmann)
 * #23037 -- ctmap: fix-up host_local flag in the DSR NAT entry for GC test (@julianwiedmann)
 * #22962 -- clustermesh: Add missing brackets of etcd option (@YutaroHayakawa)
 * #21857 -- test: net_policies: delete custom IP routes after test completion (@julianwiedmann)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20619 21267 22620 22821 22794 22807 22745 22678 22930 22985 22884 22977 22972 23018 23037 22962 21857; do contrib/backporting/set-labels.py $pr done 1.12; done
```

---

PRs dropped from this round:
 * #22928 -- CODEOWNERS: Cover test/bpf_tests by sig-datapath (@christarazi)
  -> dropped, maintenance branches have different CODEOWNERS
 * #21768 -- Endpoint/CEP Ownership Fix (@tommyp1ckles)
  -> relies on missing node.GetCiliumEndpointNodeIP()
 * #22810 -- nodeport: fix CT accounting in revDNAT path (@julianwiedmann)
  -> generated quite a large diff I wasn't sure what to do with
 * #22768 -- Make cilium pprof listen address configurable (@chancez)
  -> can probably be made to fit with some work from the author; do we really want/need to backport this?
 * #22220 -- Enable Google Analytics 4 (@chalin)
 * #21980 -- datapath: Fix L7 reply to outside when endpoint routes disabled (@brb)

Manual fix added to skip `check-missing-tags-in-tests.sh` in v1.12 branch due to 7435adb50f.

### CODE REVIEW

**Comment by ti-mo** [comment]
/test-backport-1.12

**Review by tklauser — APPROVED** [review]
Looks good for my change, thanks.

**Review by aditighag — APPROVED** [review]
Backport changes for my PR look good. Thanks!

**Comment by chancez** [comment]
[PR created to backport](https://github.com/cilium/cilium/pull/23094):
 * #22768 -- Make cilium pprof listen address configurable (@chancez)

**Review by pippolo84 — APPROVED** [review]
LGTM for PR #22745, thanks! :100:

**Review by christarazi — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]
> * [bpf: nodeport: wire up trace aggregation for rev_nodeport_lb6() #22794](https://github.com/cilium/cilium/pull/22794) -- bpf: nodeport: wire up trace aggregation for rev_nodeport_lb6() (@julianwiedmann)
>       -> please double-check if this makes sense, rev_nodeport_lb6 changed quite a bit

Looks good, thanks!

**Comment by julianwiedmann** [comment]
The [error](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.24-kernel-net-next/676/testReport/junit/Suite-k8s-1/24/K8sEgressGatewayTest_tunnel_disabled_with_endpointRoutes_enabled_no_egress_gw_policy_connectivity_works/) in `1.24-net-next`
> RTNETLINK answers: File exists

makes me think we need https://github.com/cilium/cilium/pull/21857 for `v1.12`.

**Review by jibi — APPROVED** [review]

**Review by NikAleksandrov — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Review by YutaroHayakawa — APPROVED** [review]
My change looks good. Thanks!

**Comment by aanm** [comment]
/test-backport-1.12

**Comment by aanm** [comment]
/test-backport-1.12

**Review by YutaroHayakawa — APPROVED** [review]

**Comment by ldelossa** [comment]
ConformanceGKE (ci-gke-1.12) — Connectivity test failed - Unrelated to changes:
```
Run while [ "$(gcloud container operations list --filter="status=RUNNING AND targetLink~cilium-cilium-3948015237" --format="value(name)")" ];do
ERROR: (gcloud.container.clusters.delete) Some requests did not succeed:
 - args: ["ResponseError: code=404, message=Not found: projects/***/zones/us-west2-a/clusters/cilium-cilium-3948015237.\nNo cluster named 'cilium-cilium-3948015237' in ***."]
   exit_code: 1
```

k8s-1.19-kernel-4.9 (test-1.19-4.9) — Build finished. - https://github.com/cilium/cilium/issues/22578

k8s-1.21-kernel-4.9 (test-1.21-4.9) — Build finished. - https://github.com/cilium/cilium/issues/22578

**Comment by christarazi** [comment]
@ldelossa Are the underlying errors the same in the failure vs the flake? The failure reports a level=error log msg which is typically something we should scrutinize closer.

**Comment by ldelossa** [comment]
BPF checks / build datapath (pull_request) Failing after 6m  - looks legitimate. The Go driven BPF tests are complaining about a minimum kernel version. 
 
 That test is using a Ubuntu 22.04 image: https://github.com/cilium/cilium/actions/runs/3947994288/workflow#L75
 That should be a newer kernel then >= 4.12. 

The error message `    bpf_test.go:261: error while running setup prog: can't test program: BPF_PROG_TEST_RUN not supported (requires >= v4.12)` is returned from cilium/ebpf.Program.Test().

**Comment by ldelossa** [comment]
@christarazi Those tests fail consistently with:

```
12:08:34 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-vt8gd': Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 
``` 

Which appear to be a known flake.

**Comment by joestringer** [comment]
@ldelossa where did you get the immediate above comment from? Are you sure that's the failure and not an intermediate report for a specific `STEP` in the test? I don't see `FAIL:`., and when I follow the links from the checks box below for k8s-1.x-kernel-4.9 failures, I don't see the above as the cause.

**Comment by christarazi** [comment]
That was just a transient error that happened earlier. If you scroll down further, you should see

```
=== Test Finished at 2022-12-06T12:09:26Z====
12:09:26 STEP: Running JustAfterEach block for EntireTestsuite K8sDatapathConfig
FAIL: Found 1 io.cilium/app=operator logs matching list of errors that must be investigated:
level=error
```

**Comment by ldelossa** [comment]
Aha I see. 

In that case:

 k8s-1.21-kernel-4.9 (test-1.21-4.9) — Build finished.  - Existing flake: https://github.com/cilium/cilium/issues/21279
 
 Will re-run for 1.19 error, since I do not see any issue for that Kafka related fail.

**Comment by ldelossa** [comment]
/test-1.19-4.9

**Comment by ldelossa** [comment]
> /test-1.19-4.9

Flake, I'll track a ticket with that previous failure.

**Comment by ldelossa** [comment]
This backport needed some sugar on top: https://github.com/cilium/cilium/pull/23190

The original PR is opened on Timo's fork which I can't push to, so we'll use the new PR above to merge in the backports.

**Comment by ti-mo** [comment]
Superseded by #23190.

@ldelossa For posterity, this PR had 'Allow edits by maintainers' enabled, so a `gh pr checkout ti-mo:pr/v1.12-backport-2023-01-13` should've set things up for you to push to this branch without issues.

**Comment by ldelossa** [comment]
@ti-mo yup, now I know, my bad. I should have just gave it a try, but wasn't sure if you wanted pushes directly to your fork.

**Pull request closed without merging**
