### PR TITLE
[v1.10] Consider VPC's secondary CIDRs during cilium_host IP restoration

### PR DESCRIPTION
**Pull request by gandro**
This is a custom v1.10 backport of 

- #19341 by @hemanthmalla 

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 19341; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Review by hemanthmalla — APPROVED** [review]
@gandro changes LGTM. Thanks for backporting this. These are the exact same changes going into [1.11](https://github.com/cilium/cilium/pull/20364/commits/fdd86ee2ab9db64e069b0be943f075ef242e8a68) as well right ?

**Comment by gandro** [comment]
> @gandro changes LGTM. Thanks for backporting this. These are the exact same changes going into [1.11](https://github.com/cilium/cilium/pull/20364/commits/fdd86ee2ab9db64e069b0be943f075ef242e8a68) as well right ?

Oh, I didn't realize the v1.11 backport also had conflicts. I did the backport independently of that, but it looks like the main conflict (in the `if ipv6` branch in `restoreCiliumHostIPs`) was resolved exactly in the same manner. So the two look identical to me.

**Comment by gandro** [comment]
/ci-aks-1.10

**Comment by gandro** [comment]
/ci-aks-1.10

**Review by qmonnet — APPROVED** [review]

**Pull request merged**
