### PR TITLE
WIP: Tests: Update base box to cilium/ginkgo

### PR DESCRIPTION
**Pull request by eloycoto**
Updated the base box from Cilium/ubuntu-16.10 to cilium/ginkgo. The main
change is the version update from Ubuntu 16.10 to Ubuntu 17.10

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by ianvernon** [comment]
The root `Vagrantfile` has a variety of setup steps that it takes that the CI doesn't test (specifically when launched with `K8s=1 ./contrib/vagrant/start.sh`). Can you please test that locally and verify that it is not broken as part of this change?

Feel free to shoot this town - maybe we could have some type of 'infrastructure' Jenkins build which checks the variety of VM use cases (i.e., do the VMs boot correctly with the variety of options contained within `contrib/vagrant/start.sh`). What do you think? cc: @aanm

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
Another PR with this work

**Pull request closed without merging**
