### PR TITLE
hubble: traffic direction filter

### PR DESCRIPTION
**Pull request by kaworu**
Before this patch, filtering Hubble flows by traffic direction (e.g. ingress or egress) was not possible.

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]
But what if I want to next steps??

**Comment by qmonnet** [comment]
There's some user impact here, maybe switch to `release-note/minor`?

**Review by michi-covalent — APPROVED** [review]

**Review by chancez — APPROVED** [review]

**Review by gandro — APPROVED** [review]
Thanks!

**Review by aditighag — APPROVED** [review]
Nice!

**Comment by kaworu** [comment]
/test-1.24-5.4

**Pull request merged**
