### PR TITLE
v1.6 backports 2020-04-01

### PR DESCRIPTION
**Pull request by jrajahalme**
* #10564 -- test: Update Istio integration to release 1.5.0 (@jrajahalme)
 * #10730 -- test: Update Istio integration to release 1.5.1 (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 10564 10730; do contrib/backporting/set-labels.py $pr done 1.6; done
```

```release-note
Istio integration is updated to release 1.5.1, with backported fix for GKE/COS.
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@jrajahalme it seems only the istio tests have failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18441/testReport/junit/Suite-k8s-1/16/K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter_service_connectivity/

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by gandro** [comment]
test-me-please

**Comment by nebril** [comment]
never-tell-me-the-odds

**Comment by nebril** [comment]
restart-ginkgo

**Comment by gandro** [comment]
restart-ginkgo

**Comment by gandro** [comment]
test-missed-k8s

**Comment by gandro** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
@jrajahalme What's the situation with this backport PR?

**Comment by joestringer** [comment]
test-backport-1.6

**Comment by joestringer** [comment]
Bookinfo test failures in these builds suggest a legitimate breakage from this PR:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3163/
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19717/

**Comment by jrajahalme** [comment]
closing in favor of #12356

**Pull request closed without merging**
