### PR TITLE
kind e2e network policy use only 10 tests in parallel

### PR DESCRIPTION
**Pull request by aojea**
The network policy tests run a lot of pods and this can cause
    resource starvation on CI environments.

Example of local execution, it got completely stuck in a pretty decent machine

```
kubectl get pods -A
NAMESPACE                   NAME                                         READY   STATUS    RESTARTS   AGE
default                     server-deployment-75fddc65fd-kd9gp           1/1     Running   0          33h
kube-system                 cilium-7s6tz                                 1/1     Running   0          31h
kube-system                 cilium-m7f2j                                 1/1     Running   0          31h
kube-system                 cilium-node-init-5bd8d                       1/1     Running   0          33h
kube-system                 cilium-node-init-ckxf4                       1/1     Running   0          33h
kube-system                 cilium-operator-56c965c499-f5g8k             1/1     Running   0          33h
kube-system                 cilium-operator-56c965c499-xncnk             1/1     Running   0          33h
kube-system                 coredns-787d4945fb-prvmk                     1/1     Running   0          34h
kube-system                 coredns-787d4945fb-xpb46                     1/1     Running   0          34h
kube-system                 etcd-kind-control-plane                      1/1     Running   0          34h
kube-system                 kube-apiserver-kind-control-plane            1/1     Running   0          34h
kube-system                 kube-controller-manager-kind-control-plane   1/1     Running   0          34h
kube-system                 kube-scheduler-kind-control-plane            1/1     Running   0          34h
local-path-storage          local-path-provisioner-c8855d4bb-nnlmm       1/1     Running   0          34h
netpol-x-1362               a                                            1/1     Running   0          21m
netpol-x-1362               b                                            1/1     Running   0          21m
netpol-x-1362               c                                            1/1     Running   0          21m
netpol-x-1399               a                                            1/1     Running   0          21m
netpol-x-1399               b                                            1/1     Running   0          21m
netpol-x-1399               c                                            1/1     Running   0          21m
netpol-x-1819               a                                            1/1     Running   0          21m
netpol-x-1819               b                                            1/1     Running   0          21m
netpol-x-1819               c                                            1/1     Running   0          21m
netpol-x-2257               a                                            1/1     Running   0          14m
netpol-x-2257               b                                            1/1     Running   0          14m
netpol-x-2257               c                                            1/1     Running   0          14m
netpol-x-2739               a                                            1/1     Running   0          21m
netpol-x-2739               b                                            1/1     Running   0          21m
netpol-x-2739               c                                            1/1     Running   0          21m
netpol-x-2829               a                                            2/2     Running   0          21m
netpol-x-2829               b                                            2/2     Running   0          21m
netpol-x-2829               c                                            2/2     Running   0          21m
netpol-x-3360               a                                            1/1     Running   0          21m
netpol-x-3360               b                                            1/1     Running   0          21m
netpol-x-3360               c                                            1/1     Running   0          21m
netpol-x-3651               a                                            1/1     Running   0          21m
netpol-x-3651               b                                            1/1     Running   0          21m
netpol-x-3651               c                                            1/1     Running   0          21m
netpol-x-3700               a                                            0/1     Pending   0          4m21s
netpol-x-3700               b                                            0/1     Pending   0          4m21s
netpol-x-3700               c                                            0/1     Pending   0          4m21s
netpol-x-4190               a                                            1/1     Running   0          21m
netpol-x-4190               b                                            1/1     Running   0          21m
netpol-x-4190               c                                            1/1     Running   0          21m
netpol-x-4315               a                                            1/1     Running   0          14m
netpol-x-4315               b                                            1/1     Running   0          14m
netpol-x-4315               c                                            1/1     Running   0          14m
netpol-x-5512               a                                            1/1     Running   0          21m
netpol-x-5512               b                                            1/1     Running   0          21m
netpol-x-5512               c                                            1/1     Running   0          21m
netpol-x-5551               a                                            2/2     Running   0          21m
netpol-x-5551               b                                            2/2     Running   0          21m
netpol-x-5551               c                                            2/2     Running   0          21m
netpol-x-6231               a                                            2/2     Running   0          14m
netpol-x-6231               b                                            2/2     Running   0          14m
netpol-x-6231               c                                            2/2     Running   0          14m
netpol-x-6476               a                                            1/1     Running   0          21m
netpol-x-6476               b                                            1/1     Running   0          21m
netpol-x-6476               c                                            1/1     Running   0          21m
netpol-x-8368               a                                            1/1     Running   0          21m
netpol-x-8368               b                                            1/1     Running   0          21m
netpol-x-8368               c                                            1/1     Running   0          21m
netpol-x-917                a                                            1/1     Running   0          21m
netpol-x-917                b                                            1/1     Running   0          21m
netpol-x-917                c                                            1/1     Running   0          21m
netpol-x-945                a                                            1/1     Running   0          14m
netpol-x-945                b                                            1/1     Running   0          14m
netpol-x-945                c                                            1/1     Running   0          14m
netpol-x-9656               a                                            1/1     Running   0          21m
netpol-x-9656               b                                            1/1     Running   0          21m
netpol-x-9656               c                                            1/1     Running   0          21m
netpol-x-9698               a                                            1/1     Running   0          4m45s
netpol-x-9698               b                                            1/1     Running   0          4m45s
netpol-x-9698               c                                            1/1     Running   0          4m45s
netpol-x-9703               a                                            1/1     Running   0          21m
netpol-x-9703               b                                            1/1     Running   0          21m
netpol-x-9703               c                                            1/1     Running   0          21m
netpol-x-9720               a                                            1/1     Running   0          21m
netpol-x-9720               b                                            1/1     Running   0          21m
netpol-x-9720               c                                            1/1     Running   0          21m
netpol-x-9740               a                                            2/2     Running   0          21m
netpol-x-9740               b                                            2/2     Running   0          21m
netpol-x-9740               c                                            2/2     Running   0          21m
netpol-y-1071               a                                            1/1     Running   0          21m
netpol-y-1071               b                                            1/1     Running   0          21m
netpol-y-1071               c                                            1/1     Running   0          21m
netpol-y-1429               a                                            1/1     Running   0          21m
netpol-y-1429               b                                            1/1     Running   0          21m
netpol-y-1429               c                                            1/1     Running   0          21m
netpol-y-1538               a                                            1/1     Running   0          21m
netpol-y-1538               b                                            1/1     Running   0          21m
netpol-y-1538               c                                            1/1     Running   0          21m
netpol-y-1543               a                                            0/1     Pending   0          4m21s
netpol-y-1543               b                                            0/1     Pending   0          4m21s
netpol-y-1543               c                                            0/1     Pending   0          4m21s
netpol-y-1546               a                                            1/1     Running   0          21m
netpol-y-1546               b                                            1/1     Running   0          21m
netpol-y-1546               c                                            1/1     Running   0          21m
netpol-y-1926               a                                            1/1     Running   0          21m
netpol-y-1926               b                                            1/1     Running   0          21m
netpol-y-1926               c                                            1/1     Running   0          21m
netpol-y-2789               a                                            2/2     Running   0          14m
netpol-y-2789               b                                            2/2     Running   0          14m
netpol-y-2789               c                                            2/2     Running   0          14m
netpol-y-312                a                                            2/2     Running   0          21m
netpol-y-312                b                                            2/2     Running   0          21m
netpol-y-312                c                                            2/2     Running   0          21m
netpol-y-3241               a                                            1/1     Running   0          21m
netpol-y-3241               b                                            1/1     Running   0          21m
netpol-y-3241               c                                            1/1     Running   0          21m
netpol-y-360                a                                            2/2     Running   0          21m
netpol-y-360                b                                            2/2     Running   0          21m
netpol-y-360                c                                            2/2     Running   0          21m
netpol-y-4205               a                                            1/1     Running   0          21m
netpol-y-4205               b                                            1/1     Running   0          21m
netpol-y-4205               c                                            1/1     Running   0          21m
netpol-y-4729               a                                            1/1     Running   0          14m
netpol-y-4729               b                                            1/1     Running   0          14m
netpol-y-4729               c                                            1/1     Running   0          14m
netpol-y-4784               a                                            1/1     Running   0          14m
netpol-y-4784               b                                            1/1     Running   0          14m
netpol-y-4784               c                                            1/1     Running   0          14m
netpol-y-5285               a                                            1/1     Running   0          21m
netpol-y-5285               b                                            1/1     Running   0          21m
netpol-y-5285               c                                            1/1     Running   0          21m
netpol-y-5629               a                                            1/1     Running   0          21m
netpol-y-5629               b                                            1/1     Running   0          21m
netpol-y-5629               c                                            1/1     Running   0          21m
netpol-y-5641               a                                            1/1     Running   0          21m
netpol-y-5641               b                                            1/1     Running   0          21m
netpol-y-5641               c                                            1/1     Running   0          21m
netpol-y-684                a                                            1/1     Running   0          4m45s
netpol-y-684                b                                            1/1     Running   0          4m45s
netpol-y-684                c                                            1/1     Running   0          4m45s
netpol-y-723                a                                            2/2     Running   0          21m
netpol-y-723                b                                            2/2     Running   0          21m
netpol-y-723                c                                            2/2     Running   0          21m
netpol-y-7848               a                                            1/1     Running   0          21m
netpol-y-7848               b                                            1/1     Running   0          21m
netpol-y-7848               c                                            1/1     Running   0          21m
netpol-y-8206               a                                            1/1     Running   0          21m
netpol-y-8206               b                                            1/1     Running   0          21m
netpol-y-8206               c                                            1/1     Running   0          21m
netpol-y-8463               a                                            1/1     Running   0          21m
netpol-y-8463               b                                            1/1     Running   0          21m
netpol-y-8463               c                                            1/1     Running   0          21m
netpol-y-8503               a                                            1/1     Running   0          21m
netpol-y-8503               b                                            1/1     Running   0          21m
netpol-y-8503               c                                            1/1     Running   0          21m
netpol-y-9532               a                                            1/1     Running   0          14m
netpol-y-9532               b                                            1/1     Running   0          14m
netpol-y-9532               c                                            1/1     Running   0          14m
netpol-z-1400               a                                            1/1     Running   0          21m
netpol-z-1400               b                                            1/1     Running   0          21m
netpol-z-1400               c                                            1/1     Running   0          21m
netpol-z-1454               a                                            1/1     Running   0          21m
netpol-z-1454               b                                            1/1     Running   0          21m
netpol-z-1454               c                                            1/1     Running   0          21m
netpol-z-2424               a                                            1/1     Running   0          21m
netpol-z-2424               b                                            1/1     Running   0          21m
netpol-z-2424               c                                            1/1     Running   0          21m
netpol-z-2503               a                                            2/2     Running   0          21m
netpol-z-2503               b                                            2/2     Running   0          21m
netpol-z-2503               c                                            2/2     Running   0          21m
netpol-z-3266               a                                            1/1     Running   0          14m
netpol-z-3266               b                                            1/1     Running   0          14m
netpol-z-3266               c                                            1/1     Running   0          14m
netpol-z-35                 a                                            1/1     Running   0          14m
netpol-z-35                 b                                            1/1     Running   0          14m
netpol-z-35                 c                                            1/1     Running   0          14m
netpol-z-3715               a                                            1/1     Running   0          21m
netpol-z-3715               b                                            1/1     Running   0          21m
netpol-z-3715               c                                            1/1     Running   0          21m
netpol-z-4163               a                                            1/1     Running   0          21m
netpol-z-4163               b                                            1/1     Running   0          21m
netpol-z-4163               c                                            1/1     Running   0          21m
netpol-z-4468               a                                            1/1     Running   0          21m
netpol-z-4468               b                                            1/1     Running   0          21m
netpol-z-4468               c                                            1/1     Running   0          21m
netpol-z-4922               a                                            1/1     Running   0          21m
netpol-z-4922               b                                            1/1     Running   0          21m
netpol-z-4922               c                                            1/1     Running   0          21m
netpol-z-5048               a                                            1/1     Running   0          21m
netpol-z-5048               b                                            1/1     Running   0          21m
netpol-z-5048               c                                            1/1     Running   0          21m
netpol-z-5058               a                                            0/1     Pending   0          4m21s
netpol-z-5058               b                                            0/1     Pending   0          4m21s
netpol-z-5058               c                                            0/1     Pending   0          4m21s
netpol-z-5115               a                                            1/1     Running   0          21m
netpol-z-5115               b                                            1/1     Running   0          21m
netpol-z-5115               c                                            1/1     Running   0          21m
netpol-z-609                a                                            1/1     Running   0          21m
netpol-z-609                b                                            1/1     Running   0          21m
netpol-z-609                c                                            1/1     Running   0          21m
netpol-z-6133               a                                            1/1     Running   0          4m45s
netpol-z-6133               b                                            1/1     Running   0          4m45s
netpol-z-6133               c                                            0/1     Pending   0          4m45s
netpol-z-629                a                                            1/1     Running   0          21m
netpol-z-629                b                                            1/1     Running   0          21m
netpol-z-629                c                                            1/1     Running   0          21m
netpol-z-6417               a                                            1/1     Running   0          21m
netpol-z-6417               b                                            1/1     Running   0          21m
netpol-z-6417               c                                            1/1     Running   0          21m
netpol-z-6679               a                                            1/1     Running   0          21m
netpol-z-6679               b                                            1/1     Running   0          21m
netpol-z-6679               c                                            1/1     Running   0          21m
netpol-z-734                a                                            1/1     Running   0          14m
netpol-z-734                b                                            1/1     Running   0          14m
netpol-z-734                c                                            1/1     Running   0          14m
netpol-z-7470               a                                            1/1     Running   0          21m
netpol-z-7470               b                                            1/1     Running   0          21m
netpol-z-7470               c                                            1/1     Running   0          21m
netpol-z-8364               a                                            2/2     Running   0          21m
netpol-z-8364               b                                            2/2     Running   0          21m
netpol-z-8364               c                                            2/2     Running   0          21m
netpol-z-9218               a                                            2/2     Running   0          14m
netpol-z-9218               b                                            2/2     Running   0          14m
netpol-z-9218               c                                            2/2     Running   0          14m
netpol-z-9957               a                                            2/2     Running   0          21m
netpol-z-9957               b                                            2/2     Running   0          21m
netpol-z-9957               c                                            2/2     Running   0          21m
udp-network-policy-x-3320   a                                            0/1     Pending   0          4m9s
udp-network-policy-x-3320   b                                            0/1     Pending   0          4m9s
udp-network-policy-x-3320   c                                            0/1     Pending   0          4m9s
udp-network-policy-x-783    a                                            1/1     Running   0          21m
udp-network-policy-x-783    b                                            1/1     Running   0          21m
udp-network-policy-x-783    c                                            1/1     Running   0          21m
udp-network-policy-y-3119   a                                            1/1     Running   0          21m
udp-network-policy-y-3119   b                                            1/1     Running   0          21m
udp-network-policy-y-3119   c                                            1/1     Running   0          21m
udp-network-policy-y-7524   a                                            0/1     Pending   0          4m9s
udp-network-policy-y-7524   b                                            0/1     Pending   0          4m9s
udp-network-policy-y-7524   c                                            0/1     Pending   0          4m9s
udp-network-policy-z-2850   a                                            0/1     Pending   0          4m9s
udp-network-policy-z-2850   b                                            0/1     Pending   0          4m9s
udp-network-policy-z-2850   c                                            0/1     Pending   0          4m9s
udp-network-policy-z-7800   a                                            1/1     Running   0          21m
udp-network-policy-z-7800   b                                            1/1     Running   0          21m
udp-network-policy-z-7800   c                                            1/1     Running   0          21m

```

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
it failed here too https://github.com/cilium/cilium/actions/runs/5382835799/jobs/9768795354?pr=26490, the problem is that some pods fails to be ready


> 2023-06-26T21:18:33.5839009Z     Warning  Unhealthy  5m17s (x4 over 9m17s)  kubelet            Readiness probe failed: command "/agnhost connect --protocol=tcp --timeout=1s 127.0.0.1:80" timed out
2023-06-26T21:18:33.5839797Z     Warning  Unhealthy  5m8s (x8 over 14m)     kubelet            Readiness probe failed: command "/agnhost connect --protocol=tcp --timeout=1s 127.0.0.1:81" timed out
2023-06-26T21:18:33.5840116Z 


that is surprising since the probe is exec inside the network namespace and connecting to localhost

@squeed how can this be possible?

**Comment by aojea** [comment]
1/1 success

**Comment by aojea** [comment]
failed to install cilium this time

> Error: Unable to install Cilium: timeout while waiting for status to become successful: context deadline exceeded

is that normal?

**Comment by joestringer** [comment]
> > Error: Unable to install Cilium: timeout while waiting for status to become successful: context deadline exceeded
> 
> is that normal?

Sometimes this is caused by a runtime issue in the agent. Given that there were some disruptive changes in the tree that required all PRs to be rebased, it's possible you just hit that issue. Usually when I see this, I dig into the cilium-agent logs to inspect what it's doing and why there's a delay.

**Review by joestringer — APPROVED** [review]
Changes LGTM, but I note that the CI job is failing.

I'm often confused by this, but will GitHub run the changes in this PR for the triggers in this workflow or do we have to merge it first in order to validate?

**Comment by aojea** [comment]
Don't merge if it fails, I need to narrow this down

**Comment by aojea** [comment]
trying to get a failure with debug logs enabled https://github.com/cilium/cilium/pull/26639

**Pull request closed without merging**
