### PR TITLE
[CI] set $HOME in parallel builds to avoid cache pollution

### PR DESCRIPTION
**Pull request by nebril**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9932)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
flaked on basic policy tls test

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Pull request merged**
