### PR TITLE
v1.15 Backports 2024-02-08

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #30443 (@brlbil)
 * [x] #30507 (@pippolo84) (reviewed by @sayboras)
 * [x] #30536 (@hemanthmalla)
 * [x] #30525 (@tklauser)
 * [x] #30520 (@julianwiedmann)
 * [x] #30496 (@giorio94)
 * [x] #30378 (@brlbil)
 * [x] #30368 (@christarazi)
 * [x] #30543 (@chaunceyjiang) (reviewed by @sayboras )
 * [x] #30321 (@giorio94) (reviewe by @sayboras)
 * [x] #30576 (@julianwiedmann)
 * [ ] #30612 (@gailsuccess)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30443 30507 30536 30525 30520 30496 30378 30368 30543 30321 30576 30612
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.15

**Comment by nbusseneau** [comment]
The expected `Conformance Gateway API` check is missing because it has been renamed in this PR to `Conformance Gateway API (ci-gateway-api)`.

All testing has passed, awaiting for reviews now.

**Review by tklauser — APPROVED** [review]
My change looks good, thanks Nicolas.

As you already noted, the required workflows will need to be updated to account for the renamed _Conformance Gateway API (ci-gateway-api)_ workflow.

**Review by julianwiedmann — APPROVED** [review]

**Review by brlbil — APPROVED** [review]

**Comment by nbusseneau** [comment]
This should be ready to merge as soon as reviews are in.

**Review by hemanthmalla — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
LGTM :heavy_check_mark:

**Review by sayboras — APPROVED** [review]
LGTM for https://github.com/cilium/cilium/pull/30507 as Fabio is on leave.

**Comment by sayboras** [comment]
Most of the reviews are in, marking this ready to merge.

**Pull request merged**
