### PR TITLE
Install Cilium in kube-system on GKE

### PR DESCRIPTION
**Pull request by pchaigno**
Cilium on GKE is coming back home!

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Review by twpayne — COMMENTED** [review]
LGTM - assuming the tests pass 🎉

**Review by christarazi — APPROVED** [review]

**Comment by pchaigno** [comment]
test-gke

**Review by aanm — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Review by qmonnet — APPROVED** [review]

**Comment by pchaigno** [comment]
test-gke

**Comment by pchaigno** [comment]
All team reviews are covered and CI builds are passing. I think this is ready to merge.

**Comment by pchaigno** [comment]
Marking for backports into v1.9.

**Pull request merged**
