### PR TITLE
envoy: Use envoy image with Istio v1.1 support.

### LINKED ISSUE #7463: proxy: Bump Istio dependency to v1.1.0 for Cilium 1.5
- [ ] Bump Envoy dependency to the same SHA Istio is using
- [ ] Update Istio dependency to v1.1.0
- [ ] Update Istio GSG to match the new version

### PR DESCRIPTION
**Pull request by jrajahalme**
Update cilium/proxy dependencies to Envoy with Istio v1.1.1 filters.

This is a required prerequisite to test a new Envoy image before important bug fixes are available.

Go deps for cilium/envoy generated protobufs are updated to the same
SHA as cilium-envoy, which also requires bumping go protobuf
dependency to v1.3.

Istio sidecar proxy image has not been updated yet, and the Istio GSG still refers to Istio v1.0.2. Work to update those to Istio 1.1 is to be done later.

TODO:
- [ ] Merge cilium/proxy branch `pr/istio-v1.1.0` into master this PR passes CI, and before this PR is merged!

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
Fixes: #7463

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7468)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-flannel (failed to download VMs)

**Comment by aanm** [comment]
test-flannel

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by tgraf** [comment]
Tests passed, would love to have this so we can announce Istio 1.1 support in 1.5

**Comment by jrajahalme** [comment]
@tgraf Additional work is still needed on creating the Istio images and making sure the GSG works, but yes, this is the first step to that direction we need to take.

**Comment by jrajahalme** [comment]
I'll update this once more Envoy fixes land in.

**Comment by jrajahalme** [comment]
#7602 superceded this and is already merged. Took a bit simpler approach with that, skipping the Go API changes as the protobufs are still compatible. Will refresh this later, but this is no longer a release blocker.

**Comment by ianvernon** [comment]
Superseded by Istio 1.1.2 work.

**Pull request closed without merging**
