### PR TITLE
Bump StateDB to v0.3 with range-funcs

### PR DESCRIPTION
**Pull request by joamaki**
This bumps StateDB to v0.3.0 which brings in the `iter.Seq2` based API: https://github.com/cilium/statedb/pull/40.

Before:
```
  iter := tbl.All(db.ReadTxn())
  for obj, _, ok := iter.Next(); ok; obj, _, ok = iter.Next() {
    ...
  }
```

Now:
```
  for obj := range tbl.All(db.ReadTxn()) { 
    ... 
  }
```

### CODE REVIEW

**Review by dylandreimerink — APPROVED** [review]
Checked all files owned by teams I am on, LGTM

**Review by tommyp1ckles — APPROVED** [review]
nice! @cilium/sig-k8s changes lgtm.

**Review by tklauser — APPROVED** [review]

**Pull request merged**
