### PR TITLE
Add protoc-gen-gotag plugin to builder image

### PR DESCRIPTION
**Pull request by marqc**
Please ensure your pull request adheres to the following guidelines:

- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.

Adds a protoc-gen-gotag plugin to generate yaml annotations in the generated proto as discussed in https://github.com/cilium/cilium/pull/28873#discussion_r1377689955

cc: @chancez @glibsm 

```release-note
Adds a protoc-gen-gotag plugin
```

### CODE REVIEW

**Review by chancez — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Comment by christarazi** [comment]
I see that the commit in https://github.com/cilium/cilium/pull/28944 is the same as the commit here? Is this intended?

**Comment by marqc** [comment]
> I see that the commit in #28944 is the same as the commit here? Is this intended?

@christarazi I'm not sure if changing the build image can be submitted together with changes using it. That's why this commit is included in both PRs. Once the other PR gets merged this one will be obsolete. If this PR is merged first, the other one will only contain changes after using this build image.

**Comment by christarazi** [comment]
> I'm not sure if changing the build image can be submitted together with changes using it.

I am not aware of any problems with the build image being submitted together. I think we should probably close this PR to avoid confusion.

**Comment by christarazi** [comment]
Oh I see Chance gave [details](https://github.com/cilium/cilium/pull/28944#issuecomment-1791064155) on this and I don't want to be giving conflicting feedback, so please ignore my message above.

**Review by bimmlerd — APPROVED** [review]
fine by me, but will similarly conflict with https://github.com/cilium/cilium/pull/28945; let's just see who gets in first.

**Comment by chancez** [comment]
> Oh I see Chance gave [details](https://github.com/cilium/cilium/pull/28944#issuecomment-1791064155) on this and I don't want to be giving conflicting feedback, so please ignore my message above.

I also had no idea we could do a single PR that modified the base image 😮

**Comment by marqc** [comment]
> fine by me, but will similarly conflict with #28945; let's just see who gets in first.

Rebased

**Comment by marqc** [comment]
@julianwiedmann rebased, can you trigger the github action to build the image, so I can update definitions

**Comment by rolinh** [comment]
> can you trigger the github action to build the image

Just did it.

**Comment by marqc** [comment]
> > can you trigger the github action to build the image
> 
> Just did it.

thanks, image references updated

**Comment by marqc** [comment]
I just realized that names generated with this plugin are inconsitent with json tags. This would make a mess in the API. I will close this and instead I will use different YAML parser that works with json tags  `sigs.k8s.io/yaml`

**Pull request closed without merging**
