### PR TITLE
[v1.12-backport] Introduce fromEgressProxyRule

### PR DESCRIPTION
**Pull request by jschwinger233**
- [x] https://github.com/cilium/cilium/pull/31923

### CODE REVIEW

**Comment by jschwinger233** [comment]
/test-backport-1.12

**Comment by jschwinger233** [comment]
/test-1.16-4.9

**Comment by julianwiedmann** [comment]
This is needed to enable smooth downgrades from v1.13, right? Is it enough to merge the PR, or would the v1.13 CI also require a fresh v1.12 release? (which we most likely won't do, as v1.12 is EOL).

**Comment by jschwinger233** [comment]
@julianwiedmann I was thinking the same. If there won't be a 1.12 release, how about specifying downgrade image tag like https://github.com/cilium/cilium/pull/31955/files#diff-07b1303f71b74ecfe10ad34472da7c7e9b79ac9274fd93fe833ecc1551898473 in 1.13 test-ipsec-upgrade.yaml? Or any way more elegant to let 1.13 upgrade test use the 1.12 tip?

**Comment by julianwiedmann** [comment]
> @julianwiedmann I was thinking the same. If there won't be a 1.12 release, how about specifying downgrade image tag like https://github.com/cilium/cilium/pull/31955/files#diff-07b1303f71b74ecfe10ad34472da7c7e9b79ac9274fd93fe833ecc1551898473 in 1.13 test-ipsec-upgrade.yaml? Or any way more elegant to let 1.13 upgrade test use the 1.12 tip?

My first thought was to make the Egress-Proxy support on v1.13 an opt-in feature. Because in the end users will face the same problem - they can't downgrade to a fixed v1.12.

**Comment by jschwinger233** [comment]
> Because users will face the same problem - they can't downgrade to a fixed v1.12.

For 1.13 -> 1.12 downgrade, we can provide downgrade guide with several simple command in the next 1.13 release notes. (Hope users are reading release notes....

**Comment by jschwinger233** [comment]
Close due to won't do.

1.12 is EOL so it doesn't make sense to release another 1.12.X.

I'll take care of downgrade issue by manually adding necessary commands in ci-ipsec-upgrade.yaml.

**Comment by jschwinger233** [comment]
/test-backport-1.12

**Pull request closed without merging**
