### PR TITLE
update golang to 1.18.10

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Review by nbusseneau — APPROVED** [review]

**Comment by aanm** [comment]
/test-backport-1.12

**Review by michi-covalent — APPROVED** [review]
latest and greatest

**Comment by michi-covalent** [comment]
/test-1.17-4.9

**Comment by michi-covalent** [comment]
/test-1.23-4.9

**Pull request merged**
