### PR TITLE
v1.16 Backports 2024-07-15

### PR DESCRIPTION
**Pull request by giorio94**
* [x] #33426 (@jschwinger233) :warning: resolved conflicts
    * :information_source: Skipped 89edd94812d3, as codeowners changes are not propagated to stable branches. 
 * [x] #33621 (@brb)
 * [x] #33626 (@giorio94)
 * [ ] #33680 (@joestringer)
 * [ ] #33655 (@aditighag)
 * [ ] #33634 (@chaunceyjiang)
 * [ ] #33608 (@jrajahalme) :warning: resolved conflicts
    * :information_source: Resolved minor conflict accepting the incoming hunk.
 * [x] #33694 (@marseel)
 * [x] #33683 (@sayboras)
 * [x] ~~#33686 (@julianwiedmann)~~
    * :x: Dropped, as causing the E2E upgrade/downgrade workflow to fail.
 * [x] #33592 (@gandro)
 * [ ] #33708 (@Mais316)
 * [ ] #33598 (@archerwu9425)
 * [x] #33637 (@giorio94)
 * [ ] #33699 (@EricMountain)
 * [x] #33679 (@giorio94)
 * [x] #33725 (@brb)
 * [ ] #33640 (@chaunceyjiang)
 * [ ] #33416 (@tommyp1ckles) :warning: resolved conflicts
    * :information_source: Skipped 79084b64197e, as codeowners changes are not propagated to stable branches. 
 * [ ] #33698 (@youngnick)
 * [ ] #33616 (@mrproliu)
 * [x] #33764 (@julianwiedmann) :warning: resolved conflicts
    * :warning: Hit minor conflict due to 26085bd85aaa not being present in the v1.16 branch. Resolved accepting the current hunk, and manually changing `goto encrypt` to `goto overlay_encrypt`.
 * [x] #33506 (@pippolo84)
 * [ ] #33709 (@aditighag)
 * [x] #33769 (@pchaigno)
 * [x] #33735 (@giorio94)
 * [ ] #33306 (@skmatti)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33426 33621 33626 33680 33655 33634 33608 33694 33683 33592 33708 33598 33637 33699 33679 33725 33640 33416 33698 33616 33764 33506 33709 33769 33735 33306
```

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Comment by giorio94** [comment]
Dropped #33283, as already included in the v1.16 branch (/cc @bimmlerd)

**Comment by giorio94** [comment]
/test-backport-1.16

**Review by marseel — APPROVED** [review]

**Review by jschwinger233 — APPROVED** [review]

**Review by brb — APPROVED** [review]
LGTM, thanks!

**Review by pippolo84 — APPROVED** [review]
My PR looks good, thanks!

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commit

**Comment by giorio94** [comment]
The Cilium E2E Upgrade workflow is failing with Cilium agents crashing due to:

```
2024-07-15T08:27:05.720153693Z time="2024-07-15T08:27:05Z" level=fatal msg="IPv6 BPF masquerade is not supported along with the host firewall." subsys=daemon
```

@julianwiedmann I guess we'll need to wait one more release for https://github.com/cilium/cilium/pull/33804/commits/811c840bd3db84e885d47fd0a31af5124fd39751 (or explicitly disable host firewall in the relevant upgrade/downgrade tests).

**Comment by julianwiedmann** [comment]
> The Cilium E2E Upgrade workflow is failing with Cilium agents crashing due to:
> 
> ```
> 2024-07-15T08:27:05.720153693Z time="2024-07-15T08:27:05Z" level=fatal msg="IPv6 BPF masquerade is not supported along with the host firewall." subsys=daemon
> ```
> 
> @julianwiedmann I guess we'll need to wait one more release for [811c840](https://github.com/cilium/cilium/commit/811c840bd3db84e885d47fd0a31af5124fd39751) (or explicitly disable host firewall in the relevant upgrade/downgrade tests).

ugh yes. Then let's definitely drop it for now - sorry, should have anticipated this :/.

**Review by pchaigno — APPROVED** [review]

**Comment by giorio94** [comment]
> > The Cilium E2E Upgrade workflow is failing with Cilium agents crashing due to:
> > ```
> > 2024-07-15T08:27:05.720153693Z time="2024-07-15T08:27:05Z" level=fatal msg="IPv6 BPF masquerade is not supported along with the host firewall." subsys=daemon
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @julianwiedmann I guess we'll need to wait one more release for [811c840](https://github.com/cilium/cilium/commit/811c840bd3db84e885d47fd0a31af5124fd39751) (or explicitly disable host firewall in the relevant upgrade/downgrade tests).
> 
> ugh yes. Then let's definitely drop it for now - sorry, should have anticipated this :/.

No problem, dropped.

**Comment by giorio94** [comment]
/test-backport-1.16

**Pull request merged**
