### PR TITLE
cilium preflight identity migration

### PR DESCRIPTION
**Pull request by raybejjani**
As a convenience, we want to support migrating kvstore-backed identities to CRD-backed ones while minimizing connection loss. `cilium preflight migrate-identity` allows this by migrating the identities from the kvstore and allocating them with the same ID in the CRDs. In case the ID is already taken, it will allocate a new ID. All this is logged so the operator can decide what to do.

I've also fixed some typos in the docs.

Note: I still need to fully test the instructions with our helm yaml. I may need to add more instructions on how to generate the kvstore config along with the CRD one within the preflight pods.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8807)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-docs-please

**Comment by raybejjani** [comment]
I just noticed an already-existing setup function. I'll use that.

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-docs

**Comment by raybejjani** [comment]
All sorted. I also fixed the hound warnings

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by jrajahalme** [comment]
@raybejjani Do we support migration to the other direction? E.g., user needs to scale a CRD identity based cluster up to a size not feasible for the CDR backed identities, so the identities would need to be migrated to a kv-store? If we may need something like this, then maybe the command name should reflect the direction of the migration?

**Review by jrajahalme — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
> Do we support migration to the other direction? E.g., user needs to scale a CRD identity based cluster up to a size not feasible for the CDR backed identities, so the identities would need to be migrated to a kv-store? If we may need something like this, then maybe the command name should reflect the direction of the migration?

In the Monday meeting, we concluded that only one direction is required. For a rollback, we require etcd-operator to keep running to support immediate rollback.

**Pull request merged**
