### PR TITLE
ci: pass race-detection env vars to vagrant boxes

### PR DESCRIPTION
**Pull request by nebril**

### CODE REVIEW

**Comment by nebril** [comment]
test-race-runtime

**Comment by nebril** [comment]
test-race-upstream

**Comment by nebril** [comment]
test-race-upstream-k8s

**Review by aanm — APPROVED** [review]

**Comment by nebril** [comment]
test-race-runtime

**Comment by nebril** [comment]
test-race-runtime

**Comment by nebril** [comment]
test-race-upstream-k8s

**Comment by nebril** [comment]
test-race-upstream-k8s

**Comment by nebril** [comment]
test-race-upstream-k8s

**Comment by nebril** [comment]
test-race-upstream-k8s

**Comment by nebril** [comment]
test-net-next

**Review by christarazi — APPROVED** [review]

**Comment by nebril** [comment]
test-race-runtime

**Review by aanm — APPROVED** [review]

**Pull request merged**
