### PR TITLE
Aspsk/backports to v1.10

### PR DESCRIPTION
**Pull request by aspsk**
Backport of the following PRs:

* https://github.com/cilium/cilium/pull/20711 (@aspsk)
* https://github.com/cilium/cilium/pull/20859 (@aspsk)

### CODE REVIEW

**Comment by aspsk** [comment]
/test-backport-1.10

**Comment by aspsk** [comment]
> release

I think no

**Comment by gandro** [comment]
> > release
> 
> I think no

Turns out the release was not triggered by this PR, but by the previous one: https://github.com/cilium/cilium/pull/21484
 GitHub is confused because the branch is the same. The failed deployment on this PR can be safely ignored.

**Comment by aspsk** [comment]
/test-backport-1.10

**Review by sayboras — APPROVED** [review]
LGTM :100:

**Pull request merged**
