### PR TITLE
feat: Cloudprovider Policy support via cilium config

### LINKED ISSUE #26135: CFP: Egress Policy to restrict traffic to specific set without blocking all
## Cilium Feature Proposal
        
Thanks for taking time to make a feature request for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your feature request related to a problem?**

If so, please describe the problem

**Describe the feature you'd like**
The current implementation of Cilium lacks a mechanism to restrict egress traffic to specific endpoints without blocking all traffic. When the egress policy is enabled for an endpoint, it effectively goes into a default deny state for egress traffic. Even if an "allow-all" policy is enforced to counteract this behavior, it can introduce conflicts when other network policies are defined with restricted access. This feature is essential for cloud provider to enforce network policy at cluster level to restrict access to infrastructure components. This proposal aims to solve this issue and enhance cilium functionality.

Include any specific requirements you need

**(Optional) Describe your proposed solution**

Proposal Doc:  https://docs.google.com/document/d/1ZtHn4ZHtNFD-z5vQl0AckgCb14GSNPGDMzZchgRo1uI/edit?usp=sharing

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

### PR DESCRIPTION
**Pull request by tamilmani1989**
Introducing a new cilium config field `egress-deny-tuples` to allow cloudprovider to block certain traffic without denying rest of traffic.The deny tuples are converted to Cilium Egress Deny rules and enforced to all cilium endpoints without default deny. So only traffic to endpoints configured in deny-tuples would be blocked while rest of traffic allowed. If any of other NetworkPolicy or CiliumNetworkPolicy is enforced for an endpoint, then it goes to default deny as usual. This change would not regress any exisiting NetworkPolicy behaviour.

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #26135 
CFP: https://github.com/cilium/design-cfps/pull/12

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Comment by squeed** [comment]
I've asked @nathanjsweet to take a look at the policy logic changes, since he knows that code the best.

I'll start to think about how this is all plumbed together.

In the mean time, @tamilmani1989, would you mind splitting this in to a few commits? There should be one commit for the "front-end" (e.g. policy ingestion via command line), and at least one for the "non-default-deny" mode for policies.

**Comment by tamilmani1989** [comment]
@squeed / @nathanjsweet i split into different commits. there were some failures due to that and i hope it will go away once i squash back the commits.. would be great if you take a look at PR and share your suggestions

**Comment by squeed** [comment]
Hi there, @tamilmani1989.

This https://github.com/cilium/cilium/pull/30572 is fortunately timed :-). There are some other users that would like similar logic added to the core of the policy engine. After looking at your PR, I realized it missed a few special cases in calculating policy defaults. So, I filed a PR that implements just the non-default-deny logic. Could you review that and see that it meets your needs?

I'm still mulling over the question of how to have a "stickier" policy enforcement. This PR creates a policy type that is enforced, even if policy is disabled. We need to proceed carefully here.

At the end of the day, administrators have administrative control over their clusters. They can create HostNetwork pods, change Cilium images, etc. Even if we ignore a specific config-map key, there's many, many other ways to circumvent policy. How do you envision enforcing this?

If, however, we assume that administrators do not have the ability to write to the kube-system namespace, then it's not actually possible to disable policy. So, I'm not sure there's much value in a non-disable-able policy; if administrators can change Cilium ConfigMaps, then they can just remove the policy in question.

Now, I do think it would be nice to have statically-defined policies. If you would like to make a small controller (probably adding on to the work in https://github.com/cilium/cilium/pull/30322 ) that watches a directory and applies any policies found in there, I would be 100% in favor. You could then build a custom image of Cilium, or deploy it with a ConfigMap that included these static policies.

Make sense? Happy to talk about this online if it would help.

**Comment by tamilmani1989** [comment]
Thanks @squeed for responding back. 

> At the end of the day, administrators have administrative control over their clusters. They can create HostNetwork pods, change Cilium images, etc. Even if we ignore a specific config-map key, there's many, many other ways to circumvent policy. How do you envision enforcing this?

Cloud provider doesn't allow changing the config map or cilium image. It will get reconciled back to original config/image. Cluster admin would not have control over it. 

Today only k8s network policies are supported and if we go by your PR we have to start supporting cnp.

It would be good if we can discuss this over a call. I will reach out to you in slack if that's ok.

**Comment by joestringer** [comment]
> Now, I do think it would be nice to have statically-defined policies. If you would like to make a small controller (probably adding on to the work in https://github.com/cilium/cilium/pull/30322 ) that watches a directory and applies any policies found in there, I would be 100% in favor. You could then build a custom image of Cilium, or deploy it with a ConfigMap that included these static policies.

Incidentally, I do think that this solves a slightly more general problem than the current proposal by abstracting the solution space further, and I think that provides some useful properties. In conjunction with the feature in #30572 this would solve the problem space in a way that is more supportable long-term IMO. Rather than providing a way for users to specify individual rules on the commandline in a relatively static and limited way, being able to pick up YAML/JSON specifications from a directory would provide the full power of the policy engine without requiring us to think about how to expose and translate a new rule language for the new commandline flag.

I think we could do this even by supporting the existing policy formats KNP/CNP/CCNP, as long as we ensure that they are somehow namespaced separately from k8s resources. That is to say, if someone loads these policies from a directory, there is no way for someone to also create a network policy resource in k8s that modifies or alters the policies loaded from disk. If you look at `cilium-dbg policy add ...` and the json policy examples under `examples/`, you may get a sense for the ability to do this already. The format is effectively the same as the CNP resources in that case, and done in `cilium-dbg` rather than `cilium-agent`, but the same principle applies for Casey's proposal.

**Review by nathanjsweet — COMMENTED** [review]
Other folks are working on Default Allow (aka "non-default-deny"). Once that work gets merged then I think we can revisit this. Does that sound fair? @tamilmani1989

**Pull request closed without merging**
