### PR TITLE
update alpine base image to v3.18.4

### PR DESCRIPTION
**Pull request by bmelbourne**
Update Alpine container base image to v3.18.4.

```release-note
Update Alpine container base image to v3.18.4.
```

### CODE REVIEW

**Comment by aanm** [comment]
@markpash @lambdanis can you take a look? Thank you

**Review by markpash — APPROVED** [review]

**Comment by lambdanis** [comment]
Hey @bmelbourne, thanks for opening the PR. I see that `examples/kubernetes-memcached/memcd-sw-app.yaml` is used in documentation here: https://docs.cilium.io/en/latest/security/memcached/. Have you verified that the instructions on this page work with the new version?

**Comment by bmelbourne** [comment]
> Hey @bmelbourne, thanks for opening the PR. I see that `examples/kubernetes-memcached/memcd-sw-app.yaml` is used in documentation here: https://docs.cilium.io/en/latest/security/memcached/. Have you verified that the instructions on this page work with the new version?

@lambdanis 
I'll take a look and respond in the near future.

**Comment by lmb** [comment]
Converted to draft for now. Please mark as ready once you've had time to verify the instructions work.

**Pull request closed without merging**
