### PR TITLE
daemon: Remove stale maps only after restoring all endpoints

### PR DESCRIPTION
**Pull request by brb**
Previously, stale and disabled BPF maps could have been removed while not all endpoints had been restored.

The b75ec9b4 ("datapath: Simplify map name handling") commit changed the format of a local BPF map name which made endpoint maps considered as stale, and thus to be removed during the bootstrap of cilium daemon.

Having the race and the change combined, this led to an interesting bug when an endpoint tail call map (`cilium_calls_${ENDPOINT_ID}`) was removed due to the local name change before the new endpoint program has been compiled and loaded. So, the datapath BPF code of the endpoint was failing with `DROP_MISSED_TAIL_CALL` which led to some packets being dropped during an upgrade from <v1.5 to 1.5 (reported by a user).

An example of such bug:

```
2019-05-10T14:28:39.178985386Z level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_calls_1201 subsys=datapath-maps
2019-05-10T14:28:39.179951876Z level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_ep_config_1201 subsys=datapath-maps
2019-05-10T14:28:39.180742219Z level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_policy_1201 subsys=datapath-maps
<..>
2019-05-10T14:28:39.681887394Z level=debug msg="Finished writing ELF" error="<nil>" new-elf-path=1201_next/bpf_lxc.o subsys=elf template-path=/var/run/cilium/state/templates/4bfc47bec0776fc129e1ac0dcbca88dc51850e87/bpf_lxc.o
```

This commit fixes the race by making the removal of the stale maps to wait until all endpoints have been restored.

---

I'm not sure whether it's a good idea to block the whole bootstrapping process while waiting for endpoints to be restored. Alternatively, we could just spawn a goroutine which could call `maps.CollectStaleMapGarbage()`.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7982)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by ianvernon** [comment]
VM downloading failed:
```
[K    k8s1-1.14: Progress: 99% (Rate: 3350k/s, Estimated time remaining: 0:00:02)
[KThe box failed to unpackage properly. Please verify that the box
16:38:52  file you're trying to add is not corrupted and that enough disk space
16:38:52  is available and then try again.
16:38:52  The output from attempting to unpackage (if any):
16:38:52  
16:38:52  bsdtar: Error opening archive: Failed to open '/root/.vagrant.d/tmp/box2867efb70d9120ff21731e1c018ec7b6a66137fd'
```

Link: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12235/

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by ianvernon** [comment]
Failure is a bit strange - https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12237/testReport/junit/(root)/Suite-runtime/RuntimeFQDNPolicies_DNS_proxy_policy_works_if_Cilium_stops/

**Comment by ianvernon** [comment]
test-me-please

**Comment by brb** [comment]
VM image download timeout.

**Comment by brb** [comment]
test-me-please

**Comment by ianvernon** [comment]
This would affect the downgrade case as well, right? If we rename maps in v1.5 and downgrade to v1.4, then we would hit this issue as well? If so we should backport to v1.4.

**Comment by tgraf** [comment]
> This would affect the downgrade case as well, right? If we rename maps in v1.5 and downgrade to v1.4, then we would hit this issue as well? If so we should backport to v1.4.

Yes, but we should be able to backport as stale map removal was already present in 1.4 and earlier.

**Review by borkmann — APPROVED** [review]

**Comment by borkmann** [comment]
One more note that is relevant here (which was not in the commit msg): while other maps like hash tables etc are still retained in the kernel and can be accessed normally by the prog, tail call maps cannot. This is due to breaking dependency chain to avoid cyclic dependencies where they otherwise could never be released. So once the last user space reference is gone (pinned file or fd), they flush all the slots upon removal which happened here with the missed tail call.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Finally got a build without VM booting timing out :)

**Comment by brb** [comment]
Hmm, `Suite-runtime.RuntimeFQDNPolicies DNS proxy policy works if Cilium stops` failed for the second time. I'm going to investigate this.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
The test case from `Suite-runtime.RuntimeFQDNPolicies DNS proxy policy works if Cilium stops` failed because of
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:340
Docker containers mistmach with Cilium Endpoints
Expected
    <*errors.errorString | 0xc420a07140>: {
        s: "ContainerID  is not present in the endpoint list",
    }
to be nil
```

which is triggered by `ExpectDockerContainersMatchCiliumEndpoints` (OT: took me awhile (not the first time) to find which exact test method triggered a failure; maybe we can improve test output?).

https://github.com/cilium/cilium/blob/6733df9987f2332973984435d762bf5504d088cb/test/helpers/cilium.go#L662-L681

The output of the test executor running the method ^^:

```
time="2019-05-10T23:16:28Z" level=error msg="write ^C error: EOF"
time="2019-05-10T23:16:28Z" level=debug msg="running command: docker network inspect cilium-net | jq -r '.[].Containers|keys |.[]'"
cmd: "docker network inspect cilium-net | jq -r '.[].Containers|keys |.[]'" exitCode: 0 duration: 31.434992ms stdout:
0ba8800b83b2d1b0159f9af235b2308bcc92f5fefc8a362454d27269d9106bbb
2fec5fbfb757666cd757fc0e211cf46941c743f02a19283fb63c29a86268de0d
a76fc45bf9f8f396fe7bb54662c50838c6617d87ae78c4673fb074bcf74faa51
bf8fe284b184c4ec567fb1b490d74028d2726defcbcc50fa395aedf8668bd9b2
d084076f8d1c09c1f19260c804e6351470410e256a8592b256ec471c4d3188de
d7c0b00b36e0597a5008db105cc8685772d1231cbfcad4638699cb6325bde0fa
d93f4da8c72d2ead18b8f9ba16da4c96e3731a3c0862be3bfc4b65c00aad3c39
dc106bf7bc58e47d3f1ef7121ae2d942b653f66df315094a5e2eaedcd58a9dbc

time="2019-05-10T23:16:28Z" level=debug msg="running command: sudo cilium endpoint list -o jsonpath='{range[*]}{.status.external-identifiers.container-id}{\"=\"}{.id}{\"\\n\"}{end}'"
time="2019-05-10T23:16:28Z" level=error msg="write ^C error: EOF"
time="2019-05-10T23:16:28Z" level=error msg="write ^C error: EOF"
cmd: "sudo cilium endpoint list -o jsonpath='{range[*]}{.status.external-identifiers.container-id}{\"=\"}{.id}{\"\\n\"}{end}'" exitCode: 0 duration: 61.784627ms stdout:
2fec5fbfb757666cd757fc0e211cf46941c743f02a19283fb63c29a86268de0d=237
d7c0b00b36e0597a5008db105cc8685772d1231cbfcad4638699cb6325bde0fa=285
d084076f8d1c09c1f19260c804e6351470410e256a8592b256ec471c4d3188de=631
0ba8800b83b2d1b0159f9af235b2308bcc92f5fefc8a362454d27269d9106bbb=1136
dc106bf7bc58e47d3f1ef7121ae2d942b653f66df315094a5e2eaedcd58a9dbc=2449
d93f4da8c72d2ead18b8f9ba16da4c96e3731a3c0862be3bfc4b65c00aad3c39=3565
a76fc45bf9f8f396fe7bb54662c50838c6617d87ae78c4673fb074bcf74faa51=3880
bf8fe284b184c4ec567fb1b490d74028d2726defcbcc50fa395aedf8668bd9b2=4087

```

My guess is that `docker network inspect cilium-net | jq -r '.[].Containers|keys |.[]'` returned container IDs + an empty line which was considered as an `ContainerID`, thus it failed. Not sure why it fails only sometimes, but it could be related to those `level=error msg="write ^C error: EOF"` error messages which the executor output is full of.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
@borkmann Thanks for the note, appended to the commit message.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by joestringer** [comment]
> I'm not sure whether it's a good idea to block the whole bootstrapping process while waiting for endpoints to be restored. Alternatively, we could just spawn a goroutine which could call `maps.CollectStaleMapGarbage()`.

I think this would be safe to perform in a goroutine? The map sweeper logic basically fetches filepaths, derives the endpoint ID from them, then looks the endpoint up in the endpoint manager to confirm that it's live, and only remove the map if either the map name is stale or the endpoint doesn't exist (`deleteMapIfStale()`).

The question is then, how long could this last? The sweeping itself should be pretty quick, which is probably why we were okay with having it in the main thread until now. But the waiting for restore to complete? That looks like it's gated on the full regeneration of every endpoint, which is gated on getting identity, which is gated on the kvstore being available to allocate those identities... plus the potential 30s identity change grace period.... Seems like it's a bit too long, no?

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12261/testReport/junit/Suite-k8s-1/14/K8sChaosTest_Connectivity_demo_application_Endpoint_can_still_connect_while_Cilium_is_not_running/

Looks like etcd communication was in a bad state:

```
2019-05-13T09:39:30.865916013Z level=error msg="Unable to initialize local node. Retrying..." error="timeout while retrieving initial list of objects from kvstore" subsys=nodediscovery
2019-05-13T09:39:30.887162495Z level=fatal msg="Timeout while waiting for initial allocator state" subsys=allocator
```

Trying again!

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Infra is unstable:

```
Setting status of 1ba402d30a0f49e2c35faf237362a56d3db8c4e1 to FAILURE with url https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12268/ and message: 'Build finished. '
Using context: Cilium-Ginkgo-Tests
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.kohsuke.github.Requester.parse(Requester.java:615)
Caused: java.net.SocketTimeoutException: Read timed out
```

**Comment by ianvernon** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
@joestringer
 
> Seems like it's a bit too long, no?

Agreed. Do we want to keep the `bootstrapStats.cleanup` metric? If yes, then we will need to synchronize the metrics update.

**Comment by brb** [comment]
test-me-please

**Comment by joestringer** [comment]
> Agreed. Do we want to keep the bootstrapStats.cleanup metric? If yes, then we will need to synchronize the metrics update.

@brb Hmm, that seems kinda ugly to me. If this cleanup logic is being handled asynchronously, then do we really care about its effect (time impact) on bootstrap any more? I don't think so.

**Comment by brb** [comment]
@joestringer Sure regarding the ugliness. I was just concerned whether someone is actually interested in the cleanup time regardless of how the cleanup is being performed.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
PTAL - made the stale maps cleanup async.

**Review by aanm — APPROVED** [review]

**Comment by brb** [comment]
CI failed due to:
```
hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on jenkins-fixed-new-experimental-with-cache-0 failed. The channel is closing down or has closed down
```

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failed due to:
```
[2019-05-14T11:17:22.640Z] /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/machine.rb:606:in `write': No such file or directory @ rb_sysopen - /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.14-gopath/src/github.com/cilium/cilium/test/.vagrant/machines/k8s2-1.14/virtualbox/vagrant_cwd (Errno::ENOENT)
```

**Comment by brb** [comment]
test-me-please

**Pull request merged**
