### PR TITLE
v1.10 (focused backport) backports 2021-06-28

### PR DESCRIPTION
**Pull request by aditighag**
* #16259 -- kpr: Enable/fix Cilium socket based load balancing in different environments (@aditighag)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16259; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by aditighag** [comment]
test-backport-1.10

**Comment by aditighag** [comment]
test-backport-1.10

**Comment by aditighag** [comment]
test-backport-1.10

**Comment by aditighag** [comment]
test-backport-1.10

**Comment by aditighag** [comment]
test-backport-1.10

**Review by joestringer — APPROVED** [review]

**Comment by aditighag** [comment]
test-1.19-5.4

**Comment by aditighag** [comment]
test-1.19-5.4

**Comment by aditighag** [comment]
Considering the upstream PR mainly changed the cilium agent daemonset to fixe socket-based lb in certain scenarios, the relevant tests (K8sServices*) on net-next and 5.4 kernel have passed. Marking it as ready for merge. 

net-next nodeport failure -  #12511 (#14330).

4.9 failure - 
>Expected command: kubectl exec -n default xwing-6d75b9b56b-6rrwn -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://deathstar.default.svc.cluster.local/v1 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 6 
Err: exit status 6
Stdout:
 	 time-> DNS: '0.000000()', Connect: '0.000000',Transfer '0.000000', total '0.000000'
Stderr:
 	 command terminated with exit code 6

Looks like a similar flake that https://github.com/cilium/cilium/pull/16411 fixed. But we already check if kube-dns is up in this test. 
Dup of - #11002.

**Comment by aanm** [comment]
test-1.17-4.9

**Comment by aditighag** [comment]
test-1.17-4.9

**Comment by aditighag** [comment]
k8s-1.17-kernel-4.9 passed. Ready to merge.

**Comment by aditighag** [comment]
Jobs are stuck.

**Comment by aditighag** [comment]
test-1.16-netnext

**Comment by aditighag** [comment]
test-backport-1.10

**Comment by aditighag** [comment]
4.9 failure - 

>/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
connectivity-check pods are not ready after timeout
Expected
    <*errors.errorString | 0xc007229550>: {
        s: "timed out waiting for pods with filter  to be ready: 4m0s timeout expired",
    }
to be nil

**Pull request merged**
