### PR TITLE
docs: Add note about DNS-related policies on OpenShift 

### PR DESCRIPTION
**Pull request by twpayne**

### CODE REVIEW

**Review by qmonnet — COMMENTED** [review]
I think it would be worth referencing the YAML file from the note in the documentation? Otherwise I'm not sure that 1) users will find it and 2) we'll easily remember what this example was supposed to demonstrate.

**Comment by twpayne** [comment]
> I think it would be worth referencing the YAML file from the note in the documentation?

Agreed. Done with a tabs and a note.

**Review by qmonnet — APPROVED** [review]
The tab is a good idea. Looks good, thank you!

**Review by errordeveloper — APPROVED** [review]
Thanks a lot, well spotted!

**Pull request merged**
