### PR TITLE
v1.9 backports 2021-02-24

### PR DESCRIPTION
**Pull request by aditighag**
* #14993 -- Move Azure IPAM out of beta (@tgraf)
I had to resolve conflicts.
 * #14951 -- kpr: Make it possible to run bpf_sock on Kind (@brb)
 * #14943 -- helm: Fix and add missing podLabels (@Subreptivus)
I had to resolve conflicts.
Unable to backport the last commit - 
` Warning: No commit correlation found!    via cf933403d63fac743630511f40876070d3a83e71 ("Removed empty comment line from podLabels/Annotations Signed-off-by: Yurii Komar <IKOM@equinor.com>")`

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14993 14951 14943; do contrib/backporting/set-labels.py $pr done 1.9; done
```

Edit: This is superseded by  - https://github.com/cilium/cilium/pull/15104

### CODE REVIEW

**Comment by joestringer** [comment]
FYI for the last commit, I'm not sure why that comes up:

> Unable to backport the last commit -
> Warning: No commit correlation found! via cf933403d63fac743630511f40876070d3a83e71 ("Removed empty comment line from podLabels/Annotations Signed-off-by: Yurii Komar <IKOM@equinor.com>")

But you should be able to figure out the correct commit by using `git log --oneline upstream/master` and searching for the title. Looks like it's 40661dc32a56.

**Review by brb — APPROVED** [review]
:+1: for my changes, thanks.

**Comment by twpayne** [comment]
@aditighag #15104 fixes a few commits to get the CI pass (I think a couple of changes got missed in this PR).

You can see the diff by running:

    git remote add twpayne https://github.com/twpayne/cilium.git
    git fetch twpayne
    git diff aditighag/pr/v1.9-backport-2021-02-24..twpayne/pr/v1.9-backport-2021-02-24

Feel free to grab the changes to complete the backport.

**Comment by aditighag** [comment]
@twpayne Thanks. Since all the tests are already passing on your PR, let's submit your PR. I'll close this PR, and open a new PR to backport the new commits that were merged yesterday.

**Pull request closed without merging**
