### PR TITLE
v1.14 Backports 2023-12-05

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #29111 (@Alex-Waring)
 * [x] #29098 (@julianwiedmann)
 * [x] #29462 (@akhilles)
 * [x] #29182 (@viktor-kurchenko)
 * [x] #29547 (@sayboras)
 * [x] #29554 (@tklauser)
 * [x] #29497 (@danehans)
 * [x] #29566 (@christarazi)
 * [x] #29613 (@giorio94)
 * [x] #29603 (@mhofstetter)

PRs skipped due to conflicts:

 * #29443 (@gandro)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 29111 29098 29462 29182 29443 29547 29554 29497 29566 29613 29603
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
@viktor-kurchenko @gandro Some minor conflicts were hit, please check commit notes for details.

**Review by christarazi — APPROVED** [review]

**Review by mhofstetter — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
Thanks, looks good for my change.

**Comment by nbusseneau** [comment]
/test-backport-1.14

**Review by julianwiedmann — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
My commit looks good. Thanks!

**Review by viktor-kurchenko — APPROVED** [review]
My commit looks good. Thanks!

**Review by Alex-Waring — APPROVED** [review]
My change looks good thanks

**Review by sayboras — APPROVED** [review]
Thanks and LGTM :heavy_check_mark:

**Review by ti-mo — APPROVED** [review]

**Comment by nbusseneau** [comment]
I manually double-checked missing acks for backports of #29111, #29462, and #29497. This PR has passed all CI, only failing `ci-ipsec-upgrade` in a limited fashion, but this check is not required and known to be flaky right now.

I think we can merge this.

**Pull request merged**
