### PR TITLE
V1.4 - Backports 12-02-2019

### PR DESCRIPTION
**Pull request by eloycoto**
Backports

#7030
#7029

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7037)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by tgraf** [comment]
Do not merge this. This is not critical for 1.4.0

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
