### PR TITLE
daemon: bpf: add --bpf-conntrack-accounting-enabled flag

### PR DESCRIPTION
**Pull request by jibi**

### CODE REVIEW

**Review by gandro — COMMENTED** [review]
Helm LGTM. But is there a reason there is no usage or help flag like so?:

https://github.com/cilium/cilium/blob/59f0244e31d876150eb2de1fd309df5d20425ff1/daemon/cmd/daemon_main.go#L384-L385

In particular I'm not sure the configmap bit is picked up without BindEnv. Am I missing something?

**Comment by jibi** [comment]
> Helm LGTM. But is there a reason there is no usage or help flag like so?:

nite catch, I just overlooked that

> https://github.com/cilium/cilium/blob/59f0244e31d876150eb2de1fd309df5d20425ff1/daemon/cmd/daemon_main.go#L384-L385
> 
> In particular I'm not sure the configmap bit is picked up without BindEnv. Am I missing something?

(didn't notice I was missing it as the agent is still picking up the flag from the configmap)

**Review by gandro — APPROVED** [review]

**Comment by gandro** [comment]
> (didn't notice I was missing it as the agent is still picking up the flag from the configmap)

Ah right, because the configmap is mounted and read manually, and not via ENV variables

**Review by tommyp1ckles — APPROVED** [review]

**Pull request merged**
