### PR TITLE
cilium-health: Fix setting of disable_ipv6 sysctl

### PR DESCRIPTION
**Pull request by joamaki**
The disable_ipv6 sysctl setting is changed for the "cilium" veth interface inside the cilium health network namespace. For that we cannot use the normal sysctl API as that operates in the host network namespace. Instead we need to do a direct sysctl.

This fixes this sysctl health degradation which happens due to the sysctl setting happening on the wrong network namespace:

  "Error":"could not open the sysctl file /host/proc/sys/net/ipv6/conf/cilium/disable_ipv6:
   open /host/proc/sys/net/ipv6/conf/cilium/disable_ipv6: no such file or directory"

Fixes: 2079aa44fa3c ("datapath/sysctl: Use generic reconciler for sysctl params")

Marking this as "release-note/misc" without a release note as this fixes an issue in an unreleased version
of Cilium.

### CODE REVIEW

**Review by pippolo84 — APPROVED** [review]
Thanks!

**Review by nebril — APPROVED** [review]
Nice catch!

**Pull request merged**
