### PR TITLE
k8s: Update libraries to v1.21.11

### PR DESCRIPTION
**Pull request by nathanjsweet**
Signed-off-by: Nate Sweet <nathanjsweet@pm.me>

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Comment by nathanjsweet** [comment]
test-backport-1.10

**Review by YutaroHayakawa — APPROVED** [review]

**Comment by nathanjsweet** [comment]
/test-backport-1.10

**Comment by nathanjsweet** [comment]
All of the backport tests passed already, reopening to retest conformance.

**Comment by nathanjsweet** [comment]
/test-backport-1.10

**Comment by nathanjsweet** [comment]
Backport PRs passed already. I shouldn't have restarted them. This is ready to merge; I was waiting for Conformance to pass. AKS failure is #19766.

**Pull request merged**
