### PR TITLE
daemon: move policy trifecta leftovers (policy, ipcache & identityallocator)  to respective cells

### PR DESCRIPTION
**Pull request by mhofstetter**
Please review the individual commits.

Follow-up of #34332

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Awesome cleanup!

**Comment by mhofstetter** [comment]
renamed wrong packagename (`packagecell` -> `policycell`)

**Review by joamaki — APPROVED** [review]

**Comment by dlapcevic** [comment]
This is another great step forward for the modularization effort!

I’ve been looking into modularizing pkg/identity.
@mhofstetter, this seems to be an important part of the work for https://github.com/cilium/cilium/issues/23767.

cc @jrife

**Pull request merged**
