### PR TITLE
v1.8 backports 2020-06-19

### PR DESCRIPTION
**Pull request by borkmann**
v1.8 backports 2020-06-19

 * #12187 -- docs: Host firewall documentation (@pchaigno)
 * #12144 -- doc: revamp kata containers getting started guide (@Rolinh)
 * #12162 -- docs: Add IP fragmentation tracking section (@joestringer)
 * #12122 -- add missing hook in misc unit tests (@aanm)
 * #12192 -- test: Scrub GKE cluster more thoroughly when releasing cluster. (@jrajahalme)
 * #12145 -- docs: Extend BPF-based masquerading section (@brb)
 * #12197 -- datapath,daemon: Fix initialization panics when IPv6 is enabled (@brb)
 * #12198 -- option: Require native-routing-cidr only if IPv4 is enabled (@brb)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12187 12144 12162 12122 12192 12197 12198 12145; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by borkmann** [comment]
test-backport-1.8

**Comment by borkmann** [comment]
test-backport-1.8

**Review by pchaigno — APPROVED** [review]
:+1: for my changes.

**Comment by borkmann** [comment]
test-backport-1.8

**Review by brb — APPROVED** [review]
LGTM for my changes.

**Comment by borkmann** [comment]
runtime-4.9 test suite hit `Suite-runtime.RuntimePolicies Init Policy Default Drop Test With PolicyAuditMode tests ingress` test failure:
```
/home/jenkins/workspace/Cilium-PR-Runtime-4.9/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Default policy verdict on ingress failed
Expected
    <*errors.errorString | 0xc000de09f0>: {
        s: "Expected string \"[reserved:host] -> 1408 [container:somelabel] 10.15.140.6 : FORWARDED 5\" is not in the filter output of \"{.source.labels} -> {.destination.ID} {.destination.labels} {.IP.destination} : {.verdict} {.event_type.type}\": 4m0s timeout expired",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Runtime-4.9/runtime-gopath/src/github.com/cilium/cilium/test/runtime/Policies.go:1558
```
This should be fixed via https://github.com/cilium/cilium/pull/12003 which was not backported to 1.8 branch. Given this is known, I'm rerunning runtime-4.9 to see if it goes green, also marking 12003 to be backported, but can be done at a later point with the next batch.

**Comment by borkmann** [comment]
retest-runtime

**Review by joestringer — APPROVED** [review]

**Pull request merged**
