### PR TITLE
v1.14 Backports 2023-08-08

### PR DESCRIPTION
**Pull request by joamaki**
* [x] #26975 (@mhofstetter)
 * [ ] #27184 (@pchaigno)
 * [x] #27250 (@qmonnet)
 * [x] #27311 (@sayboras)
 * [x] #27237 (@giorio94)
 * [x] #27168 (@learnitall)
 * [x] #27208 (@WeirdMachine)
 * [x] #27312 (@julianwiedmann)
 * [x] #27231 (@youngnick)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 26975 27184 27250 27311 27237 27168 27208 27312 27231; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=26975,27184,27250,27311,27237,27168,27208,27312,27231
```

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commit :heavy_check_mark:

**Review by mhofstetter — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Review by learnitall — APPROVED** [review]
Looks good for my commit, thank you!

**Review by giorio94 — APPROVED** [review]
My commits look good. Thanks!

**Review by youngnick — APPROVED** [review]

**Comment by joamaki** [comment]
/test-backport-1.14

**Review by ldelossa — APPROVED** [review]

**Pull request merged**
