### PR TITLE
v1.6 backports 2019-08-09

### PR DESCRIPTION
**Pull request by nebril**
* #8840 -- bpf: verifier rejection fix and sock cookie cleanup (@borkmann)
 * #8809 -- eventqueue: protect against enqueueing same Event twice (@ianvernon)
 * #8848 -- Add RBAC to cilium preflight manifests (@raybejjani)
 * #8858 -- Fix NodePort template and GSG (@brb)
 * #8852 -- Fix typos in helm charts and documentation (@aanm)
 * #8850 -- nodeport: nat map size and collision retries (@borkmann)
 * #8859 -- preflight migrate-identity fixes (again) (@raybejjani)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 8840 8809 8848 8858 8852 8850 8859; do contrib/backporting/set-labels.py $pr done 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8853)

### CODE REVIEW

**Comment by nebril** [comment]
never-tell-me-the-odds

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
never-tell-me-the-odds

**Comment by ianvernon** [comment]
never-tell-me-the-odds

**Review by tgraf — APPROVED** [review]

**Pull request merged**
