### PR TITLE
v1.12: manual backport of #27193

### PR DESCRIPTION
**Pull request by nbusseneau**
This is a manual backport of #27193.

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.12

**Review by viktor-kurchenko — APPROVED** [review]

**Comment by nbusseneau** [comment]
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/163/ hit #24840. Marking `ready-to-merge`.

**Comment by ldelossa** [comment]
/test-1.16-4.9

**Comment by nbusseneau** [comment]
@ldelossa This change cannot have any impact on `k8s-1.16-kernel-4.9 (test-1.16-4.9)`, I've only flagged the flake because it was ran as part of the regular CI but there is no need to get it green ;)

**Pull request merged**
