### PR TITLE
docs: fix deployment resource type output

### PR DESCRIPTION
**Pull request by cleverhu**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

fix deployment apiversion error
Fixes: #issue-number

```release-note
docs: Fix `kubectl create` output in docs after some deployments have moved from K8s "extensions" to "apps".
```

### CODE REVIEW

**Review by qmonnet — CHANGES_REQUESTED** [review]
Hi, and thanks! Could you please provide some context on what the change is necessary? (Typically, linking to https://github.com/cilium/cilium/commit/f4ec8ea85aef609eb8c8db9ff958a32c84ac2090 in the commit description).

**Review by squeed — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
The changes LGTM, thanks. It would be nice to include the details of the corresponding commit as Quentin mentioned, but as a first PR focused primarily on docs I'm not too worried about it.

I've allowed the CI to run to check the docs build correctly.

**Comment by joestringer** [comment]
Smoke test hit known flake #22168 . Docs test passed.

**Comment by cleverhu** [comment]
> The changes LGTM, thanks. It would be nice to include the details of the corresponding commit as Quentin mentioned, but as a first PR focused primarily on docs I'm not too worried about it.
> 
> 

I'm sorry I forgot to modify commit. I'll change the commit description as soon as possible.

**Comment by joestringer** [comment]
OK, feel free to ping me when you have updated the PR.

**Comment by cleverhu** [comment]
> OK, feel free to ping me when you have updated the PR.

@joestringer I have updated the commit description, PTAL. Thanks a lot.

**Comment by joestringer** [comment]
I suspect that the failures may be introduced because the PR is based upon a much older version of the main branch, and the code at that time was not as stable. I'll see if the "Update with Rebase" button addresses the latest failures.

**Comment by joestringer** [comment]
Typically commit messages would start with a short one-liner like the title of the PR has, then the rest of the current commit message would follow. For example:

```
docs: fix deployment resource type output

Since k8s had remove support for extensions/v1beta1 API version after… ￼…
1ab8cb4
… 1.16, we should update the docs to the latest and stable version.

Signed-off-by: cleverhu <shouping.hu@daocloud.io>
```

This would also help to resolve one of the CI complaints.

**Comment by cleverhu** [comment]
> Typically commit messages would start with a short one-liner like the title of the PR has, then the rest of the current commit message would follow. For example:
> 
> 
> 
> ```
> 
> docs: fix deployment resource type output
> 
> 
> 
> Since k8s had remove support for extensions/v1beta1 API version after 1.16, we should update the docs to the latest and stable version.
> 
> 
> 
> Signed-off-by: cleverhu <shouping.hu@daocloud.io>
> 
> ```
> 
> 
> 
> This would also help to resolve one of the CI complaints.

Ok,thanks. I will update as soon as possible.

**Comment by cleverhu** [comment]
> Typically commit messages would start with a short one-liner like the title of the PR has, then the rest of the current commit message would follow. For example:
> 
> ```
> docs: fix deployment resource type output
> 
> Since k8s had remove support for extensions/v1beta1 API version after 1.16, we should update the docs to the latest and stable version.
> 
> Signed-off-by: cleverhu <shouping.hu@daocloud.io>
> ```
> 
> This would also help to resolve one of the CI complaints.

Done, PTAL.

**Comment by joestringer** [comment]
Thanks, merged.

**Pull request merged**
