### PR TITLE
bpf: Dual-license code as GPL 2.0 and 2-Clause BSD

### LINKED ISSUE #18823: Dual-license `bpf/` code as GPL 2.0 and 2-Clause BSD
As part of [Cilium's work with the Linux Foundation](https://cilium.io/blog/2021/10/13/cilium-joins-cncf), CNCF made the request that the eBPF datapath code under `bpf/` be dual-licensed. The motivation for this is to be compliant with the [CNCF IP policy](https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy).

The selected licenses for the code are the [GPL 2.0](https://spdx.org/licenses/GPL-2.0-only.html) and the [2-Clause BSD](https://spdx.org/licenses/BSD-2-Clause.html): `GPL-2.0-only OR BSD-2-Clause`. The 2-Clause BSD was selected because:

- It is one of the [approved licenses for the CNCF allowlist license policy](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md).
- It would help if we needed to potentially share code with libbpf in the future (libbpf is LGPL-2.1 OR BSD-2-Clause).
- `"Dual BSD/GPL"` has the additional advantage of being [a valid license string in the eyes of the Linux kernel verifier](https://elixir.bootlin.com/linux/v5.16/source/include/linux/license.h).

This decision was submitted for a vote to the Cilium Committers, and the result was in favour of the change. Next steps:
1. Get the approval of the various contributors to the `bpf/` code, as copyright holders.
2. Create a PR to update license notices, license strings in ELF sections, and `bpf/COPYING` accordingly.

### PR DESCRIPTION
**Pull request by qmonnet**
As part of [Cilium's work with the Linux Foundation](https://cilium.io/blog/2021/10/13/cilium-joins-cncf), CNCF made the request that the eBPF datapath code under `bpf/` be dual-licensed. The motivation for this is to be compliant with the [CNCF IP policy](https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy).

The selected licenses for the code are the [GPL 2.0](https://spdx.org/licenses/GPL-2.0-only.html) and the [2-Clause BSD](https://spdx.org/licenses/BSD-2-Clause.html): `GPL-2.0-only OR BSD-2-Clause`. The 2-Clause BSD was selected because:

- It is one of the [approved licenses for the CNCF allowlist license policy](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md).
- It would help if we needed to potentially share code with libbpf in the future (libbpf is LGPL-2.1 OR BSD-2-Clause).
- `"Dual BSD/GPL"` has the additional advantage of being [a valid license string in the eyes of the Linux kernel verifier](https://elixir.bootlin.com/linux/v5.16/source/include/linux/license.h).

This decision was submitted for a vote to the Cilium Committers, and the result was in favour of the new licenses. This PR implements the change.

Related issue: #18823 

[Status] We now have the approval of most authors, either as reviews on this PR, or by private channels such as email. Please refer to the description of the first commit for details.

### CODE REVIEW

**Comment by Weil0ng** [comment]
LGTM :)

**Review by chez-shanpu — APPROVED** [review]
LGTM :D

**Comment by bpineau** [comment]
LGTM

**Comment by lkpdn** [comment]
LGTM

**Review by lkpdn — APPROVED** [review]
LGTM

**Review by lbernail — APPROVED** [review]
LGTM

**Review by errordeveloper — APPROVED** [review]

**Review by ap4y — APPROVED** [review]
LGTM

**Review by fristonio — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Review by xunholy — APPROVED** [review]
LGTM

**Comment by hangyan** [comment]
LGTM

**Comment by ArthurChiao** [comment]
LGTM, thanks!

**Review by jaffcheng — APPROVED** [review]

**Review by ArthurChiao — APPROVED** [review]

**Review by vadorovsky — APPROVED** [review]
LGTM

**Comment by Inode1** [comment]
LGTM

**Comment by qmonnet** [comment]
I received approvals from most contributors. Nobody objected. There are a few contributors from whom I did not manage to get an answer, but this is only for minor code changes, so I believe we can go ahead and proceed.

I marked the PR as non-draft.

The details for all approvals received are written down in the description of the first commit of the PR.

**Review by borkmann — APPROVED** [review]

**Review by jibi — APPROVED** [review]

**Review by lizrice — APPROVED** [review]

**Pull request merged**
