### PR TITLE
daemon: Allow to fallback to iptables-based masquerading and friends

### PR DESCRIPTION
**Pull request by brb**
This PR:

- Fallbacks to iptables-based masquerading if `--enable-bpf-masquerading=true`, but `--enable-node-port=true` is not possible. This allows us to enable BPF masquerading by default for new deployments (via helm).
- Adds masquerading to `cilium status`.

Reviewable per commit.

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
retest-4.19

**Review by soumynathan — COMMENTED** [review]
LGTM

**Review by soumynathan — COMMENTED** [review]
Looks good to me.

**Pull request merged**
