### PR TITLE
agent: Add flag to disable connectivity health checking

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7413)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Review by vadorovsky — APPROVED** [review]

**Comment by vadorovsky** [comment]
Probably unrelated:

```
13:00:47  • Failure [57.325 seconds]
13:00:47  K8sFQDNTest
13:00:47  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:377
13:00:47    Restart Cilium validate that FQDN is still working [It]
13:00:47    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:409
13:00:47  
13:00:47    "app2-5b49d5dd9-xx7mz" cannot curl to "http://world1.cilium.test"
[2019-03-15T12:00:47.586Z]   Expected command: kubectl exec -n default app2-5b49d5dd9-xx7mz -- curl -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 http://world1.cilium.test -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
[2019-03-15T12:00:47.586Z]   To succeed, but it failed:
[2019-03-15T12:00:47.586Z]   Exitcode: 28 
[2019-03-15T12:00:47.586Z]   Stdout:
[2019-03-15T12:00:47.586Z]    	 time-> DNS: '0.029867()', Connect: '0.000000',Transfer '0.000000', total '5.004550'
[2019-03-15T12:00:47.586Z]   Stderr:
[2019-03-15T12:00:47.586Z]    	 command terminated with exit code 28
[2019-03-15T12:00:47.586Z]   	 
[2019-03-15T12:00:47.586Z]   
13:00:47  
13:00:47    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/fqdn.go:150
```

And a lot of etcd connection errors:

```
13:02:20  Cilium is not ready yet: status is unhealthy: cilium-agent 'cilium-598jf' is unhealthy: Exitcode: 1 
13:02:20  Stdout:
13:02:20   	 KVStore:                Failure   Err: Not able to connect to any etcd endpoints
13:02:20  	 ContainerRuntime:       Ok        docker daemon: OK
13:02:20  	 Kubernetes:             Ok        1.13 (v1.13.4) [linux/amd64]
13:02:20  	 Kubernetes APIs:        ["CustomResourceDefinition", "cilium/v2::CiliumNetworkPolicy", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
13:02:20  	 Cilium:                 Failure   Kvstore service is not ready
13:02:20  	 NodeMonitor:            Disabled
13:02:20  	 Cilium health daemon:   Ok   
13:02:20  	 IPv4 address pool:      3/255 allocated from 10.10.0.0/24
13:02:20  	 IPv6 address pool:      2/65535 allocated from f00d::a0a:0:0:0/112
13:02:20  	 Controller Status:      16/16 healthy
13:02:20  	 Proxy Status:           OK, ip 10.10.0.1, port-range 10000-20000
13:02:20  	 
13:02:20  Stderr:
13:02:20   	 command terminated with exit code 1
```

**Comment by vadorovsky** [comment]
test-me-please

**Comment by tgraf** [comment]
Only FQDN test failed

**Pull request merged**
