### PR TITLE
v1.15 Backports 2024-02-27

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
* [x] #30090 (@chaunceyjiang)
 * [ ] #30677 (@tklauser)
 * [ ] #30859 (@tklauser)
 * [x] #30854 (@julianwiedmann)
 * [x] #30170 (@oblazek)
 * [ ] #30635 (@jdmcmahan)
 * [x] #30868 (@YutaroHayakawa)
 * [x] #30818 (@giorio94)
 * [x] #30970 (@iandrewt)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30090 30677 30859 30854 30170 30635 30868 30818 30970
```

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
My commit looks good, thanks!

**Review by oblazek — APPROVED** [review]
My part looks good :) Thanks.

**Review by sayboras — APPROVED** [review]
Thanks and LGTM for https://github.com/cilium/cilium/pull/30970

**Review by julianwiedmann — APPROVED** [review]

**Review by chaunceyjiang — APPROVED** [review]
/lgtm Thanks.

**Comment by YutaroHayakawa** [comment]
/test-backport-1.15

**Review by ldelossa — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
Cilium IPsec upgrade: Timeout
Conformance E2E: https://github.com/cilium/cilium/issues/27762
Conformance Ingress: https://github.com/cilium/cilium/issues/30281

**Pull request merged**
