### PR TITLE
helm: Remove deprecated hubble.tls.ca

### PR DESCRIPTION
**Pull request by ysksuzuki**
hubble.tls.ca has been removed but but it's still being referenced. This commit cleans up those references.

follow-up of 0fd394566dfca3a3b64ac5f245d76df503d78531

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]
Looks good from my side, thanks for catching this and fixing it!

Given that it fixes an issue with the Helm charts that we recently introduced, it would be great to have this in before the next release. I'm marking as release blocker.

**Comment by ysksuzuki** [comment]
It seems that Chart CI push has been fixed by https://github.com/cilium/cilium/pull/25274

**Comment by ysksuzuki** [comment]
Hit the flake https://github.com/cilium/cilium/issues/15455

**Comment by ysksuzuki** [comment]
/test-1.26-net-next

**Comment by ysksuzuki** [comment]
Hit https://github.com/cilium/cilium/issues/22579

**Comment by ysksuzuki** [comment]
/test-1.26-net-next

**Review by gandro — APPROVED** [review]

**Comment by ysksuzuki** [comment]
@youngnick Would you be able to take a look at this PR?

**Review by youngnick — APPROVED** [review]

**Pull request merged**
