### PR TITLE
vagrant: Bump net-next VM image version

### PR DESCRIPTION
**Pull request by pchaigno**
This new image includes a few additional kernel configs that are (1) useful for debugging and (2) required for kube-proxy.

### CODE REVIEW

**Comment by pchaigno** [comment]
/test-1.25-net-next

**Review by gentoo-root — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.25-net-next

**Comment by pchaigno** [comment]
/test-1.25-net-next

**Pull request merged**
