### PR TITLE
Protect remaining local keys from kvstore delete events

### PR DESCRIPTION
**Pull request by tgraf**
Fixes: #7222

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7246)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Known CI flake `k8s-1.8.K8sFQDNTest Restart Cilium validate that FQDN is still working`

**Comment by tgraf** [comment]
test-me-please

**Review by jrfastab — APPROVED** [review]

**Comment by ianvernon** [comment]
@tgraf my understanding a 'local' key appears to be wrong - how is it that a 'local' key would be removed by the kvstore? Are local keys also stored in the kvstore? What exactly is the definition of a local key? Is it a key that is 'in-use' locally?

**Comment by tgraf** [comment]
> my understanding a 'local' key appears to be wrong - how is it that a 'local' key would be removed by the kvstore? Are local keys also stored in the kvstore? What exactly is the definition of a local key? Is it a key that is 'in-use' locally?

A local key is a kvstore key that is owned by the local agent instance. The main reason for the local key disappearing is the lease timing out before the local agent comes up again and overwrites the key with a new lease. Another source is malicious or erroneous deletion.

**Pull request merged**
