### PR TITLE
vendor: bump github.com/google/gopacket to v1.1.19

### PR DESCRIPTION
**Pull request by tklauser**
Note that behavior of `(*DecodingLayerParser).DecodeLayers` wrt. empty packet data changed (see google/gopacket#846). This was addressed in the Cilium codebase in #14448.

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
retest-runtime

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
retest-runtime

**Review by vadorovsky — APPROVED** [review]

**Pull request merged**
