### PR TITLE
v1.7 backports 2020-06-12

### PR DESCRIPTION
**Pull request by jrajahalme**
* #11995 -- test: Wait for POD policy revision increment in all cases. (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 11995; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-backport-1.7

**Comment by joestringer** [comment]
@jrajahalme are you still looking at this at all?

**Comment by brb** [comment]
@jrajahalme Can we close this?

**Comment by jrajahalme** [comment]
This backport turned out to be too messy due to other changes in the CI code. The flake fixed here is really rare, so not worth the effort to backport this.

**Pull request closed without merging**
