### PR TITLE
kvstore: Support creation of multiple clients

### PR DESCRIPTION
**Pull request by tgraf**
Requires moving lease management into client specific code. New function
NewClient() and .Close() to create and close clients.

Required for #4727 

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4725)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by aanm** [comment]
How can you specify the server address for the new client? When doing `newInstance()` aren't you duplicating the number of controllers?

**Comment by tgraf** [comment]
> How can you specify the server address for the new client?
```
opts := map[string]string{
    "etcd.config": rc.configPath,
}
backend, err := kvstore.NewClient("etcd", opts)
```



> When doing newInstance() aren't you duplicating the number of controllers?

I'm not sure I understand. `newInstance()` will create a copy of the backend specific option definition to store options specific to the instance, e.g.
```
        etcdInstance = &etcdModule{
                opts: backendOptions{
                        addrOption: &backendOption{
                                description: "Addresses of etcd cluster",
                        },
                        cfgOption: &backendOption{
                                description: "Path to etcd configuration file",
                        },
                },
        }
```

**Review by aanm — APPROVED** [review]
@tgraf I thought "NewInstance" was a new instance of a client.

**Pull request merged**
