### PR TITLE
Prepare for release v1.2.3

### PR DESCRIPTION
**Pull request by ianvernon**
Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5597)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-missed-k8s

**Review by tgraf — APPROVED** [review]

**Comment by aanm** [comment]
```
10:50:57 • Failure in Spec Setup (BeforeEach) [465.332 seconds]
10:50:57 K8sPolicyTest
10:50:57 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
10:50:57   Basic Test [BeforeEach]
10:50:57   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
10:50:57     checks all kind of Kubernetes policies
10:50:57     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
10:50:57 
10:50:57     kube-dns was not able to get into ready state
10:50:57     Expected
10:50:57         <*errors.errorString | 0xc4204d99c0>: {
10:50:57             s: "Timeout reached: timed out waiting for pods with filter -l k8s-app=kube-dns to be ready",
10:50:57         }
10:50:57     to be nil
```
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/869/execution/node/54/log/?consoleFull

**Comment by aanm** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Triaging the failures...

**Comment by ianvernon** [comment]
There was no kube-dns pod running at all?

```
09:04:09 • Failure in Spec Setup (BeforeEach) [449.478 seconds]
09:04:09 K8sChaosTest
09:04:09 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
09:04:09   Endpoint can still connect while Cilium is not running [BeforeEach]
09:04:09   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
09:04:09 
09:04:09   kube-dns was not able to get into ready state
09:04:09   Expected
09:04:09       <*errors.errorString | 0xc420087930>: {
09:04:09           s: "Timeout reached: timed out waiting for pods with filter -l k8s-app=kube-dns to be ready",
09:04:09       }
09:04:09   to be nil
09:04:09 
09:04:09   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/k8sT/Chaos.go:41
09:04:09 ------------------------------
09:04:09 SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
09:04:09 ------------------------------
09:04:09 K8sKafkaPolicyTest Kafka Policy Tests 
09:04:09   KafkaPolicies
09:04:09   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
09:11:19 ===================== TEST FAILED =====================
09:11:19 prometheus-core-5c9fbf5cc6-jrqd9 => none
09:11:19 cmd: kubectl get pods -o wide --all-namespaces
09:11:19 NAMESPACE     NAME                               READY     STATUS    RESTARTS   AGE       IP              NODE
09:11:19 kube-system   cilium-lnr9n                       1/1       Running   0          28m       192.168.36.11   k8s1
09:11:19 kube-system   cilium-qs25t                       1/1       Running   0          28m       192.168.36.12   k8s2
09:11:19 kube-system   etcd-k8s1                          1/1       Running   0          40m       192.168.36.11   k8s1
09:11:19 kube-system   kube-apiserver-k8s1                1/1       Running   0          39m       192.168.36.11   k8s1
09:11:19 kube-system   kube-controller-manager-k8s1       1/1       Running   0          37m       192.168.36.11   k8s1
09:11:19 kube-system   kube-proxy-p6cvs                   1/1       Running   0          37m       192.168.36.11   k8s1
09:11:19 kube-system   kube-proxy-vvhkf                   1/1       Running   0          32m       192.168.36.12   k8s2
09:11:19 kube-system   kube-scheduler-k8s1                1/1       Running   0          37m       192.168.36.11   k8s1
09:11:19 prometheus    prometheus-core-5c9fbf5cc6-jrqd9   1/1       Running   0          32m       10.10.0.86      k8s1
09:11:19 
```

**Comment by ianvernon** [comment]
```
08:31:58     k8s1-1.8: Error from server (NotFound): error when deleting "/tmp/provision//manifest/dns_deployment.yaml": configmaps "kube-dns" not found
08:31:58     k8s1-1.8: error when stopping "/tmp/provision//manifest/dns_deployment.yaml": timed out waiting for the condition
08:31:58     k8s1-1.8: service "kube-dns" created
08:31:58     k8s1-1.8: serviceaccount "kube-dns" created
08:31:58     k8s1-1.8: configmap "kube-dns" created
08:31:58     k8s1-1.8: Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
08:31:58     k8s1-1.8: deployment "kube-dns" configured
```

That would explain it :) - unfortunately we do the following in the VM provisioning, meaning that if there is some legitimate error, we may mask it?

```
kubectl -n kube-system delete -f ${PROVISIONSRC}/manifest/dns_deployment.yaml || true
```

**Comment by tgraf** [comment]
We should triage and look into build failures when we do backports, not while merging the changelog. It will become bad practice and will result in us merging backports that are not well tested.

**Pull request merged**
