### PR TITLE
v1.3: backports 19-01-29

### PR DESCRIPTION
**Pull request by ianvernon**
* PR: 6794 -- daemon: syncLBMapsWithK8s - delete k8s service once if not found (@aanm) -- https://github.com/cilium/cilium/pull/6794
* PR: 6808 -- endpoint: Fix old endpoint identity release (@tgraf) -- https://github.com/cilium/cilium/pull/6808

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6849)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Trying to backport #6834 caused issues because the cherry-pick script is trying to cherry-pick a change onto itself. Given that this isn't an end-user facing change, ignored it for now.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
Regular CI tests failed due to VM being unable to boot: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9473/flowGraphTable/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
K8s tests failed due to upgrade test failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1577/testReport/junit/k8s-1/8/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/

This was the first test that ran in the CI; I wonder if the test can handle being the first test to run - is it reliant upon Cilium v1.3 being deployed previously?

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Build failure: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1580

Connections during restart tests failed. This has failed periodically in the v1.3 branch in the past.

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
@tgraf @aanm can you PTAL at the backported commits ? The test failures are fairly consistent in the K8s tests w.r.t. connections being dropped during Cilium restart. 

Link: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1585/

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by tgraf — APPROVED** [review]
Commit 2 LGTM

**Pull request merged**
