### PR TITLE
Fix the typo in Fatalf message of printConfigurations

### PR DESCRIPTION
**Pull request by wqld**
Signed-off-by: Wongyu Lee <kyu21@outlook.com>

I fixed Fatalf msg's typo in printConfigurations() method.
configuratons -> configurations

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Comment by 21kyu** [comment]
sorry, I typed signed-off-by wrong.
I modified the commit message with "Signed-off-by: Wongyu Lee <kyu21@outlook.com>" but I am not sure if it is correct.

(The error message seemed to ask for "Signed-off-by: wq <kyu21@outlook.com>", but from what I have checked, anonymous names are not allowed like 'wq'. So I renamed Github and also modified signed-off-by appropriately.)

**Comment by pchaigno** [comment]
@21kyu The new commit is fine. The bot would complain if the Signed-off-by tag was improperly formatted. And yes, anonymous names are not allowed.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
Oh, wait! Checkpatch does complain. The issue is the lack of an empty line between the commit title and the Signed-off-by tag I believe.

**Comment by 21kyu** [comment]
@pchaigno Thanks so much for the advice!
I added a newline between the commit title and signed-off-by.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
The changes are trivial and smoke tests passed. Merging.

**Pull request merged**
