### PR TITLE
envoy: Adjust log levels to avoid excessive logging.

### PR DESCRIPTION
**Pull request by jrajahalme**
Only enable Envoy debug level if cilium-agent option "--debug-verbose
flow" is set. Enable Envoy "trace" log level if "--debug-verbose
envoy" is set.

Adjust the log levels of cilium envoy filters to reduce logging.

Fixes: #3021 
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
I'll rebase this after #3034 is merged.

**Comment by tgraf** [comment]
@jrajahalme #3034 has been merged

**Review by rlenglet — APPROVED** [review]

**Comment by jrajahalme** [comment]
test-me-please

**Review by manalibhutiyani — APPROVED** [review]

**Comment by manalibhutiyani** [comment]
Merging since all checks have passed.

**Pull request merged**
