### PR TITLE
Update AWS deps

### PR DESCRIPTION
**Pull request by ungureanuvladvictor**
Signed-off-by: Vlad Ungureanu <ungureanuvladvictor@gmail.com>

### CODE REVIEW

**Comment by ungureanuvladvictor** [comment]
ci-eks -- checking if this works!

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Comment by ungureanuvladvictor** [comment]
test-gke

**Comment by ungureanuvladvictor** [comment]
test-1.16-netnext

**Comment by ungureanuvladvictor** [comment]
retest-net-next

**Review by christarazi — APPROVED** [review]
If you happen to know, would these changes support IMDSv2 API (context: https://github.com/cilium/cilium/issues/15520)?

**Comment by ungureanuvladvictor** [comment]
@christarazi I see https://github.com/aws/aws-sdk-go-v2/pull/453 and that was included in `config/v0.1.0`. I think the SDK by default tries to use imdsv2 if it is not disabled. Will have to look at bit more at this to be 100% sure.

**Comment by ungureanuvladvictor** [comment]
test-gke

**Comment by ungureanuvladvictor** [comment]
test-1.16-netnext

**Pull request merged**
