### PR TITLE
v1.12 backports 2022-07-05

### PR DESCRIPTION
**Pull request by qmonnet**
* [x] #20286 -- images: Bump Hubble CLI to v0.10.0 (@gandro)
 * [x] #20357 -- Update values.yaml.tmpl (@michi-covalent)
 * [x] #20316 -- labels/cidr: use netip types to improve GetCIDRLabels and IPStringToLabel performace (@tklauser)
 * [ ] #20264 -- test: Fix make target for k8s tests (@ysksuzuki)
 * [x] #20304 -- Fix config map options validation (@pippolo84)
    * Trivial conflict on first commit, solved by regenerating install/kubernetes/cilium/README.md and Documentation/helm-values.rst.
 * [x] #20308 -- Add support for disabling ENI PD at node level (@hemanthmalla)
    * Conflict: Jumping CustomResourceDefinitionSchemaVersion from 1.25.3 instead of 1.25.4 in pkg/k8s/apis/cilium.io/v2/register.go.
 * [x] #20132 -- test/runtime: remove disabled memcache test (@tklauser)
    *  Trivial conflict: CODEOWNERS, trimmed for 1.12 release, is left untouched.
 * [x] #19932 -- ipsec: fix stale keys reclaim logic (@jibi)
 * [ ] #20361 --  fix identity gc  to return correct  max/min id (@dkhachyan)
 * [x] #20360 -- ci: pick up cilium-cli v0.11.10 for master, v1.11 and v1.12 workflows (@tklauser)
    *  Most workflow files have been removed in preparation of the 1.12 release, and were therefore skipped on this branch.
 * [x] #20371 -- go.mod, vendor: update cloud provider SDK Go modules for July 2022 (@tklauser)
 * [x] #20241 -- docs: Add more envoy supported extensions (@sayboras)
 * [x] #20373 -- Restore patch in ciliumnetworkpolicies/status ClusterRole (@pippolo84)
 * [x] #20328 -- daemon: Deprecate KPR=probe (@brb)
 * [ ] #20379 -- bpf: Provision HostPort also for case of Maglev (@borkmann)
 * [x] #20245 -- bpf: Don't emit policy verdict post-L7 (@joestringer)
 * [x] #20149 -- api: re-sync bpf drop reasons (@julianwiedmann)
 * [x] #20269 -- daemon, option: Fix MTU when egress gateway is used (@pchaigno)
 * [x] #20392 -- nodediscovery: make LocalNode return a deep copy of localNode (@jibi)
 * [x] #20282 -- daemon, option: Fix vlan bpf bypass ids loading (@pippolo84)
 * [ ] #20388 -- ctmap: Do not use nil locks (@jrajahalme)
 * [x] #20399 -- docs: Improve policy troubleshooting guide (@joestringer)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20286 20357 20316 20264 20304 20308 20132 19932 20361 20360 20371 20241 20373 20328 20379 20245 20149 20269 20392 20282 20388 20399; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
$ make add-label BRANCH=v1.12 ISSUES=20286,20357,20316,20264,20304,20308,20132,19932,20361,20360,20371,20241,20373,20328,20379,20245,20149,20269,20392,20282,20388,20399
```

### CODE REVIEW

**Review by joestringer — APPROVED** [review]
For my PRs: :+1:

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by michi-covalent — APPROVED** [review]
thanks @qmonnet! lgtm on my change https://github.com/cilium/cilium/pull/20401/commits/591ca418bdb809e96e3aea778a2e8d8666d4c7ec ✅

**Review by hemanthmalla — APPROVED** [review]
LGTM. Thank you.

**Comment by qmonnet** [comment]
/test-backport-1.12

**Comment by qmonnet** [comment]
/test-backport-1.12

**Review by sayboras — APPROVED** [review]
Looks good for my commit, thanks :100:

**Comment by qmonnet** [comment]
/test-1.20-4.9

**Review by julianwiedmann — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
My changes look good, thanks Quentin!

**Review by pippolo84 — APPROVED** [review]
For my PRs :+1:

**Review by gandro — APPROVED** [review]

**Review by brb — APPROVED** [review]
LGTM for my changes, thanks.

**Review by jibi — APPROVED** [review]

**Comment by ti-mo** [comment]
This seems to have hit https://github.com/cilium/cilium/issues/18595.

**Comment by ti-mo** [comment]
/ci-aks-1.12

**Comment by ti-mo** [comment]
GKE hitting known flakes. AKS workflow currently broken, though no Azure-related changes were included. Another round of backports needs to be started, merging.

**Pull request merged**
