### PR TITLE
resource: Add support for custom Indexers

### PR DESCRIPTION
**Pull request by pippolo84**
Add support for custom Indexers to the Resource[T] package.  This enables to add user-defined indexes to the k8s objects in the resource[T] underlying store.

### CODE REVIEW

**Review by youngnick — APPROVED** [review]

**Review by rastislavs — APPROVED** [review]
LGTM

**Review by tommyp1ckles — APPROVED** [review]
awesome! changes look good

**Comment by pippolo84** [comment]
Cilium Conformance E2E flake tracked [here](https://github.com/cilium/cilium/issues/27194), rerunning.

**Pull request merged**
