### PR TITLE
bpf: use bpf_xdp_load_bytes() / bpf_xdp_store_bytes() helpers

### LINKED ISSUE #29356: bpf: use bpf_xdp_load_bytes() / bpf_xdp_store_bytes() when available
These new helpers were introduced with kernel `5.18`, and can replace our current [inline-assembly](https://github.com/cilium/cilium/blob/9c1031e31719214c2d19c0fa0c33d91a3304df3b/bpf/include/bpf/ctx/xdp.h#L37) implementation.

### PR DESCRIPTION
**Pull request by julianwiedmann**
These helpers were introduced in kernel 5.18, with
3f364222d032 ("net: xdp: introduce bpf_xdp_pointer utility routine").

Add the needed probes, and have the datapath use the helpers when available.

Fixes: #29356

```release-note
bpf: use bpf_xdp_load_bytes() / bpf_xdp_store_bytes() helpers when available
```

### CODE REVIEW

**Review by rgo3 — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Review by borkmann — APPROVED** [review]

**Comment by borkmann** [comment]
> Add the needed probes, and have the datapath use the helpers when available.

:rocket: this could also get us closer to supporting >4k MTU on XDP.

**Review by brlbil — APPROVED** [review]

**Comment by julianwiedmann** [comment]
Looks like we want this in `v1.14` to improve complexity for the 6.1 kernel.

**Pull request merged**
