### PR TITLE
vendor: Upgrade github.com/optiopay/kafka

### PR DESCRIPTION
**Pull request by rlenglet**
Signed-off-by: Romain Lenglet <romain@covalent.io>

### CODE REVIEW

**Review by tgraf — APPROVED** [review]

**Comment by rlenglet** [comment]
This PR pull in this Kafka parser fix: https://github.com/cilium/kafka/pull/1

**Review by manalibhutiyani — APPROVED** [review]
Thanks for fixing this!

**Comment by rlenglet** [comment]
It seems like Build 1's K8s tests failed due to kube-apiserver not responding to "get pods" request:
https://jenkins.cilium.io/job/cilium/job/cilium/view/change-requests/job/PR-2280/1/execution/node/35/log/?consoleFull
Started another build.

**Review by manalibhutiyani — CHANGES_REQUESTED** [review]
The message change set is true for versions >=1. I just realized it while testing. I will update the fork and you can update the new SHA here. Apologies for that.

**Review by manalibhutiyani — APPROVED** [review]
Looks good..Thanks for the patience!

**Comment by rlenglet** [comment]
Got a passing build for this change: https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-2280/2/

**Pull request merged**
