### PR TITLE
v1.14 Backports 2024-08-19

### PR DESCRIPTION
**Pull request by viktor-kurchenko**
* [x] #33698 (@youngnick) :warning: resolved conflicts
 * [ ] #34137 (@youngnick) :warning: resolved conflicts
 * [ ] #34372 (@Artyop)
 * [x] #34400 (@mhofstetter)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33698 34137 34372 34400
```

### CODE REVIEW

**Review by mhofstetter — APPROVED** [review]

**Comment by viktor-kurchenko** [comment]
/test-backport-1.14

**Review by youngnick — APPROVED** [review]

**Comment by youngnick** [comment]
I approved because #33698 is all good, but #34137 has had some content lost along the way.

**Comment by viktor-kurchenko** [comment]
/test-backport-1.14

**Comment by viktor-kurchenko** [comment]
> I approved because #33698 is all good, but #34137 has had some content lost along the way.

@youngnick I've pushed the fix. Could you please take a look one more time? Thank you!

**Review by ldelossa — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Review by youngnick — APPROVED** [review]
@viktor-kurchenko that all looks great now, thanks!

**Pull request merged**
