### PR TITLE
bpf: Enable some IPv6 code only if ENABLE_IPV6 is set

### PR DESCRIPTION
**Pull request by brb**
75028e4bcb14 made setting of `ROUTER_IP` conditional, i.e. it is non-empty only if IPv6 is enabled.

In the case of ipv4-only mode, `ROUTER_IP` in `node_config.h` is empty which leads to compilation errors of BPF functions which invoke `BPF_V6(<..>, ROUTER_IP)`.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6771)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
LGTM, if it compiles with all the combinations locally in the tree then it should be fine.

We could probably clean up the macro checks a little bit by shifting them to lib/* headers as much as possible, so that eg `bpf/bpf_overlay.c` doesn't need the extra checks (it would just do a `handle_ipv6()` call which is defined to `return DROP_UNKNOWN_L3` if `!ENABLE_IPv6`, but that's not necessary in this PR.

**Comment by tgraf** [comment]
We should also fix
```
bpf/node_config.h:#define ROUTER_IP 0xbe, 0xef, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x1, 0x0, 0x0
```

to only be defined when IPv6 is enabled

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
> We could probably clean up the macro checks a little bit by shifting them to lib/* headers as much as possible, so that eg bpf/bpf_overlay.c doesn't need the extra checks (it would just do a handle_ipv6() call which is defined to return DROP_UNKNOWN_L3 if !ENABLE_IPv6, but that's not necessary in this PR.

Good idea! I will do it in a subsequent PR.

**Comment by tgraf** [comment]
I've added this for the IPv6 only case:
```
diff --git a/bpf/node_config.h b/bpf/node_config.h
index 5540e71ee..ff15c1106 100644
--- a/bpf/node_config.h
+++ b/bpf/node_config.h
@@ -38,9 +38,13 @@
 #define INIT_ID 5
 #define HOST_IFINDEX_MAC { .addr = { 0xce, 0x72, 0xa7, 0x03, 0x88, 0x56 } }
 #define NAT46_PREFIX { .addr = { 0xbe, 0xef, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0 } }
+
+#ifdef ENABLE_IPV4
 #define IPV4_MASK 0xffff
 #define IPV4_GATEWAY 0xfffff50a
 #define IPV4_LOOPBACK 0x1ffff50a
+#endif
+
 #define ENCAP_GENEVE 1
 #define ENDPOINTS_MAP test_cilium_lxc
 #define EVENTS_MAP test_cilium_events

```

**Review by borkmann — APPROVED** [review]
lgtm

**Pull request merged**
