### PR TITLE
[v1.9] Update K8s to v1.19.12

### PR DESCRIPTION
**Pull request by christarazi**
- k8s: Update libraries to 1.19.12

### CODE REVIEW

**Comment by christarazi** [comment]
test-backport-1.9

**Review by jibi — APPROVED** [review]

**Comment by christarazi** [comment]
test-backport-1.9

**Comment by christarazi** [comment]
test-only --focus="K8sVerifier.*" --k8s_version=1.18 --kernel_version=419

**Comment by christarazi** [comment]
test-1.17-5.4

**Comment by christarazi** [comment]
test-1.18-4.19

**Review by errordeveloper — APPROVED** [review]

**Comment by aditighag** [comment]
Branch needs to be rebased, but since these are just library changes, it should be okay to merge.

**Pull request merged**
