### PR TITLE
bpf: Fix setting IPv6 proxy rule

### PR DESCRIPTION
**Pull request by jrajahalme**
Add the needed white space to the bash `if` statement testing if we
need to set the routing rule for IPv6.

Missing the special routing rules caused TCP connections redirected to an ingress proxy from an external (non-Cilium-range) address to fail in TCP handshake, which is seen the source as a connection timeout.

Fixes: c2e7d8a521 ("bpf: Only attempt to install ip rules if address family is available")

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5777)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by jrajahalme** [comment]
Thanks to @joestringer for spending the time with me to track this down!

**Comment by ianvernon** [comment]
Ah, bash, my old friend.

**Comment by jrajahalme** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Comment by jrajahalme** [comment]
@joestringer I'm adding a test in a separate PR.

**Pull request merged**
