### PR TITLE
Fix makefile and a small interface change

### PR DESCRIPTION
**Pull request by anfernee**
2 small fixes that I bumped into when running `make unit-tests`.

### CODE REVIEW

**Review by tklauser — APPROVED** [review]
Thanks!

**Comment by tklauser** [comment]
test-me-please

**Comment by anfernee** [comment]
checked the failed tests. I don't think the failed test is related to this change.

**Comment by pchaigno** [comment]
test-gke

**Comment by pchaigno** [comment]
retest-4.19

**Comment by pchaigno** [comment]
retest-runtime

**Comment by tklauser** [comment]
retest-4.19

**Pull request merged**
