### PR TITLE
Pin bookinfo container image versions

### PR DESCRIPTION
**Pull request by joestringer**
We rely on specific contents of images in the 'bookinfo' tests, in                                                         
particular that the images contain the 'wget' binary. Pin the container                                                    
image versions in the manifests file to ensure that the tests don't                                                        
break because of upstream changes to the images. 

This currently blocks 1.0 backports.

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Clean CI run while running the relevant test, will now remove the focus change.

**Comment by joestringer** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Previous focus didn't work as intended. Retrying.

**Comment by joestringer** [comment]
OK, this time, successful run with the focus. Removing the focus patch.

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3083/execution/node/66/log/

**Comment by joestringer** [comment]
test-me-please

**Pull request merged**
