### PR TITLE
v1.7 backport for docs: re-design cilium docs theme

### PR DESCRIPTION
**Pull request by genbit**
Backport the new docs theme.
* #11803
* #12002 
* #12010 

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 11803 12002 12010; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
test-docs-please

**Comment by genbit** [comment]
@joestringer built it locally on my readthedocs - https://cilium-genbit.readthedocs.io/en/v1.7/gettingstarted/k8s-install-gke.html seems to work ok

**Review by aanm — CHANGES_REQUESTED** [review]
Let's keep the 1.7 untouched because this changes the UI a lot an usually UI shouldn't be changed for older versions as humans are used to navigate via patterns. If we change those patterns it will be difficult for us and users to find documentation pieces that we / they previously found in the past.

**Comment by genbit** [comment]
Main idea was to backport only 1.7 and 1.6 version, and keep older versions untouched, as majority of users are on these cilium versions and we want to avoid having a question that @joestringer mentioned:
>  I fully expect that if we don't backport, people will ask the question of whether the v1.7/v1.6 docs are maintained / up-to-date over the next 6 months.

**Comment by joestringer** [comment]
Let's hold off on actually merging this (and v1.6, https://github.com/cilium/cilium/pull/12040 ) until we do the full v1.8 release.

**Comment by joestringer** [comment]
test-docs-please

**Comment by aanm** [comment]
@genbit the docs failed to build:

```
08:04:27   ---> Running in 0405111d1e26
08:04:28  Removing intermediate container 0405111d1e26
08:04:28   ---> 9532fa804bc3
08:04:28  Step 9/10 : ADD _api $API_DIR
08:04:28   ---> 22cd63f81dd5
08:04:28  Step 10/10 : ADD . $DOCS_DIR
08:04:28   ---> a6fe72d07bc5
08:04:28  Successfully built a6fe72d07bc5
08:04:28  Successfully tagged cilium/docs-builder:latest
08:04:28  docker container rm -f docs-cilium >/dev/null 2>&1 || true
08:04:28  docker container run --rm -v $(pwd):/srv/ cilium/docs-builder /bin/bash -c 'make html'
08:04:29  /bin/sh: syntax error: unexpected word (expecting "do")
08:04:29  make: *** [Makefile:27: check-requirements] Error 2
08:04:29  Makefile:424: recipe for target 'test-docs' failed
08:04:29  make: *** [test-docs] Error 2
```

from https://jenkins.cilium.io/job/Cilium-PR-Doc-Tests/2248/

**Comment by joestringer** [comment]
test-docs-please

**Comment by joestringer** [comment]
test-docs-please

**Pull request merged**
