### PR TITLE
bpf: minor nodeport cleanups

### PR DESCRIPTION
**Pull request by julianwiedmann**
Just a few trivial cleanups from poking around in the lb code.

But as an added bonus, the first patch seems to help with complexity and brings https://github.com/cilium/cilium/pull/21539 back into play  (see https://github.com/cilium/cilium/pull/22312).

### CODE REVIEW

**Comment by julianwiedmann** [comment]
CI fails are all for `1.1.1.1` connectivity (eg. https://github.com/cilium/cilium/issues/22168, https://github.com/cilium/cilium/issues/22217).

**Review by NikAleksandrov — APPROVED** [review]

**Comment by aanm** [comment]
@julianwiedmann can you drop the merge commit? Thanks

**Comment by NikAleksandrov** [comment]
> @julianwiedmann can you drop the merge commit? Thanks
Sorry about that, it was my bad, did it by accident. I've also let Julian know.

**Comment by julianwiedmann** [comment]
Hitting https://github.com/cilium/cilium/issues/21710 in `ConformanceIngress`

**Pull request merged**
