### PR TITLE
[v1.14] Fix labels synchronization issues on Cilium

### PR DESCRIPTION
**Pull request by aanm**
- [x] #29248
- [x] #29615

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 29248 29615; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=29248,29615
```

### CODE REVIEW

**Comment by aanm** [comment]
/test-backport-1.14

**Review by mhofstetter — APPROVED** [review]
Thanks @aanm !

**Comment by aanm** [comment]
/test-backport-1.14

**Review by ti-mo — APPROVED** [review]

**Pull request merged**
