### PR TITLE
v1.12 backports 2023-02-28

### PR DESCRIPTION
**Pull request by pchaigno**
- [x] #23469 -- bpf: Fix usage of tunnel map structs (@pchaigno)
 - [x] #23590 -- Add leader requirement to watch from Etcd. (@marseel)
 - [x] #23947 -- clustermesh: fix services cache bloat due to incorrect deletion (@giorio94)
     - Trivial conflict in imports of the unit tests.
 - [ ] #23499 -- watchers: endpointsync can manage already owned CiliumEndpoints. (@tommyp1ckles)
 - [x] #24012 -- docs: Fix the dead link to Mellanox performance tuning guide (@gentoo-root)
 - [x] #24030 -- IPsec: Remove `IP_POOLS` logic (@pchaigno)
     - Trivial conflict in the docs.
     - Minor conflicts in bpf/bpf_host.c.
     - Major conflicts in commit that removed IP_POOLS. I mostly reapplied the changes since they are fairly straightforward: remove IP_POOLS and related logic.
     - Major conflicts in the commit to write the node ID into packet mark.
 - [x] #23441 -- helm: Add SA automount configuration (@sayboras)
     - (tam): Manually resolved conflict and pushed in this PR
 - [x] #23443 -- helm: Add pod and container security context (@sayboras)
     - (tam): Manually resolved conflict and pushed in this PR

Skipped due to conflicts:
 - [ ] #23915 -- agent: dump stack on stale probes (@squeed)
     - (tam): As we don't backport go version, there is compilation issue due to atomic.Int64 in status.go 

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 23469 23441 23590 23947 23499 23443 24012 24030; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.12

**Comment by sayboras** [comment]
/test-1.24-net-next

**Review by giorio94 — APPROVED** [review]
My commit looks good. Thanks!

**Comment by marseel** [comment]
My commit looks good too, thank you!

**Review by marseel — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-backport-1.12

**Review by gentoo-root — APPROVED** [review]
Approved for my commit.

**Comment by pchaigno** [comment]
I manually the connectivity tests on 3-nodes GKE, AKS, and VXLAN clusters with IPsec enabled to validate the backport. All looks good :tada:

**Comment by pchaigno** [comment]
k8s-1.23-kernel-4.9 hit known flake https://github.com/cilium/cilium/issues/23317. All other tests are passing. Reviews are in except for one PR without conflicts. Marking ready to merge.

**Pull request merged**
