### PR TITLE
v1.14 Backports 2024-07-15

### PR DESCRIPTION
**Pull request by giorio94**
* [x] #33283 (@bimmlerd) :warning: resolved conflicts
    * ⚠️ Fixed minor conflicts in allocateHealthIPs, due to different indentation, and extended the same changes to the IPv6 branch (coalescenceCIDR got removed there by https://github.com/cilium/cilium/commit/023818c9dade7a1e99852b617efc3faee0f7e159 as IPv6 is not supported in ENI mode).
 * [x] #33373 (@aditighag) :warning: resolved conflicts
    * ℹ️ Skipped https://github.com/cilium/cilium/commit/69e5edee4aa8cce140ece1838b6ee06b603ebd35, as codeowners changes are not propagated to stable branches.
 * [x] #33621 (@brb)
 * [x] #33626 (@giorio94)
 * [x] #33655 (@aditighag) :warning: resolved conflicts
    * ℹ️ Hit minor conflict due to different surrounding context; resolved accepting combination.
 * [x] #33683 (@sayboras) :warning: resolved conflicts
    * ℹ️ Hit minor conflicts, resolved adapting the upstream changes to the local structure.
 * [x] #33592 (@gandro) :warning: resolved conflicts
    * ℹ️ Hit minor conflict in pkg/defaults/defaults.go due to different surrounding context; resolved accepting combination. Adapted flag registration, changing `vp` to `Vp`. Additionally dropped the `values.schema.json` hunk, as not applicable in v1.14, and regenerated helm values documentation.
 * [ ] #33708 (@Mais316)
 * [x] #33679 (@giorio94) :warning: resolved conflicts
    * ℹ️ Hit conflict as v1.15 still used an old etcd image for integration tests; accepted the incoming changes, as we want to keep the etcd version up-to-date.
 * [ ] ~~#33769 (@pchaigno)~~
    * :x: Skipped, as causes the Cilium IPsec upgrade workflow to fail, and needs further investigation.
 * [x] #33735 (@giorio94) :warning: resolved conflicts
    * ℹ️ Hit minor conflict due to different surrounding context; resolved accepting combination.

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33283 33373 33621 33626 33655 33683 33592 33708 33679 33735
```

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Thank you!

**Review by brb — APPROVED** [review]
LGTM, thanks!

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commit

**Comment by giorio94** [comment]
Cilium IPsec upgrade seems pretty unhappy on downgrade. @pchaigno Could you please take a look?

**Review by aditighag — APPROVED** [review]
Looks good for my backports. Thanks!

**Comment by giorio94** [comment]
/test-backport-1.14

**Review by nebril — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Pull request merged**
