### PR TITLE
[1.6] Fix regression to avoid freeing alive IPs

### PR DESCRIPTION
**Pull request by tgraf**
Backport of https://github.com/cilium/cilium/pull/10207

```upstream-prs
$ for pr in 10207; do contrib/backporting/set-labels.py $pr done 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10237)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by aanm** [comment]
seems a real failure
```
# github.com/cilium/cilium/daemon
daemon/endpoint.go:388:2: unreachable code
make[1]: *** [govet] Error 2
make[1]: Leaving directory `/home/travis/gopath/src/github.com/cilium/cilium'
make: *** [unit-tests] Error 2
```

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by jrfastab — APPROVED** [review]
LGTM

**Review by joestringer — APPROVED** [review]

**Pull request merged**
