### PR TITLE
Use arbitrary non-root user in Dockerfile

### PR DESCRIPTION
**Pull request by brandshaide**
As a minor security improment this PR is introducing to use a arbitrary ( > `UID` 0) non-root user for launching processes in the container.

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by errordeveloper** [comment]
I believe this depends on https://github.com/cilium/cilium/pull/10531, which can be merged any time now actually.

It's probably best to set the UID in the pod, that way new image will remain compatible with old ways of deploying it that someone might have. Also, I'm not actually sure if Kubernetes picks up `USER` instruction from Dockerfile, have you tested that?

**Comment by brandshaide** [comment]
> It's probably best to set the UID in the pod, that way new image will remain compatible with old ways of deploying it that someone might have.

you mean like that? 

```
[...] 
securityContext:          
      # run container under uid 1000 (user id) and gid 1000 (group id)
       runAsUser: 1000
       fsGroup: 1000
         [...]
```

>  Also, I'm not actually sure if Kubernetes picks up `USER` instruction from Dockerfile, have you tested that?

yes, when I'm docker-inspecting underlying container(s) of respective pod(s) the `UID` is being reflected: 

```
"Config": {
            "Hostname": "cons-77454965b7-c8rpl",
            "Domainname": "",
            "User": "65534",
```

**Comment by brandshaide** [comment]
@errordeveloper how shall we proceed here? defining `UID` in the pod (see my comment above) and thus closing my PR? thx for your input :-)

**Comment by errordeveloper** [comment]
@brandshaide you can close the PR if you like, but ultimately this is still a very welcome change, it's just better to make it in the helm chart instead! Let me know if you need some help with that :)

**Comment by brandshaide** [comment]
@errordeveloper I'll take care of employing that in the chelm chart. and thanks in advance for your help 🙂 
As I had a look on the `PodSecurityPolicy` e. g. for the `agent`, there's already a respective  [definition](https://github.com/cilium/cilium/blob/035b95381b6b7362d36b6c5419d374f08be458f8/install/kubernetes/cilium/charts/agent/templates/podsecuritypolicy.yaml#L22) . So to clarify: shall I make this configurable via `values.yaml`, so the user can specify the `UID` he wants to have?

**Comment by brandshaide** [comment]
@errordeveloper I'll take care of employing that in the chelm chart. and thanks in advance for your help 🙂 

If I look at the `PodSecurityPolicy` as being defined e. g. for the agent, there's already a respective [definition](https://github.com/cilium/cilium/blob/035b95381b6b7362d36b6c5419d374f08be458f8/install/kubernetes/cilium/charts/agent/templates/podsecuritypolicy.yaml#L22). 

So just to clarify: shall I make this part configurable utilizing templating in the `values.yaml`?

**Comment by errordeveloper** [comment]
> So to clarify: shall I make this configurable via `values.yaml`, so the user can specify the `UID` he wants to have?

Actually, I am junk just a boolean would be best, e.g. `runAsUnprivilegedUser`, with default to `true`.

**Comment by brandshaide** [comment]
@errordeveloper I've moved the enforcement to the Helm chart, could you please have a look 🙂 ?

**Comment by nathanjsweet** [comment]
test-me-please

**Comment by errordeveloper** [comment]
@brandshaide thanks a lot, this LGTM overall. What type of manual tests did you run, if any?

**Comment by brandshaide** [comment]
> What type of manual tests did you run, if any?

@errordeveloper I've invoked a `helm template --dry-run` and didn't encounter any issues. Don't know if this is sufficient though...

**Comment by christarazi** [comment]
test-me-please

**Comment by brandshaide** [comment]
test-me-please

**Comment by aanm** [comment]
@brandshaide please follow the instructions provided as https://github.com/cilium/cilium/pull/10681#issuecomment-618994230

**Comment by brandshaide** [comment]
@aanm sry and thx for pointing out: done

**Comment by aanm** [comment]
test-me-please

**Comment by brandshaide** [comment]
`Checks service across nodes with L7 policy Tests NodePort with L7 Policy` has been failing not only on this PR apparently due to an timeout while `curling`: 

```
kubectl exec -n default testclient-x55bb -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 http://10.39.241.230:10080 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})
```
-> exit code 28 ( `CURLE_OPERATION_TIMEDOUT` )

**Comment by joestringer** [comment]
@brandshaide searching the name of the test in the issues:

https://github.com/cilium/cilium/issues?q=is%3Aissue+Checks+service+across+nodes+with+L7+policy+Tests+NodePort+with+L7+Policy+

I saw some similar reports, but the actual stacktrace showed a different failure.

I've filed https://github.com/cilium/cilium/issues/11235 to track this anyway, as I saw similar reports in the Slack #testing channel so it is likely that this failure is possible on master even without your changes.

Meanwhile, GKE is not a required check to merge so feel free to disregard (unless you'd like to dig into the failure and understand it more deeply, which you're welcome to do but not expected to do :-) )

**Comment by brandshaide** [comment]
> [...] feel free to disregard (unless you'd like to dig into the failure and understand it more deeply [...] 

@joestringer I'll dig into this... 😎

**Review by aanm — CHANGES_REQUESTED** [review]
Before merging we need to understand that this works. Currently it requires that global.psp is set, this is *not* set in our CI so we don't have a way to tell if Cilium can run as Non Root. #11140 needs to be merged first

**Comment by brandshaide** [comment]
@aanm how can we prevent this PR from being marked as stale (see above). This PR is being blocked by  #11140

**Comment by joestringer** [comment]
@brandshaide I added the pinned label to prevent stale bot from closing it.

**Comment by aanm** [comment]
@brandshaide I'm going to close this PR. PodSecurityPolicy will be removed in Kubernetes https://github.com/kubernetes/kubernetes/pull/90603

**Pull request closed without merging**
