### PR TITLE
[1.15] ci: Add IPsec leak detection for ci-ipsec-e2e

### PR DESCRIPTION
**Pull request by jschwinger233**
- [x] https://github.com/cilium/cilium/pull/32930 @jschwinger233 

```upstream-prs
 32930
```

### CODE REVIEW

**Comment by jschwinger233** [comment]
/test-backport-1.15

**Review by julianwiedmann — APPROVED** [review]
thank you!

**Review by pchaigno — APPROVED** [review]
LGTM assuming there were no conflicts.

**Pull request merged**
