### PR TITLE
workflows/ipsec: Cover Ingress

### PR DESCRIPTION
**Pull request by pchaigno**

### CODE REVIEW

**Review by brlbil — APPROVED** [review]

**Review by jschwinger233 — APPROVED** [review]

**Comment by julianwiedmann** [comment]
The v1.16 backport was [reverted](https://github.com/cilium/cilium/pull/36116), adjusting the labels so it doesn't get lost.

**Comment by julianwiedmann** [comment]
[Second time](https://github.com/cilium/cilium/pull/38930) lucky :crossed_fingers:

**Pull request merged**
