### PR TITLE
cmd/watchdogs: add health reporter to watchdog controller.

### PR DESCRIPTION
**Pull request by tommyp1ckles**
Watchdog already runs in a module, so we should add a health reporter so it appears in modular health status.

### CODE REVIEW

**Comment by tommyp1ckles** [comment]
cc: @derailed

**Review by derailed — APPROVED** [review]
@tommyp1ckles LG!

**Comment by tommyp1ckles** [comment]
pinging @thorn3r 🙂

**Review by thorn3r — APPROVED** [review]

**Pull request merged**
