### PR TITLE
v1.13 Backports 2024-02-12

### PR DESCRIPTION
**Pull request by sayboras**
* [ ] #30711 (@geakstr)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30711
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.13

**Review by michi-covalent — APPROVED** [review]

**Comment by sayboras** [comment]
/test-backport-1.13

**Comment by michi-covalent** [comment]
[test-1.22-4.19](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/438/): hit https://github.com/cilium/cilium/issues/25403

**Comment by michi-covalent** [comment]
/test-1.22-4.19

**Pull request merged**
