### PR TITLE
pkg/k8s: add DeepEqual code generation for Service

### PR DESCRIPTION
**Pull request by aanm**
DeepEqual of Service can be automatically generated by deepequal-gen,
so there is no reason to manually keep the equalness of this structure.

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by fristonio — APPROVED** [review]
LGTM :rocket:

**Review by christarazi — APPROVED** [review]

**Review by brb — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
