### PR TITLE
v1.12 Backports 2023-07-26

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #27002 (@michi-covalent)
 * [x] #27014 (@qmonnet)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 27002 27014; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=27002,27014
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.12

**Review by viktor-kurchenko — APPROVED** [review]

**Comment by nbusseneau** [comment]
Note for maintainers:

After merge, the following checks will need to be unmarked as required on `v1.12`:

- ingress-conformance-test

And the following checks will need to be marked as required instead:

- ConformanceIngress

**Review by qmonnet — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]
tyty

**Comment by joestringer** [comment]
@cilium/tophat, feel free to approve but I'll take care of merge after releases since I can then adjust the branch protection immediately afterwards.

**Review by youngnick — APPROVED** [review]

**Pull request merged**
