### PR TITLE
v1.8 backports 2020-06-04

### PR DESCRIPTION
**Pull request by tklauser**
* #11846 -- hubble: enable metrics before starting server (@aanm)
 * #11827 -- doc: Troubleshooting with Hubble (@gandro)
 * #11852 -- pkg/clustermesh: protect tests against concurrent access (@aanm)
 * #11851 -- k8s: Fix data race when setting node address (@tgraf)
 * #11858 -- ci: Change vagrant timeout mechanism (@nebril)
 * #11838 -- Fix live preview with Python 3.8 (@joestringer)
 * #10635 -- Fetch MTU from the nodeIP interface (@manuelbuil)
 * #11854 -- helm: Bump hubble-ui to v0.6.0 (@gandro)
 * #11860 -- Docs: update backport commands for jenkins builds (@nebril)
 * #11808 -- cocci: Detect unlogged missed tail calls (@pchaigno)
 * #11870 -- daemon: cancel daemon context on TearDownTest (@aanm)
 * #11830 -- Add anti-affinity for Cilium pods (@nebril)
 * #11793 -- eni: update limits list (@bpineau)
 * #11797 -- test: add retries to expected successful curl calls (@nebril)
 * #11693 -- ci: make docker images in ghaction (@nebril)
 * #11872 -- pkg/identity: protect LabelsSHA256 against concurrent initializations (@aanm)
 * #11863 -- service: Fix wrong localEndpoints count in HealthCheckNodePort (@gandro)
 * #11829 -- pkg/k8s: decrease CEP status initialization (@aanm)
 * #11795 -- Enable host firewall in kube-proxy-free CI (@pchaigno)
 * #11876 -- nodeinit: Use newly built image (@errordeveloper)
 * #11697 -- doc: Update the EKS getting started guide (@michi-covalent)
 * #11843 -- Add audit action to the policy verdict log (@ap4y)
 * #11879 -- docs: Include directions to restart pods in the k3s install guide (@seanmwinn)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 11846 11827 11852 11851 11858 11838 10635 11854 11860 11808 11870 11830 11793 11797 11693 11872 11863 11829 11795 11876 11697 11843 11879; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by tklauser** [comment]
test-backport-1.8

**Review by pchaigno — APPROVED** [review]
:+1: for my changes

**Comment by errordeveloper** [comment]
My changes look good!

**Comment by aanm** [comment]
test-missed-k8s

**Pull request merged**
