### PR TITLE
vagrant: Bump all Vagrant box versions

### PR DESCRIPTION
**Pull request by pchaigno**
These new VM images include a new Ubuntu 20.04.4 version and updated prepulled Docker images.

### CODE REVIEW

**Review by tklauser — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.21-5.4

**Comment by pchaigno** [comment]
/test-1.21-5.4

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
/test-1.21-5.4

**Review by ldelossa — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
I've excluded the net-next update for now as it seems we've hit a kernel regression.

**Comment by pchaigno** [comment]
All Jenkins tests are passing. Merging.

**Pull request merged**
