### PR TITLE
backports v1.7 2020-02-05

### PR DESCRIPTION
**Pull request by borkmann**
* #9977 -- CI: Add test for healthCheckNodePort in NodePort BPF (@gandro)
 * #10028 -- doc: update instructions about restarting pods after deployment (@Rolinh)
 * #10016 -- policy: clean a duplicated code (@zhiyuan0x)
 * #10053 -- tests: test nodeport connectivity via v4-in-v6 sockets (@borkmann)
 * #9808 -- Getting started guide to TLS-visibility (@danwent)
 * #10057 -- kubernetes: Disable LocalNodeRoute while chaining (@tgraf)
 * #10062 -- [CI] add release name to helm template calls (@nebril)
 * #10060 -- bpf: compile out service lookup entirely on kubeProxyReplacement=disa… (@borkmann)
 * #10066 -- ipam: Protect release from releasing alive IP (@tgraf)
 * #10047 -- test: Improve skipping of k8sT/Services.go tests (@brb)
 * #10069 -- docs: revamp kube-proxy-free gsg (@borkmann)
 * #9997 -- test/K8sServices: Add Tests for UDP connectivity (@gandro)
 * #10059 -- daemon: Add KubeProxyReplacement to cilium status cmd (@brb)
 * #10073 -- docs: document kube-proxy replacement modes (@borkmann)
 * #10051 -- CI: PolicyTest toEntities All (@raybejjani)
 * #10063 -- cli: Remove NodePort programs from native netdev upon cleanup (@brb)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 9977 10028 10016 10053 9808 10057 10062 10060 10066 10047 10069 9997 10059 10073 10051 10063; do contrib/backporting/set-labels.py $pr done 1.7; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10072)

### CODE REVIEW

**Comment by borkmann** [comment]
never-tell-me-the-odds

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-missed-k8s

**Comment by borkmann** [comment]
never-tell-me-the-odds

**Comment by borkmann** [comment]
provision error, retrying

**Comment by borkmann** [comment]
never-tell-me-the-odds

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by borkmann** [comment]
Maciej hinted that we need https://github.com/cilium/cilium/pull/10062 in this backport as well to get it working.

**Comment by borkmann** [comment]
never-tell-me-the-odds

**Review by aanm — APPROVED** [review]

**Pull request merged**
