### PR TITLE
GatewayAPI: Fix listener parsing

### LINKED ISSUE #27533: Gateway's Listener to Service is missing Port in Service LoadBalancer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am applying the following spec(s) in my cluster

IPAM pool and L2 Policy
```yaml
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  interfaces:
  - ^eth[0-9]+
  externalIPs: true
  loadBalancerIPs: true
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "test-pool"
spec:
  cidrs:
  - cidr: "172.16.0.128/29"
```

Gateway
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: default
  namespace: cilium-gw-system
  annotations: 
    cert-manager.io/issuer: ca-issuer
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: http
    allowedRoutes:
      kinds :
        - kind: HTTPRoute
      namespaces:
        from: All
  - protocol: HTTPS
    port: 443
    name: https
    hostname: test.example.com
    tls:
      mode: Terminate
      certificateRefs:
      - name: default-cert
    allowedRoutes:
      kinds:
        - kind: HTTPRoute
      namespaces:
        from: All
```

This will result in the following service being reconciled that is then clearly missing the :443 port from the listeners section of the Gateway.

Service
```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-08-16T12:22:33Z"
  labels:
    io.cilium.gateway/owning-gateway: default
  name: cilium-gateway-default
  namespace: cilium-gw-system
  ownerReferences:
  - apiVersion: gateway.networking.k8s.io/v1beta1
    kind: Gateway
    name: default
    uid: 21336fa3-ad07-48e0-b4c8-9ee250fdfb20
  resourceVersion: "748727"
  uid: ca62b55d-c4cf-480b-886e-c96334e68f56
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.17.28.155
  clusterIPs:
  - 172.17.28.155
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-443
    nodePort: 31739
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: LoadBalancer
status:
  conditions:
  - lastTransitionTime: "2023-08-16T12:22:33Z"
    message: ""
    reason: satisfied
    status: "True"
    type: io.cilium/lb-ipam-request-satisfied
  loadBalancer:
    ingress:
    - ip: 172.16.0.134

```

Gateway
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/issuer: ca-issuer
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.networking.k8s.io/v1beta1","kind":"Gateway","metadata":{"annotations":{"cert-manager.io/issuer":"ca-issuer"},"name":"default","namespace":"cilium-gw-system"},"spec":{"gatewayClassName":"cilium","listeners":[{"allowedRoutes":{"kinds":[{"kind":"HTTPRoute"}],"namespaces":{"from":"All"}},"name":"http","port":80,"protocol":"HTTP"},{"allowedRoutes":{"kinds":[{"kind":"HTTPRoute"}],"namespaces":{"from":"All"}},"hostname":"test.example.com","name":"https","port":443,"protocol":"HTTPS","tls":{"certificateRefs":[{"name":"default-cert"}],"mode":"Terminate"}}]}}
  creationTimestamp: "2023-08-16T12:22:33Z"
  generation: 1
  name: default
  namespace: cilium-gw-system
  resourceVersion: "748767"
  uid: 21336fa3-ad07-48e0-b4c8-9ee250fdfb20
spec:
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
      namespaces:
        from: All
    name: http
    port: 80
    protocol: HTTP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
      namespaces:
        from: All
    hostname: test.example.com
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: default-cert
      mode: Terminate
status:
  addresses:
  - type: IPAddress
    value: 172.16.0.134
  conditions:
  - lastTransitionTime: "2023-08-16T12:22:33Z"
    message: Gateway successfully scheduled
    observedGeneration: 1
    reason: Accepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2023-08-16T12:22:33Z"
    message: Gateway successfully reconciled
    observedGeneration: 1
    reason: Programmed
    status: "True"
    type: Programmed
  listeners:
  - attachedRoutes: 1
    conditions:
    - lastTransitionTime: "2023-08-16T12:22:33Z"
      message: Listener Programmed
      observedGeneration: 1
      reason: Programmed
      status: "True"
      type: Programmed
    - lastTransitionTime: "2023-08-16T12:22:33Z"
      message: Listener Accepted
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    name: http
    supportedKinds:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
  - attachedRoutes: 1
    conditions:
    - lastTransitionTime: "2023-08-16T12:22:33Z"
      message: Listener Programmed
      observedGeneration: 1
      reason: Programmed
      status: "True"
      type: Programmed
    - lastTransitionTime: "2023-08-16T12:22:33Z"
      message: Listener Accepted
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    name: https
    supportedKinds:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute

```

### Cilium Version

1.14.1

### Kernel Version

Oracle Linux Server 8.8 - 5.15.0-103.114.4.el8uek.x86_64

### Kubernetes Version

v1.27.4+k3s1

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Managarmrr**
Previously, parsing the listeners of a Gateway object only worked correctly, if only one listener of a given type (HTTP or TLS) was present, as looping over them was incorrectly handled.

Fixes: #27533
Fixes: 677e8b49481c ("Implement TLSRoute")

```release-note
Fix Gateway managed services not exposing all ports
```

### CODE REVIEW

**Comment by joestringer** [comment]
Hi @Managarmrr , thanks for the contribution. I can't speak for the details, will leave review up to the assigned CODEOWNERS. But I will point out one thing - Cilium relies on linear git history, so before accepting this PR the merge commit will need to be dropped. Consider either rebasing against tip of main + force pushing the PR to update, or use the drop-down from "update branch" at the bottom of the page to do a rebase against the main branch.

I've kicked off the initial testsuites to give CI feedback for now.

**Comment by Managarmrr** [comment]
> Hi @Managarmrr , thanks for the contribution. I can't speak for the details, will leave review up to the assigned CODEOWNERS. But I will point out one thing - Cilium relies on linear git history, so before accepting this PR the merge commit will need to be dropped. Consider either rebasing against tip of main + force pushing the PR to update, or use the drop-down from "update branch" at the bottom of the page to do a rebase against the main branch.
> 
> I've kicked off the initial testsuites to give CI feedback for now.

Thanks for the heads up, for some reson I expected GitHub to perform a rebase on main when I pressed that button. Fixed it now.

**Review by meyskens — APPROVED** [review]
Good catch! LGTM, thanks :)

**Comment by meyskens** [comment]
(sorry for the label remove and add, pressed the wrong buttons i trust on the bot here)

**Pull request merged**
