### PR TITLE
Update netlink library to not set XFRMA_IF_ID = 0 by default

### LINKED ISSUE #18500: CI: RuntimePrivilegedUnitTests Run Tests EncryptStatusSuite.TestCountUniqueIPsecKeys value syscall.Errno = 0x16 ("invalid argument")
### Test Name
```test-name
RuntimePrivilegedUnitTests Run Tests
```

### Failure Output
```failure-output
FAIL: Failed to run privileged unit tests
```

### Stacktrace
<details><summary>Click to show.</summary>

```stack-trace
/home/jenkins/workspace/Cilium-PR-Runtime-net-next/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:527
Failed to run privileged unit tests
Expected command: sudo make -C /home/vagrant/go/src/github.com/cilium/cilium/ tests-privileged 
To succeed, but it failed:
Exitcode: 2 
Err: Process exited with status 2
Stdout:
 	 make: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 make init-coverage
	 make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 echo "mode: count" > coverage-all-tmp.out
	 echo "mode: count" > coverage.out
	 make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 for pkg in github.com/cilium/cilium/cilium/cmd github.com/cilium/cilium/daemon/cmd github.com/cilium/cilium/pkg/bpf github.com/cilium/cilium/pkg/datapath/link github.com/cilium/cilium/pkg/datapath/linux github.com/cilium/cilium/pkg/datapath/linux/config github.com/cilium/cilium/pkg/datapath/linux/ipsec github.com/cilium/cilium/pkg/datapath/linux/probes github.com/cilium/cilium/pkg/datapath/linux/route github.com/cilium/cilium/pkg/datapath/linux/routing github.com/cilium/cilium/pkg/datapath/loader github.com/cilium/cilium/pkg/egressgateway github.com/cilium/cilium/pkg/fqdn/dnsproxy github.com/cilium/cilium/pkg/maps/ctmap github.com/cilium/cilium/pkg/maps/egressmap github.com/cilium/cilium/pkg/maps/eppolicymap github.com/cilium/cilium/pkg/maps/lbmap github.com/cilium/cilium/pkg/maps/policymap github.com/cilium/cilium/pkg/modules github.com/cilium/cilium/pkg/mountinfo github.com/cilium/cilium/pkg/mtu github.com/cilium/cilium/pkg/redirectpolicy github.com/cilium/cilium/pkg/sysctl; do \
	 	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/vagrant/go/src/github.com/cilium/cilium/bpf go test  -mod=vendor -tags=osusergo,privileged_tests -ldflags "-X github.com/cilium/cilium/pkg/kvstore.consulDummyAddress=https://consul:8443 -X github.com/cilium/cilium/pkg/kvstore.etcdDummyAddress=http://etcd:4002 -X github.com/cilium/cilium/pkg/datapath.DatapathSHA256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" $pkg -test.v -timeout 600s -check.vv  -covermode=count -coverprofile=coverage.out -coverpkg ./... \
	 	|| exit 1; \
	 	tail -n +2 coverage.out >> coverage-all-tmp.out; \
	 done
	 === RUN   Test
	 START: encrypt_status_test.go:49: EncryptStatusSuite.TestCountUniqueIPsecKeys
	 encrypt_status_test.go:58:
	     c.Assert(err, IsNil)
	 ... value syscall.Errno = 0x16 ("invalid argument")
	 
	 FAIL: encrypt_status_test.go:49: EncryptStatusSuite.TestCountUniqueIPsecKeys
	 
	 START: encrypt_status_test.go:77: EncryptStatusSuite.TestGetXfrmStats
	 PASS: encrypt_status_test.go:77: EncryptStatusSuite.TestGetXfrmStats	0.000s
	 
	 OOPS: 1 passed, 1 FAILED
	 --- FAIL: Test (0.00s)
	 FAIL
	 coverage: 2.0% of statements in ./...
	 FAIL	github.com/cilium/cilium/cilium/cmd	0.102s
	 FAIL
	 make: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 
Stderr:
 	 make: *** [Makefile:138: tests-privileged] Error 1
	 

/home/jenkins/workspace/Cilium-PR-Runtime-net-next/runtime-gopath/src/github.com/cilium/cilium/test/runtime/privileged_tests.go:46
```
</details>

### Standard Output
<details><summary>Click to show.</summary>

```stack-output


```
</details>

### Standard Error
<details><summary>Click to show.</summary>

```stack-error
10:15:00 STEP: Running BeforeAll block for EntireTestsuite RuntimePrivilegedUnitTests
FAIL: Failed to run privileged unit tests
Expected command: sudo make -C /home/vagrant/go/src/github.com/cilium/cilium/ tests-privileged 
To succeed, but it failed:
Exitcode: 2 
Err: Process exited with status 2
Stdout:
 	 make: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 make init-coverage
	 make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 echo "mode: count" > coverage-all-tmp.out
	 echo "mode: count" > coverage.out
	 make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 for pkg in github.com/cilium/cilium/cilium/cmd github.com/cilium/cilium/daemon/cmd github.com/cilium/cilium/pkg/bpf github.com/cilium/cilium/pkg/datapath/link github.com/cilium/cilium/pkg/datapath/linux github.com/cilium/cilium/pkg/datapath/linux/config github.com/cilium/cilium/pkg/datapath/linux/ipsec github.com/cilium/cilium/pkg/datapath/linux/probes github.com/cilium/cilium/pkg/datapath/linux/route github.com/cilium/cilium/pkg/datapath/linux/routing github.com/cilium/cilium/pkg/datapath/loader github.com/cilium/cilium/pkg/egressgateway github.com/cilium/cilium/pkg/fqdn/dnsproxy github.com/cilium/cilium/pkg/maps/ctmap github.com/cilium/cilium/pkg/maps/egressmap github.com/cilium/cilium/pkg/maps/eppolicymap github.com/cilium/cilium/pkg/maps/lbmap github.com/cilium/cilium/pkg/maps/policymap github.com/cilium/cilium/pkg/modules github.com/cilium/cilium/pkg/mountinfo github.com/cilium/cilium/pkg/mtu github.com/cilium/cilium/pkg/redirectpolicy github.com/cilium/cilium/pkg/sysctl; do \
	 	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/vagrant/go/src/github.com/cilium/cilium/bpf go test  -mod=vendor -tags=osusergo,privileged_tests -ldflags "-X github.com/cilium/cilium/pkg/kvstore.consulDummyAddress=https://consul:8443 -X github.com/cilium/cilium/pkg/kvstore.etcdDummyAddress=http://etcd:4002 -X github.com/cilium/cilium/pkg/datapath.DatapathSHA256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" $pkg -test.v -timeout 600s -check.vv  -covermode=count -coverprofile=coverage.out -coverpkg ./... \
	 	|| exit 1; \
	 	tail -n +2 coverage.out >> coverage-all-tmp.out; \
	 done
	 === RUN   Test
	 START: encrypt_status_test.go:49: EncryptStatusSuite.TestCountUniqueIPsecKeys
	 encrypt_status_test.go:58:
	     c.Assert(err, IsNil)
	 ... value syscall.Errno = 0x16 ("invalid argument")
	 
	 FAIL: encrypt_status_test.go:49: EncryptStatusSuite.TestCountUniqueIPsecKeys
	 
	 START: encrypt_status_test.go:77: EncryptStatusSuite.TestGetXfrmStats
	 PASS: encrypt_status_test.go:77: EncryptStatusSuite.TestGetXfrmStats	0.000s
	 
	 OOPS: 1 passed, 1 FAILED
	 --- FAIL: Test (0.00s)
	 FAIL
	 coverage: 2.0% of statements in ./...
	 FAIL	github.com/cilium/cilium/cilium/cmd	0.102s
	 FAIL
	 make: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 
Stderr:
 	 make: *** [Makefile:138: tests-privileged] Error 1
	 

=== Test Finished at 2022-01-17T10:16:08Z====
10:16:08 STEP: Running AfterEach for block EntireTestsuite

[[ATTACHMENT|830c66c2_RuntimePrivilegedUnitTests_Run_Tests.zip]]
10:16:08 STEP: Running AfterAll block for EntireTestsuite RuntimePrivilegedUnitTests
10:16:08 STEP: Restarting Cilium


```
</details>

ZIP Links: 
<details><summary>Click to show.</summary>

 https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next//1026/artifact/830c66c2_RuntimePrivilegedUnitTests_Run_Tests.zip
  https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next//1026/artifact/test_results_Cilium-PR-Runtime-net-next_1026_BDD-Test-PR.zip
 
</details>

Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1026/

If this is a duplicate of an existing flake, comment 'Duplicate of #\<issue-number>' and close this issue.

### PR DESCRIPTION
**Pull request by tklauser**
(previous PR title: `Fix EncryptStatusSuite.TestCountUniqueIPsecKeys`)

As of Linux kernel commit https://github.com/torvalds/linux/commit/68ac0f3810e7 ("xfrm: state and
policy should fail if XFRMA_IF_ID 0"), specifying xfrm if_id = 0 leads
to EINVAL being returned. So far, the netlink library always specified
the XFRMA_IF_ID netlink attribute, regardless of its value. Upstream PR
https://github.com/vishvananda/netlink/pull/727 changed this behavior to
only set XFRMA_IF_ID in case XfrmState.Ifid or XfrmPolicy.Ifid are != 0
to fix the issue.

Updated using:

    go get github.com/vishvananda/netlink@main
    go mod tidy
    go mod vendor

Fixes: #18500

### CODE REVIEW

**Comment by pchaigno** [comment]
Regarding backport labels, the test doesn't exist in v1.10.

**Review by pchaigno — APPROVED** [review]
Nice catch! How did you find this so quickly?

**Comment by tklauser** [comment]
> Nice catch! How did you find this so quickly?

`git bisect run` :wink:

**Comment by tklauser** [comment]
There is another legitimate failure in `pkg/datapath/linux/ipsec`: https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1043/

I think this needs to be fixed in the netlink library to only set the `XFRMA_IF_ID` attribute if it is not 0. I've opened https://github.com/vishvananda/netlink/pull/727 doing that.

**Comment by tklauser** [comment]
Dropped the second commit explicitly setting `XfrmState.IfId` to 1 and instead added a commit updating the `github.com/vishvananda/netlink` library to pull in https://github.com/vishvananda/netlink/pull/727.

**Review by rolinh — APPROVED** [review]

**Comment by pchaigno** [comment]
Runtime tests are passing. Reviews are in. Marking ready to merge.

**Comment by pchaigno** [comment]
We also need to backport this to v1.10 to fix the EKS workflow there (cf. https://github.com/cilium/cilium/runs/5405780998?check_suite_focus=true).

**Comment by tklauser** [comment]
> The title is a bit misleading here. IIRC, this pull request doesn't only fix the test.

Good point. The title still stems from the initial fix which was made before the actual cause of the issue was known. I'll change the PR title/description accordingly.

**Pull request merged**
