### PR TITLE
cilium: encryption, fixes for encrypt-node mode

### PR DESCRIPTION
**Pull request by jrfastab**
Fixes needed to get CI running encrypt-node tests.

The following improvements are made,
 * Specify local addr (e.g. src) in node route for peer nodes so  that we use node IP for source IP
 * Add iptables rule to translate source IP chosen from default route when sending to service IP, this is specific to vagrant setup.
 * Add CI test

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8737)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by jrfastab** [comment]
Timed-out during container creation. I'm going to retry now that we changed the timers.
```
00:07:09      Pods are not ready after timeout
[2019-07-31T07:07:09.664Z]     Expected
[2019-07-31T07:07:09.664Z]         <*errors.errorString | 0xc0004b9f00>: {
[2019-07-31T07:07:09.664Z]             s: "Timeout reached: timed out waiting for pods with filter  to be ready",
[2019-07-31T07:07:09.664Z]         }
[2019-07-31T07:07:09.664Z]     to be nil
00:07:09  
```
```
00:05:23   	 NAMESPACE     NAME                                    READY     STATUS              RESTARTS   AGE       IP              NODE
00:05:23  	 default       testclient-4sg2k                        1/1       Running             0          4m        10.10.0.239     k8s1
00:05:23  	 default       testclient-nbk48                        0/1       ContainerCreating   0          4m        <none>          k8s2
00:05:23  	 default       testds-f8gz5                            1/1       Running             0          4m        10.10.0.72      k8s1
00:05:23  	 default       testds-rxqqh                            0/1       ContainerCreating   0          4m        <none>      
```

**Comment by jrfastab** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
Updates: Added iptables rule patch (https://github.com/cilium/cilium/pull/8737/commits/5d3fe3415922f7f99531335257665976f72cadbb) to use local node IP for source IP when default route is chosen when sending to service IP. Pushed FIB lookup fixes via another fixes branch for backporting.

**Comment by jrfastab** [comment]
git fetch timeout errors retrying.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
forgot to add iptables rule to provisioning scripts only added to Vagrantfile.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
convert iptables MASQ -> SNAT --to rule

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
seems route cleanup failed and broke the test following encrypt-node test.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
Last test-me-please was not run and the one before that seems to have not completed but I dont see any errors in jenkins pipeline. Retry again maybe we can get the log this is passing in my local ginkgo runs now.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
oops the added CI test here only works on kernels with fib lookup support. Otherwise MAC address rewrite doesn't happen and packets get dropped. :( Disable old kernels by adding net-next check to test.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
from test-me-please seems it didn't kick ginko-tests trying again

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
Got a `stderr: /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/.git: No space left on device` error

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
last test-me-please did not provision either, did a force push and retrying.

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Pull request closed without merging**
