### PR TITLE
test: Move service-proxy-name to unit test

### PR DESCRIPTION
**Pull request by brb**
Instead of having the dedicated CI test case to test service-proxy-name
functionality, create a unit test with the fake client-go instance to
test whether the label filtering is working properly.

This is part of ongoing work to reduce the k8sT/Services.go size and
flakiness.

### CODE REVIEW

**Comment by brb** [comment]
/test-1.23-net-next

**Comment by brb** [comment]
/test-1.23-net-next

**Comment by brb** [comment]
The relevant CI tests have passed. Ready for the review.

**Review by kkourt — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by brb** [comment]
/test-1.22-4.19

**Comment by brb** [comment]
/test-1.22-4.19

**Pull request merged**
