### PR TITLE
Fix CIDR ingress lookup

### PR DESCRIPTION
**Pull request by joestringer**

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
```
04:04:13     k8s2-1.10: E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
04:04:13     k8s2-1.10: E: Unable to lock directory /var/lib/apt/lists/
04:04:13 The SSH command responded with a non-zero exit status. Vagrant
04:04:13 assumes that this means the command failed. The output for this command
04:04:13 should be in the log above. Please read the output to determine what
04:04:13 went wrong.
```

**Pull request merged**
