### PR TITLE
loader: remove stale tc filters with a different priority

### LINKED ISSUE #36172: connectivity impact after changing bpf filter priority
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

Saw on cilium v1.14.15 and v1.16.2 in AKS cluster and with latest cilium in kind cluster

After changing the `bpf-filter-priority` in config from default value of `1`, the original tc egress and ingress filters and bpf programs attached to interface do not get cleaned up. Duplicates of these filters are added at the new priority and nodes fall into a notready state where connectivity is lost and kubelet stops reporting status. 

### How can we reproduce the issue?

1. Create cluster with cilium v1.14.15
3. After cilium is up and running, set `bpf-filter-priority: 2`
4. Restart cilium daemonset

Note: if repro is on a later cilium version the config must also have `enable-tcx: false` and `enable-node-port: true`

### Cilium Version

Cilium v1.14.15, v1.16.2

### Kernel Version

5.15.0-1074-azure

### Kubernetes Version

Kubernetes v1.29 (with cilium v1.14.15) and v1.31 (with cilium v1.16.2)

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

@tamilmani1989 is working on the fix for this issue 

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tamilmani1989**
The fix is to check if duplicate filter attached to same interface with same filter name but different priority and removes the old filter.

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

```release-note
Fix connectivity issue caused by stale cilium eBPF program when using --bpf-filter-priority
```

Fixes: #36172

### CODE REVIEW

**Comment by tamilmani1989** [comment]
@cilium/loader can I get review on this PR?

**Review by ti-mo — APPROVED** [review]

**Comment by ti-mo** [comment]
@tamilmani1989 I changed the PR to take a slightly different approach: we reuse the same logic to detect if there's already an active Cilium prog attached to the current device+qdisc and delete all Cilium progs with a different priority. 

Had to bump the minimum prio to 1 to make tests work, as they all run with option.Config.TCFilterPriority set to 0, which makes the kernel auto-assign a priority. I made the priority configurable in `upsertTCProgram` to make it testable, and added a test targeting the specific behaviour.

I had to rebase and some flakes popped up. I started some retries, but we might have to rebase and re-run in a few days to get this to pass.

**Comment by tamilmani1989** [comment]
@ti-mo can we backport this to 1.16?

**Pull request merged**
