### PR TITLE
v1.7: Provide option to avoid DROP_INVALID_IDENTITY during upgrade from v1.6 to later Cilium versions

### PR DESCRIPTION
**Pull request by joestringer**
*  Allow tunnel traffic "from host" with remote-node-identity=false

    According to the documentation:

        One can set enable-remote-node-identity=false in the ConfigMap to
        retain the Cilium 1.6.x behavior.

    The above is true when evaluating policy, but not true from the
    DROP_INVALID_IDENTITY perspective as during an upgrade from v1.6 to
    v1.7, v1.6 nodes may send traffic to v1.7 nodes with the "host" identity
    and the v1.7 nodes will drop such traffic with this error code. Mitigate
    this by also covering this datapath case with the
    `EnableRemoteNodeIdentity` flag check.

* Add hidden `allow-remote-src` flag

    This flag allows to override the default setting for whether to accept
    traffic into a node if the source node reports the source identity as
    "host". Default is "auto" - to allow if enableRemoteNodeIdentity is
    disabled; deny if enableRemoteNodeIdentity is enabled. If specified
    directly, it will take on the configured behaviour (allow such traffic
    if true, otherwise drop it).

Backported for `bpf.sha` rebase, daemon arg changes.

~Related: #12998~

```release-note
Fix packet loss issues when running Cilium v1.6 and v1.7 in the same cluster concurrently with --enable-remote-node-identity=false
```

### CODE REVIEW

**Comment by joestringer** [comment]
test-backport-1.7

**Comment by joestringer** [comment]
test-backport-1.7

**Comment by joestringer** [comment]
test-backport-1.7

**Review by pchaigno — APPROVED** [review]
LGTM!

(The `ifdef`s totally bugged me on the first PR, given Chris said he tested the patch. All good now :-)

**Comment by pchaigno** [comment]
Shouldn't we document this flag in the upgrade guide though (and/or set it via the Helm chart for upgrade path)?

**Comment by joestringer** [comment]
> Shouldn't we document this flag in the upgrade guide though (and/or set it via the Helm chart for upgrade path)?

The primary goal here is to make the code conform with the documentation: That is, with `--enable-remote-node-identity=false`, there is no behavioural difference from v1.6.

The hidden flag is provided as an override in case we really need a knob. Users should not need to know about this unless there is some special condition in which we can let them know to configure in a configmap.

**Review by christarazi — APPROVED** [review]
LGTM and validated against a split-version (v1.6 & v1.7) cluster.

**Comment by joestringer** [comment]
Regular ginkgo tests hit known flakes #12777 , #12994

**Comment by joestringer** [comment]
Only Istio 1.5.9 failure in k8s tests, github infrastructure issue. Given the changes are unrelated and the only failures are known flakes, this is good to merge.

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3461/testReport/junit/Suite-k8s-1/16/K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter_service_connectivity/

**Pull request merged**
