### PR TITLE
[v1.3] test: make function provided to WithTimeout run asynchronously

### PR DESCRIPTION
**Pull request by ianvernon**
[ upstream commit 149998951b493fea232dbe24d57c38f4998c9b54 ]

The provided function was previously ran in the same goroutine as that which
would fail upon timeout. If the function itself took longer than the amount of
time in the timeout, or got stuck, the timeout would never get hit because it
was running in the same goroutine as the function itself. So, run the function
in a goroutine and return the result via a channel, which we can select upon. If
the timeout is hit before the function exits, `WithTimeout` will now return an
error as expected instead of waiting forever.

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7881)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
K8s tests failed : https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1953/

This is because the upgrade tests ran first.

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Boot VMs timed out: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11956/

**Comment by ianvernon** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by ianvernon** [comment]
test-docs-please

**Pull request merged**
