### PR TITLE
Fix up install make target

### PR DESCRIPTION
**Pull request by joestringer**
Recent changes in #10177 added an ineffective statement and broke install when the quiet variable was specified, fix them up.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10320)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by raybejjani** [comment]
This might need to be rebased onto master if it keeps flaking with pod delete errors (the fix for that is https://github.com/cilium/cilium/pull/10325 but was only merged 2 hours ago)

**Comment by aanm** [comment]
> This might need to be rebased onto master if it keeps flaking with pod delete errors (the fix for that is #10325 but was only merged 2 hours ago)

I thought jenkins was smart enough to rebase stuff on every PR?

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
