### PR TITLE
Upgrade k8s libraries to 1.13.0-rc.1

### PR DESCRIPTION
**Pull request by aanm**
Usually there aren't significantly differences between RCs in k8s so it's better to update the libraries so we can catch possible bugs earlier.

```release-note
Add support for Kubernetes 1.13
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6353)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

hit https://github.com/cilium/cilium/issues/6122 in k8s 1.9

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Review by tgraf — APPROVED** [review]

**Pull request merged**
