### PR TITLE
daemon: cleanup daemon fields

### PR DESCRIPTION
**Pull request by mhofstetter**
This commit cleans up the fields from the daemon and daemonParams
struct:

- `EgressGatewayManager` (unused - removed from daemon and daemonParams)
- `HealthProvider` (unused - removed from daemon and daemonParams)
- `DeviceManager` (keep in daemonParams)
- `EndpointManager` (set when initializing daemon struct)

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]
LGTM

**Comment by mhofstetter** [comment]
rebased to `main` to pick up some fixes for the failing Gateway API checks :pray:

**Pull request merged**
