### PR TITLE
v1.4 backports 2019 01 28

### PR DESCRIPTION
**Pull request by joestringer**
* #6726
  * Required a `make -C examples/kubernetes` to cleanly apply diff
* #6745
* #6759
* #6769
* #6773
* #6777
* #6785
* #6787
* #6794
* #6797
* #6798
* #6799
* #6805
* #6806
* #6808
* #6809
  * Depended on a35399e6c6a995c929bf36b66e4915f9efcbb46f (backported here)
* #6811
  * Depended on 1e91684f22474b44ced8cd9ed8fc72aa1a86e05b (backported here)
* #6814
* #6817
* #6827

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6832)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

EDIT: Failure:
```
23:42:52     k8s1-1.8: docker build --build-arg LOCKDEBUG=1 --build-arg V= -t "cilium/cilium:"latest"" .
23:42:53     k8s1-1.8: error checking context: 'file ('/home/vagrant/go/src/github.com/cilium/cilium/bpf/bpf_lxc.ll-58cb08bf') not found or excluded by .dockerignore'.
23:42:53     k8s1-1.8: Makefile:139: recipe for target 'docker-image-no-clean' failed
23:42:53     k8s1-1.8: make: *** [docker-image-no-clean] Error 1
```

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9440/execution/node/80/log/

Re-running to see if this recurs.

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
K8s upstream tests failed downloading the VM: https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/1070/execution/node/33/log/

Trying again.

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
Doc failure also affects master:
```
02:50:17 WARNING: Found 14 misspelled words
02:50:17 WARNING: Not copying tabs assets! Not compatible with spelling builder
02:50:17 Please fix the following spelling mistakes:
02:50:17 * Documentation/cmdref/cilium.md:28: (fqdn) 
02:50:17 * Documentation/cmdref/cilium_fqdn.md:3: (fqdn) 
02:50:17 * Documentation/cmdref/cilium_fqdn.md:5: (fqdn) 
02:50:17 * Documentation/cmdref/cilium_fqdn.md:9: (fqdn) 
02:50:17 * Documentation/cmdref/cilium_fqdn.md:32: (fqdn) 
02:50:17 * Documentation/cmdref/cilium_fqdn_cache.md:3: (fqdn) 
02:50:17 * Documentation/cmdref/cilium_fqdn_cache.md:5: (fqdn) 
02:50:17 * Documentation/cmdref/cilium_fqdn_cache.md:9: (fqdn) 
02:50:17 * Documentation/cmdref/cilium_fqdn_cache.md:31: (fqdn) 
02:50:17 * Documentation/cmdref/cilium_fqdn_cache.md:32: (fqdn) 
02:50:17 * Documentation/cmdref/cilium_fqdn_cache_clean.md:3: (fqdn) 
02:50:17 * Documentation/cmdref/cilium_fqdn_cache_clean.md:5: (fqdn) 
02:50:17 * Documentation/cmdref/cilium_fqdn_cache_clean.md:9: (fqdn) 
02:50:17 * Documentation/cmdref/cilium_fqdn_cache_clean.md:33: (fqdn) 
02:50:17 If the words are not misspelled, add them to Documentation/spelling_wordlist.txt.
```

**Comment by ianvernon** [comment]
K8s tests failed: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1571/

etcd-operator couldn't get started in time.

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Review by aanm — APPROVED** [review]
LGTM for my commits

**Comment by brb** [comment]
Backporting https://github.com/cilium/cilium/pull/6837 should fix the docs failure.

**Comment by ianvernon** [comment]
https://github.com/cilium/cilium/pull/6837 can be backported in the next round of backports ; merging this since all tests passed and the known issue with docs is a trivial fix.

**Pull request merged**
