### PR TITLE
workflows: various fixes & consistency passes

### PR DESCRIPTION
**Pull request by nbusseneau**
Please see individual commits :)

tested in https://github.com/cilium/cilium/pull/16634

### CODE REVIEW

**Comment by nbusseneau** [comment]
Marking as draft until we release CLI v0.8.1 (hotfix to v0.8).

**Review by nebril — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
LGTM but the title of this PR needs to be updated, no? It's no longer updating the CLI version.

**Comment by nebril** [comment]
This seems to still be failing in https://github.com/cilium/cilium/pull/16634 , blocking this PR until investigating what's wrong there

**Comment by nbusseneau** [comment]
Closing in favor of #16787.

**Pull request closed without merging**
