### PR TITLE
v1.13 Backports 2024-07-03

### PR DESCRIPTION
**Pull request by sayboras**
* [x] #33403 (@sayboras)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33403
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.13

**Comment by sayboras** [comment]
/test-1.16-4.19

**Comment by sayboras** [comment]
/test-1.17-4.19

**Comment by sayboras** [comment]
/test-1.21-4.19

**Comment by sayboras** [comment]
/test-1.23-4.19

**Comment by sayboras** [comment]
/test-1.23-4.19

**Comment by sayboras** [comment]
/test-1.26-net-next

**Comment by sayboras** [comment]
/test-1.17-4.19

**Comment by sayboras** [comment]
/test-1.26-net-next

**Review by dylandreimerink — APPROVED** [review]

**Comment by sayboras** [comment]
/test-1.17-4.19

**Pull request merged**
