### PR TITLE
Revert "workflow: yaml change - change "cosign attach" to "cosign attest""

### PR DESCRIPTION
**Pull request by aanm**
Reverts cilium/cilium#30823

### CODE REVIEW

**Comment by aanm** [comment]
@umesh3034 I had to revert the changes made in https://github.com/cilium/cilium/pull/30823 since it broke the CI with the error:
```
Run cosign attest sbom --sbom sbom_ci_pr_docker-plugin_81fe381f406c566960231d14deb65045973a75fb.spdx quay.io/cilium/docker-plugin-ci@sha256:f718e1389ef82de91909406d99479c88fddeb0b3517addbb946b48b71c3ab15b
Error: unknown flag: --sbom
main.go:74: error during command execution: unknown flag: --sbom
Error: Process completed with exit code 1.
```
from https://github.com/cilium/cilium/actions/runs/7945159264/job/21691833560?pr=30826

**Review by brlbil — APPROVED** [review]

**Review by viktor-kurchenko — APPROVED** [review]

**Comment by umesh3034** [comment]
> @umesh3034 I had to revert the changes made in #30823 since it broke the CI with the error:
> 
> ```
> Run cosign attest sbom --sbom sbom_ci_pr_docker-plugin_81fe381f406c566960231d14deb65045973a75fb.spdx quay.io/cilium/docker-plugin-ci@sha256:f718e1389ef82de91909406d99479c88fddeb0b3517addbb946b48b71c3ab15b
> Error: unknown flag: --sbom
> main.go:74: error during command execution: unknown flag: --sbom
> Error: Process completed with exit code 1.
> ```
> 
> from https://github.com/cilium/cilium/actions/runs/7945159264/job/21691833560?pr=30826

@aanm , i will check this.

**Comment by umesh3034** [comment]
@aanm , apologies for the breakage. Is there a doc to show how to run Manual CI jobs?

**Comment by aanm** [comment]
> @aanm , apologies for the breakage. Is there a doc to show how to run Manual CI jobs?

@umesh3034 you can try running it from your forked repository? The problem was that the GH workflows don't run PR changes from a fork. I would suggest to create a new PR with the new changes and then I can mirror the PR and open another PR from a branch within cilium/cilium to test the changes. Ping me on the new PR if you end up opening it.

**Comment by umesh3034** [comment]
@aanm 
I tried doing changes for the #30823 again (cosign attest), but this would mean changes for scripts using .sbom to use .att artifacts. Based on https://github.com/sigstore/cosign/issues/2755 issue this would be harder to do and more breakages can happen.
Do we need to pursue https://github.com/cilium/cilium/issues/30664 at this point if older versions of cosign will be used for sbom creation?

**Comment by aanm** [comment]
> @aanm I tried doing changes for the #30823 again (cosign attest), but this would mean changes for scripts using .sbom to use .att artifacts. Based on [sigstore/cosign#2755](https://github.com/sigstore/cosign/issues/2755) issue this would be harder to do and more breakages can happen. Do we need to pursue #30664 at this point if older versions of cosign will be used for sbom creation?

@umesh3034 sorry, I'm not sure if I understood your question

**Comment by umesh3034** [comment]
@aanm 
Hi, does #30823 need to fixed right now or we can live with the warning?

**Comment by aanm** [comment]
> @aanm Hi, does #30823 need to fixed right now or we can live with the warning?

If we could we should fix it now.

**Pull request merged**
