### PR TITLE
clean package "io/ioutil" ,because "io" and "os" can replaced it totally

### PR DESCRIPTION
**Pull request by yanggangtony**
Signed-off-by: yanggang <gang.yang@daocloud.io>

We should clean all io/util package according the url: https://go.dev/doc/go1.16#ioutil
/kind cleanup

### CODE REVIEW

**Review by pchaigno — CHANGES_REQUESTED** [review]
Thanks for your pull request!

Could you explain, in the commit description, why you are making this change?

Also, what does "for advanced Golang" mean? Did you mean "to accommodate newer Golang versions"?

**Comment by yanggangtony** [comment]
> Thanks for your pull request!
> 
> Could you explain, in the commit description, why you are making this change?
> 
> Also, what does "for advanced Golang" mean? Did you mean "to accommodate newer Golang versions"?

@pchaigno 
I mean the io/ioutil package is obsolete , maybe will be removed in newer version of golang.
Now it is replaced well by io or os package..

**Comment by pchaigno** [comment]
> > Thanks for your pull request!
> > Could you explain, in the commit description, why you are making this change?
> > Also, what does "for advanced Golang" mean? Did you mean "to accommodate newer Golang versions"?
> 
> @pchaigno I mean the io/ioutil package is obsolete , maybe will be removed in newer version of golang. Now it is replaced well by io or os package..

I understand that but we need that explanation in the commit message.

**Review by aanm — APPROVED** [review]

**Comment by pchaigno** [comment]
The commit is ill-formatted. There should be two new lines between the commit title and it's description and the commit title should be less than 75 characters. This is why GitHub and checkpatch are currently confused.

**Comment by yanggangtony** [comment]
> The commit is ill-formatted. There should be two new lines between the commit title and it's description and the commit title should be less than 75 characters. This is why GitHub and checkpatch are currently confused.

@pchaigno 
thanks ,that's better now..

**Comment by pchaigno** [comment]
It's better but your title is still:
```
clean package "io/ioutil" because "io" and "os" package can replaced it totally. according to the url : https://go.dev/doc/go1.16#ioutil
```
You need **two** newlines to separate a commit's title from its description.

**Comment by yanggangtony** [comment]
@pchaigno 
> You need **two** newlines to separate a commit's title from its description.

now , the commit style is ok?
i add two newlines..:smile::smile:

**Review by pchaigno — APPROVED** [review]

**Comment by yanggangtony** [comment]
> @yanggangtony Yep, looks good now. Next time I'd advise to look at it with `git log` and you'll see that the previous version broke the formatting.

@pchaigno 
thanks...

**Comment by pchaigno** [comment]
The smoke tests are passing and, given the changes, I don't think we need to run the full end-to-end tests. cilium/proxy is missing a review but the changes for that codeowners aren't really specific to the proxy, so probably okay to skip. Merging.

Thanks @yanggangtony for your contribution!

**Pull request merged**
