### PR TITLE
v1.9 backports 2021-01-06

### PR DESCRIPTION
**Pull request by christarazi**
* #14388 -- test: Add missing gomega Eventually intervals (@jrajahalme)
 * #14021 -- helm: 'bpf.ctTcpMax' and 'bpf.ctAnyMax' need to be strings, not integers (@mvisonneau)
 * #14346 -- pkg/logging: Init klog with flag set name (@fafucoder)
 * #14412 -- test: Test policy enforcement through tunnels (@pchaigno)
 * #14413 -- helm: fix TLS cert server name for cluster names containing dots (@kaworu)
 * #14416 -- helm: fix TLS cert server name for cluster names containing dots with certgen (@kaworu)
 * #14420 -- test: Fix microk8s deployment hurdles (@joestringer)
 * #14434 -- docs: Update linux distribution compatibility (@joestringer)
 * #13888 -- docs: add info about tailcalls in bpf subprograms (@mfijalko)
 * #14449 -- install/kubernetes: set the right option for expectAzureVnet (@aanm)
 * #14447 -- bpf: Fix misaligned access in bpf_xdp with prefilter and IPv6 (@pchaigno)
 * #14241 -- Update policy-creation.rst (@gecube)
 * #14473 -- Fixing Hubble ServiceMonitor k8s-app label (@guilhermef)
 * #14271 -- Istio: Update to 1.6.14 (@jrajahalme)
   * Notes: Slight conflict inside test suite, where v1.9 tree has the Istio tests quarantined, and `master` seemingly doesn't. Kept it as quarantined.
 * #14508 -- Add missing requireIPv6PodCIDR setting (@NeilW)
 * #14513 -- vendor: Update vishvananda/netlink (@pchaigno)
 * #14517 -- docs: Add cgroups kernel config requirements (@joestringer)

Removed from PR:
 * #14464 -- test: Un-Quarantine K8sUpdates on GKE (@gandro)
   * See https://github.com/cilium/cilium/pull/14538#issuecomment-759317706

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14388 14021 14346 14412 14413 14416 14420 14434 13888 14449 14447 14241 14473 14271 14508 14513 14517; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by christarazi** [comment]
test-backport-1.9

**Review by aanm — APPROVED** [review]
LGTM for my PRs

**Review by pchaigno — APPROVED** [review]
My PRs look good :+1: 

I've also executed the IPSec+tunneling test locally to check it works as expected.

**Comment by christarazi** [comment]
retest-gke

**Review by kaworu — APPROVED** [review]
LGTM for my commits, thanks!

**Review by gandro — APPROVED** [review]
Looks good for my commit. The un-quarantined test failed due to an ImagePullBackOff error. This is not an error I have observed with regards to the (previously broken) upgrade tests. It could be a spurious failure due e.g. network connectivity, I'm not sure if this is correlated or not. I don't believe it is, as I did not see anything suspicious in the logs?

**Comment by pchaigno** [comment]
retest-gke

**Review by guilhermef — APPROVED** [review]

**Comment by gandro** [comment]
retest-gke

**Comment by christarazi** [comment]
retest-gke

**Comment by pchaigno** [comment]
retest-gke

**Review by joestringer — APPROVED** [review]
Backports of my commits LGTM.

**Comment by gandro** [comment]
retest-gke

**Comment by christarazi** [comment]
@gandro Looks like the GKE test is finally running, but it failed with the same error that Paul linked: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/3906/testReport/Suite-k8s-1/16/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/

**Comment by gandro** [comment]
> @gandro Looks like the GKE test is finally running, but it failed with the same error that Paul linked: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/3906/testReport/Suite-k8s-1/16/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/

I guess this needs further investigation. Feel free to my commit from the PR to get this merged.

**Comment by christarazi** [comment]
test-backport-1.9

**Pull request merged**
