### PR TITLE
envoy: Bump envoy version to v1.23.7

### PR DESCRIPTION
**Pull request by sayboras**
Upstream release https://github.com/envoyproxy/envoy/releases/tag/v1.23.7

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.11

**Comment by sayboras** [comment]
/test-backport-1.11

**Comment by sayboras** [comment]
/test-backport-1.11

**Comment by sayboras** [comment]
/test-backport-1.11

**Comment by sayboras** [comment]
/test-1.16-netnext

**Comment by sayboras** [comment]
/test-backport-1.11

**Comment by sayboras** [comment]
/test-1.20-4.9

**Review by squeed — APPROVED** [review]

**Comment by sayboras** [comment]
/test-1.18-4.9

**Comment by sayboras** [comment]
/test-1.19-4.9

**Comment by sayboras** [comment]
/test-1.20-4.9

**Comment by sayboras** [comment]
/test-1.20-4.9

**Pull request merged**
