### PR TITLE
test: parallelize log gathering

### PR DESCRIPTION
**Pull request by nebril**
We are running multiple kubectl commands to gather logs. This change
makes the gathering commands run in parallel.

### CODE REVIEW

**Review by errordeveloper — APPROVED** [review]

**Comment by nebril** [comment]
test-4.9

**Comment by nebril** [comment]
test-runtime

**Comment by nebril** [comment]
test-4.19

**Comment by nebril** [comment]
test-net-next

**Comment by nebril** [comment]
Added a deliberate test failure to make a sanity check on generated logs

**Comment by nebril** [comment]
test-focus K8sServicesTest

**Comment by nebril** [comment]
test archives look good: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated-Focus/204/#showFailuresLink , removing the failing test commit and getting this merged

**Comment by nebril** [comment]
test-4.9

**Pull request merged**
