### PR TITLE
bpf: Remove POLICY_MAP from bpf_netdev and bpf_overlay

### LINKED ISSUE #3450: Schedule removal of policy_reserved_ maps
Add code to remove policy_reserved_* maps in a future release once restore from endpoints using this is never encountered anymore

### PR DESCRIPTION
**Pull request by tgraf**
Both the bpf_netdev and bpf_overlay have not been using a policy map for their
functionality but a BPF map was still allocated and pinned to the filesystem.
Refactor the code a bit to avoid allocating BPF policy maps for these programs.

Also, remove old pinned BPF maps on agent bootstrap.

Fixes: #3450

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9949)

### CODE REVIEW

**Review by borkmann — APPROVED** [review]
LGTM

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
```
01:19:51.141  Progress state: VBOX_E_INVALID_OBJECT_STATE
01:19:51.141  VBoxManage: error: Machine delete failed
01:19:51.141  VBoxManage: error: Medium '/root/VirtualBox VMs/ubuntu-18.04.3-amd64-164_1579790870371_15828/ubuntu-18.04.3-amd64-164-disk001.vmdk' is locked for reading by another task
01:19:51.141  VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MediumWrap, interface IMedium
01:19:51.141  VBoxManage: error: Context: "RTEXITCODE handleUnregisterVM(HandlerArg*)" at line 162 of file VBoxManageMisc.cpp
01:19:51.680  0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
```

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Pull request merged**
