### PR TITLE
policy: Create derivative policy for EgressDeny rules

### LINKED ISSUE #23829: NetworkPolicy: `toGroups` rule in `egressDeny` policy doesn't generate derivative policy
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I followed the document [Locking down external access using AWS metadata](https://docs.cilium.io/en/stable/gettingstarted/aws/) to create a `toGroups` rule with an AWS security group id under the `egress` policy and an derivative policy can be generated with my ec2 instance IPs.
Here is the policy:
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: egress-default
  namespace: network-multitool
spec:
  egress:
    - toGroups:
        - aws:
            securityGroupsIds:
              - sg-07283569446d92723
  endpointSelector: {}
```
The generated derivative policy is:
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    io.cilium.network.policy.kind: derivative
    io.cilium.network.policy.parent.uuid: a45969bd-1b05-47a5-8147-3895e2b5da96
  name: egress-default-togroups-a45969bd-1b05-47a5-8147-3895e2b5da96
  namespace: network-multitool
specs:
  - egress:
      - toCIDRSet:
          - cidr: 10.103.10.122/32
          - cidr: 10.103.25.222/32
          - cidr: 10.103.217.142/32
    endpointSelector:
      matchLabels:
        k8s:io.kubernetes.pod.namespace: network-multitool
    labels:
      - key: io.cilium.k8s.policy.derived-from
        source: k8s
        value: CiliumNetworkPolicy
      - key: io.cilium.k8s.policy.name
        source: k8s
        value: egress-default
      - key: io.cilium.k8s.policy.namespace
        source: k8s
        value: network-multitool
      - key: io.cilium.k8s.policy.uid
        source: k8s
        value: a45969bd-1b05-47a5-8147-3895e2b5da96
```

Well, when I update the CNP by changing the `egress` to `egressDeny`, there is no derivative policy generated (the previous one was deleted by cilium operator after the update).
Here is the CNP after being updated:
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: egress-default
  namespace: network-multitool
spec:
  egressDeny:
    - toGroups:
        - aws:
            securityGroupsIds:
              - sg-07283569446d92723
  endpointSelector: {}
```
There is a log from `cilium-operator` pod:
```
level=info msg="New CNP does not have derivative policy, but old had. Deleting old policies" ciliumNetworkPolicyName=egress-default k8sNamespace=network-multitool subsys=Groups
```

Then, it looks like being logged from here https://github.com/cilium/cilium/blob/4b803e9cdf4a9365b12c158787abbe2172d5321c/pkg/policy/groups/actions.go#L72-L76 that the `newCNP.RequiresDerivative()` returns `true`.

When I dug a bit more codes, it looks like the the follow codes only check `Egress` field of `Rule` but missed checking `EgressDeny` field. https://github.com/cilium/cilium/blob/4b803e9cdf4a9365b12c158787abbe2172d5321c/pkg/policy/api/rule.go#L207-L214

```go
func (r *Rule) RequiresDerivative() bool {
	for _, rule := range r.Egress {
		if rule.RequiresDerivative() {
			return true
		}
	}
	return false
}
```
Also, the derivative policy creation for `egressDeny` is also missed from the method `CreateDerivative` just below it.
https://github.com/cilium/cilium/blob/4b803e9cdf4a9365b12c158787abbe2172d5321c/pkg/policy/api/rule.go#L218-L230

### Cilium Version

```
root@ip-10-103-111-49:/home/cilium# cilium version
Client: 1.12.4 6eaecaf 2022-11-16T05:45:01+00:00 go version go1.18.8 linux/amd64
Daemon: 1.12.4 6eaecaf 2022-11-16T05:45:01+00:00 go version go1.18.8 linux/amd64
```

### Kernel Version

```
Linux ip-10-103-111-49.us-east-2.compute.internal 5.4.228-131.415.amzn2.x86_64 #1 SMP Tue Dec 20 12:51:02 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.16-eks-ffeb93d", GitCommit:"52e500d139bdef42fbc4540c357f0565c7867a81", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:42Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

I am assuming `toGroups` should be supported by `egressDeny` since it is defined in the CNP's CRD and not sure if this is intentional.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rockc2020**
This PR is to create derivative policy when `egressDeny` including `toGroups` rules.

With issue https://github.com/cilium/cilium/issues/23829, there is no derivative policy created when `egressDeny` including `toGroups` rules.

This fix includes following changes:
* Add check for `EgressDeny` in method `RequiresDerivative()`
* Add derivative policy creation for `EgressDenyRule` in method `CreateDerivative()`
* Add unit tests for both methods

I also built an image with this change from my local and deployed in my EKS cluster. Then, I created a ccnp:
```yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: egress-global
spec:
  egressDeny:
    - toGroups:
        - aws:
            securityGroupsIds:
              - sg-07283569446d92723
  endpointSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - network-multitool
```
Then, a derivative policy was created successfully:
```yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  labels:
    io.cilium.network.policy.kind: derivative
    io.cilium.network.policy.parent.uuid: 6b2c336b-1608-4611-b63d-21acd36fa75f
  managedFields:
    - apiVersion: cilium.io/v2
      fieldsType: FieldsV1
      fieldsV1:
        f:specs: {}
      manager: Go-http-client
      operation: Update
      time: '2023-02-22T02:07:18Z'
  name: egress-global-togroups-6b2c336b-1608-4611-b63d-21acd36fa75f
  ownerReferences:
    - apiVersion: cilium.io/v2
      kind: CiliumClusterwideNetworkPolicy
      name: egress-global
      uid: 6b2c336b-1608-4611-b63d-21acd36fa75f
  resourceVersion: '6154562'
  uid: 1e102dec-f882-4c08-817f-34b013c78b37
  selfLink: >-
    /apis/cilium.io/v2/ciliumclusterwidenetworkpolicies/egress-global-togroups-6b2c336b-1608-4611-b63d-21acd36fa75f
specs:
  - egressDeny:
      - toCIDRSet:
          - cidr: 10.103.25.222/32
          - cidr: 10.103.71.146/32
          - cidr: 10.103.217.142/32
    endpointSelector:
      matchExpressions:
        - key: any:app
          operator: In
          values:
            - network-multitool
    labels:
      - key: io.cilium.k8s.policy.derived-from
        source: k8s
        value: CiliumClusterwideNetworkPolicy
      - key: io.cilium.k8s.policy.name
        source: k8s
        value: egress-global
      - key: io.cilium.k8s.policy.uid
        source: k8s
        value: 6b2c336b-1608-4611-b63d-21acd36fa75f
```

Fixes: #23829

```release-note
policy: Derivative policies (policies for cloud provider-specific identities) for egress deny rules were not being generated, this has now been fixed. 
```

### CODE REVIEW

**Comment by nathanjsweet** [comment]
Thanks for the PR @rockc2020, I'm off tomorrow, but I'll take a thorough look at this on Monday.

**Comment by rockc2020** [comment]
hi @nathanjsweet as 1 check failed with my PR https://github.com/cilium/cilium/actions/runs/4238946330/jobs/7379640730. after I had a run on my local, it seems some errors of `ERROR:NO_AUTHOR_SIGN_OFF` that some commits missing `Signed-off-by`. I guess that might be because I merged master by clicking the update branch button before. so do I need to just revert that merging commit and using rebase again? or just wait for reviewing and then update?

**Comment by nathanjsweet** [comment]
`checkpatch` is complaining about unrelated commits (checking them because the rebase is behind) to this PR.

**Review by nathanjsweet — APPROVED** [review]

**Pull request merged**
