### PR TITLE
Add a function to get connection info in a structure format from data

### PR DESCRIPTION
**Pull request by lzang**
Add a function to get connection info in a structure format from data so that it is easier for post processing.

Signed-off-by: Zang Li <zangli@google.com>

### CODE REVIEW

**Comment by lzang** [comment]
test-me-please

**Comment by lzang** [comment]
test-me-please

**Comment by lzang** [comment]
test-me-please

**Review by rolinh — APPROVED** [review]

**Comment by lzang** [comment]
test-me-please

**Comment by pchaigno** [comment]
restart-ginkgo

**Comment by lzang** [comment]
restart-ginkgo

**Comment by lzang** [comment]
@pchaigno, thanks for the tip!  How to restart the Ginkgo-GKE test,  test-gke?

**Comment by pchaigno** [comment]
@lzang Yep, `test-gke` exactly. The GKE pipeline isn't required to merge at the moment though. So I wouldn't bother re-running if you've already checked that the failing tests are not the same between two runs (i.e., they are flakes).

**Review by joestringer — APPROVED** [review]

**Pull request merged**
