### PR TITLE
[v1.13] fqdn: Add Protocol to DNS Proxy Cache

### PR DESCRIPTION
**Pull request by nathanjsweet**
DNS Proxy indexes domain selectors by port
only. In cases where protocols collide on port
the DNS proxy may have a more restrictive selector than it should because it does not merge port
protocols for L7 policies (only ports).

Refactor all users of the DNS Proxy are updated
to add protocol to any DNS Proxy entries, and all
tests are updated to test for port-protocol
merge errors.
```release-note
fqdn: Fixed bug that caused DNS Proxy to be overly restrictive on allowed DNS selectors.
```

### CODE REVIEW

**Comment by nathanjsweet** [comment]
/test-backport-1.13

**Comment by nathanjsweet** [comment]
This is a backport of https://github.com/cilium/cilium/pull/31328

**Review by pippolo84 — APPROVED** [review]
LGTM :rocket:

**Comment by julianwiedmann** [comment]
/test-1.22-4.19

**Comment by julianwiedmann** [comment]
/test-1.26-net-next

**Review by squeed — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]

**Comment by julianwiedmann** [comment]
/test-1.26-net-next

**Review by julianwiedmann — APPROVED** [review]

**Pull request merged**
