### PR TITLE
Test: WithTimeout executed on start

### PR DESCRIPTION
**Pull request by eloycoto**
WithTimeout was not executed on start, so the first run was after
`config.Ticker` value (default to 5) With this change always will
executed on first run, if fail will executed each config.Ticker.

This change should make test a bit faster.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4710)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
