### PR TITLE
kafka: remove unused package

### PR DESCRIPTION
**Pull request by tklauser**
It's unused since proxylib was moved to the cilium/proxy repo in commit 51fc881f0cb5 ("proxylib: Remove proxylib module").

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Thanks a lot :heavy_check_mark:

**Review by rolinh — APPROVED** [review]
```
+0 −7,255
```
:point_up: best kind of diff!

**Comment by tklauser** [comment]
marked as ready to merge given the outstanding reviews for @cilium/docs-structure and @cilium/contributing are for trivial deletions due to the package being removed.

**Pull request merged**
