### PR TITLE
kubernetes: Use 2.0.4 version of cilium-etcd-operator

### PR DESCRIPTION
**Pull request by tgraf**
Signed-off-by: Thomas Graf <thomas@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6634)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

```
00:22:45.067     Expected command: docker exec -i  app2 curl -s -D /dev/stderr --fail --connect-timeout 3 --max-time 8 http://[f00d::1:1]:1234/public -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
00:22:45.067     To succeed, but it failed:
00:22:45.067     Exitcode: 28 
00:22:45.067     Stdout:
00:22:45.067      	 time-> DNS: '0.000028()', Connect: '0.000000',Transfer '0.000000', total '3.001652'
00:22:45.067     Stderr:
```

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

etcd did not come up. Unfortunately no logs. Trying again

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
@aanm Based on CI results, the 2.0.4 version of the cilium-etcd-operator has some issues. It's working fine for me in standalone testing though

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9035/

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
