### PR TITLE
routing: Extend unit tests

### LINKED ISSUE #19261: Extend unit tests for routing setup
We should extend the unit tests in `pkg/datapath/linux/routing` to cover the sort of bug described and fixed in https://github.com/cilium/cilium/pull/19162.

The TL;DR is that we had a mismatch between the creation (`Configure`) and deletion (`Delete`) of IP rules. In unit tests today, we test those two functions separately. We would need to add a new unit test which call one after the other and checks the system is back to its original state.

### PR DESCRIPTION
**Pull request by krabradosty**
Previously, there was a bug (#19162) between the creation and deletion of routing rules due to inconsistent conditions. This commit updates unit tests to cover unhandled situations.

Fixes #19261

### CODE REVIEW

**Comment by joestringer** [comment]
This affects only (privileged?) unit tests and the corresponding tests have passed. Just waiting on review from @aspsk .

**Review by aspsk — APPROVED** [review]
LGTM. (Sorry for the delay, missed this PR due to travels)

**Comment by joestringer** [comment]
Thanks for the contribution! Merging.

**Pull request merged**
