### PR TITLE
[CI] Replace jenkinsfiles with symlinks

### PR DESCRIPTION
**Pull request by nebril**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10262)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
Small steps but we are getting there :smile:

**Comment by aanm** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Pull request merged**
