### PR TITLE
vendor: Bump gopkg.in/yaml.v2 to v2.4.0

### PR DESCRIPTION
**Pull request by twpayne**
This version reverts the default line wrapping change introduced in v2.3.0, so we can remove our override in `go.mod`.

See https://github.com/go-yaml/yaml/commit/7649d4548cb53a614db133b2a8ac1f31859dda8c.

### CODE REVIEW

**Comment by twpayne** [comment]
test-me-please

**Review by rolinh — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by twpayne** [comment]
test-me-please

**Comment by twpayne** [comment]
test-gke

**Comment by pchaigno** [comment]
retest-gke

**Pull request merged**
