### PR TITLE
docs: fix mistake in the docs of api rate limiting

### PR DESCRIPTION
**Pull request by yanhongchang**
the default value of auto-adjust is wrong.

Signed-off-by: yanhongchang yanhongchang5@163.com

### CODE REVIEW

**Review by qmonnet — COMMENTED** [review]
Hi, thanks a lot for your contribution!

Can you please explain how you found the default value at `true`? I had a look at the code and was under the impression that `false` was the correct value.

**Comment by yanhongchang** [comment]
> 
I met some warning event about endpoint-create , such as  like "putEndpointIdTooManyRequests", and I check the log of cilium-agent and view the docs about rate-limiting ，then I try to adjust the "parallel-requests", set value to 200,but it not work, Then I check the code, and I found the "auto-adjust"  default value is "true". please see the code link:
https://github.com/cilium/cilium/blob/master/daemon/cmd/api_limits.go#L24

**Comment by qmonnet** [comment]
OK, thank you for the pointer.

In that case, I believe the documentation is correct as it is. The table that you propose to change contains the default values used when _new_ rate limits are configured, for API calls that are not rate-limited by default. As I understand it, the code that you pointed implements the defaults for the `endpoint-create` call. It's true that for this call, `auto-adjust` defaults to `true`; but this is already reported in [the table with the default rate limits implemented for the `endpoint-*` calls](https://docs.cilium.io/en/latest/configuration/api-rate-limiting/#default-rate-limits), on the same page.

**Comment by yanhongchang** [comment]
> OK, thank you for the pointer.
> 
> In that case, I believe the documentation is correct as it is. The table that you propose to change contains the default values used when _new_ rate limits are configured, for API calls that are not rate-limited by default. As I understand it, the code that you pointed implements the defaults for the `endpoint-create` call. It's true that for this call, `auto-adjust` defaults to `true`; but this is already reported in [the table with the default rate limits implemented for the `endpoint-*` calls](https://docs.cilium.io/en/latest/configuration/api-rate-limiting/#default-rate-limits), on the same page.

Oh, I got it !  It's my fault, I overlook the table of _Default Rate Limits_, thank you for your answer !

**Comment by yanhongchang** [comment]
> OK, thank you for the pointer.
> 
> In that case, I believe the documentation is correct as it is. The table that you propose to change contains the default values used when _new_ rate limits are configured, for API calls that are not rate-limited by default. As I understand it, the code that you pointed implements the defaults for the `endpoint-create` call. It's true that for this call, `auto-adjust` defaults to `true`; but this is already reported in [the table with the default rate limits implemented for the `endpoint-*` calls](https://docs.cilium.io/en/latest/configuration/api-rate-limiting/#default-rate-limits), on the same page.

Oh, I got it !  It's my fault, I overlook the table of _Default Rate Limits_, thank you for your answer !

**Comment by qmonnet** [comment]
You're welcome, thanks again for the PR, the intent was great! :rocket:

**Pull request closed without merging**
