### PR TITLE
README: Fixed Typo

### PR DESCRIPTION
**Pull request by 0xcaff**

### CODE REVIEW

**Review by vadorovsky — APPROVED** [review]

**Review by vadorovsky — CHANGES_REQUESTED** [review]
Commits in Cilium need to be signed off. Please do `git commit --amend --signoff` and then `git push -f` ro re-submit your commit.

**Comment by 0xcaff** [comment]
Sorry about that. It's signed off now.

**Comment by aanm** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@0xcaff Thanks for the PR!

**Pull request merged**
