### PR TITLE
ci: conn tests concurrent run

### PR DESCRIPTION
**Pull request by viktor-kurchenko**
EKS workflows improved with connectivity tests concurrent run.

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Review by christarazi — APPROVED** [review]

**Comment by viktor-kurchenko** [comment]
@christarazi could you please review one more time?
I've [added one more node](https://github.com/cilium/cilium/pull/34417/files#diff-78d97443983227cc6f706201576401c6d6f17f6e76380a9b99c70eaaf00b38c5R55) to EKS cluster and increased test concurrency.
Without this change workflow speedup is almost invisible.
Sorry for the confusion.

**Review by christarazi — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Pull request merged**
