### PR TITLE
v1.11: operator: fix key name for delete during k8s->kvstore sync

### PR DESCRIPTION
**Pull request by tklauser**
Manual backport of #20968 for v1.11

The handler which synchronizes CiliumNodes from k8s to the KV store
includes the cluster name in the update operation but not the delete
operation. This might lead to nodes not being correctly deleted from the
KV store when they disappear.

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.11

**Comment by tklauser** [comment]
/test-1.23-4.9

**Review by aanm — APPROVED** [review]

**Comment by aditighag** [comment]
@tklauser Do you mind rebasing the PR?

**Comment by tklauser** [comment]
/test-backport-1.11

**Pull request merged**
