### PR TITLE
bpf: remove unused GetProgNextID, GetProgFDByID and GetProgInfoByFD

### PR DESCRIPTION
**Pull request by tklauser**
These are not used by Cilium. If they'd be needed in the future they
should be added to github.com/cilium/ebpf

Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10187)

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Comment by pchaigno** [comment]
I'm not sure we can/want to remove those. These functions were added in #3899 to be used by a separate project (https://github.com/genuinetools/bpfps).

**Comment by tklauser** [comment]
> I'm not sure we can/want to remove those. These functions were added in #3899 to be used by a separate project (https://github.com/genuinetools/bpfps).

Do we guarantee API stability for non-Cilium projects? It seems `github.com/genuinetools/bpfps` is vendoring a version `github.com/cilium/cilium` which still has these funcs. When building it against latest cilium master, it's broken already anyhow:

```
# github.com/genuinetools/bpfps
./main.go:63:21: not enough arguments in call to bpf.CheckOrMountFS
	have (string)
	want (string, bool)
make: *** [basic.mk:48: bpfps] Error 2
```

**Comment by tklauser** [comment]
Ideally these functions should probably be added to `github.com/cilium/ebpf` so they can be safely consumed by other packages.

**Comment by brb** [comment]
> Do we guarantee API stability for non-Cilium projects?

@aanm ^^?

**Comment by aanm** [comment]
test-me-please

**Review by aanm — CHANGES_REQUESTED** [review]
@tklauser The whole file `pkg/bpf/prog_linux.go` can be removed since its not used anywhere.

**Comment by aanm** [comment]
> > Do we guarantee API stability for non-Cilium projects?
> 
> @aanm ^^?

I don't see how we could enforce this for all the code base. We have `api/v1` that should guarantee the API stability.

**Comment by tklauser** [comment]
test-me-please

**Comment by aanm** [comment]
@tklauser needs rebase

**Comment by tklauser** [comment]
test-me-please

**Pull request merged**
