### PR TITLE
bgpv2: Add a knob to disable CRD status reporting

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
We recently introduced several CRD status reporting features (https://github.com/cilium/cilium/pull/33411, https://github.com/cilium/cilium/pull/35517, https://github.com/cilium/cilium/pull/35527, https://github.com/cilium/cilium/pull/35650). They are useful for troubleshooting, but there's a trade-off between API server load. For the large cluster with many nodes or many BGP resources may experience a high API server load. In this PR, we introduce a knob to disable BGPv2 CRD status reporting for such an environment.

```release-note
bgpv2: Add a knob to disable CRD status reporting
```

### CODE REVIEW

**Review by rastislavs — APPROVED** [review]
LGTM, thanks!

**Review by gandro — COMMENTED** [review]
Code-wise, this looks good to me.

We used to have a similar feature for CNPs, that we eventually turned off by default and then removed completely because it suffered from the same scalability issues. 

I do wonder if we should also disable this feature by default.

**Review by gandro — APPROVED** [review]
Discussed offline. Turns out the scalability issues are less pronounced with the BGP status compared to the old CNP status I mentioned. So keeping this enabled by default seems like a reasonable tradeoff.

> In the CNP case, we used to edit global CNP from multiple nodes while they are watched by all nodes. On the other hand, the BGP resources only have a single writer.

**Comment by YutaroHayakawa** [comment]
Cilium E2E Upgrade: https://github.com/cilium/cilium/issues/35774
Conformance External Workloads: Provisioning timeout
Conformance Ginkgo: https://github.com/cilium/cilium/issues/18889

**Review by tommyp1ckles — APPROVED** [review]

**Pull request merged**
