### PR TITLE
nodemanager: Fix bug where Cilium tried to reach stale health endpoints on kubeapi-server nodes

### PR DESCRIPTION
**Pull request by gandro**
IPCache entries each have an associated source, which determines if an
entry can be overwritten with information originating in a different
source. If the node manager detects that a change to a node was rejected
by the IPCache, it will skip informing any node subscribers about the
change.

For the `KubeAPIServer` source however, special care has to be taken.
While the IPCache entry itself may not be overwritten, auxiliary node
properties such as the health endpoints may still have changed and must
be propagated to all node subscribers (such as the health subsystem).

This commit adds a special check for `KubeAPIServer` entries which
ensures that even if the IPCache entry did not change, that we still
inform all node subscribers about the change. This fixes a bug where
health endpoint changes on the kubeapi-server node where not picked up
by remote cilium agent instances and thus those instances tried to reach
a stale endpoint.

### CODE REVIEW

**Comment by gandro** [comment]
GKE is known to be broken at the moment and not required to merge. This is ready for review.

**Review by tklauser — APPROVED** [review]

**Comment by sayboras** [comment]
/test-1.23-4.19

**Review by sayboras — APPROVED** [review]

**Comment by gandro** [comment]
> /test-1.23-4.19

This test suite has been added after this PR has been opened, it replaced the `test-1.23-4.19` which passed before. So the failure can be ignored

**Review by christarazi — APPROVED** [review]
LGTM as a temporary fix. Unfortunately, this is a consequence of the old ipcache design which forces each user of the ipcache to consider all other usages. Once https://github.com/cilium/cilium/pull/19765 merges, this should no longer be necessary. 

cc @joestringer as FYI

**Pull request merged**
