### PR TITLE
Fix: prevent goroutine leakage

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

Use the `ctx` passed to `startSynchronizingCiliumNodes` instead of `wait.NeverStop`.

/kind cleanup

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Review by joamaki — APPROVED** [review]
Thanks, this looks good to me. The goroutine leakage only has impact in tests (e.g. test/controlplane) since in real operation the operator will exit anyway after context is cancelled. 

There's couple more of these still in `pkg/k8s/watchers` for example. If you're interested in taking a look you might want to run `test/controlplane` tests and use `goleak.VerifyTestMain(m)` to see what still leaks.

**Comment by kerthcet** [comment]
> There's couple more of these still in `pkg/k8s/watchers` for example. If you're interested in taking a look you might want to run `test/controlplane` tests and use `goleak.VerifyTestMain(m)` to see what still leaks.

Sure, I'll take a look later.

**Review by christarazi — COMMENTED** [review]
Could you add the context from the PR description to the commit msg as well? Fix LGTM.

**Comment by kerthcet** [comment]
> Could you add the context from the PR description to the commit msg as well? Fix LGTM.

Updated, I'll pay attention next time. Thanks.

**Review by christarazi — APPROVED** [review]

**Comment by kerthcet** [comment]
Anything remains before merging the PR? @christarazi

**Comment by christarazi** [comment]
@kerthcet Let's see how CI runs to ensure there's no regressions. If it passes then we can merge.

**Pull request merged**
