### PR TITLE
test: Disable the host firewall in incompatible tests

### PR DESCRIPTION
**Pull request by pchaigno**
See commits for details.

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
retest-4.19

**Comment by pchaigno** [comment]
retest-4.9

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
All required CI builds are green except for the known broken test k8sVerifier on net-next and 4.19. That test was enabled by mistake on those pipelines and will be disabled by https://github.com/cilium/cilium/pull/14162.
Marking as ready to merge.

**Pull request merged**
