### PR TITLE
v1.8 backports 2021-07-15

### PR DESCRIPTION
**Pull request by joestringer**
* #16721 -- Fix and add more commands in CI sysdumps (@aanm)
   * Minor conflict in log-gatherer pod spec. Bumped to v1.1.
 * #16750 -- contrib/docs: rename 'cilium-actions.yml' with 'maintainers-little-helper.yaml (@aanm)
   * Minor conflict in docs
 * #16804 -- contrib: Explicitly set remote for backport branches (@twpayne)

Skipped until I hear from @jrajahalme that the benefit outweighs the risks:
 * #16801 -- Fix potential deadlock in pod identity updates (@jrajahalme)

Skipped since it seems to break VM provisioning for test-upstream-k8s job (see comments below)
* #16554 -- ci: Disable NFS locking (@gandro)
   * Minor conflict, resolved by applying the new option to the old config

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16721 16750 16804; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by joestringer** [comment]
test-backport-1.8

**Review by aanm — APPROVED** [review]
LGTM thanks!

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by joestringer** [comment]
@aanm it seems like it hit the same issue again: https://jenkins.cilium.io/job/Cilium-PR-K8s-Upstream/3244/flowGraphTable/

Are we going to make progress by continuing to retrigger the jobs in the hopes that some time the right node will manage to cache the VM? Or should we be taking different action to resolve that on the jenkins nodes so that we can trigger the test reliably?

**Review by gandro — APPROVED** [review]

**Comment by joestringer** [comment]
test-upstream-k8s

**Comment by joestringer** [comment]
Definitely still failing the same way:
https://jenkins.cilium.io/job/Cilium-PR-K8s-Upstream/3251/flowGraphTable/

I'll try dropping the CI change.

**Comment by joestringer** [comment]
test-upstream-k8s

**Comment by joestringer** [comment]
Travis hit docker ratelimiting:

https://app.travis-ci.com/github/cilium/cilium/builds/233369040

```
anyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Makefile:15: recipe for target 'builder-image' failed
```

Did we do something different on newer branches so we don't hit this?

**Comment by joestringer** [comment]
`test-upstream-k8s` passed: https://jenkins.cilium.io/job/Cilium-PR-K8s-Upstream/3252/

All other tests passed previously and we've had sufficient reviews of this backport PR. Merging.

**Pull request merged**
