### PR TITLE
v1.9 backports 2021-06-02

### PR DESCRIPTION
**Pull request by qmonnet**
* [x] #14639 -- test: Mark GKE CI pipeline as running Linux 4.19 (@pchaigno)
   - Commit 227860cbbccb (`test: Mark GKE CI pipeline as running Linux 4.19`) skipped: Already backported in #16224, but reverted afterwards in 2dbe4c1c31d2 because of CI failure. It is added _again_ in this PR (revert of the revert), with a change to make sure that the failing test is skipped on GKE (just like on master branch).
   - Commit 814a2f8ea2f7 (`test: Fix fragment tracking test on GKE`) backported in this PR (accidentally omitted from #16224).
   - Commit 0eb9b82aefff (`test: Skip fragment tracking test on GKE`) skipped: Already backported in #16224.
 * [x] #16176 -- contrib: simplify check-docker-images script (@aanm)
 * [x] #16043 -- Support non-default Azure clouds (@ungureanuvladvictor)
   First commit: Bump azure vendor from `v44.2.0+incompatible` instead of `v50.2.0+incompatible` as for master branch.
 * [x] #16137 -- docs: document the policy for backporting documentation changes (@qmonnet)
 * [ ] #16194 -- Make LRP restore test logic robust and optimized (@aditighag)
 * [ ] #16055 -- Add missing bpftool map dumps (@h3llix)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14639 16176 16043 16137 16194 16055; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by qmonnet** [comment]
test-backport-1.9

**Review by pchaigno — CHANGES_REQUESTED** [review]
I think we also need to revert https://github.com/cilium/cilium/commit/2dbe4c1c31d2ae65f10133012c0c55916bda54e6. The missing commit is probably the reason why it was failing.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
test-backport-1.9

**Review by ungureanuvladvictor — APPROVED** [review]
My azure commits look good!

**Comment by qmonnet** [comment]
I see some failures already.
- `k8s-1.17-kernel-5.4 (test-1.17-5.4)` seems to be a flake, https://github.com/cilium/cilium/issues/16050
- `k8s-1.18-kernel-4.19 (test-1.18-4.19)` seems to be a flake, https://github.com/cilium/cilium/issues/15255
- `gke-stable` seems to be https://github.com/cilium/cilium/issues/16317, supposedly closed by https://github.com/cilium/cilium/pull/16333, which contains the revert from @pchaigno's commit. Paul, it seems that 227860c does not work on v1.9, even with 814a2f8 applied? (Fragment testing should be skipped on GKE anyway as per 0eb9b82, so I don't think 814a2f8 would solve the issue?)

**Comment by pchaigno** [comment]
>     * `gke-stable` seems to be #16317, supposedly closed by #16333, which contains the revert from @pchaigno's commit. Paul, it seems that [227860c](https://github.com/cilium/cilium/commit/227860cbbccb06cb0e9d904be73f3be7b2ba2cbf) does not work on v1.9, even with [814a2f8](https://github.com/cilium/cilium/commit/814a2f8ea2f70133453565776dca5480b342072e) applied? (Fragment testing should be skipped on GKE anyway as per [0eb9b82](https://github.com/cilium/cilium/commit/0eb9b82aefff44ff59b928113ffbc8cfbb0aa0d8), so I don't think [814a2f8](https://github.com/cilium/cilium/commit/814a2f8ea2f70133453565776dca5480b342072e) would solve the issue?)

That test doesn't fail on master because we skip it on master. Let's do the same here. Could you edit the commit to skip `Tests NodePort (kube-proxy)` when running on GKE and add a note in the commit to explain? The corresponding master code is here: https://github.com/cilium/cilium/blob/7a4184f1195c0dd81a84cd3b265de19fb0f0fbb8/test/k8sT/Services.go#L2059

**Review by aanm — APPROVED** [review]
Looks good for my commit.

**Comment by qmonnet** [comment]
I updated according to Paul's suggestion (and rebased on top of current v1.9). His first commit in this PR is the only one which changed.

<details><summary><code>git diff qmonnet/pr/v1.9-backport-2021-06-02 -- test</code></summary>

``` diff
diff --git a/test/helpers/utils.go b/test/helpers/utils.go
index c28e097b7885..8f2f53f47c90 100644
--- a/test/helpers/utils.go
+++ b/test/helpers/utils.go
@@ -561,6 +561,13 @@ func DoesNotRunOnEKS() bool {
 	return !RunsOnEKS()
 }
 
+// RunsWithKubeProxyReplacement returns true if the kernel supports our
+// kube-proxy replacement. Note that kube-proxy may still be running
+// alongside Cilium.
+func RunsWithKubeProxyReplacement() bool {
+	return RunsOnGKE() || RunsOnNetNextKernel() || RunsOn419Kernel() || RunsOn54Kernel()
+}
+
 // DoesNotHaveHosts returns a function which returns true if a CI job
 // has less VMs than the given count.
 func DoesNotHaveHosts(count int) func() bool {
diff --git a/test/k8sT/Services.go b/test/k8sT/Services.go
index da4562222811..6fcba71a7f72 100644
--- a/test/k8sT/Services.go
+++ b/test/k8sT/Services.go
@@ -1563,7 +1563,7 @@ var _ = SkipDescribeIf(helpers.RunsOn54Kernel, "K8sServicesTest", func() {
 			}
 		}
 
-		SkipContextIf(helpers.RunsWithoutKubeProxy, "Tests NodePort (kube-proxy)", func() {
+		SkipContextIf(helpers.RunsWithKubeProxyReplacement, "Tests NodePort (kube-proxy)", func() {
 			SkipItIf(helpers.DoesNotRunOn419OrLaterKernel, "with IPSec and externalTrafficPolicy=Local", func() {
 				deploymentManager.SetKubectl(kubectl)
 				deploymentManager.Deploy(helpers.CiliumNamespace, IPSecSecret)
```
</details>

**Review by pchaigno — APPROVED** [review]

**Comment by qmonnet** [comment]
test-backport-1.9

**Comment by qmonnet** [comment]
- Failure on `k8s-1.12-kernel-netnext (test-1.12-netnext)` is known as https://github.com/cilium/cilium/issues/16122
- Failure on `k8s-1.17-kernel-5.4 (test-1.17-5.4)` is known as https://github.com/cilium/cilium/issues/16050

**Pull request merged**
