### PR TITLE
ipsec: Simplify egress packet path in native routing mode

### PR DESCRIPTION
**Pull request by pchaigno**
During encryption we currently keep the 0x0E00 bit in the mark to force encrypted packets through bpf_host@cilium_host (using ip rules & routes). There we can setup the configuration for encapsulation and redirect to cilium_vxlan.

There's however no need to go through cilium_host in native routing mode. This commit therefore clears the mark completely on encryption. As a results, encrypted packets will be routed directly to the native device.

### CODE REVIEW

**Comment by julianwiedmann** [comment]
I sort of liked that our encryption traffic is easily identifiable when it reaches `to-netdev` :disappointed:. Can we instead just not install the ip rules/routes when in native-routing mode?

**Comment by jschwinger233** [comment]
Like the motivation.

Also like to keep 0xd00 for the "encrypted" context as Julian mentioned.

How about add a new ip rule? I found those two can coexist:

```
$ ip ru
0:	from all lookup local
32761:	from all fwmark 0xe00/0xffffff00 lookup 2004
32762:	from all fwmark 0xe00/0xf00 lookup 2005
```

And they work as we wish:

```
$ ip r g 1.1.1.1 mark 0x11111e00
1.1.1.1 dev lo table 2005 src 10.103.80.104 mark 0x11111e00 uid 1000 
    cache <local> mtu 2005 

$ ip r g 1.1.1.1 mark 0xe00
1.1.1.1 dev docker0 table 2004 src 172.17.0.1 mark 0xe00 uid 1000 
    cache 
```

Therefore we can route 0xe00 and 0xXXXXXe00 to different dest?

**Pull request closed without merging**
