### PR TITLE
1.3: backports 18-12-03

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:

* #6211 
* #6291 
* #6299 
* #6346 
* #6318 
* #6360 
* #6218 

Signed-off by: Ian Vernon <ian@cilium.io>

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6362)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Build failure: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8389/

gofmt failed:
```
03:28:59     runtime: Unformatted Go source code:
03:28:59     runtime: ./pkg/endpoint/endpoint.go
03:28:59     runtime: diff -u ./pkg/endpoint/endpoint.go.orig ./pkg/endpoint/endpoint.go
03:28:59     runtime: --- ./pkg/endpoint/endpoint.go.orig	2018-12-03 03:28:55.576232000 +0000
03:28:59     runtime: +++ ./pkg/endpoint/endpoint.go	2018-12-03 03:28:55.576232000 +0000
03:28:59     runtime: @@ -2081,8 +2081,8 @@
03:28:59     runtime:  		e.getLogger().WithFields(logrus.Fields{
03:28:59     runtime:  			logfields.EndpointState + ".from": fromState,
03:28:59     runtime:  			logfields.EndpointState + ".to":   toState,
03:28:59     runtime: -			"file":                            fileName,
03:28:59     runtime: -			"line":                            fileLine,
03:28:59     runtime: +			"file": fileName,
03:28:59     runtime: +			"line": fileLine,
03:28:59     runtime:  		}).Info("Invalid state transition skipped")
03:28:59     runtime:  	}
03:28:59     runtime:  	e.logStatusLocked(Other, Warning, fmt.Sprintf("Skipped invalid state transition to %s due to: %s", toState, reason))
03:28:59     runtime: Makefile:233: recipe for target 'precheck' failed
```

**Comment by ianvernon** [comment]
Docs tests passed: https://jenkins.cilium.io/job/Cilium-PR-Doc-Tests/656/
K8s tests passed:  https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1388/

Will not run these again.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
@joestringer the verifier test failed with the CT backport:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8402/testReport/(root)/runtime/RuntimeVerifier_runs_the_kernel_verifier_against_the_tree_copy_of_the_BPF_datapath/

**Comment by ianvernon** [comment]
I'm going to move out the BPF backports from this PR so we can get the other backports merged. I've reached out to Joe about the verifier failure occurring as this may require more involved work to get the change backported (should we decide to backport it given that it causes complexity issues).

**Comment by ianvernon** [comment]
Pushed branch 1.3-backports-18-12-03-with-bpf-ct-backport which will have the BPF backport.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
@ianvernon I cherry-picked 1eb1c18fdf76b144ccbe49703ed92578e1878290 and 53e1f373abf89da26e1a83b3ac6f967205d1b670 onto `1.3-backports-18-12-03-with-bpf-ct-backport` to reduce the complexity, and this seems to allow the local testing to pass for me.

**Review by jrfastab — APPROVED** [review]

**Comment by ianvernon** [comment]
@joestringer OK, I'll cherry-pick those as well onto this PR.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8424/testReport/junit/k8s-1/12/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/

Etcd-operat was not ready after timeout.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by tgraf** [comment]
test-docs-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
