### PR TITLE
CI: WaitForDeploy/Daemonset

### PR DESCRIPTION
**Pull request by ianvernon**
I am taking over the state of https://github.com/cilium/cilium/pull/8110 for @raybejjani .

"WaitForDeployment uses the number of pods configured in k8s to determine
if the deploy is ready. This should be resilient to still-terminated
pods left over from other tests and better reflect what the k8s
scheduler thinks is true.

WaitForDaemonSetReady uses the k8s expected pods to determine that pods
are ready. This sidesteps passing a count to WaitforNPods or passing 0
to cause it to determine the number of pods from those currently
running."

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8615)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]
:clap:

**Comment by ianvernon** [comment]
approved offline by Maciej

**Pull request merged**
