### PR TITLE
ipsec: Add/Fix packet tracing for overlay mode

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
Please see the commit messages for more details.

```release-note
Add missing & fix wrong traces for IPSec + overlay receive path
```

### CODE REVIEW

**Review by kkourt — APPROVED** [review]
LGTM, thanks!

A couple of non-blocking comments:
* I think it would be useful if each commit had an example of messages before and after the patch, to make it even more clear what the change is
* nit: there is a typo in the second commit: "insearted" -> "inserted"

**Review by pchaigno — APPROVED** [review]
Don't forget to set the labels.

**Comment by YutaroHayakawa** [comment]
/test-1.23-net-next

**Comment by YutaroHayakawa** [comment]
Seems the service-related tests are failing. Recently, there are some efforts in that area. I'm not certain if it is related, but rebased with latest master to see what happens.

**Comment by YutaroHayakawa** [comment]
/test-1.21-5.4

**Comment by YutaroHayakawa** [comment]
Now two failures observed
- [Suite-k8s-1.21.K8sPolicyTestExtended Validate toEntities KubeAPIServer Allows connection to KubeAPIServer](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-5.4/577/testReport/junit/Suite-k8s-1/21/K8sPolicyTestExtended_Validate_toEntities_KubeAPIServer_Allows_connection_to_KubeAPIServer/)
- [Suite-k8s-1.21.K8sUpdates Tests upgrade and downgrade from a Cilium stable image to master](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-5.4/577/testReport/junit/Suite-k8s-1/21/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/)

The former one is the variant of https://github.com/cilium/cilium/issues/16928 (which I also reported in the related PR https://github.com/cilium/cilium/pull/18704#issuecomment-1033973342). Again, this PR only contains the BPF changes, so safe to ignore I think.

The latter one is a known flake (https://github.com/cilium/cilium/issues/18873) which has still not been investigated. Likely to be related to the recent tail call change discussed in https://github.com/cilium/cilium/pull/17758. However, since this PR only contains the changes to the tracing and nothing affects the connectivity, I think it's safe to ignore.

**Pull request merged**
