### PR TITLE
v1.10: Update Go to 1.16.10

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.10

**Review by pchaigno — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
/test-backport-1.10

**Comment by tklauser** [comment]
The [net-next failure](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/1908/) looks like #12511 et al. and the respective test has been quarantined on `master` by #17514 for a while due to frequent failures. Doesn't look like it was backported to `v1.10 though, should we?

The [4.9 failure](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/1740/) looks new, thus:

/mlh new-flake Cilium-PR-K8s-1.21-kernel-4.9

**Comment by tklauser** [comment]
test-1.21-4.9

**Comment by tklauser** [comment]
The net-next failure is a known flake, see https://github.com/cilium/cilium/pull/17793#issuecomment-965019660. All other tests passed and required reviews are in. Marking as ready to merge.

**Pull request merged**
