### PR TITLE
v1.17 Backports 2024-12-20

### PR DESCRIPTION
**Pull request by sayboras**
* [x] #36679 (@JacobHenner)
 * [x] #36701 (@alagoutte)
 * [x] #36734 (@sayboras)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 36679 36701 36734
```

### CODE REVIEW

**Comment by julianwiedmann** [comment]
> * [ ]  [gh: e2e-upgrade: add coverage for 6.6 kernel #36626](https://github.com/cilium/cilium/pull/36626) (@julianwiedmann) ⚠️ resolved conflicts
> 
>     * [ ]  [gh: e2e-upgrade: add coverage for 6.12 kernel #36640](https://github.com/cilium/cilium/pull/36640) (@julianwiedmann) ⚠️ resolved conflicts

I see these two in the v1.17 branch, so looks like they made the branch cut-off. Could you please drop them? Sorry for the trouble.

**Review by julianwiedmann — APPROVED** [review]
thank you!

**Review by viktor-kurchenko — APPROVED** [review]

**Pull request merged**
