### PR TITLE
Hide `--install-iptables-rules` agent flag and remove `installIptablesRules` Helm flag

### PR DESCRIPTION
**Pull request by pchaigno**
First commit hides the agent flag. Second commit removes the equivalent Helm flag.

### CODE REVIEW

**Review by joestringer — APPROVED** [review]
I think that enough users are shooting themselves in the foot that it's worth hiding this. It's still useful for development for now. We can re-expose it again once we've addressed #4825.

**Comment by joestringer** [comment]
Should we backport this? Perhaps at least to v1.13?

**Comment by pchaigno** [comment]
> Should we backport this? Perhaps at least to v1.13?

Yep, let's backport to v1.13. I wouldn't backport to older branches because (1) not a bug per se and (2) it's still a Helm flag removal. Plus, I suspect users hitting this as new users, more likely to run on v1.13 than any other release.

**Review by qmonnet — APPROVED** [review]
Looks good.

Unrelated: I note that the rule `/install/kubernetes/cilium/values.yaml.tmpl linguist-language=yml` from .gitattributes doesn't seem to affect the colours of the file snippet here (by contrast, values.yaml is correctly highlighted). I haven't checked if it works on other PRs.

**Comment by pchaigno** [comment]
The changes here are pretty contained and minor. I don't think we need another review. Marking ready to merge.

**Pull request merged**
