### PR TITLE
gateway-api/model: Refactor envoy virtual host

### PR DESCRIPTION
**Pull request by pippolo84**
Refactor the code to generate envoy virtual host routes from HTTPRoutes. The new code is functionally equivalent to the previous one, but relies on some helper functions to improve readability while taking into account every different scenario:

- HTTPS routes
- HTTP routes with Direct Response
- HTTP routes with single backend
- HTTP routes with multiple load-balanced backend

### CODE REVIEW

**Review by nebril — APPROVED** [review]

**Comment by pippolo84** [comment]
/test-1.16-4.9

**Comment by pippolo84** [comment]
/test-1.25-net-next

**Comment by pippolo84** [comment]
/test-1.16-4.9

**Comment by pippolo84** [comment]
/test-1.16-4.9

**Comment by pippolo84** [comment]
/test-1.24-5.4

**Comment by pippolo84** [comment]
/test-1.25-4.19

**Comment by pippolo84** [comment]
/test-1.25-4.19

**Comment by pippolo84** [comment]
Smoke test is hitting [this](https://github.com/cilium/cilium/issues/22168). Marking ready to merge.

**Comment by jrajahalme** [comment]
Only known flakes, merging.

**Pull request merged**
