### PR TITLE
v1.4 backports 2019-01-30

### PR DESCRIPTION
**Pull request by joestringer**
* #6855 -- pkg/client: set new client structure in case of failure (@aanm)
 * #6854 -- kubernetes: Bump cilium-etcd-operator version to 2.0.5 (@tgraf)
 * #6846 -- cilium: return formatted error on ipsec-key-file open failure (@nirmoy)
 * #6844 -- datapath/linux: fix updateTunnelMapping when old and new CIDR are nil (@nirmoy)
 * #6843 -- Don't put empty node ips into special identities (@nebril)
 * #6841 -- Jenkins: Flannel job fixes (@eloycoto)
 * #6835 -- docs: Document ConfigMap option changes in v1.4 (@joestringer)
 * #6816 -- cilium: auto-detect when kernel has ipv6 compiled out and set enable-ipv6 to false (@nirmoy)
 * #6812 -- Update install guides for 1.4.0 (@tgraf)
   * Commit c0d8caa05f6c0de35cd16d2a820754f9218bf7f9 needed to be manually cherry-picked, as the cherry-pick script doesn't like diffs in commit logs.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6858)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-missed-k8s

**Comment by joestringer** [comment]
test-docs-please

**Comment by joestringer** [comment]
One of k8s tests failed due to Cilium preflight checks failing (no kvstore connectivity, #6631):

```
KVStore:                Failure   Err: Not able to connect to any etcd endpoints
```

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1581/execution/node/98/log/

**Review by jrfastab — APPROVED** [review]
LGTM pretty straight forward.

**Comment by joestringer** [comment]
test-missed-k8s

**Review by brb — APPROVED** [review]

**Pull request merged**
