### PR TITLE
Test: Simplified JQ filter on Kubernetes test

### PR DESCRIPTION
**Pull request by eloycoto**
Make it simpler to get Kubernetes version.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6525)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-upstream-k8s

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
@eloycoto is this just an enhancement, or should this change be backported as well? Was there any functionality that wasn't working which necessitated this to be done?

**Comment by eloycoto** [comment]
just an enhancement :-)

**Pull request merged**
