### PR TITLE
[CI] parallel image build and cluster setup for eks

### PR DESCRIPTION
**Pull request by nebril**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9714)

### CODE REVIEW

**Comment by nebril** [comment]
test-eks K8sDemos*

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-eks K8sDemos*

**Comment by nebril** [comment]
test-eks K8sDemos*

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-eks K8sDemos*

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-eks K8sDemos*

**Comment by nebril** [comment]
test-eks K8sDemos*

**Comment by nebril** [comment]
test-eks K8sDemos*

**Review by aanm — APPROVED** [review]
Changes look good. Hope we find out where "default" is coming from.

**Comment by nebril** [comment]
test-eks K8sDemos*

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Pull request merged**
