### PR TITLE
Bump gops to 0.3.16

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
For some reason GH actions didn't trigger. Reopening PR attempting to fix this.

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-runtime

**Comment by tklauser** [comment]
test-1.20-4.9

**Pull request merged**
