### PR TITLE
Envoy 1.12 update

### PR DESCRIPTION
**Pull request by jrajahalme**
Update cilium-proxy to a build from Envoy release 1.12 with Cilium TLS
support patches. Use of the new functionality is added in a follow-on PR.

Backports to 1.6 and 1.5 are needed so that any future Envoy security patches may be applied.

Envoy ORIGINAL_DST_LB load balancer type has been deprecated, use CLUSTER_PROVIDED instead.

Add access log fields 'MissingHeaders' and 'RejectedHeaders':

**MissingHeaders**: HTTP headers that were either added to the request, or headers that were merely logged as missing.

**RejectedHeaders**: HTTP headers that were flagged as invalid by the policy. Depending on the policy these headers may have been removed and the request allowed, or the request may have been denied due to them.

```release-note
Envoy has been updated to release 1.12.
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9542)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
removed needs-backport due envoy regression, @jrajahalme will re-add the label once it's fixed

**Pull request merged**
