### PR TITLE
test: bump k8s version to 1.11.4

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6061)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
build: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1194/

**Review by eloycoto — APPROVED** [review]

**Pull request merged**
