### PR TITLE
bitlpm: Factor out common code

### PR DESCRIPTION
**Pull request by jrajahalme**
Reduce code repetition by defining a 'traverse' function that is shared between multiple functions.

Clarify comments.

### CODE REVIEW

**Review by nathanjsweet — APPROVED** [review]

**Comment by nathanjsweet** [comment]
Looks good!

**Review by christarazi — APPROVED** [review]

**Comment by ldelossa** [comment]
@nathanjsweet should this be merged without test suite running?

**Comment by nathanjsweet** [comment]
@ldelossa Sorry, yeah. I should have said that.

**Pull request merged**
