### PR TITLE
aws/eni: fix cilium operator crash on IPv6 ENI

### PR DESCRIPTION
**Pull request by bimmlerd**
Cilium operator would crash when being brought up in an AWS region where there was a IPv6-only ENI and no subnet filters, because it would fail to parse the ENI (logs will show `ENI has no IP address` and `Initial synchronization with instances API failed`). 

We work around this issue for the moment by filtering the network interfaces we fetch from AWS with `'private-ip-addresses=*'`, which includes all ENIs with any value in the PrivateIpAddress field. This is the field `parseENI` complains about otherwise. 

In general, though, it seems that the ENI IPAM mode needs to learn to handle IPv6 ENIs. There are unsolved challenges (such as representing the IP pool as a list of addresses, which will not work for IPv6), however,  which cannot be addressed quickly, so we work around it for now.

cc @gandro @chanieljdan @bmcustodio 

```release-note
Prevent cilium operator crash in AWS region with IPv6-only ENIs without subnet filters.
```

### CODE REVIEW

**Comment by bimmlerd** [comment]
Should I also create a ticket for this to make it more discoverable?

Also, do we want to backport this?

**Comment by gandro** [comment]
I don't think we necessarily need an issue here, the PR already describes it well enough. 

Let's backport this to the latest stable, as it is a regular bug fix.

**Review by gandro — APPROVED** [review]

**Review by christarazi — APPROVED** [review]
Good find and thanks for the fix. I'm wondering if it would also be worthwhile to update the docs to mention that Cilium only supports IPv4 ENIs.

**Comment by bimmlerd** [comment]
> Good find and thanks for the fix. I'm wondering if it would also be worthwhile to update the docs to mention that Cilium only supports IPv4 ENIs.

I've added a sentence. I guess we track this in https://github.com/cilium/cilium/issues/18405, and https://github.com/cilium/cilium/issues/19251 is related. Do we link to issues in the docs, e.g. something like "work on implementing this is tracked in xyz?"

**Comment by christarazi** [comment]
@bimmlerd I've seen it done before, so yes.

**Comment by joestringer** [comment]
>  Do we link to issues in the docs, e.g. something like "work on implementing this is tracked in xyz?"

Yes, there is even built-in syntax for it: :gh-issue:`19251` would link to #19251, for instance.

**Comment by christarazi** [comment]
Ah yes, thanks Joe. I remember we had done it by I forgot about this incantation.

**Review by joestringer — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Comment by joestringer** [comment]
I've filed https://github.com/cilium/cilium/issues/22217 for the ConformanceKind1.19 failure. This seems likely to be broken on master somehow.

**Pull request merged**
