### PR TITLE
Fix IPv4 CIDR lookup on older kernels

### PR DESCRIPTION
**Pull request by joestringer**
Fixes: #3352

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]
lgtm

**Review by tgraf — APPROVED** [review]

**Comment by ianvernon** [comment]
Given that BPF experts have approved, I'm taking their approval as approval for the CI portion :)

**Review by ianvernon — APPROVED** [review]

**Comment by joestringer** [comment]
This PR falied the upgrade test when it merged into master, but I'm not sure if it was just a test flake.

**Pull request merged**
