### PR TITLE
ci: Run cilium sysdump in conformance-ginkgo

### PR DESCRIPTION
**Pull request by chancez**
To make it easier to debug test failures in ginkgo.

### CODE REVIEW

**Comment by julianwiedmann** [comment]
odd, how does this match up with https://github.com/cilium/cilium/blob/17516f1c648c21c1c59b74d89e56a1f3d804cf43/test/helpers/kubectl.go#L3292 ?

Can you share a failed run where the sysdump was missing?

**Comment by aanm** [comment]
> odd, how does this match up with
> 
> https://github.com/cilium/cilium/blob/17516f1c648c21c1c59b74d89e56a1f3d804cf43/test/helpers/kubectl.go#L3292
> 
> ?
> Can you share a failed run where the sysdump was missing?

Yeah, the sysdump should be part of the failed runs.

**Comment by chancez** [comment]
Oh interesting. Here's an example run: https://github.com/cilium/cilium/actions/runs/8821913059 it only has the test results in the cilium-sysdumps.zip

**Comment by aanm** [comment]
> Oh interesting. Here's an example run: https://github.com/cilium/cilium/actions/runs/8821913059 it only has the test results in the cilium-sysdumps.zip

@chancez wasn't that what you were looking for? Each test result has its own sysdump.

**Pull request closed without merging**
