### PR TITLE
api: Add extensions field to observer.GetFlowsRequest and flow.Flows types

### PR DESCRIPTION
**Pull request by chancez**
In order to facilitate building new features to extend the Hubble API, introduce a new extensions field on GetFlowsRequest and Flow.

This enables vendors to add additional metadata in requests and responses to enhance or change the behavior of Hubble itself, or Hubble compatible APIs without changing the public API.

```release-note
api: Add extensions field to observer.GetFlowsRequest and flow.Flows types
```

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]
🥰🥰🥰

**Review by kaworu — APPROVED** [review]

**Comment by joestringer** [comment]
@chancez Is this user-facing? Typically we reserve `release-note/minor` for release notes that our users may peruse and take action on. For API changes that users don't directly interact with, I'd typically put them under `release-note/misc`. This doesn't reflect that the change is any less important or impactful, just whether or not users can leverage the change.

**Comment by chancez** [comment]
@joestringer I guess I figured our API is public facing, but in practical terms, this doesn't impact users.

**Pull request merged**
