### PR TITLE
v1.15 Backports 2024-05-24

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
* [x] #32328 (@joestringer)
 * [ ] #32017 (@mikemykhaylov)
 * [ ] #32307 (@ferozsalam)
 * [x] #32513 (@giorio94)
 * [x] #32536 (@harsimran-pabla) :warning: resolved conflicts
 * [ ] #32464 (@darox)
 * [x] #32553 (@michi-covalent)
 * [ ] #32564 (@jibi) :warning: resolved conflicts
 * [ ] #32548 (@squeed)
 * [x] #32570 (@mhofstetter)
 * [x] #32506 (@joamaki)
 * [x] #32450 (@jschwinger233)
 * [ ] #32600 (@mhofstetter) :warning: resolved conflicts
 * [x] #32302 (@marseel) :warning: resolved conflicts
 * [ ] #32629 (@antonipp) :warning: resolved conflicts

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 32084 32328 32017 32307 32513 32536 32464 32553 32564 32548 32570 32506 32450 32600 32302 32629
```

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
Thanks! My commit looks good

**Review by michi-covalent — APPROVED** [review]
ty~!

**Review by mhofstetter — APPROVED** [review]
Thanks Yutaro! My commits look good.

**Review by ferozsalam — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
Approving for backport of my PR. I also glanced through my codeowners and nothing obvious seemed out of place (though I would delegate to the original authors if they have specific concerns)

**Review by harsimran-pabla — APPROVED** [review]

**Review by marseel — APPROVED** [review]

**Review by jschwinger233 — APPROVED** [review]

**Review by joamaki — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
/test-backport-1.15

**Review by lmb — APPROVED** [review]

**Review by pchaigno — DISMISSED** [review]
I think my commit was already backported because it's empty here. Didn't git complain?

**Review by marseel — CHANGES_REQUESTED** [review]
It seems that GKE failures are due to my commit.

Here we have:
```
      - name: Set up gcloud credentials
        id: 'auth'
        uses: google-github-actions/auth@71fee32a0bb7e97b4d33d548e7d957010649d8fa # v2.1.3
        with:
          credentials_json: '${{ secrets.GCP_PR_SA_KEY }}'
```

but backported/on main version is:
```
      - name: Set up gcloud credentials
        id: 'auth'
        uses: google-github-actions/auth@55bd3a7c6e2ae7cf1877fd1ccb9d54c0503c457c # v2.1.2
        with:
          workload_identity_provider: ${{ secrets.GCP_PR_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_PR_SA }}
          create_credentials_file: true
          export_environment_variables: true
```

The diff comes from the fact that https://github.com/cilium/cilium/pull/30809 wasn't backported, we might want to backport it too, but let's hear from @viktor-kurchenko

**Review by darox — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
> I think my commit was already backported because it's empty here. Didn't git complain?

Yeah, it indeed complained as `deleted by them`, but I didn't realize it means the backport is already there. Let me drop your PR.

**Comment by YutaroHayakawa** [comment]
Made a stand-alone PR here to fix Marceel's issue: https://github.com/cilium/cilium/pull/32707

**Comment by YutaroHayakawa** [comment]
Rebased on top of the latest v1.15 to pull-in https://github.com/cilium/cilium/pull/32707.

**Comment by YutaroHayakawa** [comment]
/test-backport-1.15

**Review by marseel — APPROVED** [review]
Looks like GKE tests work now, thanks!

**Pull request merged**
