### PR TITLE
[only-for-testing] Test SA refactoring + udp fix on 5.4

### PR DESCRIPTION
**Pull request by aditighag**

### CODE REVIEW

**Comment by aditighag** [comment]
test-1.19-5.4

**Comment by aditighag** [comment]
test-1.19-5.4

**Comment by aditighag** [comment]
test-1.19-5.4

**Comment by aditighag** [comment]
test-1.19-5.4

**Comment by aditighag** [comment]
test-1.19-5.4

**Comment by aditighag** [comment]
test-1.19-5.4

**Comment by ti-mo** [comment]
Looks like @github-actions is stepping on its own toes here. Can this one be closed? Apparently it's still in my review queue.

**Pull request closed without merging**
