### PR TITLE
bpf: Add VTEP redirection bpf_host complexity tests

### PR DESCRIPTION
**Pull request by vincentmli**
VTEP support L7 proxy through bpf_host, add complexity
test for VTEP in bpf_host.

Signed-off-by: Vincent Li <v.li@f5.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
add vtep bpf complexity test in bpf_host
```

### CODE REVIEW

**Review by NikAleksandrov — APPROVED** [review]
The change looks good to me, I don't think the build failure is related to it (pull limit hit).

**Comment by aanm** [comment]
@vincentmli it look the PR needs to be rebased. Could you do that please? Thank you!

**Comment by vincentmli** [comment]
@aanm rebase done

**Comment by vincentmli** [comment]
@aanm I did another rebase to resolve the conflict

**Comment by vincentmli** [comment]
@aanm this is another rebase, previous rebase and test sees no problem, I presume it is safe to merge? :)

**Comment by vincentmli** [comment]
> /test
> 
> Job 'Cilium-PR-K8s-1.23-kernel-4.19' failed:
> 
> Click to show.
> ### Test Name
> ```
> K8sServicesTest Checks graceful termination of service endpoints Checks client terminates gracefully on service endpoint deletion
> ```
> 
> ### Failure Output
> ```
> FAIL: Timed out after 60.001s.
> ```

it appears to be  https://github.com/cilium/cilium/issues/18447, don't think related to this PR since this PR only applies to 5.4 and netnext kernel. @aanm, I think it is safe to merge this PR, I don't want to delay and do rebase again and again :-)

**Pull request merged**
