### PR TITLE
identity: Wait for initial set of security identities before restoring endpoints

### PR DESCRIPTION
**Pull request by tgraf**
Fixes: #5290

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5291)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by tgraf** [comment]
Hit https://github.com/cilium/cilium/issues/5292

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
Kafka DNS resolution issue. Not sure what the right issue is to assign to, we have a lot of DNS related CI flakes.

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by tgraf** [comment]
CI failure: Unable to build endpoints due to builds taking too long. Unlikely related to these changes.

**Comment by tgraf** [comment]
test-me-please

hit #5204

**Comment by tgraf** [comment]
test-me-please

**Comment by jrfastab** [comment]
backport-pending/1.1 should get its tag pushed to needs-backport/1.1 because I pulled it out of the backports due to it apparently introducing a flake.

**Comment by ianvernon** [comment]
@jrfastab I am doing 1.1 backports - do you know exactly what the notion of the flake is that caused this to no longer be backported?

**Comment by jrfastab** [comment]
@ianvernon this fell off my queue, I don't recall what the specific issue was I bisected to this patch and removed. After removing it the CI passed successfully.

**Comment by borkmann** [comment]
Dropping `needs-backport/1.1` as per discussion with @tgraf.

**Pull request merged**
