### PR TITLE
bump k8s dependencies and test to v1.18.3

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
```
16:14:06  fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
16:14:06  fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
16:14:06  ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.9/main: temporary error (try again later)
[2020-05-25T14:14:06.460Z] WARNING: Ignoring APKINDEX.b89edf6e.tar.gz: No such file or directory
[2020-05-25T14:14:06.460Z] ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.9/community: temporary error (try again later)
[2020-05-25T14:14:06.460Z] WARNING: Ignoring APKINDEX.737f7e01.tar.gz: No such file or directory
[2020-05-25T14:14:06.460Z] ERROR: unsatisfiable constraints:
[2020-05-25T14:14:06.460Z]   ca-certificates (missing):
```

**Review by nebril — APPROVED** [review]

**Comment by aanm** [comment]
retest-4.19

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
retest-4.9

**Review by qmonnet — APPROVED** [review]

**Pull request merged**
