### PR TITLE
v1.7 backports 2020-07-08

### PR DESCRIPTION
**Pull request by vadorovsky**
* #12185 -- cilium: chaining mode skb->mark can be mangled by iptables allow opt-out (@jrfastab)
 * #12194 -- cilium: fix helm usage of enableIdentityMap -> enableIdentityMark (@jrfastab)
 * #12291 -- docs: add instructions for vX.Y helm charts (@aanm)
 * #12351 -- contrib: Add ability to pass suffix for branch  (@christarazi)
 * #12361 -- contrib: fix branch check in `start-backport` script (@Rolinh)
 * #11236 -- Add an option to cilium-agent for disabling 'HealthCheckNodePort' (@soumynathan)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12185 12194 12291 12351 12361 11236; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by mrostecki** [comment]
test-backport-1.7

**Comment by brb** [comment]
The failures look legit:
```
14:01:49  # github.com/cilium/cilium/pkg/service
[2020-07-08T12:01:49.812Z] ../pkg/service/service.go:125:5: undefined: option
[2020-07-08T12:01:49.812Z] ../pkg/service/service.go:246:6: undefined: option
[2020-07-08T12:01:49.812Z] ../pkg/service/service.go:611:5: undefined: option
[2020-07-08T12:01:49.812Z] Makefile:8: recipe for target 'cilium' failed
14:01:49  make[1]: Leaving directory '/go/src/github.com/cilium/cilium/cilium'
14:01:49  make[1]: *** [cilium] Error 2
[2020-07-08T12:01:49.812Z] make: *** [build-container] Error 2
[2020-07-08T12:01:49.812Z] Makefile:81: recipe for target 'build-container' failed
14:01:51  The command '/bin/sh -c make LOCKDEBUG=$LOCKDEBUG PKG_BUILD=1 V=$V LIBNETWORK_PLUGIN=$LIBNETWORK_PLUGIN     SKIP_DOCS=true DESTDIR=/tmp/install clean-container build-container install-container' returned a non-zero code: 2
14:01:51  Makefile:209: recipe for target 'docker-image-no-clean' failed
14:01:51  make: *** [docker-image-no-clean] Error 2
```

**Comment by mrostecki** [comment]
test-backport-1.7

**Review by christarazi — APPROVED** [review]
LGTM for my changes. I noticed that the PRs listed are not marked as "pending". Could you please mark them (the script should do it for you)? This helps reduce any conflict in case another backporter starts a 1.7 backport.

**Comment by mrostecki** [comment]
CI is complaining about bindata:

```
14:39:52    CHECK contrib/scripts/bindata.sh
14:39:52  ../contrib/scripts/bindata.sh 4c9cc3d2d8462a47feff46ddfe344e0396d955b6
14:39:52  sha1sum: WARNING: 1 computed checksum did NOT match
[2020-07-08T14:39:52.094Z] bindata.go: FAILED
14:39:52  ########################################################################
14:39:52  
14:39:52                    ERROR: bindata.go is out of date.
14:39:52  
14:39:52   This can happen for two reasons:
14:39:52   1. You are using a go-bindata binary compiled with a different version
14:39:52      of golang (not 1.13.12). If so, please up/downgrade.
14:39:52  
14:39:52   2. You have made changes to the bpf/ directory. Please run the
14:39:52      following command to update the SHA in daemon/bpf.sha:
14:39:52  
14:39:52      $ make -C daemon apply-bindata
14:39:52  
14:39:52  ########################################################################
14:39:52  make[1]: *** [check-bindata] Error 1
[2020-07-08T14:39:52.094Z] Makefile:53: recipe for target 'check-bindata' failed
14:39:52  make[1]: Leaving directory '/go/src/github.com/cilium/cilium/daemon'
14:39:52  Makefile:81: recipe for target 'build-container' failed
14:39:52  make: *** [build-container] Error 2
[2020-07-08T14:39:52.770Z] The command '/bin/sh -c make LOCKDEBUG=$LOCKDEBUG PKG_BUILD=1 V=$V LIBNETWORK_PLUGIN=$LIBNETWORK_PLUGIN     SKIP_DOCS=true DESTDIR=/tmp/install clean-container build-container install-container' returned a non-zero code: 2
14:39:52  Makefile:209: recipe for target 'docker-image-no-clean' failed
14:39:52  make: *** [docker-image-no-clean] Error 2
```

although this PR doesn't change any `bpf/` files.

**Comment by mrostecki** [comment]
@christarazi Sorry for that, I totally forgot about running the set-labels script.

**Comment by mrostecki** [comment]
test-backport-1.7

**Review by aanm — APPROVED** [review]
looks good for my changes

**Comment by mrostecki** [comment]
Failure:

```
11:46:36  • Failure in Spec Setup (BeforeEach) [267.302 seconds]
11:46:36  K8sServicesTest
11:46:36  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.12-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
11:46:36    External services
11:46:36    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.12-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
11:46:36      To Services first endpoint creation [BeforeEach]
11:46:36      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.12-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
11:46:36  
11:46:36      Endpoints are not ready after timeout
[2020-07-09T09:46:36.139Z]     Expected
[2020-07-09T09:46:36.139Z]         <*helpers.SSHMetaError | 0xc0012c9040>: Error: context deadline exceeded
[2020-07-09T09:46:36.139Z]     Extended info: 	Cilium Pod: cilium-dt9zt 	Endpoint: 372 	Identity: 5	 State: ready
[2020-07-09T09:46:36.139Z]     	Cilium Pod: cilium-dt9zt 	Endpoint: 3070 	Identity: 4	 State: ready
[2020-07-09T09:46:36.139Z]     	Cilium Pod: cilium-nwp8z 	Endpoint: 1484 	Identity: 21866	 State: ready
[2020-07-09T09:46:36.139Z]     	Cilium Pod: cilium-nwp8z 	Endpoint: 1904 	Identity: 39889	 State: ready
[2020-07-09T09:46:36.139Z]     	Cilium Pod: cilium-nwp8z 	Endpoint: 3014 	Identity: 4	 State: ready
[2020-07-09T09:46:36.139Z]     
[2020-07-09T09:46:36.139Z]     
[2020-07-09T09:46:36.139Z]     to be nil
11:46:36  
11:46:36      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.12-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:846
```

**Comment by joestringer** [comment]
Looks like known flake https://github.com/cilium/cilium/issues/10442 .

**Pull request merged**
