### PR TITLE
v1.12 backports 2022-09-07 (for ingress)

### PR DESCRIPTION
**Pull request by sayboras**
* #20860 -- ingress: Propagate required annotations from Ingress to LB Service (@NikhilSharmaWe)
* #21222 --ingress: Rename LB annotation to annotation prefixes (@sayboras )

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20860 21222; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Comment by sayboras** [comment]
Manual backport this to 1.12 due to some conflict.

**Comment by sayboras** [comment]
/test-backport-1.12

**Comment by sayboras** [comment]
Couple of failures in CI are unrelated to this change. The most important job (e.g. ConformanceIngress) is passed.

https://github.com/cilium/cilium/runs/8225952460?check_suite_focus=true

**Comment by chancez** [comment]
Seems like this PR is having failures on egress gateway tests, which I also found in my PR #21079 and was originally reported here: https://github.com/cilium/cilium/issues/18012

**Comment by sayboras** [comment]
Thanks for your info, I didn't take a closer look on CI failures.

**Review by nebril — CHANGES_REQUESTED** [review]
I think you committed some tmp files not present in original PR?

**Comment by sayboras** [comment]
/test-backport-1.12

**Review by nebril — APPROVED** [review]

**Comment by sayboras** [comment]
/test-backport-1.12

**Review by michi-covalent — APPROVED** [review]

**Comment by sayboras** [comment]
Seems like there is something wrong with 4.9 kernel version, I don't think it's related to this change.

The most important job (e.g. ConformanceIngress) is passing, so marking this ready to merge.

**Comment by nebril** [comment]
jenkins failures are mostly verifier errors which should be fixed on 1.12 already. Merging

**Pull request merged**
