### PR TITLE
Adding support for tracking instance hypervisor type in ENI limits pkg

### PR DESCRIPTION
**Pull request by tommyp1ckles**
[ upstream commit 2cd83ee6db83d51980f637176becab7fd51dbd0e ]

Signed-off-by: Hemanth Malla <hemanth.malla@datadoghq.com>
Signed-off-by: Tom Hadlaw <tom.hadlaw@isovalent.com>

Please ensure your pull request adheres to the following guidelines:

Backporting recent update to the eni limits map so that v1.10 has up to date list, as well as recent changes to the limit structure so that we can easily backport these updates in the future.

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@tommyp1ckles the CI failure is legitimate.

**Comment by tommyp1ckles** [comment]
/test-backport-v1.11

**Comment by tommyp1ckles** [comment]
/test-1.22-5.4

**Comment by tommyp1ckles** [comment]
/test-1.24-net-next

**Comment by tommyp1ckles** [comment]
/test-1.22-5.4

**Comment by tommyp1ckles** [comment]
/test-1.24-net-next

**Comment by tommyp1ckles** [comment]
/test-backport-1.11

**Comment by tommyp1ckles** [comment]
/test-ci-aks-1.11

**Comment by tommyp1ckles** [comment]
/ci-aks-1.11

**Comment by tommyp1ckles** [comment]
/test-backport-1.11

**Comment by tommyp1ckles** [comment]
/test-backport-1.11

**Comment by tommyp1ckles** [comment]
/test-1.22-4.19

**Comment by tommyp1ckles** [comment]
/test-gke-1.11

**Comment by tommyp1ckles** [comment]
/ci-gke-1.11

**Pull request merged**
