### PR TITLE
Some extra vndr cleanup

### PR DESCRIPTION
**Pull request by dqminh**
Notably:
- bump etcd to v3.2.1, the original switch to vendor.conf missed that independent change
- also remove Godeps manifest, the original switch missed that too
- remove prometheus related dependencies. vndr detected that they are unused and removed them. Looks like we indeed dont use prometheus in the code. One possible usage for this is for etcd metrics with grpc-prometheus gateway, but we dont configure that option.

### CODE REVIEW

**Review by aanm — COMMENTED** [review]
Are the etcd `vendor/` files up do date with `v3.2.1`?

**Comment by dqminh** [comment]
@aanm yah they should be up to date with `3.2.1`. I double-checked the content.

I think the original `3.1.0` downgrade in `vendor.conf` was an error from my part when doing the move where i vendor with `3.2.1` but didnt actually commit the `vendor.conf` change. Rerun vendor with `3.1.0` in the manifest shows these changes:

```
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   vendor/github.com/coreos/etcd/auth/authpb/auth.pb.go
        modified:   vendor/github.com/coreos/etcd/clientv3/README.md
        modified:   vendor/github.com/coreos/etcd/clientv3/auth.go
        modified:   vendor/github.com/coreos/etcd/clientv3/balancer.go
        modified:   vendor/github.com/coreos/etcd/clientv3/client.go
        modified:   vendor/github.com/coreos/etcd/clientv3/cluster.go
        modified:   vendor/github.com/coreos/etcd/clientv3/compare.go
        modified:   vendor/github.com/coreos/etcd/clientv3/concurrency/election.go
        modified:   vendor/github.com/coreos/etcd/clientv3/concurrency/key.go
        modified:   vendor/github.com/coreos/etcd/clientv3/concurrency/mutex.go
        modified:   vendor/github.com/coreos/etcd/clientv3/concurrency/session.go
        modified:   vendor/github.com/coreos/etcd/clientv3/concurrency/stm.go
        modified:   vendor/github.com/coreos/etcd/clientv3/config.go
        modified:   vendor/github.com/coreos/etcd/clientv3/kv.go
        modified:   vendor/github.com/coreos/etcd/clientv3/lease.go
        modified:   vendor/github.com/coreos/etcd/clientv3/maintenance.go
        modified:   vendor/github.com/coreos/etcd/clientv3/op.go
        modified:   vendor/github.com/coreos/etcd/clientv3/txn.go
        modified:   vendor/github.com/coreos/etcd/clientv3/watch.go
        deleted:    vendor/github.com/coreos/etcd/clientv3/yaml/config.go
        modified:   vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/rpctypes/error.go
        modified:   vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/etcdserver.pb.go
        modified:   vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/raft_internal.pb.go
        modified:   vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go
        modified:   vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.proto
        modified:   vendor/github.com/coreos/etcd/mvcc/mvccpb/kv.pb.go

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.gw.go
```

which looks expected.

**Comment by aanm** [comment]
Why is `vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.gw.go` untracked?

**Comment by dqminh** [comment]
> Why is vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.gw.go untracked?

@aanm ah, this was just a changelog to show what a downgrade from 3.2 -> 3.1 would look like. That proto file was moved into a separate package in etcd 3.2

**Comment by aanm** [comment]
@dqminh Can you rebase your PR?

**Review by aanm — APPROVED** [review]

**Pull request merged**
