### PR TITLE
v1.16 Backports 2024-10-25

### PR DESCRIPTION
**Pull request by tklauser**
* [ ] #33998 (@marseel)
 * [x] #34755 (@julianwiedmann)
 * [x] #35349 (@giorio94)
 * [ ] #35306 (@jrife) :warning: resolved conflicts
   * Conflicts in `go.mod` for the netlink package, kept the version from the PR and ran `go mod tidy && go mod vendor`. Also had to pull in changes to adjust Cilium code to the changed mask type in the new netlink library version (`int` to `uint32`).
 * [ ] #35390 (@baurmatt)
 * [ ] #35293 (@squeed)
 * [x] #35173 (@smagnani96) :warning: resolved conflicts
   * Dropped cilium-cli changes as `v1.16` does not have the `cilium-cli/` directory and the version on `main` supports and is used on all stable branches.

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33998 34755 35349 35306 35390 35293 35173
```

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.16

**Review by jrife — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
My commit looks good. Thanks!

**Review by julianwiedmann — APPROVED** [review]

**Comment by julianwiedmann** [comment]
oh, netlink build failures :(. For reference, Andre fixed this up in `main` with f6031e2f7da6ee8bdac5f15fb8beaf8b8312d5b3.

**Comment by tklauser** [comment]
> oh, netlink build failures :(. For reference, Andre fixed this up in `main` with [f6031e2](https://github.com/cilium/cilium/commit/f6031e2f7da6ee8bdac5f15fb8beaf8b8312d5b3).

Thanks. I've pulled these fixes into the commit updating the netlink lib.

**Comment by tklauser** [comment]
/test-backport-1.16

**Review by smagnani96 — APPROVED** [review]
LGTM! Thanks for dropping cli changes from the commits :+1:

**Pull request merged**
