### PR TITLE
README: Add SGW podcast and Docker summit preso

### PR DESCRIPTION
**Pull request by tgraf**

### CODE REVIEW

**Comment by aanm** [comment]
LGTM, but how about we put dates on it?

**Comment by tgraf** [comment]
Sure, will do. Daniel also mentioned that the FOSDEM slides are a duplicate from the NetDev slides so I'll drop those again.

**Comment by tgraf** [comment]
Ping @aanm

**Comment by aanm** [comment]
Add these videos to the presentations:
- https://www.youtube.com/watch?v=GwT9hRiqdUo
- https://www.youtube.com/watch?v=KHXxSN5vwHY

**Pull request merged**
