### PR TITLE
gateway-api: Bump the version to v0.8.1

### PR DESCRIPTION
**Pull request by sayboras**

### CODE REVIEW

**Review by nbusseneau — APPROVED** [review]

**Review by lmb — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]
Looks OK as far as I can tell. Doc change is good.

**Review by youngnick — APPROVED** [review]
LGTM, thanks @sayboras

**Review by meyskens — APPROVED** [review]
LGTM for me

**Review by rolinh — APPROVED** [review]
Vendor changes lgtm.

**Pull request merged**
