### PR TITLE
[v1.13] Author Backport of 28352 (Split mapstate keys into allow and deny)

### PR DESCRIPTION
**Pull request by pippolo84**
* [ ] #28352 (@bimmlerd)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 28352
```

### CODE REVIEW

**Comment by pippolo84** [comment]
/test-backport-1.13

**Comment by pippolo84** [comment]
/test-1.25-4.19)

**Comment by christarazi** [comment]
/test-1.25-4.19

**Comment by pippolo84** [comment]
/test-backport-1.13

**Comment by christarazi** [comment]
I'm assuming we still want this PR @pippolo84?

**Pull request closed without merging**
