### PR TITLE
images: use /usr/bin/env bash instead of /bin/bash

### PR DESCRIPTION
**Pull request by MrFreezeex**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
use /usr/bin/env bash instead of /bin/bash in images dir
```

### CODE REVIEW

**Comment by gandro** [comment]
Approved the image builder workflow (needed to rebuild runtime/builder base images required for changes to `images/`). Once it passed, CI should re-run

**Review by gandro — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Comment by MrFreezeex** [comment]
Hmm should I rebase for the travis test that timed out and the other tests not launching?

**Comment by gandro** [comment]
We did have a recent Jenkins outage, the failing `/test` likely has a different cause. Let's try again

**Comment by nbusseneau** [comment]
The net-next failure is https://github.com/cilium/cilium/issues/25605 and not caused by this PR.

**Comment by gandro** [comment]
Relevant CI passed (or has known flakes) and the image build (which executes the script here) was successful in the critical phase: https://github.com/cilium/cilium/actions/runs/5025428977/jobs/9012381931

The "Push change to PR" stage failed because the source branch here is on a fork. @MrFreezeex manually pushed the changes to the PR in commit https://github.com/cilium/cilium/pull/25558/commits/2ce3e1b5008bb6f86380889f2e8acab7530f677d - which looks identical to what CI was pushing. This is also partially confimred by the follow-up run, which is green: https://github.com/cilium/cilium/actions/runs/5045936115/jobs/9050828649

I'm marking this ready to merge.

**Pull request merged**
