### PR TITLE
v1.8 backports 2020-10-02

### PR DESCRIPTION
**Pull request by errordeveloper**
* #13297 -- docs: add initial performance guide doc (@borkmann)
 * #13267 -- helm: configurable nodeSelector and tolerations for all charts (@mvisonneau)
 * #13318 -- docs: Clarify session affinity support on <5.7 (@pchaigno)
 * ~#13324 -- hubble: Support `--since` requests in combination with follow-mode (@gandro)~
 * #13355 -- documentation: performance evaluation improvements (@kkourt)
 * #13346 -- datapath: Support enable-endpoint-routes with encapsulation (@tgraf)
 * #13146 -- doc: fixes markdown in hostnet policy troubleshooting (@jedsalazar)
 * #13342 -- bugtool: get bpffs mountpoint from /proc/mounts (@jibi)
 * #13357 -- contrib: Improve start-release.sh script (@joestringer)
 * #13325 -- fsnotify: correctly check for event operation (@kAworu)
 * #13369 -- install: Add explicit RBAC permissions for finalizers subresources (@errordeveloper)
 * #13377 -- docs: Move scale and perf guides to Operations (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13297 13267 13318 13355 13346 13146 13342 13357 13325 13369 13377; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by errordeveloper** [comment]
test-me-please

**Review by pchaigno — CHANGES_REQUESTED** [review]
There's still one documentation error:
```
Please fix the following documentation warnings:
/src/Documentation/operations/system_requirements.rst:170: WARNING: undefined label: bandwidth-manager (if the link has no caption the label must precede a section header)
```
Should be easy to fix with `git rebase --exec "make render-docs" master`.

**Comment by errordeveloper** [comment]
@pchaigno I just deleted the line, sounds like "bandwidth manager" is a 1.9 feature... 🤔

**Comment by pchaigno** [comment]
> @pchaigno I just deleted the line, sounds like "bandwidth manager" is a 1.9 feature... thinking

@errordeveloper Yes, that's correct.

**Comment by errordeveloper** [comment]
@pchaigno for the rest, are you changes looking OK? I think most of them have applied cleanly.

**Review by pchaigno — APPROVED** [review]
My documentation changes look good. I checked the result by running `make render-docs` rather than checking the code changes since there are a lot of code changes.

**Review by kkourt — APPROVED** [review]
LGTM for my patches.

**Comment by errordeveloper** [comment]
@Rolinh I'm dropping #13324 as discussed, since conflicts are beyond trivial and deserve a separate PR.

**Comment by errordeveloper** [comment]
test-me-please

**Comment by errordeveloper** [comment]
test-gke

**Comment by errordeveloper** [comment]
test-k8s-1.19

**Comment by pchaigno** [comment]
test-backport-1.8

**Review by kaworu — APPROVED** [review]
LGTM for my patches, thanks!

**Comment by pchaigno** [comment]
retest-4.19

**Comment by errordeveloper** [comment]
So I can see this in Jenkins:
```
14:32:58  make[1]: Leaving directory '/home/jenkins/workspace/Cilium-PR-K8s-GKE/src/github.com/cilium/cilium'
14:32:59  The push refers to repository [147.75.55.179/cilium/cilium]
14:32:59  Get https://147.75.55.179/v2/: x509: cannot validate certificate for 147.75.55.179 because it doesn't contain any IP SANs
```
It looks like an issue with local registry.

**Comment by nebril** [comment]
@errordeveloper let's retest for both failed builds, just to be on the safe side (K8s-1.19-kernel-4.9 failed on provisioning).

**Comment by nebril** [comment]
test-gke

**Comment by nebril** [comment]
test-4.9

**Comment by pchaigno** [comment]
The builds that failed due to provisioning issues are not required for backport PRs (is it even expected that they fail?). All other builds are passing, so marking as `ready-to-merge`.

**Review by gandro — APPROVED** [review]

**Comment by tgraf** [comment]
Was too late, reviewed my backported commit. LGTM 👍

**Comment by errordeveloper** [comment]
Labels updated.

**Pull request merged**
