### PR TITLE
Reorganize Hubble docs

### PR DESCRIPTION
**Pull request by chancez**
To better support continued expansion of the Hubble documentation, we need somewhere to put documentation related to Hubble configuration somewhere besides the getting started section. We already have the hubble export documentation in the Observability section, so let's add a new "Network Observability with Hubble" section under the Observability section to the docs where we can add more structure to the documentation around Hubble. 

The new section will focus primarily on network observability, ie: ways to access Hubble flows, either through the API or through file export, and how to configure these features. This means we're keeping Hubble metrics documentation in the Monitoring & Metrics section, instead of consolidating it under this new Hubble section. This gives the existing Hubble TLS documentation a better home (as it's not really a "getting started" topic), and provides us a place where we can link to using Hubble CLI instead of trying to embed the instructions into the relevant pages. This allows us to expand the current usage documentation for Hubble CLI, to better support future usage docs around using CEL, and other Hubble CLI filters.

### CODE REVIEW

**Review by youngnick — APPROVED** [review]
LGTM from sig-servicemesh.

**Review by derailed — APPROVED** [review]
@chancez LGTM

**Review by tklauser — APPROVED** [review]

**Comment by chancez** [comment]
Rebasing to pick up CI fixes

**Review by ghost — APPROVED** [review]
nice, looks good

**Pull request merged**
