### PR TITLE
fqdn: Avoid races when updating global cache on GC

### PR DESCRIPTION
**Pull request by raybejjani**
We attempted to avoid locking the main cache while updating expired
entries from endpoints. This left a small window where an entry is
removed from the global cache outright but hasn't been re-populated by
endpoints. This would only manifest when a DNS lookup existed in
multiple endpoints but one had evicted the entry.
The new code holds the global cache's lock while clearing and updating
from all endpoint caches, avoiding the race.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9483)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Pull request merged**
