### PR TITLE
v1.13 Backports 2024-02-29

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
* [x] #30742 (@qmonnet)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30742
```

### CODE REVIEW

**Comment by YutaroHayakawa** [comment]
/test-backport-1.13

**Review by aanm — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]
Thanks!

**Comment by YutaroHayakawa** [comment]
/test-backport-1.13

**Review by ldelossa — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
[Cilium IPsec upgrade](https://github.com/cilium/cilium/actions/runs/8097638182): 1.1.1.1 timeout
[Conformance IPsec E2E](https://github.com/cilium/cilium/actions/runs/8097637678): 1.1.1.1 timeout
[k8s-1.21-kernel-4.19](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.19/407/): https://github.com/cilium/cilium/issues/30802

**Comment by YutaroHayakawa** [comment]
/test-1.21-4.19

**Pull request merged**
