### PR TITLE
Add NetBird to the Cilium user list

### PR DESCRIPTION
**Pull request by braginini**
Add NetBird to the Cilium user list

### CODE REVIEW

**Comment by xmulligan** [comment]
Thanks for the addition! In the description, can you talk a little bit more about how you use Cilium at NetBird?

**Comment by joestringer** [comment]
Switched to draft while you address Bill's feedback. Once that's done, please click the "Ready for review" button at the bottom of the PR page.

**Comment by braginini** [comment]
> Thanks for the addition! In the description, can you talk a little bit more about how you use Cilium at NetBird?

This post describes it best :)
https://netbird.io/knowledge-hub/using-xdp-ebpf-to-share-default-dns-port-between-resolvers

**Review by xmulligan — APPROVED** [review]

**Comment by joestringer** [comment]
@ldelossa FYI with the recent improvements to Ariane, we can always run CI and it should skip irrelevant tests automatically. This should help with when to make value judgements on running tests (which looks correct in this instance, but can be more nuanced if the changes involve more files).

**Pull request merged**
