### PR TITLE
test: Wait for DNS entry of kafka and zookeeper service

### PR DESCRIPTION
**Pull request by tgraf**
Related: #4431

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4470)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by manalibhutiyani — APPROVED** [review]
Looks good

**Comment by manalibhutiyani** [comment]
This might will solve the ```Removing server kafka-service:9092 from bootstrap.servers as DNS resolution failed for kafka-service``` issue you pointed out at slack, but the #4431 issue is happening before this ie in WaitforPods and looks more like a Kafka app error, although it could be that kafka is trying to resolve zookeeper service on starting and is unable to resolve it?

**Comment by tgraf** [comment]
Need to use FQDN, will respin

**Comment by tgraf** [comment]
test-m-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
