### PR TITLE
1.0 backports 18-08-28

### PR DESCRIPTION
**Pull request by nebril**
prs included:
 #5300
 #5284
 #5252
 #5250
 #5230
 #5206

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5392)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by jrfastab** [comment]
copy errors? Lets see if we get the same error with another run.
```
14:58:40 [Runtime] time="2018-08-29T21:58:39Z" level=debug msg="running command: sudo cp -r /var/run/cilium /home/vagrant/go/src/github.com/cilium/cilium/test/test_results/RuntimeValidatedConntrackTestConntrack-relatedconfigurationoptionsforendpoints/lib"
14:58:40 [Runtime] time="2018-08-29T21:58:39Z" level=error msg="cannot gather files for cmd 'sudo cp -r /var/run/cilium /home/vagrant/go/src/github.com/cilium/cilium/test/test_results/RuntimeValidatedConntrackTestConntrack-relatedconfigurationoptionsforendpoints/lib': cp: cannot create fifo 
```

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
Error is in GC backport here, 'endpointmanager: Fix conntrack GC' I'll roll a v2.

**Comment by jrfastab** [comment]
(same as before AFAIK I can't push to @nebril pull request) v2 link here, https://github.com/cilium/cilium/pull/5435

**Comment by aanm** [comment]
@jrfastab Can we close this PR in favor of #5435?

**Comment by raybejjani** [comment]
superseded by https://github.com/cilium/cilium/pull/5435

**Pull request closed without merging**
