### PR TITLE
v1.11 backport: Policy deny override redirect

### PR DESCRIPTION
**Pull request by jrajahalme**
* [ ] #26344 (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 26344; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
make add-labels BRANCH=v1.11 ISSUES=26344
```

### CODE REVIEW

**Comment by jibi** [comment]
/test-backport-1.11

**Comment by jibi** [comment]
/test-1.17-4.9

**Comment by jibi** [comment]
/test-1.20-4.9

**Review by nathanjsweet — APPROVED** [review]

**Comment by julianwiedmann** [comment]
/test-1.17-4.9

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/24840, merging

**Pull request merged**
