### PR TITLE
Encryption state remove on node delete and restart

### PR DESCRIPTION
**Pull request by jrfastab**
On node deletion the xfrm state was persisting this series will now remove it. This way we avoid polluting the xfrm state with old entries that are no longer useful. Also we cleanup routes/xfrm state on restart so when we transition from --enable-ipsec to encryption disabled the old state is also removed.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8027)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
rerunning, https://github.com/cilium/cilium/pull/8027

**Comment by jrfastab** [comment]
test-me-please

**Comment by tgraf** [comment]
@jrfastab Can you set the appropriate PR labels so people know when this is good to review?

**Comment by jrfastab** [comment]
Previously failure was due to missing route->table fix, I originally thought it would be OK without the fix but it ended up deleting a route in the default table and failing.

**Review by tgraf — APPROVED** [review]

**Pull request merged**
