### PR TITLE
ginkgo-kubernetes-all.Jenkinsfile: fix misplaced bracket

### PR DESCRIPTION
**Pull request by aanm**
Fixes: dcc4f78376fb ("Test: Fix issues with Ginkgo Kubernetes Job")
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4907)

### CODE REVIEW

**Comment by aanm** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Build failure is legitimate:

```
20:14:47     k8s1-1.11: 	[WARNING FileExisting-crictl]: crictl not found in system path
20:14:47     k8s1-1.11: Suggestion: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
20:14:47     k8s1-1.11: I0719 20:14:45.728864    3518 kernel_validator.go:81] Validating kernel version
20:14:47     k8s1-1.11: I0719 20:14:45.729026    3518 kernel_validator.go:96] Validating kernel config
20:14:47     k8s1-1.11: 	[WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 18.03.0-ce. Max validated version: 17.03
20:14:47     k8s1-1.11: [preflight] Some fatal errors occurred:
20:14:47     k8s1-1.11: 	[ERROR KubeletVersion]: the kubelet version is higher than the control plane version. This is not a supported version skew and may lead to a malfunctional cluster. Kubelet version: "1.11.0-beta.0" Control plane version: "1.10.5"
20:14:47     k8s1-1.11: [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
20:14:47 The SSH command responded with a non-zero exit status. Vagrant
20:14:47 assumes that this means the command failed. The output for this command
20:14:47 should be in the log above. Please read the output to determine what
20:14:47 went wrong.
20:14:47 
```

Link: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/570/

**Review by eloycoto — APPROVED** [review]

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]
Agreed offline to fix the issues with provisioning the environment in a separate PR; the issue this PR purports to fix is indeed fixed by this PR, so let's merge it.

**Pull request merged**
