### PR TITLE
vendor, netlink: fix portid check handling

### PR DESCRIPTION
**Pull request by borkmann**
Pulls in https://github.com/vishvananda/netlink/pull/468 .

Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8616)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by brb — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Hitting #8346

**Comment by borkmann** [comment]
test-me-please

**Pull request merged**
