### PR TITLE
bpf: nodeport: SNAT before adding tunnel info in NAT egress path

### PR DESCRIPTION
**Pull request by julianwiedmann**
When forwarding to a remote backend via tunnel, we currently first add the encap info and only then apply SNAT to the packet. Meaning that the TRACE_TO_OVERLAY in __encap_with_nodeid() doesn't report the final header content.

This is in contrast to the non-tunnel path (where the TRACE_TO_NETWORK in to-netdev will report the post-SNAT header content), and the reply path (where from-overlay raises the TRACE_FROM_OVERLAY long before checking for revSNAT).

So re-order the NAT egress path to first apply SNAT, and then add the encap info afterwards.

For now this just helps to make the TRACE_TO_OVERLAY entry consistent. In the future it's also needed to enable in-XDP encap (as we want to SNAT the inner packet, before adding the encap headers).

### CODE REVIEW

**Comment by julianwiedmann** [comment]
net-next:  `Timed out while waiting for the machine to boot`

**Comment by julianwiedmann** [comment]
/test-1.26-net-next

**Review by dylandreimerink — APPROVED** [review]

**Pull request merged**
