### PR TITLE
v1.10 backports 2022-04-11

### PR DESCRIPTION
**Pull request by jrajahalme**
* #18618 -- pull in the latest changes from github.com/vishvananda/netlink (@aditighag)
 * #19310 -- Test runtime cilium in container (take two) (@jrajahalme)
 * #19358 -- test: Fix whitespace in docker-run-cilium (@jrajahalme)
 * #19360 -- daemon: Restore old CIDR identities (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18618 19310 19358 19360; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.10

**Comment by jrajahalme** [comment]
/test-1.19-5.4

**Comment by jrajahalme** [comment]
/test-1.18-4.9

**Comment by jrajahalme** [comment]
Restarted tests due to VM provisioning fails.

**Comment by jrajahalme** [comment]
Runtime test failing to start Envoy due to #19370 not being merged yet

**Comment by jrajahalme** [comment]
Cherry-picked commits from #19370 here (6 first commits) to be able to run the new test verifying local identity restoration.

**Comment by jrajahalme** [comment]
/test-backport-1.11

**Comment by jrajahalme** [comment]
/test-backport-1.10

**Comment by jrajahalme** [comment]
Format of `cilium bpf ipcache list -o json` is different from master, amended.

**Comment by nbusseneau** [comment]
/ci-gke-1.10

**Comment by nbusseneau** [comment]
/test-1.21-4.9

**Pull request merged**
