### PR TITLE
Remove skip-cnp-status-startup-clean

### LINKED ISSUE #29590: Remove `skip-cnp-status-startup-clean` and CNP status
Follow-ups from https://github.com/cilium/cilium/issues/24503 :
- Remove `skip-cnp-status-startup-clean`: https://github.com/cilium/cilium/blob/2835b063800f7e98696c38e451016e5e9a0ab47b/operator/option/config.go#L72
- Remove CNP Status: https://github.com/cilium/cilium/blob/e6a55a021627d41c0779631e8e01faed4e5f31a3/pkg/k8s/apis/cilium.io/v2/cnp_types.go#L77
- Remove hidden option `legacy-turn-off-k8s-event-handover` https://github.com/cilium/cilium/blob/5ef0f107d64e64a422a65741d804b01cd3995545/pkg/option/config.go#L828

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Remove `skip-cnp-status-startup-clean`

Fixes: #29590

```release-note
Remove `skip-cnp-status-startup-clean`
```

### CODE REVIEW

**Review by derailed — APPROVED** [review]
@chaunceyjiang Thanks for this update!

**Review by christarazi — APPROVED** [review]

**Pull request merged**
