### PR TITLE
V1.0 backport160518

### PR DESCRIPTION
**Pull request by eloycoto**
PR backported: 

https://github.com/cilium/cilium/pull/4116
https://github.com/cilium/cilium/pull/4105
https://github.com/cilium/cilium/pull/4111
https://github.com/cilium/cilium/pull/4113
https://github.com/cilium/cilium/pull/4110 (This one I added the test in a new file rule_validation_test.go that was not backported before.)

Skipped: 
https://github.com/cilium/cilium/pull/4106
https://github.com/cilium/cilium/pull/4107

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by borkmann — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by eloycoto** [comment]
Vagrant download didn't work well.
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3232/execution/node/40/log/

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
Hit test flake https://github.com/cilium/cilium/issues/3297 that was not backported. 

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3246/

**Comment by eloycoto** [comment]
test-me-please

**Pull request merged**
