### PR TITLE
1.2 backports 18 10 04

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:

* #5451
* #5732
* #5752
* #5771 
* #5792 
* #5798
* #5804
*  f9399b9a4f8184c85cb86441a039aa0a707df0ea of #5334
* #5666
* #5777

*Not* backported PRs:

* #5334 - I did not backport this because it had a lot of merge conflicts, and it is a CI-only change. 

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5800)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]
The xds commits LGTM.

**Comment by jrajahalme** [comment]
@ianvernon Could you indicate which commits required significant manual merging so that I could concentrate my review on those?

**Comment by ianvernon** [comment]
@jrajahalme basically every single commit required merge conflict resolution :(

**Comment by ianvernon** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]
looks good to me

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
K8s 1.8 cilium health test failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/982/testReport/junit/k8s-1/8/K8sHealthTest_checks_cilium_health_status_between_nodes/

This failure, while rare, has occurred before (could be a flake in cilium-health). It does warrant triage. Trying again .

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
Added backport for: #5798, #5804,  f9399b9a4f8184c85cb86441a039aa0a707df0ea of #5334

**Comment by raybejjani** [comment]
test-missed-k8s

**Comment by raybejjani** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
Added backports for #5666, #5777

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
K8s tests got stuck:

```
11:25:02 K8sServicesTest Bookinfo Demo 
11:25:02   Tests bookinfo demo
11:25:02   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
11:25:02 STEP: Creating objects in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v1.yaml"
11:25:03 STEP: Creating objects in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v2.yaml"
11:25:16 STEP: Waiting for pods to be ready
11:25:16 STEP: Waiting for services to be ready
11:25:16 STEP: Validating DNS without Policy
11:25:19 STEP: All pods should be able to connect without policy
11:25:19 STEP: Checking that "reviews-v1-1217721402-vsrqw" can connect to "ratings.default.svc.cluster.local:9080/health"
11:25:20 STEP: Checking that "reviews-v1-1217721402-vsrqw" can connect to "ratings.default.svc.cluster.local:9080/ratings/0"
11:25:21 STEP: Checking that "productpage-v1-407527135-ftpk9" can connect to "details.default.svc.cluster.local:9080/health"
11:25:21 STEP: Checking that "productpage-v1-407527135-ftpk9" can connect to "ratings.default.svc.cluster.local:9080/health"
11:25:22 STEP: Checking that "productpage-v1-407527135-ftpk9" can connect to "ratings.default.svc.cluster.local:9080/ratings/0"
11:25:22 STEP: Importing policy
12:38:17 Sending interrupt signal to process
12:38:18 Sending interrupt signal to process
12:38:27 After 10s process did not stop
```

Build link: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7004

No logs due to timeout. Best we can do is try again.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
K8s tests failed for K8s-1.12 because Cilium was not able to get into a ready state:
```
12:06:53   cilium was not able to get into ready state
12:06:53   Expected
12:06:53       <*errors.errorString | 0xc420441430>: {
12:06:53           s: "Timeout reached: timed out waiting for pods with filter -l k8s-app=cilium to be ready",
12:06:53       }
12:06:53   to be nil
```

Build link: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/989/

Investigating.  Not sure what happened - `kubecfg update` appeared to succeed just fine:

```
time="2018-10-05T11:56:42Z" level=debug msg="running command: kubecfg validate /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cilium_ds.jsonnet"
cmd: "kubecfg validate /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cilium_ds.jsonnet" exitCode: 0 stdout:

stderr:
Validating configmaps kube-system.cilium-config
validate object "/v1, Kind=ConfigMap"
Validating secrets kube-system.cilium-etcd-secrets
validate object "/v1, Kind=Secret"
Validating daemonsets kube-system.cilium
validate object "extensions/v1beta1, Kind=DaemonSet"
Validating clusterrolebindings cilium
validate object "rbac.authorization.k8s.io/v1beta1, Kind=ClusterRoleBinding"
Validating clusterroles cilium
validate object "rbac.authorization.k8s.io/v1beta1, Kind=ClusterRole"
Validating serviceaccounts kube-system.cilium
validate object "/v1, Kind=ServiceAccount"

time="2018-10-05T11:56:43Z" level=debug msg="running command: kubecfg update /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cilium_ds.jsonnet"
cmd: "kubecfg update /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cilium_ds.jsonnet" exitCode: 0 stdout:

stderr:
Validating configmaps kube-system.cilium-config
validate object "/v1, Kind=ConfigMap"
Validating secrets kube-system.cilium-etcd-secrets
validate object "/v1, Kind=Secret"
Validating daemonsets kube-system.cilium
validate object "extensions/v1beta1, Kind=DaemonSet"
Validating clusterrolebindings cilium
validate object "rbac.authorization.k8s.io/v1beta1, Kind=ClusterRoleBinding"
Validating clusterroles cilium
validate object "rbac.authorization.k8s.io/v1beta1, Kind=ClusterRole"
Validating serviceaccounts kube-system.cilium
validate object "/v1, Kind=ServiceAccount"
Fetching schemas for 6 resources
Updating clusterroles cilium
Creating non-existent clusterroles cilium
Updating clusterrolebindings cilium
Creating non-existent clusterrolebindings cilium
Updating serviceaccounts kube-system.cilium
Creating non-existent serviceaccounts kube-system.cilium
Updating configmaps kube-system.cilium-config
Creating non-existent configmaps kube-system.cilium-config
Updating secrets kube-system.cilium-etcd-secrets
Creating non-existent secrets kube-system.cilium-etcd-secrets
Updating daemonsets kube-system.cilium
Creating non-existent daemonsets kube-system.cilium
```

But Cilium pods never start!
```
time="2018-10-05T11:56:43Z" level=debug msg="running command: kubectl -n kube-system get pods -l k8s-app=cilium -o json"
cmd: "kubectl -n kube-system get pods -l k8s-app=cilium -o json" exitCode: 0 stdout:
{
    "apiVersion": "v1",
    "items": [],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}
```

Trying again...

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
Dropped backport of #5581

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Kafka tests failed:
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
Failed to produce to empire-hq on topic deathstar-plans
Expected
    <*errors.errorString | 0xc421c34480>: {
        s: "ExecKafkaPodCmd: command 'kubectl exec -n default empire-hq-2917507631-5041l sh -- -c \"echo 'deathstar reactor design v3' | ./kafka-produce.sh --topic deathstar-plans\"' failed '>>' || '[2018-10-05 17:21:16,870] ERROR Error when sending message to topic deathstar-plans with key: null, value: 27 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)\norg.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for deathstar-plans-0: 2310 ms has passed since batch creation plus linger time\n'",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/KafkaPolicies.go:177
```

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7010/

Not really sure how to debug this one.

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
