### PR TITLE
preflight migrate-identity fixes (again)

### LINKED ISSUE #8851: cilium-pre-flight helm chart creates etcd-operator deployment
https://github.com/cilium/cilium/blob/07386353b69eddb6d102fbc738b143c272684624/Documentation/install/upgrade.rst#L796-L805

This should not happen as it will overwrite the etcd-operator the user is running

### PR DESCRIPTION
**Pull request by raybejjani**
This should be safe to merge with only the docs tests. The code changes compiled for me but I'm testing anyway (the command isn't used in testing so it's only a compile check)

There are some small fixes:
- Always use ClusterFirst DNS policy for preflight: This came up because when etcd.managed=true the etc-operator daemonset is also included in the output yaml, but that yaml is expected to only be the preflight daemonset. The risk here is that a etcd-operator was tweaked in some way and running this yaml would overwrite it.
The dependency here was on how DNS lookups worked. The preflight pod is on host networking but it needs to lookup the etcd service. This was enabled by etcd.managed=true. It is now always true.
- Fix deadlock in cilium preflight on etcd timeout: In some cases, when the etcd config wasn't actually correct, we would deadlock on a ListAndWatch call. This function is blocking but I was calling it inline. embarrassing.
- cilium preflight uses cilium RBAC role: https://github.com/cilium/cilium/pull/8848 (merged just this morning!) added a new role for preflight. It is replaced by directly using the cilium role. In my testing this didn't work but aanm helped me figure it out :)

[fixes https://github.com/cilium/cilium/pull/8848]
[fixes 238ae5b]
[fixes 7227d45]

fixes #8851 

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8859)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-docs-please

**Comment by raybejjani** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by raybejjani** [comment]
test-docs-please

**Comment by raybejjani** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
