### PR TITLE
k8s: update k8s libraries to 1.19.3

### PR DESCRIPTION
**Pull request by aanm**
Also update k8s test versions to 1.18.10 and 1.17.13

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by tklauser** [comment]
retest-4.19

**Review by tklauser — APPROVED** [review]

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
K8s all are failing on master, merging this PR https://jenkins.cilium.io/job/cilium-master-K8s-all/

**Pull request merged**
