### PR TITLE
v1.9 backports 2020-10-23

### PR DESCRIPTION
**Pull request by gandro**
* #13683 -- endpoint: Fix goroutine leak when EP is deleted (@christarazi)
 * #13685 -- docs: update NodePort XDP kube-proxy-free GSG for Azure AKS (@tklauser)
 * #13673 -- docs: improve Host Firewall GSG (@qmonnet)
 * #13668 -- docs/gettingstarted: Fix minor issues in Metrics guide (@twpayne)
 * #13675 -- Optimizations for initialization of CRDs (@aanm)
 * #13667 -- endpoint: Avoid benign error messages on restoration (@pchaigno)
 * #13327 -- Adds API for LRP introspection (@Weil0ng)
 * #13698 -- vagrant: Add host name argument in vagrant port command (@sayboras)
 * #13695 -- docs: docker: update some command outputs (@jibi)
 * #13693 -- docker: update Hubble CLI to v0.7.1 (@Rolinh)
 * #13697 -- examples: getting-started: bump Cilium docker image to 1.9 (@jibi)
 * #13703 -- backporting: Update labels by default when submitting backport (@pchaigno)
 * #13699 -- pkg/endpoint: reduce cardinality of prometheus labels (@aanm)
 * #13704 -- docs: Fix shell session highlighting (@joestringer)
 * #13689 -- Refresh upgrade guide for v1.9 (@joestringer)
 * #13691 -- Fix Helm upgrade compatibility (@joestringer)
 * #13543 -- examples/doc Add example LRP yaml files for real-world use cases (@aditighag)
 * #13694 -- test: improve debugging of dns issues, add retries to external conn check (@nebril)
 * #13692 -- docs: Updates kube-proxy-free getting started guide (@pchaigno)
 * #13696 -- pkg/labelsfilter: add more unit test and rewrite docs (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 13683 13685 13673 13668 13675 13667 13327 13698 13695 13693 13697 13703 13699 13704 13689 13691 13543 13694 13692 13696; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Review by tklauser — APPROVED** [review]
👍 for my change

**Review by pchaigno — APPROVED** [review]
My changes look good :+1:

**Comment by gandro** [comment]
test-backport-1.9

**Review by sayboras — APPROVED** [review]
looks good for my one line change :sweat_smile:

**Review by jibi — APPROVED** [review]
:+1: for my changes, thanks!

**Review by qmonnet — APPROVED** [review]
> * #13673 -- docs: improve Host Firewall GSG (@qmonnet)

Looks good, thank you.

**Review by aanm — APPROVED** [review]

**Comment by gandro** [comment]
GKE failed in *Suite-k8s-1.16.K8sIstioTest Istio Bookinfo Demo Tests bookinfo inter-service connectivity*: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/2922/

Seems like the pods did not pull the images in time? Retesting.

**Comment by gandro** [comment]
retest-gke

**Pull request merged**
