### PR TITLE
Fix overall races in the Cilium code base

### PR DESCRIPTION
**Pull request by aanm**
Read per commit

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
retest-net-next

**Comment by aanm** [comment]
retest-net-next

**Comment by aanm** [comment]
retest-net-next

**Comment by aanm** [comment]
retest-net-next

**Comment by aanm** [comment]
retest-net-next

**Comment by aanm** [comment]
retest-net-next

**Comment by nebril** [comment]
test-with-races

**Comment by nebril** [comment]
test-with-races

**Comment by nebril** [comment]
test-with-races

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-with-races

**Review by tklauser — APPROVED** [review]

**Review by christarazi — APPROVED** [review]
Nice!

**Comment by aanm** [comment]
test-with-races

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-with-races

**Comment by aanm** [comment]
runtime hit https://github.com/cilium/cilium/issues/12891

**Comment by aanm** [comment]
1.12 kernel netnext hit https://github.com/cilium/cilium/issues/12596

**Comment by aanm** [comment]
retest-race-upstream-k8s

**Comment by aanm** [comment]
test-race-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/13275

**Pull request merged**
