### PR TITLE
(WIP) envoy update

### PR DESCRIPTION
**Pull request by jrajahalme**
- [ ] Make sure Istio filters build as well.

Update Bazel & Envoy.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6096)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by vadorovsky** [comment]
First thing - my PR in Envoy about visibility of proto libs is rejected. They have a hack for creating publicly visible aliases with `_export` suffix. See their comments: https://github.com/envoyproxy/envoy/pull/4895#pullrequestreview-169537059

That hack is done here:
https://github.com/envoyproxy/envoy/blob/master/api/bazel/api_build_system.bzl#L135

I'm switching to your branch now and I will check whether it's working. I will let you know later.

Second thing - you updated Bazel to 0.18, where `bazel.rc` is deprecated in favor of `.bazelrc`. Details here https://github.com/bazelbuild/bazel/issues/6319

**Review by vadorovsky — CHANGES_REQUESTED** [review]
OK, I can confirm now that they are right and using `_export` suffix is the solution. I closed my Envoy PR.

Build works for me on https://github.com/mrostecki/cilium/tree/envoy-update-mrostecki with this change https://github.com/mrostecki/cilium/commit/8375cb52dd21a91fb9be6a7ad0f4ae07e1637340

And of course I removed this commit https://github.com/cilium/cilium/commit/3fa688e140fdbfc5dea2e5495b7db76ec5a307bc

**Comment by jrajahalme** [comment]
@mrostecki Thanks for the tips, updated this PR accordingly.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Superceded by #6198

**Pull request closed without merging**
