### PR TITLE
Send info to slack on build failure

### PR DESCRIPTION
**Pull request by nebril**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10614)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-focus NightlyEpsMeasurement

**Comment by nebril** [comment]
test-focus K8sDemos

**Comment by nebril** [comment]
test-me-please

**Comment by aanm** [comment]
this PR has been marked as a draft PR since it had a WIP label. Please click in "Ready for review" [below vvv ] once the PR is ready to be reviewed. CI will still run for draft PRs.

**Pull request closed without merging**
