### PR TITLE
Remove beta.kubernetes.io/arch as it's already deprecated

### PR DESCRIPTION
**Pull request by my-git9**
beta.kubernetes.io/arch is already removal

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Review by christarazi — CHANGES_REQUESTED** [review]
Thanks for the PR! There's also more places in the code base that contain label which we should also change. For example, `test/controlplane/node/ciliumnodes/ciliumnodes.go`.

**Comment by my-git9** [comment]
> Thanks for the PR! There's also more places in the code base that contain label which we should also change

Yes, there are many other places that include this tag, but they also include kubernetes.io/arch , I'm not sure if I need to remove beta.kubernetes.io/arch, like:
```
	{
		"state4.yaml",
		map[string]string{
			"beta.kubernetes.io/arch": "amd64",
			"beta.kubernetes.io/os":   "linux",
			"cilium.io/ci-node":       "k8s1",
			"kubernetes.io/arch":      "amd64",
			"kubernetes.io/hostname":  "cilium-nodes-worker",
			"kubernetes.io/os":        "linux",

			"another-test-label": "changed-test-value",
		},
	},
```

**Comment by christarazi** [comment]
Yes, please do update the remaining references.

**Review by christarazi — APPROVED** [review]

**Pull request merged**
