### PR TITLE
Fix MTU connectivity issue with external services

### PR DESCRIPTION
**Pull request by joestringer**
We observed an issue where requests to external services would often
stall or fail from pods inside a minikube 0.24/0.25 environment (Linux
4.9.x). As soon as an outgoing request attempted to fetch data beyond
the MTU of the endpoint veth device MTU, the command would stall. This
was tested by running a curl to external service such as google. Running
`cilium monitor` showed large responses being redirected into the veth
device, however the packets were not observed on the device within the
pod making the request (observing via tcpdump). Upon closer inspection,
the container device MTU was being set to 1450 however the devices on
the cilium node used for connectivity to the outside world had MTU 1500.
Lowering the cilium_host device MTU fixed the issue.

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
