### PR TITLE
 v1.12 Backports 2023-09-08

### PR DESCRIPTION
**Pull request by margamanterola**
* [ ] #28012 (@jrfastab)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 28012; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=28012
```

### CODE REVIEW

**Comment by margamanterola** [comment]
/test-backport-1.12

**Comment by margamanterola** [comment]
/test-backport-1.12

**Review by jrfastab — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Comment by michi-covalent** [comment]
[`k8s-1.19-kernel-4.9 (test-1.19-4.9)`](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.9/180/): hit https://github.com/cilium/cilium/issues/24840

**Comment by michi-covalent** [comment]
/test-1.19-4.9

**Comment by michi-covalent** [comment]
[`k8s-1.19-kernel-4.9 (test-1.19-4.9)`](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.9/182/): hit https://github.com/cilium/cilium/issues/24840 and https://github.com/cilium/cilium/issues/25721

**Comment by michi-covalent** [comment]
/test-1.19-4.9

**Pull request merged**
