### PR TITLE
policy: Allow TLS termination and origination without L7 rules

### PR DESCRIPTION
**Pull request by jrajahalme**
Add new L7ParserType "tls" to be used when TLS termination and/or
origination is needed, and when no L7 policy is to be used.

This relaxes the requirement to have L7 rules in a Cilium Network Policy
in order to use TLS termination or origination.

Use Envoy TCP proxy for TLS termination and/or origination in this case.

First four commits are smaller refactors preparing for the feature change.

This PR is a dependency for multiple additional feature work branches.
    
Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>

```release-note
Cilium Network Policy can now have TLS termination and/or origination without L7 rules.
```

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by jrajahalme** [comment]
Rebased.

**Comment by jrajahalme** [comment]
Rebased.

**Comment by jrajahalme** [comment]
Looks like setup failed on test-1.25-net-next, nothing succeeded. Trying again

**Comment by jrajahalme** [comment]
/test-1.25-net-next

**Comment by jrajahalme** [comment]
Rebased, unquarantined test in a new commit.

**Comment by jrajahalme** [comment]
smoke-test fails connections to https://1.1.1.1 from a pod that has no policy. Bpf policy map shows egress traffic, so this looks like the failure happens outside of the cilium node, as there is no ingress traffic for that pod:
```
/sys/fs/bpf/tc/globals/cilium_policy_03337:

POLICY   DIRECTION   IDENTITY   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
Allow    Ingress     0          ANY          NONE         0       0         
Allow    Ingress     1          ANY          NONE         0       0         
Allow    Egress      0          ANY          NONE         5624    76        
```
Traffic to google.com from the same node succeeds.

Flow logs only show the outgoing SYN:
```
{"flow":{"time":"2022-11-18T20:59:56.297024240Z","verdict":"FORWARDED","ethernet":{"source":"2a:7a:62:19:26:7c","destination":"c6:9d:96:0f:fc:77"},"IP":{"source":"10.244.1.194","destination":"1.1.1.1","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":49620,"destination_port":443,"flags":{"SYN":true}}},"source":{"ID":3337,"identity":32209,"namespace":"default","labels":["k8s:io.cilium.k8s.policy.cluster=default","k8s:io.cilium.k8s.policy.serviceaccount=default","k8s:io.kubernetes.pod.namespace=default","k8s:name=pod-to-external-1111"],"pod_name":"pod-to-external-1111-6d75cc476d-tjdcd","workloads":[{"name":"pod-to-external-1111","kind":"Deployment"}]},"destination":{"identity":2,"labels":["reserved:world"]},"Type":"L3_L4","node_name":"chart-testing-worker","event_type":{"type":4,"sub_type":3},"traffic_direction":"EGRESS","trace_observation_point":"TO_STACK","is_reply":false,"Summary":"TCP Flags: SYN"},"node_name":"chart-testing-worker","time":"2022-11-18T20:59:56.297024240Z"}
```

As this failing traffic is not redirected to Envoy, this failure is unlikely to be due to this PR.

**Comment by jrajahalme** [comment]
Fixed the new test.

**Comment by jrajahalme** [comment]
Fixed the updated policy yaml, rebased.

**Comment by jrajahalme** [comment]
Another fix for the new test...

**Comment by jrajahalme** [comment]
runtime test failed due to known flake (or breakage on master): #22373

**Comment by jrajahalme** [comment]
Rebased.

**Pull request merged**
