### PR TITLE
[v1.13] Author backport of "Address ipcache startup perfomance regression"

### PR DESCRIPTION
**Pull request by bimmlerd**
* [ ] #25007 (@bimmlerd)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 25007; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=25007
```

### CODE REVIEW

**Comment by bimmlerd** [comment]
/test-backport-1.13

**Comment by bimmlerd** [comment]
/test-1.16-4.19

**Comment by bimmlerd** [comment]
/test-1.17-4.19

**Comment by bimmlerd** [comment]
/test-1.19-4.19

**Comment by bimmlerd** [comment]
/test-1.20-4.19

**Comment by bimmlerd** [comment]
/test-1.22-4.19

**Review by joestringer — APPROVED** [review]

**Pull request merged**
