### PR TITLE
v1.11 backports 2022-02-22

### PR DESCRIPTION
**Pull request by jrajahalme**
* #18748 -- envoy: Update to release 1.21.0 (@jrajahalme)
 * #18899 -- envoy: Update to 1.21.1 (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18748 18899; do contrib/backporting/set-labels.py $pr done 1.11; done

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.11

**Comment by jrajahalme** [comment]
runtime provision fail, retesting

**Comment by joestringer** [comment]
There's a known issue with runtime provisioning at the moment, which we hope to resolve in https://github.com/cilium/cilium/pull/18886 . If that's the only problem we have with runtime then I'll be inclined to ignore it to :ship: .

**Comment by jrajahalme** [comment]
/test-backport-1.11

**Comment by joestringer** [comment]
Two failures:

* k8s-1.16-kernel-netnext (test-1.16-netnext) — Build finished.
Required
[Details](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/2244/)[](https://github.com/ciliumbot)
  * Timed out with issues like the ones highlighted in https://github.com/cilium/cilium/issues/18913 .
  * Also found weird individual issues like #18917 where running a command that we expect to terminate quickly, instead takes 4 minutes and fails/times out.
* runtime (test-runtime) — Build finished.
Required
[Details](https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1380/)
  * Looks like it failed out at 30 minutes due to a timeout. Known issue that is awaiting backports to address.

**Pull request merged**
