### PR TITLE
v1.8 backports 2021-05-21

### PR DESCRIPTION
**Pull request by nbusseneau**
* #16072 -- node-neigh: Fix unit test flake (@brb)
 * #16123 -- docs: add ids to the list of special identities (@bmcustodio)
 * #16160 -- contrib: Make upstream commit check more generic (@joestringer)
 * #15899 -- Improve author attribution scripts (@joestringer)
 * #15872 -- Improve ipsec compile-time testing in CI (@joestringer)
 * #16214 -- Specify scrape interval for Hubble metrics (@christian-2)
 * #15989 -- docs: Clarify coordination for backporting process (@christarazi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16072 16123 16160 15899 15872 16214 15989; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
Sorry, I made a mistake with my fork and accidentally closed all my PRs. Reopening.

**Review by christarazi — APPROVED** [review]
:+1: for my commits

**Review by brb — APPROVED** [review]

**Review by bmcustodio — CHANGES_REQUESTED** [review]
> #16123 -- docs: add ids to the list of special identities (@bmcustodio)

Hmmm I don't actually see my commit 🤔

**Comment by nbusseneau** [comment]
@bmcustodio PTAL, I added back two missing PRs that were improperly cherry-picked and left in a dangling state (my bad).

**Comment by nbusseneau** [comment]
test-backport-1.8

**Review by bmcustodio — APPROVED** [review]
> #16123 -- docs: add ids to the list of special identities (@bmcustodio)

LGTM :+1:

**Comment by nbusseneau** [comment]
test-upstream-k8s

**Comment by nbusseneau** [comment]
There's an issue with the upstream job while tagging `cilium/cilium` (?), happened twice in a row:
```
21:40:11      k8s1-1.18: Successfully tagged cilium/cilium:latest
21:40:11      k8s1-1.18: docker tag cilium/cilium:"latest" cilium/cilium:"latest"-amd64
21:40:11      k8s1-1.18: docker tag cilium/cilium:"latest" quay.io/cilium/cilium:"latest"
21:40:11      k8s1-1.18: Push like this when ready:
21:40:11      k8s1-1.18: docker push cilium/cilium:latest-amd64
21:40:11      k8s1-1.18: tagging cilium image...
21:40:11      k8s1-1.18: pushing cilium image to k8s1:5000/cilium/cilium-dev...
21:40:11      k8s1-1.18: The push refers to repository [k8s1:5000/cilium/cilium-dev]
21:40:11      k8s1-1.18: Get https://k8s1:5000/v2/: x509: certificate has expired or is not yet valid
21:40:11  The SSH command responded with a non-zero exit status. Vagrant
21:40:11  assumes that this means the command failed. The output for this command
21:40:11  should be in the log above. Please read the output to determine what
21:40:11  went wrong.
```

**Comment by nbusseneau** [comment]
test-upstream-k8s

**Comment by nbusseneau** [comment]
test-upstream-k8s

**Comment by nbusseneau** [comment]
#16379 should fix the upstream boxes. What's the process? Are backport PRs "rebasable"?

**Comment by nbusseneau** [comment]
Rebased on latest `v1.8` at a0b53e25987af7899288d8c27635b4668b1cf1ed. Retriggering tests.

**Comment by nbusseneau** [comment]
test-backport-1.8

**Comment by nbusseneau** [comment]
All Jenkins tests successful following fixes.

**Review by joestringer — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Pull request merged**
