### PR TITLE
vendor: Update k8s dependencies and tests to 1.21.3

### PR DESCRIPTION
**Pull request by christarazi**
Also updates the k8s version for other branches to 1.18.20, 1.19.13, and
1.20.9.

Signed-off-by: Chris Tarazi <chris@isovalent.com>

### CODE REVIEW

**Comment by christarazi** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by christarazi** [comment]
test-me-please

**Review by rolinh — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

**Comment by aanm** [comment]
@christarazi a new k8s version has been released so it might make sense to upgrade to that one and rebase the PR against master.

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
Smoke Test with IPv6 / conformance-test-ipv6 failed by timing out on connectivty check pods timing out: https://github.com/cilium/cilium/pull/16608/checks?check_run_id=3108750036

It's difficult to tell why. I opened https://github.com/cilium/cilium/pull/16968 in order to get insights (hubble flows) as to why those pods' connectivity were broken.

Otherwise this is ready to merge.

**Pull request merged**
