### PR TITLE
refactor trafficdirection into its own package

### PR DESCRIPTION
**Pull request by ianvernon**
This removes the dependency of pkg/policy on any BPF-related code.

Signed-off by: Ian Vernon <ian@cilium.io>

Related-to: #6101

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6097)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]

**Review by aanm — COMMENTED** [review]
@tgraf shouldn't this be moved to the api pkg instead?

**Comment by tgraf** [comment]
@aanm I think this is fine. It's not exposed to the user as input, and the output is not machine-readable yet.

**Review by tgraf — APPROVED** [review]

**Pull request merged**
