### PR TITLE
k8s: Remove unused AnnotatePod

### PR DESCRIPTION
**Pull request by tgraf**
The code is unused and can be removed

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7276)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
`runtime.RuntimeFQDNPolicies CNAME follow`

**Comment by tgraf** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by tgraf** [comment]
`runtime.RuntimeFQDNPolicies Implements matchPattern: "*"`

**Pull request merged**
