### PR TITLE
[v1.9] vagrant: Bump runtime box image

### PR DESCRIPTION
**Pull request by joestringer**
Related: https://github.com/cilium/cilium/issues/18919
Related: #17190

Backports:
- https://github.com/cilium/cilium/pull/14272
- #17761

Supersedes: #19047

```upstream-prs
  $ for pr in 14272 17761; do contrib/backporting/set-labels.py $pr done v1.9; done
```

### CODE REVIEW

**Comment by joestringer** [comment]
/test-runtime-4.9

**Review by pchaigno — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Comment by pchaigno** [comment]
> Runtime failed with `22:51:52 runtime: Failed to disable unit: Unit file unattended-upgrades.service does not exist.` - seems like this was removed in commit [e59a713](https://github.com/cilium/cilium/commit/e59a713aabfca5d4ea9be02e47ebfdb287ec8b8d) which is not present on v1.9

We've removed that service in the VM images, so we'd need to backport that commit or at least remove those commands in the v1.9 provisioning.

**Comment by joestringer** [comment]
Thanks for the pointers, I cherry-picked  e59a713.

**Comment by joestringer** [comment]
/test-runtime-4.9

**Comment by pchaigno** [comment]
We'll need to run all the tests that rely on the 4.9 VM before merging. I think the easiest way to do that is still to run everything with `/test-backport-1.9`.

**Comment by joestringer** [comment]
/test-backport-1.9

**Comment by joestringer** [comment]
Latest failure:
```
10:49:00      k8s1-1.13: Failed to restart sys-fs-bpf.mount: Unit sys-fs-bpf.mount has a bad unit file setting.
```

**Comment by joestringer** [comment]
Looking at the previous failure, it also wasn't just a plain provisioning error, actually it's a problem where the go version has been bumped in the VMs and so now the default linting targets fail due to upstream go changes to the formatting.

**Comment by joestringer** [comment]
/test-backport-1.9

**Comment by joestringer** [comment]
```
12:25:04      k8s1-1.14: [init] Using Kubernetes version: v1.14.10
12:25:04      k8s1-1.14: [preflight] Running pre-flight checks
12:25:05      k8s1-1.14: 	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
12:25:05      k8s1-1.14: 	[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 20.10.12. Latest validated version: 18.09
12:25:05      k8s1-1.14: error execution phase preflight: [preflight] Some fatal errors occurred:
12:25:05      k8s1-1.14: 	[ERROR Swap]: running with swap on is not supported. Please disable swap
12:25:05      k8s1-1.14: [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

**Comment by qmonnet** [comment]
@joestringer Did these backports become unnecessary? Can you please adjust the `backport-pending/1.9` label on the original PRs to reflect the current situation?

**Comment by joestringer** [comment]
@qmonnet thanks for the ping, I lost track of these. I dropped the backport labels. I'm not sure we solved the underlying problem yet, but I was hitting enough hurdles here that it wasn't clear to me that this is the correct solution.

**Pull request closed without merging**
