### PR TITLE
v1.12 backports 2022-07-14

### PR DESCRIPTION
**Pull request by ldelossa**
* #20438 -- Update gops to v0.3.25 (@tklauser)
 * #20460 -- docs: fix a Links documentation style guide error (@Kikiodazie)
 * #20369 -- daemon: Rename host-reachable services to socket LB (@brb)
     * @brb - lots of complexity test merge conflicts, may want to double check all the 
             flags look good.
 * #20499 -- test: Do not start cilium monitor in K8sServicesTest (@brb)
 * #20491 -- Add metric on number of requests rejected by DNS Proxy semaphore (@rahulkjoshi)
 * #19434 -- vtep: VTEP integration pod src identity set to WORLD_ID (@vincentmli)
 * #20501 -- Update Go to 1.18.4 (@tklauser)
   * @tklauser - this cherry pick made a conflict with #20438 , this is later commit
        so I let this one win. LMK if that's correct.
 * #20249 -- docs(bpf): fix minor grammar errors in struct padding section (@maxbrunet)
 * #20415 -- Documentation: Improve cilium-cli and hubble cli installation instructions (@chancez)
 * #20439 -- docs: Add cluster install/prep guide for AKS-to-AKS clustermesh (@dylandreimerink)
 * #20447 -- docs: Improve kubeproxy replacement and OKD GSG guide. (@tommyp1ckles)
 * #20458 -- envoy: Support ca.crt Secrets (@jrajahalme)
 * #20500 -- test: Remove sockops test cases (@brb)
 * #20512 -- cilium/cmd, test/runtime: convert test loading invalid policy JSON to unit test (@tklauser)
 * #20526 -- test: remove nightly test leftovers (@tklauser)
 * #20383 -- pkg/k8s/version: Also set EndpointSlice when forcing version (@joamaki)
 * #20537 -- fqdn/dnsproxy: fix test build (@tklauser)
 * #20549 -- Update cilium-iproute2 (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20438 20460 20369 20499 20491 19434 20501 20249 20415 20439 20447 20458 20500 20512 20526 20383 20537 20549; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Comment by ldelossa** [comment]
/test-backport-1.12

**Comment by ldelossa** [comment]
/test-backport-1.12

**Comment by ldelossa** [comment]
ConformanceAKS (ci-aks-1.12) 
ConformanceGKE (ci-gke-1.12)

Currently known flakes - disregarding for merge criteria.

**Comment by aanm** [comment]
/test-backport-1.12

**Comment by aanm** [comment]
/test-backport-1.12

**Review by aanm — APPROVED** [review]
I believe it's safe to merge this PR once the tests have passed since the v1.12 branch is not that different from the master branch.

**Comment by aanm** [comment]
/ci-aks-1.12

**Comment by aanm** [comment]
/test-1.22-5.4

**Comment by aanm** [comment]
All failures looked like a regression. I bisect the commits from this PR [here](https://github.com/cilium/cilium/pull/20551) but the PR didn't fail with the same failures. We can safely merge this one.

**Review by brb — APPROVED** [review]
My changes LGTM, thanks.

**Review by nbusseneau — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Pull request merged**
