### PR TITLE
envoy: Do not use deprecated fields

### LINKED ISSUE #14919: Cilium latest Envoy warnings
Recent builds on latest Cilium (v1.10 dev cycle) have been triggering the following warnings from Envoy:

* `[Unable to use runtime singleton for feature envoy.http.headermap.lazy_map_min_size`
* `[Deprecated field: type envoy.config.route.v3.RouteAction Using deprecated option 'envoy.config.route.v3.RouteAction.max_grpc_timeout' from file route_components.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.`
* `[there is no configured limit to the number of allowed active connections. Set a limit via the runtime key overload.global_downstream_max_connections`

Example tests:
`K8sConformance Portmap Chaining Check connectivity-check compliance with portmap chaining`
`K8sPolicyTest Multi-node policy test with L7 policy using connectivity-check to check datapath`
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/6537/execution/node/191/log/?consoleFull

We should investigate these warnings and address the underlying issue or change them to informational logs if they have no real user impact.

### PR DESCRIPTION
**Pull request by jrajahalme**
Use new options instead of these deprecated fields to avoid deprecation warnings:

- RouteAction.max_grpc_timeout
- Cluster.protocol_selection
- Cluster.http2_protocol_options

Define runtime option "overload.global_downstream_max_connections" to avoid a warning like:

       "there is no configured limit to the number of allowed active connections.
       Set a limit via the runtime key overload.global_downstream_max_connections"

Fixes: #14919
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by tklauser** [comment]
test-runtime

**Review by tklauser — APPROVED** [review]

**Comment by jrajahalme** [comment]
retest-1.13-netnext

**Comment by jrajahalme** [comment]
test-1.20-4.9 hit by #15141

**Comment by jrajahalme** [comment]
retest-1.20-4.9

**Comment by joestringer** [comment]
Only failure is known issue #15246 . @jrajahalme do you want another set of eyes on the changes before we merge?

**Pull request merged**
