### PR TITLE
[v1.13 backport] test: Switch target FQDN

### PR DESCRIPTION
**Pull request by nbusseneau**
Manual backport of #25571 to v1.13.

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.13

**Comment by nbusseneau** [comment]
/test-1.21-4.19

**Comment by nbusseneau** [comment]
/test-1.22-4.19

**Comment by nbusseneau** [comment]
/test-1.23-4.19

**Review by pchaigno — APPROVED** [review]

**Comment by nbusseneau** [comment]
All CI passed, marking ready to merge.

**Pull request merged**
