### PR TITLE
revert recent Istio changes to unblock CI failures

### PR DESCRIPTION
**Pull request by ianvernon**
Revert commits from #4415, as master became broken after it was merged.

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4423)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by rlenglet** [comment]
Master has been green today. What does a single green build of this revert prove?

**Review by rlenglet — CHANGES_REQUESTED** [review]
Master has been green today. What does a single green build of this revert prove?

**Comment by rlenglet** [comment]
test-me-please

**Comment by tgraf** [comment]
Let's revert the vm change only and keep the docs changes. The images are already built.

**Comment by tgraf** [comment]
Revert  is happening in #4428

**Pull request closed without merging**
