### PR TITLE
envoy: Sync supported resources in CiliumEnvoyConfig

### PR DESCRIPTION
**Pull request by sayboras**
These resources are enabled in cilum-proxy build, and can be used in CiliumEnvoyConfig directly, however, without related imported statements, Cilium agent will fail to marshal/unmarshal objects.

Sample error

```
level=warning msg="Ignoring invalid CiliumEnvoyConfig JSON (proto:\u00a0(line 1:405): unable to resolve \"type.googleapis.com/envoy.extensions.filters.http.router.v3.Router\": \"not found\")
```

```release-note
envoy: Sync supported resources to fix not found issue
```

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]
LGTM

**Review by pippolo84 — APPROVED** [review]
Thanks! :rocket:

**Review by rolinh — APPROVED** [review]
Vendor changes lgtm.

**Pull request merged**
