### PR TITLE
Test tls flake

### PR DESCRIPTION
**Pull request by jrajahalme**
Reintroduce TLS test without HTTP rules that was recently reverted. It looks like this test failed due to DNS proxy not waiting for the policy to be plumbed to the datapath and/or Envoy. This has recently been fixed on master, so this test should now pass.

Added a few commands to bugtool that generally help triaging policy issues, and updated the ginkgo install line in docs.

### CODE REVIEW

**Comment by jrajahalme** [comment]
Master fixed, testing again.

**Comment by jrajahalme** [comment]
Focused test run passed, rebasing and marking as ready for review.

**Review by nebril — APPROVED** [review]

**Comment by joestringer** [comment]
just a heads up re: `bugtool: Add 'cilium policy get' and 'cilium endpoint list'`, this info is included in the `cilium-debuginfo-20220803-163142.74+0000-UTC.md` file in 1.12 or older releases. That said this has confused enough people over the years that it makes sense to pull it out into its own file.

**Pull request merged**
