### PR TITLE
v1.12: vendor: update logrus v1.9.0 => v1.9.3

### PR DESCRIPTION
**Pull request by rolinh**
Release v1.9.3 address a potential DoS vulnerability.

```release-note
Update the logrus dependency to address a security issue.
```

### CODE REVIEW

**Comment by rolinh** [comment]
/test-backport-1.12

**Review by ti-mo — APPROVED** [review]

**Comment by rolinh** [comment]
Looks like a flake, I'll re-trigger the test
```
	 Error: INSTALLATION FAILED: cannot re-use a name that is still in use
```

**Comment by rolinh** [comment]
/test-1.22-4.9

**Comment by rolinh** [comment]
/test-backport-1.12

**Comment by aanm** [comment]
/test-1.24-net-next

**Pull request merged**
