### PR TITLE
fix broken link on readme

### LINKED ISSUE #13879: The README file in this repo has some bad links - [404:NotFound]
The README file in this repo has some bad links - [404:NotFound]

Status code [404:NotFound] - Link: https://docs.cilium.io/en/stable/install/upgrade/
Status code [404:NotFound] - Link: http://docs.cilium.io/en/doc-1.0/install/system_requirements

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

### PR DESCRIPTION
**Pull request by kaitoii11**
Fixes: #13879 

Fix broken links on README.rst

Signed-off-by: Kaito Ii kaitoii1111@gmail.com

### CODE REVIEW

**Review by aanm — APPROVED** [review]
Thanks!

**Review by tklauser — APPROVED** [review]
Thanks

**Comment by tklauser** [comment]
@kaitoii11 please also add the `Signed-off-by-line` to the commit message (you can e.g. use `git commit --amend -s` on the existing commit)

**Comment by tklauser** [comment]
@kaitoii11 it seems like there is now a merge commit in the PR, please drop that one and just push the commit with the actual fix including the `Signed-off-by` line in the commit message. You may use `git push --force` if need be.

**Comment by kaitoii11** [comment]
@tklauser  Thank you! I think I've got it fixed. Sorry for the trouble.

**Comment by tklauser** [comment]
@kaitoii11 no worries. It looks fine now, thanks!

Marking the PR as ready to merge, no need to run Jenkins CI as it only affects the README.

**Review by fristonio — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
