### PR TITLE
Update Go to 1.14.2

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
Build of the cilium-runtime image is currently blocked by the Go 1.14.2 image not being published yet due to docker-library/golang#322

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
This PR conflicts with open PR #10819 in case one is merged the other needs to be rebased

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
restart-ginkgo

**Comment by tklauser** [comment]
restart-ginkgo

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
restart-ginkgo

**Comment by aanm** [comment]
restart-ginkgo

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-gke

**Pull request merged**
