### PR TITLE
vtep: Add vtep map cilium bpf command

### PR DESCRIPTION
**Pull request by vincentmli**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
Add vtep map cilium bpf command
```

### CODE REVIEW

**Comment by vincentmli** [comment]
`make -C Documentation update-cmdref` generating following error

make[2]: Entering directory '/home/go/src/github.com/f5devcentral/cilium/cilium'
CGO_ENABLED=0 go build  -mod=vendor -ldflags ' -X "github.com/cilium/cilium/pkg/version.ciliumVersion=1.11.90 2071f7cbb6 2022-04-28T01:40:02+00:00" -s -w -X "github.com/cilium/cilium/pkg/envoy.RequiredEnvoyVersionSHA=12e3081cc292764b1308668cab1e7e523429bedc" -X "github.com/cilium/cilium/pkg/datapath/loader.DatapathSHA256=42e24917a7ffc18e9de74b8e15b1a0147f6039a2aab4cebba5f47b325c2b2434" ' -tags=osusergo  -o cilium
package github.com/cilium/cilium/cilium: build constraints exclude all Go files in /home/go/src/github.com/f5devcentral/cilium/cilium
make[2]: *** [Makefile:14: cilium] Error 1
make[2]: Leaving directory '/home/go/src/github.com/f5devcentral/cilium/cilium'
make[1]: *** [Makefile:132: cilium] Error 2
make[1]: Leaving directory '/home/go/src/github.com/f5devcentral/cilium'
make: *** [Makefile:25: cilium-build] Error 2
make: Leaving directory '/home/go/src/github.com/f5devcentral/cilium/Documentation'

**Comment by vincentmli** [comment]
keep it alive :)

**Comment by vincentmli** [comment]
Hi @ldelossa, gently ping, this PR is getting stale :)

**Review by ldelossa — APPROVED** [review]
LGTM

**Pull request merged**
