### PR TITLE
Bugtool: add taskset 

### LINKED ISSUE #14566: Add taskset to bugtool
To assist with additional debugging around processor affinity, it would be useful to add this command to the bugtool:

```
$ taskset -p 1
pid 1's current affinity mask: f
```

There's a list of `defaultCommands` in `bugtool/cmd/configuration.go` which could be extended with this tool. The binary should already be present in the Cilium container.

### PR DESCRIPTION
**Pull request by youssefazrak**
To assist with additional debugging around processor affinity, we are
adding the Taskset command to the bugtool.

Fixes: #14566

Signed-off-by: Youssef Azrak <yazrak.tech@gmail.com>

### CODE REVIEW

**Comment by youssefazrak** [comment]
@joestringer 
I added the `-pc` flag instead of the simple `-pc` as this gives back a more "user-friendly" result for the cpu affinity instead of the hexadecimal value.

Btw, `numactl -H` seems to give some useful information at a higher-level as it is aware of the processor topology and how the CPU cores map to CPU sockets.

**Review by twpayne — APPROVED** [review]
LGTM, thanks!

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
`numactl -H` looks kinda interesting, if we were to add it we'd have to also extend the container image to include the tool. 

Though that said I'm not sure it necessarily matters so much for general debugging. The reason I proposed `taskset` is because it observes state that Go uses to detect the number of CPUs and therefore could impact BPF map initialization and so on. Not sure whether the NUMA layout is likely to impact those kinds of things in such a way that it's important to retrospectively analyse rather than an active investigation into e.g. performance, queue configuration, etc.?

**Comment by joestringer** [comment]
PR LGTM, doesn't impact CI so merging.

**Comment by twpayne** [comment]
Marking this PR for backport, as it's another useful addition.

**Pull request merged**
