### PR TITLE
Istio: Update to release 1.5.2

### PR DESCRIPTION
**Pull request by jrajahalme**
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

```release-note
Istio integration has been updated to release 1.5.2
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-missed-k8s

**Review by qmonnet — APPROVED** [review]

**Comment by jrajahalme** [comment]
Issued #11286 for the GKE CI fail, retesting.

**Comment by jrajahalme** [comment]
test-gke

**Review by aanm — APPROVED** [review]

**Pull request merged**
