### PR TITLE
docs: link to ariane-config.yaml for available triggers.

### PR DESCRIPTION
**Pull request by sypakine**
docs: link to ariane-config.yaml for available triggers.

This change surfaces additional triggers to the
reader via the ariane-config file. These triggers are
helpful when seeking which specific workflows to initiate.

```release-note
Link ariane triggers in testing/CI documentation.
```

### CODE REVIEW

**Comment by sypakine** [comment]
See discussion: https://cilium.slack.com/archives/C2B917YHE/p1726064117715459?thread_ts=1725994779.135989&cid=C2B917YHE

/cc @aanm

**Review by bimmlerd — APPROVED** [review]
LGTM, cheers. Ideally I think `/test` would be smart enough that we don't have to expose these details to contributors, but until that's the case I'm all for it.

**Comment by sypakine** [comment]
Is there an e2e override for docs changes or do we still run /test?

**Review by ghost — APPROVED** [review]
lgtm

**Comment by lambdanis** [comment]
> Is there an e2e override for docs changes or do we still run /test?

Still run `/test` - it should recognize docs-only changes and run only relevant jobs.

**Pull request merged**
