### PR TITLE
cilium: Support user-specified monitor socket

### PR DESCRIPTION
**Pull request by jrajahalme**
* CLI: Support user-specified monitor socket #8943

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8958)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by brb** [comment]
CI failed:

```
[2019-08-19T22:38:29.398Z] [0mRuntimeCassandra[0m 
[2019-08-19T22:38:29.398Z]   [1mTests policy allowing all actions[0m
[2019-08-19T22:38:29.398Z]   [37m/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:420[0m
[2019-08-19T22:38:34.417Z] ===================== TEST FAILED =====================
[2019-08-19T22:38:34.417Z] cmd: kubectl get pods -o wide --all-namespaces
[2019-08-19T22:38:34.417Z] Exitcode: 0 
[2019-08-19T22:38:34.417Z] Stdout:
[2019-08-19T22:38:34.417Z]  	 NAMESPACE     NAME                               READY     STATUS                  RESTARTS   AGE       IP              NODE
[2019-08-19T22:38:34.417Z] 	 kube-system   cilium-operator-677d7d5d44-b9tvr   0/1       Pending                 0          20m       <none>          <none>
[2019-08-19T22:38:34.417Z] 	 kube-system   cilium-rstjb                       0/1       Init:ImagePullBackOff   0          20m       192.168.36.11   k8s1
[2019-08-19T22:38:34.417Z] 	 kube-system   cilium-t6qmz                       0/1       Init:ImagePullBackOff   0          20m       192.168.36.12   k8s2
```

**Comment by brb** [comment]
never-tell-me-the-odds

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-missed-k8s

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-missed-k8s

**Pull request merged**
