### PR TITLE
ci: update cilium-cli to v0.10.0

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
ci-awscni

**Comment by tklauser** [comment]
All CI 3.0 tests passed: https://github.com/cilium/cilium/actions?query=branch%3Apr%2Ftklauser%2Fcilium-cli-v0.10.0++

Dropping test commit and marking as ready to review.

**Review by nbusseneau — APPROVED** [review]
:shipit:

**Pull request merged**
