### PR TITLE
docs: update kubeproxy-free docs with info about EKS

### LINKED ISSUE #22039: Cilium kube-proxy replacement breaks on EKS due to dynamic k8sServiceHost endpoint IP
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium would work on newly added nodes (by cluster auto-scaler) just as its working on the nodes it was originally installed on.

### Cilium Version

```
cilium-cli: v0.12.6 compiled with go1.19.1 on darwin/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.3
cilium image (running): v1.12.3
```

### Kernel Version

```
Linux ip-10-0-76-118.us-west-2.compute.internal 5.10.135 #1 SMP Tue Oct 18 01:58:53 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

[cilium-sysdump-20221107-153111.zip](https://github.com/cilium/cilium/files/9956327/cilium-sysdump-20221107-153111.zip)

### Relevant log output

```shell
level=info msg="Using autogenerated IPv4 allocation range" subsys=node v4Prefix=10.47.0.0/16
level=info msg="Initializing daemon" subsys=daemon
level=info msg="Establishing connection to apiserver" host="https://10.1.0.1:443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://10.1.0.1:443" subsys=k8s
level=error msg="Unable to contact k8s api-server" error="Get \"https://10.1.0.1:443/api/v1/namespaces/kube-system\": dial tcp 10.1.0.1:443: i/o timeout" ipAddr="https://10.1.0.1:443" subsys=k8s
level=fatal msg="Unable to initialize Kubernetes subsystem" error="unable to create k8s client: unable to create k8s client: Get \"https://10.1.0.1:443/api/v1/namespaces/kube-system\": dial tcp 10.1.0.1:443: i/o timeout" subsys=daemon
```

**Logs from existing node where Cilium is working fine**
```shell
level=info msg="Using autogenerated IPv4 allocation range" subsys=node v4Prefix=10.118.0.0/16
level=info msg="Initializing daemon" subsys=daemon
level=info msg="Establishing connection to apiserver" host="https://10.1.0.1:443" subsys=k8s
level=info msg="Connected to apiserver" subsys=k8s
level=info msg="Trying to auto-enable \"enable-node-port\", \"enable-external-ips\", \"bpf-lb-sock\", \"enable-host-port\", \"enable-session-affinity\" features" subsys=daemon
level=info msg="Inheriting MTU from external network interface" device=eth0 ipAddr=10.0.76.118 mtu=9001 subsys=mtu
```

### Helm config values
```js
{
  rollOutCiliumPods: true,
  autoDirectNodeRoutes: true,
  egressMasqueradeInterfaces: 'eth0',
  tunnel: 'disabled',
  kubeProxyReplacement: 'strict',
  k8sServiceHost: '10.1.0.1.',
  k8sServicePort: '443',
  loadBalancer: {
    algorithm: 'maglev',
    serviceTopology: true,
  },
  maglev: {
    hashSeed,
  },
  eni: {
    enabled: true,
    awsReleaseExcessIPs: true,
  },
  ipam: {
    mode: 'eni',
  },
  socketLB: {
    hostNamespaceOnly: true,
  },
  hubble: {
    enabled: true,
    relay: {
      enabled: true,
    },
    ui: {
      enabled: true,
    },
    metrics: {
      enabled: ['dns:query;ignoreAAAA', 'drop', 'tcp', 'flow', 'icmp', 'http'],
    },
    tls: {
      auto: {
        method: 'cronJob',
      },
    },
  },
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by munjalpatel**
Updated docs to indicate that users in cloud environments like EKS must use the Kubernetes service hostname instead of the endpoint IP address.

Signed-off-by: Munjal A Patel <munjalpatel@gmail.com>

---

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Fixes: #22039

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Review by brb — APPROVED** [review]
Thanks!

**Review by joestringer — COMMENTED** [review]
LGTM. Should we also update `Documentation/operations/upgrade.rst` to replace `API_SERVER_IP` with `API_SERVER_HOST`?

**Comment by munjalpatel** [comment]
@joestringer  that would be best to ensure consistency.

**Comment by joestringer** [comment]
@munjalpatel sounds good. Would you mind amending your PR / commit to include that change as well?

**Review by ldelossa — APPROVED** [review]

**Comment by joestringer** [comment]
@munjalpatel did you get a chance to look into the feedback above?

**Comment by munjalpatel** [comment]
> @munjalpatel did you get a chance to look into the feedback above?

Not yet. I’ll find some time to work on it in a few days.

**Comment by joestringer** [comment]
I would suggest using `git rebase` to rebase your changes on top of master, as the Cilium project does not accept submissions with merge commits from the main branch. Thanks.

**Review by joestringer — CHANGES_REQUESTED** [review]
Please also update the similar cases in `Documentation/operations/upgrade.rst` the same way. Then I think this should be good to merge :+1:

**Comment by joestringer** [comment]
Marked as draft. Once you've addressed the feedback, please click the "Ready for review" button at the bottom of the page.

**Comment by joestringer** [comment]
Hi @munjalpatel, any plans to rebase the PR? It looked pretty close based on the comments above.

**Comment by qmonnet** [comment]
The fix still looks useful. @munjalpatel, do you still have time to work on this?

**Pull request closed without merging**
