### PR TITLE
[1.12] Author backport of #28928 (Dns proxy use original source address and port)

### PR DESCRIPTION
**Pull request by jrajahalme**
* [ ] #27582 (@tklauser)
 * [ ] #28928 (@jrajahalme)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 27582 28928
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.12

**Review by squeed — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Comment by jrajahalme** [comment]
/test-1.17-4.9

**Comment by jrajahalme** [comment]
test-1.19-4.9

**Comment by jrajahalme** [comment]
/test-1.19-4.9

**Comment by jrajahalme** [comment]
/test-1.21-4.9

**Comment by nathanjsweet** [comment]
/test-1.19-4.9

**Comment by jrajahalme** [comment]
test-1.19-4.9 hit one known flake (#24840), I don't think it's worth wasting time running it again. Marking as ready-to-merge.

**Pull request merged**
