### PR TITLE
bugtool: add map dumps and events for all lb4/6 v3 backends

### PR DESCRIPTION
**Pull request by ti-mo**
Bugtool is missing dumps and events for lb4/6 v3 backends.

I'm using this PR to get some more output for https://github.com/cilium/cilium/issues/26062.

```release-note
Dump maps and events for all lb4/6 v3 backends
```

### CODE REVIEW

**Review by mhofstetter — APPROVED** [review]

**Comment by mhofstetter** [comment]
@ti-mo is this really of type `release-note/bug`?

**Review by rgo3 — APPROVED** [review]

**Comment by mhofstetter** [comment]
> I guess not, though it addresses an oversight in a released version of Cilium. Does it make a difference?

not really - even though IMO it's more kind of an enhancement/cleanup (of something that got missed) - and it's not actually fixing a bug. otherwise it gets mentioned as fixed bug in the release notes? i would label it as `release-note/misc`

**Review by michi-covalent — APPROVED** [review]

**Comment by ti-mo** [comment]
/test-1.26-net-next

**Comment by ti-mo** [comment]
/test-1.26-net-next

**Pull request merged**
