### PR TITLE
CmdRes.CombineOutput does not clobber stdout & SW demo fixup

### PR DESCRIPTION
**Pull request by raybejjani**
`CmdRes.CombineOutput` accidentally reused the `CmdRes.stdout` variable and modified it, corrupting later `CmdRes.StdOut` calls. This PR fixes that, and fixes the SW GSG demo to use only Stdout to check http codes.

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]

**Comment by ianvernon** [comment]
Looks like the tests didn't get triggered? Trying again.

**Comment by ianvernon** [comment]
test-me-please

**Comment by raybejjani** [comment]
they're scared of the conscequences

**Comment by ianvernon** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by eloycoto** [comment]
Issue with Kafka not related.

**Comment by eloycoto** [comment]
test-me-please

**Comment by raybejjani** [comment]
@eloycoto are you sure? it failed on that same test yesterday as well. I couldn't see how it could but it was a timeout, so it's likely some utility function relied on the older `CombineOutput` side-effects :/

**Comment by eloycoto** [comment]
@raybejjani yes, It is before the ExpectContains

```
Stacktrace

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:312
Failed to produce to empire-hq on topic deathstar-plans
Expected
    <*errors.errorString | 0xc420da0130>: {
        s: "ExecKafkaPodCmd: command 'kubectl exec -n default empire-hq-bc4bfbcc6-gnxx8 sh -- -c \"echo “deathstar reactor design v3” | ./kafka-produce.sh --topic deathstar-plans\"' failed '' || 'The connection to the server 192.168.36.11:6443 was refused - did you specify the right host or port?\n'",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/KafkaPolicies.go:153
```

Fixed in #3456

**Comment by raybejjani** [comment]
backport in https://github.com/cilium/cilium/pull/4009

**Pull request merged**
