### PR TITLE
ci: only report status after matrix jobs are done

### LINKED ISSUE #23729: CI: Premature GitHub status report in case of matrix jobs
Some GitHub Actions jobs which use the matrix feature are reporting their status prematurely.

The first matrix job which finishes successfully is going to report "success" to the PR status - which might be too early due to potentially failing parallel jobs within the same matrix. (failure will be reported correctly afterwards, but in the meantime the status shouldn't be succeeded)

status reporting should "never" be reported within the matrix itself and moved to the end into a separate job - whether pending at the beginning or the actual result at the end (but especially success)

examples:
* https://github.com/cilium/cilium/blob/master/.github/workflows/tests-datapath-verifier.yaml
* https://github.com/cilium/cilium/blob/master/.github/workflows/conformance-datapath.yaml

### PR DESCRIPTION
**Pull request by spacewander**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #23729

### CODE REVIEW

**Comment by spacewander** [comment]
The solution is found at https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow.

And its effect's similar to:
微信截图_20230218213054
微信截图_20230218213136

Currently I only update one CI workflow. If this one is accepted, I will update the remain workflows in this PR.

**Review by aanm — COMMENTED** [review]
@spacewander thank you for these changes. Does this work? I'm only asking because as far as I know the `if: ${{ success() }}`, ` if: ${{ failure() }}` and ` if: ${{ cancelled() }}` only refer to the steps from the same job, not from previous jobs.

**Comment by spacewander** [comment]
> @spacewander thank you for these changes. Does this work? I'm only asking because as far as I know the `if: ${{ success() }}`, ` if: ${{ failure() }}` and ` if: ${{ cancelled() }}` only refer to the steps from the same job, not from previous jobs.

Yes. GitHub documents this behavior at https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow.
I also tested it in my repo, the result can be seen from the screenshots in https://github.com/cilium/cilium/pull/23865#issuecomment-1435670521

**Review by nebril — APPROVED** [review]
Thanks! LGTM.

**Review by nbusseneau — CHANGES_REQUESTED** [review]
Thanks for your contribution! Unfortunately, I don't think this works as intended, as per the documentation: https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions

The status check functions only work for steps in the same job, as André was mentioning. Snippet from the doc (and same for other functions):

> `success`
> Returns true when none of the previous steps have failed or been canceled.

The failure one works with ancestor jobs, but I don't think it works for the others.

**Comment by nbusseneau** [comment]
I think for checking against previous jobs, we should instead use `needs.foo.result == 'success')` (with `foo` being the ancestor job): https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context

**Comment by spacewander** [comment]
Although GitHub's doc may not make it clear, the `success` can be used for previous job if the `if` condition is applied at the job level. Here is an example: https://github.com/spacewander/play_with_travis/blob/master/.github/workflows/ci.yml, the run result can be found in https://github.com/spacewander/play_with_travis/actions/runs/4238632888.

微信截图_20230222101520

We can see the "Set commit status to success" job is run after the matrix job "build" is successful.

**Review by nbusseneau — CHANGES_REQUESTED** [review]
Nice then! In this case we need for the reporting job to have access to the SHA, otherwise the commit status API step itself will fail (as is the case right now in the examples provided).

The following step needs to be added prior to calling the commit status API to retrieve the SHA:

```yaml
      - name: Set up job variables
        id: vars
        run: |
          if [ ${{ github.event.issue.pull_request || github.event.pull_request }} ]; then
            PR_API_JSON=$(curl \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              ${{ github.event.issue.pull_request.url || github.event.pull_request.url }})
            SHA=$(echo "$PR_API_JSON" | jq -r ".head.sha")
          else
            SHA=${{ github.sha }}
          fi
```

**Comment by brb** [comment]
@spacewander :wave: Are you still on this PR?

**Comment by brb** [comment]
@spacewander Thanks! Could you squash your commits into a single one?

**Comment by spacewander** [comment]
> @spacewander Thanks! Could you squash your commits into a single one?

Done

**Review by aanm — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Pull request merged**
