### PR TITLE
k8s: update k8s libraries to 1.18.18

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.8

**Review by joestringer — APPROVED** [review]

**Comment by qmonnet** [comment]
test-1.15-4.9

**Comment by qmonnet** [comment]
test-1.16-4.9

**Comment by qmonnet** [comment]
test-1.17-4.19

**Comment by qmonnet** [comment]
test-1.18-4.9

**Comment by aanm** [comment]
@qmonnet I haven't rebased this PR yet, I was waiting for https://github.com/cilium/cilium/pull/15739 and https://github.com/cilium/cilium/pull/15634 to be merged first.

**Comment by aanm** [comment]
test-backport-1.8

**Pull request merged**
