### PR TITLE
[v1.16] workflows: Extend IPsec tests to cover egress gateway

### PR DESCRIPTION
**Pull request by julianwiedmann**
Manual backport, to tolerate that KPR and IPsec don't work together on v1.15.

* [x] #35323

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 35323
```

### CODE REVIEW

**Comment by julianwiedmann** [comment]
/test-backport-1.16

**Review by pchaigno — APPROVED** [review]

**Pull request merged**
