### PR TITLE
Documentation: fix typos

### PR DESCRIPTION
**Pull request by aalemayhu**
o s/accross/across
o s/masquaraded/masqueraded
o s/abstration/abstraction
o s/precendence/precedence
o s/encounted/encountered
o s/alway/always
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/cilium/cilium/pull/458%23issuecomment-289243390%22%2C%20%22https%3A//github.com/cilium/cilium/pull/458%23issuecomment-289270206%22%2C%20%22https%3A//github.com/cilium/cilium/pull/458%23issuecomment-289577503%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/cilium/cilium/pull/458%23issuecomment-289243390%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Dan%20is%20working%20on%20a%20bigger%20doc%20update%2C%20we%27ll%20wait%20with%20this%20as%20this%20is%20easier%20to%20rebase%20on%20top%20of%20his%20work%20than%20the%20other%20way%20around.%22%2C%20%22created_at%22%3A%20%222017-03-25T22%3A17%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1417913%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tgraf%22%7D%7D%2C%20%7B%22body%22%3A%20%22On%20Sat%2C%20Mar%2025%2C%202017%20at%2003%3A17%3A25PM%20-0700%2C%20Thomas%20Graf%20wrote%3A%5Cn%3E%20Dan%20is%20working%20on%20a%20bigger%20doc%20update%2C%20we%27ll%20wait%20with%20this%20as%20this%20is%20easier%5Cn%3E%20to%20rebase%20on%20top%20of%20his%20work%20than%20the%20other%20way%20around.%5Cn%3E%5CnOK%2C%20looking%20forward%20to%20reading%20it.%5Cn%5Cn--%20%5CnMit%20freundlichen%20Gr%5Cu00fc%5Cu00dfen%5Cn%5CnAlexander%20Alemayhu%5Cn%22%2C%20%22created_at%22%3A%20%222017-03-26T10%3A05%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/925044%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/scanf%22%7D%7D%2C%20%7B%22body%22%3A%20%22Looks%20like%20these%20will%20be%20handled%20in%20other%20prs.%22%2C%20%22created_at%22%3A%20%222017-03-27T20%3A34%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/925044%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/scanf%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/cilium/cilium/pull/458#issuecomment-289243390'>General Comment</a></b>
- <a href='https://github.com/tgraf'></a> Dan is working on a bigger doc update, we'll wait with this as this is easier to rebase on top of his work than the other way around.
- <a href='https://github.com/scanf'></a> On Sat, Mar 25, 2017 at 03:17:25PM -0700, Thomas Graf wrote:
> Dan is working on a bigger doc update, we'll wait with this as this is easier
> to rebase on top of his work than the other way around.
>
OK, looking forward to reading it.
--
Mit freundlichen Grüßen
Alexander Alemayhu
- <a href='https://github.com/scanf'></a> Looks like these will be handled in other prs.

<a href='https://www.codereviewhub.com/cilium/cilium/pull/458?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/cilium/cilium/pull/458?approve=1'></a>&nbsp;<a href='https://github.com/cilium/cilium/pull/458'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by aanm** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/cilium/cilium/pull/458'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by tgraf** [comment]
Dan is working on a bigger doc update, we'll wait with this as this is easier to rebase on top of his work than the other way around.

**Comment by aalemayhu** [comment]
On Sat, Mar 25, 2017 at 03:17:25PM -0700, Thomas Graf wrote:
> Dan is working on a bigger doc update, we'll wait with this as this is easier
> to rebase on top of his work than the other way around.
>
OK, looking forward to reading it.

-- 
Mit freundlichen Grüßen

Alexander Alemayhu

**Comment by aalemayhu** [comment]
Looks like these will be handled in other prs.

**Pull request closed without merging**
