### PR TITLE
Pr/v1.1 backport 18 07 30

### PR DESCRIPTION
**Pull request by joestringer**
* #4945                                                                         
  * Required #4768 to cleanly apply                                             
* #4998                                                                         
  * Did not cleanly apply - @nebril please review
    * `pkg/endpoint/bpf.go`
    * `pkg/api` changes autoapplied to `pkg/apisocket` during cherry-pick, so I imported `apisocket` as `api` to minimize diff from original patches
* #5019                                                                         
* #5021                                                                         
* #5024                                                                         
* #5029

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5042)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
CI failure:

```
12:31:42 pkg/client/config.go:20:2: cannot find package "github.com/cilium/cilium/pkg/api" in any of:
12:31:42 	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/cilium/pkg/api (vendor tree)
12:31:42 	/usr/local/go/src/github.com/cilium/cilium/pkg/api (from $GOROOT)
12:31:42 	/go/src/github.com/cilium/cilium/pkg/api (from $GOPATH)
```

**Comment by joestringer** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by tgraf** [comment]
I've reviewed the backport of #4998. Looks good. Nebril is out today.

**Pull request merged**
