### PR TITLE
v1.10 backports 2021-10-18

### PR DESCRIPTION
**Pull request by joamaki**
* #17364 -- bpf/Makefile: Enable setting complexity options (@pchaigno)
 * #17408 -- verifier-test.sh: allow for empty FOO_PROGS (@kkourt)
 * #17587 -- .github: Fix codeQL workflow skip logic (@joestringer)
 * #17581 -- k8sT/Egress: fixes (@kkourt)
 * #17529 -- aks: fix AKS cluster creation following new taint limitations *Documentation only* (@nbusseneau) 

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 17364 17408 17587 17529 17581; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by joamaki** [comment]
#17529 skipped as it was modifying files that were removed from v1.10 in 65eb99a85596cc36fdd74ebcaabec44eb7769479.

**Review by nbusseneau — CHANGES_REQUESTED** [review]
> #17529 skipped as it was modifying files that were removed from v1.10 in [65eb99a](https://github.com/cilium/cilium/commit/65eb99a85596cc36fdd74ebcaabec44eb7769479).

The documentation changes need backporting, but the workflow changes indeed do not: we can ignore c5f5de861061367b436adf1be47f47d5c79f569b and backport only 2cb55ca6552904d48b24cc8fd5112ca9ebf9a847 🙏🏻

**Review by nbusseneau — APPROVED** [review]
Thanks, LGTM for #17529.

**Review by pchaigno — APPROVED** [review]
> * bpf/Makefile: Enable setting complexity options #17364 -- bpf/Makefile: Enable setting complexity options (@pchaigno)
> * verifier-test.sh: allow for empty FOO_PROGS #17408 -- verifier-test.sh: allow for empty FOO_PROGS (@kkourt)

Those two commits look okay to me.

**Review by joestringer — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Review by kkourt — APPROVED** [review]

**Pull request merged**
