### PR TITLE
v1.9: Update Go to 1.15.8

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
test-backport-1.9

**Review by jibi — APPROVED** [review]

**Comment by tklauser** [comment]
Smoke tests hit #14950 (fix not yet backported to `v1.9` branch).

**Comment by tklauser** [comment]
retest-gke

**Comment by tklauser** [comment]
test-missed-k8s

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@tklauser the smoke tests was backported in https://github.com/cilium/cilium/pull/14961

**Comment by aanm** [comment]
test-gke

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by tklauser** [comment]
test-backport-1.9

**Comment by tklauser** [comment]
retest-gke

**Comment by jibi** [comment]
retest-gke

**Comment by tklauser** [comment]
retest-gke

**Comment by jibi** [comment]
retest-gke

**Comment by tklauser** [comment]
retest-gke

**Comment by aanm** [comment]
test-gke

**Comment by aanm** [comment]
test-gke

**Comment by aanm** [comment]
The GKE tests were failing before this PR. Merging...

**Pull request merged**
