### PR TITLE
images: squash common operator images in a single Dockerfile

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-gke

**Comment by aanm** [comment]
This patch was applied before just to test the new images, and they wer green as we can see in the screenshot:

```patch
diff --git a/.github/workflows/images-legacy.yaml b/.github/workflows/images-legacy.yaml
index aad779ceff..c416b8d0c0 100644
--- a/.github/workflows/images-legacy.yaml
+++ b/.github/workflows/images-legacy.yaml
@@ -9,7 +9,6 @@ on:
   push:
     branches:
       - master
-      - pr/squash-operator-images
 
 jobs:
   build-and-push-prs:
```


image

The failures presented by GH action are now expected because it's running workflow from master and the Dockerfiles no longer exist.

**Review by michi-covalent — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
Nice! :tada:

**Pull request merged**
