### PR TITLE
docs: Add link to CI failure triage to contributing guide

### PR DESCRIPTION
**Pull request by twpayne**
As requested by @joestringer. It turns out there's already a detailed section on identifying flaky tests in the docs, this just adds a link to it from the Development Guide.

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
LGTM!

(We should update that page with up-to-date test names & info, as well as references to the CI dashboard.)

**Review by joestringer — APPROVED** [review]
LGTM. Would be nice to get a new mention of the CI dashboard under `Triage Process` too. Happy to iterate/provide pointers on that/answer related questions on Slack so we can get that in as well.

**Comment by joestringer** [comment]
And coincidentally, Travis is providing a great example of why we have these docs...

The failure is here:
https://travis-ci.com/github/cilium/cilium/jobs/396946063

The test is `TestNodeManagerReleaseAddress`, which if we search issues points towards #11990 , and the error matches so it's a known flake. Safe to ignore, though if you'd like to pick it up and investigate to figure out how to prevent this test from flaking then that'd be awesome. Not required to merge this PR though.

**Comment by joestringer** [comment]
Only docs changes in the PR, and GH docs check reports success, so merging.

**Pull request merged**
