### PR TITLE
v1.9 backports 2021-03-12

### PR DESCRIPTION
**Pull request by kaworu**
* #15182 -- azure: Add the correct JSON tag to GatewayIP field in CiliumNode CRD (@AnishShah)
  - **NOTE**: partially backported, see https://github.com/cilium/cilium/pull/15331#issuecomment-797582199
* #15304 -- doc: Document minimal version of AWS CNI in chaining mode (@tgraf)
* #15263 -- node: Fix CIDR comparison when updating routes (@brb)
* #15194 -- azure: populate ApplicationSecurityGroups field in the new IPConfigurations (@AnishShah)
* #15303 -- ipam: Fix ENI routing for secondary CIDRs (@gandro)

Skipped:
 * #15228 -- endpoint: Fix the initialization of endpoints' datapath configs (@pchaigno)
   * lacking context to resolve the conflict around the `RequireRouting` disable.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 15182 15304 15263 15194 15303; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by kaworu** [comment]
@ti-mo could you take a close look at the backport of #15182 (azure: Add the correct JSON tag to GatewayIP field in CiliumNode CRD) please?

I had to resolve some conflicts and I lack context about how `pkg/k8s/apis/cilium.io/v2/client/bindata.go` is generated. Specifically: does it matter that the `vmssName` member of `AzureInterface` is named differently between v1.9 (`VMSSName`) and master (`vmssName`) or is it only a public/private scope change without impact?

**Comment by kaworu** [comment]
test-backport-1.9

**Comment by AnishShah** [comment]
The wedding commit of #15182 doesn't need backport I think. @aanm

**Comment by aanm** [comment]
> The wedding commit of #15182 doesn't need backport I think. @aanm

If you mean the one with the tittle "azure: Add Gateway field to AzureInterface and deprecate GatewayIP field" I agree, we need to drop that one.

**Comment by kaworu** [comment]
@AnishShah thank you, I've dropped "azure: Add Gateway field to AzureInterface and deprecate GatewayIP field" from this PR, please take another look!

/cc @aanm

**Review by tgraf — APPROVED** [review]

**Comment by kaworu** [comment]
@gandro this [CI failure](https://github.com/cilium/cilium/pull/15331/checks?check_run_id=2111004327) seems to be related to [this patch](https://github.com/cilium/cilium/pull/15303/commits/40c50668352aaf43d81ad942257da2dfe6ae212d). In `v1.9` we have [aws-sdk-go-v2@v0.24.0](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2@v0.24.0) vs [aws-sdk-go-v2@v1.2.0
](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2@v1.2.0) in `master`.

From https://aws.github.io/aws-sdk-go-v2/docs/migrating/#pointer-parameters
> When upgrading your application from AWS SDK for Go V1 to AWS SDK for Go V2, you must migrate usage of the helpers for converting from the pointer types to the non-pointer variants. For example, `aws.StringValue` must be updated to `aws.ToString`.

So I just `s/ToString/StringValue/`, please take a look.

**Comment by ti-mo** [comment]
@kaworu Correct, the struct members in `azure/types/types.go` were lowercased in https://github.com/cilium/cilium/commit/7cd51b689afbbd2e62d70eb39b163e06486acae6. Looks like we could backport that change as well, but might be safer to hold off since it's relatively cross-cutting.

Can't provide any context on bindata generation, sorry. :frowning_face: Do we generate bindata in CI and check if it dirties the repo?

**Review by gandro — APPROVED** [review]
My commit looks good! Thanks for fixing!

**Comment by kaworu** [comment]
@ti-mo thanks for taking a look,  @AnishShah and @aanm both commented about #15182 so hopefully they can comment also on the bindata stuff.

**Comment by kaworu** [comment]
test-backport-1.9

**Review by jrajahalme — APPROVED** [review]

**Comment by AnishShah** [comment]
I think we do check if the any changes in bindata dirties the repo. It is "Go-related checks / generate-api". But I'm not sure.

**Comment by kaworu** [comment]
test-backport-1.9

**Review by ti-mo — APPROVED** [review]

**Comment by kaworu** [comment]
test-1.12-netnext

**Comment by kaworu** [comment]
> I think we do check if the any changes in bindata dirties the repo. It is "Go-related checks / generate-api". But I'm not sure.

@AnishShah FWIW I've checked and your statement is correct:

https://github.com/cilium/cilium/blob/9fa8b2dbdb53aaa5325729388ded6b9fa045e560/.github/workflows/go-check.yaml#L95

https://github.com/cilium/cilium/blob/9fa8b2dbdb53aaa5325729388ded6b9fa045e560/contrib/scripts/check-k8s-code-gen.sh#L16-L27

https://github.com/cilium/cilium/blob/9fa8b2dbdb53aaa5325729388ded6b9fa045e560/Makefile#L414-L422

**Review by brb — APPROVED** [review]
:+1: for my changes, thanks.

**Pull request merged**
