### PR TITLE
envoy: Update envoy version to the latest build

### PR DESCRIPTION
**Pull request by sayboras**
This commit is to perform the below:

- Update envoy image to latest build
- Include new resources into pkg/envoy/resource for serialization
  - grpc related resources are for upcoming support with GRPCRoute
- Change policy id to uint32, related to https://github.com/cilium/proxy/commit/f37daf70991e4d58fc610244fb559cf48ea475e2

Related build: https://github.com/cilium/proxy/actions/runs/5974676861/job/16210098929

### CODE REVIEW

**Review by tklauser — APPROVED** [review]
vendor changes LGTM

**Review by kaworu — APPROVED** [review]
Helm changes LGTM.

**Review by ghost — APPROVED** [review]
The docs change looks good.

However, I'm a bit worried about maintainability of the extensions list. At the moment the docs contain both:
* a link to the config in cilium/proxy (but to the main branch, not the corresponding version)
* a list of enabled extensions

It seems duplicated information. When extra extensions are enabled it's easy to miss a Cilium docs update, and also users on older versions might get confused by the list on the main branch. Could we handle this sync better? Maybe have only a link to cilium/proxy repo, but to the corresponding tag?

It's probably something for a follow-up, not for this PR, so I'm approving this one.

**Comment by sayboras** [comment]
Not sure why a couple of GHA jobs are not kicking off, retry with rebase.

**Review by youngnick — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]

**Comment by jrajahalme** [comment]
Superseded by #27819 to fix the merge conflict (@kaworu @tklauser @lambdanis @youngnick).

**Pull request closed without merging**
