### PR TITLE
v1.13 backports 2023-07-27

### PR DESCRIPTION
**Pull request by pchaigno**
- [x] #25114 -- bpf: test: Fix the byte order in the IPV4 macro (@gentoo-root)
 - [x] #25191 -- bpf,test: Fix verifier issues in IPv6 BPF tests when running locally (@dylandreimerink)
 - [x] #25699 -- Add BPF unit tests for IPsec (@jschwinger233)
 - [ ] #27029 -- ipsec, auth: Avoid out-of-order events that lead to inconsistent node IDs (@pchaigno)
     - Commits bbeda92bcf3816e54df0edd8b4cb1c28dab09df6, c1f4a63aac4d54252445e81aec11a50b7f7acf2b, 52b0430c9ef7701d2a57cad91455cea382c7010f, and fc8da7266ab03b6813cb7469e2fd217187308acc were skipped because the node ID map doesn't use the hive framework and Mutual Auth feature is only in v1.14.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 25114 25191 25699 27029; do contrib/backporting/set-labels.py $pr done 1.13; done
```

### CODE REVIEW

**Comment by pchaigno** [comment]
/test-backport-1.13

**Comment by pchaigno** [comment]
/test-backport-1.13

**Comment by pchaigno** [comment]
/test-backport-1.13

**Comment by pchaigno** [comment]
/test-backport-1.13

**Review by gandro — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Review by jschwinger233 — APPROVED** [review]
Thank you Paul!

**Comment by jschwinger233** [comment]
/test-1.18-4.19

**Review by gentoo-root — APPROVED** [review]
+1 for my commit.

**Comment by pchaigno** [comment]
Marking ready to merge to summon tophat who also happen to be the last missing reviewers. Travis CI failed with known flake https://github.com/cilium/cilium/issues/25272.

**Review by dylandreimerink — APPROVED** [review]

**Pull request merged**
