### PR TITLE
ci: parametrize jenkinsfile to accept k8s version

### PR DESCRIPTION
**Pull request by nebril**
This change will allow developers to focus-test on any supported
k8s-kernel version pair.

### CODE REVIEW

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-only --k8s_version=1.11 --focus="K8sServices" --kernel_version=net-next

**Comment by nebril** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by nebril** [comment]
Since all CI passed for this PR already, I will document these changes in followup PR.

**Pull request merged**
