### PR TITLE
BGP: Removing metallb BGP integration

### PR DESCRIPTION
**Pull request by harsimran-pabla**
Metallb BGP integration in Cilium has been deprecated since v1.14 release. Original issue for deprecation tracking https://github.com/cilium/cilium/issues/22246.

Announcement to OSS community: https://cilium.slack.com/archives/C06HL734BM5/p1731082755110609

Migration path to Cilium BGP Control Plane: https://isovalent.com/blog/post/migrating-from-metallb-to-cilium/ 

```release-note
bgp: remove metallb bgp integration.
```

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]
lgtm on cli change. i'm guessing there will be another PR to update the documentation? 📝

**Review by rastislavs — APPROVED** [review]
🧹 Thanks!

**Review by mhofstetter — APPROVED** [review]
Great - thanks! :tada:

**Review by bimmlerd — APPROVED** [review]
:broom:

**Review by marseel — APPROVED** [review]
Thanks!

**Review by dlapcevic — APPROVED** [review]

**Review by youngnick — APPROVED** [review]

**Review by gandro — COMMENTED** [review]
~Can we add a note in the upgrade docs please?~

Edit: Apologies, I missed [the comment above](https://github.com/cilium/cilium/pull/36191#issuecomment-2506536490). Approving now

**Review by gandro — APPROVED** [review]

**Review by derailed — APPROVED** [review]
@harsimran-pabla Nice work!

**Pull request merged**
