### PR TITLE
v1.7 backports 2020-12-02

### PR DESCRIPTION
**Pull request by jrajahalme**
* #14222 -- vendor: Fix cilium/arping goroutine leak (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14222; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-backport-1.7

**Comment by jrajahalme** [comment]
Ran `./contrib/go-mod/update-vendor.sh`

**Comment by jrajahalme** [comment]
test-backport-1.7

**Comment by joestringer** [comment]
Hit https://github.com/cilium/cilium/issues/10678 in Travis,  this seems to be a very rare flake that we thought we had resolved: https://travis-ci.com/github/cilium/cilium/builds/206001905

And regular ginkgo tests VM provisioning failed:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/20027/

**Comment by joestringer** [comment]
test-backport-1.7

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
Previous failure was https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3763/testReport/junit/Suite-k8s-1/14/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications/

**Pull request merged**
