### PR TITLE
v1.15 Backports 2024-04-22

### LINKED ISSUE #32095: Severe network bug on v1.15.4
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Upon upgrading from v1.15.3 -> v1.15.4 and doing a few node reboots, some nodes start failing pod connectivity.

```
Controller Status:      123/124 healthy
  Name                                  Last success   Last error   Count   Message
  endpoint-1578-regeneration-recovery   never          38s ago      39      regeneration recovery failed
  ```

It seems BPF gets in a really weird state trying to come back and then I see this as well: `creating bpffs link dir for device bond0.713: mkdir /sys/fs/bpf/cilium/devices/bond0.713: operation not permitted`

Once I roll back to v1.15.3, it creates the endpoint and pod connectivity comes back immediately.

### Cilium Version

v1.15.4

### Kernel Version

6.1.82

### Kubernetes Version

v1.29.4

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jschwinger233**
* [x] #30579 (@joamaki)
 * [x] #31510 (@giorio94)
 * [x] #31970 (@joestringer)
 * [x] #31959 (@marseel)
 * [x] #32004 (@jrajahalme)
 * [x] #31958 (@giorio94)
 * [x] #31964 (@sayboras)
 * [x] #32042 (@giorio94)
 * [x] #32090 (@rgo3)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30579 31510 31970 31959 32004 31958 31964 32042 32090
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commit :+1:

**Comment by jschwinger233** [comment]
/test-backport-1.15

**Review by giorio94 — APPROVED** [review]
My PRs look good, thanks!

**Comment by jschwinger233** [comment]
/test-backport-1.15

**Review by marseel — APPROVED** [review]

**Review by rgo3 — APPROVED** [review]
My commit lgtm

**Review by jrajahalme — APPROVED** [review]
My commits LGTM

**Review by joamaki — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Review by ti-mo — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Pull request merged**
