### PR TITLE
api: don't attempt to set unix domain socket group to `cilium`

### PR DESCRIPTION
**Pull request by tklauser**
Since commit 67f74ff43201 ("images/cilium: remove cilium group from
Dockerfile") the cilium group is no longer created in the image running
the agent, resulting in the following log message on cilium-agent start:

```
level=info msg="Group not found" error="group: unknown group cilium" file-path=/var/run/cilium/cilium.sock group=cilium subsys=api
```

Setting the group is no longer necessary, so that part of
`SetDefaultPermissions`.

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Review by tommyp1ckles — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
Nice cleanup, thanks. I think when we support non-root, this should also not be necessary so :+1:

**Comment by tklauser** [comment]
Added a second commit to drop the `cilium` group from dev and test VMs as well. This should fix the failing runtime tests.

**Review by christarazi — APPROVED** [review]

**Pull request closed without merging**
