### PR TITLE
v1.7: Istio backports 2020-04-01

### PR DESCRIPTION
**Pull request by jrajahalme**
v1.7 backports 2020-04-01

 * #10730 -- test: Update Istio integration to release 1.5.1 (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10730; do contrib/backporting/set-labels.py $pr done 1.7; done
```

```release-note
Istio integration is updated to release 1.5.1, with backported fix for GKE/COS.
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-gke K8sIstio.*

**Comment by jrajahalme** [comment]
test-me-please

**Comment by joestringer** [comment]
I think that we haven't backported all GKE test infrastructure to v1.7 branch, so will plan to ignore that failure:
https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/217/
```
13:15:54  + ./select-cluster.sh
13:15:54  rm: cannot remove 'gke-kubeconfig': No such file or directory
13:15:54  selecting random cluster
13:15:54  getting kubeconfig for 
13:15:55  ERROR: (gcloud.container.clusters.get-credentials) argument NAME: Must be specified.
13:15:55  Usage: gcloud container clusters get-credentials NAME [optional flags]
13:15:55    optional flags may be  --help | --internal-ip | --region | --zone
13:15:55  
13:15:55  For detailed information on this command and its flags, run:
13:15:55    gcloud container clusters get-credentials --help
```

**Comment by joestringer** [comment]
Pipeline test for `Cilium-tests-with-kernel` is empty, seems broken on v1.7 (/cc @nebril @raybejjani ):
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/94/flowGraphTable/

**Pull request merged**
