### PR TITLE
Provide CT/NAT maps GC logic through hive

### PR DESCRIPTION
**Pull request by giorio94**
Please refer to the commit descriptions for additional details.

### CODE REVIEW

**Comment by giorio94** [comment]
Converting back to draft, the integration test failure is legitimate.

**Review by gentoo-root — APPROVED** [review]

**Review by markpash — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by giorio94** [comment]
CI is green, code owners reviews are covered. Marking as ready to merge.

**Pull request merged**
