### PR TITLE
Ginkgo: 05-cni migration

### PR DESCRIPTION
**Pull request by eloycoto**
- Moving 05-cni.sh test to Ginkgo. 
- Added new context on runtime/connectivity.go testcase

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-all-ginkgo

**Review by ianvernon — APPROVED** [review]
LGTM!

**Comment by eloycoto** [comment]
test-all-ginkgo

**Comment by eloycoto** [comment]
test-all-ginkgo

**Comment by eloycoto** [comment]
test-all-ginkgo

**Comment by eloycoto** [comment]
test-all-ginkgo

**Comment by eloycoto** [comment]
test-all-ginkgo

**Comment by eloycoto** [comment]
test-all-ginkgo

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-all-ginkgo

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
I've just rebased with master due the changes that Thomas did on `cilium.WaitEndpointsReady()`

**Comment by eloycoto** [comment]
test-all-ginkgo

**Comment by eloycoto** [comment]
test-all-ginkgo

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-all-ginkgo

**Comment by eloycoto** [comment]
test-me-please

**Comment by ianvernon** [comment]
https://jenkins.cilium.io/job/Cilium-Ginkgo-Tests/250/ failed due to odd issues with Envoy, so I'm retriggering a build.

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
