### PR TITLE
pkg/envoy: update generated files

### PR DESCRIPTION
**Pull request by aanm**
This updates generated files with the development VM v106.

Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5146)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]
Thank you!

**Comment by ianvernon** [comment]
@aanm out of curiosity, how did you make these files? Would be good to document updating these files in the future in case things get out of sync again.

**Comment by tgraf** [comment]
Does this need a 1.2 backport?

**Comment by rlenglet** [comment]
Ideally yes, that should be backported. But it’s not critical since those files are regenerated on every build.

**Comment by aanm** [comment]
@ianvernon they just shown up after doing starting a development VM.

**Comment by ianvernon** [comment]
@aanm easy enough :-) thanks!

**Pull request merged**
