### PR TITLE
tests: Use multiple clang releases

### PR DESCRIPTION
**Pull request by aalemayhu**
Checking how long it takes to build this.

### CODE REVIEW

**Comment by aanm** [comment]
@scanf are those clang versions already installed? maybe this should be for nightly builds?

**Comment by aalemayhu** [comment]
@aanm No they are not installed but that is not an issue since it will skip the missing ones. Have opened up a pull request for the [packer script][0]. The last failing test is in the `K8s multi node Tests`. Have checked that this is behaving as expected. Why did you remove the label I added? 

[0]: https://github.com/cilium/packer-ubuntu-16.10/pull/13

**Comment by aanm** [comment]
> Why did you remove the label I added?

@scanf because I think this should be discussed. When we add clang tests will get slower which I think we should move this to the nightly tests

**Comment by aalemayhu** [comment]
@aanm I disagree about moving this to the nightly tests. If you look closely at the diff we are only running two of the tests. It should not take much longer.

**Comment by ianvernon** [comment]
Do you still want review on this? I see you added the `wip` tag. Please remove the `pending-review` tag, and remove the `wip` tag if it is ready for review.

**Comment by ianvernon** [comment]
I prefer running different versions of things (clang, kernel, etc.) as part of the nightly tests. PR builds should be testing core functionality against a specific version to reduce the complexity of merging code.

**Comment by aalemayhu** [comment]
Removed the label. Initially, it was ready, but after discussing with Daniel I made some other changes.  IIRC those changes will trigger the instruction limit. The last thing we talked about was wrapping this with an environment variable but that will affect bisectability. It would be nice to run some of the tests with several LLVM releases but when dropping the debug flag right now we hit the verifier issues which will break the build. 

I will drop this since it seems the preference is for adding something in the nightly.

**Pull request closed without merging**
