### PR TITLE
endpoint: Better name for policyRevision log messages

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5288)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
Can we wait until this gets merged? https://github.com/cilium/cilium/pull/5270

**Comment by tgraf** [comment]
sure

**Review by joestringer — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
