### PR TITLE
test: add k8s 1.13 to testing framework

### PR DESCRIPTION
**Pull request by aanm**
As we are always testing against k8s 1.8 can remove it from
ginkgo-kubernetes-all.Jenkinsfile

Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5959)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by eloycoto** [comment]
@aanm tried the setup, the config for kubeadm changed to Init and ClusterConfig: 

```
KUBEADM_CONFIG_ALPHA3=$(cat <<-EOF
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
apiEndpoint:
  advertiseAddress: {{ .KUBEADM_ADDR }}
  bindPort: 6443
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: {{ .TOKEN }}
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
nodeRegistration:
  criSocket: "{{ .KUBEADM_CRI_SOCKET }}"
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: "v{{ .K8S_FULL_VERSION }}"
networking:
  dnsDomain: cluster.local
  podSubnet: "{{ .KUBEADM_POD_NETWORK }}/{{ .KUBEADM_POD_CIDR}}"
  serviceSubnet: "{{ .KUBEADM_SVC_CIDR }}"
EOF
)
```

That works ok: 
```
vagrant@k8s1:~$ kubectl get nodes
NAME   STATUS     ROLES    AGE     VERSION
k8s1   NotReady   master   4m41s   v1.13.0-alpha.3
k8s2   NotReady   <none>   108s    v1.13.0-alpha.3
```

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
previous failure https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1265/flowGraphTable/

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Tests failed for K8s 1.9: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1318/

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Comment by aanm** [comment]
deprecated by https://github.com/cilium/cilium/pull/6297

**Pull request closed without merging**
