### PR TITLE
v1.6 backport 19-09-27

### PR DESCRIPTION
**Pull request by jrfastab**
PRs:
#9288
#9291
#9278

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9293)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
retest seems we hit this, https://github.com/cilium/cilium/issues/8775?

**Comment by jrfastab** [comment]
missing,
`cilium-health/launch/endpoint.go:45:2: cannot find package "github.com/cilium/cilium/pkg/sysctl"`

**Comment by jrfastab** [comment]
Added ./pkg/sysctl only three patches so pull the entire thing in vs trying to cherry pick specific required pieces.

**Comment by jrfastab** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Pull request merged**
