### PR TITLE
docs: Mark pod-short option in Hubble metrics as deprecated

### PR DESCRIPTION
**Pull request by ghost**
As one of source/destination context options in Hubble metrics, `pod-short` tries to provide a workload name. However, this option is correct only in some cases. It naively cuts two last bits starting with '-' from the pod name. For Deployments this will indeed result in the Deployment name. But e.g. for StatefulSets or DaemonSets, it will cut too much, unless the workload name doesn't contain hyphens. For standalone pods it's completely meaningless.

For example:
* Deployment `hubble-relay`, pod `hubble-relay-7c7bf78559-6b46b`, pod-short `huble-relay` - ok
* DaemonSet `cilium`, pod `cilium-2kp2v`, pod-short `cilium` - ok
* DaemonSet `cilium-node-init`, pod `cilium-node-init-c6gmz`, pod-short `cilium-node` - not ok
* standalone pod `my-amazing-pod`, pod-short `my` - not ok

There is also `workload-name` option, which provides the correct workload name from the pod metadata. It should be preferred over `pod-short`. Additionally, users might want to add `pod` option as a fallback, to handle bare pods correctly.

This PR only marks the `pod-short` option as deprecated in docs. Can it be backported to 1.13? Then this option can be removed in the next release.

### CODE REVIEW

**Review by chancez — APPROVED** [review]
Good idea.

**Review by qmonnet — APPROVED** [review]
Looks good, thank you.

Any plan to deprecate `pod-short` in a future version?

**Comment by lambdanis** [comment]
> Any plan to deprecate pod-short in a future version?

@qmonnet You mean to delete? I would consider it deprecated already (ideally this PR would get backported to 1.13) and the plan is to delete it soon.

**Comment by qmonnet** [comment]
Sorry I had missed the last sentence of your PR description. OK thanks, I added the label for the 1.13 backport.

In that case it might be worth adding a comment next to `pod-short` in the source to remember to remove it, see e.g. in pkg/ipam/metrics/metrics.go: `// Deprecated, will be removed in version 1.14`.

**Comment by qmonnet** [comment]
Also I note that `pod-short` is still used in some test files under `pkg/hubble/metric/`, would it make sense to update to `workload-name|pod` in there as well?

**Comment by lambdanis** [comment]
@qmonnet Updated with your suggestion.

Regarding tests - I think they should be updated when the option is removed, but I wanted to keep the backport tiny to avoid any conflicts.

**Comment by qmonnet** [comment]
> I wanted to keep the backport tiny to avoid any conflicts.

v1.13 hasn't shipped yet, it's unlikely we'd hit many conflicts on these test files.

> Plus in most of the tests it doesn't really matter which option is used.

Isn't that one more reason to update them? :) But OK

**Review by aditighag — APPROVED** [review]

**Comment by Shunpoco** [comment]
[It's just a question]
I think `pod-short` contains its namespace as a prefix (like `some-namespace/some-deployment`), but `workload-name` doesn't contain the prefix. So, `workload-name | pod` can not completely replace `pod-short`.
I think it's ok to mark `pod-short` as deprecated, but should we add the namespace prefix for `workload-name` or should we add an option to add namespace as a prefix for whole contexts?

**Comment by lambdanis** [comment]
> should we add the namespace prefix for workload-name

I would rather go the other way - add another option (e.g. `pod-name`) for pod without namespace, and recommend using it over `pod`. Namespace information can be added as separate labels via `labelsContext`.

> or should we add an option to add namespace as a prefix for whole contexts?

Personally I don't really see a reason for doing it. Namespaces can be added as separate labels, and I'd prefer doing that rather than including namespace in source/destination labels. If someone really needs labels in namespace/workload format, then it can be achieved with relabeling rules.

More discussion on that here: https://github.com/cilium/cilium/issues/23122

The `workload-name|pod` option I suggested might be indeed confusing because of this issue. Although I think it's still better than using `pod-short` - this one is simply incorrect.

**Comment by ldelossa** [comment]
docs only, full test suite not necessary.

**Pull request merged**
