### PR TITLE
WIP sockmap v4

### PR DESCRIPTION
**Pull request by jrfastab**
verify we didn't break anything on the non-sockmap case.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5629)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by joestringer** [comment]
```
18:42:25 contrib/scripts/check-logging-subsys-field.sh
18:42:25 ./pkg/maps/sockmap/sockmap.go:81:var log = logging.DefaultLogger
18:42:25 Logging entry instances have to contain the LogSubsys field. Example of
18:42:25 properly configured entry instance:
18:42:25 
18:42:25 	import (
18:42:25 		"github.com/cilium/cilium/pkg/logging"
18:42:25 		"github.com/cilium/cilium/pkg/logging/logfields"
18:42:25 	)
18:42:25 
18:42:25 	var log = logging.DefaultLogger.WithField(logfields.LogSubsys, "my-subsystem")
18:42:25 
18:42:25 Makefile:227: recipe for target 'logging-subsys-field' failed
```

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
passing great, close for now need some cleanups in pkg/sockops

**Pull request closed without merging**
