### PR TITLE
ipcache: Re-create keys when necessary

### PR DESCRIPTION
**Pull request by tgraf**
The ipcache is not resilient to key removals right now. If keys are mistakenly
removed from the kvstore even though the ipcache entry is still in use locally,
the ipcache entry in the datapath will be blindly deleted.

Instead, verify whether the ipcache entry is still in use locally and re-create
the key if necessary. This covers cases where keys are deleted manually, the
kvstore state is restored from a backup, the kvstore is buggy or Cilium is
deleting a key by mistake.

Tested manually by deleting ipcache keys in the kvstore.

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5804)

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by joestringer** [comment]
Failure:

```
23:55:34 fatal error: sync: unlock of unlocked mutex
23:55:34 level=info msg="Envoy: Starting xDS gRPC server listening on /tmp/cilium-test-run308577933/xds.sock" subsys=envoy-manager
23:55:34 
23:55:34 goroutine 239 [running]:
23:55:34 runtime.throw(0x2ab8022, 0x1e)
23:55:34 	/usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc421a57bf8 sp=0xc421a57bd8 pc=0xfd8001
23:55:34 sync.throw(0x2ab8022, 0x1e)
23:55:34 	/usr/local/go/src/runtime/panic.go:605 +0x35 fp=0xc421a57c18 sp=0xc421a57bf8 pc=0xfd7f75
23:55:34 sync.(*Mutex).Unlock(0xc421729920)
23:55:34 	/usr/local/go/src/sync/mutex.go:184 +0xc2 fp=0xc421a57c40 sp=0xc421a57c18 pc=0x100f9a2
23:55:34 github.com/cilium/cilium/pkg/ipcache.(*IPIdentityWatcher).Watch(0xc4213005a0)
23:55:34 	/go/src/github.com/cilium/cilium/pkg/ipcache/kvstore.go:388 +0x6a8 fp=0xc421a57fd8 sp=0xc421a57c40 pc=0x1f80aa8
23:55:34 runtime.goexit()
23:55:34 	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc421a57fe0 sp=0xc421a57fd8 pc=0x1007521
23:55:34 created by github.com/cilium/cilium/pkg/ipcache.InitIPIdentityWatcher.func1
23:55:34 	/go/src/github.com/cilium/cilium/pkg/ipcache/kvstore.go:421 +0x106
23:55:34 
23:55:34 goroutine 1 [chan receive, 1 minutes]:
23:55:34 testing.(*T).Run(0xc4204685a0, 0x2a78b7c, 0x4, 0x2b6f0d0, 0x102c1d6)
23:55:34 	/usr/local/go/src/testing/testing.go:825 +0x301
23:55:34 testing.runTests.func1(0xc4204684b0)
23:55:34 	/usr/local/go/src/testing/testing.go:1063 +0x64
23:55:34 testing.tRunner(0xc4204684b0, 0xc421907d90)
23:55:34 	/usr/local/go/src/testing/testing.go:777 +0xd0
23:55:34 testing.runTests(0xc421810a20, 0x3bd4750, 0x1, 0x1, 0xfbd36d)
23:55:34 	/usr/local/go/src/testing/testing.go:1061 +0x2c4
23:55:34 testing.(*M).Run(0xc42049c680, 0x0)
23:55:34 	/usr/local/go/src/testing/testing.go:978 +0x171
23:55:34 main.main()
23:55:34 	_testmain.go:118 +0x208
...
```

Is this multiple unit tests running at once and racing to lock/unlock the mutex?

**Comment by tgraf** [comment]
Unit test failure has been tracked down to existing bug due to `globalMap` being initialized multiple times in unit tests while the identity watcher go routine was only started once and while `globalMap` was re-initialized.

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please (cfssl download timeout)
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/6989/execution/node/93/log/?consoleFull

**Comment by eloycoto** [comment]
test-me-please

**Comment by raybejjani** [comment]
I think I understand how this works for CIDRs:
- AllocateCIDRs and ReleaseCIDRs call `kvReferenceCounter.upsert/delete` and that changes the refcount.
- the ipcache kvstore watcher now checks a map in `kvReferenceCounter` and uses that to assert that the kvstore entry is still in use.

How does this work with podIPs though? `UpdatePodHostIP` calls `ipcache.IPIdentityCache.Upsert` directly, and that bypasses the refcounting, right?  It would be possible to delete a podIP by adding and removing it from a CIDR rule since the `kvReferenceCounter. marshaledIPIDPairs` check would fail and allow the delete to happen.
I don't know what the keys actually look like, so maybe I'm missing something there.

(I realise the main bug we saw was around CIDRs getting deleted, this is a more open ended question)

**Comment by tgraf** [comment]
> How does this work with podIPs though? `UpdatePodHostIP` calls `ipcache.IPIdentityCache.Upsert` directly, and that bypasses the refcounting, right?

The naming makes this a bit hard to understanding. This is unrelated to `ipcache.IPIdentityCache` entirely. All local keys are inserted into the kvstore via `globalMap` and are refcounted. When delete events are received, we check against the refcount in the `globalMap` and re-create it. This will cause a add notification to be sent again which will in turn invoke `ipcache.IPIdentityCache.Upsert` again. To make it even more resilient, the delete operation is skipped on `ipcache.IPIdentityCache` if the key is still in use locally so we avoid deleting and re-adding.

I've tested with both pod IP and CIDR IP ipcache entries.

**Comment by raybejjani** [comment]
I think I see what I've missed before this. You wanted to guard against a buggy refcount in another agent, not against the refcount logic being wrong on all the nodes. Sorry, I totally didn't get that part :/

**Comment by tgraf** [comment]
Yes, in particular for CIDR based identities, this will an agent cover for other agents as all agents will have a reference.

**Comment by jrfastab** [comment]
@tgraf to complete backport the merge conflicts were not obvious to me.

**Pull request merged**
