### PR TITLE
docker: bump cilium-iproute2 image

### PR DESCRIPTION
**Pull request by qmonnet**
Bump iproute2 image, and then cilium-runtime and cilium-builder that depend on it:

- Update iproute2 image to [f873abca8c71](quay.io/cilium/cilium-iproute2:f873abca8c7128f48206c6aecbbcdc6315d3d79d), using [latest build from image-tools](https://github.com/cilium/image-tools/runs/1688953137)
- Update cilium-runtime-dev with scripts/update-cilium-runtime-image.sh
- Build cilium-runtime [from Quay](https://quay.io/repository/cilium/cilium-runtime/build/0b08a52d-413c-4e52-953d-e49b3326652b) on top of the above changes, and update
- Build cilium-builder [from Quay](https://quay.io/repository/cilium/cilium-builder/build/05954363-4ae3-4570-8cf8-ddff9b0dec03) on top of the above changes, and update

```release-note
Expose the XFRM output mask in the bugtool archive.
```

### CODE REVIEW

**Comment by qmonnet** [comment]
Not sure how I got the cilium-runtime-dev tag wrong, I'm pretty sure I ran `./images/scripts/update-cilium-runtime-image.sh` right after updating the iproute2 image, in the same commit.

Does anyone know if I can fix this tag and simply force-push here, or if I need to rebuild the cilium-runtime and cilium-builder images on top of the change?

**Review by kkourt — APPROVED** [review]
edit: apologies, missed the above comment with the issue.

**Comment by qmonnet** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]
I validated I can observe the xfrm output mask by running:
```
$ K8S_VERSION=1.16 NETNEXT=1 ginkgo -v --focus "K8sDatapathConfig Encapsulation Check connectivity with transparent encryption and VXLAN encapsulation" -- -cilium.testScope="k8s" -cilium.provision=true -cilium.holdEnvironment=true
$ K8S_VERSION=1.16 vagrant ssh k8s1-1.16
# ks exec cilium-xxxxx -- ip xfrm s
```
LGTM! Thanks @qmonnet! :tada:

**Review by aanm — APPROVED** [review]

**Comment by qmonnet** [comment]
I'm working on backports for this PR.

**Comment by pchaigno** [comment]
> Ah, is this about exposing `ip xfrm` output to bugtool? That would be useful context to have in the commit message and/or release notes.

I've added a release note.

**Pull request merged**
