### PR TITLE
[WIP] Identify long held locks

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5064)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
Tests failed due to the following:
```
Aug 01 02:16:51 runtime cilium-agent[16632]: level=warning msg="Unable to remove proxymap entry after closing connection" error="Unable to delete element from map: %!s(<nil>)" subsys=proxy
Aug 01 02:16:53 runtime cilium-agent[16632]: POTENTIAL DEADLOCK:
Aug 01 02:16:53 runtime cilium-agent[16632]: Previous place where the lock was grabbed
Aug 01 02:16:53 runtime cilium-agent[16632]: goroutine 303333 lock 0xc422071b04
Aug 01 02:16:53 runtime cilium-agent[16632]: /home/vagrant/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:644 endpoint.(*Endpoint).regenerateBPF { e.Mutex.Lock() } <<<<<
Aug 01 02:16:53 runtime cilium-agent[16632]: /home/vagrant/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:718 endpoint.(*Endpoint).regenerate { revision, compilationExecuted, err = e.regenerateBPF(owner, tmpDir, reason) }
Aug 01 02:16:53 runtime cilium-agent[16632]: /home/vagrant/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:810 endpoint.(*Endpoint).Regenerate.func1 { err := e.regenerate(owner, reason) }
Aug 01 02:16:53 runtime cilium-agent[16632]: Have been trying to lock it again for more than 5s
Aug 01 02:16:53 runtime cilium-agent[16632]: goroutine 304051 lock 0xc422071b04
Aug 01 02:16:53 runtime cilium-agent[16632]: /home/vagrant/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1660 endpoint.(*Endpoint).HasLabels { e.Mutex.RLock() } <<<<<
Aug 01 02:16:53 runtime cilium-agent[16632]: /home/vagrant/go/src/github.com/cilium/cilium/daemon/endpoint.go:88 main.getEndpointList.func1 { if ep.HasLabels(convertedLabels) { }
```


This is the block of code which is responsible for holding the mutex for more than 5 seconds:

https://github.com/cilium/cilium/blob/b22cc7c90cc7abda785deb36378139a2fe4c3c3f/pkg/endpoint/bpf.go#L644-L663

**Comment by jrajahalme** [comment]
@rlenglet Any idea why `e.addNewRedirects()` and/or `e.removeOldRedirects()` would take more than 5 seconds? It seems to me that `e.proxyStatisticsMutex` should not be the reason?

**Comment by rlenglet** [comment]
I will look, but I think that we were doing nothing blocking in there.

**Comment by jrajahalme** [comment]
Could it be just that each change to proxy config dumps the whole LDS config to Envoy? I would think that even if there are many redirects this should still not take 5 seconds.

**Comment by rlenglet** [comment]
That would be done asynchronously and wouldn't block anything. We don't wait for an ACK at this point.

**Pull request closed without merging**
