### PR TITLE
Add gARP capability to L2 announcer feature

### PR DESCRIPTION
**Pull request by dylandreimerink**
When failover occurs a different node will start responding to ARP.
But other nodes on the network will not know this has happened and thus
keep using the ARP entry from their local cache.

This PR makes it so we broadcast a gARP reply with the new MAC
address of the IP any time we reconcile a IP+ifidx tuple that was not
yet present in the L2 responder map.

Nodes that honor gARP replies will update their ARP cache to minimize
downtime. Those who do not honer these replies will have more downtime
until their ARP cache entry expires and they perform a ARP request
themselves.

```release-note
Added gARP capability to L2 announcer feature
```

### CODE REVIEW

**Review by rolinh — APPROVED** [review]
vendor changes lgtm

**Review by ldelossa — APPROVED** [review]
LGTM.

**Review by markpash — APPROVED** [review]
LGTM

**Comment by dylandreimerink** [comment]
/test-1.26-net-next

**Pull request merged**
