### PR TITLE
[removed]

### PR DESCRIPTION
**Pull request by jrajahalme**

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.14

**Comment by jrajahalme** [comment]
/test-backport-1.14

**Comment by jrajahalme** [comment]
debugging at https://github.com/cilium/cilium/pull/35805 due to workflow missing debug logs

**Comment by jrajahalme** [comment]
/test-backport-1.14

**Comment by jrajahalme** [comment]
/test-backport-1.14

**Comment by jrajahalme** [comment]
/test-backport-1.14

**Review by nebril — APPROVED** [review]

**Pull request closed without merging**
