### PR TITLE
Add etcd-operator in the default Cilium Kubernetes descriptor

### PR DESCRIPTION
**Pull request by aanm**
Depends on https://github.com/cilium/cilium-etcd-operator/pull/14

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6332)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

The only test that failed was the known bug related with long lived connections

**Review by ianvernon — APPROVED** [review]
LGTM. The CI failure appears unrelated.

**Review by jrajahalme — APPROVED** [review]
Would be nice to have a bit more context for the change in the commit message. So with this the etcd-operator is no longer run as a separate pod, but as part of the cilium daemon set?

**Comment by aanm** [comment]
test-me-please

failed to provision node https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8346/execution/node/70/log/

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-k8s-upstream

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-k8s-upstream

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Review by tgraf — APPROVED** [review]
Awesome work!

**Pull request merged**
