### PR TITLE
[v1.12] docs: Harmonise references to Cilium Slack

### PR DESCRIPTION
**Pull request by qmonnet**
Backport:

- https://github.com/cilium/cilium/pull/27346 (@qmonnet)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 27346; do contrib/backporting/set-labels.py $pr done 1.12; done
```
or with
```
make add-labels BRANCH=v1.12 ISSUES=27346
```

### CODE REVIEW

**Comment by qmonnet** [comment]
/test-backport-1.12

**Comment by qmonnet** [comment]
/test-1.16-4.9

**Comment by qmonnet** [comment]
/test-1.16-4.9

**Comment by qmonnet** [comment]
/test-1.24-net-next

**Comment by qmonnet** [comment]
/test-1.23-4.19

**Review by youngnick — APPROVED** [review]

**Comment by qmonnet** [comment]
/test-1.16-4.9

**Comment by qmonnet** [comment]
Not sure why some jobs are marked as required but were not triggered by `/test-backport-1.12`. @youngnick do you know? Anything else I need to do here?

**Comment by youngnick** [comment]
@joestringer made some changes recently, I'll try re-triggering.

**Comment by youngnick** [comment]
/test-backport-1.12

**Comment by qmonnet** [comment]
/test-backport-1.12

**Comment by joestringer** [comment]
This required job wasn't triggered somehow:

image

I suspect it's supposed to correspond to the Conformance Kind job, but I don't see that one in the list either.

```
$ git grep "Installation and Connectivity"                                                               
.github/workflows/conformance-aks.yaml:    name: Installation and Connectivity Test
.github/workflows/conformance-aks.yaml:      job_name: "Installation and Connectivity Test"
.github/workflows/conformance-aws-cni.yaml:    name: Installation and Connectivity Test
.github/workflows/conformance-aws-cni.yaml:      job_name: "Installation and Connectivity Test"
.github/workflows/conformance-clustermesh.yaml:    name: Installation and Connectivity Test
.github/workflows/conformance-clustermesh.yaml:      job_name: "Installation and Connectivity Test"
.github/workflows/conformance-eks.yaml:    name: Installation and Connectivity Test
.github/workflows/conformance-eks.yaml:      job_name: "Installation and Connectivity Test"
.github/workflows/conformance-externalworkloads.yaml:    name: Installation and Connectivity Test
.github/workflows/conformance-externalworkloads.yaml:      job_name: "Installation and Connectivity Test"
.github/workflows/conformance-gke.yaml:    name: Installation and Connectivity Test
.github/workflows/conformance-gke.yaml:      job_name: "Installation and Connectivity Test"
.github/workflows/conformance-kind.yaml:    name: Installation and Connectivity Test
```

I suspect that we're missing a workflow run on this branch for some reason, possibly related to recent Ariane workflow changes.

**Comment by qmonnet** [comment]
@joestringer Related to https://github.com/cilium/cilium/pull/27822#issuecomment-1710810528?

This backport is only related to docs, do you think we need to block the PR on this workflow? (Agreed that the jobs not triggering is something we must fix, though)

**Comment by joestringer** [comment]
Looking at other v1.12 PRs that were opened earlier today, they don't have the same problem, so it's probably fixed overall. This particular PR is not likely to break such targets, so I think it's fine to gloss over.

**Pull request merged**
