### PR TITLE
pkg/k8s: fix heartbeat unit test

### LINKED ISSUE #10770: CI: Travis: Heartbeat should have closed all connections
## Heartbeat should have closed all connections

Failed on ARM64 Travis run:
https://travis-ci.com/github/cilium/cilium/jobs/309363923

```
=== RUN   Test
----------------------------------------------------------------------
FAIL: client_test.go:184: K8sSuite.Test_runHeartbeat
client_test.go:245:
    c.Assert(err, IsNil, Commentf("Heartbeat should have closed all connections"))
... value *errors.errorString = &errors.errorString{s:"timeout reached while waiting for condition"} ("timeout reached while waiting for condition")
... Heartbeat should have closed all connections
OOPS: 60 passed, 1 skipped, 1 FAILED
```

This is rebased against very recent master, specifically commit d933cfe08b55 ("Fix incorrect name in sysctl_linux_test.go"). PR #10766

(I didn't find it before, but I guess this is a duplicate of #10750 which was previously closed)

### PR DESCRIPTION
**Pull request by aanm**
Fix unit test logic for the heartbeat function mock. In some test cases
this function should block until the test is finished so some of those
tests were re-written to take this into account.

Signed-off-by: André Martins <andre@cilium.io>

Fixes: https://github.com/cilium/cilium/issues/10770

3rd time's a charm... 

I've ran this test locally 100 times and I didn't hit any failures with the new changes.

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
restart-ginkgo

**Comment by pchaigno** [comment]
restart-ginkgo

**Comment by aanm** [comment]
restart-ginkgo

**Comment by aanm** [comment]
restart-ginkgo

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
This is a unit test change which passes Travis and also passes one of the ginkgo runs, so I'm overriding the failed check for flakes on the other ginkgo runs.

**Pull request merged**
