### PR TITLE
test/k8s: remove l7_demos test

### PR DESCRIPTION
**Pull request by tklauser**
With https://github.com/cilium/cilium-cli/pull/962 in place in
cilium-cli v0.12.0 and the CI update to use that version in
https://github.com/cilium/cilium/pull/20617, the connectivity tests
cover all functionality tested by the tests in l7_demos.go. Moreover,
the cilium-cli connectivity tests can be run against arbitrary clusters
with Cilium deployed, while this test is specific for the test setup
based on vagrant VMs. Thus, drop this test.

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
removed manifest files are not used in other tests, so :shipit:

**Review by aanm — APPROVED** [review]

**Comment by michi-covalent** [comment]
i removed backport v1.11 label. these files don't exist in v1.11 branch.

**Comment by tklauser** [comment]
> i removed backport v1.11 label. these files don't exist in v1.11 branch.

The containing directory got renamed `k8sT` -> `k8s` in commit ffd7e57b377f982fb57cf574564b7f1debef74a4. The patch doesn't apply because the file seems to have the old path in v1.11 branch. I'll send a separate backport PR to remove it.

**Pull request merged**
