### PR TITLE
[v1.16] author backport: LRP fixes

### PR DESCRIPTION
**Pull request by ysksuzuki**
This PR is an author backport for the following LRP PRs:

- https://github.com/cilium/cilium/pull/34954 
- https://github.com/cilium/cilium/pull/35030
- https://github.com/cilium/cilium/pull/35016
- https://github.com/cilium/cilium/pull/34443
- https://github.com/cilium/cilium/pull/33721
- https://github.com/cilium/cilium/pull/33768

### CODE REVIEW

**Comment by ysksuzuki** [comment]
/test-backport-1.16

**Comment by ysksuzuki** [comment]
/test-backport-1.16

**Comment by ysksuzuki** [comment]
Tested manually with the conditions bellow. 

(We can't run local-redirect-policy test with per packet LB mode in v1.16 until this backport PR is merged. Otherwise, e2e-upgrade on main branch runs it with v1.16(downgrade test)  which doesn't include the per packet LB fix and fails. )

```
// KPR=false, socketLB=false
cilium install --wait \
    --chart-directory=$(pwd)/install/kubernetes/cilium \
    --disable-check=minimum-version \
    --helm-set=debug.enabled=true \
    --helm-set=debug.verbose=envoy \
    --helm-set=hubble.eventBufferCapacity=65535 \
    --helm-set=bpf.monitorAggregation=none \
    --helm-set=cluster.name=default \
    --helm-set=authentication.mutual.spire.enabled=false \
    --nodes-without-cilium  \
    --helm-set-string=kubeProxyReplacement=false \
    --helm-set=image.repository=localhost:5000/cilium/cilium-dev \
    --helm-set=image.useDigest=false \
    --helm-set=image.tag=local \
    --helm-set=image.pullPolicy=Never \
    --helm-set=operator.image.repository=localhost:5000/cilium/operator \
    --helm-set=operator.image.suffix= \
    --helm-set=operator.image.tag=local \
    --helm-set=operator.image.useDigest=false \
    --helm-set=operator.image.pullPolicy=Never \
    --helm-set-string=tunnelProtocol=geneve \
    --helm-set-string=endpointRoutes.enabled=true \
    --helm-set=ipv6.enabled=true \
    --helm-set=localRedirectPolicy=true 

// KPR=false, socketLB=true
cilium install --wait \
    --chart-directory=$(pwd)/install/kubernetes/cilium \
    --disable-check=minimum-version \
    --helm-set=debug.enabled=true \
    --helm-set=debug.verbose=envoy \
    --helm-set=hubble.eventBufferCapacity=65535 \
    --helm-set=bpf.monitorAggregation=none \
    --helm-set=cluster.name=default \
    --helm-set=authentication.mutual.spire.enabled=false \
    --nodes-without-cilium  \
    --helm-set-string=kubeProxyReplacement=false \
    --set='socketLB.enabled=true' \
    --helm-set=image.repository=localhost:5000/cilium/cilium-dev \
    --helm-set=image.useDigest=false \
    --helm-set=image.tag=local \
    --helm-set=image.pullPolicy=Never \
    --helm-set=operator.image.repository=localhost:5000/cilium/operator \
    --helm-set=operator.image.suffix= \
    --helm-set=operator.image.tag=local \
    --helm-set=operator.image.useDigest=false \
    --helm-set=operator.image.pullPolicy=Never \
    --helm-set-string=tunnelProtocol=geneve \
    --helm-set-string=endpointRoutes.enabled=true \
    --helm-set=ipv6.enabled=true \
    --helm-set=localRedirectPolicy=true 

# KPR=true
cilium install --wait \
    --chart-directory=$(pwd)/install/kubernetes/cilium \
    --helm-set=debug.enabled=true \
    --helm-set=debug.verbose=envoy \
    --helm-set=hubble.eventBufferCapacity=65535 \
    --helm-set=bpf.monitorAggregation=none \
    --helm-set=cluster.name=default \
    --helm-set=authentication.mutual.spire.enabled=false \
    --nodes-without-cilium \
    --helm-set-string=kubeProxyReplacement=true \
    --helm-set=image.repository=localhost:5000/cilium/cilium-dev \
    --helm-set=image.useDigest=false \
    --helm-set=image.tag=local \
    --helm-set=image.pullPolicy=Never \
    --helm-set=operator.image.repository=localhost:5000/cilium/operator \
    --helm-set=operator.image.suffix= \
    --helm-set=operator.image.tag=local \
    --helm-set=operator.image.useDigest=false \
    --helm-set=operator.image.pullPolicy=Never \
    --helm-set-string=tunnelProtocol=vxlan \
    --helm-set=devices='eth0' \
    --helm-set-string=loadBalancer.mode=snat \
    --helm-set-string=endpointRoutes.enabled=false \
    --helm-set=ipv6.enabled=true \
    --helm-set=bpf.masquerade=true \
    --helm-set=egressGateway.enabled=true \
    --helm-set=localRedirectPolicy=true \
    --helm-set=loadBalancer.acceleration=testing-only

# KPR=true, socketLB.hostNamespaceOnly=true
cilium install --wait \
    --chart-directory=$(pwd)/install/kubernetes/cilium \
    --helm-set=debug.enabled=true \
    --helm-set=debug.verbose=envoy \
    --helm-set=hubble.eventBufferCapacity=65535 \
    --helm-set=bpf.monitorAggregation=none \
    --helm-set=cluster.name=default \
    --helm-set=authentication.mutual.spire.enabled=false \
    --nodes-without-cilium \
    --helm-set-string=kubeProxyReplacement=true \
    --set='socketLB.hostNamespaceOnly=true' \
    --helm-set=image.repository=localhost:5000/cilium/cilium-dev \
    --helm-set=image.useDigest=false \
    --helm-set=image.tag=local \
    --helm-set=image.pullPolicy=Never \
    --helm-set=operator.image.repository=localhost:5000/cilium/operator \
    --helm-set=operator.image.suffix= \
    --helm-set=operator.image.tag=local \
    --helm-set=operator.image.useDigest=false \
    --helm-set=operator.image.pullPolicy=Never \
    --helm-set-string=tunnelProtocol=vxlan \
    --helm-set=devices='eth0' \
    --helm-set-string=loadBalancer.mode=snat \
    --helm-set-string=endpointRoutes.enabled=false \
    --helm-set=ipv6.enabled=true \
    --helm-set=bpf.masquerade=true \
    --helm-set=egressGateway.enabled=true \
    --helm-set=localRedirectPolicy=true \
    --helm-set=loadBalancer.acceleration=testing-only


$ ./cilium-cli/cilium connectivity test --include-unsafe-tests --test local-redirect

[=] [cilium-test-1] Test [local-redirect-policy] [95/102]
....
[=] [cilium-test-1] Test [local-redirect-policy-with-node-dns] [96/102]
...

✅ [cilium-test-1] All 2 tests (7 actions) successful, 100 tests skipped, 0 scenarios skipped.
```

**Review by brlbil — APPROVED** [review]
CI changes 👍

**Review by borkmann — APPROVED** [review]

**Pull request merged**
