### PR TITLE
fix 'egressIP' field indentation

### PR DESCRIPTION
**Pull request by yulng**
Fix 'egressIP' field indentation

@joestringer

### CODE REVIEW

**Comment by yulng** [comment]
> Fix 'egressIP' field indentation Signed-off-by: yulng [wei.yang@daocloud.io](mailto:wei.yang@daocloud.io)
> 
> @joestringer

@joestringer  :)

**Review by joestringer — APPROVED** [review]
Change looks good, thanks.

In future, please format your commit messages using `git commit -s` for the signoff and ensure that there is an empty line after the first (title) line of the commit and before the sign-off lines. Signing off with `-s` will also ensure that the signoff line is properly formatted.

For this PR, I fixed this up directly.

**Comment by joestringer** [comment]
Ah correction, I was not able to fix it up.

Please format the commit message like this:

```
Fix 'egressIP' field indentation                                                                                                                                                                            
                                                                                                                                                                                                            
Signed-off-by: yulng <wei.yang@daocloud.io>
```

You can do this with `git commit --amend`.

**Review by joestringer — CHANGES_REQUESTED** [review]
See above.

**Comment by yulng** [comment]
> Ah correction, I was not able to fix it up.
> 
> Please format the commit message like this:
> 
> ```
> Fix 'egressIP' field indentation                                                                                                                                                                            
>                                                                                                                                                                                                             
> Signed-off-by: yulng <wei.yang@daocloud.io>
> ```
> 
> You can do this with `git commit --amend`.

I push it again by "git commit -s"
thanks😄😄

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
LGTM, thanks!

**Pull request merged**
