### PR TITLE
[v1.7] vendor: update github.com/cilium/ebpf

### PR DESCRIPTION
**Pull request by gandro**
Due to the `__NR_CPUS__` bugfixes backported in #12363, the cilium monitor reader is now trying to access the perf event ring buffer for offline CPUs. This causes crashes with older versions of `cilium/ebpf` in Cilium 1.7.6. Thus we need to bump `cilium/ebpf`, as the newer version contains the patches which deal with offline CPUs.

This fixes a regression introduced in 1.7.6 where Hubble and `cilium monitor` crash the agent on machines with offline CPUs.

 * #12068 -- vendor: update github.com/cilium/ebpf (@tklauser )

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12068; do contrib/backporting/set-labels.py $pr done 1.7; done
```

/cc @pchaigno @kAworu @Rolinh

### CODE REVIEW

**Comment by gandro** [comment]
test-backport-1.7

**Review by rolinh — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by tklauser** [comment]
I think you forgot to `git add vendor/golang.org/x/xerrors`, see the Travis CI build failure: https://travis-ci.com/github/cilium/cilium/builds/174807922

Otherwise LGTM.

**Comment by kAworu** [comment]
I hit that bug when trying to deploy Hubble v0.5 with Cilium v1.7.6 on my machine which report a higher possible cpu count than online cpu count:

```
% cat /sys/devices/system/cpu/possible
0-15
% cat /sys/devices/system/cpu/online
0-7
% cat /sys/devices/system/cpu/present
0-7
% cat /sys/devices/system/cpu/offline
8-15
% nproc --all
8
```

**Review by kaworu — APPROVED** [review]
This PR fixed the issue

**Comment by gandro** [comment]
> I think you forgot to `git add vendor/golang.org/x/xerrors`, see the Travis CI build failure: https://travis-ci.com/github/cilium/cilium/builds/174807922
> 
> Otherwise LGTM.

Thanks! I was indeed not realizing this and was wondering what went wrong with `go mod` when in fact it was just me :facepalm: 
Should be fixed now.

**Comment by gandro** [comment]
test-backport-1.7

**Comment by gandro** [comment]
runtime tests failure seems unrelated

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19806/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/

**Comment by gandro** [comment]
restart-ginkgo

**Comment by gandro** [comment]
test-me-please

**Comment by gandro** [comment]
test-backport-1.7

**Comment by tklauser** [comment]
> runtime tests failure seems unrelated
> 
> https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19806/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/

This looks similar to #11512. I think I remember @pchaigno mentioning something similar while ago. We might need to increase the timeout for the privileged runtime tests yet again.

**Comment by pchaigno** [comment]
> > runtime tests failure seems unrelated
> > https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19806/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/
> 
> This looks similar to #11512. I think I remember @pchaigno mentioning something similar on master a while ago. We might need to increase the timeout for the privileged runtime tests yet again.

This one doesn't look like a timeout. There's this bit of info. in the logs:
```
	 START: routing_test.go:71: LinuxRoutingSuite.TestDelete
	 valid IP addr matching rules
	 Inside new network ns NS(3:4026532381)
	 Added dummy device
	 routing_test.go:130:
	     runFuncInNetNS(c, func() {
	         ip := tt.preRun()
	         err := Delete(ip)
	         c.Assert((err != nil), Equals, tt.wantErr)
	     }, masterMAC)
	 routing_test.go:178:
	     c.Assert(err, IsNil)
	 ... value *errors.errorString = &errors.errorString{s:"unable to find ifindex for interface MAC: interface with MAC 00:11:22:33:44:55 not found"} ("unable to find ifindex for interface MAC: interface with MAC 00:11:22:33:44:55 not found")
	 
	 routing_test.go:130:
	     runFuncInNetNS(c, func() {
	         ip := tt.preRun()
	         err := Delete(ip)
	         c.Assert((err != nil), Equals, tt.wantErr)
	     }, masterMAC)
	 routing_test.go:226:
	     c.Assert(netlink.LinkDel(dummy), IsNil)
	 ... value syscall.Errno = 0x16 ("invalid argument")
	 
	 Closed new network ns NS(3:4026532381)
	 FAIL: routing_test.go:71: LinuxRoutingSuite.TestDelete
```
I couldn't find an existing flake report for that error.

**Review by aanm — APPROVED** [review]

**Review by brb — APPROVED** [review]

**Comment by brb** [comment]
> This one doesn't look like a timeout. There's this bit of info. in the logs:

@pchaigno It could be that we [not safely change the network namespaces](https://www.weave.works/blog/linux-namespaces-and-go-don-t-mix) in Go.

**Comment by pchaigno** [comment]
@brb Yes, #11620 fixes it and is now marked for backport into 1.7.

**Pull request merged**
