### PR TITLE
bpf: Add socket policy wildcard support

### PR DESCRIPTION
**Pull request by joestringer**
This case is generated by userspace to indicate that all traffic is
allowed in the given direction. Check it in the fallthrough case.
This makes socket policy follow the regular packet policy logic.

Do we need to backport this?

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9317)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
Doesn't this fix an open GH issue? I had the feeling there was a GH WRT...

**Review by jrfastab — APPROVED** [review]

**Comment by joestringer** [comment]
Will skip backport since sockops is not yet a stable feature in current (eg v1.6) releases.

**Comment by ianvernon** [comment]
Superseded by #9335

**Pull request closed without merging**
