### PR TITLE
Backport/v1.0 2018 04 19

### PR DESCRIPTION
**Pull request by raybejjani**
doc: Replace cilium-sidecar.yaml with a config map setting
[ upstream commit 95d04e633f2e97244c5bc78c4fa0c6052466971d ]

doc: Fix spelling
[ upstream commit e89d35c2a21319b3f5ec2e19405aa6646652b1c4 ]

Kafka : remove noise from logging EOF messages in Kafka parser We keep seeing a lot of these on normal client (produce/consume) connection close. We should not be logging valid
[ upstream commit d9143000325e61a9ed63817b453f7cffbf76de89 ]

Fixes: #3693 #3792

### CODE REVIEW

**Comment by raybejjani** [comment]
cc @aanm

**Comment by raybejjani** [comment]
I didn't backport doc changes from https://github.com/cilium/cilium/pull/3702 that were based on 1.0 docs that haven't been merged. We can skip commit ffb31f5a5ff977d72be5fe019e762432cb2ba7ac if we don't want a partial apply (I left the spellcheck words file)

**Comment by aanm** [comment]
@raybejjani what's the best option to not forget commit `ffb31f5`?

**Review by aanm — APPROVED** [review]

**Comment by raybejjani** [comment]
@aanm I commented on that PR, and it still has the backport-needed label. It also has the 1.0-docs label so it will show up during that search as well. Nonetheless, the best option is that I will keep checking backports until it's merged :(

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
