### PR TITLE
v1.14 Backports 2024-07-02

### PR DESCRIPTION
**Pull request by pippolo84**
* [x] #33382 (@gandro)
 * [x] #33427 (@marseel) :warning: resolved conflicts
 * [x] #33448 (@jrajahalme) :warning: resolved conflicts
 * [x] #33442 (@aditighag) :warning: resolved conflicts
 * [x] #33444 (@brb)
 * [x] #33514 (@aanm)
 * [x] #33420 (@gandro) :warning: resolved conflicts

PRs skipped due to conflicts:

 * #33403 (@sayboras) :x: Dropped because there is no `pkg/ciliumenvoyconfig/envoy_l7lb_backend_syncer.go` in v1.15
 * #33421 (@brb) :x: Dropped because I was unable to adapt the test to v1.14 (e.g: missing `lib/ipcache.h` header)
 
Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33382 33427 33448 33442 33444 33514 33420
```

### CODE REVIEW

**Review by gandro — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]

**Review by brb — APPROVED** [review]
The non-dropped PR :+1: Thanks!

**Review by marseel — APPROVED** [review]

**Comment by sayboras** [comment]
> https://github.com/cilium/cilium/pull/33403 (@sayboras) ❌ Dropped because there is no pkg/ciliumenvoyconfig/envoy_l7lb_backend_syncer.go in v1.15

Noted  and thanks, I have adjusted the patch in https://github.com/cilium/cilium/pull/33534

**Review by nebril — APPROVED** [review]

**Comment by pippolo84** [comment]
Force-pushed to solve conflict in `install/kubernetes/Makefile.values` with v1.14 target branch

**Comment by pippolo84** [comment]
/test-backport-1.14

**Comment by pippolo84** [comment]
Smoke Test failure will be fixed by https://github.com/cilium/cilium/pull/33579

**Comment by pippolo84** [comment]
Force-pushed to include https://github.com/cilium/cilium/pull/33579

**Comment by pippolo84** [comment]
/test-backport-1.14

**Review by jrajahalme — APPROVED** [review]

**Review by ysksuzuki — APPROVED** [review]
LGTM for the LRP changes

Note:
- e962bcc803127dc200a276427b2ece6ff01e2ef8 removed the stale comments for the logic revised in  ad09e20df402127cd88fa7293c560a107ccd816c which v1.14 doesn't include. So no need to backport it on v1.14.
- 56c6ca335413be3ea82d169744d4859197a928b1 modifies the v1.16 upgrade notes. So no need to backport it on v1.14.

**Pull request merged**
