### PR TITLE
install/kubernetes: Add CAP_IPC_LOCK for mmap

### LINKED ISSUE #19808: Crashloop for Cilium v1.12-rc2 and Centos 8
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi!
I'm trying to use v1.12-rc2 with CentOS 8 (in the steps below, ks is an alias for `kubectl -n kube-system `)
I had 1.11.4 before and upgraded to this version with
``` 
$ helm upgrade cilium cilium/cilium -n kube-system --version 1.12.0-rc2 --reset-values
```
I used --reset-values to make sure my old values wasn't causing the trouble (played around with bgp in 1.11.4)

The operator deployment is stable.
```
$ ks get pods
NAME                              READY   STATUS              RESTARTS   AGE
cilium-operator-5868c8cbd-5pntg   1/1     Running             0          70s
cilium-operator-5868c8cbd-8t4zp   1/1     Running             0          70s
```
And the logs from the operator tells me everything seems fine:
```
$ ks logs deploy/cilium-operator | grep -v 'level=info' | wc -l
Found 2 pods, using pod/cilium-operator-5868c8cbd-5pntg
0
```
The cilium daemonSet is crashlooping:
```
$ ks get pods -l k8s-app=cilium
NAME           READY   STATUS             RESTARTS   AGE
cilium-r8w7z   0/1     CrashLoopBackOff   9          22m
cilium-rzxx8   0/1     CrashLoopBackOff   9          22m

$ ks logs -p cilium-r8w7z | grep -v level=info
level=fatal msg="Cannot initialise BPF perf ring buffer sockets" error="failed to create perf ring for CPU 0: can't mmap: operation not permitted" startTime="2022-05-12 21:57:54.463823399 +0000 UTC m=+3.211794063" subsys=monitor-agent
```
I'm running kubernetes 1.21.11 on CentOS steam 8

```
$ k get nodes -o wide
NAME                          STATUS   ROLES    AGE     VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE          KERNEL-VERSION          CONTAINER-RUNTIME
k8s01-worker01.k8s01.k8s.se   Ready    <none>   7d23h   v1.21.11   172.31.5.161   <none>        CentOS Stream 8   4.18.0-383.el8.x86_64   containerd://1.4.4
k8s01-worker02.k8s01.k8s.se   Ready    <none>   7d23h   v1.21.11   172.31.5.162   <none>        CentOS Stream 8   4.18.0-383.el8.x86_64   containerd://1.4.4
```
And the running image is:
```
$ ks describe pod cilium-operator-5868c8cbd-5pntg | grep 'Image: ' 
    Image:         quay.io/cilium/operator-generic:v1.12.0-rc2
$ ks describe pod cilium-r8w7z | grep 'Image: '  | uniq
    Image:         quay.io/cilium/cilium:v1.12.0-rc2
```

### Cilium Version

v1.12.0-rc2

### Kernel Version

4.18.0-383.el8.x86_64

### Kubernetes Version

1.21.11

### Sysdump

[cilium-sysdump-20220513-001017.zip](https://github.com/cilium/cilium/files/8682842/cilium-sysdump-20220513-001017.zip)

### Relevant log output

```shell
level=fatal msg="Cannot initialise BPF perf ring buffer sockets" error="failed to create perf ring for CPU 0: can't mmap: operation not permitted" startTime="2022-05-12 22:08:15.518205973 +0000 UTC m=+3.270311059" subsys=monitor-agent
```

### Anything else?

I'm having the controlplane for kubernetes in another cluster namespace.
This is a test/lab cluster so there is no problem to tear it down, use a elrepo kernel and things like that.
The worker nodes are VM's on oVirt (kvm), but I don't think I have set any special options since cilium works with previous versions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sayboras**
### Description

This commit is to add IPC_LOCK cap for cilium agent, as mmap is triggered as
part of monitor-agent.

```
level=fatal msg="Cannot initialise BPF perf ring buffer sockets" error="failed to create perf ring for CPU 0: can't mmap: operation not permitted" startTime="2022-05-12 21:57:54.463823399 +0000 UTC m=+3.211794063" subsys=monitor-agent
```

Related docs:
https://man7.org/linux/man-pages/man7/capabilities.7.html

Relates 28bffa6d4b11936f9c2dc94a68dec0ecd4d3f745
Fixes #19808

Signed-off-by: Tam Mach <tam.mach@cilium.io>

### Testing

I was able to simulate the issue locally with normal `cilium install --version v1.12.0-rc2`, and then just test it out by modify cilium daemonset directly.

<details>
<summary>Before</summary>

```
$ ksysgpo
NAME                               READY   STATUS             RESTARTS      AGE
cilium-operator-688b75db67-28tj4   1/1     Running            0             38m
cilium-t72pb                       0/1     CrashLoopBackOff   4 (52s ago)   2m40s

$ ksysg daemonsets.apps cilium -o json | jq '.spec.template.spec.containers[0].securityContext'
{
  "capabilities": {
    "add": [
      "KILL",
      "NET_ADMIN",
      "SYS_MODULE",
      "SYS_ADMIN",
      "SYS_RESOURCE"
    ]
  }
}

$ ksyslo ds/cilium | grep "level=fatal"
level=fatal msg="Cannot initialise BPF perf ring buffer sockets" error="failed to create perf ring for CPU 30: can't mmap: operation not permitted" startTime="2022-05-13 12:07:42.393208179 +0000 UTC m=+2.609485545" subsys=monitor-agent

```

</details>

<details>
<summary>After</summary>

```
$ ksysg daemonsets.apps cilium -o json | jq '.spec.template.spec.containers[0].securityContext'
{
  "capabilities": {
    "add": [
      "KILL",
      "NET_ADMIN",
      "IPC_LOCK",
      "SYS_MODULE",
      "SYS_ADMIN",
      "SYS_RESOURCE"
    ]
  }
}

$ kgpo -A
NAMESPACE     NAME                               READY   STATUS    RESTARTS      AGE
kube-system   cilium-9fl7v                       1/1     Running   0             18s
kube-system   cilium-operator-688b75db67-28tj4   1/1     Running   0             42m
kube-system   coredns-64897985d-vbtzt            1/1     Running   0             43m
kube-system   etcd-minikube                      1/1     Running   0             43m
kube-system   kube-apiserver-minikube            1/1     Running   0             43m
kube-system   kube-controller-manager-minikube   1/1     Running   0             43m
kube-system   kube-proxy-pns5t                   1/1     Running   0             43m
kube-system   kube-scheduler-minikube            1/1     Running   0             43m
kube-system   storage-provisioner                1/1     Running   1 (42m ago)   43m

$ cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         OK
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
DaemonSet         cilium             Desired: 1, Ready: 1/1, Available: 1/1
Containers:       cilium             Running: 1
                  cilium-operator    Running: 1
Cluster Pods:     1/1 managed by Cilium
Image versions    cilium             quay.io/cilium/cilium:v1.12.0-rc2: 1
                  cilium-operator    quay.io/cilium/operator-generic:v1.12.0-rc2: 1
```

</details>

### CODE REVIEW

**Review by joestringer — APPROVED** [review]
I tried this out, and it solved the issue for me.

Fixes: https://github.com/cilium/cilium/pull/14446 (only in master, targeted for v1.12 release)

**Comment by joestringer** [comment]
I renamed the PR since the standard name for the capability from capabilities(7) is `CAP_IPC_LOCK`.

**Review by christarazi — APPROVED** [review]

**Review by gandro — APPROVED** [review]
Good catch!

**Comment by sayboras** [comment]
/test-1.16-4.9

**Comment by sayboras** [comment]
/test-1.21-5.4

**Comment by sayboras** [comment]
/test-1.22-4.19

**Comment by sayboras** [comment]
/test-1.23-net-next

**Comment by sayboras** [comment]
/test-1.22-4.19

**Comment by sayboras** [comment]
re-run failed test as we were having environment issue with jenkins.

**Pull request merged**
