### PR TITLE
v1.11 backports 2022-06-08

### PR DESCRIPTION
**Pull request by joamaki**
* #18667 -- Ensure priority scheduling (@sdake)
 * #19809 -- Add counter to track all datapath timeouts due to FQDN IP updates (@ungureanuvladvictor)
 * #19857 -- Expose metrics for active FQDN connections per endpoint (@christarazi)
 * #19955 -- cmd: Allow more complicated patterns in map string type. (@sayboras)
 * #19875 -- pkg/fqdn: Replace remaining usages of regex compile with LRU (@christarazi)
 * #19565 -- ui: v0.9.0 images and drop envoy proxy container (@geakstr)
 * #19987 -- metrics: Fix NaN value for cilium metrics list CLI (@sayboras)
 * #19933 -- helm: use port 80/443 by default for the peer service (@rolinh)
 * #20047 -- docs: add kube-apiserver to the special identity list (@kaworu)
 * #19843 -- Optimize CIDR label functions (@christarazi)
 * #19925 -- pkg/fqdn: Fix missing delete for forward map (@christarazi)
 * #19959 -- clustermesh: Add ownerReferences for CiliumNodes (@sayboras)
 * #19999 -- Add type label to the identity metric (@ungureanuvladvictor)
 * #19968 -- cli: Use custom named map instead of StringToStringVar (@sayboras)
 * #20011 -- bugtool: Add structured node and health output (@gandro)
 * #19998 -- ctmap,daemon: Exclude host IPs from conntrack GC (@pchaigno)
 * #19923 -- ipam: Fix inconsistent update of CiliumNodes (@pchaigno)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18667 19809 19857 19955 19875 19565 19987 19933 20047 19843 19925 19959 19999 19968 20011 19998 19923; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
$ make add-label BRANCH=v1.11 ISSUES=18667,19809,19857,19955,19875,19565,19987,19933,20047,19843,19925,19959,19999,19968,20011,19998,19923
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Looks good for my commit, also I have checked this one https://github.com/cilium/cilium/pull/20111/commits/f0c54cfcb1fa8cd0fa0870cd983d1b8fbeb00a2d as well.

Thanks :100:

**Review by gandro — APPROVED** [review]
My commits looks good, thanks!

**Review by rolinh — APPROVED** [review]

**Review by kaworu — APPROVED** [review]
My patch looks good, thanks!

**Comment by joamaki** [comment]
/test-backport-1.11

**Review by geakstr — APPROVED** [review]
Thanks, my commit looks good!

**Review by ungureanuvladvictor — APPROVED** [review]
My commits look good, thanks for handling this!

**Review by christarazi — APPROVED** [review]
:+1:

**Review by nebril — APPROVED** [review]

**Comment by nebril** [comment]
/ci-aks-1.11

**Comment by nebril** [comment]
Looks like GKE nodes got preemted, retrying

**Review by pchaigno — COMMENTED** [review]
My PRs look good. Thanks!

**Pull request merged**
