### PR TITLE
make: Ensure that checker.DeepEquals is used everywhere

### PR DESCRIPTION
**Pull request by vadorovsky**
Cilium defines its own DeepEquals checker in pkg/checker which gives a
more detailed trace than DeepEquals checker from gopkg.in/check.v1.

Signed-off-by: Michal Rostecki <mrostecki@suse.de>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6452)

### CODE REVIEW

**Comment by vadorovsky** [comment]
test-me-please

**Comment by vadorovsky** [comment]
test-me-please

**Comment by vadorovsky** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]
LGTM

**Review by tgraf — APPROVED** [review]
Great work!

**Pull request merged**
