### PR TITLE
Pr/v1.11 backport 2022 11 30

### PR DESCRIPTION
**Pull request by tommyp1ckles**
* #22361 -- fqdn: dnsproxy: fix forwardng of the original security identity (@aspsk)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 22361; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Comment by tommyp1ckles** [comment]
/test-backport-1.11

**Comment by tommyp1ckles** [comment]
/test-backport-1.11

**Comment by tommyp1ckles** [comment]
/test-1.20-4.9

**Comment by tommyp1ckles** [comment]
/test-1.20-4.9

**Comment by tommyp1ckles** [comment]
/test-backport-1.11

**Comment by tommyp1ckles** [comment]
/test-backport-1.11

**Comment by joestringer** [comment]
It looks like this PR was also impacted by the issue that was recently fixed in https://github.com/cilium/cilium/pull/22724 . All other tests are passing and the other backports for this are in. I'll make an exception to CI failures and merge this to ensure that the fix lands in all trees in the upcoming patch release.

**Pull request merged**
