### PR TITLE
Update USERS.md

### PR DESCRIPTION
**Pull request by hrittikhere**
Signed-off-by: Hrittik Roy <fp@ayedo.de>

### CODE REVIEW

**Comment by hrittikhere** [comment]
Signed-off-by: Hrittik Roy [fp@ayedo.de](mailto:fp@ayedo.de)[](https://github.com/hrittikhere)

**Comment by nebril** [comment]
Hi @hrittikhere , thanks for your PR! Can you add the `Signed-off-by` line to the end of your commit msg as per https://docs.cilium.io/en/v1.11/contributing/development/contributing_guide/#dev-coo ?

Thanks!

**Comment by nebril** [comment]
hey @hrittikhere I see that you closed the PR (which is definitely within your rights). If you want pursue this change, let me know, I can try to help you getting it merged.

**Comment by hrittikhere** [comment]
hey @nebril I will make one PR tomorrow :) Didn't save the previous env and was confused about how to replicate the msg. Thanks ☺️

**Pull request closed without merging**
