### PR TITLE
v1.5 backports 2019-06-05

### PR DESCRIPTION
**Pull request by borkmann**
PRs:

- #7710 
- #8197
- #8002
- #8194 
- #8130 
- #8214 
- #8217 
- #8223

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8215)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-missed-k8s

**Comment by borkmann** [comment]
test-upstream-k8s

**Comment by borkmann** [comment]
test-docs-please

**Review by tgraf — APPROVED** [review]

**Comment by ianvernon** [comment]
Build got stuck: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2167/ #7796

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by borkmann** [comment]
Same issue, stuck again in the CI:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2168/
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2168/
```
[...]
20:49:34  Ran 44 of 369 Specs in 1790.763 seconds
20:49:34  SUCCESS! -- 44 Passed | 0 Failed | 0 Pending | 325 Skipped
20:49:34  PASS
20:49:34  
20:49:34  Ginkgo ran 1 suite in 30m9.749359989s
20:49:34  Test Suite Passed
Post stage
[Pipeline] sh
20:49:35  + cd /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.15-gopath/src/github.com/cilium/cilium/test
20:49:35  + ./post_build_agent.sh
20:49:35  output of following commands are ran on the Jenkins agent itself
20:49:35  output of: "ps -ef | grep -i vbox" 
20:49:35  root      4129     1  0 19:22 ?        00:00:07 /usr/lib/virtualbox/VBoxXPCOMIPCD
20:49:35  root     11924 11921  0 20:49 ?        00:00:00 grep -i vbox
20:49:35  root     12785     2  0 07:23 ?        00:00:00 [iprt-VBoxWQueue]
20:49:35  root     12790     2  0 07:23 ?        00:00:00 [iprt-VBoxTscThr]
20:49:35  root     22663     1  0 20:11 ?        00:00:07 /usr/lib/virtualbox/VBoxSVC --auto-shutdown
20:49:35  root     23888 22663  0 20:11 ?        00:00:00 /usr/lib/virtualbox/VBoxNetDHCP --comment HostInterfaceNetworking-vboxnet0 --config /tmp/dhcp-config-ldxvv.xml
20:49:35  root     24418 22663 61 20:11 ?        00:23:35 /usr/lib/virtualbox/VBoxHeadless --comment test_k8s1-113_1559765474350_2913 --startvm 64a0fea4-1b2c-4a96-9285-61fcd2f10cb9 --vrde config
20:49:35  root     29813 22663 24 20:18 ?        00:07:31 /usr/lib/virtualbox/VBoxHeadless --comment test_k8s2-113_1559765901978_22449 --startvm 1fefc655-4bab-4e1c-b5be-f794a5df286b --vrde config
20:49:35  output of: "ps -ef | grep -i vagrant" 
20:49:35  root     11926 11921  0 20:49 ?        00:00:00 grep -i vagrant
20:49:35  output of: "VBoxManage list runningvms" 
20:49:35  "test_k8s1-113_1559765474350_2913" {64a0fea4-1b2c-4a96-9285-61fcd2f10cb9}
20:49:35  "test_k8s2-113_1559765901978_22449" {1fefc655-4bab-4e1c-b5be-f794a5df286b}
20:49:35  output of: "VBoxManage list intnets" 
20:49:35  Name:        cilium-k8s2168-Cilium-PR-Ginkgo-Tests-K8s-1.13
20:49:35  Name:        intnet
[Pipeline] sh
20:49:36  + cd /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.15-gopath/src/github.com/cilium/cilium/test
20:49:36  + ./archive_test_results.sh
20:49:36  ./archive_test_results.sh: line 3: cd: /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/test: No such file or directory
[Pipeline] sh
20:49:38  + cd /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.15-gopath/src/github.com/cilium/cilium/test/..
20:49:38  + mv test_results_Cilium-PR-Ginkgo-Tests-K8s_2168_BDD-Test-k8s-1.15.zip /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s
[Pipeline] sh
20:49:39  + cd /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.15-gopath/src/github.com/cilium/cilium/test
20:49:39  + mv k8s-1.11.xml k8s-1.12.xml k8s-1.15.xml /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test
[Pipeline] sh
20:49:40  + cd /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.15-gopath/src/github.com/cilium/cilium/test
20:49:40  + vagrant destroy -f
20:49:41  ==> k8s2-1.14: VM not created. Moving on...
20:49:41  ==> k8s1-1.14: VM not created. Moving on...
20:49:41  ==> runtime: VM not created. Moving on...
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
```

**Comment by borkmann** [comment]
test-missed-k8s

**Comment by borkmann** [comment]
Same here.

**Comment by borkmann** [comment]
test-missed-k8s

**Comment by borkmann** [comment]
test-missed-k8s

**Comment by borkmann** [comment]
test-docs-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
Direct route test failed again: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2172/flowGraphTable/

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
Only `00:52:36.557  [Fail] K8sFQDNTest [It] Restart Cilium validate that FQDN is still working` failed

**Pull request merged**
