### PR TITLE
CI: migrate 20-identity-list.sh to Ginkgo, mark corresponding tests as validated

### PR DESCRIPTION
**Pull request by ianvernon**
Signed-off by: Ian Vernon <ian@cilium.io>

Related-to: #1841 

Fixes: #2532

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]
LGTM thanks

**Pull request merged**
