### PR TITLE
vendor: bump etcd to v3.5.0 and grpc to v1.39.0

### PR DESCRIPTION
**Pull request by rolinh**
Our version of grpc has been lagging behind for a while now because of the issue described [in this comment](https://github.com/cilium/cilium/pull/13405#issuecomment-704766707). The etcd project has just released a version (albeit still marked ~alpha~ beta at the moment) that fixes this issue and thus allows bumping grpc to a more recent version. The Hubble team has been desperately wanting to bump the grpc dependency for a while now mostly to be able to provide more useful error messages.

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by rolinh** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
The Travis CI failure looks real, it's failing in `pkg/kvstore.AllocatorEtcdSuite`: https://travis-ci.com/github/cilium/cilium/jobs/514936128

**Comment by tklauser** [comment]
test-runtime

**Comment by rolinh** [comment]
> The Travis CI failure looks real, it's failing in `pkg/kvstore.AllocatorEtcdSuite`: https://travis-ci.com/github/cilium/cilium/jobs/514936128

A bug in the unit tests apparently. It should be fixed with #16596. Marking this PR as blocked until this other PR is merged and this one rebased.

**Comment by rolinh** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Comment by rolinh** [comment]
test-me-please

**Comment by rolinh** [comment]
test-me-please

**Pull request merged**
