### PR TITLE
api: Upgrade go-swagger version to v0.30.5

### PR DESCRIPTION
**Pull request by sayboras**
Also to add the renovate configuration for auto update version later. Just a note we might still need to run `make generate-api` manually till the work with self-hosted renovate with post-hook is done.

https://github.com/cilium/cilium/pull/30185

### CODE REVIEW

**Review by jibi — APPROVED** [review]

**Review by pippolo84 — APPROVED** [review]
Thanks! :100:

**Review by learnitall — CHANGES_REQUESTED** [review]
Sweet thank you! Would you mind adding a quick comment in the `Makefile.defs` about needing to run `make generate-api` when the version is updated by renovate? It might help folks who are reviewing renovate PRs.

**Review by learnitall — APPROVED** [review]
Thank you!

**Pull request merged**
