### PR TITLE
NodePort health checks should be disabled when kube-proxy is installed

### PR DESCRIPTION
**Pull request by pchaigno**
See commit descriptions.

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Review by brb — APPROVED** [review]
Thanks, LGTM!

Asking @gandro to review it as well, as he might have more context for this feature.

**Review by gandro — APPROVED** [review]
Looks good! At first I was a bit confused, since the flag shouldn't do anything if KPR is turned off, but looks like in that test we have both KPR and KP enabled.

Edit: I guess I could have also read the commit messages. Thanks!

**Review by nbusseneau — APPROVED** [review]
LGTM, thanks for the context in commit message.

**Comment by pchaigno** [comment]
ConformanceAKS is failing with known flake https://github.com/cilium/cilium/issues/16292, k8s-1.19-kernel-5.4 with https://github.com/cilium/cilium/issues/15455. Reviews are in. Marking as ready to merge.

**Pull request merged**
