### PR TITLE
Improve separation between cilium-agent and cli

### PR DESCRIPTION
**Pull request by brb**
This PR contains multiple changes to improve separation between `cilium-agent` and `cilium`:

1. Fix `cilium-agent` detection routine.
2. Do not call the CLI initialization function when running as `cilium-agent`.
3. Set `$HOME` as a dir for the default `ciliumd.yaml` config.

Please review each commit separately.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7912)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Comment by brb** [comment]
Hit the well known VM image issue.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Pull request merged**
