### PR TITLE
run bpf_ct_tests as part of CI

### PR DESCRIPTION
**Pull request by kkourt**
Run BPF_PROG_TEST_RUN tests as a GH action.

### CODE REVIEW

**Comment by kkourt** [comment]
test-focus runtime

**Comment by kkourt** [comment]
test-me-please, retest-runtime

**Comment by kkourt** [comment]
test-focus Runtime

**Comment by kkourt** [comment]
retest-runtime

**Comment by kkourt** [comment]
retest-runtime

**Comment by kkourt** [comment]
Since this patch only touches a github action file, no reason to run the other CI tests.

**Review by aanm — APPROVED** [review]

**Pull request merged**
