### PR TITLE
Backport #11830 into 1.7

### PR DESCRIPTION
**Pull request by nebril**

### CODE REVIEW

**Comment by nebril** [comment]
test-ginkgo

**Comment by nebril** [comment]
restart-ginkgo

**Comment by nebril** [comment]
test-focus K8sDatapathConfig

**Comment by joestringer** [comment]
@nebril is it important to follow up on this and do you intend to do so? Otherwise I'd be inclined to just close this.

**Comment by errordeveloper** [comment]
@nebril ping!

**Comment by joestringer** [comment]
Closing, feel free to rebase & reopen if you feel that this is important to fix up in the 1.7 branch.

**Pull request closed without merging**
