### PR TITLE
v1.15 Backports 2024-05-13

### PR DESCRIPTION
**Pull request by jibi**
* [x] #31424 (@learnitall)
 * [x] #32117 (@giorio94)
 * [x] #32278 (@joestringer)
 * [x] #32402 (@michi-covalent)
 * [x] #32462 (@brlbil)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31424 32117 32278 32402 32462
```

### CODE REVIEW

**Comment by jibi** [comment]
/test-backport-1.15

**Review by giorio94 — APPROVED** [review]
My commits look good, thanks!

**Review by michi-covalent — APPROVED** [review]
thank you!

**Review by brlbil — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Review by learnitall — APPROVED** [review]
Thanks!

**Review by joestringer — APPROVED** [review]
Approve for backport of my PR. Thanks!

**Pull request merged**
