### PR TITLE
doc: Use Hubble version specified in stable.txt

### PR DESCRIPTION
**Pull request by michi-covalent**
Ref: https://github.com/cilium/hubble/issues/298

Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Comment by michi-covalent** [comment]
@Rolinh i'm not sure how to do this on windows...

**Comment by gandro** [comment]
Looks like the `kubectl` docs also didn't solve this. I don't have access to a Windows machine, but on `wine`, I can do the following in `cmd.exe`:

```
set /p HUBBLE_VERSION=<stable.txt
curl -LO "https://github.com/cilium/hubble/releases/download/%HUBBLE_VERSION%/hubble-linux-amd64.tar.gz"
```

**Comment by Rolinh** [comment]
@michi-covalent I'm not a Windows guy :)
However, I did get access to a Windows machine and can confirm that the instructions provided by @gandro do work just fine.
Let's add them!

**Comment by michi-covalent** [comment]
thanks @Rolinh i also created a windows vm. testing it now

**Comment by michi-covalent** [comment]
Screen Shot 2020-06-18 at 2 33 50 PM

**Review by rolinh — APPROVED** [review]

**Pull request merged**
