### PR TITLE
bpf: Use ENABLE_L7_LB in complexity test

### PR DESCRIPTION
**Pull request by jrajahalme**
Add -DENABLE_L7_LB=1 to MAX_BASE_OPTIONS to pull that code in for load testing.

Fixes: #18894
Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>

### CODE REVIEW

**Review by ti-mo — APPROVED** [review]

**Comment by jrajahalme** [comment]
Rebased.

**Comment by jrajahalme** [comment]
Rebased.

**Review by pchaigno — CHANGES_REQUESTED** [review]
You will need to change files under bpf/complexity-tests/. The Makefile options are only used as the default options for compilation, not as the options for complexity tests.

**Comment by borkmann** [comment]
> You will need to change files under bpf/complexity-tests/. The Makefile options are only used as the default options for compilation, not as the options for complexity tests.

ping @jrajahalme

**Pull request closed without merging**
