### PR TITLE
Script fixes

### PR DESCRIPTION
**Pull request by jrajahalme**

### CODE REVIEW

**Comment by jrajahalme** [comment]
The third commit that re-enables running the go tests causes a build failure due to a failing unit test:

Excerpt from https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-715/1/console:

==> cilium-master: go tool cover -html=coverage-all.out -o=coverage-all.html
==> cilium-master: cover: invalid argument
==> cilium-master: Makefile:43: recipe for target 'tests-consul' failed
==> cilium-master: make: *** [tests-consul] Error 1

Can someone have a look at that?

**Comment by tgraf** [comment]
> Can someone have a look at that?

@aanm Any indication on the consuls test fail?

**Comment by aanm** [comment]
@tgraf It's not related to consul, but with `cover` tool:
```
==> cilium-master: go tool cover -html=coverage-all.out -o=coverage-all.html
==> cilium-master: cover: invalid argument
```

@jrajahalme It's odd, I can't trigger this on my local VM.

**Comment by jrajahalme** [comment]
Locally the build with tests completes successfully, but it runs tests only once. On the build failure there also is one successful run before the failed one. I don't know what is the difference between the two runs on Jenkins.

**Comment by jrajahalme** [comment]
Also, I'm locally running the tests also without the "sudo", seems to work the same either way. Anyone know why we have the "sudo" on the make tests line in the script?

**Comment by jrajahalme** [comment]
Ian found that "cover: invalid argument" has been seen previously when there was no permissions rot write to the output files. Not the most best way to put it!

**Comment by tgraf** [comment]
So the issue is this in the `Vagrantfile`
```
make -C ~/go/src/github.com/cilium/cilium/ tests || exit 1
```

A previous command run with sudo must create the output directory with different permissions

**Comment by jrajahalme** [comment]
You mean that the "make check" as non-root fails after the build.sh runs the tests as root?
If so, the fix is to not run the tests as root from the build.sh, or, if we are running the tests separately anyway, remove the whole make checks line from build.sh.

Suggestions?

N.B. I'm using NFS to share my cilium directory, and in the setup permissions make no difference, so that explains why I can't see this failure on my system.

**Comment by aanm** [comment]
>N.B. I'm using NFS to share my cilium directory, and in the setup permissions make no difference, so that explains why I can't see this failure on my system.

ah! I'm also using NFS

**Comment by jrajahalme** [comment]
My preference is to remove the sudo make tests line from build.sh. It was effectively disabled as is already, so this would be the least disruption option.

**Comment by tgraf** [comment]
> My preference is to remove the sudo make tests line from build.sh. It was effectively disabled as is already, so this would be the least disruption option.

Agreed

**Comment by jrajahalme** [comment]
This is now hitting a run-time test failure, too:

==> cilium-master: ++ docker exec -i client bash -c 'curl -s --output /dev/stderr -w '\''%{http_code}'\'' --connect-timeout 10 -XGET http://10.11.77.25:80/private'
==> cilium-master: { 'val': 'this is private' }
==> cilium-master: ------------------------------------------------------------------------
==> cilium-master:                             Test Failed
==> cilium-master: GET /private, unexpected return

Seems like #707

**Review by tgraf — APPROVED** [review]

**Pull request merged**
