### PR TITLE
Ingress id backport 1.13

### PR DESCRIPTION
**Pull request by jrajahalme**
* [x] #24826(@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 24826; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=24826
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.13

**Comment by sayboras** [comment]
/test-1.18-4.19

**Comment by sayboras** [comment]
/test-1.21-4.19

**Comment by sayboras** [comment]
/test-1.26-net-next

**Review by michi-covalent — APPROVED** [review]

**Comment by jrajahalme** [comment]
/test-1.16-4.19

**Comment by jrajahalme** [comment]
/test-1.18-4.19

**Comment by jrajahalme** [comment]
/test-1.19-4.19

**Pull request merged**
