### PR TITLE
[v1.4] examples/kubernetes: bump cilium to v1.4.5

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8447)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-docs-please

**Comment by ianvernon** [comment]
FQDN tests failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13373/execution/node/135/log/

**Comment by ianvernon** [comment]
test-upstream-k8s

**Pull request merged**
