### PR TITLE
pkg/k8s: fix custom dialer logic for etcd >= 3.5.0

### PR DESCRIPTION
**Pull request by aanm**
Since etcd >= 3.5.0 the library started to remove the URL Scheme from
the URL making the custom dialer failing parse a "service ID" from the
URL. This commit introduces some logic that will allow it to parse a
"service ID" from the URL that doesn't have the URL Scheme, as per
etcd 3.5.0

```release-note
Fix Cilium bootstrapping regression with etcd without relying on DNS
```

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
While you are here, can you bump etcd to 3.5.3 as well ? 

https://github.com/etcd-io/etcd/tree/main/CHANGELOG

> Running etcd v3.5.2, v3.5.1 and v3.5.0 under high load can cause a data corruption issue. If etcd process is killed, occasionally some committed transactions are not reflected on all the members. Recommendation is to upgrade to v3.5.3.

**Review by christarazi — APPROVED** [review]

**Comment by aanm** [comment]
> While you are here, can you bump etcd to 3.5.3 as well ?
> 
> https://github.com/etcd-io/etcd/tree/main/CHANGELOG
> 
> > Running etcd v3.5.2, v3.5.1 and v3.5.0 under high load can cause a data corruption issue. If etcd process is killed, occasionally some committed transactions are not reflected on all the members. Recommendation is to upgrade to v3.5.3.

that should be done by @dependabot

**Comment by sayboras** [comment]
> that should be done by https://github.com/dependabot

oh I mean the etcd images that we used in values.yaml (e.g. clustermesh) and some places with testing.

**Pull request merged**
