### PR TITLE
Cilium-operator fixes

### PR DESCRIPTION
**Pull request by eloycoto**
- Operator: install on path
- Runtime: Install ca-certificates to be able to communicate with AWS on toGroups rule. 
- Bump version on the main dockerfile. (I'm not sure If it is the right workflow

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6322)

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by eloycoto** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

Download timed out

**Comment by tgraf** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
