### PR TITLE
restore full go vet behaviour

### PR DESCRIPTION
**Pull request by bimmlerd**
This PR contains three commits to fix up `go vet ./...` which had regressed, and a fourth commit to reinstate running it as part of CI.

This effectively reverts https://github.com/cilium/cilium/pull/26978, which seems fine as the PR which is linked as requiring it was never merged. Additionally, the work which seems to supersede it doesn't appear to require the deepcopy stuff https://github.com/cilium/cilium/pull/28873 (feel free to correct me here, @marqc).

cc @tklauser for the original change to drop `go vet`.

### CODE REVIEW

**Review by tklauser — APPROVED** [review]

**Review by kaworu — APPROVED** [review]
Hubble changes LGTM, thanks @bimmlerd!

**Comment by marqc** [comment]
@bimmlerd LGTM
I believe the original change was made by @AwesomePatrol because the initial attempt for dynamic flowlogging was to use CRDs with FlowFilters. This is not required by configuration stored in yaml files.

**Comment by bimmlerd** [comment]
Tests reliant on 1.1.1.1 are failing due to https://www.cloudflarestatus.com/incidents/hm7491k53ppg, I'll wait with retriggering until that is resolved.

**Pull request merged**
