### PR TITLE
docs: add section for stable releases to readme

### PR DESCRIPTION
**Pull request by borkmann**
Rendered preview: https://github.com/cilium/cilium/blob/pr/misc-docs/README.rst#stable-releases

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9131)

### CODE REVIEW

**Comment by borkmann** [comment]
test-docs-please

**Review by joestringer — COMMENTED** [review]
This is nice for visibility from users, though I wonder if it becomes a pain to maintain over time. In particular if anyone checks out an older branch or release they'll get random values for this, regardless of what the actual current stable versions are.

Another aspect to this is when we make a new v1.4 branch release, we need to submit a PR against master to update this version.

It'd be nice if we could generate just one page, ideally dynamically, by just pulling the versions from the actual branches:

https://github.com/cilium/cilium/blob/v1.6/VERSION
https://github.com/cilium/cilium/blob/v1.5/VERSION
https://github.com/cilium/cilium/blob/v1.4/VERSION

Would this be better suited for integration into the main cilium.io website? We could retain a reference in the docs like this that says "For stable versions, visit this URL...".

We could even just set up some cron job somewhere that pulls the current versions from the above URLs, compares them against the current website code, and submits a PR to the website repo to update it if they change. Then we only need to update the cron job's set of branches once per release series (`1.x.0`) rather than submitting a PR once per release (`1.x.y`).

I guess if we got super fancy then we could pull http://docs.cilium.io/en/stable to fetch the latest version number of the current release, then do some simple `-1`, `-2` version magic to figure out the current 3 supported releases. Then we wouldn't need any manual interaction at all per release.

**Comment by borkmann** [comment]
> This is nice for visibility from users, though I wonder if it becomes a pain to maintain over time. In particular if anyone checks out an older branch or release they'll get random values for this, regardless of what the actual current stable versions are.
> 
> Another aspect to this is when we make a new v1.4 branch release, we need to submit a PR against master to update this version.
> 
> It'd be nice if we could generate just one page, ideally dynamically, by just pulling the versions from the actual branches:
> 
> https://github.com/cilium/cilium/blob/v1.6/VERSION
> https://github.com/cilium/cilium/blob/v1.5/VERSION
> https://github.com/cilium/cilium/blob/v1.4/VERSION

If this could be scripted, that would be nice indeed. Wrt maintainability, whenever we cut a new v1.7 stable branch in future, for example, then this section would need to be removed from the v1.7 branch README to avoid confusing users as the one in master would be the source of truth. Agree  that there is some sort of an update burden for the master's README, though the nice aspect is that it would be directly at the main landing page for the Cilium repo, hence easy to find for users.

> Would this be better suited for integration into the main cilium.io website? We could retain a reference in the docs like this that says "For stable versions, visit this URL...".

No strong opinion wrt whether website is better. I like for example that on kernel.org, all the important info wrt releases is in a single overview page there. The website could probably have a similar page somewhere. Third option would be in docs.cilium.io under release management, though might be harder to find and more easily missed wrt update.

> We could even just set up some cron job somewhere that pulls the current versions from the above URLs, compares them against the current website code, and submits a PR to the website repo to update it if they change. Then we only need to update the cron job's set of branches once per release series (`1.x.0`) rather than submitting a PR once per release (`1.x.y`).

Good point, presumably that could also be done by a bot for the README as well, so this would work whichever way we would want to go.

> I guess if we got super fancy then we could pull http://docs.cilium.io/en/stable to fetch the latest version number of the current release, then do some simple `-1`, `-2` version magic to figure out the current 3 supported releases. Then we wouldn't need any manual interaction at all per release.

**Review by nebril — APPROVED** [review]

**Comment by joestringer** [comment]
> If this could be scripted, that would be nice indeed. Wrt maintainability, whenever we cut a new v1.7 stable branch in future, for example, then this section would need to be removed from the v1.7 branch README to avoid confusing users as the one in master would be the source of truth. Agree that there is some sort of an update burden for the master's README, though the nice aspect is that it would be directly at the main landing page for the Cilium repo, hence easy to find for users.

We could probably script this too. If we don't already have a "prepare for release" script, we could likely add some sed magic to look for and exclude this section when updating older releases. Might be simpler than the proposals I had. /cc @ianvernon 

> Good point, presumably that could also be done by a bot for the README as well, so this would work whichever way we would want to go.

True :)

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
We need to heavily increase our release automation anyway - adding an extra step isn't too big of a deal right now.

**Pull request merged**
