### PR TITLE
[v1.11] test/k8sT: remove l7_demos test

### PR DESCRIPTION
**Pull request by tklauser**
Manual backport of #20619 to `v1.11` branch. See https://github.com/cilium/cilium/pull/20619#issuecomment-1403391230 and https://github.com/cilium/cilium/pull/23313#issuecomment-1403398570 for context.

[ upstream commit 1db11560db02b930864d481b5bf719a08de33a43 ]

[ Backporter's note: manual backport because the containing directory got
  renamed in commit ffd7e57b377f ("test: Standardize file naming for
  tests") on master. ]

With cilium/cilium-cli#962 in place in cilium-cli v0.12.0 and the CI update to use that version in #20617, the connectivity tests cover all functionality tested by the tests in l7_demos.go. Moreover, the cilium-cli connectivity tests can be run against arbitrary clusters with Cilium deployed, while this test is specific for the test setup based on vagrant VMs. Thus, drop this test.

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.11

**Review by michi-covalent — APPROVED** [review]
LGTM

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
/test-backport-1.11

**Comment by tklauser** [comment]
> /test-gke
> 
> Previous run imed out due to Cilium pods still in ContainerCreating or Init state, presumably due to delays in image build: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/9256/ Re-triggered to confirm.

From https://jenkins.cilium.io/view/Cilium-v1.11/job/cilium-v1.11-gke/ it looks like that job is broken on `v1.11` in general. I assume it's thus also not marked as required. Given the failure is unrelated to this PR, all other tests passed and approvals are in, I'll mark this as ready to merge.

**Comment by joestringer** [comment]
> I assume it's thus also not marked as required.

No need to assume, the UI does not label it as "Required":

image

**Pull request merged**
