### PR TITLE
v1.14 Backports 2023-07-05

### PR DESCRIPTION
**Pull request by joamaki**
* [x] #25901 (@jrajahalme)
 * [ ] #26518 (@nayihz)
 * [x] #26245 (@nathanjsweet)
 * [x] #26538 (@gandro)
 * [x] #26549 (@jrajahalme)
 * [x] #19541 (@borkmann)
 * [x] #26349 (@dylandreimerink)
 * [x] #26558 (@julianwiedmann)
 * [x] #26375 (@mhofstetter)
 * [x] #26553 (@qmonnet)
 * [x] #26550 (@julianwiedmann)
 * [x] #26560 (@ferozsalam)
 * [ ] #26526 (@networkop)
 * [x] #26522 (@gandro)
 * [x] #26566 (@tklauser)
 * [x] #26582 (@julianwiedmann)
 * [x] #26517 (@markpash)
 * [x] #26609 (@julianwiedmann)
 * [x] #26534 (@harsimran-pabla)
 * [x] #26139 (@PhilipSchmid)
 * [x] #25582 (@marqc) (NOTE: Regenerated cilium/values.yaml)
 * [x] #26592 (@mhofstetter)
 * [x] #26627 (@mhofstetter)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 25901 26518 26245 26538 26549 19541 26349 26558 26375 26553 26550 26560 26526 26522 26566 26582 26517 26609 26534 26139 25582 26592 26627; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=25901,26518,26245,26538,26549,19541,26349,26558,26375,26553,26550,26560,26526,26522,26566,26582,26517,26609,26534,26139,25582,26592,26627
```

### CODE REVIEW

**Review by gandro — APPROVED** [review]
My PRs look good to me, thanks!

**Review by mhofstetter — APPROVED** [review]
LGTM, thanks!

**Review by ferozsalam — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
Thanks, looks good for my commit.

**Review by PhilipSchmid — APPROVED** [review]

**Comment by qmonnet** [comment]
- https://github.com/cilium/cilium/pull/26553 (@qmonnet)

Looks good, thank you

**Review by dylandreimerink — APPROVED** [review]

**Review by marqc — APPROVED** [review]
My PR lgtm

**Review by nathanjsweet — APPROVED** [review]
policy doc changes look good.

**Review by markpash — APPROVED** [review]

**Comment by joamaki** [comment]
/test-backport-1.14

**Review by qmonnet — APPROVED** [review]
Forgot to “approve”

**Review by aanm — APPROVED** [review]

**Review by borkmann — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]

**Pull request merged**
