### PR TITLE
Test: Updating Kube-dns manifest to get more verbose

### PR DESCRIPTION
**Pull request by eloycoto**
- Updating kube-dns to version 1.14.10

Related to #3878

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by ianvernon** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
Issue with getting container images: 
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:312
Empire pods are not ready after timeout
Expected
    <*errors.errorString | 0xc420c1f870>: {
        s: "Timeout reached: could not get Pods",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/demos.go:136
```

**Comment by eloycoto** [comment]
test-me-please

**Pull request merged**
