### PR TITLE
Standardize testing directory filepath naming

### PR DESCRIPTION
**Pull request by joestringer**
Standardize the naming and remove the weird capitalization issues. This
may create a bit of churn in the tree in the short term, but will save
developers' fingers when trying to figure out which characters need to be
capitalized or not while attempting to edit specific filepaths.

### CODE REVIEW

**Comment by joestringer** [comment]
Only one failure. I see that there's a conflict, can coordinate rebase+merge at some point to hopefully minimize conflict with any other PRs in the tree.

**Comment by joestringer** [comment]
Wow, I actually didn't anticipate it pulling in so many codeowners. I really think this only needs one or two people to look over it for a sanity check and :+1: .

**Review by christarazi — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Review by twpayne — APPROVED** [review]
It's worth mentioning this in the next community meeting as it will mostly affect macOS developers with their case-insensitive but case-preserving filesystems.

**Review by jibi — APPROVED** [review]

**Comment by joestringer** [comment]
To avoid filesystem naming conflicts, I renamed the runtime test files slightly differently than the `k8sT`->`k8s` renames:
```
 test/runtime/{assertionHelpers.go => assertion_helpers.go}               |  0
 test/runtime/{Policies.go => net_policies.go}                            |  0
```

**Review by aditighag — APPROVED** [review]

**Comment by joestringer** [comment]
[runtime](https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1343/execution/node/78/log/?consoleFull) provisioning took a very long time, looks suspiciously like issues we've had in the past with the provider for the CI infrastructure. Ignoring. I'll rebase once more & re-kick for another check of CI stability. None of the failures are looking at all related to the PR at this point.

**Comment by joestringer** [comment]
[k8s-1.21-kernel-5.4](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-5.4/574/) hit #18873. [runtime](https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1365/) hit timeouts during provisioning, to be fixed by https://github.com/cilium/cilium/pull/18886.

**Comment by joestringer** [comment]
[Runtime job](https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1433/execution/node/92/log/) hit some weird issue:
```
12:11:37      runtime: /tmp/provision/compile.sh: line 28: cd: /home/vagrant/go/src/github.com/cilium/cilium: Stale file handle
```

**Pull request merged**
