### PR TITLE
[CI] Fix path to print-node-ip script in jenkinsfile

### PR DESCRIPTION
**Pull request by nebril**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10112)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Review by aanm — APPROVED** [review]
Thanks @nebril

**Comment by aanm** [comment]
@nebril do we need to backport this to 1.6 and 1.7?

**Comment by nebril** [comment]
@aanm only 1.7

**Comment by nebril** [comment]
test-focus K8sDemos*

**Pull request merged**
