### PR TITLE
v1.8 backports 2021-01-28

### PR DESCRIPTION
**Pull request by joestringer**
* #14730 -- bpf: Send packet drop notify for ipv6 lb nat mode failures. (@hzhou8)
 * #14707 -- contrib: Add script to fetch docker manifests (@joestringer)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14730 14707; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by joestringer** [comment]
test-backport-1.8

**Comment by joestringer** [comment]
@pchaigno is this what a normal k8sVerifier test failure looks like, or does it normally give more details at the jenkins job level?

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.11-net-next/1535/testReport/Suite-k8s-1/11/K8sVerifier_Runs_the_kernel_verifier_against_Cilium_s_BPF_datapath/

**Comment by pchaigno** [comment]
> @pchaigno is this what a normal k8sVerifier test failure looks like, or does it normally give more details at the jenkins job level?
> 
> https://jenkins.cilium.io/job/Cilium-PR-K8s-1.11-net-next/1535/testReport/Suite-k8s-1/11/K8sVerifier_Runs_the_kernel_verifier_against_Cilium_s_BPF_datapath/

It should always give more information (usually BPF verifier logs). Here it failed to schedule, but it should already have all the necessary tolerations :thinking:

I'll add `kubectl describe nodes` to the failure logs to see if we're missing any toleration. In the meantime, I'll restart (we need K8sVerifier here given we are backporting some BPF changes).

**Comment by pchaigno** [comment]
test-netnext

**Comment by pchaigno** [comment]
test-1.11-netnext

**Review by pchaigno — APPROVED** [review]
Backports look good to me!

**Review by kaworu — APPROVED** [review]

**Pull request merged**
