### PR TITLE
bpf, sock: fix post-bind-sock{4,6} not found in ELF file

### PR DESCRIPTION
**Pull request by borkmann**
See commit msg.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10124)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Review by joestringer — COMMENTED** [review]
Is just `NODE_PORT` enough? Inside `bpf_sock.c` there's conditionals for node port enablement, meaning some of it is expected to run without nodeport (only hostlb maybe?). In `pkg/datapath/loader/base.go` this value seems to be configured purely based on the `EnableNodePort` flag.

**Comment by borkmann** [comment]
> Is just `NODE_PORT` enough? Inside `bpf_sock.c` there's conditionals for node port enablement, meaning some of it is expected to run without nodeport (only hostlb maybe?). In `pkg/datapath/loader/base.go` this value seems to be configured purely based on the `EnableNodePort` flag.

Yes, so the ExternalIP enablement depends on NodePort, and the bind hooks are only needed for these two cases (to block binding on the same src port).

**Review by joestringer — APPROVED** [review]
Makes sense, thanks!

**Review by brb — APPROVED** [review]

**Comment by borkmann** [comment]
provision error, retry

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Hit `Restart Cilium validate that FQDN is still working` flake.

**Comment by borkmann** [comment]
test-me-please

**Pull request merged**
