### PR TITLE
kvstore: clean up casting around kvstore.Encode

### LINKED ISSUE #8630: Clean up casting around kvstore.Encode
The casting between `string` and `[]byte` around usage of `kvstore.Encode()` and its helpers `encodeKey()` can be optimized

### PR DESCRIPTION
**Pull request by borancar**
Replace []byte with *string. In go, string is in effect a read-only slice of
bytes https://blog.golang.org/strings. The only semantic difference would be
that a byte[] can be nil, but a string can't, so use *string.

Fixes: #8630

Signed-off-by: Boran Car <boran.car@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9138)

### CODE REVIEW

**Review by borancar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cilium/cilium/9138)* status: :shipit: complete! 0 of 9 files reviewed, 4 unresolved discussions (waiting on @houndci-bot)

___
*[pkg/kvstore/kvstore.go, line 56 at r1](https://reviewable.io/reviews/cilium/cilium/9138#-Lo0OxirBQ1gQluTVgNy-r1-56:-Lo25Pih6woyUlqEPtfh:b-896fix) ([raw file](https://github.com/cilium/cilium/blob/0cea0143583e6618082c5bd373d84c1a4d588821/pkg/kvstore/kvstore.go#L56)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

if block ends with a return statement, so drop this else and outdent its block
</blockquote></details>

Done.
___
*[pkg/kvstore/kvstore.go, line 68 at r1](https://reviewable.io/reviews/cilium/cilium/9138#-Lo0OxirBQ1gQluTVgNy-r1-68:-Lo25Smm9uwYBbGiHDQq:b-896fix) ([raw file](https://github.com/cilium/cilium/blob/0cea0143583e6618082c5bd373d84c1a4d588821/pkg/kvstore/kvstore.go#L68)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

if block ends with a return statement, so drop this else and outdent its block
</blockquote></details>

Done.
___
*[pkg/kvstore/kvstore.go, line 80 at r1](https://reviewable.io/reviews/cilium/cilium/9138#-Lo0OxirBQ1gQluTVgNy-r1-80:-Lo25TNxAEH7tp65NGY2:b-896fix) ([raw file](https://github.com/cilium/cilium/blob/0cea0143583e6618082c5bd373d84c1a4d588821/pkg/kvstore/kvstore.go#L80)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

if block ends with a return statement, so drop this else and outdent its block
</blockquote></details>

Done.
___
*[pkg/kvstore/kvstore.go, line 92 at r1](https://reviewable.io/reviews/cilium/cilium/9138#-Lo0OxirBQ1gQluTVgNy-r1-92:-Lo25U-k2_S92l7jXmkq:b-896fix) ([raw file](https://github.com/cilium/cilium/blob/0cea0143583e6618082c5bd373d84c1a4d588821/pkg/kvstore/kvstore.go#L92)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

if block ends with a return statement, so drop this else and outdent its block
</blockquote></details>

Done.

**Comment by ianvernon** [comment]
test-me-please

**Comment by borancar** [comment]
I can't reproduce the Ginkgo test failure locally on k8s 1.15 (and 1.11) and I don't get any "Key allocation attempt failed" in the cilium-test.log.
```
$ ginkgo --focus="Istio Bookinfo Demo Tests" -- -cilium.testScope k8s
level=info msg="environment variable \"K8S_VERSION\" was not set; setting to default value \"1.15\""
User specified the scope:  "k8s"
Running Suite: Suite-k8s-1.15
=============================
Random Seed: 1567768090
Will run 1 of 366 specs

Spinning up vagrant VMs... ●SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

------------------------------
• [SLOW TEST:1533.397 seconds]
K8sIstioTest
/home/boran/go/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:385
  Istio Bookinfo Demo
  /home/boran/go/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:385
    Tests bookinfo inter-service connectivity
    /home/boran/go/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:420
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 366 Specs in 1533.399 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 365 Skipped
PASS

Ginkgo ran 1 suite in 25m36.312180374s
Test Suite Passed
```

**Comment by borancar** [comment]
Can we rerun the the tests please?

**Comment by borancar** [comment]
test-me-please

**Comment by aanm** [comment]
@borancar can you rebase against master instead? (We try to avoid merge commits)

I'll trigger a test-me-please in the meanwhile

**Comment by aanm** [comment]
test-me-please

**Comment by borancar** [comment]
Rebased. This is the link to the previous tests, before the rebase - https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14913/. There was an issue provisioning the VMs, it seems:
```
03:08:28  VBoxManage: error: Machine 'a38c7b8c-bf31-4439-bd75-8ef7a9f32f84' is not currently running
03:08:28  0%...10%...20%...30%...40%...
03:08:28  Progress state: VBOX_E_INVALID_OBJECT_STATE
03:08:28  VBoxManage: error: Machine delete failed
03:08:28  VBoxManage: error: Medium '/root/VirtualBox VMs/ubuntu-18.04.3-amd64-32_1568076335632_91690/ubuntu-18.04.3-amd64-32-disk001.vmdk' is locked for reading by another task
03:08:28  VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MediumWrap, interface IMedium
03:08:28  VBoxManage: error: Context: "RTEXITCODE handleUnregisterVM(HandlerArg*)" at line 162 of file VBoxManageMisc.cpp
```

Could we rerun tests, please? :)

**Comment by borancar** [comment]
For merging, if tests are successful, could you Squash and rebase please, since the 2nd commit deals solely with fixing Hound issues?

**Review by aanm — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Pull request merged**
