### PR TITLE
make: check that Go major/minor version matches required version

### PR DESCRIPTION
**Pull request by tklauser**
Currently, when building Cilium with a Go major/minor version other than
the one specified in `GO_VERSON`, the build currently fails with:

    package github.com/cilium/cilium/cilium: build constraints exclude all Go files

It's not obvious from the compiler error message that this is due to
mismatching Go version.

This change adds a `check-go-version` target which checks the Go
compiler version used for building Cilium (as specified in `$(GO)`
against the version pinned in the `GO_VERSION` file, i.e. the version
used to build Cilium in CI. This check is required to pass in the
`precheck` target which should surface mismatching Go versions in a more
user-friendly way.

Example with matching version:

    $ go version
    go version go1.18.1 linux/amd64
    $ make check-go-version

Example with mismatching version:

    $ go1.17.9 version
    go version go1.17.9 linux/amd64
    $ make GO=go1.17.9 check-go-version
    Installed Go version 1.17 does not match requested Go version 1.18
    make: *** [Makefile:602: check-go-version] Error 1

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Review by aditighag — APPROVED** [review]
Thank you! 🚀

**Comment by aditighag** [comment]
@tklauser We don't seem to match the minor version though - https://github.com/cilium/cilium/blob/master/daemon/main.go#L6-L6.

**Comment by tklauser** [comment]
> @tklauser We don't seem to match the minor version though - https://github.com/cilium/cilium/blob/master/daemon/main.go#L6-L6.

I assume you meant the patch version? If yes, that's intentional. The `//go:build goX.Y` tags only use major/minor number and e.g. `//go:build go1.18` will evaluate to true for all Go 1.18.z versions and all major/minor versions newer than Go 1.18. The documentation unfortunately isn't very clear on this: https://pkg.go.dev/cmd/go (Ctrl-F for `go1.`)

**Comment by aditighag** [comment]
@tklauser Should we backport this to older versions?

**Comment by tklauser** [comment]
> @tklauser Should we backport this to older versions?

Yes, good point. Let's do that.

**Pull request merged**
