### PR TITLE
[wip]node: error on local host IP addresses collision with podCIDR

### LINKED ISSUE #6321: avoid running cilium if any of the local host IP addresses conflict with any other node's podCIDR

### PR DESCRIPTION
**Pull request by nirmoy**
avoid running cilium if any of the local host IP addresses
conflict with any other node's podCIDR

Fixes:#6321

Signed-off-by: Nirmoy Das <ndas@suse.de>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6415)

### CODE REVIEW

**Comment by nirmoy** [comment]
test-me-please

**Review by joestringer — COMMENTED** [review]
Could we get a unit test on this new functionality?

**Comment by nirmoy** [comment]
test-me-please

**Comment by nirmoy** [comment]
test-me-please

**Comment by nirmoy** [comment]
test-me-please

**Comment by raybejjani** [comment]
@nirmoy Following up on the discussion in the [cilium meeting on Dec 10](https://docs.google.com/document/d/1Y_4chDk4rznD6UgXPlPvn3Dc7l-ZutGajUv1eF0VDwQ/edit#heading=h.x1emtkxpfv5l), this is the "reservation" code I had in mind: https://github.com/cilium/cilium/blob/master/pkg/ipam/init.go#L146-L156 It seems to handle the scenario of changing `podCIDR` here too, and maybe that makes this function a good spot for the new logic. (cc @aanm since he put this up for discussion).
I noticed that there is code further up to handle routes and discovering them as well.

**Comment by joestringer** [comment]
As discussed in Slack, this is currently checking for collisions between the local IPs and the local CIDR range, however the intent of #6321 is to check for collisions between local IPs and remote CIDR ranges.

**Review by joestringer — CHANGES_REQUESTED** [review]
As discussed in Slack, this is currently checking for collisions between the local IPs and the local CIDR range, however the intent of #6321 is to check for collisions between local IPs and remote CIDR ranges.

**Pull request closed without merging**
