### PR TITLE
docs: Clean-up Host Firewall documentation, list known issues

### PR DESCRIPTION
**Pull request by qmonnet**
- docs: Alias "kubectl exec" command in Host Firewall guide
- docs: Clean up Host Firewall documentation
- docs: Document Host Policies known issues
  Refers to:
  - https://github.com/cilium/cilium/issues/25448
  - https://github.com/cilium/cilium/issues/31209
  - https://github.com/cilium/cilium/issues/17636
  - https://github.com/cilium/cilium/issues/17877
  - https://github.com/cilium/cilium/issues/18347
  - https://github.com/cilium/cilium/issues/12545
- docs: Link Host Policies "troubleshooting"/"known issues" from HFW tuto

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Nice, looks good to me.

Should it get backported to previous versions?

**Comment by qmonnet** [comment]
Good question, I'm not sure all reported issues apply to all stable branches so I'd need to check about that, first. Thanks!

**Review by julianwiedmann — APPROVED** [review]
lgtm, thank you! I'll add the 1.15 backports label, think it's good to also have this in a stable release.

**Review by squeed — APPROVED** [review]

**Pull request merged**
