### PR TITLE
bpf: Force preallocation for SNAT maps of LRU type

### LINKED ISSUE #7899: Use of IPVLAN required to use --preallocate-bpf-maps=true
Reported by krsna1729 on Slack [0]

A user running the following configuration:
```
  datapath-mode: "ipvlan"
  ipvlan-master-device: "enp0s9"
  tunnel: "disabled"
  masquerade: "true"
  install-iptables-rules: "false"
  auto-direct-node-routes: "true"
```

reported this error:
```
level=warning msg="+ tc filter add dev enp0s9 ingress prio 1 handle 1 bpf da obj bpf_netdev.o sec masq-pre" subsys=daemon
level=warning msg="Map object 'cilium_snat_v4_external' rejected: Unknown error 524 (524)!" subsys=daemon
level=warning msg=" - Type:         9" subsys=daemon
level=warning msg=" - Identifier:   0" subsys=daemon
level=warning msg=" - Pinning:      2" subsys=daemon
level=warning msg=" - Size key:     14" subsys=daemon
level=warning msg=" - Size value:   40" subsys=daemon
level=warning msg=" - Max elems:    524288" subsys=daemon
level=warning msg=" - Flags:        0x1" subsys=daemon
level=warning subsys=daemon
level=warning msg="Error loading maps into kernel!" subsys=daemon
```

```
include/linux/errno.h:#define ENOTSUPP  524     /* Operation is not supported */
```

It was suspected that the following kernel check fails:
```
        if (lru && !prealloc)
                return -ENOTSUPP;
```

We requested the user to run with the flag `--preallocate-bpf-maps=true`. This solved the problem.

[0] https://cilium.slack.com/archives/C1MATJ5U5/p1556646507097200

### PR DESCRIPTION
**Pull request by brb**
As reported by a user and tgraf, the bpf/hashtab.c in the kernel has the following precondition when creating maps:

    if (lru && !prealloc)
        return -ENOTSUPP;

Previously, the SNAT related maps set `CONDITIONAL_PREALLOC` regardless of the maps type. Thus, when `HAVE_LRU_MAP_TYPE` was detected and `--preallocate-bpf-maps=false` was passed to cilium-agent, the kernel was failing to load the map with the following error:

    Map object 'cilium_snat_v4_external' rejected: Unknown error 524 (524)!

Fixes: 0e785f9675 ("bpf: initial bpf-based masquerading support")

Fix #7899 

---

Please note that no changes are required for the Go part, as we already require the preallocation for the LRU maps: https://github.com/cilium/cilium/blob/pr/brb/fix-snat-map-prealloc-lru/pkg/bpf/map.go#L131.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7907)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by brb** [comment]
The CI build failed due to the know issue - timeout during the VM image fetch. I'll re-run the tests once the CI infra issue has been resolved.

**Review by joestringer — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]
Good catch, lgtm!

**Comment by tgraf** [comment]
VM download timed out

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Hit known flakes, merging

**Pull request merged**
