### PR TITLE
ci: Move HostPort test from Jenkins CI to the ConformanceKind GitHub Action

### PR DESCRIPTION
**Pull request by gandro**
This PR removes the `conformance.go` test driver from the Jenkins-based CI test suite and replaces it favor of an updated ConformanceKind GitHub Action with HostPort support enabled.

The removed K8sConformance Jenkins test ran the YAML-based connectivity tests with HostPort support enabled. We have since ported over all functionality of the `connectivity-check-*.yaml` files to the Cilium CLI, including most recently the HostPort test in https://github.com/cilium/cilium-cli/pull/1005.

The HostPort conformance test is now performed by ConformanceKind (see previous commit), as well as any future test platform which runs with KPR HostPort enabled. All other functionality of `conformance-check-*.yaml` was already previously covered by `cilium connectivity test`. The only exception is the disabled "HostPort with L7 policy" test, which has not been ported to the CLI.  HostPort with L7 policy [however was never enabled in CI](https://github.com/cilium/cilium/pull/12758), because it's not supported by Cilium. The YAML itself remains available for reproduction if needed.

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Nice :100:

**Comment by gandro** [comment]
:heavy_check_mark: The relevant GHA workflow passed: https://github.com/cilium/cilium/runs/8093074666?check_suite_focus=true

It's hard to see without running the CLI in verbose mode, but the HostPort related CLI checks have been executed as indicated by the number of additional dots in `no-policies`:

Before:
```
[=] Test [no-policies]
................................
```

After
```
[=] Test [no-policies]
....................................
```

**Comment by gandro** [comment]
/test-1.24-4.19

**Comment by gandro** [comment]
/test-1.16-4.9

**Review by christarazi — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]

**Comment by gandro** [comment]
There is a conflict due to the recently merged secrets change in our GHA workflows. Since that other change broke CI, I'll hold of a rebase till the other issue is addressed.

**Review by aanm — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by gandro** [comment]
Rebased. Marking ready to merge without re-running CI, as there have not been any relevant changes to the code.

**Comment by gandro** [comment]
Apparently HostPort support is broken on the current master, but the new test is apparently not failing. Investigating.

**Comment by gandro** [comment]
> Apparently HostPort support is broken on the current master, but the new test is apparently not failing. Investigating.

The breakage was actually not HostPort related, but the fact that the bump to CNI 0.4 broke CNI chaining on K8s 1.16 (which does not support CNI plugin 0.4).

It's unfortunate that by removing `conformance.go`, we'll also remove the test of CNI chaining on K8s v1.16, but I'm not sure what to do here.

**Comment by joestringer** [comment]
> It's unfortunate that by removing conformance.go, we'll also remove the test of CNI chaining on K8s v1.16, but I'm not sure what to do here.

Maybe a sign we should just drop k8s v1.16 support in Cilium v1.13?

**Comment by gandro** [comment]
We decided in the Cilium community meeting to bump the minimum K8s version for Cilium 1.13. The exact details are to be hashed out, but support for K8s 1.16 will be dropped and thus we can remove the test being removed in this PR here. Marking ready to merge.

**Comment by aanm** [comment]
@gandro will you be able to submit the documentation changes and necessary changes that drop the 1.16 job from being run?

**Comment by gandro** [comment]
> @gandro will you be able to submit the documentation changes and necessary changes that drop the 1.16 job from being run?

Yes, I will do that as a follow-up.

**Pull request merged**
