### PR TITLE
Test: Add microscope with timestamps

### LINKED ISSUE #4566: CI: Add timestamps to monitor.log
It'd be good to get timestamps for the monitor log so the traffic can be cross-referenced with timestamps in testsuite failures.

This might just be a matter of installing and using the `ts` command.

### PR DESCRIPTION
**Pull request by eloycoto**
- Update the microscope image with one that has installed moreutils
package.
- Add ts command on microscope output

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

Fix #4566

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4748)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by ianvernon** [comment]
@eloycoto  might be failing because `ts` may not installed in the microscope pod.

**Comment by eloycoto** [comment]
@ianvernon is already installed.

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
