### PR TITLE
Fix Azure IPAM regression

### PR DESCRIPTION
**Pull request by tgraf**

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
The GKE test failed because the FQDN proxy can't bind to the port:
```
2020-10-04T21:30:16.42229825Z level=fatal msg="Error while creating daemon" error="listen tcp :40457: bind: address already in use" subsys=daemon
```

**Comment by tgraf** [comment]
test-gke

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
Only 1.8 backport is needed, the bug is not present in 1.7.

**Pull request merged**
