### PR TITLE
build: Remove envoy from Makefile target

### PR DESCRIPTION
**Pull request by sayboras**
As mentioned in envoy/Makefile, the envoy binary is now part of cilium/proxy instead. This commit is to remove unnecessary step from Makefile targets.

### CODE REVIEW

**Review by bimmlerd — APPROVED** [review]

**Review by pippolo84 — APPROVED** [review]
:rocket:

**Review by michi-covalent — APPROVED** [review]

**Comment by sayboras** [comment]
Reviews from required teams are in, merging.

**Comment by pippolo84** [comment]
> Reviews from required teams are in, merging.

Marking this ready to be reviewed. :+1:

**Pull request merged**
