### PR TITLE
[v1.14] bpf: fib: fix issues with L2 resolution

### PR DESCRIPTION
**Pull request by julianwiedmann**
Manual & minimal backport of
* [ ] #30128

I opted to add the `allow_neigh_map` parameter only for `fib_do_redirect()`, while ignoring the legacy `fib_redirect()`.

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30128
```

### CODE REVIEW

**Comment by julianwiedmann** [comment]
/test-backport-1.14

**Comment by julianwiedmann** [comment]
verifier tests need https://github.com/cilium/cilium/pull/30371 to land ...

**Comment by julianwiedmann** [comment]
/test-backport-1.14

**Review by ldelossa — APPROVED** [review]
LGTM, contingent on tests :heavy_check_mark:

**Comment by julianwiedmann** [comment]
/test-backport-1.14

**Review by squeed — APPROVED** [review]

**Pull request merged**
