### PR TITLE
v1.7 backports 2020-04-29

### PR DESCRIPTION
**Pull request by vadorovsky**
* #11023 -- examples/getting-started: add bind mount for docker socket to docker-compose.yml (@tklauser)
 * #11101 -- daemon: set k8s options as soon as possible (@aanm)
 * #11121 -- docs: Pin Hubble version to v0.5 branch (@gandro)
 * #10964 -- policymap, fragmap: clean up doc, map size configuration (@qmonnet)
 * #11037 -- dns: Log WriteMsgIP details. (@jrajahalme)
 * #11073 -- Fix cilium-health healthchecking remote endpoint in ENI mode (@christarazi)
 * #10407 -- Add Kubernetes IPAM mode (@tgraf) - only the documentation change, without mentioning "kubernetes" mode
 * #11079 -- Switch to native-routing in GKE guide (@tgraf)
 * #11188 -- cilium: add NodePortBindProtection to allow for opting out bind rejection (@borkmann)
 * #11206 -- Auto-detects EndpointSlice support via apimachinery (@Weil0ng)
 * #11253 -- k8s: Provide fallback for EndpointSlices detection if discovery API is not available (@tgraf)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 11023 11101 11121 10964 11037 11073 10407 11079 11188 11206 11253; do contrib/backporting/set-labels.py $pr done 1.7; done
```

### CODE REVIEW

**Review by tklauser — APPROVED** [review]
LGTM for my change.

**Review by christarazi — CHANGES_REQUESTED** [review]
My changes seem to be missing 7c783f554b1ce86bab5fd77c1f636168f930dcaf from https://github.com/cilium/cilium/pull/11073

**Comment by jrfastab** [comment]
If possible it would be best to merge https://github.com/cilium/cilium/pull/11109 first to get things in order.

**Comment by mrostecki** [comment]
> My changes seem to be missing [7c783f5](https://github.com/cilium/cilium/commit/7c783f554b1ce86bab5fd77c1f636168f930dcaf) from #11073

@christarazi Yes, you are right. It didn't apply properly, so I thought it can be dropped, since it only changes variable names. But now I see that those variables are there on 1.7 branch and I could just solve the conflict. Sorry for that, I will reapply.

**Comment by joestringer** [comment]
Thanks for following up on these backports :)

FWIW I'd like to hold off on further 1.7 backports until we get #11109 merged and v1.7.3 out, users 
are hitting issues quite frequently (in particular the remote-node identity stuff) and other than the PRs that are also in #11109, I don't think any of the remaining backports here are immediately critical.

Hopefully we should be able to get v1.7.3 out today or tomorrow and proceed with the rest of these backports from there.

**Comment by mrostecki** [comment]
Sure, let's wait for #11109. This pull request is huge anyway and I think that there will be a lot to fix in ginkgo tests. And I will regenerate modules and cmdref before the next push.

**Comment by joestringer** [comment]
By the way I meant to post an update, but the above PR was merged and we put out v1.7.3. No need to block on anything for this PR now.

**Comment by qmonnet** [comment]
For what it's worth the backport for the fix I did for the eppolicymap looks good to me :+1:

**Comment by mrostecki** [comment]
@tgraf Documentation changes from #11079 (which I'm backporting here) seem to depend on documentation from #10407 - specifically on the `Documentation/concepts/ipam/kubernetes.rst`. How do you feel about backporting #10407? Or maybe we should backport only documentation from #10407?

**Comment by mrostecki** [comment]
@christarazi All your commits from your PR should be there. Sorry again!

**Comment by mrostecki** [comment]
never-tell-me-the-odds

**Comment by mrostecki** [comment]
Doc test fail because of the dependency mentioned here https://github.com/cilium/cilium/pull/11233#issuecomment-623420003

Now I'm sure that we have to backport #10407 too, at least partially.

**Comment by mrostecki** [comment]
never-tell-me-the-odds

**Comment by mrostecki** [comment]
never-tell-me-the-odds

**Comment by mrostecki** [comment]
never-tell-me-the-odds

**Comment by joestringer** [comment]
All of the tests except for the known failing ones (See also https://github.com/cilium/cilium/projects/85) are passing. @mrostecki are you looking for any further feedback on any of the backports?

**Comment by mrostecki** [comment]
@joestringer I would appreciate a feedback from @tgraf and @christarazi.

**Comment by Weil0ng** [comment]
Not sure if this is the right place or if it is too late to ask, but can we backport #11253 too? Without it #11206 might cause cilium to not start correctly on environments like GKE (where discovery API would fail).

**Review by christarazi — APPROVED** [review]

**Comment by mrostecki** [comment]
@Weil0ng I will backport #11253 tomorrow and add it to this PR. Thanks for letting me know!

**Comment by joestringer** [comment]
> Not sure if this is the right place or if it is too late to ask, but can we backport #11253 too? Without it #11206 might cause cilium to not start correctly on environments like GKE (where discovery API would fail).

Right place would usually be on the PR in question (I added a comment: https://github.com/cilium/cilium/pull/11253#issuecomment-624363433) or you could also raise it on Slack, in either #development or #launchpad . The request might be lost on the primary audience if it's tucked away in this PR.

At a glance it seems reasonable to me to backport, but I didn't review it and I don't know the risk / size / impact of the backport, which is why I figured it's worthwhile to raise a discussion point on the original PR to determine if we think the benefit / risk ratio is high enough to backport. Usually we mark all bugfixes for backport to the latest version, but there can be cases where it'd be less risky to hold it for a future release or do additional testing first.

**Review by tgraf — APPROVED** [review]

**Review by tgraf — CHANGES_REQUESTED** [review]
Must also backport #11253 as mentioned by @Weil0ng

**Comment by mrostecki** [comment]
never-tell-me-the-odds

**Comment by joestringer** [comment]
Ginkgo provisioning failure:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19550/execution/node/114/log/

**Comment by joestringer** [comment]
restart-ginkgo

**Comment by pchaigno** [comment]
@mrostecki That's a known failure, cf. #11126.

**Comment by pchaigno** [comment]
Another artifact for the same failure: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/1228/
[f3f75a75_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip](https://github.com/cilium/cilium/files/4593653/f3f75a75_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip)

**Comment by joestringer** [comment]
Lots of weird interrupts, seems like infrastructure issue: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19552/flowGraphTable/

**Comment by joestringer** [comment]
restart-ginkgo

**Comment by joestringer** [comment]
All checks came back green except for the known flake #11126. I'll rebase the bpf.sha and re-kick CI.

**Comment by joestringer** [comment]
never-tell-me-the-odds

**Comment by joestringer** [comment]
Failures seem to be provisioning issues. I will rekick.

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3078/
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19602/

**Comment by joestringer** [comment]
restart-ginkgo

**Comment by joestringer** [comment]
test-missed-k8s

**Comment by christarazi** [comment]
Looks like the build went green :tada:

**Pull request merged**
