### PR TITLE
bugtool: add `ip rule` and `cilium-health status` commands

### PR DESCRIPTION
**Pull request by ianvernon**
Fixes: #3498, #2691 

Signed-off by: Ian Vernon <ian@cilium.io>

### CODE REVIEW

**Comment by ianvernon** [comment]
Ran bugtool in a Cilium pod and the commands succeeded:

```
$ cat ip-rule.md 
# ip rule
10:	from all fwmark 0xfea/0xfff lookup 2005 
100:	from all lookup local 
32766:	from all lookup main 
32767:	from all lookup default 

$ cat cilium-health-status.md 
# cilium-health status
Probe time:   2018-04-03T18:24:11Z
Nodes:
  k8s2 (localhost):
    Host connectivity to 192.168.36.12:
      ICMP:          OK, RTT=642.49µs
      HTTP via L3:   OK, RTT=403.958µs
    Endpoint connectivity to 10.10.1.172:
      ICMP:          OK, RTT=560.358µs
      HTTP via L3:   OK, RTT=1.422554ms
  k8s1:
    Host connectivity to 192.168.36.11:
      ICMP:          OK, RTT=595.707µs
      HTTP via L3:   OK, RTT=2.10881ms
    Endpoint connectivity to 10.10.0.172:
      ICMP:          OK, RTT=871.968µs
      HTTP via L3:   OK, RTT=10.382773ms
```

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Hit #3462 :( running again.

**Comment by ianvernon** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
LGTM

**Comment by joestringer** [comment]
test-me-please

**Review by ashwinp — APPROVED** [review]

**Pull request merged**
