### PR TITLE
image/runtime: Update iptables-wrapper script

### PR DESCRIPTION
**Pull request by sayboras**
### Description

The original iptables-wrapper script is coming from [1], however,
this was spinned off to [2] in k8s upstream repo. This commit is
to get the latest iptables-wrapper script.

[1]: https://github.com/kubernetes/kubernetes/pull/82966
[2]: https://github.com/kubernetes-sigs/iptables-wrappers/blob/master/iptables-wrapper-installer.sh
Signed-off-by: Tam Mach <tam.mach@cilium.io>

### Testing

This is spin-off from #19852 so that we can decide to backports these changes (e.g. ubuntu upgrade vs iptables-wrapper update) independently.

### CODE REVIEW

**Review by christarazi — COMMENTED** [review]
Changes LGTM, I'm not sure how useful it is to review the actual iptables script. Do we feel that CI will give us a good enough signal to avoid regressions? Do we still feel this is risky?

**Comment by tommyp1ckles** [comment]
What's the context for why the script was changed upstream?

**Comment by sayboras** [comment]
> What's the context for why the script was changed upstream?

Sorry for late reply. As per my understanding, this script was not maintained and updated for quite sometime. The recent update in upstream is to keep up with latest k8s deployment:
- most of k8s deployment is with linux distribution with recent iptables version (e.g. 1.8.7)
- NFT mode is preferred compared to legacy mode.

https://github.com/kubernetes-sigs/iptables-wrappers/commits/master/iptables-wrapper-installer.sh

**Comment by sayboras** [comment]
> Changes LGTM, I'm not sure how useful it is to review the actual iptables script. Do we feel that CI will give us a good enough signal to avoid regressions? Do we still feel this is risky?

I think CI is giving us some confidence for sure, but it's hard to have complete confidence on iptables 😢 . Can we have it as part of 1.12 release, and then will backport to older version if required ?

**Comment by sayboras** [comment]
Closed this one as we are considering other approach to make sure kubelet and cilium are using the same iptables mode.

**Pull request closed without merging**
