### PR TITLE
IPsec: Remove `IP_POOLS` logic

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request removes the `IP_POOLS` logic in an attempt to make our IPsec logic as independent from IPAM modes as possible. These differences between IPAM modes have caused a lot of bugs in IPsec in the past.

The `IP_POOLS` logic is specific to AKS and EKS' IPAM modes, where we don't have one pod CIDR per node. Therefore, with those IPAM modes, we can't simply match on the destination pod CIDR in the kernel's IPsec configuration to know what outer destination IP address to use for the IPsec encapsulation. Instead, we rely on the ipcache to tell us what IP address to use. We tell the kernel to encapsulate with IP 0.0.0.0 and then rewrite the destination IP address to whatever the ipcache gave us.

This `IP_POOLS` logic is easy to implement, but fairly hackish and it means that the IPsec kernel configuration differs significantly between IPAM modes. This pull request replaces it with a new implementation.

In the new implementation, we rely on the recently introduced node IDs (cf. https://github.com/cilium/cilium/pull/23202). We install the same IPsec kernel configuration for all IPAM modes and use the packet mark to determine the destination node. The node ID is read from the ipcache before encryption and written into the packet mark, such that we will match the appropriate IPsec kernel config. and encapsulate with the right IP address.

Commit summary below. See commits for details.

1. Match on node ID from packet mark in XFRM. Doesn't handle AKS & EKS yet.
0. Document the limitation to 64k nodes for IPsec due to the use of the node IDs.
0. Free `skb->cb[4]` as we need it in a subsequent commit.
0. Remove `IP_POOLS` special case for AKS & EKS. This includes rewrite of the outer IP header after encryption.
0. Free the packet mark by using `skb->cb[4]` instead to pass the source security ID.
0. Write the node ID in the packet mark, to be matched against the XFRM state at encryption time.
0. Free packet mark on bpf_overlay recirculation, as we need it for the node IDs.
0. Rework the XFRM states and policies for AKS & EKS to have one XFRM state per remote nodes. This is the complement of commit 4.

### CODE REVIEW

**Review by NikAleksandrov — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]
Looks good to me, nice work! And very clean commit history.

(Typo `latter` -> `later` in the first commit description.)

**Review by jibi — APPROVED** [review]

**Comment by pchaigno** [comment]
All good as per MLH's label, but I'll push a small commit description change (to describe how the last commit's code moves, as per Jibi's feedback) before relabelling.

**Pull request merged**
