### PR TITLE
v1.13 Backports 2024-04-10

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #31533 (@chancez)
 * [x] #31686 (@sayboras) :warning: resolved conflicts
 * [x] #25642 (@tklauser)
 * [x] #29581 (@xyz-li)
 * [x] #31750 (@tklauser)
 * [x] #31728 (@saintdle)
 * [x] #31692 (@katiestruthers)
 * [x] #31847 (@xmulligan)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31533 31686 25642 29581 31750 31728 31692 31847
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Thanks for resolving the conflict, lgtm for my commits.

**Comment by nbusseneau** [comment]
I fixed missing `Sign-off` in my commits locally but not pushing for now since it's only commit log changes, no need to retrigger CI for that.

**Review by chancez — APPROVED** [review]

**Review by lmb — APPROVED** [review]
tophat

**Review by tklauser — APPROVED** [review]
Looks good for my changes, thanks!

**Comment by sayboras** [comment]
/test-1.16-4.19

**Comment by sayboras** [comment]
/test-1.23-4.19

**Review by xmulligan — APPROVED** [review]

**Comment by nbusseneau** [comment]
/test-backport-1.13

**Comment by nbusseneau** [comment]
/test-1.16-4.19

**Comment by nbusseneau** [comment]
/test-1.24-5.4

**Comment by nbusseneau** [comment]
/test-1.22-4.19

**Comment by nbusseneau** [comment]
/test-1.26-net-next

**Review by tklauser — APPROVED** [review]
Thanks

**Comment by giorio94** [comment]
The `RuntimeDatapathLB` datapath failure is caused by the `cilium bpf lb list -o json` key now including the backend slot as well, which is not expected when [looking up the map entry as part of the test](https://github.com/cilium/cilium/blob/pr%2Fv1.13-backport-2024-04-10-05-36/test/helpers/cilium.go#L880-L883). 

Example `cilium bpf lb list -o json` output:

```
{
  "10.2.2.2:80 (0)": [
    "0.0.0.0:0 (10) (0) [ClusterIP, non-routable] "
  ],
  "10.2.2.2:80 (1)": [
    "1.1.1.1:80 (10) (1)"
  ],
  "10.2.2.2:80 (2)": [
    "1.1.1.2:80 (10) (2)"
  ],
...
}
```

I still need to figure out why this didn't happen in the other stable branches though.

**Comment by giorio94** [comment]
Hmm, this well explains why it didn't occur in other branches 😅: bc927c0088f13a17904fe11ee53c29b5312396ed

**Comment by giorio94** [comment]
Attempted to adapt the test to make it compatible with the change, reusing the helper that had been introduced as part of the commit :crossed_fingers: :

```diff
diff --git a/test/helpers/cilium.go b/test/helpers/cilium.go
index 452fd7a1642b..1127470e46f3 100644
--- a/test/helpers/cilium.go
+++ b/test/helpers/cilium.go
@@ -47,7 +47,8 @@ func (s *SSHMeta) BpfLBList(noDuplicates bool) (map[string][]string, error) {
        if !res.WasSuccessful() {
                return nil, fmt.Errorf("cannot get bpf lb list: %s", res.CombineOutput())
        }
-       err := res.Unmarshal(&result)
+
+       result, err := parseLBList(res)
        if err != nil {
                return nil, err
        }
```

**Comment by giorio94** [comment]
/test-backport-1.13

**Comment by giorio94** [comment]
/test-backport-1.13

**Comment by giorio94** [comment]
Second attempt, additionally sorting the backend entries to prevent flakes during comparison:

```diff
diff --git a/test/helpers/cilium.go b/test/helpers/cilium.go
index 1127470e46f3..a420f4841191 100644
--- a/test/helpers/cilium.go
+++ b/test/helpers/cilium.go
@@ -10,6 +10,7 @@ import (
        "net"
        "os"
        "path/filepath"
+       "sort"
        "strconv"
        "strings"
        "time"
@@ -53,6 +54,13 @@ func (s *SSHMeta) BpfLBList(noDuplicates bool) (map[string][]string, error) {
                return nil, err
        }
 
+       // Ensure consistent ordering of the backend entries, to prevent flakes
+       // during the comparison performed as part of the "validates service
+       // recovery on restart" test.
+       for _, entries := range result {
+               sort.Strings(entries)
+       }
+
        if noDuplicates {
                for svc, entries := range result {
                        unique := make(map[string]struct{})
```

**Comment by giorio94** [comment]
/test-1.22-4.19

**Comment by giorio94** [comment]
/test-1.22-4.19

**Comment by giorio94** [comment]
/test-1.24-4.19

**Pull request merged**
