### PR TITLE
1.3 backports 18 10 17

### PR DESCRIPTION
**Pull request by ianvernon**
Backported PRs:

* #5885
* #5897
* #5898 
* #5908
* #5909
* #5910
* #5911
* #5912

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5918)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by tgraf** [comment]
k8s tests failed because etcd-operator scaled down and was not able to bootstrap again

**Comment by tgraf** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
