### PR TITLE
v1.16 Backports 2024-11-20

### PR DESCRIPTION
**Pull request by rastislavs**
* [x] #33523 (@michi-covalent)
 * [ ] #35923 (@yilas)
 * [x] #35921 (@ysksuzuki)
 * [ ] #35953 (@seadog007)
 * [x] #35945 (@tommyp1ckles)
 * [x] #35974 (@michi-covalent)
 * [x] #35971 (@harsimran-pabla)
 * [x] #35902 (@pippolo84)
 * [x] #35979 (@aanm) :warning: resolved conflicts
   - dropped changes in `.github/renovate.json5` (does not exist in v1.16)
 * [x] #34893 (@odinuge) :warning: resolved conflicts
   - manually resolved minor conflicts in few `dummyBackend` methods in `allocator_test.go`
 * [ ] #36005 (@devodev) :warning: resolved conflicts
   - manually added terminanting dot for peer-service as its content did not match with the version in the main branch
 * [x] #35838 (@MrFreezeex) :warning: resolved conflicts
   - resolved multiple conflicts and test incompatibilities, please see backporter's notes on individual commits
 * [ ] #35856 (@nddq)
 * [ ] #35936 (@jrajahalme)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33523 35923 35921 35953 35945 35974 35971 35902 35979 34893 36005 35838 35856 35936
```

### CODE REVIEW

**Comment by rastislavs** [comment]
/test-backport-1.16

**Review by michi-covalent — APPROVED** [review]

**Review by MrFreezeex — APPROVED** [review]
My commits looks good thanks!

**Review by brlbil — APPROVED** [review]

**Review by pippolo84 — APPROVED** [review]
Thanks!

**Review by harsimran-pabla — APPROVED** [review]

**Review by ysksuzuki — APPROVED** [review]

**Comment by rastislavs** [comment]
Cilium IPsec upgrade (ci-ipsec-upgrade) seems to be [failing consistently on the v1.16 branch recently](https://github.com/cilium/cilium/actions/workflows/tests-ipsec-upgrade.yaml?query=branch%3Av1.16) due to these issues:

- https://github.com/cilium/cilium/issues/36086
- https://github.com/cilium/cilium/issues/36081

**Review by aanm — APPROVED** [review]

**Review by odinuge — APPROVED** [review]

**Review by nddq — APPROVED** [review]

**Review by tommyp1ckles — APPROVED** [review]

**Comment by rastislavs** [comment]
@glibsm gentle ping, could you please take a look?

**Comment by rastislavs** [comment]
/test-backport-1.16

**Review by devodev — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Pull request merged**
