### PR TITLE
test: Keep trying exec if killed

### LINKED ISSUE #22476: CI: K8sAgentFQDNTest Validate that multiple specs are working correctly
### Test Name
```test-name
K8sAgentFQDNTest Validate that multiple specs are working correctly
```

### Failure Output
```failure-output
FAIL: Cannot install fqdn proxy policy
```

### Stacktrace
<details><summary>Click to show.</summary>

```stack-trace
/home/jenkins/workspace/Cilium-PR-K8s-1.25-kernel-4.19/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:515
Cannot install fqdn proxy policy
Expected
    <*errors.errorString | 0xc0006bb8b0>: {
        s: "Cannot retrieve cilium pod cilium-86qxh policy revision: cannot get the revision ",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.25-kernel-4.19/src/github.com/cilium/cilium/test/k8s/fqdn.go:257
```
</details>

### Standard Output
<details><summary>Click to show.</summary>

```stack-output
Cilium pods: [cilium-86qxh cilium-fc74v]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                           Ingress   Egress
prometheus-7c8c9684bb-tsvpn   false     false
app1-787b5c6c47-n76xw         false     false
app1-787b5c6c47-srgwt         false     false
app2-6b6857744b-w7hw4         false     false
app3-79897dfc85-5rpqb         false     false
coredns-567b6dd84-bwdzq       false     false
coredns-567b6dd84-lkv8d       false     false
grafana-59957b9549-9gtdc      false     false
Cilium agent 'cilium-86qxh': Status: Ok  Health: Ok Nodes "" ContainerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 30 Failed 0
Cilium agent 'cilium-fc74v': Status: Ok  Health: Ok Nodes "" ContainerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 38 Failed 0


```
</details>

### Standard Error
<details><summary>Click to show.</summary>

```stack-error
FAIL: Cannot install fqdn proxy policy
Expected
    <*errors.errorString | 0xc0006bb8b0>: {
        s: "Cannot retrieve cilium pod cilium-86qxh policy revision: cannot get the revision ",
    }
to be nil
=== Test Finished at 2022-12-01T00:17:25Z====
===================== TEST FAILED =====================
00:17:25 STEP: Running AfterFailed block for EntireTestsuite K8sAgentFQDNTest
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                               READY   STATUS    RESTARTS   AGE     IP              NODE   NOMINATED NODE   READINESS GATES
	 cilium-monitoring   grafana-59957b9549-9gtdc           1/1     Running   0          100s    10.0.1.130      k8s2   <none>           <none>
	 cilium-monitoring   prometheus-7c8c9684bb-tsvpn        1/1     Running   0          100s    10.0.1.250      k8s2   <none>           <none>
	 default             app1-787b5c6c47-n76xw              2/2     Running   0          25s     10.0.0.67       k8s1   <none>           <none>
	 default             app1-787b5c6c47-srgwt              2/2     Running   0          25s     10.0.0.28       k8s1   <none>           <none>
	 default             app2-6b6857744b-w7hw4              1/1     Running   0          25s     10.0.0.60       k8s1   <none>           <none>
	 default             app3-79897dfc85-5rpqb              1/1     Running   0          25s     10.0.0.244      k8s1   <none>           <none>
	 kube-system         cilium-86qxh                       1/1     Running   0          99s     192.168.56.12   k8s2   <none>           <none>
	 kube-system         cilium-fc74v                       1/1     Running   0          99s     192.168.56.11   k8s1   <none>           <none>
	 kube-system         cilium-operator-5d66864f64-6lcv5   1/1     Running   0          99s     192.168.56.12   k8s2   <none>           <none>
	 kube-system         cilium-operator-5d66864f64-6p6gz   1/1     Running   0          99s     192.168.56.11   k8s1   <none>           <none>
	 kube-system         coredns-567b6dd84-lkv8d            1/1     Running   0          36s     10.0.0.95       k8s1   <none>           <none>
	 kube-system         etcd-k8s1                          1/1     Running   0          6m34s   192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-apiserver-k8s1                1/1     Running   0          6m34s   192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-controller-manager-k8s1       1/1     Running   0          6m34s   192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-m7czx                   1/1     Running   0          6m8s    192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-x6lhb                   1/1     Running   0          2m29s   192.168.56.12   k8s2   <none>           <none>
	 kube-system         kube-scheduler-k8s1                1/1     Running   0          6m34s   192.168.56.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-cfsd4                 1/1     Running   0          106s    192.168.56.12   k8s2   <none>           <none>
	 kube-system         log-gatherer-jv2pg                 1/1     Running   0          106s    192.168.56.11   k8s1   <none>           <none>
	 kube-system         registry-adder-4jlkd               1/1     Running   0          2m27s   192.168.56.11   k8s1   <none>           <none>
	 kube-system         registry-adder-xxxfh               1/1     Running   0          2m26s   192.168.56.12   k8s2   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-86qxh cilium-fc74v]
cmd: kubectl exec -n kube-system cilium-86qxh -c cilium-agent -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend              Service Type   Backend                            
	 1    10.98.197.138:9090    ClusterIP      1 => 10.0.1.250:9090 (active)      
	 2    10.101.239.154:443    ClusterIP      1 => 192.168.56.11:4244 (active)   
	                                           2 => 192.168.56.12:4244 (active)   
	 3    10.96.0.1:443         ClusterIP      1 => 192.168.56.11:6443 (active)   
	 4    10.96.0.10:53         ClusterIP      1 => 10.0.0.95:53 (active)         
	 5    10.96.0.10:9153       ClusterIP      1 => 10.0.0.95:9153 (active)       
	 6    10.108.160.162:3000   ClusterIP      1 => 10.0.1.130:3000 (active)      
	 7    10.110.136.116:80     ClusterIP      1 => 10.0.0.67:80 (active)         
	                                           2 => 10.0.0.28:80 (active)         
	 8    10.110.136.116:69     ClusterIP      1 => 10.0.0.67:69 (active)         
	                                           2 => 10.0.0.28:69 (active)         
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-86qxh -c cilium-agent -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                        IPv6        IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                              
	 854        Disabled           Disabled          4          reserved:health                                                                    fd02::174   10.0.1.72    ready   
	 1062       Disabled           Disabled          21034      k8s:app=prometheus                                                                 fd02::163   10.0.1.250   ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-monitoring                                    
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                            
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                                              
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                                                   
	 1903       Disabled           Disabled          19955      k8s:app=grafana                                                                    fd02::1e2   10.0.1.130   ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-monitoring                                    
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                            
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                     
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                                                   
	 3631       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s2                                                                                  ready   
	                                                            reserved:host                                                                                                       
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-fc74v -c cilium-agent -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend              Service Type   Backend                            
	 1    10.96.0.1:443         ClusterIP      1 => 192.168.56.11:6443 (active)   
	 2    10.96.0.10:53         ClusterIP      1 => 10.0.0.95:53 (active)         
	 3    10.96.0.10:9153       ClusterIP      1 => 10.0.0.95:9153 (active)       
	 4    10.108.160.162:3000   ClusterIP      1 => 10.0.1.130:3000 (active)      
	 5    10.98.197.138:9090    ClusterIP      1 => 10.0.1.250:9090 (active)      
	 6    10.101.239.154:443    ClusterIP      1 => 192.168.56.11:4244 (active)   
	                                           2 => 192.168.56.12:4244 (active)   
	 7    10.110.136.116:80     ClusterIP      1 => 10.0.0.67:80 (active)         
	                                           2 => 10.0.0.28:80 (active)         
	 8    10.110.136.116:69     ClusterIP      1 => 10.0.0.67:69 (active)         
	                                           2 => 10.0.0.28:69 (active)         
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-fc74v -c cilium-agent -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                  IPv6       IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                       
	 622        Disabled           Disabled          61000      k8s:id=app3                                                                  fd02::6c   10.0.0.244   ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                       
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                     
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                              
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                      
	                                                            k8s:zgroup=testapp                                                                                           
	 779        Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s1                                                                           ready   
	                                                            k8s:node-role.kubernetes.io/control-plane                                                                    
	                                                            k8s:node.kubernetes.io/exclude-from-external-load-balancers                                                  
	                                                            reserved:host                                                                                                
	 826        Disabled           Disabled          23180      k8s:id=app1                                                                  fd02::5    10.0.0.28    ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                       
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                     
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                                         
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                      
	                                                            k8s:zgroup=testapp                                                                                           
	 881        Disabled           Disabled          4          reserved:health                                                              fd02::35   10.0.0.76    ready   
	 1424       Disabled           Disabled          23180      k8s:id=app1                                                                  fd02::b5   10.0.0.67    ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                       
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                     
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                                         
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                      
	                                                            k8s:zgroup=testapp                                                                                           
	 1938       Disabled           Disabled          17086      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system   fd02::6a   10.0.0.95    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                     
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                              
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                  
	                                                            k8s:k8s-app=kube-dns                                                                                         
	 2464       Disabled           Disabled          20717      k8s:appSecond=true                                                           fd02::8    10.0.0.60    ready   
	                                                            k8s:id=app2                                                                                                  
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                       
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                     
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app2-account                                                         
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                      
	                                                            k8s:zgroup=testapp                                                                                           
	 
Stderr:
 	 

===================== Exiting AfterFailed =====================
00:17:36 STEP: Running AfterEach for block EntireTestsuite K8sAgentFQDNTest
00:17:36 STEP: Running AfterEach for block EntireTestsuite

[[ATTACHMENT|92826f4b_K8sAgentFQDNTest_Validate_that_multiple_specs_are_working_correctly.zip]]


```
</details>

ZIP Links: 
<details><summary>Click to show.</summary>

 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-4.19//50/artifact/92826f4b_K8sAgentFQDNTest_Validate_that_multiple_specs_are_working_correctly.zip
  https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-4.19//50/artifact/d259401b_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip
  https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-4.19//50/artifact/test_results_Cilium-PR-K8s-1.25-kernel-4.19_50_BDD-Test-PR.zip
 
</details>

Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-4.19/50/

If this is a duplicate of an existing flake, comment 'Duplicate of #\<issue-number>' and close this issue.

### PR DESCRIPTION
**Pull request by jrajahalme**
Keep trying if a kubectl exec on cilium pod is killed rather than fail the test.

Fixes: #22476
Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>

### CODE REVIEW

**Comment by jrajahalme** [comment]
Note that the test for the exit code 137 is assumed to match "signal: killed" (128 + 9). Added logging to show the exit code in case this is not correct.

**Comment by jrajahalme** [comment]
`ci-eks` can't create cluster

**Review by gandro — APPROVED** [review]

**Pull request merged**
