### PR TITLE
hubble: Support --cel-expression filter in hubble observe

### PR DESCRIPTION
**Pull request by chancez**
I originally opened this PR to the hubble repo https://github.com/cilium/hubble/pull/1465 but now Hubble CLI is part of the cilium repo so I've reopened the PR here.

Implements the CLI side of https://github.com/cilium/cilium/pull/31070

### CODE REVIEW

**Comment by chancez** [comment]
Not really sure of the right release note label since we already have https://github.com/cilium/cilium/pull/31070 as a release note and this being separate is an artifact of the Hubble CLI repo being merged with cilium.

**Review by kaworu — CHANGES_REQUESTED** [review]
> Not really sure of the right release note label since we already have #31070 as a release note and this being separate is an artifact of the Hubble CLI repo being merged with cilium.

Sure let's go with `release-note/misc` for this one then. Requesting change at the patch is currently missing tests.

**Comment by chancez** [comment]
@kaworu good catch, tests added.

**Review by kaworu — APPROVED** [review]
Thanks!

**Pull request merged**
