### PR TITLE
daemon: clean up network interfaces before exit

### PR DESCRIPTION
**Pull request by nirmoy**
cilium-agent leaves cilium interfaces untouched on exit. 
Signed-off-by: Nirmoy Das <ndas@suse.de>

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
CC @joestringer I think this would cause the cilium-health sub-daemon to also try a cleanup if it exits, right?

Previously, it made sense to keep the pidfile removal local to each `.Write` invocation since cleaning up that file on any exit was the correct thing to do. @aanm pointed out that this new cleanup behaviour would leave containers unable to reach each other on cilium-exit (note that the security policy is still in effect even cilium exits, only updates would no longer happen). This cleanup would also occur when upgrading cilium-agent, causing outages :/

A CLI flag might make this behaviour less risky but, because of the upgrade scenario, it might make sense as a startup behaviour, not a shutdown one.

**Comment by joestringer** [comment]
@raybejjani that's correct. `cilium-health` daemon shutdown should not trigger this kind of cleanup.

Furthermore, as-is it looks like this would break multi-node endpoint connectivity during Cilium restart / upgrade. This needs to be done very carefully to ensure that it's only cleaning up in cases where users are very explicit that they want Cilium to stop connectivity after shutting down (which should not be the default, and should not trigger on any signal).

**Comment by nirmoy** [comment]
@raybejjani @joestringer Thanks for detail review. I am closing this PR till I come up something better.

**Comment by raybejjani** [comment]
sorry @nirmoy :( One smaller step that might accomplish some of the same goals would be to make these steps a separate script we include in the repo and in our releases. This script can then be called when needed, perhaps by the supervisor for that system (e.g. systemd in those cases, or perhaps a configuration changer like chef/puppet). Also check out [`cilium cleanup`](http://cilium.readthedocs.io/en/latest/cmdref/cilium_cleanup/), it might be a reasonable place to add this (especially if you would also want to clear out the cilium-agent state in the same circumstances as the net cleanup)

**Comment by nirmoy** [comment]
@raybejjani I missed out about cilium cleanup, that solves my problem :) Thanks for pointing me

**Pull request closed without merging**
