### PR TITLE
v1.6 backports 2020-07-01

### PR DESCRIPTION
**Pull request by jrajahalme**
* #10564 -- test: Update Istio integration to release 1.5.0 (@jrajahalme)
 * #10730 -- test: Update Istio integration to release 1.5.1 (@jrajahalme)
 * #10851 -- istio: Use cilium-istioctl instead of helm directly (@jrajahalme)
 * #11280 -- Istio: Update to release 1.5.2 (@jrajahalme)
 * #11530 -- istio: Update to 1.5.4 (@jrajahalme)
 * #11905 -- test: Skip Istio test if Ginkgo runs on unsupported runtime. (@jrajahalme)
 * #11993 -- test: Add retries to curl command (@christarazi)
 * #12109 -- test: Download correct cilium-istioctl for the executing OS. (@jrajahalme)
 * #12214 -- istio: Update to 1.5.6 (@jrajahalme)
 * #12248 -- iptables: Remove '--nowildcard' from socket match (@jrajahalme)
 * #12353 -- istio: Update to 1.5.7 (@jrajahalme)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10564 10730 10851 11280 11530 11905 11993 12109 12214 12248 12353; do contrib/backporting/set-labels.py $pr done 1.6; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-backport-1.6

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@jrajahalme it seems the failures were related with the changes from the PR:
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.14-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:420
Unable to create resource "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v2-istio.yaml"
Expected command: kubectl create -f  /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v2-istio.yaml 
To succeed, but it failed:
Exitcode: 1 
Stdout:
 	 
Stderr:
 	 error: the path "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v2-istio.yaml" does not exist
	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.14-gopath/src/github.com/cilium/cilium/test/k8sT/istio.go:289
```

**Comment by jrajahalme** [comment]
test-backport-1.6

**Comment by joestringer** [comment]
Hit known flake https://github.com/cilium/cilium/issues/11895.

**Pull request merged**
