### PR TITLE
Add cilium_egress_v4 to ignoredELFPrefixes

### LINKED ISSUE #16277: Skipping symbol substitution cilium_egress_v4
Reported by mikek on Slack:
```
level=warning msg="Skipping symbol substitution" subsys=elf symbol=cilium_egress_v4
```
We need to add `cilium_egress_v4` to `ignoredELFPrefixes`.

### PR DESCRIPTION
**Pull request by Divya063**
Fixes: #16277
Signed-off-by: Divya Rani ranidivya063@gmail.com

### CODE REVIEW

**Comment by ti-mo** [comment]
Hi @Divya063, thanks for the patch. Could you add a short description of the change to the commit message? A GH issue link is not very useful.

@pchaigno https://github.com/cilium/cilium/issues/16277 doesn't contain much context. Does this cause any impact, or is it really just a warning?

**Comment by pchaigno** [comment]
> @pchaigno #16277 doesn't contain much context. Does this cause any impact, or is it really just a warning?

It only causes a warning.

**Comment by ti-mo** [comment]
@Divya063 This should be good to go with a slightly more detailed commit message.

**Review by ti-mo — APPROVED** [review]
Thank you!

**Pull request merged**
