### PR TITLE
policy: Connection-based toFQDNs IP expiration

### PR DESCRIPTION
**Pull request by raybejjani**
Connections can outlive the DNS query that allowed them via toFQDNs
policies. We previously papered over this with a very high (1 week)
--tofqdns-min-ttl value. Mixed workloads where some connections are
long-lived and others are short-lived strain this model as the
short-lived connections' DNS cache entries accumulate.
We can consider the current state of the connection tracking table when
retiring IPs from the toFQDNs caches. We rely on the normal CT GC to
traverse the connections, and accumulate this information on each
endpoint. When expiring DNS cache entries, IPs that are still in-use and
are allowed due to a toFQDNs policy will not expire but continue being
used by toFQDNsSelectors until the connection is closed, or the selector
is deleted (via a policy change).

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9452)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by tgraf** [comment]
@raybejjani Can this be closed?

**Comment by raybejjani** [comment]
Actually done in https://github.com/cilium/cilium/pull/9497

**Pull request closed without merging**
