### PR TITLE
[v1.7] Extend FQDN test to validate DNS proxy during restart

### PR DESCRIPTION
**Pull request by christarazi**
See commit msgs.

We can consider forward-porting this to newer branches + `master`, if deemed valuable.

Follow up from https://github.com/cilium/cilium/pull/12718 and
https://github.com/cilium/cilium/pull/12731

### CODE REVIEW

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
test-backport-1.7

**Review by tklauser — APPROVED** [review]
Would be nice to forward port this to `master` (and maybe then backport to `v1.8`).

Jenkins CI failures look unrelated.

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by christarazi** [comment]
test-backport-1.7

**Pull request merged**
