### PR TITLE
bpf: use double word for v6 addr copy and comparison

### PR DESCRIPTION
**Pull request by borkmann**
Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7680)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Review by jrfastab — APPROVED** [review]
Looks good to me its going to conflict with my encryption rolling key fix PR but lets see which one lands first.

**Comment by borkmann** [comment]
> Looks good to me its going to conflict with my encryption rolling key fix PR but lets see which one lands first.

Lets land your PR first, of course.

**Review by joestringer — APPROVED** [review]

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
provision failed, retesting

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Provision failure:
```
[K==> k8s2-1.14: Matching MAC address for NAT networking...
10:39:38  ==> k8s2-1.14: Checking if box 'cilium/ubuntu' version '150' is up to date...
10:39:39  ==> k8s2-1.14: Setting the name of the VM: test_k8s2-114_1557398378845_51439
10:39:39  ==> k8s2-1.14: Fixed port collision for 22 => 2222. Now on port 2202.
10:39:40  ==> k8s2-1.14: Clearing any previously set network interfaces...
10:39:40  ==> k8s2-1.14: Preparing network interfaces based on configuration...
10:39:40      k8s2-1.14: Adapter 1: nat
10:39:40      k8s2-1.14: Adapter 2: intnet
10:39:40      k8s2-1.14: Adapter 3: hostonly
10:39:40  ==> k8s2-1.14: Forwarding ports...
10:39:40      k8s2-1.14: 22 (guest) => 2202 (host) (adapter 1)
10:39:40  ==> k8s2-1.14: Running 'pre-boot' VM customizations...
10:39:40  ==> k8s2-1.14: Booting VM...
10:39:41  ==> k8s2-1.14: Waiting for machine to boot. This may take a few minutes...
10:39:41      k8s2-1.14: SSH address: 127.0.0.1:2202
10:39:41      k8s2-1.14: SSH username: vagrant
10:39:41      k8s2-1.14: SSH auth method: private key
10:39:54  The guest machine entered an invalid state while waiting for it
10:39:54  to boot. Valid states are 'starting, running'. The machine is in the
10:47:27  'paused' state. Please verify everythingwrapper script does not seem to be touching the log file in /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated@tmp/durable-adf493a6
10:47:27  (JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
10:47:27  Cannot contact jenkins-fixed-new-1: java.io.IOException: No space left on device
10:52:32  wrapper script does not seem to be touching the log file in /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated@tmp/durable-adf493a6
10:52:32  (JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
10:57:38  wrapper script does not seem to be touching the log file in /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated@tmp/durable-adf493a6
```

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Pull request merged**
