### PR TITLE
endpoint: do not export `Status` field

### PR DESCRIPTION
**Pull request by ianvernon**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9068)

### CODE REVIEW

**Comment by ianvernon** [comment]
Health-status check failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14703/testReport/junit/Suite-k8s-1/11/K8sHealthTest_checks_cilium_health_status_between_nodes/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Checkout failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14722/execution/node/29/log/

**Comment by ianvernon** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Review by raybejjani — APPROVED** [review]

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
