### PR TITLE
bpf: Ignore HOST_ID resolved from ipcache for IPv6 case

### PR DESCRIPTION
**Pull request by ysksuzuki**
This PR adds the check to ignore HOST_ID resolved from ipcache for IPv6 case. resolve_srcid_ipv6 should ignore the HOST_ID resolved from ipcache because the packets marked MARK_MAGIC_HOST actually be from the host.

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

```release-note
Fix IPv6 policy enforcement for SNATed traffic from the Host
```

### CODE REVIEW

**Review by aspsk — APPROVED** [review]

**Review by borkmann — APPROVED** [review]
lgtm and in line with resolve_srcid_ipv4

**Comment by joestringer** [comment]
Several of the GitHub-based workflows did not automatically trigger for some reason. Given this affects the IPv6 path, I have attempted to trigger the verifier test, but I suspect that the other awscni / eks / external-workloads / multicluster tests do not configure IPv6. The failing tests are not marked as required due to test case instability.

**Comment by joestringer** [comment]
Thanks for the fix @ysksuzuki !

**Pull request merged**
