### PR TITLE
cmd/policy: Close file descriptor if required

### PR DESCRIPTION
**Pull request by jiuker**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

close file fd

Fixes: None

```release-note
cmd/policy: Close file descriptor if required
```

### CODE REVIEW

**Comment by squeed** [comment]
Two things: can you properly set the labels?

And, secondly, rather than doing a type assertion, I'd suggest something like this:

```go
fp, err := os.Open(path)
if err != nil {
	return nil, err
}
defer fp.Close()
r = fp
```

**Review by squeed — CHANGES_REQUESTED** [review]
Two things: can you properly set the labels?

And, secondly, rather than doing a type assertion, I'd suggest something like this:

```go
fp, err := os.Open(path)
if err != nil {
	return nil, err
}
defer fp.Close()
r = fp
```

**Comment by jiuker** [comment]
> Two things: can you properly set the labels?
> 
> And, secondly, rather than doing a type assertion, I'd suggest something like this:
> 
> ```go
> fp, err := os.Open(path)
> if err != nil {
> 	return nil, err
> }
> defer fp.Close()
> r = fp
> ```

1.I don't have permission to modify pr's label
2.I have modified this pr like you requested

**Review by squeed — APPROVED** [review]

**Comment by squeed** [comment]
> 1.I don't have permission to modify pr's label

**Comment by sayboras** [comment]
Conformance GatewayAPI failure is due to lack of rebase with master. Reviews are in, all CI jobs are good.

Marking this ready to merge.

**Pull request merged**
