### PR TITLE
Backport: Don't failfast on branch V1.0

### PR DESCRIPTION
**Pull request by eloycoto**
Don't Failfast in the 1.0 tests.

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by eloycoto** [comment]
test-me-please

**Comment by ianvernon** [comment]
[Build failed](https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/2544/) due to VirtualBox fun:
```
17:14:37 [Cilium-PR-Ginkgo-Tests-Validated@2] Running shell script
17:14:38 + cd /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated@2/src/github.com/cilium/cilium/test
17:14:38 + K8S_VERSION=1.10 vagrant up --no-provision
17:14:38 Bringing machine 'runtime' up with 'virtualbox' provider...
17:14:39 Bringing machine 'k8s1-1.10' up with 'virtualbox' provider...
17:14:39 Bringing machine 'k8s2-1.10' up with 'virtualbox' provider...
17:14:39 ==> runtime: Checking if box 'cilium/ubuntu' is up to date...
17:14:48 ==> runtime: Machine not provisioned because `--no-provision` is specified.
17:14:48 ==> k8s1-1.10: Checking if box 'cilium/ubuntu' is up to date...
17:14:49 ==> k8s1-1.10: Machine not provisioned because `--no-provision` is specified.
17:14:51 ==> k8s2-1.10: Checking if box 'cilium/ubuntu' is up to date...
17:14:52 ==> k8s2-1.10: Clearing any previously set forwarded ports...
17:14:54 There was an error while executing `VBoxManage`, a CLI used by Vagrant
17:14:54 for controlling VirtualBox. The command and stderr is shown below.
17:14:54 
17:14:54 Command: ["modifyvm", "cb76074f-ecc0-4c25-99a4-a66cf537f24c", "--natpf1", "delete", "ssh"]
17:14:54 
17:14:54 Stderr: VBoxManage: error: The machine 'test_k8s2-110_1524150607827_67331' is already locked for a session (or being unlocked)
17:14:54 VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
17:14:54 VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 525 of file VBoxManageModifyVM.cpp
```

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
