### PR TITLE
v1.5 backport 19-16-04

### PR DESCRIPTION
**Pull request by jrfastab**
PRs:
#7733
#7727
#7738
#7739 

All backports were clean.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7754)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-docs-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
