### PR TITLE
pkg/metrics: Remove source node label

### PR DESCRIPTION
**Pull request by aditighag**
See commits description.

### CODE REVIEW

**Review by joestringer — APPROVED** [review]
LGTM thanks!

**Review by sayboras — APPROVED** [review]
oops, my bad 💯

**Review by tommyp1ckles — APPROVED** [review]
lgtm

**Comment by aanm** [comment]
@aditighag I've added the `needs-backport/1.11` and `needs-backport/1.12` labels since the original PR is also meant to be backported to those branches. Please remove the labels if it is not intended.

**Pull request merged**
