### PR TITLE
lbmap: check backend number before delete maglev element

### PR DESCRIPTION
**Pull request by ChenYahui2019**
to delete a frontend which don't have any backend will return err,
root cause is maglev table didn't update when upsert service.

Signed-off-by: chenyahui <chenyahui9@jd.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Comment by borkmann** [comment]
Thanks for the fix, could you also add a commit description to describe the issue and e.g. how it was reproduced?

**Comment by ChenYahui2019** [comment]
> 

done

**Review by borkmann — APPROVED** [review]

**Comment by borkmann** [comment]
(cc @brb for visibility)

**Comment by brb** [comment]
> how it was reproduced?

@ChenYahui2019 Thanks for your fix! Do you have an explanation how you ended hitting the bug?

**Comment by brb** [comment]
@ChenYahui2019 friendly ping regarding:
> Do you have an explanation how you ended hitting the bug?

**Comment by brb** [comment]
Changing it to draft until we have the answer to https://github.com/cilium/cilium/pull/18452#issuecomment-1016537444

**Comment by ChenYahui2019** [comment]
> > how it was reproduced?
> 
> @ChenYahui2019 Thanks for your fix! Do you have an explanation how you ended hitting the bug?

Thx for the warning.

Backens number will be checked before calling `UpsertMaglevLookupTable` when `UpsertService`.
For the same reason, backends number should be checked befor calling `deleteMaglevTable` when `DeleteService`, otherwise, `deleteMaglevTable` will return error if the the backends number is zero.

**Comment by brb** [comment]
@ChenYahui2019 Do you plan to revive the PR?

**Comment by brb** [comment]
Closing in favor of https://github.com/cilium/cilium/pull/20625.

**Pull request closed without merging**
