### PR TITLE
v1.7 backport 2020-03-16

### PR DESCRIPTION
**Pull request by gandro**
v1.7 backports 2020-03-16

 * #10262 -- [CI] Replace jenkinsfiles with symlinks (@nebril)
 * #10377 -- Improve pod restarts on GKE (@ap4y)
 * #10480 -- docs: fix bird dashboard image scale (@aanm)
 * #10481 -- test: Fix possible race in waitForNPods helper function (@brb)
 * #10482 -- cni: fix interface sandbox in cmdAdd return value (@jaffcheng)
 * #10351 -- Fix eks restart pods helm (@tom-hadlaw-hs)
 * #10476 -- Docs: Implements Documentation to install Cilium on k3s (@seanmwinn)
 * #10508 -- Docs: Add step for mounting bpf filesystem on k3s installations (@seanmwinn)
 * #10515 -- Helm-charts: Fix the values.yaml comment that was misleading (@soumynathan)
 * #10479 -- doc: Improve deployment section (@errordeveloper)
 * #10519 -- docs: Update SIG meeting notes (@joestringer)
 * #10526 -- bpf: do not drop unknown protos in nat handling (@borkmann)
 * #10536 -- docs: Clarify wording for cluster and init entities (@joestringer)
 * #10554 -- pkg/monitor: Add missing drop reasons (@Frankkkkk)
 * #10550 -- docs: A few cosmetic improvements in GKE guide (@errordeveloper)
 * #10579 -- doc: Upgrade MarkupSafe to 1.1.1 (@mrostecki)
 * #10564 -- test: Update Istio integration to release 1.5.0 (@jrajahalme)

*Resolved Conflicts*

  * #10262 (@nebril)

    - The `CODEOWNERS` change (commit fc15d0cf3d5f0f81aefc8f5c9ac51bcd7bac025b) has not been backported, as stable branches do not contain the full `CODEOWNERS` file.
   
  * #10476 (@seanmwinn) & #10479 (@errordeveloper)

    - Trivial conflicts in doc changes.

**Unresolved Conflicts**

The following PRs have been skipped in this backport PR:

 * #10390 -- test: Avoid panics due to dereferencing a nil error (@jrajahalme)
 
    -  Unapplicable. It is dependent on code changes and might not need a backport (see https://github.com/cilium/cilium/pull/10390#issuecomment-599561908)
 
 * #10184 -- Add apiserver heartbeat with conntrack (@tom-hadlaw-hs)
 
    - Multiple merge conflicts. PR description says needs additional testing  before backport, therefore skipped for now (this PR has already enough commits as is).

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10262 10377 10480 10481 10482 10351 10476 10508 10515 10479 10519 10526 10536 10554 10550 10579 10564; do contrib/backporting/set-labels.py $pr done 1.7; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10591)

### CODE REVIEW

**Comment by gandro** [comment]
never-tell-me-the-odds

**Comment by joestringer** [comment]
Jenkins run failed provisioning, ran out of space on jenkins-node-16:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/17927/

```
09:08:31  /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:203:in `close': No space left on device @ fptr_finalize_flush - /root/.vagrant.d/data/fp-leases/127_0_0_1_2222 (Errno::ENOSPC)
```

**Comment by joestringer** [comment]
test-me-please

**Comment by gandro** [comment]
k8s tests hit https://github.com/cilium/cilium/projects/85#card-32888586

**Comment by gandro** [comment]
test-missed-k8s

**Comment by gandro** [comment]
gingko tests also hit https://github.com/cilium/cilium/projects/85#card-32888586 :thinking:

**Comment by gandro** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Do you want any specific review before merging? It seemed pretty straightforward to me.

**Comment by gandro** [comment]
> Do you want any specific review before merging? It seemed pretty straightforward to me.

Thanks! I was mostly interested in feedback/opinions regarding the omitted commits. I think I'll ping the relevant folks privately.

**Review by aanm — APPROVED** [review]
All good for my commit

**Pull request merged**
