### PR TITLE
.github/workflows: bump v1.10 workflows to cilium-cli v0.10.5

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Review by jibi — APPROVED** [review]

**Comment by michi-covalent** [comment]
i'll look into these failures

**Comment by michi-covalent** [comment]
/ci-awscni-1.10

**Review by joestringer — APPROVED** [review]

**Comment by michi-covalent** [comment]
testing the change against v1.10 branch here => https://github.com/cilium/cilium/pull/19906

**Review by sayboras — APPROVED** [review]

**Comment by jibi** [comment]
Changes were tested on a branch based on v1.10 :heavy_check_mark:

**Pull request merged**
