### PR TITLE
Vagrant Update base box to 131

### PR DESCRIPTION
**Pull request by eloycoto**
Got Ian commit and apply some changes. 

Fix https://github.com/cilium/packer-ci-build/issues/116

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7096)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by brb** [comment]
Got hit by the same issue with the latest ubuntu-next.

**Review by brb — APPROVED** [review]

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by ianvernon** [comment]
The unit tests passed fine, but Coveralls failed:
```
make[1]: Leaving directory `/home/travis/gopath/src/github.com/cilium/cilium'
Bad response status from coveralls: 422
{"message":"Couldn't find a repository matching this job.","error":true}
travis_time:end:09af9f78:start=1550507575566829998,finish=1550508001092656763,duration=425525826765
[0K[31;1mThe command "./.travis/build.sh" exited with 1.[0m
```

**Comment by ianvernon** [comment]
Unit test failures are unrelated - the PR is only for updating the VM version, which the Travis CI does not run in. Given that build passed with the VM version being updated, the fix is self-evident, so am merging.

**Review by ianvernon — COMMENTED** [review]
I forgot to officially 'approve' this as a member of the cilium/vagrant group, so consider this my approval ;)

**Pull request merged**
