### PR TITLE
README: update security releases

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Review by rolinh — CHANGES_REQUESTED** [review]
I think versions should be bumped in `SECURITY.md` as well.

**Comment by aanm** [comment]
> I think versions should be bumped in `SECURITY.md` as well.

It's the first time I'm seeing this file :D

**Review by rolinh — APPROVED** [review]

**Review by fristonio — APPROVED** [review]
:tada: :rocket:

**Comment by joestringer** [comment]
Github UI messed up when I tried to merge, will fix in a moment.

**Pull request merged**
