### PR TITLE
bpf: nodeport cleanups

### PR DESCRIPTION
**Pull request by julianwiedmann**
Some easy cleanups in the nodeport code, to shrink down my feature branch.

### CODE REVIEW

**Comment by julianwiedmann** [comment]
@borkmann does the last patch ring any bells?

**Review by ldelossa — APPROVED** [review]
Changes LGTM.

**Review by YutaroHayakawa — APPROVED** [review]
LGTM

**Comment by borkmann** [comment]
> @borkmann does the last patch ring any bells?

It's been a while, but did you manually test that vxlan and geneve works fine pod to remote pod via tunnel? Did you check each drivers if there's special logic around L2 handling?

**Comment by julianwiedmann** [comment]
> > @borkmann does the last patch ring any bells?
> 
> It's been a while, but did you manually test that vxlan and geneve works fine pod to remote pod via tunnel? Did you check each driver if there's special logic around L2 handling?

CI has pod-to-pod coverage for both vxlan and geneve, so no worries about the good path.

Poked around a bit in `geneve.ko` and `vxlan.ko`, but nothing caught my eye. Think that if there's any fallout, it most likely would be in GRO ...?
There's even a few optional things that might work "better" with proper inner L2 addresses (eg. `VXLAN_F_LEARN`).

**Pull request merged**
