### PR TITLE
Unset `ImageReference` when updating Azure VMSS

### LINKED ISSUE #19695: IPAM errors cause rate limiting in Azure
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The `cilium-operator` produces warnings such as these:
```
Unable to assign additional IPs to interface, will create new interface
```
With error:
```
unable to update virtualmachinescaleset: compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=0 -- Original Error: Code=\"LinkedAuthorizationFailed\" Message=\"The client has permission to perform action 'Microsoft.Compute/galleries/images/versions/read' on scope '/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Compute/virtualMachineScaleSets/<vmss>/virtualmachines/1', however the current tenant '<tenant-id>' is not authorized to access linked subscription '109a5e88-712a-48ae-9078-9ca8b3c81345'.\"
```

This has two consequences:
1. Cilium is unable to pre-allocate IPs, so we are limited to the IPs provisioned via the Azure CNI's `max_pods` parameter used when creating the cluster
2. The repeated attempts to allocate IPs result in large numbers of requests to Azure's VMSS API, which eventually results in rate limiting for Cilium and other services which use the API (such as Terraform and the controller responsible for provisioning volumes).

### Cilium Version

Client: 1.10.9-cee.2 aa267b8 2022-03-31T16:32:08+00:00 go version go1.16.15 linux/amd64
Daemon: 1.10.9-cee.2 aa267b8 2022-03-31T16:32:08+00:00 go version go1.16.15 linux/amd64

### Kernel Version

5.4.0-1074-azure #77~18.04.1-Ubuntu SMP Wed Mar 30 15:36:02 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.21.9

### Sysdump

_No response_

### Relevant log output

```shell
level=warning msg="Unable to assign additional IPs to interface, will create new interface" error="unable to update virtualmachinescaleset: compute.VirtualMachineScaleSetVMsClient#Update: Failure sending request: StatusCode=0 -- Original Error: Code=\"LinkedAuthorizationFailed\" Message=\"The client has permission to perform action 'Microsoft.Compute/galleries/images/versions/read' on scope '/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Compute/virtualMachineScaleSets/<vmss>/virtualmachines/1', however the current tenant '<tenant-id>' is not authorized to access linked subscription '109a5e88-712a-48ae-9078-9ca8b3c81345'.\"" instanceID=/subscriptions/<subscription-id>/resourcegroups/<resource-group>/providers/microsoft.compute/virtualmachinescalesets/<vmss>/virtualmachines/1 ipsToAllocate=2 name=<vmss> selectedInterface=/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Compute/virtualMachineScaleSets/<vmss>/virtualMachines/1/networkInterfaces/<interface> subsys=ipam
```

## Cause

This appears to relate to https://github.com/Azure/AKS/issues/1819, which was raised following an Azure update to AKS so that some clusters use base images from a shared gallery in the `109a5e88-712a-48ae-9078-9ca8b3c81345` subscription, an Azure-owned subscription which normal subscribers don't have access to.  Because this subscription is now included in the `storageProfile.imageReference` property of returned VMSS instances, it caused issues for the CLI, which was performing updates by `GET`ting the instance, modifying a property then `PUT`ting it back - since the subscription ID is included in the `PUT` payload, a permissions check is triggered against the Azure-owned subscription which results in an error.

The resolution is to either use `PATCH` instead of `PUT`, to only modify the properties you're interested in, or to remove the `storageProfile.imageReference` property from the JSON payload sent in the `PUT` request.

`cilium-operator` appears to [`GET`](https://github.com/cilium/cilium/blob/1.10.8/pkg/azure/api/api.go#L391) the instance, add the additional IPs it wants to allocate, then [`PUT`](https://github.com/cilium/cilium/blob/1.10.8/pkg/azure/api/api.go#L435) the instance back, using the [`azure-sdk-for-go`](https://github.com/Azure/azure-sdk-for-go/tree/v54.0.0/) module's [`update`](https://github.com/Azure/azure-sdk-for-go/blob/v54.0.0/services/compute/mgmt/2021-03-01/compute/virtualmachinescalesetvms.go#L1318) function.

A fix could be for the `cilium-operator` to `nil` the `StorageProfile` in the result returned from the `GET` request before using the value in the `PUT` request.

## Mitigation

The rate-limiting element of this issue can be mitigated by preventing Cilium from attempting to pre-allocate IPs.

We couldn't find a way to disable this behaviour directly, but were able to prevent it by setting the Cilium's `ipam.pre-allocate` parameter and the AKS `max_pods` parameters such that the number of IPs allocated by the Azure CNI before it's replaced by Cilium is sufficient for the number of pods that will run on the cluster - so `<number of IPs required> + ipam.pre-allocate <= max_pods`.

Unfortunately, setting `ipam.pre-allocate` to `0` results in the default `8` being set, so the lowest this can be set to is `1`.  You can do this with the following `cni-configuration` config map:
```
apiVersion: v1
kind: ConfigMap
data:
  cni-config: |
    {
      "cniVersion": "0.3.1",
      "name": "cilium",
      "plugins": [
        {
          "cniVersion": "0.3.1",
          "type": "cilium-cni",
          "ipam": {
            "pre-allocate": 1
          }
        }
      ]
    }
```

## Related issues

It could be that this issue is what caused the high number of `cilium-operator` requests described in #16206 - we were experiencing similar issues until implementing the mitigation described above.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by andrew-bulford-form3**
This is to avoid 403 errors when updating an Azure VMSS instance to assign additional IP addresses.

The 403 can occur as the result of a permissions check when the image reference contains a subscription ID which the service principal making the request doesn't have access to, which is the case for Azure Compute Gallery images, as they contain an Azure-owned subscription ID.

Unsetting this property doesn't affect the instance, it just tells Azure that we don't want to change the value.

Fixes: #19695

Signed-off-by: Andrew Bulford <andrew.bulford@form3.tech>

```release-note
Fix Azure IPAM 403 errors for Azure instances using Azure Compute Gallery images
```

### CODE REVIEW

**Review by ti-mo — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.16-4.9

**Comment by pchaigno** [comment]
The k8s-1.16-kernel-4.9 flake is unrelated as it happened in other PRs and is unrelated to the changes in this PR. Other tests are passing and changes are reviewed. Marking ready to merge.

**Comment by samuel-form3** [comment]
Thanks ❤️

**Pull request merged**
