### PR TITLE
Add Rancher Labs to Cilium users

### PR DESCRIPTION
**Pull request by divya-mohan0209**
Signed-off-by: Divya Mohan ([divya.mohan0209@gmail.com](mailto:divya.mohan0209@gmail.com))

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Adding Rancher labs to Cilium users

### CODE REVIEW

**Comment by pchaigno** [comment]
Thanks for the pull request! As per MLH's comment above, we'll need a sign-off on the commit and then we should be good to merge.

**Comment by divya-mohan0209** [comment]
@pchaigno : I have added the signed-off-by in the commit above as part of the description, not sure if I need to do something else.

**Comment by xmulligan** [comment]
@divya-mohan0209 you added it to the PR comment, but not the commit itself. The easiest way to fix this is to amend the commit and add your sign off there https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/amending-a-commit

**Comment by divya-mohan0209** [comment]
Thank you @xmulligan & @pchaigno , that worked! Hopefully y'all can provide a sign-off once the tests sign it off okay.

**Review by xmulligan — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]

**Pull request merged**
