### PR TITLE
v1.13 Backports 2024-07-08

### PR DESCRIPTION
**Pull request by jibi**
* [x] #33509 (@julianwiedmann)
 * [x] #33512 (@jasonaliyetti) :warning: resolved conflicts
 * [x] #33551 (@julianwiedmann) :warning: resolved conflicts

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33509 33512 33551
```

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]

**Comment by jibi** [comment]
/test-backport-1.13

**Review by aanm — APPROVED** [review]

**Comment by jibi** [comment]
(rebased and fixed the backport note on all commit messages)

**Comment by jibi** [comment]
/test-backport-1.13

**Comment by jibi** [comment]
/test-1.17-4.19

**Comment by jibi** [comment]
/test-1.22-4.19

**Comment by jibi** [comment]
/test-1.21-4.19

**Review by aditighag — APPROVED** [review]

**Comment by jibi** [comment]
/test-1.17-4.19

**Comment by jibi** [comment]
seems like an infra issue for 1.17 on 4.19:

```
18:24:11      k8s1-1.17: 	[ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.4.3-0: output: Error response from daemon: Head "https://k8s.gcr.io/v2/etcd/manifests/3.4.3-0": unable to decode token response: invalid character '<' looking for beginning of value
```

**Comment by jibi** [comment]
/test-1.17-4.19

**Review by christarazi — APPROVED** [review]

**Comment by jibi** [comment]
/test-1.17-4.19

**Comment by jibi** [comment]
/test-1.17-4.19

**Pull request merged**
