### PR TITLE
v1.6 backports 19-07-25

### PR DESCRIPTION
**Pull request by ianvernon**
* #8663 -- minor follow-up improvements and fixes in nat engine (@borkmann)
 * #8676 -- bpf: initial docs for getting started on host reachable services (@borkmann)
 * #8684 -- docs: Remove confusing mentioning of etcd server in ConfigMap (@brb)
 * #8681 -- docs: Add NodePort GSG (@brb)
 * #8670 -- datapath: Store NodePort client MAC addr in LRU map (@brb)
 * #8643 -- Gopkg: update etcd library to v3.3.13 (@aanm)
 * #8673 -- test: Fix etcd-operator readiness check (@joestringer)

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 8663 8676 8684 8681 8670 8643 8673; do contrib/backporting/set-labels.py $pr done 1.6; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8695)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
previous failure https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13889/

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
@ianvernon it seems the a commit from this PR brakes the test as it failed 2 times in a row.

**Comment by ianvernon** [comment]
The following PR's may have broken the CI:

• #8663 -- minor follow-up improvements and fixes in nat engine (@borkmann)
• #8676 -- bpf: initial docs for getting started on host reachable services (@borkmann)
• #8670 -- datapath: Store NodePort client MAC addr in LRU map (@brb)
• #8643 -- Gopkg: update etcd library to v3.3.13 (@aanm)
• #8673 -- test: Fix etcd-operator readiness check (@joestringer)

**Comment by ianvernon** [comment]
Previous failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13909/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
I don't believe that these above failures are strictly related to the PR - the v1.6 CI has been a bit unstable :( https://jenkins.cilium.io/view/Cilium-v1.6/job/cilium-v1.6-standard/

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
