### PR TITLE
k8s: update k8s libraries to 1.19.4

### PR DESCRIPTION
**Pull request by aanm**
Also update k8s test versions to 1.17.14 and 1.18.12

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-backport-1.9

**Comment by aanm** [comment]
test-backport-1.9

**Review by fristonio — APPROVED** [review]
LGTM :rocket: :tada:

**Comment by aanm** [comment]
retest-4.19

**Review by christarazi — APPROVED** [review]

**Pull request merged**
