### PR TITLE
v1.11 backports 2023-02-23

### PR DESCRIPTION
**Pull request by sayboras**
- [x] #23706 -- Fix RKE doc link (@raphink)
 - [ ] #23669 -- docs: replace usage of api.twitter.com (@kaworu). _Updated: I have manually double checked this PR :heavy_check_mark:_
 - [x] #23728 -- Remove / in RKE doc link as it causes redirect bug (@raphink)
 - [ ] #23713 -- ipam/crd: Fix panic due to concurrent map read and map write (@gandro). _Updated: I have manually double checked this PR :heavy_check_mark:_
 - [x] #23740 -- workflow: fixes LLVM, Clang cache and install path (@brlbil). _Small conflict_
 - [x] #23787 -- agent: fix incorrect deletion of veth host interfaces on bootstrap (@giorio94)
 - [x] #23857 -- Fix connectivity issue upon agent restart in case of ipv6 + direct routing + KPR replacement (@giorio94)
 - [x] #23800 -- envoy: Bump envoy to 1.23.4 (@sayboras)
 - [x] #23904 -- fix(deps): update module golang.org/x/net to v0.7.0 [security] (master) (@renovate[bot])

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 23706 23669 23728 23713 23740 23787 23857 23800 23904; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.11

**Review by giorio94 — APPROVED** [review]
My commits look good. Thanks!

**Review by raphink — APPROVED** [review]
RKE docs LGTM

**Review by brlbil — APPROVED** [review]
Workflow changes LGTM, Thanks.

**Review by tklauser — APPROVED** [review]
LGTM, thanks.

**Comment by sayboras** [comment]
/test-1.20-4.9

**Review by aanm — APPROVED** [review]

**Comment by sayboras** [comment]
All CI passes, most of reviews are in, merging this after double check two pending PRs.

**Pull request merged**
