### PR TITLE
v1.10: Update Go to 1.16.5

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
test-backport-1.10

**Comment by tklauser** [comment]
test-1.21-4.9

**Review by aanm — APPROVED** [review]

**Comment by nathanjsweet** [comment]
Sorry for the conflict, but #16384 took precedence.

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-1.19-5.4

**Comment by tklauser** [comment]
test-runtime

**Comment by tklauser** [comment]
test-1.21-4.9

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-backport-1.10

**Comment by tklauser** [comment]
test-runtime

previous failure due to Jenkins issues, it seems: https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/4924/

**Comment by tklauser** [comment]
test-1.16-netnext

previous failure: #13839 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/730/

**Comment by tklauser** [comment]
test-1.18-4.9

hit #15630 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.18-kernel-4.9/1659/

**Comment by tklauser** [comment]
test-1.19-5.4

previous failure: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-5.4/305/

**Comment by tklauser** [comment]
test-1.16-netnext

**Comment by tklauser** [comment]
test-1.18-4.9

**Comment by tklauser** [comment]
test-1.19-5.4

**Comment by tklauser** [comment]
test-1.16-netnext

**Review by joestringer — APPROVED** [review]

**Pull request merged**
