### PR TITLE
Remove tests/ and examples/demo/

### PR DESCRIPTION
**Pull request by brb**
See commit msgs.

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]
Some of the changes in patch 3 (`tests`->`test/envoy` in Documentation, .gitignore, .dockerignore) would logically belong to patch 2 instead I think, but that's very minor and not blocking.

Looks good to me.

**Review by nathanjsweet — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
ci-aks failed to due potential connectivity issues:
```
Error: Unable to install Cilium: unable to execute "az ad sp create-for-rbac --scopes /subscriptions/986ec55c-1e77-4e2e-9ca5-dcbb34c7a110/resourceGroups/MC_cilium-cilium-1074187775_cilium-cilium-1074187775_westeurope --output json --only-show-errors": exit status 1
 ERROR: Please ensure you have network connection. Error detail: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
 ```

**Comment by brb** [comment]
net-next hit:
- https://github.com/cilium/cilium/issues/16399
- https://github.com/cilium/cilium/issues/16971
:eyes:

**Comment by brb** [comment]
test-1.16-netnext

**Review by vadorovsky — APPROVED** [review]

**Pull request merged**
