### PR TITLE
Backport 18-04-27

### PR DESCRIPTION
**Pull request by nebril**

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
Both of backported prs share the same commit, that's why this PR has only two of them (instead of 3)

**Comment by raybejjani** [comment]
ooh, the power of git's merger!

**Review by raybejjani — APPROVED** [review]

**Comment by jrajahalme** [comment]
@raybejjani It was exactly the same commit that they shared, maybe that helped :-)

**Pull request merged**
