### PR TITLE
Test: Core-dns fix log issues

### PR DESCRIPTION
**Pull request by eloycoto**
On provision Coredns the configMap provided by kubeadm does not have the
`k8s-app=kube-dns` so the configMap was not updated when apply the new
one.

With this change we deleted all resources related to the *-DNS and
install the new ones from scratch.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4957)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
Microscope issue:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5220/

**Comment by eloycoto** [comment]
test-me-please

**Comment by ianvernon** [comment]
@eloycoto I can merge this if you are comfortable doing so since the issue that failed the tests is a known flake.

**Pull request merged**
