### PR TITLE
Optimize memory consumption of agent

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6464)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
LGTM.

Should we also add `monitor-queue-size` to the DS YAML to define the env variable if the option is specified in the config-map? I guess if it's considered an advanced user option then perhaps we don't need to.

**Comment by ianvernon** [comment]
@tgraf the CI failed with a `panic found in logs` error:

```
2018-12-17T17:30:21.046062287Z panic: runtime error: slice bounds out of range
2018-12-17T17:30:21.046091741Z 
2018-12-17T17:30:21.046187204Z goroutine 1 [running]:
2018-12-17T17:30:21.046265595Z main.(*Daemon).regenerateRestoredEndpoints(0xc00038e960, 0xc000b2c990)
2018-12-17T17:30:21.046339755Z 	/go/src/github.com/cilium/cilium/daemon/state.go:193 +0x4b2
2018-12-17T17:30:21.04638668Z main.runDaemon()
2018-12-17T17:30:21.046470927Z 	/go/src/github.com/cilium/cilium/daemon/daemon_main.go:870 +0x2f7
2018-12-17T17:30:21.046642967Z main.glob..func2(0x44726c0, 0xc000864230, 0x0, 0x7)
2018-12-17T17:30:21.046716344Z 	/go/src/github.com/cilium/cilium/daemon/daemon_main.go:166 +0x30
2018-12-17T17:30:21.046977999Z github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).execute(0x44726c0, 0xc0000d0010, 0x7, 0x7, 0x44726c0, 0xc0000d0010)
2018-12-17T17:30:21.047070654Z 	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:648 +0x241
2018-12-17T17:30:21.047228009Z github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x44726c0, 0xc00046a5a0, 0x2858f20, 0xc00019b468)
2018-12-17T17:30:21.047358534Z 	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:735 +0x2cc
2018-12-17T17:30:21.04747011Z github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).Execute(0x44726c0, 0x0, 0x0)
2018-12-17T17:30:21.047533299Z 	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:693 +0x2b
2018-12-17T17:30:21.047580741Z main.daemonMain()
2018-12-17T17:30:21.047674552Z 	/go/src/github.com/cilium/cilium/daemon/daemon_main.go:184 +0x133
2018-12-17T17:30:21.047708533Z main.main()
2018-12-17T17:30:21.047779243Z 	/go/src/github.com/cilium/cilium/daemon/main.go:30 +0xc9
```

**Review by ianvernon — APPROVED** [review]

**Comment by tgraf** [comment]
> the CI failed with a `panic found in logs` error:

The panic occurs every time more than one endpoint fails to restore. I've fixed it in:
https://github.com/cilium/cilium/pull/6468/commits/e73633543f0386d2d729129511e52808de2ffbbc

We have similar code constructs in pkg/ip/ip.go. Removing an item in a slice while iterating over it is not safe with the approach we commonly use right now

**Comment by tgraf** [comment]
The panic is a symptom of the following:
```
2018-12-17T17:30:21.042206344Z level=warning msg="Unable to restore endpoint" error="unable to reuse endpoint ID: endpoint ID 30618 is already in use" subsys=daemon
2018-12-17T17:30:21.042208328Z level=debug msg="Starting new controller" name="sync-to-k8s-ciliumendpoint (4085)" subsys=controller uuid=6dc69f74-0221-11e9-b7fc-08002765ce83
2018-12-17T17:30:21.042210324Z level=warning msg="Unable to restore endpoint" error="unable to reuse endpoint ID: endpoint ID 63031 is already in use" subsys=daemon
2018-12-17T17:30:21.042212392Z level=warning msg="Unable to restore endpoint" error="unable to reuse endpoint ID: endpoint ID 26861 is already in use" subsys=daemon
2018-12-17T17:30:21.042214436Z level=warning msg="Unable to restore endpoint" error="unable to reuse endpoint ID: endpoint ID 26861 is already in use" subsys=daemon
```

It is not clear yet whether this is related to this PR or not.

**Comment by tgraf** [comment]
> It is not clear yet whether this is related to this PR or not.

The endpoint ID allocator must be more liberal and except endpoint IDs that are now outside of the reduced idpool range (64K -> 4K). Added unit tests to test this.

**Comment by tgraf** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Pull request merged**
