### PR TITLE
Remove NEEDS_RELAX_VERIFIER

### LINKED ISSUE #15498: Remove NEEDS_RELAX_VERIFIER
In the datapath, we use `` to determine if we need to compile in the insertion of state pruning point, i.e., `relax_verifier()`.
https://github.com/cilium/cilium/blob/a78f75e1eb1dd37e107be01eec6ba7db53ad6f4f/bpf/include/bpf/verifier.h#L13-L17
That macro is defined whenever the kernel supports 1M instructions because we know the verifier stopped needing state pruning points around the same time.
https://github.com/cilium/cilium/blob/0218d373d2f8452720855a4a07b2719fd9826095/daemon/cmd/daemon_main.go#L1359-L1360

We however don't need to go through userspace to generate this macro, since it's already defined in `bpf_features.h` as `HAVE_LARGE_INSN_LIMIT`. We should remove `NEEDS_RELAX_VERIFIER` and `NeedsRelaxVerifier` and use `HAVE_LARGE_INSN_LIMIT` instead.

### PR DESCRIPTION
**Pull request by rscampos**
This commit removes userspace code related to NEEDS_RELAX_VERIFIER.

We can just use ifndef HAVE_LARGE_INSN_LIMIT (already defined) in
bpf/verifier.h, and cleaned up all code related to
NEEDS_RELAX_VERIFIER from cilium daemon. That macro is defined
whenever the kernel supports 1M instructions.

Besides that, a reference in Makefile was removed and a define
was added when compiling the BPF unit tests.

Fixes: #15498

Signed-off-by: Raphael Campos <raphael@accuknox.com>

### CODE REVIEW

**Comment by aditighag** [comment]
test-me-please

**Review by aditighag — APPROVED** [review]
LGTM

**Review by pchaigno — CHANGES_REQUESTED** [review]
Thanks for the contribution! :rocket: 

There is also at least one reference to that macro in `bpf/Makefile` we can remove. It best to run `git grep NEEDS_RELAX_VERIFIER` across the codebase to check if there are any references left.

**Comment by jibi** [comment]
nit: the mail in the `Signed-off-by:` line of the commit message should be surrounded by `< >` (which is why the `BPF checks / checkpatch (pull_request)` check is failing)

**Comment by rscampos** [comment]
Hello @pchaigno @aditighag @jibi, thank you guys for the help :D
I made all the requested changes

**Review by pchaigno — APPROVED** [review]

**Review by jibi — CHANGES_REQUESTED** [review]
~Looks like the macro is named `NO_HAVE_LARGE_INSN_LIMIT` rather than `HAVE_LARGE_INSN_LIMIT`~

Actually, both `HAVE_LARGE_INSN_LIMIT` and `NO_HAVE_LARGE_INSN_LIMIT` are valid based on the feature being present or not. The problem is the check, which should be:

```
#ifndef HAVE_LARGE_INSN_LIMIT
```

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Review by pchaigno — CHANGES_REQUESTED** [review]
The Travis CI failure is legit:
```
make[1]: Leaving directory '/home/travis/gopath/src/github.com/cilium/cilium/test/bpf'
test/bpf/unit-test
make: *** [Makefile:204: unit-tests] Segmentation fault (core dumped)
```
We either need to invert the #ifndef logic to not compile in `get_smp_processor_id` by default or we need to define `HAVE_LARGE_INSN_LIMIT` when compiling the BPF unit tests.

**Comment by rscampos** [comment]
@pchaigno, I added a define in test/bpf/unit-test.c and the test passed here.
If something is not right, please let me know. Thank you for all the help :D

**Review by pchaigno — APPROVED** [review]
:rocket:

**Comment by pchaigno** [comment]
test-me-please

**Review by jibi — APPROVED** [review]
Looks good! :rocket:

**Comment by jibi** [comment]
retest-4.9

**Comment by pchaigno** [comment]
> retest-4.9

What failed on 4.9?

**Comment by pchaigno** [comment]
test-1.16-netnext

**Comment by rscampos** [comment]
@pchaigno thanks, I'm going to run the test for K8s 1.16 version here... trying to address the problem
I let you know when I made some progress

**Comment by jibi** [comment]
> > retest-4.9
> 
> What failed on 4.9?

`K8sDatapathConfig Transparent encryption DirectRouting Check connectivity with transparent encryption and direct routing` (link to [jenkins](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/166/testReport/Suite-k8s-1/21/K8sDatapathConfig_Transparent_encryption_DirectRouting_Check_connectivity_with_transparent_encryption_and_direct_routing/))

**Comment by pchaigno** [comment]
k8s-1.16-kernel-netnext failed with known flake https://github.com/cilium/cilium/issues/14959 previously, and now with known flakes https://github.com/cilium/cilium/issues/15337 (just closed but this branch wasn't rebased) and https://github.com/cilium/cilium/issues/15620.

All team reviews are covered except `cilium/cli` and `cilium/build`. I believe `cilium/build` is an incorrect codeowners. It's for `bpf/Makefile` which should really be owned by `cilium/bpf`. `cilium/cli` is for `daemon/cmd/daemon_main.go` which has minor changes and several reviewers are familiar with.

Merging.

**Pull request merged**
