### PR TITLE
Fix weird indentation for rules in endpoint get output

### PR DESCRIPTION
**Pull request by ishantanu**
Fixing weird indentation rules in cilium endpoint get
command

Signed-off-by: Shantanu Deshpande <shantanud106@gmail.com>

**Summary of changes**:

Fixes: #3322 

```release-note
Fixed nested indentation issue while getting cilium endpoint details in the output
```

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
@iamShantanu101 Can you add a release note with the bug that you have fixed? Thanks

**Review by aanm — APPROVED** [review]

**Comment by ishantanu** [comment]
@aanm Added release note.

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
This is a trivial printf change and should not affect stability, so I don't think that the CI run provides useful information.

Suggesting `ready-to-merge` based on this reasoning.

**Pull request merged**
