### PR TITLE
Backports V1.2 - 21092018

### PR DESCRIPTION
**Pull request by eloycoto**
*Backported PR*
PR #5627
PR #5608
PR #5606
PR #5592
PR #5050

*In discussion to backport*

PR #5445

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5656)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

(Unable to provision, checking again: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/6658/)

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Review by aanm — APPROVED** [review]

**Review by rlenglet — APPROVED** [review]

**Comment by eloycoto** [comment]
Im my opinion this can be be merged, the missed kubernetes test can be addressed when https://github.com/cilium/cilium/pull/5675 is merged backported.

**Pull request merged**
