### PR TITLE
v1.2 backport 18 07 30

### PR DESCRIPTION
**Pull request by joestringer**
* #4998 
* #5029 
* #5039 

No conflicts during backport.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5041)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by raybejjani — CHANGES_REQUESTED** [review]
This is merging into master, which is probably wrong?
Otherwise, ship it!

**Comment by joestringer** [comment]
@raybejjani Just changed up the branch, good catch.

**Review by raybejjani — APPROVED** [review]

**Comment by raybejjani** [comment]
Uually I only notice when it shows me a massive diff with conflicts... too fresh a branch I guess

**Review by tgraf — APPROVED** [review]

**Pull request merged**
