### PR TITLE
test/k8s: for services test, wait for all applied manifests to delete

### PR DESCRIPTION
**Pull request by tommyp1ckles**
In the K8sDatapathConfig tests "echo-svc" deployment Pods are failing to terminate while waiting to terminate all Pods. These come from a deployment, that don't appear to be used in this suite. Presumably failure to delete is being cause by the Deployment controller restarting the Pods as they're deleted.

To try to fix this, going to wait for applied yamls in K8sServices to be fully deleted, including finalizers.

Addresses: #25255

### CODE REVIEW

**Review by qmonnet — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by tommyp1ckles** [comment]
bunch of failures from GH outages, will merge once I'm convinced everything relevant is passing.

**Comment by tommyp1ckles** [comment]
Go unit tests hit: https://github.com/cilium/cilium/pull/25353 - theres a PR open to fix.

**Comment by tommyp1ckles** [comment]
/test-1.16-4.19

**Comment by tommyp1ckles** [comment]
/test-1.26-net-next

**Pull request merged**
