### PR TITLE
tools: Add maptool executable to .gitignore

### PR DESCRIPTION
**Pull request by brb**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9420)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by ianvernon** [comment]
Health check failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/15416/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Test failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/15430/

Not related. Merging.

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
