### PR TITLE
helm: Improve debug.verbose docs

### PR DESCRIPTION
**Pull request by lgadban**
Add note on how to set multiple fields for the debug.verbose helm value

Minor issue but was trying to set this for debugging purposes and spent more time than I would have liked tracking down how to specify multiple fields. Hopefully this will save some time for others!

### CODE REVIEW

**Comment by borkmann** [comment]
Looks good, do you want to move this out of draft so it can be merged? Thanks!

**Comment by lgadban** [comment]
Rebased and ready for review. Thank you!

**Review by squeed — APPROVED** [review]

**Comment by lgadban** [comment]
Thanks for the approval @squeed ! 

Just rebased again on top of `main` and force-pushed; is there anything else I should be doing to get this merged?

**Comment by squeed** [comment]
@lgadban once the CI runs, it should be good to merge.

**Pull request merged**
