### PR TITLE
v1.11 backports 2022-02-11

### PR DESCRIPTION
**Pull request by jibi**
* #18681 -- helm: Add values for custom service monitor annotations (@michi-covalent)
 * #18717 -- loader: Fix egress attachment for bandwidth manager (@pchaigno)
 * #18720 --  ci: fix QEMU image build following Google Cloud SDK updates (@nbusseneau)
 * #18653 -- Also take secondary CIDRs into account when checking for validity of IPv4NativeRoutingCIDR (@codablock)
 * #18764 --  docs: Update clustermesh example verification steps (@sayboras)
 * #18633 -- k8s: Update libraries to 1.23.3 (@christarazi)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18681 18717 18720 18653 18764 18633; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
$ make add-label branch=v1.11 issues=18681,18717,18720,18653,18764,18633
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Looks good for my commit 💯

**Comment by jibi** [comment]
/test-backport-1.11

**Review by pchaigno — APPROVED** [review]
My change looks good. Thanks!

**Review by nbusseneau — APPROVED** [review]
My changes LGTM.

**Review by christarazi — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Comment by jibi** [comment]
/test-1.20-4.9

**Review by gandro — APPROVED** [review]
https://github.com/cilium/cilium/pull/18653 looks good to me!

**Comment by jibi** [comment]
Reviews are in, CI is green, merging :ship:

**Pull request merged**
