### PR TITLE
[v1.15-backport] helm: loadBalancerClass for Cluster Mesh APIserver

### PR DESCRIPTION
**Pull request by PhilipSchmid**
- [ ] https://github.com/cilium/cilium/pull/33033

```upstream-prs
 33033
```

### CODE REVIEW

**Comment by PhilipSchmid** [comment]
Can a maintainer please remove `backport-pending/1.15` from #33033 and add `backport/author`? Thanks

**Comment by youngnick** [comment]
/test-backport-1.15

**Comment by PhilipSchmid** [comment]
Thanks, Nick, for triggering the tests. Maybe I'm wrong, but to me, it looks like the two failed CI tests aren't related to this change:
- https://github.com/cilium/cilium/actions/runs/9656740711/job/26634809608#step:15:294
- https://github.com/cilium/cilium/actions/runs/9643081112/job/26592822913?pr=33342#step:3:242

**Review by aanm — APPROVED** [review]

**Pull request merged**
