### PR TITLE
datapath: clarify RESET_QUEUES as HAVE_WRITEABLE_QUEUE_MAPPING

### PR DESCRIPTION
**Pull request by julianwiedmann**
Having write access to skb->queue_mapping requires a certain kernel version (5.1). Manage the probing for this capability from the usual place, and don't hide it in the bandwidth manager.

Also wire up this capability in the complexity tests for all TC programs.

Note: from checking the RHEL8 source code (linux-4.18.0-372.32.1.el8_6) the skb->queue_mapping is writeable there as well.

### CODE REVIEW

**Review by rgo3 — APPROVED** [review]

**Comment by borkmann** [comment]
Looks reasonable, if it's minimal 5.1, do we even need to probe at all? My understanding is with 1.17 the minimal kernel will be 5.4.

**Review by borkmann — APPROVED** [review]

**Comment by julianwiedmann** [comment]
> Looks reasonable, if it's minimal 5.1, do we even need to probe at all? My understanding is with 1.17 the minimal kernel version will be 5.4.

Let's see what https://github.com/cilium/cilium/pull/34491 says. I'm fuzzy on the exact kernel requirements for the EDT path, but at least `skb->tstamp` looks good on RHEL8.

**Comment by julianwiedmann** [comment]
> > Looks reasonable, if it's minimal 5.1, do we even need to probe at all? My understanding is with 1.17 the minimal kernel version will be 5.4.
> 
> Let's see what #34491 says. I'm fuzzy on the exact kernel requirements for the EDT path, but at least `skb->tstamp` looks good on RHEL8.

Yep let's go with that PR instead.

**Pull request closed without merging**
