### PR TITLE
ci: conformance-kind: don't explicitly enable session affinity

### PR DESCRIPTION
**Pull request by julianwiedmann**
This option is already implied by KPR=true.

### CODE REVIEW

**Comment by julianwiedmann** [comment]
@brb mind keeping me honest here? For [reference](https://github.com/cilium/cilium/blob/c321f9063e79a1f18b81006c817a761fb4ff7ab7/daemon/cmd/kube_proxy_replacement.go#L59).

**Review by brb — APPROVED** [review]
:+1: Session Affinity is considered part of the full KPR (in kube-proxy there is no need to opt-in for SA).

**Review by aanm — APPROVED** [review]
:crossed_fingers:

**Pull request merged**
