### PR TITLE
1.6 envoy backports 2019 12 10

### PR DESCRIPTION
**Pull request by jrajahalme**
```release-note
Envoy is updated to release 1.12.2, including important security fixes.
```

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9734)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by aanm** [comment]
never-tell-me-the-odds

**Comment by jrajahalme** [comment]
never-tell-me-the-odds

**Comment by jrajahalme** [comment]
never-tell-me-the-odds

**Comment by jrajahalme** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
