### PR TITLE
cilium-health: avoid allocating in loop

### PR DESCRIPTION
**Pull request by tklauser**
Instead of allocating a new instance of models.Status, just change the
existing one.

Updates #10056

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10335)

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Review by joestringer — CHANGES_REQUESTED** [review]
The last statement in the loop is a sleep for 5 seconds, so these allocations should not occur often. Does this PR make a meaningful difference? (Why?)

This seems like it could leak a failed `status.Msg` from the previous iteration of the loop if you have a failed fetch of health status followed by a successful one.

**Review by gandro — APPROVED** [review]
Nice catch!

Edit (reverted approval): Did not see Joe's review. Once `ch.setStatus(status)` is called, we indeed must not touch that object anymore.

**Comment by tklauser** [comment]
> Nice catch!
> 
> Edit (reverted approval): Did not see Joe's review. Once `ch.setStatus(status)` is called, we indeed must not touch that object anymore.

Duh, I misread `(*CiliumHealth).GetStatus()` and thought it returns a copy, not the pointer. Even if, it seems it is polled with a period of 5s, so we would also copy every 5s. This PR doesn't make sense then, closing. Sorry for the noise.

**Comment by joestringer** [comment]
Oh, that's even worse than I realised. Nice work on review @gandro @tklauser , I think we saved ourselves from debugging a really weird failure case here.

FWIW if there are general structural changes that you think would be worthwhile to make this code more obvious then I'm open to making modifications. The ownership of the `status` here was apparently not clear to any of us on the first read of the code.

**Pull request closed without merging**
