### PR TITLE
gateway-api: Remove unused function check

### PR DESCRIPTION
**Pull request by ferozsalam**
The linter is complaining about `isReferenceAllowed` not being used as a result of https://github.com/cilium/cilium/commit/cd826fd3a275ca4841bf8e62f37da9931980cd28

The `isReferenceAllowed` check is now defined in `operator/pkg/gateway-api/helpers/referencegrants.go`, I have removed the unused version.

### CODE REVIEW

**Review by sayboras — APPROVED** [review]

**Comment by sayboras** [comment]
/test-backport-1.13

**Review by michi-covalent — APPROVED** [review]
😇

**Comment by sayboras** [comment]
Failed tests are due to wrong comand used, all requried tests are passed, reviews are in.

ci-l4lb-1.13 is not related to this change. Marking this ready to merge.

**Pull request merged**
