### PR TITLE
test bump image of upgrade / downgrade test to v1.5

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8087)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
@brb the upgrade downgrade test fails from v1.5 to master I believe you are already aware of it.

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.14-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
migrate-svc restart count values do not match
Expected
    <int>: 0
to be identical to
    <int>: 10
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.14-gopath/src/github.com/cilium/cilium/test/k8sT/Updates.go:249
```

**Comment by brb** [comment]
@aanm Yep, I'm aware of it: https://github.com/cilium/cilium/pull/8041#issuecomment-493355010. I'm going to fix.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
Failed due to the git timeout (https://github.com/cilium/cilium/pull/8122 might fix this).

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
CI failed due to:
```
[2019-06-03T17:12:58.640Z]     k8s2-1.10: Digest: sha256:71ad056a93753b04a3e7ced45a369fb0564a2fd7dcd3fe3689ab144712b97a6b
[2019-06-03T17:12:58.640Z]     k8s2-1.10: Status: Downloaded newer image for k8s1:5000/cilium/cilium-dev:latest
[2019-06-03T17:12:58.640Z]     k8s2-1.10: 0445bccc448d4819b7a3f3facb85e743e02f44c1f4a0f350f3bb0edc92b9e70b
[2019-06-03T17:12:58.640Z]     k8s2-1.10: 6bf57f8e2eb549d536063d52b19a7c43a58ba27f39df1b2e337bb9dd352caaf1
[2019-06-03T17:12:59.129Z]     k8s2-1.10: 68633968554c71740f90f514f497b1f8e787feed0113dc504d187b3ad3dd548d
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[2019-06-03T17:44:45.761Z] Cancelling nested steps due to timeout
[2019-06-03T17:44:45.842Z] Sending interrupt signal to process
[2019-06-03T17:45:05.842Z] After 20s process did not stop
```

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
Failed due to VM issues (fetching Docker images got stuck)

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by brb** [comment]
@aanm PTAL

**Comment by brb** [comment]
`Cilium-Ginkgo-Test-k8s` failed because of:

```
14:16:27  • [SLOW TEST:4835.099 seconds]
14:16:27  K8sDatapathConfig
14:16:27  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.12-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:378
14:16:27    DirectRouting
14:16:27    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.12-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:378
14:16:27      Check connectivity with automatic direct nodes routes
14:16:27      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.12-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
14:16:27  ------------------------------
14:16:27  K8sDatapathConfig Transparent encryption DirectRouting 
14:16:27    Check connectivity with automatic direct nodes routes
14:16:27    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.12-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
14:16:27  ===================== TEST FAILED =====================
```

which is unrelated to my changes.

**Pull request merged**
