### PR TITLE
Cleanup Azure allocator cloud name detection code

### PR DESCRIPTION
**Pull request by ungureanuvladvictor**
Signed-off-by: Vlad Ungureanu <vladu@palantir.com>

Following up on comments from https://github.com/cilium/cilium/pull/16515#pullrequestreview-701892180.

### CODE REVIEW

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Comment by ungureanuvladvictor** [comment]
test-1.16-netnext

**Review by ti-mo — APPROVED** [review]
Heh, thanks! :)

**Review by ashrayjain — APPROVED** [review]

**Comment by ungureanuvladvictor** [comment]
@twpayne / @aanm -- I see you folks are part of the `ipam` team, mind taking a look at this?

**Review by aanm — APPROVED** [review]

**Pull request merged**
