### PR TITLE
chore: Avoid docker warning due to casing

### PR DESCRIPTION
**Pull request by sayboras**
Example warning message in log can be found below

```
#1 WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 12)
#1 WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 41)
#1 WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 47)
#1 WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 57)
#1 WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 72)
#1 WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 82)
```

Relates: https://docs.docker.com/reference/build-checks/from-as-casing/

### CODE REVIEW

**Review by viktor-kurchenko — APPROVED** [review]
Thanks!

**Review by rolinh — APPROVED** [review]
I guess warnings made a good case for the change? :slightly_smiling_face:

**Review by nebril — APPROVED** [review]

**Comment by tklauser** [comment]
Added backport labels for all supported stable branches so we can avoid warnings being flagged on each PR to these branches.

**Pull request merged**
