### PR TITLE
bpf: Remove unused BPF feature probes/macros

### PR DESCRIPTION
**Pull request by vadorovsky**
The following macros were used in the old implementation of load
balancer, but are not used anymore:

- HAVE_MAP_VAL_ADJ
- HAVE_MARK_MAP_VALS

Also, those feature are available in kernel 4.9+, which is already
required for running Cilium.

Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9802)

### CODE REVIEW

**Comment by mrostecki** [comment]
test-me-please

**Review by brb — APPROVED** [review]
LGTM! Just needs rebase.

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
Probably unrelated

```
11:52:45  • Failure [117.949 seconds]
11:52:45  K8sServicesTest
11:52:45  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
11:52:45    Checks service across nodes
11:52:45    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
11:52:45      Tests NodePort BPF
11:52:45      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
11:52:45        Tests with direct routing
11:52:45        /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
11:52:45          Tests NodePort [It]
11:52:45          /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
11:52:45  
11:52:45          Pod "testclient-nrqjd" can not connect to service "http://127.0.0.1:32499"
[2020-01-06T10:52:45.526Z]         Expected command: kubectl exec -n default testclient-nrqjd -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 http://127.0.0.1:32499 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
[2020-01-06T10:52:45.526Z]         To succeed, but it failed:
[2020-01-06T10:52:45.526Z]         Exitcode: 28 
[2020-01-06T10:52:45.526Z]         Stdout:
[2020-01-06T10:52:45.526Z]          	 time-> DNS: '0.000018()', Connect: '0.000000',Transfer '0.000000', total '5.001122'
[2020-01-06T10:52:45.526Z]         Stderr:
[2020-01-06T10:52:45.526Z]          	 command terminated with exit code 28
[2020-01-06T10:52:45.526Z]         	 
[2020-01-06T10:52:45.526Z]         
11:52:45  
11:52:45          /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:295
```

**Comment by mrostecki** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Pull request merged**
