### PR TITLE
1.4.0-rc3 backports

### PR DESCRIPTION
**Pull request by tgraf**
* PR: 6628 -- client: Fix a possible NULL pointer dereference of localNode (@brb) -- https://github.com/cilium/cilium/pull/6628
 * PR: 6598 -- Ginkgo: Call AfterAll if it fails on BeforeAll (@eloycoto) -- https://github.com/cilium/cilium/pull/6598
 * PR: 6624 -- agent: Fix endpoint restore with unmounted BPF filesystem (@tgraf) -- https://github.com/cilium/cilium/pull/6624
 * PR: 6622 -- fqdn: Remove *domain.com special case (@raybejjani) -- https://github.com/cilium/cilium/pull/6622
 * PR: 6620 -- docs: toFQDNs intro example collects DNS data (@raybejjani) -- https://github.com/cilium/cilium/pull/6620
 * PR: 6613 -- Print IPAM ranges in cilium status (@joestringer) -- https://github.com/cilium/cilium/pull/6613
 * PR: 6611 -- daemon: Do not omit any error of createNodeConfigHeaderfile (@brb) -- https://github.com/cilium/cilium/pull/6611
 * PR: 6609 -- daemon: Exit daemon when usage is printed (@raybejjani) -- https://github.com/cilium/cilium/pull/6609
 * PR: 6606 -- FQDN: use the correct TTL on DNS-proxy (@eloycoto) -- https://github.com/cilium/cilium/pull/6606
 * PR: 6602 -- [RFC] fqdn: Timeouts in forwarded DNS Proxy passed back (@raybejjani) -- https://github.com/cilium/cilium/pull/6602
 * PR: 6599 -- --tofqdns-min-ttl default depends on --tofqdns-enable-poller (@raybejjani) -- https://github.com/cilium/cilium/pull/6599
 * PR: 6594 -- test: Run cilium status preflight check (@tgraf) -- https://github.com/cilium/cilium/pull/6594
 * PR: 6586 -- agent: Fix endpoint removal when createEndpoint() fails (@tgraf) -- https://github.com/cilium/cilium/pull/6586
 * PR: 6583 -- cni: Wait for cilium-agent availability (@mrostecki) -- https://github.com/cilium/cilium/pull/6583
 * PR: 6571 -- DNSProxy: Provide a flag for rejected DNS queries. (@eloycoto) -- https://github.com/cilium/cilium/pull/6571
 * PR: 6498 -- DNS Proxy emits error monitor events & proxy metrics (@raybejjani) -- https://github.com/cilium/cilium/pull/6498
 * PR: 6357 -- bpf: Do not pre-allocate BPF maps by default (@tgraf) -- https://github.com/cilium/cilium/pull/6357
 * PR: 6550 -- bpf: Move linux specific code into _linux.go files (@tgraf) -- https://github.com/cilium/cilium/pull/6550

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6633)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
Needs to pull in #6628

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
Test failure seems unrelated:

```
00:08:16.765     k8s1-1.9: SSH username: vagrant
00:08:16.765     k8s1-1.9: SSH auth method: private key
00:18:20.943 Timed out while waiting for the machine to boot. This means that
00:18:20.944 Vagrant was unable to communicate with the guest machine within
00:18:20.944 the configured ("config.vm.boot_timeout" value) time period.
00:18:20.944 
00:18:20.944 If you look above, you should be able to see the error(s) that
00:18:20.944 Vagrant had when attempting to connect to the machine. These errors
00:18:20.944 are usually good hints as to what may be wrong.
00:18:20.944 
00:18:20.944 If you're using a custom box, make sure that networking is properly
00:18:20.944 working and you're able to connect to the machine. It is a common
00:18:20.944 problem that networking isn't setup properly in these boxes.
00:18:20.944 Verify that authentication configurations are also setup properly,
00:18:20.944 as well.
00:18:20.944 
00:18:20.944 If the box appears to be booting properly, you may want to increase
00:18:20.944 the timeout ("config.vm.boot_timeout") value.
```

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
