### PR TITLE
Ginkgo: Add Kubernetes 1.9 support

### PR DESCRIPTION
**Pull request by eloycoto**
Added kubernetes 1.9 support in vagrantfile and added that version in
Nightly test

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

### CODE REVIEW

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Comment by ianvernon** [comment]
Discussed over chat - I have approved because the change itself looks fine, but the test failures should be analyzed to see what the cause for failure is.

**Comment by ianvernon** [comment]
https://github.com/cilium/cilium/issues/2800 is a blocker for this to be merged.

**Comment by eloycoto** [comment]
test-all-ginkgo

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
Hi @ianvernon 

I disabled the Jenkinsfile part so the PR can be merged to deploy a Kubernetes 1.9 without problems. 

This change shouldn't affect other versions ;-)

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
