### PR TITLE
[v1.11] images: Bump Hubble CLI to v0.11.1

### PR DESCRIPTION
**Pull request by gandro**
This bumps the Hubble CLI to the latest release, v0.11.1. By upgrading the Hubble CLI to the latest release, we ensure that the binary is built using the most recent version of Golang while preserving compatibility to the previous version using the new `HUBBLE_COMPAT` environment variable.

### CODE REVIEW

**Review by michi-covalent — APPROVED** [review]

**Review by ldelossa — APPROVED** [review]

**Comment by gandro** [comment]
/test-backport-1.11

**Comment by gandro** [comment]
/ci-l4lb-1.11

**Comment by michi-covalent** [comment]
will rebase after https://github.com/cilium/cilium/pull/23220 gets backported cc @ldelossa

**Comment by gandro** [comment]
/ci-awscni-1.11

**Comment by gandro** [comment]
/ci-aks-1.11

**Comment by gandro** [comment]
/ci-eks-1.11

**Comment by gandro** [comment]
/ci-gke-1.11

**Comment by gandro** [comment]
/ci-external-workloads-v1.11

**Comment by gandro** [comment]
/ci-multicluster-1.11

**Comment by gandro** [comment]
For some reason, the images cannot be fetched, even though the image build pipeline is green. Let's wait for #23220 and rebase afterwards to trigger the image build again.

**Comment by joestringer** [comment]
/test-backport-1.11

**Comment by joestringer** [comment]
ConformanceAKS fails a different way each time it runs - https://github.com/cilium/cilium/issues/20887, #23366, https://github.com/cilium/cilium/issues/23367

**Pull request merged**
