### PR TITLE
v1.12 Backports 2024-02-08

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #30503 (@qmonnet)
 * [x] #30496 (@giorio94)

PRs skipped due to conflicts:

 * #30504 (@marseel)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 30503 30496
```

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
Thanks!

**Comment by nbusseneau** [comment]
/test-1.18-4.9

**Comment by nbusseneau** [comment]
/test-1.19-4.9

**Comment by nbusseneau** [comment]
/test-1.19-4.9

**Comment by nbusseneau** [comment]
External workloads and GKE testing are failing due to K8s 1.24 not being available on GKE anymore, the failures can be ignored as per our policy this means GKE testing will get removed in a separate PR because none of the K8s versions officially supported on 1.12 are available on GKE.

**Comment by nbusseneau** [comment]
1.18 / 4.9 hit #27118.

**Comment by nbusseneau** [comment]
This should be ready to merge as soon as reviews are in, cf. previous messages for rationale to ignore failures.

**Review by brlbil — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]

**Comment by sayboras** [comment]
/test-backport-1.12

**Comment by sayboras** [comment]
/test-1.16-4.9

**Comment by sayboras** [comment]
/test-1.17-4.9

**Pull request merged**
