### PR TITLE
CI, docs: remove libelf-dev from dependencies

### PR DESCRIPTION
**Pull request by tklauser**
Since commit 4db3166 ("cilium-map-migrate: remove program and all
of its references") cilium-map-migrate has been replaced by a binary
written in Go and we no longer link binaries against libelf as of commit
c67cf7e ("bpf: remove libelf dependency and unused nobpf.h"). Thus,
drop libelf-dev from dependencies in CI and documentations.

Also update the `cilium-builder` image.

### CODE REVIEW

**Review by qmonnet — COMMENTED** [review]
Looks good. I can also see references to (elfutils-)libelf-dev in the following files:

- contrib/packaging/rpm/Dockerfile
- contrib/packaging/rpm/cilium.spec.envsubst
- contrib/ansible/roles/common/tasks/common_delete.yml
- contrib/ansible/roles/common/tasks/common_install.yml

Should they go as well?

**Review by qmonnet — APPROVED** [review]
> Initially, I wasn't sure about them because I had no way to test changes on these files and they don't seem to be covered by CI. It looks like they haven't been updated (apart from minor changes) in a while.

I saw the same, and suggested only because we've had those minor updates already.

> Are they still used by people at all?

No idea :/. Might be worth asking on Slack, or pinging the original authors?

**Review by nebril — APPROVED** [review]

**Comment by tklauser** [comment]
Rebased and added a second commit to remove `ipset` which was accidentially added to the Travis CI packages in #17706, see https://github.com/cilium/cilium/pull/17706#discussion_r739112486

**Comment by tklauser** [comment]
Will rebase and rebuild images once #17792 is merged.

**Review by pchaigno — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by tklauser** [comment]
GKE failure looks like #17307: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/6891/

**Comment by tklauser** [comment]
test-gke

**Comment by tklauser** [comment]
All tests passed and reviews are in, marking as ready to merge.

**Pull request merged**
