### PR TITLE
v1.14 Backports 2023-08-24

### PR DESCRIPTION
**Pull request by tklauser**
* [x] #26338 (@ysksuzuki)
 * [x] #27573 (@tklauser)
 * [x] #27583 (@weizhoublue)
 * [x] #27590 (@hemanthmalla)
 * [ ] #27314 (@qmonnet)
 * [x] #27640 (@haiyuewa)
 * [x] #27597 (@sayboras)
 * [ ] #27644 (@brb)
 * [x] #27645 (@giorio94)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 26338 27573 27583 27590 27314 27640 27597 27644 27645; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=26338,27573,27583,27590,27314,27640,27597,27644,27645
```

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.14

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commits 🍒

**Review by giorio94 — APPROVED** [review]
My commit looks good, thanks!

**Review by ysksuzuki — APPROVED** [review]
My commit looks good. Thanks!

**Comment by weizhoublue** [comment]
LGTM, thanks

**Comment by haiyuewa** [comment]
My commit looks good, thanks!

**Review by hemanthmalla — APPROVED** [review]

**Review by viktor-kurchenko — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
I looked over the remaining PRs without the checkboxes checked, LGTM.

**Pull request merged**
