### PR TITLE
1.2 backports 15-01-19

### PR DESCRIPTION
**Pull request by nebril**
#6636
#6624
#6611
#6586
#6570
#6568
#6558
#6555
#6551
#6549

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6647)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
