### PR TITLE
bpf: Fix ipcache lookup for kernels with HAVE_LPM_MAP_TYPE again

### PR DESCRIPTION
**Pull request by tgraf**
Commit 9cdd6b9205e3 ("bpf: If available, use ipcache for encapsulation")
mistakenly undid the fix of ce2278e7bf04 ("bpf: Fix ipcache lookup for kernels
with HAVE_LPM_MAP_TYPE") again.

Fixes: 9cdd6b9205e3 ("bpf: If available, use ipcache for encapsulation")

The bug was only ever present in master so no need to backport.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4802)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Comment by tgraf** [comment]
Hit #4803

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by tgraf** [comment]
I've not marked this for release note inclusion as this regression was never released

**Pull request merged**
