### PR TITLE
istio: Update to 1.5.6

### PR DESCRIPTION
**Pull request by jrajahalme**
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>
```release-note
Istio integration is updated to Istio release 1.5.6.
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-gke Istio

**Comment by jrajahalme** [comment]
test-gke K8sIstio

**Comment by jrajahalme** [comment]
test-gke K8sIstio

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-gke

**Comment by jrajahalme** [comment]
Travis CI hit by known flake #11955

**Comment by joestringer** [comment]
test-missed-k8s

**Review by joestringer — APPROVED** [review]

**Comment by jrajahalme** [comment]
GKE has one unrelated test flake, Istio test in GKE passed.

**Pull request merged**
