### PR TITLE
bpf: Fix node-port access to l7 proxy

### PR DESCRIPTION
**Pull request by joestringer**
Commit 1671a19eb979 ("bpf: Avoid routing loops for former local endpoint
IPs") adjusted the logic for the cilium_host devices to drop traffic
which is destined for somewhere that we don't control, under the
assumption that it is likely destined for an endpoint that we previously controlled,
but no longer do.

One hole in this logic was that when external endpoints reach to an
endpoint that has L7 policy applied, the traffic is first routed into
the localhost to terminate the connection in the L7 proxy, which then
sends back a response to establish the connection. This traffic may be
sent back over the cilium_host device, and will then be dropped by the
new logic to avoid routing loops.

Fix this case by only dropping traffic for destinations that lie within
the range of IPs managed by this node, and allowing other traffic to
pass.

Fixes: #6251
Fixes: 1671a19eb979 ("bpf: Avoid routing loops for former local endpoint IPs")

---

This issue is only present in unreleased versions of Cilium, so no release note is necessary.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6269)

### CODE REVIEW

**Comment by joestringer** [comment]
PR #6266 shows that this fix works as intended:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8113/execution/node/82/log/

**Comment by joestringer** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Comment by ianvernon** [comment]
@joestringer compilation failure:

```
22:39:11     runtime: clang -Iinclude -I. -D__NR_CPUS__=2 -O2 -g -target bpf -emit-llvm -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option -c bpf_netdev.c -o bpf_netdev.ll
22:39:11     runtime: bpf_netdev.c:457:17: error: & has lower precedence than ==; == will be evaluated first [-Werror,-Wparentheses]
22:39:11     runtime:         if (ip4->daddr & IPV4_MASK == IPV4_GATEWAY & IPV4_MASK)
22:39:11     runtime:                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
22:39:11     runtime: bpf_netdev.c:457:17: note: place parentheses around the '==' expression to silence this warning
22:39:11     runtime:         if (ip4->daddr & IPV4_MASK == IPV4_GATEWAY & IPV4_MASK)
22:39:11     runtime:                        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
22:39:11     runtime: bpf_netdev.c:457:17: note: place parentheses around the & expression to evaluate it first
22:39:11     runtime:         if (ip4->daddr & IPV4_MASK == IPV4_GATEWAY & IPV4_MASK)
22:39:11     runtime:             ~~~~~~~~~~~^~~~~~~~~~~
22:39:11     runtime: 1 error generated.
22:39:11     runtime: Makefile:27: recipe for target 'bpf_netdev.o' failed
22:39:11     runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/bpf'
22:39:11     runtime: make[1]: *** [bpf_netdev.o] Error 1
22:39:11     runtime: Makefile:32: recipe for target 'bpf' failed
```

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
@ianvernon Fixed.

**Pull request merged**
