### PR TITLE
v1.11 backports 2022-06-21

### PR DESCRIPTION
**Pull request by kkourt**
* #19487 -- runtime: Bump privileged test timeout (@joestringer)
 * #19992 -- Add metric on datapath update latency due to FQDN IP updates (@rahulkjoshi)
 * #20106 -- pkg/k8s: fix custom dialer logic for etcd >= 3.5.0 (@aanm)
 * #19522 -- redirectpolicy: Fix panic in service matcher LPR processing (@aditighag)
 * #20115 -- bpf: Use tunnel port flag instead of hardcoded value (@pchaigno)
 * #20131 -- operator: connect to the KVStore asynchronously (@aanm)
 * #19876 -- update-docs : add details for how to enable/disable Policy Audit Mode by endpoint (@BryanStenson-okta)
 * #20158 -- nodediscovery: ensure we cache the nodeResource  (@odinuge)
 * #20184 -- docs: Fix reference to upgrade guide (@joestringer)
 * #19996 -- Use DeleteOnMetadataMatch instead of Delete for endpointUpdated (@kvaster)
      * conflicit: because https://github.com/cilium/cilium/pull/19073 is not backported. Used global IPCache
 * #20195 -- docs: remove stale EgressGW limitation with CES (@julianwiedmann)
 * #20206 -- helm: Templatize preflight and clustermesh-apiserver repos (@michi-covalent)
 * #20208 -- Add a note about conflicting node CIDRs #20204 (@wokalski)
    * minor conflict
 * #20238 -- ci: provide CI images with unstripped binaries (@tklauser)
    * used v1.11 tags
 * #20210 -- nodemanager: Fix bug where Cilium tried to reach stale health endpoints on kubeapi-server nodes (@gandro)

Skipped:
 * #20123 -- cilium: fix conflicting iptables-legacy and iptables-nft rules (@jrfastab)
    * there are conflicts and requires updates on the runtime images
 * #20072 -- datapath: Create sysctl `rp_filter` overwrite config on agent init (@dylandreimerink)
    * due to conflicts

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 19487 19992 20106 19522 20115 20131 19876 20158 20184 19996 20195 20206 20208  20238 20210; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Review by tklauser — APPROVED** [review]
My change LGTM, thanks for adjusting the tags!

**Review by pchaigno — APPROVED** [review]
My changes look good!

**Review by odinuge — APPROVED** [review]
Mine look good!

**Comment by kkourt** [comment]
/test-backport-1.11

**Review by gandro — APPROVED** [review]
My commit looks good

**Comment by joestringer** [comment]
Changed from me LGTM. Would be good to clarify with @jrfastab / @dylandreimerink on who will work on getting those backports in, as they are both very useful bugfixes. The runtime one just needs to remove the runtime image bump changes and then follow the [docs page on updating the runtime images](https://docs.cilium.io/en/v1.11/contributing/development/images/#update-cilium-builder-and-cilium-runtime-images). Not sure about the rp_filter conflicts.

**Comment by kkourt** [comment]
/test-1.21-4.9

**Comment by pchaigno** [comment]
@kkourt That flake is https://github.com/cilium/cilium/issues/17307. The identifying factors are GKE + `connection refused` on readiness probes.

**Review by aanm — APPROVED** [review]
Thank you!

**Comment by dylandreimerink** [comment]
Backport for #20072 with resolved conflicts has been made in #20242, we we can merge that PR or cherry-pick the commits from that into this PR.

**Review by aditighag — APPROVED** [review]
Looks good for my changes. Thanks!

**Review by julianwiedmann — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]
CI now looks all good, and I checked the backports for Joe's PRs which are good as well.

Thanks!

**Pull request merged**
