### PR TITLE
v1.3 backport 19-03-19

### PR DESCRIPTION
**Pull request by jrfastab**
PRs:
 #7402 

KVstore and annotation PRs #7409 , #7394, and #7356 will follow shortly none applied cleanly.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7448)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by jrfastab** [comment]
test-missed-k8s

**Comment by jrfastab** [comment]
This is a backport script change and a README change! Retest, linking to details of error: 

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1832/

**Comment by jrfastab** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
Failure in K8s tests is due to https://github.com/cilium/cilium/issues/6923 which is a CI problem, not a Cilium issue.

All other tests passed, this can be merged.

**Pull request merged**
