### PR TITLE
images: Update bpftool

### PR DESCRIPTION
**Pull request by pchaigno**
This new version includes new feature probes for eBPF instruction set extensions and bounded loops.

### CODE REVIEW

**Comment by pchaigno** [comment]
/test-1.22-4.19

**Comment by pchaigno** [comment]
/test-1.22-4.19

**Comment by pchaigno** [comment]
/test-1.22-4.19

**Comment by borkmann** [comment]
Hey Paul, bpf-next was merged into net-next last weekend, and there are dependencies for probing for BBR. Do you have a chance to build the latest bpftool from bpf-next? That would be really great, thanks!

**Review by nbusseneau — APPROVED** [review]

**Review by kkourt — APPROVED** [review]

**Comment by pchaigno** [comment]
k8s-1.23-kernel-net-next is another case of https://github.com/cilium/cilium/issues/15474. This pull request doesn't include the fix from https://github.com/cilium/cilium/pull/19061, but Jenkins rebased the tests such that the new test ran and failed. Safe to ignore. Reviews are in, so marking ready to merge.

**Comment by ti-mo** [comment]
This seems to have a merge conflict.

**Comment by pchaigno** [comment]
Oh, no...

**Review by christarazi — APPROVED** [review]

**Comment by pchaigno** [comment]
- Runtime failed with known flake https://github.com/cilium/cilium/issues/18958. Thankfully it failed while collecting coverage so we know all privileged unit tests passed.
- k8s-1.22-kernel-4.19 failed with known flake https://github.com/cilium/cilium/issues/18318.

Reviews are in. Marking ready to merge.

**Pull request merged**
