### PR TITLE
backport: Helm Clustermesh and Openshift Backport for 1.10

### PR DESCRIPTION
**Pull request by nathanjsweet**
* #17851 -- Add support to connect Clustermesh clusters through Helm Chart (@samueltorres)
* #18849-- install/helm: Add Image Override Option to All Images (@nathanjsweet)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 17851 18849; do contrib/backporting/set-labels.py $pr done 1.10; done
```
or with
```
$ make add-label branch=v1.10 issues=17851,18849
```

### CODE REVIEW

**Comment by kaworu** [comment]
/test-backport-1.10

**Comment by gandro** [comment]
/ci-eks-1.10

**Review by gandro — APPROVED** [review]

**Comment by gandro** [comment]
To re-run the failed tests, we would have to rebuild the images. But considering that none of those use clustermesh (and EKS and Runtime don't use Helm), there is no point in re-running them. Merging.

**Pull request merged**
