### PR TITLE
Use RouteMTU to configure interfaces

### LINKED ISSUE #23711: Cilium sets wrong MTU to veth-interfaces
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey, we're using cilium to run virtual machines using KubeVirt project.
The KubeVirt inherits MTU value from veth-interface created by CNI.

But the problem is that Cilium sets wrong MTU for veth-interfaces:

```console
29: lxcd014acdcb003@if28: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether ca:eb:0e:7e:e2:d7 brd ff:ff:ff:ff:ff:ff link-netns cni-bf21b517-613f-f985-4fda-9f5159bc587b
```

It seems this MTU 1500 is inherited from physical device:

```
level=info msg="  --mtu='0'" subsys=daemon
level=info msg="Inheriting MTU from external network interface" device=eno1 ipAddr=92.53.71.83 mtu=1500 subsys=mtu
```

But I have VXLAN tunnel mode enabled. Thus it should equal 1450, same like in routing table:

```
10.111.0.0/24 via 10.111.0.169 dev cilium_host src 10.111.0.169
10.111.0.169 dev cilium_host scope link
10.111.1.0/24 via 10.111.0.169 dev cilium_host src 10.111.0.169 mtu 1450
10.111.2.0/24 via 10.111.0.169 dev cilium_host src 10.111.0.169 mtu 1450
10.111.3.0/24 via 10.111.0.169 dev cilium_host src 10.111.0.169 mtu 1450
10.111.4.0/24 via 10.111.0.169 dev cilium_host src 10.111.0.169 mtu 1450
```

---

During investigation of this problem, I found that:
- Setting `--mtu` option manually, changes MTU in routes, but not for veth-devices.
- Setting  `--device-mtu` option makes no effect.

Any way, even if this would work, specifying MTU manually is not universal solution and will disable MTU autodetection.
So I am a supporter of using RouteMTU for created veth-intefaces.

AFAIK [flannel-cni](https://github.com/flannel-io/flannel) and other CNI plugins are setting correct MTU value for Veth interfaces.
In case of tunnel enabled it is always 1450 instead of 1500

### Cilium Version

Client: 1.11.12  go version go1.17.13 linux/amd64
Daemon: 1.11.12  go version go1.17.13 linux/amd64

### Kernel Version

5.15.0-60-generic

### Kubernetes Version

v1.23.15

### Sysdump

_No response_

### Relevant log output

```shell
enable-pmtu-discovery: "true"
```

### Anything else?

@tgraf as author of this change, cloud you comment this issue please?
https://github.com/cilium/cilium/commit/829fc5730dc1741a07f8781ce6fc74eaeba4edc9#diff-7361d3356cb8d25d09fee88f8dbba7f047387c04c417e21f7a234a78068c02a7R349

Thank you 🙂 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kvaps**
Signed-off-by: Andrei Kvapil <kvapss@gmail.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: https://github.com/cilium/cilium/issues/23711

```release-note
MTU on veth interfaces now sets correctly according to tunneling mode.
```

### CODE REVIEW

**Comment by squeed** [comment]
As mentioned in https://github.com/cilium/cilium/issues/23711, I don't think this is a bug.

**Comment by youngnick** [comment]
Hi @kvaps, thanks again for this PR. I understand that you and @squeed are still discussing this one on #23711, what would you like to do here? We could move this to draft while you discuss this approach, or if you would like to proceed still, it looks like this needs a rebase and update to fix the outstanding conflicts.

**Comment by kvaps** [comment]
Hi @youngnick, sure, rebased.
We use this patch to make KubeVirt VMs working with Cilium.

We combined these two amazing technologies in our Kubernetes platform Deckhouse

**Review by squeed — CHANGES_REQUESTED** [review]
So, I had a bit of a chat with @joestringer, and we likely do not want this in its present configuration. We set the MTU on the route, rather than the device, to avoid any fragmentation issues on the receive side. Specifically since pods have an unrestricted MTU to the outside world, we do not want to artificially limit traffic that would otherwise be unaffected.

However, I understand that this would be useful for some use-cases. Would you be willing to add this as an option on the [CNI configuration](https://github.com/cilium/cilium/blob/master/plugins/cilium-cni/types/types.go#L23) instead?

**Comment by joestringer** [comment]
I think the ideal situation would be if kubevirt could learn about Cilium's route MTU and configure routes inside the VMs with that MTU, since then the kubevirt VMs could also have the correct MTU handling properties, identical to containers.

That said, a configurable option on CNI seems reasonable enough, but we certainly cannot accept this proposal against all devices as this will introduce connectivity breakages for certain paths.

**Comment by joestringer** [comment]
I had converted this to draft, but actually I think it makes sense to just close this PR out since it won't be accepted in the current form. If we need to discuss the solutions further, then we can use https://github.com/cilium/cilium/issues/23711 to continue the discussion. If and when there is a new proposal that addresses the concerns here, feel free to submit a fresh PR with that proposal.

Thanks for your ongoing contributions to Cilium!

**Pull request closed without merging**
