### PR TITLE
v1.9 backports 2021-12-10

### PR DESCRIPTION
**Pull request by nbusseneau**
* #18203 -- ui: v0.8.5 (@geakstr)
 * #18209 -- install: Fix hubble-ui image references (@joestringer)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 18203 18209; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.9

**Comment by nbusseneau** [comment]
/test-1.12-netnext

**Comment by nbusseneau** [comment]
/test-1.16-4.9

**Comment by nbusseneau** [comment]
Smoke tests failed with:

```
helm template cilium cilium --namespace=kube-system \
--set image.useDigest=true --set operator.image.useDigest=true --set preflight.image.useDigest=true --set hubble.relay.image.useDigest=true --set clustermesh.apiserver.image.useDigest=true --set hubble.tls.auto.enabled=true --set hubble.tls.auto.method="cronJob" --set hubble.metrics.enabled="{dns,drop,tcp,flow,icmp,http}" --set hubble.relay.enabled=true --set hubble.ui.enabled=true --set localRedirectPolicy=true --set bandwidthManager=true --set operator.replicas=1 > "/home/runner/work/cilium/cilium/install/kubernetes/experimental-install.yaml"
make: Leaving directory '/home/runner/work/cilium/cilium/install/kubernetes'
diff --git a/install/kubernetes/cilium/values.yaml b/install/kubernetes/cilium/values.yaml
index 0008b5e..75e6048 100644
--- a/install/kubernetes/cilium/values.yaml
+++ b/install/kubernetes/cilium/values.yaml
@@ -637,7 +637,7 @@ hubble:
       # -- Hubble-ui backend image.
       image:
         repository: quay.io/cilium/hubble-ui-backend
-        tag: v0.7.9@sha256:632c938ef6ff30e3a080c59b734afb1fb7493689275443faa1435f7141aabe76
+        tag: v0.8.5@sha256:2bce50cf6c32719d072706f7ceccad654bfa907b2745a496da99610776fe31ed
         pullPolicy: IfNotPresent
       # [Example]
       # resources:
@@ -654,7 +654,7 @@ hubble:
       # -- Hubble-ui frontend image.
       image:
         repository: quay.io/cilium/hubble-ui
-        tag: v0.7.9@sha256:e0e461c680ccd083ac24fe4f9e19e675422485f04d8720635ec41f2ba9e5562c
+        tag: v0.8.5@sha256:4eaca1ec1741043cfba6066a165b3bf251590cf4ac66371c4f63fbed2224ebb4
         pullPolicy: IfNotPresent
       # [Example]
       # resources:
diff --git a/install/kubernetes/experimental-install.yaml b/install/kubernetes/experimental-install.yaml
index 0c1a7c6..21a415f 100644
--- a/install/kubernetes/experimental-install.yaml
+++ b/install/kubernetes/experimental-install.yaml
@@ -1170,7 +1170,7 @@ spec:
       serviceAccountName: hubble-ui
       containers:
         - name: frontend
-          image: "quay.io/cilium/hubble-ui:v0.7.9@sha256:e0e461c680ccd083ac24fe4f9e19e675422485f04d8720635ec41f2ba9e5562c"
+          image: "quay.io/cilium/hubble-ui:v0.8.5@sha256:4eaca1ec1741043cfba6066a165b3bf251590cf4ac66371c4f63fbed2224ebb4"
           imagePullPolicy: IfNotPresent
           ports:
             - containerPort: 8080
@@ -1178,7 +1178,7 @@ spec:
           resources:
             {}
         - name: backend
-          image: "quay.io/cilium/hubble-ui-backend:v0.7.9@sha256:632c938ef6ff30e3a080c59b734afb1fb7493689275443faa1435f7141aabe76"
+          image: "quay.io/cilium/hubble-ui-backend:v0.8.5@sha256:2bce50cf6c32719d072706f7ceccad654bfa907b2745a496da99610776fe31ed"
           imagePullPolicy: IfNotPresent
           env:
             - name: EVENTS_SERVER_PORT
please run 'make -C install/kubernetes experimental-install' and submit your changes
```

This is a legitimate issue coming from the PR, probably this was fixed independently on `master`.

**Comment by nbusseneau** [comment]
Manual links to re-runs of failed pipelines from above:

- https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.12-net-next/1843/
- https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.16-kernel-4.9/443/

**Review by joestringer — APPROVED** [review]
Thanks. Yeah on master we don't track the shas directly in the values file, readme etc. so those changes were unnecessary there. This is one of those few cases where we just need to run an extra command to get the backport to work correctly.

**Comment by nbusseneau** [comment]
CI passed, merging.

**Pull request merged**
