### PR TITLE
test: skip new tests in upstream k8s

### PR DESCRIPTION
**Pull request by aanm**
New tests will be be added in Kubernetes repository [1], we can
already prepare Cilium to ignore those new tests for which Cilium has
no support for those functionalities.

[1] https://github.com/kubernetes/kubernetes/pull/91592

### CODE REVIEW

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by jayunit100** [comment]
So, it looks like the semantics of loopback services on cillim don't match that of services aren't necessarily well defined in the network policy API.  I've modified the above PR to reflect that we shouldn't fail on loopback related ALLOW/DENY .

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by jayunit100** [comment]
I think this didn't run the latest commit ... ^

**Comment by jayunit100** [comment]
test-upstream-k8s

**Comment by christarazi** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
the current failures are also happening in master.

**Review by christarazi — APPROVED** [review]
LGTM. Are we tracking this upstream gaps in functionality anywhere?

**Comment by aanm** [comment]
> LGTM. Are we tracking this upstream gaps in functionality anywhere?

@christarazi yes https://github.com/cilium/cilium/issues/12737 and https://github.com/cilium/cilium/issues/5719

**Comment by jayunit100** [comment]
just FYI this will also ADD some test coverage for the new tests as well looks like :) ? so its skipping broken ones but adding new ones .

**Pull request merged**
