### PR TITLE
Refactor /endpoint/{id} Policy types for API 1.0 stability

### PR DESCRIPTION
**Pull request by raybejjani**
Summary of changes:
Refactor endpoint Policy field to have Spec and Realized to distinguish between what's in the datapath and what's intended for it.

How to test (optional):
all tests should pass.

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
Comments and description in the API can be improved but structure looks like what we want for 1.0

**Pull request merged**
