### PR TITLE
Fix bug when reusing the same cell in multiple hives

### PR DESCRIPTION
**Pull request by giorio94**
Currently, the "Invoke" cell internally stores a reference to the container when `Apply()` gets called. Yet, this causes issues if the same cell is registered as part of multiple hives (e.g., constructing multiple subcommands), as that reference gets overwritten by new `hive.New()` executions.

Let's remove this explicit reference, capturing instead the container parameter through an anonymous function. Additionally, let's craft a unit test to prevent regressions.

```release-note
Fix bug when reusing the same cell in multiple hives
```

### CODE REVIEW

**Review by joamaki — APPROVED** [review]
Oopsie. Thanks for the fix, LGTM!

**Comment by joamaki** [comment]
Even though there was nothing shipped in v1.14 that was affected by this bug, lets backport this before we backport code that could be affected.

**Comment by giorio94** [comment]
Rebased onto main

**Pull request merged**
