### PR TITLE
helm: Add hubble-ui ingress labels

### PR DESCRIPTION
**Pull request by ReillyBrogan**
Support additional labels in the hubble-ui ingress definition.

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Some Ingress controllers (Traefik for example) support using labels for selecting which ingresses to serve from a particular ingress controller. This adds support for that.

```release-note
helm: Add support of additional labels to hubble ui ingress
```

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Thanks!

**Review by gandro — CHANGES_REQUESTED** [review]
There seems to be a typo in the generated files. From [CI:](https://github.com/cilium/cilium/actions/runs/4295932598/jobs/7500309469)

```
--- a/Documentation/helm-values.rst
+++ b/Documentation/helm-values.rst
@@ -1228,7 +1228,7 @@
    * - hubble.ui.ingress
      - hubble-ui ingress configuration.
      - object
-     - ``{"annotations":{},"className":"","enabled":false,"hosts":["chart-example.local"],"labels":{},""tls":[]}``
+     - ``{"annotations":{},"className":"","enabled":false,"hosts":["chart-example.local"],"labels":{},"tls":[]}``
    * - hubble.ui.nodeSelector
      - Node labels for pod assignment ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
      - object
HINT: to fix this, run 'make -C Documentation update-helm-values'

**Review by tommyp1ckles — APPROVED** [review]
lg, aside from some CI linting issues?

**Comment by gandro** [comment]
@ReillyBrogan Could you rebase this branch on master? It seems to be lagging a bit behind, thereby causing some CI failures due to tests requiring a more recent code base. Thanks.

**Review by gandro — APPROVED** [review]
Looking good! Let's run CI

**Comment by gandro** [comment]
/test-1.26-net-next

**Pull request merged**
