### PR TITLE
pkg/labels: Optimize LabelArray {GetModel(),String()}

### PR DESCRIPTION
**Pull request by odinuge**
Saw these two allocate a relatively huge chunks of memory in production. Small improvement to reduce the number of bytes allocated, as well as the total number of allocations.

See the two commit messages for the actual numbers.

---

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [X] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

### CODE REVIEW

**Comment by odinuge** [comment]
Looks like the failed conformance test is a flake since it fails on a step downloading an artifact.

**Comment by odinuge** [comment]
~kinda related to https://github.com/cilium/cilium/issues/19571. cc @christarazi since you made that issue

**Review by christarazi — APPROVED** [review]
Thanks! :rocket:

**Review by rolinh — APPROVED** [review]

**Review by aditighag — APPROVED** [review]
Cool!

**Review by aanm — APPROVED** [review]

**Pull request merged**
