### PR TITLE
install/kubernetes: Remove deprecated cluster roles

### PR DESCRIPTION
**Pull request by christarazi**
Following up on https://github.com/cilium/cilium/pull/13285.

### CODE REVIEW

**Review by gandro — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by christarazi** [comment]
Hit https://github.com/cilium/cilium/issues/18273. I only ran a few CI jobs just to ensure that the changes didn't cause issues and the change doesn't require a full run to validate Kubernetes cluster roles. Marking ready to merge.

**Comment by tklauser** [comment]
Looking at the [sysdump in one of the failed conformance tests](https://github.com/cilium/cilium/actions/runs/1552525671) we see:

```
2021-12-16T09:41:00.537284463Z level=warning msg="github.com/cilium/cilium/pkg/k8s/synced/crd.go:137: failed to list *v1.PartialObjectMetadata: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:kube-system:cilium\" cannot list resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope" subsys=klog
2021-12-16T09:41:00.537399673Z level=error msg=k8sError error="github.com/cilium/cilium/pkg/k8s/synced/crd.go:137: Failed to watch *v1.PartialObjectMetadata: failed to list *v1.PartialObjectMetadata: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:kube-system:cilium\" cannot list resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope" subsys=k8s
2021-12-16T09:41:01.824037600Z level=warning msg="github.com/cilium/cilium/pkg/k8s/synced/crd.go:137: failed to list *v1.PartialObjectMetadata: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:kube-system:cilium\" cannot list resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope" subsys=klog
2021-12-16T09:41:01.824073203Z level=error msg=k8sError error="github.com/cilium/cilium/pkg/k8s/synced/crd.go:137: Failed to watch *v1.PartialObjectMetadata: failed to list *v1.PartialObjectMetadata: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:kube-system:cilium\" cannot list resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope" subsys=k8s
2021-12-16T09:41:04.931524118Z level=warning msg="github.com/cilium/cilium/pkg/k8s/synced/crd.go:137: failed to list *v1.PartialObjectMetadata: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:kube-system:cilium\" cannot list resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope" subsys=klog
2021-12-16T09:41:04.931718934Z level=error msg=k8sError error="github.com/cilium/cilium/pkg/k8s/synced/crd.go:137: Failed to watch *v1.PartialObjectMetadata: failed to list *v1.PartialObjectMetadata: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:kube-system:cilium\" cannot list resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope" subsys=k8s
2021-12-16T09:41:10.260370044Z level=warning msg="github.com/cilium/cilium/pkg/k8s/synced/crd.go:137: failed to list *v1.PartialObjectMetadata: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:kube-system:cilium\" cannot list resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope" subsys=klog
2021-12-16T09:41:10.260395046Z level=error msg=k8sError error="github.com/cilium/cilium/pkg/k8s/synced/crd.go:137: Failed to watch *v1.PartialObjectMetadata: failed to list *v1.PartialObjectMetadata: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:kube-system:cilium\" cannot list resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope" subsys=k8s
2021-12-16T09:41:19.464549767Z level=warning msg="github.com/cilium/cilium/pkg/k8s/synced/crd.go:137: failed to list *v1.PartialObjectMetadata: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:kube-system:cilium\" cannot list resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope" subsys=klog
2021-12-16T09:41:19.464590770Z level=error msg=k8sError error="github.com/cilium/cilium/pkg/k8s/synced/crd.go:137: Failed to watch *v1.PartialObjectMetadata: failed to list *v1.PartialObjectMetadata: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:kube-system:cilium\" cannot list resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope" subsys=k8s
```

I think this is a legitimate failure causing the smoke tests to fail consistently. I've also tried re-triggering one of them and the failure is consistent.

It seems like cilium-cli is used in the smoke tests. Could this be an issue with cilium-cli?

Removing the `ready-to-merge` label for now to investigate further.

**Review by gandro — CHANGES_REQUESTED** [review]
@tklauser's assesement is solid.

It looks like `list` and `get` are required for this check in the agent here:
https://github.com/cilium/cilium/blob/3f8e54ee315573509aa095d335b9908cfb4d9140/daemon/cmd/daemon.go#L618

The reason why this didn't pop up in `ci-gke` and `ci-eks` is because they use the Cilium CLI and not Helm to install (and thus didn't test the modified code at all).

**Comment by christarazi** [comment]
Thanks @tklauser! It totally slipped my mind that GH Actions runs with the CLI don't use Helm. I've re-added the `list` action.

**Comment by christarazi** [comment]
/test-1.21-5.4

**Comment by christarazi** [comment]
/test-1.21-5.4

**Review by gandro — APPROVED** [review]

**Pull request merged**
