### PR TITLE
v1.16 Backports 2024-12-09

### PR DESCRIPTION
**Pull request by gandro**
* [x] #36318 (@giorio94)
 * [x] #35452 (@sayboras)
 * [x] #36384 (@julianwiedmann)
 * [x] #36386 (@julianwiedmann)
 * [x] #36252 (@bimmlerd)
 * [ ] #36267 (@liyihuang) :warning: backporter tool did not find upstream commit. I've manually picked it

PRs skipped due to conflicts (build errors to be correct):

 * #35868 (@hemanthmalla)
 * #36330 (@jrajahalme)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 36318 35452 36384 36386 36252 36267
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commit :+1:

**Comment by gandro** [comment]
/test-backport-1.16

**Review by giorio94 — APPROVED** [review]
My commit looks good, thanks!

**Comment by gandro** [comment]
Dropped two PRs due to build errors.

**Review by julianwiedmann — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Review by bimmlerd — APPROVED** [review]

**Pull request merged**
