### PR TITLE
v1.1 backport - proxy: "Make NACK cancel the WaitGroup and pass NACK detail in ProxyError"

### PR DESCRIPTION
**Pull request by jrajahalme**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5743)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by ianvernon** [comment]
Tests failed: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/6861

Looks like the tests got stuck:
```
18:16:20 K8sValidatedChaosTest
18:16:20 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:341
18:16:20   Endpoint can still connect while Cilium is not running
18:16:20   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:373
18:16:20 ------------------------------
18:16:20 K8sValidatedUpdates 
18:16:20   Updating Cilium stable to master
18:16:20   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:373
18:54:39 Sending interrupt signal to process
18:54:39 Sending interrupt signal to process
18:54:43 Terminated
```

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
