### PR TITLE
docs: add guidelines for contributing to Cilium's documentation

### PR DESCRIPTION
**Pull request by qmonnet**
This PRs a set of recommendations on style and formatting for contributing to Cilium's documentation. The current guidelines are mostly about RST formatting for now, but can be extended with whatever directions may help produce a better documentation in the future.

Some of these guidelines are simply suggestions: they may not have been the topic of any particular discussion before, and feedback is welcome. I spent some time looking at the RST specification, but I don't claim to have the right point-of-view on every item.

One follow-up item to add would be a recommendation on the structure, in particular regarding nesting (or not nesting) RST fragments. See [this discussion](https://github.com/cilium/cilium/pull/16126#discussion_r633660502) with suggestions from @nbusseneau for reference, but I'm not sure a consensus was reached at the time.

[First commit also relates to the documentation, but focuses on syntax highlighting and cancels Sphinx's default attempt to highlight snippets based on Python3's syntax.]

### CODE REVIEW

**Comment by nbusseneau** [comment]
> See this discussion with suggestions from @nbusseneau for reference, but I'm not sure a consensus was reached at the time.

We had a short discussion on Slack, and the conclusion was that it was better to fix structural issues when they arise rather, since they are quite rare. Until we happen to have the same kind of breakage all the time, no need to have guidelines for that :)

**Review by nbusseneau — APPROVED** [review]
Read through, LGTM. I was thinking we should maybe have an additional section regarding formatting, notably for indentation and whitespace around various common blocks. What do you think?

**Review by aditighag — APPROVED** [review]
lgtm, thanks!

**Comment by qmonnet** [comment]
> Read through, LGTM. I was thinking we should maybe have an additional section regarding formatting, notably for indentation and whitespace around various common blocks. What do you think?

Not a bad idea, but I don't think there's a consensus on that - I think that for code blocks for example we have a mix of 2, 3, 4, 8 spaces in different files (or sometimes in a single one). And if we make it too strict, nobody will follow it. Do you have suggestions in particular?

One thing that comes to mind is that we prefer to wrap long lines, I forgot to mention that.

**Comment by nbusseneau** [comment]
> Do you have suggestions in particular?

No, I was mostly just confused when contributing about what rules I should follow. So far I've just rolled with using the same style as the one around what I was modifying.

**Review by joestringer — APPROVED** [review]
:100:

**Comment by qmonnet** [comment]
I added a (hopefully consensual) note on line wrapping:

```rst
Body
----

Wrap the lines for long sentences or paragraphs. There is no fixed convention
on the length of lines, but targeting a width of about 80 characters should be
safe in most circumstances.
```

Based on the reviews and the Documentation action passing, I'll mark as ready-to-merge. I'm happy to add a note on indent and spacing as a follow-up if we settle on something.

**Pull request merged**
