### PR TITLE
v1.16 Backports 2024-09-25

### PR DESCRIPTION
**Pull request by pippolo84**
* [x] #34783 (@dylandreimerink)
 * [x] #34913 (@ysksuzuki)
 * [x] #34715 (@gandro)
 * [x] #34934 (@kaworu)
 * [x] #34941 (@bimmlerd)
 * [ ] #34922 (@fjvela)
 * [x] #34951 (@harsimran-pabla)
 * [x] #34959 (@rastislavs) :warning: resolved conflicts
   * Conflicts in `pkg/bgpv1/manager/reconcilerv2/service.go`: Fixed accepting incoming changes and using `BGPInstance.ASN` instead of `BGPInstance.Global.ASN`
 * [x] #34946 (@kaworu)
 * [ ] #34789 (@tommyp1ckles)
 * [x] #34976 (@rastislavs)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 34783 34913 34715 34934 34941 34922 34951 34959 34946 34789 34976
```

### CODE REVIEW

**Review by kaworu — APPROVED** [review]
Thanks @pippolo84 my patches LGTM!

**Review by gandro — APPROVED** [review]

**Review by harsimran-pabla — APPROVED** [review]

**Review by rastislavs — APPROVED** [review]
Thanks!

**Review by bimmlerd — APPROVED** [review]

**Comment by pippolo84** [comment]
/test-backport-1.16

**Review by dylandreimerink — APPROVED** [review]

**Review by ysksuzuki — APPROVED** [review]

**Review by brlbil — APPROVED** [review]

**Comment by pippolo84** [comment]
Force-pushed to pull https://github.com/cilium/cilium/pull/35053 and fix conformance-ginkgo workflow

**Comment by pippolo84** [comment]
/test-backport-1.16

**Comment by pippolo84** [comment]
Force-pushed to pull https://github.com/cilium/cilium/pull/35053 and fix conformance-ginkgo workflow

**Comment by pippolo84** [comment]
/test-backport-1.16

**Review by tommyp1ckles — APPROVED** [review]

**Pull request merged**
