### PR TITLE
2018-07-23 - CI backport changes

### PR DESCRIPTION
**Pull request by aanm**
This PR is an attempt to fix the failures found in https://github.com/cilium/cilium/pull/4907

It will probably be the last PR for 1.0 with CI changes.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4941)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
Build failure was due to Kafka: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5194

**Comment by ianvernon** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
I wanted to debug this locally and I see that we are deploying kube-dns and coredns into the cluster:

```
$ kubectl exec cilium-pwjdh    -n kube-system -it /bin/bash
root@k8s1:~# cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                   IPv6                 IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                   
173        Disabled           Disabled          64951      k8s:io.kubernetes.pod.namespace=kube-system   f00d::a0a:0:0:ad     10.10.0.66    ready   
                                                           k8s:k8s-app=kube-dns                                                                     
13949      Disabled           Disabled          64951      k8s:io.kubernetes.pod.namespace=kube-system   f00d::a0a:0:0:367d   10.10.0.32    ready   
                                                           k8s:k8s-app=kube-dns                                                                     
29381      Disabled           Disabled          64951      k8s:io.kubernetes.pod.namespace=kube-system   f00d::a0a:0:0:72c5   10.10.0.59    ready   
                                                           k8s:k8s-app=kube-dns                                                                     
29898      Disabled           Disabled          49034      reserved:health                               f00d::a0a:0:0:74ca   10.10.0.172   ready   
```

Will we have to backport https://github.com/cilium/cilium/commit/8c8f7ae7df1e505883ceb7fd1bc1ec6fa63e264c as well? IMO we should get the latest round of backports out for v1.0 *without CI fixes* and then work on getting the K8s CI working for v1.0 separately in parallel, and not have it block the release of the next version of v1.0. All of these CI issues are unrelated to the code used in production environments that  we ship out, and are blocking the release of bug fixes to v1.0.

**Comment by raybejjani** [comment]
If we're forward testing to the latest k8s, then I suppose we have no choice but to also backport the dns fixup. I think we did discuss not testing older releases with newer k8s versions. If so, that might also simplify our life.

Looking at the CI build, I think it ran all the other tests? (it didn't fail-fast at least). If so, merging is it is the right choice.

**Comment by ianvernon** [comment]
@raybejjani I am not for merging code which breaks the tests. I agree that we need the CI fixes backported, but I think that can be worked on in parallel; we can get the fixes to Cilium itself backported and merged, as these are actual fixes that users of Cilium in production environments will want.

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5305

Investigating.

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
