### PR TITLE
[v1.10] cilium: fix inconsistent iptables and nft usage

### PR DESCRIPTION
**Pull request by jrfastab**
Backport v1.10 fix inconsistent iptables and nft usage.

Backports:
- #20123

```upstream-prs
$ for pr in 20123; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Comment by joestringer** [comment]
Would be good to add the `[ upstream commit ... ]` annotations inside the commit messages, referring to the merged commits:

```
20381ec53f54 (upstream/master) update cilium-{runtime,builder}
369f3f917ec9 image/runtime: Fix kube proxy and Cilium iptables and nftables collision
```

And it looks like there's still one more round of the runtime image bump bits to sort out. Otherwise this should be OK.

**Review by pchaigno — CHANGES_REQUESTED** [review]
Blocked on Joe's comment above, which needs to be addressed.

**Comment by joestringer** [comment]
I've bumped the runtime images and added the upstream commit reference to the bugfix commit here.

**Review by nbusseneau — APPROVED** [review]

**Review by pchaigno — APPROVED** [review]

**Comment by aanm** [comment]
/test-backport-1.10

**Comment by joestringer** [comment]
The failures look unrelated to the changes, many of the CI targets worked fine. Seems like this should be safe to merge.

**Comment by joestringer** [comment]
The other Jenkins failure looks similar to #19055 (different test though).

**Comment by joestringer** [comment]
ConformanceEKS hit known issue #16938.

**Comment by joestringer** [comment]
Triage complete, no evidence of any relation to the fix. This fix addresses a real issue where Cilium can select the wrong iptables-{legacy,nft} and cause ongoing connectivity issues. Merging.

**Pull request merged**
