### PR TITLE
Allow QPS/Burst for AWS client to be configurable

### PR DESCRIPTION
**Pull request by ungureanuvladvictor**
---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8414)

### CODE REVIEW

**Comment by ungureanuvladvictor** [comment]
While testing in our environment the AWS ENI IPAM functionality I observed the ec2 client being rate limited when a lot number of would start up and request ENIs.

This allows the user to override the rate limit defaults especially if the AWS server side limits are increased in special environments.

**Comment by tgraf** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by ungureanuvladvictor** [comment]
@tgraf I took a look at the test and looks like the operator failed to start with:
`2019-06-28T05:22:52.384304992Z level=fatal msg="Unable to start status api: http: Server closed" subsys=cilium-operator`

Looking at k8s etcd logs it has some lines like:
`2019-06-28T05:24:37.898852674Z E0628 05:24:37.898536       1 upgradeaware.go:355] Error proxying data from backend to client: write tcp 192.168.36.11:6443->192.168.36.11:48750: write: broken pipe`

Let me know if I should debug further what's happening here. At a first glance don't see how my change could trigger this but maybe I'm missing something.

**Comment by tgraf** [comment]
> Let me know if I should debug further what's happening here. At a first glance don't see how my change could trigger this but maybe I'm missing something.

Agreed, looks unrelated.

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
@ungureanuvladvictor We are currently debugging and fixing why the operator is restarting in the CI. It  has started happening since we started running it in host networking mode. The failure is definitely not related to this change. We can re-run the CI once that is fixed.

**Comment by ungureanuvladvictor** [comment]
Thx for the update! I'll watch the PR.

**Review by ianvernon — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
@ungureanuvladvictor The operator is stable again, please rebase against master and we can run the CI again.

**Comment by ungureanuvladvictor** [comment]
@tgraf thx for the help here, just rebased.

**Comment by tgraf** [comment]
test-me-please

**Pull request merged**
