### PR TITLE
[v1.13] golangci: Enable errorlint

### PR DESCRIPTION
**Pull request by jrajahalme**
* [x] #31458 (@jrajahalme)
 * [x] #23983 (@sayboras)
 
**Note:** Added commit updating golangci-lint version used by `make lint` to match that of the GH Go lint action.

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31458 23983
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
/test-backport-1.13

**Review by chancez — APPROVED** [review]
Hubble changes LGTM

**Comment by jrajahalme** [comment]
Backported #23983 to bump vagrant boxes used for runtime tests to Go 1.20, which is already used in v1.13 development. G0 1.20 added support for multiple `%w` formatters in `fmt.Errorf()`.

**Comment by jrajahalme** [comment]
/test-backport-1.13

**Review by sayboras — APPROVED** [review]

**Comment by jrajahalme** [comment]
/test-1.21-4.19

**Comment by jrajahalme** [comment]
/test-1.23-4.19

**Comment by jrajahalme** [comment]
/test-1.24-5.4

**Comment by jrajahalme** [comment]
/test-1.26-net-next

**Comment by jrajahalme** [comment]
/test-1.24-5.4

**Comment by jrajahalme** [comment]
/test-1.26-net-next

**Comment by jrajahalme** [comment]
/test-1.24-5.4

**Review by learnitall — APPROVED** [review]
Thanks!

**Review by squeed — APPROVED** [review]

**Review by glibsm — APPROVED** [review]

**Comment by jrajahalme** [comment]
rebased & resolved conflicts

**Comment by jrajahalme** [comment]
/test-backport-1.13

**Comment by jrajahalme** [comment]
/test-1.24-5.4

**Comment by jrajahalme** [comment]
/test-backport-1.13

**Comment by jrajahalme** [comment]
Added a commit to bump up VM provisioning timeouts

**Comment by jrajahalme** [comment]
/test-backport-1.13

**Review by michi-covalent — APPROVED** [review]

**Comment by jrajahalme** [comment]
Rebased

**Comment by jrajahalme** [comment]
/test-backport-1.13

**Comment by jrajahalme** [comment]
/test-1.21-4.19

**Review by ti-mo — APPROVED** [review]

**Pull request merged**
