### PR TITLE
docs: Pick up PyYAML 6.0.1

### LINKED ISSUE #26873: CI: Travis `ERROR: Could not find a version that satisfies the requirement PyYAML==6.0`
## CI failure

Travis is unable to fetch some of the docs tooling dependencies:

```
#7 8.190 Collecting PyYAML==6.0
#7 8.195   Downloading PyYAML-6.0.tar.gz (124 kB)
#7 8.405   Installing build dependencies: started
#7 12.07   Installing build dependencies: finished with status 'done'
#7 12.07   Getting requirements to build wheel: started
#7 12.39   Getting requirements to build wheel: finished with status 'error'
#7 12.39   ERROR: Command errored out with exit status 1:
...
#7 12.39 ERROR: Could not find a version that satisfies the requirement PyYAML==6.0
#7 12.39 ERROR: No matching distribution found for PyYAML==6.0
#7 12.41 WARNING: You are using pip version 21.0.1; however, version 23.2 is available.
#7 12.41 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
#7 ERROR: executor failed running [/bin/sh -c pip install -r /tmp/requirements.txt]: runc did not terminate sucessfully
```

- Observed on main here: https://app.travis-ci.com/github/cilium/cilium/builds/264564427 (PR https://github.com/cilium/cilium/pull/26869)
- And on v1.13 here: https://app.travis-ci.com/github/cilium/cilium/jobs/606180933 (PR https://github.com/cilium/cilium/pull/26861)

### PR DESCRIPTION
**Pull request by michi-covalent**
Revert commit 04d48fe3, and pick up PyYAML 6.0.1.

Fixes: #26873

### CODE REVIEW

**Comment by michi-covalent** [comment]
ran `make -C Documentation builder-image` locally to verify that it fixes #26873

**Review by learnitall — APPROVED** [review]
LGTM :rocket:

**Comment by gandro** [comment]
Adding `needs-backport` labels based on the commit which is fixed.

**Comment by gandro** [comment]
Documentation and Travis are green. Let's merge this to fix CI.

**Pull request merged**
