### PR TITLE
[v1.7] k8s: Update libraries to v1.17.16

### PR DESCRIPTION
**Pull request by christarazi**

### CODE REVIEW

**Comment by christarazi** [comment]
test-backport-1.7

**Comment by aanm** [comment]
test-upstream-k8s

**Review by aanm — APPROVED** [review]

**Review by aanm — CHANGES_REQUESTED** [review]
Actually I forgot one thing, the versions that we are testing in `./test/provision/k8s_install.sh` also need to be updated.

**Comment by christarazi** [comment]
test-backport-1.7

**Review by aanm — CHANGES_REQUESTED** [review]
The tests are failing. Also k8s 1.17.16 was just released so we might just modify this PR to point to 1.17.16 instead.

**Comment by christarazi** [comment]
test-backport-1.7

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-missed-k8s

**Pull request merged**
