### PR TITLE
Ginkgo: Added L4 egress rules to Nightly test

### PR DESCRIPTION
**Pull request by eloycoto**
Added the following rules:

- Layer 4 Egress to protocol TCP
- Layer 4 Egress to protocol UDP
- Layer 4 Egress using protocol and port
- Layer 4 Egress using protocol and port
- Layer 4 Ingress using only protocol

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

### CODE REVIEW

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-nightly

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
Hi @ianvernon 

I know that this PR fails on tests, but it's a work in progress and I would like to have it merged to run every night. It fixes15 test, and the fail that we have here looks like a cilium pod died. Could you merge this, please?

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
