### PR TITLE
v1.13 Backports 2024-07-15

### PR DESCRIPTION
**Pull request by giorio94**
* [x] #33626 (@giorio94)
 * [x] #33592 (@gandro) :warning: resolved conflicts
   * ℹ️ Hit minor conflicts due to different surrounding context; resolved accepting combination. Adapted flag registration, changing vp to Vp. Additionally dropped the values.schema.json hunk, as not applicable in v1.14, and regenerated helm values documentation.
 * [ ] ~~#33769 (@pchaigno)~~
    * :x: Skipped, as causes the Cilium IPsec upgrade workflow to fail, and needs further investigation.
 * [x] #33819 (@giorio94)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33626 33592 33819
```

### CODE REVIEW

**Comment by giorio94** [comment]
/test-backport-1.13

**Comment by giorio94** [comment]
Blocked waiting on https://github.com/cilium/cilium/pull/33819 to be reviewed and merged, as it needs to be backported as well.

**Review by gandro — APPROVED** [review]
Thank you!

**Comment by giorio94** [comment]
/test-backport-1.13

**Comment by giorio94** [comment]
/test-backport-1.13

**Comment by giorio94** [comment]
/test-backport-1.13

**Comment by giorio94** [comment]
> Blocked waiting on #33819 to be reviewed and merged, as it needs to be backported to fix CI.

Manually included as part of this backport PR, unblocking

**Review by joestringer — APPROVED** [review]

**Pull request merged**
