### PR TITLE
Update CNI to 1.2.0

### PR DESCRIPTION
**Pull request by michi-covalent**
[ upstream commit a1046bcc10b75c7130f0579d40d0529c85e1fe56 ]

Run `images/scripts/update-cni-version.sh 1.2.0` to update the CNI version.

Ref: https://github.com/containernetworking/plugins/releases/tag/v1.2.0
Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Comment by michi-covalent** [comment]
/test-backport-1.13

**Review by gandro — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]

**Comment by michi-covalent** [comment]
/test-1.19-4.9

**Comment by michi-covalent** [comment]
/test-1.24-5.4

**Comment by aanm** [comment]
@michi-covalent it looks that 1.19 failed for [the first time](https://lookerstudio.google.com/u/0/reporting/1kYVnPCU-tJCRUV2E3Pf044NFNnlFZgmW/page/IcyMB?params=%7B%22df54%22:%22include%25EE%2580%25800%25EE%2580%2580IN%25EE%2580%2580K8sAgentPolicyTest%2520Namespaces%2520policies%2520Kubernetes%2520Network%2520Policy%2520by%2520namespace%2520selector%22,%22df109%22:%22include%25EE%2580%25801%25EE%2580%2580IN%25EE%2580%25801%22%7D) with this test. I would suggest to run it five times before merging to detect the potential flake caused by this PR.

**Comment by michi-covalent** [comment]
yeah the same test failed again. very suspicious: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.9/2570/

**Comment by michi-covalent** [comment]
/test-1.19-4.9

**Comment by michi-covalent** [comment]
/test-1.19-4.9

**Comment by michi-covalent** [comment]
/test-backport-1.13

**Comment by michi-covalent** [comment]
- ✅ test-1.19-4.9: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.9/2605/

**Comment by michi-covalent** [comment]
/test-1.19-4.9

**Comment by michi-covalent** [comment]
/test-1.19-4.9

**Comment by michi-covalent** [comment]
/test-1.19-4.9

**Comment by michi-covalent** [comment]
/test-1.19-4.9

**Comment by michi-covalent** [comment]
/test-backport-1.13

**Comment by michi-covalent** [comment]
/test-backport-1.13

**Comment by michi-covalent** [comment]
test-1.22-4.9: https://github.com/cilium/cilium/issues/23317

**Comment by michi-covalent** [comment]
/test-1.22-4.9

**Comment by michi-covalent** [comment]
/ci-gke-1.13

**Comment by michi-covalent** [comment]
/ci-aks-1.13

**Comment by michi-covalent** [comment]
/test-1.22-4.9

**Comment by michi-covalent** [comment]
/test-backport-1.13

**Comment by michi-covalent** [comment]
/test-1.18-4.9

**Pull request merged**
