### PR TITLE
Remove etcd.managed Helm setting

### PR DESCRIPTION
**Pull request by joestringer**
The etcd-operator Helm templates rely on a piece of software which is
no longer maintained upstream, and it relies on outdated CRDs which are
no longer supported since Kubernetes 1.22. The setting has been hidden
and not documented for several releases, we can remove it now.

### CODE REVIEW

**Review by giorio94 — DISMISSED** [review]
Thanks a lot for this cleanup! :broom: 

The following helm values entries could now be deleted as well, as no longer used:
* https://github.com/cilium/cilium/blob/pr%2Fjoe%2Fdrop-managed-etcd/install/kubernetes/cilium/values.yaml.tmpl#L2406-L2492
* https://github.com/cilium/cilium/blob/pr%2Fjoe%2Fdrop-managed-etcd/install/kubernetes/cilium/values.yaml.tmpl#L2497-L2498
* https://github.com/cilium/cilium/blob/pr%2Fjoe%2Fdrop-managed-etcd/install/kubernetes/cilium/values.yaml.tmpl#L97-L101

And these comments should be updated not to mention *managed* anymore:
* https://github.com/cilium/cilium/blob/pr%2Fjoe%2Fdrop-managed-etcd/install/kubernetes/cilium/values.yaml.tmpl#L2499-L2504

**Review by squeed — APPROVED** [review]
Looks good, along with @giorio94's suggestions.

**Comment by joestringer** [comment]
Good pointers @giorio94 . This time I did a deeper clean by scanning through the output of `git grep -i etcd.op`.

**Comment by joestringer** [comment]
ci-ingress hit known CI issue https://github.com/cilium/cilium/issues/31857

**Review by giorio94 — CHANGES_REQUESTED** [review]
The first commit looks good to me, thanks!

I'm not sure we can merge the second one straight away without going through a proper deprecation process though, as I'm pretty sure that there are users who are still running etcd in pod network leveraging other operators (we never officially deprecated that support AFAIK), but relying upon the same reserved identities. Similarly, there are quite a few other pieces of logic spread across the code-base to enable such setup (e.g., the CRD to kvstore watch handover), which would also be need to be considered if we were to completely remove that support.

I'd also personally preserve the logic to automatically translate DNS names matching k8s services to the corresponding ClusterIP, as potentially useful in certain circumstances (and harmless in the others). Related to this, I've recently [opened a PR](https://github.com/cilium/cilium/pull/32916) to generalize and decouple that logic from the etcd.managed setting, which should already largely simplify that part.

**Review by derailed — APPROVED** [review]
@joestringer Nice work!

**Comment by joestringer** [comment]
@giorio94 Managed etcd mode was deprecated back in v1.10 with the intent to remove in v1.11, but we didn't follow up to do the full removal: https://github.com/cilium/cilium/pull/15464

**Comment by joestringer** [comment]
Probably it makes sense for me to break this down and drop the second commit for now, stick to just the Helm changes then we can revisit the other changes down the line. Thanks for the feedback @giorio94 .

**Comment by giorio94** [comment]
> @giorio94 Managed etcd mode was deprecated back in v1.10 with the intent to remove in v1.11, but we didn't follow up to do the full removal: #15464

Yeah, I totally agree with removing it. I'd just not break the support for etcd running in pod network yet, as slightly different, and not formally deprecated AFAIK. 

> Probably it makes sense for me to break this down and drop the second commit for now, stick to just the Helm changes then we can revisit the other changes down the line.

SGTM, thanks! You may want to include the `contrib/release/check-docker-images.sh` hunk as well into the first commit.

**Comment by joestringer** [comment]
@giorio94 :+1: I added a note in the upgrade guide to mention this is removed as well. We can send a deprecation notice for podnetwork etcd after this.

**Review by giorio94 — APPROVED** [review]
Thanks!

**Review by qmonnet — APPROVED** [review]

**Pull request merged**
