### PR TITLE
v1.13 backports 2023-02-23

### PR DESCRIPTION
**Pull request by sayboras**
- [ ] ~#23091 -- bpf: Fix broken remote-node identity classification (@ysksuzuki)~
    - Dropped from this backport till we resolve discussions around this change.
 - [x] #23803 -- k8s: Handle EndpointSlice AddressType field properly (@YutaroHayakawa)
 - [x] #23787 -- agent: fix incorrect deletion of veth host interfaces on bootstrap (@giorio94)
 - [x] #23857 -- Fix connectivity issue upon agent restart in case of ipv6 + direct routing + KPR replacement (@giorio94)
 - [x] #23756 -- [Docs]: Add disclaimer content to Ingress and Gateway API pages. (@kayceeDev). _Updated: I have verified this changes :heavy_check_mark:.
 - [x] #23800 -- envoy: Bump envoy to 1.23.4 (@sayboras)
 - [x] #23904 -- fix(deps): update module golang.org/x/net to v0.7.0 [security] (master) (@renovate[bot])
 - [x] #23934 -- test: Skip K8sPolicyTestExtended on the 4.19 (@brb). _Updated: I have double checked this change :heavy_check_mark:_
 - [x] #23836 -- endpoint, proxy: Fix deadlock with ipcache and K8s watcher (@christarazi). _Updated: I have double checked this change :heavy_check_mark:_
 - [x] #23866 -- helm: Prevent duplicate enable-envoy-config (@DWSR)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 23091 23803 23787 23857 23756 23800 23904 23934 23836 23866; do contrib/backporting/set-labels.py $pr done 1.13; done
```

### CODE REVIEW

**Comment by sayboras** [comment]
/test-backport-1.13

**Review by giorio94 — COMMENTED** [review]
My commits look good. Thanks!

**Comment by sayboras** [comment]
/test-1.24-4.9

**Comment by sayboras** [comment]
build-commits job timeout, so I just verify locally by running

**Review by giorio94 — APPROVED** [review]

**Comment by sayboras** [comment]
Job 'Cilium-PR-K8s-1.24-kernel-5.4' hit: https://github.com/cilium/cilium/issues/23944 (87.33% similarity).

All other jobs are completed successfully.

**Review by joestringer — CHANGES_REQUESTED** [review]
I'm a little nervous about #23091 until we resolve some further discussion on the PR, can we perhaps remove that for now?

**Comment by sayboras** [comment]
> I'm a little nervous about #23091 until we resolve some further discussion on the PR, can we perhaps remove that for now?

sure, let me drop this PR and re-run the test.

**Comment by sayboras** [comment]
/test-backport-1.13

**Review by joestringer — APPROVED** [review]
My previous blocker is resolved. I didn't review any commits.

**Review by YutaroHayakawa — APPROVED** [review]
My commits looks good to me. Thanks!

**Comment by sayboras** [comment]
/test-1.16-4.9

**Comment by sayboras** [comment]
/test-1.21-4.9

**Comment by sayboras** [comment]
/test-1.24-4.9

**Comment by sayboras** [comment]
/test-1.16-4.9

**Comment by sayboras** [comment]
/test-1.21-4.9

**Comment by sayboras** [comment]
/test-1.24-4.9

**Comment by sayboras** [comment]
/test-1.16-4.9

**Comment by sayboras** [comment]
/test-1.24-4.9

**Comment by sayboras** [comment]
/test-1.24-4.9

**Comment by sayboras** [comment]
Reviews are in, all CI jobs passed after re-triggered due to environment issue.

Merging this in.

**Pull request merged**
