### PR TITLE
Log combined stderr and stdout

### PR DESCRIPTION
**Pull request by amshinde**
On cmd.CombinedOutput returning an error, only the return code
was being logged/returned. Include the comboned stderr, stdout as well
to help understand what went wrong.

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7068)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failed due to issues with GitHub Jenkins plugin: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/9866/execution/node/7/log/

**Comment by ianvernon** [comment]
test-me-please

**Review by jrfastab — APPROVED** [review]
Thanks, much nicer than having to cut'n'paste the bpf cmds to get output.

**Comment by amshinde** [comment]
cc @mcastelino

**Pull request merged**
