### PR TITLE
Fix privileged unit tests

### PR DESCRIPTION
**Pull request by aanm**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6106)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
@tgraf should we backport this to 1.3?

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]
LGTM

**Review by tgraf — APPROVED** [review]

**Comment by aanm** [comment]
There was a green CI in https://github.com/cilium/cilium/pull/6106#issuecomment-434271887 as the failures are not related with the changes I'll merge it.

**Pull request merged**
