### PR TITLE
k8s: k8s 1.9.3 compatible version parsing

### PR DESCRIPTION
**Pull request by raybejjani**
**Summary of changes**:

On minikube 0.25.0, at least, cilium-agent cannot parse the k8s version
because ServerVersion.major and .minor are not populated. gitVersion is
and we fall back to parsing that instead.

```json
ray@Rays-MacBook-Pro:cilium (master *)$ kubectl version -o json
{
  "clientVersion": {
    "major": "1",
    "minor": "8",
    "gitVersion": "v1.8.0",
    "gitCommit": "6e937839ac04a38cac63e6a7a306c5d035fe7b0a",
    "gitTreeState": "clean",
    "buildDate": "2017-09-28T22:57:57Z",
    "goVersion": "go1.8.3",
    "compiler": "gc",
    "platform": "darwin/amd64"
  },
  "serverVersion": {
    "major": "",
    "minor": "",
    "gitVersion": "v1.9.0",
    "gitCommit": "925c127ec6b946659ad0fd596fa959be43f0cc05",
    "gitTreeState": "clean",
    "buildDate": "2018-01-26T19:04:38Z",
    "goVersion": "go1.9.1",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

**How to test (optional)**:
I ran a modified cilium daemonset (under examples/minikube/cilium.yaml) on minikube 0.25.0. I've included it below. On osx minikube mounts the whole VM host filesystem. I pointed the daemonset to run the cilium-agent I compiled in my dev-vm (itself syncing to the VM host filesystem).

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: cilium-config
  namespace: kube-system
data:
  # This etcd-config contains the etcd endpoints of your cluster. If you use
  # TLS please make sure you uncomment the ca-file line and add the respective
  # certificate has a k8s secret, see explanation bellow in the comment labeled
  # "ETCD-CERT"
  etcd-config: |-
    ---
    endpoints:
    - http://127.0.0.1:2379
    #
    # In case you want to use TLS in etcd, uncomment the following line
    # and add the certificate as explained in the comment labeled "ETCD-CERT"
    #ca-file: '/var/lib/etcd-secrets/etcd-ca'
    #
    # In case you want client to server authentication, uncomment the following
    # lines and add the certificate and key in cilium-etcd-secrets bellow
    #key-file: '/var/lib/etcd-secrets/etcd-client-key'
    #cert-file: '/var/lib/etcd-secrets/etcd-client-crt'

  # If you want to run cilium in debug mode change this value to true
  debug: "false"
  disable-ipv4: "false"
---
# The etcd secrets can be populated in kubernetes.
# For more information see: https://kubernetes.io/docs/concepts/configuration/secret
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cilium-etcd-secrets
  namespace: kube-system
data:
  # ETCD-CERT: Each value should contain the whole certificate in base64, on a
  # single line. You can generate the base64 with: $ base64 -w 0 ./ca.pem
  # (the "-w 0" generates the output on a single line)
  etcd-ca: ""
  etcd-client-key: ""
  etcd-client-crt: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cilium
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cilium
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cilium
subjects:
- kind: ServiceAccount
  name: cilium
  namespace: kube-system
- kind: Group
  name: system:nodes
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cilium
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: cilium
        kubernetes.io/cluster-service: "true"
      annotations:
        # This annotation plus the CriticalAddonsOnly toleration makes
        # cilium to be a critical pod in the cluster, which ensures cilium
        # gets priority scheduling.
        # https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: >-
          [{"key":"dedicated","operator":"Equal","value":"master","effect":"NoSchedule"}]
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      serviceAccountName: cilium
      containers:
      - image: cilium/cilium:v0.13.2
        imagePullPolicy: Always
        name: cilium-agent
        command: [ "/cilium/daemon/cilium-agent" ]
        args:
          - "--debug=$(CILIUM_DEBUG)"
          - "-t"
          - "vxlan"
          - "--kvstore"
          - "etcd"
          - "--kvstore-opt"
          - "etcd.config=/var/lib/etcd-config/etcd.config"
          - "--disable-ipv4=$(DISABLE_IPV4)"
        ports:
          - name: prometheus
            containerPort: 9090
        lifecycle:
          postStart:
            exec:
              command:
                - "/cni-install.sh"
          preStop:
            exec:
              command:
                - "/cni-uninstall.sh"
        env:
          - name: "K8S_NODE_NAME"
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: "CILIUM_DEBUG"
            valueFrom:
              configMapKeyRef:
                name: cilium-config
                key: debug
          - name: "DISABLE_IPV4"
            valueFrom:
              configMapKeyRef:
                name: cilium-config
                key: disable-ipv4
          # Note: this variable is a no-op if not defined, and is used in the
          # prometheus examples.
          - name: "CILIUM_PROMETHEUS_SERVE_ADDR"
            valueFrom:
              configMapKeyRef:
                name: cilium-metrics-config
                optional: true
                key: prometheus-serve-addr
        livenessProbe:
          exec:
            command:
            - /cilium/cilium/cilium
            - status
          # The initial delay for the liveness probe is intentionally large to
          # avoid an endless kill & restart cycle if in the event that the initial
          # bootstrapping takes longer than expected.
          initialDelaySeconds: 120
          failureThreshold: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - cilium
            - status
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
          - name: bpf-maps
            mountPath: /sys/fs/bpf
          - name: cilium-run
            mountPath: /var/run/cilium
          - name: cni-path
            mountPath: /host/opt/cni/bin
          - name: etc-cni-netd
            mountPath: /host/etc/cni/net.d
          - name: docker-socket
            mountPath: /var/run/docker.sock
            readOnly: true
          - name: etcd-config-path
            mountPath: /var/lib/etcd-config
            readOnly: true
          - name: etcd-secrets
            mountPath: /var/lib/etcd-secrets
            readOnly: true
          - name: cilium
            mountPath: /cilium
        securityContext:
          capabilities:
            add:
              - "NET_ADMIN"
          privileged: true
      hostNetwork: true
      volumes:
          # To keep state between restarts / upgrades
        - name: cilium-run
          hostPath:
            path: /var/run/cilium
          # To keep state between restarts / upgrades
        - name: bpf-maps
          hostPath:
            path: /sys/fs/bpf
          # To read docker events from the node
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
          # To install cilium cni plugin in the host
        - name: cni-path
          hostPath:
            path: /opt/cni/bin
          # To install cilium cni configuration in the host
        - name: etc-cni-netd
          hostPath:
              path: /etc/cni/net.d
        - name: cilium
          hostPath:
              path: /Users/ray/covalent/cilium
        # To read the etcd config stored in config maps
        - name: etcd-config-path
          configMap:
            name: cilium-config
            items:
            - key: etcd-config
              path: etcd.config
          # To read the k8s etcd secrets in case the user might want to use TLS
        - name: etcd-secrets
          secret:
            secretName: cilium-etcd-secrets
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
      # Mark cilium's pod as critical for rescheduling
      - key: CriticalAddonsOnly
        operator: "Exists"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cilium
rules:
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  - nodes
  - endpoints
  - componentstatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - extensions
  resources:
  - networkpolicies #FIXME remove this when we drop support for k8s NP-beta GH-1202
  - thirdpartyresources
  - ingresses
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - cilium.io
  resources:
  - ciliumnetworkpolicies
  verbs:
  - "*"
```

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
I wonder what's the outcome of this because of the watchers that we create based on the kubernetes version running

**Comment by raybejjani** [comment]
Righto. I know why this is happening.
k8s 1.9.3 did this:
`CustomResourceDefinitions: OpenAPI v3 validation schemas containing $refreferences are no longer permitted (valid references could not be constructed previously because property ids were not permitted either). Before upgrading, ensure CRD definitions do not include those $ref fields. (#58438, @carlory)`
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md#other-notable-changes

Our validation uses $refs all over. I need to figure out how to get swagger to expand them.

**Comment by raybejjani** [comment]
@eloycoto This is specifically 1.9.3
to unblock you, could you try to disable validation (hopefully it won't look at the field then) or use 1.9.2 until we sort this out?

**Comment by tgraf** [comment]
> I wonder what's the outcome of this because of the watchers that we create based on the kubernetes version running

@aanm Is this a concern before merging this or is this good to merge?

**Comment by raybejjani** [comment]
I should test more (to wip).
I looked at the NewVersion function we call (and return) and it seems to want a semver style number. the gitversion (with the leading v stripped) should be parseable and the result consistent with whatever we were using this go-version.Version (https://github.com/hashicorp/go-version/blob/master/version.go#L23:6) type for. I'm not sure if I missed anything.

**Comment by raybejjani** [comment]
I ran against my dev k8s 1.8.1 and no errors printed. I'm not sure what else to check. Any thoughts?

@aanm did you mean how we handle 1.6? do we have some case where this GetVersion thing is expected to return an error?

**Comment by raybejjani** [comment]
Ok. We use the version info here https://github.com/cilium/cilium/blob/master/daemon/k8s_watcher.go#L75-L79 and I don't see them failing as long as the version parses at all (and we'd error out if it didn't). Worst case is that we'd spawn no informers and make no CRDs or TPRs. I can add default cases to all the switch statements to at least log errors when this happens. Thoughts?

**Review by aanm — CHANGES_REQUESTED** [review]
Sorry @raybejjani I think this will cause problems here https://github.com/cilium/cilium/blob/master/daemon/k8s_watcher.go#L222

Can you change that to be "default"?

**Review by aanm — APPROVED** [review]
discussed offline, all good

**Comment by raybejjani** [comment]
Let me add a comment to the new code to avoid tears later :)

**Comment by tgraf** [comment]
> Let me add a comment to the new code to avoid tears later :)

Please add the ready to merge label when done or merge yourself ;)

**Comment by raybejjani** [comment]
Done. Until next time!

**Pull request merged**
