### PR TITLE
Added ByteDance to users.md

### PR DESCRIPTION
**Pull request by Jiang1155**
Show support for Cilium from ByteDance.

### CODE REVIEW

**Comment by xmulligan** [comment]
@Jiang1155 Thanks for adding to the doc! Can you sign off your commit so we can merge it? https://www.secondstate.io/articles/dco/

**Comment by xmulligan** [comment]
@Jiang1155 Just a friendly reminder. Can you sign off your commit so we can merge it? Let me know if you need any help :)

**Comment by Jiang1155** [comment]
Sorry for the late reply, I just notice your message.

I added sign-off in the commit message, and pushed to the patch-1 branch. But I saw it was behind master of cilium so I clicked "pull and merge" button on github. Now, my patch-1 branch shows 2 commits. One is this one. The other is a merge commit. I think I need to remove the merge commit somehow?  Can you merge it as of now?

Or I can create a new pull request since this is a simple change. 

Normally, when I saw my branch is behind the master, do I need to update my branch to make it mergeable? Or the merge process will take care of it? 

Let me know how to proceed. Thanks.

**Comment by xmulligan** [comment]
Hi @Jiang1155 , thanks for coming back to this! We can't merge it right now because the second commit isn't signed off.

It is probably easier to just close this PR and open a new one. If you do it in the GitHub UI, sign off is actually now automatically added to new PRs in the repo.

**Comment by Jiang1155** [comment]
Sure. I just opened a new one.  I will close this one. Thanks.

**Pull request closed without merging**
