### PR TITLE
v1.10 backports 2021-06-01

### PR DESCRIPTION
**Pull request by qmonnet**
* [x] #16052 -- .github: Don't persist credentials in repository (@pchaigno)
 * [x] #16126 -- docs: various fixes to documentation, notably Getting Started Guides (@nbusseneau)
 * [ ] #16263 -- docs: Fix Helm instructions for BGP (@xentobias)
 * [x] #16274 -- .github: Fix scheduled end-to-end tests (@pchaigno)
 * [x] #16293 -- docs: Fix WireGuard spelling (@gandro)
 * [x] #16081 -- docs: Update troubleshooting for 1.10 (@twpayne)
 * [x] #16268 -- pkg/k8s: ignore namespace events that do not change labels (@aanm)
 * [x] #16288 -- docs: remove 1.7 upgrade guide and add upgradeCompatibility for 1.9 (@aanm)
 * [x] #16310 -- .github: Fix concurrency group comment triggers (@pchaigno)
 * [ ] #16211 -- envoy: Remove request headers from response access logs (@jrajahalme)
 * [x] #16286 -- pkg/k8s: set right logic to ignore ipcache errors (@aanm)
 * [ ] #16271 -- endpoint: Skip waiting-to-regenerate -> waiting-for-identity state transitions (@jrajahalme)
 * [x] #16227 -- loader: Revert incorrect initialization of endpoints in chaining mode (@pchaigno)
 * [x] #16176 -- contrib: simplify check-docker-images script (@aanm)
 * [x] #16043 -- Support non-default Azure clouds (@ungureanuvladvictor)
   First commit: Update azure vendor from `v50.0.0+incompatible` instead of `v50.2.0+incompatible` as for master branch.
 * [x] #16137 -- docs: document the policy for backporting documentation changes (@qmonnet)
 * [ ] #16194 -- Make LRP restore test logic robust and optimized (@aditighag)
 * [x] #16319 -- .github: Don't wait for GKE cluster cleanup (@pchaigno)
 * [ ] #16325 -- docs: fix a typo in Helm installation documentation (@netflash)
 * [ ] #16055 -- Add missing bpftool map dumps (@h3llix)
 * [x] #12527 -- Makefile, contrib: Add script to create kind cluster (@christarazi)
 * [x] #16336 -- docs: fix some dead links (@aanm)
 * [x] #16312 -- Refactored, renamed and small misc changes in GH workflows (@aanm)
   Second commit: Update action in documentation.yaml from `actions/checkout@v1` instead of `actions/checkout@v2` as for master branch.

Skipped:

 * #16324 -- docs: add missing mount bpf fs on minikube GSG (@aanm)
   (Will be reverted in https://github.com/cilium/cilium/pull/16346; Label was removed from PR accordingly.)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 16052 16126 16263 16274 16293 16081 16268 16288 16310 16211 16286 16271 16227 16176 16043 16137 16194 16319 16325 16055 12527 16336 16312; do contrib/backporting/set-labels.py $pr done 1.10; done
```

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
My PRs look good.

**Review by ungureanuvladvictor — APPROVED** [review]
My Azure PRs look good.

**Review by nbusseneau — APPROVED** [review]
And my axe!

**Review by christarazi — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Comment by qmonnet** [comment]
test-backport-1.10

**Review by aanm — APPROVED** [review]
Looks good for my commits

**Review by gandro — APPROVED** [review]

**Comment by h3llix** [comment]
Does everyone need to approve their commits in such backport pr's ?

**Comment by pchaigno** [comment]
> Does everyone need to approve their commits in such backport pr's ?

@h3llix Good question. It's best if all authors review, but we typically only make sure that backported commits that had conflicts are reviewed. The other commits typically matter a bit less (though that doesn't mean they can't break something).

I'm not sure the backporting documentation makes that clear. If it's not the case, we should update it.

**Comment by qmonnet** [comment]
I simply rebased on top of de53e80cd71b3e421bbece251b3bac39bfe02954. No change to backported commits.

**Comment by pchaigno** [comment]
test-backport-1.10

**Comment by nathanjsweet** [comment]
I'm seeing a lot of failures for k8s1.17-kernel-4.9

**Comment by qmonnet** [comment]
Right, there are some flakes:

- `k8s-1.16-kernel-netnext` hits https://github.com/cilium/cilium/issues/12511 and https://github.com/cilium/cilium/issues/12511.
- `k8s-1.21-kernel-4.9` is documented at https://github.com/cilium/cilium/issues/16237.
- `runtime` relates to https://github.com/cilium/cilium/issues/16221.

As for `k8s-1.17-kernel-4.9`, there are 11 tests failing, and I've not managed yet to figure out if there is a root cause or if they might be independent.

**Comment by qmonnet** [comment]
New conflict, new rebase.
Still looking at the previous failure, but so far I think they might have been independent failures, documented in existing PRs.
I'll re-run the tests with the latest rebase anyway.

**Comment by qmonnet** [comment]
test-backport-1.10

**Comment by qmonnet** [comment]
Some failures again, all identifiable as documented flakes.

- `k8s-1.19-kernel-5.4` -> https://github.com/cilium/cilium/issues/16203
- `k8s-1.21-kernel-4.9` -> https://github.com/cilium/cilium/issues/16237 (fixed on master, not backported to 1.10 yet)
- `runtime` -> https://github.com/cilium/cilium/issues/16433

**Comment by nathanjsweet** [comment]
K8s-1.21-kernel-4.9 is #16237
K8s-1.19-kernel-5.4 is #16203
Runtime is #16433

**Pull request merged**
