### PR TITLE
v1.12 Backports 2023-02-01

### PR DESCRIPTION
**Pull request by qmonnet**
* [x] #21937 (@wu0407)
 * [x] #23298 (@giorio94)
 * [x] #23463 (@michi-covalent)
   * Minor conflict
 * [x] #23482 (@aanm)
 * [x] #23429 (@tommyp1ckles)
   * Minor conflict
 * [x] #23467 (@giorio94)
   * Minor conflict

Once this PR is merged, you can update the PR labels via:

```upstream-prs
$ for pr in 21937 23298 23463 23482 23429 23467; do contrib/backporting/set-labels.py $pr done 1.12; done
```

### CODE REVIEW

**Review by tommyp1ckles — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]
❤️

**Comment by pchaigno** [comment]
The build seems to be failing because of the backport of https://github.com/cilium/cilium/pull/23467. @giorio94 would you know what is missing here?

**Comment by giorio94** [comment]
> The build seems to be failing because of the backport of https://github.com/cilium/cilium/pull/23467. @giorio94 would you know what is missing here?

It should be this [reset method](https://github.com/cilium/cilium/blob/147b72eb055345c340f3c5d420b4f38a549b533d/pkg/backoff/backoff.go#L143) that was not yet present.

**Comment by pchaigno** [comment]
@giorio94 Thanks for checking! Would it be safe to backport the whole of https://github.com/cilium/cilium/pull/21937?

**Comment by giorio94** [comment]
> @giorio94 Thanks for checking! Would it be safe to backport the whole of https://github.com/cilium/cilium/pull/21937?

@pchaigno To me it seems safe to back port also that PR.

**Review by nbusseneau — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
Besides the need to backport also #21937 as discussed above, my PRs look good. Thanks!

**Comment by pchaigno** [comment]
@giorio94 Could I also ask you to review the https://github.com/cilium/cilium/pull/21937 backport if you feel familiar enough with that code?

**Comment by pchaigno** [comment]
/test-backport-1.12

**Comment by giorio94** [comment]
> @giorio94 Could I also ask you to review the #21937 backport if you feel familiar enough with that code?

@pchaigno The backport of that PR looks good to me.

I had a look at the linting failures, and they trace to the change of a map key type introduced in the first commit of #21161. This occurs a couple of times in the tests (e.g., [here](https://github.com/cilium/cilium/blob/pr/v1.12-backport-2023-02-01/pkg/k8s/service_cache_test.go#L476)). Changing `cmtypes.MustParseAddrCluster("2.2.2.2")` to just `"2.2.2.2"` should solve the problem.

**Comment by pchaigno** [comment]
@giorio94 Thanks for the tip!

**Comment by pchaigno** [comment]
/test-backport-1.12

**Comment by joestringer** [comment]
@qmonnet just a heads up, if you need to add the ```` ```upstream-prs ...``` ```` section after posting the backport, please ensure it exactly matches the format for other PRs. In this case I found that the `$` was missing at the start, which messed up the release notes tool. Maybe we can look at making the release notes tool more resilient to such situations :thinking: . I would also be interested if there are some underlying reasons why the backporting process here did not generate the same standardized issue format since the backporting tool works very closely with the release notes generator to make sure the release processes are smooth.

**Comment by qmonnet** [comment]
@joestringer :scream: Apologies for making the release harder! I didn't realise removing the prompt symbol here would break the release tool - I didn't realised that block was being parsed, even. Let me investigate on how this happened.

**Comment by joestringer** [comment]
@qmonnet No worries! This sort of thing is pretty hard to predict. Thanks for following up.

**Pull request merged**
