### PR TITLE
docs: Update Sphinx and its dependencies, Cilium theme

### PR DESCRIPTION
**Pull request by qmonnet**
I rebased our fork of the Sphinx theme here: https://github.com/cilium/sphinx_rtd_theme/tree/cilium/rebase-2023-09

Now we can use this newer version in the docs. We can also update a bunch of other dependencies that were stuck because of the docutils version formerly required by the theme.

- docs: Drop is_html5_writer_available() in cilium_external_links.py
- docs: Update Sphinx (7.1.2) and dependencies
- docs: Re-enable Sphinx output in check-build.sh
- ci: update docs-builder

v2 of https://github.com/cilium/cilium/pull/28171, from Cilium repo for the deployments to work.

### CODE REVIEW

**Comment by qmonnet** [comment]
[Netlify preview](https://deploy-preview-28172--docs-cilium-io.netlify.app/)

**Review by nbusseneau — APPROVED** [review]
FWIW, we don't need to run `/test` here, the documentation workflow runs automatically on `pull_request` events.

**Comment by qmonnet** [comment]
@nbusseneau My understanding is that I need to /test anyway if I want the checks to be all green and the PR to either get the green badge or get mergeable by me, directly. Non-relevant tests for docs PR are skipped anyway.

**Review by learnitall — APPROVED** [review]
Great! I took a look at the netifly preview and nothing that I could see stood out or looked weird.

**Comment by nbusseneau** [comment]
> My understanding is that I need to /test anyway if I want the checks to be all green and the PR to either get the green badge or get mergeable by me, directly. Non-relevant tests for docs PR are skipped anyway.

True, I just typically set it to `ready-to-merge` and state why `/test` is not necessary in a comment, but both approaches work!

**Pull request merged**
