### PR TITLE
v1.10: Update Go to 1.16.15

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.10

**Review by gandro — APPROVED** [review]

**Comment by tklauser** [comment]
/test-backport-1.10

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
/test-1.16-netnext

**Comment by tklauser** [comment]
/test-1.19-5.4

**Comment by tklauser** [comment]
runtime test failure is #18919: https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1479/

All other tests passed and two reviewers approved. Marking as ready to merge.

**Pull request merged**
