### PR TITLE
1.3 backports 12-12-18

### PR DESCRIPTION
**Pull request by nebril**
#6435 
#6427 
#6403 
#6401 
#6388 

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6445)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-missing-k8s

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-docs-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
test-missed-k8s

**Comment by nebril** [comment]
test-me-please

**Pull request merged**
