### PR TITLE
v1.14 backports 2023-11-20

### PR DESCRIPTION
**Pull request by sayboras**
- [x] #27007 -- metrics: fix potential conflict on metrics registration (@ysksuzuki)
 - [x] #29178 -- ci-ipsec-upgrade: Do not run conn tests after installing Cilium (@brb)
    - :warning: minor conflict 
 - [x] #29189 -- ci-ipsec-upgrade: Check for errors (@brb)
    - :warning: minor conflict 

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 27007 29178 29189; do contrib/backporting/set-labels.py $pr done 1.14; done
```

### CODE REVIEW

**Review by julianwiedmann — APPROVED** [review]

**Comment by sayboras** [comment]
/test-backport-1.14

**Review by brb — APPROVED** [review]
Thanks!

**Review by ysksuzuki — APPROVED** [review]
Thanks! LGTM

**Review by nbusseneau — APPROVED** [review]

**Review by lmb — APPROVED** [review]

**Comment by christarazi** [comment]
@lmb Just a heads up when merging backport PR to remember to run the scripts to set the labels as described in the PR description. Our release scripts rely on this process and may cause at worst missed PRs into releases and at best, missing release notes for PRs that did land.

**Comment by lmb** [comment]
Ok!

**Comment by aanm** [comment]
> @lmb Just a heads up when merging backport PR to remember to run the scripts to set the labels as described in the PR description. Our release scripts rely on this process and may cause at worst missed PRs into releases and at best, missing release notes for PRs that did land.

@christarazi we already have automation that does this https://github.com/cilium/cilium/actions/workflows/call-backport-label-updater.yaml

/cc @lmb

**Comment by christarazi** [comment]
@aanm Oh I didn't realize that. That's great and I wonder why it didn't properly work for this PR. I had to manually fix up some backport labels on PRs, so not sure what went wrong.

**Comment by sayboras** [comment]
Thanks all. 

It seems like the backport script didn't throw the errors, or I overlooked them, hence the pending-backport/1.14 label was not set for mentioned PRs. 

Will be more cautious next time :bow:

**Pull request merged**
