### PR TITLE
docs: fix EKS Kubernetes compatibility link 

### PR DESCRIPTION
**Pull request by fjvela**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed or remove this section! -->
```

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Thank you for the PR @fjvela, the change looks good.

The bot is complaining about a missing sign-off in the merge commit. The Cilium project doesn't use merge commits, to keep clean git history, and if there are no conflicts then there is no no need to keep your branch always up to date (if there are conflicts then please use git rebase). Could you drop the merge commit and force push?

**Comment by fjvela** [comment]
@lambdanis welcome!

Done!

**Review by ghost — APPROVED** [review]
Thanks!

**Pull request merged**
