### PR TITLE
docs: add warning in docs for older versions

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

Fixes https://github.com/cilium/cilium/issues/5726

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5760)

### CODE REVIEW

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
Depends on https://github.com/humitos/sphinx-version-warning/pull/16

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
Before merging, switch readthedocs to python3

**Comment by jrfastab** [comment]
LGTM would have saved some hassle on my side to get python2 working with correct libs.

**Comment by jrfastab** [comment]
Although why is the backports tag needed?

**Comment by aanm** [comment]
@jrfastab the library needs to be in effect since version 1.0 in order to show the banner the more recent version is available.

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-docs-please

**Comment by ianvernon** [comment]
@aanm I can't build it locally in my VM? :/ 

```
$ make html
! (sphinx-build -b spelling -d "_build/doctrees" "." "_build/spelling" -q -E  && touch check-build.ok) \
	| grep -v -e "tabs assets" -e "misspelled words"
/home/vagrant/.local/lib/python2.7/site-packages/sphinx/application.py:402: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  RemovedInSphinx20Warning)

Exception occurred:
  File "/home/vagrant/.local/lib/python2.7/site-packages/versionwarning/extension.py", line 5, in <module>
    from .signals import generate_versionwarning_data_json
  File "/home/vagrant/.local/lib/python2.7/site-packages/versionwarning/signals.py", line 41
    **{config.versionwarning_message_placeholder: '<a href="#"></a>'},
                                                                     ^
SyntaxError: invalid syntax
The full traceback has been saved in /tmp/sphinx-err-Z3e6K1.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:53: recipe for target 'check-build' failed
make: *** [check-build] Error 1
```

EDIT: looks like I can't even build master in the dev VM. Not sure why, will investigate.

EDIT 2: This was using the `make html` target directly in the VM instead of the Docker image way of building the docs. I'll try that instead.

EDIT 3: With master, running `make render-docs` works, but with this PR, it does not work locally:

```
$ make render-docs
...
Successfully tagged cilium/docs-builder:latest
docker container rm -f docs-cilium >/dev/null 2>&1 || true
docker container run --rm -ti -u $(id -u):$(id -g ianvernon) -v $(pwd):/srv/ cilium/docs-builder /bin/bash -c 'make html'
! (sphinx-build -b spelling -d "_build/doctrees" "." "_build/spelling" -q -E  && touch check-build.ok) \
	| grep -v -e "tabs assets" -e "misspelled words"
/usr/local/lib/python3.6/site-packages/sphinx/application.py:402: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  RemovedInSphinx20Warning)

Exception occurred:
  File "/usr/local/lib/python3.6/site-packages/versionwarning/signals.py", line 66, in generate_versionwarning_data_json
    os.mkdir(data_path)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/versionwarning/_static/data'
The full traceback has been saved in /tmp/sphinx-err-re2r22dc.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:56: check-build] Error 1
make: *** [render-docs] Error 2
```

**Comment by aanm** [comment]
@ianvernon fixed in last commit please try again

**Comment by aanm** [comment]
test-docs-please

**Comment by ianvernon** [comment]
It fails for a different reason this time when ran locally:
```
 make render-docs
can't load package: package github.com/cilium/cilium/test/bpf: C source files not allowed when not using cgo or SWIG: bpf-event-test.c unit-test.c
grep -v -E "(SOURCE|GIT)_VERSION" .gitignore >.dockerignore
echo ".*" >>.dockerignore # .git pruned out
cp -r ./api ./Documentation/_api
docker image build -t cilium/docs-builder --build-arg=UID=$(id -u) --build-arg=GID=$(id -g ianvernon) -f Documentation/Dockerfile ./Documentation; \
	  (ret=$?; rm -r ./Documentation/_api && exit $ret)
Sending build context to Docker daemon  38.07MB
Step 1/17 : FROM docker.io/library/python:3.6.7-alpine3.8
 ---> a3184dc36856
Step 2/17 : LABEL maintainer="maintainer@cilium.io"
 ---> Using cache
 ---> 58bf91538c37
Step 3/17 : ENV DOCS_DIR=/srv/Documentation
 ---> Using cache
 ---> 73c1aec784b3
Step 4/17 : ENV API_DIR=/srv/api
 ---> Using cache
 ---> c13467e2b71c
Step 5/17 : ADD ./requirements.txt $DOCS_DIR/requirements.txt
 ---> Using cache
 ---> 9f167dbf1d09
Step 6/17 : ENV PACKAGES="    bash     ca-certificates     make     git     py-pip     sphinx-python     enchant     aspell-en "
 ---> Using cache
 ---> 25208c3ed2be
Step 7/17 : RUN apk add --no-cache --virtual --update $PACKAGES &&     pip install --upgrade pip
 ---> Using cache
 ---> 3867ebf73e68
Step 8/17 : ARG GID
 ---> Using cache
 ---> 2162e2e0371c
Step 9/17 : ARG UID
 ---> Using cache
 ---> d2661729f954
Step 10/17 : RUN addgroup -g $GID -S appuser && adduser -G appuser -D -u $UID appuser
 ---> Running in c0fcd3c3b1e1
addgroup: gid '20' in use
The command '/bin/sh -c addgroup -g $GID -S appuser && adduser -G appuser -D -u $UID appuser' returned a non-zero code: 1
make: *** [docs-container] Error 1
```

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
test-docs-please

**Comment by aanm** [comment]
@ianvernon please try again

**Comment by aanm** [comment]
do not delete branch after merging

**Review by ianvernon — APPROVED** [review]
LGTM! Running `make render-docs` locally works for me with this PR now.

**Pull request merged**
