### PR TITLE
v1.13 Backports 2024-03-19

### PR DESCRIPTION
**Pull request by gandro**
* [x] #31016 (@hemanthmalla) :warning: Conflicts, see commit description
 * [x] #31366 (@PhilipSchmid) :warning: Conflicts, see commit description
 * [x] #31387 (@YutaroHayakawa)
 * [x] #26998 (@tommyp1ckles)
 * [x] #31271 (@sayboras) :warning: Conflicts, see commit description
 * [x] #31420 (@giorio94)
 * [x] #31437 (@pchaigno)
 * [x] #31211 (@kaworu) :warning: Conflicts, see commit description

PRs skipped due to conflicts:

 * #22900 (@sayboras)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31016 31366 31387 26998 31271 31420 31437 31211
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Thanks for resolving the conflict, the changes look good to me :heavy_check_mark:

**Review by PhilipSchmid — APPROVED** [review]

**Comment by gandro** [comment]
/test-backport-1.13

**Review by giorio94 — APPROVED** [review]
My commit looks good, thanks!

**Review by pchaigno — APPROVED** [review]
All good. Thanks!

**Review by hemanthmalla — APPROVED** [review]
LGTM. Thanks for dealing with the conflicts.

**Review by YutaroHayakawa — APPROVED** [review]
Thanks!

**Review by kaworu — APPROVED** [review]
My patch LGTM, thanks for handling the conflicts :pray:

**Review by jrajahalme — APPROVED** [review]
Checked out the ipam commit for Tom.

**Pull request merged**
