### PR TITLE
fix:'go routine' should be 'goroutine'

### PR DESCRIPTION
**Pull request by yulng**
Signed-off-by: yulng <wei.yang@daocloud.io>

Usually, goroutine is represented by goroutine

Thanks

### CODE REVIEW

**Review by mainred — COMMENTED** [review]
Good catch and thank you.

There'll be more search results than you find in this current PR, will you fix them as well? like

https://github.com/cilium/cilium/blob/17ad4e16883b4fb2d5cd0424d0c016f7d31c751b/daemon/cmd/daemon.go#L737

Please also ignore case when searching.

**Comment by yulng** [comment]
> Good catch and thank you.
> 
> There'll be more search results than you find in this current PR, will you fix them as well? like
> 
> https://github.com/cilium/cilium/blob/17ad4e16883b4fb2d5cd0424d0c016f7d31c751b/daemon/cmd/daemon.go#L737
> 
> Please also ignore case when searching.

changed all
thanks

**Review by kaworu — APPROVED** [review]
Thanks for the cleanup!

**Review by christarazi — APPROVED** [review]

**Review by mainred — APPROVED** [review]

**Comment by aditighag** [comment]
Only fixing logs and comments, so no need to run the full CI.

**Review by aditighag — APPROVED** [review]

**Pull request merged**
