### PR TITLE
cilium: streamline lb mode config to lb alg

### PR DESCRIPTION
**Pull request by borkmann**
(see commit desc)

### CODE REVIEW

**Review by dylandreimerink — APPROVED** [review]
Changes look good to me :rocket:

**Review by nebril — APPROVED** [review]

**Review by aspsk — APPROVED** [review]

**Review by ghost — APPROVED** [review]
docs good

**Review by tklauser — APPROVED** [review]
LGTM for my code owners

**Review by learnitall — APPROVED** [review]
Looks good for API!

**Review by derailed — APPROVED** [review]
@borkmann Nice work Daniel!

**Pull request merged**
