### PR TITLE
Merge v1.10 branch to pr/jibi/fix-differentiate-udp-tcp-svc-upgrade

### PR DESCRIPTION
**Pull request by briantopping**
This PR is to update @jibi's PR with a merge from the v1.10 branch.

### CODE REVIEW

**Comment by pchaigno** [comment]
I'm not sure I understand the goal here. We would need to force-push after a rebase to update the branch anyway, so this won't work. If you want to take over that effort and think you found a solution to the current blocker(s), it might be best to just open a new pull request against master.

**Comment by briantopping** [comment]
Was just trying to keep the original PR branch alive. Wasn't aware that it would require a FP, should be no different than if @jibi had made the same merge to bring it up to date. I considered marking it as draft but it wasn't intended to be merged to a production branch.

**Comment by pchaigno** [comment]
> Wasn't aware that it would require a FP, should be no different than if @jibi had made the same merge to bring it up to date.

Absolutely. Gilberto would do that by rebasing and force pushing, to keep a clean commit history, without merge commits.

> I considered marking it as draft but it wasn't intended to be merged to a production branch.

No problem. I'm just marking as draft to avoid the review requests.

**Comment by briantopping** [comment]
Thanks for the insights. I feel like my initial lack of vision as to why the original PR was unworkable may require a lot of coaching to get this across the line. So I'm nervous about committing to it as it may take longer than the few weeks I have before more income generation starts. I do have it set up in Delve over the weekend and it's top-of-list right now though. 

Curious, are traditional merges without rebase discouraged to the point of not being an option?

**Comment by pchaigno** [comment]
> Curious, are traditional merges without rebase discouraged to the point of not being an option?

I think so, yes. AFAIK, that's why merging without rebase is disabled for pull requests in this repository.

**Pull request closed without merging**
