### PR TITLE
bpf: misc cleanups

### PR DESCRIPTION
**Pull request by julianwiedmann**
Two small drive-by cleanups, while reviewing code in this area.

### CODE REVIEW

**Comment by borkmann** [comment]
ack, both lgtm

**Review by borkmann — APPROVED** [review]

**Comment by borkmann** [comment]
interesting, looks like ARPing test failed 
```
	 [12:48:52] FAIL: node_linux_test.go:2248: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
	 [12:48:52] 
	 [12:48:52] node_linux_test.go:2452:
	 [12:48:52]     // deleteNeighbor is invoked async too
	 [12:48:52]     wait(nodev1.Identity(), "veth0", nil, true)
	 [12:48:52] node_linux_test.go:2369:
	 [12:48:52]     c.Assert(err, check.IsNil)
	 [12:48:52] ... value *errors.errorString = &errors.errorString{s:"timeout reached while waiting for condition"} ("timeout reached while waiting for condition")
	 [12:48:52] 
	 [12:48:52] level=warning msg="Attempted to deallocate a node ID that wasn't allocated" nodeID=0 subsys=linux-datapath
	 [12:48:52] level=warning msg="Attempted to deallocate a node ID that wasn't allocated" nodeID=0 subsys=linux-datapath
	 [12:48:52] OOPS: 35 passed, 1 FAILED
```

**Comment by julianwiedmann** [comment]
> interesting, looks like ARPing test failed
> 
> ```
> 	 [12:48:52] FAIL: node_linux_test.go:2248: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
> 	 [12:48:52] 
> 	 [12:48:52] node_linux_test.go:2452:
> 	 [12:48:52]     // deleteNeighbor is invoked async too
> 	 [12:48:52]     wait(nodev1.Identity(), "veth0", nil, true)
> 	 [12:48:52] node_linux_test.go:2369:
> 	 [12:48:52]     c.Assert(err, check.IsNil)
> 	 [12:48:52] ... value *errors.errorString = &errors.errorString{s:"timeout reached while waiting for condition"} ("timeout reached while waiting for condition")
> 	 [12:48:52] 
> 	 [12:48:52] level=warning msg="Attempted to deallocate a node ID that wasn't allocated" nodeID=0 subsys=linux-datapath
> 	 [12:48:52] level=warning msg="Attempted to deallocate a node ID that wasn't allocated" nodeID=0 subsys=linux-datapath
> 	 [12:48:52] OOPS: 35 passed, 1 FAILED
> ```

-> opened https://github.com/cilium/cilium/issues/24326, re-running.

**Pull request merged**
