### PR TITLE
Remove deprecated CiliumEndpoint fields

### PR DESCRIPTION
**Pull request by tgraf**
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10509)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — CHANGES_REQUESTED** [review]
Because the endpoint status structure is being modified we need to bump https://github.com/cilium/cilium/blob/9779b09b6a19b461ab04c97a4cac8c6f506c3eef/pkg/k8s/apis/cilium.io/v2/register.go#L45

Also, by bumping that version, we will brake downgrade path as that structure will no longer exist if the user wants to downgrade from 1.8 to 1.7.

I would only keep the changes in `pkg/endpoint/endpoint_status.go` plus the version upgrade and remove the deprecated fields from `EndpointStatus` later on probably once we don't support downgrade to 1.8 (possibly in 1.10)

**Comment by tgraf** [comment]
> Also, by bumping that version, we will brake downgrade path as that structure will no longer exist if the user wants to downgrade from 1.8 to 1.7.

Why does it need to be bumped? None of the fields are changing. The CRV remains identical. Why would downgrade break? If an upgrade occurred then the old CEP CRD is already registered so it will be unchanged and rollback is possible. The removed fields have been marked as deprecated for a long time and no code should depend on it. If it depends on them, it should break.

**Comment by aanm** [comment]
> > Also, by bumping that version, we will brake downgrade path as that structure will no longer exist if the user wants to downgrade from 1.8 to 1.7.
> 
> Why does it need to be bumped? None of the fields are changing. The CRV remains identical. Why would downgrade break? If an upgrade occurred then the old CEP CRD is already registered so it will be unchanged and rollback is possible. The removed fields have been marked as deprecated for a long time and no code should depend on it. If it depends on them, it should break.

I had the impression that we had a CRV for CEP.

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
> I had the impression that we had a CRV for CEP.

Thanks for double checking

**Pull request merged**
