### PR TITLE
docs(users): add archer aviation

### PR DESCRIPTION
**Pull request by hongbo-miao**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

Add Archer Aviation in the user list.

### CODE REVIEW

**Review by xmulligan — APPROVED** [review]

**Comment by xmulligan** [comment]
Thanks for the addition!

**Comment by julianwiedmann** [comment]
@xmulligan huh, when did we start to run e2e CI on these PRs? :raised_eyebrow:

Could you look into excluding it in https://github.com/cilium/cilium/blob/main/.github/ariane-config.yaml ?

**Pull request merged**
