### PR TITLE
Fix permission issue when copying cni plugins onto host path

### LINKED ISSUE #24889: cilium init container failed to copy cni onto hostpath due to permission denied
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Install cilium by setting the cni binaries path, the init contaienrd 'install-cni-binaries' will failed to copy cni plugins onto the host path due to permission denied error when the path is not root permission, like the following.

You can see the cni folder is owned by user 1999 with 700 permission. If not privileged, the init container can never copy the bins to the host path.
image

```
[root@ip-10-164-32-33 charts]# kubectl logs -f cilium-gmq42 -n kube-system -c install-cni-binaries
Installing loopback driver...
cp: cannot stat '/host/opt/cni/bin/loopback': Permission denied
Installing cilium-cni to /host/opt/cni/bin/ ...
rm: cannot remove '/host/opt/cni/bin/cilium-cni.new': Permission denied
cp: failed to access '/host/opt/cni/bin/.cilium-cni.new': Permission denied
```

I've already set privilege as true, but it doesn't work. 
```
helm install cilium cilium-1.13.1.tgz -n kube-system \
    --set cni.binPath=/opt/cdf/cni \
    --set cni.confPath=/opt/cdf/cni/conf \
    --set cluster.name=cdf-kubernetes \
    --set ipam.mode=kubernetes \
    --set securityContext.privileged=true \
    --set kubeProxyReplacement=strict \
    --set k8sServiceHost=${API_SERVER_IP} \
    --set k8sServicePort=${API_SERVER_PORT}

```

After I check the yaml file, I found init container 'install-cni-binaries' didn't have securityContext.privileged settings inside the yaml like other init containers do. Refer to : 
https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L674-L680

I think this is a defect and I will create a PR for this later to fix this issue. 
Here is the PR: https://github.com/cilium/cilium/pull/24891

### Cilium Version

cilium-cli: v0.13.2 compiled with go1.20.2 on linux/amd64
cilium image (default): v1.13.1
cilium image (stable): v1.13.1
cilium image (running): v1.13.1

### Kernel Version

Linux ip-10-164-32-33.us-west-2.compute.internal 4.18.0-348.el8.x86_64 https://github.com/cilium/cilium/pull/1 SMP Mon Oct 4 12:17:22 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"db61bf1bb93524ed38d80018b6490f910358fb05", GitTreeState:"clean", BuildDate:"2023-03-15T03:13:46Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"db61bf1bb93524ed38d80018b6490f910358fb05", GitTreeState:"clean", BuildDate:"2023-03-15T03:10:15Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by JohnJAS**
Fix permission issue when copying cni plugins onto host path.

The root cause is that the init container 'install-cni-binaries' didn't have securityContext.privileged settings inside the yaml like other init containers do. It leads to that it failed to copy cni binaries onto the hostpath which has no root permisison.

Fixes: https://github.com/cilium/cilium/issues/24889

Signed-off-by: Joseph Sheng [jiajun.sheng@microfocus.com](mailto:jiajun.sheng@microfocus.com)

### CODE REVIEW

**Comment by tommyp1ckles** [comment]
Think the change makes sense

CC @squeed I'm looking at your last change here: e1a46216b4dfba98a13f5b32b1272c137b2cc923. Was the intention that this works without the privileged init container?

**Comment by tommyp1ckles** [comment]
As well, thanks for the contribution!

**Review by gandro — APPROVED** [review]
Thanks!

**Comment by squeed** [comment]
I'm surprised this is necessary - @JohnJAS, what sort of issues did you have? Why was the `privileged` flag required?

**Comment by JohnJAS** [comment]
> I'm surprised this is necessary - @JohnJAS, what sort of issues did you have? Why was the `privileged` flag required?

**Comment by JohnJAS** [comment]
> I'm surprised this is necessary - @JohnJAS, what sort of issues did you have? Why was the `privileged` flag required?

@squeed  If cilium agent pod was started as root user, the root user inside container could not directly copy stuffs to a folder on hostpath which is not owned by root user. It needs `privileged` in this case. And another init contianer `mount-cgroup` has the same issue but it has the `privileged` flag. 
https://github.com/cilium/cilium/blob/5ca3696faef6feca006d2cabc1766542b76060f3/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L469-L471
IMO, if `mount-cgroup` container has the `privileged` flag, so as the 'install-cni-binaries' .

Please refer to more details in https://github.com/cilium/cilium/issues/24889.

**Review by squeed — APPROVED** [review]

**Review by tommyp1ckles — APPROVED** [review]

**Comment by JohnJAS** [comment]
hi @gandro, i found that the CI test due to the connection timed out, but i think it was not related to the code change. 
`Err:1 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libnss-systemd amd64 249.11-0ubuntu3.9
  Could not connect to azure.archive.ubuntu.com:80 (52.147.219.192), connection timed out`
I commented `\test` but it didn't trigger another CI test. What else should I do for this PR?

**Comment by gandro** [comment]
>  I commented \test but it didn't trigger another CI test. What else should I do for this PR?

At the moment, only contributors with the commit bit can trigger the tests. Feel free to ping me or `@cilium/tophat` if you require the tests to be re-run. 

>  i found that the CI test failed due to the connection timed out, but i think it was not related to the code change.

There are multiple different test failures. Many of them have Cilium in a CrashLoopBackoff. Just looking at "Suite-k8s-1.25.K8sDatapathConfig Transparent encryption DirectRouting Check connectivity with transparent encryption and direct routing with bpf_host", the reason for the crash is:

```
level=fatal msg="auto-direct-node-routes cannot be used with tunneling. Packets must be routed through the tunnel device." subsys=daemon
```

This is fortunately an unrelated issue:

- https://github.com/cilium/cilium/issues/15474

 We recently renamed that flag and the test driver code is using the new flag, where as you branch does not yet understand it. Could you rebase your PR on main to pull in the recent changes? After that, we can re-run CI again and triage the failures again.

**Comment by JohnJAS** [comment]
@gandro it's done, thanks for the reply ;-)

**Pull request merged**
