### PR TITLE
Fix race condition on cilium_ratelimit map

### PR DESCRIPTION
**Pull request by pchaigno**
First two commits are preparatory work and third one actually contains the fix. See their descriptions for details.

### CODE REVIEW

**Review by dylandreimerink — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by tklauser** [comment]
@pchaigno While backporting this PR I've hit some conflicts because of the ratelimit map not existing in `v1.16`, i.e. https://github.com/cilium/cilium/pull/29711 which added the map wasn't backported to `v1.16` it seems. Should we backport #29711 as well, just resolve conflicts or skip this PR from being backported?

**Comment by pchaigno** [comment]
@tklauser My bad, we should skip it. For some reason, I thought we had had that map for a while.

**Pull request merged**
