### PR TITLE
v1.13 backport 2023-01-23 

### PR DESCRIPTION
**Pull request by borkmann**
* [x] https://github.com/cilium/cilium/pull/22653
 * [x] https://github.com/cilium/cilium/pull/23020

Fixes: #22833

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 22653 23020; do contrib/backporting/set-labels.py $pr done 1.13; done
```

### CODE REVIEW

**Comment by borkmann** [comment]
(ci-l4lb-1.13 is green)

**Review by brb — APPROVED** [review]
I think the last arg in tests-l4lb-v1.13.yaml is noop:
```
cd ${{ github.workspace }}/test/l4lb && sudo ./test.sh ${{ github.repository_owner}} ${{ steps.vars.outputs.sha }} ${{ github.workspace }}/pull-request/install/kubernetes/cilium
```
The rest LGTM.

**Comment by borkmann** [comment]
> I think the last arg in tests-l4lb-v1.13.yaml is noop:
> 
> ```
> cd ${{ github.workspace }}/test/l4lb && sudo ./test.sh ${{ github.repository_owner}} ${{ steps.vars.outputs.sha }} ${{ github.workspace }}/pull-request/install/kubernetes/cilium
> ```

Good point, I'll check the diff on master. (This has no additional code change for v1.13 branch.)

**Comment by ldelossa** [comment]
/test-backport-1.13

**Comment by borkmann** [comment]
> /test-backport-1.13

(fyi, changes in here are only relevant to the l4lb test suite which is green as per above comment, nothing should be affected outside of it.)

**Review by nbusseneau — APPROVED** [review]

**Pull request merged**
