### PR TITLE
k8s: Update dependencies to v0.26.0

### PR DESCRIPTION
**Pull request by sayboras**
As k8s 1.26.0 is released, we can just replace RC version to v0.26.0

Relates #22270

Signed-off-by: Tam Mach <tam.mach@cilium.io>

### CODE REVIEW

**Comment by sayboras** [comment]
Not sure why the reviewer is not automatically assigned for vendor team, my hunch is that all members are on leave :thinking:. Hence, I just add tophat team instead.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
> Not sure why the reviewer is not automatically assigned for vendor team, my hunch is that all members are on leave thinking. Hence, I just add tophat team instead.

Yep, we have three members and they are all out this week.

I've reviewed and there are no new deps, only updates, so I think we can skip the cilium/vendor review and merge.

**Pull request merged**
