### PR TITLE
wireguard: Reject duplicate public keys

### PR DESCRIPTION
**Pull request by gandro**
This fixes an issue where a malicious node could duplicate another node's public
key and thereby force all cilium-agent instances to overwrite the
original node's WireGuard peer.

While the impersonating node cannot decrypt any traffic (it does not
know the original node's public key, nor would traffic be redirected to
the impersonating node due to the lack of AllowedIPs on the
impersonating peer entry), the impersonating node could still effectively
deny any traffic to the original node.

This commit fixes the issues by keeping track of which node has added a
given public key. Because node names are guaranteed to be unique, only
one node can own a certain public key this way. Any attempt to upsert a
public key already owned by another node will be rejected and a warning
will be emitted in the cilium-agent logs.

### CODE REVIEW

**Review by christarazi — APPROVED** [review]

**Comment by gandro** [comment]
Hit the following flakes 

- #18318 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/977/
- https://github.com/cilium/cilium/issues/17270 https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/8104/testReport/junit/Suite-k8s-1/20/K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter_service_connectivity/ (might be a different issue though)
- https://github.com/cilium/cilium/issues/18073 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-net-next/953/ (might be a different issue though)
- https://github.com/cilium/cilium/runs/5855518045?check_suite_focus=true failed during the cleanup?

I'm not 100% certain about the flakes, but it's clear all of them are unrelated, as none of them have WireGuard enabled (and this PR only touches code which requires WireGuard to be enabled)

**Comment by gandro** [comment]
/test-1.22-4.19

**Comment by gandro** [comment]
/test-1.23-net-next

**Review by brb — APPROVED** [review]

**Review by cure53 — COMMENTED** [review]
:heavy_check_mark: LGTM

**Pull request merged**
