### PR TITLE
Fix hairpin flows in CNI-chaining mode

### LINKED ISSUE #9347: Pod can not reach itself through clusterIP service in EKS chaining mode
Connection from POD to itself through ClusteIP is not routable in Cilium EKS CNI chaining mode.
It works when trying EKS without Cilium

## Bug report

**General Information**

- Cilium version 1.6.2 and 1.6.1
- Kernel version Linux frontend-7976fcf949-q5br8 4.14.133-113.112.amzn2.x86_64 #1 SMP Tue Jul 30 18:29:50 UTC 2019 x86_64 GNU/Linux

- Orchestration system version in use 
AWS EKS cluster, built using eksctl
https://cilium.readthedocs.io/en/stable/gettingstarted/k8s-install-eks/
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**How to reproduce the issue**

1. create EKS cluster with cilium following getting started guide
2. install 
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/1.6.2/examples/kubernetes/connectivity-check/connectivity-check.yaml
3. reduce number of echo pods to 1
4. perform connection from pod to itself through echo service

Result: 
Connection is stack. 

cilium monitor:
```
-> stack flow 0xc8fc37a identity 54168->2 state new ifindex 0: 169.254.42.1:55742 -> 192.168.54.56:8080 tcp SYN
```

### PR DESCRIPTION
**Pull request by brb**
This PR fixes hairpin flows (aka loopback svc) when `ENABLE_ROUTING` is disabled.

In the latter case, a packet to self is returned to stack. If the packet is routed back via the interface it came from (observed with `aws-cni` in the CNI-chaining mode), the kernel will drop the packet.

To fix this, we allow the (skb) redirection of such flows even if `ENABLE_ROUTING` is disabled.

We could have improved the performance by avoiding the endpoint lookup in the BPF map for the hairpin flows, but that would require adding more vars to `lxc_config.h`, and also modifying `ipv{4,6}_local_delivery()` which would increase the datapath code complexity from the readability perspective.

Also, this PR adds a CI test for the loopback svc. However, currently we don't have any test which would run with `ENABLE_ROUTING` disabled. Therefore, the test case doesn't test with the option disabled. This will change once we run tests on e.g. AWS EKS. Anyway, I have manually tested the fix on AWS EKS.

Fix #9347 

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9399)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]
CI bits LGTM

**Review by joestringer — APPROVED** [review]
Nice work!

**Pull request merged**
