### PR TITLE
Slim down Node handler interface

### PR DESCRIPTION
**Pull request by bimmlerd**
Review commit by commit, though changes shouldn't be too large

I was looking into `NodeHandler` for a [related PR](https://github.com/cilium/cilium/pull/25419), and noticed that one has to stub out quite a few methods to implement the interface, even if the code is just interested in getting notifed on `Node{Add,Update,Delete}`. That seemed suboptimal, so this series splits the `NodeHandler` interface in three more focussed interfaces. Purely cosmetic change, no (intentional) functional changes.

A next step might be to look into breaking up the `linuxNodeHandler`, but that's stuff for another PR.

cc @gandro

### CODE REVIEW

**Review by chancez — APPROVED** [review]
LGTM on hubble side. I've been wanting to fix this for a while myself, especially since I've seen a lot more methods added to it recently! Thanks a ton.

**Review by gandro — APPROVED** [review]
Thank you for taking care of this! :pray: :rocket:

**Review by christarazi — APPROVED** [review]
Nice cleanup! :broom:

**Comment by bimmlerd** [comment]
Rebased as this picked up a conflict with upstream.

**Review by thorn3r — APPROVED** [review]
nice work! :heavy_plus_sign:

**Review by YutaroHayakawa — APPROVED** [review]

**Comment by bimmlerd** [comment]
This picked up a new set of conflicts, rebased on latest `main` again.

**Pull request merged**
