### PR TITLE
gateway-api: Align GRPCRoute matchers with GEP specification

### LINKED ISSUE #34079: gateway-api: GRPCRoute requires explicitly specifying methods names for gRPC routes to work
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

`GRPCRoute` doesn’t support this kind of matching:
```
  rules:
    - matches:
        - method:
            service: package.name.version.Service
```

requests will fail with `Unimplemented (12): unknown service`.  `GRPCRoute` expects us to explicitly list methods like:
```
  rules:
    - matches:
        - method:
            service: package.name.version.Service
            method: SomeMethodName
        - method:
            service: package.name.version.Service
            method: AnotherMethodName
```

### How can we reproduce the issue?

Use any GRPCRoute without specifying `method` in a match rule.

### Cilium Version

any

### Kernel Version

any

### Kubernetes Version

any

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cfsnyder**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #34079

### CODE REVIEW

**Review by youngnick — APPROVED** [review]

**Comment by youngnick** [comment]
Thanks for this, nice work.

**Comment by youngnick** [comment]
However, checkpatch wants you to cut two characters off your commit message before the rest of CI will run, sorry!

**Comment by cfsnyder** [comment]
Sorry, looks like I had a couple of typos that were caught by the integration test run. I've updated the PR to fix those.

**Comment by cfsnyder** [comment]
Not sure if any of these check failures are related to my changes? It doesn't appear so to me, based upon the errors in the job output, but please let me know if I'm wrong.

**Comment by youngnick** [comment]
@cfsnyder, any chance you could rebase this change from upstream `main`? I suspect that there's some build error that's been fixed there.

**Comment by cfsnyder** [comment]
updated @youngnick

**Comment by rauanmayemir** [comment]
What needs to happen for this to go into v1.16?

**Pull request merged**
