### PR TITLE
v1.12 Backports 2023-12-07

### PR DESCRIPTION
**Pull request by sayboras**
* [x] #24836 (@darox)
 * [ ] #29511 (@ayuspin)
 * [ ] #29610 (@ayuspin)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 24836 29511 29610
```

### CODE REVIEW

**Review by ti-mo — APPROVED** [review]

**Review by ti-mo — APPROVED** [review]

**Comment by sayboras** [comment]
/test-1.22-4.9

**Comment by nbusseneau** [comment]
@sayboras Sorry, I messed up your PR for a few seconds by force-pushing because I was doing a regular backport round with the same branch name 😢 Restored previous state.

**Comment by sayboras** [comment]
/test-1.19-4.9

**Review by darox — APPROVED** [review]

**Pull request merged**
