### PR TITLE
Update Go to 1.20.1

### PR DESCRIPTION
**Pull request by tklauser**
> go1.20.1 (released 2023-02-14) includes security fixes to the
> crypto/tls, mime/multipart, net/http, and path/filepath packages, as
> well as bug fixes to the compiler, the go command, the linker, the
> runtime, and the time package.

Release notes: https://go.dev/doc/devel/release#go1.20.1

### CODE REVIEW

**Review by squeed — APPROVED** [review]

**Review by aanm — APPROVED** [review]
From all files in here it looks that it's doable to upgrade all of these dependencies with renovate automatically. :tada:

**Review by nebril — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Review by aditighag — APPROVED** [review]
🚢

**Review by chancez — APPROVED** [review]

**Comment by tklauser** [comment]
Runtime tests failed because the test suite there is still built using the Go toolchain provided in the runtime VM image 😭 I'll take care of updating the VM images to Go 1.20.1.

**Review by sayboras — APPROVED** [review]
:ship:

**Pull request merged**
