### PR TITLE
examples: remove obsolete Mesos example

### PR DESCRIPTION
**Pull request by tklauser**
Noticed while reviewing #15370

The respective guide was removed from documentation in commit
3d0e805c2dfa ("doc: Remove Mesos/Marathon guide"), thus the link in the
README is broken already. The example hasn't been tested for the last
few releases (v1.9: #13627, v1.8: #11903), so remove it.

### CODE REVIEW

**Comment by qmonnet** [comment]
I see a few references to Mesos elsewhere in the repository (`git grep -i mesos`), should we make sure that we either deprecate Mesos support completely, or keep a minimal updated documentation?

**Comment by tklauser** [comment]
> I see a few references to Mesos elsewhere in the repository (`git grep -i mesos`), should we make sure that we either deprecate Mesos support completely, or keep a minimal updated documentation?

That's a good point. Most of these references seem to come from extraction of Mesos labels in the CNI. Not sure whether we want to still retain this?

Other than that I see nothing Mesos-specific in our code base apart from some other occurrences, e.g. in the issue template and the `README` we could probably already drop as well. A [quick search](https://github.com/cilium/cilium/issues?q=is%3Aissue+in%3Abody+mesos+NOT+kubernetes+NOT+k8s) through our recent issues shows nobody reporting Mesos as an orchestrator (but maybe I didn't search hard enough, having `Mesos` mentioned as part of the issue template makes it a bit hard to search exactly).

@tgraf what do you think?

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
> That's a good point. Most of these references seem to come from extraction of Mesos labels in the CNI. Not sure whether we want to still retain this?

It's fine to keep them. The logic of the labels being provided via the CNI ADD is good to have in general. It will simply further integrations and is not Mesos specific in any way. If we need it, we can refactor it to a more generic name.

We can remove all mentions of Mesos in the documentation, templates, ... though

**Comment by tklauser** [comment]
> We can remove all mentions of Mesos in the documentation, templates, ... though

Pushed an additional commit removing mentions in the docs, except for the parts describing the Mesos labels extracted by the CNI.

**Review by qmonnet — APPROVED** [review]

**Comment by qmonnet** [comment]
I can't find where the request review for ci-structure originates from, and I don't think it is necessary. Marking as ready to merge.

**Pull request merged**
