### PR TITLE
Update Go to 1.13.10

### PR DESCRIPTION
**Pull request by tklauser**

### CODE REVIEW

**Comment by tklauser** [comment]
Build of the `cilium-runtime` image is currently blocked by the Go 1.13.10 not being published yet due to docker-library/golang#322

**Comment by tklauser** [comment]
The `docker.io/library/golang:1.13.10` is now available and `cilium-runtime` image was successfully rebuilt.

**Comment by tklauser** [comment]
never-tell-me-the-odds

**Comment by tklauser** [comment]
test-with-kernel

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
test-missed-k8s

**Comment by tklauser** [comment]
test-upstream-k8s

**Comment by tklauser** [comment]
test-with-kernel

**Comment by tklauser** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-kernel

**Comment by aanm** [comment]
test-with-kernel

**Comment by tklauser** [comment]
Looks like a backport of #10932 is needed for this to pass `test-with-kernel`.

**Comment by tklauser** [comment]
Need to wait for #10966 to land and will rebase afterwards.

**Comment by aanm** [comment]
restart-kernel

**Comment by aanm** [comment]
ginkgo-kernel

**Comment by aanm** [comment]
restart-with-kernel

**Comment by aanm** [comment]
test-with-kernel

**Pull request merged**
