### PR TITLE
Removes Unused TransformToNode() Func

### LINKED ISSUE #25680: Remove Unused ConvertToNode() Func
## Cilium Feature Proposal
        
After https://github.com/cilium/cilium/pull/25604 merges, `ConvertToNode()` in the k8s pkg is only used in test code, so it should be removed.

**Is your feature request related to a problem?**

ConvertToNode() is unused code.

**Describe the feature you'd like**

Remove ConvertToNode() from test code.

### PR DESCRIPTION
**Pull request by danehans**
Updates tests to no longer use `TransformToNode()`.

Fixes: #25680

### CODE REVIEW

**Review by joamaki — APPROVED** [review]

**Comment by danehans** [comment]
@joamaki now that 1.14 is cut, do you have any reviewer suggestions to move this PR forward?

**Comment by danehans** [comment]
@joestringer PTAL when you have a moment or can you suggest any other maintainers that can review?

**Comment by joestringer** [comment]
@danehans it looks like all codeowners are satisfied, the issue is that there are required tests that have not passed. Might be worth rebasing + re-running CI? For reference, [here](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#howto-contribute) are the requirements to merge PRs.

**Comment by joestringer** [comment]
Looking at one of the [image build failures](https://github.com/cilium/cilium/actions/runs/5857442418/job/15879308377?pr=26743), Quay.io may have had an outage. They don't report it on their [status page](https://status.quay.io) but I'm suspicious given the range of weird failures.

I don't immediately see why changing these libraries would require changes to the base images. I'll try closing+reopening the PR to see if that unblocks these CI failures, otherwise it might be worth doing another rebase+repush (maybe do a `git commit --amend` on the top commit to make sure it refreshes the sha so that github doesn't cache the same test results).

**Comment by danehans** [comment]
@joestringer thanks for your help. It looks like https://github.com/cilium/cilium/pull/26743#issuecomment-1677569443 is no longer an issue. PTAL when you have a moment.

**Pull request merged**
