### PR TITLE
Add support for BPF maps without cache to GetModel

### PR DESCRIPTION
**Pull request by AwesomePatrol**
This function is called by `cilium-dbg map get <map-name>`. Some BPF maps (that are not managed by Go-side of cilium-agent) don't have their caches populated, so it was difficult to get this information with `cilium-dbg` CLI (you could still do that with `bpftool`)

```release-note
"cilium-dbg map get ..." can now be called on BPF maps without cache
```

### CODE REVIEW

**Comment by michi-covalent** [comment]
not sure if lorenz is available to review this right now, could somebody from @cilium/loader take a look?

**Review by lmb — APPROVED** [review]
LGTM, sorry for the long wait.

**Comment by joestringer** [comment]
Thanks for this. Heads up for two things:
1. You can always use `cilium bpf ...` to dump specific maps directly from the kernel without calling through userspace
2. I bumped the release note level up to `release-note/minor` and updated the changelog description, since this seems like it could be a helpful tool for users to know about.

**Pull request merged**
