### PR TITLE
ci: update cilium-cli to v0.12.1 for master, v1.11 and v1.12 workflows

### PR DESCRIPTION
**Pull request by tklauser**
Release notes: https://github.com/cilium/cilium-cli/releases/tag/v0.12.1

### CODE REVIEW

**Comment by tklauser** [comment]
CI passed for affected workflows:

- L4LB: https://github.com/cilium/cilium/actions/runs/2816766654
- AWS-CNI: https://github.com/cilium/cilium/actions/runs/2816768328
- EKS: https://github.com/cilium/cilium/actions/runs/2816766673
- External workloads: https://github.com/cilium/cilium/actions/runs/2816766639

Removing test commit and marking as ready for review.

**Review by sayboras — APPROVED** [review]
:ship: :rocket:

**Review by nbusseneau — APPROVED** [review]

**Pull request merged**
