### PR TITLE
test: fix gofmt

### PR DESCRIPTION
**Pull request by ianvernon**
Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7731)

### CODE REVIEW

**Review by jrajahalme — APPROVED** [review]
Sorry for the churn!

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Fixes: a1f1d0ff5f2f ("CI: Enforce sensible timeouts.") (https://github.com/cilium/cilium/pull/7720 which is marked as pending a 1.5 backport and needing earlier backports)

**Comment by ianvernon** [comment]
@joestringer I ran `go fmt` on the files in the v1.5 backport branch as part of the backporting process so 1.5 is good here

**Comment by ianvernon** [comment]
test-me-please

**Comment by brb** [comment]
Ouch, sorry, I think I have fixed the same issue ;-/ https://github.com/cilium/cilium/pull/7738

**Comment by ianvernon** [comment]
Superseded by #7738

**Pull request closed without merging**
