### PR TITLE
Adds a locked function to do ipcache delete on metadata match

### PR DESCRIPTION
**Pull request by Weil0ng**
Fixes potential racing condition introduced in PR #17161.

Suggested-by: Joe Stringer <joe@cilium.io>
Signed-off-by: Weilong Cui <cuiwl@google.com>

### CODE REVIEW

**Review by joestringer — APPROVED** [review]
Thanks, the fix looks good to me.

I see that you have referenced my handle in the git commit message. I appreciate the acknowledgement there. Unfortunately, this also means that github will notify me any time that this commit shows up in other PRs on github, including backports. In future, you may want to consider instead adding a tag next to the signed-off-by with just the name rather than the github handle, something like:

`Reported-by: Joe Stringer <joe@cilium.io>` or
`Suggested-by: Joe Stringer <joe@cilium.io>`

**Comment by Weil0ng** [comment]
> In future, you may want to consider instead adding a tag next to the signed-off-by with just the name rather than the github handle, something like:
> 
> `Reported-by: Joe Stringer <joe@cilium.io>` or `Suggested-by: Joe Stringer <joe@cilium.io>`

Thanks for letting me know, changed commit msg, will default to this format when acknowledging folks in the future :)

**Review by aanm — APPROVED** [review]

**Review by errordeveloper — APPROVED** [review]

**Pull request merged**
