### PR TITLE
compile: consolidate OutputType check to single switch

### PR DESCRIPTION
**Pull request by lx1036**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

### CODE REVIEW

**Comment by lx1036** [comment]
Signed-off-by: Xiang Liu <lx1036@126.com>

**Comment by ti-mo** [comment]
@lx1036 The `Signed-off-by` clause should be part of the commit message, not as a GH comment.

Also, could you please rephrase the commit title to something more descriptive? e.g.: `compile: consolidate OutputType check to single switch`.

**Comment by lx1036** [comment]
@ti-mo  thanks for your help. I have fixed it.

**Review by ti-mo — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Pull request merged**
