### PR TITLE
v1.3: backport 19-04-15

### PR DESCRIPTION
**Pull request by brb**
v1.3 backports 2019-04-15

**INCLUDED**

 * #7713 -- Doc: Update jinja dependency for documentation building (@tgraf)
 * #7717 -- envoy: Update to enable path normalization (@jrajahalme)
 * #7712 -- Istio update to use proxy image with path normalization (@jrajahalme): There were a couple of trivial merge conflicts. @jrajahalme Could you double check whether I have fixed them properly?
 * #7704 -- Fix backporting scripts for https users (@nebril)

**NOT INCLUDED**
 
* #7720 -- CI: Enforce sensible timeouts. (@jrajahalme): There was a merge conflict. @jrajahalme Is it fine to exclude this PR or is it needed to make the 1.3 CI stable?

Once this PR is merged, you can update the PR labels via:
```
$ for pr in 7713 7717 7712 7704; do contrib/backporting/set-labels.py $pr done 1.3; done
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7730)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-docs-please

**Comment by brb** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
Had to fix up the backport because the new `WaitForCRDCount` took in a `time.Duration` as a parameter, but in `v1.3` the `TimeoutConfig` expected an `int64`.

**Comment by ianvernon** [comment]
All test runs ran the upgrade test first, which fails for the v1.3 branch. 

Want to get one upgrade run that is clean through first to validate that the upgrade test passes. Will not re-run the K8s tests, since all other tests passed.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Update test passed in Ginkgo tests here: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11622/

**Review by ianvernon — APPROVED** [review]

**Pull request merged**
