### PR TITLE
v1.14 Backports 2024-08-02

### PR DESCRIPTION
**Pull request by nbusseneau**
* [x] #33769 (@pchaigno)
 * [x] #33666 (@bimmlerd) :warning: resolved conflicts
 * [ ] #33908 (@giorio94) :warning: resolved conflicts
 * [ ] #34004 (@tommyp1ckles) :warning: resolved conflicts
 * [x] #34044 (@Huweicai) :warning: resolved conflicts

PRs skipped due to conflicts:

 * #34091 (@giorio94)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33769 33666 33908 34004 34044
```

### CODE REVIEW

**Comment by nbusseneau** [comment]
/test-backport-1.14

**Review by bimmlerd — APPROVED** [review]

**Comment by julianwiedmann** [comment]
I reviewed https://github.com/cilium/cilium/pull/33769.

**Review by julianwiedmann — APPROVED** [review]
I reviewed https://github.com/cilium/cilium/pull/33769.

**Review by julianwiedmann — APPROVED** [review]

**Comment by gandro** [comment]
Remaining reviewers are out, but changes are not complicated and CI is green. Merging.

**Pull request merged**
