### PR TITLE
images: golang version to 1.19.6

### PR DESCRIPTION
**Pull request by aanm**
Since Golang 1.20.0 had a regression we have decided to release 1.13.0 with 1.19.x instead. However the change made in
626ce4d8c4a8ca84a2ff1287a6780235af4877e4 was merged but not reverted. This commit sets the Golang version to the last stable release, which also includes some security bug fixes.

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Approving in advance of the bot generating the new cilium-runtime images and bumping the dependency in the main image. Core change LGTM.

**Comment by aanm** [comment]
/test-backport-1.13

**Review by joestringer — APPROVED** [review]

**Comment by aanm** [comment]
/test-1.19-4.9

**Review by michi-covalent — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Pull request merged**
