### PR TITLE
Use default interface when encrypt-interface is not set

### PR DESCRIPTION
**Pull request by lbernail**
When IPSEC is enabled but Tunnel is disabled, `encrypt-interface` is required

However in some clusters the main interface name can vary according to instances (frequent on AWS with Ubuntu where c5 will use ens5 and i3 ens3 for instance). This PR uses the interface associated with the default IPV4 route as the encrypt-interface when the flag is not set.

Doing it there seemed to be the simplest solution but of course I can modify the PR if there is a better one

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8606)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Review by jrfastab — APPROVED** [review]
LGTM thanks for doing this.

**Comment by jrfastab** [comment]
@lbernail also we should use the helper, NodeDeviceNameWithDefaultRoute() in ./pkg/datapath/linuxx/node.go

**Comment by jrfastab** [comment]
@lbernail I needed to pull this into my PR to add encrypt-node support to our CI. Would you like me to push it through that PR, keeping your author attribution of course? Either way is fine might save you some cycles though.

**Comment by lbernail** [comment]
@jrfastab This is indeed much cleaner (sorry I did not about the helper)

Of course feel free to cherry-pick this change where you see fit

**Comment by aanm** [comment]
@lbernail can you rebase against master? it seems there's a conflicting file

**Comment by jrfastab** [comment]
superseded by https://github.com/cilium/cilium/pull/8711

**Pull request closed without merging**
