### PR TITLE
Istio: Update to release 1.5.9

### PR DESCRIPTION
**Pull request by jrajahalme**
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

```release-note
Istio integration has been updated to Istio release 1.5.9.
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Review by soumynathan — COMMENTED** [review]
Looks good to me.

**Comment by joestringer** [comment]
All of runtime failed, seems likely some issue with provisioning the runtime VM: https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/1534/execution/node/97/log/?consoleFull

**Comment by joestringer** [comment]
retest-runtime

**Comment by jrajahalme** [comment]
All failing tests are known unrelated flakes.

**Pull request merged**
