### PR TITLE
Ingress/Gateway API: merge Envoy listeners for HTTP(S) and TLS passthrough

### LINKED ISSUE #31242: Adding `ingress.cilium.io/tls-passthrough` to any one ingress breaks all ingresses
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. When using cilium ingress, adding `ingress.cilium.io/tls-passthrough` to any one ingress breaks it and all other ingresses in cluster. All ingresses fail with `curl: (56) Recv failure: Connection was reset`
2. The issue occurs, no matter if `ingressController.loadbalancerMode` is in `shared` or `dedicated` mode

### Cilium Version

v1.15.1

### Kernel Version

6.1.80-talos

### Kubernetes Version

v1.29.2

### Regression

This is a new addition in 1.15, the functionality was not present in previous versions

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mhofstetter**
Currently, the translation from Ingress controller & Gateway API resources into the corresponding `CiliumEnvoyConfig` creates two Envoy listeners for TLS passthrough (Ingress annotation or GW-API `TLSRoute`) and HTTP(S) related functionality.

- TLS Passthrough implemented with Envoy [TCPProxy](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/tcp_proxy_filter) network filter
- HTTP(S) implemented with Envoy [HCM](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/http_conn_man#config-http-conn-man) network filter

This works fine for Gateway API and Dedicated Ingresses where the two use-cases are never combined into the same `CiliumEnvoyConfig` - but leads to problems with Shared Ingresses.

Problem 1: Listener name clash

The two listeners have the same name listener - hence only one of them ends up in the configuration (in most of the cases the TLS Passthrough one which appears later in the configuration).

Problem 2: TPROXY redirection to different listeners with same frontend service port

After solving the name clash, there's still an issue with TLS Passthrough and HTTPS using the same "frontend" port 443 (or the corresponding NodePort) on the Ingress Service that is handled by different Envoy listeners. The current implementation (based on TPROXY) is not able to conditionally (HTTPS or TLS Passthrough) forward traffic to one of these two Listeners.

Therefore, this PR merges the two functionalities within the same Envoy listener by using different filterchains and filterchain-matches based on the servernames (SNI).

Fixes: https://github.com/cilium/cilium/issues/31242
Related to: https://github.com/cilium/cilium/pull/30840

### CODE REVIEW

**Review by jrajahalme — APPROVED** [review]
Read through; LGTM

**Review by youngnick — APPROVED** [review]

**Comment by mhofstetter** [comment]
rebased to `main` to resolve conflicts in cmd-ref-docs

**Comment by squeed** [comment]
Do we need to worry about removing existing fields? Were these fields present in a released version?

**Comment by mhofstetter** [comment]
> Do we need to worry about removing existing fields? Were these fields present in a released version?

@squeed No, these Helm values (and annotations) were added with the PR https://github.com/cilium/cilium/pull/30840 which lands in v1.16. Therefore they weren't released except for the pre-releases (https://github.com/cilium/cilium/releases/tag/v1.16.0-pre.0)

**Comment by mhofstetter** [comment]
Improvements

* naming of annotation & helm values after merging them (including `listener` in name) (annotation: `ingress.cilium.io/host-listener-port` / helm: `ingressController.hostNetwork.sharedListenerPort`)
* explicit sharedListenerPort of `80` (in addition to implicit one)

**Review by squeed — APPROVED** [review]

**Comment by mhofstetter** [comment]
rebased to `main` to fix issues with build commit check (introduced via changes in clangd: https://github.com/cilium/cilium/pull/31754)

```
contrib/scripts/builder.sh make build -j 4: 1: contrib/scripts/builder.sh: not found
```

:crossed_fingers:

**Pull request merged**
