### PR TITLE
examples/kubernetes: set Cilium ConfigMap on top

### PR DESCRIPTION
**Pull request by aanm**
This allows users to easily change any necessary configurations suited
for their clusters.

Follow up of https://github.com/cilium/cilium/pull/6494

Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6540)

### CODE REVIEW

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
@aanm can you elaborate why this needs backporting?

**Comment by aanm** [comment]
@ianvernon #6494 was also backported

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by tgraf** [comment]
@aanm This is painful to backport to 1.3. Any particular reason for the backport?

**Comment by aanm** [comment]
@tgraf #6494 is marked backport-done/1.3, wasn't the case?

**Comment by tgraf** [comment]
@aanm Seems only a partial backport has happened. What is the motivation for the backport of this PR?

**Comment by aanm** [comment]
@tgraf only because it was a follow up of #6464, if that would have been backported then this one would need to.

**Comment by ianvernon** [comment]
@aanm @tgraf so should this be backported to v1.3 given that #6494 was only partially backported?

**Comment by ianvernon** [comment]
I will leave the 'needs-backport/1.3' label on this PR, but will not backport it, as this is primarily a cosmetic change, but does not cherry-pick cleanly onto v1.3 .

**Comment by aanm** [comment]
> @aanm @tgraf so should this be backported to v1.3 given that #6494 was only partially backported?

No

**Pull request merged**
