### PR TITLE
bpf: Honor DROP_ALL also in ingress to a container.

### PR DESCRIPTION
**Pull request by jrajahalme**
Even if DROP_ALL is defined, the bpf program can be compiled so that
the actual ingress policy check returns OK (e.g., POLICY_INGRESS not
defined). Check for DROP_ALL in higher level code that is not
conditional to any other compile time definitions.

Fixes: https://github.com/cilium/cilium/issues/3731
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/3733)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Not sure if it is safe to remove DROP_ALL handling from `bpf/lib/policy.h`, but that seems likely, unless there are callers elsewhere than `bpf/bpf_lxc.c`.

**Comment by tgraf** [comment]
To be on the 100% safe size for the future, let's add:
```
diff --git a/bpf/lib/policy.h b/bpf/lib/policy.h
index bf07ed8f3..dc672f748 100644
--- a/bpf/lib/policy.h
+++ b/bpf/lib/policy.h
@@ -174,7 +174,11 @@ policy_can_access_ingress(struct __sk_buff *skb, __u32 src_label,
                          __u16 dport, __u8 proto, size_t cidr_addr_size,
                          void *cidr_addr)
 {
+#ifdef DROP_ALL
+       return DROP_POLICY;
+#else
        return TC_ACT_OK;
+#endif
 }

 #endif /* POLICY_INGRESS */
@@ -257,14 +261,22 @@ static inline int
 policy_can_egress6(struct __sk_buff *skb, struct ipv6_ct_tuple *tuple,
                   __u16 default_identity, union v6addr *daddr)
 {
+#ifdef DROP_ALL
+       return DROP_POLICY;
+#else
        return TC_ACT_OK;
+#endif
 }
 static inline int
 policy_can_egress4(struct __sk_buff *skb, struct ipv4_ct_tuple *tuple,
                   __u16 default_identity, __be32 daddr)
 {
+#ifdef DROP_ALL
+       return DROP_POLICY;
+#else
        return TC_ACT_OK;
+#endif
 }
 #endif /* POLICY_EGRESS && LXC_ID */
```

**Comment by jrajahalme** [comment]
IMO we could be even more defensive and make all functions in bpf/lib/policy.h conditional on DROP_ALL. I'll add a commit here for that.

**Comment by jrajahalme** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
