### PR TITLE
policy: Suppress any policy map updates when updating redirects if keeping the current policy

### PR DESCRIPTION
**Pull request by jrajahalme**
Incremental policy update path
(AccumulateMapChanges/ConsumeMapChanges) is taking care of the policy
map updates when a full policy recalcualtion is not necessary. We
already depended on this to get the redirect entries plumbed down to
the bpf maps. Make this more explicit by suppressing policy MapState
updates while updating proxy redirects if a new policy was not
calculated. This allows ConsumeMapsChanges() to notice that the
redirect entry was not already in the desired MapState and pass it
along as a map change to be applied to the bpf maps.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Known flake (#12511) on netnext, no other failures.

**Review by christarazi — APPROVED** [review]

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Rebase to master & retest.

**Review by aanm — APPROVED** [review]

**Pull request merged**
