### PR TITLE
WIP: test v1.1 branch stability

### PR DESCRIPTION
**Pull request by ianvernon**
**Summary of changes**:

Fixes: #issue-number

```release-note
<!-- Enter the release note text here if needed -->
```

**How to test (optional)**:
e.g. Run `make tests`, `make runtime-tests` and/or some more specific way to
exercise the new behavior(s).
Note: [The runtime testsuite will modify the host it runs on.](http://cilium.readthedocs.io/en/latest/contributing/#testsuite)

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4838)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4915/

**Comment by ianvernon** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please (green)

**Comment by ianvernon** [comment]
test-me-please (fail)

**Comment by ianvernon** [comment]
test-me-please (green)

**Comment by ianvernon** [comment]
test-me-please (green)

**Comment by ianvernon** [comment]
test-me-please (failed, but because unable to pull microscope image)

**Comment by ianvernon** [comment]
tests failed, but because microscope pull went into `ImagePullBackoff`:

```
kube-system   microscope                         0/1       ImagePullBackOff   0          5m        <none>          k8s2
```

trying again to see if this was just a connectivity issue to DockerHub.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
I don't know what happened to the Cilium v1.1.0 microscope image? I tried pulling it locally and it failed:

```
$ docker pull docker.io/cilium/microscope:1.1.0
Error response from daemon: manifest for cilium/microscope:1.1.0 not found
```

**Comment by ianvernon** [comment]
It's not on DockerHub either: https://hub.docker.com/r/cilium/microscope/tags/

**Pull request closed without merging**
