### PR TITLE
v1.8 backports 2021-04-13

### PR DESCRIPTION
**Pull request by jibi**
* ~#15540 -- bpf: Extend datapath options for K8sVerifier test (@pchaigno)~
 * #15590 -- ctmap: do not call InitMapInfo() in init() (@kkourt)
 * #15622 -- Fix ethtool issues (@tklauser)
 * #15260 -- mtu: Switch to v/netlink for querying netdevs (@brb)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 15590 15622 15260; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by jibi** [comment]
(rebuilding runtime and builder images)

**Comment by tklauser** [comment]
>     * #14329 -- cilium, gops: remap to fixed port to avoid collision with nodeport range (@borkmann)

This is already being backported in #15634. Apologies, I forgot to mark the PR as `backport-pending/1.8`.

**Comment by jibi** [comment]
> > * #14329 -- cilium, gops: remap to fixed port to avoid collision with nodeport range (@borkmann)
> 
> This one is already being backported in #15634. Apologies, I forgot to mark the PR as `backport-pending/1.8`.

No worries :raised_hands:  I'll drop the PR then

**Comment by jibi** [comment]
Holding off until https://github.com/cilium/cilium/pull/15602 gets merged (as #15622 depends on https://github.com/cilium/cilium/pull/15357)

**Comment by kkourt** [comment]
Hi! #15590 does not seem to be on the commits... Was this dropped as well?

**Comment by jibi** [comment]
> Hi! #15590 does not seem to be on the commits... Was this dropped as well?

Yeah, I haven't backported anything yet (that's why this is still a draft).

I started by just backporting #14329 (as I had to rebuild the runtime and builder images), but then I dropped that as Tobias was already backporting it. (Then I moved to #15622 but that dependes on another backport which is not merged yet, so I put everything on hold)

**Pull request closed without merging**
