### PR TITLE
Run resolution test from all the log-gatherer pods

### LINKED ISSUE #14909: test: Validate Kubernetes DNS can resolve from both nodes
When we deploy Cilium in tests, one of our first validation steps is to check that Kubernetes' DNS can resolve domain names. That is one of our most complex early checks because it involves sending a request to a VIP and potentially cross-node communications. It is the reason why `Kubernetes DNS did not become ready in time` is such a frequent error message in test failures and flakes.

We currently only run this resolution from a single node (k8s1 via its log-gatherer pod): https://github.com/cilium/cilium/blob/fce7fe070c14d09adf79395106b056111ad86caa/test/helpers/kubectl.go#L1758-L1759
Depending on where the CoreDNS pod was scheduled, this test can involve a cross-node communication or not. That is, if the CoreDNS pod was schedule on k8s1, the request won't leave k8s1. In the other case (CoreDNS scheduled on k8s2), we will send packets across nodes, thereby testing the tunnel or direct routing in the process.

This lack of determinism can cause flakes and make debugging harder (e.g., https://github.com/cilium/cilium/issues/13774). We should instead test the DNS resolution from both nodes and fail if either resolution fails. That way we wouldn't depend on the location of the CoreDNS pod.

### PR DESCRIPTION
**Pull request by weirdwiz**
Fixes: #14909

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Comment by weirdwiz** [comment]
test-me-please

**Comment by weirdwiz** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-1.16-netnext

**Comment by weirdwiz** [comment]
Force pushed in order to rebase.

**Comment by weirdwiz** [comment]
> The failures in [k8s-1.16-kernel-netnext](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/271/testReport/junit/Suite-k8s-1/16/K8sServicesTest_Testing_test_script_Validating_test_script_correctness/) are very likely to be related. Retriggering to see if it's a flake introduced by the PR or if it breaks consistently.
> 
> test-1.16-netnext

Both k8s-1.16(netnext) and k8s-1.21 ran correctly on my local machine, I'm not sure why every DNS resolution failed in k8s-1.16.

@pchaigno Do you have a recommended approach to debug the CI issues?

**Comment by pchaigno** [comment]
test-1.16-netnext

**Review by nbusseneau — APPROVED** [review]

**Comment by pchaigno** [comment]
> Both k8s-1.16(netnext) and k8s-1.21 ran correctly on my local machine, I'm not sure why every DNS resolution failed in k8s-1.16.

The CI job is still failing with this. How did you test locally?

**Comment by weirdwiz** [comment]
> > Both k8s-1.16(netnext) and k8s-1.21 ran correctly on my local machine, I'm not sure why every DNS resolution failed in k8s-1.16.
> 
> The CI job is still failing with this. How did you test locally?

I'm running `NETNEXT=1 K8S_VERSION=1.16 ginkgo --focus="K8s"`. To test the changes locally.

**Comment by pchaigno** [comment]
Ok. Try `NETNEXT=1 K8S_VERSION=1.16 KUBEPROXY=0 K8S_NODES=3 NO_CILIUM_ON_NODE="k8s3" ginkgo --focus="K8s"`; it's closer to what our CI job runs. If your laptop is struggling with 3 VMs, might be worth trying `NETNEXT=1 K8S_VERSION=1.16 KUBEPROXY=0 ginkgo --focus="K8s"` as `KUBEPROXY=0` (i.e., don't install kube-proxy) is likely to have the most impact here. Don't hesitate to reach out on Slack if you have any question.

**Comment by pchaigno** [comment]
test-1.16-netnext

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
It looks like k8s-1.16-kernel-netnext failed due to a timeout. Resolving DNS twice seems to have increasing testing time considerably. Maybe we can find a way to check the two DNS resolutions in parallel?

**Comment by weirdwiz** [comment]
Just to confirm, would that be running a goroutine for every iteration?

**Comment by pchaigno** [comment]
Switching to draft mode so that it doesn't show up in everyone's review queue while the required changes are implemented.

**Pull request closed without merging**
