### PR TITLE
v1.13 Backports 2023-03-22

### PR DESCRIPTION
**Pull request by NikAleksandrov**
* [x] #22848 (@christarazi)
 * [x] #24205 (@borkmann)
 * [x] #24174 (@aojea)
 * [x] #24171 (@romanspb80)
 * [x] #24255 (@tklauser)
 * [x] #24144 (@joestringer)
 * [x] #24140 (@jibi)
 * [x] #24164 (@jspaleta)
 * [x] #24271 (@borkmann)
 * [x] #24275 (@aanm)
 * [x] #24244 (@pchaigno)
 * [x] #24134 (@nebril)
 * [x] #24163 (@giorio94)
 * [x] #24304 (@dylandreimerink)
 * [x] #24223 (@brb)
 * [x] #24189 (@forgems)
 * [x] #24046 (@oblazek)
 * [x] #24373 (@christarazi)
 * [x] #24267 (@alexkats)
 * [x] #24407 (@PhilipSchmid)
 * [x] #24400 (@pchaigno)
 * [x] #24398 (@pchaigno)
 * [x] #23764 (@christarazi)
 * [x] #24413 (@hemanthmalla)
 * [x] #24460 (@NikAleksandrov)
 * [x] #24428 (@PhilipSchmid)
 * [x] #24477 (@gandro)
 * [x] #24435 (@lizrice)
 * [x] #23297 (@dylandreimerink)

PRs skipped due to conflicts:

 * #24296 (@brb)
 * #24350 (@chancez)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 22848 24205 24174 24171 24255 24144 24140 24164 24271 24275 24244 24134 24163 24304 24223 24189 24046 24373 24267 24407 24400 24398 23764 24413 24460 24428 24477 24435 23297; do contrib/backporting/set-labels.py $pr done 1.13; done
```
or with
```
make add-labels BRANCH=v1.13 ISSUES=22848,24205,24174,24171,24255,24144,24140,24164,24271,24275,24244,24134,24163,24304,24223,24189,24046,24373,24267,24407,24400,24398,23764,24413,24460,24428,24477,24435,23297
```

### CODE REVIEW

**Comment by aojea** [comment]
what about https://github.com/cilium/cilium/pull/24202 @NikAleksandrov , was it already backported?

**Review by PhilipSchmid — APPROVED** [review]
LGTM. Thanks!

**Comment by pchaigno** [comment]
> Few notes:

I'd encourage putting that information in the OP otherwise many people will miss it. GitHub may even end up hiding your comment.

**Review by pchaigno — APPROVED** [review]
My PRs look good. Thanks!

**Comment by oblazek** [comment]
my PR looks good as well :)

**Comment by NikAleksandrov** [comment]
> > Few notes:
> 
> Paul suggested to put these in the PR description, which I think is the _minimum_ for informing the original authors - we rely on this to identify when there are changes we need to take a closer look at. I would suggest taking this one step further and also including this information in the commit messages. Then if it turns out there is a bug related to this issue and we bisect to that commit, we will have the context that the backport made some specific changes vs. the original proposed PR.
> 
> Note that this is standard process that is expected from backporters per step 3 in the [backporting guide](https://docs.cilium.io/en/stable/contributing/release/backports/#creating-the-backports-branch).

Alright, point taken. I'll update the descriptions.

**Review by hemanthmalla — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
My PR looks good. Thanks!

**Review by jibi — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Comment by NikAleksandrov** [comment]
Note that commit:
```
commit 49b6bb2e6f24
Author: Dylan Reimerink <dylan.reimerink@isovalent.com>
Date:   Tue Jan 24 17:13:12 2023 +0100

    lbipam: Fixed mismatched label test and associated bug
    
    [ upstream commit db1a06114184b9e569787bea5dcf4716de4bb41c ]
    
    This unit test was incorrect. It assumed that services with requested
    IPs whom didn't match the pool selector would be ignored. But this
    behavior was changed at some point during development so we instead
    set a status condition on the service. However the test wasn't updated.
    
    The test still returned PASS because it is time based and terminated
    after 100ms, but 7999/8000 times LB-IPAM takes longer than 100ms to
    send the update. This flake occurs only when we send the update in
    <100ms after start.
    
    The test has been updated to reflect the correct behavior, which
    surfaced a bug that was fixed as well.
    
    Fixes: #23272
    
    Signed-off-by: Dylan Reimerink <dylan.reimerink@isovalent.com>
    Signed-off-by: Nikolay Aleksandrov <nikolay@isovalent.com>
```
was skipped because it was breaking CI after a discussion with Dylan, it is not needed.
The first commit of https://github.com/cilium/cilium/pull/23297 is still present.

**Review by borkmann — APPROVED** [review]

**Review by lizrice — APPROVED** [review]
Mine looks fine, thank you!

**Comment by NikAleksandrov** [comment]
/test-backport-1.13

**Comment by NikAleksandrov** [comment]
hitting the kind.sh CI issue mentioned in this PR: https://github.com/cilium/cilium/pull/24611

**Comment by NikAleksandrov** [comment]
/test-backport-1.13

**Comment by NikAleksandrov** [comment]
/test-ci-datapath-1.13

**Comment by NikAleksandrov** [comment]
/test-backport-1.13

**Comment by jibi** [comment]
rebased on top of v1.13

**Comment by jibi** [comment]
/test-backport-1.13

**Review by aanm — APPROVED** [review]

**Review by tommyp1ckles — APPROVED** [review]

**Review by squeed — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by jibi** [comment]
`test-1.18-4.9` is failing due to a known flake, everything else is green, reviews are in

**Pull request merged**
