### PR TITLE
v1.16 Backports 2024-07-22

### PR DESCRIPTION
**Pull request by joamaki**
* [x] #33488 (@rastislavs)
 * [ ] #33459 (@aditighag) :warning: resolved conflicts (minor conflict due to commit d26009cfea811 in main changing SocketLBTracing to true, but missing from v1.16, kept the original value)
 * [ ] #33661 (@chancez)
 * [x] #33824 (@pippolo84)
 * [ ] #33823 (@tommyp1ckles)
 * [ ] #33854 (@tamilmani1989)
 * [x] #33819 (@giorio94)
 * [x] #33888 (@giorio94) :warning: resolved conflicts (minor conflict in upgrade.rst due to "Cilium CLI" section in v1.16)
 * [ ] #33887 (@gandro)
 * [x] #33879 (@sayboras)
 * [x] #33907 (@julianwiedmann)
 * [x] #33867 (@pippolo84)
 * [ ] #33853 (@beyildirim)
 * [ ] #33903 (@chaunceyjiang)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33488 33459 33661 33824 33823 33854 33819 33888 33887 33879 33907 33867 33853 33903
```

### CODE REVIEW

**Comment by joamaki** [comment]
/test-backport-1.16

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commit

**Review by julianwiedmann — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
My commits look good, thanks!

**Review by rastislavs — APPROVED** [review]

**Review by pippolo84 — APPROVED** [review]
My PRs look good, thanks!

**Review by chancez — APPROVED** [review]

**Review by squeed — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Pull request merged**
