### PR TITLE
v1.12: Update Go to 1.18.6

### PR DESCRIPTION
**Pull request by tklauser**
This version fixes a security issue in the net/http package. See the release notes [1] for more details

[1] https://go.dev/doc/devel/release#go1.18.6

### CODE REVIEW

**Comment by tklauser** [comment]
/test-backport-1.12

**Review by rolinh — APPROVED** [review]

**Comment by tklauser** [comment]
/test-backport-1.12

**Review by sayboras — APPROVED** [review]
LGTM ✅

**Comment by tklauser** [comment]
/test-backport-1.12

**Review by nbusseneau — APPROVED** [review]

**Comment by tklauser** [comment]
All 4.9 tests failed on #20288 which was fixed on `master` by bumping the Vagrant VM image. Not sure whether the same should be done for `v1.12`, but in any case the failure is not related to this PR, so marking as ready to merge given reviewers approved.

**Pull request merged**
