### PR TITLE
Ginkgo: Added md5sum check on RuntimeChaos

### LINKED ISSUE #2433: Ginkgo CI: check whether output in "Endpoint recovery on restart" fully matches with md5sum
The bash script tests in `tests/96-restore-endpoints.sh` compares the md5sum of the output of `cilium endpoint list` before & after restart to confirm that all restoration of the endpoints was successful. In the Ginkgo tests though, the following comparison is done to check whether the restore output is equivalent:
```
...
ips := vm.Exec(`
		curl -s --unix-socket /var/run/cilium/cilium.sock \
		http://localhost/v1beta/healthz/ | jq ".ipam.ipv4|length"`)
Expect(originalIps.Output().String()).To(Equal(ips.Output().String()))
```

This does not check whether the contents of `cilium endpoint list` are the same before / after, only whether the number of IPv4 IPs allocated is the same. The bash script implementation is more comprehensive. Use something like https://golang.org/pkg/crypto/md5/ to get the checksum of the output of `cilium endpoint list` before / after restore in `test/runtime/chaos.go`.

### PR DESCRIPTION
**Pull request by eloycoto**
Added md5Sum on endpoint list on RuntimeChaos.

Fixed #2433

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

### CODE REVIEW

**Review by aanm — COMMENTED** [review]
Is it worth it to print the `cilium endpoint list` output in case they differ from each other?

**Comment by tgraf** [comment]
> Is it worth it to print the cilium endpoint list output in case they differ from each other?

Yes, this will be a requirement to debug any failure of this test.

**Comment by eloycoto** [comment]
@aanm all commands executed and the output are saved in the log file per test, so you can debug without problem ;-)

**Comment by tgraf** [comment]
> @aanm all commands executed and the output are saved in the log file per test, so you can debug without problem ;-)

Can you give an example on how this looks like exactly? The test output should give a clear indication on why something fails without requiring to hunt logfiles.

**Comment by eloycoto** [comment]
@aanm @tgraf the last change should be ok.

**Review by tgraf — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]
LGTM. Ran the test locally, and it succeeded. The build failure was due to misconfiguration of one of the Jenkins agents.

**Pull request merged**
