### PR TITLE
loader: Fix missing dot in assembly output files

### PR DESCRIPTION
**Pull request by pchaigno**

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by pchaigno** [comment]
retest-runtime

**Comment by pchaigno** [comment]
retest-4.19

**Comment by pchaigno** [comment]
retest-runtime

**Comment by pchaigno** [comment]
retest-4.19

**Comment by pchaigno** [comment]
retest-gke

**Pull request merged**
