### PR TITLE
endpoint：fix the comments about Delete

### PR DESCRIPTION
**Pull request by pengbinbin1**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #issue-number

```release-note
The endpoint's IP is not released in the function **Delete**  ,it is released in the function  **EndpointDeleted** . This comments will confused the code reader
```

### CODE REVIEW

**Comment by tommyp1ckles** [comment]
Thanks for the contribution @pengbinbin1 , could also add to the commit message why this is no longer needed?

**Comment by pengbinbin1** [comment]
> Thanks for the contribution @pengbinbin1 , could also add to the commit message why this is no longer needed?


> The endpoint's IP is not released in the function **Delete**  ,it is released in the function  **EndpointDeleted** . This comments will confused the code reader

**Review by joestringer — APPROVED** [review]

**Comment by pengbinbin1** [comment]
I just removed one line about the comments, why the kubernetes e2e test is failed?

**Comment by joestringer** [comment]
I've filed https://github.com/cilium/cilium/issues/25271 for the kubernetes-e2e failure so we can gather further information. It looks like a flaky issue since, as you say, this PR is only changing code comments and therefore shouldn't have any impact on production code stability.

**Comment by joestringer** [comment]
I've filed https://github.com/cilium/cilium/issues/25272 to follow up on the Travis failure.

**Comment by joestringer** [comment]
Changes look good to me, thanks for the contribution! Merging.

**Comment by qmonnet** [comment]
Note: This Pull Request was merged into the `master` branch, but we switched to `main` as the default branch for Cilium a few days earlier. It's absent from the `main` branch, I'm looking at the best way to add it there.

**Pull request merged**
