### PR TITLE
hubble-relay: add support for LOCKDEBUG

### PR DESCRIPTION
**Pull request by rolinh**

### CODE REVIEW

**Review by tklauser — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Comment by sayboras** [comment]
hit #https://github.com/cilium/cilium/issues/12279, I am capturing logs for futher analaysis :)

**Comment by Rolinh** [comment]
@gandro @tklauser I updated the PR to also add support for the race detector.

**Comment by tklauser** [comment]
> @gandro @tklauser I updated the PR to also add support for the race detector.

Still LGTM; thanks.

**Review by gandro — APPROVED** [review]

**Comment by Rolinh** [comment]
The container can't run when built with `RACE=1`:
```
$ docker run --rm cilium/hubble-relay:latest help
standard_init_linux.go:211: exec user process caused "no such file or directory"
```
This is also the case with `NOSTRIP=1`. It's not yet clear if we can get this to work with `scratch`.

**Comment by Rolinh** [comment]
I found the cause: `CGO` is automatically enabled if `RACE` is enabled:  https://github.com/cilium/cilium/blob/1bd46240479805818370daadd342cf5c8aa271f6/Makefile.defs#L123
I think that as of Go 1.14.3, `CGO` is no longer required for the race detector. I'll test this and report back.

**Comment by pchaigno** [comment]
End-to-end tests are not required as they don't cover this change. Merging.

**Pull request merged**
