### PR TITLE
proxy: Remove oxyproxy, CILIUM_USE_ENVOY.

### PR DESCRIPTION
**Pull request by ianvernon**
Now that we always test with Envoy we can remove the oxy proxy and
simplify by removing the cilium-agent command line argument
"envoy-proxy" and the use of the environment variable
"CILIUM_USE_ENVOY".

```release-note
Remove oxy proxy and CILIUM_USE_ENVOY environment variable
```

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

Note: this duplicates PR #2625 , which isn't getting builds triggered due to Jenkins misbehaving, so I am pushing out a duplicate PR of the same branch on @jrajahalme 's behalf.

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Pull request closed without merging**
