### PR TITLE
Add retry to curl call in basic TLS policy test

### LINKED ISSUE #9869: CI: K8sPolicyTest Basic Test TLS policy
## CI failure
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.17-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
Cannot connect from "app2-776cf4f9c6-lrb2q" to 'https://swapi.co:443/api/planets/1/'
Expected command: kubectl exec -n k8spolicytestbasictestchecksallkindofkubernetespolicies app2-776cf4f9c6-lrb2q -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 -4 --max-time 15 -v --cacert /cacert.pem https://swapi.co:443/api/planets/1/ -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 35 
Stdout:
 	 time-> DNS: '0.125623(104.31.76.248)', Connect: '0.126019',Transfer '0.000000', total '0.128330'
Stderr:
 	 *   Trying 104.31.76.248...
	 * TCP_NODELAY set
	 * Connected to swapi.co (104.31.76.248) port 443 (#0)
	 * ALPN, offering http/1.1
	 * successfully set certificate verify locations:
	   CAfile: /cacert.pem
	   CApath: none
	 * TLSv1.2 (OUT), TLS handshake, Client hello (1):
	 } [512 bytes data]
	 * LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to swapi.co:443 
	 * Closing connection 0
	 command terminated with exit code 35
	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.17-gopath/src/github.com/cilium/cilium/test/k8sT/Policies.go:327
```

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/16358/testReport/junit/Suite-k8s-1/17/K8sPolicyTest_Basic_Test_TLS_policy/

https://github.com/cilium/cilium/pull/9866

### PR DESCRIPTION
**Pull request by nebril**
fixes #9869

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9957)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by aanm** [comment]
@nebril the flake should be hopefully fixed by https://github.com/cilium/cilium/pull/9892 once it's merged.

**Comment by nebril** [comment]
test-focus K8sPolicyTest*

**Comment by nebril** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Pull request merged**
