### PR TITLE
Test: Disable to-entities test

### PR DESCRIPTION
**Pull request by eloycoto**
Skip test on to-entities due errors.

Issue to track the new changes needed #5791

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5792)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by ianvernon** [comment]
@eloycoto this will fail the CI in K8s-1.12 until #5790 is merged

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
test-me-please

**Pull request merged**
