### PR TITLE
cilium: enable more ci tests for bw manager

### PR DESCRIPTION
**Pull request by borkmann**
See commit msgs.

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
retest-4.9

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
retest-4.9

**Review by brb — APPROVED** [review]
LGTM! However, the box update should happen in a separate PR (with a specific branch name). Otherwise, the VM image cache won't get updated.

**Comment by borkmann** [comment]
> LGTM! However, the box update should happen in a separate PR (with a specific branch name). Otherwise, the VM image cache won't get updated.

Ah fair enough, given CI is green I split this into two PRs and won't rerun.

**Pull request merged**
