### PR TITLE
Fix for data race in IP release features

### LINKED ISSUE #18204: CI: Travis fatal error: concurrent map iteration and map write in github.com/cilium/cilium/pkg/ipam
## CI failure

- First observed in https://github.com/cilium/cilium/pull/18153
- Travis log https://app.travis-ci.com/github/cilium/cilium/jobs/551583526
- Saved Travis output [log.txt](https://github.com/cilium/cilium/files/7687935/log.txt)

From the stack trace:
```
fatal error: concurrent map iteration and map write

goroutine 684 [running]:

runtime.throw({0x1b8bb62, 0x7fe8d6e875b8})

	/home/travis/.gimme/versions/go1.17.4.linux.amd64/src/runtime/panic.go:1198 +0x71 fp=0xc000e438a0 sp=0xc000e43870 pc=0x437631

runtime.mapiternext(0x0)

	/home/travis/.gimme/versions/go1.17.4.linux.amd64/src/runtime/map.go:858 +0x4eb fp=0xc000e43910 sp=0xc000e438a0 pc=0x41156b

runtime.mapiterinit(0xc0007c0000, 0xc0007c0190, 0x0)

	/home/travis/.gimme/versions/go1.17.4.linux.amd64/src/runtime/map.go:848 +0x236 fp=0xc000e43930 sp=0xc000e43910 pc=0x411036

github.com/cilium/cilium/pkg/ipam.(*Node).PopulateIPReleaseStatus(0xc000926100, 0xc0007ad880)

	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node.go:788 +0x86 fp=0xc000e439f8 sp=0xc000e43930 pc=0x1766f26

github.com/cilium/cilium/pkg/ipam.(*Node).syncToAPIServer(0xc000926100)

	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node.go:835 +0x16b fp=0xc000e43eb0 sp=0xc000e439f8 pc=0x176728b

github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update.func4({0xc000697fb0, 0xc000e43f34, 0x2da2d00})

	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:299 +0x26 fp=0xc000e43ec8 sp=0xc000e43eb0 pc=0x1769826
```

@hemanthmalla The top function `PopulateIPReleaseStatus` looks code introduced in https://github.com/cilium/cilium/pull/17939 (which also explains the timing). Do you mind taking a look? I recommend running the test with the race detector enabled.

### PR DESCRIPTION
**Pull request by hemanthmalla**
Fixes: #18204

Signed-off-by: Hemanth Malla <hemanth.malla@datadoghq.com>

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Looks good to me. Note that this fixes an issue in the Travis pipeline, not the Jenkins race pipeline.

Also marking for backport as the underlying code is scheduled for a v1.11 backport too.

**Comment by gandro** [comment]
Marking this as ready to merge, as this is impacting the stability of our Travis pipeline and all test failures are unrelated as per Chris' investigation above.

**Comment by nbusseneau** [comment]
@hemanthmalla Thanks for the PR! Merging.

**Pull request merged**
