### PR TITLE
ingress: Rename LB annotation to annotation prefixes

### PR DESCRIPTION
**Pull request by sayboras**
This is to avoid any potential confusion from user. Also, related docs are updated.

Related: https://github.com/cilium/cilium/pull/20860

Signed-off-by: Tam Mach <tam.mach@cilium.io>

### CODE REVIEW

**Review by gandro — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]
Looks good, thanks.
Given that the Helm value has changed name, does it deserve a mention in the Upgrade Notes (Documentation/operations/upgrade.rst)?

**Comment by sayboras** [comment]
> Looks good, thanks. Given that the Helm value has changed name, does it deserve a mention in the Upgrade Notes (Documentation/operations/upgrade.rst)?

Right now, the original annotation changes are only available in master and 1.13.0-rc0, and this is a newly added feature, I don't think we need to highlight it in upgrade docs.

**Review by christarazi — APPROVED** [review]

**Comment by sayboras** [comment]
Tests are all passed, most of the reviews are in. Marking this ready to merge.

In case of there is any other comments coming later, I will address in subsequent PRs.

**Pull request merged**
