### PR TITLE
Upgrade github.com/emicklei/go-restful to v2.16.0

### PR DESCRIPTION
**Pull request by michi-covalent**
To pick up the fix for https://github.com/emicklei/go-restful/issues/489

Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Comment by michi-covalent** [comment]
/test-backport-1.12

**Comment by michi-covalent** [comment]
[test-1.22-5.4](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-5.4/840/): a known flake: https://github.com/cilium/cilium/issues/23264

**Comment by michi-covalent** [comment]
/test-1.22-5.4

**Comment by michi-covalent** [comment]
test-1.18-4.9: vm provisioning failure: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.18-kernel-4.9/2387/

**Comment by michi-covalent** [comment]
/test-1.18-4.9

**Review by joestringer — APPROVED** [review]

**Pull request merged**
