### PR TITLE
test: Add HostPort conformance to upstream-k8s

### PR DESCRIPTION
**Pull request by joestringer**
Add HostPort Conformance test to the upstream-k8s testing so that we get
coverage for this test in CI.

Related: #14287

### CODE REVIEW

**Comment by joestringer** [comment]
test-upstream-k8s

**Review by christarazi — APPROVED** [review]

**Comment by joestringer** [comment]
Seems to be successfully failing :grin: 

```
18:32:18  • Failure [37.540 seconds]
18:32:18  [sig-network] HostPort
18:32:18  /home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/common/framework.go:23
18:32:18    validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance] [It]
18:32:18    /home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:630
18:32:18  
18:32:18    Aug  4 01:32:17.407: Failed to connect to exposed host ports
18:32:18  
18:32:18    /home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
```

**Comment by joestringer** [comment]
test-upstream-k8s

**Review by christarazi — APPROVED** [review]

**Comment by joestringer** [comment]
This only modifies a script used in the `test-upstream-k8s` job, which I ran and it passes. Good to merge.

**Pull request merged**
