### PR TITLE
v1.14 Backports 2024-04-30

### PR DESCRIPTION
**Pull request by gandro**
* [x] #31866 (@squeed) :warning: resolved conflicts (see commit message)
 * [ ] #32008 (@darox)
 * [x] #32118 (@marseel)
 * [x] #31999 (@gandro) :warning: resolved conflicts
 * [ ] #32099 (@jasonaliyetti)
 * [x] #32085 (@pchaigno)
 * [ ] #32030 (@JBodkin-Amphora)
 * [ ] #32132 (@jrajahalme)
 * [x] #32176 (@dependabot[bot]) :warning: resolved conflicts (used newer image tag)
 * [x] #32181 (@tklauser) :warning: resolved conflicts (regenerated Helm docs)
 * [x] #32168 (@squeed) :warning: resolved conflicts (see commit message)
 * [x] #32203 (@mhofstetter)
 * [x] #32201 (@marseel)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31866 32008 32118 31999 32099 32085 32030 32132 32176 32181 32168 32203 32201
```

### CODE REVIEW

**Review by mhofstetter — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
My change looks good, thanks Sebastian!

**Review by squeed — APPROVED** [review]

**Comment by gandro** [comment]
/test-backport-1.14

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by marseel — APPROVED** [review]

**Comment by gandro** [comment]
Reviews for non-trivial PRs are in. Merging.

**Pull request merged**
