### PR TITLE
envoy: Import Health check sink API

### PR DESCRIPTION
**Pull request by jrajahalme**
Import Go API for Cilium health check event pipe sink extension for later use.

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
We might need to add import statement in https://github.com/cilium/cilium/blob/main/pkg/envoy/resource/envoy.go (if not already there), otherwise cilium agent will not be able to encode and decode the resources.

**Comment by jrajahalme** [comment]
> We might need to add import statement in https://github.com/cilium/cilium/blob/main/pkg/envoy/resource/envoy.go (if not already there), otherwise cilium agent will not be able to encode and decode the resources.

This extension is part of the CIlium API package which is already imported :-)

**Pull request merged**
