### PR TITLE
bpf: propagate geneve option seclabel after parsing geneve opts

### PR DESCRIPTION
**Pull request by borkmann**

### CODE REVIEW

**Comment by borkmann** [comment]
test-all-ginko

**Comment by eloycoto** [comment]
test-all-ginkgo

**Review by joestringer — COMMENTED** [review]
How did this ever work? Was it actually using VNI before?

I also see in the userspace side, we seem to be writing the length as "4", even though the actual value in the TLV should be 4-byte multiples, ie. "1". I suspect that should mean we end up dropping geneve at the receiver because the length is wrong?

Looks like there's supposed to be testing of this functionality in `test/k8sT/Tunnels.go`, but maybe it's not actually testing end-to-end connectivity?

Minor organizational feedback - could we put this "fetch tunnel_id from skb" helper into common code in bpf/lib/geneve.h and reuse from both v4/v6 paths?

**Review by jrfastab — APPROVED** [review]

**Comment by tgraf** [comment]
> How did this ever work? Was it actually using VNI before?

I'm not sure it ever worked. We added Geneve initially because we believed the 16bit would never be enough but then it never became a problem.

**Comment by borkmann** [comment]
> Looks like there's supposed to be testing of this functionality in test/k8sT/Tunnels.go, but maybe it's not actually testing end-to-end connectivity?

Been talking offline with @eloycoto on that one. It is supposed to send icmp traffic over the vxlan/geneve tunnel in order to test the two modes, but he'll double check to see why the test was not failing so far.

**Pull request closed without merging**
