### PR TITLE
v1.11 backports 2022-07-06

### PR DESCRIPTION
**Pull request by qmonnet**
* [ ] #20361 --  fix identity gc  to return correct  max/min id (@dkhachyan)
 * [ ] #20149 -- api: re-sync bpf drop reasons (@julianwiedmann)
    * Trivial conflict in code, and api/v1/flow/README.md skipped (missing on v1.11)
 * [x] #20269 -- daemon, option: Fix MTU when egress gateway is used (@pchaigno)
 * [x] #20282 -- daemon, option: Fix vlan bpf bypass ids loading (@pippolo84)
    * Minor conflicts on Documentation/cmdref/cilium-agent.md (regenerated) and contrib/scripts/check-viper-unusable-api.sh (kept the most recent version).
 * [ ] #20388 -- ctmap: Do not use nil locks (@jrajahalme)
 * [x] #20399 -- docs: Improve policy troubleshooting guide (@joestringer)
 * [ ] #16499 -- docs: Document clustermesh datapath configuration for non-tunneled modes (@jrajahalme)
 * [ ] #19533 -- Use '.Values.enableIPv4Masquerade' in 'node-init' (@bmcustodio)
 * [x] #20389 -- daemon: Fix issue where stale router IPs were not cleaned up (@gandro)

PRs skipped due conflicts:

 * #20373 -- Restore patch in ciliumnetworkpolicies/status ClusterRole (@pippolo84)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 20361 20149 20269 20282 20388 20399 16499 19533 20389; do contrib/backporting/set-labels.py $pr done 1.11; done
```
or with
```
$ make add-label BRANCH=v1.11 ISSUES=20361,20149,20269,20282,20388,20399,16499,19533,20389
```

### CODE REVIEW

**Comment by qmonnet** [comment]
/test-backport-1.11

**Review by pchaigno — APPROVED** [review]
My PR looks good. Thanks!

**Review by gandro — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Review by pippolo84 — APPROVED** [review]
LGTM, thanks!

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
For https://github.com/cilium/cilium/pull/20149 we only need f9c850cac8d0aeb94cbc56fdc0ab2ab210307c1d. The other two drop reasons [don't exist in the v1.11 datapath](https://github.com/cilium/cilium/pull/20149#issuecomment-1154217658).

**Comment by ti-mo** [comment]
/test-backport-1.11

**Review by julianwiedmann — APPROVED** [review]

**Comment by ti-mo** [comment]
/test-1.21-4.9

**Comment by ti-mo** [comment]
/ci-l4lb-1.11

**Comment by ti-mo** [comment]
/ci-aks-1.11

**Pull request merged**
