### PR TITLE
v1.11 backports 2021-11-26

### PR DESCRIPTION
**Pull request by qmonnet**
* [x] `docs: update Helm reference after updates for latest -rc release` (cc @aanm)
* [x] #17983 (@borkmann)
* [x] #17975 (@errordeveloper)
* [x] #17973 (@borkmann)
* [x] #17968 (@aanm)
* [x] #17969 (@aditighag)
* [x] #17995 (@aanm)
* [x] #17993 (@joestringer)
* [x] #17929 (@brb)
* [x] #17813 (@jibi)
* [x] #17856 (@gandro)
* [x] #18008 (@aanm)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 17983 17975 17973 17968 17969 17995 17993 17929 17813 17856 18008; do contrib/backporting/set-labels.py $pr done 1.11; done
```

### CODE REVIEW

**Comment by qmonnet** [comment]
/test-backport-1.11

**Comment by qmonnet** [comment]
On hold, needs a rebase on top of https://github.com/cilium/cilium/pull/17986. I'll mark as draft for now.

**Comment by aanm** [comment]
/test-backport-1.11

**Review by brb — APPROVED** [review]
LGTM for my changes, thanks.

**Comment by qmonnet** [comment]
/test-backport-1.11

**Review by gandro — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
I like the checkboxes, did we recently change that in the template? (If not, maybe we should :) )

**Review by aditighag — APPROVED** [review]
Backport of my PR looks good. Thanks!

**Review by borkmann — APPROVED** [review]

**Comment by aanm** [comment]
- k8s-1.21-kernel-4.19 hit https://github.com/cilium/cilium/issues/18014

**Comment by aanm** [comment]
The gke-stable failed because there was multiple IP addresses in cilium-host interface. I assume it will be fixed by https://github.com/cilium/cilium/pull/17762

**Review by jibi — APPROVED** [review]

**Comment by qmonnet** [comment]
Thanks André! Summary:

- [`gke-stable`](https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/7052/) is https://github.com/cilium/cilium/issues/17307 and should be fixed by https://github.com/cilium/cilium/pull/17762
- [`k8s-1.17-kernel-4.9`](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-4.9/415/) looks like a hiccup (`Recording test results\nNo test report files were found. Configuration error?`)
- [`k8s-1.18-kernel-4.9`](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.18-kernel-4.9/1824/) is due to a failure to download kubectl in a `BeforeAll` block
- [`k8s-1.19-kernel-4.9`](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.9/1906/) is https://github.com/cilium/cilium/issues/13071
- [`k8s-1.21-kernel-4.19`](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.19/252/) is https://github.com/cilium/cilium/issues/18014
- [`k8s-1.22-kernel-4.9`](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.9/244/) is https://github.com/cilium/cilium/issues/17942

I'm still struggling to triage the [ConformanceGKE](https://github.com/cilium/cilium/runs/4360926779?check_suite_focus=true) failure. @aanm can you also have a look at the [CodeQL](https://github.com/cilium/cilium/pull/18027/checks?check_run_id=4353317976) failure please? I'm not sure how I should handle it?

**Comment by qmonnet** [comment]
/test-1.18-4.9

**Comment by qmonnet** [comment]
/test-1.19-4.9

**Comment by qmonnet** [comment]
/test-1.21-4.19

**Comment by qmonnet** [comment]
/test-1.22-4.9

**Comment by qmonnet** [comment]
/ci-gke-1.11

**Comment by qmonnet** [comment]
The four Jenkins workflows that failed again all hit https://github.com/cilium/cilium/issues/18060 :thinking:
I've seen this on another PR so it's unlikely related to the current backport, though.

**Pull request merged**
