### PR TITLE
[v1.12] renovate: Replace update-hubble-version.sh with Renovate Bot

### PR DESCRIPTION
**Pull request by gandro**
Custom backport of https://github.com/cilium/cilium/pull/23508 to v1.12. This does not contain the `renovate.json` changes (since that file does not exist in stable branches, it's only read by renovate from the default branch).

### CODE REVIEW

**Comment by gandro** [comment]
/test-backport-1.12

**Comment by pchaigno** [comment]
Should we get one of the original reviewers to review this (and sibling backport PRs) as well?

**Comment by gandro** [comment]
> Should we get one of the original reviewers to review this (and sibling backport PRs) as well?

We can, but I don't think it's necessary. It's a fairly harmless change. As long as the image build passes, there should be no functional change, since (if you ignore the deleted scripts) we're basically only adding a few `# renovate` lines that will be picked up by Renovate once it's merged. The worst that could happen I think is that the change does not take any effect, because we missed something in the `renovate.json` in `master`. But that would have to fixed in master and wouldn't change the diff of this PR.

**Comment by gandro** [comment]
Maybe to give more context: Renovate is already active on the v1.1x branches since the upstream PR was merged. It would already bump the Hubble CLI docker images, if they were out of date (which they are currently only in v1.13, see https://github.com/cilium/cilium/pull/23520).

The only interesting thing that this PR here adds (besides the script removal) is the `# renovate` annotations to the pinned digests/version in the shell script. The regex for those annotations is already live on all stable branches and master. Thus, once this PR is merged, Renovate will start automatically updating them if there is a new Hubble CLI GitHub release (which currently, there is not), without any further configuration needed.

**Comment by gandro** [comment]
- https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.9/1576/ hit unrelated flake https://github.com/cilium/cilium/issues/18318
- https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.9/415/ hit unrelated flake https://github.com/cilium/cilium/issues/13071

Marking ready to merge.

**Review by pchaigno — APPROVED** [review]

**Pull request merged**
