### PR TITLE
v1.0 backports 2018-10-11

### PR DESCRIPTION
**Pull request by joestringer**
* #5835
  * Required additional minor rebasing over v1.1/v1.2 backports
* #5837
  * Dropped CRIO YAML patch as CRIO wasn't supported in v1.0.
* #5842
  * Backport #5652 to resolve conflict
* #5855
* #5856

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5847)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

EDIT: Needed bindata rebase.

**Comment by joestringer** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by ianvernon** [comment]
test-me-please

**Comment by jrajahalme** [comment]
@joestringer go-bindata out of date

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Failure:
```
17:41:45 monitor/monitor.go:32:2: cannot find package "github.com/cilium/cilium/pkg/defaults" in any of:
17:41:45 	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/cilium/pkg/defaults (vendor tree)
17:41:45 	/usr/local/go/src/github.com/cilium/cilium/pkg/defaults (from $GOROOT)
17:41:45 	/go/src/github.com/cilium/cilium/pkg/defaults (from $GOPATH)
17:41:45 make: *** [tests-ginkgo-real] Error 1
```

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Failure:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7194/testReport/junit/(root)/runtime/RuntimeValidatedCLI_Identity_CLI_testing_Test_labelsSHA256/

```
17:59:07     runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/cilium'
17:59:07     runtime: go build -i -ldflags '-X "github.com/cilium/cilium/pkg/version.Version=1.0.6 58c6b0941 2018-10-11T17:45:59+00:00 go version go1.9.3 linux/amd64"' -tags lockdebug -o cilium
17:59:21     runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/cilium'
...
18:00:10     runtime: ../cilium/cilium cmdref -d /tmp/tmp.op3C8xGdty
18:00:10     runtime: make[1]: ../cilium/cilium: Command not found
18:00:10     runtime: Makefile:36: recipe for target 'cmdref' failed
18:00:10     runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/Documentation'
18:00:10     runtime: make[1]: *** [cmdref] Error 127
18:00:10     runtime: Makefile:277: recipe for target 'postcheck' failed
18:00:10     runtime: make: *** [postcheck] Error 2
18:00:10 The SSH command responded with a non-zero exit status. Vagrant
18:00:10 assumes that this means the command failed. The output for this command
18:00:10 should be in the log above. Please read the output to determine what
18:00:10 went wrong.
```

Seems like a weird flake, will retry.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Likely the same issue that the v1.1 backports hit, #5867 . Retrying.

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Pull request merged**
