### PR TITLE
endpoint: Make owner a member of Endpoint

### PR DESCRIPTION
**Pull request by jrajahalme**
Endpoint functions taking 'owner' as an argument expect the same
'owner' to be passed across calls to all of these functions. Make
this more explicit by making 'owner' a member of the Endpoint itself.

This allows calls not originating from the 'owner' directly to call
Owner functions. This is needed by later PRs.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8586)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Hit by #8596

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]
LGTM! I've been thinking about doing this for a while, so thanks for taking care of it :)

**Review by gandro — APPROVED** [review]

**Comment by ianvernon** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Pull request merged**
