### PR TITLE
vagrant: bump all vagrant box versions

### LINKED ISSUE #11255: "'stddef.h' file not found" in dev. VM
## Issue
Trying to run the unit tests from inside the dev. VM results in the following error:
```
In file included from unit-test.c:8:
/usr/include/stdlib.h:31:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
```
That error is happening because [we recently switched the compiler for the BPF unit tests to Clang](https://github.com/cilium/cilium/commit/1f0c4a995bf526fe82d5feb2347a61c40a467ac7). The dev. VM images (4.9 and net-next) don't include a full Clang, but only the strict minimum required to compile BPF programs.

## Workaround
The following steps, proposed by André for a similar issue on v1.7, work as a quick fix:
```
sudo mv /usr/bin/clang{,.bak}
sudo mv /usr/bin/llc{,.bak}
sudo apt-get install -y clang-7 llvm-7
sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-7/bin/clang 1000
sudo update-alternatives --install /usr/bin/llc llc /usr/lib/llvm-7/bin/llc 1000
```
To revert:
```
sudo mv /usr/bin/clang{.bak,}
sudo mv /usr/bin/llc{.bak,}
``` 

## Proper Fix
The proper fix requires to revert part of cilium/packer-ci-build#200, to be able to compile on x86 with Clang.

----
Reported-by: Nate Sweet <nathanjsweet@pm.me>

### PR DESCRIPTION
**Pull request by pchaigno**
These include a fix for #11255.

Fixes: #11255

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-me-please

**Review by michi-covalent — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Comment by aanm** [comment]
@pchaigno I've marked this PR to wait for upstream as I'm bumping the image tags in https://github.com/cilium/cilium/pull/12287. Do you think it's worth merging the PR as it is and bump the VM images afterwards or should we wait?

**Pull request merged**
