### PR TITLE
envoy: Bump envoy minor version to v1.29.x

### PR DESCRIPTION
**Pull request by sayboras**
Notable upstream PRs:

- Clang 17 https://github.com/cilium/proxy/pull/710
- Envoy 1.29.3 https://github.com/cilium/proxy/pull/660

Signed-off-by: Tam Mach <tam.mach@cilium.io>

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Helm LGTM!

**Review by rolinh — APPROVED** [review]

**Review by jrajahalme — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Pull request merged**
