### PR TITLE
bpf: improve ethertype validation

### PR DESCRIPTION
**Pull request by lkpdn**
The main motivation here is to suppress misleading DROP notification
from handle_xgress() which says "reason Invalid source ip" when the
frame is not Ethernet II, e.g., LLC frame whose skb->protocol being
set to ETH_P_IP or ETH_P_IPV6 leads to the aforementioned message.
Let's directly validate ethertype instead of checking skb->protocol.
For clarity this patch introduces the error code DROP_UNSUPPORTED_L2.

Fixes: #6305
Signed-off-by: Koichiro Den <den@klaipeden.com>

```release-note
Introduce robust ethertype validation with a new error code DROP_UNSUPPORTED_L2.
```

Quick example to see the new message introduced:
```
# from lxc inside:
$ scapy
>>> sendp(SNAP(code=0xffff)/IP(dst="10.10.10.10"),iface="eth0")
.
Sent 1 packets.
```
```
# from cilium-agent in the same node:                                                                                                                                                                                               
$ cilium monitor -v
[...]
------------------------------------------------------------------------------
CPU 01: MARK 0xafd5e007 FROM 1328 DROP: 25 bytes, reason Unsupported L2 protocol, identity 5440->0
Ethernet        {Contents=[..14..] Payload=[..14..] SrcMAC=00:00:14:00:01:00 DstMAC=00:00:00:ff:ff:45 EthernetType=LLC Length=64}
  Packet has been truncated
------------------------------------------------------------------------------
[...]
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7488)

### CODE REVIEW

**Comment by lkpdn** [comment]
rebased and updated SHA

**Comment by joestringer** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]
New drop reason looks fine. Deferring to the bpf codeowner regarding the datapath change.

**Review by joestringer — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by lkpdn** [comment]
Thanks for the review.

**Pull request merged**
