### PR TITLE
v1.6 backports 2020-05-12

### PR DESCRIPTION
**Pull request by qmonnet**
* #10926 -- bpf: Preserve source identity for hairpin via stack (@tgraf)
     * Based on backport for v1.7, see #11239
 * #11008 -- bpf: remap MARK_MAGIC_SNAT_DONE marker to avoid conflicts (@borkmann)
 * #10928 -- datapath/iptables: Masquerade hairpin traffic that traversed the stack (@tgraf)
     * [updated] Commits 949959643d809007fe1e4c07a4d359b28bab1495 and 4bd2fcdd0397d999583cbce9a03c2bfc3da0e513 intentionally left out: The connectivity check extension relies on portmap and does not seem to work properly on v1.6. We do not want to backport portmap at this time, so let's skip this commit. The test in the second one is based on these connectivity check additions, so there is little interest in picking it without those new checks. Leaving out those two commits mean we don't test in v1.6 that the other two commits for #10928 work as expected, but we can probably trust the CI tests on later versions for that. At least CI should show that it does not introduce any regression.
 * #11467 -- k8s: Do not send DeleteService event upon DeleteEndpoints (@brb)

#### Not included in this batch

 * #10741 -- cilium: set encrypt node route mtu in encryption table (@jrfastab)
     * Depends on 25a890ca67968f06ab5667159a7ea4dbbbce4d04, pending backport (#11044)
 * #10984 -- datapath: Fix wrong rev-NAT xlation due to stale conntrack entry (@brb)
     * Skipped due to non-trivial conflicts. Second commit depends on eb2714e1cab09860b833595907359e28d765c153 (#9687), not backported.
* Two commits from #10928, see note above.

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 10926 11008 10928 11467; do contrib/backporting/set-labels.py $pr done 1.6; done
```

### CODE REVIEW

**Comment by qmonnet** [comment]
never-tell-me-the-odds

**Comment by qmonnet** [comment]
I forgot to build the tests locally, and at least backport from 11467 breaks them.

**Comment by qmonnet** [comment]
Backport for commit 949959643d809007fe1e4c07a4d359b28bab1495 for the Conformance test should now compile and hopefully pass.

<details><summary>Adjustments</summary>

``` diff
diff --git a/test/k8sT/Conformance.go b/test/k8sT/Conformance.go
index c8cc6faa5d22..6b77913c6002 100644
--- a/test/k8sT/Conformance.go
+++ b/test/k8sT/Conformance.go
@@ -23,13 +23,11 @@ import (
 
 var _ = Describe("K8sConformance", func() {
 	var kubectl *helpers.Kubectl
-	var ciliumFilename string
 	var connectivityCheckYaml string
 
 	BeforeAll(func() {
 		kubectl = helpers.CreateKubectl(helpers.K8s1VMName(), logger)
-		connectivityCheckYaml = kubectl.GetFilePath("../examples/kubernetes/connectivity-check/connectivity-check.yaml")
-		ciliumFilename = helpers.TimestampFilename("cilium.yaml")
+		connectivityCheckYaml = helpers.GetFilePath("../examples/kubernetes/connectivity-check/connectivity-check.yaml")
 	})
 
 	BeforeEach(func() {
@@ -38,27 +36,26 @@ var _ = Describe("K8sConformance", func() {
 
 	AfterEach(func() {
 		kubectl.Delete(connectivityCheckYaml)
-		kubectl.DeleteCiliumDS()
+		deleteCiliumDS(kubectl)
 		ExpectAllPodsTerminated(kubectl)
 	})
 
 	AfterFailed(func() {
-		kubectl.CiliumReport(helpers.CiliumNamespace,
+		kubectl.CiliumReport(helpers.KubeSystemNamespace,
 			"cilium endpoint list")
 	})
 
 	AfterAll(func() {
-		DeployCiliumAndDNS(kubectl, ciliumFilename)
+		DeployCiliumAndDNS(kubectl)
 		kubectl.CloseSSHClient()
 	})
 
 	JustAfterEach(func() {
-		blacklist := helpers.GetBadLogMessages()
-		kubectl.ValidateListOfErrorsInLogs(CurrentGinkgoTestDescription().Duration, blacklist)
+		kubectl.ValidateNoErrorsInLogs(CurrentGinkgoTestDescription().Duration)
 	})
 
-	deployCilium := func(options map[string]string) {
-		DeployCiliumOptionsAndDNS(kubectl, ciliumFilename, options)
+	deployCilium := func(options []string) {
+		DeployCiliumOptionsAndDNS(kubectl, options)
 
 		_, err := kubectl.CiliumNodesWait()
 		ExpectWithOffset(1, err).Should(BeNil(), "Failure while waiting for k8s nodes to be annotated by Cilium")
@@ -70,11 +67,10 @@ var _ = Describe("K8sConformance", func() {
 
 	Context("Portmap Chaining", func() {
 		It("Check connectivity-check compliance with portmap chaining", func() {
-			SkipIfIntegration(helpers.CIIntegrationFlannel)
-			SkipItIfNoKubeProxy()
+			SkipIfFlannel()
 
-			deployCilium(map[string]string{
-				"global.cni.chainingMode": "portmap",
+			deployCilium([]string{
+				"--set global.cni.chainingMode=portmap",
 			})
 
 			kubectl.ApplyDefault(connectivityCheckYaml).ExpectSuccess("cannot install connectivity-check")
```
</details>

**Comment by qmonnet** [comment]
never-tell-me-the-odds

**Review by brb — APPROVED** [review]
LGTM for my included change.

**Comment by qmonnet** [comment]
never-tell-me-the-odds

**Comment by jraby** [comment]
Hi,  is there any way to include https://github.com/cilium/cilium/commit/52e070e133694e4439b33d7afaee32e57cf2f483  in this?

I was pretty sure it had made its way in 1.6 back in november, but it didn't.
That commit is required for us since our bridge interface is `cni0` and not `cilium_host`. Without it, cilium replaces the local node's podCIDR route leading to hmmm no network connectivity for all pods.

**Comment by qmonnet** [comment]
never-tell-me-the-odds

**Comment by qmonnet** [comment]
never-tell-me-the-odds

**Comment by qmonnet** [comment]
never-tell-me-the-odds

**Comment by qmonnet** [comment]
Hi @jraby, sorry for not answering sooner. Did you get an answer from another channel, or is your request still pending?

**Comment by qmonnet** [comment]
So after discussing with @joestringer, I changed this PR by leaving out two commits from #10928 (see updated description at the top). All checks are now passing. Please disregard the comments on manual adjustments above, they were for the commits that are no longer part of this PR.

I'm marking the set as ready for review.

**Comment by jraby** [comment]
> Hi @jraby, sorry for not answering sooner. Did you get an answer from another channel, or is your request still pending?

No problem, I haven't used any other channel yet, so my request is still pending.
Would you rather I opened a new issue to discuss this?

**Comment by qmonnet** [comment]
@jraby I discussed it and it appears there is no plan to backport this PR at this time, as we usually avoid to spend cycles for backports other than bug fixes. I would recommend upgrading to 1.7.3 if possible. Alternatively, if you feel like [creating the PR to do the backport](https://docs.cilium.io/en/latest/contributing/release/backports/) yourself, it _should_ be accepted given that the change is light. And yeah, if you have more questions, let's move the discussion to a dedicated issue or to Slack :) Thank you!

**Review by joestringer — APPROVED** [review]

**Pull request merged**
