### PR TITLE
[v1.14] bpf: Fix identity determination in bpf_overlay.c

### PR DESCRIPTION
**Pull request by ysksuzuki**
This PR is the manual backport of https://github.com/cilium/cilium/pull/29155 for v1.14.

When DSR with Geneve is enabled, Cilium identity is not determined by the client's IP address and requests from outside cluster are dropped even though they are permitted by CiliumNetworkPolicy using `fromCIDR`.

This commit inputs identity that is from the client IP address.

Fixes: #29153

Also, this PR backports the following PRs to reduce the divergence from the main to make it easier to backport later changes.

- [bpf: dsr: merge Ingress tail-calls into nodeport_lb*()](https://github.com/cilium/cilium/pull/27267)
- [bpf: ct: simplify ct_action parameter for CT lookup](https://github.com/cilium/cilium/pull/26527)
- [bpf: ct: clean up tuple swapping for forward lookups](https://github.com/cilium/cilium/pull/26826)

### CODE REVIEW

**Comment by julianwiedmann** [comment]
/test-backport-1.14

**Comment by ysksuzuki** [comment]
Need this fix to run BPF complexity tests
https://github.com/cilium/cilium/pull/29553

**Comment by ysksuzuki** [comment]
There is a verifier complexity issue on kernel 6.1 with my branch. https://github.com/cilium/cilium/pull/29377/commits/e3367b9eec83e18a4a32e6cd4d921cd417e903d7 fixed it.

```
level=fatal msg="Failed to compile XDP program" error="loading eBPF collection into the kernel: program tail_handle_snat_fwd_ipv6: load program: argument list too long: BPF program is too large. Processed 1000001 insn (1143 line(s) omitted)" subsys=datapath-loader

# Config
cilium install --wait \
    --chart-directory=/home/yusuke/go/src/github.com/cilium/cilium/install/kubernetes/cilium \
    --helm-set=debug.enabled=true \
    --helm-set=debug.verbose=envoy \
    --helm-set=hubble.eventBufferCapacity=65535 \
    --helm-set=bpf.monitorAggregation=none \
    --helm-set=cluster.name=default \
    --helm-set=authentication.mutual.spire.enabled=false \
    --nodes-without-cilium=kind-worker3 \
    --helm-set-string=kubeProxyReplacement=true \
    --helm-set=image.repository=localhost:5000/cilium/cilium-dev \
    --helm-set=image.useDigest=false \
    --helm-set=image.tag=local \
    --helm-set=image.pullPolicy=Never \
    --helm-set=operator.image.repository=localhost:5000/cilium/operator \
    --helm-set=operator.image.suffix= \
    --helm-set=operator.image.tag=local \
    --helm-set=operator.image.useDigest=false \
    --helm-set=operator.image.pullPolicy=Never \
    --helm-set-string=routingMode=native \
    --helm-set-string=tunnelProtocol=geneve \
    --helm-set-string=autoDirectNodeRoutes=true \
    --helm-set-string=ipv4NativeRoutingCIDR=10.244.0.0/16 \
    --helm-set-string=ipv6NativeRoutingCIDR=fd00:10:244::/56 \
    --helm-set=devices='eth0' \
    --helm-set-string=loadBalancer.mode=dsr \
    --helm-set-string=loadBalancer.dsrDispatch=geneve \
    --helm-set-string=endpointRoutes.enabled=false \
    --helm-set=ipv6.enabled=true \
    --helm-set=bpf.masquerade=true \
    --helm-set=egressGateway.enabled=true \
    --helm-set=loadBalancer.acceleration=testing-only 

```

**Comment by ysksuzuki** [comment]
The BPF complexity test is green. It seems that the issue only occurs with kernel 6.1
https://github.com/cilium/cilium/actions/runs/7101950048/job/19331222570

**Review by julianwiedmann — APPROVED** [review]
looks good, and bringing the additional CT changes doesn't feel too invasive. Thank you!

**Comment by ti-mo** [comment]
@ysksuzuki Looks like the commit messages are missing upstream commit references, see https://docs.cilium.io/en/latest/contributing/release/backports/#codecell6 for an example. If you're not using the backporting scripts/tools, you have to add them in by yourself. :slightly_smiling_face:

**Comment by ysksuzuki** [comment]
/test-backport-1.14

**Comment by ysksuzuki** [comment]
@ti-mo I have added upstream commit references. PTAL. Thanks!

**Pull request merged**
