### PR TITLE
cilium: K8s CI testing for sockops

### PR DESCRIPTION
**Pull request by jrfastab**
To date we've had some basic tests for sockops negative case in k8s and some simple netperf runtime tests. This adds nertperf K8s tests and http tests using wrk.

After this we can add https tests to include ssl and contrib scripts to extract performance metrics over time.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9685)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
retesting old error here, https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/15993/

**Comment by jrfastab** [comment]
I removed netperf-policy.yaml because I no longer use it in k8sT/DatapathConfigurations.go but its still used in Chaos tests. Add it back and retest.

**Comment by jrfastab** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
changes LGTM @jrfastab do we publish the results somewhere so we can have some comparison?

**Comment by jrfastab** [comment]
At the moment results are not published the plan is to push a contrib script to extract the results and then I can run it locally on bare-metal where performance is interesting on some cadence (nightly) and then push results somewhere? Any idea where? I was initially thinking just a git repository with all the data so folks could do whatever with it, consume it and publish in dashboard, etc.

**Pull request merged**
