### PR TITLE
ipam/aws: updated EC2 instances ENI limits and added an helper function to make it easier to do so in the future

### PR DESCRIPTION
**Pull request by mvisonneau**
part of the fix for #14802

On top of #14905, this PR updates the hardcoded EC2 ENI limits to support newly added instance types. I also added as an inline comment the helper I used to recalculate this list dynamically.

```release-note
ipam/aws: updated EC2 instances ENI limits and added an helper function to make it easier to do so in the future
```

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by aanm** [comment]
@mvisonneau can you rebase this PR against master so that we can run the CI? thanks!

**Comment by mvisonneau** [comment]
there you go @aanm :+1:

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
@mvisonneau can you make the commit message title shorter? :pray:

**Comment by mvisonneau** [comment]
absolutely, I need to workout my commit descriptions :sweat_smile:  :+1:

**Comment by aanm** [comment]
test-me-please

**Pull request merged**
