### PR TITLE
test: Allow Cilium 1.4 to be run with K8s 1.14

### PR DESCRIPTION
**Pull request by brb**
This PR makes it possible to run upgrade tests on k8s 1.14 with Cilium 1.4.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7779)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
CI failed due to #7615 and #7721.

**Comment by brb** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Review by eloycoto — APPROVED** [review]

**Comment by jrfastab** [comment]
Already applied to v1.4 by @eloycoto  removing need-backport tag.

**Pull request merged**
