### PR TITLE
1.3: Remove the Codeowners file.

### PR DESCRIPTION
**Pull request by eloycoto**
To do not trigger reviews from all teams in backpors,keep the CODEOWNERS
file only to Janitor teams.

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6031)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-missed-k8s

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
This can be merged; no tests should fail due to this change, though, so the failures should be analyzed.

**Comment by ianvernon** [comment]
Filed #6036 to track the build failure.

**Comment by joestringer** [comment]
@eloycoto @ianvernon I thought we usually leave the `api` codeowners in place for commits like this, to ensure that if API changes are made unintentionally that we catch these before breaking a micro release?

**Pull request merged**
