### PR TITLE
treewide: use /usr/bin/env bash instead of /bin/bash

### PR DESCRIPTION
**Pull request by MrFreezeex**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/master/USERS.md)
- [x] Thanks for contributing!

This commit switch most usage of "/bin/bash" to "/usr/bin/env bash". This allows to conform to the PATH env variable when invoking bash which is especially important on distros/installs in which bash is *NOT* installed in /bin/bash (for instance in some more "exotic" distros like NixOS or even if bash is installed in /usr/local/bin/ for whatever reasons).

The goal here is not to be perfectly exhaustive but to address most low hanging fruits whenever this happens and most importantly should ease Cilium contributions for people which don't have bash installed in /bin/bash.

```release-note
use /usr/bin/env bash instead of /bin/bash in contrib, examples and test dirs
```

### CODE REVIEW

**Comment by MrFreezeex** [comment]
Hey :wave:, this comes with a big change over many files it's mostly a sed which affect mostly shebangs with careful re-reading of the change but this could be pretty well split into multiple commits/PR, let me know.

**Review by nebril — CHANGES_REQUESTED** [review]
Thanks a lot for the PR!

I think that this change might a little too big in scope. I would probably leave anything in `install` and `images` aside from `images/scripts` as is, as these scripts are not running on host, but in containers either during image build or in k8s pods.

Looking through the change this is a list of folders that should be changed:
- `contrib`
- `examples`
- `images/scripts`
- `test`

Not sure about:
- `bpf`
- `pkg/datapath/loader`

**Comment by MrFreezeex** [comment]
> Thanks a lot for the PR!
> 
> I think that this change might a little too big in scope. I would probably leave anything in `install` and `images` aside from `images/scripts` as is, as these scripts are not running on host, but in containers either during image build or in k8s pods.
> 
> Looking through the change this is a list of folders that should be changed:
> 
>     * `contrib`
> 
>     * `examples`
> 
>     * `images/scripts`
> 
>     * `test`
> 
> 
> Not sure about:
> 
>     * `bpf`
> 
>     * `pkg/datapath/loader`

Hi @nebril, thanks for the review! So I ended up dropping everything in `images` as it's actually slightly more complicated than just keeping `images/scripts` because those have dependencies on scripts in directories in the the rest of `images/` (like runtime and builder IIRC). I propose to come back later with another PR for this directory specifically (+ it's also easier for the CI/merge conflict and all).

For the rest I dropped bpf and pkg/datapath/loader mostly but kept travis/github ones as it's testing related so it doesn't look harmful to keep this (and it's also like 3 files anyway). Let me know WDYT of the new version!

**Review by nebril — APPROVED** [review]
LGTM now! I will run the CI and let's see whether this breaks anything there :).

**Review by zacharysarah — COMMENTED** [review]
LGTM from a docs perspective

**Review by nbusseneau — APPROVED** [review]
LGTM, hopefully CI passes :D

**Comment by MrFreezeex** [comment]
The CI failure (https://jenkins.cilium.io/job/Cilium-PR-K8s-1.27-kernel-net-next/34/) are related to a test that I actually added very recently. Not sure why it launch those test though it's not supposed to be in this branch yet. It seems like the CI use the test from master but with the cilium version from my branch somehow. Do you have an idea if this assumption could be somehow correct @jibi :pray:?

Anyway I just rebased this, pretty sure it should work now if anyone could trigger the tests please :pray:.

**Comment by nbusseneau** [comment]
> Do you have an idea if this assumption could be somehow correct

This is correct, rebasing should do it :)

**Comment by joestringer** [comment]
The test run didn't seem to take for a few of the required jobs. I'll re-kick it.

**Comment by MrFreezeex** [comment]
I just rebased, it will most likely be sufficient to fix the few failures in the latest test run.

**Comment by joestringer** [comment]
Hopefully :) Just be aware that we need to re-run CI each time there is a rebase.

**Comment by joestringer** [comment]
k8s-1.24-kernel-5.4 hit https://github.com/cilium/cilium/issues/15455, known flake. No need to block merging on that failure.

**Review by gentoo-root — APPROVED** [review]

**Review by aspsk — APPROVED** [review]
Sorry, I was offline. LGTM, thanks!

**Review by rolinh — APPROVED** [review]

**Review by rgo3 — APPROVED** [review]
No loader specific changes anymore, but LGTM.

**Comment by joestringer** [comment]
:heavy_check_mark: Merged, thanks for the contribution!

**Pull request merged**
