### PR TITLE
v1.4: backports 19-04-29

### PR DESCRIPTION
**Pull request by ianvernon**
* PR: 7834 -- doc: fix up Ubuntu apt-get install command (@liuqun) -- https://github.com/cilium/cilium/pull/7834
* PR: 7865 -- test: make function provided to WithTimeout run asynchronously (@ianvernon) -- https://github.com/cilium/cilium/pull/7865
* PR: 7829 -- contrib: ensure check-fmt.sh runs correctly, and fails if it does not (@ianvernon) -- https://github.com/cilium/cilium/pull/7829

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7880)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-docs-please

**Comment by ianvernon** [comment]
test-missed-k8s

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Issue downloading VMs: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1951/execution/node/37/log/

**Comment by ianvernon** [comment]
test-missed-k8s

**Review by joestringer — APPROVED** [review]

**Pull request merged**
