### PR TITLE
bpf: fix cilium_host unroutable check

### PR DESCRIPTION
**Pull request by borkmann**
See commit msg.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9299)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by borkmann** [comment]
Hit known `Suite-runtime.RuntimeKVStoreTest Consul KVStore` flake, retesting.

**Comment by borkmann** [comment]
test-me-please

**Comment by joestringer** [comment]
> Hit known Suite-runtime.RuntimeKVStoreTest Consul KVStore flake, retesting.

@borkmann Is there an issue for this? I don't see it in the [1.7 CI project](https://github.com/cilium/cilium/projects/85) .

**Review by joestringer — APPROVED** [review]

**Review by brb — APPROVED** [review]

**Comment by borkmann** [comment]
Backport only in 1.6 needed.

**Comment by borkmann** [comment]
> > Hit known Suite-runtime.RuntimeKVStoreTest Consul KVStore flake, retesting.
> 
> @borkmann Is there an issue for this? I don't see it in the [1.7 CI project](https://github.com/cilium/cilium/projects/85) .

Added #9301.

**Pull request merged**
