### PR TITLE
Allow requesting specific IP address

### LINKED ISSUE #17026: Will cilium IPAM support specified ip address of pod?
## Proposal / RFE

**Is your feature request related to a problem?**

**Describe the solution you'd like**

As the title states, in some cases we need a static pod ip address because our program does not support DNS.  We think if a pod can be assign with a static ip address will solve this problem. We wonder if cilium will support it in future versions or maybe there're better ways we haven't found? 
We found that calico IPAM has a feature by setting annotation "cni.projectcalico.org/ipAddrs" can specific ip address to single pod, but cilium has more other powerful features that we need, so we decide use cilium as our network plugin.

Looking forward to your favorable  reply.

### PR DESCRIPTION
**Pull request by kvaps**
Add the oportunity to request specific IP-address using annotation:

    cni.cilium.io/ipAddress: 10.10.10.10

fixes #17026

---

Hello, we use this fix in [Deckhouse](https://github.com/deckhouse/deckhouse/tree/main/modules/021-cni-cilium/images/cilium/patches) to provide virtual machines a stable IP address which is not changing during live migration.

This allows to live-migrate virtual machine without reconfiguring network interfaces and routes in it. 

We would like to have this opportunity in upstream, so we are ready to update it according to your recommendations.
If you are interested in this patch to get merged, please guide us for rewriting it in a more correct way.

related issues:
- <s>https://github.com/cilium/cilium/pull/17097</s> (old implementation)
- <s>https://github.com/cilium/cilium/pull/19789</s> (old implementation)
- https://github.com/cilium/cilium/pull/24100
- https://github.com/kubevirt/kubevirt/pull/7768
- https://github.com/kubevirt/community/pull/182

---

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
Allow requesting specific IP address using `cni.cilium.io/ipAddress` annotation
```

### CODE REVIEW

**Comment by joestringer** [comment]
Just a heads up for when this gets proposed, there's a few questions that come up with this current implementation:
1. Does this still have the limitations that folks were concerned about in the #17097 proposal, and is the "more flexible IPAM" solution in a better state now?
2. This is signed off as though the code was written entirely by you, but it looks like substantial portions came from #17097, in which case the PR should at least include `Co-authored-by` tag to indicate the provenance.
3. I see a k8s lister, does that cause problems at scale and is there already an existing caching mechanism for annotation state like this?
4. The vendor change seems to be made directly to the `vendor/` tree without submitting the change upstream to the vendor and then updating the vendor dependency. That will cause some issues, the proposal would need to go through https://github.com/cilium/ipam . (Though that said, the change by itself also looks a bit sketchy since it removes error checking logic, but that would be subject to upstream review)

**Comment by joestringer** [comment]
Oh, and for context, the primary reason this didn't get any comments before is that it's marked as draft. Typically in Cilium, draft status suggests that you are still working on the patches so the Cilium community won't take a closer look.

**Comment by david972** [comment]
Would be great, indeed

**Comment by kvaps** [comment]
This patch is still actual

**Comment by MohammedNoureldin** [comment]
Good job! I guess this is still relevant, right? Do you have any estimation for its release?

**Comment by SixFive7** [comment]
> Oh, and for context, the primary reason this didn't get any comments before is that it's marked as draft. Typically in Cilium, draft status suggests that you are still working on the patches so the Cilium community won't take a closer look.

@kvaps Is the draft status correct?

**Comment by neoareslinux** [comment]
any update?

**Comment by MohammedNoureldin** [comment]
Is this PR required to select a specific IP /32?

Or is it deprecated after merging https://github.com/cilium/cilium/pull/26488?

**Comment by joestringer** [comment]
I think you should be able to use multi-pool IPAM for this use case?

**Pull request closed without merging**
