### PR TITLE
test: Run WG with per-endpoint routes

### PR DESCRIPTION
**Pull request by brb**
Just to have confidence that nothing is broken with this setup.

### CODE REVIEW

**Comment by brb** [comment]
test-net-next

**Review by jibi — APPROVED** [review]

**Comment by brb** [comment]
test-net-next

**Comment by brb** [comment]
CI failed (`K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing With host policy Tests NodePort`)
```
/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Request from testclient-pdw8w pod to service http://10.106.23.200:10080 failed
Expected command: kubectl exec -n default testclient-pdw8w -- /bin/bash -c 'fails=""; id=$RANDOM; for i in $(seq 1 10); do if curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://10.106.23.200:10080 -H "User-Agent: cilium-test-$id/$i"; then echo "Test round $id/$i exit code: $?"; else fails=$fails:$id/$i=$?; fi; done; if [ -n "$fails" ]; then echo "failed: $fails"; fi; cnt="${fails//[^:]}"; if [ ${#cnt} -gt 0 ]; then exit 42; fi' 
To succeed, but it failed:
Exitcode: 42 
Err: exit status 42
Stdout:
```

**Comment by brb** [comment]
test-net-next

**Comment by brb** [comment]
The net-next passed, marking as ready to merge.

**Pull request merged**
