### PR TITLE
test: add k8s 1.12 test framework

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4265)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Review by raybejjani — APPROVED** [review]
works for me.
Did we have instructions on how to add (or remove) a new version?

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-k8s-missed

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/285

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/299/

**Comment by aanm** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/303/

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
@raybejjani

> works for me.
> Did we have instructions on how to add (or remove) a new version

I just copy paste the existing versions and increment to the new one

**Comment by aanm** [comment]
test-me-please

**Comment by raybejjani** [comment]
> I just copy paste the existing versions and increment to the new one

I thought we had a make target that created all the versions we need, no? If we're not using that regularly we should take it out, maybe?

**Comment by aanm** [comment]
>I thought we had a make target that created all the versions we need, no? If we're not using that regularly we should take it out, maybe?

@raybejjani Are you talking about jenkins or the `examples/kubernetes`?

**Comment by raybejjani** [comment]
I meant the Makefile, but you already modified that. I guess I though you were saying you copy-pasted the files, as opposed to the sections in the scripts and makefile. So, my bad.

**Comment by aanm** [comment]
test-me-please

**Comment by ianvernon** [comment]
@aanm this may work now that we disable kube-dns in 1.11 ( see 8c8f7ae7df1e505883ceb7fd1bc1ec6fa63e264c ) - may need a similar check for 1.12.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/345/ Hit #4431

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/347/ Hit #4431 again

**Comment by aanm** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/349/ hit #4431 again

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/350 hit #4431 again

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
Hit non kafka issue https://jenkins.cilium.io/view/PR/job/Cilium-PR-Ginkgo-Tests-Validated/4213/testReport/k8s-1/10/K8sValidatedChaosTest_Endpoint_can_still_connect_while_Cilium_is_not_running/

trying again

**Comment by manalibhutiyani** [comment]
test-me-please

**Comment by manalibhutiyani** [comment]
test-missed-k8s

**Comment by manalibhutiyani** [comment]
haven't hit #4431 after rebasing with #4488 yet!

**Comment by manalibhutiyani** [comment]
test-upstream-k8s

**Comment by manalibhutiyani** [comment]
Hit non kafka issue, #3878
k8s-1.10.K8sValidatedUpdates Updating Cilium stable to master
trying again

**Comment by manalibhutiyani** [comment]
test-missed-k8s

**Comment by manalibhutiyani** [comment]
test-upstream-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
Hit #3878

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
waiting on https://github.com/cilium/cilium/pull/4555

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by manalibhutiyani** [comment]
removing needs-backport/1.1 and 1.0 since already back ported to respective branches

**Pull request merged**
