### PR TITLE
examples/kubernetes: fix k8s 1.12 cilium image tag

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4761)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by aanm** [comment]
to check if it's a flake https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/482/

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
It is a known bug already fixed on master but is not yet backported to v1.1 https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/498/testReport/junit/k8s-1/9/K8sValidatedUpdates_Updating_Cilium_stable_to_master/

**Comment by aanm** [comment]
test-missed-k8s

**Pull request merged**
