### PR TITLE
Added Last page Edit on Documentation

### PR DESCRIPTION
**Pull request by gailsuccess**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #21847` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Screenshot from 2024-02-03 02-22-02

Fixes: #21847

```release-note
Added Last page Edit on Documentation
```

### CODE REVIEW

**Comment by gailsuccess** [comment]
Hello @qmonnet , thank you for sharing [this information ](https://github.com/cilium/cilium/issues/21847#issuecomment-1318839617). It helped me a lot . Please have a look at my PR.

**Review by qmonnet — APPROVED** [review]
Looks pretty straightforward, thanks!

**Comment by learnitall** [comment]
@qmonnet reviewed on `sig/docs-structure` so I'll remove myself from reviewing as well.

**Comment by qmonnet** [comment]
Works well on the main branch, let's mark it for backport to the older branches too

**Pull request merged**
