### PR TITLE
Jenkins: Fix issues with downstreams Jobs 

### PR DESCRIPTION
**Pull request by eloycoto**
- Added `sha1` and `ghprbSourceBranch` in parameters to build the    
downstreams jobs.                                                    
- Fix some jenkins jobs report status

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
@cilium/ci Hi 

Quick update, maybe this does not work, but let me explain. The Jenkins parameters, when call to a downstream job, are not in place yet. So the parameters need to be specified in the build before to be in the Jenkins Job.  

I will suggest merging this PR, and as soon all PRs have the correct parameters the downstream jobs will work as normal, but need to run these Jenkinsfiles to get these parameters. 

There is one issue, the Kubernetes Upstream tests are failing, issue tracked on #4131 and #4132. 

Regards

**Comment by eloycoto** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Pull request merged**
