### PR TITLE
v1.14 Backports 2024-08-14

### PR DESCRIPTION
**Pull request by jschwinger233**
* [x] #33945 (@viktor-kurchenko)
 * [x] #34190 (@joestringer)
 * [x] #34247 (@sayboras)
 * [x] #34339 (@sayboras) :warning: resolved conflicts

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 33945 34190 34247 34339
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Thanks and looks good for my commits :+1:

**Review by viktor-kurchenko — APPROVED** [review]
Thank you!

**Review by joestringer — APPROVED** [review]
Thanks!

**Review by christarazi — APPROVED** [review]

**Review by youngnick — APPROVED** [review]

**Comment by jschwinger233** [comment]
/test-backport-1.14

**Pull request merged**
