### PR TITLE
Add troubleshooting section

### PR DESCRIPTION
**Pull request by briantopping**
Add troubleshooting documentation from helpful debugging session. 

Signed-off-by: Brian Topping <brian.topping@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6601)

### CODE REVIEW

**Comment by eloycoto** [comment]
Hi @briantopping 

Thanks for the contribution, really appreciate it. 

Few things: 

1) Commits for contribute in Cilium need to be signed, http://docs.cilium.io/en/v1.3/contributing/?highlight=sign%20commits#dev-coo

2) Your guide looks good to me, but it'll be nice if we can get out that image, that is always hard to maintain up-to-date, my proposal is to have something like that: 

```
kubectl -n kube-system exec -ti cilium-q8wvt -- cilium endpoint get 59084 -o jsonpath='{.status.status.policy.realized.policy-enabled}`
```

So the output can be in json and it's easier to copy and paste and keep up to date. 

3) I'm happy if you don't mention/add this, but if you're using Kubernetes >= 1.11 you can use `kubectl get cep` that is the list of the cilium endpoints with the same endpoint information that you have per each Cilium Pod, so you don't need to access to cilium pod at all and you can use the pod names, here is an example: 

```

vagrant@k8s1:~$ kubectl get pods
NAME                    READY   STATUS    RESTARTS   AGE
app1-6f995955d9-bdjw7   1/1     Running   0          7h41m
app1-6f995955d9-dcng7   1/1     Running   0          7h41m
app2-5b49d5dd9-tqdqn    1/1     Running   0          7h41m
app3-645549cb84-4drzj   1/1     Running   0          7h41m
bind-6755c5c8-c24p5     1/1     Running   0          7h34m
vagrant@k8s1:~$ kubectl get cep
NAME                    ENDPOINT ID   IDENTITY ID   POLICY ENFORCEMENT   ENDPOINT STATE   IPV4          IPV6
app1-6f995955d9-bdjw7   3253          61971         none                 ready            10.10.0.239   f00d::a0a:0:0:3a80
app1-6f995955d9-dcng7   37            61971         none                 ready            10.10.0.247   f00d::a0a:0:0:21c5
app2-5b49d5dd9-tqdqn    581           48968         none                 ready            10.10.0.248   f00d::a0a:0:0:ced
app3-645549cb84-4drzj   3425          1596          none                 ready            10.10.0.165   f00d::a0a:0:0:3901
bind-6755c5c8-c24p5     4095          14452         none                 ready            10.10.0.103   f00d::a0a:0:0:15ab
vagrant@k8s1:~$ kubectl get cep app2-5b49d5dd9-tqdqn -o json | jq '.status.status.policy.realized'
{
  "allowed-egress-identities": [
    2,
    106,
    100,
    103,
    48968,
    5,
    3,
    1596,
    4,
    31653,
    105,
    101,
    102,
    1,
    104,
    61971,
    14452
  ],
  "allowed-ingress-identities": [
    3,
    61971,
    5,
    48968,
    101,
    31653,
    106,
    102,
    103,
    104,
    100,
    1596,
    14452,
    1,
    105,
    2,
    4
  ],
  "build": 14,
  "cidr-policy": {
    "egress": [],
    "ingress": []
  },
  "id": 48968,
  "l4": {
    "egress": [],
    "ingress": []
  },
  "policy-enabled": "none",
  "policy-revision": 14
}
```

Thanks for contributing!

**Comment by briantopping** [comment]
Hi @eloycoto, thanks for the feedback! Appreciate you pulling me through he process. 

I thought I had complied with the dev procedure. I can certify the statement in http://docs.cilium.io/en/v1.3/contributing/?highlight=sign%20commits#developer-s-certificate-of-origin, so I added the line to my commit. Do I need to certify the statement and send it to someone? 

Agreed on the maintenance, I had not thought of that. Now that you mention it, it's even better when the source document is checked in like live code. But I definitely see where you are going. What I was trying to do is demonstrate filtering information density, the old "hand a fish to a hungry man / teach him how to fish" parable. It's very hard to show collapsed structure without an image. I also know some `jsonpath` and it's the bomb-diggity, was just catering a bit to the folks that might otherwise interrupt Thomas and André...

Would it help if I "fuzzed" the image some so people weren't looking at the actual content and it suddenly wasn't going out of date? Just a thought. 

I like the last suggestion, just kind of curious about this to start. Thanks!!

**Comment by joestringer** [comment]
Hi @briantopping, thanks for the contribution!

It looks like your sign-off was added to the PR description, but not the commit description which might be part of the confusion (see here for your commit log: https://github.com/cilium/cilium/pull/6601/commits/ddc38800a8aa7006d78461fe0a2487b784c5a5c4). You can add the signoff to the commit log using `git commit --amend --signoff`.

**Review by tgraf — APPROVED** [review]
I personally like the image a lot. It doesn't matter if it gets slightly out of date. It gets the point across nicely on how to dig into JSON.

**Comment by tgraf** [comment]
test-docs-please

**Comment by briantopping** [comment]
Thanks Thomas, that's kind of what I was thinking too, but the hive mind brings better solutions: What if we watermarked it with `SAMPLE` in diagonal grey type like is common for every other information domain? Maybe that solves future update problems?
troubleshooting_policy

**Comment by tgraf** [comment]
I think this is fine to merge. I'm happy with it and I haven't heard and further concrete change requests.

**Pull request merged**
