### PR TITLE
v1.15 Backports 2024-06-04

### PR DESCRIPTION
**Pull request by viktor-kurchenko**
* [x] #31514 (@tskinn)
 * [x] #32304 (@marseel)
 * [x] #32694 (@dswaffordcw)
 * [x] #32338 (@stelucz)
 * [x] #32860 (@aanm)

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
 31514 32304 32694 32338 32860
```

### CODE REVIEW

**Comment by viktor-kurchenko** [comment]
/test-backport-1.15

**Review by christarazi — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by viktor-kurchenko** [comment]
/test-backport-1.15

**Review by marseel — APPROVED** [review]
Thanks!

**Review by qmonnet — CHANGES_REQUESTED** [review]
Commit https://github.com/cilium/cilium/pull/32889/commits/0dcd53f12ca4ca4d8b8b8942535d6883104f54b1 in this PR has the same commit title and description as https://github.com/cilium/cilium/commit/686876c727282710f23145239ae908060d29a7bb, including the upstream commit reference and backporter notes, although the contents are distinct. Please take a look. Maybe the two commits need to be squashed together? I see the original PR had just one commit.

**Review by qmonnet — APPROVED** [review]
Thanks!

**Comment by qmonnet** [comment]
/test-backport-1.15

**Comment by viktor-kurchenko** [comment]
> Thanks!

Thank you very much @qmonnet !

**Pull request merged**
