### PR TITLE
v1.8 backport 2020 06 26

### PR DESCRIPTION
**Pull request by jrfastab**
v1.8 backports 2020-06-26

 * #12257 -- hubble/peer: fix buf.Pop() crash issue (@Jianlin-lv)
 * #12271 -- docs: fix set flag in upgrade guide (@aanm)
 * #12102 -- install/kubernetes: Helm option for fragment tracking (@pchaigno)
 * #12267 -- test: Fix ginkgo -cilium help output (@pchaigno)
 * #12276 -- docs: clarify helm options for kubernetes ipam (@aanm)
 * #12275 -- install/kubernetes: remove mapDynamicSizeRatio leftover (@aanm)
 * #12262 -- docs: Support minikube in Hubble getting started guide (@gandro)
 * #12254 -- build: install gops binary in operator images (@tklauser)
 * #12269 -- hubble:Add unit test for Pop with closed stop chan (@Jianlin-lv)
 * #12239 -- test: Display error in case command fails (@pchaigno)
 * #12287 -- packaging/docker: update cni loopback to 0.8.6 (@aanm)
 * #12274 -- Helm: Make nodeinit image, tag and registry configurable using helm values (@seanmwinn)
 * #12272 -- docs: Mark host-policies as tech preview (@joestringer)
 * #12285 -- hubble/peer: prevent pushing to buffer when it's closed (@Rolinh)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 12257 12271 12102 12267 12276 12275 12262 12254 12269 12239 12287 12274 12272 12285; do contrib/backporting/set-labels.py $pr done 1.8; done
```

### CODE REVIEW

**Comment by jrfastab** [comment]
test-backport-1.8

**Comment by jrfastab** [comment]
@aanm Please take a look at backport of this one there was a conflict in Dockerfile and it wasn't obvious to me what the right choice was for quay.io image in 1.8 thanks! 

   #12287 -- packaging/docker: update cni loopback to 0.8.6 (@aanm)

**Review by tklauser — APPROVED** [review]

**Comment by aanm** [comment]
test-backport-1.8

**Review by aanm — APPROVED** [review]
I had to create a runtime image for this branch. I've fixed my commit, thanks for the warning @jrfastab

**Review by pchaigno — APPROVED** [review]
:+1: for my changes.

**Review by vadorovsky — APPROVED** [review]

**Pull request merged**
