### PR TITLE
 [v1.13] ipsec: Safely delete Xfrm state

### PR DESCRIPTION
**Pull request by jschwinger233**
- [ ] #32450 @jschwinger233 

Once this PR is merged, a GitHub action will update the labels of these PRs:
```upstream-prs
32450
```

### CODE REVIEW

**Comment by jschwinger233** [comment]
/test-backport-1.13

**Comment by jschwinger233** [comment]
/test-1.24-4.19

**Comment by jschwinger233** [comment]
/test-1.26-net-next

**Comment by jschwinger233** [comment]
/test-1.26-net-next

**Review by julianwiedmann — APPROVED** [review]
lgtm, and identical to https://github.com/cilium/cilium/pull/32704.

**Review by lmb — APPROVED** [review]

**Pull request merged**
