### PR TITLE
Fix panic in ipsec/xfrm_collector.go

### LINKED ISSUE #34643: SIGSEGV: segmentation violation in ipsec/xfrm_collector.go
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

First, I realized the following [Talos Linux conformance tests failures](https://github.com/isovalent/terraform-aws-talos/actions/runs/10664100244/job/29554686872#step:8:6694):
```
  ❌ pod-to-ingress-service/pod-to-ingress-service/curl-0: cilium-test/client-69748f45d8-zfrkh (100.64.1.110) -> /cilium-ingress-ingress-service (cilium-ingress-ingress-service.:80)
  ❌ pod-to-ingress-service/pod-to-ingress-service/curl-1: cilium-test/client2-ccd7b8bdf-hhqxq (100.64.1.98) -> /cilium-ingress-ingress-service (cilium-ingress-ingress-service.:80)
  ❌ pod-to-ingress-service/pod-to-ingress-service/curl-2: cilium-test/client3-868f7b8f6b-8thnh (100.64.0.2) -> /cilium-ingress-ingress-service (cilium-ingress-ingress-service.:80)
```

Suspicious was that the same test scenario (Cilium 1.16.1 + IPsec enabled) already failed last week (see [GH workflow log](https://github.com/isovalent/terraform-aws-talos/actions/runs/10556850383/job/29243234624#step:8:6759)). Hence, I downloaded the [sysdump from this week's failure](https://github.com/isovalent/terraform-aws-talos/actions/runs/10664100244/artifacts/1881559237) (`cilium-sysdump-10664100244-184.zip`) and found crash looping Cilium Agent Pods:
```
kube-system                     cilium-p69w8                                     0/1     Running            15 (52s ago)     51m   10.0.102.156   ip-10-0-102-156   <none>           <none>
kube-system                     cilium-4cvr8                                     0/1     CrashLoopBackOff   13 (68s ago)     51m   10.0.102.243   ip-10-0-102-243   <none>           <none>
```

Having a look at the Cilium Agent logs (e.g., `logs-cilium-4cvr8-cilium-agent-20240902-095631-prev.log`) revealed a `SIGSEGV` in `/go/src/github.com/cilium/cilium/pkg/datapath/linux/ipsec/xfrm_collector.go` (likely around line `156`). See the relevant code [here](https://github.com/cilium/cilium/blob/v1.16.1/pkg/datapath/linux/ipsec/xfrm_collector.go).

### How can we reproduce the issue?

Leverage the Talos test environment from [here](https://github.com/isovalent/terraform-aws-talos/tree/main/example).

### Cilium Version

1.16.1

### Kernel Version

6.6.43

### Kubernetes Version

v1.29.3

### Regression

_No response_

### Sysdump

[cilium-sysdump-10664100244-184.zip](https://github.com/user-attachments/files/16837404/cilium-sysdump-10664100244-184.zip)

### Relevant log output

```shell
2024-09-02T09:55:23.016816809Z panic: runtime error: invalid memory address or nil pointer dereference
2024-09-02T09:55:23.016842124Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9d0258]
2024-09-02T09:55:23.016845372Z 
2024-09-02T09:55:23.017515907Z goroutine 2226 [running]:
2024-09-02T09:55:23.017525417Z log/slog.(*Logger).Handler(...)
2024-09-02T09:55:23.017529102Z 	/usr/local/go/src/log/slog/logger.go:122
2024-09-02T09:55:23.017649655Z log/slog.(*Logger).Enabled(0xc002cad538?, {0x44ba1a0?, 0x6ef0a80?}, 0xc002cad548?)
2024-09-02T09:55:23.017653768Z 	/usr/local/go/src/log/slog/logger.go:169 +0x18
2024-09-02T09:55:23.017801504Z log/slog.(*Logger).log(0x0, {0x44ba1a0, 0x6ef0a80}, 0x8, {0x3e7db69, 0x1e}, {0xc001e11ed0, 0x2, 0x2})
2024-09-02T09:55:23.017805943Z 	/usr/local/go/src/log/slog/logger.go:242 +0x6a
2024-09-02T09:55:23.017809162Z log/slog.(*Logger).Error(...)
2024-09-02T09:55:23.017812057Z 	/usr/local/go/src/log/slog/logger.go:230
2024-09-02T09:55:23.017856154Z github.com/cilium/cilium/pkg/datapath/linux/ipsec.(*xfrmCollector).collectErrors(0xc001d1cff0, 0xc002b42780)
2024-09-02T09:55:23.017860350Z 	/go/src/github.com/cilium/cilium/pkg/datapath/linux/ipsec/xfrm_collector.go:93 +0x109
2024-09-02T09:55:23.017926328Z github.com/cilium/cilium/pkg/datapath/linux/ipsec.(*xfrmCollector).Collect(0xc001d1cff0, 0xc002b42780)
2024-09-02T09:55:23.017963489Z 	/go/src/github.com/cilium/cilium/pkg/datapath/linux/ipsec/xfrm_collector.go:156 +0x1d
2024-09-02T09:55:23.017967665Z github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
2024-09-02T09:55:23.018031191Z 	/go/src/github.com/cilium/cilium/vendor/github.com/prometheus/client_golang/prometheus/registry.go:455 +0x105
2024-09-02T09:55:23.018035011Z created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather in goroutine 2224
2024-09-02T09:55:23.018124359Z 	/go/src/github.com/cilium/cilium/vendor/github.com/prometheus/client_golang/prometheus/registry.go:547 +0xbab
```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Fixes: #34643

```release-note
Fix agent panic when IPsec is enabled but XFRM stats are not exposed by the kernel.
```

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Review by derailed — APPROVED** [review]
@chaunceyjiang Great catch. Thank you for this update!

**Review by sayboras — APPROVED** [review]
Thanks

**Pull request merged**
