### PR TITLE
v1.14 Backports 2023-09-08

### PR DESCRIPTION
**Pull request by margamanterola**
* [ ] #28012 (@jrfastab)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
for pr in 28012; do contrib/backporting/set-labels.py $pr done 1.14; done
```
or with
```
make add-labels BRANCH=v1.14 ISSUES=28012
```

### CODE REVIEW

**Comment by margamanterola** [comment]
Failures are unrelated to IPSec (currently v1.14 is failing due to a recent commit that broke some tests)

**Comment by margamanterola** [comment]
/test-backport-1.14

**Review by michi-covalent — APPROVED** [review]
@jrfastab could you also approve this 🙏

**Review by jrfastab — APPROVED** [review]

**Pull request merged**
