### PR TITLE
Fix: resync IP addresses for instances that have been stopped for more than a minute

### LINKED ISSUE #11088: Cloud weather causes node to never receive ENI/IPs in CRD-backed IPAM mode
## Bug report
Note: running in CRD-backed IPAM mode.

During an AWS outage, we got into a state where several of our nodes were without ENIs/IPs indefinitely, requiring manual action to recover. During the AWS outage, the operator had gone through several rounds of ENI creation + attach failure + ENI deletion (the attach operation was failing AWS-side). However, eventually the ENI attach operation returned an (incorrect) error message: `Instance '[REDACTED]' is not 'running' or 'stopped'.`

This error message usually indicates the node was terminated and the k8s node will disappear shortly as well. However, in this case, the error message was incorrect, and that node was still around. Even after AWS had recovered, this node remained without ENIs/IPs, blocking the cilium-agents on those nodes. The CiliumNode resource was never updated, and thus the IP deficit was never resolved.

The proposed solution here is for the operator to mark not-running nodes "alive" once every minute or so, and retry the operations to resolve the IP deficit of that node. In the normal case, the k8s node should be gone before this happens (and if it does not, we'll just mark it not-running again), and in the degenerate case described above, we will recover without manual intervention. 

**General Information**

- Cilium version (run `cilium version`): 1.6.8
- Kernel version (run `uname -a`): Linux ip-10-0-2-30.ec2.internal 4.15.0-1065-aws #69-Ubuntu SMP Thu Mar 26 02:17:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...): k8s 1.15.9
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)

**How to reproduce the issue**

This is difficult to reproduce because it requires your cloud-provider to misbehave. Reporting that a node is not running on an ENI-attach operation will get you into this abandoned state.

### PR DESCRIPTION
**Pull request by willdeuschle**
Maintain IP addresses for instances that have been stopped for more than a minute whose k8s nodes haven't been deleted yet.

Previously, it was possible to get into a state where a node would never
acquire IPs in CRD-backed IPAM mode if the cloud provider incorrectly
returned an error message indicating the instance was stopped. This
patch allows for those nodes to recover without needing manual action.

Fixes: #11088

Signed-off-by: Will Deuschle wdeuschle@palantir.com

### CODE REVIEW

**Comment by ungureanuvladvictor** [comment]
test-me-please

**Comment by ungureanuvladvictor** [comment]
@tgraf I suspect the failures on GKE are not related to this PR, any place I can add them for future tracking of flakes?

**Comment by pchaigno** [comment]
test-gke

**Comment by ungureanuvladvictor** [comment]
test-gke

**Review by christarazi — COMMENTED** [review]
Change looks good to me. Why did you choose a 1 minute value, or is it just a heuristic?

**Review by tgraf — APPROVED** [review]

**Comment by willdeuschle** [comment]
@christarazi just a heuristic - enough time in the general case for a terminated node to be deleted from k8s but not so long that a node without IPs would be unusable for many minutes

**Review by christarazi — APPROVED** [review]

**Pull request merged**
