### PR TITLE
enable Prometheus metrics for Hubble Relay

### LINKED ISSUE #30475: Helm chart | Enable Prometheus metrics for Hubble Relay
### Is there an existing issue for this?

- [X] I have searched the existing issues

I have installed Cilium via its Helm chart in the `kube-system` namespace of a _kind_ cluster.
I want to enable Prometheus metrics for the Hubble Relay component.
I have set the `hubble.relay.prometheus.enabled` field in the _values.yaml_ file to `true`.

### `values.yaml`
```yaml
policyEnforcementMode: always
hubble:
  metrics:
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - tcp
    - flow
    - icmp
    - http
  relay:
    enabled: true
    prometheus:
      enabled: true              # appears to have no effect
  ui:
    enabled: true
prometheus:
  enabled: true
operator:
  prometheus:
    enabled: true
```

### What I expected to happen
The `hubble-relay` pod and the `hubble-relay-metrics` service should have been _annotated_ in a specific manner, in order to let the Prometheus server know which endpoint has been exposed for scraping.

`kubectl get -nkube-system po/hubble-relay-<replica_set>-<pod> -ojson |jq .metadata.annotations`

```json
{
  "prometheus.io/port": "9966",
  "prometheus.io/scrape": "true"
}
```

### What happened
Neither the `hubble-relay` pod nor the `hubble-relay-metrics` service have been annotated accordingly.

Running the cmd above produces `null` as a result.

### Recommendation

If this is not a misconfiguration on my part, and providing this functionality is no longer relevant for Hubble Relay, perhaps consider removing this field from the `values.yaml` file, or at least mark it as deprecated to avoid further confusion in the future.

### Cilium Version

```
cilium-cli: v0.15.20 compiled with go1.21.6 on darwin/arm64
cilium image (default): v1.14.5
cilium image (stable): v1.14.6
cilium image (running): 1.14.6
```

### Kernel Version

`Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64`

### Kubernetes Version

```
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Fixes: #30475

```release-note
helm: Fix Prometheus metrics annotations for Hubble Relay
```

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Thanks!

**Review by rolinh — APPROVED** [review]

**Comment by karojohn** [comment]
@tommyp1ckles please review at your earliest convenience.

**Pull request merged**
