### PR TITLE
envoy: Update to use original source address also for external destinations

### PR DESCRIPTION
**Pull request by jrajahalme**
Update `cilium-envoy` to use original source address also for external destinations.

Change to support original source addressing regardless of the datapath mode.

Related cilium-envoy change: https://github.com/cilium/proxy/pull/742

### CODE REVIEW

**Comment by squeed** [comment]
Can you link to the corresponding cilium-envoy changes? And what's the procedure for rolling out a change to both repositories -- do we tag a new c-e version first, or use a -dev image until release day, then tag both at the same time?

**Review by youngnick — APPROVED** [review]

**Comment by jrajahalme** [comment]
> Can you link to the corresponding cilium-envoy changes? And what's the procedure for rolling out a change to both repositories -- do we tag a new c-e version first, or use a -dev image until release day, then tag both at the same time?

Added link to the PR into the description.

Currently we do not tag cilium-envoy releases. Release builds are made from each merge to main and release branches, so updating cilium agent repo to those can be merged without any further process. 

`-dev` images are built for `cilium/proxy` PRs, `cilium/cilium` PRs referring to those should never be merged. Once we figure PR is good to merge, we can then use the release builds and merge.

**Review by sayboras — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]

**Comment by jrajahalme** [comment]
Rebased to resolve context conflict in images/cilium/Dockerfile

**Review by squeed — APPROVED** [review]

**Review by borkmann — APPROVED** [review]

**Comment by jrajahalme** [comment]
rebased due to images no longer being available for the last test

**Pull request merged**
