### PR TITLE
fix: remove help message in build config failure

### LINKED ISSUE #28158: config init container prevented Cilium from coming up without useful information
Cilium was unable to be provisioned which resulted in the following message on a `kubectl describe pod -n kube-system cilium-123`
```
Init Containers:
  config:
    Container ID:  containerd://0ae84d5f730feed99842a5f7a7b42d5f2443b7d33a931c29a2a4fbd787a9223d
    Image:         quay.io/cilium/cilium:v1.14.1
    Image ID:      quay.io/cilium/cilium@sha256:edc1d05ea1365c4a8f6ac6982247d5c145181704894bb698619c3827b6963a72
    Port:          <none>
    Host Port:     <none>
    Command:
      cilium
      build-config
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   eys that are allowed to be overridden (e.g. set from not the first source. Takes precedence over deny-config-keys
      --deny-config-keys strings         List of configuration keys that are not allowed to be overridden (e.g. set from not the first source. If allow-config-keys is set, this field is ignored
      --dest string                      Destination directory to write the fully-resolved configuration. (default "/tmp/cilium/config-map")
      --enable-k8s                       Enable the k8s clientset (default true)
      --enable-k8s-api-discovery         Enable discovery of Kubernetes API groups and resources with the discovery API
  -h, --help                             help for build-config
      --k8s-api-server string            Kubernetes API server URL
      --k8s-client-burst int             Burst value allowed for the K8s client
      --k8s-client-qps float32           Queries per second limit for the K8s client
      --k8s-heartbeat-timeout duration   Configures the timeout for api-server heartbeat, set to 0 to disable (default 30s)
      --k8s-kubeconfig-path string       Absolute path of the kubernetes kubeconfig file
      --node-name string                 The name of the node on which we are running. Also set via K8S_NODE_NAME environment. (default "ip-10-2-7-248.us-east-2.compute.internal")
      --source strings                   Ordered list of configuration sources. Supported values: config-map:<namespace>/name - a ConfigMap with <name>, optionally in namespace <namespace>. cilium-n
      Exit Code:    1
      Started:      Wed, 13 Sep 2023 23:12:52 +0200
      Finished:     Wed, 13 Sep 2023 23:13:57 +0200

```

The only way to discover what was wrong with the container was to ssh into the node and check the container logs:
```
[root@ip-10-2-7-248 ~]# cat /var/log/pods/kube-system_cilium-q2qj2_53c733be-3991-4666-be63-5eb5771df3c1/config/302.log 
2023-09-13T21:18:58.587524912Z stdout F Running
2023-09-13T21:18:58.58798195Z stderr F level=info msg=Invoked duration="413.966µs" function="cmd.glob..func36 (build-config.go:32)" subsys=hive
2023-09-13T21:18:58.58798824Z stderr F level=info msg=Starting subsys=hive
2023-09-13T21:18:58.587996421Z stderr F level=info msg="Establishing connection to apiserver" host="https://172.20.0.1:443" subsys=k8s-client
2023-09-13T21:19:33.602466142Z stderr F level=info msg="Establishing connection to apiserver" host="https://172.20.0.1:443" subsys=k8s-client
2023-09-13T21:20:03.606589434Z stderr F level=error msg="Unable to contact k8s api-server" error="Get \"https://172.20.0.1:443/api/v1/namespaces/kube-system\": dial tcp 172.20.0.1:443: i/o timeout" ipAddr="https://172.20.0.1:443" subsys=k8s-client
2023-09-13T21:20:03.606617845Z stderr F level=error msg="Start hook failed" error="Get \"https://172.20.0.1:443/api/v1/namespaces/kube-system\": dial tcp 172.20.0.1:443: i/o timeout" function="client.(*compositeClientset).onStart" subsys=hive
2023-09-13T21:20:03.606627126Z stderr F level=info msg=Stopping subsys=hive
2023-09-13T21:20:03.606629916Z stderr F Error: failed to start: Get "https://172.20.0.1:443/api/v1/namespaces/kube-system": dial tcp 172.20.0.1:443: i/o timeout
2023-09-13T21:20:03.607036561Z stdout F Usage:
2023-09-13T21:20:03.60704281Z stdout F   cilium build-config --node-name $K8S_NODE_NAME [flags]
2023-09-13T21:20:03.607044841Z stdout F 
2023-09-13T21:20:03.607046001Z stdout F Flags:
2023-09-13T21:20:03.607048302Z stdout F       --allow-config-keys strings        List of configuration keys that are allowed to be overridden (e.g. set from not the first source. Takes precedence over deny-config-keys
2023-09-13T21:20:03.607051002Z stdout F       --deny-config-keys strings         List of configuration keys that are not allowed to be overridden (e.g. set from not the first source. If allow-config-keys is set, this field is ignored
2023-09-13T21:20:03.607052282Z stdout F       --dest string                      Destination directory to write the fully-resolved configuration. (default "/tmp/cilium/config-map")
2023-09-13T21:20:03.607053502Z stdout F       --enable-k8s                       Enable the k8s clientset (default true)
2023-09-13T21:20:03.607054452Z stdout F       --enable-k8s-api-discovery         Enable discovery of Kubernetes API groups and resources with the discovery API
2023-09-13T21:20:03.607055352Z stdout F   -h, --help                             help for build-config
2023-09-13T21:20:03.607056242Z stdout F       --k8s-api-server string            Kubernetes API server URL
2023-09-13T21:20:03.607057182Z stdout F       --k8s-client-burst int             Burst value allowed for the K8s client
2023-09-13T21:20:03.607058372Z stdout F       --k8s-client-qps float32           Queries per second limit for the K8s client
2023-09-13T21:20:03.607059332Z stdout F       --k8s-heartbeat-timeout duration   Configures the timeout for api-server heartbeat, set to 0 to disable (default 30s)
2023-09-13T21:20:03.607060202Z stdout F       --k8s-kubeconfig-path string       Absolute path of the kubernetes kubeconfig file
2023-09-13T21:20:03.607062412Z stdout F       --node-name string                 The name of the node on which we are running. Also set via K8S_NODE_NAME environment. (default "ip-10-2-7-248.us-east-2.compute.internal")
2023-09-13T21:20:03.607065523Z stdout F       --source strings                   Ordered list of configuration sources. Supported values: config-map:<namespace>/name - a ConfigMap with <name>, optionally in namespace <namespace>. cilium-node-config:<NAMESPACE> - any CiliumNodeConfigs in namespace <NAMESPACE>.  node:<NODENAME> - Annotations on the node. Namespace and nodename are optional (default [config-map:cilium-config,cilium-node-config:kube-system])
2023-09-13T21:20:03.607069093Z stdout F 
2023-09-13T21:20:03.607070833Z stdout F Global Flags:
2023-09-13T21:20:03.607072903Z stdout F       --config string   Config file (default is $HOME/.cilium.yaml)
2023-09-13T21:20:03.607075083Z stdout F   -D, --debug           Enable debug messages
2023-09-13T21:20:03.607088164Z stdout F   -H, --host string     URI to server-side API
2023-09-13T21:20:03.607090224Z stdout F 
2023-09-13T21:20:03.607091824Z stdout F failed to start: Get "https://172.20.0.1:443/api/v1/namespaces/kube-system": dial tcp 172.20.0.1:443: i/o timeout

```

In here it was straightforward to understand what was wrong with the config container. In case of initialization failure we shouldn't print the help message as this can cause confusion to the user.

I didn't try the following command as suggested by [Debug Init Containers](https://kubernetes.io/docs/tasks/debug/debug-application/debug-init-containers/#accessing-logs-from-init-containers): `kubectl logs <pod-name> -c <init-container-2>`. It could probably give the same information without SSHing into the node but we still shouldn't print the help message for initialization problems.

### PR DESCRIPTION
**Pull request by vipul-21**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Use the `Fatalf` incase of error in buildconfig command to avoid help messages in the init failure

Fixes: #28158

### CODE REVIEW

**Review by asauber — APPROVED** [review]
Thanks for the PR. Would you mind adding `Fixes: #28158` to the commit message as well?

**Comment by vipul-21** [comment]
@asauber let me know if there is anything else I need to update to merge this.

**Pull request merged**
