### PR TITLE
bpf: Simplify and fix ENABLE_NAT46 dependencies

### PR DESCRIPTION
**Pull request by joestringer**
Update both the daemon configuration for NAT46 and the datapath code to
consistently check and use the same macros:

* Require ENABLE_IPV6 for ENABLE_NAT46.
* Userspace defines ENABLE_NAT46, and only if the prerequisites are set.
* Make the same prerequisite checks in the datapath in a simpler way.
* Make the datapath consistently use ENABLE_NAT46, not LXC_NAT46.
* Remove the ENABLE_NAT46 definition in lib/common.h which isn't used.
  (it couldn't be, because common.h is included before LXC_NAT46 is defined).

The only minor bug that's being fixed here is that it's previously possible to disable IPV6 but enable NAT46. I'm not sure what the current behaviour would be if this were attempted, but this patch attempts to disallow such a combination of configurations.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6680)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
> The only minor bug here is that it's possible to disable IPV6 but enable NAT46.

@joestringer Why is this? Can we not test for that permutation of options in the option library like you did for `pkg/option`?

**Comment by aanm** [comment]
please hold merging until #6653 is merged

**Comment by joestringer** [comment]
> @joestringer Why is this? Can we not test for that permutation of options in the option library like you did for pkg/option? 

Poor wording on my part, what I mean to say is that this is the bug that exists, and this PR fixes it in exactly the way you describe.

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Pull request merged**
