### PR TITLE
loader: clean up tcx bpf_links created by newer Cilium versions

### PR DESCRIPTION
**Pull request by ti-mo**
This PR represents the backportable part of https://github.com/cilium/cilium/pull/30103 and needs to be merged and backported independently in order for the downgrade path (and tests) to work.

```release-note
Remove tcx links created by Cilium 1.16 onwards
```

### CODE REVIEW

**Review by rgo3 — APPROVED** [review]

**Comment by rgo3** [comment]
Do we need a 1.13 backport? TCX will be released with 1.16, so only 1.15 and 1.14 need the downgrade path or did we change that policy?

**Comment by borkmann** [comment]
> Do we need a 1.13 backport? TCX will be released with 1.16, so only 1.15 and 1.14 need the downgrade path or did we change that policy?

No, 1.13 is not needed. Technically only 1.15 needs it.

**Review by borkmann — APPROVED** [review]

**Comment by ti-mo** [comment]
Had to make the `<device>/links` removal a bit less greedy since it was also removing existing xdp links that were created right before. `attachTCProgram` now only removes `<device>/links/cil_<prog>` before trying to attach it using netlink.

**Comment by giorio94** [comment]
👋 @ti-mo  Are you still planning on backporting this to v1.14?

**Comment by ti-mo** [comment]
> 👋 @ti-mo  Are you still planning on backporting this to v1.14?

Thanks for the ping, I didn't remove the label after Daniel's comment.

**Pull request merged**
