### PR TITLE
Various link fixes in documentation.

### PR DESCRIPTION
**Pull request by runiq**
**Summary of changes**: Fixes some outdated links in the docs to point to the correct location.

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-docs-please

**Review by nebril — APPROVED** [review]
LGTM, thanks a ton!

**Review by raybejjani — APPROVED** [review]
Thanks!

@tgraf just to confirm, we did retire the stable branch, right? and we are still on docs-1.0

**Review by borkmann — APPROVED** [review]
lgtm

**Pull request merged**
