### PR TITLE
terminology.rst: fixing 1 typo

### PR DESCRIPTION
**Pull request by didier-durand**
Hi there,
As per title.
Didier

### CODE REVIEW

**Review by errordeveloper — APPROVED** [review]
Thank you, well spotted!

**Comment by errordeveloper** [comment]
@didier-durand looks like you will need to re-open the PR against master add `needs-backport/1.9` label instead of targeting v1.9 branch directly. Please also make sure to sign-off you commit! Thanks a lot :)

**Comment by errordeveloper** [comment]
@didier-durand I spoke too soon, GitHub allows changing base-branch now, looks like a new feature... Could you please rebase the commit on master and make sure sign-off? No need to re-open :)

**Review by errordeveloper — CHANGES_REQUESTED** [review]
- rebase on master
- sign-off the commit

**Comment by didier-durand** [comment]
re-opened as https://github.com/cilium/cilium/pull/14181

**Comment by didier-durand** [comment]
> Thank you, well spotted!

@errordeveloper : you're very welcome. If I see more, I'll open other PRs

**Pull request closed without merging**
