### PR TITLE
bpf: pahole support and minor doc update

### PR DESCRIPTION
**Pull request by borkmann**
```release-note
pahole support for LLVM generated BPF object files
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5107)

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-docs-please

**Review by joestringer — APPROVED** [review]
Does this need elfutils < 0.173, or elfutils >= 0.173 (referring to the commit message)?

**Comment by borkmann** [comment]
The option -mattr=dwarfris is for elfutils < 0.173 in order to allow pahole to work. Later versions the dwarfris option doesn't matter since elfutils understands BPF relocs by then, but doesn't hurt either.

**Pull request merged**
