### PR TITLE
envoy: Update to release 1.17.1

### PR DESCRIPTION
**Pull request by jrajahalme**
Update Envoy to release 1.17.1.

All extensions not needed for Cilium policy enforcement are compiled out, leading to 45% smaller binary size (45.8 MB -> 25.6 MB).

Note for backporting: Only backport the first commit onto the main `Dockerfile` of the release branches.

Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

```release-note
Envoy is updated to release 1.17.1
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
4.9 known flake #13071

**Comment by jrajahalme** [comment]
Net-next known flake #12511

**Comment by jrajahalme** [comment]
retest-net-next

**Comment by jrajahalme** [comment]
rertest-4.9

**Comment by jrajahalme** [comment]
retest-4.9

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by jrajahalme** [comment]
retest-gke

**Comment by jrajahalme** [comment]
lifted `dont-merge/blocked` label until the quarantined TLS L7 test is checked out.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
retest-gke

**Comment by jrajahalme** [comment]
retest-1.20-4.9

**Comment by jrajahalme** [comment]
retest-1.13-netnext

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Quarantined TLS L7 CI test passed on local testing:
```
$ K8S_VERSION=1.19 ginkgo --focus="K8s.*TLS policy" -v -- -cilium.runQuarantined=true -cilium.holdEnvironment=true -cilium.provision=false
...
17:36:14 STEP: Testing L7 Policy with TLS
=== Test Finished at 2021-03-04T17:36:25-08:00====
...
Ginkgo ran 1 suite in 2m20.126306386s
Test Suite Passed
```

**Comment by jrajahalme** [comment]
retest-1.20-4.9

**Pull request merged**
