### PR TITLE
1.5 backports 2019 08 05 

### PR DESCRIPTION
**Pull request by jrfastab**
PR: #8710

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8789)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]
Seems straightforward, and I guess this is intentionally IPv4 only.

**Comment by jrfastab** [comment]
I left it as IPv4 only because the original block of code in v1.5 was IPv4 only.

**Comment by ianvernon** [comment]
test-missed-k8s

**Pull request merged**
