### PR TITLE
auth: fix fatal error: concurrent map iteration and map write

### LINKED ISSUE #33468: fatal error: concurrent map iteration and map write in github.com/cilium/cilium/pkg/auth
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

We have ran into the following errors when clusters load goes high and more pods are created, and it seems that there could be concurrency issue with ciliumIdentitiesDiscovered at https://github.com/cilium/cilium/blob/v1.15.6/pkg/auth/authmap_gc.go#L446. 

Let me know if we need anything else.

### Cilium Version

1.15.6

### Kernel Version

6.1.90

### Kubernetes Version

1.28

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell
2024-06-26T09:23:08.877430323Z stderr F fatal error: concurrent map iteration and map write
2024-06-26T09:23:08.88065491Z stderr F
2024-06-26T09:23:08.880679156Z stderr F goroutine 41516 [running]:
2024-06-26T09:23:08.880685482Z stderr F github.com/cilium/cilium/pkg/auth.(*authMapGarbageCollector).cleanupEndpoints(0x4000894000, {0x40011a0780?, 0x4001a105a0?})
2024-06-26T09:23:08.880690167Z stderr F         /go/src/github.com/cilium/cilium/pkg/auth/authmap_gc.go:446 +0x1c8
2024-06-26T09:23:08.880692956Z stderr F github.com/cilium/cilium/pkg/auth.(*authMapGarbageCollector).EndpointDeleted(0x4000894000, 0x403519c380, {0x78?, 0xcc?})
2024-06-26T09:23:08.8806955Z stderr F   /go/src/github.com/cilium/cilium/pkg/auth/authmap_gc.go:427 +0x7c
2024-06-26T09:23:08.880701678Z stderr F github.com/cilium/cilium/pkg/endpointmanager.(*endpointManager).removeEndpoint(0x4001ab7220, 0x4012a8cf18?, {0x0?, 0x0?})
2024-06-26T09:23:08.880704337Z stderr F         /go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:422 +0xf0
2024-06-26T09:23:08.880706774Z stderr F github.com/cilium/cilium/pkg/endpointmanager.(*endpointManager).RemoveEndpoint(0x4000349b90?, 0x4012a8cdd8?, {0xee?, 0x9e?})
2024-06-26T09:23:08.880714068Z stderr F         /go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:432 +0x30
2024-06-26T09:23:08.880716948Z stderr F github.com/cilium/cilium/daemon/cmd.(*Daemon).deleteEndpointQuiet(...)
2024-06-26T09:23:08.88072082Z stderr F  /go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:782
2024-06-26T09:23:08.880724439Z stderr F github.com/cilium/cilium/daemon/cmd.(*Daemon).deleteEndpoint(0x4001cf8000, 0x403519c380)
2024-06-26T09:23:08.880727327Z stderr F         /go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:764 +0x110
2024-06-26T09:23:08.880739126Z stderr F github.com/cilium/cilium/daemon/cmd.(*Daemon).deleteEndpointByContainerID(0x4001cf8000, {0x400d2346c0, 0x40})
2024-06-26T09:23:08.880741776Z stderr F         /go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:840 +0x424
2024-06-26T09:23:08.880744279Z stderr F github.com/cilium/cilium/daemon/cmd.deleteEndpointHandler(0x4001cf8000, {0x4015d68100, 0x4000fccc20})
2024-06-26T09:23:08.880746658Z stderr F         /go/src/github.com/cilium/cilium/daemon/cmd/endpoint.go:138 +0x1e8
2024-06-26T09:23:08.880749029Z stderr F github.com/cilium/cilium/daemon/cmd.(*apiHandler[...]).Handle(0x2dad200, {0x4015d68100?, 0x4000fccc20?})
2024-06-26T09:23:08.880751524Z stderr F         /go/src/github.com/cilium/cilium/daemon/cmd/api_handlers.go:109 +0x8c
2024-06-26T09:23:08.880766662Z stderr F github.com/cilium/cilium/api/v1/server/restapi/endpoint.(*DeleteEndpoint).ServeHTTP(0x4006248438, {0x38fcab0, 0x400a4b0bb8}, 0x4015d68100)
2024-06-26T09:23:08.880770633Z stderr F         /go/src/github.com/cilium/cilium/api/v1/server/restapi/endpoint/delete_endpoint.go:58 +0x13c
2024-06-26T09:23:08.880776311Z stderr F github.com/go-openapi/runtime/middleware.(*Context).RoutesHandler.NewOperationExecutor.func1({0x38fcab0, 0x400a4b0bb8}, 0x4015d68100)
2024-06-26T09:23:08.880778953Z stderr F         /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x5c
2024-06-26T09:23:08.880781332Z stderr F net/http.HandlerFunc.ServeHTTP(0x4012a8d9d8?, {0x38fcab0?, 0x400a4b0bb8?}, 0x7?)
2024-06-26T09:23:08.880784647Z stderr F         /usr/local/go/src/net/http/server.go:2136 +0x38
2024-06-26T09:23:08.880787051Z stderr F github.com/go-openapi/runtime/middleware.NewRouter.func1({0x38fcab0, 0x400a4b0bb8}, 0x400c317f00)
2024-06-26T09:23:08.88079204Z stderr F  /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/router.go:78 +0x1c4
2024-06-26T09:23:08.8807946Z stderr F net/http.HandlerFunc.ServeHTTP(0x4012a8d918?, {0x38fcab0?, 0x400a4b0bb8?}, 0x27ba0?)
2024-06-26T09:23:08.880799449Z stderr F         /usr/local/go/src/net/http/server.go:2136 +0x38
2024-06-26T09:23:08.880801951Z stderr F github.com/go-openapi/runtime/middleware.Redoc.func1({0x38fcab0, 0x400a4b0bb8}, 0x4012a8d998?)
2024-06-26T09:23:08.880804413Z stderr F         /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0x1f4
2024-06-26T09:23:08.880809229Z stderr F net/http.HandlerFunc.ServeHTTP(0x4012a8d9b8?, {0x38fcab0?, 0x400a4b0bb8?}, 0x1f7ac?)
2024-06-26T09:23:08.880814333Z stderr F         /usr/local/go/src/net/http/server.go:2136 +0x38
2024-06-26T09:23:08.880816844Z stderr F github.com/go-openapi/runtime/middleware.Spec.func1({0x38fcab0, 0x400a4b0bb8}, 0x4005659701?)
2024-06-26T09:23:08.880822045Z stderr F         /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/spec.go:45 +0x168
2024-06-26T09:23:08.88082952Z stderr F net/http.HandlerFunc.ServeHTTP(0x4005659740?, {0x38fcab0?, 0x400a4b0bb8?}, 0x3?)
2024-06-26T09:23:08.88083222Z stderr F  /usr/local/go/src/net/http/server.go:2136 +0x38
2024-06-26T09:23:08.880843337Z stderr F github.com/cilium/cilium/pkg/metrics.(*APIEventTSHelper).ServeHTTP(0x403ef0e7b0, {0x38fd270?, 0x403aaae700}, 0x400c317f00)
2024-06-26T09:23:08.88087112Z stderr F  /go/src/github.com/cilium/cilium/pkg/metrics/middleware.go:63 +0x1b8
2024-06-26T09:23:08.880878348Z stderr F github.com/cilium/cilium/pkg/api.(*APIPanicHandler).ServeHTTP(0x10?, {0x38fd270?, 0x403aaae700?}, 0x403aaae700?)
2024-06-26T09:23:08.880881917Z stderr F         /go/src/github.com/cilium/cilium/pkg/api/apipanic.go:42 +0x68
2024-06-26T09:23:08.880884978Z stderr F net/http.serverHandler.ServeHTTP({0x38eeb70?}, {0x38fd270?, 0x403aaae700?}, 0x6?)
2024-06-26T09:23:08.880888104Z stderr F         /usr/local/go/src/net/http/server.go:2938 +0xbc
2024-06-26T09:23:08.880893675Z stderr F net/http.(*conn).serve(0x403f6cd7a0, {0x3912200, 0x403de5d530})
2024-06-26T09:23:08.880899099Z stderr F         /usr/local/go/src/net/http/server.go:2009 +0x518
2024-06-26T09:23:08.880901634Z stderr F created by net/http.(*Server).Serve in goroutine 14244
2024-06-26T09:23:08.88090988Z stderr F  /usr/local/go/src/net/http/server.go:3086 +0x4cc
2024-06-26T09:23:08.880912218Z stderr F
2024-06-26T09:23:08.880917765Z stderr F goroutine 1 [select, 2 minutes]:
2024-06-26T09:23:08.880923172Z stderr F github.com/cilium/cilium/pkg/hive.(*Hive).waitForSignalOrShutdown(0x40005880a0)
2024-06-26T09:23:08.880925707Z stderr F         /go/src/github.com/cilium/cilium/pkg/hive/hive.go:232 +0x100
2024-06-26T09:23:08.880928111Z stderr F github.com/cilium/cilium/pkg/hive.(*Hive).Run(0x40005880a0)
2024-06-26T09:23:08.880933387Z stderr F         /go/src/github.com/cilium/cilium/pkg/hive/hive.go:216 +0xd8
2024-06-26T09:23:08.880938762Z stderr F github.com/cilium/cilium/daemon/cmd.NewAgentCmd.func1(0x4000a62900?, {0x32f8d75?, 0x4?, 0x32f8be1?})
...
```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Fixes: #33468

```release-note
auth: fix fatal error: concurrent map iteration and map write
```

### CODE REVIEW

**Review by youngnick — APPROVED** [review]
Nice catch, thanks @chaunceyjiang!

**Comment by shk3** [comment]
Oh hey, thanks for the fix, @chaunceyjiang !!

**Pull request merged**
