### PR TITLE
v1.9 backports 2021-03-19

### PR DESCRIPTION
**Pull request by jrajahalme**
* #14488 -- Bugtool: route tables dynamically dumped (@youssefazrak)
 * #14568 -- Bugtool: add taskset  (@youssefazrak)
 * #15228 -- endpoint: Fix the initialization of endpoints' datapath configs (@pchaigno)
 * #15328 -- contrib: fix remote overriding (@kaworu)
 * #15323 -- docs: adds a rancher kubernetes engine installation guide (@seanmwinn)
 * #15365 -- Documentation: fix key rotation command in encryption guide (@mauriciovasquezbernal)
 * #15363 -- bugtool: dump iptables-legacy and iptables-nft (@h3llix)

Once this PR is merged, you can update the PR labels via:
```upstream-prs
$ for pr in 14488 14568 15228 15328 15323 15365 15363; do contrib/backporting/set-labels.py $pr done 1.9; done
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-backport-1.9

**Review by pchaigno — APPROVED** [review]
My PR looks good :+1:

**Comment by jrajahalme** [comment]
test-1.19-4.9 hit a known flake #6728

**Review by aditighag — APPROVED** [review]
>bpf: Skip policy enforcements for service loopback case
LGTM

**Comment by jrajahalme** [comment]
retest-1.19-4.9

**Review by kaworu — APPROVED** [review]
LGTM for my patch, thank you!

**Comment by joestringer** [comment]
@jrajahalme other than looking into the sysdump attached to the failure (See the "Artifacts" box above the output results box here: https://github.com/cilium/cilium/pull/15399/checks?check_run_id=2167272770), in the past I have looked up the specific action and just iterated through the instructions to run the same steps. I think it's typically just a matter of pointing kind towards the right config file under .github and running a few more commands.

I'd like if it were a bit easier, but I think the above is workable?

**Comment by jrajahalme** [comment]
> @jrajahalme other than looking into the sysdump attached to the failure (See the "Artifacts" box above the output results box here: https://github.com/cilium/cilium/pull/15399/checks?check_run_id=2167272770), in the past I have looked up the specific action and just iterated through the instructions to run the same steps. I think it's typically just a matter of pointing kind towards the right config file under .github and running a few more commands.
> 
> I'd like if it were a bit easier, but I think the above is workable?

Just did that, run kind locally using the same steps as in .github file, and it succeeded (cubedns became available long before the 5m timeout).

**Comment by jrajahalme** [comment]
Could the fact that the smoke-test yaml is running 5 jobs in parallel be a factor? Are they all run in the same VM?
If so then relaxing the timeout from 5m to 10m might help?

**Comment by jrajahalme** [comment]
test-backport-1.9

**Review by joestringer — APPROVED** [review]

**Comment by pchaigno** [comment]
Closed and reopened to trigger the GitHub actions.

**Comment by jrajahalme** [comment]
IPv4 version of smoke-test/conformance test keeps failing for the same reason, coredns container stuck on `ContainerCreating`:
```
            "status": {
                "conditions": [
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2021-03-24T08:51:06Z",
                        "status": "True",
                        "type": "Initialized"
                    },
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2021-03-24T08:51:06Z",
                        "message": "containers with unready status: [coredns]",
                        "reason": "ContainersNotReady",
                        "status": "False",
                        "type": "Ready"
                    },
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2021-03-24T08:51:06Z",
                        "message": "containers with unready status: [coredns]",
                        "reason": "ContainersNotReady",
                        "status": "False",
                        "type": "ContainersReady"
                    },
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2021-03-24T08:51:01Z",
                        "status": "True",
                        "type": "PodScheduled"
                    }
                ],
                "containerStatuses": [
                    {
                        "image": "k8s.gcr.io/coredns:1.7.0",
                        "imageID": "",
                        "lastState": {},
                        "name": "coredns",
                        "ready": false,
                        "restartCount": 0,
                        "started": false,
                        "state": {
                            "waiting": {
                                "reason": "ContainerCreating"
                            }
                        }
                    }
                ],
                "hostIP": "172.18.0.3",
                "phase": "Pending",
                "qosClass": "Burstable",
                "startTime": "2021-03-24T08:51:06Z"
            }
```

**Comment by jrajahalme** [comment]
@joestringer Do we have access to kubelet logs on failed GH actions? Anything else I could look into?

**Comment by pchaigno** [comment]
We also have the k8s events. The last messages for the CoreDNS pods are:
```
(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox \"cf2fed496930a0d91f3f21f6c7825b89df08581607f9c66fcff36193978fa519\": Unable to create endpoint: Cilium API client timeout exceeded
(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox \"ba5551d718be4b94ce880fd423e8254dd576ae825481a4b32e6361a67725c058\": Unable to create endpoint: Cilium API client timeout exceeded
```
Maybe worth trying to bisect since only two commits actually changed the Cilium code (mine and Aditi's)?

**Comment by jrajahalme** [comment]
@pchaigno Bisecting on another pr: https://github.com/cilium/cilium/pull/15470, rolled back 4 commits. The failing test succeeded locally with all the commits in though.

**Comment by jrajahalme** [comment]
Found on the Cilium agent logs of the failing test:
```
2021-03-24T08:50:45.136837385Z level=error msg="Command execution failed" cmd="[iptables -t mangle -n -L CILIUM_PRE_mangle]" error="exit status 1" subsys=iptables
2021-03-24T08:51:28.846113523Z level=error msg="Command execution failed" cmd="[tc filter replace dev lxc_health ingress prio 1 handle 1 bpf da obj 3040_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader
2021-03-24T08:51:28.858208384Z level=error msg="Error while rewriting endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3040 error="Failed to load tc filter: exit status 1" identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-03-24T08:51:28.858717591Z level=error msg="endpoint regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3040 error="Failed to load tc filter: exit status 1" identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-03-24T08:51:47.502112157Z level=error msg="Command execution failed" cmd="[tc filter replace dev lxc20d0fd01bec3 ingress prio 1 handle 1 bpf da obj 731_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader
2021-03-24T08:51:47.504477987Z level=error msg="Error while rewriting endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=731 error="Failed to load tc filter: exit status 1" identity=22009 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-03-24T08:51:47.505101095Z level=error msg="endpoint regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=731 error="Failed to load tc filter: exit status 1" identity=22009 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-03-24T08:52:09.797732721Z level=error msg="Command execution failed" cmd="[tc filter replace dev lxc5b2ed8d3a457 ingress prio 1 handle 1 bpf da obj 1950_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader
2021-03-24T08:52:09.941663256Z level=error msg="Error while rewriting endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=1950 error="Failed to load tc filter: exit status 1" identity=8650 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-03-24T08:52:09.941702756Z level=error msg="endpoint regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=1950 error="Failed to load tc filter: exit status 1" identity=8650 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-03-24T08:52:28.483418240Z level=error msg="Command execution failed" cmd="[tc filter replace dev lxc_health ingress prio 1 handle 1 bpf da obj 3040_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader
2021-03-24T08:52:28.494170377Z level=error msg="Error while rewriting endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3040 error="Failed to load tc filter: exit status 1" identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-03-24T08:52:28.494532381Z level=error msg="endpoint regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3040 error="Failed to load tc filter: exit status 1" identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-03-24T08:52:50.023309719Z level=error msg="Command execution failed" cmd="[tc filter replace dev lxc20d0fd01bec3 ingress prio 1 handle 1 bpf da obj 731_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader
2021-03-24T08:52:50.030387209Z level=error msg="Error while rewriting endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=731 error="Failed to load tc filter: exit status 1" identity=22009 ipv4= ipv6= k8sPodName=/ subsys=endpoint
... (200 more level=error lines like this)
```

**Comment by jrajahalme** [comment]
One full repeating set of logs (for different endpoints):
```
2021-03-24T08:51:28.846113523Z level=error msg="Command execution failed" cmd="[tc filter replace dev lxc_health ingress prio 1 handle 1 bpf da obj 3040_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader
2021-03-24T08:51:28.846154723Z level=warning msg="Log buffer too small to dump verifier log 16777215 bytes (10 tries)!" subsys=datapath-loader
2021-03-24T08:51:28.846166423Z level=warning msg="JIT disabled, but 1/5 tail call maps in the program have JITed owner!" subsys=datapath-loader
2021-03-24T08:51:28.846171524Z level=warning msg="Error fetching program/map!" subsys=datapath-loader
2021-03-24T08:51:28.846176124Z level=warning msg="Unable to load program" subsys=datapath-loader
2021-03-24T08:51:28.858065082Z level=warning msg="JoinEP: Failed to load program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3040 error="Failed to load tc filter: exit status 1" file-path=3040_next/bpf_lxc.o identity=4 ipv4= ipv6= k8sPodName=/ subsys=datapath-loader veth=lxc_health
2021-03-24T08:51:28.858208384Z level=error msg="Error while rewriting endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3040 error="Failed to load tc filter: exit status 1" identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-03-24T08:51:28.858317485Z level=warning msg="generating BPF for endpoint failed, keeping stale directory." containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3040 file-path=3040_next_fail identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-03-24T08:51:28.858506788Z level=warning msg="Regeneration of endpoint failed" bpfCompilation=3.333051289s bpfLoadProg=32.039088613s bpfWaitForELF=3.333218091s bpfWriteELF="254.004µs" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3040 error="Failed to load tc filter: exit status 1" identity=4 ipv4= ipv6= k8sPodName=/ mapSync="38.401µs" policyCalculation="58.601µs" prepareBuild="301.604µs" proxyConfiguration="9µs" proxyPolicyCalculation="17.3µs" proxyWaitForAck=0s reason="updated security labels" subsys=endpoint total=35.374685036s waitingForCTClean="486.707µs" waitingForLock="9.6µs"
2021-03-24T08:51:28.858717591Z level=error msg="endpoint regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3040 error="Failed to load tc filter: exit status 1" identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
```

**Comment by jrajahalme** [comment]
Looks like none-of the endpoints can be regenerated, coredns is just the first one being verified in the test script?

**Comment by jrajahalme** [comment]
#### Endpoint list

```
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                      IPv6   IPv4           STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                                         
918        Disabled           Disabled          22009      k8s:io.cilium.k8s.policy.cluster=default                                                10.244.1.13    regenerating            
                                                           k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                                                
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                                                    
                                                           k8s:k8s-app=kube-dns                                                                                                           
3613       Disabled           Disabled          1          reserved:host                                                                                          ready                   
3828       Disabled           Disabled          4          reserved:health                                                                         10.244.1.89    waiting-to-regenerate   
3837       Disabled           Disabled          8650       k8s:app=local-path-provisioner                                                          10.244.1.120   regenerating            
                                                           k8s:io.cilium.k8s.policy.cluster=default                                                                                       
                                                           k8s:io.cilium.k8s.policy.serviceaccount=local-path-provisioner-service-account                                                 
                                                           k8s:io.kubernetes.pod.namespace=local-path-storage                                                                             
```

**Comment by jrajahalme** [comment]
Removed #15321 -- bpf: Skip policy enforcements for service loopback case (@aditighag) as it appears to have caused the smoke-test/conformance-test failure.

**Comment by jrajahalme** [comment]
test-backport-1.9

**Comment by pchaigno** [comment]
Arf! That's a complexity issue again.

**Comment by jrajahalme** [comment]
> Arf! That's a complexity issue again.

It's curious that this only happened in that one test, everything else passed. Must be a unique kernel/cilium config combo?

**Comment by jrajahalme** [comment]
Pulled the non-backport PR that doubled a test timeout.

**Comment by jrajahalme** [comment]
test-backport-1.9

**Comment by pchaigno** [comment]
> It's curious that this only happened in that one test, everything else passed. Must be a unique kernel/cilium config combo?

Most likely because it's the only test running on 5.4.

**Comment by aditighag** [comment]
> > It's curious that this only happened in that one test, everything else passed. Must be a unique kernel/cilium config combo?
> 
> 
> 
> Most likely because it's the only test running on 5.4.

So all the other tests on older and newer kernels passed? 😕

**Pull request merged**
